### ISSUE TITLE
comparitech.com: ads

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#21719]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.comparitech.com/blog/information-security/pgp-encryption-gmail/`

### Category

ads

### Description

An ad banner appears in the right. Tried this fiter but the image reappears:
||cdn.comparitech.com/wp-content/themes/comparitech-2018/images/320x100_Incogni_cyber_security.png

### Other extensions used

none

### Screenshot(s)

<img width="1468" alt="Screenshot 2024-01-01 at 21 47 50" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/3bf3de2e-21aa-4bf1-8df0-21aff6b6a264">

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 113879
 cosmetic: 44176
 scriptlet: 18524
 html: 1981
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  dpollock-0: 11620-4, now
 default:
  user-filters: 17-0, never
  ublock-filters: 37037-289, now
  ublock-badware: 7729-11, now
  ublock-privacy: 951-0, now
  ublock-unbreak: 2219-0, now
  ublock-quick-fixes: 169-1, now
  easylist: 76530-395, now
  easyprivacy: 33212-182, now
  urlhaus-1: 10045-0, now
filterset (user): [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 339 ms
 maxAssetCacheWait: 84 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`comparitech.com##.promo.box`


@ryanbr
