### ISSUE TITLE
hitjankari.com: detection

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#21711]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hitjankari.com/?lid=WUyFUw&pid=934986&plid=1&vid=263075431`

### Category

detection

### Description

uBlock origin is detected. Note: I am making this issue becuase someone reported the detection in the subreddit and they didn't make an issue here.
Note 2: I was able to remove the popup and the overlay with these filters: 
hitjankari.com##.adb-animate.adb-popup
hitjankari.com##.adb-overlay

### Other extensions used

none 

### Screenshot(s)

<img width="1468" alt="Screenshot 2024-01-01 at 12 17 04" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/1ddacc8b-b8ce-4888-85c5-e042c62ebcc0">

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 115963
 cosmetic: 44161
 scriptlet: 18514
 html: 1981
listset (total-discarded, last-updated):
 added:
  dpollock-0: 11620-467, now
 default:
  user-filters: 17-0, never
  ublock-filters: 37010-206, now
  ublock-badware: 7729-11, now
  ublock-privacy: 951-0, now
  ublock-unbreak: 2219-1, now
  ublock-quick-fixes: 169-0, now
  easylist: 76509-839, now
  easyprivacy: 33212-888, now
  urlhaus-1: 9960-0, now
  plowe-0: 3784-1, now
filterset (user): [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 244 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 8
 network:
  botman.ninja: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 3
```
</details>

**Comment by Dani-1-2** [comment]
@okiehsch The issue persists. I have updated the filter lists.

**Comment by Dani-1-2** [comment]
@ItsProfessional  I have done all of this and the issue still persists.

**Comment by Dani-1-2** [comment]
My own filter worked when it was enabled

**Comment by okiehsch** [comment]
`hitjankari.com` is a site used by url-shorteners.

What is the shortener link you used, or are you saying that you went to
`https://hitjankari.com/?lid=WUyFUw&pid=934986&plid=1&vid=263075431`
directly?

**Comment by Dani-1-2** [comment]
> `hitjankari.com` is a site used by url-shorteners.
> 
> What is the shortener link you used, or are you saying that you went to `https://hitjankari.com/?lid=WUyFUw&pid=934986&plid=1&vid=263075431` directly?

Correct, I went to it directly.

**Comment by okiehsch** [comment]
Ok, then our filters won't work,
These kind of sites don't have any "content" they are solely used for redirection purposes.
Usually nobody goes directly to such a site.

**Comment by Dani-1-2** [comment]
> Ok, then our filters won't work, These kind of sites don't have any "content" they are solely used for redirection purposes. Usually nobody goes directly to such a site.

I visited it directly because someone sent a link to it in the subreddit and they said that it got detected.

**Comment by Dani-1-2** [comment]
@okiehsch Does this mean that if I don't visit the link directly uBlock origin will not be detected?

**Comment by okiehsch** [comment]
If you use a shortener link that redirects through `hitjankari.com` you should not get detected on that site.
