### ISSUE TITLE
mobiel.de: breakage

### ISSUE THREAD

**Issue by JayAige** [uBlockOrigin/uAssets#21714]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mobiel.de/fahrplaene/fahrplanauskunft/verbindung-finden/`

### Category

breakage

### Description

"Sorry, something went wrong. Try reloading or going back to the previous page and reloading." Maybe because of blocking 'anwendungen.stadtwerke-bielefeld.de'

### Other extensions used

HTTPS everywhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 107417
 cosmetic: 48997
 scriptlet: 18524
 html: 1981
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37027-302, 6m
  ublock-badware: 7729-11, 6m
  ublock-privacy: 950-0, 6m
  ublock-unbreak: 2219-0, 6m
  easylist: 76509-553, 6m
  easyprivacy: 33212-863, 6m
  plowe-0: 3784-1, now
  DEU-0: 7244-3, 6m
  urlhaus-1: 9960-0, 6m
  ublock-quick-fixes: 169-1, 6m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1394 ms
 maxAssetCacheWait: 701 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  stadtwerke-bielefeld.de: 2
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce.

<details>
<summary>Screenshot(s)</summary>


![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/53f1fffd-f8b7-44d4-b5f1-c9d89a3d8080)

</details>

**Comment by mapx-** [comment]
@JayAige 

- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
