### ISSUE TITLE
cinedoblego.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2172]
URL(s) where the issue occurs

`https://www.cinedoblego.com/the-dragon-spell-2016/`

Describe the issue

![](https://i.imgur.com/CgjsQwP.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.2

Settings

Default

**Comment by mapx-** [comment]
No difference even disabling uBo

**Comment by KiLL4FuNK** [comment]
you have to open the link

**Comment by mapx-** [comment]
test this filter
`@@||sitiosywebs.com/adframe.js$script,first-party`

**Comment by KiLL4FuNK** [comment]
that page blocked me and I have to wait 24 hours and it does not let me see the link

**Comment by KiLL4FuNK** [comment]
You can close the theme if you want

**Comment by lain566** [comment]
Suggested filter
`||flag.catalogointeractivo.com/getData.php$xmlhttprequest`

Test link
`https://www.cinedoble.tv/26221/bajar-seleccion-canina-2014-hd-latino-gratis.html`

![e15432cd-07ae-4454-a845-9a15469caeb8](https://user-images.githubusercontent.com/27441315/52525261-34e38f80-2ca7-11e9-864e-13edd38dfdd7.png)
