### ISSUE TITLE
bricoman.fr: breakage

### ISSUE THREAD

**Issue by guiled** [uBlockOrigin/uAssets#21721]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bricoman.fr/`

### Category

breakage

### Description

Click on the search field, a popin should appear.

### Other extensions used

ghostery, duckduckgo extension.

### Screenshot(s)

nothing

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 124342
 cosmetic: 53289
 scriptlet: 18663
 html: 1981
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37044-280, now
  ublock-badware: 7729-11, now
  ublock-privacy: 951-0, now
  ublock-unbreak: 2219-1, now
  ublock-quick-fixes: 169-0, now
  easylist: 76530-736, now
  easyprivacy: 33212-812, now
  urlhaus-1: 10045-0, now
  plowe-0: 3784-1, now
  FRA-0: 28985-336, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 204 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 4
 network:
  datadome.co: 1
  googletagmanager.com: 1
  sensefuel.live: 2
```
</details>

**Comment by okiehsch** [comment]
Borken by `EasyPrivacy`.
`@@||tag.search.sensefuel.live/tag/*$script,domain=bricoman.fr`
fixes the issue on my end.
@ryanbr
