### ISSUE TITLE
honkailab.com: breakage

### ISSUE THREAD

**Issue by xnusnim** [uBlockOrigin/uAssets#21727]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

## explanation
- The website broken when ubo is activated without touching anything.
## screen shot
<img width="1512" alt="스크린샷 2024-01-02 오전 11 51 35" src="https://github.com/uBlockOrigin/uBlock-issues/assets/81290656/a2211491-04c8-4014-ae7d-93dcf1b5b375">

### A specific URL where the issue occurs.

`https://honkailab.com/`

### Steps to Reproduce

1. active the uBO extension.
2. enter the honkailab.com website.
3. the web site is broken.

### Expected behavior

I expected ads are blocked

### Actual behavior

But website is broken..

### uBO version

1.54.0

### Browser name and version

firefox / 121.0 (latest version)

### Operating System and version

mac / 14.2.1

**Comment by piquark6046** [comment]
@MasterKia It is related to Ad-Shield.

**Comment by piquark6046** [comment]
For more information, please refer https://github.com/AdguardTeam/AdguardFilters/issues/167048.

**Comment by JobcenterTycoon** [comment]
Works fine for me.

But the site is protected by "Ad-Shield". Also fake "breakage" can appear.
**For the best blocking results try --> [microShield](https://github.com/List-KR/microShield) <--. Its a special userscript designed to block Ad-Shield related ads.**

**Comment by xnusnim** [comment]
@JobcenterTycoon 
If you wait for about 15 seconds on the website, an error occurs that breaks the screen.
These problems are likely to cause users to leave.
I will use microShield, but please do not experience problems for users.

**Comment by piquark6046** [comment]
The userscript is not installed in uBO.
And, the anti-adblock script of Ad-Shield lies users that an adblocker breaks the webpage.

**Comment by JobcenterTycoon** [comment]
I can’t reproduce the breakage. Seems to be mapx- and MasterKia also can't. So it seems to be a rare problem and microShield is the best solution for Ad-Shield protected sites so far.

**Comment by xnusnim** [comment]
Have you tried reproducing it in Firefox?
It only happens in Firefox.

**Comment by JobcenterTycoon** [comment]
Sure.
