### ISSUE TITLE
msn.com: breakage

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#21731]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.msn.com/en-in/autos/photos/invitations-only-to-those-ram-temple-chief-priest-responds-to-uddhav-s-no-invite-remark/ar-AA1miv8s?ocid=msedgntp&pc=IERDSP&cvid=f45306b4ff2b4056990e4bee0a85d634&ei=14`

### Description

video is blocked 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (270)](https://github.com/uBlockOrigin/uAssets/assets/20338483/fa3e66bb-c2bb-4995-9265-c956e801d9a0)

</details>

### Configuration

uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105071
 cosmetic: 44176
 scriptlet: 19868
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-1, never
  easylist: 76533-15, 49m
  easyprivacy: 33178-65, 2d.8h.28m
  plowe-0: 3784-1154, 2d.8h.28m
  ublock-badware: 7725-137, 2d.8h.28m
  ublock-filters: 36441-217, 1h.14m
  ublock-privacy: 954-8, 2d.8h.28m
  ublock-quick-fixes: 154-48, 1h.14m
  ublock-unbreak: 2176-31, 2d.8h.28m
  urlhaus-1: 9985-0, 7h.26m
filterset (user): [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 2422 ms (selfie)
 maxAssetCacheWait: 432 ms
popupPanel:
 blocked: 72
 network:
  msn.com: 49
  adnxs.com: 7
  azure.com: 2
  btloader.com: 1
  scorecardresearch.com: 13
 extended:
  ##.articlePage_bannerAd_wrapper-DS-EntryPoint1-1
  ##.intra-article-ad-full
  ##[class^="articlePage_eoabContent"]
  ##above-river-block
  ##div[class^="articlePage_topBannerAdContainer_"]
  ##display-ads
  ##.ad-slot-placeholder
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)

**Comment by gorhill** [comment]
> may be that element inside open shadow root

Yes, it is.

**Comment by ave9858** [comment]
Getting stuck on white screen, example URL `https://www.msn.com/en-au/news/other/impeach-expand-investigate-how-democrats-in-congress-are-trying-to-rein-in-the-supreme-court/ar-BB1pq6j4`, tested on Mull Browser, troubleshooting info:

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 140428
 cosmetic: 55374
 scriptlet: 20246
 html: 1856
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39580-113, now
  ublock-badware: 8792-1, now
  ublock-privacy: 1024-4, now
  ublock-unbreak: 2429-2, now
  ublock-quick-fixes: 122-5, now
  adguard-mobile: 9563-74, now
  easylist: 86491-239, now
  easyprivacy: 52710-73, now
  urlhaus-1: 15380-5, now
  plowe-0: 3543-1061, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2772 ms
 maxAssetCacheWait: 326 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  msn.com: 10
  adnxs.com: 5
  duckduckgo.com: 3
 extended:
  ##+js(json-prune-fetch-response, properties.componentConfigs.sli…
  ##+js(json-prune-fetch-response, *, list.*.link.ad list.*.link.k…
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
```
</details>
<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 139030
 cosmetic: 47494
 scriptlet: 20181
 html: 1856
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
 default:
  user-filters: 0-0, never
  ublock-filters: 39580-113, 6m
  ublock-badware: 8792-1, 6m
  ublock-privacy: 1024-4, 6m
  ublock-unbreak: 2429-2, 6m
  ublock-quick-fixes: 122-5, 6m
  easylist: 86491-175, 6m
  easyprivacy: 52710-65, 6m
  urlhaus-1: 15380-5, 6m
  plowe-0: 3543-987, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2772 ms
 maxAssetCacheWait: 326 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  msn.com: 14
  adnxs.com: 5
 extended:
  ##+js(json-prune-fetch-response, properties.componentConfigs.sli…
  ##+js(json-prune-fetch-response, *, list.*.link.ad list.*.link.k…
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
```
</details>

**Comment by stephenhawk8054** [comment]
Does it work in normal Firefox?

**Comment by ave9858** [comment]
> @ave9858 Does it work in normal Firefox?

Don't have it installed, I'll try

**Comment by ave9858** [comment]
Can't reproduce with stock Firefox with uBO, or Mull with uBO off. Seems the combination of uBO and Mull causes the issue, I'll try to investigate more but I'm confused on what could be causing this

**Comment by stephenhawk8054** [comment]
@ave9858 Backup uBO configurations, reset uBO to default settings, turn off all other extensions, restart the browser and test again.

**Comment by ave9858** [comment]
> @ave9858 Backup your uBO configurations, reset uBO to default settings, turn off all other extensions, restart the browser and test again.

I reset Mull before testing, and attached the troubleshooting info above. There's two pasted, one right after reset with uBO default config and one with adguard mobile manually disabled with no other changes. I've also narrowed down the list to only easylist but finding the exact filter causing this change is difficult for me on mobile.

**Comment by stephenhawk8054** [comment]
@ave9858 Can you test this filter?

```adb
@@||assets.msn.com/resolver/api/resolve/v3/config/?$xhr,1p
```

**Comment by ave9858** [comment]
> @ave9858 Can you test this filter?
> 
> ```
> @@||assets.msn.com/resolver/api/resolve/v3/config/?$xhr,1p
> ```

Works, thank you

**Comment by stephenhawk8054** [comment]
Normal Firefox blocks the same connections but still works normally so I don't know what's wrong with Mull.
