### ISSUE TITLE
spreaker.com: ads

### ISSUE THREAD

**Issue by jag176** [uBlockOrigin/uAssets#21730]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.
`https://www.spreaker.com/user/17034015/deadlock227`

### Description

Ads inserted into audio after trying to play or download. Does not occur if VPN is used to change location to Russia

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 287771
 cosmetic: 178381
 scriptlet: 46717
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28253-29, 1d.20h
  adguard-generic: 81602-487, 1d.20h
  adguard-mobile: 8950-48, 1d.20h.2m
  adguard-mobile-app-banners: 4868-10, 1d.20h.2m
  adguard-other-annoyances: 13992-9, 1d.20h.2m
  adguard-popup-overlays: 26728-93, 1d.20h.1m
  adguard-social: 22155-927, 1d.20h
  adguard-spyware: 82406-1219, 1d.20h
  adguard-spyware-url: 1381-5, 1d.20h.1m
  adguard-widgets: 2388-6, 1d.20h.1m
  block-lan: 55-0, 9d.21h.5m
  curben-phishing: 79644-20, 17h.59m
  [4 lists not shown]: [too many]
 default:
  user-filters: 85-0, never
  easylist: 76531-2067, 2h.58m
  easyprivacy: 33212-16466, 2h.58m
  plowe-0: 3787-1663, 9d.21h.5m
  ublock-badware: 7555-324, 4d.20h.26m
  ublock-filters: 36418-3938, 4d.20h.26m
  ublock-privacy: 955-386, 2h.58m
  ublock-quick-fixes: 157-18, 2h.58m
  ublock-unbreak: 2176-148, 4d.20h.26m
  urlhaus-1: 10045-0, 17h.58m
filterset (user): [array of 86 redacted]
trustedset:
 added: [array of 15 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 hyperlinkAuditingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2352 ms
 maxAssetCacheWait: 1461 ms
```
</details>

**Comment by mapx-** [comment]
What country did you test the site from?

**Comment by jag176** [comment]
> What country did you test the site from?

Canada

**Comment by mapx-** [comment]
it seems to be included in the normal stream

**Comment by jag176** [comment]
> it seems to be included in the normal stream

But it's not in if I change location to Russia

**Comment by stephenhawk8054** [comment]
Looks like they serve `.mp3` files as audios. If they distribute different `.mp3` files depending on the region, I doubt uBO can do anything.
