### ISSUE TITLE
platform.ledn.io: breakage

### ISSUE THREAD

**Issue by harsha-venugopal-ledn** [uBlockOrigin/uAssets#21734]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://platform.ledn.io/`

### Category

breakage

### Description

Hi There,

Our site ( platform.ledn.io ) does an external call to a `Captcha` endpoint `https://272f60420c0e.8d80c9ff.us-east-1.token.awswaf.com/272f60420c0e` . On checking DevTools ( screen-shot attached ), `Ublock` seems to be blocking the request. Because of this, once the user completes the `Captcha`, the site doesn't seem to continue to load.

The site works when `Ublock` is disabled.

### Other extensions used

I haven't used any other extension.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

If `ublock is enabled`

![image](https://github.com/uBlockOrigin/uAssets/assets/87039080/d8373d97-f788-4095-b759-1488849763fd)

If `ublock is disabled`
![image](https://github.com/uBlockOrigin/uAssets/assets/87039080/3c863050-a710-4ac5-94bc-f01720692d84)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105139
 cosmetic: 44165
 scriptlet: 19864
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76533-15, 20m
  easyprivacy: 33212-65, 20m
  plowe-0: 3784-1155, 20m
  ublock-badware: 7725-137, 20m
  ublock-filters: 36389-217, 20m
  ublock-privacy: 955-8, 20m
  ublock-quick-fixes: 154-48, 20m
  ublock-unbreak: 2173-31, 20m
  urlhaus-1: 10065-0, 20m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 378 ms (selfie)
 maxAssetCacheWait: 103 ms
popupPanel:
 blocked: 5
 network:
  awswaf.com: 1
  googletagmanager.com: 1
  heapanalytics.com: 1
  maps.googleapis.com: 1
  sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
EasyPrivacy's filter is blocking this request:

`||awswaf.com^*/telemetry`

@ryanbr

**Comment by harsha-venugopal-ledn** [comment]
@mapx- - Thank you for your time. 

Please find below credentials for a test account - 

```
harshaledn+testking@ledn.io
leGTH6Ps2PbOiRWU6itcKF9i83D4DZ44w3EUtVRDN@123
```

**Comment by ryanbr** [comment]
I get an error; 

We encountered an error with your login. Please attempt the following:
If you have a VPN connection, turn it off;
Attempt logging in from Google Chrome.

Not sure if filter related.

**Comment by mapx-** [comment]
`@@||awswaf.com/*/telemetry$xhr,domain=platform.ledn.io`

After whitelisting the xhr request, I got:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/0080205c-bfa2-447c-a473-95e44434fda9)

**Comment by harsha-venugopal-ledn** [comment]
> `@@||awswaf.com/*/telemetry$xhr,domain=platform.ledn.io`
> 
> After whitelisting the xhr request, I got:
> 
> ![image](https://private-user-images.githubusercontent.com/10303732/293771462-0080205c-bfa2-447c-a473-95e44434fda9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjU4ODQsIm5iZiI6MTcwNDIyNTU4NCwicGF0aCI6Ii8xMDMwMzczMi8yOTM3NzE0NjItMDA4MDIwNWMtYmZhMi00NDdjLWE0NzMtOTVlNDQ0MzRmZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE5NTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZDkyYjg3NjE4OTAxMjM0NTNhYmNjM2YwNTQ0NmE0YWZlNGFiOTZiNTE5MTkwYjVjMTM2OTUyNzc3NTJmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rNdKxS6_4_LA43Odw8_2GGh_tZ2jxqHdUpLqAIJgGdw)

This is the expected page as the email ID was not confirmed. 

I have another account in case you want to see a different behaviour - 

```
harsha+testking@ledn.io
leGTH6Ps2PbOiRWU6itcKF9i83D4DZ44w3EUtVRDN@123
```

**Comment by mapx-** [comment]
- now is asking for a SMS code
- however, did you test the filter above ? (which was added in easyprivacy list)

`@@||awswaf.com/*/telemetry$xhr,domain=platform.ledn.io`

**Comment by harsha-venugopal-ledn** [comment]
I did receive a SMS for an attempt you did 👍 

I tried the filter and it worked. Please find below screen-shot

![image](https://github.com/uBlockOrigin/uAssets/assets/87039080/fc21b23a-61e1-4aee-b733-916b320b845f)
