### ISSUE TITLE
kulaklik.com: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#21738]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kulaklik.com/blog/137/kablolu-kulaklik-onerileri-2023-yuksek-ses-kalitesine-sahip-tum-modeller-137`

### Category

ads

### Description

ads and cookie w.

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/0466774f-8a47-4143-a338-0cca2e03b735)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 113002
 cosmetic: 148886
 scriptlet: 30481
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28274-29, now
  easylist-annoyances: 4301-42, now
  easylist-chat: 177-0, now
  easylist-newsletters: 6853-23, now
  easylist-notifications: 2902-87, now
  fanboy-cookiemonster: 49134-3708, now
  fanboy-social: 16032-13, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6486-85, now
  ublock-cookies-adguard: 851-851, now
  ublock-cookies-easylist: 851-851, now
 default:
  user-filters: 0-0, never
  TUR-0: 13111-7, now
  easylist: 76568-38, now
  easyprivacy: 33154-101, now
  plowe-0: 3787-1160, now
  ublock-badware: 7725-137, now
  ublock-filters: 36384-246, now
  ublock-privacy: 955-10, now
  ublock-quick-fixes: 152-48, now
  ublock-unbreak: 2174-36, now
  urlhaus-1: 10065-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 608 ms (selfie)
 maxAssetCacheWait: 179 ms
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 2
  yandex.ru: 1
 extended:
  ##.react-share__ShareButton
  ##.icon-footer-facebook
  ##.icon-footer-twitter
  ##.icon-footer-youtube
```
</details>

**Comment by mapx-** [comment]
add

```
kulaklik.com##.left-right-banner
kulaklik.com##[class^="CookieInfo_cookieContainer"]
```

@Yuki2718 @Alex-302

**Comment by Alex-302** [comment]
Added.
