### ISSUE TITLE
imdb.com: breakage

### ISSUE THREAD

**Issue by RDru** [uBlockOrigin/uAssets#21741]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.imdb.com/search/title/?title_type=tv_series`

### Category

breakage

### Description

Clicking on "Sort by   Popularity" does nothing. Only disabling uBlock on the site fixes the issue.
"?title_type=tv_series" is just example search.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 106573
 cosmetic: 52103
 scriptlet: 18728
 html: 1991
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36982-324, now
  ublock-badware: 7729-11, now
  ublock-privacy: 951-0, now
  ublock-unbreak: 2220-0, now
  ublock-quick-fixes: 169-0, now
  easylist: 76589-562, now
  easyprivacy: 33144-795, now
  urlhaus-1: 10065-0, now
  plowe-0: 3787-1, now
  POL-0: 8359-27, now
  POL-2: 1283-12, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 988 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel:
 blocked: 10
 network:
  imdb.com: 3
  amazon-adsystem.com: 1
  amazon.com: 3
  scorecardresearch.com: 1
  ssl-images-amazon.com: 2
 extended:
  ##.slot_wrapper
  ##[id^="ads_"]
  ##[id^="adv-"]:not(#adv-settings)
```
</details>

**Comment by D4niloMR** [comment]
@xxcriticxx

Caused by `[id^="adv-"]:not(#adv-settings)`
