### ISSUE TITLE
Block onesignal.com as 3rd party

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#2174]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://onesignal.com`
https://documentation.onesignal.com/docs#section-why-should-i-use-onesignal

### Describe the issue

"We make money by using the data we aggregate to improve web and mobile experiences. We also offer custom solutions to enterprise clients."

" Best of all, OneSignal is a free service that supports unlimited devices and notifications. OneSignal makes money by selling data to advertisers and research companies. We also offer paid service options for clients that require increased data privacy."

OneSignal is selling user data.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Firefox
- uBlock Origin version: Latest

### Settings

- Default

### Notes

Does not break any site. Total scumbags.

**Comment by PakistanAdBlockList** [comment]
Agreed. This shady practice of selling data has to end. They even shamelessly advertise this.

**Comment by mapx-** [comment]
@ryanbr @monzta @Khrin

**Comment by smed79** [comment]
Fyi, `onesignal.com` is blocked https://github.com/easylist/easylist/commit/2a79d9d40869c006fe3599818b93cacdd54ed7fa in [**Fanboy's Annoyances list**](https://adblockplus.org/subscriptions#type_other).

**Comment by ReyCobin** [comment]
It should also be included in tracking list too.

**Comment by ReyCobin** [comment]
This is the answer:
cdn.onesignal.com$third-party

**Comment by pgl** [comment]
Added, thanks: https://pgl.yoyo.org/adservers/details.php?hostname=cdn.onesignal.com
