### ISSUE TITLE
hamrobiratnagar.com: ads

### ISSUE THREAD

**Issue by Sabinnar12** [uBlockOrigin/uAssets#21744]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hamrobiratnagar.com/`

### Category

Custom Ads

### Description

! 2024-01-02 https://www.hamrobiratnagar.com
||www.hamrobiratnagar.com/content/upload/post_image/720-1-mingifkx7itxiql.gif$image
||www.hamrobiratnagar.com/content/upload/post_image/krishna-catering-finalgifeybya5y9p.gif$image
||www.hamrobiratnagar.com/content/upload/post_image/eastern-college-adgifriq85uj4e.gif$image
www.hamrobiratnagar.com###multi-d-items > div.container > .py-2.row > .col-md-12
||www.hamrobiratnagar.com/content/upload/post_image/premierwires-1gifi0ezxhgxl.gif$image
||www.hamrobiratnagar.com/content/upload/post_image/premire-steeljpgm0jcf2x8f.jpg$image
||www.hamrobiratnagar.com/content/upload/post_image/bagmati-compressedgif7u0o63uuz.gif$image
||www.hamrobiratnagar.com/content/upload/post_image/whatsapp-image-2023-12-05-at-54939-pmjpeg4ekrqrzhs.jpeg$image

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 109899
 cosmetic: 52390
 scriptlet: 19866
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/sndsabin/swaccha-adblock-filter/master/swaccha-static-adblock-filters.txt: 134-1, now
  IND-0: 12952-11, now
 default:
  user-filters: 33-0, never
  easylist: 76591-19, now
  easyprivacy: 33144-6, now
  plowe-0: 3787-1158, now
  ublock-badware: 7725-137, now
  ublock-filters: 36381-218, now
  ublock-privacy: 955-8, now
  ublock-quick-fixes: 152-48, 46m
  ublock-unbreak: 2174-31, now
  urlhaus-1: 9910-0, now
filterset (user): [array of 33 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 308 ms (selfie)
 maxAssetCacheWait: 120 ms
popupPanel:
 blocked: 26
 network:
  hamrobiratnagar.com: 4
  doubleclick.net: 10
  facebook.com: 2
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  sharethis.com: 1
  statcounter.com: 1
  youtube.com: 5
 extended:
  ###multi-d-items > div.container > .py-2.row > .col-md-12
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##.AdBox
  ##.post-ads
  ##.sponsorPost
```
</details>

**Comment by huyszn** [comment]
You already made an issue on this site at https://github.com/mediumkreation/IndianList/issues/8649

**Comment by Sabinnar12** [comment]
please shut down this issue

**Comment by Sabinnar12** [comment]
Thanks
