### ISSUE TITLE
[nsfw] twnt1.rdtk.io: popups

### ISSUE THREAD

**Issue by ssocial-reject** [uBlockOrigin/uAssets#21746]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twnt1.rdtk.io/63efc4bb8ab16400011e2776`

### Category

popups

### Description

I dont know why but this keeps popping up. I scanned my device multiple times, blocked this website and other websites, removed files and more but it wont go away.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/81339479/a21a4cee-e5b3-478a-a941-5d9866ef2580)

![Screenshot 2024-01-03 030500](https://github.com/uBlockOrigin/uAssets/assets/81339479/eabfcd17-4faf-402d-b8ba-7ede341d8137)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105002
 cosmetic: 44191
 scriptlet: 19868
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76591-13, now
  easyprivacy: 33144-6, now
  plowe-0: 3787-1158, now
  ublock-badware: 7725-137, now
  ublock-filters: 36385-215, now
  ublock-privacy: 955-8, now
  ublock-quick-fixes: 152-48, now
  ublock-unbreak: 2174-31, now
  urlhaus-1: 9910-0, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 391 ms (selfie)
 maxAssetCacheWait: 108 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by okiehsch** [comment]
> I dont know why but this keeps popping up

`https://www.malwarebytes.com/blog/detections/rdtk-io`

There is nothing we can do about it.
