### ISSUE TITLE
programme-tv.net: nuisance

### ISSUE THREAD

**Issue by azgaresncf** [uBlockOrigin/uAssets#21749]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.programme-tv.net/news/people/331181-jallais-vers-la-mort-adele-castillon-fait-des-confidences-bouleversantes-sur-son-addiction-aux-medicaments-qui-a-failli-lui-couter-la-vie/`

### Category

nuisance

### Description

A CMP window is displayed.
``||consent.programme-tv.net/index.html`` should be added

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/50982832/c8fa9d7f-41fc-444a-b182-2b139fa39a99)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 124167
 cosmetic: 53332
 scriptlet: 20008
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 29014-39, 2m
  easylist: 76604-53, 2m
  easyprivacy: 33144-270, 2m
  plowe-0: 3787-1168, 2m
  ublock-badware: 7725-152, 2m
  ublock-filters: 36369-274, 2m
  ublock-privacy: 955-8, 2m
  ublock-quick-fixes: 155-48, 2m
  ublock-unbreak: 2173-35, 2m
  urlhaus-1: 9840-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1655 ms
 maxAssetCacheWait: 8 ms
popupPanel:
 blocked: 4
 network:
  audion.fm: 2
  datadoghq-browser-agent.com: 1
  googletagmanager.com: 1
 extended:
  ##.containerAds
  ##.ads-banniereHaute
  ##.innerAds
  ##.ads-placeholder
  ##.ads-text
  ##.ads-core-placer
  ##.ads-mobile
  ##.ads-paveHaut
  ##.ads-paveBas
  ##.ads-paveBas2
  ##.ads-desktop
  #@#[data-ads-core]
  ##+js(set-constant, Object.prototype.withAds, false)
  ##+js(abort-on-property-read, _sp_._networkListenerData)
```
</details>

**Comment by mapx-** [comment]
`||consent.programme-tv.net/index.html` is breaking the videos

**Comment by mapx-** [comment]
Enable uBlock filters – Annoyances
