### ISSUE TITLE
primevideo.com: breakage

### ISSUE THREAD

**Issue by sinkro** [uBlockOrigin/uAssets#21753]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.primevideo.com/`

### Category

breakage

### Description

The subtitles are out of sync by several seconds. The subtitles appear several seconds before the dialogue appears. As soon as uBO is disabled, the problem goes away. This has been going on for a few days now. 

### Other extensions used

Privacy Badger
Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 104943
 cosmetic: 44205
 scriptlet: 18530
 html: 1983
listset (total-discarded, last-updated):
 default:
  user-filters: 17-1, never
  ublock-filters: 36973-272, 24m
  ublock-badware: 7729-11, 24m
  ublock-privacy: 947-0, 24m
  ublock-unbreak: 2222-0, 24m
  easylist: 76604-543, 24m
  easyprivacy: 33144-798, 24m
  plowe-0: 3787-1, 24m
  urlhaus-1: 9840-0, 56m
  ublock-quick-fixes: 171-0, 24m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1917 ms (selfie)
 maxAssetCacheWait: 871 ms
popupPanel:
 blocked: 8
 network:
  primevideo.com: 4
  amazon.com: 4
 extended:
  ##+js(json-prune, cuepointPlaylist)
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] |…
```
</details>

**Comment by stephenhawk8054** [comment]
Do you know any free links that can reproduce the issue?
