### ISSUE TITLE
kooora.com: breakage

### ISSUE THREAD

**Issue by ayoubelmhamdi** [uBlockOrigin/uAssets#21754]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kooora.com/?region=-1&area=0`

### Category

big arabic footbal static 

### Description

i can see anything on the siteweb

### Other extensions used

nothing related to the block content

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/34358145/c16db689-e1cf-4552-a9de-17e5ecc98d1b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 117791
 cosmetic: 148039
 scriptlet: 32174
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28293-1594, 16m
  adguard-mobile-app-banners: 4880-17, 16m
  adguard-other-annoyances: 14002-15, 16m
  adguard-popup-overlays: 26754-121, 16m
  adguard-social: 22178-2075, 16m
  adguard-widgets: 2391-38, 16m
  ara-0: 2385-250, 16m
  easylist-annoyances: 4302-1107, 16m
  easylist-chat: 177-21, 16m
  easylist-newsletters: 6853-2304, 16m
  easylist-notifications: 2903-1702, 16m
  fanboy-cookiemonster: 49147-19661, 16m
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 76608-16091, 16m
  easyprivacy: 33101-128, 16m
  plowe-0: 3787-1157, 16m
  ublock-badware: 7725-137, 17m
  ublock-filters: 36373-765, 17m
  ublock-privacy: 950-9, 17m
  ublock-quick-fixes: 155-48, 17m
  ublock-unbreak: 2176-36, 17m
  urlhaus-1: 9840-0, 17m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1568 ms (selfie)
 maxAssetCacheWait: 945 ms
popupPanel:
 blocked: 18
 network:
  kooora.com: 1
  cloudflareinsights.com: 1
  facebook.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  lngtd.com: 1
  moatads.com: 1
  scorecardresearch.com: 1
  spot.im: 8
  taboola.com: 1
 extended:
  ###Leaderboard
  ##+js(set-constant, admiral, noopFunc)
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by gorhill** [comment]
I can't reproduce.

> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists

Yet:

> ```
> listset (total-discarded, last-updated):
> added:
>   adguard-cookies: 28293-1594, 16m
>   adguard-mobile-app-banners: 4880-17, 16m
>   adguard-other-annoyances: 14002-15, 16m
>   adguard-popup-overlays: 26754-121, 16m
>   adguard-social: 22178-2075, 16m
>   adguard-widgets: 2391-38, 16m
>   ara-0: 2385-250, 16m
>   easylist-annoyances: 4302-1107, 16m
>   easylist-chat: 177-21, 16m
>   easylist-newsletters: 6853-2304, 16m
>   easylist-notifications: 2903-1702, 16m
>   fanboy-cookiemonster: 49147-19661, 16m
>   [5 lists not shown]: [too many]
> ```

I still can't reproduce after adding annoyances and ara lists.
