### ISSUE TITLE
zcool.com.cn: breakage

### ISSUE THREAD

**Issue by lsh1215225** [uBlockOrigin/uAssets#21752]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zcool.com.cn/work/ZNjcwMTg2MzI=.html`

### Category

breakage

### Description

评论区无法显示，点赞异常，消息不显示数目

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 125583
 cosmetic: 77139
 scriptlet: 21498
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22582-12, 24m
  https://filters.adtidy.org/extension/ublock/filters/220.txt: 1880-3, 24m
  https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt: 68-1, 24m
  RUS-0: 40150-10, 24m
 default:
  user-filters: 38-5, never
  CHN-0: 25809-22672, 24m
  easylist: 76604-53, 24m
  easyprivacy: 33144-109, 24m
  ublock-badware: 7725-137, 24m
  ublock-filters: 36370-253, 24m
  ublock-privacy: 951-8, 24m
  ublock-quick-fixes: 154-48, 24m
  ublock-unbreak: 2176-32, 24m
filterset (user): [array of 38 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1243 ms (selfie)
 maxAssetCacheWait: 201 ms
popupPanel:
 blocked: 18
 network:
  zcool.com.cn: 14
  zcool.cn: 4
 extended:
  ##.adBox
```
</details>

**Comment by mapx-** [comment]
- do not open 2 issues for the same site
- test the filter I indicated here: https://github.com/uBlockOrigin/uAssets/issues/21751#issuecomment-1875606973
