### ISSUE TITLE
[nsfw] hentai2w.com: nuisance

### ISSUE THREAD

**Issue by TheNate** [uBlockOrigin/uAssets#21768]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hentai2w.com/`

### Category

nuisance

### Description

Page loads, then whited out - no content at all.
Disabling JS: page loads fine, little to functionality (of course)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="783" alt="Screenshot 2024-01-04 at 8 19 04 AM" src="https://github.com/uBlockOrigin/uAssets/assets/96553837/0151857d-181d-4785-b5b1-0ced89ac1e7b">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104711
 cosmetic: 44202
 scriptlet: 19889
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76715-12, 1h.53m
  easyprivacy: 33103-4, 1h.53m
  plowe-0: 3788-1156, now
  ublock-badware: 7740-137, 1h.53m
  ublock-filters: 36384-203, 1h.53m
  ublock-privacy: 950-7, 1h.53m
  ublock-quick-fixes: 158-47, 1h.53m
  ublock-unbreak: 2176-31, 1h.53m
  urlhaus-1: 9530-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 142 ms (selfie)
 maxAssetCacheWait: 60 ms
popupPanel:
 blocked: 13
 network:
  hentai2w.com: 2
  coendouspare.com: 1
  magsrv.com: 1
  placeholder.com: 9
 extended:
  ##+js(abort-current-script, Math.random, ExoLoader)
  ##+js(addEventListener-defuser, getexoloader)
  ##+js(addEventListener-defuser, click, popMagic)
```
</details>

**Comment by D4niloMR** [comment]
> Page loads, then whited out - no content at all.

Same without uBO.
