### ISSUE TITLE
pastebin.com: Ad leftovers

### ISSUE THREAD

**Issue by unbeatable-101** [uBlockOrigin/uAssets#21778]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pastebin.com/k965qYcJ`

### Category

ads

### Description

Sometimes when reloading the page, an advert leftover saying "Advertisement" appears. This does not happen when reloading and cleaning cache (^+Sh+R).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Reloading with ^+R
<img width="974" alt="Screenshot 2024-01-04 at 22 12 12" src="https://github.com/uBlockOrigin/uAssets/assets/58151048/81542df1-6e08-4922-9ffc-5b6d98954be1">
Reloading with ^+Sh+R
<img width="983" alt="Screenshot 2024-01-04 at 22 12 46" src="https://github.com/uBlockOrigin/uAssets/assets/58151048/b98e2207-05ed-4b9c-9e90-2e9b52ff34ce">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1rc2
Firefox: 123
filterset (summary):
 network: 188226
 cosmetic: 197845
 scriptlet: 31391
 html: 2203
listset (total-discarded, last-updated):
 added:
  https://neuter.mchang.xyz/filter: 174-0, now
  https://neuter.mchang.xyz/filter/misc: 41-1, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/requests.txt: 5-0, now
  https://raw.githubusercontent.com/paulgb/BarbBlock/master/blacklists/ublock-origin.txt: 550-6, now
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/duckduckgo/global.txt: 4206-0, now
  adguard-spyware-url: 1401-92, now
  adguard-spyware: 84914-16881, now
  block-lan: 55-0, now
  adguard-social: 22179-875, now
  adguard-cookies: 28322-62, now
  ublock-cookies-adguard: 872-0, now
  adguard-popup-overlays: 26762-1607, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 73-0, never
  ublock-filters: 36978-558, 14m Δ
  ublock-badware: 7755-11, 14m Δ
  ublock-privacy: 946-0, 14m Δ
  ublock-unbreak: 2222-1, 14m Δ
  ublock-quick-fixes: 199-0, 14m Δ
  easylist: 76765-690, 14m Δ
  easyprivacy: 33103-973, 14m Δ
  urlhaus-1: 9655-0, now
  plowe-0: 3788-359, now
filterset (user): [array of 73 redacted]
trustedset:
 added: [array of 46 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 510 redacted]
urlRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1008 ms (selfie)
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  infolinks.com: 3
  vlitag.com: 1
 extended:
  ##.adsbyvli
  ##div.-cookies
  ##.share-btn
  ##.js-twitter-share
  ##.cd-top
  ##.popup-box.-cookies
  ##.popup-box.-pro
  ##.content > [style^="padding-bottom:"]
```
</details>

**Comment by stephenhawk8054** [comment]
I don't see the generic cosmetic filters like `##.adSense` in OP's configuration, maybe due to the custom filter lists.

**Comment by unbeatable-101** [comment]
I tried this again after resetting uBo to default settings and it still happened.

**Comment by unbeatable-101** [comment]
Troubleshooting info from default settings

```
uBlock Origin: 1.55.1b0
Firefox: 123
filterset (summary):
 network: 104910
 cosmetic: 44190
 scriptlet: 18549
 html: 1999
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36980-206, now
  ublock-badware: 7755-11, now
  ublock-privacy: 946-0, now
  ublock-unbreak: 2222-0, now
  ublock-quick-fixes: 201-0, now
  easylist: 76765-608, now
  easyprivacy: 33103-793, now
  urlhaus-1: 9655-0, now
  plowe-0: 3788-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 678 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.content > [style^="padding-bottom:"]
  ##div[style^="color: #999; font-size: 12px; text-align: center;"…
  ##.adsbyvli
```

**Comment by stephenhawk8054** [comment]
I refreshed many times but could not reproduce the issue

**Comment by unbeatable-101** [comment]
The issue ended up being darkreader. I had disabled it from the extension menu and assumed it would not interact with the page, but obviously it still did.
