### ISSUE TITLE
counterstrike-hack.leforum.eu: ads

### ISSUE THREAD

**Issue by razeNFR** [uBlockOrigin/uAssets#21775]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

```
https://counterstrike-hack.leforum.eu/index.php
https://ajt.xooit.org/index.php
```

### Description

Look screen because my english is too bad for explain in text

### Other extensions used

i use other extension but i know its not due to my other extension (i tried to disable all and its same)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![xooit filter issue ub](https://github.com/uBlockOrigin/uAssets/assets/71156828/c48f5a9f-1a32-4161-878c-e0179dd8791c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 128322
 cosmetic: 126250
 scriptlet: 26616
 html: 2203
listset (total-discarded, last-updated):
 added:
  fanboy-thirdparty_social: 68-0, 8d.7h.44m
  fanboy-cookiemonster: 49147-226, 1d.4h.37m
  fanboy-social: 16032-22, 1d.4h.37m
  ublock-annoyances: 6440-881, 1h.16m
  easylist-annoyances: 4302-97, 1d.4h.37m
  easylist-chat: 175-0, 8d.7h.44m
  easylist-newsletters: 6853-13, 1d.4h.37m
  easylist-notifications: 2903-4, 1d.4h.38m
  ublock-cookies-easylist: 851-0, 1d.4h.38m
 default:
  user-filters: 44-2, never
  ublock-filters: 36991-287, 1h.16m
  ublock-badware: 7755-11, 1h.16m
  ublock-privacy: 946-0, 1h.16m
  ublock-unbreak: 2222-0, 1h.16m
  ublock-quick-fixes: 200-0, 1h.16m
  easylist: 76749-704, 1h.16m
  easyprivacy: 33103-880, 1h.16m
  urlhaus-1: 9530-0, 11h.15m
  plowe-0: 3787-1, 7d.11h.30m
  FRA-0: 28985-347, 3d.7h.3m
filterset (user): [array of 44 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 271 ms (selfie)
 maxAssetCacheWait: 122 ms
popupPanel:
 blocked: 5
 network:
  leforum.eu: 3
  googlesyndication.com: 1
  googletagmanager.com: 1

```
</details>

**Comment by gorhill** [comment]
What's the issue? Your screenshot does not make it clear.

**Comment by huyszn** [comment]
I think he is talking about the gray banner on the left side of the page? It appears after I refresh the page.
<img width="1440" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/5dc82894-9338-4e5a-bb44-b791b030caee">

**Comment by dportvine** [comment]
If you want to hide it, add to `'My filters'`: `counterstrike-hack.leforum.eu##+js(aopr, document.body.style.backgroundPosition)`

**Comment by razeNFR** [comment]
> If you want to hide it, add to `'My filters'`: `counterstrike-hack.leforum.eu##+js(aopr, document.body.style.backgroundPosition)`

Wow thank you so much !!! Its worked !

**Comment by mapx-** [comment]
add

```
||counterstrike-hack.leforum.eu/pub.php$subdocument
||ajt.xooit.org/pub.php$subdocument
```

@smed79

**Comment by garry-ut99** [comment]
> huyszn : I think he is talking about the gray banner on the left side of the page? It appears after I refresh the page.

It doesn't seem so : 
- on OP's screenshoot there is no grey banner because he has FRA regional list enabled, 
you have this grey placeholder most likely because you forgot to enable FRA regional list
- OP clearly marked the whole empty ad placeholder at the left side, which means this is what he means
- the ad placeholder is caused by a moved/restyled background, which means that to fix it, the background needs to be moved/restyled again, but `style()` or `remove-attr() ` won't work on this  site, and it requires a scriplet to be fixed

<hr>

> > dportvine : If you want to hide it, add to `'My filters'`: `counterstrike-hack.leforum.eu##+js(aopr, document.body.style.backgroundPosition)`
>
>  razeNFR : Wow thank you so much !!! Its worked !

Works also for the other domain : `ajt.xooit.org`, so the full filter would be  :
 `counterstrike-hack.leforum.eu,ajt.xooit.org##+js(aopr, document.body.style.backgroundPosition)`

<hr>

> mapx- : add
> ```
> ||counterstrike-hack.leforum.eu/pub.php$subdocument
> ||ajt.xooit.org/pub.php$subdocument
> ```

It doesn't work, there is an explanation why :

The ad/ad placeholder at the left site OP reported doesn't occur at the 1st clean visit (cookies & cache cleared), 
it occurs only at the 2nd + later visits, most likely you missed this fact and added your solution, then made a single clean visit to check whether it works, and then you wrongly assumed it was working, but if you visit page more than one time you will see ad placeholder is still there.

**Comment by garry-ut99** [comment]
Each of them contains hundreds / thousands of subdomains (forums)  - example : [LINK](https://www.google.com/search?q=site%3A*.leforum.eu)
It would require to add all the main domains to the scriplet, which would cover all the subdomains automatically, 
but it's somehow similiar to adding generic filters, which was not recommended : https://github.com/uBlockOrigin/uAssets/issues/7468#issuecomment-635422293, so most likely we should follow the recommendations and limit  fixing to sites reported by actual visitors.
