### ISSUE TITLE
syracuse.com: breakage

### ISSUE THREAD

**Issue by mjf17** [uBlockOrigin/uAssets#21771]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.syracuse.com/#/0`

### Description

Just recently (possibly today, 1/4/2024) I'm no longer able to access paid content on this site. I have a properly paid account. But when logged in and uBlock Origin is engaged, "subscriber only" articles are no longer fully accessible - they behave as if I was not a paying customer and was not logged in. When I turn off uBlock Origin for the site, all the ads return AND I am able to properly access all content. To be clear, I am not trying to bypass the paywall. I have a paid subscription and a proper account. But something on the site changed so that with uBlock Origin engaged, it's somehow not recognizing that I'm logged in.

### Other extensions used

Google Drive Application Launcher, Google Docs Offline, Google Mail Checker, Salesloft Connect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104745
 cosmetic: 44207
 scriptlet: 19901
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76730-12, 11m
  easyprivacy: 33103-4, 11m
  plowe-0: 3788-1154, 11m
  ublock-badware: 7751-137, 11m
  ublock-filters: 36389-203, 11m
  ublock-privacy: 950-7, 11m
  ublock-quick-fixes: 178-49, 11m
  ublock-unbreak: 2176-31, 11m
  urlhaus-1: 9530-0, 11m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 128 ms (selfie)
 maxAssetCacheWait: 72 ms
popupPanel:
 blocked: 0
 extended:
  ##.revenue-display
  ##.ad-small-1
  ##.ad-small-2
  ##.ad-inner
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.ad-large-1
  ##.module__ad-wide
  #@#.ad-unit
  ##+js(abort-on-property-read, _sp_._networkListenerData)
  ##+js(remove-node-text, script, /typeof [a-z]\.cmd\.unshift/, co…

```
</details>

**Comment by mapx-** [comment]
- without an account we cannot porperly investigate the issue
- however try this filter:

`||sophi.io^$3p,badfilter`

**Comment by mjf17** [comment]
Thanks, I tried it. It didn't fully work but it seems like it helped a little. There are little key icons next to news stories that are for subscribers only. When I applied that filter, the little key icons showed up again (they apparently were gone / blocked before). But the subscriber only articles still don't quite work unfortunately.

Is there a way for us to use a password manager and for me to share the password securely with you for a more thorough investigation?

Regardless, thanks for the help and for the quick response.

**Comment by mapx-** [comment]
You can send to me your account credentials and all the steps to reproduce your issues

my email address: `axis.trivia@gmail.com`

**Comment by mjf17** [comment]
Is there a password manager that you use?

**Comment by liamengland1** [comment]
@mjf17
Try adding all of these filters:

```
@@||googletagmanager.com/gtm.js$script,domain=syracuse.com
@@||p952.syracuse.com^
syracuse.com#@#^script:has-text(/typeof [a-z]\.cmd\.unshift/)
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=syracuse.com
```

@mapx- I had to add these, plus `||sophi.io^$3p,badfilter` to get the paywall to show up in a vanilla profile of Firefox w/ uBo on default filterlists.

**Comment by stephenhawk8054** [comment]
@liamengland1 OP is using chromium, so the 3rd filter should be

```adb
syracuse.com#@#+js(rmnt, script, /typeof [a-z]\.cmd\.unshift/, condition, cmd.unshift)
```

**Comment by stephenhawk8054** [comment]
I'll adjust the admiral filters first

**Comment by mjf17** [comment]
Ok, I was finally able to check this. I didn't try any of the new filters listed by @liamengland1 or @stephenhawk8054. But I opened up the page (syracuse.com) and everything was working properly. I tried on 3 different computers (two of which I did not add the original custom filter by @mapx-) and the page works as expected on all 3 machines. By "as expected", I mean no ads showing but it is recognizing my logging in and giving me full access to "subscriber only" articles. So the issue is now resolved.

The minor side effect is that I wasn't able to test the new set of filters to see if they had any impact, at least in a local custom filters context. If the global filters were adjusted with those additions, then I can confirm that the site works properly at this time.

**Comment by mapx-** [comment]
@mjf17 it seems you are saying there is no issue at all

**Comment by mjf17** [comment]
Yes, it looks like things are all good and still working. Thanks for all the help and all the responses.

**Comment by liamengland1** [comment]
@stephenhawk8054 there are more news sites owned by the same company (Advance Media) affected by the above breakage issue. A few test links:

```
https://www.oregonlive.com/portland/2024/02/portland-news-station-airs-racist-image-during-share-a-photo-from-your-past-that-makes-you-smile-segment.html
https://www.cleveland.com/court-justice/2024/02/a-royal-con-how-authorities-say-an-east-cleveland-man-pretended-to-be-a-prince-duped-city-leaders-and-stole-10-million.html
https://www.mlive.com/highschoolsports/2024/02/arthur-hill-turns-to-boop-in-historic-win-over-saginaw-high.html
https://www.pennlive.com/opinion/2024/02/how-we-exposed-corruption-in-pennsylvanias-corrections-union-opinion.html
https://www.masslive.com/news/2024/02/songwriting-legend-81-suffering-from-dementia-says-family-seeking-conservatorship.html
https://www.al.com/news/mobile/2024/02/fairhope-residents-water-bills-may-see-an-increase-soon.html
```

Also, the scriptlet targeting `v4ac1eiZr0` doesn't seem to be causing breakage anymore when testing, I only need the below filters to unbreak. 


```
@@||googletagmanager.com/gtm.js$script,3p,domain=oregonlive.com|cleveland.com|syracuse.com|nj.com|mlive.com|pennlive.com|masslive.com|silive.com|lehighvalleylive.com|al.com
@@||apps.sophi.io/latest/*.segments.min.js$script,3p,domain=oregonlive.com|cleveland.com|syracuse.com|nj.com|mlive.com|pennlive.com|masslive.com|silive.com|lehighvalleylive.com|al.com
@@/DG/DEFAULT/rest/rpc/*$script,1p,domain=oregonlive.com|cleveland.com|syracuse.com|nj.com|mlive.com|pennlive.com|masslive.com|silive.com|lehighvalleylive.com|al.com
```

**Comment by greentop** [comment]
The issue is back with _www.pennlive.com_ _www.syracuse.com_ _www.masslive.com_ all now detecting UBO upon loading their home pages.
