### ISSUE TITLE
livingstonparishnews.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21774]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.livingstonparishnews.com/breaking_news/louisiana-state-police-investigating-fatal-crash-on-i-12/article_4c406706-ab1a-11ee-9c84-5fccc5ed90d8.html`

### Category

detection

### Description

"Ads are being blocked by your browser" detection message. Same detection also appears on `gwinnettdailypost.com` (
`https://www.gwinnettdailypost.com/local/osborne-middle-schools-steven-bragg-named-media-clerk-of-the-year/article_a2513166-ab47-11ee-afff-a312a1665e0c.html`)

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105031
 cosmetic: 45964
 scriptlet: 24374
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6491-16, now
 default:
  user-filters: 66-2, never
  easylist: 76715-12, 23m
  easyprivacy: 33103-4, now
  plowe-0: 3788-1156, now
  ublock-badware: 7751-137, now
  ublock-filters: 36388-212, 23m
  ublock-privacy: 950-7, now
  ublock-quick-fixes: 184-49, now
  ublock-unbreak: 2176-32, now
  urlhaus-1: 9530-0, now
filterset (user): [array of 52 redacted]
trustedset:
 added: [array of 23 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 389 ms
 maxAssetCacheWait: 135 ms
popupPanel:
 blocked: 13
 network:
  livingstonparishnews.com: 3
  facebook.net: 1
  googletagmanager.com: 2
  townnews.com: 7
 extended:
  ##.tnt-ads-container
```
</details>

**Comment by huyszn** [comment]
I also found other news sites that have the same detection message but it doesn't cover the whole page:
```
https://www.rivervalleynow.com/local_news/high-school-seniors-invited-to-time-out-for-tech-feb-22/article_3ed58840-a9c5-11ee-861a-638b350f194e.html
https://www.stlamerican.com/election/reed-calls-spencer-s-attack-ad-a-sad-old-racist-trope/article_b7e6f7ae-70cb-11eb-8880-8715ccb8349c.html
https://www.gillettenewsrecord.com/news/local/article_47a9ea5e-1517-596e-9420-d2fb87749d08.html
https://www.colemantoday.com/news/dense-fog-advisory-issued-until-10-00-am/article_fbe7c8a2-aae3-11ee-9eca-5b93caa6e06e.html
https://www.dailyuw.com/opinion/streaming-services-shouldn-t-be-charging-us-to-watch-ads/article_17f92244-7128-11ed-ac12-c7e5dbbf3c1b.html
https://www.sunnysidesun.com/beware-of-false-social-media-posts/article_9134d04e-014e-11ed-9c86-e3a8a347d7d6.html
```
Is this an annoyance? I see in the annoyance list there is
```
idahopress.com##.tnc-overlay.tncms-block
idahopress.com###blox-message-incompatible
```
that is the same detection as the news sites in the list.

**Comment by D4niloMR** [comment]
It's an annoyance since its a soft anti-adblock.

@mapx- maybe it should be written in the readme that soft and dismissable anti-adblock are fixed on ublock-annoyances?

**Comment by liamengland1** [comment]
There are at least 500 sites using Blox CMS with these baits. They can all be fixed by allowing the bait scripts like so

```
@@||townnews.com^*/tncms/*/ads/*/tnt.ads.advertisements.$script
@@||townnews.com^*/tncms/*/ads/*/tnt.ads.adverts.$script
```

**Comment by D4niloMR** [comment]
I need only `@@||townnews.com^*/tncms/*/ads/*/tnt.ads.adverts.$script` here
