### ISSUE TITLE
netsecure.adp.com: breakage

### ISSUE THREAD

**Issue by andriygm** [uBlockOrigin/uAssets#21773]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://netsecure.adp.com/associate-forms/?callingAppId=UniversalLogin&returnUrl=https://www.adp.com/contact-us/customer-service.aspx&locale=en_US`

### Category

breakage

### Description

Form doesn't submit

### Other extensions used

1Password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104768
 cosmetic: 44206
 scriptlet: 19902
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76749-12, now
  easyprivacy: 33103-4, now
  plowe-0: 3788-1154, now
  ublock-badware: 7751-137, now
  ublock-filters: 36391-203, now
  ublock-privacy: 950-7, now
  ublock-quick-fixes: 180-49, now
  ublock-unbreak: 2176-31, now
  urlhaus-1: 9530-0, 1h.49m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms (selfie)
 maxAssetCacheWait: 89 ms
popupPanel:
 blocked: 5
 network:
  adp.com: 1
  online-metrix.net: 3
  pendo.io: 1
```
</details>

**Comment by mapx-** [comment]
does this help ?

`@@||cdn.pendo.io/agent/static/*/pendo.js$script,domain=netsecure.adp.com`

**Comment by liamengland1** [comment]
@mapx- that should work. I tested with junk info and console shows `Uncaught TypeError: pendo.track is not a function` after clicking the continue button

**Comment by D4niloMR** [comment]
or `netsecure.adp.com##+js(set, pendo.track, noopFunc)`

**Comment by liamengland1** [comment]
also needed for `my.adp.com`, can the domain match be changed to just `adp.com`

![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/b900e527-3c66-4606-b9cf-67c2a37bc506)

**Comment by D4niloMR** [comment]
Does [this](https://github.com/uBlockOrigin/uAssets/issues/21773#issuecomment-1879913731) work without issue?
