### ISSUE TITLE
promotions.hu: ads

### ISSUE THREAD

**Issue by legycsapo1** [uBlockOrigin/uAssets#21781]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://promotions.hu/`

### Category

ads

### Description

There's leftover text from ads on the homepage of promotions.hu. Using the element picker on the "hirdetés" text   **_`"##section > div.py-4.justify-center.items-center.flex.h-full.w-full.bg-transparent.banner > .px-6.relative.mx-auto.items-center.justify-center.flex.banner__ad > .text-xs.text-gray-500.-bottom-4.absolute.block"`_**   this is one of the problems, and above that, there's some empty space. **_`"###b_home_page_top_head > .adsbygoogle"`_**

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-01-05 13_59_35-Hírek _ Programok _ Sporthírek _ Promotions hu](https://github.com/uBlockOrigin/uAssets/assets/81675270/597b8296-f94e-4a39-b797-4feac80deec3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 205631
 cosmetic: 113778
 scriptlet: 38578
 html: 0
listset (total-discarded, last-updated):
 added:
  HUN-0: 2090-0, 9m
  adguard-generic: 81639-492, 9m
  adguard-popup-overlays: 26775-73, 9m
  curben-phishing: 77868-20, 9m
  easylist-newsletters: 6857-449, 9m
 default:
  user-filters: 0-0, never
  easylist: 76765-1717, 9m
  easyprivacy: 33103-169, 9m
  plowe-0: 3784-1165, 10m
  ublock-badware: 7751-322, 10m
  ublock-filters: 36374-3579, 10m
  ublock-privacy: 950-7, 10m
  ublock-quick-fixes: 185-49, 10m
  ublock-unbreak: 2176-98, 10m
  urlhaus-1: 10125-0, 10m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 654 ms (selfie)
 maxAssetCacheWait: 248 ms
popupPanel:
 blocked: 4
 network:
  clarity.ms: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  pahtag.tech: 1
 extended:
  ##[id*="google_ads"]
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
add

```
promotions.hu##.banner__ad
promotions.hu##.banner
```

@scripthunter7

**Comment by scripthunter7** [comment]
@mapx- done, thanks
