### ISSUE TITLE
cryptopolitan.com: ads

### ISSUE THREAD

**Issue by k3tonan** [uBlockOrigin/uAssets#21784]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cryptopolitan.com/`

### Category

ads

### Description

A banner add appears in the top just below the ticker and at the very bottom.

when selecting the top ad this is the top filter to remove it:
##.elementor-widget-template.elementor-widget.elementor-element-eab5def.elementor-element

the bottom ad
##.clickout-banner-regular_native_box-bottom.clickout-banner-regular_native_box.clickout-rendered-container-060ba704-row

### Other extensions used

N/A used a fresh browser without add-ons other than UBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105373
 cosmetic: 44193
 scriptlet: 19907
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 76765-12, 47m
  easyprivacy: 33103-4, 47m
  plowe-0: 3784-1153, now
  ublock-badware: 7751-137, 47m
  ublock-filters: 36374-203, 47m
  ublock-privacy: 950-7, 47m
  ublock-quick-fixes: 185-49, 47m
  ublock-unbreak: 2176-31, 47m
  urlhaus-1: 10125-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 780 ms (selfie)
 maxAssetCacheWait: 249 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  stats.wpmucdn.com: 1
  twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
```
||cryptotrials.care^$3p
||kurzycz.care^$3p
cryptopolitan.com##.elementor-widget-template.elementor-widget
```

@ryanbr
