### ISSUE TITLE
pogo.com: detection

### ISSUE THREAD

**Issue by doqpark** [uBlockOrigin/uAssets#21787]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pogo.com/`

### Category

detection

### Description

When UBlock is active on pogo.com, the games will not load at all- instead, the site just displays a black box. 

### Other extensions used

- GaiaUpgrade
- New Xkit
- Return YouTube Dislike 
- Ruffle Flash Emulator 
- Tapermonkey
- YouTube Redux

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 105379
 cosmetic: 44192
 scriptlet: 18548
 html: 1999
listset (total-discarded, last-updated):
 default:
  user-filters: 5-1, never
  ublock-filters: 36977-275, 36m
  ublock-badware: 7755-11, 36m
  ublock-privacy: 946-0, 36m
  ublock-unbreak: 2222-0, 36m
  ublock-quick-fixes: 203-0, 36m
  easylist: 76765-538, 36m
  easyprivacy: 33103-793, 36m
  urlhaus-1: 10125-0, 10m
  plowe-0: 3784-1, 10m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 312 ms (selfie)
 maxAssetCacheWait: 113 ms
popupPanel:
 blocked: 2604
 network:
  3lift.com: 4
  4dex.io: 1457
  a-mo.net: 49
  adnxs.com: 49
  adsafeprotected.com: 1
  amazon-adsystem.com: 50
  aniview.com: 3
  casalemedia.com: 49
  criteo.com: 49
  criteo.net: 98
  dotomi.com: 1
  doubleclick.net: 50
  doubleverify.com: 11
  ea.com: 3
  flashtalking.com: 16
  google-analytics.com: 18
  google.com: 7
  googlesyndication.com: 1
  innovid.com: 1
  lijit.com: 49
  media.net: 49
  omnitagjs.com: 49
  openx.net: 49
  pubmatic.com: 49
  richaudience.com: 98
  rubiconproject.com: 98
  scorecardresearch.com: 1
  sharethrough.com: 49
  smartadserver.com: 98
  sonobi.com: 49
  the-ozone-project.com: 49
```
</details>

**Comment by mapx-** [comment]
@doqpark 

Test

`@@||player.aniview.com/script/$script`

**Comment by mapx-** [comment]
right. adding the exception above makes the player to start immediately

**Comment by mapx-** [comment]
@ryanbr
