### ISSUE TITLE
alltransistors.com: breakage

### ISSUE THREAD

**Issue by kravets-levko** [uBlockOrigin/uAssets#21785]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://alltransistors.com/adv/pdfdatasheet_international_rectifier/irfr210pbf_irfu210pbf.pdf`

### Category

breakage

### Description

With uBlock Origin enabled, I cannot download files from alltransistors.com. Of course, I can disable the extension for the site, but I think the rule that blocks the download is too generic (see screenshots)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/12139186/d837fdf4-6e32-4aa0-a1c3-9cc8767e6123)

![image](https://github.com/uBlockOrigin/uAssets/assets/12139186/4135d566-67b4-482f-9fb6-78851e19baa0)

![image](https://github.com/uBlockOrigin/uAssets/assets/12139186/0eae7905-23a8-41ed-9e10-2eb362d1f3f7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105336
 cosmetic: 44207
 scriptlet: 19902
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76730-12, 57m
  easyprivacy: 33103-4, 57m
  plowe-0: 3784-1153, now
  ublock-badware: 7751-137, 57m
  ublock-filters: 36390-203, 57m
  ublock-privacy: 950-7, 57m
  ublock-quick-fixes: 178-49, 57m
  ublock-unbreak: 2176-31, 57m
  urlhaus-1: 10125-0, 57m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14003 ms (selfie)
 maxAssetCacheWait: 2497 ms
popupPanel:
 blocked: 1
 network:
  alltransistors.com: 1
```
</details>

**Comment by mapx-** [comment]
- go to `https://alltransistors.com/transistor.php?transistor=72100`
- click `d965-kehe d9cu.pdf`
- I can click or right click (save as ..) the pdf

**Comment by kravets-levko** [comment]
@mapx- thank you for the reply. Try to actually save the file - click "Save as", when the save dialog appears - chose any folder/filename and confirm. See the last screenshot

**Comment by mapx-** [comment]
- provide the specific page from your screenshot
- do I need an account ?

**Comment by okiehsch** [comment]
I can reproduce, no account needed.
Go to
`https://alltransistors.com/adv/pdfview.php?doc=d965-kehe_d9cu.pdf&dire=_cn_kehe`
the preview of the file is blocked and if you try right click /save as  it won't work, i.e. try to actually get the file on your hard drive.
`@@||alltransistors.com/adv/*$frame,other,1p`
works on my end.
