### ISSUE TITLE
breakage on exported webflow sites due to https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js

### ISSUE THREAD

**Issue by doctorpangloss** [uBlockOrigin/uAssets#21797]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js`

### Description

This is the JQuery URL referenced by many WebFlow exports. **It should not be blocked at all**, it is used in tens of thousands, possibly hundreds of thousands of legitimate sites (https://github.com/search?q=d3e54v103j8qbb.cloudfront.net&type=code).

This ought to reopen https://github.com/uBlockOrigin/uAssets/issues/21791 which was fixed by

```
@@||d3e54v103j8qbb.cloudfront.net/js/jquery$script,domain=wellzesta.com
```

in your `quick-fixes.txt`.

The reason is due to EasyList's rule `||d3e54v103j8qbb.cloudfront.net^`

I am the owner of a website affected by this, and I will simply host JQuery from my own URL. That said, you probably do not mean to block this.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 115652
 cosmetic: 44187
 scriptlet: 18560
 html: 1999
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36976-276, 6m
  ublock-badware: 7755-11, 6m
  ublock-privacy: 946-0, 6m
  ublock-unbreak: 2223-0, 6m
  ublock-quick-fixes: 214-0, 6m
  easylist: 76795-549, 6m
  easyprivacy: 43388-822, 6m
  urlhaus-1: 10125-0, 6m
  plowe-0: 3784-1, 6m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 506 ms (selfie)
 maxAssetCacheWait: 108 ms
popupPanel:
 blocked: 20
 network:
  github.com: 20

```
</details>

**Comment by huyszn** [comment]
Has been removed https://github.com/easylist/easylist/commit/fe3a6bd400a97923ce737f6b2d50b932ff14aed2

**Comment by D4niloMR** [comment]
The filter got removed from EL 3 hours ago, update your filters. https://github.com/uBlockOrigin/uAssets/commit/f681095a8669ee6bb959d7a7d35f49e7c36d4482
