### ISSUE TITLE
wellzesta.com: breakage

### ISSUE THREAD

**Issue by CharlesBuss** [uBlockOrigin/uAssets#21791]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wellzesta.com/`

### Category

breakage

### Description

Site built on WebFlow using existent theme.
Works perfectly when the uBlock is disabled.

### Other extensions used

1Password, Loom, Google Analytics Debugger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="924" alt="Screenshot 2024-01-05 at 16 47 47" src="https://github.com/uBlockOrigin/uAssets/assets/11364046/eb596399-8f92-4423-97d9-6c7ea37b9045">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105380
 cosmetic: 44188
 scriptlet: 19908
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76777-12, 1h.59m
  easyprivacy: 33103-4, 1h.59m
  plowe-0: 3784-1153, now
  ublock-badware: 7751-137, 1h.59m
  ublock-filters: 36370-203, 1h.59m
  ublock-privacy: 950-7, 1h.59m
  ublock-quick-fixes: 183-49, 1h.59m
  ublock-unbreak: 2176-31, 1h.59m
  urlhaus-1: 10125-0, 1h.59m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 467 ms (selfie)
 maxAssetCacheWait: 133 ms
popupPanel:
 blocked: 7
 network:
  d3e54v103j8qbb.cloudfront.net: 1
  hs-analytics.net: 1
  hs-banner.com: 1
  hsadspixel.net: 1
  hsleadflows.net: 1
  hubspot.com: 1
  newrelic.com: 1
```
</details>

**Comment by okiehsch** [comment]
Site is completely broken
`@@||d3e54v103j8qbb.cloudfront.net/js/jquery$script,domain=wellzesta.com`
@ryanbr
