### ISSUE TITLE
barbadosdigital.com: breakage (CloudFront CDN being blocked – affects Webflow sites)

### ISSUE THREAD

**Issue by bastones** [uBlockOrigin/uAssets#21798]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.

### URL address of the web page

https://barbadosdigital.com

### Category

breakage

### Description

Navbar dropdowns not working and some UI animations broken due to jQuery CDN (via CloudFront) being blocked by EasyList.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 119589
 cosmetic: 115586
 scriptlet: 22282
 html: 1999
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95308-32471, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-social: 16033-17, now
 default:
  user-filters: 144-2, never
  ublock-filters: 36976-206, 42m
  ublock-badware: 7755-11, 42m
  ublock-privacy: 946-0, 42m
  ublock-unbreak: 2223-0, 42m
  easylist: 76795-620, 42m
  easyprivacy: 43388-826, 42m
  plowe-0: 3784-1, now
  urlhaus-1: 10125-0, now
  ublock-quick-fixes: 214-0, 42m
filterset (user): [array of 144 redacted]
trustedset:
 added: [array of 50 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1503 ms (selfie)
 maxAssetCacheWait: 553 ms
popupPanel:
 blocked: 20
 network:
  d3e54v103j8qbb.cloudfront.net: 12
  googletagmanager.com: 6
  mouseflow.com: 2
```
</details>

**Comment by bastones** [comment]
Related: https://github.com/uBlockOrigin/uAssets/issues/21797

**Comment by huyszn** [comment]
Has been removed https://github.com/easylist/easylist/commit/fe3a6bd400a97923ce737f6b2d50b932ff14aed2
