### ISSUE TITLE
viafree.no

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#218]
### URL(s) where the issue occurs

http://www.viafree.no/

http://www.viafree.no/programmer/livsstil/luksusfellen/sesong-15/episode-1

### Describe the issue

Videoes on the site doesn't start. Tells me to turn off adblocker to view the content.

### Screenshot(s)

http://i.imgur.com/R1PSvTo.jpg

### Versions

- Browser/version: [Chrome/54.0.2840.99]
- uBlock Origin version: [1.10.0]

### Settings

Enabled WebRTC not leaking IP address.
Enabled all 3 social network filters.

### Notes

I got this filter from adblock forum. It does enable me to see the video, but still show ads throughout the videoes, multiple times, and commercials are usually 1-4 minutes long.

@@||viafree.no$xmlhttprequest
@@||adm.fwmrm.net/p/MTG_Brightcove_HTML5/AdManager.js$script,domain=viafree.no
@@||viafree.no^$generichide
@@||5d404.v.fwmrm.net/ad/$script,domain=viafree.no
@@||viafree.no$xmlhttprequest
@@||viafree.no^$generichide
@@||fwmrm.net/p/MTG_Brightcove_HTML5/AdManager.js$script,domain=viafree.no

**Comment by gorhill** [comment]
I get this message when I go to <http://www.viafree.no/programmer/livsstil/luksusfellen/sesong-15/episode-1>:

> Innholdet du prøver å se er kun tilgjengelig for brukere i Norge

Which translates into:

> The content you are trying to view is only available for users in Norway

So I won't be able to help.

**Comment by mapx-** [comment]
if it's about brightcove player ..probably there's nothing to do about
http://www.onlinevideo.net/2016/01/stream-stitching-what-pros-must-know-about-the-ad-blocker-beater/

**Comment by gorhill** [comment]
@mapx- Is there a site accessible from where I am which uses this technology?

**Comment by mapx-** [comment]
try these sites
https://adblockplus.org/forum/viewtopic.php?p=161732#p161732

**Comment by IDKwhattoputhere** [comment]
Is [this](https://github.com/uBlockOrigin/uAssets/issues/27) the same issue? I see requests to Brightcove on the site too.

**Comment by mapx-** [comment]
I guess brightcove provides not only the newest (expensive) approach but also the old one (separate streams)

**Comment by ghajini** [comment]
There is no geolock right now.....

**Comment by okiehsch** [comment]
@ghajini I get a message that suggests that I should disable my adblocker, if I then whitelist
the site the video never starts, can you watch the video if you whitelist the site?

**Comment by ghajini** [comment]
I also not able to watch video....I thought it was my internet speed problem.... Though I don't know, what's the problem

**Comment by mapx-** [comment]
working filters for chrome (tested on the link gorhill posted above, using hola):
`http://www.viafree.no/programmer/livsstil/luksusfellen/sesong-15/episode-1`

```
@@||fwmrm.net/*MTG$script,domain=viafree.no
||fwmrm.net/ad/$xmlhttprequest,redirect=nooptext,domain=viafree.no
||freewheel-mtgx-tv.akamaized.net/$media,domain=viafree.no
```

**Comment by mapx-** [comment]
working for viafree.se too
```
@@||fwmrm.net/*MTG$script,domain=viafree.no
||fwmrm.net/ad/$xmlhttprequest,redirect=nooptext,domain=viafree.no|viafree.se|viafree.se
||freewheel-mtgx-tv.akamaized.net/$media,domain=viafree.no|viafree.se
```
