### ISSUE TITLE
tvtropes.org: breakage

### ISSUE THREAD

**Issue by honnza** [uBlockOrigin/uAssets#21805]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tvtropes.org/`

### Category

breakage

### Description

Captcha displays and interacts correctly. After solving captcha, page displays "you will be redirected shortly" but does not redirect. Reloading the page results in a new captcha. Disabling uBO and solving the captcha results in the main page loading successfully and captcha does not reappear even if uBO is reactivated and the page is reloaded.

### Other extensions used

Tampermonkey (no scripts installed)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 117037
 cosmetic: 35961
 scriptlet: 18786
 html: 2002
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 37356-452, now
  ublock-badware: 7749-11, now
  ublock-privacy: 946-1, now
  ublock-unbreak: 2228-1, now
  ublock-quick-fixes: 214-0, now
  adguard-mobile: 8967-132, now
  easylist: 76800-16688, now
  easyprivacy: 43388-837, now
  urlhaus-1: 9840-0, now
  plowe-0: 3784-1, now
  CZE-0: 830-47, now
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 571 ms (selfie)
 maxAssetCacheWait: 200 ms
popupPanel:
 blocked: 1
 network:
  awswaf.com: 1
```
</details>

**Comment by mapx-** [comment]
Czech ip => bad EP filter  `||awswaf.com^*/telemetry`

fixed

@honnza update unbreak list => use for update: 
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-unbreak&manual=1
