### ISSUE TITLE
[nsfw] camwhores.tv: ads

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#21806]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.camwhores.tv/videos/41703/novapatra-leaves-twitch-on-and-then-faps-in-private-premium-video-50a450c2-a466e5d5b57c2954/`

If that doesnt work try:

`https://www.camwhores.tv/videos/41703/novapatra-leaves-twitch-on-and-then-faps-in-private-premium-video/`

### Category

nuisance

### Description

Play the video, then pause and then resume. A video ad will be shown. _There is also an ad banner at the top (if you care about fixing this as well. If not its okay this report is only about the video ad)._

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105373
 cosmetic: 49063
 scriptlet: 19933
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 default:
  user-filters: 9-0, never
  DEU-0: 7260-0, now
  easylist: 76800-19, now
  easyprivacy: 43391-41, now
  ublock-badware: 7763-137, now
  ublock-filters: 36408-219, now
  ublock-privacy: 950-6, now
  ublock-quick-fixes: 196-50, now
  ublock-unbreak: 2177-33, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1456 ms (selfie)
 maxAssetCacheWait: 295 ms
popupPanel:
 blocked: 9
 network:
  afkwa.com: 3
  googletagmanager.com: 1
  imglnkd.com: 2
  ku42hjr2e.com: 1
  scfsdvc.com: 2
 extended:
  ##a[href*="theporndude.com"]
  ##a[href^="https://t.ajrkm1.com/"]
  ##+js(no-setTimeout-if, innerText, 2000)
  ##+js(abort-current-script, onload)
  ##+js(addEventListener-defuser, , Pop)
  ##+js(abort-on-property-read, _wm)
  ##+js(abort-on-property-read, loadTool)
  ##+js(no-window-open-if)
  ##+js(set-constant, flashvars.adv_pre_src, )
  ##+js(set-constant, flashvars.adv_pre_url, )
  ##+js(set-constant, flashvars.adv_pre_vast, )
  ##+js(set-constant, flashvars.protect_block, )
  ##+js(set-constant, flashvars.video_click_url, )
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Symbai** [comment]
Why are you unable to reproduce? Maybe the ads are based on region? I got them all the time (only pausing and resuming it for the FIRST time).

**Comment by huyszn** [comment]
Did you update your filters? I copied your lists and I noticed that you didn't have the filter
`##.fp-player > div[style="position: absolute; inset: 0px; overflow: hidden; z-index: 160; background: transparent; display: block;"]`
which I have when using your lists. Without this filter, I can see the video ads. It is in the `uBlock filters – Ads` list.

**Comment by Symbai** [comment]
When reporting this issue Ublock suggested me to update the filter swhich I did, video ad still played. And while writing this I just cleared the cache and refresh. Still the same. I even added your line into my custom filters, still video ad is played.

**Comment by huyszn** [comment]
What Chromium browser are you using? Have you tested on other browsers?

**Comment by Symbai** [comment]
Im using Edge (Stable and preview, its same on both). I havnet tried other browsers. But I just installed Chrome portable (stable version) and it appears that the issue doesnt happen on Chrome but on Edge.

**Comment by D4niloMR** [comment]
I can reproduce on Edge.

`||afkwa.com^` fixes here 

@Yuki2718 to EasyList

**Comment by Yuki2718** [comment]
> Why are you unable to reproduce?

Don't know, I don't see `afkwa.com` request. Such things happen and so we have many people.
