### ISSUE TITLE
loanoffering.in: detection

### ISSUE THREAD

**Issue by Noorhasanrz** [uBlockOrigin/uAssets#21811]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://loanoffering.in/what-is-the-minimum-credit-score-needed-for-a-car-loan/`

### Category

detection

### Description

Loanoffering is a return web page of a link shortener and it's detected uBlock

### Other extensions used

None

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/145339882/382438a5-20ee-43ac-9cf3-6145c3e6be08

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 117383
 cosmetic: 35588
 scriptlet: 18725
 html: 2001
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37458-454, now
  ublock-badware: 7755-11, now
  ublock-privacy: 946-1, now
  ublock-unbreak: 2236-1, now
  ublock-quick-fixes: 217-0, now
  adguard-mobile: 8969-132, now
  easylist: 76823-16686, now
  easyprivacy: 43392-832, now
  urlhaus-1: 10385-0, now
  plowe-0: 3784-1, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3492 ms
 maxAssetCacheWait: 31 ms
popupPanel:
 blocked: 0
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by huyszn** [comment]
What is the link shortener from which you got to this page?

**Comment by Noorhasanrz** [comment]
This is link shortener https://modijiurl.com/ZTnw
