### ISSUE TITLE
eksisozluk111.com: privacy

### ISSUE THREAD

**Issue by fenopa** [uBlockOrigin/uAssets#21815]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://eksisozluk111.com/

### Description

On `https://eksisozluk111.com/`, `https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location` is allowed because of this rule from "EasyList – Cookie Notices" according to the logger: `@@||geolocation.onetrust.com/cookieconsentpub/$xhr,from=~cbsnews.com|~cnbc.com|~metacritic.com|~teenvogue.com|~vogue.co.jp|~vogue.co.uk|~vogue.com|~vogue.com.tw|~vogue.de|~vogue.es|~vogue.fr|~vogue.in|~vogue.it|~vogue.mx|~vogue.ph`

but
1- I don't see any "eksisozluk111" on that rule so I don't understand why that rule grants an exception to this xhr request.
2- that "geolocation.onetrust.com" request sounds like a tracking request that should be blocked to me

Any insights? Thanks.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
> 1- I don't see any "eksisozluk111" on that rule so I don't understand why that rule grants an exception to this xhr request

that filter is applied for every site / page with exception of those listed (see the leading `~`)

> 2- that "geolocation.onetrust.com" request sounds like a tracking request that should be blocked to me

There were breakages blocking it, so the whitelisting became necessary

**Comment by mapx-** [comment]
I get no `geolocation` request. Even so, you have to report it at easylist repo.

@ryanbr
