### ISSUE TITLE
de.flightsim.to: detection

### ISSUE THREAD

**Issue by AmiDami23** [uBlockOrigin/uAssets#21816]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://de.flightsim.to/file/67060/new-age-scenery-library`

### Category

detection

### Description

I get thius messge from the website
"Please be fair and turn off your adblocker to continue."

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-01-06 23_29_40-New Age Scenery Library für Microsoft Flight Simulator _ MSFS – Mozilla Firefox](https://github.com/uBlockOrigin/uAssets/assets/135400935/26ee3d42-731c-409b-a3da-540ed0d51845)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 118332
 cosmetic: 49064
 scriptlet: 18664
 html: 2000
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37107-222, now
  ublock-badware: 7761-11, now
  ublock-privacy: 946-0, now
  ublock-unbreak: 2231-0, now
  ublock-quick-fixes: 217-0, now
  easylist: 76823-625, now
  easyprivacy: 43392-832, now
  urlhaus-1: 10385-0, 1h.23m
  plowe-0: 3784-1, now
  DEU-0: 7260-3, 1h.23m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 293 ms (selfie)
 maxAssetCacheWait: 70 ms
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 4
  curvedhoney.com: 1
  googletagmanager.com: 1
  pub.network: 2
 extended:
  ##[data-freestar-ad]
  ##+js(abort-current-script, fetch, status)
  ##+js(abort-current-script, document.getElementById, adsblock)
  ##+js(adjust-setInterval, timer)
  ##+js(no-xhr-if, pub.network)
```
</details>

**Comment by D4niloMR** [comment]
I could reproduce on `https://de.flightsim.to/file/67060/new-age-scenery-library`
