### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by mattlodder** [uBlockOrigin/uAssets#21810]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Description

Chrome back button does not work whilst on reddit.com whilst uBlock is enabled. Disabling sovles issue.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115964
 cosmetic: 44203
 scriptlet: 20023
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 199-50, now
 default:
  user-filters: 1-0, never
  easylist: 76823-12, now
  easyprivacy: 43392-32, now
  plowe-0: 3784-1165, now
  ublock-badware: 7757-137, now
  ublock-filters: 36500-204, now
  ublock-privacy: 950-7, now
  ublock-unbreak: 2185-31, now
  urlhaus-1: 10385-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 18 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1892 ms (selfie)
 maxAssetCacheWait: 441 ms
popupPanel:
 blocked: 8
 network:
  reddit.com: 3
  redditmedia.com: 3
  redditstatic.com: 2
 extended:
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(abort-on-property-write, STICKY_CANARY)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by b007zk** [comment]
This happens on firefox... should be reproducible

**Comment by gorhill** [comment]
I am not able to reproduce.

**Comment by b007zk** [comment]
After updating firefox the issue disappeared.

**Comment by b007zk** [comment]
@gorhill  Are you on the latest version of firefox? 122.0 (64-bit)

I am noticing that if I go to a reddit post and immediately try to go back to google search, it works but if I linger in the reddit post for a little (maybe a minute or less) then the back button appears to get blocked by ublock origin

**Comment by gorhill** [comment]
Post the URL of specific reddit post where you can reproduce for sure, to be sure we are testing the same thing at first. Also, are you logged in?

**Comment by b007zk** [comment]
@gorhill It's not even necessary to go to any particular post it seems. You can just go to reddit.com from google earch and after waiting a few seconds the back button will not work anymore. I am logged into reddit yes.

**Comment by b007zk** [comment]
@gorhill Actually I just noticed something. It looks like the **chat window** needs to be open on reddit for this problem to happen. If the chat box is closed, then the back button works fine.

**Comment by D4niloMR** [comment]
I can reproduce, and it seems to be a reddit issue, as this happens with uBO completely disabled.

**Comment by b007zk** [comment]
Hmmm ok, reason I thought it was ublock origin is that I see it blocking something consistently as I  hit the back button

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21810#issuecomment-2782270465 - It doesn't look like the malfunction are caused by the added CSS4/procedural CSS filtering.

I am able to reproduce the bug with an exception added to the my custom filter list.
