### ISSUE TITLE
usa.experian.com: breakage

### ISSUE THREAD

**Issue by Nuru** [uBlockOrigin/uAssets#21814]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://usa.experian.com/login/index`

### Description

Trying to log into `https://usa.experian.com` (specifically `https://usa.experian.com/login/index`) fails with a new account or immediately after a password reset. Whatever would normally trigger further authentication with a one-time passcode. The page gives the error

> The username or password you entered is incorrect.

even if the password was just reset. 

After disabling uBlock, I was able to get past the password prompt to the one-time passcode prompt, and after filling that in I was logged in. 

After that, I was able to log in without requiring a passcode, and after that I was able to re-enable uBlock and still log in. Since I did my best to clear all the caches and cookies (including using an entirely different browser) but never got another prompt for a one-time passcode, I have to conclude that Experian somehow associated my IP address with my account, after which whatever uBlock was blocking was no longer an issue. But up until that point, I tried resetting my password several times, and each time although the reset succeeded, I could not log in with the new password. (Also, each time I reset the password, I tried resetting it to what I had set it to before, and was blocked by a message telling me not to reuse a previous password, so I'm confident the password reset worked.)

### Other extensions used

- 1Password
- Evernote Web Clipper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115957
 cosmetic: 44194
 scriptlet: 19937
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76813-12, 4h.6m
  easyprivacy: 43392-32, 4h.6m
  plowe-0: 3787-1162, 9d.7h.18m
  ublock-badware: 7757-137, 4h.6m
  ublock-filters: 36413-204, 4h.6m
  ublock-privacy: 950-7, 4h.6m
  ublock-quick-fixes: 196-50, 4h.6m
  ublock-unbreak: 2177-31, 4h.6m
  urlhaus-1: 10385-0, 6m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 224 ms (selfie)
 maxAssetCacheWait: 106 ms
```
</details>

**Comment by liamengland1** [comment]
Can't reproduce with default filterlists in Firefox. OTP prompt comes up and I can log in fine.

![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/99a26648-02fa-4d01-9ce9-269b821bc009)

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
