### ISSUE TITLE
computerbild.de: nuisance

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#21823]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.computerbild.de/artikel/cb-Tipps-Software-Geloeschte-Daten-wiederherstellen-5236572.html`

### Category

nuisance

### Description

Cookie Notice

### Other extensions used

- Bitwarden 
- BlockTube
- DeepL
- FrankerFaceZ
- LanguageTool
- Gumbo
- Postman
- Return YouTube Dislike
- SimpleLogin
- SponsorBlock 
- Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 135049
 cosmetic: 122097
 scriptlet: 28194
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2546-1, 17m
  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-only/hosts: 10105-0, now
  easylist-annoyances: 4308-33, now
  easylist-chat: 177-0, now
  easylist-newsletters: 6859-15, now
  easylist-notifications: 2905-86, now
  fanboy-cookiemonster: 49197-166, now
  fanboy-social: 16044-13, now
  ublock-annoyances: 6519-78, now
  ublock-cookies-easylist: 862-862, now
 default:
  user-filters: 0-0, never
  DEU-0: 7260-0, 18m
  easylist: 76846-19, now
  easyprivacy: 43395-127, now
  plowe-0: 3784-1166, now
  ublock-badware: 7757-141, now
  ublock-filters: 36509-240, now
  ublock-privacy: 950-57, now
  ublock-quick-fixes: 200-50, now
  ublock-unbreak: 2184-37, now
  urlhaus-1: 10175-0, 17m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 328 ms (selfie)
 maxAssetCacheWait: 143 ms
popupPanel:
 blocked: 8
 network:
  computerbild.de: 3
  adnxs.com: 1
  asadcdn.com: 3
  jobbio.com: 1
 extended:
  ###billboard
  ##.billboardBtfContainer
  ##.jobbioTeaser
  ##.superbannerBtfContainer
  ##.superbannerContainer
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
test for breakage

`||i.computer-bild.de/assets/cmp-config.js$script,domain=computerbild.de`

**Comment by B1ack3ye** [comment]
The website didn't break for me with this filter.

**Comment by mapx-** [comment]
@ryanbr @Alex-302 for ELC / AA

**Comment by Morku** [comment]
@Alex-302
The change breaks videoplayback here: https://www.computerbild.de/artikel/cb-Tests-Handy-iPhone-14-vs-iPhone-15-Vergleich-Test-Review-36810663.html
