### ISSUE TITLE
checkadblock.ru: ads

### ISSUE THREAD

**Issue by Bunnyisback** [uBlockOrigin/uAssets#21829]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://checkadblock.ru/`

### Category

ads

### Description

"

### Other extensions used

——

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 132273
 cosmetic: 45097
 scriptlet: 18907
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37447-452, now
  ublock-badware: 7767-11, now
  ublock-privacy: 947-1, now
  ublock-unbreak: 2238-1, now
  ublock-quick-fixes: 212-1, now
  adguard-mobile: 8969-132, now
  easylist: 76875-16700, now
  easyprivacy: 43395-845, now
  urlhaus-1: 10315-0, now
  plowe-0: 3784-1, now
  CHN-0: 25899-1269, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4125 ms (selfie)
 maxAssetCacheWait: 221 ms
popupPanel:
 blocked: 0
 no-remote-fonts: true
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
- russian site, enable the russian regional list
- if still viewing ads report here => https://github.com/easylist/ruadlist/issues
