### ISSUE TITLE
trip.businessnews-nigeria.com: ads

### ISSUE THREAD

**Issue by TechyAditya** [uBlockOrigin/uAssets#21822]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://trip.businessnews-nigeria.com/the-smallest-governorate-in-jordan-in-terms-of-population/`

### Category

ads

### Description

Another shortlink site which makes us wait 15 seconds before pressing continue link button and captcha

### Other extensions used

surfshark

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 121
filterset (summary):
 network: 115765
 cosmetic: 44222
 scriptlet: 20028
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76846-12, now
  easyprivacy: 43395-32, now
  plowe-0: 3784-1165, now
  ublock-badware: 7757-137, now
  ublock-filters: 36509-204, now
  ublock-privacy: 950-7, now
  ublock-quick-fixes: 200-50, now
  ublock-unbreak: 2184-31, now
  urlhaus-1: 10175-0, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 457 ms (selfie)
 maxAssetCacheWait: 158 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
You always have to provide the original shortener link.

**Comment by BlazeFTL** [comment]
@mapx- Has To Added Here
```
te-it.com,world2our.com,mobi2c.com,tech5s.co,ez4mods.com,sinonimos.de,bluetechno.net,forexit.online###go_d:remove-attr(disabled)
te-it.com,world2our.com,mobi2c.com,sinonimos.de,bluetechno.net,forexit.online###submitBtn, #go_d, #devozon-snp, #submitBtn, #tp-snp1, #go_d2:others()
te-it.com,world2our.com,mobi2c.com,tech5s.co,ez4mods.com,sinonimos.de,bluetechno.net,forexit.online###submitBtn, #go_d, #devozon-snp, #submitBtn, #tp-snp1, #go_d2:style(display: block !important;)
