### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by PancakeLegend** [uBlockOrigin/uAssets#21838]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=dQw4w9WgXcQ`

### Category

breakage

### Description

Can't unsubscribe from YouTube channels if Ublock Origin is enabled.

Turning off Ublock Origin will re-enable unsubscription.

### Other extensions used

Google dictionary
Google calendar weekend highlighter
Return Youtube dislike
Shazam
Sponsorblock
Youtube Shorts Block
Grammarly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115722
 cosmetic: 44332
 scriptlet: 20016
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 141-1, never
  easylist: 76876-12, now
  easyprivacy: 43395-32, now
  plowe-0: 3784-1165, now
  ublock-badware: 7769-137, now
  ublock-filters: 36455-204, now
  ublock-privacy: 951-7, now
  ublock-quick-fixes: 213-50, now
  ublock-unbreak: 2187-31, now
  urlhaus-1: 10085-0, now
filterset (user): [array of 141 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 162 ms (selfie)
 maxAssetCacheWait: 68 ms
popupPanel:
 blocked: 20
 network:
  youtube.com: 14
  doubleclick.net: 3
  google.com: 2
  google.com.au: 1
 extended:
  ##.ytd-rich-section-renderer.style-scope > .ytd-rich-shelf-rende…
  ###main > #banner.ytd-merch-shelf-renderer
  ###panels > [target-id="engagement-panel-ads"]
  ###related > div#player-ads
  ###scroll-container > #items.ytd-merch-shelf-renderer
  ###ytd-player button.ytp-suggested-action-badge
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
Why did you tick on this?

> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
