### ISSUE TITLE
dlink2.net: popups

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21837]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dlink2.net/jjQR`

### Category

popups

### Description

Original link: `clictune.com/jjQR`

Opera GX ad that covers most of the page. 10 second timer. Clicking anywhere on the top gray area opens a popup window.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116000
 cosmetic: 45973
 scriptlet: 24509
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6521-18, 6m
 default:
  user-filters: 1129-4, never
  easylist: 76876-12, 6m
  easyprivacy: 43395-32, 6m
  plowe-0: 3784-1165, 6m
  ublock-badware: 7769-137, 6m
  ublock-filters: 36458-1278, 6m
  ublock-privacy: 951-7, 6m
  ublock-quick-fixes: 213-50, 1h.55m
  ublock-unbreak: 2187-32, 6m
  urlhaus-1: 10085-0, 6m
filterset (user): [array of 53 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel:
 blocked: 5
 network:
  dlink2.net: 1
  doubleclick.net: 2
  trk-bistiona.com: 1
  youtube.com: 1
 extended:
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
test

```
dlink2.net##+js(rpnt, script, var seconde = 10;, var seconde = 0;)
dlink2.net##+js(set-cookie, clictune_pop, off)
*$frame,domain=dlink2.net
```

**Comment by huyszn** [comment]
> ```
> dlink2.net##+js(rpnt, script, var seconde = 10;, var seconde = 0;)
> dlink2.net##+js(set-cookie, clictune_pop, off)
> *$frame,domain=dlink2.net
> ```
These filters work
