### ISSUE TITLE
braflix.app: nuisance

### ISSUE THREAD

**Issue by ALA-recognize** [uBlockOrigin/uAssets#21830]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.braflix.app/`

### Category

nuisance

### Description

ctrl+shift+i to open devtools does not work, and opening devtools using any other method creates a redirect to google.com

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 115941
 cosmetic: 44212
 scriptlet: 18649
 html: 2006
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37066-258, now
  ublock-badware: 7773-11, now
  ublock-privacy: 947-0, now
  ublock-unbreak: 2233-0, now
  ublock-quick-fixes: 212-1, now
  easylist: 76875-549, now
  easyprivacy: 43395-823, now
  urlhaus-1: 10315-0, now
  plowe-0: 3784-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 921 ms
 maxAssetCacheWait: 334 ms
popupPanel:
 blocked: 2
 network:
  google.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by huyszn** [comment]
These filters both work only on chrome for ctrl+shift+i and the redirect. 
```
braflix.app##+js(aeld, keydown, keyCode)
braflix.app##+js(nosiif, detect)
```
On firefox ctrl+shift+i works but the redirect still occurs.

**Comment by mapx-** [comment]
working fine FF / chrome on my end

**Comment by nocasio-beep** [comment]
in

**Comment by nocasio-beep** [comment]
Ctrl  shift qq good
