### ISSUE TITLE
aftonbladet.se: ads

### ISSUE THREAD

**Issue by Impeccable9** [uBlockOrigin/uAssets#21849]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aftonbladet.se/sportbladet/hockey/a/VPE5d4/nhl-connor-bedard-har-brutit-kaken-blir-borta-lange`

### Category

ads

### Description

Shows an ad before loading the actual video. 
![Capture](https://github.com/uBlockOrigin/uAssets/assets/155859025/d77c41e2-e1b3-4f3b-aea8-a10cddd146a3)

### Other extensions used

600% Sound Volume
Proton Pass
Proton VPN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/155859025/7df74e34-7072-4d89-994c-11f65ff99a5b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 115876
 cosmetic: 44207
 scriptlet: 18641
 html: 2006
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37027-259, now
  ublock-badware: 7774-11, now
  ublock-privacy: 946-0, now
  ublock-unbreak: 2233-0, now
  ublock-quick-fixes: 234-1, now
  easylist: 76901-549, now
  easyprivacy: 43399-823, now
  urlhaus-1: 10225-0, now
  plowe-0: 3784-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 287 ms (selfie)
 maxAssetCacheWait: 114 ms
popupPanel:
 blocked: 22
 network:
  adnxs.com: 3
  brandmetrics.com: 1
  fwmrm.net: 2
  imrworldwide.com: 1
  relevant-digital.com: 1
  schibsted.com: 9
  stickyadstv.com: 4
  userreport.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable the regional list: `Frellwit's Swedish Filter` 

If you still get ads report directly here: https://github.com/lassekongo83/Frellwits-filter-lists/issues
