### ISSUE TITLE
cda.pl: nuisance

### ISSUE THREAD

**Issue by Losif-kun** [uBlockOrigin/uAssets#21845]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cda.pl/`

### Category

nuisance

### Description

There is a big banner on the left and right side of the page. Also there is always a video on top of the page. In screenshots I outlined everything that isn't an ad (and censored my account name with red)

### Other extensions used

Universal Bypass, Sponsor block for youtube, IDM integration module, Shorts Blocker, Return youtube dislike button, Copy All URLS, MEGA, cookie remover 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cda screenshot](https://github.com/uBlockOrigin/uAssets/assets/64921174/54f96544-48e4-4217-a338-a6824604bfda)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 119510
 cosmetic: 44772
 scriptlet: 36944
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist.to/easylist/easylist.txt: 76876-12, now
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=raw: 180-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 23173-25, now
 default:
  user-filters: 4-0, never
  easylist: 76876-76876, now
  easyprivacy: 43395-33, now
  plowe-0: 3784-1166, now
  ublock-badware: 7769-137, now
  ublock-filters: 36462-2241, now
  ublock-privacy: 950-8, now
  ublock-quick-fixes: 213-51, now
  ublock-unbreak: 2187-32, now
  urlhaus-1: 10085-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 797 ms (selfie)
 maxAssetCacheWait: 138 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ###bgad
  ##[class^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; po…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[class^="div-gpt-ad"]
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
1. enable the polish lists

2. 

disable / remove all these lists

```
https://easylist.to/easylist/easylist.txt: 76876-12, now
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=raw: 180-0, now
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 23173-25, now
```

3. add as custom filter:

`cda.pl##.siddeAd`

**Comment by garry-ut99** [comment]
It will be fixed in POL list soon.
