### ISSUE TITLE
chip.de: ads

### ISSUE THREAD

**Issue by Dragodraki** [uBlockOrigin/uAssets#21840]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.chip.de/downloads/c1_downloads_auswahl_44031012.html`

### Description

Ticket about ticket issues regarding chip.de problems:

There are several tickets complaining about extremely advertising on chip.de, e.g. here: 
`https://www.chip.de/downloads/c1_downloads_auswahl_44031012.html` 
for several months now  - some markes as opened, most as closed. The issue still exist. Now, I wonder how thats possible. Either chip.de creates techniques to bypass new methods very very fast or tickets about that problem get marked as closed before a fix was applied to filters of uBO to get rid of them...

And yeah, I tested it against all important steps called above - even with no custom filter and no other addon existing and standard DNS behaviour and cookies cleared. I verified that by setting up a test with FF privacy window too. chip.de contains massive ads and uBO does not block them correctly!

Maybe someone can investigate in this?
All downloading pages of chip.de are targetted (so, almost everything but the pure homepage). It would be really satisfying sending chips new advertismenets finally back to hell, where they belong.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/76787321/e966c063-5429-456f-ad45-4ebffcb03307)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 118328
 cosmetic: 32653
 scriptlet: 18652
 html: 2006
listset (total-discarded, last-updated):
 default:
  user-filters: 224-5, never
  ublock-filters: 37069-406, 1h.10m
  ublock-badware: 7773-11, 1h.10m
  ublock-privacy: 947-1, 1h.10m
  ublock-unbreak: 2233-1, 1h.10m
  ublock-quick-fixes: 213-1, 1h.10m
  easylist: 76876-16650, 1h.10m
  easyprivacy: 43395-830, 1h.10m
  urlhaus-1: 10315-0, 15h.14m
  plowe-0: 3784-1, 8d.12h.29m
  DEU-0: 7261-394, 15h.13m
filterset (user): [array of 224 redacted]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 598 ms
 maxAssetCacheWait: 221 ms
```
</details>

**Comment by mapx-** [comment]
continue here: https://github.com/uBlockOrigin/uAssets/issues/21504
