### ISSUE TITLE
infinityscans.net: detection

### ISSUE THREAD

**Issue by ozhang05** [uBlockOrigin/uAssets#21852]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://infinityscans.net/comic/12/im-the-max-level-newbie/3gf6gscn926gcvrakljftfjq93`

### Category

detection

### Description

Site detects an adblocker when you try to read any manhwa.

I got around this for a while by going into uBO settings and purging all caches whenever it detected me, but it does not seem to work anymore.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116882
 cosmetic: 50104
 scriptlet: 24569
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 1059-7, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  easylist-annoyances: 4308-33, now
  ublock-annoyances: 6523-25, now
 default:
  user-filters: 0-0, never
  easylist: 76901-14, now
  easyprivacy: 43399-43, now
  plowe-0: 3784-1165, now
  ublock-badware: 7770-137, now
  ublock-filters: 36431-210, now
  ublock-privacy: 950-8, now
  ublock-quick-fixes: 228-51, now
  ublock-unbreak: 2187-34, now
  urlhaus-1: 9890-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 627 ms (selfie)
 maxAssetCacheWait: 263 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(no-fetch-if, /googlesyndication|bidgear|marreerouens|pubfu…
  ##+js(no-window-open-if)
  ##+js(remove-node-text, script, ;break;case $.)
```
</details>

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**do not add anymore FFA + abp lists**
