### ISSUE TITLE
all3dp.com: detection

### ISSUE THREAD

**Issue by viclick** [uBlockOrigin/uAssets#21857]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://all3dp.com/`

### Category

detection

### Description

uBlock Origin is detected on All3DP.com, and viewing of the website is prohibited.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-01-09 04_55_59-All About 3D Printing   Additive Manufacturing _ All3DP — Mozilla Firefox](https://github.com/uBlockOrigin/uAssets/assets/61207817/acc8ae79-7ca1-4377-9b84-bfdd846cd49e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115548
 cosmetic: 44212
 scriptlet: 18636
 html: 2006
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37025-258, 7m
  ublock-badware: 7774-11, 7m
  ublock-privacy: 947-0, 8m
  ublock-unbreak: 2233-0, 8m
  ublock-quick-fixes: 229-1, 8m
  easylist: 76908-538, 8m
  easyprivacy: 43404-834, 8m
  urlhaus-1: 9890-0, 8m
  plowe-0: 3784-1, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 878 ms
 maxAssetCacheWait: 315 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  all3dp.com: 1
  doubleclick.net: 1
  google.com: 6
 extended:
  ##.ad-container
  ##.notification
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
@viclick enable `uBlock filters – Annoyances`

**Comment by viclick** [comment]
Success.  Thank you.
