### ISSUE TITLE
Socialblade.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#2185]
### URL(s) where the issue occurs

`https://socialblade.com/`
`https://socialblade.com/youtube/top/100`

### Describe the issue

Adblock detect

### Screenshot(s)

![image](https://user-images.githubusercontent.com/35370833/39662955-8f5dd624-506a-11e8-9240-62c31dbe9056.png) |
--- |

![image](https://user-images.githubusercontent.com/35370833/39662956-a46e1e2a-506a-11e8-8ec6-43e7f23733a3.png) | 
--- |

![image](https://user-images.githubusercontent.com/35370833/39662993-39b4f300-506b-11e8-8427-af77314b8cdc.png) |
--- |

![obraz](https://user-images.githubusercontent.com/35370833/39663004-51526c0e-506b-11e8-98d3-5c3d77e566f8.png) |
--- |

### Versions

- Browser/version: Firefox **59.0.3**
- uBlock Origin version: **16.4**

### Settings

- Default uBO + uBO Annoyance + Cookiemonster

**Comment by mapx-** [comment]
test
`@@||socialblade.com^$generichide`

is it an annoyance or some parts of the site are blocked ?
