### ISSUE TITLE
restegourmet.de: detection

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#21862]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://restegourmet.de/rezeptsuche/_/reis,paprika/_`

### Category

detection

### Description

Click on the first dish/recipe (image) and a popup appears that adblocker has been detected

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/14368203/a5c8bb19-071b-43a0-bd61-f3b6d33d9e5a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 108323
 cosmetic: 50825
 scriptlet: 24504
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  ublock-annoyances: 6534-12, now
 default:
  user-filters: 17-0, never
  DEU-0: 7262-0, now
  easylist: 76908-19, now
  easyprivacy: 43405-41, now
  plowe-0: 3784-1166, now
  ublock-badware: 7770-137, now
  ublock-filters: 36438-221, now
  ublock-privacy: 958-7, now
  ublock-quick-fixes: 227-51, now
  ublock-unbreak: 2187-34, now
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 37 redacted]
 removed:
  edge-scheme
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1380 ms (selfie)
 maxAssetCacheWait: 669 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  symplr.de: 1
 extended:
  ###AdHeader
  ###AD_Top
  ###homead
  ###ad-lead
  ##.ad_label
  ##[data-ad-name]
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 ping for Adguard

**Comment by Yuki2718** [comment]
@JobcenterTycoon They still detects and show interstital ad if you click the image first time. The info is stored deeply at `rg_cookie_simulation` in local storage.

**Comment by Symbai** [comment]
@JobcenterTycoon @Yuki2718 Ads are back, this time they force you to watch a short ad video. Same instructions, click on a dish -> ad popup. Lmk if you need a screenshot or something.

**Comment by JobcenterTycoon** [comment]
Works all fine for me.

**Comment by Symbai** [comment]
The video is blocked but the popup and the delay not. I guess then its more like an "annoyance" ? Where can I report it for the "uBlock filters – Annoyances" list?

**Comment by JobcenterTycoon** [comment]
Fixed in the base list because its part of a ad.
