### ISSUE TITLE
dropbox.com: breakage

### ISSUE THREAD

**Issue by BrandonS8** [uBlockOrigin/uAssets#21861]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://dropbox.com`
`https://www.dropbox.com/home/`

### Description

With uBlock enabled these suggested folders/items (surrounded by green outline in screenshot) are not clickable anymore. When clicking they are supposed to take you to the folder/item, with uBlock on they do nothing though. Tested it on chrome & firefox with just uBlock and it breaks on both.

This view is at dropbox.com/home/

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-09 055852](https://github.com/uBlockOrigin/uAssets/assets/32366023/d0a0d85d-d53d-448a-b6d8-41e6dc1b95ef)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115543
 cosmetic: 44218
 scriptlet: 18647
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37034-193, 6m
  ublock-badware: 7774-11, 6m
  ublock-privacy: 955-0, 6m
  ublock-unbreak: 2233-0, 6m
  ublock-quick-fixes: 228-1, 6m
  easylist: 76908-607, 6m
  easyprivacy: 43405-834, 6m
  urlhaus-1: 9890-0, 6m
  plowe-0: 3784-1, 6m
filterset (user): [empty]
trustedset:
 added: [array of 20 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 352 ms (selfie)
 maxAssetCacheWait: 65 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 127
 network:
  dropbox.com: 127
```
</details>

**Comment by mapx-** [comment]
add

`||dropbox.com/2/ml_platform/log_predictions_events$badfilter`

@ryanbr
