### ISSUE TITLE
foxnews.com: breakage

### ISSUE THREAD

**Issue by C14Alpha** [uBlockOrigin/uAssets#21866]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.foxnews.com/politics/firebrand-house-republican-seeing-massive-surge-desantis-iowa`

### Category

breakage

### Description

FoxNews (and FoxBusiness) detect uBlock and place a login screen over articles (whethere logged in or not).  Logging in to Fox does not resolve the issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ScreenCap 01-09-24](https://github.com/uBlockOrigin/uAssets/assets/89372153/a2606b06-1955-4f5f-95e2-7552d8b085c4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115794
 cosmetic: 44217
 scriptlet: 18648
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37035-193, 53m Δ
  ublock-badware: 7774-11, 53m Δ
  ublock-privacy: 955-0, 53m Δ
  ublock-unbreak: 2233-0, 53m Δ
  ublock-quick-fixes: 228-1, 53m Δ
  easylist: 76908-618, 53m Δ
  easyprivacy: 43405-823, 53m Δ
  urlhaus-1: 10140-0, now
  plowe-0: 3784-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 936 ms (selfie)
 maxAssetCacheWait: 121 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 47
 network:
  foxnews.com: 3
  amazon-adsystem.com: 2
  amp.akamaized.net: 1
  aswpsdkus.com: 1
  atp.fox: 2
  bing.com: 1
  chartbeat.com: 2
  criteo.net: 1
  datadoghq-browser-agent.com: 1
  doubleclick.net: 1
  flipboard.com: 1
  foxnewsplayer-a.akamaihd.net: 1
  google.com: 5
  googletagmanager.com: 2
  h-cdn.com: 1
  imasdk.googleapis.com: 1
  imrworldwide.com: 1
  knotch-cdn.com: 1
  opecloud.com: 1
  outbrain.com: 1
  pix.pub: 1
  scorecardresearch.com: 1
  spot.im: 10
  springserve.com: 1
  taplytics.com: 1
  yahoo.com: 2
  yimg.com: 1
 extended:
  ##.ad-h-250
  ##.ad-w-300
  ##.sticky-ads
  ##.ad-w-728
  ##.ad
  ##.ad-container
  ##.vendor-unit
  ##.amp-ads
  ##.amp-ad-container
  ##[class^="amp-ad-"]
```
</details>

**Comment by mapx-** [comment]
disable uBO => same behaviour

**Comment by pt20223** [comment]
Not sure why this was closed, it doesn't happen when uBO is disabled and you're signed in.   If you're NOT signed in and disable uBO yeah it will popup, since the site wants you to sign in.

**Comment by stephenhawk8054** [comment]
Website shows the article normally for me when logged in with uBO enabled. 

Screenshot:

<details>

![Screenshot 2024-01-10 at 11-03-54 Firebrand House Republican seeing 'massive surge' for DeSantis in Iowa 'Closer than people think'](https://github.com/uBlockOrigin/uAssets/assets/66517106/66dfcbe7-f08b-47c6-981a-4cdeb28a10eb)

</details>
