### ISSUE TITLE
biobiochile.cl: detection

### ISSUE THREAD

**Issue by Gorack1** [uBlockOrigin/uAssets#21874]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.biobiochile.cl/noticias/espectaculos-y-tv/tv/2024/01/09/francisco-vidal-confirma-conversaciones-con-directorio-de-tvn-por-polemica-de-peso-pluma-en-vina-2024.shtml`

### Category

detection

### Description

site lets me read for a few seconds, after that it says that i have to turn of the adblocker

### Other extensions used

honey
yomichan
better ttv
duckduck go privacy esstentials

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 287281
 cosmetic: 243531
 scriptlet: 49110
 html: 2214
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81427-6936, 2m
  adguard-mobile: 9028-19, 2m
  adguard-spyware-url: 1413-93, 2m
  adguard-spyware: 87233-26989, 2m
  block-lan: 56-0, 2m
  curben-phishing: 80737-28, 2m
  adguard-social: 22206-876, 2m
  adguard-cookies: 28354-62, 2m
  ublock-cookies-adguard: 868-0, 2m
  adguard-popup-overlays: 26710-1663, 2m
  adguard-mobile-app-banners: 4889-1071, 2m
  adguard-other-annoyances: 14023-332, 2m
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36964-410, 4m
  ublock-badware: 7768-11, now Δ
  ublock-privacy: 955-0, now Δ
  ublock-unbreak: 2233-1, now Δ
  ublock-quick-fixes: 226-1, now Δ
  easylist: 76939-745, 4m
  easyprivacy: 43405-950, now Δ
  urlhaus-1: 9995-0, 4m
  plowe-0: 3784-84, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1913 ms
 maxAssetCacheWait: 1133 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  digitalproserver.com: 2
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 3
  googletagmanager.com: 1
  mrf.io: 1
  scorecardresearch.com: 1
  teads.tv: 2
 extended:
  ##.post-social-container
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##[id^="ad_sky"]
  ###fb-root:not(body):not(html)
  ##.header-ad-container
  ###ad_top
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `AdGuard Spanish/Portuguese` filter list

**Comment by Gorack1** [comment]
thanks, solved
