### ISSUE TITLE
gq.com: breakage

### ISSUE THREAD

**Issue by shnaps** [uBlockOrigin/uAssets#21876]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gq.com/gallery/the-menswear-essentials-youll-need-in-the-new-year`

### Category

breakage

### Description

When JavaScript is enabled for the page, it goes completely white after loading. Disabling javascript and reloading helps to avoid the issue.

### Other extensions used

I only have AdsBypasser script and no other extensions which do adblocking.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/18357973/5e8c6275-9432-406d-bcaf-1caabab41664)
Disabled javascript.
![image](https://github.com/uBlockOrigin/uAssets/assets/18357973/0e4fc994-2f86-4890-953b-b6352a702e00)
Enabled javascript

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 133129
 cosmetic: 65411
 scriptlet: 20055
 html: 2032
listset (total-discarded, last-updated):
 added:
  RUS-0: 40236-127, 1h.19m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 36966-118, now
  ublock-badware: 7768-11, now
  ublock-privacy: 955-0, now
  ublock-unbreak: 2233-0, now
  easylist: 76939-643, now
  easyprivacy: 43406-823, now
  urlhaus-1: 9995-0, now
  plowe-0: 3784-1, now
  ublock-quick-fixes: 226-1, 1h.19m Δ
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 464 ms (selfie)
 maxAssetCacheWait: 182 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  gq.com: 1
  adsafeprotected.com: 1
  cnevids.com: 1
  conde.digital: 2
  condenastdigital.com: 7
  d20l1z9qfxwqa3.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  fwpixel.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  permutive.app: 1
  yimg.com: 1
```
</details>

**Comment by shnaps** [comment]
Still has the same behaviour with disabled adsbypasser.

**Comment by liamengland1** [comment]
Any error messages in the console?

**Comment by shnaps** [comment]
There are a bunch of errors.
<details>
<summary>First error</summary>
<pre>
DOMException: Node.removeChild: The node to be removed is not a child of this node
    fc https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Lp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    $p https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    zp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Qa https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Qa https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ja https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Tp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    kp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Rp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    B https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    onmessage https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    60053 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    63840 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    64448 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    73935 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    98897 https://www.gq.com/verso/static/4735.795dac2331ddf8e72643.js:12835
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    36380 https://www.gq.com/verso/static/4735.795dac2331ddf8e72643.js:12835
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    10149 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:159
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    24086 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:159
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    61085 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    n https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    O https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    <anonymous> https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    <anonymous> https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
6716.d07ecdfd806fdf2a613d.js:2:756750
    rc https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    callback https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Or https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    dc https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Lp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    $p https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    zp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Qa https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Qa https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ja https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Tp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    kp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Rp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    B https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    onmessage https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    (Async: EventHandlerNonNull)
    60053 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    63840 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    64448 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    73935 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    98897 https://www.gq.com/verso/static/4735.795dac2331ddf8e72643.js:12835
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    36380 https://www.gq.com/verso/static/4735.795dac2331ddf8e72643.js:12835
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    10149 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:159
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    24086 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:159
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    61085 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    n https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    O https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    <anonymous> https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    <anonymous> https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
</pre>
</details>

<details>
<summary>Second error</summary>
<pre>
Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node
    fc https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Lp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    $p https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    zp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Qa https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Qa https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ja https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Tp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    unstable_runWithPriority https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Ha https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    kp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    Rp https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    B https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    onmessage https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    60053 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    63840 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    64448 https://www.gq.com/verso/static/6716.d07ecdfd806fdf2a613d.js:2
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    73935 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    98897 https://www.gq.com/verso/static/4735.795dac2331ddf8e72643.js:12835
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    36380 https://www.gq.com/verso/static/4735.795dac2331ddf8e72643.js:12835
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    10149 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:159
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    24086 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:159
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    61085 https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    a https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    n https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    O https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    <anonymous> https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
    <anonymous> https://www.gq.com/verso/static/presenter-galleries.29d16a85c57d14c9bc5d.js:405
6716.d07ecdfd806fdf2a613d.js:2
</pre>
</details>

**Comment by stephenhawk8054** [comment]
Can you turn off all other extensions (not just the ones with adblocking), restart the browser, open new tab and test again?

**Comment by shnaps** [comment]
Just tried and the issue can be closed now. Just confirmed that there is no issue with ublock filters, one of my addons (BypassPaywall) conflicted with ublock and this broke the site. For some reason it decided that there is paywall or something like that.
