### ISSUE TITLE
thegamescabin.com: detection

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#21871]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thegamescabin.com/how-to-steal-cheese-from-the-dairy-plant-in-vampire-survivors/`

### Category

detection

### Description

A fullscreen adblocker detection popups appears ~1 second after page loaded. Note that refreshing the page a couple of times no longer triggers this popup but visiting another page of this site triggers it again

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 108342
 cosmetic: 50845
 scriptlet: 24508
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  ublock-annoyances: 6531-12, now
 default:
  user-filters: 17-0, never
  DEU-0: 7274-0, now
  easylist: 76938-19, now
  easyprivacy: 43405-41, now
  plowe-0: 3784-1166, now
  ublock-badware: 7764-137, now
  ublock-filters: 36374-146, now
  ublock-privacy: 958-7, now
  ublock-quick-fixes: 225-51, now
  ublock-unbreak: 2187-34, now
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 37 redacted]
 removed:
  edge-scheme
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1380 ms (selfie)
 maxAssetCacheWait: 669 ms
popupPanel:
 blocked: 10
 network:
  thegamescabin.com: 1
  adsafeprotected.com: 2
  advertising.com: 1
  chartbeat.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  merequartz.com: 2
  pubnation.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's admiral
