### ISSUE TITLE
Tall image auto-generated borders

### ISSUE THREAD

**Issue by ZenMasterSych** [uBlockOrigin/uAssets#21872]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

[vk.com](url)

### Description

Normaly, images on this website that are too "tall" have gray-ish borders to them. Today I noticed this abomination instead. Issue does not persist in Edge browser with uBlock enabled.

### Other extensions used

Turned off everything, doesn't help. Turning off uBlock helps though.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

unedited screenshot: https://i.imgur.com/Am6NLTg.png

edited for clarity: https://i.imgur.com/ZOsJhnJ.png

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 134665
 cosmetic: 67311
 scriptlet: 24496
 html: 2255
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1704-0, 51m
  ublock-annoyances: 6486-11, 51m
 default:
  user-filters: 0-0, never
  ublock-filters: 36966-121, 51m
  ublock-badware: 7768-11, 51m
  ublock-privacy: 955-7, 51m
  ublock-unbreak: 2233-4, 51m Δ
  ublock-quick-fixes: 226-1, 51m
  easylist: 76939-650, 51m
  easyprivacy: 43430-1033, 51m
  urlhaus-1: 10140-0, 51m
  plowe-0: 3784-8, 51m
  RUS-0: 40236-136, 51m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  about-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1304 ms
 maxAssetCacheWait: 335 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  mail.ru: 3
  tns-counter.ru: 1
  vk-portal.net: 2
 extended:
  ###ads_left
  ##div[data-ad-view]
  ##div[data-ad]
  ###system_msg
  #@#div[id$="notifiers_wrap"]
  ##+js(abort-on-property-read, Groups.showDisclaimer)
  ##+js(href-sanitizer, a[href*="/away.php?"], ?to)
  ##+js(set-constant, PageBottomBanners, undefined)
  ##+js(set-constant, Unauthorized2, undefined)
  ##+js(set-constant, noAdsAtAll, {})
</details>

**Comment by krystian3w** [comment]
Try update RU Ad List twice?

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/cf7aaeec431548b670f5aa527ba9422982c712a7

**Comment by ZenMasterSych** [comment]
> Fix: [easylist/ruadlist@cf7aaee](https://github.com/easylist/ruadlist/commit/cf7aaeec431548b670f5aa527ba9422982c712a7)

thanks!
