### ISSUE TITLE
loanoffering.in: detection

### ISSUE THREAD

**Issue by Noorhasanrz** [uBlockOrigin/uAssets#21882]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://loanoffering.in/want-to-apply-for-a-business-loan-here-is-a-checklist-of-documents-you-will-need/`

### Category

detection

### Description

This is a link shortener page and it's detected uBlock.
This is link shortener url - https://modijiurl.com/1NiG

### Other extensions used

None

### Screenshot(s)

![Screenshot_2024-01-10-17-13-19-36_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/145339882/cc8481b7-c66f-42c8-a5c1-778ee1dd7d67)

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 117091
 cosmetic: 35672
 scriptlet: 18720
 html: 2011
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37339-365, now
  ublock-badware: 7762-11, now
  ublock-privacy: 959-1, now
  ublock-unbreak: 2238-1, now
  ublock-quick-fixes: 226-1, 1m Δ
  adguard-mobile: 9028-132, now
  easylist: 76939-16690, now
  easyprivacy: 43407-833, now
  urlhaus-1: 9995-0, 1m
  plowe-0: 3785-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 476 ms (selfie)
 maxAssetCacheWait: 174 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 4
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Noorhasanrz** [comment]
Issue resolved Thanks bro 👍

**Comment by spidy2356** [comment]
@Noorhasanrz sir, redirect url not work. plz check.
link: https://modijiurl.com/Hotleakes (maybe nsfw inside)
