### ISSUE TITLE
formulatv.com: breakage

### ISSUE THREAD

**Issue by UserPizza** [uBlockOrigin/uAssets#21887]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.formulatv.com`

### Description

videos no load in this site..

`https://www.formulatv.com/videos/kelsey-grammer-regresos-sitcoms-funcionar-frasier-27644/`

I tested this filter: `@@||fundingchoicesmessages.google.com^$xhr,script,domain=www.formulatv.com` and works the videos, but getting anti-adblocker in this other page if scroll down:

`https://www.formulatv.com/noticias/la-isla-de-las-tentaciones-7-alex-marienta-sextos-126171/`

### Other extensions used

no others extension actived... but today i see this .. `This means that the adblocker was slowing down Google Chrome.`

![1](https://github.com/uBlockOrigin/uAssets/assets/146446273/78ad70d4-8c8a-4c78-ac3a-d2d1569bfb32)

after closing chrome and reopening again.. the **ERROR** gone..  I remember that a few months ago, the same problem happened to me.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![aa](https://github.com/uBlockOrigin/uAssets/assets/146446273/84d9ea9d-1a73-456b-866c-040c7e6faacb)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 118692
 cosmetic: 52317
 scriptlet: 24891
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6530-11, 33m
 default:
  user-filters: 0-0, never
  easylist: 76978-12, 33m
  easyprivacy: 43409-32, 33m
  plowe-0: 3787-1167, 33m
  spa-0: 3777-19, 33m
  spa-1: 5706-210, 33m
  ublock-badware: 7764-137, 33m
  ublock-filters: 36385-149, 33m
  ublock-privacy: 962-7, 33m
  ublock-quick-fixes: 225-51, 33m
  ublock-unbreak: 2187-34, 33m
  urlhaus-1: 10170-0, 33m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 143 ms (selfie)
 maxAssetCacheWait: 88 ms

```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||fundingchoicesmessages.google.com/i/$script,3p,domain=formulatv.com
@@||fundingchoicesmessages.google.com/f/$script,3p,domain=formulatv.com
```

**Comment by UserPizza** [comment]
videos works..

but.. the filters enabling anti-adblock here:

`https://www.formulatv.com/noticias/la-isla-de-las-tentaciones-7-alex-marienta-sextos-126171/`

**Comment by stephenhawk8054** [comment]
I don't see anti-adblock on that page. Can you screenshot how it looks like?

Also, can you screenshot `chrome://extensions` page?

**Comment by UserPizza** [comment]
For anti-adblock is in the main post click in Screenshots 

extension page

![ext](https://github.com/uBlockOrigin/uAssets/assets/146446273/ad0312bb-61a0-45cc-8639-6538c4ff052b)

Only:

- picture-in-picture
- 7TV 
- uBlock Origin

enabled

**Comment by stephenhawk8054** [comment]
Keep the above 2 filters, can you add this one?

```adb
@@||formulatv.com^$ghide
```

**Comment by UserPizza** [comment]
perfect now! 

if you cant reproduce the issue.. how solved that XD

thanks

**Comment by stephenhawk8054** [comment]
It appears randomly for me. I have to refresh some times to make it appear.

---

@Yuki2718 For Adguard Spanish list?

```adb
@@||fundingchoicesmessages.google.com/i/$script,3p,domain=formulatv.com
@@||fundingchoicesmessages.google.com/f/$script,3p,domain=formulatv.com
@@||formulatv.com^$ghide
```

**Comment by Yuki2718** [comment]
AG doesn't block `fundingchoicesmessages.google.com`. I can't reproduce anti-adb either. @AdamWr
