### ISSUE TITLE
[nsfw] reddxxx.com: ads

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21883]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://reddxxx.com/`

### Category

ads

### Description

Ad placeholders when you scroll down. A blank ad appears at the bottom right of the site where you can close it in 5 seconds. Ad placeholders also appear in posts like in 

`https://reddxxx.com/r/TittyDrop/comments/14z9wck/my_boobs_are_perfect_for_tittyfuck_cum_and_try`

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116149
 cosmetic: 45992
 scriptlet: 24534
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6530-16, now
 default:
  user-filters: 84-3, never
  easylist: 76939-12, now
  easyprivacy: 43408-32, now
  plowe-0: 3786-1167, now
  ublock-badware: 7764-137, now
  ublock-filters: 36389-164, now
  ublock-privacy: 962-7, now
  ublock-quick-fixes: 225-51, now
  ublock-unbreak: 2187-32, now
  urlhaus-1: 10170-0, now
filterset (user): [array of 54 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel:
 blocked: 9
 network:
  reddxxx.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  juicyads.com: 1
  magsrv.com: 2
  pemsrv.com: 1
  rkgwzfwjgk.com: 1
```
</details>

**Comment by mapx-** [comment]
```
reddxxx.com##.items-center:has-text(/^ad$/)
reddxxx.com##.w-screen.backdrop-blur-md
reddxxx.com##[role="gridcell"]:has-text(/^AD$/)
```

last one for the home page (but removing only the AD item, not the cell)

@ryanbr
