### ISSUE TITLE
defenseworld.net: ads

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21885]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.defenseworld.net/2024/01/10/nvidia-co-nasdaqnvda-is-balboa-wealth-partners-3rd-largest-position.html`

### Category

ads

### Description

Marketbeat ad at the bottom right of the page.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/58f29a35-e8fb-40b3-a60f-bbab7d0f1f8d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116150
 cosmetic: 45992
 scriptlet: 24534
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6530-11, 1h.55m
 default:
  user-filters: 50-7, never
  easylist: 76939-12, 1h.54m
  easyprivacy: 43408-32, 1h.54m
  plowe-0: 3786-1167, 1h.54m
  ublock-badware: 7764-137, 1h.55m
  ublock-filters: 36389-130, 1h.55m
  ublock-privacy: 962-7, 1h.55m
  ublock-quick-fixes: 225-51, 1h.55m
  ublock-unbreak: 2187-32, 1h.55m
  urlhaus-1: 10170-0, 1h.55m
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel:
 blocked: 8
 network:
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  marketbeat.com: 2
  onesignal.com: 1
  statcounter.com: 2
 extended:
  ##.in-article-ad
  ##ins.adsbygoogle
  ##a[href*="NativeDisplayAdID"]
  ##+js(addEventListener-defuser, mouseleave, NativeDisplayAdID)
```
</details>

**Comment by mapx-** [comment]
```
defenseworld.net##[href^="https://www.marketbeat.com/scripts/redirect.aspx"]
defenseworld.net###mb-bar
```

@ryanbr
