### ISSUE TITLE
exego.app: detection

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#21895]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://exego.app/H0fOmv`

### Description

The site detects ad-blockers.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/0fdd573f-8722-4fc7-a4c0-7dafd5fc34a6)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by Hazuki-san** [comment]
Is there something I need to add about this?

**Comment by Yuki2718** [comment]
> Is there something I need to add about this?

Your Configuration is empty. Provide them.

**Comment by Hazuki-san** [comment]
My configuration is default config. Using the stock one.

**Comment by Yuki2718** [comment]
The destination says
> Your link has been generated by another IP address. Please use the same IP.

Is it possible I have to use the same IP?

**Comment by Hazuki-san** [comment]
That's weird, I've tried with multiple IPs. I can still access fine. Is there any error screen I can see?

**Comment by Yuki2718** [comment]
Please copy and paste Troubleshooting info in case.

**Comment by Hazuki-san** [comment]
```
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 135494
 cosmetic: 84289
 scriptlet: 37534
 html: 0
listset (total-discarded, last-updated):
 added:
  THA-0: 1468-3, now
  adguard-generic: 81526-490, now
 default:
  user-filters: 9-1, never
  easylist: 76982-1680, 1h.35m Δ
  easyprivacy: 43408-128, 1h.35m Δ
  plowe-0: 3787-1178, now
  ublock-badware: 7774-317, 7m
  ublock-filters: 36396-3427, 7m
  ublock-privacy: 963-7, 7m
  ublock-quick-fixes: 187-50, 7m
  ublock-unbreak: 2187-98, 7m
  urlhaus-1: 10325-0, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 434 ms (selfie)
 maxAssetCacheWait: 233 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  arglingpistole.com: 1
  asacdn.com: 1
  demand.supply: 1
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##.steps-to-earn, .flex.share-icons-container, .register-banner,…
  ##+js(no-fetch-if, pagead2.googlesyndication.com)
  ##+js(abort-current-script, document.createElement, break;case $…
  ##+js(addEventListener-defuser, click, handleClick)
  ##+js(abort-on-stack-trace, Object, /(?=^(?!.*(https)))/)
  ##+js(set-constant, blurred, false)
  ```

**Comment by Hazuki-san** [comment]
Alright, I wiped everything to factory settings. It seems to be working fine now.

**Comment by gorhill** [comment]
The following filter is causing the `prevent-fetch` scriptlet to throw:

    exego.app##+js(aost, Object, /(?=^(?!.*(https)))/)

Solution is to use safe `Object_defineProperty`, which is already declared. It's unrelated to the commit you mention, the exception occurs when setting the `url` property which has been there since long.

**Comment by rrrcabral** [comment]
i also have problem is this site

**Comment by detyso** [comment]
still ads After Clicking im not a robot it gets redirected to other sites  https://exego.app/GdvGUG

**Comment by gorhill** [comment]
Maybe I am too late to investigate but I am not seeing a difference when following the steps.

**Comment by gorhill** [comment]
In neither Chromium or Firefox do I see a match for `open` when I use `exego.app##+js(aeld)`.

**Comment by D4niloMR** [comment]
On my end that script is commented out
