### ISSUE TITLE
anix.to: [unknown]

### ISSUE THREAD

**Issue by GoggieRene** [uBlockOrigin/uAssets#21892]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://anix.to/home`

### Category

[unknown]

### Description

This page started popping up about in early Jan 2024. I've never seen it before. 

### Other extensions used

TWP Translate Web Pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 300662
 cosmetic: 255395
 scriptlet: 49345
 html: 2221
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81511-4074, now
  adguard-mobile: 9032-60, now
  adguard-spyware-url: 1421-95, now
  adguard-spyware: 87232-1637, now
  block-lan: 56-0, now
  curben-phishing: 81216-29, now
  adguard-social: 22211-51, now
  adguard-cookies: 28325-44, now
  ublock-cookies-adguard: 872-7, now
  adguard-popup-overlays: 26724-1011, now
  adguard-mobile-app-banners: 4891-20, now
  adguard-other-annoyances: 14026-439, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 92-12, never
  ublock-filters: 36986-64, now
  ublock-badware: 7773-11, now
  ublock-privacy: 959-0, now
  ublock-unbreak: 2233-1, now
  ublock-quick-fixes: 225-54, now
  easylist: 76982-1899, now
  easyprivacy: 43408-26414, now
  urlhaus-1: 10065-0, now
  plowe-0: 3787-1667, now
filterset (user): [array of 92 redacted]
trustedset:
 added: [array of 81 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 757 ms (selfie)
 maxAssetCacheWait: 311 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  amung.us: 1
  googletagmanager.com: 1
  sharethis.com: 2
 extended:
  ##.sharethis-inline-share-buttons
  ##+js(no-window-open-if, _blank)
  ##+js(set-cookie, __pf, 1)
  ##+js(no-window-open-if)
```
</details>

**Comment by GoggieRene** [comment]
Hi,

Sorry I put the URL in another place. 

https://antix.to/home

Goggie

**Comment by mapx-** [comment]
antix ? anix ?

How do you get that address ? clicking on some page ? using some extension ?

`anix.to` is working fine on my end

**Comment by GoggieRene** [comment]
Hi,

I got the address from my GitHub report page from when I reported it as a popup. Yes the page works fine, but to me it’s an annoying popup in my Firefox browser with pop up blocker enabled and uBlock extension running. I thought I was reporting it to you guys to stop it popping up again. Thank you.

Googie

**Comment by mapx-** [comment]
> pop up blocker enabled

- disable any other extension, keep only uBO enabled and test again
- provide a screenshot with whatever popup you get there

**Comment by GoggieRene** [comment]
I use a site called 123series a lot and get antix popups randomly. I just got this new one tonight. https://netu.ac/
![Screenshot 2024-01-11 at 20 07 45](https://github.com/uBlockOrigin/uAssets/assets/100321522/d7c8533d-da59-4284-9d24-25bfc8052670)

**Comment by mapx-** [comment]
without the complete steps, links to reproduce your issue we cannot investigate. closing.

**Comment by GoggieRene** [comment]
I did what you asked me to do. What is imcomplete?

 
 

Sent: Thursday, January 11, 2024 at 8:26 PM

**Comment by mapx-** [comment]
1. go to example.com
2. click this element
3. I get a specific (link) popup 
4. etc

**Comment by GoggieRene** [comment]
I see what you mean, but the antix popup on 123series.nl appears randomly. Unless you spend an hour or more there binging tv shows you may not encounter it. 

Any advice on how to report random ones?
