### ISSUE TITLE
Can't reply to comments on Mobile Nations sites (Android Central, Windows Central, etc) with EasyList enabled

### ISSUE THREAD

**Issue by PalZer0** [uBlockOrigin/uAssets#219]
### URL(s) where the issue occurs

http://www.androidcentral.com
http://www.windowscentral.com
http://www.imore.com
http://www.crackberry.com
http://www.vrheads.com
http://www.teslacentral.com
http://www.connectedly.com

### Describe the issue

Replying to comments is impossible as I get redirected to a page full of code on every attempt.

1. Log into your Mobile Nations Passport account.
2. Click on a story on any of the sites listed in the previous section.
3. Click "Reply" on any comment.
4. The browser should redirect to a page filled with code.

### Versions

- Browser/version: Firefox 50.0.2
- uBlock Origin version: 1.10.0

### Settings

Only change is unchecking "Show number of blocked requests on the icon" but the issue still occurs after resetting to defaults and updating the default filter lists.

### Notes

After disabling all the various filter lists, I've determined that it's a filter in EasyList that is causing this issue. As long as EasyList is enabled, no other filter list changes will make a difference.

**Comment by gorhill** [comment]
> with EasyList enabled

Report the issue to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=64>.
