### ISSUE TITLE
shareus.io: nuisance

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#21907]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shareus.io/iZJBWZ`

### Category

nuisance

### Description

cannot continue and i have to click ads to continue

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium Mobile: 110
filterset (summary):
 network: 127246
 cosmetic: 164596
 scriptlet: 29212
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6610-197, now Δ
 default:
  user-filters: 34-2, never
  adguard-mobile: 9036-16, now
  easylist: 76984-121, now Δ
  easyprivacy: 43408-157, now Δ
  plowe-0: 3787-1243, now
  ublock-badware: 7763-138, now Δ
  ublock-filters: 36773-630, now Δ
  ublock-privacy: 964-9, now Δ
  ublock-quick-fixes: 187-51, now Δ
  ublock-unbreak: 2192-36, now Δ
  urlhaus-1: 10325-0, now
filterset (user): [array of 34 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2280 ms
 maxAssetCacheWait: 720 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 11
 network:
  shareus.io: 7
  google.com: 1
  googletagmanager.com: 1
  taboola.com: 1
  unpkg.com: 1
 extended:
  ##.MuiAlert-message
  ##.share-buttons-container
  ##.share-button
  ##.adunit-container
```
</details>

**Comment by mapx-** [comment]
Did you test it disabling uBO ?

**Comment by Fatcavill** [comment]
yes i get open link button but i have to click on ads

**Comment by D4niloMR** [comment]
Test:

```adb
@@||dg.jamwoodvises.com/i03ddHLe2A1UgyqW/55010|$popup,domain=shareus.io
shareus.io##+js(trusted-set, document.visibilityState, hidden)
shareus.io##+js(nano-sib, wo(_l, 1000, 0.001)
shareus.io#@#.adunit-container
```

Maybe something better could be done with `$replace`

**Comment by Fatcavill** [comment]
I can see that open link button but cant get to next page

**Comment by D4niloMR** [comment]
Did you click on "Download your file now" and came back?

**Comment by Fatcavill** [comment]
oh sorry it is working now

**Comment by Fatcavill** [comment]
It is not working again can anyone fix

**Comment by Fatcavill** [comment]
How can i get past get link ?

**Comment by Fatcavill** [comment]
from telegram `https://shrs.link/uq7ODG`

**Comment by huyszn** [comment]
The `Open Link` button works after you click on the `Download Your File Now` ad link twice.

**Comment by ItsProfessional** [comment]
Hosting sites and link shorteners are to be reported here: https://github.com/uBlockOrigin/uAssets/discussions/17361
Continue there.

**Comment by D4niloMR** [comment]
working ok for me with 

```adb
shareus.io##+js(nano-stb, ()=>{, *, 0.001)
shareus.io##+js(nowoif)
@@||dg.jamwoodvises.com^$popup,from=shareus.io,badfilter
shareus.io#@#+js(trusted-set-constant, document.visibilityState, hidden)
```

**Comment by D4niloMR** [comment]
seems to, to always work I had to remove the `nano-stb`

**Comment by Fatcavill** [comment]
can confirm works thank you bro

**Comment by Fatcavill** [comment]
hello the site is changed can the ads and timer be skipped ?

**Comment by D4niloMR** [comment]
seems broken for me, can't pass through even with uBO disabled.
