### ISSUE TITLE
LogRocket, a user session recorder, Blog hosted with Medium is blocked

### ISSUE THREAD

**Issue by wesamco** [uBlockOrigin/uAssets#2190]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`blog.logrocket.com`

### Describe the issue
this is a blog for a user session recorder provider, can we unfilter it and if yes should we?

https://github.com/uBlockOrigin/uAssets/blob/6a0294dd4ebf54b5a2d00797af6a6538e5f49a2c/filters/privacy.txt#L141
https://github.com/uBlockOrigin/uAssets/blob/2766a35c1097bbef2ecf74787868bba682748be4/thirdparties/pgl.yoyo.org/as/serverlist#L1741

### Versions

- Browser/version: Google Chrome 66.0.3359.139(Official Build) (64-bit) (cohort: Stable)
- uBlock Origin version: 1.16.2

### Settings
none

### Notes
the blogging platfom/service Medium has a feature where it enables blogs to use their own domain for their Medium blog, it's the same Medium blog (hosted by Medium), so Medium.com's filters should apply, 
How can this be solved?

**Comment by mapx-** [comment]
does it work for you ?
`||logrocket.com^$badfilter`

**Comment by wesamco** [comment]
Yup, thanks.

@mapx-  incidentally by checking the logger on that page I noticed the subdomain `log.logrocket.io` is being used for tracking.
`https://log.logrocket.io/fbcom/tr/?` with these vars in query strings:

'id': | 000000000000000
-- | --
'ev': | PageView
'dl': | https://blog.logrocket.com/
'rl': | <directing url>
'if': | false
'ts': | 0000000000000
'sw': | `<screen width>`
'sh': | `<screen height>`
'v': | 0.0.00
'r': | stable
'a': | seg
'ec': | 0
'o': | 00
'it': | 0000000000000

returned a blank white 1x1 gif.
here are other requests with other /routes/
`/js/heap-0000000000.js`
`heap/h?`
`/fb/en_US/fbevents.js`
`/fb/signals/config/000000000000000?v=0.0.00&r=stable`
`/a.js/v1/<GUID>/a.js`
so just add `log.logrocket.io`.

**Comment by gwarser** [comment]
@mapx- why not `||logrocket.com^$third-party`?

https://old.reddit.com/r/uBlockOrigin/comments/914dvt/without_any_rhyme_or_reason_some_pages_in_my/

**Comment by gwarser** [comment]
EasyPrivacy have it https://github.com/uBlockOrigin/uAssets/commit/83eab34fa01d02ccacc58382275fc24d216500e7
