### ISSUE TITLE
meetings.smartrecovery.org: breakage

### ISSUE THREAD

**Issue by scott31339** [uBlockOrigin/uAssets#21918]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://meetings.smartrecovery.org/meetings/`

### Category

breakage

### Description

Unable to enter a city/state/zip in the box with UBlock turned on. Once turned off, the cookies message in the bottom right shows up - and then once authorized, the site allows city/state to be entered.

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 120487
 cosmetic: 117265
 scriptlet: 28226
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4309-32, now
  easylist-chat: 177-0, now
  easylist-newsletters: 6868-15, now
  easylist-notifications: 2906-86, now
  fanboy-cookiemonster: 49223-166, now
  fanboy-social: 16057-13, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6533-78, 1h.10m
  ublock-cookies-easylist: 872-872, now
 default:
  user-filters: 0-0, never
  easylist: 77037-12, 1h.10m
  easyprivacy: 43408-118, 1h.10m
  plowe-0: 3787-1167, now
  ublock-badware: 7784-137, 1h.10m
  ublock-filters: 36391-150, 1h.10m
  ublock-privacy: 962-9, 1h.10m
  ublock-quick-fixes: 188-50, 1h.10m
  ublock-unbreak: 2187-35, 1h.10m
  urlhaus-1: 10325-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 395 ms (selfie)
 maxAssetCacheWait: 176 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by D4niloMR** [comment]
Add
`meetings.smartrecovery.org###cookieconsentmodal ~ .modal-backdrop`

@ryanbr
