### ISSUE TITLE
boardingpass.ro: detection

### ISSUE THREAD

**Issue by Klendat** [uBlockOrigin/uAssets#21915]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://boardingpass.ro/hisky-zboruri-din-cluj-napoca-si-chisinau-spre-new-york-cu-escala-la-bucuresti/`

### Category

detection

### Description

site detects ublock and blocks any reading

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-11 220436](https://github.com/uBlockOrigin/uAssets/assets/7203850/84d17ffd-a75b-4e04-b163-a9d7c149b53c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116045
 cosmetic: 44238
 scriptlet: 20018
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  easylist: 76982-12, 1h.50m
  easyprivacy: 43408-32, 1h.50m
  plowe-0: 3787-1167, now
  ublock-badware: 7774-137, 1h.50m
  ublock-filters: 36396-128, 1h.50m
  ublock-privacy: 962-7, 1h.50m
  ublock-quick-fixes: 186-50, 1h.50m
  ublock-unbreak: 2187-31, 1h.50m
  urlhaus-1: 10325-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 63 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 677 ms (selfie)
 maxAssetCacheWait: 266 ms
popupPanel:
 blocked: 22
 network:
  ezodn.com: 1
  google-analytics.com: 1
  google.com: 13
  googlesyndication.com: 3
  googletagmanager.com: 1
  media.net: 1
  onesignal.com: 1
  quantserve.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
@Klendat enable the romanian list
