### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Whopperwhite** [uBlockOrigin/uAssets#21910]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

The youtube page is detecting ublock origin now :(

And now I am unable to watch videos without ads, please fix this bug dear developers of unlock origin 😭🙏

### Other extensions used

none.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/156359605/930e4428-274a-46c6-bcbc-0c364bf34c9e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116106
 cosmetic: 44233
 scriptlet: 20018
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77037-12, now
  easyprivacy: 43408-32, now
  plowe-0: 3787-1167, now
  ublock-badware: 7784-137, now
  ublock-filters: 36391-129, now
  ublock-privacy: 962-7, now
  ublock-quick-fixes: 188-50, now
  ublock-unbreak: 2187-31, now
  urlhaus-1: 10325-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1186 ms (selfie)
 maxAssetCacheWait: 256 ms
popupPanel:
 blocked: 7
 network:
  youtube.com: 1
  doubleclick.net: 3
  google.co.in: 1
  google.com: 2
 extended:
  ###panels > [target-id="engagement-panel-ads"]
  ###related > div#player-ads
  ###ytd-player button.ytp-suggested-action-badge
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by JobcenterTycoon** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/20586

**Comment by JBL1503** [comment]
Same, blocks youtube
