### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by DBeitniz** [uBlockOrigin/uAssets#21911]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

Youtube surely just rolled out a new update that detects the uBO (Again...), they still think we will buy YT Premium, lol, never doing that.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116106
 cosmetic: 44233
 scriptlet: 20018
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77037-12, 4m
  easyprivacy: 43408-32, 4m
  plowe-0: 3787-1167, 4m
  ublock-badware: 7784-137, 4m
  ublock-filters: 36391-129, 4m
  ublock-privacy: 962-7, 4m
  ublock-quick-fixes: 188-50, 4m
  ublock-unbreak: 2187-31, 4m
  urlhaus-1: 10325-0, 4m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 158 ms (selfie)
 maxAssetCacheWait: 50 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/20586

**Comment by mapx-** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/20586
