### ISSUE TITLE
wunderground.com: ads

### ISSUE THREAD

**Issue by xcoldfyrex** [uBlockOrigin/uAssets#21924]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wunderground.com/weather/us/wa/port-orchard/47.53,-122.64`

### Category

nuisance

### Description

Search locations at top is covered by translucent box preventing user input

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 117109
 cosmetic: 35684
 scriptlet: 18700
 html: 2014
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37331-362, 31m
  ublock-badware: 7792-11, 31m
  ublock-privacy: 958-1, 31m
  ublock-unbreak: 2238-1, 31m
  ublock-quick-fixes: 190-1, 31m
  adguard-mobile: 9035-132, now
  easylist: 77047-16693, 31m
  easyprivacy: 43409-834, 31m
  urlhaus-1: 9905-0, now
  plowe-0: 3787-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2448 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 12
 network:
  amplitude.com: 2
  confiant-integrations.net: 1
  doubleclick.net: 1
  googlesyndication.com: 4
  instana.io: 2
  moatads.com: 1
  scorecardresearch.com: 1
 extended:
  ##+js(abort-on-property-write, _sp_)
```
</details>

**Comment by gorhill** [comment]
Uncheck "Ignore generic cosmetic filters" in "Filter lists" pane.
