### ISSUE TITLE
makemytrip.com: breakage

### ISSUE THREAD

**Issue by AkhileshLvsn** [uBlockOrigin/uAssets#21937]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.makemytrip.com/`

### Category

breakage

### Description

When I open the MakeMyTrip.com with uBO on it gets detected I suppose and the page content is not shown. But where as uBO is disabled the page content loads.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 385229
 cosmetic: 368237
 scriptlet: 54409
 html: 2329
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1m
  adguard-generic: 81549-8102, now
  adguard-spyware-url: 1421-95, now
  adguard-spyware: 87237-27181, now
  block-lan: 56-0, now
  curben-phishing: 81998-31, now
  adguard-social: 22343-889, now
  adguard-cookies: 28346-74, now
  ublock-cookies-adguard: 913-0, now
  adguard-popup-overlays: 26741-1729, now
  adguard-mobile-app-banners: 4900-1072, now
  adguard-other-annoyances: 14035-340, now
  [47 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37345-590, now
  ublock-badware: 7792-11, now
  ublock-privacy: 959-0, now
  ublock-unbreak: 2238-0, now
  ublock-quick-fixes: 202-1, now
  adguard-mobile: 9038-19, now
  easylist: 77193-1257, now
  easyprivacy: 43412-1165, now
  urlhaus-1: 10395-0, now
  plowe-0: 3782-84, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2621 ms
 maxAssetCacheWait: 1703 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  mmtcdn.com: 2
  webengage.com: 1
 extended:
  ###top-banner
  ##.socialMediaLinks
  ##.appDnldCnt
  ###appDownloadWrapper
  ##.adtech-desktop
  ##div[data-cy^="AdTechCard_"]
  ##+js(trusted-set-session-storage-item, opd, "1")
  ##+js(set-local-storage-item, altses, false)
  ##+js(set-session-storage-item, altses, false)
```
</details>

**Comment by gorhill** [comment]
Closing as invalid because:

> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

>     [47 lists not shown]: [too many]

We ask people to report issues for default lists. For too heavily customized settings, you will have to investigate on your side which list(s) is causing your issue and report to the maintainers of that list -- we do not have the free time to investigate such heavily customized settings.

**Comment by gorhill** [comment]
Your `###top-banner` filter is what is causing your issue. Find from which list it's coming from.
