### ISSUE TITLE
nanoreview.net: ads

### ISSUE THREAD

**Issue by Sym8** [uBlockOrigin/uAssets#21930]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nanoreview.net/en/soc-compare/qualcomm-snapdragon-7s-gen-2-vs-qualcomm-snapdragon-695`

### Category

ads

### Description

Leftover empty ad space

### Other extensions used

Dark reader, Google search fixer tampermonkey.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-01-12-15-07-22-21_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/66876418/12d412b4-386f-447e-975e-3aabe160b883)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 119902
 cosmetic: 88050
 scriptlet: 24105
 html: 2224
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28341-53, now
  easylist-newsletters: 6869-7, now
  easylist-notifications: 2907-4, now
  ublock-annoyances: 6552-929, now
  ublock-cookies-adguard: 910-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37348-168, now
  ublock-badware: 7792-11, now
  ublock-privacy: 959-0, now
  ublock-unbreak: 2238-0, now
  ublock-quick-fixes: 191-1, now
  adguard-mobile: 9037-102, now
  easylist: 77049-678, now
  easyprivacy: 43410-910, now
  urlhaus-1: 9905-0, now
  plowe-0: 3787-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 270 ms (selfie)
 maxAssetCacheWait: 126 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  erling.online: 2
  nanostatistics.net: 2
  quantcast.com: 1
  vlitag.com: 2
 extended:
  ##.sinad_only_desktop
  ##.adsbyvli
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
##.sinad_only_mobile
```

@Yuki2718 I'm not sure if it's for EL or Adguard Mobile?

**Comment by stephenhawk8054** [comment]
```adb
nanoreview.net##div[class^="wisinad_only_"]
```

cc @ryanbr

**Comment by stephenhawk8054** [comment]
```adb
nanoreview.net##.sewisinad_only_desktop
```

@ryanbr

**Comment by xandaronox** [comment]
again for mobile view

```adb
nanoreview.net##div.gtx_lol_o_mobile
```
