### ISSUE TITLE
blog.fastssh.com: detection

### ISSUE THREAD

**Issue by lakshitha5462** [uBlockOrigin/uAssets#21938]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.fastssh.com/vpn-protocol/vless/how-to-use-vless-on-windows/`

### Category

detection

### Description

detect adblock

### Other extensions used

reek anti adblock killer list

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116309
 cosmetic: 44266
 scriptlet: 20024
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
 default:
  user-filters: 0-0, never
  easylist: 77193-12, now
  easyprivacy: 43412-32, now
  plowe-0: 3782-1168, now
  ublock-badware: 7794-137, 8m
  ublock-filters: 36398-129, now
  ublock-privacy: 962-7, 8m
  ublock-quick-fixes: 189-50, 8m
  ublock-unbreak: 2187-31, 8m
  urlhaus-1: 10395-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 724 ms (selfie)
 maxAssetCacheWait: 174 ms
popupPanel:
 blocked: 8
 network:
  googlesyndication.com: 6
  shriftskats.com: 1
  wp.com: 1
 extended:
  ##+js(no-fetch-if, adsbygoogle)
```
</details>

**Comment by ItsProfessional** [comment]
> reek anti adblock killer list

Remove that, and test again.

**Comment by gorhill** [comment]
> [x] I did not answer truthfully to ALL the above checkpoints.

I can reproduce if I enable ABP along uBO. Given that OP didn't truthfully answer checkpoints, this could be a case of [using other content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625).
