### ISSUE TITLE
loopearplugs.com: breakage

### ISSUE THREAD

**Issue by novahahn** [uBlockOrigin/uAssets#21933]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://www.loopearplugs.com/pages/contact

### Description

Clicking the link "Start a chat with our team" has no visible effect

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 115581
 cosmetic: 44228
 scriptlet: 18643
 html: 2016
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36991-115, 1m
  ublock-badware: 7773-11, 1m
  ublock-privacy: 959-0, 2m
  ublock-unbreak: 2233-0, 2m
  ublock-quick-fixes: 191-1, 2m
  easylist: 76939-618, 2m
  easyprivacy: 43409-825, 2m
  urlhaus-1: 9905-0, 2m
  plowe-0: 3788-1, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2767 ms
 maxAssetCacheWait: 14 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  loopearplugs.com: 12
  amplitude.com: 1
  cloudflareinsights.com: 2
  convertexperiments.com: 2
  d38xvr37kwwhcm.cloudfront.net: 1
  duel.me: 2
  facebook.net: 1
  googletagmanager.com: 3
  intelligems.io: 1
  klaviyo.com: 2
  rebuyengine.com: 1
  sc-static.net: 1
  sentry.io: 4
  snapchat.com: 1
  yougreencolumn.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=loopearplugs.com
```

@ryanbr
