### ISSUE TITLE
forums.commentcamarche.net: breakage

### ISSUE THREAD

**Issue by charmilhe** [uBlockOrigin/uAssets#21940]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://forums.commentcamarche.net/`

### Category

breakage

### Description

Cosmetic filtering removes text from the page

### Other extensions used

Darkreader (disabled)
Cookie autedelete (disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 143543
 cosmetic: 117030
 scriptlet: 23998
 html: 2016
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 717-8, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2551-76, now
  adguard-spyware-url: 1421-234, now
  adguard-cookies: 28346-39, now
  fanboy-cookiemonster: 49233-3720, now
  ublock-cookies-adguard: 875-0, now
  ublock-cookies-easylist: 875-875, now
 default:
  user-filters: 4-0, never
  ublock-filters: 36989-190, now
  ublock-badware: 7798-11, now
  ublock-privacy: 959-50, now
  ublock-unbreak: 2233-1, now
  ublock-quick-fixes: 202-1, now
  easylist: 77193-669, now
  easyprivacy: 43412-1044, now
  urlhaus-1: 10395-0, now
  plowe-0: 3782-1, now
  FRA-0: 26855-118, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 567 ms (selfie)
 maxAssetCacheWait: 266 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 no-cosmetic-filtering: true
 network:
  adsafeprotected.com: 1
  amazon-adsystem.com: 1
  appconsent.io: 2
  b.akamai.net: 2
  ccmbg.com: 1
  criteo.net: 1
  digidip.net: 1
  doubleclick.net: 1
  hubvisor.io: 1
  outbrain.com: 1
  zebestof.com: 1
```
</details>

**Comment by gorhill** [comment]
Also can't reproduce with default lists + FR.

Please be more specific: what text? Provide screenshot.
