### ISSUE TITLE
gsmarena.com: ads

### ISSUE THREAD

**Issue by Sym8** [uBlockOrigin/uAssets#21941]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gsmarena.com/compare.php3?idPhone1=12776&idPhone2=12723&idPhone3=12581`
`https://www.gsmarena.com/poco_x6-review-2654p2.php`

### Category

ads

### Description

Leftover empty ad space

### Other extensions used

way too many to write down

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-12 211316](https://github.com/uBlockOrigin/uAssets/assets/66876418/3b44746b-5fd5-4562-906c-316a780acf3f)
![Screenshot 2024-01-12 211331](https://github.com/uBlockOrigin/uAssets/assets/66876418/9d44feee-7fd3-46a4-9a59-20ab7aa24300)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 118431
 cosmetic: 76423
 scriptlet: 20398
 html: 2016
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28346-50, now
  easylist-newsletters: 6869-4, now
  ublock-cookies-adguard: 875-0, now
 default:
  user-filters: 1-0, never
  ublock-filters: 36986-116, 8m
  ublock-badware: 7798-11, 8m
  ublock-privacy: 959-0, 9m
  ublock-unbreak: 2233-0, 9m
  ublock-quick-fixes: 202-1, 9m
  easylist: 77193-625, 50m Δ
  easyprivacy: 43412-826, 50m Δ
  urlhaus-1: 10395-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 777 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  uniconsent.com: 2
 extended:
  ###topAdv
  ##.ad-c-label
  ##.ad-top
  ###subHeader
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
I came up with this:

    gsmarena.com###specs-list > div:has([class*="ad-"])
    gsmarena.com##.adv

This can be fixed in EasyList, cc @ryanbr

**Comment by stephenhawk8054** [comment]
Please report at https://github.com/easylist/easylist/issues

**Comment by ghost** [comment]
Can this "Daily deals" section be hidden too?

https://github.com/user-attachments/assets/01f7be6f-8582-45ea-9fae-11ce44a0a2ff)

**Comment by 3xploiton3** [comment]
https://github.com/user-attachments/assets/30cde572-02e6-400a-a304-2f387262a354)

https://www.gsmarena.com/asus_rog_phone_9_pro-13469.php

```
name: uBlock Origin Lite
version: 2025.525.2314
browser: Chrome 137 (win)
filtering:
 site: optimal
 default: optimal
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 annoyances-cookies
 idn-0
 annoyances-overlays
 annoyances-others
```

**Comment by ghost** [comment]
They seem to be back with them:

https://github.com/user-attachments/assets/23b85b7c-bb4f-4ee2-af0c-e6041f1bdc5a)

```
uBlock Origin: 1.64.0
Firefox: 139
filterset (summary):
 network: 152154
 cosmetic: 42978
 scriptlet: 23406
 html: 2366
listset (total-discarded, last-updated):
 default:
  user-filters: 62-1, never
  ublock-filters: 41092-113, 33m
  ublock-badware: 11465-17, 33m
  ublock-privacy: 3152-2, 33m
  ublock-unbreak: 2702-0, 22m Δ
  ublock-quick-fixes: 290-22, 33m
  easylist: 71504-239, 22m Δ
  easyprivacy: 54143-51, 22m Δ
  urlhaus-1: 33115-0, 33m
  plowe-0: 3430-908, 33m
  ROU-1: 1482-40, 33m
filterset (user): [array of 57 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 123 ms (selfie)
 maxAssetCacheWait: 53 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cleverwebserver.com: 1
  doubleclick.net: 1
  google.com: 3
  googletagmanager.com: 1
  uniconsent.com: 2
 extended:
  ###subHeader:has(> #topAdv)
  ##div[style="margin-left: -10px; margin-top: 30px; height: 145px…
  ##.adv
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ###topAdv
  ##.ad-c-label
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.ad-label
  ##.adv-mpu
  ##.stickyads
  ##.ads_banner
  ##.AdBox
  ##.ad-top
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
  #@#.ad-unit
```

**Comment by mapx-** [comment]
provide specific link

**Comment by ghost** [comment]
It's the main page. 

`https://www.gsmarena.com/`

**Comment by mapx-** [comment]
us ip

```adb
gsmarena.com###subHeader3:has([href="deals.php3"])
```

**Comment by ghost** [comment]
It works.

**Comment by ghost** [comment]
They still seem to show that section on mobile:
https://github.com/user-attachments/assets/9e071f20-db7b-46de-89fd-45b9bfe9b9d8
https://github.com/user-attachments/assets/9e9fd55a-b497-441e-9f5b-3fdcba978066

**Comment by ghost** [comment]
Update: now they got hidden too.

**Comment by Sym8** [comment]
Leftover ad space in between pages on main page and comment section. https://m.gsmarena.com/newscomm-68882.php

https://github.com/user-attachments/assets/a1c955be-8ee9-418e-b980-94fb42d4d750
https://github.com/user-attachments/assets/7e68727c-4db1-4b25-bf50-482873f5cbe2

Firefox and ublock origin Android.

**Comment by ghost** [comment]
Post your troubleshooting info.

**Comment by Sym8** [comment]
uBlock Origin: 1.65.0
Firefox Mobile: 141
filterset (summary):
 network: 161388
 cosmetic: 107762
 scriptlet: 35647
 html: 2649
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 2180-139, 1h.13m
  fanboy-cookiemonster: 45977-153, never
  ublock-cookies-easylist: 5070-47, never
  easylist-annoyances: 5094-43, 42m
  easylist-chat: 243-0, 42m
  easylist-newsletters: 8957-35, 42m
  easylist-notifications: 3372-172, 42m
  ublock-annoyances: 4559-58, 1h.25m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 40899-134, 1h.25m Δ
  ublock-badware: 11434-18, 1h.25m Δ
  ublock-privacy: 3347-2, 1h.25m Δ
  ublock-unbreak: 2731-3, 1h.25m Δ
  ublock-quick-fixes: 289-14, 1h.25m Δ
  adguard-mobile: 11223-11, now
  easylist: 75603-284, 1h.25m Δ
  easyprivacy: 54344-64, 1h.25m Δ
  urlhaus-1: 30995-0, never
  plowe-0: 3419-972, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 325 ms (selfie)
 maxAssetCacheWait: 152 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  gsmarena.com: 1
  googletagmanager.com: 1
  uniconsent.com: 1
 extended:
  ##.top-adv
  ##.adv-mpu
  ##.stickyads
  ##.ads_banner
  ##.AdBox
  ##.adv-bottom
  ##.adv-mid
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ad-c-label
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]

**Comment by mapx-** [comment]
```adb
gsmarena.com##.justify-center:has(.ad-c-label)
```

**Comment by ghost** [comment]
Ads on `https://m.gsmarena.com/indian_it_minister_claims_well_see_the_first_indian_smartphone_brands_in_the_near_future-news-71252.php`

(https://github.com/user-attachments/assets/8f71b402-f602-4fdf-9cc7-e5fe42546534)

and also, on `https://m.gsmarena.com/news.php3#more` if you scroll more, there are ad leftovers.

(https://github.com/user-attachments/assets/eb6d5262-51e7-4c7e-8bb4-a3134c465c33)

Using Microsoft Edge for Android

**Comment by mapx-** [comment]
```adb
gsmarena.com##.deal
gsmarena.com##.d-flex:has(pgs-ad)
```

@ryanbr
