### ISSUE TITLE
poki.com: detection

### ISSUE THREAD

**Issue by ggomezz22** [uBlockOrigin/uAssets#21946]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://poki.com/`

### Category

detection

### Description

it says privacy error

### Other extensions used

ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  ublock-filters: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
 added:
  https://poki.com/block/false: 0-0, never
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 11 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 autoUpdate: false
 collapseBlocked: false
 contextMenuEnabled: false
 parseAllABPHideFilters: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1640 ms (selfie)
 maxAssetCacheWait: 1217 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 no-cosmetic-filtering: true
```
</details>

**Comment by D4niloMR** [comment]
Reset uBO to default and test again.

**Comment by gorhill** [comment]
With such broken configuration, no point keeping this issue opened, it's straight up invalid.
