### ISSUE TITLE
movieplayer.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21948]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://movieplayer.it/`

### Category

nuisance

### Description

cookies dialog

AG rules:
```
#%#//scriptlet('trusted-click-element', '.iubenda-cs-customize-btn')
#%#//scriptlet('trusted-click-element', '#iubFooterBtn')
```

uBO rules for `multiplayer.it` (similar site)
```
! https://github.com/uBlockOrigin/uAssets/issues/20302
multiplayer.it##+js(trusted-set-cookie, euconsent-v2, CPtgasAPtgasAAGABCENDECgAAAAAAAAAApAAAAAAAAA.YAAAAAAAAAAA, 1year)
multiplayer.it##+js(trusted-set-cookie, _iub_cs-495815, %7B%22timestamp%22%3A%222023-10-26T10%3A24%3A25.058Z%22%2C%22version%22%3A%221.48.0%22%2C%22consent%22%3Atrue%2C%22id%22%3A495815%2C%22cons%22%3A%7B%22rand%22%3A%2287691d%22%7D%7D, 1year)
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1125" alt="j" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/0d726e1a-ee18-464b-b4f6-aba90c393a82">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 142417
 cosmetic: 170868
 scriptlet: 44828
 html: 2223
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81562-5858, now
  adguard-social: 22343-45, never
  adguard-cookies: 28346-38, never
  ublock-cookies-adguard: 875-875, never
  adguard-popup-overlays: 26741-994, never
  adguard-mobile-app-banners: 4900-9, never
  adguard-other-annoyances: 14034-438, never
  adguard-widgets: 2399-9, never
  ublock-annoyances: 6494-165, never
 default:
  user-filters: 0-0, never
  ublock-filters: 36991-115, now
  ublock-badware: 7798-11, now
  ublock-privacy: 959-0, now
  ublock-unbreak: 2233-0, now
  ublock-quick-fixes: 202-1, now
  easylist: 77193-619, now
  easyprivacy: 43412-826, now
  urlhaus-1: 10395-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4631 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  amazon-adsystem.com: 1
  ebxcdn.com: 2
  google.com: 7
  googletagmanager.com: 1
  iubenda.com: 1
  pghub.io: 1
 extended:
  ###fb-root:not(body):not(html)
  ###personalization_ads
  ###top_ads_container
```
</details>

**Comment by mapx-** [comment]
ELC is using

`||iubenda.com^$third-party`

Did you test it ? any breakage ?

**Comment by superlex** [comment]
@mapx- 
Check videos here:
`https://movieplayer.it/serietv/video/`
It looks like you need to accept all cookies
`! ##+js(trusted-click-element, .iubenda-cs-visible .iubenda-cs-accept-btn)`

**Comment by superlex** [comment]
@mapx- 
Maybe `||iubenda.com^$3p` should be excluded by ELC for `movieplayer.it`, in any case with the `@@||iubenda.com^$3p,domain=movieplayer.it` it looks like you're whitelisting `hits-i.iubenda.com` too, that is a tracking server blocked by Peter Lowe.
