### ISSUE TITLE
amazon.de: breakage

### ISSUE THREAD

**Issue by IngoKnieto** [uBlockOrigin/uAssets#21944]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amazon.de/ref=nav_logo`

### Category

breakage

### Description

The top bar is visible and working fine, everything below is blocked. Only uBlock was active during testing. Disabling uBlock fixes this.
![amazon](https://github.com/uBlockOrigin/uAssets/assets/35420660/edbe6fed-f34b-4ccc-830e-6e2aec52260f)

### Other extensions used

only uBlock was active during testing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 118609
 cosmetic: 49154
 scriptlet: 18644
 html: 2016
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36986-130, 1h.42m Δ
  ublock-badware: 7798-11, 1h.42m Δ
  ublock-privacy: 959-0, 1h.42m Δ
  ublock-unbreak: 2233-0, 1h.42m Δ
  ublock-quick-fixes: 202-1, 1h.42m Δ
  easylist: 77193-626, 1h.42m Δ
  easyprivacy: 43412-828, 1h.42m Δ
  urlhaus-1: 10325-0, 19h.37m
  plowe-0: 3784-1, 10d.17h.13m
  DEU-0: 7282-3, 19h.37m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 126 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  amazon.de: 15
  amazon.com: 1
 extended:
  ###nav-swmslot
  ##[data-card-metrics-id]
  ##div[cel_widget_id^="adplacements:"]
  ##.ad-center
  ##+js(json-prune, cuepointPlaylist)
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] |…
```
</details>

**Comment by okiehsch** [comment]
Added today to EasyList
https://github.com/easylist/easylist/commit/c91748ffde08a3bc87e64ab35984337ddc228056

@ryanbr the filter completely breaks `amazon.de`.

**Comment by D4niloMR** [comment]
Here it breaks on all tld
