### ISSUE TITLE
[nsfw] rezka.ag: breakage

### ISSUE THREAD

**Issue by Mr-Maxsimus** [uBlockOrigin/uAssets#21945]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rezka.ag/series/drama/50102-uslysh-menya-2022.html`

### Category

breakage

### Description

When the ad blocker is turned on, the online video player stops downloading, or reduces the quality, or loads endlessly and does not play the video!!!
I only use the bookmark extension apart from the ad blocker and that's it!

### Other extensions used

Speed Dial 3™   

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 133763
 cosmetic: 65496
 scriptlet: 21428
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  RUS-0: 40205-9, 1h.34m
  easylist: 77194-35, now
  easyprivacy: 43412-119, now
  plowe-0: 3782-1172, now
  ublock-badware: 7794-137, now
  ublock-filters: 36404-155, now
  ublock-privacy: 962-8, now
  ublock-quick-fixes: 222-50, now
  ublock-unbreak: 2187-31, now
  urlhaus-1: 10395-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 164 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  jsdelivr.net: 1
 extended:
  ##body.has-brand .b-content__main > div[id]:not([class]):empty
  ##body[class^="has-brand"][class*=" active-brand"][class*="fixed…
  ##+js(abort-current-script, document.getElementsByTagName, AMSP.…
  ##+js(set-constant, Object.prototype.preroll, undefined)
```
</details>

**Comment by dimisa-RUAdList** [comment]
This issue can be discussed here: https://github.com/easylist/ruadlist/issues/232
