### ISSUE TITLE
comparitech.com: ads

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#21953]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.comparitech.com/blog/vpn-privacy/adblocking-filter-lists/`

### Category

ads

### Description

Ad is shown.
Can remove ads with:

```
comparitech.com##.ct089
comparitech.com##.how_test
```

### Other extensions used

none

### Screenshot(s)

<img width="1466" alt="Screenshot 2024-01-13 at 19 11 04" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/714f31c9-3736-4830-a575-fa3b9a6f7e70">

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 116948
 cosmetic: 44695
 scriptlet: 18661
 html: 2017
listset (total-discarded, last-updated):
 added:
  BGR-0: 1022-1, 1m
 default:
  user-filters: 17-0, never
  ublock-filters: 37005-115, 1h.8m Δ
  ublock-badware: 7736-11, 1h.8m Δ
  ublock-privacy: 960-0, 1h.8m Δ
  ublock-unbreak: 2235-0, 1h.8m Δ
  ublock-quick-fixes: 232-1, 1h.8m Δ
  easylist: 77208-621, 1m
  easyprivacy: 43412-826, 1h.8m Δ
  urlhaus-1: 10435-0, 1m
  plowe-0: 3782-1, 1m
filterset (user): [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 268 ms (selfie)
 maxAssetCacheWait: 177 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  convertexperiments.com: 8
  googletagmanager.com: 4
 extended:
  ###AdBlock
  ##.ct_popup_modal
```
</details>

**Comment by mapx-** [comment]
to be reported at [easylist repo](https://github.com/easylist/easylist/issues)

**Comment by ItsProfessional** [comment]
@ryanbr
