### ISSUE TITLE
mtv.it: detection

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21956]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mtv.it/video-musicali/q515bo/quello-che-mi-fai`

### Category

detection

### Description

anti-adblock

other sites:
`https://www.mtvema.com/it-it/video/m2t2h2/2022-mtv-emas-anitta-thanks-voters-for-helping-her-win-best-latin-award`
Maybe also
`https://www.mtv.de/musikvideos/1n1joi/komet`
`https://www.mtv.co.uk/video/a8cnai/mtv-push-austin-mahone-what-pushes-you`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1128" alt="j" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/abf6ec17-1d4f-481e-b263-d81aa3981767">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 142434
 cosmetic: 170876
 scriptlet: 44813
 html: 2224
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81537-5865, 43m
  adguard-social: 22343-163, 43m
  adguard-cookies: 28344-43, 43m
  ublock-cookies-adguard: 877-0, 43m
  adguard-popup-overlays: 26740-997, 43m
  adguard-mobile-app-banners: 4900-7, 43m
  adguard-other-annoyances: 14034-63, 43m
  adguard-widgets: 2399-1, 43m
  ublock-annoyances: 6496-892, 43m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 37005-395, 43m Δ
  ublock-badware: 7736-11, 43m Δ
  ublock-privacy: 960-0, 43m Δ
  ublock-unbreak: 2235-0, 43m Δ
  ublock-quick-fixes: 232-1, 43m Δ
  easylist: 77208-677, 43m Δ
  easyprivacy: 43412-895, 43m Δ
  urlhaus-1: 10435-0, 43m
  plowe-0: 3782-1, 43m
filterset (user): [empty]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1347 ms
 maxAssetCacheWait: 833 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  cbsaavideo.com: 4
  cbsivideo.com: 15
  cookielaw.org: 1
  demdex.net: 2
  imasdk.googleapis.com: 1
  mtvnservices.com: 1
  newrelic.com: 4
  ns1p.net: 1
  psychedelicarithmetic.com: 1
```
</details>

**Comment by mapx-** [comment]
test for mtv.it

```
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$xhr,domain=mtv.it
||imasdk.googleapis.com/pal/sdkloader/pal.js$redirect-rule=noop.js,domain=mtv.it
```
