### ISSUE TITLE
huffingtonpost.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21954]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.huffingtonpost.it/audio/serie/2022/01/19/playlist/polvere-7472370/`

### Category

nuisance

### Description

`huffingtonpost.it##+js(trusted-click-element, .iubenda-cs-visible .iubenda-cs-accept-btn)`

You can't hide the popup, otherwise you don't get audios (see second screenshot).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1121" alt="j" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/61202f8f-9551-4399-9ac1-85fc0ab294fb">

<img width="1039" alt="yhjkl" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/7c397e7e-06cc-42b3-8aff-e7545075729d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 142434
 cosmetic: 170876
 scriptlet: 44813
 html: 2224
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81537-5865, 1m
  adguard-social: 22343-163, 1m
  adguard-cookies: 28344-41, 1m
  ublock-cookies-adguard: 877-0, 1m
  adguard-popup-overlays: 26740-929, 1m
  adguard-mobile-app-banners: 4900-7, 1m
  adguard-other-annoyances: 14034-63, 1m
  adguard-widgets: 2399-1, 1m
  ublock-annoyances: 6496-892, 1m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 37005-465, 1m Δ
  ublock-badware: 7736-11, 1m Δ
  ublock-privacy: 960-0, 1m Δ
  ublock-unbreak: 2235-0, 1m Δ
  ublock-quick-fixes: 232-1, 1m Δ
  easylist: 77208-677, 1m Δ
  easyprivacy: 43412-895, 1m Δ
  urlhaus-1: 10435-0, 1m
  plowe-0: 3782-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1241 ms
 maxAssetCacheWait: 754 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  huffingtonpost.it: 1
  admantx.com: 1
  chartbeat.com: 3
  googletagmanager.com: 1
  imrworldwide.com: 1
  iubenda.com: 1
  opecloud.com: 1
  viafoura.co: 5
 extended:
  ##a[href^="https://twitter.com/share"]
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://web.whatsapp.com/send?text="]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ###adv-Top
  ###adv-TopLeft
  ###fb-root:not(body):not(html)
```
</details>

**Comment by superlex** [comment]
@mapx- 
Thanks!
Same for `lastampa.it`
`https://www.lastampa.it/audio/audioarticoli/2024/01/13/playlist/gli_audioarticoli_del_13_gennaio_2024-13991855/`

**Comment by AlfonsoML** [comment]
The https://www.huffingtonpost.es/ site also shows a cookie wall banner.  
Should I create a new ticket or is it just enough this post?

**Comment by mapx-** [comment]
it's ok here

**Comment by mapx-** [comment]
@AlfonsoML 

test this filter for breakage

`||sdk.privacy-center.org/*/loader.js$script,important,domain=huffingtonpost.es`

**Comment by AlfonsoML** [comment]
Thank you. I've done only a quick test as I don't use to visit that site and it seemed to work correctly.
Good job!
