### ISSUE TITLE
elpais.com: nuisance

### ISSUE THREAD

**Issue by goblinsta** [uBlockOrigin/uAssets#21958]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://elpais.com/`

### Category

nuisance

### Description

Banner appears on any screen of that domain. It can be avoided by clicking on "disable JavaScript on this site" but then this affects the page format (images have wrong size for example), videos cannot be played, comments cannot be accessed, etc.

### Other extensions used

Bypass paywalls clean, Workona tab suspender, Languagetool, Foxtrick

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/156548232/989b0d8d-454b-4988-a900-e8d6a149ace0)

![Captura de pantalla 2024-01-13 213850](https://github.com/uBlockOrigin/uAssets/assets/156548232/77e9f48e-ad1d-40cb-aff6-d326c1845c7a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 119134
 cosmetic: 52389
 scriptlet: 24912
 html: 0
listset (total-discarded, last-updated):
 added:
  spa-0: 3786-19, now
  spa-1: 5701-210, now
  ublock-annoyances: 6545-11, now
 default:
  user-filters: 15-0, never
  easylist: 77208-12, now
  easyprivacy: 43412-32, now
  plowe-0: 3782-1168, now
  ublock-badware: 7732-136, now
  ublock-filters: 36414-150, now
  ublock-privacy: 963-7, now
  ublock-quick-fixes: 231-50, now
  ublock-unbreak: 2189-34, now
  urlhaus-1: 10435-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 22 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 263 ms (selfie)
 maxAssetCacheWait: 135 ms
popupPanel:
 blocked: 6
 network:
  elpais.com: 1
  google.com: 5
 extended:
  ##.ad
  ##div[id^="ad-"]
  ##.ad-giga
  ##.ad-mpu
```
</details>

**Comment by D4niloMR** [comment]
Enable "EasyList – Cookie Notices" or "AdGuard – Cookie Notices".
