### ISSUE TITLE
monetoad.com: popups

### ISSUE THREAD

**Issue by kenny9p** [uBlockOrigin/uAssets#21968]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://monetoad.com/v1/go/?deeplink=https%3A%2F%2Ftwnfz.com%2Fg%2Foqcmadzidp4cc7b61b34acbbb3152e%2F%3Fsubid%3D3CeedBfX9s9jImFGlXNbCVHyY1JZ1a8YTxuzqdiYiRO8Ua%26subid2%3Dkoala-apps.io%26subid3%3D%26subid4%3D233152%26ref%3Dtatrck.com%26ulp%3Dhttps%253A%252F%252Fwww.fiverr.com%252Fnikitapanasenko%252Fdo-3d-modeling-and-3d-rendering%253Fcontext_referrer%253Dseller_page%2526ref_ctx_id%253D0fde312c170c49499802bfd8d03b6f0e%2526pckg_id%253D1%2526pos%253D1%2526imp_id%253D2b846ae9-c5bc-4b9e-9529-b878fa6edd1f&p=2wu2qa9d0x`

### Category

popups

### Description

This URL appears randomly on any websites as a redirect on random buttons on the website. I have seen it mainly in Fiverr, but have also seen it in Google and other sites when I click on a button, this monetoad url will show up before redirecting to the true url. Hitting back to previous page on the browser does not land back on monetoad. Sometimes in the URL parameter there is the name "koala-apps" which is an extension Koala Inspector I and a lot of people use (a very helpful extension in ecommerce), but I believe their business is also to track links click or something of their users using the monetoad URL. I reached out to them about this and they said they asked for specifics and then "fix" the problem and ask me to check if it's still happening. I said it happens randomly and ask if they knowingly use this monetoad.com url and ask for for clarification on what happened but they just keep ignoring me and don't want to tell me a straightforward "no" that they are not affiliated with the monetoad URL. Very suspicious of them. They keep ignoring me question and tell me they'd give me 2 months free of their app lol in response lol. I would uninstall the app, but I need to use the app as there aren't substitutes. 

If you look at their Chrome extension reviews, many people have said that called out that they are tracking users' link clicks. 

### Other extensions used

Koala Inspector, Similar Web, Wappalyzer, Super Dark Mode, Bitwarden. 
https://github.com/uBlockOrigin/uAssets/assets/153080215/303d785a-83f8-4ba9-a493-7ab7da9d18c3

https://github.com/uBlockOrigin/uAssets/assets/153080215/6bdf6ee6-d322-4bf0-a99e-5f0b159fd0b7
https://github.com/uBlockOrigin/uAssets/assets/153080215/c563397c-4d2a-4c03-abea-368bd6a4b335
https://github.com/uBlockOrigin/uAssets/assets/153080215/8607b65e-a675-4394-8c74-222368b1f544
https://github.com/uBlockOrigin/uAssets/assets/153080215/e15ce6c0-4b7e-4fd0-a0b1-7c3908e3c964
https://github.com/uBlockOrigin/uAssets/assets/153080215/1790a95f-7732-4d2e-a980-1df561298c7a
https://github.com/uBlockOrigin/uAssets/assets/153080215/3f56bde1-ee4c-4018-822b-54434f052783
https://github.com/uBlockOrigin/uAssets/assets/153080215/96c3b35e-a2e8-481a-8fc6-b423fb86ad53

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 116115
 cosmetic: 44261
 scriptlet: 20023
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77210-12, 16m
  easyprivacy: 43421-37, now
  plowe-0: 3782-1169, now
  ublock-badware: 7732-136, now
  ublock-filters: 36371-129, now
  ublock-privacy: 963-7, now
  ublock-quick-fixes: 233-50, now
  ublock-unbreak: 2189-31, now
  urlhaus-1: 10215-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 7 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2982 ms (selfie)
 maxAssetCacheWait: 457 ms
popupPanel:
 blocked: 1
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  monetoad.com: 1
```
</details>

**Comment by mapx-** [comment]
It seems your system is infested by adware / malware.
Disable / remove any weird extension, then scan your system for malware using some trustful software.

For example try this one:
https://www.trendmicro.com/en_il/forHome/products/housecall.html

**Comment by ItsProfessional** [comment]
Occurs on all websites -> it's something to do with your system and can't be fixed by uBO
