### ISSUE TITLE
clarin.com: ads

### ISSUE THREAD

**Issue by nervocalm** [uBlockOrigin/uAssets#21964]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.clarin.com/`

### Category

ads

### Description

It blocks the ads but keeps the placeholders even with the cosmetic options activated. On the top of the page there is also a banner that I could hide manually.

### Other extensions used
<details>
<summary>Screenshot(s)</summary>

[
![Screenshot_20240114-015610](https://github.com/uBlockOrigin/uAssets/assets/24263312/1a94d986-baed-49f1-8ccb-86011228633d)
](url)

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240114-015001](https://github.com/uBlockOrigin/uAssets/assets/24263312/672f361c-b4a0-4bfe-8c17-354cc8219ba5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 117484
 cosmetic: 35754
 scriptlet: 18719
 html: 2017
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37352-362, 35m
  ublock-badware: 7730-11, 35m
  ublock-privacy: 960-1, 35m
  ublock-unbreak: 2240-1, 35m
  ublock-quick-fixes: 233-1, 35m
  adguard-mobile: 9038-132, 36m
  easylist: 77194-16692, 35m
  easyprivacy: 43412-834, 36m
  urlhaus-1: 10215-0, 36m
  plowe-0: 3782-1, 36m
filterset (user): [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 434 ms
 maxAssetCacheWait: 206 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 2
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  mrf.io: 1
  permutive.app: 1
  scorecardresearch.com: 1
 extended:
  ##.bannerTopHeader
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by ItsProfessional** [comment]
Enable spanish regional list
