### ISSUE TITLE
[nsfw] xvideos.com: ads

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#21969]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

    https://www.xvideos.com/video79590829/goth_big_step_sister_vs_horny_little_perv_-_charli_o_-_family_therapy_-_alex_adams

### Description

Hello, the link from above contain some ads from CamGirls. You can see these on the right side of the video player.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/86512304/82b4506f-fcb1-49f9-9457-b459b0f45cad)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 293357
 cosmetic: 151495
 scriptlet: 45675
 html: 2217
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81549-6893, 2d.35m
  adguard-spyware-url: 1421-94, 2d.34m
  block-lan: 55-0, 9d.17h.57m
  curben-phishing: 84194-30, 7h.59m
  fanboy-cookiemonster: 49224-3762, 2d.2h.36m
  ublock-annoyances: 6500-875, 3h.7m Δ
  dpollock-0: 11623-467, 2d.19h.33m
  adguard-spyware: 87237-27027, 2d.34m
  adguard-cookies: 28346-41, 2d.34m
  ublock-cookies-adguard: 862-0, 5d.6h.8m
  ublock-cookies-easylist: 864-862, 5d.6h.8m
 default:
  user-filters: 364-8, never
  ublock-filters: 36953-121, 3h.7m Δ
  ublock-badware: 7736-11, 3h.7m Δ
  ublock-privacy: 960-0, 3h.7m Δ
  ublock-unbreak: 2233-1, 3h.7m Δ
  ublock-quick-fixes: 235-1, 3h.7m Δ
  easylist: 77209-797, 3h.7m Δ
  easyprivacy: 43421-925, 3h.7m Δ
  urlhaus-1: 10215-0, 7h.59m
  plowe-0: 3787-1, 2d.19h.33m
filterset (user): [array of 351 redacted]
switchRuleset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5620 ms
 maxAssetCacheWait: 2599 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  xvideos.com: 4
  orbsrv.com: 2
  trafficfactory.biz: 1
  xvideos-cdn.com: 4
 extended:
  ##.remove-ads
  ##.remove-ads-link
  ###video-sponsor-links
  ##.exo-ad-ins-container
  ##.adsbyexoclick
  ##.videoad-title
  ###ad-footer
  ##+js(no-window-open-if)
  ##+js(set-constant, xv.disclaimer.displayCookiePopup, noopFunc)
  ##+js(abort-on-property-read, popns)
  ##+js(remove-class, has-banner, #page > #main > #profile-title)

```
</details>

**Comment by mapx-** [comment]
it'self promotion

add as custom filter

`xvideos.com###content > [class]:matches-attr(/^/=/[\w\W]{30,}/)`
