### ISSUE TITLE
digisport.ro: detection

### ISSUE THREAD

**Issue by MarcoFilimon** [uBlockOrigin/uAssets#21970]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.digisport.ro/live/digisport-1`

### Category

detection

### Description

Can't watch the broadcast without disabling ublock

### Other extensions used

I dont care about cookies
Dark Reader
SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 116336
 cosmetic: 45920
 scriptlet: 22966
 html: 2217
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6494-11, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 36963-117, 13m Δ
  ublock-badware: 7736-11, 13m Δ
  ublock-privacy: 960-0, 13m Δ
  ublock-unbreak: 2234-1, 13m Δ
  ublock-quick-fixes: 236-1, 13m Δ
  easylist: 77226-624, 13m Δ
  easyprivacy: 43421-828, 13m Δ
  urlhaus-1: 10130-0, 11m
  plowe-0: 3782-1, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 295 ms (selfie)
 maxAssetCacheWait: 194 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  adtlgc.com: 2
  cxense.com: 4
  googletagservices.com: 1
  imasdk.googleapis.com: 2
 extended:
  ##.ad-wrapper
  ##.AdSense
  ###AdSense2
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
Enable the regional list: `Romanian Ad (ROad) Block List Light`
