### ISSUE TITLE
bbc.com: nuisance

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#21974]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bbc.com/russian/articles/c3gylmddvrko`

### Category

nuisance

### Description

To display Instagram, YouTube, Facebook, Twitter, and others, consent to the use of cookies is required

I suggest adding ~>
`bbc.com##+js(trusted-click-element, #consentBanner > [data-testid="banner-button"])`

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bbc](https://github.com/uBlockOrigin/uAssets/assets/20126984/82e00d67-3d1f-4885-b607-f37dc50911fc)

</details>

### Configuration

uBO 1.55.1b1 default + uBlock filters – Annoyances

**Comment by dimisa-RUAdList** [comment]
@D4niloMR 
It looks like the rule isn't working as expected. [During the 10 seconds](https://github.com/gorhill/uBlock/wiki/Resources-Library#trusted-click-elementjs-) that the scriptlet is running, the user will not have time to read the material and scroll the page to the desired place, and there are no target elements in the initial layout; they will appear later, as they scroll.

Thus, the rule only works if you open the article in advance, scroll to the desired location, and then refresh the page. This is an unrealistic scenario.

Any ideas?

@gorhill

**Comment by dimisa-RUAdList** [comment]
Maybe consider improving `trusted-click-element` by adding an additional parameter, such as `stay`?

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2917

**Comment by dimisa-RUAdList** [comment]
Please change to: `bbc.com##+js(trusted-click-element, [data-testid="consentBanner"] > button[data-testid="banner-button"], , 1000)`

**Comment by dimisa-RUAdList** [comment]
Sometimes there are several elements on a page that need to be clicked. 

Example: `https://www.bbc.com/russian/features-54391793`

I suggest adding ~>
```
bbc.com##+js(trusted-click-element, [data-testid="consentBanner"] > button[data-testid="banner-button"], , 1100)
bbc.com##+js(trusted-click-element, [data-testid="consentBanner"] > button[data-testid="banner-button"], , 1200)
bbc.com##+js(trusted-click-element, [data-testid="consentBanner"] > button[data-testid="banner-button"], , 1300)
```
And also remove the viewing delay: `bbc.com##+js(nano-stb, viewClickAttributeId)`

**Comment by mapx-** [comment]
it's already fixed by ELC or AdGuard – Cookie Notices

**Comment by dimisa-RUAdList** [comment]
@mapx- 
You probably just didn't understand the idea behind these rules. They are needed not for cookies, but for revealing content (uBlock filters – Annoyances).

<details>
<summary>Screenshot(s)</summary>

![BBC](https://github.com/uBlockOrigin/uAssets/assets/20126984/af592651-4271-464f-b3de-896d89001aba)

</details>

**Comment by dimisa-RUAdList** [comment]
@mapx- 
Can these rules be placed side by side? They perform the same task.

https://github.com/uBlockOrigin/uAssets/commit/fcd663bffc5c9a361b0359f378fb1a80bc831143
https://github.com/uBlockOrigin/uAssets/commit/a0384df8b5b36638c8242b891e1484572f704dd0

**Comment by stephenhawk8054** [comment]
@Marko-98 Which country are you when accessing the site?

**Comment by stephenhawk8054** [comment]
@Marko-98 Can you test this filter:

```adb
cdn.privacy-mgmt.com##+js(trusted-click-element, button[title="I do not agree"])
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
