### ISSUE TITLE
watch.sling.com: ads

### ISSUE THREAD

**Issue by xerosagas** [uBlockOrigin/uAssets#21972]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://watch.sling.com/`

### Category

ads

### Description

When you watch a movie on Sling, you will get preroll ads.
Repro steps:

1. Go to Sling and search for a movie (eg. Harlem Nights)
2. Wait for the movie to start playing

Result: Instead of going into the movie, 1-3 ads will play.

### Other extensions used

Built in Opera GX privacy protection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4909903/5b915ef5-cbcb-47cc-a173-1fd0ea7ff83e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 116052
 cosmetic: 44268
 scriptlet: 20034
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 77226-12, now
  easyprivacy: 43421-37, now
  plowe-0: 3782-1169, now
  ublock-badware: 7732-136, now
  ublock-filters: 36389-129, now
  ublock-privacy: 963-7, now
  ublock-quick-fixes: 236-50, now
  ublock-unbreak: 2190-32, now
  urlhaus-1: 10130-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9990 ms (selfie)
 maxAssetCacheWait: 149 ms
popupPanel:
 blocked: 4
 network:
  flashtalking.com: 1
  googletagmanager.com: 1
  scorecardresearch.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter? It cannot remove the waiting screens at beginning and at the end of the videos though

```adb
watch.sling.com##+js(json-prune, ssai_manifest ad_manifest playback_info.ad_info qvt.playback_info.ad_info)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by mapx-** [comment]
your `json-prune` filter seems working
