### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by karafo** [uBlockOrigin/uAssets#21988]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bild.de/`

### Category

detection

### Description

After updating chrome bild.de detects uBlock Origin

### Other extensions used

Gyazo, Fluffy Busting Purity (facebook), Fireshot, Devolution Workspace, Adobe Acrobat, Delinea Web Passwort Filler, Google Docs Offline, Recent History, The tiny URL shortener

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bildadblock](https://github.com/uBlockOrigin/uAssets/assets/29731481/be3b2396-be6e-432b-8399-a7ffc48783aa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 117936
 cosmetic: 49217
 scriptlet: 20034
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7284-0, 21m
  easylist: 77310-19, 21m
  easyprivacy: 43423-46, 21m
  plowe-0: 3782-1170, 21m
  ublock-badware: 7732-136, 21m
  ublock-filters: 36391-144, 21m
  ublock-privacy: 963-7, 21m
  ublock-quick-fixes: 233-47, 21m
  ublock-unbreak: 2190-34, 21m
  urlhaus-1: 9630-0, 21m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 360 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel:
 blocked: 14
 network:
  bild.de: 3
  bing.com: 1
  cxense.com: 1
  demdex.net: 2
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  ioam.de: 1
  kameleoon.eu: 1
  outbrain.com: 1
  taboola.com: 1
 extended:
  ##+js(no-setTimeout-if, offsetParent)
  ##+js(abort-on-property-read, SmartAdServerASMI)
  ##+js(json-prune, adBlockWallEnabled)
  ##+js(addEventListener-defuser, load, adBlock)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21987
