### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by fschloegl** [uBlockOrigin/uAssets#21987]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bild.de/`

### Category

detection

### Description

A few seconds after opening bild.de or a subsite, bild.de is recognizing the ublock origing an redirecting to `https://www.bild.de/adblockwall.html`

### Other extensions used

1password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/13234252/206ccacc-599f-4322-81a0-1d303d144d7d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 117963
 cosmetic: 49216
 scriptlet: 20031
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7284-0, 5m
  easylist: 77310-19, 5m
  easyprivacy: 43448-46, 5m
  plowe-0: 3782-1170, 5m
  ublock-badware: 7732-136, 5m
  ublock-filters: 36387-144, 5m
  ublock-privacy: 964-7, 6m
  ublock-quick-fixes: 234-47, 6m
  ublock-unbreak: 2190-34, 6m
  urlhaus-1: 9630-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 25 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 345 ms (selfie)
 maxAssetCacheWait: 110 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  bild.de: 2
  bing.com: 1
  cxense.com: 1
  demdex.net: 3
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  ioam.de: 1
  kameleoon.eu: 1
  outbrain.com: 1
  taboola.com: 2
 extended:
  ##+js(no-setTimeout-if, offsetParent)
  ##+js(abort-on-property-read, SmartAdServerASMI)
  ##+js(json-prune, adBlockWallEnabled)
  ##+js(addEventListener-defuser, load, adBlock)
```
</details>

**Comment by Daxy7** [comment]
need to use this for the anti-adblock 
```
@@||*.bild.de^$ehide
```
redirect though. normal?
https://github.com/uBlockOrigin/uAssets/assets/91396482/3a275634-107e-4eef-a9c3-cb2826c902bd

**Comment by manuallypure** [comment]
is there a way to permanently remove these two objects? 

1.  the BLACK DEALS banner (the ads on this banner keep rotating so now its some lottery but will change again and again)? There is always this kind of Banner with different commercials on it and it even says "Anzeige" (advertisement) but it never gets blocked. 

2. the HEY_ graphic

<details>

![2](https://github.com/user-attachments/assets/e962aac7-397b-4ea2-b597-0356b20d3e69)
![1](https://github.com/user-attachments/assets/f01b7ad5-01ff-4124-9d0c-27c648fcce6d)

</details>

**Comment by JobcenterTycoon** [comment]
@manuallypure report regular ads on german sites here: https://github.com/easylist/easylistgermany

**Comment by wefwef1** [comment]
ads again 

![Image](https://github.com/user-attachments/assets/314b3c8a-1562-4149-a5ae-4247f31ca506)

config:
```yaml
name: uBlock Origin Lite
version: 2026.426.1626
browser: Safari 26.4 (mac)
filtering:
 site: optimal
 default: optimal
permission: all
badge: 49
rules: 128126
rulesets:
 +annoyances-ai
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +annoyances-social
 +annoyances-widgets
 +block-lan
 deu-0
 easylist
 easyprivacy
 ublock-filters
scripting:
 annoyances-others.isolated
 annoyances-overlays.isolated
 css-specific
 annoyances-social.isolated
 ublock-filters.isolated
 annoyances-cookies.main
 ublock-filters.main
 annoyances-notifications.isolated
 annoyances-notifications.main
 easyprivacy.main
 css-procedural
 annoyances-cookies.isolated
 annoyances-overlays.main
 annoyances-others.main
 easyprivacy.isolated
```

**Comment by stephenhawk8054** [comment]
It will be fixed in next uBOL update.

**Comment by bm206** [comment]
Since the last update, ads are no longer showing, but now videos won't play.
Testpage: https://www.bild.de/news/ausland/horror-auf-dem-bord-hai-jagt-surfer-zehn-minuten-lang-69f30cc44c47c7adc671d320

<details>

```yml
name: uBlock Origin Lite
version: 2026.503.1521
browser: Safari 26.4 (mac)
filtering:
 default: complete
permission: all
rules: 131230
rulesets:
 +adguard-mobile
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +annoyances-social
 +annoyances-widgets
 +block-lan
 deu-0
 easylist
 easyprivacy
 ublock-filters
scripting:
 css-generic-some
 css-generic-all
 css-specific
 annoyances-others.isolated
 annoyances-overlays.isolated
 adguard-mobile.main
 adguard-mobile.isolated
 prevent-popup
 annoyances-social.isolated
 ublock-filters.isolated
 annoyances-cookies.main
 ublock-filters.main
 annoyances-notifications.isolated
 annoyances-cookies.isolated
 annoyances-notifications.main
 easyprivacy.main
 css-procedural
 annoyances-overlays.main
 annoyances-others.main
 easyprivacy.isolated
```

</details>
