### ISSUE TITLE
peliculas-mp4.com [Fake Button] [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2198]
URL(s) where the issue occurs

`http://www.peliculas-mp4.com/la-leyenda-del-charro-negro-2018/`

Describe the issue

![](https://i.imgur.com/d5Gveiw.png)
![](https://i.imgur.com/yMXpVxo.png)
![](https://i.imgur.com/tuNfPrL.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`peliculas-mp4.com##script:inject(abort-on-property-write.js, adsurgeNode)`

**Comment by okiehsch** [comment]
It does not actually mine because of the existing filter
`*$csp=worker-src 'none',domain=peliculas-mp4.com`
![image](https://user-images.githubusercontent.com/16838044/42902834-285e74ba-8ad0-11e8-9249-cca0d80ed583.png)

**Comment by lain566** [comment]
I was referring in this domain `megapastes.com`
Click on descargar, last week they used this domain `play.pampopholf.com/app.js`

![GitHub Logo](https://camo.githubusercontent.com/ae40a69dbfd463c4a58732ba1a9e07db5e57f6a7/68747470733a2f2f692e696d6775722e636f6d2f794d587056786f2e706e67)

**Comment by okiehsch** [comment]
Sorry for the misunderstanding, I updated the fix.

**Comment by lain566** [comment]
No problem, thanks.

**Comment by KiLL4FuNK** [comment]
`http://mega-dvdrip.info/la-casa-con-un-reloj-en-sus-paredes-2017-hd-720p-latino-00/`

**Comment by lain566** [comment]
This message appears and you can't continue: _Click on the advertising and wait 30 seconds_
`https://mega-dvdrip.info/dragon-ball-super-broly-2018-latino-02/`

![7f173631-7975-4748-85b0-91f68d3c0075](https://user-images.githubusercontent.com/27441315/52175444-4529d500-27a4-11e9-8cfd-4e310aacf574.png)

**Comment by lain566** [comment]
New domain `mega-dvdrip.com`
`https://mega-dvdrip.com/alita-angel-de-combate-2018-latino-y-subtitulada/`

Suggested filter
`mega-dvdrip.*##+js(addEventListener-defuser.js, DOMContentLoaded, shortener)`


<details><summary>Screenshot</summary>

![Anotación 2019-03-31 111002](https://user-images.githubusercontent.com/27441315/55287176-e056b980-53a5-11e9-9edd-4368c1e06edf.png)
</details>

**Comment by okiehsch** [comment]
Why not just block `||acortador.net^$3p`?
Could that break something at another site?

**Comment by lain566** [comment]
They can change domain easily and break your solution, same as `https://github.com/uBlockOrigin/uAssets/issues/4798`

But ok, add `||acortador.net^$3p`

**Comment by okiehsch** [comment]
Sorry my reply was worded wrongly, I meant in addition to your filter, just like I fixed https://github.com/uBlockOrigin/uAssets/issues/5271 by adding the domain + plus breaking the script.

**Comment by lain566** [comment]
For some reason, they know when their domain is blocked, or maybe they are using uBO, 
I don't know if it would break another sites.
