### ISSUE TITLE
faulty adblock detection

### ISSUE THREAD

**Issue by cometzkornrr** [uBlockOrigin/uAssets#21999]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

```yaml
https://emoji.gg/
```

### Description

I'm trying to use my discord bot called emoji uploader but when I go to the https://emoji.gg/ site (the site you upload from) it says it detected an ad blocker and or anti-tracking extension even though I turned all of my extensions off to see if it was one of them but it still falsely detected one.

### Other extensions used

manuals directory search, Grammarly, Ocean Hero, read aloud: a text-to-speech voice reader, safety search powered by Yahoo, to google translate, browsing safety by safely

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

i dont see it on the website.
```yaml


```
</details>

**Comment by krystian3w** [comment]
> them but it still falsely detected one.

So https://github.com/uBlockOrigin/uAssets/labels/site%20issue

You should contact with webmaster (instead waiting for free Internet Mother Teresah) if is not planned conservation od filters for that page.

**Comment by ItsProfessional** [comment]
moreover, if you actually enable uBO it won't be detected.
