### ISSUE TITLE
5-7 sec Video load @chip.de

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#22]
after 5-7 sec load, the Video playback @ chip .de, too long i think...

with ubo 1.6.9b1 the videos loads much faster ( sry for my bad english)

look @:

http://www.chip.de/news/Aldi-So-gut-ist-das-Medion-Notebook-vom-28.04_92379607.html

http://www.chip.de/news/Quicktime-Player-am-Ende-Das-sollten-Sie-jetzt-wissen_92378525.html

http://www.chip.de/video/Was-ist-9-7-Finden-Sie-die-Loesung-Video_91992963.html

### Your settings
 uBO standart filter

- Browser/version: [46 beta 11]
- uBlock Origin version: [1.6.9 beta 2]

**Comment by gorhill** [comment]
I can't reproduce.

Are you sure you are using default settings and nothing else?

**Comment by akks1981** [comment]
yes i use the default settings and flashplayer disabled, nothing else!

**Comment by IDKwhattoputhere** [comment]
Takes around 7 seconds for me with 1.6.9 beta 2 but also with 1.6.8 in Firefox 46.0b11.

**Comment by gorhill** [comment]
I used latest Nightly 48.0a1 to test.
