### ISSUE TITLE
www.bild.de

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#220]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

www.bild.de

### Describe the issue

Anti-Adblock measure specifically against Ublock Origin

### Screenshot(s)

https://s12.postimg.org/f68numtd9/bild.jpg

### Versions

- Browser/version: Firefox 50.0.2
- uBlock Origin version: 1.10.0

### Settings

- default settings

### Notes

Translation of the text:

Why do I not see BILD.de?
A plugin in your browser corrupts the function of the website, so we can not give you access to the content.
You may be using Ublock Origin or another Adblocker plugin. If this is the case, please try to disable it.

**Comment by Hrxn** [comment]
Default Settings with EasyList DE? Or is this a new global default?

**Comment by TonyTough** [comment]
Yes, with easylist DE
