### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by Kasapkedi** [uBlockOrigin/uAssets#22003]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aternos.org/files/`

### Category

detection

### Description

detection

### Other extensions used

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 117324
 cosmetic: 54178
 scriptlet: 21641
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  TUR-0: 13137-7, 2m
  easylist: 77310-33, 38m
  easyprivacy: 43423-42, 38m
  plowe-0: 3785-1172, 2m
  ublock-badware: 7732-136, 38m
  ublock-filters: 36387-136, 38m
  ublock-privacy: 963-7, 38m
  ublock-quick-fixes: 233-47, 38m
  ublock-unbreak: 2190-33, 38m
  urlhaus-1: 9740-0, 38m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 151 ms (selfie)
 maxAssetCacheWait: 68 ms
popupPanel:
 blocked: 10
 network:
  aternos.org: 1
  ad-delivery.net: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  quantserve.com: 1
  script.ac: 1
  upapi.net: 1
  venatusmedia.com: 1
  vntsm.com: 1
 extended:
  ##.header-center:style(margin-top:-5000px !important;)
  ##.sidebar:style(width: 1.745px !important;)
  ##.ad-dfp:style(min-height: 0.1485mm !important; height: 0.1485m…
```
</details>

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13144
