### ISSUE TITLE
twitter.com: ads

### ISSUE THREAD

**Issue by RambIing** [uBlockOrigin/uAssets#22009]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

```yaml
https://twitter.com/
```

### Description

Twitter experiments with ads that do not show "Ad" at the top nor have the same tracking divs as seen in the #20792 fix. 

From what I've noticed this requires looking in the `TweetDetail` graphQL, which might not be in scope for this. However having this issue open can hopefully get others to find suitable ways to block purely from something special in the HTML.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/b6110fbc-7b34-4b7a-b198-f955d8ab5139)
![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/6b472c28-dd96-4877-8b9d-e90d2a1cee76)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by ItsProfessional** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/20792
