### ISSUE TITLE
oggi.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#22005]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.oggi.it/video/personaggi/2024/01/15/gabriella-di-monaco-ruba-la-scena-a-mamma-charlene-wittstock/`

### Category

nuisance

### Description

cookies dialog

add `oggi.it` to
`corriere.it,gazzetta.it##+js(trusted-click-element, .privacy-cp-wall #privacy-cp-wall-accept)`

or to

```
! privacy-cp-wall sites - Accept
sosfanta.com,corriere.it##+js(trusted-click-element, #privacy-cp-wall-accept)

```
(is `corriere.it` duplicate?)

Then, if video doesn't play, add `oggi.it` to
`*$script,redirect-rule=noopjs,domain=corriere.it`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1129" alt="j" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/baeab065-4456-4f96-826e-e492a653d6ff">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 143704
 cosmetic: 177582
 scriptlet: 44855
 html: 2218
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81636-5894, 4m
  adguard-social: 22366-164, 4m
  adguard-cookies: 28392-42, 3m
  ublock-cookies-adguard: 888-0, 3m
  adguard-popup-overlays: 26746-929, 4m
  adguard-mobile-app-banners: 4901-7, 4m
  adguard-other-annoyances: 14044-66, 4m
  adguard-widgets: 2406-1, 4m
  ublock-annoyances: 6509-903, 4m Δ
  ITA-0: 8362-20, 3m
 default:
  user-filters: 1-0, never
  ublock-filters: 37088-472, 4m Δ
  ublock-badware: 7736-11, 4m Δ
  ublock-privacy: 958-0, 4m Δ
  ublock-unbreak: 2234-1, 4m Δ
  ublock-quick-fixes: 231-0, 4m Δ
  easylist: 77326-686, 4m Δ
  easyprivacy: 43426-901, 4m Δ
  urlhaus-1: 9740-0, 3m
  plowe-0: 3785-1, 4m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 447 ms (selfie)
 maxAssetCacheWait: 195 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  brandmetrics.com: 1
  confiant-integrations.net: 1
  d2bnxibecyz4h5.cloudfront.net: 1
  demdex.net: 1
  doubleclick.net: 1
  google.com: 1
  imasdk.googleapis.com: 1
  imrworldwide.com: 2
  insurads.com: 1
  permutive.app: 1
  rcsmetrics.it: 2
  rcsobjects.it: 2
  tiqcdn.com: 1
 extended:
  ##.socialContainer
  ##.adv-top-banner
  ###rcsad_TopLeft
  ##.social-box
  ##.social-wrapper
  ###rcsad_Frame1
  ###rcsad_Frame2
  ###hp_sez_advmkt_01
  ##.sidebar-item-adv
  ##.boxOpenx
  ##.adv-square
  ##.wrapper-bottom2
  ##a[href^="https://web.whatsapp.com/send?text="]
  ##+js(addEventListener-defuser, adb)
  ##+js(set-constant, google.ima.OmidVerificationVendor, {})
  ##+js(set-constant, Object.prototype.omidAccessModeRules, {})
```
</details>

**Comment by superlex** [comment]
@mapx- 
Don't you have issues playing videos?

https://github.com/uBlockOrigin/uAssets/assets/1375223/50d0ed87-2cc9-49ab-a443-62d6fdc6332a

https://github.com/uBlockOrigin/uAssets/assets/1375223/b46de92f-fbe7-402b-afe2-e480456f1326

**Comment by D4niloMR** [comment]
This helps?

```adb
@@||components2.rcsobjects.it/rcs_cpmt/v1/distro/oggi_ct.js$script,domain=oggi.it
oggi.it##body:remove-class(noScroll)
oggi.it##.privacy-cp-wall
```

with only uBlock annoyances this is not reproducible

**Comment by superlex** [comment]
@D4niloMR 
Nope.
Only `*$script,3p,redirect-rule=noopjs,domain=oggi.it` help on my end.
I don't understand which script exactly causes that.

**Comment by mapx-** [comment]
on my end: the videos are working fine in chrome but not in firefox (even whitelisting the page)
