### ISSUE TITLE
Anti Adblock by techsini.com

### ISSUE THREAD

**Issue by wSedlacek** [uBlockOrigin/uAssets#2200]
### URL(s) where the issue occurs
https://cmacapps.com/
http://techsini.com/

### Describe the issue
Anti adblock is not being blocked.

### Screenshot(s)
https://imgur.com/a/pMg53pQ

### Versions

- Browser/version: Chrome[66], Firefox[58]
- uBlock Origin version: 1.16.4

### Settings
Have tried nano defender, nano adblocker, reek's killer and xuhaiyang1234's killer

### Notes
This appears to be the adblock killer they are using:
https://wordpress.org/plugins/simple-adblock-notice/

Seems to be doing it based on content no loading? Not too sure. It has the warning even when just using pi.hole

**Comment by zaphodbeebblebrox** [comment]
`cmacapps.com##script:inject(setTimeout-defuser.js, google_jobrunner)`. It presumably works for the other site as well, but it gives me ERR_CONNECTION_TIMED_OUT.

**Comment by smed79** [comment]
add also
```
||fortpush.com^
||basepush.com^
```
