### ISSUE TITLE
[nsfw] 2th.me: detection

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#22016]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://2th.me/a/h_game/f1030/3045025`

### Category

detection

### Description

website does not show ads however the site knows that user is using adblocker

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot-1705400081852](https://github.com/uBlockOrigin/uAssets/assets/27200811/920efdcd-1823-4a10-a572-cbe222b9c614)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115561
 cosmetic: 44317
 scriptlet: 20029
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77393-12, 1h.31m Δ
  easyprivacy: 43439-37, 1h.31m Δ
  plowe-0: 3785-1172, now
  ublock-badware: 7742-136, 1h.31m Δ
  ublock-filters: 36455-129, 1h.31m Δ
  ublock-privacy: 962-7, 1h.31m Δ
  ublock-quick-fixes: 215-48, 1h.31m Δ
  ublock-unbreak: 2190-32, 1h.31m Δ
  urlhaus-1: 9445-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 884 ms (selfie)
 maxAssetCacheWait: 221 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  jads.co: 2
```
</details>

**Comment by Hazuki-san** [comment]
Update:
breakage in adblock reminder
![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/2ece571d-f4e1-41e7-94bd-026679cc6888)

**Comment by stephenhawk8054** [comment]
Isn't it just a placeholder for the ads? What breakages?

**Comment by Hazuki-san** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/edc2013d-e244-4084-a1a3-052edc224c78)

**Comment by stephenhawk8054** [comment]
Yes, it's the ads

**Comment by Hazuki-san** [comment]
Ah, okay. Then I suppose leaving space there wouldn't hurt. Would be nice if "Sponsered" text and the empty space there gets removed though.
