### ISSUE TITLE
novaramedia.com: nuisance

### ISSUE THREAD

**Issue by LooneyH** [uBlockOrigin/uAssets#22021]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://novaramedia.com/privacy-policy/`

### Category

nuisance

### Description

The page has two overlays, one for subscribing to slow support and another is for cookies. The cookie prompt has no decline button, nor can I find a clear method of doing so.

### Other extensions used

ClearURLs add-on, Firefox Relsy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240116-151921](https://github.com/uBlockOrigin/uAssets/assets/5049950/7c636f74-1626-4ad3-ba69-cf84f7923691)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 303208
 cosmetic: 196288
 scriptlet: 50598
 html: 2223
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76508-76506, 1m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1024-0, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1939-26, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95414-95404, now
  adguard-generic: 81663-7126, now
  adguard-spyware-url: 1425-105, now
  block-lan: 56-0, now
  curben-phishing: 84054-29, now
  adguard-social: 22379-1576, 1m
  fanboy-thirdparty_social: 68-1, 1m
  fanboy-cookiemonster: 49224-19730, 1m
  [14 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 37391-723, 2m Δ
  ublock-badware: 7740-11, 2m Δ
  ublock-privacy: 968-2, 2m Δ
  ublock-unbreak: 2239-3, 2m Δ
  ublock-quick-fixes: 221-0, 2m Δ
  adguard-mobile: 9043-133, now
  easylist: 77408-16947, now
  easyprivacy: 43439-1057, 2m Δ
  urlhaus-1: 9555-0, now
  plowe-0: 3785-2, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6926 ms
 maxAssetCacheWait: 1492 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
novaramedia.com###obligation-bar
novaramedia.com##.support-section
novaramedia.com##.support-bar
novaramedia.com##.background-support-texture
novaramedia.com##.email-signup
```

@ryanbr @Alex-302

**Comment by Alex-302** [comment]
Done.
