### ISSUE TITLE
Unable to Purge and Manually update Filter list as NEEDED for YouTube.

### ISSUE THREAD

**Issue by three7s** [uBlockOrigin/uAssets#22028]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

```yaml
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html
```

### Description

I have lost the ability to manually purge and update the filters lists. I have found nothing in the change logs to indicate that it was intentionally removed. This is NEEDED for uBlock to block the virus ads on YouTube. 

Please help!

Thank you

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBlock](https://github.com/uBlockOrigin/uAssets/assets/78269494/43241d5d-0923-4091-b61f-47b0c708c46e)

</details>

### Configuration

<details>
<summary>Details</summary>

```
Refreshed Page, restarted browser. still missing buttons

```
</details>

**Comment by D4niloMR** [comment]
See: https://github.com/gorhill/uBlock/commit/bd7ce41224

Also https://github.com/uBlockOrigin/uBlock-issues/discussions/2958
