### ISSUE TITLE
[nsfw] udvl.com: ads

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#22020]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://udvl.com/terms/`

### Category

ads

### Description

Ads appear at the bottom right of the site. The ads only appear on chrome and not on firefox.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1439" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/d3f966cf-64b6-43d0-80ee-82a0cff812a7">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115897
 cosmetic: 46076
 scriptlet: 24545
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6552-16, now
 default:
  user-filters: 50-2, never
  easylist: 77408-12, now
  easyprivacy: 43439-37, now
  plowe-0: 3785-1172, now
  ublock-badware: 7742-136, now
  ublock-filters: 36462-132, now
  ublock-privacy: 972-7, now
  ublock-quick-fixes: 215-48, 42m Δ
  ublock-unbreak: 2190-33, now
  urlhaus-1: 9445-0, now
filterset (user): [array of 44 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 7
 network:
  checkupforecast.com: 1
  googletagmanager.com: 1
  notonthebedsheets.com: 2
  o333o.com: 1
  tsyndicate.com: 1
  wpadmngr.com: 1
 extended:
  ##+js(abort-current-script, $, open)
```
</details>

**Comment by huyszn** [comment]
@mapx- I still see the ads on chrome when I click through links, like when I click on the "Top Rated" button and then the "Most Viewed" button on the `udvl.com` main page.

**Comment by D4niloMR** [comment]
Test:

`udvl.com##+js(aeld, DOMContentLoaded, popupurls)`

**Comment by huyszn** [comment]
> Test:
> 
> `udvl.com##+js(aeld, DOMContentLoaded, popupurls)`

The filter doesn't seem to change anything. I still see the ads.

**Comment by D4niloMR** [comment]
So, blocking these help?

```adb
||notonthebedsheets.com^
||a.ma3ion.com^
```

This filter https://github.com/uBlockOrigin/uAssets/issues/22020#issuecomment-1894729174 is for the popup on the video player

**Comment by huyszn** [comment]
> So, blocking these help?
> 
> ```
> ||notonthebedsheets.com^
> ||a.ma3ion.com^
> ```
> 
> This filter [#22020 (comment)](https://github.com/uBlockOrigin/uAssets/issues/22020#issuecomment-1894729174) is for the popup on the video player

Yes, I don't see the ads anymore. Also `udvl.com##+js(aeld, DOMContentLoaded, popupurls)` works to stop the popups on the video player. Didn't notice there were popups on the video player.

**Comment by D4niloMR** [comment]
@Yuki2718 for EasyList https://github.com/uBlockOrigin/uAssets/issues/22020#issuecomment-1894805277

`https://a.ma3ion.com/ad-provider.js`
`https://notonthebedsheets.com/achUHxa.js`

**Comment by D4niloMR** [comment]
@Yuki2718 `ma3ion.com` can be added to the popup list also

On the video player:

`https://teenanal.co/videos/1879269/featuring-and-tory-lanes-compilation-xxx/`
