### ISSUE TITLE
rki.de: breakage

### ISSUE THREAD

**Issue by Tegeler2** [uBlockOrigin/uAssets#22027]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

> Seite von `https://www.rki.de/grippeweb` wird zuerst komplett und vollständig geladen, dann jedoch falsch angezeigt. uBO filtert nichts, ist zum Test einzigstes AddOn.

**Page from `https://www.rki.de/grippeweb` is first loaded completely and completely, but then displayed incorrectly. uBO doesn't filter anything and is the only add-on for testing.**

### A specific URL where the issue occurs.

```yaml
https://www.rki.de/grippeweb
```

### Steps to Reproduce

1. Call URL from email
2. Register at `https://www.rki.de`
3. Page `https://www.rki.de/grippeweb` loads
4. Select the week to edit
5. Page of the week loads first, then appears with missing buttons and incorrect font

### Expected behavior

So far correct behavior as under Vivaldi (Chromium)

### Actual behavior

Incorrect representation of the page `https://www.rki.de/grippeweb`

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 117949
 cosmetic: 49201
 scriptlet: 18648
 html: 2012
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37042-127, 1h.52m Δ
  ublock-badware: 7746-11, 1h.52m Δ
  ublock-privacy: 968-0, 1h.52m Δ
  ublock-unbreak: 2234-1, 1h.52m Δ
  ublock-quick-fixes: 221-0, 1h.52m Δ
  easylist: 77408-629, 1h.52m Δ
  easyprivacy: 43439-837, 1h.52m Δ
  urlhaus-1: 9445-0, 9h.52m
  plowe-0: 3782-1, 2d.10h.9m
  DEU-0: 7284-3, 9h.53m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2967 ms (selfie)
 maxAssetCacheWait: 1000 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gorhill** [comment]
> displayed incorrectly, uBO doesn't filter anything

It's most certainly a cosmetic filter issue, cosmetic filters are not counted on the extension badge. Specific troubleshooting info should help identify the problematic cosmetic filter.

**Comment by Dani-1-2** [comment]
Looks fine to me. 
![Screenshot 2024-01-16 220534](https://github.com/uBlockOrigin/uAssets/assets/149429107/732fc47b-6df2-426a-b4d9-8e9557ded002)
![Screenshot 2024-01-16 220605](https://github.com/uBlockOrigin/uAssets/assets/149429107/4ee9efd5-4eec-46b7-838e-45b90e92d133)
![Screenshot 2024-01-16 220626](https://github.com/uBlockOrigin/uAssets/assets/149429107/75d75012-2729-4379-b58d-2a31a3814b58).
Is this what the webpage is supposed to look like? My config:
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 302243
 cosmetic: 244284
 scriptlet: 49174
 html: 2217
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81537-4324, 3d.1h.38m
  adguard-mobile: 9038-20, 3d.1h.38m
  adguard-spyware-url: 1422-96, 3d.37m
  adguard-spyware: 87245-28055, 3d.2h.40m
  block-lan: 55-0, 13d.3h.57m
  curben-phishing: 84054-29, 4h.18m
  adguard-social: 22343-882, 4d.34m
  adguard-cookies: 28344-59, 4d.34m
  ublock-cookies-adguard: 891-0, 19m
  adguard-popup-overlays: 26740-1686, 4d.35m
  adguard-mobile-app-banners: 4900-1072, 4d.35m
  adguard-other-annoyances: 14034-332, 4d.35m
  [12 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 37035-408, 11m Δ
  ublock-badware: 7746-11, 11m Δ
  ublock-privacy: 958-0, 11m Δ
  ublock-unbreak: 2234-1, 11m Δ
  ublock-quick-fixes: 212-0, 11m Δ
  easylist: 77393-2584, 11m Δ
  easyprivacy: 43439-1033, 11m Δ
  urlhaus-1: 9740-0, 23h.20m
  plowe-0: 3785-84, 23h.19m
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 897 ms (selfie)
 maxAssetCacheWait: 411 ms
 cacheBackend: indexedDB
 Logger screenshot:
![Screenshot 2024-01-16 220944](https://github.com/uBlockOrigin/uAssets/assets/149429107/33ca7206-5027-4a98-973f-0d617395ae1f)
