### ISSUE TITLE
[nsfw] 2th.me: breakage?

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#22022]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://2th.me/a/h_game/f1030/3045025`

### Category

breakage

### Description

the adblock reminder is gone but there's empty space there instead.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/15348857-501a-4fed-9129-57237db05b92)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115713
 cosmetic: 44323
 scriptlet: 20035
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77415-12, now
  easyprivacy: 43441-37, now
  plowe-0: 3785-1172, now
  ublock-badware: 7742-136, now
  ublock-filters: 36467-129, now
  ublock-privacy: 972-7, now
  ublock-quick-fixes: 223-48, now
  ublock-unbreak: 2190-32, now
  urlhaus-1: 9555-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 699 ms (selfie)
 maxAssetCacheWait: 248 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  jads.co: 2
  juicyads.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
continue in https://github.com/uBlockOrigin/uAssets/issues/22016
