### ISSUE TITLE
espaebook2.com: ads

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#22023]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.espaebook2.com/book/cuentos-del-inventor-de-respuestas-2/`

### Category

ads

### Description

4 fake download buttons left in this ebook site

EDIT: I forgot: The picture with the ebook cover is also a fake download button. It would be nice to keep the image but remove its link if possible

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/115593284/e7f4f4cc-173c-427d-a127-ac9fdabc86b3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 119312
 cosmetic: 110280
 scriptlet: 23898
 html: 2012
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28402-38, now
  ublock-cookies-adguard: 891-0, now
  fanboy-cookiemonster: 49297-3722, now
  ublock-cookies-easylist: 891-891, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37042-114, 57m Δ
  ublock-badware: 7746-11, 57m Δ
  ublock-privacy: 968-0, 57m Δ
  ublock-unbreak: 2234-1, 57m Δ
  ublock-quick-fixes: 221-0, 57m Δ
  easylist: 77415-626, now
  easyprivacy: 43441-834, now
  urlhaus-1: 9555-0, now
  plowe-0: 3785-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms (selfie)
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  espaebook2.com: 3
  google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`espaebook2.com##[href*="foxqck.com"]`

@Yuki2718 for spanish list

**Comment by Rust1667** [comment]
thank you
