### ISSUE TITLE
avherald.com: nuisance

### ISSUE THREAD

**Issue by d89u** [uBlockOrigin/uAssets#22037]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.avherald.com/
```

### Description

Content is blocked by cookie notice. Cookie notice is powered by getadmiral.com

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 120579
 cosmetic: 120930
 scriptlet: 23159
 html: 2013
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49314-182, now
  fanboy-social: 16104-8, now
  ublock-quick-fixes: 229-0, 4h.10m Δ
  easylist-annoyances: 4313-97, now
  easylist-chat: 177-0, now
  easylist-newsletters: 6885-13, now
  easylist-notifications: 2909-4, now
  ublock-cookies-easylist: 892-0, now
 default:
  user-filters: 107-1, never
  ublock-filters: 37061-134, 4h.10m Δ
  ublock-badware: 7746-11, 4h.10m Δ
  ublock-privacy: 968-0, 4h.10m Δ
  ublock-unbreak: 2234-1, 4h.10m Δ
  easylist: 77445-654, 4h.10m Δ
  easyprivacy: 43446-924, 4h.10m Δ
  urlhaus-1: 7970-0, 10h.32m
  plowe-0: 3784-1, 10d.21h.4m
  DEU-0: 7283-4, 10h.32m
filterset (user): [array of 107 redacted]
trustedset:
 added: [array of 62 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2670 ms (selfie)
 maxAssetCacheWait: 196 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  adsafeprotected.com: 2
  advertising.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  merequartz.com: 2
  storage.googleapis.com: 2
 extended:
  ###adcell

```
</details>

**Comment by D4niloMR** [comment]
From which country are you accessing the site?

**Comment by d89u** [comment]
Germany

![grafik](https://github.com/uBlockOrigin/uAssets/assets/156951282/a24ab2bd-3525-4bc3-81aa-5f13feaa6a82)

**Comment by D4niloMR** [comment]
I can reproduce with uBO disabled, but the domain serving the cookie is not blocked, shouldn't cause problem if blocked.

Add in "My filters" and test:

`||possiblepencil.com^`

**Comment by d89u** [comment]
That works. Thank you!
