### ISSUE TITLE
buycycle.com: privacy

### ISSUE THREAD

**Issue by Shivam1n** [uBlockOrigin/uAssets#22036]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://buycycle.com/en-us`

### Category

privacy

### Description

an analytics request from Adyen payment company

checkoutshopper-live.adyen.com/checkoutshopper/images/analytics.png?
checkoutshopper-live.adyen.com/checkoutshopper/v2/analytics/log?

!
||adyen.com/*/analytics

This request will be shown to you on the checkout page or after checkout so try adding a product to your cart and purchasing it.

### Other extensions used

dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 120274
 cosmetic: 52483
 scriptlet: 18659
 html: 2013
listset (total-discarded, last-updated):
 added:
  IND-0: 12996-9, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37061-182, 42m
  ublock-badware: 7746-11, 42m
  ublock-privacy: 968-0, 42m
  ublock-unbreak: 2234-1, 42m
  ublock-quick-fixes: 229-0, 42m
  easylist: 77445-552, 42m
  easyprivacy: 43446-831, 42m
  urlhaus-1: 9255-0, 42m
  plowe-0: 3785-1, 42m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3352 ms
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  rudderlabs.com: 1
  trustpilot.com: 1
```
</details>

**Comment by mapx-** [comment]
report directly here, for easyprivacy list: https://github.com/easylist/easylist/issues

@ryanbr
