### ISSUE TITLE
live.vodafone.de: ads

### ISSUE THREAD

**Issue by Slipi089** [uBlockOrigin/uAssets#22030]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://live.vodafone.de/unterhaltung/tvkino/judith-rakers-verabschiedet-sich-von-der-tagesschau/12456378`

### Category

ads

### Description

The website displays advertising banners

### Other extensions used

Undo close tabs, Bitwarden, decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![17-01-2024_06-43-02](https://github.com/uBlockOrigin/uAssets/assets/59597268/17472971-c424-4d49-a630-b701db644ac6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 116492
 cosmetic: 49203
 scriptlet: 20034
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7283-0, now
  easylist: 77408-19, now
  easyprivacy: 43446-46, now
  plowe-0: 3785-1173, now
  ublock-badware: 7742-136, now
  ublock-filters: 36462-144, now
  ublock-privacy: 972-7, now
  ublock-quick-fixes: 226-48, now
  ublock-unbreak: 2190-34, now
  urlhaus-1: 7970-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 590 ms
 maxAssetCacheWait: 5 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  arcor.de: 2
  criteo.net: 3
  googletagmanager.com: 1
  outbrain.com: 2
 extended:
  ##.gujAd
```
</details>

**Comment by stephenhawk8054** [comment]
@okiehsch @JobcenterTycoon Just FYI that I have splitted the filter as per some other big filters
