### ISSUE TITLE
youtg.net: breakage

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#22039]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://youtg.net/`

### Category

breakage

### Description

No video with EasyPrivacy list enabled.
It looks like due to
`||msvdn.net/api/v2/heartbeat/`
Could you check, please?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1073" alt="no" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/09876d64-9f5e-45e8-9519-4a9d1283e209">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 117228
 cosmetic: 50899
 scriptlet: 18659
 html: 2013
listset (total-discarded, last-updated):
 added:
  ITA-0: 8347-19, 5m
 default:
  user-filters: 0-0, never
  ublock-filters: 37062-121, 5m Δ
  ublock-badware: 7746-11, 5m
  ublock-privacy: 968-0, 5m Δ
  ublock-unbreak: 2234-1, 5m
  ublock-quick-fixes: 229-0, 5m
  easylist: 77457-627, 5m
  easyprivacy: 43476-831, 5m
  urlhaus-1: 9255-0, 5m
  plowe-0: 3785-1, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 2486 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 33
 network:
  youtg.net: 1
  googlesyndication.com: 9
  msvdn.net: 22
  nativery.com: 1
 extended:
  ###sp-adv-banner-top
  ##ins.adsbygoogle
  ###sp-testata
  ##.banneritem
  ##.player-ads
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`||msvdn.net/api/v2/heartbeat/$badfilter`
