### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by DaStarr1212** [uBlockOrigin/uAssets#22038]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

on channels i still recieve ads 

### Other extensions used

[`https://www.twitch.tv/](https://www.twitch.tv/gamesdonequick)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115450
 cosmetic: 44331
 scriptlet: 20045
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77445-12, 57m
  easyprivacy: 43446-37, 57m
  plowe-0: 3785-1172, now
  ublock-badware: 7742-136, 57m
  ublock-filters: 36481-129, 57m
  ublock-privacy: 971-7, 57m
  ublock-quick-fixes: 231-48, 57m
  ublock-unbreak: 2190-32, 57m
  urlhaus-1: 9255-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1044 ms
 maxAssetCacheWait: 395 ms
popupPanel:
 blocked: 26
 network:
  twitch.tv: 6
  amazon-adsystem.com: 6
  d2v02itv0y9u9t.cloudfront.net: 1
  imrworldwide.com: 7
  scorecardresearch.com: 4
  serving-sys.com: 1
  ttvnw.net: 1
 extended:
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/5184
