### ISSUE TITLE
nsw2u.net: breakage

### ISSUE THREAD

**Issue by masterofobzene** [uBlockOrigin/uAssets#22031]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nsw2u.net/Category/switch/xci`

### Category

breakage

### Description

Game banners cannot be seen

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-17 at 10-10-23 XCI Archives nsw2u net](https://github.com/uBlockOrigin/uAssets/assets/94469116/28f44adb-af36-424a-ab71-29176fccb41d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 256346
 cosmetic: 275868
 scriptlet: 51155
 html: 2245
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76530-76530, 2m
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/startpage/global.txt: 4206-0, 1m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 1m
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, 1m
  adguard-generic: 81686-7129, 1m
  adguard-spyware-url: 1421-105, 1m
  block-lan: 56-0, 1m
  adguard-social: 22386-877, 1m
  fanboy-thirdparty_social: 68-0, 1m
  fanboy-cookiemonster: 49320-3802, 1m
  fanboy-social: 16105-22, 1m
  ublock-annoyances: 6507-908, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 525-41, never
  ublock-filters: 37061-437, now
  ublock-badware: 7746-11, now
  ublock-privacy: 968-0, now
  ublock-unbreak: 2234-0, now
  easylist: 77445-1008, now
  easyprivacy: 43446-1048, now
  urlhaus-1: 9255-0, 1m
  plowe-0: 3785-1626, 1m
  ublock-quick-fixes: 229-1, now
filterset (user): [array of 525 redacted]
trustedset:
 added: [array of 24 redacted]
switchRuleset:
 added: [array of 9 redacted]
hostRuleset:
 added: [array of 541 redacted]
urlRuleset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2096 ms
 maxAssetCacheWait: 827 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  dubannihilation.com: 1
  googletagmanager.com: 1
 extended:
  ##.sidebar.columns.large-4
  ###footer-widget
  ##[href^="https://bit.ly/"]
  ##body .code-block
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  ##+js(abort-current-script, eval, replace)
  ##+js(no-xhr-if, googlesyndication)
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(abort-on-stack-trace, document.createElement, adsBlocked)
  ##+js(abort-current-script, eval, split)
  ##+js(abort-on-property-read, adsBlocked)
  ##+js(noeval-if, /fairAdblock|chp_?adblock|adsbygoogle\.js/)
  ##+js(set-constant, adbEnableForPage, false)
  ##+js(abort-current-script, document.createElement, break;case $…
```
</details>

**Comment by ItsProfessional** [comment]
Even with uBO disabled, the "Game banners cannot be seen" issue is reproducible.
