### ISSUE TITLE
bloggingtips.com: ads

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#22033]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bloggingtips.com/`

### Category

ads

### Description

Contains bottom-right notification popups and in-article ads for stuff like bluehost

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 117425
 cosmetic: 69762
 scriptlet: 21063
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28404-30, now
 default:
  user-filters: 41-0, never
  easylist: 77457-14, now
  easyprivacy: 43452-40, now
  plowe-0: 3785-1173, now
  ublock-badware: 7742-136, now
  ublock-filters: 36481-131, now
  ublock-privacy: 971-7, now
  ublock-quick-fixes: 229-47, 47m
  ublock-unbreak: 2190-32, now
  urlhaus-1: 9255-0, now
filterset (user): [array of 43 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 89 ms
popupPanel:
 blocked: 7
 network:
  adthrive.com: 2
  duckduckgo.com: 2
  googletagmanager.com: 1
  pressidiumcdn.com: 1
  videoplayerhub.com: 1
 extended:
  ##.adthrive
  ##.adthrive-ad
  ##.adthrive-content
```
</details>

**Comment by mapx-** [comment]
You should provide specific pages where you get those ads / notification stuff (+ screenshots indicating the items)

**Comment by huyszn** [comment]
For the "bottom-right notification popups", are you talking about this? I get this on the main page by clicking on the "Free Blogging Course" button at the top right which opens a new tab and then returning to the original tab with the main page using chrome.
<img width="1440" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/251b9486-adb7-42f6-9ee9-a77ca057630f">
