### ISSUE TITLE
todayheadline.co: ads

### ISSUE THREAD

**Issue by Shivam1n** [uBlockOrigin/uAssets#22034]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://todayheadline.co/`

### Category

ads

### Description

id="wpgtr_stickyads_textcss_container"

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 120274
 cosmetic: 52483
 scriptlet: 18659
 html: 2013
listset (total-discarded, last-updated):
 added:
  IND-0: 12996-9, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37061-182, 5m
  ublock-badware: 7746-11, 5m
  ublock-privacy: 968-0, 5m
  ublock-unbreak: 2234-1, 5m
  ublock-quick-fixes: 229-0, 5m
  easylist: 77445-552, 5m
  easyprivacy: 43446-831, 5m
  urlhaus-1: 9255-0, 5m
  plowe-0: 3785-1, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3352 ms
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  deployads.com: 3
  googlesyndication.com: 2
  googletagmanager.com: 1
  hs-analytics.net: 1
  hs-banner.com: 1
  hsforms.com: 1
  midas-network.com: 2
  wp.com: 2
 extended:
  ##.ads-wrapper
  ##ins.adsbygoogle
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`todayheadline.co###wpgtr_stickyads_textcss_container`
