### ISSUE TITLE
hit-films.com: nuisance

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#22045]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hit-films.com/best-german-movies-part-1/`

### Category

nuisance

### Description

This is a link shortener

You get to it coming from `https://hit-films.com/safe.php?adfly1=1jtjbfolam`

When you get to the site I'm reporting, it makes you wait with a timer to show you a button.
That button moves you to the bottom of the page, where you find the final button. 
This final button is the only thing that should appear from the beginning (if you can fix it)

That final button is defined with this HTML element on "step 3/4":
```<button id="btn6" class="tp-btn tp-blue" style="display: block;">Continue</button>```

On the next "step 4/4" the final button has this element:
```<button class="tp-btn tp-blue">Continue</button>```

unnecessary extra detail: one arrives to these particular links shorteners originally from a site called "olamovies"

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 121616
 cosmetic: 116686
 scriptlet: 24288
 html: 2013
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28406-38, 35m
  ublock-cookies-adguard: 892-0, 35m
  fanboy-cookiemonster: 49319-3724, 35m
  ublock-cookies-easylist: 892-892, 35m
  spa-0: 3796-3, 35m
  spa-1: 5711-162, 35m
 default:
  user-filters: 0-0, never
  ublock-filters: 37063-133, 35m
  ublock-badware: 7746-11, 35m
  ublock-privacy: 969-0, 35m
  ublock-unbreak: 2234-1, 35m
  ublock-quick-fixes: 230-0, 35m
  easylist: 77497-679, 35m
  easyprivacy: 43452-848, 35m
  urlhaus-1: 9255-0, 35m
  plowe-0: 3785-1, 35m
filterset (user): [empty]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 615 ms (selfie)
 maxAssetCacheWait: 182 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  d3u598arehftfk.cloudfront.net: 1
  googletagmanager.com: 1
  r2b2.io: 19
```
</details>

**Comment by huyszn** [comment]
Can you provide the original link on olamovies? I get different link shorteners and not the link shortener that has `hit-films.com` when I go to olamovies.

**Comment by Rust1667** [comment]
I'm trying to track where I got to that link from and now I can't find it sorry, I clicked too many of them.
But olamovies seems to have a lot of these different shorteners, almost a diferent one with each link.
I'm almost certain its one of the links from the movie "The Marvels" but its giving me different shorteners now...

**Comment by huyszn** [comment]
I was asking because when I go to `https://hit-films.com/safe.php?adfly1=1jtjbfolam`. It says I am on step 3/4, so I think this domain is part of another shortener.

**Comment by Rust1667** [comment]
I see...

I confirm it was the release for "The Marvels" ```"[2160p 4K sdr [11.51gb]](https://olamovies.yachts/generate/?id=112223)"``` because that id=112223 is the one arrived to and the end of the shortener I reported. But now the link is expired and they seem to generate a new different one

**Comment by huyszn** [comment]
Ok, I found out the domain comes from this shortener: `https://link.owllink.net/4pmip8olam`

**Comment by Rust1667** [comment]
Ah nice.
I also finally found the originator shortener to the one I reported looking through the history
Its this:
`https://link.birdurls.com/1jtjbfolam?__cf_chl_tk=TBU8tEKgkY0x.Tfi1f.9iBcuVCqagSx25WQIpTa2r00-1705535118-0-gaNycGzNDVA`

**Comment by huyszn** [comment]
Try these filters:
```
hit-films.com###btn6:style(display: block !important;)
hit-films.com###btn6:others()
```

**Comment by Rust1667** [comment]
Those worked perfectly
Now I only see the "Continue" button which is all that needs to be there
