### ISSUE TITLE
mmotutkunlari.com: ads

### ISSUE THREAD

**Issue by Ebrehe** [uBlockOrigin/uAssets#22048]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mmotutkunlari.com/`

### Category

ads

### Description

ads

### Other extensions used

...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/106402223/54981adb-0ba5-44f1-96cc-ddaf6cab633b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 156130
 cosmetic: 171805
 scriptlet: 32016
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js: 118-75, now
  https://github.com/pixeltris/TwitchAdSolutions/raw/master/video-swap-new/video-swap-new-ublock-origin.js: 99-74, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2553-1, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 46412-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1108-4, now
  adguard-cookies: 28406-46, now
  adguard-popup-overlays: 26774-101, now
  block-lan: 56-0, now
  easylist-annoyances: 4313-158, 1h.29m
  easylist-chat: 177-2, now
  easylist-newsletters: 6882-461, 1h.29m
  easylist-notifications: 2907-209, 1h.28m
  [5 lists not shown]: [too many]
 default:
  user-filters: 24-0, never
  TUR-0: 13217-38, now
  easylist: 77503-12229, now
  easyprivacy: 43453-5930, 24m Δ
  plowe-0: 3785-2306, now
  ublock-badware: 7742-162, 24m Δ
  ublock-filters: 36483-323, 24m Δ
  ublock-privacy: 973-77, now
  ublock-quick-fixes: 233-46, 24m Δ
  ublock-unbreak: 2190-37, 24m Δ
  urlhaus-1: 8975-0, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 24 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1216 ms (selfie)
 maxAssetCacheWait: 752 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  mmotutkunlari.com: 2
  google.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.p-footer-rssLink
  ##.js-notice.notice--cookie
  ##.notice--cookie:not(body):not(html)
  ##.u-scrollButtons
```
</details>

**Comment by Alex-302** [comment]
@kodiakhub Some users report dozens of porn-farms per hour. This is a case where rules are unlikely to be added.
