### ISSUE TITLE
Twitch.tv: uBlock Origin breaks video controls on twitch after watching for a few minutes.

### ISSUE THREAD

**Issue by TheMightyTore** [uBlockOrigin/uAssets#22041]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.twitch.tv/
```

### Description

I'm very sorry but I couldn't for the life of me find where to post twitch issues. this is not about ads but about how uBlock Origin breaks video controls on twitch after watching for a few minutes (can't pause/play, change volume, go fullscreen/theatre mode.)

I have a fresh uBlock install, restored default settings, removed every other chrome extension, have no custom filters added yet uBlock breaks the twitch players video controls. the problem does NOT occur when I uninstall uBlock, problem persists though if I just turn off uBlock (not disabling it through chrome, just disabling it specifically for twitch) on twitch.

I know there is a temporary fix for this by resizing the window to get video controls back, and some others said removing BetterTTV fixed it, but uBlock Origin is my only extension and the problem only occurs with it. I've tested with many extension combinations and the problem just happen whenever uBlock is enabled or alone.

I have been updating the filter list and I've still been struggling with this issue for a few weeks now. Any help would be much appreciated. I'm sorry again this is posted in the wrong place, I'd be happy to repost in the correct category if I could be shown how. Thank you!

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115505
 cosmetic: 44340
 scriptlet: 20045
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77497-12, 30m
  easyprivacy: 43452-37, 30m
  plowe-0: 3785-1172, 30m
  ublock-badware: 7742-136, 30m
  ublock-filters: 36482-129, 30m
  ublock-privacy: 972-7, 30m
  ublock-quick-fixes: 233-46, 30m
  ublock-unbreak: 2190-32, 30m
  urlhaus-1: 9255-0, 30m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 165 ms (selfie)
 maxAssetCacheWait: 87 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  twitch.tv: 1
  amazon-adsystem.com: 1
  d2v02itv0y9u9t.cloudfront.net: 1
  scorecardresearch.com: 3
 extended:
  ##+js(no-window-open-if, amazon-adsystem)

```
</details>

**Comment by big-cat-loaf** [comment]
--> #5184 <--

**Comment by D4niloMR** [comment]
> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
