### ISSUE TITLE
videogames.si.com: breakage

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#22055]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://videogames.si.com/reviews/the-last-of-us-part-2-remastered-review`

### Category

breakage

### Description

The video doesn't play with the error, "This video cannot be played because of a technical error."

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115532
 cosmetic: 46117
 scriptlet: 24577
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6553-16, now
 default:
  user-filters: 61-3, never
  easylist: 77508-12, 22m
  easyprivacy: 43456-37, now
  plowe-0: 3786-1173, now
  ublock-badware: 7742-136, now
  ublock-filters: 36491-132, now
  ublock-privacy: 973-7, now
  ublock-quick-fixes: 232-46, now
  ublock-unbreak: 2192-33, now
  urlhaus-1: 8975-0, now
filterset (user): [array of 56 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 430 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 83
 network:
  si.com: 4
  33across.com: 9
  3lift.com: 1
  adnxs.com: 2
  adsrvr.org: 1
  amazon-adsystem.com: 5
  bidswitch.net: 2
  casalemedia.com: 1
  contextweb.com: 2
  d1z2jf7jlzjs58.cloudfront.net: 1
  datadome.co: 1
  doubleclick.net: 1
  doubleverify.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwplayer.com: 1
  jwpltx.com: 1
  kargo.com: 2
  liadm.com: 5
  lijit.com: 1
  outbrain.com: 1
  permutive.app: 1
  petametrics.com: 11
  pubmatic.com: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
  spot.im: 8
  stickyadstv.com: 1
  teads.tv: 1
  typekit.net: 1
  yahoo.com: 12
 extended:
  ##.m-balloon-header--spacer
  ##.m-balloon-header--ad
  ##.m-header-ad
  ##.m-in-content-ad-row
  ##.m-in-content-ad
  ##.m-ad
  ##.l-grid--ad-card
  ##+js(trusted-click-element, .message-container.global-font butt…
  ##+js(trusted-click-element, [data-choice="1683026410215"], , 50…
  ##+js(trusted-click-element, .sanoma-logo-container ~ .message-c…
  ##+js(trusted-click-element, button[title="Accept all"])
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
||jwplayer.com^$domain=americansongwriter.com|dexerto.com|gamesradar.com|ginx.tv|infoworld.com|kiplinger.com|soulbounce.com|spokesman-recorder.com|tennis.com|thestreet.com|tomshardware.com|variety.com|videogames.si.com|whathifi.com
```

in EL.

@ryanbr @Yuki2718
