### ISSUE TITLE
mybacklog.gg: breakage

### ISSUE THREAD

**Issue by tejapoth** [uBlockOrigin/uAssets#22051]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mybacklog.gg/`

### Category

breakage

### Description

when adblock the website stops being responsive after 6 seconds

### Other extensions used

lastpass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115214
 cosmetic: 44338
 scriptlet: 20045
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77457-12, 3m
  easyprivacy: 43479-37, 3m
  plowe-0: 3785-1172, 3m
  ublock-badware: 7742-136, 3m
  ublock-filters: 36482-129, 3m Δ
  ublock-privacy: 972-7, 3m Δ
  ublock-quick-fixes: 233-46, 3m Δ
  ublock-unbreak: 2190-32, 3m Δ
  urlhaus-1: 8975-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 655 ms
 maxAssetCacheWait: 190 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  ezodn.com: 2
 extended:
  ##[data-ez-name]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ###ez-sidebar-wall-left
  ##.ez-sidebar-wall-ad
  ##.ezoic-ad
  ##.adtester-container
  #@#[id^="div-gpt-ad"]
  #@#.ad-unit
  #@#.banner-ads
  #@#.banner_ads
  #@#.ad-zone
  #@#.ad-space
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to sign in to reproduce the issue?

**Comment by tejapoth** [comment]
No you don’t need to sign-in. This is how to reproduce the issue.
1. go to mybacklog.gg
2. Click on the right arrow 
<img width="1399" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/34321739/b1aa0e0a-8fdb-4eeb-8ee7-72c5e9b74159">
3. Then you’ll see the right arrow wont move to the next page of the games. and then few seconds later the website gets stuck!

**Comment by huyszn** [comment]
Test `mybacklog.gg###ez-sidebar-wall-right`

`###ez-sidebar-wall-left` is in unbreak filters but not `###ez-sidebar-wall-right`

**Comment by tejapoth** [comment]
im not a coder, i have no idea how to do that sorry

**Comment by tejapoth** [comment]
hi this is marked as completed but unfortunately it isn’t fixed.

**Comment by stephenhawk8054** [comment]
The fix is added here: https://github.com/uBlockOrigin/uAssets/commit/c1bc82c021ad4cdd2008212850552752f9f471a4

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/b83fb873-a5c8-4721-91a5-e8192056153a)

Wait about 5-6 hours, the filter lists will be automatically updated, or you can add this filter meanwhile

```adb
##.ez-sidebar-wall
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by tejapoth** [comment]
awesome! it worked after I added ##.ez-sidebar-wall to "My Filter" pane. 
Should I delete this ##.ez-sidebar-wall from "My Filter" after a couple of days after the filter lists gets updated?

btw thanks. for fixing so soon! :D

**Comment by stephenhawk8054** [comment]
Yes, you can remove it usually after 5-6 hours, or more if the updates are still not there for you yet.

**Comment by tejapoth** [comment]
cheers!
