### ISSUE TITLE
parcelsapp.com: nuisance

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#22052]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://parcelsapp.com/`

### Category

nuisance

### Description

Opening the developer tools will trigger a debugger statement.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.1b8
Firefox: 121
filterset (summary):
 network: 115216
 cosmetic: 44340
 scriptlet: 18665
 html: 2013
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37067-64, 1h.24m Δ
  ublock-badware: 7746-11, 1h.24m Δ
  ublock-privacy: 970-0, 1h.24m Δ
  ublock-unbreak: 2234-1, 1h.24m Δ
  ublock-quick-fixes: 230-47, 1h.24m Δ
  easylist: 77499-222, 1h.24m Δ
  easyprivacy: 43453-58, 1h.24m Δ
  urlhaus-1: 8975-0, 1h.24m
  plowe-0: 3785-1173, 24m
filterset (user): [array of 68 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1006 ms
 maxAssetCacheWait: 380 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  adpushup.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##._ap_apex_ad
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
you could try

`parcelsapp.com##+js(set, Array, {})`

or just use chrome and click "deactivate breakpoints" (ctrl+F8)

**Comment by ItsProfessional** [comment]
> or just use chrome
FYI: this can be done in firefox >=121 by unchecking "Pause on debugger statement"

**Comment by mapx-** [comment]
Unfortunately only theoritacally: try it yourself, it will block Firefox

**Comment by mapx-** [comment]
it does not work in chrome, I'll close it, at least in chrome we have a way to use the dev tools
