### ISSUE TITLE
lfnw.org: breakage

### ISSUE THREAD

**Issue by bear454** [uBlockOrigin/uAssets#22068]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lfnw.org/`

### Category

breakage

### Description

The 'partners' section of our sponsor roll is removed by cosmetic filtering.

### Other extensions used

none (testing in private view with all other extensions disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without uBlock, or with uBlock cosmetic filtering disabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/108494/2452ca1f-d76e-46d5-90f7-f509e751dee3)

With uBlock default settings:
![image](https://github.com/uBlockOrigin/uAssets/assets/108494/9f87a3fe-42b9-48a3-a093-1d999a8d6c12)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115332
 cosmetic: 44342
 scriptlet: 18660
 html: 2013
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37061-111, now
  ublock-badware: 7746-11, now
  ublock-privacy: 969-0, now
  ublock-unbreak: 2236-1, now
  ublock-quick-fixes: 229-0, now
  easylist: 77503-621, now
  easyprivacy: 43458-832, now
  urlhaus-1: 9085-0, now
  plowe-0: 3786-1, 1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 553 ms
 maxAssetCacheWait: 165 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-cosmetic-filtering: true
 extended:
  ###sponsor-partners
```
</details>

**Comment by ItsProfessional** [comment]
1. Blocked by easylist, not us.
2. Intentional

**Comment by bear454** [comment]
Thanks for the guidance/direction; I can fix based on that.
