### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by GitGitu79** [uBlockOrigin/uAssets#22065]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

ads

### Description

There is an ad banner at the right side of the screen

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/152173286/45c58208-645b-4188-b9fc-7001c3b96ddb)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/152173286/ee098bd7-3828-449b-a716-d2dc92dab504)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115383
 cosmetic: 44356
 scriptlet: 20054
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77540-13, 10m
  easyprivacy: 43458-38, 10m
  plowe-0: 3786-1173, 10m
  ublock-badware: 7752-136, 10m
  ublock-filters: 36496-129, 10m
  ublock-privacy: 973-7, 10m
  ublock-quick-fixes: 232-46, 10m
  ublock-unbreak: 2192-32, 10m
  urlhaus-1: 9085-0, 10m
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4480 ms (selfie)
 maxAssetCacheWait: 1633 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  live.com: 2
  adnxs.com: 2
  office.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances` and test again.

**Comment by GitGitu79** [comment]
It works, the banner is now gone
