### ISSUE TITLE
einthusan.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2206]
URL(s) where the issue occurs

`https://einthusan.tv/movie/watch/zgIA/?lang=hindi`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by KiLL4FuNK** [comment]
When the movie tries to load, it detects uBlock Origin

**Comment by mapx-** [comment]
try
`@@*einthusan*$xmlhttprequest,domain=imasdk.googleapis.com`

**Comment by KiLL4FuNK** [comment]
It works well

**Comment by mapx-** [comment]
for chrome
`*einthusan*$xmlhttprequest,redirect=nooptext,domain=imasdk.googleapis.com`

**Comment by KiLL4FuNK** [comment]
It works well

`*einthusan*$xmlhttprequest,redirect=nooptext,domain=imasdk.googleapis.com`

**Comment by okiehsch** [comment]
The redirection is the "better" fix, because the video starts instantly without the "loading advertising" screen.
I added the exception filter and I also added the redirection for chromium based browsers only.
````
@@||springserve.com/vast/*einthusan$xmlhttprequest,domain=imasdk.googleapis.com
!#if env_chromium
||springserve.com/vast/*einthusan$xmlhttprequest,important,redirect=nooptext,domain=imasdk.googleapis.com
!#endif
````

I can't test Safari on a Mac, so the exception filter is the standard fix, if the redirection works with every browser except Firefox we could change the standard fix.

**Comment by zaphodbeebblebrox** [comment]
The filter strangely does nothing in safari. However, `||springserve.com/vast/*einthusan$xmlhttprequest,important,redirect=nooptext,domain=einthusan.tv` works.

**Comment by okiehsch** [comment]
Does it work if you add
````
||springserve.com/vast/*einthusan$xmlhttprequest,redirect=nooptext,domain=imasdk.googleapis.com
!#if env_firefox
@@||springserve.com/vast/*einthusan$xmlhttprequest,domain=imasdk.googleapis.com
!#endif
````
with all your browsers?
You have to remove the fix I added or simply disable uBO-filters.

**Comment by zaphodbeebblebrox** [comment]
It works in firefox (post-quantum), waterfox (pre-quantum), chrome, edge, safari for me.

**Comment by okiehsch** [comment]
Thanks for testing.
