### ISSUE TITLE
getmodsapk.com: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#22064]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://getmodsapk.com/real-moto-2-mod-apk/`

### Category

ads

### Description

empty ad placeholder

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium Mobile: 110
filterset (summary):
 network: 126609
 cosmetic: 165066
 scriptlet: 29287
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6632-197, now
 default:
  user-filters: 42-6, never
  adguard-mobile: 9060-16, now
  easylist: 77540-122, now
  easyprivacy: 43458-161, now
  plowe-0: 3786-1249, now
  ublock-badware: 7746-137, now
  ublock-filters: 36867-633, now
  ublock-privacy: 974-9, now
  ublock-quick-fixes: 232-47, now
  ublock-unbreak: 2197-37, now
  urlhaus-1: 9085-0, now
filterset (user): [array of 42 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2088 ms
 maxAssetCacheWait: 724 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##+js(adjust-setInterval, download, *, 0.02)
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 there is popup domain `grapseex.com` unblocked by EL.

**Comment by Yuki2718** [comment]
@JobcenterTycoon How to reproduce?

**Comment by JobcenterTycoon** [comment]
Click on "Download" -> Open the dropdown menu -> Click on "XAPK 201.17 MB" inside the dropdown menu. The site try to open a popuo which is blocked by a uBO regex but the domain is unblocked by EL.
