### ISSUE TITLE
discord.com: GCP uploads not working

### ISSUE THREAD

**Issue by erkinalp** [uBlockOrigin/uAssets#22062]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://discord.com/`

### Category

breakage

### Description

https://discord-attachments-uploads-prd.storage.googleapis.com is blocked, which prevents attachment uploads

### Other extensions used

greasemonkey, but no userscripts are enabled for discord.com
dark reader

### Screenshot(s)

Not necessary in this specific report

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 1374859
 cosmetic: 255680
 scriptlet: 50958
 html: 2224
listset (total-discarded, last-updated):
 added:
  https://curbengh.github.io/urlhaus-filter/urlhaus-filter-online.txt: 3945-0, now
  https://fanboy.co.nz/fanboy-turkish.txt: 823-0, now
  https://filters.adtidy.org/extension/ublock/filters/5.txt: 16-0, now
  https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt: 6-0, now
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/BadIpList.txt: 14-2, now
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/HostsList.txt: 9872-35, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiBadCapitalismList.txt: 573-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiFunctionalityRemovalList.txt: 22-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt: 439-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/EmptyPaddingRemover.txt: 45-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/I Don't Want to Download Your Browser.txt: 61-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 50-0, now
  [32 lists not shown]: [too many]
 default:
  user-filters: 10-1, never
  ublock-filters: 37072-422, 1h.42m Δ
  ublock-badware: 7746-23, 1h.42m Δ
  ublock-privacy: 969-3, 1h.42m Δ
  ublock-unbreak: 2236-2, 1h.42m Δ
  ublock-quick-fixes: 229-0, 1h.42m Δ
  easylist: 77508-1091, 1h.42m Δ
  easyprivacy: 43457-1105, 1h.42m Δ
  urlhaus-1: 9085-3910, now
  plowe-0: 3786-282, now
  TUR-0: 13219-171, now
filterset (user): [array of 10 redacted]
trustedset:
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 allowGenericProceduralFilters: true
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 600
 filterAuthorMode: true
 trustedListPrefixes: ublock- user- adguard- easylist-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 651 ms (selfie)
 maxAssetCacheWait: 467 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 230
 network:
  discord.com: 217
  storage.googleapis.com: 13
```
</details>

**Comment by stephenhawk8054** [comment]
You are using a lot of custom filter lists. Test again in another browser profile with only uBO and its default settings.

**Comment by erkinalp** [comment]
hmm, cannot reproduce anymore
once i opened ubo debugger, i lost the ability to reproduce it for all
weird

**Comment by stephenhawk8054** [comment]
Please follow what you ticked on:

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

**Comment by erkinalp** [comment]
@stephenhawk8054 I tried that as well, was the same, no longer reproducing
