### ISSUE TITLE
bing.com: breakage

### ISSUE THREAD

**Issue by joaofbravo** [uBlockOrigin/uAssets#22066]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bing.com/search?q=Bing+AI&showconv=1`

### Category

breakage

### Description

Settings button in Bing Copilot does not open anything.
Clicking my account name also does nothing anymore.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/30523313/8c1a6110-f42b-4c30-b1b3-6029d48b71ab)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 211172
 cosmetic: 119032
 scriptlet: 25712
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2553-1, now
  DEU-0: 7284-0, now
  adguard-cookies: 28416-30, now
  adguard-spyware-url: 1423-156, now
  curben-phishing: 84680-20, now
  fanboy-cookiemonster: 49319-3704, now
  spa-1: 5711-67, now
  ublock-cookies-adguard: 895-8, now
  ublock-cookies-easylist: 895-895, now
 default:
  user-filters: 25-1, never
  easylist: 77540-23, now
  easyprivacy: 43458-50, now
  plowe-0: 3786-1175, now
  ublock-badware: 7752-143, now
  ublock-filters: 36496-175, now
  ublock-privacy: 973-117, now
  ublock-quick-fixes: 232-46, now
  ublock-unbreak: 2192-37, now
  urlhaus-1: 9085-0, now
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 771 ms (selfie)
 maxAssetCacheWait: 173 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 36
 network:
  bing.com: 36
 extended:
  ##body:style(overflow: auto !important;)
  ##+js(trusted-set-cookie, BCP, AD=0&AL=0&SM=0)
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
```
</details>

**Comment by mapx-** [comment]
> Clicking my account name also does nothing anymore.
add & test:
`bing.com#@#body:style(overflow: auto !important;)`

> Settings button in Bing Copilot

where is that button ?

**Comment by krystian3w** [comment]
At screen is Edege.

**Comment by ryanbr** [comment]
It came from https://github.com/uBlockOrigin/uAssets/issues/18497  is this still current?

**Comment by mapx-** [comment]
I no longer get `.bnp_cookie_banner` in the logger even though the page refers to it, but maybe it's safer removing
both filters

```
bing.com##.bnp_cookie_banner
bing.com##body:style(overflow: auto !important;)
```

**Comment by mapx-** [comment]
@joaofbravo add & test

```
bing.com#@#.bnp_cookie_banner
bing.com#@#body:style(overflow: auto !important;)
```

**Comment by joaofbravo** [comment]
> > Clicking my account name also does nothing anymore.
> 
> add & test: `bing.com#@#body:style(overflow: auto !important;)`
> 
> > Settings button in Bing Copilot
> 
> where is that button ?

this solved it. Thank you!

**Comment by joaofbravo** [comment]
> @joaofbravo add & test
> 
> ```
> bing.com#@#.bnp_cookie_banner
> bing.com#@#body:style(overflow: auto !important;)
> ```

Using `bing.com#@#body:style(overflow: auto !important;)` solves the problem but removing the `@` makes it come back. Why?

**Comment by mapx-** [comment]
The filter with `@` disables the original cosmetic filter (which causes the breakage)
