### ISSUE TITLE
bombuj.si: breakage

### ISSUE THREAD

**Issue by Beji-kun** [uBlockOrigin/uAssets#22073]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bombuj.si/`

### Category

breakage

### Description

1. Choose film
2. Video player of film isn't available

### Other extensions used

only uBlock

### Screenshot(s)
<details>
<summary>Screenshot(s)</summary>

![e1f1e63f-4513-4180-b0a6-29dbbd8817e7](https://github.com/uBlockOrigin/uAssets/assets/63636174/9e4a2c01-250f-44a5-af9d-33fe7fc38779)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115410
 cosmetic: 44372
 scriptlet: 20085
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77573-13, now
  easyprivacy: 43464-38, now
  plowe-0: 3786-1173, now
  ublock-badware: 7752-136, now
  ublock-filters: 36531-130, now
  ublock-privacy: 973-7, now
  ublock-quick-fixes: 233-46, now
  ublock-unbreak: 2192-32, now
  urlhaus-1: 9085-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 344 ms (selfie)
 maxAssetCacheWait: 95 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  wurfl.io: 1
 extended:
  ##[href][target="_blank"]
  ##style:has-text(blink_me_ad):upward(2)
```
</details>

**Comment by huyszn** [comment]
The video players load when I enable the EasyList Czech and Slovak regional list.

**Comment by krystian3w** [comment]
So maybe possible copy his solution to small 🇸🇮 list?

**Comment by mapx-** [comment]
@Beji-kun enable `EasyList Czech and Slovak`

**Comment by Beji-kun** [comment]
How to do it ? Can tou navigate me? thx

**Comment by ItsProfessional** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists
