### ISSUE TITLE
leboncoin.fr: breakage

### ISSUE THREAD

**Issue by Herrifunix** [uBlockOrigin/uAssets#22079]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.leboncoin.fr/messages
https://www.leboncoin.fr/mes-annonces
https://www.leboncoin.fr/mes-recherches
https://www.leboncoin.fr/compte/part/accueil
```

### Description

The content of the page is removed

### Other extensions used

Enhancer for Youtube
Eye Dropper
Force background Tab
Honey
Return Youtube Dislike
TamperMonkey (No script used on this site)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/79200718/0eb59805-c104-48fb-9c28-0ecb40ff1aad)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 145922
 cosmetic: 204264
 scriptlet: 32819
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28423-32, 10m
  adguard-mobile-app-banners: 4901-7, 10m
  adguard-other-annoyances: 14103-10, 10m
  adguard-popup-overlays: 26784-90, 10m
  adguard-social: 22403-932, 10m
  adguard-widgets: 2408-4, 10m
  easylist-annoyances: 4313-242, 10m
  easylist-chat: 177-12, 10m
  easylist-newsletters: 6888-465, 10m
  easylist-notifications: 2908-1468, 10m
  fanboy-cookiemonster: 49327-3756, 10m
  fanboy-social: 16103-750, 10m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  FRA-0: 26862-40, 10m
  easylist: 77574-117, 32m Δ
  easyprivacy: 43544-413, 32m Δ
  plowe-0: 3786-1185, 10m
  ublock-badware: 7752-151, 32m Δ
  ublock-filters: 36543-591, 32m Δ
  ublock-privacy: 973-9, 32m Δ
  ublock-quick-fixes: 239-46, 32m Δ
  ublock-unbreak: 2192-40, 32m Δ
  urlhaus-1: 9040-0, 10m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 532 ms (selfie)
 maxAssetCacheWait: 362 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 12
 network:
  github.com: 12
 extended:
  ###cookie-consent-banner

```
</details>

**Comment by mapx-** [comment]
@Herrifunix an account is required (and a french phone number), so we cannot investigate your issue.

Try resetting uBO to the default lists / settings and test again.

**Comment by Herrifunix** [comment]
Tried with another laptop and it works properly, guess the issue isn't on Ublock
