### ISSUE TITLE
rambler.ru: privacy

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#22076]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rambler.ru/`

### Category

privacy

### Description

Add please: `||rambler.ru/*#rcmrclid=$uritransform=/#rcmrclid=.*//`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![rambler](https://github.com/uBlockOrigin/uAssets/assets/20126984/0d544603-0165-4a45-bf99-1c150d01cb89)

</details>

### Configuration

<details>

uBlock Origin: 1.55.1b10 default + RUS: RU AdList + uBlock filters – Annoyances

Firefox: 115

</details>

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054

**Comment by stephenhawk8054** [comment]
Hmm... What's the issue with the old filter?

**Comment by dimisa-RUAdList** [comment]
The old version works reliably only in Firefox. Chrome-based browsers often open blank pages.

<details>
<summary>Gif</summary>

![Image](https://github.com/user-attachments/assets/ba942345-52d7-40dc-a615-c8a22f49c227)

</details>

**Comment by stephenhawk8054** [comment]
Hmm... I still can't reproduce it in Chromium, but modifying it is not big problem.

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
Please replace ~> `gazeta.press,gazeta.ru,rambler.ru##+js(trusted-replace-fetch-response, /#rcmrclid=[a-zA-Z0-9]+/g, '')`

**Comment by stephenhawk8054** [comment]
It's better to narrow down the URL of the fetch response. Making it run in all fetch requests is not good for performance.

**Comment by dimisa-RUAdList** [comment]
`gazeta.press,gazeta.ru,rambler.ru##+js(trusted-replace-fetch-response, /#rcmrclid=[a-zA-Z0-9]+/g, '', rcm.rambler.ru)`
