### ISSUE TITLE
play.max.com: ads

### ISSUE THREAD

**Issue by mpjensen4** [uBlockOrigin/uAssets#22074]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://play.max.com/video/watch/4442c78e-f7e5-4f52-ab41-4f0a0bb94792/25c17e69-f83f-4ef7-a806-f19cc366cdf9`

### Category

ads

### Description

ads are showing up within the video, doesnt load the 30 second ads, but still displays them.
tried changing a few different variables but nothing vhanged.

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115430
 cosmetic: 44371
 scriptlet: 18696
 html: 2017
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37111-111, 15m Δ
  ublock-badware: 7756-11, 15m Δ
  ublock-privacy: 969-0, 15m Δ
  ublock-unbreak: 2236-0, 15m Δ
  ublock-quick-fixes: 233-1, 15m Δ
  easylist: 77573-624, 15m Δ
  easyprivacy: 43464-832, 15m Δ
  urlhaus-1: 9115-0, now
  plowe-0: 3786-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 406 ms (selfie)
 maxAssetCacheWait: 181 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 141
 network:
  max.com: 124
  app.link: 3
  demdex.net: 1
  googletagmanager.com: 1
  litix.io: 12
 extended:
  ##+js(json-prune, ssaiInfo fallback.ssaiInfo)
  ##+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="Seg…
  ##+js(json-prune, adtech-brightline adtech-google-pal adtech-iab…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
play.max.com#@#+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="SegmentTimeline"])][not(.//*[name()="ContentProtection"])]), , .mpd)
play.max.com##+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="SegmentTimeline"])][not(.//*[name()="ContentProtection"])] | //*[name()="Period"][./*[name()="BaseURL"]][not(.//*[name()="ContentProtection"])]), , .mpd)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by mpjensen4** [comment]
Yeah, that seemed to work! thanks so much!

**Comment by daenyraine** [comment]
willing to share credentials, also used said filters and did not work.

**Comment by stephenhawk8054** [comment]
You can send the account to this email: `stephenhawk8054@protonmail.com`

**Comment by stephenhawk8054** [comment]
@daenyraine Can you test these filters?

```adb
play.max.com#@#+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="SegmentTimeline"])][not(.//*[name()="ContentProtection"])] | //*[name()="Period"][./*[name()="BaseURL"]][not(.//*[name()="ContentProtection"])]), , .mpd)

play.max.com##+js(xml-prune, xpath(//*[name()="MPD"]/@mediaPresentationDuration | //*[name()="Period"]/@start | //*[name()="Period"][not(.//*[name()="SegmentTimeline"])][not(.//*[name()="ContentProtection"])] | //*[name()="Period"][./*[name()="BaseURL"]][not(.//*[name()="ContentProtection"])]), , .mpd)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by daenyraine** [comment]
seems to have solved the issue so far, tried opening several episodes and all worked well, will update if anything changes.
