### ISSUE TITLE
[nsfw] shemalez.com: ads

### ISSUE THREAD

**Issue by qenxdi** [uBlockOrigin/uAssets#22071]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://shemalez.com/videos/750385/beautiful-tranny-takes-deep-anal-dicking-allison-ferrety/`

### Category

ads

### Description

divs with random name

### Other extensions used

tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 72400
 cosmetic: 142075
 scriptlet: 6153
 html: 42
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26065-45, 9m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1706-0, 9m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76575-1453, now
 default:
  user-filters: 214-3, never
  easylist: 77563-58, now
  RUS-0: 40253-138, 9m Δ
filterset (user): [array of 214 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 60 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 contextMenuEnabled: false
 hyperlinkAuditingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 396 ms (selfie)
 maxAssetCacheWait: 165 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  baccarat112.com: 12
  boannred.com: 1
  d592971f36.com: 1
  exoclick.com: 1
  exosrv.com: 1
  metricswpsh.com: 3
  mnaspm.com: 1
  multstorage.com: 1
  pix-cdn.org: 2
  vstserv.com: 1
  vstvstsa.com: 2
  wpu.sh: 1
  yandex.ru: 2
  zog.link: 1
 extended:
  ##.video-tube-friends
  ##.header__cookie
  ##a[href^="https://bongacams"][href*="com/track?"]
  ##a[href^="https://bongacams10.com/track?"]
  ##a[href^="https://clickadilla.com/"]
```
</details>

**Comment by D4niloMR** [comment]
Re-enable the default lists?

> ```
> listset (total-discarded, last-updated):
>  removed:
>   ublock-filters: null
>   ublock-badware: null
>   ublock-privacy: null
>   ublock-unbreak: null
>   ublock-quick-fixes: null
>   easyprivacy: null
>   urlhaus-1: null
>   plowe-0: null
> ```
