### ISSUE TITLE
froxy.com: breakage

### ISSUE THREAD

**Issue by x0r2d2** [uBlockOrigin/uAssets#22086]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://froxy.com
```

### Description

Hubspot Support Widget unable to load with turned on ublock filters - Privacy

### Other extensions used

1password
Deepl translator
ESET Browser Privacy & Security

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/12900872/4343d379-2960-4ed6-884c-331dae620bce)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 89347
 cosmetic: 91373
 scriptlet: 37168
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
  ublock-privacy: null
 added:
  adguard-generic: 81870-487, 10m
  adguard-mobile: 9068-48, 10m
 default:
  user-filters: 0-0, never
  easylist: 77574-1753, 10m
  ublock-badware: 7752-317, 6m Δ
  ublock-filters: 36543-3437, 11m
  ublock-quick-fixes: 239-46, 10m
  ublock-unbreak: 2192-80, 6m Δ
  urlhaus-1: 9040-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 310 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 4

```
</details>

**Comment by mapx-** [comment]
@stephenhawk8054 maybe it's about these filters:

commit `52f32e19fcd35ee381488cf3d7d2f5d567582e32`

```
$removeparam=__hssc
$removeparam=__hstc
```

**Comment by okiehsch** [comment]
>  unable to load with turned on ublock filters - Privacy

`@@||googletagmanager.com/gtm.js$script,domain=froxy.com`
fixes the issue on my end, so I don't think it's caused by a filter in `uBO-privacy`.

**Comment by mapx-** [comment]
right, now I can reproduce the issue and your filter fixes it
