### ISSUE TITLE
ukrayina.pl: leftovers

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#22085]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ukrayina.pl/ukrayina/7,183471,30611019,1050-1110-1073-1077-1088-1072-1090-1072-1082-1072.html`

### Category

leftovers

### Description

I see leftovers on this site.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-01-19_161349](https://github.com/uBlockOrigin/uAssets/assets/111344219/2721b022-1dc6-4571-8785-e4f6cc3a68e3)
![2024-01-19_161406](https://github.com/uBlockOrigin/uAssets/assets/111344219/295101fe-1d6b-4f4d-9190-ff3eb9b20e33)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.1b10
Chromium: 120
filterset (summary):
 network: 132752
 cosmetic: 65573
 scriptlet: 21523
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  RUS-0: 40214-9, 3m
  easylist: 77508-35, 2m
  easyprivacy: 43454-124, 2m
  plowe-0: 3781-1173, 2m
  ublock-badware: 7752-136, 2m
  ublock-filters: 36566-154, 2m
  ublock-privacy: 974-8, 2m
  ublock-quick-fixes: 239-46, 2m
  ublock-unbreak: 2192-32, 2m
  urlhaus-1: 9040-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 537 ms (selfie)
 maxAssetCacheWait: 238 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adviewDFPBanner
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by D4niloMR** [comment]
Test:

`ukrayina.pl##+js(set, dfpParams.slots, null)`

**Comment by dportvine** [comment]
> Test:
> 
> `ukrayina.pl##+js(set, dfpParams.slots, null)`

Tnx, works for me.

**Comment by D4niloMR** [comment]
@xxcriticxx for Oficjalne Polskie Filtry do uBlocka Origin https://github.com/uBlockOrigin/uAssets/issues/22085#issuecomment-1900652627

**Comment by dportvine** [comment]
Also `https://wiadomosci.gazeta.pl/wiadomosci/7,114884,30612741,sprawa-syna-poslanki-filiks-krrit-nie-ukarze-radia-szczecin.html`

<details>
<summary>Screenshot(s)</summary>

![2024-01-19_214016](https://github.com/uBlockOrigin/uAssets/assets/111344219/40d7884d-82e6-468b-af6b-f62b3ded6199)
</details>

`gazeta.pl,ukrayina.pl##+js(set, dfpParams.slots, null)` scriplet solved this problem.
