### ISSUE TITLE
bricklink.com: breakage

### ISSUE THREAD

**Issue by uexfclonq** [uBlockOrigin/uAssets#22088]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bricklink.com/v3/studio/download.page`

### Category

breakage

### Description

Cookie selection banner text is blocked, but not the white background of the banner. The page is not usable

### Other extensions used

Snowflake, Bitwarden, Wikimapper, Youtube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-01-19 19 24 49 www bricklink com 1fbf3e2423f2](https://github.com/uBlockOrigin/uAssets/assets/82674753/4af629ed-c4f6-48a1-bda0-3983cacc62aa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 121671
 cosmetic: 120699
 scriptlet: 23941
 html: 0
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95605-16328, 22h.27m
 default:
  user-filters: 9-2, never
  DEU-0: 7284-1, 21h.27m
  easylist: 77594-45, now Δ
  easyprivacy: 43545-186, now Δ
  plowe-0: 3782-1170, 5d.22h.4m
  ublock-badware: 7762-136, now Δ
  ublock-filters: 36538-191, now Δ
  ublock-privacy: 976-9, now Δ
  ublock-quick-fixes: 238-46, now Δ
  ublock-unbreak: 2193-37, now Δ
  urlhaus-1: 9085-0, 21h.26m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 610 ms (selfie)
 maxAssetCacheWait: 111 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  facebook.net: 1
  google-analytics.com: 1
 extended:
  ##.cookie-notice__content
```
</details>

**Comment by gorhill** [comment]
Works fine with AdGuard Cookie Notices though, it uses these filters:

    bricklink.com##body:style(overflow: auto!important;)
    bricklink.com##.cookie-notice


cc @ryanbr
