### ISSUE TITLE
blog.topfaucet.us: detection

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#22087]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://blog.topfaucet.us/`

### Category

detection

### Description

overlay saying "Ads Blocker Detected!!!"

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 121504
 cosmetic: 116753
 scriptlet: 24395
 html: 2020
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28428-38, now
  ublock-cookies-adguard: 898-0, now
  fanboy-cookiemonster: 49329-3732, now
  ublock-cookies-easylist: 898-898, now
  spa-0: 3796-3, now
  spa-1: 5719-162, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37118-161, now
  ublock-badware: 7766-11, now
  ublock-privacy: 972-0, now
  ublock-unbreak: 2237-1, now
  ublock-quick-fixes: 238-0, 33m Δ
  easylist: 77594-681, now
  easyprivacy: 43545-847, now
  urlhaus-1: 9040-0, now
  plowe-0: 3781-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 496 ms (selfie)
 maxAssetCacheWait: 202 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  alwingulla.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by ItsProfessional** [comment]
By the way, is this domain part of a shortener?

**Comment by ItsProfessional** [comment]
....... why? only report sites you actually use.
