### ISSUE TITLE
dotnet.guide: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#22097]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://dotnet.guide/internet/google-domains.html
```

### Description

Permanent anti-adblock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ss_01](https://github.com/uBlockOrigin/uAssets/assets/72945564/340b4f96-91c4-424a-a82d-f3cb8dcefb2b)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBO dev, Firefox/Opera, default

```
</details>

**Comment by garry-ut99** [comment]
`ghide` has caused a placeholder to appear : [SCREENSHOOT](https://github.com/uBlockOrigin/uAssets/assets/72945564/8b2bc541-62f5-41d5-98d9-27a769bc44ef)

**Comment by okiehsch** [comment]
That "placeholder" is there without the ghide filter too on my end.
It's a youtube video wrapper.
Add
`dotnet.guide##.fluid-width-video-wrapper` to your filter list if you want to remove it.

**Comment by garry-ut99** [comment]
I know, what I meant was that the ad placeholder visually has become bigger after adding `ghide`, and was smaller without `ghide`. I've checked deeper again, reloaded page 20 times with `ghide` and 20 times without `ghide`, 
and I see now that regardless of `ghide` on or off , this stupid ad placholder sometimes appears bigger and sometimes smaller, but since this happens regardless of `ghide` on or off,  I must admit it's not your fault, but not my fault either, it's just the stupid site's scripts or site's third-party ads, or some filters causing such "random szie of ad placeholder" effect, also it seems to happen only on Firefox, see : [ANIMATION](https://github.com/uBlockOrigin/uAssets/assets/72945564/54496f20-04c3-48a1-a9f5-e0801f359464) (page reloaded 3-4 times)
