### ISSUE TITLE
netflix.com: breakage

### ISSUE THREAD

**Issue by soyrod** [uBlockOrigin/uAssets#22090]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When you play a video on Netflix and you have uBlock Origin activated in the Opera Browser, it seems that it is causing some problem when Netflix tries to show an ad, as the window closes and changes to one that indicates that there is interference with a browser extension and by inference must be uBlock

### A specific URL where the issue occurs.

```yaml
https://www.netflix.com/watch/80000527?trackId=155573558
```

### Steps to Reproduce

1. You play video
2. the video advances to the end
3. The video may crash when finishing the video or starting the next one

### Expected behavior

When it works correctly, you see the occasional video advertisement, sometimes none appear in the entire video you watch.

### Actual behavior

You can watch several videos in a row without the problem appearing but unexpectedly the page closes and the gray background page appears (in Opera Browser) with the browser extension warning causing a conflict

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 117898
 cosmetic: 50758
 scriptlet: 20504
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 11-0, never
  easylist: 77590-20, 1m
  easyprivacy: 43547-39, 1m
  plowe-0: 3781-1169, 1m
  spa-0: 3796-19, 1m
  spa-1: 5719-213, 1m
  ublock-badware: 7762-136, 1m
  ublock-filters: 36516-178, 1m
  ublock-privacy: 976-7, 1m
  ublock-quick-fixes: 240-46, 1m
  ublock-unbreak: 2193-34, 1m
  urlhaus-1: 9040-0, 1m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 671 ms (selfie)
 maxAssetCacheWait: 98 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by gorhill** [comment]
> - [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

How did you verify that this is not a filter list issue?

Provide troubleshooting information _for the site_ once you get the issue: Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by soyrod** [comment]
> > * [x]  I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
> 
> How did you verify that this is not a filter list issue?
> 
> Provide troubleshooting information _for the site_ once you get the issue: Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

A few days ago Netflix was working as is, showing sporadic video ads, but today this error appeared, and I tried restarting the browser and deactivating the native Opera blocker. I haven't added anything to the filter list or changed the UBO configuration.

I emphasize that the problem is not constant and can appear after having watched several videos, but I am surprised that not a single ad video has appeared so far, so I suspect that the problem appears when UBO interferes when an ad tries to appear

**Comment by soyrod** [comment]
![imagen_2024-01-19_154420861](https://github.com/uBlockOrigin/uAssets/assets/34144665/6ef0be92-7a28-4a43-a218-dd5149163526)

**Comment by gorhill** [comment]
> I emphasize that the problem is not constant and can appear after having watched several videos

You need to find out if this happens with uBO fully disabled in the browser.

> I haven't added anything to the filter list

Sites and filter lists change all the time, issues arising from these are not a content blocker issues, they are filter list issues.

**Comment by soyrod** [comment]
> > I emphasize that the problem is not constant and can appear after having watched several videos
> 
> You need to find out if this happens with uBO fully disabled in the browser.
> 
> > I haven't added anything to the filter list
> 
> Sites and filter lists change all the time, issues arising from these are not a content blocker issues, they are filter list issues.

Before writing the report I had already manually updated the lists, and if it were only the lists it would not show that error but the classic blocking that uBO shows.

**The temporary solution is to leave the native blocker of the Opera browser enabled and deactivate uBO for Netflix, this way the error no longer appears**

**Comment by gorhill** [comment]
> if it were only the lists

> deactivate uBO for Netflix

Deactivating uBO for Netflix actually _proves_ this is a filter issue.

If you don't trust we know what we are doing to diagnose an issue and rather argue about this, and not help identify the filter issue by providing the information we are asking, we can't move this issue forward, we will have to close it. Again:

> Provide troubleshooting information _for the site_ once you get the issue: Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)
