### ISSUE TITLE
blockchain.com: ads

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#22093]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.blockchain.com/explorer/transactions/bch/9891c46d5a0c322a32cef900bf81ef81a8907b43d9ae0f360ba373036bcaa556`

### Category

ads

### Description

some casino ads in the top right corner.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/e35927c2-5835-402d-a8e7-aec8492787f8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115315
 cosmetic: 44393
 scriptlet: 18755
 html: 2021
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37123-111, now
  ublock-badware: 7766-11, now
  ublock-privacy: 969-0, now
  ublock-unbreak: 2237-1, now
  ublock-quick-fixes: 240-0, now
  easylist: 77595-623, now
  easyprivacy: 43547-858, now
  urlhaus-1: 8980-0, now
  plowe-0: 3781-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4550 ms
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 43
 network:
  cloudflare.com: 40
  coinzillatag.com: 1
  czilladx.com: 1
  google-analytics.com: 1
```
</details>

**Comment by huyszn** [comment]
Test this filter: `||api.blockchain.info/explorer-gateway/advertisements$xhr,domain=blockchain.com`

**Comment by ave9858** [comment]
> Test this filter: `||api.blockchain.info/explorer-gateway/advertisements$xhr,domain=blockchain.com`

works, ty

**Comment by stephenhawk8054** [comment]
@ryanbr
