### ISSUE TITLE
online-fix.me: popups

### ISSUE THREAD

**Issue by nerdeded** [uBlockOrigin/uAssets#22092]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://online-fix.me/`

### Category

popups

### Description

the site opens a small window at the bottom right that opens whenever you visit the site after closing the window two times it will no longer appear

### Other extensions used

BTRoblox
Dark Reader
MyJDownloader Browser Extension
Tampermonkey (no running scripts)
600% Sound volume
Hide Youtube Fullscreen Controls
![image](https://github.com/uBlockOrigin/uAssets/assets/157082952/49c5523e-7767-4cb4-a55b-17c5ef53228b)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/157082952/38c0e64c-bf86-49b6-b020-110c7cd18570)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115313
 cosmetic: 44389
 scriptlet: 18755
 html: 2020
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37118-139, 14m Δ
  ublock-badware: 7766-11, 14m Δ
  ublock-privacy: 972-0, 14m Δ
  ublock-unbreak: 2237-1, 14m Δ
  ublock-quick-fixes: 238-0, 14m Δ
  easylist: 77594-623, 14m Δ
  easyprivacy: 43545-830, 14m Δ
  urlhaus-1: 8980-0, 14m
  plowe-0: 3781-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 342 ms (selfie)
 maxAssetCacheWait: 240 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  d2v02itv0y9u9t.cloudfront.net: 2
  google.com: 1
  translate.googleapis.com: 3
  videoroll.net: 2
  yadro.ru: 3
  yandex.ru: 1
 extended:
  ##+js(no-setTimeout-if, /width|innerHTML/)
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `RU AdList` filter list and test again?

**Comment by subby2006** [comment]
`/services/?id=$script,domain=online-fix.me` seems to fix it

**Comment by nerdeded** [comment]
> Can you enable `RU AdList` filter list and test again?

this solved the issue
