### ISSUE TITLE
manatoki322.net: ads

### ISSUE THREAD

**Issue by Kaz238** [uBlockOrigin/uAssets#22094]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://manatoki322.net/comic/18235893`

### Category

ads

### Description

Ads always back after I block it manually

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115340
 cosmetic: 44392
 scriptlet: 20126
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-3, never
  easylist: 77595-13, now
  easyprivacy: 43548-39, now
  plowe-0: 3781-1169, now
  ublock-badware: 7762-136, now
  ublock-filters: 36515-159, now
  ublock-privacy: 975-7, now
  ublock-quick-fixes: 240-46, 10m Δ
  ublock-unbreak: 2193-32, now
  urlhaus-1: 8980-0, now
filterset (user): [array of 20 redacted]
trustedset:
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1081 ms (selfie)
 maxAssetCacheWait: 407 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  google.com: 2
  histats.com: 1
  translate.googleapis.com: 2
  waust.at: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `List-KR` filter list and test again?
