### ISSUE TITLE
nationalpost.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2210]
### URL(s) where the issue occurs

`Nationalpost.com`

### Describe the issue

Anti-adblock.  (Also some random blocked youtube thumbnails, but that isn't nearly as important)

### Settings

Default settings.

### Notes

Is there a reason for the filter `||nationalpost.com^$generichide,important`? There doesn't seem to be a generichide filter if I remove it.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/458#issuecomment-315173013 the reason was the excessive whitelisting from EasyList regarding Instart Logic sites at the time.
I will remove it.

**Comment by rcdmk** [comment]
Currently detecting uBO Lite and displaying an overlay asking to pay or disable adblocker.

https://nationalpost.com/news/canada/vancouver-rent-commuting-alberta-to-bc
![image](https://github.com/user-attachments/assets/f021a298-c2c4-4560-a497-9dd933b094b5)

**Comment by stephenhawk8054** [comment]
@rcdmk Which mode are you using for uBOL?

**Comment by rcdmk** [comment]
@stephenhawk8054 I tried with all modes with the same results

**Comment by rcdmk** [comment]
One has to scroll down to the article to trigger that, though. Or maybe just waiting a few seconds is enough.

**Comment by stephenhawk8054** [comment]
Can you screenshot your settings in uBO settings page? (Not the dashboard in the toolbar)
