### ISSUE TITLE
playingfire.com: nuisance

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#22106]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.playingfire.com/steps-to-set-up-a-date-with-a-girl-over-text/`

### Category

nuisance

### Description

This site blocks the ability to select text, preventing people from copy-pasting content.

I tried with all the official annoyance filters enabled.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 121523
 cosmetic: 116775
 scriptlet: 24400
 html: 2028
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28432-38, now
  ublock-cookies-adguard: 898-0, now
  fanboy-cookiemonster: 49349-3736, now
  ublock-cookies-easylist: 898-898, now
  spa-0: 3797-3, now
  spa-1: 5719-162, now
 default:
  user-filters: 1-0, never
  ublock-filters: 37099-161, now
  ublock-badware: 7766-11, now
  ublock-privacy: 992-0, now
  ublock-unbreak: 2237-1, now
  ublock-quick-fixes: 245-0, now
  easylist: 77645-681, now
  easyprivacy: 43548-847, now
  urlhaus-1: 9010-0, now
  plowe-0: 3781-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 567 ms (selfie)
 maxAssetCacheWait: 192 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 2
  google.com: 1
  googletagmanager.com: 2
  hs-scripts.com: 2
  youtube.com: 1
 extended:
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by ABetterWeb** [comment]
It looks like `AdGuard – Other Annoyances` addresses it

**Comment by ABetterWeb** [comment]
Test with `AdGuard – Cookie Notices`

**Comment by Rust1667** [comment]
> Test with `AdGuard – Cookie Notices` or add `||[hs-scripts.com](http://hs-scripts.com)^$3p` to `My filters`

Tried both, it still won't let me select text.

**Comment by ABetterWeb** [comment]
Oh, my bad.

```
playingfire.com##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
```

**Comment by Rust1667** [comment]
> Oh, my bad.
> 
> ```
> [playingfire.com##*:style](http://playingfire.com##*:style)(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
> ```

Thank you, this worked!

**Comment by ABetterWeb** [comment]
heck yeah
