### ISSUE TITLE
aptekiplus.ru breakage 

### ISSUE THREAD

**Issue by Reym-ai** [uBlockOrigin/uAssets#22105]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://aptekiplus.ru/
```

### Description

When enabling uBlock: Technical work is underway on the site. We apologize for the inconvenience.

### Other extensions used

7TV, SponsorBlock for YouTube.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/148795905/ad84402a-d264-44c8-bfda-ca499c66cc2a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 309025
 cosmetic: 251105
 scriptlet: 52349
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 9m
  adguard-cookies: 28430-44, 1d.1h.9m
  adguard-generic: 81877-708, 1d.1h.9m
  adguard-mobile: 9071-74, 1d.1h.10m
  adguard-mobile-app-banners: 4904-10, 1d.7m
  adguard-other-annoyances: 14105-46, 1d.7m
  adguard-popup-overlays: 26796-450, 1d.7m
  adguard-social: 22390-937, 3d.4h.10m
  adguard-spyware: 88566-1274, 1d.1h.9m
  adguard-spyware-url: 1423-5, 1d.8m
  adguard-widgets: 2408-18, 1d.8m
  block-lan: 56-0, 1d.2h.10m
  [9 lists not shown]: [too many]
 default:
  user-filters: 736-2, never
  RUS-0: 40218-33, 1m Δ
  easylist: 77645-1892, 1m Δ
  easyprivacy: 43548-26624, 1m Δ
  plowe-0: 3784-1337, 12d.2h.54m
  ublock-badware: 7762-324, 1m Δ
  ublock-filters: 36520-3865, 1m Δ
  ublock-privacy: 996-408, 1m Δ
  ublock-quick-fixes: 245-46, 1m Δ
  ublock-unbreak: 2193-150, 1m Δ
  urlhaus-1: 9010-0, 1m
filterset (user): [array of 560 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 889 ms (selfie)
 maxAssetCacheWait: 465 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  aptekiplus.ru: 4
  yandex.ru: 2
 extended:
  ##.cookie-banner:not(body):not(html)
  ##div.cookie-banner
  ##.cookie__content
  ##.cookie__wrapper
  ##.cookie
  ##+js(set-cookie, header_banner_cookies, true)

```
</details>

**Comment by D4niloMR** [comment]
Add:

`@@||aptekiplus.ru/_nuxt/popup-attention`
