### ISSUE TITLE
9to5google.com: nuisance

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#22103]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://9to5google.com/`

### Category

nuisance

### Description

consent notice appears over the page on first visit.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/2b59c053-c011-4d05-9a62-01a2e48937cf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 117117
 cosmetic: 88326
 scriptlet: 23116
 html: 2028
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 64729-15568, now
  ublock-cookies-easylist: 898-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37097-210, 6m
  ublock-badware: 7766-11, 2m Δ
  ublock-privacy: 992-0, 6m
  ublock-unbreak: 2237-1, 2m Δ
  ublock-quick-fixes: 247-0, 6m
  easylist: 77604-552, 2m Δ
  easyprivacy: 43548-830, now Δ
  urlhaus-1: 9010-0, 6m
  plowe-0: 3781-1, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3599 ms
 maxAssetCacheWait: 88 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 2
  quantserve.com: 1
  scorecardresearch.com: 2
  typekit.net: 1
  videoplayerhub.com: 1
  wp.com: 1
 extended:
  ##.ad-container--leaderboard
  ##.inlinead
  ##ins.adsbygoogle
  ##.ad-container
  ##.ad-disclaimer-container, .inlinead, .ad-container
  ##iframe[name="googlefcPresent"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
This works:

    9to5google.com##.fc-consent-root
    9to5google.com##body:style(overflow: initial !important)

**Comment by mapx-** [comment]
sometimes on such pages the videos are broken

**Comment by gorhill** [comment]
So far I've found only Youtube-based videos and they play fine. I am trying to find other video sources.

**Comment by ABetterWeb** [comment]
@gorhill on mac, firefox, dark mode after consenting => same issue as https://www.reddit.com/r/uBlockOrigin/comments/198to3q/comments_on_sites_dark_theme_unreadable/ , so unbreak-related

**Comment by stephenhawk8054** [comment]
@ABetterWeb If you turn off Firefox Tracking Protection, does the issue occur again?

**Comment by ABetterWeb** [comment]
FF w/ Tracking Protection + AdGuard for Mac => no issue
FF w/ Tracking Protection + uBO (without the cookie-remover scriptlet) => comment visiblity issue (dark mode)
FF without TP + uBO => no such issue

**Comment by stephenhawk8054** [comment]
```adb
@@||cdn.viglink.com/api/$script,domain=9to5google.com
```

is already in unbreak list.

@ABetterWeb So with `cookie-remover` scriptlet, it works for you?

**Comment by ABetterWeb** [comment]
Actually, it looks like it's just jittering. Maybe allowing more google funding choices stuff would help or somehow tinkering with the text font

**Comment by gorhill** [comment]
I think I remember investigating quickly, and something was preventing the element`[data-spotim-module]` from being found, and this is necessary for the proper dark mode to be rendered (code is at `https://9to5google.com/wp-content/themes/ninetofive/dist/js/darkmode.js?ver=21f73f57dc1807676703`).

**Comment by ABetterWeb** [comment]
Maybe we could look at the `redirect-rule` filter - it may be a bit too broad

**Comment by gorhill** [comment]
It's that AdGuard filter that somehow unbreak dark/light them:

    9to5google.com,9to5mac.com,9to5toys.com,dronedj.com,electrek.co#%#AG_onLoad(function(){const a=document.createElement("div");document.documentElement.appendChild(a),setTimeout(()=>{a&&a.remove()},100)});

If I execute the following in the dev console, dark theme is properly toggle when browser preference is set to dark theme:

    (function(){const a=document.createElement("div");document.documentElement.appendChild(a),setTimeout(()=>{a&&a.remove()},100)})()

So essentially adding then removing an `empty div` is what it takes.

**Comment by gorhill** [comment]
@ABetterWeb once you consent, the comments will be rendered fine on subsequent page loads, I think it's a site issue.

**Comment by stephenhawk8054** [comment]
@gorhill I don't see any consents on the page, and the button doesn't work if FF Tracking Protection is turned on

**Comment by stephenhawk8054** [comment]
`rpnt` works indeed

```adb
9to5google.com##+js(trusted-rpnt, script, (function($), '(function(){const a=document.createElement("div");document.documentElement.appendChild(a),setTimeout(()=>{a&&a.remove()},100)})(); (function($)')
```

**Comment by ABetterWeb** [comment]
for the consent thing, make sure you have a EU IP address, and have deleted the relevant cache / cookies

**Comment by gorhill** [comment]
> rpnt works with FF Tracking Protection enabled indeed

Confirm this works all fine.

**Comment by stephenhawk8054** [comment]
I'll replace the exceptions with the `rpnt`. We'll see if it would stable or not.
