### ISSUE TITLE
vider.info: detection

### ISSUE THREAD

**Issue by janjezowski** [uBlockOrigin/uAssets#22101]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vider.info/vid/+f1cmes`

### Category

detection

### Description

The page detects uBlock Origin and makes it impossible to watch videos while using adblock.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 116768
 cosmetic: 52519
 scriptlet: 18977
 html: 2039
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37097-221, now Δ
  ublock-badware: 7766-11, now Δ
  ublock-privacy: 992-0, now Δ
  ublock-unbreak: 2237-1, now Δ
  ublock-quick-fixes: 247-0, now Δ
  easylist: 77604-539, now Δ
  easyprivacy: 43548-875, now Δ
  urlhaus-1: 9010-0, 3h.16m
  plowe-0: 3786-1, 1d.9h.28m
  POL-0: 8587-42, 5m
  POL-2: 1283-12, 1d.2h.37m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 876 ms (selfie)
 maxAssetCacheWait: 415 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  vider.info: 4
  addthis.com: 2
  googletagmanager.com: 2
  vendimob.pl: 3
  vidoomy.com: 1
  webshark.pl: 5
 extended:
  ##.ad-300
  ##[id$="reklamy"]:not(h1):not(h2):not(h3):not(h4):not(h5):not(h6…
```
</details>

**Comment by garry-ut99** [comment]
I confirm : [SCREENSHOOT](https://github.com/uBlockOrigin/uAssets/assets/72945564/5cdebf57-e8e4-48be-8858-56a1e8499f1b), also no anti-adblock with `AdGuard - Ads` list enabled, 
which contains this exception filter: `@@||static.webshark.pl/adserver/*/main_script.js?advertise_check=1`

**Comment by gorhill** [comment]
I get 404 at the provided URL.

**Comment by garry-ut99** [comment]
The video loads fine for me (no 404 error).

**Comment by gorhill** [comment]
I get constant 404 when navigating to `https://vider.info/vid/+f1cmes`, including when trying to load from a `pl` VPN.

**Comment by garry-ut99** [comment]
Well, I've checked several different videos including the one OP posted and they always load fine for me.
But this video hosting is a low cost and low bandwidth thing, and it often lags, many times in the past videos freezed "forever" here, while watching, I wouldn't be surprised if it gives permanent 404 for some users.

**Comment by stephenhawk8054** [comment]
@garry-ut99 Which country are you when accessing the site successfully?

**Comment by mapx-** [comment]
polish ip
