### ISSUE TITLE
leboncoin.fr: breakage

### ISSUE THREAD

**Issue by anisse** [uBlockOrigin/uAssets#22104]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.leboncoin.fr/mes-recherches`

### Category

breakage

### Description

I'm sorry, this page needs an account. Playing with the lists on mobile, I found that the issue is in the "uBlock filters – Cookie Notices" list.

The content that should be on the page isn't. I'll try on desktop to see if I reproduce.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 138138
 cosmetic: 0
 scriptlet: 26899
 html: 2236
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49349-43973, now
  ublock-annoyances: 6575-1728, 6m
  ublock-cookies-easylist: 936-936, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37446-10583, 1m
  ublock-badware: 7760-683, 1m
  ublock-privacy: 992-13, 1m
  ublock-unbreak: 2241-311, 1m
  ublock-quick-fixes: 247-117, 1m
  adguard-mobile: 9065-7583, 1m
  easylist: 77597-33889, 1m
  easyprivacy: 43547-1073, 1m
  urlhaus-1: 9010-0, now
  plowe-0: 3781-1, now
  FRA-0: 26864-7030, 6m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1338 ms (selfie)
 maxAssetCacheWait: 233 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  leboncoin.fr: 1
  aticdn.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  hubvisor.io: 1
  sentry.io: 3
 extended:
  ##+js(set-constant, Didomi, noopFunc)
```
</details>

**Comment by mapx-** [comment]
test

`leboncoin.fr#@#+js(set, Didomi, noopFunc)`

**Comment by anisse** [comment]
I was just about to post that this rule was the issue.

**Comment by anisse** [comment]
It did reproduce on Desktop, but can't anymore. Did you update the rules ?

**Comment by mapx-** [comment]
it's a rule from fanboy-cookiemonster

@ryanbr
