### ISSUE TITLE
free-mp3-download.net: detection

### ISSUE THREAD

**Issue by Christoph-Neumann-1** [uBlockOrigin/uAssets#22100]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://free-mp3-download.net/`

### Category

detection

### Description

Refuses to serve content with ublock enabled. Tested on Android 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 116783
 cosmetic: 35833
 scriptlet: 18815
 html: 2028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37439-457, 9m
  ublock-badware: 7760-11, 9m
  ublock-privacy: 992-1, 9m
  ublock-unbreak: 2242-2, 9m
  ublock-quick-fixes: 234-0, 9m Δ
  adguard-mobile: 9065-132, 9m
  easylist: 77590-16620, 9m
  easyprivacy: 43572-853, 9m
  urlhaus-1: 9010-0, 9m
  plowe-0: 3781-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 524 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> Refuses to serve content with ublock enabled.

meaning you get a detection message or it remains stuck on "downloading" ?

Did you test the site disabling uBO for that page ?

**Comment by ABetterWeb** [comment]
Are you using AdGuard for Android (app / extension), AdAway, AdGuard DNS etc.?
