### ISSUE TITLE
bazar.bg: ads

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#22125]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bazar.bg/obiavi?q=nintendo%20switch&sort=weight`

### Category

ads

### Description

Ads are shown on the bottom.
Was able to hide the ads with these filters:
```
bazar.bg##.last.newsLink.listItemLink
bazar.bg##.listItemLink.newsLink
```
Can remove the empty space after hiding the ads with these filters:
```
bazar.bg##div:nth-of-type(70)
bazar.bg##div:nth-of-type(71)
```
This is the filter to block images from the ad server:
`||cdn4.focus.bg/fakti/*$domain=bazar.bg`

### Other extensions used

none

### Screenshot(s)

<img width="735" alt="Screenshot 2024-01-21 at 18 37 55" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/55ab14c3-df85-42cb-b68b-9384b91f7e0e">

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 116164
 cosmetic: 44788
 scriptlet: 18771
 html: 2031
listset (total-discarded, last-updated):
 added:
  BGR-0: 1022-1, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37127-216, now
  ublock-badware: 7766-11, now Δ
  ublock-privacy: 992-0, now
  ublock-unbreak: 2237-1, now
  ublock-quick-fixes: 243-0, now
  easylist: 77645-554, now
  easyprivacy: 43575-831, now
  urlhaus-1: 9130-0, now
  plowe-0: 3781-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 713 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  adocean.pl: 2
  creativecdn.com: 1
  doubleclick.net: 1
  gemius.pl: 1
  google.com: 7
  googletagmanager.com: 2
  googletagservices.com: 1
 extended:
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by mapx-** [comment]
- add the bulgarian list
- report other issues (for bulgarian sites) here: https://github.com/RealEnder/adblockbg/issues

@RealEnder

**Comment by Dani-1-2** [comment]
> * Enable the regional (bulgarian) list
> 
>     * report other issues (for bulgarian sites) here: https://github.com/RealEnder/adblockbg/issues
> 
> 
> @RealEnder

The list is enabled. Also uBO lists this as the bulgarian list homepage: https://stanev.org/abp/ ?

**Comment by mapx-** [comment]
yes, it's the same dev

**Comment by Dani-1-2** [comment]
@mapx- Why did you close this? has it been resolved?

**Comment by ItsProfessional** [comment]
Whenever it's fixed, it'll be fixed in the bulgarian list. No point of keeping our issue open.

**Comment by Dani-1-2** [comment]
> Whenever it's fixed, it'll be fixed in the bulgarian list. No point of keeping our issue open.

I will create an issue there then.
