### ISSUE TITLE
primeleech.com: nuisance

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#22129]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.primeleech.com/generator/rapidgator`

### Category

nuisance

### Description

scam site. possible malware.
i have other variations/mirrors of this site. if its blockable please let me know!

### Other extensions used

ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/0d24391d-fbfe-4f77-812e-c7fec43ac3c1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 207577
 cosmetic: 149562
 scriptlet: 30981
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28432-30, now
  curben-phishing: 84185-20, now
  easylist-annoyances: 4316-42, now
  easylist-chat: 177-0, now
  easylist-newsletters: 6893-23, now
  easylist-notifications: 2908-87, now
  fanboy-cookiemonster: 49373-3735, now
  fanboy-social: 16108-14, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6560-90, 12m Δ
  ublock-cookies-adguard: 898-898, now
  ublock-cookies-easylist: 898-898, now
 default:
  user-filters: 0-0, never
  TUR-0: 13219-7, now
  easylist: 77673-37, 12m Δ
  easyprivacy: 43551-133, 12m Δ
  plowe-0: 3781-1171, now
  ublock-badware: 7751-142, 12m Δ
  ublock-filters: 36541-187, 12m Δ
  ublock-privacy: 996-9, 12m Δ
  ublock-quick-fixes: 245-52, 12m Δ
  ublock-unbreak: 2193-37, 12m Δ
  urlhaus-1: 9130-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 645 ms (selfie)
 maxAssetCacheWait: 222 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 3
```
</details>

**Comment by ABetterWeb** [comment]
@ryanbr adserver?

**Comment by mapx-** [comment]
> scam site. possible malware.

provide evidence for your claim

**Comment by big-cat-loaf** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/157169

**Comment by gototheskinny** [comment]
> > scam site. possible malware.
> 
> provide evidence for your claim

i did provide in the screenshot. it's obvious for me isn't it for you guys? and reinstalled ubo and i can still access to the this scam site. to prove even more i have to get scammed by these scums and i'm not that stupid. human verification is an OLDD scam type.

**Comment by mapx-** [comment]
already added to out badware list

**Comment by gototheskinny** [comment]
> [AdguardTeam/AdguardFilters#157169](https://github.com/AdguardTeam/AdguardFilters/issues/157169)

i still can access to the site with ag too on ios tho i didn't tried on pc.

**Comment by gototheskinny** [comment]
> already added to out badware list

https://github.com/hagezi/dns-blocklists/issues/409
can you please check the issue above? it's not blocked in their lists and adguard too i dont understand why i still can access to these sites AND just checked today just what i've expected it's a corrupted file so it's a scam for sure STILL.
These are the sites that scams people. i'm sure there are more mirrors out there.
[youdebrid.com](youdebrid.com) [okdebrid.com](okdebrid.com) [https://maxdebrid.com](https://maxdebrid.com) [https://debridlink.com](https://debridlink.com) [https://hotdebrid.com](https://hotdebrid.com)

**Comment by hagezi** [comment]
@gototheskinny The pages are blocked in my lists.
