### ISSUE TITLE
myanimelist.net: breakage

### ISSUE THREAD

**Issue by alan-ford** [uBlockOrigin/uAssets#22123]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://myanimelist.net/`

### Category

breakage

### Description

When the "uBlock filters - Unbreak" filter is active, the text on MyAnimeList cannot be selected.

### Other extensions used

Firefox Relay, I don't care about cookies, Search by Image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 117286
 cosmetic: 50963
 scriptlet: 18771
 html: 2031
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37127-127, 22m
  ublock-badware: 7766-11, 10m Δ
  ublock-privacy: 992-0, 10m Δ
  ublock-unbreak: 2237-1, 10m Δ
  ublock-quick-fixes: 243-0, 23m
  easylist: 77672-629, 10m Δ
  easyprivacy: 43575-858, 26m
  urlhaus-1: 9130-0, 27m
  plowe-0: 3781-1, 27m
  ITA-0: 8323-19, 25m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6300 ms (selfie)
 maxAssetCacheWait: 1370 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  inmobi.com: 1
  sascdn.com: 1
  smartadserver.com: 1
  unblockia.com: 2
 extended:
  ##[src*="/c/img/images/event/"]
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
test after disabling I don't care about cookies
