### ISSUE TITLE
bringmethenews.com: detection

### ISSUE THREAD

**Issue by SkyNetX1** [uBlockOrigin/uAssets#22128]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bringmethenews.com/`

### Category

detection

### Description

Admiral nag present on entire website. Using UBO only on FireFox Mobile.

### Other extensions used

I disables all other extensions and have no custom rules.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240121_140612_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/115195215/0837d5a8-b41b-468d-bdb0-29ef6878f6bb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 148298
 cosmetic: 195383
 scriptlet: 48755
 html: 2239
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81865-6080, 12m
  adguard-spyware-url: 1423-103, 11m
  adguard-social: 22419-1575, 11m
  adguard-cookies: 28432-1634, 11m
  ublock-cookies-adguard: 936-0, 11m
  adguard-popup-overlays: 26796-1692, 11m
  adguard-mobile-app-banners: 4904-1077, 11m
  adguard-other-annoyances: 14105-346, 11m
  adguard-widgets: 2408-36, 11m
  fanboy-thirdparty_social: 68-1, 11m
  easylist-annoyances: 4316-1000, 11m
  easylist-chat: 177-21, 11m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37470-653, 15m
  ublock-badware: 7749-10, 9m Δ
  ublock-privacy: 992-1, 15m
  ublock-unbreak: 2242-3, 9m Δ
  ublock-quick-fixes: 245-0, 9m Δ
  adguard-mobile: 9067-144, 15m
  easylist: 77673-16777, 9m Δ
  easyprivacy: 43575-1003, 15m
  urlhaus-1: 9130-0, 15m
  plowe-0: 3781-1, 15m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1098 ms
 maxAssetCacheWait: 635 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 61
 network:
  bringmethenews.com: 5
  33across.com: 4
  3lift.com: 2
  adnxs.com: 2
  adsafeprotected.com: 1
  adsrvr.org: 2
  advertising.com: 1
  amazon-adsystem.com: 1
  bidswitch.net: 2
  casalemedia.com: 1
  ccgateway.net: 2
  contextweb.com: 2
  d1z2jf7jlzjs58.cloudfront.net: 1
  datadome.co: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  indexww.com: 1
  kargo.com: 1
  liadm.com: 6
  lijit.com: 1
  merequartz.com: 2
  optmnstr.com: 1
  permutive.app: 1
  petametrics.com: 3
  pubmatic.com: 2
  quantserve.com: 1
  rlcdn.com: 2
  rubiconproject.com: 2
  scorecardresearch.com: 1
  yahoo.com: 5
```
</details>

**Comment by SkyNetX1** [comment]
![Screenshot_20240121_140612_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/115195215/0837d5a8-b41b-468d-bdb0-29ef6878f6bb)

**Comment by stephenhawk8054** [comment]
I can reproduce

**Comment by D4niloMR** [comment]
Embedded video is broken `https://bringmethenews.com/minnesota-weather/nws-mid-winter-thaw-looks-to-continue-and-not-hold-back`

**Comment by stephenhawk8054** [comment]
> Embedded video is broken `https://bringmethenews.com/minnesota-weather/nws-mid-winter-thaw-looks-to-continue-and-not-hold-back`

Looks like it's a video slideshow ads, not really directly related to the article

**Comment by D4niloMR** [comment]
Seems not, the video leads to another article in the same site.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/6ea809f5-073b-49da-b5ff-59f41ba10700)

</p>
</details> 

Trying to figure it out but this site lags without uBO...

**Comment by stephenhawk8054** [comment]
Yeah, I mean I saw 2 articles using the same video, although 1 article is different to the video content. This is usually considered video ads by EL. These kinds of videos pull seemingly-related content and collect users' watching information, especially the slideshows format, which is the lowest-effort of these kinds (some other sites use real videos, interviews... related to the articles).

**Comment by D4niloMR** [comment]
Ok, it looks strange without removing the PH though

**Comment by stephenhawk8054** [comment]
Yeah, we should tell EL about the placeholder

@ryanbr

**Comment by SkyNetX1** [comment]
@@||c.amazon-adsystem.com^$domain=bringmethenews.com
@@||player.ex.co/player/$domain=bringmethenews.com
bringmethenews.com#@#.pbs__player
@@||player.ex.co/config$domain=bringmethenews.com
@@||cdn.ex.co/player/$domain=bringmethenews.com
@@||p.channelexco.com/player/$domain=bringmethenews.com

These rules fixes most the content. These rules were not enabled when I tested. The Admiral nag pops up with or without the rules.
