### ISSUE TITLE
1337x.to: detection

### ISSUE THREAD

**Issue by 1265578519** [uBlockOrigin/uAssets#22122]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1337x.to/FitGirl-torrents/1/`

### Category

detection

### Description

您的浏览器版本太低！
请更新您的浏览器后方可正常查看此网站。

**_Your browser version is too old! Please update your browser to view this website properly._**

https://github.com/uBlockOrigin/uAssets/assets/6442439/a76213f8-82e1-4803-adff-735a10ec1581

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 130665
 cosmetic: 55042
 scriptlet: 20358
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  CHN-0: 26125-134, now
  easylist: 77672-27, now
  easyprivacy: 43549-52, now
  plowe-0: 3781-1171, now
  ublock-badware: 7762-136, now
  ublock-filters: 36548-176, now
  ublock-privacy: 996-7, now
  ublock-quick-fixes: 243-52, now
  ublock-unbreak: 2193-33, now
  urlhaus-1: 9130-0, now
filterset (user): [array of 4 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 177 ms (selfie)
 maxAssetCacheWait: 89 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##img[src*="data:image"]
  ##+js(remove-node-text, script, style)
  ##+js(abort-on-stack-trace, document.createElement, _0x)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, afScript)
  ##+js(no-setTimeout-if, adb)
  ##+js(nowebrtc)
  ##+js(abort-on-property-read, AaDetector)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
```
</details>

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/19c0pu3/1337xto_being_bontinuously_blocked_by/

**Comment by 1265578519** [comment]
> https://www.reddit.com/r/uBlockOrigin/comments/19c0pu3/1337xto_being_bontinuously_blocked_by/

你发的链接地址我打不开，不知道什么原因
![image](https://github.com/uBlockOrigin/uAssets/assets/6442439/2d71ab6c-3d29-404c-8281-8046b6569317)


1337x.to 只有禁用这个开关我才能打开，几台电脑都有相同的情况
![image](https://github.com/uBlockOrigin/uAssets/assets/6442439/ae9bbab1-cf02-49ff-8dc1-6894f3ac6f29)

https://github.com/uBlockOrigin/uAssets/assets/6442439/306ef735-b94f-4f6f-8eb4-0ae668103dab

**Comment by mapx-** [comment]
it seems fixed by easylist => click https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=easylist&manual=1

@1265578519 update easylist and test again
Reply using english language (use google translate or deepl.com)

**Comment by 1265578519** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/6442439/628fd341-c760-43c3-984b-cd83a46948ef)
不起作用，没有修复

**Comment by ABetterWeb** [comment]
Could you please test in "My filters"?

```
||1337x.to^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data:,badfilter
||1337x.to^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data: challenges.cloudflare.com
```

@ryanbr

**Comment by ABetterWeb** [comment]
Why did you delete the comment? The filters worked and the screenshot showed cloudflare explicitly asking to unblock `challenges.cloudflare.com`

**Comment by mapx-** [comment]
it was already fixed by EL

**Comment by ABetterWeb** [comment]
yes, I saw, the CDN didn't grab it yet

**Comment by 1265578519** [comment]
他发了什么评论，我怎么看到一直被作者删除？

**Comment by mapx-** [comment]
> Reply using english language (use google translate or deepl.com)

@1265578519 as I said: already fixed, investigate on your end, maybe you are using some other extension or your country is blocking cloudflare

**Comment by ABetterWeb** [comment]
I have a feeling there's a bug with the new update system.

@1265578519 disable EasyList and enable it after - this is to force an update - it worked for me

**Comment by 1265578519** [comment]
> 我有一种感觉，新的更新系统有一个错误。
> 
> 禁用 EasyList 并在之后启用它 - 这是为了强制更新 - 这对我有用

@ABetterWeb
可能是你说的EasyList server CDN cache，我过几个小时在测试，现在我这不起效果
https://github.com/uBlockOrigin/uAssets/assets/6442439/41f6a5d6-3f5a-400c-8a11-3fe9922bd186

**Comment by mapx-** [comment]
clicking the link I provided above will update easylist.
