### ISSUE TITLE
diariodenavarra.es: detection

### ISSUE THREAD

**Issue by AlfonsoML** [uBlockOrigin/uAssets#22127]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.diariodenavarra.es/noticias/opinion/2024/01/20/educando-igualdad-mediocridad-596154-1064.html`

### Category

detection

### Description

The main page works fine, but the sub-pages (news) show a full-page div blocking all the content after 5 seconds.

### Other extensions used

None. I've disabled them to test while writting the report, it still fails

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2024-01-21 184148](https://github.com/uBlockOrigin/uAssets/assets/2482331/2dcd36ef-c1e1-4517-a70d-855d37a1422b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 294416
 cosmetic: 250940
 scriptlet: 49831
 html: 2238
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81865-4308, now
  adguard-mobile: 9067-103, now
  adguard-spyware-url: 1423-103, now
  block-lan: 56-0, now
  curben-phishing: 84185-27, now
  adguard-social: 22419-877, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 49373-3804, now
  fanboy-social: 16108-26, now
  ublock-annoyances: 6514-934, 1h.59m Δ
  adguard-spyware: 88582-28021, now
  adguard-cookies: 28432-64, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37127-530, 1h.59m Δ
  ublock-badware: 7766-11, 1h.59m Δ
  ublock-privacy: 992-0, 1h.59m Δ
  ublock-unbreak: 2237-1, 1h.59m Δ
  easylist: 77672-2439, 1h.59m Δ
  easyprivacy: 43549-966, 1h.59m Δ
  urlhaus-1: 9130-0, 2m
  plowe-0: 3781-1, now
  spa-0: 3797-5, 2m
  spa-1: 5719-162, now
  ublock-quick-fixes: 243-1, 1h.59m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 21 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1029 ms (selfie)
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  diariodenavarra.es: 1
  20m.es: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  privacy-center.org: 1
  sensic.net: 1
  taboola.com: 1
 extended:
  ##.henneoHB
  ##.roba
  ##.sticky_horizontal
  ##.share-options
  ###AdSlot_megabanner
  ##.sticky_roba
  ##+js(no-setTimeout-if, AdBanner, 2000)
```
</details>

**Comment by AlfonsoML** [comment]
Please, reopen this because it's broken.

**Comment by ItsProfessional** [comment]
I have fixed it. Wait about 10 minutes and force an update of your filter lists.
