### ISSUE TITLE
as.com paywall

### ISSUE THREAD

**Issue by skarvin** [uBlockOrigin/uAssets#22130]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
as.com
```

### Description

Paywall still showing 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
We do not fix paywalls.

**Comment by D4niloMR** [comment]
@JobcenterTycoon the cookie banner is fixed on ELC

No embed issue.

`https://as.com/baloncesto/videos/resumen-del-baskonia-vs-morabanc-andorra-de-la-liga-endesa-v/`

**Comment by JobcenterTycoon** [comment]
I get a cookie banner with ELC enabled.

**Comment by skarvin** [comment]
Yes it's not a paywall but a cookie banner

**Comment by JobcenterTycoon** [comment]
The cookie banner is fixed in `uBlock filters – Cookie Notices`
