### ISSUE TITLE
home.novel-gate.com: detection

### ISSUE THREAD

**Issue by ASURA715** [uBlockOrigin/uAssets#22138]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://home.novel-gate.com/novel/theres-my-dad-is-a-legendary-cultivator-2022/chapter-9/`

### Category

detection

### Description

![Screenshot_20240122_195905](https://github.com/uBlockOrigin/uAssets/assets/70307892/5c551c92-036b-4b3d-a420-e9bd9756f43d)

### Other extensions used

![Screenshot_20240122_200251](https://github.com/uBlockOrigin/uAssets/assets/70307892/85fa7fe7-04eb-44af-9496-c90d954c11fc)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 133268
 cosmetic: 164215
 scriptlet: 31227
 html: 2241
listset (total-discarded, last-updated):
 added:
  adguard-social: 22427-1578, now
  adguard-cookies: 28430-1634, now
  ublock-cookies-adguard: 940-0, now
  adguard-popup-overlays: 26803-1694, now
  adguard-mobile-app-banners: 4910-1077, now
  adguard-other-annoyances: 14110-346, now
  adguard-widgets: 2409-37, now
  easylist-annoyances: 4316-1011, now
  easylist-chat: 177-21, now
  fanboy-cookiemonster: 49378-19728, now
  ublock-cookies-easylist: 940-940, now
  easylist-newsletters: 6893-1867, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37477-650, 1h.14m Δ
  ublock-badware: 7754-10, 1h.14m Δ
  ublock-privacy: 992-1, 1h.14m Δ
  ublock-unbreak: 2242-1, 1h.14m Δ
  ublock-quick-fixes: 247-1, 1h.14m Δ
  adguard-mobile: 9066-49, now
  easylist: 77713-16783, 1h.14m Δ
  easyprivacy: 43559-1003, 1h.14m Δ
  urlhaus-1: 9320-0, 1h.14m
  plowe-0: 3781-84, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 611 ms (selfie)
 maxAssetCacheWait: 163 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
  ko-fi.com: 2
  pubfuture-ad.com: 2
```
</details>

**Comment by ASURA715** [comment]
thank you very much

**Comment by JobcenterTycoon** [comment]
It need a few hours until uBlock Origin updates.

You can manually add `novel-gate.com##+js(noeval-if, /chp_?ad/)` into your filters until the public update is avaiable.

**Comment by ASURA715** [comment]
Thank you very much brother
