### ISSUE TITLE
businessinsider.com anti-adblock (Microsoft Edge)

### ISSUE THREAD

**Issue by gparyani** [uBlockOrigin/uAssets#2213]
### URL(s) where the issue occurs

`www.businessinsider.com/programmers-debate-requirements-to-behave-respectfully-ccoc-2018-5`

### Describe the issue

There is an anti-adblock prompt on certain Business Insider URLs. 

### Screenshot(s)

N/A (Obvious)

### Versions

- Browser/version: Microsoft Edge 41.16299.371.0
- uBlock Origin version: 1.16.2 (based on Nano Adblocker 1.0.0.46)

### Settings

- Whatever changes that [Nano Adblocker](https://github.com/NanoAdblocker/NanoCore) made, along with [Nano Defender](https://github.com/jspenguin2017/uBlockProtector)

### Notes

My actual issue is with Nano Defender, but the instructions for filing issues there say that if it's a hard prompt (that it forces you to disable your ad blocker or pay a fee), the issue should be filed here, and to only file an issue there if there is no resolution here.

**Comment by mapx-** [comment]
I see no  anti adb message / prompt - tested in FF / chrome - last uBo dev build.

**Comment by gparyani** [comment]
@mapx- I updated Nano Adblocker to 1.0.0.46 (based on uBlock Origin 1.16.2). I also tried to reproduce this in Chrome and was unable to; this bug is thus specific to Microsoft Edge.

**Comment by uBlock-user** [comment]
FYI, there's no official Edge builds, there are forks.

**Comment by gparyani** [comment]
@uBlock-user Yeah, I know that, in fact I made it clear in my original issue report that I was using Nano Adblocker. The only reason I'm posting here is because I was directed to do so by the author of that port.

**Comment by jspenguin2017** [comment]
> I was directed to do so by the author of that port.

I also said ping me right away if you've been told that the issue could not be reproduced.

**Comment by gparyani** [comment]
@jspenguin2017 You were not listed as a pingable user when I was typing it up; your name would have been just plain text. Anyway, I was about to close this and file another issue at Nano Filters, but you beat me to doing that.

**Comment by jspenguin2017** [comment]
Just write plain text and it'll become a ping when you submit the comment. 
Yes, close this and open in NanoFilters. I can reproduce it, I think it's a problem with the redirect rule.

**Comment by jspenguin2017** [comment]
@gparyani Try this: 
`businessinsider.com##script:inject(abort-current-inline-script.js, document.createElement, setAdblockerCookie)`

**Comment by jspenguin2017** [comment]
@mapx- I updated the instructions to direct all Edge issues to NanoFilters directly.
