### ISSUE TITLE
[nsfw] tsmodelstube.com: ads

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#22135]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tsmodelstube.com/`

### Category

ads

### Description

There are many ad banners and ads on sidebar when scrolling down the main page. There are also ad banners, sidebar ads, and ad when pausing a video on video pages (`https://tsmodelstube.com/videos/casey-calvert-and-kasey-kei-hot-hardcore-sex-tgirl-25480.html`) and ad banners and sidebar ads on model pages (`https://tsmodelstube.com/models/4724/lynn-2-.html`)

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115902
 cosmetic: 46150
 scriptlet: 24681
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6560-34, now
 default:
  user-filters: 47-2, never
  easylist: 77707-13, now
  easyprivacy: 43577-39, now
  plowe-0: 3781-1169, now
  ublock-badware: 7751-135, now
  ublock-filters: 36541-163, now
  ublock-privacy: 996-7, now
  ublock-quick-fixes: 245-52, now
  ublock-unbreak: 2193-33, now
  urlhaus-1: 9130-0, now
filterset (user): [array of 40 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 161 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  getclicky.com: 1
  googletagmanager.com: 1
 extended:
  ##a[href^="https://bongacams10.com/track?"]
```
</details>

**Comment by D4niloMR** [comment]
```adb
||tsmodelstube.com/fun/$image,1p
tsmodelstube.com###playerOverlay
tsmodelstube.com##.spot-regular
tsmodelstube.com##a[href="https://tsmodelstube.com/a/tangels"]
```

@ryanbr
