### ISSUE TITLE
cybertyrant.com: nuisance

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#22146]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cybertyrant.com/`

### Category

nuisance

### Description

This is a link shortener.
It makes you click, wait, search for the continue button, repeat in the next page.
If possible, please remove everything in the page, and leave only the necessary buttons to continue towards the download link.

originator link: `https://fast-dl.pro/embed?download=VXzqosNyoO5q7f7OfJdE5PTXZ`
To get to that link, I started from one of the movies and then clicked the first green button saying "G-direct"

found in this movie DDL site: vegamovies.dad

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 121292
 cosmetic: 120741
 scriptlet: 26880
 html: 2243
listset (total-discarded, last-updated):
 added:
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4316-97, now
  easylist-chat: 177-0, now
  fanboy-cookiemonster: 49378-226, now
  ublock-cookies-easylist: 902-0, now
  easylist-newsletters: 6893-13, now
  easylist-notifications: 2908-4, now
  fanboy-social: 16108-23, now
  ublock-annoyances: 6525-934, now
  spa-0: 3805-3, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37206-128, now
  ublock-badware: 7789-10, now
  ublock-privacy: 992-0, now
  ublock-unbreak: 2237-1, now
  ublock-quick-fixes: 143-0, now
  easylist: 78272-667, now
  easyprivacy: 43560-967, now
  urlhaus-1: 9320-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2497 ms
 maxAssetCacheWait: 6 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  headerbidding.ai: 2
```
</details>

**Comment by BlazeFTL** [comment]
For Filter-2022
4072 Line
