### ISSUE TITLE
travel.vebma.com: detection

### ISSUE THREAD

**Issue by ankarakata** [uBlockOrigin/uAssets#22148]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://travel.vebma.com/`
Shortener URL: `https://wts.pw/7xX0gAYVFK`

### Category

detection

### Description

Redirect website detect ublock origin for 1000 seconds on Iceraven Browser (Android)

### Other extensions used

https://github.com/uBlockOrigin/uAssets/assets/131877079/907355bd-9374-458f-8975-cf56839ec863

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-01-23-11-05-49-787_io github forkmaintainers iceraven](https://github.com/uBlockOrigin/uAssets/assets/131877079/16ca38c7-cdc0-4460-a14e-369df2a3c2b7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 119
filterset (summary):
 network: 117018
 cosmetic: 35866
 scriptlet: 18858
 html: 2036
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37611-391, now Δ
  ublock-badware: 7783-10, now Δ
  ublock-privacy: 992-1, now Δ
  ublock-unbreak: 2242-2, now Δ
  ublock-quick-fixes: 142-0, now Δ
  adguard-mobile: 9066-132, now
  easylist: 77751-16706, now Δ
  easyprivacy: 43560-840, now Δ
  urlhaus-1: 9080-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 689 ms (selfie)
 maxAssetCacheWait: 378 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  dundeesmemo.com: 1
  googlesyndication.com: 2
  histats.com: 1
  pubfuture-ad.com: 2
  trvdp.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by BlazeFTL** [comment]
@ankarakata Give Initial Link

**Comment by ankarakata** [comment]
> @ankarakata Give Initial Link

https://wts.pw/7xX0gAYVFK

**Comment by BlazeFTL** [comment]
Try In My Filters
```
travel.vebma.com##+js(no-fetch-if, ads)
travel.vebma.com##.text-primary.inline-block, button.text-primary:others()
travel.vebma.com##+js(aeld, blur, counter)
travel.vebma.com##+js(nano-sib, /counter|wait/, *, 0.02)
adtival.network##div.box:has(.purple)
