### ISSUE TITLE
sadisflix.biz: ads

### ISSUE THREAD

**Issue by AirOne01** [uBlockOrigin/uAssets#22145]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sadisflix.biz/`

### Category

ads

### Description

Ads for the Telegram of this website (animated GIFs) are showing on top of any movie/show page

### Other extensions used

(Using Firefox)
- FastForward
- TWP
- Buster
- ViolentMonkey
- I still don't care about cookies
- Song id
- Don't track me Google

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/21955960/925dec32-6333-4f7a-a0a7-875bb18b4fb8)
![image](https://github.com/uBlockOrigin/uAssets/assets/21955960/d5b12f2e-404d-4f1e-87f3-05d80a07df59)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115829
 cosmetic: 44908
 scriptlet: 18771
 html: 2035
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37206-144, now
  ublock-badware: 7789-10, now
  ublock-privacy: 992-0, now
  ublock-unbreak: 2237-1, now
  ublock-quick-fixes: 143-0, now
  easylist: 78272-623, now
  easyprivacy: 43560-831, now
  urlhaus-1: 9320-0, 43m
  plowe-0: 3782-1, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1063 ms (selfie)
 maxAssetCacheWait: 741 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  capletstyldia.com: 2
  d2j042cj1421wi.cloudfront.net: 1
  d3eub2e21dc6h0.cloudfront.net: 2
  forfeitsubscribe.com: 1
  googletagmanager.com: 1
  h74v6kerf.com: 2
  premiumvertising.com: 1
  tawk.to: 1
  tehxjoqnqab.com: 1
  wldepmzuwqvmyq.com: 1
 extended:
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(no-window-open-if)
  ##+js(remove-node-text, script, /adblock|popunder/)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by mapx-** [comment]
add

`*.gif$domain=sadisflix.biz,image`

the telegram stuff for sadisflix is self promotion 
@smed79

**Comment by mapx-** [comment]
it seems the gif is gone for now

**Comment by AirOne01** [comment]
> I don't see the [ad banner buttons](https://i.imgur.com/xZBMIFE.png) even if i disable my adblocker.
> 
> A sample page or direct link may help me.

A sample page would be https://sadisflix.fun/watch/arcane.html?key=yu1650qz9sxr but it's already been removed.
