### ISSUE TITLE
dagensnytt.com: detection

### ISSUE THREAD

**Issue by Torsteinws** [uBlockOrigin/uAssets#22149]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dagensnytt.com/har-du-denne-senen-pa-armen-her-er-hva-det-betyr/`

### Category

detection

### Description

The website detects ublock origin and asks the user to disable it in order to see the website content.

### Other extensions used

- Bitwarden
- Dark reader
- YouTube High Definition

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240123_111921_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/47348352/31c136b6-ce03-42af-8699-007174ed8597)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 117006
 cosmetic: 36376
 scriptlet: 18835
 html: 2036
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37556-434, 22m Δ
  ublock-badware: 7783-10, 22m Δ
  ublock-privacy: 992-1, 22m Δ
  ublock-unbreak: 2242-2, 22m Δ
  ublock-quick-fixes: 143-0, 22m Δ
  adguard-mobile: 9067-132, 22m
  easylist: 78272-16614, 22m Δ
  easyprivacy: 43560-882, 22m Δ
  urlhaus-1: 9080-0, 5m
  plowe-0: 3782-1, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 855 ms (selfie)
 maxAssetCacheWait: 91 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  doubleclick.net: 4
  google.com: 7
  googlesyndication.com: 5
  googletagmanager.com: 1
  youtube.com: 2
 extended:
  ##ins.adsbygoogle
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
dagensnytt.com##+js(rmnt, script, doTest)

**Comment by Torsteinws** [comment]
Adding it to My Filters does indeed remove the ad block blocker overlay.
