### ISSUE TITLE
raiplay.it: breakage

### ISSUE THREAD

**Issue by tremoar** [uBlockOrigin/uAssets#22147]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.raiplay.it/
```

### Description

I'm using firefox which allow me to block trackers.
raiplay.it seems have a broken behaviour if it's not able to send a notification to gigya.com tracker during the login process. 
This means that blocking gigya.com trackers by firefox or ublock origin filter will break raiplay.it login at all.
As temporary solution I fixed the issue with these filters but I know you'll have a smarter one.

`www.raiplay.it##+js(set, window.gigya, {})`
`www.raiplay.it##+js(set, window.gigya.socialize, {})`
`www.raiplay.it##+js(set, window.gigya.socialize.notifyLogin, noopFunc)`

To test the issue you have to be located in Italy and it's required an account.
Of course this issue is due to firefox block trackers because there are no filters to block gigya.com in ublock origin in raiplay.it, but maybe there should be to protect users which use other browsers. 

So, I checked the last required flag but this issue can be consider to affect ublock origin if you want add a filter to block gigya.com trackers on raiplay.it or it can be considered a firefox issue (i don't think so because trackers should always be blocked).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 117551
 cosmetic: 51474
 scriptlet: 18771
 html: 2035
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37206-126, now
  ublock-badware: 7789-10, now
  ublock-privacy: 992-0, now
  ublock-unbreak: 2237-0, now
  easylist: 78272-629, now
  easyprivacy: 43560-859, now
  plowe-0: 3782-1, 59m
  ITA-0: 8323-19, 59m
  urlhaus-1: 9320-0, 59m
  ublock-quick-fixes: 143-1, now
filterset (user): [array of 560 redacted]
trustedset:
 added: [array of 10 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 36 redacted]
hostRuleset:
 added: [array of 70 redacted]
urlRuleset:
 added: [array of 29 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 251 ms (selfie)
 maxAssetCacheWait: 98 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  raiplay.it: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  scorecardresearch.com: 1
  smartclip.net: 2
  windows.net: 2
  wt-eu02.net: 2
  wt-safetag.com: 1
 extended:
  ##.ad_zone
  ###AdHeader
  ###AD_Top
  ###homead
  ###ad-lead
```
</details>

**Comment by mapx-** [comment]
I get the breakage only blocking `gigya.com`

`||gigya.com^$script,domain=raiplay.it`

in that case your filters are working fine

Even using strict ETP => raiplay is working fine (logging in included)
