### ISSUE TITLE
epsilondelta.co & ed-sys.net removal

### ISSUE THREAD

**Issue by prasam25** [uBlockOrigin/uAssets#22154]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.epsilondelta.co/
https://www.bigbasket.com/
https://www.healthkart.com/
```

### Description

We operate as a SaaS company specializing in real user site speed monitoring. Our product utilizes two domains, both of which are currently blocked by uBlock filters. It's important to note that we do not track users' privacy data or display ads. The integration of our product and the collection of performance data is authorized by the site owner through a paid subscription model. We kindly request the removal of our two domains from  easyprivacy_trackingservers_general.txt 
||ed-sys.net^
||epsilondelta.co^

### Other extensions used

No extenstions used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1363" alt="Screenshot 2024-01-23 at 3 14 14 PM" src="https://github.com/uBlockOrigin/uAssets/assets/45089785/6b6e3ad0-92af-4ac0-a02a-50bfd1aa62f5">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115596
 cosmetic: 44388
 scriptlet: 20178
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77751-13, 48m
  easyprivacy: 43554-39, 48m
  plowe-0: 3782-1169, 48m
  ublock-badware: 7785-135, 48m
  ublock-filters: 36629-201, 48m
  ublock-privacy: 996-7, 48m
  ublock-quick-fixes: 143-9, 48m
  ublock-unbreak: 2193-32, 48m
  urlhaus-1: 9080-0, 48m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 925 ms
 maxAssetCacheWait: 1 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 56
 network:
  epsilondelta.co: 54
  facebook.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
>  easyprivacy_trackingservers_general

1. This repo is for uBO, not EasyPrivacy.
2. "real user site speed monitoring" -> tracking
