### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by LongtimeSun556** [uBlockOrigin/uAssets#22159]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/collection/tracks`

### Category

ads

### Description

Using without any filters, with an old installation and a new installation of uBlock Origins ads make it through on Chrome on Spotify Web Browser.

When using the following filters:

||akamaized.net/audio/$media,redirect-rule=noop-1s.mp4:10,from=open.spotify.com
||scdn.co/audio/*$media,redirect=noop-1s.mp4:10,domain=open.spotify.com

whenever a round of ads comes around, at least one out of the three ads plays in its entirety, the rest skipped after a second passes.

### Other extensions used

Dark Reader
Save Image as Type

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115549
 cosmetic: 44384
 scriptlet: 20180
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 8-3, never
  easylist: 77698-13, 2m
  easyprivacy: 43584-39, 2m
  plowe-0: 3782-1170, 2m
  ublock-badware: 7785-135, 2m
  ublock-filters: 36626-201, 2m
  ublock-privacy: 996-7, 2m
  ublock-quick-fixes: 142-9, 2m
  ublock-unbreak: 2193-32, 2m
  urlhaus-1: 9055-0, 2m
filterset (user): [array of 7 redacted]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1341 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 53
 network:
  ads-twitter.com: 1
  audio-ak-spotify-com.akamaized.net: 2
  doubleclick.net: 4
  fastly-insights.com: 1
  google-analytics.com: 35
  googleoptimize.com: 1
  googletagmanager.com: 2
  pinimg.com: 1
  scorecardresearch.com: 3
  sentry.io: 2
  trkn.us: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by LongtimeSun556** [comment]
Why was this marked as completed

**Comment by mapx-** [comment]
_unable to reproduce the issue_

**Comment by Yuki2718** [comment]
May possibly worth adding to ALL *.com issues?
