### ISSUE TITLE
photopea.com: detection

### ISSUE THREAD

**Issue by DesperatePea** [uBlockOrigin/uAssets#22158]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.photopea.com/`

### Category

detection

### Description

This site detects adblockers and displays a "please disable your adblock or get a premium account." I would if it wasnt for the fact it still shows this message and displays a blank sidebar even with premium accounts. Opening this to show the laggy ads in an inkognito window is the only way to bypass it afaik atm.

### Other extensions used

"i still dont care about cookies"
"return youtube dislikes
"sponsorblock"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Skjermbilde 2024-01-23 kl  13 44 21](https://github.com/uBlockOrigin/uAssets/assets/73502428/c461a216-c373-428f-8c05-a81d18793f6e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 309188
 cosmetic: 260870
 scriptlet: 52448
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76706-128, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95748-22032, 1m
  RUS-0: 40155-457, 1h.42m Δ
  adguard-cookies: 28445-28445, 7m
  adguard-generic: 81848-892, 1m
  adguard-other-annoyances: 14114-14114, 7m
  adguard-popup-overlays: 26827-26827, 8m
  adguard-social: 22439-1647, 1m
  adguard-spyware: 89699-1274, 1m
  adguard-spyware-url: 1424-5, 1m
  block-lan: 56-0, 1m
  curben-phishing: 84437-21, 1m
  [9 lists not shown]: [too many]
 default:
  user-filters: 37-1, never
  NOR-0: 3864-3, 1m
  easylist: 76774-1852, 1h.42m Δ
  easyprivacy: 43560-26488, 1h.42m Δ
  plowe-0: 3782-1268, 1m
  ublock-badware: 7785-327, 1h.42m Δ
  ublock-filters: 36637-3899, 1h.42m Δ
  ublock-privacy: 996-416, 1h.42m Δ
  ublock-quick-fixes: 147-9, 1h.42m Δ
  ublock-unbreak: 2191-150, 1h.42m Δ
  urlhaus-1: 9055-0, 1m
filterset (user): [array of 37 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1333 ms (selfie)
 maxAssetCacheWait: 493 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ##+js(set-constant, console.clear, noopFunc)
```
</details>

**Comment by Yuki2718** [comment]
You have heavily modified settings. Is this the same if you reset your settings to default (backup settings before doing so) and disable other extensions?

**Comment by Dani-1-2** [comment]
Cannot reproduce as well.

**Comment by DesperatePea** [comment]
I figured it out, it was my extension "i dont care about cookies" that was causing the problem, not ublock itself.
