### ISSUE TITLE
downforeveryoneorjustme.com: ads

### ISSUE THREAD

**Issue by along02** [uBlockOrigin/uAssets#22165]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://downforeveryoneorjustme.com/`

### Category

ads

### Description

There is a banner ad.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1506" alt="Screenshot 2024-01-23 at 2 37 14 PM" src="https://github.com/uBlockOrigin/uAssets/assets/21041802/f877829b-febc-4337-a3c6-e0b873d7b7ac">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 114156
 cosmetic: 45115
 scriptlet: 20186
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77011-13, 2m
  easyprivacy: 43584-39, 2m
  plowe-0: 3782-1170, 2m
  ublock-badware: 7785-135, 2m
  ublock-filters: 36661-201, 2m
  ublock-privacy: 996-6, 2m
  ublock-quick-fixes: 142-9, 2m
  ublock-unbreak: 2192-32, 2m
  urlhaus-1: 9055-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 350 ms
 maxAssetCacheWait: 88 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  buysellads.com: 1
  carbonads.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by Dani-1-2** [comment]
||downforeveryoneorjustme.com/img/asurion-1456x180-jan17.png
This works for me.

**Comment by gorhill** [comment]
Maybe:

    downforeveryoneorjustme.com##[aria-hidden="true"]:has(> a[href*="?utm_source="])

cc @ryanbr

**Comment by Dani-1-2** [comment]
@gorhill Wouldn't it be better to use a network filter to prevent extra network load?

**Comment by Dani-1-2** [comment]
@gorhill

**Comment by gorhill** [comment]
In the end it's just a judgment call when we think that one way is more resilient than another -- time spent on maintaining filter list is also a factor.
