### ISSUE TITLE
foxnews.com, foxbusiness.com: breakage

### ISSUE THREAD

**Issue by 411621** [uBlockOrigin/uAssets#22160]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.foxnews.com
https://www.foxbusiness.com
```

### Description

starting this year more and more news pages don't load the actual article contents. the letter is missing but [randomly] requests for login appear.
Sometimes not, but then comment section is missing and/or vice versa.
News listed@foxnews.com that resides on foxusiness.com and is linked thereto cannot post comments on latter and produces error.
only a separate access attempt to foxusiness.com will allow comment posting.

### Other extensions used

pageMaker
single file
sticky notes
stop auto reload
tab session manager
email ondeck temporary email
user agent switcher and manager
view image
visited color picker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29167457/44463f4c-b287-4b93-8cdc-78c62323ea56)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 107
filterset (summary): 
  network: 303026
  cosmetic: 196072
  scriptlet: 50990
  html: 2246
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/14.txt: 76720-76720, 50m
    https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 49m
    https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95748-95748, 49m
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 76-0, 50m
    adguard-generic: 81853-7107, 50m
    adguard-mobile: 9077-171, 50m
    adguard-social: 22438-1576, 50m
    fanboy-thirdparty_social: 68-1, 50m
    fanboy-cookiemonster: 49395-19716, 50m
    fanboy-social: 16108-11635, 50m
    ublock-annoyances: 6739-944, 50m
    dpollock-0: 11627-467, 50m
    adguard-spyware-url: 1424-103, 50m
    block-lan: 56-0, 50m
    curben-phishing: 84437-29, 50m
    ublock-quick-fixes: 148-0, 50m
    adguard-spyware: 89697-26990, 50m
    adguard-cookies: 28448-1630, 50m
    adguard-popup-overlays: 26835-1636, 50m
    adguard-mobile-app-banners: 4912-1077, 50m
    [8 lists not shown]: [too many]
  default: 
    user-filters: 45-2, never
    ublock-filters: 38540-721, 50m
    ublock-badware: 7794-10, 50m
    ublock-privacy: 1053-77, 50m
    ublock-unbreak: 2234-3, 50m
    easylist: 76773-16933, 50m
    easyprivacy: 43562-1070, 50m
    urlhaus-1: 9055-0, 50m
    plowe-0: 3782-1, 50m
filterset (user): [array of 45 redacted]
trustedset: 
  added: [array of 194 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 870 ms (selfie)
  maxAssetCacheWait: 554 ms
```
</details>

**Comment by gwarser** [comment]
Does it happen with default config, without your custom filter lists?

**Comment by Dani-1-2** [comment]
Articles load properly for me.

**Comment by jsegaert** [comment]
I confirm this is also an issue for me; it won't let me past the 'Enter email' screen to show the actual content of any articles on foxnews.com

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details? I accessed `https://www.foxnews.com/` already, what should I do next? Which exact article should I click next?

**Comment by jsegaert** [comment]
The main page works fine, but specific articles have the issue, e.g.

https://www.foxnews.com/entertainment/dana-carveys-son-dexs-official-cause-of-death-determined

In case it matters:

- Issue happens both on Windows 10 & Android, both are using the Firefox browser. 
- I have all other extensions disabled (Privacy Badger)
- I'm in the USA
- Default set-up.  I have some custom blocked elements for www.tvguide.com

**Comment by stephenhawk8054** [comment]
@jsegaert Can you test these filters?

```adb
foxnews.com##+js(set, Taplytics, {})
foxnews.com##+js(set, Taplytics.featureFlagEnabled, noopFunc)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by jsegaert** [comment]
Woohoo!  Those filters resolve the issue for me.  😄

**Comment by stephenhawk8054** [comment]
It's CNAME issue so only Firefox is affected.

---

Anyone knows which links of `https://www.foxbusiness.com` have the same issue? I tried to find one to see if it can have the same solution or not but can't find any.

**Comment by jsegaert** [comment]
So far, I haven't been able to reproduce this issue on any `www.foxbusiness.com` sites; both the article contents & comment sections seem to load fine.

**Comment by jsegaert** [comment]
I want to take the time to thank you again for addressing this issue so quickly!

**Comment by chaynes112** [comment]
I am experiencing this issue on foxnews.com even after adding the two recommended filters.
