### ISSUE TITLE
Site functionality breaks after cyanlabs.net: nuisance #20190 

### ISSUE THREAD

**Issue by Fma965** [uBlockOrigin/uAssets#22161]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://cyanlabs.net/tutorials/
https://cyanlabs.net/fhub/sync3/apim-asbuilt-decoder/?filename=1705931182.xml
```

### Description

I am the owner of this site and if you want to block this that's fine, but i have to point out that you break functionality,

The tabs on `https://cyanlabs.net/fhub/sync3/apim-asbuilt-decoder/?filename=1705931182.xml` do not work, note this link will expire shortly due to it be a user submitted xml file.

The filter on the left does not work on `https://cyanlabs.net/tutorials/` 

many other things are likely broken since it appear your brute force way to resolve my "nuisance" ads is to terminate jQuery, what a terrible idea that is.

This is due to 20190
`##+js(abort-current-script, jQuery, adsbygoogle)`

![image](https://github.com/uBlockOrigin/uAssets/assets/1707290/1f1a85ed-f36d-404c-a305-f8eef46ef5b6)

### Other extensions used

None, test enviroment.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/1707290/57c3c983-4c5e-4265-811f-db10144c2c3d)
![image](https://github.com/uBlockOrigin/uAssets/assets/1707290/9ab5e13a-f030-4a16-b34a-ade24263bcdc)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 279730
 cosmetic: 118725
 scriptlet: 26871
 html: 2248
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 88069-1876, 1h
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2553-1, 22h.35m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 46240-1870, 22h.34m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 217-0, 22h.35m
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/antimalware.txt: 47258-1262, 22h.34m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, 15d.4h.1m
  block-lan: 56-0, 15d.4h.1m
  easylist-annoyances: 4313-97, 6d.1h.50m
  easylist-chat: 177-0, 6d.1h.51m
  fanboy-cookiemonster: 49314-258, 6d.1h.50m
  ublock-cookies-easylist: 892-0, 6d.1h.50m
  easylist-newsletters: 6885-13, 6d.1h.50m
  [3 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37234-234, 3h Δ
  ublock-badware: 7794-10, 3h Δ
  ublock-privacy: 988-49, 3h Δ
  ublock-unbreak: 2236-1, 3h Δ
  ublock-quick-fixes: 147-0, 3h Δ
  easylist: 76773-12886, 3h Δ
  easyprivacy: 43561-6229, 3h Δ
  urlhaus-1: 9320-0, 22h.34m
  plowe-0: 3781-1, 2d.3h.25m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 516 ms (selfie)
 maxAssetCacheWait: 178 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cyanlabs.net: 2
  googletagmanager.com: 1
 extended:
  ##[title="Back to Top"]
  ##+js(abort-current-script, jQuery, adsbygoogle)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fd9c3fcf7a85a538d5817b9fd15ccb7db8dc7f04

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/commit/38fa36fffedec317f09ef448e414dcd853f4f875
