### ISSUE TITLE
respawnfirst.com: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#22166]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://respawnfirst.com/life-is-strange-true-colors-chromatic-aberration-fix/`

### Category

ads

### Description

leftovers

### Other extensions used

violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock, flag cookies,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenasfasdgfshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/7f54ffe3-904f-41e8-b2c3-77799079c1f9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 137510
 cosmetic: 150339
 scriptlet: 31031
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/fake.txt: 15504-0, now
  adguard-cookies: 28463-30, now
  easylist-annoyances: 4319-42, now
  easylist-chat: 179-0, now
  easylist-newsletters: 6893-23, now
  easylist-notifications: 2908-87, now
  fanboy-cookiemonster: 49395-3736, now
  fanboy-social: 16108-15, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6582-90, now
  ublock-cookies-easylist: 910-910, now
 default:
  user-filters: 0-0, never
  TUR-0: 13218-7, now
  easylist: 77002-36, now
  easyprivacy: 43561-133, now
  plowe-0: 3782-1172, now
  ublock-badware: 7790-135, now
  ublock-filters: 36667-229, now
  ublock-privacy: 992-8, now
  ublock-quick-fixes: 150-5, now
  ublock-unbreak: 2192-37, now
  urlhaus-1: 9055-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 240 ms (selfie)
 maxAssetCacheWait: 153 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  wp.com: 1
 extended:
  ##.td-social-icon-wrap
  ##.td-icon-facebook
  ##.td-icon-instagram
  ##.td-icon-twitter
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
Suggested filter:

    respawnfirst.com##.code-block

cc @ryanbr
