### ISSUE TITLE
Tabs being closed automatically

### ISSUE THREAD

**Issue by peimansh** [uBlockOrigin/uAssets#22179]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://linkdoni.soft98.ir/link-27804.html
```

### Description

When opening the above URL from the parent website: soft98.ir the new opened tab automatically closes.
Opening the URL directly in a new tab results in a blank unresponsive tab. This applies to all the links from the top section (News section) of the home page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 115999
 cosmetic: 45102
 scriptlet: 20180
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 79037-13, 15m Δ
  easyprivacy: 43562-39, 15m Δ
  plowe-0: 3781-1169, 5d.3h.21m
  ublock-badware: 7791-136, 15m Δ
  ublock-filters: 36645-207, 15m Δ
  ublock-privacy: 992-6, 15m Δ
  ublock-quick-fixes: 134-5, 15m Δ
  ublock-unbreak: 2192-32, 15m Δ
  urlhaus-1: 8900-0, 9h.48m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 701 ms (selfie)
 maxAssetCacheWait: 325 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  soft98.ir: 3
  googletagmanager.com: 3
  kaprila.com: 3
 extended:
  ##+js(addEventListener-defuser, click, [native code])
  ##+js(close-window, /link-)

```
</details>

**Comment by mapx-** [comment]
duplicate
go to https://github.com/uBlockOrigin/uAssets/issues/14480
