### ISSUE TITLE
qwant.com: detection

### ISSUE THREAD

**Issue by Bceez** [uBlockOrigin/uAssets#22175]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.qwant.com/?q=Efteling&t=web`

### Category

detection

### Description

The site detects an adblocker when visiting it

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 117254
 cosmetic: 36582
 scriptlet: 18853
 html: 2043
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37595-358, now
  ublock-badware: 7789-10, now
  ublock-privacy: 988-1, now
  ublock-unbreak: 2244-2, now
  ublock-quick-fixes: 132-0, now
  adguard-mobile: 9079-132, now
  easylist: 78882-16701, now
  easyprivacy: 43562-869, now
  urlhaus-1: 8900-0, never
  plowe-0: 3783-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7087 ms
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  qwant.com: 9
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by JobcenterTycoon** [comment]
I can reproduce with a german IP. Hotfix:

```
qwant.com#@#.result__ext:has([data-testid="adResult"])
qwant.com##.result__ext:has([data-testid="adResult"]):style(visibility: hidden !important; max-height: 1px !important;)
```

**Comment by JobcenterTycoon** [comment]
@Yuki2718 Adguard ping

**Comment by johnwick1** [comment]
guys, qwant.com is still blocking ubo at the moment, any fix ?

**Comment by JobcenterTycoon** [comment]
Works fine for me.

**Comment by johnwick1** [comment]
i did some tests again today with this time edge and ubo instead of firefox, i did some simple searches no popup, but when i'm making some research like "cars" or "watches" anything related to business/commercial i do have the popup from qwant blocking the page.

anyone tested too ?

**Comment by johnwick1** [comment]
Hello guys,

Could you please see again ? new popup asking to disable ublock, can't use the website.

**Comment by mapx-** [comment]
test

```
@@||qwant.com/apm/intake/v2/rum/events$xhr,1p
@@||qwant.com/action/$ping,1p
```

**Comment by johnwick1** [comment]
> test
> 
> ```
> @@||qwant.com/apm/intake/v2/rum/events$xhr,1p
> @@||qwant.com/action/$ping,1p
> ```

not working

**Comment by JobcenterTycoon** [comment]
Works for me.

**Comment by johnwick1** [comment]
it works temporarily then after few researches you got the popup

**Comment by goblinsta** [comment]
Hi, any solution to this? Issues still persisting
