### ISSUE TITLE
tubitv.com: ads

### ISSUE THREAD

**Issue by BaronSolace** [uBlockOrigin/uAssets#22171]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tubitv.com/movies/100013787/nefarious?autoplay=true`

### Category

ads

### Description

Randomly started getting commercials the other day.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115534
 cosmetic: 45093
 scriptlet: 20200
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 78564-13, 18m
  easyprivacy: 43562-39, 18m
  plowe-0: 3782-1170, 18m
  ublock-badware: 7790-135, 18m
  ublock-filters: 36663-204, 18m
  ublock-privacy: 992-6, 18m
  ublock-quick-fixes: 132-5, 18m
  ublock-unbreak: 2192-32, 18m
  urlhaus-1: 8900-0, 18m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 584 ms (selfie)
 maxAssetCacheWait: 147 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 137
 network:
  tubitv.com: 1
  doubleclick.net: 1
  extremereach.io: 4
  google.com: 3
  googletagmanager.com: 1
  hrzn-nxt.com: 1
  imrworldwide.com: 2
  ispot.tv: 1
  sentry.io: 2
  tubi.io: 120
  tubi.video: 1
```
</details>

**Comment by stephenhawk8054** [comment]
You mean video ads? At which point did you see the ads, beginning, middle or the end of the video?

**Comment by BaronSolace** [comment]
Throughout the whole thing random ad breaks , on every video on the site, it started happening yesterday, they are commercial breaks,  normally ubo would just do alike a split second skip, but now full commercials just play

**Comment by stephenhawk8054** [comment]
So you mean WHILE playing the videos, or in the MIDDLE of the videos right? Not at beginning or at the end?

**Comment by BaronSolace** [comment]
while watching yes

**Comment by poemathesonking** [comment]
I have never not known ubo to not block ads on tubi.tv until last night. It doesn't happen all the time but some ads are starting to show during playback. Here is the specific video that prompted this post:  [](https://tubitv.com/movies/100014969/bronze-age)

**Comment by stephenhawk8054** [comment]
Already fixed: https://github.com/uBlockOrigin/uAssets/commit/baa9f6a061346effca42ed49b8c12b4a3437e2fe

Duplicate: https://github.com/uBlockOrigin/uAssets/issues/21414
