### ISSUE TITLE
vrcmods.com: detection

### ISSUE THREAD

**Issue by McDudeMan** [uBlockOrigin/uAssets#22178]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vrcmods.com/download/6706`

### Category

detection

### Description

detects that an ad blocker is used and displays a banner insisting you turn it off.

### Other extensions used

none that affect the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/157627778/b8978bb9-5164-438a-86a0-6a614aa32b06)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 122
filterset (summary):
 network: 115916
 cosmetic: 45106
 scriptlet: 20180
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  easylist: 79037-13, now Δ
  easyprivacy: 43562-39, now Δ
  plowe-0: 3783-1171, now
  ublock-badware: 7791-136, now Δ
  ublock-filters: 36645-207, now Δ
  ublock-privacy: 992-6, now Δ
  ublock-quick-fixes: 134-5, now Δ
  ublock-unbreak: 2192-32, now Δ
  urlhaus-1: 8815-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 346 ms (selfie)
 maxAssetCacheWait: 195 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 7
 network:
  ad.plus: 1
  d23d7sc86jmil5.cloudfront.net: 1
  googletagmanager.com: 3
  pub.network: 2
 extended:
  ##[data-freestar-ad]
  ##+js(adjust-setInterval, timeLeft)
  ##+js(no-setTimeout-if, height)
  ##+js(no-setInterval-if, height)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Dani-1-2** [comment]
No such issue for me.

**Comment by ItsProfessional** [comment]
> none that affect the page

List them anyway.
