### ISSUE TITLE
hole-io.com: ads

### ISSUE THREAD

**Issue by Cyberuben** [uBlockOrigin/uAssets#22173]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hole-io.com/`

### Category

ads

### Description

The following element still remains after ad-blocking, this wasn't an issue before:

```html
<div id="aip-sidebarads" style="background-color: rgb(0, 0, 0); position: absolute; top: 0px; bottom: 0px; right: 0px; display: block; width: 300px; max-width: 300px;"><div id="hole-io-com_300x250_2" aip-sidabarads-rendered="true" style="display: block; margin: 10px 0px;"></div><div id="hole-io-com_300x600_2" aip-sidabarads-rendered="true" style="display: block; margin: 10px 0px;"></div></div>
```

It also shows the following script:

```html
<script>
		window.HasAdBlock = false;
		window.adBlockFunction = function(){
			window.HasAdBlock = true;
		}
	</script>
<script async="" src="//api.adinplay.com/libs/aiptag/pub/TPZ/hole-io.com/tag.min.js" onerror="adBlockFunction();"></script>
```

Previously, the game would work in full-screen and the sidebar wouldn't be loaded / left over.

Opening devtools, removing said elements, then closing devtools again reinstates the elements, so I'm quite sure they detect these changes.

### Other extensions used

none (happens in incognito too, where only uBlock is enabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2560" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1823121/96d98933-d1b8-489c-a990-7cbd5bd5f282">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115535
 cosmetic: 45094
 scriptlet: 20200
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 78564-13, 50m Δ
  easyprivacy: 43562-39, 50m Δ
  plowe-0: 3783-1171, now
  ublock-badware: 7790-135, 50m Δ
  ublock-filters: 36664-204, 50m Δ
  ublock-privacy: 992-6, 50m Δ
  ublock-quick-fixes: 132-5, 50m Δ
  ublock-unbreak: 2193-32, 50m Δ
  urlhaus-1: 8900-0, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1832 ms (selfie)
 maxAssetCacheWait: 377 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 172
 network:
  hole-io.com: 1
  3lift.com: 5
  4dex.io: 1
  adnxs.com: 13
  bidswitch.net: 13
  btloader.com: 1
  casalemedia.com: 12
  cpmstar.com: 4
  doubleclick.net: 1
  gameads.io: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  indexww.com: 1
  onetag-sys.com: 13
  openx.net: 17
  pubmatic.com: 13
  rubiconproject.com: 13
  script.ac: 1
  sharethrough.com: 12
  sonobi.com: 12
  the-ozone-project.com: 12
  unrulymedia.com: 12
  yellowblue.io: 12
```
</details>

**Comment by D4niloMR** [comment]
Test:

```adb
hole-io.com###aip-sidebarads
hole-io.com##.webgl-content:style(width: 100% !important;)
```

**Comment by Cyberuben** [comment]
Works!
