### ISSUE TITLE
thesun.co.uk: ads

### ISSUE THREAD

**Issue by Columbo1867** [uBlockOrigin/uAssets#22185]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.thesun.co.uk/
https://www.thesun.co.uk/news/17691645/what-wind-speed-cancels-flights-trains/
```

### Description

Ad banners throughout the website

### Other extensions used

N/A

### Screenshot(s)

<details><summary>Screenshot(s)</summary>

![ads2](https://github.com/uBlockOrigin/uAssets/assets/67225952/36d04d0b-196d-47af-aca4-9d8a38f0dabf)
![Ads](https://github.com/uBlockOrigin/uAssets/assets/67225952/9ea4a125-766a-48bc-90cd-1b07461659a1)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 103211
 cosmetic: 84748
 scriptlet: 37616
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
 added:
  https://small.oisd.nl/: 43535-0, 31m
  adguard-generic: 81855-4294, 31m
 default:
  user-filters: 1-0, never
  easylist: 79061-26994, 1h.12m Δ
  ublock-badware: 7791-332, 1h.12m Δ
  ublock-filters: 36647-3490, 1h.12m Δ
  ublock-privacy: 992-14, 1h.12m Δ
  ublock-quick-fixes: 129-6, 1h.12m Δ
  ublock-unbreak: 2192-81, 1h.12m Δ
  urlhaus-1: 8815-0, 5h.7m
filterset (user): [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 417 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 22
 network:
  thesun.co.uk: 7
  ads-twitter.com: 1
  brightcove.com: 5
  criteo.net: 3
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  newscgp.com: 1
  parsely.com: 1
  quantserve.com: 1
 extended:
  ##.advert-wrapper
  ##.dfp-ad
  ##.widget_thesun_dfp_ad_widget
  ##.dfp-ad-container
  ##.nuk-ad-placeholder
  ##.vjs-ima3-ad-container
  ##.billboard
  ##.customiser-v2-layout-1-billboard
  ##.customiser-v2-layout-three-native-ad-container
  ##div[id^="customiser"] > div.sun-grid-container > div.new-block…

```
</details>

**Comment by gorhill** [comment]
Unable to reproduce when using default settings/lists.

Which exact Chromium-based browser is this?

**Comment by Daxy7** [comment]
i can reproduce:
https://github.com/uBlockOrigin/uAssets/assets/91396482/9155f723-c4cf-4089-ba52-c082e5c7945f

clicking the image goes to blocked `||paid.outbrain.com^$document`

`advert-wrapper, dfp-ad` etc are already blocked

one of the urls
```
<img referrerpolicy="unsafe-url" src="/wp-content/uploads/2024/01/eKmNyXL2sl-mVYey-yack-quark-opinion-4f5b5e-march.png">
```

**Comment by gorhill** [comment]
So this works?

    /^https://www.thesun.co.uk/[0-9a-z]{32}\.js$/$script

**Comment by Daxy7** [comment]
lol chatgpt spat this out when i trialed. still sep 2021 data i presume
`^https?://thesun\.co\.uk/.*[0-9a-f]{32}\.js$`

> So this works?

yes, it works fine. was testing this but will lead to unexpected breakage
```
||www.thesun.co.uk/*.js$script
@@||www.thesun.co.uk/assets/client/*$script
@@||www.thesun.co.uk/assets/*$script
@@||www.thesun.co.uk/sw-update.js$script
```

**Comment by Columbo1867** [comment]
Thank you both of you!
