### ISSUE TITLE
accounts.google.com: breakage

### ISSUE THREAD

**Issue by jajceglava** [uBlockOrigin/uAssets#22184]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://accounts.google.com/CookieMismatch`

### Category

breakage

### Description

frequently come to a page that says "We've detected a problem with your cookie settings." that cannot be resolved by changing the cookie settings for the website independently. Only works once this extension is disabled. This prevents secure sign-in on multiple websites

### Other extensions used

Privacy Badger (website still breaks when privacy badger is turned off)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115929
 cosmetic: 45108
 scriptlet: 18765
 html: 2042
listset (total-discarded, last-updated):
 default:
  user-filters: 8-2, never
  ublock-filters: 37227-112, 1h.28m
  ublock-badware: 7795-10, 1h.28m
  ublock-privacy: 988-0, 1h.28m
  ublock-unbreak: 2238-1, 1h.28m
  ublock-quick-fixes: 129-0, 1h.28m
  easylist: 79061-629, 1h.28m
  easyprivacy: 43562-860, 1h.28m
  urlhaus-1: 8815-0, 1h.28m
  plowe-0: 3783-1, 1h.28m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 19 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2465 ms (selfie)
 maxAssetCacheWait: 1815 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  google.com: 6
```
</details>

**Comment by Yuki2718** [comment]
> This prevents secure sign-in on multiple websites

So this happens when you try to login on third-party sites? Please describe steps to reproduce.
