### ISSUE TITLE
deezer.com: ads / breakage / detection

### ISSUE THREAD

**Issue by nappfun** [uBlockOrigin/uAssets#22189]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deezer.com/fr/profile/29206981/loved`

### Category

breakage

### Description

Les publicités sont de nouveaux audible depuis le 21 janvier plus au moins, au même rythme que si ublockorigin n'existait pas...
Deezer ne le détecte pas, mais ça ne fonctionne plus non plus 

[translation: The advertisements have been audible again since January 21.]

### Other extensions used

/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 155730
 cosmetic: 99058
 scriptlet: 37882
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81855-677, now
  adguard-mobile: 9081-49, now
 default:
  user-filters: 1-0, never
  FRA-0: 26969-40, now
  easylist: 79607-1893, now
  easyprivacy: 43562-381, now
  plowe-0: 3783-1268, now
  ublock-badware: 7791-336, now
  ublock-filters: 36657-3553, now
  ublock-privacy: 992-6, now
  ublock-quick-fixes: 128-6, now
  ublock-unbreak: 2192-103, now
  urlhaus-1: 8745-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 297 ms (selfie)
 maxAssetCacheWait: 214 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 no-cosmetic-filtering: true
 no-popups: true
 network:
  braze.com: 2
  googletagmanager.com: 1
  hubvisor.io: 2
  sentry.io: 1
 extended:
  ##.css-tzddi9
  ##+js(set-constant, smartLoaded, true)
  ##+js(no-setTimeout-if, Ads)
```
</details>

**Comment by gorhill** [comment]
Can you provide exact details about how to reproduce? It will save time if we know exactly what to do, otherwise I don't think anybody is going to take this one without knowing for sure how to reproduce at will in the least time possible.

**Comment by nappfun** [comment]
Bonjour,

J'ouvre simplement google chrome sous windows 11 et lance mes coups de
coeurs ou une playlist sur deezer.com/fr
La musique est à nouveau bien présente, de façon aléatoire comme d'habitude
avec deezer, mais généralement après la 1ère chanson et toutes les 3 ou 5
chansons...
Plus rien ne bloque les publicités sonores.
Je ne pourrais en dire plus

Le ven. 26 janv. 2024 à 02:38, Raymond Hill ***@***.***> a
écrit :

**Comment by nappfun** [comment]
Depuis hier, de façon aléatoire, les publicités sonores sont à nouveau audibles. Toutes ne sont plus bloquée. Après un certain moment, le visuel en bas de page marque "publicité" laissant penser qu'il y'en avait effectivement une, on ne l'entend pas, mais tout se bloque. Ca reste bloqué sur "publicité" et la musique ne continue plus.
Obliger de rafraichir la page pour recommencer la lecture...

Deezer a probablement encore légérement modifié son script :/

**Comment by bergerst** [comment]
In this case, ads were enabled on the Deezer side again for some European users, I think.

1 year ago they did the same thing and then it fixed itself after a few weeks: https://github.com/uBlockOrigin/uAssets/issues/13571#issuecomment-1437328893

Any custom rules in that old issue only break the player. I've tested this rule and the Javascript throws an error that the noopmp3-0.5s response does not have certain headers:
```
||cmodmedia*.live.streamtheworld.com/media/appnexus-audio*$media,redirect=noopmp3-0.5s,domain=deezer.com
||redirector.gvt1.com/videoplayback/*/itag/*/source/dclk_video_ads/*$media,redirect=noopmp3-0.5s,domain=deezer.com
```

The first ones are ads for playlists/artists, the second one are ads for other companies.

I can provide more details if needed, but I don't know enough about the inner workings of uBlock Origin to find a solution.

**Comment by stephenhawk8054** [comment]
I think we can only investigate with the exact accounts that have ads.

**Comment by bergerst** [comment]
It might be reproducible by setting https://www.deezer.com/account/country_selector to the affected countries, in this case at least France and Austria.

The main problem with debugging is that the pattern of when ads are played seems random. Sometimes it happens after 5 titles, sometimes after 3 hours of playback.

**Comment by ItsProfessional** [comment]
@bergerst None of us is able to reproduce ads on the site. As your words say,
> In this case, ads were enabled on the Deezer side again for some European users, I think.

It might be only applied to a fraction of the accounts on the site. Perhaps we'll be able to reproduce with such an account. Are you willing to share your credentials?

**Comment by Inhama** [comment]
![image_2024-02-22_122651751](https://github.com/uBlockOrigin/uAssets/assets/114201338/c58643f9-62ab-40e7-a2a4-58119372705f)

In Canada:
Same issue but Advertisement would just stop playback after 6 songs on Flow mode, unable to skip the advert, unable to play next song. Just silence, have to reload page.

**Comment by nappfun** [comment]
I still have this problem reported. More and more frequently

**Comment by nappfun** [comment]
Hello,
Since yesterday, on the web application (chrome & edge), it is no longer possible to launch music: this is blocked directly by an advertisement which makes the use of deezer impossible. Is there a possibility of achieving something? Or am I the only one in this situation? THANKS
------
Depuis hier, sur l'application web (chrome & edge), plus aucun lancement de musique n'est réalisable maintenant: cela est bloqué directement par une publicité qui rend l'utilisation de deezer impossible. Y'a t il une possibilité de réaliser quelque chose ou suis je le seul dans ce cas? merci

**Comment by doctorsketch** [comment]
I have audio ads playing too. Country set to United Kingdom. Updated my uBlockOrigin and made no difference.

Free tier Deezer account on this playlist: https://www.deezer.com/en/playlist/1996494362

**Comment by nappfun** [comment]
En passant d'un compte à un autre, le soucis est généralisé... Il semblerait qu'il y'ait des formats de publicités plus agressive qui ne sont pas supportée par ublock et bloque le lecteur web obligeant de rafraichir la page.
Le problème: elles sont de plus en plus nombreuses dans ce cas et souvent au tout début... rendant l'utilisation de deezer impossible avec ublock 
----------------------------------------
When switching from one account to another, the problem is generalized... It seems that there are more aggressive advertising formats which are not supported by ublock and block the web reader forcing the page to be refreshed.
The problem: there are more and more of them in this case and often at the very beginning... making the use of deezer impossible with ublock

**Comment by Pear-Tea** [comment]
I also have a problem with ads on Deezer. In my case, the ads are not filtered at all.

Deezer makes an initial request to retrieve the URL of the ad audio and other information about the ad. This request is made when the page is loaded and then regularly to load new ads.
`https://www.deezer.com/ajax/gw-light.php?method=deezer.getAudiobreak&input=3&api_version=1.0&api_token=[APITOKEN]&cid=[CID]`

A second request is then made to retrieve the audio from the advert. The URL used is the one retrieved during the previous request.
`https://cdn.tabmo.io/hawk.tabmo.io/organizations/f42c2087-8482-4af0-9099-e05519206007/creative/bac19367-ed3d-486c-be86-33f04d013f9d.mp3`

I've tried blocking the domain name `tabmo.io` but when I do that the player remains blocked so there's nothing to do but reload the page.

I specify that I'm on Windows 11 and that I'm using Firefox 128.0.

**Comment by stephenhawk8054** [comment]
@Pear-Tea Which country are you when accessing the site?

**Comment by Pear-Tea** [comment]
@stephenhawk8054 I'm in France

**Comment by stephenhawk8054** [comment]
@Pear-Tea Can you test this filter?

```adb
deezer.com##+js(json-prune-fetch-response, results, , propsToMatch, deezer.getAudiobreak)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Pear-Tea** [comment]
@stephenhawk8054 Ok, it seems to work, thanks for the resolution! I'll get back to you if I have any more problems.

**Comment by doctorsketch** [comment]
> @Pear-Tea Can you test this filter?
> 
> ```
> deezer.com##+js(json-prune-fetch-response, results, , propsToMatch, deezer.getAudiobreak)
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Can confirm this works. Big thanks @stephenhawk8054

**Comment by nappfun** [comment]
Bonjour,

Depuis hier, la publicité vidéo est apparue ses les plateformes web de Deezer... rendant le démarrage de la lecture de titres impossible: il se met en continu à charger la publicité...
Y'a t il déjç un moyen de trouver une issue pour bloquer les publicités vidéos qui arrivent au début et au bout de 2 ou 3 titres, en remplacement de la publicité audio

merci

**Comment by Muumuufelin** [comment]
Hello.

There's now a message saying "Ad-blocker detected. Please disable your ad-blocker to use Deezer" when you try to play a song on Deezer (France in my case) using Firefox.
Would appreciate some help, thanks! 

![Capture d'écran 2024-11-28 231737](https://github.com/user-attachments/assets/eb01a3e9-782e-4d7f-9bff-c419b3af8bdf)

**Comment by D4niloMR** [comment]
Caused by blocking `https://cdn-assets.dzcdn.net/common/js/yzfdmoan.js`

**Comment by white12130** [comment]
Thank you  D4niloMR

**Comment by white12130** [comment]
17 / 5 000
still detected

**Comment by white12130** [comment]
still detected

**Comment by stephenhawk8054** [comment]
Force update your filter lists by clicking on [this link.](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=241201)

**Comment by Yuki2718** [comment]
`yzfdmoan.js` is no longer in EL, can be removed.

**Comment by TirOFlanc** [comment]
Hello,

For me, what blocks music playback is when this java script file is blocked:

`https://cdn-assets.dzcdn.net/common/js/gdpr-appliance/index.1a1c6234d544de3dc27e10690a4cca08b5aab4f8.js`

![image](https://github.com/user-attachments/assets/58db3f4b-7947-432b-b006-73a9fa7c40d7)

Once the rule has been created (as shown in the image below), everything works as it should, i.e. listening on deezer without premium accounts or ads.

![image](https://github.com/user-attachments/assets/115cfbc2-cb65-426f-a610-f2ed352e5526)

And I can add that I didn't fake it, I installed the AdGuard, Decentraleyes, Disconnect, Ghostery, Privacy Badger and of course uBlock Origin extensions, activating everything possible in terms of blocking.

Music is joy, it should be free, so enjoy!
