### ISSUE TITLE
hdmovie2.ren: breakage

### ISSUE THREAD

**Issue by Abdul8999** [uBlockOrigin/uAssets#22183]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hdmovie2.ren/44199-the-ghost-lights.html`

### Category

breakage

### Description

</details>player disappears

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-25 at 01-52-36 Wednesday](https://github.com/uBlockOrigin/uAssets/assets/152802539/32c01010-b1ba-4c87-8a45-d0f4922f6e3d)

</details>player disappears

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 115927
 cosmetic: 45104
 scriptlet: 18765
 html: 2042
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37227-112, now
  ublock-badware: 7795-10, now
  ublock-privacy: 988-0, now
  ublock-unbreak: 2238-1, now
  ublock-quick-fixes: 129-0, now
  easylist: 79061-629, now
  easyprivacy: 43562-860, now
  urlhaus-1: 8815-0, now
  plowe-0: 3783-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4429 ms (selfie)
 maxAssetCacheWait: 1026 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 57
 network:
  coolserving.com: 7
  gregarpor-roundens-i-276.site: 50
```
</details>

**Comment by okiehsch** [comment]
Add
`||gregarpor-roundens-i-276.site^$badfilter`
to your filter list.
@ryanbr  `||gregarpor-roundens-i-276.site^` in `EasyList` is causing the breakage.
