### ISSUE TITLE
o2online.de: breakage

### ISSUE THREAD

**Issue by D4n2021** [uBlockOrigin/uAssets#22196]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.o2online.de/kontakt/
```

### Description

On that page, scroll down to "Alle Kontaktmöglichkeiten im Überblick" and click on any of the dropdown-menus shown in the screenshot below. A loading animation will then play infinitely with uBO activated.

### Other extensions used

"Sponsorblock" for example

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/20766261/1a863f9a-6247-401f-ae7d-2696c89ac61a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 118772
 cosmetic: 50026
 scriptlet: 18776
 html: 2045
listset (total-discarded, last-updated):
 default:
  user-filters: 27-2, never
  ublock-filters: 37258-106, 1h.4m Δ
  ublock-badware: 7795-10, 1h.4m Δ
  ublock-privacy: 988-0, 1h.4m Δ
  ublock-unbreak: 2238-2, 1h.4m Δ
  ublock-quick-fixes: 128-5, 1h.4m Δ
  easylist: 79607-641, 1h.4m Δ
  easyprivacy: 43562-869, 1h.4m Δ
  urlhaus-1: 8745-0, 4m
  plowe-0: 3783-1, 4m
  DEU-0: 7292-18, 4m
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 30 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 285 ms (selfie)
 maxAssetCacheWait: 143 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  baqend.com: 17
  nowinteract.com: 1
  trbo.com: 1
  usercentrics.eu: 1

```
</details>

**Comment by huyszn** [comment]
Test: `@@||trbo.com/plugin/trbo_$script,domain=o2online.de`

**Comment by huyszn** [comment]
Yes, but I edited the filter so test the edited filter.
Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by okiehsch** [comment]
@ryanbr broken by `EasyPrivacy`.
`@@||trbo.com/plugin/trbo_$script,domain=o2online.de`
fiyes the issue.
