### ISSUE TITLE
intercelestial.com: nuisance

### ISSUE THREAD

**Issue by Wisdom1998** [uBlockOrigin/uAssets#22195]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://intercelestial.com/225088-gonggong/#generate
https://intercelestial.com/
```

### Description

The cosmatic filter is disabling the tempormonkey TimerHooker Module.

a week ago ublock was baypassing the wait timer on the above website , but now it does not work , please fix that thank you 

### Other extensions used

![Screenshot 2024-01-25 193004](https://github.com/uBlockOrigin/uAssets/assets/154932955/7b54e14b-fcdc-4504-a3de-aa3f69fad62e)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by ItsProfessional** [comment]
1. Remove your "tempormonkey TimerHooker Module"
2. This's a link shortener; go to #17361
