### ISSUE TITLE
maxstreams.site: detection

### ISSUE THREAD

**Issue by Alessio979** [uBlockOrigin/uAssets#22193]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://maxstreams.site/watchfree/gpefftk29czr/jaykuprgcav9/VGJ4MU1yMmRIRGlhYUlwRE4zeUJkdz09
```

### Description

new domain of maxstream.video

### Other extensions used

tampermonkey
Norton Password Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 248462
 cosmetic: 251886
 scriptlet: 50332
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76771-127, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95759-22033, now
  adguard-cookies: 28451-28451, now
  adguard-generic: 81858-566, 1m
  adguard-mobile: 9083-65, 1m
  adguard-mobile-app-banners: 4919-4919, now
  adguard-other-annoyances: 14133-14133, now
  adguard-popup-overlays: 26858-26858, now
  adguard-social: 22462-1643, now
  adguard-spyware-url: 1424-5, 1m
  adguard-widgets: 2410-2410, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ITA-0: 8323-24, 2h.14m
  easylist: 79607-2105, 13m Δ
  easyprivacy: 43562-423, 13m Δ
  plowe-0: 3783-1610, 1m
  ublock-badware: 7791-330, 13m Δ
  ublock-filters: 36657-3870, 13m Δ
  ublock-privacy: 992-106, 13m Δ
  ublock-quick-fixes: 128-7, 13m Δ
  ublock-unbreak: 2192-104, 13m Δ
  urlhaus-1: 8745-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2005 ms (selfie)
 maxAssetCacheWait: 1188 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by Alessio979** [comment]
it doesn't works:
Disable your adblock please.

Filters updated

Thanks

**Comment by Alessio979** [comment]
I had opened another report because I thought that once they were closed they would no longer be read.... it would seem so :)

**Comment by Alessio979** [comment]
news?
Thanks

**Comment by Alessio979** [comment]
As I imagined, closed tickets are no longer considered, perfect :D

**Comment by D4niloMR** [comment]
I get `Error 1005 Access denied`

**Comment by Alessio979** [comment]
new domain:
maxs15.online

link added
