### ISSUE TITLE
mediaexpert.pl: ads

### ISSUE THREAD

**Issue by asparanoiks** [uBlockOrigin/uAssets#22192]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mediaexpert.pl/`

### Category

ads

### Description

there are ads at the page's sides

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 117814
 cosmetic: 53264
 scriptlet: 18990
 html: 2056
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37237-180, 1h.44m Δ
  ublock-badware: 7795-10, 1h.44m Δ
  ublock-privacy: 988-0, 1h.44m Δ
  ublock-unbreak: 2238-1, 1h.44m Δ
  ublock-quick-fixes: 128-0, 1h.44m Δ
  easylist: 79607-649, 1h.44m Δ
  easyprivacy: 43562-832, 1h.44m Δ
  urlhaus-1: 8745-0, now
  plowe-0: 3783-1, now
  POL-0: 8620-26, now
  POL-2: 1283-12, 44m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 754 ms (selfie)
 maxAssetCacheWait: 188 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cookielaw.org: 1
  criteo.com: 1
  facebook.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
report at regional list repository (polish)
