### ISSUE TITLE
freerideworldtour.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#22190]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freerideworldtour.com/junior/news-videos/replay-2024-freeride-junior-world-championships/`

### Category

detection

### Description

Detects uBO when trying to watch the replay.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1438" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/0794b57a-9f1b-4a24-9973-fefab9994212">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 116707
 cosmetic: 46870
 scriptlet: 24709
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6585-34, 36m Δ
 default:
  user-filters: 47-2, never
  easylist: 79607-13, 1m
  easyprivacy: 43562-39, 1m
  plowe-0: 3783-1173, 1m
  ublock-badware: 7791-136, 1m
  ublock-filters: 36657-215, 1m
  ublock-privacy: 992-6, 1m
  ublock-quick-fixes: 128-5, 1m
  ublock-unbreak: 2192-33, 1m
  urlhaus-1: 8745-0, 1m
filterset (user): [array of 40 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 161 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  servedbyadbutler.com: 1
 extended:
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by BlazeFTL** [comment]
`freerideworldtour.com##+js(no-fetch-if, servedbyadbutler)`

**Comment by stephenhawk8054** [comment]
> `freerideworldtour.com##+js(no-fetch-if, servedbyadbutler)`

It will cause `No livestream available`

**Comment by BlazeFTL** [comment]
> livestream available

Both Ways It Says It Isn't Available For Me🙃

**Comment by stephenhawk8054** [comment]
The video plays fine for me with the new filters

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/10e80cce-c5ba-46a0-aa85-940425b76b5d)

**Comment by huyszn** [comment]
The new filters work for me. Maybe the site is geo-specific.
