### ISSUE TITLE
dunelm.com: breakage

### ISSUE THREAD

**Issue by Columbo1867** [uBlockOrigin/uAssets#22204]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.dunelm.com/product/2500w-11-fin-oil-filled-radiator-1000065946?defaultSkuId=30184953
```

### Description

The 'Recommended For You' pane does not appear. I have shown the screenshot with uBlock on and then with uBlock off. The pane appears as normal if EasyPrivacy is unticked.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled1](https://github.com/uBlockOrigin/uAssets/assets/67225952/e7e62d7c-81af-4912-ba39-0190809bd4ee)
![Untitled](https://github.com/uBlockOrigin/uAssets/assets/67225952/96382217-2cc1-41ba-8ffd-5d1bf07e098e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 145625
 cosmetic: 84770
 scriptlet: 37695
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://small.oisd.nl/: 43803-0, 32m
  adguard-generic: 81855-4288, 22h.50m
 default:
  user-filters: 1-0, never
  easylist: 79765-27369, 3h.53m Δ
  easyprivacy: 43562-1467, 25m
  ublock-badware: 7791-332, 3h.53m Δ
  ublock-filters: 36681-3519, 3h.53m Δ
  ublock-privacy: 992-15, 3h.53m Δ
  ublock-quick-fixes: 130-6, 3h.53m Δ
  ublock-unbreak: 2192-100, 3h.53m Δ
  urlhaus-1: 8675-0, 2h.53m
filterset (user): [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 609 ms (selfie)
 maxAssetCacheWait: 205 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 11
 network:
  dunelm.com: 2
  bazaarvoice.com: 2
  bing.com: 1
  contentsquare.net: 1
  klarnaservices.com: 1
  monetate.net: 3
  snapchat.com: 1

```
</details>

**Comment by huyszn** [comment]
Test: `@@||monetate.net^$xhr,domain=dunelm.com`

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
