### ISSUE TITLE
theglobeandmail.com: ads

### ISSUE THREAD

**Issue by Kr-cK** [uBlockOrigin/uAssets#22208]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.theglobeandmail.com/`

### Category

ads

### Description

Ad/nuisance on the bottom of the screen. Red banner that says "$1.99 subscribe now etc etc"

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 120099
 cosmetic: 45151
 scriptlet: 18795
 html: 2045
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2556-1, now
  adguard-spyware-url: 1424-216, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37273-140, now
  ublock-badware: 7800-10, now
  ublock-privacy: 988-49, now
  ublock-unbreak: 2242-1, now
  ublock-quick-fixes: 132-0, now
  easylist: 79812-636, now
  easyprivacy: 43563-832, now
  urlhaus-1: 8550-0, now
  plowe-0: 3783-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
hostRuleset:
 added: [array of 167 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 128 ms (selfie)
 maxAssetCacheWait: 67 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  adnxs.com: 2
  adorableattention.com: 1
  amazon-adsystem.com: 1
  amplitude.com: 2
  casalemedia.com: 1
  chartbeat.com: 3
  confiant-integrations.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  indexww.com: 1
  media.net: 1
  moatads.com: 1
  ntv.io: 1
  rubiconproject.com: 2
  scorecardresearch.com: 1
  sophi.io: 2
  wsod.com: 2
 extended:
  ##.c-button--adchoices
  ##.c-ad
  ##div[class^="BaseAd_"]
  ##+js(abort-on-property-write, adBlocker)
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. Add this as your custom filter

```adb
theglobeandmail.com###subscription-pencil-area
```
