### ISSUE TITLE
[nsfw] v.aki-h.com: breakage

### ISSUE THREAD

**Issue by MaalTi** [uBlockOrigin/uAssets#22207]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://v.aki-h.com/v/29228`

### Category

breakage

### Description

doesn't run at all

### Other extensions used

EditThisCookie

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 114
filterset (summary):
 network: 207155
 cosmetic: 45151
 scriptlet: 18795
 html: 2045
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 default:
  user-filters: 0-0, never
  ublock-filters: 37273-140, now
  ublock-badware: 7800-10, now
  ublock-privacy: 988-0, now
  ublock-unbreak: 2242-1, now
  ublock-quick-fixes: 132-0, now
  easylist: 79812-636, now
  adguard-spyware-url: 1424-103, now
  easyprivacy: 43563-832, now
  urlhaus-1: 8550-0, now
  curben-phishing: 87084-28, now
  plowe-0: 3783-1, now
  LegitimateURLShortener: 2556-163, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 785 ms (selfie)
 maxAssetCacheWait: 467 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
> doesn't run at all

Can you screenshot what exactly happened?

**Comment by mapx-** [comment]
I get 

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/b4a917bb-1927-4d5a-9d38-83881b718276)

**Comment by ItsProfessional** [comment]
Occurs even with uBO disabled.
