### ISSUE TITLE
civitai.com: detection

### ISSUE THREAD

**Issue by Buffmutti** [uBlockOrigin/uAssets#22203]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://civitai.com/models`

### Category

detection

### Description

I use Civitai.com daily because i create pictures with the AI every day and need LoRAs and other stuff from that site.
Since today Civitai.com recognizes that i use a adblocker and tells me to remove it and plasters the place with graphics and buttons with which i would buy their premium model. I updated the filters already, but this didn't help.

### Other extensions used

Consent-O-matic
Deactivation Add-on for Google Analytics
Fluff Busting Purity
Google Search "View Image" button
Hide Youtube Shorts
IBA Opt-out
IDN Safe
Mega
MyJDownloader Browser extension
Privacy Badger
Return Youtube Dislike
RSS Feedreader
Set Character Encoding
Shorts to normal player
Sponsorblock for Youtube
Cyberghost VPN
Tampermonkey
Tineye
Unshorten.it
Volume Control for Google Chrome
WebRTC Leak Shield 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![civitai](https://github.com/uBlockOrigin/uAssets/assets/22818031/be0aa32c-d3fe-46cc-9cf1-4994a1ae75dd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 242987
 cosmetic: 183181
 scriptlet: 42225
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  plowe-0: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76801-127, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 81847-506, now
  adguard-mobile: 9092-65, now
  adguard-social: 22470-938, now
  adguard-spyware-url: 1424-5, now
  curben-phishing: 86563-20, now
  dpollock-0: 11632-81, now
 default:
  DEU-0: 7297-6, now
  easylist: 79802-2073, now
  easyprivacy: 43563-336, 1h.32m Δ
  ublock-badware: 7791-330, 1h.32m Δ
  ublock-filters: 36681-3860, 1h.32m Δ
  ublock-privacy: 992-104, 1h.32m Δ
  ublock-quick-fixes: 130-6, 1h.32m Δ
  ublock-unbreak: 2192-103, 1h.32m Δ
  urlhaus-1: 8745-0, now
filterset (user): [array of 103 redacted]
trustedset:
 added: [array of 31 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
switchRuleset:
 added: [array of 16 redacted]
hostRuleset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 390 ms (selfie)
 maxAssetCacheWait: 315 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 19
 network:
  civitai.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 2
  google.com: 2
  googlesyndication.com: 1
  instagram.com: 9
  magsrv.com: 1
  youtube.com: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by huyszn** [comment]
I used `civitai.com##+js(no-fetch-if, googlesyndication)` to hide the banners but the placeholders and the `Become a supporter to turn off ads today.` still remain on `https://civitai.com/models`

**Comment by gorhill** [comment]
I can reproduce, @huyszn's `civitai.com##+js(no-fetch-if, googlesyndication)` works.

**Comment by Symbiomatrix** [comment]
Can this be reopened? The issue is only partially solved.
I've tried applying the following static filter, which seemingly catches the placeholders, but then they "phase in and out of existence", only disappearing when entering element picker / zapper mode and still showing on regular browsing after a refresh.
The js filter did nothing as far as I can tell.
`##.mantine-Paper-root:has(a[href="/pricing"])`

**Comment by stephenhawk8054** [comment]
```adb
civitai.com##.mantine-Paper-root:has(a:has-text(Remove ads))
```

hides the whole page in `https://civitai.com/images/5742499`

**Comment by huyszn** [comment]
@stephenhawk8054 Should the boxes on `https://civitai.com/models` when scrolling down that say `Become a supporter to turn off ads today.` be hidden or is it self-promo? I used this filter to remove them.
```
civitai.com##.mantine-Paper-root:has(> .mantine-Stack-root:has(.mantine-Text-root:has-text(Become a supporter)))
```

**Comment by stephenhawk8054** [comment]
@huyszn The filter is not really efficient (2 nested `has` with `has-text` inside), so I think we should not hide them

**Comment by gorhill** [comment]
I think this one would be ok:

    civitai.com##.mantine-Paper-root > .mantine-Stack-root:has-text(Become a supporter):upward(.mantine-Paper-root)

There are only ~15 matching elements for `:has-text()` to process, rather than (114x6x7) with the `:has()` based one.

**Comment by huyszn** [comment]
I noticed that posts on `https://civitai.com/posts` do not load when the filter `civitai.com##.mantine-Paper-root:empty` is enabled.

**Comment by D4niloMR** [comment]
Still have PH on the main page, maybe

`civitai.com##div[style^="width: "] > .mantine-Paper-root[style^="margin: "]`

**Comment by huyszn** [comment]
There is also a PH on model pages like `https://civitai.com/models/260267/animagine-xl-v3` between the Discussion and the Gallery section.

**Comment by nl255** [comment]
It is now an image which means matching text won't work. The key seems to be ##div.mantine-[random 6 character string].mantine-Paper-root and possibly div.mantine-[random 6 character string].mantine-Paper-root:nth-of-type(1).
The best I could get is with `||civitai.com/_next/image?url=%2Fimages%2Fsupport-us` which while it doesn't replace the PH it does remove the image and replace it with an empty box.

**Comment by k1logr4m** [comment]
I'm experiencing the same thing described on this Issue. The problem still persists even after creating a new Firefox profile with no extensions other than uBlockOrigin. 

### Troubleshooting Information (taken from clean profile)
```
uBlock Origin: 1.72.2
Firefox: 152
filterset (summary):
 network: 185080
 cosmetic: 43337
 scriptlet: 33740
 html: 3671
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 52934-160, 18m Δ
  ublock-badware: 10364-51, 18m Δ
  ublock-privacy: 4071-6, 45m
  ublock-unbreak: 2853-16, 45m
  ublock-quick-fixes: 488-13, 45m
  easylist: 89319-6, 18m Δ
  easyprivacy: 56006-41, 45m
  urlhaus-1: 47735-10, 45m
  plowe-0: 3518-1027, 45m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 115 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  snigelweb.com: 1
 extended:
  ##+js(prevent-fetch, faro.civitai.com)
  ##+js(prevent-fetch, googlesyndication)
  ##+js(prevent-clipboard-write, /^mshta |^(bash <<<|curl -kfsSL) …
```
