### ISSUE TITLE
9to5mac.com: breakage

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#22202]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://9to5mac.com/`

### Category

breakage

### Description

When uBo is enabled, I cannot toggle dark mode on this page. To do that, click on the circled button in the screenshot below.

### Other extensions used

None

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/11874211/69bd3f41-0eaf-47fb-a5da-b94a1f4a39cb)

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 116575
 cosmetic: 45139
 scriptlet: 18779
 html: 2045
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37259-142, now
  ublock-badware: 7795-10, now
  ublock-privacy: 988-0, now
  ublock-unbreak: 2238-1, now
  ublock-quick-fixes: 134-0, now
  easylist: 79802-636, now
  easyprivacy: 43563-832, now
  urlhaus-1: 8745-0, now
  plowe-0: 3783-1, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 398 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googletagmanager.com: 2
  parsely.com: 1
  twitter.com: 1
  typekit.net: 1
  videoplayerhub.com: 1
  wp.com: 1
 extended:
  ##.ad-disclaimer-container, .inlinead, .ad-container
  ##.ad-container
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.ad-container--leaderboard
  ##.inlinead
  ##ins.adsbygoogle
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtm.js$script,domain=9to5mac.com
@@||googletagmanager.com/gtag/js$script,domain=9to5mac.com
@@||fundingchoicesmessages.google.com$script,domain=9to5mac.com
```

**Comment by aaronliu0130** [comment]
Seems to work now!

-- 
Cheers,
Aᴀʀᴏɴ

**Comment by stephenhawk8054** [comment]
We have `rpnt` solutions without the need for exceptions: https://github.com/uBlockOrigin/uAssets/issues/22103#issuecomment-1902458699

I'll update it
