### ISSUE TITLE
next-episode.net breakage

### ISSUE THREAD

**Issue by chukpeev2** [uBlockOrigin/uAssets#22201]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://next-episode.net/for-all-mankind
```

### Description

The Popularity graph (above the "If you like For All Mankind you may also like") doesn't show up with ublock enabled, but does show when I disable it.

This happens on each show page where there is a popularity graph.

This broke recently, I know for sure it worked 3-4 days ago.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by gorhill** [comment]
You removed the troubleshooting information, do not do this. Nothing will move forward until you put it back.

**Comment by chukpeev2** [comment]
> You removed the troubleshooting information

Apologies, I don't think I removed anything. I didn't provide troubleshooting information because I didn't know what it was though.

I googled and found it in uBlock settings and added it to the ticket ...

**Comment by gorhill** [comment]
It's automatically filled when using the report button in the popup panel: <https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website>

Use this instead next time, almost all the fields will be filled properly.
