### ISSUE TITLE
nature.com: privacy

### ISSUE THREAD

**Issue by greatagnostic** [uBlockOrigin/uAssets#22216]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nature.com/articles/s41598-024-52599-y`

### Category

privacy

### Description

Cookie warning.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 129100
 cosmetic: 157033
 scriptlet: 31282
 html: 2257
listset (total-discarded, last-updated):
 added:
  adguard-social: 22470-1573, now
  adguard-cookies: 28458-1632, now
  ublock-cookies-adguard: 949-0, now
  adguard-popup-overlays: 26864-1635, now
  adguard-mobile-app-banners: 4920-1078, now
  adguard-other-annoyances: 14139-346, now
  adguard-widgets: 2425-36, now
  easylist-annoyances: 4319-1000, now
  easylist-chat: 180-22, now
  fanboy-cookiemonster: 49437-19727, now
  ublock-cookies-easylist: 949-949, now
  easylist-newsletters: 6896-1867, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37634-714, 6m Δ
  ublock-badware: 7794-10, 6m Δ
  ublock-privacy: 988-1, 6m Δ
  ublock-unbreak: 2247-1, 6m Δ
  ublock-quick-fixes: 134-0, 6m Δ
  adguard-mobile: 9092-144, now
  easylist: 79812-16786, 6m Δ
  easyprivacy: 43563-1005, 6m Δ
  urlhaus-1: 8550-0, now
  plowe-0: 3783-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1329 ms (selfie)
 maxAssetCacheWait: 311 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google.com: 2
  googletagmanager.com: 1
 extended:
  ##.c-site-messages
  ##.c-site-messages--nature-briefing
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by mapx-** [comment]
test

```
nature.com##.cc-banner__content
nature.com##.cc-banner
```

**Comment by dportvine** [comment]
`adguard-cookies: 28458-1632, now`

<details>
<summary>Screen</summary>

![2024-01-26_161832](https://github.com/uBlockOrigin/uAssets/assets/111344219/6efff935-ef5f-46a1-a035-138f81618603)
</details>

**Comment by mapx-** [comment]
@ryanbr @Alex-302

**Comment by Alex-302** [comment]
@mapx- We have `##.cc-banner`

<details>
<summary>Details</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8361299/f92c4295-daf0-4c4a-9d34-3811a11bb8b9)
![image](https://github.com/uBlockOrigin/uAssets/assets/8361299/aa193c97-9e5c-4718-915e-5c1fc12be1ae)


</details>

**Comment by mapx-** [comment]
@greatagnostic  check in your FF mobile this setting: `Ignore generic cosmetic filters` => it has to be disabled

**Comment by ItsProfessional** [comment]
The user has the option enabled. It's enabled by default on mobile, and if it's disabled then there's an explicit `ignoreGenericCosmeticFilters: false` in the troubleshooting info.
