### ISSUE TITLE
odiasongmuzic.com: nuisance

### ISSUE THREAD

**Issue by Harsh0121** [uBlockOrigin/uAssets#22211]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://odiasongmuzic.com/`

### Category

nuisance

### Description

its giving a verify things on all gplink shortend sites 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-26 113257](https://github.com/uBlockOrigin/uAssets/assets/79654658/fb89e5d0-c176-4ac5-b304-e404b0582280)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116416
 cosmetic: 45151
 scriptlet: 20200
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 50-40, never
  easylist: 79812-14, 9m
  easyprivacy: 43563-40, 10m Δ
  plowe-0: 3783-1173, 9m
  ublock-badware: 7796-136, 10m Δ
  ublock-filters: 36693-210, 10m Δ
  ublock-privacy: 992-6, 10m Δ
  ublock-quick-fixes: 132-5, 10m Δ
  ublock-unbreak: 2196-31, 10m Δ
  urlhaus-1: 8550-0, 10m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 289 ms (selfie)
 maxAssetCacheWait: 120 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 42
 network:
  ampproject.org: 10
  digislots.in: 1
  doubleclick.net: 1
  google.com: 7
  googlesyndication.com: 21
  googletagmanager.com: 2
 extended:
  ##center:others()
  ##[id*="iframe"], [id*="gpt_unit"], [id*="div-gpt-"]:style(heigh…
  ##+js(abort-on-property-write, AdBDetected)
  ##+js(set-constant, count, 0)
```
</details>

**Comment by ItsProfessional** [comment]
It has been fixed alongside the detection in your previous issue: #22210
don't create more issues about this domain
