### ISSUE TITLE
free-mp3-download.net: detection

### ISSUE THREAD

**Issue by TeflonDon93** [uBlockOrigin/uAssets#22212]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://free-mp3-download.net/?`

### Category

using ad blocker detection

### Description

It still comes up even with it off, iv tried multiple things iv seen on internet and revert back to default and still no luck
disabling javascript doesnt work neither

### Other extensions used

NORDVPN
Zyft

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122704
 cosmetic: 118531
 scriptlet: 29631
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 26863-44, now
  easylist-annoyances: 4319-138, now
  easylist-notifications: 2908-200, now
  fanboy-cookiemonster: 49399-200, now
  ublock-annoyances: 6588-156, 19m
  ublock-cookies-easylist: 911-911, now
 default:
  user-filters: 3-0, never
  easylist: 79812-45, 6m
  easyprivacy: 43563-146, 1h.49m Δ
  plowe-0: 3783-1173, 6m
  ublock-badware: 7796-136, now Δ
  ublock-filters: 36693-300, now Δ
  ublock-privacy: 992-7, now
  ublock-quick-fixes: 132-5, now Δ
  ublock-unbreak: 2196-35, now Δ
  urlhaus-1: 8550-0, 6m
filterset (user): [array of 3 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 147 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(abort-current-script, disableSelection, reEnable)
  ##+js(abort-on-property-write, document.oncontextmenu)
  ##+js(addEventListener-defuser, /^(contextmenu|keydown)$/)
```
</details>

**Comment by stephenhawk8054** [comment]
> It still comes up even with it off

That means something else on your machine is triggering the anti-adblock. Test again in a new browser profile with only uBO and its default settings.

---

> NORDVPN
> Zyft

You should check again your other extensions too.

**Comment by TeflonDon93** [comment]
![2024-01-26 15_34_18-](https://github.com/uBlockOrigin/uAssets/assets/152045815/d1adaa97-8092-4a3e-982b-6450d1b28ef4)

I already did 
and thats the screenshot to prove

**Comment by stephenhawk8054** [comment]
@TeflonDon93 What happens if you turn off uBO?

Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by TeflonDon93** [comment]
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 266677
 cosmetic: 45411
 scriptlet: 20914
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 89708-150, 1h.30m
  adguard-spyware-url: 1424-5, 1h.30m
  curben-phishing: 87084-20, 1h.30m
 default:
  user-filters: 0-0, never
  easylist: 79812-61, 1h.38m
  easyprivacy: 43563-26210, 3h.21m Δ
  plowe-0: 3783-1254, 1h.38m
  ublock-badware: 7796-143, 1h.32m Δ
  ublock-filters: 36702-246, 1h.21m
  ublock-privacy: 992-413, 1h.32m
  ublock-quick-fixes: 132-5, 1h.32m Δ
  ublock-unbreak: 2196-78, 1h.32m Δ
  urlhaus-1: 8550-0, 1h.38m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: browser.storage.local

**Comment by stephenhawk8054** [comment]
```yml
added:
adguard-spyware: 89708-150, 1h.30m
adguard-spyware-url: 1424-5, 1h.30m
curben-phishing: 87084-20, 1h.30m
```

You are not using default settings yet. Can you reset to default settings and test again? Which country are you when accessing the site?

Also

> What happens if you turn off uBO?

**Comment by TeflonDon93** [comment]
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116408
 cosmetic: 45149
 scriptlet: 20197
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 79812-14, now
  easyprivacy: 43563-40, now
  plowe-0: 3783-1173, now
  ublock-badware: 7796-136, now
  ublock-filters: 36693-210, now
  ublock-privacy: 992-6, now
  ublock-quick-fixes: 132-5, now
  ublock-unbreak: 2193-31, now
  urlhaus-1: 8550-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1200 ms
 maxAssetCacheWait: 36 ms
 cacheBackend: browser.storage.local
 
 
 
 so i just put it to default after u said
 
 and nothing changes when i turn it off
 im in australia

**Comment by stephenhawk8054** [comment]
> nothing changes when i turn it off

What happens if you turn off uBO completely in `chrome://extensions`

**Comment by TeflonDon93** [comment]
ive also already tried that

![Uploading 2024-01-26 16_30_24-.png…]()

**Comment by gwarser** [comment]
Your screenshot did not upload. 

>ive also already tried that

This means it's not uBO issue. You really should try harder to find issues in your browser, system or connection.

**Comment by TeflonDon93** [comment]
lol how am i supposed to figure it out if iv done all things you've told me or done before you even mentioned it
and your telling me to try harder when iv already even done the things you suggested

how rude of you to say i should try harder
you expect someone to try harder and know how to look further when they've already gone as far as they can

but "nah try harder"
![2024-01-26 16_30_24-](https://github.com/uBlockOrigin/uAssets/assets/152045815/7caf80da-8377-4932-b2cf-61be0979ea02)

**Comment by okiehsch** [comment]
You say you can reproduce even if you completely disable uBO.
If the site detects an adblocker even if you don't have one why do you think we cause the detection and what do you think we should do?

On my end the site works without issue with or without uBO enabled.

**Comment by marior12346** [comment]
I also have the same problem, by disabling uBO the site works

**Comment by ItsProfessional** [comment]
Fixed 9 hours ago. Update your lists.

**Comment by x8009** [comment]
Hey, it's not working again.. can fix?
