### ISSUE TITLE
puzzle-slant.com: ads

### ISSUE THREAD

**Issue by OhThirtyFour** [uBlockOrigin/uAssets#22218]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.puzzle-slant.com/?size=10`

### Category

ads

### Description

This website is showing a flashing gif of an ad for wayclix.com. On previous days, the ads were not visible, but starting January 26th they became visible.

### Other extensions used

SponsorBlock, Search by Image, ClearURLs, Indie Wiki Buddy, Open in VLC Media Player

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116389
 cosmetic: 45150
 scriptlet: 18787
 html: 2048
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  ublock-filters: 37284-142, 1m
  ublock-badware: 7800-10, 1m
  ublock-privacy: 988-0, 1m
  ublock-unbreak: 2242-0, 1m
  ublock-quick-fixes: 134-0, 1m
  easylist: 79812-636, now
  easyprivacy: 43563-832, now
  urlhaus-1: 8535-0, now
  plowe-0: 3783-1, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 266 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  puzzle-slant.com: 2
  a-mo.net: 1
  adnxs.com: 1
  criteo.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  lijit.com: 1
  s-onetag.com: 2
```
</details>

**Comment by gorhill** [comment]
Got this, unsure whether it's sensible:

    ||puzzle-slant.com/images/ad/
    puzzle-slant.com##body > :not(#Side,#MainContainer)
    puzzle-slant.com###MainContainer > :not(#pageContent)

cc @ryanbr

**Comment by JobcenterTycoon** [comment]
Its ad reinsertion. Same group: https://github.com/uBlockOrigin/uAssets/issues/22220 fixed one hour ago.
