### ISSUE TITLE
guanjia.qq.com: breakage

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#22217]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://guanjia.qq.com/knowledge-base/content/1059`

### Category

breakage

### Description

uBlock Orgin makes article in this page couldn't display. 

### Other extensions used

Not relevant. This issue even happens when only enable uBlock Origin. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBock Origin enabled
![uBock Origin enabled](https://github.com/uBlockOrigin/uAssets/assets/56181919/430cba66-9038-47bd-ab6c-54322991782e)

uBlock Origin disabled
![uBock Origin disabled](https://github.com/uBlockOrigin/uAssets/assets/56181919/cd94fac3-10d6-49e1-b938-bd39cdc562a9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 122
filterset (summary):
 network: 300939
 cosmetic: 103147
 scriptlet: 37262
 html: 2048
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81873-5881, 1m
  adguard-mobile: 9094-102, 1m
  adguard-spyware-url: 1424-103, 2m
  adguard-spyware: 89712-27863, 2m
  block-lan: 56-0, 2m
  curben-phishing: 87084-28, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 37284-173, now
  ublock-badware: 7800-10, 1m
  ublock-privacy: 986-0, 1m
  ublock-unbreak: 2244-1, 1m
  ublock-quick-fixes: 133-0, 1m
  easylist: 79812-700, 1m
  easyprivacy: 43563-852, 2m
  urlhaus-1: 8550-0, 2m
  plowe-0: 3783-1, 2m
  CHN-0: 26194-154, 2m
filterset (user): [empty]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 534 ms (selfie)
 maxAssetCacheWait: 345 ms
popupPanel:
 blocked: 8
 network:
  qq.com: 5
  rumt-zh.com: 3
 extended:
  ##+js(json-prune, ad)
```
</details>

**Comment by mapx-** [comment]
add

`@@||beacon.cdn.qq.com/sdk/*/beacon_web.min.js$script,domain=guanjia.qq.com`

`AdGuard Tracking Protection`
due to `||beacon.cdn.qq.com^`
@Alex-302 @Yuki2718
