### ISSUE TITLE
etsy.com: breakage

### ISSUE THREAD

**Issue by frugalshave** [uBlockOrigin/uAssets#22224]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.etsy.com/your/shops/me/dashboard?ref=hdr-mcpa`

### Category

breakage

### Description

Just started today. When enabled everything past the header is blocked

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ScreenShot1](https://github.com/uBlockOrigin/uAssets/assets/60978308/e1465a74-9848-4a41-813f-98586cd98a55)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 127404
 cosmetic: 196982
 scriptlet: 29126
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28468-30, 5m
  adguard-mobile-app-banners: 4920-8, 5m
  adguard-other-annoyances: 14138-8, 5m
  adguard-popup-overlays: 26884-80, 5m
  adguard-social: 22476-935, 5m
  adguard-widgets: 2425-3, 5m
  easylist-annoyances: 4319-238, 1m
  easylist-chat: 180-13, 1m
  easylist-newsletters: 6896-471, 1m
  easylist-notifications: 2908-1465, 1m
  fanboy-cookiemonster: 49403-3766, 1m
  fanboy-social: 16111-751, 1m
  [2 lists not shown]: [too many]
 default:
  user-filters: 31-1, never
  easylist: 79817-70, 1h.3m Δ
  easyprivacy: 43563-155, 1h.3m Δ
  plowe-0: 3786-1178, 1m
  ublock-badware: 7796-136, 1h.3m Δ
  ublock-filters: 36702-568, 1h.3m Δ
  ublock-privacy: 992-8, 1h.3m Δ
  ublock-quick-fixes: 133-7, 1h.3m Δ
  ublock-unbreak: 2198-34, 1h.3m Δ
  urlhaus-1: 8535-0, 1m
filterset (user): [array of 31 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1154 ms
 maxAssetCacheWait: 384 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  etsy.com: 1
  sentry-cdn.com: 1
  zdassets.com: 1
 extended:
  ###fb-root:not(body):not(html)
  #@#div[data-gdpr-consent-prompt]
  ##+js(set-cookie, ctc_rejected, 1)
  ##+js(trusted-set-cookie, p, eyJnZHByX3RwIjoyLCJnZHByX3AiOjF9, 1…
```
</details>

**Comment by mapx-** [comment]
I have an account but going to 
https://www.etsy.com/your/shops/me/dashboard

it results in:
```
Uh oh!
Sorry, the page you were looking for was not found.
```

Test using only the default settings  / filter lists => if it's ok => add 1 by 1 the other lists until you'll get the "bad" one => report back
