### ISSUE TITLE
tech.unblockedgames.world: nuisance

### ISSUE THREAD

**Issue by SDee001** [uBlockOrigin/uAssets#22229]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tech.unblockedgames.world/`

### Category

nuisance

### Description

The Timer in the site wont go after being redirected from other on to this one

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 313136
 cosmetic: 253853
 scriptlet: 49550
 html: 2256
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81887-7072, now
  adguard-mobile: 9100-103, now
  adguard-spyware-url: 1424-104, now
  adguard-spyware: 89719-26890, now
  block-lan: 56-0, now
  curben-phishing: 98539-28, now
  adguard-social: 22476-877, now
  adguard-cookies: 28468-63, now
  ublock-cookies-adguard: 912-0, now
  adguard-popup-overlays: 26884-1683, now
  adguard-mobile-app-banners: 4920-1074, now
  adguard-other-annoyances: 14130-332, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 37434-427, 1h.4m Δ
  ublock-badware: 7800-10, 1h.4m Δ
  ublock-privacy: 988-0, 1h.4m Δ
  ublock-unbreak: 2244-0, 1h.4m Δ
  ublock-quick-fixes: 133-0, 1h.4m Δ
  easylist: 79949-838, 1h.4m Δ
  easyprivacy: 43563-1006, 1h.4m Δ
  urlhaus-1: 8300-0, now
  plowe-0: 3786-1, 4m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 43067 ms (selfie)
 maxAssetCacheWait: 3340 ms
 cacheBackend: indexedDB
 unsuspendAfter: 39027 ms
popupPanel:
 blocked: 3
 network:
  adpushup.com: 1
  doubleclick.net: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by ItsProfessional** [comment]
Provide us the shortener URL.
