### ISSUE TITLE
apkmirror.com: breakage

### ISSUE THREAD

**Issue by WiFi-mon** [uBlockOrigin/uAssets#22223]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.apkmirror.com/`

### Category

breakage

### Description

Pressing the magnifying glass button doesn't open the search bar.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240127-001542_Mull](https://github.com/uBlockOrigin/uAssets/assets/157819828/aae6e64c-4f16-4a49-9687-e31e2dd60608)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 121
filterset (summary):
 network: 116388
 cosmetic: 45467
 scriptlet: 18784
 html: 2046
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  JPN-1: null
 default:
  user-filters: 0-0, never
  ublock-filters: 37609-113, 15m
  ublock-badware: 7789-10, 10m
  ublock-privacy: 988-0, 10m
  ublock-unbreak: 2244-0, 10m
  ublock-quick-fixes: 133-0, 10m
  easylist: 79812-262, never
  easyprivacy: 43563-63, never
  urlhaus-1: 8535-0, never
  plowe-0: 3786-1178, never
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2157 ms (selfie)
 maxAssetCacheWait: 799 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  apkmirror.com: 1
  googletagmanager.com: 1
  pro-market.net: 1
  scorecardresearch.com: 1
 extended:
  ##div.appRow[style]
  ##.advertisement-text
  ##.ains
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, as_profile_cache, $remove$)
  ##+js(set-local-storage-item, as_accetpable_ads_blocked_cache, $…
  ##+js(set-local-storage-item, as_adblock_cache, $remove$)
  ##+js(noeval-if, /07c225f3\.online|content-loader\.com|css-load\…
```
</details>

**Comment by gorhill** [comment]
Caused by `apkmirror.com##+js(rmnt, script, /style:last-of-type|:empty|APKM\..+?\.innerHTML/)`

**Comment by gorhill** [comment]
@stephenhawk8054 The problematic filter was added in <https://github.com/uBlockOrigin/uAssets/commit/8a0159428bc>. I don't know what was the fix for and how it should be modified. The issue is that code in files required `APZM.docReady`, but it's not defined with that filter.

**Comment by stephenhawk8054** [comment]
@gorhill It was used for their previous anti-adblock, but now they don't use it any more. I'll remove it
