### ISSUE TITLE
thedial.world: nuisance

### ISSUE THREAD

**Issue by xemptsible** [uBlockOrigin/uAssets#22239]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thedial.world/`

### Category

nuisance

### Description

Cookie banner on bottom left that can't be element picked

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/131531215/010b6d76-4a75-4940-af4f-227a06a16632)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 119281
 cosmetic: 61043
 scriptlet: 27087
 html: 2259
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4319-902, 4m
  fanboy-cookiemonster: 64840-32894, 11m
  ublock-cookies-easylist: 912-0, 4m
  ublock-annoyances: 6552-940, 4m Δ
  VIE-1: 1900-16, 1h.24m
 default:
  user-filters: 0-0, never
  ublock-filters: 37455-374, 1h.24m Δ
  ublock-badware: 7800-10, 1h.24m Δ
  ublock-privacy: 988-1, 1h.24m Δ
  ublock-unbreak: 2244-1, 1h.24m Δ
  ublock-quick-fixes: 142-0, 1h.24m Δ
  easylist: 79956-16778, 1h.24m Δ
  easyprivacy: 43569-902, 1h.24m Δ
  urlhaus-1: 8175-0, now
  plowe-0: 3786-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 870 ms (selfie)
 maxAssetCacheWait: 314 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 no-cosmetic-filtering: true
 network:
  thedial.world: 1
  googletagmanager.com: 1
  squarespace.com: 2
  typekit.net: 2
```
</details>

**Comment by mapx-** [comment]
it's due to your ignoring the generic cosmetic filters

`ignoreGenericCosmeticFilters: true`

reset uBO to default settings / lists
