### ISSUE TITLE
yingyongge.com: ads

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#22235]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yingyongge.com/lElF3.html`

### Category

ads

### Description

Residual ads

### Other extensions used

N/A. It still happens when disable all other extensions. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-01-27 at 19-17-09 电脑机箱后面风扇出风还是进风-应用哥科技](https://github.com/uBlockOrigin/uAssets/assets/56181919/9d4849b9-c115-46f9-a3bd-25fc1d8da79c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 122
filterset (summary):
 network: 312208
 cosmetic: 103224
 scriptlet: 37304
 html: 2051
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81887-6962, 1m
  adguard-mobile: 9100-102, 1m
  adguard-spyware-url: 1424-103, 2m
  adguard-spyware: 89719-26853, 2m
  block-lan: 56-0, 2m
  curben-phishing: 98539-28, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 37437-185, now
  ublock-badware: 7800-10, 1m
  ublock-privacy: 986-0, 1m
  ublock-unbreak: 2244-1, 1m
  ublock-quick-fixes: 135-0, 1h.29m
  easylist: 79955-770, 1m
  easyprivacy: 43569-855, 2m
  urlhaus-1: 8300-0, 2m
  plowe-0: 3786-1, 2m
  CHN-0: 26203-154, 2m
filterset (user): [empty]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 403 ms (selfie)
 maxAssetCacheWait: 236 ms
popupPanel:
 blocked: 15
 network:
  baidu.com: 14
  baidustatic.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Report in the regional list repo https://github.com/AdguardTeam/AdguardFilters/issues
