### ISSUE TITLE
diariodenavarra.es: detection

### ISSUE THREAD

**Issue by AlfonsoML** [uBlockOrigin/uAssets#22233]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.diariodenavarra.es/noticias/opinion/2024/01/27/presidente-federacion-atletismo-596935-1064.html`

### Category

detection

### Description

Last week I created https://github.com/uBlockOrigin/uAssets/issues/22127 about this same issue and it was fixed shortly after.  
I don't remember if I saw it work properly because I might not read that website everyday (sometimes only the front page).
The issue is the same, the page loads and shortly after it shows a full page banner blocking everything because it has detected uBlock.  
If I keep the Developer tools console open, it breaks on a Javascript error and the page isn't blocked

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2024-01-27 112414](https://github.com/uBlockOrigin/uAssets/assets/2482331/14bb8ad4-d626-4c3e-9490-ad174d3d04a7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 310674
 cosmetic: 252177
 scriptlet: 49933
 html: 2259
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 81887-7055, now
  adguard-mobile: 9100-105, now
  adguard-spyware-url: 1424-103, now
  block-lan: 56-0, now
  curben-phishing: 98539-28, now
  adguard-social: 22476-877, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 49425-3807, now
  fanboy-social: 16112-26, now
  ublock-annoyances: 6542-928, 1m Δ
  adguard-spyware: 89719-26892, now
  adguard-cookies: 28468-63, now
  [9 lists not shown]: [too many]
 default:
  ublock-filters: 37437-440, 1m Δ
  ublock-badware: 7800-10, 1m Δ
  ublock-privacy: 988-0, 1m Δ
  ublock-unbreak: 2244-1, 1m Δ
  easylist: 79954-887, 1m Δ
  easyprivacy: 43569-1020, 1m Δ
  urlhaus-1: 8300-0, now
  plowe-0: 3786-1, now
  spa-0: 3838-3, now
  spa-1: 5790-167, now
  ublock-quick-fixes: 136-0, 1m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 21 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1204 ms (selfie)
 maxAssetCacheWait: 263 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  diariodenavarra.es: 1
  20m.es: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  privacy-center.org: 1
  sensic.net: 1
  taboola.com: 1
 extended:
  ##.henneoHB
  ##.roba
  ##.sticky_horizontal
  ##.share-options
  ###AdSlot_megabanner
  ##.sticky_roba
  ##+js(addEventListener-defuser, DOMContentLoaded, AdBlock)
```
</details>

**Comment by big-cat-loaf** [comment]
```javascript
<script>
setTimeout(function () {
  var labelStyle = "color:white;background-color:#fa3;border-radius:100px;";
  if (window.Didomi.getUserConsentStatusForVendor('facebook')) {
    console.log('%c TCF Vendor Facebook Activo ', labelStyle);
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '1799479896975612');
    fbq('track', 'PageView');
  }
}, 5000)
</script>
``` 
Trigger code for detection

**Comment by ItsProfessional** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

You didn't. Continue in #22127
