### ISSUE TITLE
seriouseats.com: breakage

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [uBlockOrigin/uAssets#22234]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.seriouseats.com/food-lab-complete-guide-to-sous-vide-steak`

### Category

breakage

### Description

After clicking on reject all or accept all cookies button the cookie reminder does not disappear stuck on screen. Firefox mobile.
Turning off Ublock origin works well and disappears as expected.

### Other extensions used

Darkreader
Cookie auto delete 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 319416
 cosmetic: 198400
 scriptlet: 49598
 html: 2276
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81887-7218, now
  adguard-spyware-url: 1424-104, now
  adguard-spyware: 89719-26999, now
  block-lan: 56-0, now
  curben-phishing: 98539-28, now
  adguard-social: 22476-1585, now
  adguard-cookies: 28468-1636, now
  ublock-cookies-adguard: 950-0, now
  adguard-popup-overlays: 26884-1720, now
  adguard-mobile-app-banners: 4920-1079, now
  adguard-other-annoyances: 14130-615, now
  adguard-widgets: 2426-37, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 7-0, never
  ublock-filters: 37787-388, 1m Δ
  ublock-badware: 7794-10, 1m Δ
  ublock-privacy: 988-1, 1m Δ
  ublock-unbreak: 2249-1, 1m Δ
  ublock-quick-fixes: 136-0, 1m Δ
  adguard-mobile: 9100-49, now
  easylist: 79954-17026, 1m Δ
  easyprivacy: 43569-1111, 1m Δ
  urlhaus-1: 8300-0, now
  plowe-0: 3786-84, now
filterset (user): [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1713 ms (selfie)
 maxAssetCacheWait: 929 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cookielaw.org: 2
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  truste.com: 1
 extended:
  ##.mntl-dialog--campaign
  ##.campaign-dialog
```
</details>

**Comment by ItsProfessional** [comment]
> ` [11 lists not shown]: [too many]`

You are using a heavily modified configuration of uBO. Reset uBO and see if it works.

**Comment by Dani-1-2** [comment]
I have the annoyances filter lists and I have no such issues.
