### ISSUE TITLE
inquirer.com: breakage

### ISSUE THREAD

**Issue by uwagura** [uBlockOrigin/uAssets#22244]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.inquirer.com/`

### Category

breakage

### Description

Right hand sidebar does not appear on website with uBlock enabled

### Other extensions used

Bitwarden, Consent-O-matic, Decentraleyes, Ecosia, Enhancer for Youtube, Firefox multi-account containers, Fonts ninja, Get RSS feed from URL, honey, Old Reddit Redirect, Reddit Enhancement Suite, Redirect Amp to HTML, Simplelogin,  Tabs Mix plus, Tampermonkey(no scripts though), 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/36386988/a3c7b7ca-19c6-4264-95f0-1f484d62c216)
 it should look like this ( the section labelled "most read" is what is missing):
![image](https://github.com/uBlockOrigin/uAssets/assets/36386988/f797ade8-7a1f-4da4-9283-383ff0634392)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116096
 cosmetic: 45298
 scriptlet: 18838
 html: 2051
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37454-274, now
  ublock-badware: 7800-10, now
  ublock-privacy: 988-0, now
  ublock-unbreak: 2244-0, now
  ublock-quick-fixes: 143-0, now
  easylist: 79959-543, now
  easyprivacy: 43571-877, now
  urlhaus-1: 8190-0, now
  plowe-0: 3786-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1000 ms (selfie)
 maxAssetCacheWait: 453 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  inquirer.com: 4
  amazon-adsystem.com: 1
  chartbeat.com: 3
  cxense.com: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  matheranalytics.com: 1
  npttech.com: 1
  permutive.app: 1
  qualaroo.com: 1
  rubiconproject.com: 1
  speedcurve.com: 2
 extended:
  ##.lg\:col-span-1.sm\:col-span-2.auto-rows-min.grid-cols-1.gap-6…
```
</details>

**Comment by liamengland1** [comment]
```
@@||cdn.cxense.com^$script,domain=www.inquirer.com
@@||api.cxense.com^$script,domain=www.inquirer.com
```

**Comment by stephenhawk8054** [comment]
I only see `The latest`: 
![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/4644c8b9-c87c-4d09-a5ef-135018ea01c4)

I don't see any `Most read` even when turning off uBO.

**Comment by mapx-** [comment]
uBO off => most read
uBO on => the latest => + filters above => most read

@ryanbr

**Comment by uwagura** [comment]
Is there anyway to get just on or the other to appear on the home screen? I can see the "Most Read" section now, but only after "The Latest" section flickers onto the screen and then off of it: 

![inquirer_flickering](https://github.com/uBlockOrigin/uAssets/assets/36386988/95426848-b911-4594-aceb-4074709edbd3)

I think the inquirer switches between placing "The Latest" and "Most Read" at the right hand side of the screen so the exact entry that appears isn't super important, but I'm not sure why it is flickering between the two entries

**Comment by liamengland1** [comment]
@uwagura The site works that way with uBo off as well, its just poor design. If you want to hide "The Latest" from showing momentarily until "Most Popular" shows up, use this filter
`inquirer.com##.inq-card--latest-headlines>div:not(:has([id^="cxense-"]))`
