### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by gdviraj** [uBlockOrigin/uAssets#22245]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/artist/4EkSOXM6psqNE4w6j0tEEl`

### Category

breakage

### Description

When the ads comes on, Spotify player gets stuck. This was not the case until last week. I do not what has changed since then. This happens both on my Mac and Android.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116096
 cosmetic: 45298
 scriptlet: 18838
 html: 2051
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37454-126, 1h.36m Δ
  ublock-badware: 7800-10, 1h.36m Δ
  ublock-privacy: 988-0, 1h.36m Δ
  ublock-unbreak: 2244-0, 1h.36m Δ
  ublock-quick-fixes: 143-0, 1h.36m Δ
  easylist: 79959-705, 1h.36m Δ
  easyprivacy: 43571-863, 1h.36m Δ
  urlhaus-1: 8190-0, now
  plowe-0: 3786-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 185 ms (selfie)
 maxAssetCacheWait: 44 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Click on &#128344; clock icon at the end of `uBlock filters – Quick fixes` list, open new tab and test again.

Then continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/22198
