### ISSUE TITLE
vanillatweaks.net: ads, nuisance

### ISSUE THREAD

**Issue by Johannes-Andersen** [uBlockOrigin/uAssets#22243]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vanillatweaks.net/picker/crafting-tweaks/`

### Category

ads

### Description

The page has 3 issues:

- Privacy if a network call fails it posts to log-error.php
- When trying to download it has a 7 sec wait while you watch the ads in the popup
- Leftover ads in the popup (see screenshot)

Working filter to resolve the issues:
```
! 2024-01-27 https://vanillatweaks.net
||vanillatweaks.net/assets/server/log-error.php
vanillatweaks.net##fieldset.banner-spot
vanillatweaks.net##+js(nano-sib, downloadTimer)
```

### Other extensions used

Refined Github
1Password
Facebook container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="791" alt="Screenshot 2024-01-27 at 19 28 26" src="https://github.com/uBlockOrigin/uAssets/assets/57638117/e7544729-78d3-4ea6-8314-cfd6b6775f20">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 321654
 cosmetic: 252527
 scriptlet: 49956
 html: 2284
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81891-7251, 29m
  adguard-mobile: 9100-19, 29m
  adguard-spyware-url: 1424-104, 29m
  adguard-spyware: 89719-26980, 29m
  curben-phishing: 98015-29, 29m
  adguard-social: 22476-884, 28m
  adguard-cookies: 28468-64, 28m
  ublock-cookies-adguard: 912-0, 28m
  adguard-popup-overlays: 26884-1684, 28m
  adguard-mobile-app-banners: 4920-1074, 28m
  adguard-other-annoyances: 14131-332, 28m
  adguard-widgets: 2426-2, 28m
  [13 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 37455-421, 29m Δ
  ublock-badware: 7800-10, 29m Δ
  ublock-privacy: 988-0, 29m Δ
  ublock-unbreak: 2244-0, 29m Δ
  ublock-quick-fixes: 142-0, 29m Δ
  easylist: 79956-1007, 29m Δ
  easyprivacy: 43569-1104, 29m Δ
  urlhaus-1: 8175-0, 29m
  plowe-0: 3786-84, 29m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 288 ms (selfie)
 maxAssetCacheWait: 218 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  nitropay.com: 2
 extended:
  ##fieldset.banner-spot
  ##.share-button
  ##+js(adjust-setInterval, downloadTimer)
```
</details>

**Comment by stephenhawk8054** [comment]
I don't see any `log-error` connections. How to reproduce it?

**Comment by Johannes-Andersen** [comment]
> I don't see any `log-error` connections. How to reproduce it?

Hey!
It only logs when the `POST https://vanillatweaks.net/assets/server/zipresourcepacks.php` call fails
To quickly simulate the error, I just disabled the "disable" on the button, but it may trigger in scenarios like network timeouts etc



https://github.com/uBlockOrigin/uAssets/assets/57638117/f1101b04-9fee-4fd9-9a06-c876dafecacf

**Comment by stephenhawk8054** [comment]
I'm not really sure how it's related to privacy. It simply reports the connections that are failed to load when clicking "Download". It does not set any cookies nor collect any more information.
