### ISSUE TITLE
app.axenthost.com: detection

### ISSUE THREAD

**Issue by SakhJack** [uBlockOrigin/uAssets#22249]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.axenthost.com/`

### Category

detection

### Description

show pop-up asking to disable ADblock
refreshing page sometimes get rid of it, but it comes back after couple seconds

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/42785c73-6178-4f58-b46a-65694b815c4a)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 117
filterset (summary):
 network: 206247
 cosmetic: 45291
 scriptlet: 18833
 html: 2055
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37418-277, 1h.55m Δ
  ublock-badware: 7800-10, 5m Δ
  ublock-privacy: 988-0, 1h.55m Δ
  ublock-unbreak: 2244-1, 5m Δ
  ublock-quick-fixes: 147-0, 1h.55m Δ
  easylist: 79963-543, 1h.55m Δ
  adguard-spyware-url: 1424-103, 27m
  easyprivacy: 43569-877, 1h.55m Δ
  urlhaus-1: 8160-0, 1h.54m
  curben-phishing: 86522-28, 1h.55m
  plowe-0: 3786-1, 27m
  LegitimateURLShortener: 2555-163, 1h.55m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 246 ms (selfie)
 maxAssetCacheWait: 115 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  clarity.ms: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  nitropay.com: 1
 extended:
  ##+js(no-fetch-if, /^/)
```
</details>

**Comment by D4niloMR** [comment]
Test:

`app.axenthost.com#@#+js(no-fetch-if, /^/)`

**Comment by ScorelessPine** [comment]
I will say I just tested the above filter and it did not seem to work, and I also tried adding the filter from the referenced commit and it also did not seem to work. My filter list is updated as of minutes ago, refreshing the page did not solve the issue.

**Comment by SakhJack** [comment]
filter works but is incompatible with "AdGuard – Ads"

**Comment by D4niloMR** [comment]
Report here -> https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by D4niloMR** [comment]
@ScorelessPine On the site: 🛡️ uBO's icon > 💬 Report > Click "Troubleshooting information" > Select all > Copy > Share it.

**Comment by ScorelessPine** [comment]
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 116517
 cosmetic: 45305
 scriptlet: 20271
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  easylist: 80245-14, 1h.20m Δ
  easyprivacy: 43597-48, 1h.20m Δ
  plowe-0: 3786-1177, 42m
  ublock-badware: 7797-136, 41m
  ublock-filters: 36887-290, 41m
  ublock-privacy: 992-6, 41m
  ublock-quick-fixes: 135-8, 41m
  ublock-unbreak: 2198-31, 41m
  urlhaus-1: 8310-0, 1h.20m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 3868 ms (selfie)
 maxAssetCacheWait: 317 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0

**Comment by D4niloMR** [comment]
Can reproduce on Chrome. continue here: https://github.com/uBlockOrigin/uAssets/issues/20379
