### ISSUE TITLE
goodreads.com: breakage

### ISSUE THREAD

**Issue by micahchoo** [uBlockOrigin/uAssets#22240]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.goodreads.com/book/show/43990.Karukku`

### Category

breakage

### Description

I tried #20510, still breaks the site "An unexpected error has occurred."

### Other extensions used

Nothing else

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 123549
 cosmetic: 133090
 scriptlet: 29184
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28468-30, now
  adguard-mobile-app-banners: 4920-8, now
  adguard-other-annoyances: 14131-8, now
  adguard-popup-overlays: 26884-80, now
  adguard-social: 22476-935, now
  adguard-widgets: 2426-3, now
  ublock-annoyances: 6599-179, 21m Δ
  ublock-cookies-adguard: 912-912, now
 default:
  user-filters: 0-0, never
  easylist: 79956-70, 21m Δ
  easyprivacy: 43569-109, 21m Δ
  plowe-0: 3786-1178, now
  ublock-badware: 7796-136, 21m Δ
  ublock-filters: 36875-639, 21m Δ
  ublock-privacy: 992-7, 21m Δ
  ublock-quick-fixes: 141-7, 21m Δ
  ublock-unbreak: 2198-33, 21m Δ
  urlhaus-1: 8175-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1070 ms (selfie)
 maxAssetCacheWait: 255 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 14
 network:
  goodreads.com: 10
  amazon-adsystem.com: 1
  amazon.com: 1
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ##+js(remove-class, Header__siteHeaderBanner, header.Header__sit…
```
</details>

**Comment by mapx-** [comment]
@gorhill 

the filter bellow from `AdGuard – Popup Overlays` is breaking the page (`An unexpected error has occurred.`)

`goodreads.com#?#.Overlay--floating:has(> div.Overlay__window > div.Overlay__content > div.LoginInterstitial)`

(repeat 2-3 times to get it)

- the filter does not break the page in AdGuard extension (chrome)
- the filter is not reported by the logger in uBO (neither in AG)

**Comment by mapx-** [comment]
@micahchoo to have temp fix add in "my filters"

`goodreads.com#@?#.Overlay--floating:has(> div.Overlay__window > div.Overlay__content > div.LoginInterstitial)`

**Comment by gorhill** [comment]
That filter doesn't cause the issue on my side, but I do see the issue with the whole list "AdGuard – Popup Overlays".

**Comment by gorhill** [comment]
Note that I also get the error when adding the following to ABP:

    goodreads.com##.Overlay--floating:has(> div.Overlay__window > div.Overlay__content > div.LoginInterstitial)

It seems to me the page has an issue when a native `:has()` selector is present -- not sure AdGuard is injecting a native `:has()`.

**Comment by mapx-** [comment]
Even the filter using `remove()` leads to the same error on my end

**Comment by gorhill** [comment]
The site is going to suffer the same issue once AdGuard supports native `:has()`, so it's probably something they would want to fix. This one works, it just makes the element invisible:

    goodreads.com#?#.Overlay--floating:has(> div.Overlay__window > div.Overlay__content > div.LoginInterstitial):style(opacity: 0 !important; pointer-events: none !important)

**Comment by mapx-** [comment]
@Alex-302

**Comment by gorhill** [comment]
Related: <https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2587>

**Comment by Alex-302** [comment]
Changed to removing rule.
