### ISSUE TITLE
egamersworld.com: ads

### ISSUE THREAD

**Issue by nqlp** [uBlockOrigin/uAssets#22241]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://egamersworld.com/blog/league-of-legends-patch-141-comprehensive-overview-t8fwzRWID`

### Category

ads

### Description

There are 2 banners ads positioned on the left, right, and in the middle.

### Other extensions used

- Bitwarden
- Dark Reader
- Fast Forward
- SponsorBlock for YouTube
- 2FAS
- Bypass Paywalls Clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/86736500/23bca657-6437-47e4-8e1a-bb0691ef530d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 307824
 cosmetic: 245831
 scriptlet: 51160
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76829-127, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95788-22032, now
  adguard-cookies: 28468-28468, now
  adguard-generic: 81891-538, now
  adguard-mobile: 9100-62, now
  adguard-mobile-app-banners: 4920-4920, now
  adguard-other-annoyances: 14131-14131, now
  adguard-popup-overlays: 26884-26884, now
  adguard-social: 22476-1646, now
  adguard-spyware: 89719-1238, now
  adguard-spyware-url: 1424-5, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 21-1, never
  easylist: 79954-1942, 12m Δ
  easyprivacy: 43569-26459, 12m Δ
  plowe-0: 3786-1344, now
  ublock-badware: 7796-329, 12m Δ
  ublock-filters: 36857-4008, 12m Δ
  ublock-privacy: 992-414, 12m Δ
  ublock-quick-fixes: 135-8, 12m Δ
  ublock-unbreak: 2198-149, 12m Δ
  urlhaus-1: 8175-0, now
filterset (user): [array of 22 redacted]
userSettings:
 advancedUserEnabled: true
 hyperlinkAuditingDisabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 299 ms (selfie)
 maxAssetCacheWait: 234 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 30
 network:
  connatix.com: 2
  doubleclick.net: 1
  ezodn.com: 10
  ezoic.net: 11
  google.com: 2
  googletagmanager.com: 1
  pubmatic.com: 1
  youtube.com: 2
 extended:
  ##[data-ez-name]
  ##div[id^="ezoic-pub-ad-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ezoic-ad
  #@#[id^="div-gpt-ad"]
```
</details>

**Comment by mapx-** [comment]
add

`egamersworld.com##[href^="/gg/"]`

@ryanbr
