### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by jgorman6475** [uBlockOrigin/uAssets#22242]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/playlist/309hZ1MyVsw8yXwyOae5Vw`

### Category

ads

### Description

Plays 2-3 songs then stops working showing either full song completed or next song queue'd with ad playing. Previous fix was being able to purge cache then update

tried various filters found in comments of other spotify issue posts, none have worked.

### Other extensions used

dark reader
privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116079
 cosmetic: 45295
 scriptlet: 18837
 html: 2051
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37453-126, now
  ublock-badware: 7800-10, now
  ublock-privacy: 988-0, now
  ublock-unbreak: 2244-0, now
  ublock-quick-fixes: 142-0, now
  easylist: 79956-705, now
  easyprivacy: 43569-863, now
  urlhaus-1: 8175-0, now
  plowe-0: 3786-1, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 521 ms (selfie)
 maxAssetCacheWait: 135 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 5
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by ItsProfessional** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

You didn't. #22198

**Comment by jgorman6475** [comment]
It’s like I stated that I tried the various fixes in it and they didn’t work. All the rest of the ones keep getting closed because they “can’t be replicated” even though with the amount of issues it’s obviously replicated.

**Comment by jgorman6475** [comment]
You also closed that ticket mentioned with no fix or steps for attempts to fix. There is no megathread created and no other updates. Yet all of these tickets get closed and moved on from

**Comment by ItsProfessional** [comment]
It doesn't matter if it's fixed or not: you have to continue on the same issue. Don't create duplicates.
