### ISSUE TITLE
uploady.io: popups

### ISSUE THREAD

**Issue by Stoebi65** [uBlockOrigin/uAssets#22247]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uploady.io/jrd11llcl0a1`
`https://homogonymouserapparels.monster/`

### Category

popups and open new tab

### Description

After clicking a download button a new tab is always open a new tab: homogonymouserapparels.monster/*
Then i click again, i can dl the file.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 118463
 cosmetic: 50183
 scriptlet: 20233
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  DEU-0: 7301-0, now
  easylist: 79963-21, 44m Δ
  easyprivacy: 43571-49, 44m Δ
  plowe-0: 3786-1178, 44m
  ublock-badware: 7796-136, 44m Δ
  ublock-filters: 36821-305, 44m Δ
  ublock-privacy: 992-6, 44m Δ
  ublock-quick-fixes: 143-9, 44m Δ
  ublock-unbreak: 2198-33, 44m Δ
  urlhaus-1: 8190-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 384 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by Stoebi65** [comment]
lrepacks.net and select a file, click uplody.io

**Comment by huyszn** [comment]
I found a page on the site that has the `uploady.io` link: `https://lrepacks.net/repaki-programm-dlya-interneta/56-internet-download-manager-repack.html`. It is `uploady.io` not `uplody.io`.

**Comment by Fatcavill** [comment]
`https://uploady.io/572b3xs2h3eb/BBVpn_VPN_Unlimited_VPN_v3.7.7_317_Premium_Mod..apk`

Why do i have click twice in the first and last button on the page can that be fixed ? An there is also ad
Thank you

**Comment by huyszn** [comment]
I could reproduce clicking twice on the last button where you download the file. Not sure what you mean by the first button.

**Comment by Fatcavill** [comment]
its fix now thanks bro
