### ISSUE TITLE
Purge all caches option missing. 

### ISSUE THREAD

**Issue by Tri-colore** [uBlockOrigin/uAssets#22259]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
ublock dashboard filter list
```

### Description

The Purge all caches option has disappeared. 

### Other extensions used

Dark reader 
marvelous suspender

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="793" alt="Screenshot 2024-01-29 at 2 33 41 AM" src="https://github.com/uBlockOrigin/uAssets/assets/78786273/0ebfdb73-03a4-43d7-b736-28159f4e271b">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116354
 cosmetic: 45294
 scriptlet: 20257
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80228-14, 1m Δ
  easyprivacy: 43567-42, 1m Δ
  plowe-0: 3786-1177, 2h.23m
  ublock-badware: 7796-136, 1m Δ
  ublock-filters: 36867-290, 1m Δ
  ublock-privacy: 992-6, 1m Δ
  ublock-quick-fixes: 146-24, 1m Δ
  ublock-unbreak: 2198-31, 1m Δ
  urlhaus-1: 8190-0, 20h.45m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 489 ms (selfie)
 maxAssetCacheWait: 224 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/1995cww/why_purge_all_caches_is_now_removed_from_ubo/
