### ISSUE TITLE
softonic.com.br: breakage

### ISSUE THREAD

**Issue by juarez-spa3** [uBlockOrigin/uAssets#22252]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://foobar2000.softonic.com.br/`

### Category

breakage

### Description

1-Click the Rate button. The popup is not shown.

2-Type something in the search button on the home page and press enter. Search results are not shown.

This `softonic.*##+js(addEventListener-defuser, , [native code])` rule breaks the site.

3-Please also add the following rule for Softsonic's international websites. It doesn't seem to cause breakage.
`softonic-ar.com,softonic-id.com,softonic.jp,softonic.kr,softonic.nl,softonic.pl,softonic.com.br,softonic.ru,softonic-th.com,softonic.com.tr,softonic.vn,softonic.cn##.sam-slot`

### Other extensions used

TWP Translate web pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![sft-break](https://github.com/uBlockOrigin/uAssets/assets/153795294/8c3c7243-dcd6-4d88-8666-a46b79055967)
![sft-break2](https://github.com/uBlockOrigin/uAssets/assets/153795294/896743f7-5f7f-4030-b7e2-45e647b2c5ed)
![afbeelding](https://github.com/uBlockOrigin/uAssets/assets/153795294/198b63fd-ae24-46a1-8869-b297d8d4fe61)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 118194
 cosmetic: 51199
 scriptlet: 19257
 html: 2056
listset (total-discarded, last-updated):
 added:
  spa-1: 5790-11, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37418-169, 5m
  ublock-badware: 7800-10, 5m
  ublock-privacy: 988-0, 5m
  ublock-unbreak: 2244-0, 5m
  ublock-quick-fixes: 144-0, 5m
  easylist: 79986-750, 5m
  easyprivacy: 43567-850, 5m
  urlhaus-1: 8160-0, 5m
  plowe-0: 3786-1, 5m
  NLD-0: 2773-10, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4770 ms
 maxAssetCacheWait: 11 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  push-sdk.com: 1
 extended:
  ##+js(addEventListener-defuser, , [native code])
```
</details>

**Comment by D4niloMR** [comment]
> 3-Please also add the following rule for Softsonic's international websites. It doesn't seem to cause breakage.
softonic-ar.com,softonic-id.com,softonic.jp,softonic.kr,softonic.nl,softonic.pl,softonic.com.br,softonic.ru,softonic-th.com,softonic.com.tr,softonic.vn,softonic.cn##.sam-slot

For EL @ryanbr
