### ISSUE TITLE
(popup & ads) maxdeportv.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2225]
### URL(s) where the issue occurs

`http://maxdeportv.net/?canal=17`

### Describe the issue

There are many popups, and a lot of ads placeholders. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/39778852-bfe11958-52c4-11e8-9c68-750b55552f41.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.4

### Settings

All default. 

### Notes

Original report: 
```
Reference: Quick Issue Reporter

Message:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Nano Defender 14.11

[other] http://maxdeportv.net/?canal=17
There is a mix of unblocked ad, that I blocked with "maxdeportv.net###adsdiv" and "maxdeportv.net###iframe1" and a redirect to amazon.com if you switch canal from upper menu. For example if you browse to canal 18 when you click it, you 'll get redirected.
```

**Comment by okiehsch** [comment]
Well, I can't get the site to work properly, it looks totally "mangled" on my end, I can reproduce the popups,  
so I will fix them.
````
maxdeportv.net##script:inject(abort-on-property-write.js, Fingerprint2)
maxdeportv.net##script:inject(abort-current-inline-script.js, atob, tabunder)
maxdeportv.net##script:inject(window.open-defuser.js)
maxdeportv.net##A[href$=".html"][rel="nofollow norefferer noopener"]
````

**Comment by jspenguin2017** [comment]
I didn't, but they don't solve the problem, the white space just becomes black: 
![image](https://user-images.githubusercontent.com/7283682/39783967-134bd4fc-52d4-11e8-9691-739c15fa8d07.png)

**Comment by okiehsch** [comment]
Adding 
````
maxdeportv.net###adsdiv
maxdeportv.net###iframe1
````
makes the site much better looking on my end, so I will add them.

**Comment by mapx-** [comment]
some filters:
```
maxdeportv.net##script:inject(abort-on-property-write.js, Fingerprint2)
maxdeportv.net##script:inject(abort-current-inline-script.js, atob, tabunder)
||maxdeportv.club/lateral.html$subdocument
maxdeportv.net###iframe1
||maxdeportv.net/jquerymin1.js$script,first-party
deportesmax.info##script:inject(addEventListener-defuser.js, load, 2000)
deportesmax.info##script:inject(nowebrtc.js)
mitierratvco2.com##script:inject(nowebrtc.js)
mitierratvco2.com##script:inject(addEventListener-defuser.js, load, 2000)
||mitierratvco2.com/canales/canalpub.html
chatytvgratis.net##script:inject(nowebrtc.js)
cdn.chatytvgratis.net###interContainer
cdn.chatytvgratis.net###interVeil
```

**Comment by mapx-** [comment]
tested here:
`http://maxdeportv.net/?canal=caracol`

**Comment by okiehsch** [comment]
@mapx- add the filters that work for you, like I said the video streaming part of the site does not work for me.

**Comment by jspenguin2017** [comment]
The video isn't quite working for me, maybe Geo Lock. Fix as you see fit.

**Comment by llacb47** [comment]
Can you add:
```
vipracing.live,vipracing.info###vpp
||edua29146y.com^$3p
||showyourresult.com^$3p
```
thanks :)
