### ISSUE TITLE
abc.es: cookie message

### ISSUE THREAD

**Issue by UserPizza** [uBlockOrigin/uAssets#22254]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.abc.es/
https://www.abc.es/espana/rueda-unico-aprueba-conocido-favorito-gobernar-20240128181548-nt.html
```

### Description

I think is a anti-adblocker that appears with uBO active and forcing to pay
If accept the cookie-message with the adblocker OFF no appears again

some filters in uBlock filters – Cookie Notices and Annoyances maybe need a update

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![11](https://github.com/uBlockOrigin/uAssets/assets/146446273/0221edf3-4ef1-423d-9b48-f7e81ee49ae0)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 120663
 cosmetic: 97302
 scriptlet: 28824
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 64858-15635, never
  ublock-annoyances: 6602-29, 1h.27m Δ
  ublock-cookies-adguard: 913-913, never
  ublock-cookies-easylist: 913-913, never
 default:
  user-filters: 0-0, never
  easylist: 79986-14, 1h.27m Δ
  easyprivacy: 43567-40, 1h.27m Δ
  plowe-0: 3786-1177, 10m
  spa-0: 3838-19, 10m
  spa-1: 5790-219, 10m
  ublock-badware: 7796-136, 1h.27m Δ
  ublock-filters: 36858-307, 1h.27m Δ
  ublock-privacy: 992-6, 1h.27m Δ
  ublock-quick-fixes: 147-24, 1h.27m Δ
  ublock-unbreak: 2198-34, 1h.27m Δ
  urlhaus-1: 8160-0, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 100 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by UserPizza** [comment]
video no load
`https://www.abc.es/deportes/mohamed-katir-suspendido-tres-fallos-localizacion-controles-20240207133700-nt.html`

and the annoying cookie issue is back ( **the cookie-message appears all time** ), blocking this filter works:

`||sdk.privacy-center.org/*/loader`

**Comment by D4niloMR** [comment]
Should work now

**Comment by UserPizza** [comment]
tested the filter but no working, the message still all time

why `trusted-click-element` appears in red in my filters?

![111](https://github.com/uBlockOrigin/uAssets/assets/146446273/1df98d7f-37f0-475d-9b71-87ba42ff0655)

**Comment by UserPizza** [comment]
oh thanks for the info!

but the filter refreshing the page all time, example in main page:

`https://www.abc.es/`

im using `1.55.0` version of uBlock Origin, maybe is the problem?

**Comment by UserPizza** [comment]
haha perfect! 10/10
what a pro's! 😆

thanks
