### ISSUE TITLE
chilican.com group: breakage

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#22255]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

```
http://www.grattez.fr/
http://www.hackedgames.com/
http://www.jeux.com/
http://www.jouer.fr/
http://www.kissinggames.com/
http://www.pintgames.com/
http://www.playhub.com/
http://www.playpink.com/
http://www.prehackshub.com/

http://www.hackedgames.com/action/earn-to-die.html
http://www.jeux.com/jeux-sociaux/rami-11822.html
http://www.jeux.com/reflexion/candy-crush/candy-match-3.html
http://www.jouer.fr/racing/trials-ride-2.html
http://www.kissinggames.com/girls/secret-office-kissing.html
http://www.pintgames.com/girls/mario-island.html
http://www.playhub.com/action/dummy-never-fails.html
http://www.playpink.com/girls/dress-up/my-puppy.html
http://www.prehackshub.com/action/raft-wars.html
```

### Category

breakage

### Description

fix and cleanup filters that are self-promo
```
@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=hackedgames.com|jeux.com|jouer.fr|kissinggames.com|pintgames.com|playpink.com|prehackshub.com|playhub.com
grattez.fr##.ad-image-megaban
hackedgames.com,jeux.com,jouer.fr,kissinggames.com,pintgames.com,playhub.com,playpink.com,prehackshub.com##.ad-title-megaban
hackedgames.com,jouer.fr,prehackshub.com,pintgames.com##.ad-game-600, .ad-megaban-game-300
jeux.com,playhub.com,playpink.com##.ad-title-pave
playhub.com,playpink.com##.ad-title-sky
||play.turbommo.com^$3p
```
```
! invalid
jeux.*###msg_abk
||jeux.com/js/pu_ad.js
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 106471
 cosmetic: 48928
 scriptlet: 23750
 html: 2266
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1038-0, 14h.26m
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1993-0, 14h.26m
  ublock-annoyances: 6555-12, 3h.20m Δ
 default:
  user-filters: 2133-16, never
  ublock-filters: 37418-154, 3h.20m Δ
  ublock-badware: 7800-10, 3h.20m Δ
  ublock-privacy: 988-0, 3h.20m Δ
  ublock-unbreak: 2244-0, 3h.20m Δ
  ublock-quick-fixes: 147-0, now
  easylist: 79963-384, 3h.20m Δ
  easyprivacy: 43595-1803, 14h.26m
filterset (user): [array of 986 redacted]
switchRuleset:
 added: [array of 11 redacted]
hostRuleset:
 added: [array of 10 redacted]
 removed:
  behind-the-scene * * noop
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 632 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
 unsuspendAfter: 470 ms
popupPanel:
 blocked: 14
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  powerad.ai: 2
  ramponneraient.xyz: 2
  scorecardresearch.com: 1
  smilewanted.com: 2
  sportslocalmedia.com: 2
  taboola.com: 1
  vidoomy.com: 2
```
</details>

**Comment by ItsProfessional** [comment]
> `hackedgames.com,jouer.fr,prehackshub.com,pintgames.com##.ad-game-600, .ad-megaban-game-300`

Don't concatenate selectors with commas. Keep them on separate filters:
```adb
hackedgames.com,jouer.fr,prehackshub.com,pintgames.com##.ad-game-600
hackedgames.com,jouer.fr,prehackshub.com,pintgames.com##.ad-megaban-game-300
```

1. gorhill once urged this is the preferred way
2. Convenient for future cleanup
3. Advantageous to auto-deduplication, if the same filter exists in multiple lists (such as lists outside of uAssets, e.g. EasyList)

**Comment by Daxy7** [comment]
breakage
```
http://www.flibus.com/far-cry-5.html
```
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=flibus.com
```

**Comment by stephenhawk8054** [comment]
> `http://www.flibus.com/far-cry-5.html`

The video looks like unrelated to the article. I think it's a video ad.

**Comment by Daxy7** [comment]
Well, we'll block the player to disable the white flash upon loading the page
```
||player.pepsia.com/sdk.js$script,domain=flibus.com
```

**Comment by Daxy7** [comment]
@stephenhawk8054 safe for you to add this network filter along with chilican subsection?

**Comment by stephenhawk8054** [comment]
Does it appear in other sites?

**Comment by Daxy7** [comment]
in mostly french websites `https://trends.builtwith.com/websitelist/Pepsia`
i'm pretty sure most need `imasdk.googleapis.com` allowlisted. i'll update this in an hour or so
```
http://dailygeekshow.com
http://dicanimoz.com
http://festivalesdemusicaelectronica.com
http://first-names-meanings.com
http://infodiscus.com
http://infogym.com
http://jeux-geographiques.com
http://jeux-historiques.com
http://lemagfemmes.com
http://pergolamadine.com
http://phrase-swag.com
http://pilote-de-course.com
http://pulserocktv.com
http://signification-prenom.com
http://vipcrossing.com
http://streamkontrolle.de
http://videos4kids.de
http://dictionnaire-des-rimes.fr
http://francaisreussite.fr
http://france-prospect.fr
http://jardinature.net
http://jdbn.fr
http://leptidigital.fr
http://linfodurable.fr
http://parisfans.fr
http://parlerdamour.fr
http://phrase-amour.fr
http://prise2tete.fr
http://question-conversation.fr
http://recettesduchef.fr
http://seriesaddict.fr
http://stars-en-couple.fr
http://zone-turf.fr
http://juegostradicionales.net
http://potager-facile.net
http://paroles.net
http://finanzcheck.pro
```
