### ISSUE TITLE
[nsfw] domlepen.com: ads

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#22251]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://domlepen.com/kosu-arkadaslari-sikis-arkadaslarina-donustu/`

### Category

ads

### Description

Showing 2 video ads before playing actual video

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 132660
 cosmetic: 153826
 scriptlet: 33351
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 41m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1700-0, now
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, now
  https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-1, now
  adguard-cookies: 28468-30, now
  adguard-other-annoyances: 14131-7, now
  easylist-annoyances: 4320-105, now
  fanboy-cookiemonster: 49440-3742, now
  fanboy-social: 16118-15, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6602-137, now
  ublock-cookies-adguard: 913-913, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 1287-8, never
  TUR-0: 13115-7, now
  easylist: 79986-74, now
  easyprivacy: 43567-293, now
  plowe-0: 3786-1191, now
  ublock-badware: 7796-140, now
  ublock-filters: 36858-581, now
  ublock-privacy: 992-15, now
  ublock-unbreak: 2198-36, now
  urlhaus-1: 8160-0, now
filterset (user): [array of 1280 redacted]
trustedset:
 added: [array of 20 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 488 ms (selfie)
 maxAssetCacheWait: 244 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##.share-post
  ##.share-text
  ##.social-linkedin
  ##.social-pinterest
```
</details>

**Comment by D4niloMR** [comment]
Add:

`||haberprofil.biz/assets/*/vast.js$script`
