### ISSUE TITLE
Spotify playback issue

### ISSUE THREAD

**Issue by Luminous-Journey** [uBlockOrigin/uAssets#22258]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://open.spotify.com/
```

### Description

Sometimes (inconsistently) when using spotify, the songs start skipping and then stops after like 5/10 and does nothing, which repeats if you un-pause,  and spotify sends a notification that it cant play songs rn when you try and play a different song

The filter lists i have enabled are all of the ones included in the filter list tab except for the regional languages

### Other extensions used

No script (issue persists after being disabled)

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 296696
 cosmetic: 245786
 scriptlet: 49572
 html: 2263
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81893-7030, 5m
  adguard-mobile: 9100-102, 5m
  adguard-spyware-url: 1424-104, never
  adguard-spyware: 89719-26806, never
  block-lan: 56-0, never
  curben-phishing: 87031-27, never
  adguard-social: 22476-50, never
  adguard-cookies: 28468-41, never
  ublock-cookies-adguard: 913-7, never
  adguard-popup-overlays: 26881-974, never
  adguard-mobile-app-banners: 4920-20, never
  adguard-other-annoyances: 14131-419, never
  [10 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 37443-185, 1h.38m Δ
  ublock-badware: 7800-10, 1h.38m Δ
  ublock-privacy: 988-0, 1h.38m Δ
  ublock-unbreak: 2244-0, 1h.38m Δ
  ublock-quick-fixes: 148-0, 1h.38m Δ
  easylist: 79987-870, 1h.38m Δ
  easyprivacy: 43567-837, 1h.38m Δ
  urlhaus-1: 8165-0, 1h.38m
  plowe-0: 3781-1, 9d.1h.54m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 441 ms (selfie)
 maxAssetCacheWait: 254 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/22198
