### ISSUE TITLE
free-mp3-download.net: detection

### ISSUE THREAD

**Issue by 2014MU69** [uBlockOrigin/uAssets#22263]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://free-mp3-download.net/`

### Category

detection

### Description

I am using Iceraven on Android.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-01-29-21-30-21-09](https://github.com/uBlockOrigin/uAssets/assets/102027221/48e7b440-1ff8-4906-8015-ab43b6fccf0a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 117894
 cosmetic: 53053
 scriptlet: 18901
 html: 2059
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37798-188, 2m
  ublock-badware: 7795-10, 2m
  ublock-privacy: 988-0, 1m Δ
  ublock-unbreak: 2249-0, 2m
  ublock-quick-fixes: 153-0, 2m
  adguard-mobile: 9102-102, 15m
  easylist: 80233-755, 15m
  easyprivacy: 43567-870, 1m
  urlhaus-1: 8310-0, 1m
  plowe-0: 3786-1, 1m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8419 ms
 maxAssetCacheWait: 22 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(no-xhr-if, adsbygoogle, length:2000-3000)
```
</details>

**Comment by ItsProfessional** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

You didn't. Continue in #22067

**Comment by 2014MU69** [comment]
> > * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
> 
> You didn't. Continue in #22067

I did. I just didn't have enough GitHub experience to know that I am supposed to reply to a closed issue. Sorry.
