### ISSUE TITLE
top.gg: detection

### ISSUE THREAD

**Issue by GoldBee1818** [uBlockOrigin/uAssets#22265]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://top.gg/bot/432610292342587392/vote`

### Category

detection

### Description

Detects the only active adblocker and will not allow me to proceed with any function of the website until disabled.

### Other extensions used

Opera GX built in adblock that is disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 116587
 cosmetic: 45307
 scriptlet: 20267
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80281-14, 34m Δ
  easyprivacy: 43597-48, 34m Δ
  plowe-0: 3786-1177, now
  ublock-badware: 7799-136, 34m Δ
  ublock-filters: 36887-290, 34m Δ
  ublock-privacy: 992-6, 34m Δ
  ublock-quick-fixes: 133-8, 34m Δ
  ublock-unbreak: 2198-31, 34m Δ
  urlhaus-1: 8345-0, 34m
filterset (user): [empty]
userSettings:
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 676 ms (selfie)
 maxAssetCacheWait: 105 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
 extended:
  ###parent_nn_player
  ##+js(adjust-setTimeout, readyToVote, 12000)
```
</details>

**Comment by mapx-** [comment]
Do we need an account in order to reproduce the issue ?

**Comment by ItsProfessional** [comment]
@GoldBee1818 can you test:
```adb
top.gg##body:style(overflow: auto !important;)
top.gg##div[class^="chakra-modal__overlay"][style="opacity: 1;"]:style(display: none !important;)
top.gg##div[class^="chakra-modal__overlay"][style="opacity: 1;"] ~ div[data-focus-lock-disabled]:style(display: none !important;)
```
