### ISSUE TITLE
divar.ir: breakage

### ISSUE THREAD

**Issue by benyaminbeyzaie** [uBlockOrigin/uAssets#22260]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

`https://divar.ir/support/articles/display-ads-search`

### Description

Divar is one the largest online ad platform in Iran and support.divar, divar/support is about customer related issues, for example display-ads-search is the title of an article and there is no ads in this page, but uBlock blocks it, This is affecting our users trying to solve their problems.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116330
 cosmetic: 45295
 scriptlet: 20260
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80228-14, 7m
  easyprivacy: 43567-42, 7m
  plowe-0: 3786-1177, 7m
  ublock-badware: 7796-136, 7m
  ublock-filters: 36873-290, 7m
  ublock-privacy: 992-6, 7m
  ublock-quick-fixes: 146-24, 7m
  ublock-unbreak: 2198-31, 7m
  urlhaus-1: 8165-0, 7m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 162 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  divar.ir: 1
  divar.cloud: 6
  googletagmanager.com: 2

```
</details>

**Comment by ItsProfessional** [comment]
It's not even blocked on a default configuration of uBO.

**Comment by benyaminbeyzaie** [comment]
[divar.ir/support/articles/display-ads-search](https://divar.ir/support/articles/display-ads-search)

This is blocked because it contains "ads" in the url

**Comment by D4niloMR** [comment]
Works with `@@||divar.ir/support/faq/question/display-ads-search/`

**Comment by D4niloMR** [comment]
On `https://divar.ir/support/articles/display-ads-search`

<details><summary>
Whitelisting</summary>
<p>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/3b13aedf-b744-4b44-b7f7-8686b0297714)


</p>
</details> 

<details><summary>
not whitelisting</summary>
<p>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/d68e6333-01f2-4f1e-8d87-83854430a488)



</p>
</details>

**Comment by mapx-** [comment]
```
/display-ads-$from=~google.co.uk|~google.com|~google.com.au,badfilter
/display-ads-$domain=~google.co.uk|~google.com|~google.com.au|~divar.ir
```

@ryanbr
