### ISSUE TITLE
[unknown]: popups

### ISSUE THREAD

**Issue by long213** [uBlockOrigin/uAssets#22269]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wqtn4stb5jv6mepsiktgbd0a.gossipinvest.com/landers/KR/bank-of-korea-sues-seung-cheol-lee/index.php?lp_key=170655c3dcc5d8c488c6d563658d7a1dcc1c599834&on=GPT%202.0%20Definity`

### Category

ads

### Description

Invest ads

### Other extensions used

Adblock Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 117860
 cosmetic: 48805
 scriptlet: 20419
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 5044-10, 1h.15m
  easylist: 80281-59, 1h.15m Δ
  easyprivacy: 43597-58, 1h.15m Δ
  plowe-0: 3786-1192, now
  ublock-badware: 7799-136, 1h.15m Δ
  ublock-filters: 36887-294, 1h.15m Δ
  ublock-privacy: 992-8, 1h.15m Δ
  ublock-quick-fixes: 133-8, 1h.15m Δ
  ublock-unbreak: 2198-31, 1h.15m Δ
  urlhaus-1: 8310-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 413 ms (selfie)
 maxAssetCacheWait: 137 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
- You have to provide the original page and not the redirected spam page
- remove Adblock Plus => it's only source of conflicts with uBO
