### ISSUE TITLE
xyzsports111.xyz: ads

### ISSUE THREAD

**Issue by mustihoca** [uBlockOrigin/uAssets#22274]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.xyzsports111.xyz/player.php?channel=1`

### Category

streaming adds

### Description

Hello,

I'm encountering an issue with ads that appear before the streaming starts on a platform. I need assistance in creating effective filters to bypass these ads. Additionally, the domain names for these ads seem to be dynamically changing in a sequential manner, such as xyzsports111.xyz, xyzsports112.xyz, and so on.

Problem Details:

    Pre-roll Ads: Two ads are displayed before the streaming begins, and I cannot proceed without watching them.
    Dynamic Domain Names: The domain names for these ads keep changing in a sequential pattern (e.g., xyzsports111.xyz, xyzsports112.xyz).

Additional Information:

    I am using uBlock Origin for ad blocking.

Ads resources:
https://odin.fc6abcee4cf2.shop/0/master.m3u8?v=ads1
https://odin.fc6abcee4cf2.shop/0/master.m3u8?v=ads2

Request for Help:
I am seeking guidance on how to create effective filters to bypass these pre-roll ads. Any assistance or suggestions would be greatly appreciated. Thank you!

### Other extensions used

ı don't carry about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 118148
 cosmetic: 290459
 scriptlet: 22044
 html: 2058
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/mstflgz/FiltreListem/main/filtreler.txt: 236946-21, 38m
 default:
  user-filters: 45-0, never
  ublock-filters: 37460-161, 1h.2m Δ
  ublock-badware: 7808-10, 1h.2m Δ
  ublock-privacy: 988-0, 1h.2m Δ
  ublock-unbreak: 2246-0, 1h.2m Δ
  ublock-quick-fixes: 134-0, 1h.2m Δ
  easylist: 80393-731, 1h.2m Δ
  easyprivacy: 43604-844, 1h.2m Δ
  urlhaus-1: 8325-0, 1h.2m
  plowe-0: 3786-1, 38m
  TUR-0: 12953-63, 38m
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 17 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 818 ms (selfie)
 maxAssetCacheWait: 314 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##[href="https://rebrand.ly/Bahisbeyselcuksport"]
```
</details>

**Comment by stephenhawk8054** [comment]
It's a Turkish site but I need `trusted-set` for it:

```adb
xyzsports111.xyz##+js(trusted-set, adsConfigs, {"value": [{"enabled":0}]})
```

---

@Yuki2718 @gorhill Regarding domains with regex, I see that there are many filters with the format of `[$domain=/^inattv\d+\.xyz$/]##` in Adguard Turkish list since it's very popular for the domains to have those formats in Turkey. But those are all marked as invalid

Should we start using regex for `##` filters?

```adb
/^www\.xyzsports\d+\.xyz/##+js(trusted-set, adsConfigs, {"value": [{"enabled":0}]})
```

**Comment by gorhill** [comment]
If there is no other solution... Or maybe we fall back on using regexes when more similar reports justify doing so.

Ultimately I guess I should adapt the parser to be able to deal with that AG's specific syntax.

**Comment by stephenhawk8054** [comment]
> Ultimately I guess I should adapt the parser to be able to deal with that AG's specific syntax.

I think this would be better, as those filters would be only activated in regional lists and won't affect the performance of users who don't use that list.

I will first address only `xyzsports111.xyz` since other domains redirect to it.

**Comment by stephenhawk8054** [comment]
Oh, I forgot it's `trusted-set` so it could not be addressed in regional list, so if we use regex for it, we would address it in uAssets default anyways.

**Comment by stephenhawk8054** [comment]
The `trusted-set` is pretty simple though, but since it's involved array, I can't use normal `set` for it

**Comment by stephenhawk8054** [comment]
I know

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/FiltersCompiler/issues/204

**Comment by stephenhawk8054** [comment]
> `[$domain=/(^\|.+\.)xyzsports\d+\.xyz/]#$#.table-area { visibility: hidden !important; }`

It appears normally for me:

![Image](https://github.com/user-attachments/assets/0c02fb18-439a-4303-a590-d96a8d07e320)

**Comment by stephenhawk8054** [comment]
> This filter rule does not work in uBO

How to test it?

**Comment by stephenhawk8054** [comment]
It's because of `(^\|.+\.)` in that regex. If I remove it,

```adb
[$domain=/xyzsports\d+\.xyz/]#$#.table-area { visibility: hidden !important; }
```

works for me. I don't know why there's `(^\|.+\.)` in that regex.

If you put `(^\|.+\.)xyzsports\d+\.xyz` to https://regex101.com/ , it doesn't match `https://xyzsports237.xyz/`

**Comment by stephenhawk8054** [comment]
cc @Yuki2718 @gorhill Sorry, can you check the above?

**Comment by gwarser** [comment]
Should probably be `(^|.+\.)xyzsports\d+\.xyz` - some AdGuard specific escape sequence?

**Comment by gwarser** [comment]
Hmmm, it "matches the `$domain` option", so pipes need to be escaped because they work as separators in option values.

https://adguard.com/kb/general/ad-filtering/create-own-filters/#non-basic-domain-modifier

?

But there are no regex examples. Only `$path` has some which does not match - `[$path=/\\/(sub1|sub2)\\/page\\.html/]##.textad`

**Comment by Yuki2718** [comment]
No idea, it looks https://github.com/AdguardTeam/AdguardFilters/commit/c2ac2868209b0eaca203d8e8fd20cf9106c9ff3b was the first commit with this part. @AdamWr

**Comment by gorhill** [comment]
uBO support regex literal without needing to escape, so there is no need to escape `(^\|.+\.)` => `(^|.+\.)`.

**Comment by Yuki2718** [comment]
It seems there are many filters with `(^|.+\.)` including but not limited to Turkish filter, I'm not sure what fix will be the best - too many to fix by `!# if`.

**Comment by gorhill** [comment]
> I'm not sure what fix will be the best

If the escaping is only with `\|`, then I could add a special unescaping applied only when the AG syntax `[domain=...]` is used.

**Comment by AdamWr** [comment]
As far as I understand, it looks like that unfortunately it's not only `|` but also `]` and `,` (I'm not sure if there are more characters).
There is probably another related issue - https://github.com/AdguardTeam/tsurlfilter/issues/121

**Comment by Yuki2718** [comment]
Hmm, then I think `!# if` ~ `!# else` will be the best fix, if filters without `(^|.+\.)` can correctly be distributed to uBO.

**Comment by kodiakhub** [comment]
`dizi15.life`:

<details><summary>Screenshot</summary>
<p>

<img width="1438" height="198" alt="Image" src="https://github.com/user-attachments/assets/984ef578-64a4-4084-8f2f-f2f938c6ccd2" />

<img width="353" height="407" alt="Image" src="https://github.com/user-attachments/assets/3eb348a0-df72-4382-88e5-735923d96107" />

</p>
</details>

For uBO:

```adb
[$domain=/dizi\d+\.life/]##.banner-container
or
/dizi\d+\.life/##.banner-container
```

Does not work. Why? 🤔

**Comment by stephenhawk8054** [comment]
The filter in [`Adguard Turkish`](https://filters.adtidy.org/extension/ublock/filters/13.txt) list is

```adb
[$domain=/(^\|.+\.)dizi\d+\.life/]##.banner-container
```

not

```adb
[$domain=/dizi\d+\.life/]##.banner-container
```

which causes it not work.

**Comment by kodiakhub** [comment]
> The filter in [`Adguard Turkish`](https://filters.adtidy.org/extension/ublock/filters/13.txt) list is
> 
> [$domain=/(^\|.+\.)dizi\d+\.life/]##.banner-container
> not
> 
> [$domain=/dizi\d+\.life/]##.banner-container
> which causes it not work.

I mean yeah, it's not working on `my filters`. 🤔

**Comment by stephenhawk8054** [comment]
It works on my side:

<img width="2520" height="1608" alt="Image" src="https://github.com/user-attachments/assets/09be4a42-f8e8-4f17-889e-dc91484a21b3" />

**Comment by kodiakhub** [comment]
> It works on my side:

Oh i see, it works for firefox, but not chrome. 🤔

**Comment by stephenhawk8054** [comment]
It still works for me on chromium

<img width="2520" height="1608" alt="Image" src="https://github.com/user-attachments/assets/bb201f1a-9d31-45d0-b966-a7ccc47c9d79" />

**Comment by kodiakhub** [comment]
> It still works for me on chromium

Alright, after resetting UBO, I re-added the relevant regex filter rule and it worked. However, I still couldn't figure out what caused the previous issue. I re-applied the same settings as before, enabling some and disabling others, and added the custom filter again, but I just couldn't identify the source of the issue. I apologize.
