### ISSUE TITLE
top.gg: ads

### ISSUE THREAD

**Issue by ffsmyusernameistaken** [uBlockOrigin/uAssets#22277]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://top.gg/bot/664508672713424926/vote`

### Category

ads

### Description

Today uBlock stopped blocking ads on top.gg. I updated all filters, it didn't fix the problem.

### Other extensions used

TamperMonkey, PlanetVPN, Session Buddy, The Marvellous Suspender, WebRTC Network Limiter

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_2024-01-31_10-34-55](https://github.com/uBlockOrigin/uAssets/assets/26306446/5867ac38-d83e-402d-83a0-93434d043eec)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 109
filterset (summary):
 network: 117892
 cosmetic: 119767
 scriptlet: 39856
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1703-0, 2m
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 23268-96, 2m
  adguard-generic: 81917-667, 2m
 default:
  user-filters: 4-0, never
  RUS-0: 40170-2664, 2m
  easylist: 80381-1962, 2m Δ
  plowe-0: 3786-415, 2m
  ublock-badware: 7804-321, 2m Δ
  ublock-filters: 36857-3593, 2m
  ublock-privacy: 992-12, 2m
  ublock-quick-fixes: 138-8, 2m
  ublock-unbreak: 2200-84, 2m
  urlhaus-1: 8415-0, 2m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 16 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1310 ms (selfie)
 maxAssetCacheWait: 389 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  dn0qt3r0xannq.cloudfront.net: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ###ad-container
  ##+js(adjust-setTimeout, readyToVote, 12000)
```
</details>

**Comment by ItsProfessional** [comment]
It's self promotion.

**Comment by ffsmyusernameistaken** [comment]
> It's self promotion.
But it was blocked before.

**Comment by ffsmyusernameistaken** [comment]
> It's self promotion.

But it was blocked before.

**Comment by stephenhawk8054** [comment]
Could be 3rd party ads before or overzealous blocking

**Comment by stephenhawk8054** [comment]
We don't block self-promotion. What happens if you click on the links there?

**Comment by stephenhawk8054** [comment]
As the banners are still big and repetitive, they are addressed in `uBlock filters – Annoyances` list. You can enable that list or add this as a custom filter

```adb
top.gg##[class*="AdContainer"]
```
