### ISSUE TITLE
southpark.lat: detection

### ISSUE THREAD

**Issue by FrapzHaash** [uBlockOrigin/uAssets#22286]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.southpark.lat/`

### Category

detection

### Description

detected

### Other extensions used

nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80805708/585b33c6-8ec8-48e6-a3ec-fc61139db8a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116441
 cosmetic: 45503
 scriptlet: 18801
 html: 2064
listset (total-discarded, last-updated):
 default:
  user-filters: 97-5, never
  ublock-filters: 37445-142, now
  ublock-badware: 7808-10, now
  ublock-privacy: 989-0, now
  ublock-unbreak: 2247-0, now
  ublock-quick-fixes: 144-0, now
  easylist: 80103-644, now
  easyprivacy: 43614-839, now
  urlhaus-1: 8365-0, now
  plowe-0: 3786-1, now
filterset (user): [array of 97 redacted]
trustedset:
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 277 ms (selfie)
 maxAssetCacheWait: 82 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 39
 network:
  cbsaavideo.com: 6
  cbsivideo.com: 13
  demdex.net: 2
  imasdk.googleapis.com: 1
  mtvnservices.com: 2
  newrelic.com: 4
  ns1p.net: 2
  paramount.tech: 9
```
</details>

**Comment by D4niloMR** [comment]
Enable AdGuard spanish/portuguese list and test again.

**Comment by FrapzHaash** [comment]
works now, ty
