### ISSUE TITLE
notion.so: breakage

### ISSUE THREAD

**Issue by cai-tan** [uBlockOrigin/uAssets#22283]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.notion.so/`

### Category

breakage

### Description

See screenshots. Table entries cannot be opened from the table view. Technically, they can be opened as pages on their own, but the button to do so from the "side peek" is missing, as is everything from the side peek window. I would have to right-click the entry to open their page, which breaks workflow.

### Other extensions used

Dark Reader (configured to whitelist; Notion.so is not on the whitelist, therefore this is inactive)
Indie Wiki Buddy + wiki.gg Redirect (these do not have permission to modify Notion.so by design)
FFZ + BTTV + Twitch Chat Pronouns (these only have permission to modify Twitch.tv by design)
Foxy Gestures (mouse gestures for Firefox) (issue was not fixed by disabling)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Normal behavior (uBO disabled)
![firefox_aOaLZedSQo](https://github.com/uBlockOrigin/uAssets/assets/83613248/970c9f3f-facf-4480-82de-7873c2f795e5)
Broken Behavior (uBO enabled)
![firefox_PbS2uGHXHH](https://github.com/uBlockOrigin/uAssets/assets/83613248/1cb44860-3aca-4c7a-9d48-8e5560b859f5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 116361
 cosmetic: 45381
 scriptlet: 18827
 html: 2061
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 37439-274, 1h.43m Δ
  ublock-badware: 7808-10, 1h.43m Δ
  ublock-privacy: 989-0, 1h.43m Δ
  ublock-unbreak: 2246-0, 1h.43m Δ
  ublock-quick-fixes: 139-0, 1h.43m Δ
  easylist: 80061-545, 1h.43m Δ
  easyprivacy: 43606-884, 1h.43m Δ
  urlhaus-1: 8415-0, now
  plowe-0: 3786-1, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7098 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 982
 network:
  notion.so: 25
  bing.com: 4
  sentry.io: 57
  splunkcloud.com: 896
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||splunkcloud.com/services/collector/$badfilter
```

**Comment by cai-tan** [comment]
nevermind, turns out I lied and I actually did have a custom rule on Notion, I just forgot
