### ISSUE TITLE
iceland.co.uk: breakage

### ISSUE THREAD

**Issue by linuxgirl22** [uBlockOrigin/uAssets#22281]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.iceland.co.uk/
```

### Description

Unable to login ... when enter email address and password, then press the button, nothing happens; not even page attempting to run anything. Only turning off uBlock Origin enabled login.

### Other extensions used

uMatrix (didn't unblock anything via uMatrix on iceland site)
Canvasblocker (not running on iceland site)
ClearURLs
Decentraleyes
javascript control (javascript enabled for iceland site)
... had to tick 'not using other' at top as was compulsory and not clicking that blocked being able to submit this issue. Only turning off uBlock Origin enabled login to work on the iceland site. 

Also running fixed zoom, privacy redirect, and Librewolf update notifier.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 208259
 cosmetic: 46610
 scriptlet: 20224
 html: 2064
listset (total-discarded, last-updated):
 default:
  user-filters: 52-21, never
  ublock-filters: 37439-162, 1m
  ublock-badware: 7808-10, 1m
  ublock-privacy: 989-0, 1m
  ublock-unbreak: 2246-1, 1m Δ
  ublock-quick-fixes: 139-0, 1m
  easylist: 80061-716, 1m
  adguard-spyware-url: 1435-103, now
  easyprivacy: 43606-842, now
  urlhaus-1: 8415-0, now
  curben-phishing: 87855-28, now
  plowe-0: 3786-1, now
  LegitimateURLShortener: 2558-160, 1m
  bpc-paywall-filter: 1036-0, now
  AntiPaywall: 1939-14, now
filterset (user): [array of 52 redacted]
trustedset:
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  opera-scheme
  vivaldi-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  iceland.co.uk: 4
  cquotient.com: 2
  go-mpulse.net: 1
  googletagmanager.com: 1
  techlab-cdn.com: 4


```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
iceland.co.uk##+js(set, fp, {})
iceland.co.uk##+js(set, fp.t, noopFunc)
iceland.co.uk##+js(set, fp.s, noopFunc)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by linuxgirl22** [comment]
Works perfectly! Thank you very much for such a quick and helpful response. Much appreciate.
