### ISSUE TITLE
app.vaia.com: ads

### ISSUE THREAD

**Issue by aixno** [uBlockOrigin/uAssets#22285]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.vaia.com/studyset/19251091/flashcards/create?trackingSource=studyset_flashcards_overview`

### Category

ads

### Description

Ads are not blocked and manual element blocking does not block the ads either. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 116544
 cosmetic: 47459
 scriptlet: 18813
 html: 2067
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37411-123, 24m Δ
  ublock-badware: 7808-10, 24m Δ
  ublock-privacy: 989-0, 24m Δ
  ublock-unbreak: 2246-0, 24m Δ
  ublock-quick-fixes: 142-0, 24m Δ
  easylist: 80094-642, 24m Δ
  easyprivacy: 43606-867, 24m Δ
  urlhaus-1: 8330-0, 1h.33m
  plowe-0: 3786-1, 21m
  FIN-0: 2263-1, 21m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4505 ms
 maxAssetCacheWait: 23 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 158
 network:
  adform.net: 9
  amplitude.com: 76
  b-cdn.net: 3
  doubleclick.net: 24
  facebook.net: 1
  googlesyndication.com: 3
  googletagmanager.com: 2
  lr-in.com: 1
  paypal.com: 2
  sentry.io: 37
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by MrTahWasTaken** [comment]
Hold on!
I made a 48-hour burner account I'm willing to share, because I have the same problem too.
I'll also copy-paste this description I made:

The website has ads, specifically when reviewing flashcards. After reviewing them for a while, one or two ads may pop up, before you may continue your previous activity.
Sometimes, they may also popup throughout the main menus, though the big ones on the right are already blocked (it does leave some big blank area though).
