### ISSUE TITLE
free-mp3-download.net: detection

### ISSUE THREAD

**Issue by ilovethensa** [uBlockOrigin/uAssets#22282]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://free-mp3-download.net
```

### Description

The page detects an adblock is used and tells the user to disable it

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![20240131_11h05m20s_grim](https://github.com/uBlockOrigin/uAssets/assets/145558184/ffd40ff3-3225-47b6-a8bb-a85d31630042)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 309193
 cosmetic: 246243
 scriptlet: 49575
 html: 2269
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81891-7043, 3d.10h.35m
  adguard-mobile: 9100-103, 3d.10h.35m
  adguard-spyware-url: 1424-103, 3d.10h.35m
  adguard-spyware: 89719-26977, 3d.10h.35m
  block-lan: 56-0, 3d.10h.35m
  curben-phishing: 87855-28, 9m
  adguard-social: 22476-877, 3d.10h.35m
  adguard-cookies: 28468-61, 3d.10h.35m
  ublock-cookies-adguard: 912-0, 3d.10h.35m
  adguard-popup-overlays: 26884-1621, 3d.10h.35m
  adguard-mobile-app-banners: 4920-1074, 3d.10h.35m
  adguard-other-annoyances: 14131-332, 3d.10h.35m
  [12 lists not shown]: [too many]
 default:
  user-filters: 3-2, never
  ublock-filters: 37439-487, 2h.5m Δ
  ublock-badware: 7808-10, 2h.5m Δ
  ublock-privacy: 989-0, 2h.5m Δ
  ublock-unbreak: 2246-1, 2h.5m Δ
  ublock-quick-fixes: 139-0, 2h.5m Δ
  easylist: 80061-1006, 2h.5m Δ
  easyprivacy: 43606-1105, 2h.5m Δ
  urlhaus-1: 8415-0, 9m
  plowe-0: 3786-1, 3d.11h.10m
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1169 ms (selfie)
 maxAssetCacheWait: 772 ms
 cacheBackend: indexedDB

```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/22067

**Comment by JobcenterTycoon** [comment]
Site is broken. I get detection even without adblocker.
