### ISSUE TITLE
kazwire.com: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#22284]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kazwire.com/`

### Category

ads

### Description

Still sometimes shows a ad or the advertisement text

### Other extensions used

- Privacy badger
- Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/ddb981af-3e63-4b1a-b2ec-8742453b7e29)

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/c04d54d6-25cb-4938-89ab-63ba49739ea2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 281805
 cosmetic: 45633
 scriptlet: 19532
 html: 2061
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 90841-26843, now
  block-lan: 56-0, now
  dpollock-0: 11633-466, now
 default:
  user-filters: 2-0, never
  ublock-filters: 37439-303, 24m Δ
  ublock-badware: 7808-10, 24m Δ
  ublock-privacy: 989-0, 24m Δ
  ublock-unbreak: 2246-1, 24m Δ
  ublock-quick-fixes: 139-0, 24m Δ
  easylist: 80061-714, 24m Δ
  adguard-spyware-url: 1435-103, now
  easyprivacy: 43606-950, 24m Δ
  urlhaus-1: 8330-0, now
  curben-phishing: 87840-28, now
  plowe-0: 3786-1, now
  LegitimateURLShortener: 2558-160, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1314 ms (selfie)
 maxAssetCacheWait: 316 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  wgplayer.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
kazwire.com##h3.tracking-widest
```

@ryanbr
