### ISSUE TITLE
[nsfw] komikcast.lol: ads

### ISSUE THREAD

**Issue by ankarakata** [uBlockOrigin/uAssets#22290]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://komikcast.lol/`

### Category

ads

### Description

(website contain nsfw content)

still show ads 
![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/e683625b-60a6-406c-9be8-352c2da79b39)

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/68a5d217-7129-4863-bb43-f30f8646b147)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 117
filterset (summary):
 network: 116404
 cosmetic: 44701
 scriptlet: 20242
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 79340-16, now
  easyprivacy: 43614-48, now
  plowe-0: 3786-1177, now
  ublock-badware: 7804-136, never
  ublock-filters: 36874-210, now
  ublock-privacy: 993-6, now
  ublock-quick-fixes: 149-8, now
  ublock-unbreak: 2200-31, now
  urlhaus-1: 8365-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 933 ms
 maxAssetCacheWait: 6 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  komikcast.lol: 2
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  histats.com: 1
  outbrain.com: 1
  taboola.com: 1
  visivefluxing.com: 1
 extended:
  ##+js(addEventListener-defuser, load, onload)
  ##+js(abort-on-property-read, open)
  ##+js(abort-current-script, JSON.parse, Promise)
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `ABPindo` list
