### ISSUE TITLE
polygonscan.com: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#22293]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://polygonscan.com/tx/0x79fa8e10c8ef79ca3568a8c1b8d761acb48ee220e46bb36488871bc2c4cae1fc`

### Category

ads

### Description

Still shows a "sponsored" section on transaction details

### Other extensions used

- Privacy badger
- Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/6be65b51-7f47-48f2-9c23-cbf0abe6d450)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 282788
 cosmetic: 45623
 scriptlet: 19518
 html: 2065
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 90847-26853, now
  block-lan: 56-0, now
  dpollock-0: 11635-466, now
 default:
  user-filters: 3-0, never
  ublock-filters: 37425-143, 13m Δ
  ublock-badware: 7808-10, 13m Δ
  ublock-privacy: 990-0, 13m Δ
  ublock-unbreak: 2251-1, 13m Δ
  ublock-quick-fixes: 144-0, 13m Δ
  easylist: 80051-814, 13m Δ
  adguard-spyware-url: 1434-103, now
  easyprivacy: 43615-933, 13m Δ
  urlhaus-1: 8480-0, 1h.50m
  curben-phishing: 88580-27, 1h.50m
  plowe-0: 3786-1, now
  LegitimateURLShortener: 2558-160, 1h.50m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 962 ms (selfie)
 maxAssetCacheWait: 397 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  coinzillatag.com: 1
  etherscan.com: 2
  googletagmanager.com: 1
 extended:
  ##[data-revive-zoneid]
```
</details>

**Comment by D4niloMR** [comment]
Report it at https://github.com/easylist/easylist/issues

**Comment by ItsProfessional** [comment]
@ryanbr
