### ISSUE TITLE
top.gg: ads

### ISSUE THREAD

**Issue by Dhruv1002** [uBlockOrigin/uAssets#22292]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://top.gg/bot/824029844496056364/vote`

### Category

ads

### Description

there is a pop up add on the bottom of the screen which is like hard to detect by ublock origin as it is like a part of the website

### Other extensions used

Bard next to google results
Optisearch
Bitdefender Anti-Tracker {I tried opening website with this disabled but the problem still persisted.}

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/96822294/23445d03-09fb-43c8-8fe0-eba46ac4446c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116405
 cosmetic: 44704
 scriptlet: 20246
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 79340-16, 6m Δ
  easyprivacy: 43614-48, 6m Δ
  plowe-0: 3786-1177, now
  ublock-badware: 7804-136, 6m Δ
  ublock-filters: 36874-210, 6m Δ
  ublock-privacy: 994-6, 6m Δ
  ublock-quick-fixes: 149-8, 6m Δ
  ublock-unbreak: 2204-31, 6m Δ
  urlhaus-1: 8365-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 821 ms (selfie)
 maxAssetCacheWait: 371 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  top.gg: 2
  dn0qt3r0xannq.cloudfront.net: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##+js(adjust-setTimeout, readyToVote, 12000)
```
</details>

**Comment by ItsProfessional** [comment]
It's self promotion, not an ad.
