### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by alexlolxp** [uBlockOrigin/uAssets#22299]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Description

Videos uploaded to reddit cannot be played when uBlock Origin is enabled. Disabling fixes the issue

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116530
 cosmetic: 45369
 scriptlet: 18813
 html: 2064
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37421-142, 37m Δ
  ublock-badware: 7808-10, 37m Δ
  ublock-privacy: 991-77, 37m Δ
  ublock-unbreak: 2251-0, 37m Δ
  ublock-quick-fixes: 144-0, 37m Δ
  easylist: 80063-644, 37m Δ
  easyprivacy: 43615-839, 37m Δ
  urlhaus-1: 8480-0, now
  plowe-0: 3786-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2521 ms (selfie)
 maxAssetCacheWait: 424 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  reddit.com: 1
  ad-delivery.net: 1
  redditmedia.com: 1
  redditstatic.com: 3
 extended:
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(abort-on-property-write, STICKY_CANARY)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
I uploaded a video to a subreddit and the video plays normally. Test in a new Firefox profile with only uBO and its default settings.

Also, please describe the steps to reproduce in the most details as possible.
