### ISSUE TITLE
anime sites problem on firefox

### ISSUE THREAD

**Issue by strikenf** [uBlockOrigin/uAssets#22302]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://gogoanime3.co/
https://aniwave.to/home
https://animesuge.to/home
https://aniwatch.to/
```

### Description

cannot play and watch any videos 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![problem](https://github.com/uBlockOrigin/uAssets/assets/48569735/52ea1c8a-f93a-4350-98f9-9e292ace50b7)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 139018
 cosmetic: 157121
 scriptlet: 40232
 html: 2069
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82330-5883, 30m
  easylist-annoyances: 4320-99, 3d.9h.23m
  easylist-chat: 180-0, 4d.23h.24m
  fanboy-cookiemonster: 65174-15756, 1d.23h.23m
  easylist-newsletters: 6905-14, 3d.9h.23m
  easylist-notifications: 2912-8, 3d.9h.23m
  fanboy-social: 16122-8, 3d.9h.24m
 default:
  user-filters: 2-0, never
  ublock-filters: 37431-106, 1h.30m Δ
  ublock-badware: 7808-10, 1h.30m Δ
  ublock-privacy: 991-0, 1h.30m Δ
  ublock-unbreak: 2252-1, 1h.30m Δ
  ublock-quick-fixes: 147-7, 1h.30m Δ
  easylist: 80069-670, 1h.30m Δ
  easyprivacy: 43615-957, 1h.30m Δ
  urlhaus-1: 8230-0, 26m
  plowe-0: 3786-1, 36m
filterset (user): [array of 2 redacted]
hostRuleset:
 added: [array of 78 redacted]
userSettings:
 advancedUserEnabled: true
 autoUpdate: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 186 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  bidgear.com: 4
  disqus.com: 1
  embtaku.pro: 1
  google.com: 1
  googletagmanager.com: 1
 extended:
  ##.adsverting


```
</details>

**Comment by stephenhawk8054** [comment]
Websites work normally for me. Test again in a new Firefox profile with only uBO and its default settings.

Also, please describe the steps to reproduce in the most details as possible.

**Comment by strikenf** [comment]
After trying new Firefox profile with only uBO and its default settings, it works perfectly fine.

**Comment by stephenhawk8054** [comment]
Then please check your current profile settings and uBO configurations yourself.

**Comment by strikenf** [comment]
The only difference is I unblock the 3rd-party frames. I used to block it and I could still watch the anime episodes with no issue until today.

**Comment by stephenhawk8054** [comment]
The videos are hosted in 3rd-party sites embedded in those websites, aka 3rd-party frames. Blocking them will block the videos.

Please always address what custom configurations you are using to not waste volunteers' time.

> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

**Comment by ron77950** [comment]
I had a similar issue as this and fixed mine by turning off the filters at Filters List > Annoyances > uBlock filters - Annoyances

**Comment by stephenhawk8054** [comment]
@ron77950 Can you give exact URLs where you see the issue?
