### ISSUE TITLE
startpage.com: detection

### ISSUE THREAD

**Issue by rgarcianfm** [uBlockOrigin/uAssets#22304]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.startpage.com/sp/search`

### Category

detection

### Description

On all startpage.com search results, Ublock is detected and ads are shown in the lead section

### Other extensions used

Wappalyzer, Grammarly, Ahrefs, CopyPlainText, Fireshot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116320
 cosmetic: 45373
 scriptlet: 18818
 html: 2069
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 37432-222, now
  ublock-badware: 7808-10, now
  ublock-privacy: 991-0, now
  ublock-unbreak: 2252-0, now
  easylist: 80098-564, now
  easyprivacy: 43617-839, now
  plowe-0: 3786-1, now
  urlhaus-1: 8230-0, now
  ublock-quick-fixes: 147-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 192 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1011 ms (selfie)
 maxAssetCacheWait: 264 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  startpage.com: 6
 extended:
  ##.ad.widget
```
</details>

**Comment by anonymous721** [comment]
I'm getting this as well, inconsistently. If I re-search or simply refresh the page, the ads disappear. But next time I search something they'll usually be back.
