### ISSUE TITLE
japscan.lol: ads

### ISSUE THREAD

**Issue by guant36** [uBlockOrigin/uAssets#22307]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.japscan.lol/`

### Category

ads

### Description

ads display and open a new tab

### Other extensions used

pop up blocker pro

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/136157300/c93442b5-62b4-4323-a980-9e6537ff6fe4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 135666
 cosmetic: 52386
 scriptlet: 20423
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 27131-40, 5m
  easylist: 80061-192, 5m
  easyprivacy: 43615-308, 5m
  plowe-0: 3786-1187, 5m
  ublock-badware: 7804-151, 5m
  ublock-filters: 36915-280, 5m
  ublock-privacy: 995-6, 5m
  ublock-quick-fixes: 152-8, 5m
  ublock-unbreak: 2206-35, 5m
  urlhaus-1: 8230-0, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1304 ms
 maxAssetCacheWait: 5 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(abort-current-script, document.addEventListener, /getCompu…
  ##+js(no-setTimeout-if, detectImgLoad)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||japscan.lol/ujs/$script
japscan.lol##+js(aeld, click, sessionStorage)
japscan.lol###stickyBanner
```

@Yuki2718 For AdGuard Français list?

**Comment by huyszn** [comment]
I think the `Toutes tes copines AI` section on the main page is an ad. There is also an ad banner on the top of pages like `https://www.japscan.lol/lecture-en-ligne/jujutsu-kaisen/249/`

**Comment by Yuki2718** [comment]
Maybe `.japscan.lol##.card.copines`.

**Comment by justinbridouille** [comment]
created an error on webtoon types which are no longer displayed 
exemple: https://www.japscan.lol/lecture-en-ligne/omniscient-reader-s-viewpoint/1/1.html

**Comment by Camilleri-Nathan** [comment]
> created an error on webtoon types which are no longer displayed exemple: https://www.japscan.lol/lecture-en-ligne/omniscient-reader-s-viewpoint/1/1.html
> 
> cause : /japs/*_1200x2000_banner_fr.jpg$domain=japscan.lol

I have the same issue, i wonder how can i fix it

**Comment by justinbridouille** [comment]
> > created an error on webtoon types which are no longer displayed exemple: https://www.japscan.lol/lecture-en-ligne/omniscient-reader-s-viewpoint/1/1.html
> > cause : /japs/*_1200x2000_banner_fr.jpg$domain=japscan.lol
> 
> I have the same issue, i wonder how can i fix it

met juste ca dans tes filtres pour réactiver les bannières en attendant qu'ils corrigent :  
@@japscan.lol/imgs/japs/*_1200x2000_banner_fr.jpg$image
et tu peut mettre ca pour enlever la première pub sur les webtoon: 
www.japscan.lol###d-img-0
mais j'ai pas réussit a enlever les copines AI sur les pages de manga

**Comment by Camilleri-Nathan** [comment]
> > > created an error on webtoon types which are no longer displayed exemple: https://www.japscan.lol/lecture-en-ligne/omniscient-reader-s-viewpoint/1/1.html
> > > cause : /japs/*_1200x2000_banner_fr.jpg$domain=japscan.lol
> > 
> > 
> > I have the same issue, i wonder how can i fix it
> 
> i found how to correct it :
> 
> @@japscan.lol/imgs/japs/__1200x2000_banner_fr.jpg$image,domain=www.japscan.lol ||www.japscan.lol/imgs/japs/__1200x2000_banner_fr.jpg$xhr,domain=www.japscan.lol [www.japscan.lol###d-img-0](http://www.japscan.lol###d-img-0)
> 
> I think there was a detection in a script for the xhr

Can you show me a screenshot of how you did it?

**Comment by justinbridouille** [comment]
> Can you show me a screenshot of how you did it?
Did what ?

**Comment by Yuki2718** [comment]
Just update French list.
