### ISSUE TITLE
bluemediadownload.lat: detection

### ISSUE THREAD

**Issue by Gho24** [uBlockOrigin/uAssets#22301]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://bluemediadownload.lat/url-generator-1.php?url=SDUS9bRvhba8BF9dQAj5ctxRtYJoR0C0VYKh5jHUqc5yEx/4YVh99iZFkTnsg0c0
```

### Description

When visiting any page from bluemedia's new address ("https://bluemediadownload.lat"), adblock is detected, a ton of ads is shown, and page functionality is denied.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![BlueMediaDownload_lat](https://github.com/uBlockOrigin/uAssets/assets/153461932/c13f2951-326b-4391-9873-b47c2101537c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.47.2
Firefox: 89
filterset (summary): 
  network: 105162
  cosmetic: 44155
  scriptlet: 19765
  html: 1142
listset (total-discarded, last-updated): 
  added: 
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, 46d.5h.24m
  default: 
    user-filters: 0-0, never
    ublock-filters: 37497-225, 38d.10h.15m
    ublock-badware: 7547-11, 38d.10h.14m
    ublock-privacy: 1007-81, 46d.5h.24m
    ublock-unbreak: 2215-2, 46d.5h.24m
    ublock-quick-fixes: 134-25, 46d.5h.24m
    easylist: 75822-668, 46d.5h.24m
    easyprivacy: 33114-808, 46d.5h.24m
    urlhaus-1: 11000-0, 46d.5h.24m
    plowe-0: 3781-1, 46d.5h.24m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms
  maxAssetCacheWait: 300 ms

```
</details>

**Comment by stephenhawk8054** [comment]
No need to change the title. We all see new comments. Wait about 1 more hour and update again.

If you **REALLY** want to manually update, click on [this link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=240204)

**WARNING**: This will break your filter lists' differential updates and your main `uBlock filters - Ads` list will only be auto-updated again in next 5 days, instead of next few hours.
