### ISSUE TITLE
aniwatch.to: popups

### ISSUE THREAD

**Issue by Jacob-Suldaan** [uBlockOrigin/uAssets#22300]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniwatch.to/watch/black-summoner-18088?ep=92806`

### Category

popups

### Description

When ever I try watching something on anitwach it gives me a forced popup/open a new tab that breaks the video and stops it from working, I have disabled all pop-ups across UBO and firefox.

### Other extensions used

Darkreader
Dearrow
Firefox translations
Facebook container
Cookieauto delete
Bitwarden
Tamper monkey
consent-o-matic
reddit enhancement suite

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116530
 cosmetic: 45369
 scriptlet: 18813
 html: 2064
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37421-114, 26m Δ
  ublock-badware: 7808-10, 27m Δ
  ublock-privacy: 991-0, 27m Δ
  ublock-unbreak: 2251-0, 27m Δ
  ublock-quick-fixes: 144-0, 27m Δ
  easylist: 80063-644, 27m Δ
  easyprivacy: 43615-867, 26m Δ
  urlhaus-1: 8480-0, now
  plowe-0: 3786-1, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 905 ms (selfie)
 maxAssetCacheWait: 77 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 no-cosmetic-filtering: true
 no-popups: true
 network:
  choaboox.com: 1
  googletagmanager.com: 2
  nossairt.net: 2
```
</details>

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
