### ISSUE TITLE
iqiyi.com: ads

### ISSUE THREAD

**Issue by MGT-0504** [uBlockOrigin/uAssets#22306]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.iqiyi.com/v_27udoqiohh0.html?vfrm=free.category_lib.2&vfrmblk=S%3Alib_1_video&vfrmrst=S%3Alib_1_video_float_video_area3&bkt=list_main,list_online&e=65bd9800d1ce7f2065dd0f021ea0dcd1&stype=2&c1=%E7%94%B5%E8%A7%86%E5%89%A7`

### Category

ads

### Description

> 在打开，某一部视频的时候开头还是有广告的

**When I open a certain video, there are still ads at the beginning.**

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 60681
 cosmetic: 11379
 scriptlet: 19551
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
  easylist: null
  plowe-0: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
 added:
  https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt: 1880-24, now
  https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt: 68-3, now
  https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt: 1207-12, now
 default:
  user-filters: 97-0, never
  easyprivacy: 43617-20, now
  ublock-filters: 36921-340, now
  urlhaus-1: 8230-0, now
filterset (user): [array of 76 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 73 redacted]
urlRuleset:
 added: [array of 7 redacted]
userSettings:
 autoUpdate: false
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 479 ms (selfie)
 maxAssetCacheWait: 215 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 65
 network:
  iqiyi.com: 7
  bdstatic.com: 1
  qy.net: 57
 extended:
  ##iqpdiv[data-cupid="container"]
  ##+js(set-constant, Object.prototype.parseXML, noopFunc)
  ##+js(set-constant, Object.prototype.blackscreenDuration, 1)
  ##+js(set-constant, QiyiPlayerProphetData.a.data, {})
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
removed:
  CHN-0: null
  easylist: null
  plowe-0: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
```

You have removed many default lists. Reset to default settings and test again.
