### ISSUE TITLE
tradersunion.com: popups

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#22312]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tradersunion.com/ru/brokers/crypto/view/ledgerwallet/`

### Category

[unknown]

### Description

`https://tradersunion.com/ru/brokers/crypto/view/ledgerwallet/`

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 135238
 cosmetic: 56904
 scriptlet: 20340
 html: 2093
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 37798-359, 1h.37m Δ
  ublock-badware: 7802-10, 1h.37m Δ
  ublock-privacy: 991-1, 1h.37m Δ
  ublock-unbreak: 2257-1, 1h.37m Δ
  ublock-quick-fixes: 153-0, 1h.37m Δ
  adguard-mobile: 9034-132, now
  easylist: 80193-16708, 1h.37m Δ
  easyprivacy: 43618-894, 1h.37m Δ
  urlhaus-1: 8240-0, now
  plowe-0: 3784-1, now
  RUS-0: 40026-1062, 1h.37m Δ
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 667 ms (selfie)
 maxAssetCacheWait: 270 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cookielaw.org: 1
  facebook.net: 1
  google.com: 2
  googletagmanager.com: 1
  maps.googleapis.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
what's the issue?

**Comment by lyubomyrhv** [comment]
there a window pops up and there is a video where they are brainwashed with all sorts of training2 февр. 2024 г. 19:49 пользователь ItsProfesssional ***@***.***> написал:
what's the issue?

**Comment by lyubomyrhv** [comment]
2 февр. 2024 г. 19:49 пользователь ItsProfesssional ***@***.***> написал:
what's the issue?
