### ISSUE TITLE
movies7.to: popups

### ISSUE THREAD

**Issue by Rokeugon** [uBlockOrigin/uAssets#22317]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://movies7.to/tv/still-game-kkv46/2-2`

### Category

popups

### Description

Made a comment regarding this on the other issue but it was marked closed. dont know if its appropriate to make a new request or if by chance yous re-open previously closed issues.

Site is again opening new browser windows this time at random and it cycles through many sites trying to spread malicious stuff from facebook _(said it was blocked due to NSFW content to share or something like that)_, Twitter, also seen something related to whatsapp and telegram.

How to reproduce = When you RMB anywhere on the site and then click back onto the site to get rid of RMB menu it will force open a new smaller window

### Other extensions used

Dark Reader (not active on site)
Decentraleyes
i dont care about cookies
Volume Master 
Web Cache Viewer 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 136433
 cosmetic: 72422
 scriptlet: 37977
 html: 0
listset (total-discarded, last-updated):
 added:
  KOR-1: 4941-101, 1h.48m
  adguard-generic: 82373-768, now
 default:
  user-filters: 9-0, never
  easylist: 80119-17699, now
  easyprivacy: 43625-156, now
  plowe-0: 3784-1203, now
  ublock-badware: 7804-321, now
  ublock-filters: 36939-3691, now
  ublock-privacy: 995-9, now
  ublock-quick-fixes: 161-9, now
  ublock-unbreak: 2206-99, now
  urlhaus-1: 8240-0, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 543 ms (selfie)
 maxAssetCacheWait: 180 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  amung.us: 1
  bidgear.com: 1
  bunnycdn.ru: 1
  disqus.com: 2
  googletagmanager.com: 1
  interviewidiomantidote.com: 2
  placingsolemnlyinexpedient.com: 3
  sharethis.com: 4
 extended:
  ##+js(abort-current-script, document.createElement, break;case $…
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ###placement-top
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
  ##[src^="assets/bn"]:upward([style])
  ##+js(remove-attr, data-ad-img|data-ad-target|data-id|data-p, #p…
  ##+js(remove-attr, data-id|data-p, [data-id]\,[data-p], stay)
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in the old thread. We all see new comments. No need to open duplicated issue thread.
