### ISSUE TITLE
tumblr.com: ads

### ISSUE THREAD

**Issue by pneuma163** [uBlockOrigin/uAssets#22315]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tumblr.com/`

### Category

ads

### Description

The top of the tumblr feed includes a large black box that appears to be a video waiting to be played. If I select it using UBO's element picker it gives me the following: ##a[href^="https://use1.smartadserver.com/click"]:nth-of-type(1)

It'd be nice for that object to disappear and not clutter up the top of the page.

### Other extensions used

None. More specifically I have disabled all other extensions as well as my own custom filters in UBO and verified that the problem still occurs.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tumblr_breaks_ubo](https://github.com/uBlockOrigin/uAssets/assets/48236663/129a5089-433d-45d7-b6cc-4b2f63b69f86)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116453
 cosmetic: 45365
 scriptlet: 18839
 html: 2069
listset (total-discarded, last-updated):
 default:
  user-filters: 78-2, never
  ublock-filters: 37458-114, 6m
  ublock-badware: 7808-10, 6m
  ublock-privacy: 991-0, 6m
  ublock-unbreak: 2252-0, 6m
  easylist: 80119-642, 6m
  easyprivacy: 43625-868, 6m
  urlhaus-1: 8240-0, 6m
  plowe-0: 3784-1, 6m
  ublock-quick-fixes: 156-0, 6m
filterset (user): [array of 78 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1270 ms
 maxAssetCacheWait: 152 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  tumblr.com: 10
  doubleclick.net: 1
  moatads.com: 2
  pubmatic.com: 1
  wp.com: 3
 extended:
  ##.Yc2Sp h1, .Yc2Sp a:style(font-size: 0 !important;)
  #@#.Qrht9
  #@#.Yc2Sp
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to sign in to reproduce the issue?

**Comment by Yuki2718** [comment]
> Do you need to sign in to reproduce the issue?

Should be the case as he said feed.

**Comment by pneuma163** [comment]
Yes, I was signed in, as you figured out. The black box is no longer there now... Maybe tumblr cycled through to a different ad or ad provider for that spot for me? Or maybe some other UBO filter got it. It was there for at least 24 hours which is why I figured I'd report it since refreshing my block list didn't change anything earlier. I haven't added any filters of my own to get rid of it. *shrug*

Should we close this or should this stay open in case it comes up again? Feel free to close this if that's the usual.
