### ISSUE TITLE
digi.no: ads

### ISSUE THREAD

**Issue by ayathedoggo** [uBlockOrigin/uAssets#22316]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.digi.no/artikler/test-sikkerhetsnokler/521212`

### Category

ads

### Description

Webpage loads ads through Brave Shields, uBO, Adblocker Ultimate (tested on another browser/device).

### Other extensions used

[Absolute Enable Right Click and Copy](https://chromewebstore.google.com/detail/absolute-enable-right-cli/jdocbkpgdakpekjlhemmfcncgdjeiika)
[AutoScroll](https://chromewebstore.google.com/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan)
[Dark Reader](https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)
[FastForward](https://chromewebstore.google.com/detail/fastforward/icallnadddjmdinamnolclfjanhfoafe)
[Google Translate](https://chromewebstore.google.com/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb)
[Search by Image](https://chromewebstore.google.com/detail/search-by-image/cnojnbdhbhnkbcieeekonklommdnndci)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Ads are marked as "ANNONSE" above or below. Brave Shields make no difference.
![image](https://github.com/uBlockOrigin/uAssets/assets/105717495/45270080-ba34-4bca-8590-d31cc6cdd947)
![image](https://github.com/uBlockOrigin/uAssets/assets/105717495/7615b8ff-b1e4-491b-b884-63ad979da078)
![image](https://github.com/uBlockOrigin/uAssets/assets/105717495/5d1c9272-4e7d-4a9f-9962-d7579818c122)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116451
 cosmetic: 45360
 scriptlet: 20301
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-4, never
  easylist: 80119-14, 1h.44m Δ
  easyprivacy: 43625-48, 1h.44m Δ
  plowe-0: 3784-1178, 1h.44m
  ublock-badware: 7804-136, 1h.44m Δ
  ublock-filters: 36939-210, 1h.44m Δ
  ublock-privacy: 995-6, 1h.44m Δ
  ublock-quick-fixes: 161-8, 1h.44m Δ
  ublock-unbreak: 2206-31, 1h.44m Δ
  urlhaus-1: 8240-0, 1h.44m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1392 ms (selfie)
 maxAssetCacheWait: 147 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##.lg\:h-\[320px\].lg\:flex.hidden.items-center.mx-auto.my-4.fle…
  ##.side-ads-wrapper--left.side-ads-wrapper > .sticky-ads-wrapper…
  ##div.clear-both > .items-center.mx-auto.my-4.flex-col.flex
  ##.items-center.px-4.nativeAdDatas-center.h-12.justify-between.f…
  ##.group.relative.border.flex-col.bg-white.flex
  ##.ad-label
```
</details>

**Comment by D4niloMR** [comment]
Enable the regional list. 

Also use only uBlock Origin. https://twitter.com/gorhill/status/1033706103782170625

**Comment by ayathedoggo** [comment]
Hullo! I have two HP laptops, and use Adblocker Ultimate on one and uBO on the other. They're not doubled up on one device or browser. What I meant is that neither of them block the ads. Thank you.

I enabled the regional list, and ad still shows.
https://github.com/uBlockOrigin/uAssets/assets/105717495/60a5f9a3-b609-4179-a154-62efc33a07ea

**Comment by Daxy7** [comment]
ads on top of the page for me and them ads too
https://github.com/uBlockOrigin/uAssets/assets/91396482/3f414cf9-4173-4964-b2a1-04785c70f92c

test these rules in 'my filters' 
```
/508-b74f426bac60fe2b.js$domain=digi.no
digi.no##.nativeAdDatas-center:upward(1)
```
advert code, might need `##+js` if url ever changes
```
https://pastebin.com/raw/m9Gkd4Dv
```

**Comment by D4niloMR** [comment]
Add:

`digi.no##.my-6:has(.ad-label)`

@DandelionSprout

**Comment by DandelionSprout** [comment]
I'll handle it within 2 hours-ish.

**Comment by DandelionSprout** [comment]
I could find 1 sponsored article on that page tonight, namely for `NetSecurity`; however, checking out that sponsored article, it seems to actually be informative, and doesn't actually try to beg you to buy their products (although the link to it is oddly placed in the midst of a review scoring). So as it's a 40:60 on whether I'd block it, my current decision is to not block it.
