### ISSUE TITLE
maxroll.gg: detection

### ISSUE THREAD

**Issue by Peanutbutter146** [uBlockOrigin/uAssets#22318]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://maxroll.gg/last-epoch/build-guides?filter[classes][taxonomy]=taxonomies.classes&filter[classes][value]=rogue&filter[classes][filters][0][taxonomy]=taxonomies.classes&filter[classes][filters][0][value]=marksman`

### Category

detection

### Description

After browsing the site for about 15 seconds a window will popup prompting to disable AdBlock on the site. Following the directions above this issues was isolated to being apart of the "Easylist" filter under the "Ads" drop down.

### Other extensions used

Other adblocks are installed however in an attempt to isolate this issue this same problem has only been replicable using ublock origin. This problem persists not matter the combonation of other adblocks used. Tested all combonations of ublock origin, ad guard, and adblock plus.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/158645777/e0e37f8f-a764-4cd1-8489-b6ff5d26964f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116374
 cosmetic: 45351
 scriptlet: 20300
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 80119-14, 2m
  easyprivacy: 43625-48, 2m
  plowe-0: 3784-1178, 2m
  ublock-badware: 7804-136, 2m
  ublock-filters: 36939-210, 2m
  ublock-privacy: 995-6, 2m
  ublock-quick-fixes: 158-8, 10m
  ublock-unbreak: 2206-31, 2m
  urlhaus-1: 8170-0, 2m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 569 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  maxroll.gg: 2
  cloudflareinsights.com: 1
  nitropay.com: 1
  sentry.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters - Annoyances` list or add this as your custom filter

```adb
maxroll.gg##+js(set-constant, nitroAds.loaded, true)
```

**Comment by LeBigNasty** [comment]
This issue has returned with both annoyance filter enabled and the specific block mentioned.

**Comment by marsderp** [comment]
Sorry to necro this - am seeing popup with annoyance filter but following this worked https://old.reddit.com/r/uBlockOrigin/comments/1b1ksxt/maxrollgg_popup_asking_to_disable_adblock/ 

```adblock
maxroll.gg##.fixed:has(> .bg-black-450.border-dark-5) 
```

**Comment by stephenhawk8054** [comment]
I can't reproduce. Test again in another browser profile with only uBO and its default settings + `uBlock filters – Annoyances` list
