### ISSUE TITLE
tmz.com: ads

### ISSUE THREAD

**Issue by Gleason70** [uBlockOrigin/uAssets#22314]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tmz.com/`

### Category

ads

### Description

TMZ Investigates Ad for a TMZ Video Documentary that repeats throughout the page, over and over again.
I would like to know how to block this.

This is what the ad looks like:

![TMZ Investigates #1](https://github.com/uBlockOrigin/uAssets/assets/135865380/11669476-3b8d-447e-992b-7beee88f6a26)

Many thanks!

### Other extensions used

![TMZ Investigates #1](https://github.com/uBlockOrigin/uAssets/assets/135865380/fc8cee58-bae0-4ef4-bee3-c2181ba02257)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![TMZ Investigates #1](https://github.com/uBlockOrigin/uAssets/assets/135865380/0c33d8cf-b81d-428b-a42a-9f825f3235da)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 347794
 cosmetic: 225201
 scriptlet: 52865
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76930-1790, 12m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 12m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96261-52758, 12m
  FRA-0: 27141-3010, 11m
  ISR-0: 1771-7, 11m
  RUS-0: 39986-1491, 11m
  adguard-cookies: 28514-28514, 11m
  adguard-generic: 82373-1132, 11m
  adguard-mobile: 9034-116, 11m
  adguard-mobile-app-banners: 4932-4932, 11m
  adguard-other-annoyances: 14128-14128, 11m
  adguard-popup-overlays: 26926-26926, 11m
  [17 lists not shown]: [too many]
 default:
  user-filters: 3440-51, never
  easylist: 80193-18248, 45m Δ
  easyprivacy: 43618-26689, 44m Δ
  plowe-0: 3784-1688, 12m
  ublock-badware: 7804-344, 45m Δ
  ublock-filters: 36934-4150, 45m Δ
  ublock-privacy: 995-413, 44m Δ
  ublock-quick-fixes: 158-9, 45m Δ
  ublock-unbreak: 2206-154, 45m Δ
  urlhaus-1: 8240-0, 12m
filterset (user): [array of 3441 redacted]
trustedset:
 added: [array of 60 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1352 ms (selfie)
 maxAssetCacheWait: 852 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 26
 network:
  aaxads.com: 1
  amazon-adsystem.com: 1
  atp.fox: 1
  connatix.com: 1
  doubleclick.net: 1
  duckduckgo.com: 1
  fox.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  instagram.com: 2
  ketchcdn.com: 1
  megaphone.fm: 3
  opecloud.com: 2
  twitter.com: 5
  webcontentassessor.com: 1
  youtube-nocookie.com: 2
 extended:
  ##div.sidebar-child-wrapper:nth-of-type(1)
  ##div.sidebar-child-wrapper:nth-of-type(3)
  ##div.sidebar-child-wrapper:nth-of-type(4)
  ##div.sidebar-child-wrapper:nth-of-type(5)
  ##.sidebar
  ##.browser-notifications-prompt
  ##.ad-size-leaderboard.ad-container.ad-blogroll5
  ##.masthead-social
  ##.ad-size-billboard.ad-container
  ###browser-notifications-prompt
  ##.social-item
  ##.ad-container
  ##.social.social--blogroll
  ##.btn.social__btn.social__btn--sm.social__btn--twitter.js-track…
  ##.btn.social__btn.social__btn--sm.social__btn--facebook.js-trac…
  ##article > div[class] > div[role="button"]:has(> div[dir="auto"…
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  ##._aagw:empty
  ##.HoverCard
  ##body:style(overflow: visible!important;)
  ##[class]:style(-webkit-touch-callout: default !important; -webk…
  ##+js(set-constant, _sharedData.is_whitelisted_crawl_bot, true)
  ##+js(set-session-storage-item, loggedOutAppSheetIsMinimized, 1)
  ##+js(trusted-set-cookie, ig_did, 0C826C21-17C3-444A-ABB7-EBABD3…
  ##.ytp-cards-teaser
  ##.ytp-pause-overlay
  ##.ytp-paid-content-overlay
  ##.ytp-ad-progress-list
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
```
</details>

**Comment by stephenhawk8054** [comment]
Self-promotion. As it looks quite annoyed, I'll address it in `uBlock filters - Annoyances list`. You can enable that list or add this as your custom filter

```adb
tmz.com##.canvas-video-block--aside
```

**Comment by Gleason70** [comment]
Thank-you!!!
Your filter works beautifully & you're right, they are very annoying.
Thanks again & cheers
 
 
  On Fri, Feb 2, 2024 at 21:05, ***@***.***> wrote:   


Self-promotion. As it looks quite annoyed, I'll address it in uBlock filters - Annoyances list. You can enable that list or add this as your custom filter
tmz.com##.canvas-video-block--aside
