### ISSUE TITLE
careers.twitter.com: nuisance

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#22313]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://careers.twitter.com/en`

### Category

nuisance

### Description

Cookie notice is displayed. Can block with this:
`twitter.com##.eUHfuh.src__NoticeElement-kaFenH`
Would be nice to add this to the easylist annoyances filter.

### Other extensions used

none

### Screenshot(s)

<img width="1470" alt="Screenshot 2024-02-02 at 19 41 22" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/6f93ab15-2f7c-4ee8-8e73-537963e0becf">

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 311176
 cosmetic: 246787
 scriptlet: 49591
 html: 2276
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82373-6987, now
  adguard-mobile: 9034-140, now
  adguard-spyware-url: 1434-103, now
  adguard-spyware: 90799-26902, now
  block-lan: 56-0, now
  curben-phishing: 88597-28, now
  adguard-social: 22112-848, now
  adguard-cookies: 28513-62, now
  ublock-cookies-adguard: 921-0, now
  adguard-popup-overlays: 26926-1600, now
  adguard-mobile-app-banners: 4932-1073, now
  adguard-other-annoyances: 14128-334, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 45-0, never
  ublock-filters: 37452-504, 34m Δ
  ublock-badware: 7808-10, 34m Δ
  ublock-privacy: 991-0, 34m Δ
  ublock-unbreak: 2252-1, 34m Δ
  ublock-quick-fixes: 153-0, 34m Δ
  easylist: 80193-940, 34m Δ
  easyprivacy: 43618-1079, 34m Δ
  urlhaus-1: 8240-0, now
  plowe-0: 3784-1, now
filterset (user): [array of 45 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4737 ms
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  twitter.com: 1
 extended:
  ##.eUHfuh.src__NoticeElement-kaFenH
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by mapx-** [comment]
report here: https://github.com/easylist/easylist/issues
