### ISSUE TITLE
dictionary.com: ads

### ISSUE THREAD

**Issue by datcu-octavian** [uBlockOrigin/uAssets#22311]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dictionary.com/`

### Category

ads

### Description

picker doesn't block the video ad of word of day

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 123
filterset (summary):
 network: 117816
 cosmetic: 36841
 scriptlet: 18896
 html: 2069
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 37798-387, 5m Δ
  ublock-badware: 7802-10, 5m Δ
  ublock-privacy: 991-1, 5m Δ
  ublock-unbreak: 2257-1, 5m Δ
  ublock-quick-fixes: 153-0, 5m Δ
  adguard-mobile: 9034-132, now
  easylist: 80193-16725, 5m Δ
  easyprivacy: 43618-849, 5m Δ
  urlhaus-1: 8240-0, now
  plowe-0: 3784-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 395 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 43
 network:
  dictionary.com: 1
  1rx.io: 1
  adobedtm.com: 4
  adsrvr.org: 1
  agkn.com: 1
  amazon-adsystem.com: 2
  anyclip.com: 21
  btloader.com: 1
  demdex.net: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  icanhazip.com: 1
  imasdk.googleapis.com: 2
  openx.net: 1
  rubiconproject.com: 1
  sonobi.com: 1
  springserve.com: 1
  yieldmo.com: 1
 extended:
  ###dictionary_content_300x250_noflex_1
```
</details>

**Comment by Dani-1-2** [comment]
I cannot see such video ad, but I have all filter lists enabled. There are some ad leftovers though and I can block them with:
www.dictionary.com##.fHACXxic9xvQeSNITiwH

**Comment by mapx-** [comment]
@datcu-octavian 

enable AdGuard – Annoyances
or
EasyList – Annoyances
or add in your custom filters

`||player.anyclip.com^$from=dictionary.com`
