### ISSUE TITLE
developer.twitter.com: nuisance

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#22319]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/delete-message-event`

### Category

nuisance

### Description

Cookie notice

### Other extensions used

- Bitwarden
	- 2024.1.1
- DeepL
	- 1.14.0
- LanguageTool
	- 8.4.0
- Postman Interceptor
	- 3.0.5
- SimpleLogin
	- 2.10.2
- SponsorBlock
	- 5.4.28
- Violentmonkey
	- 2.18.0
- Wayback Machine
	- 3.2
- BlockTube
	- 0.3.38
- Gumbo: Twitch
	- 1.18.6
- Refined GitHub
	- 24.2.2
- Return YouTube Dislike
	- 3.0.0.14
- YouTube Party
	- 2.2.2

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63259739/b5da97a3-e519-4c26-99ce-3275cf5b794a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 136958
 cosmetic: 123703
 scriptlet: 28759
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2558-1, now
  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-only/hosts: 10188-0, now
  adguard-spyware-url: 1434-153, now
  easylist-annoyances: 4334-33, now
  easylist-chat: 180-0, now
  easylist-newsletters: 6916-15, now
  easylist-notifications: 2915-86, now
  fanboy-cookiemonster: 49705-183, now
  fanboy-social: 16127-15, now
  ublock-annoyances: 6615-82, now
  ublock-cookies-easylist: 921-921, now
 default:
  user-filters: 0-0, never
  DEU-0: 7241-0, now
  easylist: 80128-21, now
  easyprivacy: 43623-143, now
  plowe-0: 3784-1179, now
  ublock-badware: 7808-140, now
  ublock-filters: 36940-244, now
  ublock-privacy: 998-120, now
  ublock-quick-fixes: 161-8, now
  ublock-unbreak: 2206-38, now
  urlhaus-1: 8170-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 346 ms (selfie)
 maxAssetCacheWait: 183 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  twitter.com: 1
 extended:
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by mapx-** [comment]
does this work without breakage ?

`developer.twitter.com##.u12-data-protection-notice__item`

**Comment by B1ack3ye** [comment]
So far it has worked for me without any problems.
