### ISSUE TITLE
partis.si: ads

### ISSUE THREAD

**Issue by Enzycal** [uBlockOrigin/uAssets#22325]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://partis.si/
```

### Description

Some ads are not removed. They are marked as "Oglas" on the website, visible on the screenshots.

The leftover ads can be removed by including these two filters:
`partis.si##a.card-item-ad.card`
`partis.si##a:has(> div[id^="ad-popular"])`

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without the above provided filters:
![NO_FILTER](https://github.com/uBlockOrigin/uAssets/assets/45462298/71b88d94-74d3-4d8d-a485-4035ab205e65)

With the above provided filters:
![WITH_FILTER](https://github.com/uBlockOrigin/uAssets/assets/45462298/1a7058d9-3ab0-4b48-9b97-baed0ee38574)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 116465
 cosmetic: 45355
 scriptlet: 20304
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80130-14, 4h.9m Δ
  easyprivacy: 43623-48, 4h.9m Δ
  plowe-0: 3782-1172, 11d.18h.28m
  ublock-badware: 7808-137, 4h.9m Δ
  ublock-filters: 36948-210, 4h.9m Δ
  ublock-privacy: 998-6, 4h.9m Δ
  ublock-quick-fixes: 161-8, 4h.9m Δ
  ublock-unbreak: 2206-31, 4h.9m Δ
  urlhaus-1: 8240-0, 20h.52m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1238 ms (selfie)
 maxAssetCacheWait: 222 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##.ad_btn
  ##.banner-ad

```
</details>

**Comment by D4niloMR** [comment]
@betterwebleon for Slovenian List.
