### ISSUE TITLE
thesimsresource.com: ads

### ISSUE THREAD

**Issue by ExteriorCloth20** [uBlockOrigin/uAssets#22324]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thesimsresource.com/artists/Cyclonesue/downloads/browse/category/sims2/skipsetitems/1`

### Category

ads

### Description

Leftover box where ads are supposed to be is shown

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/39027313/8f386ca6-194a-4512-a648-b4d1b6c036f2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 124032
 cosmetic: 81627
 scriptlet: 24738
 html: 2283
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1042-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 408-3, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2558-3, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/WikiaPureBrowsingExperience.txt: 79-0, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1939-12, now
  block-lan: 56-0, now
  easylist-annoyances: 4334-103, now
  easylist-chat: 180-0, now
  easylist-newsletters: 6920-16, now
  easylist-notifications: 2925-5, now
  fanboy-social: 16094-23, 49m
  ublock-annoyances: 6568-71, 49m Δ
  [2 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 37467-176, 49m Δ
  ublock-badware: 7812-10, 49m Δ
  ublock-privacy: 994-51, 49m Δ
  ublock-unbreak: 2252-0, 49m Δ
  ublock-quick-fixes: 156-0, 49m Δ
  easylist: 80130-683, 49m Δ
  easyprivacy: 43623-960, 49m Δ
  urlhaus-1: 8000-0, now
  plowe-0: 3784-2, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 prefetchingDisabled: false
hiddenSettings:
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 5
 cnameMaxTTL: 720
 filterAuthorMode: true
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 292 ms (selfie)
 maxAssetCacheWait: 155 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.back-to-top:not(body):not(html)
  ##.footer-social
  ##.crtv-top-wrapper
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.ad-browse-rectangle
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, isAdBlocked, false)
  ##+js(no-xhr-if, /enthusiastgaming|googleoptimize|googletagmanag…
```
</details>

**Comment by ExteriorCloth20** [comment]
example website in screenshot https://www.thesimsresource.com/artists/Cyclonesue/downloads/browse/category/sims2/skipsetitems/1

**Comment by D4niloMR** [comment]
Add:

`hesimsresource.com##[class^="ad-browse-"]`

@ryanbr
