### ISSUE TITLE
manhwa-freak.com: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22322]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://manhwa-freak.com/
```

### Description

sponsored partner + ads leftovers 
filter suggestion for ads: 
```adblock-filter-list
||p.ck.sb^$image,domain=https://manhwa-freak.com/
``` 

### Other extensions used

no 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-03 161753](https://github.com/uBlockOrigin/uAssets/assets/100969549/112791bf-647c-4a40-b9e8-dca35b929d47)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 361667
 cosmetic: 277041
 scriptlet: 51815
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4302-4, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 32-0, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96321-16590, now
  CHN-0: 25697-134, now
  JPN-1: 14000-9, now
  KOR-1: 4940-21, now
  adguard-cookies: 28517-3648, now
  [22 lists not shown]: [too many]
 default:
  user-filters: 53-0, never
  DEU-0: 7241-1, now
  easylist: 80251-2215, now
  easyprivacy: 43624-26550, now
  plowe-0: 3781-1683, never
  ublock-badware: 7808-342, now
  ublock-filters: 36953-3933, now
  ublock-privacy: 998-418, now
  ublock-quick-fixes: 161-9, now
  ublock-unbreak: 2206-155, now
  urlhaus-1: 8000-1, now
filterset (user): [array of 54 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 91 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 debugScriptlets: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 745 ms (selfie)
 maxAssetCacheWait: 395 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  acscdn.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.scrollToTop
  ###teaser3
```
</details>

**Comment by D4niloMR** [comment]
Add:

```
manhwa-freak.com##.kln
manhwa-freak.com##.widget_text.popular:has(> .custom-html-widget > .adsbygoogle)
```

@ryanbr
