### ISSUE TITLE
allegro.pl: popups

### ISSUE THREAD

**Issue by Methosss** [uBlockOrigin/uAssets#22327]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://allegro.pl/listing?string=%C5%9Bled%C5%BA%20esata`

### Category

popups

### Description

i have this annoying section that i cannot block, after refreshing site they appear again:
![image](https://github.com/uBlockOrigin/uAssets/assets/32804020/380b2e73-f7f4-4081-94a0-96963ef0a501)
and there area also popups.

### Other extensions used

popup blocker (strict) scroll anywhere, shazam, open in firefox, return youtube dislike, tab groups extension,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/32804020/be8921e5-db13-4d83-b1f0-7ea4d0257048)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 299650
 cosmetic: 245364
 scriptlet: 47836
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28517-30, now
  adguard-generic: 82379-908, now
  adguard-mobile: 9033-49, now
  adguard-mobile-app-banners: 4932-8, now
  adguard-other-annoyances: 14128-46, now
  adguard-popup-overlays: 26926-103, now
  adguard-social: 22112-881, now
  adguard-spyware: 90800-1241, now
  adguard-spyware-url: 1434-5, now
  adguard-widgets: 2430-6, now
  block-lan: 56-0, now
  curben-phishing: 89089-20, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 4765-15, never
  easylist: 80255-1931, 48m Δ
  easyprivacy: 43378-26371, 48m Δ
  plowe-0: 3784-1344, now
  ublock-badware: 7808-330, 48m Δ
  ublock-filters: 36954-7362, 48m Δ
  ublock-privacy: 998-415, 48m Δ
  ublock-quick-fixes: 164-10, 48m Δ
  ublock-unbreak: 2206-148, 48m Δ
  urlhaus-1: 8000-1, now
filterset (user): [array of 2848 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1400 ms (selfie)
 maxAssetCacheWait: 698 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 10
 network:
  allegroimg.com: 2
  doubleclick.net: 1
  facebook.com: 1
  gemius.pl: 3
  googletagmanager.com: 1
  naanalle.pl: 1
  ngastatic.com: 1
 extended:
  ##.AdBox
  ##.SponsoredResults
  ##.sponsored_content
  ##._13850_FyKIz.mse2_40.mzmg_f9.munh_0_l.munh_16_s.munh_8.mpof_v…
  ##body:style(overflow-y: auto !important;)
  ##body:style(overflow: auto !important;)
```
</details>

Using latest edge browser.

**Comment by u-RraaLL** [comment]
Where are the "popups"?

For the section, try this:

    allegro.pl##[data-box-name="articles"]

**Comment by mapx-** [comment]
self promotion

**Comment by Methosss** [comment]
> Where are the "popups"?
> 
> For the section, try this:
> 
> ```
> allegro.pl##[data-box-name="articles"]
> ```

there:
![image](https://github.com/uBlockOrigin/uAssets/assets/32804020/83daaa85-ec06-4478-ac5c-de954de4bf06)
When you scrolling down site, but your code blocks both of them at once. thanks.
