### ISSUE TITLE
adblock detection pop up on https://movies4u.date/ site.

### ISSUE THREAD

**Issue by spidy2356** [uBlockOrigin/uAssets#22321]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://movies4u.date/
```

### Description

adblock detection pop up comes out on this site. i make an filter using element picker but when I go to categories then pop up comes again.

![image](https://github.com/uBlockOrigin/uAssets/assets/101243689/4a988f5d-041a-4a09-a5c4-3aa4951ac96e)

### Other extensions used

no. not related to adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/101243689/633f3cfd-19ff-4a02-bb13-bcc99ac9cdf0)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 120286
 cosmetic: 117105
 scriptlet: 24883
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4333-32, 1d.4h.15m
  easylist-chat: 180-0, 5d.23h.24m
  easylist-newsletters: 6912-15, 1d.4h.14m
  easylist-notifications: 2915-86, 1d.4h.15m
  fanboy-cookiemonster: 64863-15615, 8d.4h.22m
  fanboy-social: 16136-29, 1d.4h.15m
  ublock-cookies-easylist: 921-2, 1d.4h.15m
 default:
  user-filters: 18-0, never
  easylist: 80130-14, 2h.43m Δ
  easyprivacy: 43623-134, 2h.43m Δ
  plowe-0: 3783-1173, 9d.22h.13m
  ublock-badware: 7808-137, 2h.43m Δ
  ublock-filters: 36948-227, 2h.43m Δ
  ublock-privacy: 998-8, 2h.43m Δ
  ublock-quick-fixes: 161-8, 2h.43m Δ
  ublock-unbreak: 2206-34, 2h.43m Δ
  urlhaus-1: 8000-0, 2h.43m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9081 ms (selfie)
 maxAssetCacheWait: 290 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by spidy2356** [comment]
! 2024-02-04 https://movies4u.date
movies4u.date##.popSc

this solves the detection issue but generates 2 scroll bars, that cause issues during scrolling. plz fix

**Comment by spidy2356** [comment]
but what about double scrollbar. it's still there. is it possible to solve. if yes then do it plz

**Comment by ItsProfessional** [comment]
Remove your filter that you added.

**Comment by spidy2356** [comment]
> Remove your filter that you added.
@ItsProfessional 
sorry sir. that error was created for and tampermonkey userscript. and the issue occurs in a few sites only. so it's a mistake. it fixed now, no issue from ublock origin extension side. thanks for help. issue fixed so u can close this.
