### ISSUE TITLE
1cloudfile.com: detection

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#22329]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1cloudfile.com/bn01`

### Category

detection

### Description

Instead of the download button, there's a "Please Disable adblock and the page" text with a "Refresh" button to the right. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1cloudfile download page](https://github.com/uBlockOrigin/uAssets/assets/50150516/515b7e5c-6afb-490b-9442-c1a12fb055bf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 309291
 cosmetic: 234830
 scriptlet: 47467
 html: 0
listset (total-discarded, last-updated):
 added:
  ROU-1: 1342-1, now
  adguard-cookies: 28517-30, now
  adguard-generic: 82379-504, now
  adguard-other-annoyances: 14128-6, now
  adguard-popup-overlays: 26926-84, now
  adguard-social: 22112-878, now
  adguard-spyware: 90800-1196, now
  adguard-spyware-url: 1434-5, now
  adguard-widgets: 2430-5, now
  block-lan: 56-0, now
  curben-phishing: 89089-20, now
  dpollock-0: 11635-214, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  easylist: 80255-2079, now
  easyprivacy: 43378-26384, now
  plowe-0: 3784-1625, now
  ublock-badware: 7808-330, now
  ublock-filters: 36954-3888, now
  ublock-privacy: 998-415, now
  ublock-quick-fixes: 164-9, now
  ublock-unbreak: 2204-148, now
  urlhaus-1: 8000-1, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 26 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 662 ms (selfie)
 maxAssetCacheWait: 508 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  1cloudfile.com: 2
  capaciousdrewreligion.com: 1
  doubleclick.net: 1
  friendshipmale.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  lopsydir.live: 1
  proftrafficcounter.com: 2
  viewerebook.com: 3
  waust.at: 1
 extended:
  ##.advert-wrapper
  ##body .top-advert
  ##.top-advert
  ##ins.adsbygoogle
  ##.back-to-top:not(body):not(html)
  ##.adsbygoogle-noablate
  ##center > a[onclick^="window.open"] > button
  ##+js(no-fetch-if, cloudfront.net/?)
  ##+js(abort-current-script, document.getElementById, adblockEnab…
  ##+js(abort-on-property-read, cdnasset)
  ##+js(no-window-open-if)
  ##+js(no-fetch-if, /adsbygoogle\.js|\.js/)
  ##+js(no-setInterval-if, !display)
```
</details>

**Comment by mapx-** [comment]
test

```
@@*$xhr,domain=1cloudfile.com
1cloudfile.com#@#+js(prevent-fetch, /adsbygoogle\.js|\.js/)
1cloudfile.com##.uk-text-center
1cloudfile.com##.preview-download-wrapper
1cloudfile.com##.content-preview-wrapper
```

**Comment by ave9858** [comment]
> test
> 
> ```
> @@*$xhr,domain=1cloudfile.com
> 1cloudfile.com#@#+js(prevent-fetch, /adsbygoogle\.js|\.js/)
> 1cloudfile.com##.uk-text-center
> 1cloudfile.com##.preview-download-wrapper
> 1cloudfile.com##.content-preview-wrapper
> ```

This delays the "Please Disable adblock and Refresh" message, but doesn't get rid of it. But even with uBO and firefox tracking protection both disabled, I still see the message, so this might be a site issue and not caused by uBO.

**Comment by mapx-** [comment]
- working fine FF / chrome on my end
- reset uBO to default

**Comment by ghajini** [comment]
i removed the filter here https://github.com/uBlockOrigin/uAssets/commit/b3db735514a69fa9935d5a3d37a46b75856496aa
because i see antiadblock is present despite ublock or adblocking .in presence of above filter ,i see 3p ad requests unblocking

**Comment by BlazeFTL** [comment]
[Screenshot_2024-02-07-15-59-00-979_org mozilla fenix](https://github.com/uBlockOrigin/uAssets/assets/139938337/479fdee3-b7de-4fc0-b019-ca829925cd3a)

Although Currently I Need 
```
@@||darwinpoems.com^$script,xhr,domain=1cloudfile.com
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=1cloudfile.com
@@*$xhr,domain=1cloudfile.com,badfilter

**Comment by playonevideo** [comment]
On `https://1cloudfile.com/2bv3l` the Download button doesn't appear if uBO is on, it shows this spinner icon continuously loading:

<img width="1596" height="811" alt="Image" src="https://github.com/user-attachments/assets/f2ea1dee-fa7d-4d6c-9bf5-66f9b6dcaf81" />

**Comment by mapx-** [comment]
```adb
1cloudfile.com#@#+js(remove-node-text, script, /"\\|\\[ux]|\+\[\]/, excludes, self.__next)
```

@huyszn

**Comment by BlazeFTL** [comment]
https://github.com/uBlockOrigin/uAssets/commit/50463e0c8142944058c54d32fc63930c830a7466
