### ISSUE TITLE
quillbot.com: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22323]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://quillbot.com/grammar-check`

### Category

nuisance

### Description

When using this service on this website, it forces you, after some time, to create an account.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-03 162717](https://github.com/uBlockOrigin/uAssets/assets/100969549/cd07cb41-04ee-4f33-9dda-095d72d3a4b6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 361667
 cosmetic: 277041
 scriptlet: 51815
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2m
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4302-4, 2m
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, 2m
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, 2m
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, 2m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 32-0, 2m
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, 2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96321-16590, 2m
  CHN-0: 25697-134, 2m
  JPN-1: 14000-9, 2m
  KOR-1: 4940-21, 2m
  adguard-cookies: 28517-3648, 2m
  [22 lists not shown]: [too many]
 default:
  user-filters: 53-0, never
  DEU-0: 7241-1, 2m
  easylist: 80251-2215, 2m
  easyprivacy: 43624-26550, 2m
  plowe-0: 3781-1683, never
  ublock-badware: 7808-342, 2m
  ublock-filters: 36953-3933, 2m
  ublock-privacy: 998-418, 2m
  ublock-quick-fixes: 161-9, 2m
  ublock-unbreak: 2206-155, 2m
  urlhaus-1: 8000-1, 2m
filterset (user): [array of 54 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 91 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 debugScriptlets: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 745 ms (selfie)
 maxAssetCacheWait: 395 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 19
 network:
  amplitude.com: 17
  cookielaw.org: 1
  partnerstack.com: 1
 extended:
  ##.grecaptcha-badge
  ##+js(set-local-storage-item, showPrivacyBannerNov2023, false)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
Add:

`quillbot.com##+js(set-local-storage-item, mode-quills, $remove$)`

@ryanbr
