### ISSUE TITLE
tiktok.com: nuisance

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#22320]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktok.com/uBlockOrigin/uAssets/issues/19009`

### Category

nuisance

### Description

seems that something changed in tiktok code and `##+js(aeld, visibilitychange, pagehide)` no longer keeps the video playing in a new tab. test link:
```
https://www.tiktok.com/@jadafacer/video/82714842335199232
```
https://github.com/uBlockOrigin/uAssets/issues/19009

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 106760
 cosmetic: 48980
 scriptlet: 23774
 html: 2283
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1041-0, 3h.56m
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 2031-0, 3h.56m
  ublock-annoyances: 6568-12, 3h.56m Δ
 default:
  user-filters: 2121-16, never
  ublock-filters: 37459-120, 3h.56m Δ
  ublock-badware: 7812-10, 3h.56m Δ
  ublock-privacy: 994-0, 3h.56m Δ
  ublock-unbreak: 2252-0, 3h.56m Δ
  ublock-quick-fixes: 156-0, now
  easylist: 80128-318, 3h.56m
  easyprivacy: 43623-1832, 3h.56m Δ
filterset (user): [array of 984 redacted]
switchRuleset:
 added: [array of 11 redacted]
hostRuleset:
 added: [array of 10 redacted]
 removed:
  behind-the-scene * * noop
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 728 ms (selfie)
 maxAssetCacheWait: 235 ms
 cacheBackend: indexedDB
 unsuspendAfter: 366 ms
popupPanel:
 blocked: 4
 network:
  github.com: 4
 extended:
  ##.Popover
  ##.color-fg-success
  ##*:style(border-radius:0px !important;)
```
</details>

**Comment by ItsProfessional** [comment]
continue in #19009
