### ISSUE TITLE
sonyliv.com: breakage

### ISSUE THREAD

**Issue by Midore11** [uBlockOrigin/uAssets#22326]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sonyliv.com/shows/shark-tank-india-1700000741/pitching-innovation-1000263443?watch=true`

### Category

breakage

### Description

Loading Screen gets stuck at 95%. But when Ublock is disabled it loads perfectly with the first ad and continues streaming.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116206
 cosmetic: 45350
 scriptlet: 20301
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 80119-14, 55m Δ
  easyprivacy: 43625-48, 55m Δ
  plowe-0: 3784-1178, now
  ublock-badware: 7804-136, 55m Δ
  ublock-filters: 36939-210, 55m Δ
  ublock-privacy: 995-6, 55m Δ
  ublock-quick-fixes: 161-8, 55m Δ
  ublock-unbreak: 2206-31, 55m Δ
  urlhaus-1: 8000-0, 55m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1363 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 10
 network:
  crwdcntrl.net: 1
  d2r1yp2w7bby2u.cloudfront.net: 2
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
 extended:
  ##+js(json-prune, adProvider)
```
</details>

**Comment by mapx-** [comment]
I don't get any ad at the beginning of the video

**Comment by Midore11** [comment]
Okay I ran ublock on Chrome it was running properly with no other extensions running. I restarted my edge, cleaned history and cache, and now it seems to work fine. My bad should have tested it. Seems like a Sony Liv glitch.

**Comment by mapx-** [comment]
> Seems like a Sony Liv glitch.

We added 2 corrections.
