### ISSUE TITLE
retroonly.com: ads

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#22328]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://retroonly.com/how-to-use-switch-homebrew-without-getting-banned/`

### Category

ads

### Description

Ad appears. Can be removed with:
retroonly.com##div.wp-block-column-is-layout-flow.is-layout-flow.wp-block-column:nth-of-type(2)
||media-amazon.com*$domain=retroonly.com

### Other extensions used

none

### Screenshot(s)

<img width="1470" alt="Screenshot 2024-02-03 at 20 25 50" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/f847b065-c851-47ab-b42e-caaa361fa819">

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 311263
 cosmetic: 246805
 scriptlet: 49635
 html: 2280
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82379-6985, now
  adguard-mobile: 9033-20, now
  adguard-spyware-url: 1434-106, now
  adguard-spyware: 90800-26863, now
  block-lan: 56-0, now
  curben-phishing: 89089-29, now
  adguard-social: 22112-849, now
  adguard-cookies: 28517-63, now
  ublock-cookies-adguard: 921-0, now
  adguard-popup-overlays: 26926-1664, now
  adguard-mobile-app-banners: 4932-1073, now
  adguard-other-annoyances: 14128-334, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 46-0, never
  ublock-filters: 37475-410, 1h.46m Δ
  ublock-badware: 7812-10, 1h.46m Δ
  ublock-privacy: 994-0, 1h.46m Δ
  ublock-unbreak: 2252-1, 1h.46m Δ
  ublock-quick-fixes: 157-0, 1h.46m Δ
  easylist: 80255-978, 1h.46m Δ
  easyprivacy: 43378-1104, 1h.46m Δ
  urlhaus-1: 8000-0, now
  plowe-0: 3784-83, now
filterset (user): [array of 46 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4737 ms
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  retroonly.com: 2
  adthrive.com: 1
  amazon-adsystem.com: 2
  googletagmanager.com: 1
  videoplayerhub.com: 1
 extended:
  ##.adthrive-ad
  ##.adthrive-content
  ##.adthrive
  ##.grecaptcha-badge
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by mapx-** [comment]
report at easylist repo
