### ISSUE TITLE
mail.google.com: ads

### ISSUE THREAD

**Issue by joshzee** [uBlockOrigin/uAssets#22333]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

ads

### Description

I'm not sure why this is happening though uBlock Origin is no longer blocking ads in my gmail 'Promotions' and 'Social' tabs.
Everything is up-to-date though still, ads are there..

Any help or advice would be great!

### Other extensions used

Honey
Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![CleanShot 2024-02-04 at 17 02 34](https://github.com/uBlockOrigin/uAssets/assets/20275949/b517b8e9-e275-4df5-9fed-19302dcd0bb6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 146262
 cosmetic: 238837
 scriptlet: 50537
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28517-30, now
  adguard-generic: 82379-490, now
  adguard-mobile-app-banners: 4932-8, now
  adguard-other-annoyances: 14128-8, now
  adguard-popup-overlays: 26926-93, now
  adguard-social: 22112-880, now
  adguard-widgets: 2430-3, now
  easylist-annoyances: 4335-266, now
  easylist-chat: 180-13, now
  easylist-newsletters: 6920-483, now
  easylist-notifications: 2925-1467, now
  fanboy-cookiemonster: 49708-3811, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 80284-1788, now
  easyprivacy: 43378-254, now
  plowe-0: 3784-1190, now
  ublock-badware: 7829-322, now
  ublock-filters: 36953-3849, now
  ublock-privacy: 998-8, now
  ublock-quick-fixes: 164-9, now
  ublock-unbreak: 2204-102, now
  urlhaus-1: 8235-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 499 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 10
 network:
  google.com: 10
```
</details>

**Comment by ItsProfessional** [comment]
I can't reproduce.

> `[4 lists not shown]: [too many]`

You are using a somewhat modified configuration of uBO. Check if resetting uBO to defaults helps.

**Comment by joshzee** [comment]
Hi @ItsProfessional,

Unfortunately it didn't do a thing :( 

There must be a way I can pinpoint the parent element of this and at least `disply:none` some custom script or something..

![](https://github.com/uBlockOrigin/uAssets/assets/20275949/ac3f0ba5-7f9f-422e-8839-89bafbb0ef7c)

It looks like the ads get inserted about .15 secs after changing tabs to 'Promotions'.

Ahhh why uBlock why. Anything to do with Sonoma and new Macbook you think?

**Comment by u-RraaLL** [comment]
Is it always the first row or are there more of these?

Can you right-click the full row line (`tr`) > copy outer html > paste the contents to `logpasta.com` and share it?
