### ISSUE TITLE
checkout.steampowered.com: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#22337]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://checkout.steampowered.com/checkout/?purchasetype=self&cart=4957968626672798304&snr=1_8_4__503`

### Category

breakage

### Description

When selecting Visa, the input field for the card number is not shown. However, after selecting Mastercard and Visa again, it is shown.

### Other extensions used

ahfgeienlihckogmohjhadlkjgocpleb : Chrome Web Store : version 0_2
cjpalhdlnbpafiamejdnhcphjbkeiagm : uBlock Origin : version 1_55_0
cnpniohnfphhjihaiiggeabnkjhpaldj : Image Downloader : version 3_4_2
dnhpnfgdlenaccegplpojghhmaamnnfp : Augmented Steam : version 2_6_0
donbcfbmhbcapadipfkeojnmajbakjdc : Ruffle - Flash Emulator : version 0_1_0_1107
efkkjffdefaaioagghcaflicdajfhceo : Web Timer : version 1_4_9
eignhdfgaldabilaaegmdfbajngjmoke : Black Menu for Google™ : version 25_34_0
emehklffcaphknhhfhadkjhpfapcbpco : Strong Password Generator : version 1_6
eokjikchkppnkdipbiggnmlkahcdkikp : Herramienta de selección de color - Geco : version 1_0_7
gddbgllpilhpnjpkdbopahnpealaklle : descargador de videos - CocoCut : version 3_14
ghbmnnjooekpmoecnnnilnnbdlolhkhi : Documentos de Google sin conexión : version 1_73_0
gppongmhjkpfnbhagpmjfkannfbllamg : Wappalyzer - Technology profiler : version 6_10_67
hdghceafmahkdiaoenecabpfokplecfi : Black Menu for Wikipedia : version 5_16_3
ibkoenhablealnikeefmjineccmgegmh : Bitdefender Password Manager : version 1_3_0
icncamkooinmbehmkeilcccmoljfkdhp : Wolfram|Alpha (Official) : version 2_0
idmnciiknelklflhdlnkokcoihkidkln : Dark Space : version 2
ifbmcpbgkhlpfcodhjhdbllhiaomkdej : Copiar y pegar de Office Online : version 0_1_11_5
jgjaeacdkonaoafenlfkkkmbaopkbilf : ChatGPT for Google : version 4_3_8
jjicbefpemnphinccgikpdaagjebbnhg : CSFloat Market Checker : version 3_2_4
johejpedmdkeiffkdaodgoipdjodhlld : Chessvision.ai Chess Position Scanner : version 3_4_1
kdbmhfkmnlmbkgbabkdealhhbfhlmmon : SteamDB : version 3_7_9
llimhhconnjiflfimocjggfjdlmlhblm : Reader Mode : version 1_3_5
lpcaedmchfhocbbapmcbpinfpgnhiddi : Extensión de Google Keep para Chrome : version 4_24042_600_1
mcbpblocgmgfnpjjppndjkmgjaogfceg : Captura de página completa - FireShot : version 1_12_18
meagmjlgkihmljnchdjagbcgfclobkho : Trustpilot : version 1_93_0
mfengiknfnndchbhjmgjjffjndklkpcm : Remove YouTube End Cards & End Screen Videos : version 1_0_4
mffmjlddchdccijipncbjhoabgmphjfb : Vimego - Descargador de videos de Vimeo™ : version 1_5_32
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
mhnlakgilnojmhinhkckjpncpbhabphi : MaxAI.me: Usa IA en cualquier lugar con un solo clic : version 2_5_4
mmioliijnhnoblpgimnlajmefafdfilb : Shazam: identifica música desde tu navegador : version 2_1_2
mmpokgfcmbkfdeibafoafkiijdbfblfg : Merge Windows : version 1_5_0_0
mnjggcdmjocbbbhaepdhchncahnbgone : SponsorBlock para YouTube - Omitir Sponsors : version 5_5_4
nakplnnackehceedgkgkokbgbmfghain : Fakespot Fake Amazon Reviews and eBay Sellers : version 0_9_44
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_21
nlipoenfbbikpbjkfpfillcgkoblgpmj : Impresionante captura de pantalla y grabador de pantalla : version 4_4_8
nmmhkkegccagdldgiimedpiccmgmieda : Sistema de pagos de Chrome Web Store : version 1_0_0_6
nnpljppamoaalgkieeciijbcccohlpoh : Link Redirect Trace : version 1_0_0_0
oeopbcgkkoapgobdbedcemjljbihmemj : Checker Plus for Gmail™ : version 25_0_6
ofpnmcalabcbjgholdjcjblkibolbppb : Monica - Tu asistente de inteligencia artificial ChatGPT4 : version 4_7_3
ponfpcnoihfmfllpaingbgckeeldkhle : Enhancer for YouTube™ : version 2_0_122

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![FireShot Capture 002 - Comprar - checkout steampowered com](https://github.com/uBlockOrigin/uAssets/assets/43375046/6b64ac9e-eae9-4c9d-bac0-d9516d5d0540)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 118794
 cosmetic: 51656
 scriptlet: 20692
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80431-14, now
  easyprivacy: 43332-48, now
  plowe-0: 3784-1178, now
  spa-0: 3843-19, now
  spa-1: 5383-218, now
  ublock-badware: 7829-137, now
  ublock-filters: 36989-225, now
  ublock-privacy: 998-6, now
  ublock-quick-fixes: 173-32, now
  ublock-unbreak: 2204-33, now
  urlhaus-1: 8235-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 691 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by u-RraaLL** [comment]
No issues on my side. Disable ALL other extensions and test.

**Comment by rodrigosambadesaa** [comment]
With only uBlock Origin enabled, the issue does not appear. I will test with extension was causing the problem.

**Comment by ItsProfessional** [comment]
Next time, check if it's another extension causing the issue before blindly assuming it's uBO.

**Comment by rodrigosambadesaa** [comment]
The issue was caused by the extension ibkoenhablealnikeefmjineccmgegmh : Bitdefender Password Manager : version 1_3_0
