### ISSUE TITLE
FlashX.Tv [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2233]
URL(s) where the issue occurs

`https://playview.io/`

Describe the issue

``https://streamable.com/gf2i1``

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by smed79** [comment]
@okiehsch mining at `http://flashx.pw/embed-supydaho1ptm.html`

@ryanbr fyi.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7fea8ceba15b3b40a6b9234c631ec5fe9c64d20c
