### ISSUE TITLE
strava.com: breakage

### ISSUE THREAD

**Issue by nessatse** [uBlockOrigin/uAssets#22335]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.strava.com/dashboard`

### Category

breakage

### Description

Page only loads partially, seems some assets are blocked by uBo (requires login account on Strava)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/5959951/70b30f59-627e-411b-beeb-a363c93e55db)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116447
 cosmetic: 45352
 scriptlet: 18843
 html: 2072
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37475-114, 37m Δ
  ublock-badware: 7833-10, 37m Δ
  ublock-privacy: 994-0, 37m Δ
  ublock-unbreak: 2250-0, 37m Δ
  ublock-quick-fixes: 157-0, 37m Δ
  easylist: 80391-643, 37m Δ
  easyprivacy: 43379-868, 37m Δ
  urlhaus-1: 8235-0, 37m
  plowe-0: 3784-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 277 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 77
 network:
  branch.io: 1
  d3nn82uaxijpm6.cloudfront.net: 75
  googletagmanager.com: 1
```
</details>

**Comment by todeveni** [comment]
[Offending filter/commit](https://github.com/easylist/easylist/commit/6011f61e4fb4dcc27d3edcbf00c5626e5619177c) can be found in EasyPrivacy list.

**Comment by ItsProfessional** [comment]
@ryanbr

**Comment by mapx-** [comment]
fixed by EP
https://github.com/easylist/easylist/commit/007a89d
