### ISSUE TITLE
msn.com: ads

### ISSUE THREAD

**Issue by UserPizza** [uBlockOrigin/uAssets#22330]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.msn.com/es-es/eltiempo/prevision/in-Madrid,Comunidad-de-Madrid
```

### Description

blocks of ads in the gallery of `msn.com` weather

is this related by the ad-blocker or the website? i never see that in other sites.. is a long URL starting with `localhost:8080` 

in yellow:

![1](https://github.com/uBlockOrigin/uAssets/assets/146446273/12fde001-1906-4f29-a5ac-c6832d7aa201)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 118961
 cosmetic: 53396
 scriptlet: 25206
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6615-29, 4h.11m Δ
 default:
  user-filters: 0-0, never
  easylist: 80255-14, 4h.11m Δ
  easyprivacy: 43378-48, 4h.11m Δ
  plowe-0: 3786-1177, 5d.22h.27m
  spa-0: 3843-19, 20h.47m
  spa-1: 5383-218, 21h.47m
  ublock-badware: 7808-137, 4h.11m Δ
  ublock-filters: 36954-227, 4h.11m Δ
  ublock-privacy: 998-6, 4h.11m Δ
  ublock-quick-fixes: 164-8, 4h.11m Δ
  ublock-unbreak: 2206-34, 4h.11m Δ
  urlhaus-1: 8240-0, 20h.47m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 168 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by UserPizza** [comment]
I forgot to write that the blocked filter seen in the image seems to work

**Comment by mapx-** [comment]
`msn.com##[style^="grid-area"]:has([class^="nativeAd"])`
or
`||assets.msn.com/*/libs_ad-service$script,1p`

@ryanbr

**Comment by stephenhawk8054** [comment]
@Yuki2718 About https://github.com/uBlockOrigin/uAssets/issues/26965 , I can reproduce when simulating phone on Firefox desktop while using VPN to Singapore. I can see the same on desktop too.

These work for me:

```adb
||assets.msn.com/content/v1/cms/api/amp/Document/
msn.com##div[id^="nativead"]
```

**Comment by Yuki2718** [comment]
`||assets.msn.com/content/v1/cms/api/amp/Document/` looks a bit risky, though I don't know.

**Comment by stephenhawk8054** [comment]
They are XHRs, in the form of `https://assets.msn.com/content/v1/cms/api/amp/Document/BBIfqX9`.

I just checked and actually our old scriptlet just... prunes the whole XHR

```adb
www.msn.com##+js(json-prune-fetch-response, *, list.*.link.ad list.*.link.kicker, propsToMatch, url:content/v1/cms/api/amp)
```

It doesn't match now maybe because of the condition `list.*.link.ad list.*.link.kicker` is not matched any more.

**Comment by Yuki2718** [comment]
If `msn.com##div[id^="nativead"]` works by itself, I'll refrain from adding the network filter to EL.

**Comment by Yuki2718** [comment]
uBO doesn't need scriptlet to hide elements in shadow DOM.

**Comment by gorhill** [comment]
@kodiakhub You should be able to use the pseudo operator `:shadow()` to do this. From the official AG documentation, I believe the equivalent cosmetic filter would be:

    msn.com##shopping-sd-card:shadow(.me-stripe-tile-content.me-stripe-compact:has(> .ad-container-skyscraper, .ad-container, .vd-ad, cs-native-ad-card-no-hover, display-ads, .display-ad-container, .display-ads-container, .views-right-rail-top-display, #entry-point-hp-wc-banner, .me-stripe-title-subtitle, #displayAdCard, a[href*=".booking.com/"], a[href^="https://amzn.to/"]))

**Comment by stephenhawk8054** [comment]
```css
.me-stripe-tile-content.me-stripe-compact:has(> .ad-container-skyscraper, .ad-container, .vd-ad, cs-native-ad-card-no-hover, display-ads, .display-ad-container, .display-ads-container, .views-right-rail-top-display, #entry-point-hp-wc-banner, .me-stripe-title-subtitle, #displayAdCard, a[href*=".booking.com/"], a[href^="https://amzn.to/"], shopping-sd-card)
```

looks like a pure CSS so I think uBO can hide it without pseudo operator?

**Comment by gorhill** [comment]
Right, it would work if the selector doesn't cross shadow DOM boundaries. But I can't tell what is the best solution, on my side I don't even get a match with the base selector `shopping-sd-card` at `msn.com`.

**Comment by gorhill** [comment]
A plain CSS selector works:

    msn.com##.me-stripe-tile-content.me-stripe-compact:has(> .ad-container-skyscraper, .ad-container, .vd-ad, cs-native-ad-card-no-hover, display-ads, .display-ad-container, .display-ads-container, .views-right-rail-top-display, #entry-point-hp-wc-banner, .me-stripe-title-subtitle, #displayAdCard, a[href*=".booking.com/"], a[href^="https://amzn.to/"], shopping-sd-card)

**Comment by gorhill** [comment]
> didn’t see anything in the uBO logger showing that it was blocked

Because the targeted elements lie deep into nested shadow DOM nodes, they can't be found using `querySelector()`. Anything targeted by plain CSS selectors sitting inside a shadow node can't be looked up by the logger code. I didn't try but other blockers quite probably also suffer this limitation.
