### ISSUE TITLE
music.youtube.com: ads

### ISSUE THREAD

**Issue by ARDivlji** [uBlockOrigin/uAssets#22339]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://music.youtube.com/watch?v=sbTVZMJ9Z2I&list=RDAMVMsbTVZMJ9Z2I`

### Category

ads

### Description

It just shows the ads, and I can't get rid of them

### Other extensions used

Return Youtube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 115888
 cosmetic: 45417
 scriptlet: 20326
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80193-14, 2d.2h.29m
  easyprivacy: 43332-48, 2h.46m Δ
  plowe-0: 3787-1177, 2d.2h.29m
  ublock-badware: 7829-136, 2h.46m Δ
  ublock-filters: 36990-210, 2h.46m Δ
  ublock-privacy: 998-6, 2h.46m Δ
  ublock-quick-fixes: 173-32, 2h.46m Δ
  ublock-unbreak: 2204-31, 2h.46m Δ
  urlhaus-1: 7925-0, 1h.46m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1148 ms (selfie)
 maxAssetCacheWait: 217 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  youtube.com: 8
  doubleclick.net: 2
  google.com: 3
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.video-ads
```
</details>

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20586
