### ISSUE TITLE
op.gg: ads

### ISSUE THREAD

**Issue by MrTorfick** [uBlockOrigin/uAssets#22349]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.op.gg/champions?tier=emerald_plus&position=all`

### Category

ads

### Description

It seems that op.gg is using an ad, to advertise their ad-free version of op.gg.

### Other extensions used

BetterTV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/86810991/89d4d79c-331f-49fa-81de-ee2bd8bb482f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116249
 cosmetic: 45411
 scriptlet: 20335
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80537-14, 1h.18m Δ
  easyprivacy: 43335-48, 1h.18m Δ
  plowe-0: 3784-1178, now
  ublock-badware: 7829-137, 1h.18m Δ
  ublock-filters: 37009-210, 1h.18m Δ
  ublock-privacy: 998-6, 1h.18m Δ
  ublock-quick-fixes: 170-31, 1h.18m Δ
  ublock-unbreak: 2204-31, 1h.18m Δ
  urlhaus-1: 7930-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 525 ms (selfie)
 maxAssetCacheWait: 207 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 24
 network:
  cleanhaircut.com: 1
  doubleclick.net: 2
  google.com: 7
  googletagmanager.com: 2
  riotgames.com: 1
  vntsm.com: 1
  zendesk.com: 10
 extended:
  ###banner-container
  ##.vm-placement
  ##div[class^="css-"]:has(> div:not([class], [id]) > .vm-placemen…
  ###top-banner-ad
  ##.AdSense
  ##[id^="div-gpt-ad"]:not([class]):upward(div[class])
  ##+js(abort-on-property-write, lifeOnwer)
  ##+js(no-setTimeout-if, adblock, 2000)
```
</details>

**Comment by Daxy7** [comment]
For uBO annoyances list:

`op.gg##.adTd`



`op.gg##.adfree-banner`
   | 
   V
https://github.com/uBlockOrigin/uAssets/assets/91396482/65388654-9f78-4fc8-917c-3dcb0abdc66d

**Comment by ItsProfessional** [comment]
It's self promotion. @stephenhawk8054 should we block this one in the annoyance list?

**Comment by stephenhawk8054** [comment]
@ItsProfessional I can't access the site now. If you think it's annoying enough, you can add it.

**Comment by stephenhawk8054** [comment]
@ItsProfessional I think the site is `op.gg`, not `top.gg`?

**Comment by ItsProfessional** [comment]
I accidentally added it there, fixed it now: https://github.com/uBlockOrigin/uAssets/commit/01532093a9024b21b05205e9f59f2351849c2e15
