### ISSUE TITLE
strava.com: breakage

### ISSUE THREAD

**Issue by Clown007** [uBlockOrigin/uAssets#22340]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.strava.com/dashboard`

### Category

breakage

### Description

Website not fully loaded

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 118564
 cosmetic: 50277
 scriptlet: 20329
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  DEU-0: 7244-0, now
  easylist: 80512-21, now
  easyprivacy: 43335-57, now
  plowe-0: 3784-1179, now
  ublock-badware: 7829-137, now
  ublock-filters: 36998-225, now
  ublock-privacy: 998-6, now
  ublock-quick-fixes: 172-31, now
  ublock-unbreak: 2204-33, now
  urlhaus-1: 7925-0, now
filterset (user): [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 40
 network:
  branch.io: 1
  d3nn82uaxijpm6.cloudfront.net: 38
  googletagmanager.com: 1
```
</details>

**Comment by huyszn** [comment]
Continue in #22335
