### ISSUE TITLE
frdl.to: nuisance

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#22341]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://frdl.to/2dpp08ljxcbs`

### Category

nuisance

### Description

timer

`frdl.to##+js(nano-stb, downloadbtn)`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Timer](https://github.com/uBlockOrigin/uAssets/assets/20126984/d8001e84-0e1e-4a40-a6b2-fc84c3015185)

</details>

### Configuration

<details>

uBlock Origin: 1.55.1b28 + uBlock filters – Annoyances
Chromium: 120

</details>

**Comment by ItsProfessional** [comment]
There's a server sided check.

https://github.com/uBlockOrigin/uAssets/assets/63961221/7168458c-3fae-472e-9754-0893214cd649
