### ISSUE TITLE
[nsfw] pholder.com: ads

### ISSUE THREAD

**Issue by G-D-B-9-9** [uBlockOrigin/uAssets#22342]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pholder.com/u/marknight95/`
`https://pholder.com/r/bigboobsgw/`

### Category

ads

### Description

Chaturbate.com ads at pholder.com NSFW subs /r/ and /u/ userpages.
Url path system is similar to that of Reddit. For example:
`https://pholder.com/u/marknight95/`
`https://pholder.com/r/bigboobsgw/`

### Other extensions used

Violentmonkey
Twitter UI Customizer

AdAway Android with several hosts file block lists. 

### Screenshot(s)

<details>
<summary>Screenshot of AdAway hosts lists</summary>

![Screenshot_20240204-201850_1](https://github.com/uBlockOrigin/uAssets/assets/82726385/ea5db1bd-7a04-429e-bd86-32259a501e30)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 110
filterset (summary):
 network: 59313
 cosmetic: 77619
 scriptlet: 25696
 html: 0
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  urlhaus-1: null
 added:
  adguard-cookies: 28517-1600, 1h.18m
  fanboy-cookiemonster: 49729-19643, 1h.18m
  ublock-cookies-adguard: 959-19, 1h.18m
  ublock-cookies-easylist: 959-959, 1h.18m
 default:
  user-filters: 0-0, never
  easylist: 80512-16057, 1h.18m
  ublock-filters: 37343-397, 1h.18m
  ublock-privacy: 998-4, 1h.18m
  ublock-quick-fixes: 172-31, 1h.18m
  ublock-unbreak: 2209-14, 1h.18m
filterset (user): [empty]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 917 ms (selfie)
 maxAssetCacheWait: 539 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by huyszn** [comment]
There are also ad placeholders on SFW pages like `https://pholder.com/r/food/` and `https://pholder.com/u/all-top-today_ss/`

**Comment by G-D-B-9-9** [comment]
I have Easylist both in AdAway and in browser as hosts file was leaking some ads - but those Chaturbate ads are terrible and so annoying.

**Comment by Daxy7** [comment]
why not just use `https://old.reddit.com/r/BigBoobsGW/`?

**Comment by G-D-B-9-9** [comment]
Pholder.com is not a mirror while it has lot's of on site Reddit content but much more an archive.
