### ISSUE TITLE
yandex.uz: [unknown]

### ISSUE THREAD

**Issue by Otkritka** [uBlockOrigin/uAssets#22348]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yandex.uz/pogoda/tashkent?utm_source=serp&utm_campaign=helper&utm_medium=desktop&utm_content=helper_desktop_main&utm_term=title&lat=41.311151&lon=69.279737`

### Category

[unknown]

### Description

Advertising on Yandex

### Other extensions used

No other extensions

### Screenshot(s)
![yandex uz-ПрогнозпогодывТашкентена10дней—Яндекс Погода](https://github.com/uBlockOrigin/uAssets/assets/55092038/ac88abf7-2d27-47ae-9f96-dd06b62d93de)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 109
filterset (summary):
 network: 156615
 cosmetic: 179925
 scriptlet: 47764
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82393-649, now
  easylist-annoyances: 4340-66, now
  easylist-chat: 180-0, now
  easylist-newsletters: 6920-24, now
  easylist-notifications: 2925-116, now
  fanboy-cookiemonster: 49729-200, now
  fanboy-social: 16103-19, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6624-122, 1h.13m Δ
  ublock-cookies-easylist: 921-921, now
 default:
  user-filters: 5-0, never
  RUS-0: 39991-9, 1h.13m Δ
  easylist: 80537-1757, 1h.13m Δ
  easyprivacy: 43335-283, 1h.13m Δ
  plowe-0: 3784-1193, now
  ublock-badware: 7829-322, 1h.13m Δ
  ublock-filters: 37009-3530, 1h.13m Δ
  ublock-privacy: 998-9, 1h.13m Δ
  ublock-quick-fixes: 170-32, 1h.13m Δ
  ublock-unbreak: 2204-102, 1h.13m Δ
  urlhaus-1: 7930-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 19778 ms (selfie)
 maxAssetCacheWait: 784 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 31
 network:
  360yield.com: 1
  acint.net: 1
  adhigh.net: 1
  adriver.ru: 2
  aidata.io: 1
  betweendigital.com: 1
  bumlam.com: 2
  buzzoola.com: 1
  digitaltarget.ru: 1
  hybrid.ai: 2
  kimberlite.io: 1
  mts.ru: 1
  new-programmatic.com: 1
  otm-r.com: 1
  rambler.ru: 1
  rutarget.ru: 2
  semantiqo.com: 1
  shopnetic.com: 1
  tns-counter.ru: 1
  upravel.com: 1
  uuidksinc.net: 1
  weborama.fr: 1
  whiteboxdigital.ru: 1
  yandex.ru: 3
  yastatic.net: 1
```
</details>

**Comment by Daxy7** [comment]
The rules for this site are contained in [RUS: RU AdList](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt&title=RU%20AdList%20for%20uBO%20only) and [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) (left-click to subscribe).

**Comment by Otkritka** [comment]
> https://yandex.uz/pogoda/tashkent?utm_source=serp&utm_campaign=helper&utm_medium=desktop&utm_content=helper_desktop_main&utm_term=title&lat=41.311151&lon=69.279737

The subscription did not help, the problem has not been solved.
![Uploading yandex.uz-ПрогнозпогодывТашкентена10дней—Яндекс.Погода.jpeg…]()

**Comment by dimisa-RUAdList** [comment]
Something wrong. If the RU AdList: Counters filter had been used, the link would not have contained `utm_`.

**Comment by Otkritka** [comment]
![Снимок](https://github.com/uBlockOrigin/uAssets/assets/55092038/693d4180-445d-4ccb-a6c4-913e1d1a9fb6)

Opera 
Version:95.0.4635.90
System:Windows 7 32-bit
Chromium version:109.0.5414.149
Browser identification
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0

**Comment by dimisa-RUAdList** [comment]
Opera? Ok - https://forums.lanik.us/viewtopic.php?t=32218 (point No. 8), or [here](http://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=13#1) (first paragraph).

**Comment by ItsProfessional** [comment]
"is an actual issue that affects people" -> issue for people who don't care about the ads being hidden (they would otherwise do a tiny bit of research and would've added the separate list.)

**Comment by greetclammy** [comment]
I have both `RU: AdList` and `RU AdList: Counters` enabled, with both filters updated to the latest versions. I'd like to report ads on `https://yandex.lv/weather/`. Do note the `.lv` domain. On any other domains e.g. `yandex.ru`,`yandex.kz`, `yandex.eu` etc. the ads are blocked but on `yandex.lv` they are not blocked. Please add support for `yandex.lv`. Thank you!

<img width="1448" alt="Image" src="https://github.com/user-attachments/assets/7e9554c6-815a-429b-ac57-1fc7f9408660" />

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/5244114954dddcde7eb2064f49cf984fb4562538

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Currently MV3 hasn't implemented wildcard for TLDs yet: https://github.com/w3c/webextensions/issues/394 , so the new filters will be discarded in uBOL. If possible, could you still keep the list of TLDs besides the wildcard, i.e, they will look like this:

```adb
@@||an.yandex.ru/meta/*target-ref=*pogoda$xmlhttprequest,domain=yandex.*|yandex.by|yandex.kz|yandex.ru|yandex.uz|yandex.lv
```

Actually we can add those special filters listing the TLDs in uAssets' own uBOL's list, but since these filters are for `Counters` list, I think it's not good to include them by default.

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Only the ones with wildcard TLDs will be discarded, i.e

```adb
@@||an.yandex.ru/meta/*target-ref=*pogoda$xmlhttprequest,domain=yandex.*|yandex.by
```

will be equivalent to

```adb
@@||an.yandex.ru/meta/*target-ref=*pogoda$xmlhttprequest,domain=yandex.by
```

However, if a rule only contains wildcard domains (without other domains after `domain=`) then the whole rule will be discarded, i.e this will be discarded:

```adb
@@||an.yandex.ru/meta/*target-ref=*pogoda$xmlhttprequest,domain=yandex.*
```

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 This limitation only applies to rules for network requests, such as: `@@||an.yandex.ru/meta/*target-ref=*pogoda$xmlhttprequest,domain=yandex.*|yandex.by` ?

As far as I can see, all scriptlets and hiding rules (Counters) for 4pda.to, containing 4pda.* - are quite functional in uBOL.

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Yes, the wildcard problem only occurs for network rules. Cosmetic/Scriptlet rules are not affected.
