### ISSUE TITLE
https://www.strava.com/dashboard: breakage - multiple JS links are blocked by uBlock

### ISSUE THREAD

**Issue by erlendur-ccp** [uBlockOrigin/uAssets#22345]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.strava.com/`

### Category

breakage

### Description

When loading https://www.strava.com/dashboard then multiple JS files are blocked, rendering the site unusable.

![image](https://github.com/uBlockOrigin/uAssets/assets/4366305/8d0212b1-7747-4402-b66c-21fb57830530)

### Other extensions used

1Password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4366305/3d720c19-ca96-40a7-9ce3-43a4eb2a9a72)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116210
 cosmetic: 45365
 scriptlet: 18863
 html: 2072
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37519-166, 1h.20m Δ
  ublock-badware: 7833-10, 1h.20m Δ
  ublock-privacy: 994-0, 1h.20m Δ
  ublock-unbreak: 2250-0, 1h.20m Δ
  ublock-quick-fixes: 165-0, 1h.20m Δ
  easylist: 80512-643, 1h.20m Δ
  easyprivacy: 43335-839, 1h.20m Δ
  urlhaus-1: 7925-0, now
  plowe-0: 3784-1, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1034 ms (selfie)
 maxAssetCacheWait: 240 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 77
 network:
  branch.io: 1
  d3nn82uaxijpm6.cloudfront.net: 75
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/22335
