### ISSUE TITLE
wallpaperenginefree.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2234]
URL(s) where the issue occurs

`https://www.wallpaperenginefree.com/2018/05/cold-biome-wallpaper-engine.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`@@||wallpaperenginefree.com^$generichide`

**Comment by garry-ut99** [comment]
Ad placeholders all over the site, caused by `ghide` from "uBlock Filters", on both main page and subpages : [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219685721-5848d892-ceed-4fbc-beed-f4499f6242b5.png), I get no AA with `ghide` off but there is AA still in the source code.
