### ISSUE TITLE
decrypt.day: detection

### ISSUE THREAD

**Issue by fuomag9** [uBlockOrigin/uAssets#22359]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://decrypt.day/app/id1599719154`

### Category

detection

### Description

dns block for pagead2.googlesyndication.com gets detected (even with ublock origin off)

safari + adguard works

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/1580624/6cde5156-cd8b-48ce-b256-26abd3069a6d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 316186
 cosmetic: 253210
 scriptlet: 51385
 html: 0
listset (total-discarded, last-updated):
 added:
  ITA-0: 8319-18, now
  adguard-cookies: 28526-30, now
  adguard-generic: 82479-520, now
  adguard-mobile: 9042-51, now
  adguard-mobile-app-banners: 4934-8, now
  adguard-other-annoyances: 14140-12, now
  adguard-popup-overlays: 26939-95, now
  adguard-social: 22122-881, now
  adguard-spyware: 94438-1203, now
  adguard-spyware-url: 1438-5, now
  adguard-widgets: 2430-7, now
  block-lan: 56-0, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 80307-2124, now
  easyprivacy: 43336-26355, now
  plowe-0: 3784-1677, now
  ublock-badware: 7848-334, now
  ublock-filters: 37065-3909, now
  ublock-privacy: 998-415, now
  ublock-quick-fixes: 159-31, now
  ublock-unbreak: 2204-149, now
  urlhaus-1: 7800-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 409 ms (selfie)
 maxAssetCacheWait: 268 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 16
 network:
  cloudflareinsights.com: 1
  google.com: 6
  googletagmanager.com: 1
  mzstatic.com: 8
 extended:
  ##iframe[name="googlefcPresent"]
  ##+js(adjust-setInterval, update, *, 0.001)
```
</details>

**Comment by JobcenterTycoon** [comment]
Should work fine now. In rare cases a anti adblock can still appear but a reload should help.

**Comment by Daxy7** [comment]
`https://decrypt.day/app/id850251209/dl/cls9nuozo03u1ojy0lahewde3`
is it possible to skip the 5 second wait here

**Comment by JobcenterTycoon** [comment]
Fixed in the annoyance list.
