### ISSUE TITLE
uktvplay.co.uk: detection

### ISSUE THREAD

**Issue by Will-Glyphica** [uBlockOrigin/uAssets#22358]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://uktvplay.co.uk/shows/madam-secretary/watch-online
```

### Description

They seem to have updated their website and with it updated their ad block detection as it was working okay previously. It does require an account to access and is likely restricted to the UK.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot_2](https://github.com/uBlockOrigin/uAssets/assets/52570899/b53e84ed-431f-42bc-aacc-bc2ef0c6ea28)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 115935
 cosmetic: 45425
 scriptlet: 20361
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80319-14, 12m
  easyprivacy: 43359-48, 12m
  plowe-0: 3784-1178, 12m
  ublock-badware: 7829-136, 12m
  ublock-filters: 37065-210, 12m
  ublock-privacy: 998-6, 12m
  ublock-quick-fixes: 163-31, 12m
  ublock-unbreak: 2204-31, 12m
  urlhaus-1: 7800-0, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 737 ms
 maxAssetCacheWait: 12 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 49
 network:
  ati-host.net: 18
  fwmrm.net: 3
  googletagmanager.com: 1
  onetrust.com: 1
  sentry.io: 25
  thefilter.com: 1
 extended:
  ##+js(no-xhr-if, fwmrm.net)
```

</details>

**Comment by liamengland1** [comment]
Test `uktvplay.co.uk##+js(no-fetch-if, fwmrm.net)`

**Comment by Will-Glyphica** [comment]
That works great, thanks.
