### ISSUE TITLE
nytimes.com: detection

### ISSUE THREAD

**Issue by jo99jo** [uBlockOrigin/uAssets#22355]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nytimes.com/2024/02/05/business/economy/nevada-economy-primary-election.html`

### Category

detection

### Description

As of Monday morning, when UBO enabled, NYT pages show the page as very faded.  Turning off UBO shows a regular page.

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-02-05  NYT faded screen using UBO](https://github.com/uBlockOrigin/uAssets/assets/48929420/2ad077a3-53d6-4fdc-8bae-7d06e2aad270)

</details>

1. 

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 115927
 cosmetic: 45421
 scriptlet: 20344
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 170-31, now Δ
 default:
  user-filters: 23-1, never
  easylist: 80324-14, now Δ
  easyprivacy: 43336-48, now Δ
  plowe-0: 3784-1178, 37m
  ublock-badware: 7829-136, now Δ
  ublock-filters: 37025-210, now Δ
  ublock-privacy: 998-6, now Δ
  ublock-unbreak: 2204-31, now Δ
  urlhaus-1: 7800-0, 37m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 316 ms (selfie)
 maxAssetCacheWait: 121 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 35
 no-cosmetic-filtering: true
 no-popups: true
 network:
  nytimes.com: 10
  amazon-adsystem.com: 1
  datadoghq-browser-agent.com: 1
  doubleclick.net: 1
  geoedge.be: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  nyt.com: 18
```
</details>

**Comment by liamengland1** [comment]
Can't reproduce, regwall shows up as expected.

![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/fc505dfc-705e-4cc9-b64f-4144913ab121)

**Comment by stephenhawk8054** [comment]
Can you test in a new browser profile with only uBO and its default settings?

**Comment by Daxy7** [comment]
Works for me in the UK. The full page loads but NYTimes also now disallows JS blockage if you have that enabled.
https://github.com/uBlockOrigin/uAssets/assets/91396482/293bde8f-b950-491e-922a-b385d86fa6b9

**Comment by jo99jo** [comment]
I found that if I logged in, the faded page disappeared.

But I can only see part of the article with UBO enabled both in IE and old FF.

**Comment by stephenhawk8054** [comment]
> Can you test in a new browser profile with only uBO and its default settings?

**Comment by Daxy7** [comment]
>  IE and old FF.

Internet Explorer and old Firefox are outdated browsers and should not be used in general web browsing. This is why you are getting "detection." Your configuration details show `Chromium: 121`, use this browser or Edge/Firefox fully updated.
