### ISSUE TITLE
Civitai adblock detection

### ISSUE THREAD

**Issue by nl255** [uBlockOrigin/uAssets#22350]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
Civitai may have NSFW images (though it isn't supposed to unless you are logged in and allow NSFW) but both the image search page (for "cat") and main page was safe for me in a private window.

https://civitai.com/search/images?sortBy=images_v3&query=cat
https://civitai.com/
```

### Description

Civitai is detecting uBlock Origin and displays not only multiple banners insisting on disabling ad blocking but also in the images search will frequently display such an image every so often.  Since it is an image it is not possible to use text matching like in the previous issue on the subject.

### Other extensions used

port authority, hide private mode, google/amazon/facebook container

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/4340587/3d0b5d19-8181-4a8c-bc8e-5861be278df0)
![image](https://github.com/uBlockOrigin/uAssets/assets/4340587/d28565d1-ae32-47c4-9243-b053c3a042d1)

### Configuration

uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 210814
 cosmetic: 246247
 scriptlet: 49568
 html: 2279
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76933-24476, 1d.14h.18m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95778-18671, 8d.23h
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, 1d.2h.23m
  adguard-generic: 82379-6985, 1d.14h.24m
  adguard-mobile: 9033-101, 1d.14h.23m
  adguard-spyware: 90800-26798, 1d.14h.22m
  adguard-spyware-url: 1434-107, 1d.14h.21m
  adguard-social: 22112-137, 1d.14h.20m
  fanboy-thirdparty_social: 68-0, 8d.23h.1m
  ublock-annoyances: 6576-12, 20m
  adguard-mobile-app-banners: 4933-7, 20m
  adguard-other-annoyances: 14129-64, 20m
 default:
  user-filters: 169-11, never
  ublock-filters: 37458-404, 1d.14h.27m
  ublock-badware: 7812-10, 1d.14h.26m
  ublock-privacy: 994-77, 1d.2h.25m
  ublock-unbreak: 2252-0, 1d.14h.25m
  ublock-quick-fixes: 165-0, 8h.24m
  easylist: 80281-738, 5d.21h.50m
  easyprivacy: 43642-895, 2d.13h.35m
  urlhaus-1: 7925-0, 8h.25m
  plowe-0: 3784-1, 2h.57m
filterset (user): [array of 169 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 6 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8303 ms
 maxAssetCacheWait: 6361 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  civitai.com: 2
  cloudflareinsights.com: 1
  stripe.com: 3
 extended:
  ##.grecaptcha-badge
  ##+js(no-fetch-if, googlesyndication)
  ##+js(no-fetch-if, pagead2.googlesyndication.com)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])

**Comment by D4niloMR** [comment]
Go to https://github.com/uBlockOrigin/uAssets/issues/22203
