### ISSUE TITLE
gov.setupgovgr.xyz: badware

### ISSUE THREAD

**Issue by PhoenixFossGR** [uBlockOrigin/uAssets#22353]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
gov.setupgovgr.xyz
gov.setupgovgr.xyz/gr
```

### Description

This website is a phishing/malware site pretending to be the official website of the Greek Government, gov.gr.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by ItsProfessional** [comment]
> phishing/malware site

Provide evidence. I get "Sorry, you have been blocked"

**Comment by ItsProfessional** [comment]
I know it's a phishing site, but that is not enough to fit for the badware list. You said that the site is a "malware site". I asked you to provide a few malware samples from that site.

**Comment by stephenhawk8054** [comment]
I can access the website when using Greece VPN, but the site appears as blank page for me:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/dae39dc9-98ff-4b13-ac2a-213bcc2bac45)

How does it look like on your side?

**Comment by stephenhawk8054** [comment]
Thanks
