### ISSUE TITLE
puzzle-nonograms.com: detection

### ISSUE THREAD

**Issue by Rothlan284** [uBlockOrigin/uAssets#22367]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.puzzle-nonograms.com/`

### Category

detection

### Description

When visiting the website or refreshing the webpage I get this message: 

""**It seems that you may be using an ad blocking software.

We rely on ads to keep this website alive. Ad blockers also disrupt the normal layout and behavoir of the website.

Please allow the ads on the site or join our patron program!

Contact us if you have any questions. Thank you!**""

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 115787
 cosmetic: 45328
 scriptlet: 18906
 html: 2081
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37626-217, now
  ublock-badware: 7853-14, now
  ublock-privacy: 994-0, now
  ublock-unbreak: 2250-0, now
  ublock-quick-fixes: 194-0, now
  easylist: 80323-545, now
  easyprivacy: 43338-885, now
  urlhaus-1: 7550-0, now
  plowe-0: 3785-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 271 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  a-mo.net: 1
  adnxs.com: 1
  criteo.com: 1
  d3mw273ubcaiex.cloudfront.net: 4
  dotomi.com: 1
  doubleclick.net: 1
  e-planning.net: 1
  googletagmanager.com: 1
  lijit.com: 1
  s-onetag.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon Is it the same `puzzle-` sites recently?

**Comment by JobcenterTycoon** [comment]
Fixed the anti adblock in base because its also part of the ad reinsertion.
