### ISSUE TITLE
mobile.de: breakage

### ISSUE THREAD

**Issue by kKmiecik99** [uBlockOrigin/uAssets#22362]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

i got problem with mobile.de. i have to clear cookies and site data every few tabs opened.
![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/10344029/16ab6894-a06e-4c07-834a-d6046fd2c72c)

### A specific URL where the issue occurs.

```yaml
mobile.de
```

### Steps to Reproduce

i was searching for cars and after opening some of advertises i got something like that 
![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/10344029/3dcd3cd2-8685-457e-b1c2-b6dfbd15e595)

### Expected behavior

i expect to open normal page with car i selected

### Actual behavior

![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/10344029/f0f9dc8d-3368-4eed-b870-8d59ada7145d)

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 117157
 cosmetic: 53554
 scriptlet: 19106
 html: 2091
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37611-204, 2h.3m Δ
  ublock-badware: 7853-14, 2h.3m Δ
  ublock-privacy: 994-0, 2h.3m Δ
  ublock-unbreak: 2250-0, 2h.3m Δ
  ublock-quick-fixes: 157-0, 2h.3m Δ
  easylist: 80265-658, 2h.3m Δ
  easyprivacy: 43336-838, 2h.3m Δ
  urlhaus-1: 7550-0, 3h.4m
  plowe-0: 3786-1, 10d.17h.5m
  POL-0: 8727-26, 3h.4m
  POL-2: 1283-12, 1d.21h.23m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 300 ms (selfie)
 maxAssetCacheWait: 92 ms
 cacheBackend: indexedDB
```
</details>

**Comment by JobcenterTycoon** [comment]
Works all fine for me. Looks more like a site issue

**Comment by ItsProfessional** [comment]
Probably a site issue, and even if not, doesn't seem like it's caused by uBO from testing.
