### ISSUE TITLE
watch.lonelil.com: nuisance

### ISSUE THREAD

**Issue by alike-scrambled** [uBlockOrigin/uAssets#22369]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://watch.lonelil.com/`

### Category

nuisance

### Description

Opening Developer Tools causes a redirect to `https://watchlonelil.github.io/#/antitamper`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/159203152/34412b82-6966-4625-ada2-a69219d085bc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 115753
 cosmetic: 45282
 scriptlet: 18903
 html: 2080
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37620-217, 1m
  ublock-badware: 7853-14, 1m
  ublock-privacy: 994-0, 1m
  ublock-unbreak: 2250-0, now Δ
  ublock-quick-fixes: 159-0, now Δ
  easylist: 80280-545, now Δ
  easyprivacy: 43338-885, now Δ
  urlhaus-1: 7550-0, 1m
  plowe-0: 3785-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3331 ms
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  lonelil.com: 1
  cloudflareinsights.com: 2
```
</details>

**Comment by huyszn** [comment]
Enable the `uBlock filters - Annoyances` list
