### ISSUE TITLE
rbtv77.makeup: detection

### ISSUE THREAD

**Issue by Joop4441** [uBlockOrigin/uAssets#22364]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rbtv77.makeup/`

### Category

detection

### Description

the webpage a message popup that says that it detects the ad blocker when trying to access the stream

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 241246
 cosmetic: 361864
 scriptlet: 54470
 html: 2397
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82478-7084, 4m
  adguard-social: 22126-854, 2m
  adguard-cookies: 28550-67, 2m
  ublock-cookies-adguard: 922-0, 2m
  adguard-popup-overlays: 26951-1648, 2m
  adguard-mobile-app-banners: 4942-1077, 2m
  adguard-other-annoyances: 14139-340, 2m
  adguard-widgets: 2431-1, 2m
  easylist-annoyances: 4344-128, 2m
  easylist-chat: 180-13, 2m
  fanboy-cookiemonster: 49806-3879, 2m
  ublock-cookies-easylist: 922-922, 2m
  [41 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37623-741, now
  ublock-badware: 7853-14, now
  ublock-privacy: 994-0, 57m Δ
  ublock-unbreak: 2250-7, now
  ublock-quick-fixes: 159-0, 57m Δ
  easylist: 80280-1371, 1h.57m Δ
  easyprivacy: 43338-1413, 57m Δ
  urlhaus-1: 7550-0, now
  plowe-0: 3785-1, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1551 ms
 maxAssetCacheWait: 182 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  acdcdn.com: 1
  expelledcleaner.com: 11
  googlesyndication.com: 1
  googletagmanager.com: 1
  jsdelivr.net: 1
 extended:
  ##+js(no-xhr-if, googlesyndication)
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue in this thread next time: https://github.com/uBlockOrigin/uAssets/issues/20364
