### ISSUE TITLE
jules.com: breakage

### ISSUE THREAD

**Issue by YS-DooMguy** [uBlockOrigin/uAssets#22368]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.jules.com/fr-fr/tunnel-de-commande/?stage=payment`

### Category

breakage

### Description

I can't write my paycard number in the paycheck page. It work after disable uBlock

### Other extensions used

nothings else

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 115788
 cosmetic: 45335
 scriptlet: 18906
 html: 2081
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 default:
  user-filters: 8-0, never
  ublock-filters: 37626-136, now
  ublock-badware: 7853-14, now
  ublock-privacy: 994-0, now
  ublock-unbreak: 2250-0, now
  ublock-quick-fixes: 194-0, now
  easylist: 80323-643, now
  easyprivacy: 43338-868, now
  urlhaus-1: 7550-0, now
  plowe-0: 3785-1, now
filterset (user): [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 549 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  jules.com: 2
  aticdn.net: 1
  cquotient.com: 1
  curalate.com: 1
  facil-iti.app: 1
  iadvize.com: 1
  kameleoon.eu: 2
  maps.googleapis.com: 1
  netvigie.com: 1
```
</details>

**Comment by Daxy7** [comment]
test
```
@@||aticdn.net^$domain=jules.com
@@||cquotient.com^$domain=jules.com
@@||curalate.com^$domain=jules.com
@@||facil-iti.app^$domain=jules.com
@@||iadvize.com^$domain=jules.com
@@||jules.com^$domain=jules.com
@@||kameleoon.eu^$domain=jules.com
@@||maps.googleapis.com^$domain=jules.com
@@||netvigie.com^$domain=jules.com
```
if it works, replace the above with
```
@@||iadvize.com^$domain=jules.com
@@||jules.com^$domain=jules.com
@@||kameleoon.eu^$domain=jules.com
@@||maps.googleapis.com^$domain=jules.com
@@||netvigie.com^$domain=jules.com
```
if the above doesn't, replace that with
```
@@||aticdn.net^$domain=jules.com
@@||cquotient.com^$domain=jules.com
@@||curalate.com^$domain=jules.com
@@||facil-iti.app^$domain=jules.com
```

**Comment by ItsProfessional** [comment]
> ```yaml
>filterset (user): [array of 8 redacted]
```
@YS-DooMguy Remove your custom filters and test again.

**Comment by peace2000** [comment]
I think there is an issue.

On my end, it looks like this:

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/4f28f42e-fdf1-484a-b376-48aa045e07b6)

I can't write anything.

If I add this exception:

`@@||kameleoon.eu^$script,domain=jules.com`

Those fields will become available and I can write (when those fields are available, they have those grey pre-filled texts on them:

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/a515d77e-3e9c-49dd-b647-d3962d1fcaee)

@YS-DooMguy Can you test adding that exception rule?

**Comment by YS-DooMguy** [comment]
> @@||aticdn.net^$domain=jules.com
> @@||cquotient.com^$domain=jules.com
> @@||curalate.com^$domain=jules.com
> @@||facil-iti.app^$domain=jules.com

It doesn't work for me

**Comment by ItsProfessional** [comment]
Not those. The one that peace2000 provided you:
`@@||kameleoon.eu^$script,domain=jules.com`

**Comment by YS-DooMguy** [comment]
> @peace2000 can you check , i can't reproduce,this is how it looks on my end,i can enter paycard number(**CARTE BANCAIRE**) https://github.com/uBlockOrigin/uAssets/assets/20338483/df5dfc0d-31f5-42c1-91e4-56c1f949ba67


https://github.com/uBlockOrigin/uAssets/assets/55631175/4cc66796-721f-4037-b68e-e1c4af796550

I can't get a cursor when I click in blank fields. Even if I click and tape on my keyboard then nothing happen.

**Comment by YS-DooMguy** [comment]
> ```yaml
> filterset (user): [array of 8 redacted]
> ```

Custom filters are removed. What this that ?: filterset (user): [array of 8 redacted]

**Comment by ItsProfessional** [comment]
Try this:
>Not those. The one that peace2000 provided you: `@@||kameleoon.eu^$script,domain=jules.com`

**Comment by YS-DooMguy** [comment]
> @@||kameleoon.eu^$script,domain=jules.com


https://github.com/uBlockOrigin/uAssets/assets/55631175/f88bed27-3b91-4a24-9d28-38add8d16f95

It doesn't work for me. I don't no why. Look the video. Why it work for you but not for me ?

Even if I block like this :
![kameleoon](https://github.com/uBlockOrigin/uAssets/assets/55631175/c06f7a50-0574-40bc-bbc5-1e263fb585c7)

**Comment by YS-DooMguy** [comment]
> Try this:
> 
> > Not those. The one that peace2000 provided you: `@@||kameleoon.eu^$script,domain=jules.com`

Look above. Does it work for you ?

_It's not very important to me, I just need to deactivate ubo to pay by card. I just want to pass on information to help improve ubo._

**Comment by YS-DooMguy** [comment]
![firefox](https://github.com/uBlockOrigin/uAssets/assets/55631175/a3cc4f08-3d36-4af6-90ec-bc72af34566a)

That works ! I forgot to disable Firefox protection. But I confirm that even without Firefox protection, ubo blocks entry to payment fields.

**Comment by Daxy7** [comment]
> That works !

so the provided filter `@@||kameleoon.eu^$script,domain=jules.com` is working for you and without changing anything else?

**Comment by YS-DooMguy** [comment]
> > That works !
> 
> so the provided filter `@@||kameleoon.eu^$script,domain=jules.com` is working for you and without changing anything else?

Yes it work well. I close the issue
