### ISSUE TITLE
smartbox.com: breakage

### ISSUE THREAD

**Issue by lapoigne** [uBlockOrigin/uAssets#22361]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.smartbox.com/fr/`

### Category

breakage

### Description

The website can't load content.
In the console I can see
> New Relic: A problem occurred when starting up session manager. This page will not start or extend any session.
> ChunkLoadError: Loading chunk 111 failed. (error: https://js-agent.newrelic.com/nr-spa-1.251.1.min.js)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran 2024-02-06 172111](https://github.com/uBlockOrigin/uAssets/assets/1994265/d4efaa81-2cdf-4279-9b7c-849196f59fa3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 135252
 cosmetic: 52195
 scriptlet: 19041
 html: 2080
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37611-136, 44m Δ
  ublock-badware: 7853-14, 44m Δ
  ublock-privacy: 994-0, 44m Δ
  ublock-unbreak: 2250-0, 44m Δ
  easylist: 80265-809, 44m Δ
  easyprivacy: 43336-868, 44m Δ
  urlhaus-1: 7550-0, now
  plowe-0: 3785-1, now
  FRA-0: 27199-391, now
  ublock-quick-fixes: 157-0, 44m Δ
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 666 ms (selfie)
 maxAssetCacheWait: 273 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  newrelic.com: 2
```
</details>

**Comment by lapoigne** [comment]
It work, I will report

**Comment by ItsProfessional** [comment]
@smed79
