### ISSUE TITLE
simplebits.io: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#22376]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://simplebits.io/short/nWP6STl6LKNdFKalytXol`

### Category

detection

### Description

shortlink

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 120
filterset (summary):
 network: 121433
 cosmetic: 38473
 scriptlet: 20421
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 59-0, never
  IDN-0: 9836-3881, 14h.51m
  adguard-mobile: 9031-53, 4d.20h.35m
  easylist: 80149-16112, 4d.20h.35m
  easyprivacy: 43618-60, 4d.20h.35m
  plowe-0: 3786-1251, 4d.20h.35m
  ublock-badware: 7798-137, 4d.20h.35m
  ublock-filters: 37273-495, 4d.20h.35m
  ublock-privacy: 995-7, 4d.20h.35m
  ublock-quick-fixes: 201-3, 1h.37m Δ
  ublock-unbreak: 2211-35, 4d.20h.35m
  urlhaus-1: 7550-0, 13h.50m
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2784 ms (selfie)
 maxAssetCacheWait: 288 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 25
 network:
  a-ads.com: 2
  bmcdn6.com: 1
  cloudflareinsights.com: 7
  coinzillatag.com: 4
  ctengine.io: 2
  d3mzokty951c5w.cloudfront.net: 1
  displayvertising.com: 1
  googletagmanager.com: 5
  jydydmctzxcea.com: 1
  uhsvkgwess.com: 1
 extended:
  ##+js(no-xhr-if, /ads)
  ##+js(no-fetch-if, /ads)
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me. For contributer: Test acc with email inbox `https://www.emailnator.com/inbox/#sede.n.rode.o@gmail.com`

**Comment by D4niloMR** [comment]
Test:

`simplebits.io##+js(nostif, , 3000)`

or

`simplebits.io##+js(aopr, PerformanceObserver)`

**Comment by smaragdina** [comment]
> Test:
> 
> `simplebits.io##+js(nostif, , 3000)`
> 
> or
> 
> `simplebits.io##+js(aopr, PerformanceObserver)`

work fine bro thank..

**Comment by smaragdina** [comment]
> Test:
> 
> `simplebits.io##+js(nostif, , 3000)`
> 
> or
> 
> `simplebits.io##+js(aopr, PerformanceObserver)`

detection again bro :(

**Comment by ItsProfessional** [comment]
continue in #17361
