### ISSUE TITLE
torrentgalaxy.to: breakage

### ISSUE THREAD

**Issue by programatix** [uBlockOrigin/uAssets#22372]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://torrentgalaxy.to/torrents.php
```

### Description

Left panel shutters with blank image placeholders.

Workarounds

1. Disable uBlock, or
2. Disable cosmetic filtering

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Left Panel
![image](https://github.com/uBlockOrigin/uAssets/assets/3293865/eadd3e08-f7dd-4849-9398-05cb420bddc4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 115726
 cosmetic: 45354
 scriptlet: 18910
 html: 2081
listset (total-discarded, last-updated):
 default:
  user-filters: 20-0, never
  ublock-filters: 37635-217, 23m Δ
  ublock-badware: 7853-14, 23m Δ
  ublock-privacy: 994-0, 23m Δ
  ublock-unbreak: 2250-0, 23m Δ
  easylist: 80323-545, 23m Δ
  easyprivacy: 43338-885, 23m Δ
  plowe-0: 3785-1, 10m
  urlhaus-1: 7490-0, 23m
  ublock-quick-fixes: 194-0, 23m Δ
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 24 redacted]
 removed:
  edge-scheme
  moz-extension-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 20153 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  patsincerelyswing.com: 1
 extended:
  ##a[href^="/"][href*="?"][href*="&"]:has(img[src*="picturedent.o…
  ##+js(abort-on-stack-trace, String.prototype.charCodeAt, $)

```
</details>    

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 115706
 cosmetic: 45306
 scriptlet: 20373
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 10-0, never
  easylist: 80265-14, 24m Δ
  easyprivacy: 43336-48, 24m Δ
  plowe-0: 3784-1178, 2d.1h.18m
  ublock-badware: 7849-140, 24m Δ
  ublock-filters: 37088-211, 24m Δ
  ublock-privacy: 998-6, 24m Δ
  ublock-quick-fixes: 164-29, 24m Δ
  ublock-unbreak: 2204-31, 24m Δ
  urlhaus-1: 7490-0, 24m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 353 ms (selfie)
 maxAssetCacheWait: 153 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  patsincerelyswing.com: 1
 extended:
  ##a[href^="/"][href*="?"][href*="&"]:has(img[src*="picturedent.o…
  ##+js(abort-on-stack-trace, String.prototype.charCodeAt, $)
```
</details>

**Comment by JobcenterTycoon** [comment]
Run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes,ublock-filters&manual=1 should work fine now.

**Comment by BlazeFTL** [comment]
Ads are back
