### ISSUE TITLE
socket.pearsoned.com: breakage

### ISSUE THREAD

**Issue by Ap0them** [uBlockOrigin/uAssets#22371]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://socket.pearsoned.com/uiservice/dashboard/0ec4476b-67cb-41d5-bd6c-04849ee450db`

### Category

breakage

### Description

The webpage loads bland

### Other extensions used

Firefox Containers
Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2024-02-06 19-00-57](https://github.com/uBlockOrigin/uAssets/assets/65299214/afc2d50e-c330-4f09-b6b3-ec86d2d7bf3e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 115728
 cosmetic: 45337
 scriptlet: 18909
 html: 2083
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37642-136, now
  ublock-badware: 7853-14, now
  ublock-privacy: 994-0, now
  ublock-unbreak: 2250-0, now
  ublock-quick-fixes: 192-0, now
  easylist: 80324-643, now
  easyprivacy: 43338-868, now
  urlhaus-1: 7490-0, now
  plowe-0: 3785-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 389 ms (selfie)
 maxAssetCacheWait: 122 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  pearsoned.com: 4
  go-mpulse.net: 2
  google-analytics.com: 1
  paypal.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
socket.pearsoned.com##+js(set, initializeNewRelic, noopFunc)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by Ap0them** [comment]
@stephenhawk8054 That works perfectly!
