### ISSUE TITLE
free-mp3-download.net: detection

### ISSUE THREAD

**Issue by purplescorpion1** [uBlockOrigin/uAssets#22378]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://free-mp3-download.net/`

### Category

detection

### Description

Overlay pops up saying adblock is detected please disable adblocking. Works in browser without UblockOrigin installed

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 16487
 cosmetic: 11362
 scriptlet: 18850
 html: 2082
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 default:
  user-filters: 7-0, never
  ublock-filters: 37647-136, 7m
  ublock-badware: 7853-14, 7m
  ublock-privacy: 994-0, 7m
  ublock-unbreak: 2251-0, 7m
  ublock-quick-fixes: 192-0, 7m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 52359 ms (selfie)
 maxAssetCacheWait: 5856 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
Just Comment Here No Need To Open New Issue https://github.com/uBlockOrigin/uAssets/issues/22067
