### ISSUE TITLE
paster.so: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#22377]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://paster.so/sV7jU`

### Category

publicité, layer

### Description

Petite pub en bas à droite de la page

### Other extensions used

aucune qui n'entre en conflit avec uBlock

### Screenshot(s)

https://paster.so/sV7jU
![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/220e912e-92af-40d0-a336-dc03ab286d89)

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 109
filterset (summary):
 network: 135241
 cosmetic: 52234
 scriptlet: 20532
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  FRA-0: 27199-39, now
  easylist: 80280-186, 2m Δ
  easyprivacy: 43338-295, 2m Δ
  plowe-0: 3785-1189, now
  ublock-badware: 7849-155, now
  ublock-filters: 37125-281, now
  ublock-privacy: 998-6, now
  ublock-quick-fixes: 166-29, 2m Δ
  ublock-unbreak: 2205-35, now
  urlhaus-1: 7490-0, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 462 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  getclicky.com: 1
```
</details>

**Comment by 101budspencer** [comment]
@Daxy7 You lack some experience but the /hits endpoint just gets the view count

**Comment by Daxy7** [comment]
Ok. it also removes the api. Removed.

**Comment by HuntArnaud** [comment]
https://paster.so/73Juv
