### ISSUE TITLE
inn.co.il

### ISSUE THREAD

**Issue by XDavidT** [uBlockOrigin/uAssets#2238]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
You should describe the issue, we cannot read your mind.

**Comment by XDavidT** [comment]
v1.16.4
FIREFOX 59.0.3
Ads doesn't block...

**Comment by XDavidT** [comment]
try to block element's but, after refresh they came back

**Comment by mapx-** [comment]
You should continue here
https://github.com/easylist/EasyListHebrew/issues/288

reporting where you see the ads (example page)

**Comment by mapx-** [comment]
I get no such ads (using easylist hebrew)

**Comment by XDavidT** [comment]
Try refresh the page, i just now see the one in the screenshot that i add..

**Comment by mapx-** [comment]
see if helps
```
inn.co.il###divMainRightInfo
inn.co.il##[href^="https://www.inn.co.il/info/"]
||a7.org/*.html$subdocument,domain=inn.co.il
```

**Comment by XDavidT** [comment]
GREAT THX
