### ISSUE TITLE
crunchyroll.com: breakage

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22382]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.crunchyroll.com/de/watch/G14U415QM/im-used-to-it`

### Category

breakage

### Description

Oops! Something went wrong! Overlay: see screenshot in German
There could be an Austrian IP or an Account needed to reproduce.
Reproduced with no other adblock, no other extension, no VPN, and default Google Chrome 
(could be an Adgard filter issue. I'm not sure.) 

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-07 160533](https://github.com/uBlockOrigin/uAssets/assets/100969549/9bb498c7-b993-4a3f-a5fa-ee85c5540d99)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 367819
 cosmetic: 277334
 scriptlet: 52040
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4302-4, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96580-16682, now
  CHN-0: 25762-134, 1h.51m
  JPN-1: 14006-9, 1h.51m
  KOR-1: 4940-21, 1h.54m
  adguard-cookies: 28558-3654, 1h.51m
  [22 lists not shown]: [too many]
 default:
  user-filters: 53-0, never
  DEU-0: 7244-1, 1h.51m
  easylist: 80324-2219, 1h.54m Δ
  easyprivacy: 43338-26503, 1h.51m
  plowe-0: 3785-1691, 1h.51m
  ublock-badware: 7849-345, 1h.51m
  ublock-filters: 37114-3937, 1h.11m
  ublock-privacy: 998-418, 1h.51m
  ublock-quick-fixes: 196-5, 1h.11m
  ublock-unbreak: 2206-156, 1h.51m
  urlhaus-1: 7540-2, 1h.51m
filterset (user): [array of 54 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 89 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 debugScriptlets: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1548 ms (selfie)
 maxAssetCacheWait: 430 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 21
 network:
  braze.com: 6
  evidon.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  litix.io: 9
  segment.io: 1
 extended:
  ##.share-icon
  ##.erc-upsell-popup > div.erc-upsell-popup-body
  ##.erc-upsell-popup::after
  ##+js(set-cookie, _evidon_suppress_notification_cookie, 1)
  ##+js(json-prune, value.media.ad_breaks)
  ##+js(no-setInterval-if, onAdVideoStart)
```
</details>

**Comment by D4niloMR** [comment]
Did you test in a new profile with default uBO?

**Comment by big-cat-loaf** [comment]
I haven't tested it with a new profile, and for default uBO, I have tested it without my own added filters, but for filters like Adgard, I have added them. I will test it again with a new profile and the absolute-only default uBO. (For the breakage to occur, for me, I needed to watch over 20 minutes to achieve it.)

**Comment by ItsProfessional** [comment]
> ```yaml
>  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
>  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4302-4, now
>  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
>  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/>Austria.txt: 24115-0, now
>  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
>  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
>  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: >1361-5, now
>  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96580-16682, now
>  CHN-0: 25762-134, 1h.51m
>  JPN-1: 14006-9, 1h.51m
>  KOR-1: 4940-21, 1h.54m
>  adguard-cookies: 28558-3654, 1h.51m
>  [22 lists not shown]: [too many]
>  ```

You're using a heavily customized configuration of uBO. We can't help users with such a customized configuration of uBO.

> Can someone explain to me why it doesn't work when I turn it off, but when I turn it on, it does???

Then it's a site issue, or it's caused by another extension or DNS blocking.
