### ISSUE TITLE
torrent galaxy rule hides Hot Picks images on the left carousel

### ISSUE THREAD

**Issue by Siderite** [uBlockOrigin/uAssets#22381]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://torrentgalaxy.to/torrents.php
```

### Description

The rule ` torrentgalaxy.to,tgx.rs##a[href^="/"][href*="?"][href*="&"]:has(img[src*="picturedent.org"])` is hiding the Hot Picks torrent on the left side of the screen.

### Other extensions used

None

### Configuration

![image](https://github.com/uBlockOrigin/uAssets/assets/260529/c52cecaf-667e-452f-a523-d566b730f13f)

**Comment by JobcenterTycoon** [comment]
Got fixed hours ago already https://github.com/uBlockOrigin/uAssets/issues/22372

Run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes,ublock-filters&manual=1
