### ISSUE TITLE
foxbusiness.com: video breakage

### ISSUE THREAD

**Issue by chaynes112** [uBlockOrigin/uAssets#22385]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.foxbusiness.com/lifestyle/southwest-airlines-new-seat-design-tiktok-users-sounding-off-just-earned-yourself-delta-customer
```

### Description

When you click a video clip, it just shows a larger version of the image. It doesn't actually play the video.
![foxbusiness](https://github.com/uBlockOrigin/uAssets/assets/70556906/db6c7c9f-21d2-4517-ab21-871e0a7cf14e)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Next time, just continue in the old thread: https://github.com/uBlockOrigin/uAssets/issues/22160 . We all see new comments. No need to open duplicated issue

**Comment by chaynes112** [comment]
Oh, ok. I thought it said that thread was closed and I didn't see any mention of videos failing to load. It said the issue was the article failing to load.

**Comment by chaynes112** [comment]
This appears to be working now.

**Comment by ItsProfessional** [comment]
Yes, because we fixed it.
![image](https://github.com/uBlockOrigin/uAssets/assets/63961221/8a40d99e-9013-45f3-9bee-4673b5dd759b)
