### ISSUE TITLE
businessaccountingbasics.co.uk: breakage 

### ISSUE THREAD

**Issue by KanchiMoe** [uBlockOrigin/uAssets#22388]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.businessaccountingbasics.co.uk/free-accounting-software/
```

### Description

A script/annoyance removes the scroll bar from the browser, preventing the user from scrolling down.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.imgur.com/hkjdtKR.png

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 327039
 cosmetic: 246585
 scriptlet: 49748
 html: 2295
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76935-43926, 3d.5h.34m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 23h.47m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 2h.34m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96261-88376, 5d.2h.28m
  https://winhelp2002.mvps.org/hosts.txt: 8729-2, 3d.5h.36m
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, 3d.5h.36m
  adguard-generic: 82393-6997, 3d.5h.36m
  adguard-mobile: 9034-142, 3d.5h.35m
  adguard-social: 22112-839, 3d.5h.35m
  fanboy-thirdparty_social: 68-0, 5d.2h.29m
  fanboy-cookiemonster: 49705-3824, 4d.5h.36m
  fanboy-social: 16103-17, 2d.5h.52m
  [11 lists not shown]: [too many]
 default:
  user-filters: 83-1, never
  ublock-filters: 37641-433, 4h.34m Δ
  ublock-badware: 7853-19, 4h.34m Δ
  ublock-privacy: 994-0, 4h.34m Δ
  ublock-unbreak: 2252-1, 4h.34m Δ
  easylist: 80349-974, 4h.34m Δ
  easyprivacy: 43341-1212, 4h.34m Δ
  plowe-0: 3784-327, 5d.4h.29m
  urlhaus-1: 7490-0, 23h.47m
  ublock-quick-fixes: 193-0, 4h.34m Δ
filterset (user): [array of 84 redacted]
trustedset:
 added: [array of 31 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 500 ms (selfie)
 maxAssetCacheWait: 364 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  getclicky.com: 1
  impactradius-go.com: 1
  pxf.io: 1
 extended:
  ###mc_embed_signup
  ###mc_embed_signup_scroll
  ##.footer-social
  ##.social-link-facebook
  ##.social-link-twitter
  ###fb-root:not(body):not(html)
  ###cookie-law-info-bar
  ###cookie-law-info-bar ~ .cli-modal-backdrop
  ###cookie-law-info-again
  ###cookie_hdr_showagain
  ###cliSettingsPopup
```
</details>

**Comment by ItsProfessional** [comment]
Broken by easylist as well as AG cookie notices

**Comment by mapx-** [comment]
no breakage on my end

**Comment by ItsProfessional** [comment]
wait a few seconds.

**Comment by Daxy7** [comment]
test
```
businessaccountingbasics.co.uk#@##cookie-law-info-bar
businessaccountingbasics.co.uk#@##cookie-law-info-again
businessaccountingbasics.co.uk#@##cliSettingsPopup

! and remove with
##.wt-cli-cookie-bar-container
businessaccountingbasics.co.uk##body:style(overflow:auto!important)

! remove ads 
##[href^="https://quickbooks.partnerlinks.io/"]
```

**Comment by ryanbr** [comment]
The cookie popup does show, but doesn't break the site
