### ISSUE TITLE
drakescans.com: ads

### ISSUE THREAD

**Issue by ASURA715** [uBlockOrigin/uAssets#22384]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://drakescans.com/series/moon-slayer/chapter-20/`

### Category

ads

### Description

![Screenshot_20240207_220530](https://github.com/uBlockOrigin/uAssets/assets/70307892/ce769e7f-65c4-4158-9543-117458cf98ab)

Remaining ads appearing 

### Other extensions used

![Screenshot_20240207_220705](https://github.com/uBlockOrigin/uAssets/assets/70307892/baa89331-38e1-412c-9d6a-f708cbd7dbe9)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 321799
 cosmetic: 206029
 scriptlet: 49844
 html: 2296
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82521-4626, now
  adguard-spyware-url: 1438-107, now
  adguard-spyware: 94451-27890, now
  block-lan: 56-0, now
  curben-phishing: 91977-33, 25m
  adguard-social: 22133-1559, now
  adguard-cookies: 28562-3846, now
  ublock-cookies-adguard: 965-0, now
  adguard-popup-overlays: 26956-1707, now
  adguard-mobile-app-banners: 5009-1081, now
  adguard-other-annoyances: 14144-348, now
  adguard-widgets: 2431-36, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37987-635, 25m Δ
  ublock-badware: 7847-14, 25m Δ
  ublock-privacy: 994-1, 25m Δ
  ublock-unbreak: 2257-1, 25m Δ
  ublock-quick-fixes: 186-0, 25m Δ
  adguard-mobile: 9050-134, now
  easylist: 80338-18400, 25m Δ
  easyprivacy: 43340-1135, 25m Δ
  urlhaus-1: 7540-0, 25m
  plowe-0: 3785-1, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 691 ms (selfie)
 maxAssetCacheWait: 399 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  drakescans.com: 2
  bidgear.com: 6
  disqus.com: 4
  googlesyndication.com: 3
  googletagmanager.com: 1
  privacymanager.io: 1
  realsrvcdn.com: 1
  viglink.com: 2
  wp.com: 2
 extended:
  ##ins.adsbygoogle
  ##+js(noeval-if, ads)
  ##+js(abort-on-stack-trace, document.createElement, adsBlocked)
  ##+js(abort-current-script, eval, split)
  ##+js(set-constant, adbEnableForPage, false)
  ###email-signup
  ###thread-share-bar
  ##.comment__share > *
  ###thread-subscribe-button
  ##.comment-policy-refresh
  ###placement-top
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by D4niloMR** [comment]
Site issue, same with uBO disabled.

**Comment by ASURA715** [comment]
oh thank you.

**Comment by D4niloMR** [comment]
Oh, you are talking about the close button?

**Comment by ASURA715** [comment]
no the top
![Uploading 303059844-ce769e7f-65c4-4158-9543-117458cf98ab.jpg…]()

**Comment by ASURA715** [comment]
![Uploading 303059844-ce769e7f-65c4-4158-9543-117458cf98ab.jpg…]()

**Comment by ASURA715** [comment]
![303059844-ce769e7f-65c4-4158-9543-117458cf98ab](https://github.com/uBlockOrigin/uAssets/assets/70307892/b6bbe786-3f8c-45bf-8a65-cece55a06bae)

**Comment by ASURA715** [comment]
as you previously mentioned that is a site issue 
it is not a UBO problem.
even when UBO switched of it still appears.

**Comment by D4niloMR** [comment]
Yeah, you can add `drakescans.com##body > :is(.adblock_title, .adblock_subtitle, .adblock_subtitle + div[class=""])` in "My filters" to remove that.
