### ISSUE TITLE
dev.miuiflash.com: detection

### ISSUE THREAD

**Issue by UblockAntiAdblock** [uBlockOrigin/uAssets#22392]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dev.miuiflash.com/what-exactly-is-next-js-and-why-do-we-use-it/`

### Category

detection
It seems that the page changes direction for each refresh

### Description

Click in generarte link

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 115
filterset (summary):
 network: 144760
 cosmetic: 82977
 scriptlet: 36946
 html: 2087
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82558-6065, 8m
 default:
  user-filters: 6-0, never
  ublock-filters: 38004-480, 8m
  ublock-badware: 7847-14, 8m
  ublock-privacy: 994-1, 8m
  ublock-unbreak: 2259-1, 8m
  ublock-quick-fixes: 194-0, 43m Δ
  adguard-mobile: 9051-133, 8m
  easylist: 80355-16557, 8m
  easyprivacy: 50142-856, 8m
  urlhaus-1: 7240-0, 8m
  plowe-0: 3787-1, 8m
  spa-0: 3867-267, 8m
  spa-1: 5414-258, 8m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 prefetchingDisabled: false
 suspendUntilListsAreLoaded: false
 webrtcIPAddressHidden: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 578 ms (selfie)
 maxAssetCacheWait: 265 ms
 cacheBackend: indexedDB
 unsuspendAfter: 223 ms
popupPanel:
 blocked: 1
 network:
  devfiles.pages.dev: 1
 extended:
  ##[id*="div-gpt-ad-"], [id*="google_ads_"]
  ##div[id^="div-gpt-ad"]
  ###featuredimage
  ##+js(trusted-replace-node-text, script, iframe., form.)
  ##+js(trusted-replace-node-text, script, /none'|hidden'|, false'…
  ##+js(trusted-replace-node-text, script, /none"|hidden"/, false"…
  ##+js(trusted-replace-node-text, script, /undefined|null/, false…
  ##+js(trusted-replace-node-text, script, featuredimage', contain…
  ##+js(remove-node-text, script, checkifscript)
  ##+js(trusted-replace-node-text, script, IFRAME", CONTAINER")
  ##+js(addEventListener-defuser, DOMContentLoaded, antiAdBlockerH…
  ##+js(no-xhr-if, /adtrue\.com|eningspon\.com|freychang\.fun|orqu…
  ##+js(no-fetch-if, /a-mo\.net|adnxs\.com|prebid|creativecdn\.com…
```
</details>

**Comment by ItsProfessional** [comment]
duplicate of https://github.com/uBlockOrigin/uAssets/discussions/17361
