### ISSUE TITLE
euronics.ee: breakage

### ISSUE THREAD

**Issue by Kaberniit** [uBlockOrigin/uAssets#22399]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.euronics.ee/tv/televiisorid/58-kuni-68/philips`

### Category

breakage

### Description

When trying to filter out items on the webpage the filter doesn't work when ublock is active. Page won't refresh with filter rules. When I disable ublock, site works as intended or as in M$ Edge... Added 2 screenshots of same page. One with uBlock disabled and page working, other when uBlock is active and page is broken. Red ovals show what is the issue.

### Other extensions used

Only Token Sign (Estonian eID signing thingie..)=

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1018" alt="With_ublock" src="https://github.com/uBlockOrigin/uAssets/assets/154732530/2eedd0d5-db4e-46a6-b559-e872fdaee520">

<img width="959" alt="Disabled_ublock" src="https://github.com/uBlockOrigin/uAssets/assets/154732530/c521f6a5-a2dc-46c3-b18d-67cd5db51aab">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122416
 cosmetic: 45386
 scriptlet: 20394
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80355-14, 1m
  easyprivacy: 50142-35, 1m
  plowe-0: 3787-1185, 1m
  ublock-badware: 7849-140, 1m
  ublock-filters: 37118-211, 1m
  ublock-privacy: 998-6, 1m
  ublock-quick-fixes: 197-4, 1m
  ublock-unbreak: 2206-32, 1m
  urlhaus-1: 7320-0, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 623 ms
 maxAssetCacheWait: 6 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 no-cosmetic-filtering: true
 network:
  facebook.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtm.js$script,domain=euronics.ee
@@||googletagmanager.com/gtag/js$script,domain=euronics.ee
```

@ryanbr

**Comment by Kaberniit** [comment]
Hi. Currently the page is still broken.
