### ISSUE TITLE
cwtv.com: breakage

### ISSUE THREAD

**Issue by Jesssiccaa** [uBlockOrigin/uAssets#22398]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cwtv.com/shows/lost-girl/fae-ge-against-the-machine/?play=cb4396c7-a672-4252-8461-106e642c3a3a`

### Category

detection

### Description

It was working fine the past few days but today the site started messing up the playback. The video will move in slow motion then freeze and buffer. This has happened before when using a different adblocker. It hasn't kicked me off like the other CW thread I saw which is why I'm putting this issue in. I have no idea what most of the settings do so I've been clicking things on and off to see if it helps. 
 I'm a total noob when it comes to coding, the most I've done is some myspace html 15 years ago. So sorry in advance for my iliteracy. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 133236
 cosmetic: 29299
 scriptlet: 20414
 html: 0
listset (total-discarded, last-updated):
 added:
  dpollock-0: 11637-1, 9m
 default:
  user-filters: 0-0, never
  easylist: 80372-16160, 51m Δ
  easyprivacy: 50142-167, 51m Δ
  plowe-0: 3787-1557, 27m
  ublock-badware: 7849-141, 51m Δ
  ublock-filters: 37150-411, 51m Δ
  ublock-privacy: 998-7, 51m Δ
  ublock-quick-fixes: 197-4, 51m Δ
  ublock-unbreak: 2206-33, 51m Δ
  urlhaus-1: 7240-0, 27m
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 collapseBlocked: false
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 554 ms (selfie)
 maxAssetCacheWait: 200 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 43
 no-cosmetic-filtering: true
 network:
  branch.io: 1
  conviva.com: 13
  facebook.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  imrworldwide.com: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  moatads.com: 1
  mparticle.com: 1
  scorecardresearch.com: 21
```
</details>

**Comment by thedatadwarf** [comment]
The following rules suggested by @Daxy7 appear to fix the issue.
```
@@||branch.io^$domain=cwtv.com
@@||conviva.com^$domain=cwtv.com
@@||googletagmanager.com^$domain=cwtv.com
@@||imasdk.googleapis.com^$domain=cwtv.com
@@||imrworldwide.com^$domain=cwtv.com
```

**Comment by stephenhawk8054** [comment]
These are enough to work on my side:

```adb
@@||googleadservices.com/pagead/conversion_async.js^$script,domain=cwtv.com
@@||googletagmanager.com/gtm.js^$script,domain=cwtv.com
```

**Comment by thedatadwarf** [comment]
> These are enough to work on my side with the link `https://www.cwtv.com/shows/lost-girl/fae-ge-against-the-machine/?play=cb4396c7-a672-4252-8461-106e642c3a3a`:
> 
> ```
> @@||googleadservices.com/pagead/conversion_async.js^$script,domain=cwtv.com
> @@||googletagmanager.com/gtm.js^$script,domain=cwtv.com
> ```

My initial testing confirms the these two work on other videos on `cwtv.com`

**Comment by Thortok** [comment]
<img width="840" height="72" alt="Image" src="https://github.com/user-attachments/assets/a569bd7c-99b3-4a9d-b6f9-2f62173aeaef" />

It is uncommon to be specifically told to reopen closed threads that are years old.

My mistake was looking at the 'duplicate' wording of THIS post from 2 years ago which does NOT have the "use old threads" instruction and assuming the instruction was unchanged in the current instruction checklist. There were not any current open issues and the most recent one not marked as a duplicate was closed 2 years ago.

It's also extremely unintuitive. Commenting on a closed post from 2 years ago feels like nobody's going to see it.

You also then lack all the debug log reports and screenshots and everything you get from creating the new issue.

But whatever y'all want, I suppose.

**Comment by stephenhawk8054** [comment]
> It is uncommon to be specifically told to reopen closed threads that are years old.

Because the filters added in the old threads could be the reasons. It's easier for us to track how the issues change.

We are volunteers, not customer supports. We have little free time to investigate different issues from different sites every day. Any users wanting less time for them cost more time for us.

> Commenting on a closed post from 2 years ago feels like nobody's going to see it.

All volunteers are notified with new comments. Don't just assume things. We have threads that last multiple years. 2 years is not that old.

---

Anyone who doesn't agree with this are free to use other tools. As said, we are volunteers, not paid for this and we are stressed enough with different issues from different sites. We won't spend time arguing more. Any further comments about this will be removed.

**Comment by Thortok** [comment]
1 - I didn't see the instruction even though I was carefully attempting to follow all instructions. This confirms there is a potential legibility issue.
2 - I suggest that the instruction be reworded to improve legibility. My suggestion:

"Limit all reports about the same site to a single issue thread. Comment in the old issue threads even if they are closed or even if you have a different problem, so long as it is the same site being reported. (Use this button to find any currently existing threads.)"

3 - Issues: The bolded sentence is AFTER the button to click at which point the reader has left the page and is no longer reading the sentence. Reader may forget to read the rest of the sentence after returning from the search. In addition, it is not intuitive for the user to think the "issue" is a "duplicate" if the last time anyone talked about it was 2 years ago. The user will think their issue is "new" and therefore not a duplicate.

4 - Reasoning for suggestion:  Specifically changing the verbiage to "All reports about the same site, regardless of age" will be more clear and potentially reduce confusion: The user will confirm it's about the same site, and removes the user's need to judge if this is "new" or "duplicate." Moving the link to the final sentence makes it more likely the key instruction is read before the click that leaves the page.

This is my attempt to provide feedback to help prevent this issue from recurring and reduce the workload for you, the volunteers. Thank you for your time and efforts.

Note: It may also help if this instruction was near the button in the actual extension itself. Current is "To avoid burdening volunteers with duplicate reports, please verify that the **issue** has not already been reported. Note: clicking the button will cause the page's origin to be sent to GitHub." Changing 'issue' to 'site' may help prevent confusion on its own, depending on whether or not you want to put the explicit "even if it's closed/old" verbiage right there next to that button as well (I would suggest so if you find a concise way to add it). I bet if you made these changes you would drastically reduce future accidental duplicates.

**Comment by stephenhawk8054** [comment]
We said

We won't spend time arguing more. Any further comments about this will be removed.
--

Don't put more stress and work to us please.

**Comment by Thortok** [comment]
That was not an argument. I did not say "you should not keep issues to a single thread." I attempted to suggest how to prevent this exact mistake from occurring in the future.

In the meantime, do you need anything from me that will actually help with this issue with this site? Any of the information that would contribute to the issue being reported, such as version number, screenshots, anything? All of that was in the other 'new issue' thread.

What do you need to make this more convenient for you?

**Comment by stephenhawk8054** [comment]
Any further comments about this will be removed.
-

**Comment by Thortok** [comment]
You have now created a complete contradiction.

The issue exists, and yet, any comments that indicate the issue exists, will be removed. The ticket even remains in the status of 'closed' despite repeated interaction.

The site continues to not work. Anyone who discovers that, following the instructions, will be directed to this thread, where they are told that any further comments will be removed. So.... the site is just not going to work forever?

What instructions am I supposed to follow at this point? How do I report the issue in the site if in the very thread I'm told to comment in, I'm directly told not to comment at all?

**Comment by stephenhawk8054** [comment]
> Any further comments about **this** will be removed.

`this` is about the report procedure, not about the site's issue.

> That was not an argument. I did not say "you should not keep issues to a single thread." I attempted to suggest how to prevent this exact mistake from occurring in the future.

**Comment by Thortok** [comment]
Then feel free to ignore my feedback about the report procedure. It was only intended to help, you're under no obligation to take my suggestion that was intended to make things easier for you.

The only remaining questions I have about 'the report procedure' is: What now? What details do you need from me now?

All the details about my report are in that other thread, not here. Screenshots, version numbers, everything.

I also noted that the issue was with ubo LITE and this thread was not for UBO lite. (That's another reason I didn't consider this a duplicate, but oh well.)

So again I ask: What are the instructions you want me to follow? How is the report now supposed to be made? The script doesn't give a template for commenting on old threads, only for making new ones. Should I copy-paste that post to here?

Instruct me, please.

**Comment by stephenhawk8054** [comment]
> Then feel free to ignore my feedback about the report procedure. It was only intended to help, you're under no obligation to take my suggestion that was intended to make things easier for you.

Any further comments about that just put more work and stress to us. We said `Any further comments about this will be removed.` so don't continue with that PLEASE.

---

Just wait until the volunteers have time to investigate the site's issue. I've just woke up and first thing we are receiving is a ton of reports about twitter issue and I have barely free time to investigate twitter now. What do you want me to do now? DON'T put more comments about what we said that we won't spend time arguing about that.
