### ISSUE TITLE
cnet.com: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#22391]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cnet.com/health/fitness/5-exercise-snacks-you-can-do-for-heart-health/`

### Category

ads

### Description

content unrelated to article, video ad with resistant code, it auto plays in background, creates 404 when filtering it entirely

health tips = super bowl
https://github.com/easylist/easylist/assets/91396482/45674950-05d3-4696-9390-dbcef2a53057

main
```
https://www.cnet.com/a/neutron/0c6752a.modern.js
```
```
! related
https://www.cnet.com/a/neutron/4479fb0.modern.js
https://www.cnet.com/a/neutron/4607a0b.modern.js
https://www.cnet.com/a/neutron/cbcdc12.modern.js
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 113653
 cosmetic: 49039
 scriptlet: 23912
 html: 2301
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1053-0, now
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 2031-0, now
  ublock-annoyances: 6611-12, now
 default:
  user-filters: 2136-13, never
  ublock-filters: 37658-146, now
  ublock-badware: 7853-14, now Δ
  ublock-privacy: 994-0, now
  ublock-unbreak: 2254-0, now
  ublock-quick-fixes: 194-0, now
  easylist: 80355-319, now
  easyprivacy: 50142-1790, now
filterset (user): [array of 1000 redacted]
switchRuleset:
 added: [array of 10 redacted]
hostRuleset:
 added: [array of 10 redacted]
 removed:
  behind-the-scene * * noop
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1113 ms
 maxAssetCacheWait: 267 ms
 cacheBackend: indexedDB
 unsuspendAfter: 481 ms
popupPanel:
 blocked: 26
 network:
  cnet.com: 1
  2mdn.net: 1
  ads-twitter.com: 1
  amazon-adsystem.com: 1
  clrt.ai: 1
  confiant-integrations.net: 1
  doubleclick.net: 3
  facebook.net: 1
  go-mpulse.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  indexww.com: 1
  moatads.com: 1
  narrativ.com: 1
  onetrust.com: 1
  qualtrics.com: 1
  redventures.io: 2
  sentry.io: 4
  taboola.com: 1
  tiktok.com: 1
 extended:
  ##.c-adDisplay_container
  ##.c-adSkyBox
  ##.c-adDisplay
  ###onetrust-consent-sdk
  ##*:style(border-radius:0px !important;)
  ##+js(xml-prune, VAST, , adnxs)
```
</details>

**Comment by mapx-** [comment]
maybe

```
||cnet.com/a/video-player/$1p
cnet.com##.c-avStickyVideo
```
