### ISSUE TITLE
uploads.to

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#224]
### URL(s) where the issue occurs

https://uploads.to/ui9qc541cj0j

### Describe the issue

BlockAdblock script blocks the page from being accessed by the user as usual.

### Screenshot(s)

https://i.gyazo.com/4c3edce946e9eb832f466b1a10ed45e4.png

### Versions

Browser/version: [here] Chromium 57
uBlock Origin version: [here] 1.10.0

### Settings

Default

**Comment by okiehsch** [comment]
I still can´t download because of issue #154 

If I add
`||uploads.to^$inline-script`
`@@|https://uploads.to^|$inline-script`
I can download while still retaining the ability to upload files.

**Comment by uBlock-user** [comment]
Works fine here without needing that filter, probably an issue on your side.

**Comment by IDKwhattoputhere** [comment]
@uBlock-user It was already fixed so maybe you got the filter update?

**Comment by uBlock-user** [comment]
No, I meant before the update, also I update manually, so it's not the update. I tested it myself when I reported.

**Comment by okiehsch** [comment]
So 
1. Go to `https://uploads.to/ui9qc541cj0j`,
2. Allow inline scripts per dynamic filtering on that site
3. Reload
4. Click anywhere 
5. Result:
![upload](https://cloud.githubusercontent.com/assets/16838044/21284663/8e917532-c422-11e6-9639-4c4304aa977d.JPG)

**Comment by gorhill** [comment]
I was able to reproduce back then, hence why I included the filters.
