### ISSUE TITLE
thepiratebay.org: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#22403]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thepiratebay.org/description.php?id=74426848`

### Category

ads

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/370b654d-c20b-4ed6-acdd-5fb12fc9b2c1)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 133755
 cosmetic: 163262
 scriptlet: 34447
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 9558-0, 39m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 197-0, 39m
  adguard-cookies: 28580-30, 39m
  adguard-other-annoyances: 14152-22, 39m
  adguard-popup-overlays: 26899-77, 39m
  easylist-annoyances: 4344-212, 39m
  easylist-notifications: 2933-398, 39m
  fanboy-cookiemonster: 49946-3810, 39m
  spa-1: 5403-75, 39m
  ublock-annoyances: 6655-223, 39m
  ublock-cookies-adguard: 929-929, 39m
  ublock-cookies-easylist: 929-929, 39m
 default:
  user-filters: 42-1, never
  easylist: 80401-76, 39m
  easyprivacy: 50143-143, 39m
  plowe-0: 3787-1186, 39m
  ublock-badware: 7849-141, 39m
  ublock-filters: 37159-678, 39m
  ublock-privacy: 998-7, 39m
  ublock-quick-fixes: 199-4, 39m
  ublock-unbreak: 2206-37, 39m
  urlhaus-1: 7285-0, 39m
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 31 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2653 ms (selfie)
 maxAssetCacheWait: 1465 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  thepiratebay.org: 1
  d1n3aexzs37q4s.cloudfront.net: 1
  exdynsrv.com: 1
  iconcardinal.com: 1
  onautcatholi.xyz: 1
  ricewaterhou.xyz: 2
  spotscenered.info: 1
  wpadmngr.com: 1
 extended:
  ###ad-bottom
  ##.ad728
  ##.ad468
  ##.ad234
  ##.ad120
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(abort-on-property-read, _wm)
  ##+js(addEventListener-defuser, /^(?:click|mousedown)$/, _0x)
  ##+js(abort-on-property-write, spot)
  ##+js(abort-on-property-read, popjs.init)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
```
</details>

**Comment by Daxy7** [comment]
test
```
||torrindex.net/images/ads/$important
```
@ryanbr

**Comment by LightAndy1** [comment]
For me, this is not fixed. The fake "Download" ad button still appears on the page: 
![image](https://github.com/uBlockOrigin/uAssets/assets/50150516/cc7d3539-3eba-4799-9f31-8157168ef8c6)

**Comment by stephenhawk8054** [comment]
@Yuki2718 Maybe `||torrindex.net/images/ads/`?

**Comment by LightAndy1** [comment]
Or this `thepiratebay.org##[href^="https://cipledecline.buzz/redirect"]`. Idk if this is a good suggestion, I used the element picker from the extension 😅
