### ISSUE TITLE
imleagues.com: detection

### ISSUE THREAD

**Issue by clayostroff** [uBlockOrigin/uAssets#22402]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.imleagues.com/
```

### Description

IMLeagues has anti-adblock and detects ublock origin

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122420
 cosmetic: 45413
 scriptlet: 20421
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80374-14, 1h.46m Δ
  easyprivacy: 50142-35, 1h.46m Δ
  plowe-0: 3784-1184, 2d.14h.43m
  ublock-badware: 7849-140, 1h.46m Δ
  ublock-filters: 37157-211, 1h.46m Δ
  ublock-privacy: 998-6, 1h.46m Δ
  ublock-quick-fixes: 199-4, 1h.46m Δ
  ublock-unbreak: 2206-32, 1h.46m Δ
  urlhaus-1: 7320-0, 5h.36m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 923 ms (selfie)
 maxAssetCacheWait: 169 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by huyszn** [comment]
Do you need to sign into an account to see the detection?

**Comment by clayostroff** [comment]
Not sure. Attaching a screenshot. I have other extensions but I disabled them all to make sure they weren't causing the detection.
<img width="2160" alt="Screenshot 2024-02-08 at 5 31 13 PM" src="https://github.com/uBlockOrigin/uAssets/assets/45951433/557544d2-243c-4b40-b49f-71dc3e4a9687">

**Comment by ItsProfessional** [comment]
Although I can't reproduce, I do see some anti-adb code:
<details>
<summary>Details</summary>

```js
this.updateAnalytics = function (dimensions, uid, path, title, showAds) {
	var adHeight = 0;
	try {
		//// send google analytics page view
		//var setObj = {'&uid': uid};
		//for (var i = 1; i <= dimensions.length; i++) {
		//	//ga('set', 'dimension' + i, dimensions[i - 1]);
		//	setObj['dimension' + i] =  dimensions[i - 1];
		//}
		////ga('set', '&uid', uid);

		// detect ad-blocking
		var ad = document.createElement("imlAdvertisement");
		ad.className = "AdSense";
		ad.style.display = "block";
		ad.style.position = "absolute";
		ad.style.top = "-1px";
		ad.style.height = "1px";
		document.body.appendChild(ad);

		$log.info("ad.ClientHeight: " + ad.clientHeight);
		adHeight = ad.clientHeight;

		var dimSchool = dimensions[0];
		var dimType = dimensions[1];
		var dimGender = dimensions[2];
		var dimAge = dimensions[3];
		var dimStatus = dimensions[4];
		var dimAdmin = dimensions[5];
		var dimGradYear = dimensions[6];
		var dimSport = dimensions[7];
		var dimSeason = dimensions[8];
		var dimAdsBlocked = !ad.clientHeight;
		var dimShowAds = showAds;

		document.body.removeChild(ad);

		gtag("set", "user_properties", {
			user_school: dimSchool,
			user_gender: dimGender,
			user_age: dimAge,
			user_status: dimStatus,
			user_admin: dimAdmin,
			user_gradyear: dimGradYear,
			user_adsblocked: dimAdsBlocked,
			user_showads: dimShowAds,
		});

		gtag("event", "page_view", {
			page_path: path,
			page_title: title,
			page_school: dimSchool,
			page_admin: dimAdmin,
			page_adsblocked: dimAdsBlocked,
			page_showads: dimShowAds,
			page_type: dimType,
			page_sport: dimSport,
			page_season: dimSeason,
		});
		$log.info(
			"Send google analytics page view for " +
				path +
				" with title " +
				title +
				" successfullly."
		);
	} catch (err) {
		$log.error(
			"Send google analytics page view for " + path + " failed due to " + err
		);
	}

	//start detect ad block
	try {
		if (!adHeight) {
			$log.info("Ad is blocked..");
			try {
				$rootScope.$broadcast(constants.events.NOTIFY_AD_BLOCKED_EVENT, null);
			} catch (err) {}
		} else {
			//recheck to prevent the case turn off blocker to login then turn on blocker
			//run this after 1 second since it may has some cost
			setTimeout(function () {
				$.getScript("/spa/ads/show_ads.js?v=414")
					.done(function () {
						$log.info("Ad is not blocked.., see if user are using duckduckgo");
						//use gtag to detect, this will not change even we change ad provider
						$window
							.fetch(
								"https://www.googletagmanager.com/gtag/js?id=G-Y3W5YK5PG2",
								{
									method: "HEAD",
									mode: "no-cors",
								}
							)
							.then(function (response) {
								// If the request is redirected, then the ads are blocked.
								if (response.redirected) {
									$log.info("Ad is blocked..");
									try {
										$rootScope.$broadcast(
											constants.events.NOTIFY_AD_BLOCKED_EVENT,
											null
										);
									} catch (err) {}
								}
							})
							.catch(function () {
								// If the request fails completely, then the ads are blocked.
								$log.info("Ad is blocked..");
								try {
									$rootScope.$broadcast(
										constants.events.NOTIFY_AD_BLOCKED_EVENT,
										null
									);
								} catch (err) {}
							});
					})
					.fail(function () {
						$log.info("Ad is blocked..");
						try {
							$rootScope.$broadcast(
								constants.events.NOTIFY_AD_BLOCKED_EVENT,
								null
							);
						} catch (err) {}
					});
			}, 1000);
		}
	} catch (e) {
		$log.error("Check Ad Block for " + path + " failed due to " + e);
	}
};
```

</details>

@clayostroff Try adding the following to your "My filters" and test again:
```adb
@@||imleagues.com^$ghide
imleagues.com##+js(nostif, blocker)
```

**Comment by clayostroff** [comment]
Unfortunately that didn't work

**Comment by ItsProfessional** [comment]
The `nostif` I wrote earlier would've caused that whole block to not execute, so won't help

**Comment by ItsProfessional** [comment]
@clayostroff Remove ALL extensions, reset uBO to defaults, remove any network-wide blocking and test again.

**Comment by ItsProfessional** [comment]
unable to repro -> closing

**Comment by BlueGadget89** [comment]
I think I found a fix. I resetted uBO to default then I enabled all the annoyances in the filter lists tab, then ctrl + f5 on the site.

**Comment by stephenhawk8054** [comment]
Does the issue still occur?

**Comment by BlueGadget89** [comment]
No it does not

**Comment by automatediceberg** [comment]
This has become an issue again on Safari version 26.0.1, using uBlock Origin Lite 2025.1002.1210. Default settings - neither optimal or complete filtering blocks it

<img width="600" height="424" alt="Image" src="https://github.com/user-attachments/assets/3dc3a9cb-8f05-440c-89e9-cced939fdef3" />

Issue should probably be reopened. I would like to add if you directly open the page (with UBOL) the popup doesn't show, but if you click a link within the site the popup shows and prevents you from doing anything.

**Comment by stephenhawk8054** [comment]
Do we need to sign in? Describe the steps to reproduce the issue in details.

My screen looks like this, and I don't know what to click next:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/e92792d0-ed86-45b6-ab70-054fe74f618e" />

</details>

**Comment by automatediceberg** [comment]
Yes, you need to sign up. What I did was join my school, and that is where the issue shows (on the home page after you sign in). A second issue is not just the anti-adblock/UBOL is detected, but leftover spaces (see left and top)

<img width="1150" height="557" alt="Image" src="https://github.com/user-attachments/assets/b065f667-f779-42fc-b144-c44fcdadeada" />

**Comment by automatediceberg** [comment]
Update: the issue still isn't fixed (I saw a commit that referenced this). Clicking any buttons on the site still causes the Adblock detection popup (but technically if you reload right after that it reloads in the site without that popup - but this existed before the commit anyways). And the leftover spaces are still there too.

Sorry for this useless comment if the changes weren't supposed to be active yet/a new version of UBOL has to be released for the changes to take effect - if that's the case then I'll wait for the next App Store update before commenting again. Let me know if there's anything else Is should provide if relevant.

**Comment by stephenhawk8054** [comment]
If you are using uBO Lite, you need to wait until next uBO Lite version.

**Comment by stephenhawk8054** [comment]
Or you can add this as a custom filter in the meantime

```adb
@@||googletagmanager.com/gtag/js$xhr,domain=imleagues.com
```

1. Go to uBOL dashboard `Settings` pane 
2. Enable `Developer mode` 
3. Go to `Develop` pane 
4. Choose `Custom DNR rules`
5. Copy paste the above filter(s) and `Save`, open new tab and test again

**Comment by automatediceberg** [comment]
<details>

<img width="696" height="305" alt="Image" src="https://github.com/user-attachments/assets/7155961d-52ad-4c48-88c8-f98118c47f1c" />

</details>

I added the filter but the issue is still there/the Adblock detection doesn't go away. Also now reloading the page doesn't get rid of the popup

<details>

<img width="594" height="426" alt="Image" src="https://github.com/user-attachments/assets/b8544ee4-6773-47c6-b525-d7fb125c399f" />

</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO: and its default settings + that filter.

**Comment by automatediceberg** [comment]
The only issue remaining is the leftover ad spaces. Otherwise, it blocked the Adblock detection - it worked. Thank you!

**Comment by automatediceberg** [comment]
<img width="298" height="583" alt="Image" src="https://github.com/user-attachments/assets/46814d89-0172-4509-bffa-a2f8b335d82b" />
<img width="1051" height="224" alt="Image" src="https://github.com/user-attachments/assets/72f85c9b-812e-46e7-abba-3517a2705177" />

After updating to the newest version, the leftover ad spaces is still an issue

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters - Annoyances` or `Popups/overlay` list if you are using uBOL.
