### ISSUE TITLE
vuejs.org: breakage

### ISSUE THREAD

**Issue by hichemfantar** [uBlockOrigin/uAssets#22414]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://vuejs.org/
```

### Description

The sponsor section doesn't show any sponsots when ublock is enabled

### Other extensions used

https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
https://chromewebstore.google.com/detail/web-vitals/ahfhijdlegdabablpippeagghigmibma
https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

### Screenshot(s)

<details>
<summary>ublock on</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/34947993/db447d68-b9f5-481a-a2f7-57de52838f88)

</details>

<details>
<summary>ublock off</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/34947993/6d05a4ee-6a35-4701-91fe-563fe6cf621a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122305
 cosmetic: 45428
 scriptlet: 20422
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 80406-14, 1h.16m Δ
  easyprivacy: 50143-36, 1h.16m Δ
  plowe-0: 3786-1183, 9d.2h.8m
  ublock-badware: 7849-140, 1h.16m Δ
  ublock-filters: 37164-211, 1h.16m Δ
  ublock-privacy: 998-6, 1h.16m Δ
  ublock-quick-fixes: 196-4, 1h.16m Δ
  ublock-unbreak: 2206-32, 1h.16m Δ
  urlhaus-1: 7180-0, 1h.16m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 298 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  usefathom.com: 1
 extended:
  ##.sponsor-container

```
</details>

**Comment by mapx-** [comment]
`vuejs.org#@#.sponsor-container`

@ryanbr

**Comment by hichemfantar** [comment]
It seems like the sponsors section doesn't show at all now.
Shouldn't it be visible?

**Comment by stephenhawk8054** [comment]
@Khrin `###sponsors` hides the same section?

**Comment by mapx-** [comment]
@hichemfantar fixed in unbreak list

**Comment by Khrin** [comment]
@hichemfantar Ok then, I confused what you wanted exactly, sorry. We consider these "sponsor" links to be advertisements. 

Perplexed and disappointed by @mapx-  decision.

**Comment by mapx-** [comment]
It is more about a list of donors who contributed to the development of this framework

**Comment by hichemfantar** [comment]
These aren't exactly ads, they're a list of entities that donated to the open source project.

**Comment by hichemfantar** [comment]
It's more recognition than advertisement

**Comment by Khrin** [comment]
> It's more recognition than advertisement

Of course.

Happy to stick to my decision.

**Comment by hichemfantar** [comment]
lgtm! the sponsor list is working again

**Comment by hichemfantar** [comment]
looks like it broke again, can you confirm this?
![image](https://github.com/uBlockOrigin/uAssets/assets/34947993/6eca681c-d5a5-4b67-ab67-5a58155d3349)

**Comment by D4niloMR** [comment]
Caused by `||sponsors.vuejs.org^` in El.
