### ISSUE TITLE
tntdrama.com: breakage

### ISSUE THREAD

**Issue by Arikdefrasia** [uBlockOrigin/uAssets#22419]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tntdrama.com/shows/all-elite-wrestling-collision/season-2/episode-5/february-3-2024`

### Category

breakage

### Description

Ublock seems to block the webplayer elements on "tntdrama.com" and "tbs.com"
No video on either site begins when the play icon is clicked while Ublock in enabled. Up until this week they played fine with Ublock Origin. It may be noteworthy that the play icon is also different when Ublock is enabled vs disabled.  

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Ublock Enabled
![enabled](https://github.com/uBlockOrigin/uAssets/assets/44817082/8d709c32-b583-4b3a-8cde-3309d8916180)
Ublock Disabled
![disabled](https://github.com/uBlockOrigin/uAssets/assets/44817082/a0810e46-61e7-485a-9fb2-c66bbfddc6bc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 329832
 cosmetic: 246960
 scriptlet: 49935
 html: 2300
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77078-77078, 5m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 24m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96860-96832, 5m
  adguard-generic: 82616-7001, 5m
  adguard-mobile: 9054-19, 5m
  adguard-spyware-url: 1440-107, 5m
  block-lan: 56-0, 5m
  curben-phishing: 104071-33, 24m
  adguard-social: 22135-852, 5m
  fanboy-thirdparty_social: 68-0, 5m
  fanboy-cookiemonster: 49963-3857, 5m
  fanboy-social: 16115-25, 5m
  [14 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 37704-408, 5m
  ublock-badware: 7858-14, 5m
  ublock-privacy: 994-0, 5m
  ublock-unbreak: 2255-0, 5m
  ublock-quick-fixes: 196-0, 5m
  easylist: 80574-942, now
  easyprivacy: 50146-1109, 5m
  urlhaus-1: 7180-0, 24m
  plowe-0: 3783-84, 5m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 44 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 438 ms (selfie)
 maxAssetCacheWait: 203 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  tntdrama.com: 8
  addtoany.com: 2
  branch.io: 1
  cookielaw.org: 1
  googletagmanager.com: 1
  newrelic.com: 2
  ngtv.io: 4
  turner.com: 4
  typekit.net: 1
 extended:
  ###socialLinks
  ##.addtoany_list
  ###share-bar
  ##.share_icons
  ###video-ad
  ##.video-ad
  ##.ad-wrapper
  ##.footer-social
  ##.adchoices
  ##.sm-ad
  ##.ad-text
```
</details>

**Comment by Arikdefrasia** [comment]
Narrowed the issue down to the "EasyPrivacy" checkbox.  Unchecked, and Ublock enabled, the sites go back to playing just fine.

**Comment by huyszn** [comment]
Caused by `/analytics_v2.js` filter in EasyPrivacy

@ryanbr

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
tntdrama.com##+js(set, turnerAnalyticsObj, {})
tntdrama.com##+js(set, turnerAnalyticsObj.setVideoObject4AnalyticsProperty, noopFunc)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by vindanger** [comment]
This site's video player is currently being broken by the uBlock filters - Unbreak list. Disabling it fixes it, but this will break the video player on tbs.com if the EasyPrivacy list is enabled.
