### ISSUE TITLE
[nsfw] pixiv.net: ads

### ISSUE THREAD

**Issue by chimaha** [uBlockOrigin/uAssets#22418]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pixiv.net/tags/%E9%A2%A8%E6%99%AF/illustrations`

### Category

ads

### Description

The change from :upward() to :has() has caused the rule to no longer work.
It works if I change the div to li.

https://github.com/uBlockOrigin/uAssets/blob/ecafe69251be5bf1696ae35f21e3cb59c07bc57b/filters/filters.txt#L9915-L9916

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bgg5c6hNXI](https://github.com/uBlockOrigin/uAssets/assets/107383950/92f3d199-6bf9-447c-8400-443b9d6b56c1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 133194
 cosmetic: 144919
 scriptlet: 27913
 html: 2300
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-spyware-url: 1440-107, 1m
  adguard-social: 22135-136, 1m
  adguard-cookies: 28580-43, 1m
  ublock-cookies-adguard: 934-0, 1m
  adguard-popup-overlays: 26902-979, 1m
  adguard-mobile-app-banners: 5012-7, 1m
  adguard-other-annoyances: 14153-63, 1m
  adguard-widgets: 2431-1, 1m
  ublock-annoyances: 6613-949, now
 default:
  ublock-filters: 37704-396, 1m
  ublock-badware: 7858-14, 1m
  ublock-privacy: 994-0, now
  ublock-unbreak: 2254-0, 1m Δ
  ublock-quick-fixes: 196-0, 1m
  easylist: 80574-724, now
  easyprivacy: 50141-970, 1m Δ
  urlhaus-1: 7180-0, 1m
  plowe-0: 3783-1, 1m
  JPN-1: 14017-34, 1m
filterset (user): [array of 46 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 484 ms (selfie)
 maxAssetCacheWait: 141 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  pixiv.net: 1
  ads-pixiv.net: 3
  doubleclick.net: 1
  errortrace.dev: 2
  googletagmanager.com: 1
  onesignal.com: 1
 extended:
  ##div:has(> iframe[name="footer"][width="728"][height="90"])
  ##div:has(> iframe[name="header"][width="468"][height="60"])
  ##section[class^="sc-"] > div[class^="sc-"]:has(+ div[class^="sc…
  ##div > div:not([class]) > div[class^="sc-"]:has(> div > p > spa…
  ##section[class] aside[class*="-0 "] > iframe[src^="https://imp.…
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to sign in to reproduce the issue?

**Comment by chimaha** [comment]
No, you don't need to sign in.
It seems that ads will not be displayed unless the language is set to Japanese.
