### ISSUE TITLE
aliexpress.com: ads

### ISSUE THREAD

**Issue by LinogeFly** [uBlockOrigin/uAssets#22413]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.aliexpress.com/w/wholesale-raspberry-pi.html
```

### Description

Ads, or basically sponsored items, are not blocked on the search results page. See the screenshot example.

I checked that there were filters for aliexpress.com in filters-2023.txt file. But they stopped working and event started to break pages, to my understanding, and were commented out.

I made this filter, and tested it for couple of days now, and it seems to be working:

```
aliexpress.com##a[class*="search-card-item"] div:has-text(/^AD$/):upward(div[data-spm="main"] > div)
```

If can make a pull request for this, if that's ok. I'm not sure how the process usually goes with adding or updating filters.

### Other extensions used

No other extensions used.

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/10357631/11061e97-be95-47da-aa5c-515acb70ed0f)

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 115765
 cosmetic: 47453
 scriptlet: 18958
 html: 2093
listset (total-discarded, last-updated):
 added:
  FIN-0: 2269-1, never
 default:
  user-filters: 3-0, never
  ublock-filters: 37683-140, 1m
  ublock-badware: 7853-14, 1m
  ublock-privacy: 994-0, 1m
  ublock-unbreak: 2254-0, 1m
  ublock-quick-fixes: 192-0, 1m
  easylist: 80401-644, 1m
  easyprivacy: 43338-840, 1m
  urlhaus-1: 7285-0, 1m
  plowe-0: 3787-1, 1m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1827 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  alicdn.com: 4
  criteo.net: 1
  facebook.net: 1
  go-mpulse.net: 1
  mmstat.com: 18
  taobao.com: 3
```
</details>

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e31a41835107817afe403a91c487fe17a5b8e608

**Comment by Yuki2718** [comment]
@stephenhawk8054 What was the problem? If this was just because the results were all ads, I guess it's fine.

**Comment by Yuki2718** [comment]
Or maybe we can try safer rule like `##a.search-card-item[href*="&aem_p4p_detail="]:has(div[class*="cards--image--"] > div[class*="multi--"]:has-text(/^AD$/))`

**Comment by LinogeFly** [comment]
Yeah, that rule looks more specific and safer for sure.

Didn't realize "AD" was only for English website, which makes perfect sense, but still it migh be good to cover English interface.

**Comment by Yuki2718** [comment]
Added a safer rule coveing all languages. Let's see how it goes.

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 ~What was the problem? If this was just because the results were all ads, I guess it's fine.~ Looks you coudn't reproduce either. Anyway, it seems better not to hide them. (BTW `AD` works only for English interface)

Yeah, the previous versions cause blank pages for some people. I couldn't reproduce those cases though. If it has many troubles, I think it's fine not to hide them.

**Comment by Yuki2718** [comment]
Possible issue https://github.com/easylist/easylist/issues/18543
