### ISSUE TITLE
alexela.ee: nuisance

### ISSUE THREAD

**Issue by GaN-FET** [uBlockOrigin/uAssets#22416]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.alexela.ee/et/elekter`

### Category

nuisance

### Description

Nuisance overlay, blocks interaction, GDPR cookie dialog remnant, that I can't get rid of with the element picker or zapper. (Maybe these tools could be improved?)
Ghostery (when enabled for the site) gets rid of the cookie dialog.
Switcing Mz FF Enh. Tracker protection, Decentraleyes, EFF Privacy Badger and/or Ghostery off for this site does not make for a difference vs the specific issue (verified).

### Other extensions used

EFF Privacy Badger version 2024.2.6
Ghostery  version 8.12.5
Decentraleyes 2.0.18

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 122467
 cosmetic: 45618
 scriptlet: 18946
 html: 2087
listset (total-discarded, last-updated):
 added:
  EST-0: 465-6, 1h.44m
 default:
  user-filters: 11-0, never
  ublock-filters: 37683-193, 44m Δ
  ublock-badware: 7853-14, 44m Δ
  ublock-privacy: 994-0, 44m Δ
  ublock-unbreak: 2254-0, 44m Δ
  ublock-quick-fixes: 192-0, 44m Δ
  easylist: 80401-570, 44m Δ
  easyprivacy: 50143-907, 44m Δ
  urlhaus-1: 7180-0, 1h.44m
  plowe-0: 3783-1, now
filterset (user): [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10268 ms (selfie)
 maxAssetCacheWait: 1696 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by zenstorage** [comment]
try these filters:
```
www.alexela.ee##.c-cookie
www.alexela.ee##body:style(overflow: auto !important;)
www.alexela.ee##body::after:style(display: none !important;)
```

**Comment by GaN-FET** [comment]
Works like a charm, thanks!
Should this make into a more systematic fix (for others to automatically also benefit from) or should I just close this as fixed for me?

**Comment by D4niloMR** [comment]
Or `||www.alexela.ee/modules/contrib/eu_cookie_compliance/js/eu_cookie_compliance.min.js$script,1p`

**Comment by stephenhawk8054** [comment]
About https://github.com/uBlockOrigin/uAssets/issues/34014

```adb
alexela.ee##body.eu-cookie-compliance-popup-open:style(overflow: auto !important;)
alexela.ee##body.eu-cookie-compliance-popup-open::after:style(display: none !important;)
```

cc @ryanbr
