### ISSUE TITLE
academictorrents.com: ads

### ISSUE THREAD

**Issue by AdamFrack** [uBlockOrigin/uAssets#22415]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://academictorrents.com/browse.php`

### Category

ads

### Description

Doesn't block ads via Carbon. (carbonads.net is blocked)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ads](https://github.com/uBlockOrigin/uAssets/assets/147642132/0d94cb33-e7cc-4a1b-b74a-8c7118a393a4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 122472
 cosmetic: 45420
 scriptlet: 18951
 html: 2088
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37704-112, 4m
  ublock-badware: 7858-14, 4m
  ublock-privacy: 994-0, 4m
  ublock-unbreak: 2254-0, 4m
  ublock-quick-fixes: 196-0, 4m
  easylist: 80574-645, 4m
  easyprivacy: 50170-860, 4m
  urlhaus-1: 7180-0, 4m
  plowe-0: 3783-1, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1634 ms
 maxAssetCacheWait: 180 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by D4niloMR** [comment]
Add:

`academictorrents.com###carbon`
