### ISSUE TITLE
memurlar.net: ublock disables also videos

### ISSUE THREAD

**Issue by linguist5** [uBlockOrigin/uAssets#22423]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.memurlar.net/haber/1092303/evin-altina-40-metrelik-kuyu-kazip-define-aradilar.html`

### Category

breakage

### Description

Whem ublock is active, web page cant't show video with error message "IMA SKD can't be loaded".
 When ublock is disabled, web page shows videos with ads.

### Other extensions used

No other extensions used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![this](https://github.com/uBlockOrigin/uAssets/assets/57441361/fba25373-685b-478e-be37-c15dcb34a87e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 109
filterset (summary):
 network: 124256
 cosmetic: 55399
 scriptlet: 22197
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 111-11, never
  TUR-0: 13208-61, now
  easylist: 80577-35, now
  easyprivacy: 50147-43, now
  plowe-0: 3783-1184, now
  ublock-badware: 7854-140, now
  ublock-filters: 37190-221, now
  ublock-privacy: 998-6, now
  ublock-quick-fixes: 204-4, now
  ublock-unbreak: 2207-33, now
  urlhaus-1: 7460-0, now
filterset (user): [array of 113 redacted]
trustedset:
 added: [array of 38 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 968 ms (selfie)
 maxAssetCacheWait: 147 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 19
 network:
  admatic.com.tr: 2
  ads-twitter.com: 1
  adsby.io: 2
  adtarget.com.tr: 1
  doubleclick.net: 1
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  idealmedia.io: 2
  imasdk.googleapis.com: 1
  membrana.media: 1
  sharethis.com: 2
  taboola.com: 1
  yandex.ru: 1
 extended:
  ###sticky-masthead
  ##.widget-970x250
  ##.widget-336x280
  ##.widget-580x400
  ##.adm-ads-area
  ##div[id*="ScriptRoot"]
```
</details>

**Comment by Yuki2718** [comment]
Interesting that `/adsbygoogle.js` redirect causes this error. An alternative fix is 
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect-rule,domain=video.memurlar.net`.

**Comment by linguist5** [comment]
Adding that line to options solved the issue

thanks a lot

**Comment by Yuki2718** [comment]
The issue is fixed in uBlock's own filter, you only need to update filters.
