### ISSUE TITLE
eurostreaming.ing: breakage

### ISSUE THREAD

**Issue by Alessio979** [uBlockOrigin/uAssets#22427]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://eurostreaming.ing/stream/2143-halo-2022-streaming.html
```

### Description

Hi, first screenshot with ublock on, the second one with ublock off

Can you fix to view links?

Thanks

### Other extensions used

Norton Password Manager
MyJDownloader
Video DownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/67b161c7-1c3c-4656-9078-95f0caadc362)
![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/81959787-2f47-43da-9311-82285acaf93e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 331619
 cosmetic: 253621
 scriptlet: 51617
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77105-128, 2d.14h.3m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 17h.8m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96213-22258, 8d.15h.47m
  adguard-cookies: 28579-28557, 15h.7m
  adguard-generic: 82616-572, 15h.8m
  adguard-mobile: 9054-65, 15h.6m
  adguard-mobile-app-banners: 5012-5009, 15h.7m
  adguard-other-annoyances: 14153-14143, 15h.7m
  adguard-popup-overlays: 26902-26860, 15h.7m
  adguard-social: 22135-1591, 15h.6m
  adguard-spyware: 94452-1227, 2d.14h.3m
  adguard-spyware-url: 1440-5, 15h.6m
  [14 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ITA-0: 8299-24, 14h.5m
  easylist: 80590-2159, 1h.7m Δ
  easyprivacy: 50282-32507, 1h.7m Δ
  plowe-0: 3784-1676, 6d.17h.1m
  ublock-badware: 7854-334, 1h.7m Δ
  ublock-filters: 37199-4048, 1h.7m Δ
  ublock-privacy: 998-415, 1h.7m Δ
  ublock-quick-fixes: 203-4, 1h.7m Δ
  ublock-unbreak: 2208-150, 1h.7m Δ
  urlhaus-1: 7180-0, 10h.8m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9179 ms (selfie)
 maxAssetCacheWait: 1175 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by ItsProfessional** [comment]
Works fine for me.

> ` [14 lists not shown]: [too many]`

You are using a heavily customized configuration of uBO. We can't help users with such a customized configuration of uBO.

Reset uBO, and if the issue still occurs, comment here.

**Comment by Alessio979** [comment]
I reset the settings and the problem persist.
Thanks

**Comment by Alessio979** [comment]
<details>
<summary>Details</summary>


```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 124443
 cosmetic: 52012
 scriptlet: 20433
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ITA-0: 8299-18, 1m
  easylist: 80565-21, now
  easyprivacy: 50142-38, now
  plowe-0: 3783-1184, now
  ublock-badware: 7854-140, now
  ublock-filters: 37190-221, now
  ublock-privacy: 998-6, now
  ublock-quick-fixes: 203-4, now
  ublock-unbreak: 2207-32, now
  urlhaus-1: 7460-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2660 ms
 maxAssetCacheWait: 10 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by huyszn** [comment]
I get the breakage on chrome, but not on firefox. The breakage is caused by the filter: `eurostreaming.*##+js(aost, document.createElement, /HTMLScriptElement|onload/)`

**Comment by Alessio979** [comment]
I've updated the integrated filters but the issue continues

**Comment by mapx-** [comment]
@Alessio979 
update clicking this link:
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1

**Comment by Alessio979** [comment]
works 

Thanks
