### ISSUE TITLE
tv4play.se: detection

### ISSUE THREAD

**Issue by Antjo2000** [uBlockOrigin/uAssets#22428]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tv4play.se/video/c0fba8dc33f5dc675b9a/fredag-9-februari`

### Category

detection

### Description

Har du en annonsblockerare igång?
För att ta del av vårt innehåll behöver du avaktivera din annonsblockerare och ladda om sidan.
(Swedish)

Says are you using an adblocker, to use our content you must turn off you adblocker and reload the page.

Did test this on Chrome with only ublock installed aswell as on firefox.
Can get the webiste to load when using Brave so i believe its not an issue with vpn etc.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 124327
 cosmetic: 48097
 scriptlet: 19294
 html: 2106
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 37714-112, 2m Δ
  ublock-badware: 7858-14, 2m Δ
  ublock-privacy: 994-0, 2m Δ
  ublock-unbreak: 2255-0, 2m Δ
  ublock-quick-fixes: 197-0, 2m Δ
  easylist: 80577-652, 2m Δ
  easyprivacy: 50147-867, 2m Δ
  urlhaus-1: 7460-0, now
  plowe-0: 3783-1, now
  SWE-1: 4638-6, now
filterset (user): [array of 4 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 668 ms (selfie)
 maxAssetCacheWait: 166 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  tv4play.se: 1
  bugsnag.com: 1
  imrworldwide.com: 1
  youborafds01.com: 1
 extended:
  ##button:has-text(Besök annonsör)
  ##.avod-web-player-pause:style(background-color:transparent!impo…
  ##+js(json-prune-fetch-response, bumpers, , propsToMatch, url:/p…
  ##+js(xml-prune, Ad, , se-tv4.videoplaza.tv/proxy/distributor)
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by Antjo2000** [comment]
Please close this found a solution for it

**Comment by ItsProfessional** [comment]
What's your "solution"?

**Comment by Antjo2000** [comment]
I updated firefox and after that it detects adblock even without ublock installed, so its an issue with firefox itself, solution simply used older firefox version
