### ISSUE TITLE
bongo.be: breakage

### ISSUE THREAD

**Issue by owengraven** [uBlockOrigin/uAssets#22429]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bongo.be/nl/`

### Category

breakage

### Description

The site doesn't load and stays mostly blank apart from a few searchboxes. Disableing ublock make it work, enabling it breaks it again.

### Other extensions used

steamdb
bitwarden
G menu
dark reader (which is disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 124551
 cosmetic: 89788
 scriptlet: 25041
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49995-176, 5m
  ublock-cookies-easylist: 934-3, 4m
 default:
  user-filters: 0-0, never
  easylist: 80577-14, 5m Δ
  easyprivacy: 50147-38, 5m Δ
  plowe-0: 3783-1183, now
  ublock-badware: 7854-140, 5m Δ
  ublock-filters: 37188-221, 5m Δ
  ublock-privacy: 998-6, 5m Δ
  ublock-quick-fixes: 204-4, 5m Δ
  ublock-unbreak: 2207-33, 5m Δ
  urlhaus-1: 7460-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1533 ms
 maxAssetCacheWait: 544 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 10
 network:
  cookielaw.org: 1
  criteo.net: 1
  google.com: 1
  googletagmanager.com: 1
  newrelic.com: 2
  nr-data.net: 4
```
</details>

**Comment by mapx-** [comment]
add

`@@||cdn.cookielaw.org/scripttemplates/*/otBannerSdk.js$script,domain=bongo.be`

@ryanbr 

@Alex-302 broken by AA too

`@@||cdn.cookielaw.org/scripttemplates/otSDKStub.js$script,domain=bongo.be`

**Comment by Alex-302** [comment]
Unblocked also `@@||geolocation.onetrust.com/cookieconsentpub/v*/geo/location$domain=bongo.be`, because 
https://www.bongo.be/nl/cadeaubonnen/actie-en-avontuur/ has the same problem (opened in *a new* private tab).
