### ISSUE TITLE
cb01.promo: ads

### ISSUE THREAD

**Issue by Alessio979** [uBlockOrigin/uAssets#22426]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://cb01.promo/invito-a-un-omicidio-hd-2023/
```

### Description

Banner into the page

### Other extensions used

Norton Password Manager
MyJDownloader
Video DownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/4000da6e-389c-4dcb-939c-da6a09a99cbd)
![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/07307891-710d-4f34-9afe-68ae8f45e2e8)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 331619
 cosmetic: 253621
 scriptlet: 51617
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77105-128, 2d.13h.46m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 16h.51m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96213-22258, 8d.15h.30m
  adguard-cookies: 28579-28557, 14h.49m
  adguard-generic: 82616-572, 14h.50m
  adguard-mobile: 9054-65, 14h.48m
  adguard-mobile-app-banners: 5012-5009, 14h.50m
  adguard-other-annoyances: 14153-14143, 14h.50m
  adguard-popup-overlays: 26902-26860, 14h.50m
  adguard-social: 22135-1591, 14h.49m
  adguard-spyware: 94452-1227, 2d.13h.46m
  adguard-spyware-url: 1440-5, 14h.49m
  [14 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ITA-0: 8299-24, 13h.48m
  easylist: 80590-2159, 50m Δ
  easyprivacy: 50282-32507, 50m Δ
  plowe-0: 3784-1676, 6d.16h.44m
  ublock-badware: 7854-334, 50m Δ
  ublock-filters: 37199-4048, 50m Δ
  ublock-privacy: 998-415, 50m Δ
  ublock-quick-fixes: 203-4, 50m Δ
  ublock-unbreak: 2208-150, 50m Δ
  urlhaus-1: 7180-0, 9h.50m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9179 ms (selfie)
 maxAssetCacheWait: 1175 ms
 cacheBackend: browser.storage.local

```
</details>    
/

**Comment by stephenhawk8054** [comment]
You mean the red banner at the right?

**Comment by Alessio979** [comment]
also those:
![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/b8f59fab-350f-4da5-a49f-c27ea8e5651d)
![image](https://github.com/uBlockOrigin/uAssets/assets/157692465/2ffadf19-1b2c-47a7-ab2b-45f485aa0409)

and first screenshot "riproduci"

Thanks

**Comment by stephenhawk8054** [comment]
@Khrin For EasyList Italy?

```adb
cb01.promo##a[href*="/4k/film/"]
```

**Comment by Alessio979** [comment]
new domain:
cb01.archi

Thanks
