### ISSUE TITLE
Sentry CDN is blocked, will affect support.

### ISSUE THREAD

**Issue by tkbstudios** [uBlockOrigin/uAssets#22439]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://tinet.tkbstudios.com/
```

### Description

uBlock blocks the Sentry CDN, because of this, I can't capture session replays and won't be able to help out users in case of problems.  
those are the blocked domains:
- sentry-cdn.com
- *.ingest.sentry.io

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/69647028/de99e2b7-eaf3-45a0-85d5-fb15eed10c0a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 122723
 cosmetic: 45450
 scriptlet: 19107
 html: 2094
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37740-222, 31m Δ
  ublock-badware: 7851-14, 31m Δ
  ublock-privacy: 994-0, 31m Δ
  ublock-unbreak: 2260-0, 31m Δ
  ublock-quick-fixes: 209-0, 31m Δ
  easylist: 80703-546, 31m Δ
  easyprivacy: 50188-851, 31m Δ
  urlhaus-1: 7430-0, 12h.53m
  plowe-0: 3784-1, 6d.23h.12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 406 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  sentry-cdn.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
> - [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).

You didn't read the [EasyPrivacy policies](https://easylist.to/pages/policy.html).
Sentry -> tracking.
