### ISSUE TITLE
[nsfw] mycryptotraffic.com: ads

### ISSUE THREAD

**Issue by elsanto86** [uBlockOrigin/uAssets#22433]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mycryptotraffic.com/plus500/it/index.html`

### Category

ads

### Description

Italic

### Other extensions used

Italic

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 124335
 cosmetic: 52006
 scriptlet: 19095
 html: 2092
listset (total-discarded, last-updated):
 added:
  https://www.primevideo.com/offers/nonprimehomepage: 0-0, never
 default:
  user-filters: 1-0, never
  ublock-filters: 37727-150, 1h.28m Δ
  ublock-badware: 7851-14, 1h.28m Δ
  ublock-privacy: 994-0, 1h.28m Δ
  ublock-unbreak: 2260-0, 1h.28m Δ
  ublock-quick-fixes: 204-0, 1h.28m Δ
  easylist: 80590-652, 1h.28m Δ
  easyprivacy: 50207-832, 1h.28m Δ
  urlhaus-1: 7430-0, now
  plowe-0: 3783-1, now
  ITA-0: 8300-19, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 7 redacted]
userSettings:
 largeMediaSize: 38
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms (selfie)
 maxAssetCacheWait: 251 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-large-media: true
 no-popups: true
```
</details>

**Comment by D4niloMR** [comment]
So, how do you get there?
