### ISSUE TITLE
programming-link.info: detection

### ISSUE THREAD

**Issue by Sabinnar12** [uBlockOrigin/uAssets#22438]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://programming-link.info/Please-Wait.php`
Source link (ItsProfessoinal): `https://getintopc.com/softwares/3d-visualization/adobe-illustrator-2024-free-download/?id=001233978721` (click on `Download Full Setup`

### Category

detection

### Description

it detect ad blocker

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/41190010/6cabd3e9-12ae-4730-949d-b995b3861504)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 210826
 cosmetic: 123793
 scriptlet: 40024
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/sndsabin/swaccha-adblock-filter/master/swaccha-static-adblock-filters.txt: 135-1, now
  IND-0: 13017-11, now
  adguard-generic: 82639-530, now
  adguard-mobile: 9055-50, now
  adguard-popup-overlays: 26902-58, now
  adguard-spyware: 94460-1192, now
  fanboy-thirdparty_social: 68-0, now
 default:
  user-filters: 5-0, never
  easylist: 80703-1894, 4m Δ
  easyprivacy: 50188-32328, 4m Δ
  plowe-0: 3783-1342, now
  ublock-badware: 7847-322, 4m Δ
  ublock-filters: 37216-3767, 4m Δ
  ublock-privacy: 998-313, 4m Δ
  ublock-quick-fixes: 256-24, 4m Δ
  ublock-unbreak: 2212-146, 4m Δ
  urlhaus-1: 7460-0, never
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 411 ms (selfie)
 maxAssetCacheWait: 280 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by ItsProfessional** [comment]
continue in #21424, same source site
