### ISSUE TITLE
streaam.in: nuisance

### ISSUE THREAD

**Issue by spidy2356** [uBlockOrigin/uAssets#22430]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://streaam.in/6Md6he
```

### Description

timer and pop up not get bypassed.

### Other extensions used

not related to adblock. turn off all and test only with ublock, same situation.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/101243689/58b2213f-4d70-432e-a0ff-9780290040c3)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 126564
 cosmetic: 117427
 scriptlet: 25135
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4344-32, 23h.38m
  easylist-chat: 180-0, 3d.19h.26m
  easylist-newsletters: 6936-15, 23h.39m
  easylist-notifications: 2933-86, 23h.38m
  fanboy-cookiemonster: 49718-183, 6d.23m
  fanboy-social: 16136-29, 8d.20m
  ublock-cookies-easylist: 929-2, 23h.38m
 default:
  user-filters: 17-0, never
  easylist: 80590-14, 42m Δ
  easyprivacy: 50282-122, 42m Δ
  plowe-0: 3785-1185, 3d.29m
  ublock-badware: 7854-140, 42m Δ
  ublock-filters: 37199-362, 42m Δ
  ublock-privacy: 998-8, 42m Δ
  ublock-quick-fixes: 203-4, 42m Δ
  ublock-unbreak: 2208-35, 42m Δ
  urlhaus-1: 7180-0, 19h.37m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6829 ms (selfie)
 maxAssetCacheWait: 254 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by spidy2356** [comment]
@huyszn still have same issue, update the filter list.
link: https://streaam.in/5MXQA3jZ

**Comment by huyszn** [comment]
Update the filters list now and test again.

**Comment by spidy2356** [comment]
> Update the filters list now and test again.

now working. thanks u so much sir

**Comment by Rust1667** [comment]
now using a new domain `www.webzeni.com`
