### ISSUE TITLE
board-game.co.uk: breakage

### ISSUE THREAD

**Issue by ymax** [uBlockOrigin/uAssets#22437]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.board-game.co.uk/category/board-games/`

### Category

breakage

### Description

* pagination doesn't work: if I click to go to page 2 (or 3, or last), I still remain at first page.
* none of the left side menu buttons work.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/uBlockOrigin/uAssets/assets/5382212/7b7e0817-7eb8-4f98-af12-e516ff8f1173)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 140057
 cosmetic: 66376
 scriptlet: 20559
 html: 2118
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37740-163, now
  ublock-badware: 7851-14, now
  ublock-privacy: 994-0, now
  ublock-unbreak: 2260-0, now
  ublock-quick-fixes: 209-0, now
  easylist: 80703-673, now
  easyprivacy: 50188-832, now
  urlhaus-1: 7330-0, now
  plowe-0: 3783-1, now
  RUS-0: 39986-94, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13854 ms
 maxAssetCacheWait: 325 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  board-game.co.uk: 1
  facebook.net: 1
  googletagmanager.com: 4
  trackedlink.net: 2
  trackedweb.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `/cdn-cgi/zaraz/*` in EP

```adb
@@||board-game.co.uk/cdn-cgi/zaraz/s.js$script,1p
```

@ryanbr

**Comment by ryanbr** [comment]
Resolved, note its an issue only in Firefox and not in Chrome/Chromium browsers.
