### ISSUE TITLE
dailymotion.com: breakage

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#22432]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dailymotion.com/embed/video/k6m65BWqndm0kBzTY1g?logo=0&autoPlay=0&quality=720&playlist=x79ac2`

### Category

breakage

### Description

video does not load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240210-175729-413](https://github.com/uBlockOrigin/uAssets/assets/20338483/b05b67ae-8136-48d2-ad21-d32d11b346be)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 124
filterset (summary):
 network: 143489
 cosmetic: 61810
 scriptlet: 23673
 html: 2305
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6674-10, 57m Δ
  FRA-0: 26778-121, 3m
 default:
  user-filters: 10-0, never
  ublock-filters: 38069-232, 4m
  ublock-badware: 7852-14, 4m
  ublock-privacy: 994-0, 4m
  ublock-unbreak: 2261-1, 4m
  ublock-quick-fixes: 196-0, 4m
  adguard-mobile: 9055-102, now
  easylist: 80590-941, 57m Δ
  easyprivacy: 50282-1087, 57m Δ
  urlhaus-1: 7460-0, 57m
  plowe-0: 3783-1, now
filterset (user): [array of 10 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 629 ms (selfie)
 maxAssetCacheWait: 286 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  dailymotion.com: 6
  d1g61tw28new6q.cloudfront.net: 7
  dm-event.net: 12
  imasdk.googleapis.com: 2
  scorecardresearch.com: 8
 extended:
  ##+js(trusted-set-cookie, dm-euconsent-v2, CPt6yMAPt6yMABpAGAEND…
```
</details>

**Comment by mapx-** [comment]
@smed79 @Alex-302 broken by french list

`@@||dailymotion.com^$cname`
