### ISSUE TITLE
sbazar.cz: ads

### ISSUE THREAD

**Issue by yagarea** [uBlockOrigin/uAssets#22447]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sbazar.cz/tristan/detail/202704757-lenovo-x1-carbon-i7-16gb-ram-14-ips-2560x1440`

### Category

ads

### Description

it shows adds

### Other extensions used

keepassxc, privacy badgeer, localCDN, Istilldontcareaboutcookies, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-02-11-15-25-58](https://github.com/uBlockOrigin/uAssets/assets/14349169/364e1b75-5c0e-4b82-8e15-6fc990e24bd2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 121
filterset (summary): 
  network: 122425
  cosmetic: 45315
  scriptlet: 19028
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, 2d.2h.35m
  default: 
    user-filters: 0-0, never
    easylist: 80598-14, 1d.53m
    easyprivacy: 50137-38, 1d.52m
    plowe-0: 3785-1185, 4d.18h.49m
    ublock-badware: 7828-140, 4d.18h.47m
    ublock-filters: 35588-194, 4d.18h.46m
    ublock-privacy: 915-83, 2d.2h.34m
    ublock-quick-fixes: 242-0, 1h.19m
    ublock-unbreak: 2195-31, 4d.18h.48m
    urlhaus-1: 7235-0, 29m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2115 ms
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    gemius.pl: 1
    sklik.cz: 4
```
</details>

**Comment by mapx-** [comment]
report here: https://github.com/tomasko126/easylistczechandslovak/issues

or add in "my filters"

`sbazar.cz##.banner-wrapper`
