### ISSUE TITLE
email.inbox.lv: detection

### ISSUE THREAD

**Issue by mozilla343** [uBlockOrigin/uAssets#22448]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://email.inbox.lv/mailbox`

### Category

detection

### Description

The web email service detects an ad blocker, resulting in a popup being displayed. However, users can close this popup and continue using their email. This doesn’t happen every time an email is opened, but periodically. Until the popup is closed, scroll is blocked. This popup happens only in full page email view (email.inbox.lv) not the mini email view (inbox.lv) where news are to occupying rest of the page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/62311944/d928f807-f66a-4757-83db-abd685ba4c0a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 123
filterset (summary):
 network: 160918
 cosmetic: 115056
 scriptlet: 39618
 html: 0
listset (total-discarded, last-updated):
 added:
  EST-0: 464-1, now
  LTU-0: 1253-2, now
  LVA-0: 396-4, now
  RUS-0: 39949-17, now
  adguard-generic: 82641-700, now
  adguard-mobile: 9056-71, now
 default:
  user-filters: 3-0, never
  easylist: 80693-1872, now
  easyprivacy: 50194-239, now
  plowe-0: 3783-1272, now
  ublock-badware: 7846-322, now
  ublock-filters: 37230-3675, 23m Δ
  ublock-privacy: 998-7, now
  ublock-quick-fixes: 264-24, 23m Δ
  ublock-unbreak: 2212-101, now
  urlhaus-1: 7235-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 984 ms (selfie)
 maxAssetCacheWait: 653 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  adbox.lv: 1
  gemius.pl: 1
  googletagmanager.com: 1
  sentry.io: 1
 extended:
  ###inx-main-roof
  ##.bxS-text_link
  ##.col-ad
```
</details>

**Comment by dimisa-RUAdList** [comment]
The last commit in the Latvian filter was made [a year ago](https://github.com/Latvian-List/adblock-latvian/commits/master/). Is it generally supported, or abandoned?

**Comment by mapx-** [comment]
already fixed by `uBlock filters – Annoyances` => subscribe it !

**Comment by mozilla343** [comment]
> already fixed by `uBlock filters – Annoyances` => subscribe it !

I am so sorry. I just subscribed to it. But one question, there are sooo many filter lists and many of them are not selected by default, can anyone enlighten me which of them should I enable after clean ublock origin extension install?

**Comment by D4niloMR** [comment]
https://www.reddit.com/r/uBlockOrigin/wiki/index/#wiki_which_filter_lists_should_i_select.3F
