### ISSUE TITLE
genshin-impact.fandom.com: breakage

### ISSUE THREAD

**Issue by yixophoenix** [uBlockOrigin/uAssets#22459]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://genshin-impact.fandom.com/`
`https://honkai-star-rail.fandom.com/`
`https://www.fandom.com/`

### Category

breakage

### Description

This is way too complicated for me. Started happening today genshin, honkai wikis and fandom.com are just reloading indefinitely.
I tried all the checkmarks under lists and this one's causing it: uBlock filters – Privacy.

### Other extensions used

I tried disabling everything else. Until I turn off ublock it won't load.

### Screenshot(s)

it's a white page and reloads forever

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 325531
 cosmetic: 247631
 scriptlet: 50187
 html: 2312
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82543-7308, now
  adguard-mobile: 9072-20, now
  adguard-spyware-url: 1440-106, now
  adguard-spyware: 100510-32915, now
  block-lan: 56-0, now
  curben-phishing: 93465-33, now
  adguard-social: 22141-852, now
  adguard-cookies: 28612-62, now
  ublock-cookies-adguard: 934-0, now
  adguard-popup-overlays: 26933-1672, now
  adguard-mobile-app-banners: 5015-1078, now
  adguard-other-annoyances: 14180-334, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37890-475, 4m Δ
  ublock-badware: 7849-14, 4m Δ
  ublock-privacy: 995-0, 4m Δ
  ublock-unbreak: 2261-1, 4m Δ
  ublock-quick-fixes: 217-0, 4m Δ
  easylist: 80796-950, 4m Δ
  easyprivacy: 50199-1115, 4m Δ
  urlhaus-1: 7300-0, now
  plowe-0: 3782-84, now
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 252 ms (selfie)
 maxAssetCacheWait: 178 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(set-cookie, tracking_session_id, OK, , reload, 1)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
  ##+js(trusted-set-cookie, euconsent-v2, CPt3fQAPt3fQACNAFAENDLCg…
  ##+js(trusted-set-cookie, tracking-opt-in-status, rejected, 1yea…
  ##+js(trusted-set-cookie, addtl_consent, 1~, 1year)
  ##+js(set-constant, wgAffiliateEnabled, false)
```
</details>

**Comment by JobcenterTycoon** [comment]
I can't reproduce but try this `fandom.com#@#+js(set-cookie, tracking_session_id, OK, , reload, 1)`

**Comment by stephenhawk8054** [comment]
Can you test in a new Firefox profile with only uBO and its default settings?

**Comment by stephenhawk8054** [comment]
In your old profile, reset uBO to default settings, turn off all other extensions, restart the browser, open new tab and test again.

**Comment by yixophoenix** [comment]
> In your old profile, reset uBO to default settings, turn off all other extensions, restart the browser, open new tab and test again.

Okay wtf, I did what you said and it fixed it, I turned on all the old extensions again and put all the filter options I had before and it's still fixed?????

**Comment by ItsProfessional** [comment]
If you ever encounter the issue again in future, report back.

**Comment by yixophoenix** [comment]
Well it's back...
"fandom.com#@#+js(set-cookie, tracking_session_id, OK, , reload, 1)" this still solves it but I tried resetting all settings and turning off all other extensions and it didn't fix it like last time. Though loading the other clean profile and adding ublock there does solve it but I kinda don't want to delete all my history and input the thousand passwords again unless absolutely necessary.

Also it seems I never mentioned this but it's specifically the "uBlock filters - Privacy" that's causing it.

**Comment by D4niloMR** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section

**Comment by yixophoenix** [comment]
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section

Thanks? but I wasn't really talking about saving ublock settings? I tried resetting it multiple times if that's what you wanted me to take from that link.
