### ISSUE TITLE
secure.backblaze.com: breakage

### ISSUE THREAD

**Issue by Xevion** [uBlockOrigin/uAssets#22450]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://secure.backblaze.com/b2_buckets.htm`

### Category

breakage

### Description

A popup is supposed to appear when signing up with Backblaze B2; this popup is blocked when uBlock Origin is enabled.
If you need to test this, just create an account (only a password is needed), and you _should_ see the popup blocked with uBlock enabled.
This popup is _required_ to continue with B2 on-boarding, so having it blocked is a major issue and constitutes breakage of the website.

### Other extensions used

<details>
<summary>Firefox Extensions/Addons</summary>
<pre>
Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Amazon.com	extension	1.7	true	amazondotcom@search.mozilla.org
Battlefield 4 True Player Count	extension	0.0.0.3	true	{5cb5d74f-e74b-4d10-b8fc-3c699cd3a1da}
Bing	extension	1.6	true	bing@search.mozilla.org
Bitwarden - Free Password Manager	extension	2024.1.1	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
CollabDown	extension	1.2.2	true	{20d4198d-1b8f-4cd8-9d21-0e7c79d9385a}
Copy All Tab Urls	extension	2.2.0	true	{0507f777-2480-4d48-baf1-3b9c8feeb2b4}
Dark Reader	extension	4.9.77	true	addon@darkreader.org
Decentraleyes	extension	2.0.18	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	extension	1.4	true	ddg@search.mozilla.org
DuckDuckGo !bangs	extension	0.6.1	true	{de5abd6c-321f-49cb-b68f-381241ad4e9e}
eBay	extension	1.4	true	ebay@search.mozilla.org
Export Tabs URLs	extension	0.2.12	true	{17165bd9-9b71-4323-99a5-3d4ce49f3d75}
find+ | Regex Find-in-Page Tool	extension	2.2.1	true	{6fa42eda-38ca-4126-96d5-3163f0de6900}
GitHub Isometric Contributions	extension	1.1.28	true	isometric-contributions@jasonlong.me
GNOME Shell integration	extension	11.1	true	chrome-gnome-shell@gnome.org
Google	extension	1.4	true	google@search.mozilla.org
Grammarly: AI Writing and Grammar Checker App	extension	8.910.0	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
Greasemonkey	extension	4.12.0	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
I don't care about cookies	extension	3.5.0	true	jid1-KKzOGWgsW3Ao4Q@jetpack
Image Search Options	extension	3.0.12	true	{4a313247-8330-4a81-948e-b79936516f78}
NZB Unity	extension	1.17.5	true	{96586e48-b9a2-45dd-b1a1-54fa85a97c91}
Octotree - GitHub code tree	extension	7.11.2	true	jid1-Om7eJGwA1U8Akg@jetpack
Privacy | Protect Your Payments	extension	2.2.1	true	privacy@privacy.com
React Developer Tools	extension	5.0.0	true	@react-devtools
Reddit Enhancement Suite	extension	5.22.17	true	jid1-xUfzOsOFlzSOXg@jetpack
Return YouTube Dislike	extension	3.0.0.14	true	{762f9885-5a13-4abd-9c77-433dcd38b8fd}
SauceNAO Fetcher	extension	1	true	{384ac858-9a3a-4be5-980e-0dec1ace9be4}
Save as PDF	extension	2	true	save-as-pdf-ff@pdfcrowd.com
Save In…	extension	3.7.1	true	{72d92df5-2aa0-4b06-b807-aa21767545cd}
Save Page WE	extension	28.11	true	savepage-we@DW-dev
ShareX	extension	2.0.1	true	firefox@getsharex.com
Shortkeys (Custom Keyboard Shortcuts)	extension	4.0.2	true	Shortkeys@Shortkeys.com
Simplify Copilot - Autofill job applications	extension	1.6.13	true	sabre@simplify.jobs
SponsorBlock for YouTube - Skip Sponsorships	extension	5.5.4	true	sponsorBlocker@ajay.app
Stylus	extension	1.5.46	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
SVG Export	extension	2.2.17	true	{605a075b-09d9-4443-bed6-4baa743f7d79}
Tab Manager Plus for Firefox	extension	5.2.0	true	{45f2dc53-96cd-4c41-91f6-f4a73a8fb2b0}
Tampermonkey	extension	5.0.1	true	firefox@tampermonkey.net
TinEye Reverse Image Search	extension	2.0.4	true	tineye@ideeinc.com
Toolkit for YNAB	extension	3.11.1	true	{4F1FB113-D7D8-40AE-A5BA-9300EAEA0F51}
Twitter Video Downloader	extension	1.0.3	true	extension@twittervid.com
uBlock Origin	extension	1.55.0	true	uBlock0@raymondhill.net
UnloadTabs	extension	0.8.5	true	@unload-tabs
Vimium	extension	2.0.6	true	{d7742d87-e61d-4b78-b8a1-b469842139fa}
Vue.js devtools	extension	6.5.1	true	{5caff8cc-3d2e-4110-a88a-003cc85b3858}
Wikipedia (en)	extension	1.3	true	wikipedia@search.mozilla.org
Youtube Watchmarker	extension	4.6.1	true	yourect@coderect.com
Dark	theme	1.2	true	firefox-compact-dark@mozilla.org
</pre>
</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
The blurry image is just a screenshot image, it's not real UI.

uBlock Enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/44609630/c3e2e7f0-8891-47d9-8d73-3336c8209a24)

uBlock Disabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/44609630/1510d9ec-8d8f-496c-b675-49f8ca679b49)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 123
filterset (summary):
 network: 122512
 cosmetic: 45465
 scriptlet: 19120
 html: 2098
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37752-194, 1h.29m Δ
  ublock-badware: 7850-14, 1h.29m Δ
  ublock-privacy: 994-0, 1h.29m Δ
  ublock-unbreak: 2260-0, 1h.29m Δ
  ublock-quick-fixes: 217-0, 1h.29m Δ
  easylist: 80693-545, 1h.29m Δ
  easyprivacy: 50194-879, 1h.29m Δ
  urlhaus-1: 7235-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 155 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  backblazeb2.com: 1
  hs-analytics.net: 1
  hs-banner.com: 1
  hsadspixel.net: 1
  hsforms.com: 2
  hsleadflows.net: 1
  pendo.io: 2
  segreencolumn.com: 3
```
</details>

**Comment by D4niloMR** [comment]
Test:

```adb
@@||cdn.pendo.io/agent/static/*/pendo.js$script,3p,domain=secure.backblaze.com
@@||data.pendo.io/data/guide.js/$script,3p,domain=secure.backblaze.com
```

Account for test purposes:

`123345678910@gmail.com`:`123345678910`
