### ISSUE TITLE
delfi.lt: nuisance

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#22456]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.delfi.lt/news/daily/lithuania/ka-is-tikruju-atskleide-putino-interviu-viena-zinute-buvo-skirta-ne-tik-ukrainai-bet-ir-lietuvai-95852473`

### Category

nuisance

### Description

The site manipulates its copy functionality by replacing copied text with the article's link.

Related discussion:
`https://github.com/DandelionSprout/adfilt/discussions/779#discussioncomment-8436558`

Suggested filter:
```adblock
delfi.lt##+js(aeld, copy)
```

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.1b28
Firefox: 122
filterset (summary):
 network: 122468
 cosmetic: 45498
 scriptlet: 19136
 html: 2098
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37811-106, 23m Δ
  ublock-badware: 7849-14, 23m Δ
  ublock-privacy: 995-0, 23m Δ
  ublock-unbreak: 2261-2, 23m Δ
  ublock-quick-fixes: 219-4, 23m Δ
  easylist: 80698-240, 23m Δ
  easyprivacy: 50198-87, 23m Δ
  urlhaus-1: 7175-0, now
  plowe-0: 3782-1184, now
filterset (user): [array of 69 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 208 ms (selfie)
 maxAssetCacheWait: 124 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 20
 network:
  delfi.lt: 3
  adform.net: 2
  cxense.com: 5
  dimatter.ai: 1
  facebook.net: 1
  gemius.pl: 1
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 2
  npttech.com: 1
  stpd.cloud: 1
  youtube.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
Nevermind, I can reproduce on another profile.
