### ISSUE TITLE
civilsdaily.com: ads

### ISSUE THREAD

**Issue by manuviens** [uBlockOrigin/uAssets#22458]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.civilsdaily.com/news/fediverse-understanding-decentralized-social-networking/`

### Category

ads

### Description

Popups ads

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98410832/edf1ee5f-daba-43c7-89cb-312803baedec)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 140173
 cosmetic: 52380
 scriptlet: 19279
 html: 2098
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 37890-247, 51m Δ
  ublock-badware: 7849-14, 51m Δ
  ublock-privacy: 995-0, 51m Δ
  ublock-unbreak: 2261-0, 51m Δ
  ublock-quick-fixes: 217-0, 51m Δ
  easylist: 80796-790, 51m Δ
  easyprivacy: 50199-1061, 51m Δ
  urlhaus-1: 7300-0, now
  plowe-0: 3782-1, now
  FRA-0: 25077-113, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 757 ms (selfie)
 maxAssetCacheWait: 207 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  civilsdaily.com: 2
  googletagmanager.com: 1
 extended:
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
add

`civilsdaily.com##.modal`

annoyance @ryanbr @Alex-302

**Comment by manuviens** [comment]
Working, thank you !

**Comment by Alex-302** [comment]
It blocks login popup.
Added `civilsdaily.com###z.modal`
