### ISSUE TITLE
detection: sinonimos.de

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#22453]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://sinonimos.de/the-best-digital-marketing-tools/
if there is no timer in the above link, it can be achieved by going through https://ctr.sh/4uJmoPFO
```

### Description

1. adblock detection
2. rapid timer reduction not working (was working until yesterday)

### Other extensions used

Popup Blocker (strict)
Universal Bypass
Privacy Badger

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 223599
 cosmetic: 227309
 scriptlet: 50142
 html: 2312
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77116-286, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97024-68897, now
  adguard-generic: 82678-5331, now
  adguard-mobile: 9067-102, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 50034-3824, now
  ublock-annoyances: 6624-11, 45m Δ
  dpollock-0: 11638-493, now
  adguard-spyware: 94461-867, now
 default:
  user-filters: 42-5, never
  ublock-filters: 37786-505, 45m Δ
  ublock-badware: 7849-14, 45m Δ
  ublock-privacy: 995-0, 45m Δ
  ublock-unbreak: 2261-0, 45m Δ
  easylist: 80731-2667, 45m Δ
  easyprivacy: 50198-33054, 45m Δ
  urlhaus-1: 7175-0, 45m
  plowe-0: 3782-1, now
  ublock-quick-fixes: 219-0, 45m Δ
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 635 ms (selfie)
 maxAssetCacheWait: 217 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 3
  googletagmanager.com: 1
  profitsfly.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(set-constant, waitTime441, 0)
  ##+js(adjust-setInterval, waitTime, *, 0.02)
  ##+js(abort-on-property-read, adsBlocked)
```
</details>

**Comment by ItsProfessional** [comment]
Continue in #17361
