### ISSUE TITLE
hulu.com: breakage

### ISSUE THREAD

**Issue by 3052** [uBlockOrigin/uAssets#22452]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://hulu.com/watch/f6a4c981-745e-48ef-aaa0-c857c187ce93
```

### Description

~~~
We're having trouble playing this
Rest assured, we're working on it. In the meantime, it may help if you restart
the video.
Hulu Error Code: P-DEV313
Unique Error ID: 990535B2-E923-7FF5-47E4-A9615CBC7615
Local Time of Error: 2024-02-11 20:02:43 (UTC6)
~~~

note this is with no special rules. then if I turn off uBlock Origin, it works fine. I can share credentials if need be.

### Other extensions used

!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 101
filterset (summary):
 network: 122550
 cosmetic: 45525
 scriptlet: 19126
 html: 2098
listset (total-discarded, last-updated):
 default:
  user-filters: 29-0, never
  ublock-filters: 37790-140, 5h.54m Δ
  ublock-badware: 7849-14, 5h.54m Δ
  ublock-privacy: 994-0, 5h.54m Δ
  ublock-unbreak: 2261-0, 5h.54m Δ
  ublock-quick-fixes: 223-0, 5h.54m Δ
  easylist: 80721-648, 5h.54m Δ
  easyprivacy: 50198-832, 5h.54m Δ
  urlhaus-1: 7235-0, 11h.54m
  plowe-0: 3784-1, 6d.36m
filterset (user): [array of 36 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 added: [array of 150 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 995 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  github.com: 44
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
Firefox: 101
```

Can you test in an updated Firefox version (current is 122) with only uBO and its default settings (you are having a modified configuration)?

**Comment by 3052** [comment]
> Can you test in an updated Firefox version (current is 122) with only uBO and its default settings (you are having a modified configuration)?

If I download Firefox 111 or later, extract and install uBO and try, it works. however after updating my actual browser to 111, its still failing for some reason. I made sure to reset the uBO to default.

> Then in that browser, open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here.

~~~
uBlock Origin: 1.55.0
Firefox: 111
filterset (summary):
 network: 122489
 cosmetic: 45469
 scriptlet: 19109
 html: 2094
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37740-223, 2m
  ublock-badware: 7849-14, 2m
  ublock-privacy: 995-0, 2m
  ublock-unbreak: 2260-0, 2m
  ublock-quick-fixes: 219-0, 2m
  easylist: 80731-545, 2m
  easyprivacy: 50194-851, 2m
  urlhaus-1: 7175-0, 2m
  plowe-0: 3782-1, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1409 ms
 maxAssetCacheWait: 24 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 network:
  hulu.com: 19
  ads-twitter.com: 1
  conviva.com: 4
  demdex.net: 3
  imrworldwide.com: 1
  omtrdc.net: 7
  sc-static.net: 1
  yimg.com: 2
 extended:
  ##+js(set-constant, Object.prototype._parseVAST, noopFunc)
  ##+js(set-constant, Object.prototype.createAdBlocker, noopFunc)
  ##+js(set-constant, Object.prototype.isAdPeriod, falseFunc)
  ##+js(json-prune-fetch-response, breaks pause_ads video_metadata…
  ##+js(json-prune, breaks pause_ads video_metadata.end_credits_ti…
  ##+js(xml-prune, xpath(//*[name()="MPD"]/@mediaPresentationDurat…
~~~

**Comment by stephenhawk8054** [comment]
Uninstall uBO and test again. Does it still works? Then reinstall uBO (without other configurations) and test again.

**Comment by 3052** [comment]
> Uninstall uBO and test again. Does it still works? Then reinstall uBO (without other configurations) and test again.

AH OK, this worked. choosing the uBO Reset to default settings did not fix it, but uninstall and reinstall uBO fixed it, along with Firefox 111 of course - thank you!
