### ISSUE TITLE
hitbullseye.com: ads

### ISSUE THREAD

**Issue by Broken-Glass1** [uBlockOrigin/uAssets#22454]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.hitbullseye.com/Seating-Arrangement.php
```

### Description

.

### Other extensions used

.

### Screenshot(s)

![brave_screenshot_www hitbullseye com](https://github.com/uBlockOrigin/uAssets/assets/159278763/1635a87f-f9de-4a7b-8e7e-ca99eb0a087c)

### Configuration

ubo default

**Comment by mapx-** [comment]
add

`||hitbullseye.com/*.gif$image`

@ryanbr

**Comment by JobcenterTycoon** [comment]
It breaks also other real images.

And ads on `https://www.hitbullseye.com/Quant` are missed.

**Comment by Yuki2718** [comment]
On my end the second rule is enough, is there ad missed by the second one but caught by the first?

**Comment by Yuki2718** [comment]
There are some more banners but looks to be self-promo. I leave them to @ryanbr .
