### ISSUE TITLE
resetera.com: detection

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#22469]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.resetera.com/threads/switch-lite-oled-coming-courtesy-of-modders-hdmi-output-may-follow.811056/`

### Category

detection

### Description

Twitter embed is not working

### Other extensions used

none

### Screenshot(s)

<img width="1463" alt="Screenshot 2024-02-12 at 21 31 50" src="https://github.com/uBlockOrigin/uAssets/assets/149429107/ca43a0ad-61f9-49ba-9158-a03c3615d6c5">

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 122694
 cosmetic: 45510
 scriptlet: 19139
 html: 2098
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37895-291, now
  ublock-badware: 7849-14, now
  ublock-privacy: 995-0, now
  ublock-unbreak: 2261-0, now
  ublock-quick-fixes: 217-0, now
  easylist: 80798-547, now
  easyprivacy: 50199-851, now
  urlhaus-1: 7300-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 805 ms
 maxAssetCacheWait: 4 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  resetera.com: 2
  adthrive.com: 1
  alexametrics.com: 1
  btloader.com: 2
  cloudflareinsights.com: 2
  googletagmanager.com: 1
 extended:
  ##.samCodeUnit
```
</details>

**Comment by ItsProfessional** [comment]
Caused by firefox "Enhanced Tracking Protection", not uBO.

**Comment by Dani-1-2** [comment]
> > * [x]  I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
> 
> You did not. It's caused by firefox's "Enhanced Tracking Protection", not uBO.

I apologize.
