### ISSUE TITLE
pt.aliexpress.com: breakage

### ISSUE THREAD

**Issue by Miguel-Rodrigues** [uBlockOrigin/uAssets#22464]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pt.aliexpress.com/w/wholesale-SN74LVC1G86DBVT.html?g=y&SearchText=SN74LVC1G86DBVT`

### Category

breakage

### Description

When searching for items on Aliexpress, the search results show for a split second, being then removed immediately after.
Possible anti blocker on search results. Loads the results and then removes them after some content gets blocked.

### Other extensions used

- Dark Reader
- Picture in Picture Extension
- QR Code
- Adobe Reader
- Google Docs offline

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/10254384/33bd34be-10c6-4e5b-97be-2169e8175d04

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122733
 cosmetic: 45536
 scriptlet: 20515
 html: 0
listset (total-discarded, last-updated):
 removed:
  spa-1: null
 default:
  user-filters: 1-0, never
  easylist: 80810-14, 1h.7m Δ
  easyprivacy: 50199-38, 1h.7m Δ
  plowe-0: 3782-1184, 36m
  ublock-badware: 7845-141, 1h.7m Δ
  ublock-filters: 37374-349, 1h.7m Δ
  ublock-privacy: 999-6, 1h.7m Δ
  ublock-quick-fixes: 264-90, 1h.7m Δ
  ublock-unbreak: 2213-32, 1h.7m Δ
  urlhaus-1: 7300-0, 1h.7m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 322 ms
 maxAssetCacheWait: 133 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 25
 network:
  alicdn.com: 2
  criteo.net: 1
  facebook.net: 1
  go-mpulse.net: 1
  mmstat.com: 20
 extended:
  ##div[data-spm="seoads"]
  ###card-list > .search-item-card-wrapper-gallery:has(a.search-ca…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
aliexpress.com#@?##card-list > .search-item-card-wrapper-gallery:-abp-has(a.search-card-item[href*="&aem_p4p_detail="] div[class*="cards--image--"] > div[class*="multi--ax--"]:-abp-contains(/^(?:AD|An[uú]ncio|광고|広告)$/))
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by Miguel-Rodrigues** [comment]
Sorry I didn't gave feedback in time...

It is now working.
