### ISSUE TITLE
nowtv.com.tr: detection

### ISSUE THREAD

**Issue by juarez-spa3** [uBlockOrigin/uAssets#22466]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
`https://www.fox.com.tr/`
```

### Description

This domain currently redirects to Now TV. This rule needs to be updated
```
! https://forums.lanik.us/viewtopic.php?f=62&t=42004
fox.com.tr##+js(set, adblockDetector, trueFunc)
```

### Other extensions used

none

### Screenshot(s)

-

### Configuration

-

**Comment by ghajini** [comment]
**URL =** 

    https://www.nowtv.com.tr/Orta-Sayfa/fragman/1-Bolum-3-Fragman

**issue =**  video does not show up

**troubleshooting information** =

<details>

```yaml
uBlock Origin: 1.70.1b4
Chromium: 146
filterset (summary):
 network: 172570
 cosmetic: 55088
 scriptlet: 37154
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  TUR-0: 16077-31, 1h.6m
 default:
  ublock-filters: 50814-100, 2h.23m Δ
  ublock-badware: 10928-30, 2h.23m Δ
  ublock-privacy: 4000-4, 2h.23m Δ
  ublock-unbreak: 2750-1, 2h.23m Δ
  ublock-quick-fixes: 436-0, 2h.23m Δ
  easylist: 95857-506, 2h.23m Δ
  easyprivacy: 55648-703, 2h.23m Δ
  urlhaus-1: 26300-11, 2h.23m
  plowe-0: 3519-0, 3d.21h.4m
filterset (user): [array of 1420 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 391 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  pghub.io: 1
 extended:
  ##.ads:not(#style_important)
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.custom-ad
  ##.custom-ad-container
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
  ##+js(prevent-setInterval, .addClass('getir'))
  ##+js(set-constant, adblockDetector, trueFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

```adb
@@||googletagmanager.com/gtm.js$script,domain=nowtv.com.tr
@@||cdn.cookielaw.org/scripttemplates/*/otBannerSdk.js$script,domain=nowtv.com.tr
nowtv.com.tr#@##onetrust-consent-sdk
nowtv.com.tr#@##onetrust-banner-sdk
nowtv.com.tr##+js(trusted-click-element, button[id="onetrust-reject-all-handler"], , 1500)
```
