### ISSUE TITLE
[nsfw] ddd-smart.net: ads

### ISSUE THREAD

**Issue by hanekuro** [uBlockOrigin/uAssets#22467]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ddd-smart.net/doujinshi3/show-m.php?g=20240126&dir=002&page=0&from=list&from=package-list`

### Category

ads

### Description

広告が表示される
[Translation: `Ads are displayed`]

### Other extensions used

Dark Render
keepa

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 120
filterset (summary):
 network: 125466
 cosmetic: 48852
 scriptlet: 20756
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  JPN-1: 14039-134, 3m
  adguard-mobile: 9072-71, 3m
  easylist: 80811-15999, 3m
  easyprivacy: 50199-74, 3m
  plowe-0: 3782-1264, 3m
  ublock-badware: 7839-153, 3m
  ublock-filters: 37730-602, 3m
  ublock-privacy: 999-7, 3m
  ublock-quick-fixes: 266-91, 3m
  ublock-unbreak: 2218-38, 3m
  urlhaus-1: 6700-0, 3m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5958 ms
 maxAssetCacheWait: 101 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 13
 network:
  ddd-smart.net: 2
  googletagmanager.com: 1
  waqool.com: 10
 extended:
  ##img[src*="//cdn.ddd-smart.net/ad/"]
  ##.bookview-wrap a[class*="id"][target="_blank"]
  ##ul.out-scroll-img__list
  ##div[id^="active_overlay"]
```
</details>

**Comment by Yuki2718** [comment]
I can't reproduce with Firefox Mobile. What browser are you using? Screenshot(s) of the ads?

**Comment by Yuki2718** [comment]
I guess reproduced.
