### ISSUE TITLE
biobiochile.cl: detection

### ISSUE THREAD

**Issue by elhuiro** [uBlockOrigin/uAssets#22465]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.biobiochile.cl/`

### Category

detection

### Description

the page brings up a pop up that say that ublock its detected and block the navigation on the website. It could be used using the element zapper mode, but after every new click on the page (its a newspaper so everytime you access a news) the same message popup and block the navigation

### Other extensions used

adblock ultimate
adaware ADBLOCK

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/159853043/4bdf6ef8-50f0-4835-b752-2ae566e20ad1)
<img width="960" alt="Screenshot 2024-02-12 20 14 41" src="https://github.com/uBlockOrigin/uAssets/assets/159853043/033e98f1-bf5b-4712-8c48-788f38efd75c">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 122702
 cosmetic: 45517
 scriptlet: 19141
 html: 2099
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37898-206, now
  ublock-badware: 7849-14, now
  ublock-privacy: 995-0, now
  ublock-unbreak: 2261-0, now
  ublock-quick-fixes: 217-0, now
  easylist: 80811-651, now
  easyprivacy: 50199-832, now
  urlhaus-1: 7300-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2134 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 network:
  bbcl.cl: 4
  digitalproserver.com: 2
  doubleclick.net: 1
  google-analytics.com: 2
  googletagmanager.com: 2
  imasdk.googleapis.com: 2
  mrf.io: 1
  rudo.video: 2
  scorecardresearch.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Enable the AdGuard Spanish/Portuguese list.

---

> ### Other extensions used
> 
> adblock ultimate
> adaware ADBLOCK

See: https://twitter.com/gorhill/status/1033706103782170625

**Comment by krystian3w** [comment]
One more: https://github.com/uBlockOrigin/uBlock-issues/issues/3117
