### ISSUE TITLE
Easylist breaking watchcartoononline.io

### ISSUE THREAD

**Issue by Ofunniku** [uBlockOrigin/uAssets#2246]
watchcartoononline DOT io (I'm avoiding linking to the site directly)

disabling easylist and refreshing restores proper layout

enabled a bunch of other lists, none causing issues except easylist

**Comment by mapx-** [comment]
update unbreak list

**Comment by Ofunniku** [comment]
thanks, confirmed fixed

**Comment by zaphodbeebblebrox** [comment]
Site is broken again, can be fixed with `@@||watchcartoononline.io/inc/*/report.js$script,domain=watchcartoononline.io`

**Comment by lain566** [comment]
The player is broken.
`https://www.watchcartoononline.io/playlist-cat/396/yu-gi-oh-gx-episode-1-english-dubbed-2`
