### ISSUE TITLE
[nsfw] mat6tube.com: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#22477]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mat6tube.com/video/watch+porn`

### Category

ads

### Description

top and bottom has empty ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 110
filterset (summary):
 network: 134006
 cosmetic: 166877
 scriptlet: 30077
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6759-214, now
 default:
  user-filters: 32-4, never
  adguard-mobile: 9188-16, now
  easylist: 81045-126, now
  easyprivacy: 50196-159, now
  plowe-0: 3782-1260, now
  ublock-badware: 7845-142, now
  ublock-filters: 37768-820, now
  ublock-privacy: 975-8, now
  ublock-quick-fixes: 138-26, now
  ublock-unbreak: 2221-37, now
  urlhaus-1: 7220-0, now
filterset (user): [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2140 ms (selfie)
 maxAssetCacheWait: 397 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 1
  google.com: 1
  googletagmanager.com: 1
  jsdelivr.net: 1
  tsyndicate.com: 4
 extended:
  ##+js(adjust-setTimeout, download, 1100)
  ##+js(set-constant, ads, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
ignoreGenericCosmeticFilters: false
```

You are disabling generic cosmetic filters. Turn it on again.

**Comment by BlazeFTL** [comment]
You Missed One Placeholder In The Video Player..Play A Video

**Comment by Yuki2718** [comment]
I don't see `ipvertnet.com`.
