### ISSUE TITLE
yandex.com ads

### ISSUE THREAD

**Issue by G-D-B-9-9** [uBlockOrigin/uAssets#22478]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://yandex.com/images
```

### Description

Ads injected among search results 

### Other extensions used

Violentmonkey
Twitter UI Customizer 

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 110
filterset (summary):
 network: 59927
 cosmetic: 78220
 scriptlet: 25945
 html: 0
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  urlhaus-1: null
 added:
  adguard-cookies: 28607-1601, 1d.18h.38m
  fanboy-cookiemonster: 50070-19652, 1d.18h.37m
  ublock-cookies-adguard: 972-20, 1d.18h.37m
  ublock-cookies-easylist: 972-972, 1d.18h.37m
 default:
  user-filters: 5-0, never
  easylist: 81045-15937, 4h.59m Δ
  ublock-filters: 37767-401, 4h.59m Δ
  ublock-privacy: 975-4, 4h.59m Δ
  ublock-quick-fixes: 134-26, 4h.59m Δ
  ublock-unbreak: 2220-15, 4h.59m Δ
filterset (user): [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1014 ms (selfie)
 maxAssetCacheWait: 521 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by ItsProfessional** [comment]
duplicate of https://github.com/uBlockOrigin/uAssets/issues/14700

**Comment by G-D-B-9-9** [comment]
I haven't I use AdAway in Android and there is lots of adblocking lists

![Screenshot_20240214-221627](https://github.com/uBlockOrigin/uAssets/assets/82726385/90eaf172-a06c-46cb-a107-99eea3787c07)

Some 220 000 hosts in AdAway

**Comment by G-D-B-9-9** [comment]
I use AdAway in Android + ublock origin in mobile browser(s)
