### ISSUE TITLE
netzwelt.de: nuisance

### ISSUE THREAD

**Issue by darealdemayo** [uBlockOrigin/uAssets#22474]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.netzwelt.de/download/12130-mremote.html`

### Category

nuisance

### Description

Cookie or Pay banner

### Other extensions used

keepassXC-browser

### Screenshot(s)

it's not hard to describe

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 337597
 cosmetic: 275566
 scriptlet: 52892
 html: 0
listset (total-discarded, last-updated):
 added:
  CZE-0: 832-1, now
  DEU-0: 7258-0, now
  FRA-0: 25077-52, now
  NLD-0: 2772-19, now
  POL-0: 8690-12, now
  POL-2: 1280-14, now
  adguard-cookies: 28743-33, now
  adguard-generic: 80945-969, now
  adguard-mobile: 9188-65, now
  adguard-mobile-app-banners: 5032-8, now
  adguard-other-annoyances: 14178-15, now
  adguard-popup-overlays: 26953-112, now
  [18 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 81025-1668, 11m Δ
  easyprivacy: 50196-32567, 11m Δ
  plowe-0: 3782-1359, now
  ublock-badware: 7851-268, 11m Δ
  ublock-filters: 37413-4157, 11m Δ
  ublock-privacy: 975-399, 11m Δ
  ublock-quick-fixes: 134-29, 11m Δ
  ublock-unbreak: 2215-158, 11m Δ
  urlhaus-1: 6695-0, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 651 ms (selfie)
 maxAssetCacheWait: 545 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  netzwelt.de: 1
  vgwort.de: 1
  webpushr.com: 1
 extended:
  ##.inner-ad
  ##.native-ad
  ##.jobbioapp
  ##.m-share
  ###onetrust-consent-sdk
  ##.onetrust-pc-dark-filter
  ###onetrust-banner-sdk
  ##.ad
  ##._Bell[onclick^="_webpushrGetPromp"]
  ##.subscribeboard
  ##.nl-share
  ##ul.mfb--bl
  ##a[href^="https://twitter.com/share"]
  ##a[href*="//getpocket.com/edit?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
enable `uBlock filters – Cookie Notices`

**Comment by mapx-** [comment]
update that list clicking:

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-annoyances&manual=1

**Comment by mapx-** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/f2dc06c5-6a3e-417f-85c8-bd20d3032bc2)

I added a filter 2 hours ago, that's why you had to update that list

uBO annoyances contains uBO cookies list (that's why you see 0)
