### ISSUE TITLE
elektroda.pl - content post disappears

### ISSUE THREAD

**Issue by gulson-dev** [uBlockOrigin/uAssets#22470]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.elektroda.pl/rtvforum/topic4035645.html
https://www.elektroda.pl/rtvforum/topic1906706-210.html#9394288
https://www.elektroda.pl/rtvforum/topic2767179.html#13357558
https://www.elektroda.pl/rtvforum/topic2662626.html#12810254
https://www.elektroda.pl/rtvforum/find.php?q=utm_
+1000
```

### Description

Hi,
The issue was reported by one of our forum users today. It appears that when the uBlockOrigin extension is active, all post content on our forum disappears.

This seems to be related to a specific filtering rule that was added approximately 5 days ago:
```
elektroda.pl##*:has(> a[href*="?utm_"])
```
You can find the commit for this change here: [dd2852365cecf6616d071d141f80be79f6b7d20d](https://github.com/uBlockOrigin/uAssets/commit/dd2852365cecf6616d071d141f80be79f6b7d20d)

The issue occurs when a user includes any link containing `?utm_` within their post. As a result, the entire post content is being removed.

Additionally, I have shared some insights regarding a user garry-ut99 activity that seems to be aimed at disrupting the functionality of our platform. For more context, please refer to my comment on the issue [#1545](https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-1940718256).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-13 at 11 14 10](https://github.com/uBlockOrigin/uAssets/assets/65391101/a371c76a-bfd4-449f-9061-bf9994cea30d)
![Screenshot 2024-02-13 at 11 15 15](https://github.com/uBlockOrigin/uAssets/assets/65391101/41e5d116-0528-4ec3-9e45-fb6a6f395db3)
![Screenshot 2024-02-13 at 11 15 39](https://github.com/uBlockOrigin/uAssets/assets/65391101/d47011bc-4411-4f4e-8fe6-35b986ab38e7)
![Screenshot 2024-02-13 at 11 16 58](https://github.com/uBlockOrigin/uAssets/assets/65391101/579cd243-07fe-41da-928b-ea845da25245)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 123552
 cosmetic: 53780
 scriptlet: 20724
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 8690-9, 2h.14m
  POL-2: 1280-14, 2h.14m
 default:
  user-filters: 0-0, never
  easylist: 80810-38, 14m Δ
  easyprivacy: 50199-38, 14m Δ
  plowe-0: 3782-1191, 2h.14m
  ublock-badware: 7845-141, 14m Δ
  ublock-filters: 37374-388, 14m Δ
  ublock-privacy: 999-6, 14m Δ
  ublock-quick-fixes: 264-90, 14m Δ
  ublock-unbreak: 2213-33, 14m Δ
  urlhaus-1: 6700-0, 2h.14m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 197 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  elektroda.pl: 1
  doubleclick.net: 1
  errorception.com: 1
  google-analytics.com: 1
  google.com: 1
 extended:
  ##*:has(> a[href*="?utm_"])
  ##*:has(> .top-box-caption:has-text(/REKLAMA|WERBUNG/) + a)
  ##+js(set-constant, loadElementBlock, noopFunc)
  ##+js(no-setTimeout-if, adBlockTest, 100)
  #@#+js(set-constant, loadElement, noopFunc)
```
</details>

**Comment by JobcenterTycoon** [comment]
Removed the filter.

**Comment by gulson-dev** [comment]
Thank you so much!

**Comment by garry-ut99** [comment]
Beware - this guy gulson likes to troll, he is known for intentionally breaking his own site and then blaming filter creators for the breakage, just like he did on POL tracker, also he is known for personal attacking and trolling, like described in full the story: https://github.com/uBlockOrigin/uAssets/issues/1545#issuecomment-1942577142
