### ISSUE TITLE
[Anti-adblock] finofilipino.org

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2247]
### URL(s) where the issue occurs

`https://finofilipino.org/post/173781428878/los-seguidores-de-paquirrin`

### Describe the issue

Comments don't load. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/39932889-9aa344f4-54fe-11e8-9cd1-aabc32ff102b.png)
![image](https://user-images.githubusercontent.com/7283682/39932899-a2d080ba-54fe-11e8-95b0-d8bc8b9924e1.png)

### Versions

- Browser/version: 68
- uBlock Origin version: 1.16.4

### Settings

All default

### Notes

Original report: 
```
Reference: Quick Issue Reporter

Message:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Nano Defender 14.17

[Anti-adblock] https://finofilipino.org/post/173781428878/los-seguidores-de-paquirrin
replaces the comments section with the anti-blocking message
```

**Comment by uBlock-user** [comment]
`finofilipino.org##script:inject(set-constant.js, caca, noopFunc)`
