### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by karafo** [uBlockOrigin/uAssets#22485]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bild.de/adblockwall.html`

### Category

detection

### Description

After updating uBlock website shows still adblocker detection

### Other extensions used

Google Drive, Fluff Busting Purity, Recent History, tiny URL shortener

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bild-adblocker](https://github.com/uBlockOrigin/uAssets/assets/29731481/5fe6e673-b8f3-4660-a1d4-f2cf366b363e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 125444
 cosmetic: 50373
 scriptlet: 20440
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7258-0, 1h.27m
  easylist: 81045-21, 1h.28m
  easyprivacy: 50196-47, 1h.28m
  plowe-0: 3782-1185, 1h.28m
  ublock-badware: 7861-141, 1h.28m
  ublock-filters: 37281-364, 1h.28m
  ublock-privacy: 975-6, 1h.28m
  ublock-quick-fixes: 138-26, 1h.28m
  ublock-unbreak: 2211-34, 1h.28m
  urlhaus-1: 7485-0, 1h.28m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 425 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  bild.de: 2
  bing.com: 1
  cxense.com: 1
  demdex.net: 2
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  ioam.de: 1
  kameleoon.eu: 1
  outbrain.com: 1
  taboola.com: 3
 extended:
  ##+js(no-setTimeout-if, offsetParent)
  ##+js(abort-on-property-read, SmartAdServerASMI)
  ##+js(json-prune, adBlockWallEnabled)
  ##+js(set-constant, __NUXT__.state.advertisement.adBlockWallEnab…
  ##+js(addEventListener-defuser, load, adBlock)
```
</details>

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21987
