### ISSUE TITLE
oko.sh: ads

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#22482]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://oko.sh/MFh`

### Category

ads

### Description

There is a fake "Click here to continue" button. It's in the 2nd step of the page.

this is the html element:
`<a href="https://eergortu.net/4/5016961" target="_blank"><img src="/webroot/img/25525422.png"></a>`

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 129667
 cosmetic: 125680
 scriptlet: 27904
 html: 2309
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4363-97, now
  easylist-chat: 181-0, now
  fanboy-cookiemonster: 50085-229, now
  ublock-cookies-easylist: 936-0, now
  easylist-newsletters: 6974-13, now
  easylist-notifications: 2941-4, now
  fanboy-social: 16152-24, now
  ublock-annoyances: 6633-969, 1h.12m Δ
  spa-0: 3879-3, now
  spa-1: 5404-178, now
 default:
  user-filters: 2-0, never
  ublock-filters: 37946-187, 1h.12m Δ
  ublock-badware: 7855-14, 1h.12m Δ
  ublock-privacy: 971-0, 1h.12m Δ
  ublock-unbreak: 2264-0, 1h.12m Δ
  ublock-quick-fixes: 131-0, 1h.12m Δ
  easylist: 81045-735, 1h.12m Δ
  easyprivacy: 50196-952, 1h.12m Δ
  urlhaus-1: 7220-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 626 ms (selfie)
 maxAssetCacheWait: 257 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  oko.sh: 1
  google-analytics.com: 3
  kognoaka.net: 1
  thubanoa.com: 1
 extended:
  ##+js(remove-node-text, script, /document\.createElement|\.banne…
  ##+js(abort-on-property-read, AaDetector)
  ##+js(abort-on-property-read, open)
  ##+js(set-constant, blurred, false)
  ##+js(no-setTimeout-if, Adblock)
  ##+js(no-fetch-if, /googlesyndication|inklinkor|ads\/load/)
  ##+js(abort-current-script, XMLHttpRequest, adb)
  ##+js(no-xhr-if, inklinkor.com)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by ItsProfessional** [comment]
Report link shorteners in #17361
