### ISSUE TITLE
d0000d.com: breakage

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#22483]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://d0000d.com/e/3dkggnm5a9k6`

### Category

breakage

### Description

video does not play

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 124
filterset (summary):
 network: 142037
 cosmetic: 61913
 scriptlet: 23837
 html: 2311
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6694-11, 1h.45m Δ
  FRA-0: 25077-115, 1m
 default:
  user-filters: 11-0, never
  ublock-filters: 38300-253, 1m
  ublock-badware: 7849-14, 1m
  ublock-privacy: 971-0, 1m
  ublock-unbreak: 2269-0, 1m
  ublock-quick-fixes: 131-1, 1m
  adguard-mobile: 9196-102, now
  easylist: 81045-842, 1h.45m Δ
  easyprivacy: 50196-1086, 1h.45m Δ
  urlhaus-1: 7220-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 863 ms (selfie)
 maxAssetCacheWait: 442 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(no-window-open-if)
  ##+js(remove-node-text, script, /adblock|popunder/)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

### Notes
- first reported here `https://www.reddit.com/r/uBlockOrigin/comments/1aq9g8g/ublock_blocks_doodstreams_player_itself/`

@smed79 @Alex-302

these are problematic filters

`*$document,csp=default-src 'self' 'unsafe-inline' data: *.bootstrapcdn.com *.cloudflare.com *.google.com *.googleapis.com *.gstatic.com *.hcaptcha.com *.jquery.com .jwpcdn.com *.recaptcha.net *.video-delivery.net *.youtube.com *.zencdn.net i.doodcdn.co img.doodcdn.co,domain=d0000d.com|do0od.com|dood.la|dood.pm|dood.re|dood.sh|dood.so|dood.to|dood.watch|dood.wf|dood.ws|dood.yt|doods.pro|doodstream.co|doodstream.com|doodstream.me|dooood.com`

`*$subdocument,csp=default-src 'self' 'unsafe-inline' data: *.bootstrapcdn.com *.cloudflare.com *.google.com *.googleapis.com *.gstatic.com *.hcaptcha.com *.jquery.com .jwpcdn.com *.recaptcha.net *.video-delivery.net *.youtube.com *.zencdn.net i.doodcdn.co img.doodcdn.co,domain=d0000d.com|do0od.com|dood.la|dood.pm|dood.re|dood.sh|dood.so|dood.to|dood.watch|dood.wf|dood.ws|dood.yt|doods.pro|doodstream.co|doodstream.com|doodstream.me|dooood.com`

- this happens on not just `d0000d.com` but all doodstream mirror sites

**Comment by Alex-302** [comment]
At the moment I see only one rule. Badfiltered it.
