### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by solimar1963** [uBlockOrigin/uAssets#22489]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bild.de/adblockwall.html`

### Category

detection

### Description

website expects the blocker to be switched off

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/127691532/856f99f6-dbe4-4663-be99-f1752d47c939)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 125755
 cosmetic: 52067
 scriptlet: 23475
 html: 2315
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  ublock-annoyances: 6640-11, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37825-264, now
  ublock-badware: 7865-14, now
  ublock-privacy: 971-0, now
  ublock-unbreak: 2259-0, now
  easylist: 81072-556, now
  easyprivacy: 50196-878, now
  urlhaus-1: 7485-0, now
  plowe-0: 3782-1, now
  DEU-0: 7265-3, now
  ublock-quick-fixes: 133-0, now
filterset (user): [empty]
trustedset:
 added: [array of 31 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 355 ms (selfie)
 maxAssetCacheWait: 133 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  bild.de: 2
  bing.com: 2
  cxense.com: 1
  demdex.net: 2
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  ioam.de: 1
  iocnt.net: 2
  kameleoon.eu: 1
  outbrain.com: 1
  taboola.com: 3
 extended:
  ##+js(no-setTimeout-if, offsetParent)
  ##+js(abort-on-property-read, SmartAdServerASMI)
  ##+js(json-prune, adBlockWallEnabled)
  ##+js(set-constant, __NUXT__.state.advertisement.adBlockWallEnab…
  ##+js(addEventListener-defuser, load, adBlock)
```
</details>

**Comment by mapx-** [comment]
already fixed, update your filters clicking:

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1
