### ISSUE TITLE
fotbollskanalen.se: detection

### ISSUE THREAD

**Issue by filipafm** [uBlockOrigin/uAssets#22480]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.fotbollskanalen.se/`

### Category

detection

### Description

When trying to view video content on the site, it gives a message that says (in Swedish): "Do you have an adblocker running? Please disable it and reload the page to view our content.".

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 122847
 cosmetic: 45446
 scriptlet: 19089
 html: 2095
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37814-134, now
  ublock-badware: 7865-14, now
  ublock-privacy: 971-0, now
  ublock-unbreak: 2264-0, now
  ublock-quick-fixes: 131-0, now
  easylist: 81045-651, now
  easyprivacy: 50196-860, now
  urlhaus-1: 7220-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 421 ms
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  fotbollskanalen.se: 1
  doubleclick.net: 1
  googleoptimize.com: 1
  lwadm.com: 2
  maxetise.net: 2
 extended:
  ##.ad-inner
  ##.ad-right
  ##.ad-sticky
```
</details>

**Comment by ItsProfessional** [comment]
Note for volunteers: the site is related to `tv4play.se`

**Comment by lassekongo83** [comment]
Unable to reproduce. An exakt video link where it happens would be preferable. Firefox tracking protection, or any other blocker may be interfering if they still use the old videoplaza ad provider.

Tv4 did recently change their ad provider to freewheel, so just in case I'll update fotbollskanalen with the same solution. I've yet to find any videos with freewheel on fotbollskanalen though.

**Comment by ItsProfessional** [comment]
@filipafm If you still get the issue after enabling the swedish list, comment here.
