### ISSUE TITLE
various sites: unhandled 'ad recovery'

### ISSUE THREAD

**Issue by ftc2** [uBlockOrigin/uAssets#22491]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.sonyalpharumors.com/
https://publicholidays.de/contact/
https://www.garagejournal.com/forum/

more sightings: https://www.google.com/search?q=%22We+rely+on+ads+to+keep+creating+quality+content+for+you+to+enjoy+for+free%22
```

### Description

i have seen this annoyance around on several sites. some ad broker has an ad recovery feature (anti-adblocker annoyance) that uBO's default filters are not handling so far.

thanks very much for your help <3

> Looks like your ad blocker is on.
> We rely on ads to keep creating quality content for you to enjoy for free.
> Please support our site by disabling your ad blocker or adding `$website` to your whitelist.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="434" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/9761890/67022a3c-ea3d-40ad-b973-af2fdf99444a">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 123158
 cosmetic: 45466
 scriptlet: 19089
 html: 2097
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37824-114, now
  ublock-badware: 7865-14, now
  ublock-privacy: 971-0, now
  ublock-unbreak: 2259-0, now
  ublock-quick-fixes: 113-0, now
  easylist: 81111-651, now
  easyprivacy: 50196-860, now
  urlhaus-1: 7480-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1731 ms
 maxAssetCacheWait: 1493 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  ampproject.org: 2
  datafeedfile.com: 2
  doubleclick.net: 2
  getclicky.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  pinterest.com: 1
  pub.network: 4
  youtube.com: 1
 extended:
  ##[data-freestar-ad]
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed in `uBlock filters – Annoyances` list. Enable that list in 5-6 hours.
