### ISSUE TITLE
croisieresendirect.com: breakage

### ISSUE THREAD

**Issue by QuinoaMillet** [uBlockOrigin/uAssets#22497]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://croisieresendirect.com/`

### Category

breakage

### Description

The button to dismiss cookies is not shown and the band at the bottom containing the button is still visible.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/94190421/b7d3e716-5bd0-4a95-a788-0f51e55d80f1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.1rc4
Firefox: 122
filterset (summary):
 network: 144537
 cosmetic: 126267
 scriptlet: 27620
 html: 2309
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97224-17170, now
  fanboy-thirdparty_social: 68-0, now
  FRA-0: 25077-114, now
  ublock-annoyances: 6659-11, 6m Δ
 default:
  user-filters: 24-0, never
  ublock-filters: 37844-185, 6m Δ
  ublock-badware: 7865-14, 6m Δ
  ublock-privacy: 915-0, 6m Δ
  ublock-unbreak: 2259-0, 6m Δ
  easylist: 81001-793, 6m Δ
  easyprivacy: 50204-1079, 6m Δ
  plowe-0: 3782-1, now
  urlhaus-1: 7275-0, now
  ublock-quick-fixes: 122-0, 6m Δ
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 15 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1043 ms (selfie)
 maxAssetCacheWait: 304 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  google-analytics.com: 2
  googletagmanager.com: 4
  hotjar.com: 2
  maps.googleapis.com: 2
 extended:
  ###accept-cookies
```
</details>

**Comment by gorhill** [comment]
`###accept-cookies` from "EasyList – Cookie Notices" removes the button but not the cookie warning.

Maybe:

    croisieresendirect.com##+js(set-cookie, accepted, 1)

cc @ryanbr
