### ISSUE TITLE
puzzle-minesweeper.com: detection

### ISSUE THREAD

**Issue by BudDeuce** [uBlockOrigin/uAssets#22492]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.puzzle-minesweeper.com/minesweeper-20x20-hard/`

### Category

detection

### Description

Whenever I try to visit this website and its relatives (puzzle-), I am met with a message stating "It seems that you may be using an ad blocking software.

We rely on ads to keep this website alive. Ad blockers also disrupt the normal layout and behavoir of the website.

Please allow the ads on the site or join our [patron program](https://www.puzzle-minesweeper.com/patron.php)!

[Contact us](https://www.puzzle-minesweeper.com/feedback.php) if you have any questions. Thank you!"

I know this is a uBlock Origin issue since disabling it and reloading the website causes the message to go away.

### Other extensions used

Tampermonkey (no scripts enabled for the puzzle- sites), Application Launcher For Drive (by Google), Chromebook Recovery Utility, 
Google Docs Offline, Return YouTube Dislike, SponsorBlock for YouTube - Skip Sponsorships.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="833" alt="Screenshot 2024-02-14 200607" src="https://github.com/uBlockOrigin/uAssets/assets/83543648/43fb4b39-44cf-45a4-8351-42eb6bdd1349">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 123165
 cosmetic: 45479
 scriptlet: 20443
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81089-14, now
  easyprivacy: 50198-38, now
  plowe-0: 3782-1184, now
  ublock-badware: 7861-141, now
  ublock-filters: 37285-349, now
  ublock-privacy: 975-6, now
  ublock-quick-fixes: 120-6, never
  ublock-unbreak: 2216-32, never
  urlhaus-1: 7480-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2370 ms
 maxAssetCacheWait: 11 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  a-mo.net: 1
  adnxs.com: 1
  criteo.com: 1
  d3lj2s469wtjp0.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  lijit.com: 1
  s-onetag.com: 1
```
</details>

**Comment by gorhill** [comment]
You can click on [this link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=20240214) to get the fix.

**Comment by BudDeuce** [comment]
Thank you for your dedication, but when I go to minesweeper after closing the tab and clicking the link, the message still pops up.

**Comment by gorhill** [comment]
I made a mistake in the link, it's corrected now, you can click again on it.

**Comment by BudDeuce** [comment]
Yep, can confirm it works now! Thank you so much!

**Comment by BudDeuce** [comment]
@gorhill Seems like they have cracked down once more, I don't think the ad is an image anymore but a featherlight prompt if that helps.

<img width="1126" alt="Screenshot 2024-02-15 224320" src="https://github.com/uBlockOrigin/uAssets/assets/83543648/072cf2c1-d104-4a7e-b029-554c1dfd1678">

**Comment by BudDeuce** [comment]
BINGO!

<img width="1126" alt="Screenshot 2024-02-15 224938" src="https://github.com/uBlockOrigin/uAssets/assets/83543648/71538dd1-2ff9-4fb0-8319-ab195f80e893">

**Comment by stephenhawk8054** [comment]
Just give descriptions and screenshots. No need for `BINGO`

---

@JobcenterTycoon Looks like the anti-adb banner comes back when we F5 so we should move from annoyance list to main list?

**Comment by BudDeuce** [comment]
That's just me expressing that I found something useful for fixing this issue. I'm just excited, that's all.

**Comment by JobcenterTycoon** [comment]
I thought puzzle site -> the user staying for longer time on one site -> annoyance because its appear one time. But when a reload is needed sometimes it should be moved to main

**Comment by BudDeuce** [comment]
Just saw the commit, after updating the filters, it works now, hopefully for good this time!

I will report back if it broke.
