### ISSUE TITLE
digi24.ro: breakage

### ISSUE THREAD

**Issue by modinfo** [uBlockOrigin/uAssets#22499]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.digi24.ro/`

### Category

breakage

### Description

redirecting continuously without ever loading the landing page or the articles

### Other extensions used

disabled privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 134159
 cosmetic: 199548
 scriptlet: 31890
 html: 2309
listset (total-discarded, last-updated):
 added:
  adguard-social: 22156-47, now
  adguard-cookies: 28767-38, now
  ublock-cookies-adguard: 937-7, now
  adguard-popup-overlays: 26966-965, now
  adguard-mobile-app-banners: 5036-20, now
  adguard-other-annoyances: 14191-405, now
  adguard-widgets: 2439-9, now
  fanboy-thirdparty_social: 68-3, now
  easylist-annoyances: 4368-257, now
  easylist-chat: 182-14, now
  fanboy-cookiemonster: 50137-3832, now
  ublock-cookies-easylist: 937-937, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37838-106, 1h.9m Δ
  ublock-badware: 7865-14, 1h.9m Δ
  ublock-privacy: 915-0, 1h.9m Δ
  ublock-unbreak: 2259-2, 1h.9m Δ
  ublock-quick-fixes: 118-6, 1h.9m Δ
  easylist: 81001-240, 1h.9m Δ
  easyprivacy: 50204-87, 1h.9m Δ
  urlhaus-1: 7275-0, now
  plowe-0: 3782-1186, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1179 ms
 maxAssetCacheWait: 852 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##+js(set-cookie-reload, cmp_level, 5)
  ##+js(set-cookie, cmp_level, 15)
  ##+js(addEventListener-defuser, copy)
```
</details>

**Comment by ghost** [comment]
I get this empty space from their app ad:

https://github.com/user-attachments/assets/5a9faddc-7655-4e39-8425-2a3c29ef9c15
