### ISSUE TITLE
link.nfpa.org: breakage

### ISSUE THREAD

**Issue by jkcfan** [uBlockOrigin/uAssets#22508]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://link.nfpa.org/`

### Category

breakage

### Other extensions used

Microsoft Editor
Last Pass
Printer Logic Extension 1.0.6.1
Adobe Acrobat
My Apps Secure Sign-inm

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122870
 cosmetic: 45505
 scriptlet: 20349
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81022-14, now
  easyprivacy: 50205-38, now
  plowe-0: 3782-1184, now
  ublock-badware: 7886-141, now
  ublock-filters: 37265-351, now
  ublock-privacy: 869-6, now
  ublock-quick-fixes: 129-6, now
  ublock-unbreak: 2211-32, now
  urlhaus-1: 7275-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 486 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  adnxs.com: 1
  ads-twitter.com: 1
  doubleclick.net: 3
  facebook.net: 1
  google-analytics.com: 1
  googleadservices.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  licdn.com: 1
  lsdm.co: 1
  pendo.io: 1
  securedvisit.com: 1
```
</details>

**Comment by gorhill** [comment]
Please describe what exactly is broken.

**Comment by jkcfan** [comment]
Nothing loads on the page, it is completely blank

thank you


Jill Clements​​​​
IT Technician
RLH / HSI
o:      +1(661)383-1019<tel:+1(661)383-1019>
c:      +1(661) 312-2832<tel:+1(661)%20312-2832>
________________________________

**Comment by stephenhawk8054** [comment]
Works fine for me: 
![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/a0436e16-9427-48cb-af26-13de4425f1bd)

Test in a new browser profile with only uBO and its default settings.

**Comment by jkcfan** [comment]
Yes.


Jill Clements​​​​
IT Technician
RLH / HSI
o:      +1(661)383-1019<tel:+1(661)383-1019>
c:      +1(661) 312-2832<tel:+1(661)%20312-2832>
________________________________

**Comment by gorhill** [comment]
I create a dummy account and the site loads for me. I won't be able to further help unless you investigate more on your site about which filter list(s)/filter(s) is causing your issue by using the logger.

**Comment by jkcfan** [comment]
Thank you, I'll try to get more information


Jill Clements​​​​
IT Technician
RLH / HSI
o:      +1(661)383-1019<tel:+1(661)383-1019>
c:      +1(661) 312-2832<tel:+1(661)%20312-2832>
________________________________

**Comment by jkcfan** [comment]
Logger information-hope it helps

+3
link.nfpa.org
0,1
get
script
https://link.nfpa.org/service-worker.js

+1
link.nfpa.org
1
get
xhr
https://id.nfpa.org/nfpaprod.onmicrosoft.com/b2c_1a_signup_signin/v2.0/.well-known/openid-configuration

+0
link.nfpa.org
3
get
image
https://nfpa-cod-production-frontend.s3.amazonaws.com/7916/favicon.ico

+0
link.nfpa.org
3
get
image
https://nfpa-cod-production-frontend.s3.amazonaws.com/7916/favicon-32x32.png

+0
link.nfpa.org
3
get
image
https://nfpa-cod-production-frontend.s3.amazonaws.com/7916/favicon-16x16.png

+0
||adnxs.com^
--
link.nfpa.org
3
get
image
https://secure.adnxs.com/px?id=1237912&seg=21365272&redir=https%3A%2F%2Fpixel.mediaiqdigital.com%2Fpixel%3F%26pixel_id%3D1237912%26uid%3D%24%7BUID%7D&t=2

+0
||googleadservices.com^
--
link.nfpa.org
3
get
script
https://www.googleadservices.com/pagead/conversion/1038202397/?random=1708109378652&cv=11&fst=1708109378652&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&label=C_mVCKLYgIQDEJ3shu8D&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&value=0&bttype=purchase&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.161%7CChromium%3B121.0.6167.161&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1&capi=1&rfmt=3&fmt=4

+0
||doubleclick.net^
--
link.nfpa.org
3
get
script
https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1038202397/?random=1708109378640&cv=11&fst=1708109378640&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.161%7CChromium%3B121.0.6167.161&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1&rfmt=3&fmt=4

+0
/fbevents.js
--
link.nfpa.org
3
get
script
https://connect.facebook.net/en_US/fbevents.js

+0
||ads-twitter.com^
--
link.nfpa.org
3
get
script
https://static.ads-twitter.com/uwt.js

+0
.lms-analytics/
--
link.nfpa.org
3
get
script
https://snap.licdn.com/li.lms-analytics/insight.min.js

+0
||hotjar.com^
--
link.nfpa.org
3
get
script
https://static.hotjar.com/c/hotjar-1952156.js?sv=7

+0
||lsdm.co^
--
link.nfpa.org
3
get
script
https://lsdm.co/smrtdsh/rec.cfm

+0
||doubleclick.net^
--
link.nfpa.org
3
get
frame
https://td.doubleclick.net/td/rul/1038202397?random=1708109378652&cv=11&fst=1708109378652&fmt=3&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&label=C_mVCKLYgIQDEJ3shu8D&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&value=0&bttype=purchase&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.161%7CChromium%3B121.0.6167.161&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1&capi=1

+0
||doubleclick.net^
--
link.nfpa.org
3
get
frame
https://td.doubleclick.net/td/rul/1038202397?random=1708109378640&cv=11&fst=1708109378640&fmt=3&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.161%7CChromium%3B121.0.6167.161&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1

+0
||securedvisit.com^
--
link.nfpa.org
3
get
script
https://track.securedvisit.com/js/sv.js?sv_cid=5775_04622&sv_origin=nfpa.org

+0
||google-analytics.com^
--
link.nfpa.org
0,3
get
xhr
https://www.google-analytics.com/analytics.js

+0
googletagmanager_gtm.js:5
<<
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtag/js?id=G-79Y98SKVHX&l=dataLayer&cx=c

+0
||googletagmanager.com/gtag/js$xhr,redirect-rule=googletagmanager_gtm.js:5
--
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtag/js?id=G-79Y98SKVHX&l=dataLayer&cx=c

+0
||googletagmanager.com^
--
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtag/js?id=G-79Y98SKVHX&l=dataLayer&cx=c

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/systemsettings

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/systemsettings

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/settings

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/roles

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/userrolegroups?userId=298340

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/auth/2852716

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/groups?userId=298340

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/settings

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/roles

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/userrolegroups?userId=298340

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/auth/2852716

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/groups?userId=298340

+0
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340

+0
||googletagmanager.com^
--
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtm.js?id=GTM-W8NLW6L&gtm_auth=&gtm_preview=&gtm_cookies_win=x

+0
link.nfpa.org
3
get
script
https://d2yyd1h5u9mauk.cloudfront.net/integrations/web/v1/library/dGgY9HL6wcgEsPQU/delightedCsat4.js

+0
||pendo.io^$3p
--
link.nfpa.org
3
get
script
https://cdn.pendo.io/agent/static/4c751883-d458-4a13-6009-1a7fdac624ba/pendo.js

**Comment by stephenhawk8054** [comment]
Your logger information does not show all requests from the website. Open the logger first, then open new tab and reproduce the issue with the website later.

**Comment by ItsProfessional** [comment]
@jkcfan Test in a new browser profile.

**Comment by gorhill** [comment]
> Your logger information does not show all requests from the website

Also, we do not really need all the entries from the logger, just the blocked ones are of interest at first.

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by jkcfan** [comment]
Cleared cache, and reset UBO  Logger:

<details><summary>Logger output</summary>

```
+28
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://ublockorigin.github.io/uAssetsCDN/ublock/assets.json
```
```
+26
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist.txt
```
```
+24
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easyprivacy.txt
```
```
+21
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
```
```
+18
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/badware.min.txt
```
```
+15
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/filters.min.txt
```
```
+13
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://ublockorigin.pages.dev/filters/privacy.min.txt
```
```
+11
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/quick-fixes.min.txt
```
```
+9
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://ublockorigin.pages.dev/filters/unbreak.min.txt
```
```
+7
link.nfpa.org
0,1
get
script
https://link.nfpa.org/service-worker.js
```
```
+7
cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme
0,3
get
xhr
https://curbengh.github.io/malware-filter/urlhaus-filter-ag-online.txt
```
```
+6
||pendo.io^$3p
--
link.nfpa.org
3
get
script
https://cdn.pendo.io/agent/static/4c751883-d458-4a13-6009-1a7fdac624ba/pendo.js
```
```
+5
link.nfpa.org
1
get
frame
https://id.nfpa.org/nfpaprod.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize?client_id=84c358b2-a083-463a-bb74-9c1031a1e764&scope=84c358b2-a083-463a-bb74-9c1031a1e764%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Flink.nfpa.org%2Fazure&client-request-id=64ddf982-a786-4ea0-8504-71ac04acc066&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.33.0&client_info=1&code_challenge=ndXJgdXTF_ie7MDzb41LA6mvGrGktxN-bu8B9ye_vXo&code_challenge_method=S256&prompt=none&nonce=67902029-daa4-40ea-a9a1-2fe9b7bb66b6&state=eyJpZCI6ImM2YTQzYzNhLWM0YmUtNGM1OC05Njc3LTc3Zjk1ZDBlNjAwZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoic2lsZW50In19
```
```
+5
link.nfpa.org
1
get
xhr
https://id.nfpa.org/nfpaprod.onmicrosoft.com/b2c_1a_signup_signin/v2.0/.well-known/openid-configuration
```
```
+5
link.nfpa.org
3
get
image
https://nfpa-cod-production-frontend.s3.amazonaws.com/7916/favicon-32x32.png
```
```
+5
link.nfpa.org
3
get
image
https://nfpa-cod-production-frontend.s3.amazonaws.com/7916/favicon-16x16.png
```
```
+5
||adnxs.com^
--
link.nfpa.org
3
get
image
https://secure.adnxs.com/px?id=1237912&seg=21365272&redir=https%3A%2F%2Fpixel.mediaiqdigital.com%2Fpixel%3F%26pixel_id%3D1237912%26uid%3D%24%7BUID%7D&t=2
```
```
+5
||doubleclick.net^
--
link.nfpa.org
3
get
frame
https://td.doubleclick.net/td/rul/1038202397?random=1708443044151&cv=11&fst=1708443044151&fmt=3&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&label=C_mVCKLYgIQDEJ3shu8D&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&value=0&bttype=purchase&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.185%7CChromium%3B121.0.6167.185&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1&capi=1
```
```
+5
||googleadservices.com^
--
link.nfpa.org
3
get
script
https://www.googleadservices.com/pagead/conversion/1038202397/?random=1708443044151&cv=11&fst=1708443044151&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&label=C_mVCKLYgIQDEJ3shu8D&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&value=0&bttype=purchase&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.185%7CChromium%3B121.0.6167.185&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1&capi=1&rfmt=3&fmt=4
```
```
+5
||doubleclick.net^
--
link.nfpa.org
3
get
frame
https://td.doubleclick.net/td/rul/1038202397?random=1708443044143&cv=11&fst=1708443044143&fmt=3&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.185%7CChromium%3B121.0.6167.185&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1
```
```
+5
||doubleclick.net^
--
link.nfpa.org
3
get
script
https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1038202397/?random=1708443044143&cv=11&fst=1708443044143&bg=ffffff&guid=ON&async=1&gtm=45He42c0v830853598za200&gcd=13l3l3l3l1&dma=0&u_w=1920&u_h=1200&url=https%3A%2F%2Flink.nfpa.org%2F&hn=www.googleadservices.com&frm=0&tiba=NFPA%20LiNK%C2%AE&npa=0&pscdl=noapi&auid=1524626893.1707934660&uaa=x86&uab=64&uafvl=Not%2520A(Brand%3B99.0.0.0%7CGoogle%2520Chrome%3B121.0.6167.185%7CChromium%3B121.0.6167.185&uamb=0&uap=Windows&uapv=15.0.0&uaw=0&fledge=1&rfmt=3&fmt=4
```
```
+5
/fbevents.js
--
link.nfpa.org
3
get
script
https://connect.facebook.net/en_US/fbevents.js
```
```
+5
||ads-twitter.com^
--
link.nfpa.org
3
get
script
https://static.ads-twitter.com/uwt.js
```
```
+5
.lms-analytics/
--
link.nfpa.org
3
get
script
https://snap.licdn.com/li.lms-analytics/insight.min.js
```
```
+5
||hotjar.com^
--
link.nfpa.org
3
get
script
https://static.hotjar.com/c/hotjar-1952156.js?sv=7
```
```
+5
||lsdm.co^
--
link.nfpa.org
3
get
script
https://lsdm.co/smrtdsh/rec.cfm
```
```
+5
||securedvisit.com^
--
link.nfpa.org
3
get
script
https://track.securedvisit.com/js/sv.js?sv_cid=5775_04622&sv_origin=nfpa.org
```
```
+5
||google-analytics.com^
--
link.nfpa.org
0,3
get
xhr
https://www.google-analytics.com/analytics.js
```
```
+5
googletagmanager_gtm.js:5
<<
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtag/js?id=G-79Y98SKVHX&l=dataLayer&cx=c
```
```
+5
||googletagmanager.com/gtag/js$xhr,redirect-rule=googletagmanager_gtm.js:5
--
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtag/js?id=G-79Y98SKVHX&l=dataLayer&cx=c
```
```
+5
||googletagmanager.com^
--
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtag/js?id=G-79Y98SKVHX&l=dataLayer&cx=c
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/systemsettings
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/systemsettings
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/settings
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/roles
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/userrolegroups?userId=298340
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/auth/2852716
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/groups?userId=298340
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/settings
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340/roles
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/userrolegroups?userId=298340
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/auth/2852716
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/groups?userId=298340
```
```
+5
link.nfpa.org
0,1
get
xhr
https://link.nfpa.org/en-us/api/v1/users/298340
```
```
+5
||googletagmanager.com^
--
link.nfpa.org
0,3
get
xhr
https://www.googletagmanager.com/gtm.js?id=GTM-W8NLW6L&gtm_auth=&gtm_preview=&gtm_cookies_win=x
```
```
+5
link.nfpa.org
3
get
script
https://d2yyd1h5u9mauk.cloudfront.net/integrations/web/v1/library/dGgY9HL6wcgEsPQU/delightedCsat4.js
```
```
+5
||pendo.io^$3p
--
link.nfpa.org
3
get
script
https://cdn.pendo.io/agent/static/4c751883-d458-4a13-6009-1a7fdac624ba/pendo.js
```
```
+5
link.nfpa.org
0,3
get
xhr
https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i&display=swap
```
```
+3
duckduckgo.com
1
get
frame
https://duckduckgo.com/ntp-tracker-stats.html
```
```
+2
duckduckgo.com
1
get
frame
https://duckduckgo.com/ntp-tracker-stats.html
```
```
+2
duckduckgo.com
1
get
frame
https://duckduckgo.com/ntp-tracker-stats.html
```
```
+1
duckduckgo.com
1
get
frame
https://duckduckgo.com/ntp-tracker-stats.html
```
```
+1
duckduckgo.com
1
get
frame
https://duckduckgo.com/ntp-tracker-stats.html
```
```
+0
duckduckgo.com
1
get
frame
https://duckduckgo.com/ntp-tracker-stats.html
```
```
+0
duckduckgo.com
1
get
frame
https://duckduckgo.com/post3.html
```
```
+0
duckduckgo.com
1
get
doc
https://duckduckgo.com/chrome_newtab
```
```
+0
https://duckduckgo.com/chrome_newtab
```
</details>
