### ISSUE TITLE
Breakage - habitburger.com

### ISSUE THREAD

**Issue by TraceGroot** [uBlockOrigin/uAssets#22505]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.habitburger.com/contact-us/feedback/
```

### Description

There is a checkbox that is supposed to be at the bottom of the form (right above the Submit button) where you agree to their privacy policy and terms.  If uBlock is enabled, that checkbox is not displayed and the form is impossible to submit.

If you turn off uBlock for that site and refresh, then it shows up.

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.54.0
Firefox: 119
filterset (summary):
 network: 214987
 cosmetic: 247391
 scriptlet: 50084
 html: 2335
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77079-7253, 4d.14h.52m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96807-32976, 6d.19h.5m
  ublock-annoyances: 6678-11, 51m
  adguard-generic: 82639-7218, 4d.14h.51m
  adguard-mobile: 9054-102, 4d.14h.51m
  adguard-social: 22134-749, 4d.14h.51m
  fanboy-social: 16138-2, 1d.17h.47m
  adguard-spyware-url: 1440-106, 4d.14h.52m
  adguard-spyware: 94460-32765, 4d.14h.52m
 default:
  user-filters: 381-4, never
  ublock-filters: 37809-184, 51m
  ublock-badware: 7890-14, 51m
  ublock-privacy: 859-0, 51m
  ublock-unbreak: 2259-1, 51m
  easylist: 81007-728, 51m
  easyprivacy: 50205-982, 51m
  plowe-0: 3784-1, 11d.20h.19m
  urlhaus-1: 7480-0, 7h.46m
  ublock-quick-fixes: 119-0, 51m
filterset (user): [array of 381 redacted]
trustedset:
 added: [array of 97 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 8 redacted]
hostRuleset:
 added: [array of 90 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 535 ms (selfie)
 maxAssetCacheWait: 292 ms
popupPanel:
 blocked: 3
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  typekit.net: 1
 extended:
  ##.social_row
  ##.consent_box
  ###footer_social

```
</details>

**Comment by gorhill** [comment]
Broken by `##.consent_box` in "EasyList – Cookie Notices".

cc @ryanbr

**Comment by TraceGroot** [comment]
I don't have "EasyList – Cookie Notices" enabled.  

Is there any chance that a different list is also responsible?

**Comment by gorhill** [comment]
> Is there any chance that a different list is also responsible?

You imported this list: `https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt` -- it contains "Easylist -- Cookie Notices".

**Comment by TraceGroot** [comment]
Ah!  Thank you for clarifying.
