### ISSUE TITLE
dailymotion.com: ads

### ISSUE THREAD

**Issue by deckrd** [uBlockOrigin/uAssets#22506]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dailymotion.com/video/x8h1hzh`

### Category

ads

### Description

ads

### Other extensions used

0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 122859
 cosmetic: 45505
 scriptlet: 20347
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81007-14, 5m Δ
  easyprivacy: 50205-38, 5m Δ
  plowe-0: 3784-1184, never
  ublock-badware: 7886-141, 5m Δ
  ublock-filters: 37270-351, 5m Δ
  ublock-privacy: 865-6, 5m Δ
  ublock-quick-fixes: 128-6, 5m Δ
  ublock-unbreak: 2211-32, 5m Δ
  urlhaus-1: 7275-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 494 ms (selfie)
 maxAssetCacheWait: 219 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##div[class^="DisplayAd"]
  ##div[class^="NewWatchingDiscovery__adSection"]
```
</details>

**Comment by gorhill** [comment]
>    blocked: 0

That is not normal, I get ~30 blocked network requests when navigation to `https://www.dailymotion.com/video/x8h1hzh`.

Which exact browser/version is this?

**Comment by ButterVsMargarine** [comment]
@deckrd Is an account needed to get ads? Please disable brave's ad blocker on the site if you are using it
![image](https://github.com/uBlockOrigin/uAssets/assets/159081099/4ba23101-5ce7-4097-afbd-e8c66fdad14f)
