### ISSUE TITLE
tiktokcounter.net: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#22512]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokcounter.net/tech/the-best-marketing-platforms-for-your-website/`

### Category

detection

### Description

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&usg=AOvVaw2kcdrI4i5dKsq-SoGMPTvT&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjijLPUseH1AhVFwAIHHcieC5IQFnoECAQQAQ&url=https://tiktokcounter.net/tech/?url8j=https://ctr.sh/OWwcuyn5q1q

### Other extensions used

nine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 120
filterset (summary):
 network: 124937
 cosmetic: 37155
 scriptlet: 20549
 html: 0
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 default:
  user-filters: 76-0, never
  adguard-mobile: 9202-47, 3m
  easylist: 81259-15993, 3m
  easyprivacy: 50216-48, 3m
  plowe-0: 3783-1259, 3m
  ublock-badware: 7880-143, 3m
  ublock-filters: 37627-640, 3m
  ublock-privacy: 870-7, 3m
  ublock-quick-fixes: 129-6, 3m
  ublock-unbreak: 2216-35, 3m
  urlhaus-1: 7710-0, 3m
filterset (user): [array of 39 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4920 ms (selfie)
 maxAssetCacheWait: 671 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  tiktokcounter.net: 1
  googlesyndication.com: 1
  profitsfly.com: 1
 extended:
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(abort-on-property-read, adbDetected)
```
</details>

**Comment by ItsProfessional** [comment]
#17361

**Comment by adhip94** [comment]
@ItsProfessional If i open the link posted in the description it detects ublock and increases the timer. Is there any way to disable the ad-block detection? Is it possible to remove the timer?

**Comment by Fatcavill** [comment]
adblock detect on this site help

**Comment by rpodric** [comment]
It's unclear to me what the upshot of this, if there is one.

One post above points to ubo-link-shorteners.txt, which is fine but seems to have no affect for this. Aside from that and the default filters, is there anything else?

**Comment by ItsProfessional** [comment]
continue in https://github.com/uBlockOrigin/uAssets/discussions/17361
