### ISSUE TITLE
cmteb.ro: breakage

### ISSUE THREAD

**Issue by Coosminn** [uBlockOrigin/uAssets#22518]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cmteb.ro/functionare_sistem_termoficare.php`

### Category

breakage

### Description

i cant press any of the buttons on the site, the map (harta) or the district (sector).

### Other extensions used

none.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 337541
 cosmetic: 248037
 scriptlet: 50137
 html: 2332
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80982-817, now
  adguard-mobile: 9091-20, now
  adguard-spyware-url: 1447-106, now
  adguard-spyware: 100352-33715, now
  block-lan: 56-0, now
  curben-phishing: 105246-33, now
  adguard-social: 22165-854, now
  adguard-cookies: 28778-66, now
  ublock-cookies-adguard: 940-0, now
  adguard-popup-overlays: 26972-1686, now
  adguard-mobile-app-banners: 5038-1078, now
  adguard-other-annoyances: 14194-335, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37807-3699, now
  ublock-badware: 7890-14, now
  ublock-privacy: 734-0, now
  ublock-unbreak: 2259-1, now
  ublock-quick-fixes: 123-0, now
  easylist: 81260-2273, now
  easyprivacy: 50217-1211, now
  urlhaus-1: 7800-0, now
  plowe-0: 3782-84, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 726 ms (selfie)
 maxAssetCacheWait: 439 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.modal
  ##body,html:style(overflow: auto !important; position: initial !…
```
</details>

**Comment by D4niloMR** [comment]
Add:

`cmteb.ro##.modal-backdrop`

**Comment by ButterVsMargarine** [comment]
```
cmteb.ro##+js(acs, $, .modal)
```
@ryanbr

**Comment by gorhill** [comment]
I don't see anything which needs fixing with default lists or default lists + "EasyList/uBO – Cookie Notices".

With default lists, the `.modal-backdrop` element and related warning disappear if I click anywhere on the page.

With default lists + "EasyList/uBO – Cookie Notices", the page renders fine with no issue.

**Comment by ButterVsMargarine** [comment]
@gorhill with EasyList + uBO annoyances => href elements are not clickable

**Comment by gorhill** [comment]
> with EasyList + uBO annoyances => href elements are not clickable

You're right, I had tested the top buttons only.

Indeed, this is needed:

    cmteb.ro##.modal-backdrop
