### ISSUE TITLE
weather.com: breakage

### ISSUE THREAD

**Issue by Evoden1** [uBlockOrigin/uAssets#22516]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://weather.com/weather/today/l/a496cfcba367ffae60ccfdc94e31bcf3d0a12ac6515336dbd274f381a932abbc
https://weather.com/weather/hourbyhour/l/a496cfcba367ffae60ccfdc94e31bcf3d0a12ac6515336dbd274f381a932abbc
```

### Description

I tried using a fresh Firefox profile without any extensions, and it worked perfectly with the default filters. However, as soon as I enabled **EasyList - Cookie Notices**, **the page began to repeatedly refresh over and over nonstop**.

It will happen if you try switching from the hourly weather page to the today weather page or vice versa.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-16 184749](https://github.com/uBlockOrigin/uAssets/assets/95939609/8d227593-2c21-401a-b1a9-88573c83f302)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 123
filterset (summary):
 network: 195837
 cosmetic: 120716
 scriptlet: 28918
 html: 2332
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1447-107, 21m
  adguard-spyware: 100352-32552, 9m
  adguard-cookies: 28778-51, 21m
  ublock-cookies-adguard: 940-0, 21m
  fanboy-cookiemonster: 66066-19762, 21m
  easylist-newsletters: 6982-4, 21m
  ublock-annoyances: 6684-957, 20m
 default:
  user-filters: 0-0, never
  ublock-filters: 37807-118, 21m
  ublock-badware: 7890-14, 21m Δ
  ublock-privacy: 695-0, 21m
  ublock-unbreak: 2259-0, 21m
  ublock-quick-fixes: 123-0, 21m
  easylist: 81260-666, 21m
  easyprivacy: 50217-883, 21m
  urlhaus-1: 7800-0, 21m
  plowe-0: 3782-1, 21m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 198 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
```
</details>

**Comment by D4niloMR** [comment]
I can reproduce it, only easylist cookies and cleaned cookies at first visit.

Caused by `weather.com##+js(set-cookie, __adblocker, false, , reload, 1)` it eventually stops, now, I don't know why this is happening.

Add:

`weather.com#@#+js(set-cookie, __adblocker, false, , reload, 1`

**Comment by gorhill** [comment]
I am not able to reproduce "repeatedly refresh over and over nonstop" when using "Easylist/uBO -- Cookie Notices".

**Comment by ryanbr** [comment]
weather.com is checking for GPC, which affected Brave and Firefox. Brave implemented a fix to get around it

https://github.com/brave/adblock-lists/pull/1488

Is this what the user is seeing? @Evoden1

**Comment by CatBoi-Finnbjorn** [comment]
Had the same problem, ryanbr's fix worked for me by adding to myfilter's list
