### ISSUE TITLE
aiimgvlog.fun: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#22513]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aiimgvlog.fun/index.php/2023/09/01/ai-image-technology-unlocking-the-potential-of-artificial-intelligence-in-image-processing/`

### Category

detection

### Description

`https://aiimgvlog.fun/index.php/2023/09/01/ai-image-technology-unlocking-the-potential-of-artificial-intelligence-in-image-processing/`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 120
filterset (summary):
 network: 124937
 cosmetic: 37155
 scriptlet: 20549
 html: 0
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 default:
  user-filters: 76-0, never
  adguard-mobile: 9202-47, 11m
  easylist: 81259-15993, 11m
  easyprivacy: 50216-48, 11m
  plowe-0: 3783-1259, 11m
  ublock-badware: 7880-143, 11m
  ublock-filters: 37627-640, 11m
  ublock-privacy: 870-7, 11m
  ublock-quick-fixes: 129-6, 11m
  ublock-unbreak: 2216-35, 11m
  urlhaus-1: 7710-0, 10m
filterset (user): [array of 39 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4920 ms (selfie)
 maxAssetCacheWait: 671 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 31
 network:
  aiimgvlog.fun: 12
  blog24.me: 1
  bmcdn6.com: 1
  btc25.org: 1
  cryptocoinsad.com: 4
  doge25.in: 1
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  ltc25.in: 1
  profitsfly.com: 1
  quiziizz.github.io: 1
  waust.at: 1
  wpadmngr.com: 1
  wtg-ads.com: 1
 extended:
  ##+js(addEventListener-defuser, , popMagic)
  ##+js(no-xhr-if, popunder)
  ##+js(abort-current-script, eval, replace)
  ##+js(abort-current-script, addEventListener, google_ad_client)
  ##+js(abort-on-property-write, AdbModel)
  ##+js(set-constant, protection, noopFunc)
  ##+js(set-constant, document.hasFocus, trueFunc)
  ##+js(remove-node-text, script, /ad\s?block|adsBlocked|document\…
```
</details>

**Comment by ItsProfessional** [comment]
> `filterset (user): [array of 39 redacted]`

You are using a highly customized configuration of uBO. We can't help such users. Reset uBO to defaults

> ```yaml
>removed:
>  IDN-0: null

Don't disable regional lists.

**Comment by mapx-** [comment]
maybe it's about some shortener crap, report at #17361 provoding the original link
