### ISSUE TITLE
Daringfireball.net

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#2251]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://daringfireball.net/`

### Describe the issue

Adblock bypass.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: FF/59
- uBlock Origin version: 1.16.4

### Settings

Default

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by zaphodbeebblebrox** [comment]
That is all I get as well.

**Comment by ReyCobin** [comment]
@gorhill Please look into this. uBO is not supposed to allow any ads.

**Comment by uBlock-user** [comment]
Post screenshots, I can't reproduce any ads either.

**Comment by gorhill** [comment]
If other can't reproduce ads, you will have to scan your system for adware or investigate your other extensions.

**Comment by gorhill** [comment]
> `daringfireball.net###SidebarMartini`

If that is the ad in question, this can be added to EasyList. @ryanbr
