### ISSUE TITLE
readcomiconline.li: detection

### ISSUE THREAD

**Issue by Jimbo-Tacoz** [uBlockOrigin/uAssets#22525]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://readcomiconline.li/Comic/New-Avengers-2010/Issue-7?id=3193&s=s2`

### Category

detection

### Description

readcomiconline.li blocks issues from loading with the following error:

> Please disable adblock or this issue is broken, it'll be fixed automatically. Please try again in next 5 mins

When attempting to load issues, the url updates to include &s=s2 at the end.

### Other extensions used

AHA Music - Song Finder
Stream Cleaner
ChatReplay
Return YouTube Dislike
YCS - YouTube Comment Search
Youtube-shorts block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2024-02-16 at 6 40 53 PM](https://github.com/uBlockOrigin/uAssets/assets/160301936/6258f4bf-1306-4c86-96a4-746e34164666)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 116
filterset (summary):
 network: 123730
 cosmetic: 45528
 scriptlet: 20210
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81266-14, 1h.43m
  easyprivacy: 50217-6, 41m Δ
  plowe-0: 3782-1185, 1h.43m
  ublock-badware: 7885-142, 1h.43m
  ublock-filters: 37259-356, 1h.43m
  ublock-privacy: 738-6, 1h.43m
  ublock-quick-fixes: 130-6, 1h.43m
  ublock-unbreak: 2212-32, 1h.43m
  urlhaus-1: 7875-0, 1h.43m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3448 ms
 maxAssetCacheWait: 95 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  readcomiconline.li: 4
  bidgear.com: 1
  google-analytics.com: 1
  hagweedtoytown.com: 1
  sharethis.com: 1
 extended:
  ##.divCloseBut
  ##div[style*="width: 300px"]
  ##+js(abort-on-property-read, adblockDetector)
  ##+js(addEventListener-defuser, mousedown, localStorage)
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by mapx-** [comment]
> Chromium: 116

chrome or some other chromium browser ?

**Comment by gorhill** [comment]
> attempting to load issues

What does that mean? `&s=s2` happens when selecting "Server 2".
