### ISSUE TITLE
511tactical.com: breakage

### ISSUE THREAD

**Issue by BrightApollo** [uBlockOrigin/uAssets#22522]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.511tactical.com/xprt-collection.html
```

### Description

the navigation banner that offers choices of men, women, bags, etc is occluded by other text

### Other extensions used

none active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/10965669/444b03c5-9ae8-4080-9e2c-e9c2b8d4043f)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 123125
 cosmetic: 45447
 scriptlet: 19076
 html: 2092
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37786-140, 4d.13m
  ublock-badware: 7865-14, 2d.34m Δ
  ublock-privacy: 971-0, 2d.34m Δ
  ublock-unbreak: 2259-0, 2d.34m Δ
  ublock-quick-fixes: 113-0, 2d.34m Δ
  easylist: 81072-651, 2d.34m Δ
  easyprivacy: 50196-832, 2d.34m Δ
  urlhaus-1: 7485-0, 2d.34m
  plowe-0: 3782-1, 4d.12m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 353 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 no-remote-fonts: true
 network:
  github.com: 9

```
</details>

**Comment by D4niloMR** [comment]
Did you test with uBlock Origin disabled?

**Comment by mapx-** [comment]
> no-remote-fonts: true

You enabled `Block remote fonts`

disable it
