### ISSUE TITLE
cdn.paddle.com: breakage

### ISSUE THREAD

**Issue by fbelzile** [uBlockOrigin/uAssets#22521]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://getcoldturkey.com/pricing/
```

### Description

Error (error code: E-403) with Paddle Checkout when clicking the "Purchase" button. Web Inspector shows the following URL blocked by uBlock Origin:
**https://cdn.paddle.com/paddle/assets/images/health-check.gif?_=1708103507283**

Paddle Checkout works properly once uBlock Origin is disabled. This is potentially a wider reaching issue that may affect all online stores that use Paddle Checkout.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 125393
 cosmetic: 89780
 scriptlet: 22739
 html: 2078
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50140-129, 30m
 default:
  user-filters: 5-0, never
  ublock-filters: 37807-153, 1h.58m Δ
  ublock-badware: 7890-14, 1h.58m Δ
  ublock-privacy: 695-0, 1h.58m Δ
  ublock-unbreak: 2259-0, 1h.58m Δ
  ublock-quick-fixes: 123-0, 1h.58m Δ
  easylist: 81260-658, 1h.58m Δ
  easyprivacy: 50217-882, 1h.58m Δ
  urlhaus-1: 7800-0, 30m
  plowe-0: 3782-1, 30m
filterset (user): [array of 5 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 952936 ms (selfie)
 maxAssetCacheWait: 2755 ms
 cacheBackend: indexedDB
```
</details>

**Comment by fbelzile** [comment]
Paddle just updated their status page and may possibly fix the breakage themselves:
https://paddle.status.io/

**Comment by mapx-** [comment]
@Yuki2718 https://github.com/easylist/easylist/pull/18562

**Comment by mapx-** [comment]
@ryanbr
