### ISSUE TITLE
10bitclub.tech: Detection

### ISSUE THREAD

**Issue by symentium** [uBlockOrigin/uAssets#22527]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://10bitclub.tech/`

### Category

detection

### Description

While surfing to any page in the website, an overlay pops up saying 'It looks like you've adblocker enabled'. It can closed at the top right corner.

### Other extensions used

Clear URLs
Dark Reader
I still don't care about cookies
Local CDN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 361135
 cosmetic: 311552
 scriptlet: 52520
 html: 2370
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 1062-7, now
  https://filters.adtidy.org/windows/filters/17.txt: 1446-5, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1054-1, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 406-3, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 728-80, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2565-188, now
  https://raw.githubusercontent.com/hant0508/uBlock-filters/master/filters.txt: 1462-2, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1939-13, now
  https://raw.githubusercontent.com/stephenhawk8054/PrivacyExtended/main/privacy_extended.txt: 17431-114, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, now
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42453-1395, 1m
  [22 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38163-570, now
  ublock-badware: 7884-14, now
  ublock-privacy: 734-113, now
  ublock-unbreak: 2265-1, now
  ublock-quick-fixes: 123-0, now
  adguard-mobile: 9090-114, now
  easylist: 81022-1051, now
  easyprivacy: 50221-6350, now
  urlhaus-1: 7875-0, now
  plowe-0: 3782-2, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1260 ms (selfie)
 maxAssetCacheWait: 757 ms
 cacheBackend: indexedDB
 unsuspendAfter: 259 ms
popupPanel:
 blocked: 5
 network:
  10bitclub.tech: 3
  doubleclick.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
too many lists: reset uBO to default settings / filter lists, test again

**Comment by ItsProfessional** [comment]
If you still get detected after resetting uBO and removing all other extensions, comment here.

**Comment by symentium** [comment]
OK, the the reset version on filter lists do not trigger the adblock detection. Is it any way to find which one triggers it other than trial and error?

**Comment by mapx-** [comment]
no: you have to disable 1 by 1 the not-default lists and you'll find out which is the "bad" one
