### ISSUE TITLE
visionpapers.org: detection

### ISSUE THREAD

**Issue by sujitfg1** [uBlockOrigin/uAssets#22529]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://visionpapers.org/gmdownload/12th-maths-vraj-paperset-2024-gm/`

### Category

breakage

### Description

Whenever we click on Fetch File Site it broke site after 2-3 seconds and after disabling uBo it works fine. You can check by yourself using Link

Thankyou 

### Other extensions used

FontNinja

That's all 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240217_142317](https://github.com/uBlockOrigin/uAssets/assets/105970492/352cca84-1d67-4ec6-ac38-6a0e9b806ca1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 120
filterset (summary):
 network: 125129
 cosmetic: 37148
 scriptlet: 20273
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  adguard-mobile: 9090-47, now
  easylist: 81266-15998, 1h.23m Δ
  easyprivacy: 50220-16, 1h.23m Δ
  plowe-0: 3782-1261, now
  ublock-badware: 7879-143, 1h.23m Δ
  ublock-filters: 37613-602, 1h.23m Δ
  ublock-privacy: 738-7, 1h.23m Δ
  ublock-quick-fixes: 130-6, 1h.23m Δ
  ublock-unbreak: 2217-35, 1h.23m Δ
  urlhaus-1: 7875-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4336 ms (selfie)
 maxAssetCacheWait: 517 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  adxfire.net: 1
  googletagmanager.com: 1
 extended:
  ##.popup
  ##.popup-container
```
</details>

**Comment by sujitfg1** [comment]
How to add This Filters 2024?

**Comment by ItsProfessional** [comment]
You don't have to. Just update your filter lists.

**Comment by sujitfg1** [comment]
Thankyou i updated and now getting this :⁠,⁠-⁠)

![Screenshot_20240217_161009](https://github.com/uBlockOrigin/uAssets/assets/105970492/c39c76a9-41d5-4c73-b7c6-57f48ec2396b)
Still ad block detention

![Screenshot_2024_0217_161048](https://github.com/uBlockOrigin/uAssets/assets/105970492/33983ed8-817b-4dda-aeee-c4a12c90b30a)
Every filter is up to date

**Comment by ItsProfessional** [comment]
It's working fine for me. Try turning off "Ignore generic cosmetic filters"

**Comment by sujitfg1** [comment]
>Try turning off "Ignore generic cosmetic filters".

Thanks now it working. Could you tell me how Cosmetic filters was Affecting Page?

**Comment by ItsProfessional** [comment]
It's because that option is automatically disabled on mobile to increase performance on some low end devices, by disabling generic filters. If enabling it works, keep it enabled.
