### ISSUE TITLE
New cookie popups at various Norwegian sites

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#22533]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.dagsavisen.no/
https://www.digi.no/
https://www.tu.no/
https://www.vl.no/
```

### Issue:
New cookie popups at various Norwegian sites.

### Possible fix:
`/wrapperMessagingWithoutDetection.js$domain=dagsavisen.no|digi.no|tu.no|vl.no`

@Yuki2718: Like the ones that you added here: https://github.com/DandelionSprout/adfilt/discussions/932#discussioncomment-8264980

### Note:
Unlike the popups at some Schibsted sites (https://github.com/uBlockOrigin/uAssets/issues/22295/), blocking them with a network rule doesn't appear to break anything, but this might need to be further investigated.

@DandelionSprout: What do you think?

### Other extensions used

none

### Configuration

* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v122.0-2 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.55.0

**Comment by krystian3w** [comment]
IMO for ELC, fyi @Nojuuu / @peace2000

**Comment by Nojuuu** [comment]
If it doesn't need trusted filters it can probably be handled in ELC

**Comment by peace2000** [comment]
Blocking `wrapperMessagingWithoutDetection.js` seems fine to me. Videos work and so do twitter embeds. These two things are the most common thing to break, if something is going to break.

Sample links:
`https://www.vl.no/religion/2024/02/12/kvinnelig-gjerningsperson-skutt-etter-skyting-i-megakirke-i-texas-to-saret/`
`https://www.tu.no/video/digi-forklarer-nodvarsling-pa-mobil/2142`
`https://www.tu.no/artikler/samlet-inn-over-3-85-millioner-kroner-ble-suspendert-av-kickstarter/223165`
`https://www.digi.no/artikler/teslas-nye-robot-kan-bli-et-av-selskapets-viktigste-produkter/541307`
`https://www.digi.no/artikler/eu-strever-med-a-enes-om-banebrytende-ki-regler/540835`
`https://www.dagsavisen.no/video/2024/01/27/anders-gjose/`

**Comment by ryanbr** [comment]
`/wrapperMessagingWithoutDetection.js$domain=dagsavisen.no|digi.no|tu.no|vl.no` so this works with no breakages?

**Comment by peace2000** [comment]
@ryanbr Yeah, at least I didn't notice issues.

**Comment by THEtomaso** [comment]
Here are four more sites, which features `/wrapperMessagingWithoutDetection.js`:
```
https://www.friflyt.no/
https://www.friflytbestill.no/
https://www.norsk-klatring.no/
https://www.utemagasinet.no/
```

**Comment by THEtomaso** [comment]
@ryanbr / @Yuki2718:

/wrapperMessagingWithoutDetection.js @
```
dolen.no
driva.no
fjordabladet.no
fjordingen.no
fjt.no
fjuken.no
fosna-folket.no
morenytt.no
nyss.no
rbnett.no
smp.no
vestlandsnytt.no
vigga.no
vikebladet.no
```

**Comment by THEtomaso** [comment]
Another one:
`https://www.jeger.no/`

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/f1cf998b99a769fdd2c121587c054e17f4357bc9
https://github.com/AdguardTeam/AdguardFilters/commit/12be075ced8d604eb3f69e36a04736397f5d2134

**Comment by THEtomaso** [comment]
```
hintaopas.fi
prisjagt.dk
prisjakt.no
prisjakt.nu
```

**Comment by THEtomaso** [comment]
@Yuki2718:
You awake? :)

**Comment by Yuki2718** [comment]
I was DoS-ed by notification at the time.

**Comment by THEtomaso** [comment]
FYI; '**EasyList - Cookie Notices**' still lacks `/wrapperMessagingWithoutDetection.js` for `prisjakt.nu`.

Also, this rule..
`hintaopas.fi,ledenicheur.fr,prisjagt.dk,prisjakt.no,prisjakt.nu,pricespy.co.uk,pricespy.co.nz##+js(set-cookie, privacy_settings, 1)`
..should be modified to this now:
`ledenicheur.fr,pricespy.co.uk,pricespy.co.nz##+js(set-cookie, privacy_settings, 1)`

**Comment by Yuki2718** [comment]
Will do tonight.

**Comment by THEtomaso** [comment]
### Issue:
There's a new GDPR banner on various Aller Media sites.

### Affected sites:
```
https://www.dagbladet.no/
https://www.elbil24.no/
https://www.kk.no/
https://www.seher.no/
https://sol.no/
```

### Screenshot:
![filterissue-allermedia](https://github.com/uBlockOrigin/uAssets/assets/9382674/33a77777-2494-4a5a-b6d3-5aa4be2cabba)

### Note:
The banner only appears on first load.

### Possible fix:
`dagbladet.no,elbil24.no,kk.no,seher.no,sol.no###am-branding`

**Comment by Yuki2718** [comment]
Can `###am-branding` be generic?

**Comment by THEtomaso** [comment]
Probably, but there really aren't that many Aller Media sites, so it would be a bit overkill.

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `andalsnes-avis.no`

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `kvinneguiden.no`

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `klikk.no`

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `lister24.no`

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `varden.no`

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `aesby.no`

**Comment by THEtomaso** [comment]
There's a cookie popup @ `bestdrive.no`.
The Finnish domain (`bestdrive.fi`) has it too.
Don't know what would the best approach in this case though.

**Comment by THEtomaso** [comment]
**Issue:**
Another cookie popup at these domains;
```
giffits.be
giffits.dk
giffits.es
giffits.fr
giffits.it
giffits.no
giffits.pl
giffits.se
giffits-articles-publicitaires.ch
```
..whilst these domains are already handled by '**EasyList - Cookie Notices**':
```
giffits.de
giffits-werbeartikel.at
giffits-werbeartikel.ch
```
**Possible fix:**
```
giffits.*,giffits-articles-publicitaires.ch##.body__wrapper > div.overlay
giffits.*,giffits-articles-publicitaires.ch##.cookie_opt_in
```

**Comment by peace2000** [comment]
> There's a cookie popup @ `bestdrive.no`. The Finnish domain (`bestdrive.fi`) has it too. Don't know what would the best approach in this case though.

https://github.com/uBlockOrigin/uAssets/commit/7eb78d01c29646501ba02d2ec8829487a2575115

@THEtomaso

**Comment by peace2000** [comment]
Now let's wait for EL authors to accept my PR for `giffits` domains.

**Comment by THEtomaso** [comment]
Wow, good work with that BestDrive rule, peace2000! :)

**Comment by Yuki2718** [comment]
Ooops, missed the PR. But I didn't see cookie popup on `giffits-werbeartikel.at` or `giffits-werbeartikel.ch`

**Comment by Yuki2718** [comment]
> Beacause '**EasyList - Cookie Notices**' already blocked it at those domains, like I pointed out.

I overlooked that...

**Comment by THEtomaso** [comment]
`https://onsk.no/` and `https://www.penger.no/`:
Simply `onsk.no,penger.no##.bottom-0` ?

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `venneslatidende.no`

**PS:** Also check out my previous post!

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ `helthjem.no`

**Comment by THEtomaso** [comment]
@ `detskjer.rbnett.no`:
`##[tabindex="0"]` ?

**Comment by THEtomaso** [comment]
`/wrapperMessagingWithoutDetection.js` @ the following sites:
```
agderposten.no
avisafroya.no
banett.no
bomlo-nytt.no
fitjarposten.no
fvn.no
gauldalsposten.no
kulingen.no
kystogfjord.no
l-a.no
lp.no
marsteinen.no
mn24.no
morgenbladet.no
opp.no
oyposten.no
porten.no
randaberg24.no
s-n.no
steinkjer24.no
stord24.no
sunnhordland.no
vaganavisa.no
```

**Comment by THEtomaso** [comment]
@Yuki2718: :point_up_2:

**Comment by D4niloMR** [comment]
You can also report at https://github.com/easylist/easylist and https://github.com/AdguardTeam/AdguardFilters

**Comment by Yuki2718** [comment]
I'm aware of them, just not having time. Anyone is welcome to open PR or issues so other members having time can review and merge.

**Comment by THEtomaso** [comment]
That's OK.
I'm sure someone will find time, sooner or later. :)

**Comment by THEtomaso** [comment]
@ `oda.com`:
`##[class^="styles_cookie-widget-wrapper"]`

**Comment by THEtomaso** [comment]
Can someone please reverse this terrible change?:
https://github.com/uBlockOrigin/uAssets/pull/26776/
https://github.com/uBlockOrigin/uAssets/commit/72ea3fce732f8c89acd47e064d7f6a671fa55769/
The old rules worked just fine with uBO!
Perhaps ryanbr was testing them with ABP, or something?
The worst thing is that it now automatically accepts all of the cookie rules, instead of denying them!!

**Comment by THEtomaso** [comment]
Can someone please reverse this terrible commit, which now automatically accepts all cookie terms at `e24.no` and `vg.no`, instead of denying them!?:
https://github.com/uBlockOrigin/uAssets/pull/26776/
https://github.com/uBlockOrigin/uAssets/commit/72ea3fce732f8c89acd47e064d7f6a671fa55769/

The previous fix simply required a small adjustment!
This rule:
`cmp.e24.no,cmp.vg.no##+js(trusted-click-element, .btns-container > button[title="Tilpass"])`
..needed to be change into this:
`cmp.e24.no,cmp.vg.no##+js(trusted-click-element, .btns-container > button[title="Tilpass cookies"])`

**Comment by THEtomaso** [comment]
**`/wrapperMessagingWithoutDetection.js`** at the following site(s):
```
klebuposten.no
nearadio.no
ringsaker-blad.no
setesdolen.no
```

**Comment by THEtomaso** [comment]
At `viivilla.no`..

~~this seems to work:
`viivilla.no##.didomi-host`
`viivilla.no##+js(trusted-click-element, .didomi-popup-notice button[id="didomi-notice-learn-more-button"])`
`viivilla.no##+js(trusted-click-element, .didomi-consent-popup-preferences-purposes button[id="btn-toggle-disagree"], , 1000)`
..but there might be a simpler solution?~~

--

**EDIT:**
I've now posted a much simpler solution here:
https://github.com/AdguardTeam/AdguardFilters/issues/207728#issuecomment-3172324590
:)

**Comment by THEtomaso** [comment]
At `itavisen.no`:

Screenshot:
https://github.com/user-attachments/assets/460480f4-4437-4a59-97dc-0a465f71eb48

Possible fix:
```
itavisen.no##.qc-cmp2-container
itavisen.no##+js(trusted-click-element, [id="qc-cmp2-ui"] [mode="secondary"], , 2000)
itavisen.no##+js(trusted-click-element, [id="qc-cmp2-ui"] button[class*="css-"]:nth-of-type(1), , 3000)
```

**Comment by THEtomaso** [comment]
At `https://www.vpg.no/`:
`||vpg.no^*.cookie-$script`
