### ISSUE TITLE
yoomoney.ru: ads, privacy

### ISSUE THREAD

**Issue by ekeew** [uBlockOrigin/uAssets#22538]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://yoomoney.ru/checkout/payments/v2/success
```

### Description

In Succes page `https://yoomoney.ru/checkout/payments/v2/success` Yoomoney uploads advertising through the request of `https://yoomoney.ru/offerwall/ajax/getRecommendations`.
Advertising banners' URLs begin with `https://yoomoney.ru/promo/offer/<banner_id>`.
Then it saves your statistics at `https://yoomoney.ru/offerwall/ajax/statistics/save`.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/87432927/e7cdab9d-a471-44b0-9857-ef8138dbaa16)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 123745
 cosmetic: 45534
 scriptlet: 18889
 html: 2080
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37830-116, 1h.11m Δ
  ublock-badware: 7895-14, 1h.11m Δ
  ublock-privacy: 736-0, 1h.11m Δ
  ublock-unbreak: 2260-0, 1h.11m Δ
  ublock-quick-fixes: 129-0, 1h.11m Δ
  easylist: 81272-624, 1h.11m Δ
  easyprivacy: 50221-861, 1h.11m Δ
  urlhaus-1: 7890-0, 1h.11m
  plowe-0: 3782-1, 4d.1h.27m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 504 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  yoomoney.ru: 2
  google-analytics.com: 1
  yandex.ru: 2
```
</details>

**Comment by krystian3w** [comment]
Try enable RU AdList?

https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

Due I see disabled in config log.

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This can be discussed here: https://github.com/easylist/ruadlist/issues
