### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#2253]
### URL(s) where the issue occurs

`https://www.reddit.com/r/waterfox/`

### Describe the issue
Advertisement leftovers from the right side.

### Screenshot(s)

![screenshot_20180512_090001](https://user-images.githubusercontent.com/19818572/39954707-c2e9d67e-55c3-11e8-9726-58be3b64472d.png)

### Versions

- Browser/version: Waterfox 56.1.0
- uBlock Origin version: 1.16.4

### Settings

- `https://gist.github.com/hawkeye116477/c19a440599c62cf50dd8f200c2030627`

**Comment by zaphodbeebblebrox** [comment]
```
reddit.com##div:has(:scope > div > [id^="sidebar-atf-"])
reddit.com##div:has(:scope > div > [id^="sidebar-btf-"])
```
New reddit is changing a lot, so I thought it would be better to do it without referencing procedurally generated names that change frequently.

**Comment by mapx-** [comment]
`reddit.com##.vuIDB`

**Comment by hawkeye116477** [comment]
@zaphodbeebblebrox This helps on main https://www.reddit.com/r/waterfox/, but ads leftovers are also on specific topics like this `https://www.reddit.com/r/waterfox/comments/8ipw0q/corruptwrong_favicon_for_shortcut/`, which this doesn't work. 
However @mapx- rule works perfectly for me :smile:.

**Comment by krystian3w** [comment]
Ajax iframes...

**Comment by tendererdegree** [comment]
This issue has popped up again for me for a while.

reddit.com##.vuIDB

The above code shows the placeholder frame as of now

I propose we replace it with the following

reddit.com##.ii4q9d-0:has(.s9i6gcs-1)

This hides the parent frame and fixes uneven padding

**Comment by krystian3w** [comment]
`##div[id*="sidebar"][data-before-content="advertisement"]:nth-ancestor(4)`

**Comment by gwarser** [comment]
Updated r. https://www.reddit.com/r/uBlockOrigin/comments/gntsm0/home_menu_bug_bug/fre199z/

**Comment by krystian3w** [comment]
That still has to be updated in the `Nano - Placeholder buster` used similar syntax - NanoMeow still no added issue into `quick-report`.
