### ISSUE TITLE
notizie.tiscali.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#22537]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://notizie.tiscali.it/feeds/lavoro-gen-z-non-teme-part-time-differenza-dei-millennials/`

### Category

nuisance

### Description

Suggested solution: add `tiscali.it` to
```
##+js(trusted-click-element, 'button.iubenda-cs-customize-btn, button.iub-cmp-reject-btn, button#iubFooterBtn')
##html[style="overflow: hidden;"]:style(overflow: auto !important)
##[id|="iubenda"]
```

If you hide the banner, audio doesn't load:

<details>
<img width="749" src="https://github.com/AdguardTeam/AdguardFilters/assets/1375223/874d61c8-1175-48c1-928f-caf489673303">
</details>

Rejecting cookies:

<details>
<img width="773" src="https://github.com/AdguardTeam/AdguardFilters/assets/1375223/30a7b522-8f08-4b47-b932-d3a8add790f8">
</details>

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1118" alt="j" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/ce0f800a-e9a8-410f-8fa3-1e07877890a9">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 120
filterset (summary):
 network: 116765
 cosmetic: 128796
 scriptlet: 9402
 html: 255
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
 added:
  adguard-social: 22171-134, 5m
  adguard-cookies: 28791-43, 5m
  ublock-cookies-adguard: 941-0, 5m
  adguard-popup-overlays: 26974-910, 5m
  adguard-mobile-app-banners: 5039-7, 5m
  adguard-other-annoyances: 14198-8, 5m
  adguard-widgets: 2440-1, 5m
  ublock-annoyances: 6689-1009, 5m
  ITA-0: 8305-23, 6m
 default:
  user-filters: 0-0, never
  easylist: 81272-459, 6m Δ
  easyprivacy: 50221-899, 6m Δ
  urlhaus-1: 7890-0, 6m
  plowe-0: 3782-0, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 775 ms
 maxAssetCacheWait: 463 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  tiscali.it: 2
  acsbapp.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  iubenda.com: 1
  unblockia.com: 1
  webtrekk.net: 1
  wt-safetag.com: 1
 extended:
  ###adwallpaper
  ##.share-box
  ###admputop2
  ###admpumiddle2
  ###admputop
  ###admpumiddle
  ###admpubottom
  ###admpubottom2
  ###fb-root:not(body):not(html)
  ##.entry-pos-vsb
  ##div[id^="dotnAd-"]
```
</details>

**Comment by mapx-** [comment]
what is hiding `##[id|="iubenda"]` ?!

**Comment by superlex** [comment]
@mapx- 
https://github.com/uBlockOrigin/uAssets/issues/21485#issuecomment-1863661798
