### ISSUE TITLE
chillhay.vip: ads

### ISSUE THREAD

**Issue by nqlp** [uBlockOrigin/uAssets#22541]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://chillhay.vip/quoc-gia/phim-han-quoc/`

### Category

ads

### Description

The website is about movies. The page has 4 ads. Attention: 2 of them are NSFW ads.

### Other extensions used

- Bitwarden
- Dark Reader
- 2FAS
- Bypass Paywalls Clean
- FastForward
- RYD
- SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/86736500/fb03052b-8fe0-44f7-aea2-9cf2721416c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 327992
 cosmetic: 262156
 scriptlet: 51207
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77442-130, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-1604, now
  adguard-cookies: 28791-28791, now
  adguard-generic: 80443-501, now
  adguard-mobile: 9094-53, now
  adguard-mobile-app-banners: 5039-5039, now
  adguard-other-annoyances: 14198-14198, now
  adguard-popup-overlays: 26974-26974, now
  adguard-social: 22171-884, now
  adguard-spyware: 100401-1202, now
  adguard-spyware-url: 1447-5, now
  adguard-widgets: 2440-2440, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 21-1, never
  easylist: 81244-1497, 36m Δ
  easyprivacy: 50224-32338, 36m Δ
  plowe-0: 3782-1344, now
  ublock-badware: 7891-256, 36m Δ
  ublock-filters: 37298-4002, 36m Δ
  ublock-privacy: 740-219, 36m Δ
  ublock-quick-fixes: 136-9, 36m Δ
  ublock-unbreak: 2212-148, 36m Δ
  urlhaus-1: 8075-0, 1h.37m
filterset (user): [array of 22 redacted]
userSettings:
 advancedUserEnabled: true
 hyperlinkAuditingDisabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 301 ms (selfie)
 maxAssetCacheWait: 234 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  chillhay.vip: 2
  facebook.com: 1
  googletagmanager.com: 1
 extended:
  ###fb-root:not(body):not(html)
  ##.fb-like-box
```
</details>

**Comment by stephenhawk8054** [comment]
Enable Vietnamese list `ABPVN List` and test again.

**Comment by nqlp** [comment]
> Enable Vietnamese list `ABPVN List` and test again.

Thank you. It works!
