### ISSUE TITLE
worldhistory.org: ads

### ISSUE THREAD

**Issue by krc** [uBlockOrigin/uAssets#22540]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.worldhistory.org/image/14807/the-ancient-near-east-c-1500-1300-bce/`

### Category

ads

### Description

ad frames and some text still appear, images seem mostly blocked still
ads reappear on reload after removing with element picker

Checked after turning off non-default lists as well, still there.

### Other extensions used

I have NoScript, when I temporarily allowed just  worldhistory.org, it complained in a pop up box that html-load.com was blocked. When I enabled that domain in NoScript, that is when the ad material appeared. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![signal-2024-02-17-172627_002](https://github.com/uBlockOrigin/uAssets/assets/211671/2c8eba71-f73d-47ed-b4e5-e6ebd0c680f4)

![image](https://github.com/uBlockOrigin/uAssets/assets/211671/45e894ff-ab47-44f7-aab0-1ac72181293a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 123
filterset (summary):
 network: 131394
 cosmetic: 133492
 scriptlet: 27862
 html: 2335
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77442-1530, now
  adguard-social: 22171-43, now
  ublock-annoyances: 6692-11, now
 default:
  user-filters: 23-3, never
  ublock-filters: 37848-118, now
  ublock-badware: 7895-14, now
  ublock-privacy: 736-0, now
  ublock-unbreak: 2260-0, now
  ublock-quick-fixes: 129-0, now
  easylist: 81244-681, now
  easyprivacy: 50224-884, now
  urlhaus-1: 8075-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1077 ms (selfie)
 maxAssetCacheWait: 366 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  worldhistory.org: 1
  33across.com: 1
  ay.delivery: 3
  cloudflareinsights.com: 2
  confiant-integrations.net: 1
  criteo.com: 1
  criteo.net: 3
  doubleclick.net: 2
  googlesyndication.com: 2
  gravitec.net: 1
  html-load.com: 6
  kueezrtb.com: 2
  metricool.com: 2
  pinterest.com: 1
 extended:
  ##.ahe-ad
  ##.ad_header
  ##.adcontainer
  ##a[href*="pinterest.com/pin/create/button"]
  ##+js(set-constant, admiral, noopFunc)
```
</details>

**Comment by JobcenterTycoon** [comment]
@mapx- defusing the inline loader script doesn’t work for you? `worldhistory.org##^script:has-text(adShieldScript)`

**Comment by mapx-** [comment]
I didn't test it, on my side those filters are working fine on both FF / chrome

**Comment by JobcenterTycoon** [comment]
I tested and it works perfectly. As long there is no Ad-AShield PHP part Ad-Shield can be completely defused.
