### ISSUE TITLE
digitalblogly.com: detection

### ISSUE THREAD

**Issue by Himanshu2ht** [uBlockOrigin/uAssets#22547]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://m.digitalblogly.com/2024/02/17/top-management-consulting-company-in-usa/`

### Category

detection

### Description

Before detection I did not use any other extension beside uBo ...to avoid detection i used greasemonkey and respective user script...but then also it detects adblocking....even when I remove ubo extension then also it says adblock detected.
This is just crap..

### Other extensions used

Greasemonkey with ad adblock killer script 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 125363
 cosmetic: 37173
 scriptlet: 18966
 html: 2094
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 38223-480, now
  ublock-badware: 7889-14, now
  ublock-privacy: 736-1, 11m Δ
  ublock-unbreak: 2271-1, now
  ublock-quick-fixes: 127-0, now
  adguard-mobile: 9094-133, now
  easylist: 81187-16441, 11m Δ
  easyprivacy: 50233-848, now
  urlhaus-1: 8125-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1338 ms
 maxAssetCacheWait: 530 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
is digitalblogly the original page or it's about some shortener page ?

**Comment by Himanshu2ht** [comment]
> is `digitalblogly` the original page or it's about some shortener page ?

Yes it's a shortener page.

**Comment by mapx-** [comment]
When you'll find the link report directly here: #17361

**Comment by Himanshu2ht** [comment]
> go on, provide the real link

I am using it to download a mod of crunchyroll from here: https://teraboxapp.com/s/10pj5LT_VbO_CV8ilosHrBA

Then it needs a pin when you open the app and login through your email. I get this link ::

https://m.digitalblogly.com/2024/02/17/the-future-of-artificial-intelligence-in-healthcare/
