### ISSUE TITLE
exeo.app: detection

### ISSUE THREAD

**Issue by afhsh1** [uBlockOrigin/uAssets#22545]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://exeo.app/Nq3a`

### Category

detection

### Description

Website asks to disable Ublock.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 123913
 cosmetic: 45489
 scriptlet: 18899
 html: 2090
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37863-117, now
  ublock-badware: 7895-14, now
  ublock-privacy: 736-0, now
  ublock-unbreak: 2266-0, now
  ublock-quick-fixes: 127-0, now
  easylist: 81187-618, now
  easyprivacy: 50227-867, now
  urlhaus-1: 8075-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1431 ms (selfie)
 maxAssetCacheWait: 273 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  asacdn.com: 1
  demand.supply: 1
  exe.io: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##.actions, .earning-steps ~ *, .earning-steps, header, footer, …
  ##+js(set-constant, blurred, false)
```
</details>

**Comment by ItsProfessional** [comment]
#17361
