### ISSUE TITLE
fastapi.tiangolo.com: ads

### ISSUE THREAD

**Issue by suspiciousRaccoon** [uBlockOrigin/uAssets#22542]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://fastapi.tiangolo.com/
```

### Description

The page has an aside element at the top that displays ads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/127566947/0240f132-5ef9-4593-b272-95a2e8362449)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.55.0
Firefox: 123
filterset (summary):
 network: 123891
 cosmetic: 45505
 scriptlet: 18881
 html: 2078
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37808-143, now
  ublock-badware: 7895-14, now
  ublock-privacy: 734-0, now
  ublock-unbreak: 2260-0, now
  ublock-quick-fixes: 123-0, now
  easylist: 81225-623, now
  easyprivacy: 50221-835, now
  urlhaus-1: 8075-0, now
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1652 ms
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
fastapi.tiangolo.com###announce-right .item:has(.sponsor-badge)
||fastapi.tiangolo.com/img/sponsors/$image
```

@ryanbr

**Comment by MicaelJarniac** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/19514231/21027d85-3e07-49cd-8f15-340e552cd589)
![image](https://github.com/uBlockOrigin/uAssets/assets/19514231/4b191398-8cf9-40a3-a949-c3931721d00e)

It's hiding the ads, but breaking the top bar, adding a scroll bar to it.
