### ISSUE TITLE
masterkreatif.com [Pop-up] [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2254]
URL(s) where the issue occurs

`https://www.masterkreatif.com/dvdfab-player-ultra-full-version`

Describe the issue

Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by KiLL4FuNK** [comment]
Pop-up Fake Button

`https://www.mazterize.me/internet-download-manager-full-version`

**Comment by KiLL4FuNK** [comment]
Pop-up Fake Button

`https://www.mazterize.com/ccleaner-pro-full-version.html`

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by llacb47** [comment]
Button is still there but does nothing: add `masterkreatif.com##.user[data-user]`

**Comment by mapx-** [comment]
thx

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by llacb47** [comment]
`mazterize.com##.dl-but`

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
`Fake Button`

@mapx-

**Comment by mapx-** [comment]
@ryanbr 

`mazterize.com##.dl-but`

**Comment by KiLL4FuNK** [comment]
Fake Button
