### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by Himanshu2ht** [uBlockOrigin/uAssets#22549]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dropgalaxy.com/drive/fdsba7onxmlx`

### Category

detection

### Description

This site does not only detects adblocker ...but also specially highlights to _**GitHub users(/losers)**_ who get detected 😂😂😂

😡😡
![Screenshot_20240218-204347](https://github.com/uBlockOrigin/uAssets/assets/158832828/737f838f-a30c-475e-b208-6b737da93be9)

### Other extensions used

Greasemonkey and tempermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20240218-204347](https://github.com/uBlockOrigin/uAssets/assets/158832828/4adff3b6-b4e1-4c66-9953-cfc29e949515)

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 125363
 cosmetic: 37173
 scriptlet: 18966
 html: 2094
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.2m
 default:
  user-filters: 0-0, never
  ublock-filters: 38223-480, 58m
  ublock-badware: 7889-14, 58m
  ublock-privacy: 736-1, 1h.9m Δ
  ublock-unbreak: 2271-1, 58m
  ublock-quick-fixes: 127-0, 58m
  adguard-mobile: 9094-133, 58m
  easylist: 81187-16441, 1h.9m Δ
  easyprivacy: 50233-848, 58m
  urlhaus-1: 8125-0, 58m
  plowe-0: 3782-1, 58m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 695 ms (selfie)
 maxAssetCacheWait: 216 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  a-ads.com: 1
  cloudflareinsights.com: 2
 extended:
  ##+js(no-window-open-if)
  ##+js(trusted-set-constant, document.visibilityState, visible)
  ##+js(set-constant, supportedBrowsers, )
```
</details>

**Comment by mapx-** [comment]
=> #17361
