### ISSUE TITLE
komplett.no: breakage

### ISSUE THREAD

**Issue by krogedal** [uBlockOrigin/uAssets#22557]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.komplett.no/kundeservice`

### Category

breakage

### Description

Chat bubble in bottom right does not show when uBO is active.

### Other extensions used

privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 123852
 cosmetic: 45451
 scriptlet: 18899
 html: 2093
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37807-233, 1h.7m Δ
  ublock-badware: 7895-14, 1h.7m Δ
  ublock-privacy: 740-0, 1h.7m Δ
  ublock-unbreak: 2267-2, 1h.7m Δ
  ublock-quick-fixes: 127-0, 1h.7m Δ
  easylist: 81228-532, 1h.7m Δ
  easyprivacy: 50237-835, 1h.7m Δ
  urlhaus-1: 7980-0, 1h.7m
  plowe-0: 3782-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 752 ms
 maxAssetCacheWait: 292 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  komplett.no: 1
  go-mpulse.net: 1
```
</details>

**Comment by krogedal** [comment]
Site is aware of the issue and recommends disabling ad blockers as a fix if chat is not visible

**Comment by stephenhawk8054** [comment]
```adb
@@||stm.komplett.no/gtm.js$script,1p
```

@ryanbr
