### ISSUE TITLE
mobile.de: breakage

### ISSUE THREAD

**Issue by CKa0121** [uBlockOrigin/uAssets#22552]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mobile.de/verkaufen/auto/`

### Category

breakage

### Description

Opening this page with default filter lists results in a blank screen.
If I disable the lists EasyPrivacy and EasyList (both!) the page loads fine - issues seems to be blocking of optimizely.com

### Other extensions used

Cookie Quick Manager
Copy PlainText
DEfault Bookmark Folder
Dict.cc Übersetzung
Feedbro
Geschlossenen Tab wiederherstellen
Gruppen-SpeedDial
HTTPS Everywhere
Joplin Web Clipper
KeePassXC-Browser
MetaGer Suche
Screngrab!
Video DownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="956" alt="Qb4TL9x558" src="https://github.com/uBlockOrigin/uAssets/assets/154369182/10dfdb37-4ac6-4f04-a0ad-4f92d1bcdd37">
<img width="955" alt="hsuDcLYCKU" src="https://github.com/uBlockOrigin/uAssets/assets/154369182/619ff139-d957-4fa4-b0a4-d3a506bd65b8">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 126251
 cosmetic: 50427
 scriptlet: 18889
 html: 2093
listset (total-discarded, last-updated):
 default:
  user-filters: 11-1, never
  ublock-filters: 37799-129, 12m
  ublock-badware: 7895-14, 12m
  ublock-privacy: 740-0, 12m
  ublock-unbreak: 2266-0, 12m
  easylist: 81226-624, never
  easyprivacy: 50224-876, 9m
  plowe-0: 3782-1, 10m
  DEU-0: 7269-3, 10m
  urlhaus-1: 8125-0, 10m
  ublock-quick-fixes: 125-0, 12m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 31 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2582 ms (selfie)
 maxAssetCacheWait: 2094 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  googletagmanager.com: 1
  optimizely.com: 4
  theadex.com: 1
  trackjs.com: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`@@||cdn.optimizely.com/public/*.json/tag.js$script,domain=mobile.de`
