### ISSUE TITLE
gamestar.de: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22555]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gamestar.de/`

### Category

nuisance

### Description

Cookie-Banner

### Other extensions used

non relevant

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-19 082542](https://github.com/uBlockOrigin/uAssets/assets/100969549/9af258aa-f455-4b27-aa46-9d7c97620a52)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 376577
 cosmetic: 278056
 scriptlet: 51784
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4318-4, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97346-16943, now
  CHN-0: 25615-133, now
  JPN-1: 14097-9, now
  KOR-1: 4947-21, 56m
  adguard-cookies: 28792-3674, now
  [22 lists not shown]: [too many]
 default:
  user-filters: 62-0, never
  DEU-0: 7269-1, now
  easylist: 81228-1834, 8m Δ
  easyprivacy: 50237-32525, 8m Δ
  plowe-0: 3782-1689, now
  ublock-badware: 7891-268, 8m Δ
  ublock-filters: 37257-4039, 8m Δ
  ublock-privacy: 744-222, 8m Δ
  ublock-quick-fixes: 134-7, 8m Δ
  ublock-unbreak: 2210-156, 8m Δ
  urlhaus-1: 7980-2, now
filterset (user): [array of 63 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 88 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 debugScriptlets: true
 loggerPopupType: normal
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 826 ms (selfie)
 maxAssetCacheWait: 687 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  gamestar.de: 2
  cgames.de: 1
  duckduckgo.com: 2
  getjad.io: 1
  pbstck.com: 1
  typekit.net: 1
  webcontentassessor.com: 1
 extended:
  ###backtotop
  ###footer-bold
  ###dfp-header
  ###dfp-header-container
  ##.jad-placeholder
  ##.content-item-small:has(h3:has-text(Anzeige))
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by gorhill** [comment]
I came up with this to remove the overlay:

    gamestar.de###cmp-modal
    gamestar.de##.modal-backdrop
    gamestar.de##body:style(overflow:auto!important)
    gamestar.de##.modal-cmp:style(filter:none!important)

cc @ryanbr

**Comment by dportvine** [comment]
Is it too much?

```adblock
gamestar.de##+js(aopr, $, #cmp-modal)
```

<details>
<summary>Screen</summary>

![2024-02-19_171324](https://github.com/uBlockOrigin/uAssets/assets/111344219/8e6760fe-c344-4e1f-8a5e-a837dd048904)
</details>
