### ISSUE TITLE
0zz0.*: breakage

### ISSUE THREAD

**Issue by Chipsum** [uBlockOrigin/uAssets#22559]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
*.0zz0.*
```

### Description

this is a image upload website that most Arab forums and communities uses, and I am really getting frustrated when I see someone's reply empty, till I understood it was UO that's blocking it.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/37517008/3436fe5e-5996-4a25-9191-47d06289a964)

Meanwhile when I disable UO:

![image](https://github.com/uBlockOrigin/uAssets/assets/37517008/a5da6005-f6fd-4b38-840f-fbc05ddbf147)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by ItsProfessional** [comment]
Does the site require an account?
Also, provide the exact URL, not just the domain.

**Comment by ItsProfessional** [comment]
I don't see the chat even with uBO disabled. Can you provide your troubleshooting info, you didn't mention it in the issue.

**Comment by Chipsum** [comment]
@What chat event ?

**Comment by dportvine** [comment]
>image upload website that most Arab forums and communities uses

What website is the problem on?

**Comment by Chipsum** [comment]
@dportvine it's www.0zz0.com

**Comment by dportvine** [comment]
Ok, what's the problem?

**Comment by Chipsum** [comment]
wait I will take a video since it seems that whatever I write is not understandable

**Comment by Chipsum** [comment]
let's take this forum as an example
https://www.startimes.com/f.aspx?t=39127852&r=1438735065

and here is the video explaining the problem:

https://github.com/uBlockOrigin/uAssets/assets/37517008/aa50947d-d609-4cbf-83c9-f2006111764a

**Comment by ButterVsMargarine** [comment]
Blocked by uBlock Origin filter `||0zz0.com^$3p`

**Comment by gorhill** [comment]
@Chipsum when asked to provide an exact URL where we can experience first-hand the issue, please do provide it, otherwise we all waste our (volunteered) time.

Here is the proper way to report the issue:

- **Exact URL** to navigate to experience the issue: `https://www.startimes.com/f.aspx?t=39141591`
- Page rendering broken, missing information:

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/6ea1e616-8c80-446a-a672-6e19309deea5)

- uBO disabled for the site:

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/f002d028-c87a-44d2-8f0b-5362eef6ab64)

With this, we would have figured immediately the issue. Telling to navigate to `*.0zz0.*` is pointless and waste our time -- try for yourself to copy/paste `*.0zz0.*` in your address bar to see for yourself.

**Comment by Chipsum** [comment]
@gorhill It was not my intention to waste your time as I do not want to waste my time too and the proof is that I am reporting.
I did not understand the exact meaning of exact url, since UBO blocked www.0zz0.com and not the forum www.startimes.com, so please don't hurt my feelings I am trying my best to do what's right.

**Comment by gorhill** [comment]
The issue was fixed with <https://github.com/uBlockOrigin/uAssets/commit/e596610829b059b4243d7a2c8afbbab8e1641f8e>.

**Comment by Chipsum** [comment]
> The issue was fixed with [e596610](https://github.com/uBlockOrigin/uAssets/commit/e596610829b059b4243d7a2c8afbbab8e1641f8e).

Thanks
I am sorry for the waste of time
