### ISSUE TITLE
[nsfw] xvideos.com: breakage

### ISSUE THREAD

**Issue by geoniz** [uBlockOrigin/uAssets#22563]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.xvideos.com/`

### Category

breakage

### Description

Afther open any video there is just white screen,when i disable cosmetic filters all load fine,dont sure is there some cosmetic filtering error or what. I dont thins i need to do screenshot, just white screen with cosmetic filter enabled)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 102
filterset (summary):
 network: 141083
 cosmetic: 66391
 scriptlet: 21678
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 10-0, never
  RUS-0: 39860-9, 49m Δ
  easylist: 81228-30, 49m Δ
  easyprivacy: 50237-86, 49m Δ
  plowe-0: 3782-1190, 18m
  ublock-badware: 7891-142, 49m Δ
  ublock-filters: 37257-381, 49m Δ
  ublock-privacy: 744-7, 49m Δ
  ublock-quick-fixes: 134-6, 49m Δ
  ublock-unbreak: 2210-34, 49m Δ
  urlhaus-1: 7840-0, 18m
filterset (user): [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1933 ms (selfie)
 maxAssetCacheWait: 281 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 no-cosmetic-filtering: true
 network:
  xvideos.com: 2
  gstatic.com: 1
  orbsrv.com: 2
```
</details>

**Comment by mapx-** [comment]
already fixed, use this link to update the specific list (easylist)
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=easylist&manual=1

**Comment by geoniz** [comment]
I'm trying it right now,afther update easylist,and still white screen.

**Comment by mapx-** [comment]
Did you update using my link above ?

**Comment by geoniz** [comment]
Yes,thank you! Afther reset and update list again all work fine!
