### ISSUE TITLE
mail.ru: breakage

### ISSUE THREAD

**Issue by dasasd122311** [uBlockOrigin/uAssets#22569]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
*.mail.ru
```

### Description

I noticed that ublock does not block *.mail.ru ads
I noticed they're downloaded from here - https://r.mradx.net/img/89/1B3698.png => https://r.mradx.net/img/*/*.png
But I think that it also loads additional js modules (I don’t understand how advertising, your extension, etc. work)
example links :
https://mail.ru/
https://cloud.mail.ru/public/5wLd/u61ccVuit
i use default configuration

### Other extensions used

metamask & phantom wallet (they only affect phishing links)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/154722840/b702fe01-d8ac-4b49-abad-861b9886f1f1)
![image](https://github.com/uBlockOrigin/uAssets/assets/154722840/9a291e51-7b7c-49c4-9ecd-a102cb99ffe9)
![image](https://github.com/uBlockOrigin/uAssets/assets/154722840/a8e37328-c4ad-4958-b13c-80f139a4444e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by ItsProfessional** [comment]
Enable russian regional list.

**Comment by dasasd122311** [comment]
> Enable russian regional list.
Thx, worked
![image](https://github.com/uBlockOrigin/uAssets/assets/154722840/48ccfc2c-43d5-4df9-993e-5aab5163371d)

Why aren't they enabled by default, is there a problem with them?

**Comment by ItsProfessional** [comment]
@dasasd122311
> Why aren't they enabled by default, is there a problem with them?

I'm *pretty sure* they are enabled by default, if your browser's language is set to russian.

> they break the site. For example - when downloading from cloud.mail.ru I am asked for authorization, but without the filter I am not

@dimisa-RUAdList can you reproduce this?

**Comment by dimisa-RUAdList** [comment]
Yes, I observe this behavior. If you block ads and trackers, and then delete cookies, then on pages like `https://cloud.mail.ru/public/4nUG/bwMo7v9yy`, the authorization request when downloading files will not appear. But this is not a breakdown, but rather a random pleasant bonus from the blocker. Requesting authorization when downloading files is completely unnecessary.
