### ISSUE TITLE
webnovel.com: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22566]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.webnovel.com/book/immortality-system-the-last-human's-transmigration_23118523506262305/mind-games_62975139523918219`

### Category

nuisance

### Description

1, The Website is trying to stop Debugger
2, The Website is clearing Consle by console.clear() 
3, The Website is forcing you to switch to mobile. Can you stop that?  

### Other extensions used

non relavent 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-19 210757](https://github.com/uBlockOrigin/uAssets/assets/100969549/e3e61b4f-8bba-48df-a811-3fb908dd3015)
![Screenshot 2024-02-19 210814](https://github.com/uBlockOrigin/uAssets/assets/100969549/bfc3215a-197a-4e86-9813-06dc9da139db)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 389990
 cosmetic: 278145
 scriptlet: 51808
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4318-4, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97346-16943, now
  CHN-0: 25618-133, now
  JPN-1: 14107-9, now
  KOR-1: 4951-21, 36m
  adguard-cookies: 28807-3672, now
  [22 lists not shown]: [too many]
 default:
  user-filters: 62-0, never
  DEU-0: 7269-1, now
  easylist: 81238-1834, 1h.36m Δ
  easyprivacy: 50239-32496, 1h.36m Δ
  plowe-0: 3782-1689, now
  ublock-badware: 7953-268, 1h.36m Δ
  ublock-filters: 37272-4039, 1h.36m Δ
  ublock-privacy: 744-222, 1h.36m Δ
  ublock-quick-fixes: 117-4, 1h.36m Δ
  ublock-unbreak: 2210-156, 1h.36m Δ
  urlhaus-1: 7840-2, now
filterset (user): [array of 63 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 88 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 debugScriptlets: true
 loggerPopupType: normal
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1605 ms (selfie)
 maxAssetCacheWait: 652 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 71
 network:
  webnovel.com: 67
  dwin1.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##.m_down_app_wrap
  ##.no-select:remove-class(no-select)
  ##+js(addEventListener-defuser, /contextmenu|copy/)
  ##+js(set-constant, adblockSuspected, false)
```
</details>

**Comment by mapx-** [comment]
1 + 2:

```
webnovel.com##+js(set, console.clear, noopFunc)
webnovel.com##+js(nosiif, debug)
```

3: How is forcing you to switch to mobile ?

**Comment by big-cat-loaf** [comment]
Wenn you go on a Book, than of the Chapter, scroll down, you see ones with a lock. Thats the one that you need to switch to mobile.
Normal chapter: ![Screenshot 2024-02-19 213402](https://github.com/uBlockOrigin/uAssets/assets/100969549/b311fe92-2f63-422a-9c14-301a82e426f0)
Chapter with forced mobile switch: 
! [Screenshot 2024-02-19 213347](https://github.com/uBlockOrigin/uAssets/assets/100969549/982f1693-8b43-4d32-9adf-64b2fd176cea)

**Comment by mapx-** [comment]
it seems to be a paywall

add
`webnovel.com##+js(rpnt, script, "isToApp":true, "isToApp":false)`

now you'll have to log in and get this:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/b1e006e2-0ccb-49e7-a284-d5dcfbb8a910)

which is a paywall

**Comment by big-cat-loaf** [comment]
Thanks I didn't know that it was a paywall. I thought some had no paywall and were only blocked by the chapter-forced-app-script. Thanks for your help. I hop, I didn't wast your time to much.

**Comment by big-cat-loaf** [comment]
When you put the other two filters in the list, I will close the ticket.

**Comment by mapx-** [comment]
added in `uBlock filters – Annoyances`
