### ISSUE TITLE
mypunepulse.com: ads

### ISSUE THREAD

**Issue by kookieman12** [uBlockOrigin/uAssets#22568]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mypunepulse.com/after-march-15-it-will-no-longer-be-possible-to-recharge-your-paytm-fastag-learn-how-to-purchase-a-new-one-instead/`

### Category

ads

### Description

Ads are shown on the right

### Other extensions used

bitwarden, bypass paywalls clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 124115
 cosmetic: 45451
 scriptlet: 18914
 html: 2093
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37825-202, 20m
  ublock-badware: 7972-14, 20m
  ublock-privacy: 740-0, 20m
  ublock-unbreak: 2268-2, 20m
  ublock-quick-fixes: 110-1, 20m
  easylist: 81274-528, 20m
  easyprivacy: 50268-867, 20m
  urlhaus-1: 8100-0, 21m
  plowe-0: 3782-1, 21m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1123 ms
 maxAssetCacheWait: 4 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  googlesyndication.com: 4
  googletagmanager.com: 1
  onesignal.com: 1
  twitter.com: 4
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
mypunepulse.com##.n2-section-smartslider
mypunepulse.com##[id^="smartslider"]
```

@ryanbr

**Comment by stephenhawk8054** [comment]
It will take time for the lists to be updated. Use the above filters as your custom filters in the meantime.
