### ISSUE TITLE
ranui.store.freshchoice.co.nz: nuisance

### ISSUE THREAD

**Issue by bubbles54321** [uBlockOrigin/uAssets#22567]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

```yml
https://ranui.store.freshchoice.co.nz
```

### Category

nuisance

### Description

this is a popup always displayed not only to first time shoppers

### Other extensions used

bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 123842
 cosmetic: 45469
 scriptlet: 20244
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 81274-12, 53m Δ
  easyprivacy: 50240-6, 53m Δ
  plowe-0: 3782-1186, now
  ublock-badware: 7968-142, 53m Δ
  ublock-filters: 37275-359, 53m Δ
  ublock-privacy: 744-6, 53m Δ
  ublock-quick-fixes: 117-3, 53m Δ
  ublock-unbreak: 2210-34, 53m Δ
  urlhaus-1: 7840-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 426 ms (selfie)
 maxAssetCacheWait: 197 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 2
  maps.googleapis.com: 1
  newrelic.com: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
freshchoice.co.nz##[data-broadcast-modal]:remove()
```

@ryanbr For EL Notifications or EL Other Annoyances?

**Comment by stephenhawk8054** [comment]
Added to `EasyList – Other Annoyances` list

**Comment by bubbles54321** [comment]
As far as i can tell, my lists are up to date but this issue is still occurring. Am I missing something?

**Comment by stephenhawk8054** [comment]
Enable `EasyList – Other Annoyances` list

**Comment by bubbles54321** [comment]
Very sorry, I thought I had enabled that. Sorry
