### ISSUE TITLE
lnw.com: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#22575]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.lnw.com
```

### Description

The page doesn't load properly.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Page](https://github.com/uBlockOrigin/uAssets/assets/20948631/58d1aeeb-9115-41aa-8de1-818cb299c251)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 107601
 cosmetic: 227190
 scriptlet: 50232
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  ublock-privacy: null
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77519-131, 11h.55m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 96873-22525, 1d.12h.54m
  adguard-cookies: 28812-28812, 11h.56m
  adguard-generic: 80599-538, 11h.55m
  adguard-mobile: 9103-63, 11h.55m
  adguard-mobile-app-banners: 5058-5058, 11h.55m
  adguard-other-annoyances: 14207-14207, 11h.55m
  adguard-popup-overlays: 26992-26992, 11h.55m
  adguard-widgets: 2441-2441, 11h.55m
  block-lan: 56-0, 9d.21h.51m
  dpollock-0: 11638-77, 10d.20h.47m
  easylist-annoyances: 4373-4348, 11h.55m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 81285-1714, 2m Δ
  plowe-0: 3783-831, 10d.20h.47m
  ublock-badware: 7991-250, 2m Δ
  ublock-filters: 37313-3805, 2m Δ
  ublock-quick-fixes: 119-4, 2m Δ
  ublock-unbreak: 2211-84, 2m Δ
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 696 ms (selfie)
 maxAssetCacheWait: 360 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by gorhill** [comment]
Unable to reproduce when using default settings/lists.

- [x] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x]  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists

Your troubleshooting information contradict those statements, we can't help if you do not truthfully follow those prerequisites.

**Comment by gorhill** [comment]
Caused by `||cookielaw.org^$3p` in "AdGuard – Cookie Notices" and added list `https://filters.adtidy.org/extension/ublock/filters/14.txt`.

**Comment by stephenhawk8054** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Fixed.
