### ISSUE TITLE
Domain required for adblock filters

### ISSUE THREAD

**Issue by rnixs** [uBlockOrigin/uAssets#22578]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
cdn.b2.ai
```

### Description

This domain is the request domain of anti-adblock. I'm not restoring ads yet, but I'm asking you to block that domain because it's a threat.
<a href="https://www.b2.ai/">About anti-adblock B2</a>

### Other extensions used

none(only uBO)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="920" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/81290656/c8c0c178-e48a-4352-a0d9-0f23e8c85a4f">

<img width="1385" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/81290656/7bd10e54-ad8e-41a3-9dc1-a7b473775b55">

</details>

### Configuration

<details>
<summary>Details</summary>
block the b2.ai request domain

```yaml
||cdn.b2.ai^
```
</details>

**Comment by stephenhawk8054** [comment]
We can only investigate with real websites getting anti-adblock. If you find any websites like that, please report here.
