### ISSUE TITLE
larousse.fr: nuisance

### ISSUE THREAD

**Issue by LightShaft** [uBlockOrigin/uAssets#22573]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.larousse.fr/`

### Category

nuisance

### Description

There's a banner that's blurring the background, asking for consent
You're supposed to give consent for the site to give another banner to confirm cookies, but clicking on « I consent » doesn't do anything, it's basically stuck

### Other extensions used

I still don't care about cookies (I tried disabling it tho)
Basic protection from Firefox (tried disabling it too)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/27209225/f5ac06c9-4bab-4fea-8f45-8b6b68a4faff)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 141649
 cosmetic: 52349
 scriptlet: 19066
 html: 2093
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37863-207, now Δ
  ublock-badware: 7995-14, now Δ
  ublock-privacy: 740-0, now Δ
  ublock-unbreak: 2268-2, now Δ
  ublock-quick-fixes: 112-1, now Δ
  easylist: 81285-767, now Δ
  easyprivacy: 50247-1035, now Δ
  urlhaus-1: 8145-0, now
  plowe-0: 3782-1, now
  FRA-0: 25077-111, never
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 262 ms (selfie)
 maxAssetCacheWait: 111 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  cloudflareinsights.com: 3
  sparteo.com: 1
  viously.com: 3
 extended:
  ##.pub-top
  ##.pub-pave
  ###taboola-below-article-thumbnails
  ##.pub-bottom
```
</details>

**Comment by dportvine** [comment]
Enable **AdGuard – Cookie Notices** in Annoyances section

**Comment by stephenhawk8054** [comment]
Fixed in cookie notices lists.
