### ISSUE TITLE
unite-db.com: ads

### ISSUE THREAD

**Issue by EmperorWaluigi** [uBlockOrigin/uAssets#22574]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://unite-db.com/`

### Category

ads

### Description

Site still has an add showing on the home page
personally dont mind it the site is nice and dont find it too much a bother just wanted to report that they did manage to get an ad through.
ad is located below the tabs [i.e pokemon stats etc] and above the pokemon
new to reporting this so if any other info is needed email me or check the site out

there is a prior report but that was 2 years ago so cant say its a duplicate now...? unless that is then sorry but leaving this here anyways.

### Other extensions used

Autohd/4k extension [the one that auto sets youtube video quality] 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 124151
 cosmetic: 45472
 scriptlet: 20247
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81279-12, 4m Δ
  easyprivacy: 50244-6, 4m Δ
  plowe-0: 3782-1186, now
  ublock-badware: 7968-142, 4m Δ
  ublock-filters: 37275-359, 4m Δ
  ublock-privacy: 744-6, 4m Δ
  ublock-quick-fixes: 119-3, 4m Δ
  ublock-unbreak: 2211-34, 4m Δ
  urlhaus-1: 8145-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 858 ms (selfie)
 maxAssetCacheWait: 163 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 2
  googletagmanager.com: 2
  moatads.com: 1
  network-n.com: 2
  primis.tech: 1
```
</details>

**Comment by gorhill** [comment]
Suggested filter:

    unite-db.com##a[href*="?utm_source"]:has(> img)

**Comment by stephenhawk8054** [comment]
@ryanbr
