### ISSUE TITLE
seriesgato.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2258]
URL(s) where the issue occurs

`https://www.seriesgato.tv/serie/la-resistencia-341430.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by lain566** [comment]
Fake buttons and popup when clicking on player.
`https://seriesgato.tv/capitulo/the-flash/1/01/`

**Comment by mapx-** [comment]
for the buttons
`seriesgato.tv##+js(abort-on-property-write.js, smrtSB)`

no popup

Does the filter above fixes both issues for you ?

**Comment by lain566** [comment]
Yeah, that filter fixes the popup and fake buttons
