### ISSUE TITLE
cachecrawler.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#22583]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cachecrawler.com/`

### Category

nuisance

### Description

overlay cookies

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/07dba885-33ba-45ae-8f35-90c47d96ca81)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 122
filterset (summary):
 network: 133589
 cosmetic: 159152
 scriptlet: 33298
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 9468-0, 27m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 194-0, now
  adguard-other-annoyances: 14210-22, now
  adguard-popup-overlays: 27001-67, now
  easylist-annoyances: 4379-203, now
  easylist-newsletters: 7003-480, now
  easylist-notifications: 2943-400, now
  fanboy-cookiemonster: 50082-215, now
  fanboy-social: 16173-51, now
  ublock-annoyances: 6773-219, now
  ublock-cookies-easylist: 951-951, now
 default:
  user-filters: 39-0, never
  easylist: 81341-70, now
  easyprivacy: 50257-110, now
  plowe-0: 3782-1186, now
  ublock-badware: 7992-143, now
  ublock-filters: 37276-807, now
  ublock-privacy: 744-8, now
  ublock-quick-fixes: 115-5, now
  ublock-unbreak: 2211-38, now
  urlhaus-1: 8230-0, 1h.27m
filterset (user): [array of 39 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 858 ms (selfie)
 maxAssetCacheWait: 384 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
test

```
cachecrawler.com##+js(trusted-set-session-storage-item, hasConsent, yjazld5mmsll377zp2m77wknrgdhywt2)
cachecrawler.com##+js(trusted-set-session-storage-item, hasDsg, lr5nqqiwe6jk6fv97gzicld3wlk92x74)
```

**Comment by 3xploiton3** [comment]
> ```
> cachecrawler.com##+js(set-session-storage-item, hasConsent, 1)
> cachecrawler.com##+js(set-session-storage-item, hasDsg, 1)
> ```
> 
> value is 1 for me?

this work for me too
