### ISSUE TITLE
cj.com: breakage

### ISSUE THREAD

**Issue by josefpsurny** [uBlockOrigin/uAssets#22580]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cj.com/`

### Category

breakage

### Description

Looks like CSS is not loaded and critical JS.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![www cj com_(16_9 (360x640))](https://github.com/uBlockOrigin/uAssets/assets/60666717/1291e6d6-3973-4af4-bab0-6820608399c9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 124487
 cosmetic: 45893
 scriptlet: 20376
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CZE-0: 832-1, now
  easylist: 81341-16, now
  easyprivacy: 50248-11, now
  plowe-0: 3782-1186, now
  ublock-badware: 7992-142, now
  ublock-filters: 37280-359, now
  ublock-privacy: 744-6, now
  ublock-unbreak: 2211-32, now
  urlhaus-1: 8230-0, now
filterset (user): [empty]
trustedset:
 added: [array of 30 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 589 ms (selfie)
 maxAssetCacheWait: 222 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 49
 network:
  cj.com: 34
  doubleclick.net: 2
  google.com: 4
  googleoptimize.com: 1
  licdn.com: 1
  matomo.cloud: 1
  pardot.com: 1
  typekit.net: 1
  youtube.com: 4
 extended:
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted#click-the-big-power-button
