### ISSUE TITLE
texteditor.nsspot.net: detection

### ISSUE THREAD

**Issue by oignon-blashley** [uBlockOrigin/uAssets#22598]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://texteditor.nsspot.net/`

### Category

detection

### Description

After a few seconds, the site's text editor program disappears and is replaced by an anti-ad blocking message.

### Other extensions used

Grammarly, Session Buddy, Chrono Download Manager, Honey, Notion, Pinterest

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 136266
 cosmetic: 199813
 scriptlet: 33417
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28848-31, now
  adguard-mobile-app-banners: 5061-7, now
  adguard-other-annoyances: 14215-8, now
  adguard-popup-overlays: 27005-84, now
  adguard-social: 22196-878, now
  adguard-widgets: 2441-3, now
  easylist-annoyances: 4379-244, now
  easylist-chat: 182-14, now
  easylist-newsletters: 7004-488, now
  easylist-notifications: 2943-1472, now
  fanboy-cookiemonster: 50082-3840, now
  fanboy-social: 16173-757, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 32-6, never
  easylist: 81353-69, 1h.8m Δ
  easyprivacy: 50261-119, 1h.8m Δ
  plowe-0: 3782-1187, now
  ublock-badware: 7992-142, 1h.8m Δ
  ublock-filters: 37312-714, 1h.8m Δ
  ublock-privacy: 744-8, 1h.8m Δ
  ublock-quick-fixes: 115-5, 1h.8m Δ
  ublock-unbreak: 2211-38, 1h.8m Δ
  urlhaus-1: 8880-0, now
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2096 ms
 maxAssetCacheWait: 1280 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 3
 extended:
  ##+js(set-constant, gadb, false)
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 Is this issue still ongoing?

**Comment by Yuki2718** [comment]
Yeah, can be closed.
