### ISSUE TITLE
[Malicious website] interest.center

### ISSUE THREAD

**Issue by kovacsattila-hun** [uBlockOrigin/uAssets#226]
### URL(s) where the issue occurs

`http://www.interest.center/hu/h1/#`

### Describe the issue

Blackmailer virus + abuse of Google's name!

### Screenshot(s)

http://i.imgur.com/YSEft50.png

### Versions

- Browser/version: Google Chrome 55 (Windows)
- uBlock Origin version: 1.10.0

### Settings

All default settings.

### Notes

It may be necessary to block the page.

**Comment by SMed79** [comment]
Post the url to the page/site who displays advertising and describe exactly how to reproduce not **ONLY** the URL to the ad.

Also an adblocker can not replace an antivirus software, scan your system for malware / adware using:
- https://www.malwarebytes.com/mwb-download/ (free)
- https://toolslib.net/downloads/viewdownload/1-adwcleaner/

**Comment by gorhill** [comment]
The thing to do is to report to the malware domain lists:
http://www.malwaredomainlist.com/
http://www.malwaredomains.com/
