### ISSUE TITLE
tvnz.co.nz: breakage

### ISSUE THREAD

**Issue by Steve641** [uBlockOrigin/uAssets#22600]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tvnz.co.nz/shows/coronation-street/episodes/s2024-e11189-11190`

### Category

breakage

### Description

Custom subtitles on this site are broken when using uBlock. Disabling uBlock from Chrome's Extensions page in Settings restores functionality. The standard subtitles still work, but they are large and obscure much of the picture. Basically, the option to use customised subtitles disappears when uBlock is running, even if turned off with the blue disable button in the menu that drops down when clicking the icon. I have tried numerous options on the menu, and reinstalled uBlock, but the problem persists as long as uBlock is present and not disabled from the extensions page. Otherwise, the best adblocker I have used...:-)

### Other extensions used

I disabled all other extensions from Settings/Extensions to test this. It made no difference.

### Screenshot(s)

![Clipboard01](https://github.com/uBlockOrigin/uAssets/assets/114973188/df5827f5-4959-4ec3-8edb-21c4a702c9f8)
![Clipboard02](https://github.com/uBlockOrigin/uAssets/assets/114973188/355ba7d7-e5f4-4023-b751-59027c5bf7bd)
You can see that the subtitle menu item for custom subtitles is missing from the first screenshot, where uBlock is running.

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 124734
 cosmetic: 45550
 scriptlet: 20271
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81527-12, now
  easyprivacy: 50263-6, now
  plowe-0: 3782-1186, now
  ublock-badware: 7996-142, now
  ublock-filters: 37310-361, now
  ublock-privacy: 744-6, now
  ublock-quick-fixes: 114-5, now
  ublock-unbreak: 2211-34, now
  urlhaus-1: 8510-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 358 ms (selfie)
 maxAssetCacheWait: 211 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  brightcove.com: 5
  crazyegg.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  imrworldwide.com: 2
  newrelic.com: 1
  qualtrics.com: 1
  segment.com: 1
  tremorhub.com: 1
  youborafds01.com: 1
 extended:
  ##.Advert
  ##.Advert-label
```
</details>

**Comment by stephenhawk8054** [comment]
With your link above, even when I don't use any extensions, I don't see the other subtitle option:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/e595909d-14dd-4dbe-bae0-5019c655ca01)

**Comment by mapx-** [comment]
I can't replicate your issue either
