### ISSUE TITLE
affiliates.groovehq.com: breakage

### ISSUE THREAD

**Issue by Piotrekk** [uBlockOrigin/uAssets#22604]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://affiliates.groovehq.com/
```

### Description

Website assets are not loaded properly due to uBlock blocking it.

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1434" alt="Screenshot 2024-02-22 at 13 24 30" src="https://github.com/uBlockOrigin/uAssets/assets/4234378/557a1796-c9f0-4503-96f8-9a8699ddd7b7">

<img width="1438" alt="Screenshot 2024-02-22 at 13 24 50" src="https://github.com/uBlockOrigin/uAssets/assets/4234378/619e35bc-7f2c-4eba-8818-f9fe876d9f91">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 125107
 cosmetic: 45557
 scriptlet: 20279
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81530-12, 1h Δ
  easyprivacy: 50264-6, 1h Δ
  plowe-0: 3782-1186, 4d.18h.29m
  ublock-badware: 7996-142, 1h Δ
  ublock-filters: 37323-361, 1h Δ
  ublock-privacy: 744-6, 1h Δ
  ublock-quick-fixes: 114-5, 1h Δ
  ublock-unbreak: 2211-34, 1h Δ
  urlhaus-1: 8880-0, 17h.51m
filterset (user): [empty]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 353 ms (selfie)
 maxAssetCacheWait: 130 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by mapx-** [comment]
add

`@@||web-assets.tapfiliate.com^$domain=affiliates.groovehq.com`

@ryanbr

**Comment by Piotrekk** [comment]
@mapx- There is also following issue:

<img width="709" alt="Screenshot 2024-02-23 at 15 19 16" src="https://github.com/uBlockOrigin/uAssets/assets/4234378/c84c3f10-83d4-4f56-b131-f902880a0b9a">
