### ISSUE TITLE
mobalytics.gg: detection

### ISSUE THREAD

**Issue by fadedninna** [uBlockOrigin/uAssets#22616]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mobalytics.gg/`

### Category

detection

### Description

Site detects UBO

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran görüntüsü 2024-02-23 015342](https://github.com/uBlockOrigin/uAssets/assets/47019227/678d5428-c22b-4915-80d0-fab14b7a8976)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 126394
 cosmetic: 55323
 scriptlet: 22053
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  TUR-0: 13102-61, now
  easylist: 81654-33, 1h.48m Δ
  easyprivacy: 50264-11, 1h.48m Δ
  plowe-0: 3782-1187, now
  ublock-badware: 8011-142, 1h.48m Δ
  ublock-filters: 37330-371, 1h.48m Δ
  ublock-privacy: 744-6, 1h.48m Δ
  ublock-quick-fixes: 122-5, 1h.48m Δ
  ublock-unbreak: 2211-35, 1h.48m Δ
  urlhaus-1: 8550-0, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 190 ms (selfie)
 maxAssetCacheWait: 111 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 18
 network:
  d1l6p2sc9645hc.cloudfront.net: 1
  doubleclick.net: 1
  fuseplatform.net: 1
  googletagmanager.com: 1
  hotjar.com: 1
  mixpanel.com: 12
  riotgames.com: 1
```
</details>

**Comment by mapx-** [comment]
where exactly do you get the detection message ?

**Comment by fadedninna** [comment]
not exactly a detection message but it is on bottom right corner

**Comment by ItsProfessional** [comment]
We mean the exact URL of the page where you're detected. You only provided the domain, but in your screenshot, there's a different URL. Provide that URL.

**Comment by mapx-** [comment]
it's not detection, the same containers appear disabling uBO

test 

```
mobalytics.gg##:xpath(//span[contains(text(),"Remove ")]):upward(2)
mobalytics.gg##:xpath(//span[contains(text(),"Advertisement")]):upward(3)
```

**Comment by ItsProfessional** [comment]
@fadedninna This isn't detection, it's self promotion for the premium subscription for the site
