### ISSUE TITLE
terpli.io: breakage

### ISSUE THREAD

**Issue by diegomors** [uBlockOrigin/uAssets#22617]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.theartisttree.com/
https://thesanctuaryca.com/
https://www.thesourcenv.com/
```

### Description

Hi, I've build a web application that works like a floating chat to provide product recommendation into a retailer's website based on their products and the customer preferences.

This application is embedded through an iframe and it's currently being blocked by uBlock. However, the application is trust for retailers' website, because they added our aplication into their website.

**Could you add our domain to your whitelist to avoid this issue?**
  - Domain: terpli.io

### Other extensions used

No other extension was used.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1680" alt="Screenshot 2024-02-22 at 20 23 32" src="https://github.com/uBlockOrigin/uAssets/assets/4834401/4db96bc3-f5ac-4f44-808f-f742ae91b95e">

<img width="1680" alt="Screenshot 2024-02-22 at 20 23 49" src="https://github.com/uBlockOrigin/uAssets/assets/4834401/b904ec82-4112-47d5-bab4-f2ee9df55b1a">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
It's because you embed it inside `googletagmanager` which is blocked by uBO. `terpli.io` is not blocked by uBO

Needs

```adb
@@||googletagmanager.com/gtm.js$script,domain=theartisttree.com|thesanctuaryca.com|thesourcenv.com
```

I don't like the idea of needing `googletagmanager` for your chat.

@ryanbr What do you think?

**Comment by ryanbr** [comment]
could be a few terpli.io sites if they rely on gtm. The better option is for them to remove the gtm requirement, for privacy sake.

**Comment by stephenhawk8054** [comment]
Can you share any sites that work without `googletagmanager`?

**Comment by mapx-** [comment]
@diegomors add here your comments

**Comment by diegomors** [comment]
Hey @stephenhawk8054 , @ryanbr , @mapx- is there some way to make the uBlock knows that we are not an advertising even using google tag manager? 

It was the only way to integrate our web plugin with many clients and these clients have a lot of users that uses uBlock and would be great to find a solution. Do you have some idea to workaround?
