### ISSUE TITLE
community.spontacts.com: detection

### ISSUE THREAD

**Issue by amaru7** [uBlockOrigin/uAssets#22611]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://community.spontacts.com/index?stream-list-items=20&qt=1708620210450`

### Category

detection

### Description

Ublock isn't filtering the sites Anti Adblock and it is quite annoying. Could anyone filter? Unfortunately registration is required to be able to see the ads. I hope somebody has the account there or would be willing to do a quick registration. This issue has been going for quite some time.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 127214
 cosmetic: 50477
 scriptlet: 18915
 html: 1815
listset (total-discarded, last-updated):
 default:
  user-filters: 14-2, never
  ublock-filters: 37563-159, 53m Δ
  ublock-badware: 8015-14, 53m Δ
  ublock-privacy: 740-0, 53m Δ
  ublock-unbreak: 2268-2, 53m Δ
  ublock-quick-fixes: 117-1, 53m Δ
  easylist: 81638-633, 53m Δ
  easyprivacy: 50264-844, 53m Δ
  urlhaus-1: 8550-0, now
  plowe-0: 3782-1, now
  DEU-0: 7283-3, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 64 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 467 ms (selfie)
 maxAssetCacheWait: 144 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  spontacts.com: 3
  onesignal.com: 1
  synexit.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by amaru7** [comment]
![Screenshot 2024-02-22 at 17-56-47 Neuigkeiten](https://github.com/uBlockOrigin/uAssets/assets/14934650/b74a6eb5-c0c0-4477-afd3-4bfe7df1c62b)

**Comment by amaru7** [comment]
> Works fine for me.

Ads are only visible, when registred and logged in. Did you do that? I still see the ads.

**Comment by amaru7** [comment]
>     * restart the system, reopen the browser, test again.

These suggestions are irrelevant or didn't fix it. Using Chrome and Firefox

**Comment by JobcenterTycoon** [comment]
Run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes,ublock-filters&manual=1 and try again. I was only able to reproduce on the logout page.

**Comment by amaru7** [comment]
> Run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes,ublock-filters&manual=1 and try again. 

That worked, thank you so much! Will this be part of the Ublock filter list in the next update?

**Comment by JobcenterTycoon** [comment]
The filter is already in the uBlock Origin filterlist but it need up to 5 hours until it's available for the users as a auto update.

**Comment by amaru7** [comment]
Awesome, Kudos!
