### ISSUE TITLE
sinonimos.de: detection

### ISSUE THREAD

**Issue by GollumArain** [uBlockOrigin/uAssets#22618]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sinonimos.de/crypto-news-a-comprehensive-overview/`

### Category

detection

### Description

I redirected from https://ctr.sh.

### Other extensions used

IDM, Bitwarden, ColorZilla

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 124918
 cosmetic: 45562
 scriptlet: 20286
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81654-12, 16m Δ
  easyprivacy: 50264-6, 16m Δ
  plowe-0: 3782-1186, 16m
  ublock-badware: 8011-142, 16m Δ
  ublock-filters: 37330-361, 16m Δ
  ublock-privacy: 744-6, 16m Δ
  ublock-quick-fixes: 122-5, 16m Δ
  ublock-unbreak: 2211-34, 16m Δ
  urlhaus-1: 8550-0, 16m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 773 ms (selfie)
 maxAssetCacheWait: 411 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  profitsfly.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(set-constant, waitTime441, 0)
  ##+js(abort-on-property-read, adbDetected)
```
</details>

**Comment by D4niloMR** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/discussions/17361
