### ISSUE TITLE
[nsfw] ebaticalfel.com: detection

### ISSUE THREAD

**Issue by AnonDSide** [uBlockOrigin/uAssets#22613]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ebaticalfel.com/s?pX0v`

### Category

detection

### Description

Before this uBo can skip the survey, but it detected 

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240223_025948_edit_9595967144150](https://github.com/uBlockOrigin/uAssets/assets/160940482/8017bb83-06e8-41a9-ad21-61a86113e403)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 126287
 cosmetic: 37249
 scriptlet: 18978
 html: 1816
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37920-302, 1h.21m Δ
  ublock-badware: 8009-14, 1h.21m Δ
  ublock-privacy: 740-1, 1h.21m Δ
  ublock-unbreak: 2273-5, 1h.21m Δ
  ublock-quick-fixes: 117-9, 1h.21m Δ
  adguard-mobile: 9115-178, now
  easylist: 81638-16545, 1h.21m Δ
  easyprivacy: 50264-872, 1h.21m Δ
  urlhaus-1: 8550-0, now
  plowe-0: 3782-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 502 ms (selfie)
 maxAssetCacheWait: 139 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  dfdgfruitie.xyz: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Is there any real content? I just see spam even when i bypass the anti adblock.

**Comment by ItsProfessional** [comment]
It's a shortener. Continue here #17361 

We've had duplicate before: https://github.com/uBlockOrigin/uAssets/issues/22602, https://github.com/uBlockOrigin/uAssets/issues/22609
