### ISSUE TITLE
tutorialspoint.com: breakage

### ISSUE THREAD

**Issue by Julienraptor01** [uBlockOrigin/uAssets#22621]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tutorialspoint.com/oracle_terminal_online.php`

### Category

breakage

### Description

The result panel does not appear when filters are enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

ubo filters enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/49841713/1b6f56fc-3486-4ccd-81e3-f72016cc681a)

ubo filters disabled
![image](https://github.com/uBlockOrigin/uAssets/assets/49841713/4837fb6e-4059-42c7-9acc-2bedcdf6d281)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 151716
 cosmetic: 206677
 scriptlet: 32007
 html: 2069
listset (total-discarded, last-updated):
 added:
  adguard-social: 22198-851, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 50103-3883, 27m
  fanboy-social: 16173-25, 27m
  ublock-annoyances: 6743-1008, 27m Δ
  adguard-cookies: 28863-67, now
  ublock-cookies-adguard: 961-0, 27m
  adguard-popup-overlays: 27021-1622, now
  adguard-mobile-app-banners: 5065-1079, now
  adguard-other-annoyances: 14217-339, now
  adguard-widgets: 2442-1, now
  easylist-annoyances: 4381-124, 27m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37568-527, 27m Δ
  ublock-badware: 8015-14, 27m Δ
  ublock-privacy: 740-0, 27m Δ
  ublock-unbreak: 2268-2, 27m Δ
  ublock-quick-fixes: 119-1, 27m Δ
  easylist: 81680-967, 27m Δ
  easyprivacy: 50264-1193, 27m Δ
  urlhaus-1: 9095-0, 27m
  plowe-0: 3782-1, now
  FRA-0: 22637-129, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 816 ms (selfie)
 maxAssetCacheWait: 312 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 no-cosmetic-filtering: false
 network:
  adpushup.com: 1
  adrecover.com: 1
  google-analytics.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `tutorialspoint.com##.panel-htop.layout-panel-east` in EL

@ryanbr

**Comment by Julienraptor01** [comment]
Thanks for reacting so fast 👍
