### ISSUE TITLE
linkedin.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#22627]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.linkedin.com/company/starbucks?trk=public_jobs_topcard-org-name`

### Category

privacy

### Description

The site redirects outbound links via `https://www.linkedin.com/redir/redirect?url={destination}`.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b0
Firefox: 123
filterset (summary):
 network: 125107
 cosmetic: 45552
 scriptlet: 18961
 html: 1782
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37585-106, 49m Δ
  ublock-badware: 8015-14, 49m Δ
  ublock-privacy: 740-0, 49m Δ
  ublock-unbreak: 2268-2, 49m Δ
  ublock-quick-fixes: 120-11, 49m Δ
  easylist: 81680-250, 49m Δ
  easyprivacy: 50264-55, 49m Δ
  urlhaus-1: 8725-0, 16m
  plowe-0: 3782-1187, now
filterset (user): [array of 60 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 211 ms (selfie)
 maxAssetCacheWait: 134 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  linkedin.com: 2
```
</details>

**Comment by mapx-** [comment]
> The site redirects outbound links

example of such link ?

**Comment by mapx-** [comment]
weird .. still not seeing something like that

**Comment by stephenhawk8054** [comment]
> weird .. still not seeing something like that

It's at the description at the top, it shows normal URL for you when hovering over?

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/3c88a96b-3bd6-471e-8b99-393b2f4251dc)

**Comment by mapx-** [comment]
well .. I get redir link only when I'm logged off linkedin

The filter above is working fine
