### ISSUE TITLE
indiatimes group: breakage

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#22628]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://navbharattimes.indiatimes.com/metro/delhi/politics/aap-congress-seat-sharing-formula-final-know-equation-arvind-kejriwal-party-how-caught-congress-vote/articleshow/107948509.cms
https://marathi.indiatimes.com/maharashtra/pune-news/mahayuti-campaign-for-lok-sabha-election-from-baramati-chief-minister-deputy-chief-minister-in-baramati-on-march-2/articleshow/107948241.cms
https://vijaykarnataka.com/news/mandya/wait-and-see-about-mandya-bjp-ticket-says-mp-sumalatha/articleshow/107949425.cms
https://telugu.samayam.com/telangana/hyderabad/patancheru-police-explained-lasya-nanditha-car-accident-reasons-and-case-registered-on-pa-akash/articleshow/107948859.cms
https://tamil.samayam.com/tamil-cinema/movie-news/legend-saravanan-hints-about-his-second-movie-title-and-shooting/articleshow/107946289.cms
https://malayalam.samayam.com/latest-news/kerala-news/sn-junction-thripunithura-terminal-trial-run/articleshow/107949152.cms
https://eisamay.com/west-bengal-news/kolkata-news/suvendu-adhikari-bjp-leader-shares-sandeshkhali-video-criticising-sheikh-shahjahan/articleshow/107948057.cms
https://www.iamgujarat.com/world/usa-among-countries-that-give-citizenship-by-birth-of-child/articleshow/107945555.cms
```

### Description

- comments does not load
- some broken layouts/widgets not load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/20338483/546aae05-4f14-48bc-9f04-55b02d0a9ce8)
![image](https://github.com/uBlockOrigin/uAssets/assets/20338483/b47b7322-a65c-467f-bffd-ee1cbc9466da)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by Alex-302** [comment]
Fixed. But I don't see comments.
