### ISSUE TITLE
ioe.vn: breakage

### ISSUE THREAD

**Issue by gnadgnaoh** [uBlockOrigin/uAssets#22629]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://ioe.vn/oauth/login?client_id=a402e57987f74cc1&redirect_uri=https://ioe.vn/sso&state=eyJpZCI6bnVsbCwidXJpIjoiaHR0cHM6Ly9pb2Uudm4vdHJhbmctY2h1Iiwic3QiOiI2Mzg0NDMyNTk2NjAxNDI4NTciLCJydCI6ImxvZ2luIn0
```

### Description

Cannot login in ioe.vn

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 471570
 cosmetic: 248522
 scriptlet: 49714
 html: 2036
listset (total-discarded, last-updated):
 added:
  https://get.letsblock.it/list/6aa53cff-d7b6-4f67-8ddb-56151572a534.txt: 77-0, 10h.49m
  https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_ads.txt: 17083-17, 5d.3m
  https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_clickthroughs.txt: 24825-7, 5d.3m
  https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_mail_trackers.txt: 35623-3, 5d.3m
  https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_microsites.txt: 6483-1, 5d.3m
  https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers.txt: 83238-25465, 5d.3m
  https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_original_trackers.txt: 61-0, 5d.3m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2587-1, 10h.49m
  adguard-generic: 79944-10245, 1m
  adguard-mobile: 9116-143, 2m
  adguard-spyware-url: 1463-222, 2m
  adguard-spyware: 111833-54083, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37579-485, 3h.23m Δ
  ublock-badware: 8015-14, 3h.23m Δ
  ublock-privacy: 740-50, 3h.23m Δ
  ublock-unbreak: 2268-3, 3h.23m Δ
  ublock-quick-fixes: 121-1, 3h.23m Δ
  easylist: 81680-1118, 3h.23m Δ
  easyprivacy: 50264-10648, 3h.23m Δ
  urlhaus-1: 9095-0, 6h.23m
  plowe-0: 3782-16, 5d.6m
  VIE-1: 1814-0, 6h.24m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings:
 cnameUncloakProxied: true
supportStats:
 allReadyAfter: 979 ms (selfie)
 maxAssetCacheWait: 536 ms
 cacheBackend: indexedDB
 ```
</details>

**Comment by ItsProfessional** [comment]
Works fine for me.

> ```yaml
>  [17 lists not shown]: [too many]
>```

You are using a heavily customized configuration of uBO. We can't help such users. Reset uBO to defaults, test again, and if it still occurs, comment here.

**Comment by gnadgnaoh** [comment]
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125537
 cosmetic: 46711
 scriptlet: 19123
 html: 1782
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37579-106, now
  ublock-badware: 8015-14, now
  ublock-privacy: 740-0, now
  ublock-unbreak: 2268-4, now
  ublock-quick-fixes: 117-9, now
  easylist: 81654-646, now
  easyprivacy: 50264-869, now
  urlhaus-1: 8725-0, now
  plowe-0: 3782-1, now
  VIE-1: 1814-4, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2647 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB

**Comment by gnadgnaoh** [comment]
Still have this issue
Account: gnadgnaoh123
Password: gnadgnaoh123

**Comment by gnadgnaoh** [comment]
> Works fine for me.
> 
> > ```yaml
> >  [17 lists not shown]: [too many]
> > ```
> 
> You are using a heavily customized configuration of uBO. We can't help such users. Reset uBO to defaults, test again, and if it still occurs, comment here.

Please reopen issue

**Comment by D4niloMR** [comment]
Test:

```adb
ioe.vn##+js(set, fingerprint, {})
ioe.vn##+js(set, fingerprint.getCookie, noopFunc)
```

**Comment by gnadgnaoh** [comment]
> Test:
> 
> ```
> ioe.vn##+js(set, fingerprint, {})
> ioe.vn##+js(set, fingerprint.getCookie, noopFunc)
> ```

Working fine now, Thank you
