### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#2262]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.quora.com/Is-ad-tracking-creepy`

### Describe the issue

Ads visible

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: 1.16.4
- uBlock Origin version: Chrome/Stable

### Settings

Default

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
They're playing the cat and mouse game, this is the third time they did it in less than a month.

**Comment by ReyCobin** [comment]
Not removed on mobile. Here is the filter that works:
##.outer_content_box.question_page_stuff:has-text(You dismissed this ad.)
