### ISSUE TITLE
[nsfw] porndoe.com: breakage

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#22630]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://porndoe.com/watch/pd0q8j4k8j0i`
`https://porndoe.com/watch/pd3c2x9h9x8j`

### Category

breakage

### Description

There is no problem with most videos on the site. The two videos I gave as an example do not react when I press the play button. When I inactivate uBlock, the videos open after the advert. 
In the thumbnails of the videos below, normally when I move the mouse over it, it shows excerpts from the video, but this does not happen when uBlock is active.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 126587
 cosmetic: 55342
 scriptlet: 20732
 html: 1782
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37586-154, 7m Δ
  ublock-badware: 8000-14, 7m Δ
  ublock-privacy: 740-0, 7m Δ
  ublock-unbreak: 2278-2, 7m Δ
  ublock-quick-fixes: 121-1, 7m Δ
  easylist: 81686-650, 7m Δ
  easyprivacy: 50264-840, 7m Δ
  urlhaus-1: 8725-0, 7m
  plowe-0: 3782-1, 6m
  TUR-0: 13138-63, 6m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 479 ms
 maxAssetCacheWait: 235 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  porndoe.com: 7
  googletagmanager.com: 1
  tbpot.com: 1
 extended:
  ##.player-right
  ##.-h-ticker
  ##.\-f-banners
  ##.below-video
  ##.vpr-section
  ##a[href*=".com/track/"]
  ##.advertisement-box
  ##+js(abort-on-property-read, open)
  ##+js(addEventListener-defuser, click, pop_under)
  ##+js(no-setTimeout-if, location.href, 500)
  ##+js(abort-on-property-read, ExoLoader)
```
</details>

**Comment by dportvine** [comment]
Same problem. Video don't react when I press the play button. `https://porndoe.com/watch/pd0q8j4k8j0i`
