### ISSUE TITLE
justwatch.com: nuisance

### ISSUE THREAD

**Issue by marior12346** [uBlockOrigin/uAssets#22632]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.justwatch.com/it`

### Category

nuisance

### Description

Sponsors among the contents

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (184)](https://github.com/uBlockOrigin/uAssets/assets/157696146/08e13df2-20a6-4807-9a4a-cb30470e26a7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 131201
 cosmetic: 99504
 scriptlet: 20849
 html: 1782
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1463-106, 1d.11h.33m
  adguard-social: 22197-34, 1d.11h.32m
  adguard-cookies: 28855-41, 1d.11h.32m
  ublock-cookies-adguard: 944-0, 5d.5h.18m
 default:
  user-filters: 1-0, never
  ublock-filters: 37584-135, 13m Δ
  ublock-badware: 8005-14, 13m Δ
  ublock-privacy: 740-0, 13m Δ
  ublock-unbreak: 2280-3, 13m Δ
  ublock-quick-fixes: 121-1, 13m Δ
  easylist: 81714-639, 13m Δ
  easyprivacy: 50264-869, 13m Δ
  urlhaus-1: 9095-0, 11h.24m
  plowe-0: 3782-1, 5h.6m
  ITA-0: 8306-19, 11h.25m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 561 ms
 maxAssetCacheWait: 285 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  justwatch.com: 7
  doubleclick.net: 2
  tw.cx: 1
  usercentrics.eu: 5
```
</details>

**Comment by marior12346** [comment]
If you go into any movie if you go a little bit further down there will be the sponsor again

![Screenshot (185)](https://github.com/uBlockOrigin/uAssets/assets/157696146/9ecc510f-32b5-4616-97c8-5c245b52b09b)

**Comment by stephenhawk8054** [comment]
```adb
justwatch.com##.sponsored-recommendation
```

@ryanbr

**Comment by rakleed** [comment]
Ad (promoted) on `https://www.justwatch.com/us/tv-show/cyberpunk-edgerunners`:

<details><summary>Screenshot:</summary>
<p>

![Image](https://github.com/user-attachments/assets/267dab78-5e47-4ece-b2f9-4ef4008b76e0)

</p>
</details>

<details><summary>Details</summary>
<p>

```yaml
uBlock Origin: 1.62.0
Chromium: 134
filterset (summary):
 network: 196425
 cosmetic: 275540
 scriptlet: 61555
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-badware: null
 added:
  adguard-generic: 100010-5828, 19m
  adguard-mobile: 10839-25, 19m
  adguard-spyware-url: 2023-136, 19m
  adguard-cookies: 33641-91, 19m
  ublock-cookies-adguard: 3759-21, 19m
  fanboy-cookiemonster: 44543-3712, 19m
  ublock-cookies-easylist: 3759-3759, 19m
  adguard-social: 23774-822, 19m
  fanboy-social: 16645-11, 19m
  adguard-popup-overlays: 28957-2340, 14m
  adguard-mobile-app-banners: 5932-22, 14m
  adguard-other-annoyances: 14747-420, 14m
  [8 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40546-127, 19m
  ublock-privacy: 2757-33, 19m
  ublock-unbreak: 2573-2, 19m
  ublock-quick-fixes: 256-1, 19m
  easylist: 69880-628, 19m
  easyprivacy: 53415-869, 19m
  urlhaus-1: 25800-0, 19m
  plowe-0: 3464-84, 19m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 133 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  ads-twitter.com: 1
  clarity.ms: 1
  facebook.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  sc-static.net: 1
  sentry.io: 2
  tiktok.com: 1
  tw.cx: 1
  yieldlove.com: 1
 extended:
  ##.mobile-banner
  ##.consent-banner
  ##.ad-unit:not(.text-ad):not(.textads):not([style^="width: 1px; …
  ##.ad-unit:not(.textads)
  ##.jw-ad
  #@#.ad-unit
``` 

</p>
</details>

**Comment by crafty991** [comment]
@stephenhawk8054 The problem has resurfaced

**Comment by stephenhawk8054** [comment]
What problem? Please give exact link where the issue occurs and screenshot what the issues are. We have to resolve many different issues everyday. We can't remember exactly the details in each issue.

**Comment by crafty991** [comment]
> What problem? Please give exact link where the issue occurs and screenshot what the issues are. We have to resolve many different issues everyday. We can't remember exactly the details in each issue.

Go to https://www.justwatch.com/it after logging in.
Or go to https://www.justwatch.com/it/serie-tv/ted-lasso without logging in.

<details>
<summary>Screenshot(s)</summary>

<img width="1917" height="880" alt="Image" src="https://github.com/user-attachments/assets/a5f3c81e-8fa3-41a2-9bba-d26e97a511ab" />

https://github.com/user-attachments/assets/4ae299d6-efc4-49e7-b549-06eedc8a1b9a

</details>
