### ISSUE TITLE
speedtest.net now taunts blockers with whitelist instructions

### ISSUE THREAD

**Issue by muscled** [uBlockOrigin/uAssets#2263]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.speedtest.net/`

### Describe the issue

An overlay over the functional interactive portion of the site appears with whitelist items one is directed to add to a filterlist.

### Screenshot(s)

<img width="1000" alt="screen shot 2018-05-13 at 12 04 44 am" src="https://user-images.githubusercontent.com/39233185/39964827-eb8707a4-5641-11e8-88cd-98b70373e254.png">
 

### Versions

- Browser/version: waterfox 56.1.0
- uBlock Origin version: v1.16.4

### Settings
<img width="187" alt="red gnome army liberation" src="https://user-images.githubusercontent.com/39233185/39964841-18c01940-5642-11e8-8e7c-6a47266ac328.png">

<img width="303" alt="gnome world domination" src="https://user-images.githubusercontent.com/39233185/39964842-1be18154-5642-11e8-969e-41dd3f17f678.png">

### Notes

reloaded page using ub logger
peered into http://b.cdnst.net/javascript/speedtest-main.js?v=83b94bf3403e95bf129d7e3539d55a2c
when I returned to the page the adblock taunt had disappeared though I had changed nothing

**Comment by uBlock-user** [comment]
`speedtest.net##script:inject(set-constant.js, isBlocked, false)`
