### ISSUE TITLE
Suggestion: Make a filterlist with very low expiry time

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#2264]
Some websites are playing the cat and mouse game. A filter-list for these specific websites would be nice, with low expiry time so user receives the update as fast as possible.

**Comment by smed79** [comment]
see https://forums.lanik.us/viewtopic.php?f=23&t=40427

**Comment by jspenguin2017** [comment]
The owner of RawGit offered to host the filters, but they will strictly update once a day which means newest commit won't be pulled even if you manually initiate an update.

**Comment by jspenguin2017** [comment]
100Mbps is huge, it is ~30TB per month if unthrottled, which would cost $3600 with Google App Engine.

**Comment by ReyCobin** [comment]
Great than. If you can manage, its fine. If not, inform me, I'll arrange the server and the bandwidth. 
I estimate around 40TB a month (including DDOS's).

**Comment by uBlock-user** [comment]
Just host it on Github in a separate list which is optional for users, so they will need to import it and that way it won't have every user subscribed by default.

**Comment by jspenguin2017** [comment]
If you get DDoS'ed, your server goes down, period. Big DDoS can generate 600Gbps traffics, you just cannot defend that with $5 servers. Scaleway has built-in DDoS protection from Online.net, not sure how effective that is though. 

I get 50k requests on my mirror server, the average file size is around 10KB compressed, the traffic is about 50GB per month.

**Comment by ReyCobin** [comment]
Dont want to get kicked by GitHub. They are probably angry that we host the general filter lists here. Better not risk any more :face_with_head_bandage:

**Comment by smed79** [comment]
Maybe @gorhill consider adding a feature to define the interval of the update by the user.

**Comment by geoffdutton** [comment]
What about hosting it on something like https://surge.sh/ and if necessary putting https://www.cloudflare.com/ in front of it?
