### ISSUE TITLE
sonixgvn.net: detection

### ISSUE THREAD

**Issue by Neptune-mk2** [uBlockOrigin/uAssets#22648]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sonixgvn.net/`

### Category

detection

### Description

Anti-adblock goes off a few seconds after accessing the site, I tried to manually block the anti-adblock banner using the picker tool but was unsuccessful.

### Other extensions used

Bitwarden
TranslateWebPages
SearchByImage
DontAcceptImageWebP
WebArchives

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/34612088/23499be8-4789-4492-bf5b-4970507ef2ec)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 95184
 cosmetic: 91956
 scriptlet: 35640
 html: 1783
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  adguard-generic: 79840-5224, 3m
  adguard-mobile-app-banners: 5063-7, 3m
  adguard-widgets: 2443-1, 3m
  easylist-chat: 182-14, 3m
 default:
  user-filters: 10-0, never
  ublock-filters: 37575-116, 14m Δ
  ublock-badware: 8006-14, 14m Δ
  ublock-privacy: 740-0, 14m Δ
  ublock-unbreak: 2280-2, 14m Δ
  ublock-quick-fixes: 123-0, 14m Δ
  easylist: 81750-625, 14m Δ
  urlhaus-1: 9055-0, 3m
  plowe-0: 3782-1, 3m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 11 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 593 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  sonixgvn.net: 16
  doubleclick.net: 1
  ezodn.com: 2
  ezoic.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  quantserve.com: 1
 extended:
  ##.ezoic-adpicker-ad
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ##.ez-sidebar-wall
  ##.ez-sidebar-wall-ad
  ##.ez-video-wrap
  ###custom_html-4
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##+js(abort-on-stack-trace, setTimeout, ads)
  ##+js(abort-on-stack-trace, document.getElementsByTagName, adsBl…
  ##+js(addEventListener-defuser, /^PN_CREAT/, ][)
  ##+js(addEventListener-defuser, PN_BEFORE_CREATE, ][)
```
</details>

**Comment by dtantono** [comment]
@stephenhawk8054 Sorry to reopen this issue. But, it seems the newest update does not worked

<img width="833" alt="image" src="https://github.com/user-attachments/assets/a1d35310-060b-4bb7-bfeb-3754c6c74ab2">

**Comment by dtantono** [comment]
<img width="937" alt="image" src="https://github.com/user-attachments/assets/7c02c853-bc88-4a49-a6f5-83c5903c0390">
it looks like it cover a whole screen

**Comment by dtantono** [comment]
it looks like it shows black screen instead
<img width="954" alt="image" src="https://github.com/user-attachments/assets/7e56f18f-5a36-4557-97af-19ac56555921">

**Comment by moemoe900** [comment]
@stephenhawk8054 I tried to add the custom filter and it does not worked.

**Comment by moemoe900** [comment]
@ghajini Thanks for an update. But, it looks like it does not worked again

**Comment by garry-ut99** [comment]
Detection again, same like in https://github.com/uBlockOrigin/uAssets/issues/22648#issuecomment-2303617185.

**Comment by moemoe900** [comment]
it looks like there is a change within the adblock blocker layout. 
<img width="816" alt="2024-08-28_23-18" src="https://github.com/user-attachments/assets/a85c1827-12bd-422c-b363-5abab3130d65">

**Comment by moemoe900** [comment]
@mapx since this is a filehosting site. I can see that the download URL is covered by ads. Is it possible for the adblocker to not cover this element or at least make the URL visible?

**Comment by mapx-** [comment]
@moemoe900 provide specific link, explain where is the download link, add screenshot showing whatever is needed

**Comment by moemoe900** [comment]
it is not on one specific link. it is covered on whole website that host external file hosting URLs. like this one: https://sonixgvn.net/the-idolmaster-cinderella-master-067-069-chiyo-shirayuki-nanami-asari-eve-santaclaus/
Extension disabled
<img width="760" alt="2024-09-01_16-06" src="https://github.com/user-attachments/assets/359e4ff8-3c0d-4cff-bca0-c9846276435a">

Extension enabled
<img width="863" alt="2024-09-01_16-05" src="https://github.com/user-attachments/assets/26168e18-24de-4578-b191-85c4dad54750">

**Comment by moemoe900** [comment]
@mapx- it looks like the URL covered again.

**Comment by moemoe900** [comment]
I tried to remove the old script as described and add the new one one Firefox. But, it does not working

**Comment by moemoe900** [comment]
@mapx-  it looks like the adblock blocker is back again
![2024-09-27_20-44_1](https://github.com/user-attachments/assets/4a79e58c-dd91-4871-b5b1-1c0ff6dea2f9)

**Comment by dnet890** [comment]
I know it happened 2 years ago. But, the issue is different. So, when I want to go to this site and download something. the countdown stopped and I must disable the extension. What do you think?

<img width="1342" height="531" alt="Image" src="https://github.com/user-attachments/assets/a8d1fb4b-7451-4d9b-a91d-cb61c7a99db4" />

**Comment by stephenhawk8054** [comment]
> the issue is different.

We said in the prerequisites

> - [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.

Comment in the old issue threads even when they are closed or even if you have a different problem.
--

**Comment by dnet890** [comment]
@stephenhawk8054 noted for that. So, since I suspect the website blacklisting adblocker again for this time. What is your opinion?
