### ISSUE TITLE
whatsnewonnetflix.com: nuisance

### ISSUE THREAD

**Issue by ayathedoggo** [uBlockOrigin/uAssets#22644]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://whatsnewonnetflix.com/norway/454/the-blacklist-2018`

### Category

nuisance

### Description

Chatbot widget after a few seconds of being on the site. All filters supposed to block this enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 138125
 cosmetic: 200781
 scriptlet: 29733
 html: 0
listset (total-discarded, last-updated):
 added:
  NOR-0: 3884-2, now
  adguard-cookies: 28881-33, 1m
  adguard-mobile-app-banners: 5063-7, 2m
  adguard-other-annoyances: 14216-8, 2m
  adguard-popup-overlays: 27027-84, 2m
  adguard-social: 22199-878, 2m
  adguard-widgets: 2443-3, 2m
  easylist-annoyances: 4389-244, 1m
  easylist-chat: 182-14, now
  easylist-newsletters: 7027-494, now
  easylist-notifications: 2948-1472, 1m
  fanboy-cookiemonster: 50134-3844, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 50-6, never
  easylist: 81750-71, 1h.20m Δ
  easyprivacy: 50275-120, 1h.20m Δ
  plowe-0: 3782-1188, now
  ublock-badware: 8002-142, 1h.20m Δ
  ublock-filters: 37359-714, 1h.20m Δ
  ublock-privacy: 744-8, 1h.20m Δ
  ublock-quick-fixes: 126-4, 1h.20m Δ
  ublock-unbreak: 2223-37, 1h.20m Δ
  urlhaus-1: 9055-0, now
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 732 ms (selfie)
 maxAssetCacheWait: 304 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
report at easylist or adguard repository
