### ISSUE TITLE
jayservicestuff.com: breakage

### ISSUE THREAD

**Issue by DoktorDementor** [uBlockOrigin/uAssets#22645]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jayservicestuff.com/nbonyiyd5u5l`

### Category

breakage

### Description

The above mentioned page is the one I am redirected to when I click on a Voe.sx link, unfortunately the video does not play, when I press the play button I only see a spinning loading circle and nothing happens.

### Other extensions used

Noscript

### Screenshot(s)

![grafik](https://github.com/uBlockOrigin/uAssets/assets/161163015/6cda55d3-f65d-4845-b7b9-11341d6c3cc9)

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123.0
filterset (summary):
 network: 127798
 cosmetic: 50482
 scriptlet: 18950
 html: 1783
listset (total-discarded, last-updated):
 default:
  user-filters: 48-0, never
  ublock-filters: 37596-123, 4m
  ublock-badware: 8006-14, 4m
  ublock-privacy: 740-0, 4m
  ublock-unbreak: 2280-0, 4m Δ
  easylist: 81750-637, 4m
  easyprivacy: 50275-872, 4m
  urlhaus-1: 9055-0, 4m
  plowe-0: 3782-1, 4m
  DEU-0: 7285-3, 4m
filterset (user): [array of 46 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 271 ms (selfie)
 maxAssetCacheWait: 119 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  ads-twitter.com: 2
  humandiminutionengaged.com: 1
  imasdk.googleapis.com: 1
  openfpcdn.io: 1
 extended:
  ##+js(no-window-open-if)
  ##+js(set-constant, console.clear, undefined)
```
</details>

**Comment by mapx-** [comment]
Disable noscript, disable ETP, test again

**Comment by DoktorDementor** [comment]
You were right,it was indeed noscript.After you press the play button a new web address called **jsdelivr.net** pops up in nocscript.How could i have missed that,sorry to have wasted your time.Thanks for your help.
