### ISSUE TITLE
tvnet.lv: breakage

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#22646]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.tvnet.lv/section/6177
```

### Description

This webpage is supposed to list news articles but Ublock hides them. Allowlisting cxense.com on this website fixes this issue.

### Other extensions used

none

### Configuration

uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 241669
 cosmetic: 58076
 scriptlet: 27331
 html: 2038
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  curben-phishing: 116628-34, 4h.33m
  fanboy-cookiemonster: 50101-17529, 2d.4h.18m
  ublock-cookies-easylist: 946-0, 2d.4h.18m
  ublock-annoyances: 6757-959, 46m Δ
 default:
  user-filters: 1-0, never
  ublock-filters: 37596-313, 46m Δ
  ublock-badware: 8006-14, 46m Δ
  ublock-privacy: 740-1, 46m Δ
  ublock-unbreak: 2280-3, 46m Δ
  ublock-quick-fixes: 123-0, 46m Δ
  easylist: 81750-16138, 46m Δ
  easyprivacy: 50275-70, 46m Δ
  urlhaus-1: 9055-0, 4h.33m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 503 ms (selfie)
 maxAssetCacheWait: 300 ms
 cacheBackend: indexedDB

**Comment by mapx-** [comment]
```
@@||cdn.cxense.com^$script,domain=tvnet.lv
@@||api.cxense.com/public/widget/$script,domain=tvnet.lv
```

@ryanbr
