### ISSUE TITLE
serieslatinoamerica.net: ads

### ISSUE THREAD

**Issue by erikovick** [uBlockOrigin/uAssets#22649]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://serieslatinoamerica.net/
```

### Description

Hello, I have searched the forum for this problem, I am new and I do not understand the mechanism well, I hope for your understanding...
1. I enter the page and when I click on the player to watch a series, the advertising banner pops up, partially corrected with the command console in Firefox at this address (`https://1wtwaq.xyz/v3/2146/mediabye -double-bonus-arg-2-0?lang=es&subid={sub1}&payout={amount}&sub1=1kq113a2mq2im`), I don't know if it can be corrected...

### Other extensions used

tab suspender

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2024-02-24 194656](https://github.com/uBlockOrigin/uAssets/assets/103467640/5d3ebf92-b642-46cc-b65e-1c6f5255483b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 192097
 cosmetic: 234825
 scriptlet: 48138
 html: 2073
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80721-5812, 3d.9m
  adguard-popup-overlays: 27006-938, 3d.10m
  adguard-mobile-app-banners: 5061-7, 3d.7m
  easylist-annoyances: 4381-25, 8m
  easylist-chat: 182-0, 8m
  fanboy-cookiemonster: 50109-256, 8m
  ublock-cookies-easylist: 985-0, 7m
  easylist-newsletters: 7027-13, 8m
  easylist-notifications: 2948-1154, 8m
  fanboy-social: 16209-23, 9m
  ublock-annoyances: 6758-1020, 1h.44m Δ
  CZE-0: 833-1, 9m
  [8 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 37575-170, 1h.44m Δ
  ublock-badware: 8006-14, 1h.44m Δ
  ublock-privacy: 740-0, 1h.44m Δ
  ublock-unbreak: 2280-0, 1h.44m Δ
  ublock-quick-fixes: 123-2, 1h.44m Δ
  easylist: 81750-1038, 1h.44m Δ
  easyprivacy: 50275-1215, 1h.44m Δ
  urlhaus-1: 9055-0, 8h.14m
  plowe-0: 3782-1, 3d.10m
  spa-0: 3893-3, 8h.14m
  spa-1: 5415-178, 3d.10m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1079 ms
 maxAssetCacheWait: 444 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
The site redirects to `https://flixlatam.com/` for me.

Test

```adb
||flixlatam.com/combined.js^$script
```

@Yuki2718 For Adguard Spanish list?

**Comment by Yuki2718** [comment]
> The site redirects to `https://flixlatam.com/` for me.
> 

Same here. @erikovick Do you actually access to `https://serieslatinoamerica.net/` without redirect? If so, which country you access from?

**Comment by Westfargo0147** [comment]
> The site redirects to `https://flixlatam.com/` for me.
> 
> Test
> 
> ```
> ||flixlatam.com/combined.js^$script
> ```
> 
> @Yuki2718 For Adguard Spanish list?

**Comment by erikovick** [comment]
> > The site redirects to `https://flixlatam.com/` for me.
> 
> Same here. @erikovick Do you actually access to `https://serieslatinoamerica.net/` without redirect? If so, which country you access from?
Well, as I say, it's partial, sometimes it works, other times it doesn't..., so I don't know what else can be done...?

**Comment by erikovick** [comment]
I don't know if this helps but this is what I have found there and it is major leagues for me
![jscript lexilatam](https://github.com/uBlockOrigin/uAssets/assets/103467640/d6b80686-7adf-4504-bee6-7d5c84215b3c)

**Comment by Yuki2718** [comment]
So you are not redirected to `https://flixlatam.com/`? Where you access from?

**Comment by mapx-** [comment]
even using an EC ip I'm redirected to flixlatam èage

**Comment by erikovick** [comment]
> even using an EC ip I'm redirected to flixlatam èage

Like I say, sometimes it works for me, other times it doesn't... that's why I created the thread

**Comment by D4niloMR** [comment]
I get a preroll on `https://embedsito.net/video/tt21927720-1x01/`

This filter works for you?

`||embedsito.net/static/vast`

**Comment by erikovick** [comment]
> I get a preroll on `https://embedsito.net/video/tt21927720-1x01/`
> 
> This filter works for you?
> 
> ```
> ||embedsito.net/static/vast
> ```

I'm going to try it and see how it works

**Comment by Yuki2718** [comment]
Yep, same with Ecuador VPN

**Comment by erikovick** [comment]
> Yep, same with Ecuador VPN

I've tested this 3 

||https://1wtwaq.xyz/v3/2146/mediabye-double-bonus-arg-2-0?lang=es&subid={sub1}&payout={amount}&sub1=1kq113a2mq2im

||flixlatam.com/combined.js^$script

||1wtwaq.xyz^$script

And they have worked for me for now

**Comment by D4niloMR** [comment]
> I've tested this 3
> 
> ||[https://1wtwaq.xyz/v3/2146/mediabye-double-bonus-arg-2-0?lang=es&subid={sub1}&payout={amount}&sub1=1kq113a2mq2im](https://1wtwaq.xyz/v3/2146/mediabye-double-bonus-arg-2-0?lang=es&subid=%7Bsub1%7D&payout=%7Bamount%7D&sub1=1kq113a2mq2im)
> 
> ||flixlatam.com/combined.js^$script
> 
> ||1wtwaq.xyz^$script
> 
> And they have worked for me for now

Already blocked in filter lists. 

---

You get the ad in the embedded player? if you clear the cookies the ad will come back again.

Ad url: `https://embedsito.net/static/vast_1win.xml`

**Comment by Yuki2718** [comment]
@D4niloMR `embedsito.net` has no traffic and won't be added to AG Spanish. You can add the rule to our filters.

**Comment by erikovick** [comment]
> > He probado estos 3 
> > `||https://1wtwaq.xyz/v3/2146/mediabye-double-bonus-arg-2-0?lang=es&subid={sub1}&payout={amount}&sub1=1kq113a2mq2im`
> > `||flixlatam.com/combined.js^$script`
> > `||1wtwaq.xyz^$script`
> > Y por ahora me han funcionado
> 
> Ya bloqueado en listas de filtros.
> 
> ¿Te aparece el anuncio en el reproductor integrado? Si borra las cookies, el anuncio volverá a aparecer.
> 
> Si es así, borre las cookies y pruebe este filtro: [ #22649 (comentario) ](https://github.com/uBlockOrigin/uAssets/issues/22649#issuecomment-1963074208)
> 
> URL del anuncio: `https://embedsito.net/static/vast_1win.xml`

in the easy list i guess?
