### ISSUE TITLE
warcraftlogs.com: nuisance

### ISSUE THREAD

**Issue by Timmaykc** [uBlockOrigin/uAssets#22654]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.warcraftlogs.com/`

### Category

nuisance

### Description

It has donate ads throughout the site, some are very annoying and cut off the content on the page, others are just at the bottom.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/114791068/518df190-4e31-4841-837d-e342f90ed950)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 125611
 cosmetic: 45613
 scriptlet: 20293
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 81761-13, now
  easyprivacy: 50278-6, now
  plowe-0: 3782-1186, now
  ublock-badware: 8002-142, now
  ublock-filters: 37361-363, now
  ublock-privacy: 743-6, now
  ublock-quick-fixes: 126-4, now
  ublock-unbreak: 2223-34, now
  urlhaus-1: 9145-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 973 ms (selfie)
 maxAssetCacheWait: 346 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  btloader.com: 1
  googletagmanager.com: 1
  intergient.com: 1
  sentry.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Add this as your custom filter: `warcraftlogs.com##.playwire-ad`

**Comment by Timmaykc** [comment]
Thank you!
