### ISSUE TITLE
aerlive.ro: breakage

### ISSUE THREAD

**Issue by Coosminn** [uBlockOrigin/uAssets#22659]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aerlive.ro/?city=BUC`

### Category

breakage

### Description

the map in the center of the site, which is supposed to show all the stations data, is not loading when ublock origin is turned on.

### Other extensions used

none that would conflict with a site (flagfox, copy plaintext, etc.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 362088
 cosmetic: 248228
 scriptlet: 49516
 html: 2038
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79840-5147, now
  adguard-mobile: 9117-141, now
  adguard-spyware-url: 1463-107, now
  adguard-spyware: 111835-32669, now
  block-lan: 61-0, now
  curben-phishing: 116335-34, 1h.18m
  adguard-social: 22199-861, now
  adguard-cookies: 28881-68, now
  ublock-cookies-adguard: 993-0, now
  adguard-popup-overlays: 27027-1688, now
  adguard-mobile-app-banners: 5063-1079, now
  adguard-other-annoyances: 14216-335, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37597-404, 1h.18m Δ
  ublock-badware: 8006-14, 1h.18m Δ
  ublock-privacy: 739-0, 1h.18m Δ
  ublock-unbreak: 2280-2, 1h.18m Δ
  ublock-quick-fixes: 123-0, 1h.18m Δ
  easylist: 81761-2294, 1h.18m Δ
  easyprivacy: 50278-1121, 1h.18m Δ
  urlhaus-1: 9145-0, 1h.18m
  plowe-0: 3782-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 434 ms (selfie)
 maxAssetCacheWait: 308 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cdn-cookieyes.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
 extended:
  ##.newsletter_form
  ###cookie-law-info-bar
  ###cookie-law-info-bar ~ .cli-modal-backdrop
  ###cookie-law-info-again
  ###cookie_hdr_showagain
  ###cliSettingsPopup
```
</details>

**Comment by mapx-** [comment]
> [11 lists not shown]: [too many]

reset uBO to default settings / filter lists, test again

**Comment by Coosminn** [comment]
> reset uBO to default settings / filter lists (subscribe the regional list too: `Romanian Ad (ROad) Block List Light`), test again
already did that, same problem

**Comment by mapx-** [comment]
- go to about:preferences#privacy
- if you have standard / strict => choose custom => unselect all entries
- test again

**Comment by Coosminn** [comment]
i kinda solved it! i did absolutely nothing. now it works 2/3 times, by magic...
