### ISSUE TITLE
scribd.com: ads

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#22656]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.scribd.com/document/490608539/Werkstatt-B2-pdf
```

### Description

Ad on the top, ads between document pages, ad on the bottom right corner

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-25 120615](https://github.com/uBlockOrigin/uAssets/assets/43014154/674a4b40-eed9-438b-8292-976d65277c28)

![Screenshot 2024-02-25 120603](https://github.com/uBlockOrigin/uAssets/assets/43014154/f4f65138-a088-432b-aee5-3ec4bf5e4d32)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 241181
 cosmetic: 89993
 scriptlet: 23694
 html: 1784
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  curben-phishing: 116335-34, 24m
  fanboy-cookiemonster: 50146-191, 21m
  ublock-cookies-easylist: 988-0, 25m
 default:
  user-filters: 1-0, never
  ublock-filters: 37597-116, 24m
  ublock-badware: 8006-14, 24m
  ublock-privacy: 739-0, 24m
  ublock-unbreak: 2280-2, 24m
  ublock-quick-fixes: 123-0, 21m Δ
  easylist: 81761-258, 25m
  easyprivacy: 50278-50, 25m
  urlhaus-1: 9145-0, 24m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1085 ms
 maxAssetCacheWait: 532 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
it seems to be self promotion

**Comment by stephenhawk8054** [comment]
You can add these:

```adb
scribd.com##section.body > div[class^="GridContainer-module_wrapper"]:style(padding-top: 0px !important;)
scribd.com##[data-testid="bottom-right-mrec"]
scribd.com##[data-testid="desktop-leaderboard"]
scribd.com##[data-testid="sticky-wrapper"]
scribd.com##.between_page_portal_root
scribd.com##.list_content_wrapper > li:not([data-e2e])
scribd.com##.wrapper__doc_page_shared_recommender_list > a[href]:not([data-e2e])
```

**Comment by Yuki2718** [comment]
Self-promotion is out-of-scope for adblocking filters. Enable either EasyList – Other Annoyances or AdGuard – Other Annoyances.

**Comment by Yuki2718** [comment]
@stephenhawk8054 
Are
```
scribd.com##.list_content_wrapper > li:not([data-e2e])
scribd.com##.wrapper__doc_page_shared_recommender_list > a[href]:not([data-e2e])
```
on the same page? I don't see them.

**Comment by Yuki2718** [comment]
@gorhill The picker is broken only on Chrome.

**Comment by gorhill** [comment]
> The picker is broken only on Chrome

Broken how and where?

**Comment by Yuki2718** [comment]
> Broken how and where?

After choosing the picker  it never opens on my end.

**Comment by gwarser** [comment]
Works fine here.

**Comment by gorhill** [comment]
> Works fine here.

Also can't reproduce, Chromium or Firefox.

**Comment by Yuki2718** [comment]
Okay, apparently something in My filters is causing the problem. Not directly related, but if I disable My filters, the picker icon disappered. Is this intended?

**Comment by gorhill** [comment]
> if I disable My filters, the picker icon disappered. Is this intended?

Yes: <https://github.com/gorhill/uBlock/commit/bc641fc024>

**Comment by Yuki2718** [comment]
yeah, I can reproduce. Not sure if I had this turend on and disabled on checking filters.

**Comment by gorhill** [comment]
Still can't reproduce after enable _"uBlock filters -- Annoyances"_.

**Comment by D4niloMR** [comment]
> @gorhill i see why it happens, enable ublock annoyances which has this filter `scribd.com##+js(aeld, /^(mouseout|mouseleave)$/)`
> 
> which causes element picker to not act when triggered, is this bug?

I can reproduce.

**Comment by gorhill** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/585534/9734354d-7334-4e65-93c9-627ecdbf3cc9)

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/8a0531cc-f7f8-434a-88fd-729b8ac31544)

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/12f212d6-c88e-4107-b9ba-a724d394a261)

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 Are
> 
> ```
> scribd.com##.list_content_wrapper > li:not([data-e2e])
> scribd.com##.wrapper__doc_page_shared_recommender_list > a[href]:not([data-e2e])
> ```
> 
> on the same page? I don't see them.

@Yuki2718 It's at the right sidebar where it lists other (related?) file links. At the top and among them when scrolling are the self-promotions.

**Comment by Yuki2718** [comment]
> It's at the right sidebar where it lists other (related?) file links. At the top and among them when scrolling are the self-promotions.

I see the parent element, but on my end they are always 0 hit for some reason.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/26046

@Yuki2718 For EL?

```adb
scribd.com##.between_page_portal_root
scribd.com###sidebar > div:has([data-e2e^="dismissible-ad-header"])
```

**Comment by Yuki2718** [comment]
Done

**Comment by HelloIamarandomperson** [comment]
Not sure if this is should be here but SCRIBD seems to have a thing where you have to wait 10 seconds before seeing something (Supposed to be an ad but obv's its being blocked) The text is clearly there so there should be some sort of fix that can be added to annoyances to remove the delay, I have a fix using a different extentinon but its inconsistent.

**Comment by stephenhawk8054** [comment]
Please give exact URL.

**Comment by HelloIamarandomperson** [comment]
Here you go 
https://www.scribd.com/document/689444152/W6-Midterm-She-is-Water-Story

It's appearance is very unstable for me, I don't know why exactly, but it should look like this
![image](https://github.com/user-attachments/assets/baf17d39-9bb9-47fd-9f86-ef0bb3974719)

scroll up and down, for some reason this site decided to make it so it only appears after a few seconds on pdf pages that you could already see.

**Comment by stephenhawk8054** [comment]
Are you signed in to the site?

**Comment by HelloIamarandomperson** [comment]
no

**Comment by stephenhawk8054** [comment]
I can't reproduce. It just shows this to me

![image](https://github.com/user-attachments/assets/91a48806-869f-49fd-b868-cdaa34381ad0)

**Comment by HelloIamarandomperson** [comment]
That's weird, switched computers and still showed up, turned off other extensions and reset to factory settings, still appeared. I used firefox and chrome. Didn't matter. It couldn't have been tracking me either, used different IP's.

I figured out some combination of:
www.scribd.com##.blurred_page
www.scribd.com##.blur
www.scribd.com##[style*="filter: blur"]
www.scribd.com##[style*="backdrop-filter: blur"]
www.scribd.com##.page_missing_explanation
works.
