### ISSUE TITLE
dngz.net: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#22657]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://www.dngz.net/`

### Category

ads

### Description

Some ads exist.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/35957435/6ca4ead5-348c-409b-a80f-d6235ec74233

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 125
filterset (summary):
 network: 247874
 cosmetic: 246779
 scriptlet: 49534
 html: 2039
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79840-3905, 1m
  adguard-spyware-url: 1463-107, 1m
  adguard-spyware: 111835-1398, 1m
  adguard-social: 22199-53, 2m
  adguard-cookies: 28881-48, 2m
  ublock-cookies-adguard: 993-10, 2m
  adguard-popup-overlays: 27027-989, 2m
  adguard-other-annoyances: 14216-399, 2m
  adguard-widgets: 2443-11, 2m
  fanboy-thirdparty_social: 68-3, 2m
  easylist-annoyances: 4388-284, 2m
  easylist-chat: 182-15, 2m
  [6 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 37602-106, 1m
  ublock-badware: 8006-14, 1m
  ublock-privacy: 738-0, 1m
  ublock-unbreak: 2280-2, 1m
  ublock-quick-fixes: 113-11, 1m
  easylist: 81761-1573, 1m
  easyprivacy: 50278-32239, 1m
  urlhaus-1: 9145-0, 2m
  plowe-0: 3782-1271, 2m
  CHN-0: 25694-213, 2m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1395 ms (selfie)
 maxAssetCacheWait: 1134 ms
popupPanel:
 blocked: 1
 network:
  cnzz.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
dngz.net##.ad
dngz.net##[href^="https://promotion.aliyun.com"]
```

@cjx82630

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/955133ad04d26634c0c4d12546894ce72e1b2b5e
https://github.com/easylist/easylistchina/commit/102c7e63af94bcad4ca11110a7191b5bd2024728
