### ISSUE TITLE
[nsfw] pornhub.com: ads

### ISSUE THREAD

**Issue by soskamified** [uBlockOrigin/uAssets#22669]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`(NSFW) https://www.pornhub.com/view_video.php?viewkey=ph623af79815571`

### Category

ads

### Description

For the past week or so, each time a video page is loaded, there is a big space where an ad was originally located below the video itself and above the title. I've attempted to manually block the element, however the div element class changes each time the page is loaded, so it gets bypassed. The div class name is usually "(random string) (random string) hd clear original," and within this div is an ad element. There's probably an easy way to counteract this but I'm not sure what it is. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/145834859/235306eb-669c-4604-84b5-06d992ed48e5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 155722
 cosmetic: 246943
 scriptlet: 50328
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28882-33, now
  adguard-generic: 79257-482, now
  adguard-mobile: 9096-49, now
  adguard-mobile-app-banners: 5047-8, now
  adguard-other-annoyances: 14200-9, now
  adguard-popup-overlays: 27007-96, now
  adguard-social: 22197-881, now
  adguard-widgets: 2443-4, now
  easylist-annoyances: 4393-281, now
  easylist-chat: 182-14, now
  easylist-newsletters: 7027-501, now
  easylist-notifications: 2949-1473, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 114-6, never
  easylist: 81817-1464, now
  easyprivacy: 50277-220, now
  plowe-0: 3782-1270, now
  ublock-badware: 8002-249, now
  ublock-filters: 37377-3943, now
  ublock-privacy: 744-8, now
  ublock-quick-fixes: 126-36, now
  ublock-unbreak: 2223-102, now
  urlhaus-1: 8990-0, now
filterset (user): [array of 114 redacted]
userSettings:
 showIconBadge: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms (selfie)
 maxAssetCacheWait: 421 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 47
 network:
  pornhub.com: 7
  etahub.com: 36
  google-analytics.com: 1
  googletagmanager.com: 1
  trafficjunky.com: 2
 extended:
  ##.adsbytrafficjunky
  ##.shareTrig
  ##.js-triggerShare
  ##.share-sites-thumbs
  ##.socialIconsWrapper
  ##.logoWrapper > [href="/"]
  ##.videoPremiumBlock
  ###hd-rightColVideoPage > .clearfix:first-child
  ##.realsex
  ##.playerFlvContainer > div#pb_template[style]
  ###relatedVideosCenter > .wrapVideoBlock:has(> .videoSpiceVidsBl…
  ###jsShare
  ###pb_template
  ##a[href*="?ats="]
  ##a[href^="http://ads.trafficjunky.net/"]
  ###pb_block
  ###relatedVideosCenter > .wrapVideoBlock
  ##a[href^="https://a.adtng.com/"]
  ##+js(set-constant, page_params.holiday_promo_prem, true)
  ##+js(no-setTimeout-if, \x41\x64\x62\x6c\x6f\x63\x6b\x20\x66\x6f…
  ##+js(set-constant, abp1, 0)
  ##+js(remove-class, hasAdAlert, header)
  ##+js(no-setTimeout-if, adsbytrafficjunkycontext)
  ##+js(abort-current-script, Object.defineProperty, trafficjunky)
  ##+js(no-window-open-if)
  ##+js(set-constant, page_params.holiday_promo, true)
  ##+js(set-constant, abp1, 1)
```
</details>

**Comment by D4niloMR** [comment]
Add:

`pornhub.com##.video-wrapper > .original.clear.hd:has(.adsbytrafficjunky)`

**Comment by Rachitidk** [comment]
Livecam ads above the player, reopen.

**Comment by Rachitidk** [comment]
Ad information ads above player.

**Comment by stephenhawk8054** [comment]
I can't see it.

**Comment by Rachitidk** [comment]
> I can't see it.

![1000116533](https://github.com/user-attachments/assets/d367f2f8-4a9d-43b0-88bd-c824eb793113)

**Comment by Rachitidk** [comment]
Live cams ads came bake, ad information not solved.

**Comment by Rachitidk** [comment]
> Live cams ads came back, ad information ads not solved.

Still there

**Comment by Rachitidk** [comment]
Not fixed.
