### ISSUE TITLE
forum.iptvkalite.com: detection

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#22668]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://forum.iptvkalite.com/`

### Category

detection

### Description

AdBlock Detected !!! 

gives the warning.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 126896
 cosmetic: 55393
 scriptlet: 20725
 html: 1786
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37608-182, now
  ublock-badware: 8006-14, now
  ublock-privacy: 740-0, now
  ublock-unbreak: 2280-2, now
  ublock-quick-fixes: 123-1, now Δ
  easylist: 81761-650, now
  easyprivacy: 50277-840, now
  urlhaus-1: 8990-0, now
  plowe-0: 3782-1, now
  TUR-0: 13138-63, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 440 ms
 maxAssetCacheWait: 192 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  iptvkalite.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##+js(no-setTimeout-if, 0===o.offsetLeft&&0===o.offsetTop)
```
</details>

**Comment by punisher018** [comment]
Still gives warning. 
In UbO Log says
[forum.iptvkalite.com][abort-on-property-read ⁝ btoa] Aborted

**Comment by D4niloMR** [comment]
it works here, does `@@||forum.iptvkalite.com^$script,1p` works for you?

**Comment by punisher018** [comment]
Still doesn't working.

**Comment by D4niloMR** [comment]
Sorry, I forgot I had disabled cosmetic filtering on the site
