### ISSUE TITLE
bazar.bg: breakage

### ISSUE THREAD

**Issue by dedaznamaz** [uBlockOrigin/uAssets#22665]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bazar.bg/favorites/search`

### Category

breakage

### Description

Hello, several days ago bazar.bg changed how 
```
bazar.bg/favorites/search
bazar.bg/favorites/ads
bazar.bg/favorites/users
```

loads data. I managed to track the rule that breaks the loading of content, its 
`||fundingchoicesmessages.google.com^`
When I allow it, the pages load as they should. Probably some script detecting UBO ? Usually I fix most of issues by myself, but I can't handle this one. Thanks in advance

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Snap5](https://github.com/uBlockOrigin/uAssets/assets/114338663/5f7170d1-987c-4fd7-8feb-a561f23b10b6)
![Snap4](https://github.com/uBlockOrigin/uAssets/assets/114338663/ff963135-805b-49bc-ab7f-21064b36d0e5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 111
filterset (summary):
 network: 365783
 cosmetic: 290278
 scriptlet: 49512
 html: 2089
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77634-77634, 21m
  https://gitlab.com/DandelionSprout/adfilt/-/raw/master/ClearURLs for uBo/clear_urls_uboified.txt: 728-8, 1h.5m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 21m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 21m
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42453-1388, 21m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97322-97322, 21m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 50151-3827, 21m
  https://secure.fanboy.co.nz/r/fanboy-ultimate.txt: 212199-212141, 21m
  https://winhelp2002.mvps.org/hosts.txt: 8729-2, 21m
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, 21m
  adguard-generic: 79289-6474, 21m
  adguard-mobile: 9116-155, 21m
  [22 lists not shown]: [too many]
 default:
  user-filters: 2067-2, never
  ublock-filters: 37608-539, 1h.5m Δ
  ublock-badware: 8006-19, 1h.5m Δ
  ublock-privacy: 740-21, 1h.5m Δ
  ublock-unbreak: 2280-0, 1h.5m Δ
  easylist: 81761-1044, 1h.5m Δ
  easyprivacy: 50277-1359, 1h.5m Δ
  urlhaus-1: 8990-0, 1h.5m
  plowe-0: 3782-324, 21m
  ublock-quick-fixes: 123-3, 1h.5m Δ
filterset (user): [array of 1531 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 732 ms (selfie)
 maxAssetCacheWait: 488 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  adocean.pl: 2
  creativecdn.com: 1
  gemius.pl: 1
  google.com: 5
  googletagmanager.com: 2
  googletagservices.com: 1
  gstatic.com: 4
 extended:
  ##[data-link*="/delivery/discount"]
  ##iframe[name="googlefcPresent"]
  ###fb-root:not(body):not(html)
```
</details>

**Comment by mapx-** [comment]
Do we need an account ?
Do we need to search for some item ?
provide all the steps, words to insert / search etc

**Comment by dportvine** [comment]
I don't see the problem, use the default uBO settings.

<details>
<summary>Screen</summary>

![2024-02-25_211627](https://github.com/uBlockOrigin/uAssets/assets/111344219/0bb44942-acc0-4a31-92d6-c19e267025a1)
![2024-02-25_211639](https://github.com/uBlockOrigin/uAssets/assets/111344219/daa38a6d-149d-4efb-a76a-f6527151f2e3)
</details>

**Comment by dedaznamaz** [comment]
> Do we need an account ? Do we need to search for some item ? provide all the steps, words to insert / search etc
Yes, you need account. Nothing to search for, it's a list of favorite items. There are no steps required.

**Comment by dedaznamaz** [comment]
> I don't see the problem, use the default uBO settings.
> Screen
> 
> ![2024-02-25_211627](https://private-user-images.githubusercontent.com/111344219/307616322-0bb44942-acc0-4a31-92d6-c19e267025a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTEwMjQsIm5iZiI6MTcwODg5MDcyNCwicGF0aCI6Ii8xMTEzNDQyMTkvMzA3NjE2MzIyLTBiYjQ0OTQyLWFjYzAtNGEzMS05MmQ2LWMxOWUyNjcwMjVhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxOTUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmZmYjA5NDFjZmMyNzAwMjlmOWQ5NDdiOGVhYzI5NjRiODAwZjgzODhjM2U4ZGRhMWM0MzUxNzhkNjVjMzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O7Zj3ALYlkKYLnjIri4gSGMpxao9UfRrkxqDym1hDsk) ![2024-02-25_211639](https://private-user-images.githubusercontent.com/111344219/307616327-daa38a6d-149d-4efb-a76a-f6527151f2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTEwMjQsIm5iZiI6MTcwODg5MDcyNCwicGF0aCI6Ii8xMTEzNDQyMTkvMzA3NjE2MzI3LWRhYTM4YTZkLTE0OWQtNGVmYi1hNzZhLWY2NTI3MTUxZjJlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxOTUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzBjNDE0MzcwMWQ1NjdkY2YxOWUyNTA3OGMyZGIzNTk5NzlhMjQ1ZmZhMzVkMjBhMWEwODBhNTgyNTExNDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JWG_95zMkDulShlmkl0bvXtZhUniMubek7dbGXnvXM)

Strange, I jsut get blank page. Tomorrow I will try to dig more and provide more info.

**Comment by dedaznamaz** [comment]
Ok, it seems to be Firefox issue, on Chrome everything works just fine with the same UBO settings... Still strange why it works when I allow ||fundingchoicesmessages.google.com^

**Comment by mapx-** [comment]
indeed, needing
`@@||fundingchoicesmessages.google.com^$script,domain=bazar.bg`

**Comment by dedaznamaz** [comment]
> indeed, needing `@@||fundingchoicesmessages.google.com^$script,domain=bazar.bg`

Didn't wanted to allow google trash, but I have no choice for now :(

**Comment by dedaznamaz** [comment]
Hello, you can remove the rule you added to Unbreak. It seems it was bazar.bg issue, the fixed it and it's working now without fundingchoicesmessages.
