### ISSUE TITLE
serayunews.com: ads

### ISSUE THREAD

**Issue by F640** [uBlockOrigin/uAssets#22664]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://serayunews.com/besok-kirab-dan-pentas-seni-peringati-hari-jadi-banjarnegara
```

### Description

There are ads in this website (the ad server also evades blocker)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (99)](https://github.com/uBlockOrigin/uAssets/assets/92260436/180c0ede-4560-4bc0-b734-e3f8d5a5b8fe)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125430
 cosmetic: 45621
 scriptlet: 20294
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81761-13, 7m
  easyprivacy: 50277-6, 7m
  plowe-0: 3782-1186, 7m
  ublock-badware: 8001-142, 7m
  ublock-filters: 37376-363, 7m
  ublock-privacy: 744-6, 7m
  ublock-quick-fixes: 126-35, 7m
  ublock-unbreak: 2223-34, 7m
  urlhaus-1: 8990-0, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 894 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by mapx-** [comment]
add

`||fnasmpygwa.com^$third-party`

or subscribe the russian list (the ad server is a russian one)

**Comment by mapx-** [comment]
@gmarcher
