### ISSUE TITLE
github.com: breakage

### ISSUE THREAD

**Issue by luckman212** [uBlockOrigin/uAssets#22670]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://github.com
```

### Description

Last couple of weeks I noticed when saving comments or submitting forms on GitHub, the green Submit button would dim indicating I submitted the form, but the page would not reload. I always waited a few moments and then manually refreshed the page and saw that the content had actually been saved.

Finally today I decided to open the console to check, and I saw requests being blocked (by uBO), to 2 domains

```
api.github.com
collector.github.com
```

I'm not 100% sure but I think somehow these blocked requests (specifically `api.github.com`) are interfering with the form submission. It seemed to be much more likely to succeed if I added `@@||api.github.com^` to **My filters** and `* api.github.com * allow` to **My rules**

### Other extensions used

- Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/1992842/db66ff13-f3cd-46eb-b50f-79532785d822)

![image](https://github.com/uBlockOrigin/uAssets/assets/1992842/fee174b8-56a4-4084-8d37-608c587d29c0)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125473
 cosmetic: 45622
 scriptlet: 20294
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81804-13, 2h.41m
  easyprivacy: 50277-6, 2h.41m
  plowe-0: 3782-1186, 2h.41m
  ublock-badware: 8002-142, 2h.42m
  ublock-filters: 37376-363, 2h.42m
  ublock-privacy: 744-6, 2h.42m
  ublock-quick-fixes: 126-35, 2h.42m
  ublock-unbreak: 2223-34, 2h.42m
  urlhaus-1: 8990-0, 4h.1m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 362 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 47
 network:
  github.com: 47

```
</details>

**Comment by mapx-** [comment]
provide the complete steps / example to reproduce your issue

**Comment by luckman212** [comment]
I will try to make 100% reproducible steps and/or a screen recording.
