### ISSUE TITLE
rmcbfmplay.com: detection

### ISSUE THREAD

**Issue by bben72** [uBlockOrigin/uAssets#22679]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rmcbfmplay.com/`

### Category

detection 

### Description

anti adblock on this domain works again, even with this script used : 
||estat.com^$script,3p,redirect-rule=noopjs,domain=rmcbfmplay.com

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/159134772/3eadb0dc-d1da-480a-8577-04135c5c4dca)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 366081
 cosmetic: 201900
 scriptlet: 49671
 html: 2040
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt: 0-0, 24m
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 12-0, never
  fanboy-thirdparty_social: 68-1, now
  fanboy-social: 16056-11490, now
  dpollock-0: 11649-465, now
  adguard-generic: 79340-5735, 11m
  fanboy-cookiemonster: 50161-19804, now
  adguard-mobile: 9095-172, 12m
  ublock-annoyances: 6770-1033, 24m Δ
  adguard-social: 22205-1555, now
  adguard-spyware-url: 1467-106, now
  block-lan: 61-0, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37625-757, 24m Δ
  ublock-badware: 8007-14, 24m Δ
  ublock-privacy: 741-1, 24m Δ
  ublock-unbreak: 2280-2, 24m Δ
  easylist: 81860-17065, 24m Δ
  easyprivacy: 50283-1283, 24m Δ
  plowe-0: 3783-1, now
  FRA-0: 22661-3086, now
  urlhaus-1: 8725-0, 1h.26m
  ublock-quick-fixes: 120-1, 24m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 42 redacted]
 removed:
  about-scheme
  edge-scheme
  moz-extension-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1444 ms (selfie)
 maxAssetCacheWait: 869 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  estat.com: 1
  facebook.net: 1
  fwmrm.net: 2
  privacy-center.org: 1
  xiti.com: 1
 extended:
  ##+js(prevent-fetch, /www3\.doubleclick\.net|tagger\.opecloud\.c…
  ##html:style(overflow:auto!important)
```
</details>

**Comment by D4niloMR** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/issues/22360

**Comment by bben72** [comment]
It works nows. Thank You !
