### ISSUE TITLE
crystalmark.info: badware

### ISSUE THREAD

**Issue by qupo1** [uBlockOrigin/uAssets#22672]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://crystalmark.info/download/gmo/*

for example:
https://crystalmark.info/download/gmo/CrystalDiskInfo9_2_3AdsAoi.exe
https://crystalmark.info/download/gmo/CrystalDiskInfo9_2_3Ads.exe
```

### Description

These links distribute software installers which contains japanese adware "E-START" (aka j-word).
Users can get original installers without adware from [sourceforge](https://sourceforge.net/projects/crystaldiskinfo/). So please block these links to protect people from adware.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b0
Firefox: 125
filterset (summary):
 network: 350971
 cosmetic: 252490
 scriptlet: 49624
 html: 2040
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/Yuki2718/adblock2/main/japanese/jpf-plus.txt: 849-6, 1d.21h.17m
  adguard-generic: 79840-3908, 20h.15m
  adguard-spyware-url: 1463-107, 20h.16m
  adguard-spyware: 111835-1399, 20h.16m
  block-lan: 56-0, 21d.20h.48m
  curben-phishing: 104769-39, 12m
  adguard-social: 22199-53, 20h.16m
  adguard-cookies: 28881-48, 20h.15m
  ublock-cookies-adguard: 961-7, 3d.20h.58m
  adguard-popup-overlays: 27027-995, 20h.15m
  adguard-mobile-app-banners: 5063-20, 20h.15m
  adguard-other-annoyances: 14216-410, 20h.14m
  [11 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  ublock-filters: 37618-109, 4h.14m Δ
  ublock-badware: 8007-15, 4h.14m Δ
  ublock-privacy: 740-0, 4h.14m Δ
  ublock-unbreak: 2281-2, 4h.14m Δ
  ublock-quick-fixes: 123-41, 4h.14m Δ
  easylist: 81820-1579, 4h.14m Δ
  easyprivacy: 50280-32239, 4h.14m Δ
  urlhaus-1: 9160-0, 12m
  plowe-0: 3782-1623, 12m
  JPN-1: 14128-129, 20h.14m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 100 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 extensionUpdateForceReload: true
supportStats:
 allReadyAfter: 544 ms (selfie)
 maxAssetCacheWait: 402 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by JobcenterTycoon** [comment]
0 Virustotal detections https://www.virustotal.com/gui/file/410613b74b833eac47f30b31a2535a2dd244c46b79be734cb733ead58ce28243 we need a proof

**Comment by Yuki2718** [comment]
If we start to block adware, there will be infinite cases to address (I'd say Avast was an adware at least in past). The page is the official site of the software and if the dev decided to distribute adware, it's his decision. We will definitely block if this is a malware.
