### ISSUE TITLE
sxyprn.com: breakage

### ISSUE THREAD

**Issue by saboteur1000** [uBlockOrigin/uAssets#22675]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sxyprn.com/post/65db56b10feaf.html`

### Category

breakage

### Description

Online videos on this site don't play if uBlock Origin is installed.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 86
filterset (summary): 
  network: 144453
  cosmetic: 66554
  scriptlet: 20590
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1706-0, 8h.37m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, 12h.53m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8h.34m
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-2, 12h.52m
  default: 
    user-filters: 97-1, never
    RUS-0: 39801-42, 1d.17h.29m
    easylist: 81694-43, 1d.17h.30m
    easyprivacy: 50261-390, 1d.17h.31m
    plowe-0: 3782-1191, 7d.22h.35m
    ublock-badware: 7981-142, 2d.17h
    ublock-filters: 35708-234, 2d.16h.59m
    ublock-privacy: 683-90, 12h.54m
    ublock-quick-fixes: 103-2, 8h.36m
    ublock-unbreak: 2202-34, 2d.16h.58m
    urlhaus-1: 9160-0, 8h.35m
filterset (user): [array of 97 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 566 ms (selfie)
  maxAssetCacheWait: 431 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    adtng.com: 2
    bymyth.com: 1
    googletagmanager.com: 1
    kgfjrb711.com: 3
    ku42hjr2e.com: 1
    magsrv.com: 3
    static-srv.com: 1
    tapioni.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
>```yaml
>  added: 
>    https://easylist-downloads.adblockplus.org/cntblock.txt: 1706-0, 8h.37m
>    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, 12h.53m
>    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8h.34m
>    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-2, 12h.52m
>```
>```yaml
>filterset (user): [array of 97 redacted]
>```

You are using a heavily customized configuration of uBO. We can't help such users. Reset uBO to default and remove all other extensions. If the problem persists, comment here.
