### ISSUE TITLE
archive.nytimes.com: nuisance

### ISSUE THREAD

**Issue by Coccocoahelper** [uBlockOrigin/uAssets#22686]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://archive.nytimes.com/www.nytimes.com/external/gigaom/2009/02/07/07gigaom-the-brave-new-world-of-open-source-game-design-37415.html`

### Category

nuisance

### Description

A cookie banner is displayed. Fixable with `archive.nytimes.com##body > div:nth-of-type(6)`.

### Other extensions used

LanguageTool,
Proton Pass,
Stylus,
ViolentMonkey,
Chromium Web Store
Lichess Tools by Siderite (only does anything on Lichess)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b0
Chromium: 121
filterset (summary):
 network: 237645
 cosmetic: 127198
 scriptlet: 26193
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1045-0, 23m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 395-3, 23m
  DEU-0: 7289-0, 23m
  curben-phishing: 104549-30, 23m
  easylist-annoyances: 4402-36, 23m
  easylist-chat: 183-0, 23m
  easylist-newsletters: 7039-17, 23m
  easylist-notifications: 2950-88, 23m
  fanboy-cookiemonster: 50176-187, 23m
  fanboy-social: 16056-16, 23m
  spa-1: 5375-75, 23m
  ublock-cookies-easylist: 1009-3, 23m
 default:
  user-filters: 14-0, never
  easylist: 81757-21, 23m
  easyprivacy: 50285-101, 23m
  plowe-0: 3783-1188, 23m
  ublock-badware: 8005-151, 23m
  ublock-filters: 37408-409, 23m
  ublock-privacy: 745-8, 23m
  ublock-quick-fixes: 109-5, 23m
  ublock-unbreak: 2223-38, 23m
  urlhaus-1: 8770-0, 23m
filterset (user): [array of 14 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2445 ms (selfie)
 maxAssetCacheWait: 1757 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  nytimes.com: 1
 extended:
  ##body:remove-class(didomi-popup-open)
  ##body:style(overflow: auto !important;)
  ##+js(json-prune, data.user)
  ##+js(json-prune-fetch-response, data.user)
  ##+js(trusted-set-cookie, purr-pref-agent, <a1<Go)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
archive.nytimes.com##body > div[style*="z-index: 2147483647"]:has(a[href="https://nytimes.com/cookie-policy/"])
```

@ryanbr
