### ISSUE TITLE
kuantokusta.pt: nuisance

### ISSUE THREAD

**Issue by Coccocoahelper** [uBlockOrigin/uAssets#22683]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kuantokusta.pt/`

### Category

nuisance

### Description

All websites using Didomi display a cookie banner, even with the Cookie Notice filter from uBO on.

### Other extensions used

LanguageTool,
Proton Pass,
Stylus,
ViolentMonkey,
Chromium Web Store
Lichess Tools by Siderite (only does anything on Lichess)
Terms of Service; Didn't Read

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b0
Chromium: 121
filterset (summary):
 network: 237639
 cosmetic: 127277
 scriptlet: 26191
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1045-0, 1m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 395-3, 1m
  DEU-0: 7289-0, 1h.1m
  curben-phishing: 104549-30, 1m
  easylist-annoyances: 4399-36, 1m
  easylist-chat: 183-0, 1m
  easylist-newsletters: 7028-17, 1m
  easylist-notifications: 2949-88, 1m
  fanboy-cookiemonster: 50161-188, 1m
  fanboy-social: 16056-16, 1m
  spa-1: 5375-75, 1m
  ublock-cookies-easylist: 1009-3, 1m
 default:
  user-filters: 10-0, never
  easylist: 81867-21, 1h.1m Δ
  easyprivacy: 50283-101, 1h.1m Δ
  plowe-0: 3783-1188, 1m
  ublock-badware: 8005-151, 1h.1m Δ
  ublock-filters: 37406-409, 1h.1m Δ
  ublock-privacy: 745-8, 1h.1m Δ
  ublock-quick-fixes: 109-5, 1h.1m Δ
  ublock-unbreak: 2223-38, 1h.1m Δ
  urlhaus-1: 8770-0, 1m
filterset (user): [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2445 ms (selfie)
 maxAssetCacheWait: 1757 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 10
 network:
  avis-verifies.com: 2
  go-mpulse.net: 2
  px-cdn.net: 2
  px-cloud.net: 2
  pxchk.net: 2
```
</details>

**Comment by D4niloMR** [comment]
Fixed, update should come in about 5 hours. If you see more cookie notices report at https://github.com/easylist/easylist

**Comment by Coccocoahelper** [comment]
@D4niloMR I'm really, REALLY sorry to ping ya, but I just found a fix:
`*###didomi-host`
`*##body:remove-class(didomi-popup-open)`
`*##body.didomi-popup-open:style(overflow: auto !important)`

**Comment by stephenhawk8054** [comment]
Don't use `*##` for `remove-class` and `style`, it would affect performance a lot. Report the sites to EasyList.

**Comment by ItsProfessional** [comment]
@Coccocoahelper Remove your filters, we fixed it in the official lists. Just update your lists.
