### ISSUE TITLE
eurotruck2.com.br: detection

### ISSUE THREAD

**Issue by Rescom** [uBlockOrigin/uAssets#22682]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.eurotruck2.com.br/`

### Category

detection

### Description

After entering the site the adblock got detected

### Other extensions used

Aha Music
Last Pass
IDM Download Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/39840955/4b9dd9ec-3393-4d3f-b1eb-c3658e855a98)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 126503
 cosmetic: 49334
 scriptlet: 20697
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 21-15, never
  easylist: 81860-13, now
  easyprivacy: 50283-6, now
  plowe-0: 3783-1187, now
  spa-1: 5386-72, now
  ublock-badware: 8003-142, now
  ublock-filters: 37394-376, now
  ublock-privacy: 745-6, now
  ublock-quick-fixes: 118-5, now
  ublock-unbreak: 2223-33, now
  urlhaus-1: 8725-0, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1333 ms
 maxAssetCacheWait: 479 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  googlesyndication.com: 2
  intellipopup.com: 1
  waust.at: 1
 extended:
  ##ins.adsbygoogle
  ###adHolder1
  ###boxAd300
  ###rotating_ad
  ###sideAdSub
  ###topad2
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 ping for `AdGuard Spanish/Portuguese` a filter can be `eurotruck2.com.br##+js(aeld, load, nextFunction)`

**Comment by Yuki2718** [comment]
This is either antiblock .org or killadblock, will be addressed in Base.
