### ISSUE TITLE
imgur.com: ads

### ISSUE THREAD

**Issue by ctyotgomrbwoaujv** [uBlockOrigin/uAssets#22684]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://imgur.com/`

### Category

ads

### Description

shows ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/5914642/8d8d37f6-014c-4ef3-8043-6bc53ae05fff)
![firefox_SgJKkc1xZh](https://github.com/uBlockOrigin/uAssets/assets/5914642/9abffdfa-919e-453c-8af4-f83e63eb1d19)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125263
 cosmetic: 45669
 scriptlet: 18985
 html: 1786
listset (total-discarded, last-updated):
 default:
  user-filters: 9-1, never
  ublock-filters: 37631-142, 1m
  ublock-badware: 8009-14, 1m
  ublock-privacy: 741-0, 1m
  ublock-unbreak: 2280-0, 1m
  ublock-quick-fixes: 106-1, 1m
  easylist: 81867-629, 1m
  easyprivacy: 50283-836, 1m
  urlhaus-1: 8770-0, 1m
  plowe-0: 3783-1, 1m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2746 ms (selfie)
 maxAssetCacheWait: 1252 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  imgur.com: 4
  amazon-adsystem.com: 1
  assemblyexchange.com: 2
  btloader.com: 1
  ccgateway.net: 1
  d3c8j8snkzfr1n.cloudfront.net: 2
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  media-lab.ai: 1
  placed.com: 1
  sascdn.com: 4
  stretchsquirrel.com: 1
  xeno-soswcrde4a-uc.a.run.app: 3
 extended:
  ##+js(set-constant, ADBLOCKED, false)
  ##+js(set-cookie, WHITELISTED_CLOSED, 1)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
imgur.com##.Post-item:has(.Post-item-external-ad)
```

@ryanbr

**Comment by stephenhawk8054** [comment]
```adb
imgur.com##a.Post-item:has(.Post-item-external-ad)
```

@ryanbr
