### ISSUE TITLE
dankmemer.lol: detection

### ISSUE THREAD

**Issue by Win-ss** [uBlockOrigin/uAssets#22692]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dankmemer.lol/freemium`

### Category

detection

### Description

Site detects that im using adblock

### Other extensions used

**Nothing relevant.**
Volume master,
Silk - Privacy Pass Client
picture in picture
return youtube dislikes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70939650/055064ce-a02a-4052-be89-eb99e4f87a3f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125185
 cosmetic: 45584
 scriptlet: 20327
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 28-6, never
  easylist: 81757-13, 1h.27m Δ
  easyprivacy: 50285-6, 1h.27m Δ
  plowe-0: 3783-1187, now
  ublock-badware: 8005-142, 1h.27m Δ
  ublock-filters: 37400-363, 1h.27m Δ
  ublock-privacy: 746-6, 1h.27m Δ
  ublock-quick-fixes: 109-5, 1h.27m Δ
  ublock-unbreak: 2223-32, 1h.27m Δ
  urlhaus-1: 8670-0, now
filterset (user): [array of 28 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 515 ms (selfie)
 maxAssetCacheWait: 65 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  nitropay.com: 2
```
</details>

**Comment by dportvine** [comment]
I can't reproduce but I can see this code.  `https://dankmemer.lol/_next/static/chunks/app/(top)/freemium/page-7c348ce99986a3fc.js`

<details>
<summary>Screen</summary>

![2024-02-27_171923](https://github.com/uBlockOrigin/uAssets/assets/111344219/cfeccdc6-0177-4f45-b573-5dc730c9090c)
</details>

**Comment by mapx-** [comment]
@Win-ss 
test this filter:

`dankmemer.lol##+js(nostif, nads)`
