### ISSUE TITLE
vnexpress.net: detection

### ISSUE THREAD

**Issue by anhduclee2006** [uBlockOrigin/uAssets#22693]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vnexpress.net/everton-duoc-tra-lai-4-diem-tai-ngoai-hang-anh-4715798.html`

### Category

detection

### Description

uBo detected

### Other extensions used

Nope

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/120443839/a856f662-f73d-4165-bcbb-3ccd2d974962)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 109
filterset (summary):
 network: 58170
 cosmetic: 102787
 scriptlet: 24043
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
 added:
  easylist-annoyances: 4402-32, 1m
  easylist-newsletters: 7041-15, 1m
  easylist-notifications: 2950-87, 1m
  fanboy-cookiemonster: 50181-139, 1m
 default:
  user-filters: 0-0, never
  VIE-1: 1819-0, 53m
  easylist: 81757-37, 9m Δ
  ublock-filters: 37400-221, 9m Δ
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1525 ms (selfie)
 maxAssetCacheWait: 225 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 16
 network:
  doubleclick.net: 3
  eclick.vn: 7
  google.com: 1
  googletagmanager.com: 5
 extended:
  ##.banner-ads:not(.textads)
  ###to_top:not(body)
  ##.grecaptcha-badge
  ###supper_masthead
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed in `uBlock filters – Annoyances` list
