### ISSUE TITLE
Blocked redirects from Finder pages

### ISSUE THREAD

**Issue by fmrk** [uBlockOrigin/uAssets#22695]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.finder.com.au/
https://www.finder.com/
https://www.findershopping.com.au/
https://www.creditcard.com.au/
https://whatphone.com.au/
```

### Description

First of all, I'd like to thank you very much for your great advice which helped successfully solve my [last issue](https://github.com/uBlockOrigin/uAssets/issues/21939) 🙇‍♂️
I'm getting back to you because there are more things off when using uBO and redirecting from Finder pages.

Finder lists products from multiple partners for users to compare and choose from. Lots of our partners use their redirect platforms such as:
- awin1.com
- click.linksynergy.com
- t.cfjump.com
- doubleclick.net
- prf.hn
- shareasale.com

and many more.

For example when clicking `Go to site` button for `Qantas Premier Platinum` on https://www.finder.com.au/credit-cards I'm getting:
>uBlock Origin has prevented the following page from loading:
https://ad.doubleclick.net/ddm/trackclk/...
Because of the following filter:
||doubleclick.net^

I also got a similar result for `Get deal` for `The new Koala mattress from $790` on https://www.findershopping.com.au/. The issue applies to hundreds of other products on all of our domains listed above.

Of course, clicking `Proceed` takes the user to the credit card and the mattress, but the warning itself creates confusion and drop-off anyway.
Like previously, I think getting redirected to the expected destination isn't an undesired ad or any other sort of trap.
I've noticed that most of these domains are listed on Peter Lowe’s Ad and tracking server list. After some digging, I've bumped into uBO's "unbreak list". Is there an option for unbreaking our users' experience and redirecting them without the page load being blocked?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1124" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/12071815/baa0194f-aac5-457d-9f88-03777ff79d78">

<img width="685" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/12071815/25f11404-30c7-44e6-b6ce-1d3cc73b6e55">

<img width="1156" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/12071815/45769d71-5d0c-4751-891c-7e65b8604a05">

<img width="665" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/12071815/ae669306-7870-473f-82a8-c5ea28160f5b">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 125241
 cosmetic: 45619
 scriptlet: 20324
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81846-13, 42m Δ
  easyprivacy: 50287-6, 42m Δ
  plowe-0: 3783-1187, 1h.47m
  ublock-badware: 8010-142, 42m Δ
  ublock-filters: 37415-362, 42m Δ
  ublock-privacy: 745-6, 42m Δ
  ublock-quick-fixes: 109-6, 42m Δ
  ublock-unbreak: 2223-32, 42m Δ
  urlhaus-1: 8670-0, 1h.47m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 644 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0

```
</details>

**Comment by stephenhawk8054** [comment]
There are thousands of ways an ad domain being used as redirections and no way to differentiate which one is ad and which one is redirection. In this case the domain being used is `doubleclick.net` which is a big ad domain. And uBO does not only block ads, it blocks trackers as well and this is also a big tracker.

Instead of complaining to uBO, it's better to complain to the websites to tell them removing privacy-invasion redirections.

**Comment by fmrk** [comment]
> There are thousands of ways an ad domain being used as redirections and no way to differentiate which one is ad and which one is redirection. In this case the domain being used is `doubleclick.net` which is a big ad domain. And uBO does not only block ads, it blocks trackers as well and this is also a big tracker.
> 
> Instead of complaining to uBO, it's better to complain to the websites and tell them to remove privacy-invasion redirections.

Thanks for your answer. Still, it might be close to impossible to get all these domains (doubleclick, awin1, etc) removed from filter lists. Given our situation, would it be possible to create some kind of exception for such redirects from our domains only? We are committed to ensuring a privacy-respecting experience for our users and are open to suggestions on how best to achieve this without negatively impacting their experience.

**Comment by stephenhawk8054** [comment]
As I said, my stance is the website better removing privacy-invasion 3rd-party redirection than uBO making exceptions. Each website coming and asking for making exceptions for their 3rd-party redirections and finally uBO is next-to-useless for blocking trackers?

That's my personal opinion.
