### ISSUE TITLE
globalnews.ca

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#2269]
### URL(s) where the issue occurs

`https://globalnews.ca/news/3870557/wilfred-laurier-freedom-of-expression-lindsay-shepherd/`

### Describe the issue

Anti-adblock 
### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/39975790-a68580a0-56fe-11e8-9a0e-e80f264a5998.png)

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.
