### ISSUE TITLE
aeroinsta.com: detection

### ISSUE THREAD

**Issue by efempic** [uBlockOrigin/uAssets#22694]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aeroinsta.com/`

### Category

detection

### Description

Ublock origin is being detected by the page. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 127650
 cosmetic: 39908
 scriptlet: 19047
 html: 1786
listset (total-discarded, last-updated):
 removed:
  spa-1: null
 default:
  user-filters: 2-1, never
  ublock-filters: 37999-358, 5m Δ
  ublock-badware: 8008-14, 5m Δ
  ublock-privacy: 743-1, 5m Δ
  ublock-unbreak: 2285-1, 5m Δ
  ublock-quick-fixes: 113-2, 5m Δ
  adguard-mobile: 9091-135, now
  easylist: 81764-16453, 5m Δ
  easyprivacy: 50287-873, 5m Δ
  urlhaus-1: 8670-0, now
  plowe-0: 3783-1, now
  spa-0: 3903-265, 4m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1429 ms
 maxAssetCacheWait: 514 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  pub.network: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Yeah, if there are hard anti-adb, we should move it to main list.
