### ISSUE TITLE
toggo.de: breakage

### ISSUE THREAD

**Issue by odin81** [uBlockOrigin/uAssets#22697]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.toggo.de/toggolino/rubble--crew-pty561/hoerspiele/ich-geh'-mit-meiner-laterne-aep221`

### Category

breakage

### Description

Video is not starting to play. Without uBlock enabled there is on add and then die video starts playing.
It starts some days ago. I can't tell the exact date.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 127496
 cosmetic: 50610
 scriptlet: 18984
 html: 1785
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37648-252, now
  ublock-badware: 8009-14, now
  ublock-privacy: 741-0, now
  ublock-unbreak: 2280-0, now
  ublock-quick-fixes: 114-2, now
  easylist: 81860-537, now
  easyprivacy: 50287-849, now
  urlhaus-1: 8670-0, now
  plowe-0: 3783-1, now
  DEU-0: 7295-3, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3449 ms
 maxAssetCacheWait: 35 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  toggo.de: 1
  demdex.net: 2
  omtrdc.net: 1
  sentry.io: 2
  smartclip.net: 1
  youboranqs01.com: 23
```
</details>

**Comment by Yuki2718** [comment]
`smartclip.net` is in EL so shouldn't this be fixed in EL?

**Comment by JobcenterTycoon** [comment]
Yes why not

`@@||ad-ipd.sxp.smartclip.net/select?type=vast$xhr,domain=toggo.de` is to prevent the breakage and
 `||ccstatic.toggo.de/cc-static-files/bumper-video/Toggolino_WT_$media,1p` to block the "ad starting" and "ad ending" video.

**Comment by Yuki2718** [comment]
@Khrin Can you take a look for the ad?
