### ISSUE TITLE
brainly.com: detection

### ISSUE THREAD

**Issue by Oqarshi** [uBlockOrigin/uAssets#22704]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://brainly.com/question/20291364`

### Category

detection

### Description

There is a "Expert Verfied Answer" section. You can skip this by watching an ad, but brainly detects the adblocker and trys to make you turn it off so you can see the answer.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-27 205639](https://github.com/uBlockOrigin/uAssets/assets/94034118/aa770b30-f97d-44cd-afda-1a89958e102c)
![Screenshot 2024-02-27 205718](https://github.com/uBlockOrigin/uAssets/assets/94034118/a80f24be-9571-4df1-b822-5f4d78de3fc4)
![Screenshot 2024-02-27 205736](https://github.com/uBlockOrigin/uAssets/assets/94034118/5e0074c3-0554-4069-97d1-1595ce2a70bb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 441747
 cosmetic: 368724
 scriptlet: 55781
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  ALB-0: 305-0, 15m
  BGR-0: 1040-1, 49m
  CHN-0: 25372-129, 48m
  CZE-0: 832-1, 15m
  DEU-0: 7295-0, 15m
  EST-0: 464-2, 2m
  FIN-0: 2276-0, 2m
  FRA-0: 22730-67, 48m
  GRC-0: 1074-0, 2m
  HRV-0: 388-2, 2m
  HUN-0: 2083-2, 2m
  IDN-0: 9876-19, 2m
  [47 lists not shown]: [too many]
 default:
  easylist: 81801-2285, 2m
  easyprivacy: 50293-32616, 2m
  plowe-0: 3783-1712, 2m
  ublock-badware: 8010-286, 2m
  ublock-filters: 37381-4178, 2m
  ublock-privacy: 746-221, 2m
  ublock-quick-fixes: 110-7, 2m
  ublock-unbreak: 2224-166, 2m
  urlhaus-1: 8655-0, 2m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1336 ms (selfie)
 maxAssetCacheWait: 1014 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 19
 network:
  brainly.com: 8
  ad.gt: 1
  adlightning.com: 1
  branch.io: 1
  cloudflareinsights.com: 1
  datadome.co: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  opti-digital.com: 1
  privacy-center.org: 1
  sentry.io: 2
 extended:
  ##div[data-testid="brainly_ads_placeholder"]
  ##[data-testid="brainly_ads_placeholder"]
  ##+js(set-local-storage-item, simple-funnel-name, $remove$)
  ##+js(set-local-storage-item, social-qa/telemetry, )
  ##+js(set-constant, jsData.adsEnabled, false)
  ##+js(set-constant, jsData.hasVideoMeteringUnlogEnabled, undefin…
  ##+js(set-local-storage-item, social-qa/machineId, $remove$)
  ##+js(no-setTimeout-if, trigger, 0)
  ##+js(abort-on-property-read, __brn_private_mode)
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` or add this filter as your custom filter

```adb
brainly.*##+js(set-local-storage-item, social-qa/machineId, $remove$)
```

Also please don't enable all the lists, including regional lists, existed.

**Comment by Oqarshi** [comment]
Im sorry i disabled regional lists, also enabled uBlock filters – Annoyances, but the issue seems to still be persistent.

**Comment by Oqarshi** [comment]
> Enable `uBlock filters – Annoyances` list or add this filter as your custom filter
> 
> ```
> brainly.*##+js(set-local-storage-item, social-qa/machineId, $remove$)
> ```
> 
> Also please don't enable all the lists, including regional lists, existed.

Im sorry i disabled regional lists, also enabled uBlock filters – Annoyances, but the issue seems to still be persistent.

**Comment by stephenhawk8054** [comment]
Reset uBO to default settings, enable uBlock filters – Annoyances list, restart the browser, open new tab and test again.

**Comment by Oqarshi** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/584611be-536a-471f-8c0f-dd6e97adb6f8)
Uhh its still not working, brainly still detects an adblocker

**Comment by stephenhawk8054** [comment]
The answer is still blurred for you?

**Comment by Oqarshi** [comment]
Yes

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by Oqarshi** [comment]
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 136367
 cosmetic: 199494
 scriptlet: 33285
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28800-33, 10m
  adguard-mobile-app-banners: 5037-7, 10m
  adguard-other-annoyances: 13897-8, 10m
  adguard-popup-overlays: 26647-82, 10m
  adguard-social: 22175-899, 10m
  adguard-widgets: 2405-3, 10m
  easylist-annoyances: 4402-246, 10m
  easylist-chat: 183-14, 10m
  easylist-newsletters: 7041-495, 10m
  easylist-notifications: 2950-1467, 10m
  fanboy-cookiemonster: 66079-19730, 10m
  fanboy-social: 16056-752, 10m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 81846-71, 10m Δ
  easyprivacy: 50288-119, 10m Δ
  plowe-0: 3783-1188, 11m
  ublock-badware: 8010-142, 11m
  ublock-filters: 37380-706, 11m
  ublock-privacy: 746-8, 11m
  ublock-quick-fixes: 110-6, 11m
  ublock-unbreak: 2224-36, 10m Δ
  urlhaus-1: 8655-0, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 999 ms
 maxAssetCacheWait: 339 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 12
 network:
  brainly.com: 2
  ad.gt: 1
  adlightning.com: 1
  branch.io: 1
  cloudflareinsights.com: 1
  datadome.co: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  opti-digital.com: 1
  privacy-center.org: 1
  sentry.io: 1
 extended:
  ##[data-testid="brainly_ads_placeholder"]
  ##+js(set-local-storage-item, social-qa/telemetry, )
  ##+js(set-constant, jsData.adsEnabled, false)
  ##+js(set-constant, jsData.hasVideoMeteringUnlogEnabled, undefin…
  ##+js(set-local-storage-item, social-qa/machineId, $remove$)
  ##+js(no-setTimeout-if, trigger, 0)
  ##+js(abort-on-property-read, __brn_private_mode)

**Comment by stephenhawk8054** [comment]
You haven't reset uBO to default settings.

> Reset uBO to default settings, enable uBlock filters – Annoyances list, restart the browser, open new tab and test again.

**Comment by Oqarshi** [comment]
im not sure how to tell you this buttt

![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/028009f4-0ccd-41af-8fe7-6b1dfa65f448)


uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125038
 cosmetic: 47394
 scriptlet: 25014
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6825-32, never
 default:
  user-filters: 0-0, never
  easylist: 81846-13, 1m
  easyprivacy: 50288-6, 1m
  plowe-0: 3783-1187, 1m
  ublock-badware: 7717-142, 1m
  ublock-filters: 37400-363, 1m
  ublock-privacy: 745-6, 1m
  ublock-quick-fixes: 126-5, 1m
  ublock-unbreak: 2224-32, 1m
  urlhaus-1: 8430-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1453 ms
 maxAssetCacheWait: 9 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 16
 network:
  brainly.com: 2
  ad.gt: 1
  adlightning.com: 1
  amazon-adsystem.com: 1
  branch.io: 1
  cloudflareinsights.com: 1
  datadome.co: 1
  doubleclick.net: 2
  googletagmanager.com: 1
  opti-digital.com: 1
  rlcdn.com: 1
  rubiconproject.com: 1
  sentry.io: 2
 extended:
  ##[data-testid="brainly_ads_placeholder"]
  ##+js(no-setTimeout-if, trigger, 0)
  ##+js(abort-on-property-read, __brn_private_mode)
  ##+js(set-constant, jsData.hasVideoMeteringUnlogEnabled, undefin…
  ##+js(set-local-storage-item, social-qa/machineId, $remove$)

**Comment by Oqarshi** [comment]
i reset ublock origin to default settings and just turned on uBlock filters – Annoyances

**Comment by stephenhawk8054** [comment]
Can you reproduce the issue and copy the troubleshooting information here again?

**Comment by Oqarshi** [comment]
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125030
 cosmetic: 47403
 scriptlet: 24927
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6825-29, now
 default:
  user-filters: 0-0, never
  easylist: 81846-13, now
  easyprivacy: 50292-6, now Δ
  plowe-0: 3783-1187, now
  ublock-badware: 7717-142, now
  ublock-filters: 37309-365, now Δ
  ublock-privacy: 745-6, now
  ublock-quick-fixes: 126-5, now Δ
  ublock-unbreak: 2224-33, now
  urlhaus-1: 8430-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 985 ms
 maxAssetCacheWait: 299 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  brainly.com: 2
  ad.gt: 1
  adlightning.com: 1
  amazon-adsystem.com: 1
  branch.io: 1
  cloudflareinsights.com: 1
  datadome.co: 1
  doubleclick.net: 2
  googletagmanager.com: 1
  opti-digital.com: 1
  rlcdn.com: 1
  rubiconproject.com: 1
  sentry.io: 1
 extended:
  ##[data-testid="brainly_ads_placeholder"]
  ##+js(set-constant, jsData.hasVideoMeteringUnlogEnabled, undefin…
  ##+js(set-local-storage-item, social-qa/machineId, $remove$)
  ##+js(no-setTimeout-if, trigger, 0)
  ##+js(abort-on-property-read, __brn_private_mode)

**Comment by stephenhawk8054** [comment]
Can you clear the site's cookies and data, then browse it a while to see if the issue is still there?
