### ISSUE TITLE
pandora.com: breakage

### ISSUE THREAD

**Issue by onparr24** [uBlockOrigin/uAssets#22701]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pandora.com/station/play/155025644105762751`

### Category

breakage

### Description

Pandora gets stuck on loading screen when extension is enabled. It is the only extension I have installed. When I disable Ublock origin then Pandora will load with ads. I use Chrome on Windows 10.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="957" alt="pandora issue" src="https://github.com/uBlockOrigin/uAssets/assets/60029617/b9c04963-0746-46e4-b244-285641fa883f">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125242
 cosmetic: 45620
 scriptlet: 20325
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 81846-13, now
  easyprivacy: 50287-6, now
  plowe-0: 3783-1187, now
  ublock-badware: 8010-142, now
  ublock-filters: 37415-362, now
  ublock-privacy: 746-6, now
  ublock-quick-fixes: 110-6, now
  ublock-unbreak: 2223-32, now
  urlhaus-1: 8670-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 699 ms (selfie)
 maxAssetCacheWait: 422 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 14
 network:
  pandora.com: 1
  adsafeprotected.com: 1
  adswizz.com: 2
  bizible.com: 1
  branch.io: 1
  cookielaw.org: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  krxd.net: 1
  scorecardresearch.com: 1
  sentry.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to log in to reproduce the issue?
