### ISSUE TITLE
hktvmall.com: breakage

### ISSUE THREAD

**Issue by capomic** [uBlockOrigin/uAssets#22702]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hktvmall.com/`

### Category

breakage

### Description

Search bar vanishes when clicked

### Other extensions used

None (site functional when uBO is disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/39001397/8aeca1f4-f37f-4fea-a909-a4d3a26cfefc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 139793
 cosmetic: 56095
 scriptlet: 19128
 html: 1785
listset (total-discarded, last-updated):
 added:
  https://github.com/pixeltris/TwitchAdSolutions/raw/bc355dda0ae98e142577e8521ad1857ccdb3b724/vaft/vaft-ublock-origin.js: 111-68, now
  CHN-0: 25371-133, now
 default:
  user-filters: 10-0, never
  ublock-filters: 37613-131, 38m Δ
  ublock-badware: 8014-14, 38m Δ
  ublock-privacy: 742-0, 38m Δ
  ublock-unbreak: 2281-0, 38m Δ
  easylist: 81846-649, 38m Δ
  easyprivacy: 50288-877, 38m Δ
  urlhaus-1: 8655-0, now
  plowe-0: 3783-1, now
  ublock-quick-fixes: 115-2, 38m Δ
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 27 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9030 ms (selfie)
 maxAssetCacheWait: 161 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  facebook.net: 1
  googleadservices.com: 2
  googletagmanager.com: 1
 extended:
  ##.CrazyAd
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test in a new Firefox profile with only uBO and its default settings?

**Comment by liamengland1** [comment]
I can reproduce. Caused by `||hktvmall.com/yuicombo?$script,removeparam=/_ui/shared/common/js/InappCommunicationManager.js` in uBo - privacy.

**Comment by stephenhawk8054** [comment]
Ah ok I can reproduce now. Do these work?

```adb
hktvmall.com##+js(set, analytics, {})
hktvmall.com##+js(set, analytics.getGaRevamp2020AnalyticsZone, noopFunc)
hktvmall.com##+js(set, analytics.trackEcommercePromoImpressionMulti, noopFunc)
```

**Comment by liamengland1** [comment]
Yes, I also added `hktvmall.com##+js(set, analytics.trackEcommercePromoImpression, noopFunc)` to fix the slideshow/carousel on the homepage.

**Comment by stephenhawk8054** [comment]
Hmmm... I think the script not loaded successfully is a concern, better to disable the above `removeparam` filter than adding scriptlets.

**Comment by stephenhawk8054** [comment]
cc @Yuki2718

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/2ee71aa7e26a609169880cf851e7fecbf724759b
