### ISSUE TITLE
psychpsyo.com: breakage

### ISSUE THREAD

**Issue by Psychpsyo** [uBlockOrigin/uAssets#22703]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://psychpsyo.com/repro/buttonImages/`

### Category

breakage

### Description

If an ``<img>`` is inside a ``<button>`` and has a ``width`` set so that it ends up being smaller than its original size, it will not show up while being click-dragged. (usually, you'd see a half-transparent version of the image as you drag it)
This only happens the first time you drag it.

To reset and re-do the bug, clear or disable the site's cache.

Also, I originally found the bug on https://battle.crossuniverse.net/deckMaker/ but the reported site here is a simplified reproduction setup.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/60073468/5dfd2983-4414-4bf1-bd51-5feb435ee3eb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125220
 cosmetic: 45607
 scriptlet: 18950
 html: 1785
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37613-142, 49m Δ
  ublock-badware: 8014-14, 49m Δ
  ublock-privacy: 742-0, 49m Δ
  ublock-unbreak: 2281-0, 49m Δ
  easylist: 81846-628, 49m Δ
  easyprivacy: 50288-836, 49m Δ
  urlhaus-1: 8655-0, now
  plowe-0: 3783-1, now
  ublock-quick-fixes: 115-2, 49m Δ
filterset (user): [empty]
trustedset:
 added: [array of 30 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 373 ms (selfie)
 maxAssetCacheWait: 201 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
I don't understand. The site looks the same even when not using any extensions

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/215e5dff-5e10-42fe-825f-d6d5c21a6d84)

**Comment by liamengland1** [comment]
Nothing to do with uBo, should be filed with Bugzilla if desired.

**Comment by Psychpsyo** [comment]
> I don't understand. The site looks the same even when not using any extensions

It doesn't show the pink rectangle instead of the image when you try to click&drag it.
(keep in mind: This happens the first time only so clear the cache before trying.)

> Nothing to do with uBo, should be filed with Bugzilla if desired.

That was my first idea until I noticed that this stops happening when I disable uBO.

**Comment by stephenhawk8054** [comment]
I set my profile auto-clear all cache and cookie when closing. They work the same for me with or without uBO (First time is pink, 2nd time and forward is the image)

**Comment by Psychpsyo** [comment]
> I set my profile auto-clear all cache and cookie when closing. They work the same for me with or without uBO (First time is pink, 2nd time and after is the image)

You're right, I'm sorry. Must've messed this up myself yesterday.
