### ISSUE TITLE
yhmgo.com: ads

### ISSUE THREAD

**Issue by ShunAn1231** [uBlockOrigin/uAssets#22705]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

ads in the video is not being blocked
![2024-02-28 13_54_56-Greenshot](https://github.com/uBlockOrigin/uBlock-issues/assets/67151466/2d02bc5f-3170-4f7b-9519-d3032b7426b3)

### A specific URL where the issue occurs.

```yaml
https://www.yhmgo.com/vp/23237-2-4.html
```

### Steps to Reproduce

no more details.

### Expected behavior

no ads in between the video

### Actual behavior

still have ads in every video

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 147077
 cosmetic: 142523
 scriptlet: 25110
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77579-133, 1d.23h.51m
  CHN-0: 25354-139, 1d.23h.51m
  adguard-social: 22197-880, 1d.23h.51m
 default:
  user-filters: 0-0, never
  easylist: 81846-91, 1m Δ
  easyprivacy: 50288-87, 1m Δ
  plowe-0: 3782-1189, 5d.15h.24m
  ublock-badware: 8010-142, 1m Δ
  ublock-filters: 37380-717, 1m Δ
  ublock-privacy: 746-7, 1m Δ
  ublock-quick-fixes: 110-6, 1m Δ
  ublock-unbreak: 2224-34, 1m Δ
  urlhaus-1: 8770-0, 21h.32m
filterset (user): [empty]
userSettings:
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 700 ms (selfie)
 maxAssetCacheWait: 370 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you reproduce?

**Comment by ShunAn1231** [comment]
hi, can i ask what should i do to my filter list to block these ads?

**Comment by cjx82630** [comment]
The ad was made into the video, is  a part of the video file now.

**Comment by ShunAn1231** [comment]
but i report this type of ads before and they helped me solve it, in another website.

**Comment by stephenhawk8054** [comment]
@ShunAn1231 Can you test these filters?

```adb
yhmgo.com#@#+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|adjump/, .m3u8)
yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|adjump|1\d{4}\.ts/, .m3u8)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by ShunAn1231** [comment]
> @ShunAn1231 Can you test these filters?
> 
> ```
> yhmgo.com#@#+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|adjump/, .m3u8)
> yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|adjump|1\d{4}\.ts/, .m3u8)
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

ok

**Comment by stephenhawk8054** [comment]
Does it work?

**Comment by ShunAn1231** [comment]
yes it does, tysm

**Comment by stephenhawk8054** [comment]
@ShunAn1231 Next time please just continue in your old thread: https://github.com/uBlockOrigin/uAssets/issues/19889

We are all notified with new comments. It's easier to manage same site with same issue at one place, no need to open duplicated issue.
