### ISSUE TITLE
farsroid.com: detection

### ISSUE THREAD

**Issue by mztd006** [uBlockOrigin/uAssets#22708]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.farsroid.com/airmirror/`

### Category

detection

### Description

`www.farsroid.com` is a Persian mobile app store
the below text saysin persian: to keep using this website disable your AdBlock extension
![Screenshot 2-28-2024 at 03 07 PM](https://github.com/uBlockOrigin/uAssets/assets/131897783/765c3bae-c232-45c1-8941-78cc5b1c1ab9)

### Other extensions used

bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2-28-2024 at 03 10 PM](https://github.com/uBlockOrigin/uAssets/assets/131897783/e9a7a4bb-b60f-42f4-bbcc-c3e22915b6cf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126410
 cosmetic: 47263
 scriptlet: 20429
 html: 0
listset (total-discarded, last-updated):
 added:
  IRN-0: 3008-0, 47m
 default:
  user-filters: 2-0, never
  easylist: 81805-19, now
  easyprivacy: 50292-16, now
  plowe-0: 3783-1189, now
  ublock-badware: 8010-143, now
  ublock-filters: 37387-362, now
  ublock-privacy: 745-6, now
  ublock-quick-fixes: 118-5, now
  ublock-unbreak: 2224-34, now
  urlhaus-1: 8655-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 720 ms
 maxAssetCacheWait: 218 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(remove-node-text, script, ads_app_name)
  ##+js(no-window-open-if)
```
</details>

**Comment by JobcenterTycoon** [comment]
@MasterKia
