### ISSUE TITLE
Quora Assistant blocked by "uBlock filters – Ads"

### ISSUE THREAD

**Issue by limdingwen** [uBlockOrigin/uAssets#22707]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.quora.com/Why-is-Tor-more-popular-than-I2P
```

### Description

Without `uBlock filters – Ads`, the Quora Assistant works as usual. When it is enabled, the questions and answers blank out, leaving only suggested questions.

I am logged out.

Might be more suitable for Annoyances?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without the filter list:

<img width="685" alt="Screenshot 2024-02-28 at 6 23 07 PM" src="https://github.com/uBlockOrigin/uAssets/assets/1744967/f4961f17-3636-4bf1-bcce-7e430f77ced1">
<img width="647" alt="Screenshot 2024-02-28 at 6 23 23 PM" src="https://github.com/uBlockOrigin/uAssets/assets/1744967/65df86e8-a171-4c41-bd48-dc8ea81f06cc">

With the filter list:

<img width="683" alt="Screenshot 2024-02-28 at 6 23 43 PM" src="https://github.com/uBlockOrigin/uAssets/assets/1744967/22a8e290-a372-4535-a9cc-7e3f007f34f3">
<img width="659" alt="Screenshot 2024-02-28 at 6 23 51 PM" src="https://github.com/uBlockOrigin/uAssets/assets/1744967/9cdb6e7f-5918-43c1-904f-f36a040ce1c0">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 148851
 cosmetic: 237258
 scriptlet: 31960
 html: 364
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
 added:
  adguard-generic: 79363-2217, 6m
  adguard-mobile: 9091-19, 6m
  adguard-social: 22175-868, 6m
  adguard-cookies: 28801-67, 6m
  ublock-cookies-adguard: 999-0, 6m
  adguard-popup-overlays: 26648-1633, 6m
  adguard-mobile-app-banners: 5035-1079, 6m
  adguard-other-annoyances: 13897-337, 6m
  adguard-widgets: 2406-2, 6m
  fanboy-thirdparty_social: 68-0, 6m
  easylist-annoyances: 4399-135, 6m
  easylist-chat: 183-14, 6m
  [6 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-badware: 8014-14, 23m
  ublock-privacy: 741-0, 23m
  ublock-unbreak: 2281-0, 6m Δ
  ublock-quick-fixes: 115-2, 23m
  easylist: 81805-664, now
  easyprivacy: 50292-959, now
  urlhaus-1: 8655-0, now
  plowe-0: 3783-84, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2616 ms (selfie)
 maxAssetCacheWait: 331 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  quora.com: 3
  amazon-adsystem.com: 1
  btloader.com: 2
  doubleclick.net: 1
  facebook.net: 1
  google.com: 1
 extended:
  ##[data-nosnippet="true"]
  ##.PageContentsLayout___StyledBox-d2uxks-0 > .q-box > .q-sticky …
  ##.dom_annotate_ad_image_ad
  ##.dom_annotate_ad_promoted_answer
  ##.spacing_log_question_page_ad
  ##.qu-pb--medium > .q-box.qu-borderAll:has(> .q-box > .qu-py--sm…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.qu-zIndex--action_bar.qu-bg--raised:style(bottom: 0px !import…
  ##.qu-overflow--hidden:not(.q-relative):style(overflow: auto !im…
  ##body:style(overflow: auto !important;)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, ansFrontendGlobals.settings.signupWallType, …
```
</details>

**Comment by limdingwen** [comment]
Holy crap that was fast, thank you! 😊

**Comment by Daxy7** [comment]
cleanup invalid cosmetic filters. add ad placeholders unaddressed in https://github.com/easylist/easylist/issues/18474
```
https://www.quora.com/How-do-I-add-a-favicon-in-a-Blogspot-blog-in-2020
```
```
! fast
quora.com##[style^="box-sizing: border-box; position: sticky; top: 66px;"]
! precise
quora.com##div.dom_annotate_google_ad:upward(3)
! or
quora.com##.q-sticky:has-text(Advertisement)
```
```
! invalid
!quora.com##.PromptsList
!quora.com##.AdBundle
!quora.com##.AdStory
!!#if env_mobile
!quora.com##.top_slot
!!#endif
!quora.com##div[id$="_content_box"]
!quora.com##.lower_slot
!quora.com##[disable_auto_login*="True"]
!quora.com##:xpath(//div[not(@class="ui_qtext_para") and contains(text(), 'ad by')]/parent::div/parent::div/parent::div[@id])
!quora.com##:xpath(//div[not(@class="ui_qtext_para") and contains(text(), 'promoted') and contains(text(), 'by')]/parent::a/parent::div/parent::div/parent::div[@id])
!quora.com##:xpath(//div[not(@class="ui_qtext_para") and contains(text(), 'Quora') and contains(text(), 'by') and contains(text(), 'Business')]/parent::a/parent::div/parent::div/parent::div[@id])
!quora.com##.FeedStory.feed_item > div > div:has-text(/by Quora for Business/i)
!quora.com##.Toggle.SimpleToggle.ToggleAnswerFooterWrapper > div:has-text(/Promoted/i)
!quora.com##:xpath(//span[contains(text(), 'by')]/ancestor::*[contains(concat(' ', @class, ' '), ' external_link ')]/../../..)
!quora.com##:xpath(//p[(text()='d')]/../../../../..)
! from abp cv list for https://github.com/uBlockOrigin/uAssets/issues/8032
!quora.com##.u-margin-top--lg+div[class="UnifiedAnswerPagedList PagedListFoo unified"][id$="_paged_list"]
!quora.com##.pagedlist_item > div[id$="_paged_list"]
!quora.com##.answer_auto_expanded_comments + div > div.feed_expand
!quora.com##.feedback_wrapper.hidden:not(.negative_action) + .FeedStory.HyperLinkFeedStory.feed_item
!quora.com##div[class="question_main_col"]  > div:nth-child(3) > div[class="UnifiedAnswerPagedList PagedListFoo unified"]
!quora.com##div[class="pagedlist_item"]  div[id*="paged_list"]
!quora.com##.q-box.qu-borderAll>.q-box>div>div[class^="Box-sc-"]>div:not([class])
!quora.com##.q-box.qu-borderTop>[class^="Box-sc-"]>div:not([class])
!quora.com##div > [class^="Box-"] > div > .q-box.qu-pb--tiny.qu-pt--medium.qu-px--medium
!quora.com##.qu-bg--white>[class^="Box-"] .qu-pt--medium
!quora.com##.q-box.qu-borderTop>[class^="Box-"] .q-box.qu-pt--medium.qu-pb--tiny
!quora.com##.q-box.qu-borderAll>.q-box>div:not([class="q-box"])>[class^="Box-"]
!quora.com##.q-box.qu-borderAll.qu-bg--white>.q-box>div>[class="q-box "]>[class="q-box"]
!quora.com##[class="q-box qu-borderTop"]>[class="q-box "]
!quora.com##[class="q-box qu-bg--white"]>[class="q-box "]>[class="q-box"]
!quora.com##.dom_annotate_multifeed_bundle_AdBundle
```

**Comment by Daxy7** [comment]
@JobcenterTycoon Sorry, but these filters are invalid and may cause breakage. I also added filters that remove placeholders seen in https://github.com/easylist/easylist/issues/18474

**Comment by JobcenterTycoon** [comment]
@uBlock-user do you want to take a look? I don’t have a account.
