### ISSUE TITLE
dktechnicalmate.com: detection

### ISSUE THREAD

**Issue by xd003** [uBlockOrigin/uAssets#22719]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://dktechnicalmate.com
```

### Description

Adblock is detected as soon as the website loads

### Other extensions used

Dark Reader
Cookie Editor
1Password
Violetmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26503185/9ffa01e7-3235-4046-938e-308d0f2f678b)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 132208
 cosmetic: 140988
 scriptlet: 30167
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 26646-44, 1d.21h.56m
  block-lan: 56-0, 27d.7h.16m
  easylist-annoyances: 4381-139, 6d.4h.58m
  easylist-chat: 183-0, 1h.30m
  easylist-newsletters: 7010-474, 6d.4h.57m
  easylist-notifications: 2948-198, 6d.4h.58m
  fanboy-cookiemonster: 50103-208, 6d.4h.58m
  fanboy-social: 16176-46, 6d.4h.58m
  ublock-annoyances: 6834-159, 30m Δ
  ublock-cookies-easylist: 973-967, 6d.4h.59m
 default:
  user-filters: 0-0, never
  easylist: 81851-44, 30m Δ
  easyprivacy: 50292-110, 30m Δ
  plowe-0: 3782-1186, 4d.7h.38m
  ublock-badware: 7717-142, 30m Δ
  ublock-filters: 37305-456, 30m Δ
  ublock-privacy: 745-8, 30m Δ
  ublock-quick-fixes: 126-5, 30m Δ
  ublock-unbreak: 2224-36, 30m Δ
  urlhaus-1: 8385-0, 21h.55m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 394 ms (selfie)
 maxAssetCacheWait: 289 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by ItsProfessional** [comment]
fixed https://github.com/uBlockOrigin/uAssets/commit/cfeb9b71c9d5711348ac1402138329fc2655bc50
