### ISSUE TITLE
app.blubank.com: breakage

### ISSUE THREAD

**Issue by nadkaro** [uBlockOrigin/uAssets#22710]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.blubank.com/`

### Category

breakage

### Description

بلو بانک 

### Other extensions used

کار‌نمیکنه بلو بانک‌در صورت اجرا.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 122
filterset (summary):
 network: 126333
 cosmetic: 37421
 scriptlet: 19015
 html: 1786
listset (total-discarded, last-updated):
 removed:
  IRN-0: null
 default:
  user-filters: 0-0, never
  ublock-filters: 37977-355, 6m Δ
  ublock-badware: 8008-14, 13m
  ublock-privacy: 742-1, 6m Δ
  ublock-unbreak: 2286-1, 13m
  ublock-quick-fixes: 119-2, 13m
  adguard-mobile: 9093-133, 14m
  easylist: 81805-16403, 6m Δ
  easyprivacy: 50292-873, 6m Δ
  urlhaus-1: 8385-0, 13m
  plowe-0: 3783-1, 13m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1180 ms
 maxAssetCacheWait: 427 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by liamengland1** [comment]
`Blue Bank does not work when running`

Caused by `app.blubank.com##+js(trusted-set-constant, navigator.userAgent, 'iPad; CPU OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari')` in uBo filters.

I see `Uncaught TypeError: navigator.userAgent is undefined` in Firefox. Issue with `trusted-set-constant`?

**Comment by liamengland1** [comment]
@mapx- I edited the comment to say that I couldn't reproduce on a new profile, didn't know if you saw. So maybe we can keep that filter if I investigate what extension (?) I have that is causing trusted-set to misbehave with Firefox

**Comment by mapx-** [comment]
I tested in chrome - mobile emulation, I'm stuck on loading due to that filter (same for the other site), so I removed them
