### ISSUE TITLE
[nsfw] soap2day.qa: popups

### ISSUE THREAD

**Issue by alphnum** [uBlockOrigin/uAssets#22715]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://soap2day.qa/tv/forever/1/17`

### Category

popups

### Description

New window pops up whenever starting media

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 361397
 cosmetic: 246208
 scriptlet: 50788
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28805-33, 7m
  adguard-generic: 78968-491, 26m
  adguard-mobile: 9094-49, 26m
  adguard-mobile-app-banners: 5037-8, 7m
  adguard-other-annoyances: 13900-9, 7m
  adguard-popup-overlays: 26654-94, 7m
  adguard-social: 22182-902, 7m
  adguard-spyware: 113922-1184, 7m
  adguard-spyware-url: 1465-5, 7m
  adguard-widgets: 2407-6, 7m
  block-lan: 61-0, 7m
  curben-phishing: 115011-31, 7m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 81846-1748, 1h.38m Δ
  easyprivacy: 50292-32319, 1h.38m Δ
  plowe-0: 3783-1676, now
  ublock-badware: 7717-259, 1h.38m Δ
  ublock-filters: 37309-3969, 1h.38m Δ
  ublock-privacy: 745-219, 1h.38m Δ
  ublock-quick-fixes: 126-6, 1h.38m Δ
  ublock-unbreak: 2224-147, 1h.38m Δ
  urlhaus-1: 8385-0, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 5 redacted]
urlRuleset:
 added: [array of 4 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 705 ms (selfie)
 maxAssetCacheWait: 128 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 no-popups: true
 network:
  carpfreshtying.com: 1
  idealintruder.com: 1
  jsdelivr.net: 1
  privacymanager.io: 1
  sharethis.com: 1
 extended:
  ##.btn.gotop
  ##.grecaptcha-badge
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.pinterest.com/pin/create/button/"]
  ##a[href*="pinterest.com/pin/create/button"]
  ##body:style(overflow: auto !important; padding-right: 0 !import…
  ##+js(abort-current-script, globalThis, break;case)
  ##+js(abort-current-script, navigator, FingerprintJS)
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(remove-node-text, script, Reflect)
  ##+js(abort-on-property-write, glxopen)
  ##+js(abort-on-property-write, GLX_GLOBAL_UUID_RESULT)
  ##+js(json-prune, *, pop_type)
  ##+js(json-prune, *, rot_url)
  ##+js(abort-current-script, document.createElement, break;case $…
  ##+js(no-setInterval-if, /devtools|0x/)
  ##+js(set-constant, console.clear, trueFunc)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, __Y)
  ##+js(remove-node-text, script, break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(remove-node-text, script, FingerprintJS)
  ##.share-icons-wrapper
  ###placement-top
  ###email-signup
  ###thread-subscribe-button
  ###thread-share-bar
```
</details>

**Comment by D4niloMR** [comment]
Add in "My filters":

`||privateapi.click^`

**Comment by D4niloMR** [comment]
> @D4niloMR Are you sure this is causing the popups?

It seemed to work, but you're right, it's not this domain that's causing popups.

**Comment by D4niloMR** [comment]
@monzta `https://paicdn.privateapi.click/re.php`

causes popups.

reproducible on `https://embeded.embedz.click/vidsrc.php?video_id=tt21692408`
