### ISSUE TITLE
ovk.to: ads

### ISSUE THREAD

**Issue by TildaRu** [uBlockOrigin/uAssets#22717]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ovk.to/`

### Category

[unknown]

### Description

###_groupListPinnedGroups > [href="/donate"]

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/107315419/2e467575-0867-4e00-9ba6-49fbe156d3f6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 161032
 cosmetic: 112924
 scriptlet: 38494
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 78981-642, now
  adguard-mobile: 9094-70, now
 default:
  user-filters: 1-0, never
  RUS-0: 39783-9, now
  easylist: 81851-1434, now
  easyprivacy: 50292-175, now
  plowe-0: 3783-1274, now
  ublock-badware: 7717-250, now
  ublock-filters: 37309-3607, now
  ublock-privacy: 745-7, now
  ublock-quick-fixes: 126-6, now
  ublock-unbreak: 2224-96, now
  urlhaus-1: 8430-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 35 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 40098 ms (selfie)
 maxAssetCacheWait: 1872 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  piwik.pro: 1
```
</details>

**Comment by TildaRu** [comment]
> Need an account?
> 
> @dimisa-RUAdList

Yes, needed

**Comment by mapx-** [comment]
donate ? self promotion

**Comment by dportvine** [comment]
@TildaRu 
Fixed in [RU AdList: BitBlock](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links)
