### ISSUE TITLE
technical.city: ads

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uAssets#22729]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://technical.city/ru/cpu/Core-i5-12600KF-protiv-Core-i5-12400F`

### Category

ads

### Description

Empty frame exists.

### Other extensions used

Noscript, uMatrix

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![EPHeKc8](https://github.com/uBlockOrigin/uAssets/assets/16985985/58290db2-8c78-4749-be03-917b8f6479d8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b9
Firefox: 124
filterset (summary):
 network: 137321
 cosmetic: 142067
 scriptlet: 28757
 html: 2021
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25914-20, 1h.56m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1723-24, now
  fanboy-cookiemonster: 50146-439, now
  ublock-annoyances: 6797-35, 55m Δ
  easylist-newsletters: 7063-28, now
  ublock-cookies-easylist: 1025-1022, now
 default:
  user-filters: 10-0, never
  ublock-filters: 37329-108, 55m Δ
  ublock-badware: 7721-14, 55m Δ
  ublock-privacy: 741-9, 55m Δ
  ublock-unbreak: 2283-7, 55m Δ
  ublock-quick-fixes: 126-7, 55m Δ
  easylist: 81859-261, 55m Δ
  easyprivacy: 50320-365, 55m Δ
  RUS-0: 39786-247, 1h.56m Δ
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1529 ms (selfie)
 maxAssetCacheWait: 1068 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  catsnetwork.ru: 2
  disqus.com: 1
  facebook.net: 1
  googletagmanager.com: 2
  muteknife.com: 1
  yadro.ru: 1
  yandex.ru: 2
 extended:
  ##div[class^="banner_"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.reddit.com/submit?"]
  ##div[id^="yandex_rtb"]
  ##.facebook
  ##.twitter
  ###thread-share-bar
  ###badges-message__container
  ###email-signup
  ##.icon-facebook-circle
  ##.share-icons-wrapper
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
technical.city##body:style(padding-top: 0px !important;)
technical.city##.container > div:has(div[id^="yandex_rtb"])
```

@dimisa-RUAdList For Ru Adlist?

**Comment by TheFinalCut83** [comment]
[He advised me](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=2040#18) to contact here because this site is multilingual.

**Comment by dimisa-RUAdList** [comment]
```
||technicalcity.b-cdn.net/css/inlab.
technical.city##.container > div[style^="margin-bottom:"]
```

**Comment by stephenhawk8054** [comment]
I see. The reason is the issue does not occur when I switched to other languages.

**Comment by dimisa-RUAdList** [comment]
EasyList already has rules for this domain. Maybe these should be there?

**Comment by stephenhawk8054** [comment]
Ah yeah, I forgot the added ones don't need `style`
