### ISSUE TITLE
www.lightnovelpub.com: ads

### ISSUE THREAD

**Issue by pmfAC** [uBlockOrigin/uAssets#22728]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.lightnovelpub.com/hub_29071230
www.lightnovelpub.com
```

### Description

Blank Adboxes keep showing with element names such as ##.xJGogE-s etc. 

### Other extensions used

None

### Screenshot(s)

![msedge_NYnBbTioUD](https://github.com/uBlockOrigin/uAssets/assets/161791039/9fbc6521-2ac6-413e-8f95-813655733205)

### Configuration

uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 135965
 cosmetic: 199541
 scriptlet: 33140
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28817-33, 6m
  adguard-mobile-app-banners: 5042-7, 6m
  adguard-other-annoyances: 13909-8, 6m
  adguard-popup-overlays: 26664-82, 6m
  adguard-social: 22188-899, 6m
  adguard-widgets: 2407-3, 6m
  easylist-annoyances: 4403-246, 6m
  easylist-chat: 183-14, 6m
  easylist-newsletters: 7055-496, 6m
  easylist-notifications: 2950-1467, 6m
  fanboy-cookiemonster: 50192-3841, 6m
  fanboy-social: 16088-766, 6m
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 81851-71, 6m
  easyprivacy: 50320-119, 4h.4m Δ
  plowe-0: 3783-1188, 3d.5h.52m
  ublock-badware: 7717-142, 4h.4m Δ
  ublock-filters: 37127-696, 4h.4m Δ
  ublock-privacy: 745-8, 4h.4m Δ
  ublock-quick-fixes: 131-6, 4h.4m Δ
  ublock-unbreak: 2226-36, 4h.4m Δ
  urlhaus-1: 8470-0, 4h.4m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1260 ms (selfie)
 maxAssetCacheWait: 179 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  lightnovelpub.com: 1
  googletagmanager.com: 1
  inmobi.com: 1
  vntsm.com: 1
 extended:
  ##body:style(overflow: auto !important;)
  ##*:style(-webkit-touch-callout: default !important; -webkit-use…
  ##+js(no-setTimeout-if, /appendChild|e\("/)
  ##+js(no-setTimeout-if, =>)

**Comment by D4niloMR** [comment]
Add in "My filters":

`lightnovelpub.com##[data-mobid]`
