### ISSUE TITLE
pinterest.com: breakage

### ISSUE THREAD

**Issue by blzfrost** [uBlockOrigin/uAssets#22727]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pinterest.com/`

### Category

breakage

### Description

When UBO is active, I can't see my followers. If I 'turn off' UBO for the site I can see them again. I've also tried it with every other extension disabled, and the results are the same.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/10277488/530f3242-ccc2-42cf-8d9a-18331abcf00a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124807
 cosmetic: 45594
 scriptlet: 18952
 html: 1785
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37620-114, 17m
  ublock-badware: 7721-14, 17m
  ublock-privacy: 741-0, 17m
  ublock-unbreak: 2283-0, 18m
  ublock-quick-fixes: 123-1, 18m
  easylist: 81851-628, 18m
  easyprivacy: 50320-864, 18m
  urlhaus-1: 8470-0, 18m
  plowe-0: 3783-1, 18m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2609 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  pinterest.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Caused by `pinterest.*##[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"])[href]:not([href^="/pin"]))`

and `pinterest.*##body:style(overflow-y: scroll !important;)` in uBO annoyances creates double scrollbar.

**Comment by D4niloMR** [comment]
Do you see any ad with this filter?

`pinterest.*#@#[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"])[href]:not([href^="/pin"]))`

Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes

**Comment by Cylentnyte** [comment]
> Do you see any ad with this filter?
> 
> `pinterest.*#@#[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"])[href]:not([href^="/pin"]))`

This didn't work, but this does:

`pinterest.*##[data-grid-item]:has([class ="o04wc94pm1978196118972341870"])`

**Comment by D4niloMR** [comment]
> `pinterest.*#@#[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"])[href]:not([href^="/pin"]))`

This filter is an exception for the problematic filter. Can you share the specific link where you get ads?

**Comment by D4niloMR** [comment]
Ok, I could see ads once on my account.

**Comment by stephenhawk8054** [comment]
@D4niloMR Does the filter in this thread work for you?
https://www.reddit.com/r/uBlockOrigin/comments/1b59tt9/updated_filter_to_block_promoted_pins_on_pinterest/

If yes maybe we can use without caring about the language.

**Comment by D4niloMR** [comment]
Works only for desktop layout, if we would use this filter I think it's better make 2 filters, for desktop ads and mobile, or a less specific filter which catches them all like

`pinterest.*##[data-grid-item]:has([data-test-pin-id] a[href^="http"][rel])`

**Comment by D4niloMR** [comment]
Seems good to me, I'll test it more later
