### ISSUE TITLE
pch.com: ads

### ISSUE THREAD

**Issue by Jackal12** [uBlockOrigin/uAssets#22720]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pch.com/instantwin/gameplay/arcade/raise-your-game-bulls-eye-bucks`

### Category

ads

### Description

While no ads are showing the site is saying "Your game will load after this sponsored message" but the game never loads, just a black part of the screen where the game should be.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/45652562/1ee93c23-cfed-458b-af8e-a049711e4f4d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124737
 cosmetic: 45612
 scriptlet: 18909
 html: 1786
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37561-142, 8m
  ublock-badware: 7721-14, 8m
  ublock-privacy: 741-0, 8m
  ublock-unbreak: 2281-0, 8m
  ublock-quick-fixes: 123-1, 8m
  easylist: 81846-628, 8m
  easyprivacy: 50292-836, 8m
  urlhaus-1: 8470-0, 8m
  plowe-0: 3783-1, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2018 ms
 maxAssetCacheWait: 12 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  go-mpulse.net: 1
  newrelic.com: 1
  privacy-mgmt.com: 1
  tiqcdn.com: 1
  truste.com: 2
```
</details>

**Comment by Jackal12** [comment]
N/A

**Comment by dportvine** [comment]
Need an account. US IP.

<details>
<summary>Screen</summary>

![2024-02-29_180701](https://github.com/uBlockOrigin/uAssets/assets/111344219/461edc74-9fad-4f6c-a420-36dc5e090f64)
</details>

**Comment by mapx-** [comment]
@Jackal12 we have to investigate the issue and an account is required, are you willing to share user / pass of your account ?
(I'll provide an email address if you confirm it)

**Comment by liamengland1** [comment]
Fix: `@@||tags.tiqcdn.com/utag/*/utag.js$script,domain=www.pch.com`

`https://tags.tiqcdn.com/utag/pch/pchcomnew/prod/utag.js` required but blocked by `*$script,domain=pch.com,redirect=noopjs,3p`
