### ISSUE TITLE
[nsfw] fullpornnetwork.com: detection

### ISSUE THREAD

**Issue by twonfov** [uBlockOrigin/uAssets#22722]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fullpornnetwork.com/`
`https://thirstyplus.com/`

`https://abbiemaley.com/`
`https://analamateur.com/`
`https://analbbc.com/`
`https://analviolation.com/`
`https://analized.com/`
`https://baddaddypov.com/`
`https://badfamilypov.com/`
`https://badmommypov.com/`
`https://brokensluts.net/`
`https://cumdumpsterteens.com/`
`https://daughterjoi.com/`
`https://downtofuckdating.com/`
`https://dtfsluts.com/`
`https://girlfaction.com/`
`https://hergape.com/`
`https://homemadeanalwhores.com/`
`https://jamesdeen.com/`
`https://lesbiananalsluts.com/`
`https://mommyjoi.com/`
`https://mugfucked.com/`
`https://onlyprince.com/`
`https://pervertgallery.com/`
`https://porkvendors.com/`
`https://povperverts.net/`
`https://publicsexdate.com/`
`https://realfuckingdating.com/`
`https://shefucksonthefirstdate.com/`
`https://slutinspection.com/`
`https://slutsbts.com/`
`https://slutspov.com/`
`https://sluttybbws.com/`
`https://teasingandpleasing.com/`
`https://teenageanalsluts.com/`
`https://teenagecorruption.com/`
`https://teenagetryouts.com/`
`https://twistedvisual.com/`
`https://wifespov.com/`
`https://yourmomdoesanal.com/`
`https://yourmomdoesporn.com/`

### Category

detection

### Description

All sites listed in this report exhibit the same anti-blocker behavior.

`https://fullpornnetwork.com/` is the main network site.
`https://thirstyplus.com/` is the premium add-on/up-sell site.

The following are all sub-sites of the main network.

`https://abbiemaley.com/`
`https://analamateur.com/`
`https://analbbc.com/`
`https://analviolation.com/`
`https://analized.com/`
`https://baddaddypov.com/`
`https://badfamilypov.com/`
`https://badmommypov.com/`
`https://brokensluts.net/`
`https://cumdumpsterteens.com/`
`https://daughterjoi.com/`
`https://downtofuckdating.com/`
`https://dtfsluts.com/`
`https://girlfaction.com/`
`https://hergape.com/`
`https://homemadeanalwhores.com/`
`https://jamesdeen.com/`
`https://lesbiananalsluts.com/`
`https://mommyjoi.com/`
`https://mugfucked.com/`
`https://onlyprince.com/`
`https://pervertgallery.com/`
`https://porkvendors.com/`
`https://povperverts.net/`
`https://publicsexdate.com/`
`https://realfuckingdating.com/`
`https://shefucksonthefirstdate.com/`
`https://slutinspection.com/`
`https://slutsbts.com/`
`https://slutspov.com/`
`https://sluttybbws.com/`
`https://teasingandpleasing.com/`
`https://teenageanalsluts.com/`
`https://teenagecorruption.com/`
`https://teenagetryouts.com/`
`https://twistedvisual.com/`
`https://wifespov.com/`
`https://yourmomdoesanal.com/`
`https://yourmomdoesporn.com/`

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b6
Firefox: 123
filterset (summary):
 network: 124766
 cosmetic: 45567
 scriptlet: 18788
 html: 1734
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37329-104, 1m
  ublock-badware: 7721-14, 1m
  ublock-privacy: 741-0, 1m
  ublock-unbreak: 2281-2, 1m
  ublock-quick-fixes: 126-7, 1m
  easylist: 81851-244, 1m
  easyprivacy: 50320-56, 1m
  urlhaus-1: 8470-0, 1m
  plowe-0: 3783-1188, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 686 ms
 maxAssetCacheWait: 383 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  fpncash.com: 6
  googletagmanager.com: 1
 extended:
  ##[data-revive-zoneid]
```
</details>

**Comment by mapx-** [comment]
add 

`#@#[data-revive-zoneid]`

@Yuki2718 could this `##[data-revive-zoneid]` be removed from EL ?

**Comment by huyszn** [comment]
`yourmomdoesporn.com#@#[data-revive-zoneid]` is in uBO filters already

**Comment by Yuki2718** [comment]
Shoud be fine now https://github.com/easylist/easylist/commit/f7ed43ea62fccb02391bc42777a46582f277bac8
