### ISSUE TITLE
duckduckgo.com: breakage

### ISSUE THREAD

**Issue by MAGOLIS** [uBlockOrigin/uAssets#22736]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://duckduckgo.com/?q=what+caused+world+war+11%0A&t=fpas&ia=web`

### Category

breakage

### Description

Been facing serious spying and interferences by FinSpy actors. Github / DuckDuckgo is being automatically being prevented from loading properly and unlock Origin being disabled.
I have also seen websites not listed also being connected to my device eg
gfx.ms
afx.ms
tinycachefly.net

### Other extensions used

Conscripts
Decentraleyes
FirefoxRelay
Privacy Badger
ClearURLs
Search by image
Foxy Proxy
uBlockOrigin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 122
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: ?
 maxAssetCacheWait: ?
popupPanel:
 blocked: 7
 network:
  duckduckgo.com: 7
 extended:
  ##.js-footer-card
  ##.header--aside.js-header-aside > .header--aside__item > [class…
  ##.header__search-wrap + div.header--aside > div.header--aside__…
```
</details>

**Comment by MAGOLIS** [comment]
If you suggestion to improve my security and privacy please from FinSpy.

**Comment by gorhill** [comment]
> - [x] I did not answer truthfully to ALL the above checkboxes.

Please go through the prerequisite steps again, but this time follow them to the letter, and better describe what exactly is the breakage at the provided URL.
