### ISSUE TITLE
linkedin.com: nuisance

### ISSUE THREAD

**Issue by Dyonisos66** [uBlockOrigin/uAssets#22735]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.linkedin.com/signup/cold-join?session_redirect=https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Ffeed&trk=login_reg_redirect`

### Category

popups

### Description

open liks

### Other extensions used

ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 139629
 cosmetic: 52440
 scriptlet: 20268
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 22757-37, 51m
  easylist: 81940-303, 1h.16m Δ
  easyprivacy: 50319-251, 1h.16m Δ
  plowe-0: 3779-1195, 52m
  ublock-badware: 7717-157, 1h.16m Δ
  ublock-filters: 37135-420, 1h.16m Δ
  ublock-privacy: 745-6, 1h.16m Δ
  ublock-quick-fixes: 130-6, 1h.16m Δ
  ublock-unbreak: 2230-37, 1h.16m Δ
  urlhaus-1: 8210-0, 1h.16m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18975 ms (selfie)
 maxAssetCacheWait: 2975 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  gstatic.com: 1
  licdn.com: 3
```
</details>

**Comment by gorhill** [comment]
What do you call "popups"? Provide screenshots please.
