### ISSUE TITLE
[nsfw] altyazitube*.*: detection

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#22731]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://altyazitube22.lat/
```

### Description

Just to keep the track of the site changing domain regularly to circumvent our filters

### Other extensions used

NA

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126774
 cosmetic: 57488
 scriptlet: 20323
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  JPN-1: 14102-4, 1d.20m
  easylist: 81916-32, now Δ
  easyprivacy: 50319-32, now Δ
  plowe-0: 3782-1191, 4d.21h.33m
  ublock-badware: 7717-153, now Δ
  ublock-filters: 37142-361, now Δ
  ublock-privacy: 745-6, now Δ
  ublock-quick-fixes: 132-6, now Δ
  ublock-unbreak: 2230-36, now Δ
  urlhaus-1: 8470-0, 21h.15m
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 383 ms
 maxAssetCacheWait: 197 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  bobabillydirect.org: 1
  googlesyndication.com: 2
 extended:
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by Yuki2718** [comment]
Last commit https://github.com/uBlockOrigin/uAssets/commit/2730f1e16752310ba1f4b0d8d25b433e4b3567e3 so no need to check for now.

**Comment by stephenhawk8054** [comment]
Maybe use `^` if there's no other subdomains?

**Comment by Yuki2718** [comment]
> Maybe use `^` if there's no other subdomains?

I'm almost sure they will add subdomain if we do so.
