### ISSUE TITLE
kusonime.com: detection

### ISSUE THREAD

**Issue by ankarakata** [uBlockOrigin/uAssets#22730]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kusonime.com/toradora-bd-batch-subtitle-indonesia/`

### Category

detection

### Description

Adblock detection in kusonime website so the download link that should be like [1] this is not appear when ublock origin on

[1]
![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/33421037-1fbb-487a-b852-e6d4dce66d5b)

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/b77c6f7d-7230-4f7a-8d14-edcf34770af5)
![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/e8367233-2378-40f0-8501-31271ad7fd56)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/09f7e228-39ee-4ab8-944e-3692e65fae49)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 120
filterset (summary):
 network: 128917
 cosmetic: 51066
 scriptlet: 20166
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 9869-2, now
 default:
  user-filters: 1-0, never
  easylist: 81914-22, 1h.56m Δ
  easyprivacy: 50320-8, 1h.56m Δ
  plowe-0: 3783-1187, 1m
  ublock-badware: 7717-142, 1h.56m Δ
  ublock-filters: 37132-371, 1h.56m Δ
  ublock-privacy: 745-6, 1h.56m Δ
  ublock-quick-fixes: 126-6, 1h.56m Δ
  ublock-unbreak: 2230-34, 1h.56m Δ
  urlhaus-1: 8240-0, 1m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5043 ms (selfie)
 maxAssetCacheWait: 321 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  google.com: 3
  googletagmanager.com: 2
  nyaa-tan.my.id: 1
 extended:
  ##.iklanads
  ##.adsleft
  ##.adsright
  ##.advertiseText
  ##+js(trusted-replace-node-text, script, /\(\S+?window\.showAds\…
  ##+js(no-setTimeout-if, css_class.show)
  ##+js(set-constant, showada, true)
  ##+js(abort-on-property-write, app_advert)
```
</details>

**Comment by stephenhawk8054** [comment]
Next time please just continue in old thread: https://github.com/uBlockOrigin/uAssets/issues/18533
