### ISSUE TITLE
zh.moegirl.org.cn: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#22746]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://zh.moegirl.org.cn/Mainpage`

### Category

ads

### Description

There are some "capsule-cards" with advertisement tag("推广") showed in the page. The normal capsule-cards are linked to "https://zh.moegirl.org.cn/xxx", while the capsule-cards with advertisement tag are linked to "https://events.qooapp.io/xxx".

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/35957435/5c30c13d-4960-4b52-9252-3aa84eec6e28

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 125
filterset (summary):
 network: 248661
 cosmetic: 245604
 scriptlet: 49256
 html: 1990
listset (total-discarded, last-updated):
 added:
  adguard-generic: 78987-3884, now
  adguard-spyware-url: 1467-107, now
  adguard-spyware: 113941-1388, now
  adguard-social: 22198-53, now
  adguard-cookies: 28827-48, now
  ublock-cookies-adguard: 1014-11, now
  adguard-popup-overlays: 26684-986, now
  adguard-other-annoyances: 13915-410, now
  adguard-widgets: 2408-11, now
  fanboy-thirdparty_social: 68-3, now
  easylist-annoyances: 4413-288, now
  easylist-chat: 183-15, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 37343-104, now
  ublock-badware: 7730-14, now
  ublock-privacy: 737-0, now
  ublock-unbreak: 2293-2, now
  ublock-quick-fixes: 131-6, now
  easylist: 81996-1584, now
  easyprivacy: 50325-32206, now
  urlhaus-1: 8250-0, now
  plowe-0: 3779-1271, now
  CHN-0: 25438-208, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1305 ms (selfie)
 maxAssetCacheWait: 1026 ms
popupPanel:
 blocked: 6
 network:
  google.com: 5
  googletagmanager.com: 1
 extended:
  ##.swiper-slide-active.swiper-slide
  ##.swiper-wrapper
  ##+js(no-setTimeout-if, offsetHeight)
  ##+js(remove-class, skin-moeskin, body)
  ##+js(addEventListener-defuser, copy, jQuery!=="undefined")
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
moegirl.org.cn##.capsule-card:has(.n-tag)
```

@cjx82630 Sorry, can you check this?
