### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by Santu8801** [uBlockOrigin/uAssets#22745]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dropgalaxy.com/drive/bc3othhhkpyd`

### Category

detection

### Description

Dropgalaxy.com has detected that I'm using a adblocker 

### Other extensions used

Privacybadger extension 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 126037
 cosmetic: 37432
 scriptlet: 18879
 html: 1737
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37701-351, 1h.21m Δ
  ublock-badware: 7724-14, 1h.21m Δ
  ublock-privacy: 740-1, 1h.21m Δ
  ublock-unbreak: 2297-1, 1h.21m Δ
  ublock-quick-fixes: 131-1, 1h.21m Δ
  adguard-mobile: 9096-50, 3m
  easylist: 81974-16400, 1h.21m Δ
  easyprivacy: 50320-873, 1h.21m Δ
  urlhaus-1: 8250-0, 3m
  plowe-0: 3779-84, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1189 ms
 maxAssetCacheWait: 399 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  a-ads.com: 1
  cloudflareinsights.com: 2
 extended:
  ##+js(no-window-open-if)
  ##+js(trusted-set-constant, document.visibilityState, visible)
  ##+js(set-constant, supportedBrowsers, )
```
</details>

**Comment by D4niloMR** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/discussions/17361
