### ISSUE TITLE
huggingface.co: breakage

### ISSUE THREAD

**Issue by bimg21** [uBlockOrigin/uAssets#22756]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://huggingface.co/spaces/`

### Category

When allowing website scripts related to Huggingface but blocking others scripts and frames, HF chat doesn't display results, instead displays included error message. (When HF related website scripts are not allowed actively, it will not even display the chat widget)

![Screenshot from 2024-03-04 15-14-52](https://github.com/uBlockOrigin/uAssets/assets/124696075/8842811a-5df4-4acb-8a45-9108781506dc)
![Screenshot from 2024-03-04 15-17-45](https://github.com/uBlockOrigin/uAssets/assets/124696075/f54c27bc-730c-46c4-8d65-4b989ecd9408)

### Description

When allowing website scripts related to Huggingface but blocking others scripts and frames, HF chat doesn't display results, instead displays included error message. (When HF related website scripts are not allowed actively, it will not even display the chat widget)
![Screenshot from 2024-03-04 15-14-52](https://github.com/uBlockOrigin/uAssets/assets/124696075/1b00483c-b844-4bc8-b339-ab17d68201b7)
![Screenshot from 2024-03-04 15-17-45](https://github.com/uBlockOrigin/uAssets/assets/124696075/2cf19c17-2872-4310-9006-f23b05aa5120)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 259580
 cosmetic: 261230
 scriptlet: 49298
 html: 1995
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://hostfiles.frogeye.fr/firstparty-only-trackers-hosts.txt: 11907-0, 2m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt: 1472-6, 2m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt: 113726-33537, 2m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2589-156, 2m
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, 2m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-19, 2m
  adguard-generic: 79039-5472, 1m
  adguard-mobile: 9101-84, 1m
  block-lan: 61-0, 1m
  adguard-social: 22206-865, 1m
  fanboy-thirdparty_social: 68-0, 1m
  [15 lists not shown]: [too many]
 default:
  user-filters: 416-26, never
  ublock-filters: 37376-458, 1h.33m Δ
  ublock-badware: 7750-14, 1h.33m Δ
  ublock-privacy: 739-112, 1h.33m Δ
  ublock-unbreak: 2293-1, 1h.33m Δ
  easylist: 82120-623, 1h.33m Δ
  easyprivacy: 50327-1008, 1h.33m Δ
  urlhaus-1: 8255-0, 1m
  ublock-quick-fixes: 140-1, 1h.33m Δ
filterset (user): [array of 419 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 583 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1061 ms (selfie)
 maxAssetCacheWait: 477 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 no-remote-fonts: true
 network:
  huggingface.co: 2
  cloudflare.com: 2
  fonts.googleapis.com: 4
  googletagmanager.com: 1
  hf.space: 3
  segment.com: 1
  stripe.com: 1
```
</details>

**Comment by gorhill** [comment]
You are using [medium block mode through dynamic filtering](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode), it's for you to figure how to unbreak websites:

> High likelihood of web pages being broken: you have to be ready and willing to fix them when this happens.

You are blocking `cdjnjs.cloudflare.com`, this might be your issue.

If you are not willing to fix breakage arising of using advanced blocking modes, I suggest you just stick to default settings/lists.

**Comment by gorhill** [comment]
It's the 2nd time you open an issue which is caused by heavily customized uBO ([see](https://github.com/uBlockOrigin/uAssets/issues/20048)), so I will ask you to not open issues caused by your heavy customizations, it's your responsibility to verify that the issue exists with uBO default settings/lists, and if not, you will have to spend your own time investigating your customizations, do not ask volunteers to do this for you.

**Comment by bimg21** [comment]
I have verified the same issue in two other browsers with less customization and playing with allowing various 3-rd party websites. None of that worked.

**Comment by gorhill** [comment]
In a ne wbrowser profile, install uBO, visit "Filter lists" pane to ensure lists ar eup to date. Visit the site, and if broken, report using the chat icon in the popup panel. Explain exactly the steps needed to reproduce on our side, and what exactly is broken. If an account is needed, say so, and any other information which makes it easy to reproduce on our side without having to make guesses.

**Comment by bimg21** [comment]
Done in: [(https://github.com/uBlockOrigin/uAssets/issues/22766)]

**Comment by stephenhawk8054** [comment]
> Medium mode.

Test in a new Firefox profile with only uBO and its **default** settings. Don't change any settings manually yourself.

**Comment by gorhill** [comment]
It's a site issue, see <https://github.com/uBlockOrigin/uAssets/issues/22766#issuecomment-1978598873>, I can reproduce with no extension enabled.
