### ISSUE TITLE
jobs.trustaffingpartners.com: popups

### ISSUE THREAD

**Issue by formijunkmail** [uBlockOrigin/uAssets#22757]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jobs.trustaffingpartners.com/?source=LinkedIn`

### Category

popups

### Description

I went to this site and applied for the position. Thereafter, the page keeps opening up by itself in my Firefox browser every 10 minutes or so. Nothing stops it from happening. Multiple new windows will just keep opening the page and I have to close them every time. After adding uBlock, the page will still try to open, although now instead of the page appearing, the page opens but a series of colored balls just keeps showing on the middle of a white screen. How do I stop this madness?

### Other extensions used

I use Firefox with extensions for Malwarebytes, Zoom, Kaspersky, Tab Session Manager, Tree Style Tab, PDF Mage, Print Friendly & PDF, and uBlock Origin. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/162145707/0c24f275-93a1-4c8d-aca5-8d12e6445ce0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124826
 cosmetic: 45612
 scriptlet: 18834
 html: 1739
listset (total-discarded, last-updated):
 added:
  https://jobs.trustaffingpartners.com/?source=LinkedIn#/jobs/6406?utm_source=linkedin: 0-0, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37376-112, 14m
  ublock-badware: 7750-14, 14m
  ublock-privacy: 739-0, 6m Δ
  ublock-unbreak: 2293-0, 6m Δ
  ublock-quick-fixes: 140-1, 6m Δ
  easylist: 82120-624, 14m
  easyprivacy: 50327-864, 6m Δ
  urlhaus-1: 8255-0, 14m
  plowe-0: 3779-1, 14m
filterset (user): [empty]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 616 ms
 maxAssetCacheWait: 218 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  trustaffingpartners.com: 5
  cloudflare.com: 4
  google-analytics.com: 1
  googletagmanager.com: 2
  herefish.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
This is unrelated to uBO. You've some installed malware (either as an extension, some software, etc) on your system.

This is not the place to discuss that. You'll need to remove it on your own.
