### ISSUE TITLE
zonebourse.com: detection

### ISSUE THREAD

**Issue by titisouven** [uBlockOrigin/uAssets#22758]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.zonebourse.com/membre/-/valeurs/`

### Category

detection

### Description

The site has been promoting their subscription over free content a lot lately.
Now they've implemented an adblocker detector and ublock is causing the site to stop showing anything but the anti adblock popup.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124826
 cosmetic: 45616
 scriptlet: 18835
 html: 1739
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 37376-140, 1h.36m Δ
  ublock-badware: 7750-14, 1h.36m Δ
  ublock-privacy: 739-0, 1h.36m Δ
  ublock-unbreak: 2293-0, 1h.36m Δ
  ublock-quick-fixes: 140-1, 1h.36m Δ
  easylist: 82120-624, 1h.36m Δ
  easyprivacy: 50327-836, 1h.36m Δ
  urlhaus-1: 8255-0, now
  plowe-0: 3779-1, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 223 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  clarity.ms: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  sportslocalmedia.com: 2
 extended:
  ##+js(abort-current-script, $, AdBlocker)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how it looks like, and can you give exact link where you see anti-adb popup?

**Comment by titisouven** [comment]
Sure thing. I attached a screenshot of the popup.
It happens on any part of the site that's not the main page.
So checking actuality, specific articles, a list of values...
This is the actuality link: https://www.zonebourse.com/actualite-bourse/

It only happens on the french version of the site. English or dutch seem to be working fine and both redirect to https://www.marketscreener.com/ 

![Screenshot 2024-03-05 092610](https://github.com/uBlockOrigin/uAssets/assets/51990354/f0902fa0-4d2a-4a5f-907e-17a987ddb185)

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/13b40998-c4cc-403d-9438-fb885d86ad91)

Check if you are using any:

- Custom filters / filter lists,
- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by titisouven** [comment]
That strange...
I don't use custom filter and I just reset ublock to default settings, but still the same popup.
I'm using firefox with default settings.
It has a popup blocker, but there is no built-in ad-blocker.
Regarding other extensions, I've a limited amount of extensions for tab management and youtube.
I disabled all of them and still have the adblock popup.

The last 3 points are not applicable to me.

I now installed chrome, added ublock and navigated to zonnebourse.
After a few refreshes on the News link (Actualités), I got the prompt to login (guest limit reached).
After login and another refresh, I got the popup immediately (on a fresh install, all default settings).

![Screenshot 2024-03-05 115802](https://github.com/uBlockOrigin/uAssets/assets/51990354/56351f83-f956-4392-8b70-230860a55c3a)

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by titisouven** [comment]
I'm in Belgium.

**Comment by stephenhawk8054** [comment]
Hmm... I used VPN to Belgium but still can't reproduce it.

**Comment by titisouven** [comment]
I believe they might allow a certain number of browses through articles for new accounts before starting to block.
I have otherwise no idea why I would see the block immediately using my account on a fresh install of another browser.
Maybe you can try opening a dozen tabs from articles from the News link?

I tried adding rules to the filter to block the popup which seems to work, but there is another element darkening the page and preventing scrolling which I have more trouble with.
If I attempt a rule creation using the selector, it wants to create a rule for 
##.modal_backdrop
This does remove the darkening, but scrolling, moving in the page is still blocked.
If I don't make a rule and use the lightning button to remove that backdrop, then everything works fine. Darkening gone, scrolling working.
It's strange that the lightning (remove once) and selector (permanent rule making) have a different working.

**Comment by ItsProfessional** [comment]
@titisouven Can you create a fresh account on a fresh new browser/profile?
If you don't get detected, then it means the issue only occurs for a fraction of users. In this case, we'll need a test account to investigate the issue.

**Comment by titisouven** [comment]
I created a new account using another email address from my work laptop.
I'm not getting detected atm.

**Comment by ItsProfessional** [comment]
Can you share the credentials of that fresh account you just created? I'll provide an email if you agree.

**Comment by titisouven** [comment]
Sure thing. I can share the info.

**Comment by ItsProfessional** [comment]
@titisouven `itsprofessional1234@gmail.com`

**Comment by ItsProfessional** [comment]
@titisouven Does this work (on both of your accounts)?
```adb
zonebourse.com##+js(aopw, noopFunc)
```

Also, test for any breakage that occurs on the site after adding it.

**Comment by titisouven** [comment]
I don't think it breaks anything or at least what I can browse seem to work, but it doesn't prevent the issue.
The moment I click outside the home page, I get an orange popup asking me to disable adblock and subscribe.

Your rule does solve the issue on the Listes menu link which is not affected by that popup anymore.
That's probably because of what I wrote in my mail.
It seems there are 2 different scripts for that same popup and the Listes link uses a script that is now blocked thanks to your rule.
But the script responsible for the same popup on Actualités is still working.

**Comment by ItsProfessional** [comment]
@titisouven Can you test:
```adb
zonebourse.com##+js(set, onloadUI, noopFunc)
zonebourse.com##+js(trusted-replace-argument, document.getElementById, 0, null, condition, modal)
```

**Comment by stephenhawk8054** [comment]
@ItsProfessional OP would need dev build to use the 2nd filter btw

**Comment by ItsProfessional** [comment]
@stephenhawk8054 It's included in the latest release: https://github.com/gorhill/uBlock/releases/tag/1.56.0

**Comment by stephenhawk8054** [comment]
@ItsProfessional I mean to use the trusted scriptlets in "My filters", OP needs to enable via advanced settings in stable release or use dev build

**Comment by titisouven** [comment]
@ItsProfessional 
I added the line and enabled advanced settings.
The 2nd line fixed the issue on both computers for the Actualités link and anywhere else I still saw the popup.
My own account and the newly created test account can now both freely navigate the site without any hindrance.

Thank you very much, the both of you, for the time you spend solving this.
You've made my day ;)

**Comment by ItsProfessional** [comment]
Actually, I just realized that the filters I provided might end up blocking all popups, not just the detection one.
The popup on the fresh account, on translation, while very similar to the one OP provided, seems to be directly asking about a subscription, and there's no mention of detection.

@titisouven Is the popup only shown for this, or does it ask for more?

**Comment by titisouven** [comment]
I believe the popup is shown for the adblock detection and for browsing more than 5 (or 10?) articles a day.
