### ISSUE TITLE
gplinks.co: detection

### ISSUE THREAD

**Issue by spidy2356** [uBlockOrigin/uAssets#22754]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
main link:https://gplinks.co/qsc6P

and the redirect sites where pop up detects are
1. eternalcbse.in
2. foreverhealth.in
```

### Description

adblock detection pop up appear.

### Other extensions used

not related to adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/101243689/c1f8e1fc-2ac3-494f-bb4a-067f845f0750)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 128753
 cosmetic: 117888
 scriptlet: 25148
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4413-32, now
  easylist-chat: 183-0, now
  easylist-newsletters: 7084-14, now
  easylist-notifications: 2954-86, now
  fanboy-cookiemonster: 50241-182, now
  fanboy-social: 15825-15, now
  ublock-cookies-easylist: 1015-3, now
 default:
  user-filters: 17-0, never
  easylist: 81997-13, now
  easyprivacy: 50325-90, now
  plowe-0: 3779-1186, now
  ublock-badware: 7746-142, now
  ublock-filters: 37185-372, now
  ublock-privacy: 743-8, now
  ublock-quick-fixes: 143-7, 7m Δ
  ublock-unbreak: 2236-36, now
  urlhaus-1: 8245-5, 7m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3852 ms (selfie)
 maxAssetCacheWait: 276 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  digislots.in: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  scriptcdn.net: 1
 extended:
  ###ast-scroll-top
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by ItsProfessional** [comment]
Whenever you (or anyone) sees a new gplinks domain, comment here.

**Comment by spidy2356** [comment]
@ItsProfessional I search gplink keyword before create new issue. thanks for inform.
but detection still not fix yet. should I comment again on ongoing thread??

**Comment by spidy2356** [comment]
@ItsProfessional I already did that day..but didn't fixed yet
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-8665992
