### ISSUE TITLE
hktvmall.com: breakage

### ISSUE THREAD

**Issue by lemongrasse** [uBlockOrigin/uAssets#22764]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.hktvmall.com/hktv/en/search_a?keyword=food
https://www.hktvmall.com/hktv/zh/search_a?keyword=food
```

### Description

Searching any keyword, E.g. "food" at hktvmall.com has led to a breakage where the website stopped listing any products.

Disabling the plugin, website works and listing the products again.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Add-on when activated:
![hktvmall](https://github.com/uBlockOrigin/uAssets/assets/162273262/61487d87-0b12-457e-8b9a-a6996acf43da)
Add-on when disabled:
![hktvmall 2](https://github.com/uBlockOrigin/uAssets/assets/162273262/ea7ea90d-467f-4a99-a963-80c37bbbd324)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 120843
 cosmetic: 45615
 scriptlet: 18838
 html: 1739
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
 default:
  user-filters: 0-0, never
  ublock-filters: 37378-112, 1h.58m Δ
  ublock-badware: 7750-14, 1h.58m Δ
  ublock-privacy: 739-0, 1h.58m Δ
  ublock-unbreak: 2293-0, 1h.58m Δ
  ublock-quick-fixes: 142-1, 1h.58m Δ
  easylist: 82229-624, 1h.58m Δ
  easyprivacy: 50327-864, 1h.58m Δ
  urlhaus-1: 4165-0, 32m
  plowe-0: 3779-1, 32m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 30197 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  hktvmall.com: 1
  facebook.net: 1
  googleadservices.com: 1
  googletagmanager.com: 1
 extended:
  ##.adLabel
```
</details>

**Comment by stephenhawk8054** [comment]
cc @Yuki2718
