### ISSUE TITLE
free.fr phishing group: badware

### ISSUE THREAD

**Issue by orbotimn75** [uBlockOrigin/uAssets#22765]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://espacefidelitefree.fr/`

### Category

badware

### Description

This site  `https://espacefidelitefree.fr/` is a phishing campaign against customers Free mobile.

The legitimate page can be found at : `https://mobile.free.fr/`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 135955
 cosmetic: 52462
 scriptlet: 18976
 html: 1739
listset (total-discarded, last-updated):
 default:
  user-filters: 10-1, never
  ublock-filters: 37378-181, 27m Δ
  ublock-badware: 7750-14, 27m Δ
  ublock-privacy: 739-0, now
  ublock-unbreak: 2293-0, 27m Δ
  easylist: 82229-915, 27m Δ
  easyprivacy: 50327-1064, 27m Δ
  urlhaus-1: 4165-0, now
  plowe-0: 3779-1, now
  FRA-0: 22821-110, now
  ublock-quick-fixes: 142-1, 27m Δ
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 25 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1292 ms (selfie)
 maxAssetCacheWait: 153 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by iam-py-test** [comment]
It seems they are using `shopflarehub.com` for their payments: https://tria.ge/240305-2bg53abb8x/behavioral1 (CloudFlared). It appears to be malicious and [is detected by 10 security vendors on VirusTotal](https://www.virustotal.com/gui/url/716d44ef0981fada4907f6c77d18b8c3915ddfaf29c232d8a794d4aff3d3c904).
Thank you

**Comment by orbotimn75** [comment]
New phishing site http://mobile.i-free.fr

The legitimate page can be found at : https://mobile.free.fr/

**Comment by orbotimn75** [comment]
Phishing link  https://www.gatekeeperapp.net/gatekeeper/https%3A%2F%2Fwww.gatekeeperapp.net%2Fgatekeeper%2Fhttps%253A%252F%252F5qin.muelo.fr%252F   redirect to this phishing site http://mobile.i-free.fr/

**Comment by stephenhawk8054** [comment]
> `http://mobile.i-free.fr/`

Hmm... The link returns 403 error for me

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/021497af-02ff-4619-a304-21853a75bc24)

Same as `https://www.gatekeeperapp.net/gatekeeper/https%3A%2F%2Fwww.gatekeeperapp.net%2Fgatekeeper%2Fhttps%253A%252F%252F5qin.muelo.fr%252F`, it redirects to `https://5qin.muelo.fr/` which returns 403 too.

**Comment by orbotimn75** [comment]
if you are a Free mobile customer, this is what appears when you click on the link : 
![Screenshot_20240314-121129_Firefox](https://github.com/uBlockOrigin/uAssets/assets/160862428/2e406a0d-5e30-455e-8c83-40dd7b290374)

**Comment by orbotimn75** [comment]
phishing site  https://free-mobil.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/ or https://mobile.free.fr/

**Comment by stephenhawk8054** [comment]
Hmm... Is the whole domain `hubside.fr` a phishing domain? If so, we can block the whole domain instead of each subdomain.

**Comment by orbotimn75** [comment]
solution@hubside.com suggests using the abuse form below, but it doesn't seem very effective :
 

Nous vous remercions pour votre email.
Pour prendre en charge votre demande, nous vous invitons à remplir le formulaire dédié que vous trouverez [ici](https://forms.office.com/Pages/ResponsePage.aspx?id=gC8xhjohE0ybO1XgqklLmL3cZPMz3JFJl5pJ8XE5fDRUMTVSREdSU1pLSDYyNUFGQkxQUlowTEVDQyQlQCN0PWcu)

Thank you for your email.
To process your request, please fill in the dedicated form here  [ici](https://forms.office.com/Pages/ResponsePage.aspx?id=gC8xhjohE0ybO1XgqklLmL3cZPMz3JFJl5pJ8XE5fDRUMTVSREdSU1pLSDYyNUFGQkxQUlowTEVDQyQlQCN0PWcu)

**Comment by ItsProfessional** [comment]
> Hmm... Is the whole domain hubside.fr a phishing domain? If so, we can block the whole domain instead of each subdomain.

https://github.com/uBlockOrigin/uAssets/commit/6b0971d9132fe1b28ebdf7059ff285eb1ad39761#commitcomment-138936944

**Comment by orbotimn75** [comment]
new phishing from domain hubside.fr => https://free-service.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
Phishing  from domain https://www.hubside.com/ =>  https://freezimail.hubside.fr/;https://zimbrafreemail.hubside.fr/;https://zimbra-inbox.hubside.fr/;https://free-mobile241.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
phishing site https://pointsfreemobile.com/fr/

The legitimate page can be found at :  https://mobile.free.fr/

**Comment by orbotimn75** [comment]
Phishing =>  https://free-mob2584.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
Phishing => https://free-mob215478.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
Phishing =>  https://zimbrafree-fr.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by ItsProfessional** [comment]
These phishing sites for `free.fr` are being created very frequently; keep the issue open.

**Comment by orbotimn75** [comment]
Phishing : 

https://web-free.hubside.fr/ 
https://zimbra-free-com.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
phishing site : 

https://free-mobi20i2582.hubside.fr/
https://zimbra-free-email.hubside.fr/
https://freezimbra.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/ or https://mobile.free.fr/

**Comment by JobcenterTycoon** [comment]
Do you work for `free.fr` and from where do you get all the domains?

**Comment by orbotimn75** [comment]
Yes i work for free.fr, these are users and subscribers free.fr who sends us the phishing emails received . You can see an example below  :

INFO MAIL


Cher Utilisateur Zimbra,

Zimbra vous informe de la désactivation de votre compte conformément aux règlements si vous ne confirmez pas votre identifiant.
Car passé la date du   Lundi 1 Avril 2024 votre compte sera verrouillé.

Identifiez-vous en cliquant sur le bouton ci-dessous:

[Réactiver mon compte](http://zimbra-free-com.hubside.fr/)
Merci de votre confiance

**Comment by orbotimn75** [comment]
phishing : 

shortlink https://appurl.io/kJA_ItlhkW  redirect to  https://web0mail.hubside.fr/

**Comment by orbotimn75** [comment]
Phishing : https://free-mobile0021547.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
New phishing sites from domain hubside.fr/

https://free-information.hubside.fr/
https://mobiles.hubside.fr/
https://freemailzimbra.hubside.fr/
https://rivita3106felibgcom.hubside.fr/
https://info-free.hubside.fr/
https://emails-free.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

**Comment by orbotimn75** [comment]
New phishing sites from domain hubside.fr/

https://freema.hubside.fr/

https://free-zimbra.hubside.fr/

https://free-mobile1540478.hubside.fr/

https://freewebzim.hubside.fr/

http://acceder-a-mon-free.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/  https://subscribe.free.fr/login/

**Comment by orbotimn75** [comment]
phishing site from domain hubside.fr/

https://my-acount-free.hubside.fr/

The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/ https://subscribe.free.fr/login/
