### ISSUE TITLE
binged.in: detection

### ISSUE THREAD

**Issue by JinEnMok** [uBlockOrigin/uAssets#22769]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://binged.in/`

### Category

detection

### Description

Binged.in displays an "UwU" placeholder and doesn't load assets when the developer console is open, as well as displaying a "You don't have permission to use DEVTOOL" error in the console. See also on [Reddit](https://www.reddit.com/r/Piracy/comments/1b6tboa/bingedin_website_wont_allow_me_to_inspect_the_page/)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-05 at 13-57-23 Spaceman](https://github.com/uBlockOrigin/uAssets/assets/30158696/9a46e29b-36b4-4f29-95aa-fe4b7626988b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 125
filterset (summary):
 network: 137560
 cosmetic: 66508
 scriptlet: 20211
 html: 1755
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 37386-112, 1h.41m Δ
  ublock-badware: 7755-14, 1h.41m Δ
  ublock-privacy: 739-0, 1h.41m Δ
  ublock-unbreak: 2293-0, 1h.41m Δ
  ublock-quick-fixes: 142-1, 1h.41m Δ
  easylist: 81572-645, 1h.41m Δ
  easyprivacy: 50327-864, 1h.41m Δ
  urlhaus-1: 4165-0, now
  plowe-0: 3779-1, now
  RUS-0: 39786-117, 1h.41m Δ
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 59008 ms (selfie)
 maxAssetCacheWait: 2931 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  goatcounter.com: 1
 extended:
  ##+js(no-setInterval-if, /devtools|0x/)
  ##+js(set-constant, console.clear, trueFunc)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, __Y)
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-current-script, navigator, FingerprintJS)
```
</details>

**Comment by JinEnMok** [comment]
@JobcenterTycoon I'm still getting uwu'd with that... assuming I installed it correctly

**Comment by stephenhawk8054** [comment]
Keep the above 2 and add this one also:

```adb
vidsrc.*##+js(nosiif, devtool)
```

**Comment by JobcenterTycoon** [comment]
Maybe clearing the website cache also helps.

**Comment by JinEnMok** [comment]
@stephenhawk8054 that seems to do the trick. 

Will this be added to some standard list?

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon `vidsrc.*##+js(acs, RegExp.prototype.toString)` is quite broad. I think maybe we can put it in Annoyance list first to see if there's any breakage or not.

**Comment by JobcenterTycoon** [comment]
Works fine for me. But why base list? Why not adding these filter to the annoyance list

```
vidsrc.*##+js(acs, RegExp.prototype.toString, .join(""))
vidsrc.*##+js(aeld, keydown, 123)
vidsrc.*##+js(nosiif, devtool)
vidsrc.*##+js(set, console.clear, trueFunc)
```

I also see anti F12 `vidsrc.*##+js(aeld, keydown, 123)` will fix this.

**Comment by stephenhawk8054** [comment]
Yeah I agree. I was also about to do so. I'll move them to annoyance list.

**Comment by ItsProfessional** [comment]
@JobcenterTycoon why `vidsrc.*##+js(aeld, keydown, 123)` instead of just `vidsrc.*##+js(aeld, keydown)`?
They could easily make it so that the listener callback no longer contains "123" (e.g. by using `atob`)

**Comment by JobcenterTycoon** [comment]
Because they also run legit code on the `keydown` event like m = mute. 123 is the key code of the F12 key so the chance of breakage is pretty small.

**Comment by An0n-00** [comment]
# Request to reopen this issue: 
The Issue might have been resolved, but it came back. Binged (which is now freek) and all the sites using `embed.su` as their content provider have the same issue... 

Here a screenshot: 
![image](https://github.com/user-attachments/assets/77a27135-a286-4c6c-9e1d-b8a14e5a9c54)
> [!Note]
> I am using Brave and UBO **with** several block lists (not only the default ones)

To trigger this, you need to have the dev tools open already before the iframe starts loading (e.a. load the site with dev tool open).

should i open a new issue for this?
thanks!

**Comment by stephenhawk8054** [comment]
Just continue commenting here.

**Comment by An0n-00** [comment]
fixed. thanks!
