### ISSUE TITLE
tuttoandroid.net: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#22761]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tuttoandroid.net/`
`https://www.tuttoandroid.net/news/2024/03/01/unieuro-offerte-android-google-days-volantino-marzo-1033157/`

### Category

nuisance

### Description

No video without accepting cookies.
Related Adguard fix:
https://github.com/AdguardTeam/AdguardFilters/commit/a27a3183b985921417fd78d769ef058eb1d56e10

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![f](https://github.com/uBlockOrigin/uAssets/assets/1375223/a3d89269-6434-443d-8989-de8905168828)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 133955
 cosmetic: 139960
 scriptlet: 27700
 html: 1995
listset (total-discarded, last-updated):
 added:
  adguard-social: 22196-156, now
  adguard-cookies: 28861-49, now
  ublock-cookies-adguard: 1017-0, now
  adguard-popup-overlays: 26696-910, now
  adguard-mobile-app-banners: 5050-7, now
  adguard-other-annoyances: 13923-67, now
  adguard-widgets: 2410-1, now
  ublock-annoyances: 6794-1032, now Δ
  ITA-0: 8292-20, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37378-452, now Δ
  ublock-badware: 7750-14, now Δ
  ublock-privacy: 739-0, now Δ
  ublock-unbreak: 2293-0, now Δ
  ublock-quick-fixes: 142-1, now Δ
  easylist: 82212-691, now Δ
  easyprivacy: 50327-949, now Δ
  urlhaus-1: 8255-0, now
  plowe-0: 3779-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 2079 ms
 maxAssetCacheWait: 1400 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  tuttoandroid.net: 2
  doubleclick.net: 1
  googletagmanager.com: 2
  iubenda.com: 1
 extended:
  ##.banner
  ###admputop2
  ###adwallpaper
  ###admputop
  ##.admputop
  ###admpumiddle
  ###admpumiddle2
  ##.card.dark:has(span:has-text(Adv))
  ##html:style(overflow: auto !important;)
  ##+js(prevent-fetch, www3.doubleclick.net)
```
</details>

**Comment by mapx-** [comment]
I'm able to watch the video on your example page using ELC.

or add only 
`||iubenda.com^$3p`

and test again
