### ISSUE TITLE
tiktokcounter.net: detection

### ISSUE THREAD

**Issue by M2MTek** [uBlockOrigin/uAssets#22774]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokcounter.net/digital-marketing/the-best-marketing-platforms-for-your-website/`

### Category

detection

### Description

- Open `https://ctr.sh/xawKp`
- Now it will be redirected to [tiktokcounter.net](https://tiktokcounter.net/) (attached image)
- Tiktokcounter.net can detect adblock (RED BANNER) and the counter was extended from 15s to 150s. When the counter reached 0s, click on "Continue" and it will redirected to another ads, which also can detect adblock and increase the counter to 150s. This will be repeated 5 times in total.

### Other extensions used

Internet Download Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![xx](https://github.com/uBlockOrigin/uAssets/assets/162337334/495885d8-21c1-4ea8-8c27-26df083b23ff)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 120727
 cosmetic: 46828
 scriptlet: 20364
 html: 0
listset (total-discarded, last-updated):
 added:
  VIE-1: 1865-0, now
 default:
  user-filters: 3-0, never
  easylist: 81701-37, now
  easyprivacy: 50329-9, now
  plowe-0: 3779-1187, now
  ublock-badware: 7751-143, now
  ublock-filters: 37185-359, now
  ublock-privacy: 743-6, now
  ublock-quick-fixes: 143-7, now
  ublock-unbreak: 2236-33, now
  urlhaus-1: 4115-0, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 171 ms (selfie)
 maxAssetCacheWait: 99 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  profitsfly.com: 2
 extended:
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(abort-on-property-read, adbDetecte2d)
```
</details>

**Comment by Daxy7** [comment]
shortener*
