### ISSUE TITLE
15min.lt: breakage

### ISSUE THREAD

**Issue by Vartotojas1234** [uBlockOrigin/uAssets#22776]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.15min.lt/video/is-drono-vilniuje-rastas-sprogmuo-kasant-zeme-uztikta-sena-bomba-251004`

### Category

breakage

### Description

Video does not work when the blocking program is turned on

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/uBlockOrigin/uAssets/assets/24992139/88856245-c68b-4817-a6c3-19a02bafe065)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 372874
 cosmetic: 259968
 scriptlet: 50611
 html: 2012
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79090-5622, 4m
  adguard-spyware: 113728-33595, 4m
  curben-phishing: 116116-43, 4m
  adguard-social: 22199-866, 4m
  adguard-cookies: 28863-69, 4m
  ublock-cookies-adguard: 1015-0, 4m
  adguard-popup-overlays: 26708-1681, 4m
  adguard-mobile-app-banners: 5057-1081, 4m
  adguard-other-annoyances: 13928-586, 4m
  adguard-widgets: 2411-1, 4m
  easylist-annoyances: 4413-126, 4m
  easylist-chat: 185-15, 4m
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37403-104, 4m
  ublock-badware: 7755-14, 4m
  ublock-privacy: 739-0, 4m
  ublock-unbreak: 2293-2, 4m
  ublock-quick-fixes: 152-18, 4m
  easylist: 81722-899, 4m
  easyprivacy: 50333-1108, 4m
  urlhaus-1: 4115-0, 4m
  plowe-0: 3779-1, 4m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3701 ms
 maxAssetCacheWait: 2326 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  15min.lt: 1
  cloudflareinsights.com: 4
  cxense.com: 3
  dimatter.ai: 2
  doubleclick.net: 3
  ebxcdn.com: 1
  gemius.pl: 2
  googlesyndication.com: 1
  imasdk.googleapis.com: 2
  inmobi.com: 1
  npttech.com: 1
  piano.io: 1
  rehabilitatereason.com: 1
  teads.tv: 1
 extended:
  ###fb-root:not(body):not(html)
  ##.ads-cnt
  ##.share--facebook
  ##.share--twitter
  ##.icomoon-twitter
  ##.dfp
  ##.page-item-lazyload
  ##body > div[class][style="display: block;"]
  ##.share--vertical
  ##.wrapper:style(margin-top: 0 !important)
  ##+js(no-setTimeout-if, insertBefore)
  ##+js(abort-on-property-read, _renderAdblock)
  ##+js(abort-on-stack-trace, Promise, inlineScript)
```
</details>

**Comment by mapx-** [comment]
broken by `AdGuard – Ads`

add
`15min.lt#@#+js(aost, Promise, inlineScript)`

@Alex-302

**Comment by Alex-302** [comment]
Fixed.
