### ISSUE TITLE
vs.lv: breakage

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#22775]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://vs.lv/raksts/sabiedriba/2023/12/21/riga-satiksmei-atverta-austrumu-magistrale
```

### Description

Articles under section "REKOMENDĒJAM" are not visible.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-05 194602](https://github.com/uBlockOrigin/uAssets/assets/43014154/7b9496f5-7598-4bf5-9306-be589ef461dc)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
add

```
@@||code.giraff.io/data/widget-vslv.js$script,domain=vs.lv
@@||data.giraff.io/track/vslv.js$script,domain=vs.lv
@@||a.giraff.io/data/*json$script,domain=vs.lv
```

@ryanbr

**Comment by ryanbr** [comment]
all 3 needed?

**Comment by mapx-** [comment]
yes

**Comment by ryanbr** [comment]
Those are ads linking to `https://code.directadvert.ru/click/` it should be blocked?

**Comment by ryanbr** [comment]
Maybe more of case to move giraff.io to EL.
