### ISSUE TITLE
tiktok.com: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22777]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.tiktok.com/@legendaryjay_/video/7340835370520759595?_r=1&_t=8kJE4polGhl
```

### Description

login banner 

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/100969549/9b60fb35-3d53-48ff-8912-e7a0194ac3b1)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 122
filterset (summary):
 network: 123208
 cosmetic: 52394
 scriptlet: 25014
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6826-30, now Δ
 default:
  user-filters: 0-0, never
  DEU-0: 7315-0, now
  easylist: 81722-21, now
  easyprivacy: 50333-16, now
  plowe-0: 3782-1188, 11d.37m
  ublock-badware: 8010-143, now Δ
  ublock-filters: 37415-382, now Δ
  ublock-privacy: 746-6, now Δ
  ublock-quick-fixes: 109-6, now Δ
  ublock-unbreak: 2223-35, now Δ
  urlhaus-1: 4115-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 427 ms (selfie)
 maxAssetCacheWait: 233 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 14
 network:
  tiktok.com: 2
  byteoversea.com: 4
  tiktokv.com: 8
 extended:
  ##+js(addEventListener-defuser, contextmenu, preventDefault)

```
</details>

**Comment by gorhill** [comment]
This works for me:

    tiktok.com##body > [class*="DivModalContainer"]:has(#login-modal)

Can be added to EasyList.

cc @ryanbr

**Comment by dportvine** [comment]
> tiktok.com##body > [class*="DivModalContainer"]:has(#login-modal)

Scrolling is still locked.

<details>
<summary>Screen</summary>

![2024-03-06_092210](https://github.com/uBlockOrigin/uAssets/assets/111344219/1aebe01e-4a76-4716-a38e-406003bad0f4)
</details>

**Comment by ryanbr** [comment]
Would affect users who would want to actually login

**Comment by big-cat-loaf** [comment]
It doesn't matter if it's locked; I just want to watch the video with the link that I get. When I want to use tiktok.com, I create an account.
