### ISSUE TITLE
nra.lv: breakage

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#22773]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://tautaruna.nra.lv/kriminali/447065-daugavpili-huligani-izdara-ko-tadu-kas-gandriz-noved-pie-lielas-nelaimes/
```

### Description

Video does not play when the play button is clicked. Red error message is displayed. This does not happen with Ublock turned off.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-05 161457](https://github.com/uBlockOrigin/uAssets/assets/43014154/4d5d75bd-e7e2-4138-ae89-142e79d7a5fd)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by gorhill** [comment]
It plays fine when clinking the "play" button to open the video in its original site instead when embedded:

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/d3eacfa2-6283-4714-8ee6-5adb65e51af3)

Looks like a difficult fix, I couldn't figure where this fails.

**Comment by mapx-** [comment]
If I disable uBO => the video ads are running correctly but then I get the same error. It seems to be a site issue.
