### ISSUE TITLE
hulu.com: breakage

### ISSUE THREAD

**Issue by pendragonmikel** [uBlockOrigin/uAssets#22788]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hulu.com/`

### Category

breakage

### Description

Video will not play when in desktop mode on the Hulu site with ublock enabled. If I disable it, video plays fine. Was working beautifully a few days ago.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240305_221321_Firefox](https://github.com/uBlockOrigin/uAssets/assets/102331382/b717ea99-e93e-42e9-afda-733db8972c19)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 124958
 cosmetic: 37477
 scriptlet: 18912
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37760-390, 12m
  ublock-badware: 7749-19, 12m
  ublock-privacy: 740-1, 12m
  ublock-unbreak: 2298-1, 12m
  ublock-quick-fixes: 154-1, 12m
  adguard-mobile: 9109-133, 12m
  easylist: 82211-16402, 12m
  easyprivacy: 50327-845, 12m
  urlhaus-1: 6905-0, 12m
  plowe-0: 3779-1, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2341 ms
 maxAssetCacheWait: 16 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 93
 network:
  hulu.com: 65
  ads-twitter.com: 1
  adsrvr.org: 1
  conviva.com: 3
  demdex.net: 3
  facebook.com: 1
  ipredictive.com: 2
  omtrdc.net: 4
  sc-static.net: 5
  sentry.io: 1
  tealiumiq.com: 4
  tiktok.com: 1
  yimg.com: 2
 extended:
  ##+js(set-constant, Object.prototype._parseVAST, noopFunc)
  ##+js(set-constant, Object.prototype.createAdBlocker, noopFunc)
  ##+js(set-constant, Object.prototype.isAdPeriod, falseFunc)
  ##+js(json-prune-fetch-response, breaks pause_ads video_metadata…
  ##+js(json-prune, breaks pause_ads video_metadata.end_credits_ti…
  ##+js(xml-prune, `xpath(//*[name()="MPD"]/@mediaPresentationDura…
```
</details>

**Comment by mapx-** [comment]
@pendragonmikel are you willing to share user / pass of your account ? (I'll provide an email address if you confirm it)

**Comment by FTOtter** [comment]
I'm confused as to why my report was closed and redirected here when it appears to have nothing in common with this issue?
