### ISSUE TITLE
lemonde.fr: breakage

### ISSUE THREAD

**Issue by polo199** [uBlockOrigin/uAssets#22783]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lemonde.fr/economie/article/2024/03/05/cnews-la-decision-du-conseil-d-etat-a-vocation-a-raffermir-la-liberte-d-expression_6220285_3234.html`

### Category

breakage

### Description

Missing suscriber features when reading any article. Features are 3 buttons that allow for bookmarking, offering or sharing the article. Quite useful when you're a suscriber.
Seems to be blocked by ".meta_social" according to the DOM Inspector.
Not an ad or a nuisance according to me. However, if it is considered as such, I would be grateful to anyone helping me build an exception just for these buttons (tried to but I did not succeed).

Unfortunately, the buttons only appear when you're a suscriber.

![lemonde_NO-uBlock_OK](https://github.com/uBlockOrigin/uAssets/assets/130090935/be46756d-792e-4475-85d7-f95e8d9d491b)
![lemonde_uBlock_NOK](https://github.com/uBlockOrigin/uAssets/assets/130090935/70606c94-c1f3-48a1-94e9-cec508b02e79)
![lemonde_DOM-Inspector](https://github.com/uBlockOrigin/uAssets/assets/130090935/8a66ffaa-f072-48c7-a07a-a9d6860751c7)
![lemonde_Firefox-Inspector](https://github.com/uBlockOrigin/uAssets/assets/130090935/1485f60c-da5a-4680-aa6f-a236470157aa)

I would be glad to help if you need a suscriber to fix this issue. Thanks in advance for you help.

### Other extensions used

Metamask
Tampermonkey

Both inactive on the www.lemonde.fr domain.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 244665
 cosmetic: 245538
 scriptlet: 49393
 html: 1996
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76975-76975, 6m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97203-97203, 6m
  ublock-annoyances: 6799-11, 7m Δ
  adguard-generic: 79066-5563, 6m
  adguard-social: 22200-860, 6m
  fanboy-cookiemonster: 50258-3882, 6m
  fanboy-social: 15828-10, 8m
  adguard-spyware-url: 1470-107, 6m
  adguard-spyware: 113728-33508, 6m
  adguard-cookies: 28866-74, 6m
  adguard-popup-overlays: 26712-1703, 6m
  adguard-mobile-app-banners: 5057-1082, 6m
  [8 lists not shown]: [too many]
 default:
  ublock-filters: 37403-456, 7m Δ
  ublock-badware: 7755-14, 7m Δ
  ublock-privacy: 739-0, 7m Δ
  ublock-unbreak: 2293-0, 7m Δ
  easylist: 81722-1002, 7m Δ
  easyprivacy: 50333-1176, 7m Δ
  plowe-0: 3779-1, 6m
  FRA-0: 22824-128, 6m
  urlhaus-1: 4115-0, 8m
  ublock-quick-fixes: 152-1, 7m Δ
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 213 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13114 ms
 maxAssetCacheWait: 2962 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  lemonde.fr: 1
  amplitude.com: 1
  appsflyer.com: 1
  batch.com: 2
  ebxcdn.com: 1
  sirius.press: 1
 extended:
  ##.message--register
  ##.meta__social
  ##.dfp-slot
  ###dfp-habillage
  ##.js-social
  ##.OUTBRAIN
  ##.footer__social
  ##body,html:style(height: auto !important; overflow: auto !impor…
```
</details>

**Comment by mapx-** [comment]
I notified the maintainers

**Comment by mapx-** [comment]
@polo199 however, you could disable the social lists or use those exceptions as your custom filters

**Comment by Alex-302** [comment]
In AdGuard Social filter I unblocked only Favorites button, but sharing is still blocked.
