### ISSUE TITLE
twitter.com: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#22780]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://twitter.com/flyingcat
```

### Description

forcing me to login and redirecting me + banner 
https://twitter.com/flyingcat  to https://twitter.com/i/flow/login?redirect_after_login=%2Fflyingcat 

### Other extensions used

non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-05 192323](https://github.com/uBlockOrigin/uAssets/assets/100969549/7524f171-14b7-4713-b897-a3553ab08033)
![image](https://github.com/uBlockOrigin/uAssets/assets/100969549/17138467-dba5-4240-b59e-0c6077a78796)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 123205
 cosmetic: 52394
 scriptlet: 25014
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6826-30, 14m Δ
 default:
  user-filters: 0-0, never
  DEU-0: 7315-0, 14m
  easylist: 81722-21, 14m
  easyprivacy: 50333-16, 14m
  plowe-0: 3779-1188, now
  ublock-badware: 8010-143, 14m Δ
  ublock-filters: 37415-382, 14m Δ
  ublock-privacy: 746-6, 14m Δ
  ublock-quick-fixes: 109-6, 14m Δ
  ublock-unbreak: 2223-35, 14m Δ
  urlhaus-1: 4115-0, 14m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2468 ms (selfie)
 maxAssetCacheWait: 455 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  twitter.com: 5
  google.com: 3
 extended:
  ##html:style(overflow:auto!important)

```
</details>

**Comment by gorhill** [comment]
Login wall is not something uBO can bypass.

**Comment by gorhill** [comment]
Seems to be a server-side login wall, not something uBO can bypass.

**Comment by ItsProfessional** [comment]
Regardless, login walls aren't something we bypass (afaik).
