### ISSUE TITLE
www2.veziseriale.org: nuisance

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#22782]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www2.veziseriale.org/filme/closing-the-ring-povestea-unui-inel-2007/
```

### Description

A small popup window appears at the top right side of the screen when the video is clicked. When the site finishes loading in that small window, it will turn to full size.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 120295
 cosmetic: 45651
 scriptlet: 20207
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81722-13, 2m Δ
  easyprivacy: 50333-7, 2m Δ
  plowe-0: 3779-1187, 2m
  ublock-badware: 7751-143, 2m Δ
  ublock-filters: 37230-354, 2m Δ
  ublock-privacy: 743-6, 2m Δ
  ublock-quick-fixes: 155-18, 3m
  ublock-unbreak: 2236-33, 3m
  urlhaus-1: 4115-0, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1996 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: browser.storage.local

```
</details>

**Comment by mapx-** [comment]
I don't see your configuration, try resetting uBO to default and test again

**Comment by mapx-** [comment]
ok, it's beacause you didn't subscribe the regional list => [Romanian Ad (ROad) Block List Light](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=ROU-1)

**Comment by mapx-** [comment]
it depends on your system settings
