### ISSUE TITLE
mangareader.to: popups

### ISSUE THREAD

**Issue by JussChillin** [uBlockOrigin/uAssets#22797]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mangareader.to/home`

### Category

popups

### Description

When I select to sign in I get redirected to this popup message, was fine yesterday but today this is happening.

### Other extensions used

I only have ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240306-055744](https://github.com/uBlockOrigin/uAssets/assets/162461155/d08056ed-6a96-4a1f-b967-13593047c839)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 116
filterset (summary):
 network: 125226
 cosmetic: 37489
 scriptlet: 18910
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37764-391, 7m
  ublock-badware: 7754-14, 7m
  ublock-privacy: 740-1, 7m
  ublock-unbreak: 2298-1, 7m
  ublock-quick-fixes: 152-1, 7m Δ
  adguard-mobile: 9109-133, now
  easylist: 81975-16405, now
  easyprivacy: 50340-846, now
  urlhaus-1: 7405-5, now
  plowe-0: 3779-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2564 ms (selfie)
 maxAssetCacheWait: 1166 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  doruffleton.com: 1
  googletagmanager.com: 1
  sharethis.com: 1
 extended:
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by gorhill** [comment]
> When I select to sign in

After clicking "Sing-in" button or just when bringing up the sign in dialog?

**Comment by JussChillin** [comment]
Went back to try again and it seems like this popup message shows up after
clicking on anything on that site. I know it's blocking the ad but since
installing the app I had not gotten the pop-up for any blocked ads until
today. It is only happening on this site. All the other sites I use are
fine.

**Comment by JussChillin** [comment]
Did you do anything to fix it? Because it's working fine again, I don't
what was causing but I'm happy it's back to normal.
Letting you know it's working properly so you don't waste time and
resources looking into this any longer. Maybe I should've waited and I
panic, I apologize. I bare to ill will. I love the app and would be truly
sad if I'd lose it. Thank you so much. 5 stars all the way and have a good
day!

**Comment by gorhill** [comment]
I see that `ublock-filters` was updated through full update instead of differential update, suggesting the list hadn't been updated in more than 4 days. If the filter was edited recently, this would be the explanation. Although we do ask to test again after updating the filter list by reloading the webpage in a new tab.

**Comment by JussChillin** [comment]
Oh ok, someone else in the thread also mentioned it being outdated and just
replied that it was effective updated recently. Are updates installed
automatically or is there a way to do it manually if needed?

**Comment by JussChillin** [comment]
As you mentioned before, outdated filter was most likely the culprit. It is
working fine now, thank you for your help.
Are filter updated automatically or is there a way to do it manually if
needed?

**Comment by gorhill** [comment]
They update automatically every 5-6 hours, but the fix was added 2 hours before you opened the issue, so you were most likely not yet updated to latest version yet. Forcing an update in the _Support_ pane should have brought your lists all up to date though.

**Comment by JussChillin** [comment]
This is great info, I will keep that in mind in the future. Again, thank
you so much for your help. Very much appreciated!
