### ISSUE TITLE
(admiral) dawgpounddaily.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2279]
### URL(s) where the issue occurs

`https://dawgpounddaily.com/2018/05/13/cleveland-browns-nick-chubb-impresses-rookie-camp/`

### Describe the issue

Admiral. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/40019239-e142fb8c-577b-11e8-93f3-e24c0a67db04.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.4

### Settings

All default

**Comment by smed79** [comment]
ref https://forums.lanik.us/viewtopic.php?f=62&t=39468
