### ISSUE TITLE
medeberiya1.com: detection

### ISSUE THREAD

**Issue by nadeeshaunarathna** [uBlockOrigin/uAssets#22796]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://medeberiya1.com/`

### Category

detection

### Description

Detect ad blocker

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 123760
 cosmetic: 45656
 scriptlet: 20182
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81888-13, 4m
  easyprivacy: 50337-7, 4m
  plowe-0: 3779-1187, 4m
  ublock-badware: 7756-143, 4m
  ublock-filters: 37214-354, 4m
  ublock-privacy: 743-6, 4m
  ublock-quick-fixes: 156-18, 4m
  ublock-unbreak: 2236-33, 4m
  urlhaus-1: 7405-5, 4m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 549 ms (selfie)
 maxAssetCacheWait: 287 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 13
 no-cosmetic-filtering: true
 no-popups: true
 no-remote-fonts: true
 network:
  medeberiya1.com: 3
  d38b9p5p6tfonb.cloudfront.net: 1
  dcbbwymp1bhlf.cloudfront.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  gstatic.com: 4
  wp.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
fixed already https://github.com/uBlockOrigin/uAssets/issues/22795
