### ISSUE TITLE
fancode.com: detection

### ISSUE THREAD

**Issue by nir2594** [uBlockOrigin/uAssets#22799]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.fancode.com/formula1/tour/f1-gulf-air-bahrain-grand-prix-2024-17100709/video-highlights/full-replay-red-bull-ferrari-dominate-105461
```

### Description

If I play the video, there's an error message with following title: "Please retry and kindly also disable AdBlockers/VPNs. MEDIA_ERR_SRC_NOT_SUPPORTED"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (9)](https://github.com/uBlockOrigin/uAssets/assets/7221613/9398ba85-3818-4610-ad0a-89a0cd4d26b7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 128582
 cosmetic: 53897
 scriptlet: 18821
 html: 1740
listset (total-discarded, last-updated):
 added:
  IND-0: 13002-11, never
 default:
  user-filters: 3-0, never
  ublock-filters: 37388-123, 2m Δ
  ublock-badware: 7760-14, 2m Δ
  ublock-privacy: 739-0, 2m Δ
  ublock-unbreak: 2293-0, 2m Δ
  ublock-quick-fixes: 153-1, 2m Δ
  easylist: 81975-625, 2m Δ
  easyprivacy: 50340-865, 2m Δ
  urlhaus-1: 7405-5, 2m
  plowe-0: 3779-1, 1d.3h.10m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 510 ms (selfie)
 maxAssetCacheWait: 194 ms
 cacheBackend: indexedDB
```
</details>

**Comment by dportvine** [comment]
Same error without uBO.
