### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by almog123** [uBlockOrigin/uAssets#228]
URL(s) where the issue occurs

haaretz.com

Describe the issue

looks like multiple proxy ads, reported 3 weeks ago to the main easylist.

Screenshot(s)
http://i.imgur.com/vdd9h9z.png
http://i.imgur.com/f78AdSV.png

Versions

Browser/version: Chromium 57
uBlock Origin version: 1.10.0

**Comment by IDKwhattoputhere** [comment]
https://forums.lanik.us/viewtopic.php?p=108553#p108553

**Comment by gorhill** [comment]
Report to <https://github.com/easylist/EasyListHebrew> please.
