### ISSUE TITLE
[nsfw] iedprivatedqu.com: breakage

### ISSUE THREAD

**Issue by basedbeans** [uBlockOrigin/uAssets#22806]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://iedprivatedqu.com/s?ngMH`

### Category

breakage

### Description

with uBO enabled page repeatedly reloads, infinitely switching between itself, `https://ebaticalfel.com/s?ngMH` and `https://stownrusis.com/s?ngM`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/138249766/4bc73f2f-7404-463a-9f37-0bb2473d421e

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 123909
 cosmetic: 45662
 scriptlet: 20189
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82032-13, 3m
  easyprivacy: 50340-7, 3m
  plowe-0: 3779-1187, 3m
  ublock-badware: 7756-143, 3m
  ublock-filters: 37226-354, 3m
  ublock-privacy: 743-6, 3m
  ublock-quick-fixes: 156-18, 3m
  ublock-unbreak: 2239-33, 3m
  urlhaus-1: 7405-5, 3m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 124 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  d2zf5gu5e5mp87.cloudfront.net: 1
  dfdgfruitie.xyz: 1
```
</details>

**Comment by huyszn** [comment]
Is this a link shortener? What is the original page where you got this link?

**Comment by basedbeans** [comment]
> Is this a link shortener? What is the original page where you got this link?

yes the first link was https://mega-guy.com/s?regF

**Comment by huyszn** [comment]
@Yuki2718 The links seem to be related to #16691

**Comment by Yuki2718** [comment]
@huyszn We have to add exception for each domain. The blocking is legitimate as it is a FingerprintJS server, it's just the site is self-breaking.
