### ISSUE TITLE
myanimelist.net: breakage

### ISSUE THREAD

**Issue by nexr4** [uBlockOrigin/uAssets#22805]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://myanimelist.net/`

### Category

breakage

### Description

> [!NOTE]
> _I feel the need to write this note because the filter list "`AdGuard – Ads`" isn't checked in the image provided under the "Prerequisites" checklist but the filter list "`EasyList`" is checked though they are under the same section. So, just in case, I'm assuming the "`AdGuard – Ads`" filter list is a default one. After all it does come with uBO.
**But if it isn't a default filter list then please disregard this issue and close it.**
Thank you for your time._

**"`AdGuard – Ads`"** filter list under the "`Ads`" section visually breaks `MyAnimeList.net`.
I have confirmed this by first disabling uBO. With uBO disabled **issue was gone**.
Then I turned uBO _**on**_ and **disabled all filter lists including my filters** and **issue was gone**.
After checking all filter lists individually I saw that it was the filter list "`AdGuard – Ads`" that caused the breakage. **_I have confirmed that this is the only filter list that causes the issue._**
Disabling said filter list fixes the white background issue but it also results in the showing of the color of the background ad (but not the ad itself).

On all screenshots every filter list other than "`AdGuard – Ads`" is **enabled**.

<details>
<summary>First screenshot shows the white background issue on the mainpage of <code>MyAnimeList.net</code> with the filter list "<code>AdGuard – Ads</code>" <b>enabled</b>.</summary>

![Screenshot 2024-03-06 234309](https://github.com/uBlockOrigin/uAssets/assets/90934014/b09d8335-8f24-4932-958f-f5eac5966e6b)

</details>

<details>
<summary>Second screenshot shows background color of the ad, but not the ad itself, not filtered by uBO with the filter list "<code>AdGuard – Ads</code>" <b>disabled</b>.</summary>

![Screenshot 2024-03-06 235517](https://github.com/uBlockOrigin/uAssets/assets/90934014/6f828757-4382-414d-adac-a824a3ddbe36)

</details>

<details>
<summary>Third screenshot shows the black background being restored <b><i>on pages without background ads</i></b> with the filter list <b>disabled</b>.</summary>

![Screenshot 2024-03-06 234544](https://github.com/uBlockOrigin/uAssets/assets/90934014/8383567f-06fa-4b39-accf-bb92261ed4a8)

</details>

> [!NOTE]
> Here is the first ten lines of the asset ("`AdGuard – Ads`") that I was talking about:
>> ![Adblock Plus 2.0]
>> ! Checksum: QZ/DWPtHAIuhSOfDraaBdg
>> ! Diff-Path: ../patches/2_without_easylist/2_without_easylist-s-1709750205-3600.patch
>> ! Title: AdGuard Base filter
>> ! Description: This filter is necessary for quality ad blocking.
>> ! Version: 2.3.25.55
>> ! TimeUpdated: 2024-03-06T18:33:08+00:00
>> ! Expires: 5 days (update frequency)
>> ! Homepage: https://github.com/AdguardTeam/AdGuardFilters
>> ! License: https://github.com/AdguardTeam/AdguardFilters/blob/master/LICENSE

### Other extensions used

- [Augmented Steam](https://addons.mozilla.org/en-US/firefox/addon/augmented-steam/)
- [MAL-Sync](https://addons.mozilla.org/en-US/firefox/addon/mal-sync/)
- [Modern for Wikipedia](https://addons.mozilla.org/en-US/firefox/addon/modern-for-wikipedia/)
- [SteamDB](https://addons.mozilla.org/en-US/firefox/addon/steam-database/)
- [Swift Selection Search](https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/)
- [YouTube High Definition](https://addons.mozilla.org/en-US/firefox/addon/youtube-high-definition/)
- [Matte Black (Blue)](https://addons.mozilla.org/en-US/firefox/addon/matte-black-blue/) (I'm adding this just in case since it is a theme)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-06 at 23-33-06 MyAnimeList net - Anime and Manga Database and Community](https://github.com/uBlockOrigin/uAssets/assets/90934014/df3e9881-c6f5-4f92-88a5-9f7b4b690039)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 361352
 cosmetic: 246267
 scriptlet: 49292
 html: 1996
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance.txt: 79948-79942, 5m
  adguard-generic: 79051-809, never
  adguard-mobile: 9112-20, 3m
  adguard-spyware-url: 1470-106, 3m
  adguard-spyware: 113737-33582, 3m
  block-lan: 61-0, 3m
  curben-phishing: 116116-43, 4m
  adguard-social: 22213-864, 4m
  adguard-cookies: 28884-72, 4m
  ublock-cookies-adguard: 1018-0, 4m
  adguard-popup-overlays: 26734-1631, 4m
  adguard-mobile-app-banners: 5062-1083, 4m
  [12 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  ublock-filters: 37398-3691, 3m
  ublock-badware: 7760-14, 3m
  ublock-privacy: 739-0, 3m
  ublock-unbreak: 2293-1, 3m
  ublock-quick-fixes: 153-1, 3m
  easylist: 81722-2264, 3m
  easyprivacy: 50333-1205, 3m
  urlhaus-1: 7405-5, 4m
  plowe-0: 3779-84, 4m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16963 ms (selfie)
 maxAssetCacheWait: 7148 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  myanimelist.net: 2
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  quantcast.com: 1
  unblockia.com: 2
 extended:
  ##.footer-app
  ##.header-mini-banner
  ##.btn-mal-service
  ##.footer-social-media
  ##[src*="/c/img/images/event/"]
  ##.grecaptcha-badge
  ##body:style(background-color: inherit!important;)
  ##+js(nofab)
  ##+js(set-local-storage-item, wf-promo-2::d, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by D4niloMR** [comment]
Caused by `myanimelist.net#$#body { background-color: inherit!important; }`

@Alex-302

**Comment by D4niloMR** [comment]
Maybe?

```adb
myanimelist.net##+js(rmnt, style, /body:not\(.ownlist\) {\s+background-color: #E3EEFF;\s+background-image: url\(data:image\/png;base64/)
```

**Comment by Alex-302** [comment]
That rule was removed. https://github.com/AdguardTeam/AdguardFilters/commit/8fb3fe2dd6b9607e8f80ade6330fcc5c2f62f617
