### ISSUE TITLE
egy.best

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2280]
### URL(s) where the issue occurs

`https://egy.best/movie/welad-rezk-2015/`

### Describe the issue

Anti-adblock (I have been informed that the red text is an anti-adblock message)

### Settings

- Default settings

### Notes

`@@||cdn.egy.best/static/global/js/adblock.js$script,first-party` perhaps?

**Comment by smed79** [comment]
@mapx- mirror site `http://egybest.site/`

**Comment by KiLL4FuNK** [comment]
download Anti-adblock

`https://egy.best/movie/heart-of-his-mother-2018/?ref=home-new`

**Comment by smed79** [comment]
anti adblock `http://egybest.site/`

```
@@||cdn.egy.best/static/global/js/adblock.js$script,domain=egy.best|egybest.site
```
or
```
@@||cdn.egy.best/static/global/js/adblock.js$script
```

**Comment by smed79** [comment]
egybest has been shutdown.

**Comment by gwarser** [comment]
Still alive?

https://old.reddit.com/r/uBlockOrigin/comments/cecksg/httpsegybest_detect_ublock/

**Comment by KiLL4FuNK** [comment]
anti adblock play video

`https://www.egy.best/movie/dark-phoenix-2019/?ref=home-new`

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/cwjlnf/the_new_egybest_for_arabictranslated_movies_is_a/
