### ISSUE TITLE
shudder.com: breakage

### ISSUE THREAD

**Issue by williamsonf** [uBlockOrigin/uAssets#22804]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.shudder.com/movies/watch/hell-house-llc-iii-lake-of-fire/f016a6798452e3b3`

### Category

breakage

### Description

The "play" link on shudder's film descriptions does not function when Ublock Origin is installed.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 123909
 cosmetic: 45662
 scriptlet: 20188
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 156-18, now
 default:
  user-filters: 0-0, never
  easylist: 82032-13, now
  easyprivacy: 50340-7, now
  plowe-0: 3779-1187, now
  ublock-badware: 7756-143, now
  ublock-filters: 37225-354, now
  ublock-privacy: 743-6, now
  ublock-unbreak: 2239-33, now
  urlhaus-1: 7405-5, 35m
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 374 ms (selfie)
 maxAssetCacheWait: 109 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 17
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  krxd.net: 1
  mparticle.com: 1
  newrelic.com: 2
  optimizely.com: 11
```
</details>

**Comment by huyszn** [comment]
Test this filter to see if the play button and video works:

`@@||jssdkcdns.mparticle.com/js/*/mparticle.js$script,domain=shudder.com`

Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes
