### ISSUE TITLE
roystream.com: popups

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#22810]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://roystream.com/e/hockey/nhl/401560217`

### Category

popups

### Description

This site recently opens new tabs and windows when anything is clicked.

### Other extensions used

PrivacyBadger
Decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 340355
 cosmetic: 246256
 scriptlet: 49298
 html: 1997
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 79072-5457, 25m
  adguard-mobile: 9112-103, 25m
  adguard-spyware-url: 1470-106, 25m
  block-lan: 61-0, 25m
  curben-phishing: 105383-43, 25m
  adguard-social: 22213-864, 25m
  fanboy-thirdparty_social: 68-0, 25m
  fanboy-cookiemonster: 50274-3884, 25m
  fanboy-social: 15833-25, 25m
  ublock-annoyances: 6809-1059, 26m Δ
  adguard-spyware: 113737-33508, 25m
  adguard-cookies: 28884-71, 25m
  [10 lists not shown]: [too many]
 default:
  ublock-filters: 37399-402, 26m Δ
  ublock-badware: 7760-14, 26m Δ
  ublock-privacy: 739-0, 26m Δ
  ublock-unbreak: 2296-1, 26m Δ
  ublock-quick-fixes: 153-1, 26m Δ
  easylist: 82032-756, 26m Δ
  easyprivacy: 50340-1006, 26m Δ
  urlhaus-1: 7595-0, 26m
  plowe-0: 3779-1, 25m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 993 ms (selfie)
 maxAssetCacheWait: 428 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 no-popups: true
 network:
  chatango.com: 1
  googletagmanager.com: 1
  grapseex.com: 2
  mfthkdj.com: 1
  psougnoa.net: 2
  rhwvpab.com: 2
  rtmark.net: 4
  tzegilo.com: 1
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.facebook.com/sharer.php"]
```
</details>

**Comment by peroleucopus** [comment]
Sorry for the stupid question, but how do I apply this fix?

**Comment by ItsProfessional** [comment]
You don't. It should be automatically applied by now.

**Comment by peroleucopus** [comment]
Interesting, it wasn't fixed for me. Is there a filter list I need to make sure I have added?

**Comment by gwarser** [comment]
Scriptlet is not injected on sample page for me. Maybe because it's not secure and returns 404. But my custom scriptlet is.

**Comment by gwarser** [comment]
I did update filter list 12 minutes ago. It did not work, so I put the filter in My filters using only this page domain and it started working. Some filters caching bug? It does not help debugging when on each filter edit browser console is spammed by `loadFilterLists() Loading filters from...`.

**Comment by stephenhawk8054** [comment]
Update your filter lists.
