### ISSUE TITLE
elevatebyprincipal.com: breakage

### ISSUE THREAD

**Issue by jrearick-pfg** [uBlockOrigin/uAssets#22815]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.principalcdn.com/css/*
https://elevatebyprincipal.com/
https://www.principalfoundation.org/
https://www.pilot.principalfoundation.org/
https://www.principalam.com/
https://www.principal.cl/
https://www.principal.co.id/
https://www.principal.com.my/
https://principal.com.mx/
https://www.principal.com.sg/
https://www.principal.th/
```

### Description

This is similar to #20983 

A majority of Principal Financial Group's websites are broken for users using uBlock due to a filter rule that doesn't allow js under css filepaths. CSS is ironically an old department name in the company, and thus it is used as part of a CDN path to host javascript assets. Please see the attached screenshots and troubleshooting information for more context.

The current filter seems to exempt `~principal.com` and `~principalcdn.com`, however we have other domains. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-07 at 3 29 21 PM](https://github.com/uBlockOrigin/uAssets/assets/79481644/c3e16fd7-3ac4-4371-b027-2fbc62c3e4df)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124009
 cosmetic: 45641
 scriptlet: 20203
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81995-13, 1h.35m Δ
  easyprivacy: 50343-7, 1h.35m Δ
  plowe-0: 3783-1188, 9d.1h.55m
  ublock-badware: 7762-143, 1h.35m Δ
  ublock-filters: 37254-354, 1h.35m Δ
  ublock-privacy: 743-6, 1h.35m Δ
  ublock-quick-fixes: 161-18, 1h.35m Δ
  ublock-unbreak: 2240-33, 1h.35m Δ
  urlhaus-1: 7490-5, 6h.39m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 153 ms (selfie)
 maxAssetCacheWait: 64 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  brightcove.com: 5
  dynatrace.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  principalcdn.com: 1
```
</details>

**Comment by Yuki2718** [comment]
@jrearick-pfg I excluded any requests going **toward** `principalcdn.com` regardless of its origin. Is this enough?
