### ISSUE TITLE
englex.ru: ads

### ISSUE THREAD

**Issue by pr1vetsodna** [uBlockOrigin/uAssets#22818]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://englex.ru/`

### Category

ads

### Description

huge ads appear in the middle of the main content of the site

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/102536986/2ba61748-a8fb-4616-9634-fe5331801ff2)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/102536986/938756bc-2530-43cd-aa39-7b9782c747b8

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 141443
 cosmetic: 66494
 scriptlet: 21577
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  RUS-0: 39771-9, now
  easylist: 81990-32, 27m Δ
  easyprivacy: 50343-87, 27m Δ
  plowe-0: 3779-1191, now
  ublock-badware: 7803-143, 27m Δ
  ublock-filters: 37252-379, 27m Δ
  ublock-privacy: 742-7, 27m Δ
  ublock-quick-fixes: 162-18, 27m Δ
  ublock-unbreak: 2240-33, 27m Δ
  urlhaus-1: 7490-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 586 ms (selfie)
 maxAssetCacheWait: 181 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  acstat.com: 1
  google.com: 3
  googletagmanager.com: 1
  indoleads.com: 1
  jsdelivr.net: 1
  mail.ru: 1
  roistat.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by dimisa-RUAdList** [comment]
self promotion
