### ISSUE TITLE
parcelsapp.com: breakage

### ISSUE THREAD

**Issue by micbanand** [uBlockOrigin/uAssets#22817]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://parcelsapp.com/en/tracking/UA191793129HU`

### Category

[unknown]

### Description

tracking function stops working when block enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125573
 cosmetic: 47955
 scriptlet: 20244
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 34-2, never
  NOR-0: 3890-2, 1m
  easylist: 81975-14, 1m
  easyprivacy: 50343-8, 1m
  plowe-0: 3779-1188, 1m
  ublock-badware: 7803-143, 1m
  ublock-filters: 37235-357, 1m
  ublock-privacy: 743-6, 1m
  ublock-quick-fixes: 162-18, 1m
  ublock-unbreak: 2240-33, 1m
  urlhaus-1: 7490-0, 1m
filterset (user): [array of 34 redacted]
trustedset:
 added: [array of 21 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 266 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  adpushup.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##._ap_apex_ad
```
</details>

**Comment by ItsProfessional** [comment]
> tracking function stops working when block enabled

You mean the website is no longer able to track with uBO enabled? It's intentional.

**Comment by micbanand** [comment]
no it is not able to use the postal tracking. as the side is used for??

**Comment by micbanand** [comment]
thats wird did try 3 different trackings right now. 1 did take a looong time. but seems fine now. must have been a bug on the site. been going on for days. but sorry for wasting your time!
