### ISSUE TITLE
titantv.com: detection

### ISSUE THREAD

**Issue by BobTheKoder** [uBlockOrigin/uAssets#22813]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.titantv.com/Default.aspx?r=t`

### Category

detection

### Description

Ublock is detected and use of the site is inhibited. 

### Other extensions used

Privacy Badger
Wayback Machine
Swift Read

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124105
 cosmetic: 45671
 scriptlet: 20195
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82033-13, 1h.56m Δ
  easyprivacy: 50340-7, 1h.56m Δ
  plowe-0: 3779-1187, now
  ublock-badware: 7756-143, 1h.56m Δ
  ublock-filters: 37241-354, 1h.56m Δ
  ublock-privacy: 743-6, 1h.56m Δ
  ublock-quick-fixes: 156-18, 1h.56m Δ
  ublock-unbreak: 2239-33, 1h.56m Δ
  urlhaus-1: 7595-0, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1371 ms (selfie)
 maxAssetCacheWait: 274 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  pub.network: 3
 extended:
  ##.gpAdBox
  ##.gpAdFooter
  ##.gAd
  ##td[id^="menutablelogocell"]
  ###sidebox
  ##[data-freestar-ad]:not(:empty)
  ##+js(abort-current-script, document.createElement, admiral)
  ##+js(addEventListener-defuser, load, player)
```
</details>

**Comment by ItsProfessional** [comment]
I'm unable to reproduce this. Can you take a screenshot of page where it shows detection?

**Comment by BobTheKoder** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/162551455/27b0abd1-0469-4ac0-be7c-65f71765eed8)

**Comment by BobTheKoder** [comment]
> > I have verified that other extensions are not causing the issue.
> 
> You need check this without other extensions.
> 
> Screen

I just found out privacy badger was causing this. I forgot it was installed.
