### ISSUE TITLE
google.com/maps: breakage (search results in maps is black)

### ISSUE THREAD

**Issue by paericksen** [uBlockOrigin/uAssets#22826]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/maps/search/childrens+shoes/@39.6016081,-104.91139,13z/data=!3m1!4b1?entry=ttu`

### Category

breakage

### Description

when searching in google maps the search results are a black box.  I disabled uBO and the search results work.  I enable uBO again and the search results do not work.  Someone already reported this issue in https://github.com/uBlockOrigin/uAssets/issues/17193 but that ticket was closed as 'unable to reproduce'.  

### Other extensions used

Bitwarden, Fakespot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4397404/7b184087-6c3c-464a-9f4f-261c33e5c7bb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 123
filterset (summary):
 network: 124407
 cosmetic: 45608
 scriptlet: 18854
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37441-151, 12m
  ublock-badware: 7827-14, 12m
  ublock-privacy: 742-0, 12m
  ublock-unbreak: 2298-0, 12m
  ublock-quick-fixes: 156-1, 12m
  easylist: 82005-627, 12m
  easyprivacy: 50345-834, 12m
  urlhaus-1: 7810-5, 12m
  plowe-0: 3772-1, 12m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5388 ms (selfie)
 maxAssetCacheWait: 72 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 46
 network:
  google.com: 41
  csp.withgoogle.com: 1
  googlesyndication.com: 4
 extended:
  ##.OcdnDb
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##div[jsaction^="mouseover:pane."]:has(span.jHLihd)
```
</details>

**Comment by D4niloMR** [comment]
Caused by `google.com##div[jsaction^="mouseover:pane."]:has(span.jHLihd)`

Add in "My filters":

`google.*#@#div[jsaction^="mouseover:pane."]:has(span.jHLihd)`
