### ISSUE TITLE
[nsfw] ebaticalfel.com: ads

### ISSUE THREAD

**Issue by quoctninh** [uBlockOrigin/uAssets#22823]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ebaticalfel.com/s?ngMH`

### Category

ads

### Description

Normally ublock orgin can bypass all the websites that I access. Now it doesn't 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124399
 cosmetic: 45620
 scriptlet: 20218
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82005-17, now
  easyprivacy: 50344-7, now
  plowe-0: 3772-1184, now
  ublock-badware: 7813-143, now
  ublock-filters: 37261-353, now
  ublock-privacy: 746-6, 13m Δ
  ublock-quick-fixes: 162-18, 13m
  ublock-unbreak: 2241-33, now
  urlhaus-1: 7810-5, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 85 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  dfdgfruitie.xyz: 1
  muendakutyfore.info: 2
  ourtshipanditlas.info: 1
```
</details>

**Comment by quoctninh** [comment]
Usually there is content ahead. Before the update from uBlock origin, I
believe uBlock was able to bypass all of the AD's (surveys, reading
articles, etc) to access links to those mega file folders with content.
Since the update, the website just keeps refreshing and never gets past
those AD pages. Before, it will skip all that and take me directly to the
mega website filled with content or another website that has the direct
link to the mega website.

**Comment by quoctninh** [comment]
To further elaborate on this...

The original link is https://utopianleaks.com/s?rr17

When you click on this link, it takes you to the AD website where you have
to fill out a survey, read articles or whatever it asks you to do. However,
as soon as you click the link to the page, it will refresh several times.
The link address wouldn't be utopianleaks. Instead it changes to what I
submitted a ticket for. Sometimes the posts will have a mirror link that
takes me to linkvertise.com when they do, I'll click that link instead to
get access. Some other posts would just have utopianlinks.

"https://onepiecered.co/s?rnjE" is another example

**Comment by quoctninh** [comment]
Thanks!

**Comment by huyszn** [comment]
This is related to #22806

**Comment by ItsProfessional** [comment]
Continue in #17361
