### ISSUE TITLE
Apkmirror.com failed to load

### ISSUE THREAD

**Issue by MLSci** [uBlockOrigin/uAssets#22828]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
apkmirror.com
```

### Description

www.apkmirror.com says:
Failed to load website properly since 07c225f3.online is blocked (TypeError: Failed to fetch). Please allow 07c225f3.online (click OK if you'd like to learn how).

### Other extensions used

Dark reader, Rakuten, Bypass paywalls

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 122
filterset (summary): 
 network: 263022
 cosmetic: 268507
 scriptlet: 49740
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2h.8m
  CHN-0: 25476-129, 2d.4h.41m
  JPN-1: 14123-9, 2d.4h.42m
  adguard-cookies: 28884-33, 2d.4h.45m
  adguard-generic: 79045-522, 2d.4h.49m
  adguard-mobile: 9112-92, 2d.4h.48m
  adguard-mobile-app-banners: 5062-13, 2d.4h.44m
  adguard-other-annoyances: 13926-20, 2d.4h.46m
  adguard-popup-overlays: 26734-99, 2d.4h.51m
  adguard-social: 22213-907, 2d.4h.43m
  adguard-spyware: 113735-1208, 2d.4h.50m
  adguard-spyware-url: 1470-5, 2d.2h.37m
  adguard-widgets: 2412-7, 2d.4h.47m
  block-lan: 61-0, 4d.1h.59m
  curben-phishing: 696-0, 2h.9m
  dpollock-0: 11659-271, 1d.4h.34m
  easylist-annoyances: 4414-297, 4d.4h.4m
  easylist-chat: 183-15, 7d.18h.29m
  easylist-newsletters: 7086-505, 4d.4h.1m
  easylist-notifications: 2956-1472, 4d.4h
  [6 lists not shown]: [too many]
 default: 
  user-filters: 29-6, never
  easylist: 81996-1798, 5d.6h.35m
  easyprivacy: 50342-32287, 2h.10m
  plowe-0: 3772-1678, 1h.11m
  ublock-badware: 7751-262, 2d.4h.52m
  ublock-filters: 35780-3801, 1d.6h.37m
  ublock-privacy: 688-218, 4d.4h.2m
  ublock-quick-fixes: 151-20, 2h.7m
  ublock-unbreak: 2238-155, 1d.6h.36m
  urlhaus-1: 7490-0, 17h.20m
filterset (user): [array of 29 redacted]
trustedset: 
 added: [array of 155 redacted]
switchRuleset: 
 added: [array of 16 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 contextMenuEnabled: false
 prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 807 ms (selfie)
 maxAssetCacheWait: 570 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in another browser profile with only uBO and its default settings.

**Comment by MLSci** [comment]
I tested again. The issue manifest with or without uBO. We can close this issue. Thank you
