### ISSUE TITLE
clinicalkey.com: breakage

### ISSUE THREAD

**Issue by anwarmahmood1** [uBlockOrigin/uAssets#22822]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.clinicalkey.com/student/content/video/23-s2.0-mm_9780323881685_0002?startTime=24
```

### Description

after authenticating to https://www.clinicalkey.com/student, I can search for videos, but when you attempt to play, the browser page goes blank

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
authenticate.

search for 'cleavage and blastocyst formation' to be offered a link that takes you to

https://www.clinicalkey.com/student/content/video/23-s2.0-mm_9780323881685_0002?startTime=24

this displays correctly

![ublock 1](https://github.com/uBlockOrigin/uAssets/assets/43573768/f9e0f086-dd7a-421f-9c70-7866ab348d51)

when you click Play, the browser page goes blank;

![ublock 2](https://github.com/uBlockOrigin/uAssets/assets/43573768/569a4c7b-e76b-4584-a336-f83d0334a24d)

using uBlock origin tools, you can identify the rule; if you except the rule...

![ublock 3](https://github.com/uBlockOrigin/uAssets/assets/43573768/b3cb8846-a562-4f24-a664-27ed7e2ab428)

...then reload the page, it works.

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124079
 cosmetic: 45599
 scriptlet: 18852
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37423-123, 13m Δ
  ublock-badware: 7812-14, 13m Δ
  ublock-privacy: 742-0, 13m Δ
  ublock-unbreak: 2298-0, 13m Δ
  ublock-quick-fixes: 159-1, 13m Δ
  easylist: 82005-623, 13m Δ
  easyprivacy: 50344-869, 13m Δ
  urlhaus-1: 7490-0, 6h.31m
  plowe-0: 3782-1, 11d.7h.51m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 399 ms (selfie)
 maxAssetCacheWait: 210 ms
 cacheBackend: indexedDB

```yaml


```
</details>

**Comment by anwarmahmood1** [comment]
Universities subscribe to https://www.clinicalkey.com/student

learners could be anywhere - at home, at University, etc - when they encounter this.

**Comment by ItsProfessional** [comment]
We will need a test account in order to investigate. Are you willing to share your account credentials? I'll provide an email to send it to if you agree.
