### ISSUE TITLE
quora.com: nuisance

### ISSUE THREAD

**Issue by afagf** [uBlockOrigin/uAssets#22820]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I have verified that other extensions are not causing the issue.
- [ ] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.quora.com/Do-older-computers-have-better-performance-with-Windows-10-or-11`

### Category

nuisance

### Description

it makes flu it self 

### Other extensions used

![Ekran Alıntısı](https://github.com/uBlockOrigin/uAssets/assets/46799591/1790d78d-8359-4171-a150-ce8de73158c3)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125530
 cosmetic: 54572
 scriptlet: 21497
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  TUR-0: 11721-15, now
  easylist: 82027-35, 43m Δ
  easyprivacy: 50343-12, 43m Δ
  plowe-0: 3779-1188, now
  ublock-badware: 7803-143, 43m Δ
  ublock-filters: 37251-366, 43m Δ
  ublock-privacy: 743-6, 43m Δ
  ublock-quick-fixes: 162-18, 43m Δ
  ublock-unbreak: 2240-34, 43m Δ
  urlhaus-1: 7490-0, now
filterset (user): [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 927 ms (selfie)
 maxAssetCacheWait: 603 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  quora.com: 2
 extended:
  ##.qu-zIndex--blocking_wall.qu-overflow--hidden.qu-justifyConten…
```
</details>

**Comment by ItsProfessional** [comment]
This is caused by your filter, as you've tried to block the login popup:
> `.qu-zIndex--blocking_wall.qu-overflow--hidden.qu-justifyConten…`

Remove it.
