### ISSUE TITLE
tiktokcounter.net: nuisance

### ISSUE THREAD

**Issue by Yoderjase** [uBlockOrigin/uAssets#22827]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokcounter.net/marketing/how-to-choose-the-right-health-insurance/`

### Category

nuisance

### Description

the wait time gets increased to 50s when it detects the ad block.

### Other extensions used

dark reader and IDM

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124257
 cosmetic: 45606
 scriptlet: 18854
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37441-238, 33m Δ
  ublock-badware: 7817-14, 33m Δ
  ublock-privacy: 742-0, 33m Δ
  ublock-unbreak: 2298-0, 33m Δ
  ublock-quick-fixes: 156-1, 33m Δ
  easylist: 82005-540, 33m Δ
  easyprivacy: 50345-834, 33m Δ
  urlhaus-1: 7670-5, 1m
  plowe-0: 3772-1, 1m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 colorBlindFriendly: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 147 ms (selfie)
 maxAssetCacheWait: 63 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  googlesyndication.com: 2
  googletagmanager.com: 4
  profitsfly.com: 5
 extended:
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(abort-on-property-read, adbDetecte2d)
  ##+js(abort-on-stack-trace, Promise, _0x)
```
</details>

**Comment by liamengland1** [comment]
Provide original download page, etc. which took you to that page

**Comment by huyszn** [comment]
Continue in #17361
