### ISSUE TITLE
survivopedia.com: ads

### ISSUE THREAD

**Issue by colleirose** [uBlockOrigin/uAssets#22831]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.survivopedia.com/how-to-hide-in-plain-sight/`

### Category

ads

### Description

This site has a lot of weird clickbait ads on the right side. They all have the class `svp_campaign_main`.

### Other extensions used

Privacy Badger
Wappalyzer
Tampermonkey
Return YouTube Dislike
Indie Wiki Buddy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/147954091/1cd56d41-9bfb-4445-915c-bf668b996199)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124285
 cosmetic: 45331
 scriptlet: 18859
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37456-123, now
  ublock-badware: 7827-14, now
  ublock-privacy: 742-0, now
  ublock-unbreak: 2301-2, now
  ublock-quick-fixes: 157-1, now
  easylist: 81736-627, now
  easyprivacy: 50345-862, now
  urlhaus-1: 7670-5, now
  plowe-0: 3772-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 405 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  survivopedia.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
  sumome.com: 1
  trackerrr.com: 12
  wp.com: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
survivopedia.com##.svp_campaign_main
```

@ryanbr
