### ISSUE TITLE
20min.ch: breakage

### ISSUE THREAD

**Issue by GitMastic** [uBlockOrigin/uAssets#22837]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.20min.ch/fr/video/japon-il-fait-du-hors-piste-et-tombe-dans-une-cascade-103059717`

### Category

breakage

### Description

Video not playing on the website, happens on PC (edge) and android (Firefox) 

### Other extensions used

None 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 141178
 cosmetic: 41113
 scriptlet: 19061
 html: 1743
listset (total-discarded, last-updated):
 default:
  user-filters: 8-2, never
  ublock-filters: 37812-450, 34m Δ
  ublock-badware: 7821-14, 34m Δ
  ublock-privacy: 743-1, 34m Δ
  ublock-unbreak: 2306-3, 34m Δ
  ublock-quick-fixes: 158-1, 34m Δ
  adguard-mobile: 9123-133, now
  easylist: 81736-16317, 33m Δ
  easyprivacy: 50345-1075, 33m Δ
  urlhaus-1: 7670-5, now
  plowe-0: 3772-1, now
  FRA-0: 23035-3215, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4082 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  20min.ch: 2
  adnxs.com: 1
  adsafeprotected.com: 1
  da-services.ch: 1
  doubleclick.net: 1
  ebxcdn.com: 2
  google.com: 2
  imasdk.googleapis.com: 1
  k5a.io: 2
  tda.link: 3
  visualwebsiteoptimizer.com: 1
 extended:
  ##+js(abort-on-property-read, _sp_._networkListenerData)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||tdn.da-services.ch/libs/prebid$script,3p,domain=20min.ch
```

@ryanbr
