### ISSUE TITLE
businesstoday.in: ads

### ISSUE THREAD

**Issue by Sym8** [uBlockOrigin/uAssets#22833]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.businesstoday.in/industry/banks/story/bank-employees-to-get-17-annual-wage-hike-5-day-work-week-waits-for-centres-approval-420698-2024-03-09`

### Category

ads

### Description

Leftover ads and ad banner.

### Other extensions used

TWP, dark reader, tampermonkey with amp scripts, Google search fixer and video background play fix.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-03-09-13-04-29-14_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/66876418/0610d663-2ae4-4cb2-b3d6-bcd94e82a8a5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 133900
 cosmetic: 101724
 scriptlet: 24738
 html: 1999
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28895-75, now
  easylist-annoyances: 4420-108, now
  easylist-newsletters: 7096-12, now
  easylist-notifications: 2958-3, now
  ublock-annoyances: 6874-1095, 4m Δ
  IND-0: 13010-5, 2m
  ublock-cookies-adguard: 1062-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37812-179, 4m Δ
  ublock-badware: 7821-14, 4m Δ
  ublock-privacy: 743-0, 4m Δ
  ublock-unbreak: 2306-2, 4m Δ
  ublock-quick-fixes: 158-1, 4m Δ
  adguard-mobile: 9123-102, now
  easylist: 81736-711, 4m Δ
  easyprivacy: 50345-971, 4m Δ
  urlhaus-1: 7670-5, now
  plowe-0: 3772-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 422 ms (selfie)
 maxAssetCacheWait: 235 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  chartbeat.com: 1
  crazyegg.com: 2
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 5
  googletagmanager.com: 2
  jwpltx.com: 1
  pubmatic.com: 1
  scorecardresearch.com: 1
  taboola.com: 1
  tosshub.com: 2
  webengage.com: 2
 extended:
  ##.story__top__ad
  ##.inner-ad-section
  ###taboola-below-article-thumbnails
  ##.ad-300X250-body
  ##.ad-300X250
  ##.daily-news-letter
  ###taboola-right-rail-thumbnails
  ##.mainBorromSliderSec
  ##.outer-add-section
  ##.right-side-tabola
  ##.secondAdPosition
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.googleAdsContainer
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
##.stoybday-ad
```

@ryanbr

**Comment by stephenhawk8054** [comment]
From: https://github.com/uBlockOrigin/uAssets/issues/23865

```adb
businesstoday.in##.itgdAdsPlaceholder
businesstoday.in##.btPlyer
```

@ryanbr

**Comment by Sym8** [comment]
https://www.businesstoday.in/latest/world/story/us-based-ceo-sells-company-for-1-7-billion-makes-540-employees-millionaires-overnight-538506-2026-06-23

<details>

<img width="1080" height="2460" alt="Image" src="https://github.com/user-attachments/assets/3972534c-7fd9-478a-bf6c-f965e7a36d95" />

</details>

Ublock origin lite on Microsoft edge 149 Android, filtering mode set to complete. 
Not reproduced on mv2 extension.

**Comment by stephenhawk8054** [comment]
Please share your uBOL troubleshooting information to here.

**Comment by Sym8** [comment]
> Please share your uBOL troubleshooting information to here.

<details>

```yml
name: uBlock Origin Lite
version: 2026.628.2035
browser: Chrome Mobile 149 (android)
filtering:
 site: complete
 default: complete
permission: all
badge: 33
rules: 23920
rulesets:
 +adguard-spyware-url
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +ublock-experimental
 +ubol-tests
 adguard-mobile
 easylist
 easyprivacy
 pgl
 ublock-badware
 ublock-filters
 urlhaus-full
scripting:
 ublock-filters.main
 ublock-filters.isolated
 easyprivacy.main
 easyprivacy.isolated
 ublock-badware.main
 adguard-mobile.main
 adguard-mobile.isolated
 annoyances-cookies.main
 annoyances-cookies.isolated
 annoyances-overlays.main
 annoyances-overlays.isolated
 annoyances-others.main
 annoyances-others.isolated
 annoyances-notifications.main
 annoyances-notifications.isolated
 ublock-experimental.main
 ublock-experimental.isolated
 ubol-tests.main
 ubol-tests.isolated
 css-generic-all
 css-generic-some
 prevent-popup
 css-specific
```

</details>

**Comment by Sym8** [comment]
Thanks, issue is fixed.
