### ISSUE TITLE
web.de: ads

### ISSUE THREAD

**Issue by thaliel** [uBlockOrigin/uAssets#22834]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://web.de/`

### Category

ads

### Description

banner ad appears on the top of the page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-02-23 073308](https://github.com/uBlockOrigin/uAssets/assets/5956255/f2071e71-9b84-40d3-beed-604b58dcbfc4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 126616
 cosmetic: 50313
 scriptlet: 18859
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 46-9, never
  ublock-filters: 37456-141, 51m Δ
  ublock-badware: 7827-14, 51m Δ
  ublock-privacy: 742-0, 51m Δ
  ublock-unbreak: 2301-2, 51m Δ
  ublock-quick-fixes: 158-1, 51m Δ
  easylist: 81736-635, 51m Δ
  easyprivacy: 50345-871, 51m Δ
  urlhaus-1: 7670-5, 2m
  plowe-0: 3772-1, 2m
  DEU-0: 7315-3, 2m
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 568 ms (selfie)
 maxAssetCacheWait: 165 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 82
 network:
  web.de: 31
  360yield.com: 2
  3lift.com: 1
  adform.net: 2
  adition.com: 2
  adnxs.com: 3
  adsrvr.org: 2
  agma-analytics.de: 1
  amazon-adsystem.com: 1
  casalemedia.com: 1
  criteo.com: 2
  criteo.net: 1
  id5-sync.com: 1
  indexww.com: 1
  ioam.de: 3
  jubbie.de: 1
  openx.net: 1
  otto.de: 2
  pbstck.com: 1
  pubmatic.com: 1
  rubiconproject.com: 3
  smartadserver.com: 2
  taboola.com: 2
  ui-portal.de: 6
  uicdn.com: 2
  uimserv.net: 3
  yieldlab.net: 2
  ysucej.com: 2
 extended:
  ###service-linklist
  ###service-middle
  ##.partner-links
  ##+js(addEventListener-defuser, timeupdate)
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults

**Comment by D4niloMR** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/1bwnuul/filter_new_ad_banner_on_webde/

I can reproduce and this works for me:

```adb
||web.de/*/nonfriendlyiframe.html$frame,1p
web.de##+js(rmnt, script, '"Anzeige"')
web.de##div[data-service-slot-initialized]
```
