### ISSUE TITLE
tv.bdix.app: detection

### ISSUE THREAD

**Issue by Touhid97** [uBlockOrigin/uAssets#22838]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tv.bdix.app/`

### Category

detection

### Description

The website says, "ad blocker detecter" and I can not access it.

### Other extensions used

IDM integration module

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124285
 cosmetic: 45332
 scriptlet: 18859
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37456-151, 43m Δ
  ublock-badware: 7827-14, 43m Δ
  ublock-privacy: 742-0, 43m Δ
  ublock-unbreak: 2301-2, 43m Δ
  ublock-quick-fixes: 158-1, 43m Δ
  easylist: 81736-627, 43m Δ
  easyprivacy: 50345-834, 43m Δ
  urlhaus-1: 7670-5, 11m
  plowe-0: 3772-1, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 243 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  doubleclick.net: 6
  faltercollection.com: 2
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  histats.com: 1
  notix.io: 1
  wp.com: 2
 extended:
  ##.module_home_ads
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by ItsProfessional** [comment]
I get blocked by cloudflare.

**Comment by Touhid97** [comment]
The issue was solved (after reporting back in March). Now, the website detects uBO again and blocks access.
Thank you!
![Screenshot (61)](https://github.com/user-attachments/assets/1ce2d772-9c39-4493-a211-803981d1e374)
