### ISSUE TITLE
[nsfw] jav.guru: popups

### ISSUE THREAD

**Issue by Bastian12355** [uBlockOrigin/uAssets#22846]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jav.guru/`

### Category

popups

### Description

Still get 1 popup when playing any video

### Other extensions used

Nothing 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 113
filterset (summary):
 network: 124705
 cosmetic: 45582
 scriptlet: 20242
 html: 319
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-unbreak: 2300-0, 1h.31m Δ
  ublock-badware: 7837-14, 1h.37m
  ublock-filters: 37603-105, 1h.37m
  easylist: 82275-249, 1h.31m Δ
  ublock-privacy: 750-3, 1h.31m Δ
  easyprivacy: 50346-193, 1h.31m Δ
  urlhaus-1: 7715-0, 1h.37m
  plowe-0: 3772-1185, 1h.37m
  ublock-quick-fixes: 171-20, 1h.37m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 626 ms
 maxAssetCacheWait: 489 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  mnaspm.com: 1
```
</details>

**Comment by mapx-** [comment]
using what server ?

**Comment by BuffiKyu** [comment]
TV, ST and SB, weirdly just tried DD and got no pop ups, any idea why?

**Comment by stephenhawk8054** [comment]
I can only reproduce the popup on `STREAM TV` server once, so I can't be assure 100% but these might help

```adb
emturbovid.com###pop
emturbovid.com##+js(aeld, click, pop)
emturbovid.com##+js(trusted-set, comboAds, "'1'")
```

I can't reproduce with ST, SB and DD
