### ISSUE TITLE
decrypt.day: detection

### ISSUE THREAD

**Issue by SwiftWinds** [uBlockOrigin/uAssets#22840]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://decrypt.day/app/id544007664#download-box
```

### Description

Clicking on the right download button:

https://github.com/uBlockOrigin/uAssets/assets/12981958/8763e65b-ae6e-472d-884d-de2b63e47040

results in:

https://github.com/uBlockOrigin/uAssets/assets/12981958/c08b4b49-a839-4e93-9cf3-031bd1a47426

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Hmm... I have to use

```adb
decrypt.day#@#ins.adsbygoogle:style(height: 1px !important; visibility: hidden !important;)
decrypt.day##ins.adsbygoogle:style(visibility: hidden !important;)
@@||decrypt.day^$ghide

@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=decrypt.day
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl$script,domain=decrypt.day
@@||googletagmanager.com/gtag/js$script,domain=decrypt.day
@@||fundingchoicesmessages.google.com^$script,domain=decrypt.day
```

Anyone has better ideas?

**Comment by JobcenterTycoon** [comment]
I need

```
decrypt.day#@#ins.adsbygoogle:style(height: 1px !important; visibility: hidden !important;)
decrypt.day##ins.adsbygoogle:style(visibility: hidden !important;)
@@||decrypt.day^$ghide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=decrypt.day
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl$script,domain=decrypt.day
@@||googletagmanager.com/gtag/js$script,domain=decrypt.day
@@||fundingchoicesmessages.google.com^$script,domain=decrypt.day
*$frame,redirect-rule=noopframe,domain=decrypt.day
```

**Comment by SwiftWinds** [comment]
Still doesn't work for me:

<img width="970" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/12981958/4cfd77b4-e5c6-4494-a7ed-10b363d87055">

Even though it works on a "Browse as Guest" session with no extensions (i.e., without adblock).

Just refreshed "uBlock Filters - Ads" a minute ago.

**Comment by jimmysofat6864** [comment]
Same issue here. I tried refreshing my filters but it doesn't work.

**Comment by jimmysofat6864** [comment]
I also tried waiting a few seconds but it didn't work.

**Comment by JobcenterTycoon** [comment]
Can reproduce, updated https://github.com/uBlockOrigin/uAssets/commit/1abb4286242847ad8355a65946c8b9d0779a0afb but its unstable because they keep updating.

**Comment by JobcenterTycoon** [comment]
Works fine for me.

**Comment by JobcenterTycoon** [comment]
Works for me. Its just important to wait a few seconds until clicking on the download button because the anti adblock script is very slow.

**Comment by JobcenterTycoon** [comment]
I know no other fix.

**Comment by yigitsalar** [comment]
Same issue.

**Comment by kotx** [comment]
Same issue on Firefox 134.0.1

**Comment by rakleed** [comment]
I can reproduce the problem again, see https://github.com/uBlockOrigin/uAssets/issues/27338#issue-2885029594

**Comment by llama-for3ver** [comment]
They have some JS going on that inserts a "bait" element. It looks like the following from the bundled code:

`<div id="aswift_5_host"><div class="checker"></div> <center class="w-full"><div class="w-full relative mb-4 h-0"><ins class="adsbygoogle"></ins></div></center> <iframe id="aswift_99" title="aswift_99" style="height: 0; width: 0;"></iframe> <div class="fc-message-root"></div></div>`
Just change it to something innocuous and it'll work.

**Comment by JobcenterTycoon** [comment]
At the moment the site is broken on my end but i excluded the `checker` bait now.

**Comment by llama-for3ver** [comment]
May just be a fluke, but disabling ETP on FF seems to let it download.

**Comment by cantunborn** [comment]
The adblock detection is still reproducible with ETP off on FF. Anyone has any idea which filters may be causing it?

**Comment by gothic-bum** [comment]
@cantunborn 

Test again after you disable all extensions except for uBO.  
  
If the issue still occurs, then post the uBO troubleshooting information as described here: https://github.com/uBlockOrigin/uAssets#how-to-correctly-report-an-issue
