### ISSUE TITLE
1337x.to: ads

### ISSUE THREAD

**Issue by pardub** [uBlockOrigin/uAssets#22848]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1337x.to/`

### Category

ads

### Description

This message is diaplyed when opening `https://1337x.to/`
" Please unblock challenges.cloudflare.com to proceed."

### Other extensions used

Bitwarden, skip redirect, TWP - Translate Web Pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cloudfare](https://github.com/uBlockOrigin/uAssets/assets/42610272/b8669618-f516-4bc0-9438-bf78073fdf0c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 130462
 cosmetic: 91140
 scriptlet: 24578
 html: 1740
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2610-1, 3m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2096-0, 3m
  adguard-spyware-url: 1476-222, 3m
  fanboy-cookiemonster: 50305-186, 3m
  ublock-cookies-easylist: 1026-0, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 37512-131, 3m
  ublock-badware: 7840-14, 3m
  ublock-privacy: 742-51, 3m
  ublock-unbreak: 2303-3, 3m
  ublock-quick-fixes: 168-1, 3m
  easylist: 82282-640, 3m
  easyprivacy: 50346-867, 3m
  urlhaus-1: 7715-0, 3m
  plowe-0: 3772-2, 3m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 12 redacted]
hostRuleset:
 added: [array of 129 redacted]
 removed:
  behind-the-scene * 3p noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2232 ms (selfie)
 maxAssetCacheWait: 779 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  cloudflare.com: 1
 extended:
  ##+js(remove-node-text, script, style)
  ##+js(abort-on-stack-trace, document.createElement, _0x)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, afScript)
  ##+js(no-setTimeout-if, adb)
  ##+js(nowebrtc)
  ##+js(abort-on-property-read, AaDetector)
```
</details>

**Comment by gorhill** [comment]
That's not an ad, it's cloudflare "human verification", which is blocked on your side, probably as a result of customization.

> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

**Comment by pardub** [comment]
Thank you for the insights.
I knew it wasn't an add but as it was a pop up, I wasn't too sure which statement to select in the list.
I'm using the medium mode and the`* * 3p-script block` in the rules panel was blocking the cloudfare challenge.
I actually misunderstood the meaning of custom filter/rules. As they are part of medium settings, I didn't consider them, for some reasons, as custom filter/rules , thinking wrongly that only filter lists as part of customization.
I had to setup a local noop rule for the third-party script to get the cloudfare challenge to sort this out.

**Comment by ItsProfessional** [comment]
If you aren't an advanced user, don't use medium mode and stick to defaults.

**Comment by gorhill** [comment]
[Blocking mode: medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode):

> Blocking-wise, this is one significant leap from [easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode). **However, be ready to accept that you will have to un-break websites**
