### ISSUE TITLE
surfline.com: ads

### ISSUE THREAD

**Issue by peanutarbuckle666** [uBlockOrigin/uAssets#22843]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.surfline.com/surf-report/crystal-pier/5842041f4e65fad6a7708a73?camId=607469675de89b52fae36137
```

### Description

Blocked ads successfully until a few days ago, now ad plays before cam feed starts. Another post was closed because they didn't provide screenshots, I've attached one here. I am using Firefox if that matters. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock surfline](https://github.com/uBlockOrigin/uAssets/assets/162814301/5cb9e88d-dabf-4003-af4d-e312b2204c7f)

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124659
 cosmetic: 45343
 scriptlet: 18868
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37480-239, 2h.44m Δ
  ublock-badware: 7827-14, 2h.44m Δ
  ublock-privacy: 742-0, 2h.44m Δ
  ublock-unbreak: 2301-2, 2h.44m Δ
  ublock-quick-fixes: 164-1, 2h.44m Δ
  easylist: 82045-539, 2h.44m Δ
  easyprivacy: 50346-842, 2h.44m Δ
  urlhaus-1: 7715-0, 1h.44m
  plowe-0: 3783-1, 11d.12h.40m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2908 ms (selfie)
 maxAssetCacheWait: 44 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  appsflyer.com: 1
  blogherads.com: 2
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  lr-in-prod.com: 1
  newrelic.com: 2
  segment.com: 1
 extended:
  ##.quiver-google-dfp
  ###sl-header-ad
  ##+js(adjust-setTimeout, adFreePopup, 15000, 0.02)
  ##+js(set-constant, Object.prototype.isPremium, true)
  ##+js(set-constant, __BACKPLANE_API__.renderOptions.showAdBlock,…

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Already addressed few hours ago: https://github.com/uBlockOrigin/uAssets/commit/61e28979ca407db3c14dfb4a46d768e87e5efe3f

**Comment by mapx-** [comment]
update your list using this link:

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1
