### ISSUE TITLE
blog.freeoseocheck.com: detection

### ISSUE THREAD

**Issue by grilzim** [uBlockOrigin/uAssets#22844]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://blog.freeoseocheck.com/post/link-analyzer`
'blog.carsmania.net'
'carsmania.net'
'blog.makeupguide.net'
'makeupguide.net'
'blog.cryptowidgets.net'
'cryptowidgets.net'
'blog.carstopia.net'
'carstopia.net'
by site Earnow site shortner

### Category

detection

### Description

A pop-up or iframe appears, announcing the detection of ublock and asking to deactivate it. At that moment the page freezes and the scroll does not work, it prevents you from using the ublock element 'pick', if you change the tab the page updates itself and stays like that permanently.

### Other extensions used

yes, the bypass all shortlinks of blogger permula

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock detected](https://github.com/uBlockOrigin/uAssets/assets/125164708/2b384577-2c6c-4959-8ec0-ef02c843494a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 129868
 cosmetic: 50461
 scriptlet: 37698
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=raw: 184-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 23219-19, now
 default:
  user-filters: 794-28, never
  easylist: 82275-23, 1h.19m Δ
  easyprivacy: 50346-35, 1h.19m Δ
  plowe-0: 3772-1185, now
  spa-1: 5432-74, now
  ublock-badware: 7833-146, 1h.19m Δ
  ublock-filters: 37344-2322, 1h.19m Δ
  ublock-privacy: 746-7, 1h.19m Δ
  ublock-quick-fixes: 171-19, 1h.19m Δ
  ublock-unbreak: 2246-38, 1h.19m Δ
  urlhaus-1: 7715-0, now
filterset (user): [array of 773 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2883 ms (selfie)
 maxAssetCacheWait: 290 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 32
 no-cosmetic-filtering: true
 no-large-media: true
 no-remote-fonts: true
 network:
  freeoseocheck.com: 2
  czilladx.com: 1
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 1
  gstatic.com: 3
  hbagency.it: 2
  menrealitycalc.com: 1
  netpub.media: 7
  r2b2.io: 10
  smilewanted.com: 1
  wtg-ads.com: 2
```
</details>

**Comment by huyszn** [comment]
Continue in #17361
