### ISSUE TITLE
scenexe2.io: detection

### ISSUE THREAD

**Issue by throwaway215** [uBlockOrigin/uAssets#22847]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://scenexe2.io
```

### Description

Upon loading the page it displays a banner that you are using an adblocker

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/a/fmMPQlr

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 124685
 cosmetic: 45554
 scriptlet: 20224
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82282-17, now
  easyprivacy: 50346-7, now
  plowe-0: 3772-1184, now
  ublock-badware: 7823-146, 7m
  ublock-filters: 37288-353, 7m
  ublock-privacy: 746-6, 7m
  ublock-quick-fixes: 162-18, 7m
  ublock-unbreak: 2246-35, 7m
  urlhaus-1: 7715-0, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5937 ms (selfie)
 maxAssetCacheWait: 468 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle:not(:empty)
```
</details>

**Comment by huyszn** [comment]
Enable the `uBlock filters - Annoyances` list

**Comment by D4niloMR** [comment]
Since it comes every time user refreshes the page it can be in the main list.
