### ISSUE TITLE
connect.secure.wellsfargo.com: breakage

### ISSUE THREAD

**Issue by kronus2023** [uBlockOrigin/uAssets#22859]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://connect.secure.wellsfargo.com/auth/login/present`

### Category

breakage

### Description

Cannot log in, states that username/password is incorrect. Turning off uBO (Power Button, upper right) then refreshing page fixes the problem. Firefox 123.0.1, uBO 1.56.0. Also happens on the latest version of Chrome 122.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 260374
 cosmetic: 197716
 scriptlet: 49417
 html: 1997
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79107-4165, 5m
  adguard-mobile: 9123-92, 5m
  adguard-spyware-url: 1476-107, 5m
  adguard-spyware: 113747-1410, 5m
  block-lan: 61-0, 5m
  curben-phishing: 14031-2, 5m
  adguard-social: 22241-1210, 5m
  adguard-cookies: 28897-1624, 5m
  ublock-cookies-adguard: 1029-13, 5m
  adguard-popup-overlays: 26756-1033, 5m
  adguard-mobile-app-banners: 5066-30, 5m
  adguard-other-annoyances: 13920-421, 5m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37605-299, 5m
  ublock-badware: 7847-14, 5m
  ublock-privacy: 750-1, 5m
  ublock-unbreak: 2299-3, 5m
  ublock-quick-fixes: 167-20, 5m
  easylist: 82160-17274, 5m
  easyprivacy: 50347-32161, 5m
  urlhaus-1: 7700-5, 5m
  plowe-0: 3772-1675, 6m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 917 ms (selfie)
 maxAssetCacheWait: 774 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 no-remote-fonts: true
 network:
  wellsfargo.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by kronus2023** [comment]
stephenhawk8054 - Thank you, that seems to have worked. It must have been one of the options I selected in addition to the default settings.

**Comment by ItsProfessional** [comment]
@kronus2023 Stick to the defaults, as they are more than enough for most users.
