### ISSUE TITLE
loadout.tf: ads

### ISSUE THREAD

**Issue by ghwtewteawteawrart** [uBlockOrigin/uAssets#22856]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://loadout.tf/`

### Category

ads

### Description

help

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124405
 cosmetic: 45581
 scriptlet: 20262
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82059-15, 6m Δ
  easyprivacy: 50346-7, 6m Δ
  plowe-0: 3772-1184, now
  ublock-badware: 7838-146, 6m Δ
  ublock-filters: 37412-354, 6m Δ
  ublock-privacy: 746-6, 6m Δ
  ublock-quick-fixes: 171-18, 6m Δ
  ublock-unbreak: 2246-35, 6m Δ
  urlhaus-1: 7575-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1212 ms (selfie)
 maxAssetCacheWait: 161 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 no-large-media: true
 no-popups: true
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
There's a `Description` part in the body of your issue. Put your description in there instead of writing "help" and don't put the description in the title.

**Comment by Sonic5435325** [comment]
![Screenshot from 2024-03-10 14-21-44](https://github.com/uBlockOrigin/uAssets/assets/89158249/9324ef92-d52d-43c7-8974-6401c4fc6ee4)

**Comment by stephenhawk8054** [comment]
@gorhill This site is using nested closed shadow roots, but somehow I can't use native `:has` with it.

Do you think this idea of using `window.find` for shadow roots case would be possible? https://github.com/uBlockOrigin/uBlock-issues/issues/2297#issuecomment-1792545613

**Comment by D4niloMR** [comment]
Maybe

```adb
loadout.tf##.header:has(> div[data-i18n^="#ad"])
loadout.tf##.header:has(> div[data-i18n^="#ad"]) + div:not([class]):last-child
```

?

**Comment by caw-caw-robinjay** [comment]
> ```
> loadout.tf##.header:has(> div[data-i18n^="#ad"])
> loadout.tf##.header:has(> div[data-i18n^="#ad"]) + div:empty:last-child
> ```

This solves the issue! Thank you kindly.

**Comment by Sonic5435325** [comment]
issues again

**Comment by caw-caw-robinjay** [comment]
the site's latest update has hidden:
killstreak sheens
cosmetic paint cans
the animation menu

**Comment by caw-caw-robinjay** [comment]
the issue has been fixed! i don't know what github etiquette is, but figured i would leave a thank-you to whoever it was that updated the filters to fix things up. your hard work goes appreciated!
