### ISSUE TITLE
jazbaat.in: detection

### ISSUE THREAD

**Issue by rayan135** [uBlockOrigin/uAssets#22854]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jazbaat.in/tips-to-reduce-your-household-energy-use/`

### Category

detection

### Description

it detacts it after like 5s

### Other extensions used

nope

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124495
 cosmetic: 45581
 scriptlet: 20261
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82059-15, now
  easyprivacy: 50346-7, now
  plowe-0: 3772-1184, now
  ublock-badware: 7838-146, now
  ublock-filters: 37411-354, now
  ublock-privacy: 746-6, now
  ublock-quick-fixes: 171-18, now
  ublock-unbreak: 2246-35, now
  urlhaus-1: 7670-5, never
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 494 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 1
  googlesyndication.com: 6
  googletagmanager.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##ins.adsbygoogle:not(:empty)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by ItsProfessional** [comment]
@rayan135 Is this a shortener?

**Comment by rayan135** [comment]
yes

**Comment by mapx-** [comment]
@rayan135 provide the original link not that useless link
