### ISSUE TITLE
propanefitness.com: breakage

### ISSUE THREAD

**Issue by skobylite** [uBlockOrigin/uAssets#22855]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://propanefitness.com/casestudy?el=pbwebsite
```

### Description

Opt-in box is lost when ublock origin is enabled, losing site functionality.

### Other extensions used

Brave browser (disabled shields, problem persists: isolated to ublock).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot2024-03-10 at 12 30 40@2x](https://github.com/uBlockOrigin/uAssets/assets/41369534/327987a9-f0b5-4c12-be23-e7257c04b28a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124405
 cosmetic: 45581
 scriptlet: 20262
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82059-15, 14m Δ
  easyprivacy: 50346-7, 14m Δ
  plowe-0: 3772-1184, 3m
  ublock-badware: 7838-146, 14m Δ
  ublock-filters: 37412-354, 14m Δ
  ublock-privacy: 746-6, 14m Δ
  ublock-quick-fixes: 171-18, 14m Δ
  ublock-unbreak: 2246-35, 14m Δ
  urlhaus-1: 7575-0, 3m
filterset (user): [empty]
trustedset:
 added: [array of 39 redacted]
switchRuleset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 213 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 13
 network:
  clickfunnels.com: 5
  cloudflareinsights.com: 1
  facebook.net: 1
  googletagmanager.com: 1
  hyros.com: 1
  newrelic.com: 4

```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||app.clickfunnels.com/assets/lander.js$script,domain=propanefitness.com
```

@ryanbr
