### ISSUE TITLE
users.jyu.fi: false detection

### ISSUE THREAD

**Issue by PyryAnttila** [uBlockOrigin/uAssets#22852]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://users.jyu.fi
```

### Description

Site is being blocked in the phishing URL blocklist. It is a website that redirects to the schools main page if not given any other information. Doesn't have anything to do with phishing.

### Other extensions used

Bypass Paywalls
Web Developer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 112
filterset (summary):
 network: 142809
 cosmetic: 46822
 scriptlet: 20282
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37431-129, now
  ublock-badware: 7840-14, now
  ublock-privacy: 742-0, now
  ublock-unbreak: 2303-3, now
  ublock-quick-fixes: 168-1, now
  easylist: 82054-641, now
  adguard-spyware-url: 1476-106, now
  easyprivacy: 50370-872, now
  urlhaus-1: 7775-5, now
  curben-phishing: 14078-2, now
  plowe-0: 3772-1, now
  LegitimateURLShortener: 2610-167, now
  bpc-paywall-filter: 1050-0, now
  AntiPaywall: 2096-15, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1367 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Please report here: https://gitlab.com/malware-filter/phishing-filter/-/issues

**Comment by PyryAnttila** [comment]
> Please report here: https://gitlab.com/malware-filter/phishing-filter/-/issues
> 
> In the meantime, add this as your custom filter:
> 
> ```
> ||users.jyu.fi^$badfilter
> ```

Done, thanks!
