### ISSUE TITLE
scamwarners.com: ads

### ISSUE THREAD

**Issue by colleirose** [uBlockOrigin/uAssets#22850]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.scamwarners.com/forum/viewtopic.php?f=13&t=217888`

### Category

ads

### Description

Ad leftovers:
![image](https://github.com/uBlockOrigin/uAssets/assets/147954091/a55e2211-3e35-40c5-bebf-b91526ed6901)

### Other extensions used

Wappalyzer
Privacy Badger
Tampermonkey
Indie Wiki Buddy
Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/147954091/292e17ac-0f80-4064-9da6-beb52930f7c9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124584
 cosmetic: 45582
 scriptlet: 18883
 html: 1740
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37559-123, now
  ublock-badware: 7840-14, now
  ublock-privacy: 742-0, now
  ublock-unbreak: 2303-2, now
  ublock-quick-fixes: 168-1, 1h.26m Δ
  easylist: 82075-629, now
  easyprivacy: 50346-862, now
  urlhaus-1: 7775-5, now
  plowe-0: 3772-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 238 ms (selfie)
 maxAssetCacheWait: 72 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  scamwarners.com: 1
  cloudflareinsights.com: 2
  d31qbv1cthcecs.cloudfront.net: 1
  getclicky.com: 1
  googlesyndication.com: 5
  googletagmanager.com: 1
  infolinks.com: 2
  smartlook.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
scamwarners.com##center:has-text(Advertisement)
scamwarners.com##.subheader:has(> ins.adsbygoogle)
```
