### ISSUE TITLE
klz9.com: ads

### ISSUE THREAD

**Issue by afat123** [uBlockOrigin/uAssets#22853]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://klz9.com/jxsh-the-king-of-cave-will-live-a-paradise-life-manga-raw-chapter-29.1.html
```

### Description

it has an ad like the pic in the screenshots. in between 1st and 2nd page.
using private windows removes the ad, but it keeps the black background the same as having the ads. 

previously, ublock works like a charm, it just from a few days ago the ad keeps popping up back again.
picking it using the element picker doesnt seem to work, when i refersh the page the ad comes back.
so need help removing the ads and the black background too.
thanks in advance

### Other extensions used

bypass paywalls clean
clearURLs
enhancer for youtube
fastforward
google unlocked
honey
image search options
malwarebytes browser guard
pixiv toolkit
redirector
return youtube dislike
social fixer for facebook
sponsorblock for youtube - skips sponsorships
tampermonkey
xdm browser monitor
xdm v8+ browser helper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/65108757/e1110d3f-47b3-45aa-9ee9-a56bff739ef7)
![image](https://github.com/uBlockOrigin/uAssets/assets/65108757/2b9ae2bd-70bf-40e5-93bc-97c13aa695bf)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124495
 cosmetic: 45567
 scriptlet: 18891
 html: 1740
listset (total-discarded, last-updated):
 default:
  user-filters: 20-1, never
  ublock-filters: 37563-123, 32m Δ
  ublock-badware: 7840-14, 32m Δ
  ublock-privacy: 742-0, 32m Δ
  ublock-unbreak: 2303-2, 32m Δ
  ublock-quick-fixes: 168-1, 32m Δ
  easylist: 82054-629, 32m Δ
  easyprivacy: 50346-866, 32m Δ
  urlhaus-1: 7670-5, 22h.32m
  plowe-0: 3783-1, 10d.11h.25m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 267 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  klz9.com: 2
  aso1.net: 2
  bidgear.com: 10
  cliqtag.net: 2
  diclotrans.com: 2
  googletagmanager.com: 4
  klimv1.xyz: 1
  pubfuture-ad.com: 2
  smasheswamefou.com: 1
 extended:
  ##.float-ck

```
</details>

**Comment by gwarser** [comment]
"AdGuard – Ads" has filters for this page.

**Comment by ItsProfessional** [comment]
I can't reproduce the ads.
@afat123 Remove all of your extensions and reset uBO to defaults and test again.

**Comment by stephenhawk8054** [comment]
I can reproduce using VPN to Spain. The filter in Adguard Ads works for me

```adb
klz9.com###list-imga > center > div[style^="width:336px"]
```

@ryanbr

**Comment by ryanbr** [comment]
Not seeing it? we have from yesterday: https://github.com/easylist/easylist/commit/ce91b3f61b543a1708a63a4b90af1aa07a2b02d8

`klz9.com##div[style^="width:336px"]`

**Comment by stephenhawk8054** [comment]
Ah ok, maybe the update hasn't come to me yet.

**Comment by Elhazinforever1** [comment]
Wrong check again

في أحد، 10 مارس، 2024 في 2:38 م، كتب Fanboynz ***@***.***>:

**Comment by afat123** [comment]
the ads is gone for me, but it left this:
![image](https://github.com/uBlockOrigin/uAssets/assets/65108757/b8948e72-3cd0-4970-a5b6-2afcc9ebd05e)
