### ISSUE TITLE
ttzj666.com: detection

### ISSUE THREAD

**Issue by Iovenoname** [uBlockOrigin/uAssets#22861]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ttzj666.com/`

### Category

detection

### Description

Picture A represents the situation where uBlock Origin has not been closed, Picture B represents the situation where uBlock Origin has been closed.
![屏幕截图 2024-03-11 163518](https://github.com/uBlockOrigin/uAssets/assets/124352494/a30a36ab-636c-4453-b7fc-27a69fb29dd9)

### Other extensions used

NO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 123
filterset (summary):
 network: 262001
 cosmetic: 256852
 scriptlet: 49598
 html: 1997
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79097-3896, 1h.3m
  adguard-mobile: 9123-62, 1h.3m
  adguard-spyware-url: 1476-107, 1h.3m
  adguard-spyware: 113747-1395, 1h.3m
  block-lan: 61-0, 1h
  adguard-social: 22241-53, 1h
  adguard-cookies: 28895-48, 1h
  adguard-popup-overlays: 26756-993, now
  adguard-mobile-app-banners: 5066-21, 1h
  adguard-other-annoyances: 13921-414, 1h
  adguard-widgets: 2412-12, 1h.1m
  fanboy-thirdparty_social: 68-3, 1h.1m
  [8 lists not shown]: [too many]
 default:
  user-filters: 1246-10, never
  ublock-filters: 37596-105, 1h.3m
  ublock-badware: 7847-14, 1h.3m
  ublock-privacy: 750-1, 1h.3m
  ublock-unbreak: 2299-2, 1h.3m
  ublock-quick-fixes: 167-20, 1h.3m
  easylist: 82079-1666, 1h.3m
  easyprivacy: 50347-32160, 1h
  urlhaus-1: 7700-5, 1h
  plowe-0: 3772-1674, 1h.2m
  CHN-0: 25553-256, 1h.2m
filterset (user): [array of 1200 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  about-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3054 ms (selfie)
 maxAssetCacheWait: 734 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 14
 network:
  ttzj666.com: 5
  baidu.com: 2
  chuzushijian.cn: 1
  haokoubei.top: 4
  ymmiyun.com: 2
 extended:
  ##.open-share
  ##.bdsharebuttonbox
```
</details>

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/3894763ca4df59089d1d33d7e51024e128738d89
