### ISSUE TITLE
amazon.de: breakage

### ISSUE THREAD

**Issue by h-nn-ng** [uBlockOrigin/uAssets#22862]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.amazon.de/Akku-Winkelschleifer-Bohrungsdurchmesser-Scheibendurchmesser-arretierbarer-Einschalter/dp/B00B8AFJYI/ref=pd_day0fbt_d_sccl_2/259-8844556-3179435?pd_rd_w=puT8v&content-id=amzn1.sym.a448a60d-171e-41b3-a693-2dc17f9728e0&pf_rd_p=a448a60d-171e-41b3-a693-2dc17f9728e0&pf_rd_r=P4YKQA5ZMFPM66BQGT4X&pd_rd_wg=iKKpH&pd_rd_r=bde8279d-d9e0-4510-bf58-2728f5ea52ad&pd_rd_i=B00B8AFJYI&th=1`

### Category

breakage

### Description

Viewing of review photo galleries is blocked.
![Bildschirmfoto 2024-03-10 um 19 49 16](https://github.com/uBlockOrigin/uAssets/assets/13087104/b428914f-6b1a-4af1-bdbb-50d2edfb4159)

### Other extensions used

![Bildschirmfoto 2024-03-11 um 11 44 21](https://github.com/uBlockOrigin/uAssets/assets/13087104/8dde4052-e0da-481e-a023-4d5ccf1cb19b)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bildschirmfoto 2024-03-10 um 19 49 16](https://github.com/uBlockOrigin/uAssets/assets/13087104/1e9232ad-1e8c-41d5-840b-7d2213868696)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126960
 cosmetic: 50553
 scriptlet: 20280
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7323-0, now
  easylist: 82160-23, now Δ
  easyprivacy: 50347-17, now Δ
  plowe-0: 3772-1185, 1d.15h.48m
  ublock-badware: 7843-146, now Δ
  ublock-filters: 37442-370, now Δ
  ublock-privacy: 754-6, now Δ
  ublock-quick-fixes: 170-17, now Δ
  ublock-unbreak: 2242-37, now Δ
  urlhaus-1: 7700-5, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 159 ms (selfie)
 maxAssetCacheWait: 53 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 111
 network:
  amazon.de: 91
  amazon-adsystem.com: 1
  amazon.com: 7
  amazonaws.com: 1
  d5glw3nnbe3pc.cloudfront.net: 4
  media-amazon.com: 1
  ssl-images-amazon.com: 6
 extended:
  ##.reviews-display-ad
  ###ape_Detail_ad-endcap-1_Glance_placement
  ###heroQuickPromo_feature_div
  ##div[data-ad-id]
  ##div[id^="sp_detail"]
  ###nav-swmslot
  ###sponsoredProducts2_feature_div
  ##div[cel_widget_id*="_ad-placements-"]
  ##div[cel_widget_id*="desktop-dp-"]
  ##div[cel_widget_id^="adplacements:"]
  ##div[cel_widget_id^="multi-brand-"]
  ##div[data-a-carousel-options*="\\\"isSponsoredProduct\\\":\\\"t…
  ##div[cel_widget_id="sims-consolidated-5_csm_instrumentation_wra…
  ##+js(json-prune, cuepointPlaylist)
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] |…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
