### ISSUE TITLE
webextension.org: ads

### ISSUE THREAD

**Issue by KTibow** [uBlockOrigin/uAssets#22867]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://webextension.org/`

### Category

ads

### Description

There is a section that looks like an advertisement and is labeled as an advertisement. See screenshot.

### Other extensions used

The extensions with "read and change data" are Stylus, Firefox Multi-Account Containers, Block Site, and User-Agent Switcher and Manager.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/10727862/7b1b52ce-9b75-43ab-b5fb-9c9c10eb3c24)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124817
 cosmetic: 45585
 scriptlet: 18920
 html: 1741
listset (total-discarded, last-updated):
 added:
  block-lan: 61-0, now
 default:
  user-filters: 7-0, never
  ublock-filters: 37613-123, now
  ublock-badware: 7852-14, now
  ublock-privacy: 750-0, now
  ublock-unbreak: 2299-2, now
  ublock-quick-fixes: 174-1, now
  easylist: 82154-630, 1h.41m Δ
  easyprivacy: 50347-861, 1h.41m Δ
  urlhaus-1: 7825-5, 1h.41m
  plowe-0: 3772-1, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 736 ms (selfie)
 maxAssetCacheWait: 102 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googlesyndication.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings

**Comment by KTibow** [comment]
I believe it must somehow toggle between a Google ad and a custom ad, as when I'm now visiting it anywhere it's giving me a Google ad. Regardless, in all profiles I still see the wrapper that says Advertisement, which should be removed.

**Comment by stephenhawk8054** [comment]
Yes, I see the placeholder. But the ads inside is blocked. I see that you are using a modified configuration of uBO

```yml
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 3 redacted]
```

and you might be unblocking something with it. Your blocked section lacks `##ins.adsbygoogle` compared to what on my side

```yml
popupPanel:
 blocked: 1
 network:
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(set-constant, rwt, noopFunc)
```

That's why I told you to test on a new profile with only uBO and its default settings. Don't change anything.

---

About the placeholder

```adb
webextension.org##.adb
```

@ryanbr

**Comment by KTibow** [comment]
> But the ads inside is blocked.

To clarify:
I believe that this site dynamically switches the ad type. When I created this issue, the ad was a *custom ad* by the maker of the website, only for other extensions, as shown in the screenshot. However, it changed to an iframe of Google Ads. But at this point everything's good.

**Comment by punisher018** [comment]
Also need that filter. For example on this page there is similar ad space at the top.  @ryanbr 
`https://webextension.org/listing/allow-right-click.html`

`webextension.org###adb`
