### ISSUE TITLE
kozkutak.hu: breakage

### ISSUE THREAD

**Issue by brabazsi** [uBlockOrigin/uAssets#22863]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kozkutak.hu/?z=9&c=47.1253/17.8212&o=0`

### Category

breakage

### Description

uBlock Origin blocks the markers on the map.

This is how the website looks with uBlock turned on:
![kép_2024-03-11_121414555](https://github.com/uBlockOrigin/uAssets/assets/86551652/4ab58203-e020-429d-979b-0565bc4741ed)

This is how it looks with uBlock turned off: (how it should)
![kép_2024-03-11_121302273](https://github.com/uBlockOrigin/uAssets/assets/86551652/93163267-6866-4dc5-bfbe-205da121c870)

### Other extensions used

none of my extensions were active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

(Just copied from above)
![kép_2024-03-11_121414555](https://github.com/uBlockOrigin/uAssets/assets/86551652/4ab58203-e020-429d-979b-0565bc4741ed)
![kép_2024-03-11_121302273](https://github.com/uBlockOrigin/uAssets/assets/86551652/93163267-6866-4dc5-bfbe-205da121c870)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 124946
 cosmetic: 47315
 scriptlet: 20317
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  HUN-0: 2082-0, now
  easylist: 82160-17, 1h.40m Δ
  easyprivacy: 50347-18, 1h.40m Δ
  plowe-0: 3772-1185, now
  ublock-badware: 7843-146, 1h.40m Δ
  ublock-filters: 37442-356, 1h.40m Δ
  ublock-privacy: 754-6, 1h.40m Δ
  ublock-quick-fixes: 170-17, 1h.40m Δ
  ublock-unbreak: 2242-35, 1h.40m Δ
  urlhaus-1: 7700-5, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 772 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 7
 network:
  kozkutak.hu: 4
  google.com: 1
  maps.googleapis.com: 1
  scriptcdn.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `&t=pageview&` in EP.

Test `&t=pageview&$badfilter`

@ryanbr
