### ISSUE TITLE
realmadryt.pl: breakage

### ISSUE THREAD

**Issue by PiotrWadolowski** [uBlockOrigin/uAssets#22869]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.realmadryt.pl/`

### Category

breakage

### Description

The site detects that Adblocker is enabled and does not allow logging into an already existing account that is saved with cookies. Manualy log in is also not working. Confirmed that the site works normally when uBlock is disabled.

### Other extensions used

Grammarly and Windows Accounts

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![main](https://github.com/uBlockOrigin/uAssets/assets/108071825/c8acd59c-bfbf-4455-a5ae-2705d266cb21)
![login site](https://github.com/uBlockOrigin/uAssets/assets/108071825/f7817c8c-e105-4090-b659-66dadfe704c8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 251488
 cosmetic: 254414
 scriptlet: 51221
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28914-33, now
  adguard-generic: 79072-753, 7m
  adguard-mobile: 9126-53, 7m
  adguard-mobile-app-banners: 5066-9, now
  adguard-other-annoyances: 13925-13, now
  adguard-popup-overlays: 26773-97, now
  adguard-social: 22253-906, now
  adguard-spyware: 113918-1174, now
  adguard-spyware-url: 1477-5, now
  adguard-widgets: 2412-6, now
  block-lan: 61-0, now
  curben-phishing: 14094-1, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  POL-0: 8694-9, now
  POL-2: 1280-14, 43m
  easylist: 82253-1559, now
  easyprivacy: 50352-32189, now
  plowe-0: 3772-1349, now
  ublock-badware: 7858-256, now
  ublock-filters: 37464-4007, now
  ublock-privacy: 754-219, now
  ublock-quick-fixes: 175-17, now
  ublock-unbreak: 2242-155, now
  urlhaus-1: 7825-5, now
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 284 ms (selfie)
 maxAssetCacheWait: 110 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
  optad360.io: 2
  vidverto.io: 1
 extended:
  ##.gamebar-section-sponsors
  ##fieldset
  ##div[class^="rmpl-adsense-"]
  ##A[href$="/reklama"]
  ##+js(prevent-fetch, /optad360\.io|pagead2\.googlesyndication\.c…
  ##+js(prevent-fetch, method:GET)
```
</details>

**Comment by mapx-** [comment]
wrong filter in [Oficjalne Polskie Filtry do uBlocka Origin](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=POL-0)

needing 
`realmadryt.pl#@#fieldset`
