### ISSUE TITLE
toggo.de: breakage

### ISSUE THREAD

**Issue by odin81** [uBlockOrigin/uAssets#22868]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.toggo.de/toggolino/rubble--crew-pty561/folge/die-crew-baut-eine-bruecke-vep15306`

### Category

breakage

### Description

The site has again problems with uBlock enabled. It tries to play Ads and hangs.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 127000
 cosmetic: 50526
 scriptlet: 18912
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37591-167, 1m Δ
  ublock-badware: 7847-14, 1m Δ
  ublock-privacy: 750-0, 1m Δ
  ublock-unbreak: 2303-2, 1m Δ
  easylist: 82082-638, 1m Δ
  easyprivacy: 50347-843, 1m Δ
  urlhaus-1: 7825-5, 1m
  plowe-0: 3772-1, 1m
  DEU-0: 7324-3, 2m
  ublock-quick-fixes: 168-1, 1m Δ
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3040 ms
 maxAssetCacheWait: 280 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  adobedtm.com: 4
  demdex.net: 1
  emsservice.de: 6
  firebaselogging-pa.googleapis.com: 2
  googlesyndication.com: 2
  mopinion.com: 1
  omtrdc.net: 3
  opecloud.com: 1
  sentry.io: 5
  youborafds01.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
@khrin

**Comment by JobcenterTycoon** [comment]
@monzta

**Comment by Khrin** [comment]
Unable to reproduce with current filters. (Without your "fixes") Not sure what you exactly want, @JobcenterTycoon

**Comment by Khrin** [comment]
.

cannot reproduce it with ubo on ff.  I could see the same problem on ABP when the bumper videos were blocked, I suppose that's why monzta used $rewrite in ELG instead of blocking the resources. 

I don't see any reason to change our filters, maybe you can edit your fixes to do something similar to what ELG have now? using what ubo has in place to redirect (or rewrite), instead of blocking altogether.
