### ISSUE TITLE
fidelitefree.fr: detection

### ISSUE THREAD

**Issue by orbotimn75** [uBlockOrigin/uAssets#22864]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fidelitefree.fr/`

### Category

detection

### Description

This site https://fidelitefree.fr/ is a phishing campaign against customers Free mobile.

The legitimate page can be found at : https://mobile.free.fr/

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 140256
 cosmetic: 52429
 scriptlet: 19058
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 10-1, never
  ublock-filters: 37613-221, now
  ublock-badware: 7852-14, now
  ublock-privacy: 750-0, now
  ublock-unbreak: 2299-2, now
  easylist: 82154-748, now
  easyprivacy: 50347-833, now
  urlhaus-1: 7825-5, now
  plowe-0: 3772-1, now
  FRA-0: 23036-305, now
  ublock-quick-fixes: 174-1, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 25 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1525 ms (selfie)
 maxAssetCacheWait: 201 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
You can continue at the old thread next time: https://github.com/uBlockOrigin/uAssets/issues/22765 . All volunteers are notified with new comments.
