### ISSUE TITLE
statisticsanddata.org: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#22875]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://statisticsanddata.org/data/most-popular-backend-frameworks-2012-2023/`

### Category

breakage

### Description

blocking video

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/fa2c29ec-4f41-4918-88c7-f05c7d54cefd)
![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/450e2ec9-4ba5-4734-bf51-102b1bc7a702)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 135999
 cosmetic: 163730
 scriptlet: 34556
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 9181-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 199-0, 46m
  adguard-cookies: 28921-33, now
  adguard-other-annoyances: 13925-24, now
  adguard-popup-overlays: 26775-80, now
  easylist-annoyances: 4427-216, now
  easylist-notifications: 2958-393, now
  fanboy-cookiemonster: 50337-3849, now
  spa-1: 5434-75, now
  ublock-annoyances: 6872-231, 1h.46m Δ
  ublock-cookies-adguard: 1031-1029, now
  ublock-cookies-easylist: 1031-1031, now
 default:
  user-filters: 45-0, never
  easylist: 82263-76, 1h.46m Δ
  easyprivacy: 50352-115, 1h.46m Δ
  plowe-0: 3772-1185, now
  ublock-badware: 7858-148, 1h.46m Δ
  ublock-filters: 37470-797, 1h.46m Δ
  ublock-privacy: 754-7, 1h.46m Δ
  ublock-quick-fixes: 175-15, 1h.46m Δ
  ublock-unbreak: 2242-42, 1h.46m Δ
  urlhaus-1: 7770-5, now
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 35 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1062 ms (selfie)
 maxAssetCacheWait: 380 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  statisticsanddata.org: 3
  googletagmanager.com: 1
  ko-fi.com: 1
 extended:
  ###cmplz-cookiebanner-container
  ##.cookie-statement
```
</details>

**Comment by liamengland1** [comment]
` [X]  I did not answer truthfully to ALL the above checkboxes.`

**Comment by stephenhawk8054** [comment]
It's hidden by the cookie lists, but I think the videos can be unblocked without the need of users accepting the consent

```adb
statisticsanddata.org##.cmplz-blocked-content-container:remove-class(cmplz-blocked-content-container)
statisticsanddata.org##+js(set-attr, iframe[data-src-cmplz][src="about:blank"], src, [data-src-cmplz])
```
