### ISSUE TITLE
4sharedlink.com: breakage

### ISSUE THREAD

**Issue by PREETCHAUHAN** [uBlockOrigin/uAssets#22878]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://4sharedlink.com/FLSTUdioWiN`

### Category

breakage

### Description

**Count down not starting**

### Other extensions used

**No**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Opera Snapshot_2024-03-12_155130_4sharedlink com](https://github.com/uBlockOrigin/uAssets/assets/33035404/5e7a541a-f661-4336-8e64-d745ef35308b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 341192
 cosmetic: 368391
 scriptlet: 55919
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  ALB-0: 305-0, now
  BGR-0: 1040-1, now
  CHN-0: 25567-129, now
  CZE-0: 832-1, now
  DEU-0: 7324-0, now
  EST-0: 464-2, now
  FIN-0: 2281-0, now
  FRA-0: 22830-65, now
  GRC-0: 1074-0, now
  HRV-0: 388-2, now
  HUN-0: 2082-2, now
  IDN-0: 9869-19, now
  [47 lists not shown]: [too many]
 default:
  easylist: 82264-2055, 7m Δ
  easyprivacy: 50352-32524, 7m Δ
  plowe-0: 3772-1709, now
  ublock-badware: 7858-283, 7m Δ
  ublock-filters: 37459-4184, 7m Δ
  ublock-privacy: 754-221, 7m Δ
  ublock-quick-fixes: 175-20, 7m Δ
  ublock-unbreak: 2242-175, 7m Δ
  urlhaus-1: 7770-5, now
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1401 ms (selfie)
 maxAssetCacheWait: 372 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  addthis.com: 1
  googletagmanager.com: 1
  rawgit.com: 1
 extended:
  ##.addthis_toolbox
  ##.addthis_default_style
  ##.addthis_32x32_style
  ##.addthis_button_facebook
  ##.addthis_button_twitter
  ##.addthis_button_pinterest_share
  ##.addthis_button_google_plusone_share
  ##.addthis_button_linkedin
  ##.addthis_button_compact
```
</details>

**Comment by dportvine** [comment]
Add in My filters & check again `/jquery.particleground.min.js$badfilter`

**Comment by ItsProfessional** [comment]
@PREETCHAUHAN You're using a heavily customized configuration of uBO. We can't help such users. Reset uBO.

**Comment by dportvine** [comment]
> /jquery.particleground.min.js$badfilter

This rule works for me.

<details>
<summary>Screen</summary>

![2024-03-12_125633](https://github.com/uBlockOrigin/uAssets/assets/111344219/7004e4a1-3972-4b8b-86fe-8d55d7924b92)
![2024-03-12_125633](https://github.com/uBlockOrigin/uAssets/assets/111344219/f71da09e-b7a1-4f3d-8db8-91b742a46a6d)
</details>

**Comment by mapx-** [comment]
@ryan 

breakage due to `EasyList – Other Annoyances`

`/jquery.particleground.min.js$badfilter`
