### ISSUE TITLE
nextdoor.com: ads

### ISSUE THREAD

**Issue by blakegearin** [uBlockOrigin/uAssets#22877]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://nextdoor.com/for_sale_and_free
https://nextdoor.com/news_feed
```

### Description

On the "Free & For Sale" page, ads are inserted as tiles alongside listings. Sponsored posts are also inserted in the news feed.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1476" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/17950836/f4c9e608-e19d-40ad-b007-c0573806f5ab">

![image](https://github.com/uBlockOrigin/uAssets/assets/17950836/6a7ed152-8776-4914-a3b8-b14da722f5e1)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
userSettings: [none]
Firefox: 113
listset (total-discarded, last-updated):
 default:
  ublock-filters: 37532-104, 2m
  easyprivacy: 50346-57, 1m
  ublock-badware: 7862-14, 2m
  plowe-0: 3772-1185, 1m
  urlhaus-1: 7770-5, 1m
  ublock-quick-fixes: 166-13, 1m
  user-filters: 0-0, never
  ublock-privacy: 740-0, 2m
  easylist: 82262-252, 1m
  ublock-unbreak: 2299-2, 1m
supportStats:
 maxAssetCacheWait: 305 ms
 allReadyAfter: 411 ms
hiddenSettings: [none]
filterset (summary):
 scriptlet: 18888
 cosmetic: 45560
 html: 1740
 network: 124775
uBlock Origin: 1.51.0
filterset (user): [empty]
popupPanel:
 blocked: 0
```
</details>

**Comment by ryanbr** [comment]
Asking internally if someone can test this. Created an account, but cannot verify non-US accounts

**Comment by ryanbr** [comment]
Does this help?
```
nextdoor.com##a[href][target="_blank"] > [class] > [class]
```

**Comment by blakegearin** [comment]
> Does this help?

Looks like that works but only for the news feed.

**Comment by liamengland1** [comment]
@blakegearin test the following please

```
nextdoor.com##.feed-container>div>div>div:has(span:has-text(/^Sponsored$/))
nextdoor.com##.info-bar-container>aside>div>div:has(.nas-container)
nextdoor.com##.classifieds-nav-bar+.feed-container>div>div>div>div>div[data-v3-view-type]+:not([data-v3-view-type])
```

First filter is for home feed ads.
Second filter is for sidebar ads.
Third filter is for ads in the for sale listing feed

**Comment by blakegearin** [comment]
Those seem to work.

**Comment by liamengland1** [comment]
@mapx- I don't see a linked commit, was it added to easylist?

**Comment by mapx-** [comment]
I notified @ryanbr on slack about the test results, so ... it's up to EL

**Comment by D4niloMR** [comment]
Do you have a dummy account for this site? Or please highlight the ads in the DOM tree and share here

**Comment by liamengland1** [comment]
@D4niloMR you can dm me on slack, also see here https://listauthorschat.slack.com/archives/C05G8V3NERH/p1710453007064609
