### ISSUE TITLE
[nsfw] js-xzsh.com: ads

### ISSUE THREAD

**Issue by M4-SOP2** [uBlockOrigin/uAssets#22872]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://js-xzsh.com/mj/index.html?mash=qZkuSDeTnM&style=2`

### Category

ads

### Description

ads

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 139535
 cosmetic: 56067
 scriptlet: 19095
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37591-143, 1m
  ublock-badware: 7852-14, 1m
  ublock-privacy: 750-0, 1m
  ublock-unbreak: 2299-2, 1m
  ublock-quick-fixes: 174-1, 1m
  easylist: 82242-652, 1m
  easyprivacy: 50352-874, 1m
  urlhaus-1: 7825-5, 1m
  plowe-0: 3772-1, 1m
  CHN-0: 25559-132, 1m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1934 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by D4niloMR** [comment]
I don't see any ads.
