### ISSUE TITLE
theverge.com: ads

### ISSUE THREAD

**Issue by colejohnson66** [uBlockOrigin/uAssets#22879]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.theverge.com/`

### Category

ads

### Description

Ad shows on page.

Suggested network filters from picker:

```
||www.nytimes.com/svc/oembed/html/?url=https%3A%2F%2Fwww.nytimes.com%2F2024%2F03%2F11%2Ftechnology%2Fcarmakers-driver-tracking-insurance.html
||www.nytimes.com/svc/oembed/html/
```

### Other extensions used

Only relevant would be Greasemonkey. Disabling it still shows the ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ad](https://github.com/uBlockOrigin/uAssets/assets/11381599/6b8f0105-73f8-4c76-b4c4-9ee8061c99a5)
![Suggested filters from picker](https://github.com/uBlockOrigin/uAssets/assets/11381599/625f6fb2-08bd-46eb-be8d-d9998db0af3f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 128903
 cosmetic: 117896
 scriptlet: 23935
 html: 1741
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50337-196, now
  fanboy-social: 15781-8, now
  easylist-annoyances: 4427-98, now
  easylist-chat: 186-0, now
  easylist-newsletters: 7117-12, now
  easylist-notifications: 2958-3, now
  ublock-cookies-easylist: 1031-0, now
 default:
  user-filters: 4-0, never
  ublock-filters: 37615-121, 35m Δ
  ublock-badware: 7862-14, 35m Δ
  ublock-privacy: 750-0, now
  ublock-unbreak: 2299-2, 35m Δ
  ublock-quick-fixes: 172-1, 35m Δ
  easylist: 82264-659, 35m Δ
  easyprivacy: 50352-949, 35m Δ
  urlhaus-1: 7770-5, now
  plowe-0: 3772-1, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 332 ms (selfie)
 maxAssetCacheWait: 183 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  amazon-adsystem.com: 1
  btloader.com: 1
  concert.io: 1
  doubleverify.com: 1
  google-analytics.com: 1
  googleoptimize.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  indexww.com: 1
  monacobeatles.com: 1
  narrativ.com: 1
  parsely.com: 2
  permutive.com: 1
  rubiconproject.com: 1
  sail-horizon.com: 1
  sentry.io: 1
  twitter.com: 5
 extended:
  ##div[data-concert]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.m-ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##article.story:style(opacity: 1.0 !important;)
  ##body:style(overflow: auto !important;)
```
</details>

**Comment by liamengland1** [comment]
That’s not an ad…

**Comment by colejohnson66** [comment]
Looking at it again, I can see that it isn't. But it looks like one at first glance.
