### ISSUE TITLE
123menlife.com: ads

### ISSUE THREAD

**Issue by spear13** [uBlockOrigin/uAssets#22876]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.123menlife.com/`

### Category

ads

### Description

Publicité 

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 122
filterset (summary):
 network: 141729
 cosmetic: 41252
 scriptlet: 19131
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37983-447, 29m Δ
  ublock-badware: 7856-14, 29m Δ
  ublock-privacy: 751-1, 29m Δ
  ublock-unbreak: 2304-3, 29m Δ
  ublock-quick-fixes: 172-1, 29m Δ
  adguard-mobile: 9126-133, 29m
  easylist: 82262-16430, 29m Δ
  easyprivacy: 50352-1041, 29m Δ
  urlhaus-1: 7770-5, 29m
  plowe-0: 3772-1, 29m
  FRA-0: 22830-3038, 29m
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 272 ms (selfie)
 maxAssetCacheWait: 118 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  advlistings.com: 1
  googletagmanager.com: 4
  taboola.com: 1
```
</details>

**Comment by dportvine** [comment]
@spear13 
Can you add a screenshot?
