### ISSUE TITLE
[nsfw] tiktokcounter.net: detection

### ISSUE THREAD

**Issue by MvSimorq** [uBlockOrigin/uAssets#22884]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokcounter.net/marketing/how-to-choose-the-right-lawyer/`

### Category

detection

### Description

site can detect ublock and remove button to press for going to next page

### Other extensions used

pocket, simple translate, idm

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126275
 cosmetic: 47264
 scriptlet: 20432
 html: 0
listset (total-discarded, last-updated):
 added:
  IRN-0: 3015-0, 1m
 default:
  user-filters: 0-0, never
  easylist: 82283-21, 1m
  easyprivacy: 50358-18, 1m
  plowe-0: 3772-1186, 1m
  ublock-badware: 7858-148, 1m
  ublock-filters: 37471-355, 1m
  ublock-privacy: 754-6, 1m Δ
  ublock-quick-fixes: 149-17, 1m
  ublock-unbreak: 2244-37, 1m
  urlhaus-1: 8015-5, 1m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 461 ms (selfie)
 maxAssetCacheWait: 261 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 13
 network:
  google-analytics.com: 2
  googlesyndication.com: 6
  googletagmanager.com: 2
  profitsfly.com: 3
 extended:
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(abort-on-stack-trace, Promise.all, injectedScript)
  ##+js(no-setTimeout-if, console)
```
</details>

**Comment by huyszn** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/discussions/17361
