### ISSUE TITLE
klarna purchase flow blocked by filter

### ISSUE THREAD

**Issue by thejool** [uBlockOrigin/uAssets#22881]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://pay.playground.klarna.com/eu/hpp/payments/${ID} (not possible to share actual URL as it's related to a purchase)
```

### Description

A previously added filter is blocking klarna purchase flow and making it impossible to place a purchase using klarna when having uBlockOrigin popup overlay filter enabled. This filter: https://github.com/uBlockOrigin/uAssets/issues/18594 is applied way to widely and is preventing the whole klarna purchase flow instead of just the popup it was intended to block.

URL can not be shared due to being purchases but can be reproduced at ikea ecommerce for example.

### Other extensions used

none (incognito)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/7832336/ff0aa3da-f0d1-4e01-9573-3b60090c7bb6)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 128287
 cosmetic: 67789
 scriptlet: 21463
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 26781-44, 3m
 default:
  user-filters: 0-0, never
  easylist: 82264-46, 16m
  easyprivacy: 50352-66, 16m
  plowe-0: 3772-1184, 16m
  ublock-badware: 7858-147, 16m
  ublock-filters: 37459-432, 16m
  ublock-privacy: 754-6, 16m
  ublock-quick-fixes: 175-15, 16m
  ublock-unbreak: 2242-36, 16m
  urlhaus-1: 8015-5, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2665 ms
 maxAssetCacheWait: 1201 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 23
 network:
  klarnaevt.com: 19
  sentry.io: 4
 extended:
  ##body > div#root ~ script + div

```
</details>

**Comment by mapx-** [comment]
> can be reproduced at ikea ecommerce for example

provide link, steps to reproduce the issue, if an account is required

@Alex-302

**Comment by thejool** [comment]
https://www.ikea.com/se/en/p/faergklar-18-piece-service-matt-light-grey-70564699/

1. Add to shopping bag
2. Go to shopping bag
3. Continue to checkout
4. Continue as guest
5. Select delivery
6. Fill in address
7. Choose "Klarna pay later" as payment method
8. Check terms and conditions
9. Press complete my order
10. Page is redirect to klarna but the page is blank due to uBlockOrigin filter
