### ISSUE TITLE
alpin.de: ads

### ISSUE THREAD

**Issue by Manziel123** [uBlockOrigin/uAssets#22883]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.alpin.de/home/olaf-klaert-das-schon/22570/artikel_wann_sollte_man_seine_alte_ausruestung_erneuern.html`

### Category

ads

### Description

Shows plenty of ads
![image](https://github.com/uBlockOrigin/uAssets/assets/161650745/4314ddc2-fc66-429f-821e-6e53e37de212)

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125083
 cosmetic: 45583
 scriptlet: 18926
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37627-114, 49m Δ
  ublock-badware: 7862-14, 49m Δ
  ublock-privacy: 750-0, 49m Δ
  ublock-unbreak: 2301-0, 49m Δ
  easylist: 82283-632, 49m Δ
  easyprivacy: 50358-861, 49m Δ
  plowe-0: 3772-1, now
  urlhaus-1: 8015-5, 1h.31m
  ublock-quick-fixes: 146-2, 49m Δ
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  alpin.de: 5
  aticdn.net: 1
  cxense.com: 1
  iocnt.net: 2
  npttech.com: 1
  pinpoll.com: 2
  storage.googleapis.com: 1
  taboola.com: 2
  usercentrics.eu: 1
  vgwort.de: 1
 extended:
  ##.ad-rectangle
  ##.ad-sky
  ###taboola-mid-article-thumbnails
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 Adguard ping (if you can’t reproduce scroll down and click on a new article or test on chrome).

I reported the placeholder to EL germany already.

I also see CNAME requests https://github.com/AdguardTeam/cname-trackers/issues/93
