### ISSUE TITLE
douyin.com: ads

### ISSUE THREAD

**Issue by marswow** [uBlockOrigin/uAssets#22889]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.douyin.com/`

### Description

文字类、小气泡类的ads。
这种很难去除掉，因为是通过鼠标移动到 通知、私信这两个选项才会自动弹出下拉菜单，而且通过右键无法屏蔽

[Text-based and small-bubble ads. This is difficult to remove because the drop-down menu will automatically pop up when you move the mouse to the notification and private message options, and it cannot be blocked by right-clicking.]

我用chrome元素查看器将想屏蔽的部分复制了出来
[I used the chrome element viewer to copy the elements I wanted to block.]

1.
```html
<div class="YLK1Proo fBUGquc7"><div class="nUbceE5V"><div class="aPyHfyKJ">下载客户端，随时接收消息</div><a href="https://www.douyin.com/download/pc/obj/douyin-pc-client/7044145585217083655/releases/11634728/3.5.1/win32-ia32/douyin-downloader-v3.5.1-win32-ia32-douyinDownload1.exe" download="douyin-downloader-v3.5.1-win32-ia32-douyinDownload1-wid-8KbbUG2t7PW.exe" class="WyzLi5rI"><svg width="14" height="14" fill="none" xmlns="http://www.w3.org/2000/svg" class="XY6_uMiT" viewBox="0 0 14 14"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.646 7.146L8 9.793V2.5H7v7.293L4.354 7.146l-.708.708 3.5 3.5.354.353.354-.353 3.5-3.5-.708-.708zM3 12.5v1h9v-1H3z" fill="#fff" stroke="#fff" stroke-width="0.5"></path></svg><span>下载</span></a></div></div>
```

2.
```html
<div class="YLK1Proo wZsfSQtZ"><div class="nUbceE5V"><div class="aPyHfyKJ">下载客户端，随时接收消息</div><a href="https://www.douyin.com/download/pc/obj/douyin-pc-client/7044145585217083655/releases/11634728/3.5.1/win32-ia32/douyin-downloader-v3.5.1-win32-ia32-douyinDownload1.exe" download="douyin-downloader-v3.5.1-win32-ia32-douyinDownload1-wid-8KbbUG2t7PW.exe" class="WyzLi5rI"><svg width="14" height="14" fill="none" xmlns="http://www.w3.org/2000/svg" class="XY6_uMiT" viewBox="0 0 14 14"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.646 7.146L8 9.793V2.5H7v7.293L4.354 7.146l-.708.708 3.5 3.5.354.353.354-.353 3.5-3.5-.708-.708zM3 12.5v1h9v-1H3z" fill="#fff" stroke="#fff" stroke-width="0.5"></path></svg><span>下载</span></a></div></div>
```

3.
```html
<div class="hb6kxNSJ _hzzu8wn"><a href="https://api.amemv.com/magic/eco/runtime/release/6461f944e84c15036369f2a8" class="hY8lWHgA c5weHswV" target="_blank" rel="noopener nofollow noreferrer" data-e2e="alink-item"><span class="zNOCwzeP">剪映专业版</span><svg width="29" height="12" fill="none" xmlns="http://www.w3.org/2000/svg" class="B5yDXM_S" viewBox="0 0 29 12" style="top: 17px; right: 29px;"><rect width="29" height="12" rx="6" fill="#FE2C55"></rect><path d="M4.967 9.341h1.27V5.285h.07l2.936 4.056h1.099V3h-1.27v4.039h-.07L6.074 3H4.967v6.341zM11.384 9.341h4.201V8.247h-2.874V6.643h2.712v-1.02H12.71V4.095h2.874V3h-4.2v6.341zM17.78 9.341h1.252l1.186-4.271h.07l1.2 4.271h1.244L24.415 3h-1.371l-.98 4.53h-.07L20.816 3h-1.12L18.54 7.53h-.07L17.48 3H16.1l1.68 6.341z" fill="#fff"></path></svg></a><div class="Y7z0XV7g"></div></div>
```

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

这张是我想屏蔽的部分
[This is the part I want to block]

![屏幕截图 2024-03-13 125125](https://github.com/uBlockOrigin/uAssets/assets/13765982/dc587d16-dcd9-4b57-8a02-56804d764c55)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 139903
 cosmetic: 56345
 scriptlet: 20492
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 251-5, never
  CHN-0: 25579-129, now
  easylist: 82225-36, now
  easyprivacy: 50358-21, now
  plowe-0: 3772-1186, now
  ublock-badware: 7858-147, now
  ublock-filters: 37490-375, now
  ublock-privacy: 756-6, now
  ublock-quick-fixes: 150-4, now
  ublock-unbreak: 2244-36, now
  urlhaus-1: 8160-5, now
filterset (user): [array of 251 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 274 ms (selfie)
 maxAssetCacheWait: 158 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 64
 network:
  byteimg.com: 22
  zijieapi.com: 42
 extended:
  ##.wobrT4EE > .RQFWObp0 > .iqAeEhI1 > div
  ##.QCAc0UCH.i4p_LDeX > .RQFWObp0
  ##div.iqAeEhI1:nth-of-type(3)
  ##.BiTcKW5v
  ##.anFLc8TW.MlLk82IS
  ##.QCAc0UCH.i4p_LDeX > .dy-tip-container.wobrT4EE
  ##._wBqqeOM
```
</details>

**Comment by ItsProfessional** [comment]
@cjx82630 Sorry, can you check this?

**Comment by gorhill** [comment]
uBO uses AdGuard Chinese, not EasyList China because it doesn't make use of advanced filtering syntax. This should be looked into by whoever maintains AdGuard Chinese.

**Comment by cjx82630** [comment]
@marswow "剪影" belongs to douyin.com, so the ads you mentioned are annoying self-promotion to some users, and won't be listed in Easylist China which only focus on ads.

**Comment by Alex-302** [comment]
I don't understand which elements mentioned.
Please add more clear description with screenshots.
