### ISSUE TITLE
hotcopper.com.au: breakage

### ISSUE THREAD

**Issue by bevter** [uBlockOrigin/uAssets#22886]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hotcopper.com.au/`

### Category

breakage

### Description

This is all I get since yesterday and it was working fine prior. I can get the site with Chrome no issues.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125083
 cosmetic: 45583
 scriptlet: 18926
 html: 1741
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37627-114, 24m Δ
  ublock-badware: 7862-14, 24m Δ
  ublock-privacy: 750-0, 24m Δ
  ublock-unbreak: 2301-2, 24m Δ
  ublock-quick-fixes: 146-0, 24m Δ
  easylist: 82283-632, 24m Δ
  easyprivacy: 50358-861, 24m Δ
  urlhaus-1: 8015-5, now
  plowe-0: 3772-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8579 ms (selfie)
 maxAssetCacheWait: 2538 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(abort-current-script, $, blockAds)
```
</details>

**Comment by huyszn** [comment]
I can access the site on firefox and chrome just fine.

**Comment by bevter** [comment]
Hmmm strange. I don't know what else I can do. I get all the ads on Chrome. Thx anyway. Terry

**Comment by D4niloMR** [comment]
> - [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.

Did you follow this prerequisite?
