### ISSUE TITLE
cinemagia.ro: breakage

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#22880]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://m.cinemagia.ro/filme/kung-fu-panda-4-3293735/?show_type=cinema`

### Category

breakage

### Description

The video on the website is no longer available for playback (the player has a black screen), when I activated all the filters in all countries, the default ones. 

### Other extensions used

does not exist 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240312-151202_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/114283947/c0261ae0-0ddf-472d-91eb-4403fcf92028)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 341416
 cosmetic: 369751
 scriptlet: 54304
 html: 2096
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79097-6585, 2m
  adguard-spyware-url: 1477-106, 2m
  adguard-spyware: 113929-33651, 2m
  block-lan: 61-0, 2m
  curben-phishing: 14144-3, 1m
  adguard-social: 22262-890, 2m
  adguard-cookies: 28908-93, 2m
  ublock-cookies-adguard: 1069-0, 1m
  adguard-popup-overlays: 26778-1969, 2m
  adguard-mobile-app-banners: 5066-1083, 2m
  adguard-other-annoyances: 13926-360, 2m
  adguard-widgets: 2413-1, 2m
  [45 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37971-779, 3m
  ublock-badware: 7856-14, 3m
  ublock-privacy: 751-0, 3m
  ublock-unbreak: 2304-3, 3m
  ublock-quick-fixes: 172-1, 3m
  adguard-mobile: 9129-112, 3m
  easylist: 82160-1266, 3m
  easyprivacy: 50346-1474, 3m
  urlhaus-1: 8015-5, 3m
  plowe-0: 3772-1, 3m
  ROU-1: 1348-12, 3m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9594 ms
 maxAssetCacheWait: 572 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  agorahtag.tech: 2
  demand.supply: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  onnetwork.tv: 1
 extended:
  ##div[data-ad]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.demand-supply
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
add

```
@@||video.onnetwork.tv/embed.php$script,domain=m.cinemagia.ro
@@||cdn.onnetwork.tv/js/player90/embed.min.js$script,domain=m.cinemagia.ro
@@||video.onnetwork.tv^$frame,domain=m.cinemagia.ro
```

however, for a romanian site you don't need the russian list

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Previously, this domain was used on Ukrainian sites as an advertising server. I don't see this now.

Fix: https://github.com/easylist/ruadlist/commit/27c440b1502f223eff8c693d8292e7ade20b5955
