### ISSUE TITLE
fbox.pw: popups

### ISSUE THREAD

**Issue by blackTopHatCat** [uBlockOrigin/uAssets#22894]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fbox.pw/series/mr-robot-72498/1-1/`

### Category

popups

### Description

Popups upon clicking video player.

### Other extensions used

FastForward
Search by Image
Buster: Captcha Solver for Humans
Web Archives
Medium parser

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 143448
 cosmetic: 46932
 scriptlet: 20374
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37661-119, 41m Δ
  ublock-badware: 7862-14, 41m Δ
  ublock-privacy: 752-0, 41m Δ
  ublock-unbreak: 2301-3, 41m Δ
  ublock-quick-fixes: 147-0, 41m Δ
  easylist: 82223-639, 41m Δ
  adguard-spyware-url: 1477-106, now
  easyprivacy: 50358-867, 41m Δ
  urlhaus-1: 8125-0, now
  curben-phishing: 14151-2, now
  plowe-0: 3772-1, now
  LegitimateURLShortener: 2611-167, now
  bpc-paywall-filter: 1048-0, now
  AntiPaywall: 2092-15, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 130 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  ditlastedallth.info: 27
  googletagmanager.com: 1
  loketsaucy.com: 1
  optimalscreen1.online: 1
  ptaupsom.com: 1
  refpamjeql.top: 1
  terabigyellowmotha.info: 3
 extended:
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by D4niloMR** [comment]
Fixed. https://github.com/uBlockOrigin/uAssets/commit/bf385513634597f84ed0aec2f73ab8e214f6e567

[Click here](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1) to update the filters.
