### ISSUE TITLE
zimbra-freefr8.godaddysites.com: detection

### ISSUE THREAD

**Issue by orbotimn75** [uBlockOrigin/uAssets#22893]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://zimbra-freefr8.godaddysites.com/`

### Category

detection

### Description

This site is a phishing campaign against customers using Free Webmail.
The legitimate page can be found at : https://zimbra.free.fr/ or https://webmail.free.fr/

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 140686
 cosmetic: 52342
 scriptlet: 19086
 html: 1742
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 147-2, 18m Δ
 default:
  user-filters: 18-0, never
  ublock-filters: 37661-182, 18m Δ
  ublock-badware: 7862-14, 18m Δ
  ublock-privacy: 752-0, 18m Δ
  ublock-unbreak: 2301-0, 18m Δ
  easylist: 82225-653, 18m Δ
  easyprivacy: 50358-1060, 18m Δ
  plowe-0: 3772-1, 1h.18m
  FRA-0: 22836-109, 1h.18m
  urlhaus-1: 8160-5, 1h.18m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 41 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1987 ms (selfie)
 maxAssetCacheWait: 1447 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  wsimg.com: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in the old thread as said here: https://github.com/uBlockOrigin/uAssets/issues/22864#issuecomment-1988454068 . It's better to manage these sites in 1 place.
