### ISSUE TITLE
waaw.tv

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#229]
Hi, 

`waaw.tv##script:contains(base64)`

to disable the script which redirection waaw.tv links to the `data:` iframe.

`http://waaw.tv/watch_video.php?v=Qq3t3kLIXtbO`

Thank you.

**Comment by gorhill** [comment]
What is a URL where I can check myself the issue, and what do I need to do to make the issue appear? A solution which work for all browsers would be preferable.

**Comment by SMed79** [comment]
already give an example url: 
`http://waaw.tv/watch_video.php?v=Qq3t3kLIXtbO` redirect to 
```
data:text/html;charset=utf-8;base64,PGlmcmFtZSBzcmM9Imh0dHA6Ly93YWF3LnR2L3dhdGNoX3ZpZGVvLnBocD92PVFxM3Qza0xJWHRiTyZkYXRhdD0xIiBzY3JvbGxpbmc9Im5vIiBmcmFtZWJvcmRlcj0iMCIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgYWxsb3dmdWxsc2NyZWVuPSJ0cnVlIiB3ZWJraXRhbGxvd2Z1bGxzY3JlZW49InRydWUiIG1vemFsbG93ZnVsbHNjcmVlbj0idHJ1ZSIgc3R5bGU9InBvc2l0aW9uOiBmaXhlZDsgdG9wOiAwcHg7IGxlZnQ6IDBweDsgd2lkdGg6IDEwMCU7IGhlaWdodDogMTAwJTsiPjwvaWZyYW1lPg==
```

http://pastebin.com/DGCUr5Zj

**Comment by ryanbr** [comment]
Interesting how the re-direct to a data:text/html; stop element hider in ABP from working
