### ISSUE TITLE
music.youtube.com: breakage

### ISSUE THREAD

**Issue by DocOcc** [uBlockOrigin/uAssets#22908]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://music.youtube.com/`

### Category

breakage

### Description

Site reloads after a video has finished and it it loading the next one, when clicking the home page, going to discovery, ect.  I believe it is an issue with the site trying to reload blocked assets and crashing itself in the process 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 260322
 cosmetic: 239255
 scriptlet: 51110
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28924-33, 21h.19m
  adguard-generic: 79143-493, 20h.59m
  adguard-mobile-app-banners: 5070-9, 21h.18m
  adguard-other-annoyances: 14014-10, 21h.18m
  adguard-popup-overlays: 26815-92, 21h.19m
  adguard-social: 22359-905, 21h.19m
  adguard-spyware: 113955-1158, 20h.59m
  adguard-spyware-url: 1478-5, 20h.59m
  adguard-widgets: 2415-5, 21h.19m
  block-lan: 61-0, 20h.59m
  curben-phishing: 14151-1, 20h.59m
  dpollock-0: 11660-214, 20h.59m
  [10 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  easylist: 82617-1728, 3h.2m Δ
  easyprivacy: 50364-32229, 3h.2m Δ
  plowe-0: 3779-1624, 7d.20h.53m
  ublock-badware: 7868-256, 3h.2m Δ
  ublock-filters: 37541-3965, 3h.2m Δ
  ublock-privacy: 763-223, 3h.2m Δ
  ublock-quick-fixes: 183-30, 3h.2m Δ
  ublock-unbreak: 2246-152, 3h.2m Δ
  urlhaus-1: 8125-0, 23h.9m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 largeMediaSize: 500
 prefetchingDisabled: false
hiddenSettings:
 autoUpdateAssetFetchPeriod: 60000
 autoUpdateDelayAfterLaunch: 60000
 autoUpdatePeriod: 0
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 7738 ms (selfie)
 maxAssetCacheWait: 683 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by DocOcc** [comment]
Does music.youtube.com classify under the no YouTube rule?  I don't know if the music site uses the same scripts and such as the normal YouTube site.

**Comment by stephenhawk8054** [comment]
Yes, continue in the main YouTube thread and follow the perquisites carefully. Don't tick them just to submit the issue.
