### ISSUE TITLE
qds.it: breakage

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#22903]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://qds.it/video-gorilla-infuriato-guardiani-paura-zoo/`

### Category

breakage

### Description

No video on my end.
Ok with
```
@@||qds.it/wp-content/plugins/digistream/digiplayer/js/videojs.ga.js$script,first-party
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=qds.it,important
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="571" alt="j" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/d5b5baf4-3e45-4855-a750-5134cae17739">

<img width="504" alt="k" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/2a4009ef-70e4-4710-ab4b-44fdf55b20a2">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 127256
 cosmetic: 53909
 scriptlet: 23498
 html: 1997
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  ublock-annoyances: 6836-11, 3m Δ
  ITA-0: 8293-19, 3m
 default:
  ublock-filters: 37696-147, 3m
  ublock-badware: 7872-14, 3m
  ublock-privacy: 759-0, 3m
  ublock-unbreak: 2301-0, 2m Δ
  ublock-quick-fixes: 187-2, 3m Δ
  easylist: 82328-643, 2m Δ
  easyprivacy: 50359-879, 3m
  urlhaus-1: 8125-0, 3m
  plowe-0: 3772-1, 2m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 992 ms
 maxAssetCacheWait: 629 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  qds.it: 1
  codesour.com: 2
  facebook.net: 1
  googletagmanager.com: 2
  imasdk.googleapis.com: 2
  wp.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
Thanks for providing the solution.

**Comment by superlex** [comment]
You're welcome 😊
