### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by bergerst** [uBlockOrigin/uAssets#22909]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.deezer.com/
```

### Description

Once you click Play, an error message with a Retry button pops up.

They changed their website today, which caused this error.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/24389548/04211bda-f16c-4599-82e4-c260d6a0d59d)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 122534
 cosmetic: 50590
 scriptlet: 18986
 html: 1742
listset (total-discarded, last-updated):
 added:
  DEU-0: 7331-3, 2m
 default:
  user-filters: 4-0, never
  ublock-filters: 37701-151, 1m
  ublock-badware: 7872-14, 1m
  ublock-privacy: 759-0, 1m
  ublock-unbreak: 2303-0, 1m
  easylist: 82632-643, 1m
  easyprivacy: 50363-870, 1m
  plowe-0: 3772-1, 1m
  urlhaus-1: 2770-1, 1m
  ublock-quick-fixes: 187-0, 1m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  about-scheme
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 907 ms
 maxAssetCacheWait: 538 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 33
 network:
  adnxs-simple.com: 8
  adswizz.com: 6
  doubleclick.net: 7
  google.com: 2
  googletagmanager.com: 1
  hubvisor.io: 7
  segment.com: 1
  sentry.io: 1
 extended:
  ##+js(no-setTimeout-if, Ads)
```
</details>

**Comment by mapx-** [comment]
I guess it's because deezer will allow only previews of 30 seconds (mp3 format) in some countries and the full songs only on premium subscriptions

`Listen to full length tracks on Deezer.com with Deezer Premium`

**Comment by mapx-** [comment]
test

```
@@||s0.2mdn.net/instream/video/client.js$script,domain=deezer.com
@@||cdn.hubvisor.io/wrapper/common/player.js$script,domain=deezer.com
@@||cdn.hubvisor.io/wrapper/*/hubvisor.js$script,domain=deezer.com
```

**Comment by bergerst** [comment]
Fixes the error, thanks.

**Comment by stephenhawk8054** [comment]
Hmm... There are some reports of ads slipped: https://www.reddit.com/r/uBlockOrigin/comments/1bfc2so/blocking_no_longer_works_on_deezer/
