### ISSUE TITLE
file-converter.org: badware

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#22907]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://file-converter.org/`

### Category

privacy

### Description

The following site is a fake version of the official File Converter software provided at https://github.com/Tichau/FileConverter
It needs to be added to the "Badware risks" list
![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/fddf5c22-95a9-4f90-af39-8e69d8e52b01)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/8550e6d5-c367-444d-8199-7fbf54c29a0a)
![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/d31f37d0-53f9-48bf-aaaa-36928cb99481)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125105
 cosmetic: 45628
 scriptlet: 18986
 html: 1742
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37701-163, 1h.12m Δ
  ublock-badware: 7872-14, 1h.12m Δ
  ublock-privacy: 759-0, 1h.12m Δ
  ublock-unbreak: 2303-0, 1h.12m Δ
  ublock-quick-fixes: 187-0, 1h.12m Δ
  easylist: 82617-635, 1h.12m Δ
  easyprivacy: 50364-833, 1h.12m Δ
  urlhaus-1: 7690-5, 12m
  plowe-0: 3772-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 362 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  plausible.io: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Where is the badware? The download has 0 VT detections https://www.virustotal.com/gui/file/3a5f51e46b9314228955b6e42ba9cf5c37566a69a2f49acb9ad0ee8c3132ba24
