### ISSUE TITLE
multitest.ua: breakage

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#22906]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://www.multitest.ua/uk/speedtest-test-skorosti-interneta/`

### Category

breakage

### Description

After clicking on the button to 'check the speed', nothing happens.

`http://www.multitest.ua/static/bower_components/boomerang/boomerang.js`

`/boomerang.js` ~> **EasyPrivacy**

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-03-14_160250](https://github.com/uBlockOrigin/uAssets/assets/111344219/c7e454ff-69ba-45ac-8980-665401a2afc0)
![2024-03-14_160250](https://github.com/uBlockOrigin/uAssets/assets/111344219/d638e514-4914-47f6-b02a-a4b7c4923eb6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.1b17
Firefox: 123
filterset (summary):
 network: 142877
 cosmetic: 68156
 scriptlet: 24902
 html: 2014
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6860-33, now
  RUS-0: 39780-138, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37705-104, now
  ublock-badware: 7882-14, now
  ublock-privacy: 759-0, now
  ublock-unbreak: 2303-2, now
  ublock-quick-fixes: 187-29, now
  easylist: 82631-255, now
  easyprivacy: 50364-57, now
  urlhaus-1: 7690-5, now
  plowe-0: 3772-1185, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 317 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  multitest.ua: 2
  facebook.net: 1
  google-analytics.com: 1
  googleadservices.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 1
  ipinfo.io: 1
  maps.googleapis.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by dportvine** [comment]
@ryanbr

**Comment by mapx-** [comment]
`@@||multitest.ua/static/bower_components/boomerang/boomerang.js$script,1p`
