### ISSUE TITLE
hurawatch.bz: detection

### ISSUE THREAD

**Issue by TuanLVT90** [uBlockOrigin/uAssets#22901]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hurawatch.bz/tv/shogun2-jw2l2/1-1`

### Category

detection

### Description

this is the first day that this was detected, before this day it worked normally

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/163357542/dd1c2fba-83a4-48a5-b0d1-59bdd8df96f8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125474
 cosmetic: 47684
 scriptlet: 20369
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FIN-0: 2281-0, now
  easylist: 82328-15, 53m Δ
  easyprivacy: 50359-8, 53m Δ
  plowe-0: 3772-1184, now
  ublock-badware: 7868-147, 53m Δ
  ublock-filters: 37536-357, 53m Δ
  ublock-privacy: 763-6, 53m Δ
  ublock-quick-fixes: 183-28, 53m Δ
  ublock-unbreak: 2244-36, 53m Δ
  urlhaus-1: 8125-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 155 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 11
 network:
  amung.us: 1
  bidgear.com: 1
  disqus.com: 1
  foolishjunction.com: 2
  googletagmanager.com: 1
  moonjscdn.info: 3
  sharethis.com: 2
 extended:
  ##+js(no-window-open-if, _blank)
  ##+js(set-cookie, __pf, 1)
  ##+js(remove-node-text, script, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
@@||moonjscdn.info/player8/JWui.js?v=2$script,domain=vpcxz19p.xyz

**Comment by BlazeFTL** [comment]
Try
```
||moonjscdn.info^$3p,badfilter

**Comment by gorhill** [comment]
This happens only for Filemoon server.

**Comment by TuanLVT90** [comment]
thx
