### ISSUE TITLE
web.businessuniqueidea.com: detection

### ISSUE THREAD

**Issue by absouini** [uBlockOrigin/uAssets#22916]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://web.businessuniqueidea.com/title-5-reasons-to-choose-an-iphone-over-android/`

### Category

detection

### Description

It seems that you are using some ad blocking software which is preventing the page from fully loading. Please whitelist this website or disable ad blocking software.

### Other extensions used

Adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![screencapture-web-businessuniqueidea-title-5-reasons-to-choose-an-iphone-over-android-2024-03-14-00_58_59](https://github.com/uBlockOrigin/uAssets/assets/92689195/7bda59c5-40e9-4c0f-a3d9-31f82abe387a)

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 140650
 cosmetic: 52338
 scriptlet: 20511
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  FRA-0: 22838-36, now
  easylist: 82651-39, now
  easyprivacy: 50365-252, now
  plowe-0: 3772-1193, now
  ublock-badware: 7848-162, now
  ublock-filters: 37521-428, now
  ublock-privacy: 763-6, now
  ublock-quick-fixes: 198-28, 1h.35m Δ
  ublock-unbreak: 2246-37, now
  urlhaus-1: 7690-5, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 10 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5032 ms (selfie)
 maxAssetCacheWait: 750 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 16
 network:
  businessuniqueidea.com: 10
  doubleclick.net: 4
  google-analytics.com: 1
  quantserve.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
That site has no content, one single "article" -- my opinion is it's not worth to bloat the list for what seems to not be a real site. If you still want to fix it, use:

    web.businessuniqueidea.com##+js(set, b2a, noopFunc)

**Comment by stephenhawk8054** [comment]
It looks like it's from a shortener link.

@absouini If you encounter it from a shortener link, please give original link

**Comment by absouini** [comment]
> It looks like it's from a shortener link.
> 
> @absouini If you encounter it from a shortener link, please give original link

https://web.businessuniqueidea.com/?go=Wqb28

**Comment by absouini** [comment]
> That site has no content, one single "article" -- my opinion is it's not worth to bloat the lists for what seems to not be a real site. If you still want to fix it, use:
> 
> ```
> web.businessuniqueidea.com##+js(set, b2a, noopFunc)
> ```

Working Fine

**Comment by absouini** [comment]
> That site has no content, one single "article" -- my opinion is it's not worth to bloat the lists for what seems to not be a real site. If you still want to fix it, use:
> 
> ```
> web.businessuniqueidea.com##+js(set, b2a, noopFunc)
> ```

Working Fine
