### ISSUE TITLE
onedio.com: nuisance

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#22914]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://onedio.com/`

### Category

nuisance

### Description

A pop up appears saying "allow notifications to be notified of contents". Although I have selected all Easylist filters, the problem is not resolved. I only get notifications in chromium browsers, not in firefox.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![onedio](https://github.com/uBlockOrigin/uAssets/assets/51531027/77aabd9f-b407-41a4-8cbc-061dc7d0b8a1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 131021
 cosmetic: 128690
 scriptlet: 30616
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4427-32, 3m
  easylist-chat: 186-0, 3m
  easylist-newsletters: 7124-14, 3m
  easylist-notifications: 2958-86, 3m
  fanboy-cookiemonster: 50350-182, 3m
  fanboy-social: 15786-15, 3m
  fanboy-thirdparty_social: 68-15, 2m
  ublock-annoyances: 6908-83, 1m Δ
  ublock-cookies-easylist: 1037-1037, 3m
 default:
  user-filters: 18-0, never
  TUR-0: 11954-15, 1m
  easylist: 82644-37, 20m Δ
  easyprivacy: 50364-97, 20m Δ
  plowe-0: 3772-1185, now
  ublock-badware: 7878-147, 20m Δ
  ublock-filters: 37521-386, 20m Δ
  ublock-privacy: 763-8, 20m Δ
  ublock-quick-fixes: 198-28, 20m Δ
  ublock-unbreak: 2246-38, 20m Δ
  urlhaus-1: 7690-5, now
filterset (user): [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 189 ms (selfie)
 maxAssetCacheWait: 111 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 14
 network:
  onedio.com: 2
  cloudflare.com: 1
  criteo.net: 2
  doubleclick.net: 3
  googletagmanager.com: 3
  imasdk.googleapis.com: 1
  taboola.com: 2
 extended:
  ##div[unit-name="masthead"]
  ###mansetAlti-container
  ###masthead-container
  ##div[id^="crt-"][style]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
onedio.com##+js(set-cookie, o-push-alert, 1)
```

@ryanbr For EasyList – Notifications
