### ISSUE TITLE
hktvmall.com: breakage

### ISSUE THREAD

**Issue by FawkesMeteor** [uBlockOrigin/uAssets#22918]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hktvmall.com/hktv/en/search_a?keyword=coke
`

### Category

breakage

### Description

URL:All the page in hktvmall.com which contains product results
Issue: the product result is blank in pages (screenshot as below).

Caused by filter list:
uBlock filters - Privacy
AdGuard URL Tracking Protection

found: 
disable the below filter line will fix the breakage.

> ||hktvmall.com/yuicombo?$script,removeparam=/^\/_ui\/desktop\/common\/js\/uiAnalytics\//

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80746970/99a451c3-3209-4a47-82b6-77c5664829e7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 213542
 cosmetic: 130865
 scriptlet: 25058
 html: 1744
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1478-107, never
  adguard-spyware: 113956-32488, 30m
  adguard-social: 22376-153, 31m
  adguard-cookies: 28927-48, 31m
  ublock-cookies-adguard: 1040-0, 31m
  adguard-popup-overlays: 26820-833, 31m
  adguard-mobile-app-banners: 5073-8, 31m
  adguard-other-annoyances: 14016-11, 31m
 default:
  user-filters: 0-0, never
  ublock-filters: 37684-489, 31m
  ublock-badware: 7852-14, 31m
  ublock-privacy: 759-2, never
  ublock-unbreak: 2305-0, 31m
  ublock-quick-fixes: 203-0, 31m
  easylist: 82656-693, 31m
  easyprivacy: 50364-895, 31m Δ
  urlhaus-1: 7840-5, 32m
  plowe-0: 3772-0, 32m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1246 ms
 maxAssetCacheWait: 8 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  hktvmall.com: 1
  facebook.net: 1
  googleadservices.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Hmm... I can't reproduce the issue
![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/eca76fc9-0050-476d-9460-6a6d46f1ba52)

**Comment by FawkesMeteor** [comment]
I had check the Logger, it shows some URL start with "https://www.hktvmall.com/yuicombo?/_ui/desktop/common/js" is blocked, but didn't match the regex "/^\/_ui\/desktop\/common\/js\/uiAnalytics\//"
Tried reinstall the uBlock with default setting. Is there any cache file might cause the issue?

**Comment by gorhill** [comment]
> some URL start with `https://www.hktvmall.com/yuicombo?/_ui/desktop/common/js` is blocked

I don't see any of those URLs being blocked on my side when using the same filter lists as shown in your troubleshooting information.

Are you logged in?

What might be happening is:

- Site makes a network request with URL like `https://www.hktvmall.com/yuicombo?/_ui/desktop/common/js/uiAnalytics/`
- _uBlock  filters -- Privacy_ or _AdGuard URL Tracking Protection_ removes the `?/_ui/desktop/common/js/uiAnalytics/` part because of the filter `||hktvmall.com/yuicombo?$script,removeparam=/^\/_ui\/desktop\/common\/js\/uiAnalytics\//` in both lists
- The resulting URL is `https://www.hktvmall.com/yuicombo`
- That URL matches the block filter `||hktvmall.com/yuicombo|$script,1p` in _uBlock  filters -- Privacy_

**Comment by stephenhawk8054** [comment]
The filter appears if I go to `https://www.hktvmall.com` first, then start to click on search banner and type to search things.

But I still can't reproduce the issue.

**Comment by dportvine** [comment]
I can reproduce.

```
https://www.hktvmall.com/hktv/en/Housewares/Kitchenware/main/search?q=%3Arelevance%3Astreet%3Amain%3Acategory%3AAA18150000000
```

<details>
<summary>Screen</summary>

![2024-03-16_093046](https://github.com/uBlockOrigin/uAssets/assets/111344219/b20b4d06-3bca-4f12-810f-b4acf2c5f4ac)
![2024-03-16_093148](https://github.com/uBlockOrigin/uAssets/assets/111344219/c17beb54-1634-4e8c-b681-14baf4ce2aee)
</details>

**Comment by stephenhawk8054** [comment]
cc @Yuki2718
