### ISSUE TITLE
deezer.com: breakage DELETE (Duplicated)

### ISSUE THREAD

**Issue by OuiKey** [uBlockOrigin/uAssets#22912]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deezer.com/`

### Category

breakage

### Description

Music dont work when uBlock is active.

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/94763043/1bd09196-d33a-4a3f-af0f-b1960138027d)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/94763043/6155ee94-0742-4974-a34d-e7dc84cb5144)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 140657
 cosmetic: 52321
 scriptlet: 19140
 html: 1744
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37675-325, 2m Δ
  ublock-badware: 7882-14, 2m Δ
  ublock-privacy: 759-0, 2m Δ
  ublock-unbreak: 2303-0, 2m Δ
  ublock-quick-fixes: 202-0, 2m Δ
  easylist: 82641-539, 2m Δ
  easyprivacy: 50364-1037, 2m Δ
  urlhaus-1: 7690-5, now
  plowe-0: 3772-1, now
  FRA-0: 22838-132, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 734 ms
 maxAssetCacheWait: 315 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  bing.com: 1
  google.com: 1
  googletagmanager.com: 1
  gstatic.com: 1
  hubvisor.io: 2
  segment.com: 1
  sentry.io: 2
  snapchat.com: 1
 extended:
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/22909
