### ISSUE TITLE
puzzle-loop.com: detection

### ISSUE THREAD

**Issue by markhamnr** [uBlockOrigin/uAssets#22928]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.puzzle-loop.com/`

### Category

detection

### Description

Site shows a dialog with "It seems that you may be using an ad blocking software."

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125164
 cosmetic: 45556
 scriptlet: 18934
 html: 1746
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37682-134, 24m Δ
  ublock-badware: 7852-14, 24m Δ
  ublock-privacy: 759-0, 24m Δ
  ublock-unbreak: 2309-0, 24m Δ
  easylist: 82657-633, 24m Δ
  easyprivacy: 50369-832, 24m Δ
  plowe-0: 3765-1, now
  urlhaus-1: 7770-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 48 redacted]
 removed:
  about-scheme
  edge-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 174 ms (selfie)
 maxAssetCacheWait: 88 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  a-mo.net: 1
  adnxs.com: 1
  criteo.com: 1
  dotomi.com: 1
  doubleclick.net: 1
  e-planning.net: 1
  googletagmanager.com: 1
  lijit.com: 1
  s-onetag.com: 2
 extended:
  ###MainContainer > [id^="bannerTopSpacer"]
  ###MainContainer + [id]:has(> #bannerSide)
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances`
