### ISSUE TITLE
[nsfw] imagereviser.com: detection

### ISSUE THREAD

**Issue by SarvanshRaj** [uBlockOrigin/uAssets#22929]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://imagereviser.com/new-york-city-construction-accident-lawyer/`

### Category

detection

### Description

Detects adblock

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium Mobile: 124
filterset (summary):
 network: 126597
 cosmetic: 37493
 scriptlet: 20457
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 3h.37m
 default:
  user-filters: 0-0, never
  adguard-mobile: 9144-47, now
  easylist: 82657-15804, 6m Δ
  easyprivacy: 50369-18, 6m Δ
  plowe-0: 3765-1258, now
  ublock-badware: 7842-148, 6m Δ
  ublock-filters: 37876-596, 6m Δ
  ublock-privacy: 763-7, 6m Δ
  ublock-quick-fixes: 199-28, 1h.58m Δ
  ublock-unbreak: 2257-36, 6m Δ
  urlhaus-1: 7770-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5688 ms
 maxAssetCacheWait: 1327 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 2
  purdasseer.com: 1
  wp.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link?

**Comment by SarvanshRaj** [comment]
Yes
