### ISSUE TITLE
tumblr.com: breakage

### ISSUE THREAD

**Issue by Mikaill** [uBlockOrigin/uAssets#22926]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tumblr.com/markrosewater`

### Category

breakage

### Description

There is a button on the page "Question Mark" that causes a redirect to "`https://www.tumblr.com/new/ask/markrosewater`" showing a pop-up form element, where user can submit a question to the blogger. With UBO enabled, the pop-up does not show.

### Other extensions used

I have verified that the issue is caused by UBO and only UBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 126661
 cosmetic: 54042
 scriptlet: 19229
 html: 1757
listset (total-discarded, last-updated):
 added:
  POL-0: 8707-28, 7m
  POL-2: 1283-12, 7m
 default:
  user-filters: 230-2, never
  ublock-filters: 37682-203, 7m
  ublock-badware: 7852-14, 7m
  ublock-privacy: 759-0, 7m
  ublock-unbreak: 2309-0, 7m
  ublock-quick-fixes: 203-0, 7m
  easylist: 82657-648, 7m
  easyprivacy: 50369-832, 7m
  urlhaus-1: 7770-0, 7m
  plowe-0: 3765-1, 7m
filterset (user): [array of 230 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  about-scheme
hostRuleset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16263 ms (selfie)
 maxAssetCacheWait: 2436 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  tumblr.com: 5
  doubleclick.net: 1
  pubmatic.com: 1
  wp.com: 5
 extended:
  ##.Yc2Sp h1, .Yc2Sp a:style(font-size: 0 !important;)
  #@#.Qrht9
  #@#.Yc2Sp
```
</details>

**Comment by mapx-** [comment]
> user-filters: 230-2

disable / remove all your custom filters for `tumblr` and test again
