### ISSUE TITLE
tiktokcounter.net: detection

### ISSUE THREAD

**Issue by fam007e** [uBlockOrigin/uAssets#22924]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokcounter.net/tech/how-to-choose-the-right-lawyer/`

### Category

detection

### Description

The UBlock adblock is detected by the website hence link generation cannot be accessed. It is actually a website related to psarips website where you get the link by going through 4 such website mentioned about. Tried without general brave browser protection and without it with only UBlock so UBlock can't seem to subvert this advertisement forcing.

### Other extensions used

General brave browser protection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_withonlyUBlockactive_braveprotdeactivated](https://github.com/uBlockOrigin/uAssets/assets/19180457/53e4187d-61e2-4b1b-addd-9bbf542019fd)
![Screenshot_withoutanyblocker_nonactiveBraveprot](https://github.com/uBlockOrigin/uAssets/assets/19180457/ed799976-bdd5-495a-8d9a-ed914a4aeb77)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 125208
 cosmetic: 45613
 scriptlet: 20393
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82657-16, now
  easyprivacy: 50369-8, now
  plowe-0: 3765-1183, now
  ublock-badware: 7848-147, now
  ublock-filters: 37521-355, now
  ublock-privacy: 763-6, now
  ublock-quick-fixes: 199-28, now
  ublock-unbreak: 2251-33, now
  urlhaus-1: 7770-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 1
  googletagmanager.com: 2
  profitsfly.com: 2
 extended:
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
  ##+js(abort-on-stack-trace, Promise.all, injectedScript)
  ##+js(no-setTimeout-if, /function.*?\{.*?const.*?0x.*?window\[.*…
  ##+js(no-setTimeout-if, ();}, 2000)
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues?q=tiktokcounter.net
