### ISSUE TITLE
webnovel.com: nuisance

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#22937]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.webnovel.com/comic/solo-leveling(only-i-level-up)_15227640605485101
```

### Description

Site displays popup every time it is refreshed. This popup is not necessary for site's functionality.

[nsfw] https://www.webnovel.com/comic/solo-leveling(only-i-level-up)_15227640605485101/000-only-i-level-up_45196186038101142
Here the story can't be read (placeholder images displayed) unless the popup is interacted with so using only cosmetic filters causes breakage.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-16 170433](https://github.com/uBlockOrigin/uAssets/assets/43014154/108e26e0-f2bb-4d3a-b04a-10442cdce3a8)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 139679
 cosmetic: 95316
 scriptlet: 27664
 html: 2005
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  curben-phishing: 14020-1, 3h.18m
  easylist-annoyances: 4429-19, 16m
  fanboy-cookiemonster: 66358-16156, 16m
  ublock-cookies-easylist: 1044-0, 16m
  ublock-annoyances: 6860-1069, 16m
 default:
  user-filters: 4-0, never
  ublock-filters: 37720-151, 16m
  ublock-badware: 7852-14, 16m Δ
  ublock-privacy: 758-0, 16m
  ublock-unbreak: 2308-0, 16m
  ublock-quick-fixes: 205-0, 16m
  easylist: 82700-284, 1h.17m Δ
  easyprivacy: 50376-112, 1h.17m Δ
  urlhaus-1: 7925-5, 3h.17m
filterset (user): [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 499 ms (selfie)
 maxAssetCacheWait: 268 ms
 cacheBackend: indexedDB

```
</details>

**Comment by ItsProfessional** [comment]
I'm pretty sure that this is out of scope of the annoyance list.


You can use these filters locally:
```adb
webnovel.com##.m-preference-mod
webnovel.com##html:style(overflow: revert !important;)
```

Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes
