### ISSUE TITLE
devuploads.com: detection

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#22934]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://devuploads.com/nhk26jo6uzsf
```

### Description

The https://devuploads.com/ detects uBO on firefox.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80951522/82ef1e48-4189-4e85-93fa-31ce9332c309)

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 125366
 cosmetic: 45656
 scriptlet: 19023
 html: 1747
listset (total-discarded, last-updated):
 default:
  user-filters: 25-0, never
  ublock-filters: 37719-135, 1h Δ
  ublock-badware: 7852-14, 1h Δ
  ublock-privacy: 759-0, 1h Δ
  ublock-unbreak: 2308-0, 1h Δ
  ublock-quick-fixes: 203-0, 1h Δ
  easylist: 82665-628, 1h Δ
  easyprivacy: 50372-865, 1h Δ
  urlhaus-1: 7925-5, 10m
  plowe-0: 3765-1, 10m
filterset (user): [array of 21 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1096 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0

</details>

**Comment by BlazeFTL** [comment]
Works For Me In 2nd Try
Their Adblock Script Is Buggy...
