### ISSUE TITLE
healthline.com: ads

### ISSUE THREAD

**Issue by colleirose** [uBlockOrigin/uAssets#22933]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.healthline.com/nutrition/10-reasons-you-are-tired`

### Category

ads

### Description

Ad at the top:
![image](https://github.com/uBlockOrigin/uAssets/assets/147954091/fb9d7d75-3419-4c43-9daf-dced69d15f13)

### Other extensions used

Privacy Badger
Wappalyzer
Tampermonkey
Return YouTube Dislike
Indie Wiki Buddy
SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 136611
 cosmetic: 200282
 scriptlet: 32014
 html: 2003
listset (total-discarded, last-updated):
 added:
  adguard-social: 22669-859, now
  adguard-cookies: 28939-71, now
  ublock-cookies-adguard: 1044-0, now
  adguard-popup-overlays: 26845-1683, now
  adguard-mobile-app-banners: 5078-8, now
  adguard-other-annoyances: 14041-285, now
  adguard-widgets: 2418-1, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4431-124, now
  easylist-chat: 186-15, now
  fanboy-cookiemonster: 50367-3900, now
  ublock-cookies-easylist: 1044-1044, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37719-398, now
  ublock-badware: 7852-14, now
  ublock-privacy: 759-0, now
  ublock-unbreak: 2308-0, now
  ublock-quick-fixes: 203-0, now Δ
  easylist: 82674-719, now
  easyprivacy: 50372-994, now
  urlhaus-1: 7925-5, now
  plowe-0: 3765-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 451 ms (selfie)
 maxAssetCacheWait: 274 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  healthline.com: 5
  adspsp.com: 1
  adsrvr.org: 1
  amazon-adsystem.com: 1
  cookielaw.org: 4
  doubleclick.net: 3
  doubleverify.com: 1
  ensighten.com: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 6
  pinimg.com: 1
  pinterest.com: 1
  qualtrics.com: 1
  rlcdn.com: 1
  sail-horizon.com: 1
  scorecardresearch.com: 1
  sentry-cdn.com: 1
  youtube.com: 3
 extended:
  ##.button-wrapper
  ##div[data-testid="share-tools"]
  ###modal-host
  ##.css-12efcmn
  ##.css-20w1gi
  ##[data-empty]
  ##[data-testid="driver"]
  ##[data-testid="header-leaderboard"]
  ##hl-newsletter-cta
  ##a[href^="https://share.flipboard.com/bookmarklet/popout?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.pinterest.com/pin/create/button/"]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="https://share.flipboard.com/bookmarklet/"]
  ##a[title="Share on Facebook"]
  ##a[title="Share on Pinterest"]
  ##a[title="Share on Twitter"]
  ##[data-adbridg-ad-class]
  ##[data-dynamic-ads]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##aside:has(div:matches-css-before(content:/ADVERTISEMENT/))
  ##div[data-empty^="true"]:matches-css-before(content:/ADVERTISEM…
  ##[class*="css"]:matches-css-before(content:/ADVERTISEMENT/)
  ##body:style(overflow: visible !important;)
  ##body:style(overflow: auto !important; position: initial !impor…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by dportvine** [comment]
`healthline.com##[data-event^="Sponsored"]` ?

**Comment by ghost** [comment]
I have ad leftovers on Edge Mobile and uBO Lite. I also tried Complete mode but they don't disappear.
https://github.com/user-attachments/assets/61bb6f80-75ce-42db-97b1-73f8ef6636d5

<details>

```yaml
name: uBlock Origin Lite
version: 2025.812.1339
browser: Chrome Mobile 139 (android)
filtering:
 site: optimal
 default: optimal
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 adguard-mobile
 annoyances-cookies
 rou-1
```


</details>

**Comment by mapx-** [comment]
```adb
healthline.com##article > [class] > [class^="css"]:has([data-ad="true"])
```

**Comment by ghost** [comment]
I can't add it into uBO Lite, it doesn't support custom filters.
