### ISSUE TITLE
magesy.blog: detection

### ISSUE THREAD

**Issue by Fauxvert** [uBlockOrigin/uAssets#22930]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.magesy.blog/`

### Category

detection

### Description

![mgsty](https://github.com/uBlockOrigin/uAssets/assets/107963400/47faeb3e-b3f0-4eec-8703-1cc81fb5fa96)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 140866
 cosmetic: 52403
 scriptlet: 19161
 html: 1747
listset (total-discarded, last-updated):
 default:
  user-filters: 52-1, never
  ublock-filters: 37719-234, now
  ublock-badware: 7852-14, now
  ublock-privacy: 759-0, now
  ublock-unbreak: 2308-0, now
  easylist: 82665-674, now
  easyprivacy: 50372-832, now
  plowe-0: 3765-1, now
  FRA-0: 22987-308, now
  urlhaus-1: 7770-0, now
  ublock-quick-fixes: 203-0, now
filterset (user): [array of 52 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 735 ms (selfie)
 maxAssetCacheWait: 307 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  magesy.blog: 1
  doubleclick.net: 1
  ezodn.com: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  media.net: 1
  quantserve.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(noeval-if, blocker)
  ##+js(no-setTimeout-if, Blocked)
  ##+js(no-setTimeout-if, AdBlocker)
  ##+js(prevent-fetch, adsbygoogle)
  ##+js(abort-on-stack-trace, document.getElementById, adsBlocked)
  ##+js(abort-current-script, document.createElement, admiral)
```
</details>

**Comment by x-R0b0T-x** [comment]
https://www.magesy.blog/plugins-vst/vocalsynth-v2-7-0-aax-vst3-vst2-x64-win-ce-v-r/

https://github.com/user-attachments/assets/f23dd154-19bf-4e69-b8b0-5267ac834a27" />
