### ISSUE TITLE
todopolicia.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2294]
URL(s) where the issue occurs

`http://www.todopolicia.com/foro/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by PIZZA90** [comment]
`https://www.todopolicia.com/foro/`

![aa](https://user-images.githubusercontent.com/33556647/124350602-c4ca6100-dbf5-11eb-8565-96397cfa5ad9.PNG)

**Comment by PIZZA90** [comment]
one way:
`todopolicia.com##div[style="background: rgba(0, 0, 0, 0.4); display: block;"]`
