### ISSUE TITLE
instander.me: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#22945]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://instander.me/veterans-guide-to-va-loans-benefits-and-how-to-qualify/`

### Category

nuisance

### Description

Countdown stops if the tab is not in focus. Also, would be nice to skip countdown if possible

If link above doesn't work, try this link that redirects to `instander.me`
`https://gplinks.co/VPhoneGaGaGoldV360`

### Other extensions used

Nope

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126341
 cosmetic: 47907
 scriptlet: 20427
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  NOR-0: 3921-3, now
  easylist: 82082-16, 5d.13h.39m Δ
  easyprivacy: 50347-9, 5d.13h.39m Δ
  plowe-0: 3765-1184, now
  ublock-badware: 7848-146, now
  ublock-filters: 37550-355, now
  ublock-privacy: 754-6, 5d.13h.39m Δ
  ublock-quick-fixes: 201-28, now Δ
  ublock-unbreak: 2250-33, now
  urlhaus-1: 7890-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 163 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  digislots.in: 2
  doubleclick.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 4
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by ItsProfessional** [comment]
The countdown has also been fixed.
