### ISSUE TITLE
client.falixnodes.net: detection

### ISSUE THREAD

**Issue by Oqarshi** [uBlockOrigin/uAssets#22946]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://client.falixnodes.net/`

### Category

detection

### Description

When you register on falixnodes.net and log inublock origin gets detected, the website will notice it and automatically send you 
 https://client.falixnodes.net/disableadblock
 
 Note: The adblock detector does not show when you have not registered as when you try to go to https://client.falixnodes.net/
 it will tell you to sign up.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/f49c3b0e-df6f-4a6a-af3f-cb4e7d524c2f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 136595
 cosmetic: 200395
 scriptlet: 33641
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28939-33, now
  adguard-mobile-app-banners: 5078-8, now
  adguard-other-annoyances: 14042-10, now
  adguard-popup-overlays: 26846-83, now
  adguard-social: 22669-903, now
  adguard-widgets: 2418-3, now
  easylist-annoyances: 4434-249, now
  easylist-chat: 186-15, now
  easylist-newsletters: 7127-496, now
  easylist-notifications: 2961-1469, now
  fanboy-cookiemonster: 50376-3859, now
  fanboy-social: 15791-744, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 82700-75, 58m Δ
  easyprivacy: 50376-121, 58m Δ
  plowe-0: 3765-1184, now
  ublock-badware: 7848-147, 58m Δ
  ublock-filters: 37558-694, 58m Δ
  ublock-privacy: 763-8, now
  ublock-quick-fixes: 201-38, 58m Δ
  ublock-unbreak: 2251-37, 58m Δ
  urlhaus-1: 7890-0, 58m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1243 ms (selfie)
 maxAssetCacheWait: 376 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  falixnodes.net: 4
  cloudflareinsights.com: 4
```
</details>

**Comment by Oqarshi** [comment]
Works now thanks👍

**Comment by lostnt1** [comment]
Again @JobcenterTycoon 
![Screenshot_20240513_063001_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/136184400/6c6fcaff-fd16-4fd2-aa44-48933793b22e)
