### ISSUE TITLE
instander.me: detection

### ISSUE THREAD

**Issue by adam999000** [uBlockOrigin/uAssets#22941]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://instander.me/crafting-your-financial-plan-balancing-loans-mortgages-and-insurance/`

### Category

detection

### Description

Pls fix it

### Other extensions used

No idon't use 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-03-16-20-55-52-584_org mozilla firefox](https://github.com/uBlockOrigin/uAssets/assets/81935664/13e33a01-d10a-4ad6-a09d-be8fe39feb93)

</details>
![Screenshot_2024-03-16-20-55-52-584_org mozilla firefox](https://github.com/uBlockOrigin/uAssets/assets/81935664/60dfed1a-8d21-410e-bca5-bef9fe2fb299)

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 117
filterset (summary):
 network: 126739
 cosmetic: 37483
 scriptlet: 19073
 html: 1745
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38051-376, 2m
  ublock-badware: 7846-14, 2m
  ublock-privacy: 759-1, 2m
  ublock-unbreak: 2313-1, 2m
  ublock-quick-fixes: 205-0, 2m
  adguard-mobile: 9142-133, 2m
  easylist: 82657-16416, 2m
  easyprivacy: 50376-869, 2m
  urlhaus-1: 7890-0, 2m
  plowe-0: 3765-1, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3553 ms
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  digislots.in: 2
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed.
