### ISSUE TITLE
client.falixnodes.net: detection

### ISSUE THREAD

**Issue by BussyBakks** [uBlockOrigin/uAssets#22949]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://client.falixnodes.net/`

### Category

detection

### Description

website detect ublock

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/108082159/58829033-00e4-4fda-9ea6-cade9570f93d)
(this picture captured in chrome://newtab)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/108082159/74f084ab-fa1c-473e-b417-9b3083339569)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 125057
 cosmetic: 45662
 scriptlet: 20409
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 82711-16, 15m
  easyprivacy: 50369-8, 15m
  plowe-0: 3765-1183, 15m
  ublock-badware: 7848-147, 16m
  ublock-filters: 37558-356, 16m
  ublock-privacy: 763-6, 16m
  ublock-quick-fixes: 197-28, 16m
  ublock-unbreak: 2250-33, 16m
  urlhaus-1: 7600-5, 16m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3836 ms
 maxAssetCacheWait: 19 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  cloudflareinsights.com: 1
```
</details>

**Comment by dportvine** [comment]
>I verified that this issue is not a duplicate.

https://github.com/uBlockOrigin/uAssets/issues/22946
