### ISSUE TITLE
deezer.com: nuisance

### ISSUE THREAD

**Issue by Quinss271** [uBlockOrigin/uAssets#22940]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deezer.com/ru/`

### Category

nuisance

### Description

Popup on free plan, without sub. showing pop-up window with offer to subscribe

### Other extensions used

VideoDownload helper
Dark reader
Tampermonkey
Sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/22166165/9f02a472-b199-42c3-bfbf-05e200a578d4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 241747
 cosmetic: 140613
 scriptlet: 31458
 html: 0
listset (total-discarded, last-updated):
 added:
  https://hg.adblockplus.org/antiadblockfilters/raw-file/tip/antiadblockfilters/antiadblock_russian.txt: 441-1, now
  adguard-spyware: 113967-204, now
  block-lan: 61-0, now
  curben-phishing: 14098-2, now
  easylist-annoyances: 4434-54, now
  easylist-chat: 186-1, now
  easylist-newsletters: 7127-16, now
  easylist-notifications: 2961-113, now
  fanboy-cookiemonster: 50376-199, now
  fanboy-social: 15791-16, now
  ublock-annoyances: 6915-85, 1h.11m Δ
  ublock-cookies-easylist: 1046-1046, now
 default:
  user-filters: 57-0, never
  RUS-0: 39665-449, 1h.11m Δ
  easylist: 82700-78, 1h.11m Δ
  easyprivacy: 50376-32132, 1h.11m Δ
  plowe-0: 3765-1262, now
  ublock-badware: 7848-148, 1h.11m Δ
  ublock-filters: 37557-434, 1h.11m Δ
  ublock-privacy: 762-123, 1h.11m Δ
  ublock-quick-fixes: 201-32, 1h.11m Δ
  ublock-unbreak: 2251-87, 1h.11m Δ
  urlhaus-1: 7890-0, now
filterset (user): [array of 57 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 104 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 666 ms (selfie)
 maxAssetCacheWait: 292 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 8
 network:
  dzcdn.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  segment.com: 1
  sentry.io: 4
 extended:
  ##+js(abort-on-property-read, onbeforeunload)
  ##+js(no-setTimeout-if, bait)
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)
```
</details>

**Comment by ItsProfessional** [comment]
Self promotion.

**Comment by awsms** [comment]
> Self promotion.

This comes up at every single page refresh..

**Comment by ItsProfessional** [comment]
Use a custom filter in My Filters.

**Comment by goodstuff626** [comment]
> Use a custom filter in My Filters.

I am having this same problem with deezer.com. What custom filter do I need to fix this problem? Why do I need a custom filter to block the ad instead of ublock origin default filters fixing the problem and blocking the ad?

**Comment by ItsProfessional** [comment]
> What custom filter do I need to fix this problem?
I don't use deezer and don't have a deezer account, so I can't help with that. Maybe another volunteer will suggest a filter here.

> Why do I need a custom filter to block the ad instead of ublock origin default filters fixing the problem and blocking the ad?

These are not ads. These are self promotions.

We follow the [EasyList policy](https://easylist.to/pages/policy.html), as to what is to be fixed in the lists (e.g. ads, trackers, etc.).

By this policy, ads on sites which are self promotions, i.e. what is being advertised belongs to the site itself (not a third party), are not considered as "ads" and thus not fixed in the lists.

And I think it's a good policy, otherwise we would block all links of a website, because they are technically "ads" to their own site.

**Comment by stephenhawk8054** [comment]
@goodstuff626 Test these filters

```adb
deezer.com##.chakra-portal:has(> [data-focus-lock-disabled] > .chakra-modal__content-container .chakra-button[href^="https://www.deezer.com/payment/go.php?origin=paywall_pressure"])
deezer.com##body.force-scrollbar:style(overflow-y: scroll !important;)
deezer.com##+js(aeld, test, undefined)
```

Deezer deliberately circumvents our filters if we put it to the lists, so you can use them yourselves.

**Comment by mapx-** [comment]
or use

`deezer.com##+js(trusted-click-element, button[aria-label="Close"])`

**Comment by awsms** [comment]
Does Deezer work without any problem for you all?
![Screenshot from 2024-04-06 15-07-59](https://github.com/uBlockOrigin/uAssets/assets/48278661/042c394b-18a5-49d0-9de4-cb7393d9da8e)

Getting this when playing a track (stock setup, I'm not using any filters etc.), can play after hard refreshing the page a couple of times.
Waiting for a bit of feedback before opening a new issue

**Comment by goodstuff626** [comment]
> @goodstuff626 Test these filters
> 
> ```
> deezer.com##.chakra-portal:has(> [data-focus-lock-disabled] > .chakra-modal__content-container .chakra-button[href^="https://www.deezer.com/payment/go.php?origin=paywall_pressure"])
> deezer.com##body.force-scrollbar:style(overflow-y: scroll !important;)
> deezer.com##+js(aeld, test, undefined)
> ```
> 
> Deezer deliberately circumvents our filters if we put it to the lists, so you can use them yourselves.

This works good. Thank you very much.
