### ISSUE TITLE
kuponuna183.top: ads

### ISSUE THREAD

**Issue by skollroff** [uBlockOrigin/uAssets#22953]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kuponuna183.top/`

### Category

ads

### Description

cant blocking ads

### Other extensions used

bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 225187
 cosmetic: 94826
 scriptlet: 39270
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79903-500, now
  adguard-spyware: 113967-1135, now
  adguard-spyware-url: 1478-5, now
  block-lan: 61-0, now
 default:
  user-filters: 0-0, never
  TUR-0: 11963-15, now
  easylist: 82722-1466, 1h.48m Δ
  easyprivacy: 50381-32093, 1h.48m Δ
  plowe-0: 3765-1267, now
  ublock-badware: 7848-254, 1h.48m Δ
  ublock-filters: 37454-3644, 1h.48m Δ
  ublock-privacy: 763-221, 1h.48m Δ
  ublock-quick-fixes: 208-39, 1h.48m Δ
  ublock-unbreak: 2251-149, 1h.48m Δ
  urlhaus-1: 7635-5, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 539 ms (selfie)
 maxAssetCacheWait: 261 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  google-analytics.com: 2
  googletagmanager.com: 2
  kxcdn.com: 1
  srvd2204.com: 1
 extended:
  ##.AdSense
  ##+js(no-xhr-if, /advert.js)
  ##+js(no-setTimeout-if, $('body').empty().append)
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by skollroff** [comment]
İn Türkiye

18 Mar 2024 Pzt 05:52 tarihinde stephenhawk8054 ***@***.***>
şunu yazdı:
