### ISSUE TITLE
rustica.fr: detection

### ISSUE THREAD

**Issue by GigAnon** [uBlockOrigin/uAssets#22958]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rustica.fr/`

### Category

detection

### Description

1. Go to https://www.rustica.fr/
2. A modal window block access to the website, and says (in French) "Bloqueur de publicité détecté !", which translate to "Adblocker detected"
3. Disabling ublock allows access to the website

### Other extensions used

Sponsorblock, DarkReader, I Still Don't Care About Cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 185210
 cosmetic: 254214
 scriptlet: 49090
 html: 1970
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 79903-5653, now
  adguard-mobile: 9143-113, now
  curben-phishing: 14160-2, 20m
  adguard-social: 22669-860, now
  adguard-cookies: 28939-72, now
  adguard-popup-overlays: 26846-1630, now
  adguard-mobile-app-banners: 5078-1084, now
  adguard-other-annoyances: 14042-341, now
  adguard-widgets: 2418-1, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4436-124, now
  [9 lists not shown]: [too many]
 default:
  ublock-filters: 37611-547, 20m Δ
  ublock-badware: 7852-14, 20m Δ
  ublock-privacy: 759-0, 20m Δ
  ublock-unbreak: 2308-0, 20m Δ
  ublock-quick-fixes: 212-0, 20m Δ
  easylist: 82722-814, 20m Δ
  easyprivacy: 50381-1197, 20m Δ
  urlhaus-1: 7635-5, 20m
  plowe-0: 3765-1, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 196 ms (selfie)
 maxAssetCacheWait: 105 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  rustica.fr: 1
  fastcmp.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.social
  ###stickMe
  ##.col-lg-3.ps-lg-0 > *:not(.nav)
  ###insidedroite > div.mb-3:has(> form.inscription-nl)
  ##.adslot
  ##.BeOpWidget
  ##.back-top
  ##+js(abort-on-property-write, dtctAB)
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 

```
rustica.fr##+js(set, checkAdsBlocked, noopFunc)
rustica.fr##body:style(padding-top: 0px !important;)
```

**Comment by Yuki2718** [comment]
@JobcenterTycoon Please consider to ping other AG team members too, as I suffer with too many notification these days.
