### ISSUE TITLE
erroneously blocks article images on clickondetroit.com

### ISSUE THREAD

**Issue by divinity76** [uBlockOrigin/uAssets#2295]
### URL(s) where the issue occurs

`https://www.clickondetroit.com/all-about-michigan/michigan-history/91-years-later-michigans-bath-school-disaster-remains-deadliest-of-its-kind-in-us-history`

### Describe the issue

all (or nearly all?) article images are being blocked. i had to disable uBlock while reading the article to enjoy it. 

### Screenshot(s)
ublock enabled: 
![ublockenabled](https://user-images.githubusercontent.com/1874996/40073726-f7288ca8-5877-11e8-9f1d-775ff1c74dde.png)

ublock disabled: 
![ublockdisabled](https://user-images.githubusercontent.com/1874996/40073745-ff3ff908-5877-11e8-8a1d-984dff0ce0d9.png)

### Versions

- Browser/version: happens both on Chrome 66.0.3359.139 (Official Build) (64-bit)  AND Firefox 52.8.0-ESR (64-bit)
- uBlock Origin version: Chrome: 1.16.4  Firefox: 1.16.6

### Settings

- [List here all the changes you made to uBO's default settings]
N/A

### Notes

seems to be a filter blocking everything from `bobcat.grahamdigital.com`, as a specific example, this image url is blocked: https://bobcat.grahamdigital.com/d07d246a0c11d2b97cb1a7828bc6cacda084a8ab/crop-640x360-000.jpg

uBlock's message: 

> uBlock Origin has prevented the following page from loading:
> 
> https://bobcat.grahamdigital.com/d07d246a0c11d2b97cb1a7828bc6cacda084a8ab/crop-640x360-000.jpg
> 
> Because of the following filter
> 
> ||grahamdigital.com^
> 
> Found in: Peter Lowe’s Ad and tracking server list
>

**Comment by smed79** [comment]
@mapx- blocked by which filter?

**Comment by mapx-** [comment]
see above

> ||grahamdigital.com^
> 
> Found in: Peter Lowe’s Ad and tracking server list

**Comment by yourduskquibbles** [comment]
FYI @pgl `||grahamdigital.com^` filter is also breaking the following [Graham Digital](http://www.grahammedia.com/http/grahamdigitalcom/) sites: 

1. https://www.click2houston.com
2. https://www.clickondetroit.com
3. https://www.clickorlando.com
4. https://www.ksat.com
5. https://www.local10.com
6. https://www.news4jax.com
7. https://www.wsls.com

@mapx- or @okiehsch  Are you able to update the filter from https://github.com/uBlockOrigin/uAssets/commit/a146cc972042b0628f548f8640a3d91b0b83aa2e to include these other domains as well or do you want me to open separate issues for each domain?

**Comment by pgl** [comment]
Thanks, I've removed `grahamdigital.com` from my list.
