### ISSUE TITLE
[nsfw] 3xyaoi.com: popups

### ISSUE THREAD

**Issue by Benjigx** [uBlockOrigin/uAssets#22957]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://3xyaoi.com/`

### Category

popups

### Description

pop up +18  news tabs

### Other extensions used

pop up +18 new tabs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 137607
 cosmetic: 204116
 scriptlet: 33928
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28939-33, now
  adguard-mobile-app-banners: 5078-8, now
  adguard-other-annoyances: 14042-10, now
  adguard-popup-overlays: 26846-83, now
  adguard-social: 22669-903, now
  adguard-widgets: 2418-3, now
  easylist-annoyances: 4436-249, now
  easylist-chat: 187-15, now
  easylist-newsletters: 7129-496, now
  easylist-notifications: 2963-1470, now
  fanboy-cookiemonster: 50382-3859, now
  fanboy-social: 15792-744, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  easylist: 82722-75, 8m Δ
  easyprivacy: 50381-121, 8m Δ
  plowe-0: 3765-1184, now
  spa-1: 5436-76, now
  ublock-badware: 7848-147, 8m Δ
  ublock-filters: 37437-708, 8m Δ
  ublock-privacy: 763-8, 8m Δ
  ublock-quick-fixes: 208-33, 8m Δ
  ublock-unbreak: 2251-40, 8m Δ
  urlhaus-1: 7635-5, 8m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1202 ms (selfie)
 maxAssetCacheWait: 718 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  3xyaoi.com: 1
  insanityquietlyviolent.com: 1
 extended:
  ##.c-ads
  ##.body-top-ads
  ##.go-to-top
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 `3xyaoi.com##+js(set, initPopunder, noopFunc)`

**Comment by Ozumbi** [comment]
![Image](https://github.com/user-attachments/assets/766f62c2-7d74-445b-a463-aedefbffbe5f)

O 3xyaoi consegue detectar o ublock origin, como contorno isso?

**Comment by Yuki2718** [comment]
@Ozumbi Please report to https://github.com/AdguardTeam/AdguardFilters/issues next time.
