### ISSUE TITLE
download.megaup.net: detection

### ISSUE THREAD

**Issue by joshenko** [uBlockOrigin/uAssets#22955]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/`

### Category

detection

### Description

megaup.net is now able to detect Ublock Origin (wasn't before) and block users from downloading files

### Other extensions used

IDM Integration Module

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19656033/ed993c8d-170d-44f9-9a9d-4859b94a7aef)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126365
 cosmetic: 49365
 scriptlet: 20689
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 82722-16, now
  easyprivacy: 50381-8, now
  plowe-0: 3765-1183, now
  spa-1: 5436-71, now
  ublock-badware: 7848-147, now
  ublock-filters: 37437-369, now
  ublock-privacy: 763-6, now
  ublock-quick-fixes: 208-33, now
  ublock-unbreak: 2251-36, now
  urlhaus-1: 7635-5, 38m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 593 ms (selfie)
 maxAssetCacheWait: 240 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 4
 network:
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  keydawnawe.com: 1
 extended:
  ##a img:not([src="images/main_logo_inverted.png"]):matches-css(h…
  ##+js(spoof-css, a img:not([src="images/main_logo_inverted.png"]…
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(remove-node-text, script, FingerprintJS)
```
</details>

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20505

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5ffc8409e42bb2e0bca158e9667df027965b487d
