### ISSUE TITLE
hindustantimes.com: nuisance

### ISSUE THREAD

**Issue by Broken-Glass1** [uBlockOrigin/uAssets#22969]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.hindustantimes.com/education/competitive-exams/ssc-gd-answer-key-2024-live-updates-constable-answer-keys-ssc-nic-in-direct-link-101710644278588.html
```

### Description

Social media icon

### Other extensions used

no

### Screenshot(s)

![brave_screenshot_www hindustantimes com](https://github.com/uBlockOrigin/uAssets/assets/159278763/d676abeb-b2dc-464b-b3df-b509a062af83)

### Configuration

ubo default + fanboy social block list

**Comment by ItsProfessional** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Not seeing it. Got an ad element

**Comment by mapx-** [comment]
add

`hindustantimes.com##a.fb,a.tw,a.ln`

@ryanbr

**Comment by mapx-** [comment]
already fixed https://github.com/easylist/easylist/commit/c6338f6407ff7ead3b865a5ea61739e30df6d8c8

**Comment by mapx-** [comment]
use this link to update your filter list
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=fanboy-social&manual=1

**Comment by mapx-** [comment]
provide an article where you still see social icons

**Comment by mapx-** [comment]
the social stuff is hidden on my end

**Comment by stephenhawk8054** [comment]
> on all articles

Can you give exact links where the issue occurs?

**Comment by stephenhawk8054** [comment]
You are using too many additional filter lists. That's not what you claimed here:

> ubo default + fanboy social block list

Sorry, I won't participate in this any more.

**Comment by mapx-** [comment]
@Broken-Glass1 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
