### ISSUE TITLE
dropgalaxy.vip: detection

### ISSUE THREAD

**Issue by xd003** [uBlockOrigin/uAssets#22965]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://dropgalaxy.vip/8u9f0umvtuzl
https://financemonk.net/gold-rate-today-in-india-latest-updates-trends-march-6-2024/ ( The URL where the above URL redirects but i have noticed that directly opening this URL doesn't work so have to click on the Free Download button on the dropgalaxy URL to get redirected and reproduce the detection issue )
```

### Description

Adblock is detected as soon as the original URL redirects to a different webpage

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26503185/0b345cd1-28ba-4bb4-9a24-55f6761a1273)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 124944
 cosmetic: 45648
 scriptlet: 18985
 html: 1715
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37616-163, 15m
  ublock-badware: 7852-14, 15m
  ublock-privacy: 759-0, 15m
  ublock-unbreak: 2309-0, 15m
  ublock-quick-fixes: 214-0, 15m
  easylist: 82722-639, 15m
  easyprivacy: 50376-832, 15m
  urlhaus-1: 7485-5, 15m
  plowe-0: 3765-1, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6353 ms
 maxAssetCacheWait: 87 ms
 cacheBackend: indexedDB

```
</details>

**Comment by xd003** [comment]
I see this is labelled as a duplicate but i didn't found any other issue currently open for this very website. Sorry if i missed something

**Comment by ItsProfessional** [comment]
> Ah didn't knew there's a dedicated discussion for such sites, thanks for the heads up

You checked this:
> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or **[_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361)** report. _These sites MUST be reported by clicking their **respective links**_.
