### ISSUE TITLE
Afdah.to anti-adblock

### ISSUE THREAD

**Issue by AllPermission** [uBlockOrigin/uAssets#2296]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`afdah.to`

### Describe the issue

Anti-adblocker prevents watching videos

### Notes

Anti-adblock scripts are
http://afdah.to/show-ad.js
http://afdah.to/show-ads.js

**Comment by ghajini** [comment]
`https://afdah.info/watch-movies/67727-glass-2019/`
Click on `server 4`,  popup ads

**Comment by mapx-** [comment]
I get no popup chrome / FF

**Comment by ghajini** [comment]
Probably fixed during https://github.com/uBlockOrigin/uAssets/commit/af5ffcfe26efbdb3ad23c14ab78b937ef5aac3c3

**Comment by mapx-** [comment]
right, I'll add
```
psystreams.com##+js(abort-on-property-read.js, AaDetector)
psystreams.com##+js(abort-on-property-read.js, decodeURI)
```
