### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by maxwisecracks** [uBlockOrigin/uAssets#22967]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.derstandard.at/adblockwall/`

### Category

detection

### Description

site unusable

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-18 145327](https://github.com/uBlockOrigin/uAssets/assets/160344168/c8fb9b3d-facd-439f-8df4-15b398efc01f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 127667
 cosmetic: 50626
 scriptlet: 20311
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7332-0, 1m
  easylist: 82722-24, 1m
  easyprivacy: 50383-17, 1m
  plowe-0: 3765-1184, 1m
  ublock-badware: 7848-147, 1m
  ublock-filters: 37441-372, 1m
  ublock-privacy: 763-6, 1m
  ublock-quick-fixes: 210-33, 1m
  ublock-unbreak: 2251-35, 1m
  urlhaus-1: 7870-5, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1111 ms
 maxAssetCacheWait: 5 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 1
 network:
  derstandard.at: 1
 extended:
  ##+js(trusted-replace-node-text, script, "adsDisabled":false, "a…
  ##+js(no-setTimeout-if, event, 3000)
```
</details>

**Comment by mots** [comment]
Still happening to me with default settings. If you can't repro, I suspect they might be a/b testing their new login wall?
