### ISSUE TITLE
hashrate.no: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#22974]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hashrate.no/gpus`

### Category

ads

### Description

ad

### Other extensions used

violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/5c703091-d9df-46d8-96fa-7d0f3e9ab66b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 156590
 cosmetic: 166026
 scriptlet: 32287
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/fake.txt: 16404-0, 1h.8m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt: 22882-79, 1h.8m
  adguard-cookies: 28962-33, 1h.8m
  easylist-annoyances: 4432-47, 1h.8m
  easylist-chat: 187-0, now
  easylist-newsletters: 7137-22, 1h.8m
  easylist-notifications: 2965-90, 1h.7m
  fanboy-cookiemonster: 50386-3832, 1h.7m
  fanboy-social: 15809-29, 1h.7m
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 6925-97, 1m Δ
  ublock-cookies-easylist: 1048-1048, 1h.7m
 default:
  user-filters: 0-0, never
  TUR-0: 12040-26, 1h.8m
  easylist: 82785-212, 1m Δ
  easyprivacy: 50384-136, 1m Δ
  plowe-0: 3765-1187, now
  ublock-badware: 7854-147, 1m Δ
  ublock-filters: 37414-401, 1m Δ
  ublock-privacy: 764-8, 1m Δ
  ublock-quick-fixes: 213-34, 1m Δ
  ublock-unbreak: 2252-39, 1m Δ
  urlhaus-1: 7870-5, 1h.8m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 451 ms (selfie)
 maxAssetCacheWait: 177 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 32
 network:
  coinzillatag.com: 1
  ctengine.io: 1
  google.com: 8
  googlesyndication.com: 3
  googletagmanager.com: 4
  youtube.com: 15
 extended:
  ##ins.adsbygoogle
  ###google_ads_frame1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
hashrate.no##center:has(.sevioads)
hashrate.no##.verticalAdContainer
```

@ryanbr
