### ISSUE TITLE
easymc.io detection

### ISSUE THREAD

**Issue by Razzy52** [uBlockOrigin/uAssets#22978]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
easymc.io
```

### Description

Ad's are detected on latest UBO. 

### Other extensions used

NA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
NA

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    
NA

**Comment by ItsProfessional** [comment]
Provide screenshot and troubleshooting info.

**Comment by Razzy52** [comment]
Sorry for the long delay, I've been fairly busy lately.

![image](https://github.com/uBlockOrigin/uAssets/assets/101041312/2dc6ddbd-d3a8-41bb-948f-8fc16befbd39)


I believe this to be the correct troubleshooting information.


uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 125551
 cosmetic: 45659
 scriptlet: 18990
 html: 1717
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37580-145, 2h.39m Δ
  ublock-badware: 7985-14, 2h.39m Δ
  ublock-privacy: 761-0, 2h.39m Δ
  ublock-unbreak: 2309-0, 2h.39m Δ
  ublock-quick-fixes: 225-0, 2h.39m Δ
  easylist: 82825-637, 2h.39m Δ
  easyprivacy: 50395-867, 2h.39m Δ
  urlhaus-1: 7885-5, 23h.24m
  plowe-0: 3772-1, 6d.3h.44m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 280 ms (selfie)
 maxAssetCacheWait: 71 ms
 cacheBackend: indexedDB

**Comment by stephenhawk8054** [comment]
Your 2nd image wasn't uploaded successfully yet

**Comment by Razzy52** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/101041312/2a7b4706-6c3f-4179-8a18-bd6a23204107)
sorry

**Comment by ItsProfessional** [comment]
@Razzy52 Screenshot your "My filters" and send here.

**Comment by Razzy52** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/101041312/802d719c-1efc-4fe8-85e4-9826ece7f825)
![image](https://github.com/uBlockOrigin/uAssets/assets/101041312/26abe3de-5e92-4127-b68a-30afd2518e80)
![image](https://github.com/uBlockOrigin/uAssets/assets/101041312/da6ee8b1-ced9-492e-ae71-d9d19de09b91)

**Comment by Razzy52** [comment]
Clearing site cookies and changing DNS to automatic seems to have fixed it. I will report back if this happens again, this time with everything being tested properly.
Thanks for the help
