### ISSUE TITLE
olx.in: ads

### ISSUE THREAD

**Issue by Broken-Glass1** [uBlockOrigin/uAssets#22976]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.olx.in/
```

### Description

Blank frame of blocked ads.
Web Browser:- Brave Browser with shields Aggressive + ubo

### Other extensions used

No

### Screenshot(s)

![brave_screenshot_www olx in](https://github.com/uBlockOrigin/uAssets/assets/159278763/a3d6495b-5af8-4003-b407-61643555e21f)

### Configuration

Ubo default + easylist cookie + fanboy social filter + ag ads. mobile. url. privacy, annoyance.

**Comment by mapx-** [comment]
- working fine in brave on my end
- are you sure your filters are updated ? => use this link for update the list: 
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1

**Comment by mapx-** [comment]
Did you update the lists as I indicated above ?

**Comment by mapx-** [comment]
reset uBO to defaults
