### ISSUE TITLE
phind.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#22975]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.phind.com/search?q=advantages+using+sveltejs+%3F&source=searchbox`

### Category

nuisance

### Description

popu up overlay, 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/3c2336a4-59ee-4b67-9d99-7bca2bbd42dd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 135362
 cosmetic: 160055
 scriptlet: 33976
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8553-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 199-0, now
  adguard-cookies: 28962-33, now
  adguard-other-annoyances: 14048-23, now
  adguard-popup-overlays: 26865-81, now
  easylist-annoyances: 4432-218, now
  easylist-notifications: 2965-393, now
  fanboy-cookiemonster: 50386-3855, now
  ublock-annoyances: 6925-228, 58m Δ
  ublock-cookies-adguard: 1050-1050, now
  ublock-cookies-easylist: 1050-1050, now
 default:
  user-filters: 47-0, never
  easylist: 82785-78, 58m Δ
  easyprivacy: 50384-115, 58m Δ
  plowe-0: 3765-1184, now
  ublock-badware: 7854-148, 58m Δ
  ublock-filters: 37414-777, 58m Δ
  ublock-privacy: 764-7, 58m Δ
  ublock-quick-fixes: 213-34, 58m Δ
  ublock-unbreak: 2252-37, 58m Δ
  urlhaus-1: 7950-5, now
filterset (user): [array of 47 redacted]
trustedset:
 added: [array of 36 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2501 ms (selfie)
 maxAssetCacheWait: 1043 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 2
  sentry.io: 1
  vercel-insights.com: 2
```
</details>

**Comment by ItsProfessional** [comment]
Self promotion.
