### ISSUE TITLE
c.lazada.co.id: popups

### ISSUE THREAD

**Issue by rzgriz** [uBlockOrigin/uAssets#22973]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection or [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [ ] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://c.lazada.co.id/t/c.bTN9Uj`

### Category

popups

### Description

Annoying popup of online market app from south east asia

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 122
filterset (summary):
 network: 126730
 cosmetic: 37532
 scriptlet: 19048
 html: 1716
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37973-404, 14m Δ
  ublock-badware: 7846-14, 14m Δ
  ublock-privacy: 759-1, 14m Δ
  ublock-unbreak: 2313-1, 14m Δ
  ublock-quick-fixes: 214-0, 14m Δ
  adguard-mobile: 9162-133, now
  easylist: 82712-16421, 14m Δ
  easyprivacy: 50383-841, 14m Δ
  urlhaus-1: 7870-5, 14m
  plowe-0: 3765-1, now
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1878 ms
 maxAssetCacheWait: 717 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
test
