### ISSUE TITLE
tekinvestor.no: nuisance

### ISSUE THREAD

**Issue by Nuruiak** [uBlockOrigin/uAssets#22985]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tekinvestor.no/t/hvordan-henter-scraper-dere-data-om-selskaper-pa-oslo-bors-fra-nettet/8749/19`

### Category

nuisance

### Description

Forced login wall. It usually shows up after 10-15 seconds of first viewing the page. I can click outside the main sign-up window to close the wall, but it almost instantly appears again. The login wall did not reappear after clicking in the light blue area on the main domain.

Edit(s): Cleaned up grammar and fixed inaccurate label.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-19 at 18-57-10 Hvordan henter (scraper) dere data om selskaper på Oslo Børs fra nettet - Spørsmål   Svar - TekInvestor - Norges Beste Aksjeforum](https://github.com/uBlockOrigin/uAssets/assets/164057043/4bc8c528-2895-4312-9995-f15a285f476b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 141134
 cosmetic: 204418
 scriptlet: 32897
 html: 1973
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 439-54, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2617-51, never
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2092-10, never
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, never
  block-lan: 61-0, never
  adguard-social: 22684-744, never
  adguard-cookies: 28982-84, never
  adguard-popup-overlays: 26878-1676, never
  adguard-mobile-app-banners: 5084-1095, never
  adguard-other-annoyances: 14056-708, never
  adguard-widgets: 2421-44, never
  easylist-annoyances: 4437-122, never
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37592-135, 1h.8m Δ
  ublock-badware: 7858-14, 1h.8m Δ
  ublock-privacy: 760-0, 1h.8m Δ
  ublock-unbreak: 2309-0, 1h.8m Δ
  ublock-quick-fixes: 218-0, 1h.8m Δ
  easylist: 82819-733, 1h.8m Δ
  easyprivacy: 50386-1031, 1h.8m Δ
  urlhaus-1: 7945-5, 1h.21m
  plowe-0: 3765-1, 1h.19m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 899 ms (selfie)
 maxAssetCacheWait: 401 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  amplitude.com: 1
  cloudflareinsights.com: 2
  google-analytics.com: 1
  plausible.io: 1
 extended:
  ##a[title="Share on Facebook"]
  ##a[title="Share on Twitter"]
  ##button[title="Share on Twitter"]
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by gorhill** [comment]
This works:

    tekinvestor.no###discourse-modal:style(visibility: hidden !important)
    tekinvestor.no##.modal-backdrop

The page doesn't like usage of `display: none`, so `visibility: hidden` works better here. Not sure which list that would go in.

**Comment by Nuruiak** [comment]
Thanks, works without any issues @gorhill :)

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
tekinvestor.no##+js(nostif, custom-modal-create-account-link)
```

cc @ryanbr

**Comment by stephenhawk8054** [comment]
Fixed in `EasyList – Other Annoyances` list
