### ISSUE TITLE
fakty.tvn24.pl: breakage

### ISSUE THREAD

**Issue by akurzawa** [uBlockOrigin/uAssets#22980]
Synt4x err0r

**Comment by stephenhawk8054** [comment]
Can you screenshot your "My filters" pane to here?

**Comment by akurzawa** [comment]
> Can you screenshot your "My filters" pane to here?

![image](https://github.com/uBlockOrigin/uAssets/assets/20043789/06930bfe-c10c-4984-a65e-262396d78769)

**Comment by gwarser** [comment]
Default settings, accept cookies, refresh page, and it works. For some reason, is problematic on Chrome (requires reload), works fine in Firefox.

**Comment by akurzawa** [comment]
Any clue why in Chrome it requires reloading?

**Comment by garry-ut99** [comment]
It works fine for me on Firefox and Opera, and no need to reload.

**Comment by mapx-** [comment]
@akurzawa reset uBO to defaults, do not use any other blocking extension / builtin blocker
