### ISSUE TITLE
94.103.83.138: popups

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#22982]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://94.103.83.138/movies/stopmotion/`

### Category

popups

### Description

clicking on movies opens popup,also playing movies open popup

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium Mobile: 110
filterset (summary):
 network: 136520
 cosmetic: 167757
 scriptlet: 29882
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4434-65, 2d.19h.25m
  easylist-chat: 186-0, 2d.19h.25m
  easylist-newsletters: 7127-14, 2d.19h.25m
  easylist-notifications: 2962-1231, 2d.19h.25m
 default:
  user-filters: 42-2, never
  ublock-filters: 37783-448, 2h.38m Δ
  ublock-badware: 7848-14, 2h.38m Δ
  ublock-privacy: 764-0, 2h.38m Δ
  ublock-unbreak: 2257-0, 2h.38m Δ
  ublock-quick-fixes: 214-0, 2h.38m Δ
  adguard-mobile: 9143-19, 2d.19h.25m
  easylist: 82819-772, 2h.38m Δ
  easyprivacy: 50386-31, 2h.38m Δ
  urlhaus-1: 7945-5, 2h.38m
  plowe-0: 3765-892, 2d.19h.25m
filterset (user): [array of 42 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1160 ms (selfie)
 maxAssetCacheWait: 141 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  lawfulrole.com: 1
 extended:
  ##a[href^="whatsapp://send"]
  ##.dt_social_single
```
</details>

**Comment by gorhill** [comment]
This works for me:

    94.103.83.138###clickfakeplayer:remove-attr(href)

**Comment by JobcenterTycoon** [comment]
I also need `94.103.83.138##+js(nowoif)` because the site open popups on the startpage.
