### ISSUE TITLE
rsgames.xyz: detection

### ISSUE THREAD

**Issue by absouini** [uBlockOrigin/uAssets#22986]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rsgames.xyz/link?token=VD3hSALyE/fx+U148NH+O4onstrhhMOjAXGSbNQEZevyrGlNivpYwJ9anwoi4ZHSI34L5Twny4GJpX2rNH3JO9dqYCEudTl8AN6pHmgeWiMGfBQyikHg2Ey+8fRMx+GtomylDmXLw6FPFKK8inLw0jS7QXFgsEzTv5hWIRkEgKwycLzhm6Ri`

### Category

detection

### Description

it's a Shortlink : https://rsshort.com/heOf   PLEASE USE THIS TO ENTER 

### Other extensions used

Adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 141216
 cosmetic: 52485
 scriptlet: 20484
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1468-3, never
  FRA-0: 23133-36, now
  easylist: 82821-138, now
  easyprivacy: 50386-252, now
  plowe-0: 3765-1192, now
  ublock-badware: 7854-162, now
  ublock-filters: 37426-1765, now
  ublock-privacy: 764-6, now
  ublock-quick-fixes: 215-34, now
  ublock-unbreak: 2252-37, now
  urlhaus-1: 7945-5, now
filterset (user): [array of 765 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8759 ms (selfie)
 maxAssetCacheWait: 555 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by ItsProfessional** [comment]
#17361
