### ISSUE TITLE
vtmgo.be: detection

### ISSUE THREAD

**Issue by dettcdryvt** [uBlockOrigin/uAssets#22988]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vtmgo.be/`

### Category

detection

### Description

detects the adblock, the player stops working

### Other extensions used

FFZ
7TV
betterTTV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/164087022/84967da7-8b42-4afb-b06a-0079a2b6e1db)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126168
 cosmetic: 47742
 scriptlet: 20367
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  NLD-0: 2772-10, 10m
  easylist: 82822-20, now
  easyprivacy: 50386-9, now
  plowe-0: 3765-1183, now
  ublock-badware: 7884-147, now
  ublock-filters: 37426-356, now
  ublock-privacy: 764-6, now
  ublock-quick-fixes: 215-34, now
  ublock-unbreak: 2252-33, now
  urlhaus-1: 7945-5, 1h.56m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 93 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 1
  fwmrm.net: 1
  gemius.pl: 1
  litix.io: 1
  pushengage.com: 2
  vtm.be: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe

```adb
vtmgo.be##+js(no-fetch-if, doubleclick)
```

@JohnyP36 Sorry can you check this?

**Comment by mapx-** [comment]
@Nomes77
