### ISSUE TITLE
20min.ch: breakage

### ISSUE THREAD

**Issue by y4nuts** [uBlockOrigin/uAssets#22983]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.20min.ch/fr`

### Category

breakage

### Description

Site doesn't load with adblock on.
Error message :
(Application error: a client-side exception has occurred (see the browser console for more information)
If i disable adblock the site load, then i just activate adblock and the site works just fine... 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 152382
 cosmetic: 207416
 scriptlet: 32139
 html: 1972
listset (total-discarded, last-updated):
 added:
  adguard-social: 22683-857, now
  adguard-cookies: 28982-72, now
  ublock-cookies-adguard: 1053-0, now
  adguard-popup-overlays: 26878-1629, now
  adguard-mobile-app-banners: 5084-1085, now
  adguard-other-annoyances: 14056-340, now
  adguard-widgets: 2421-1, now
  easylist-annoyances: 4437-124, now
  easylist-chat: 187-15, now
  fanboy-cookiemonster: 50633-3904, now
  ublock-cookies-easylist: 1053-1053, now
  easylist-newsletters: 7139-12, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37592-534, now
  ublock-badware: 7858-14, now
  ublock-privacy: 760-0, now
  ublock-unbreak: 2309-0, now
  ublock-quick-fixes: 218-0, now
  easylist: 82819-843, now
  easyprivacy: 50386-1190, now
  urlhaus-1: 7945-5, now
  plowe-0: 3765-1, now
  FRA-0: 23133-126, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 231 ms (selfie)
 maxAssetCacheWait: 163 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  adnxs.com: 4
  browser-intake-datadoghq.eu: 1
  casalemedia.com: 1
  criteo.com: 1
  criteo.net: 1
  doubleclick.net: 2
  indexww.com: 1
  pubmatic.com: 2
  teads.tv: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
`||rackcdn.com/stf.js` in EasyPrivacy breaks

**Comment by JobcenterTycoon** [comment]
Does

```
20min.ch##+js(set, _ain, {})
20min.ch##+js(set, window._ain.stop, noopFunc)
```
Works?

**Comment by y4nuts** [comment]
Yes it works.

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e3699d5cc15f7ad60a7d836be9be2ce363b6b83c works. Run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1 to get the fix directly.

**Comment by y4nuts** [comment]
Thanks ! 

Have great day.

**Comment by trevon88** [comment]
Works! Thanks!
