### ISSUE TITLE
False positive Badware filter: roundyearfun.org

### ISSUE THREAD

**Issue by roundyearfun** [uBlockOrigin/uAssets#22990]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
roundyearfun.org
roundyearfun.com
anyplacehere.me
funaroundy.click
anyplacehere.live
funtwitter.games
twitter-circle.com
funroundy.click
twitterfun.games
funxgames.site
funroundy.online
funxgames.me
anyplacehere.store
```

### Description

The article attached [here](https://github.com/uBlockOrigin/uAssets/pull/18388) is 2 years old and was a coordinated hit piece by a competitor called "Affinitweet". None of the information in the article is correct and our website hosts authentic Twitter games for Twitter users to enjoy. The filter in your plugin is limiting people's ability to enjoy our website and is hurting our reputation. Please see: [https://github.com/uBlockOrigin/uAssets/pull/18388#issuecomment-2008197509](https://github.com/uBlockOrigin/uAssets/pull/18388#issuecomment-2008197509)

### Other extensions used

none

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
"our site" while you post 12 domains ... many of them with questionable domain names like `anyplacehere.live` or `funaroundy.click`

**Comment by Daxy7** [comment]
```
https://anyplacehere.live
https://anyplacehere.me
https://anyplacehere.store
https://funaroundy.click
https://funroundy.click
https://funroundy.online
https://funtwitter.games
https://funxgames.me
https://funxgames.site
https://roundyearfun.com
https://roundyearfun.org
https://twitter-circle.com
https://twitterfun.games
```
It seems like detection circumvenetion [revolving domains], buying in bulk inexpensive domains to me

**Comment by gorhill** [comment]
Declined.

**Comment by gorhill** [comment]
You can still find many recent complaints on Twitter regarding this "", Examples:

- `https://twitter.com/imcleasknife/status/1720855198313091355`
- `https://twitter.com/M1asmaGh0ul/status/1769622521475895395`
- `https://twitter.com/LoxyThePinkFoxy/status/1769355398065144156`
- etc.
