### ISSUE TITLE
rts.ch: breakage

### ISSUE THREAD

**Issue by y4nuts** [uBlockOrigin/uAssets#22999]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rts.ch/play/tv/cash/video/ballons-chateau-doex?urn=urn:rts:video:14720533`

### Category

breakage

### Description

Since they update their site i can't play video with adblock on.

I had to disable ad block and delete their cookies in order to play their videos it it can help you.

It works with adblock on with annoyances disabled but you have to delete their cookies.
### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 152608
 cosmetic: 207441
 scriptlet: 32155
 html: 1973
listset (total-discarded, last-updated):
 added:
  adguard-social: 22687-56, never
  adguard-cookies: 28991-78, never
  ublock-cookies-adguard: 1054-1054, never
  adguard-popup-overlays: 26886-1689, never
  adguard-mobile-app-banners: 5093-1104, never
  adguard-other-annoyances: 14058-740, never
  adguard-widgets: 2421-46, never
  easylist-annoyances: 4439-144, never
  easylist-chat: 187-0, never
  fanboy-cookiemonster: 50642-3906, never
  ublock-cookies-easylist: 1054-1054, never
  easylist-newsletters: 7139-23, never
  [3 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37574-209, 20m
  ublock-badware: 7966-14, 20m
  ublock-privacy: 761-0, 20m
  ublock-unbreak: 2309-0, 20m
  ublock-quick-fixes: 225-0, 20m
  easylist: 82804-789, 20m
  easyprivacy: 50394-1079, 20m
  urlhaus-1: 8040-0, 20m
  plowe-0: 3765-1, 20m
  FRA-0: 23185-109, 20m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 208 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  chartbeat.net: 6
  scorecardresearch.com: 7
  srf.ch: 11
```
</details>

**Comment by y4nuts** [comment]
If i get the cookies without adblock, it works with adblock on so i'm not sure if it is an ublock issue or the website itself.

**Comment by gorhill** [comment]
Ok I can reproduce with "EasyList/uBO -- Cookie Notices". I had to except those filters to make the cookie wall appears:

- `rts.ch##+js(trusted-set-local-storage-item, uc_user_interaction, true)`
- `rts.ch##+js(trusted-set-local-storage-item, uc_settings, uc_settings)`
- `||usercentrics.eu^$3p`

Once the cookie wall appears, clicking _"Accepter uniquement les services strictement nécessaires"_ fixes the breakage.

**Comment by mapx-** [comment]
@ryanbr @Alex-302

needing
```
@@||app.usercentrics.eu/browser-ui/latest/loader.js$script,domain=rts.ch
@@||app.usercentrics.eu/browser-ui/$script,domain=rts.ch
@@||api.usercentrics.eu^$xhr,domain=rts.ch
```
