### ISSUE TITLE
mhdsports.com: detection

### ISSUE THREAD

**Issue by tailscale7** [uBlockOrigin/uAssets#22994]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://mhdsports.com/
```

### Description

Adblocker detected

### Other extensions used

none

### Screenshot(s)

![Capture](https://github.com/uBlockOrigin/uAssets/assets/110523519/f63abc04-dfb6-4e50-b2ad-9151f6bb1b78)

### Configuration

uBlock Origin: 1.56.0
Chromium: 109
filterset (summary):
 network: 125514
 cosmetic: 45837
 scriptlet: 20313
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 183-1, never
  easylist: 82800-16, 56m Δ
  easyprivacy: 50387-8, 56m Δ
  plowe-0: 3765-1183, 3d.1h.15m
  ublock-badware: 7894-147, 56m Δ
  ublock-filters: 37397-357, 56m Δ
  ublock-privacy: 764-6, 56m Δ
  ublock-quick-fixes: 215-35, 56m Δ
  ublock-unbreak: 2252-33, 56m Δ
  urlhaus-1: 7950-5, 1d.8m
filterset (user): [array of 183 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2083 ms (selfie)
 maxAssetCacheWait: 325 ms
 cacheBackend: browser.storage.local

**Comment by punisher018** [comment]
Can you take another look at it? I also keep getting adblock warnings with these filters, but not always. (without my filters) Try clicking on 5-6 channels in a row and it should show up.

Previously I added the filters below for these sites to my filters and it works fine for me.

`@@||static.doubleclick.net/instream/ad_status.js$xhr,domain=mhdtvmax.net`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=mhdtvsports.net|mhdsports.com`

**Comment by mapx-** [comment]
@punisher018 

test

`mhdsports.*##+js(aost, fetch, HTMLDocument)`

**Comment by punisher018** [comment]
@mapx it's ok for mhdsports.com 👌

**Comment by punisher018** [comment]
You can add this one too.

`mhdtvmax.net##+js(aost, fetch, HTMLDocument)`
