### ISSUE TITLE
Androidrepublic.org

### ISSUE THREAD

**Issue by m1m2m3mr** [uBlockOrigin/uAssets#2299]
### URL(s) where the issue occurs

`https://androidrepublic.org/threads/hive-summoner-war.59393/`

### Describe the issue

"Please support us by disabling AdBlocker on our website." appear below of main thread and appear on random posts 

### Versions

- Browser/version: Version 66.0.3359.139 (Official Build) (64-bit)
- uBlock Origin version: 1.16.4

### Settings

- Default settings

**Comment by uBlock-user** [comment]
`androidrepublic.org##.samSupportUs`

**Comment by mapx-** [comment]
I cannot reproduce the issue, however seems to be an annoyance, right ?

**Comment by m1m2m3mr** [comment]
Yeah it's annoyance. Thank for the code
