### ISSUE TITLE
Not an issue : how to disable a 3rd-party filter?

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#23]
Just a fast, easy question regarding a point I should know by the time but ignore nevertheless:

How must I proceed to disable a given 3rd-party filter?
Specifically, I wish to disable _3rd-party filters / uBlock filters /_ dailymotion.com##script:inject(1136.js)

I've tried adding to _My filters_, @@||dailymotion.com##script:inject(1136.js) but it doesn't seem to work.

Thanks

**Comment by gorhill** [comment]
Currently exception filters for `[...]##script:[...]` filters are not supported. However, if you [toggle off cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) for the site, scriptlets won't be injected.

**Comment by zymase** [comment]
OK, gorhill, thanks. Toggling off cosmetic filtering for the site has the inconvenience of being exaggeratedly radical and the advantage of immediate efficiency. Of course it's bothering to lose other wished cosmetic filters applicable to the site for the sake of disabling only one. Anyway I know now how to proceed.
This was not an issue stricto sensus , but where else to expose a non-issue question? If there is thanks for letting me know.

**Comment by gorhill** [comment]
Is there an issue with `script:inject(1136.js)`?

**Comment by zymase** [comment]
There's always an issue with DailyMotion, not with UBO scripts which handle the issues correctly but which may face a site's obsession to continuously modify their code to perform, in the case of DailyMotion, their in-video ad force-feed.

Confronted recently to a non efficiency of `script:inject(1136.js)` to block what appeared to be another code shift on the part of DailyMotion I just started wondering if it wouldn't be more pertinent -- as far as I'm concerned -- to consider another approach than that of a valuable script but vulnerable confronted to DailyMotion's ever-changing code : slightly annoyed of this continuous cat-mouse race, for me, for exposing it again & again, having you, gorhill, spend time modifying the script ... ouf! ... I ran into a userscript over at Greaseforkwhich that simply replaces DailyMotions's (html5) video player with "pure" html5, I mean Firefox's built-in html5 video player -> no ads, whatever dailyMotion's excentricities.

That's the trigger for this post, and an example as well to ask for the exception filters availability. But the trigger was DailyMotion. The video company doesn't yet haunt my nightmares but not far. What a pain...

Sorry, unable to make it short, not in my genes :)

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/a7fe367eecf2af16d07e8ec69743638cd2b05adf>.

`script:inject` filters can now be "excepted" like any other cosmetic filters. Using the current issue, this would be:

    #@#script:inject(1136.js)

**Comment by zymase** [comment]
Good to know, thanks for pointing it out, gorhill
