### ISSUE TITLE
cbc.ca - advertisements injected after page load

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#2300]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.cbc.ca/news/canada/newfoundland-labrador/elon-musk-tesla-newfoundland-interns-hired-1.4663270`

### Describe the issue

Ads are loaded above header and on the side

### Screenshot(s)

![cbc ca](https://user-images.githubusercontent.com/22258847/40127315-9d8632ac-591e-11e8-8472-8b9cf777bdc8.PNG)

### Versions

- Browser/version: Chrome 66.0.3359.181 (Official Build) (64-bit)
- uBlock Origin version: 1.16.5.101

### Settings

- Default settings & filters on test profile with uBlock Origin Extra also installed (No other extensions installed)

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
test
```
cbc.ca##[id^=risingstar]
cbc.ca##[id^=bigbox]
cbc.ca##.responsive
```

**Comment by yourduskquibbles** [comment]
These filters cosmetically hide the ads but it still seems like there is some javascript code running in the background because the page takes awhile to fully load and seems to rewrite the display a couple times.

Not sure if trying to eliminate that is out of scope though.

**Comment by mapx-** [comment]
We know about that code, gorhill will see what can be done
