### ISSUE TITLE
sofmap.com: nuisance

### ISSUE THREAD

**Issue by RyabDev** [uBlockOrigin/uAssets#23008]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sofmap.com/`

### Category

ads

### Description

Seems like almost none of the ads on this site are blocked

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Issue is blatant on the site

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 126158
 cosmetic: 45659
 scriptlet: 18990
 html: 1717
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37580-237, 1h.32m Δ
  ublock-badware: 7985-14, 1h.32m Δ
  ublock-privacy: 761-0, 1h.32m Δ
  ublock-unbreak: 2309-0, 1h.32m Δ
  easylist: 82825-545, 1h.32m Δ
  easyprivacy: 50395-866, 1h.32m Δ
  urlhaus-1: 8495-0, now
  plowe-0: 3765-1, now
  ublock-quick-fixes: 225-0, 1h.32m Δ
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8529 ms (selfie)
 maxAssetCacheWait: 125 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  sofmap.com: 1
  amazon.com: 4
  duckduckgo.com: 2
  google-analytics.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 Looks like self-promotion of a shopping site?

**Comment by mapx-** [comment]
@RyabDev you should also use the regional list: `jp: AdGuard Japanese`

**Comment by Yuki2718** [comment]
@RyabDev Self-promotion is out-of-scope for ad-blocking filters. Enable either EasyList – Other Annoyances or AdGuard – Other Annoyances in Filter lists pane.
