### ISSUE TITLE
text-compare.com: ads

### ISSUE THREAD

**Issue by hims056** [uBlockOrigin/uAssets#23014]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://text-compare.com/`

### Category

ads

### Description

The ads started showing today (22nd Mar 2024) only. It was working smoothly till now.

### Other extensions used

Google Translate, Google Dicstionary, ColorPick Eyedropper, GoFullPage, Imagus, Tempormonkey (no custom JS for this web page)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_22-3-2024_74052_text-compare com](https://github.com/uBlockOrigin/uAssets/assets/3929613/713c12c4-bc73-4289-ba49-1bbdc9a6944e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126416
 cosmetic: 45702
 scriptlet: 20324
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82838-16, now
  easyprivacy: 50401-8, now
  plowe-0: 3765-1183, 12m
  ublock-badware: 8027-147, now
  ublock-filters: 37429-359, now
  ublock-privacy: 770-5, now
  ublock-quick-fixes: 236-40, now
  ublock-unbreak: 2248-33, now
  urlhaus-1: 8670-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1505 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 39
 network:
  criteo.net: 3
  doubleclick.net: 1
  ezoic.net: 12
  ezojs.com: 12
  fuseplatform.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  html-load.com: 6
  quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon Ad-shield?

**Comment by JobcenterTycoon** [comment]
Yes, fixed now.

**A alternate way to block Ad-Shield ads is --> [microShield](https://github.com/List-KR/microShield) <--. Its a special userscript designed to block Ad-Shield related ads.**

**Comment by krystian3w** [comment]
But is domain locked instead work on whole Internet.
