### ISSUE TITLE
injora.com: breakage

### ISSUE THREAD

**Issue by Guden79** [uBlockOrigin/uAssets#23013]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.injora.com/`

### Category

breakage

### Description

Side open half a second, then it get completly white.
Need to push "loading again" to see it..
And this by every operation on this side.

It is only with de blocker, without blocker everything is fine.

Oh, sometimes the sid does not work at all with the blocker :-(

### Other extensions used

Language tool... or do you mean any other blocker? No other blocker used...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 128206
 cosmetic: 50657
 scriptlet: 18992
 html: 1721
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37572-161, 1h.33m Δ
  ublock-badware: 8036-15, 1h.33m Δ
  ublock-privacy: 767-0, 1h.33m Δ
  ublock-unbreak: 2307-0, 1h.33m Δ
  ublock-quick-fixes: 250-0, 1h.33m Δ
  easylist: 82825-651, 1h.33m Δ
  easyprivacy: 50397-870, 1h.33m Δ
  urlhaus-1: 8180-0, 1m
  plowe-0: 3765-0, 1m
  DEU-0: 7335-3, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 726 ms (selfie)
 maxAssetCacheWait: 160 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  injora.com: 11
  cloudflare.com: 2
  google-analytics.com: 1
  googletagmanager.com: 3
  shopifysvc.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||cloudflare.com/cdn-cgi/trace$xhr,domain=injora.com`

@ryanbr
