### ISSUE TITLE
dev.miuiflash.com: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#23012]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://devuploads.com/t722brlh89z9`

### Category

detection

### Description

https://devuploads.com/t722brlh89z9

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 127275
 cosmetic: 37594
 scriptlet: 19056
 html: 1722
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37929-386, 52m Δ
  ublock-badware: 8030-15, 52m Δ
  ublock-privacy: 767-1, 52m Δ
  ublock-unbreak: 2312-1, 52m Δ
  ublock-quick-fixes: 250-0, 52m Δ
  adguard-mobile: 9176-133, now
  easylist: 82825-16426, 52m Δ
  easyprivacy: 50397-870, 52m Δ
  urlhaus-1: 8180-0, now
  plowe-0: 3765-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 17120 ms (selfie)
 maxAssetCacheWait: 516 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##[id*="div-gpt-ad-"], [id*="google_ads_"]
  ###featuredimage
```
</details>

**Comment by BlazeFTL** [comment]
Test in my filters
```
jytechs.in,dev.miuiflash.com,djxmaza.in,thecubexguide.com#@#[id*="div-gpt-ad-"], [id*="google_ads_"]
jytechs.in,dev.miuiflash.com,djxmaza.in,thecubexguide.com##[id*="div-gpt-ad-"], [id*="google_ads_"]:style(clip-path: circle(0) !important;)

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
