### ISSUE TITLE
freemidi.org: detection

### ISSUE THREAD

**Issue by Fauxvert** [uBlockOrigin/uAssets#23017]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://freemidi.org/`

### Category

detection

### Description

![midi](https://github.com/uBlockOrigin/uAssets/assets/107963400/9230b62f-f32e-4c80-88ae-add191dda7f0)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 141801
 cosmetic: 52444
 scriptlet: 19149
 html: 1724
listset (total-discarded, last-updated):
 default:
  user-filters: 52-1, never
  ublock-filters: 37609-104, now
  ublock-badware: 8046-15, now
  ublock-privacy: 783-0, now
  ublock-unbreak: 2305-2, now
  easylist: 82838-842, 1h.27m Δ
  easyprivacy: 50401-1061, 1h.27m Δ
  plowe-0: 3763-0, now
  FRA-0: 22634-180, now
  urlhaus-1: 8890-0, now
  ublock-quick-fixes: 240-35, now
filterset (user): [array of 52 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 898 ms (selfie)
 maxAssetCacheWait: 528 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  translate.googleapis.com: 1
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce with default settings/lists.

> -[x] I did not answer truthfully to ALL the above checkboxes.

Please go through the steps again and carefully follow the instructions -- these are there for you to rule out that something else than uBO is causing this on your side.

The only way I was able to reproduce was after enabling DuckDuckGo Privacy Essentials.

**Comment by ItsProfessional** [comment]
>```yaml
>filterset (user): [array of 52 redacted]
>```

You are using a heavily customized configuration of uBO. We can't help such users. Create a fresh firefox profile, and use uBO with default settings and don't install other extensions.
