### ISSUE TITLE
lnk.lt: breakage

### ISSUE THREAD

**Issue by Vartotojas1234** [uBlockOrigin/uAssets#23016]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lnk.lt/straipsniai/lietuvoje/aviacijos-vasaros-sezonui-sugrizta-populiarios-kryptys/242577`

### Category

breakage

### Description

As a video quality 1080p only black screen and sound. With 720p, 576p everything is fine.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/uBlockOrigin/uAssets/assets/24992139/cacefe56-6427-4705-8cfb-6ec5a01a2029)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 264214
 cosmetic: 261914
 scriptlet: 51198
 html: 1993
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80177-6664, 1m
  adguard-spyware: 100268-640, 1m
  curben-phishing: 13940-3, 1m
  adguard-social: 22698-862, 1m
  adguard-cookies: 29016-78, 1m
  ublock-cookies-adguard: 1055-0, 1m
  adguard-popup-overlays: 26908-1710, 1m
  adguard-mobile-app-banners: 5095-1085, 1m
  adguard-other-annoyances: 14070-345, 1m
  adguard-widgets: 2424-1, 1m
  easylist-annoyances: 4450-125, 1m
  easylist-chat: 188-15, 1m
  [9 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 37602-444, 1m
  ublock-badware: 8036-15, 1m
  ublock-privacy: 766-0, 1m
  ublock-unbreak: 2305-0, 1m
  ublock-quick-fixes: 240-0, 1m
  easylist: 82838-956, 1m
  easyprivacy: 50401-32248, 1m
  urlhaus-1: 8670-0, 1m
  plowe-0: 3765-0, 1m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3589 ms
 maxAssetCacheWait: 2369 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  lnk.lt: 2
  doubleclick.net: 3
  gemius.pl: 6
  googletagmanager.com: 3
  jwpcdn.com: 2
  jwpltx.com: 1
  quantcast.com: 3
  stpd.cloud: 3
 extended:
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##.jw-settings-sharing
  ##.jw-submenu-sharing
  ##html:style(overflow:auto!important)
```
</details>

**Comment by gorhill** [comment]
This also happens without uBO installed. Please mind:

> - [x] If this is about a breakage or detection, **I have verified that it is caused by uBlock Origin and isn't a site issue.**

**Comment by mapx-** [comment]
site issue using firefox, chrome is working fine
