### ISSUE TITLE
chanrycz.com: breakage

### ISSUE THREAD

**Issue by chanrycz** [uBlockOrigin/uAssets#23011]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://chanrycz.com
```

### Description

I originally had an issue with uBO blocking the JS file for Cloudflare Apps on my website which was resolved (#12196). However, Cloudflare has announced the deprecation of Cloudflare Apps and I have now moved my custom inline HTML to Cloudflare Zaras so I'm now facing a similar issue where it's blocking the JS file (`
https://chanrycz.com/cdn-cgi/zaraz/s.js?z=JTdCJTIyZXhlY3V0ZWQlMjIlM0ElNUIlNUQlMkMlMjJ0JTIyJTNBJTIyUnlhbiUyMEMuJTIyJTJDJTIyeCUyMiUzQTAuMTkyMzM4NTg5MTQxMDY4OTQlMkMlMjJ3JTIyJTNBMTkyMCUyQyUyMmglMjIlM0ExMDgwJTJDJTIyaiUyMiUzQTkxMSUyQyUyMmUlMjIlM0E4MzYlMkMlMjJsJTIyJTNBJTIyaHR0cHMlM0ElMkYlMkZjaGFucnljei5jb20lMkYlMjIlMkMlMjJyJTIyJTNBJTIyJTIyJTJDJTIyayUyMiUzQTI0JTJDJTIybiUyMiUzQSUyMlVURi04JTIyJTJDJTIybyUyMiUzQS00ODAlMkMlMjJxJTIyJTNBJTVCJTVEJTdE`).

**Context about what I'm doing with Zaras**
I'm using Cloudflare Zaras to add inline HTML in order to mass-add Statuspage Embed (and other JS scripts) to some or all pages on the domain. uBO is blocking the JS for Cloudflare Zaras so the embed will not be able to show.

Steps to reproduce:
1. First go to https://chanrycz.com with uBO enabled
2. Run statusEmbedTest() in the console - function is not defined
3. Disable uBO and refresh the page
4. Run statusEmbedTest() again in the console - embed shows up with test message

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 141581
 cosmetic: 52413
 scriptlet: 20457
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 23185-36, now
  easylist: 82808-160, 58m Δ
  easyprivacy: 50396-252, 58m Δ
  plowe-0: 3765-1192, 10m
  ublock-badware: 7986-162, 58m Δ
  ublock-filters: 37399-429, 58m Δ
  ublock-privacy: 771-5, 58m Δ
  ublock-quick-fixes: 245-45, 58m Δ
  ublock-unbreak: 2250-37, 58m Δ
  urlhaus-1: 8180-0, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 294 ms (selfie)
 maxAssetCacheWait: 141 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  chanrycz.com: 1
  cloudflareinsights.com: 1
```
</details>

**Comment by ryanbr** [comment]
zaraz is a fingerprinting script, it should stay. Why are you relying on such a script? Improve your privacy.

**Comment by ItsProfessional** [comment]
> - [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).

@chanrycz You didn't read the EasyPrivacy policies. As stated by ryanbr, it's a fingerprinting script and won't be removed. Modify your website to use something else if you want it to work for users that have a content blocker.
