### ISSUE TITLE
deichmann.com: breakage

### ISSUE THREAD

**Issue by sppmasterspp** [uBlockOrigin/uAssets#23019]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deichmann.com/`

### Category

breakage

### Description

breakage if cosmetic filtering is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 170419
 cosmetic: 212062
 scriptlet: 51868
 html: 0
listset (total-discarded, last-updated):
 added:
  BGR-0: 1040-1, now
  RUS-0: 39594-9, 11m Δ
  adguard-cookies: 29018-48, now
  adguard-generic: 80187-657, now
  adguard-other-annoyances: 14073-48, now
  adguard-popup-overlays: 26911-420, now
  easylist-annoyances: 4450-258, now
  fanboy-cookiemonster: 50658-3868, now
  ublock-annoyances: 6933-263, 11m Δ
  ublock-cookies-easylist: 1055-1055, now
 default:
  user-filters: 0-0, never
  easylist: 82842-1496, 11m Δ
  easyprivacy: 50402-233, 11m Δ
  plowe-0: 3763-1196, now
  ublock-badware: 8052-254, 11m Δ
  ublock-filters: 37448-3957, 11m Δ
  ublock-privacy: 787-7, 11m Δ
  ublock-quick-fixes: 236-46, 11m Δ
  ublock-unbreak: 2248-101, 11m Δ
  urlhaus-1: 8890-0, 11m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 762 ms (selfie)
 maxAssetCacheWait: 354 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 no-cosmetic-filtering: true
 network:
  consentmanager.net: 2
  dse-tech.net: 1
```
</details>

**Comment by ItsProfessional** [comment]
No apparent breakage on my end. Provide a screenshot.

**Comment by sppmasterspp** [comment]
> No apparent breakage on my end. Provide a screenshot.

If cosmetic filtering is enabled, the whole screen is blank and there is no content, only white background, nothing else.
Disabling cosmetic filtering corrects it

**Comment by mapx-** [comment]
@sppmasterspp 

add

`deichmann.com#@#body,html:style(height: auto !important; overflow: auto !important)`

@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/f209884db4ea539a14550d265048a2b5dd38340d

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/63544952e11a3bb522c66138dbe4954f080dc2f3
