### ISSUE TITLE
[nsfw] 4hi.in: detection

### ISSUE THREAD

**Issue by dreminh** [uBlockOrigin/uAssets#23021]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://4hi.in/aNnoMc`

### Category

detection

### Description

every 4hi.in is detected add block , also doesnt load captcha img as well 
sorry for bad english

### Other extensions used

kaspersky but i turn off add block , other web work fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/23002308/56bfe212-c50a-43df-bee8-73bacf08bf64)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126672
 cosmetic: 45728
 scriptlet: 20346
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82864-16, now
  easyprivacy: 50402-8, now
  plowe-0: 3763-1182, now
  ublock-badware: 8052-147, now
  ublock-filters: 37448-360, now
  ublock-privacy: 787-5, now
  ublock-quick-fixes: 236-41, now
  ublock-unbreak: 2248-33, now
  urlhaus-1: 8890-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 154 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  bowlingunauthorized.com: 5
  googletagmanager.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
