### ISSUE TITLE
torrentgalaxy.to: breakage

### ISSUE THREAD

**Issue by deadman616** [uBlockOrigin/uAssets#23023]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://torrentgalaxy.to/`

### Category

breakage

### Description

The Hot Picks on the left side of the website are missing when I login but when I log out there back. Please fix this problem.

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 126662
 cosmetic: 45708
 scriptlet: 19012
 html: 1725
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37616-265, 18m Δ
  ublock-badware: 8056-15, 18m Δ
  ublock-privacy: 783-0, 18m Δ
  ublock-unbreak: 2305-0, 18m Δ
  ublock-quick-fixes: 240-0, 18m Δ
  easylist: 82864-547, 18m Δ
  easyprivacy: 50402-833, 18m Δ
  urlhaus-1: 8890-0, 18m
  plowe-0: 3763-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10217 ms (selfie)
 maxAssetCacheWait: 2311 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##body > [id] > div:first-child > div:first-child > div:first-ch…
  ##+js(abort-on-stack-trace, String.prototype.charCodeAt, $)
```
</details>

**Comment by JobcenterTycoon** [comment]
Was able to reproduce. Happened because the website code is different with a account (no ads appear) so a filter matched a wrong element.
