### ISSUE TITLE
hindustantimes.com: nuisance

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#23037]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.hindustantimes.com/
```

### Description

Google account signup annoyance at the top right corner appearing a few seconds after webpage is loaded. It would usually be blocked by `###credential_picker_container` rule in easylist other annoyances but it can't happen because of `@@||hindustantimes.com^$generichide` in Ublock - ads filter.

That signup dialog appears every single time. If it does not appear browse around this website a bit.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 141050
 cosmetic: 95544
 scriptlet: 29240
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  curben-phishing: 14309-0, 18h.2m
  easylist-annoyances: 4432-32, 5d.21h.46m
  fanboy-cookiemonster: 66374-16164, 5d.21h.46m
  ublock-annoyances: 6936-76, 6m Δ
  ublock-cookies-easylist: 1048-1045, 5d.21h.46m
 default:
  user-filters: 1-0, never
  easylist: 82720-16, 6m Δ
  easyprivacy: 50406-19, 6m Δ
  ublock-badware: 8082-144, 6m Δ
  ublock-filters: 37448-375, 5m
  ublock-privacy: 784-6, 6m Δ
  ublock-quick-fixes: 235-32, 6m Δ
  ublock-unbreak: 2247-37, 6m Δ
  urlhaus-1: 8840-0, 18h.2m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 844 ms (selfie)
 maxAssetCacheWait: 432 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 11
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 2
  htmedia.in: 1
  pubmatic.com: 1
  scorecardresearch.com: 1
  taboola.com: 1
  webengage.com: 1
 extended:
  ###divshopnowRight
  ##.affilaite-widget
  ##.headBanner
  ##.m_headBanner
  ##.rgtAdSection
  ###gdprpopup
  ##.blackOverlay
  ##.desktopAd
  ##.storyAd
  ##[class^="adHeight"]
  ##[class^="adMinHeight"]
  ##div[id^="div-gpt-ad"]
  ##body:style(overflow: auto !important;)
  ##+js(prevent-fetch, adsbygoogle.js)
  ##+js(remove-attr, onclick, a[href][onclick^="getFullStory"])

```
</details>

**Comment by mapx-** [comment]
it's about

`accounts.google.com###credentials-picker-container`

but using it "sign in" does not work anymore

**Comment by mapx-** [comment]
removed
