### ISSUE TITLE
animevietsub.io: popups

### ISSUE THREAD

**Issue by NnQuang20** [uBlockOrigin/uAssets#23030]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://animevietsub.io/`

### Category

popups

### Description

sometimes it opens another tab when I click on anywhere on the screen

### Other extensions used

J2TEAM security. 
Who Deleted Me

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 126814
 cosmetic: 45782
 scriptlet: 20355
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 83101-16, now Δ
  easyprivacy: 50405-8, now Δ
  plowe-0: 3763-1182, now
  ublock-badware: 8055-147, now Δ
  ublock-filters: 37458-361, now Δ
  ublock-privacy: 787-5, now Δ
  ublock-quick-fixes: 238-41, now Δ
  ublock-unbreak: 2248-33, now Δ
  urlhaus-1: 8840-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 267 ms (selfie)
 maxAssetCacheWait: 95 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  google.com: 1
  googletagmanager.com: 1
  intorterraon.com: 2
  rtmark.net: 4
  youtube.com: 1
 extended:
  ##.ads-300
  ##.ads_player
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by mapx-** [comment]
Enable the regional list [vn: ABPVN List](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=VIE-1)
