### ISSUE TITLE
[nsfw] new.lewd.ninja: detection

### ISSUE THREAD

**Issue by RumeZucabr** [uBlockOrigin/uAssets#23033]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://new.lewd.ninja/game/178604-disruption-v012-public-gaaby`

### Category

detection

### Description

Adblock Detected (code: 421) is happening again. Sometimes there's a brief delay before it kicks in.

### Other extensions used

Greasemonkey (only one active script not on this website), Allow Right Click (not activated)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 126556
 cosmetic: 45685
 scriptlet: 19007
 html: 1720
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37572-161, 7m
  ublock-badware: 8059-15, 7m
  ublock-privacy: 783-0, 7m
  ublock-unbreak: 2305-0, 7m
  ublock-quick-fixes: 242-0, 7m
  easylist: 82808-639, 7m
  easyprivacy: 50396-833, 7m
  urlhaus-1: 8840-0, 7m
  plowe-0: 3763-0, 7m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 611 ms
 maxAssetCacheWait: 236 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  lewd.ninja: 1
  0i0i0i0.com: 2
  cloudflareinsights.com: 2
  google-analytics.com: 1
  jads.co: 9
  tapioni.com: 2
 extended:
  ##a.navbar-item.is-hidden-desktop-only
  ##div[id][style*="height:1px;display:inline-block;clear:none;pos…
  ##div[tabindex="-1"]:not(.modal.is-active.is-image-modal, .viewe…
  ##+js(no-setInterval-if, atob)
  ##+js(no-setTimeout-if, setAntiAb)
  ##+js(addEventListener-defuser, click, shouldShow)
```
</details>

**Comment by D4niloMR** [comment]
It did work, it is that they have already updated.

**Comment by rakleed** [comment]
timer on `https://new.lewd.ninja/external/game/250298/af0dd33c308279a1ebf93a35b1134d7a1f8e554f7358354abc325f927b10e157`

<details><summary>Screenshot</summary>
<p>

![Image](https://github.com/user-attachments/assets/53b556d3-fb0a-44bf-b08b-47723d6bd2de)

</p>
</details> 

<details><summary>Details</summary>
<p>

```yaml
uBlock Origin: 1.63.2
Chromium: 135
filterset (summary):
 network: 197349
 cosmetic: 213737
 scriptlet: 56854
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-badware: null
 added:
  adguard-generic: 97280-657, now
  adguard-mobile: 10815-136, now
  adguard-spyware-url: 2042-137, now
  adguard-cookies: 33739-100, now
  ublock-cookies-adguard: 4081-25, now
  adguard-social: 23874-58, now
  adguard-popup-overlays: 29042-2306, now
  adguard-mobile-app-banners: 5971-22, now
  adguard-other-annoyances: 14762-403, now
  adguard-widgets: 2930-6, now
  ublock-annoyances: 5962-56, now
  RUS-0: 41122-606, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40150-3646, now
  ublock-privacy: 2797-27, now
  ublock-unbreak: 2565-0, now
  ublock-quick-fixes: 248-0, now
  easylist: 69115-1908, now
  easyprivacy: 53537-965, now
  urlhaus-1: 34105-0, now
  plowe-0: 3452-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 848 ms
 maxAssetCacheWait: 274 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  lewd.ninja: 2
  adguard.org: 2
  cloudflareinsights.com: 1
  google-analytics.com: 2
  googletagmanager.com: 1
  jads.co: 20
  lewd.ws: 1
  tapioni.com: 1
 extended:
  ##a.navbar-item.is-hidden-desktop-only
  ##.navbar-start a[target="_blank"]
  ##iframe[width="728"][height="90"]
  ##+js(addEventListener-defuser, click, shouldShow)
  ##+js(prevent-fetch, ads.juicyads.com)
  ##img[width="728"][height="90"]
```

</p>
</details>
