### ISSUE TITLE
eurobaustoff.com: breakage

### ISSUE THREAD

**Issue by repofodu** [uBlockOrigin/uAssets#23044]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.eurobaustoff.com/de/das-unternehmen/unternehmen/gesellschafter/
```

### Description

The website needs consent to show Google Maps. Clicking "Consent-Tool öffnen" does not open the consent tool and instead redirects to
`https://www.eurobaustoff.com/de/das-unternehmen/unternehmen/gesellschafter/www.eurobaustoff.com/#CCM.openWidget`
I have enabled (some) easylist and ublock annoyances filters. Is it still okay to submit an issues here? If not where should I report it instead?

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/164751929/ea8bf108-4478-495b-b70e-99ee0ed6c8d8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 131507
 cosmetic: 107590
 scriptlet: 27726
 html: 1981
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4450-19, 2d.53m
  fanboy-cookiemonster: 50658-223, 2d.53m
  ublock-cookies-easylist: 1055-0, 2d.53m
  easylist-newsletters: 7144-10, 2d.53m
  ublock-annoyances: 6881-1086, 1h.38m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 37608-156, 1h.30m
  ublock-badware: 8086-15, 30m Δ
  ublock-privacy: 780-0, 1h.30m
  ublock-unbreak: 2306-0, 1h.30m
  ublock-quick-fixes: 239-0, 1h.30m
  easylist: 82720-669, 1h.38m Δ
  easyprivacy: 50406-898, 1h.38m Δ
  urlhaus-1: 8600-0, 1h.38m
  plowe-0: 3763-0, 2d.1h.20m
  DEU-0: 7346-4, 1h.38m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 142 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
add

@@||cookiemanager.onm.de^$domain=eurobaustoff.com

@ryanbr
