### ISSUE TITLE
jiocinema.com: ads

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#23042]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.jiocinema.com/sports/cricket/gujarat-titans-vs-mumbai-indians/3930960`

### Category

ads

### Description

Video type advertisement 

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 123
filterset (summary):
 network: 127575
 cosmetic: 37676
 scriptlet: 19073
 html: 1726
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  ublock-filters: 37965-408, now
  ublock-badware: 7934-15, now
  ublock-privacy: 780-1, now
  ublock-unbreak: 2311-1, now
  ublock-quick-fixes: 239-0, now
  adguard-mobile: 9179-133, now
  easylist: 82835-16420, now
  easyprivacy: 50406-841, now
  urlhaus-1: 8600-0, now
  plowe-0: 3763-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 19491 ms (selfie)
 maxAssetCacheWait: 998 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  adsmoloco.com: 1
  clevertap-prod.com: 19
  go-mpulse.net: 2
  googletagmanager.com: 3
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  litix.io: 12
  mparticle.com: 1
  sentry.io: 3
  voot.com: 1
```
</details>

**Comment by mapx-** [comment]
indian ip, desktop / mobile tested for a movie
`https://www.jiocinema.com/movies/hanuman/3926455/watch`

no video ads

if I disable uBO I get media ads like:

```
https://r2---sn-i3b7knsd.c.2mdn.net/videoplayback/id/5279e9c74613a45d/itag/37/source/web_video_ads/ctier/L/acao/yes/ip/0.0.0.0/ipbits/0/expire/3855455498/sparams/acao,ctier,expire,id,ip,ipbits,itag,mh,mip,mm,mn,ms,mv,mvi,pl,source/signature/6137FDF2C7EF0A38AF07448A7AB58AFA34AA02B6.5EF4AF441564CE99B9DF02F849558C6BFDF9CC91/key/cms1/cms_redirect/yes/mh/Uc/mip/176.227.240.65/mm/42/mn/sn-i3b7knsd/ms/onc/mt/1712855803/mv/m/mvi/2/pl/24/file/file.mp4
https://gcdn.2mdn.net/videoplayback/id/5279e9c74613a45d/itag/37/source/web_video_ads/ctier/L/acao/yes/ip/0.0.0.0/ipbits/0/expire/3855455498/sparams/id,itag,source,ctier,acao,ip,ipbits,expire/signature/280BC5707F231D770E9F74EBA7C1829912C18AF8.148C365FFC6E8A25BA7CB78680E46F3E58B45EC9/key/ck2/file/file.mp4
```

**Comment by mapx-** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/6438ca9e-a220-4f9f-97f4-ca93c211efd7)

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/commit/931f44ae16b4f48a68878283d5c137db007f2998
