### ISSUE TITLE
themarker.com: detection

### ISSUE THREAD

**Issue by sha-265** [uBlockOrigin/uAssets#23041]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.themarker.com/allnews/2024-03-24/ty-article/0000018e-7064-ddf4-a3de-78f685210000`
`https://www.haaretz.co.il/magazine/underthesun/2024-03-20/ty-article/.highlight/0000018e-5b71-d9a8-a5ae-fffd81630000`

### Category

detection

### Description

A lot of article pages (the above are just examples) in TheMarker/Haaretz detect uBO, and blocking the page by redirecting to:
`https://www.themarker.com/hblocked` and `https://www.haaretz.co.il/hblocked`

### Other extensions used

Bypass Paywalls Clean (tried to disable)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4103710/3a749bae-f058-426c-a2f6-5331355b8758)
![image](https://github.com/uBlockOrigin/uAssets/assets/4103710/bb10cd7a-be7f-4cc1-91bf-27fbb7e9eda2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 137195
 cosmetic: 46874
 scriptlet: 19072
 html: 1734
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-spyware-url: 1485-106, now
  block-lan: 61-0, now
  fanboy-thirdparty_social: 68-0, now
  dpollock-0: 11664-1, now
  ISR-0: 1874-0, now
 default:
  user-filters: 14-0, never
  ublock-filters: 37608-165, 5m Δ
  ublock-badware: 8086-15, 5m Δ
  ublock-privacy: 780-0, 5m Δ
  ublock-unbreak: 2304-1, 5m Δ
  ublock-quick-fixes: 239-0, 5m Δ
  easylist: 82720-501, 5m Δ
  easyprivacy: 50406-155, 5m Δ
  urlhaus-1: 8600-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 13 redacted]
 removed:
  edge-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 21 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3855 ms
 maxAssetCacheWait: 251 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  ads-twitter.com: 2
  analysis.fi: 2
  brandmetrics.com: 2
  chartbeat.com: 1
  doubleclick.net: 4
  dxmdp.com: 2
  facebook.net: 1
  fastly.net: 1
  firstimpression.io: 2
  geoedge.be: 1
  googletagmanager.com: 2
  licdn.com: 1
  outbrain.com: 2
  taboola.com: 1
  valuad.cloud: 1
  youtube.com: 1
 extended:
  ##[href^="https://www.haaretz.co.il/labels/"]
  ##+js(addEventListener-defuser, , hblocked)
  ##+js(set-constant, showAds, true)
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by sha-265** [comment]
tested with default settings. still same problem

**Comment by sha-265** [comment]
```uBlock Origin: 1.56.0
Firefox: 125
filterset (summary):
 network: 119207
 cosmetic: 45534
 scriptlet: 18895
 html: 2080
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37829-116, never
  ublock-badware: 7895-14, never
  ublock-privacy: 742-0, never
  ublock-unbreak: 2260-0, never
  ublock-quick-fixes: 129-0, never
  easylist: 81272-624, never
  easyprivacy: 50221-50, never
  urlhaus-1: 3355-0, never
  plowe-0: 3782-814, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2070 ms
 maxAssetCacheWait: 9 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  ads-twitter.com: 2
  analysis.fi: 1
  brandmetrics.com: 1
  chartbeat.com: 1
  doubleclick.net: 3
  dxmdp.com: 1
  facebook.net: 1
  fastly.net: 1
  firstimpression.io: 1
  geoedge.be: 1
  googletagmanager.com: 1
  licdn.com: 1
  outbrain.com: 2
  pushwoosh.com: 1
  taboola.com: 1
  valuad.cloud: 1
  youtube.com: 1
 extended:
  ##.banner-ad
  ##div[data-adunit]
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```

**Comment by ItsProfessional** [comment]
I'm able to reproduce.

**Comment by sha-265** [comment]
> now enable **il: easylist Hebrew** filter list from ublock settings > filter lists > regions & languages then click apply changes subsequently click clock button next to each filter list you enabled ,this will update each list to latest (as i see from your config that filter update never took)

not working

**Comment by mapx-** [comment]
I'm able to reproduce the detection only disabling the regional list.

@sha-265 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable tracking protection in firefox
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
