### ISSUE TITLE
loja.ibrath.com: privacy

### ISSUE THREAD

**Issue by t7winko** [uBlockOrigin/uAssets#23045]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://loja.ibrath.com/blogs/244-significado/como-desbloquear-agentes-valorant`

### Category

privacy

### Description

a

### Other extensions used

a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 127475
 cosmetic: 49500
 scriptlet: 20729
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 82856-16, 22m
  easyprivacy: 50405-8, 22m
  plowe-0: 3763-1182, 22m
  spa-1: 5445-71, 23m
  ublock-badware: 7941-140, 23m
  ublock-filters: 37443-372, 23m
  ublock-privacy: 784-5, 23m
  ublock-quick-fixes: 235-34, 23m
  ublock-unbreak: 2249-36, 23m
  urlhaus-1: 8600-0, 23m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1291 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 25
 network:
  ibrath.com: 10
  ampproject.org: 2
  avcdn.net: 1
  facebook.net: 2
  google-analytics.com: 1
  google.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  pinimg.com: 1
  tiktok.com: 1
  youtube.com: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
> Description a

provide real info about your issue

**Comment by ItsProfessional** [comment]
It's a spam issue created via uBO's report button.

- > - [X] I did not answer truthfully to **ALL** the above checkboxes.
- > a
