### ISSUE TITLE
decrypt.day: detection

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#23049]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://decrypt.day/app/id544007664`

### Category

detection

### Description

Adblock detection 

### Other extensions used

FastForward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2024-03-24 at 10 11 42 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/558e40a6-e632-4499-9582-c23bb2d82bb5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 171830
 cosmetic: 227878
 scriptlet: 50749
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77537-135, now
  https://malware-filter.gitlab.io/malware-filter/pup-filter.txt: 0-0, never
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97841-22825, now
  adguard-generic: 80194-553, now
  adguard-mobile: 9179-63, now
  adguard-spyware-url: 1485-5, now
  block-lan: 61-0, now
  curben-phishing: 14101-0, now
  fanboy-cookiemonster: 50683-50683, now
  ublock-annoyances: 6934-267, now
 default:
  user-filters: 0-0, never
  easylist: 83198-1561, now
  easyprivacy: 50408-271, now
  plowe-0: 3763-1267, now
  ublock-badware: 7971-251, now
  ublock-filters: 37442-3950, now
  ublock-privacy: 778-108, now
  ublock-quick-fixes: 235-39, now
  ublock-unbreak: 2247-102, now
  urlhaus-1: 8795-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2715 ms
 maxAssetCacheWait: 1666 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
 extended:
  ##+js(no-fetch-if, adsbygoogle)
```
</details>

**Comment by jimmysofat6864** [comment]
duplicate

**Comment by JobcenterTycoon** [comment]
Wait a few seconds before you click on download. Their anti adblock script is slow and buggy.

**Comment by jimmysofat6864** [comment]
> Wait a few seconds before you click on download. Their anti adblock script is slow and buggy.

I tried that but it didn't work. Do I need to add anything to my custom filters?
