### ISSUE TITLE
[nsfw] koyso.com: detection

### ISSUE THREAD

**Issue by xiaoxiongweihu** [uBlockOrigin/uAssets#23055]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://koyso.com/`

### Category

detection

### Description

This site detects AD blocking plugins

### Other extensions used

I have used the AD gurard plugin and it will also be detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![批注 2024-03-26 031750](https://github.com/uBlockOrigin/uAssets/assets/114919604/5f5e97cc-9e86-470a-ad49-d5e3f18b0ec9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 141984
 cosmetic: 56287
 scriptlet: 20524
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 25413-127, 20m
  easylist: 83384-41, 6m Δ
  easyprivacy: 50409-22, 6m Δ
  plowe-0: 3763-1184, 19m
  ublock-badware: 8021-140, 6m Δ
  ublock-filters: 37427-380, 19m
  ublock-privacy: 780-5, 6m Δ
  ublock-quick-fixes: 234-33, 20m
  ublock-unbreak: 2247-34, 20m
  urlhaus-1: 9235-0, 20m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 201 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  clarity.ms: 1
  eecjrmd.com: 1
  googletagmanager.com: 1
 extended:
  ##.google-ad:not(.testAd)
```
</details>

**Comment by mapx-** [comment]
add

`@@||koyso.com^$ghide`

@cjx82630
