### ISSUE TITLE
baeldung.com: detection

### ISSUE THREAD

**Issue by YouriStudent** [uBlockOrigin/uAssets#23058]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.baeldung.com/spring-classpath-file-access`

### Category

detection

### Description

Shows a message to please disable your adblocker

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/88655038/af678a22-ec7d-4e1d-a17a-c9039b72646d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 127581
 cosmetic: 45774
 scriptlet: 19003
 html: 1724
listset (total-discarded, last-updated):
 default:
  user-filters: 21-0, never
  ublock-filters: 37571-162, 1h.58m Δ
  ublock-badware: 7980-15, 1h.58m Δ
  ublock-privacy: 776-0, 1h.58m Δ
  ublock-unbreak: 2304-0, 1h.58m Δ
  ublock-quick-fixes: 238-0, 1h.58m Δ
  easylist: 83469-639, 1h.58m Δ
  easyprivacy: 50409-832, 1h.58m Δ
  urlhaus-1: 9350-0, now
  plowe-0: 3763-0, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1075 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  baeldung.com: 1
  duckduckgo.com: 1
  facebook.net: 1
  frspecifics.com: 1
  getdrip.com: 1
  googletagmanager.com: 2
  pub.network: 4
 extended:
  ##.topAdContainer
  ##[data-freestar-ad]:not(:empty)
```
</details>

**Comment by stephenhawk8054** [comment]
Test in a new Firefox profile with only uBO and its default settings.

**Comment by YouriStudent** [comment]
> Test in a new Firefox profile with only uBO and its default settings.

In a new profile with everything default I got the same thing

**Comment by stephenhawk8054** [comment]
@YouriStudent Can you go to `about:addons` page (type in URL bar) and screenshot it here?

**Comment by YouriStudent** [comment]
> @YouriStudent Can you go to `about:addons` page (type in URL bar) and screenshot it here?

![image](https://github.com/uBlockOrigin/uAssets/assets/88655038/7592f0fa-6a77-47b2-a933-cf59849ef916)
![image](https://github.com/uBlockOrigin/uAssets/assets/88655038/b42f731f-922c-4c03-b118-095b3f87d262)

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue.

**Comment by YouriStudent** [comment]
Maybe I was to fast with opening the page after installing the extension in a new profile, A reloaded it without cache its fixed now on my PC.
