### ISSUE TITLE
amedia.site: ads

### ISSUE THREAD

**Issue by FollowerWind** [uBlockOrigin/uAssets#23057]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://amedia.site/112-prizrak-v-dospehah-sindrom-odinochki.html`

### Category

[unknown].

### Description

The sound of the advertisement does not disappear.
When you turn on the video, there is a sound of an advertisement, the video image of which is missing. This is specifically related to the player used by different sites.
Even this morning on the 26th03, there was no such problem.

### Other extensions used

They are not there

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 95
filterset (summary):
 network: 144989
 cosmetic: 66345
 scriptlet: 20374
 html: 1740
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37571-253, 1h.28m Δ
  ublock-badware: 7980-15, 1h.28m Δ
  ublock-privacy: 776-0, 1h.28m Δ
  ublock-unbreak: 2304-0, 1h.28m Δ
  ublock-quick-fixes: 238-0, 1h.28m Δ
  easylist: 83469-557, 1h.27m Δ
  easyprivacy: 50409-945, 1h.28m Δ
  urlhaus-1: 9350-0, now
  plowe-0: 3763-0, now
  RUS-0: 39531-14, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 426 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 61
 network:
  amedia.site: 6
  aj1907.online: 6
  buzzoola.com: 3
  jsdelivr.net: 4
  mn230126pb.com: 1
  moe.video: 6
  moviead55.ru: 9
  sape.ru: 6
  serving-sys.ru: 3
  snsv.ru: 9
  traffer.net: 3
  yadro.ru: 1
  yandex.ru: 4
 extended:
  ##.mfp-hide
  ##div[id^="yandex_rtb"]
```
</details>

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/64934fac855867c64154b5be38231f6f62ff5a09
