### ISSUE TITLE
burningwhee1s.blogspot.com: popups

### ISSUE THREAD

**Issue by iomollie** [uBlockOrigin/uAssets#23056]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://burningwhee1s.blogspot.com/2024/03/indycar-2024-thermal-1-million-challenge.html`

### Category

popups

### Description

when double clicking a video to make it fullscreen it opens up unwanted tabs in the web browser

### Other extensions used

Hola VPN
Pouch
Metamask
Go Back With Backspace
Return Youtube dislike button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 134830
 cosmetic: 129746
 scriptlet: 23724
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29040-33, now
  adguard-mobile-app-banners: 5107-7, now
  adguard-popup-overlays: 26924-68, now
  adguard-social: 22707-786, now
  adguard-widgets: 2430-3, now
  easylist-newsletters: 7146-484, now
  easylist-notifications: 2970-1200, now
  fanboy-thirdparty_social: 68-3, now
  ublock-cookies-adguard: 1062-13, now
 default:
  user-filters: 2-0, never
  easylist: 83386-55, 1h.26m Δ
  easyprivacy: 50409-112, 1h.26m Δ
  plowe-0: 3763-1183, 26m
  ublock-badware: 8021-140, 1h.26m Δ
  ublock-filters: 37407-441, 1h.27m Δ
  ublock-privacy: 780-6, 1h.26m Δ
  ublock-quick-fixes: 234-33, 1h.27m Δ
  ublock-unbreak: 2247-34, 1h.27m Δ
  urlhaus-1: 9350-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 805 ms
 maxAssetCacheWait: 423 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 170
 network:
  google.com: 14
  googlesyndication.com: 1
  mail.ru: 136
  scorecardresearch.com: 13
  tns-counter.ru: 6
 extended:
  ##ins.adsbygoogle
  ##.post-share-buttons
  ##.share-button
  ##.b-video-viral-panel
  ##+js(set-constant, Object.prototype.isAdblockEnable, noopFunc)
  ###system_msg
  ##+js(set-constant, window.Unauthorized2, undefined)
  ##+js(set-constant, window.PageBottomBanners.initUnauthBanner, n…
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
There are many videos and many players. Describe exactly which one you see the issue.

**Comment by iomollie** [comment]
Any video i double click on opens another tab.

**Comment by stephenhawk8054** [comment]
Just give exact video and exact player. The problem is we can't reproduce with "any" video. We need exact details for easier confirming.

**Comment by mapx-** [comment]
I was able to reproduce it, it seems RU AdList has a filter for it:

`||r.mail.ru/*=videoplayer$popup,domain=my.mail.ru`

It seems `my.mail.ru##+js(nowoif)` is working too

@dimisa-RUAdList is this something you already took care of ?

**Comment by dimisa-RUAdList** [comment]
@mapx- 
That's right. The RU AdList for this player contains the following rules:
```
||r.mail.ru/*=videoplayer$popup,domain=my.mail.ru
my.mail.ru##html.window-loaded .b-video-backscreen
my.mail.ru##html.window-loaded .b-video-controls__inside-play-button:style(visibility: visible !important; opacity: 0 !important; width: 100% !important; height: 100% !important; top: 0 !important; left: 0 !important)
```

**Comment by mapx-** [comment]
@iomollie add the filters @dimisa-RUAdList wrote above or subscribe the russian list: RU AdList

**Comment by iomollie** [comment]
Thank you all for the help and replies!
