### ISSUE TITLE
z-lib.io: breakage

### ISSUE THREAD

**Issue by GITHUBTRASHACCOUNT** [uBlockOrigin/uAssets#23051]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://z-lib.io/s/test?`
`https://z-lib.io/`

### Category

breakage

### Description

the webpage breaks and dosen't load it think its has to do with something about scipt inline excution not working on the website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/115583890/87dc0785-efeb-4621-8eb3-e2aed31c02b1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 130982
 cosmetic: 114648
 scriptlet: 30152
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29033-33, 1h.40m
  fanboy-cookiemonster: 66692-19839, 39m
  ublock-annoyances: 6935-76, 39m Δ
  ublock-cookies-adguard: 1060-1060, 39m
  ublock-cookies-easylist: 1060-1060, 39m
 default:
  user-filters: 0-0, never
  easylist: 83347-21, 39m Δ
  easyprivacy: 50408-12, 39m Δ
  plowe-0: 3763-1183, now
  ublock-badware: 8021-140, 39m Δ
  ublock-filters: 37430-373, 39m Δ
  ublock-privacy: 780-5, 39m Δ
  ublock-quick-fixes: 234-33, 39m Δ
  ublock-unbreak: 2247-35, 39m Δ
  urlhaus-1: 8795-0, 1h.40m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2235 ms (selfie)
 maxAssetCacheWait: 1488 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 20
 network:
  z-lib.io: 16
  google.com: 2
  translate.googleapis.com: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
The real z-library seems to be `https://singlelogin.re/`
