### ISSUE TITLE
rawstory.com: nuisance

### ISSUE THREAD

**Issue by LittleBuzzon** [uBlockOrigin/uAssets#23059]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

No matter how many times I pick and block popups, they keep coming up on screen.

### A specific URL where the issue occurs.

```yaml
https://www.rawstory.com/alex-jones-baltimore-bridge/
```

### Steps to Reproduce

Go to rawstory.com
Click on any article
Read and scroll thru article
Popups should appear

### Expected behavior

block element

### Actual behavior

Popups return

### uBO version

?

### Browser name and version

firefox 124.0.1

### Operating System and version

windows 10 32 bit

**Comment by gorhill** [comment]
Not a popup, it's a paywall overlay.
