### ISSUE TITLE
ads / countdown

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#2306]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://micloudfiles.com/6cg1cnbxzhwb`

### Describe the issue

sometimes ads 
countdown of 1min
### Screenshot(s)

![screenshot 11](https://user-images.githubusercontent.com/20338483/40135679-85de4b90-5963-11e8-8a12-1d227177bbca.png)

### Versions

- Browser/version: chrome/firefox latest stable
- uBlock Origin version: stable latest

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

tried
micloudfiles.com##script:inject(nano-setInterval-booster.js) with no success

**Comment by mapx-** [comment]
I tried 
`micloudfiles.com##script:inject(nano-setTimeout-booster.js)`

apparently it works but then the page is saying skipped countdown
