### ISSUE TITLE
coryzen.com: detection

### ISSUE THREAD

**Issue by Noorhasanrz** [uBlockOrigin/uAssets#23060]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://coryzen.com/moments-introduces-several-versions-of-blockchain-technology/`

### Category

detection

### Description

This is link shortener page
 Original url is `https://coryzen.com/?go=3aa0f96a`

### Other extensions used

Tempermonkey

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/145339882/16846d3b-055f-4fa7-a411-9c3ec88fa40a

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 128449
 cosmetic: 37682
 scriptlet: 19070
 html: 1725
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37928-375, 3m Δ
  ublock-badware: 7979-15, 3m Δ
  ublock-privacy: 776-1, 3m Δ
  ublock-unbreak: 2309-1, 3m Δ
  ublock-quick-fixes: 244-0, 3m Δ
  adguard-mobile: 9191-133, now
  easylist: 83519-16427, 3m Δ
  easyprivacy: 50409-869, 3m Δ
  urlhaus-1: 8780-0, now
  plowe-0: 3763-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1601 ms
 maxAssetCacheWait: 524 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 5
  googlesyndication.com: 4
  googletagmanager.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by gorhill** [comment]
This works for me:

    coryzen.com##+js(no-fetch-if, googlesyndication.com/pagead/js/adsbygoogle.js)

**Comment by BlazeFTL** [comment]
Site Seems Broken To Me...After 3rd Page There Is No Content
```
coryzen.com##+js(no-fetch-if, ads)
coryzen.com##+js(nano-sib, wpsafelinkCounter, *, 0.02)
coryzen.com##+js(nano-sib, , 5000)
coryzen.com###overlay, #masthead, #foo, #primary
coryzen.com###page:style(min-height: inherit! important;)

**Comment by mapx-** [comment]
to be discussed here: https://github.com/uBlockOrigin/uAssets/discussions/17361
