### ISSUE TITLE
fplstatistics.com detection

### ISSUE THREAD

**Issue by Columbo1867** [uBlockOrigin/uAssets#23061]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
fplstatistics.com
```

### Description

Website does not show content when uBlock is enabled. Please see screenshots of it working with uBlock disabled, and what happens when uBlock is enabled. Thank you 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/67225952/da2bc9cb-6f14-4b81-af0d-b93f123ae9cd)

![image](https://github.com/uBlockOrigin/uAssets/assets/67225952/81d27227-def6-4503-8405-9ef7924d235f)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 124572
 cosmetic: 45801
 scriptlet: 20341
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 default:
  user-filters: 2-0, never
  easylist: 83544-18, 23m Δ
  easyprivacy: 50409-10, 23m Δ
  ublock-badware: 7981-140, 23m Δ
  ublock-filters: 37410-359, 23m Δ
  ublock-privacy: 780-5, 23m Δ
  ublock-quick-fixes: 242-35, 23m Δ
  ublock-unbreak: 2247-33, 23m Δ
  urlhaus-1: 8780-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 316 ms (selfie)
 maxAssetCacheWait: 112 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 14
 network:
  googlesyndication.com: 8
  gstatic.com: 4
  paypalobjects.com: 2
 extended:
  ##ins.adsbygoogle

```
</details>

**Comment by BlazeFTL** [comment]
Try
```
fplstatistics.com##+js(nostif, _0x)
fplstatistics.com###divAdvert
fplstatistics.com##[href^="https://betterfpl.com/"]
fplstatistics.com##[href="https://fantasyfootballhub.co.uk/join/"]

**Comment by Columbo1867** [comment]
> Try
> 
> ```
> fplstatistics.com##+js(nostif, _0x)
> fplstatistics.com###divAdvert
> fplstatistics.com##[href^="https://betterfpl.com/"]
> fplstatistics.com##[href="https://fantasyfootballhub.co.uk/join/"]
> ```

Thank you for your help, but this doesn't bring up the content of the website that shows without uBlock on.
