### ISSUE TITLE
google.com: detection

### ISSUE THREAD

**Issue by Vietnam0509** [uBlockOrigin/uAssets#23066]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/search?q=d%E1%BB%8Bch&rlz=1C1KNTJ_viVN1058VN1058&oq=d%E1%BB%8Bch&gs_lcrp=EgZjaHJvbWUqDggAEEUYOxhDGIAEGIoFMg4IABBFGDsYQxiABBiKBTIOCAEQIxgTGCcYgAQYigUyDQgCEAAYgwEYsQMYgAQyBwgDEAAYgAQyDQgEEAAYgwEYsQMYgAQyBwgFEAAYgAQyBggGEEUYPTIGCAcQRRg90gEIMjE4N2owajeoAgiwAgE&sourceid=chrome&ie=UTF-8`

### Category

detection

### Description

It says there is still adblock but at the same time it has to be turned off

### Other extensions used

CHONGLUADAO and muathongminh

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
AdBlock Max - chặn quảng cáo: 1.0.11
Chromium: 123
filterset (summary): 
 network: 127254
 cosmetic: 46974
 scriptlet: 19243
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 6-0, never
  VIE-1: 1896-0, 1h.20m
  easylist: 83101-41, 1d.19h.15m
  easyprivacy: 50407-10, 1d.19h.15m
  plowe-0: 3765-1183, 10d.7h.8m
  ublock-badware: 8021-139, 1d.19h.15m
  ublock-filters: 36007-210, 1d.19h.15m
  ublock-privacy: 709-6, 6d.21h.7m
  ublock-quick-fixes: 241-33, 1h.19m
  ublock-unbreak: 2245-33, 1d.19h.15m
  urlhaus-1: 8880-0, 1h.21m
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 12 redacted]
modifiedUserSettings: 
 tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 34034 ms (selfie)
 maxAssetCacheWait: 2173 ms
popupPanel: 
 blocked: 102
 no-cosmetic-filtering: true
 no-popups: true
 network: 
  google.com: 102
```
</details>

**Comment by stephenhawk8054** [comment]
> AdBlock Max - chặn quảng cáo: 1.0.11

You are not using uBlock Origin.

**Comment by garry-ut99** [comment]
Message to OP:  https://github.com/uBlockOrigin/uAssets/issues/20239#issuecomment-1775375712
