### ISSUE TITLE
[nsfw] nhentai.net: breakage

### ISSUE THREAD

**Issue by FumetsuKage** [uBlockOrigin/uAssets#23063]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nhentai.net/`

### Category

breakage

### Description

https://www.reddit.com/r/nhentai/comments/1ahujoy/comment/kv9asbf/?context=3
I've tested disabling ublock and that allows the auto scroll back to top to work but then an annoying popup comes up with every page turn. but with unlock it doesn't auto scroll to the top unless I hit the minus on the zoom.

(sorry for the screenshot bit idk what I'm supposed to screenshot for this)

### Other extensions used

dashlane, honey, Malwarebytes, Grammarly, guardio, watch2gether but as stated I've narrowed the issue to specifically ublock as i've tried with all of those disabled but the only one that affects the auto scroll is ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/165093200/5e4d78aa-dd87-41b1-9154-1fab4f9d5d30)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 127081
 cosmetic: 45796
 scriptlet: 20341
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 83544-18, now
  easyprivacy: 50409-10, now
  plowe-0: 3763-1182, now
  ublock-badware: 7981-140, now
  ublock-filters: 37406-359, now
  ublock-privacy: 780-5, now
  ublock-quick-fixes: 242-35, now
  ublock-unbreak: 2247-33, now
  urlhaus-1: 8780-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 817 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  adtng.com: 1
  cloudflareinsights.com: 1
  google-analytics.com: 1
 extended:
  ##+js(no-window-open-if)
  ##+js(set-constant, _n_app.popunder, null)
  ##+js(trusted-replace-node-text, script, popunder, p)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce the issue in more details? (Go to which link, click on which buttons/keyboards...?)

**Comment by FumetsuKage** [comment]
Well go to any doujin and have the setting for auto scroll to top turned on read a page while scrolling to the bottom, then go to the next page. Oh and remember to read right to left. With ublock on the auto scroll to top will do nothing. With ublock off when you get to the next page it'll bring the scroll bar back to the top. Not really sure what else i can possibly do to explain.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorhill** [comment]
Using uBO with default settings/lists and no other extensions, I am unable to reproduce what resemble to the description. When I "turn" a page, the top of the next image is the top of the viewport, same as when uBO is disabled.

**Comment by FumetsuKage** [comment]
Well that's weird, i know I'm not the only one and i haven't ever touched any settings for it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stephenhawk8054** [comment]
Can you test again in a new browser profile with only uBO and its default settings?

**Comment by FumetsuKage** [comment]
Sure when i get home

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FumetsuKage** [comment]
just tried a completely different computer with a different browser, default settings with ublock as the only extension and same thing.
________________________________

**Comment by stephenhawk8054** [comment]
On that profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on Troubleshooting Information and copy paste it here?

**Comment by FumetsuKage** [comment]
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 127191
 cosmetic: 45871
 scriptlet: 20341
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 83749-137, now
  easyprivacy: 50408-10, now
  plowe-0: 3763-1182, now
  ublock-badware: 7981-140, now
  ublock-filters: 37405-360, now
  ublock-privacy: 780-5, now
  ublock-quick-fixes: 242-35, now
  ublock-unbreak: 2247-33, now
  urlhaus-1: 8880-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1404 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  adtng.com: 1
  cloudflareinsights.com: 1
  google-analytics.com: 1
 extended:
  ##+js(no-window-open-if)
  ##+js(set-constant, _n_app.popunder, null)
  ##+js(trusted-replace-node-text, script, popunder, p)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
________________________________

**Comment by stephenhawk8054** [comment]
> Also, where's the settings `auto scroll to top`? I only see these:

<details>

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/2b3cdf70-e1d7-4f31-8561-b7a073dbff41)

</details>

> Can you screenshot exactly which settings you are using?

**Comment by FumetsuKage** [comment]
jump on page turn (top of image) setting is what I'm referring to
________________________________

**Comment by stephenhawk8054** [comment]
When I set to that, clicked on an image, scrolled to the bottom, then press -> button to continue to next image, it jumped to the top normally for me.

**Comment by FumetsuKage** [comment]
so we've established that yours is fine but for months mine on several computers and several browsers doesn't work. what now?
________________________________

**Comment by stephenhawk8054** [comment]
It means I cannot investigate what causes the issue if I cannot reproduce it. Or else what could I do?

**Comment by FumetsuKage** [comment]
I don't know, I'm not privy to the reason this affects me and several other people but not you, I'm not even really certain what ublock is even blocking to cause this, all I know is it's blocking 3 things and 1 or more of those is site functionality

**Comment by stephenhawk8054** [comment]
Well, you might need to wait for other volunteers who can reproduce and investigate it. Currently 2 of us cannot reproduce it and unable to investigate further.

I won't participate in this any more.

**Comment by gorhill** [comment]
I can reproduce when I enable _Malwarebytes Browser Guard_, and I can still reproduce after I disabled uBO and keep _Malwarebytes Browser Guard_ enabled. This is not a uBO issue.
