### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by Otkritka** [uBlockOrigin/uAssets#23065]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yandex.ru/images/search?img_url=https%3A%2F%2Fsun9-59.userapi.com%2Fimpf%2Fc623425%2Fv623425975%2F31b2%2FVGF6aBtlA84.jpg%3Fsize%3D370x470%26quality%3D96%26sign%3Da3ac5a2e3b7d16a0529ea9611b5eaacd%26c_uniq_tag%3DUBK_GmSaFMElolNdGnUhAuH3zQtSKVomzI_afp_Z4UM%26type%3Dalbum&lr=10335&p=1&pos=6&rpt=simage&text=%D0%BE%D0%BF%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5%20%D0%B8%D0%BB%D0%BB%D1%8E%D0%B7%D0%B8%D0%B8`

### Category

ads

### Description

Advertising on the website

### Other extensions used

There are no other blockers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![024-03-27_082655_yandex ru](https://github.com/uBlockOrigin/uAssets/assets/55092038/241274fb-5e53-4fee-a160-4444e13754d8)
![2024-03-27_082716_yandex ru](https://github.com/uBlockOrigin/uAssets/assets/55092038/6d04fa0d-7703-427d-b67f-fc77f43035b8)
![2024-03-27_082735_yandex ru](https://github.com/uBlockOrigin/uAssets/assets/55092038/5e87a9d8-e74e-4f1d-a50a-bcf402fb6648)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 109
filterset (summary):
 network: 144595
 cosmetic: 66431
 scriptlet: 21698
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  RUS-0: 39477-9, 1h.49m Δ
  easylist: 83749-156, now
  easyprivacy: 50409-90, now
  plowe-0: 3763-1186, now
  ublock-badware: 7981-140, now
  ublock-filters: 37387-382, now
  ublock-privacy: 780-6, now
  ublock-quick-fixes: 242-35, now
  ublock-unbreak: 2247-33, now
  urlhaus-1: 8880-0, 1h.49m
filterset (user): [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6050 ms (selfie)
 maxAssetCacheWait: 361 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 104
 network:
  yandex.ru: 104
 extended:
  ##div[id*="Images"] div[class*="_filled"][style^="max-width:"]
  ##.b-page:style(padding-top: 0 !important)
```
</details>

**Comment by dimisa-RUAdList** [comment]
See: https://github.com/uBlockOrigin/uAssets/issues/22348
