### ISSUE TITLE
phoronix.com: detection

### ISSUE THREAD

**Issue by RoonMoonlight** [uBlockOrigin/uAssets#23067]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.phoronix.com/news/Fedora-Approved-January-F40`

### Category

detection

### Description

> **It looks like your ad blocker is on.**
>
> Ads are what make it possible to produce new content on Phoronix each and every day over the past 20 years.
> 
> Please support Phoronix by disabling your ad blocker.
> 
> Alternatively, you can join Phoronix Premium as an option for ad-free viewing, multi-page articles on a single page, native dark mode, and more benefits.
>
> Join Phoronix Premium
The following above error occurs.

### Other extensions used

SponsorBlock for YouTube, YouTube Live Stream Latancy Mitigator, Simply Translate, Auto Tab Discard, HyperChat [Improved YouTube Chat], Remove Twitch Recommended Channel Live Chat, LibRedirect, Violentmonkey (No script is active), Return YouTube Dislike, ColorZilla, Plasma Integration, User Agent Switcher, BetterTTV, Proton Pass, Improve YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240327_182719](https://github.com/uBlockOrigin/uAssets/assets/25527589/02c5f015-4b8a-4e2f-8359-fd11eaff42d8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 127353
 cosmetic: 45855
 scriptlet: 18992
 html: 1724
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37553-134, now
  ublock-badware: 7991-15, now
  ublock-privacy: 776-0, now
  ublock-unbreak: 2304-0, now
  ublock-quick-fixes: 246-0, now
  easylist: 83920-760, now
  easyprivacy: 50409-860, now
  urlhaus-1: 8880-0, now
  plowe-0: 3763-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 663 ms (selfie)
 maxAssetCacheWait: 223 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  pub.network: 1
  twitter.com: 1
 extended:
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
```
</details>

**Comment by stephenhawk8054** [comment]
Enable "uBlock filters – Annoyances" list or add this filter as your custom filter

```adb
phoronix.com#@#[data-freestar-ad]:not(:empty)
```

**Comment by RoonMoonlight** [comment]
> Enable "uBlock filters – Annoyances" list or add this filter as your custom filter
> 
> ```
> phoronix.com#@#[data-freestar-ad]:not(:empty)
> ```

So this is not enforced Adblock detection?

**Comment by RoonMoonlight** [comment]
Oh alright, thanks!
