### ISSUE TITLE
censor.net: breakage

### ISSUE THREAD

**Issue by YumbaMumba** [uBlockOrigin/uAssets#23062]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://censor.net/`

### Category

breakage

### Description

Enabling Ublock Origin makes the login button disappear. And the same goes for the toolbar over the Comments box (it's gone when it's on, and it's there when it's off).

### Other extensions used

No other extensions used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![2024-03-26_211431](https://github.com/uBlockOrigin/uAssets/assets/62180023/c700ae43-7fe0-4
![2024-03-26_211543](https://github.com/uBlockOrigin/uAssets/assets/62180023/dcd2f9db-87c3-429d-a124-ae187324ac23)
34b-
![2024-03-26_211732](https://github.com/uBlockOrigin/uAssets/assets/62180023/8a3caa42-8e4e-4f94-a5eb-b82d5b505a1b)
![2024-03-26_211816](https://github.com/uBlockOrigin/uAssets/assets/62180023/83908b93-6aab-4863-80d6-d0d3a9f61677)

8d10-e3da30f422e0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 144346
 cosmetic: 66325
 scriptlet: 20377
 html: 1740
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37576-134, 6m
  ublock-badware: 7985-15, 6m
  ublock-privacy: 776-0, 6m
  ublock-unbreak: 2304-0, 6m
  ublock-quick-fixes: 246-0, 6m
  easylist: 83384-638, 6m
  easyprivacy: 50409-860, 6m
  urlhaus-1: 8780-0, 6m
  plowe-0: 3763-0, 6m
  RUS-0: 39507-136, 6m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2938 ms
 maxAssetCacheWait: 258 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  censor.net: 2
  cloudflareinsights.com: 2
  googleoptimize.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##body iframe[name][style*="display:none"]:not([id]):not([class]…
```
</details>

**Comment by mapx-** [comment]
add

`.censor.net/js/$script,badfilter`

@dimisa-RUAdList

**Comment by YumbaMumba** [comment]
Hello,

Thanks for the quick answer.

I'm a total noob when it comes to adding sth to Ublock Origin :( Could you
please provide me with more detailed instructions?

Best regards,

User



вт, 26 мар. 2024 г. в 21:56, mapx ***@***.***>:

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/d1342cf4bbbd169932a73dd1cae6186cd45b0072

**Comment by YumbaMumba** [comment]
I'm sorry I still don't get it :(

What should I do with this fix? How do I apply it?

вт, 26 мар. 2024 г. в 22:05, dimisa ***@***.***>:

**Comment by mapx-** [comment]
@YumbaMumba 

click this link to update the list:
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=RUS-0&manual=1

**Comment by YumbaMumba** [comment]
It worked!!!
Thank you very much indeed!!!!!!!!!

вт, 26 мар. 2024 г. в 22:18, mapx ***@***.***>:
