### ISSUE TITLE
beatstars.com: ads

### ISSUE THREAD

**Issue by liamengland1** [uBlockOrigin/uAssets#23078]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.beatstars.com/search?type=tracks&tags=rob49
```

### Description

Users can pay to promote their beats as "ads" on the site, which will show up in search results and may play before the beat you actually want to listen to. 

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/4201f22a-9106-4171-819f-dd7c139724a3)
![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/31f4720b-ad8a-4348-972a-cf56d44e153c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    

Fix:
```
||beatstars.com/v3/promote/
||beatstars.com/promos?
```

**Comment by ryanbr** [comment]
`||beatstars.com/promos?` is enough?

**Comment by mapx-** [comment]
it seems ok only that filter @ryanbr

**Comment by liamengland1** [comment]
No, one filter is for the ads that appear in search results, and the other is for promoted beats that play before the beat the user clicked on

**Comment by D4niloMR** [comment]
Was it fixed?

**Comment by liamengland1** [comment]
@D4niloMR can we start leaving the "fixable by easylist" issues open until the filters are added to easylist or uAssets? that way they don't get forgotten. another time this happened is with https://github.com/uBlockOrigin/uAssets/issues/22877

**Comment by D4niloMR** [comment]
Sure, I always keep them open until fixed.
