### ISSUE TITLE
200ok.shop: breakage

### ISSUE THREAD

**Issue by vnandan** [uBlockOrigin/uAssets#23070]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://200ok.shop/`

### Category

breakage

### Description

It is a shopify site for personal store. The chat support disappears when I use ublock origin on FF. After disabling UO, it functions correctly. This has been reproduced by developer and Shopify support.

### Other extensions used

sponsorblock, bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/3316435/933b518a-00af-45f9-bebd-c7285a999a10)

after disabling UO

![image](https://github.com/uBlockOrigin/uAssets/assets/3316435/82139037-8ef4-4c9f-b587-3cd8c1a90de4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 138646
 cosmetic: 201178
 scriptlet: 32059
 html: 1980
listset (total-discarded, last-updated):
 added:
  adguard-social: 22713-862, 1m
  fanboy-thirdparty_social: 68-0, 1m
  fanboy-cookiemonster: 50714-3908, 1m
  fanboy-social: 15844-25, 1m
  ublock-annoyances: 6882-1097, 42m Δ
  adguard-cookies: 29060-71, 1m
  adguard-popup-overlays: 26936-1689, 1m
  adguard-mobile-app-banners: 5107-1086, 1m
  adguard-other-annoyances: 14083-350, 1m
  adguard-widgets: 2435-1, 1m
  easylist-annoyances: 4451-125, 1m
  easylist-chat: 188-15, 1m
  [4 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 37553-396, 42m Δ
  ublock-badware: 7991-15, 42m Δ
  ublock-privacy: 776-0, 42m Δ
  ublock-unbreak: 2304-0, 42m Δ
  ublock-quick-fixes: 246-0, 42m Δ
  easylist: 83920-845, 42m Δ
  easyprivacy: 50409-994, 42m Δ
  urlhaus-1: 8880-0, 1m
  plowe-0: 3763-0, 1m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 14 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 202 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  200ok.shop: 11
  judge.me: 1
  shopify.com: 1
  shopifysvc.com: 1
 extended:
  ##.list-social
```
</details>

**Comment by mapx-** [comment]
`@@||cdn.shopify.com/extensions/*/assets/inbox-chat-loader.js$script,domain=200ok.shop`

@ryanbr

**Comment by mapx-** [comment]
@vnandan however this is due to using `EasyList – Chat Widgets` list (killing the chat widgets), if you disable it you'll get the chat

**Comment by ryanbr** [comment]
This is intentional it removes the chat from the website. As expected.
