### ISSUE TITLE
facebook.com: nuisance

### ISSUE THREAD

**Issue by BDARmech** [uBlockOrigin/uAssets#23075]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.facebook.com/`

### Category

nuisance

### Description

Hash redirects with embeded tags. 

### Other extensions used

ClearUrls, standard settings with this isolation. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 138298
 cosmetic: 45858
 scriptlet: 18988
 html: 1723
listset (total-discarded, last-updated):
 added:
  dpollock-0: 11663-462, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37547-135, 33m Δ
  ublock-badware: 7991-15, 33m Δ
  ublock-privacy: 776-0, 33m Δ
  ublock-unbreak: 2304-0, 33m Δ
  ublock-quick-fixes: 251-0, 33m Δ
  easylist: 84038-931, 33m Δ
  easyprivacy: 50409-969, 33m Δ
  urlhaus-1: 8780-0, never
  plowe-0: 3772-0, never
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 largeMediaSize: 75
hiddenSettings: [none]
supportStats:
 allReadyAfter: 168 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 no-cosmetic-filtering: true
 no-large-media: true
 no-remote-fonts: true
 network:
  facebook.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
#3367
