### ISSUE TITLE
ovagames.com: detection

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#23072]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
www.ovagames.com
```

### Description

Anti-adblock prevents the use of the site.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 117346
 cosmetic: 49559
 scriptlet: 19363
 html: 1723
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 default:
  user-filters: 2-0, never
  ublock-filters: 37531-270, now
  ublock-badware: 7991-15, now
  ublock-privacy: 776-0, now
  ublock-unbreak: 2304-0, now
  ublock-quick-fixes: 251-0, now
  easylist: 84038-327, now
  easyprivacy: 50409-46, now
  spa-1: 5445-16, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2201 ms (selfie)
 maxAssetCacheWait: 1140 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  adtrackers.net: 1
  crunchylashins.com: 2
  facebook.com: 1
  histats.com: 1
  linkspy.cc: 2
 extended:
  ##+js(abort-current-script, JSON, _0x)
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
