### ISSUE TITLE
EDIT: no longer broken; coursera.org: breakage

### ISSUE THREAD

**Issue by hschennum** [uBlockOrigin/uAssets#23079]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.coursera.org/learn/software-architecture/home/welcome`

### Category

breakage

### Description

Upon entering any "course" page with uBO enabled, the page content fails to appear (see images).
Note that the Coursera homepage (https://www.coursera.org) does not break.
URL examples which break:
https://www.coursera.org/learn/software-architecture/home/welcome
https://www.coursera.org/learn/programming-languages-part-c/home/welcome
etc

Issue was confirmed for desktop: Chrome, Firefox, Edge and for mobile: Firefox

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

with uBO enabled
![image](https://github.com/uBlockOrigin/uAssets/assets/132386901/37793bba-83f2-4a59-932f-e98f944b0d0b)
without uBO enabled
![image](https://github.com/uBlockOrigin/uAssets/assets/132386901/a6a23f3f-5bed-4320-ad8c-db17502f84ce)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 138838
 cosmetic: 201236
 scriptlet: 32049
 html: 1979
listset (total-discarded, last-updated):
 added:
  adguard-social: 22713-862, 38m
  adguard-cookies: 29079-71, 38m
  ublock-cookies-adguard: 1062-0, 38m
  adguard-popup-overlays: 26938-1689, 38m
  adguard-mobile-app-banners: 5111-8, 38m
  adguard-other-annoyances: 14084-290, 38m
  adguard-widgets: 2438-1, 38m
  fanboy-thirdparty_social: 68-0, 38m
  easylist-annoyances: 4451-125, 38m
  easylist-chat: 188-15, 38m
  fanboy-cookiemonster: 50714-3908, 38m
  ublock-cookies-easylist: 1062-1062, 38m
  [4 lists not shown]: [too many]
 default:
  user-filters: 44-0, never
  ublock-filters: 37533-396, 38m
  ublock-badware: 7991-15, 38m
  ublock-privacy: 776-0, 38m
  ublock-unbreak: 2304-0, 38m
  ublock-quick-fixes: 251-0, 38m
  easylist: 84059-846, 38m
  easyprivacy: 50409-994, 38m
  urlhaus-1: 8930-0, 38m
  plowe-0: 3763-0, 38m
filterset (user): [array of 43 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 901 ms (selfie)
 maxAssetCacheWait: 287 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  sentry-cdn.com: 1
 extended:
  ###fb-root:not(body):not(html)
  ##+js(prevent-fetch, eventing)
```
</details>

**Comment by liamengland1** [comment]
Test this filter:
`@@||browser.sentry-cdn.com^$script,from=coursera.org`
