### ISSUE TITLE
totalav.com: popups

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#23073]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.totalav.com/ultra-deal-new-9?exit=`

### Category

popups

### Description

The ?exit= makes you when you want to leave the site or move your mouse cursor up (see video), open up a popup . Can you make sure that any website can't measure where my mouse cursor is? 

### Other extensions used

non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/100969549/44cc29d8-ba1b-4dfd-85b1-df7fa48108d8

</details>

### Configuration

<details>

```yaml
[uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 301713
 cosmetic: 280073
 scriptlet: 52598
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1053-0, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4325-4, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 97910-17033, now
  CHN-0: 25448-129, now
  JPN-1: 14179-9, now
  KOR-1: 5027-21, now
  [23 lists not shown]: [too many]
 default:
  user-filters: 61-0, never
  DEU-0: 7353-1, now
  easylist: 84038-2038, 30m Δ
  easyprivacy: 50409-32128, 30m Δ
  plowe-0: 3763-1685, now
  ublock-badware: 7987-261, 30m Δ
  ublock-filters: 37381-4034, 30m Δ
  ublock-privacy: 780-222, 30m Δ
  ublock-quick-fixes: 247-41, 30m Δ
  ublock-unbreak: 2247-158, 30m Δ
  urlhaus-1: 8930-0, now
filterset (user): [array of 62 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 108 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 debugScriptlets: true
 loggerPopupType: normal
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1677 ms (selfie)
 maxAssetCacheWait: 490 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  totalav.com: 5
  trustpilot.com: 1
 extended:
  ##.trustpilot-widget
  ##.footer__social-links
  ##div.cookie-notice
  ##.cookie-notice:not(body):not(html)
  ##.cookie-notice-content](https://www.totalav.com/ultra-deal-new-9?exit=)](https://www.gmx.net/)
```
</details>

**Comment by ItsProfessional** [comment]
It's a malicious scam site.

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/pull/20272
