### ISSUE TITLE
Background color override

### ISSUE THREAD

**Issue by gmask** [uBlockOrigin/uAssets#2307]
### URL where the issue occurs

`hltv.org`

### Describe the issue

[This line](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L1850) in `filters.txt` overrides the background color on HLTV.org. If you're using the site's default (light) theme then it's perfect, but if you're on the dark theme it looks terrible.

I've [tried overriding this style](https://gist.github.com/gmask/9ef0d7c75fac5610e7cc21b94b84b01f) both with a self-hosted filter list and with a local filter on uBlock, as well as using Greasemonkey to [apply a custom style](https://gist.github.com/gmask/4701a681481fa6357d2b211b0eb80f0d), but none of these work.

I'm wondering if/how I can override that particular line.

**Comment by mapx-** [comment]
Did you try an exception ?
`hltv.org#@#body:style(background: #e5e7ea !important;)`

**Comment by gmask** [comment]
That works great, thanks! Can be hard to know what's possible from [the syntax documentation](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax).

**Comment by mapx-** [comment]
see
https://adblockplus.org/en/filters#elemhide_exceptions
