### ISSUE TITLE
gmx.net: ads

### ISSUE THREAD

**Issue by WasdeAsde** [uBlockOrigin/uAssets#23071]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gmx.net/`

### Category

ads

### Description

Ads are still present on the right side of the page.

### Other extensions used

KeePassXC-Browser
Return YT Dislikes
LanguageTool

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/54501537/fcff16dc-db6e-4ece-9787-1e694dd55db5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 122
filterset (summary):
 network: 129237
 cosmetic: 50745
 scriptlet: 19008
 html: 1725
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37609-103, 4m Δ
  ublock-badware: 8066-15, 4m Δ
  ublock-privacy: 782-0, 4m Δ
  ublock-unbreak: 2305-2, 4m Δ
  ublock-quick-fixes: 247-36, 4m Δ
  easylist: 83101-646, 3m Δ
  easyprivacy: 50405-876, 4m Δ
  urlhaus-1: 8930-0, 3m
  plowe-0: 3772-0, 3m
  DEU-0: 7352-19, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6455 ms (selfie)
 maxAssetCacheWait: 3152 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  gmx.net: 7
  adition.com: 3
  criteo.net: 2
  ioam.de: 3
  ui-portal.de: 4
  uimserv.net: 1
  united-infos.net: 2
 extended:
  ##.partner-links
  ##+js(addEventListener-defuser, timeupdate)
  ##+js(no-setTimeout-if, UABP)
  ##+js(set-constant, adBlockDetectionResult, undefined)
```
</details>

**Comment by mapx-** [comment]
it seems to be self promotion
