### ISSUE TITLE
achieve.macmillanlearning.com: breakage

### ISSUE THREAD

**Issue by DeathOverlord** [uBlockOrigin/uAssets#23080]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://achieve.macmillanlearning.com/`

### Category

breakage

### Description

There are buttons that open little popups that show extra information, it's supposed to just open a side tab but now it just causes the entire page to go white. 

Expected:
![image](https://github.com/uBlockOrigin/uAssets/assets/24486489/fba7652b-e57c-4cd3-b650-dd6931a934f4)

Actual:
![image](https://github.com/uBlockOrigin/uAssets/assets/24486489/d54dcc68-6092-4fec-bc52-27c21dd2553e)

other 

I'm not sure how to verify if it's with the site, it used to work fine but now it does not.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 116
filterset (summary):
 network: 145900
 cosmetic: 47201
 scriptlet: 20409
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  ublock-filters: 37533-265, 16m
  ublock-badware: 7991-15, 16m
  ublock-privacy: 776-0, 16m
  ublock-unbreak: 2304-1, 16m
  ublock-quick-fixes: 251-0, 16m
  easylist: 84059-667, 16m
  adguard-spyware-url: 1488-106, 16m
  easyprivacy: 50409-844, 16m
  urlhaus-1: 8965-0, 16m
  curben-phishing: 14143-2, 16m
  plowe-0: 3763-0, 16m
  LegitimateURLShortener: 2623-167, 16m
  bpc-paywall-filter: 1054-0, 16m
  AntiPaywall: 2092-15, 16m
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 336 ms (selfie)
 maxAssetCacheWait: 139 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 no-cosmetic-filtering: true
 network:
  googletagmanager.com: 1
  instana.io: 2
  pendo.io: 2
  usercentrics.eu: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in official Firefox browser with only uBO and its default settings.
