### ISSUE TITLE
fitgirltorrent.com: breakage

### ISSUE THREAD

**Issue by Arylone23** [uBlockOrigin/uAssets#23085]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://fitgirl-repacks.site/.
```

### Description

The website is being blocked by ublock origin while it does not contains any advertisements

### Other extensions used

https://fitgirl-repacks.site/.

### Screenshot(s)

![donimg](https://github.com/uBlockOrigin/uAssets/assets/88710633/572b2094-1710-4604-ba09-83944ca415de)

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 242236
 cosmetic: 253806
 scriptlet: 51506
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7354-0, 22m
  adguard-cookies: 29079-33, 22m
  adguard-generic: 80275-508, 22m
  adguard-mobile: 9197-62, 22m
  adguard-mobile-app-banners: 5111-9, 22m
  adguard-other-annoyances: 14085-13, 22m
  adguard-popup-overlays: 26940-97, 22m
  adguard-social: 22711-908, 22m
  adguard-spyware: 100830-1172, 22m
  adguard-spyware-url: 1488-5, 22m
  adguard-widgets: 2440-9, 22m
  block-lan: 61-0, 22m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 83519-1585, 22m
  easyprivacy: 50409-31936, 22m
  plowe-0: 3763-1342, 22m
  ublock-badware: 7987-249, 22m
  ublock-filters: 37401-4001, 22m
  ublock-privacy: 781-219, 22m
  ublock-quick-fixes: 242-65, 22m
  ublock-unbreak: 2247-154, 22m
  urlhaus-1: 9065-0, 22m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 77 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 771 ms (selfie)
 maxAssetCacheWait: 559 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/23084#issuecomment-2025133742
