### ISSUE TITLE
timeshighereducation.com: breakage

### ISSUE THREAD

**Issue by naufalaziz7** [uBlockOrigin/uAssets#23086]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.timeshighereducation.com/world-university-rankings/2023/regional-ranking`

### Category

breakage

### Description

breakage on the ranking list. disabling ublock origin does fix the problem.

### Other extensions used

![Screenshot 2024-03-29 000422](https://github.com/uBlockOrigin/uAssets/assets/60262112/984020e8-c0ad-4566-b37d-05edfde17437)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-28 235240](https://github.com/uBlockOrigin/uAssets/assets/60262112/f0187d78-b18d-437d-8548-2f98732de61d)
![Screenshot 2024-03-28 235329](https://github.com/uBlockOrigin/uAssets/assets/60262112/0cf71051-84d2-4756-b6d2-e49149e5d26d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 225027
 cosmetic: 241623
 scriptlet: 50453
 html: 1977
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1054-0, 1h.23m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  adguard-generic: 80251-5490, now
  adguard-spyware-url: 1488-106, now
  adguard-spyware: 100832-33205, now
  block-lan: 61-0, now
  adguard-social: 22710-862, now
  adguard-cookies: 29088-70, now
  adguard-popup-overlays: 26976-1628, now
  adguard-mobile-app-banners: 5111-1087, now
  adguard-other-annoyances: 14095-290, now
  adguard-widgets: 2443-1, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 23-1, never
  ublock-filters: 37567-437, 1h.23m Δ
  ublock-badware: 8000-15, 1h.23m Δ
  ublock-privacy: 777-0, 1h.23m Δ
  ublock-unbreak: 2304-1, 1h.23m Δ
  ublock-quick-fixes: 189-0, 1h.23m Δ
  easylist: 84149-841, 1h.23m Δ
  easyprivacy: 50409-996, 1h.23m Δ
  urlhaus-1: 9065-0, 1h.23m
  plowe-0: 3763-0, 1h.22m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 967 ms (selfie)
 maxAssetCacheWait: 648 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  timeshighereducation.com: 9
  automatad.com: 1
  cookiebot.com: 1
  doubleclick.net: 1
  newrelic.com: 2
 extended:
  ##.share-buttons
  ##.block-the-dfp
  ##.pane-social-links
  ###block-the-dfp-the-dfp-oop
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-on-stack-trace, Drupal.CTools.Modal.show, /(^(?!.*(i…
```
</details>

**Comment by D4niloMR** [comment]
> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

Report at https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters
