### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by gettysburg** [uBlockOrigin/uAssets#23089]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://open.spotify.com
```

### Description

When using uBlock Origin on the web player site from Spotify for a while to get rid of ads, eventually playback breaks completely.

For example, when trying to play the first song in an album, it instantly starts hopping to the next song, and does so for a few more songs (in my test case right now, 8).

In some cases, it tries starting playback, then just cancels, but without looping through the album.

Either way, no music is played at all.

This can be temporarily fixed by deleting all data for `*.spotify.com`, upon logging back in to the web player, maybe one song will play, but then it's back to the behavior above.

### Other extensions used

```
1.) Old Reddit Redirect
2.) Remove DNT (DoNotTrack) header from requests
3.) Return YouTube Dislike
4.) Search by Image
5.) Tampermonkey
```

### Screenshot(s)

There is really nothing to show, as in no error pops up, so I decided to open the network request logger instead, as well as uBlock Origin's logger.

The Firefox network log is from when one song **initially plays fine**, then when trying to play the next song, it started looping through tracks until stopping eventually.

The uBO logger screenshot is from when Spotify was actively looping through the tracks.

![image](https://github.com/uBlockOrigin/uAssets/assets/2256003/78e2ade5-6efc-4580-8787-c8c78757b3e8)
![image](https://github.com/uBlockOrigin/uAssets/assets/2256003/76c682e6-12bf-41b8-8f69-a4c7fd137fd6)

### Configuration

System:

```
OS: ArchLinux
Kernel: 6.8.1
Firefox: 124.0.1
uBlock Origin: 1.56.1rc5
```

No recent package changes could have caused this.

**Comment by stephenhawk8054** [comment]
Can you test in a new Firefox profile with only uBO and its default settings?

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/issues/22198

**Comment by gettysburg** [comment]
@ItsProfessional Fuck you nigger :)
