### ISSUE TITLE
fitgirltorrent.com: breakage

### ISSUE THREAD

**Issue by rythmofthenight** [uBlockOrigin/uAssets#23084]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fitgirltorrent.com/`

### Category

breakage

### Description

The website is being blocked by ublock origin while it does not contains any advertisements

### Other extensions used

`https://www.fitgirltorrent.com/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 127778
 cosmetic: 45866
 scriptlet: 18982
 html: 1721
listset (total-discarded, last-updated):
 default:
  user-filters: 22-7, never
  ublock-filters: 37567-138, 10m Δ
  ublock-badware: 8000-15, 10m Δ
  ublock-privacy: 777-0, 10m Δ
  ublock-unbreak: 2304-0, 10m Δ
  ublock-quick-fixes: 189-0, 10m Δ
  easylist: 84149-756, 10m Δ
  easyprivacy: 50409-832, 10m Δ
  urlhaus-1: 9065-0, now
  plowe-0: 3763-0, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 199 redacted]
switchRuleset:
 added: [array of 36 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1371 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Because its a fake site, the real site is `https://fitgirl-repacks.site/`.
