### ISSUE TITLE
tiktokcounter.net: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#23088]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiktokcounter.net/finance/2024/02/12/how-to-choose-the-right-health-insurance/`

### Category

detection

### Description

http://ez4short.com/5nwtr8olam

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 129364
 cosmetic: 37783
 scriptlet: 19051
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  ublock-filters: 37924-356, now
  ublock-badware: 8009-15, now
  ublock-privacy: 777-1, now
  ublock-unbreak: 2310-1, now
  ublock-quick-fixes: 192-0, now
  adguard-mobile: 9206-134, now
  easylist: 84333-16550, now
  easyprivacy: 50410-869, now
  urlhaus-1: 9065-0, 49m
  plowe-0: 3763-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2300 ms (selfie)
 maxAssetCacheWait: 924 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  quesignifi.ca: 1
 extended:
  ##+js(remove-class, is-hidden)
  ##+js(set-constant, isAdClickDone, true)
```
</details>

**Comment by monkeyde98** [comment]
It was detected again today. [link](https://coinfays.com/dHqZ) that can get to it

**Comment by monkeyde98** [comment]
try now [link](https://coinfays.com/kRfJ5SE)
