### ISSUE TITLE
NSFW! (anti-adblock) porntopic.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2308]
### URL(s) where the issue occurs

`http://porntopic.com/videos/19582/hightide-video-isabelle-scat-slut-isabelle-extreme/`

### Describe the issue

Anti-adblock, may need to refresh 1~2 times to reproduce. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/40146335-624b5736-5922-11e8-9e0c-cb1849dc0400.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.4

### Settings

All default.

**Comment by uBlock-user** [comment]
same as https://github.com/reek/anti-adblock-killer/issues/3939

`porntopic.com#script:inject(setTImeoout-defuser.js, innerText)`
