### ISSUE TITLE
thecubexguide.com: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#23090]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thecubexguide.com/python-web-server-vs-nginx/`

### Category

detection

### Description

https://devuploads.com/t722brlh89z9

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 129364
 cosmetic: 37779
 scriptlet: 19051
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37924-380, 5m
  ublock-badware: 8009-15, 5m
  ublock-privacy: 777-1, 5m
  ublock-unbreak: 2310-1, 5m
  ublock-quick-fixes: 192-0, 5m
  adguard-mobile: 9206-134, 5m
  easylist: 84333-16550, 5m
  easyprivacy: 50410-841, 5m
  urlhaus-1: 9065-0, 54m
  plowe-0: 3763-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2300 ms (selfie)
 maxAssetCacheWait: 924 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ###featuredimage
```
</details>

**Comment by mapx-** [comment]
dedicated thread https://github.com/uBlockOrigin/uAssets/discussions/17361
