### ISSUE TITLE
gem.cbc.ca: breakage

### ISSUE THREAD

**Issue by BoobooProton** [uBlockOrigin/uAssets#23098]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gem.cbc.ca/coronation-street?autoplay=1`

### Category

breakage

### Description

Just  keeps try to load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 127928
 cosmetic: 45943
 scriptlet: 19006
 html: 1722
listset (total-discarded, last-updated):
 default:
  user-filters: 33-0, never
  ublock-filters: 37640-109, 3m
  ublock-badware: 8036-15, 3m
  ublock-privacy: 777-0, 3m
  ublock-unbreak: 2305-0, 3m
  ublock-quick-fixes: 192-0, 3m
  easylist: 84613-760, 3m
  easyprivacy: 50411-860, 3m
  urlhaus-1: 8730-5, 3m
  plowe-0: 3762-0, 3m
filterset (user): [array of 33 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 134 ms (selfie)
 maxAssetCacheWait: 48 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 45
 network:
  cbc.ca: 9
  2mdn.net: 1
  casalemedia.com: 4
  chartbeat.com: 2
  conductrics.com: 1
  crwdcntrl.net: 1
  cxense.com: 1
  demdex.net: 6
  doubleclick.net: 2
  facebook.net: 1
  googlesyndication.com: 1
  imasdk.googleapis.com: 1
  omtrdc.net: 7
  radio-canada.ca: 3
  scorecardresearch.com: 2
  sentry-cdn.com: 1
  tranquilveil.com: 2
 extended:
  ##+js(addEventListener-defuser, click, /event_callback=function\…
  ##+js(abort-on-property-write, xhr.prototype.realSend)
```
</details>

**Comment by BoobooProton** [comment]
Thank you

**Comment by mapx-** [comment]
add & test

`@@||imasdk.googleapis.com/js/core/bridge*.html$subdocument,domain=gem.cbc.ca`

**Comment by BoobooProton** [comment]
Fixed
