### ISSUE TITLE
bbc.com: breakage

### ISSUE THREAD

**Issue by RonanCJ** [uBlockOrigin/uAssets#23097]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bbc.com/news/world-us-canada-68642027`

### Category

breakage

### Description

When I load the website on Firefox Android with uBO enabled, the thumbnail appears as normal, but when I click play the video buffers endlessly. I believe it is trying to load an ad, since disabling uBO lets the site load and play an ad, then the video plays as expected.

This issue appeared recently and seems to be due to a change/update to the BBC.com video player.

### Other extensions used

Ghostery with ad blocking turned off - problem still occurs when Ghostery paused entirely
Kagi Search
Mate Translate  - not active on English website
Dark Reader inactive - problem still occurs when extension turned off for site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 129273
 cosmetic: 37789
 scriptlet: 19048
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37915-350, 1h.6m Δ
  ublock-badware: 8019-15, 1h.6m Δ
  ublock-privacy: 777-1, 1h.6m Δ
  ublock-unbreak: 2310-1, 1h.6m Δ
  ublock-quick-fixes: 185-0, 1h.6m Δ
  adguard-mobile: 9211-134, now
  easylist: 84586-16549, 1h.6m Δ
  easyprivacy: 50412-869, 1h.6m Δ
  urlhaus-1: 8730-5, now
  plowe-0: 3762-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 940 ms (selfie)
 maxAssetCacheWait: 269 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`@@||imasdk.googleapis.com/js/core/bridge*.html$frame,domain=bbc.com`

@ryanbr
