### ISSUE TITLE
loadout.tf: advertisement bar is back

### ISSUE THREAD

**Issue by caw-caw-robinjay** [uBlockOrigin/uAssets#23099]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://loadout.tf/
```

### Description

This is a returning issue, last seen in `[a report closed 3 weeks ago](https://github.com/uBlockOrigin/uAssets/issues/22856)`. To repeat what was said there, while the actual ad on the side of the screen is blocked, the black bar containing the ad is not.
![loadout](https://github.com/uBlockOrigin/uAssets/assets/162194910/12131183-6c1f-4b9c-bdfe-8ea90324260b)

The zapper, picker, and block element right-click shortcut all do not work, even with sliders, always blocking the entire page rather than just the ad. 
![Screenshot (1526)](https://github.com/uBlockOrigin/uAssets/assets/162194910/d6890ee2-4428-4bcf-b852-d6d9e2cb591a)
![Screenshot (1527)](https://github.com/uBlockOrigin/uAssets/assets/162194910/0050fccd-16c0-4d8d-9379-5837c4e8abdc)

Bearing in mind that I have no idea what I'm talking about, I assume the reason for this is either due to the ad being underneath a shadow root, the website's content and ads being named the same thing in inspect element, or a combination of both.
![Screenshot (1524)](https://github.com/uBlockOrigin/uAssets/assets/162194910/95fb1d40-5e26-46b0-bce1-517131df9e41)
![Screenshot (1525)](https://github.com/uBlockOrigin/uAssets/assets/162194910/5c9d4342-f618-4bf4-9649-eca6a65e8e65)

This issue is present on both Chrome and Firefox, in version 1.56.0. Hopefully this issue will be fixed in the newly announced 1.57.0, but until it comes to Firefox and I can verify that it is fixed, I thought I would create an issue for it. Once 1.57.0 comes, I'll update the issue with whether it's fixed or not.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by D4niloMR** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/issues/22856
