### ISSUE TITLE
channel4.com: detection

### ISSUE THREAD

**Issue by ethimeris** [uBlockOrigin/uAssets#23096]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.channel4.com/programmes/taskmaster/on-demand/75588-001`

### Category

detection

### Description

Video player would not load at all at first. I tested every extension one by one (by turning off every other one) and I would get a loading circle thing for each one that has not changed for several minutes. In the past, I've not had this issue. It's only when I tried in a private window that I got a pop-up about an adblocker being detected.

(Apologise for any messups, I'm not super well-versed in any kind of computer stuff)

### Other extensions used

Ghostery, YouTube Non-Stop, Chameleon, Privacy Badger, Privacy Possum, Search by Image, 12ft, Let's get color blind, AdNauseum. Bypass Paywalls for Firefox, Clear Browsing Data, ClearURLs, Cookie AutoDelete, Clippings, Disconnect, Dictionary Anywhere, Decentraleyes, YouTube SponsorBlock, DuckDuckGo Privacy Essentials, History Cleaner, Highlighter + Notes, Don't Track Me Google, Facebook Container, Measure It, minerBlock, Norton AntiTrack, PopUp Blocker (Strict), Single File, Return YouTube Dislikes, Spaywall News & Research, Tranquility Reader, Unpaywall, Undo Close Tab, Video Download Helper, User-Agent Switcher and Manager, YouTube Shorts Block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 127878
 cosmetic: 45859
 scriptlet: 18983
 html: 1722
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37560-137, 58m Δ
  ublock-badware: 8025-15, 58m Δ
  ublock-privacy: 777-0, now
  ublock-unbreak: 2305-0, now
  ublock-quick-fixes: 185-0, now
  easylist: 84586-760, 58m Δ
  easyprivacy: 50412-832, 58m Δ
  urlhaus-1: 8730-5, now
  plowe-0: 3762-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 140 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  channel4.com: 1
  braze.eu: 1
  c4assets.com: 1
  demdex.net: 1
  fwmrm.net: 1
 extended:
  ###c4ad-Top
  ##.advert-leaderboard
  ##+js(no-xhr-if, /\/ad\/g\/1/)
```
</details>

**Comment by ItsProfessional** [comment]
> - [X] I am not using uBlock Origin along with other content blockers.

You are. You're using dozens of content blockers (including ghostery, adnauseum, etc.). Read and follow all pre-requisites; do not just tick and ignore them.
