### ISSUE TITLE
arras.io: breakage

### ISSUE THREAD

**Issue by throwaway215** [uBlockOrigin/uAssets#23102]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://arras.io/`

### Category

breakage

### Description

uBlock Origin breaks the game if the "annoyances" filter is enabled while on Firefox. Everything works normally if I'm either using Chrome, or if I disable the "annoyances" filter.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/a/oErP99U

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 128458
 cosmetic: 47586
 scriptlet: 23540
 html: 1978
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6879-11, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37571-208, never
  ublock-badware: 8025-15, now
  ublock-privacy: 777-0, now
  ublock-unbreak: 2305-0, never
  ublock-quick-fixes: 191-0, never
  easylist: 84516-659, now
  easyprivacy: 50410-886, now
  urlhaus-1: 9055-0, never
  plowe-0: 3763-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 867 ms
 maxAssetCacheWait: 293 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  arras.io: 2
  cloudflareinsights.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
cc @JobcenterTycoon I'm not sure how to reproduce the previous issue.

**Comment by JobcenterTycoon** [comment]
Just join a game. The check is broken on firefox so it will throw every time a anti adblock.
