### ISSUE TITLE
[nsfw] 4khd.com: nuisance

### ISSUE THREAD

**Issue by ice051128** [uBlockOrigin/uAssets#23104]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.4khd.com/tag/%EC%86%90%EC%98%88%EC%9D%80/page/7`

### Category

nuisance

### Description

Leftover empty banner.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_26](https://github.com/uBlockOrigin/uAssets/assets/49018832/d66fb64b-d83c-42cf-997d-b634b38c6de5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 128112
 cosmetic: 45934
 scriptlet: 20340
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84627-139, 44m Δ
  easyprivacy: 50416-12, 44m Δ
  plowe-0: 3762-1182, 2m
  ublock-badware: 8061-140, 44m Δ
  ublock-filters: 37471-360, 44m Δ
  ublock-privacy: 781-5, 44m Δ
  ublock-quick-fixes: 193-8, 44m Δ
  ublock-unbreak: 2250-33, 44m Δ
  urlhaus-1: 8860-5, 44m
filterset (user): [empty]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 132 ms (selfie)
 maxAssetCacheWait: 69 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  4khd.com: 1
  magsrv.com: 2
 extended:
  ##.adsbyexoclick
```
</details>

**Comment by mapx-** [comment]
@ice051128 the maintainer has been notified, if it wont be fixed you can open an issue directly at easylist repository
