### ISSUE TITLE
lachainemeteo.com: nuisance

### ISSUE THREAD

**Issue by LoockyLucky** [uBlockOrigin/uAssets#23108]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lachainemeteo.com/meteo-france/previsions-meteo-france-aujourdhui`

### Category

detection

### Description

Detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2237" alt="Capture d’écran 2024-03-30 à 19 09 57" src="https://github.com/uBlockOrigin/uAssets/assets/146693990/0d8ff561-860b-40c3-94fb-daf86c6435eb">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 148607
 cosmetic: 92869
 scriptlet: 22522
 html: 1722
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 26991-133, never
  adguard-mobile-app-banners: 5114-18, never
  adguard-other-annoyances: 14105-276, never
  adguard-widgets: 2444-7, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37629-180, 6m
  ublock-badware: 8036-15, 6m
  ublock-privacy: 777-0, 6m
  ublock-unbreak: 2305-0, 6m
  ublock-quick-fixes: 192-0, 6m
  easylist: 84627-891, 6m
  easyprivacy: 50416-1115, 6m
  urlhaus-1: 8940-5, 6m
  plowe-0: 3762-0, 6m
  FRA-0: 23334-110, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1197 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  appconsent.io: 1
  googletagmanager.com: 1
  hubvisor.io: 1
  opecloud.com: 1
 extended:
  ##div[id^="mban_atf-"]
  ##.ad
  ##div[id^="ob_in-feed"]
  ##.ad-background-container
  ##.ad-bg
  #@#.ad-side
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances` list
