### ISSUE TITLE
gem.cbc.ca: detection

### ISSUE THREAD

**Issue by IliaO7** [uBlockOrigin/uAssets#23100]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gem.cbc.ca/heartland`

### Category

detection

### Description

CBC Gem detects UBlock Origin and does not playback content when enabled

### Other extensions used

No other extensions are being used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 127945
 cosmetic: 45938
 scriptlet: 20341
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84613-139, 20m Δ
  easyprivacy: 50411-12, 20m Δ
  plowe-0: 3762-1182, now
  ublock-badware: 8034-140, 20m Δ
  ublock-filters: 37486-360, 20m Δ
  ublock-privacy: 781-5, 20m Δ
  ublock-quick-fixes: 193-7, 20m Δ
  ublock-unbreak: 2248-33, 20m Δ
  urlhaus-1: 8730-5, 25m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 346 ms
 maxAssetCacheWait: 152 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 21
 network:
  cbc.ca: 21
 extended:
  ##+js(abort-on-property-write, xhr.prototype.realSend)
  ##+js(addEventListener-defuser, click, /event_callback=function\…
```
</details>

**Comment by mapx-** [comment]
duplicate, go to https://github.com/uBlockOrigin/uAssets/issues/23098#issuecomment-2027551254
