### ISSUE TITLE
actu.fr: nuisance

### ISSUE THREAD

**Issue by LoockyLucky** [uBlockOrigin/uAssets#23107]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://actu.fr/grenoble/`

### Category

detection

### Description

detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2209" alt="Capture d’écran 2024-03-30 à 19 07 21" src="https://github.com/uBlockOrigin/uAssets/assets/146693990/c8978797-de5b-444a-921f-3f3f847a9aeb">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 148607
 cosmetic: 92869
 scriptlet: 22522
 html: 1722
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 26991-133, never
  adguard-mobile-app-banners: 5114-18, never
  adguard-other-annoyances: 14105-276, never
  adguard-widgets: 2444-7, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37629-180, now
  ublock-badware: 8036-15, now
  ublock-privacy: 777-0, now
  ublock-unbreak: 2305-0, now
  ublock-quick-fixes: 192-0, now
  easylist: 84627-891, now
  easyprivacy: 50416-1115, now
  urlhaus-1: 8940-5, now
  plowe-0: 3762-0, now
  FRA-0: 23334-110, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1197 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  non.li: 1
 extended:
  ##.ac-banner-ad
```
</details>

**Comment by mapx-** [comment]
enable uBlock filters – Annoyances

**Comment by x-R0b0T-x** [comment]
https://actu.fr/auvergne-rhone-alpes/caluire-et-cuire_69034/lyon-le-vol-d-une-banane-vire-au-drame-a-l-epicerie-un-homme-dans-un-etat-grave_63501656.html

<img width="570" height="154" alt="Image" src="https://github.com/user-attachments/assets/8ba2b5dc-5aa2-4166-8d51-62d9bbc07222">

<img width="322" height="281" alt="Image" src="https://github.com/user-attachments/assets/dfc2a7c3-378a-4477-a4c7-ac9e9b2c7bc7">

<img width="317" height="619" alt="Image" src="https://github.com/user-attachments/assets/c1c0f88e-a957-4a96-8d31-53a22e230375">

I know this is a "cosmetic" issue. So where can I find the aesthetic filtering option in uBlock Origin Lite?

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25679#issuecomment-3621490080
