### ISSUE TITLE
radyofenomen.com: nuisance

### ISSUE THREAD

**Issue by juarez-spa3** [uBlockOrigin/uAssets#23113]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.radyofenomen.com/`

### Category

nuisance

### Description

cookie notice

### Other extensions used

bitwarden, twp translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/153795294/1142e5c9-0aa4-40f3-9fa7-1dd77bf0e1ca)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 131738
 cosmetic: 101462
 scriptlet: 29083
 html: 1978
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50726-216, 1m
  ublock-cookies-easylist: 1063-0, 1m
  ublock-annoyances: 6872-1074, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37638-120, 2m
  ublock-badware: 8053-15, now Δ
  ublock-privacy: 777-0, now Δ
  ublock-unbreak: 2307-0, now Δ
  ublock-quick-fixes: 192-0, 2m
  easylist: 84627-786, now Δ
  easyprivacy: 50416-883, 2m
  urlhaus-1: 8940-5, 2m
  plowe-0: 3762-0, 2m
  TUR-0: 12155-16, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3651 ms
 maxAssetCacheWait: 27 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  facebook.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
radyofenomen.com##+js(set-cookie, isSiteCookieReviewed, 0, , reload, 1)
```

@ryanbr
