### ISSUE TITLE
[nsfw] xhamster.com: detection

### ISSUE THREAD

**Issue by AKABobHoward** [uBlockOrigin/uAssets#23118]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://xhamster.com/`

### Category

detection

### Description

Persistent red box at top of screen instructing user to disable ad blocker.
![Screenshot_20240330_213029_Firefox](https://github.com/uBlockOrigin/uAssets/assets/66700582/3733a3cc-db9a-4c79-b893-41aa11c7adaa)

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 129283
 cosmetic: 37842
 scriptlet: 19078
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38002-378, 1m Δ
  ublock-badware: 8047-15, 1m Δ
  ublock-privacy: 777-1, 1m Δ
  ublock-unbreak: 2312-1, 1m Δ
  ublock-quick-fixes: 198-0, 1m Δ
  adguard-mobile: 9213-134, now
  easylist: 84631-16556, 1m Δ
  easyprivacy: 50416-841, 1m Δ
  urlhaus-1: 8650-5, 1m
  plowe-0: 3762-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7872 ms (selfie)
 maxAssetCacheWait: 968 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 no-cosmetic-filtering: true
 network:
  xhamster.com: 7
  d3c.life: 1
  googletagmanager.com: 1
  tsyndicate.com: 3
 extended:
  ##.thumb-list-mobile-item--widget
  ##.video-page__layout-ad
  ##.thumb-list-mobile > .thumb-list-mobile-item--widget
  ##div[class^="yld-"]
  ##+js(set-constant, initials.yld-pdpopunder, )
  ##+js(set-cookie, ts_popunder, true, , reload, 1)
  ##+js(trusted-replace-node-text, script, popunder, , condition, …
  ##+js(remove-cookie, video_view_count)
```
</details>

**Comment by stephenhawk8054** [comment]
Wait about 5-6 hours and enable `uBlock filters – Annoyances` list or add this as your custom fitler:

```adb
xhamster.com##+js(no-fetch-if, /ad\.php|api\/ads/)
```

**Comment by ghost** [comment]
It's back again, but on mobile:
https://github.com/user-attachments/assets/0b959ed7-e008-45de-97d7-eafb9df4fc39
