### ISSUE TITLE
720pstream.nu: popups

### ISSUE THREAD

**Issue by ThatAnonymousGuy1** [uBlockOrigin/uAssets#23119]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://720pstream.nu/nhl/live-columbus-blue-jackets-stream`

### Category

nuisance

### Description

This applies to any streams on this site. As of the last two days, there continues to be popups when clicking the stream window. I can see and filter them, but then maybe another reload or minutes later a random new one will appear. Something new must have been added within the last week because this nuisance was fixed before. I updated all my filters. I no longer see a purge option though. 

### Other extensions used

Dark Reader, Alternate Tab Order, PIP, Lastpass, RES, X-notifier

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-03-30 220116](https://github.com/uBlockOrigin/uAssets/assets/37353659/13d78820-ffa8-4576-aaa9-1e9aa0869ec7)
![Screenshot 2024-03-30 220226](https://github.com/uBlockOrigin/uAssets/assets/37353659/e4761fa2-28fc-4366-8d9b-438faefed3a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 127902
 cosmetic: 45979
 scriptlet: 20353
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
 default:
  user-filters: 52-0, never
  easylist: 84631-139, now
  easyprivacy: 50416-12, now
  plowe-0: 3762-1182, now
  ublock-badware: 8051-140, now
  ublock-filters: 37486-370, now
  ublock-privacy: 781-5, now
  ublock-quick-fixes: 200-8, now
  ublock-unbreak: 2250-33, now
  urlhaus-1: 8650-5, now
filterset (user): [array of 53 redacted]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 68 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 556 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 15
 network:
  acacdn.com: 1
  asacdn.com: 1
  castanydm.com: 3
  dlem1deojpcg7.cloudfront.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  lkxahvf.com: 2
  pregainpotgut.top: 1
  taboola.com: 1
  web3-lab.com: 2
 extended:
  ##div.text-center.col-12:nth-of-type(1)
  ##.text-left.row.col-12
  ##div.text-center.col-12:nth-of-type(6)
  ##.text-center.text-warning.col-12
  ##.text-left.col-12
  ##.bg-dark.position-absolute
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(no-window-open-if)
  ##+js(no-setTimeout-if, admc)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(nowebrtc)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-current-script, JSON, break;case)
  ##+js(no-setTimeout-if, (), 150)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
  ##+js(remove-node-text, script, FingerprintJS)
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by mapx-** [comment]
@ThatAnonymousGuy1 

test

```
cuervotv.me##+js(nowoif)
cuervotv.me##+js(rmnt, script, ;}}};break;case $.)
```

**Comment by ThatAnonymousGuy1** [comment]
> @ThatAnonymousGuy1
> 
> test
> 
> ```
> cuervotv.me##+js(nowoif)
> cuervotv.me##+js(rmnt, script, ;}}};break;case $.)
> ```

Thanks. I will try this later today when the site has some live streams to test and report back.
