### ISSUE TITLE
chownow.com: breakage

### ISSUE THREAD

**Issue by nbeaver** [uBlockOrigin/uAssets#23117]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.chownow.com/search`

### Category

breakage

### Description

Search works but I cannot click on the resulting search results. I just get this error:

> Uncaught (in promise) TypeError: window.mParticle.upload is not a function NextJS

### Other extensions used

None (reproduced in a clean Firefox profile with uBlock origin as the only addon)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="564" alt="Screenshot 2024-03-30 195238" src="https://github.com/uBlockOrigin/uAssets/assets/3036798/bc5f412f-7dc2-4967-b471-d264219555bb">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 128178
 cosmetic: 45913
 scriptlet: 19013
 html: 1722
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37647-137, 55m Δ
  ublock-badware: 8053-15, 55m Δ
  ublock-privacy: 777-0, 55m Δ
  ublock-unbreak: 2307-0, 55m Δ
  ublock-quick-fixes: 198-0, 55m Δ
  easylist: 84631-765, 55m Δ
  easyprivacy: 50416-832, 55m Δ
  urlhaus-1: 8940-5, now
  plowe-0: 3762-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 133 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  branch.io: 1
  browser-intake-datadoghq.com: 5
  cookielaw.org: 1
  launchdarkly.com: 4
  maps.googleapis.com: 2
  mparticle.com: 1
  sentry.io: 12
  sift.com: 1
```
</details>

**Comment by mapx-** [comment]
error code 1005 => no vpn can be used

**Comment by ItsProfessional** [comment]
Search is working fine for my (no vpn needed for me).

**Comment by nbeaver** [comment]
Yes, this was reproduced in a new Firefox profile with only uBlock Origin installed. Make sure "Delivery" is enabled, if "Pickup" is enabled I can't reproduce either.

**Comment by ItsProfessional** [comment]
No issue on my end, even with "delivery" selected.
