### ISSUE TITLE
puzzle-tents.com: nuisance

### ISSUE THREAD

**Issue by Krecik-dev** [uBlockOrigin/uAssets#23114]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.puzzle-tents.com/?size=8`

### Category

nuisance

### Description

When I turn on cosmetic filter to remove "AD box" it also remove "setings box" in this website.

### Other extensions used

vidIQ
1VPN
Chomikuj.pl
Youtube Nonstop
Flash Player +
Flash Player (playlist)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cosmetic filter on](https://github.com/uBlockOrigin/uAssets/assets/71896929/39a994a1-ad70-4444-a17f-63432fa82159)
![cosmetic filter off](https://github.com/uBlockOrigin/uAssets/assets/71896929/b0139b16-cd89-40c5-9436-da623f61059a)
![AD box](https://github.com/uBlockOrigin/uAssets/assets/71896929/04aef742-f857-4c33-b30c-66dba1eb49f6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 129654
 cosmetic: 54171
 scriptlet: 20550
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  POL-0: 8736-9, now
  POL-2: 1280-14, now
  easylist: 84628-163, 35m Δ
  easyprivacy: 50416-12, 35m Δ
  plowe-0: 3762-1190, now
  ublock-badware: 8051-140, 35m Δ
  ublock-filters: 37472-399, 35m Δ
  ublock-privacy: 781-5, 35m Δ
  ublock-quick-fixes: 193-8, 35m Δ
  ublock-unbreak: 2250-34, 35m Δ
  urlhaus-1: 8940-5, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 424 ms (selfie)
 maxAssetCacheWait: 134 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 7
 network:
  a-mo.net: 1
  adnxs.com: 1
  criteo.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  lijit.com: 1
  s-onetag.com: 1
 extended:
  ###MainContainer > [id^="bannerTopSpacer"]
  ###MainContainer + [id]:has(> #bannerSide)
  ###MainContainer > [id]:has(> [id^="btIn"] > #bannerTop) a
```
</details>

**Comment by JobcenterTycoon** [comment]
There was a overlapping invisible element which blocked around 70% of the settings button. Should work fine now.
