### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by servantutar** [uBlockOrigin/uAssets#23116]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.derstandard.at/`

### Category

detection

### Description

Webpage detects ublock

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240331_003827_Firefox](https://github.com/uBlockOrigin/uAssets/assets/112799966/b0fcef9f-db7a-4597-8756-6ade35bd7c77)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 132206
 cosmetic: 44202
 scriptlet: 23630
 html: 1979
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6935-14, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38002-395, 1m
  ublock-badware: 8047-15, 1m
  ublock-privacy: 777-1, 1m
  ublock-unbreak: 2312-1, 1m
  ublock-quick-fixes: 192-0, 1m
  adguard-mobile: 9213-134, 2m
  easylist: 84627-16563, 1m
  easyprivacy: 50416-868, 1m
  urlhaus-1: 8940-5, 1m
  plowe-0: 3762-0, 1m
  DEU-0: 7356-408, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2545 ms
 maxAssetCacheWait: 9 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  derstandard.at: 1
 extended:
  ##+js(trusted-replace-node-text, script, "adsDisabled":false, "a…
  ##+js(no-setTimeout-if, event, 3000)
```
</details>

**Comment by jondo** [comment]
I also see this. Simply replacing the `.at` by `.de` does the job as workaround for me.

**Comment by D4niloMR** [comment]
How to reproduce the detection?

**Comment by jondo** [comment]
I see in only on mobile Firefox, (Fennec from F-Droid) not on desktop.

**Comment by jondo** [comment]
Also, it had worked until some days ago.

**Comment by jondo** [comment]
Hmm, now the site works again. 🤷
