### ISSUE TITLE
heyzine.com: nuisance

### ISSUE THREAD

**Issue by fAntMP** [uBlockOrigin/uAssets#23122]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://heyzine.com/`

### Category

nuisance

### Description

Cookie notice is present.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 139165
 cosmetic: 201502
 scriptlet: 33681
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29097-33, now
  adguard-mobile-app-banners: 5114-7, now
  adguard-other-annoyances: 14105-10, now
  adguard-popup-overlays: 26991-85, now
  adguard-social: 22719-903, now
  adguard-widgets: 2444-3, now
  easylist-annoyances: 4454-256, now
  easylist-chat: 188-15, now
  easylist-newsletters: 7156-501, now
  easylist-notifications: 2975-1474, now
  fanboy-cookiemonster: 50751-3870, now
  fanboy-social: 15850-748, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 19-2, never
  easylist: 84631-198, 14m Δ
  easyprivacy: 50417-125, 14m Δ
  plowe-0: 3762-1183, now
  ublock-badware: 8063-140, 14m Δ
  ublock-filters: 37493-702, 14m Δ
  ublock-privacy: 781-7, 14m Δ
  ublock-quick-fixes: 200-8, 14m Δ
  ublock-unbreak: 2250-37, 14m Δ
  urlhaus-1: 8650-5, now
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 601 ms (selfie)
 maxAssetCacheWait: 362 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  google.com: 2
  googletagmanager.com: 1
 extended:
  ##a[href^="https://feedly.com/i/subscription/"]
```
</details>

**Comment by mapx-** [comment]
add

heyzine.com##.cookies

@ryanbr @Alex-302
