### ISSUE TITLE
mbt-store.com: breakage

### ISSUE THREAD

**Issue by ONE11111111ONE** [uBlockOrigin/uAssets#23121]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://mbt-store.com/
```

### Description

when opening the website, grey layer appears and nothing works. 
using latest version. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![MBT](https://github.com/uBlockOrigin/uAssets/assets/150746073/193b20d1-a1c1-41dc-a6d5-121eb52d6cf3)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by ONE11111111ONE** [comment]
funny thing is, when i open a new tab and ACCEPT the cookies and  try to teproduce, it just worksfine, no cookie blocker activated!

**Comment by ONE11111111ONE** [comment]
![grafik](https://github.com/uBlockOrigin/uAssets/assets/150746073/8aae36d6-b6de-42c5-9337-56f0042bb82c)

**Comment by ONE11111111ONE** [comment]
uBlock Origin: 1.56.1rc5
Firefox: 124
filterset (summary):
 network: 140769
 cosmetic: 206143
 scriptlet: 32061
 html: 1978
listset (total-discarded, last-updated):
 added:
  adguard-social: 22713-47, 2d.11h.29m
  adguard-cookies: 29084-41, 2d.11h.29m
  ublock-cookies-adguard: 1077-13, 3d.12h.37m
  adguard-popup-overlays: 26977-966, 2d.11h.29m
  adguard-mobile-app-banners: 5111-20, 2d.11h.29m
  adguard-other-annoyances: 14096-412, 2d.11h.29m
  adguard-widgets: 2443-9, 2d.11h.28m
  fanboy-thirdparty_social: 68-3, 8d.12h.32m
  easylist-annoyances: 4450-268, 3d.12h.37m
  easylist-chat: 188-15, 8d.12h.32m
  fanboy-cookiemonster: 50693-3874, 3d.12h.37m
  ublock-cookies-easylist: 1077-1077, 3d.12h.37m
  [4 lists not shown]: [too many]
 default:
  user-filters: 8-1, never
  ublock-filters: 37567-104, 1d.13h.10m
  ublock-badware: 8015-15, 1d.13h.10m
  ublock-privacy: 777-0, 9h.1m
  ublock-unbreak: 2305-2, 1d.13h.10m
  ublock-quick-fixes: 192-3, 8h.1m
  easylist: 83519-253, 3d.9h.39m
  easyprivacy: 50409-58, 3d.9h.39m
  urlhaus-1: 8860-0, 19h.2m
  plowe-0: 3763-1183, 8d.15h.32m
  DEU-0: 7356-44, 19h.2m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 269 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  amazon.com: 5
  facebook.com: 2
  google.de: 1
  maps.googleapis.com: 1
  newsletter2go.com: 1
  paypal.com: 4
  trustedshops.com: 2
 extended:
  ##.fb-page
  ###tfm_dsgvo_disclaimer
  ##div.newsletter-section
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…

**Comment by ONE11111111ONE** [comment]
i'm afraid, i activated more filterlists then the common ones

**Comment by stephenhawk8054** [comment]
Yes, you are enabling too many additional lists. I suspect the cookie lists can cause issues. Turn off one-by-one to see which one is causing issues.

**Comment by mapx-** [comment]
@ONE11111111ONE 

add

```
mbt-store.com###tfm_dsgvo_disclaimer_shadow
mbt-store.com###tfm_dsgvo_disclaimer_container
mbt-store.com###newsletterModal
mbt-store.com##.in.fade.modal-backdrop
mbt-store.com##.index-wrap:style(overflow: auto !important;)
```

the last 3 for the newsletter

@ryanbr

**Comment by ONE11111111ONE** [comment]
@mapx- 
@stephenhawk8054 
@ryanbr 

Thank you so much guys!

**Comment by ONE11111111ONE** [comment]
Sorry, still doesn't work for me. Cleared cache and so on.

**Comment by ONE11111111ONE** [comment]
The cookie banner goes away, yet the grey background stays.

**Comment by mapx-** [comment]
reset uBO to defaults, do not use other blocking extensions, test again

**Comment by ONE11111111ONE** [comment]
Done, now its good.

Thanks!

**Comment by krystian3w** [comment]
#23867
