### ISSUE TITLE
Bit Fun & Moon Cash Anti-Adblock

### ISSUE THREAD

**Issue by jdck** [uBlockOrigin/uAssets#2312]
### URL(s) where the issue occurs

`http://bitfun.co/games`
`http://moonbitcoin.cash/faucet`

### Describe the issue

This is bitcoin faucet. Anti-Adblock blocks claim.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16664309/40181426-a5a95b5a-5a1b-11e8-932a-9fb3cf9cd3f9.png)
![image](https://user-images.githubusercontent.com/16664309/40181448-b2860062-5a1b-11e8-91ae-2bbb62a5e5cd.png)

### Versions

- Browser/version: Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)
- uBlock Origin version: Nano Adblocker v1.0.0.49

### Settings

- Default

### Notes

Seems like the only current workaround is switching off Nano Adblocker on the site. Nano Defender doesn't work either.

**Comment by uBlock-user** [comment]
Both websites require an account.
