### ISSUE TITLE
freep.com: ads, breakage

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#23120]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freep.com/story/money/cars/ford/2022/01/18/ford-adt-canopy-antitheft-camera-accessory/6559242001/`

### Category

ads

### Description

Lots of leftover and complete ads around the article. Redirects sometimes. Video ads play in corner of screen. Hidden ads blend in with screen

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/b6766fde-d9b2-458f-b8ba-c520ad0af5c2)

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 221770
 cosmetic: 46170
 scriptlet: 19742
 html: 1722
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1491-106, now
  block-lan: 61-0, now
  curben-phishing: 13954-4, now
  dpollock-0: 11664-461, now
  adguard-spyware: 100833-32277, now
 default:
  user-filters: 6-0, never
  ublock-filters: 37647-138, 1h.26m Δ
  ublock-badware: 8053-15, 1h.26m Δ
  ublock-privacy: 777-0, 1h.26m Δ
  ublock-unbreak: 2307-1, 1h.26m Δ
  ublock-quick-fixes: 198-0, 1h.26m Δ
  easylist: 84631-934, 1h.26m Δ
  easyprivacy: 50416-940, 1h.26m Δ
  urlhaus-1: 8650-5, now
  plowe-0: 3762-0, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 31 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 245 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  freep.com: 2
  2mdn.net: 1
  adsafeprotected.com: 1
  amazon-adsystem.com: 1
  brandmetrics.com: 1
  btloader.com: 1
  confiant-integrations.net: 1
  doubleclick.net: 1
  gannettinnovation.com: 2
  imasdk.googleapis.com: 2
  pointdigestion.com: 1
  scorecardresearch.com: 3
  taboola.com: 2
 extended:
  ##.gnt_x
  ##.gnt_x__lbl
  ###gnt_atomsnc
  ##.gnt_tb.gnt_tbb
  ##.gnt_flp
  ##.gnt_rr_xpst
  ##.gnt_tbr.gnt_tb
  ##.gnt_rr_xst
  ##+js(set-constant, adsEnabled, true)
  ##+js(abort-current-script, document.createElement, admiral)
```
</details>

**Comment by Oqarshi** [comment]
A few ads get by ublock origin but most of them are blocked. hopefully it gets fixed cause im too dumb to figure this stuff out
![Screenshot 2024-03-30 225018](https://github.com/uBlockOrigin/uAssets/assets/94034118/45f0dadc-1d91-44ef-9857-e1d57ac86cab)

**Comment by mapx-** [comment]
self promotion

**Comment by ItsProfessional** [comment]
We follow the [EasyList policy](https://easylist.to/pages/policy.html), as to what is to be fixed in the lists (e.g. ads, trackers, etc.).

By this policy, ads on sites which are self promotions, i.e. what is being advertised belongs to the site itself (not a third party), are not fixed in the lists.

**Comment by ItsProfessional** [comment]
Oh, I didn't look at your screenshot. The content in @Oqarshi's screenshot is self promotion, but your issue isn't about that. My bad.

**Comment by mapx-** [comment]
yeah, self promotion in @Oqarshi comment.

@Tornadoalley 

test

```
freep.com##.teal-video-wrap
freep.com##.gnt_em_vp__tavp.gnt_em
freep.com##a.gnt_cw_sl
freep.com##.gnt_ar_xb
```
