### ISSUE TITLE
thestreameast.to: popups

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#23128]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thestreameast.to/v6/`

### Category

popups

### Description

New window opens when clicking in here:
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 251565
 cosmetic: 248945
 scriptlet: 49978
 html: 1979
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80287-6516, 2d.5h.27m
  adguard-mobile: 9209-21, 2d.5h.27m
  adguard-spyware-url: 1491-106, 2d.5h.27m
  adguard-spyware: 100833-32334, 2d.5h.27m
  block-lan: 61-0, 23d.19h.1m
  curben-phishing: 14146-3, 20h.4m
  adguard-social: 22718-863, 2d.5h.27m
  adguard-cookies: 29094-70, 2d.5h.27m
  ublock-cookies-adguard: 1062-0, 20h.3m
  adguard-popup-overlays: 26988-1694, 2d.5h.27m
  adguard-mobile-app-banners: 5114-1088, 2d.5h.27m
  adguard-other-annoyances: 14099-346, 2d.5h.27m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37662-385, now Δ
  ublock-badware: 8085-15, now Δ
  ublock-privacy: 777-0, now Δ
  ublock-unbreak: 2307-1, now Δ
  ublock-quick-fixes: 179-0, now Δ
  easylist: 84575-1066, now Δ
  easyprivacy: 50423-1109, now Δ
  urlhaus-1: 8940-5, 20h.4m
  plowe-0: 3765-83, 10d.18h.20m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2081 ms
 maxAssetCacheWait: 1208 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  lkxahvf.com: 1
  youradexchange.com: 1
 extended:
  ##+js(addEventListener-defuser, /^/, 0x)
  ##+js(no-setInterval-if, visibility, 1000)
  ##+js(nowebrtc)
  ##+js(no-setTimeout-if, sadbl)

### Other extensions used

Decentralyze
PrivacyBadger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 251214
 cosmetic: 249007
 scriptlet: 49994
 html: 1979
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80306-6522, now
  adguard-mobile: 9213-104, now
  adguard-spyware-url: 1491-106, now
  adguard-spyware: 100833-32334, now
  block-lan: 61-0, now
  curben-phishing: 14052-3, now
  adguard-social: 22719-864, now
  adguard-cookies: 29097-69, now
  ublock-cookies-adguard: 1064-0, now
  adguard-popup-overlays: 26992-1694, now
  adguard-mobile-app-banners: 5114-1088, now
  adguard-other-annoyances: 14105-346, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37662-386, 1m Δ
  ublock-badware: 8085-15, 1m Δ
  ublock-privacy: 777-0, 1m Δ
  ublock-unbreak: 2307-1, 1m Δ
  ublock-quick-fixes: 179-0, 1m Δ
  easylist: 84575-1065, 1m Δ
  easyprivacy: 50423-1109, 1m Δ
  urlhaus-1: 8680-5, now
  plowe-0: 3762-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2081 ms
 maxAssetCacheWait: 1208 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  lkxahvf.com: 1
  youradexchange.com: 1
 extended:
  ##+js(addEventListener-defuser, /^/, 0x)
  ##+js(no-setInterval-if, visibility, 1000)
  ##+js(nowebrtc)
  ##+js(no-setTimeout-if, sadbl)
```
</details>

**Comment by peroleucopus** [comment]
Marked as complete but no fix? Is there something I need to update?

**Comment by D4niloMR** [comment]
Click on this link to update filters: https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1

**Comment by peroleucopus** [comment]
Thanks!
