### ISSUE TITLE
toririchard.com: breakage

### ISSUE THREAD

**Issue by kevomac12** [uBlockOrigin/uAssets#23129]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://toririchard.com/
klclick1.com^ is flagged, why??!
```

### Description

Web site access denied by: 
`https://trk.klclick1.com/ls/click?upn=u001.FyvoP9yTskv2DEIMIXrmQi9hDfzYlirblPOJcKBIqRAqaL9h4NJF64SmBtqthv-2FeG6oM8GRCmHLXdaKGnpbouj4vylDuBasiiNNmFa03vScWe31eEWrEeKLvUbOB38nombUp2nsP2tux6XbsjcbbpXBf3n6cuDCZ-2FIe4kF-2ByYxnZS0EFEO7QYxDj5wmZ1z00zeiSBVngRTu9EoUSk55sQh12TJZJnwktVnxxgbyEHKN4Mo6-2BXs0tdrzAyFKpzFmdX7mBfvFX5Y-2B2NPCYMM05pjfJdp-2BdQXaCIqnQO4NWfChV5DOB0axTXoSV9Ke3ZoszO3yo7n38jf1jq91B0wDKZ9rvu5GIuYHCIl9FvCuTwcPMbRWBjp-2B0-2Ba3-2FPoxbHwGCJE69xMSzMhkS8OrMm17UsNIzt6TvVDAw-2BsnYYOIvO2rFJooHMqI4383ZuMIB-2FmSGfvHGajK49pUCtbRjq2kltQ-3D-3D5kdt_cjyms7U4tiv3oNJzxJGyutxM7ONlhTqBEgeZr8eqOJqTVM9C9Uz-2BoFLkGQDE3e1T9NPfo8PnS80SCeUARFTETOK7z-2FFQLBxq6CULGjF5JAFnbTJGU3zrhA-2F25NICe6yKugKeLAuoEE3VK6hJCB-2FRUcm-2Bkdzd-2FDguueFnf33Ndhxl5X0O6dxVGFfI05VRqIqlYIU4rEKxXEAGiI4DHWvKYQO-2F1GY1trE8DeEwPY5rnkE0YpaKTHYUE3sVuIcOz03hVs7bFPw7tVFRjZmv2HaF-2BIcoO2W8tG42mGOWe5D1kXDNe9tlBvuudQuCSeFlVphqnunQUHT6QNhu48EtyGUmb94n0mbFRs0ZAW-2FIsvMUEGfj6UPv2tPKu8r8U0bbFOo-2BYSIe4G9-2BGHR-2FYa0V8tXIoZslG4dvMYKLShPC0tghHCgQAJWrl1hTq-2FXMOLm0PgVTgfKHJbGLo6uKuEXh4f9mtA-3D-3D`

### Other extensions used

N/A - Sorry but the fields to be filled in, via HTML tags, not clear for information delivered by your error message display!!

https://github.com/uBlockOrigin/uAssets/assets/8869566/470b8fc6-57c5-4bed-b1c8-eecfe49a3b34

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    
</ UPN:
without parameters = https://trk.klclick1.com/ls/click
upn = u001.FyvoP9yTskv2DEIMIXrmQi9hDfzYlirblPOJcKBIqRAqaL9h4NJF64SmBtqthv-2FeG6oM8GRCmHLXdaKGnpbouj4vylDuBasiiNNmFa03vScWe31eEWrEeKLvUbOB38nombUp2nsP2tux6XbsjcbbpXBf3n6cuDCZ-2FIe4kF-2ByYxnZS0EFEO7QYxDj5wmZ1z00zeiSBVngRTu9EoUSk55sQh12TJZJnwktVnxxgbyEHKN4Mo6-2BXs0tdrzAyFKpzFmdX7mBfvFX5Y-2B2NPCYMM05pjfJdp-2BdQXaCIqnQO4NWfChV5DOB0axTXoSV9Ke3ZoszO3yo7n38jf1jq91B0wDKZ9rvu5GIuYHCIl9FvCuTwcPMbRWBjp-2B0-2Ba3-2FPoxbHwGCJE69xMSzMhkS8OrMm17UsNIzt6TvVDAw-2BsnYYOIvO2rFJooHMqI4383ZuMIB-2FmSGfvHGajK49pUCtbRjq2kltQ-3D-3D5kdt_cjyms7U4tiv3oNJzxJGyutxM7ONlhTqBEgeZr8eqOJqTVM9C9Uz-2BoFLkGQDE3e1T9NPfo8PnS80SCeUARFTETOK7z-2FFQLBxq6CULGjF5JAFnbTJGU3zrhA-2F25NICe6yKugKeLAuoEE3VK6hJCB-2FRUcm-2Bkdzd-2FDguueFnf33Ndhxl5X0O6dxVGFfI05VRqIqlYIU4rEKxXEAGiI4DHWvKYQO-2F1GY1trE8DeEwPY5rnkE0YpaKTHYUE3sVuIcOz03hVs7bFPw7tVFRjZmv2HaF-2BIcoO2W8tG42mGOWe5D1kXDNe9tlBvuudQuCSeFlVphqnunQUHT6QNhu48EtyGUmb94n0mbFRs0ZAW-2FIsvMUEGfj6UPv2tPKu8r8U0bbFOo-2BYSIe4G9-2BGHR-2FYa0V8tXIoZslG4dvMYKLShPC0tghHCgQAJWrl1hTq-2FXMOLm0PgVTgfKHJbGLo6uKuEXh4f9mtA-3D-3D
>

**Comment by stephenhawk8054** [comment]
Test again in another computer with only uBO and its default settings.

**Comment by mapx-** [comment]
@kevomac12 are there specific steps to reproduce your issue ?

**Comment by kevomac12** [comment]
Sorry, these occurred in an email: extension://odfafepnkmbhccpbejgmiehpchacaeak/document-blocked.html?details=%7B%22url%22%3A%22https%3A%2F%2Ftrk.klclick1.com%2Fls%2Fclick%3Fupn%3Du001.FyvoP9yTskv2DEIMIXrmQi9hDfzYlirblPOJcKBIqRAqaL9h4NJF64SmBtqthv-2FeG6oM8GRCmHLXdaKGnpbouj4vylDuBasiiNNmFa03vScaxaScjhop1STzzWyksEAUA0oCpqUFNdWgzIARL9rXR6gzYayzcrRSwbSCFnoSBh2JCIs2LD9BntYuw6bxFa2IDf8UK456-2FSnlPiXK-2BqOjMA0NUZxbu-2BC6Kxo4v1YGocR8oIh4WaHOon6eMaRFxOrBkSvXAo5p5vTh5LAiPmsQsM0W8sWOFaqdWexr5T8SwQFfCMaf7RwnTljrgPqwD-2Bc6Uq-2BZbNWbM0B-2B9lpaCVCT9Kw4VgdGAUHq4kKso4ur-2F3xQB3ofLX3kDyt-2B6dXQPzczRx163aPpflZz8owZvdjgxNCqDnoE-2BjYi4Pc-2B8QRWmFUXIiAjGVZhsUEuaCSK1qbJEamI_cjyms7U4tiv3oNJzxJGyutxM7ONlhTqBEgeZr8eqOJqTVM9C9Uz-2BoFLkGQDE3e1T9NPfo8PnS80SCeUARFTETMI-2B-2FB4cHKeTRwFwVkip2aSW1zfswe7dLcdr2xyxFjRdYGkwwwYguqb4nuDo1l7qZovw1kEsilStG-2FVztTjKdZ4xBNtXSaOPpM4eDo347HUi-2B1yGbXwJKzt9-2FIihWpE8Y4wSBxx-2FQdesbwAat8XBNtlwfMYNzuSHbhjnIxAmTnjHiBGCMB9bqVSANSdNeoZjWyi-2BMvhRUbswhNAioorEYzpxiuzlcA8tgwTriAb0kivpQjbpKL1bXSHNQ7bxczprGEpKDV5348y2Fad0gr2TTI8W2qd3mKVnRCXBaSOLL01a59u52HQy0kNdml8-2B1q7LUU6nT9B05ZPSYwyCnRyh1wronCbNRVKMJm5ScpvTJSM3iKPt8dv3PdIUGwKZdGx8pQ-3D-3D%22%2C%22hn%22%3A%22trk.klclick1.com%22%2C%22dn%22%3A%22klclick1.com%22%2C%22fs%22%3A%22%7C%7Cklclick1.com%5E%22%7D

I have a tab saved for Tori Richard, I'm just curious why it happens!

KMW
