### ISSUE TITLE
download.megaup.net: detection

### ISSUE THREAD

**Issue by ragg102** [uBlockOrigin/uAssets#23126]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/`

### Category

detection

### Description

when the page load put a message that i use a ad block 

### Other extensions used

bitwarden
save from
fastforward
jdownloader2
keepa
web browser firefox windows

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 130281
 cosmetic: 52336
 scriptlet: 19389
 html: 1723
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37663-251, now
  ublock-badware: 8085-15, now
  ublock-privacy: 777-0, now
  ublock-unbreak: 2307-0, now
  ublock-quick-fixes: 183-0, now
  easylist: 84575-723, now
  easyprivacy: 50423-846, now
  urlhaus-1: 8680-5, now
  plowe-0: 3762-0, now
  spa-0: 4012-5, now
  spa-1: 5443-182, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 257 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 2
  keydawnawe.com: 1
 extended:
  ##a img:not([src="images/main_logo_inverted.png"]):matches-css(h…
  ##+js(spoof-css, a img:not([src="images/main_logo_inverted.png"]…
  ##+js(trusted-replace-node-text, script, /\!\=\s*_/g, ==_)
  ##+js(abort-current-script, Math, break;case $.)
```
</details>

**Comment by JobcenterTycoon** [comment]
Known issue https://github.com/uBlockOrigin/uAssets/issues/20505 fixed 4 minutes ago https://github.com/uBlockOrigin/uAssets/commit/7bd357384424fac275cbe11ee2a905152db6ac95
