### ISSUE TITLE
[nsfw] ovabee.com: detection

### ISSUE THREAD

**Issue by Tinnuzz** [uBlockOrigin/uAssets#23136]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ovabee.com/upload/en/bENlMmzFlQVOfjR-FC2-PPV-4363476.jpg`

### Category

detection

### Description

Similar to another issue I reported, probably owned by the same individual

> Please Turn Off Adblock to view this photo.
> 
> - My website only has banners and I've tried to keep them from bothering you.
> 
> - If you like my work please turn off your Adblock extension.
> 
> - The banners help me have money to continue my work.
> 
> _________________________
> 
> Best regards,
> 
> offkab
> 

### Other extensions used

```
Return YT dislike
Tampermonkey
Sponsorblock
google RIS
Facebook Container
Youtube enhancer
1Password
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
NSFW

![image]https://i.imgur.com/e8HZA4t.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 127812
 cosmetic: 45745
 scriptlet: 18951
 html: 1725
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37462-144, now
  ublock-badware: 8095-15, now
  ublock-privacy: 777-0, now
  ublock-unbreak: 2297-0, now
  ublock-quick-fixes: 200-0, 1h.22m Δ
  easylist: 84516-763, now
  easyprivacy: 50423-832, now
  urlhaus-1: 8610-5, never
  plowe-0: 3763-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 250 ms (selfie)
 maxAssetCacheWait: 67 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  clumsyshare.com: 1
  googlesyndication.com: 1
  magsrv.com: 13
 extended:
  ##.popup-box-ads
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
ovabee.com##+js(rmnt, script, detectAdBlock)

**Comment by Tinnuzz** [comment]
added filter, cleared cache, restarted browser, issue remains.
