### ISSUE TITLE
cybermania.ws: detection

### ISSUE THREAD

**Issue by tetz88** [uBlockOrigin/uAssets#23144]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.cybermania.ws/
```

### Description

Detected

### Other extensions used

None

### Screenshot(s)

<details>

![Screenshot (20240402-092944)](https://github.com/uBlockOrigin/uAssets/assets/50235321/0e4d2b0c-7d6f-4c39-873f-70bfa54ad74e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 137206
 cosmetic: 118565
 scriptlet: 26472
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 9890-2, 2d.18h.18m
  adguard-popup-overlays: 26991-48, 2d.18h.18m
  fanboy-cookiemonster: 50731-197, 1d.20h.37m
  ublock-cookies-easylist: 1063-3, 1d.20h.37m
 default:
  user-filters: 99-1, never
  easylist: 84516-180, 29m Δ
  easyprivacy: 50423-72, 29m Δ
  plowe-0: 3765-1183, 10d.14h.21m
  ublock-badware: 8098-140, 29m Δ
  ublock-filters: 37337-468, 29m Δ
  ublock-privacy: 781-5, 29m Δ
  ublock-quick-fixes: 194-4, 29m Δ
  ublock-unbreak: 2240-36, 29m Δ
  urlhaus-1: 8610-5, 17h.38m
filterset (user): [array of 99 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 7 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 489 ms (selfie)
 maxAssetCacheWait: 207 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by stephenhawk8054** [comment]
Test in a new browser profile with only uBO and its default settings.
