### ISSUE TITLE
comeforvid0z.click: [unknown]

### ISSUE THREAD

**Issue by omar1115** [uBlockOrigin/uAssets#23141]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://comeforvid0z.click/?660b1a342c094=8fa1883a43ef076f0fb031508f75c605&660b1a342c0ad=39&660b1a342c0ae=1_full-movie-hd&somato=692912`

### Category

[unknown]

### Description

Please block this link and consider it an advertisement because it always comes to me

### Other extensions used

no thing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128154
 cosmetic: 45867
 scriptlet: 20354
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37493-269, 11m Δ
  ublock-badware: 8093-15, 11m Δ
  ublock-privacy: 781-0, 1h.11m
  ublock-unbreak: 2240-0, 1h.11m
  ublock-quick-fixes: 194-0, 1h.11m
  easylist: 84516-763, 11m Δ
  easyprivacy: 50423-832, 11m Δ
  urlhaus-1: 8905-5, 1h.11m
  plowe-0: 3763-0, 1h.11m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1981 ms
 maxAssetCacheWait: 1050 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
> an advertisement because it always comes to me

if you always get it => it could be your system is infested by some malware
