### ISSUE TITLE
phoronix.com: detection

### ISSUE THREAD

**Issue by Jusix** [uBlockOrigin/uAssets#23154]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.phoronix.com/review/tuxedo-pulse14-gen3`

### Category

detection

### Description

A popup appears.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/8763014/5cb9182a-1c4c-4392-b67a-fb4b1f62df32)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 128023
 cosmetic: 50742
 scriptlet: 18960
 html: 1730
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 default:
  user-filters: 0-0, never
  ublock-filters: 37464-126, now
  ublock-badware: 8131-15, now
  ublock-privacy: 777-0, now
  ublock-unbreak: 2297-0, now
  ublock-quick-fixes: 214-0, now
  easylist: 84558-398, now
  easyprivacy: 50425-60, now
  urlhaus-1: 8920-5, now
  DEU-0: 7362-2, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 360 ms (selfie)
 maxAssetCacheWait: 89 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  pub.network: 1
  twitter.com: 1
 extended:
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
```
</details>

**Comment by D4niloMR** [comment]
Enable uBlock filters – Annoyances list and test again.
