### ISSUE TITLE
aniwave.to: unable to add to temporary rules list

### ISSUE THREAD

**Issue by megatronusprimee** [uBlockOrigin/uAssets#23151]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://aniwave.to/watch/transformers-cybertron.2pm0/ep-1
```

### Description

I use uBlock Origin in Microsoft Edge. Whenever I try to add a "no-popups: aniwave.to" on the temporary rules list, it always erases it after clicking the "Save" button.

### Other extensions used

Bitdefender Anti-tracker
File Centipede
Microsoft Rewards
RoPro - Enhance Your Roblox Experience
RoGold - Level Up Roblox
BTRoblox -  Making Roblox Better
Google Docs Offline
Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

No response

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128173
 cosmetic: 45768
 scriptlet: 20335
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37344-269, 27m
  ublock-badware: 8129-15, 27m
  ublock-privacy: 781-0, 27m
  ublock-unbreak: 2240-0, 27m
  ublock-quick-fixes: 194-0, 27m
  easylist: 84516-763, 27m
  easyprivacy: 50424-832, 27m
  urlhaus-1: 8920-5, 27m
  plowe-0: 3763-0, 27m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1593 ms
 maxAssetCacheWait: 21 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  bidgear.com: 3
  boundarygoose.com: 1
  cloudflareinsights.com: 2
  comitalmows.com: 1
  disqus.com: 1
  du0pud0sdlmzf.cloudfront.net: 1
  foolishjunction.com: 1
  googletagmanager.com: 2
  magsrv.com: 1
  sharethis.com: 2
 extended:
  ##.adx
  ##+js(no-window-open-if, _blank)
  ##+js(set-cookie, __pf, 1)
  ##+js(abort-on-property-read, AaDetector)
  ###overlayads
  ##+js(abort-on-property-write, adcashMacros)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…

```
</details>

**Comment by mapx-** [comment]
you have to add

`no-popups: aniwave.to true`
