### ISSUE TITLE
bokadirekt.se: breakage

### ISSUE THREAD

**Issue by coolriver242** [uBlockOrigin/uAssets#23159]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bokadirekt.se/boka-tjanst/simcoachense-7446/pt-par-solna-simhall-57386`

### Category

breakage

### Description

if you click on the "mer info" link, the pop up is blocked. 
verified in incognito mode and edge. cookies cleaned.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 144497
 cosmetic: 58999
 scriptlet: 20778
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 25530-142, now
  SWE-1: 4590-8, now
 default:
  user-filters: 0-0, never
  easylist: 84294-695, now
  easyprivacy: 50425-820, now
  plowe-0: 3764-0, now
  ublock-badware: 8219-15, now
  ublock-filters: 37345-391, now
  ublock-privacy: 781-0, now
  ublock-quick-fixes: 203-0, 40m Δ
  ublock-unbreak: 2240-20, now
  urlhaus-1: 9130-5, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3832 ms
 maxAssetCacheWait: 1398 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  facebook.net: 1
  google.com: 3
  googletagmanager.com: 1
  sentry.io: 3
  snapchat.com: 1
 extended:
  ##.ReactModalPortal, a:not([href*="bokadirekt.se"]):not([href^="…
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
bokadirekt.se##.ReactModalPortal, a:not([href*="bokadirekt.se"]):not([href^="/"]) img
bokadirekt.se##body:style(overflow:initial!important)
```

in `Frellwit's Swedish Filter` list

@lassekongo83 Sorry can you check this?
