### ISSUE TITLE
idnes.cz: dark theme broken

### ISSUE THREAD

**Issue by MrtkaZKrdka** [uBlockOrigin/uAssets#23160]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.idnes.cz/`

### Category

breakage

### Description

Dark theme while using unblock reverses only text, but background is white instead of black. No issues with add on disabled. 

### Other extensions used

S3. Translator

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 130044
 cosmetic: 38143
 scriptlet: 19186
 html: 1732
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37820-351, 1h.17m Δ
  ublock-badware: 8150-15, 1h.17m Δ
  ublock-privacy: 777-1, 1h.17m Δ
  ublock-unbreak: 2302-1, 1h.17m Δ
  adguard-mobile: 9217-134, now
  easylist: 84530-16476, 1h.17m Δ
  easyprivacy: 50425-874, 1h.17m Δ
  urlhaus-1: 9130-5, 1h.16m
  plowe-0: 3764-0, now
  CZE-0: 833-47, 1h.17m
  ublock-quick-fixes: 214-0, 1h.17m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 287 ms (selfie)
 maxAssetCacheWait: 138 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cpex.cz: 3
  gemius.pl: 1
  googletagmanager.com: 1
  r2b2.cz: 1
 extended:
  ##body:style(background: none !important; overflow: auto !import…
  ##+js(addEventListener-defuser, beforeunload, ())
  ##+js(abort-current-script, document.createElement, adbDetect)
  ##+js(remove-cookie, /^_?adb/)
  ##+js(abort-current-script, HTMLIFrameElement.prototype.contentW…
  ##+js(no-setTimeout-if, /Adform|didomi|adblock|forEach/)
```
</details>

**Comment by stephenhawk8054** [comment]
How can you change to dark theme on that site?

**Comment by MrtkaZKrdka** [comment]
Hello,
as shown in the picture. Bottom of each article.
 
 
S pozdravem/Regards
 
Michal Janováč
tel.:+420776148234
 
______________________________________________________________
> Od: "stephenhawk8054" ***@***.***>
> Komu: "uBlockOrigin/uAssets" ***@***.***>
> Datum: 03.04.2024 14:11
> Předmět: Re: [uBlockOrigin/uAssets] idnes.cz: dark theme broken (Issue #23160)
>
> CC: ***@***.***, ***@***.***>
 
How can you change to dark theme on that site?
