### ISSUE TITLE
benzinpreis.de: detection

### ISSUE THREAD

**Issue by derestle-htwg** [uBlockOrigin/uAssets#23161]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.benzinpreis.de`

### Category

detection

### Description

Site will load for a second then url gets changed an an AdBlock.phtml site. There they request to deactivate AdBlock.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox Mobile: 124
filterset (summary):
 network: 131732
 cosmetic: 42352
 scriptlet: 19030
 html: 1731
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37823-367, 1h.30m Δ
  ublock-badware: 8215-15, 1h.30m Δ
  ublock-privacy: 777-1, 1h.30m Δ
  ublock-unbreak: 2302-1, 1h.30m Δ
  ublock-quick-fixes: 214-0, 1h.30m Δ
  adguard-mobile: 9221-134, now
  easylist: 84295-16483, 1h.30m Δ
  easyprivacy: 50425-878, 1h.30m Δ
  urlhaus-1: 8890-0, now
  plowe-0: 3764-0, now
  DEU-0: 7362-408, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 885 ms (selfie)
 maxAssetCacheWait: 142 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Does `benzinpreis.de##+js(nostif, adblock)` works without breakage?

**Comment by mapx-** [comment]
maybe

```
benzinpreis.de##+js(nostif, adblock)
benzinpreis.de##+js(set, consentGiven, true)
```

**Comment by JobcenterTycoon** [comment]
See no breakage. Added.
