### ISSUE TITLE
app.vaia.com: ads

### ISSUE THREAD

**Issue by MrTahWasTaken** [uBlockOrigin/uAssets#23163]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [ ] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.vaia.com/`

### Category

ads

### Description

The website has ads, specifically when reviewing flashcards. After reviewing them for a while, one or two ads may pop up, before you may continue your previous activity.
There's also some big ads on the right in the main menu that are already blocked, but leave out a big empty space.

A previous issue on this website got closed a while ago because the original poster never had an account to share. However, I DO have a temporary account I'm willing to share if needed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 128146
 cosmetic: 45810
 scriptlet: 20349
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 39-0, never
  easylist: 84396-139, now
  easyprivacy: 50427-12, now
  plowe-0: 3764-1182, now
  ublock-badware: 8244-140, now
  ublock-filters: 37350-366, now
  ublock-privacy: 781-5, now
  ublock-quick-fixes: 211-10, now
  ublock-unbreak: 2240-33, now
  urlhaus-1: 8890-0, 11m
filterset (user): [array of 39 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 426 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 48
 network:
  amplitude.com: 37
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  lr-in.com: 1
  paypal.com: 2
  sentry.io: 4
 extended:
  ##aside > .ng-star-inserted
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
- send your account credentials here: `axis.trivia@gmail.com`
- provide the exact steps to get the ads
- provide screenshots indicating the ads

**Comment by MrTahWasTaken** [comment]
@mapx- I've sent an email. Hopefully you received it.

**Comment by MrTahWasTaken** [comment]
I have a 2025 update!

As of recent the same issues that I previously stated in my original post have returned.
The only difference this time is that there's no longer a blank space on the right hand side as the ads haven't been blocked.

I still have the same dummy account that can be used for testing should it be needed.

**Comment by stephenhawk8054** [comment]
Can you send to this email: `stephenhawk8054@protonmail.com`?

**Comment by MrTahWasTaken** [comment]
@stephenhawk8054 sent an email – hopefully you got it!

**Comment by stephenhawk8054** [comment]
@MrTahWasTaken I still can't reproduce the issue:

https://github.com/user-attachments/assets/4a5ab29b-19d2-4325-bf42-a1fb3e2d8fc7

**Comment by MrTahWasTaken** [comment]
It's a bit of a luck based thing – if you keep clicking you should be able to. Worst case scenario perhaps 20 flashcards.

https://github.com/user-attachments/assets/ce1ec5db-a96d-48e6-b4d1-42bc3ef29932

**Comment by stephenhawk8054** [comment]
I clicked about 50 times and nothing happened. If it's random and based on luck, I can't help further, I can't sit all day just to click on this site.

**Comment by MrTahWasTaken** [comment]
I'm sorry to hear that – I've never heard anyone in my class say they went even a fifth of that amount without an ad, let alone 50, so that's very bizarre.
On the plus side, at least the other ads can be fixed right?

**Comment by stephenhawk8054** [comment]
I don't see any other ads on the site. Where are they?

**Comment by MrTahWasTaken** [comment]
I decided to log into that account again to figure out what's going on and it looks like ads _have_ dissapeared... for that account.
I tried swapping over to my personal account and the problems still persist which is really strange – I'll just attach an example screenshot below.
As a test I made a brand new account (I'll mail the login details) and the ads problem seems to have returned the way I originally told you which is interesting.

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/be1efe4c-d48f-445b-ba6a-a015a8acd096" />

**Comment by stephenhawk8054** [comment]
Can you test these filters:

```adb
||prod.studysmarter.de/joboffers/
||prod.studysmarter.de/affiliate/
```

Go to uBO's settings > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by MrTahWasTaken** [comment]
Having a trial run, everything looks good. Thanks!
