### ISSUE TITLE
shop-apotheke.com: nuisance

### ISSUE THREAD

**Issue by jobluetooth** [uBlockOrigin/uAssets#23164]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.shop-apotheke.com/`

### Category

nuisance

### Description

popup

### Other extensions used

i don't care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 130340
 cosmetic: 50768
 scriptlet: 18964
 html: 1730
listset (total-discarded, last-updated):
 default:
  user-filters: 30-0, never
  ublock-filters: 37468-226, 1h.2m Δ
  ublock-badware: 8221-15, 1h.2m Δ
  ublock-privacy: 777-0, 1h.2m Δ
  ublock-unbreak: 2297-0, 1h.2m Δ
  easylist: 84295-664, 1h.2m Δ
  easyprivacy: 50425-877, 1h.2m Δ
  plowe-0: 3764-0, now
  DEU-0: 7362-3, now
  urlhaus-1: 8890-0, now
  ublock-quick-fixes: 214-0, 1h.2m Δ
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 64 redacted]
 removed:
  edge-scheme
userSettings:
 cloudStorageEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 890 ms (selfie)
 maxAssetCacheWait: 203 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  es.io: 2
  google.com: 4
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
it should work:

`shop-apotheke.com##+js(set-session-storage-item, ErxModal, true)`

@ryanbr
