### ISSUE TITLE
1337x.to: ads

### ISSUE THREAD

**Issue by tjcameron** [uBlockOrigin/uAssets#23167]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1337x.to/torrent/6047870/Snack-Shack-2024-1080p-AMZN-WEBRip-DDP5-1-x265-10bit-GalaxyRG265/`

### Category

Ads

### Description

Any Click or Right Click of Magnet Download or Torrent Download will bring up "Free VPN Account Recommend by 1337x" dialog that prevents any interaction with the page. Highlighted in Red box on the Screenshot attached.

Can't utilize the site - blocks the ability to select Torrent or Magnet Address
This started in the last couple of days
Similar to 3xploiton3 Reported issue https://github.com/uBlockOrigin/uAssets/issues/22401 that was resolved on 2/9/2024

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="740" alt="1337x Screen Shot Edited" src="https://github.com/uBlockOrigin/uAssets/assets/17729029/70b5343e-d169-4bf1-b29f-6e68708592b0">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 128158
 cosmetic: 45784
 scriptlet: 20357
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84412-139, now
  easyprivacy: 50435-12, now
  plowe-0: 3764-1182, now
  ublock-badware: 8244-140, now
  ublock-filters: 37354-366, now
  ublock-privacy: 781-5, now
  ublock-quick-fixes: 216-10, now
  ublock-unbreak: 2240-33, now
  urlhaus-1: 8890-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 361 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  1337x.to: 1
  ippleshiswashis.info: 2
 extended:
  ##[href*="vpn"]
  ##[onclick*="vpn"]
  ##:xpath('//*[contains(text(),"Hide your IP")]/..')
  ##+js(remove-node-text, script, style)
  ##+js(abort-on-stack-trace, document.createElement, _0x)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, afScript)
  ##+js(no-setTimeout-if, adb)
  ##+js(nowebrtc)
  ##+js(abort-on-property-read, AaDetector)
  ##+js(addEventListener-defuser, popstate)
  ##+js(abort-on-stack-trace, navigator, FingerprintJS)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
```
</details>

**Comment by yotoprules** [comment]
Fix: Add this to your filters:
`1337x.vpnonly.site/ipinfo.php?js=6`

**Comment by DickShackleford** [comment]
> Fix: Add this to your filters: `1337x.vpnonly.site/ipinfo.php?js=6`

This worked for me. Thanks.

**Comment by stephenhawk8054** [comment]
```adb
||1337x.vpnonly.site^
```

@ryanbr
