### ISSUE TITLE
dailyboulder.com: detection

### ISSUE THREAD

**Issue by frshhh** [uBlockOrigin/uAssets#23169]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dailyboulder.com/trumps-bond-filing-bungled-court-rejects-submission-due-to-missing-financial-statement/`

### Category

detection

### Description

Upon visiting the website, after a couple of seconds the page fades to black and is replaced with a "Adblock detected" overlay. (see screenshot)

I tried using the element zapper to get rid of the adblock block but it returns after refreshing.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/7753557/5a027e86-120c-487e-9527-0500e83d474f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 139119
 cosmetic: 199900
 scriptlet: 28482
 html: 1732
listset (total-discarded, last-updated):
 added:
  adguard-social: 22736-860, now
  fanboy-cookiemonster: 50765-3885, now
  fanboy-social: 15850-10, now
  adguard-cookies: 29134-66, now
  adguard-popup-overlays: 27025-1558, now
  adguard-mobile-app-banners: 5117-1087, now
  adguard-other-annoyances: 14118-294, now
  adguard-widgets: 2453-1, now
  easylist-annoyances: 4455-125, now
  easylist-chat: 188-15, now
  easylist-newsletters: 7161-12, now
  easylist-notifications: 2975-3, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  ublock-filters: 37475-440, now
  ublock-badware: 8246-15, now
  ublock-privacy: 782-0, now
  ublock-unbreak: 2297-0, now
  ublock-quick-fixes: 218-0, now
  easylist: 84412-848, now
  easyprivacy: 50435-976, now
  urlhaus-1: 8890-0, now
  plowe-0: 3765-0, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 863 ms (selfie)
 maxAssetCacheWait: 155 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  dailyboulder.com: 4
  googlesyndication.com: 4
  googletagmanager.com: 1
  infolinks.com: 2
  taboola.com: 1
  twitter.com: 1
 extended:
  ##.top-site-ad
  ##ins.adsbygoogle[data-ad-slot]
  ###rb-privacy
  ##.privacy-bar
  ##.share-action
  ##.share-trigger
  ##.t-shared-sec
  ##.share-label
  ##.l-shared-sec-outer
  ##.icon-flipboard
  ##.icon-reddit
  ##.ad-wrap
  ###taboola-below-article-thumbnails
  ##.entry-newsletter
  ##.mc4wp-form
  ##.e-shared-sec
  ##.ad-description
  ###cookie-notice
  ##.cookie-revoke-hidden
  ##.cn-position-bottom
  ##.cookie-notice-container
  ###back-top
  ##a[href^="https://share.flipboard.com/bookmarklet/popout?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.reddit.com/submit?"]
  ##a[href^="https://www.reddit.com/submit"]
  ##a[href^="https://share.flipboard.com/bookmarklet/"]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  ##+js(set-cookie, twtr_pixel_opt_in, N)
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
```
</details>

**Comment by meldroc** [comment]
I just got a detection as of 8/28/2025. Perhaps dailyboulder.com changed their anti-adblock?
