### ISSUE TITLE
olx.pl: breakage

### ISSUE THREAD

**Issue by ludexter** [uBlockOrigin/uAssets#23175]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
www.olx.pl
```

### Description

OLX is a big-ish site to sell/buy used items. Search engine doesn't work. After sign-in, there are some bugs, not everything is shown. I tried disabling uBlock and it definitely helped. Sometimes Ctrl+F5 works for a little while. This problem is visible on newest Firefox, Win10 x64, experiencing this issue(s) longer than 2 months, so I decided to let You know. Thanks in advice! 
With kindness ~Peter

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![icannotClickOnItems](https://github.com/uBlockOrigin/uAssets/assets/43359243/34b92962-abc0-4117-b3c9-a52f06161ab9)
I cant click on items, (only uBlock enable!)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 129790
 cosmetic: 53999
 scriptlet: 19188
 html: 1743
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37465-104, now
  ublock-badware: 8262-15, now
  ublock-privacy: 780-0, now
  ublock-unbreak: 2297-2, now
  ublock-quick-fixes: 224-8, now
  easylist: 84416-378, now
  easyprivacy: 50435-61, now
  urlhaus-1: 9055-5, now
  plowe-0: 3766-1182, now
  POL-0: 8740-46, now
  POL-2: 1283-48, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 331 ms
 maxAssetCacheWait: 124 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  appboycdn.com: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  newrelic.com: 2
  olx-st.com: 9
  olx.org: 3
  sentry.io: 2
  unpkg.com: 1
 extended:
  ##[data-cy="l-card"]:has([data-testid="adCard-featured"])
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]

```
</details>

**Comment by ludexter** [comment]
Thanks for your answer. I think there is a script that ensures that specific (maybe periodic) ads are loaded (or visible) and THEN you can click on things. If uBO blocks it, then no clicking allowed. It goes worse if you are logged and try for example view your list of stuff to sell. But the most annoying is when switching from "my account" to "search". Weird, now I tried, everything works faster and no bugs. Maybe loading errors will show today/soon.

**Comment by mapx-** [comment]
search is working fine on my side FF / chrome
