### ISSUE TITLE
canadiantire.ca: breakage

### ISSUE THREAD

**Issue by Papabeezer** [uBlockOrigin/uAssets#23172]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.canadiantire.ca/en/pdp/canvas-renfrew-square-outdoor-patio-conversation-dining-set-w-uv-resistant-cushions-3-pc-0882040p.0882040.html?rq=store+promotion`

### Category

breakage

### Description

Product reviews section is being blocked/hidden when ublock origin is enabled for the site. If I disable Ublock, then the prodcut reviews show again.

### Other extensions used

Facebook Purity
Facebook Container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 128302
 cosmetic: 45772
 scriptlet: 18973
 html: 1732
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37473-142, now
  ublock-badware: 8246-15, now
  ublock-privacy: 780-0, now
  ublock-unbreak: 2297-0, now
  easylist: 84414-761, now
  easyprivacy: 50435-832, now
  urlhaus-1: 9055-5, now
  plowe-0: 3766-0, now
  ublock-quick-fixes: 218-0, now
filterset (user): [empty]
trustedset:
 added: [array of 34 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 669 ms (selfie)
 maxAssetCacheWait: 193 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  canadiantire.ca: 4
  adobedtm.com: 5
  appboycdn.com: 1
  coherentpath.com: 1
  curalate.com: 1
  evergage.com: 2
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  kampyle.com: 1
  maps.googleapis.com: 1
  newrelic.com: 2
  optimizely.com: 4
  signifyd.com: 1
 extended:
  ##.google-ads
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=canadiantire.ca
```

@ryanbr
