### ISSUE TITLE
[nsfw] 4fans.gay: detection

### ISSUE THREAD

**Issue by kerzankerim** [uBlockOrigin/uAssets#23174]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://4fans.gay/latest/`

### Category

detection

### Description

this web site do not let you run the add block

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/165980590/3f8fc98d-8892-420e-ac5c-ccd311ab9e12)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128314
 cosmetic: 45789
 scriptlet: 20362
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 84416-761, 53m Δ
  easyprivacy: 50435-813, 53m Δ
  plowe-0: 3766-0, now
  ublock-badware: 8244-15, 53m Δ
  ublock-filters: 37346-275, 53m Δ
  ublock-privacy: 783-0, 53m Δ
  ublock-quick-fixes: 216-0, 53m Δ
  ublock-unbreak: 2240-19, 53m Δ
  urlhaus-1: 9055-5, now
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 314 ms (selfie)
 maxAssetCacheWait: 130 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  4fans.gay: 3
  giggleostentatious.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  magsrv.com: 1
  pemsrv.com: 1
  wp.com: 1
 extended:
  ##.ads-wrapper
  ##.adlink
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##+js(set-constant, rwt, noopFunc)
```
</details>this web site do not let you run the add block

![Capture](https://github.com/uBlockOrigin/uAssets/assets/165980590/84d67621-99b2-4b87-a1e8-918229d323bf)

**Comment by Oqarshi** [comment]
prob should label this a nsfw
