### ISSUE TITLE
op.gg: ads

### ISSUE THREAD

**Issue by mantoudayo** [uBlockOrigin/uAssets#23178]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.op.gg/champions`

### Category

ads

### Description

opgg的会员广告无法去除 

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 142737
 cosmetic: 56325
 scriptlet: 20548
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 17-12, never
  CHN-0: 25530-143, now
  easylist: 84421-688, now
  easyprivacy: 50437-813, now
  plowe-0: 3766-0, now
  ublock-badware: 8260-15, now
  ublock-filters: 37353-393, now
  ublock-privacy: 783-0, now
  ublock-quick-fixes: 222-0, now
  ublock-unbreak: 2240-19, now
  urlhaus-1: 8815-0, now
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 438 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  op.gg: 10
  cleanhaircut.com: 1
  connatix.com: 1
  doubleclick.net: 2
  google.com: 12
  googletagmanager.com: 2
  hackle.io: 5
  riotgames.com: 1
  vntsm.com: 1
  youtube.com: 6
  zendesk.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. Add this as your custom filter

```adb
op.gg##.premium-banner
```

**Comment by mantoudayo** [comment]
解决了 谢谢
