### ISSUE TITLE
laravel-news.com: ads

### ISSUE THREAD

**Issue by rabol** [uBlockOrigin/uAssets#23176]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://laravel-news.com/creating-helpers`

### Category

ads

### Description

In the lower right corner is an ad

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-04 at 14 46 06](https://github.com/uBlockOrigin/uAssets/assets/1177191/6211a149-0d25-4813-9cfd-c3cf145fad4d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 128098
 cosmetic: 45790
 scriptlet: 20363
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84416-139, 1m Δ
  easyprivacy: 50435-12, 1m Δ
  plowe-0: 3766-1182, now
  ublock-badware: 8260-140, 1m Δ
  ublock-filters: 37346-362, 1m Δ
  ublock-privacy: 783-5, 1m Δ
  ublock-quick-fixes: 222-10, 1m Δ
  ublock-unbreak: 2240-33, 1m Δ
  urlhaus-1: 8815-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 133 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 53
 network:
  cloudflareinsights.com: 1
  doubleclick.net: 2
  facebook.net: 1
  google.com: 12
  googletagmanager.com: 1
  typekit.net: 1
  usefathom.com: 1
  youtube.com: 34
 extended:
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(trusted-replace-fetch-response, '/"auxiliaryUi":\{"message…
  ##+js(trusted-replace-fetch-response, /("trackingParam":"kx_fmPx…
  ##+js(trusted-replace-fetch-response, /("trackingParam":"k5DfmPx…
  ##+js(trusted-replace-xhr-response, '/"auxiliaryUi":\{"messageRe…
  ##+js(trusted-replace-xhr-response, /("trackingParam":"kx_fmPxho…
  ##+js(trusted-replace-xhr-response, /("trackingParam":"k5DfmPxho…
```
</details>

**Comment by mapx-** [comment]
add

`laravel-news.com##.relative:has([wire\:key="article-ad-card"])`

@ryanbr
