### ISSUE TITLE
freegames.io: breakage

### ISSUE THREAD

**Issue by mortembeatus2** [uBlockOrigin/uAssets#23186]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://freegames.io/game/hole-io`

### Category

breakage

### Description

The games on the site do not work.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 129682
 cosmetic: 54950
 scriptlet: 21856
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 12155-14, now
  easylist: 84337-663, now
  easyprivacy: 50438-837, now
  plowe-0: 3766-1, now
  ublock-badware: 8286-15, now
  ublock-filters: 37356-287, now
  ublock-privacy: 783-0, now
  ublock-quick-fixes: 216-0, now
  ublock-unbreak: 2240-1, now
  urlhaus-1: 8880-0, 27m
filterset (user): [empty]
trustedset:
 added: [array of 80 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 896 ms (selfie)
 maxAssetCacheWait: 678 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 47
 network:
  3lift.com: 2
  4dex.io: 2
  adinplay.com: 1
  adnxs.com: 5
  bidswitch.net: 2
  btloader.com: 2
  casalemedia.com: 1
  cpmstar.com: 1
  doubleclick.net: 2
  gameads.io: 1
  googletagmanager.com: 3
  hole-io.com: 1
  imasdk.googleapis.com: 1
  indexww.com: 1
  onetag-sys.com: 5
  openx.net: 2
  pubmatic.com: 2
  rubiconproject.com: 3
  script.ac: 4
  sharethrough.com: 1
  the-ozone-project.com: 3
  unrulymedia.com: 1
  yellowblue.io: 1
 extended:
  ##.banner-ad-wrapper
```
</details>

**Comment by gorhill** [comment]
Also unable to reproduce.

- [x]  I did not answer truthfully to ALL the above checkboxes.

Go through the prerequisite steps again and answer truthfully this time.
