### ISSUE TITLE
windowsxlite.com: detection

### ISSUE THREAD

**Issue by tetz88** [uBlockOrigin/uAssets#23184]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://windowsxlite.com/
```

### Description

Detected

### Other extensions used

![Screenshot (20240405-142236)](https://github.com/uBlockOrigin/uAssets/assets/50235321/96976937-9ed3-4d78-b834-4b5ba279a317)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 137606
 cosmetic: 118629
 scriptlet: 26506
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 9896-2, 1d.17h.34m
  adguard-popup-overlays: 27028-48, 22h.56m
  fanboy-cookiemonster: 50731-197, 5d.1h.31m
  ublock-cookies-easylist: 1063-3, 5d.1h.31m
 default:
  user-filters: 99-1, never
  easylist: 84336-61, 41m Δ
  easyprivacy: 50438-72, 41m Δ
  plowe-0: 3766-1182, 19h.2m
  ublock-badware: 8285-140, 41m Δ
  ublock-filters: 37356-466, 41m Δ
  ublock-privacy: 783-5, 41m Δ
  ublock-quick-fixes: 216-12, 41m Δ
  ublock-unbreak: 2240-36, 41m Δ
  urlhaus-1: 8880-0, 41m
filterset (user): [array of 99 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 7 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 520 ms (selfie)
 maxAssetCacheWait: 244 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by ItsProfessional** [comment]
You have a somewhat customized configuration, reset uBO and test again.

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
