### ISSUE TITLE
homestuck.com: ads

### ISSUE THREAD

**Issue by RoseyCatttttt** [uBlockOrigin/uAssets#23181]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.homestuck.com/story`

### Category

ads

### Description

black ad skyscraper is still visible, though ads do not display for me

following filter was used to block skyscraper manually. testing without this filter still shows the skyscraper 
! 2024-04-05 https://www.homestuck.com
www.homestuck.com##.disp-bl--md.disp-n

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/120997459/3180a4b1-9a55-42f1-828e-7a758cb80a85)
![image](https://github.com/uBlockOrigin/uAssets/assets/120997459/cbec6058-804a-4a2e-ab92-a99bdf9192c6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 128075
 cosmetic: 45774
 scriptlet: 18978
 html: 1732
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37472-104, now
  ublock-badware: 8262-15, now
  ublock-privacy: 780-1, now
  ublock-unbreak: 2297-2, now
  ublock-quick-fixes: 212-10, now
  easylist: 84421-378, now
  easyprivacy: 50437-61, now
  urlhaus-1: 8815-0, now
  plowe-0: 3766-1182, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3107 ms
 maxAssetCacheWait: 226 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  google-analytics.com: 1
  google.com: 5
  googletagservices.com: 1
  typekit.net: 1
 extended:
  ##.disp-bl--md.disp-n
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
homestuck.com###desktop_skyscraper
```

@ryanbr
