### ISSUE TITLE
top.gg: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#23185]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://top.gg/`

### Category

ads leftovers

### Description

Page still shows ad containers all over

### Other extensions used

Bitwarden, dark reader, decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/8ef16a3a-9bc5-49d4-a566-2453c31ef00b)

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/79139d57-cdda-4c6f-8c74-62ebd4b56d97)

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/bf498f3c-9941-425e-b6f1-7c0a5a1907fe)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 123
filterset (summary):
 network: 146374
 cosmetic: 47108
 scriptlet: 20416
 html: 1732
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37467-104, now
  ublock-badware: 8221-15, now
  ublock-privacy: 780-1, now
  ublock-unbreak: 2297-2, now
  ublock-quick-fixes: 212-8, now
  easylist: 84418-378, now
  adguard-spyware-url: 1492-107, now
  easyprivacy: 50435-61, now
  urlhaus-1: 8880-0, now
  curben-phishing: 14092-1, now
  plowe-0: 3766-1183, now
  LegitimateURLShortener: 2625-167, now
  bpc-paywall-filter: 1065-2, now
  AntiPaywall: 2095-34, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2779 ms
 maxAssetCacheWait: 12 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  top.gg: 2
  anonymised.io: 2
  btloader.com: 1
  cloudflare.com: 20
  datadome.co: 2
  doubleclick.net: 1
  googletagmanager.com: 2
  green-bot.app: 4
  moatads.com: 2
  network-n.com: 3
  pbstck.com: 1
  permutive.app: 1
  sattler.dev: 2
  scorecardresearch.com: 1
 extended:
  ##+js(adjust-setTimeout, readyToVote, 12000)
```
</details>

**Comment by gorhill** [comment]
This works for me:

    top.gg##[class*="AdHeaderHero__AdContainer-"]

**Comment by ItsProfessional** [comment]
@ryanbr
