### ISSUE TITLE
accuradio.com: ads

### ISSUE THREAD

**Issue by ffsmyusernameistaken** [uBlockOrigin/uAssets#23182]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.accuradio.com/`

### Category

ads

### Description

Ads are being played between songs, it started happening maybe a month ago.

### Other extensions used

Google Translator, Tamper Monkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 109
filterset (summary):
 network: 121481
 cosmetic: 120062
 scriptlet: 39545
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1697-0, 49m
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 23058-87, now
  adguard-generic: 80457-660, now
 default:
  user-filters: 5-0, never
  RUS-0: 39466-2593, now
  easylist: 84336-1627, 50m Δ
  plowe-0: 3766-397, now
  ublock-badware: 8285-247, 50m Δ
  ublock-filters: 37356-3447, 50m Δ
  ublock-privacy: 783-11, 50m Δ
  ublock-quick-fixes: 216-12, 50m Δ
  ublock-unbreak: 2240-84, 50m Δ
  urlhaus-1: 8880-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 16 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 164077 ms
 maxAssetCacheWait: 1437 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 27
 network:
  accuradio.com: 5
  adswizz.com: 4
  cloudflareinsights.com: 1
  demdex.net: 2
  dn0qt3r0xannq.cloudfront.net: 1
  doubleclick.net: 2
  ensighten.com: 1
  exelator.com: 3
  googletagmanager.com: 1
  googletagservices.com: 1
  primis.tech: 2
  s3.amazonaws.com: 1
  streamtheworld.com: 1
  tritondigital.com: 2
 extended:
  ###slot2Wrapper
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
||live.streamtheworld.com/ondemand/ars?$xhr,3p
||vader.amperwave.net/*/instream/$xhr,3p
```
