### ISSUE TITLE
arcanescans.com: nuisance

### ISSUE THREAD

**Issue by DeathDoors** [uBlockOrigin/uAssets#23180]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://arcanescans.com/manga/legendary-car-hailing-system/chapter-5/`

### Category

nuisance

### Description

There is a png from wallpapercanvas that i cant get rid of no matter what i have tried. Its giving a warning about ad block which I dont need to see on each page. Zapping works but filter doesn't.

Below is where I tried to get help before this.
https://www.reddit.com/r/uBlockOrigin/comments/1bvxu05/comment/ky2s0gu/?context=3
I have tried to block using the picker, using the help DrTomDice I have tried other filters.

### Other extensions used

Was only using Ubo, but added noscript to see if i could fix the issue through there.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-04 225957](https://github.com/uBlockOrigin/uAssets/assets/125616429/2da714f9-bb93-44d1-9028-5e8e593b0e32)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 142278
 cosmetic: 45775
 scriptlet: 18978
 html: 1732
listset (total-discarded, last-updated):
 added:
  curben-phishing: 14182-1, 1h.22m
 default:
  user-filters: 25-1, never
  ublock-filters: 37472-104, 1h.17m Δ
  ublock-badware: 8262-15, 1h.52m Δ
  ublock-privacy: 780-1, 1h.17m Δ
  ublock-unbreak: 2297-2, 1h.52m Δ
  ublock-quick-fixes: 212-10, 1h.52m Δ
  easylist: 84421-378, 1h.17m Δ
  easyprivacy: 50437-61, 1h.52m Δ
  urlhaus-1: 8815-0, 1h.22m
  plowe-0: 3766-1183, 1h.22m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 138 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 58
 no-cosmetic-filtering: true
 no-remote-fonts: true
 network:
  arcanescans.com: 7
  bidgear.com: 2
  clarity.ms: 1
  cloudflare.com: 2
  disqus.com: 4
  google.com: 7
  googlesyndication.com: 14
  googletagmanager.com: 2
  gstatic.com: 12
  ko-fi.com: 2
  onesignal.com: 2
  pubfuture-ad.com: 2
  wallpapercave.com: 1
```
</details>

**Comment by DeathDoors** [comment]
![logger2024-04-04 232410](https://github.com/uBlockOrigin/uAssets/assets/125616429/4916ff38-c915-4d00-8474-aacfb06102af)
Logger showing it to be blocked

**Comment by stephenhawk8054** [comment]
Test in a new Firefox profile with only uBO and its default settings.

**Comment by gorhill** [comment]
> I have verified that other extensions are not causing the issue.

> Issue: DuckDuckGo
