### ISSUE TITLE
emojipedia.org: breakage

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#23191]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://emojipedia.org/skull`

### Category

breakage

### Description

The navbar is moved down, making it overlap with the entry

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/11874211/3956fa8e-f9e1-4775-9899-6b48e810e7fe)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 123
filterset (summary):
 network: 128170
 cosmetic: 45779
 scriptlet: 18989
 html: 1732
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37484-145, 1m
  ublock-badware: 8303-15, 1m
  ublock-privacy: 780-0, now Δ
  ublock-unbreak: 2297-0, now Δ
  ublock-quick-fixes: 212-0, now Δ
  easylist: 84370-642, 1m
  easyprivacy: 50440-832, 1m
  urlhaus-1: 8810-0, 1m
  plowe-0: 3758-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 504 ms
 maxAssetCacheWait: 167 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  hotjar.com: 1
  pub.network: 1
 extended:
  ##.h-\[112px\]
  ##div[class^="AdContainer"]
```
</details>

**Comment by saccma** [comment]
this is happening again to me ☹️

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 141
filterset (summary):
 network: 155038
 cosmetic: 46959
 scriptlet: 23053
 html: 2358
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/Craftplacer/04089c2c666c89e10818124c92d9c65b/raw/FuckFandom.txt: 22-0, 58m
  ITA-0: 6307-10, 58m
 default:
  user-filters: 26-1, never
  ublock-filters: 40555-71, 1h.58m Δ
  ublock-badware: 11434-17, 1h.58m Δ
  ublock-privacy: 3346-2, 1h.58m Δ
  ublock-unbreak: 2727-1, 1h.58m Δ
  ublock-quick-fixes: 285-13, 1h.58m Δ
  easylist: 75434-204, 1h.58m Δ
  easyprivacy: 54343-54, 1h.58m Δ
  urlhaus-1: 30920-0, 58m
  plowe-0: 3419-898, 58m
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 97 ms (selfie)
 maxAssetCacheWait: 31 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  emojipedia.org: 1
  googletagmanager.com: 1
  pub.network: 2
 extended:
  ###FreeStarVideoAdContainer
  ##.items-center:has([class^="AdContainer_ad"])
  ##.h-\[312px\]
  ##div[class^="AdContainer"]
  ##[data-freestar-ad][id]
```
</details>
