### ISSUE TITLE
honkailab.com: breakage

### ISSUE THREAD

**Issue by myurei** [uBlockOrigin/uAssets#23194]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://honkailab.com/characters/sparkle-build/`

### Category

breakage

### Description

Almost all ads are still displayed, and after a few moments the page completely breaks with error message "Too many inventory failures - honkailab/pc/all_top_banner_2" and a prompt to report the issue. Issue has been reported using said form with no changes. Have disabled all but default filters and issue persists. Issue is present through entire site, not just page linked.

### Other extensions used

Google Translate, Paypal Honey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/151973406/bc67f04e-371b-4ba0-9321-26dc81cd131a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 121
filterset (summary):
 network: 253428
 cosmetic: 249321
 scriptlet: 51654
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29175-33, 6m
  adguard-generic: 80486-4159, 6m
  adguard-mobile: 9233-16, 6m
  adguard-mobile-app-banners: 5126-8, 6m
  adguard-other-annoyances: 14120-350, 6m
  adguard-popup-overlays: 27042-909, 6m
  adguard-social: 22752-1612, 6m
  adguard-spyware: 102336-33263, 6m
  adguard-spyware-url: 1492-106, 6m
  adguard-widgets: 2457-18, 6m
  block-lan: 61-0, 6m
  curben-phishing: 14432-5, 38m
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 84379-2340, 6m
  easyprivacy: 50440-232, 6m
  plowe-0: 3758-1307, 6m
  ublock-badware: 8301-17, 6m
  ublock-filters: 37362-620, 6m
  ublock-privacy: 783-0, 6m
  ublock-quick-fixes: 216-0, 6m
  ublock-unbreak: 2240-25, 6m
  urlhaus-1: 8810-0, 38m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 90957 ms
 maxAssetCacheWait: 4432 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 309
 network:
  connatix.com: 1
  css-load.com: 305
  googlesyndication.com: 1
  googletagmanager.com: 1
  nitropay.com: 1
 extended:
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(prevent-fetch, /static\.criteo\.net|adsbygoogle/, length:1…
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed. But these ads are hard to block because they are protected by "Ad-Shield". Also fake "breakage" can appear.
**For the best blocking results try --> [microShield](https://github.com/List-KR/microShield) <--. Its a special userscript designed to block Ad-Shield related ads.**

**Comment by Oqarshi** [comment]
Why is adshield so hard to block?!?

**Comment by JobcenterTycoon** [comment]
They self breaking the page when they detect ad reinsertion Adblocking.

Just blocking their script will not work because the site moved the css of the site into the adshield script. Blocking -> broken site.
