### ISSUE TITLE
sfchronicle.com: breakage

### ISSUE THREAD

**Issue by roshkins** [uBlockOrigin/uAssets#23190]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sfchronicle.com/`

### Category

breakage

### Description

UBlock Origin prevents SF Chronicle's login system from working. It only shows me as logged out, and it doesn't show the Sign In link. When I am signed it, it shows me as unauthenticated.

I logged in after turning off the adblocker and turned it back on, this is what it shows
![image](https://github.com/uBlockOrigin/uAssets/assets/593949/73969931-2128-4574-a14c-7fd5cff868c7)

### Other extensions used

Bitwarden - Free Password Manager

2024.2.1

A secure and free password manager for all of your devices.

IDjbkfoedolllekgbhcbcoahefnbanhhlh

Inspect views

background.html
Details
Remove

Microsoft Editor: Spelling & Grammar Checker

v1.8.0

Write with confidence with Microsoft Editor, your intelligent grammar, spelling, and style checking writing assistant.

IDhokifickgkhplphjiodbggjmoafhignh

Inspect views

offscreen.html;
service worker
Details
Remove

Refreshless for Microsoft Edge

1.2.8.0

Automatically refresh a web page periodically

IDimikakimiedjagifepfgklmblemgkcna

Inspect views

Background page
Details
Remove

SponsorBlock for YouTube - Skip Sponsorships

5.5.9

Skip sponsorships, subscription begging and more on YouTube videos. Report sponsors on videos you watch to save others' time.

IDmbmgnelfcpoecdepckhlhegpcehmpmji

Inspect views

Background page (Inactive)
Details
Remove

uBlock Origin

1.57.0

Finally, an efficient blocker. Easy on CPU and memory.

IDodfafepnkmbhccpbejgmiehpchacaeak

Inspect views

background.html;
dashboard.html (iframe);
dashboard.html;
asset-viewer.html
Details
Remove

Alternate Player for Twitch.tv

2022.2.7.1

Alternate player of live broadcasts for Twitch.tv website.

IDbhplkbgoehhhddaoolmakpocnenplmhf

Inspect views

No active views

Details
Remove

Chrome Remote Desktop

2.1

Chrome Remote Desktop extension

IDinomeogfingihgjfjlpeplalcfajhgai

Inspect views

service worker (Inactive)
Details
Remove

Freevee Skipper: skip ads, intros & more

1.0.17

Automatically skip intros, recaps, block ads and click next episode button on Freevee

IDnfodepdbkedfahdadcglakjdmopkobon

Inspect views

service worker (Inactive)
Details
Remove

Google Docs Offline

1.75.4

We have readily installed this extension to help optimize your Google Docs experience when offline.

IDghbmnnjooekpmoecnnnilnnbdlolhkhi

Inspect views

No active views

Details
Remove

IPFS Companion

3.1.0

Harness the power of IPFS in your browser

IDnibjojkomfdiaoajekhjakgkdhaomnch

Inspect views

service worker
Details
Remove

Privacy | Protect Your Payments

2.3.0

Protect yourself from fraud and identity theft with disposable card numbers for use online

IDhmgpakheknboplhmlicfkkgjipfabmhp

Inspect views

service worker
Details
Remove

Return YouTube Dislike

3.0.0.14

Returns ability to see dislikes

IDgebbhagfogifgggkldgodflihgfeippi

Inspect views

service worker (Inactive)
Details
Remove

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

I logged in after turning off the adblocker and turned it back on, this is what it shows
![image](https://github.com/uBlockOrigin/uAssets/assets/593949/73969931-2128-4574-a14c-7fd5cff868c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 131385
 cosmetic: 103768
 scriptlet: 25486
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  easylist-annoyances: 4465-18, now
  easylist-chat: 189-0, now
  easylist-newsletters: 7167-12, now
  easylist-notifications: 2977-81, now
  fanboy-cookiemonster: 50791-196, now
  ublock-cookies-easylist: 1072-0, now
 default:
  user-filters: 7-1, never
  easylist: 84370-665, 10m Δ
  easyprivacy: 50440-897, 10m Δ
  plowe-0: 3758-0, now
  ublock-badware: 8301-15, 10m Δ
  ublock-filters: 37363-285, 10m Δ
  ublock-privacy: 783-0, 10m Δ
  ublock-quick-fixes: 216-0, 10m Δ
  ublock-unbreak: 2240-21, 10m Δ
  urlhaus-1: 8810-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 39 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1360 ms
 maxAssetCacheWait: 647 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 network:
  sfchronicle.com: 3
  3lift.com: 2
  adnxs.com: 1
  amazon-adsystem.com: 1
  casalemedia.com: 2
  chartbeat.com: 2
  criteo.com: 1
  criteo.net: 1
  d15kdpgjg3unno.cloudfront.net: 1
  doubleclick.net: 1
  dyv1bugovvq1g.cloudfront.net: 1
  googletagmanager.com: 1
  hearst3pcc.com: 1
  liadm.com: 4
  ml314.com: 1
  newrelic.com: 2
  ntv.io: 1
  openx.net: 2
  permutive.app: 1
  rubiconproject.com: 5
  sail-horizon.com: 1
  scorecardresearch.com: 1
  sfgate.com: 1
  webcontentassessor.com: 1
 extended:
  ##[data-block-type="ad"]
```
</details>

**Comment by liamengland1** [comment]
Test the following filters:

```
@@||q777.sfchronicle.com/script.js$1p
@@/DG/DEFAULT/rest/rpc/*$script,1p,domain=sfchronicle.com
||realm.hearst3pcc.com/utility/C3P0_RealmCookie$script,redirect=none:10
```

**Comment by roshkins** [comment]
That works for me. Thanks!

**Comment by liamengland1** [comment]
@mapx- the rule is also needed for `expressnews.com`

**Comment by mapx-** [comment]
@liamengland1 I see "sign in" link, how to reproduce the issue ?

**Comment by gorhill** [comment]
@mapx- I don't see it, I see it when adding `expressnews.com|` to the previously added filter.

**Comment by mapx-** [comment]
right, I'm able to reproduce the issue only using an us ip
