### ISSUE TITLE
aniworld.to: popups

### ISSUE THREAD

**Issue by Hyperioll** [uBlockOrigin/uAssets#23196]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniworld.to/`

### Category

popups

### Description

When I click on an episode to watch it, it opens up a new tab with some random ads. Usually ads pop up three times before I can watch an episode. This resets after a couple minutes of watching, but don't trigger unless I click to pause for example.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 255734
 cosmetic: 254294
 scriptlet: 51655
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29175-49, 14m
  adguard-generic: 80486-556, 14m
  adguard-mobile: 9233-143, 14m
  adguard-mobile-app-banners: 5128-10, 15m
  adguard-other-annoyances: 14120-67, 14m
  adguard-popup-overlays: 27042-179, 14m
  adguard-social: 22753-911, 14m
  adguard-spyware: 102336-1308, 14m
  adguard-spyware-url: 1492-5, 14m
  adguard-widgets: 2457-12, 15m
  block-lan: 61-0, 15m
  curben-phishing: 14243-2, 15m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  DEU-0: 7364-1, now
  easylist: 84378-2139, 1h.33m Δ
  easyprivacy: 50440-32713, 1h.33m Δ
  plowe-0: 3758-0, now
  ublock-badware: 8301-251, 1h.33m Δ
  ublock-filters: 37364-3996, 1h.33m Δ
  ublock-privacy: 783-219, 1h.33m Δ
  ublock-quick-fixes: 216-12, 1h.33m Δ
  ublock-unbreak: 2240-155, 1h.33m Δ
  urlhaus-1: 8930-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 764 ms (selfie)
 maxAssetCacheWait: 205 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  ads-twitter.com: 2
  imasdk.googleapis.com: 2
  laughingrecordinggossipy.com: 2
  yandex.com: 6
 extended:
  ##.addthis_inline_share_toolbox
  ##+js(abort-current-script, document.createElement, delete windo…
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by mapx-** [comment]
@Hyperioll 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
