### ISSUE TITLE
[nsfw] youtube.com: nuisance

### ISSUE THREAD

**Issue by begem** [uBlockOrigin/uAssets#23197]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=4YBGRGBj7_w&list=PLdkj6XH8GYPSMCsoD5Z55LxK-VLTwAgOA&index=47`

### Category

nuisance, irritating elements, autotranslation

### Description

An annoying request to press a button appears. attempt to add a custom filter (background, response menu) fails (initially the agree button is clicked)
#all checkbox sellect bcrse it need to send msg,- what wrong with u? 

### Other extensions used

1) single file- not activated on this page
2) gnome shell integration - fail, sys win10 (firefox)
3) video download helper- not active on this website
4) yahoo search

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
no screenshot bcrse i was pressed "ok"

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 152575
 cosmetic: 153787
 scriptlet: 25768
 html: 1748
listset (total-discarded, last-updated):
 added:
  adguard-social: 22753-47, now
  adguard-cookies: 29175-41, now
  ublock-cookies-adguard: 1071-12, now
  adguard-popup-overlays: 27042-970, now
  adguard-mobile-app-banners: 5128-21, now
  adguard-other-annoyances: 14121-412, now
  adguard-widgets: 2457-9, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37475-104, 1h.9m Δ
  ublock-badware: 8303-15, 9m Δ
  ublock-privacy: 782-0, 1h.9m Δ
  ublock-unbreak: 2297-2, 9m Δ
  ublock-quick-fixes: 212-8, now
  easylist: 84412-382, 1h.9m Δ
  easyprivacy: 50435-61, 1h.9m Δ
  urlhaus-1: 8930-0, now
  plowe-0: 3758-1183, now
  RUS-0: 39492-538, 9m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3816 ms (selfie)
 maxAssetCacheWait: 2242 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  youtube.com: 8
  doubleclick.net: 2
  google.com: 1
 extended:
  ##body > ytd-app > #content.ytd-app.style-scope > ytd-page-manag…
  ###offer-module
  ###ticker.ytd-masthead
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytd-metadata-row-container-renderer:has(> div.style-scope > y…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
```
</details>

**Comment by begem** [comment]
as i remember on debian i was can add it to custom filter

**Comment by gorhill** [comment]
I am unable to understand what exactly you are talking about.

**Comment by gwarser** [comment]
Probably user activity tracking. Try this add-on  https://addons.mozilla.org/pl/firefox/addon/video-background-play-fix/
