### ISSUE TITLE
fedex.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#23208]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.fedex.com/fedextrack/?trknbr=272127779750&trkqual=12027~272127779750~FDEG`

### Category

ads

### Description

Ad for shoprunner at the top of the page not sure if this counts. Needs valid tracking number for it to show and only shows on tracking screen. Use 272127779750 as tracking number. 

### Other extensions used

FastFoward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1280" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/4841137e-9771-4988-a39f-e6ee97b6a382">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 173618
 cosmetic: 228527
 scriptlet: 50938
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 77923-4442, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98094-70036, now
  adguard-generic: 80486-5495, now
  adguard-mobile: 9234-100, now
  adguard-spyware-url: 1492-106, now
  block-lan: 61-0, now
  curben-phishing: 14193-3, now
  fanboy-cookiemonster: 50809-206, now
  ublock-annoyances: 6928-9, now
 default:
  user-filters: 1-0, never
  easylist: 84386-697, now
  easyprivacy: 50445-838, now
  plowe-0: 3758-0, now
  ublock-badware: 8347-15, now
  ublock-filters: 37384-302, now
  ublock-privacy: 785-0, now
  ublock-quick-fixes: 224-0, now
  ublock-unbreak: 2240-22, now
  urlhaus-1: 8690-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1302 ms (selfie)
 maxAssetCacheWait: 220 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  fedex.com: 2
  eum-appdynamics.com: 1
  techlab-cdn.com: 4
 extended:
  ###social_facebook
  ###social_instagram
  ###social_pinterest
  ###social_twitter
  ##trk-shared-smart-app-banner
```
</details>

**Comment by mapx-** [comment]
add

`fedex.com###shop-runner-banner-link`

@ryanbr
