### ISSUE TITLE
moneycontrol.com: ads

### ISSUE THREAD

**Issue by anuraag488** [uBlockOrigin/uAssets#23206]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.moneycontrol.com/mutualfundindia/`

### Category

nuisance

### Description

A pop up appears after some seconds of loading page due to script
stat2.moneycontrol.com/mcjs/common/credit_bureau_promo_popup.js

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/7353086/279c9e13-2969-4e60-869b-e4dd3c890d3d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 128108
 cosmetic: 45800
 scriptlet: 18997
 html: 1734
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37505-104, 1m
  ublock-badware: 8349-15, 1m
  ublock-privacy: 782-1, 1m
  ublock-unbreak: 2297-2, 1m
  ublock-quick-fixes: 212-10, 1m
  easylist: 84386-261, 1m
  easyprivacy: 50445-60, 1m
  urlhaus-1: 8690-0, 1m
  plowe-0: 3758-1182, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1393 ms
 maxAssetCacheWait: 12 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  moneycontrol.com: 5
  andbeyond.media: 1
  chartbeat.com: 2
  d2r1yp2w7bby2u.cloudfront.net: 2
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  linkedin.com: 2
  onthe.io: 2
  scorecardresearch.com: 1
  taboola.com: 1
 extended:
  ##.banner_300x250
  ##.advertisement_box
  ##.banner728x90
  ##.banner_300x600
  ##a[href^="https://pubads.g.doubleclick.net/"]
  ##+js(abort-current-script, document.cookie, adKey)
```
</details>

**Comment by mapx-** [comment]
self promotion
