### ISSUE TITLE
origami-resource-center.com: breakage

### ISSUE THREAD

**Issue by moonbard** [uBlockOrigin/uAssets#23204]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://origami-resource-center.com/chestnut-holder-cuple/`

### Category

breakage

### Description

Images of content disappear when uBlock is on, and reappear when switched off. I switched off other possible extensions and reproduced the issue running only uBlock for content/ad blocking

### Other extensions used

Privacy Badger, EditThisCookie, Bitwarden, Plasma Integration, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240406_172938](https://github.com/uBlockOrigin/uAssets/assets/18256977/7bace62c-d8fb-4751-98d7-a1018001f57d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128353
 cosmetic: 45822
 scriptlet: 20373
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 11-1, never
  easylist: 84365-545, 33m Δ
  easyprivacy: 50444-813, 33m Δ
  plowe-0: 3758-0, now
  ublock-badware: 8341-15, 33m Δ
  ublock-filters: 37375-375, 33m Δ
  ublock-privacy: 785-0, 33m Δ
  ublock-quick-fixes: 218-0, 33m Δ
  ublock-unbreak: 2240-19, 33m Δ
  urlhaus-1: 8930-0, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 24357 ms (selfie)
 maxAssetCacheWait: 3041 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  doubleclick.net: 1
  ezodn.com: 12
  ezoic.net: 9
  googletagmanager.com: 2
  quantserve.com: 1
 extended:
  ##div[id^="ezoic-pub-ad-"]
  ##span[data-ez-ph-id]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##.ezoic-adpicker-ad
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
```
</details>

**Comment by JobcenterTycoon** [comment]
`@@||ezodn.com/tardisrocinante/lazy_load.js?$script,domain=origami-resource-center.com`
