### ISSUE TITLE
indianmotorcycle.in: breakage

### ISSUE THREAD

**Issue by Jansh81** [uBlockOrigin/uAssets#23207]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.indianmotorcycle.in/`

### Category

breakage

### Description

Upon enabling ublock the website freezes and you can't do anything not even scroll. For a fraction of time you can see the cookie popup, then it dissapears and the site freezes. Disabling the annoyance filters did fix the problem btw. With the annoyance filters enabled the site doesn't work.

### Other extensions used

Privacy badger. But its not beacuse of other extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox Mobile: 124
filterset (summary):
 network: 241007
 cosmetic: 214149
 scriptlet: 50057
 html: 1991
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 80453-3922, now
  adguard-spyware-url: 1492-107, now
  block-lan: 61-0, now
  curben-phishing: 14193-2, now
  fanboy-cookiemonster: 50809-187, 1m
  ublock-annoyances: 6934-112, 1m Δ
  adguard-spyware: 102336-33150, now
  adguard-cookies: 29175-3725, 1m
  adguard-popup-overlays: 27042-352, 1m
  adguard-mobile-app-banners: 5128-28, 1m
  adguard-other-annoyances: 14121-367, 1m
  [7 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37860-105, 3m Δ
  ublock-badware: 8343-15, 3m Δ
  ublock-privacy: 782-1, 22m Δ
  ublock-unbreak: 2302-2, 22m Δ
  ublock-quick-fixes: 220-10, 3m Δ
  adguard-mobile: 9234-92, now
  easylist: 84386-1715, 3m Δ
  easyprivacy: 50445-162, 3m Δ
  urlhaus-1: 8690-0, now
  plowe-0: 3758-1266, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 767 ms (selfie)
 maxAssetCacheWait: 467 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##div.cc-revoke
  ##.cc-window[aria-label="cookieconsent"]
```
</details>

**Comment by mapx-** [comment]
add

`indianmotorcycle.in#@#.cc-window[aria-label="cookieconsent"]`

@Alex-302
