### ISSUE TITLE
copilot.microsoft.com: ads

### ISSUE THREAD

**Issue by Yannick138** [uBlockOrigin/uAssets#23200]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://copilot.microsoft.com/`

### Category

ads

### Description

Above where the sources are cited, in the answer - there is a box with an advertisement in it.

### Other extensions used

AHA Music - Song Finder for Browser
Bitwarden - Free Password Manager
Dark Reader (not enabled)
Discogs Enhancer
FastForward
Return YouTube Dislike
SponsorBlock for YouTube - Skip Sponsorships
UI Changer for Reddit
WikiTree Sourcer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-07 020113](https://github.com/uBlockOrigin/uAssets/assets/166234042/adf26088-f5f1-4fcd-b8ea-d0beeea8ff57)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 128330
 cosmetic: 45819
 scriptlet: 20375
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 84346-643, now
  easyprivacy: 50444-813, now
  plowe-0: 3758-0, now
  ublock-badware: 8341-15, now
  ublock-filters: 37381-277, now
  ublock-privacy: 785-0, now
  ublock-quick-fixes: 216-0, now
  ublock-unbreak: 2240-19, now
  urlhaus-1: 8930-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3963 ms (selfie)
 maxAssetCacheWait: 139 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  bing.com: 1
 extended:
  ##.b_adLastChild
```
</details>

**Comment by ghost** [comment]
Cookie notice.

<img width="1139" height="737" alt="Image" src="https://github.com/user-attachments/assets/986ed7d9-c29c-45ba-b883-068aa7a328e3" />

<details>

```yaml
name: uBlock Origin Lite
version: 2025.812.1339
browser: Edge 139 (win)
filtering:
 site: optimal
 default: optimal
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 annoyances-cookies
 rou-1
```

</details>

**Comment by stephenhawk8054** [comment]
```adb
copilot.microsoft.com###cookie-banner
```

@ryanbr
