### ISSUE TITLE
(blockadblock) freemcserver.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2320]
### URL(s) where the issue occurs

`https://freemcserver.net/`

### Describe the issue

BAB

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.6

### Settings

default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by theinstantmatrix** [comment]
anti-adblock is back again, now automatically redirects you to `https://freemcserver.net/site/adblock` on homepage visit.

**Comment by IEnjoyDrinkingGoodWater** [comment]
anti adb
