### ISSUE TITLE
casper.com: breakage

### ISSUE THREAD

**Issue by Davidgithub1** [uBlockOrigin/uAssets#23203]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://casper.com/friends-mattress`

### Category

breakage

### Description

Must disable ubo to see the "refer a friend" section

### Other extensions used

NA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 198975
 cosmetic: 46072
 scriptlet: 21103
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 102336-146, now
  adguard-spyware-url: 1492-5, now
  block-lan: 61-0, now
 default:
  user-filters: 7-0, never
  easylist: 84365-63, now
  easyprivacy: 50447-31728, now
  plowe-0: 3758-1255, now
  ublock-badware: 8347-140, now
  ublock-filters: 37381-412, now
  ublock-privacy: 785-218, now
  ublock-quick-fixes: 218-12, now
  ublock-unbreak: 2240-84, now
  urlhaus-1: 8930-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 4 redacted]
urlRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 510 ms
 maxAssetCacheWait: 212 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 11
 network:
  casper.com: 4
  affirm.com: 1
  cloudflareinsights.com: 1
  cquotient.com: 1
  dynamicyield.com: 1
  ethyca.com: 1
  pinimg.com: 1
  snapchat.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||analytics.casper.com/gtm.js$script,1p
@@||analytics.casper.com/gtag/js$script,1p
||fbot.me/events/$badfilter
||fbot.me/track/$xhr
```

@ryanbr
