### ISSUE TITLE
download.megaup.net: detection

### ISSUE THREAD

**Issue by 404unknownCoder** [uBlockOrigin/uAssets#23211]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUbemDjqOe/tWbPV4nQnHQuMunB1WpMo/tnOUL1tiqYEEPVEcPa27zLlmTiVe5qW2DeIgPGORDOikivttjVAzAoAYA=&idfilename=otomi-games.com_GGMCQFAJ.rar&idfilesize=444.00%20MB`

### Category

detection

### Description

After the 5 seconds timer the site detects that you have an adblocker

### Other extensions used

sponsorblock, dark reader, trackmenot, fontanello, unhook

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://cdn.discordapp.com/attachments/1121777434539348018/1226537685208928276/sAwihZd.png?ex=6625213c&is=6612ac3c&hm=8425498667d8ab5c4040ed97219b01f6095737d151b5276c20aae89ee0c0644f&

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 125
filterset (summary):
 network: 127980
 cosmetic: 45815
 scriptlet: 19000
 html: 1733
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37507-104, 1h.55m Δ
  ublock-badware: 8349-15, 1h.55m Δ
  ublock-privacy: 782-1, 1h.55m Δ
  ublock-unbreak: 2297-2, 1h.55m Δ
  ublock-quick-fixes: 220-10, 1h.55m Δ
  easylist: 84380-262, 1h.55m Δ
  easyprivacy: 50455-60, 1h.55m Δ
  urlhaus-1: 8565-0, now
  plowe-0: 3758-1182, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 100 ms (selfie)
 maxAssetCacheWait: 39 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/20505 fixed https://github.com/uBlockOrigin/uAssets/commit/bcecc13107023d733a547977e8ad7cdb66e45b70
