### ISSUE TITLE
you.com: breakage

### ISSUE THREAD

**Issue by MeanGreenOG** [uBlockOrigin/uAssets#23216]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://you.com/search?q=how+do+I+resolve+the+errror%3F&fromSearchBar=true&tbm=youchat&chatMode=agent&cid=c0_e5b49f14-03c2-449c-ae30-5b8f724d9834`

### Category

breakage

### Description

I think that it has an issue with plausible.io, but not certain. The search functions keep breaking as well as having issues remaining logged into the website.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 335039
 cosmetic: 311861
 scriptlet: 55129
 html: 2087
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 80518-4187, now
  adguard-mobile: 9238-92, now
  adguard-spyware-url: 1492-107, now
  adguard-spyware: 102337-1394, now
  block-lan: 61-0, now
  curben-phishing: 14091-2, now
  adguard-social: 22754-1214, now
  adguard-cookies: 29188-1632, now
  ublock-cookies-adguard: 1072-12, now
  adguard-popup-overlays: 27042-1039, now
  adguard-mobile-app-banners: 5128-31, now
  adguard-other-annoyances: 14131-419, now
  [47 lists not shown]: [too many]
 default:
  ublock-filters: 37551-300, 1h.52m Δ
  ublock-badware: 8336-15, 1h.52m Δ
  ublock-privacy: 782-2, 1h.52m Δ
  ublock-unbreak: 2297-3, now
  ublock-quick-fixes: 220-10, 1h.52m Δ
  easylist: 84396-17276, 1h.52m Δ
  easyprivacy: 50457-31859, 1h.52m Δ
  urlhaus-1: 8905-0, now
  plowe-0: 3758-1669, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 538 ms (selfie)
 maxAssetCacheWait: 362 ms
 cacheBackend: indexedDB
 unsuspendAfter: 143 ms
popupPanel:
 blocked: 45
 network:
  you.com: 39
  appsflyer.com: 1
  braze.com: 2
  clarity.ms: 1
  msadsscale.azureedge.net: 1
  plausible.io: 1
 extended:
  ##+js(json-prune, data.ads)
  ##+js(set-local-storage-item, hasSeenAddToChromeNudge, 1)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||plausible.io^$xhr,3p,redirect-rule=nooptext,domain=you.com
```

**Comment by MeanGreenOG** [comment]
Yes it works, thank you very much! You're a hero and a scholar!
