### ISSUE TITLE
bedstyle.jp: nuisance

### ISSUE THREAD

**Issue by fredy-aq** [uBlockOrigin/uAssets#23218]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bedstyle.jp/media/make/86933`

### Category

nuisance

### Description

Scroll down the page to a certain position and an overlay will appear.

### Other extensions used

None

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/166389323/c082fe54-5b9a-4b55-abfe-7c7b307de259

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 172672
 cosmetic: 230663
 scriptlet: 49347
 html: 1990
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 3m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 438-1, 3m
  https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/blog-parts.txt: 435-0, 3m
  https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/mob-app.txt: 1027-0, 3m
  https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/sabre-filters2.txt: 2010-751, never
  https://raw.githubusercontent.com/Yuki2718/adblock2/main/japanese/jpf-plus.txt: 887-6, 3m
  adguard-generic: 80606-3928, now
  curben-phishing: 14091-1, 1h.22m
  adguard-social: 22755-50, 2m
  fanboy-cookiemonster: 50827-188, now
  ublock-annoyances: 6873-144, 2m
  adguard-cookies: 29193-3720, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 37554-108, 3h.13m Δ
  ublock-badware: 8359-16, 3h.13m Δ
  ublock-privacy: 782-1, 3h.13m Δ
  ublock-unbreak: 2297-2, 3h.13m Δ
  ublock-quick-fixes: 219-10, 3h.13m Δ
  easylist: 84396-1674, now
  easyprivacy: 50457-155, now
  urlhaus-1: 8905-0, 1h.22m
  plowe-0: 3758-1192, 1h.22m
  JPN-1: 14215-98, 1h.22m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6662 ms (selfie)
 maxAssetCacheWait: 1590 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  asia-northeast1-code-mc-cdp.cloudfunctions.net: 9
  clarity.ms: 1
  codemarketing.cloud: 12
  ec-optimizer.com: 2
  googletagmanager.com: 2
  kaiu-marketing.com: 2
  promolayer.io: 1
 extended:
  ##.share-top
  ##a[href*="http://twitter.com/share"]
  ##a[href^="//www.facebook.com/sharer/sharer.php?"]
  ##a[href*="pinterest.com/pin/create/button"]
```
</details>

**Comment by mapx-** [comment]
add

`bedstyle.jp##.code-mc-container`

**Comment by fredy-aq** [comment]
Thank you for resolving the issue.
