### ISSUE TITLE
service.webgoto.net: detection

### ISSUE THREAD

**Issue by r4oz8** [uBlockOrigin/uAssets#23212]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://service.webgoto.net/chattering/
```

### Description

When I access the site, I get a message saying "Error caused by ad blocker.".

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 129934
 cosmetic: 57848
 scriptlet: 20557
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37384-285, 2m Δ
  ublock-badware: 8329-15, 24m
  ublock-privacy: 785-0, 2m Δ
  ublock-unbreak: 2240-0, 24m
  ublock-quick-fixes: 224-0, 24m
  easylist: 84386-663, 2m Δ
  easyprivacy: 50445-22, 2m Δ
  urlhaus-1: 8565-0, 24m
  plowe-0: 3758-809, 24m
  JPN-1: 14215-49, 24m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 213 ms (selfie)
 maxAssetCacheWait: 23 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
add

`service.webgoto.net##+js(no-xhr-if, amazon)`

@Yuki2718
