### ISSUE TITLE
uw.co.uk: breakage

### ISSUE THREAD

**Issue by Gregorsky** [uBlockOrigin/uAssets#23221]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uw.co.uk/`

### Category

breakage

### Description

Site completely broken and not loading.

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

WHITE PAGE - no point of screenshot

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 152270
 cosmetic: 168066
 scriptlet: 32190
 html: 2000
listset (total-discarded, last-updated):
 added:
  curben-phishing: 14253-1, now
  adguard-cookies: 29194-40, now
  ublock-cookies-adguard: 1071-12, 6m
  adguard-popup-overlays: 27046-225, now
  adguard-mobile-app-banners: 5128-19, now
  adguard-other-annoyances: 14133-295, now
  fanboy-thirdparty_social: 68-0, now
  easylist-chat: 189-0, now
  fanboy-cookiemonster: 50840-3883, now
  ublock-cookies-easylist: 1072-1071, 7m
  easylist-newsletters: 7128-500, 7m
  ublock-annoyances: 6873-1273, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 43-0, never
  ublock-filters: 37549-104, now
  ublock-badware: 8364-15, now
  ublock-privacy: 782-1, now
  ublock-unbreak: 2297-2, now
  ublock-quick-fixes: 219-10, 7m
  easylist: 84420-262, now
  easyprivacy: 50457-60, now
  urlhaus-1: 8835-0, now
  plowe-0: 3758-1184, now
filterset (user): [array of 43 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 391 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  onetrust.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 Adguard cookie issue.
