### ISSUE TITLE
webtru breakage

### ISSUE THREAD

**Issue by datasigngoto** [uBlockOrigin/uAssets#23228]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://static.jp.mercari.com/cookie_policy
```

### Description

私はCMPツール(webtru)を担当しています。
uBlockにより、CMPが表示されないページがあります。
webtruを除外対象にしてほしいです。

**I am in charge of the CMP tool (webtru). Due to uBlock, there are pages where CMP is not displayed. I would like webtru to be excluded.**

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image (1)](https://github.com/uBlockOrigin/uAssets/assets/166490105/dc24cd2e-9227-4c12-a2d9-d50f6ac245a9)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by datasigngoto** [comment]
I am in charge of the CMP tool (webtru). Some pages do not display CMP due to uBlock. I would like webtru to be excluded.

**Comment by datasigngoto** [comment]
I apologize for my lack of understanding.
What do you mean by cookie list issue?
I want my ad blocker (uBlock) to exclude webtru.

**Comment by stephenhawk8054** [comment]
It's because of `||cmp.datasign.co^` in EP. Looks like it's a domain for cookie policies.

With the filter

<details>

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/8d92128b-ec42-4d8d-980d-174413e3b323)

</details>

Without the filter

<details>

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/bc4bd07f-70cc-472b-83be-84bfd338f24b)

</details>

@Yuki2718 Sorry, can you check the site again?

**Comment by Yuki2718** [comment]
Yes, this is for consent widgets. I'll move to cookie lists.
