### ISSUE TITLE
lastampa.it: video player breakage

### ISSUE THREAD

**Issue by MolinengoLuigi** [uBlockOrigin/uAssets#23220]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lastampa.it/torino/2024/04/07/video/torino_furgone_contromano-14203130/?ref=LSHSP-P3-S1`

### Category

breakage

### Description

Every video player doesn't work on the site if uBlock is enabled: missing play/command button

### Other extensions used

Bitwarden (do not interact)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 123
filterset (summary):
 network: 129993
 cosmetic: 52543
 scriptlet: 20389
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ITA-0: 8389-18, 1h.4m
  easylist: 84396-27, 1h.4m Δ
  easyprivacy: 50457-12, 1h.4m Δ
  plowe-0: 3758-1183, now
  ublock-badware: 8357-140, 1h.4m Δ
  ublock-filters: 37434-375, 1h.4m Δ
  ublock-privacy: 785-5, 1h.4m Δ
  ublock-quick-fixes: 223-12, 1h.4m Δ
  ublock-unbreak: 2240-32, 1h.4m Δ
  urlhaus-1: 8835-0, 1h.4m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 26 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 319 ms (selfie)
 maxAssetCacheWait: 191 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 3
 network:
  lastampa.it: 1
  gedidigital.it: 2
 extended:
  ###adv-Top
  ###adv-TopLeft
  ###adv-Middle1-hr
```
</details>

**Comment by mapx-** [comment]
it was due to the other issue opend by you:
https://github.com/uBlockOrigin/uAssets/issues/23087

for that one:
`https://www.lastampa.it/cuneo`

we wont fix it (again) because fixing it would permit tracking.
for your personal use add:

```
@@||widgets.outbrain.com^$script,domain=lastampa.it
@@||outbrain.com/Multivac/api/$script,domain=lastampa.it
@@||traffic.outbrain.com/network/redir
```

**Comment by MolinengoLuigi** [comment]
I've active this custom filter:

(this one, from the previous suggestion for an other problem)
`||tlh.gedidigital.it/tlh.js$script,domain=lastampa.it`

And these:
```
@@||widgets.outbrain.com^$script,domain=lastampa.it
@@||outbrain.com/Multivac/api/$script,domain=lastampa.it
@@||traffic.outbrain.com/network/redir
```

But video player is still not working

**Comment by mapx-** [comment]
Remove the first one

**Comment by MolinengoLuigi** [comment]
Actually, the three new lines proposed do not produce the same effect as the first line. I don't know why, but with these last ones, the displayed article is changing.

Is it possible to keep this line of code
`||tlh.gedidigital.it/tlh.js$script,domain=lastampa.it 
`but also have some exclusions for videos?

(Sorry for my ignorance, I know little about uBlock filters.)
