### ISSUE TITLE
roystream.com: [unknown]

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#23225]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://roystream.com/e/baseball/mlb/401568622`

### Category

[unknown]

### Description

popup to fubo when clicking the video

### Other extensions used

decentraleyes
privacybadger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 255308
 cosmetic: 249338
 scriptlet: 50060
 html: 1990
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80637-3926, now
  adguard-mobile: 9236-60, now
  adguard-spyware-url: 1492-107, now
  adguard-spyware: 104183-1374, now
  block-lan: 61-0, now
  curben-phishing: 14119-2, 1m
  adguard-social: 22758-53, now
  adguard-cookies: 29200-47, now
  ublock-cookies-adguard: 1072-12, now
  adguard-popup-overlays: 27046-998, now
  adguard-mobile-app-banners: 5128-22, now
  adguard-other-annoyances: 14133-413, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37502-104, now
  ublock-badware: 8320-15, now
  ublock-privacy: 782-1, now
  ublock-unbreak: 2297-2, now
  ublock-quick-fixes: 219-10, 1m
  easylist: 84445-1734, now
  easyprivacy: 50464-31840, now
  urlhaus-1: 8940-0, 1m
  plowe-0: 3758-1669, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 604 ms (selfie)
 maxAssetCacheWait: 256 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  chatango.com: 1
  googletagmanager.com: 1
  kkqcnrk.com: 1
  ndzoaaa.com: 2
  nxszxho.com: 2
  voodc.com: 2
  youradexchange.com: 2
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##+js(abort-current-script, document.documentElement, break;case…
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 I see the script `http://nxszxho.com/script/thankYou.js` being slipped, does changing this

```adb
/^https?:\/\/[a-z]{5,7}\.com\/script\/[-_0-9a-z]+(\.min)?\.js$/$script,3p,match-case,from=~edu|~gov
```

to

```adb
/^https?:\/\/[a-z]{5,7}\.com\/script\/\w+(\.min)?\.js$/$script,3p,match-case,from=~edu|~gov,header=X-GUploader-UploadID
```

work on your side?

**Comment by peroleucopus** [comment]
Refreshed filter list and it's still being redirected. Do I need to reopen since this was closed?

**Comment by stephenhawk8054** [comment]
@peroleucopus Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by peroleucopus** [comment]
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 255331
 cosmetic: 249405
 scriptlet: 50081
 html: 1989
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80672-3921, now
  adguard-mobile: 9237-60, now
  adguard-spyware-url: 1492-107, now
  adguard-spyware: 104202-1375, now
  block-lan: 61-0, 6d.21h.1m
  curben-phishing: 14130-2, now
  adguard-social: 22772-53, now
  adguard-cookies: 29221-47, now
  ublock-cookies-adguard: 1071-12, 3d.21h.3m
  adguard-popup-overlays: 27062-994, now
  adguard-mobile-app-banners: 5136-22, now
  adguard-other-annoyances: 14140-412, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37551-104, 2d.20h.15m Δ
  ublock-badware: 8336-15, 2d.20h.15m Δ
  ublock-privacy: 782-1, 2d.20h.15m Δ
  ublock-unbreak: 2298-2, now Δ
  ublock-quick-fixes: 129-10, now
  easylist: 84396-1727, 2d.20h.15m Δ
  easyprivacy: 50457-31839, 2d.20h.15m Δ
  urlhaus-1: 8955-0, now
  plowe-0: 3758-1340, 4d.21h.20m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 365 ms (selfie)
 maxAssetCacheWait: 144 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  chatango.com: 1
  googletagmanager.com: 1
  uhrmzgp.com: 5
  voodc.com: 2
  youradexchange.com: 3
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##+js(abort-current-script, document.documentElement, break;case…
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…

**Comment by stephenhawk8054** [comment]
Can you update uBO to latest version `1.57.2`, update the filter lists and test again?

**Comment by peroleucopus** [comment]
Issue still persists if not worse. Getting popups now too.

uBlock Origin: 1.57.2
Firefox Mobile: 126
filterset (summary):
 network: 255809
 cosmetic: 249819
 scriptlet: 50091
 html: 2009
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80649-3933, 2d.5h.6m
  adguard-spyware-url: 1492-107, 2d.5h.5m
  adguard-spyware: 104184-1376, 2d.5h.5m
  block-lan: 61-0, 3d.13h.50m
  curben-phishing: 14161-2, 1h.32m
  adguard-social: 22761-53, 2d.5h.6m
  adguard-cookies: 29212-47, 2d.5h.5m
  adguard-popup-overlays: 27050-998, 2d.5h.6m
  adguard-mobile-app-banners: 5133-26, 2d.5h.6m
  adguard-other-annoyances: 14137-409, 2d.5h.6m
  adguard-widgets: 2458-12, 2d.5h.6m
  fanboy-thirdparty_social: 68-3, 5d.4h.11m
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37943-109, 1h.32m Δ
  ublock-badware: 8394-15, 1h.32m Δ
  ublock-privacy: 782-2, 1h.32m Δ
  ublock-unbreak: 2305-2, 1h.32m Δ
  ublock-quick-fixes: 136-34, 1h.32m Δ
  adguard-mobile: 9237-92, 1d.3h.58m
  easylist: 84917-1758, 1h.32m Δ
  easyprivacy: 50471-31842, 1h.32m Δ
  urlhaus-1: 8975-10, 1h.32m
  plowe-0: 3758-1668, 4d.1h.29m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 604 ms (selfie)
 maxAssetCacheWait: 270 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  achcdn.com: 2
  castanydm.com: 1
  chatango.com: 1
  googletagmanager.com: 2
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##+js(json-prune, *, *.adserverDomain)
  ##+js(abort-current-script, document.documentElement, break;case…
