### ISSUE TITLE
online-fix.me: ads

### ISSUE THREAD

**Issue by FSI001** [uBlockOrigin/uAssets#23229]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://online-fix.me/games/officialservers/17478-microsoft-flight-simulator-po-seti.html`

### Category

ads

### Description

Showing ads

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128428
 cosmetic: 45892
 scriptlet: 20436
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 84454-546, 1h.19m Δ
  easyprivacy: 50461-831, 1h.19m Δ
  plowe-0: 3758-0, now
  ublock-badware: 8328-15, 1h.19m Δ
  ublock-filters: 37486-391, 1h.19m Δ
  ublock-privacy: 785-0, 1h.19m Δ
  ublock-quick-fixes: 235-0, 1h.19m Δ
  ublock-unbreak: 2240-0, 1h.19m Δ
  urlhaus-1: 8940-0, 19m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1352 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  youtube-nocookie.com: 2
 extended:
  ##+js(no-setTimeout-if, /width|innerHTML/)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune-fetch-response, overlay, overlay.shortsAdsRende…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
```
</details>

**Comment by dimisa-RUAdList** [comment]
See also: https://github.com/uBlockOrigin/uAssets/issues/22092

**Comment by stephenhawk8054** [comment]
Follow the link above
