### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by sahbi1onur** [uBlockOrigin/uAssets#23231]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/playlist/21MBBlsMqdqJZUIHVbPXy0`

### Category

ads

### Description

sahbi

### Other extensions used

ja

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 130757
 cosmetic: 50889
 scriptlet: 20404
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  DEU-0: 7366-0, 5m
  easylist: 84455-28, 4m
  easyprivacy: 50457-21, 5m
  plowe-0: 3758-1183, 5m
  ublock-badware: 8328-141, 5m
  ublock-filters: 37434-381, 5m
  ublock-privacy: 785-5, 5m
  ublock-quick-fixes: 241-12, 5m
  ublock-unbreak: 2240-34, 5m
  urlhaus-1: 8950-5, 5m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2596 ms
 maxAssetCacheWait: 48 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 9
 network:
  googleoptimize.com: 2
  googletagmanager.com: 1
  scdn.co: 4
  spotifycdn.com: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/22198
