### ISSUE TITLE
svt.se: breakage

### ISSUE THREAD

**Issue by LinAGKar** [uBlockOrigin/uAssets#23234]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.svt.se/
```

### Description

On the above page, there is a cookie pop-up. Normally, you can dismiss it and it stays gone on reload, but if "uBlock filters – Annoyances" is enabled, it shows up every single time the page is loaded.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-09 at 14-44-25 SVT Nyheter](https://github.com/uBlockOrigin/uAssets/assets/3390621/e50bc603-6b86-4235-bf42-b0e1b6f8edd6)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 130324
 cosmetic: 50217
 scriptlet: 23755
 html: 2007
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6873-32, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37536-103, 4m
  ublock-badware: 8330-15, 4m
  ublock-privacy: 782-2, 4m
  ublock-unbreak: 2297-2, 4m
  ublock-quick-fixes: 237-136, 4m
  easylist: 84454-265, 4m
  easyprivacy: 50457-60, 4m
  urlhaus-1: 8950-5, 4m
  plowe-0: 3758-1182, 4m
  SWE-1: 4603-22, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1580 ms
 maxAssetCacheWait: 21 ms
 cacheBackend: indexedDB

```
</details>

**Comment by dportvine** [comment]
I can reproduce.

<details>
<summary>Screen</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/c1373177-ed70-44ee-907d-71da1202a4cc
</details>

**Comment by stephenhawk8054** [comment]
@dportvine Can you check if these filters work?

```adb
svt.se#@#+js(trusted-set-cookie, cookie-consent-1, '{"optedIn":true,"functionality":false,"statistics":false}')
svt.se##+js(trusted-set-cookie, cookie-consent-1, '{"optedIn":true,"functionality":true,"statistics":false}')
```

**Comment by stephenhawk8054** [comment]
Looks like due to this: https://github.com/uBlockOrigin/uBlock-issues/issues/3178

May need to wait for next version.

---

@gorhill Sorry, does version `1.57.2` include the fix of `trusted-set-cookie`

**Comment by stephenhawk8054** [comment]
In the meantime, I moved the filter to dev build

**Comment by mapx-** [comment]
@LinAGKar install uBO dev build 
https://github.com/gorhill/uBlock/releases/download/1.57.3b2/uBlock0_1.57.3b2.firefox.signed.xpi
