### ISSUE TITLE
epson.com.cn: breakage

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#23233]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.epson.com.cn/Apps/tech_support/GuideDrive.aspx`

### Category

breakage

### Description

The search bar is unavailable (again, #16742).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 126
filterset (summary):
 network: 257646
 cosmetic: 248494
 scriptlet: 50052
 html: 1989
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 80622-3930, now
  adguard-spyware-url: 1492-107, now
  adguard-spyware: 104184-1360, now
  curben-phishing: 14119-2, 10m
  adguard-cookies: 29209-46, now
  ublock-cookies-adguard: 1072-12, now
  fanboy-cookiemonster: 50844-3858, now
  ublock-cookies-easylist: 1072-1072, now
  adguard-social: 22761-55, now
  fanboy-social: 15825-709, now
  fanboy-thirdparty_social: 68-18, never
  adguard-popup-overlays: 27045-1040, 1m
  [7 lists not shown]: [too many]
 default:
  ublock-filters: 37536-103, 10m Δ
  ublock-badware: 8333-15, 10m Δ
  ublock-privacy: 782-2, 10m Δ
  ublock-unbreak: 2297-2, 10m Δ
  ublock-quick-fixes: 237-136, 10m Δ
  easylist: 84455-1676, 10m Δ
  easyprivacy: 50461-31833, 10m Δ
  urlhaus-1: 8950-5, 10m
  plowe-0: 3758-1266, 9m
  CHN-0: 25625-212, 1m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1818 ms (selfie)
 maxAssetCacheWait: 1142 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  epson.com.cn: 2
  googletagmanager.com: 2
 extended:
  ##+js(set-constant, _gsq, {})
  ##+js(set-constant, _gsq.push, noopFunc)
```
</details>

**Comment by gorhill** [comment]
I am unable to reproduce with default filter lists.

You have lot of extra lists enabled, please narrow down ti which list is causing your issue.

**Comment by Linisdjxm** [comment]
> I am unable to reproduce with default filter lists.
> 
> You have lot of extra lists enabled, please narrow down to which list is causing your issue.

I have removed most of the lists:
<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 126
filterset (summary):
 network: 16780
 cosmetic: 12610
 scriptlet: 4957
 html: 310
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 added:
  ublock-annoyances: 6872-11, 9m Δ
 default:
  ublock-unbreak: 2298-0, 9m Δ
  CHN-0: 25625-126, 23h.59m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1779 ms (selfie)
 maxAssetCacheWait: 893 ms
 cacheBackend: indexedDB
```
</details>
However, it just doesn't work.

**Comment by gorhill** [comment]
No need to remove default lists since I cannot reproduce with default lists. I assumed one of the extra lists you explicitly enabled was causing the issue, however if you still suffer the issue after removing all those extra lists, the issue might be elsewhere.

Have you tried to find out if the issue still exist when you wholly disable uBO in `about:addons`.

**Comment by D4niloMR** [comment]
The issue is caused by `||epson.com.cn/common/new/js/tracking_code.js$1p,important` in uBlock filters – Unbreak.

**Comment by Linisdjxm** [comment]
It's working.
