### ISSUE TITLE
rmcbfmplay.com: detection

### ISSUE THREAD

**Issue by whitesnakeftw** [uBlockOrigin/uAssets#23232]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.rmcbfmplay.com/video/rmc-decouverte/jirai-dormir-chez-vous/s14e1-algerie?contentId=Product::NEUF_RMCDEC_RMC00216587&universe=PROVIDER
```

### Description

Happening again. Enabled the AdGuard Français list but didn't make a difference. Tried on both Chrome and Firefox.

Free account needed.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 147093
 cosmetic: 59094
 scriptlet: 20464
 html: 0
listset (total-discarded, last-updated):
 added:
  FRA-0: 24245-324, 12m
  ITA-0: 8389-19, now
 default:
  user-filters: 0-0, never
  easylist: 84455-649, 26m Δ
  easyprivacy: 50461-831, 26m Δ
  plowe-0: 3758-0, now
  ublock-badware: 8331-20, 26m Δ
  ublock-filters: 37438-585, 26m Δ
  ublock-privacy: 785-0, 26m Δ
  ublock-quick-fixes: 241-0, 26m Δ
  ublock-unbreak: 2240-0, 26m Δ
  urlhaus-1: 8950-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1238 ms (selfie)
 maxAssetCacheWait: 232 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  fwmrm.net: 1
  xiti.com: 1
 extended:
  ##+js(prevent-fetch, /www3\.doubleclick\.net|tagger\.opecloud\.c…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…

```
</details>

**Comment by JobcenterTycoon** [comment]
No need to open a new issue every time, just write a comment in a old issue https://github.com/uBlockOrigin/uAssets/issues/23232
