### ISSUE TITLE
sbs.com.au: ads

### ISSUE THREAD

**Issue by sliceanddice9** [uBlockOrigin/uAssets#23248]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.sbs.com.au/ondemand/
```

### Description

I'm using uBlock Origin with Kiwi Browser on mobile. The https://www.sbs.com.au/ondemand/ mobile website still shows ads when streaming. The ads are at least skipable but they are still annoying.

I had a similar issue last year on https://www.sbs.com.au/ondemand/ using my Desktop PC, but the (sbs.com.au#@#+js(no-xhr-if, doubleclick) filter fixed things. I tried adding that same filter to uBlock Origin on my smartphone as well, but the filter does not work. I'm still getting skipable ads during streams. 

### Other extensions used

Violentmonkey

Urban VPN Proxy (not used on SBS mobile website) 

AdGuard (MV3 version) this add-on is disabled because it doesn't work on  the SBS mobile website. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 130589
 cosmetic: 92916
 scriptlet: 29206
 html: 0
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
 added:
  fanboy-cookiemonster: 66912-16261, 2d.11h.17m
  ublock-annoyances: 6997-1154, 2d.11h.17m Δ
  ublock-cookies-easylist: 1110-0, 1h.11m
 default:
  user-filters: 7-0, never
  easylist: 84642-169, 1h.10m Δ
  easyprivacy: 50469-20, 1h.10m Δ
  plowe-0: 3763-1182, 8d.9h.48m
  ublock-badware: 8372-15, 1h.11m Δ
  ublock-filters: 37831-415, 33m
  ublock-privacy: 780-5, 2d.11h.17m Δ
  ublock-quick-fixes: 133-0, 1h.11m Δ
  ublock-unbreak: 2246-0, 1h.11m Δ
  urlhaus-1: 8825-5, 1h.11m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1780 ms (selfie)
 maxAssetCacheWait: 180 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  adlightning.com: 1
  demdex.net: 2
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 2
  newrelic.com: 2
  sbs.com.au: 3
  tremorhub.com: 1
 extended:
  ##+js(set-constant, adBlockerDetected, undefined)
  ##+js(m3u-prune, /redirector\.googlevideo\.com\/videoplayback\?[…
  ##+js(no-xhr-if, /redirector\.googlevideo\.com\/videoplayback[\s…
  ##+js(json-prune, ads breaks cuepoints times)
  ##+js(remove-class, ad-controls, .bitmovinplayer-container.ad-co…
  ##+js(set-constant, odabd, false)

```
</details>

**Comment by mapx-** [comment]
sbs is broken on desktop, these are working on my end, test them on your side:

```
@@*$xhr,domain=sbs.com.au,1p
@@||dpm.demdex.net^$xhr,domain=sbs.com.au
```

if still does not work try using firefox mobile (kiwi is not fully supported)
