### ISSUE TITLE
washingtonpost.com: breakage

### ISSUE THREAD

**Issue by fallinghawks** [uBlockOrigin/uAssets#23256]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.washingtonpost.com/health/2024/04/10/pots-medical-condition-athletes-covid-pandemic/`

### Category

breakage

### Description

Only the first 3 paragraphs of the article are shown. Once uBlock Origin is disabled, the paragraphs appear. This also happens in incognito mode. I added some anti-paywall filters but removed them and the problem is still there. 

### Other extensions used

Privacy Badger, but the problem still happens when PB is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 130544
 cosmetic: 90939
 scriptlet: 25021
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1h.15m
  fanboy-cookiemonster: 50795-183, 49m
  fanboy-thirdparty_social: 68-0, 49m
 default:
  user-filters: 1105-1, never
  easylist: 84642-653, 1h.15m Δ
  easyprivacy: 50470-833, 1h.15m Δ
  plowe-0: 3759-0, 49m
  ublock-badware: 8345-15, 1h.15m Δ
  ublock-filters: 37475-299, 1h.15m Δ
  ublock-privacy: 785-0, 1h.15m Δ
  ublock-quick-fixes: 133-0, 1h.15m Δ
  ublock-unbreak: 2241-0, 1h.15m Δ
  urlhaus-1: 8825-5, 49m
filterset (user): [array of 873 redacted]
trustedset:
 added: [array of 50 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2181 ms (selfie)
 maxAssetCacheWait: 1092 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  washingtonpost.com: 1
  3gl.net: 1
  amazon-adsystem.com: 1
  brandmetrics.com: 1
  criteo.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  launchdarkly.com: 4
  unpkg.com: 1
  webcontentassessor.com: 1
  zeustechnology.com: 2
 extended:
  ##.grecaptcha-badge
  ##.outbrain-wrapper
  ##[data-qa="right-rail-ad"]
  ##[data-testid="placeholder-box"]
  ##[data-ad-module]:not([style$="left: -10000px !important; top: …
  ##.w-100:has-text(Advertisement)
  #@#[data-ad-module]
  ##+js(abort-current-script, Promise, overlay)
  ##+js(abort-current-script, document.createElement, overlay)
  ##+js(remove-node-text, script, /\badblock\b/)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test in a new browser profile with only uBO and its default settings?

**Comment by fallinghawks** [comment]
> Can you test in a new browser profile with only uBO and its default settings?

It looks fine there. Then I readded the anti-paywall filters and the problem recurred, even though it seemed like they were not the cause when I tested earlier. Thanks for the troubleshooting advice, I believe we can close this ticket
