### ISSUE TITLE
notebooksbilliger.de: ads

### ISSUE THREAD

**Issue by xRuffKez** [uBlockOrigin/uAssets#23254]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I am not using uBlock Origin along with other content blockers.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.notebooksbilliger.de/synology+diskstation+ds223+nas+2+bay+794187`

### Category

ads

### Description

Ad Banner on right side of page and top of product.

### Other extensions used

Adguard Home - Filters: Hagezi Pro, Hagezi TIF, OISD Big - Upstream: DNS0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Unbenannt](https://github.com/uBlockOrigin/uAssets/assets/92758042/ffaf6a58-3b56-4ae2-8d17-2ae9cd725fd5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 130740
 cosmetic: 50931
 scriptlet: 20382
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37475-313, 1m Δ
  ublock-badware: 8345-15, 1m Δ
  ublock-privacy: 785-0, 1m Δ
  ublock-unbreak: 2241-0, 1m Δ
  ublock-quick-fixes: 133-0, 1m Δ
  easylist: 84642-658, 1m Δ
  easyprivacy: 50470-22, 1m Δ
  urlhaus-1: 8825-5, now
  plowe-0: 3759-809, now
  DEU-0: 7367-12, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by xRuffKez** [comment]
`
||www.notebooksbilliger.de/cherry-assets/*.webp
`

**Comment by JobcenterTycoon** [comment]
self ads
