### ISSUE TITLE
Surfline webcams

### ISSUE THREAD

**Issue by Chernobyl1** [uBlockOrigin/uAssets#2325]
URL(s) https://www.surfline.com/surf-report/ocean-beach-overview/5842041f4e65fad6a77087f8

### Describe the issue:  surfline just revamped their website.  on the old website, Ublock Origin was money--it prevented the long loading, long lasting ads from coming on before the streaming cam (of surf conditions) came on.  Now, it doesn't work at all.  this message appears:

"
![capture](https://user-images.githubusercontent.com/38861934/40260812-975994c0-5ab1-11e8-8996-9bfa3154858e.PNG)
Please disable your ad blocker in order to view this Surfline cam"

l

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.16.6

### Notes
I'm scratching my head with this one.  I even tried turning off Ublock origin, but the same message applies.

**Comment by gwarser** [comment]
Because it's fixed. Update "uBlock filters" list and should be ok.

**Comment by okiehsch** [comment]
I fixed it with the commit https://github.com/uBlockOrigin/uAssets/commit/24a6c7a1cc102a858fab9e3dc10c56cd9da9581e.

It actually states the reason `okiehsch closed this in 24a6c7a`
