### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by HPK-MrJJ** [uBlockOrigin/uAssets#23265]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/playlist/0c714E6U6Xl8zCLAF5bjB7`

### Category

breakage

### Description

Songs that play right after skipping, or are played by clicking the play button on the playlist, are skipped as if they are ads.

### Other extensions used

A couple of tapermonkey scripts that don't do anything on Spotify (I checked)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
I clicked play on this song and it was blocked like an ad (one second long). Similar thing happens if I skip. The next song after the skip is blocked.

![image](https://github.com/uBlockOrigin/uAssets/assets/150632808/a86509a1-7b3b-465c-9163-6842945ff0bf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 128877
 cosmetic: 45935
 scriptlet: 20389
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84910-651, 1h.28m Δ
  easyprivacy: 50471-831, 1h.29m Δ
  plowe-0: 3759-0, now
  ublock-badware: 8398-25, 1h.29m Δ
  ublock-filters: 37479-297, 1h.28m Δ
  ublock-privacy: 785-0, 1h.28m Δ
  ublock-quick-fixes: 134-0, 1h.29m Δ
  ublock-unbreak: 2243-0, 1h.28m Δ
  urlhaus-1: 8975-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1281 ms (selfie)
 maxAssetCacheWait: 640 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 134
 network:
  activemetering.com: 1
  doubleclick.net: 56
  googletagmanager.com: 1
  researchnow.com: 1
  sentry.io: 29
  serving-sys.com: 1
  spotifycdn.com: 45
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by dportvine** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/22198
