### ISSUE TITLE
surfline cams

### ISSUE THREAD

**Issue by Chernobyl1** [uBlockOrigin/uAssets#2326]
www.surfline.com

example:
 https://www.surfline.com/surf-report/ocean-beach-overview/5842041f4e65fad6a77087f8

Describe the issue: Ublock is now detected by site, and the streaming cam won't run.  Istead it gives this message:

"Please disable your ad blocker in order to view this Surfline cam"

    Browser/version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
    uBlock Origin version: uBlock Origin v1.16.6

**Comment by okiehsch** [comment]
It is fixed.
