### ISSUE TITLE
roblox.com: privacy

### ISSUE THREAD

**Issue by loadstring1** [uBlockOrigin/uAssets#23267]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.roblox.com/home
```

### Description

Ublock origin fails to block all 1 pixel trackers on roblox website.

This following domain returns all 1 pixel trackers related to roblox and therefore should be blocked with ublock privacy list: 

`https://lms.roblox.com/recipe?iteration=0`

### Other extensions used

BTRoblox, duckduckgo privacy essentials (disabled at the time of testing), cliget, Hoxx VPN Proxy, Return Youtube Dislike, SponsorBlock, Tampermonkey, Vencord Web

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Zrzut ekranu 2024-04-11 191013](https://github.com/uBlockOrigin/uAssets/assets/156520308/e5627c79-e369-4a06-bd4e-39c1a429728f)
![Zrzut ekranu 2024-04-11 191205](https://github.com/uBlockOrigin/uAssets/assets/156520308/f8a3760c-1440-472a-a5e2-4321f318bec4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 130184
 cosmetic: 54140
 scriptlet: 19185
 html: 1763
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37581-108, 2h.24m Δ
  ublock-badware: 8400-15, 2h.24m Δ
  ublock-privacy: 782-2, 2h.24m Δ
  ublock-unbreak: 2300-2, 2h.24m Δ
  ublock-quick-fixes: 136-34, 2h.24m Δ
  easylist: 84910-268, 2h.24m Δ
  easyprivacy: 50471-60, 2h.24m Δ
  urlhaus-1: 8825-5, 21h.14m
  plowe-0: 3766-1189, 7d.2h.38m
  POL-0: 8740-38, 21h.14m
  POL-2: 1283-48, 21h.14m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 126 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB

```
</details>

**Comment by loadstring1** [comment]
> Do you need to sign in to see the issue?

Yes

**Comment by mapx-** [comment]
@ryanbr
