### ISSUE TITLE
hianime.to, aniwatchtv.to: ads

### ISSUE THREAD

**Issue by T1mp4n** [uBlockOrigin/uAssets#23268]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hianime.to/watch/the-aristocrats-otherworldly-adventure-serving-gods-who-go-too-far-18355?ep=101620&ep=101620`

### Category

ads

### Description

Ad popup when pausing and resuming content.

> Started around 18:00 cst +1 April 11

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/166747352/d67c4cc1-d5f1-4788-8453-de77e476d797)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 121
filterset (summary):
 network: 130490
 cosmetic: 48642
 scriptlet: 20647
 html: 0
listset (total-discarded, last-updated):
 added:
  SWE-1: 4586-6, 5m
 default:
  user-filters: 0-0, never
  easylist: 84917-659, 5m
  easyprivacy: 50471-838, 5m
  plowe-0: 3759-2, 5m
  ublock-badware: 8398-15, 5m
  ublock-filters: 37481-305, now
  ublock-privacy: 792-0, 5m
  ublock-quick-fixes: 141-0, 5m
  ublock-unbreak: 2243-0, 5m
  urlhaus-1: 8975-10, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3008 ms (selfie)
 maxAssetCacheWait: 1077 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 2
  sharethis.com: 1
 extended:
  ##+js(abort-current-script, document.documentElement, break;case…
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by MattmanXD** [comment]
I've experinced the same issue as well.
