### ISSUE TITLE
sunshine-live.de: breakage

### ISSUE THREAD

**Issue by Bieronaut** [uBlockOrigin/uAssets#23266]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sunshine-live.de/`

### Category

breakage

### Description

If UBlock is activated, none of the web radio streams will play.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-11 174037](https://github.com/uBlockOrigin/uAssets/assets/154052434/237f5529-77da-4ac0-ab4e-bd1f8a75fffa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 123
filterset (summary):
 network: 131200
 cosmetic: 50931
 scriptlet: 20381
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7367-1, 13m
  easylist: 84917-660, 4m Δ
  easyprivacy: 50471-840, 4m Δ
  plowe-0: 3759-0, now
  ublock-badware: 8398-15, 4m Δ
  ublock-filters: 37461-322, 4m Δ
  ublock-privacy: 785-0, 4m Δ
  ublock-quick-fixes: 141-0, 4m Δ
  ublock-unbreak: 2243-2, 4m Δ
  urlhaus-1: 8975-10, 13m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 246 ms (selfie)
 maxAssetCacheWait: 31 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  smartclip.net: 1
  usercentrics.eu: 1
```
</details>

**Comment by liamengland1** [comment]
Test
```
www.sunshine-live.de##+js(set, cpd_configdata, {})
www.sunshine-live.de##+js(set, cpd_configdata.url, '')
```
