### ISSUE TITLE
jofogas.hu: ads

### ISSUE THREAD

**Issue by Kam1kazeHQ** [uBlockOrigin/uAssets#23271]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.jofogas.hu/`

### Category

ads

### Description

Since the "Jófogás" page was updated, advertisements appear on the advertisers pages (https://www.jofogas.hu/.......).

### Other extensions used

x

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 121
filterset (summary):
 network: 129183
 cosmetic: 47672
 scriptlet: 19028
 html: 1769
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37588-108, 14m Δ
  ublock-badware: 8400-15, 14m Δ
  ublock-privacy: 789-1, 14m Δ
  ublock-unbreak: 2300-2, 14m Δ
  ublock-quick-fixes: 136-34, 14m Δ
  easylist: 84975-269, 14m Δ
  easyprivacy: 50471-60, 14m Δ
  urlhaus-1: 8975-10, now
  plowe-0: 3759-1182, now
  HUN-0: 2105-16, 8m
filterset (user): [empty]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 274 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  adverticum.net: 1
  appboycdn.com: 1
  appsflyer.com: 1
```
</details>

**Comment by gorhill** [comment]
How do these advertisements look like? Please post a screenshot showing were these are on the webpage.

**Comment by Kam1kazeHQ** [comment]
![jofogas_screenshot_2024-04-12_01](https://github.com/uBlockOrigin/uAssets/assets/166757308/c76cbdfd-2555-461e-8be2-d40d92d4e64d)

When opening the image gallery, the fourth advertisement appears (while scrolling through the images):

![jofogas_screenshot_2024-04-12_02](https://github.com/uBlockOrigin/uAssets/assets/166757308/bfe6d6cc-9e1d-4e35-baed-efcdb82e2ae3)

**Comment by ItsProfessional** [comment]
Looks like self promotion.

**Comment by gorhill** [comment]
@ItsProfessional Maybe these are shown fo fill the blocked ad placeholders, in which case it would be fair to block these I guess?

@Kam1kazeHQ You provided screenshots but do not provide the fuill URL of were these are seen. I don't see them in the front page, so for the sake of saving our time, provide the URLs were these self-promo ads are seen.

**Comment by ToIgnore** [comment]
@scripthunter7 

`https://www.jofogas.hu/veszprem/Ebike_345_km_rel_147013373.htm`

maybe
```
jofogas.hu##[alt$="promóció"]:upward(2)
jofogas.hu##[id*="adcum-"]
```

**Comment by stephenhawk8054** [comment]
@gorhill Yeah, the site shows 3rd-party ads if disabling uBO. This filter works for me:

```adb
jofogas.hu##+js(nostif, E(!1))
```

I think regional list would be better to decide this.

**Comment by gorhill** [comment]
@stephenhawk8054 Where do you see these ads? I can't find any resembling what I see in the screenshots.

**Comment by gorhill** [comment]
> https://www.jofogas.hu/veszprem/Ebike_345_km_rel_147013373.htm

I don't see ads/ad placeholders, using `.hu` VPN:

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/e7c653c7-d059-42dc-8c94-0b0a229c983b)

**Comment by scripthunter7** [comment]
@stephenhawk8054 @gorhill I pushed a fix to hufilter

**Comment by ToIgnore** [comment]
@gorhill it's caused by the aspect-ratio

**Comment by Kam1kazeHQ** [comment]
The reason I didn't link to the subpage where the ads are is because it's an advertising page, and if what I'm linking is sold in the meantime, you won't see it because it will be deleted.

I updated the hufilter, now it's good. Ads are gone. Thank you all. :)

**Comment by scripthunter7** [comment]
@Kam1kazeHQ you're welcome)
