### ISSUE TITLE
(anti-adblock) dallasnews.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2327]
### URL(s) where the issue occurs

`https://sportsday.dallasnews.com/dallas-cowboys/cowboys/2018/05/19/report-cowboys-wr-terrance-williams-arrested-public-intoxication-frisco`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/40271948-3d094a68-5b62-11e8-8b35-35e1e51c3013.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.6

### Settings

All default

**Comment by mapx-** [comment]
probably is working too
`||courier-js.dallasnews.com`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2bb5c747294ddac80c21020cb48e10d911f81527 breaks scrolling with Chrome on my end, it does work with Firefox.
