### ISSUE TITLE
play.history.com: detection

### ISSUE THREAD

**Issue by LordRelentless** [uBlockOrigin/uAssets#23273]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://play.history.com/shows/the-curse-of-oak-island/season-11/episode-22`

### Category

detection

### Description

UBlock used to block the ads on this page, but not it doesn't. It appears to be a detection and or workaround to UBlock

### Other extensions used

no other extensions that should interfere with UBlock. Ublock is my only ad blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 131816
 cosmetic: 46029
 scriptlet: 20395
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 41-7, never
  easylist: 85003-652, 58m Δ
  easyprivacy: 50471-831, 58m Δ
  plowe-0: 3759-0, now
  ublock-badware: 8398-15, 58m Δ
  ublock-filters: 37481-305, 58m Δ
  ublock-privacy: 792-0, 58m Δ
  ublock-quick-fixes: 141-0, 58m Δ
  ublock-unbreak: 2243-0, 58m Δ
  urlhaus-1: 11875-5, now
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1030 ms
 maxAssetCacheWait: 278 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 356
 network:
  history.com: 3
  adap.tv: 1
  ads-twitter.com: 1
  adsrvr.org: 3
  aetn.com: 3
  agkn.com: 1
  amazon-adsystem.com: 4
  amplitude.com: 6
  app.link: 2
  bluekai.com: 2
  branch.io: 7
  crazyegg.com: 3
  demdex.net: 4
  doubleclick.net: 38
  everesttech.net: 4
  exelator.com: 1
  firebaselogging-pa.googleapis.com: 45
  fwmrm.net: 13
  google-analytics.com: 1
  google.com: 12
  googleadservices.com: 2
  googletagmanager.com: 6
  imrworldwide.com: 13
  krxd.net: 2
  mediamelon.com: 17
  moatads.com: 1
  ns1p.net: 4
  omtrdc.net: 86
  privacy-mgmt.com: 2
  quantserve.com: 1
  rlcdn.com: 1
  samba.tv: 3
  scorecardresearch.com: 39
  sentry.io: 1
  stickyadstv.com: 2
  t.co: 5
  tapad.com: 2
  tidaltv.com: 1
  truex.com: 6
  twitter.com: 5
  w55c.net: 3
 extended:
  ##+js(json-prune, data.reg)
  ##+js(no-xhr-if, time-events)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings

**Comment by ItsProfessional** [comment]
>```yml
>filterset (user): [array of 41 redacted]
>```

You are using a modified configuration of uBO. What custom filters are you using?

> no other extensions that should interfere with UBlock. Ublock is my only ad blocker.

List all of your extensions, not just ones which you believe to "interfere with UBlock"

**Comment by LordRelentless** [comment]
The only custom filter I'm using is one where I selected an ad to block that is persistent, that uBlock isn't blocking automatically. It is unrelated to this site. I have already tested in a different browser, it still doesn't block the ads on the site I linked to. In fact, I've started to notice that uBlock isn't blocking ads on a lot of sites. It used to block ads in gmail but now they're all over the place and I'm constantly having to delete those ads. Facebook is full of ads as well. I don't know why, but it could be because of manifest-v3 which was recently rolled out. Nonetheless, I wouldn't be reporting this here unless it wasn't working.

**Comment by stephenhawk8054** [comment]
> Test again in a new browser profile with only uBO and its default settings

I did not mean test in another old profile of another computer.

**Comment by LordRelentless** [comment]
> > Test again in a new browser profile with only uBO and its default settings
> 
> I did not mean test in another old profile of another browser.

I tested in Firefox and Chromium Canary.

**Comment by mapx-** [comment]
@LordRelentless 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
-

**Comment by stephenhawk8054** [comment]
> > > Test again in a new browser profile with only uBO and its default settings
> > 
> > I did not mean test in another old profile of another browser.
> 
> I tested in Firefox and Chromium Canary. 

**NEW** profile

**Comment by LordRelentless** [comment]
Here's the thing; it's no longer blocking ads on Youtube, Dailymotion, History Channel, CBS, Paramount+, or Amazon Prime. Resetting and doing as you've asked doesn't fix this problem. This is on Chrome version 123.0.6312.123, as well as the latest version of Opera and Firefox. Ublock isn't working anymore for in video ads, at least not for me.

**Comment by stephenhawk8054** [comment]
Did you "create a new profile" like I said in this?

> Create a new Firefox profile like this: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
> 
> Don't sync anything, install uBO and just use its default settings. Then test again.

This is the 4th and the last time I ask about this information. If you still can't follow it, sorry I can't help more.

**Comment by LordRelentless** [comment]
> Did you "create a new profile" like I said in this?
> 
> > Create a new Firefox profile like this: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
> > Don't sync anything, install uBO and just use its default settings. Then test again.
> 
> This is the 4th and the last time I ask about this information. If you still can't follow it, sorry I can't help more.
> 
> If you are using chrome, please follow this: https://support.google.com/chrome/answer/2364824 (don't sync account)

I tested with a new profile, which I stated was the case. I've tested on multiple browsers, and my firefox profile is new. That is to say, it's my backup browser and it doesn't have any profile settings, is bone stock, and had no extensions beyond my installing uBlock to test it. 

Ublock is still not blocking ads on several sites. This is after I've followed all instructions provided. Nor is it blocking inline ads on history.com videos. 

I've provided you with what I've done, telling me to redo the same thing which hasn't worked, doesn't solve the problem. 

I'm letting the uBlock team know that it is no longer functioning properly.

**Comment by stephenhawk8054** [comment]
Can you screenshot how it looks like in that profile?

Then in that profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by LordRelentless** [comment]
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 133622
 cosmetic: 46087
 scriptlet: 20440
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 21-0, never
  ublock-filters: 37506-401, 2h.53m Δ
  ublock-badware: 8248-0, 2h.53m Δ
  ublock-privacy: 800-0, 2h.53m Δ
  ublock-unbreak: 2251-2, 2h.53m Δ
  ublock-quick-fixes: 260-1, 2h.53m Δ
  easylist: 85966-456, 2h.53m Δ
  easyprivacy: 50770-812, 2h.53m Δ
  urlhaus-1: 12415-5, 22h.15m
  plowe-0: 3739-0, 5d.33m
filterset (user): [array of 21 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1057 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 167
 network:
  history.com: 3
  ads-twitter.com: 1
  adsrvr.org: 1
  aetn.com: 2
  amazon-adsystem.com: 4
  amplitude.com: 7
  app.link: 1
  branch.io: 7
  crazyegg.com: 7
  demdex.net: 2
  doubleclick.net: 32
  exelator.com: 4
  firebaselogging-pa.googleapis.com: 4
  fwmrm.net: 8
  google-analytics.com: 1
  google.com: 10
  googletagmanager.com: 6
  imrworldwide.com: 5
  mediamelon.com: 13
  moatads.com: 3
  ns1p.net: 4
  omtrdc.net: 7
  privacy-mgmt.com: 2
  resonate.com: 1
  samba.tv: 3
  scorecardresearch.com: 15
  sentry.io: 1
  t.co: 5
  thrtle.com: 1
  twitter.com: 5
  w55c.net: 2
 extended:
  ##+js(json-prune, data.reg)
  ##+js(no-xhr-if, time-events)
  
![image](https://github.com/uBlockOrigin/uAssets/assets/94130636/a49d564a-49d4-4a8d-a09b-9e16cf10226e)

As you can see, uBlock is not blocking z.moatads.com ads which appear to be running through a javascript randomized API.

**Comment by stephenhawk8054** [comment]
That is not the new Firefox profile you said above?

**Comment by LordRelentless** [comment]
No, it's not, its my main chrome profile. Firefox doesn't show, in the inspect section, the z.moatads.com ads when they play. The only way for me to show you the ads in question that aren't being blocked is in Chrome.

**Comment by stephenhawk8054** [comment]
Ok. Test in that new Firefox profile first. Can you screenshot how the whole page (including the URL bar and the toolbar) looks like?

Then copy the troubleshooting information like the above steps I said.

**Comment by LordRelentless** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/94130636/ffb468f5-3b87-4ed6-a2e3-21404c370ad8)
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 133280
 cosmetic: 45956
 scriptlet: 19048
 html: 1767
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37654-108, 2m
  ublock-badware: 8250-0, 2m
  ublock-privacy: 793-1, 2m
  ublock-unbreak: 2308-2, 2m
  ublock-quick-fixes: 135-28, 2m
  easylist: 85982-172, 2m
  easyprivacy: 50769-61, 2m
  urlhaus-1: 12105-0, 2m
  plowe-0: 3739-1162, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1328 ms
 maxAssetCacheWait: 144 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 83
 network:
  history.com: 5
  amazon-adsystem.com: 4
  amplitude.com: 16
  branch.io: 1
  crazyegg.com: 2
  doubleclick.net: 10
  firebaselogging-pa.googleapis.com: 3
  fwmrm.net: 1
  googletagmanager.com: 2
  imrworldwide.com: 1
  mediamelon.com: 29
  moatads.com: 1
  ns1p.net: 2
  privacy-mgmt.com: 1
  samba.tv: 1
  scorecardresearch.com: 2
  sentry.io: 2
 extended:
  ##+js(json-prune, data.reg)
  ##+js(no-xhr-if, time-events)
  
  I have noticed a difference. In the logger on Firefox 
  https://api2.amplitude.com/2/httpapi  and  	https://beacons.mediamelon.com/StreamProducer
  are being blocked, and while the ad plays on firefox for a brief moment it's then skipped. Bearing in mind that Firefox just updated on me. 
  
  These are not being blocked in Chrome by uBlock.

**Comment by stephenhawk8054** [comment]
So currently do you see the ads on that Firefox profile?

**Comment by LordRelentless** [comment]
I do, but it's brief, then it's blocked.

**Comment by LordRelentless** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/94130636/221da245-adb0-4d1d-b6fd-c295d12f23be)

**Comment by stephenhawk8054** [comment]
Which Firefox edition are you using there, is it ESR? Can you click on `About Firefox` and screenshot it here?

**Comment by LordRelentless** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/94130636/9415bdb9-2c23-4526-8198-ed6f1b0c5660)

**Comment by stephenhawk8054** [comment]
Ok, so when you tested above, your Firefox hasn't updated yet

```yml
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
```

And now it's updated to newest version 125.

Can you restart the browser, then open new tab, and recording how you reproduce the issue again?

**Comment by LordRelentless** [comment]
Well that seems to have fixed it in Firefox. However, that still doesn't resolve the issue I have in Chrome. None of my other extensions should be interfering, nor have they since I started using uBlock over three years ago. It's the only adblocker I use. And as I said, I've noticed that uBlock for Chrome isn't updated to 1.57.2 and isn't blocking the api used by History.com or other video sources like aniwave.to (anime site).

**Comment by stephenhawk8054** [comment]
Ok, so back into your chrome.

- Create a new profile in your chrome here like here: https://support.google.com/chrome/answer/2364824 . DON'T sync any thing. DON'T install any other extensions.
- Install uBO. DON'T add/modify any other settings inside it.
- Then open new tab, and record video how to reproduce the issue again.
