### ISSUE TITLE
aniwatchtv.to: ads

### ISSUE THREAD

**Issue by Narcyftw** [uBlockOrigin/uAssets#23272]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniwatchtv.to/watch/an-archdemons-dilemma-how-to-love-your-elf-bride-19130?ep=123304&source=sub&n_id=661813632664e58edc362aef`

### Category

ads

### Description

Ads exist on the website when pausing the video

### Other extensions used

Pop up blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 128899
 cosmetic: 45980
 scriptlet: 20394
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 84975-652, 1h.35m Δ
  easyprivacy: 50471-831, 1h.35m Δ
  plowe-0: 3759-0, now
  ublock-badware: 8398-15, 1h.35m Δ
  ublock-filters: 37480-305, 1h.35m Δ
  ublock-privacy: 792-0, 1h.35m Δ
  ublock-quick-fixes: 141-0, 1h.35m Δ
  ublock-unbreak: 2243-0, 1h.35m Δ
  urlhaus-1: 8975-10, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 218 ms (selfie)
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 2
  jwpltx.com: 1
  sharethis.com: 2
 extended:
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(set-constant, rwt, noopFunc)
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by huyszn** [comment]
Same issue as #23268
