### ISSUE TITLE
max19.fun adblocker detection and pop up ads on maxstream.video (same site)

### ISSUE THREAD

**Issue by tremoar** [uBlockOrigin/uAssets#23283]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://uprot.net/msf/ic9unfc897ar
```

### Description

This link points to `max19.fun` link, there you'll be faced with adblocker detection, you can replace the url with `maxstream.video`  (it's the same site) and you'll be able to see the video but pop up ads are not blocked, my temp fix is
```
maxstream.video##^script:has-text(createElement('script'))
maxstream.video##^script:has-text(function($,document))
```
but it's only my way to disable ads 

I've noticed that `uprot.net` also detects adblocker now that I disabled my filters, a fast fix can be:
`uprot.net###butok:style(display:block !important)` 
but maybe there is a better solution

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 133443
 cosmetic: 53170
 scriptlet: 19048
 html: 1768
listset (total-discarded, last-updated):
 default:
  user-filters: 603-4, never
  ublock-filters: 37548-108, 3m
  ublock-badware: 8072-0, 3m
  ublock-privacy: 789-1, 3m Δ
  ublock-unbreak: 2303-2, 3m
  easylist: 85268-147, 3m
  easyprivacy: 50480-60, 3m Δ
  plowe-0: 3739-1162, 3m
  ITA-0: 8390-36, 3m
  urlhaus-1: 11800-0, 3m
  ublock-quick-fixes: 152-46, 3m
filterset (user): [array of 595 redacted]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 36 redacted]
hostRuleset:
 added: [array of 72 redacted]
urlRuleset:
 added: [array of 29 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1051 ms (selfie)
 maxAssetCacheWait: 102 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/23137

**Comment by tremoar** [comment]
Sorry, I merged two issues together making this half duplicated (my main issue were pop up ads not prevented on maxstream.video), anyway the fault is that maxstream.video, max19.fun, uprot.net are using temp generated links so they are not geo locked urls. 

Somehow they are looking at this repo issues to IP ban users based on posted links, there is still another way for you to test this urls: 
`https://eurostreaming.money/hightown-2/` 
there you can click on maxstream links, sometimes this site changes its url and you'll have to search eurostreaming on google but this is the best that I can do to let you be able to investigate on this website.
remember also that `max19.fun` is a mirror link of `maxstream.video` which this means that if it's get detected maybe there is some missing shared url for `max19.fun`.

Thanks a lot for your work!
