### ISSUE TITLE
developer.opencv.fr: breakage

### ISSUE THREAD

**Issue by pianist** [uBlockOrigin/uAssets#23282]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://developer.opencv.fr/ui/`

### Category

breakage

### Description

Site is blinking, but is I turn uBlock Origin, it works well.

### Other extensions used

SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 149097
 cosmetic: 66608
 scriptlet: 21787
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 88-0, never
  RUS-0: 39365-95, 35m Δ
  easylist: 85268-455, 35m Δ
  easyprivacy: 50480-794, 35m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8070-0, 35m Δ
  ublock-filters: 37437-431, 35m Δ
  ublock-privacy: 792-0, 35m Δ
  ublock-quick-fixes: 157-0, 35m Δ
  ublock-unbreak: 2246-18, 35m Δ
  urlhaus-1: 11800-0, now
filterset (user): [array of 88 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2245 ms
 maxAssetCacheWait: 492 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
It's blinking even when I don't use any extensions:

https://github.com/uBlockOrigin/uAssets/assets/66517106/3dbcb9a3-809c-427f-8332-81d947d343df

**Comment by dportvine** [comment]
I have another problem. `||cookiebot.com^$from=~cookiebot.com` **AdGuard – Cookie Notices** & **EasyList – Cookie Notices**

<details>
<summary>Video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/41eb5fda-e3b4-46a1-be92-2e192035afeb
</details>
