### ISSUE TITLE
tempest.com: ads

### ISSUE THREAD

**Issue by kegobass** [uBlockOrigin/uAssets#23288]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.tempest.com/search?encq=a%2Bdy3VzsuuYtlpSnQOXV%2BG%2FseYDi%2FlMdVWnxVFyHJkY4nCSZ%2FJxHOubE57x6XmV9gHUl9lbyJMLsrl8KIWPcJoWCA5iBTyYFZ86Hj8qt9C2zBv2adXy%2FpHt7qj1Ih%2BELnPBzxg7c2nAu%2FMeFC2Z%2FF38PY75%2BJq9DeKEWdVNLT3oFK9DZmj7Wbe5nRCeagLZzVRHdWAsUsKS9uBNTb6pRZFEdVootni8a7SZxexHwxpnftaNpopm3AMbqmXsd5z3d0ZhVAZ5Ff0jHg6UcvIb98CMfIaHDbwZnqUThBB2s09gAHpbwNu3VzLMw9zvDFC9w7EtUnNuOC10Sc9PPr4D8XA%3D%3D&encv=61027&encha=sha1
```

### Description

The element pickers do not work on the Tempest.com search results page.

### Other extensions used

![2024-04-13_08-12](https://github.com/uBlockOrigin/uAssets/assets/59669068/af39d094-7d0f-4a4d-b2ad-738c388c03c7)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-04-13_08-14](https://github.com/uBlockOrigin/uAssets/assets/59669068/45461794-6978-4034-bd88-c31f304fad8c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 16727
 cosmetic: 11530
 scriptlet: 20342
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 default:
  user-filters: 17-0, never
  ublock-filters: 37471-104, never
  ublock-badware: 8076-0, never
  ublock-privacy: 792-0, never
  ublock-unbreak: 2246-2, never
  ublock-quick-fixes: 157-43, never
filterset (user): [array of 17 redacted]
userSettings:
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 101 ms (selfie)
 maxAssetCacheWait: 21 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
```
tempest.com##.search-result-item--ad
tempest.com##.search-result-item:has(.search-result-item__title--ad)
```

**Comment by kegobass** [comment]
I tried adding those to the custom filters but it's still not blocking the ads.  Thanks for the suggestion though.

**Comment by JobcenterTycoon** [comment]
Works perfectly for me.

**Comment by JobcenterTycoon** [comment]
@mapx- please take a look

**Comment by kegobass** [comment]
> Works perfectly for me.

Not sure what browser you're using, but I'm using the Tempest Browser which might matter in this case.

**Comment by JobcenterTycoon** [comment]
Ok... pretty sure the "Tempest Browser" hinder uBlock Origin to work properly on `tempest.com`.

**Comment by kegobass** [comment]
Yeah, I'm thinking the Tempest browser itself is the issue at hand.  I use NextDNS mainly for blocking ads configured on my firewall.  I mainly use UBO for cosmetic filtering which works extremely well.

**Comment by JobcenterTycoon** [comment]
In this case we can't do much.
