### ISSUE TITLE
app.magai.co: nuisance

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#23294]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.magai.co/`

### Category

nuisance

### Description

When you register on Magai you will get this unremovable 7 day trial popup however I find out that we can remove these popups by putting 
! 2024-04-13 https://app.magai.co
app.magai.co##.column.flex.bubble-r-container.baTwaZp1.Group.bubble-element
app.magai.co##.baTydaY.greyout
app.magai.co##.baTwaQaG.greyout
app.magai.co##.column.flex.bubble-r-container.baTwaQaG.CustomElement.bubble-element > .column.flex.bubble-r-container.baTwcaY.CustomElement.bubble-element
on the filter however the blurry screen remains, by pressing the "quick action" will temporarily remove the blur.

### Other extensions used

Unrelated to ublock:
cookie editor
dearrow
darkreader
chatgpt box
downthemall

### Screenshot(s)

![librewolf_tyONubkNG3](https://github.com/uBlockOrigin/uAssets/assets/150899804/25e67b36-26b8-44df-b6ed-0fd6e07e53f5)

There are other buggs such as autoscrolling
https://imgur.com/a/I2GnTdU

and a unremovable block where I cannot click
https://imgur.com/a/HMu9PxP

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 121
filterset (summary):
 network: 167757
 cosmetic: 66554
 scriptlet: 20411
 html: 1780
listset (total-discarded, last-updated):
 added:
  RUS-0: 39389-137, 52m Δ
 default:
  user-filters: 49-3, never
  ublock-filters: 37630-108, 1m
  ublock-badware: 8120-0, 1m
  ublock-privacy: 788-1, 1m
  ublock-unbreak: 2303-2, 1m
  ublock-quick-fixes: 122-24, 52m
  easylist: 85488-171, 1m
  adguard-spyware-url: 1493-107, 1m
  easyprivacy: 50735-60, 1m
  urlhaus-1: 11890-0, 1m
  curben-phishing: 14232-2, 1m
  plowe-0: 3739-1163, 1m
  LegitimateURLShortener: 2625-166, 52m
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1060 ms (selfie)
 maxAssetCacheWait: 228 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  bugsnag.com: 1
  dwin1.com: 2
  facebook.net: 1
  intercom.io: 5
  stripe.com: 6
  usefathom.com: 2
  wdfl.co: 2
```
</details>

**Comment by stephenhawk8054** [comment]
This is paywall so you can use them as custom filters.

**Comment by ThePatriotsXOF** [comment]
> This is paywall so you can use them as custom filters.

I pretty much did it already but those bugs I provided are the only I issues im having

**Comment by stephenhawk8054** [comment]
Looks like the site needs account? I don't have account so I can't help more.
