### ISSUE TITLE
Bypass Paywalls Clean filter

### ISSUE THREAD

**Issue by SuperWolf11** [uBlockOrigin/uAssets#23293]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
moz-extension://23961903-718a-4d59-9614-1cf4b2df403b/dashboard.html#3p-filters.html
```

### Description

Bypass Paywalls Clean filter wont update

### Other extensions used

defaults

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 113
filterset (summary):
 network: 150433
 cosmetic: 47056
 scriptlet: 19887
 html: 1764
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37619-108, 20m
  ublock-badware: 8091-0, 20m
  ublock-privacy: 788-1, 20m
  ublock-unbreak: 2303-2, 20m Δ
  ublock-quick-fixes: 122-24, 20m
  easylist: 85386-170, 1h.21m Δ
  adguard-spyware-url: 1493-107, 20m
  easyprivacy: 50735-60, 20m
  urlhaus-1: 11890-0, 20m
  curben-phishing: 14232-1, 20m
  plowe-0: 3739-1163, 20m
  LegitimateURLShortener: 2620-165, 20m
  bpc-paywall-filter: 0-0, never
  AntiPaywall: 2095-22, 22m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 200 ms (selfie)
 maxAssetCacheWait: 100 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
This is uBlock Origin repo.

BPC is removed by gitlab: https://twitter.com/Magnolia1234B/status/1779050596181438791
