### ISSUE TITLE
jobhelpnews.in: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#23296]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jobhelpnews.in/financial-wellness-a-holistic-approach-to-managing-loans-insurance-and-homeownership/`

### Category

detection

### Description

https://gplinks.co/dLO9rDr

### Other extensions used

Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 133759
 cosmetic: 53920
 scriptlet: 19090
 html: 1765
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37992-109, 1h.34m Δ
  ublock-badware: 8114-0, 1h.34m Δ
  ublock-privacy: 788-1, 1h.34m Δ
  ublock-unbreak: 2308-2, 1h.34m Δ
  ublock-quick-fixes: 122-24, 1h.34m Δ
  adguard-mobile: 9241-64, now
  easylist: 85488-229, now
  easyprivacy: 50735-68, now
  urlhaus-1: 11890-0, now
  plowe-0: 3739-1237, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18068 ms (selfie)
 maxAssetCacheWait: 169 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  digislots.in: 2
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
ask for help here: https://github.com/uBlockOrigin/uAssets/discussions/17361
