### ISSUE TITLE
[nsfw] eatcells.com: popups

### ISSUE THREAD

**Issue by Melody1962** [uBlockOrigin/uAssets#23295]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eatcells.com/land/?token=bf42c28284d124a59cf58bf626f84db4`

### Category

popups

### Description

This Site opens when I Open my Mobile Phone.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 261440
 cosmetic: 254970
 scriptlet: 50159
 html: 2023
listset (total-discarded, last-updated):
 added:
  https://www.koketti.com/: 0-0, never
  adguard-generic: 80710-3920, now
  adguard-spyware-url: 1493-107, now
  adguard-spyware: 104176-1376, now
  block-lan: 61-0, now
  curben-phishing: 14232-3, now
  adguard-social: 22783-53, now
  adguard-cookies: 29238-46, now
  ublock-cookies-adguard: 1110-14, now
  adguard-popup-overlays: 27072-994, now
  adguard-mobile-app-banners: 5139-26, now
  adguard-other-annoyances: 14137-409, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37992-109, now
  ublock-badware: 8114-0, now
  ublock-privacy: 788-1, now
  ublock-unbreak: 2308-2, now
  ublock-quick-fixes: 122-24, now
  adguard-mobile: 9242-92, now
  easylist: 85488-1656, now
  easyprivacy: 50735-32158, now
  urlhaus-1: 11890-0, now
  plowe-0: 3739-1649, now
  DEU-0: 7374-61, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2039 ms (selfie)
 maxAssetCacheWait: 941 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  addthis.com: 1
 extended:
  ###share
  ##.share__text
  ##.addthis_inline_share_toolbox
```
</details>

**Comment by mapx-** [comment]
> This Site opens when I Open my Mobile Phone

scan your phone using some anti malware software
