### ISSUE TITLE
nulledteam.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2329]
URL(s) where the issue occurs

`https://www.nulledteam.com/forums/xenforo-add-on-releases-2-x.81/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.4

Settings

Default

**Comment by mapx-** [comment]
Does not work for me FF / chrome

It works (only FF):
`nulledteam.com##script:inject(abort-on-property-read.js, _0x57e0)`

**Comment by okiehsch** [comment]
Yes, `bab-defuser` does only work with Chrome, never saw that before, I did not check with Firefox.
`nulledteam.com##script:inject(abort-on-property-read.js, _0x57e0)`   does not work with Firefox on my end.

**Comment by mapx-** [comment]
well, bab does not work for me, disabling cosmetic filtering either

**Comment by okiehsch** [comment]
`nulledteam.com##^script:has-text(_0x)` should work?

**Comment by mapx-** [comment]
sure, working for FF

**Comment by okiehsch** [comment]
OK I misunderstood, `bab-defuser` does not work for you using Chrome?
It does for me.

**Comment by mapx-** [comment]
for chrome - for me - only classic whitelisting:
```
@@||nulledteam.com^$generichide
@@||pagead2.googlesyndication.com/pagead/$script,domain=nulledteam.com
nulledteam.com##[id^=aswift]
```

**Comment by mapx-** [comment]
could be something related to the last modality of injecting ?! I'm using last dev builds FF / chrome

**Comment by okiehsch** [comment]
I tried with both dev and stable builds and `bab-defuser` never works with Firefox on my end.
It does work with Chrome dev, which is my standard setup.

**Comment by mapx-** [comment]
Weird, could be due to my old system and because their script is placed at the very head of the page

**Comment by mapx-** [comment]
I'm using windows 10, updated yesterday ... who knows if it has some impact on this issue

**Comment by okiehsch** [comment]
Yes, it certainly is a race condition.
`nulledteam.com##script:inject(setInterval-defuser.js, visibility, 1000)`
works on my end.

**Comment by mapx-** [comment]
good news: `nulledteam.com##script:inject(setInterval-defuser.js, visibility, 1000)` works fine on both FF / chrome

**Comment by okiehsch** [comment]
I think for now the `setInterval-defuser.js` fix should be used if the blockadblock script is  at the top of the HTML document, to be sure that the fix works for everyone.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
