### ISSUE TITLE
rentcafe.com: breakage

### ISSUE THREAD

**Issue by j1101th** [uBlockOrigin/uAssets#23301]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rentcafe.com/apartments-for-rent/us/ca/los-angeles/`

### Category

breakage

### Description

None of the badges work for the search filter on the site.

### Other extensions used

Privacy Badger
Decentraleyes
Clean URL

Disabled all of these though when testing in private mode

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1439" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/63700139/3e582bc2-a12e-44d6-b88c-ac8263ea1f48">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 132306
 cosmetic: 45967
 scriptlet: 18980
 html: 1732
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37554-104, 14m
  ublock-badware: 8120-0, 14m
  ublock-privacy: 788-1, 14m
  ublock-unbreak: 2305-2, 14m
  easylist: 85468-172, 14m
  easyprivacy: 50747-60, 14m
  urlhaus-1: 11800-5, 14m
  plowe-0: 3739-1162, 14m
  ublock-quick-fixes: 129-10, 14m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 399 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  rentcafe.com: 1
  cloudflareinsights.com: 1
  getblueshift.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||cdn.getblueshift.com/blueshift.js$script,domain=rentcafe.com`

@ryanbr
