### ISSUE TITLE
gdpr.twitter.com: popups

### ISSUE THREAD

**Issue by metametapod** [uBlockOrigin/uAssets#23303]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://gdpr.twitter.com
```

### Description

Cookie notice visible (see attached screenshot). Suggested rule addition:

```
twitter.com##+js(trusted-set-cookie, twtr_pixel_opt_in, N)
```

or

```
gdpr.twitter.com##+js(trusted-set-cookie, twtr_pixel_opt_in, N)
```

(not sure if it applies to other subdomains)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1028" alt="Screenshot 2024-04-14 at 15 20 58" src="https://github.com/uBlockOrigin/uAssets/assets/80652640/101381bf-13b0-46dc-8ab1-edd2da9227cd">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 134143
 cosmetic: 90901
 scriptlet: 23985
 html: 1765
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50860-185, 8m
  ublock-cookies-easylist: 1072-3, 8m
 default:
  user-filters: 0-0, never
  ublock-filters: 37646-108, 29m Δ
  ublock-badware: 8116-0, 29m Δ
  ublock-privacy: 789-1, 29m Δ
  ublock-unbreak: 2305-2, 29m Δ
  ublock-quick-fixes: 129-28, 29m Δ
  easylist: 85468-171, 29m Δ
  easyprivacy: 50745-60, 1m Δ
  urlhaus-1: 11800-5, 1m
  plowe-0: 3739-1162, 9m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 381 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by mapx-** [comment]
you do not need the trusted way

`gdpr.twitter.com##+js(set-cookie, twtr_pixel_opt_in, N)`

@ryanbr 

however it's already included in [AdGuard – Cookie Notices](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-cookies)
