### ISSUE TITLE
btvplus.bg: detection

### ISSUE THREAD

**Issue by hunterA1984** [uBlockOrigin/uAssets#23306]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://btvplus.bg/produkt/predavaniya/56458/120-minuti/120-minuti-14-04-2024-g`

### Category

detection

### Description

Тhey wish to stop add block and it is not possible to watching videos

### Other extensions used

not

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 132351
 cosmetic: 45981
 scriptlet: 20480
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  easylist: 85488-553, 10m Δ
  easyprivacy: 50748-792, 10m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8114-0, 10m Δ
  ublock-filters: 37559-295, 10m Δ
  ublock-privacy: 792-2, 10m Δ
  ublock-quick-fixes: 134-0, 10m Δ
  ublock-unbreak: 2248-20, 10m Δ
  urlhaus-1: 11800-5, never
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 448 ms (selfie)
 maxAssetCacheWait: 159 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 47
 network:
  2mdn.net: 14
  doubleclick.net: 4
  google-analytics.com: 20
  google.bg: 1
  google.com: 4
  googlesyndication.com: 3
  gstatic.com: 1
```
</details>

**Comment by mapx-** [comment]
@hunterA1984 

- enable Bulgarian Adblock list
- if still you get detection => reset uBO to defaults (and check if the bulgarian list has been already enabled)
