### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by EkakshGaming** [uBlockOrigin/uAssets#23308]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/`

### Category

breakage and malfunction 

### Description

whenever i try to play a song the shows following sentence shown in the screen shot and i highly doubt on ublock origin. If anyone has solution to this issue reply to this.

### Other extensions used

i use Thorium browser and ublock origin nothing else

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/99182852/8b97f681-20b8-43a4-98ec-24e093ddfd5b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.3b1
Chromium: 122
filterset (summary):
 network: 132536
 cosmetic: 45920
 scriptlet: 20497
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37569-128, 4m Δ
  ublock-badware: 8134-0, 4m Δ
  ublock-privacy: 799-0, 4m Δ
  ublock-unbreak: 2248-4, 4m Δ
  ublock-quick-fixes: 140-0, 4m Δ
  easylist: 85793-554, 4m Δ
  easyprivacy: 50749-187, 4m Δ
  urlhaus-1: 11600-5, 4m
  plowe-0: 3739-790, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1200 ms
 maxAssetCacheWait: 221 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  google.com: 7
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 3
  spotifycdn.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
desktop / android ?

**Comment by dportvine** [comment]
Tested without uBO?
