### ISSUE TITLE
login.deepin.org: breakage

### ISSUE THREAD

**Issue by hualet** [uBlockOrigin/uAssets#23317]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://login.deepin.org/oauth2/authorize?client_id=fcb9f8cac81074100b9482d534767a1fecc148b3&redirect_uri=https:%2F%2Faccount.deepin.org%2Flogin&response_type=code&scope=user.api:base,user.api:contact&state=12eb9b48ea2a4903afe79c2322cd0e32`

### Category

breakage

### Description

can't login due to the filter of `ac.dun.163yun.com^` which is necessary for oauth login to login.deepin.org.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/2023967/a54856a1-6f9f-41ce-a452-67ae863ca312)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 147889
 cosmetic: 56584
 scriptlet: 20604
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 25702-141, now
  easylist: 85967-483, 1h.18m Δ
  easyprivacy: 50755-812, 1h.18m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8171-0, 1h.18m Δ
  ublock-filters: 37564-411, 1h.18m Δ
  ublock-privacy: 796-0, 1h.18m Δ
  ublock-quick-fixes: 140-0, now
  ublock-unbreak: 2248-2, 1h.18m Δ
  urlhaus-1: 12000-5, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 500 ms (selfie)
 maxAssetCacheWait: 166 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  163.com: 6
  163yun.com: 12
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`||ac.dun.163yun.com^$badfilter`
