### ISSUE TITLE
download.megaup.net: detection

### ISSUE THREAD

**Issue by Marcinho-3-bola** [uBlockOrigin/uAssets#23312]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/`

### Category

detection

### Description

![imagem_2024-04-15_202036442](https://github.com/uBlockOrigin/uAssets/assets/113278383/0e74c958-816f-4ed1-a9ba-cfd8501cd082)

### Other extensions used

all disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagem_2024-04-15_202115534](https://github.com/uBlockOrigin/uAssets/assets/113278383/7660ba1e-2ed1-4730-a9cb-448a734b04e2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 121
filterset (summary):
 network: 166327
 cosmetic: 101181
 scriptlet: 40152
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80719-5435, now
  adguard-other-annoyances: 14140-7, now
  curben-phishing: 14228-0, now
 default:
  user-filters: 16-0, never
  easylist: 85856-618, now
  easyprivacy: 50750-2, now
  plowe-0: 3739-791, now
  spa-1: 5511-29, now
  ublock-badware: 8132-1, now
  ublock-filters: 37563-553, now
  ublock-privacy: 796-2, now
  ublock-quick-fixes: 140-0, now
  ublock-unbreak: 2248-23, now
  urlhaus-1: 11600-5, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 72803 ms (selfie)
 maxAssetCacheWait: 9986 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  megaup.net: 2
  altowriestwispy.com: 1
  bidgear.com: 1
  keydawnawe.com: 1
 extended:
  ##+js(trusted-replace-node-text, script, /!=\s*_/, ==_)
  ##+js(trusted-replace-node-text, script, /!=\s*'/, ==')
  ##+js(spoof-css, a img:not([src="images/main_logo_inverted.png"]…
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(remove-node-text, script, FingerprintJS)
  ##+js(abort-current-script, I833)
  ##+js(set-constant, zJSYdQ, true)
  ##+js(set-constant, ASksiwk, true)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(abort-current-script, navigator, FingerprintJS)
```
</details>

**Comment by Elrasiel** [comment]
I can confirm that updating filter list does not fix this issue.

**Comment by huyszn** [comment]
Duplicate, continue in #20505
