### ISSUE TITLE
nicovideo.jp: nuisance

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uAssets#23310]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
`https://www.nicovideo.jp/tag/TAS?sort=f&order=d`
```

### Description

Since at least 4 April 2024, niconico started inserting ニコニ広告 (user ads) slots into an otherwise chronological search. This currently only affects tag search but not keyword search (e.g. `https://www.nicovideo.jp/search/TAS?sort=f&order=d`).

`www.nicovideo.jp##.nicoadVideoItem`

### Other extensions used

none

### uBlock Origin version

v1.56.0

### Browser name and version

Firefox 115.9.1esr

**Comment by stephenhawk8054** [comment]
```adb
||nicoad.nicovideo.jp^
```

?

@Yuki2718

**Comment by Yuki2718** [comment]
We intentionally unblocked that. https://github.com/easylist/easylist/pull/8326 Will check later today.

**Comment by stephenhawk8054** [comment]
@otksm Does the ad appear if you add the above filter?

**Comment by Yuki2718** [comment]
This should be at best addressed in Annoyances, but does `##.nicoadVideoItem` affect other pages?

**Comment by Yuki2718** [comment]
I'll check various page if it is desirable to block, but want to hear from those who actually use niconico.

**Comment by stm-x** [comment]
Hello.
Am I correct that you are all talking about this function?
`https://blog.nicovideo.jp/niconews/218554.html`

If so, this is a matter of personal preference.
Some people will dislike this feature, some will like it.

Personally, I find it annoying that the tag search recommends videos with other tags.

When I do tag searches, I'm often looking for games or characters that I'm interested in and focused on.
I find it annoying to see videos with other tags.

**Comment by Yuki2718** [comment]
Thanks, fixed in annoyances lists. I see them only in search pages but anyway specified the path for additional safety.

**Comment by stm-x** [comment]
Hi all,
The specified path seems to be wrong.
This element is under `/tag` . Not `/search` 
Also, have the element names been changed?
In my environment it is `##.nicodicNicoadVideoList` 

<details>
<summary>Screenshot</summary>

![タイトルなし](https://github.com/uBlockOrigin/uAssets/assets/86018494/5c155a7a-29f7-4962-a2e8-a92c771073e6)

</details>

**Comment by stm-x** [comment]
BTW, the same elements appear on the mobile version of the website.

<details>
<summary>Screenshot</summary>

![タイトルなし1](https://github.com/uBlockOrigin/uAssets/assets/86018494/1115dadd-67a8-4ed8-be8b-e176234e53d2)

</details>

`sp.nicovideo.jp##.searchResult-nicoadNicodicItem`

**Comment by Yuki2718** [comment]
I see on `https://www.nicovideo.jp/search/%E6%9D%B1%E5%8C%97` too.

**Comment by stm-x** [comment]
> I see `.nicoadVideoItem` on `https://www.nicovideo.jp/search/%E6%9D%B1%E5%8C%97` too. Looks `.nicodicNicoadVideoList` is different and more salient.

Hmm. It doesn't seem to show up in my environment.
Maybe it's an A/B test.

Anyway, Thanks for updating the rules!
