### ISSUE TITLE
botsrv2.com: breakage

### ISSUE THREAD

**Issue by bubenkoff** [uBlockOrigin/uAssets#23318]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://bots.sefbot.cz/qb/A7VaDrlP4ZrB6xgO/seatradecruiseglobal?mode=preview
```

### Description

I am reporting as a team member of Quriobot chatbot service (https://quriobot.com). 
We use botsrv2.com domain for the chatbot widget-related resources.
In our view, those should not be considered unwanted ads and be blocked.
Please consider removing our domain from the block list.
Thank you.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1186" alt="Screenshot 2024-04-16 at 13 56 27" src="https://github.com/uBlockOrigin/uAssets/assets/427136/09e2361f-0565-483b-95a2-30e3d53f94c2">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 133120
 cosmetic: 46027
 scriptlet: 20421
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 85967-554, 22m Δ
  easyprivacy: 50755-2, 22m Δ
  plowe-0: 3764-809, 12d.21h.35m
  ublock-badware: 8171-0, 22m Δ
  ublock-filters: 37564-295, 22m Δ
  ublock-privacy: 796-2, 22m Δ
  ublock-quick-fixes: 140-0, 22m Δ
  ublock-unbreak: 2248-20, 22m Δ
  urlhaus-1: 12000-5, 5h.17m
filterset (user): [empty]
trustedset:
 added: [array of 61 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4776 ms
 maxAssetCacheWait: 927 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  botsrv2.com: 3

```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
moved to chat widgets list
https://github.com/easylist/easylist/commit/e432599cc5b2a96c2eb05dbcb93d91e71ee81d28

**Comment by bubenkoff** [comment]
@mapx- 
thank you very much!
