### ISSUE TITLE
fantasy.espn.com: breakage

### ISSUE THREAD

**Issue by noelpurcell** [uBlockOrigin/uAssets#23314]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fantasy.espn.com/baseball/rosterfix?leagueId=92006&seasonId=2024&teamId=1&players=39680&type=claim`

### Category

breakage

### Description

Unable to edit lineups, receive the following error
<img width="358" alt="Screenshot 2024-04-15 at 8 07 43 PM" src="https://github.com/uBlockOrigin/uAssets/assets/167147503/a7e2e82b-328c-4589-aeb0-56eb073b3892">

https://github.com/uBlockOrigin/uAssets/assets/167147503/7e694855-b3bd-45b0-8637-ebcdc40e2d0d

### Other extensions used

Reading List, Wayback Machine, Download All Images, Save Webp as JPG or PNG, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 124
filterset (summary):
 network: 132545
 cosmetic: 45921
 scriptlet: 18985
 html: 1734
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37556-103, now
  ublock-badware: 8134-0, now
  ublock-privacy: 793-1, now
  ublock-unbreak: 2305-2, now
  ublock-quick-fixes: 135-20, 13m
  easylist: 85856-179, now
  easyprivacy: 50750-61, now
  urlhaus-1: 11600-5, now
  plowe-0: 3739-1162, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
@noelpurcell in order to be able to investigate your issue we need an account and the steps to reproduce the issue. 
Are you willing to provide your account credentials ? (I'll provide an email address if you agree)
