### ISSUE TITLE
3dzone.link always asks to remove(not just disable) uBlock

### ISSUE THREAD

**Issue by melnation-com** [uBlockOrigin/uAssets#2331]
while there's no pop-up / indicator, it will remove/not show the DL links for said item like this 

`https://3dzone.link/props/hd-flute-and-poses-for-genesis-8.html`

Note: `www.daz3d.com/hd-flute-and-poses-for-genesis-8` <-- this is not the DL link this is just the product info, I usually see a mega.co link already

**Comment by okiehsch** [comment]
I do not see a `mega.co` link even if I disable `uBlock Origin` on my end.

**Comment by jspenguin2017** [comment]
I don't see it neither, but it's right there in the DOM so...

**Comment by okiehsch** [comment]
Well, I tried different pages and the same thing happens, I can see the link in the source but no link appears with or without an active uBO, so this seems to be a site issue.

If you really need those links, just click `Ctrl + U` then search for `mega.nz` and you will see the clickable link.

**Comment by melnation-com** [comment]
Thank you guys you're too kind!
![Alt Text](https://media.giphy.com/media/3orif9Vvh80kw04Q1i/giphy.gif)
