### ISSUE TITLE
bikroy.com: detection

### ISSUE THREAD

**Issue by muktadir921** [uBlockOrigin/uAssets#23322]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bikroy.com/en/ads?query=laptop`

### Category

detection
![Screenshot 2024-04-16 211048](https://github.com/uBlockOrigin/uAssets/assets/35826342/b86fa926-1fb8-455d-9b39-76f48158f80d)

### Description

detect adblock

### Other extensions used

popup blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 160470
 cosmetic: 210437
 scriptlet: 33794
 html: 0
listset (total-discarded, last-updated):
 added:
  IND-0: 13087-0, now
  adguard-cookies: 29263-51, now
  adguard-mobile-app-banners: 5144-7, now
  adguard-other-annoyances: 14143-96, now
  adguard-popup-overlays: 27110-673, now
  adguard-social: 22811-919, now
  adguard-widgets: 2471-17, now
  dpollock-0: 11668-0, now
  easylist-annoyances: 4486-44, 30m
  easylist-chat: 189-0, now
  easylist-newsletters: 7163-10, 30m
  easylist-notifications: 2985-1480, 30m
  [5 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 85970-717, 30m Δ
  easyprivacy: 50767-244, 30m Δ
  plowe-0: 3739-1228, now
  ublock-badware: 8181-1, 30m Δ
  ublock-filters: 37570-722, 30m Δ
  ublock-privacy: 796-4, 30m Δ
  ublock-quick-fixes: 145-0, 30m Δ
  ublock-unbreak: 2248-23, 30m Δ
  urlhaus-1: 12315-5, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3559 ms (selfie)
 maxAssetCacheWait: 933 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 167
 network:
  bikroy.com: 4
  ampproject.org: 2
  bugsnag.com: 8
  d31qbv1cthcecs.cloudfront.net: 1
  doubleclick.net: 34
  facebook.com: 5
  facebook.net: 2
  google-analytics.com: 7
  google.com: 25
  google.com.bd: 2
  googleadservices.com: 8
  googlesyndication.com: 55
  googletagmanager.com: 4
  googletagservices.com: 3
  newrelic.com: 1
  nr-data.net: 2
  webengage.co: 1
  webengage.com: 3
 extended:
  ##[name^="google_ads_iframe"]
  ##div[data-google-query-id]
  ##iframe[name="googlefcPresent"]
  ##.img_ad
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###adunit
  ##.ad-1
  ##.advertiser
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
  ##div[id^="ad_position_"]
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
