### ISSUE TITLE
reddit.com: popup

### ISSUE THREAD

**Issue by Albertfanmingo** [uBlockOrigin/uAssets#23326]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.reddit.com/r/SuperMarioBros35/comments/zs2blf/need_help_mario_bros_35_custom_server/
```

### Description

On mobile, a popup appears forcing the user to either switch to the reddit app or return to the home page. This appears on posts in subreddits that have not been reviewed, or NSFW posts.

### Other extensions used

Read Aloud: Text to Speech

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240416_122258_Firefox](https://github.com/uBlockOrigin/uAssets/assets/165856136/8e94b818-4c7f-4cba-871f-8e740914ee74)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 134803
 cosmetic: 53885
 scriptlet: 19120
 html: 1768
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38018-109, 35m Δ
  ublock-badware: 8177-0, 35m Δ
  ublock-privacy: 793-1, 35m Δ
  ublock-unbreak: 2310-2, 35m Δ
  ublock-quick-fixes: 140-29, 35m Δ
  adguard-mobile: 9242-64, 1d.18h.55m
  easylist: 85970-230, 35m Δ
  easyprivacy: 50767-69, 35m Δ
  urlhaus-1: 12315-5, 22m
  plowe-0: 3758-1256, 9d.18h.33m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1623 ms (selfie)
 maxAssetCacheWait: 188 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  reddit.com: 11
  ad-delivery.net: 1
  redditstatic.com: 1
 extended:
  ##reddit-breadcrumbs
  ##.promotedlink:not([style^="height: 1px;"])
  ##shreddit-comments-page-ad
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(abort-on-property-write, STICKY_CANARY)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)

```
</details>

**Comment by ToIgnore** [comment]
enable `uBlock Annoyances`

**Comment by Albertfanmingo** [comment]
Just tried this, the popup in the center is gone, but there is still blur making the site unusable.
![Screenshot_20240417_152426_Firefox](https://github.com/uBlockOrigin/uAssets/assets/165856136/c24083b3-27df-4d5f-8b81-fde937c24455)
