### ISSUE TITLE
survivopedia.com: ads

### ISSUE THREAD

**Issue by koreirozzu** [uBlockOrigin/uAssets#23329]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.survivopedia.com/`

### Category

ads

### Description

Strange clickbait ads are back, were patched earlier:
![image](https://github.com/uBlockOrigin/uAssets/assets/167055039/7994d1cc-a22b-468b-bf58-130826a0773f)

### Other extensions used

Privacy Badger
Wappalyzer
Tampermonkey
Privacy Badger
Return YouTube Dislike
Indie Wiki Buddy
SponsorBlock
React Dev Tools
DeArrow

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 144907
 cosmetic: 201946
 scriptlet: 32137
 html: 2013
listset (total-discarded, last-updated):
 added:
  block-lan: 61-0, 4m
  adguard-social: 22813-47, 4m
  adguard-cookies: 29264-40, 4m
  ublock-cookies-adguard: 1077-13, 4m
  adguard-popup-overlays: 27114-969, 4m
  adguard-mobile-app-banners: 5144-21, 4m
  adguard-other-annoyances: 14144-407, 4m
  adguard-widgets: 2471-9, 4m
  fanboy-thirdparty_social: 68-3, 4m
  easylist-annoyances: 4492-276, 4m
  easylist-chat: 190-16, 4m
  fanboy-cookiemonster: 50878-3891, 4m
  [5 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 37548-108, 4m
  ublock-badware: 8183-0, 4m
  ublock-privacy: 793-1, 4m
  ublock-unbreak: 2305-2, 4m
  ublock-quick-fixes: 176-62, 26m Δ
  easylist: 85982-171, 4m
  easyprivacy: 50766-61, 4m
  urlhaus-1: 12415-5, 4m
  plowe-0: 3739-1163, 5m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 832 ms (selfie)
 maxAssetCacheWait: 293 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  googletagmanager.com: 2
  maps.googleapis.com: 1
  sumome.com: 1
  trackerrr.com: 12
  wp.com: 2
 extended:
  ##.grecaptcha-badge
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
```
</details>

**Comment by stephenhawk8054** [comment]
Discussing here: https://github.com/easylist/easylist/pull/19008
