### ISSUE TITLE
web1.faselhd-watch.shop: breakage

### ISSUE THREAD

**Issue by iNawar7** [uBlockOrigin/uAssets#23328]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://web1.faselhd-watch.shop/episodes/%d9%85%d8%b3%d9%84%d8%b3%d9%84-family-guy-%d8%a7%d9%84%d9%85%d9%88%d8%b3%d9%85-%d8%a7%d9%84%d8%ab%d8%a7%d9%86%d9%8a-%d9%88%d8%a7%d9%84%d8%b9%d8%b4%d8%b1%d9%88%d9%86-%d8%a7%d9%84%d8%ad%d9%84-13`

### Category

breakage

### Description

"I apologize if I'm doing something wrong, but I created an account specifically to find a solution for this site. I've tried updating the filters, but it hasn't solved the problem. The issue is that when I turn on uBlock Origin, the ads disappear, but the main video stops and shows a black screen instead."

NOTE:
"I am experiencing the same issue with all ad-blockers."

### Other extensions used

ad-block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image_2024-04-17_03-49-35](https://github.com/uBlockOrigin/uAssets/assets/167263970/5133bd95-619a-46f5-be32-d0ce652e8e1b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 152117
 cosmetic: 53338
 scriptlet: 20568
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 24246-37, now
  ara-0: 2327-4, now
  easylist: 85982-668, now
  easyprivacy: 50766-1018, now
  plowe-0: 3739-52, now
  ublock-badware: 8181-16, now
  ublock-filters: 37465-367, now
  ublock-privacy: 796-0, now
  ublock-quick-fixes: 250-0, now
  ublock-unbreak: 2248-7, now
  urlhaus-1: 12415-5, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1756 ms
 maxAssetCacheWait: 657 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  cloudflare.com: 2
  googletagmanager.com: 1
  jewhouca.net: 3
  jsdelivr.net: 1
  jwpcdn.com: 1
  jynxuiowgkxupil.com: 2
  oagnolti.net: 3
  tfqvlawqp.xyz: 2
  unpkg.com: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
What country are you connecting from ?

I tested it from an european country and I get redirected to:
`https://www.faselhdwatch.top/episodes/%d9%85%d8%b3%d9%84%d8%b3%d9%84-family-guy-%d8%a7%d9%84%d9%85%d9%88%d8%b3%d9%85-%d8%a7%d9%84%d8%ab%d8%a7%d9%86%d9%8a-%d9%88%d8%a7%d9%84%d8%b9%d8%b4%d8%b1%d9%88%d9%86-%d8%a7%d9%84%d8%ad%d9%84-13`

without experimenting any breakage

**Comment by ToIgnore** [comment]
Please visit `chrome://settings/security`, scroll down to `Select DNS provider`. Can you use Google DNS or Cloudflare DNS?

Visit `chrome://extensions/` -> you do not need AdBlock, or any other ad blocker while using uBlock Origin/
