### ISSUE TITLE
nextdoor.com: breakage

### ISSUE THREAD

**Issue by svan71** [uBlockOrigin/uAssets#23321]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://nextdoor.com/g/5td2klhwc/
https://nextdoor.com/g/aze5vpjdy/
```

### Description

Parts of the page fail to load.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1441" alt="Screenshot 2024-04-16 at 10 28 24 AM" src="https://github.com/uBlockOrigin/uAssets/assets/48870638/0dc34b1c-9324-4ecd-ad4d-d7b078481d39">
<img width="1690" alt="Screenshot 2024-04-16 at 10 45 00 AM" src="https://github.com/uBlockOrigin/uAssets/assets/48870638/c2660736-b3a4-4b0a-9bb0-579ba0b43b96">

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 167786
 cosmetic: 200608
 scriptlet: 29953
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78056-30706, 1d.11h.18m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 0-0, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 740-8, 10h.19m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-1, 1d.11h.18m
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt: 409-0, 1d.11h.18m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98118-85806, 1d.11h.18m
  adguard-spyware-url: 1493-160, 1d.11h.18m
  block-lan: 61-0, 1d.11h.18m
  curben-phishing: 14197-9, 10h.19m
  adguard-cookies: 29240-48, 1d.11h.13m
  ublock-cookies-adguard: 1075-1, 1d.11h.13m
  fanboy-cookiemonster: 50860-3858, 1d.11h.13m
  [4 lists not shown]: [too many]
 default:
  ublock-filters: 37570-297, 14m
  ublock-badware: 8181-4, 1m Δ
  ublock-privacy: 796-22, 1m Δ
  ublock-unbreak: 2248-3, 1m Δ
  ublock-quick-fixes: 145-0, 1m Δ
  easylist: 85970-571, 1m Δ
  easyprivacy: 50767-52, 1m Δ
  urlhaus-1: 12000-5, 10h.19m
  plowe-0: 3739-792, 1d.11h.18m
filterset (user): [array of 181 redacted]
trustedset:
 added: [array of 26 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 374 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
```
</details>

**Comment by svan71** [comment]
So far, it works like a charm.  Thank you.  It started about 3–4 days ago.  I went through all my setting in UBO, but like a dope I started from the bottom, disabling and re-enabling until I figured out which item was the culprit.  You fixed it on the first attempt, that's awesome.  The built-in UBO AD blocker blocks things others simply do not, and I would have hated to lose it.

Steve

**Comment by D4niloMR** [comment]
On `https://nextdoor.com/for_sale_and_free` with the exception filter should be ads, can you test this?

```adb
nextdoor.com##+js(json-prune, data.searchClassifiedFeed.searchResultView.[].searchResultItemsV2.edges.[].node.item.content.creative, data.searchClassifiedFeed.searchResultView.[].searchResultItemsV2.edges.[].node.item.content.creative.clickThroughEvent.adsTrackingMetadata.metadata.adRequestId)
```

**Comment by svan71** [comment]
Not so good

<img width="1898" alt="Screenshot 2024-04-17 at 4 01 35 PM" src="https://github.com/uBlockOrigin/uAssets/assets/48870638/015898b8-c95b-4409-a180-4d9589805b98">
