### ISSUE TITLE
kachelmannwetter.com: ads

### ISSUE THREAD

**Issue by mobergmann** [uBlockOrigin/uAssets#23320]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kachelmannwetter.com/`

### Category

ads

### Description

There are still leftovers of the ads, where the ads appear to load infinitely, showing an loading animation.
For example see the screenshot below (In this context _Anzeige_ is German for Advertisement):

### Other extensions used

Tested with the relevant tuned of, but will list them anyway. I have ...
- Bitwarden
- Hide Shorts for Youtube
- Gnome Shell integration
- DuckDuckGo
- ClearURLs 
... installed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/23003549/5e74acf8-3d27-4efe-a841-8c25c5ab0faf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 133405
 cosmetic: 45956
 scriptlet: 19049
 html: 1767
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37654-108, now
  ublock-badware: 8183-0, now
  ublock-privacy: 793-1, now
  ublock-unbreak: 2305-2, now
  ublock-quick-fixes: 140-29, now
  easylist: 85970-172, now
  easyprivacy: 50767-61, now
  urlhaus-1: 12315-5, now
  plowe-0: 3739-1162, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 187 ms (selfie)
 maxAssetCacheWait: 48 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  kachelmannwetter.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  iocnt.net: 1
  m6r.eu: 1
  yieldlove.com: 1
 extended:
  ##.dkpw-billboard-margin
  ##.kw-ad-right
  ##.sdgAnz-rectangle.sdgAnzeigenkennung
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
enable the regional list: EasyList Germany
