### ISSUE TITLE
hardverapro.hu: ads

### ISSUE THREAD

**Issue by xXRealXxx** [uBlockOrigin/uAssets#23335]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hardverapro.hu/apro/rengeteg_ps3_jatek_olcson/hsz_1-200.html`

### Category

ads

### Description

Banner ad is not blocked by Ublock Origin on this website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1269" alt="8oUfLFBU2t" src="https://github.com/uBlockOrigin/uAssets/assets/79064982/a35815e5-1850-4f03-8b0c-5f25c07e2270">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 133125
 cosmetic: 45969
 scriptlet: 19057
 html: 1768
listset (total-discarded, last-updated):
 default:
  user-filters: 7-1, never
  ublock-filters: 37632-109, now
  ublock-badware: 8250-0, now
  ublock-privacy: 797-5, now
  ublock-unbreak: 2308-2, now
  ublock-quick-fixes: 186-34, now
  easylist: 85966-171, now
  easyprivacy: 50769-61, now
  urlhaus-1: 11965-5, now
  plowe-0: 3739-1162, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 468 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 1
  gemius.pl: 1
  googletagmanager.com: 2
  rios.hu: 6
```
</details>

**Comment by ToIgnore** [comment]
enable ` hu: hufilter` regional filter

**Comment by xXRealXxx** [comment]
Thanks, hufilter worked!
