### ISSUE TITLE
9anime

### ISSUE THREAD

**Issue by scoutyongithub** [uBlockOrigin/uAssets#2333]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www4.9anime.is/watch/steinsgate-0-dub.l9zn/wzowmk.`

### Describe the issue

[anti ad block "please disable adblock to continue to use this site.]

### Versions

- Browser/version: [chrome canary/idk latest version atm]
- uBlock Origin version: [1.0.0.5.0]

### Settings

- [none pretty sure]

### Notes

[disabling javascript = cant load video]

**Comment by mapx-** [comment]
Did you update ublock filters ?
https://github.com/uBlockOrigin/uAssets/commit/5ab918d6cd5be5acda57cff82ad6113afbc35ff7

**Comment by zaphodbeebblebrox** [comment]
Anti-adblock is back again. Click on video to trigger.

**Comment by okiehsch** [comment]
This issue will remain open for now.

**Comment by dashbash5** [comment]
9anime.*##script:inject(setTimeout-defuser.js, return, 2000) isnt working and 9anime says to disable adblock to run service

**Comment by zaphodbeebblebrox** [comment]
Force an update of your filter lists and it works.

**Comment by uBlock-user** [comment]
> Force an update of your filter lists and it works.

They changed something again, doesn't work which is expected as they're keeping track of this issue tracker and swiftly firing back.

**Comment by okiehsch** [comment]
Works fine on my end.

**Comment by uBlock-user** [comment]
Not working here anymore, did you add a new filter or removed an existing one ?

**Comment by okiehsch** [comment]
If your filters are up to date and you use a default setup it works last filters added https://github.com/uBlockOrigin/uAssets/commit/c88dea10fd2d5e32343e56a0a58483738c8fb1f6

**Comment by uBlock-user** [comment]
It is updated, but not on the default setup, because I use numerous other filterlists which is fine, as, this filter `@@||trends.revcontent.com/serve.js.php$script,domain=9anime.is` won't do for me as I run a strict CSP policy and I don't whitelist any ad-servers. Nvm, will have to find another solution.

**Comment by charlie309** [comment]
I'm using Nano Adblocker v1.0.0.42. 
I'm using WaterFox 56.2.0 (64 bit)
URL Where this occurs is; 
https://www4.9anime.ru/watch/black-clover-dub.2y44/1wqpqw

I updated my filters and still not able watch the video!
 
Loading the page with the Nano filters active causes the video element to be replaced with an element containing the message:
"Please disable AdBlock then try again. If you want to watch anime in high quality without ads,just get a subscription in premium anime site. Thanks for your supporting!"

What to do???

**Comment by okiehsch** [comment]
Update your filters again, your example link works now with Chrome and Firefox on my end.

**Comment by charlie309** [comment]
Not working... Still getting the "Please disable AdBlock then try again. If you want to watch anime in high quality without ads,just get a subscription in premium anime site. Thanks for your supporting!"

**Comment by okiehsch** [comment]
It works with uBlock and Nano using Chrome or Firefox.
![unbenannt](https://user-images.githubusercontent.com/16838044/40400972-c7c236c6-5e44-11e8-880d-5c50ea3ab02c.JPG)

Probably a Waterfox issue.

**Comment by jspenguin2017** [comment]
I don't have a single rule left in Nano Filters for 9anime, stop blaming Nano please.

**Comment by xnieatx** [comment]
I think 9anime changed something again, anti-adblock message pops up. I am using latest uBlock + Nano and updated/purged filters.

**Comment by KiLL4FuNK** [comment]
![](https://i.imgur.com/611AuZJ.png)

**Comment by mapx-** [comment]
```
9anime.*#@#.rc-item-wrapper
9anime.is##.rc-bp-cta
9anime.is##.rc-bl-ads-by-revcontent
9anime.is##.rc-content
```

However, the top area is still clickable (but if hidden, then the detection is ON)

**Comment by zaphodbeebblebrox** [comment]
The site is broken again.

**Comment by okiehsch** [comment]
Well, the site changes inside a few hours, so adding new filters to a list that autoupdates every 4 days seems rather pointless.
Adding
````
9anime.*##.rc-item-wrapper:style(height: 1px !important)
9anime.*###sidebar > .text-center.crop.widget:style(height: 7px !important)
9anime.*#@#.rc-item-wrapper:style(visibility: collapse !important)
9anime.*#@##sidebar > .text-center.crop.widget:style(height: 6px !important)
@@||jsc.mgid.com^$script,domain=9anime.is
````
to your filter list should fix the issue.

**Comment by jspenguin2017** [comment]
> every 4 days 

Every 5 days.

**Comment by okiehsch** [comment]
! Title: uBlock filters
! Expires: 4 days
! Description: Filters optimized for uBlock, to be used along EasyList

**Comment by jspenguin2017** [comment]
When was that added? 
The other uBlock filters don't have the header yet, do you plan on adding them?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/74d3c608e81f51bea028f002b10f4c1f00f58f26

**Comment by lpchagnon** [comment]
Would you guys mind explaining a complete newbie why it still doesn't work for me while using nanoadblocker and defender while I purge my cache and then update filters?

**Comment by zaphodbeebblebrox** [comment]
You need to add the filters that okiehsch posted in the tab labeled My Filters in uBlock's settings.

**Comment by lpchagnon** [comment]
I tried that but it still doesn't work. Does the fact that I'm using nano adblocker and not ublock change something?

**Comment by okiehsch** [comment]
You use both uBO and Nano?
Just use one, does not matter which one, with a default setup add the filters to your My Filters tab and try again.

It works on my end.

**Comment by smed79** [comment]
« _That's what will happen when you're facing a cupide webmaster._ »

**Comment by lpchagnon** [comment]
No I mean I thought nano was an upgraded version of ublock. I only use nano adblocker and nano defender. And for some reason it's still not working for me. Does the fact that I'm on a Mac change something?

**Comment by KiLL4FuNK** [comment]
the filters of ublock origin should be updated every 24 hours

`uAssets/filters/filters.txt

 ! Title: uBlock filters 
 ! Expires: 4 days 
 ! Description: Filters optimized for uBlock, to be used along EasyList 
`

**Comment by okiehsch** [comment]
@lpchagnon "Does the fact that I'm on a Mac change something?"

That is certainly possible, I can't test a system running MacOS.
I can tell you that it works with Windows and Linux on my end.

**Comment by lpchagnon** [comment]
@okiehsch just to make sure I followed the right steps, I clicked on your 74d3c60 link, I clicked on "view", I selected and then copied the whole thing, and I pasted it in My filters. Am I missing something?

**Comment by okiehsch** [comment]
No, copy 
````
9anime.*##.rc-item-wrapper:style(height: 1px !important)
9anime.*###sidebar > .text-center.crop.widget:style(height: 7px !important)
9anime.*#@#.rc-item-wrapper:style(visibility: collapse !important)
9anime.*#@##sidebar > .text-center.crop.widget:style(height: 6px !important)
@@||jsc.mgid.com^$script,domain=9anime.is
````
and paste it in to My filters, then click `Apply changes`

**Comment by lpchagnon** [comment]
Oh ok, but still I just tried and it's not working so I guess it's cause I'm Mac?

**Comment by okiehsch** [comment]
Your guess is as good as mine.

**Comment by lpchagnon** [comment]
I see... well thanks anyway for introducing a newbie to the world of adblock filters!

**Comment by jspenguin2017** [comment]
With the filters it works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/40463686-d97fcaba-5ed3-11e8-8240-9038eeed388e.png)

**Comment by smed79** [comment]
@KiLL4FuNK 

> the filters of ublock origin should be updated every 24 hours

There is also a different expiration time between the **EasyList mirrors** used by uBo.

https://forums.lanik.us/viewtopic.php?f=23&t=40427
[https://github.com/gorhill/uBlock/pull/3690](https://git.io/vp9OP)

**Comment by okiehsch** [comment]
@smed79 I actually had to look up "cupide", my six-years of  french lessons at school were clearly not sufficient.

**Comment by jspenguin2017** [comment]
@smed79 There's a difference, for uBlock filters, they can be hosted on RawGit.

**Comment by lpchagnon** [comment]
@jspenguin2017 Are you on windows, osx or linux? and I just tried on my desktop with windows 10 and it works just fine. It's a damn shame if the problem really is osx.

**Comment by jspenguin2017** [comment]
@lpchagnon I only have access to a Windows 10 device and a Ubuntu 17.10 device. I tested it on Windows 10.

**Comment by lpchagnon** [comment]
So I guess the problem really is osx. Well not much I can do about it. Thanks for the help!

**Comment by osamayshak** [comment]
i'am an issue with 9anime, it can detect that i have an add block. i have tried everything i can. i have purged all the cashes in filters list and updated them but it didn't work. then i added all the filters for it but still it's not working. what should i do?

**Comment by uBlock-user** [comment]
^^
Find an alternative, this has now turned into a cat and mouse game. Not worth fighting over everyday.

**Comment by xnieatx** [comment]
I was having the same problem (of not working even with the filters added) so i reset to defaults on uBlock, then i added the filters from above. It works after

**Comment by osamayshak** [comment]
@xnieatx can you share a screen cap of the filters? i am new to all this so there could be something in the way added them or some thing. Here is a screen cap of my filters.
![my filters](https://user-images.githubusercontent.com/39579916/40492322-e917777a-5f78-11e8-9dc9-bdf3f86459ee.PNG)

**Comment by jspenguin2017** [comment]
@osamayshak It should be just like this: 
![image](https://user-images.githubusercontent.com/7283682/40492650-32785934-5f2e-11e8-887b-c3ea5bf11721.png)

Also make sure to update your filters.

**Comment by Asian-Rabbit** [comment]
Still having issue

**Comment by zaphodbeebblebrox** [comment]
Add the filters that okiehsch listed above to my Filters. They still work.

**Comment by Asian-Rabbit** [comment]
@zaphodbeebblebrox   still having the problem even with it and i had it back to default

**Comment by xnieatx** [comment]
@osamayshak everything on my ublock is default except adding the 5 line filters above. Nothing else added or removed (even without the Nano defender filters)
@Asian-Rabbit make sure to update filters, and add the 5 line filters above

**Comment by Asian-Rabbit** [comment]
@xnieatx Its still not working

**Comment by xnieatx** [comment]
@Asian-Rabbit Is uBlock (v1.16.6), Chrome, and Windows updated? Also try not using any other adblock extensions and anti-adblock killer scripts

**Comment by Asian-Rabbit** [comment]
@xnieatx  firefox quantum 60.0.1, window 10 home

**Comment by Asian-Rabbit** [comment]
I found a easier way to get 9anime to work. 
Just have everything default. 
Then add this in "my filter"

9anime.*##.rc-item-wrapper:style(height: 1px !important)
9anime.*###sidebar > .text-center.crop.widget:style(height: 7px !important)
9anime.*#@#.rc-item-wrapper:style(visibility: collapse !important)
9anime.*#@##sidebar > .text-center.crop.widget:style(height: 6px !important)
@@||jsc.mgid.com^$script,domain=9anime.is
www4.9anime.is##body > div:nth-of-type(8)
www4.9anime.is##body > div:nth-of-type(7)

Now with the filter above added go to setting to set your self as advance user. 
Make all Green meaning ur allowing all ads to pass through but with filter hiding it or removing it

**Comment by charlie309** [comment]
I have tried all of these ideas... Still can't play videos on 9Anime!

**Comment by charlie309** [comment]
I shut down all of my ad blockers and I still couldn't watch the videos.

**Comment by charlie309** [comment]
The only way I get even close to watching a video, is when I activate this filter.

https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js

Still searching for a way to bypass 9Anime though....

**Comment by Asian-Rabbit** [comment]
@charlie309 can you list steps then they may find a way to help you. 

Just have everything default. 
Then add this in "my filter"

9anime.*##.rc-item-wrapper:style(height: 1px !important)
9anime.*###sidebar > .text-center.crop.widget:style(height: 7px !important)
9anime.*#@#.rc-item-wrapper:style(visibility: collapse !important)
9anime.*#@##sidebar > .text-center.crop.widget:style(height: 6px !important)
@@||jsc.mgid.com^$script,domain=9anime.is
9anime.is##body > div:nth-of-type(6)
9anime.is##body > div:nth-of-type(8)
9anime.is##body > div:nth-of-type(7)

Now with the filter above added
go to setting to set your self as advance user. 
Make the box 2 box to the right of “all” box to Green meaning ur allowing all function to work.
But the filter will help remove some ads on screen

**Comment by Asian-Rabbit** [comment]
Can someone post filter that has all the ads hidden or removed and still work?

**Comment by uBlock-user** [comment]
Just update all built-in filters along with the filters posted here and it will work.

**Comment by Asian-Rabbit** [comment]
@okiehsch can you teach me or list all of the ads filter on 9anime?

**Comment by ghajini** [comment]
@uBlock-user 
i picked this filter from element picker `www4.9anime.is###body-container > .text-center.crop.widget`
and saw logger , logger doesn't show me filter details(click on that filter in logger)
![screenshot 19](https://user-images.githubusercontent.com/20338483/40589810-fa9217f8-6211-11e8-9ebf-3e9f085bf681.png)
instead a blank

**Comment by gwarser** [comment]
>logger doesn't show me filter details

https://github.com/gorhill/uBlock/issues/2179 ?

**Comment by ghajini** [comment]
@gorhill

**Comment by uBlock-user** [comment]
That will only happen if you remove the filter and click on the filter from the logger list because the filter no longer exists, it will fail and it will appear like that.

**Comment by uBlock-user** [comment]
@okiehsch ads are back, this time leveraging the whitelisted script `9anime.is/assets/min/frontend/all.js`

**Comment by mapx-** [comment]
`/9anime\.is\/[0-9a-zA-Z]{30,}/$domain=9anime.is,image`

**Comment by ghajini** [comment]
remove whitelists, no longer required
`||www5.9anime.is^$generichide,domain=www5.9anime.is,important`
`||www5.9anime.is/assets/min/frontend/all.js$script,domain=www5.9anime.is,important`
`||trends.revcontent.com^$script,domain=www5.9anime.is,important`

**Comment by Asian-Rabbit** [comment]
9anime.*##.rc-item-wrapper:style(height: 1px !important)
9anime.*###sidebar > .text-center.crop.widget:style(height: 7px !important)
9anime.*#@#.rc-item-wrapper:style(visibility: collapse !important)
9anime.*#@##sidebar > .text-center.crop.widget:style(height: 6px !important)
@@||jsc.mgid.com^$script,domain=9anime.is
doesnt block all ads.
is there any more filter i need to add?

**Comment by okiehsch** [comment]
> ads are back, this time leveraging the whitelisted script 9anime.is/assets/min/frontend/all.js

https://github.com/uBlockOrigin/uAssets/commit/039b3d282bfc33adcf8d73cb1909b4d4f8bac1a4

**Comment by osamayshak** [comment]
i have the same issue but also now the comment section is not loading or appearing at all

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c341a504bb63b1c5334ce4f7c9be3b69e3181070

**Comment by osamayshak** [comment]
@okiehsch thanks for the help, but the comment section is not appearing, it's not even loading. can you solve that issue as well? Please and thank you.

**Comment by okiehsch** [comment]
The comment section works fine on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/41039152-d631502a-6998-11e8-85c5-46eb25a0b19a.JPG)

**Comment by uBlock-user** [comment]
@okiehsch This time it's `tabunder`

**Comment by uBlock-user** [comment]
`9anime.*##script:inject(set-constant.js, Object.defineProperty, noopFunc)` breaks search and the recent anime slider.

**Comment by okiehsch** [comment]
Search works fine on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/41359780-8a6908b6-6f2b-11e8-9a27-e68eb0cb36fb.JPG)

**Comment by uBlock-user** [comment]
When I click on search, nothing happens and the cursor doesn't appear but if I add `9anime.*#@#script:inject(set-constant.js, Object.defineProperty, noopFunc)` it starts functioning normally. Your choice if you want to add it or not.

**Comment by osamayshak** [comment]
i have a new issue. when i click on an anime to watch, i cant watch because no matter what i click on the picture of the anime,
![capture](https://user-images.githubusercontent.com/39579916/41498330-45422b10-7173-11e8-8699-b7e319290cb9.PNG)
 it doesn't go away

**Comment by gorhill** [comment]
Please always provide the URL where you have the issue. I had to find it myself -- providing the URL saves time to volunteers: `https://www6.9anime.is/watch/my-hero-academia-3.l7yq/83jo2q`.

Works fine here on Chrome/Firefox, using uBO + default settings + up to date lists, no other extension.

**Comment by osamayshak** [comment]
i added `@@||9anime.is/assets/min/frontend/all.js` and it worked. thank you @uBlock-user

**Comment by gorhill** [comment]
That exception filter is already part of EasyList.

**Comment by osamayshak** [comment]
i'am having a new issue. when i click on an anime to watch i get the message "Server error, please refresh this page and try again". and that is on any anime i pick to watch not a specific one.

**Comment by artukrap** [comment]
https://www6.9anime.is/watch/cowboy-bebop-dub.l1n3/vyv106
https://i.imgur.com/bPe7rCd.jpg


There are ads on sides.

**Comment by mapx-** [comment]
before posting **update your lists**.

**Comment by dashbash5** [comment]
Server error, please refresh this page and try again is what i am seeing and i have updated my list also it isnt going away even after i refresh this page

**Comment by zaphodbeebblebrox** [comment]
Site works fine, try changing your video source.

**Comment by osamayshak** [comment]
i'am having a new issue. The website working fine, but The Rapid Video Media player is able to detect the add Blocker and refusing to work. i prefer to use it over the other mirror links because it works best for me. is there a possible fix for it?

**Comment by mapx-** [comment]
Did you update ublock filters ?

**Comment by osamayshak** [comment]
@mapx-  i just did and it worked. (-.-) never mind

**Comment by ghajini** [comment]
`https://www8.9anime.is/watch/one-piece.ov8/n019wm`
rapidvideo server not working here showing blank screen

**Comment by Asian-Rabbit** [comment]
9Anime:
![ublockorigin 9anime](https://user-images.githubusercontent.com/33164829/43050580-7f476028-8dd9-11e8-90ea-c689e24d0149.JPG)
Problem With Member Login And Video Wont Play.
This is My Settings:
![ublockorigin 1](https://user-images.githubusercontent.com/33164829/43050614-f5e811b4-8dd9-11e8-9818-68a9f14c0147.JPG)
![ublockorigin 2](https://user-images.githubusercontent.com/33164829/43050615-f5f5db3c-8dd9-11e8-88e6-6e201c2a6be6.JPG)
![ublockorigin 3](https://user-images.githubusercontent.com/33164829/43050616-f6016f06-8dd9-11e8-9d55-010dc8160a6a.JPG)
If Anyone Have A Custom Setting That Is For 9Anime Can I Have It Please. Thank You

**Comment by osamayshak** [comment]
there is this new thing that is happening on the site. RapidVideo is doing this annoying dump thing were it will let you watch 1 or 2 anime's in a hour and after that it will tell you that you have to buy a membership to be able to watch more anime's. Do you guys have a fix for it or should i just ditch RapidVideo forever?

**Comment by victorcarr59** [comment]
Remove my email address from your site
Thank you
Victor carr

--
Sent from Outlook Email App for Android

Monday, 23 July 2018, 07:53PM -03:00 from Osama Shaklab notifications@github.com<mailto:notifications@github.com>:


there is this new thing that is happening on the site. RapidVideo is doing this annoying dump thing were it will let you watch 1 or 2 anime's in a hour and after that it will tell you that you have to buy a membership to be able to watch more anime's. Do you guys have a fix for it or should i just ditch RapidVideo forever?

**Comment by Asian-Rabbit** [comment]
How do you get the request Code fixed? The image is always missing

**Comment by NoMod-Programming** [comment]
9Anime stopped working again. Any fix?

**Comment by okiehsch** [comment]
Update your `uBO-unbreak` list, should work after that.

**Comment by NoMod-Programming** [comment]
Awesome! It works, thanks!

**Comment by KiLL4FuNK** [comment]
`https://www1.9anime.to/watch/aikatsu-friends.jy04`


you can not see the video

**Comment by uBlock-user** [comment]
@KiLL4FuNK badfilter from easylist - `/^https?:\/\/([0-9a-z\-]+\.)?(9anime|animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime|gogoanime|igg-games|kimcartoon|memecenter|readcomiconline|toonget|toonova|watchcartoononline)\.[a-z]{2,4}\/(?!([Ss]cripts|[Uu]ploads|[Ii]mages|combined|content|cover|img|static|wp-content|wp-includes))(.*)/$first-party,script,badfilter`

**Comment by Asian-Rabbit** [comment]
![capture](https://user-images.githubusercontent.com/33164829/48156284-154d5d00-e29b-11e8-8c18-564d3716076c.PNG)
The image never shows

**Comment by uBlock-user** [comment]
Their CDN is down from the past two days, nothing to do anti adblock.

**Comment by Asian-Rabbit** [comment]
> 
> 
> Their CDN is down from the past two days, nothing to do anti adblock.

so do you know it will be fixed?

**Comment by uBlock-user** [comment]
@Asian-Rabbit https://www.reddit.com/r/9anime/comments/9uvhoj/the_site_is_taking_a_long_time_to_load_images/
