### ISSUE TITLE
live.bilibili.com: ads

### ISSUE THREAD

**Issue by mantoudayo** [uBlockOrigin/uAssets#23336]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://live.bilibili.com/24005080?broadcast_type=0&is_room_feed=1&spm_id_from=333.999.live_users_card.0.click&live_from=86001`

### Category

ads

### Description

广告残留
![7886c184db40c1f51cbf1922ce100ad9](https://github.com/uBlockOrigin/uAssets/assets/119979807/ea242e6f-053f-441f-bce3-a52bc8b6e3f9)

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 147952
 cosmetic: 56631
 scriptlet: 20623
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 36-23, never
  CHN-0: 25703-141, now
  easylist: 85966-580, 14m Δ
  easyprivacy: 50769-812, 14m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8248-0, 14m Δ
  ublock-filters: 37506-322, 14m Δ
  ublock-privacy: 800-0, 14m Δ
  ublock-quick-fixes: 260-1, 14m Δ
  ublock-unbreak: 2251-2, 14m Δ
  urlhaus-1: 11965-5, 1h.27m
filterset (user): [array of 36 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 389 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 41
 network:
  bilibili.com: 38
  hdslb.com: 3
 extended:
  ##+js(nowebrtc)
```
</details>

**Comment by mapx-** [comment]
maybe 
`live.bilibili.com##[data-type="liveroom_banner_show"]:upward(4)`

@cjx82630

**Comment by cjx82630** [comment]
It's self-promotion.
