### ISSUE TITLE
imleagues.com: detection

### ISSUE THREAD

**Issue by djwoodie12** [uBlockOrigin/uAssets#23337]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.imleagues.com/spa/division/db79a0593bd24f9c8f5d6dcc014a38aa/home`

### Category

detection

### Description

It detects the adblock and makes you pay to remove them

### Other extensions used

grammarly, honey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="956" alt="adblock" src="https://github.com/uBlockOrigin/uAssets/assets/167347362/007e9027-ee92-4151-ac69-5c82e151ef9a">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 133134
 cosmetic: 45945
 scriptlet: 20427
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37465-295, 1m
  ublock-badware: 8238-0, 1m
  ublock-privacy: 796-0, 1m
  ublock-unbreak: 2248-2, 1m
  ublock-quick-fixes: 140-0, 1m
  easylist: 85966-556, 1m
  easyprivacy: 50769-812, 2m
  urlhaus-1: 11965-5, 2m
  plowe-0: 3739-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1292 ms
 maxAssetCacheWait: 14 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  adroll.com: 1
  facebook.net: 1
  googletagmanager.com: 2
  intergient.com: 1
  liadm.com: 1
  proper.io: 1
  quantserve.com: 1
  scorecardresearch.com: 1
 extended:
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
```
</details>

**Comment by mapx-** [comment]
in order to be able to investigate your issue we need an account and the steps to reproduce the issue.
Are you willing to provide your account credentials ? (I'll provide an email address if you agree)
