### ISSUE TITLE
tiktok.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#23348]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tiktok.com/foryou`

### Category

ads

### Description

ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/54b64031-8156-46d7-a25f-d461d873392e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 143256
 cosmetic: 161271
 scriptlet: 34191
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8066-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 203-0, now
  adguard-cookies: 29270-74, now
  adguard-other-annoyances: 14147-345, now
  adguard-popup-overlays: 27127-388, now
  easylist-annoyances: 4496-17, now
  easylist-notifications: 2989-82, now
  fanboy-cookiemonster: 50912-3916, now
  ublock-annoyances: 6941-1107, 25m Δ
  ublock-cookies-adguard: 1078-0, now
  ublock-cookies-easylist: 1078-1078, now
 default:
  user-filters: 49-0, never
  easylist: 86034-538, 25m Δ
  easyprivacy: 50785-914, 25m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8279-1, 25m Δ
  ublock-filters: 37465-802, 25m Δ
  ublock-privacy: 816-1, 25m Δ
  ublock-quick-fixes: 309-2, 25m Δ
  ublock-unbreak: 2251-4, 25m Δ
  urlhaus-1: 12105-0, now
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 42 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 896 ms (selfie)
 maxAssetCacheWait: 187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  tiktok.com: 3
  tiktokv.com: 16
 extended:
  ##[aria-label="Scroll to the top"]
  ##tiktok-cookie-banner
  ##.css-bu8whx-DivBannerContainer
  ##+js(addEventListener-defuser, contextmenu, preventDefault)
  ##+js(set-session-storage-item, webapp_first_open_cta, 1)
  ##+js(addEventListener-defuser, keydown)
  ##+js(addEventListener-defuser, touchmove, .preventDefault():voi…
```
</details>

**Comment by D4niloMR** [comment]
@3xploiton3 Can you still reproduce ads on TikTok? If yes, please test:

```adb
www.tiktok.com##+js(json-prune-fetch-response, itemList.[-].ad_info.ad_id, , propsToMatch, url:/api/recommend/item_list/)
```

**Comment by D4niloMR** [comment]
I can reproduce with an account + Indonesian IP.
