### ISSUE TITLE
reading.amplify.com: breakage

### ISSUE THREAD

**Issue by wr0driguez** [uBlockOrigin/uAssets#23341]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://reading.amplify.com/la/24d5825e59/index.html`

### Category

breakage

### Description

ublock is preventing this page from loading for student users. i have been asked to submit this report by a collegue.

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 133184
 cosmetic: 46074
 scriptlet: 20442
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 85986-554, 1h.46m Δ
  easyprivacy: 50770-812, 1h.46m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8248-5, 1h.46m Δ
  ublock-filters: 37508-303, 1h.46m Δ
  ublock-privacy: 800-0, 1h.46m Δ
  ublock-quick-fixes: 260-1, 1h.46m Δ
  ublock-unbreak: 2251-2, 1h.46m Δ
  urlhaus-1: 11965-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 976 ms
 maxAssetCacheWait: 197 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  datadoghq-browser-agent.com: 1
  google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
We need an account in order to investigate the issue, are you willing to share the account credentials ? (I'll provide an email address if you agree)
