### ISSUE TITLE
drakescans.com: detection

### ISSUE THREAD

**Issue by 0Sniffle0** [uBlockOrigin/uAssets#23344]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://drakescans.com/`

### Category

detection

### Description

Website used to only detect the adblocker. Now they have added a adblocker that locks out any content on the website if uBO is on.

### Other extensions used

![image_2024-04-18_103549790](https://github.com/uBlockOrigin/uAssets/assets/42299987/6737f7f1-6842-408d-8cd1-e577c4e51728)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image_2024-04-18_103740400](https://github.com/uBlockOrigin/uAssets/assets/42299987/b2652afd-c02d-49ef-b056-8f83bf9d9c87)

![image_2024-04-18_103807738](https://github.com/uBlockOrigin/uAssets/assets/42299987/02dec4d4-f8d4-4f2f-8569-1469b5433d6c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 121
filterset (summary):
 network: 151159
 cosmetic: 86125
 scriptlet: 37665
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80710-5448, now
 default:
  user-filters: 31-6, never
  easylist: 85966-554, 1h.29m Δ
  easyprivacy: 50769-794, 1h.29m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8248-0, 29m Δ
  ublock-filters: 37506-303, 1h.29m Δ
  ublock-privacy: 800-0, 29m Δ
  ublock-quick-fixes: 260-1, 1h.29m Δ
  ublock-unbreak: 2251-20, 29m Δ
  urlhaus-1: 12105-0, now
filterset (user): [array of 31 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 85031 ms (selfie)
 maxAssetCacheWait: 6043 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  bidgear.com: 1
  googlesyndication.com: 3
  wp.com: 1
 extended:
  ##div:nth-of-type(4)
  ##body > div[class][style="display:none;"] + div[id][class*=" "]
  ##ins.adsbygoogle[data-ad-slot]
  ###teaser3
  ##+js(remove-node-text, script, onerror)
  ##+js(noeval-if, ads)
  ##+js(noeval-if, /fairAdblock|chp_?adblock|adsbygoogle\.js/)
```
</details>

**Comment by mapx-** [comment]
update your browser, reset uBO to defaults and do not use any other blocking stuff => test again
