### ISSUE TITLE
live24.gr: ads

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#23347]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://live24.gr/radio/generic.jsp?sid=1334`

### Category

ads

### Description

Ad banner. Also, on Android it periodically plays sound ads in English intrusively when starting and/or during web radio playback.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/101707608/5de5f5b0-f0af-406f-ac46-d74969465376)

![2](https://github.com/uBlockOrigin/uAssets/assets/101707608/643dee36-51cd-4930-aa48-75fa1dd3db18)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 355961
 cosmetic: 253849
 scriptlet: 50310
 html: 2026
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 66576-0, 2m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 91426-1245, 23m
  https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt: 918-11, 2m
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 368-0, 2m
  adguard-generic: 80863-4705, 2m
  adguard-mobile: 9257-844, 2m
  adguard-spyware-url: 1494-235, 2m
  adguard-spyware: 87899-4901, 2m
  block-lan: 61-0, 2m
  curben-phishing: 14155-7, 23m
  adguard-cookies: 29270-45, 2m
  fanboy-cookiemonster: 50912-3863, 2m
  [13 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37617-198, 24m Δ
  ublock-badware: 8281-416, 24m Δ
  ublock-privacy: 813-66, 24m Δ
  ublock-unbreak: 2308-3, 24m Δ
  ublock-quick-fixes: 235-34, 24m Δ
  easylist: 86034-41148, 24m Δ
  easyprivacy: 50785-29099, 24m Δ
  urlhaus-1: 12105-0, 23m
  plowe-0: 3739-2033, 2m
  GRC-0: 1077-16, 2m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user- https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1
supportStats:
 allReadyAfter: 22324 ms
 maxAssetCacheWait: 7431 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  live24.gr: 4
  addthis.com: 1
  adswizz.com: 3
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 1
  google.gr: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  pghub.io: 2
  sharethis.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###socialbar
  ##.sharethis-inline-share-buttons
  ##.cookieBar:not(body):not(html)
  ##div.cookieBar
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
`live24.gr##.banner`

did you report it at greek list repo ?
https://github.com/kargig/greek-adblockplus-filter/issues

**Comment by DimitrisKalaboukas** [comment]
@mapx- Not yet, but I’ll do so if necessary. Were you able to reproduce audio ads on Android?

**Comment by mapx-** [comment]
I tried only in android emulation, no audio on my side, maybe it requires (native) greek ip

**Comment by DimitrisKalaboukas** [comment]
@ToIgnore Yes, I’m sure. The site does it in all web radios, always in English and only on Android, where “live24.gr##.banner” rule doesn’t block the ad banner either.

**Comment by mapx-** [comment]
maybe

`live24.gr##.bannerContent`
