### ISSUE TITLE
japscan.lol: ads

### ISSUE THREAD

**Issue by gorillaze05** [uBlockOrigin/uAssets#23356]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.japscan.lol/lecture-en-ligne/gintama/volume-2/3.html`

### Category

ads

### Description

Ads came back on the top of the page after being addressed by uBlock since then.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 150963
 cosmetic: 52743
 scriptlet: 20619
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_16_French/filter.txt: 24380-306, now
  FRA-0: 24369-24258, now
 default:
  user-filters: 0-0, never
  easylist: 86043-659, now
  easyprivacy: 50785-794, 2m Δ
  plowe-0: 3739-0, now
  ublock-badware: 8277-0, 1m
  ublock-filters: 37528-375, 1m
  ublock-privacy: 816-0, 1m
  ublock-quick-fixes: 312-1, 1m
  ublock-unbreak: 2251-24, 1m Δ
  urlhaus-1: 12460-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 810 ms (selfie)
 maxAssetCacheWait: 400 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  japscan.lol: 4
  googletagmanager.com: 1
 extended:
  ##.blur-background
  ##.notice-message
  ##+js(no-setTimeout-if, detectImgLoad)
  ##+js(abort-current-script, document.addEventListener, /getCompu…
  ##+js(no-window-open-if)
```
</details>

**Comment by gorillaze05** [comment]
<img width="886" alt="japscan" src="https://github.com/uBlockOrigin/uAssets/assets/158492919/8a073c0f-069e-4cf1-bfbb-1cc29a761cb5">
Can't you see this ad ? I updated the French regional filter and it is still not working.
Thanks for your help

**Comment by ToIgnore** [comment]
@Yuki2718 
```adblock
japscan.lol##[href*="japscan.lol"][href*="?timstamp"]
```

**Comment by Yuki2718** [comment]
It says the page doesn't exist. Anyway pls take a look @smed79

**Comment by dportvine** [comment]
After clicking, it redirects to `https://trynectar.ai/`.

**Comment by Camilleri-Nathan** [comment]
any news about one fix ?

**Comment by mapx-** [comment]
```
japscan.lol###dlinkc
japscan.lol##div.container > [href]
```
