### ISSUE TITLE
pillowcase.su: popups

### ISSUE THREAD

**Issue by uniformization** [uBlockOrigin/uAssets#23358]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://pillowcase.su/f/c299dcfa253092d1357aa9005334a2eb
```

### Description

The page looks through the following URLs and finds one that works:

```
https://www.intelligenceadx.com/pjsnes.min.css
https://d2klx87bgzngce.cloudfront.net/fIR/aprint.js
https://www.rtxetintkraht.com/yjsnes.min.css
https://www.zsanjnpl.com/sUGXlt/qprint.js
```

If successful, it does something to open a popup.

### Other extensions used

Stylus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![KSXdfTKFiE](https://github.com/uBlockOrigin/uAssets/assets/124226059/c5600a9c-a515-4ac4-8772-0331e7b1a468)

![image](https://github.com/uBlockOrigin/uAssets/assets/124226059/45fe866c-ee1f-4738-8141-18f30eec0a05)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 133405
 cosmetic: 46070
 scriptlet: 19093
 html: 1769
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 37681-109, 2h.45m Δ
  ublock-badware: 8279-0, 2h.45m Δ
  ublock-privacy: 813-1, 2h.45m Δ
  ublock-unbreak: 2308-2, 2h.45m Δ
  easylist: 86077-172, 2h.45m Δ
  easyprivacy: 50787-61, 2h.45m Δ
  urlhaus-1: 12105-0, 20h.6m
  plowe-0: 3739-1162, 4d.21h.27m
  ublock-quick-fixes: 238-33, 2h.45m Δ
filterset (user): [array of 1051 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 132 ms (selfie)
 maxAssetCacheWait: 48 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  adsco.re: 1
  d2klx87bgzngce.cloudfront.net: 1
  intelligenceadx.com: 1
  rtxetintkraht.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 Looks like `https://www.rtxetintkraht.com/tpJOO/rprint.js` slips through

Is changing to `(?:[-.]min)?` a good idea?

```adb
/^https:\/\/www\.[a-z]{8,16}\.com\/(?:[A-Za-z]+\/)*(?:[_0-9A-Za-z]{1,20}[-.])*[_0-9A-Za-z]{1,20}(?:[-.]min)?\.js$/$script,3p,match-case,to=com,header=link:/adsco\.re\/>;rel=preconnect/
```

I'm not sure if `min` is tokenized in the current filter?
