### ISSUE TITLE
nzbstars.com anti-adblock

### ISSUE THREAD

**Issue by alitinko** [uBlockOrigin/uAssets#2335]
### URL(s) where the issue occurs

`www.nzbstars.com`

### Describe the issue

Anti ad-block.

### Screenshot(s)

`https://screenshots.firefox.com/KnkPVzgcYv69i18T/www.nzbstars.com`

### Versions

- Browser/version: Firefox Developer - 61.0b3
- uBlock Origin version:  v1.16.6

### Settings

- Default settings

### Notes

This just started today on nzbstars.com

**Comment by gwarser** [comment]
https://old.reddit.com/r/firefox/comments/9w4f98/anti_adblock_not_working/

**Comment by nicolaasjan** [comment]
Stopped working... 🙁

**Comment by nicolaasjan** [comment]
`nzbstars.com##+js(acs, document.getElementById, adblocker)`
?
