### ISSUE TITLE
taleemcity.com: detection

### ISSUE THREAD

**Issue by zain4752** [uBlockOrigin/uAssets#23352]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://taleemcity.com/2nd-year-math-notes-of-all-chapters-fsc-part-2-solutions/`

### Category

detection

### Description

after a few seconds it repeatedly asks me to turn off the ad blocker 
i close the dialog box and it reappears after a few seconds 
it is very irritating please resolve this issue as soon as possible.
All in all you are providing a great service . Thanks

### Other extensions used

Rememberry
savefrom.net helper
mediaharvest

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/167464300/017cc547-169a-4fe3-9d5d-8829780361ee)
![image_2024-04-18_225538562](https://github.com/uBlockOrigin/uAssets/assets/167464300/1c76e12a-0fcc-4988-955d-a128710ff9d5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 122
filterset (summary):
 network: 133768
 cosmetic: 46140
 scriptlet: 20473
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86038-555, 59m Δ
  easyprivacy: 50785-813, 59m Δ
  plowe-0: 3758-0, 8d.21h.3m
  ublock-badware: 8277-0, 59m Δ
  ublock-filters: 37526-303, 59m Δ
  ublock-privacy: 816-0, 59m Δ
  ublock-quick-fixes: 312-1, 59m Δ
  ublock-unbreak: 2251-20, 59m Δ
  urlhaus-1: 12460-0, 1h.59m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2705 ms (selfie)
 maxAssetCacheWait: 378 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
```
</details>

**Comment by mapx-** [comment]
@zain4752 is this page the result of some shortener link ?

**Comment by zain4752** [comment]
> @zain4752 is this page the result of some shortener link ?

i could not understand .... what do you mean by shorter link?
i just open the website and it repeatedly asks me to turn of my adblocker

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by zain4752** [comment]
> * clear cookies / localStorage/ cache for the tested page
> * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> * disable any custom filter for that site
> * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> * are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
> * restart the system, reopen the browser, test again.

![image](https://github.com/uBlockOrigin/uAssets/assets/167464300/0abe6938-688f-4ccb-95d0-19da6b04dbcb)
the issue is still not solved
