### ISSUE TITLE
automobile-catalog.com: ads

### ISSUE THREAD

**Issue by ANTS-621** [uBlockOrigin/uAssets#23354]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.automobile-catalog.com/car/1993/2047055/lada_aleko_diesel.html`

### Category

ads

### Description

Still shows ads, detects that I'm using an ad blocker.

### Other extensions used

Dark Mode

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 150855
 cosmetic: 52739
 scriptlet: 20614
 html: 0
listset (total-discarded, last-updated):
 added:
  FRA-0: 24368-381, 21m
 default:
  user-filters: 6-3, never
  easylist: 86045-659, 21m
  easyprivacy: 50785-812, 21m
  plowe-0: 3739-0, 21m
  ublock-badware: 8277-0, 21m
  ublock-filters: 37527-303, 21m
  ublock-privacy: 816-0, 21m
  ublock-quick-fixes: 312-3, 58m Δ
  ublock-unbreak: 2251-0, 21m
  urlhaus-1: 12460-0, 21m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2331 ms
 maxAssetCacheWait: 466 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  criteo.net: 3
  doubleclick.net: 1
  google.com: 7
  googlesyndication.com: 4
  googletagmanager.com: 1
  pub.network: 2
 extended:
  ##table[height="90"]
  ##table[width="300"]
  ##[data-freestar-ad]:not(:empty)
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(noeval-if, /07c225f3\.online|content-loader\.com|css-load\…
  ##+js(remove-node-text, script, KCgpPT57bGV0IGU)
```
</details>

**Comment by JobcenterTycoon** [comment]
@uBlock-user when you removing the inline script the Ad-Shield script need to be blocked with a extra filter because `||html-load.com^$redirect=noopjs,domain=` only getting applied to chrome (firefox using HTML filter).

The section starts with `||html-load.com^$script,xhr,domain=`

**Comment by f4dh2bvcs2-cyber** [comment]
This site has recently started showing ads again, including a clickable panel on the bottom which takes up some space.

**Comment by gothic-bum** [comment]
@f4dh2bvcs2-cyber 

I just tested using Firefox and uBO with default settings and I didn't see any ads.

Try testing again using a new browser profile with only uBO and its default settings.

**Comment by f4dh2bvcs2-cyber** [comment]
Sorry, I should have mentioned this is Safari. I just checked again with a  UboL extension reset. Still ads.

<details>

```yml
name: uBlock Origin Lite
version: 2026.729.1529
browser: Safari 26.6 (mac)
filtering:
 default: optimal
permission: all
rules: 118303
rulesets:
 easylist
 easyprivacy
 ublock-filters
scripting:
 css-specific
 ublock-filters.isolated
 ublock-filters.main
 easyprivacy.main
 easyprivacy.isolated
 prevent-popup
```

</details>

**Comment by stephenhawk8054** [comment]
You need to wait until next uBOL version update.
