### ISSUE TITLE
nxp.com: breakage

### ISSUE THREAD

**Issue by mvduin** [uBlockOrigin/uAssets#23351]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nxp.com/webapp/secure/technicalupdates/documentUpdates.sp`

### Category

breakage

### Description

EasyPrivacy has a broad pattern match rule for `/webanalytics.$from=~webanalytics.italia.it` which blocks the website from loading the script file https://www.nxp.com/resources/scripts/analytics/webanalytics.js but doing so breaks parts of the website because they try to call utility functions defined in this file such as `getCleanPageURL()`.

For example the linked page (free account required) fails to load the list of document updates (and also spams the javascript console full of errors). Adding a manual exception for this script file fixed the problem.

### Other extensions used

none relevant

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 133880
 cosmetic: 46147
 scriptlet: 20474
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 114-0, never
  easylist: 86043-43, now
  easyprivacy: 50785-13, now
  plowe-0: 3739-1162, now
  ublock-badware: 8277-16, now
  ublock-filters: 37528-369, now
  ublock-privacy: 816-5, now
  ublock-quick-fixes: 312-32, now
  ublock-unbreak: 2251-34, now
  urlhaus-1: 12460-0, now
filterset (user): [array of 114 redacted]
trustedset:
 added: [array of 18 redacted]
 removed:
  chrome-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 411 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  nxp.com: 1
  go-mpulse.net: 1
```
</details>

**Comment by ToIgnore** [comment]
@ryanbr 
`@@||nxp.com/resources/scripts/analytics/webanalytics.js$~third-party`
