### ISSUE TITLE
reviewmeta.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#23368]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://reviewmeta.com/amazon/B07X9J57ZY?tag=reviewmeta0b-20?utm_source=extension`

### Category

breakage

### Description

Buttons labeled " See 94 product variations" or "Check Product Title History" don't work when uBlock origin is enabled. 

### Other extensions used

FastFoward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 179675
 cosmetic: 229388
 scriptlet: 51222
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78174-6548, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98290-17283, now
  adguard-generic: 80922-5566, now
  adguard-mobile: 9260-11, now
  adguard-spyware-url: 1494-5, now
  block-lan: 61-0, now
  curben-phishing: 14271-0, now
  fanboy-cookiemonster: 50929-50929, now
  ublock-annoyances: 6942-27, now
 default:
  user-filters: 1-0, never
  easylist: 86127-534, now
  easyprivacy: 50791-10, now
  plowe-0: 3735-871, now
  ublock-badware: 8303-2, now
  ublock-filters: 37562-434, now
  ublock-privacy: 832-116, now
  ublock-quick-fixes: 324-5, now
  ublock-unbreak: 2253-24, now
  urlhaus-1: 12505-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1207 ms (selfie)
 maxAssetCacheWait: 220 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  youtube.com: 2
 extended:
  ##.modal
  ##.modal-backdrop
  ##span[class^="ad_"]
  ###mc_embed_signup
  ###mc_embed_signup_scroll
  ##.newsletter-input
  ##.newsletter-btn
  ##+js(no-setTimeout-if, innerHTML)
  ##+js(no-setTimeout-if, adsbygoogle)
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune-fetch-response, overlay, overlay.shortsAdsRende…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by ToIgnore** [comment]
caused by aspect-ratio

**Comment by mapx-** [comment]
@jimmysofat6864 

add

`reviewmeta.com#@#.modal`

@ryanbr
