### ISSUE TITLE
sports.iqiyi.com: breakage

### ISSUE THREAD

**Issue by Fliny** [uBlockOrigin/uAssets#23364]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sports.iqiyi.com/resource/pcw/play/1ktpscfmmcs`

### Category

breakage

### Description

if ublock is active, it just keeps showing the logo in the screen, and the video won't display.
if I turn off ublock, then ad shows up, after that the video could play normally.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1424" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/23095596/f0051e08-5bfb-4efe-a2ca-959565561f2b">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 123
filterset (summary):
 network: 154017
 cosmetic: 160758
 scriptlet: 26667
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29267-49, 1m
  adguard-social: 22825-741, 1m
  fanboy-cookiemonster: 50919-3862, now
  fanboy-social: 15888-30, 3m
  fanboy-thirdparty_social: 68-0, 3m
  ublock-cookies-adguard: 1079-1, 3m
  ublock-cookies-easylist: 1079-1079, 4m
 default:
  user-filters: 9-1, never
  CHN-0: 25743-141, 10m
  easylist: 86090-586, 1h.16m Δ
  easyprivacy: 50791-814, 1h.16m Δ
  plowe-0: 3735-0, 10m
  ublock-badware: 8298-0, 1h.16m Δ
  ublock-filters: 37550-331, 1h.16m Δ
  ublock-privacy: 816-1, 1h.16m Δ
  ublock-quick-fixes: 318-1, 1h.16m Δ
  ublock-unbreak: 2252-2, 1h.16m Δ
  urlhaus-1: 12505-0, 10m
filterset (user): [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 271 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  iqiyi.com: 1
  qy.net: 13
 extended:
  ##+js(set-constant, Object.prototype.parseXML, noopFunc)
  ##+js(set-constant, Object.prototype.blackscreenDuration, 1)
  ##+js(set-constant, QiyiPlayerProphetData.a.data, {})
```
</details>

**Comment by mapx-** [comment]
@cjx82630 could you take a look ? needing chinese ip

**Comment by cjx82630** [comment]
I can't reproduce this issue. The preroll ads are not being blocked. I added a rule to block them https://github.com/easylist/easylistchina/commit/d591aac90f27f8ed380ecf15816a1d336c136d57 Blackscreen for 1 second , the video will begin.

**Comment by mapx-** [comment]
@Fliny reset uBO to defaults, do not use any other blocking stuff, test again

**Comment by Fliny** [comment]
> @Fliny reset uBO to defaults, do not use any other blocking stuff, test again

it worked, ads are blocked properly, and the video can be shown.
thanks very much
