### ISSUE TITLE
reuters.com: breakage

### ISSUE THREAD

**Issue by vikingnope** [uBlockOrigin/uAssets#23365]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
reuters.com
```

### Description

Text overriding other text, with uBlock Origin turned on

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlock ON:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/7b56721f-6172-456c-a72a-53d5049301c3)

With uBlock OFF:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/decd72fe-4ea6-43f8-a890-1b6d4d52b023)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 134161
 cosmetic: 46076
 scriptlet: 19095
 html: 1769
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37683-109, 2h.47m Δ
  ublock-badware: 8300-0, 2h.47m Δ
  ublock-privacy: 813-1, 2h.47m Δ
  ublock-unbreak: 2308-2, 2h.47m Δ
  ublock-quick-fixes: 238-33, 2h.47m Δ
  easylist: 86089-172, 2h.47m Δ
  easyprivacy: 50791-61, 2h.47m Δ
  urlhaus-1: 12830-0, 7h.18m
  plowe-0: 3739-1162, 1d.8h
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 178 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
I can only reproduce this when resizing the window to smaller

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/60c11280-2522-4415-936f-dcb8402067bb)

Can you test this filter?

```adb
reuters.com##ul[class^="cluster__stories"] > li[class^="cluster__cluster-basic"][class*="cluster__column-left"]:style(margin-left: 17.0418006431vw !important;)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by stephenhawk8054** [comment]
Hmm... I can't reproduce it, whatever screen resizing I tried.

**Comment by vikingnope** [comment]
It seems to depend on how big the sub text is of the main story:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/89e67bda-e949-439a-8d05-8e90d5cf7ff8)


Currently the sub text is small, but in the previous screenshot it was much bigger

**Comment by vikingnope** [comment]
This morning it is the same again: 

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/c186a311-e03d-483d-949c-2495645ee247)

**Comment by vikingnope** [comment]
@stephenhawk8054 This morning it is the same again: 

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/c186a311-e03d-483d-949c-2495645ee247)

**Comment by stephenhawk8054** [comment]
Can you test this?

```adb
reuters.com##ul[class^="cluster__stories"] > li[class^="cluster__cluster-hub"][class*="cluster__column-middle"][class*="cluster__break-after"]:style(margin-bottom: 100px !important;)
```

**Comment by vikingnope** [comment]
That works great, thanks a lot:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/5a2bce05-e5ac-4f29-b413-181b5dc95694)

**Comment by vikingnope** [comment]
@stephenhawk8054 sorry to bother again, but I also noticed that on laptops there is an issue where you can scroll sideways due to there being an image as in the screenshot.  Maybe the image can be removed like the rest of the title bars?

 
<img width="752" alt="Screenshot 2024-04-28 at 16 18 36" src="https://github.com/uBlockOrigin/uAssets/assets/81376423/c80074ba-cc08-4074-8e5e-084265f4bb07">

**Comment by stephenhawk8054** [comment]
The site looks like that even when turning off uBO. The site is not coded well to be suitable for different screen sizes and uBO can't do much to fix them. Adding more filters will just create more chances of unexpected breakages somewhere.

**Comment by vikingnope** [comment]
Ah ok, no problem
