### ISSUE TITLE
peacocktv.com: breakage

### ISSUE THREAD

**Issue by flossiesmitty** [uBlockOrigin/uAssets#23367]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.peacocktv.com/watch/playback/vod/GMO_00000000475817_01/07e2018c-b1fd-3d63-b35e-1c9fb9831f45`

### Category

breakage

### Description

I am trying to watch the program "Days of our Lives" and when I was watching it yesterday it just went off - I tried to watch it today and nothing comes on - this is the first problem I have had with this program

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 133868
 cosmetic: 46189
 scriptlet: 20480
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86090-440, 1h.4m Δ
  easyprivacy: 50791-790, 1h.4m Δ
  plowe-0: 3735-0, now
  ublock-badware: 8298-0, 1h.4m Δ
  ublock-filters: 37550-369, 1h.4m Δ
  ublock-privacy: 816-5, 1h.4m Δ
  ublock-quick-fixes: 318-31, 1h.4m Δ
  ublock-unbreak: 2252-34, 1h.4m Δ
  urlhaus-1: 12505-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 305 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  demdex.net: 1
  freewheel.tv: 1
  mparticle.com: 2
  newrelic.com: 2
  nr-data.net: 7
 extended:
  ##.adsbox:remove()
```
</details>

**Comment by flossiesmitty** [comment]
I am not able to watch my show "days of our lives" - nothing comes on - the screen is black

**Comment by ToIgnore** [comment]
Hi @flossiesmitty. Would you be willing to give a team member temporary access to your account?

**Comment by flossiesmitty** [comment]
Yes I can give temporary access to my account - please try to resolve this problem. Thank you.    On Friday, April 19, 2024 at 02:49:27 PM EDT, ToIgnore ***@***.***> wrote:  
 
 


Hi, @flossiesmitty! Would you be willing to give a team member temporary access to your account?

**Comment by mapx-** [comment]
@ItsProfessional @liamengland1 could you take a look (vpn does not work on my side) ?

**Comment by ItsProfessional** [comment]
Doesn't work for me either.

**Comment by mapx-** [comment]
I tried 
`https://www.peacocktv.com/watch/playback/vod/GMO_00000000106370_01/776fe85a-d849-3469-9ebe-9894934ea49d?paused=true`

I get a "disable your adblocker", click dismiss and I'm able to watch it

**Comment by mapx-** [comment]
if it's about specific shows (like "days of our lives") maybe I need your account to test it, send your account credentials here: `axis.trivia@gmail.com`
