### ISSUE TITLE
tickertape.in | Ads from vmax

### ISSUE THREAD

**Issue by matter-it-does** [uBlockOrigin/uAssets#23369]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.tickertape.in/mutualfunds/hdfc-liquid-fund-M_HDCLI?chartScope=max
```

### Description

Ads visible from `vmax.com`. See screenshot below.
See ublock logger output below.

```
01:38:38​​​www.google.com​3,3​get​script​https://www.gstatic.com/recaptcha/releases/rz4DvU-cY2JYCwHSTck0_qm-/recaptcha__en.js
01:38:38​​​www.tickertape.in​3​get​xhr​https://firebase.googleapis.com/v1alpha/projects/-/apps/1:483613240967:web:cb7e3b9d6e186f32d51222/webConfig
01:38:38​​​www.tickertape.in​3​get​frame​https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6LfOYXUnAAAAAGSzHVt2ZqEWMGJLSUnIPhqAxKCh&co=aHR0cHM6Ly93d3cudGlja2VydGFwZS5pbjo0NDM.&hl=en&v=rz4DvU-cY2JYCwHSTck0_qm-&size=invisible&cb=vtqv4jgb3bgd
01:38:37​​​www.tickertape.in​3​get​script​https://www.gstatic.com/recaptcha/releases/rz4DvU-cY2JYCwHSTck0_qm-/recaptcha__en.js
01:38:37​​​www.tickertape.in​3​get​script​https://www.google.com/recaptcha/enterprise.js?render=6LfOYXUnAAAAAGSzHVt2ZqEWMGJLSUnIPhqAxKCh
01:38:36​​​www.tickertape.in​3​get​script​https://gateway.smallcase.com/scdk/2.0.0/scdk.js
01:38:35​https://www.tickertape.in/mutualfunds/hdfc-liquid-fund-M_HDCLI?chartScope=max​​​​​​
01:40:21​​​github.com​0,3​get​script​https://github.githubassets.com/assets/socket-worker-9cc1149b224c.js
01:38:46​​​www.tickertape.in​3​get​image​https://ts.vmax.com/i?p=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0.LwUgybMldDcDgpoVu_sU36O9xhA2wCT0YZ7XdsJNWhUehZQOzxjeVA.6BzEytNv6fTfmAhwG4u-9Q.9rUdjX7m1sbIYhhV8kIjhr2c_CVdT2GW7nP7SGADiwkw2Hi07IOFT4TBRTrDgPDhqysO99HgdmArw9Zat5oqxDjAj7gARQPIWGFX1eIQwgQkkiXcouo4MIMWnVjpZnlTJnCIN3AUozoeRqm6ThvgRU2yj1BaMf2vVgnOVmL-l7Rgaw6QO7oSzBqETaSSB7ct3vWvNdMA_VPXI5uPks1XRhIhy6UbztSSjsi-zhiT2FVTTvUyy2nA-9GY2RPvTBOEUOIUwuAhAQFgaV3T7qmsuUczrtQJ1np6WHD4ecjo0eQwMwONU7fXe8_xRXBCn1Cs2AM5s3fajLEo-PU16cz4Y2xjBlQHKh-BLfKeyVFGyB8ZcbMGdsqxeO42NmO0SWzqgA-lvVOj2vWcph_I8Zvwaf-OIgQlizCjBGLw5V6rDS4ZzUHTZhG2S9wAqW2ADQrp7QQ40P5_TBXE9N_W_1ATZpi5eT4MUs2TzR7MSjZ4yTb3UeOJh8sUHBO3zoFZt2Z_KAfoN2ELcuBkg8CIER-Zfe3C69dnD8JVB5JFiicdHJzuDOqCd8npIGzieojjxyEHi0OuL6kO10R_IBdIhTRKMGEQNwE8tIUKXGxREetCetVGbtsbFsztVHai-ANk8Vvkn_l8iLyPCozn3qV_1JH1Z33hxkM2i0nHRkYx4cz96t4tfEC-NSv0On3LL0OUj0X6z-XJFRIYS7Za1KPzF_dtyNf93KL7HgSlvhvKb8gMWiR022JvBLT9TFW1e9yBdv33O3il0KYyvYuOoJXrlu433CkbfImFQvoeoba5y62AwT-nJvDUE_SihQSGROABb2QfNt4kWXZHDpHW4O0SRJe1HfallCBRld5CWH-_C8awpVxSx5IF-583NaiVy0U1OCYnIAKhZlCsdB8f9dtQq4r4k_ZJcP9V2UECh_hzAVQw3NYdnUemSFAbRNYOeNd03pgJOMbOQ-kWDNhSlv98iMchiQ.qrmk3mJHtw1HZMLilDZ98Q
01:38:46​​​www.tickertape.in​3​get​script​https://d1fhalcexdp3mc.cloudfront.net/
01:38:46​​​www.tickertape.in​3​get​script​https://media.vmax.com/vjs/vlib.js?v=1.0
01:38:46​​​www.tickertape.in​3​post​xhr​https://as.vmax.com/getad.php
01:38:39​​​www.google.com​3​get​script​https://www.gstatic.com/recaptcha/releases/rz4DvU-cY2JYCwHSTck0_qm-/recaptcha__en.js
01:38:38​​​www.google.com​3,1​get​script​https://www.google.com/recaptcha/enterprise/webworker.js?hl=en&v=rz4DvU-cY2JYCwHSTck0_qm-
01:38:38​​​www.google.com​3,1​get​script​https://www.google.com/js/bg/RWTT3oxVpjnMak3qs5vv7tg5xSkq7YqXMGNs3aBXMhQ.js

```

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/76812421/9b887640-1c93-4859-81b9-a615c5405a9e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
Coming from `https://media.tickertape.in/websdk/1.3.13/ad.js`
