### ISSUE TITLE
card.discover.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#23371]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://card.discover.com/web/cardacq/referral/?page=referfriend&trafficCode=14`

### Category

breakage

### Description

Discover Card referal page doesn't work when uBlock origin is enabled. Disabling it fixes the issue. 

### Other extensions used

FastFoward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-19 143045](https://github.com/uBlockOrigin/uAssets/assets/69532417/141fb98a-1936-4516-99cf-ef417fbcca80)
![Screenshot 2024-04-19 143130](https://github.com/uBlockOrigin/uAssets/assets/69532417/6f304952-aed3-42ac-a68c-33526b7cef5b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 179586
 cosmetic: 229325
 scriptlet: 51181
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78174-6141, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98290-82469, now
  adguard-generic: 80719-5552, now
  adguard-mobile: 9260-103, now
  adguard-spyware-url: 1494-5, now
  block-lan: 61-0, now
  curben-phishing: 14271-1, now
  easylist-annoyances: 4498-16, now
  easylist-newsletters: 7169-12, now
  easylist-notifications: 2989-81, now
  fanboy-cookiemonster: 50929-211, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 86127-685, 1h.23m Δ
  easyprivacy: 50791-901, 1h.23m Δ
  plowe-0: 3735-0, now
  ublock-badware: 8298-2, 1h.23m Δ
  ublock-filters: 37562-650, 1h.23m Δ
  ublock-privacy: 832-115, 1h.23m Δ
  ublock-quick-fixes: 324-2, 1h.23m Δ
  ublock-unbreak: 2252-7, 1h.23m Δ
  urlhaus-1: 12505-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 676 ms (selfie)
 maxAssetCacheWait: 331 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.share-widget
```
</details>

**Comment by liamengland1** [comment]
Test 
```
@@||refer.discover.com^$1p
@@||discover.extole.com^$domain=discover.com
```

**Comment by jimmysofat6864** [comment]
> Test
> 
> ```
> @@||refer.discover.com^$1p
> @@||discover.extole.com^$domain=discover.com
> ```

Adding that to "my filters" didn't work.

**Comment by liamengland1** [comment]
Try `card.discover.com#@#.share-widget`

**Comment by jimmysofat6864** [comment]
> Try `card.discover.com#@#.share-widget`

That worked and the link shows up now.
