### ISSUE TITLE
washingtonpost.com: breakage

### ISSUE THREAD

**Issue by Dolphin263** [uBlockOrigin/uAssets#23379]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.washingtonpost.com/politics/2024/04/20/house-vote-ukraine-israel-aid-johnson/`

### Category

breakage

### Description

On washington post "live updates" stories with many updates over time, there is sometimes a "show more..." button that normally adds content immediately below the button.  Without ublock origin enabled, this consists of an advertisement followed by the update.  Previously (maybe a few days ago?) ublock origin handled these types of stories flawlessly, but recently something changed.

Now when you click the "show more..." instead of showing just the final part of the story, it actually makes the entire update disappear including the first part and the show more button.  It's like the ad filtering gets extended too wide and takes down the entire section, including the desirable content.  

Thanks so much for your help!!!  I love ublock origin!  Having to disable it on this site (which I subscribe too / pay for!) makes me realize how much it makes things better!!! 

Note that this is only for "live updates" stories, which are often short lived, so the provided URL might not work for you anymore.  However, on a given day there is often a "live updates" story on the front page of the washington post.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 134347
 cosmetic: 46104
 scriptlet: 19121
 html: 1772
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37705-109, now
  ublock-badware: 8311-0, now
  ublock-privacy: 830-1, now
  ublock-unbreak: 2311-2, now
  easylist: 86177-174, now
  easyprivacy: 50790-62, now
  urlhaus-1: 12920-0, now
  plowe-0: 3736-1159, now
  ublock-quick-fixes: 253-33, now
filterset (user): [empty]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 106 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 74
 network:
  3gl.net: 1
  3lift.com: 7
  adnxs.com: 6
  adsafeprotected.com: 10
  amazon-adsystem.com: 1
  bidswitch.net: 6
  brandmetrics.com: 1
  casalemedia.com: 7
  criteo.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  launchdarkly.com: 4
  openx.net: 7
  permutive.app: 1
  pubmatic.com: 7
  rubiconproject.com: 9
  unpkg.com: 1
  webcontentassessor.com: 1
  zeustechnology.com: 2
 extended:
  ##.outbrain-wrapper
  ##.pb-sm.pt-sm.b
  ##[data-qa="article-body-ad"]
  ##[data-qa="right-rail-ad"]
  ##[data-testid="placeholder-box"]
  ##[data-ad-module]:not([style$="left: -10000px !important; top: …
  ##.w-100:has-text(Advertisement)
  ##[data-testid="article-body-card"]:has-text(Advertisement)
  #@#[data-ad-module]
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Dolphin263** [comment]
So I think I figured out how to fix it.  This is the first time I'm trying to do use the ubo tools like the logger to make changes to filters.  Here's my first filter change ever  :) :

www.washingtonpost.com#@#[data-testid="article-body-card"]:has-text(Advertisement)

I did this by disabling the tool in the logger with the element blocker.  So far it resolves the issue and I don't see any ads.  Sweet!  Feel free to add this for others.

**Comment by Dolphin263** [comment]
I now see the original reason for this rule was to remove cards that have ads.  The ads themselves are blocked another way, so with this rule disabled you do see some small blank cards, like so:

![image](https://github.com/uBlockOrigin/uAssets/assets/160294196/8172f458-560b-4c01-8aa4-06c64b667f23)

Disabling that rule and seeing the empty cards occasionally is a small price to pay to be able to use the "show more..." buttons, but someone better than me might be able to rewrite the rule so it only gets the standalone ads and not the adds embedded in the show more section.

**Comment by mapx-** [comment]
test

```
washingtonpost.com#@#[data-testid="article-body-card"]:has-text(Advertisement)
washingtonpost.com##[data-testid="article-body-ad-desktop"]:upward(1)
```

**Comment by Dolphin263** [comment]
> test
> 
> ```
> washingtonpost.com#@#[data-testid="article-body-card"]:has-text(Advertisement)
> washingtonpost.com##[data-testid="article-body-ad-desktop"]:upward(1)
> ```

This works great, thanks so much!

**Comment by stephenhawk8054** [comment]
I think `:has` could work here
