### ISSUE TITLE
moneycontrol.com: breakage

### ISSUE THREAD

**Issue by kookieman12** [uBlockOrigin/uAssets#23372]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.moneycontrol.com/news/business/markets/pms-or-mutual-funds-how-returns-compared-12673241.html/amp`

### Category

breakage

### Description

Only initial text is available in the article when ublock origin is enabled as it is blocking some buttons which control the display of text. The rest of the text is not accessible. This is happening with all the articles on this website 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 139061
 cosmetic: 121655
 scriptlet: 25182
 html: 1772
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29275-39, now
  ublock-cookies-adguard: 1117-15, now
  fanboy-cookiemonster: 50929-3873, now
  ublock-cookies-easylist: 1117-1117, now
 default:
  user-filters: 2-0, never
  ublock-filters: 38062-110, 49m Δ
  ublock-badware: 8294-0, 49m Δ
  ublock-privacy: 830-1, 49m Δ
  ublock-unbreak: 2314-2, 49m Δ
  ublock-quick-fixes: 249-33, 49m Δ
  adguard-mobile: 9258-60, now
  easylist: 86127-230, 49m Δ
  easyprivacy: 50791-69, 49m Δ
  urlhaus-1: 12505-0, now
  plowe-0: 3735-1235, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 417 ms (selfie)
 maxAssetCacheWait: 118 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  moneycontrol.com: 1
  ampproject.org: 4
 extended:
  ##.ad-section
  ###bottomAd
  ##.amp-unresolved
  ##.i-amphtml-unresolved
  ##.mid-arti-ad
  ##body div.advSlotsGrayBox
  ##AMP-AD
  ##amp-sticky-ad
  ##amp-ad
  ##amp-fx-flying-carpet
  ##amp-embed[type="taboola"]
  ##+js(set-constant, initializeInterstitial, noopFunc)
```
</details>

**Comment by mapx-** [comment]
test

```
moneycontrol.com##.hide_in_desktop.footer_navigation_list:style(height: 10px !important)
moneycontrol.com##.advSlotsGrayBox
```
