### ISSUE TITLE
banned.video: ads

### ISSUE THREAD

**Issue by RacistandProudofit** [uBlockOrigin/uAssets#23382]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
banned.video
```

### Description

I notice that the ads are not being blocked on the fake news conspiracy website, Banned.video when visiting their mobile site on Kiwi Browser.  While Kiwi browser may not be "officially supported", I am posting this anyways as this appears to be a filter list issue since it works fine on Firefox for PC with the same exact filters used.  There is also no mention in the extensive list of prerequisites that no issues may be reported if using this browser so I see no reason why this legitimate issue can not be reported. Also, whether or not that many people tune into this site or not (which has millions of unique monthly visitors), this is still technically an issue that needs to be addressed.  I expect this issue to be treated with the upmost professionalism, unlike what happens in the reddit sub where people are falsely accused of ban evasion without any tangible evidence other than "the complaints are the same".  

Here is a video showing mobile browser vs PC
https://imgur.com/a/D734oNk

### Other extensions used

violent monkey, I don't care about cookies, new tab, infinity new tab for mobile

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/167045980/1959ab18-f0ce-49e6-b7f7-3b44605d5932)
![image](https://github.com/uBlockOrigin/uAssets/assets/167045980/dad439f3-7273-439a-8758-bce90be47d50)
[](https://imgur.com/a/D734oNk)

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Kiwi is not supported. Test again in Firefox Mobile.

**Comment by stephenhawk8054** [comment]
Ok, I can reproduce on Firefox desktop
