### ISSUE TITLE
volkskrant.nl: broken Twitter embed

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23389]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.volkskrant.nl/buitenland/in-aanloop-naar-verkiezingen-ruziet-maduro-met-vs-amerikanen-komen-afspraken-over-opheffen-sancties-niet-na~b68b7c1c/.`

(other article without paywall)

### Category

breakage

### Description

The Twitter embed is broken by the EasyList/uBO Cookie Notice list. Without the list enabled the page loads correctly after some delay. Site probably behaves similar to other DPG Media sites.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136349
 cosmetic: 91136
 scriptlet: 24088
 html: 1772
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50931-183, 1m
  ublock-cookies-easylist: 1079-4, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 37701-109, now
  ublock-badware: 8317-0, now
  ublock-privacy: 830-1, now
  ublock-unbreak: 2313-2, now
  ublock-quick-fixes: 247-21, now
  easylist: 86193-174, now
  easyprivacy: 50791-62, now
  urlhaus-1: 13070-0, now
  plowe-0: 3736-1159, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 77 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  volkskrant.nl: 1
  dpgmedia.cloud: 1
  googletagmanager.com: 1
  usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
> Artikelen van Natalie Righton zijn exclusief voor abonnees

if you are willing to share your credentials account weìll investigate the issue (I'll provide an email address in case you agree)

**Comment by twiddle-hobbies** [comment]
Right, I forgot about the paywall.

This other article should not be paywalled: https://www.volkskrant.nl/buitenland/in-aanloop-naar-verkiezingen-ruziet-maduro-met-vs-amerikanen-komen-afspraken-over-opheffen-sancties-niet-na~b68b7c1c/.

Thanks!

**Comment by mapx-** [comment]
ELC issue @ryanbr
