### ISSUE TITLE
cracked.io: ads

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#23384]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cracked.io/`

### Category

ads

### Description

This forum shows banner ads, it also gets different when you try to refresh the page and these banner ads are also on the threads too. For the threads its pretty depending on the user or a different thread where these banners can be different. They are mostly gifs and sometimes uses images.

### Other extensions used

Mostly not related to ublock
- Cookie Extension
- Downthemall
- Dark Reader
- DeArrow
- ChatGPT Box

### Screenshot(s)

![tMnmSnFUe3](https://github.com/uBlockOrigin/uAssets/assets/150899804/f25733e1-8e39-4459-adbb-5f0fe1dc9178)
![librewolf_0MT14MOvWX](https://github.com/uBlockOrigin/uAssets/assets/150899804/249cd69f-505e-4dc4-8899-a35b8943a6ab)
![librewolf_bK5Gm6k7Kx](https://github.com/uBlockOrigin/uAssets/assets/150899804/d8e3224c-5d64-4798-b7f2-b3cb9ce145e1)

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 121
filterset (summary):
 network: 169868
 cosmetic: 66682
 scriptlet: 20513
 html: 1787
listset (total-discarded, last-updated):
 added:
  RUS-0: 39415-140, now
 default:
  user-filters: 56-3, never
  ublock-filters: 37700-109, now
  ublock-badware: 8317-0, now
  ublock-privacy: 830-1, now
  ublock-unbreak: 2313-2, now
  ublock-quick-fixes: 253-31, 24m Δ
  easylist: 86177-174, 24m Δ
  adguard-spyware-url: 1494-120, now
  easyprivacy: 50790-62, 24m Δ
  urlhaus-1: 13070-0, 24m
  curben-phishing: 14203-2, 24m
  plowe-0: 3736-1160, now
  LegitimateURLShortener: 2621-165, 24m
filterset (user): [array of 56 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 563 ms (selfie)
 maxAssetCacheWait: 239 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.inner_stuff
  ##.red_alert
  ###pm_notice
```
</details>

**Comment by ryanbr** [comment]
The homepage sure, but every different user has ads for signatures not sure if its viable
