### ISSUE TITLE
toshort.in: detection

### ISSUE THREAD

**Issue by Noorhasanrz** [uBlockOrigin/uAssets#23380]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://toshort.in/Qcbl`

### Category

detection

### Description

This is link shortener it's redirects to 
`https://arikma.com/stocks-to-buy-watch-this-stock-of-adani-group-selected-by-anil-singhvi/`
and this was detected uBlock.

### Other extensions used

Tempermonkey

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/145339882/3a9b2a46-9d1d-42a9-81a0-f57b04514a20

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 135749
 cosmetic: 54050
 scriptlet: 19190
 html: 1773
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38067-110, 3m
  ublock-badware: 8305-0, 3m
  ublock-privacy: 830-1, 3m
  ublock-unbreak: 2315-2, 3m
  ublock-quick-fixes: 253-33, 3m
  adguard-mobile: 9260-60, 3m
  easylist: 86177-232, 3m
  easyprivacy: 50790-70, 3m
  urlhaus-1: 12920-0, 3m
  plowe-0: 3736-1234, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 419 ms (selfie)
 maxAssetCacheWait: 156 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
it requires indian ip

ask here for help: https://github.com/uBlockOrigin/uAssets/discussions/17361

(on desktop chrome no issue on my end)
