### ISSUE TITLE
seekingalpha.com: nuisance

### ISSUE THREAD

**Issue by rogertcs** [uBlockOrigin/uAssets#23385]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://seekingalpha.com/article/4684580-tesla-stock-plunging-toward-my-price-target`

### Category

nuisance

### Description

still blocked from paywall after some change by the site couple of weeks ago

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 121
filterset (summary):
 network: 134532
 cosmetic: 46220
 scriptlet: 20509
 html: 0
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, now
 default:
  user-filters: 0-0, never
  easylist: 86192-42, 5m Δ
  easyprivacy: 50791-14, 5m Δ
  plowe-0: 3736-1159, now
  ublock-badware: 8315-16, 5m Δ
  ublock-filters: 37562-371, 5m Δ
  ublock-privacy: 832-82, 5m Δ
  ublock-quick-fixes: 315-19, 5m Δ
  ublock-unbreak: 2256-34, 5m Δ
  urlhaus-1: 13070-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1884 ms (selfie)
 maxAssetCacheWait: 1015 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
It's login wall

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/8972c4ca-a809-4fee-bea1-8c9b3ba9bf29)

However, in order to block it, I have to block `tinypass.com` as well, which can cause issues for valid subscriptions.

---

@rogertcs Test these filters

```adb
seekingalpha.com##+js(nostif, '"error"')
seekingalpha.com##+js(aeld, error, (e), elements, [src*="tinypass.com"])
||tinypass.com^$script,3p,domain=seekingalpha.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by rogertcs** [comment]
@stephenhawk8054 amazing! works perfectly! thank you!
