### ISSUE TITLE
bilibili.com: nuisance

### ISSUE THREAD

**Issue by Oqarshi** [uBlockOrigin/uAssets#23383]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bilibili.com/`

### Category

nuisance

### Description

There are these ablock left overs after blocking the ads. This has already been reported and i tried updating my filters but it doesent remove these annoying adblock leftovers

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/cab73777-9836-4714-b3a3-328d96dcf449)
![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/2b859061-5971-4850-b04a-d0878d91c5ea)
![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/140f9cd6-60f5-404a-af31-e0445db779e7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 159900
 cosmetic: 147192
 scriptlet: 46147
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80958-5561, 3m
  adguard-mobile: 9260-14, 3m
  adguard-popup-overlays: 27128-707, 3m
  adguard-mobile-app-banners: 5149-8, 3m
  adguard-other-annoyances: 14155-114, 3m
  adguard-widgets: 2473-44, 3m
  easylist-annoyances: 4501-45, 3m
  easylist-chat: 190-0, 3m
  easylist-newsletters: 7172-10, 3m
  easylist-notifications: 2989-1516, 3m
  ublock-annoyances: 6942-185, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 37564-639, 3m
  ublock-badware: 8309-0, 3m
  ublock-privacy: 832-0, 3m
  ublock-unbreak: 2256-0, 3m
  ublock-quick-fixes: 327-3, 3m
  easylist: 86177-683, 3m
  easyprivacy: 50790-30, 3m Δ
  urlhaus-1: 13070-0, 3m
  plowe-0: 3736-870, 2m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1381 ms (selfie)
 maxAssetCacheWait: 424 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 50
 network:
  bilibili.com: 47
  google.com: 2
  hdslb.com: 1
 extended:
  ##.__adblockhidden
  ##.login-panel-popover
  ##.lt-row > .lt-col > .vip-login-tip
  ##a[href*="cm.bilibili.com"][data-target-url*=".bili"]
  ##+js(nowebrtc)
  ##+js(addEventListener-defuser, selectionchange, quill.emitter)
  ##+js(addEventListener-defuser, copy)
```
</details>

**Comment by mapx-** [comment]
use the regional list => if still happens report here: https://github.com/cjx82630/cjxlist/issues
