### ISSUE TITLE
kitploit.com: ads, widgets

### ISSUE THREAD

**Issue by 0x11DFE** [uBlockOrigin/uAssets#23399]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.kitploit.com/
```

### Description

Fake post ads and follow widget and email subscription.

### Other extensions used

A lot but still showing that ads (unknown website)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ads](https://github.com/uBlockOrigin/uAssets/assets/43712252/4c5d5750-5d69-4f14-a7f3-5104764bcb76)
![Widget](https://github.com/uBlockOrigin/uAssets/assets/43712252/41dfabfb-ed1d-41ed-9eb7-01c4afad91bb)

</details>

### Configuration

<details>
<summary>Fix ?</summary>

```yaml
# Ads
www.kitploit.com##div.ad-post-henry
# Widget
www.kitploit.com###HTML4
```
</details>

**Comment by mapx-** [comment]
I see no post-ad, however report it at easylist repo
