### ISSUE TITLE
twitter.com: nuisance

### ISSUE THREAD

**Issue by migozz** [uBlockOrigin/uAssets#23392]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://twitter.com/winsource
```

### Description

When opening a twitter.com page, it starts opening, and you can see contents of the page for the short time, and then redirects to login page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/24635618/b78bcc18-df0f-465f-a7e8-01ad0491125a)
![2](https://github.com/uBlockOrigin/uAssets/assets/24635618/e517616e-e2c5-4dd0-a4aa-869a925af7c3)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 155606
 cosmetic: 89264
 scriptlet: 20628
 html: 1805
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25468-47, 1d.21h.57m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1716-0, 19h.47m
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, 6d.8m
  ublock-quick-fixes: 247-1, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 37703-184, 20h.47m Δ
  ublock-badware: 8311-0, 20h.47m Δ
  ublock-privacy: 830-84, 20h.47m Δ
  ublock-unbreak: 2311-6, 20h.47m Δ
  easylist: 86177-596, 20h.47m Δ
  easyprivacy: 50790-1113, 20h.47m Δ
  urlhaus-1: 12920-0, 19h.46m
  plowe-0: 3735-7, 1d.22h.58m
  RUS-0: 39417-203, 6m Δ
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8156 ms (selfie)
 maxAssetCacheWait: 3737 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  twitter.com: 16
  google.com: 6
 extended:
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(remove-attr, data-jsarwt, #rcnt [data-ved] a)

```
</details>

**Comment by stephenhawk8054** [comment]
I actually don't see the content being loaded before redirecting. It does show the loading icon but the content has never been loaded so I think it's server-sided and nothing can be done in browser clients.

**Comment by migozz** [comment]
I used net limiter to slow down connection.

https://github.com/uBlockOrigin/uAssets/assets/24635618/30cf71b1-e0df-4978-a163-56b53e5cb850

**Comment by stephenhawk8054** [comment]
Yes, I mean the content below that (the tweets...)

**Comment by Yuki2718** [comment]
`twitter.com##+js(nostif, l(), 100)`
