### ISSUE TITLE
crackle.com: ads

### ISSUE THREAD

**Issue by Joyskol** [uBlockOrigin/uAssets#23390]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.crackle.com/watch/b5005735-ba95-483c-b72c-b19f66f202e5/detective-mclean/pilot`

### Category

ads

### Description

It starts with ads, and ads in between. No way I could stop it.

### Other extensions used

That is a very long list of extensions but I keep mostly non-activated.  I only activate them when required, mostly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screen](https://github.com/uBlockOrigin/uAssets/assets/167684279/5a67b9bf-1d7a-4de4-b0e1-1c59f2c20c24)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 134532
 cosmetic: 46220
 scriptlet: 20509
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86192-557, 49m Δ
  easyprivacy: 50791-810, 49m Δ
  plowe-0: 3736-0, now
  ublock-badware: 8315-0, 49m Δ
  ublock-filters: 37562-290, 49m Δ
  ublock-privacy: 832-0, 49m Δ
  ublock-quick-fixes: 315-1, 49m Δ
  ublock-unbreak: 2256-2, 49m Δ
  urlhaus-1: 13070-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 321 ms (selfie)
 maxAssetCacheWait: 98 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 network:
  crackle.com: 31
  bitmovin.com: 2
  fwmrm.net: 3
  googletagmanager.com: 1
  mparticle.com: 1
 extended:
  ##+js(json-prune, data.device.adSponsorshipTemplate data.device.…
```
</details>

**Comment by Joyskol** [comment]
Thank you friend. Wherever you are, God bless you. If I face any future
problems can I post them directly to you?
Regards.

**Comment by mapx-** [comment]
You can comment here again.
