### ISSUE TITLE
pillowcase.su: breakage

### ISSUE THREAD

**Issue by anthonyabbasi** [uBlockOrigin/uAssets#23397]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pillowcase.su/f/bd9c886705bc3e6a091c510cd2cfca71`

### Category

breakage

### Description

Website wont play audio when "uBlock filters – Ads" filter list is enabled, I have tried and confirmed this by disabling all my other filter lists and extensions. Also this is not the only URL that doesn't work on their website, it's every file provided on there. Here are some other files if you would like to test them out also. Another mp3 file: https://pillowcase.su/f/96108f787409ee5f1a784247302981d9 an mp4 file: https://pillowcase.su/f/5add1e3ce2446fa418fe51e8dc893942 You should be able to play the mp4 on the website as a video.

### Other extensions used

History Eraser, Adobe Acrobat, Augmented Steam, Buster, ClearURLs, Cookie-Editor, Dark Editor, FastForward, Google Docs Offline, Kaspersky Password Manager, Kaspersky Protection (I disabled the private banner and private browsing), movie-web extension, OneTab, Honey, Return YouTube Dislike, Roblox Friend Removal Button, RoPro, SponsorBlock, SteamDB, Tampermonkey (I have no installed scripts), Volume Master, Web Archives

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/82628864/84b4ff93-6dda-4229-aa62-bfb862b652e9)
![image](https://github.com/uBlockOrigin/uAssets/assets/82628864/738cf05b-859f-4e02-aa4d-b722e238bf38)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 165520
 cosmetic: 250171
 scriptlet: 51268
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29275-3760, now
  adguard-generic: 80958-5572, now
  adguard-mobile: 9260-108, now
  adguard-mobile-app-banners: 5149-1103, now
  adguard-other-annoyances: 14157-481, now
  adguard-popup-overlays: 27131-1687, now
  adguard-social: 22829-754, now
  adguard-widgets: 2473-39, now
  easylist-annoyances: 4507-16, now
  easylist-chat: 190-0, now
  easylist-newsletters: 7209-12, now
  easylist-notifications: 2964-81, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 86419-690, now
  easyprivacy: 50793-906, now
  plowe-0: 3736-0, now
  ublock-badware: 8320-0, now
  ublock-filters: 37577-639, now
  ublock-privacy: 832-1, now
  ublock-quick-fixes: 274-1, now
  ublock-unbreak: 2256-4, now
  urlhaus-1: 13265-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 797 ms (selfie)
 maxAssetCacheWait: 137 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon @Yuki2718 From what I see, there are 2 scripts that have `popundersPerIP`. The one that is wrapped by `"` is the one we should remove. The one that is wrapped by `\"` is put into another script that would break the site if removing it. The 2nd case looks like this

```
"\u003Cscript type=\"text/javascript\" data-cfasync=\"false\">\n/*\u003C![CDATA[/* */\n(function(){var h=window,d=\"fcab7f305c4022274e9e9aa1f6f37446\",z=[[\"siteId\",581+652-498+219+829+5076734],[\"minBid\",0.001],[\"popundersPerIP\",\"3\"],[\"delayBetween\",0],[\"default\",false],[\"defaultPerDay\",0],[\"topmostLayer\",\"auto\"]],q=[\"d3d3LmludGVsbGlnZW5jZWFkeC5jb20vaGpzbXBnLm1pbi5jc3M=\",\"ZDJrbHg4N2Jnem5nY2UuY2xvdWRmcm9udC5uZXQvdXhCRWEvbmpzLWRhdGEubWluLmpz\",\"d3d3Lmxkd2Jndmh4dnRuanRvLmNvbS9tanNtcGcubWluLmNzcw==\",\"d3d3LnlrYWthc3NnLmNvbS9rdGJTaC9tanMtZGF0YS5taW4uanM=\"],j=-1,l,s,e=function(){clearTimeout(s);j++;if(q[j]&&!(1739668500000\u003C(new Date).getTime()&&1\u003Cj)){l=h.document.createElement(\"script\");l.type=\"text/javascript\";l.async=!0;var w=h.document.getElementsByTagName(\"script\")[0];l.src=\"https://\"+atob(q[j]);l.crossOrigin=\"anonymous\";l.onerror=e;l.onload=function(){clearTimeout(s);h[d.slice(0,16)+d.slice(0,16)]||e()};s=setTimeout(e,5E3);w.parentNode.insertBefore(l,w)}};if(!h[d]){try{Object.freeze(h[d]=z)}catch(e){}e()}})();\n/*]]>/* */\n\u003C/script>"
```

It's quite similar to [admiral case](https://github.com/uBlockOrigin/uAssets/blob/2eae1a4baa92a9786539ca8fc12a7c60ed0ca906/filters/filters-2023.txt#L4054-L4092).

I'm not familiar with previous cases. Do all previous cases have `"` wrapped around `popundersPerIP`? If they do, I think we can switch to `/h=decodeURIComponent|"popundersPerIP"/` to prevent similar breakage for all other cases as well.

**Comment by anthonyabbasi** [comment]
Sorry, I'm not entirely sure on how this works but is this completed on my end or do I have to put something in my end or do I have to wait a bit

**Comment by stephenhawk8054** [comment]
@anthonyabbasi Wait about 5-6 hours and update your filter lists. Or you can add these filters as custom filters in the meantime

```adb
pillowcase.su#@#+js(remove-node-text, script, /h=decodeURIComponent|popundersPerIP/)
pillowcase.su##+js(remove-node-text, script, /h=decodeURIComponent|"popundersPerIP"/)
```

**Comment by anthonyabbasi** [comment]
Okay, thank you so much, I appreciate the fast response

**Comment by Yuki2718** [comment]
> Do all previous cases have `"` wrapped around `popundersPerIP`? 

Yes, PA script is generally the same except for the encoded domains.

**Comment by Yuki2718** [comment]
Old PA scripts use `'popundersPerIP'` `https://megalinks.info`

**Comment by Yuki2718** [comment]
@AdamWr AG also has to adjust `$$script[data-cfasync="false"][wildcard="*popundersPerIP*atob*"][min-length="500"][max-length="4000"]`. I think now it should be changed to `:contains()`?

**Comment by AdamWr** [comment]
>I think now it should be changed to `:contains()`?

I think that it's not necessary for now, and if I'm not wrong, it's not supported by AdGuard extension for Firefox yet.

**Comment by stephenhawk8054** [comment]
> Old PA scripts use `'popundersPerIP'` `https://megalinks.info`

Hmm... Maybe then only adjust for the breakages sites reported

**Comment by Yuki2718** [comment]
Probably no need. The old PA is not the target of the rules.
