### ISSUE TITLE
download.megaup.net: detection

### ISSUE THREAD

**Issue by yukiami** [uBlockOrigin/uAssets#23398]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/`

### Category

detection

### Description

MegaUP still gives an adblock detected message even with updated filters and dev build

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.3b5
Firefox: 115
filterset (summary):
 network: 134869
 cosmetic: 46134
 scriptlet: 19130
 html: 1772
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37706-109, now
  ublock-badware: 8317-0, now
  ublock-privacy: 833-1, now
  ublock-unbreak: 2313-2, now
  ublock-quick-fixes: 200-19, now
  easylist: 86419-174, now
  easyprivacy: 50791-62, now
  urlhaus-1: 13265-0, now
  plowe-0: 3736-1159, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3470 ms
 maxAssetCacheWait: 68 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 2
  keydawnawe.com: 1
 extended:
  ##a img:not([src="images/main_logo_inverted.png"]):matches-css(h…
  ##+js(spoof-css, a img:not([src="images/main_logo_inverted.png"]…
  ##+js(trusted-replace-node-text, script, /\]\s*\!\s*=/g, ]==)
  ##+js(trusted-replace-node-text, script, /!=\s*_/, ==_)
  ##+js(trusted-replace-node-text, script, /!=\s*'/, ==')
  ##+js(abort-current-script, Math, break;case $.)
```
</details>

**Comment by huyszn** [comment]
Duplicate, continue in https://github.com/uBlockOrigin/uAssets/issues/20505
