### ISSUE TITLE
azmath.info: detection

### ISSUE THREAD

**Issue by Yurokocat** [uBlockOrigin/uAssets#23391]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://azmath.info/`

### Category

detection

### Description

https://github.com/uBlockOrigin/uAssets/assets/137869748/dd801f57-a156-45c5-9ff0-00d82431d468
https://github.com/uBlockOrigin/uAssets/assets/137869748/2eb36449-e18a-4235-9a01-4fed4dc0fe6b

### Other extensions used

https://github.com/uBlockOrigin/uAssets/assets/137869748/e88d6cfb-b1a1-461a-9cac-667d54a55dca

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
AdBlock Max - chặn quảng cáo: 1.0.11
Chromium: 124
filterset (summary): 
 network: 134313
 cosmetic: 46022
 scriptlet: 19174
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  VIE-1: null
 default: 
  user-filters: 15-2, never
  easylist: 86043-42, 2d.4h.46m
  easyprivacy: 50769-13, 2d.4h.45m
  plowe-0: 3758-1181, 12d.6h.4m
  ublock-badware: 8279-16, 3d.3h.23m
  ublock-filters: 36034-216, 3d.3h.22m
  ublock-privacy: 762-5, 2d.10h.38m
  ublock-quick-fixes: 209-18, 8h.6m
  ublock-unbreak: 2249-34, 3d.3h.21m
  urlhaus-1: 13070-0, 12h.8m
filterset (user): [array of 15 redacted]
trustedset: 
 added: [array of 4 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 504 ms (selfie)
 maxAssetCacheWait: 314 ms
popupPanel: 
 blocked: 7
 network: 
  azmath.info: 3
  doubleclick.net: 2
  exmarketplace.com: 1
  googlesyndication.com: 1
 cosmetic: 
  ##.gptslot
  #@#.ad-unit
  #@#.ad_unit
```
</details>

**Comment by mapx-** [comment]
> AdBlock Max 

invalid
