### ISSUE TITLE
elitepvpers.com: detection

### ISSUE THREAD

**Issue by LoopStation** [uBlockOrigin/uAssets#23393]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.elitepvpers.com/forum/profile.php?do=customize`

### Category

detection

### Description

The Website are see ublock and load a ublock-censor-regime-de.png Grahic File. Blocking this File is not Working the PNG is commin again an again after switch in the forum the site or the threads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://gyazo.com/ac4ec8f302b2ba89553d47432a12bb9d

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 137405
 cosmetic: 51123
 scriptlet: 19082
 html: 1768
listset (total-discarded, last-updated):
 default:
  user-filters: 14-6, never
  ublock-filters: 37620-108, now
  ublock-badware: 8317-0, now
  ublock-privacy: 830-5, now
  ublock-unbreak: 2313-2, now
  ublock-quick-fixes: 247-40, 1h.57m Δ
  easylist: 86415-174, now
  easyprivacy: 50793-62, now
  urlhaus-1: 13445-0, 12m
  plowe-0: 3736-1159, now
  DEU-0: 7405-36, 12m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1321 ms (selfie)
 maxAssetCacheWait: 1011 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  elitepvpers.com: 2
  cloudflareinsights.com: 2
  googletagmanager.com: 1
 extended:
  ##[width="729"]
  ##div[style^="font-size:11px;"]
  ##div > .page > div > div[style]:has-text(/^Advertise/i) + a
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances`
