### ISSUE TITLE
[nsfw] tpayr.xyz: detection

### ISSUE THREAD

**Issue by xxikml** [uBlockOrigin/uAssets#23408]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tpayr.xyz/lemon-orange-orange-roughy-recipe/`

### Category

detection

### Description

it originally not this website, it go redirected after i access this "https://droplink.co/n1YhDD" url. on the url that i got redirected, they like have countdown so i have to click the add so i can access to the next website that are probably where the file can get downloaded

### Other extensions used

tempermonkey, fastforward, bitwarden, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70498951/efcfc8e1-6b96-4648-af1c-dd2387d0a885)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 284899
 cosmetic: 253682
 scriptlet: 51200
 html: 2052
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt: 651-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/modal_filters.txt: 3843-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98377-17129, 2m
  adguard-generic: 80958-3965, now
  adguard-spyware-url: 1501-120, now
  ublock-annoyances: 6886-149, 1h.54m Δ
  dpollock-0: 11669-396, now
  CHN-0: 25436-210, now
  IDN-0: 9918-74, now
  JPN-1: 14571-96, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 37753-134, 1h.54m Δ
  ublock-badware: 8362-0, 1h.54m Δ
  ublock-privacy: 833-3, 1h.54m Δ
  ublock-unbreak: 2313-5, 1h.54m Δ
  easylist: 86158-1672, 1h.54m Δ
  easyprivacy: 50793-305, 1h.54m Δ
  urlhaus-1: 14150-0, 1h.54m
  plowe-0: 3737-1543, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3378 ms
 maxAssetCacheWait: 2292 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  doubleclick.net: 5
  google.com: 1
  profitsfly.com: 2
  tiktokcounter.net: 1
  youtube.com: 6
 extended:
  ##div[class][data-index][style^="float: none; margin"]
  ##.ytp-pause-overlay
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune-fetch-response, overlay, overlay.shortsAdsRende…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by mapx-** [comment]
ask for help here: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by shenawy36** [comment]
@D4niloMR Need update sir and tiktokcounter

**Comment by smaragdina** [comment]
![Screenshot_2024-04-25-01-44-47-00_4d38fce200f96aeac5e860e739312e76](https://github.com/uBlockOrigin/uAssets/assets/36397582/775049f5-ee61-45b3-99b0-9d86b73599c5)
tpayr still detect bro
