### ISSUE TITLE
sg.hu: nuisance

### ISSUE THREAD

**Issue by LoockyLucky** [uBlockOrigin/uAssets#23400]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sg.hu/forum/tema/1263048233`

### Category

detection

### Description

detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2179" alt="Capture d’écran 2024-04-22 à 06 23 14" src="https://github.com/uBlockOrigin/uAssets/assets/146693990/a94f7d1d-4071-4fdb-aaff-5f2c2d3a6f1b">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 158008
 cosmetic: 106016
 scriptlet: 27315
 html: 2036
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27131-208, now
  adguard-mobile-app-banners: 5149-19, now
  adguard-other-annoyances: 14157-293, now
  adguard-widgets: 2473-7, now
  easylist-annoyances: 4509-268, now
  easylist-chat: 190-16, now
  easylist-newsletters: 7212-503, now
  easylist-notifications: 2966-1521, now
  ublock-annoyances: 6886-189, 11m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 37709-109, 11m Δ
  ublock-badware: 8317-0, 11m Δ
  ublock-privacy: 830-1, 11m Δ
  ublock-unbreak: 2313-2, 11m Δ
  ublock-quick-fixes: 201-21, 11m Δ
  easylist: 86415-174, 11m Δ
  easyprivacy: 50793-62, 11m Δ
  urlhaus-1: 13265-0, now
  plowe-0: 3736-1159, now
  FRA-0: 24401-508, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 116 ms (selfie)
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  gemius.pl: 1
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  inmobi.com: 2
```
</details>

**Comment by huyszn** [comment]
You were told to enable `AdGuard – Cookie Notices` in #23109
