### ISSUE TITLE
Huffington Post Video "Error Loading"

### ISSUE THREAD

**Issue by pjpreilly** [uBlockOrigin/uAssets#23405]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Videos in the story link fail to load with the extension enabled in both Chrome & Firefox but load when the extension is disabled. Seems not to be any specific filter though.

### A specific URL where the issue occurs.

```yaml
https://www.huffpost.com/entry/dems-mike-johnson-vote-ouster_n_66262532e4b0167f7bf5b742
```

### Steps to Reproduce

Load the page & observe.

### Expected behavior

Adds removed but story video plays.

### Actual behavior

"Error Loading" displayed.

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 220192
 cosmetic: 182062
 scriptlet: 34628
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78158-4458, 4d.17h.24m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 18h.59m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98202-70063, 4d.17h.24m
  adguard-spyware: 87899-28129, 4d.17h.24m
  adguard-spyware-url: 1494-5, 4d.17h.24m
  block-lan: 61-0, 3d.16h.15m
  curben-phishing: 14094-0, 18h.59m
  fanboy-cookiemonster: 66964-16305, 5d.19h.44m
  ublock-annoyances: 6942-9, 2m Δ
 default:
  user-filters: 98-2, never
  easylist: 86415-560, 2m Δ
  easyprivacy: 50793-830, 2m Δ
  plowe-0: 3739-1, 4d.17h.24m
  ublock-badware: 8360-1, 2m Δ
  ublock-filters: 37616-292, 2m Δ
  ublock-privacy: 832-114, 2m Δ
  ublock-quick-fixes: 253-4, 2m Δ
  ublock-unbreak: 2256-2, 2m Δ
  urlhaus-1: 13445-0, 18h.59m
filterset (user): [array of 98 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11611 ms (selfie)
 maxAssetCacheWait: 1711 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gorhill** [comment]
Need:

    @@||huffpost.com^$ghide
    @@||connatix.com^$domain=huffpost.com

We could re-write our own block filter to:

    ||connatix.com^$3p,domain=~huffpost.com

**Comment by pjpreilly** [comment]
> Need:

Added to my filters & it works....
