### ISSUE TITLE
vk.com: feed ads are now visible again

### ISSUE THREAD

**Issue by LeonserGT** [uBlockOrigin/uAssets#23402]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vk.com/feed`

### Category

ads

### Description

Ads embedded in the newsfeed are all suddenly visible, starting from today 22.04.2024
This is the kind of ads that pretends to be another post in the feed.
Previously they were reliably blocked, but now half of the visible content are those ads.

### Other extensions used

Return YouTube Dislike 3.0.0.16
Runet Censorship Bypass 0.0.1.63
Search by Image 6.1.2

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/49585618/ad77db97-2641-467e-a154-f64e9828bd50)
![image](https://github.com/uBlockOrigin/uAssets/assets/49585618/2339be37-7e10-4d1a-a01b-55301bb20842)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 151984
 cosmetic: 66739
 scriptlet: 21906
 html: 0
listset (total-discarded, last-updated):
 added:
  RUS-0: 39384-119, now
 default:
  user-filters: 3-0, never
  easylist: 86117-578, now
  easyprivacy: 50793-810, now
  plowe-0: 3736-0, now
  ublock-badware: 8353-0, now
  ublock-filters: 37591-291, now
  ublock-privacy: 832-0, now
  ublock-quick-fixes: 254-0, now
  ublock-unbreak: 2256-0, now
  urlhaus-1: 13265-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 649 ms (selfie)
 maxAssetCacheWait: 244 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  mail.ru: 3
  tns-counter.ru: 1
  vk-portal.net: 1
 extended:
  ###ads_left
  ###system_msg
  ##.PhotoPrimaryAttachment__background[src*="userapi.com/impf/"][…
  #@#div[id$="notifiers_wrap"]
  ##+js(abort-on-property-read, Groups.showDisclaimer)
  ##+js(href-sanitizer, a[href*="/away.php?"], ?to)
  ##+js(set-constant, PageBottomBanners, undefined)
  ##+js(set-constant, Unauthorized2, undefined)
  ##+js(set-constant, noAdsAtAll, {})
```
</details>

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This problem is better discussed here: https://forums.lanik.us/viewtopic.php?t=28751

**Comment by LeonserGT** [comment]
Yes, I have it and updated before submitting. Or should I open the ticket somewhere else specifically for that list?
