### ISSUE TITLE
chess.com : promotion leftover

### ISSUE THREAD

**Issue by voidlyvidevoid** [uBlockOrigin/uAssets#23403]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
chess.com/game/live
```

### Description

visible after a game end when played in a new account (<5 games)
`www.chess.com##.premium-trial-component` removes it.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/153749553/9de6e69a-d89a-4e8c-9258-a80048f1b178)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 134661
 cosmetic: 46213
 scriptlet: 20528
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37584-290, 1h.37m Δ
  ublock-badware: 8353-0, 1h.37m Δ
  ublock-privacy: 832-0, 1h.37m Δ
  ublock-unbreak: 2256-2, 1h.37m Δ
  ublock-quick-fixes: 274-1, 1h.37m Δ
  easylist: 86117-557, 1h.37m Δ
  easyprivacy: 50793-810, 1h.37m Δ
  urlhaus-1: 13265-0, 12m
  plowe-0: 3736-0, 12m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3034 ms
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  chess.com: 3
  dn0qt3r0xannq.cloudfront.net: 1
  sentry.io: 3
 extended:
  ##.board-layout-ad
  ###sidebar-ad
  ##body.board-layout.with-und:style(margin-right:0px!important)

```
</details>

**Comment by mapx-** [comment]
self promotion
