### ISSUE TITLE
download.megaup.net: detection

### ISSUE THREAD

**Issue by ertade3427** [uBlockOrigin/uAssets#23406]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUbeuUvBRiVBNZTMw8Nz86KMxaQIjPiUuBzt%2FcnH%2F+99bKJ3Rr5O1oaLUAFD4fhvohvkhw%2F1pRJHedcYPp2PjeOQzA%3D&idfilename=Against.Great.Darkness.rar&idfilesize=76.04+MB&__cf_chl_tk=YEfeJ298GMN_zIWzsv5050K3IQlFKPKBBQt.SZDv8lI-1713806003-0.0.1.1-1791`

### Category

detection

### Description

detects when turning back on elements, and everything. Your "check to see similar reports" didn't work, so i am sorry if this is a known issue.

### Other extensions used

dark reader, violentmonkey, localcdn, tree style tab, search by image, web archives, cleanurls, sponsorblock, returnyoutubedislikes, privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/121589978/66ef92b7-0bf9-49da-9d50-533b569de0a2)

![image](https://github.com/uBlockOrigin/uAssets/assets/121589978/3fafbd28-b204-4398-a76a-3d6234d5b728)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 135555
 cosmetic: 46138
 scriptlet: 19133
 html: 1778
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37753-109, 13m Δ
  ublock-badware: 8362-0, 13m Δ
  ublock-privacy: 833-1, 13m Δ
  ublock-unbreak: 2313-2, 13m Δ
  ublock-quick-fixes: 181-19, 13m Δ
  easylist: 86158-174, 13m Δ
  easyprivacy: 50793-63, 13m Δ
  urlhaus-1: 14150-0, now
  plowe-0: 3737-1159, now
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 261 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 no-cosmetic-filtering: true
 no-remote-fonts: true
 network:
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 2
  keydawnawe.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20505

**Comment by Arkaria317** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/167945322/0bf466ba-7bc0-46ba-9e98-d53296e17f37)
still detected today
