### ISSUE TITLE
ns.nl: breakage

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23404]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ns.nl/`

### Category

breakage

### Description

The banner in the middle of the page does not load.

I can fix the issue with the custom filter lists

```a
@@||cdn.cookielaw.org^$domain=ns.nl
@@||josiad.ns.nl^$1p
```

I added the first rule because I have the EasyList/uBO Cookie list enabled.

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 135842
 cosmetic: 46134
 scriptlet: 19127
 html: 1778
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37721-109, 1m
  ublock-badware: 8355-0, 1m
  ublock-privacy: 830-1, 1m
  ublock-unbreak: 2313-2, 1m
  ublock-quick-fixes: 253-33, 1m
  easylist: 86419-174, 1m
  easyprivacy: 50793-62, 1m
  urlhaus-1: 14150-0, 1m
  plowe-0: 3736-1159, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1153 ms
 maxAssetCacheWait: 15 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  ns.nl: 11
  datadoghq-browser-agent.com: 3
  googletagmanager.com: 1
  r42tag.com: 2
  usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
broken by EP & ELC

```
@@||josiad.ns.nl^$xhr,1p
@@||cdn.cookielaw.org/scripttemplates/*/otBannerSdk.js$script,domain=ns.nl
```
