### ISSUE TITLE
bloomberg.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#23413]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bloomberg.com/profile/company/6648340Z:GR`

### Category

ads

### Description

ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/d96bf6dc-8ec2-4e96-a64a-5dfd812a616b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 149886
 cosmetic: 181667
 scriptlet: 34315
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8081-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 203-1, now
  adguard-cookies: 29291-78, 1h.9m
  ublock-cookies-adguard: 1079-1079, 1h.9m
  fanboy-cookiemonster: 50948-3929, 1h.11m
  ublock-cookies-easylist: 1079-1, 1h.11m
  fanboy-social: 15904-42, 1h.11m
  adguard-popup-overlays: 27141-47, now
  adguard-other-annoyances: 14164-35, now
  easylist-annoyances: 4509-293, 1h.11m
  easylist-notifications: 2966-317, 1h.11m
  ublock-annoyances: 6942-1242, 1h.49m Δ
  [1 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 37621-821, 1h.49m Δ
  ublock-badware: 8360-1, 1h.49m Δ
  ublock-privacy: 832-0, 1h.49m Δ
  ublock-unbreak: 2258-1, 1h.49m Δ
  ublock-quick-fixes: 253-0, 1h.49m Δ
  easylist: 86164-548, 1h.49m Δ
  easyprivacy: 50793-934, 1h.49m Δ
  urlhaus-1: 13565-0, now
  plowe-0: 3737-1, 1h.11m
filterset (user): [array of 18 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2864 ms (selfie)
 maxAssetCacheWait: 260 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  bloomberg.com: 4
  bbthat.com: 1
  google.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 2
  ml314.com: 1
  moatads.com: 1
  newrelic.com: 1
 extended:
  ##.grecaptcha-badge
  ##.adWrapper
  ##.banner
  ###fortress-container-root
  ##div[data-ad-placeholder]
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
bloomberg.com###leaderboard
```

@ryanbr
