### ISSUE TITLE
mobiliteit.nl: breakage

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23418]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mobiliteit.nl/`

### Category

breakage

### Description

Cookie wall is hidden, but still blocks the website. 

ELC + uBO Cookie enabled

Fixed by 
```
mobiliteit.nl##html,body:style(overflow: auto !important)
mobiliteit.nl##body > *:style(filter: none !important)
```

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136954
 cosmetic: 91174
 scriptlet: 24112
 html: 1778
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50958-186, never
  ublock-cookies-easylist: 1079-1, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37758-109, now
  ublock-badware: 8384-0, now
  ublock-privacy: 833-1, now
  ublock-unbreak: 2316-2, now
  ublock-quick-fixes: 200-28, now
  easylist: 86302-174, now
  easyprivacy: 50793-63, now
  urlhaus-1: 13530-0, now
  plowe-0: 3737-1159, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 643 ms
 maxAssetCacheWait: 10 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  mobiliteit.nl: 2
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.advertisement.leaderboard
  ##.advertisement.rectangle
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
```
mobiliteit.nl##html,body:style(overflow: auto !important)
mobiliteit.nl##body > *:style(filter: none !important)
mobiliteit.nl###gdpr-consent
mobiliteit.nl###gdpr-overlay
```

@ryanbr
