### ISSUE TITLE
0.0.0.1: popups

### ISSUE THREAD

**Issue by rlock9** [uBlockOrigin/uAssets#23416]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://0.0.0.1/`

### Category

popups

### Description

Every time I launch a web browser, whether it's Firefox there's always 2 extra tab open up.

The address was 0.0.0.0 and 0.0.0.1
And Ublock origin blocked it

### Other extensions used

Bitwarden,Adam:One,FireFox Relay,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 135111
 cosmetic: 46136
 scriptlet: 19137
 html: 1778
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37758-109, 3h.44m Δ
  ublock-badware: 8384-0, 3h.44m Δ
  ublock-privacy: 833-1, 3h.44m Δ
  ublock-unbreak: 2315-2, 3h.44m Δ
  ublock-quick-fixes: 182-19, 3h.44m Δ
  easylist: 86270-174, 3h.44m Δ
  easyprivacy: 50794-63, 3h.44m Δ
  urlhaus-1: 13565-0, 3h.44m
  plowe-0: 3759-1181, 12d.13h.1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 629 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
The popup could be because of FF version 125: https://www.mozilla.org/en-US/firefox/125.0.2/releasenotes/

> When attempting to launch Firefox while it is already running, an extra blank tab with an address of `https://0.0.0.1` may sometimes appear. The cause of this has been identified and will be resolved in an upcoming release.

**Comment by Yuki2718** [comment]
Related https://github.com/easylist/easylist/issues/19041

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1892612

**Comment by rlock9** [comment]
Thx everyone ill wait for next update. Thx for the quick response.
