### ISSUE TITLE
[nsfw] yandex.kz: detection

### ISSUE THREAD

**Issue by Ramirez1989** [uBlockOrigin/uAssets#23419]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yandex.kz/video/preview/5836652643786974187?source=main_redirect&text=%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE`

### Category

detection

### Description

j

### Other extensions used

kj

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 120
filterset (summary):
 network: 152466
 cosmetic: 66798
 scriptlet: 21911
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 25-0, never
  ublock-filters: 37621-285, 14m Δ
  ublock-badware: 8382-0, 18m Δ
  ublock-privacy: 832-0, 18m Δ
  ublock-unbreak: 2259-0, 18m Δ
  ublock-quick-fixes: 256-0, 23m
  easylist: 86302-579, 18m Δ
  easyprivacy: 50795-811, 14m Δ
  urlhaus-1: 13530-0, 23m
  plowe-0: 3737-0, 23m
  RUS-0: 39387-119, 24m
filterset (user): [array of 25 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 515 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by dimisa-RUAdList** [comment]
YouTube?
