### ISSUE TITLE
joygame.com: popups

### ISSUE THREAD

**Issue by bsrtpc** [uBlockOrigin/uAssets#23426]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.joygame.com//?from=okas?from=okas`

### Category

popups

### Description

every time I open chrome the joygame page opens as the first tab and I can't change it in the settings.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Ekran Görüntüsü (373)](https://github.com/uBlockOrigin/uAssets/assets/167966937/c638308b-0eed-4cb2-a938-1501e2ed0d73)
![Ekran Görüntüsü (372)](https://github.com/uBlockOrigin/uAssets/assets/167966937/e5bfcb43-7eb4-4fea-b39a-15629ab988a4)

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136355
 cosmetic: 55369
 scriptlet: 22025
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37623-292, 1m
  ublock-badware: 8418-0, 1m
  ublock-privacy: 832-0, 1m
  ublock-unbreak: 2259-0, now Δ
  ublock-quick-fixes: 248-0, 1m
  easylist: 86274-580, now Δ
  easyprivacy: 50793-22, now Δ
  urlhaus-1: 13320-0, 1m
  plowe-0: 3737-788, 1m
  TUR-0: 12095-18, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1092 ms
 maxAssetCacheWait: 247 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  admost.com: 1
  googletagmanager.com: 1
 hasUnprocessedRequest: true
 extended:
  ###top-banner
```
</details>

**Comment by mapx-** [comment]
your home page is that joygame crap. 
Change it in chrome settings (exactly in appearance setting).
If you cannot change it maybe your system is infested by some malware. Scan it / clean it.
