### ISSUE TITLE
dev.azure.com: breakage

### ISSUE THREAD

**Issue by jgn-epp** [uBlockOrigin/uAssets#23429]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dev.azure.com/`

### Category

breakage

### Description

When using the Pull Request review page on azure devops, ublock origin is breaking the view of the changes (both when using inline and side by side view). The two files where I have noticed this happening had a lot of comments on them, so maybe this is a clue.

### Other extensions used

none (I disabled all other extensions and it was still happening)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Broken view (comments collapsed for privacy reasons):
![image](https://github.com/uBlockOrigin/uAssets/assets/10708799/36ec382a-35d8-47cb-8ef5-2cb0971968a2)

Corret view when ublock origin disabled (added orange block for privacy reasons):
![image](https://github.com/uBlockOrigin/uAssets/assets/10708799/a281e083-3c28-4fb1-99e4-f8374ff8ecbf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 134978
 cosmetic: 46225
 scriptlet: 20531
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 86300-558, 1h.4m Δ
  easyprivacy: 50796-811, 1h.4m Δ
  plowe-0: 3737-0, now
  ublock-badware: 8418-0, 1h.4m Δ
  ublock-filters: 37623-282, 1h.4m Δ
  ublock-privacy: 832-0, 1h.4m Δ
  ublock-quick-fixes: 248-0, 1h.4m Δ
  ublock-unbreak: 2259-0, 1h.4m Δ
  urlhaus-1: 13320-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1206 ms
 maxAssetCacheWait: 255 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  azure.com: 4
```
</details>

**Comment by mapx-** [comment]
(free) account required ?
provide the completr list of steps to reproduce your issue
