### ISSUE TITLE
get.freecoursesonline.me: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#23422]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [ ] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://get.freecoursesonline.me/?s=javascript&asl_active=1&p_asl_data=1&categoryset[]=3593&categoryset[]=3629&categoryset[]=3674&categoryset[]=605&categoryset[]=1525&categoryset[]=3467&categoryset[]=133&categoryset[]=1147&categoryset[]=663&categoryset[]=4138&categoryset[]=7&categoryset[]=1020&categoryset[]=1024&categoryset[]=1033&categoryset[]=1010&categoryset[]=1205&categoryset[]=2170&categoryset[]=1704&categoryset[]=4&categoryset[]=4593&categoryset[]=1000&categoryset[]=92&categoryset[]=126&categoryset[]=3449&categoryset[]=5737&categoryset[]=5510&categoryset[]=4293&categoryset[]=5479&categoryset[]=3684&categoryset[]=3688&categoryset[]=4849&categoryset[]=5496&categoryset[]=2394&categoryset[]=3635&categoryset[]=426&categoryset[]=2658&categoryset[]=2457&categoryset[]=659&categoryset[]=5&categoryset[]=1136&categoryset[]=2910&categoryset[]=5163&categoryset[]=2434&categoryset[]=5748&categoryset[]=4305&categoryset[]=4409&categoryset[]=1940&customset[]=page&customset[]=post&asl_gen[]=title&qtranslate_lang=0&filters_initial=1&filters_changed=0`

### Category

detection

### Description

scroll down until anti-adblock notice show up, 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/3024ec3b-5a35-4124-b2e4-712ca00859f1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 144947
 cosmetic: 161498
 scriptlet: 34299
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8082-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 203-0, now
  adguard-cookies: 29275-74, now
  adguard-other-annoyances: 14167-349, now
  adguard-popup-overlays: 27152-394, now
  easylist-annoyances: 4514-17, now
  easylist-notifications: 2966-83, now
  fanboy-cookiemonster: 50958-3925, now
  ublock-annoyances: 6943-1129, now
  ublock-cookies-adguard: 1080-0, now
  ublock-cookies-easylist: 1080-1080, now
 default:
  user-filters: 49-0, never
  easylist: 86302-639, now
  easyprivacy: 50796-892, now
  plowe-0: 3737-0, now
  ublock-badware: 8382-1, now
  ublock-filters: 37621-702, now
  ublock-privacy: 832-1, now
  ublock-quick-fixes: 256-1, now
  ublock-unbreak: 2259-2, now
  urlhaus-1: 13530-0, now
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 46 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1979 ms (selfie)
 maxAssetCacheWait: 478 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  freecoursesonline.me: 1
  clarity.ms: 1
  googletagmanager.com: 2
  onesignal.com: 1
  wp.com: 1
 extended:
  ##.generate-back-to-top
  ###ai-adb-ads
  ###ai-adb-sponsors
  ##+js(prevent-fetch, adsbygoogle)
  ##+js(adjust-setInterval)
  ##+js(addEventListener-defuser, load, abDetectorPro)
  ##+js(no-xhr-if, ads)
  ##+js(noeval-if, /chp_?ad/)
  ##+js(adjust-setInterval, /timeLeft|wpsafe-/, *, 0.02)
  ##+js(addEventListener-defuser, load, nextFunction)
```
</details>

**Comment by mapx-** [comment]
it seems to be down

**Comment by mapx-** [comment]
I'm able to reproduce the detection in brave with shields ON.
Be sure to disable any other blocking stuff.
