### ISSUE TITLE
funkeypagali.com: detection

### ISSUE THREAD

**Issue by superislam** [uBlockOrigin/uAssets#23420]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://funkeypagali.com/are-no-code-platforms-the-future-of-software-development/`

### Category

detection

### Description

detection

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 138431
 cosmetic: 61714
 scriptlet: 23862
 html: 2036
listset (total-discarded, last-updated):
 added:
  block-lan: 65-0, now
  ublock-annoyances: 6887-36, 25m Δ
  ara-0: 2327-15, 24m
  easylist-annoyances: 4514-64, now
  easylist-chat: 190-0, now
  easylist-newsletters: 7219-21, now
  easylist-notifications: 2966-162, now
 default:
  user-filters: 8-0, never
  ublock-filters: 37758-109, 25m Δ
  ublock-badware: 8384-0, 25m Δ
  ublock-privacy: 833-1, 25m Δ
  ublock-unbreak: 2316-2, 25m Δ
  ublock-quick-fixes: 184-14, 25m Δ
  easylist: 86302-174, 25m Δ
  easyprivacy: 50796-64, 25m Δ
  urlhaus-1: 13530-0, 24m
  plowe-0: 3737-1159, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-csp-reports: * true
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 661 ms (selfie)
 maxAssetCacheWait: 253 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  clarity.ms: 1
  doubleclick.net: 7
  googlesyndication.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link?

**Comment by superislam** [comment]
Yes, I think it is.

**Comment by mapx-** [comment]
fo shorteners you have to provide the real link.

for help go here: https://github.com/uBlockOrigin/uAssets/discussions/17361
