### ISSUE TITLE
virustotal.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#23432]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.virustotal.com/gui/home/upload`

### Category

nuisance

### Description

Banner prompting to accept terms of use and privacy notice

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![68747470733a2f2f63646e2e616467756172642e696e666f2f736974657265706f7274732f3366667972613178796f736767306f383030303467776b6b736f386373776b6c7a703569793469356f672e706e673f6e633d31](https://github.com/uBlockOrigin/uAssets/assets/101707608/e29b6b0e-b719-4b2d-b7d4-6c9237738501)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 352997
 cosmetic: 254089
 scriptlet: 50419
 html: 2036
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 66576-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 91427-1245, now
  https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt: 918-11, now
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 371-0, now
  adguard-generic: 81033-4719, now
  adguard-mobile: 9266-844, now
  adguard-spyware-url: 1501-235, now
  adguard-spyware: 80338-4900, now
  block-lan: 61-0, now
  curben-phishing: 14197-5, 1h.3m
  adguard-cookies: 29293-46, now
  fanboy-cookiemonster: 50912-3865, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37760-198, now
  ublock-badware: 8420-416, now
  ublock-privacy: 833-66, now
  ublock-unbreak: 2316-3, now
  ublock-quick-fixes: 177-10, now
  easylist: 86300-40809, now
  easyprivacy: 50796-26784, now
  urlhaus-1: 13565-0, 1h.3m
  plowe-0: 3739-2033, now
  GRC-0: 1077-16, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user- https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1
supportStats:
 allReadyAfter: 8038 ms
 maxAssetCacheWait: 4608 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  yahoo.com: 2
 extended:
  ##.grecaptcha-badge
```
</details>

**Comment by mapx-** [comment]
add

`virustotal.com##.alert.hstack`

@ryanbr
