### ISSUE TITLE
drogeriedepot.de: breakage

### ISSUE THREAD

**Issue by sppmasterspp** [uBlockOrigin/uAssets#23439]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.drogeriedepot.de/`

### Category

breakage

### Description

Cosmetic filtering brakes the site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/46223847/3f90fc73-0baf-410b-b109-57c330177c2b)

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 193167
 cosmetic: 213380
 scriptlet: 50841
 html: 2052
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81044-3931, now
  curben-phishing: 14130-2, now
  adguard-cookies: 29342-41, now
  adguard-popup-overlays: 27171-228, now
  adguard-other-annoyances: 14171-291, now
  easylist-annoyances: 4519-278, now
  fanboy-cookiemonster: 50959-3897, now
  ublock-annoyances: 6890-264, 27m Δ
  BGR-0: 1040-7, now
  RUS-0: 39434-681, 27m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 37762-109, 27m Δ
  ublock-badware: 8428-0, 27m Δ
  ublock-privacy: 833-2, 27m Δ
  ublock-unbreak: 2319-2, 27m Δ
  ublock-quick-fixes: 178-10, 27m Δ
  easylist: 86326-1617, 27m Δ
  easyprivacy: 50797-158, 27m Δ
  urlhaus-1: 13370-1, now
  plowe-0: 3737-1171, now
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 colorBlindFriendly: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 881 ms (selfie)
 maxAssetCacheWait: 330 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##div.cookie-consent-popup
```
</details>

**Comment by mapx-** [comment]
add

`drogeriedepot.de#@#div.cookie-consent-popup`

@ryanbr
