### ISSUE TITLE
mcrypto.club: [unknown]

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#23431]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mcrypto.club/bypass.php`

### Category

[unknown]

### Description

n

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 140712
 cosmetic: 59699
 scriptlet: 20670
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 63-1, never
  IDN-0: 9918-2, 1h.34m
  adguard-mobile: 9272-105, 1h.34m
  easylist: 86300-619, 1h.37m Δ
  easyprivacy: 50796-820, 1h.37m Δ
  plowe-0: 3737-0, 1h.34m
  ublock-badware: 8412-0, 1h.37m Δ
  ublock-filters: 37984-367, 1h.37m Δ
  ublock-privacy: 832-0, 1h.37m Δ
  ublock-quick-fixes: 248-0, 1h.37m Δ
  ublock-unbreak: 2263-1, 1h.37m Δ
  urlhaus-1: 13320-0, 1h.34m
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3747 ms (selfie)
 maxAssetCacheWait: 302 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  inmobi.com: 1
 extended:
  ##+js(set-constant, tabSwitched, true)
  ##+js(set-constant, tabSwitchedTime, 0)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(adjust-setTimeout, countdown, 10000)
  ##+js(no-xhr-if, wpadmngr)
  ##+js(prevent-fetch, ad)
  ##+js(trusted-replace-node-text, script, redirectToErrorPage)
  ##+js(addEventListener-defuser, click, _0x)
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
