### ISSUE TITLE
expertvn.com: detection

### ISSUE THREAD

**Issue by GollumArain** [uBlockOrigin/uAssets#23437]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://expertvn.com/`

### Category

detection

### Description

Redirected from `https://go.megafly.in/2dvc62olam`

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/72902553/23cfeb1a-1d06-4f5d-b177-3a4a1f9573c6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 134923
 cosmetic: 46225
 scriptlet: 20530
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 86319-559, 1h.49m Δ
  easyprivacy: 50797-790, 1h.49m Δ
  plowe-0: 3737-0, 4m
  ublock-badware: 8426-0, 1h.49m Δ
  ublock-filters: 37623-282, 1h.49m Δ
  ublock-privacy: 832-2, 1h.49m Δ
  ublock-quick-fixes: 250-1, 1h.49m Δ
  ublock-unbreak: 2262-18, 1h.49m Δ
  urlhaus-1: 13230-0, 4m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 717 ms (selfie)
 maxAssetCacheWait: 207 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  expertvn.com: 3
  doubleclick.net: 1
  exmarketplace.com: 1
  googlesyndication.com: 1
 extended:
  ##+js(set-constant, count, 0)
  ##+js(abort-on-property-read, SMart1)
  ##+js(noeval-if, chp_ad)
  ##+js(remove-node-text, script, deblocker)
```
</details>

**Comment by stephenhawk8054** [comment]
For future shortener sites, please comment in here: https://github.com/uBlockOrigin/uAssets/discussions/17361
