### ISSUE TITLE
frzyc.github.io: ads

### ISSUE THREAD

**Issue by usrahse** [uBlockOrigin/uAssets#23438]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://frzyc.github.io/genshin-optimizer/`

### Category

ads

### Description

still shows ads but not pictures inside of the ad html container

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 134894
 cosmetic: 46126
 scriptlet: 19137
 html: 1778
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37762-109, 5m Δ
  ublock-badware: 8428-0, 5m Δ
  ublock-privacy: 833-2, 5m Δ
  ublock-unbreak: 2319-2, 5m Δ
  ublock-quick-fixes: 179-10, 5m Δ
  easylist: 86320-175, 5m Δ
  easyprivacy: 50797-64, 5m Δ
  urlhaus-1: 13230-0, now
  plowe-0: 3737-1159, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 128 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. You can use this as custom filter:

```adb
frzyc.github.io##.go-ad-wrapper
```

**Comment by solomoncyj** [comment]
its starting to inject lootbar affilate links. should this be pushed to main lists?

**Comment by mapx-** [comment]
```adb
frzyc.github.io##[alt*="Banner"]
frzyc.github.io##[alt*="advertisement"]:upward(1)
frzyc.github.io##[href^="https://lootbar.gg"]:upward(1)
```

**Comment by solomoncyj** [comment]
<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/91703837-b86c-4918-9e31-bc4729aed2bb" />

ads placeholders noe

**Comment by solomoncyj** [comment]
and i cant right click them to use element pucker

**Comment by stephenhawk8054** [comment]
Please always describe the steps to reproduce in details.

**Comment by solomoncyj** [comment]
> Please always describe the steps to reproduce in details.

brave v1.92.134 stock. '

unreproduable on firefox

**Comment by solomoncyj** [comment]
ok ended up being browser specific. i have opned a issue with the browser's github repo: https://github.com/brave/brave-browser/issues/56944
