### ISSUE TITLE
protopage.com: detection

### ISSUE THREAD

**Issue by paulclaude** [uBlockOrigin/uAssets#23430]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.protopage.com/paulclaude`

### Category

detection

### Description

It appears at the bottom of page a banner "Warning icon
You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."
I've create a rule to delete element, the banner disappears but it re-appears on reloading the page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 142691
 cosmetic: 106146
 scriptlet: 27203
 html: 2036
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27152-208, 1m
  adguard-mobile-app-banners: 5149-19, 1m
  adguard-other-annoyances: 14168-293, 1m
  adguard-widgets: 2476-7, 1m
  easylist-annoyances: 4514-268, 1m
  easylist-chat: 190-16, 1m
  easylist-newsletters: 7245-505, 1m
  easylist-notifications: 2966-1521, 1m
  ublock-annoyances: 6887-190, 1m
 default:
  user-filters: 6-0, never
  ublock-filters: 37760-109, 1h.10m Δ
  ublock-badware: 8420-0, 1h.10m Δ
  ublock-privacy: 833-1, 1h.10m Δ
  ublock-unbreak: 2316-2, 1h.10m Δ
  ublock-quick-fixes: 177-10, 1h.10m Δ
  easylist: 86300-174, 1h.10m Δ
  easyprivacy: 50796-64, 1h.10m Δ
  urlhaus-1: 13320-0, 7m
  plowe-0: 3737-1159, now
  ITA-0: 8401-40, 8m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 526 ms (selfie)
 maxAssetCacheWait: 172 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  cloudflareinsights.com: 2
  google-analytics.com: 3
  google.com: 6
  googlesyndication.com: 2
  googletagmanager.com: 2
 extended:
  ###ad-0
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(nobab)
  ##+js(nofab)
  ##+js(adfly-defuser)
  ##+js(abort-on-property-read, pageParams.dispAds)
  ##+js(adjust-setInterval, adv, *)
```
</details>

**Comment by paulclaude** [comment]
> I created an account. No detection on my end. @paulclaude Do I need to take some specific steps to get detection?

Try reloading the page several times. I've no other AD block extensions, only uBlock.

![screenshot-24 04 2024_140143](https://github.com/uBlockOrigin/uAssets/assets/7869862/d9561658-a0cb-4319-b20d-1e063b918478)

**Comment by stephenhawk8054** [comment]
@paulclaude Test again in another Firefox profile with only uBO and its default settings.

---

If I remember correctly, this site needs an account that has been active for a while

**Comment by paulclaude** [comment]
> @paulclaude Test again in another Firefox profile with only uBO and its default settings.
> 
> If I remember correctly, this site needs an account that has been active for a while

Yes you need an account

**Comment by paulclaude** [comment]
> @paulclaude Test again in another Firefox profile with only uBO and its default settings.

Yes, it works correctly on a new profile with only uBlock. I must delete one by one each extensions, to detect the wrong one...

Maybe one of these extension is known to give those kind of problems...?

1Password extension (desktop app required)
404 Bookmarks
Add-ons Search Detection
Amazon.it
AutoFill Forms
AutoFormer+
Bing
Chiudi le schede a destra
Container Tab Groups
Disable JavaScript
Downloader for Instagram™
DuckDuckGo
DuckDuckGo Privacy Essentials
Easy Youtube Video Downloader Express
eBay
Enhancer for YouTube™
Enpass Password Manager
Firefox Multi-Account Containers
Google
I still don't care about cookies
Imagus
New Tab Suspender
OneTab
PDF Mage
Private Bookmarks
Qwant
Reload in address bar
save-as-pdf-from-context-menu
Search by Image
Show me the password!
Simple Form Fill
Swift Selection Search
Tab Flag
Tab Reloader (page auto refresh)
Turbo Download Manager (3rd edition)
TWP - Translate Web Pages
uBlock Origin
Undo Close Tab
Video Downloader professional
Video DownloadHelper
WebToPDF
Wikipedia (it)
Windscribe - Free Proxy and Ad Blocker
YouTube Video Downloader/YouTube HD Download
