### ISSUE TITLE
rsts.cz: breakage

### ISSUE THREAD

**Issue by uzivatel457** [uBlockOrigin/uAssets#23441]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rsts.cz/`

### Category

breakage

### Description

I cant scroll web page, because ublock block "Používání cookies" pop up window. when disable uBL, this pop up shows and than page is normal behaviour

### Other extensions used

overlay disable, ghostery, cookie autodelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obrazek](https://github.com/uBlockOrigin/uAssets/assets/97152224/ccf6a095-c973-4955-beb1-9d037c90da5a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 146529
 cosmetic: 203005
 scriptlet: 32485
 html: 2037
listset (total-discarded, last-updated):
 added:
  adguard-social: 22861-47, now
  fanboy-thirdparty_social: 68-3, now
  fanboy-cookiemonster: 50959-184, now
  fanboy-social: 15854-733, now
  ublock-annoyances: 6890-65, 1h.33m Δ
  adguard-cookies: 29342-3737, now
  adguard-popup-overlays: 27174-1100, now
  adguard-mobile-app-banners: 5156-23, now
  adguard-other-annoyances: 14172-475, now
  adguard-widgets: 2476-14, now
  easylist-annoyances: 4521-298, now
  easylist-chat: 191-16, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 19-2, never
  ublock-filters: 37762-109, 1h.33m Δ
  ublock-badware: 8428-0, 1h.33m Δ
  ublock-privacy: 833-2, 1h.33m Δ
  ublock-unbreak: 2319-2, 1h.33m Δ
  easylist: 86326-175, 1h.33m Δ
  easyprivacy: 50797-63, 1h.33m Δ
  urlhaus-1: 13370-1, now
  plowe-0: 3737-1159, now
  CZE-0: 833-11, now
  ublock-quick-fixes: 178-14, 1h.33m Δ
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 927 ms (selfie)
 maxAssetCacheWait: 257 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  giant4.cz: 2
  googletagmanager.com: 1
 extended:
  ##.SocialList
  ##.gc-App
```
</details>

**Comment by mapx-** [comment]
add

`rsts.cz#@#.gc-App`

@ryanbr
