### ISSUE TITLE
app.polyas.com: breakage

### ISSUE THREAD

**Issue by pnh-priorit** [uBlockOrigin/uAssets#23440]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://app.polyas.com/VGWort/
https://app.polyas.com/VGWort/admin
```

### Description

While ublock is active the site won't load anything and remains white. 

### Other extensions used

Awesome Screen Recorder & Screenshot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-04-25 12_37_03-app polyas com_VGWort_](https://github.com/uBlockOrigin/uAssets/assets/168085523/cf77504b-6153-4d37-a4bc-20e27c12afc8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 114
filterset (summary):
 network: 137394
 cosmetic: 51265
 scriptlet: 20531
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7408-1, 3h.40m
  easylist: 86324-568, 1h.41m Δ
  easyprivacy: 50797-820, 1h.41m Δ
  plowe-0: 3736-0, 3d.5h.25m
  ublock-badware: 8426-1, 1h.41m Δ
  ublock-filters: 37631-298, 1h.41m Δ
  ublock-privacy: 832-0, 1h.41m Δ
  ublock-quick-fixes: 249-0, 1h.41m Δ
  ublock-unbreak: 2262-2, 1h.41m Δ
  urlhaus-1: 13370-0, 3h.40m
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 749 ms (selfie)
 maxAssetCacheWait: 219 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
add

`/vgwort/*$badfilter`

@ryanbr
