### ISSUE TITLE
whatismyip.com: breakage

### ISSUE THREAD

**Issue by bwest2397** [uBlockOrigin/uAssets#23446]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.whatismyip.com/`

### Category

breakage

### Description

Website appears to load correctly at first, then goes blank/white. It seems `<div id="___gatsby">` gets all of its children cleared out shortly after loading. This does not happen when uBlock Origin is disabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 135028
 cosmetic: 46228
 scriptlet: 20534
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86320-559, now
  easyprivacy: 50795-811, now
  plowe-0: 3737-0, now
  ublock-badware: 8421-0, now
  ublock-filters: 37635-283, now
  ublock-privacy: 832-0, now
  ublock-quick-fixes: 250-0, now
  ublock-unbreak: 2262-0, now
  urlhaus-1: 13340-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3176 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  doubleclick.net: 2
  google.com: 3
  googletagmanager.com: 1
  primis.tech: 3
  yieldlove.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||cdn-a.yieldlove.com/*/yieldlove.js?whatismyip.com$script,domain=whatismyip.com`

@ryanbr

**Comment by bwest2397** [comment]
@mapx- That seems to do the trick 👍
