### ISSUE TITLE
dr-beckmann.com: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#23454]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://pl.dr-beckmann.com/nasze-produkty/detail/tluszcz-i-sosy/
```

### Description

Breakage by generic block `||usercentrics.eu^$3p` from ELC - I can not watch embeded video in gallery (black screen of death).

I guess page need minimum `trusted-set-local-storage` with 1 of record in "`uc_settings`":

<details> <summary> long table as value </summary>

`{"controllerId":"confidental","id":"confidental","language":"pl","services":[{"history":[{"action":"onInitialPageLoad","language":"pl","status":true,"timestamp":1714069767989,"type":"implicit","versions":{"application":"SDK-4.35.0","service":"40.17.44","settings":"52.33.140"}},{"action":"onUpdateServices","language":"pl","status":true,"timestamp":1714069782758,"type":"explicit","versions":{"application":"SDK-4.35.0","service":"40.17.44","settings":"52.33.140"}}],"id":"confidental","processorId":"confidental","status":true},{"history":[{"action":"onInitialPageLoad","language":"pl","status":true,"timestamp":1714069767989,"type":"implicit","versions":{"application":"SDK-4.35.0","service":"10.3.1","settings":"52.33.140"}},{"action":"onUpdateServices","language":"pl","status":true,"timestamp":1714069782758,"type":"explicit","versions":{"application":"SDK-4.35.0","service":"10.3.1","settin`

</details>

Unless someone knows how to disarm it with basic redirects and scriptlets.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

* BSoD:

   ![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/101bf731-8968-4edf-bcab-eb37dd40eeb7)

* Cookie wall in gallery (translated on screen by Mozilla Team machine learning):

   ![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/806a4a4c-40b3-4356-949b-5d4cfb65d1bb)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBo 1.57.3b6

enabled stock + uBo Annoyances + ELC + POL-0 and POL-2

```
</details>

**Comment by mapx-** [comment]
test

`dr-beckmann.com##+js(trusted-click-element, #usercentrics-root >>> button[data-testid="uc-deny-all-button"])`
