### ISSUE TITLE
kleinanzeigen.de: detection

### ISSUE THREAD

**Issue by qSebastiaNp** [uBlockOrigin/uAssets#23450]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kleinanzeigen.de/p-anzeige-bearbeiten.html`

### Category

detection

### Description

To test, you need to have a working kleinanzeigen.de account.
Create an item if you don't have one, then try to edit it. The save button will not work while uBlock is active.
May have to do with prebid.org adblock detection.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 137343
 cosmetic: 51171
 scriptlet: 19136
 html: 1782
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37766-109, 5m
  ublock-badware: 8423-0, 5m
  ublock-privacy: 833-2, 5m
  ublock-unbreak: 2319-2, 5m
  ublock-quick-fixes: 179-11, 5m
  easylist: 86343-175, 5m
  easyprivacy: 50796-64, 5m
  urlhaus-1: 13340-0, 23m
  plowe-0: 3737-1159, 5m
  DEU-0: 7408-37, 23m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 50 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 542 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  kleinanzeigen.de: 3
  bing.com: 1
  creativecdn.com: 1
  criteo.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googleadservices.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
  online-metrix.net: 1
```
</details>

**Comment by mapx-** [comment]
@qSebastiaNp we need an account in order to investigate your issue. 
Are you willing to share your credentials account with us ? (I'll provide an email address if you agree)
