### ISSUE TITLE
breakage: reuters.com

### ISSUE THREAD

**Issue by vikingnope** [uBlockOrigin/uAssets#23455]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.reuters.com/
```

### Description

Same issue as before where a text box becomes overlapping when fullscreened with uBlockOrigin turned on https://github.com/uBlockOrigin/uAssets/issues/23365

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/e6e540da-8584-48d7-b020-7b942eae2527)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 135037
 cosmetic: 46136
 scriptlet: 19136
 html: 1779
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37763-109, 1h.10m Δ
  ublock-badware: 8428-0, 1h.10m Δ
  ublock-privacy: 833-2, 1h.10m Δ
  ublock-unbreak: 2319-2, 1h.10m Δ
  ublock-quick-fixes: 179-11, 1h.10m Δ
  easylist: 86331-175, 1h.10m Δ
  easyprivacy: 50801-64, 1h.10m Δ
  urlhaus-1: 13370-1, 9h.17m
  plowe-0: 3736-1159, 5d.3h.53m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 299 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue in the old thread. All volunteers are notified with new connects. No need to open duplicated issue.
