### ISSUE TITLE
nepu.to: popups

### ISSUE THREAD

**Issue by TheBoguette** [uBlockOrigin/uAssets#23453]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nepu.to/`

### Category

popups

### Description

The website keeps showing overlays that randomly popup and sometimes redirects you to other pages when clicking on website elements like search bars or icons.

### Other extensions used

Dark Reader
Picture in Picture Viewer
Thorium Scrollbars
Violentmonkey (not used on webpage)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/78265370/81689c4e-f02b-4d8c-95f8-9235adeaa638)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 141096
 cosmetic: 99716
 scriptlet: 28842
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-mobile-app-banners: 5155-1103, 58m
  adguard-other-annoyances: 14173-351, 58m
  adguard-popup-overlays: 27180-882, 58m
  adguard-widgets: 2478-39, 58m
  easylist-annoyances: 4521-16, 58m
  easylist-chat: 191-0, 58m
  easylist-newsletters: 7259-12, 58m
  easylist-notifications: 2969-82, 58m
  ublock-annoyances: 6947-55, now Δ
 default:
  easylist: 86331-635, 1h Δ
  easyprivacy: 50801-896, 1h Δ
  plowe-0: 3737-0, now
  ublock-badware: 8426-0, 1h Δ
  ublock-filters: 37632-606, 1h Δ
  ublock-privacy: 832-1, 1h Δ
  ublock-quick-fixes: 251-0, 1h Δ
  ublock-unbreak: 2262-2, 1h Δ
  urlhaus-1: 13340-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 825 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 network:
  nepu.to: 9
  220t.com: 1
  aliexpress.com: 1
  cloudflare.com: 6
  download-adblock360.com: 1
  googletagmanager.com: 1
  starmobmedia.com: 2
  trackingrouter.com: 1
  trackmyorderz.com: 1
  veeqlly.com: 1
  wargaming-aff.com: 1
  youradexchange.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@mapx- unstable. Try

```
!#if cap_html_filtering
totalsportek.to,eztvx.to##^script:has-text(adserverDomain)
!#endif
/^https:\/\/[a-z]{7}\.com\/[0-9a-h]{1,15}\?[0-9a-zA-Z]{1,15}=[0-9a-zA-Z]{300,1300}(?:%3D){0,2}$/$xhr,3p,match-case,domain=totalsportek.to|eztvx.to|nepu.to
||nepu.to/z-yrdunxrcy4
```
