### ISSUE TITLE
kinox.to

### ISSUE THREAD

**Issue by smed79** [uBlockOrigin/uAssets#2346]
### URL(s) where the issue occurs

`https://kinox.to/`

### Describe the issue

popup

### filters

```
||35.184.188.211^$popup
kinox.to,kinos.to,kinox.tv,kinox.me,kinox.si,kinox.io,kinox.sx,kinox.am,kinox.nu,kinox.sg##script:inject(nowebrtc.js)
```

**Comment by mapx-** [comment]
I tested 3-4 sites, I get no popup.

**Comment by KiLL4FuNK** [comment]
I get no popup.

**Comment by okiehsch** [comment]
The filter `kinox.*##script:inject(abort-current-inline-script.js, adcashMacros)` is part of `uBO-filters` and disables those popups.
If I add `kinox.*#@#script:inject(abort-current-inline-script.js, adcashMacros)` I can reproduce.

**Comment by okiehsch** [comment]
I can reproduce the popup at `kinos.to`
