### ISSUE TITLE
vipurl.in: detection

### ISSUE THREAD

**Issue by PREETCHAUHAN** [uBlockOrigin/uAssets#23461]
### Prerequisites

- [ ] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vipurl.in/0wzCj1Dp`

### Category

detection

### Description

not working

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/33035404/3b422438-be00-4c11-8645-0879210406de)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 326147
 cosmetic: 373964
 scriptlet: 57223
 html: 0
listset (total-discarded, last-updated):
 added:
  ALB-0: 305-0, now
  BGR-0: 1040-1, now
  CHN-0: 25490-149, now
  CZE-0: 832-2, now
  DEU-0: 7411-0, now
  EST-0: 464-1, never
  FIN-0: 2275-0, never
  FRA-0: 24407-90, never
  GRC-0: 1077-0, never
  HRV-0: 388-2, never
  HUN-0: 2103-3, never
  IDN-0: 9920-2, never
  [47 lists not shown]: [too many]
 default:
  user-filters: 5-0, never
  easylist: 86364-1341, never
  easyprivacy: 50797-609, never
  plowe-0: 3737-1334, never
  ublock-badware: 8421-32, never
  ublock-filters: 37638-881, never
  ublock-privacy: 832-120, never
  ublock-quick-fixes: 250-4, never
  ublock-unbreak: 2265-46, never
  urlhaus-1: 13180-0, never
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 17 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 897 ms (selfie)
 maxAssetCacheWait: 152 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  vipurl.in: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 extended:
  ##.banner-468x60
  ###cookie-pop
  ##.cookie-message:not(html):not(body)
  ##div.cookie-message
  ##.cookie-confirm
  ##div.cookie-confirm
```
</details>

**Comment by mapx-** [comment]
- reset uBO to defaults, don't use any other non-default filter lists or blocking stuff
- in the future for such horrible shorteners ask for help directly here: https://github.com/uBlockOrigin/uAssets/discussions/17361
