### ISSUE TITLE
priuschat.com: breakage

### ISSUE THREAD

**Issue by doctorman** [uBlockOrigin/uAssets#23466]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://priuschat.com/threads/add-remote-start-to-your-prius-v-using-factory-fob-for-150.202465/`

### Category

breakage

### Description

the link to product posted by user is removed by block as if it is an ad

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 140417
 cosmetic: 125345
 scriptlet: 28847
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-other-annoyances: 14173-8, now
  adguard-popup-overlays: 27195-118, now
  fanboy-cookiemonster: 50962-205, now
  ublock-cookies-easylist: 1083-0, now
 default:
  user-filters: 7-1, never
  easylist: 86567-510, 1h.38m Δ
  easyprivacy: 50798-811, 1h.38m Δ
  plowe-0: 3734-0, now
  ublock-badware: 8425-0, 1h.38m Δ
  ublock-filters: 37657-725, 1h.38m Δ
  ublock-privacy: 832-0, 1h.38m Δ
  ublock-quick-fixes: 259-0, 1h.38m Δ
  ublock-unbreak: 2265-0, 1h.38m Δ
  urlhaus-1: 13180-0, 38m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 308 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4392 ms (selfie)
 maxAssetCacheWait: 444 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  amazon-adsystem.com: 8
  facebook.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  quantserve.com: 1
  skimresources.com: 1
  youtube.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/\{"brs_content_label":[^,]…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-set-cookie, datr, __GMZCgwVF5BbyvAtfJojQwg, 1year,…
  ##+js(addEventListener-defuser, scroll, showPopup)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot exactly what are blocked? Do you need an account and sign in to reproduce the issue?
