### ISSUE TITLE
uhdmovies.eu: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#23465]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uhdmovies.eu/download-goodbye-earth-2024-season-1-hindi-1080p/`

### Category

popups

### Description

.

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 136286
 cosmetic: 54298
 scriptlet: 19218
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38152-110, 39m Δ
  ublock-badware: 8421-0, 39m Δ
  ublock-privacy: 833-2, 39m Δ
  ublock-unbreak: 2326-2, 39m Δ
  ublock-quick-fixes: 188-23, 39m Δ
  adguard-mobile: 9272-60, now
  easylist: 86567-233, 39m Δ
  easyprivacy: 50798-72, 39m Δ
  urlhaus-1: 13180-0, 39m
  plowe-0: 3734-1233, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2193 ms (selfie)
 maxAssetCacheWait: 177 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  doubleclick.net: 4
  googletagmanager.com: 1
  hippianwispily.com: 2
  youtube.com: 8
 extended:
  ##.gridlove-ad
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune-fetch-response, overlay, overlay.shortsAdsRende…
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_sig_bit_dea, …
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||uhdmovies.eu/axwinpop.js
```

@ryanbr
