### ISSUE TITLE
adblock detected

### ISSUE THREAD

**Issue by irishwo1f** [uBlockOrigin/uAssets#23460]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://drake-scans.com/
```

### Description

AdBlock is detected, and site access is denied until it is disabled.
This is the case on both Google Chrome and Edge at the very least.

### Other extensions used

Grammarly
7TV
FrankerFaceZ
BetterTTV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-26 080707](https://github.com/uBlockOrigin/uAssets/assets/168141819/fdc2b70f-15a0-4f6f-bff1-d6f2de333e25)
![Screenshot 2024-04-26 080733](https://github.com/uBlockOrigin/uAssets/assets/168141819/916a1d96-f852-4ac6-a230-abdef64a03fd)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 135061
 cosmetic: 46238
 scriptlet: 20533
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86361-559, 9h.1m
  easyprivacy: 50796-811, 9h.1m
  plowe-0: 3737-0, 9h.1m
  ublock-badware: 8421-0, 9h.1m
  ublock-filters: 37635-283, 9h.1m
  ublock-privacy: 832-0, 9h.1m
  ublock-quick-fixes: 250-0, 1h.1m
  ublock-unbreak: 2262-0, 9h.1m
  urlhaus-1: 13340-0, 9h.1m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 818 ms (selfie)
 maxAssetCacheWait: 236 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  bidgear.com: 1
  googlesyndication.com: 2
  netpub.media: 2
  wp.com: 1
 extended:
  ##.ad_sidebar
  ##.housead
  ##.advertisment
  ##.top_adv
  ##.adslist
  ##.advertorial
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]

```
</details>

**Comment by mapx-** [comment]
already fixed
https://github.com/uBlockOrigin/uAssets/commit/cc4e65e95dd6cd4e773ab1f73a04aab34910f1fc

update using
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1
