### ISSUE TITLE
thewire.in: ads leftovers

### ISSUE THREAD

**Issue by pritkr** [uBlockOrigin/uAssets#23462]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thewire.in/law/sc-warns-against-publicising-evm-source-code-but-what-does-it-mean`

### Category

ads

### Description

Ad leftover space, it can be more effectively used in sidebar, end of article and header, I have given some example screenshots. The following filter I tested but you can choose more effective ones 
```adblock-filter-list
###ATD_SB1
###ATD_EOA
###ATD_LB
``` 

### Other extensions used

Bitwarden, wappalyzer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/81620727/b1941d74-e354-4e2b-99a5-a28cf2ce1826)
![image](https://github.com/uBlockOrigin/uAssets/assets/81620727/2ddd5f3b-e784-40e6-b21f-46ddcf36de45)
![image](https://github.com/uBlockOrigin/uAssets/assets/81620727/538b9315-88a3-468c-af6e-a5be46a71c0c)
![image](https://github.com/uBlockOrigin/uAssets/assets/81620727/4faf1323-3e24-4bdd-85f3-cb0532856091)
![image](https://github.com/uBlockOrigin/uAssets/assets/81620727/e29e5906-331e-4336-b50c-9099e10659a4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 134904
 cosmetic: 46241
 scriptlet: 20543
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37641-283, now
  ublock-badware: 8421-0, now
  ublock-privacy: 832-0, now
  ublock-unbreak: 2265-0, now
  ublock-quick-fixes: 256-0, now
  easylist: 86364-558, now
  easyprivacy: 50797-811, now
  urlhaus-1: 13180-0, 1m
  plowe-0: 3734-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1491 ms (selfie)
 maxAssetCacheWait: 356 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  automatad.com: 1
  dwcdn.net: 1
  googletagmanager.com: 1
  taboola.com: 1
  twitter.com: 4
 extended:
  ###taboola-below-article-thumbnails
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by mapx-** [comment]
enable the indian list and report the issue at their repo: https://github.com/mediumkreation/IndianList/issues
