### ISSUE TITLE
hepsiburada.com: breakage

### ISSUE THREAD

**Issue by lostnt1** [uBlockOrigin/uAssets#23476]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hepsiburada.com/dv/cok-konusturan-firsatlar?forMobileApp=true&trackingId=232771`

### Category

breakage

### Description

Via uBlockOrigin Products images broken like below images.

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With Ublock Origin
![Screenshot_20240428_115424_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/136184400/4755c619-8414-4ac1-9707-bcf93dbce645)

Without uBlock Origin

![Screenshot_20240428_115436_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/136184400/441c1b95-8858-4866-86c0-dd44debc9b24)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 143009
 cosmetic: 131506
 scriptlet: 28150
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1504-119, now
  adguard-cookies: 29369-50, now
  ublock-cookies-adguard: 1122-0, now
  fanboy-cookiemonster: 50976-3878, now
  ublock-cookies-easylist: 1122-1122, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38042-449, 1h.51m Δ
  ublock-badware: 8421-0, 1h.51m Δ
  ublock-privacy: 832-0, 1h.51m Δ
  ublock-unbreak: 2267-1, 1h.51m Δ
  ublock-quick-fixes: 253-0, 1h.51m Δ
  adguard-mobile: 9294-97, now
  easylist: 86888-533, 1h.51m Δ
  easyprivacy: 50823-823, 1h.51m Δ
  urlhaus-1: 13140-0, now
  plowe-0: 3735-0, now
  TUR-0: 12115-15, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1341 ms (selfie)
 maxAssetCacheWait: 242 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by J3ekir** [comment]
```
! https://github.com/uBlockOrigin/uAssets/blob/0515cba6fd4388682e326d00e1efb88f2bd428b5/templates/easylist-cookies.template#L8
! https://github.com/easylist/easylist/blob/151c1e5c7672cdfd28f24a73ac4665d77bedcf53/easylist_cookie/easylist_cookie_general_block.txt#L765
@@||images.hepsiburada.net/assets/tools/onetrust/onetrust-autoblock-head.v10.js$script,domain=www.hepsiburada.com
```

**Comment by punisher018** [comment]
`https://www.hepsiburada.com/corsair-vengeance-rgb-32gb-2x16gb-6000mhz-ddr5-cl36-amd-expo-dual-kit-ram-cmh32gx5m2e6000z36-pm-HBC00005OAWJR`

"Ru Adlist" breaks them

<details><summary>Configuration</summary>
<p>

uBlock Origin: 1.66.2
Chromium: 140
filterset (summary):
 network: 180400
 cosmetic: 71814
 scriptlet: 28406
 html: 0
listset (total-discarded, last-updated):
 added:
  RUS-0: 41580-28, now
  RUS-1: 1823-7, now
 default:
  user-filters: 0-0, never
  TUR-0: 10932-86, now
  easylist: 80065-378, now
  easyprivacy: 54559-862, now
  plowe-0: 3429-1, now
  ublock-badware: 10987-61, now
  ublock-filters: 41088-304, now
  ublock-privacy: 3500-27, now
  ublock-quick-fixes: 312-0, 6m
  ublock-unbreak: 2681-37, now
  urlhaus-1: 31600-5, 6m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 145 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  hepsiburada.com: 21
  ads-twitter.com: 1
  debugbear.com: 1
  doubleclick.net: 1
  featuregates.org: 3
  go-mpulse.net: 2
  go2sdk.com: 1
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 2
  hepsiburada.net: 3
  pinimg.com: 1
  statsigapi.net: 4
  webtrekk.net: 1
 extended:
  ##.Advertisement
  ##div[id^="Advertisement_"]
  ##div[data-test-id="sponsored-products"]
  ##.google-ad:not(.testAd)
  #@#.google-ad

</p>
</details> 

<details><summary>Details</summary>
<p>

Ublock Active
![Image](https://github.com/user-attachments/assets/926447cd-5a46-4d2e-8be9-21593c3e3ed5)

Ublock Inactive
![Image](https://github.com/user-attachments/assets/362c8416-b522-45e9-81b5-9a3e4a6381fe)

</p>
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||net/banners/`.

@dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/55b633b4bf3e05b40faa0bdc9515b318fbef36aa
