### ISSUE TITLE
timeanddate.com: detection

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#23472]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.timeanddate.com/date/durationresult.html?d1=1&m1=1&y1=2000&d2=1&m2=1&y2=1999&ti=on`

### Category

detection

### Description

The page occasionally shows a popup when it detects uBlock Origin. From my testing, it only appears after you use the site for a bit, then it doesn't appear again for the rest of the session.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1417" alt="Screenshot 2024-04-27 at 08 59 52" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/6ebf7531-983b-439f-8d34-33c17a140a43">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 117
filterset (summary):
 network: 137041
 cosmetic: 72612
 scriptlet: 21744
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29376-32, now
 default:
  user-filters: 75-0, never
  easylist: 86596-45, 1h Δ
  easyprivacy: 50801-17, 1h Δ
  plowe-0: 3734-1159, now
  ublock-badware: 8425-16, 1h Δ
  ublock-filters: 37665-373, 1h Δ
  ublock-privacy: 832-5, 1h Δ
  ublock-quick-fixes: 259-22, 1h Δ
  ublock-unbreak: 2265-32, 1h Δ
  urlhaus-1: 13220-0, now
filterset (user): [array of 77 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 143 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 5
 network:
  amazon-adsystem.com: 1
  btloader.com: 1
  doubleclick.net: 1
  quantcast.com: 1
  quantserve.com: 1
 extended:
  ###ad-wrap
  ###ad-wrap2
  ###ad1
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
timeanddate.com##+js(aeld, load, ad-wrap)
```

**Comment by Zephiii** [comment]
I'll report if it shows up again. It doesn't show up all the time so it might take me a while to notice it again.

**Comment by stephenhawk8054** [comment]
You can clear the site's cookies and data. It would be easier to reproduce.

**Comment by ghost** [comment]
I got detected.

https://github.com/user-attachments/assets/160698b3-72c2-488e-8a9c-b2924358bd2d

<details>

```
uBlock Origin: 1.65.0
Firefox: 141
filterset (summary):
 network: 162523
 cosmetic: 109704
 scriptlet: 33642
 html: 2363
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 34741-74, 4d.23h.22m
  ublock-cookies-adguard: 5031-73, 4d.23h.22m
  fanboy-cookiemonster: 45965-3861, 4d.23h.22m
  ublock-cookies-easylist: 5031-5031, 4d.23h.22m
 default:
  user-filters: 53-1, never
  ublock-filters: 40716-82, 8m Δ
  ublock-badware: 11369-18, 8m Δ
  ublock-privacy: 3352-9, 8m Δ
  ublock-unbreak: 2726-19, 8m Δ
  ublock-quick-fixes: 296-13, 8m Δ
  easylist: 76363-212, 8m Δ
  easyprivacy: 54365-24, 8m Δ
  urlhaus-1: 33810-0, 9h.5m
  plowe-0: 3419-899, 4d.23h.22m
  ROU-1: 1487-36, 1d.22h.51m
filterset (user): [array of 48 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 310 ms (selfie)
 maxAssetCacheWait: 170 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  amazon-adsystem.com: 1
  btloader.com: 1
  criteo.com: 1
  doubleclick.net: 1
  google.com: 2
  inmobi.com: 1
 extended:
  ###ad-wrap
  ###ad-wrap2
  ###ad1
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
```

</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` list.

**Comment by Chathund** [comment]
The domains `timeanddate.de` and `timeanddate.no` are also affected. I can reproduce the popup by accessing the webpage and then reloading it three times. Adding both domains to the existing filter rule works for me.
