### ISSUE TITLE
[nsfw] cinepiroca.com: detection

### ISSUE THREAD

**Issue by Innerbeard** [uBlockOrigin/uAssets#23486]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://cinepiroca.com/ [nsfw]
```

### Description

Anti-Adblocker prevents use of website

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 130211
 cosmetic: 269733
 scriptlet: 53102
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98448-98439, 20h.24m
  NLD-0: 2772-12, 20h.24m
  RUS-0: 39403-50, 1h.47m Δ
  adguard-cookies: 29342-84, 3d.19h.16m
  adguard-generic: 81078-5629, 3d.19h.16m
  adguard-mobile-app-banners: 5155-1104, 3d.19h.16m
  adguard-other-annoyances: 14171-395, 3d.19h.16m
  adguard-popup-overlays: 27171-2037, 3d.19h.16m
  adguard-social: 22860-894, 3d.19h.16m
  adguard-widgets: 2476-55, 3d.19h.16m
  easylist-annoyances: 4529-34, 20h.24m
  easylist-chat: 191-0, 20h.24m
  [8 lists not shown]: [too many]
 default:
  user-filters: 291-11, never
  easylist: 86770-327, 1h.47m Δ
  ublock-badware: 8427-0, 1h.47m Δ
  ublock-filters: 37690-431, 1h.47m Δ
  ublock-privacy: 832-0, 1h.47m Δ
  ublock-quick-fixes: 262-0, 1h.47m Δ
  ublock-unbreak: 2264-0, 1h.47m Δ
  urlhaus-1: 13140-0, 20h.24m
filterset (user): [array of 291 redacted]
trustedset:
 added: [array of 35 redacted]
switchRuleset:
 added: [array of 12 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1141 ms (selfie)
 maxAssetCacheWait: 541 ms
 cacheBackend: indexedDB

**Comment by Innerbeard** [comment]
I just checked after restarting Chrome and the problem persists, the website detects adblock and puts an overlay. Is there anything other i should do maybe?

**Comment by stephenhawk8054** [comment]
Wait about 5-6 hours and update the filter lists again. Or you can use this filter in the meantime

```adb
cinepiroca.com##+js(noeval-if, /chp_?ad/)
```

**Comment by Innerbeard** [comment]
Okay, noted. Thanks for the manual filter, it did the trick.
