### ISSUE TITLE
blog.workedbd.com: ads

### ISSUE THREAD

**Issue by rajarshikhatua100** [uBlockOrigin/uAssets#23483]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://blog.workedbd.com/`

### Category

ads

### Description

showing ads on the page

### Other extensions used

FastForward, I still don't care about cookies, LocalCDN, Trocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (484)](https://github.com/uBlockOrigin/uAssets/assets/77912617/312e984d-b8b3-4a30-bc56-cfaddf4895df)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 126
filterset (summary):
 network: 134759
 cosmetic: 46664
 scriptlet: 20572
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86770-557, 2h Δ
  easyprivacy: 50823-811, 2h Δ
  plowe-0: 3735-0, now
  ublock-badware: 8427-0, 2h Δ
  ublock-filters: 37691-301, 2h Δ
  ublock-privacy: 832-0, 2h Δ
  ublock-quick-fixes: 262-0, 2h Δ
  ublock-unbreak: 2264-0, 2h Δ
  urlhaus-1: 13010-0, 2h
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 544 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  a-ads.com: 1
  doubleclick.net: 1
  googletagmanager.com: 2
  r2b2.io: 6
```
</details>

**Comment by BlazeFTL** [comment]
For
https://github.com/uBlockOrigin/uAssets/blob/f623fea52388d1f83bf93a9406cb18debdd0d1ba/filters/ubo-link-shorteners.txt#L949

**Comment by mapx-** [comment]
- missing original shortener link
- ask for help (providing the original link) here: https://github.com/uBlockOrigin/uAssets/discussions/17361
