### ISSUE TITLE
coinscap.info: [unknown]

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#23488]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://coinscap.info/blog/xrp-and-xlm-blast-analysts-20x-rally-projection-to-melt-faces/`

### Category

[unknown]

### Description

next button not work

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 140244
 cosmetic: 60167
 scriptlet: 20717
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 74-1, never
  IDN-0: 9920-2, 23m
  adguard-mobile: 9299-105, 23m
  easylist: 86825-620, 23m
  easyprivacy: 50825-820, 23m
  plowe-0: 3735-0, 23m
  ublock-badware: 8442-0, 23m
  ublock-filters: 38053-387, 23m
  ublock-privacy: 832-0, 23m
  ublock-quick-fixes: 262-0, 23m
  ublock-unbreak: 2267-1, 23m
  urlhaus-1: 12680-0, 23m
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 27 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1868 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  coinscap.info: 2
  bmcdn6.com: 7
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  netpub.media: 2
  r2b2.io: 4
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
```
</details>

**Comment by mapx-** [comment]
- it looks to be some page for shorteners => you didn't provide the original link
- I already told you to ask for help here (but **provide the original link**): https://github.com/uBlockOrigin/uAssets/discussions/17361
