### ISSUE TITLE
minitool.com: ads

### ISSUE THREAD

**Issue by KenaiTheWolf** [uBlockOrigin/uAssets#23480]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.minitool.com/partition-disk/windows-not-assigning-drive-letter.html`

### Category

ads

### Description

Banner ads at the bottom of the page are still displayed.

### Other extensions used

Native HLS Playback
Facebook Containers
Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/19823127/c350f66a-eef5-44a4-9b58-33108834a48b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 134730
 cosmetic: 46562
 scriptlet: 19170
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37818-109, 16m Δ
  ublock-badware: 8429-0, 16m Δ
  ublock-privacy: 833-2, 16m Δ
  ublock-unbreak: 2321-2, 16m Δ
  ublock-quick-fixes: 191-25, 16m Δ
  easylist: 86770-174, 16m Δ
  easyprivacy: 50823-64, 16m Δ
  urlhaus-1: 13010-0, now
  plowe-0: 3735-1158, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 258 ms (selfie)
 maxAssetCacheWait: 93 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  dwin1.com: 1
  fuseplatform.net: 2
  googletagmanager.com: 1
  linkconnector.com: 1
 extended:
  ##.page-top-ads
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. You can add this as custom filter

```adb
minitool.com##.promotions-banner-wrap
```
