### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by webhunted** [uBlockOrigin/uAssets#23496]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://twitter.com/home`

### Category

breakage

### Description

The 3 dots next to the posts are missing when the extension is enabled. When disabled they appear again.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Enabled: ![image](https://github.com/uBlockOrigin/uAssets/assets/151805876/8d50d26c-7805-49bc-ae0e-bbbc196fe6db)

Disabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/151805876/b2fc8d43-bbc9-4c9c-a10c-74dae955e78d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 134517
 cosmetic: 46720
 scriptlet: 20622
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 37756-296, 59m Δ
  ublock-badware: 8448-0, 59m Δ
  ublock-privacy: 874-0, 59m Δ
  ublock-unbreak: 2264-0, 59m Δ
  ublock-quick-fixes: 254-0, 59m Δ
  easylist: 86881-558, 59m Δ
  easyprivacy: 50825-811, 59m Δ
  urlhaus-1: 12630-0, now
  plowe-0: 3735-0, now
filterset (user): [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 218 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  twitter.com: 6
  ads-twitter.com: 1
  google-analytics.com: 1
 extended:
  ##.r-jwli3a:style(display: none !important;)
  ##.r-1cmwbt1:style(display: none !important;)
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by stephenhawk8054** [comment]
Remove your custom filters in "My filters" tab, open new tab and test again.

**Comment by webhunted** [comment]
Thank you, I have resolved the issue.

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
