### ISSUE TITLE
darkreader.org: ads

### ISSUE THREAD

**Issue by webhunted** [uBlockOrigin/uAssets#23497]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://darkreader.org/help/en/`

### Category

ads

### Description

Sponsored advertisements on page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/151805876/6d1df5db-19b2-4d5b-b926-af118459e814)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 134497
 cosmetic: 46611
 scriptlet: 19221
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37885-109, 3m Δ
  ublock-badware: 8450-0, 3m Δ
  ublock-privacy: 875-2, 3m Δ
  ublock-unbreak: 2321-2, 3m Δ
  ublock-quick-fixes: 183-21, 3m Δ
  easylist: 86888-174, 3m Δ
  easyprivacy: 50825-64, 3m Δ
  urlhaus-1: 12630-0, now
  plowe-0: 3735-1159, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 417 ms (selfie)
 maxAssetCacheWait: 210 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  herokudns.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
