### ISSUE TITLE
iculture.nl: privacy

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23498]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.iculture.nl/`

### Category

privacy

### Description

There are network calls to addresses that start with `https://www.iculture.nl/ic-cgi/report`. When scrolling around the page this is reported to this URL. These requests seem to come from scripts hosted under`https://iculture.report/js`.

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136778
 cosmetic: 92987
 scriptlet: 24203
 html: 1784
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/easylistdutch.txt: 1767-0, now
  fanboy-cookiemonster: 50979-183, now
  ublock-cookies-easylist: 1084-3, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37885-109, 52m Δ
  ublock-badware: 8450-0, 52m Δ
  ublock-privacy: 875-2, 52m Δ
  ublock-unbreak: 2321-2, 52m Δ
  ublock-quick-fixes: 183-21, 52m Δ
  easylist: 86888-177, 52m Δ
  easyprivacy: 50825-65, 52m Δ
  urlhaus-1: 12630-0, now
  plowe-0: 3735-1159, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 131 ms (selfie)
 maxAssetCacheWait: 77 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  doubleclick.net: 1
  onesignal.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-hosted matomo

```adb
||iculture.report^$3p
```

@ryanbr
