### ISSUE TITLE
ygosu.com: ads

### ISSUE THREAD

**Issue by aoc272** [uBlockOrigin/uAssets#23490]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ygosu.com/`

### Category

ads

### Description

Although there are already existing issues about ygosu.com, the last ones are from 2023 and so I think that i can submit issue.. one still experience the advertising trouble in April 2024.

i'm mainly using ms edge windows desktop but the problem isn't resolved in other browsers too.

### Other extensions used

[picture-in-picture extension by google](https://chromewebstore.google.com/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ygosu](https://github.com/uBlockOrigin/uAssets/assets/47027541/a39087f9-aa07-4e7a-aa08-0089fd041a4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 135937
 cosmetic: 50224
 scriptlet: 20771
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 98-5, never
  KOR-1: 5080-47, now
  easylist: 86823-493, 47m Δ
  easyprivacy: 50825-820, 47m Δ
  plowe-0: 3735-0, now
  ublock-badware: 8448-0, 47m Δ
  ublock-filters: 37694-406, 47m Δ
  ublock-privacy: 874-0, 47m Δ
  ublock-quick-fixes: 262-0, 47m Δ
  ublock-unbreak: 2264-0, 47m Δ
  urlhaus-1: 12750-0, now
filterset (user): [array of 98 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 showIconBadge: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 162 ms (selfie)
 maxAssetCacheWait: 36 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  bidrich.com: 2
  coupang.com: 8
  googletagmanager.com: 1
 extended:
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(prevent-fetch, /static\.criteo\.net|adsbygoogle/, length:1…
  ##+js(set-constant, window.googletag.apiReady, false)
```
</details>

**Comment by mapx-** [comment]
continue here: https://github.com/uBlockOrigin/uAssets/issues/21385

**Comment by aoc272** [comment]
this works for me, thanks.
