### ISSUE TITLE
(ads) stream.cr

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2349]
### URL(s) where the issue occurs

`https://search.stream.cr/y/video.php?mid=the-pirates-who-dont-do-anything-a-veggietales-movie-zev`

### Describe the issue

Redirected to scam site when adblocker detected.
Offending script: `||search.stream.cr/core/webfonts.js$script`

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.6

### Settings

All default

**Comment by zaphodbeebblebrox** [comment]
Site detects adblock, has malicious redirect.

**Comment by okiehsch** [comment]
The amount of crap that site tries to load is really impressive.
