### ISSUE TITLE
leagueoflegends.fandom.com: breakage

### ISSUE THREAD

**Issue by Joly0** [uBlockOrigin/uAssets#23493]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://leagueoflegends.fandom.com/wiki/Trundle/LoL/Audio`

### Category

breakage

### Description

Audio-play buttons are not clickable (and doubled) and no audio is hearable

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/13993216/10c76c55-faec-4796-9772-0e25c9e353fa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136931
 cosmetic: 51668
 scriptlet: 19217
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 37868-109, now
  ublock-badware: 8450-0, now
  ublock-privacy: 875-2, now
  ublock-unbreak: 2321-2, now
  easylist: 86881-174, now
  easyprivacy: 50825-63, now
  urlhaus-1: 12750-0, now
  plowe-0: 3735-1159, now
  DEU-0: 7429-37, now
  ublock-quick-fixes: 183-19, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 886 ms (selfie)
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  ad.gt: 1
  fastly-insights.com: 2
  google-analytics.com: 1
  nocookie.net: 1
  wikia-services.com: 3
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.bottom-ads-container
  ##.sponsored-content
  ###featured-video__player-container
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
```
</details>

**Comment by stephenhawk8054** [comment]
It's the site's issue. When you refresh while bypassing the cache (`Ctrl + Shift + R`), the issue will occur. If you refresh again by just `F5`, the error won't occur. This happens even when not using any extensions.
