### ISSUE TITLE
pmsuryaghar.gov.in: detection

### ISSUE THREAD

**Issue by Vlavitz** [uBlockOrigin/uAssets#23495]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pmsuryaghar.gov.in/`

### Category

detection

### Description

Detects ublock and blank page issue

### Other extensions used

NA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled2](https://github.com/uBlockOrigin/uAssets/assets/165984236/b358c008-6ff6-487d-891f-a2cc4819b950)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 273263
 cosmetic: 280100
 scriptlet: 53641
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 184-0, 2m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 0-0, 2m
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, 2m
  IND-0: 13097-2, 1m
  RUS-0: 39445-549, 1h.39m Δ
  adguard-cookies: 29398-70, 1m
  adguard-generic: 81260-6736, 1m
  adguard-mobile: 9302-132, 1m
  adguard-mobile-app-banners: 5165-1104, 1m
  adguard-other-annoyances: 14186-358, 1m
  adguard-popup-overlays: 27215-1689, 1m
  [17 lists not shown]: [too many]
 default:
  user-filters: 69-0, never
  easylist: 86881-784, 1h.39m Δ
  easyprivacy: 50825-999, 1h.39m Δ
  plowe-0: 3735-1, 2m
  ublock-badware: 8448-3, 1h.39m Δ
  ublock-filters: 37756-827, 1h.39m Δ
  ublock-privacy: 874-118, 1h.39m Δ
  ublock-quick-fixes: 254-4, 1h.39m Δ
  ublock-unbreak: 2264-24, 1h.39m Δ
  urlhaus-1: 12630-0, 2m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 972 ms (selfie)
 maxAssetCacheWait: 280 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  pmsuryaghar.gov.in: 1
```
</details>

**Comment by D4niloMR** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/57fec95e-d459-4109-90d4-57fd29122c67)

Report at https://github.com/bogachenko/fuckfuckadblock

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

**Comment by Vlavitz** [comment]
Really very sorry I overlooked that. I'll keep that in mind in future.
