### ISSUE TITLE
Mobile version of facebook.com

### ISSUE THREAD

**Issue by kowith337** [uBlockOrigin/uAssets#235]
### URL(s) where the issue occurs
`https://mbasic.facebook.com` refer to **basic version**
`https://touch.facebook.com` refer to **touch version**
_Login required_

### Describe the issue
- Currently seems have none of any filter lists can handle news feed ads in **basic version** of Facebook site, it seems EasyList can handle some in **touch version**, but sometime it still bypassed to show up...

### Screenshot(s)
Attached with dev panel, maybe helpful to figure it out.
![Basic version](https://cloud.githubusercontent.com/assets/16535467/21341284/495ea4a0-c6be-11e6-8910-2f71704e9e2d.png)
![Touch version](https://cloud.githubusercontent.com/assets/16535467/21341096/51df0738-c6bd-11e6-9bf5-981e7da57843.png)

### Versions
- Browser/version: Firefox 50.1.0 / Fennec F-droid 50.1.0
- uBlock Origin version: 1.10.4

### Settings
- Leave everything default

### Notes
- I have no idea how to write `xpath` and/or `matches-css` rules, still need to learn.
- I'm quit using native Facebook app in Android, only Firefox and Gecko-based browser (such as Fennec F-Droid, IceCatMobile, Pale Moon) can install uBlock0 because Chromium is nothing special than Android stock browser, except can sync only bookmark and browser settings with Google account.
- If you're under mobile data (depend on some carrier), you will forced to redirect to `h.facebook.com` under **non-HTTPS** first, then send you back to `m.facebook.com` or `mobile.facebook.com`, but the layout will depend on user agent, I guess.
> - If user agent contains "Mobile", it will forced you to use touch version layout.
> - If you're using desktop browser or have "Request desktop site" checked, you will get basic version layout.

_Update 2016/12/23_
Generally, need to use only `UK English` or `US English` to work...
`mbasic.facebook.com##:xpath(//div[@role="article"][.//span/text()="Sponsored"])`

_Update 2017/01/10_
Suspect from screenshots I've sent, I think these rules can be apply without using Facebook in `UK English` or `US English` language.
`mbasic.facebook.com##div[role="article"]:has(iframe[src^="/xti.php?"])`
`touch.facebook.com###m_newsfeed_stream section article:has(iframe[src^="/xti.php?"])`
because it seems sponsored posts have a hidden `iframe` that load `xti.php`.

_Update 2017/01/12_
It seems sponsored posts have both type
- one is have `iframe` inside post body.
- another one doesn't, but that hidden `iframe` will be placed next to sponsored post body (See in F12 inspector)

so the `xpath` rule still needed.

**Comment by anewuser** [comment]
You can now enable "Adguard Mobile Filters" in the "3rd-party filters" tab of the uBlock Origin options, and report missing filters to Adguard.

**Comment by kowith337** [comment]
Can I report to their even I didn't use AdGuard, but just only subscription list?

Anyway, I need to re-investigate again because this issue info are outdated and seems like ads code was updated again, also on desktop site.

**Comment by anewuser** [comment]
Yes, missing filters should be reported to the maintainers of the appropriate lists. This will benefit the users of their own extension too, so there's no reason why you shouldn't. You can mention you use uBlock Origin in your report, so they'll tell you if the needed filter isn't cross-compatible yet.

You can also add one of the lists from https://facebook.adblockplus.me/ to your settings.

> this issue info are outdated 
So please close it.
