### ISSUE TITLE
resmed.com: breakage

### ISSUE THREAD

**Issue by precaf** [uBlockOrigin/uAssets#23508]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://myair.resmed.com/`

### Category

breakage

### Description

Page does not display anything. Blocked sites are 
```s.go-mpulse.net
www.googletagmanager.com
cdn.cookielaw.org
cookielaw.org
googletagmanager.com
go-mpulse.net
1.1.1.1
```
Even after adding them to a list of URLs considered safe the page will not load.

### Other extensions used

None. Everything disabled for testing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-04-30 at 6 53 55 PM](https://github.com/uBlockOrigin/uAssets/assets/97126718/e5b8f757-e90b-486b-827c-c9e343acd27d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 134691
 cosmetic: 46620
 scriptlet: 19221
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37895-113, 15m Δ
  ublock-badware: 8461-0, 15m Δ
  ublock-privacy: 876-0, 15m Δ
  ublock-unbreak: 2321-0, 26m
  ublock-quick-fixes: 183-21, 26m
  easylist: 86881-174, 15m Δ
  easyprivacy: 50830-64, 15m Δ
  urlhaus-1: 12815-0, 26m
  plowe-0: 3735-1159, 26m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 131 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cookielaw.org: 1
  go-mpulse.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||1.1.1.1/cdn-cgi/trace$xhr,domain=myair.resmed.com`

@ryanbr
