### ISSUE TITLE
cryptorank.io: ads

### ISSUE THREAD

**Issue by hurgir** [uBlockOrigin/uAssets#23500]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cryptorank.io/price/bitcoin/exchanges`

### Category

ads

### Description

unwanted advertisements at the top, middle and bottom of the page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/104536428/813b07cc-8c6f-450c-869d-2069308162d2)

![image](https://github.com/uBlockOrigin/uAssets/assets/104536428/861175b9-8df7-4352-ac63-c945a488469a)

![image](https://github.com/uBlockOrigin/uAssets/assets/104536428/2659f18c-82ed-413b-985d-d430a8126a08)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 28902
 cosmetic: 110511
 scriptlet: 28994
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2624-50, 1h.6m
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1068-0, 1m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2098-13, 1m
  adguard-cookies: 29398-47, now
  adguard-mobile-app-banners: 5165-7, now
  adguard-other-annoyances: 14186-128, now
  adguard-popup-overlays: 27209-854, never
  adguard-social: 22880-39, 1m
  adguard-widgets: 2488-1, 1m
  ublock-cookies-adguard: 1084-0, 1m
 default:
  user-filters: 139-4, never
  TUR-0: 12115-12, never
  ublock-badware: 8448-0, 1h.6m Δ
  ublock-filters: 37757-472, 1h.6m Δ
  ublock-privacy: 874-1, 1h.6m Δ
  ublock-quick-fixes: 254-0, 1h.6m Δ
  ublock-unbreak: 2264-0, 1h.6m Δ
filterset (user): [array of 139 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 179 ms (selfie)
 maxAssetCacheWait: 44 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  walletconnect.com: 1
  walletconnect.org: 1
  web3modal.com: 7
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
removed:
  easylist: null
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
```

You are removing default filter lists. Reset uBO to default settings and test again.

**Comment by hurgir** [comment]
`uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 219002
 cosmetic: 185999
 scriptlet: 49535
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2624-50, 2h.22m
  adguard-cookies: 29404-65, 2h.22m
  adguard-generic: 81072-6461, now
  adguard-mobile-app-banners: 5166-7, 2h.22m
  adguard-other-annoyances: 14189-65, now
  adguard-popup-overlays: 27216-970, now
  adguard-social: 22881-158, now
  adguard-spyware: 88689-31780, now
  adguard-widgets: 2488-1, now
  block-lan: 65-0, 5d.3h.45m
  ublock-annoyances: 6954-1096, now Δ
  ublock-cookies-adguard: 1080-0, 5d.3h.45m
 default:
  user-filters: 19-0, never
  TUR-0: 12115-15, 1d.22h.24m
  easylist: 86861-540, now Δ
  easyprivacy: 50825-841, now Δ
  plowe-0: 3739-0, 12d.22h.37m
  ublock-badware: 8459-0, now Δ
  ublock-filters: 37764-732, now Δ
  ublock-privacy: 874-0, now Δ
  ublock-quick-fixes: 252-0, now Δ
  ublock-unbreak: 2264-0, now Δ
  urlhaus-1: 12630-0, 2h.22m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1122 ms
 maxAssetCacheWait: 391 ms
 cacheBackend: indexedDB`

Actually it was added, then I forgot to close it for testing and add it. Either way, nothing has changed.
