### ISSUE TITLE
startpage.com: detection

### ISSUE THREAD

**Issue by lostnt1** [uBlockOrigin/uAssets#23504]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.startpage.com/rik/search?q=mc+tr`

### Category

detection

### Description

Adblock detected its annoying

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240430_160038_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/136184400/416733f8-d033-4992-83f0-734559e92ccf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 223847
 cosmetic: 131812
 scriptlet: 28933
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1505-119, 2m
  adguard-spyware: 88692-31801, 2m
  block-lan: 66-0, 2m
  curben-phishing: 14270-3, 2m
  adguard-cookies: 29413-50, 2m
  ublock-cookies-adguard: 1122-0, 2m
  fanboy-cookiemonster: 50976-3876, 2m
  ublock-cookies-easylist: 1122-1122, 2m
  dpollock-0: 11669-461, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 38125-355, 2m
  ublock-badware: 8453-0, 2m Δ
  ublock-privacy: 874-0, 2m Δ
  ublock-unbreak: 2267-1, 2m Δ
  ublock-quick-fixes: 252-0, 2m Δ
  adguard-mobile: 9305-124, 3m
  easylist: 86861-845, 2m Δ
  easyprivacy: 50825-931, 2m Δ
  urlhaus-1: 12815-0, 2m
  plowe-0: 3735-0, 2m
  TUR-0: 12115-26, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4197 ms
 maxAssetCacheWait: 1612 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  startpage.com: 3
  facebook.com: 2
 extended:
  ##.ad.widget
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` list and test again. Or you can use this filter as custom filter

```adb
@@||startpage.com^$ghide
```
