### ISSUE TITLE
couchtuner.show: nuisance

### ISSUE THREAD

**Issue by MathiasFH** [uBlockOrigin/uAssets#23509]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.couchtuner.show/`

### Category

nuisance
loss of function

### Description

With uBlock activated, all the elements on the site become unusable/unclickable, apparently blocked by some invisible cover (which does not produce pop-ups or anything else).
Without uBlock activated, the site is also full of invisible layers which constantly produce pop-ups, but the links work in theory. A different adblocker which does not block pop-ups effectively also keeps the site working or elements clickable (but often only after an annoying popup first).

### Other extensions used

BetterTTV

Adblock Plus (selectively deactivated on the site and many others)

Google Docs Offline

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 137095
 cosmetic: 51764
 scriptlet: 20625
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  DEU-0: 7436-0, now
  easylist: 86905-567, now
  easyprivacy: 50830-801, now
  plowe-0: 3735-1, now
  ublock-badware: 8459-0, now
  ublock-filters: 37767-312, now
  ublock-privacy: 875-0, now
  ublock-quick-fixes: 254-1, now
  ublock-unbreak: 2265-20, now
  urlhaus-1: 12815-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 44 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2366 ms (selfie)
 maxAssetCacheWait: 410 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  longestsundays.com: 2
  waufooke.com: 2
 extended:
  ##+js(abort-current-script, RegExp, 0x)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by libertymod** [comment]
I have had this same issue. After playing around with the settings, I discovered you can use uBlock to disable javascript on the site and that seems to have restored some functionality. I can click on the buttons for the content now, but still can't play anything. It's the option that looks like </> right below the activation button on uBlock.
