### ISSUE TITLE
linux.do: nuisance

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#23506]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://linux.do/`

### Category

nuisance

### Description

Its basically a sign up button however since their website signup is broken there is no other choice than to peek around the site. A few days ago I never experience this popup until recently, clearing cookies dosen't help either.

### Other extensions used

Mostly unrelated to ublock, no other adblockers used
- Cookie Editor
- Downthemall
- DeArrow
- Dark Reader
- ChatGPT box

### Screenshot(s)

![librewolf_TKONv9tEO7](https://github.com/uBlockOrigin/uAssets/assets/150899804/90ceaea0-13be-4405-b7bc-28a4d9f5d172)
![librewolf_ThquF7LC3v](https://github.com/uBlockOrigin/uAssets/assets/150899804/fc4e7b97-9540-4306-acf1-37bb4422eebf)

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 121
filterset (summary):
 network: 171460
 cosmetic: 80437
 scriptlet: 20822
 html: 1800
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4536-49, now
  easylist-chat: 191-0, now
  easylist-newsletters: 7291-15, now
  easylist-notifications: 2966-163, now
  RUS-0: 39478-167, now
 default:
  user-filters: 57-3, never
  ublock-filters: 37892-109, now
  ublock-badware: 8461-0, now
  ublock-privacy: 876-2, now
  ublock-unbreak: 2321-2, now
  ublock-quick-fixes: 183-21, now
  easylist: 86866-174, now
  adguard-spyware-url: 1505-120, now
  easyprivacy: 50826-64, now
  urlhaus-1: 12815-0, now
  curben-phishing: 14270-1, now
  plowe-0: 3735-1160, now
  LegitimateURLShortener: 2624-165, now
filterset (user): [array of 57 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 999 ms (selfie)
 maxAssetCacheWait: 313 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  linux.do: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
linux.do##.custom-gated-topic-container
linux.do##body.topic-in-gated-category:remove-class(topic-in-gated-category)
linux.do##.topic-in-gated-category .container.posts::before:style(background: transparent !important;)
```

@ryanbr
