### ISSUE TITLE
wordcounter.icu: breakage

### ISSUE THREAD

**Issue by Juhm123** [uBlockOrigin/uAssets#23519]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wordcounter.icu/`

### Category

breakage

### Description

> uBlock origin bloquea los CAPTCHA, no permiteindo que se genere la ventana a resolver

**uBlock origin blocks CAPTCHAs, not allowing the window to be solved to be generated**

### Other extensions used

Ninguna

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136999
 cosmetic: 53184
 scriptlet: 19650
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 14-0, never
  ublock-filters: 37903-109, 28m Δ
  ublock-badware: 8461-0, 28m Δ
  ublock-privacy: 876-2, 28m Δ
  ublock-unbreak: 2322-2, 28m Δ
  ublock-quick-fixes: 191-21, 28m Δ
  easylist: 86887-174, 28m Δ
  easyprivacy: 50842-64, 28m Δ
  urlhaus-1: 12705-0, now
  plowe-0: 3735-1159, now
  spa-0: 4061-27, now
  spa-1: 5578-247, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 404 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 71
 network:
  wordcounter.icu: 27
  amazon-adsystem.com: 1
  doubleclick.net: 1
  ezodn.com: 8
  ezoic.com: 2
  ezoic.net: 26
  grantedpigsunborn.com: 1
  imasdk.googleapis.com: 1
  pubmatic.com: 1
  quantserve.com: 1
  recaptcha.net: 1
  zencdn.net: 1
 extended:
  ###div-gpt-ad-Content_3\/4aef659d7e9842c28595c66c12cf76ca-0
  ###link-view > span
  ##.humix-universal-js-insert > .ez-video-wrap
  ##.col-md-6 > span
  ##.text-left
  ##center
  ##+js(no-window-open-if)
```
</details>

**Comment by detyso** [comment]
i cannot  get the captcha while using ublock origin i have to disable ublock origin then the google  captcha appears 
see video that i attached


https://github.com/user-attachments/assets/8b959e10-c163-4507-a5d9-e60c8418bf36
