### ISSUE TITLE
sfchronicle.com: detection

### ISSUE THREAD

**Issue by markhamnr** [uBlockOrigin/uAssets#23511]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sfchronicle.com/food/restaurants/article/diners-prices-bay-area-19418962.php`

### Category

detection

### Description

Site has an overlay that says "You have ad-blocker turned on"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 123
filterset (summary):
 network: 134685
 cosmetic: 46534
 scriptlet: 19180
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37895-109, now
  ublock-badware: 8461-0, now
  ublock-privacy: 876-2, now
  ublock-unbreak: 2322-2, now
  easylist: 86905-174, now
  easyprivacy: 50830-63, now
  plowe-0: 3735-1159, now
  urlhaus-1: 12815-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 53 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 703 ms (selfie)
 maxAssetCacheWait: 95 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  sfchronicle.com: 3
  3lift.com: 2
  amazon-adsystem.com: 1
  casalemedia.com: 2
  chartbeat.com: 1
  concert.io: 1
  ctpost.com: 1
  d15kdpgjg3unno.cloudfront.net: 1
  doubleclick.net: 1
  dyv1bugovvq1g.cloudfront.net: 1
  google.com: 2
  googletagmanager.com: 1
  hearst3pcc.com: 1
  liadm.com: 4
  ml314.com: 2
  newrelic.com: 2
  ntv.io: 1
  openx.net: 2
  permutive.app: 1
  pubmatic.com: 2
  rubiconproject.com: 8
  sail-horizon.com: 1
  scorecardresearch.com: 1
  sfgate.com: 1
  webcontentassessor.com: 1
 extended:
  ##.b-gray300.bt
  ##.b-gray300.bt.bb
  ##[data-block-type="ad"]
```
</details>

**Comment by Az1568** [comment]
URL: `https://www.sfchronicle.com/health/article/covid-vaccine-access-20884557.php`

Category: detection

Description:  Site once again has an overlay that says "Your ad-blocker is turned on".

Browser name and version: Google Chrome Version 139.0.7258.139 (Official Build) (arm64)

Other extensions used: 
1Password – Password Manager
Adobe Acrobat: PDF edit, convert, sign tools...
Cookie-Editor
Microsoft Single Sign On
RECAP
PayPal Honey
Grammarly: AI Writing Assistant and...

Country: US

Screenshot(s): 
<details>
<summary>Screenshot(s)</summary>




<img width="1512" height="873" alt="Image" src="https://github.com/user-attachments/assets/0ddf63f1-daf0-4387-97e3-dbe631631cf4" />



</details>

Configuration: 
```yaml
name: uBlock Origin Lite
version: 2025.818.1918
browser: Chrome 139 (mac)
filtering:
 site: complete
 default: optimal
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 annoyances-cookies
 annoyances-overlays
 annoyances-others
```
