### ISSUE TITLE
thedailystar.net: nuisance

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#23523]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thedailystar.net/`

### Category

nuisance

### Description

Bell icon and a cross button below. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/582ec59c-8975-49a4-bf5b-60cc0100a4eb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 130919
 cosmetic: 130004
 scriptlet: 29680
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  fanboy-cookiemonster: 67113-16356, 7m
  ublock-cookies-easylist: 1086-0, 8m
  fanboy-social: 15829-2, 8m
  easylist-annoyances: 4544-21, 8m
  easylist-chat: 191-0, 8m
  easylist-newsletters: 7292-13, 8m
  easylist-notifications: 2966-84, 8m
  ublock-annoyances: 6956-1138, 6m Δ
  IND-0: 13097-11, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37770-305, 6m Δ
  ublock-badware: 8459-0, 6m Δ
  ublock-privacy: 875-0, 8m
  ublock-unbreak: 2265-0, 6m Δ
  ublock-quick-fixes: 261-0, 8m
  easylist: 86887-585, 8m
  easyprivacy: 50842-111, 6m Δ
  plowe-0: 3735-788, 8m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 889 ms
 maxAssetCacheWait: 308 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  thedailystar.net: 2
  chartbeat.com: 2
  cloudflareinsights.com: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  maillist-manage.com: 1
  pubguru.net: 1
 extended:
  ##.social-links
  ##.top-leaderboard
  ##div[id^="dfp-ad-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.block-dfp
  ##.dfp-tag-wrapper
  ##.social-list:not(html):not(body)
  ##.pane-ad-pane
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
report at easylist repository https://github.com/easylist/easylist/issues
