### ISSUE TITLE
My users are not able to embed my video player anymore

### ISSUE THREAD

**Issue by APX403** [uBlockOrigin/uAssets#23526]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
/!\ NSFW /!\ 

https://www.myvidster.com/video/416960108/Watch_Gay_Porn_Gay_Porn_Looped_Tease_-_Blond_Amateur_Jerking_Off_No_Cum_
```

### Description

Many users have been reporting to my support team that when they embed my player on other websites, the video doesn't play if uBlock is enabled. However, when uBlock is disabled, the player functions perfectly. I'm genuinely puzzled about how to resolve this issue.

(On my website, even with UO enabled, the player is working fine. But not on embeded player.)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 /!\ NSFW /!\
 
 https://img95.pixhost.to/images/454/465227992_bug-uo.png
 

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 151779
 cosmetic: 53303
 scriptlet: 20772
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 24407-110, now
  easylist: 86909-677, now
  easyprivacy: 50843-1012, now
  plowe-0: 3735-0, now
  ublock-badware: 8459-0, now
  ublock-filters: 37780-367, now
  ublock-privacy: 875-0, now
  ublock-quick-fixes: 261-0, now
  ublock-unbreak: 2265-0, now
  urlhaus-1: 12705-0, now
filterset (user): [empty]
trustedset:
 added: [array of 47 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 362 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  disqus.com: 5
  exosrv.com: 2
  googletagmanager.com: 1
  magsrv.com: 2
  mygaytube.com: 1
  pemsrv.com: 2
  traffichaus.com: 1
  viglink.com: 2
 extended:
  ##+js(abort-current-script, document.write, cachebuster)
  ##.ad-content:not(:empty)
```
</details>

**Comment by mapx-** [comment]
maybe because you are pushing a popunder ?

test this filter
`mygaytube.com##+js(acs, document.querySelectorAll, popMagic)`

**Comment by APX403** [comment]
Yes I am !

But cannot this popunder be blocked with UO, without blocking the use of the whole player like it seems to be the case on my website ?

Thanks for your help :)

**Comment by mapx-** [comment]
just test the filter above.

**Comment by APX403** [comment]
With this filter it's working yep !
