### ISSUE TITLE
lro.realpage.com: breakage

### ISSUE THREAD

**Issue by Resiarlleh** [uBlockOrigin/uAssets#23527]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://lightstone.lro.realpage.com/Default.aspx
```

### Description

Hello,

When any user goes to the above site, only half of the content loads while ublock is enabled. once disabled the site loads fully. i cannot figure out how to update my filters for this as i am new to this role and have never used ublock and my previous boss quit and didnt have any documentation on it. i assumed clicking the +all at the top would fix it but it did not. any assistance would be appreciated. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![f49c3914-b337-4b45-aaf7-6aee4a9ca5a6](https://github.com/uBlockOrigin/uAssets/assets/168681391/9e87b56e-1c00-4e9f-b1ba-a42c1f4449df)

![f49c3914-b337-4b45-aaf7-6aee4a9ca5a6](https://github.com/uBlockOrigin/uAssets/assets/168681391/ac298a9b-044f-4b31-995d-9a8e97dfad51)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 134666
 cosmetic: 46694
 scriptlet: 20630
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86887-559, 5h.34m Δ
  easyprivacy: 50842-811, 5h.34m Δ
  plowe-0: 3737-0, 6d.6h.55m
  ublock-badware: 8459-0, 5h.34m Δ
  ublock-filters: 37775-296, 5h.34m Δ
  ublock-privacy: 875-0, 5h.34m Δ
  ublock-quick-fixes: 261-0, 5h.34m Δ
  ublock-unbreak: 2265-0, 5h.34m Δ
  urlhaus-1: 12705-0, 4h.34m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 411 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  go-mpulse.net: 10
  google-analytics.com: 3

```
</details>

**Comment by Daxy7** [comment]
Try adding this into your user filters via the dashboard, click the cog wheel on the filtering popup page
```
@@||go-mpulse.net^$domain=lightstone.lro.realpage.com
! if the above filter doesnt work, remove it and try the below whitelist filter.
@@||google-analytics.com^$domain=lightstone.lro.realpage.co

! if none of each work, try adding them both here:
@@||go-mpulse.net^$domain=lightstone.lro.realpage.com
@@||google-analytics.com^$domain=lightstone.lro.realpage.co
```

**Comment by Resiarlleh** [comment]
i figured it out, apparently, we have the whitelist saved as a registry key via GP. i updated the value there for whitelisting the site and its now working. Thank you everyone who looked into this for me! :)
