### ISSUE TITLE
infinityskull.com: detection

### ISSUE THREAD

**Issue by preetam1409** [uBlockOrigin/uAssets#23535]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://infinityskull.com/balanced-benefits-and-challenges-of-learning-in-indian-schools-education-system/`

### Category

detection

### Description

detected adblock  

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240502-201228_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/43402156/bc4fd7b7-5ba3-4eb8-9176-9e6a7a2c7960)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.3b6
Chromium Mobile: 124
filterset (summary):
 network: 136216
 cosmetic: 54618
 scriptlet: 20725
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38162-343, now
  ublock-badware: 8499-0, now
  ublock-privacy: 881-0, now
  ublock-unbreak: 2271-0, now
  ublock-quick-fixes: 262-0, now
  adguard-mobile: 9316-97, now
  easylist: 86841-611, now
  easyprivacy: 50847-819, now
  urlhaus-1: 12765-0, now
  plowe-0: 3735-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1359 ms
 maxAssetCacheWait: 197 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  clarity.ms: 1
  doubleclick.net: 1
  googlesyndication.com: 3
 extended:
  ##[id$="-Ads"], [id*="-gpt-ad"], center > h3, #skull, #content, …
  ###tp98, #btn6:style(display: block !important;)
  ##+js(remove-node-text, script, /ABDetected|navigator.brave|fetc…
  ##+js(set-constant, count, 0)
```
</details>

**Comment by BlazeFTL** [comment]
```
||cdn.jsdelivr.net/gh/itspro-dev/*/js/main.js$script,domain=iisfvirtual.in|starxinvestor.com|viewmyknowledge.com|infinityskull.com|nayisahara.com|wikifilmia.com|careersides.com|funkeypagali.com
funkeypagali.com,careersides.com,nayisahara.com,wikifilmia.com,infinityskull.com,viewmyknowledge.com,iisfvirtual.in,starxinvestor.com##+js(no-fetch-if, googlesyndication)
funkeypagali.com,careersides.com,nayisahara.com,wikifilmia.com,infinityskull.com,viewmyknowledge.com,iisfvirtual.in,starxinvestor.com##+js(noeval-if, /fairAdblock|chp_adblock|adsbygoogle\.js/)

**Comment by preetam1409** [comment]
its says forbidden when I place the whole link in chrome

**Comment by mapx-** [comment]
click uBO icon, click the last (gear) icon on the right side, "my filters" tab, paste the filters above, click "apply changes", test again

**Comment by preetam1409** [comment]
okay thak you

**Comment by preetam1409** [comment]
its working wow
