### ISSUE TITLE
my trips @ oncf-voyages.ma: [unknown]

### ISSUE THREAD

**Issue by TravelerJon** [uBlockOrigin/uAssets#23533]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.oncf-voyages.ma/resultats-disponibilites/authentification`

### Category

[unknown]

### Description

I want to open an account with ONCF 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
I do not understand, I just want to open an account with ONCF in order to buy a train ticket.

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 134753
 cosmetic: 46628
 scriptlet: 20650
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86837-559, 42m Δ
  easyprivacy: 50847-812, 42m Δ
  plowe-0: 3735-0, now
  ublock-badware: 8505-0, 43m Δ
  ublock-filters: 37804-296, 42m Δ
  ublock-privacy: 876-0, 43m Δ
  ublock-quick-fixes: 261-0, 43m Δ
  ublock-unbreak: 2268-0, 42m Δ
  urlhaus-1: 12715-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2505 ms (selfie)
 maxAssetCacheWait: 831 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google.co.uk: 2
  googletagmanager.com: 1
```
</details>

**Comment by TravelerJon** [comment]
I need a result thank you

**Comment by TravelerJon** [comment]
are you wasting my time??

**Comment by mapx-** [comment]
Explain your issue.
