### ISSUE TITLE
linkedin.com: nuisance

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#23532]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.linkedin.com/pulse/world-dominated-operating-systems-like-windows-why-linux-bhatjire-8uqpf`

### Category

nuisance

### Description

Sign-in popup

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/e083b4f0-4012-4448-ad5c-a961b0d0a6ff)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 130998
 cosmetic: 129944
 scriptlet: 29703
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  fanboy-cookiemonster: 67113-16356, 1m
  ublock-cookies-easylist: 1086-0, 1m
  fanboy-social: 15830-8, 1m
  easylist-annoyances: 4545-31, 1m
  easylist-chat: 191-0, 1m
  easylist-newsletters: 7293-13, 1m
  easylist-notifications: 2966-156, 1m
  ublock-annoyances: 6958-1138, 2m Δ
  IND-0: 13097-0, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 37804-308, 2m Δ
  ublock-badware: 8505-0, 2m Δ
  ublock-privacy: 876-0, 2m Δ
  ublock-unbreak: 2268-0, 2m Δ
  ublock-quick-fixes: 261-0, 2m Δ
  easylist: 86837-594, 2m Δ
  easyprivacy: 50847-24, 2m Δ
  plowe-0: 3735-788, 1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4218 ms (selfie)
 maxAssetCacheWait: 829 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  linkedin.com: 8
 extended:
  ##.social-share
  ##.social-share__button
  ##.social-share-button
  ##.windows-app-upsell
  ##.bg-color-background-container-tint.top-2
  ##body:style(overflow: auto !important; position: initial !impor…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
linkedin.com##+js(trusted-set-local-storage-item, contextual-sign-in-modal-cool-off-hidden, $now$)
```

@ryanbr
