### ISSUE TITLE
ign.com: ads

### ISSUE THREAD

**Issue by Torsteinws** [uBlockOrigin/uAssets#23537]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ign.com/`

### Category

ads

### Description

The United States version of ign.com shows me an ad if I scroll a little bit down the news feed.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-03 034130](https://github.com/uBlockOrigin/uAssets/assets/47348352/17018fbf-256b-45e5-ae94-9676cbf3bb34)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 138905
 cosmetic: 126249
 scriptlet: 25417
 html: 1784
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29435-3743, now
  ublock-cookies-adguard: 1086-0, now
  fanboy-cookiemonster: 50963-186, now
  ublock-cookies-easylist: 1086-1086, now
  adguard-mobile-app-banners: 5186-9, now
  easylist-newsletters: 7292-13, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37934-109, 2m
  ublock-badware: 8507-0, 2m
  ublock-privacy: 882-2, 2m
  ublock-unbreak: 2325-2, 2m
  ublock-quick-fixes: 192-21, 2m
  easylist: 86841-175, 2m
  easyprivacy: 50847-65, 1m
  urlhaus-1: 12765-0, 1m
  plowe-0: 3735-1159, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1335 ms
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 62
 network:
  ign.com: 1
  adsafeprotected.com: 1
  chartbeat.com: 2
  cxense.com: 2
  doubleclick.net: 1
  googletagmanager.com: 2
  imasdk.googleapis.com: 2
  npttech.com: 1
  p-n.io: 1
  scorecardresearch.com: 1
  sentry.io: 3
  spot.im: 39
  wknd.ai: 1
  zdbb.net: 1
  ziffstatic.com: 4
 extended:
  ###zdcFloatingBtn
  ##.adunit-wrapper
  ##.ad-rail-wrapper
  ###adchoicesBtn
  ###onetrust-consent-sdk
  ##.onetrust-pc-dark-filter
```
</details>

**Comment by mapx-** [comment]
add

`ign.com##.background-image.no-video.content-block`

@ryanbr

**Comment by Torsteinws** [comment]
Yes, that worked!
