### ISSUE TITLE
vanilla.warcraftlogs.com: ads

### ISSUE THREAD

**Issue by mrbuurns** [uBlockOrigin/uAssets#23536]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vanilla.warcraftlogs.com/`

### Category

ads

### Description

annoying Banner on the bottom of the screen remains. this is for all subs from `https://www.warcraftlogs.com/`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/a/wSUO1h0

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 160872
 cosmetic: 138816
 scriptlet: 26707
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78578-985, now
  RUS-0: 39453-97, 1h.26m Δ
 default:
  user-filters: 5-0, never
  DEU-0: 7439-1, 1h.26m
  easylist: 86841-589, now
  easyprivacy: 50847-821, now
  plowe-0: 3735-0, now
  ublock-badware: 8505-0, now
  ublock-filters: 37810-335, now
  ublock-privacy: 881-0, now
  ublock-quick-fixes: 262-0, now
  ublock-unbreak: 2268-2, now
  urlhaus-1: 12765-0, 1h.26m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 72 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 906 ms (selfie)
 maxAssetCacheWait: 426 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  btloader.com: 1
  googletagmanager.com: 1
  intergient.com: 1
  sentry.io: 2
 extended:
  ##+js(addEventListener-defuser, DOMContentLoaded, replaceAdsWith…
```
</details>

**Comment by mapx-** [comment]
test

`warcraftlogs.com##+js(rpnt, script, AdBlockMetrics, xxx)`

(you have to enable in "my filters" => `Allow custom filters requiring trust`)

**Comment by mrbuurns** [comment]
that removes the whole top rows of the website

**Comment by huyszn** [comment]
Same banner also appears on
```
fflogs.com
esologs.com
swtorlogs.com
```

**Comment by stephenhawk8054** [comment]
I think annoyance list is more suitable. I'll move the filters to it.
