### ISSUE TITLE
whereto.stream

### ISSUE THREAD

**Issue by erkinalp** [uBlockOrigin/uAssets#23542]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
`https://whereto.stream/movie/447277`
`https://whereto.stream/movie/{movie.id}`
```

### Description

"A stream with NordVPN" ad appears

Proposed solution:
```ublock
! 2024-05-03 https://whereto.stream
whereto.stream##.gap-1.items-center.flex.mx-auto.h-\[42px\].max-w-xl > .gap-2.items-center.flex.flex-1.w-full > .sm\:block.hidden.min-w-\[100px\]
```

### Other extensions used

Dark Reader, Grease Monkey and Stylus, but no rules from these affect the website

### Screenshot(s)

before: 
![image](https://github.com/uBlockOrigin/uAssets/assets/5833034/a8e0fe70-d11b-4e90-8a3f-2647eea354a2)
after:
![image](https://github.com/uBlockOrigin/uAssets/assets/5833034/3f81100d-1b81-48e0-81aa-39b200a7c54d)

### Configuration

```
uBlock Origin: 1.57.2
Firefox: 126 beta
filterset (summary):
 network: 1327552
 cosmetic: 261998
 scriptlet: 52742
 html: 2042
listset (total-discarded, last-updated):
 added:
  https://curbengh.github.io/urlhaus-filter/urlhaus-filter-online.txt: 4133-0, 19h.41m
  https://fanboy.co.nz/fanboy-turkish.txt: 823-0, 15d.18h.40m
  https://filters.adtidy.org/extension/ublock/filters/5.txt: 17-0, 18h.39m
  https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt: 6-0, 6d.19h.39m
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/BadIpList.txt: 14-2, 19h.42m
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/HostsList.txt: 9872-35, 19h.41m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1066-0, 20d.20h.23m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiBadCapitalismList.txt: 425-0, 2d.17h
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiFunctionalityRemovalList.txt: 24-0, 2d.19h.1m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt: 420-0, 2d.17h
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/EmptyPaddingRemover.txt: 67-0, 15h.38m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/I Don't Want to Download Your Browser.txt: 61-0, 18h.39m
  [33 lists not shown]: [too many]
 default:
  user-filters: 23-1, never
  ublock-filters: 37936-262, 1h.30m Δ
  ublock-badware: 8507-84, 1h.30m Δ
  ublock-privacy: 882-35, 1h.30m Δ
  ublock-unbreak: 2325-3, 1h.30m Δ
  ublock-quick-fixes: 191-21, 1h.30m Δ
  easylist: 86828-40678, 1h.30m Δ
  easyprivacy: 50856-38327, 1h.30m Δ
  urlhaus-1: 12765-4042, 19h.41m
  plowe-0: 3737-3542, 7d.20h.21m
  TUR-0: 12118-231, 18h.39m
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 allowGenericProceduralFilters: true
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 600
 filterAuthorMode: true
 trustedListPrefixes: ublock- user- adguard- easylist-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 412 ms (selfie)
 maxAssetCacheWait: 324 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  heapanalytics.com: 1
 extended:
  ##.gap-1.items-center.flex.mx-auto.h-\[42px\].max-w-xl > .gap-2.…
  ##section:remove-class(image-copy-protection)
```
Operating system: Ubuntu 24.04
System language: Turkish

**Comment by stephenhawk8054** [comment]
```adb
whereto.stream##a[href^="https://go.nordvpn.net/"]
```

@ryanbr
