### ISSUE TITLE
dicasgostosas.com: detection

### ISSUE THREAD

**Issue by DiilSilva** [uBlockOrigin/uAssets#23547]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dicasgostosas.com/peito-de-peru-glaceado-com-soja-e-misso/`

### Category

detection

### Description

Site esta reconhecendo o uso do Ublock e me obrigando a desativar.

### Other extensions used

https://dicasgostosas.com/bolo-de-caneca-com-redemoinho-de-nozes-e-canela/
![Captura de tela 2024-05-03 123104](https://github.com/uBlockOrigin/uAssets/assets/168847862/cf9f3aa9-b505-4159-9781-54a3efb4e8aa)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136515
 cosmetic: 50406
 scriptlet: 21109
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 86827-499, now
  easyprivacy: 50857-803, now
  plowe-0: 3729-0, now
  spa-1: 5591-15, now
  ublock-badware: 8512-0, now
  ublock-filters: 37842-412, now
  ublock-privacy: 881-2, now
  ublock-quick-fixes: 260-2, now
  ublock-unbreak: 2268-21, now
  urlhaus-1: 13165-0, now
filterset (user): [array of 4 redacted]
trustedset:
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 341 ms (selfie)
 maxAssetCacheWait: 139 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  demand.supply: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  popads.net: 1
  waust.at: 1
 extended:
  ##.adbox > p
  ##path
  ##b
  ##.adbox
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
```
</details>

**Comment by DiilSilva** [comment]
Uso o site https://www.anitube.vip/ para pode assistir online, onde me direcionam pra esses links de ''Culinaria'' e neles são reproduzido os videos, porem agora usando o Ublock não posso assisti-los.

**Comment by D4niloMR** [comment]
Add in "My filters":

`dicasgostosas.com##+js(nostif, hasAdblock)`

**Comment by Alex-302** [comment]
@D4niloMR Added to `AdGuard Spanish/Portuguese filter`

**Comment by DiilSilva** [comment]
![Captura de tela 2024-05-03 142347](https://github.com/uBlockOrigin/uAssets/assets/168847862/9cdb93ae-e508-4139-a148-4628c87465f3)
Da erro ao tentar adicionar

**Comment by DiilSilva** [comment]
tirei o Https:// e deu certo, obrigado!
