### ISSUE TITLE
gplinks doesn't work with extention 

### ISSUE THREAD

**Issue by sopheest** [uBlockOrigin/uAssets#23548]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://gplinks.co/x4YJo/?pid=864676&vid=357625804
https://gplinks.co
```

### Description

Cant reach site due to the Adblocker usage.

### Other extensions used

non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![124](https://github.com/uBlockOrigin/uAssets/assets/168849915/12fca026-b922-4b75-a82f-fd21e43b4ccc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 152550
 cosmetic: 67162
 scriptlet: 22085
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37812-296, 1m
  ublock-badware: 8505-0, 1m
  ublock-privacy: 881-0, 1m
  ublock-unbreak: 2268-0, 1m
  ublock-quick-fixes: 261-0, 1m
  easylist: 86828-558, 1m
  easyprivacy: 50856-812, 1m
  urlhaus-1: 13165-0, 1m
  plowe-0: 3729-0, 1m
  RUS-0: 39456-140, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1645 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
ask here for help: https://github.com/uBlockOrigin/uAssets/discussions/17361
