### ISSUE TITLE
japscan.lol:‌ breakage

### ISSUE THREAD

**Issue by WhiskasChaton** [uBlockOrigin/uAssets#23546]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.japscan.lol/lecture-en-ligne/one-piece/1113/3.html
```

### Description

When starting to read any scan from this website, a random page (usually the 2nd, 3rd or 4th) is replaced by an add
Disabling ublock will show the actual add, and allow to clik to go to next page and continue reading.
However with ublock ON, the add is well blocked, but I can't click to go on next page. Using the droplist to change page doesn't work either
Is it possible to bypass this "add page" ?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Without ublock : add is showing up and allow to go to next page

![image](https://github.com/uBlockOrigin/uAssets/assets/28593794/bbe490c1-763f-4480-8b59-48465332ef83)

With ublock : add doesn't show up but we can't go to next page
![image](https://github.com/uBlockOrigin/uAssets/assets/28593794/f3c84917-d9d3-447f-a0aa-7b4a0e166d6e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 152017
 cosmetic: 53109
 scriptlet: 19401
 html: 1784
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 37936-109, 2h.17m Δ
  ublock-badware: 8507-0, 2h.17m Δ
  ublock-privacy: 882-2, 2h.17m Δ
  ublock-unbreak: 2325-2, 2h.17m Δ
  ublock-quick-fixes: 191-21, 2h.17m Δ
  easylist: 86827-175, 2h.17m Δ
  easyprivacy: 50856-65, 2h.17m Δ
  urlhaus-1: 12895-0, 5h.17m
  plowe-0: 3734-1159, 6d.18h.35m
  FRA-0: 24407-500, 3d.22h.12m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 182 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  japscan.lol: 8
  google-analytics.com: 1
  googletagmanager.com: 1
  sebkhapaction.com: 1
 extended:
  ##.promo
  ##.blur-background
  ##.notice-message
  ###dlinkc
  ##div.container > [href]
  ##+js(no-setTimeout-if, detectImgLoad)
  ##+js(abort-current-script, document.addEventListener, /getCompu…
  ##+js(no-window-open-if)

```
</details>

**Comment by D4niloMR** [comment]
[Click here](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=FRA-0) to update French list, then try this filter:

```adb
||japscan.lol/imgs/japo/reader.jpg$xhr,1p
```

**Comment by WhiskasChaton** [comment]
Thanks, it works fine

**Comment by D4niloMR** [comment]
@Yuki2718 for AdGuard Français ?

**Comment by Yuki2718** [comment]
@smed79
