### ISSUE TITLE
cashify.in: breakage

### ISSUE THREAD

**Issue by Vlavitz** [uBlockOrigin/uAssets#23558]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cashify.in/sell-old-mobile-phone/sell-apple`

### Category

breakage

### Description

Blank screen issue due to uBlock

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/uBlockOrigin/uAssets/assets/165984236/c87c9c38-62d8-49a3-898a-e3cd5e5c549f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 255081
 cosmetic: 280401
 scriptlet: 53754
 html: 0
listset (total-discarded, last-updated):
 added:
  IND-0: 13097-0, now
  RUS-0: 39459-549, now
  adguard-cookies: 29453-32, now
  adguard-generic: 81704-6954, now
  adguard-mobile: 9317-13, now
  adguard-mobile-app-banners: 5186-8, now
  adguard-other-annoyances: 14201-11, now
  adguard-popup-overlays: 27272-1612, now
  adguard-social: 22894-159, now
  adguard-spyware: 88714-31813, now
  adguard-spyware-url: 1506-5, now
  adguard-widgets: 2493-18, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 61-0, never
  easylist: 86839-925, now
  easyprivacy: 50857-232, now
  plowe-0: 3729-1286, now
  ublock-badware: 8527-2, now
  ublock-filters: 37850-712, now
  ublock-privacy: 881-118, now
  ublock-quick-fixes: 264-4, now
  ublock-unbreak: 2268-24, now
  urlhaus-1: 12835-0, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1409 ms (selfie)
 maxAssetCacheWait: 238 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> [13 lists not shown]: [too many]

- reset to uBO defaults
- add the other lists one by one until you get the "bad" one => report back
- closing for now
