### ISSUE TITLE
support.knivesandtools.com: breakage

### ISSUE THREAD

**Issue by Woreec** [uBlockOrigin/uAssets#23550]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://support.knivesandtools.com/hc/en-us/articles/4408845139474-I-want-to-change-my-order`

### Category

breakage

### Description

The whole Contact Us widget is filtered out with "uBlock filters – Privacy" turned on, making it impossible to contact support.
(At bottom right)

### Other extensions used

Popupblocker (disabled)
Tracker blocker (disabled)
[VT4Browsers](https://www.virustotal.com/)
REDIRECTOR (disabled)
unpaywall
facebook container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 128149
 cosmetic: 35970
 scriptlet: 870
 html: 111
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
 default:
  user-filters: 4-0, never
  ublock-badware: 8514-0, 2m
  ublock-privacy: 882-0, now
  ublock-unbreak: 2325-0, now
  ublock-quick-fixes: 190-0, now
  easylist: 86833-72, now
  easyprivacy: 50857-37, now
  urlhaus-1: 13165-0, now
  plowe-0: 3729-1158, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 240 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  knivesandtools.com: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  swifteq.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=support.knivesandtools.com
```

@ryanbr
