### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#2355]
### URL(s) where the issue occurs

`http://www.komputerswiat.pl/opinie/trendy-technologiczne/2018/05/nadchodzace-zmiany-na-rynku-smartfonow.aspx`

### Describe the issue

uBO Filters - Privacy hides comments.

### Screenshot(s)
Before
![screenshot_20180523_220710](https://user-images.githubusercontent.com/19818572/40448383-a8eb517e-5ed5-11e8-80a3-112bac9ecf5e.png)
After
![screenshot_20180523_220742](https://user-images.githubusercontent.com/19818572/40448413-ba63bf2c-5ed5-11e8-9605-48248932446f.png)

### Versions

- Browser/version: Waterfox 56.2.0
- uBlock Origin version: 1.16.6

### Settings

- `https://gist.github.com/hawkeye116477/c19a440599c62cf50dd8f200c2030627`

### Notes

Fix => `@@||googletagmanager.com/gtm.js$script,domain=komputerswiat.pl`

**Comment by mapx-** [comment]
@MajkiIT

**Comment by MajkiIT** [comment]
@mapx- @hawkeye116477 thanks
