### ISSUE TITLE
marktplaats.nl: nuisance

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23555]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.marktplaats.nl/`

### Category

nuisance

### Description

Unblocked cookie wall. Blocked by
```
||consent.marktplaats.nl
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136909
 cosmetic: 91538
 scriptlet: 24277
 html: 1777
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  fanboy-cookiemonster: 50963-183, 16m
  ublock-cookies-easylist: 1086-3, 16m
 default:
  ublock-filters: 37970-109, 16m Δ
  ublock-badware: 8514-0, 16m Δ
  ublock-privacy: 882-2, 16m Δ
  ublock-unbreak: 2325-2, 16m Δ
  ublock-quick-fixes: 190-21, 16m Δ
  easylist: 86833-175, 16m Δ
  easyprivacy: 50857-65, 16m Δ
  urlhaus-1: 13020-0, 16m
  plowe-0: 3729-1158, 6m
filterset (user): [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 124 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  marktplaats.nl: 1
  datadoghq-browser-agent.com: 1
  ebayclassifieds.net: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  marktplaats.net: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr @Alex-302

**Comment by Alex-302** [comment]
Added. Will also process another issues, where I was mentioned (I was on vacation).
