### ISSUE TITLE
anwbvignetten.nl: breakage

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23554]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.anwbvignetten.nl/oostenrijk.html`

### Category

breakage

### Description

Store buttons break with EasyList Cookie enabled. Fixed by blocking custom script ending in `/ecookiebar.js`. Furthermore `anwbvignetten.nl##^script:has-text(eCookieBar)` fixes some console errors, but does not seem to be strictly necessary.

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136909
 cosmetic: 91538
 scriptlet: 24277
 html: 1777
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50963-183, 10m
  ublock-cookies-easylist: 1086-3, 10m
 default:
  user-filters: 0-0, never
  ublock-filters: 37970-109, 10m Δ
  ublock-badware: 8514-0, 10m Δ
  ublock-privacy: 882-2, 10m Δ
  ublock-unbreak: 2325-2, 10m Δ
  ublock-quick-fixes: 190-21, 10m Δ
  easylist: 86833-175, 10m Δ
  easyprivacy: 50857-65, 10m Δ
  urlhaus-1: 13020-0, 10m
  plowe-0: 3729-1158, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 124 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  ecookie.nl: 2
 extended:
  ##.cookie-status-message
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Not seen.  The active rules on the site:

```
||ecookie.nl^$3p
##.avg-cookiebar
```

**Comment by mapx-** [comment]
the script:

    https://www.anwbvignetten.nl/static/version1709563258/frontend/ANWB/Autobahnvignetten/nl_NL/Magento_Theme/js/ecookiebar.js

**Comment by mapx-** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/b29ad070-bb44-4d6d-a7cc-13642daa6939)

**Comment by ryanbr** [comment]
All I see is these 2 items, no other blocked items.

**Comment by twiddle-hobbies** [comment]
@ryanbr 

If you block both `ecookie.nl/build` and `https://www.anwbvignetten.nl/static/version1709563258/frontend/ANWB/Autobahnvignetten/nl_NL/Magento_Theme/js/ecookiebar.js` (currently obvously) there is no cookie wall and the site still works.

Now the site is not broken anymore, but there is a cookie wall.
