### ISSUE TITLE
Photopea Blank Space

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#23557]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.photopea.com/
```

### Description

With uBO enabled, all ads are gone, but it leaves behind a pretty big blank space on the right side of the screen.

### Other extensions used

Bitwarden, BTRoblox, BPC, Dark Reader, Firefox Container Extension, IDM browser integration, simplelogin, tampermonkey, TTV PRO LOL, and TWP.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/09e863d7-bebb-43a7-97bd-cc47883f9141)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 233337
 cosmetic: 251445
 scriptlet: 50665
 html: 2035
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81260-3931, 12m
  adguard-mobile: 9317-56, 12m
  adguard-spyware-url: 1506-120, 12m
  adguard-spyware: 88714-1378, 12m
  block-lan: 66-0, 12m
  curben-phishing: 412-0, 12m
  adguard-social: 22894-53, 12m
  adguard-cookies: 29453-46, 12m
  ublock-cookies-adguard: 1086-13, 12m
  adguard-popup-overlays: 27272-1002, 12m
  adguard-mobile-app-banners: 5186-22, 12m
  adguard-other-annoyances: 14201-412, 12m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37977-109, 1h.26m Δ
  ublock-badware: 8529-0, 1h.26m Δ
  ublock-privacy: 882-2, 1h.26m Δ
  ublock-unbreak: 2325-2, 1h.26m Δ
  ublock-quick-fixes: 194-21, 1h.26m Δ
  easylist: 86839-1702, 1h.26m Δ
  easyprivacy: 50857-31407, 1h.26m Δ
  urlhaus-1: 13020-0, 12m
  plowe-0: 3729-1645, 12m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 373 ms (selfie)
 maxAssetCacheWait: 193 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  uniconsent.com: 2
 extended:
  ##+js(set-constant, console.clear, noopFunc)

```
</details>

**Comment by mapx-** [comment]
duplicate => https://github.com/uBlockOrigin/uAssets/discussions/19970
