### ISSUE TITLE
(nsfw) 4fans.gay: detection

### ISSUE THREAD

**Issue by keonolo** [uBlockOrigin/uAssets#23564]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
NSFW
https://4fans.gay/
```

### Description

Receiving Disable AdBlock Prompts That Do Not Go Away Even When Turning Off UBlock

### Other extensions used

None Besides Annoyances

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 154087
 cosmetic: 145107
 scriptlet: 33111
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 50963-253, 28m
  ublock-cookies-easylist: 1086-0, 28m
  adguard-popup-overlays: 27272-887, 10m
  adguard-mobile-app-banners: 5186-1104, 10m
  adguard-other-annoyances: 14201-352, 10m
  adguard-widgets: 2493-39, 10m
  easylist-annoyances: 4548-17, 11m
  easylist-chat: 191-0, 11m
  easylist-newsletters: 7313-12, 11m
  easylist-notifications: 2966-82, 11m
  ublock-annoyances: 6967-1142, 11m Δ
  dpollock-0: 11669-460, 9m
 default:
  user-filters: 0-0, never
  ublock-filters: 37850-621, 10m
  ublock-badware: 8527-0, 10m
  ublock-privacy: 881-0, 10m
  ublock-unbreak: 2268-2, 10m
  ublock-quick-fixes: 271-0, 10m
  easylist: 86839-805, 55m Δ
  easyprivacy: 50857-1007, 55m Δ
  urlhaus-1: 13165-0, 21h.30m
  plowe-0: 3729-0, 21h.30m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 532 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  4fans.gay: 3
  cdnm4m.nl: 1
  giggleostentatious.com: 1
  googletagmanager.com: 1
  magsrv.com: 2
  wp.com: 1
 extended:
  ##a[href="#back-to-top"]
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  ##.ads-wrapper
  ##.ads_code
  ##.jnews_popup_post_container
  ##.jscroll-to-top_link
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(noeval-if, /chp_?ad/)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(no-window-open-if)
  ###directAds

```

**Comment by mapx-** [comment]
- test using uBO defaults (settings + filter lists).
- do not use any other blocking extension

**Comment by keonolo** [comment]
Using default settings but when I click on a video, the video is blocked by prompt to disable adblock still.

**Comment by mapx-** [comment]
Still working fine on my side:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
