### ISSUE TITLE
6play.fr: detection

### ISSUE THREAD

**Issue by syaouanc** [uBlockOrigin/uAssets#23565]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.6play.fr/top-chef-la-brigade-cachee-p_16435/s15-e8-c_13067283`

### Category

detection

### Description

after a long wait time detects the ad blocker, sometimes it works anyway but probably 1/2...

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 134944
 cosmetic: 46584
 scriptlet: 20666
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86828-559, 27m
  easyprivacy: 50859-811, 26m
  plowe-0: 3729-0, 26m
  ublock-badware: 8527-0, 26m
  ublock-filters: 37812-296, 26m
  ublock-privacy: 881-0, 26m
  ublock-quick-fixes: 271-0, 26m
  ublock-unbreak: 2268-0, 26m
  urlhaus-1: 12835-0, 27m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 501 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 2
  estat.com: 1
  facebook.net: 1
  fwmrm.net: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imrworldwide.com: 1
  newrelic.com: 2
  outbrain.com: 1
  stickyadstv.com: 1
  tealiumiq.com: 3
  usabilla.com: 1
  youborafds01.com: 1
 extended:
  ##.ad-display
```
</details>

**Comment by mapx-** [comment]
enable the regional list `fr: AdGuard Français`
