### ISSUE TITLE
pixiv.net: breakage

### ISSUE THREAD

**Issue by MoonlightKOBE** [uBlockOrigin/uAssets#23562]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.pixiv.net/
```

### Description

When I open Pixiv, it loads many times and the page is not displayed properly.

### Other extensions used

Clean-Spam-Link-Tweet
Control Panel for Twitter
Enhancer for YouTube™
Facebook AdBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 113723
 cosmetic: 192063
 scriptlet: 13719
 html: 260
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  plowe-0: null
  JPN-1: null
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78606-133, 6m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98534-23020, 6m
  ublock-annoyances: 6911-225, 6m
  adguard-social: 22894-1633, 6m
  fanboy-thirdparty_social: 68-18, 6m
  fanboy-cookiemonster: 50965-50963, 6m
  fanboy-social: 15868-15868, 6m
 default:
  user-filters: 229-26, never
  easylist: 86828-125, 6m
  easyprivacy: 50859-180, 6m
  ublock-quick-fixes: 201-4, 6m
filterset (user): [array of 229 redacted]
trustedset:
 added: [array of 312 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 134 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 237 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
- reset uBO to defaults
- do not disable any uBO list (very bad => removed:  ublock-filters: null,  ublock-badware: null,   ublock-privacy: null,  ublock-unbreak: null)

add
`pixiv.net#@#+js(set-cookie-reload, privacy_policy_agreement, 5)`

@ryanbr

**Comment by D4niloMR** [comment]
The conflicts between EasyList's and AdGuard's `set-cookie-reload` sometimes happen and it's not hard to happen again, I think that uBO should choose between one of them.

**Comment by ryanbr** [comment]
This is an issue with ADG not ELC, since we have set the correct value.

**Comment by D4niloMR** [comment]
I meant that if there are two `set-cookie-reload` filters for the same site uBO should choose one of them and discard the other.
