### ISSUE TITLE
institutoaocp.org.br: nuisance

### ISSUE THREAD

**Issue by whocares89** [uBlockOrigin/uAssets#23568]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.institutoaocp.org.br/concursos/603`

### Category

nuisance

### Description

It's showing "this website uses cookies" message

### Other extensions used

Brave search
Dark background and light text
Firefox color
IDM integration module
Skip redirect
Stylus
Video speed controller

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 227684
 cosmetic: 271661
 scriptlet: 51719
 html: 2035
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/easylistportuguese.txt: 1850-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2623-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1079-0, now
  https://raw.githubusercontent.com/gijsdev/ublock-hide-yt-shorts/master/list.txt: 25-0, now
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 50967-122, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-9273, 5m
  adguard-generic: 81475-3947, now
  adguard-mobile: 9317-59, now
  adguard-spyware-url: 1506-230, now
  adguard-spyware: 88714-1383, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 39-0, never
  ublock-filters: 37976-128, 42m Δ
  ublock-badware: 8530-0, 42m Δ
  ublock-privacy: 882-49, 42m Δ
  ublock-unbreak: 2325-4, 42m Δ
  ublock-quick-fixes: 202-21, 42m Δ
  easylist: 86880-1721, 42m Δ
  easyprivacy: 50859-31456, 42m Δ
  urlhaus-1: 12835-0, now
  plowe-0: 3729-1316, now
  spa-1: 5595-294, now
filterset (user): [array of 39 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 677 ms (selfie)
 maxAssetCacheWait: 455 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`institutoaocp.org.br##.fixed.bottom-0:has-text(cookies)`

@ryanbr @Alex-302

**Comment by whocares89** [comment]
> add
> 
> `institutoaocp.org.br##.fixed.bottom-0:has-text(cookies)`
> 
> @ryanbr

It worked! Thanks
