### ISSUE TITLE
Waiting for ad click!

### ISSUE THREAD

**Issue by DogancanYr** [uBlockOrigin/uAssets#23566]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://cpmlink.net/3MqLAQ
```

### Description

.

### Other extensions used

 .

### Screenshot(s)

<details>
<summary>This site(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/90002969/80b70bf7-9e1f-468b-815c-8ad3a92b0c52)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 315177
 cosmetic: 374160
 scriptlet: 55872
 html: 2133
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81704-673, 8h.37m
  adguard-mobile: 9317-45, 8h.37m
  adguard-spyware-url: 1506-120, 8h.37m
  adguard-spyware: 88714-1331, 8h.37m
  block-lan: 66-0, 8d.3h.43m
  curben-phishing: 518-0, 5h.22m
  adguard-social: 22894-44, 8h.37m
  adguard-cookies: 29453-45, 8h.37m
  ublock-cookies-adguard: 1086-13, 1d.2h.37m
  adguard-popup-overlays: 27272-934, 8h.36m
  adguard-mobile-app-banners: 5186-22, 8h.36m
  adguard-other-annoyances: 14201-170, 8h.36m
  [46 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37977-4119, now
  ublock-badware: 8530-0, 2h.50m Δ
  ublock-privacy: 882-0, 2h.50m Δ
  ublock-unbreak: 2325-0, 2h.50m Δ
  ublock-quick-fixes: 201-0, 2h.50m Δ
  easylist: 86828-1822, now Δ
  easyprivacy: 50859-31379, now Δ
  urlhaus-1: 12835-0, 5h.21m
  plowe-0: 3729-1645, 1d.4h.37m
  TUR-0: 11368-91, 1d.6h.39m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 524 ms (selfie)
 maxAssetCacheWait: 317 ms
 cacheBackend: indexedDB
```
</details>

**Comment by u-RraaLL** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
