### ISSUE TITLE
drinkspartner.com: detection

### ISSUE THREAD

**Issue by preetam1409** [uBlockOrigin/uAssets#23561]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://drinkspartner.com/top-10-mba-colleges-in-the-world/`

### Category

detection

### Description

detects adblocker

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/43402156/82b55759-1afd-49a8-9883-53680c34b270)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 134953
 cosmetic: 46586
 scriptlet: 20694
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 17-0, never
  ublock-filters: 37850-417, now
  ublock-badware: 8528-0, now
  ublock-privacy: 881-0, now
  ublock-unbreak: 2268-0, now
  ublock-quick-fixes: 271-0, now
  easylist: 86828-455, now
  easyprivacy: 50859-811, now
  urlhaus-1: 12835-0, now
  plowe-0: 3729-0, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 143 ms (selfie)
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  cleverwebserver.com: 1
  clickiocdn.com: 1
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  mgid.com: 1
 extended:
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by mapx-** [comment]
@preetam1409 

ask for help here: https://github.com/uBlockOrigin/uAssets/discussions/17361

but you have to provide the original (shortener) link

**Comment by preetam1409** [comment]
https://drinkspartner.com/top-10-mba-colleges-in-the-world/

where shall I put this link ?
