### ISSUE TITLE
nhnieuws.nl: nuisance

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23567]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nhnieuws.nl/`

### Category

nuisance

### Description

There is a cookie notice. The cookie notice can be bypassed with
```
nhnieuws.nl##+js(set-local-storage-item, psh:cookies-other, false)
nhnieuws.nl##+js(set-local-storage-item, psh:cookies-seen, true)
nhnieuws.nl##+js(set-local-storage-item, psh:cookies-social, true)
```
although I am not sure what the preferred way is. I think `psh:cookies-social` needs to be set to `true` for YouTube/Twitter embeds to work though. 

Example page with YouTube embed `https://www.nhnieuws.nl/nieuws/327047/spectaculaire-beelden-het-is-alle-hens-aan-dek-op-zee-door-storm-ciaran`.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136775
 cosmetic: 91513
 scriptlet: 24284
 html: 1777
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  fanboy-cookiemonster: 50965-183, 20m
  ublock-cookies-easylist: 1086-3, 31m
 default:
  ublock-filters: 37977-109, 1h.30m Δ
  ublock-badware: 8530-0, 1h.30m Δ
  ublock-privacy: 882-2, 1h.30m Δ
  ublock-unbreak: 2325-2, 1h.30m Δ
  ublock-quick-fixes: 201-21, 1h.30m Δ
  easylist: 86828-176, 1h.30m Δ
  easyprivacy: 50859-64, 1h.30m Δ
  urlhaus-1: 12835-0, now
  plowe-0: 3729-1158, now
filterset (user): [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 134 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  nhnieuws.nl: 2
  aticdn.net: 2
  hotjar.com: 1
  optoutadvertising.com: 2
  rackcdn.com: 1
  scorecardresearch.com: 2
  smartocto.com: 2
```
</details>

**Comment by u-RraaLL** [comment]
I'd probably skip setting a choice for social. This way, whoever wants to see social content can explicitly click to agree to these cookies.

But I guess @Yuki2718 can decide since this is fixable by EL.

**Comment by Yuki2718** [comment]
> I'd probably skip setting a choice for social. This way, whoever wants to see social content can explicitly click to agree to these cookies.
> 

Without the rule embedded videos are just not shown and no prompt if you access from EU.

**Comment by u-RraaLL** [comment]
> Without the rule embedded videos are just not shown and no prompt if you access from EU.

I'm aware. There is an in-article link to accept them though. https://imgur.com/NyjOatf
