### ISSUE TITLE
tech.fingau.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#23575]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tech.fingau.com/mikrotik-vs-ubnt.html`

### Category

ads

### Description

fake download button

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/17d8fddb-d08e-4b2b-94f4-09a9ed313e16)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 143880
 cosmetic: 161184
 scriptlet: 33534
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8128-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 203-0, now
  adguard-other-annoyances: 14202-380, now
  adguard-popup-overlays: 27272-897, now
  easylist-annoyances: 4551-17, now
  easylist-chat: 194-0, now
  easylist-newsletters: 7316-10, now
  easylist-notifications: 2967-85, now
  fanboy-cookiemonster: 50969-256, now
  fanboy-social: 15868-10, now
  ublock-annoyances: 6963-52, now
  ublock-cookies-easylist: 1082-1082, now
 default:
  user-filters: 50-0, never
  easylist: 86869-645, now
  easyprivacy: 50859-86, now
  plowe-0: 3729-788, now
  ublock-badware: 8565-1, now
  ublock-filters: 37900-712, now
  ublock-privacy: 881-4, now
  ublock-quick-fixes: 274-4, now
  ublock-unbreak: 2268-21, now
  urlhaus-1: 12690-0, now
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 925 ms (selfie)
 maxAssetCacheWait: 468 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  68d6b65e65.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ###gdpr-cookie-notice
```
</details>

**Comment by BlazeFTL** [comment]
> Is it from a shortener link?

New Domain For Uploadrar

**Comment by BlazeFTL** [comment]
Use In My Filters
```
tech.fingau.com,rahim-soft.com,uploadrar.com##a[href][target="_blank"]
tech.fingau.com,rahim-soft.com,uploadrar.*##+js(nano-stb, tick, 1000)
tech.fingau.com,rahim-soft.com,uploadrar.*##[class^="banner"]:not(:has(#commonId))
tech.fingau.com,rahim-soft.com,uploadrar.*##div.download0page:not(:has(.mngez-free-download))
tech.fingau.com,rahim-soft.com,uploadrar.*###wrapper, .banner2:style(display: initial !important;)
tech.fingau.com,rahim-soft.com,uploadrar.*##.desc:style(width:auto! important;)
tech.fingau.com,rahim-soft.com,uploadrar.com##.mngez-premium-download, ul, .txt, [id^="footer"], footer, #open_preferences_center, #news_last, .icofont-zipped, .report, .menufooter:remove()

**Comment by mapx-** [comment]
for https://github.com/uBlockOrigin/uAssets/discussions/17361
