### ISSUE TITLE
Buzzheavier: ad

### ISSUE THREAD

**Issue by DogancanYr** [uBlockOrigin/uAssets#23574]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://buzzheavier.com/f/GMz2pFL2EAA=
```

### Description

.

### Other extensions used

 .

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 315269
 cosmetic: 374163
 scriptlet: 55885
 html: 2133
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81704-3944, 23h.6m
  adguard-mobile: 9317-56, 23h.5m
  adguard-spyware-url: 1506-120, 23h.5m
  adguard-spyware: 88714-1378, 23h.5m
  block-lan: 66-0, 8d.18h.11m
  curben-phishing: 518-0, 19h.50m
  adguard-social: 22894-53, 23h.6m
  adguard-cookies: 29453-46, 23h.5m
  ublock-cookies-adguard: 1086-13, 1d.17h.5m
  adguard-popup-overlays: 27272-1002, 23h.4m
  adguard-mobile-app-banners: 5186-22, 23h.5m
  adguard-other-annoyances: 14201-412, 23h.5m
  [46 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38027-109, 2m Δ
  ublock-badware: 8567-0, 2m Δ
  ublock-privacy: 882-2, 2m Δ
  ublock-unbreak: 2325-2, 2m Δ
  ublock-quick-fixes: 204-21, 2m Δ
  easylist: 86869-1911, 2m Δ
  easyprivacy: 50859-31407, 2m Δ
  urlhaus-1: 12835-0, 19h.50m
  plowe-0: 3729-1645, 1d.19h.6m
  TUR-0: 11368-99, 1d.21h.8m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 428 ms (selfie)
 maxAssetCacheWait: 269 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
buzzheavier.com##[onclick="downloadAd()"]
```

@ryanbr
