### ISSUE TITLE
Pandora.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2357]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.pandora.com/station/play/3920351886735403660`

### Describe the issue

Webpage gets stuck on loading screen

### Settings

- Default settings

### Notes
```
@@||www.pandora.com/web-version/*_googleAnalytics.*.js$script,domain=pandora.com
@@||www.pandora.com/web-version/*comscore.*.js$script,domain=www.pandora.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.pandora.com
```
This can fix it, but there is probably a much better solution.

**Comment by mapx-** [comment]
it works fine for me
