### ISSUE TITLE
aurorastore.org: badware

### ISSUE THREAD

**Issue by lucasmz-dev** [uBlockOrigin/uAssets#23570]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://aurorastore.org
```

### Description

This domain does not seem to be official. The official domain for Aurora is https://auroraoss.com. Not even talking about the obvious issues with references to 'game mod'. Right now it doesn't seem to be spreading malware as it seems to redirect to the official downloads, even if broken, but the future risk is there.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136113
 cosmetic: 50270
 scriptlet: 19726
 html: 1777
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37981-109, 1h.11m Δ
  ublock-badware: 8530-0, 1h.11m Δ
  ublock-privacy: 882-2, 1h.11m Δ
  ublock-unbreak: 2325-2, 1h.11m Δ
  ublock-quick-fixes: 202-21, 1h.11m Δ
  easylist: 86869-177, 1h.11m Δ
  easyprivacy: 50859-64, 1h.11m Δ
  urlhaus-1: 12690-0, now
  plowe-0: 3729-1160, now
  spa-1: 5595-89, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 292 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 3
 extended:
  ##ins.adsbygoogle[data-ad-slot]

```
</details>

**Comment by stephenhawk8054** [comment]
For non-authentication website, better to block when there's obvious evidence of malware. Otherwise, when website's owner complains, we don't have any reliable evidence to back up the decision.

**Comment by JobcenterTycoon** [comment]
0 VT detections https://www.virustotal.com/gui/url/9c384314235a976099a8c75a12c9007bd55064f6f9fea73d4c10a8e5d9213293?nocache=1

We don’t block just because the site "seems to be unofficial", there must be a thread like malware, phishing, spam or something.

**Comment by Monoxide8969** [comment]
> We don’t block just because the site "seems to be unofficial", there must be a thread like malware, phishing, spam, scam or something.

Very strongly disagree, the owner of aurorastore.org is actively impersonating the dev (which is illegal), providing outdated downloads from an unofficial source and asking users for money. This could at best give a bad impression of the project to a user that stumbles on the website (which damages the dev's image) and misdirect donations or make users install malware at worst:

1.  https://aurorastore.org/about-us/
     > the developer of Aurora Store is Rahul Kumar Patel and he is also the admin of this blog

     Not true, he is NOT the admin of [aurorastore.org](https://aurorastore.org/)

2. https://aurorastore.org/contact-us/ they link to unofficial social pages that use Aurora Store branding without specifying anywhere they aren't official pages.
3.  They have a [donation page](https://aurorastore.org/donate/), where the paypal and liberapay links are the original dev's but they are also small and at the end of the page. Before those, there are links to BTC and Ethereum wallets that do not appear in the official Aurora Store Gitlab page.
4. The original dev [directly asked](https://t.me/AuroraSupport/392247) them to put a disclaimer on the website to let users know it's not official, they never did.
5. [aurorastore.org](https://aurorastore.org/aurora-store-download/) presents itself as official 

     > Step 1. Visit the official Aurora Store website or open your most preferred browser and click on the link below – https://aurorastore.org/
6. In their homepage, they seem to offer a legit download of an outdated Aurora store version, but they also link to some roblox hack thing shit (which I'll be reporting as badware risks in another issue), an App Worden apk (no idea what it's about but they also misspelled it), and an Aurora Wallpapers apk (?)

I don't know what else it needs to be said for this to be flagged as potentially malicious.

**Comment by stephenhawk8054** [comment]
> I don't know what else it needs to be said for this to be flagged as potentially malicious.

As I said above, reporters usually just report the sites and done, leaving us having to deal with all of the complaints later, and none of the reporters showing up after that to help us.

That's why we always need reliable evidences and arguments before blocking a site. "Potentially harmful", "at best", "at worst"... are not strong enough arguments for us to reply for the complaints after that. You can comment whatever to us now, but we are always the ones who have to answer the websites' owners complaints later.

**Comment by Monoxide8969** [comment]
Fair enough, even though it varies from case to case. Thank you for your work and sorry if I've been overly aggressive about it.
