### ISSUE TITLE
blocklayer.com: detection

### ISSUE THREAD

**Issue by jmilljr24** [uBlockOrigin/uAssets#23576]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.blocklayer.com/roof/skillioneng`

### Category

detection

### Description

Pop up requesting to allow ads when ublock is enabled. It is possible to remove the pop up with the element picker, however certain javascript features are disable on the site until you disable ublock and allow ads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2024-05-05 12-05-00](https://github.com/uBlockOrigin/uAssets/assets/16829344/e09aea83-4766-420a-8e79-e126eca8f6ee)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 144860
 cosmetic: 167644
 scriptlet: 32546
 html: 2035
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29465-38, 1m
  ublock-cookies-adguard: 1086-13, 1m
  adguard-popup-overlays: 27272-222, 1m
  adguard-mobile-app-banners: 5186-19, 1m
  adguard-other-annoyances: 14212-294, 1m
  adguard-widgets: 2493-7, 1m
  easylist-annoyances: 4551-285, 1m
  easylist-chat: 194-16, 1m
  fanboy-cookiemonster: 67112-20042, 1m
  ublock-cookies-easylist: 1086-1086, 1m
  easylist-newsletters: 7316-517, 1m
  easylist-notifications: 2969-1527, 1m
  [1 lists not shown]: [too many]
 default:
  user-filters: 20-2, never
  ublock-filters: 38031-109, 9m
  ublock-badware: 8576-0, 9m
  ublock-privacy: 882-2, 9m
  ublock-unbreak: 2325-2, 9m
  ublock-quick-fixes: 208-25, 9m
  easylist: 86873-178, 9m
  easyprivacy: 50859-65, 9m
  urlhaus-1: 12795-0, 9m
  plowe-0: 3729-1161, 9m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2865 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by BlazeFTL** [comment]
Test
```
blocklayer.com##+js(nostif, getComputedStyle)

**Comment by jmilljr24** [comment]
> Test
> 
> ```
> blocklayer.com##+js(nostif, getComputedStyle)
> ```

@BlazeFTL That resolves the issue. Thanks!
