### ISSUE TITLE
[nsfw] 4126.0bye.com: ads

### ISSUE THREAD

**Issue by LeArbustoh** [uBlockOrigin/uAssets#23583]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://4126.0bye.com/lp_i35_yrfktmkc.html?ymid=1714970393099910TCRTV431951068294V5&source=8312416-1560383409-3930541253&test=1b&zoneid=7374538&cnt=4126`

### Category

ads

### Description

Idk.

### Other extensions used

Decentraleyes.

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/157625527/6a1f7167-04a2-4348-ba39-f915f1ce6040

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 125
filterset (summary):
 network: 137665
 cosmetic: 54863
 scriptlet: 19399
 html: 1778
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38386-110, now Δ
  ublock-badware: 8585-0, now Δ
  ublock-privacy: 882-2, now Δ
  ublock-unbreak: 2328-2, now Δ
  ublock-quick-fixes: 203-25, now Δ
  adguard-mobile: 9322-64, now
  easylist: 87356-221, now Δ
  easyprivacy: 50861-73, now Δ
  urlhaus-1: 13930-0, now
  plowe-0: 3731-1234, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2120 ms (selfie)
 maxAssetCacheWait: 177 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  oungimuk.net: 1
```
</details>

**Comment by mapx-** [comment]
provide the original page
