### ISSUE TITLE
nrc.nl: nuisance

### ISSUE THREAD

**Issue by twiddle-hobbies** [uBlockOrigin/uAssets#23586]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nrc.nl/`

### Category

nuisance

### Description

There is a notification popup. I cannot get to reliably reproduce the popup. But it can be blocked by
```
nrc.nl##.site-notification
```

### Other extensions used

none

### Screenshot(s)

<img width="1440" alt="Screenshot of element picker blocking notification popup" src="https://github.com/uBlockOrigin/uAssets/assets/167568449/0a523f64-3a6e-453e-a839-5308f02d2fda">

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 137050
 cosmetic: 50735
 scriptlet: 19377
 html: 1777
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/easylistdutch.txt: 1770-0, 5m
  easylist-notifications: 2969-82, never
 default:
  ublock-filters: 38084-109, 20m Δ
  ublock-badware: 8591-0, 20m Δ
  ublock-privacy: 882-2, 20m Δ
  ublock-unbreak: 2325-2, 20m Δ
  ublock-quick-fixes: 203-25, 20m Δ
  easylist: 87352-164, 20m Δ
  easyprivacy: 50861-66, 20m Δ
  urlhaus-1: 13930-0, 20m
  plowe-0: 3731-1160, 8m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 626 ms
 maxAssetCacheWait: 459 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  nrc.nl: 1
  chartbeat.com: 2
  googletagmanager.com: 1
  parsely.com: 1
  scorecardresearch.com: 2
 extended:
  ##.banner
  ##div[class^="native-ad-"]
```
</details>

**Comment by stephenhawk8054** [comment]
For simple filters that are compatible with EasyList, please report to EL's repo next time: https://github.com/easylist/easylist/issues
