### ISSUE TITLE
offerpagehub.fun: detection

### ISSUE THREAD

**Issue by preetam1409** [uBlockOrigin/uAssets#23582]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://offerpagehub.fun/`

### Category

detection

### Description

original link 
https://offerlinks.in/erEmee

adblock detected in 
https://offerpagehub.fun/

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/43402156/919b7c5a-3fa5-4332-b19f-836b242981ec)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136186
 cosmetic: 46985
 scriptlet: 20697
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 17-0, never
  ublock-filters: 37850-311, now
  ublock-badware: 8579-0, now
  ublock-privacy: 881-0, now
  ublock-unbreak: 2268-0, now
  ublock-quick-fixes: 273-0, 7m Δ
  easylist: 87314-564, now
  easyprivacy: 50860-811, now
  urlhaus-1: 13930-0, 7m
  plowe-0: 3731-0, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 126 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  a-ads.com: 20
  demand.supply: 1
  doubleclick.net: 1
  googlesyndication.com: 3
  googletagmanager.com: 2
  hooliganmedia.com: 1
  news-selaxe.com: 1
  punoocke.com: 1
 extended:
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by BlazeFTL** [comment]
Test In My Filters
```
offerpagehub.fun##+js(noeval-if, ads)
offerpagehub.fun##+js(nano-sib, getElementById, *)
offerpagehub.fun##b[style*="display: inline-block;"]
first.offerlinks.in,offerpagehub.fun##button[onclick*="window.location.href="]
! Remove This Last Line If You Ever Get Blank Page
offerpagehub.fun##.site

**Comment by preetam1409** [comment]
yes its working , great thanks a lot

**Comment by mapx-** [comment]
for https://github.com/uBlockOrigin/uAssets/discussions/17361
