### ISSUE TITLE
modescanlator.com: detection

### ISSUE THREAD

**Issue by louganlbc** [uBlockOrigin/uAssets#23595]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
modescanlator.com
```

### Description

This site is detecting ublock

### Other extensions used

Free Download Manager
Voltar Dislikes do Youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/56934909/573f3d43-1cdf-464f-87e2-d6ff934dd599)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 233035
 cosmetic: 255958
 scriptlet: 51187
 html: 2035
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81815-3979, now
  adguard-mobile: 9322-56, now
  adguard-spyware-url: 1506-120, now
  block-lan: 66-0, now
  curben-phishing: 62-0, now
  adguard-social: 22900-49, now
  fanboy-thirdparty_social: 68-3, 1h.18m
  fanboy-cookiemonster: 50980-186, now
  fanboy-social: 15869-741, now
  ublock-annoyances: 6892-108, now
  dpollock-0: 11670-439, now
  adguard-spyware: 86415-32907, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 17-2, never
  ublock-filters: 38093-109, now
  ublock-badware: 8521-0, now
  ublock-privacy: 884-2, now
  ublock-unbreak: 2325-2, now
  ublock-quick-fixes: 193-18, now
  easylist: 87391-1905, now
  easyprivacy: 50861-169, now
  urlhaus-1: 13920-0, now
  plowe-0: 3731-1589, now
  spa-1: 5601-97, now
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 16 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2536 ms (selfie)
 maxAssetCacheWait: 230 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 no-popups: true
 no-remote-fonts: true
 network:
  modescanlator.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ###teaser3
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(prevent-fetch, ads_block.txt)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
modescanlator.com##+js(no-fetch-if, googlesyndication)
```

@Yuki2718 For Adguard Portuguese

**Comment by louganlbc** [comment]
Yes Portuguese Brazil

Em seg, 6 de mai de 2024 23:44, stephenhawk8054 ***@***.***>
escreveu:

**Comment by Yuki2718** [comment]
I can't reporoduce.

**Comment by D4niloMR** [comment]
I can reproduce on Firefox.
