### ISSUE TITLE
luxa.org: ads

### ISSUE THREAD

**Issue by juarez-spa3** [uBlockOrigin/uAssets#23598]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.luxa.org/image/border`

### Category

ads

### Description

Ad spaces

### Other extensions used

TWP translate
Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![b1](https://github.com/uBlockOrigin/uAssets/assets/153795294/8b8d44a6-06ed-4057-bef0-19b8a2257957)
![b2](https://github.com/uBlockOrigin/uAssets/assets/153795294/066ca9ca-8d4b-4d09-9850-1d6be05f00bc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136482
 cosmetic: 48632
 scriptlet: 23911
 html: 2035
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6892-36, never
 default:
  user-filters: 0-0, never
  ublock-filters: 38088-109, 9m
  ublock-badware: 8576-0, 9m
  ublock-privacy: 884-2, 9m
  ublock-unbreak: 2325-2, 9m
  ublock-quick-fixes: 193-18, 9m
  easylist: 87391-161, 9m
  easyprivacy: 50859-65, 9m
  urlhaus-1: 13825-0, 9m
  plowe-0: 3731-1160, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4267 ms
 maxAssetCacheWait: 479 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  clarity.ms: 1
  googlesyndication.com: 5
  gstatic.com: 1
  yandex.com: 4
  yandex.ru: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
luxa.org##.MuiContainer-root:has(> ins.adsbygoogle)
```

@ryanbr 

---

@juarez-spa3 For ads placeholders, please report to https://github.com/easylist/easylist/issues next time
