### ISSUE TITLE
dk.pcpartpicker.com: breakage

### ISSUE THREAD

**Issue by Sundanian** [uBlockOrigin/uAssets#23590]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dk.pcpartpicker.com/product/3hyH99/amd-ryzen-7-7800x3d-42-ghz-8-core-processor-100-100000910wof`

### Category

breakage

### Description

Seems some of the merchant links break. I've been in contact with pcpartpicker.com and they suggested trying to disable. And sure enough, the merchant links and logo reappear. The links likely go trough some tracking, but since it's part of the main functionality of the website, I would rather omit blocking the links and still maintains other adblocking. 

### Other extensions used

Dearrow, privacy badger, sponsor block, Web archives. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-05-06-20-13-10-76_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/11421633/978aaeb8-f2ed-4aef-af42-6711e1662514)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 125
filterset (summary):
 network: 139145
 cosmetic: 58287
 scriptlet: 19450
 html: 1779
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38415-110, now
  ublock-badware: 8515-0, now
  ublock-privacy: 884-2, now
  ublock-unbreak: 2328-2, now
  ublock-quick-fixes: 193-18, now
  adguard-mobile: 9322-64, now
  easylist: 87363-221, now
  easyprivacy: 50861-73, now
  urlhaus-1: 13920-0, 1h.13m
  plowe-0: 3731-1234, now
  NOR-0: 5058-55, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1416 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##a[href*="online.adservicemedia.dk"]
```
</details>

**Comment by mapx-** [comment]
- report directly at easylist repository
- however, similar issues were rejected for tracking reasons

**Comment by ryanbr** [comment]
Using ad/tracking servers for clicks, doesn't stop the user from clicking on them. But shouldn't be "fixed".
