### ISSUE TITLE
encycarpedia.com: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#23593]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.encycarpedia.com/`

### Category

ads

### Description

It shows "Ad" where the ad banner is supposed to be. The banners are at the top and bottom (sticky) of the page.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/50150516/f8d5fe83-1d53-4ac0-be6f-43a0a75c3a14)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 230829
 cosmetic: 240200
 scriptlet: 48436
 html: 0
listset (total-discarded, last-updated):
 added:
  ROU-1: 1380-1, 12m
  adguard-cookies: 29501-51, 12m
  adguard-generic: 81815-3491, 12m
  adguard-other-annoyances: 14217-296, 12m
  adguard-popup-overlays: 27303-1554, 12m
  adguard-social: 22900-159, 12m
  adguard-spyware: 86415-31747, 12m
  adguard-spyware-url: 1506-5, 12m
  adguard-widgets: 2493-17, 12m
  block-lan: 66-0, 12m
  curben-phishing: 519-0, 12m
  dpollock-0: 11670-9, 12m
  [8 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 87363-759, 44m Δ
  easyprivacy: 50861-254, 44m Δ
  plowe-0: 3731-1232, 12m
  ublock-badware: 8519-1, 44m Δ
  ublock-filters: 37966-4060, 44m Δ
  ublock-privacy: 883-241, 44m Δ
  ublock-quick-fixes: 264-1, 44m Δ
  ublock-unbreak: 2268-72, 44m Δ
  urlhaus-1: 13920-0, 12m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 55 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1477 ms (selfie)
 maxAssetCacheWait: 315 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google.com: 2
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by LightAndy1** [comment]
Not sure it works, but I hope this helps:
```txt
encycarpedia.com###cac98
encycarpedia.com###baa
```

**Comment by stephenhawk8054** [comment]
```adb
encycarpedia.com##.cac
```

@ryanbr
