### ISSUE TITLE
fastcompany.com: nuisance

### ISSUE THREAD

**Issue by lrdoftheblings** [uBlockOrigin/uAssets#23596]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.fastcompany.com/91117788/how-bitwarden-is-fending-off-tech-giants`

### Category

nuisance

### Description

Video overlay

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240506-181236](https://github.com/uBlockOrigin/uAssets/assets/99747685/78c04f24-83e0-46d1-a0f1-143117f973ef)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 125
filterset (summary):
 network: 137595
 cosmetic: 54870
 scriptlet: 19424
 html: 1778
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38420-110, now
  ublock-badware: 8515-0, now
  ublock-privacy: 884-2, now
  ublock-unbreak: 2328-2, now
  ublock-quick-fixes: 204-25, now
  adguard-mobile: 9322-64, now
  easylist: 87363-221, now
  easyprivacy: 50861-73, now
  urlhaus-1: 13920-0, now
  plowe-0: 3731-1234, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2054 ms
 maxAssetCacheWait: 27 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  fastcompany.com: 4
  amazon-adsystem.com: 1
  cxense.com: 1
  dianomi.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwpltx.com: 7
  marketo.net: 2
  moatads.com: 4
  npttech.com: 1
  p-n.io: 2
  scorecardresearch.com: 2
 extended:
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##.dianomi_context
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
```
</details>

**Comment by mapx-** [comment]
add

```
fastcompany.com##.jw-floating-dismissible
fastcompany.com##.sticky:has(.ad-container)
fastcompany.com##.py-8
```
