### ISSUE TITLE
mp3semti.com: ads

### ISSUE THREAD

**Issue by juarez-spa3** [uBlockOrigin/uAssets#23591]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mp3semti.com/`

### Category

ads

### Description

These three websites shows a fake download window loaded from ``https://yonderdim.com/cdn/banner/banner_tr.min.js`` 
This `||yonderdim.com^` rule fixes the problem

```
https://mp3semti.com/
```
```
https://www.mp3indirdur.net/
```
```
https://fullindirsene.net/
```

### Other extensions used

TWP Translate
Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pppppppppppppppppppppp](https://github.com/uBlockOrigin/uAssets/assets/153795294/a31d42f9-38dd-4fd3-95b9-1c0ae7a523d5)
![sde](https://github.com/uBlockOrigin/uAssets/assets/153795294/20590f12-eb74-4e0b-ae3d-ea5d88eccdb1)
![cccc](https://github.com/uBlockOrigin/uAssets/assets/153795294/ff1a9fcc-287a-4f4b-9eac-425b3aec0c57)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136135
 cosmetic: 46537
 scriptlet: 19351
 html: 1777
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38088-109, now
  ublock-badware: 8591-0, now
  ublock-privacy: 884-2, now
  ublock-unbreak: 2325-2, now
  ublock-quick-fixes: 203-25, now
  easylist: 86869-160, now
  easyprivacy: 50861-64, now
  urlhaus-1: 13920-0, now
  plowe-0: 3731-1160, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5839 ms
 maxAssetCacheWait: 1214 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  google.com: 4
  googletagmanager.com: 1
  push-sdk.net: 1
  yadro.ru: 1
  yeloads.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 turkey VPN needed because the ad server blocks requests outside of turkey.

**Comment by LightAndy1** [comment]
I've tried jaurez's suggestion, but didn't work, but I think this could work. I used a VPN to get the ad btw.
```txt
mp3semti.com##.yeloadsv2buton.yeloadsbutonv2-download
```
