### ISSUE TITLE
copyrightcontent.org: breakage

### ISSUE THREAD

**Issue by jkuerth** [uBlockOrigin/uAssets#23592]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://copyrightcontent.org
```

### Description

the URL below are being blocked incorrectly by uBlock. This script is a messaging system for site visitors and can be used as a paywall. It is not an ad inserter or ad serving platform. Please remove blocking for this URL:

URL: `https://copyrightcontent.org` 

### Other extensions used

no other extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by u-RraaLL** [comment]
All I see is "Page not found". Nothing is blocked in uBO.

On the URL: Click 🛡️ uBO's icon > 💬 Report > Click "Troubleshooting information" > Select all > Copy > Share it. [Video tutorial](https://reddit.com/link/17j6ygs/video/hvgibcylz5xb1/player)

**Comment by JobcenterTycoon** [comment]
The domain itself is not blocked. https://github.com/uBlockOrigin/uAssets/issues/8615

**Comment by mapx-** [comment]
@jkuerth provide the steps reproducing whatever issue. 
the home page redirects to some 404 error

**Comment by jkuerth** [comment]
The specific URK being blocked is http://copyrightcontent.org/unblocker as shown here: https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt

**Comment by jkuerth** [comment]
an example site using this script is MANITHAN.COM

**Comment by mapx-** [comment]
What exactly is broken ?

**Comment by jkuerth** [comment]
uBlock is blocking our URL which does not allow the script to run. We are not an ad inserter, we are not blocking or impacting uBlock, our URL shows on line 1056 on this link and need it removed please: https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt

**Comment by stephenhawk8054** [comment]
> What exactly is broken ?

And what breakages occur if the script cannot run? Describe it in details please.

**Comment by jkuerth** [comment]
uBlock is currently blocking the URL of our script. This is a service made for content creators to be able to offer an alternative to ad monetization and assist with gathering user consent. Site visitors can visit the websites with a microtransaction and avoid seeing ads.
The script does not add ads to the site, collect user data, or interfere with uBlock's script in any way; it is not supposed to be blocked by uBlock.
Any payment the site visitor makes goes directly to the site owner who created the content, 100% of it.
The breakage that uBlock causes if the script doesn't run prevents the publisher from offering something different to ads to monetize their site. It is puzzling to us why you'd be against this.
[copyrightcontent.org](https://copyrightcontent.org/) is not an adserver.
That domain allows publishers to engage visitors in a transparent way on the value exchange for their copyrighted content, it does not reinsert ads in any way.

**Comment by stephenhawk8054** [comment]
How can we reproduce the issue? I have accessed `https://manithan.com/`. Which steps should I do next to see the breakages?

**Comment by jkuerth** [comment]
the site would have to have uBlock installed to see the breakage. The breakage occurs because uBlock blocks the URL of our script, which is on line 1056 on this link: https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt

**Comment by stephenhawk8054** [comment]
I know. I installed uBO already. I see the script being blocked in uBO already. But I can't see the breakages.

**Which steps should I do next to see the breakages on `https://manithan.com/`?** The page looks normal for me:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/d7d04179-86b3-4bc5-a3c9-f00a72079836)

**Comment by jkuerth** [comment]
Attached is how the site looks without uBlock. With uBlock installed it should be showing our modal that is launched by our script, but the script is not able to run with our URL blocked by uBlock.

![unnamed (12)](https://github.com/uBlockOrigin/uAssets/assets/169093767/ba80d477-ffb9-4855-a0d0-cc03d685cc16)

**Comment by stephenhawk8054** [comment]
Yes, and uBO is blocking the ads as expected. Using ads as paywall and telling users to turn off blockers is not in line with uBO's scope about paywall. This is anti-adblock case for me

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/9d03e399-5308-4738-89f6-074e4fde97b2)

My opinion is keeping the filters. You can wait for other volunteers' opinions.

**Comment by dimisa-RUAdList** [comment]
This script is nothing more than an anti-adblock. Of course it must remain blocked.

**Comment by jkuerth** [comment]
The script is not anti-adblock. The script gives users the option and choice of how to contribute to the publisher providing original content. What you are showing in the screenshot is only one option, visitors also have the option to contribute through a micropayment, acting as a paywall, they are only prompted to turn off an ad blocker or open a new browser if the visitor chooses not to contribute. Ultimately, the visitor can determine how to proceed and the user is able to manage their own experience.

**Comment by JobcenterTycoon** [comment]
Same as https://github.com/uBlockOrigin/uAssets/issues/23592#issuecomment-2101087358
