### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by F4z** [uBlockOrigin/uAssets#236]
Google Chrome 55.0.2883.87 m (64-bit)
uBlock Origin 1.10.4

This website loads ads/script/something from `behind-the-scene` - `http://joemonster.org/`

![image](https://cloud.githubusercontent.com/assets/11742596/21407155/7d45889e-c7cf-11e6-930e-eff67f0d68e3.png)

![image](https://cloud.githubusercontent.com/assets/11742596/21407170/87fa1872-c7cf-11e6-8ad1-931b95625e36.png)

I know that I can hide them and these rules are in " POL: polskie filtry do Adblocka i uBlocka‎":
`joemonster.org##img[src^="data:image"]`
`joemonster.org##iframe[mysrc]`
`joemonster.org##a[style="cursor: pointer"][onclick^="window.location.href="][target="_blank"]`
but I would to know if is it possible to block this request without deleting `behind-the-scene` from "Whitelist"?

I ask about that, because if I delete `behind-the-scene` from "Whitelist" and add this rule - `||unblock.onaudience.com^$domain=behind-the-scene` to my filters, I do not see these ads anymore.

The same situation is on these websites:
`http://demotywatory.pl/`
`http://mistrzowie.org/`
`http://komixxy.pl/`

**Comment by gorhill** [comment]
Does `joemonster.org##script:inject(abort-on-property-write.js, ub_ct_load)` work well?

The site is using a [SharedWorker](https://developer.mozilla.org/en/docs/Web/API/SharedWorker), from which all network requests are reported as behind-the-scene.

**Comment by F4z** [comment]
Yes, this rule works, it was even in "POL: polskie filtry do Adblocka i uBlocka‎" - https://github.com/MajkiIT/polish-ads-filter/commit/ba714210747622990b819ca4fadb8fdc225707cc#diff-711027ed0794992ae3b8710d874f3df7L1530 but it has been deleted because rules with `##script:inject` break Adblock and Adblock Plus.

I asked to block `||unblock.onaudience.com^$domain=behind-the-scene`, becuase I think it is the easiest way to block these ads on all websites which use this - `http://www.onaudience.com/unblock` but maybe I am wrong.

**Comment by Piter432** [comment]
@F4z: Why not create a separate Polish filter for uBO and separate for AdBlock Plus?

**Comment by F4z** [comment]
@Piter432 we have a separate filter list for uBlock Origin - https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock_ublock.txt

**Comment by Piter432** [comment]
@F4z: Okay, but I see that there's some filters to eliminate cookie info on wykop.pl. These should be in cookies filters list for Polish sites, unless you deleted that list.

**Comment by F4z** [comment]
@Piter432 if you have any question about Polish filter list, ask here please - https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by gorhill** [comment]
Another solution to completely prevent workers:

    joemonster.org##script:inject(csp.js, worker-src 'none')

Or to prevent workers from 3rd-party scripts:

    joemonster.org##script:inject(csp.js, worker-src 'self')
