### ISSUE TITLE
spotlightstores.com: breakage

### ISSUE THREAD

**Issue by michaelmurfy** [uBlockOrigin/uAssets#23600]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://spotlightstores.com
https://www.spotlightstores.com
```

### Description

Outright block (False Positive) - this is a legitimate retail site (Spotlight Australia / New Zealand).

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136223
 cosmetic: 46874
 scriptlet: 19330
 html: 1777
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38069-109, 17m Δ
  ublock-badware: 8521-0, 17m Δ
  ublock-privacy: 885-2, 17m Δ
  ublock-unbreak: 2327-2, 17m Δ
  ublock-quick-fixes: 193-18, 17m Δ
  easylist: 87357-161, 17m Δ
  easyprivacy: 50868-65, 17m Δ
  urlhaus-1: 13920-0, 10h.21m
  plowe-0: 3731-1160, 23h.9m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 525 ms (selfie)
 maxAssetCacheWait: 34 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
