### ISSUE TITLE
[nsfw] ru.bongacams21.com: popups

### ISSUE THREAD

**Issue by hikezz23** [uBlockOrigin/uAssets#23604]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ru.bongacams21.com/?bcs=b3duZmRlZmVhODg1ZmQ0ZDlmN2U1MTQwNDhkYTdlNDgyNTI1OjoxOTE4MDA6Ojo6Ojo3SEZDQUdCMFUtRE40a1ROYzo6NzkwNTAwOjowOjoxOjoxOjo6OjA6OmRlZmF1bHQ6OjA~`

### Category

popups

### Description

edffgdd

### Other extensions used

fgdfg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 153526
 cosmetic: 67543
 scriptlet: 22146
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37942-294, 26m Δ
  ublock-badware: 8519-0, 26m Δ
  ublock-privacy: 884-0, 26m Δ
  ublock-unbreak: 2270-0, 26m Δ
  ublock-quick-fixes: 264-0, 26m Δ
  easylist: 87364-568, 26m Δ
  easyprivacy: 50868-811, 26m Δ
  urlhaus-1: 13865-0, 26m
  plowe-0: 3731-0, now
  RUS-0: 39459-119, 16m Δ
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 324 ms (selfie)
 maxAssetCacheWait: 98 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Do you mean this `bongacams21` stuff is the popup ?

**Comment by mapx-** [comment]
enable [AdGuard – Popup Overlays](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-popup-overlays)
