### ISSUE TITLE
[NSFW] luxuretv.com all domains missed ads

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2360]
### URL(s) where the issue occurs

```
http://luxuretv.com/videos/le-liveshow-torride-d---une-belle-blondasse-en-bikini-57992.html
http://en.luxuretv.com/videos/le-liveshow-torride-d---une-belle-blondasse-en-bikini-57992.html
http://es.luxuretv.com/videos/le-liveshow-torride-d---une-belle-blondasse-en-bikini-57992.html
http://de.luxuretv.com/videos/le-liveshow-torride-d---une-belle-blondasse-en-bikini-57992.html
```

### Describe the issue

Missed ads urls on page and visible elements of active advertisements.

### Screenshot(s)

![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40502707-b5371c02-5f83-11e8-8492-16dda6eef36b.jpg)

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default unmodified / untouched.

### Notes

Some ads on the pages have been missed and are still visible to users.

Popup ads are loaded in via :

```
||luxuretv.com/includes/pop/*
```

**Comment by mapx-** [comment]
The popups are already blocked (by easylist)

You can hide the top row using
`luxuretv.com###lien`

The other sites luxury club ae from the same "galaxy" so nothing  wrong.
