### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by crimsonxina** [uBlockOrigin/uAssets#23605]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://open.spotify.com/playlist/3f1dhPsof0uWPBQFKWZm33
```

### Description

It used to play Spotify by skipping ads and playing music but now it won't launch it

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://github.com/uBlockOrigin/uAssets/assets/169191007/338e034e-d1b5-4647-a9c6-72e292bdd143

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by dportvine** [comment]
What I see when simulating mobile UA.

<details>
<summary>Screen</summary>

![2024-05-08_084101](https://github.com/uBlockOrigin/uAssets/assets/111344219/acdcccc5-323a-4b32-b7a8-9e564f9e5d6e)
![2024-05-08_084146](https://github.com/uBlockOrigin/uAssets/assets/111344219/44bfa6a9-be75-47ff-8f35-b4fdb6a53f96)
</details>

**Comment by mapx-** [comment]
- your details are not visible
- use last FF mobile, last uBO version
