### ISSUE TITLE
wawacity.tokyo: popups

### ISSUE THREAD

**Issue by zorkxy** [uBlockOrigin/uAssets#23615]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wawacity.tokyo/`

### Category

popups

### Description

A lot of popup on this web page appear when we click on an item (category for example)
It has blocked fine in the past with uBO

### Other extensions used

1password
Return Youtube Dislike
Microsoft Rewards

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 136932
 cosmetic: 46961
 scriptlet: 20766
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37967-294, 2m
  ublock-badware: 8560-0, 2m
  ublock-privacy: 884-0, 2m
  ublock-unbreak: 2271-0, 2m
  ublock-quick-fixes: 265-0, 2m
  easylist: 87357-544, 2m
  easyprivacy: 50870-811, 2m
  urlhaus-1: 14555-0, 2m
  plowe-0: 3731-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 613 ms
 maxAssetCacheWait: 9 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  wawacity.tokyo: 1
  kwbgmufi.com: 1
  youradexchange.com: 1
 extended:
  ##+js(abort-on-stack-trace, String.prototype.charCodeAt, _0x)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, JSON.parse, break;case $.)
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
wawacity.tokyo##+js(acs, addEventListener, runPop)
