### ISSUE TITLE
translate.google.com: nuisance

### ISSUE THREAD

**Issue by moninah850** [uBlockOrigin/uAssets#23611]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
translate.google.com
```

### Description

"consent.google.com" does not disable when going to "translate.google.com". How can this problem be solved?

I open Firefox in private mode. I tried enabling all the filters in the filter list in uBlock Origin.

I tried adding a bunch of different filters (which I found on the Internet):
```
google.*##body > div[role="dialog"][aria-modal="true"][tabindex="0"][aria-labelledby]
google.*##body > div:nth-of-type(2) > div:nth-of-type(2)
google.*##^script:has-text(consentCookiePayload)
accounts.google.com/gsi/*
google.*##^responseheader(set-cookie)    
google.*##+js(cookie-remover, CONSENT)
consent.google.*##body > div[role="dialog"][aria-modal="true"][tabindex="0"][aria-labelledby]
consent.google.*##body > div:nth-of-type(2) > div:nth-of-type(2)
consent.google.*##^script:has-text(consentCookiePayload)
www.google.com##body:style(overflow:auto!important;)
google.*##+js(overlay-buster.js)
google.*##[src*="consent"]:upward(5)
google.*##html:style(overflow: auto !important;)
||consent.google.com^
google.*##+js(aeld, DOMContentLoaded, CONSENT)
www.google.*###before-appbar+div>div>div:matches-css(opacity: 0.7)
www.google.*###before-appbar+div>div>div:has(iframe)
||consent.google.*^
translate.google.com##[data-cbh="consent.google.com"]:remove()


```
None of the filters listed above work, except for these two:

```
google.*##^responseheader(set-cookie)    
google.*##+js(cookie-remover, CONSENT)
```
Now, if I enable all the filters in the filter list in uBlock Origin and add these two filters, and go to "translate.google.com", then "consent.google.com..." does not appear the first time, but if I try go to "translate.google.com" again, then "https://consent.google.com/m?continue=https://translate.google.com/?hl%3Dru&gl=DE&m=0&pc=t&cm=2&hl=ru&src=1" appears again.

### Other extensions used

none 

### Configuration

<details>

```yml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 165101
 cosmetic: 224308
 scriptlet: 34088
 html: 2056
listset (total-discarded, last-updated):
 added:
  adguard-social: 22908-877, 1h.56m
  adguard-cookies: 29531-69, 1h.56m
  adguard-popup-overlays: 27316-1671, 1h.56m
  adguard-mobile-app-banners: 5188-1098, 1h.56m
  adguard-other-annoyances: 14221-359, 1h.56m
  adguard-widgets: 2495-1, 1h.56m
  fanboy-thirdparty_social: 68-0, 1h.56m
  easylist-annoyances: 4568-127, 1h.56m
  easylist-chat: 194-16, 1h.56m
  fanboy-cookiemonster: 50988-3942, 1h.56m
  easylist-newsletters: 7328-12, 1h.56m
  easylist-notifications: 2972-3, 1h.56m
  [2 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 38048-484, 1h.56m
  ublock-badware: 8518-0, 1h.56m
  ublock-privacy: 888-0, 1h.56m
  ublock-unbreak: 2324-0, 1h.56m
  ublock-quick-fixes: 198-0, 1h.56m
  easylist: 87352-649, 1h.56m
  easyprivacy: 50861-944, 1h.55m
  urlhaus-1: 14555-0, 1h.55m
  plowe-0: 3731-0, 1h.55m
  RUS-0: 39487-554, 1h.57m
filterset (user): [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 579 ms (selfie)
 maxAssetCacheWait: 223 ms
```

</details>

**Comment by stephenhawk8054** [comment]
```yml
uBlock Origin: 1.51.0
Firefox: 115
```

You are using an old version of uBO, update Firefox and uBO to latest version (`1.57.2+`) and test again.

**Comment by moninah850** [comment]
> ```yaml
> uBlock Origin: 1.51.0
> Firefox: 115
> ```
> 
> You are using an old version of uBO, update Firefox and uBO to latest version (`1.57.2+`) and test again.

Yes, it really needed to be updated. The problem is solved. Thank you very much!

**Comment by moninah850** [comment]
Yes, uBlock Origin really needed an update. The problem is solved. Thank you very much!

> ```yaml
> uBlock Origin: 1.51.0
> Firefox: 115
> ```
> 
> You are using an old version of uBO, update Firefox and uBO to latest version (`1.57.2+`) and test again.

Yes, uBlock Origin really needed an update. The problem is solved. Thank you very much!

**Comment by moninah850** [comment]
> ```yaml
> uBlock Origin: 1.51.0
> Firefox: 115
> ```
> 
> You are using an old version of uBO, update Firefox and uBO to latest version (`1.57.2+`) and test again.

Yes, uBlock Origin really needed an update. The problem is solved. Thank you very much!
