### ISSUE TITLE
truckspring.com: breakage

### ISSUE THREAD

**Issue by decroft12** [uBlockOrigin/uAssets#23619]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.truckspring.com/products/Wheel-Nut-Outer-Cap-34-16-Thread-1375-Inch-High-15-Inch-Hex-Left__13-3054L.aspx
```

### Description

image blocked

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/169291272/725b60a2-ba15-4152-afef-02a366a9a45f)

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 136921
 cosmetic: 47207
 scriptlet: 19369
 html: 1783
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38091-110, 2h.34m Δ
  ublock-badware: 8562-0, 2h.34m Δ
  ublock-privacy: 890-2, 2h.34m Δ
  ublock-unbreak: 2328-2, 2h.34m Δ
  ublock-quick-fixes: 195-18, 2h.34m Δ
  easylist: 87727-159, 2h.34m Δ
  easyprivacy: 50870-65, 2h.34m Δ
  urlhaus-1: 14550-0, 2h.34m
  plowe-0: 3735-1161, 9d.7m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 177 ms (selfie)
 maxAssetCacheWait: 65 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 no-cosmetic-filtering: true
 network:
  github.com: 16
```yaml


```
</details>

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtag/js$script,domain=truckspring.com
@@||googletagmanager.com/gtm.js$script,domain=truckspring.com
```

@ryanbr

**Comment by decroft12** [comment]
Thanks for the response, but I don't understand it.  Add to where?  Filters?  This happens a lot, not just on this URL.

It appears that ublock is blocking java script( I see js$script in your response) , but in options " disable java script" is unchecked.

**Comment by huyszn** [comment]
Wait for this to be addressed in EasyPrivacy before closing the issue.
