### ISSUE TITLE
happymod.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#23626]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://happymod.com/add-watermark-on-photos-mod/com.SimplyEntertaining.addwatermark/download.html`

### Category

ads

### Description

ads

### Other extensions used

n

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/85b2ebd8-5629-4181-ad1c-c65dc8477c54)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 145986
 cosmetic: 162155
 scriptlet: 33683
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8165-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 204-0, now
  adguard-other-annoyances: 14218-369, now
  adguard-popup-overlays: 27328-918, now
  easylist-annoyances: 4578-17, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7357-11, now
  easylist-notifications: 2977-85, now
  fanboy-cookiemonster: 50991-256, now
  fanboy-social: 15934-10, now
  ublock-annoyances: 7014-1199, now
  ublock-cookies-easylist: 1143-0, now
 default:
  user-filters: 50-0, never
  easylist: 87737-631, now
  easyprivacy: 50872-86, now
  plowe-0: 3731-788, now
  ublock-badware: 8613-1, now
  ublock-filters: 37986-712, now
  ublock-privacy: 893-4, now
  ublock-quick-fixes: 273-1, 1h.48m Δ
  ublock-unbreak: 2274-20, now
  urlhaus-1: 14550-0, never
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2802 ms (selfie)
 maxAssetCacheWait: 1666 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##.container-right > div.righthm
  ##.back-to-top:not(body):not(html)
  ##.use_cookie
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||happymod.com/*/appx.php$subdocument
happymod.com##.appx
```

@ryanbr
