### ISSUE TITLE
[NSFW] camwhores.tv

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2362]
### URL(s) where the issue occurs
```
http://www.camwhores.tv/
```
### Describe the issue

Popup ads popads bypassing filters. (Obfuscated javascript in page source HTML code)

### Screenshot(s)

N/A Popads.

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default.

### Notes

Popup ads keep opening from some obfuscated JavaScript inside the page source code.

**Comment by dumbusernameidk** [comment]
`camwhores.tv` has popunders when clicking on videos it'll open a new page to `smljmp.com`.

**Comment by dumbusernameidk** [comment]
`camwhores.tv` popups back when clicking play/pause button on video.

**Comment by mapx-** [comment]
no new popup on my end

**Comment by dumbusernameidk** [comment]
try `https://www.camwhores.tv/videos/1125/livefreeforlife-2013-june-09-2-6c5fac00-e7e6443e2805b34a/`

so press play, then pause/unpause video and new tab opens `go.admjmp.com`.
