### ISSUE TITLE
smartstore.naver.com: nuisance

### ISSUE THREAD

**Issue by catagris** [uBlockOrigin/uAssets#23629]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://smartstore.naver.com/william3d/products/9909954542`

### Category

nuisance

### Description

Text selection is blocked

### Other extensions used

Google Translate, Markdown Here, 1Password, Clockify, 3CX Click2Call

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 137926
 cosmetic: 52867
 scriptlet: 25754
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4578-16, 9m
  ublock-annoyances: 7014-46, 9m
 default:
  user-filters: 4-0, never
  easylist: 87737-478, now
  easyprivacy: 50872-823, now
  plowe-0: 3731-0, now
  ublock-badware: 8613-0, now
  ublock-filters: 37989-386, now
  ublock-privacy: 893-1, now
  ublock-quick-fixes: 275-0, now
  ublock-unbreak: 2274-2, now
  urlhaus-1: 14470-0, 1h.7m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 52 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  naver.com: 1
  naver.net: 2
```
</details>

**Comment by catagris** [comment]
Tried adding custom filters as well which did not work:
```
*##+js(acis, disableSelection, reEnable)
*##+js(acis, document.oncontextmenu)
*##+js(aopr, document.ondragstart)
*##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
```

**Comment by catagris** [comment]
@mapx- Sorry but I tried adding your change to my filters and it doesn't fix the issue.

```naver.com##+js(aeld, /contextmenu|selectstart|dragstart/)```

**Comment by mapx-** [comment]
tested again, working fine in chrome/ firefox on my end
