### ISSUE TITLE
hdfilmcehennemi2.cx: ads

### ISSUE THREAD

**Issue by StarSOziOne** [uBlockOrigin/uAssets#23638]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hdfilmcehennemi2.cx/office-uprising-izle`

### Category

ads

### Description

Reklam

### Other extensions used

Reklam

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 138562
 cosmetic: 55806
 scriptlet: 22294
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  TUR-0: 11453-13, now
  easylist: 87716-483, now
  easyprivacy: 50877-815, now
  plowe-0: 3731-0, now
  ublock-badware: 8618-0, now
  ublock-filters: 37997-376, now
  ublock-privacy: 893-0, now
  ublock-quick-fixes: 259-0, now
  ublock-unbreak: 2274-0, now
  urlhaus-1: 14680-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 439 ms (selfie)
 maxAssetCacheWait: 110 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  dogt.xyz: 2
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
What ads? I don't see anything, though I see the rules @ghajini suggested hits. Why no screenshot or whatsoever?

**Comment by Yuki2718** [comment]
Okay, after waiting very long ads appeared, which was not mentioned.

**Comment by Yuki2718** [comment]
@ghajini It's not your due, the reporter's.

**Comment by StarSOziOne** [comment]
I've shared a screenshot for you, I don't know much about these things, I hope it helps. (By the way, on my computer in another location with Turktelekom internet infrastructure, I connect to the internet with the same user ID on my computer, the same site does not show any ads. However, the internet infrastructure of my home computer is Superonline. Maybe this will help to solve the problem). Also, when I manually block the ads by saying "block item" and refresh the page, the ads appear again.

If you don't have this ad, an admin can log in to my computer via remote connection and look deeper into the source of the problem :)


![Ekran görüntüsü 2024-05-11 175620](https://github.com/uBlockOrigin/uAssets/assets/76815200/e5afefc8-42d7-428a-865f-e8f3b075c01c)

**Comment by Yuki2718** [comment]
I fixed this in AdGuard Turkish, click on a clock icon next to `tr: AdGuard Turkish` in Filter lists pane to update the filter lists and check again.
