### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by freakedenough** [uBlockOrigin/uAssets#23636]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.derstandard.at/adblockwall/story/3000000219437/worum-es-bei-den-vorwuerfen-rund-um-lena-schilling-geht`

### Category

detection

### Description

austrias biggest new portal

### Other extensions used

i dont care cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-09 183741](https://github.com/uBlockOrigin/uAssets/assets/93607470/5c6843ab-81ee-4a48-86cb-8f0abd712dca)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 216684
 cosmetic: 209882
 scriptlet: 33431
 html: 2044
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1509-120, 2m
  adguard-spyware: 86424-427, 2m
  block-lan: 66-0, 2m
  curben-phishing: 197-0, 1m
  adguard-cookies: 29549-43, 1m
  ublock-cookies-adguard: 1143-13, 1m
  fanboy-cookiemonster: 67132-20022, 1m
  ublock-cookies-easylist: 1143-1143, 1m
  adguard-social: 22917-53, 1m
  fanboy-social: 15934-724, 1m
  fanboy-thirdparty_social: 68-18, 1m
  adguard-popup-overlays: 27334-1044, 1m
  [9 lists not shown]: [too many]
 default:
  user-filters: 165-10, never
  ublock-filters: 38111-110, 2m
  ublock-badware: 8615-0, 2m
  ublock-privacy: 894-2, 2m Δ
  ublock-unbreak: 2331-2, 2m
  ublock-quick-fixes: 207-21, 2m
  easylist: 87740-159, 2m
  easyprivacy: 50872-31459, 2m Δ
  urlhaus-1: 14680-0, 1m
  plowe-0: 3731-1586, 1m
  DEU-0: 7440-46, 1m
filterset (user): [array of 166 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 274 ms (selfie)
 maxAssetCacheWait: 188 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  derstandard.at: 2
  adition.com: 2
  google.com: 2
  iocnt.net: 1
  staticfiles.at: 2
  tinypass.com: 1
 extended:
  ##+js(trusted-replace-node-text, script, "adsDisabled":false, "a…
  ##+js(no-setTimeout-if, event, 3000)
  ##+js(trusted-set-cookie, consentUUID, 191c03c5-1154-4937-aa26-c…
```
</details>

**Comment by D4niloMR** [comment]
Does this work? 

```
||derstandard.at^$uritransform=/^\/adblockwall//
```

**Comment by freakedenough** [comment]
thank you, but no. my firefox says: 

Error: Redirect Error
An error occurred while connecting to www.derstandard.at.
This problem can sometimes occur if cookies are disabled or rejected.

**Comment by mapx-** [comment]
after adding the filter above OP link redirects to 
`https://www.derstandard.at/story/3000000219437/worum-es-bei-den-vorwuerfen-rund-um-lena-schilling-geht`

@freakedenough maybe you should disable `i dont care cookies`

**Comment by D4niloMR** [comment]
Try these:

```
@@||data-dda7d24eb2.derstandard.at/iomm/latest/manager/base/es6/bundle.js$script,1p
@@||imagesrv.adition.com/js/srp.js$script,domain=derstandard.at
@@||imagesrv.adition.com/js/aut.js$script,domain=derstandard.at
@@||px.staticfiles.at/dst-bi-px.js$script,domain=derstandard.at
@@||relay-client-c03.iocnt.net^$script,domain=derstandard.at
```
