### ISSUE TITLE
[NSFW] multiple adult porn sites showing popups

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2364]
### URL(s) where the issue occurs

```
http://www.bestialitytaboo.tv/video/14971/titty-fuck/
https://www.mujeresdesnudas.club/embed/1973/
```

```
https://www.zoosexnet.com/2459/mi-mujer-con-el-perro/
https://www.mujeresdesnudas.club/embed/195/
```

```
https://www.portalzoo.com/674/hungrian-horse-moviesnadja-is-a-vet/
https://www.bestialporn.com/embed/518/
```

```
https://www.bestialzoo.org/6790/aunt-visit/
https://www.mujeresdesnudas.club/embed/1762/
```

```
https://www.zookings.com/8041/riding-my-pony-dildo/
https://www.mujeresdesnudas.club/embed/816/
```

```
https://www.zootubex.tv/5903/speculum-slut/
https://www.mujeresdesnudas.club/embed/1615/
```

```
https://www.hispajotes.com/9526/step-btothers/
https://www.mujeresdesnudas.club/embed/2199/
```

```
https://www.fakingszoo.com/6358/self-pleasure/
https://www.mujeresdesnudas.club/embed/1806/
https://www.bestialporn.com/embed/75/
```

```
https://www.beastwomans.com/3231/queen-sext/
https://www.mynakedwife.video/embed/1543/
```

```
https://www.zootubex.us/10003/bestility-with-dog-on-bed/
https://www.mynakedwife.video/embed/388/
```

```
https://www.bestialzoo.net/4513/shopping-friends/
https://www.mujeresdesnudas.club/embed/1744/
```

```
https://www.bestialporn.net/11365/ultimate-cockold/
https://www.mujeresdesnudas.club/embed/2178/
```

```
https://www.bestialitysexanimals.com/embed/641/
```

```
https://www.videoszoofiliahd.com/video/1282/zoofilia-sfm-video-compilation-3d
```

```
https://www.bestialitysextaboo.com/1206/hotkinky-jo-huge-horse-dildo/
```

### Describe the issue

Popups / Popads bypassing uBlock filters. 
Clicking anywhere on some pages triggers the popup but on majority of pages clicking where the video player is specifically is what triggers the popup.

### Screenshot(s)

N/A - Popups

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default.

### Notes
```
bestialitytaboo.tv/pop2.js
bestialitysextaboo.com/pop2.js
www.zoosexnet.com/pop2.js
etc
```

**Comment by zaphodbeebblebrox** [comment]
```
bestialitysexanimals.com,mynakedwife.video,bestialporn.com,mujeresdesnudas.club##script:inject(window.open-defuser.js)
/pop2.js?_=*$script
##[href^="https://www.skypeis"]
||www.videoszoofiliahd.com/wp-content/themes/vz/js/p.js$script,first-party
```

**Comment by okiehsch** [comment]
`##[href^="https://www.skypeis"]` missed that one added for the mentioned domains.

**Comment by C0nw0nk** [comment]
Found some missed ads. (Banners mostly stripchat etc)

URL's

```
http://porntopic.com/404.php
http://pornfay.com/404.php
http://pornspark.com/404.php
http://porntopic.com/404.php
```

On each site in the menu bar "Live cams"
```
http://pornfay.com/xxx/free-porn-videos.php?s=100&u=https://t.irtyf.com/k7959vydz4?offer_id=3664&aff_id=5979&bo=2779,2778,2777,2776,3391&nopop=1&aff_sub=pfay
http://porntopic.com/new/videos.php?s=100&u=https://t.irtyf.com/k7959vydz4?offer_id=3664&aff_id=5979&bo=2779,2778,2777,2776,3391&nopop=1&aff_sub=ptopic%20id=
http://pornscum.com/xxx/animalsex.php?s=100&u=https://t.irtyf.com/k7959vydz4?offer_id=3664&aff_id=5979&bo=2779,2778,2777,2776,3391&nopop=1&aff_sub=pscum
``

**Comment by C0nw0nk** [comment]
More.

Popups / Popads annoying clicking any video / url.

```
https://zootube1.com/video/mature-50-y-o.html

```

**Comment by C0nw0nk** [comment]
Ad URL's that redirect off site on pages.
```
http://pornscum.com/xxx/animalsex.php?s=100&u=https://t.irtyf.com/k7959vydz4?offer_id=3664&aff_id=5979&bo=2779,2778,2777,2776,3391&nopop=1&aff_sub=pscum
```

Example page in header menu and footer.
```
http://pornscum.com/video/16216/hot-babe-with-big-tits-finger-fucks-herself
```

**Comment by C0nw0nk** [comment]
Ad URL's that redirect off site on pages.
```
http://porntopic.com/new/videos.php?s=100&u=https://t.irtyf.com/k7959vydz4?offer_id=3664&aff_id=5979&bo=2779,2778,2777,2776,3391&nopop=1&aff_sub=ptopic%20id=
```

Example page in header menu and footer.
```
http://porntopic.com/videos/23663/hot-babe-with-big-tits-finger-fucks-herself/
```

**Comment by C0nw0nk** [comment]
Ad URL's that redirect off site on pages.
```
http://pornfay.com/xxx/free-porn-videos.php?s=100&u=https://t.irtyf.com/k7959vydz4?offer_id=3664&aff_id=5979&bo=2779,2778,2777,2776,3391&nopop=1&aff_sub=pfay
```

Example page in header menu and footer.
```
http://pornfay.com/video/47637/colombian-morena-gives-her-partner-a-awesome-cock-ridin
```

**Comment by C0nw0nk** [comment]
Another this one has popups / popads.

```
https://asiananimaltube.org/
```
![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40891167-f4dc4f06-6778-11e8-95da-87b71ac53793.jpg)

**Comment by C0nw0nk** [comment]
Another popups / Popads.
```
http://zoosex.pink/videos/sensual-dog-bestiality-xxx-ends-with-orgasm.html
```
![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40891217-8ff9dcba-6779-11e8-912b-6ae7ddf0c47d.jpg)

**Comment by C0nw0nk** [comment]
@okiehsch 

More what also do refer to your original comment this.

> `##[href^="https://www.skypeis"]` missed that one, added for the mentioned domains.

```
https://www.allbestiality.com/6170/watching-zooskool-videos/
https://www.beastzoo.org/10237/tranny-cock/
https://www.bestialitysexvideos.com/6174/playing-pussy/
https://www.zoofilianet.com/10452/fucking-awesome-ass/
https://www.bestialporn.net/11386/step-btothers/
https://www.zoosexsite.com/5207/lesbians-friends/
https://www.zoofiliak9.com/6136/domination/
https://www.zoofiliataboo.com/5138/sperm-history/
https://www.videosbizarre.com/video/6385/como-una-cabra/
https://www.bestialityworld.org/5835/sumise-pusnish/
```


The other thing that is consistant across all of these sites is these popads script.

```
<script> 
var azar = Math.floor(Math.random() * 1) + 1;
function publicidad1() {
$.getScript('//bestialityworld.org/pop2.js');
}

if(azar==1){
publicidad1();
}
</script>
```

On some domains it is pop.js (what gets caught by easyfilter)

On other domains it is pop1.js and pop2.js very annoying.

**Comment by C0nw0nk** [comment]
```
https://www.zoofiliak9.com/pop2.js
https://www.allbestiality.com/pop2.js
https://www.beastzoo.org/pop2.js
https://www.bestialitysexvideos.com/pop2.js
https://www.zoofilianet.com/pop2.js
https://www.bestialporn.net/pop2.js
https://www.zoosexsite.com/pop2.js
https://www.zoofiliataboo.com/pop2.js
https://www.videosbizarre.com/pop2.js
https://www.bestialityworld.org/pop2.js
http://www.bestialitytaboo.tv/pop2.js
https://www.zoosexnet.com/pop2.js
https://www.portalzoo.com/pop2.js
https://www.bestialporn.com/pop.js
https://www.bestialzoo.org/pop2.js
https://www.zookings.com/pop2.js
https://www.mujeresdesnudas.club/pop.js
https://www.zootubex.tv/pop2.js
https://www.hispajotes.com/pop2.js
https://www.fakingszoo.com/pop2.js
https://www.bestialporn.com/pop2.js
https://www.beastwomans.com/pop2.js
https://www.mynakedwife.video/pop2.js
https://www.zootubex.us/pop2.js
https://www.bestialzoo.net/pop2.js
https://www.mujeresdesnudas.club/pop2.js
https://www.bestialitysexanimals.com/pop2.js
https://www.bestialitysextaboo.com/pop2.js
```

Some are pop.js others are pop2.js

**Comment by C0nw0nk** [comment]
@mapx-  @okiehsch 

Are the above popup scripts eligible to be blocked on all these sites since they load on every page.

**Comment by mapx-** [comment]
Do you still get unblocked popups on those sites ?

**Comment by C0nw0nk** [comment]
@mapx-  On some it is the script being very dynamic and may take a few page refreshes.

```
<script> 
var azar = Math.floor(Math.random() * 2) + 1;
function publicidad1() {

  $.getScript('//adspaces.ero-advertising.com/adspace/3549715.js');
}

function publicidad2(){

  $.getScript('//bestialitytaboo.tv/pop2.js');
}

if(azar==1){
publicidad1();
}
if(azar==2){
publicidad2();
}


    </script>
```

As you see in their code snippet from one site it won't load in everypage may take a few refreshes to make the `azar` javascript variable have the correct numeric value to load the script in.

The contents of the scripts on every single one of their sites is obfuscated so it is unknown to me what advertiser it is trying to load i would assume popads.net or something of that sort.

**Comment by zaphodbeebblebrox** [comment]
Is there a reason why `/pop2.js$script` is not a filter?

**Comment by mapx-** [comment]
easylist has already these filters
```
/pop.js|
/pop2.js|
```

so, probably would be better have just
```
/pop.js
/pop2.js
```

**Comment by C0nw0nk** [comment]
@okiehsch @smed79 @okiehsch @ryanbr @mapx- 

![image](https://user-images.githubusercontent.com/12204587/43027341-aacd011c-8c71-11e8-9aa9-3134a52336bc.png)

More sites with dodgy scripts trying to launch redirects and popups that navigate you to external sites clicking on urls and also block you from closing the webpages and tabs.

URLs

```
https://zooredtube.com/
```

```
https://xxxtubezoo.com/
```

They should be on some kind of google malware or blacklist for running scripts like that, that try to stop you closing tabs navigating away and such things.

**Comment by C0nw0nk** [comment]
@okiehsch 

Another for the list.

Missed ads Popups :

Popup domain
```
 http://cl96rwprue.com/55adswekf?ayn
```

![a-popup](https://user-images.githubusercontent.com/12204587/43691269-e74a1394-9911-11e8-9205-7680308bd2d4.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/85d959a17d8cebc025110ed735b3342696d9871d

**Comment by C0nw0nk** [comment]
@okiehsch 

Site: Datoporn

```https://datoporn.co/zs1upsyuwlna```

Anti-Adblock video message.

**Comment by C0nw0nk** [comment]
@mapx- 
Another for the list
```
https://femefun.com/
```

Popup ads.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1ddcfa116dbfca64e15e96ec54862746e21b3ea6

**Comment by C0nw0nk** [comment]
A new one for you guys. @mapx-  @okiehsch  @ryanbr @smed79 

```
http://www.newsfilter.org/
```

Opens popups some sliding across banner chat advert aswell. Cams popups.
sneaky redirects on my current window opens a new tab with their website while the current window i have their site open in redirects to some cam website. 

Another that seems to do sneaky redirects in firefox redirects to blank page is motherless. (could be ad is blocked but it still executes its redirect code)
```
https://motherless.com/
```

**Comment by C0nw0nk** [comment]
Popups.

```
https://yespornclips.com/videos/teen-ravenous-babe-loved-to-pleasure-two-robbers-by-sucking-their-dicks/
```

**Comment by C0nw0nk** [comment]
Anti-Adblock and missed ads.

Disable AdBlock to avoid error "html5: Video file not found"

```
http://www.camwhores.tv/videos/3460638/charleigh3/
```

Bunch of banner ads and advert url's and links around the videos too.

**Comment by C0nw0nk** [comment]
Others from the same network with missed ads.

```
https://anon-v.com/videos/186722/playwithme-02da36cba12dc324/
https://www.porntrex.com/video/474376/brazzersexxtra-lela-star-creampie-diaries-part-2
http://www.camvideos.tv/73624/yamaguchi-show-20180808-5916/
https://xblaze.com/
```

Mostly banner ads "bongacams" etc Stripchat


Popups
```
https://www.watchmyexgf.net/
https://www.cartoonporno.xxx/
```

**Comment by C0nw0nk** [comment]
Missed popups.

```
http://femefun.com/
http://porntopic.com/videos/27533/wild-blonde-hottie-with-sexy-curves-fucks-herself/
```
Femefun seems to be clicking a video tries to open new tabs and windows / popups.

<img width="259" alt="untitled" src="https://user-images.githubusercontent.com/12204587/45395376-c7ff9700-b62d-11e8-8934-9d65484725e6.png">

Another :
Video player popup message. (and all urls scripts etc on this site from `://networkpb.com/` all from this domain is ads)
```
https://madnessporn.com/video/considerate-never-before-seen-married-hoe-taking-a-huge-anal-insertion-for-her-cam-friends-19878.html
```


This site same issue with networkpb.com scripts and urls. they are all ads.
```
https://aporntv.com/video/splendid-deepthroat-solo-play-as-this-barely-legal-slut-in-a-schoolgirl-skirt-chokes-on-her-dildo-19186.html
```

**Comment by C0nw0nk** [comment]
```
http://pornfay.com/video/52829/hot-blonde-chick-fucks-her-room-mate/
```

After webpage fully loaded and all scripts on page have executed clicking anywhere results in a popup.

**Comment by C0nw0nk** [comment]
Another same as above.
```
http://pornspark.com/videos/
```

**Comment by C0nw0nk** [comment]
@mapx- 

Stumbled across another with anti adblock.

`https://beasttracker.net/forum?topic=516`

I added this to my filter what blocked it and all external requests and future ones that site may add.

```
@@||beasttracker.net/js/ads.js$script,first-party
*$subdocument,third-party,domain=beasttracker.net
```

**Comment by C0nw0nk** [comment]
Missed ad code being loaded in on pages.

```
https://hdbraze.com/
https://vip.pornbraze.com/
https://fapdig.com/
```

Ad code
```
https://hdbraze.com/sw.js
https://vip.pornbraze.com/sw.js
https://fapdig.com/sw.js
```

Some kind of push notification ads.

**Comment by Daxy7** [comment]
content redirects on `zootube1.com` when clicking on a video at random  
adding `||zootube1.com/player/html.php$subdocument` fixed it

**Comment by mapx-** [comment]
There are lots of pages in this thread, which one ?

**Comment by Daxy7** [comment]
`https://zootube1.com/index.html`

Edit: is actually some Javascript cookie redirects when clicking on video, open any about 10-15 times

```
<!--
document.cookie='da325=Ym9va21hcmtzfHx8MTl8MjB8MjB8bm9uZXwwOnowMC53b3JsZA==; expires=Sat, 20 May 2023 10:14:34 GMT; path=/;';
document.cookie='da325b=1684491274; expires=Sat, 18 May 2024 10:14:34 GMT; path=/;';
//-->
```

base64 `Ym9va21hcmtzfHx8MTl8MjB8MjB8bm9uZXwwOnowMC53b3JsZA==` decoded is a url leading to `z00.world`
```
bookmarks|||19|20|20|none|0:z00.world
```

and they have this [related?] strange code
```

   function isIndex() {
   if (typeof(Storage) !== 'undefined') {
sessionStorage.clear();
}

   }
   
function __resolver_set(key, val) {
var d = new Date();
document.cookie = key + "=" + encodeURIComponent(val) + ";expires=" + d.setTime(d.getTime() + 86400 * 1000) + "; path=/";
}

```

**Comment by mapx-** [comment]
no popup on my side, what browser are you using ?

**Comment by Daxy7** [comment]
Firefox Version 113.0.1 (64-bit)
vid demo NSFW (middle mouse click was used)
`https://github.com/uBlockOrigin/uAssets/assets/91396482/4934d2e7-d18a-4d25-9892-ab3f4939ab5b`

**Comment by Daxy7** [comment]
try click on the 4 rows of videos (16). Connected using Tor with random locations and some went through as Finland, Germany etc

one time it opened a blocked link so this could be serving malware 
`https://github.com/uBlockOrigin/uAssets/assets/91396482/852850bc-0188-43e0-a040-4d2d574cdc67`

**Comment by mapx-** [comment]
test

```
zootube1.com##+js(cookie-remover, /^/)
zootube1.com##+js(aost, document.cookie, , 2)
```

**Comment by Daxy7** [comment]
Has fixed. Tried 125+ tabs and no redirects.

**Comment by Daxy7** [comment]
Hm. although login is broken (can't view profile, or click vid without being signed out)

`https://github.com/uBlockOrigin/uAssets/assets/91396482/350d6504-6071-4ab7-a6a0-2e49288d0f0a`

**Comment by mapx-** [comment]
Test

```
zootube1.com##+js(cookie-remover, da325)
zootube1.com##+js(aost, document.cookie, https, 2)
```

**Comment by mapx-** [comment]
meaning: working or not working ?

**Comment by Daxy7** [comment]
working
