### ISSUE TITLE
hypernitro.ru: Badware

### ISSUE THREAD

**Issue by dwnas** [uBlockOrigin/uAssets#23655]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [x] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://hypernitro.ru/pctivation
https://nitrohunt.com/login
```

### Description

generic discord login account stealer, not currently detected by ublock as a bad site
note that it seems to block successive requests, using incognito appears to bypass this

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 127
filterset (summary):
 network: 137244
 cosmetic: 47178
 scriptlet: 19398
 html: 1786
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38081-110, 20m Δ
  ublock-badware: 8654-0, 20m Δ
  ublock-privacy: 901-2, 20m Δ
  ublock-unbreak: 2331-2, 20m Δ
  ublock-quick-fixes: 195-9, 20m Δ
  easylist: 87713-159, 20m Δ
  easyprivacy: 50877-64, 20m Δ
  urlhaus-1: 14780-0, now
  plowe-0: 3729-1160, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1273 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0

```
</details>

**Comment by stephenhawk8054** [comment]
Can you give full original links of it? They both show 404 error for me

**Comment by dwnas** [comment]
these links are correct, they have to have some sort of referrer i believe, as the links are normally spread through the use of a url shortener i.e _[https://goo.su/link-nitro (original link)](https://goo.su/link-nitro)_
1.
![image](https://github.com/uBlockOrigin/uAssets/assets/141259991/27b68527-f6c7-4b59-bd95-6d6e6fc677db)
2.
![image](https://github.com/uBlockOrigin/uAssets/assets/141259991/8576ed25-1cc6-4d90-adb8-16ecde32e7a5)

**Comment by stephenhawk8054** [comment]
I added the domains.

I didn't say it's not correct link or whether blocking whole domains or not. The problem is we NEED some evidences to back up the decisions. No screenshots, no original links, no steps to reproduce... How would we respond if the website owners come to complain?
