### ISSUE TITLE
baharudinyusuf.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#23652]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://baharudinyusuf.com/urip-iku-sawang-sinawang-6525bb196c78`

### Category

nuisance

### Description

overlay

### Other extensions used

n

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/c9688742-8c76-4040-8e5f-09ba56c88bcb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 145970
 cosmetic: 162153
 scriptlet: 33707
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8166-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 205-0, now
  adguard-other-annoyances: 14226-385, now
  adguard-popup-overlays: 27334-903, now
  easylist-annoyances: 4593-17, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7376-11, now
  easylist-notifications: 2980-85, now
  fanboy-cookiemonster: 50989-256, now
  fanboy-social: 15952-10, now
  ublock-annoyances: 7020-52, now
  ublock-cookies-easylist: 1145-1145, now
 default:
  user-filters: 50-0, never
  easylist: 87713-631, now
  easyprivacy: 50877-86, now
  plowe-0: 3729-788, now
  ublock-badware: 8652-1, now
  ublock-filters: 37959-696, now
  ublock-privacy: 900-4, now
  ublock-quick-fixes: 259-3, now
  ublock-unbreak: 2274-21, now
  urlhaus-1: 14480-0, never
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1289 ms (selfie)
 maxAssetCacheWait: 709 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  baharudinyusuf.com: 3
  branch.io: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 extended:
  ##div.l > .acu.act
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
@gorhill For some reasons, when I use

```adb
baharudinyusuf.com##+js(trusted-set-local-storage-item, 'lo-non-moc-membership-upsell|dismissed-at', $now$)
```

the local storage item does not convert to date with dev build (1.57.3b9). Stable works fine.
