### ISSUE TITLE
bravotv.com: breakage

### ISSUE THREAD

**Issue by teggy0** [uBlockOrigin/uAssets#23656]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bravotv.com/`

### Category

breakage

### Description

The website is fully black when uBlock is activated. When I go to a page that includes a video, the video player doesn't load.

### Other extensions used

I have privacy badger but I shut it off to test which extension may be causing the issue. The site doesn't work if either are enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 137247
 cosmetic: 47189
 scriptlet: 19398
 html: 1786
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 77-0, 1m
 default:
  user-filters: 15-0, never
  ublock-filters: 38081-110, 2m Δ
  ublock-badware: 8654-0, 2m Δ
  ublock-privacy: 901-79, 2m Δ
  ublock-unbreak: 2331-2, 2m Δ
  easylist: 87713-158, 2m Δ
  easyprivacy: 50877-64, 2m Δ
  urlhaus-1: 14780-0, 1m
  plowe-0: 3729-1160, 1m
  ublock-quick-fixes: 195-10, 2m Δ
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 26 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1138 ms (selfie)
 maxAssetCacheWait: 34 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.advertisement
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||jssdkcdns.mparticle.com/js/v2/*/mparticle.js$script,domain=bravotv.com
```

@ryanbr
