### ISSUE TITLE
kufar.by: ads

### ISSUE THREAD

**Issue by den1251** [uBlockOrigin/uAssets#23657]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kufar.by/l`

### Category

ads

### Description

Yandex ads on the website.

### Other extensions used

popup blocker and privacy badger, but as I checked I have this ads even after disabling them

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2024-05-11 13-45-04](https://github.com/uBlockOrigin/uAssets/assets/169529777/8dcc183b-f6c8-4629-9ce5-80f844da1f9a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 137244
 cosmetic: 47180
 scriptlet: 19397
 html: 1786
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 38081-110, 15m Δ
  ublock-badware: 8654-0, 15m Δ
  ublock-privacy: 901-2, 15m Δ
  ublock-unbreak: 2331-2, 15m Δ
  ublock-quick-fixes: 195-9, 15m Δ
  easylist: 87709-159, 15m Δ
  easyprivacy: 50877-64, 15m Δ
  urlhaus-1: 14780-0, now
  plowe-0: 3729-1160, now
filterset (user): [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 328 ms (selfie)
 maxAssetCacheWait: 63 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  adfox.ru: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  mindbox.ru: 1
  yandex.ru: 22
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `RU AdList` list and test again

**Comment by den1251** [comment]
Oh, sorry. Enabling `RU AdList` helped
