### ISSUE TITLE
foodandwine.com: ads

### ISSUE THREAD

**Issue by asminja** [uBlockOrigin/uAssets#23659]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.foodandwine.com/recipes/bottled-manhattan`

### Category

ads

### Description

Kroger advertisement with my location data.
![Screenshot 2024-05-11 at 09-06-44 Bottled Manhattan Recipe](https://github.com/uBlockOrigin/uAssets/assets/25459020/4dd50ad4-f0f9-41b7-80fd-f50c230af17d)

### Other extensions used

PrivacyBadger, Sponsorblock, DarkReader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 145975
 cosmetic: 204469
 scriptlet: 32718
 html: 2047
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-cookies: 29557-38, now
  ublock-cookies-adguard: 1145-13, now
  fanboy-cookiemonster: 50989-3879, now
  ublock-cookies-easylist: 1145-1145, now
  adguard-social: 22921-49, now
  fanboy-social: 15953-725, now
  fanboy-thirdparty_social: 68-18, now
  adguard-popup-overlays: 27334-1026, now
  adguard-mobile-app-banners: 5191-23, now
  adguard-other-annoyances: 14229-422, now
  adguard-widgets: 2495-11, now
  easylist-annoyances: 4595-296, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 45-0, never
  ublock-filters: 38081-110, now
  ublock-badware: 8654-0, now
  ublock-privacy: 901-2, now
  ublock-unbreak: 2331-2, now
  ublock-quick-fixes: 195-9, now
  easylist: 87716-159, now
  easyprivacy: 50882-65, now
  urlhaus-1: 14780-0, 1h
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 584 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  foodandwine.com: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  googletagmanager.com: 2
  indexww.com: 1
  jwpcdn.com: 1
  jwpltx.com: 2
  p-n.io: 1
 extended:
  ##.icon-flipboard
  ##.mm-ads-leaderboard-header
  ##.mm-ads-gpt-adunit
  ##.social-share
  ##.share-link-facebook
  ##.share-link-twitter
  ##.mntl-sc-block-adslot
  ##.rightrail-ad-placed
  ##.js-lazy-ad
  ##.leaderboard
  ##.mntl-recipe-social-share__share-wrapper
  ##body,html:style(overflow: auto !important; position: initial !…
  ##html:style(overflow: auto !important;)
  ##html,body:style(overflow: auto !important; position: initial !…
```
</details>

**Comment by JobcenterTycoon** [comment]
I also see `https://calvera-telemetry.polaris.me/events` but the ad only gives me a error.
