### ISSUE TITLE
downloadtorrentfile.com: ads

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#23653]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://downloadtorrentfile.com/hash/a234cbd9d2b859383f29af5c3840df61f67053a9?name=gimp-2.10.38-setup.exe`

### Category

ads

### Description

Leftover ad box at the top of the page

### Other extensions used

- Augmented Steam
- ClearURLs
- F.B Purity - Cleans up Facebook
- Grammar and Spell Checker - LanguageTool
- Tab Auto Refresh
- ySense Addon

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/22180480/2dea478f-0ea2-4faf-ba65-db46b265997b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 139035
 cosmetic: 57144
 scriptlet: 24237
 html: 2057
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6965-36, 32m Δ
 default:
  user-filters: 62-0, never
  ublock-filters: 38081-110, 32m Δ
  ublock-badware: 8654-0, 32m Δ
  ublock-privacy: 901-2, 32m Δ
  ublock-unbreak: 2331-2, 32m Δ
  ublock-quick-fixes: 195-9, 32m Δ
  easylist: 87713-159, 32m Δ
  easyprivacy: 50877-64, 32m Δ
  urlhaus-1: 14780-0, now
  plowe-0: 3729-1160, now
  POL-0: 8694-45, now
  POL-2: 1283-50, now
filterset (user): [array of 63 redacted]
trustedset:
 added: [array of 38 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 92 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  esteemcountryside.com: 1
  googletagmanager.com: 1
  swiggermahwa.com: 1
```
</details>

**Comment by mapx-** [comment]
`downloadtorrentfile.com##.ads`
