### ISSUE TITLE
1dizipal.com: ads

### ISSUE THREAD

**Issue by nri82** [uBlockOrigin/uAssets#23668]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1dizipal.com/gibi-5-sezon-9-bolum-izle`

### Category

ads

### Description

there is banner

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/18355195/afc6a0a2-335f-4c3b-8a79-8e67b7033a0f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 138583
 cosmetic: 56515
 scriptlet: 20898
 html: 1786
listset (total-discarded, last-updated):
 added:
  TUR-0: 12318-51, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38083-110, now
  ublock-badware: 8666-0, now
  ublock-privacy: 901-2, now
  ublock-unbreak: 2331-2, now
  ublock-quick-fixes: 195-9, now
  easylist: 87738-159, now
  easyprivacy: 50884-65, now
  urlhaus-1: 14645-0, 1h.58m
  plowe-0: 3729-1160, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 620 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  googletagmanager.com: 2
  jsdelivr.net: 2
 extended:
  ##body > div#footerFixedDiv
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by mapx-** [comment]
add

`1dizipal.com##.containerAds`

@Yuki2718
