### ISSUE TITLE
earn.bharatsarkarijobalert.com: detection

### ISSUE THREAD

**Issue by preetam1409** [uBlockOrigin/uAssets#23661]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://earn.bharatsarkarijobalert.com/`

### Category

detection

### Description

original link - https://instantearn.in/TmvBLSW

issue detected in - https://earn.bharatsarkarijobalert.com/

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/43402156/3555bd7b-e62d-4147-a936-9963a1f18822)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 137143
 cosmetic: 47283
 scriptlet: 20806
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 87716-58, 5m Δ
  easyprivacy: 50882-2, 5m Δ
  plowe-0: 3729-1160, now
  ublock-badware: 8652-15, 5m Δ
  ublock-filters: 37961-366, 5m Δ
  ublock-privacy: 900-5, 5m Δ
  ublock-quick-fixes: 259-1, 5m Δ
  ublock-unbreak: 2274-30, 5m Δ
  urlhaus-1: 14645-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1613 ms
 maxAssetCacheWait: 463 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  googlesyndication.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  ##.np-header-ads-area
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by BlazeFTL** [comment]
Add In My Filters 
```
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com##+js(acs, eval, replace)
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com###tp-snp2, #cross-snp2:style(display: block !important;)
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com###tp-snp2, #cross-snp2, .tp-top:others()
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com##+js(trusted-click-element, #tp-snp2, , 1000)
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com##+js(trusted-click-element, #cross-snp2, , 1000)
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com##.floating-ads-container
bankshiksha.in,earn.mpscstudyhub.com,earn.quotesopia.com,money.quotesopia.com,best-mobilegames.com,learn.moderngyan.com,bharatsarkarijobalert.com##+js(set, count, 0)
set.seturl.in##.blog-item
set.seturl.in##.banner-inner
get.instantearn.in##.banner-inner

**Comment by preetam1409** [comment]
thank you 🙏
