### ISSUE TITLE
[nsfw] ebay.com: ads

### ISSUE THREAD

**Issue by iconoscope** [uBlockOrigin/uAssets#23673]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ebay.com/itm/196384384839?epid=22027070979&itmmeta=01HXQ422AVSMGDVYSXHM7Q8CF4&hash=item2db96be747%3Ag%3Az9wAAOSw4AdmOsQD&itmprp=enc%3AAQAJAAAAwOL8hST1DWBu%2B5MNDlZH16t7rIfVAZZVKEhe4c0u%2FdqSr7dgaoEiMoDiPxffm23OnsoRbeGNY75ny406yX1OjGgzfOfcspL9C3qJSrN1MVNfhj3EWYceeQhtWSnYuuF2AGb1my7wISnYUrXxftjwzhi1mcWe2e1U475QcNC3DYaPAqqCV4EOiuJdvcKU1ilgV%2B1I435CzWaWXxa27IXUdVoj6r8v%2Fav0t2ICgpb%2B1CGQcra2vt2p0S4dgGn%2BUSkXvA%3D%3D%7Ctkp%3ABk9SR9SliOTtYw&LH_ItemCondition=3000`

### Category

ads

### Description

This is a new type of pop up . First it depends on having a ebay account logged in . then this is the first item you are look with the open browser which is Firefox on pc
If I Create a filter on any of it's content , which are attached , the popup will disappear , so will any right hand scroll bar for the page

The pop require a cursor touch any only the page to restore a closed popup and working page with scroll bar

every time there is a special on using the app

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture2](https://github.com/uBlockOrigin/uAssets/assets/166566844/2483a09c-bc13-412d-ab5b-4df84d36b4ed)

![Capture4](https://github.com/uBlockOrigin/uAssets/assets/166566844/aa8416f6-359a-44c0-b956-2b3e77536c74)

![Capture5](https://github.com/uBlockOrigin/uAssets/assets/166566844/8760cb6f-141a-4e6e-90da-0ff8a8dcc369)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 135381
 cosmetic: 47261
 scriptlet: 19401
 html: 1785
listset (total-discarded, last-updated):
 default:
  user-filters: 25-1, never
  ublock-filters: 38120-232, now
  ublock-badware: 8362-0, now
  ublock-privacy: 901-0, now
  ublock-unbreak: 2331-0, now
  ublock-quick-fixes: 194-0, now
  easylist: 87747-74, now
  easyprivacy: 50894-37, now
  urlhaus-1: 13180-1, now
  plowe-0: 3729-1160, now
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 28 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 628 ms (selfie)
 maxAssetCacheWait: 333 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  ebay.com: 4
  ebay-us.com: 1
  ebayrtm.com: 1
  ebaystatic.com: 5
```
</details>

**Comment by D4niloMR** [comment]
According to the screenshot, this is self-promotion, which we don't fix.
