### ISSUE TITLE
examated.co.in: ads

### ISSUE THREAD

**Issue by guimball** [uBlockOrigin/uAssets#23674]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://examated.co.in/click.php?key=txykb1tfm5k452dvsraq&visitor_id=813620033287889116&zoneid=7413447&campaignid=8116206&device=desktop&browser=edge&os=windows&osversion=win10&country=BR&language=en&isp=top%20connect%20tecnologia%20ltda&user_activity=high&countryname=BR`

### Category

ads

### Description

fake amazon card

### Other extensions used

pip and dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/124224711/80556132-4604-4e13-943c-affbad2b1e31)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136697
 cosmetic: 51121
 scriptlet: 21237
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87752-505, 28m Δ
  easyprivacy: 50894-823, 28m Δ
  plowe-0: 3729-0, now
  spa-1: 5623-15, now
  ublock-badware: 8360-0, 28m Δ
  ublock-filters: 37959-375, 28m Δ
  ublock-privacy: 900-0, 28m Δ
  ublock-quick-fixes: 258-0, 28m Δ
  ublock-unbreak: 2274-3, 28m Δ
  urlhaus-1: 13180-1, 28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 880 ms
 maxAssetCacheWait: 218 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  scriptcdn.net: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
From where do you got the domain? Maybe we can block the source (like popup ads from a random streaming site).
