### ISSUE TITLE
littlebigsnake.com: detection

### ISSUE THREAD

**Issue by GTPatriots** [uBlockOrigin/uAssets#23677]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://littlebigsnake.com/`

### Category

detection

### Description

Detects Ublock and then won't let you skip video ads

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 220521
 cosmetic: 252613
 scriptlet: 49978
 html: 2047
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78821-134, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98790-23064, now
  adguard-generic: 81888-4004, now
  adguard-mobile: 9375-70, now
  adguard-spyware-url: 1510-120, now
  block-lan: 66-0, now
  adguard-social: 22922-1639, now
  fanboy-thirdparty_social: 68-18, now
  fanboy-cookiemonster: 50989-50989, now
  fanboy-social: 15955-15955, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 14-1, never
  ublock-filters: 38098-446, 34m Δ
  ublock-badware: 8362-0, 34m Δ
  ublock-privacy: 901-4, 34m Δ
  ublock-unbreak: 2331-6, 34m Δ
  easylist: 87747-2015, 34m Δ
  easyprivacy: 50894-328, 34m Δ
  urlhaus-1: 13225-1, now
  plowe-0: 3729-1243, now
  ublock-quick-fixes: 194-9, 34m Δ
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 316 ms (selfie)
 maxAssetCacheWait: 144 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 60
 network:
  littlebigsnake.com: 48
  googletagmanager.com: 1
  scorecardresearch.com: 1
  unity3d.com: 9
  zdassets.com: 1
 extended:
  ###advertisement_banner
  ###adsContainer
  ###social_bar
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings (also turn off Firefox Tracking Protection)
