### ISSUE TITLE
Instagram.com: Stories ads

### ISSUE THREAD

**Issue by darkseid-is** [uBlockOrigin/uAssets#23679]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.instagram.com/
```

### Description

Sponsored stories get shown when stories are viewed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/55893621/169a8f48-60a9-48f8-86ed-0588c8aa343a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 313063
 cosmetic: 375830
 scriptlet: 56139
 html: 2145
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81421-3984, 53m
  adguard-mobile: 9375-56, 53m
  adguard-spyware-url: 1510-120, 53m
  adguard-spyware: 86425-1370, 53m
  block-lan: 66-0, 10d.2h.24m
  curben-phishing: 117-1, 23h.30m
  adguard-cookies: 29565-45, 53m
  ublock-cookies-adguard: 1143-13, 3d.2h.12m
  fanboy-cookiemonster: 50993-3883, 3d.2h.12m
  ublock-cookies-easylist: 1143-1143, 3d.2h.12m
  adguard-social: 22922-55, 53m
  fanboy-social: 15934-727, 3d.2h.12m
  [47 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38100-110, 3h.32m Δ
  ublock-badware: 8363-0, 3h.32m Δ
  ublock-privacy: 901-2, 3h.32m Δ
  ublock-unbreak: 2331-2, 3h.32m Δ
  ublock-quick-fixes: 194-5, 3h.32m Δ
  easylist: 87747-1935, 3h.32m Δ
  easyprivacy: 50894-31559, 3h.32m Δ
  urlhaus-1: 13220-0, 23h.30m
  plowe-0: 3735-1647, 10d.18h.9m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 600 ms (selfie)
 maxAssetCacheWait: 322 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  instagram.com: 16
 extended:
  ##._aagw:empty
  ##main > div div[style*="flex-direction: column;"] > article > d…
  ##article:has(a[href^="https://www.facebook.com/ads/"]):style(he…
  ##body:style(overflow: visible!important;)
  ##div[class]:has(> div[class]:first-child > a[href="/explore/peo…
  ##[class]:style(-webkit-touch-callout: default !important; -webk…
  ##+js(trusted-set-cookie, ig_did, 0C826C21-17C3-444A-ABB7-EBABD3…
  ##+js(set-constant, _sharedData.is_whitelisted_crawl_bot, true)
  ##+js(set-session-storage-item, loggedOutAppSheetIsMinimized, 1)
  ##+js(close-window, /[Ss][Mm][Oo][Ss][Tt][Aa][Ff][Aa][Mm][Oo][Oo…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(remove-class, _31e, body > ._li)
  ##+js(trusted-set-cookie, datr, __GMZCgwVF5BbyvAtfJojQwg, 1year,…
  ##+js(addEventListener-defuser, scroll, showPopup)

```
</details>

**Comment by krystian3w** [comment]
I see ads in X/Twitter rells/shorts.
