### ISSUE TITLE
sinnerclownceviri.net: detection

### ISSUE THREAD

**Issue by DogancanYr** [uBlockOrigin/uAssets#23683]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://sinnerclownceviri.net
```

### Description

Detects adblock after logging into the site.

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/90002969/58b3bdc5-3030-4ecb-b8f2-69eb944cc7e6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 313252
 cosmetic: 375520
 scriptlet: 56096
 html: 2145
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81934-3954, 3d.23h.13m
  adguard-mobile: 9367-56, 3d.23h.13m
  adguard-spyware-url: 1509-120, 3d.23h.13m
  adguard-spyware: 86424-1370, 3d.23h.14m
  block-lan: 66-0, 16d.18h.46m
  curben-phishing: 343-2, 12m
  adguard-social: 22917-53, 3d.23h.13m
  adguard-cookies: 29548-46, 3d.23h.13m
  ublock-cookies-adguard: 1144-13, 2d.16h.33m
  adguard-popup-overlays: 27334-1003, 3d.23h.14m
  adguard-mobile-app-banners: 5191-23, 3d.23h.14m
  adguard-other-annoyances: 14227-413, 3d.23h.14m
  [46 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38075-110, 18h.38m Δ
  ublock-badware: 8362-0, 18h.38m Δ
  ublock-privacy: 901-2, 18h.38m Δ
  ublock-unbreak: 2331-2, 18h.38m Δ
  ublock-quick-fixes: 194-5, 12m
  easylist: 87752-1936, 18h.38m Δ
  easyprivacy: 50894-31558, 18h.38m Δ
  urlhaus-1: 13225-1, 12m
  plowe-0: 3729-1645, 9d.19h.41m
  TUR-0: 11453-99, 4d.20h.32m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 365 ms (selfie)
 maxAssetCacheWait: 246 ms
 cacheBackend: indexedDB
```
</details>

**Comment by DogancanYr** [comment]
Creating an account is actually free.

**Comment by JobcenterTycoon** [comment]
I fixed it already https://github.com/uBlockOrigin/uAssets/commit/fac4433afc90d62f5fd8b4b3f05103133efdadf9 or does the fix doesn’t work for you? The update will be avaiable in a few hours as a auto update.

**Comment by DogancanYr** [comment]
I thought you didn't do anything just because you added the account required tag.
Ok now it works.
