### ISSUE TITLE
[nsfw] dinheiromoney.com: detection

### ISSUE THREAD

**Issue by manbyothername** [uBlockOrigin/uAssets#23680]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dinheiromoney.com/dicas-uteis-de-planejamento-financeiro-pessoal/`

### Category

detection

### Description

Overlay/blur is shown

### Other extensions used

Enpass, IDM Integration module

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-13 042341](https://github.com/uBlockOrigin/uAssets/assets/74740171/a5496cbe-5548-436e-b5eb-7f8500d0cc66)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 135569
 cosmetic: 47282
 scriptlet: 20795
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37953-277, now
  ublock-badware: 8488-0, now
  ublock-privacy: 900-0, now
  ublock-unbreak: 2274-0, now
  ublock-quick-fixes: 258-0, now
  easylist: 87709-546, now
  easyprivacy: 50894-810, now
  urlhaus-1: 13225-1, now
  plowe-0: 3729-0, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1480 ms
 maxAssetCacheWait: 19 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  dinheiromoney.com: 3
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 2
  google.com: 1
  googlesyndication.com: 4
  googletagmanager.com: 1
  headerbidding.ai: 2
  sendwebpush.com: 1
  vidoomy.com: 1
  youtube.com: 2
 extended:
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  ###anuncio
  ##ins.adsbygoogle[data-ad-slot]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune-fetch-response, overlay, overlay.shortsAdsRende…
```
</details>

**Comment by manbyothername** [comment]
> Is it from a shortener link?

Yes they are becoming too smart for their own good. 

I got a workaround with system wide Adguard though, shortly after searching for other adblock filter list options. Curiously its the filter https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt (which is the master file for UBlock Origin blocking) combined with Adguard Base filter and AdGuard Mobile Ads filter the setup that bypassed the detection, nothing more was selected not even DNS blocking or userscripts. 

Something in the default filters of the Ublock origin is making Ublock origin be detected or not blocking the anti adblock script or both.

![Screenshot 2024-05-13 050030](https://github.com/uBlockOrigin/uAssets/assets/74740171/1e661c13-9ad0-4d1e-8a6a-a5a5d64fc996)

**Comment by stephenhawk8054** [comment]
Post the original link to here: https://github.com/uBlockOrigin/uAssets/discussions/17361
