### ISSUE TITLE
kurzy.cz: ads

### ISSUE THREAD

**Issue by wowfilip999** [uBlockOrigin/uAssets#23688]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.kurzy.cz
```

### Description

by blocking this can it be solved from here is images https://img.kurzy.cz/block/

### Other extensions used

![obrazek](https://github.com/uBlockOrigin/uAssets/assets/67916726/47b2752c-2dda-4c06-9474-88ee5b8c018e)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
I accessed `https://www.kurzy.cz/` but the webpage does not look like your screenshot:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/8527f0e4-65ad-45a0-aa0f-b458eba8db1f)

Where should I click next? Which steps should I follow next?

**Comment by wowfilip999** [comment]
> I accessed `https://www.kurzy.cz/` but the webpage does not look like your screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/66517106/330251536-85b5b61e-90df-4797-b4bb-695d40d25e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTMxOTUsIm5iZiI6MTcxNTcxMjg5NSwicGF0aCI6Ii82NjUxNzEwNi8zMzAyNTE1MzYtODViNWI2MWUtOTBkZi00Nzk3LWI0YmItNjk1ZDQwZDI1ZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE4NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDJkMGE2OGRhZGM3MWNmM2Y3ZGYzOGYwYTE0ZmVkYmY2NjlmYmM3ZjVmNGYwNTZkNjRkY2JhZGIxZGEwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eka0xEcmPM9qylrAAu91m43bd-i-y9l8XkeOEsnv15I)
> 
> Where should I click next? Which steps should I follow next?
when you search something on the web ad will show
https://www.kurzy.cz/hledani/?q=p%C5%99evod+eura
![obrazek](https://github.com/uBlockOrigin/uAssets/assets/67916726/279f5047-3358-42c1-b88e-84dc18d5eaea)

![obrazek](https://github.com/uBlockOrigin/uAssets/assets/67916726/9c688b69-adf7-422d-8031-f5f78d655cec)
i blocked it by add to filter ||img.kurzy.cz
![obrazek](https://github.com/uBlockOrigin/uAssets/assets/67916726/45f83c69-29db-45ca-8ca9-3bcd43f49aea)

**Comment by stephenhawk8054** [comment]
Please always give full link to reproduce the issue next time.

---

@tomasko126 Sorry, can you take a look?

```adb
||img.kurzy.cz/block/$subdocument,~third-party
```
