### ISSUE TITLE
newgrounds.com: nuisance

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#23686]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.newgrounds.com/
```

### Description

After visiting the site frequently and browsing different songs, you eventually get a popup covering a lot of the screen asking you to signup. It happens quite frequently, to the point where it becomes annoying and in-your-face.

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/d6c5567c-5785-4ac4-a726-b847aa1bd49c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 231435
 cosmetic: 252115
 scriptlet: 50953
 html: 2047
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81406-3985, 2d.20h.14m
  adguard-mobile: 9375-56, 2d.20h.14m
  adguard-spyware-url: 1509-120, 2d.20h.14m
  adguard-spyware: 86424-1370, 2d.20h.14m
  block-lan: 66-0, 2d.20h.14m
  curben-phishing: 343-2, 4h.48m
  adguard-social: 22921-53, 2d.20h.14m
  adguard-cookies: 29557-46, 2d.20h.14m
  ublock-cookies-adguard: 1145-13, 2d.20h.14m
  adguard-popup-overlays: 27334-1003, 2d.20h.14m
  adguard-mobile-app-banners: 5191-23, 2d.20h.14m
  adguard-other-annoyances: 14229-413, 2d.20h.14m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38104-110, 3h.48m Δ
  ublock-badware: 8490-0, 3h.48m Δ
  ublock-privacy: 901-2, 3h.48m Δ
  ublock-unbreak: 2331-2, 3h.48m Δ
  ublock-quick-fixes: 194-5, 3h.48m Δ
  easylist: 87620-1935, 3h.48m Δ
  easyprivacy: 50894-31558, 3h.48m Δ
  urlhaus-1: 13225-1, 4h.48m
  plowe-0: 3729-1646, 2d.20h.14m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 288 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  stripe.com: 9
 extended:
  ##+js(set-constant, cpmstar_siteskin_settings, {})
  ##+js(set-constant, rwt, noopFunc)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…

```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
newgrounds.com##+js(cookie-remover, _ngViCo-SupporterPromo)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by the9655a** [comment]
Thanks. I'll let you know if I receive the popup or not

**Comment by the9655a** [comment]
Sorry, the popup doesn't always appear, so I wanted to give it some time. But I've not gotten it yet, so might as well add it to ubo filters list for others to use
