### ISSUE TITLE
1jour1film.homes: popups

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#23689]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1jour1film.homes/episodes/from-s1-e1-streaming-vf/`

### Category

pop-ups and lots of annoying things

### Description

This is an excellent site, but unfortunately it's full of adverts and pop-ups. As soon as you select a server to watch a video, when you click on play etc., it's impossible to see the adverts.

### Other extensions used

None that interfere with uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 173042
 cosmetic: 134767
 scriptlet: 27105
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1078-0, 12m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 12m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 50990-9464, 12m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-6, 12m
  RUS-0: 39454-237, 12m
 default:
  user-filters: 1-0, never
  ublock-filters: 38031-348, 1h.14m Δ
  ublock-badware: 8497-0, 1h.14m Δ
  ublock-privacy: 905-0, 1h.14m Δ
  ublock-unbreak: 2274-0, 1h.14m Δ
  ublock-quick-fixes: 255-0, 1h.14m Δ
  easylist: 87609-689, 1h.14m Δ
  easyprivacy: 50897-812, 1h.14m Δ
  urlhaus-1: 13005-1, 11m
  plowe-0: 3729-0, 11m
  FRA-0: 24422-310, 11m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 239 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  a-ads.com: 1
  alaeshire.com: 1
  alnuinvisayan.com: 1
  googletagmanager.com: 1
  histats.com: 1
  nv3tosjqd.com: 2
  push-sdk.com: 1
 extended:
  ##.module_single_ads
```
</details>

**Comment by BlazeFTL** [comment]
Test
```
1jour1film.homes###clickfakeplayer:remove-attr(href)
player.melaniezettofrais.online##a[href][target="_blank"]
player.melaniezettofrais.online,1jour1film.homes##+js(nowoif)

**Comment by stephenhawk8054** [comment]
@Yuki2718 For Adguard French?

Above filters work fine, or some of these

```adb
1jour1film.homes###clickfakeplayer:remove-attr(href)
player.melaniezettofrais.online##+js(aeld, click, Popup)
player.melaniezettofrais.online##body > div[id]:not(#video_player)
```

---

For disabling devtools detection

```adb
/cdn.jsdelivr.net/npm/disable-devtool
/devtools-detector
player.melaniezettofrais.online##+js(nosiif, devtools)
```
