### ISSUE TITLE
virginradio.co.uk: ads

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#23684]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://virginradio.co.uk/entertainment/145392/joe-lycett-receives-bafta-dressed-as-elizabeth-i`

### Category

ads

### Description

Website still shows leftover ad boxes.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screenshot 2024-05-13 at 14 20 07" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/95a841a3-1737-426c-af3c-68549b3dd05a">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 117
filterset (summary):
 network: 137463
 cosmetic: 73493
 scriptlet: 22025
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29574-32, now
 default:
  user-filters: 80-0, never
  easylist: 87620-46, 36m Δ
  easyprivacy: 50894-19, 36m Δ
  plowe-0: 3729-1161, now
  ublock-badware: 8488-15, 36m Δ
  ublock-filters: 37982-356, 36m Δ
  ublock-privacy: 900-5, 36m Δ
  ublock-quick-fixes: 258-6, 36m Δ
  ublock-unbreak: 2274-32, 36m Δ
  urlhaus-1: 13005-1, 36m
filterset (user): [array of 82 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 106 ms (selfie)
 maxAssetCacheWait: 64 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 12
 network:
  virginradio.co.uk: 3
  dotmetrics.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  newrelic.com: 2
  newscgp.com: 1
  privacy-mgmt.com: 1
  scorecardresearch.com: 2
 extended:
  ##.ad-outline
  ##.nuk-ad-placeholder
  ##body:style(overflow: visible!important;)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
virginradio.co.uk##div[class^="css-"]:has(> .ad-outline)
```

@ryanbr
