### ISSUE TITLE
bilibili.com: ads

### ISSUE THREAD

**Issue by utopeadia** [uBlockOrigin/uAssets#23699]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
bilibili.com
```

### Description

add bilibili.com##.adblock-tips to remove 
![image](https://github.com/uBlockOrigin/uAssets/assets/98788152/0323a7eb-a8cd-4d91-bb5f-c52115a3e9b5)

### Other extensions used

no

### Configuration

just add rule

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you take a look?

**Comment by cjx82630** [comment]
It's an anti adblock notice, won't be blocked by EL china.

**Comment by utopeadia** [comment]
> It's an anti adblock notice, won't be blocked by EL china.

I am curious if this rule can be added to the official subscription. If not, I can close this issue and maintain my subscription list

**Comment by stephenhawk8054** [comment]
The most we can do is addressing it `uBlock filters – Annoyances` list

**Comment by utopeadia** [comment]
> The most we can do is addressing it `uBlock filters – Annoyances` list

Adding "Annoyances list - uBlock filters" is a very helpful solution, because this tip is common and removing it can enhance the user experience. In my opinion, since you have already chosen to block ads, I will not retain this reminder for the sake of false moral or other purposes. (bilibili is not a free or open-source platform. Even though I have paid the membership fee, I am still forced to watch a large number of ads.)
