### ISSUE TITLE
yggtorrent.cool: ads

### ISSUE THREAD

**Issue by malfoyez** [uBlockOrigin/uAssets#23697]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yggtorrent.cool/`

### Category

ads

### Description

a link on the toolbar to **see the tv**

### Other extensions used

fresh firefox install

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran 2024-05-14 à 10 02 26-fullpage](https://github.com/uBlockOrigin/uAssets/assets/169759235/88f7b7d0-1d77-4d38-a824-30c41a44364a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 152172
 cosmetic: 53822
 scriptlet: 19565
 html: 1801
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38159-110, now
  ublock-badware: 8362-0, now
  ublock-privacy: 901-2, now
  ublock-unbreak: 2331-2, now
  ublock-quick-fixes: 193-5, now
  easylist: 87740-158, now
  easyprivacy: 50894-65, now
  urlhaus-1: 12865-1, now
  plowe-0: 3729-1160, now
  FRA-0: 24422-503, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 989 ms
 maxAssetCacheWait: 578 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(abort-on-property-write, Fingerprint2)
```
</details>

**Comment by mapx-** [comment]
![image](https://github.com/user-attachments/assets/1127389f-7a92-4746-9e1b-56ca7fe44551)

1. if you want to be helped you have to share your account credentials with us (if you agree => I'll provide an email address where you can send user/pass)
2. provide a better explanation of your issue

closing for now => if you agree point 1 above => just comment here
