### ISSUE TITLE
gifmagic.com: breakage

### ISSUE THREAD

**Issue by Windos-7** [uBlockOrigin/uAssets#23694]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gifmagic.com/`

### Category

breakage

### Description

gifmagic.com shows a blank white screen with uBO enabled, goes away when disabling adblock
disabling cosmetic filtering gets rid of the blank screen, but upon uploading a file, editor buttons like "effects" cannot be used without disabling adblock (normally it should pull down a drop-down menu)
website states in footer that "***Use of Ad blockers disables this site." - malicious breakage on part of the site owner

### Other extensions used

none
clean profile in Brave, shields disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/79429736/cfc6fe94-4cd4-4ed2-907f-101f90d63548)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 119
filterset (summary):
 network: 135242
 cosmetic: 47318
 scriptlet: 20855
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38036-277, 1m
  ublock-badware: 8497-0, now
  ublock-privacy: 905-0, now
  ublock-unbreak: 2274-0, now
  ublock-quick-fixes: 258-0, 1m
  easylist: 87740-546, 1m
  easyprivacy: 50894-22, 1m
  urlhaus-1: 12865-1, 1m
  plowe-0: 3729-788, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1848 ms
 maxAssetCacheWait: 1259 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googlesyndication.com: 1
 extended:
  ###adcontainer
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
gifmagic.com#@##adcontainer
```

@ryanbr
