### ISSUE TITLE
play.geforcenow.com: ads

### ISSUE THREAD

**Issue by Cactism** [uBlockOrigin/uAssets#23692]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://play.geforcenow.com/games?game-id=f66d19a8-4d80-406f-b1f0-075ff5e9b51c&lang=en_US&asset-id=01_47622aeb-7d9d-4289-8e56-ecb27af291f1`

### Category

ads

### Description

WITHOUT MY CUSTOM LISTS, there are occasionally ads once you are in the queue of a game you're trying to play.

~~WITH MY OWN LISTS, there is also an "adblocker detected" popup, as it appears that the page is detecting that `simulmedia-apis.com` is being blocked.~~ Nevermind, this appears to be due to Microsoft Edge's `Strict Tracking Prevention` setting and is unrelated to uBlock Origin's lists (however after Googling `simumedia-apis`, it appears it is an advertising platform — is it possible for this to be blocked and to evade the adblocker detected popup?).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Stock uBlock Origin:
![image](https://github.com/uBlockOrigin/uAssets/assets/88598340/0c8e57e3-f3a9-42c4-8cfc-13974eec3871)

~~My Lists:~~ Disregard, see message above.
![image](https://github.com/uBlockOrigin/uAssets/assets/88598340/0fe8da2c-95c3-4dc8-8fac-7eaed9f31cd0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 230431
 cosmetic: 255291
 scriptlet: 52797
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78859-78859, now
  CHN-0: 25695-155, now
  adguard-cookies: 29581-71, now
  adguard-generic: 81523-6839, now
  adguard-mobile-app-banners: 5193-1108, now
  adguard-other-annoyances: 14237-364, now
  adguard-popup-overlays: 27348-1693, now
  adguard-social: 22926-883, now
  adguard-spyware: 83491-31921, now
  adguard-spyware-url: 1511-5, now
  adguard-widgets: 2500-39, now
  easylist-annoyances: 4600-16, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 87597-695, now
  easyprivacy: 50898-922, now
  plowe-0: 3729-0, now
  ublock-badware: 8497-0, now
  ublock-filters: 38035-622, now
  ublock-privacy: 905-115, now
  ublock-quick-fixes: 257-0, now
  ublock-unbreak: 2274-3, now
  urlhaus-1: 13005-1, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 447 ms (selfie)
 maxAssetCacheWait: 260 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
@Cactism we need an account to check your issue. Are you willing to provide it to us ? (I'll provide an email address where you can send user / pass in case you agree)

**Comment by mapx-** [comment]
send it here (and the steps to reproduce the issue): `axis.trivia@gmail.com`

**Comment by stephenhawk8054** [comment]
@Cactism Can you test this filter?

```adb
play.geforcenow.com##+js(json-prune-fetch-response, session.sessionAds session.sessionAdsRequired, , propsToMatch, /session)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
