### ISSUE TITLE
anikore.jp: breakage

### ISSUE THREAD

**Issue by r4oz8** [uBlockOrigin/uAssets#23695]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.anikore.jp/
```

### Description

A flash of about 1 second occurs when the page loads.

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 137203
 cosmetic: 59636
 scriptlet: 20988
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37953-367, 2m
  ublock-badware: 8488-0, 3m
  ublock-privacy: 905-0, 2m
  ublock-unbreak: 2274-0, 3m
  ublock-quick-fixes: 257-0, 3m
  easylist: 87609-460, 2m
  easyprivacy: 50894-810, 2m
  urlhaus-1: 12865-1, 2m
  plowe-0: 3729-0, 2m
  JPN-1: 14709-68, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 426 ms
 maxAssetCacheWait: 89 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Not sure if you mean the blank page at loading time or not. If it is, maybe this?

```adb
anikore.jp##html[class^="loading"]:style(visibility: visible !important;)
```

cc @Yuki2718

**Comment by r4oz8** [comment]
Yes, I mean the blank page at loading time. Sorry for not explaining enough.

**Comment by Yuki2718** [comment]
No idea why the site does this if GTM is blocked, not even looks like an anti-adb.

**Comment by r4oz8** [comment]
@Yuki2718 The same issue occurs on the following page as well (blank page at loading time).

```
https://paiza.jp/
```
