### ISSUE TITLE
lectormh.com: detection

### ISSUE THREAD

**Issue by Nicolas-2307** [uBlockOrigin/uAssets#23693]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lectormh.com/`

### Category

detection

### Description

no me deja entrar al sitio con el blokeador de anuncios activo

### Other extensions used

AdBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 137601
 cosmetic: 53795
 scriptlet: 21290
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87597-602, now
  easyprivacy: 50898-825, now
  plowe-0: 3729-0, 7m
  spa-0: 4063-3, 7m
  spa-1: 5629-184, now
  ublock-badware: 8497-0, now
  ublock-filters: 38036-293, now
  ublock-privacy: 905-0, now
  ublock-quick-fixes: 257-0, now
  ublock-unbreak: 2274-4, now
  urlhaus-1: 12865-1, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 279 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ###fixedban
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I am not using uBlock Origin along with other content blockers.
> - [X] I did not answer truthfully to **ALL** the above checkboxes.

> **Other extensions used**
>
> AdBlock

Test again in a new browser profile with only uBO and its default settings.
