### ISSUE TITLE
dailymotion.com: breakage

### ISSUE THREAD

**Issue by niStee** [uBlockOrigin/uAssets#23691]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dailymotion.com/video/x8yamd8`

### Category

breakage

### Description

video is not loading

### Other extensions used

Bypass Paywalls Clean
CanvasBlocker
Privacy Redirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 245422
 cosmetic: 267843
 scriptlet: 51212
 html: 2048
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81522-3986, now
  adguard-mobile: 9377-56, now
  adguard-spyware-url: 1511-120, now
  adguard-spyware: 83491-1371, now
  block-lan: 66-0, now
  curben-phishing: 458-0, now
  adguard-social: 22926-53, now
  adguard-cookies: 29578-46, now
  ublock-cookies-adguard: 1145-13, now
  adguard-popup-overlays: 27348-1003, now
  adguard-mobile-app-banners: 5192-23, now
  adguard-other-annoyances: 14237-413, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 38154-110, now
  ublock-badware: 8499-0, now
  ublock-privacy: 906-2, now
  ublock-unbreak: 2331-2, now
  ublock-quick-fixes: 192-5, now
  easylist: 87597-1936, now
  easyprivacy: 50898-31573, now
  urlhaus-1: 13005-1, now
  plowe-0: 3729-1646, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 8 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 colorBlindFriendly: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 860 ms (selfie)
 maxAssetCacheWait: 187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  dailymotion.com: 2
  dm-event.net: 16
  doubleclick.net: 1
  googlesyndication.com: 1
  hubvisor.io: 1
  scorecardresearch.com: 1
 extended:
  ##div[class^="DisplayAd"]
  ##div[class^="NewWatchingDiscovery__adSection"]
  ##+js(no-setTimeout-if, adBlockerDetection)
  ##+js(set-cookie-reload, cookie_policy_closed, 1)
  ##+js(trusted-set-cookie, dm-euconsent-v2, CPt6yMAPt6yMABpAGAEND…
  ##+js(set-cookie, cookie_policy_closed, 1, , reload, 1)
  ##+js(xml-prune, VAST, , adnxs)
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me. Do you disabled autoplay in firefox? If yes enable it and test again.

**Comment by krystian3w** [comment]
Also disable list to "play next" by DandelionSprout:

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt

**Comment by niStee** [comment]
Thanks a lot @krystian3w and @JobcenterTycoon :)

**Comment by ghost** [comment]
I do have a breakage on Firefox mobile, the page won't load completely:
https://github.com/user-attachments/assets/a7cc1459-65b2-400e-b066-73e602e4c4ce

Meanwhile on Edge, no issues:
https://github.com/user-attachments/assets/dbebdfa4-bd0d-4f7d-8604-865420768216

My troubleshooting info:

<details>

```yaml
uBlock Origin: 1.65.0
Firefox Mobile: 142
filterset (summary):
 network: 159127
 cosmetic: 92771
 scriptlet: 32885
 html: 2374
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 46201-167, never
  ublock-cookies-easylist: 5085-32, never
 default:
  user-filters: 0-0, never
  ublock-filters: 41855-76, 41m
  ublock-badware: 11470-31, 41m
  ublock-privacy: 3426-3, 41m
  ublock-unbreak: 2737-1, 41m
  ublock-quick-fixes: 312-12, 41m
  adguard-mobile: 11313-68, 42m
  easylist: 76963-275, 42m
  easyprivacy: 54395-65, 42m
  urlhaus-1: 30370-5, 42m
  plowe-0: 3420-977, 42m
  ROU-1: 1493-35, 42m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 181 ms (selfie)
 maxAssetCacheWait: 82 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  dailymotion.com: 5
  dm-event.net: 15
  imasdk.googleapis.com: 2
 extended:
  ##div[class^="AdBanner"]
```


</details>

**Comment by ghajini** [comment]
@Alex-302
`||dmxleo.dailymotion.com/cdn/manifest/video/$xhr,from=dailymotion.com`
cause breakage on default settings

**Comment by Alex-302** [comment]
@ghajini https://github.com/AdguardTeam/AdguardFilters/commit/b2789e0659fdd12d2843f23a33b8523f0600a922

**Comment by ghost** [comment]
I got one ad slipping through, and even the "Retrieving ad" message before video starts playback, on Firefox Mobile.

Tested on `https://www.dailymotion.com/video/x8p3i9f`

https://github.com/user-attachments/assets/c98a6fcf-53dd-4d00-a9d0-10efe634640f
https://github.com/user-attachments/assets/e0c4849f-0544-4bee-87a7-60e39ae0b486

<details>

```yaml
uBlock Origin: 1.66.0
Firefox Mobile: 142
filterset (summary):
 network: 160848
 cosmetic: 53052
 scriptlet: 23558
 html: 2364
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41556-75, 4m
  ublock-badware: 10987-31, 4m
  ublock-privacy: 3480-3, 2m Δ
  ublock-unbreak: 2745-1, 2m Δ
  ublock-quick-fixes: 321-12, 2m Δ
  adguard-mobile: 11371-67, 5m
  easylist: 80027-279, 4m
  easyprivacy: 54551-70, 4m
  urlhaus-1: 31485-5, 4m
  plowe-0: 3421-979, 4m
  ROU-1: 1572-35, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 169 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 147
 network:
  dailymotion.com: 2
  360yield.com: 4
  4dex.io: 1
  a-mo.net: 1
  adform.net: 5
  adnxs.com: 6
  amazon-adsystem.com: 1
  brainlyads.com: 1
  casalemedia.com: 2
  cootlogix.com: 5
  dm-event.net: 32
  dmxleo.com: 15
  doubleclick.net: 21
  hubvisor.io: 1
  imasdk.googleapis.com: 2
  indexww.com: 1
  ingage.tech: 1
  lijit.com: 1
  nextmillmedia.com: 1
  nexx360.io: 2
  openx.net: 3
  opera.com: 1
  qortex.ai: 3
  rubiconproject.com: 15
  seedtag.com: 1
  servenobid.com: 2
  smaato.net: 4
  smartadserver.com: 8
  teads.tv: 1
  yahoo.com: 3
  yellowblue.io: 1
 extended:
  ##div[class^="DisplayAd"]
  ##div[class^="AdBanner"]
```

</details>


Got an ad also using Edge, on the same video.
Sometimes it doesn't want to play the video, it just breaks.

<details>

https://github.com/user-attachments/assets/7e6b9c84-21b9-4d57-a92a-52696f113c52

</details>

**Comment by stephenhawk8054** [comment]
@ghajini Hmm... Can you check if we block only the XHR, does the previous issue on mobile occur?

```adb
||dmxleo.dailymotion.com^$xhr
```

**Comment by ghost** [comment]
I tried that filter myself meanwhile, but the video won't load, the thumbnail remains only.

However, for about half-a-second before, it did show up starting.

On Firefox, it keeps showing me "Loading video"

Recording showing it on both Firefox and Edge Mobile having uBO + that filter:

https://streamable.com/vv0zpw

**Comment by ghajini** [comment]
> @ghajini Hmm... Can you check if we block only the XHR, does the previous issue on mobile occur?
> 
> ```adb
> ||dmxleo.dailymotion.com^$xhr
> ```

It breaks the video.
I don't see the an actual ad.@pilis1 try waiting some sec after browser start & disable other extensions

**Comment by stephenhawk8054** [comment]
@pilis1 @ghajini Can you test these filters:

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima.js,domain=dailymotion.com,important,badfilter
||dmxleo.dailymotion.com^
```

If it doesn't work, remove the 2nd filter and test again.

**Comment by ghost** [comment]
I tried again after 10 seconds when the browser was opened. Only uBO active.

Firefox with uBO + the filter [above](https://github.com/uBlockOrigin/uAssets/issues/23691#issuecomment-3291586492): the video remains stuck on "Loading video"

Firefox with uBO, without the filter: I get a "Retrieving ad" for a few seconds, then I get an ad (the same ad at Castrol as above), and after that the video starts.

Edge with uBO: in both cases, with and without that filter, the video won't load, it remains stuck on the thumbnail.

**Comment by stephenhawk8054** [comment]
There are 2 filters. If it doesn't work, remove the `||dmxleo.dailymotion.com^` and test again.

**Comment by ghost** [comment]
I know, I was writing the comment right when you mentioned the two new filters where you tagged me and ghajini. I will try now again.

**Comment by ghost** [comment]
> [@pilis1](https://github.com/pilis1) [@ghajini](https://github.com/ghajini) Can you test these filters:
> 
> ||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima.js,domain=dailymotion.com,important,badfilter
> ||dmxleo.dailymotion.com^
> If it doesn't work, remove the 2nd filter and test again.

On Edge: breakage in all three cases: with the first filter, the second one, and both at the same time. It just remains stuck on the thumbnail and it won't load.

On Firefox:

With the first filter: I get an ad, after the ad, the video starts.

With the 2nd one: The player remains stuck on "Loading video" but it actually started, if you turn on the audio, you can hear it. The player however remains stuck on that screen. So it does apply also in my previous comment too.

Both filters at the same time: same as in the case with 2nd filter only.

**Comment by ghost** [comment]
> With the 2nd one: The player remains stuck on "Loading video" but it actually started, if you turn on the audio, you can hear it. The player however remains stuck on that screen. So it does apply also in my previous comment too.
> 
> Both filters at the same time: same as in the case with 2nd filter only.

Here is a recording where you can better see it:

<details>

https://github.com/user-attachments/assets/41f23135-fe32-4d9b-bac1-c02e230ed458

</details>

**Comment by stephenhawk8054** [comment]
For the ads, test this filter (no other filters needed):

```adb
||dmads.dailymotion.com^
```

It's not for the `Retrieving ads` though.

**Comment by ghost** [comment]
Unfortunately it doesn't work, the ad still appears:
https://streamable.com/80o7rr

~~On Edge, only with this filter, the breakage still remains. The video is stuck on the thumbnail, no player loading.~~

Now I notice that if I turn off uBO in Edge, the breakage remains, so in that case it's a site issue most likely. I'm gonna focus on Firefox instead.

**Comment by stephenhawk8054** [comment]
Can you test these filters in Firefox:

```adb
dailymotion.com##+js(no-xhr-if, _VMAP_, war:noop-vmap1.xml)
dailymotion.com##+js(json-prune-fetch-response, advertising, , propsToMatch, /player/metadata)
dailymotion.com##+js(json-prune-xhr-response, advertising, , propsToMatch, .json)
```

**Comment by ghost** [comment]
The ads don't appear but the player is stuck on "Loading video". The video however started playing, you can hear the audio, it just remains stuck on the screen, as in the recording from: https://github.com/uBlockOrigin/uAssets/issues/23691#issuecomment-3291914111

**Comment by stephenhawk8054** [comment]
If you refresh the site, does the video play?

**Comment by ghost** [comment]
No, it happens the same as here:
https://github.com/uBlockOrigin/uAssets/issues/23691#issuecomment-3291914111

**Comment by stephenhawk8054** [comment]
I can only reproduce the issue when loading the video at the first time. After I refresh the site, I can't reproduce any more.

**Comment by stephenhawk8054** [comment]
Can you test these:

```adb
dailymotion.com##+js(xml-prune, [breakId], , _VMAP_)
dailymotion.com##+js(json-prune-fetch-response, advertising, , propsToMatch, /player/metadata)
dailymotion.com##+js(json-prune-xhr-response, advertising, , propsToMatch, .json)
||dmads.dailymotion.com^
@@||dailymotion.com/nativeads.js|
```

**Comment by ghost** [comment]
~~Did you use only the three filters from https://github.com/uBlockOrigin/uAssets/issues/23691#issuecomment-3292086399 or you also added other filters in combination?~~

Ok, it happened again to write at the same time. I will test and return with the result.

**Comment by ghost** [comment]
> Can you test these:
> 
> ```adb
> dailymotion.com##+js(xml-prune, [breakId], , _VMAP_)
> dailymotion.com##+js(json-prune-fetch-response, advertising, , propsToMatch, /player/metadata)
> dailymotion.com##+js(json-prune-xhr-response, advertising, , propsToMatch, .json)
> ||dmads.dailymotion.com^
> @@||dailymotion.com/nativeads.js|
> ```

It got fixed with those! 🎉

**Comment by ghajini** [comment]
(Sorry iam late for feedback,just got time)

Does this video `https://geo.dailymotion.com/player.html?playlist=x98j90&video=k1M6K60FfXYc5LDQbBu`

Works for everyone? Iam stuck at **Loading video**
These are found at dailymotion stream at `https://1max.top/watch-aew-collision-live-9-13-25-september-13th-2025-online-full-show-free/`

Using firefox mobile,ubo stable 1.66

**Comment by ghost** [comment]
It works for me, with and without the filters from https://github.com/uBlockOrigin/uAssets/issues/23691#issuecomment-3292759730

**Comment by ghost** [comment]
I noticed that, if you load the site for the first time or without cookies, the page looks weird, but after second refresh, it looks normal:
https://pixvid.org/video/kJvmn

<details>

```yaml
uBlock Origin: 1.66.4
Firefox: 144
filterset (summary):
 network: 166325
 cosmetic: 111161
 scriptlet: 34754
 html: 2445
listset (total-discarded, last-updated):
 added:
  ublock-experimental: 16-0, 8m
  adguard-cookies: 35689-72, 8m
  ublock-cookies-adguard: 5215-77, 8m
  fanboy-cookiemonster: 46481-3944, 8m
  ublock-cookies-easylist: 5215-5215, 8m
 default:
  user-filters: 62-1, never
  ublock-filters: 41475-71, 8m
  ublock-badware: 11118-31, 8m
  ublock-privacy: 3524-2, 8m
  ublock-unbreak: 2750-1, 8m
  ublock-quick-fixes: 385-12, 22m
  easylist: 82545-152, 22m Δ
  easyprivacy: 54715-44, 22m Δ
  urlhaus-1: 31195-5, 22m
  plowe-0: 3443-933, 8m
  ROU-1: 1585-35, 8m
filterset (user): [array of 57 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 415 ms (selfie)
 maxAssetCacheWait: 187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  dailymotion.com: 7
  dm-event.net: 22
  hubvisor.io: 1
  imasdk.googleapis.com: 2
 extended:
  ##div[class^="DisplayAd"]
  ##.WatchingDiscovery__adSection___eLtfR
  ##+js(set-cookie, cookie_policy_closed, 1, '', reload, 1)
  ##+js(trusted-set-cookie, dm-euconsent-v2, CQEXy8AQEXy8ABpAIAENA…
  ##+js(trusted-set-cookie, consentUUID, 4828f4be-a6c6-46d4-b46a-5…
  ##+js(set-cookie-reload, cookie_policy_closed, 1)
  ##+js(set-constant, __NATIVEADS_CANARY__, true)
  ##+js(trusted-click-element, button[title="Continue without acce…
```

</details>
