### ISSUE TITLE
uno-online.io: breakage

### ISSUE THREAD

**Issue by ffsmyusernameistaken** [uBlockOrigin/uAssets#23690]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uno-online.io/uno-multiplayer`

### Category

breakage

### Description

I can't play the game with UO enabled, it freezes.

### Other extensions used

Google Translate, Tamper Monkey, Session Buddy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26306446/ba040e3d-e5ec-424f-928c-1759f3f18efc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 109
filterset (summary):
 network: 128550
 cosmetic: 121510
 scriptlet: 40378
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1701-0, now
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 23195-86, now
  adguard-generic: 81522-5864, now
 default:
  user-filters: 5-0, never
  RUS-0: 39454-2597, now
  easylist: 87597-732, now
  plowe-0: 3729-7, now
  ublock-badware: 8497-0, now
  ublock-filters: 38035-146, now
  ublock-privacy: 905-7, 1h.49m Δ
  ublock-quick-fixes: 256-0, now
  ublock-unbreak: 2274-5, 1h.49m Δ
  urlhaus-1: 13005-1, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 16 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2882 ms (selfie)
 maxAssetCacheWait: 1318 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  adform.net: 1
  amazon-adsystem.com: 1
  beesads.com: 1
  bidswitch.net: 1
  creativecdn.com: 1
  criteo.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  onetag-sys.com: 1
  sharethrough.com: 1
  tappx.com: 2
 extended:
  ##.ads-title
  ##.ads-content
  ##ins.adsbygoogle[data-ad-slot]
  ###google_ads_frame1
  ##.ads-bg
  ##.ads-main
```
</details>

**Comment by ffsmyusernameistaken** [comment]
I have this jumping ractangle in the middle and I can't click anything, it works when I disable Ublock Origin.

**Comment by JobcenterTycoon** [comment]
`enjoy4fun.com###fake-ads-dom` works for me.
