### ISSUE TITLE
rollingstone.com: breakage

### ISSUE THREAD

**Issue by golpix2000** [uBlockOrigin/uAssets#23702]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rollingstone.com/music/music-lists/best-albums-of-all-time-1062063/`

### Category

breakage

### Description

Lists don't appear on the website with uBlock enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-15 at 10-25-13 The 500 Greatest Albums of All Time](https://github.com/uBlockOrigin/uAssets/assets/120168525/e96212ae-e48b-45bc-94a2-e9cd211fa05b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 152129
 cosmetic: 53589
 scriptlet: 19581
 html: 1801
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38170-218, 37m
  ublock-badware: 8515-0, 37m
  ublock-privacy: 905-0, 37m
  ublock-unbreak: 2332-0, 37m
  ublock-quick-fixes: 193-0, 37m
  easylist: 87531-669, 37m
  easyprivacy: 50907-1014, 37m
  urlhaus-1: 12635-1, now
  plowe-0: 3729-0, now
  FRA-0: 24425-110, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 108 ms (selfie)
 maxAssetCacheWait: 49 ms
popupPanel:
 blocked: 30
 network:
  rollingstone.com: 2
  blogherads.com: 4
  connatix.com: 1
  cxense.com: 1
  google-analytics.com: 2
  googletagmanager.com: 2
  hotjar.com: 1
  imhd.io: 1
  lightboxcdn.com: 2
  onesignal.com: 1
  parsely.com: 1
  pmc.com: 2
  rfpx1.com: 1
  s3-us-west-2.amazonaws.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
  swiftype.com: 1
  trackonomics.net: 1
  typekit.net: 1
  videoplayerhub.com: 1
  wp.com: 2
 extended:
  ###skin-ad-left-rail-container
  ###skin-ad-right-rail-container
  ##.admz
  ##.pmc-adm-boomerang-pub-div
  ##.ad-text
  ###sticky-rail-ad
  ##+js(abort-on-property-read, googletag)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
rollingstone.com#@#+js(aopr, googletag)
```

@ryanbr
