### ISSUE TITLE
voz.vn: ads

### ISSUE THREAD

**Issue by darkrain261** [uBlockOrigin/uAssets#23700]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://voz.vn/`

### Category

ads

### Description

I'm using Edge and only having this problem with Edge. Sometimes, when I open this web, the ad layout is visible but not its content. This does not always happen but when it does, the only way to make uBO works on this web again is to restart Edge.

### Other extensions used

1. AHA Music - Song Finder for Browser
2. IDM Integration Module
3. Audio Only Youtube
4. Auto Link Bypasser
5. FastForward
6. Google Docs Offline
7. Google Translate
8. Pop up blocker for Chrome™ - Poper Blocker
9. Remove YouTube End Cards & End Screen Videos
10. Return YouTube Dislike
11. Sidesy: Your Comments Sidebar For YouTube
12. Social Fixer for Facebook
13. Tampermonkey
14. Voz Next
15. WebNowPlaying
16. YouTube™ Comment Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/103837232/99cf9d96-f550-4869-969a-4abe20782cea)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 141397
 cosmetic: 100770
 scriptlet: 28343
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27334-879, now
  adguard-mobile-app-banners: 5199-1109, now
  adguard-other-annoyances: 14243-374, now
  adguard-widgets: 2499-17, now
  easylist-annoyances: 4600-41, now
  easylist-chat: 196-0, 26m
  easylist-newsletters: 7383-11, now
  easylist-notifications: 2983-84, now
  ublock-annoyances: 5885-38, 27m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 38047-602, 27m Δ
  ublock-badware: 8513-0, 27m Δ
  ublock-privacy: 905-0, 27m Δ
  ublock-unbreak: 2275-0, 27m Δ
  ublock-quick-fixes: 257-0, 27m Δ
  easylist: 87506-622, 27m Δ
  easyprivacy: 50899-918, 27m Δ
  urlhaus-1: 12905-1, 26m
  plowe-0: 3729-0, 26m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 295 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 91
 network:
  voz.vn: 3
  4dex.io: 2
  adbro.me: 2
  adform.net: 3
  adnxs.com: 4
  aj1559.online: 3
  amazon-adsystem.com: 4
  bannerflow.net: 2
  casalemedia.com: 4
  cloudflareinsights.com: 1
  creativecdn.com: 4
  criteo.com: 8
  doubleclick.net: 4
  google-analytics.com: 1
  google.com: 8
  imasdk.googleapis.com: 1
  optad360.io: 3
  pubmatic.com: 4
  pubpowerplatform.io: 19
  quantumdex.io: 4
  richaudience.com: 4
  script.ac: 1
  youtube.com: 2
 extended:
  ##.p-footer-rssLink
  ##.u-scrollButtons
  ##.ad-loader
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerConfig.ssapCon…
  ##+js(set-constant, ytInitialPlayerResponse.streamingData.server…
  ##+js(json-prune, playerResponse.playerConfig.ssapConfig playerR…
  ##+js(trusted-replace-node-text, script, /^(\(function serverCon…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune-fetch-response, overlay, overlay.shortsAdsRende…
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `ABPVN List` and test again

**Comment by darkrain261** [comment]
> Enable `ABPVN List` and test again

Sorry for late reply as I was busy this week. I turned ABPVN on but it seems no effects so far. It usually happens like this:
When I fresh open Edge, this web's ads are blocked as normal. But if I leave Edge open for a while, the access the web, the ads layout will be back. Happen to another web as well, I used uBO on Chrome and this didn't happen before.

**Comment by stephenhawk8054** [comment]
@darkrain261 Test again in a new Edge profile with only uBO and its default settings + ABPVN list

**Comment by stephenhawk8054** [comment]
@darkrain261 First, disable all other extensions except uBO, restart the browser, open new tab (important) and test again.

**Comment by darkrain261** [comment]
> @darkrain261 First, disable all other extensions except uBO, restart the browser, open new tab (important) and test again.

I tried a number of time with uBO only and it seems to work perfectly. No ads showing after open the browser for a while.

**Comment by phanduynam** [comment]
ublock cannot block ads on Voz

**Comment by stephenhawk8054** [comment]
Wait until next uBOL version update.
