### ISSUE TITLE
google.com: breakage, nuisance

### ISSUE THREAD

**Issue by jackrjli** [uBlockOrigin/uAssets#23701]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://lens.google.com/search?p=AbrfA8rj9ThWDrIo-Ntv6o2D-ckgEuIFw1BiDTOC_1VY2PzHfHrkeUHyP44x9dzbt4aq2T975M2sLsMYU24McdJJ83eTvwsg-ZiN8VtJK8jC2KnZfkjkUsxPp_-eGiGHwq_6S-35PEPgAqSpEc0eUb2gxSkdgVlexWSJzSVAmuVL27LJPw5qDX1reKoPzUdTAa3vSNCpkClRHp5vmA%3D%3D#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLDEsIkVrY0tKRFEwTWpOak56TmpMVGRoTXpBdE5EbGlPQzA0WXpoaUxXWXpPRFJsTVRjeFpEbGhZaElmTUY5Sk9VWTNTSHBXVjAxVlVVVjFlRFl4WHpJd1dFSTRVa2hYY3psNFp3PT0iLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLFtudWxsLG51bGwsW11dXQ==
```
This search is not NSFW, but the issue may be easier to visualize with a NSFW search since results would be blurred with SafeSearch on.

### Description

When searching by image on Google (lens.google.com, or clicking on the camera icon on images.google.com, _not_ a text search on Google Images), explicit images are blurred by default, and there is a notice on top of the search results from which you can change your SafeSearch settings ("Manage" next to "SafeSearch blurring is on"). However, when the "**uBlock filters – Cookie Notices**" list is enabled, this setting does not work; even if you select "Off," the results are still blurred, and the header says "SafeSearch blurring is on."

I've narrowed it down to this rule:
https://github.com/uBlockOrigin/uAssets/blob/7441290afd617dff2089b54fc14e8c308dedcaec/filters/annoyances-cookies.txt#L46

Disabling that rule with this custom rule fixes the issue:
```
www.google.*#@#+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9SQzIaAmZpIAEaBgiAzK6kBg, 1year)
```

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

SafeSearch turned off:
![safesearch-off](https://github.com/uBlockOrigin/uAssets/assets/2382506/adce2177-9b8d-441f-92d9-87ec6b156825)

SafeSearch is still enabled after turning it off and clicking the back arrow (nothing is blurred in this image because none of the results are explicit, but they would be blurred if they were explicit):
![safesearch-on](https://github.com/uBlockOrigin/uAssets/assets/2382506/3b170774-9d16-4ae4-8dd5-6e386909d83e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 135040
 cosmetic: 47155
 scriptlet: 20377
 html: 1801
listset (total-discarded, last-updated):
 added:
  ublock-cookies-easylist: 1145-0, never
 default:
  user-filters: 0-0, never
  ublock-filters: 38170-110, 7m
  ublock-badware: 8515-0, 7m
  ublock-privacy: 907-2, 7m
  ublock-unbreak: 2332-2, 7m
  ublock-quick-fixes: 193-5, 7m
  easylist: 87506-159, 7m
  easyprivacy: 50899-67, 7m
  urlhaus-1: 12635-3, 7m
  plowe-0: 3729-1160, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3048 ms
 maxAssetCacheWait: 2230 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  google.com: 8
```
</details>

**Comment by krystian3w** [comment]
Worse if we can't remove filter (lack of alternative in stable selector for `trusted-click-element).

You should definitely make sure that the new cookie value does not globally unlock violence and nudity.

**Comment by Yuki2718** [comment]
On my end the SafeSearch setting doesn't work even without uBlock filters - Annoyacnes. @peace2000 Can you reproduce?

**Comment by peace2000** [comment]
Hmm.

I can only reproduce occasionally. What exact steps are needed to reproduce this each time?

@jackrjli @Yuki2718 

Can you test with this filter?

`www.google.*##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjQwNTE0LjA2X3AwGgJmaSADGgYIgOu0sgY, 1year)`

It enables search customization but not personalized ads.

**Comment by stephenhawk8054** [comment]
I think we should not use `1year` as it's difficult for most users to know how to revert the effect without clearing all cookies of that site.

**Comment by jackrjli** [comment]
@peace2000 That filter works for me, didn't produce this breakage.

The direct link I provided earlier expired, so here's some more detailed steps to reproduce:

1. Go to lens.google.com (alternatively, go to images.google.com and click on the camera icon in the search bar).
2. Enter an image URL or upload a file. Not all images will result in the SafeSearch notice appearing; I found that https://i.redd.it/j5sajm0bka7c1.jpeg is a SFW image but still produces some blurred search results (probably due to the sites it was found on), so that's what I'm using for testing.
3. On the results page, click "Find image source" to go to the "Exact matches" page.
4. There should be a notice at the top of the results saying "SafeSearch blurring is on," with a "Manage" link next to it. Click "Manage," select "Off," then click the left arrow to go back.
5. SafeSearch blurring should be turned off now, but if the issue is present then it will still be on.

**Comment by Yuki2718** [comment]
Yeah, the new rule doesn't have the problem.

**Comment by peace2000** [comment]
I'm still failing to repro. But as it's reproduced by others and I also managed to reproduce it few times yesterday, I believe it's probably best to change the filter.

Though I'm bit puzzled as even if we allow search customization I'm still in doubt whether it affects Safe search functionality. Because Google describes search customization like this: "`Get more relevant results and recommendations by using past Google activity from this browser.`"

Also, when I change the Safe search setting, cookie called `__Secure-ENID` changes it's value. `SOCS` **doesn't change**.

I'm wondering whether the issue is that the problematic filter was created last year and Google has someway changed the logic in their scripts how the cookie value is formed and what values work properly. We need to figure this out, otherwise the new filter will break functions at some point also.

@Yuki2718 @jackrjli if you are still willing, can you try this newly created "Reject all" filter?

`www.google.*##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyNDA1MjAtMF9SQzEaAmZpIAEaBgiAjrqyBg)`

Also as suggested by @stephenhawk8054 it might a good idea to remove the 1 year expire date and make the cookie last only for a session.

**Comment by jackrjli** [comment]
@peace2000 Unfortunately that new filter breaks things for me again.

**Comment by Yuki2718** [comment]
Can confirm, `www.google.*##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyNDA1MjAtMF9SQzEaAmZpIAEaBgiAjrqyBg)` breaks SafeSearch settings again.

**Comment by stephenhawk8054** [comment]
> Shouldn't we use default expiration period?

Default is session.

**Comment by peace2000** [comment]
Setting the cookie to last only for a session caused issues: https://www.reddit.com/r/uBlockOrigin/comments/1dh4mi4/google_reverts_to_light_theme_between_sessions_in/

Reverted it back to 1 year.

**Comment by stephenhawk8054** [comment]
If the cookie is related to light/dark theme, I think we should not address this issue any more. I'm quite concerned about cookie issue where there's no easy way to address by users themselves when issues occurred.

**Comment by peace2000** [comment]
`SOCS` cookie does not determine whether the user uses light or dark theme. (I double-checked this).

"Flashbanging" between themes was just a side effect, that was caused by setting `SOCS` cookie as "session only". I don't know exactly why, but when we generate the cookie "naturally" (clicking the dialog manually), Google generates `SOCS` cookie and sets it to expire about 1 year ahead. So Google doesn't expect the cookie to last only for a session. It should last for longer time than a session.

**Comment by stephenhawk8054** [comment]
Yes, many sites set cookies as 1 year by default, but by nature of uBO's `set-cookie`, that's nearly the only thing we should not follow as it could cause interference with the website and users' choices if they don't know what exact steps to do to revert the effects in case some issues happen again (users would see that not even turning off uBO alone can fix the issues).
