### ISSUE TITLE
bydleni.cz : ads

### ISSUE THREAD

**Issue by wowfilip999** [uBlockOrigin/uAssets#23705]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.bydleni.cz/
```

### Description

![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/49549e7f-aac3-4341-b2bf-7be448cb27cf)
ads on side and image 
but if i add ||www.bydleni.cz/bs12/delivery/
ads gone add this to czech regional filter please

![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/e0174fae-b3c1-4cc2-a99f-7b439138718a)
this ad is https://cdn.bydleni.com/dm/banner/pruhledny_1140x100.gif
![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/51ce5c1d-831c-4dd0-8337-751f16bdee5f)
https://cdn.bydleni.com/dm/banner/fat_04-24/fatra.jpg this link is the ad but i used ||www.bydleni.cz/bs12/delivery/ and this ad show no more  the "silvero" on screenshot

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/49549e7f-aac3-4341-b2bf-7be448cb27cf)

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    
default

**Comment by stephenhawk8054** [comment]
```adb
||bydleni.com/dm/banner/$image,domain=bydleni.cz
bydleni.cz###rightClick
bydleni.cz###clickLeft
```

@tomasko126 @mlnrDev Sorry, can you take a look?

**Comment by wowfilip999** [comment]
> ```
> ||bydleni.com/dm/banner/$image,domain=bydleni.cz
> bydleni.cz###rightClick
> bydleni.cz###clickLeft
> ```

![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/6c1943d0-9c20-45d9-9dd0-213d77eb6a29)
this syntax not block all ads i used ||www.bydleni.cz/bs12/delivery/
and all blocked

**Comment by stephenhawk8054** [comment]
Refresh the page while bypassing the cache (`Ctrl + Shift + R`) and test again

**Comment by wowfilip999** [comment]
> ```
> ||bydleni.com/dm/banner/$domain=bydleni.cz
> bydleni.cz###rightClick
> bydleni.cz###clickLeft
> ```

ok now its works
