### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by songxiao-shawn** [uBlockOrigin/uAssets#23704]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bilibili.com/`

### Category

breakage

### Description

![微信截图_20240515185708](https://github.com/uBlockOrigin/uAssets/assets/70950370/aed94454-6551-4fff-aee1-8216f5946348)
There is nothing when I open the web, but when I shut down the ublock everything gets back.

### Other extensions used

It has been tested that other extensions are OK with this web.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![微信截图_20240515185708](https://github.com/uBlockOrigin/uAssets/assets/70950370/5c530376-ce31-4b33-b510-60f6ac6d105e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 154800
 cosmetic: 132484
 scriptlet: 24881
 html: 1801
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock.txt: 28058-43, now
  easylist-annoyances: 4595-64, now
  easylist-chat: 196-1, now
  fanboy-cookiemonster: 50997-185, now
  ublock-cookies-easylist: 1145-3, now
  easylist-newsletters: 7399-21, now
  easylist-notifications: 2986-164, now
  fanboy-social: 15980-15, now
 default:
  ublock-filters: 38196-130, 1h.58m Δ
  ublock-badware: 8548-0, 1h.58m Δ
  ublock-privacy: 907-2, 1h.58m Δ
  ublock-unbreak: 2332-4, 1h.58m Δ
  ublock-quick-fixes: 193-5, 1h.58m Δ
  easylist: 87514-405, 1h.58m Δ
  easyprivacy: 50907-83, 1h.58m Δ
  urlhaus-1: 12635-3, now
  plowe-0: 3729-1162, now
  CHN-0: 25735-25641, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 317 ms (selfie)
 maxAssetCacheWait: 169 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  bilibili.com: 10
 extended:
  ##a[href*="cm.bilibili.com"][data-target-url]:not([data-target-u…
  ##+js(spoof-css, .__adblockhidden > a, display, block)
  ##+js(nowebrtc)
```
</details>

**Comment by stephenhawk8054** [comment]
It's caused by your custom filter list: `https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock.txt`.

Remove it and please respect the prerequisites

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [X] I did not answer truthfully to **ALL** the above checkboxes.
