### ISSUE TITLE
prehrajto.cz: ads(send to czech easylist)

### ISSUE THREAD

**Issue by wowfilip999** [uBlockOrigin/uAssets#23708]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://prehrajto.cz/ahoj-svete-21-prosinec/61c1f12a871cb if search any video ad will show
```

### Description

here is ad img but i found that block ||prehrajto.cz/front/img/ads/* fix that issue please add this to czech regionial block list

![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/582323f2-65a4-44e2-8441-212dd0380e9a)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obrázok](https://github.com/uBlockOrigin/uAssets/assets/67916726/582323f2-65a4-44e2-8441-212dd0380e9a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

none
```
</details>    
###

**Comment by stephenhawk8054** [comment]
Please report these issues to https://github.com/tomasko126/easylistczechandslovak/issues

**Comment by wowfilip999** [comment]
> Please report these issues to https://github.com/tomasko126/easylistczechandslovak/issues

ok

**Comment by wowfilip999** [comment]
i add this on the github page https://github.com/tomasko126/easylistczechandslovak/issues
