### ISSUE TITLE
impula.com: breakage

### ISSUE THREAD

**Issue by BafiBafiBafi** [uBlockOrigin/uAssets#23719]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://impula.com/`

### Category

breakage

### Description

Sitedeki görselleri reklam olarak algılıyor ve .png uzantılı resimleri engelliyor. 

(EN: It detects images on the site as advertisements and blocks images with .png extension.)

### Other extensions used

Free VPN
Metamask

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran görüntüsü 2024-05-16 002818](https://github.com/uBlockOrigin/uAssets/assets/137607152/a749bfaf-4ad5-4ae8-b904-ff761f4805bc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136538
 cosmetic: 56371
 scriptlet: 22392
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38080-373, now
  ublock-badware: 8546-0, now
  ublock-privacy: 906-0, now
  ublock-unbreak: 2275-0, now
  ublock-quick-fixes: 260-0, now
  easylist: 87482-465, now
  easyprivacy: 50910-818, now
  urlhaus-1: 12645-1, now
  plowe-0: 3729-0, now
  TUR-0: 12288-13, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1364 ms (selfie)
 maxAssetCacheWait: 114 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  impula.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `/reklam-$image,from=~donanimhaber.com` in AdGuard Turkish

cc @Yuki2718
