### ISSUE TITLE
puhutv.com: detection

### ISSUE THREAD

**Issue by dixtuel** [uBlockOrigin/uAssets#23713]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://puhutv.com/behzat-c-53-bolum-izle`

### Category

detection

### Description

PuhuTV Üzerinden birşey izleyecekken reklam engelleyiciyi kapatın hatası veriyor.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran görüntüsü 2024-05-15 191357](https://github.com/uBlockOrigin/uAssets/assets/121726849/33c7e421-5f96-461b-add4-f2bf458ccaec)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136452
 cosmetic: 56295
 scriptlet: 21946
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37486-316, now
  ublock-badware: 8546-0, now
  ublock-privacy: 905-0, now
  ublock-unbreak: 2275-0, now
  ublock-quick-fixes: 260-0, now
  easylist: 87533-584, now
  easyprivacy: 50909-24, now
  urlhaus-1: 12645-2, now
  plowe-0: 3729-788, now
  TUR-0: 12288-18, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5208 ms
 maxAssetCacheWait: 1049 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  analytics.edgekey.net: 1
  cookielaw.org: 1
  doubleclick.net: 3
  dygdigital.com: 1
  gemius.pl: 3
  googletagmanager.com: 1
  mncdn.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, adBlockEnabled, false)
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(prevent-fetch, doubleclick.net)
  ##+js(abort-on-property-write, adblockCheck)
```
</details>

**Comment by D4niloMR** [comment]
@Yuki2718 for AdGuard Turkish

`puhutv.com##+js(set, maari, noopFunc)`

**Comment by AdamWr** [comment]
It should be already fixed.
By the way, this website updates anti-adblock script often lately.
