### ISSUE TITLE
vtvcab.vn: detection

### ISSUE THREAD

**Issue by sadtango289** [uBlockOrigin/uAssets#23724]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vtvcab.vn/channel/menu-1,VTV1_HD.html`

### Category

detection

### Description

Detected, prevent video from playback. Site functioning just fine after turning off uBlock.

### Other extensions used

None

### Screenshot(s)

![Screenshot 2024-05-16 191100](https://github.com/uBlockOrigin/uAssets/assets/45529026/5b86fa38-996a-44c3-be39-480656b11e30)

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 263763
 cosmetic: 240737
 scriptlet: 54697
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 25744-1221, 16m
  CZE-0: 832-47, 16m
  DEU-0: 7452-394, 16m
  RUS-0: 39476-1148, 16m
  THA-0: 1485-8, 16m
  VIE-1: 1910-17, 16m
  adguard-cookies: 29601-1655, 16m
  adguard-generic: 81623-7228, 16m
  adguard-mobile: 9381-56, 16m
  adguard-mobile-app-banners: 5205-19, 16m
  adguard-other-annoyances: 14250-375, 16m
  adguard-popup-overlays: 27375-2028, 16m
  [17 lists not shown]: [too many]
 default:
  user-filters: 9-2, never
  easylist: 87478-15683, 17m
  easyprivacy: 50912-244, 17m
  plowe-0: 3729-1286, 17m
  ublock-badware: 8571-2, 17m
  ublock-filters: 38090-877, 17m
  ublock-privacy: 906-118, 17m
  ublock-quick-fixes: 259-0, 17m
  ublock-unbreak: 2275-27, 17m
  urlhaus-1: 12410-3, 17m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 52 redacted]
switchRuleset:
 added: [array of 24 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1850 ms (selfie)
 maxAssetCacheWait: 278 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 1
  firebaselogging-pa.googleapis.com: 3
  googlesyndication.com: 1
  googletagmanager.com: 2
  gviet.vn: 1
```
</details>

**Comment by sadtango289** [comment]
https://github.com/uBlockOrigin/uAssets/assets/45529026/7c7b3f03-101c-4ea6-a8b3-8ede23aba106

Please check the video . This issue is not fixed

**Comment by stephenhawk8054** [comment]
Wait about 5-6 hours and update the filter lists again.

Or you can add this filter as custom filter in the meantime

```adb
||gviet.vn/public/js/player/ads/ima3.js^$script,redirect-rule=google-ima.js,domain=vtvcab.vn
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.
