### ISSUE TITLE
slickdeals.net: breakage

### ISSUE THREAD

**Issue by Simpuhl** [uBlockOrigin/uAssets#23729]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://slickdeals.net/f/17493714-5-bike-tailgate-bike-rack-carrier-pad-after-rebate-9?src=jfy&prop=rcmid-d5ee5914bf9129790b04b47cb64d4382&attrsrc=JFYCarousel%3APosition%3A5%7CJFYCarousel%3AType%3Athread`

### Category

breakage

### Description

Unable to click LINKS on the page, it blocks them and instantly closes them. It almost acts like if they are popups, but these are links I am actually clicking to access.

It only happens when uBlock is enabled, I not have popups blocked either.

It happens on all posts/offers on slick deals, not just the page linked.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Nothing to screenshot as it instantly closes the page when I click a link.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 135174
 cosmetic: 47029
 scriptlet: 20900
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87478-547, now
  easyprivacy: 50918-4, now
  plowe-0: 3729-788, now
  ublock-badware: 8571-0, 1h.13m Δ
  ublock-filters: 38095-276, now
  ublock-privacy: 906-2, 1h.13m Δ
  ublock-quick-fixes: 259-0, 1h.13m Δ
  ublock-unbreak: 2275-18, 1h.13m Δ
  urlhaus-1: 12660-3, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1276 ms
 maxAssetCacheWait: 247 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 36
 network:
  slickdeals.net: 2
  3lift.com: 2
  adnxs.com: 2
  amazon-adsystem.com: 1
  btttag.com: 1
  casalemedia.com: 1
  criteo.com: 1
  criteo.net: 3
  demdex.net: 1
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  heapanalytics.com: 1
  id5-sync.com: 1
  indexww.com: 1
  openx.net: 2
  pinimg.com: 1
  pubmatic.com: 2
  quantserve.com: 1
  redirectingat.com: 1
  sentry.io: 3
  sharethrough.com: 3
  videoplayerhub.com: 1
 extended:
  ###crt-adblock-a
  ###crt-adblock-b
  ##.adunit
  ##.variableHeightAd
  ###bottomDDAd
  ##.abc
```
</details>

**Comment by stephenhawk8054** [comment]
The links are redirected to 3rd-party trackers links. You can right click, copy the link and open in new tab.

**Comment by Simpuhl** [comment]
> The links are redirected to 3rd-party trackers links. You can right click, copy the link and open in new tab.

I get that, but they weren't doing that a week ago. What changed?

**Comment by stephenhawk8054** [comment]
> What changed?

The site changed their codes. 

---

I have added an unblock filter for the popup, but it will still display the blocking page, you can decide to continue each time or click on `Don't warn me again about this site`.

Or I have added a filter for the link in the description to sanitize their click-tracking:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/80c33fd6-d6d7-459a-9cdd-817d6d565295)

You can add these as custom filters while waiting for the filter lists to be updated

```adb
@@||go.redirectingat.com^$popup,3p,domain=slickdeals.net
slickdeals.net##+js(href-sanitizer, a[href^="https://slickdeals.net/?"][href*="u2=http"], ?u2)
```
