### ISSUE TITLE
swissmilk.ch: nuisance

### ISSUE THREAD

**Issue by BenjaminRosenzweig** [uBlockOrigin/uAssets#23721]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.swissmilk.ch/de/`

### Category

nuisance

### Description

Site gets grey overlay and is blocked from view.
Cookie notice appears when UBO is disabled.
I tried different configurations with disabled UBO lists and FF extensions

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s) with grey overlay</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/47740403/c766b7ca-f52a-4950-b78c-816b4b7916bd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 128
filterset (summary):
 network: 263103
 cosmetic: 294243
 scriptlet: 53171
 html: 2082
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 78936-134, now
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, now
  https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5870-17, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 98864-23094, now
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, now
  adguard-generic: 81454-4089, now
  adguard-mobile: 9381-80, now
  adguard-spyware-url: 1512-120, now
  adguard-spyware: 83500-1434, now
  adguard-social: 22941-1643, now
  adguard-cookies: 29601-29601, now
  ublock-cookies-adguard: 1145-15, now
  [16 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 38210-454, 1h.27m Δ
  ublock-badware: 8548-4, 1h.27m Δ
  ublock-privacy: 908-67, 1h.27m Δ
  ublock-unbreak: 2332-6, 1h.27m Δ
  ublock-quick-fixes: 196-5, 1h.32m
  easylist: 87464-2126, 1h.27m Δ
  easyprivacy: 50913-31735, 1h.27m Δ
  urlhaus-1: 12410-3, now
  plowe-0: 3729-1350, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 27 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 37 redacted]
hostRuleset:
 added: [array of 28 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2660 ms
 maxAssetCacheWait: 1587 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 no-remote-fonts: true
 network:
  swissmilk.ch: 13
  googletagmanager.com: 1
 extended:
  ##.CookieBanner:not(body):not(html)
  ##.CookieBanner
```
</details>

**Comment by Yuki2718** [comment]
> possible bug with scroll for iPhone (free license or outdated iOS/Safari lower 15.0).

I don't have an iPhone.

**Comment by krystian3w** [comment]
I mean you should check repair visibility pop-up for Android Content Blocker, Adblock Plus legacy build 3.x and iOS due Ryan and Khrin no longer add exceptions - only repair scrolling or use scriptlets (incompatible with CB, ABP legacy and iOS).

**Comment by BenjaminRosenzweig** [comment]
All i can say is that i use 2 different Windows 10 Computers with Firefox Nightly and Firefox on each installed and i get the same grey overlay in all 4 situations. I certainly tried with different UBO filterlists and FF Extensions disabled. 
With UBO disabled i get the cookie notice, otherwise the grey overlay.

**Comment by stephenhawk8054** [comment]
```adb
swissmilk.ch##html.cookie-banner-open:remove-class(cookie-banner-open)
```

@ryanbr @Alex-302
