### ISSUE TITLE
seznam.cz: nuisance

### ISSUE THREAD

**Issue by Aeyesx** [uBlockOrigin/uAssets#23727]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.seznam.cz/
https://cmp.seznam.cz/nastaveni-souhlasu
https://www.novinky.cz/
https://www.sbazar.cz/
https://www.firmy.cz/
https://www.sport.cz/
https://www.stream.cz/
```

### Description

The crappy Seznam.cz a.s. recently introduced super annoying popups that require one to agree so they can track everything. It saves cross-site cookie and shares data with ad companies, whats ridiculous is that the pay button doesn't even remove the ads. They kept making changes but it seems this is the final version.

Is it possible to get rid of these?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![BS1](https://github.com/uBlockOrigin/uAssets/assets/5220885/b307aaa1-fb4a-4ba6-b680-759c80237a63)
![BS2](https://github.com/uBlockOrigin/uAssets/assets/5220885/ac4c5341-098c-48f0-82ca-1f1affe8be9d)
![BS3](https://github.com/uBlockOrigin/uAssets/assets/5220885/fb4108bf-9850-43df-bb4d-18c0e636bda6)

**Comment by Houfino** [comment]
I also want to block and that's annoying..

**Comment by stephenhawk8054** [comment]
@Houfino Enable `EasyList/uBO – Cookie Notices` lists

**Comment by Houfino** [comment]
It doesn't work.. Probably the end :-/

They worked about 3-4 months ago.. We already solved it... now it doesn't work anymore....

[https://github.com/uBlockOrigin/uAssets/issues/23727](url)
