### ISSUE TITLE
nisanyansozluk.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#23722]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nisanyansozluk.com/?k=`

### Category

nuisance

### Description

Welcome popup

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-16 at 12-43-08 Nişanyan Sözlük - Türkçe Etimolojik Sözlük](https://github.com/uBlockOrigin/uAssets/assets/101707608/f87f25db-f2d8-4655-9e01-fa27afb3208c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 346497
 cosmetic: 255903
 scriptlet: 50185
 html: 2064
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 67420-0, 1m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 100754-72, 1h.47m
  https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt: 856-11, 1m
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 376-0, 1h.47m
  adguard-generic: 81616-4918, 1h.47m
  adguard-mobile: 9380-849, 1h.46m
  adguard-spyware-url: 1512-230, 1h.46m
  adguard-spyware: 83499-4989, 1h.46m
  block-lan: 66-0, 1m
  curben-phishing: 673-0, 1h.47m
  adguard-cookies: 29600-44, 1h.46m
  fanboy-cookiemonster: 50999-3894, 1m
  [13 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38210-205, 1h.47m Δ
  ublock-badware: 8548-422, 1h.47m Δ
  ublock-privacy: 908-64, 1h.47m Δ
  ublock-unbreak: 2332-3, 1h.47m Δ
  ublock-quick-fixes: 196-6, 1h.47m Δ
  easylist: 87464-41978, 1h.47m Δ
  easyprivacy: 50913-32887, 1h.47m Δ
  urlhaus-1: 12410-3, 1h.47m
  plowe-0: 3729-2030, 1m
  GRC-0: 1079-16, 1h.47m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user- https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1
supportStats:
 allReadyAfter: 61982 ms
 maxAssetCacheWait: 9278 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 1
  sentry.io: 3
 extended:
  ##p:empty:not([class])
  ##p:-moz-only-whitespace
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
nisanyansozluk.com##+js(set-local-storage-item, newYeradlariWebsiteHidden, true)
```

@ryanbr

**Comment by DimitrisKalaboukas** [comment]
@stephenhawk8054 This filter is already included in AdGuard Annoyances - Popup Overlays list, but it doesn't work on my side. (?)

**Comment by stephenhawk8054** [comment]
Hmm... I don't see any popups after adding that filter

**Comment by stephenhawk8054** [comment]
As said, I can't reproduce the issue any more with the above filter so maybe someone else can investigate it. You can test in a new Firefox profile to see how it goes.

**Comment by stephenhawk8054** [comment]
Or do you mean the popup at the bottom right?

**Comment by DimitrisKalaboukas** [comment]
Yes, that in the above screenshot.

**Comment by stephenhawk8054** [comment]
Yeah in that case, please report to EL repo: https://github.com/easylist/easylist/issues

```adb
nisanyansozluk.com##.toast
```

**Comment by DimitrisKalaboukas** [comment]
@Alex-302 ?

**Comment by Alex-302** [comment]
@DimitrisKalaboukas Added
