### ISSUE TITLE
douyin.com: ads

### ISSUE THREAD

**Issue by senlyxinn** [uBlockOrigin/uAssets#23720]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.douyin.com/?recommend=1`

### Category

ads

### Description

视频广告拦截不了

(EN: Video ads not blocked)

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 149199
 cosmetic: 57235
 scriptlet: 20850
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-3, never
  CHN-0: 25742-146, 9m
  easylist: 86827-481, 9m Δ
  easyprivacy: 50856-814, 9m Δ
  plowe-0: 3729-0, 9m
  ublock-badware: 8505-0, 9m Δ
  ublock-filters: 37812-418, 9m Δ
  ublock-privacy: 881-0, 9m Δ
  ublock-quick-fixes: 261-0, 9m Δ
  ublock-unbreak: 2268-0, 9m Δ
  urlhaus-1: 12410-0, 9m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 375 ms (selfie)
 maxAssetCacheWait: 30 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 220
 network:
  oceanengine.com: 1
  zijieapi.com: 219
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how the ads look like?

**Comment by senlyxinn** [comment]
这样式的。




duohuahua738
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;;
发送时间:&nbsp;2024年5月16日(星期四) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题：回复：[uBlockOrigin/uAssets] douyin.com：广告（问题 #23720）





 
你能截取广告的样子吗？
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you reproduce the issue?

**Comment by cjx82630** [comment]
@senlyxinn Can you provide a screenshot? 请提供截图.

**Comment by senlyxinn** [comment]
> @senlyxinn Can you provide a screenshot? 请提供截图.

![Uploading FireShot_ Webpage Screenshots + Annotations 1.12.18 installed! 和另外 5 个页面 - 个人 - Microsoft​ Edge 2024_5_17 16_54_00.png…]()

**Comment by stephenhawk8054** [comment]
@cjx82630 Looks like the ads is on the right side, can you reproduce?

**Comment by senlyxinn** [comment]
> @cjx82630 Looks like the ads is on the right side, can you reproduce?看起来广告在右侧，可以复制吗？

可以复现，还有类似的广告

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/afb892323190e46528b4866f264be35f35d6bf6b
30分钟后更新 
Fixed.Please manually update in 30 minutes.
