### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by techyyash** [uBlockOrigin/uAssets#23730]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://twitter.com/`

### Category

breakage

### Description

As you can see from the screenshot,it shows these grey lines instead of the content all the time when the extension is enabled. It has started happening recently.

### Other extensions used

No other extensions used.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.postimg.cc/bNFbXybC/Screenshot-20240516-221739-1.png
![Screenshot_20240516-221739(1)](https://github.com/uBlockOrigin/uAssets/assets/57702209/79750c9f-a7b0-4759-bb37-ed1ffd6897b3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 125
filterset (summary):
 network: 136562
 cosmetic: 54935
 scriptlet: 19540
 html: 1805
listset (total-discarded, last-updated):
 default:
  user-filters: 16-0, never
  ublock-filters: 38549-111, 1h.26m Δ
  ublock-badware: 8567-0, 1h.26m Δ
  ublock-privacy: 909-2, 1h.26m Δ
  ublock-unbreak: 2335-2, 1h.26m Δ
  ublock-quick-fixes: 203-10, 1h.26m Δ
  adguard-mobile: 9377-70, 3d.3h.11m
  easylist: 87466-224, 1h.26m Δ
  easyprivacy: 50912-75, 1h.26m Δ
  urlhaus-1: 12660-3, 2h.59m
  plowe-0: 3729-1234, 1d.2h.1m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 298 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  twitter.com: 4
  ads-twitter.com: 1
  google-analytics.com: 1
 extended:
  ##a.r-1loqt21.r-1ny4l3l.r-1777fci.r-wgabs5.r-rull8r.r-oucylx.r-1…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
```
</details>

**Comment by stephenhawk8054** [comment]
Remove your custom filters and test again.

**Comment by techyyash** [comment]
Thanks! It worked.

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

**Comment by techyyash** [comment]
I am sorry, wasn't knowing about the custom filters. I have unchecked that option now.
