### ISSUE TITLE
thestreameast.to: breakage

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#23731]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thestreameast.to/nhl/edmonton-oilers-vancouver-canucks-7-live-stream/`

### Category

breakage

### Description

None of the streams play with uBlock Origin on Firefox. Works fine without it on Chrome too.

### Other extensions used

Decentraleyes
Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 228057
 cosmetic: 252193
 scriptlet: 51047
 html: 2064
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81411-3987, now
  adguard-mobile: 9383-56, now
  adguard-spyware-url: 1512-120, now
  adguard-spyware: 83502-1369, now
  block-lan: 66-0, now
  curben-phishing: 450-1, now
  adguard-social: 22944-53, now
  adguard-cookies: 29625-45, now
  ublock-cookies-adguard: 1148-13, now
  adguard-popup-overlays: 27396-1019, now
  adguard-mobile-app-banners: 5207-23, now
  adguard-other-annoyances: 14250-415, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38218-110, 36m Δ
  ublock-badware: 8573-0, 36m Δ
  ublock-privacy: 908-2, 36m Δ
  ublock-unbreak: 2332-2, 36m Δ
  ublock-quick-fixes: 195-5, 36m Δ
  easylist: 87464-1943, 36m Δ
  easyprivacy: 50918-31579, 36m Δ
  urlhaus-1: 12505-2, now
  plowe-0: 3729-1646, 36m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 227 ms (selfie)
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  amazon-adsystem.com: 3
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  scorecardresearch.com: 1
  serving-sys.com: 1
  ttvnw.net: 1
  uwaxoyfklhm.com: 1
 extended:
  ##+js(addEventListener-defuser, /^/, 0x)
  ##+js(no-setInterval-if, visibility, 1000)
  ##+js(nowebrtc)
  ##+js(no-setTimeout-if, sadbl)
  ##+js(abort-on-property-read, aclib)
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
