### ISSUE TITLE
indeed.com: breakage

### ISSUE THREAD

**Issue by WormChickenWizard** [uBlockOrigin/uAssets#23747]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.indeed.com/viewjob?jk=1272fc5e08d7c62f
```

### Description

When loading a job listing via any site that matches `https://www.indeed.com/viewjob?jk=some_job_id`, the listing appears for a brief second then disappears. The issue does not seem to present in incognito mode. I'm using ungoogled chromium version 124.0.6367.207 on Win 10 version 22H2. I was not able to replicate the issue using regular chrome.

### Other extensions used

None. Made sure they were all disabled. Issue still presented on ungoogled chromium version 124.0.6367.207 with only the uBlock Origin enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_0Y0o9FrKRb](https://github.com/uBlockOrigin/uAssets/assets/39471591/bfe17893-af38-4951-8cf7-4c4f6b6ba21f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 134921
 cosmetic: 46979
 scriptlet: 20921
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 87453-547, now
  easyprivacy: 50935-809, now
  plowe-0: 3726-0, now
  ublock-badware: 8611-0, now
  ublock-filters: 38245-280, now
  ublock-privacy: 913-0, now
  ublock-quick-fixes: 145-0, now
  ublock-unbreak: 2275-0, now
  urlhaus-1: 12300-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 264 ms (selfie)
 maxAssetCacheWait: 83 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  indeed.com: 12
  datadoghq-browser-agent.com: 1
  ispot.tv: 1
```
</details>

**Comment by WormChickenWizard** [comment]
@stephenhawk8054 I made sure to update the unbreak filter and that it had the change you made. However the issue still seems to present itself.

**Comment by stephenhawk8054** [comment]
@WormChickenWizard Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by WormChickenWizard** [comment]
Hmm. Not sure what changed but the site seems to not disappear as it did when I tested it 3 hours ago. I opened the extension, searched for unbreak, and noticed the changes you made were present. 😕

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 135091
 cosmetic: 46989
 scriptlet: 20925
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 87467-547, now
  easyprivacy: 50935-790, now
  plowe-0: 3726-0, now
  ublock-badware: 8616-0, now
  ublock-filters: 38245-280, now
  ublock-privacy: 913-0, now
  ublock-quick-fixes: 149-0, now
  ublock-unbreak: 2276-18, now
  urlhaus-1: 12460-2, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 110 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  indeed.com: 25
  datadoghq-browser-agent.com: 1
  ispot.tv: 1
 extended:
  ##+js(set-constant, DD_RUM.addAction, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
So can you reproduce the issue any more?

**Comment by WormChickenWizard** [comment]
I can not. No.

**Comment by dstepp-indeed** [comment]
Hi @stephenhawk8054 , any chance I can convince you to revert this change or modify it?  This change breaks DataDog across all of *.indeed.com.  In particular my team maintains employers.indeed.com and it busts all of our analytics.  I get that uBlock's raison d'etre is to block things.  But nuking this DD_RUM.addAction does not seem to be applied more broadly by uBlock, only on indeed.com for some reason; why is that?
