### ISSUE TITLE
Commit 81891151877cc954d567c59e5641c8c4e81c3b37 is too broad, breaks almost all legit German banks

### ISSUE THREAD

**Issue by henryk** [uBlockOrigin/uAssets#23742]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.sparkasse-hannover.de/
https://www.sparkasse-bremen.de/
```

### Description

Commit 81891151877cc954d567c59e5641c8c4e81c3b37 introduces a blanket filter for all domains starting with `sparkasse-` with no clear rationale.
For reference: These are local German banks, and they almost all have their own domain names like "sparkasse-cityname.de". The two examples I linked above are real legit websites.

(And, yes, this invites registering "sparkasse-boguscityname.de" for phishing, but just blocking *all* sites doesn't appear to be a good idea.)

What I guess happened is that someone extrapolated from the two sites above that.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by leonlag** [comment]
Just had this issue on sparkasse-koelnbonn.de. Admittedly, this banks policy of having completely different domains for all the local franchises is quite confusing. They should have just had a subdomain on sparkasse.de per franchise.

**Comment by sleiss** [comment]
My bank https://www.sparkasse-freising-moosburg.de/ is still blocked (not by this filter but because it is explicitly listed).

Should I open another issue for this or how do I proceed here?

**Comment by stephenhawk8054** [comment]
@sleiss Wait about 10 minutes, then update the quick fix list by clicking on this link:

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=240520
