### ISSUE TITLE
AMP Stories on washingtonpost.com are broken

### ISSUE THREAD

**Issue by rohunbansal** [uBlockOrigin/uAssets#2374]
### URL(s) where the issue occurs

Example: `https://www.washingtonpost.com/graphics/2018/national/amp-stories/before-and-after-kilaueas-wrath-on-hawaiis-big-island/`

### Describe the issue

[AMP Stories](https://www.ampproject.org/stories/) on `washingtonpost.com` are broken for the Washington Post with a blank screen.

### Screenshot(s)

<img width="1175" alt="washingtonpost" src="https://user-images.githubusercontent.com/792417/40563630-76456476-6033-11e8-9c42-b83f4215d6b4.png">

### Versions

- Browser/version: Chrome 66.0
- uBlock Origin version: 1.16.6

### Settings

- Default settings, recently updated blocklists

### Notes

This looks like it's due to [this rule](https://github.com/uBlockOrigin/uAssets/blob/e84f488ec4d9295b53fdbc5aa37f06ea2eddfc18/filters/filters.txt#L483) in `filters/filters.txt` adding `height: initial !important;` to `html`. This page is trying to take up the full height through `height: 100%!important;` but is being set to 0px instead. Disabling this rule or cosmetic filtering makes the page work correctly.

**Comment by zaphodbeebblebrox** [comment]
`https://www.washingtonpost.com/world/here-are-16-of-the-weeks-best-photos/2018/05/25/2a56c8e4-5bb9-11e8-8836-a4a123c359ab_gallery.html`.

The above link breaks between the 8th and 9th slides.

**Comment by ghajini** [comment]
@okiehsch @mapx- 
autoplay after 7slide stopped working saying `wait 1 second to continue` next slides are grayed out

**Comment by mapx-** [comment]
I cannot reproduce either
