### ISSUE TITLE
bbs.io-tech.fi: ads

### ISSUE THREAD

**Issue by Jurtaani** [uBlockOrigin/uAssets#23740]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bbs.io-tech.fi/watched/threads`

### Category

ads

### Description

the page occasionally opens and ad either on the top or the bottom of the page.
it then results the content jumping around when the ad appears making it annoying to use that website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![iotech](https://github.com/uBlockOrigin/uAssets/assets/96973990/d3a8b950-ab0f-4c8a-9dab-2f091116e46a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 243815
 cosmetic: 220232
 scriptlet: 51562
 html: 2105
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81638-3987, now
  adguard-mobile: 9383-56, now
  adguard-spyware-url: 1512-120, now
  block-lan: 66-0, now
  curben-phishing: 536-2, 51m
  fanboy-cookiemonster: 51018-185, now
  ublock-annoyances: 5831-105, now
  dpollock-0: 11680-439, now
  EST-0: 465-72, 50m
  NOR-0: 3871-166, 1h.51m
  RUS-0: 39509-323, now
  SWE-1: 4593-50, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 6-1, never
  ublock-filters: 38218-110, now
  ublock-badware: 8579-0, now
  ublock-privacy: 909-2, now
  ublock-unbreak: 2331-2, now
  ublock-quick-fixes: 195-5, 1h.51m
  easylist: 87473-1953, now
  easyprivacy: 50918-171, now
  urlhaus-1: 12560-2, 51m
  plowe-0: 3726-1587, now
  FIN-0: 2281-6, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 680 ms (selfie)
 maxAssetCacheWait: 333 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  adform.net: 1
  googletagmanager.com: 1
  hinta.fi: 2
 extended:
  ##.p-footer-rssLink
  ##.u-scrollButtons
  ##[data-revive-zoneid] > iframe
```
</details>

**Comment by gorhill** [comment]
This seems to work:

    bbs.io-tech.fi##[data-revive-zoneid]

Should be fixed in regional list. cc @peace2000

**Comment by peace2000** [comment]
Fixed https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/c75d02b8047d6cba3dd9ee96bfb5a6c2dd543faa
