### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by UnluckyMatt** [uBlockOrigin/uAssets#23745]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv`

### Category

ads

### Description

the ads appears even with the uBlock active

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 123784
 cosmetic: 0
 scriptlet: 21060
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 default:
  user-filters: 0-0, never
  ublock-filters: 37621-10861, now
  ublock-badware: 8576-680, now
  ublock-privacy: 913-13, now
  ublock-unbreak: 2275-334, now
  ublock-quick-fixes: 143-47, now
  easylist: 87453-35643, now
  easyprivacy: 50925-811, now
  plowe-0: 3726-0, now
  spa-1: 5638-3885, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 autoUpdate: false
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 461 ms (selfie)
 maxAssetCacheWait: 248 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  amazon-adsystem.com: 2
  d2v02itv0y9u9t.cloudfront.net: 1
  ttvnw.net: 1
 extended:
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by gorhill** [comment]
> - [x] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [**Twitch**](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or https://github.com/uBlockOrigin/uAssets/discussions/17361 report. These sites MUST be reported by clicking their respective links.
