### ISSUE TITLE
3sat.de: breakage

### ISSUE THREAD

**Issue by zedd-0** [uBlockOrigin/uAssets#23746]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.3sat.de/wissen/nano/240517-sendung-ganz-legal-lsd-aus-dem-automaten-nano-100.html`

### Category

breakage

### Description

videoplayer is blocked

### Other extensions used

no script was disabled.
player works after disabling ublock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 192772
 cosmetic: 170667
 scriptlet: 38881
 html: 1852
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81639-3992, now
  adguard-mobile: 9385-56, now
  fanboy-social: 15997-11, now
  CHN-0: 25811-227, now
  IRN-0: 3043-26, now
  ISR-0: 1869-10, now
  RUS-0: 39511-297, 55m Δ
  adguard-social: 22949-789, now
  curben-phishing: 536-2, now
 default:
  user-filters: 340-2, never
  ublock-filters: 38293-113, 1h.55m Δ
  ublock-badware: 8578-0, 1h.55m Δ
  ublock-privacy: 909-2, 1h.55m Δ
  ublock-unbreak: 2331-2, 1h.55m Δ
  easylist: 87448-1952, 1h.55m Δ
  easyprivacy: 50926-169, 1h.55m Δ
  plowe-0: 3726-1241, now
  DEU-0: 7460-54, now
  urlhaus-1: 12560-2, now
  ublock-quick-fixes: 148-6, 1h.55m Δ
filterset (user): [array of 340 redacted]
trustedset:
 added: [array of 23 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  xiti.com: 1
  zdf.de: 2
 extended:
  ##a[href^="http://www.facebook.com/share.php"]
  ##a[href^="whatsapp://send"]
  ##a[href*="//www.facebook.com/share.php"]
  ##a[href^="https://twitter.com/share"]
```
</details>

**Comment by gorhill** [comment]
Video plays fine with default settings/lists. Please investigate more on your side to find out what is causing your issue.

**Comment by zedd-0** [comment]
i found the issue.
it was the "RU AdList" filter list.
disabling this is bad because of the current geopolitical situation.

**Comment by gorhill** [comment]
cc @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/33e4c0b47f322f14bc9bd60a986a1a30731656ff
