### ISSUE TITLE
paster.so: nuisance

### ISSUE THREAD

**Issue by Saulildo** [uBlockOrigin/uAssets#23754]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://paster.so/eWXpr`

### Category

nuisance

### Description

a completely user-friendly website that necessitates a 5-minute wait for the pasted content to display

### Other extensions used

TamperMonkey, Decentraleyes, and Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240518-100015](https://github.com/uBlockOrigin/uAssets/assets/104403007/d43813c0-aebd-4146-8311-045243e74d2b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 124
filterset (summary):
 network: 229568
 cosmetic: 256502
 scriptlet: 51546
 html: 2065
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 0-0, 13m
  adguard-generic: 81538-3998, 12m
  adguard-spyware-url: 1513-120, 12m
  adguard-spyware: 83509-1372, 12m
  block-lan: 66-0, 12m
  curben-phishing: 530-2, 12m
  adguard-social: 22949-53, 12m
  adguard-cookies: 29682-45, 12m
  ublock-cookies-adguard: 1190-15, 12m
  adguard-popup-overlays: 27410-1019, 12m
  adguard-mobile-app-banners: 5212-27, 12m
  adguard-other-annoyances: 14249-413, 12m
  [11 lists not shown]: [too many]
 default:
  user-filters: 15-0, never
  ublock-filters: 38630-114, 29m Δ
  ublock-badware: 8607-0, 29m Δ
  ublock-privacy: 910-2, 29m Δ
  ublock-unbreak: 2336-2, 29m Δ
  ublock-quick-fixes: 158-11, 29m Δ
  adguard-mobile: 9385-98, 12m
  easylist: 87475-1944, 29m Δ
  easyprivacy: 50935-31579, 29m Δ
  urlhaus-1: 12460-2, 12m
  plowe-0: 3726-1644, 13m
  spa-1: 5638-102, 13m
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1948 ms (selfie)
 maxAssetCacheWait: 905 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 1
  getclicky.com: 2
  hotjar.com: 1
  posthog.com: 2
```
</details>

**Comment by gorhill** [comment]
I don't think this can be patched by uBO.

**Comment by stephenhawk8054** [comment]
It's paywall so I don't think we can address it in uAssets.
