### ISSUE TITLE
delugerpg.com: detection

### ISSUE THREAD

**Issue by Dynamixus** [uBlockOrigin/uAssets#23757]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.delugerpg.com/`

### Category

detection

### Description

Game has a feature where you can skip some screens so fights are continuous. This is disabled when the site detects the use of Adblock, and they say it too on their FAQs.

![image](https://github.com/uBlockOrigin/uAssets/assets/137287047/12953a11-dc68-4f13-bf29-53fabb52326b)

I realize it may not be much of a frequented website, but it would still help a ton to have this. It's riddled with ads everywhere.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 135431
 cosmetic: 48615
 scriptlet: 24855
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5886-13, now
 default:
  user-filters: 0-0, never
  easylist: 87489-549, now
  easyprivacy: 50935-806, now
  plowe-0: 3726-0, now
  ublock-badware: 8616-0, now
  ublock-filters: 38245-281, now
  ublock-privacy: 913-2, now
  ublock-quick-fixes: 149-0, now
  ublock-unbreak: 2276-19, now
  urlhaus-1: 12490-2, 33m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 325 ms (selfie)
 maxAssetCacheWait: 121 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  optad360.io: 2
 extended:
  ###menuad
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by D4niloMR** [comment]
Test:

`delugerpg.com##+js(no-fetch-if, googlesyndication)`

**Comment by stephenhawk8054** [comment]
What are the steps to reproduce the issue? I accessed `https://www.delugerpg.com/intro/fresh` with a new account and the site looks like this

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/f88b6b12-7155-4c9c-b066-63e0f1f9a6c9)

We don't use this website so we don't know what to do with it.
