### ISSUE TITLE
rezka.ag: ads

### ISSUE THREAD

**Issue by xvdm** [uBlockOrigin/uAssets#23752]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rezka.ag/series/thriller/1743-dekster-2006.html`

### Category

ads

### Description

A lot of ads on the page.
Also 15 second ads before playing the movie.
This issue appeared 1-2 days ago, before that everything was ok

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_gMFbGKtTjm](https://github.com/uBlockOrigin/uAssets/assets/81222789/7aabb076-bde9-4539-ab9e-0d48be9ee86c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 212197
 cosmetic: 147184
 scriptlet: 42832
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81641-6813, 15h.19m
  adguard-mobile: 9384-169, 15h.19m
  adguard-mobile-app-banners: 5212-1113, 15h.17m
  adguard-other-annoyances: 14244-327, 15h.17m
  adguard-popup-overlays: 27408-856, 15h.17m
  adguard-spyware: 83507-31969, 15h.18m
  adguard-spyware-url: 1512-119, 15h.18m
  adguard-widgets: 2506-43, 15h.17m
  block-lan: 66-0, 15h.17m
  curben-phishing: 536-0, 15h.18m
  easylist-annoyances: 4602-108, 15h.17m
  easylist-chat: 196-0, 15h.17m
  [2 lists not shown]: [too many]
 default:
  user-filters: 41-7, never
  easylist: 87473-472, 1h.59m Δ
  easyprivacy: 50935-790, 1h.59m Δ
  plowe-0: 3726-0, 15h.28m
  ublock-badware: 8611-3, 1h.59m Δ
  ublock-filters: 38243-703, 1h.59m Δ
  ublock-privacy: 913-0, 1h.59m Δ
  ublock-quick-fixes: 145-0, 1h.59m Δ
  ublock-unbreak: 2275-33, 1h.59m Δ
  urlhaus-1: 12560-2, 15h.28m
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 466 ms (selfie)
 maxAssetCacheWait: 181 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  adpod.in: 1
  bestssrv.com: 5
  clarity.ms: 1
  doubleclick.net: 7
  franecki.net: 2
  jsdelivr.net: 1
  pjstat.com: 1
  serv01001.xyz: 3
 extended:
  ##+js(set-constant, window.abc, false)
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `RU AdList` and test again
