### ISSUE TITLE
aniworld.to: popups

### ISSUE THREAD

**Issue by Cykamon** [uBlockOrigin/uAssets#23755]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniworld.to/anime/stream/dragonball-super/staffel-5/episode-33`

### Category

popups

### Description

When i'm clicking a video on voe for example a pop up appears and dissappears after 2 seconds.
When i'm in full screen and i'm pausing the video the full screen gets closed and the pop up (which is only a blank white page) gets open and closed again

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 137408
 cosmetic: 51952
 scriptlet: 19492
 html: 1804
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38297-113, 10m Δ
  ublock-badware: 8613-0, 10m Δ
  ublock-privacy: 909-2, 10m Δ
  ublock-unbreak: 2333-2, 10m Δ
  ublock-quick-fixes: 150-6, 10m Δ
  easylist: 87475-159, 10m Δ
  easyprivacy: 50935-65, 10m Δ
  urlhaus-1: 12460-2, now
  plowe-0: 3726-1159, now
  DEU-0: 7460-37, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1903 ms (selfie)
 maxAssetCacheWait: 1188 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  ads-twitter.com: 2
  hazelmarks.com: 2
  imasdk.googleapis.com: 2
  tomorroweducated.com: 5
  twitter.com: 1
  yandex.ru: 1
 extended:
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
```
</details>

**Comment by Cykamon** [comment]
Why was it closed?

**Comment by JobcenterTycoon** [comment]
Its closed with a commit https://github.com/uBlockOrigin/uAssets/commit/0220f9c5669fdd1ce55eff5c8a0bf7fe7a38ef58 the update will be avaiable as a auto update in a few hours.

**Comment by Cykamon** [comment]
Oh that was fast. Thank you have nice day.
