### ISSUE TITLE
techguyforu.com: nuisance

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#23758]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://techguyforu.com/m1/`

### Category

nuisance

### Description

Pop-ups and ads on the webpage

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/162524406/325c79fe-8d73-48fa-9646-9d8d1a7aa560)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 228408
 cosmetic: 252451
 scriptlet: 51134
 html: 2064
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81639-3992, now
  adguard-mobile: 9385-56, now
  adguard-spyware-url: 1513-120, now
  adguard-spyware: 83509-1370, now
  block-lan: 66-0, now
  curben-phishing: 587-0, now
  adguard-social: 22949-53, now
  adguard-cookies: 29683-45, now
  ublock-cookies-adguard: 1152-13, now
  adguard-popup-overlays: 27425-1002, now
  adguard-mobile-app-banners: 5214-23, now
  adguard-other-annoyances: 14249-413, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38299-113, 1h.29m Δ
  ublock-badware: 8618-0, 1h.29m Δ
  ublock-privacy: 909-2, 1h.29m Δ
  ublock-unbreak: 2333-2, 1h.29m Δ
  ublock-quick-fixes: 154-6, 1h.29m Δ
  easylist: 87489-1952, 1h.29m Δ
  easyprivacy: 50935-31579, 1h.29m Δ
  urlhaus-1: 12490-2, now
  plowe-0: 3726-1644, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 219 ms (selfie)
 maxAssetCacheWait: 120 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 99
 network:
  techguyforu.com: 2
  a-mo.net: 10
  a-mx.com: 1
  creativecdn.com: 9
  criteo.com: 23
  criteo.net: 1
  doubleclick.net: 1
  histats.com: 1
  id5-sync.com: 1
  imasdk.googleapis.com: 1
  onetag-sys.com: 23
  quantumdex.io: 23
  vlitag.com: 1
  wp.com: 2
 extended:
  ##.cky-consent-container
  ##.cky-consent-bar
  ##.cky-overlay
  ##.share-fb
  ##.share-twitter
  ###twitterBtn
  ##.share-linkedin
  ##.share-pinterest
  ##.share-whatsapp
  ##.share-email
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link? If yes, can you provide original link?
