### ISSUE TITLE
luxuretv.com [NSFW]

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2375]
### URL(s) where the issue occurs

```
http://luxuretv.com/search/videos/lamb/
http://en.luxuretv.com/search/videos/lamb/
http://es.luxuretv.com/search/videos/lamb/
http://de.luxuretv.com/search/videos/lamb/
```

### Describe the issue

Missed banner ads annoying nudevista.

### Screenshot(s)

![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40569718-dbe823b6-607b-11e8-8bec-79d0793b1df4.jpg)

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default.

### Notes

None.

**Comment by C0nw0nk** [comment]
```
nudevista.com

<div id="nudevista">
```

**Comment by okiehsch** [comment]
Add 
`luxuretv.com###nudevista`

**Comment by C0nw0nk** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/16976

https://github.com/AdguardTeam/AdguardFilters/commit/ea46f76240e6360bad71dad073a6c34a8281935a

still displaying ads from nudevista on ublock origin, adguard has it blocked.

**Comment by ghajini** [comment]
**NSFW**

`https://www.nudevista.com/?q=april+knight&s=t&start=25`
In this site try to click `crazy pornstar april.......` that will open video to `txxx.com`
now return to previous site and click **next** ,tab is closed (`nudevista.com`)
logger shows this 
![image](https://user-images.githubusercontent.com/20338483/104687778-d9896a00-5725-11eb-8090-399c0e76d708.png)

**Comment by mapx-** [comment]
@gorhill

**Comment by gwarser** [comment]
"Manually triggered popunder" Chrome does not provide enough data to distinguish between user actions and script-triggered popups. uBO waits 10s for changes in popup(under) addresses to detect popups. Broad filter closes popunder for all addresses. Next time wait 10s before clicking on "Next" or use Firefox.

**Comment by gorhill** [comment]
I think rewriting the `popunder` filter as `*$popunder,3p,domain=txxx.*|~nudevista.com` could fix the issue.

**Comment by ghajini** [comment]
> I think rewriting the `popunder` filter as `*$popunder,3p,domain=txxx.*|~nudevista.com` could fix the issue.

If that's the filter,I will stick to gwarser suggestion, I don't want popunders(in future) at `nudevista.com`
