### ISSUE TITLE
[nsfw] uljs561.xyz: ads

### ISSUE THREAD

**Issue by 1542608903** [uBlockOrigin/uAssets#23759]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uljs561.xyz:5520/`

### Category

ads

### Description

无

### Other extensions used

🈚️

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium Mobile: 124
filterset (summary):
 network: 151305
 cosmetic: 65660
 scriptlet: 21204
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 38577-355, 13m Δ
  ublock-badware: 8610-0, 13m Δ
  ublock-privacy: 914-0, 13m Δ
  ublock-unbreak: 2279-0, 13m Δ
  ublock-quick-fixes: 157-0, 13m Δ
  adguard-mobile: 9381-103, now
  easylist: 87489-632, 13m Δ
  easyprivacy: 50935-816, 13m Δ
  urlhaus-1: 12490-1, now
  plowe-0: 3726-0, now
  CHN-0: 25831-164, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 646 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by ItsProfessional** [comment]
I don't see an ad on my side, can you provide a screenshot?
