### ISSUE TITLE
mail.yandex.ru: ads

### ISSUE THREAD

**Issue by Otkritka** [uBlockOrigin/uAssets#23761]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mail.yandex.ru/`

### Category

ads

### Description

Advertising in the mail

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Входящие — Яндекс Почта](https://github.com/uBlockOrigin/uAssets/assets/55092038/b607ee20-0480-4965-847b-9dbc80510451)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 109
filterset (summary):
 network: 152487
 cosmetic: 67423
 scriptlet: 22341
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  RUS-0: 39479-96, 9m
  easylist: 87346-568, 9m
  easyprivacy: 50935-809, 9m
  plowe-0: 3726-0, 9m
  ublock-badware: 8621-0, 9m
  ublock-filters: 38246-303, 9m
  ublock-privacy: 913-0, 9m
  ublock-quick-fixes: 149-0, 9m
  ublock-unbreak: 2277-0, 9m
  urlhaus-1: 12490-1, 1h.39m
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9649 ms (selfie)
 maxAssetCacheWait: 1723 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 40
 network:
  yandex.ru: 38
  yandex.net: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
See also: 
https://github.com/uBlockOrigin/uAssets/issues/22348
https://github.com/uBlockOrigin/uAssets/issues/23065

**Comment by stephenhawk8054** [comment]
Please just continue in your old threads.
