### ISSUE TITLE
ebooklibery.com: detection

### ISSUE THREAD

**Issue by NabeelGhallawenji** [uBlockOrigin/uAssets#23762]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ebooklibery.com/`

### Category

detection

### Description

This Website is detecting Ublock Origin, even if is disabled

### Other extensions used

Authenticator: 2FA Client
Avast Online Security & Privacy
IDM Integration Module
NordVPN - the Fastest VPN proxy for privacy
PDF Mage
PocketTube: Youtube Subscription Manager
Simple Allow Copy
Carrot
Controls for Instagram Videos
NordPass® Password Manager & Digital Vault

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 135396
 cosmetic: 46992
 scriptlet: 20925
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38245-280, 1h.17m Δ
  ublock-badware: 8621-0, 1h.17m Δ
  ublock-privacy: 913-0, 1h.17m Δ
  ublock-unbreak: 2276-0, 1h.17m Δ
  ublock-quick-fixes: 149-0, 1h.17m Δ
  easylist: 87489-547, 1h.17m Δ
  easyprivacy: 50935-808, 1h.17m Δ
  urlhaus-1: 12745-1, now
  plowe-0: 3726-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1950 ms (selfie)
 maxAssetCacheWait: 239 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
> even if is disabled

Which means something else on your machine is triggering the anti-adblock, and it's not related to uBO any more.

**Comment by gorhill** [comment]
Follow the prerequisite steps carefully, they are key for you to solve your issue on your side.
