### ISSUE TITLE
quickmath.com: breakage

### ISSUE THREAD

**Issue by namtacs** [uBlockOrigin/uAssets#23760]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://quickmath.com/`

### Category

breakage

### Description

https://quickmath.com/js/r/web-vitals.js wrongfully blocked
breaking the solver

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 115
filterset (summary):
 network: 135115
 cosmetic: 46743
 scriptlet: 19495
 html: 1804
listset (total-discarded, last-updated):
 removed:
  RUS-0: null
 default:
  user-filters: 1-0, never
  ublock-filters: 38299-113, now
  ublock-badware: 8623-0, now
  ublock-privacy: 909-2, now
  ublock-unbreak: 2333-2, now
  ublock-quick-fixes: 154-6, now
  easylist: 87346-159, now
  easyprivacy: 50935-65, now
  urlhaus-1: 12490-2, now
  plowe-0: 3726-1159, now
filterset (user): [none]
trustedset:
 added: [array of 18 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 405 ms (selfie)
 maxAssetCacheWait: 100 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  quickmath.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
