### ISSUE TITLE
[NSFW] videoszoofiliahd.com Missed Download banner ads and POPUPS

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2376]
### URL(s) where the issue occurs

```
https://www.videoszoofiliahd.com/video/1016/morena-dando-a-buceta-pro-dog-de-presente-video-zoofilia-free
```

### Describe the issue

Missed banner ads under video saying "DOWNLOAD" that belong to `ero-advertising` `https://redirect.ero-advertising.com/speedclicks/in.php?pid=50478&spaceid=3521134&returnurl=`

Keeps trying to open a popup to the following url when click anywhere.
URL Popup tries to open :
```
gatasdobabado.com.br
```

### Screenshot(s)

![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40569978-1d588866-607e-11e8-847d-d49b870d5de4.jpg)

### Versions

- Browser/version: Firefox quantum latest
- uBlock Origin version: Latest

### Settings

Default.

### Notes

None.

**Comment by C0nw0nk** [comment]
Keeps setting _ppu cookies too for popups.

**Comment by okiehsch** [comment]
I do not get that popup, I will add 
`videoszoofiliahd.com##[href^="https://redirect.ero-advertising.com/"]`

You opened an issue which includes the same site yesterday, if you still have issues just continue that thread. https://github.com/uBlockOrigin/uAssets/issues/2364

**Comment by C0nw0nk** [comment]
Thanks for the info. Must be a script cached that they have removed looks like this one to me.

```
<script src="https://www.videoszoofiliahd.com/embed/pp2.js?ver=1.1"></script>
```

They removed it hence why the code it still there but it redirects to their home page now but the cached copy I had was their popup code.

**Comment by okiehsch** [comment]
OK, my bad I used Chrome/Chromium and that scripts popup is defused by 
`videoszoofiliahd.com##script:inject(addEventListener-defuser.js, mousedown, popunder)`
which I added yesterday.

`videoszoofiliahd.com##script:inject(addEventListener-defuser.js, /^(click|mousedown|)/, popunder)`
fixes the issue with Chrome and Firefox on my end.
I will add it later today.

**Comment by C0nw0nk** [comment]
@okiehsch @smed79 

More popups / popads bypassing again

![untitled](https://user-images.githubusercontent.com/12204587/42139782-b9d200ac-7d8c-11e8-94c6-41250de14ee3.png)

**Comment by dr-junqy** [comment]
@C0nw0nk If you want to help yourself https://www.wikihow.com/Help-Someone-End-a-Pornography-Addiction

**Comment by C0nw0nk** [comment]
@dr-junqy  I will keep reporting missed ads but nice try :)

Plenty of users reporting missed ads porn sites have the most missed and contain the worst kind of ads plenty of us to keep submitting them. 

Perhaps if it is your site hence why you created a github account just to reply to me for reporting this site you should fix certain legal aspects of it (bestiality).
