### ISSUE TITLE
eddiarchive.com: ads  space

### ISSUE THREAD

**Issue by Kdroidwin** [uBlockOrigin/uAssets#23775]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eddiarchive.com/`

### Category

ads

### Description

There are still advertising space.

### Other extensions used

Fastforward
Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 146943
 cosmetic: 136679
 scriptlet: 30747
 html: 0
listset (total-discarded, last-updated):
 added:
  curben-phishing: 554-0, now
  adguard-cookies: 29708-66, now
  ublock-cookies-adguard: 1191-0, now
  adguard-popup-overlays: 27445-214, now
  adguard-mobile-app-banners: 5226-8, now
  adguard-other-annoyances: 14264-82, now
  adguard-widgets: 2508-2, now
  ublock-annoyances: 5914-20, 1h.2m Δ
 default:
  user-filters: 336-12, never
  ublock-filters: 38740-676, 1h.2m Δ
  ublock-badware: 8676-0, 1h.2m Δ
  ublock-privacy: 925-0, 1h.2m Δ
  ublock-unbreak: 2281-0, 1h.2m Δ
  ublock-quick-fixes: 150-0, 1h.2m Δ
  adguard-mobile: 9386-99, now
  easylist: 87370-686, 1h.2m Δ
  easyprivacy: 50945-839, 1h.2m Δ
  urlhaus-1: 13250-0, now
  plowe-0: 3726-0, now
  JPN-1: 14713-81, now
filterset (user): [array of 334 redacted]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 20 redacted]
hostRuleset:
 added: [array of 25 redacted]
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4560 ms (selfie)
 maxAssetCacheWait: 539 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  a8.net: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
collapseBlocked: false
```

You are disabling `Hide placeholders of blocked elements` settings, turn it back on and test again

**Comment by Kdroidwin** [comment]
Thank you for helping.
But, it only appears for a moment.

**Comment by stephenhawk8054** [comment]
For the flashing

```adb
eddiarchive.com##img[src*="a8.net"]
```

cc @Yuki2718 For Adguard JP?

**Comment by Kdroidwin** [comment]
Thank you very much.

**Comment by Yuki2718** [comment]
Almost unnoticeble. Will add only because AG for iOS user will see the full placeholder.
