### ISSUE TITLE
ads seen on NDTVprofit

### ISSUE THREAD

**Issue by wolfdael** [uBlockOrigin/uAssets#23778]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.ndtvprofit.com/business/jpmorgan-s-erdoes-says-every-new-hire-will-get-training-for-ai
```

### Description

Ads appear with default filters and only ub0 as extension on Firefox Android.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://easyupload.io/ddqn72

Please view the video. Ads visible with default filters and ub0 as only extension.

</details>

### Configuration

<details>
<summary>Details</summary>

```
uBlock Origin: 1.57.2
Firefox Mobile: 128
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
filterset (user): [array of 1 redacted]
trustedset:
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: ?
 maxAssetCacheWait: ?
popupPanel:
 blocked: 13
 network:
  ndtvprofit.com: 1
  affinitymatrix.com: 1
  chartbeat.com: 2
  criteo.net: 1
  doubleclick.net: 3
  googletagmanager.com: 1
  moengage.com: 2
  scorecardresearch.com: 2
 extended:
  ##.responsive-ad
  ###display-ads
  ##.adunitContainer
  ##.adBox
  ##.ad-with-placeholder-m__place-holder-wrapper__--JIw


```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/23682
