### ISSUE TITLE
2ddl.io, ganool.im & ancensored.com

### ISSUE THREAD

**Issue by salam2009** [uBlockOrigin/uAssets#2377]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`2ddl.io`, `ganool.im` & `ancensored.com`.

### Describe the issue
Every time those sites are opened, the popups show up as soon as we click anywhere in the page.
2ddl & ganool change their domain from time to time. So, is it possible to keep their ads blocked from my side since it's hard for you to keep updated with their new links?
Thank you guys so much for the efforts!

### Screenshot(s)
No need.

### Versions
- Browser/version: FF 60.0.1
- uBlock Origin version: 1.16.6

### Settings
https://i.imgur.com/BMT45VK.jpg
https://i.imgur.com/nzkh3JX.jpg

### Notes
None.

**Comment by okiehsch** [comment]
Do 2ddl & ganool change their domain name or only their top level domain?

**Comment by salam2009** [comment]
@okiehsch 
2ddl sometimes change the main domain but they've been only changing their TLD in the recent months.
ganool only change their TLD.
Thanks for the quick update :)

**Comment by okiehsch** [comment]
Ok, changing their tld will not have any effect with the filter I added, so as long as they don't change their main domain, or use a different popup script, you should be fine.

**Comment by smed79** [comment]
> Do 2ddl & ganool only change their top level domain?
```
2ddl.download
2ddl.io
2ddl.la
2ddl.ooo
2ddl.org
2ddl.pro
best2ddl.net
ddl2.org
iiddl.com
iiddl.net
tddl.tv
twoddl.co
twoddl.tv
```

**Comment by salam2009** [comment]
@okiehsch Ganool ads are came back for some reason.

**Comment by salam2009** [comment]
@okiehsch 2ddl ads are came back & they changed their TLD to .ws now. Thanks for any update :)

**Comment by okiehsch** [comment]
I do not get any popups  at `http://2ddl.ws`. Could you be more specific?

**Comment by salam2009** [comment]
yea, I'm not getting any ads now for some reason (maybe temporarily) but 20 minutes ago it got me an ad like this one: ydeoxwomjpvxoz.com

**Comment by salam2009** [comment]
Does that mean it pop ups at different times?

**Comment by okiehsch** [comment]
popads uses random domains like `ydeoxwomjpvxoz.com` to trigger popups, if this domain is blocked by `EasyList` no popup occurs until popads uses a different domain.
`2ddl.*##script:inject(abort-on-property-write.js, _pop)` disables the `popads-script`, so there will be no random domains.

**Comment by salam2009** [comment]
@okiehsch ok, now it uses this popad for some reason: `sgmneqaebkzjug.com` (yesterday was `jgvjzbrnjmxoq.com`)
It pops up at random times though.

**Comment by okiehsch** [comment]
I can't reproduce.
Example link: `http://2ddl.ws`

Can you post a screenshot of your logger output?

**Comment by salam2009** [comment]
That's because popads aren't active right now, so I'm not getting it either.
What do you mean by logger output btw?

**Comment by okiehsch** [comment]
Open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger), then load `http://2ddl.ws` and post a screenshot of the ouput.

My output, I filtered all image requests by adding `!image`:
![image](https://user-images.githubusercontent.com/16838044/42484917-8a1252a8-83f5-11e8-8dd0-e0bce2acbc4a.png)

**Comment by salam2009** [comment]
Here you go:
![screenshot](https://user-images.githubusercontent.com/33797202/42485154-0bed08f0-83ff-11e8-8f1d-3e413da9c92a.JPG)

**Comment by okiehsch** [comment]
Ok, for some reason `2ddl.*##script:inject(abort-on-property-write.js, _pop)` has not been injected on your end.
Please update your `uBO-filter` list then post another screenshot this time filtered to only show the `dom` request.
Looks like this for me.
![image](https://user-images.githubusercontent.com/16838044/42485470-06dfc4ee-83f8-11e8-896e-72e34ed1cdd8.png)

You should see four `script:inject` entries.

**Comment by okiehsch** [comment]
I can also see that you are using kaspersky which injects it's own script into every webpage you visit, which could potentially lead to conflicts with `uBO`.

The issue you see on your end is fixed with a default setup and up to date filters.
The `c1.popads.net` requests in your screenshot are never fired because of the 
`2ddl.*##script:inject(abort-on-property-write.js, _pop)` filter as you can see if you look at my first screenshot.

**Comment by salam2009** [comment]
Ok, here's what I get after updating `uBO-filter`:

![screenshot](https://user-images.githubusercontent.com/33797202/42486133-4a8cedc4-8403-11e8-823c-79c02f30f256.JPG)

Is there one more step to do?

**Comment by okiehsch** [comment]
Do you still see the `c1/c2.popads.net` requests of your first screenshot?

**Comment by salam2009** [comment]
Nope :)

**Comment by okiehsch** [comment]
Then your issue is fixed.

**Comment by Alhaitham** [comment]
The fix breaks some functions of ancensored.com like real time search and adding celebs to favorites.

**Comment by okiehsch** [comment]
Thanks.
Real time search should work after you update your `uBO-filter` list.

**Comment by salam2009** [comment]
@okiehsch 
Even though ganol.ru is now ganol.si, the site has been showing popads for some reason.

**Comment by okiehsch** [comment]
Should be fixed if you update your `uBO-filters` list.

**Comment by salam2009** [comment]
I just did & you're fast & awesome as always :)

**Comment by salam2009** [comment]
@okiehsch 
2ddl is now `invictus.ws` & it's opening a blank page (which closes itself) when the user clicks on the page.

**Comment by salam2009** [comment]
`ganol.si` is now `ganool123.com` with popads.

**Comment by salam2009** [comment]
@mapx- 
`ganol.si` is now `ganool123.com` with popads.

**Comment by salam2009** [comment]
@okiehsch 
`invictus.ws` has returned to `twoddl.net` while using the annoying popads. Thanks for the update in advance :)

**Comment by salam2009** [comment]
@okiehsch, @mapx- 
`invictus.ws` has returned to `twoddl.net` while using the annoying popads. Thanks for the update in advance :)

**Comment by salam2009** [comment]
@mapx- @okiehsch
`2ddl.io` is now `onceddl.net` with popads.

**Comment by salam2009** [comment]
@mapx-
`onceddl.net` has become `onceddl.com` & the popads came back.
Thanks so much for your efforts!

**Comment by salam2009** [comment]
@mapx-
`onceddl.com` is now `onceddl.org` & the popads have returned.
I can't thank you enough for your continuous support! :)

**Comment by mapx-** [comment]
The current filter covers already any TLD
`onceddl.*,twoddl.*##+js(aopw, _pop)`

I cannot reproduce in FF / chrome / opera

@llacb47 do you get any popup ?

**Comment by llacb47** [comment]
Yes, unblocked zfgloaded popunder opens in new tab.

**Comment by okiehsch** [comment]
What browser? I can't reproduce and the  zfgloaded script is commented out in the source in my end.

**Comment by salam2009** [comment]
ok, it seems the new popup gone after you updated the filters. Thanks guys! 🙂

**Comment by salam2009** [comment]
@mapx- @okiehsch
`onceddl.com` is now `2ddl.ms` & the popads are back.
Thanks for the update in advance! 😊
