### ISSUE TITLE
aniwave.vc: popups

### ISSUE THREAD

**Issue by Spaceyy64** [uBlockOrigin/uAssets#23772]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniwave.vc/home`

### Category

popups

### Description

clicking on links that should redirect to other part of website sometimes opens another website, flixrave.com on a new tab 

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/99867759/d640ca71-d415-47d1-80f8-26795e9152da)
![image](https://github.com/uBlockOrigin/uAssets/assets/99867759/fb530b8e-a7b5-497b-a54b-c5b42db0aa08)
![image](https://github.com/uBlockOrigin/uAssets/assets/99867759/382b2a8e-5273-4b7b-96c5-074fd003c8a9)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 134942
 cosmetic: 46853
 scriptlet: 20977
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87351-552, 3m Δ
  easyprivacy: 50945-788, 3m Δ
  plowe-0: 3726-0, now
  ublock-badware: 8682-0, 3m Δ
  ublock-filters: 38310-284, 3m Δ
  ublock-privacy: 924-2, 3m Δ
  ublock-quick-fixes: 151-0, 3m Δ
  ublock-unbreak: 2278-18, 3m Δ
  urlhaus-1: 12200-1, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6968 ms (selfie)
 maxAssetCacheWait: 434 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  amung.us: 1
  bidgear.com: 3
  capaciousdrewreligion.com: 1
  exactsag.com: 1
  googletagmanager.com: 1
  proftrafficcounter.com: 1
  sharethis.com: 2
  swarthsfulk.com: 1
  taxismaned.top: 1
  unseenreport.com: 1
 hasUnprocessedRequest: true
 extended:
  ##div[style^="position: fixed; inset: 0px; z-index: 2147483647; …
  ##div[id][style^="position: fixed; inset: 0px; z-index: 21474836…
```
</details>

**Comment by gorhill** [comment]
> sometimes opens another website, flixrave.com on a new tab

I can reproduce, it opens `flixflare.to` on my side. Investigating.

**Comment by gorhill** [comment]
Using `aniwave.vc##+js(nowoif)` stops the popup tab, but need to click twice to navigate to the clicked link.
