### ISSUE TITLE
tanoshiijapanese.com: ads

### ISSUE THREAD

**Issue by Matthew-Powers** [uBlockOrigin/uAssets#23770]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tanoshiijapanese.com/`

### Category

ads

### Description

Advertisements are still appearing at the bottom of the page

### Other extensions used

7TV, BetterTTV, DeArrow, FrankerFaceZ, NoScript, Privacy Badger, Read Aloud: A Text to Speech Voice Reader, Reddit Enhancement Suite, Return YouTube Dislike, SponsorBlock for YouTube - Skip Sponserships, The Amelizer, TTV LOL PRO, User-Agent Switcher and Manager, YouTube High Definition

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tanoshiijapanese_advertisement](https://github.com/uBlockOrigin/uAssets/assets/97479191/638ae2e7-d52b-4b69-b4cc-a70276ebec26)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 134905
 cosmetic: 46733
 scriptlet: 19533
 html: 1804
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 38327-113, now
  ublock-badware: 8679-0, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2335-2, now
  easylist: 87347-164, now
  easyprivacy: 50945-65, now
  urlhaus-1: 12200-1, now
  plowe-0: 3726-1159, now
  ublock-quick-fixes: 156-4, now
filterset (user): [array of 22 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 215 ms (selfie)
 maxAssetCacheWait: 69 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
