### ISSUE TITLE
viu.com: breakage

### ISSUE THREAD

**Issue by chryxe** [uBlockOrigin/uAssets#23779]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.viu.com/ott/my/en/vod/1182010/2-Days-1-Night-S4-2021`

### Category

breakage

### Description

![Screenshot 2024-05-21 122520](https://github.com/uBlockOrigin/uAssets/assets/170391791/84eccb1f-2f38-4f60-8917-6a5504f5b560)
![Screenshot 2024-05-21 122554](https://github.com/uBlockOrigin/uAssets/assets/170391791/d565cad2-6420-4503-98ab-b77305b14e90)
when hovering on the screen, its supposed to be like the first picture, but when adblock is on, it doesn't show up, like second one. (I don't know what it's called) It happens on every video.

### Other extensions used

PrivacyGuard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136009
 cosmetic: 46855
 scriptlet: 20977
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87370-552, 3m Δ
  easyprivacy: 50945-2, 3m Δ
  plowe-0: 3726-786, now
  ublock-badware: 8682-0, 3m Δ
  ublock-filters: 38312-284, 3m Δ
  ublock-privacy: 924-2, 3m Δ
  ublock-quick-fixes: 150-0, 3m Δ
  ublock-unbreak: 2278-18, 3m Δ
  urlhaus-1: 13250-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2277 ms (selfie)
 maxAssetCacheWait: 180 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  bitmovin.com: 1
  d2r1yp2w7bby2u.cloudfront.net: 1
  doubleclick.net: 1
  google.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  sentry.io: 3
 extended:
  ##.ad_title
  ##+js(no-xhr-if, mobileanalytics)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by stephenhawk8054** [comment]
@Aydenwng Describe your issue in details. How does the breakage look like?

**Comment by Aydenwng** [comment]
@stephenhawk8054 It's the exact same as the screenshots showed by chryxe. It cannot Fullscreen, it does not have any subtitles which really effects the quality of life.

**Comment by Aydenwng** [comment]
@ghajini It is reproducible you just need a VPN to connect to Hong Kong or Singapore.

**Comment by stephenhawk8054** [comment]
`unable to reproduce` means we are unable to reproduce the issue ourselves. I'm using VPN to Singapore and this is how OP's link looks like to me:

https://github.com/uBlockOrigin/uAssets/assets/66517106/d97707eb-07db-4b55-b5c7-dbcd831cd39a

**Comment by mapx-** [comment]
hk ip,
test link: https://www.viu.com/ott/hk/en/vod/2339884/Lovely-Runner

I need 
`||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=viu.com,redirect-rule=google-ima.js`
