### ISSUE TITLE
thehouseofportable.com: nuisance / detection

### ISSUE THREAD

**Issue by Ofat1958** [uBlockOrigin/uAssets#23773]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thehouseofportable.com/download/?id=895&k=2`

### Category

nuisance

### Description

Websites shows anti-adblock message (`Please disable adblock!` in HTML: `div[id="htp"]`). There is also delay when links are generated and this filter fixes it: `thehouseofportable.com##+js(nano-stb, , *)`. Fixing a delay is more important for me.

### Other extensions used

Tampermonkey
Cookie-Editor

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 136390
 cosmetic: 54938
 scriptlet: 19751
 html: 1819
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 38366-113, 46m Δ
  ublock-badware: 8684-0, 46m Δ
  ublock-privacy: 920-2, 46m Δ
  ublock-unbreak: 2335-2, 46m Δ
  ublock-quick-fixes: 156-15, 46m Δ
  easylist: 87351-164, 46m Δ
  easyprivacy: 50945-65, 46m Δ
  urlhaus-1: 12200-1, 1h.46m
  plowe-0: 3726-1159, 1m
  POL-0: 8694-45, 1h.46m
  POL-2: 1283-48, 1m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 223 ms (selfie)
 maxAssetCacheWait: 105 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  thehouseofportable.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle
  ##a[href*="/aff.php?aff="]
  ##+js(adjust-setTimeout, , *)
```
</details>

**Comment by D4niloMR** [comment]
This site detects even with uBO disabled.
