### ISSUE TITLE
[nsfw] safesysdefender.xyz: ads

### ISSUE THREAD

**Issue by Pel0t** [uBlockOrigin/uAssets#23785]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://safesysdefender.xyz/avs/en/dt/avg-1.php?c=5vz1fbl2qz8iz1&k=34ccd1725ebe9176e0a036a3ea93cafe&country_code=US&carrier=Verizon&country_name=United%20States&region=Virginia&city=Falls%20Church&isp=MCI%20Communications%20Services,%20Inc.%20d/b/a%20Verizon%20Business&lang=en&os=Mac%20OS%20X&osv=10.15&browser=Chrome&browserv=124&brand=Desktop&model=Desktop&marketing_name=Desktop&tablet=4&rheight=768&rwidth=768&e=5`

### Category

ads

### Description

safesysdefender.xyz - this website hijacks my web browsing, it replaces the page I was browsing with fake Norton security popups

### Other extensions used

Malware Bytes 
uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1318" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/103967186/3314a520-98f6-4b01-a935-f640d8f8e12c">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136200
 cosmetic: 46854
 scriptlet: 20987
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38326-375, now
  ublock-badware: 8734-0, now
  ublock-privacy: 924-0, now
  ublock-unbreak: 2278-0, now
  ublock-quick-fixes: 151-0, now
  easylist: 87351-461, now
  easyprivacy: 50953-810, now
  urlhaus-1: 13395-0, now
  plowe-0: 3726-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1471 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by Yuki2718** [comment]
The url only returns 404 on my end.
