### ISSUE TITLE
dizikral.com: ads

### ISSUE THREAD

**Issue by sistemforum** [uBlockOrigin/uAssets#23784]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dizikral.com/filmler/olumlu-dunya-2-2023-izle`

### Category

ads

### Description

ads display on clicking play button.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/2803525/fa060142-1386-4dd7-8d2f-da041c2b121e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 229102
 cosmetic: 241620
 scriptlet: 54464
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79175-30467, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99118-70404, now
  adguard-generic: 81771-6901, now
  adguard-mobile: 9388-124, now
  adguard-spyware-url: 1515-119, now
  adguard-spyware: 80727-31581, now
  block-lan: 66-0, now
  curben-phishing: 565-0, now
  adguard-cookies: 29721-50, now
  ublock-cookies-adguard: 1153-0, now
  fanboy-cookiemonster: 51040-3932, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 1450-5, never
  ublock-filters: 38326-315, now
  ublock-badware: 8739-0, now
  ublock-privacy: 924-0, now
  ublock-unbreak: 2278-1, now
  ublock-quick-fixes: 151-0, now
  easylist: 87313-789, now
  easyprivacy: 50954-948, now
  urlhaus-1: 13395-0, now
  plowe-0: 3726-459, now
  TUR-0: 12387-29, 7m
filterset (user): [array of 595 redacted]
trustedset:
 added: [array of 11 redacted]
hostRuleset:
 added: [array of 1086 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 556 ms (selfie)
 maxAssetCacheWait: 261 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  dizikral.com: 4
  1.1.1.1: 1
  adskeeper.com: 1
  google-analytics.com: 5
  google.com: 1
  googletagmanager.com: 3
  jsdelivr.net: 1
  jwpcdn.com: 1
  trafficbass.com: 3
  trafficdok.com: 2
  waust.at: 1
 extended:
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(set-constant, puShown, true)
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by Yuki2718** [comment]
A scriptlet to simply run an exisiting function may be useful. Here to execute `playVideo()`.

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
dizikral.com##+js(set, activeItem, 1)
```

**Comment by Yuki2718** [comment]
It seems @AdamWr fixed this with trusted scriptlet in https://github.com/AdguardTeam/AdguardFilters/issues/179591 Not sure if the set-constant rule is insufficient.

**Comment by AdamWr** [comment]
`set-constant` should be fine, but with trusted scriptlet you don't have to click to load video player.
