### ISSUE TITLE
scoutnet.se: breakage

### ISSUE THREAD

**Issue by Yzzoxi** [uBlockOrigin/uAssets#23788]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://scoutnet.se/f/rebates`

### Category

breakage

### Description

uBlock Origin is blocking the opening of a pop-up site when the user has filled out a form.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 135008
 cosmetic: 46692
 scriptlet: 19553
 html: 1809
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38383-113, 29m Δ
  ublock-badware: 8746-0, 29m Δ
  ublock-privacy: 920-2, 29m Δ
  ublock-unbreak: 2335-2, 29m Δ
  ublock-quick-fixes: 157-15, 29m Δ
  easylist: 87313-164, 29m Δ
  easyprivacy: 50954-66, 29m Δ
  urlhaus-1: 12200-1, never
  plowe-0: 3726-1159, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1047 ms (selfie)
 maxAssetCacheWait: 128 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  adform.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@lassekongo83 Sorry, can you reproduce the issue?

**Comment by lassekongo83** [comment]
@Yzzoxi Requires an account, so I'm going to need an output of [the logger](https://github.com/gorhill/uBlock/wiki/The-logger). Once the logger is open, can you fill out the form as normal and then [export the logger output to markdown](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog) and post it here?

Alternatively can you see if there's any blocked domain in the logger once the popup is supposed to open? If there is, then try whitelisting that domain in `My Filters`: `@@||example.com^`

If that works, then report it back here.

**Comment by Yzzoxi** [comment]
<details><summary>Logger output</summary>

```
+1
||adform.net^$popup
--
www.sj.se
3,3
get
popup
http://track.adform.net/C/?bn=16596313;cpdir=https%3A%2F%2Fwww.sj.se%2Fsok-resa%2Fvalj-resa%2FN%2525C3%2525A4ssj%2525C3%2525B6%252520Central%2FSundsvall%252520Central%2F2024-06-14%3FrestrictionId%3D4bec9e36-8aad-4865-80c9-a1b74269f6a6%26passengers%3DADULT%26ages%3DNO_AGE%26utm_source%3Dscouterna%26utm_medium%3Dsjbiz%26utm_content%3Dwidget%26utm_campaign%3Dmicrosite
```
```
+0
www.sj.se
3,1
get
popup
https://www.sj.se/apps/sj/servlet/microsite?micrositeId=4bec9e36-8aad-4865-80c9-a1b74269f6a6&language=sv&departureLocation=N%C3%A4ssj%C3%B6%20Central&arrivalLocation=Sundsvall%20Central&outboundDate=2024-06-14&travellers=ADULT&travellerAges=NO_AGE
```
```
+0
www.sj.se
get
popup
about:blank
```
</details>

**Comment by Yzzoxi** [comment]
> @Yzzoxi Requires an account, so I'm going to need an output of [the logger](https://github.com/gorhill/uBlock/wiki/The-logger). Once the logger is open, can you fill out the form as normal and then [export the logger output to markdown](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog) and post it here?
> 
> Alternatively can you see if there's any blocked domain in the logger once the popup is supposed to open? If there is, then try whitelisting that domain in `My Filters`: `@@||example.com^`
> 
> If that works, then report it back here.

I might be doing something wrong but whitelisting doesn't solve the issue, turning off uBO obviously works though.

**Comment by lassekongo83** [comment]
Can you try this filter: `@@||adform.net^$popup,domain=scoutnet.se` and see if anything happens?

**Comment by Yzzoxi** [comment]
> Can you try this filter: `@@||adform.net^$popup,domain=scoutnet.se` and see if anything happens?

Still same breakage with that filter enabled.

**Comment by lassekongo83** [comment]
I assume you get a popup like this? https://github.com/gorhill/uBlock/wiki/Strict-blocking

If you do, does it work if you click proceed?

**Comment by Yzzoxi** [comment]
I do not get any popup at all, the popup site just closes.

**Comment by lassekongo83** [comment]
Can you try `||adform.net^$popup,badfilter` and then try again?

**Comment by Yzzoxi** [comment]
No popups but now it works perfectly instead, was I not supposed to have the "@@" in the previous filter?

**Comment by lassekongo83** [comment]
An error with my explaining. The whitelist `@@` didn't work because there was no domain `scoutnet.se` when it opened.

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
@@||adform.net^$popup,domain=sj.se
```
