### ISSUE TITLE
amedia.site: ads

### ISSUE THREAD

**Issue by Hohot** [uBlockOrigin/uAssets#23783]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://amedia.site/page/2/`

### Category

[pop-up]

### Description

The pop-up box at the bottom of the site, is not blocked in any way. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/5588297/64eb1ef8-a580-4f5d-a15a-e1f2b5af123e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 122
filterset (summary):
 network: 231945
 cosmetic: 272975
 scriptlet: 54317
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29721-69, now
  adguard-generic: 81767-7005, now
  adguard-mobile: 9388-108, now
  adguard-mobile-app-banners: 5227-1111, now
  adguard-other-annoyances: 14270-366, now
  adguard-popup-overlays: 27450-954, now
  adguard-social: 22960-1644, now
  adguard-spyware: 80727-31570, now
  adguard-widgets: 2508-39, now
  curben-phishing: 565-0, 18m
  easylist-annoyances: 4630-96, now
  easylist-chat: 196-0, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 12-2, never
  RUS-0: 39498-544, now
  easylist: 87324-618, now
  easyprivacy: 50953-926, now
  plowe-0: 3726-0, now
  ublock-badware: 8734-0, now
  ublock-filters: 38327-738, now
  ublock-privacy: 924-0, now
  ublock-quick-fixes: 151-0, now
  ublock-unbreak: 2278-2, now
  urlhaus-1: 13395-1, 18m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8850 ms (selfie)
 maxAssetCacheWait: 676 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  amedia.site: 4
  yadro.ru: 1
  yandex.net: 1
  yandex.ru: 18
  yastatic.net: 8
 extended:
  ##.mfp-hide
  ##div[id^="yandex_rtb"]
  ##img[src*="counter.yadro.ru"]
  ##.footer__soc
  ##+js(no-xhr-if, strm.yandex.ru/get/)
  ##+js(set-constant, Object.prototype.partnerId, {})
```
</details>

**Comment by dimisa-RUAdList** [comment]
Please indicate the exact browser version number.

**Comment by Hohot** [comment]
> Please indicate the exact browser version number.

24.4.2.956 (64-bit) yandex browser.

**Comment by dimisa-RUAdList** [comment]
The Yandex browser was created for the purpose of displaying ads, this is its main task. It prevents blockers from working on its own and partner domains, and this feature is constantly being improved. The [dev-version of uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) is the least affected by this effect. Install it instead of the usual uBlock Origin and use the [recommended settings file](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).
