### ISSUE TITLE
24h.com.vn: nuisance

### ISSUE THREAD

**Issue by error-reporting** [uBlockOrigin/uAssets#23794]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.24h.com.vn/cong-nghe-thong-tin/xoa-ngay-ung-dung-nay-tren-iphone-de-tranh-bi-theo-doi-c55a1567207.html`

### Category

nuisance

### Description

A 3rd party sponsored post
The post occasionally change when the main page is reloaded

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-05-22-12-57-22-15_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/166897813/6e1407bf-0e6f-498f-bbc7-e8400491d8a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 126
filterset (summary):
 network: 135972
 cosmetic: 47103
 scriptlet: 19564
 html: 1812
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  adguard-mobile: null
  VIE-1: null
 default:
  ublock-filters: 38821-114, 28m
  ublock-badware: 8772-0, 28m
  ublock-privacy: 921-2, 15m Δ
  ublock-unbreak: 2339-2, 28m
  ublock-quick-fixes: 157-15, 28m
  easylist: 87317-166, 29m
  easyprivacy: 50955-66, 29m
  urlhaus-1: 13120-1, 29m
  plowe-0: 3726-1159, 30m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 14 redacted]
hostRuleset:
 added: [array of 20 redacted]
userSettings: [none]
hiddenSettings:
 assetFetchTimeout: 60
 cnameIgnore1stParty: false
 cnameIgnoreRootDocument: false
supportStats:
 allReadyAfter: 1748 ms (selfie)
 maxAssetCacheWait: 1083 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  24h.com.vn: 2
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##.adZone
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
24h.com.vn##.bnr
24h.com.vn##[id^="ADS_"]
```

cc @hoang-rio Also there are ads placeholders on the page
