### ISSUE TITLE
app-scl.five9.com: breakage

### ISSUE THREAD

**Issue by Dannnnnnnnnnnny** [uBlockOrigin/uAssets#23799]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app-scl.five9.com/clients/agent/main.html?role=Agent`

### Category

breakage

### Description

When app is done loading, users are met with the following error message: 

"Unable to load the application. Please retry in a few minutes."

This seems to be a recent issue as it has not happened before

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/105239027/a56fe4c5-282e-48e7-812b-4c829b4b5ade)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 136057
 cosmetic: 46799
 scriptlet: 21003
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87328-43, now
  easyprivacy: 50959-822, now
  plowe-0: 3726-376, now
  ublock-badware: 8789-15, now
  ublock-filters: 38349-372, now
  ublock-privacy: 924-3, now
  ublock-quick-fixes: 152-0, now
  ublock-unbreak: 2281-12, now
  urlhaus-1: 13145-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13941 ms
 maxAssetCacheWait: 357 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  five9.net: 1
```
</details>

**Comment by D4niloMR** [comment]
On `https://app-scl.five9.com/clients/agent/main.html?role=Agent` I get the same error with uBO disabled.

**Comment by D4niloMR** [comment]
Oh sorry it's not exactly the same, but it seems a account is needed to reproduce the issue.

**Comment by mapx-** [comment]
@Dannnnnnnnnnnny 
we need an account to check your issue. Are you willing to provide it to us ? (I'll provide an email address where you can send user / pass in case you agree)
