### ISSUE TITLE
viu.com: breakage- the video player won't work after I activated the ad blocker. It wasn't like this before, I could even use it 2 days ago.

### ISSUE THREAD

**Issue by Aydenwng** [uBlockOrigin/uAssets#23790]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.viu.com/ott/hk/zh/vod/2357621/%E9%AC%BC%E6%BB%85%E4%B9%8B%E5%88%83-%E6%9F%B1%E8%A8%93%E7%B7%B4%E7%AF%87`

### Category

breakage

### Description

The video player on viu.com isn't working(can't full screen, can't have subtitles). It worked 2 days ago but now, it doesn't. I'm also always connected to a VPN so it's not a VPN problem. When I disable the ad blocker, the video player works again but when I enable it, it doesn't work. Please fix it. Thank You.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 136148
 cosmetic: 46855
 scriptlet: 20992
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38335-375, 2m
  ublock-badware: 8677-0, 2m
  ublock-privacy: 924-0, 2m
  ublock-unbreak: 2278-0, 2m
  ublock-quick-fixes: 152-0, 2m
  easylist: 87351-461, 2m
  easyprivacy: 50955-810, 2m
  urlhaus-1: 13395-0, 2m
  plowe-0: 3726-0, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5288 ms
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  d2r1yp2w7bby2u.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  sentry.io: 1
 extended:
  ##.ad_title
  ##+js(no-xhr-if, mobileanalytics)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

DON'T open duplicated issue
