### ISSUE TITLE
pilipinaslive.com: breakage

### ISSUE THREAD

**Issue by g-triv** [uBlockOrigin/uAssets#23795]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pilipinaslive.com/player/liveevent/plive-avc-challengecup-2024-indvsiri-052224`

### Category

[unknown]

### Description

pilipinaslive.com unable to play live content. But I can play stored content. When uBlock is turned off, I can play the live content. The URL above is one of the current live content in pilipinaslive.com.

### Other extensions used

Easy Youtube Downlader Express
Facebook Container
Video DownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pilipinaslive_com live content](https://github.com/uBlockOrigin/uAssets/assets/170499004/7a61cb5b-edde-4d3e-a6fc-ef31a53aa228)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 135943
 cosmetic: 46697
 scriptlet: 19557
 html: 1811
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38393-113, 15m Δ
  ublock-badware: 8758-0, 15m Δ
  ublock-privacy: 920-2, 15m Δ
  ublock-unbreak: 2335-2, 15m Δ
  ublock-quick-fixes: 157-15, 15m Δ
  easylist: 87317-164, 15m Δ
  easyprivacy: 50955-66, 15m Δ
  urlhaus-1: 13120-1, 15m
  plowe-0: 3726-1159, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1081 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  d2r1yp2w7bby2u.cloudfront.net: 1
  imasdk.googleapis.com: 1
  newrelic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like the site needs account?

---

Can you test this filter first?

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect-rule=google-ima.js,domain=pilipinaslive.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by stephenhawk8054** [comment]
When I tested OP's link with another account, the site says it needs a premium account for me.

**Comment by g-triv** [comment]
Thank you! The filter worked. :)


//Gilbert


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
