### ISSUE TITLE
NSFW 8muses.com

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#238]
### URL(s) where the issue occurs

https://www.8muses.com/comix/album/free-jab-comics

### Describe the issue

Blocks the page from loading and replaces it with the one in the screenshot.

### Screenshot(s)

https://i.gyazo.com/8fcf4473f85d3dc9dd3042432d3bc1bd.png

### Versions

- Browser/version: Chromium 57
- uBlock Origin version: 1.10.4

### Settings

Default

### Notes

Anti ADB appears/disappears and the cycle goes on, if you refresh the page.

**Comment by uBlock-user** [comment]
no change, situation is still the same.

**Comment by gorhill** [comment]
Works fine here, you will need to investigate on your side and find why it does not work on your side.

**Comment by uBlock-user** [comment]
I did and it seems the redirect filters you added are not being applied. I don't know why. Though the cosmetic filter you added is being applied, but I guess without the redirect filter it won work.

**Comment by okiehsch** [comment]
Do you block `https://ads.exoclick.com/ads.js`
with something like `||exoclick.com^$third-party,important`?

**Comment by gorhill** [comment]
> redirect filters you added are not being applied. I don't know why

Logger please. I am out of ideas of what to do to make people realize this is always the first thing to look at.

**Comment by uBlock-user** [comment]
I already looked at the logger. Nothing's wrong. Exoclick was blacklisted in uMatrix. so I had to white-list script from `ads.exoclick.com` and XHR/Frame from `syndication.exoclick.com`. Now it works fine, but happens randomly once, I guess I will live with that.

**Comment by uBlock-user** [comment]
Simply add these filters and no blocking page at all, no more opening connections to adservers and then nooping them or whatever.

````
||8muses.com^$inline-script
@@||8muses.com/comix/picture^$inline-script
