### ISSUE TITLE
wiflix.travel: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#23803]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wiflix.travel/films-prochainement/27654-deadpool-3.html`

### Category

ads, fake readers and misleading buttons

### Description

Good french streaming website but with a lot of ads, fake player and misleading buttons.

### Other extensions used

None that interfere with uBlock

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/0f91c92b-cdc9-4e5e-b25f-83408dcb6cbc)
misleading buttons

![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/b72bcb7c-48a7-4b34-984d-4ecf59c673bb)
fake video player

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 175749
 cosmetic: 157046
 scriptlet: 29278
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1079-0, 9m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 9m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51044-12089, 1h.25m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-6, 1h.25m
  adguard-cookies: 29737-1645, 1h.25m
  ublock-cookies-adguard: 1152-0, 1h.25m
  fanboy-cookiemonster: 51044-51044, 1h.25m
  ublock-cookies-easylist: 1152-1152, 1h.25m
  RUS-0: 39504-261, 1h.25m
 default:
  user-filters: 1-0, never
  ublock-filters: 38349-353, 1h.25m
  ublock-badware: 8789-0, 1h.25m
  ublock-privacy: 924-0, 1h.25m
  ublock-unbreak: 2281-0, 1h.25m
  ublock-quick-fixes: 152-0, 1h.25m
  easylist: 87328-702, 1h.25m
  easyprivacy: 50959-812, 1h.25m
  urlhaus-1: 13145-0, 9m
  plowe-0: 3726-0, 1h.25m
  FRA-0: 24451-310, 1h.25m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 122 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  ads2550.bid: 1
  allicinarenig.com: 1
  brandygobian.com: 1
  googletagmanager.com: 1
  odologyelicit.com: 1
  phaseranarch.com: 1
  yandex.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
wiflix.travel##.myButton
wiflix.travel##iframe[src^="/voir/"]
```

cc @smed79
