### ISSUE TITLE
testcoz.com: detection

### ISSUE THREAD

**Issue by dixtuel** [uBlockOrigin/uAssets#23800]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.testcoz.com/test/9-sinif-turk-dili-ve-edebiyati-romanin-yapi-unsurlari-ve-turleri`

### Category

detection

### Description

Site uBlock Origin eklentisini algılıyor.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/121726849/d84b4542-6e4f-4c7c-a363-4e74c86c98e8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 137461
 cosmetic: 57137
 scriptlet: 22628
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 38339-292, 1h.37m Δ
  ublock-badware: 8776-0, 1h.37m Δ
  ublock-privacy: 924-0, 1h.37m Δ
  ublock-unbreak: 2279-0, 1h.37m Δ
  ublock-quick-fixes: 152-0, 1h.37m Δ
  easylist: 87322-556, 1h.37m Δ
  easyprivacy: 50958-815, 1h.37m Δ
  urlhaus-1: 13145-0, 4m
  plowe-0: 3726-0, 4m
  TUR-0: 13431-14, 4m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2379 ms (selfie)
 maxAssetCacheWait: 387 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  yandex.ru: 1
 extended:
  ##.adsbygoogle-noablate
```
</details>

**Comment by ghost** [comment]
kazanimtestleri.com.tr is no longer in use. remove please
