### ISSUE TITLE
[nsfw] girlscanner.online: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#23801]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://girlscanner.online/`

### Category

ads

### Description

There are ads

### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 175747
 cosmetic: 157045
 scriptlet: 29268
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1077-0, 1h.16m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 1h.16m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51044-12078, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-6, now
  adguard-cookies: 29737-1643, now
  ublock-cookies-adguard: 1152-0, now
  fanboy-cookiemonster: 51044-51044, now
  ublock-cookies-easylist: 1152-1152, now
  RUS-0: 39504-281, now
 default:
  user-filters: 1-0, never
  ublock-filters: 38339-384, now
  ublock-badware: 8789-0, now
  ublock-privacy: 924-0, now
  ublock-unbreak: 2281-0, now
  ublock-quick-fixes: 152-0, now
  easylist: 87328-466, now
  easyprivacy: 50959-812, now
  urlhaus-1: 13145-0, 1h.16m
  plowe-0: 3726-0, now
  FRA-0: 24451-509, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 120 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  exoclick.com: 1
  googletagmanager.com: 1
  magsrv.com: 1
  realsrv.com: 1
  waust.at: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Video doesn’t work at all even with uBO disabled.
