### ISSUE TITLE
zippyshare.com [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2381]
URL(s) where the issue occurs

`https://www75.zippyshare.com/v/nSmDjqGv/file.html`

Describe the issue

Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.8

Settings

Default

**Comment by mapx-** [comment]
No popup here.

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by smed79** [comment]
No popup for me too.

**Comment by ghajini** [comment]
`www113.zippyshare.com/v/6s04PyUn/file.html`
Player thumbnail controls (play,pause,full-screen etc) are broken due to Easylist filter

Pls add 

`|https://$xmlhttprequest,3p,domain=zippyshare.com,badfilter` to unbreak list
