### ISSUE TITLE
netoff.co.jp: breakage

### ISSUE THREAD

**Issue by r4oz8** [uBlockOrigin/uAssets#23810]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.netoff.co.jp/detail/0013714791
https://www.netoff.co.jp/cart_param
```

### Description

When I press the "Add to Cart" button while logged in, the loading gif remains displayed (It happens on the first link.).
I think this probably occurs on all product pages(https://www.netoff.co.jp/detail/*).

Also, when I try to delete the item by pressing the delete button from the page of the item in the cart while logged in, I cannot do so (It happens on the second link.).

I have confirmed that the above behavior does not occur when I am not logged in.

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 137649
 cosmetic: 59284
 scriptlet: 21191
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38354-288, 33m
  ublock-badware: 8744-0, 22m Δ
  ublock-privacy: 924-0, 33m
  ublock-unbreak: 2281-0, 33m
  ublock-quick-fixes: 160-0, 33m
  easylist: 87329-570, 33m
  easyprivacy: 50959-812, 33m
  urlhaus-1: 12790-0, 33m
  plowe-0: 3729-0, 7d.23h.21m
  JPN-1: 14727-51, 33m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 214 ms (selfie)
 maxAssetCacheWait: 19 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
netoff.co.jp##+js(set, _etmc, {})
netoff.co.jp##+js(set, _etmc.push, noopFunc)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by r4oz8** [comment]
I tried it while logged in and it seems to work correctly.
