### ISSUE TITLE
JapScan: breakage

### ISSUE THREAD

**Issue by RedSkull-666** [uBlockOrigin/uAssets#23819]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.japscan.lol/lecture-en-ligne/
```

### Description

Ads and ads-blocker detecto

### Other extensions used

ghostery
httpseverywhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/60255796/4f0856ef-05ed-44d7-92fc-c2d801397620)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 244037
 cosmetic: 259036
 scriptlet: 50543
 html: 2076
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79370-134, 1d.2h.16m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 21h.16m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99028-23120, 4d.4h.24m
  adguard-generic: 81794-4044, 1d.2h.16m
  adguard-mobile: 9390-70, 1d.2h.17m
  adguard-spyware-url: 1515-120, 1d.2h.17m
  block-lan: 66-0, 1d.22h.59m
  curben-phishing: 553-3, 21h.16m
  adguard-social: 23106-1642, 1d.2h.16m
  fanboy-thirdparty_social: 68-19, 4d.4h.24m
  fanboy-cookiemonster: 51012-51009, 6d.2h.51m
  fanboy-social: 16053-16043, 2d.21h.53m
  [3 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 38415-449, 8m Δ
  ublock-badware: 8828-0, 8m Δ
  ublock-privacy: 920-4, 8m Δ
  ublock-unbreak: 2341-6, 8m Δ
  ublock-quick-fixes: 165-15, 8m Δ
  easylist: 87305-2043, 8m Δ
  easyprivacy: 50963-325, 8m Δ
  urlhaus-1: 13145-1, 21h.16m
  plowe-0: 3726-1588, 8m
  FRA-0: 24451-693, 1d.2h.16m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2045 ms (selfie)
 maxAssetCacheWait: 1148 ms
 cacheBackend: indexedDB
```
</details>

**Comment by D4niloMR** [comment]
Continue in #23806
