### ISSUE TITLE
google.com: nuisance

### ISSUE THREAD

**Issue by ozne9876** [uBlockOrigin/uAssets#23817]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/`

### Category

nuisance

### Description

When I open Google in incognito mode the warning about cookies appears.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (213)](https://github.com/uBlockOrigin/uAssets/assets/157696146/83a4b785-6cf0-4ec0-a9d5-fd90bca66703)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 141737
 cosmetic: 102376
 scriptlet: 21731
 html: 1816
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1516-120, 7m
  adguard-social: 23117-47, 7m
  adguard-cookies: 29745-38, 7m
  ublock-cookies-adguard: 1153-13, 7m
 default:
  user-filters: 1-0, never
  ublock-filters: 38415-112, 2m Δ
  ublock-badware: 8828-0, 2m Δ
  ublock-privacy: 920-2, 2m Δ
  ublock-unbreak: 2341-2, 2m Δ
  ublock-quick-fixes: 165-15, 2m Δ
  easylist: 87305-164, 2m Δ
  easyprivacy: 50963-64, 2m Δ
  urlhaus-1: 12970-1, 7m
  plowe-0: 3726-1160, 7m
  ITA-0: 8422-36, 7m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 809 ms
 maxAssetCacheWait: 585 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  google.com: 12
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/23701
