### ISSUE TITLE
[nsfw] download.megaup.net: detection

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#23814]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://download.megaup.net/?idurl=0lixLaV5L89JKamcHXUberzV0u+iKo8BMdF5xLs5j2iUgLH2gDbuP6e70agOyzLZRbEcwWoB0gtpSY4tnTJfHTdZCJN8mvvRWTnNbwI67Wo=&idfilename=[NekoPoi]_Hajimete_no_Hitozu%20ma_-_03_[1080P][nekopoi.care%20].mp4&idfilesize=172.30%20MB`

### Category

detection

### Description

anti ad

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/b809f191-3465-4ba2-a0ba-5e55cc02b9a6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 141944
 cosmetic: 122073
 scriptlet: 31429
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 10146-12, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-1, now
  easylist-annoyances: 4638-95, now
  easylist-notifications: 3010-3, now
  fanboy-cookiemonster: 51048-209, now
  fanboy-social: 16094-3, now
  ublock-annoyances: 5896-43, now
  ublock-cookies-easylist: 1153-0, now
 default:
  user-filters: 16-0, never
  easylist: 87296-591, now
  easyprivacy: 50959-876, now
  plowe-0: 3726-0, now
  ublock-badware: 8826-2, 1h.32m Δ
  ublock-filters: 38356-383, now
  ublock-privacy: 924-5, now
  ublock-quick-fixes: 160-0, 1h.32m Δ
  ublock-unbreak: 2283-21, now
  urlhaus-1: 12790-1, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 848 ms (selfie)
 maxAssetCacheWait: 361 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  a-ads.com: 1
  bidgear.com: 1
  floitcarites.com: 1
  geogenyveered.com: 1
  menrealitycalc.com: 1
 extended:
  ##a img:not([src="images/main_logo_inverted.png"]):matches-css(h…
  ##+js(trusted-replace-node-text, script, ['name']!='id', ['name'…
  ##+js(spoof-css, a img:not([src="images/main_logo_inverted.png"]…
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(remove-node-text, script, FingerprintJS)
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20505
