### ISSUE TITLE
zillow.com: breakage

### ISSUE THREAD

**Issue by stevensonderekr** [uBlockOrigin/uAssets#23820]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.zillow.com/celebration-kissimmee-fl/`

### Category

breakage

### Description

Page loads, then becomes a white static page on mobile 

### Other extensions used

DarkReader, disabling does not change behavior 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox Mobile: 126
filterset (summary):
 network: 137323
 cosmetic: 54787
 scriptlet: 19637
 html: 1817
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 38844-113, 55m Δ
  ublock-badware: 8822-0, 55m Δ
  ublock-privacy: 921-2, 55m Δ
  ublock-unbreak: 2344-2, 55m Δ
  ublock-quick-fixes: 165-15, 55m Δ
  adguard-mobile: 9389-69, never
  easylist: 87305-228, 55m Δ
  easyprivacy: 50963-72, 55m Δ
  urlhaus-1: 12970-1, now
  plowe-0: 3726-1233, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1585 ms (selfie)
 maxAssetCacheWait: 125 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  zillow.com: 1
  datadoghq-browser-agent.com: 1
  google-analytics.com: 2
  scorecardresearch.com: 1
  sentry-cdn.com: 1
  sentry.io: 2
  zg-api.com: 3
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, test without any other addon enabled

**Comment by stephenhawk8054** [comment]
I can reproduce, but need to clear all cookies and data every time

@stevensonderekr Can you test this filter?

```adb
zillow.com##+js(set, DD_RUM.addError, noopFunc)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
