### ISSUE TITLE
scribd.com: detection

### ISSUE THREAD

**Issue by er512** [uBlockOrigin/uAssets#23827]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.scribd.com/`

### Category

detection

### Description

A blank page appears after loading the page.(When user fiters removed, the same situation)
When UBO disabled, page work normaly.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/3527953/aed2203c-69cf-4b9f-9401-6ec7af4a616d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 78
filterset (summary):
 network: 227129
 cosmetic: 266129
 scriptlet: 51735
 html: 2079
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80891-3994, now
  adguard-mobile: 9390-59, now
  adguard-spyware-url: 1517-120, now
  adguard-spyware: 72344-1362, now
  block-lan: 67-0, now
  curben-phishing: 544-0, now
  adguard-social: 23117-53, now
  adguard-cookies: 29753-49, now
  ublock-cookies-adguard: 1153-13, now
  adguard-popup-overlays: 27504-1003, now
  adguard-mobile-app-banners: 5248-23, now
  adguard-other-annoyances: 14413-413, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 5099-32, never
  ublock-filters: 38421-112, 1h.57m Δ
  ublock-badware: 8835-0, 1h.57m Δ
  ublock-privacy: 920-2, 1h.57m Δ
  ublock-unbreak: 2342-2, 1h.57m Δ
  ublock-quick-fixes: 165-15, 1h.57m Δ
  easylist: 87306-2045, 1h.57m Δ
  easyprivacy: 50971-29006, 1h.57m Δ
  urlhaus-1: 12865-1, now
  plowe-0: 3726-1325, now
filterset (user): [array of 5102 redacted]
trustedset:
 added: [array of 27 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1445 ms (selfie)
 maxAssetCacheWait: 1173 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 10
 no-remote-fonts: true
 network:
  scribd.com: 6
  google-analytics.com: 1
  optimizely.com: 1
  osano.com: 1
  sentry-cdn.com: 1
 extended:
  ##+js(addEventListener-defuser, /^(mouseout|mouseleave)$/)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by er512** [comment]
Hello, thank for reply.
I have found, that the problem is after loading the filters:(individually or together)
AdGuard/uBO – Cookie Notices
EasyList/uBO – Cookie Notices
After disabling its, site work normaly. These filters must be updated.

**Comment by Alex-302** [comment]
@ghajini Fixed.

**Comment by loman7560** [comment]
It's detected again on scribd.com.
uBO-L(Basic)

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/bc4579d0-aed4-4149-8f4a-dc8e66548549" />

**Comment by stephenhawk8054** [comment]
Did you try Optimal mode?

**Comment by loman7560** [comment]
Yes, optimal filtering mode looks good. Why does basic filter have that issue? Do you think it needs to be fixed?

**Comment by stephenhawk8054** [comment]
No, basic means basic. That mode lacks advanced features to deal with complicated issues. If you want to resolve those complicated ones, you'll need Optimal mode.

**Comment by Monoverde888** [comment]
This is still happening on full uBo
