### ISSUE TITLE
247sudoku.com: ads

### ISSUE THREAD

**Issue by sickofurshitalready** [uBlockOrigin/uAssets#23826]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.247sudoku.com/sudokuMedium.php`

### Category

ads

### Description

Ad leftovers remain on the side of the page.

### Other extensions used

library extension, duckduckgo privacy essentials, unpaywall, xkitrewritten, web archives, firefox translations

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 135830
 cosmetic: 46658
 scriptlet: 19575
 html: 1818
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38421-112, 17m Δ
  ublock-badware: 8835-0, 17m Δ
  ublock-privacy: 920-2, 17m Δ
  ublock-unbreak: 2342-2, 17m Δ
  ublock-quick-fixes: 165-15, 17m Δ
  easylist: 87306-164, 17m Δ
  easyprivacy: 50971-65, 17m Δ
  urlhaus-1: 12865-0, 9m
  plowe-0: 3726-1159, 9m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 12368 ms
 maxAssetCacheWait: 890 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  247sudoku.com: 2
  amazon-adsystem.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  primis.tech: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
247sudoku.com##div[class^="aspace"]
```

@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/5b7ce21154a458053cb4d46fa7c19f3a730634bc
