### ISSUE TITLE
mundodeportivo.com: nuisance

### ISSUE THREAD

**Issue by goblinsta** [uBlockOrigin/uAssets#23839]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mundodeportivo.com/`

### Category

nuisance

### Description

Overlay paywall doesnt allow to read

### Other extensions used

Languagetool, foxtrick, bypass paywall clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 206087
 cosmetic: 193945
 scriptlet: 52010
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80946-6962, now
  adguard-mobile: 9394-128, now
  adguard-spyware-url: 1522-6, now
  adguard-spyware: 72345-29394, now
  curben-phishing: 524-0, now
  fanboy-cookiemonster: 51066-258, now
  ublock-cookies-easylist: 1160-0, now
  adguard-popup-overlays: 27515-983, now
  adguard-mobile-app-banners: 5252-8, now
  adguard-other-annoyances: 14419-605, now
  adguard-widgets: 2512-23, now
  easylist-annoyances: 4640-61, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38372-107, now
  ublock-badware: 8850-2, now
  ublock-privacy: 924-118, now
  ublock-unbreak: 2291-2, now
  ublock-quick-fixes: 162-10, 25m Δ
  easylist: 87283-684, now
  easyprivacy: 50976-182, now
  urlhaus-1: 13545-1, now
  plowe-0: 3725-786, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 692 ms (selfie)
 maxAssetCacheWait: 474 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  insurads.com: 1
  newsroom.bi: 2
  permutive.app: 1
  scorecardresearch.com: 1
  sensic.net: 1
 extended:
  ##.hidden-ad
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.ad-unit:not(.textads)
  ##.bottom-ad
  ##.sticky-ad
  ##.ads-wall-container
  ##.module-box-ads
  ##.ads-box
  ##.ads-module
  ##.ads-sticky
  #@#.ad-unit
```
</details>

**Comment by ItsProfessional** [comment]
1. Unable to reproduce.
2. We don't fix paywalls.
>uAssets will not address the following:
> * Paywalls
> * Porn Farms
