### ISSUE TITLE
bristan.com: breakage

### ISSUE THREAD

**Issue by JetVarimax** [uBlockOrigin/uAssets#23831]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bristan.com/products/bathroom-taps?code=ae%20basnw%20c`

### Category

breakage

### Description

Scroll down just over half way.
Click "Fitting & Specification". Nothing happens.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 126
filterset (summary):
 network: 136552
 cosmetic: 46662
 scriptlet: 19576
 html: 1818
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38424-112, 18m Δ
  ublock-badware: 8835-0, 18m Δ
  ublock-privacy: 920-2, 18m Δ
  ublock-unbreak: 2343-2, 18m Δ
  ublock-quick-fixes: 166-15, 18m Δ
  easylist: 87310-164, 18m Δ
  easyprivacy: 50971-64, 18m Δ
  urlhaus-1: 13585-1, 1m
  plowe-0: 3725-1159, 1m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  facebook.net: 1
  googletagmanager.com: 1
  sharethis.com: 1
```
</details>

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/issues/23830
