### ISSUE TITLE
japscan.lol: ads / detection

### ISSUE THREAD

**Issue by Maddos75** [uBlockOrigin/uAssets#23833]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The Japscan site is a platform for illegally viewing manga. However, recently the site has started requiring users to disable their ad blocker and pay for a subscription to avoid ads.

Until now, it was possible to bypass this with several ad blockers/pop-up blockers, etc. This time, Japscan completely blocks the page with a large error message saying:

"Oops! It looks like you're using an ad blocker. We understand that you may have reasons for doing so, but we want to remind you that our site relies on advertising revenue to continue operating. Using an ad blocker hinders our ability to provide free quality content. If you would like to support us in another way, we invite you to consider disabling your ad blocker for our site, or you can make a donation to remove ads. This option allows you to directly contribute to our mission while enjoying an ad-free experience. Thank you for your understanding and support. Refresh / Donate."

### A specific URL where the issue occurs.

```yaml
https://www.japscan.lol/
```

### Steps to Reproduce

Simply visit the site, and you will see the problem immediately. You'll see the page for a few seconds before the blocker activates...

### Expected behavior

I would like the site to stop displaying this message so I can browse as usual and read my manga. There are a lot of hentai ads on the site; if you could remove them as well, they appear even during reading. Thank you very much.

### Actual behavior

Intrusive ads are present throughout the site, and the site is completely blocked if an ad blocker is enabled.

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 153056
 cosmetic: 53385
 scriptlet: 21167
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 24432-310, 3d.29m
  easylist: 87314-588, 37m Δ
  easyprivacy: 50973-809, 37m Δ
  plowe-0: 3725-0, 37m
  ublock-badware: 8833-0, 37m Δ
  ublock-filters: 38374-442, 37m Δ
  ublock-privacy: 924-0, 37m Δ
  ublock-quick-fixes: 161-0, 37m Δ
  ublock-unbreak: 2286-0, 37m Δ
  urlhaus-1: 12970-1, 22h.23m
filterset (user): [empty]
trustedset:
 added: [array of 54 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2643 ms (selfie)
 maxAssetCacheWait: 170 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/23806
