### ISSUE TITLE
badlefthook.com: nuisance

### ISSUE THREAD

**Issue by xemptsible** [uBlockOrigin/uAssets#23837]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.badlefthook.com/`

### Category

nuisance

### Description

When you visit the site for the first time and scroll down, the newsletter banner pops up.

### Other extensions used

none (tested in PB mode with default uBO only)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240525_125735_Firefox Nightly](https://github.com/uBlockOrigin/uAssets/assets/131531215/dee5bd32-4ca8-48c9-aee0-74c24cbf91c3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 128
filterset (summary):
 network: 201991
 cosmetic: 107691
 scriptlet: 28708
 html: 2083
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2618-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.mini.txt: 91510-164, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 260-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 98-0, now
  block-lan: 67-0, now
  fanboy-cookiemonster: 67226-16354, now
  ublock-cookies-easylist: 1198-12, now
  adguard-mobile-app-banners: 5252-15, now
  ublock-annoyances: 5871-69, now
  VIE-1: 1915-65, now
 default:
  user-filters: 14-0, never
  ublock-filters: 38856-113, now
  ublock-badware: 8830-422, now
  ublock-privacy: 921-75, now
  ublock-unbreak: 2351-3, now
  ublock-quick-fixes: 167-15, now
  adguard-mobile: 9394-543, now
  easylist: 87283-23809, now
  easyprivacy: 50976-7367, now
  urlhaus-1: 13545-1, now
  plowe-0: 3725-2416, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 607 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9589 ms
 maxAssetCacheWait: 425 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  amazon-adsystem.com: 1
  associates-amazon.com: 2
  concert.io: 5
  doubleverify.com: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  metabet.io: 2
  outbrain.com: 1
  parsely.com: 2
  recaptcha.net: 2
  rollconnection.com: 1
  rubiconproject.com: 2
  vox-cdn.com: 3
  voxmedia.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `EasyList – Newsletter Notices` list

**Comment by xemptsible** [comment]
> Enable `EasyList – Newsletter Notices` list

It works. Sorry for taking up your time.
