### ISSUE TITLE
operavision.eu: nuisance

### ISSUE THREAD

**Issue by BuffCyclist0524** [uBlockOrigin/uAssets#23835]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://operavision.eu/performance/il-giustino`

### Category

nuisance

### Description

uBlock is not blocking a cookie popup

### Other extensions used

SponsorBlock
DeArrow
Grammarly
Bitwarden
Ground News
Return YouTube Dislikes
GopherGrades
Adobe Acrobat
Firefox Translation

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/170767447/56bfa766-8001-46a2-974c-4c83261ed812)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 136522
 cosmetic: 46691
 scriptlet: 19574
 html: 1822
listset (total-discarded, last-updated):
 default:
  user-filters: 26-0, never
  ublock-filters: 38420-112, now
  ublock-badware: 8835-0, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2348-2, now
  ublock-quick-fixes: 167-15, now
  easylist: 87321-164, now
  easyprivacy: 50974-64, now
  urlhaus-1: 13545-1, now
  plowe-0: 3725-1159, now
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 7 redacted]
hostRuleset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 10000
hiddenSettings: [none]
supportStats:
 allReadyAfter: 903 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  matomo.cloud: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `EasyList/uBO – Cookie Notices` lists

**Comment by BuffCyclist0524** [comment]
That fixed it
