### ISSUE TITLE
outlook.live.com: breakage

### ISSUE THREAD

**Issue by cxen** [uBlockOrigin/uAssets#23842]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://outlook.live.com/mail/
```

### Description

The emails search function is broken (returns nothing) when the specific default filters are enabled.
However, the search function is only broken when searching in a folder. Searching in the Inbox still works; starting a search from a folder or starting from the Inbox and then navigating to a folder with the dropdown menu, turns out broken.

I could not isolate the issue to one of the filters, as enabling any of these will break the outlook.com search function:

### Ads
EasyList
AdGuard – Ads

### Multipurpose
Peter Lowe’s Ad and tracking server list
Dan Pollock’s hosts file

### Other extensions used

Unrelated

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

# Broken - Filters enabled

![image](https://github.com/uBlockOrigin/uAssets/assets/46993334/87e63ab7-a9d7-40c1-b8a7-203c8b775f50)

# Normal - Filters disabled

![image](https://github.com/uBlockOrigin/uAssets/assets/46993334/c58665ae-b0b1-482b-b577-17777fe37b74)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 219019
 cosmetic: 202845
 scriptlet: 68769
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/bpc-clone/bypass-paywalls-clean-filters/raw/main/bpc-paywall-filter.txt: 1081-0, 1m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=rawlist: 185-0, 1m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=rawlist: 23291-20, 1m
  adguard-cookies: 29757-60, 1m
  adguard-generic: 80948-7494, 1m
  adguard-mobile: 9394-11, 1m
  adguard-other-annoyances: 14420-149, 1m
  adguard-social: 23120-164, 1m
  adguard-spyware: 72345-29389, 1m
  adguard-spyware-url: 1522-5, 1m
  block-lan: 67-0, 1m
  curben-phishing: 502-0, 1m
  [7 lists not shown]: [too many]
 default:
  user-filters: 7-0, never
  easylist: 87306-863, 1m
  easyprivacy: 50963-181, 1m
  plowe-0: 3725-1284, 1m
  ublock-badware: 8823-2, 1m
  ublock-filters: 38367-2489, 1m
  ublock-privacy: 924-119, 1m
  ublock-quick-fixes: 162-0, 1m
  ublock-unbreak: 2285-25, 1m
  urlhaus-1: 13585-0, 1m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 322 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 8 redacted]
hostRuleset:
 added: [array of 108 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2209 ms (selfie)
 maxAssetCacheWait: 599 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  3lift.com: 2
  adnxs.com: 1
  microsoft.com: 7
  msn.com: 1
  taboola.com: 18
 extended:
  ##div[class][tabindex="-1"][role="region"][aria-label][data-min-…
  ###MainModule div[data-max-width="2400"] + div[class]
  ##div[data-app-section="MessageList"] > div:first-child:has(> di…
  ##.Ogt7j
  ##div[data-app-section="MessageList"] div[role="listbox"] .custo…
  ##.customScrollBar[tabindex] .customScrollBar > div[style] > div…
  ##body:style(overflow: auto !important)

```
</details>

**Comment by Yuki2718** [comment]
> * [x]  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

How?

> listset (total-discarded, last-updated):
>  added:
>   https://github.com/bpc-clone/bypass-paywalls-clean-filters/raw/main/bpc-paywall-filter.txt: 1081-0, 1m
>   https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=rawlist: 185-0, 1m
>   https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=rawlist: 23291-20, 1m
>   adguard-cookies: 29757-60, 1m
>   adguard-generic: 80948-7494, 1m
>   adguard-mobile: 9394-11, 1m
>   adguard-other-annoyances: 14420-149, 1m
>   adguard-social: 23120-164, 1m
>   adguard-spyware: 72345-29389, 1m
>   adguard-spyware-url: 1522-5, 1m
>   block-lan: 67-0, 1m
>   curben-phishing: 502-0, 1m
>   [7 lists not shown]: [too many]
>  default:
>   user-filters: 7-0, never
>   easylist: 87306-863, 1m
>   easyprivacy: 50963-181, 1m
>   plowe-0: 3725-1284, 1m
>   ublock-badware: 8823-2, 1m
>   ublock-filters: 38367-2489, 1m
>   ublock-privacy: 924-119, 1m
>   ublock-quick-fixes: 162-0, 1m
>   ublock-unbreak: 2285-25, 1m
>   urlhaus-1: 13585-0, 1m
> filterset (user): [array of 7 redacted]
> trustedset:
>  added: [array of 322 redacted]
>  removed:
>   moz-extension-scheme
> switchRuleset:
>  added: [array of 8 redacted]
> hostRuleset:
>  added: [array of 108 redacted]
>  removed:
>   behind-the-scene * * noop
>   behind-the-scene * image noop
>   behind-the-scene * 3p noop
>   behind-the-scene * inline-script noop
>   behind-the-scene * 1p-script noop
>   behind-the-scene * 3p-script noop
>   behind-the-scene * 3p-frame noop
> userSettings:
>  advancedUserEnabled: true
>  cloudStorageEnabled: true
>  showIconBadge: false

**Comment by Yuki2718** [comment]
Folder or wherever, no problem even with most of stock lists enabled.

**Comment by cxen** [comment]
You are right, I left the custom filters on. I disabled custom filters and tried again:

Disabled all filters. Issue gone.
Enabled all build-in filters, only. Issue returned.
Disabled the specified filters above. Issue gone.

**Comment by ItsProfessional** [comment]
Create a new profile of your browser, with a default configuration of uBO and no other extensions, and test again.

**Comment by cxen** [comment]
Outlook search works with a fresh Edge profile, with default UBO settings.
However, the affected filters from above, are not all enabled by default. If enabled, outlook search breaks again.

**Comment by cxen** [comment]
It's also very inconsistent. If I keep refreshing, in the new profile, the search function works sometimes even with all filters enabled.

**Comment by stephenhawk8054** [comment]
> even with all filters enabled.

What do you mean "all filters enabled"? Is it default settings or are you enabling / adding some filter lists again?

**Comment by cxen** [comment]
Default settings but ticking on all of the included filters.
Most of the ones I reported are not enabled by default.

**Comment by stephenhawk8054** [comment]
Turn on one by one and check which list is causing issue

**Comment by ibrahimab** [comment]
This issue is still active, but I found the filter that causes this problem. It is Annoyances > AdGuard Annoyances > AdGuard - Other Annoyances.

If you turn this filter off, outlook search will work again.

**Comment by Yuki2718** [comment]
If you does, please also describe your layout settings of Outlook. I don't see any problem with AdGuard - Other Annoyances enabled.
