### ISSUE TITLE
japscan.lol: breakage

### ISSUE THREAD

**Issue by RedSkull-666** [uBlockOrigin/uAssets#23840]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.japscan.lol/`

### Category

breakage / detection

### Description

the images do not appear

### Other extensions used

Ghostery

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/60255796/895e3d79-9767-4cfa-9867-1a6b8cc04b44)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 237367
 cosmetic: 259221
 scriptlet: 50545
 html: 2084
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79454-457, 1h.21m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99214-23166, 1h.21m
  adguard-generic: 80946-4046, 1h.29m
  adguard-mobile: 9394-72, 1h.29m
  adguard-spyware-url: 1522-120, 1h.29m
  block-lan: 67-0, 1h.29m
  curben-phishing: 524-1, 1h.29m
  adguard-social: 23119-1647, 1h.29m
  fanboy-thirdparty_social: 68-19, 1h.29m
  fanboy-cookiemonster: 51066-51064, 1h.29m
  fanboy-social: 16098-16098, 1h.29m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38384-112, now
  ublock-badware: 8857-0, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2348-6, now
  ublock-quick-fixes: 167-69, now
  easylist: 87268-2127, now
  easyprivacy: 50977-326, now
  urlhaus-1: 13545-1, 1h.29m
  plowe-0: 3725-1595, 1h.29m
  FRA-0: 24601-702, 1h.29m
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1500 ms (selfie)
 maxAssetCacheWait: 829 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  japscan.lol: 8
  fadingsulphur.com: 2
  googletagmanager.com: 2
  statorkumyk.com: 1
 extended:
  ###mgid_iframe1
  ###ad_footer:not([style^="position: absolute; left: -5000px"])
  ##.ad_footer
  ##.tangoai
  ###blur-inter
  ###interstitial
  ##.nav-item:has(> .text-truncate.nav-link.font-weight-bold[href*…
  ##div.container > [href]
  ##+js(no-setTimeout-if, detectImgLoad)
  ##+js(addEventListener-defuser, DOMContentLoaded, 0x)
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
  ##+js(no-setTimeout-if, sessionStorage)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/23806
