### ISSUE TITLE
Video Ads Not blocked on 7Plus site

### ISSUE THREAD

**Issue by Firedingo** [uBlockOrigin/uAssets#2384]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

Any video on the 7plus website, example video supplied 
`https://7plus.com.au/AST?episode-id=AST-245`

### Describe the issue

Video ads are not blocked on the 7plus website and any attempt to block them on my part has proceeded to break the player in various ways.
From best as I can tell, the offending URL seems to be `boltdns.net`

### Screenshot(s)

Assuming no screenshot is necessary as the issue is not complex to describe.

### Versions

- Browser/version: Opera 53.0, Firefox ESR 52.8.0
- uBlock Origin version: 1.16.6

### Settings

- Just enabled Advanced settings is all
-Attempted to add boltdns to block list without success

### Notes

I studied the logger to try and understand where the video was coming from. Looked to be two domains:
`-7plus-sevennetwork.akamaized.net`
`-boltdns.net`

My guess is that boltdns is the one serving the ads however all attempts to block them were unsuccessful and often resulted in the player breaking or it complaining I was outside Australia.
Was not really sure what else to do after that.
I do not think this is a failure of Ublock but rather a filtering issue.

**Comment by mapx-** [comment]
I used an australian ip but I get no video ad. Tested in FF / chrome.
I see xhr requests for both `7plus-sevennetwork.akamaized.net` and `boltdns.net`

**Comment by krystian3w** [comment]
Disable Opera embedded AdBlock?

**Comment by Firedingo** [comment]
Same issue when I try that as well. I mostly forget about it but recently trying to use the SBS On Demand site I discovered Opera's built in adblock results in the entire video player being blocked so I thought to try disabling it this time as well. No change.

**Comment by cyphix333** [comment]
> I used an australian ip but I get no video ad. Tested in FF / chrome.

The amount of ads vary, sometimes you will get a couple, sometimes you will get several; I think in very rare cases there has been none.

**Comment by Firedingo** [comment]
> The amount of ads vary, sometimes you will get a couple, sometimes you will get several; I think in very rare cases there has been none.
Yeah. On one occasion I got 0 ads but on every other occasion I got multiple. A good 5 or so I would guess. The ads reoccur every 10-15 minutes or so which makes them extra annoying, especially when you get more rather than less ads.

**Comment by jspenguin2017** [comment]
I see no ads neither: 
![image](https://user-images.githubusercontent.com/7283682/40882215-233cb69c-6698-11e8-8599-b4b6ede33adb.png)

**Comment by mapx-** [comment]
SSAI stuff

```
https://ssaiplayback.ap-southeast-2.prod.boltdns.net/playback/once/redirect/v1/5303576322001/6cdf1bb6-5a78-4539-8eff-3566b689fa0f/xae/default_audio64_2/segment4.ts
https://ssaiplayback.ap-southeast-2.prod.boltdns.net/playback/once/redirect/v1/5303576322001/6cdf1bb6-5a78-4539-8eff-3566b689fa0f/xae/default_audio64_2/segment3.ts

https://ssaiplayback.ap-southeast-2.prod.boltdns.net/playback/once/redirect/v1/5303576322001/6cdf1bb6-5a78-4539-8eff-3566b689fa0f/xae/5303576322001_video-200-wtmk_0_256x144/segment14.ts

https://ssaiplayback.ap-southeast-2.prod.boltdns.net/playback/once/redirect/v1/5303576322001/acb64566-850d-4786-9508-8e188e92663c/xa6/5303576322001_video-200-wtmk_0_256x144/segment12.ts
https://ssaiplayback.ap-southeast-2.prod.boltdns.net/playback/once/redirect/v1/5303576322001/acb64566-850d-4786-9508-8e188e92663c/xa6/5303576322001_video-200-wtmk_0_256x144/segment11.ts
```
