### ISSUE TITLE
palia.th.gl: detection

### ISSUE THREAD

**Issue by WolfgangDS** [uBlockOrigin/uAssets#23849]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://palia.th.gl/en/Kilima%20Valley
https://palia.th.gl/en/rummage-pile
https://palworld.th.gl/
https://diablo4.th.gl/
```

### Description

Adblockers are detected on all sites in The Hidden Gaming Lair's network, except for the primary "th.gl" domain.

### Other extensions used

Dark Reader
Enhancer for YouTube
Reddit Enhancement Suite

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-26 020729](https://github.com/uBlockOrigin/uAssets/assets/4020732/bbb2d0ad-6209-4bf7-9c72-74571ad58bfc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 136584
 cosmetic: 46769
 scriptlet: 21023
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38372-119, 3m
  ublock-badware: 8850-0, 3m
  ublock-privacy: 924-0, 3m
  ublock-unbreak: 2291-0, 3m
  ublock-quick-fixes: 162-0, 3m
  easylist: 87306-540, 3m
  easyprivacy: 50982-984, 3m
  urlhaus-1: 13560-0, 3m
  plowe-0: 3725-0, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2466 ms
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in the old threads.
