### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by urjazzy13** [uBlockOrigin/uAssets#23846]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.instagram.com/`

### Category

supicious login attemped 

### Description

It doesn't let me in it says Suspicious login attemped

### Other extensions used

It doesn't let me in

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 122
filterset (summary):
 network: 136608
 cosmetic: 46573
 scriptlet: 20922
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38151-335, 7m
  ublock-badware: 8855-0, 7m
  ublock-privacy: 924-0, 7m
  ublock-unbreak: 2291-0, 7m
  ublock-quick-fixes: 162-0, 7m
  easylist: 87286-553, 7m
  easyprivacy: 50974-23, 7m
  urlhaus-1: 13585-0, 7m
  plowe-0: 3725-786, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2165 ms
 maxAssetCacheWait: 25 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  instagram.com: 7
```
</details>

**Comment by urjazzy13** [comment]
it's blocked

**Comment by D4niloMR** [comment]
> - [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.

Did you verify this?

**Comment by krystian3w** [comment]
Of course not:

> - [x] I did not answer truthfully to ALL the above checkboxes.
