### ISSUE TITLE
brisbanedevelopment.com: detection

### ISSUE THREAD

**Issue by SfSec** [uBlockOrigin/uAssets#23859]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://brisbanedevelopment.com/prax-studio-unveils-conceptual-vision-for-toombul-shopping-centre/`

### Category

detection

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/92378302/ed7ca701-f8ea-429d-8c67-62ebdc23ed2b)

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/92378302/24f7a767-102c-40bf-a606-fecb29a091bb)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 136887
 cosmetic: 46444
 scriptlet: 19493
 html: 1823
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38217-112, now
  ublock-badware: 8882-0, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2348-2, now
  ublock-quick-fixes: 163-68, now
  easylist: 87299-166, now
  easyprivacy: 50983-64, now
  urlhaus-1: 13835-1, now
  plowe-0: 3727-1159, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 196 ms (selfie)
 maxAssetCacheWait: 46 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  googlesyndication.com: 2
  googletagmanager.com: 2
  googletagservices.com: 1
  unrulymedia.com: 2
  wp.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.top-site-ad
  ##.ad-wrap:not(#google_ads_iframe_checktag)
  ##.widget-ad-script
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-wrap
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by SfSec** [comment]
It works, thanks mate!
