### ISSUE TITLE
weibo.com: nuisance

### ISSUE THREAD

**Issue by DidNotWantToCreateGithubAccount** [uBlockOrigin/uAssets#23851]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://weibo.com/xiaozhan1`

### Category

popups

### Description

Whenever I play any video and pause or play one till the end, it either opens a pop up of or redirects me to a log-in page, whose url starts with passport.weibo.com. Pop up or redirection on the domain is set as Blocked on my Chrome setting. 

### Other extensions used

Tampermonkey, Download HLS Streams

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Weibo redirection](https://github.com/uBlockOrigin/uAssets/assets/170854128/6cefc922-0abe-40ac-9fab-e16af3388aea)
![Weibo pop up](https://github.com/uBlockOrigin/uAssets/assets/170854128/9b01680c-8dd4-456f-9270-14c621aa31c0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 206341
 cosmetic: 166691
 scriptlet: 51115
 html: 0
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99226-99226, 8m
  adguard-generic: 80946-7127, 8m
  adguard-mobile: 9394-94, 8m
  adguard-mobile-app-banners: 5253-21, 8m
  adguard-other-annoyances: 14420-372, 8m
  adguard-popup-overlays: 27518-968, 8m
  adguard-spyware: 72347-29377, 8m
  adguard-widgets: 2512-54, 8m
  block-lan: 67-0, 8m
  easylist-annoyances: 4641-949, 8m
  easylist-chat: 196-12, 8m
  easylist-newsletters: 7464-1875, 8m
  [4 lists not shown]: [too many]
 default:
  user-filters: 801-12, never
  KOR-1: 4967-101, 1h.14m
  easylist: 87305-15014, 1h.14m Δ
  easyprivacy: 50982-108, 1h.14m Δ
  plowe-0: 3725-885, 8m
  ublock-badware: 8865-1, 1h.14m Δ
  ublock-filters: 38126-873, 1h.14m Δ
  ublock-privacy: 924-7, 1h.14m Δ
  ublock-quick-fixes: 158-0, 1h.14m Δ
  ublock-unbreak: 2291-24, 1h.14m Δ
  urlhaus-1: 13560-1, 1h.14m
filterset (user): [array of 802 redacted]
trustedset:
 added: [array of 69 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 530 ms (selfie)
 maxAssetCacheWait: 293 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 no-popups: true
 network:
  weibo.com: 2
  google.com: 1
 extended:
  ##+js(abort-current-script, console.log, location.replace)
```
</details>

**Comment by WilliamK7** [comment]
This rule should be removed because it bans people from normally logging into this site.

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce the issue in details?

**Comment by WilliamK7** [comment]
1. Go to weibo.com
2. Click on the Login/Register button in the upper-right corner
3. UBO blocks the pop-up window, so nothing happens. You can't login or register your account.
