### ISSUE TITLE
scrabble-solver.com: detection

### ISSUE THREAD

**Issue by russell-williams-ga** [uBlockOrigin/uAssets#23853]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.scrabble-solver.com/`

### Category

detection

### Description

detects blocker, works when exclusion applied

### Other extensions used

malwarebytes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/69200792/0d483f60-899b-4e22-b066-010e813891fd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 136637
 cosmetic: 46575
 scriptlet: 20910
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 21-1, never
  easylist: 87305-431, 1h.54m Δ
  easyprivacy: 50982-788, 1h.54m Δ
  plowe-0: 3725-0, now
  ublock-badware: 8880-15, 1h.54m Δ
  ublock-filters: 38127-426, 1h.54m Δ
  ublock-privacy: 924-6, 1h.54m Δ
  ublock-quick-fixes: 158-0, 1h.54m Δ
  ublock-unbreak: 2291-30, 1h.54m Δ
  urlhaus-1: 13560-1, 54m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 57921 ms (selfie)
 maxAssetCacheWait: 14005 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-popups: true
 extended:
  ##[data-freestar-ad][id]
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
