### ISSUE TITLE
lobby.chumbacasino.com: privacy

### ISSUE THREAD

**Issue by Apac8476** [uBlockOrigin/uAssets#23852]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lobby.chumbacasino.com/games/reallyReelyRich`

### Category

privacy

### Description

feels different glitches and freezes a lot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 136627
 cosmetic: 46561
 scriptlet: 20909
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38126-334, 22m
  ublock-badware: 8880-0, 22m
  ublock-privacy: 924-0, 22m
  ublock-unbreak: 2291-0, 22m
  ublock-quick-fixes: 158-0, 22m
  easylist: 87305-553, 22m Δ
  easyprivacy: 50977-810, 22m Δ
  urlhaus-1: 13560-0, 43m
  plowe-0: 3725-0, 43m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1466 ms
 maxAssetCacheWait: 16 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 network:
  chumbacasino.com: 2
  googletagmanager.com: 1
  qualtrics.com: 1
  sumologic.com: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
