### ISSUE TITLE
It breaks commenting on some sites and cause images to 404.

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [uBlockOrigin/uAssets#2385]
It breaks commenting on some sites (can't post comment until i disable it, then it works even without refreshing the webpage). Even if i allow everything, it still doesn't work. It's only when the disable button is clicked that it works. Sometimes causes images on sites (`https://boards.4chan.org/g/catalog`) to 404, but as soon as i disable it (no webpage reload needed!) images shows normally.

**Comment by mapx-** [comment]
No issues on 4chan for me.

For other sites do your tests using the default setup of uBo.
For any other site provide complete info (page, what's blocked on page, eventually screenshot).
A site = 1 issue
