### ISSUE TITLE
doesthedogdie.com: ads

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#23869]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.doesthedogdie.com/`

### Category

ads

### Description

Website still shows a leftover "remove ads" button.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/93544652/dd27ed15-2ce2-4b95-8628-64a387cf5819)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 139001
 cosmetic: 73055
 scriptlet: 22192
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29768-34, now
 default:
  user-filters: 80-0, never
  easylist: 87297-557, now
  easyprivacy: 50983-810, now
  plowe-0: 3727-0, now
  ublock-badware: 8928-0, now
  ublock-filters: 38213-335, now
  ublock-privacy: 946-0, now
  ublock-quick-fixes: 158-0, now
  ublock-unbreak: 2292-0, now
  urlhaus-1: 13745-0, now
filterset (user): [array of 82 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  adligature.com: 2
  googletagmanager.com: 2
  inmobi.com: 5
  sharethis.com: 3
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. You can use this as your custom filter

```adb
doesthedogdie.com###removeAdsButton
```
