### ISSUE TITLE
[nsfw] javjavhd.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#23864]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://javjavhd.com/porn/gvg-896/`

### Category

ads

### Description

ads

### Other extensions used

n

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/ce4f21af-f958-4417-9488-088d5d17c2d6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 141937
 cosmetic: 121681
 scriptlet: 30630
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8352-0, 1h.22m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 205-0, 1h.22m
  easylist-annoyances: 4644-17, 1h.9m
  easylist-notifications: 3017-83, 1h.9m
  fanboy-cookiemonster: 51077-221, 1h.9m
  fanboy-social: 16101-8, 1h.9m
  ublock-annoyances: 5908-43, 1h.9m
  ublock-cookies-easylist: 1164-0, 1h.9m
 default:
  user-filters: 8-1, never
  easylist: 87307-586, 1h.9m
  easyprivacy: 50983-86, 1h.9m
  plowe-0: 3727-786, 1h.9m
  ublock-badware: 8880-1, 1h.35m Δ
  ublock-filters: 38166-432, 1h.9m
  ublock-privacy: 924-5, 1h.9m
  ublock-quick-fixes: 158-0, 1h.35m Δ
  ublock-unbreak: 2292-21, 1h.9m
  urlhaus-1: 13780-1, 1h.9m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2054 ms
 maxAssetCacheWait: 714 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  blurbreimbursetrombone.com: 1
  d3eub2e21dc6h0.cloudfront.net: 1
  googletagmanager.com: 4
  realsrv.com: 2
  tsyndicate.com: 1
  zriajllpaa.com: 1
 extended:
  ##.social-share
  ##.adsbyexoclick
  ##a[title="Back to top"]
  ##.adsvideo
  ##.happy-inside-player
  ##.happy-under-player
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(abort-current-script, adcashMacros)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(abort-on-property-write, DoodPop)
  ##+js(abort-on-property-write, _pop)
  ##+js(addEventListener-defuser, contextmenu)
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(abort-on-property-read, __aaZoneid)
  ##+js(no-window-open-if)
  ##+js(remove-node-text, script, /adblock|popunder/)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
javjavhd.com##a[href^="https://pornsalt.com"]
```

Please report to EL repo: https://github.com/easylist/easylist/issues
