### ISSUE TITLE
emag.ro: ads

### ISSUE THREAD

**Issue by Silveeny** [uBlockOrigin/uAssets#23860]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.emag.ro/
```

### Description

This is one of the most famous retailers in Hungary/Romania/Bulgaria where Amazon has not expanded. As a new thing, when you search for stuff, it has items that are Promoted / Sponsored. These are internal ads by the website - but none the less, I think most people would appreciate if we could get rid of them. What bothers me is promoted items that appear in the search. They have almost never a purpose. They even have a category of Promoted items, which in general have no relevance to your search, but they slam them through the search results at random points. I checked the rules, but nothing was stated about this.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2](https://github.com/uBlockOrigin/uAssets/assets/67025250/eaf27320-18dc-4a46-bf71-62c0a95c6534)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 148590
 cosmetic: 205509
 scriptlet: 32984
 html: 2085
listset (total-discarded, last-updated):
 added:
  adguard-social: 23118-47, 3d.2h.34m
  fanboy-cookiemonster: 51072-183, 6h.29m
  fanboy-social: 16100-732, 1d.7h.29m
  ublock-annoyances: 5850-63, 3h.29m Δ
  ROU-1: 1385-41, 1d.10h.51m
  ublock-quick-fixes: 163-72, 3h.29m Δ
  adguard-cookies: 29749-3763, 3d.2h.34m
  adguard-popup-overlays: 27489-1108, 3d.2h.34m
  adguard-mobile-app-banners: 5240-24, 3d.2h.34m
  adguard-other-annoyances: 14406-476, 3d.2h.34m
  adguard-widgets: 2512-14, 3d.2h.34m
  easylist-annoyances: 4638-305, 2d.6h.32m
  [5 lists not shown]: [too many]
 default:
  user-filters: 5-0, never
  ublock-filters: 38217-116, 3h.29m Δ
  ublock-badware: 8882-0, 3h.29m Δ
  ublock-privacy: 920-0, 3h.29m Δ
  ublock-unbreak: 2348-0, 3h.29m Δ
  easylist: 87299-165, 3h.29m Δ
  easyprivacy: 50983-64, 3h.29m Δ
  urlhaus-1: 13835-1, 8h.29m
  plowe-0: 3726-1159, 8d.11h.27m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 63 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1884 ms
 maxAssetCacheWait: 1155 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  bing.com: 1
  creativecdn.com: 1
  criteo.com: 1
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 2
  google.com: 1
  googletagmanager.com: 2
  onesignal.com: 2
  pinimg.com: 1
  profitshare.ro: 1
  salesforce.com: 1
  sc-static.net: 1
  sentry.io: 5
  tiktok.com: 1
 extended:
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
  ##.gdpr-cookie-banner
  ##.js-gdpr-cookie-banner
  ##.ns-wrap-bottom-right
  ##body .gdpr-cookie-banner
  ##.widget-newsletter
  ##.grecaptcha-badge
  ##.grecaptcha-badge[data-style]
  ##+js(set-constant, rwt, noopFunc)

```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||sapi.emag.ro/recommendations/$xhr,1p
```

@mapx- For Romanian list?

**Comment by mapx-** [comment]
testing the filter on home page => breakage

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/03ff3c2c-4f6d-41c7-9c57-1a18670cdcef)

**Comment by stephenhawk8054** [comment]
Hmm... How about this?

```adb
||sapi.emag.ro/recommendations/*zones=adss$xhr,1p
```

**Comment by mapx-** [comment]
@Silveeny where can I see "a category of Promoted items" ? link ?

on a specific search, for example "masina de tuns" I see that the advertised items are correctly placed in that category

**Comment by mapx-** [comment]
@stephenhawk8054 it seems working on specific items search, here for example:

`https://www.emag.ro/search/masina%20de%20tuns?ref=trending`

**Comment by mapx-** [comment]
for Hungary is working too

`||sapi.emag.*/recommendations/*zones=adss$xhr,1p`

maybe we could add it to our annoyances list

**Comment by stephenhawk8054** [comment]
I think the last letter of `adss` means it's for search. For this link `https://www.emag.ro/laptopuri/filter/tip-laptop-f7882,2in1-v-4670931/c?ref=subcat_0_fashion-grid_0` it's `zones=adsl`, so I think using `zones=ads` would cover better

```adb
/recommendations/*zones=ads$xhr,1p,to=sapi.emag.*
```

**Comment by mapx-** [comment]
did you get that section "produse promovate" ?

**Comment by stephenhawk8054** [comment]
> did you get that section "Produse promovate" ?

Hmm... I can't find that section. Which link did you see it?

**Comment by mapx-** [comment]
However, the promoted items are not really ads, you could find double items (a "normal" item and a promoted one which is the same)

**Comment by mapx-** [comment]
I saw "Produse promovate" section in OP screenshot ("They even have a category of Promoted items")

**Comment by stephenhawk8054** [comment]
> I saw "Produse promovate" section in OP screenshot ("They even have a category of Promoted items")

Ah I see. Looks like it occurs in each product page: `https://www.emag.ro/husa-tip-carte-compatibila-cu-samsung-galaxy-a13-5g-a04s-model-smart-book-case-material-textil-negru-5903396133381/pd/D8G49QMBM/`

This one works for me

```adb
emag.*##+js(json-prune-fetch-response, data, data.*.ads_ranker, propsToMatch, /recommendations/by-slot)
```

---

> However, the promoted items are not really ads, you could find double items (a "normal" item and a promoted one which is the same) => annoyance

Yeah, it happens with many online shops. Usually the ones with ads will come with UUID tracking paramters, for example

```
https://www.emag.ro/husa-pentru-samsung-galaxy-a54-tip-carte-skyddar-eco-view-leather-negru-kf2311456/pd/D26CB8MBM/?ref=sponsored_products_p_r_ov_5_1&provider=rec-ads&recid=recads_3_b8e2abe184e687d9c36ca8132a52c40128640a009c5ccda6222c6874cb9e33f1_1716798413&scenario_ID=3&aid=395f7a32-f1fa-11ee-a490-0229d980bfff&oid=118705452
```

I think if there's duplicated item (one with ads and one without ads), it's safer to remove than if that product only occurs once.

**Comment by mapx-** [comment]
instead the json filter does this work for you ?

`emag.*##.container:has([data-tracking-alias^="sponsored_products"])`

**Comment by ghost** [comment]
Getting the promoted section as well

<img width="1162" height="890" alt="Image" src="https://github.com/user-attachments/assets/ca3534eb-bf15-4185-a82f-4e040413a0f6" />
