### ISSUE TITLE
businesstoday.in: ads

### ISSUE THREAD

**Issue by Sym8** [uBlockOrigin/uAssets#23865]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.businesstoday.in/`

Similar issue which was completed few months back
https://github.com/uBlockOrigin/uAssets/issues/22833

### Category

ads

### Description

Leftover ad banner

### Other extensions used

Twp, tampermonkey, Google search fixer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-05-27-12-02-44-525_org mozilla firefox](https://github.com/uBlockOrigin/uAssets/assets/66876418/8d15585f-c338-4f44-bb11-5dd7209e8931)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 126
filterset (summary):
 network: 146585
 cosmetic: 104687
 scriptlet: 25622
 html: 2086
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29760-31, 1m
  ublock-cookies-adguard: 1202-15, 1m
  easylist-annoyances: 4646-68, 1m
  easylist-newsletters: 7474-24, 1m
  easylist-notifications: 3018-165, 1m
  ublock-annoyances: 5875-54, 1h.51m Δ
  IND-0: 13191-12, 1h.51m
 default:
  user-filters: 0-0, never
  ublock-filters: 38646-114, 1h.51m Δ
  ublock-badware: 8876-0, 1h.51m Δ
  ublock-privacy: 921-2, 1h.51m Δ
  ublock-unbreak: 2351-2, 1h.51m Δ
  ublock-quick-fixes: 163-68, 1h.51m Δ
  adguard-mobile: 9390-69, 1m
  easylist: 87299-234, 1h.51m Δ
  easyprivacy: 50983-74, 1h.51m Δ
  urlhaus-1: 13780-1, 1h.51m
  plowe-0: 3727-1234, 1m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1535 ms
 maxAssetCacheWait: 941 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  amazon-adsystem.com: 1
  chartbeat.com: 3
  clarity.ms: 1
  crazyegg.com: 2
  go-mpulse.net: 2
  google.com: 1
  googletagmanager.com: 3
  jwpcdn.com: 2
  jwpltx.com: 2
  pubmatic.com: 1
  scorecardresearch.com: 2
  taboola.com: 1
  tosshub.com: 2
  webengage.com: 2
 extended:
  ##.inner-ad-section
  ##.ad-300X250-body
  ##.ad-300X250
  ###credential_picker_iframe
  ##.secondAdPosition
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in the old threads. All volunteers are notified with new comments.
