### ISSUE TITLE
gv.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#23871]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.gv.com/
```

### Description

annoying slow custom scroll

### Other extensions used

uMatrix, Decentraleyes, Cookie AutoDelete, Violentmonkey, YouTube Auto HD + FPS, SponsorBlock, Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
You can use this as a custom filter

```adb
gv.com##+js(aeld, /scroll|wheel/)
```

I don't think it should be added to uAssets lists.

**Comment by lunaflight** [comment]
also **gv.com: nuisance**, but different problem, with **paste blockage**:

```
https://www.gv.com.sg/GVSeatSelection#/cinemaId/051/filmCode/4431/showDate/05-02-2026/showTime/1600/hallNumber/1
``` 
or simply `https://www.gv.com.sg/GVMovies` and click any movie and time slot

1. click any seat
2. click the standard price ticket
3. click credit & debit card

<img width="1123" height="911" alt="Image" src="https://github.com/user-attachments/assets/42504496-5d5f-48bd-b61e-a07fe753f403" />

4. proceed with payment
5. input whatever payment information passes, i used the following:
```
Name
a
Mobile No
61234567
Email
x@x.com
```

6. try to paste in `1` or any number into any of the fields here

<img width="1141" height="459" alt="Image" src="https://github.com/user-attachments/assets/84b6faae-54c4-4945-9a90-806073ea6a0c" />

**paste is blocked, so it fails**

firefox 146

<details>
uBlock Origin: 1.69.0
Firefox: 146
filterset (summary):
 network: 314114
 cosmetic: 113651
 scriptlet: 38946
 html: 3292
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://raw.githubusercontent.com/gijsdev/ublock-hide-yt-shorts/master/list.txt: 28-0, 33d.15h.12m
  adguard-spyware-url: 2420-136, 5d.12h.22m
  curben-phishing: 145014-56, 9h.16m
  fanboy-thirdparty_social: 69-0, 1d.3h.53m
  fanboy-cookiemonster: 45235-106, 23h.44m
  fanboy-social: 17307-26, 4d.4h.10m
  ublock-annoyances: 4626-14, 2h.17m Δ
  easylist-annoyances: 5035-48, 23h.45m
  easylist-chat: 258-0, 23h.46m
  easylist-newsletters: 9014-37, 23h.46m
  easylist-notifications: 2461-170, 23h.46m
  ublock-cookies-easylist: 5423-40, 23h.44m
  [2 lists not shown]: [too many]
 default:
  user-filters: 27-0, never
  ublock-filters: 44373-89, 2h.17m Δ
  ublock-badware: 10806-31, 2h.17m Δ
  ublock-privacy: 3602-2, 2h.17m Δ
  ublock-unbreak: 2789-0, 2h.17m Δ
  ublock-quick-fixes: 438-0, 2h.17m Δ
  easylist: 90003-155, 2h.17m Δ
  easyprivacy: 55339-47, 2h.17m Δ
  urlhaus-1: 26595-6, 9h.16m
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2950 ms (selfie)
 maxAssetCacheWait: 1483 ms
 cacheBackend: indexedDB
</details>

**Comment by stephenhawk8054** [comment]
For security-related copy paste nuisances, we won't address them: https://github.com/uBlockOrigin/uAssets/issues/13017#issuecomment-1113341426

**Comment by lunaflight** [comment]
This is a self-ad, but it's still a pop-up, so I think this is a nuisance too:

Upon accessing `https://www.gv.com.sg/`, a pop up will show up for 5 seconds or something before closing by itself. The movie represented in the advertisement changes regularly. I think this is a nuisance worthy of being blocked. 

<img width="1919" height="1059" alt="Image" src="https://github.com/user-attachments/assets/affaba96-a281-4c94-8ca5-38e9cd9054ed" />

**Comment by Sonic5435325** [comment]
You can fix that with `gv.com.sg###dataProtectionDiv2`

**Comment by stephenhawk8054** [comment]
Report to EL: https://github.com/easylist/easylist/issues/
