### ISSUE TITLE
[nsfw] porno-baguette.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#23875]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.porno-baguette.com/fr/videos/show/539/partouze-sulfureuse-pour-cheyenne-kyara-et-aude-trois-jolies-coquines.html`

### Category

ads, banners, layers

### Description

This French site is full of ads, both on the page and on the player. I trust your team to clean it up 👍🏻

### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 176728
 cosmetic: 156865
 scriptlet: 29293
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1081-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, now
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51076-12092, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-6, now
  adguard-cookies: 29781-1648, now
  ublock-cookies-adguard: 1166-1166, now
  fanboy-cookiemonster: 51076-51076, now
  ublock-cookies-easylist: 1166-0, now
  RUS-0: 39508-261, now
 default:
  user-filters: 15-6, never
  ublock-filters: 38227-107, now
  ublock-badware: 8928-0, now
  ublock-privacy: 946-0, now
  ublock-unbreak: 2292-2, now
  ublock-quick-fixes: 158-63, now
  easylist: 87280-713, now
  easyprivacy: 50984-974, now
  urlhaus-1: 13745-0, now
  plowe-0: 3727-0, now
  FRA-0: 24601-385, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 135 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cdctwm.com: 1
  easysexe.com: 1
  googletagmanager.com: 1
  tawenda-tech.org: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
||gankana.com^
porno-baguette.com##.daily-premium
porno-baguette.com##.get-premium
porno-baguette.com##.espace-cam
porno-baguette.com##.grid-layout__col:has(> .video-item--zeder)
porno-baguette.com##[data-popunder-enabled]:remove-attr(data-popunder-enabled)
porno-baguette.com##+js(set-cookie, dscl, 1)
```

**Comment by dportvine** [comment]
I have one popup, devtools are closed while testing, clear cookies.

<details>
<summary>Screen</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/6adc3792-ea38-47ad-8345-c4422d61acaa
</details>

**Comment by stephenhawk8054** [comment]
@dportvine Does this work?

```adb
porno-baguette.com##+js(ra, data-popunder-enabled, [data-popunder-enabled])
```

**Comment by dportvine** [comment]
> Does this work?
> 
> ```
> porno-baguette.com##+js(ra, data-popunder-enabled, [data-popunder-enabled])
> ```

No, works for me only `porno-baguette.com##+js(set-cookie, ppndr, 1)`
