### ISSUE TITLE
zalbik.com: detection

### ISSUE THREAD

**Issue by srjoee** [uBlockOrigin/uAssets#23876]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://zalbik.com/grounded-game-review-a-new-survival-experience`

### Category

detection

### Description

"Please disable Adblock to continue" message appears in the shortener.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/164597834/b3de8968-a3b6-4d6d-b40a-871e50d253da)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 138939
 cosmetic: 53198
 scriptlet: 21349
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38126-350, 19m
  ublock-badware: 8928-0, 19m
  ublock-privacy: 924-0, 19m
  ublock-unbreak: 2291-2, 19m
  ublock-quick-fixes: 158-0, 19m
  easylist: 87288-610, 19m
  easyprivacy: 50984-822, 19m
  urlhaus-1: 13430-0, 19m
  plowe-0: 3727-0, 19m
  spa-0: 4064-3, 19m
  spa-1: 5695-187, 19m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1681 ms
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  d1u5ibtsigyagv.cloudfront.net: 1
  demand.supply: 1
  googletagmanager.com: 1
  scarcerpokomoo.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Give the original link to this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361
