### ISSUE TITLE
gamesradar.com: breakage

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#23879]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gamesradar.com/uk/`

### Category

breakage

### Description

The video part shown in the screenshot does not load.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![sshot](https://github.com/uBlockOrigin/uAssets/assets/51531027/0714a499-a081-48fd-99ab-08e93702d5c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 152623
 cosmetic: 159983
 scriptlet: 35035
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1702-7, 1m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 1h.50m
  adguard-cookies: 29789-62, 46m
  adguard-other-annoyances: 14384-351, 46m
  easylist-annoyances: 4646-95, 46m
  easylist-notifications: 3017-3, 46m
  fanboy-cookiemonster: 51079-3947, 46m
  fanboy-social: 16215-20, 1m
  fanboy-thirdparty_social: 68-0, 1m
  ublock-annoyances: 5911-24, 46m
  ublock-cookies-adguard: 1166-0, 46m
  ublock-quick-fixes: 158-0, 46m Δ
 default:
  TUR-0: 13439-13, 46m
  easylist: 87296-617, 1h.50m Δ
  easyprivacy: 50987-1130, 1h.50m Δ
  plowe-0: 3727-1, 1m
  ublock-badware: 8945-4, 46m
  ublock-filters: 38228-596, 46m
  ublock-privacy: 948-8, 46m
  ublock-unbreak: 2292-6, 46m Δ
  urlhaus-1: 13430-0, 1m
filterset (user): [array of 1869 redacted]
trustedset:
 added: [array of 24 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 706 ms (selfie)
 maxAssetCacheWait: 129 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  gamesradar.com: 1
  dotmetrics.net: 1
  futurecdn.net: 1
  futureplc.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  jwplayer.com: 6
  parsely.com: 1
  privacy-mgmt.com: 1
  scorecardresearch.com: 1
 extended:
  ##.instagram-icon
  ##.dfp-leaderboard-container
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.widget-ads
  ##.sponsored-post
  #@#.ad-unit
  ##+js(abort-on-property-write, _sp_)
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
||jwplayer.com^$domain=americansongwriter.com|dexerto.com|gamesradar.com|ginx.tv|imfdb.org|infoworld.com|kiplinger.com|soulbounce.com|spokesman-recorder.com|tennis.com|thestreet.com|tomshardware.com|variety.com|whathifi.com
||bordeaux.futurecdn.net^
```

in EL

@ryanbr
