### ISSUE TITLE
pronews.gr: ads

### ISSUE THREAD

**Issue by apostoliskr** [uBlockOrigin/uAssets#23872]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pronews.gr/`

### Category

ads

### Description

ads

### Other extensions used

dark reader,simple translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137316
 cosmetic: 47094
 scriptlet: 19534
 html: 1825
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38270-112, 1h.15m Δ
  ublock-badware: 8930-0, 1h.15m Δ
  ublock-privacy: 943-2, 1h.15m Δ
  ublock-unbreak: 2349-2, 1h.15m Δ
  ublock-quick-fixes: 163-68, 1h.15m Δ
  easylist: 87297-166, 1h.15m Δ
  easyprivacy: 50984-64, 1h.15m Δ
  urlhaus-1: 13745-1, now
  plowe-0: 3727-1159, now
  GRC-0: 1095-8, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 48 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  agorahtag.tech: 2
  becdn.net: 2
  doubleclick.net: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  kaspersky-labs.com: 2
  mrf.io: 1
  onesignal.com: 1
  pabidding.io: 2
  vidverto.io: 1
 extended:
  ###stickyad
  ##.header-ad
  ##.adunit
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot and point to where the ads are?

**Comment by apostoliskr** [comment]
Στις Τρί 28 Μαΐ 2024 στις 5:47 π.μ., ο/η stephenhawk8054 <
***@***.***> έγραψε:

**Comment by stephenhawk8054** [comment]
Please comment directly on github. Don't comment via email.

**Comment by JobcenterTycoon** [comment]
From the duplicate

<details>
<summary>Screenshot(s)</summary>






![1716913095472](https://github.com/uBlockOrigin/uAssets/assets/170970054/dc171f6a-4bc5-485e-85fb-cc5e19b309e6)

![1716913095463](https://github.com/uBlockOrigin/uAssets/assets/170970054/aefc6855-456f-4185-aa91-71c89c19f0d9)
![Uploading 1716913095466.jpg…]()


![1716913095469](https://github.com/uBlockOrigin/uAssets/assets/170970054/403d5b13-5c52-4abc-bb79-e33c3d99ea2d)
![Uploading 1716913095475.jpg…]()

</details>
