### ISSUE TITLE
fuse-box.info: breakage

### ISSUE THREAD

**Issue by lorddoskias** [uBlockOrigin/uAssets#23878]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fuse-box.info/audi`

### Category

breakage

### Description

When uBO is enabled and the site is opened once cannot see the category of Audi cars, once uBO is disabled the site function correctly but it also shows all the ads. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBO enabled : 

![image](https://github.com/uBlockOrigin/uAssets/assets/1756931/79c6ec9d-c8b4-4a52-ba69-5e72d23069d7)

With uBO disabled:

![image](https://github.com/uBlockOrigin/uAssets/assets/1756931/5fd5859b-4551-4999-b5a7-bf73d38d9227)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 119
filterset (summary):
 network: 137247
 cosmetic: 46965
 scriptlet: 20989
 html: 0
listset (total-discarded, last-updated):
 added:
  BGR-0: 1040-1, now
 default:
  user-filters: 5-0, never
  easylist: 87296-556, 45m Δ
  easyprivacy: 50987-3, 45m Δ
  plowe-0: 3727-786, now
  ublock-badware: 8945-0, 45m Δ
  ublock-filters: 38228-335, 45m Δ
  ublock-privacy: 948-3, 45m Δ
  ublock-quick-fixes: 158-0, 45m Δ
  ublock-unbreak: 2292-18, 45m Δ
  urlhaus-1: 13430-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 217 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  bannerflow.net: 2
  google-analytics.com: 1
  googlesyndication.com: 10
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##.ads-row
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
fuse-box.info#@#.ads-row
```

@ryanbr
