### ISSUE TITLE
icons8.com: ads

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#23870]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://icons8.com/icon/set/computer-hardware/fluency`

### Category

ads

### Description

Webpage shows on-site ads. Attempting to close them normally spawns a popup for the site's premium subscription.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/93544652/cef82771-9d62-465b-8732-d699e3b6da79)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 139002
 cosmetic: 73059
 scriptlet: 22193
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29773-34, now
 default:
  user-filters: 80-0, never
  easylist: 87297-557, now
  easyprivacy: 50984-791, now
  plowe-0: 3727-0, now
  ublock-badware: 8928-0, now
  ublock-filters: 38213-335, now
  ublock-privacy: 946-0, now
  ublock-quick-fixes: 158-0, now
  ublock-unbreak: 2292-18, now
  urlhaus-1: 13745-1, now
filterset (user): [array of 82 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  icons8.com: 4
  7eer.net: 1
  buysellads.com: 1
  carbonads.com: 1
  googletagmanager.com: 1
  tapfiliate.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
icons8.com##.carbon-card-ad__loader
```

@ryanbr

**Comment by Zephiii** [comment]
> `icons8.com##.carbon-card-ad__loader`

This still shows the top and bottom banners.

**Comment by stephenhawk8054** [comment]
I only see the one at the middle of the page

```adb
icons8.com##.ads
```

---

The ones at the top and bottom are self-promotions.

**Comment by Zephiii** [comment]
> The ones at the top and bottom are self-promotions.

Still count as ads, they're just advertising their own shit.
