### ISSUE TITLE
france.tv: detection

### ISSUE THREAD

**Issue by Tom4tot** [uBlockOrigin/uAssets#23888]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.france.tv/
https://www.france.tv/sport/tennis/roland-garros
```

### Description

The video player because uBlock is detected

### Other extensions used

I still don't care about cookies, although it's not affecting the issue (I tried disabling it)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-28 at 21-39-38 Le direct TV du 28 mai](https://github.com/uBlockOrigin/uAssets/assets/32274750/10ed3af5-79de-49bb-91e9-370953f73fb6)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 136889
 cosmetic: 46449
 scriptlet: 19504
 html: 1825
listset (total-discarded, last-updated):
 default:
  user-filters: 16-0, never
  ublock-filters: 38284-128, 1h.50m Δ
  ublock-badware: 8951-0, 1h.50m Δ
  ublock-privacy: 910-2, 1h.50m Δ
  ublock-unbreak: 2349-0, 1h.50m Δ
  ublock-quick-fixes: 96-0, 1h.50m Δ
  easylist: 87280-166, 1h.50m Δ
  easyprivacy: 50984-64, 1h.50m Δ
  urlhaus-1: 13745-1, 22h.49m
  plowe-0: 3725-1159, 2d.23h.32m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 97 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
Enable `AdGuard Français` list and test again.
