### ISSUE TITLE
toolnation.nl: breakage

### ISSUE THREAD

**Issue by Yggdrasil** [uBlockOrigin/uAssets#23889]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.toolnation.nl/`

### Category

breakage

### Description

The search bar at the top of the page doesn't work. Text typed in the bar should auto-search and show the products below the bar.

Disabling uBlockOrigin for this site and reloading the page fixes the search bar.

### Other extensions used

- Bitwarden
- Picture in Picture
- LastPass
- Privacy Badger (disabled for this site)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 124
filterset (summary):
 network: 138134
 cosmetic: 48155
 scriptlet: 20963
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  NLD-0: 2296-38, now
  easylist: 87239-557, 21m Δ
  easyprivacy: 50988-810, 21m Δ
  plowe-0: 3727-0, now
  ublock-badware: 8949-0, 21m Δ
  ublock-filters: 38189-280, 21m Δ
  ublock-privacy: 913-0, 21m Δ
  ublock-quick-fixes: 91-0, 21m Δ
  ublock-unbreak: 2292-0, 21m Δ
  urlhaus-1: 14405-0, now
filterset (user): [empty]
trustedset:
 added: [array of 45 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 379 ms (selfie)
 maxAssetCacheWait: 235 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  convertexperiments.com: 1
  googletagmanager.com: 1
  msecnd.net: 1
  sooqr.com: 1
  trustedshops.com: 1
  typekit.net: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||sooqr.com^$third-party` in EP

```adb
@@||sooqr.com^$domain=toolnation.nl
```

@ryanbr

**Comment by stephenhawk8054** [comment]
@ryanbr Search is still broken with `||sooqr.com/sooqr.js`
