### ISSUE TITLE
[Annoyance] GreasyFork Promoted Script

### ISSUE THREAD

**Issue by kowith337** [uBlockOrigin/uAssets#2388]
### URL(s) where the issue occurs
Any user script details on GreasyFork, for example.
`https://greasyfork.org/en/scripts/7596`

### Describe the issue
The site will show promoted script after you've pressed "Install this script"

### Screenshot(s)
![image](https://user-images.githubusercontent.com/16535467/40585471-77ba5f2c-61dd-11e8-97ec-8e4bb9f08b16.png)

### Versions

- Browser/version: Chromium [NoSync](https://chromium.woolyss.com/#windows-64-bit) 68.0.3424.0
- uBlock Origin version: 1.16.9b0

### Settings
Nearly everything default except
- Enable `uBlock filters - Annoyance`
- Have installed Violent Monkey, but didn't install any scripts.

### Notes
- Can be blocked by `###install-area .post-install`

- Sometime it's still show "Promoted script" pane, even have early blocked exactly DOM element, but it's 
rare case and hard to reproduce.
For that reason, I've ended up by add custom `:style()` and use it for myself.

- Also, I've found it's also sent XHR ping when click to install script, this should be allow?
![image](https://user-images.githubusercontent.com/16535467/40585547-1bc41968-61df-11e8-8f76-1b504d2daa66.png)

**Comment by uBlock-user** [comment]
`greasyfork.org##.post-install`
