### ISSUE TITLE
hdblog.it: nuisance

### ISSUE THREAD

**Issue by ozne9876** [uBlockOrigin/uAssets#23885]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hdblog.it/mercato/articoli/n584132/elon-musk-vs-whatsapp-gestione-dati-sicurezza/`

### Category

nuisance

### Description

The cookie warning appears in photo 1. In photo 2 when I refuse a small banner appears in the lower left corner to manage cookies

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Photo 1](https://github.com/uBlockOrigin/uAssets/assets/157696146/0daece0e-6d32-4eaf-bc69-214ad10fdf4c)

![Photo 2](https://github.com/uBlockOrigin/uAssets/assets/157696146/c953cf36-625c-4201-82f9-7383461e29d0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 143417
 cosmetic: 102136
 scriptlet: 21692
 html: 1821
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1522-120, 7m
  adguard-social: 23143-48, 7m
  adguard-cookies: 29808-39, 7m
  ublock-cookies-adguard: 1166-14, 7m
 default:
  user-filters: 1-0, never
  ublock-filters: 38257-112, 13m Δ
  ublock-badware: 8951-0, 13m Δ
  ublock-privacy: 910-2, 13m Δ
  ublock-unbreak: 2349-2, 13m Δ
  ublock-quick-fixes: 96-9, 13m Δ
  easylist: 87239-166, 13m Δ
  easyprivacy: 50988-64, 13m Δ
  urlhaus-1: 14405-0, 7m
  plowe-0: 3727-1160, 7m
  ITA-0: 8429-36, 7m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 610 ms
 maxAssetCacheWait: 387 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  datafront.co: 1
  disqus.com: 3
  dvagh3p3rk8xj.cloudfront.net: 3
  googletagmanager.com: 1
  googletagservices.com: 1
  imrworldwide.com: 1
 extended:
  ##.ads_container_top
  ##.ads_block
  ##.leftsharebtn
  ###banner3_300600
  ##.box_highlight_footer
  ##.share__button
  ###thread-share-bar
  ##.comment__share > *
```
</details>

**Comment by mapx-** [comment]
- already fixed by easylist cookie notices / adguard cookie notices
- update your filter lists

**Comment by mapx-** [comment]
- all these cookies / sites are fixed in easylist cookies 
- you can subscribe that list or add as custom filter:

`||inmobi.com^$3p`
