### ISSUE TITLE
lesechos.fr: ads

### ISSUE THREAD

**Issue by M0lyk** [uBlockOrigin/uAssets#23891]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lesechos.fr/tech-medias/hightech/sfr-a-perdu-un-demi-million-dabonnes-sur-le-mobile-en-3-mois-2097646`

### Category

3 ad inserts by page

### Description

I think I did the various tests correctly before making a claim. In the different configurations I still have these 3 empty advertising inserts on the page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-05-29 09_40_18-SFR a perdu un demi-million d'abonnés sur le mobile en 3 mois _ Les Echos — Mozi](https://github.com/uBlockOrigin/uAssets/assets/1733940/5ccc01ba-41ad-4555-b8af-a8e6d09dd49b)

![2024-05-29 09_40_40-SFR a perdu un demi-million d'abonnés sur le mobile en 3 mois _ Les Echos — Mozi](https://github.com/uBlockOrigin/uAssets/assets/1733940/79f4b42a-9514-47c7-bd9d-0ff13bb7a730)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 1874568
 cosmetic: 260314
 scriptlet: 51404
 html: 2083
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79515-466, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://mkb2091.github.io/blockconvert/output/adblock.txt: 1728263-282, now
  https://raw.githubusercontent.com/easylist/listefr/master/liste_fr.txt: 23265-3379, now
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-2020, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99411-23370, now
  adguard-generic: 81057-7272, now
  adguard-mobile: 9410-769, now
  adguard-spyware-url: 1522-120, now
  adguard-spyware: 72265-35111, now
  block-lan: 67-0, now
  curben-phishing: 548-1, now
  [16 lists not shown]: [too many]
 default:
  user-filters: 950-2, never
  ublock-filters: 38303-112, now
  ublock-badware: 8974-681, now
  ublock-privacy: 912-51, now
  ublock-unbreak: 2349-9, now
  ublock-quick-fixes: 97-14, now
  easylist: 87203-27056, now
  easyprivacy: 50987-42039, now
  urlhaus-1: 13545-88, now
  plowe-0: 3727-3605, now
  FRA-0: 24612-22920, now
filterset (user): [array of 949 redacted]
trustedset:
 added: [array of 679 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 6 redacted]
hostRuleset:
 added: [array of 4379 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 9581 ms
 maxAssetCacheWait: 3932 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  privacy-center.org: 1
  sdv.fr: 12
 extended:
  ###app > footer + div
```
</details>

**Comment by Tom4tot** [comment]
![Screenshot 2024-05-29 at 10-29-48 SFR a perdu un demi-million d'abonnés sur le mobile en 3 mois](https://github.com/uBlockOrigin/uAssets/assets/32274750/414a10c0-1ccc-4e79-b298-760532a01a6a)

Can confirm, I also have the empty spaces

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings + `AdGuard Français` list

**Comment by Tom4tot** [comment]
> Test again in a new Firefox profile with only uBO and its default settings + `AdGuard Français` list

The issue is solved this way, but "Enhanced tracking protection" from Firefox needs to be disabled too. Thank you.

**Comment by M0lyk** [comment]
> Test again in a new Firefox profile with only uBO and its default settings + `AdGuard Français` list

Hi,
I don't know, if I just do that, I get the same result.

**Comment by stephenhawk8054** [comment]
@M0lyk Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by M0lyk** [comment]
Yes, Firefox 126.0.1 on W11, New profile created, UBO added,
No any other configuration,
Back to the url, this is the result :

thank you

`uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 154007
 cosmetic: 52932
 scriptlet: 19672
 html: 1821
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38303-112, 15m
  ublock-badware: 8974-0, 15m
  ublock-privacy: 912-2, 15m
  ublock-unbreak: 2349-2, now Δ
  ublock-quick-fixes: 97-14, 15m
  easylist: 87203-167, 15m
  easyprivacy: 50987-64, now Δ
  urlhaus-1: 13545-0, 15m
  plowe-0: 3727-1159, 15m
  FRA-0: 24612-522, 15m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 926 ms
 maxAssetCacheWait: 352 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  sascdn.com: 1
 extended:
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…`

**Comment by stephenhawk8054** [comment]
Are you logged in to the site?

**Comment by M0lyk** [comment]
No I don't have an account on this site.

![2024-05-29 13_00_37-](https://github.com/uBlockOrigin/uAssets/assets/1733940/54611b03-ac7e-4247-8c0f-e501472d2c1c)

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
lesechos.fr##span[shape="circle"] + span:has-text(Publicité):upward(2)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Tom4tot** [comment]
> No I don't have an account on this site.
> 
> ![2024-05-29 13_00_37-](https://private-user-images.githubusercontent.com/1733940/334772334-54611b03-ac7e-4247-8c0f-e501472d2c1c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODA5ODcsIm5iZiI6MTcxNjk4MDY4NywicGF0aCI6Ii8xNzMzOTQwLzMzNDc3MjMzNC01NDYxMWIwMy1hYzdlLTQyNDctOGMwZi1lNTAxNDcyZDJjMWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMTEwNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JmNTU4MWNlOGM1ODAzYTYxYjMwZWNjZjRiZDdlMzkzZTE3ZGVkMjg0MGQ3YzVjZWY2N2U1ODk0MTBkY2JiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d6ctATwnOSrBYmePzYy18R0EUy4Uzfr8COD9bGwbSgM)

If that can help, the ad frames only disappear after accepting cookies "tout accepter".

**Comment by M0lyk** [comment]
> If that can help, the ad frames only disappear after accepting cookies "tout accepter".

I never click on Tout accepter 🫣



> Can you test this filter?
> 
> ```
> lesechos.fr##span[shape="circle"] + span:has-text(Publicité):upward(2)
> ```
It works very well. Thank you very much 👍

Solved

**Comment by stephenhawk8054** [comment]
@Yuki2718 For `AdGuard Français`? I can't craft better filters since there's no other attributes when not accepting cookies.
