### ISSUE TITLE
app.sigmacomputing.com: breakage

### ISSUE THREAD

**Issue by cmcapellan** [uBlockOrigin/uAssets#23898]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.sigmacomputing.com/`

### Category

breakage

### Description

The website is a data viz tool like Tableau or Plotly. The page slows down and becomes unusable after a few minutes, each point and click to change a filter or sorting on a table (looks a lot like Excel), for example, takes several seconds. We notice in the Edge (Chredge) task manager it is using anywhere from 20% to 50% more RAM for the tab process than usual. When the uBlock is disabled the issue does not appear to manifest.

### Other extensions used

LastPass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 136781
 cosmetic: 46434
 scriptlet: 20957
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 87203-555, now
  easyprivacy: 50990-809, now
  plowe-0: 3727-0, now
  ublock-badware: 8972-0, now
  ublock-filters: 38225-280, now
  ublock-privacy: 915-0, now
  ublock-quick-fixes: 92-0, now
  ublock-unbreak: 2298-0, now
  urlhaus-1: 13545-0, 8m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 93 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5467 ms (selfie)
 maxAssetCacheWait: 4386 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
@cmcapellan 
we need an account to check your issue. Are you willing to provide it to us ? (I'll provide an email address where you can send user / pass in case you agree)

more: we need also all the steps to reproduce the issue

**Comment by cmcapellan** [comment]
Hi @mapx- unfortunately this site uses SSO. Could we do a Zoom/Teams session? The simplest course of action may be to add to trusted sites.

**Comment by cmcapellan** [comment]
@stephenhawk8054 the slowdown happens when we load one of the dashboards we built, unfortunately it touches our internal data and we can't share it.

@mapx- I grabbed the exclusions and redacted some IDs in the URLs, pasting in the next comment.

**Comment by cmcapellan** [comment]
+75
||api-iam.intercom.io/messenger/web/metrics
--
app.sigmacomputing.com
3
post
xhr
https://api-iam.intercom.io/messenger/web/metrics

+66
||sentry.io^$3p
--
app.sigmacomputing.com
3
post
xhr
https://sentry.io/api/157435/envelope/?sentry_key=<SENTRY_KEY>&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.82.0

+8
||sentry.io^$3p
--
app.sigmacomputing.com
3
post
xhr
https://sentry.io/api/157435/envelope/?sentry_key=<SENTRY_KEY>&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.82.0

+6
*$document,permissions=browsing-topics=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=compute-pressure=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=idle-detection=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=join-ad-interest-group=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=private-state-token-issuance=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=private-state-token-redemption=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=run-ad-auction=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+6
*$document,permissions=attribution-reporting=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+5
https://app.sigmacomputing.com/<CORPNAME>/finish-login/<SIGMA_GUID>?uid=<UID>&email=<USER>%40<DOMAIN>.com&organizationId=<ORG_ID>&exp=2591999&isNewSignup=false

+5
*$document,permissions=browsing-topics=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=compute-pressure=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=idle-detection=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=join-ad-interest-group=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=private-state-token-issuance=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=private-state-token-redemption=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=run-ad-auction=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
*$document,permissions=attribution-reporting=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
aws-api.sigmacomputing.com
1
post
doc
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
https://aws-api.sigmacomputing.com/api/v2/saml2/assert

+5
||sentry.io^$3p
--
app.sigmacomputing.com
3,3
post
xhr
https://sentry.io/api/157435/envelope/?sentry_key=<SENTRY_KEY>&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.82.0

+5
*$document,permissions=browsing-topics=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=compute-pressure=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=idle-detection=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=join-ad-interest-group=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=private-state-token-issuance=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=private-state-token-redemption=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=run-ad-auction=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=attribution-reporting=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3a%2f%2fapp.sigmacomputing.com%2f<CORPNAME>%2ffinish-login%2<RELAYSTATE_ID>%253D&sso_nonce=<NONCE>&client-request-id=8ac59223-bf46-4eac-93e1-0e53964eaf11&mscrid=8ac59223-bf46-4eac-93e1-0e53964eaf11

+5
*$document,permissions=browsing-topics=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=compute-pressure=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=idle-detection=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=join-ad-interest-group=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=private-state-token-issuance=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=private-state-token-redemption=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=run-ad-auction=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+5
*$document,permissions=attribution-reporting=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
login.microsoftonline.com
1
get
doc
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+4
https://login.microsoftonline.com/<TENANT_ID>/saml2?SAMLRequest=<SAML_REQUEST>&RelayState=https%3A%2F%2Fapp.sigmacomputing.com%2F<CORPNAME>%2Ffinish-login%2<RELAYSTATE_ID>%253D

+2
||sentry.io^$3p
--
app.sigmacomputing.com
3
post
xhr
https://sentry.io/api/157435/envelope/?sentry_key=<SENTRY_KEY>&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.82.0

+0
*$document,permissions=browsing-topics=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=compute-pressure=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=idle-detection=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=join-ad-interest-group=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=private-state-token-issuance=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=private-state-token-redemption=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=run-ad-auction=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
*$document,permissions=attribution-reporting=(),from=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost
--
app.sigmacomputing.com
1
get
doc
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

+0
https://app.sigmacomputing.com/<CORPNAME>/workbook/<WORKBOOK_NAME>-7JsyocdF8nmlqS2BgqXvAR?:nodeId=givHKLoxiJ&:explore=22538eff-bf3a-4a92-bab2-c2392097e6de

**Comment by mapx-** [comment]
@cmcapellan 

disable this list and test again:
`uBlock filters – Privacy`

**Comment by cmcapellan** [comment]
@mapx- Still not better, here is the new log
[sigma2.txt](https://github.com/user-attachments/files/15596203/sigma2.txt)

**Comment by stephenhawk8054** [comment]
@cmcapellan Can you test this filter?

```adb
@@||sentry.io^$domain=app.sigmacomputing.com
```

**Comment by cmcapellan** [comment]
That's disappointing @ItsProfessional. I am working with a corp IT dept so can't turn these around so fast.

@stephenhawk8054 the filter seemed to make things worse, we saw RAM usage for the tab in the browser task manager climb to about 50% more

**Comment by mapx-** [comment]
@cmcapellan 

comment that last filter and try

`||api-iam.intercom.io/messenger/web/metrics$badfilter`

**Comment by stephenhawk8054** [comment]
Just continue commenting here even when the issue is closed. All volunteers are notified with new comments and will re-open when necessary.

**Comment by mapx-** [comment]
@cmcapellan comment here if you have any other feedback

**Comment by cmcapellan** [comment]
@mapx- tried the intercom filter, didn't help either. I think we are just going to add this to trusted sites unless there is something else worth trying.
