### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by Luusername** [uBlockOrigin/uAssets#23899]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.derstandard.at
```

### Description

blurry overlay

### Other extensions used

script blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![DERSTANDARD](https://github.com/uBlockOrigin/uAssets/assets/55045299/13697540-434b-452a-a7e7-03ffb2a7ede9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 116
filterset (summary):
 network: 139127
 cosmetic: 51520
 scriptlet: 20963
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 14-0, never
  DEU-0: 7469-3, 7h.44m
  easylist: 87203-564, 3h.44m Δ
  easyprivacy: 50987-818, 3h.44m Δ
  plowe-0: 3726-0, 10d.11h.37m
  ublock-badware: 8972-0, 3h.44m Δ
  ublock-filters: 38235-296, 3h.44m Δ
  ublock-privacy: 915-0, 3h.44m Δ
  ublock-quick-fixes: 92-0, 3h.44m Δ
  ublock-unbreak: 2292-0, 3h.44m Δ
  urlhaus-1: 13545-0, 7h.44m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10426 ms (selfie)
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
```
</details>

**Comment by D4niloMR** [comment]
Disable "script blocker" and test again.

**Comment by dportvine** [comment]
@Luusername 
>I have verified that other extensions are not causing the issue.

<details>
<summary>Screen</summary>

![2024-05-30_082253](https://github.com/uBlockOrigin/uAssets/assets/111344219/cc9d20ad-b66d-438e-811e-a818ef3c732a)
</details>
