### ISSUE TITLE
Mobile Nations websites

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#239]
### URL(s) where the issue occurs

http://www.androidcentral.com
http://www.windowscentral.com
http://www.crackberry.com

### Describe the issue

anti adb inline script blocks the page(s) from being accessed by the user

### Screenshot

https://i.gyazo.com/fdb105cd5db2b106a3f31c4f3f0a7619.png

### Versions

Browser/version: Chromium 57
uBlock Origin version: 1.10.4

### Settings

Default

### Notes

Works on detection of cosmetic filters, so disabling cosmetic filtering does help to bypass the anti adb wall.

**Comment by uBlock-user** [comment]
@gorhill Blocking inline scripts does the job too and the site isn't broken for the most part apparently.

**Comment by gorhill** [comment]
> anti adb inline script blocks users from accessing any page

There is a "Continue" button in there to dismiss the message, and the dismissal appears to be remembered.

**Comment by uBlock-user** [comment]
> There is a "Continue" button in there to dismiss the message,

So ? Lots of other websites also have that functionality, what about it ? FYI - The dismissal stays as long as the cookies are staying, clear the cookies and it will happen again.

**Comment by IDKwhattoputhere** [comment]
> So ?

So your statement that users are blocked from accessing the website is incorrect.

**Comment by uBlock-user** [comment]
I didn't say "permanently blocked", there's a difference, so it's not incorrect actually, maybe I should have said pages are blocked, instead of "users are blocked", that would have been suffice . Anyways, lets get back to the topic at hand now, shall we ?

**Comment by okiehsch** [comment]
The simplest solution is `example.com#@#.adunit`, works for all three websites
but that is an issue for Easylist maintainers.

**Comment by uBlock-user** [comment]
>The simplest solution is example.com#@#.adunit, works for all three websites

Not a solution, and I'm well aware of that already, that's just the whack-a-mole game waiting to played again and again. It will never end this way. The previous one before this yesterday was removed and got patched and it happened again today, that defeats the purpose, instead of using that, you might as well deactivate cosmetic filtering, if you're going to go that route. Also those filters were added because they were from ad banners and offers, which no longer exist as they got removed and are now being used to check for the presense of an adblocker.

**Comment by okiehsch** [comment]
Okay a more sophisticated solution
`example.com##script:inject(abort-on-property-write.js, NREUM)`
`example.com##script:inject(setTimeout-defuser.js, checkBlocked, 100)`
should also work on these sites.

**Comment by uBlock-user** [comment]
The second one works, thanks. Is `checkBlocked` a variable from the anti adblocking script ?

**Comment by okiehsch** [comment]
It works for you only using
`example.com##script:inject(setTimeout-defuser.js, checkBlocked, 100)`?

**Comment by uBlock-user** [comment]
Yes, the second one only works. The first had no effect, so I discarded the first and added the second and Voila!

**Comment by IDKwhattoputhere** [comment]
@uBlock-user You asked a question and I answered it for you. I don't know why you got upset.
It's a dismissible nag screen and not a blanket block like on Forbes and your statement in the first post sounds like you didn't notice that. It wasn't a personal attack or anything if you though that.

**Comment by uBlock-user** [comment]
@okiehsch The second one I mentioned works for all the aforementioned websites fyi. Thanks.

**Comment by uBlock-user** [comment]
Anti adblock script was updated and the aformentioned solution no longer works.

New filter - ##script:inject(setTimeout-defuser.js, e)

**Comment by uBlock-user** [comment]
Anti adblock script is at it's work again!

new Filter - androidcentral.com,windowscentral.com,crackberry.com,imore.com##script:inject(setTimeout-defuser.js, [native code])

**Comment by ghajini** [comment]
@gorhill, these are comments from seanl-adg for this issue from adblock protector page.....
If this needs addition to content script of unlock extra

seanl-adg comments

`Hi all,

It is similar to the case of IL, the quick Promise wrapper defuses admiral's detection logic.
Admiral's code performs various checks to detect adblockers, and each regular expressions is supposed to defuse a corresponding check. You see, the admiral's adblock detection code internally stores a value named hasAdblockerScore; by defusing, the value becomes 0.

You don't necessarily wrap Promise, I deem filtering setTimeout with [native code] ok, but you should provide the timeout number in order to make it safer.

Also, please note that site breakages including missing jQuery and broken buttons are completely unrelated to the blocker's javascript patches. They are broken due to EasyList's aggressive blocking rules.`
