### ISSUE TITLE
mtlarchive.com: ads

### ISSUE THREAD

**Issue by B3H3M0T** [uBlockOrigin/uAssets#23906]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mtlarchive.com/novel/shinigami-the-invincible-slacker-since-rukongai/chapter-4-perfect-zanpakuto`

### Category

ads

### Description

Some ads still showing.

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 126
filterset (summary):
 network: 138369
 cosmetic: 54492
 scriptlet: 19585
 html: 1822
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38686-113, 4m
  ublock-badware: 8971-1, 4m
  ublock-privacy: 913-2, 4m
  ublock-unbreak: 2359-2, 4m
  ublock-quick-fixes: 98-14, 4m
  adguard-mobile: 9410-69, 4m
  easylist: 87239-231, 4m
  easyprivacy: 50998-72, 4m
  urlhaus-1: 13755-0, 4m
  plowe-0: 3729-1233, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2892 ms
 maxAssetCacheWait: 225 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  phoenix-widget.com: 1
 extended:
  ##a[href^="https://a-ads.com/"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot and point to where the ads are?

**Comment by B3H3M0T** [comment]
It appear sometimes at bottom of page.

**Comment by stephenhawk8054** [comment]
I can't see any ads at the bottom of the page

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/eaefbbfc-2ceb-417e-844a-dc1a4e5e3a4e)
