### ISSUE TITLE
katfile.com: ads

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#23909]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://katfile.com/6bz2903oiu92/Act_42.0.4.zip.html`

### Category

ads

### Description

fake "Free Download" banner

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 138400
 cosmetic: 56632
 scriptlet: 22584
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13226-13, now
  easylist: 87233-559, now Δ
  easyprivacy: 50996-814, now Δ
  plowe-0: 3729-0, now
  ublock-badware: 8975-1, now Δ
  ublock-filters: 38225-290, now Δ
  ublock-privacy: 915-0, now Δ
  ublock-quick-fixes: 94-0, now Δ
  ublock-unbreak: 2298-0, now Δ
  urlhaus-1: 13755-0, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 285 ms (selfie)
 maxAssetCacheWait: 53 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##.ad-box:not(#ad-banner):not(:empty)
  ##+js(abort-current-script, document.createElement, onerror)
  ##+js(adjust-setTimeout)
  ##+js(no-window-open-if)
  ##+js(set-constant, adblock, false)
```
</details>

**Comment by hetiGH7402** [comment]
The domain katfile.com is changed to katfile.cloud. The filters therefore no longer have any effect.
All filters with katfile.com in "filters/filters-2024.txt" should therefore be changed to katfile.cloud.

If possible, maybe you, @stephenhawk8054 , could have a look at it and make the changes/update?

**Comment by RazorVA69** [comment]
`https://katfile.online/a5bmw3rgk8pr`
first page needs 3 clicks on slow download button and next page theres a fake download button

**Comment by dimisa-RUAdList** [comment]
Up! > `https://katfile.online/imvfhiwa99rl/Novella_Night_Trailer.mp4.html`
