### ISSUE TITLE
visortmo.com: breakage

### ISSUE THREAD

**Issue by alexisrazok** [uBlockOrigin/uAssets#23908]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://visortmo.com/`

### Category

breakage

### Description

The elements in the populars tab section are not displaying,
also, the latest news section is not displaying.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8698415/8ce110f0-af7b-48a2-a9bc-db5edc2a0108)
![image](https://github.com/uBlockOrigin/uAssets/assets/8698415/a9042996-5d29-4efb-b9b7-b93d61ac5c42)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 139406
 cosmetic: 53141
 scriptlet: 21400
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87263-610, 32m
  easyprivacy: 50998-822, 32m
  plowe-0: 3729-2, 32m
  spa-0: 4064-173, 32m
  spa-1: 5705-13, 24m
  ublock-badware: 8975-1, 32m
  ublock-filters: 38228-296, 32m
  ublock-privacy: 915-0, 32m
  ublock-quick-fixes: 93-0, 32m
  ublock-unbreak: 2299-4, 32m
  urlhaus-1: 13755-0, 32m
filterset (user): [empty]
trustedset:
 added: [array of 703 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1012 ms (selfie)
 maxAssetCacheWait: 608 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  guywireincorp.com: 1
  nakamasweb.com: 1
  outbrain.com: 1
  taboola.com: 1
 extended:
  ##div[id^="pills-populars"] > div.row > div.element:has(> a[href…
  ##body :not(div[class="col-4 mx-0 px-0"]:not([style])):has(> sty…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
visortmo.com#@#div[id^="pills-populars"] > div.row > div.element:has(> a[href^="https://visortmo.com/library/"] > .thumbnail:not(:has(> style)))
visortmo.com#@#div[id^="pills-populars"] > div.row > div.element:has(> a[href^="https://visortmo.com/library/"] > .thumbnail > style:contains(/\/images\/.*_push|\/ne?f_|_ext|::before[\s\S]*?background-image/))
visortmo.com#@#body :not(div[class="col-4 mx-0 px-0"]:not([style])):has(> style:contains(/pplr\d+_|n.?..?_|height[\s\S]*?opacity[\s\S]*?background-image/))

visortmo.com##a[href^="https://visortmo.com/library/manhwa/"]:has(> style)
```

@Yuki2718 Caused by `AdGuard Spanish/Portuguese`. Is it a site that constantly circumvents the filters? Maybe we can address it in quick.

**Comment by Yuki2718** [comment]
I don't know. @AdamWr

**Comment by AdamWr** [comment]
Yes, it's one of these websites which often change something to counter filters.
Regarding incorrect blocking, it should be fine already, if I didn't miss anything.

**Comment by alexisrazok** [comment]
It's not completed, a section of this website is not displaying currently:
![image](https://github.com/uBlockOrigin/uAssets/assets/8698415/5319ca61-49f3-4f9e-967b-3cee711b0747)

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
