### ISSUE TITLE
sacbee.com: nuisance

### ISSUE THREAD

**Issue by gutHookt** [uBlockOrigin/uAssets#23900]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sacbee.com/news/business/real-estate-news/article288836890.html`

### Category

nuisance

### Description

Subscription ad loads after a few seconds and blocks access to article content. UBlock was blocking this until a few weeks ago.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-05-29 121749](https://github.com/uBlockOrigin/uAssets/assets/171186166/ca16b590-1c9e-45fb-b7c1-67993f9ade76)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 220952
 cosmetic: 252648
 scriptlet: 52923
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81071-492, now
  adguard-mobile: 9410-167, now
  adguard-spyware-url: 1522-119, now
  adguard-spyware: 72269-30168, now
  curben-phishing: 553-0, now
  adguard-cookies: 29819-74, 1m
  ublock-cookies-adguard: 1166-0, 1m
  fanboy-cookiemonster: 51080-3980, 1m
  ublock-cookies-easylist: 1166-1166, 1m
  adguard-social: 23143-898, 1m
  fanboy-social: 16232-42, 1m
  fanboy-thirdparty_social: 68-0, 1m
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38225-3934, 1h.13m Δ
  ublock-badware: 8975-107, 1h.13m Δ
  ublock-privacy: 915-0, 1h.13m Δ
  ublock-unbreak: 2298-73, 1h.13m Δ
  ublock-quick-fixes: 94-0, 1h.13m Δ
  easylist: 87233-2719, 1h.13m Δ
  easyprivacy: 50996-1128, 1h.13m Δ
  urlhaus-1: 13680-0, now
  plowe-0: 3727-25, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 988 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 54
 network:
  sacbee.com: 4
  amplitude.com: 22
  braze.com: 1
  connatix.com: 2
  facebook.net: 1
  flowerstreatment.com: 1
  fullcontact.com: 1
  googletagmanager.com: 2
  htlbid.com: 2
  imrworldwide.com: 1
  keywee.co: 1
  liadm.com: 1
  matheranalytics.com: 1
  ml314.com: 2
  ntv.io: 1
  osano.com: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  stackadapt.com: 1
  taboola.com: 2
  trinitymedia.ai: 3
  tru.am: 1
  viafoura.co: 1
 extended:
  ##.footer-connect
  ##.facebook-share
  ##.twitter-share
  ##.email-share
  ###leaderboard-ad
  ##article [id^="zone-el"]
  ##.zone
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
```
</details>

**Comment by mapx-** [comment]
We do not fix paywalls

try using as custom filters

```
sacbee.com##mcc-paywall
sacbee.com##html:style(overflow: auto !important)
```
