### ISSUE TITLE
nttgame.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#23907]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nttgame.com/en/news`

### Category

nuisance

### Description

cookie notice

### Other extensions used

bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/153795294/eaa580d7-fa52-4476-8dfe-a5cb8c3f67bf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 140581
 cosmetic: 103157
 scriptlet: 30640
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51088-182, never
  ublock-annoyances: 5913-66, never
 default:
  user-filters: 0-0, never
  ublock-filters: 38229-290, now
  ublock-badware: 8989-1, now
  ublock-privacy: 915-0, now
  ublock-unbreak: 2303-0, now
  ublock-quick-fixes: 93-0, now
  easylist: 87219-559, now
  easyprivacy: 50998-814, now
  urlhaus-1: 13755-0, now
  plowe-0: 3729-0, now
  TUR-0: 13226-13, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4015 ms
 maxAssetCacheWait: 21 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
nttgame.com###modalCookie
nttgame.com###lean_overlay
```

@ryanbr
