### ISSUE TITLE
portal.saludii.com: breakage

### ISSUE THREAD

**Issue by matheusAle** [uBlockOrigin/uAssets#23904]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://portal.saludii.com
```

### Description

requests to Newrelic browser agent are been blocked `bam.nr-data.net` and `https://js-agent.newrelic.com/`

### Other extensions used

Apollo Dev Tools, React Dev Tools, Scribe

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/22581882/79178849-b2ac-49fa-85ca-ccba68d8e64b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 136932
 cosmetic: 46457
 scriptlet: 20957
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87233-555, 2h.39m Δ
  easyprivacy: 50996-809, 2h.39m Δ
  plowe-0: 3727-0, 1d.13m
  ublock-badware: 8975-1, 2h.39m Δ
  ublock-filters: 38225-280, 2h.39m Δ
  ublock-privacy: 915-0, 2h.39m Δ
  ublock-quick-fixes: 94-0, 2h.39m Δ
  ublock-unbreak: 2299-0, 2h.39m Δ
  urlhaus-1: 13680-0, 7h.39m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 711 ms (selfie)
 maxAssetCacheWait: 257 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
What is broken on the page when the requests are blocked?

**Comment by matheusAle** [comment]
Hey @stephenhawk8054 thks for replay

the page can't connect to newrelic to report js errors and other observability events.

**Comment by stephenhawk8054** [comment]
I mean, what is broken for **users**? Not the server not able to collect data, which is the point of the filters.
