### ISSUE TITLE
jsfiddle.net: detection

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#23911]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jsfiddle.net/uzMPU`

### Category

detection

### Description

Displays usual "please whitelist us!!!!!!" popup sometime after landing on the site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="889" alt="Screenshot 2024-05-30 at 21 13 53" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/e59096ba-7dc7-40ac-a980-0348fd1287e7">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 139218
 cosmetic: 72936
 scriptlet: 22147
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29774-35, now
 default:
  user-filters: 87-0, never
  easylist: 87259-559, now
  easyprivacy: 50998-809, now
  plowe-0: 3729-0, now
  ublock-badware: 8991-1, now
  ublock-filters: 38244-280, now
  ublock-privacy: 878-0, now
  ublock-quick-fixes: 94-0, now
  ublock-unbreak: 2304-0, now
  urlhaus-1: 13780-0, now
filterset (user): [array of 89 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  carbonads.com: 1
  googletagmanager.com: 1
  servedby-buysellads.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` list or add this as your custom filter

```adb
jsfiddle.net##+js(nostif, modal)
```

and test again.

**Comment by Potato22** [comment]
Updated all filters, along with `uBlock filters – Annoyances` and `jsfiddle.net##+js(nostif, modal)` enabled, still hit a detection. Seems like a 'new' implementation from their end.

<img width="872" height="806" alt="Image" src="https://github.com/user-attachments/assets/3f7f299a-f924-4b9d-8d7a-ebbdce6ba211" />
