### ISSUE TITLE
ebay.com: breakage

### ISSUE THREAD

**Issue by bogu88** [uBlockOrigin/uAssets#23913]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ebay.com/b/Asian-Antiques/20082/bn_1865025?LH_Sold=1&mag=1&rt=nc&_sop=16&_fcid=45`

### Category

breakage

### Description

Ebay sold items page displays the items for a split second then they disappear. Turning off UBO fixes the problem, and correctly shows the items. I tried it on 3 pcs and also a fresh install of firefox with only UBO, and all have the same issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![UBO on](https://github.com/uBlockOrigin/uAssets/assets/140277283/e6e98095-50e6-4594-b728-a275f2efdccd)
![UBO off](https://github.com/uBlockOrigin/uAssets/assets/140277283/d559588f-0524-4077-96f9-5694f7547a1c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 137118
 cosmetic: 46454
 scriptlet: 20934
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 27-0, never
  easylist: 87259-555, 5m
  easyprivacy: 50998-2, now
  plowe-0: 3729-786, 5m
  ublock-badware: 8991-1, now
  ublock-filters: 38244-280, 5m
  ublock-privacy: 878-3, now
  ublock-quick-fixes: 94-0, now
  ublock-unbreak: 2304-18, now
  urlhaus-1: 13780-0, 1h.1m
filterset (user): [array of 28 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 474 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  ebay.com: 2
  bluekai.com: 1
  ebaystatic.com: 2
 extended:
  ##div[title="ADVERTISEMENT"]
```
</details>

**Comment by JobcenterTycoon** [comment]
Ok the issue with the "sponsored" results is not important enough to risk more future breakage.
