### ISSUE TITLE
nos.nl: breakage

### ISSUE THREAD

**Issue by DutchEllie** [uBlockOrigin/uAssets#23910]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nos.nl/`

### Category

breakage

### Description

The "Geef ons feedback" (give us feedback) button at the bottom of the page doesn't work with uBlock Origin enabled (at least on Firefox) and if I disable uBlock Origin then it does work.

This is the button: 
![image](https://github.com/uBlockOrigin/uAssets/assets/6501187/231a0227-093e-46fc-8fe7-096a21a60b47)

### Other extensions used

https://github.com/uBlockOrigin/uAssets/assets/6501187/8e110bee-2306-49e1-a9ba-251b3e296b8e

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137038
 cosmetic: 46321
 scriptlet: 19526
 html: 1822
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 38305-112, now
  ublock-badware: 8992-1, now
  ublock-privacy: 912-2, now
  ublock-unbreak: 2360-2, now
  ublock-quick-fixes: 98-14, now
  easylist: 87227-167, now
  easyprivacy: 50998-64, now
  urlhaus-1: 13755-0, now
  plowe-0: 3729-1159, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2315 ms
 maxAssetCacheWait: 519 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  optoutadvertising.com: 1
  sentry.io: 3
  smartocto.com: 2
  usabilla.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||usabilla.com^$3p` in EP

```adb
@@||usabilla.com^$script,domain=nos.nl
```

@ryanbr
