### ISSUE TITLE
science-et-vie.com: detection

### ISSUE THREAD

**Issue by macmil20** [uBlockOrigin/uAssets#23916]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.science-et-vie.com/article-magazine/pourquoi-a-t-on-le-nez-qui-coule-quand-on-pleure`

### Category

detection

### Description

block

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image_2024-05-31_082502769](https://github.com/uBlockOrigin/uAssets/assets/64298504/ccc26c4f-3cca-4a82-aee9-cc08d130d655)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 109
filterset (summary):
 network: 165776
 cosmetic: 163289
 scriptlet: 34820
 html: 0
listset (total-discarded, last-updated):
 added:
  NLD-0: 2296-99, now
  adguard-cookies: 29835-1648, now
  adguard-mobile-app-banners: 5262-18, now
  adguard-other-annoyances: 14392-19, now
  adguard-popup-overlays: 27108-1722, now
  adguard-social: 23160-1327, now
  adguard-widgets: 2523-54, now
  easylist-annoyances: 4651-1053, now
  easylist-chat: 196-12, now
  easylist-newsletters: 7521-1886, now
  easylist-notifications: 3019-1640, now
  fanboy-cookiemonster: 51096-19861, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 9-5, never
  FRA-0: 24613-2980, now
  easylist: 87270-14707, 22m Δ
  easyprivacy: 50998-1153, 22m Δ
  plowe-0: 3729-53, now
  ublock-badware: 8996-17, 22m Δ
  ublock-filters: 38245-958, 22m Δ
  ublock-privacy: 878-1, 22m Δ
  ublock-quick-fixes: 87-0, 22m Δ
  ublock-unbreak: 2307-6, 22m Δ
  urlhaus-1: 13355-0, now
filterset (user): [array of 9 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4686 ms (selfie)
 maxAssetCacheWait: 647 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  batch.com: 1
  googletagmanager.com: 3
  pinterest.com: 1
  privacy-center.org: 1
 extended:
  ##.pub_dfp
```
</details>

**Comment by garry-ut99** [comment]
This is not adblock detection, the is a cookie/GDPR/privacy wall which says that some cookies have been declined:

> You have chosen to block cookies for audience measurement, personalized content and advertising targeting.
> I support the work of the editorial team, which offers a high-quality editorial service financed solely by advertising. Subscribe Reverse my choice and accept cookies Already a subscriber? Sign in


 they have been declined by cookie filters you enabled in uBlock: `EasyList/uBO/AdGuard – Cookie Notices`, if you disable cookie filters + clean cache & cookies + manually accept cookie/GDPR message , you will not see this message anymore, but instead you will still see a different pay-wall which says to subcribe to Premium to continue reading the article.

> This article is reserved for our subscribers
> To read more, choose one of our subscription offers:
> 2 €/month Digital Subscribe
> 3 €/month Paper & digital Subscribe
> Already subscribed or registered? I connect

**Comment by mapx-** [comment]
We don't fix paywalls.

try adding as custom filter:
`||qiota.com^$3p`
