### ISSUE TITLE
tornadomovies.to

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2391]
### URL(s) where the issue occurs

`https://www1.tornadomovies.to/movie/death-wish-2018/YNlYQ8tC-watching.html`

### Describe the issue

Pre-video playing ad is displayed.

Video player selection of "Openload" Instead of "Server 1" or "Server 2" shows another ad in the middle of the video player.

### Screenshot(s)

![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40591815-b7345c84-620f-11e8-8eca-cd27f14f1689.jpg)
![screenshot-2018-5-20-2](https://user-images.githubusercontent.com/12204587/40591816-b74b976e-620f-11e8-95c3-e3440a28f188.jpg)

### Versions

- Browser/version: Firefox Quantum Latest.
- uBlock Origin version: Latest.

### Settings

Default.

### Notes

Just switching the player between server 1 server 2 and openload video options under the video player seems to be where these missed ads appear.

**Comment by C0nw0nk** [comment]
@mapx- so nobody is going to add this to the list :( ?

**Comment by mapx-** [comment]
for such (simple - non specific uBo) filters you should report them to easylist repository

@ryanbr @Khrin

**Comment by C0nw0nk** [comment]
@mapx- 

Hey mapx thanks for the help before could you be so kind to help again this site has some invideo ads that auto play and allot of upgrade to premium messages and banners and urls that appear.

```
tornadomovies.co/user/premiumlogin
```

**Comment by mapx-** [comment]
example (blocked) video ?

**Comment by C0nw0nk** [comment]
```
https://www1.tornadomovies.co/movie/avengers-infinity-war/zggaiCbo/S8sU9rWW-watching.html
```

Openload should be the video player it says what video player your using under the video box itself. Server 1, Server 2 or Openload

But openload just gives a black screen and checking ublock logs says this.

![image](https://user-images.githubusercontent.com/12204587/51475710-1a3e8a80-1d7b-11e9-8013-c1d35f972a5c.png)

**Comment by mapx-** [comment]
`@@||openload.*/embed/$frame,domain=tornadomovies.co` should work
