### ISSUE TITLE
allmusic.com: breakage

### ISSUE THREAD

**Issue by carstenknoch** [uBlockOrigin/uAssets#23919]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.allmusic.com/artist/talking-heads-mn0000131650`

### Category

breakage

### Description

Blocks actual content blocks in allmusic.com discography pages

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 162431
 cosmetic: 126686
 scriptlet: 25732
 html: 0
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51097-9451, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-6, now
  DEU-0: 7470-4, now
  FRA-0: 24613-394, now
  NLD-0: 2296-38, now
  fanboy-thirdparty_social: 68-0, now
  spa-0: 4064-3, now
  spa-1: 5706-185, now
 default:
  user-filters: 15-0, never
  easylist: 87267-762, now
  easyprivacy: 50998-734, now
  plowe-0: 3627-0, now
  ublock-badware: 9001-1, now
  ublock-filters: 38285-378, now
  ublock-privacy: 923-0, now
  ublock-quick-fixes: 81-0, now
  ublock-unbreak: 2309-6, now
  urlhaus-1: 13395-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 32 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 740 ms
 maxAssetCacheWait: 233 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  360playvid.info: 1
  d3lcz8vpax4lo2.cloudfront.net: 1
  googletagmanager.com: 1
  tunefindforfans.com: 1
  verdantlabyrinth.com: 1
 extended:
  ##.remove-ads
  ###insticator-container
  ###div-insticator-ad-1
  ###div-insticator-ad-2
  ##.advertising
  ##.insticator_ct
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
  ##+js(prevent-fetch, ads)
```
</details>

**Comment by garry-ut99** [comment]
Caused by https://github.com/uBlockOrigin/uAssets/blob/2a7610445f7ade1939a47fab95bd76b7013116b2/filters/filters.txt#L274

- which was added in the past in this issue: https://github.com/uBlockOrigin/uAssets/issues/15820
