### ISSUE TITLE
4pda.ru

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#2392]
`http://4pda.ru/`

### Describe the issue

Banner from above
Banner right
Clickable background

### Screenshot(s)

http://jpeg.im/d13d

### Versions
- Browser/version: Opera 53.0.2907.68
- uBlock Origin version: 1.16.9.0

### Settings
uBO's default settings

**Comment by mapx-** [comment]
try
```
||4pda.to/$script,domain=4pda.ru
4pda.ru##[class^=rdc]
/4pda\.to\/.{25,}\./$domain=4pda.ru,stylesheet
||s.4pda.to/*.gif$image
||4pda.ru/*$popup,first-party
```

**Comment by PoRtvine** [comment]
Very good, but tell me how to remove the space from above and two empty places on the right?
Screens:
http://jpeg.im/d16i
http://jpeg.im/d16j
http://jpeg.im/d16k

**Comment by mapx-** [comment]
sure, much better, unfortunately they are changing very often the site configuration ..

however, the last filters would be:

```
||4pda.to/$script,domain=4pda.ru
4pda.ru##[class^=rdc]
/4pda\.to\/.{25,}\./$domain=4pda.ru,stylesheet
||s.4pda.to/*.gif$image
4pda.ru##article > div > a[target="_blank"]
4pda.ru##IFRAME[style^="overflow:hidden;"]
4pda.ru##[class^=rk]:has(h2:has-text(/prom/i))
4pda.ru##[class^=rk]:has( > h2:has-text(A))
4pda.ru##ARTICLE[id^="rc"] > .post
/4pda\.to\/.{50,}\./$domain=4pda.ru,image
```

**Comment by zaphodbeebblebrox** [comment]
remove `||4pda.to/$script,domain=4pda.ru` and add `4pda.ru##main:style(background: #e6e7e9 !important;)`

**Comment by PoRtvine** [comment]
Thank you all.

**Comment by PoRtvine** [comment]
Again went away from blocking.

**Comment by k2qwerty2k** [comment]
With this rules:
- No css styles on forum
- Very many images don't loading.

**Comment by mapx-** [comment]
4pda filters removed, obviously they are checking this thread and break the site on purpose.
