### ISSUE TITLE
luratoons.com: detection

### ISSUE THREAD

**Issue by Xery122** [uBlockOrigin/uAssets#23924]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://luratoons.com/mago-devorador-de-dragoe/47/`

### Category

detection

### Description

the site is a manhwa site and images still load, but ublock is detected when you enter any manhwa chapter.

### Other extensions used

Download All Images, Sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Sem título](https://github.com/uBlockOrigin/uAssets/assets/138821579/9e135e61-96d1-406d-968c-49926dcae6c0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 138056
 cosmetic: 50214
 scriptlet: 19997
 html: 1825
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38354-112, 2m Δ
  ublock-badware: 9003-1, 2m Δ
  ublock-privacy: 920-2, 2m Δ
  ublock-unbreak: 2367-2, 2m Δ
  ublock-quick-fixes: 81-3, 2m Δ
  easylist: 87292-167, 2m Δ
  easyprivacy: 50998-64, 2m Δ
  urlhaus-1: 13395-0, now
  plowe-0: 3627-1060, now
  spa-1: 5707-86, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1517 ms
 maxAssetCacheWait: 475 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  adskeeper.com: 3
  disqus.com: 2
  googletagmanager.com: 1
  viglink.com: 2
  yandex.ru: 1
```
</details>

**Comment by D4niloMR** [comment]
Will be fixed in the regional list, in the meanwhile you can add this to your filters:

```adb
*$script,xhr,redirect-rule=nooptext,domain=luratoons.com
luratoons.com##+js(aopr, block_ads)
luratoons.com##+js(acs, fetch, /alert|bloqueador|\.catch|\.type/)
```
