### ISSUE TITLE
deepstatemap.live: breakage

### ISSUE THREAD

**Issue by scrutinizer11** [uBlockOrigin/uAssets#23923]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://deepstatemap.live
```

### Description

A filter I assigned to the link above won't enforce changes. The filter is 
```
@@||cdn.jsdelivr.net^$script,domain=deepstatemap.live
```
However, upon reloading the page, the logger still marks the domain as blocked; the visuals confirm this.

The necessity to apply the rule arose from uBO obstructing some overlays to be displayed on the map. I verified the obstruction by turning uBO off on the site.

### Other extensions used

Wayback Machine, iCloud dashboard, Click to Shorten URL, Dark Reader, Grammarly, Share with SNS, Stylus, File Converter by Convert-Online.com, Mate Translate.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBO on

![Screen Shot 2024-05-31 at 20 15 01](https://github.com/uBlockOrigin/uAssets/assets/45983734/8deed8e1-2ee3-4220-ba51-28d26e019971)

uBO off

![Screen Shot 2024-05-31 at 20 15 39](https://github.com/uBlockOrigin/uAssets/assets/45983734/04e6bd1e-dc56-4ea5-b0bf-d4c982d84369)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 78
filterset (summary):
 network: 229945
 cosmetic: 274342
 scriptlet: 52061
 html: 2098
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81049-3990, 1d.1h.40m
  adguard-mobile: 9412-71, 1d.1h.41m
  adguard-spyware-url: 1522-120, 1d.1h.40m
  adguard-spyware: 72294-1501, 1d.1h.40m
  block-lan: 66-0, 7d.1h.36m
  curben-phishing: 806-1, 16m
  adguard-social: 23156-55, 1d.1h.40m
  adguard-cookies: 29829-46, 1d.1h.40m
  ublock-cookies-adguard: 1166-14, 2d.1h.38m
  adguard-popup-overlays: 27105-1003, 1d.1h.40m
  adguard-mobile-app-banners: 5262-23, 1d.1h.40m
  adguard-other-annoyances: 14391-414, 1d.1h.41m
  [20 lists not shown]: [too many]
 default:
  user-filters: 11-2, never
  ublock-filters: 38351-128, 2h.1m Δ
  ublock-badware: 9003-1, 2h.1m Δ
  ublock-privacy: 920-2, 2h.1m Δ
  ublock-unbreak: 2366-4, 2h.1m Δ
  ublock-quick-fixes: 81-3, 2h.1m Δ
  easylist: 87267-2069, 2h.1m Δ
  easyprivacy: 50998-28709, 2h.1m Δ
  urlhaus-1: 13395-0, 16m
  plowe-0: 3725-1653, 5d.14h.20m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 7 redacted]
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 935 ms (selfie)
 maxAssetCacheWait: 534 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
>  [20 lists not shown]: [too many]

Test using the uBO defaults and disable all other extensions

**Comment by scrutinizer11** [comment]
Ok, the settings reset solved the problem on **this** site but I lost all my rules and filters for other sites. In any case, the filter I set isn't suggesting it's the culprit of the missing overlays and UI widgets.

**Comment by mapx-** [comment]
in the settings page you have also "backup to file" (saving all your settings / custom filters)

**Comment by scrutinizer11** [comment]
I know that. Still, I have no idea how to trace to the offending parameter causing the issue. Once I restore, the problem resumes.
