### ISSUE TITLE
dailymail.co.uk: breakage

### ISSUE THREAD

**Issue by african-bee** [uBlockOrigin/uAssets#23929]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dailymail.co.uk/news/article-13480395/costco-cfo-major-announcement-store-hot-dog-deal.html`

### Category

breakage

### Description

I installed ubo a long time ago and other than adding some URLs to Trusted Sites, have not tried to change many of the settings. But for about 10 days now, none of the Daily Mail comments show - previously that was not an issue. I've tried adding a couple of entries to My Filters (e.g. this one from Reddit: www.dailymail.co.uk#@##reader-comments), and then removed them again - neither made a difference. The comments are not displayed regardless what article I select. Firefox is my default browser and I only use the UBO extension there. I checked, and the comments display when I open DM articles in Chrome or Edge.

### Other extensions used

Stop Auto Reload => have been using that for a long time now & never had UBO conflicts

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/171398032/44adb187-becd-406e-869e-514a21041775)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 142954
 cosmetic: 100049
 scriptlet: 26909
 html: 2087
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27117-180, 39m
  adguard-mobile-app-banners: 5262-19, 39m
  adguard-other-annoyances: 14401-272, 39m
  adguard-widgets: 2525-6, 39m
  easylist-annoyances: 4651-284, 39m
  easylist-chat: 196-16, 39m
  easylist-newsletters: 7521-536, 39m
  easylist-notifications: 3020-1531, 39m
  ublock-annoyances: 5855-178, now Δ
 default:
  user-filters: 2-0, never
  ublock-filters: 38354-112, now Δ
  ublock-badware: 9003-1, now Δ
  ublock-privacy: 920-2, now Δ
  ublock-unbreak: 2367-20, now Δ
  ublock-quick-fixes: 81-3, now Δ
  easylist: 87257-236, now Δ
  easyprivacy: 50998-31, now Δ
  urlhaus-1: 13485-0, 1h
  plowe-0: 3627-1060, 1h
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3255 ms
 maxAssetCacheWait: 11 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 153
 no-cosmetic-filtering: true
 network:
  dailymail.co.uk: 10
  33across.com: 16
  3lift.com: 6
  admantx.com: 1
  adnxs.com: 6
  adsafeprotected.com: 1
  adsrvr.org: 1
  amazon-adsystem.com: 1
  anm.co.uk: 1
  bidswitch.net: 2
  casalemedia.com: 5
  cdnopw.com: 1
  connatix.com: 2
  creativecdn.com: 5
  criteo.com: 5
  criteo.net: 1
  dmgmediaprivacy.co.uk: 5
  dotmetrics.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 6
  googletagmanager.com: 1
  id5-sync.com: 2
  imasdk.googleapis.com: 3
  indexww.com: 2
  kargo.com: 2
  liadm.com: 4
  newzit.com: 3
  omnitagjs.com: 2
  openx.net: 6
  permutive.app: 1
  pubmatic.com: 6
  rubiconproject.com: 6
  sharethrough.com: 9
  smartadserver.com: 8
  teads.tv: 5
  the-ozone-project.com: 5
  unrulymedia.com: 8
  webcontentassessor.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by african-bee** [comment]
Hi, I removed the Stop Auto Reload and uBO extensions from FF, and then re-added uBO. I opened the 'Costco' article from my original report and still can't see comments.

Next I opened Chrome. I had no extensions there and added uBO. Afterwards I opened the Costco article and in Chrome I could see related comments.

Here's the FF uBO Trouleshooting Info:
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137169
 cosmetic: 46272
 scriptlet: 19569
 html: 1831
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38363-112, now
  ublock-badware: 9008-1, now
  ublock-privacy: 921-2, now
  ublock-unbreak: 2376-20, now
  ublock-quick-fixes: 90-3, now
  easylist: 86278-555, now
  easyprivacy: 51008-31, now
  urlhaus-1: 14735-0, now
  plowe-0: 3627-688, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1931 ms
 maxAssetCacheWait: 631 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 98
 network:
  dailymail.co.uk: 11
  33across.com: 12
  3lift.com: 2
  admantx.com: 1
  adnxs.com: 2
  adsafeprotected.com: 1
  adsrvr.org: 1
  amazon-adsystem.com: 1
  bidswitch.net: 2
  casalemedia.com: 1
  cdnopw.com: 1
  connatix.com: 2
  creativecdn.com: 1
  criteo.com: 1
  criteo.net: 1
  dmgmediaprivacy.co.uk: 5
  dotmetrics.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 6
  googletagmanager.com: 1
  id5-sync.com: 2
  imasdk.googleapis.com: 3
  indexww.com: 2
  kargo.com: 2
  liadm.com: 4
  omnitagjs.com: 2
  openx.net: 2
  pubmatic.com: 2
  rubiconproject.com: 2
  sharethrough.com: 5
  smartadserver.com: 6
  teads.tv: 2
  the-ozone-project.com: 1
  unrulymedia.com: 6
  webcontentassessor.com: 1
 extended:
  ##.mol-ads-label-container
  ###sky-left-container
  ###sky-right
  ###sky-right-container
  ##.connatix-wrapper
  ##.watermark
  ##AD-SLOT
  ##ad-slot
  ##.banner-adverts
  ###taboola-below-article-thumbnails
  ##.googleAds
  ###sky-left
  #@#.adHolder
  ##+js(abort-on-property-read, Notification)

**Comment by stephenhawk8054** [comment]
I didn't mean "removing/re-adding extensions". I meant test again in a **new** Firefox profile with only uBO and its default settings.

**Comment by african-bee** [comment]
I'm sorry - I didn't read that correctly. This time I did what you asked and the comments displayed. 

Does that mean I should update or clear something for my default profile?

But also: thank you for the help!

**Comment by stephenhawk8054** [comment]
@african-bee In your old profile, can you go to `about:addons` page and screenshot it here?

**Comment by african-bee** [comment]
Here's what I have now - as I mentioned I did use to have the Stop Auto Reload extension:
![image](https://github.com/uBlockOrigin/uAssets/assets/171398032/d5086f16-5c3e-4e22-b689-bf1e5a2de29a)

FYI, I added Stop Auto Reload to the new FF profile, and the comments still show.

**Comment by stephenhawk8054** [comment]
@african-bee Can you reset uBO to default settings, clear the website's cookies / data, restart the browser, open new tab and test again?

**Comment by african-bee** [comment]
@stephenhawk8054 - on my original profile I previously enabled the setting to clear all cookies and history every time I shut down FF. But I did as you asked and reset uBO to default, specifically cleared the DM cookies and restarted FF, making sure to use the original profile. The great news is that for both the original and the new profile I now see comments. I assume I must have messed something up at some point. Many thanks for your help!
