### ISSUE TITLE
help.textnow.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#23925]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://help.textnow.com/hc/en-us`

### Category

breakage

### Description

Live chat support agent bot isn't available in the bottom left and is the only way to get a live agent. I have Adguard Widgets and Easylist chat widgets disabled so this shouldn't be an issue. 

### Other extensions used

FastForward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/69532417/5b0a6f4d-7989-4c68-8388-6299043626bd)
![image](https://github.com/uBlockOrigin/uAssets/assets/69532417/8dab75f4-a4d1-48d0-b896-81cfdb4daf59)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 168469
 cosmetic: 231545
 scriptlet: 52242
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79158-76666, 3m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 3m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99456-36095, 3m
  adguard-cookies: 29852-32, 3m
  adguard-generic: 81079-494, 3m
  adguard-mobile: 9422-139, 3m
  adguard-mobile-app-banners: 5262-1113, 3m
  adguard-other-annoyances: 14401-376, 3m
  adguard-popup-overlays: 27117-989, 3m
  adguard-spyware-url: 1522-5, 3m
  block-lan: 67-0, 3m
  curben-phishing: 806-0, 3m
  [7 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 87263-2513, 33m Δ
  easyprivacy: 50998-916, 33m Δ
  plowe-0: 3627-26, 3m
  ublock-badware: 9001-108, 33m Δ
  ublock-filters: 38266-3943, 33m Δ
  ublock-privacy: 878-115, 33m Δ
  ublock-quick-fixes: 87-0, 33m Δ
  ublock-unbreak: 2309-74, 33m Δ
  urlhaus-1: 13395-0, 3m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1645 ms (selfie)
 maxAssetCacheWait: 287 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  textnow.com: 1
  googletagmanager.com: 1
  zdassets.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||static.zdassets.com/ekr/snippet.js$script,domain=help.textnow.com
@@||static.zdassets.com/web_widget/messenger/$script,domain=help.textnow.com
```

@ryanbr @Alex-302

**Comment by Alex-302** [comment]
Thanks, fixed (too wide rule).
