### ISSUE TITLE
carscoops.com: ads

### ISSUE THREAD

**Issue by farewell-ladmin** [uBlockOrigin/uAssets#23920]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.carscoops.com/2024/05/lucid-boss-says-tesla-has-lost-its-sense-of-purpose/`

### Category

ads

### Description

At least six AdChoices ads appear on this page even though uBlock Origin is enabled and blocking. I did refresh the lists as well as enabling the AdGuard lists. I do have a small set of custom filters but I disabled them as well. The Element Zapper does appear to remove them but they come back after a refresh. 

The ads appear to be coming from html-load.com domains and also appear to be Google Syndication ads. The ads themselves also refresh occasionally

Ad locations:
- 2 floating ads on the right hand side, one at the top, one at the bottom
- 3 ads in between paragraphs
- 1 ad after the "next post" section

### Other extensions used

1Password - Disabled for testing
7TV - Disabled for testing
Chrome Remote Desktop - Disabled For Testing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1270" alt="Screenshot 2024-05-31 at 11 03 54 AM" src="https://github.com/uBlockOrigin/uAssets/assets/10820212/dbb67efe-b324-48f9-9de5-bcbb3236140c">
<img width="1287" alt="Screenshot 2024-05-31 at 11 04 08 AM" src="https://github.com/uBlockOrigin/uAssets/assets/10820212/86b3bc83-6ee7-448a-b64b-e4be17ec6813">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 136746
 cosmetic: 46328
 scriptlet: 19554
 html: 1824
listset (total-discarded, last-updated):
 default:
  user-filters: 9-1, never
  ublock-filters: 38351-112, now
  ublock-badware: 9003-1, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2366-2, now
  ublock-quick-fixes: 81-3, now
  easylist: 87267-167, now
  easyprivacy: 50998-64, now
  urlhaus-1: 13395-0, now
  plowe-0: 3627-1060, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2043 ms
 maxAssetCacheWait: 206 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  adpushup.com: 1
  adrecover.com: 3
  criteo.net: 2
  disqus.com: 1
  doubleclick.net: 1
  ebxcdn.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 4
  html-load.com: 2
  oko.net: 1
  taboola.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adwrap
  ##._ap_apex_ad
  ###taboola-below-article-thumbnails
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by garry-ut99** [comment]
> farewell-ladmin : The Element Zapper does appear to remove them but they come back after a refresh.

By design, as stated in manual: [Element Zapper](https://github.com/gorhill/uBlock/wiki/Element-zapper) vs [Element Picker](https://github.com/gorhill/uBlock/wiki/Element-picker).
