### ISSUE TITLE
wago.io: detection

### ISSUE THREAD

**Issue by sephist** [uBlockOrigin/uAssets#23928]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wago.io/`

### Category

detection

### Description

Site detects ublock, and then throttles or never loads when ublock is active. Sometimes loads the first page, but then won't load a second. Etc. Try with and without ublock for comparisons.

Even if throttling is confirmed to be some other issue, the site definitely still detects ublock

### Other extensions used

Dark Reader, Bypass Paywalls

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 136858
 cosmetic: 46334
 scriptlet: 19558
 html: 1825
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 38355-112, 15m Δ
  ublock-badware: 9003-1, 15m Δ
  ublock-privacy: 920-2, 15m Δ
  ublock-unbreak: 2367-2, 15m Δ
  ublock-quick-fixes: 87-3, 15m Δ
  easylist: 87292-167, 15m Δ
  easyprivacy: 50998-64, 15m Δ
  urlhaus-1: 13485-0, now
  plowe-0: 3627-1060, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 190 ms (selfie)
 maxAssetCacheWait: 65 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  nitropay.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||s.nitropay.com/ads-*.js^$script,3p,redirect-rule=noopjs
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
