### ISSUE TITLE
driffle.com: detection

### ISSUE THREAD

**Issue by misspent** [uBlockOrigin/uAssets#23926]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://driffle.com/checkout`

### Category

detection

### Description

`Add something to cart -> go to cart -> click buy now -> Proceed to checkout.`

It only shows up when you're on the checkout page. I found this rather odd in all honesty, and I'm not sure how to do this myself, so I thought I'd report it to the people who know what they're doing.

### Other extensions used

I disabled uBlock Origin and everything worked as it should, so I'm sure it's that.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/78914154/6e073e2a-beec-493b-b0e3-cdbe007fd119)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 125
filterset (summary):
 network: 567378
 cosmetic: 227882
 scriptlet: 51304
 html: 2087
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79158-136, now
  https://hosts.anudeep.me/mirror/adservers.txt: 42535-176, now
  https://hosts.anudeep.me/mirror/facebook.txt: 3995-1, now
  https://o0.pages.dev/Pro/adblock.txt: 159965-3425, now
  https://phishing.army/download/phishing_army_blocklist_extended.txt: 205470-20067, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 438-11, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 760-8, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 67595-42353, now
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/all_search_engines/global.txt: 7010-6, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/privacy_essentials.txt: 1230-40, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99456-23341, now
  adguard-generic: 81055-7713, now
  [16 lists not shown]: [too many]
 default:
  user-filters: 394-0, never
  ublock-filters: 38354-649, 1h.22m Δ
  ublock-badware: 9003-761, 1h.22m Δ
  ublock-privacy: 920-73, 1h.22m Δ
  ublock-unbreak: 2367-14, 1h.22m Δ
  ublock-quick-fixes: 81-3, 1h.22m Δ
  easylist: 87292-29654, 1h.22m Δ
  adguard-spyware-url: 1522-174, now
  easyprivacy: 50998-39866, 1h.22m Δ
  urlhaus-1: 13395-78, now
  curben-phishing: 806-155, now
  plowe-0: 3627-3060, now
  LegitimateURLShortener: 2631-197, 17m
filterset (user): [array of 234 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 245 redacted]
urlRuleset:
 added: [array of 38 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 438 ms (selfie)
 maxAssetCacheWait: 246 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 48
 network:
  artfut.com: 10
  cloudflareinsights.com: 2
  criteo.com: 2
  dwin1.com: 2
  facebook.net: 1
  google.com: 4
  googletagmanager.com: 1
  gravatar.com: 1
  gstatic.com: 2
  nsureapi.com: 1
  sc-static.net: 1
  sentry.io: 6
  stripe.com: 11
  stripe.network: 1
  trustpilot.com: 1
  webengage.com: 2
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##.MuiSnackbar-anchorOriginBottomLeft
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by misspent** [comment]
That's odd I didn't think it'd work with everything as default, but it did. Time to figure out why on earth that's happening. Thanks for your help, and sorry about wasting your time with the issue.

**Comment by stephenhawk8054** [comment]
```yml
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79158-136, now
  https://hosts.anudeep.me/mirror/adservers.txt: 42535-176, now
  https://hosts.anudeep.me/mirror/facebook.txt: 3995-1, now
  https://o0.pages.dev/Pro/adblock.txt: 159965-3425, now
  https://phishing.army/download/phishing_army_blocklist_extended.txt: 205470-20067, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 438-11, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 760-8, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 67595-42353, now
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/all_search_engines/global.txt: 7010-6, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/privacy_essentials.txt: 1230-40, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99456-23341, now
  adguard-generic: 81055-7713, now
  [16 lists not shown]: [too many]
 default:
  user-filters: 394-0, never
```

You are using a heavily modified configuration. That's why we put these as prerequisites before submitting the issues

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

Please follow the prerequisites carefully.
