### ISSUE TITLE
aiarticlespinner.co: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#23939]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aiarticlespinner.co/`

### Category

ads

### Description

ads

### Other extensions used

n

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/4a57205d-32c8-4124-ab8d-fdaad06115ac)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 146317
 cosmetic: 161878
 scriptlet: 34129
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8451-10, 9m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 205-0, now
  adguard-other-annoyances: 14402-8, now
  adguard-popup-overlays: 27118-940, now
  easylist-annoyances: 4656-102, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7529-27, now
  easylist-notifications: 3020-281, now
  fanboy-cookiemonster: 51101-256, now
  fanboy-social: 16223-17, now
  ublock-annoyances: 5913-104, now
  ublock-cookies-easylist: 1171-0, now
 default:
  user-filters: 50-0, never
  easylist: 87263-641, now
  easyprivacy: 51010-86, now
  plowe-0: 3627-688, now
  ublock-badware: 9006-2, now
  ublock-filters: 38310-687, now
  ublock-privacy: 928-5, now
  ublock-quick-fixes: 90-0, now
  ublock-unbreak: 2310-21, now
  urlhaus-1: 13775-0, 8m
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 25 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 608 ms (selfie)
 maxAssetCacheWait: 265 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  avantisvideo.com: 1
  fuseplatform.net: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.headerads
  ##.adsbygoogle-noablate
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
aiarticlespinner.co##.code-block
```

@ryanbr
