### ISSUE TITLE
brave search whitelisted?

### ISSUE THREAD

**Issue by sankhababu** [uBlockOrigin/uAssets#23932]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://search.brave.com/search?q=god
```

### Description

Brave search is whitelisted. Gray in color.
![Screenshot_20240601-141642](https://github.com/uBlockOrigin/uAssets/assets/115644195/f56e30f2-fe04-4e0b-8732-0eddf0a6ce02)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by sankhababu** [comment]
uBlock Origin: 1.58.0
Chromium Mobile: 124
filterset (summary):
 network: 138333
 cosmetic: 54524
 scriptlet: 21070
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38720-108, 1m Δ
  ublock-badware: 9000-1, 2m Δ
  ublock-privacy: 924-6, 2m Δ
  ublock-unbreak: 2313-32, 2m Δ
  ublock-quick-fixes: 88-4, 2m Δ
  adguard-mobile: 9422-214, 3h.52m
  easylist: 87251-154, 1m Δ
  easyprivacy: 51008-179, 1m Δ
  urlhaus-1: 13485-0, 3h.52m
  plowe-0: 3627-1060, 3h.52m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings:
 hyperlinkAuditingDisabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 636 ms (selfie)
 maxAssetCacheWait: 216 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(prevent-fetch, body:browser)

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by sankhababu** [comment]
Same result Sir.
![Screenshot_20240601-163453](https://github.com/uBlockOrigin/uAssets/assets/115644195/a6c63666-2ac2-444e-beaf-ca0a21af8a23)

**Comment by sankhababu** [comment]
uBlock Origin: 1.58.0
Chromium Mobile: 124
filterset (summary):
 network: 138323
 cosmetic: 54524
 scriptlet: 21070
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38720-330, 5m
  ublock-badware: 9000-1, now Δ
  ublock-privacy: 924-0, now Δ
  ublock-unbreak: 2313-0, now Δ
  ublock-quick-fixes: 88-0, 5m
  adguard-mobile: 9422-97, 6m
  easylist: 87251-612, 5m
  easyprivacy: 50998-718, now Δ
  urlhaus-1: 13485-0, 6m
  plowe-0: 3627-0, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 778 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(prevent-fetch, body:browser)

**Comment by stephenhawk8054** [comment]
Which browser are you using?

**Comment by sankhababu** [comment]
Kiwi, Mull, Fennce F-droid.

**Comment by stephenhawk8054** [comment]
Can you screenshot how Fennec looks like?

**Comment by sankhababu** [comment]
Fennec-
![Screenshot_20240601-164938](https://github.com/uBlockOrigin/uAssets/assets/115644195/5e5c50d3-387e-418c-a045-06e5cfaf3278)

**Comment by sankhababu** [comment]
uBlock Origin: 1.58.0

Firefox Mobile: 125

filterset (summary):

 network: 234199

 cosmetic: 205980

 scriptlet: 47871

 html: 2088

listset (total-discarded, last-updated):

 added:

  adguard-generic: 81079-3997, 3m

  adguard-spyware-url: 1522-120, 3m

  adguard-spyware: 72313-1509, 3m

  block-lan: 66-0, 15d.5h.55m

  curben-phishing: 504-0, 3m

  adguard-social: 23143-55, 3m

  adguard-cookies: 29852-46, 3m

  ublock-cookies-adguard: 1209-16, 25m

  fanboy-thirdparty_social: 68-3, 3m

  fanboy-cookiemonster: 67205-20074, 8d.5h.50m

  ublock-cookies-easylist: 1209-1209, 25m

  ublock-annoyances: 5880-108, 4m Δ

  [3 lists not shown]: [too many]

 default:

  user-filters: 0-0, never

  ublock-filters: 38787-113, 24m

  ublock-badware: 9002-1, 3m Δ

  ublock-privacy: 921-2, 24m

  ublock-unbreak: 2370-2, 24m

  ublock-quick-fixes: 88-3, 24m

  adguard-mobile: 9422-99, 3m

  easylist: 87251-2065, 24m

  easyprivacy: 51008-28704, 4m Δ

  urlhaus-1: 13485-0, 3m

  plowe-0: 3627-1554, 3m

filterset (user): [empty]

userSettings: [none]

hiddenSettings: [none]

supportStats:

 allReadyAfter: 4437 ms

 maxAssetCacheWait: 2977 ms

 cacheBackend: indexedDB

popupPanel:

 blocked: 0

 extended:

  ##+js(prevent-fetch, body:browser)

**Comment by stephenhawk8054** [comment]
Reset uBO to default settings in Fennec, then can you screenshot your list of add-ons in Fennec?

**Comment by gwarser** [comment]
I see nothing wrong.

**Comment by sankhababu** [comment]
![Screenshot_20240601-165608](https://github.com/uBlockOrigin/uAssets/assets/115644195/9fd7b605-2c42-4cfd-bcb8-4cc868ea57fa)
![Screenshot_20240601-165846](https://github.com/uBlockOrigin/uAssets/assets/115644195/261e2c7e-2075-4e54-b961-2a9b23c8f567)

**Comment by sankhababu** [comment]
uBlock Origin: 1.58.0

Firefox Mobile: 125

filterset (summary):

 network: 138267

 cosmetic: 54493

 scriptlet: 19610

 html: 1813

listset (total-discarded, last-updated):

 default:

  user-filters: 0-0, never

  ublock-filters: 38812-114, 1m

  ublock-badware: 8997-1, 1m

  ublock-privacy: 921-2, 1m

  ublock-unbreak: 2363-2, 1m

  ublock-quick-fixes: 87-1, 1m

  adguard-mobile: 9422-69, 1m

  easylist: 87251-232, 1m

  easyprivacy: 50998-72, 1m

  urlhaus-1: 13485-0, 1m

  plowe-0: 3627-1134, 1m

filterset (user): [empty]

userSettings: [none]

hiddenSettings: [none]

supportStats:

 allReadyAfter: 15421 ms

 maxAssetCacheWait: 10588 ms

 cacheBackend: indexedDB

popupPanel:

 blocked: 0

 extended:

  ##+js(prevent-fetch, body:browser)

**Comment by stephenhawk8054** [comment]
Can you turn off all other extensions (except uBO), restart the browser, open new tab and test again?

**Comment by sankhababu** [comment]
Also cleared the cache.
![Screenshot_20240601-170412](https://github.com/uBlockOrigin/uAssets/assets/115644195/51edee7b-2197-4c00-a691-753c6cf43126)
![Screenshot_20240601-170424](https://github.com/uBlockOrigin/uAssets/assets/115644195/16ee21ad-5be9-45ac-b707-8a067d9f8d57)

**Comment by sankhababu** [comment]
uBlock Origin: 1.58.0

Firefox Mobile: 125

filterset (summary):

 network: 138294

 cosmetic: 54419

 scriptlet: 19627

 html: 1826

listset (total-discarded, last-updated):

 default:

  user-filters: 0-0, never

  ublock-filters: 38786-113, 1m Δ

  ublock-badware: 8997-1, 1m Δ

  ublock-privacy: 921-2, 1m Δ

  ublock-unbreak: 2363-20, 1m Δ

  ublock-quick-fixes: 88-3, 1m Δ

  adguard-mobile: 9422-77, 7m

  easylist: 87251-248, 6m

  easyprivacy: 51008-31, 1m Δ

  urlhaus-1: 13485-0, 6m

  plowe-0: 3627-1134, 6m

filterset (user): [empty]

userSettings: [none]

hiddenSettings: [none]

supportStats:

 allReadyAfter: 593 ms (selfie)

 maxAssetCacheWait: 132 ms

 cacheBackend: indexedDB

popupPanel:

 blocked: 0

 extended:

  ##+js(prevent-fetch, body:browser)

**Comment by stephenhawk8054** [comment]
It's normal for me, there's nothing to block on that page

<details>

![Capture+_2024-06-01-18-40-51.png](https://github.com/uBlockOrigin/uAssets/assets/66517106/4661067f-ae0d-4b40-8ae9-95521128d950)

</details>

The only difference is I don't have gray color on `search.brave.com` row

**Comment by sankhababu** [comment]
Then it's okay.
Perhaps nothing to worry.
Thanks a lot.🙏

**Comment by garry-ut99** [comment]
> sankhababu : Then it's okay.

For who? Maybe for him, but not for you as he has green color on `brave.search.com` which means the  connection has been allowed, while you have grey color like no requests have been processed, do you think it's ok when you have different color than other users on same domain or no requests have been processed for you?

For me it's green like for Steven, but I've observed that when I reload page, with domains panel expanded, `brave.search.com` becomes initially grey for a second, just like for you, but then it always turns out to green after a while, it seems for you it's stuck at light grey forever, and never turns to green, like requests were never processed.

I also noticed that on your screenshoot your uBO popup UI lacks:
- the last (Third column: local dynamic filtering rules) column
- 6 first rows at the top (from `images` to `3rd-party-frames`)

Like it didn't fit on your device's screen, either it's how does uBO popup UI does look at smaller screens or your uBO popup UI is size-glitched, maybe some colors are glitched/stucked as well.

**Comment by sankhababu** [comment]
Well then what should I do, please.

**Comment by stephenhawk8054** [comment]
The green is because I turned on `I'm an advanced user`. When I turn off that, it becomes gray for me.

**Comment by sankhababu** [comment]
I did this (enabled advanced user).
Same result in Kiwi, Mull, Fennec unfortunately.

Jun 1, 2024 6:16:54 PM stephenhawk8054 ***@***.***>:

**Comment by garry-ut99** [comment]
> sankhababu: Well then what should I do, please.

I've tried to reload page on Mobile several dozen of times, by toggling the Big Blue button on or off and then pressing reload icon every time, and I can occasionally reproduce `brave.search.com` stucked at grey color, but very rarely, most often it happens when turning the Big Blue button on or off, then clicking reload icon, and then quickly turning the Big Blue button again and clicking reload icon again before the previous reaload has finsihed. Maybe it's some glitch if an user do some thing too quickly in popup UI, but hard to say why it does happen always for you, while for me only occasionally.
