### ISSUE TITLE
lootlemon.com: ads

### ISSUE THREAD

**Issue by AngryAutist** [uBlockOrigin/uAssets#23935]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lootlemon.com/`

### Category

ads

### Description

when viewing an item on lootlemon.com, a huge banner ad with a video shows at the bottom of the page on opera gx

### Other extensions used

Dashlane
Sponsorblock
Enhancer for Youtube
Poper Blocker
Honey
Return Youtube Dislike
Indie Wiki Buddy
DeArrow

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 221317
 cosmetic: 252671
 scriptlet: 53044
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81112-492, now
  adguard-mobile: 9422-167, now
  adguard-spyware-url: 1522-119, now
  adguard-spyware: 72314-30138, now
  block-lan: 67-0, now
  curben-phishing: 507-0, now
  adguard-cookies: 29852-87, now
  ublock-cookies-adguard: 1171-1171, now
  fanboy-cookiemonster: 51101-3971, now
  ublock-cookies-easylist: 1171-0, now
  adguard-social: 23143-782, now
  fanboy-social: 16223-28, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38308-3987, 1h.46m Δ
  ublock-badware: 9006-107, 1h.46m Δ
  ublock-privacy: 928-0, 1h.46m Δ
  ublock-unbreak: 2310-74, 1h.46m Δ
  ublock-quick-fixes: 88-0, 1h.46m Δ
  easylist: 87266-2708, 1h.46m Δ
  easyprivacy: 51009-1030, 1h.46m Δ
  urlhaus-1: 13775-0, now
  plowe-0: 3627-25, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 870 ms (selfie)
 maxAssetCacheWait: 184 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 467
 network:
  1rx.io: 1
  2mdn.net: 2
  33across.com: 1
  3lift.com: 6
  4dex.io: 8
  ad-delivery.net: 2
  ad.gt: 7
  adform.net: 1
  adition.com: 1
  admanmedia.com: 1
  adnxs.com: 8
  adotmob.com: 1
  adroll.com: 1
  adsafeprotected.com: 2
  adsrvr.org: 4
  agkn.com: 1
  amazon-adsystem.com: 18
  aniview.com: 24
  anonymised.io: 9
  aralego.com: 1
  audrte.com: 1
  avplayer.com: 4
  bidr.io: 1
  bidswitch.net: 2
  bing.com: 1
  bluekai.com: 1
  btloader.com: 3
  bttrack.com: 1
  bumlam.com: 1
  casalemedia.com: 4
  celtra.com: 38
  cognitivlabs.com: 2
  company-target.com: 1
  contextweb.com: 1
  criteo.com: 5
  criteo.net: 1
  crwdcntrl.net: 2
  demdex.net: 1
  dotomi.com: 1
  doubleclick.net: 30
  eu-1-id5-sync.com: 1
  everesttech.net: 3
  fastclick.net: 1
  google-analytics.com: 7
  google.com: 10
  googlesyndication.com: 30
  googletagmanager.com: 4
  gstatic.com: 11
  hadronid.net: 2
  id5-sync.com: 4
  imasdk.googleapis.com: 4
  indexww.com: 1
  infolinks.com: 1
  iqm.com: 1
  jsdelivr.net: 1
  kueezrtb.com: 13
  liadm.com: 1
  loopme.me: 1
  mathtag.com: 1
  media.net: 2
  moatads.com: 22
  network-n.com: 22
  openx.net: 9
  pbstck.com: 12
  permutive.app: 1
  presage.io: 1
  privacy-mgmt.com: 3
  pswec.com: 1
  pubmatic.com: 5
  quantcount.com: 1
  quantserve.com: 2
  richaudience.com: 4
  rqtrk.eu: 1
  rubiconproject.com: 14
  sascdn.com: 1
  scorecardresearch.com: 3
  script.ac: 2
  semasio.net: 2
  sharethrough.com: 22
  simpli.fi: 4
  smaato.net: 1
  smartadserver.com: 8
  springserve.com: 1
  stickyadstv.com: 5
  streamrail.com: 4
  sundaysky.com: 1
  technoratimedia.com: 1
  truoptik.com: 1
  trustarc.com: 1
  turn.com: 1
  userreport.com: 1
  w55c.net: 1
  yahoo.com: 6
  yellowblue.io: 3
  zemanta.com: 1
 extended:
  ##iframe[name="googlefcPresent"]
  ##[name^="google_ads_iframe"]
  ##.ad_container
  ##.ad_caption
  ###abgb
  ##.GoogleActiveViewElement:not(:has(> #reward_close_button_widge…
  ##iframe[width="468"][height="60"]
  ##.img_ad
  ##a[href^="https://adclick.g.doubleclick.net/"]
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by MrCSharp22** [comment]
Lootlemon now has a very aggressive adblocker detection mechanism that force reloads the page and eventually redirects to a different domain to "report the problem".

The following filters clean this up and I have been using them since:

```
www.lootlemon.com##^script[id="ZJlfJlB"]
www.lootlemon.com##^script[data-sdk^="l/1."]
www.lootlemon.com##^script[nowprocket=""]
||cdn.prod.website-files.com/5ff36780a108495c598ce192/js/webflow.*.js$script
```
