### ISSUE TITLE
outlook.live.com: ads / detection

### ISSUE THREAD

**Issue by schembriaiden** [uBlockOrigin/uAssets#23933]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://outlook.live.com/mail/0/
```

### Description

Add started showing again on outlook.

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="515" alt="Screenshot 2024-06-01 at 15 58 40" src="https://github.com/uBlockOrigin/uAssets/assets/81376423/52dda4a4-0cc2-4fc1-b7d6-56c1fd945091">

<br/>

<img width="251" alt="Screenshot 2024-06-01 at 15 58 56" src="https://github.com/uBlockOrigin/uAssets/assets/81376423/84c63c70-905e-41e9-b066-7999ff13ad5d">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 137185
 cosmetic: 46266
 scriptlet: 19560
 html: 1825
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38356-112, 18m Δ
  ublock-badware: 9008-1, 18m Δ
  ublock-privacy: 920-2, 18m Δ
  ublock-unbreak: 2367-2, 18m Δ
  ublock-quick-fixes: 88-3, 18m Δ
  easylist: 87251-168, 18m Δ
  easyprivacy: 51008-64, 18m Δ
  urlhaus-1: 13775-0, 18m
  plowe-0: 3627-1060, 18m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 295 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
@vikingnope enable uBlock filters – Annoyances & test again

**Comment by vikingnope** [comment]
@mapx- I do not see the test, currently I have these enabled:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/57b0fb66-483b-4110-bcae-3087d5f1e8a9)

**Comment by vikingnope** [comment]
After enabling annoyances one of them left, the one with 'looks like you have an ad-blcok enabled'

**Comment by mapx-** [comment]
From which country are you accessing the page?
(you have a pretty old FF version)

**Comment by vikingnope** [comment]
Could it be because I am using Floorp?

I am accessing it from Malta

**Comment by mapx-** [comment]
> Could it be because I am using Floorp?

idk => try using a firefox new profile and test again using only uBO defaults (settings + filter lists)

Even using a Malta ip address => still no such annoyances on my end (FF, chrome)

**Comment by vikingnope** [comment]
Tried on latest firefox, and still getting this:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/06dfe5ef-d478-4ae1-8500-6408c28c57b0)

``` yaml

uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 138045
 cosmetic: 47809
 scriptlet: 23277
 html: 2087
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5859-39, never
 default:
  user-filters: 0-0, never
  ublock-filters: 38355-112, now
  ublock-badware: 9003-1, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2366-2, now
  ublock-quick-fixes: 90-1, now
  easylist: 87251-168, now
  easyprivacy: 51011-65, now
  urlhaus-1: 14340-0, now
  plowe-0: 3627-1060, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1158 ms
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
 
 ```

**Comment by Yuki2718** [comment]
@vikingnope Can you right-click on the ad and, choose Insepct from the menu which should open developer tools, and take a full screenshot of the page? Be careful not to include your personal information etc. in the screenshot(s).

**Comment by vikingnope** [comment]
@Yuki2718 

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/28d78fcb-628e-43b7-b478-666044dde015)

**Comment by Yuki2718** [comment]
@vikingnope Can you test adding
```
outlook.live.com##div[role="listbox"] div[style^="position: absolute"] > div[class] > div[class][id*="-"]:has(div[class] > div[class] > div[class] + .ms-Button--hasMenu.ms-Button--icon)
```

to My filters and refreshing the page?

**Comment by vikingnope** [comment]
@Yuki2718  I tried it but it did not work.

**Comment by Yuki2718** [comment]
What about
```
outlook.live.com##div[role="listbox"] div[style] > div[style] > div[class] > div[class][id*="-"]:has(> div:not([class]) div[class] > div[class] + .ms-Button--hasMenu.ms-Button--icon)
```

**Comment by vikingnope** [comment]
Nope still there

**Comment by vikingnope** [comment]
Still did not work

Here is another screenshot maybe this helps you more:

![image](https://github.com/uBlockOrigin/uAssets/assets/81376423/99ce1bd2-b5d1-48f2-9794-6b4d9e99d0cf)

**Comment by Yuki2718** [comment]
Hmm, no `[role="listbox]`... IDK what layout it is. Test
```
outlook.live.com##div[data-app-section="MessageList"] div[class][id*="-"]:has(> div:not([class]) div[class] > div[class] + .ms-Button--hasMenu.ms-Button--icon)
```

**Comment by Yuki2718** [comment]
As the rule is very broad, can you also check
```
outlook.live.com##div[data-app-section="MessageList"] div[class][id*="-"]:has(> div:not([class]) > div[class] > div[class] > div[class] > div[class] > div[class] > div[class] > div[class] + .ms-Button--hasMenu.ms-Button--icon)
```
?

**Comment by vikingnope** [comment]
> As the rule is very broad, can you also check
> 
> ```
> outlook.live.com##div[data-app-section="MessageList"] div[class][id*="-"]:has(> div:not([class]) > div[class] > div[class] > div[class] > div[class] > div[class] > div[class] > div[class] + .ms-Button--hasMenu.ms-Button--icon)
> ```
> 
> ?

This last one also worked

**Comment by Yuki2718** [comment]
Added to uBlock filters so you can remove these rules once the update came. Thanks for taking your time!

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/24649

**Comment by stephenhawk8054** [comment]
@aviationhacker Can you enable `uBlock filters – Annoyances` list and test again?

**Comment by aviationhacker** [comment]
> @aviationhacker Can you enable `uBlock filters – Annoyances` list and test again?

@stephenhawk8054 Have done that now, and has fixed the issue. Apologies I didn't even realize annoyances were on a separate list!
