### ISSUE TITLE
us.tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by kriana** [uBlockOrigin/uAssets#23936]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://us.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=24780&SortBy=LastSeen&Order=desc`

### Category

detection

### Description

Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/7259933/f01e3bf4-d611-495c-8349-ff362ec383aa)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/7259933/924d4b9f-3e41-4023-b924-7241eb2987e8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 221304
 cosmetic: 252587
 scriptlet: 51369
 html: 2093
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81112-3989, 5m
  adguard-mobile: 9422-58, 5m
  adguard-spyware-url: 1522-120, 4m
  adguard-spyware: 72314-1512, 4m
  block-lan: 67-0, 4m
  curben-phishing: 504-0, 4m
  adguard-social: 23143-55, 4m
  adguard-cookies: 29852-46, 4m
  adguard-popup-overlays: 27118-1003, 4m
  adguard-mobile-app-banners: 5262-23, 4m
  adguard-other-annoyances: 14402-412, 4m
  adguard-widgets: 2524-13, 4m
  [11 lists not shown]: [too many]
 default:
  user-filters: 126-4, never
  ublock-filters: 38382-112, now
  ublock-badware: 9008-1, now
  ublock-privacy: 921-2, now
  ublock-unbreak: 2367-2, now
  ublock-quick-fixes: 88-3, now
  easylist: 87263-2050, now
  easyprivacy: 51010-28705, now
  urlhaus-1: 13775-0, now
  plowe-0: 3627-1554, now
filterset (user): [array of 126 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7186 ms
 maxAssetCacheWait: 3660 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  tamrieltradecentre.com: 3
  google-analytics.com: 1
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##[href*="sjv.io"]:remove()
  ##img[style="max-width: 100%; max-height: 250px;"]:style(positio…
  ##+js(set-constant, adsbygoogle.loaded, true)
```
</details>

**Comment by stephenhawk8054** [comment]
I can only reproduce if I use Firefox' Enhanced Tracking Protection

**Comment by kriana** [comment]
I just tested it again with the tracking protection off and it doesn't seem to matter for me.

**Comment by stephenhawk8054** [comment]
I can't reproduce it

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/2abc98fa-64c2-4871-ab4c-b5bb3657fa1f)

Test again in a new Firefox profile with only uBO and its default settings + Turn off tracking protection
