### ISSUE TITLE
Issues about shorteners/hosting websites are to be reported here only.

### ISSUE THREAD

**Issue by moreistoria** [uBlockOrigin/uAssets#23946]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page
```
https://rsgames.xyz/youhere.html
https://freesolana.top/links
https://github.com/uBlockOrigin/uAssets/issues/23945#issue-2329544148
```
### Category

detection

### Description

detection adblock 

### Screenshot(s)
https://github.com/uBlockOrigin/uAssets/assets/144955357/ff9dd0ad-4944-4d12-a752-0fcdc38b2dce
<details>
<summary></summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83506
  cosmetic: 38547
  scriptlet: 17119
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 220-0, never
    easylist: 61357-46, 1h.31m
    easyprivacy: 30909-1172, 1h.31m
    plowe-0: 3668-898, 1h.31m
    ublock-abuse: 77-0, 1h.31m
    ublock-badware: 4216-119, 1h.31m
    ublock-filters: 32238-259, 1h.31m
    ublock-privacy: 259-1, 1h.31m
    ublock-quick-fixes: 519-141, 1h.31m
    ublock-unbreak: 1869-48, 1h.31m
    urlhaus-1: 6697-1, 1h.31m
filterset (user): [array of 85 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1132 ms (selfie)
  maxAssetCacheWait: 552 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    bambarmedia.com: 4
    clickiocdn.com: 2
    d3u598arehftfk.cloudfront.net: 1
    demand.supply: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    wtg-ads.com: 1
```
</details>

</details>

_Originally posted by @culinaxok in https://github.com/uBlockOrigin/uAssets/discussions/17361_

**Comment by stephenhawk8054** [comment]
Please continue at that thread as said to you. DON'T open the issues after we said where to post these issues.

**Comment by moreistoria** [comment]
We follow short links... All domains are filtered except https://rsgames.xyz/youhere.html. uBlock discovery occurs on this domain. Please, help! Thank you!
Screenshot:
https://github.com/uBlockOrigin/uAssets/assets/144955357/ff9dd0ad-4944-4d12-a752-0fcdc38b2dce
