### ISSUE TITLE
antena3.com: ads

### ISSUE THREAD

**Issue by DasherPack** [uBlockOrigin/uAssets#23947]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.antena3.com/novamas/moda/quien-zheng-xiang-influencer-china-que-factura-millones-mostrando-productos-tan-solo-segundos_2024020465bcea8b327cdd0001a50d2f.html`

### Category

ads

### Description

uBlock shows ad leftovers: gray boxes with the word _Publicidad_ (_Advertising_).

### Other extensions used

Bitwarden, Search by Image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-02 at 12-55-40 ¿Quién es Zheng Xiang La influencer china que factura millones mostrando productos tan solo unos segundos](https://github.com/uBlockOrigin/uAssets/assets/68102434/89048f3e-e7d8-42f2-b7fd-a71037da2fd3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 136703
 cosmetic: 46274
 scriptlet: 19567
 html: 1831
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 38361-112, 1h.8m Δ
  ublock-badware: 9008-1, 1h.8m Δ
  ublock-privacy: 921-2, 1h.8m Δ
  ublock-unbreak: 2376-2, 1h.8m Δ
  ublock-quick-fixes: 90-3, 1h.8m Δ
  easylist: 86203-168, 1h.8m Δ
  easyprivacy: 51011-65, 1h.8m Δ
  urlhaus-1: 14340-0, now
  plowe-0: 3627-1060, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1558 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 31
 network:
  antena3.com: 3
  adobedtm.com: 12
  amazon-adsystem.com: 1
  atresmedia.com: 1
  demdex.net: 4
  doubleclick.net: 3
  id5-sync.com: 1
  imasdk.googleapis.com: 1
  outbrain.com: 1
  richaudience.com: 1
  seedtag.com: 1
  sibbo.net: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `AdGuard Spanish/Portuguese` and `EasyList Spanish` list and test again.

**Comment by DasherPack** [comment]
It works using the lists you suggested.

![image](https://github.com/uBlockOrigin/uAssets/assets/68102434/875095d2-bebe-4631-939e-991b556c35d6)
