### ISSUE TITLE
Detection uBlock

### ISSUE THREAD

**Issue by moreistoria** [uBlockOrigin/uAssets#23945]
We go through short links... all domains are filtered, except https://rsgames.xyz/youhere.html. UBlock detection occurs on this domain. Please, help! Thank you!

**Comment by moreistoria** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/144955357/ff9dd0ad-4944-4d12-a752-0fcdc38b2dce)

**Comment by stephenhawk8054** [comment]
For shortener sites, give the original link here: https://github.com/uBlockOrigin/uAssets/discussions/17361
