### ISSUE TITLE
prowrestlingtees.com: breakage

### ISSUE THREAD

**Issue by EmKnird** [uBlockOrigin/uAssets#23941]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.prowrestlingtees.com/jon-moxley-the-9th-iwgp-world-heavyweight-champion-double-sided.html`

### Category

breakage

### Description

Navigation to see the back of double-sided shirts does not work. The arrows/images appear, but clicking on them does nothing. After disabling Ublock Origins and reloading the page, I was able to use them as expected. (Another double-sided shirt which has the same issue can be found at https://www.prowrestlingtees.com/promotion-tshirts/aew/mjf-the-wolf-of-wrestling-double-sided.html.)

### Other extensions used

Nuke Anything, Minimal Twitter, Keepass, Zotero Connector, Grammerly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137773
 cosmetic: 46267
 scriptlet: 19571
 html: 1831
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38382-112, now
  ublock-badware: 9008-1, now
  ublock-privacy: 921-2, now
  ublock-unbreak: 2367-2, now
  ublock-quick-fixes: 90-3, now
  easylist: 87263-169, now
  easyprivacy: 51010-64, now
  urlhaus-1: 14340-0, now
  plowe-0: 3627-1060, now
filterset (user): [empty]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1885 ms
 maxAssetCacheWait: 341 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  prowrestlingtees.com: 1
  facebook.net: 1
  google-analytics.com: 2
  googletagmanager.com: 1
  onesignal.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
