### ISSUE TITLE
romsfun.org: ads

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#23943]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://romsfun.org/`

### Category

ads

### Description

Leftover Ad 

### Other extensions used

Cookie Editor
De-Arrow
ChatGPT box
Downthemall

### Screenshot(s)

![librewolf_JxYodzD97G](https://github.com/uBlockOrigin/uAssets/assets/150899804/cf60b32a-0aa3-4a87-817d-23ca599bc6ce)
![librewolf_ObwIgTdehI](https://github.com/uBlockOrigin/uAssets/assets/150899804/6414c29e-f222-4ef3-8f09-3ca2119b973a)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 125
filterset (summary):
 network: 161667
 cosmetic: 125680
 scriptlet: 26275
 html: 1841
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51101-182, now
  ublock-cookies-easylist: 1171-3, now
  easylist-annoyances: 4656-51, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7529-20, now
  easylist-notifications: 3020-164, now
  RUS-0: 39577-183, now
 default:
  user-filters: 63-3, never
  ublock-filters: 38355-112, now
  ublock-badware: 9008-1, now
  ublock-privacy: 921-2, now
  ublock-unbreak: 2376-2, now
  ublock-quick-fixes: 90-1, now
  easylist: 86203-169, now
  adguard-spyware-url: 1522-120, now
  easyprivacy: 51011-65, now
  urlhaus-1: 14340-0, now
  curben-phishing: 521-1, now
  plowe-0: 3627-1060, now
  LegitimateURLShortener: 2635-158, now
filterset (user): [array of 63 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 721 ms (selfie)
 maxAssetCacheWait: 317 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##.modal-body
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
romsfun.org##[href^="https://kovcifra.click/"]
```

@ryanbr
