### ISSUE TITLE
support.bose.com: breakage

### ISSUE THREAD

**Issue by ComfortableMilk4454** [uBlockOrigin/uAssets#23955]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://support.bose.com/s/get-help-landing-page?hasItems=0&language=en_US
https://support.bose.com/s/?language=en_US
```

### Description

the chat button on support.bose.com is missing with uBO 1.58.0 on Firefox (release) 126.0.1

### Other extensions used

<img width="391" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/33199569-b308-404e-820b-44a771d29ab3">

note that ive tested with a fresh install of uBO 1.58.0 firefox extension on a new firefox release 126.0.1 profile without any other extensions & without modifying any settings at all of firefox or uBO and the issue still persists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
with uBO enabled:
<img width="1624" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/001ce127-c09b-40d3-8db6-d262b3eff008">
with uBO disabled (notice the chat button in the bottom right corner):
<img width="1624" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/06de89cd-2498-48e5-9a6d-a291b33daae0">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 158628
 cosmetic: 156001
 scriptlet: 46969
 html: 2093
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81069-3987, 4d.6h.7m
  adguard-cookies: 29819-40, 4d.6h.7m
  ublock-cookies-adguard: 1174-14, 2d.6h.36m
  fanboy-cookiemonster: 51096-3912, 2d.6h.36m
  ublock-cookies-easylist: 1174-1174, 2d.6h.36m
  ublock-annoyances: 5859-108, 4h.2m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 38363-117, 4h.2m Δ
  ublock-badware: 9008-1, 4h.2m Δ
  ublock-privacy: 921-0, 4h.2m Δ
  ublock-unbreak: 2376-2, 4h.2m Δ
  ublock-quick-fixes: 90-0, 4h.2m Δ
  easylist: 86278-2000, 4h.2m Δ
  easyprivacy: 51011-160, 4h.2m Δ
  urlhaus-1: 14735-0, 8h.16m
  plowe-0: 3725-1176, 9d.6h.52m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 127 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=support.bose.com
```

@ryanbr

**Comment by ComfortableMilk4454** [comment]
thanks for fixing! works on my end now :)
