### ISSUE TITLE
jadoo.lol: detection

### ISSUE THREAD

**Issue by Touhid97** [uBlockOrigin/uAssets#23952]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jadoo.lol/disable-adblock.php`

### Category

detection

### Description

Can't access. Detects adblocker. 

### Other extensions used

IDM Integration Module

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137174
 cosmetic: 46275
 scriptlet: 19571
 html: 1831
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38369-112, 1m Δ
  ublock-badware: 9008-1, 1m Δ
  ublock-privacy: 921-2, 1m Δ
  ublock-unbreak: 2376-2, 1m Δ
  ublock-quick-fixes: 90-3, 1m Δ
  easylist: 86279-543, 1m Δ
  easyprivacy: 51012-750, 1m Δ
  urlhaus-1: 14735-0, 1m
  plowe-0: 3627-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 320 ms (selfie)
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  adligature.com: 2
  faltercollection.com: 6
  googletagmanager.com: 2
  histats.com: 2
  onesignal.com: 2
  outbrain.com: 1
  quantserve.com: 1
  sharethis.com: 4
  srvtrck.com: 2
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b857aa036c2bf4481cf39b684bfa6c71f3287d90
