### ISSUE TITLE
n1info.rs: ads

### ISSUE THREAD

**Issue by Onako2** [uBlockOrigin/uAssets#23954]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://n1info.rs/vesti/najnovije-vesti-uzivo-lokalni-izbori-2024/
```

### Description

There are ads on the Serbian news site N1 that aren't (yet) in u-Block Origin filters, on the top and on the right. In the screenshots the ads are in red squares.  What I currently found out is that "halooglasi.com" delivers ads for "Halo nekretnine".

### Other extensions used

KeeVault, Feedbro, Tree Style Tabs, Sponsorblock for YouTube, 7TV, Tampermonkey(No script installed that affects that specific website), Return YouTube Dislike, Indie wiki buddy, Buster: Captcha Solver

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-02 at 21-53-48 BLOG Lokalni izbori u Srbiji Prvi rezultati za Beograd i Niš protestni skup u Novom Sadu](https://github.com/uBlockOrigin/uAssets/assets/79749977/4918ca93-fd3c-41cf-bc35-28871ae361f3)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 162979
 cosmetic: 187620
 scriptlet: 48308
 html: 2093
listset (total-discarded, last-updated):
 removed:
  DEU-0: null
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 56-0, 8d.7h.28m
  https://raw.githubusercontent.com/Onako2/never-gonna-rickroll-me/main/filterlist.txt: 62-56, 1d.5h.31m
  adguard-generic: 81069-3987, 4d.5h.56m
  curben-phishing: 542-0, 1h.16m
  fanboy-cookiemonster: 51101-184, 1h.35m
  ublock-annoyances: 5859-106, 1h.39m Δ
  adguard-cookies: 29852-3769, 2d.15m
  adguard-popup-overlays: 27106-325, 2d.23h.48m
  easylist-newsletters: 7521-536, 3d.2h.30m
  easylist-notifications: 3018-168, 3d.2h.30m
  ublock-cookies-adguard: 1169-16, 3d.2h.30m
  ublock-cookies-easylist: 1166-1166, 3d.2h.30m
 default:
  user-filters: 49-1, never
  ublock-filters: 38369-112, 1h.39m Δ
  ublock-badware: 9008-1, 1h.39m Δ
  ublock-privacy: 921-2, 1h.39m Δ
  ublock-unbreak: 2376-2, 1h.39m Δ
  ublock-quick-fixes: 90-3, 1h.39m Δ
  easylist: 86279-2000, 7h.48m Δ
  easyprivacy: 51012-160, now
  urlhaus-1: 14735-0, 1h.16m
  plowe-0: 3627-1076, now
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 56 redacted]
userSettings:
 largeMediaSize: 0
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 549 ms (selfie)
 maxAssetCacheWait: 339 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
enable `Dandelion Sprout's Serbo-Croatian filters` list
