### ISSUE TITLE
decrypt.day: detection

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#23958]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://decrypt.day/app/id544007664`

### Category

detection

### Description

Adblockers are detected

### Other extensions used

Free Download Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2024-06-02 at 5 48 27 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/82fd00f4-cbf9-4f71-9700-aa403c0a0063)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 125
filterset (summary):
 network: 211082
 cosmetic: 251141
 scriptlet: 49195
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79161-136, 20m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 20m
  adguard-cookies: 29852-29852, 20m
  adguard-generic: 81119-505, 20m
  adguard-mobile: 9422-51, 20m
  adguard-mobile-app-banners: 5263-5263, 20m
  adguard-other-annoyances: 14404-14404, 20m
  adguard-popup-overlays: 27118-27118, 20m
  adguard-social: 23143-919, 20m
  adguard-spyware: 72319-1121, 20m
  adguard-spyware-url: 1522-5, 20m
  block-lan: 67-0, 20m
  [8 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 87251-2043, 20m
  easyprivacy: 51009-28776, 20m
  plowe-0: 3627-1226, 20m
  ublock-badware: 9006-122, 20m
  ublock-filters: 38299-4057, 20m
  ublock-privacy: 928-401, 20m
  ublock-quick-fixes: 90-5, 20m
  ublock-unbreak: 2319-157, 20m
  urlhaus-1: 14735-0, 20m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5620 ms
 maxAssetCacheWait: 3295 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 59
 network:
  2mdn.net: 2
  clarity.ms: 1
  cloudflareinsights.com: 1
  doubleclick.net: 11
  fonts.googleapis.com: 1
  google-analytics.com: 4
  google.com: 16
  googlesyndication.com: 20
  gstatic.com: 3
 extended:
  ##+js(spoof-css, [id="aswift_0_host"]\, [id="aswift_1_host"]\, […
  ##+js(no-fetch-if, adsbygoogle)
  ###abgc
  ###mys-wrapper
  ##.jar
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###ad_unit
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in the old thread

**Comment by jimmysofat6864** [comment]
> Just continue in the old thread

The current thread is closed. Can that be reopened?
