### ISSUE TITLE
makeuseof.com: breakage

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#23951]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.makeuseof.com/nzxt-function-2-review/`

### Category

breakage

### Description

Video can not be played. Issue is similar to this one: https://github.com/uBlockOrigin/uAssets/issues/23937

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/bb7aa99f-38ec-4b2b-bfdd-1dbc75de1c3f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 137200
 cosmetic: 46377
 scriptlet: 21013
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38291-368, 1m Δ
  ublock-badware: 9006-1, 1m Δ
  ublock-privacy: 928-0, 1m Δ
  ublock-unbreak: 2319-0, 1m Δ
  ublock-quick-fixes: 90-0, 1m Δ
  easylist: 86278-461, 1m Δ
  easyprivacy: 51011-24, 1m Δ
  urlhaus-1: 14735-0, 1m
  plowe-0: 3627-688, 1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6463 ms (selfie)
 maxAssetCacheWait: 585 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  makeuseof.com: 1
  ad.gt: 1
  adsninja.ca: 2
  google-analytics.com: 1
  googletagmanager.com: 2
  sentinelbi.com: 1
  unpkg.com: 1
  viglink.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adsninja-ad-zone
  ##.ad-current
  ##.ad-zone-container
  ##.ad-zone:not(.textads)
  ##.adsninja-ad-zone-container-with-set-height
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-zone
  ##+js(remove-cookie, /articlesRead|previousPage/)
  ##+js(abort-current-script, document.createElement, admiral)
  ##+js(abort-on-property-read, googletag)
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in the old thread.
