### ISSUE TITLE
fmovies24.to: banner

### ISSUE THREAD

**Issue by JakeytheeClown** [uBlockOrigin/uAssets#23950]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://fmovies24.to
```

### Description

There is a banner above the comments that was not here on the last site.

### Other extensions used

MAL-sync and Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="682" alt="Screenshot 2024-06-02 115022" src="https://github.com/uBlockOrigin/uAssets/assets/165510653/bb20fc3d-8c3a-4eea-a2ec-2d9e6f60cf47">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 175896
 cosmetic: 242852
 scriptlet: 47010
 html: 1831
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/Sorrow-San/9anime-adblock-filters/raw/master/9Anime%20filter%20list: 148-3, 16h.11m
  adguard-generic: 81071-3990, 3d.17h.39m
  curben-phishing: 507-0, 16h.11m
  adguard-social: 23144-50, 3d.17h.39m
  adguard-cookies: 29819-41, 3d.17h.39m
  adguard-popup-overlays: 27098-982, 3d.17h.39m
  adguard-mobile-app-banners: 5262-22, 3d.17h.39m
  adguard-other-annoyances: 14390-409, 3d.17h.39m
  adguard-widgets: 2518-9, 3d.17h.39m
  easylist-annoyances: 4646-325, 5d.13h.42m
  easylist-chat: 196-16, 5d.17h.43m
  fanboy-cookiemonster: 51076-3940, 5d.13h.42m
  [6 lists not shown]: [too many]
 default:
  user-filters: 35-1, never
  ublock-filters: 38361-130, 4m Δ
  ublock-badware: 9008-1, 4m Δ
  ublock-privacy: 921-0, 4m Δ
  ublock-unbreak: 2376-2, 4m Δ
  ublock-quick-fixes: 90-0, 4m Δ
  easylist: 86203-2014, 4m Δ
  easyprivacy: 51011-163, 4m Δ
  urlhaus-1: 13775-0, 16h.11m
  plowe-0: 3627-1447, 1d.12h.5m
filterset (user): [array of 35 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6348 ms
 maxAssetCacheWait: 3355 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  amung.us: 1
  bidgear.com: 1
  disqus.com: 2
  google.com: 2
  googletagmanager.com: 1
  roledale.com: 2
  sharethis.com: 2
  tinkleswearfranz.com: 1
 extended:
  ##.sharethis-inline-share-buttons
  ##.icon-facebook-circle
  ##.comment__share
  ##.comment-share__buttons
  ##.share__button-container
  ##.share__button
  ###fb-root:not(body):not(html)
  ###placement-top
  ###thread-share-bar
  ##.comment__share > *
  ###thread-subscribe-button
  ###email-signup
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…

```
</details>

**Comment by mapx-** [comment]
add

`*.gif$domain=fmovies24.to`

@ryanbr
