### ISSUE TITLE
phimtuoitho.tv: popups

### ISSUE THREAD

**Issue by cocoak0la** [uBlockOrigin/uAssets#23968]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://phimtuoitho.tv/`

### Category

popups

### Description

Popup where-ever I click on.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 199612
 cosmetic: 95785
 scriptlet: 39570
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81068-7077, now
  adguard-mobile: 9425-95, now
  adguard-spyware-url: 1522-5, now
  adguard-spyware: 70353-28892, now
  block-lan: 67-0, now
  VIE-1: 1942-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38320-340, 2m Δ
  ublock-badware: 9126-2, 2m Δ
  ublock-privacy: 928-114, 2m Δ
  ublock-unbreak: 2327-3, 2m Δ
  ublock-quick-fixes: 86-0, 2m Δ
  easylist: 86520-679, 2m Δ
  easyprivacy: 51016-721, 2m Δ
  urlhaus-1: 16885-0, now
  plowe-0: 3627-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3563 ms (selfie)
 maxAssetCacheWait: 425 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 31
 network:
  amunfezanttor.com: 3
  googletagmanager.com: 1
  oastoamox.com: 7
  outnidorinoom.com: 2
  tzegilo.com: 1
  upanh.tv: 8
  waust.at: 1
  yonhelioliskor.com: 8
 extended:
  ##.catfish-bottom
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
phimtuoitho.tv##+js(acs, document.documentElement, break;case $.)
phimtuoitho.tv##+js(acs, document.addEventListener, popup)
```

@hoang-rio Sorry, can you check this?
