### ISSUE TITLE
busuanzi.ibruce.info: breakage

### ISSUE THREAD

**Issue by SharwOrange** [uBlockOrigin/uAssets#23963]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://busuanzi.ibruce.info/`

### Category

breakage

### Description

This website provides a JavaScript for counting blog visits, but when I use uBlock Origin, it intercepts the JavaScript

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![图片](https://github.com/uBlockOrigin/uAssets/assets/65716524/0a3200a2-9a18-4058-8573-bb8d7009dfe9)
![图片](https://github.com/uBlockOrigin/uAssets/assets/65716524/8004ee5a-fcf7-41c5-b590-174a5f97ff2b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 153583
 cosmetic: 56960
 scriptlet: 19799
 html: 1831
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 38390-112, now
  ublock-badware: 9102-1, now
  ublock-privacy: 921-2, now
  ublock-unbreak: 2384-2, now
  ublock-quick-fixes: 88-3, now
  easylist: 86497-170, now
  easyprivacy: 51012-65, now
  urlhaus-1: 15910-0, now
  plowe-0: 3627-1061, now
  CHN-0: 26005-195, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 169 ms (selfie)
 maxAssetCacheWait: 47 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  baidu.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's considered as tracker in EasyPrivacy. Please report here: https://github.com/easylist/easylist/issues

**Comment by SharwOrange** [comment]
ok,i will
and thank you
