### ISSUE TITLE
aclu.org: breakage

### ISSUE THREAD

**Issue by colleirose** [uBlockOrigin/uAssets#23967]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.aclu.org/news`

### Category

breakage

### Description

`https://www.aclu.org/news` fails to load any articles when uBlock Origin is enabled. Disabling uBlock Origin fixes this issue

### Other extensions used

I have already disabled them all when testing the site:

Privacy Badger
Wappalyzer
Tampermonkey
Return YouTube Dislike
Indie Wiki Buddy
SponsorBlock
DeArrow
React Developer Tools
Silk - Privacy Pass Client
Firefox's built-in "enhanced tracking protection"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/147954091/b5941652-4214-42b9-be04-a7e46fdee3d5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 151074
 cosmetic: 204522
 scriptlet: 33062
 html: 2094
listset (total-discarded, last-updated):
 added:
  block-lan: 67-0, now
  adguard-social: 23151-49, now
  adguard-cookies: 29865-39, now
  ublock-cookies-adguard: 1173-14, now
  adguard-popup-overlays: 27109-975, now
  adguard-mobile-app-banners: 5269-22, now
  adguard-other-annoyances: 14410-409, now
  adguard-widgets: 2526-9, now
  fanboy-thirdparty_social: 68-3, now
  easylist-annoyances: 4659-300, now
  easylist-chat: 196-16, now
  fanboy-cookiemonster: 51105-3939, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38392-112, now Δ
  ublock-badware: 9128-1, now Δ
  ublock-privacy: 921-2, now Δ
  ublock-unbreak: 2384-2, now Δ
  ublock-quick-fixes: 86-3, now Δ
  easylist: 86520-170, now Δ
  easyprivacy: 51016-65, now Δ
  urlhaus-1: 16885-0, now
  plowe-0: 3627-1062, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 356 ms (selfie)
 maxAssetCacheWait: 126 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.blocklink-container
  ##.floating-action-wrapper
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@colleirose 

add

`aclu.org#@#.blocklink-container`

@ryanbr
