### ISSUE TITLE
vinmec.com: ads

### ISSUE THREAD

**Issue by error-reporting** [uBlockOrigin/uAssets#23966]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vinmec.com/vi/thong-tin-duoc/su-dung-thuoc-toan/hoi-chung-reye-o-tre-em-khi-dung-aspirin/?link_type=related_posts`

### Category

ads

### Description

i see a unblocked native ads

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-06-04-08-45-05-21_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/166897813/9951f774-2e54-4db5-a263-fb7f668c15e1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 126
filterset (summary):
 network: 86461
 cosmetic: 46695
 scriptlet: 19376
 html: 1831
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  easyprivacy: null
  plowe-0: null
  VIE-1: null
 default:
  user-filters: 7-0, never
  ublock-filters: 38821-113, 15m Δ
  ublock-badware: 9096-1, 15m Δ
  ublock-privacy: 922-2, 15m Δ
  ublock-unbreak: 2387-2, 15m Δ
  ublock-quick-fixes: 86-3, 15m Δ
  easylist: 86502-172, 15m Δ
  urlhaus-1: 16885-0, 2m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 14 redacted]
hostRuleset:
 added: [array of 25 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 assetFetchTimeout: 60
 cnameIgnore1stParty: false
 cnameIgnoreRootDocument: false
supportStats:
 allReadyAfter: 1713 ms (selfie)
 maxAssetCacheWait: 1072 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  cloudflareinsights.com: 2
  dmca.com: 2
  fbcdn.net: 1
  googletagmanager.com: 1
  gstatic.com: 1
  vinbase.ai: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Those are the links of the articles of the same websites. We don't address that, you can use this as custom filter

```adb
vinmec.com##.post-related
```
