### ISSUE TITLE
vizertv.in: popups

### ISSUE THREAD

**Issue by rucafdp** [uBlockOrigin/uAssets#23965]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vizertv.in/`

### Category

popups

### Description

when i pause/resume the movie or series it popups a new site, it started happening since today 

### Other extensions used

dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 139987
 cosmetic: 50295
 scriptlet: 21472
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 18-2, never
  easylist: 86502-599, 2m Δ
  easyprivacy: 51014-725, 2m Δ
  plowe-0: 3627-0, now
  spa-1: 5712-15, now
  ublock-badware: 9100-1, 2m Δ
  ublock-filters: 38318-288, 2m Δ
  ublock-privacy: 928-0, 2m Δ
  ublock-quick-fixes: 86-0, 2m Δ
  ublock-unbreak: 2327-3, 2m Δ
  urlhaus-1: 15910-0, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 163 ms (selfie)
 maxAssetCacheWait: 34 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 56
 network:
  amung.us: 16
  cloudflareinsights.com: 9
  gaming1.com: 3
  mdstats.info: 2
  rtmark.net: 8
  tzegilo.com: 2
  viewsoz.com: 4
  waisheph.com: 2
  wayfgwbipgiz.com: 2
  whopstriglot.com: 2
  woapheer.com: 6
 extended:
  ##+js(set-constant, MDCore.adblock, 0)
  ##+js(abort-current-script, $, String.fromCharCode)
  ##+js(adjust-setTimeout, disabled)
  ##+js(no-window-open-if)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give exact link and which exact server did you choose to reproduce the issue?

**Comment by rucafdp** [comment]
> Can you give exact link and which exact server did you choose to reproduce the issue?

https://vizertv.in/filme/online/duro-de-atuar-2

option "legendado" on mixdrop server
