### ISSUE TITLE
hvylya.net

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#2396]
### URL(s) where the issue occurs

`http://hvylya.net/news/digest/v-ssha-sozdayut-mobilnyiy-protivodronovyiy-kompleks.html`

### Describe the issue

a lot of ads from the domain zmctrack.net

### Screenshot(s)

http://jpeg.im/d19a
http://jpeg.im/d19b

### Versions

- Browser/version: Opera 53.0.2907.68 
- uBlock Origin version: 1.16.9.0

### Settings

uBO's default settings

**Comment by mapx-** [comment]
You should enable RUS: Adguard Russian Filter 

However, use these filters:
```
||mixadvert.com^$third-party
hvylya.net##.adsbyyottos
```
