### ISSUE TITLE
welt.de: ads

### ISSUE THREAD

**Issue by D4n2021** [uBlockOrigin/uAssets#23961]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.welt.de/tv-programm-live-stream/
```

### Description

2 ad videos run before the actual livestream starts in the player

### Other extensions used

none

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 140679
 cosmetic: 51384
 scriptlet: 19581
 html: 1831
listset (total-discarded, last-updated):
 default:
  user-filters: 33-6, never
  ublock-filters: 38389-112, 19m
  ublock-badware: 9102-1, 19m
  ublock-privacy: 921-2, 19m
  ublock-unbreak: 2384-2, 19m
  ublock-quick-fixes: 85-3, 19m
  easylist: 86497-170, 19m
  easyprivacy: 51012-65, 19m
  urlhaus-1: 15570-0, 19m
  plowe-0: 3627-1061, 19m
  DEU-0: 7473-37, 19m
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 42 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 899 ms
 maxAssetCacheWait: 247 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 85
 network:
  welt.de: 19
  adnxs.com: 2
  asadcdn.com: 2
  axelspringer.com: 27
  bing.com: 1
  bitmovin.com: 1
  chartbeat.com: 1
  cxense.com: 18
  doubleclick.net: 1
  facebook.net: 1
  googleadservices.com: 1
  googletagmanager.com: 1
  kameleoon.eu: 1
  kameleoon.io: 4
  nmrodam.com: 2
  outbrain.com: 1
  taboola.com: 2
 extended:
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(json-prune, vastUrl)
  ##+js(remove-attr, onmousedown, .ob-dynamic-rec-link, stay)
```
</details>

**Comment by JobcenterTycoon** [comment]
Im a german user and tried with firefox and chrome. Maybe a other contributer can reproduce @mapx-

**Comment by mapx-** [comment]
@D4n2021 maybe you are talking about the "normal" ads for a live television (not injected in the stream as for a registered show)
