### ISSUE TITLE
thenation:com: detection

### ISSUE THREAD

**Issue by Zephiii** [uBlockOrigin/uAssets#23970]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.thenation.com/article/archive/palestinian-liberation-police-abolition/
```

### Description

Shows a popup yelling at you for using an adblocker, with all the same guilt-trippy shit as you've always seen.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/93544652/aed52683-1005-4a97-9f9a-0f6a63e80063)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 142326
 cosmetic: 72978
 scriptlet: 22157
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 29831-35, now
 default:
  user-filters: 88-0, never
  easylist: 87259-464, never
  easyprivacy: 50998-711, never
  plowe-0: 3627-0, 1m
  ublock-badware: 8991-1, never
  ublock-filters: 38244-366, never
  ublock-privacy: 878-0, never
  ublock-quick-fixes: 86-0, 40m Δ
  ublock-unbreak: 2304-0, never
  urlhaus-1: 16885-0, 3m
filterset (user): [array of 90 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  thenation.com: 1
  chartbeat.com: 1
  connatix.com: 2
  facebook.net: 1
  googletagmanager.com: 1
  newrelic.com: 2
  onesignal.com: 1
  pub.network: 2
  sail-horizon.com: 1
  sharethis.com: 3
  speedcurve.com: 1
 extended:
  ##.ad
  ##[data-freestar-ad][id]
  ###cookies-policy
  ###ad-leaderboard
  ##.ad.leaderboard
  ##.ad-block
  ##.ad-content:not(:empty)
  #@#.ad-content
  ##+js(abort-on-property-read, ___tp)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
thenation.com#@#.ad
```

@ryanbr
