### ISSUE TITLE
ebay.com: nuisance

### ISSUE THREAD

**Issue by EtherealDusk2024** [uBlockOrigin/uAssets#23973]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ebay.com/`

### Category

nuisance

### Description

Pop-ad for $5 Off when you purchase in the app. It has an expiration date but simply pops back up continuously with a different expiration date. I have tried blocking all elements one at a time, but whatever I do it will put a transparent layer across the entire screen.

### Other extensions used

Capital One Shopping, Fluff Busting Purity, Norton Password Manager, Read Aloud

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/171727524/bd206917-52e9-4813-9d30-a6567fc4c4e6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 145115
 cosmetic: 100298
 scriptlet: 28620
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-mobile-app-banners: 5271-1112, now
  adguard-other-annoyances: 14411-362, now
  adguard-popup-overlays: 27115-915, now
  adguard-widgets: 2528-40, now
  easylist-annoyances: 4658-96, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7530-13, now
  easylist-notifications: 3020-3, now
  ublock-annoyances: 5914-33, now
 default:
  user-filters: 20-0, never
  easylist: 86567-632, now
  easyprivacy: 51011-817, now
  plowe-0: 3627-0, now
  ublock-badware: 9128-1, now
  ublock-filters: 38336-597, now
  ublock-privacy: 928-0, now
  ublock-quick-fixes: 87-0, now
  ublock-unbreak: 2327-2, now
  urlhaus-1: 16140-0, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 25 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 288 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  ebay.com: 4
  doubleclick.net: 2
  ebayrtm.com: 2
  ebaystatic.com: 3
 extended:
  ##li.vl-carousel__item.carousel__snap-point:nth-of-type(3)
  ##.evo.vl-atf-module-js.vl-banner-carousel.vl-module-full-wide.v…
  ##.vl-atf-module-js.vl-banner-carousel.vl-module-full-wide.vl-mo…
  ##html:style(overflow: auto !important; position: initial !impor…
```
</details>

**Comment by peace2000** [comment]
How do you exactly reproduce that dialog? I'm logged in but I'm not seeing that.

**Comment by EtherealDusk2024** [comment]
It doesn't do it all of the time, but when I click on the eBay logo in the
top left, and then click on 'saved', that is usually when it pops up. It
does it like 4x a day and then starts over the next day. When it pops up
again I'll take a screenshot of the source code. Not sure if it matters,
but this is on my PC, I do not visit eBay on my phone. Thanks!

**Comment by EtherealDusk2024** [comment]
This is what I see when it pops up-- 
![filters](https://github.com/uBlockOrigin/uAssets/assets/171727524/2f36e112-26a4-4514-842b-c6b2ef12f188)
![filters2](https://github.com/uBlockOrigin/uAssets/assets/171727524/a313cb62-f311-4e6d-b445-f19d67c4b86b)

**Comment by peace2000** [comment]
I don't see those element names.

What does this filter do in your end:

`ebay.com###ghfd`

?

**Comment by EtherealDusk2024** [comment]
So far, so good. Thanks!
