### ISSUE TITLE
[AdBlock Blocker] anime-extremo.com

### ISSUE THREAD

**Issue by sigtus** [uBlockOrigin/uAssets#2397]
### URL(s) where the issue occurs

`https://www.anime-extremo.com/steins-gate-2424-ova-movie-sub-esp-mega`

### Describe the issue

uBlock is blocked.

### Screenshot(s)

https://i.imgur.com/6HZ5qU8.png

### Versions

- Browser/version: Firefox 60.0.1
- uBlock Origin version: 1.16.8

### Settings

- Default.

**Comment by KiLL4FuNK** [comment]
@sigtus update the filters watch the mini tutorial video
https://streamable.com/jdivj

**Comment by okiehsch** [comment]
I can reproduce with Firefox.

**Comment by sigtus** [comment]
It's blocked again. At least the download button does block.

**Comment by okiehsch** [comment]
Waaht exactly is blocked?

**Comment by sigtus** [comment]
Sorry, I didn't have in mind I had this link in OP.
Here's a more recent one: https://www.anime-extremo.com/mob-psycho-100-latino/
It's really weird how it works, at least for me.
Thanks in advance.

**Comment by okiehsch** [comment]
I get an error message, even if I disable uBO completey if I click descargar, can you actually download a file?

**Comment by sigtus** [comment]
Yes, this is what I get if I disable uBlock:
[](https://i.imgur.com/WfVTsPR.png)
And after waiting 30s, I click descargar again and it redirects me here:
[](http://enlaces.anime-extremo.com/?v=875)
It's really weird since it uses something like linuxseguridad.

**Comment by okiehsch** [comment]
Well, sorry I can't help this is what happens on my end if I click descargar with uBO disabled.
![image](https://user-images.githubusercontent.com/16838044/45580399-f7620e00-b890-11e8-84ff-921149e47641.png)

Maybe somebody else can reproduce, I will reopen.

**Comment by okiehsch** [comment]
OK, looking at the source I found a fix that works on my end.
@sigtus does
`anime-extremo.com##+js(abort-current-inline-script.js, jQuery, Proteger)`
work for you?

**Comment by sigtus** [comment]
Works so perfectly it really looks like magic.
Thank you.
