### ISSUE TITLE
haqqin.az: ads

### ISSUE THREAD

**Issue by kachubey** [uBlockOrigin/uAssets#23974]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://haqqin.az/news/318359`

### Category

ads

### Description

large banners at the top of the site that cannot be removed with a picker mode

### Other extensions used

SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/85690059/29cce77a-a7fb-40fc-96fd-075a477177d5)
![image](https://github.com/uBlockOrigin/uAssets/assets/85690059/8d8b8a3f-70d8-4070-9013-5f3cc7412b7e)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138974
 cosmetic: 46445
 scriptlet: 21039
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 9-1, never
  easylist: 86563-558, 1h.51m Δ
  easyprivacy: 51015-712, 1h.51m Δ
  plowe-0: 3627-0, now
  ublock-badware: 9128-1, 1h.51m Δ
  ublock-filters: 38334-274, 1h.51m Δ
  ublock-privacy: 928-0, 1h.51m Δ
  ublock-quick-fixes: 86-0, 1h.51m Δ
  ublock-unbreak: 2327-0, 1h.51m Δ
  urlhaus-1: 16140-0, now
filterset (user): [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 448 ms (selfie)
 maxAssetCacheWait: 28 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  haqqin.az: 3
  2mdn.net: 2
  adriver.ru: 1
  facebook.com: 2
  google-analytics.com: 1
  twitter.com: 1
  yadro.ru: 1
 extended:
  ##.top-banner
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/\{"brs_content_label":[^,]…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
```
</details>

**Comment by mapx-** [comment]
russian site => subscribe `RU AdList`
