### ISSUE TITLE
Blocking "Sign in to (website) with Google" popups

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#23979]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://stackoverflow.com/
https://medium.com/
https://www.reddit.com/
```

### Description

When I open one of the websites listed in the URL list, I see the annoying Google login popup. Is it better to include a filter or option to disable this popup?

I added this custom filter and it seems to work:
`||accounts.google.com/gsi/iframe`

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

StackOverflow

![stackoverflow](https://github.com/uBlockOrigin/uAssets/assets/62190484/5c188eb3-0b9c-473d-a8c9-bb4058ef00a3)

Medium

![medium](https://github.com/uBlockOrigin/uAssets/assets/62190484/14f5931b-8571-41cd-b73f-9537be308b1f)

Reddit

![reddit](https://github.com/uBlockOrigin/uAssets/assets/62190484/03f9c470-11fb-48cc-a2f7-1b09e6993db5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 140676
 cosmetic: 53038
 scriptlet: 19594
 html: 1833
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38410-114, 1h.46m Δ
  ublock-badware: 9155-1, 1h.46m Δ
  ublock-privacy: 921-0, 1h.46m Δ
  ublock-unbreak: 2384-2, 1h.46m Δ
  ublock-quick-fixes: 87-3, 1h.46m Δ
  easylist: 86579-171, 1h.46m Δ
  easyprivacy: 51011-65, 1h.46m Δ
  urlhaus-1: 16140-0, 12h.28m
  plowe-0: 3727-1160, 6d.23h.50m
  ITA-0: 8431-36, 12h.27m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 110 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
```
</details>

**Comment by krystian3w** [comment]
For Firefox 128+ maybe:

```adb
###credential_picker_container:has(iframe[src*="accounts.google.com"])
```

https://github.com/uBlockOrigin/uAssets/discussions/23165

**Comment by mapx-** [comment]
@fabriziobagala 
enable `AdGuard – Popup Overlays`

report at https://github.com/AdguardTeam/AdguardFilters/issues
asking to add to the filter 

    ||accounts.google.com/gsi/client^$third-party,script,domain=dtf.ru|stackoverflow.com|vc.ru|pikabu.ru|nytimes.com|baltimoresun.com|rozetka.com.ua|estadao.com.br|medium.com

`reddit.com` too

**Comment by fabriziobagala** [comment]
> @fabriziobagala enable `AdGuard – Popup Overlays`
> 
> report at https://github.com/AdguardTeam/AdguardFilters/issues asking to add to the filter
> 
> ```
> ||accounts.google.com/gsi/client^$third-party,script,domain=dtf.ru|stackoverflow.com|vc.ru|pikabu.ru|nytimes.com|baltimoresun.com|rozetka.com.ua|estadao.com.br|medium.com
> ```
> 
> `reddit.com` too

@mapx- I noticed that just enable the `AdGuard - Annoyances` filter and the problem is solved.

**Comment by krystian3w** [comment]
> asking to add to the filter `reddit.com` too

You reproduced big pop-up in Chromium to add network filtering?

Generic cosmetic filter should works unitl someone use `@@$ghide`.

**Comment by bughit** [comment]
`(AdGuard|EasyList) - Annoyances` have been blocking these, but I just ran into to it on [reddit](https://www.reddit.com/r/firefox/) (firefox 128)

Can this be addressed in a ublock list, generically?

**Comment by bughit** [comment]
@mapx- None of the existing lists are blocking these. Please reopen.

**Comment by D4niloMR** [comment]
You can open an issue in their repositories.

**Comment by bughit** [comment]
And why must this be handled in a third party list and not "uBlock filters – Annoyances"?

**Comment by bughit** [comment]
> It is preferred to fix filter issues in EasyList

I opened an easylist issue (easylist/easylist#19808). They are pretending its already blocked when it clearly isn't ([repro steps](/easylist/easylist/issues/19808#issuecomment-2330568505)).

**Comment by stephenhawk8054** [comment]
I can reproduce. It's caused by `@@||reddit.com^$generichide`

**Comment by stephenhawk8054** [comment]
Fixed in EL https://github.com/easylist/easylist/commit/47fea2b7983e6536ab6bdafbb8a2dbcf36f514ba

**Comment by bughit** [comment]
Both in this issue and and my easylist one, reddit is only an example. There are many sites that support google sign in ad are affected by this. It doesn't make sense to address them individually, this should be blocked generically.

**Comment by stephenhawk8054** [comment]
The generic filters are already in EL annoyance list:

https://github.com/easylist/easylist/blob/6b0a7ed80d6c92cd4a41d6b01fd11120685ca513/fanboy-addon/fanboy_annoyance_general_hide.txt#L121-L123

Only some sites need the filter `$generichide` due to webcompat / anti-adblock / breakages and therefore the generic filters cannot apply:

https://github.com/easylist/easylist/blob/6b0a7ed80d6c92cd4a41d6b01fd11120685ca513/easylist/easylist_allowlist.txt#L295

Users need to report those sites. All other sites that don't have `$generichide` don't need to address individually.
