### ISSUE TITLE
wuthering.th.gl: detection

### ISSUE THREAD

**Issue by lampham7** [uBlockOrigin/uAssets#23980]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wuthering.th.gl/`

### Category

detection

### Description

After 1 sec, a window saying Ad Blocker Detected appears

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/77009602/aed60270-a898-4a64-bb75-8eef4a52a2ba)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138412
 cosmetic: 46439
 scriptlet: 21049
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 86589-563, 1h.51m Δ
  easyprivacy: 51012-694, 1h.51m Δ
  plowe-0: 3627-0, 18m
  ublock-badware: 9189-1, 1h.51m Δ
  ublock-filters: 38347-274, 1h.51m Δ
  ublock-privacy: 928-0, 1h.51m Δ
  ublock-quick-fixes: 87-0, 1h.51m Δ
  ublock-unbreak: 2334-18, 1h.51m Δ
  urlhaus-1: 15490-0, 18m
filterset (user): [array of 6084 redacted]
trustedset:
 added: [array of 34 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 385 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  nitropay.com: 1
 extended:
  ##+js(set-constant, nitroAds, {})
  ##+js(set-constant, nitroAds.createAd, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Wait about 5-6 hours and update the filter lists again. Or use this filter as your custom filter in the meantime:

```adb
th.gl##+js(nostif, error)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
