### ISSUE TITLE
tejtime24.com: detection

### ISSUE THREAD

**Issue by preetam1409** [uBlockOrigin/uAssets#23983]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tejtime24.com/dunki-box-office-collection/`

### Category

detection

### Description

detects adblocker 
original link - https://lksfy.com/i1cxrB

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/43402156/08ad7915-1d65-4c62-bde1-7c33cdd4d78c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 139367
 cosmetic: 46447
 scriptlet: 21057
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 37-0, never
  ublock-filters: 38345-294, 24m Δ
  ublock-badware: 9189-1, 10m Δ
  ublock-privacy: 928-0, 10m Δ
  ublock-unbreak: 2334-0, 10m Δ
  ublock-quick-fixes: 87-0, 24m Δ
  easylist: 86589-563, 24m Δ
  easyprivacy: 51012-711, 10m Δ
  urlhaus-1: 16445-0, 24m
  plowe-0: 3627-0, now
filterset (user): [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 113 ms (selfie)
 maxAssetCacheWait: 31 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  tejtime24.com: 1
  adpushup.com: 2
  googletagmanager.com: 1
  netpub.media: 1
  youtube.com: 2
 extended:
  ##.quads-location:others()
  ##+js(prevent-fetch, ads)
  ##+js(adjust-setInterval, interval, *)
```
</details>

**Comment by preetam1409** [comment]
its not working I checked

**Comment by preetam1409** [comment]
on step 3/4 the next button is not visible or it seems like it gets blocked by adblocker ...

**Comment by stephenhawk8054** [comment]
@preetam1409 Next time report the shortener sites to here: https://github.com/uBlockOrigin/uAssets/discussions/17361
