### ISSUE TITLE
fx545.site: detection

### ISSUE THREAD

**Issue by Alessio979** [uBlockOrigin/uAssets#23985]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://fx545.site/wf/cwasqerzxvdt/fi967cyv5web/NVpxSWExN0tmUkdzYVNwS0pkZC9PQT09
```

### Description

Problem with this video? Disable Your Adblock

Thanks

### Other extensions used

Norton
Video downloadhelper
myjdownloader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 223065
 cosmetic: 259560
 scriptlet: 52994
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80968-7176, never
  adguard-mobile: 9425-186, never
  adguard-spyware-url: 1525-120, never
  adguard-spyware: 70360-29008, never
  block-lan: 67-0, never
  curben-phishing: 564-1, never
  adguard-cookies: 29976-3796, never
  ublock-cookies-adguard: 1173-0, never
  fanboy-cookiemonster: 51106-228, never
  ublock-cookies-easylist: 1173-1173, never
  adguard-social: 23166-786, never
  fanboy-social: 16224-7, never
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38318-284, 1d.18h.46m Δ
  ublock-badware: 9100-1, 1d.18h.46m Δ
  ublock-privacy: 928-0, 1d.18h.46m Δ
  ublock-unbreak: 2327-0, 1d.18h.46m Δ
  ublock-quick-fixes: 87-0, 7m
  easylist: 86502-573, 1d.18h.46m Δ
  easyprivacy: 51014-711, 1d.18h.46m Δ
  urlhaus-1: 16445-0, 7m
  plowe-0: 3627-0, 4d.6h.56m
  ITA-0: 8431-19, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1277 ms (selfie)
 maxAssetCacheWait: 1069 ms
 cacheBackend: indexedDB

```
</details>

**Comment by Alessio979** [comment]
if it can help you, works with cosmetic filtering off.
Thanks

**Comment by stephenhawk8054** [comment]
@Alessio979 Can you test this filter?

```adb
@@||fx545.site^$ghide
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Alessio979** [comment]
> @Alessio979 Can you test this filter?
> 
> ```
> @@||fx545.site^$ghide
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

I can't try now, I'll try it as soon as I get home.
Thanks

**Comment by Alessio979** [comment]
`@@||fx545.site^$ghide `
it's OK

**Comment by Alessio979** [comment]
no works anymore
