### ISSUE TITLE
weibo.cn: nuisance

### ISSUE THREAD

**Issue by DidNotWantToCreateGithubAccount** [uBlockOrigin/uAssets#23990]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://m.weibo.cn/detail/5042239333733134`

### Category

nuisance

### Description

`https://m.weibo.cn` domain keeps showing me an address bar popup that urges me to install their app. This issue happens daily and usually when I click a second picture or when I stay in the same page for long enough.

### Other extensions used

Download HLS streams, Tampermonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![app install popup](https://github.com/uBlockOrigin/uAssets/assets/170854128/8f0cfafb-a2ff-48a1-ad41-c364b29a0b6f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 206952
 cosmetic: 166958
 scriptlet: 52114
 html: 0
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99501-99501, now
  adguard-generic: 80952-7323, now
  adguard-mobile: 9432-94, now
  adguard-mobile-app-banners: 5275-21, now
  adguard-other-annoyances: 14417-375, now
  adguard-popup-overlays: 27130-975, now
  adguard-spyware: 70360-28954, now
  adguard-widgets: 2528-54, now
  block-lan: 67-0, now
  easylist-annoyances: 4659-950, now
  easylist-chat: 196-12, now
  easylist-newsletters: 7530-1875, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 801-11, never
  KOR-1: 4969-101, 5m
  easylist: 86592-14718, 5m Δ
  easyprivacy: 51017-108, 5m Δ
  plowe-0: 3627-787, now
  ublock-badware: 9208-1, 5m Δ
  ublock-filters: 38360-862, 5m Δ
  ublock-privacy: 928-7, 5m Δ
  ublock-quick-fixes: 87-0, 5m Δ
  ublock-unbreak: 2336-24, 5m Δ
  urlhaus-1: 15900-0, now
filterset (user): [array of 802 redacted]
trustedset:
 added: [array of 69 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 506 ms (selfie)
 maxAssetCacheWait: 297 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  weibo.cn: 1
  baidu.com: 4
  google-analytics.com: 5
  google.com: 1
 extended:
  ##+js(abort-current-script, console.log, location.replace)
  ##+js(no-window-open-if, &disp=popup, 1)
```
</details>

**Comment by mapx-** [comment]
@cjx82630

**Comment by mapx-** [comment]
test this filter

`m.weibo.cn##+js(set, alert, noopFunc)`

**Comment by DidNotWantToCreateGithubAccount** [comment]
> test this filter
> 
> `m.weibo.cn##+js(set, alert, noopFunc)`

Sorry, I'm so new to github that I didn't know feedback is a thing. The issue still persists with the filter.
