### ISSUE TITLE
roblox.com: nuisance

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#23997]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.roblox.com/home
```

### Description

I'm not sure if this counts as an issue, but I hope it does. With ubo enabled, it blocks ads, but everything that was previously in the middle is now shifted to the far right. (btroblox extension does not affect this, happens when disabled too)

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/c02588cf-7be7-45bc-973a-7eaf492a984a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 220941
 cosmetic: 252589
 scriptlet: 51438
 html: 2095
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81055-3992, 2d.10h.28m
  adguard-mobile: 9425-58, 2d.10h.28m
  adguard-spyware-url: 1522-120, 2d.10h.28m
  adguard-spyware: 70355-1513, 2d.10h.28m
  block-lan: 67-0, 13d.45m
  curben-phishing: 549-0, 36m
  adguard-social: 23152-55, 2d.10h.28m
  adguard-cookies: 29866-46, 2d.10h.28m
  ublock-cookies-adguard: 1174-14, 5d.21h.54m
  adguard-popup-overlays: 27111-1002, 2d.10h.29m
  adguard-mobile-app-banners: 5269-23, 2d.22h.54m
  adguard-other-annoyances: 14410-412, 2d.22h.54m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38437-112, 3h.39m Δ
  ublock-badware: 9210-0, 3h.39m Δ
  ublock-privacy: 921-2, 3h.39m Δ
  ublock-unbreak: 2393-2, 3h.39m Δ
  ublock-quick-fixes: 87-2, 3h.39m Δ
  easylist: 86595-2247, 3h.39m Δ
  easyprivacy: 51017-28475, 3h.39m Δ
  urlhaus-1: 15900-0, 9h.24m
  plowe-0: 3627-1555, 36m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2076 ms
 maxAssetCacheWait: 1553 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  roblox.com: 12
  ns1p.net: 1
 extended:
  ##.alert-cookie-notice
  ###cookie-banner-wrapper
  ##div.cookie-banner-wrapper
  ###Skyscraper-Abp-Right
  #@##Skyscraper-Abp-Left
  #@#.abp

```
</details>

**Comment by D4niloMR** [comment]
It was [fixed yesterday](https://github.com/AdguardTeam/AdguardFilters/issues/180898) in AdGuard Base. [Click here](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=adguard-generic) to update filters.
