### ISSUE TITLE
lostpod.space: breakage

### ISSUE THREAD

**Issue by PhieF** [uBlockOrigin/uAssets#23992]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://lostpod.space
```

### Description

Lostpod.space is my peertube instance,  when visiting this video from another website like this one https://videos.john-livingston.fr/w/wRoyJvUZEu8AQnqm5phoga

the video is blocked by this rule 

```
/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space|uno|cfd)\/[a-z0-9]{6,}\//$xhr,3p,from=~127.0.0.1|~bitrix24.life|~ccc.ac|~jacksonchen666.com|~lemmy.world|~localhost|~mempool.space|~scribble.ninja|~scribble.website|~spacepub.space|~traineast.co.uk
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran du 2024-06-06 14-45-22](https://github.com/uBlockOrigin/uAssets/assets/26841885/4bf34a93-004f-444d-b1d1-5930a0e07b78)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 156334
 cosmetic: 53057
 scriptlet: 21198
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38360-438, 5m
  ublock-badware: 9208-0, 5m
  ublock-privacy: 928-0, 5m
  ublock-unbreak: 2327-0, 5m
  ublock-quick-fixes: 87-0, 5m
  easylist: 86594-481, 5m
  easyprivacy: 51015-711, 5m
  urlhaus-1: 16130-0, 5m
  plowe-0: 3627-0, 5m
  FRA-0: 24491-312, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4502 ms
 maxAssetCacheWait: 1911 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  lostpod.space: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||lostpod.space/static/streaming-playlists/$xhr,domain=videos.john-livingston.fr`

**Comment by PhieF** [comment]
@mapx- the problem can be from any peertube, not only videos.john-livingston.fr I don't know if your regex is only to allow videos.john-livingston.fr but it won't be enough if somebody tries to stream lostpod.space videos from another server and I guess streaming-playlists could be not enough also because some videos are using other endpoints, and perhaps even worst for the tchat of live videos, could it be possible to allow whole domain ?

**Comment by mapx-** [comment]
provide other examples

**Comment by mapx-** [comment]
@ryanbr 

`/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space|uno|cfd)\/[a-z0-9]{6,}\//$xhr,3p,from=~127.0.0.1|~bitrix24.life|~ccc.ac|~jacksonchen666.com|~lemmy.world|~localhost|~mempool.space|~scribble.ninja|~scribble.website|~spacepub.space|~traineast.co.uk|~lostpod.space`

**Comment by PhieF** [comment]
@mapx- 
still not working for example when playing the video from this peertube server

https://exode.me/w/wRoyJvUZEu8AQnqm5phoga

also broken here

https://tube.todon.eu/w/wRoyJvUZEu8AQnqm5phoga

even though it now works from that one
https://videos.john-livingston.fr/w/wRoyJvUZEu8AQnqm5phoga


I'm not sure this kind of filters is adapted to federated network, since the call can be made from any domain hosting an activitypub server

here is the filter

```
/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space|uno|cfd)\/[a-z0-9]{6,}\//$xhr,3p,from=~127.0.0.1|~bitrix24.life|~ccc.ac|~jacksonchen666.com|~lemmy.world|~localhost|~lostpod.space|~mempool.space|~scribble.ninja|~scribble.website|~spacepub.space|~traineast.co.uk
```
I'm not really good with regex, sorry


here is the debogage info

```

uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 156942
 cosmetic: 52957
 scriptlet: 19741
 html: 1834
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38425-112, 4m
  ublock-badware: 9218-0, 4m
  ublock-privacy: 920-2, 4m
  ublock-unbreak: 2393-2, 4m
  ublock-quick-fixes: 78-2, 4m
  easylist: 86628-176, 9m Δ
  easyprivacy: 51023-64, 9m Δ
  urlhaus-1: 16720-0, now
  plowe-0: 3555-989, now
  FRA-0: 24492-396, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2776 ms
 maxAssetCacheWait: 178 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  lostpod.space: 2
```

**Comment by mapx-** [comment]
right, this should work:

    /^https?:\/\/(?!lostpod)[0-9a-z]{5,}\.(digital|website|life|guru|space|uno|cfd)\/[a-z0-9]{6,}\//$xhr,3p,from=~127.0.0.1|~bitrix24.life|~ccc.ac|~jacksonchen666.com|~lemmy.world|~localhost|~mempool.space|~scribble.ninja|~scribble.website|~spacepub.space|~traineast.co.uk
