### ISSUE TITLE
needrom.com: detection

### ISSUE THREAD

**Issue by yegetshalaay** [uBlockOrigin/uAssets#24008]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.needrom.com/download/infinix-zero-8i-x687b-14/`

### Category

detection

### Description

It detects uBlock Origin.

### Other extensions used

Only Privacy Badger.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240608-005305](https://github.com/uBlockOrigin/uAssets/assets/91019435/34e8b86a-ce5c-4876-90b9-a1eaf7c7e5e4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 125
filterset (summary):
 network: 194303
 cosmetic: 152054
 scriptlet: 35447
 html: 2096
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1531-120, never
  adguard-spyware: 70372-28978, never
  adguard-cookies: 30011-1684, never
  ublock-cookies-adguard: 1217-1217, never
  adguard-popup-overlays: 27152-953, never
  adguard-mobile-app-banners: 5293-49, never
  adguard-other-annoyances: 14429-425, never
  adguard-widgets: 2531-85, never
  easylist-annoyances: 4660-915, never
  easylist-chat: 196-12, never
  fanboy-cookiemonster: 51121-19870, never
  ublock-cookies-easylist: 1218-0, never
  [3 lists not shown]: [too many]
 default:
  user-filters: 38-0, never
  ublock-filters: 38867-314, 4m
  ublock-badware: 9212-16, 4m
  ublock-privacy: 921-3, 4m
  ublock-unbreak: 2396-3, 4m
  ublock-quick-fixes: 78-2, 4m
  adguard-mobile: 9436-199, never
  easylist: 86618-14697, never
  easyprivacy: 51022-63, never
  urlhaus-1: 16675-0, never
  plowe-0: 3555-615, never
  TUR-0: 13238-240, never
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6136 ms (selfie)
 maxAssetCacheWait: 688 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  inmobi.com: 1
  statcounter.com: 2
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(no-setTimeout-if, /adsbygoogle|adblock/)
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, disable other extensions
