### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by BRoenfeldt** [uBlockOrigin/uAssets#24000]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Description

When clicking on a video to watch the video doesn't start and the youtubes video player throws an error. There is no error code given other than the playback ID that changes each time you refresh the page, even with the same video.
![image_2024-06-06_151928832](https://github.com/uBlockOrigin/uAssets/assets/131790367/dabfa908-0114-4ec8-a991-0b0067f5d2db)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/131790367/2b8d57b3-6644-4d63-9789-dfc79788d135)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 139090
 cosmetic: 46458
 scriptlet: 21049
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86605-44, now
  easyprivacy: 51018-723, now
  plowe-0: 3627-376, now
  ublock-badware: 9208-16, now
  ublock-filters: 38359-369, now
  ublock-privacy: 928-3, now
  ublock-quick-fixes: 87-2, 45m Δ
  ublock-unbreak: 2336-15, now
  urlhaus-1: 16130-0, 45m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 524 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 37
 network:
  youtube.com: 21
  doubleclick.net: 4
  google.com: 5
  googlesyndication.com: 7
 hasUnprocessedRequest: true
 extended:
  ###masthead-ad
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> #content > ytd-ad-slot-renderer)
```
</details>

**Comment by Lonmine** [comment]
Fortunately it is still possible to watch Lives
