### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by reyland44** [uBlockOrigin/uAssets#24003]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/search?client=firefox-b-d&q=forza+horizon5++patch+notes`

### Category

breakage

### Description

For a few weeks now specifically on Firefox desktop Google Search has been acting weird. 

The preferences (language, region, dark mode) keep resetting every time I go an hour without googling something.

Basically after not using Google Search for some time and I go to search something, the preferences are reset and the page is in light mode. I then change it back to English language and dark mode and it's fine for a bit and then resets again when I go some time without googling. 

I've turned off the firefox tracking protection and tested without uBO and it works fine. Soon as I turn on uBO it resets.

### Other extensions used

SponsorBlock
Return YouTube Dislikes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 192564
 cosmetic: 91492
 scriptlet: 24702
 html: 1833
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 56259-0, 19m
  fanboy-cookiemonster: 51121-183, 46m
  ublock-cookies-easylist: 1179-3, 46m
 default:
  ublock-filters: 38437-112, 45m
  ublock-badware: 9218-2, 45m
  ublock-privacy: 921-2, 45m
  ublock-unbreak: 2393-2, 45m
  ublock-quick-fixes: 78-2, 45m
  easylist: 86618-176, 45m
  easyprivacy: 51022-67, 46m
  urlhaus-1: 16195-4714, 46m
  plowe-0: 3627-1061, 46m
filterset (user): [array of 46 redacted]
trustedset:
 added: [array of 19 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 130 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  google.com: 19
 extended:
  ###main a[href][data-sb^="/url?"]:remove-attr(data-sb)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by peace2000** [comment]
@reyland44 

Have you emptied your browser cache during the past two weeks?

**Comment by reyland44** [comment]
Nope, I'll do it now and report back

**Comment by reyland44** [comment]
@peace2000 

Unfortunately that didn't fix it. Just had it happen again.

I should also note it only seems to happen on Firefox desktop and Brave mobile. On Chrome and Brave desktop it doesn't happen.

**Comment by peace2000** [comment]
@reyland44 I suspect it's because the cookie will only be set for a session...

Please try these filters:

`www.google.*#@#+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjQwNTE0LjA2X3AwGgJmaSADGgYIgOu0sgY)`

`www.google.*##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjQwNTE0LjA2X3AwGgJmaSADGgYIgOu0sgY, 1year)`

The first one will disable the current filter and the second filter will set the cookie expire time 1 year ahead.

You need to click `Allow custom filters requiring trust` for those to work.

**Comment by reyland44** [comment]
@peace2000 Unfortunately that didn't work either, it's still happening 

Might not be directly related to uBO, but I found a thread with a bunch of people having this issue [here](https://www.reddit.com/r/brave_browser/comments/1d1mglv/google_search_dark_mode_turns_light_mode/)

**Comment by mapx-** [comment]
@reyland44 reset uBO to defaults, clear cookies + storage, test again

**Comment by Gigaturmix** [comment]
I also experienced this issue on my Android Google Chrome browser, where you can't install any extensions. This might be an issue with something else then?

**Comment by krystian3w** [comment]
It would come out that it's a dark theme activation error from the second visit, and in truth there should be a list where @anewuser force it.
