### ISSUE TITLE
everand.com: detection

### ISSUE THREAD

**Issue by ComfortableMilk4454** [uBlockOrigin/uAssets#24001]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.everand.com/read/224326250/Steve-Jobs
```

### Description

adblock detected on everand (see screenshot)

### Other extensions used

<img width="399" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/1e2aaecd-62b9-452d-bd56-143ae5ad226d">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1624" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/49a8210e-dcfb-452e-860e-97fff4e9bfbb">

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 160275
 cosmetic: 156283
 scriptlet: 47003
 html: 2095
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81008-6136, 1h.42m
  adguard-cookies: 29995-43, 1h.42m
  ublock-cookies-adguard: 1175-14, 1h.42m
  fanboy-cookiemonster: 51112-3944, 1h.42m
  ublock-cookies-easylist: 1175-1175, 1h.42m
  ublock-annoyances: 5860-33, 9m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 38434-239, 9m Δ
  ublock-badware: 9213-0, 9m Δ
  ublock-privacy: 921-0, 9m Δ
  ublock-unbreak: 2393-36, 9m Δ
  ublock-quick-fixes: 78-0, 9m Δ
  easylist: 86614-65, 9m Δ
  easyprivacy: 51020-20, 9m Δ
  urlhaus-1: 16130-0, 1h.44m
  plowe-0: 3627-1078, 1h.44m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 206 ms (selfie)
 maxAssetCacheWait: 91 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  github.com: 24
```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/143d7e3d-d53b-4eb8-99f1-b0159bd00393)

**Comment by ComfortableMilk4454** [comment]
huh weird, i even made a new firefox profile and only installed uBO on it with default settings and it still happens.

**Comment by stephenhawk8054** [comment]
@ComfortableMilk4454 Which country are you when accessing the site?

**Comment by ComfortableMilk4454** [comment]
USA

**Comment by ComfortableMilk4454** [comment]
& yes you need to login

**Comment by gorhill** [comment]
@ComfortableMilk4454 Looks like you tampered with the troubleshooting information, as what you provided does not match the webpage you are reporting. Please provide the troubleshooting information for the webpage which has the issue.

**Comment by ComfortableMilk4454** [comment]
oh i apologize i must've copied the troubleshooting info from another website. here is the troubleshooting for the url i provided in op:

uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 160288
 cosmetic: 156283
 scriptlet: 47004
 html: 2095
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81008-3992, 13h.4m
  adguard-cookies: 29995-40, 13h.4m
  ublock-cookies-adguard: 1175-14, 13h.4m
  fanboy-cookiemonster: 51112-3914, 13h.4m
  ublock-cookies-easylist: 1175-1175, 13h.4m
  ublock-annoyances: 5860-108, 34m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 38437-116, 34m Δ
  ublock-badware: 9218-0, 34m Δ
  ublock-privacy: 921-2, 34m Δ
  ublock-unbreak: 2393-0, 34m Δ
  ublock-quick-fixes: 78-0, 34m Δ
  easylist: 86618-2185, 34m Δ
  easyprivacy: 51022-159, 34m Δ
  urlhaus-1: 16130-0, 13h.7m
  plowe-0: 3627-1078, 13h.7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 145 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  sentry-cdn.com: 1
  sentry.io: 1
  siftscience.com: 1
 extended:
  ##.osano-cm-window
  ##+js(prevent-fetch, /api/v1/events)

**Comment by gorhill** [comment]
Does the following filter help?

    @@||everand.com^$ghide

**Comment by ComfortableMilk4454** [comment]
<img width="1624" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/c24e7819-24d4-4292-ad32-f2a87649b871">
<img width="1624" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/43555540/994a7b76-29fb-4fa8-b8f4-2270457976de">
still happens :(

**Comment by D4niloMR** [comment]
Try:

```adb
everand.com##+js(set, Scribd.Blob.AdBlockerModal, noopFunc)
```

**Comment by D4niloMR** [comment]
Added to uBlock filters. The update should come to your filters in 5-6 hours.

**Comment by ComfortableMilk4454** [comment]
awesome tysm!
