### ISSUE TITLE
royalbank.com: breakage

### ISSUE THREAD

**Issue by peakreset** [uBlockOrigin/uAssets#24009]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www1.royalbank.com/sgw1/olb/profile-hub/documents-fr/placements-en-direct/erreur`

### Category

breakage

### Description

Trying to access RBC Direct Investing recently revised "view and manage documents" page, where you can get monthly statements and transactions confirmations.
Tested on the French version of the site only.
Upon attempting to open, a red streetlight page appears, stating that an error happened.
Reloading the page isn't a valid test to check if a configuration change has fixed the issue, it's necessary to go back to the site home page and request the "view and manage documents" page again.
It's the only problematic page on the site that I've found (been using both them and uBO for years).
Issue has been reported to RBC, altough I doubt they'll investigate.
First bug I'm reporting, apologies if I'm doing something wrong.
I'll be monitoring the bug, feel free to ask for more info.

### Other extensions used

privacy badger, but the issue was reproduced with PB fully disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 139454
 cosmetic: 46351
 scriptlet: 19578
 html: 1833
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38406-112, now
  ublock-badware: 9218-0, now
  ublock-privacy: 920-2, now
  ublock-unbreak: 2393-2, now
  ublock-quick-fixes: 78-2, now
  easylist: 86627-175, now
  easyprivacy: 51022-64, now
  urlhaus-1: 16495-0, now
  plowe-0: 3555-989, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 319 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  royalbank.com: 7
  googletagmanager.com: 3
  igodigital.com: 2
  taplytics.com: 1
```
</details>

**Comment by mapx-** [comment]
- open uBO logger
- select in the search box of uBO logger only the "blocked" items
- go with the steps to reproduce the issue
- copy & paste here all the requests you see in the logger page
(click
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/99c57a29-d739-45b5-811a-d3a2bd8428b9)
icon and copy the text)

**Comment by peakreset** [comment]
Thank you for looking into this.
I understand that this is the config to use:
![blocked](https://github.com/uBlockOrigin/uAssets/assets/172090051/d38d437c-6ec8-481c-a746-3aad8017f498)
Here's the output. I did anonymize some values. The last two (that looks like UUIDs) were the same.
```
+16
googletagmanager_gtm.js:5
<<
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+16
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+16
||googletagmanager.com^
--
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+16
||collect.igodigital.com^
--
www1.royalbank.com
3
get
script
https://1397885.collect.igodigital.com/collect.js

+13
||oda.markitondemand.com^
--
www1.royalbank.com
3
get
script
https://oda.markitondemand.com/js/wa.js

+13
googletagmanager_gtm.js:5
<<
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+13
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+13
||googletagmanager.com^
--
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+13
||collect.igodigital.com^
--
www1.royalbank.com
3
get
script
https://1397885.collect.igodigital.com/collect.js

+11
/ruxitagentjs_
--
www1.royalbank.com
1
get
script
https://www1.royalbank.com/WebUI/ruxitagentjs_ICA7NVfgqrtux_10291240606133530.js

+11
/ruxitagentjs_
--
www1.royalbank.com
1
get
script
https://www1.royalbank.com/WebUI/ruxitagentjs_ICA7NVfgqrtux_10291240606133530.js

+11
/ruxitagentjs_
--
www1.royalbank.com
1
get
script
https://www1.royalbank.com/ruxitagentjs_ICA7NVfgqrtux_10291240606133530.js

+8
||taplytics.com^$3p
--
www1.royalbank.com
3
get
xhr
https://decision-rbc.taplytics.com/
aliasURL=https://taplytics.royalbank.com/v1/featureflags?token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&user_id=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

+5
googletagmanager_gtm.js:5
<<
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+5
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+5
||googletagmanager.com^
--
www1.royalbank.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-K5TWTL

+4
/ruxitagentjs_
--
www1.royalbank.com
1
get
script
https://www1.royalbank.com/sgw1/api/ruxitagentjs_ICA7NVfgqrux_10291240606133530.js

+3
https://www1.royalbank.com/sgw1/olb/profile-hub/documents-fr/placements-en-direct/consulter-les-doc-electroniques

+2
https://www1.royalbank.com/cgi-bin/rbaccess/rbunxcgi?F22=4WN600S&7ASERVER=N601LD&LANGUAGE=FRENCH&7ASCRIPT=/WebUI/Navigation/Proxy/AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA

+2
/ruxitagentjs_
--
www1.royalbank.com
1
get
script
https://www1.royalbank.com/WebUI/ruxitagentjs_ICA7NVfgqrtux_10291240606133530.js

+2
/ruxitagentjs_
--
www1.royalbank.com
1
get
script
https://www1.royalbank.com/ruxitagentjs_ICA7NVfgqrtux_10291240606133530.js

+0
https://www1.royalbank.com/cgi-bin/rbaccess/rbunxcgi?F22=4WN600S&7ASERVER=N601LD&LANGUAGE=FRENCH&7ASCRIPT=/WebUI/Navigation/CMSProxy/AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA
```

**Comment by mapx-** [comment]
@peakreset 

- try these filters 1 by 1 (not all together)
- report back if the issue is gone using one of them

```
@@||collect.igodigital.com/collect.js$domain=royalbank.com
@@||markitondemand.com/js/wa.js$domain=royalbank.com
@@||taplytics.com^$domain=royalbank.com
@@||googletagmanager.com/gtm.js$domain=royalbank.com
@@/ruxitagentjs_$domain=royalbank.com
```

**Comment by peakreset** [comment]
I tried all 5, and this one fixes it:
> ```
> @@||taplytics.com^$domain=royalbank.com
> ```
The other 4 have no impact.
