### ISSUE TITLE
mariowiki.com: ads

### ISSUE THREAD

**Issue by hyperlexus** [uBlockOrigin/uAssets#24004]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mariowiki.com/List_of_Star_Pieces_in_Paper_Mario:_The_Thousand-Year_Door`

### Category

ads

### Description

consistently plays a video ad of various different things at the bottom right that swipes in and out, and I can't even seem to be able to block it using the pipette tool. 

### Other extensions used

sponsorblock, dearrow, return yt dislike, vidIQ, yt enhancer, addoncrop yt downloader, webtime tracker, premid, google translate, jdownloader, poper blocker, aha music search thingy, checker plus for gmail, youtube remote control, save image as png, new adjacent tab, fileCR assistant, medium parser, return youtube comment username, 7TV, youtube auto hd + fps

damn, thats a lot
![1717768126931](https://github.com/uBlockOrigin/uAssets/assets/46074361/4871fd47-2e26-4882-b642-73dc934878a8)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/46074361/9008baf1-80d1-4f96-8d7d-b208253562ab)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 142026
 cosmetic: 51627
 scriptlet: 21047
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7480-0, 2m
 default:
  user-filters: 105-3, never
  easylist: 86618-478, 1h.55m Δ
  easyprivacy: 51022-647, 1h.55m Δ
  plowe-0: 3555-1, 2m
  ublock-badware: 9216-0, 1h.55m Δ
  ublock-filters: 38362-385, 1h.55m Δ
  ublock-privacy: 928-0, 1h.55m Δ
  ublock-quick-fixes: 78-0, 1h.55m Δ
  ublock-unbreak: 2336-2, 1h.55m Δ
  urlhaus-1: 16675-0, 2m
filterset (user): [array of 105 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 379 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 763
 network:
  1rx.io: 2
  2mdn.net: 6
  360yield.com: 1
  3lift.com: 2
  ad-delivery.net: 2
  ad.gt: 16
  ad4m.at: 2
  adentifi.com: 1
  adform.net: 2
  admanmedia.com: 3
  adnxs.com: 11
  adotmob.com: 1
  adscale.de: 2
  adsrvr.org: 22
  advertising.com: 3
  agkn.com: 1
  amazon-adsystem.com: 88
  appier.net: 1
  audrte.com: 1
  bfmio.com: 2
  bidr.io: 2
  bidswitch.net: 11
  brand-display.com: 1
  btloader.com: 5
  bttrack.com: 1
  casalemedia.com: 9
  ccgateway.net: 4
  clarium.io: 1
  company-target.com: 1
  confiant-integrations.net: 3
  contextweb.com: 2
  creativecdn.com: 1
  criteo.com: 13
  criteo.net: 1
  deepintent.com: 1
  demdex.net: 2
  dotomi.com: 1
  doubleclick.net: 36
  doubleverify.com: 26
  emxdgt.com: 2
  eqads.com: 1
  everesttech.net: 3
  fastclick.net: 1
  google-analytics.com: 7
  google.com: 2
  googleadservices.com: 7
  googlesyndication.com: 90
  googletagmanager.com: 2
  googletagservices.com: 3
  gstatic.com: 6
  gumgum.com: 3
  hadronid.net: 1
  id5-sync.com: 1
  imasdk.googleapis.com: 2
  indexww.com: 5
  iqm.com: 1
  liadm.com: 1
  lkqd.net: 1
  media.net: 2
  moatads.com: 21
  openx.net: 9
  presage.io: 1
  pub.network: 26
  pubmatic.com: 4
  quantcount.com: 1
  quantserve.com: 4
  rfihub.com: 1
  richaudience.com: 2
  rlcdn.com: 1
  rtactivate.com: 4
  rubiconproject.com: 24
  scorecardresearch.com: 2
  sharethrough.com: 55
  sitescout.com: 1
  smaato.net: 4
  smadex.com: 1
  smartadserver.com: 7
  smartclip.net: 2
  sonobi.com: 4
  springserve.com: 72
  stackadapt.com: 1
  stat-rock.com: 44
  storygize.net: 1
  t13.io: 9
  tapad.com: 1
  teads.tv: 2
  videoplayerhub.com: 1
  w55c.net: 3
  yahoo.com: 10
  yellowblue.io: 1
  yieldmo.com: 11
  youtube.com: 1
  zemanta.com: 1
 extended:
  ###google_ads_iframe_\/15184186\,11560343\/mariowiki_adhesion_0_…
  ##[data-freestar-ad][id]
  ##[name^="google_ads_iframe"]
  ##.adWrapper
  ###adBox
  ###AdHeader
  ###AD_Top
  ###homead
  ###ad-lead
  ##.orp-vpaid-container
  ##+js(xml-prune, VAST, , adnxs)
  ##+js(xml-prune, VAST, , barstoolsports.com)
  ##+js(set-constant, rwt, noopFunc)
  ##ins.adsbygoogle[data-ad-slot]
  ##.adsbygoogle-noablate
  ##.ad-choices
  ##.GoogleActiveViewElement:not(:has(> #reward_close_button_widge…
  ##.GoogleActiveViewElement > div:not(#reward_close_button_widget…
  ###abgb
  ##a[href^="https://ad.doubleclick.net/"]
  ###ad_unit
  ##.advertiser
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, disable all other extensions, test again
