### ISSUE TITLE
game8.co: ads

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#24007]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://game8.co/games/Honkai-Star-Rail`

### Category

ads

### Description

Ad for the TRIBE NINE game sticked to bottom

### Other extensions used

- Augmented Steam
- ClearURLs
- F.B Purity - Cleans up Facebook
- Grammar and Spell Checker - LanguageTool
- Tab Auto Refresh
- Tampermonkey
- Youtube audio_only
- ySense Addon

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/22180480/0c4ca975-0f96-4f93-abd8-ba2f54fe0d7e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 141413
 cosmetic: 56127
 scriptlet: 23523
 html: 2107
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5860-35, 4m
 default:
  user-filters: 64-0, never
  ublock-filters: 38416-112, 2m
  ublock-badware: 9218-0, 3m
  ublock-privacy: 920-2, 3m
  ublock-unbreak: 2393-2, 3m
  ublock-quick-fixes: 78-2, 3m
  easylist: 86627-176, 3m
  easyprivacy: 51022-64, 3m
  urlhaus-1: 16675-0, 4m
  plowe-0: 3555-989, 4m
  POL-0: 8694-45, 4m
  POL-2: 1283-50, 4m
filterset (user): [array of 65 redacted]
trustedset:
 added: [array of 31 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1295 ms
 maxAssetCacheWait: 592 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  game8.co: 3
  datadoghq-browser-agent.com: 1
  google.com: 6
  googletagmanager.com: 1
  pubnation.com: 2
  youtube-nocookie.com: 3
 extended:
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
```
</details>

**Comment by peace2000** [comment]
`game8.co##[data-track-nier-keyword="footer_overlay_ads"]`

Will fix it.

**Comment by przemo20** [comment]
Unfortunately, there's still leftover `footer-overlay` div block that prevents from clicking anything that is in the lower part of the page.

![Zrzut ekranu 2024-10-15 124914](https://github.com/user-attachments/assets/ea67e7ff-78d9-4d96-9a6a-84505e920658)

_Not sure if I should create a new issue about this, or just adding a comment here is enough._

**Comment by stephenhawk8054** [comment]
Test

```adb
game8.co##.footer-overlay
```

**Comment by przemo20** [comment]
> Test
> 
> ```
> game8.co##.footer-overlay
> ```

Yeah, that's what I have added myself already, and it's working. Just wanted for it to also get added to the official/global filters.
