### ISSUE TITLE
raidrush.net: detection

### ISSUE THREAD

**Issue by Pureblood4936** [uBlockOrigin/uAssets#24006]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://raidrush.net/pages/online-fernsehen/`

### Category

detection

### Description

if you try to watch any stream on the website, you'll see the adblock message

### Other extensions used

- TwitchNoSub
- m3u8 Sniffer TV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bildschirmfoto_7-6-2024_202937_raidrush net](https://github.com/uBlockOrigin/uAssets/assets/122942559/da2547ef-d03d-412a-b192-a51b34943453)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 142014
 cosmetic: 51536
 scriptlet: 21035
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38341-385, 1h.40m Δ
  ublock-badware: 9216-0, 1h.40m Δ
  ublock-privacy: 927-0, 1h.40m Δ
  ublock-unbreak: 2336-2, 1h.40m Δ
  ublock-quick-fixes: 78-0, 1h.40m Δ
  easylist: 86627-478, 1h.40m Δ
  easyprivacy: 51022-647, 1h.40m Δ
  urlhaus-1: 16675-0, now
  plowe-0: 3555-0, now
  DEU-0: 7480-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8445 ms
 maxAssetCacheWait: 2914 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  raidrush.net: 1
  doubleclick.net: 1
  fastcounter.de: 2
  googlesyndication.com: 1
  stpd.cloud: 1
  youspacko.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ###top_ga
  ##.funbox
  ###adver
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 Adguard ping (Anti adblock appear after 70 seconds).

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d2e97205d1b8ab0adcbbd07193e369c1cf977dc8 should be fine now on Chrome and Firefox.

**Comment by ghost** [comment]
Detection on `https://raidrush.net/pages/online-fernsehen/`

https://github.com/user-attachments/assets/277fbb1e-5ebd-47f3-b25f-2bce297b438d

Using Edge for Android.
