### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by GamingMix0** [uBlockOrigin/uAssets#24019]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

Die Werbung wird nicht blockiert

### Other extensions used

Die Werbung wird nicht blockiert

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 142063
 cosmetic: 51539
 scriptlet: 21039
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38346-289, 55m Δ
  ublock-badware: 9216-0, 55m Δ
  ublock-privacy: 929-0, 55m Δ
  ublock-unbreak: 2336-0, 55m Δ
  ublock-quick-fixes: 78-0, 55m Δ
  easylist: 86628-574, 55m Δ
  easyprivacy: 51023-647, 55m Δ
  urlhaus-1: 16720-0, now
  plowe-0: 3555-0, now
  DEU-0: 7482-3, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 129 ms (selfie)
 maxAssetCacheWait: 46 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 40
 network:
  amazon-adsystem.com: 1
  d2v02itv0y9u9t.cloudfront.net: 1
  mrmserve.com: 1
  scorecardresearch.com: 35
  sentry.io: 1
  ttvnw.net: 1
 extended:
  ##.stream-display-ad__wrapper
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5184
