### ISSUE TITLE
tomshw.it: nuisance

### ISSUE THREAD

**Issue by suppsuppa** [uBlockOrigin/uAssets#24016]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tomshw.it/automotive/incentivi-auto-2024-stanziati-300-milioni-esclusi-i-veicoli-elettrici-2024-06-08`

### Category

nuisance

### Description

There are still  empty adv boxes on every "news" page and one in particular at the bottom is like a banner in overlay on top of the other contents

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/161498254/10149261-7ae9-4d1f-be64-0fcb9e1b15a7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 141183
 cosmetic: 53152
 scriptlet: 21037
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ITA-0: 8434-19, now
  easylist: 86628-572, 5m Δ
  easyprivacy: 51022-638, 5m Δ
  plowe-0: 3555-0, now
  ublock-badware: 9216-0, 5m Δ
  ublock-filters: 38344-283, 5m Δ
  ublock-privacy: 929-0, 5m Δ
  ublock-quick-fixes: 78-0, 5m Δ
  ublock-unbreak: 2336-0, 5m Δ
  urlhaus-1: 16495-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 214 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  adasta.it: 1
  brid.tv: 4
  clarity.ms: 1
  disqus.com: 3
  doubleclick.net: 2
  facebook.com: 1
  facebook.net: 1
  google.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  iubenda.com: 1
  scorecardresearch.com: 2
  youtube.com: 8
 extended:
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by mapx-** [comment]
add

```
tomshw.it###sticky_ads
tomshw.it##.customads
```

@Khrin

**Comment by suppsuppa** [comment]
thx
