### ISSUE TITLE
icard.com: nuisance

### ISSUE THREAD

**Issue by ib0ndar** [uBlockOrigin/uAssets#24012]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://icard.com/en/personal-pricing`

### Category

nuisance

### Description

<img width="1958" alt="SCR-20240608-jfgq" src="https://github.com/uBlockOrigin/uAssets/assets/58164047/1aa2405f-e4df-43ac-8035-ebdcd60b1e15">

### Other extensions used

<img width="1276" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/58164047/f043ad93-16ca-41de-a6c7-7f7b2da138d1">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 228375
 cosmetic: 226167
 scriptlet: 54457
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79416-79416, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99526-99525, 1m
  adguard-generic: 81043-7445, now
  adguard-mobile: 9436-153, now
  adguard-spyware-url: 1531-119, now
  adguard-spyware: 70372-29028, now
  curben-phishing: 509-0, now
  adguard-cookies: 30011-1679, now
  ublock-cookies-adguard: 1190-1190, 28m
  fanboy-cookiemonster: 51121-19872, 28m
  ublock-cookies-easylist: 1190-0, now
  adguard-social: 23188-1511, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 45-0, never
  ublock-filters: 38344-308, now
  ublock-badware: 9216-0, now
  ublock-privacy: 929-1, now
  ublock-unbreak: 2336-4, now
  ublock-quick-fixes: 78-2, now
  easylist: 86628-14718, now
  easyprivacy: 51022-920, now
  urlhaus-1: 16495-0, now
  plowe-0: 3555-0, now
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 230 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 150 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  zdassets.com: 1
```
</details>

**Comment by mapx-** [comment]
enable `EasyList/uBO – Cookie Notices`
