### ISSUE TITLE
[nsfw] pirr7gy0r9js.xyz: [unknown]

### ISSUE THREAD

**Issue by hongyouli1111** [uBlockOrigin/uAssets#24014]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pirr7gy0r9js.xyz:8443/index.html`

### Category

[unknown]

### Description

> 色情网站

**Porn sites**

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium Mobile: 125
filterset (summary):
 network: 157206
 cosmetic: 102584
 scriptlet: 21328
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-social: 23188-767, now
  fanboy-social: 16230-18, now
  fanboy-thirdparty_social: 68-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38775-357, 1h.31m Δ
  ublock-badware: 9210-0, 1h.31m Δ
  ublock-privacy: 930-0, 1h.31m Δ
  ublock-unbreak: 2339-0, 1h.31m Δ
  ublock-quick-fixes: 78-0, 1h.31m Δ
  adguard-mobile: 9433-97, now
  easylist: 86628-654, 1h.31m Δ
  easyprivacy: 51022-726, 1h.31m Δ
  urlhaus-1: 16495-0, now
  plowe-0: 3627-0, never
  CHN-0: 26032-164, never
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 17974 ms (selfie)
 maxAssetCacheWait: 2300 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  cnzz.com: 1
```
</details>

**Comment by mapx-** [comment]
I guess it's about blocking ads, @cjx82630 could you take a look ?

**Comment by cjx82630** [comment]
@hongyouli1111 Please describe the problem in detail.If popup Ads,return to the original page and report.
