### ISSUE TITLE
comfig.app: ads

### ISSUE THREAD

**Issue by RoonMoonlight** [uBlockOrigin/uAssets#24025]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://comfig.app/`

### Category

ads

### Description

The sponsored ads displays that is generated by random text (similar to some sites such as NamuWiki). This applies to all sub pages of comfig.app.

### Other extensions used

SponsorBlock for YouTube, Improved YouTube, YouTube Live Stream Latency Mitigator, Auto Tab Discard, Simple Translate, LiveTL, HyperChat, Remove Twitch Recommended Channels Live Chat, LibRedirect, Violentmonkey, Return YouTube Dislike, Better TTV, Brave Search

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-09 112553](https://github.com/uBlockOrigin/uAssets/assets/25527589/3c9bcbe0-735d-4ac9-9d67-e9e7e2bfdc43)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137442
 cosmetic: 46357
 scriptlet: 19597
 html: 1833
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38437-112, 6m
  ublock-badware: 9218-0, 6m
  ublock-privacy: 920-2, 6m
  ublock-unbreak: 2393-2, 6m
  ublock-quick-fixes: 78-2, 6m
  easylist: 86665-176, 6m
  easyprivacy: 51022-64, 6m
  urlhaus-1: 14440-0, 6m
  plowe-0: 3555-989, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2522 ms
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 2
  sentry.io: 4
```
</details>

**Comment by mapx-** [comment]
we had a similar issue https://github.com/uBlockOrigin/uAssets/issues/19578
breaking pages etc

use these filters as custom ones:
```
comfig.app##.card-body:has-text(TF2)
comfig.app##.card-body:has-text(TF2) + [class]
```

**Comment by D4niloMR** [comment]
Maybe at least something like `comfig.app##a[href="https://comfig.app/?aff=comfig"]:remove()` ? Seems to be safe.
