### ISSUE TITLE
mail.com: nuisance 

### ISSUE THREAD

**Issue by Penticton** [uBlockOrigin/uAssets#24029]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mail.com/`

### Category

nuisance

### Description

This popular free mail provider's site has a lot wrong with it, there are sometimes popup video windows that show up in the most in opportune places throughout the site and they can't or seemingly can't be blocked, I've tried everything.

There are also areas or sections of content which are very "advert" looking and lead to places they probably make click-through funds from, like fake news headings on occasion and topics that just aren't anything at all to do with email.

Checking one's email, signing up for a free or even a paid email address for that matter and these particular headings along with their shortened paragraphs below the heading end up getting displayed all wrong and most times one of them is displayed right over top of their login text entry box and the password text entry box beside it, I've tried umpteen ways to disable certain annoyances like the ones stated here, with little or no luck, generally If I do get something blocked, it takes some other part of the page with it or simply does nothing to the original thing you tried to block out as it has some sort of seemingly unblockable overlay over some of the pages it displays.

There are literally tons of overlays all over these pages, when all most people want to do is enter their username and password and hit the LOGIN button and voila, the email page loads, eventually once you get through all the crap above, you do get to login successfully, but wait, in between the login button and the email page with your new mail, your folders such as Inbox, Spam, Outbox, Drafts etc, more often than not there's another page between those two page asking you AGAIN in another way if you'd like to sign up to a paid account, I've been sitting beside friends and others who try to login to their mail.com account via the webmail at https://www.mail.com/int/   (I take it that "int" is for International users because I often get taken through this page before it logs me into the webmail page where my mail is located.) anyways, the people I have seen try to login to their webmail often get this "middle", last chance type of page asking them to join, and the link to proceed is very tiny and hidden at the bottom of the page, almost always out of view of the user trying to login, now anyone who isn't knowledgeable in such things and aware of all the tricks like you or myself, would totally miss this link and think they've hit a wall, are completely stuck until they can either get another third party email program setup on their device or wait until they get home to their computer to do whatever it is they're attempting to login to do at that moment, when they go back to using a third party email program like Thunderbird or Outlook etc. (Which do their job just fine when checking and sending mails, third party email apps and programs even get the folders right too, this part of the service is A+++, )

### Other extensions used

Just Ublock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 192954
 cosmetic: 113921
 scriptlet: 27399
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-13732, now
  ALB-0: 305-6, now
  CHN-0: 26187-1208, now
  FRA-0: 24646-3266, now
  KOR-1: 4980-101, now
  POL-0: 8690-132, now
  POL-2: 1280-19, now
  RUS-0: 39558-1115, now
  fanboy-cookiemonster: 51128-19100, now
 default:
  user-filters: 76-7, never
  easylist: 86723-14644, now
  easyprivacy: 51031-14, now
  plowe-0: 3555-652, now
  ublock-badware: 9226-0, now
  ublock-filters: 38383-621, now
  ublock-privacy: 929-6, now
  ublock-quick-fixes: 82-0, now
  ublock-unbreak: 2337-20, now
  urlhaus-1: 14210-0, now
filterset (user): [array of 76 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
 tooltipsDisabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 738 ms (selfie)
 maxAssetCacheWait: 308 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 58
 network:
  mail.com: 2
  360yield.com: 8
  3lift.com: 1
  adform.net: 1
  adnxs.com: 2
  amazon-adsystem.com: 1
  casalemedia.com: 1
  criteo.com: 2
  criteo.net: 5
  doubleclick.net: 1
  googletagmanager.com: 2
  id5-sync.com: 2
  lijit.com: 1
  openx.net: 1
  pbstck.com: 1
  primis.tech: 1
  pubmatic.com: 2
  rubiconproject.com: 8
  smartadserver.com: 8
  taboola.com: 2
  uicdn.com: 2
  uimserv.net: 1
  united-infos.net: 1
  yieldlab.net: 2
 extended:
  ##.ad-container
  ##.blocks-3
  ##li.subnav-item:nth-of-type(9)
  ##li.has-subnav.nav-item:nth-of-type(3)
  ##.open.has-subnav.nav-item
  ##+js(no-setTimeout-if, offsetHeight)
  ##+js(set-constant, AdService.info.abd, noopFunc)
```
</details>

**Comment by mapx-** [comment]
You have a lot od lists enabled and also custom filters.
Save your configuration (backup it), reset uBO to defaults and test again.

If you still get issues report them 1 by 1 with all the steps and links required
