### ISSUE TITLE
pixeldrain: breakage

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#24039]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://pixeldrain.com/
```

### Description

I'm not sure if these were removed on purpose, but the share buttons on pixeldrain are gone with ubo enabled. Even buttons like the open link and qr code buttons are gone too. This also breaks the share button when you visit an uploaded file, preventing the sidebar from appearing (see screenshots). I don't believe these buttons are a nusance or intrusive, especially the sidebar which doesn't appear until you click the share button.

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBO on (share button):
![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/ce27aad0-139c-46ce-8829-8a8dfc04ea57)

uBO off (share button):
![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/4a3ca7bf-f0a6-49c1-91f6-ec95c1ea1c2f)

uBO on (button row):
![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/80936957-3e88-403d-bf91-14393c14d7b9)

uBO off (button row):
![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/b3b1ade1-6496-40f6-835c-5563457662a8)

</details>

### Configuration

<details>
<summary>Details</summary>

Front page:
```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 219477
 cosmetic: 252896
 scriptlet: 51451
 html: 2099
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81016-3992, 3d.7h.6m
  adguard-mobile: 9435-58, 3d.7h.6m
  adguard-spyware-url: 1531-120, 3d.7h.6m
  adguard-spyware: 70366-1513, 3d.7h.6m
  block-lan: 68-0, 3d.7h.6m
  curben-phishing: 478-0, 5h.1m
  adguard-social: 23177-55, 3d.7h.6m
  adguard-cookies: 30000-46, 3d.7h.6m
  ublock-cookies-adguard: 1179-15, 3d.7h.6m
  adguard-popup-overlays: 27147-1002, 3d.7h.6m
  adguard-mobile-app-banners: 5277-24, 3d.7h.6m
  adguard-other-annoyances: 14427-412, 3d.7h.6m
  [11 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 38469-112, 5h.1m Δ
  ublock-badware: 9228-0, 5h.1m Δ
  ublock-privacy: 920-2, 5h.1m Δ
  ublock-unbreak: 2394-2, 5h.1m Δ
  ublock-quick-fixes: 145-8, 5h.1m Δ
  easylist: 86725-2249, 5h.1m Δ
  easyprivacy: 51032-28479, 5h.1m Δ
  urlhaus-1: 14315-0, 4h.1m
  plowe-0: 3627-1555, 3d.7h.6m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 728 ms (selfie)
 maxAssetCacheWait: 430 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  pixeldrain.com: 2
 extended:
  ##.social_buttons

```

Upload page ([dummy file link](https://pixeldrain.com/u/ARM5vyoH)):
```yaml
...
 extended:
  ##.sharebar
  ##.banner

```
</details>

**Comment by mapx-** [comment]
add & test

`pixeldrain.com#@#.social_buttons`

**Comment by the9655a** [comment]
Yep, that fixes the home page.

**Comment by mapx-** [comment]
@Yuki2718 could you fix in EasyList – Social Widgets and AdGuard – Social Widgets ?
(social_buttons only for AG)
