### ISSUE TITLE
oracle.com: nuisance / privacy

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#24034]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.oracle.com/scm/logistics/`

### Category

nuisance

### Description

Un-closable "Talk to sales" button at bottom right side.

Also, some analytics scripts are not blocked:
```
https://www.oracle.com/asset/web/analytics/ora_ocom.js
https://www.oracle.com/asset/web/analytics/ora_code_yt.js
https://www.oracle.com/us/assets/metrics/ora_code.js
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138995
 cosmetic: 106874
 scriptlet: 30310
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  block-lan: 68-0, now
  curben-phishing: 478-0, now
  fanboy-cookiemonster: 51131-226, now
  ublock-cookies-easylist: 1191-1, now
  easylist-annoyances: 4660-31, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7532-11, now
  easylist-notifications: 3026-156, now
  ublock-annoyances: 5915-47, 9m Δ
 default:
  user-filters: 1-0, never
  ublock-filters: 38390-319, 9m Δ
  ublock-badware: 9226-0, 9m Δ
  ublock-privacy: 929-0, 9m Δ
  ublock-unbreak: 2337-0, 9m Δ
  ublock-quick-fixes: 141-0, 9m Δ
  easylist: 86725-215, 9m Δ
  easyprivacy: 51032-24, 9m Δ
  urlhaus-1: 14315-0, now
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1301 ms (selfie)
 maxAssetCacheWait: 433 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  oracle.com: 3
  demdex.net: 1
  googletagmanager.com: 1
  licdn.com: 1
  omtrdc.net: 2
  oracleinfinity.io: 1
  trustarc.com: 2
 extended:
  ###teconsent
```
</details>

**Comment by mapx-** [comment]
I guess you should use a custom filter for the chat gadget:

`oracle.com##ocom-chatbot`

for the analytics scripts @ryanbr

**Comment by ryanbr** [comment]
Have to be careful to block these scripts, May break other things hosted on oracle
