### ISSUE TITLE
gofile.io: breakage

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#24036]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://gofile.io/welcome
```

### Description

Theres a missing icon on the home page that seems to be caused by ubo.

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

ubo on: 
![wqUt5jJ](https://github.com/uBlockOrigin/uAssets/assets/149513282/781e5290-6cf0-41f6-ba42-40ed757407c3)

ubo off: 
![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/1328b0d1-cf03-471c-97d0-a24d9e131619)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 219477
 cosmetic: 252896
 scriptlet: 51451
 html: 2099
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81016-3992, 3d.3h.16m
  adguard-mobile: 9435-58, 3d.3h.16m
  adguard-spyware-url: 1531-120, 3d.3h.16m
  adguard-spyware: 70366-1513, 3d.3h.16m
  block-lan: 68-0, 3d.3h.16m
  curben-phishing: 478-0, 1h.11m
  adguard-social: 23177-55, 3d.3h.17m
  adguard-cookies: 30000-46, 3d.3h.17m
  ublock-cookies-adguard: 1179-15, 3d.3h.17m
  adguard-popup-overlays: 27147-1002, 3d.3h.17m
  adguard-mobile-app-banners: 5277-24, 3d.3h.17m
  adguard-other-annoyances: 14427-412, 3d.3h.17m
  [11 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 38469-112, 1h.11m Δ
  ublock-badware: 9228-0, 1h.11m Δ
  ublock-privacy: 920-2, 1h.11m Δ
  ublock-unbreak: 2394-2, 1h.11m Δ
  ublock-quick-fixes: 145-8, 1h.11m Δ
  easylist: 86725-2249, 1h.11m Δ
  easyprivacy: 51032-28479, 1h.11m Δ
  urlhaus-1: 14315-0, 11m
  plowe-0: 3627-1555, 3d.3h.17m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 728 ms (selfie)
 maxAssetCacheWait: 430 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  gofile.io: 1
 extended:
  ##.bi-share
  ###adsATF

```
</details>

**Comment by mapx-** [comment]
add

`gofile.io#@#.bi-share`

@ryanbr
