### ISSUE TITLE
japscan.lol: detection

### ISSUE THREAD

**Issue by Sentenza888** [uBlockOrigin/uAssets#24032]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.japscan.lol/lecture-en-ligne/ubel-blatt/volume-1/`
`https://www.japscan.lol/`

### Category

detection

### Description

japscan.lol is a French online manga reading website.
Sometimes the website detects ublock and displays advertisements, and detection banners/pop-ups that block access to content.

### Other extensions used

On PC: lastpass
On mobile: none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d'écran 2024-06-09 205505](https://github.com/uBlockOrigin/uAssets/assets/171957447/6de8c9f2-78e5-468c-bd97-1dffa7824d2f)
![Capture d'écran 2024-06-09 205711](https://github.com/uBlockOrigin/uAssets/assets/171957447/6bf1f303-ec76-42f5-8a60-e39ecdfce5a3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 154697
 cosmetic: 52976
 scriptlet: 19753
 html: 1833
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38437-112, 1m
  ublock-badware: 9228-0, 1m
  ublock-privacy: 920-2, 1m
  ublock-unbreak: 2394-2, 1m
  ublock-quick-fixes: 90-0, 3m Δ
  easylist: 86725-176, 1m
  easyprivacy: 51032-65, 1m
  urlhaus-1: 14210-0, 3m
  plowe-0: 3555-989, 1m
  FRA-0: 24646-397, 1m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1013 ms
 maxAssetCacheWait: 466 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  japscan.lol: 10
  googletagmanager.com: 1
  statorkumyk.com: 1
 extended:
  ###adheader:not([style^="position: absolute; left: -5000px"])
  ##.adheader
  ##.tangoai
  ###blur-inter
  ###interstitial
  ##a[target="_blank"].donate
  ##div.container > [href]
  ##.nav-item:has( > .text-truncate.nav-link.font-weight-bold[href…
  ##+js(no-setTimeout-if, detectImgLoad)
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
  ##+js(remove-node-text, script, "/'push','shift'|banner-|ApoZow/…
  ##+js(no-setTimeout-if, sessionStorage)
  ##+js(no-window-open-if)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/23806
