### ISSUE TITLE
sbs.com.au: detection

### ISSUE THREAD

**Issue by ashrama** [uBlockOrigin/uAssets#24045]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sbs.com.au/ondemand/watch/2338197059540`

### Category

detection

### Description

Message displayed on screen when trying to play video:

"Video playback error
Sorry, we've encountered an error playing this video. If you have an ad blocker turned on, try turning it off or whitelisting our website before trying again. This may prevent you from loading videos."

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![sbs ad block detection 20240611](https://github.com/uBlockOrigin/uAssets/assets/13570210/02bebe75-e0cc-4893-a441-0d90638f1721)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137083
 cosmetic: 46377
 scriptlet: 19682
 html: 1837
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38478-112, 1h.6m Δ
  ublock-badware: 9227-0, 1h.6m Δ
  ublock-privacy: 920-2, 1h.6m Δ
  ublock-unbreak: 2395-2, 1h.6m Δ
  ublock-quick-fixes: 145-8, 1h.6m Δ
  easylist: 86737-173, 1h.6m Δ
  easyprivacy: 51032-65, 1h.6m Δ
  urlhaus-1: 13995-0, 4m
  plowe-0: 3555-989, 4m
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 742 ms (selfie)
 maxAssetCacheWait: 122 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  adnxs.com: 2
  adobedtm.com: 1
  conviva.com: 4
  demdex.net: 1
  doubleclick.net: 8
  everesttech.net: 1
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  tremorhub.com: 1
 extended:
  ##+js(set-constant, adBlockerDetected, undefined)
  ##+js(m3u-prune, /redirector\.googlevideo\.com\/videoplayback\?[…
  ##+js(no-xhr-if, /redirector\.googlevideo\.com\/videoplayback[\s…
  ##+js(json-prune, ads breaks cuepoints times)
  ##+js(remove-class, ad-controls, .bitmovinplayer-container.ad-co…
  ##+js(set-constant, odabd, false)
```
</details>

**Comment by D4niloMR** [comment]
I can reproduce. @ashrama test:

```adb
sbs.com.au##+js(aopr, odabd)
sbs.com.au#@#+js(set, odabd, false)
```

**Comment by ashrama** [comment]
> I can reproduce. @ashrama test:
>
> sbs.com.au##+js(aopr, odabd)
> sbs.com.au#@#+js(set, odabd, false)

This prevents the adblock error being displayed but the video does not play, sits with loading circle indicator.

**Comment by D4niloMR** [comment]
You can see https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax for network and cosmetic filtering.

For scriptlets (`##+js()`): https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library. Maybe https://github.com/uBlockOrigin/uBlock-issues/wiki/Introduction-to-basic-filtering-syntax#investigating-anti-adblock-scripts too.
