### ISSUE TITLE
marktplaats.nl: breakage

### ISSUE THREAD

**Issue by joost00719** [uBlockOrigin/uAssets#24047]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.marktplaats.nl/v/sport-en-fitness/fitnessmaterialen/m2105016123-gorillasport-verstelbaarbankje-30kilo-dumbbels-en-halter`

### Category

nuisance

### Description

The place where the address and other info about the seller should be shown, is not visible with the adblocker enabled.

### Other extensions used

https://github.com/uBlockOrigin/uAssets/assets/21021559/9bc86102-b85a-4078-9d4d-11c4cb29c570

Note that there's an extension "Marktplaats zonder spam" which removes some elements.
I have verified that that extension is not the cause of the issue by disabling it and keeping ubo enabled

### Screenshot(s)

<details>
Note that on the first screenshot, there's missing info on the right hand side. It also looks odd with the spacing.
On the second screenshot, you'll see that the seller's info is visible. This is with ubo disabled.
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/21021559/064a70b7-8c2e-43e7-8299-75686c480058)
![image](https://github.com/uBlockOrigin/uAssets/assets/21021559/2e92c98d-ddf8-4126-9f8a-5b4e0f4acd5d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138764
 cosmetic: 48186
 scriptlet: 21116
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, never
  https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
 default:
  user-filters: 5-0, never
  NLD-0: 2294-38, now
  easylist: 86737-565, 1h Δ
  easyprivacy: 51044-640, 1h Δ
  plowe-0: 3555-0, now
  ublock-badware: 9225-0, 1h Δ
  ublock-filters: 38370-280, 1h Δ
  ublock-privacy: 929-0, 1h Δ
  ublock-quick-fixes: 147-0, 1h Δ
  ublock-unbreak: 2338-0, 1h Δ
  urlhaus-1: 13995-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 18 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 617 ms (selfie)
 maxAssetCacheWait: 325 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  marktplaats.nl: 1
  datadoghq-browser-agent.com: 1
  ebayclassifieds.net: 2
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  marktplaats.net: 1
 extended:
  ##.BannerBottom-root
  ##.BannerRight-root
  ##.right-banner-root-container
  ##.vip-banner-top-sticky-container
  ##.hz-Page-content:style(max-width: 1300px!important;)
```
</details>

**Comment by klokop** [comment]
Can confirm.

**Comment by stephenhawk8054** [comment]
```yml
  ##.hz-Page-content:style(max-width: 1300px!important;)
```

Check if you are using this filter in "My filters"

**Comment by RowinGrunder** [comment]
> ### Description
> The place where the address and other info about the seller should be shown, is not visible with the adblocker enabled.

Can confirm.

**Comment by klokop** [comment]
> ```
> ##.hz-Page-content:style(max-width: 1300px!important;)
> ```
> 
> Check if you are using this filter in "My filters"

![image](https://github.com/uBlockOrigin/uAssets/assets/856897/24104e33-6aff-4a83-b3b8-906ad5c9f7c0)

**Comment by stephenhawk8054** [comment]
@klokop Can you test in a new browser profile with only uBO and its default settings?

**Comment by klokop** [comment]
Seems to be working fine now.
