### ISSUE TITLE
forumactif.com: ads

### ISSUE THREAD

**Issue by GonzalezMo** [uBlockOrigin/uAssets#24046]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lucidaliahunters.forumactif.com/`

### Category

ads

### Description

There are ads under the banner and above the forum, those ads are present on every forums that are created with Forumactif.

Using the zapper doesn't really work, the ads seem to be on a carousel thingy, and the div doesn't have a class either...

We can't modify the php because it's against the ToS of Forumactif.

I can provide more forum to look at if you want.

Thanks for checking it out, keep up the good work for a ad-free internet !

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/49155595/9d3036d0-537b-4bd5-aadf-40d2c8dee5e1)
![image](https://github.com/uBlockOrigin/uAssets/assets/49155595/5cb05192-ce28-40ed-be08-6fd5f6b3ac15)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137095
 cosmetic: 46379
 scriptlet: 19683
 html: 1837
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 38479-112, 1h.5m Δ
  ublock-badware: 9227-0, 1h.5m Δ
  ublock-privacy: 920-2, 1h.5m Δ
  ublock-unbreak: 2395-2, 1h.5m Δ
  ublock-quick-fixes: 147-8, 1h.5m Δ
  easylist: 86737-550, 1h.5m Δ
  easyprivacy: 51044-677, 1h.5m Δ
  urlhaus-1: 13995-0, 22m
  plowe-0: 3555-0, 15m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 421 ms (selfie)
 maxAssetCacheWait: 89 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  criteo.net: 2
  googletagmanager.com: 1
 extended:
  ##div[id^="crt-"][style]
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 `AdGuard Français` issue

**Comment by stephenhawk8054** [comment]
I guess it's fixed now?

**Comment by GonzalezMo** [comment]
Thanks for your answers !

Sorry, I couldn't check them out earlier.
I don't really use gitHubg that often, and I have one question related to the fix, should I add it in a filter or it is up for anyone using ublock origins ?

**Comment by Yuki2718** [comment]
@GonzalezMo Just update AdGuard Français by clicking a clock icon next to its name in uBO's Filter Lists pane.

**Comment by GonzalezMo** [comment]
Thank you for your quick answer !

Works like a charm too, thank you so much for your work and keep it up !

**Comment by GonzalezMo** [comment]
Hello again !

After enabling the AdGuard Français, we noticed some design element of our forum going missing.

For exemple, after the banner, we have a staff introduction with tabs
![image](https://github.com/uBlockOrigin/uAssets/assets/49155595/0cb50030-9f4e-48b6-ae18-73967cba8ed5)

And at the bottom of the page, we have tabs to present the groups.
![image](https://github.com/uBlockOrigin/uAssets/assets/49155595/a02d82a3-6fa2-4cbc-bf1d-d9e70ffa4ba6)

I discussed this issue with our theme developpers, but we can't find a workaround because we don't have access to the htacess and such.

We didn't find any other issue for now, I don't know if you can find a workaround it.

Thank you in advance !
