### ISSUE TITLE
rgshows.vercel.app: nuisance, ad

### ISSUE THREAD

**Issue by god-damnit** [uBlockOrigin/uAssets#24040]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rgshows.vercel.app/`

### Category

nuisance

### Description

Shows an annoying popup of an Event (potential discord scam) every time you load the site. also there is an advertisement button at the bottom right.

### Other extensions used

none

### Screenshot(s)

<details>
Popup at center and Ad Button at the bottom right
<summary>Screenshot(s)</summary>

![firefox_McAM8MQ8WI](https://github.com/uBlockOrigin/uAssets/assets/68650297/e5ec8f49-0c4c-4a8f-b6c7-d2b9b1cec1a5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 204789
 cosmetic: 215852
 scriptlet: 34113
 html: 2101
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 438-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 760-8, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2648-75, 46m
  https://raw.githubusercontent.com/WindowsAurora/FMHYFilterlist/main/filterlist.txt: 334-1, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 77593-12, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2108-12, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1177-3, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 102-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/privacy_essentials.txt: 1234-216, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/youtube_clear_view.txt: 33-0, now
  adguard-cookies: 30021-61, now
  ublock-cookies-adguard: 1191-15, now
  [15 lists not shown]: [too many]
 default:
  user-filters: 7-0, never
  ublock-filters: 38473-281, now
  ublock-badware: 9227-436, now
  ublock-privacy: 920-80, now
  ublock-unbreak: 2395-10, now
  ublock-quick-fixes: 145-8, now
  easylist: 86735-22235, now
  easyprivacy: 51032-7322, now
  urlhaus-1: 14315-0, 46m
  plowe-0: 3555-2238, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 467 ms (selfie)
 maxAssetCacheWait: 261 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cloudflare.com: 2
  discord.com: 2
  freevisitorcounters.com: 4
```
</details>

**Comment by mapx-** [comment]
add

```
rgshows.vercel.app##.popup-overlay
rgshows.vercel.app##.icon-position
```

**Comment by ryanbr** [comment]
Need to know more info, "The read guide" popup sends me to  different page. If I remove the popup, I don't get this

Is this is what is intended?

**Comment by mapx-** [comment]
I guess we should use 
`rgshows.vercel.app###event-popup`

and not 
`rgshows.vercel.app##.popup-overlay`

**Comment by mapx-** [comment]
@god-damnit 

add

```
rgshows.vercel.app###event-popup
rgshows.vercel.app##.icon-position
```

**Comment by RISHAB-CREATOR** [comment]
Well i removed that ad widget, also kindly update the domain its now https:/rgshows.me now

**Comment by stephenhawk8054** [comment]
```adb
rgshows.me###event-popup
```

@ryanbr

**Comment by ave9858** [comment]
This site also has logger that uploads data thru a discord webhook and anti-devtools.

**Comment by D4niloMR** [comment]
```
||rgshows.me/js/devtoolsdetector.js
||rgshows.me/js/logger.js
||rgshows.me/js/statistics.js
```

**Comment by RISHAB-CREATOR** [comment]
bruh wtf
