### ISSUE TITLE
[Ads] quora.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2404]
### URL(s) where the issue occurs

`https://www.quora.com/Why-are-inline-functions-only-a-request-to-the-compiler-Why-does-the-compiler-make-the-decision-on-which-inline-functions-to-actually-inline-Why-wouldnt-the-compiler-just-do-what-the-programmer-asks-it-to-do`

### Describe the issue

Quora now has inline ads with random ID and class. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/40664908-35602a20-6319-11e8-9a9a-cbd899676402.png)
![image](https://user-images.githubusercontent.com/7283682/40664935-45aace3a-6319-11e8-908a-5fc980edc623.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.8

### Settings

All default.

**Comment by mapx-** [comment]
I cannot reproduce the ads.

**Comment by lassekongo83** [comment]
`quora.com##.PromptsList:has(a[href*="utm_campaign"])
quora.com##.pagedlist_item:has(a[href*="utm_campaign"])`

**Comment by okiehsch** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/90#issuecomment-394907715

**Comment by terrorist96** [comment]
`https://www.quora.com/What-is-the-memory-capacity-of-the-human-brain-in-terabytes`

![image](https://user-images.githubusercontent.com/12802056/41196706-7a23784c-6c15-11e8-9a00-01445463c086.png)

I'm surprised at how tenacious Quora is at bypassing adblockers...

**Comment by uBlock-user** [comment]
Add

```
quora.com##[rel="nofollow noopener"]
quora.com##div:has-text(/^ad by/)
```

**Comment by uBlock-user** [comment]
Changed again, add --

```
quora.com##[rel*="noopener"]
quora.com##[rel*="nofollow"]
quora.com##div:has-text(/^ad/)
```

**Comment by andersk** [comment]
`quora.com##[rel*="noopener"]` is way too broad—it hides all external links in legitimate answers.

**Comment by okiehsch** [comment]
Example link: `https://www.quora.com/How-difficult-is-it-to-learn-Python`

````
quora.com##[rel*="noopener"]
quora.com##[rel*="nofollow"]
````
are hiding the links, so I will remove them.

**Comment by ghajini** [comment]
need more long lasting solution all contributors
what you say @jspenguin2017

**Comment by jspenguin2017** [comment]
Eh, the only way to make it long lasting is keeping solutions private. If it's public they can always work around them.

**Comment by uBlock-user** [comment]
> i see ads

Because the last commit was reverted https://github.com/uBlockOrigin/uAssets/commit/5eff447a36774725cffc428ada8acd093f90fbe8

**Comment by uBlock-user** [comment]
`quora.com##[disable_auto_login*="True"]` works without seemingly breaking an links or anything else.

**Comment by terrorist96** [comment]
I see ads again.

**Comment by lassekongo83** [comment]
`quora.com##[id*=wrapper]:has-text(/ad\s{1,}by /i)` in uBlock Fitlers hides the entire page on mobile. Perhaps it should be added inside `!#if !env_mobile` instead.

`quora.com##.top_slot` and `quora.com##.lower_slot` seems to work on mobile. (And the last one on desktop too.)

Other possible filter that can be added for desktop: `quora.com##:xpath(//div[contains(text(), 'ad') and contains(text(), 'by')]/parent::div/parent::div/parent::div[@id])`

**Comment by krystian3w** [comment]
...`(/promoted\s{1,}by /i)` also add.

**Comment by terrorist96** [comment]
Confirm I see ads. @krystian3w's solution leaves the `Ad by xxx` text but blocks the ad content.

**Comment by krystian3w** [comment]
I blocked it manually two weeks ago, after the divs in the advertisement / promotion, unfortunately I do not have access to these rules to check if they are compatible with the mobile version.

**Comment by uBlock-user** [comment]
Adguard filters are still working, I don't see any ads with these.

```
quora.com##.UnifiedAnswerPagedList > .paged_list_wrapper > div[id]:if(a[href][target="_blank"][rel="noopener nofollow"]:not(.external_link)
quora.com##.grid_page > .layout_2col_main > div[id]:not(.AnswerListDiv):not(.answer_text_small):not(:last-child):if(a[href][target="_blank"][rel="noopener nofollow"])
```

**Comment by silverbacknet** [comment]
Gah, this completely broke my feed! Now every time I click to open an answer that has the last few lines shown, the entire answer instantly disappears! This is because, at least on my account (Quora is notorious for A/B testing), Quora adds the ad _directly onto the end of the post after expanding_, so this rule kills the whole post! It started happening this weekend, and seeing as the commit was 6 days ago, that perfectly explains it. Please revert this commit pending further testing.

**Comment by ZaphodBeebblebrox** [comment]
Update filters, it was removed earlier today.
