### ISSUE TITLE
worldstar.com: breakage

### ISSUE THREAD

**Issue by GreezyTootz** [uBlockOrigin/uAssets#24058]
### Prerequisites

- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.

### URL address of the web page

`https://worldstar.com/videos/wshhohW33jG4Fq1U3XhP/the-most-dangerous-group-of-people-in-america`

### Category

breakage

### Description

This is strange to explain but I will try my best. Whenever uBlock is on, and I go to the video's page for the first time, the video never gives me the option to play it. I can only see the thumbnail. But when I turn off uBlock via the extension icon, and then hit Refresh, the video allows me to play it. Strangely enough, if I go back to my extensions and now turn uBlock BACK on and hit Refresh, it allows me to play the video with uBlock running, but only for maybe 30 seconds or so before it freezes and starts loading. I have turned off all other extensions, removed and re-added uBlock. I have not changed any filters, nor am I running a VPN, or experiencing any issues on other browsers without uBlock. I tested this in Chrome as well as Firefox, both with the same results. I will attach screenshots of the steps I took to recreate this. I apologize there are so many but I feel it's the best way to depict this. Each screenshot has descriptions typed in them.

### Other extensions used

None, I currently have the extensions for the following installed:
3D Connexion
Adobe Acrobat PDF edit
Google Docs Offline
Picture-in-Picture

But, per the troubleshooting guide I have since turned them all off, and still got the same results. Maybe I can try to fully remove them as opposed to just turning them off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBlockSS1](https://github.com/uBlockOrigin/uAssets/assets/172435005/22a5d878-eaf1-495d-aaf6-1de97c41034d)
![uBlockSS2](https://github.com/uBlockOrigin/uAssets/assets/172435005/7226b340-eaa7-4b1f-96b7-133c10077975)
![uBlockSS3](https://github.com/uBlockOrigin/uAssets/assets/172435005/83c2b74e-4669-45b1-aa60-f61c5e68a1c4)
![uBlockSS4](https://github.com/uBlockOrigin/uAssets/assets/172435005/42237243-40e9-49fe-ac9d-1d8a62a8ddb1)
![uBlockSS5](https://github.com/uBlockOrigin/uAssets/assets/172435005/5a7e1c21-7ab1-4452-a2e6-867db8134aa3)
![uBlockSS6](https://github.com/uBlockOrigin/uAssets/assets/172435005/318fa1ff-a1fb-4c8e-a40a-b55dd4d3f173)
![uBlockSS7](https://github.com/uBlockOrigin/uAssets/assets/172435005/27cfbc1d-5dfa-499e-a8a8-dd0eb91ea90a)
![uBlockSS8](https://github.com/uBlockOrigin/uAssets/assets/172435005/e357a243-9d75-4592-b392-5cf44dc7a687)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 137046
 cosmetic: 46471
 scriptlet: 21109
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38379-280, now
  ublock-badware: 9210-0, now
  ublock-privacy: 929-0, now
  ublock-unbreak: 2337-0, now
  ublock-quick-fixes: 146-0, now
  easylist: 86725-564, now
  easyprivacy: 51046-639, now
  urlhaus-1: 13935-0, now
  plowe-0: 3555-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1154 ms
 maxAssetCacheWait: 533 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  assemblyexchange.com: 8
  googletagmanager.com: 4
  imasdk.googleapis.com: 2
  scorecardresearch.com: 2
  wknd.ai: 2
 extended:
  ##div[style^="width:972px;height:250px;"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||js.assemblyexchange.com/videojs-skip-ima3-unskippable.$script,stylesheet,domain=worldstar.com
@@||js.assemblyexchange.com/wana.$script,domain=worldstar.com
```

@ryanbr
