### ISSUE TITLE
channel4.com: breakage

### ISSUE THREAD

**Issue by dpetroff** [uBlockOrigin/uAssets#24054]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/59357-006`

### Category

breakage

### Description

The website works fine initially at first glance, i.e. when videos are started from the beginning. However, when resuming a video that was partially watched before, either by refreshing the browser tab or by navigating to the video from the "My4 -> Watching" page, pressing the "Play" button  starts the video from the correct position normally, but after [several](https://heroes.thelazy.net/index.php/Wandering_creature) seconds, the initial video details screen reappears, leaving the video playing in the background. Removing the overlay (and the transparent overlay below) with the element zapper reveals the video but the video player controls no longer exist. Even the built in browser video controls do not show when selecting the "Show all controls" context menu entry. If instead of zapping the start screen away you press the Play button, the video starts from the beginning and everything works normally (except for the fact that the video plays from the beginning instead of resuming from the point that it was meant to resume).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Start:

![image](https://github.com/uBlockOrigin/uAssets/assets/1384881/7fb7d7ec-f61a-4f90-a1dc-f4d9f6bee5a4)

After pressing play:

![image](https://github.com/uBlockOrigin/uAssets/assets/1384881/a1799ec5-49b0-4096-9932-1d575ef50a2a)

Several seconds later:

![image](https://github.com/uBlockOrigin/uAssets/assets/1384881/f844f11b-70f2-4aa6-a08a-331961d3fe86)

After pressing play again (notice the progress bar starts from the beginning):

![image](https://github.com/uBlockOrigin/uAssets/assets/1384881/df16f892-6e33-4bc7-9d79-e10823d48577)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 137066
 cosmetic: 46480
 scriptlet: 21099
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86737-562, 1h.5m Δ
  easyprivacy: 51044-639, 1h.5m Δ
  plowe-0: 3555-0, 29m
  ublock-badware: 9225-0, 1h.5m Δ
  ublock-filters: 38370-280, 1h.5m Δ
  ublock-privacy: 929-0, 1h.5m Δ
  ublock-quick-fixes: 147-0, 1h.5m Δ
  ublock-unbreak: 2338-0, 1h.5m Δ
  urlhaus-1: 13935-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1047 ms (selfie)
 maxAssetCacheWait: 317 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 170
 network:
  channel4.com: 5
  2cnt.net: 29
  braze.eu: 28
  c4assets.com: 1
  conviva.com: 52
  demdex.net: 1
  fwmrm.net: 3
  optimizely.com: 51
 extended:
  ##+js(no-xhr-if, /\/ad\/g\/1/)
```
</details>

**Comment by dpetroff** [comment]
I noticed a brief mention of a similar issue in [this comment from an older issue](https://github.com/uBlockOrigin/uAssets/issues/14352#issuecomment-1212475237) but notably here the problem is that "Pressing play again plays the video ___normally___" when what is expected is the video resumes from the correct time.

**Comment by stephenhawk8054** [comment]
I don't know how long I should wait to reproduce the issue but test this filter

```adb
channel4.com##+js(json-prune-xhr-response, adverts, , propsToMatch, /vod)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
