### ISSUE TITLE
nytimes.com: breakage

### ISSUE THREAD

**Issue by cmjdiff** [uBlockOrigin/uAssets#24061]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nytimes.com/interactive/2024/us/politics/biden-trump-2024-campaign.html`

### Category

breakage

### Description

With the "Cookie Widgets" lists enabled, the secondary navbar detaches from the top and moves down, while the top of the content moves up.  (This also blocks a nuisance that is _not_ a cookie widget, see #24059)

### Other extensions used

Other content-blocking/-modifying extensions disabled for test

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-11 221022](https://github.com/uBlockOrigin/uAssets/assets/69131295/2b517d29-4997-406c-8431-59afe42b2d28)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 148351
 cosmetic: 205033
 scriptlet: 33214
 html: 2099
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30041-88, never
  ublock-cookies-adguard: 1191-1, never
  fanboy-cookiemonster: 51148-3983, never
  ublock-cookies-easylist: 1191-1191, never
  adguard-social: 23257-49, 25m
  fanboy-social: 16245-736, 25m
  fanboy-thirdparty_social: 68-19, 25m
  adguard-popup-overlays: 27178-992, 25m
  adguard-mobile-app-banners: 5293-23, 25m
  adguard-other-annoyances: 14427-415, 25m
  adguard-widgets: 2541-11, 25m
  easylist-annoyances: 4660-293, 25m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38488-112, 25m
  ublock-badware: 9212-0, 25m
  ublock-privacy: 920-2, 25m
  ublock-unbreak: 2395-2, 25m
  ublock-quick-fixes: 147-8, 25m
  easylist: 86737-173, 25m
  easyprivacy: 51032-65, 25m
  urlhaus-1: 13935-0, 25m
  plowe-0: 3555-989, 25m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2807 ms
 maxAssetCacheWait: 18 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  nytimes.com: 3
  datadoghq-browser-agent.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  privacymanager.io: 1
 extended:
  ###bottom-wrapper
  ###top-wrapper
  ##.ad
  ##button[aria-label*="sharing"]
  ###fides-overlay
  ###standalone-footer
  ##body:style(overflow: initial !important)
  ###site-content:style(position: static !important;)
  ##body:style(overflow: auto !important;)
  ##+js(trusted-click-element, button.fides-reject-all-button, , 5…
  ##+js(set-constant, _adBlockCheck, true)
  ##+js(set-constant, webkitRequestFileSystem, noopFunc)
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, add your other lists, test again (disabling other extensions)

**Comment by cmjdiff** [comment]
I did exactly that on two separate machines before reporting here.  I'm reproducing this reliably, even on a new profile.

**Comment by cmjdiff** [comment]
Screen recording of reproducing from a clean profile: https://youtu.be/cLWMKCiVP_Q

**Comment by dportvine** [comment]
Add to **My filters** and check again  `nytimes.com#@##site-content:style(position: static !important;)`
