### ISSUE TITLE
nature.com: breakage

### ISSUE THREAD

**Issue by hooney91** [uBlockOrigin/uAssets#24064]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nature.com/articles/s41467-021-27037-6`

### Category

breakage

### Description

Can't click on items on the page.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 231365
 cosmetic: 126173
 scriptlet: 30126
 html: 2099
listset (total-discarded, last-updated):
 added:
  https://github.com/bpc-clone/bypass-paywalls-clean-filters/raw/main/bpc-paywall-filter.txt: 1084-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2648-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 77778-158, now
  adguard-spyware-url: 1536-233, now
  adguard-spyware: 69776-7063, now
  easylist-annoyances: 4663-69, now
  easylist-chat: 196-1, now
  fanboy-cookiemonster: 51148-202, now
  ublock-cookies-easylist: 1212-5, now
  easylist-newsletters: 7536-26, now
  easylist-notifications: 3023-175, now
  fanboy-social: 16255-17, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 38509-112, now
  ublock-badware: 9201-425, now
  ublock-privacy: 920-75, 1h.52m Δ
  ublock-unbreak: 2395-3, now
  ublock-quick-fixes: 151-8, 1h.52m Δ
  easylist: 86772-22101, now
  easyprivacy: 51046-31311, now
  urlhaus-1: 14245-0, now
  plowe-0: 3555-2259, now
  KOR-1: 4984-247, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 14 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 767 ms (selfie)
 maxAssetCacheWait: 170 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##.u-lazy-ad-wrapper
  ##.c-ad
  ##.leaderboard.advert
  ##.js-ad
  ##.optanon-toggle-display
  ##.cc-banner
  ##[data-cc-banner]
  ##div.c-site-messages
  ##[class^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; po…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[class^="div-gpt-ad"]
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by Petemir** [comment]
Having the exact same problem. The hidden cookie banner disables clicking anywhere on the page; getting rid of it (dialog.cc-banner) enables clicking again.

**Comment by andersjohansson** [comment]
Same issue with Springer site (same company and backend as Nature), for example:
https://link.springer.com/article/10.1007/s12013-024-01334-5

`link.springer.com##.cc-banner:remove()` worked for me.

**Comment by NooneAtAll3** [comment]
Custom filter for one website at a time is not a solution for "website element blocks uBO's most basic operation of lightning and pipette buttons"

Please reopen this issue. It is not fixed.

**Comment by mapx-** [comment]
> It is not fixed.

@NooneAtAll3 provide all the necessary info: link, issue explanation, your setup (uBO or uBOL, browser)
