### ISSUE TITLE
youtube.com: [unknown]

### ISSUE THREAD

**Issue by FabianS47** [uBlockOrigin/uAssets#24078]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=BhCVbVnPy5s`

### Category

[unknown]

### Description

the ads seems to be embed in the videos. I ve tried to reinstall ublock several times(like 30 times), update the filters several times (like 30 times) but still, the ads are embed. I ve uninstall all my extensions on chrome ( volume master and youtubenonstop) but still, the same.

P:s - I'm going brave.

P:s2 - still happening on brave too.

### Other extensions used

-

### Screenshot(s) - https://postimg.cc/wtwXcG3s    - https://postimg.cc/4mVy9ksd

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 137546
 cosmetic: 46518
 scriptlet: 21142
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38434-280, now Δ
  ublock-badware: 9219-0, now Δ
  ublock-privacy: 929-0, now
  ublock-unbreak: 2338-0, now
  ublock-quick-fixes: 149-0, now
  easylist: 86775-562, now
  easyprivacy: 51046-24, now
  urlhaus-1: 14395-0, now
  plowe-0: 3556-615, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 667 ms
 maxAssetCacheWait: 229 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  youtube.com: 11
  doubleclick.net: 3
  google.com: 1
 extended:
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by Haxorzz** [comment]
Hey I noticed you checked "This is NOT a YouTube, Facebook, Twitch or a shortener/hosting site report. These sites MUST be reported by clicking their respective links." while your issue is very clearly about youtube.

**Comment by FabianS47** [comment]
> Hey I noticed you checked "This is NOT a YouTube, Facebook, Twitch or a shortener/hosting site report. These sites MUST be reported by clicking their respective links." while your issue is very clearly about youtube.

well, yes, I lied! But yes, it is on that doomed platform.

**Comment by FabianS47** [comment]
> > Hey I noticed you checked "This is NOT a YouTube, Facebook, Twitch or a shortener/hosting site report. These sites MUST be reported by clicking their respective links." while your issue is very clearly about youtube.
> 
> well, yes, I lied! But yes, it is on that doomed platform. It is getting frustrating... imma finna go with walkman, sony ericsson or another platforms. I'm more inclined to buy music fisically but to pay youtube. Youtube now is a joke, they treat us like consumers. We are not, they are, they consume every bit of any artist on youtube. But I know that somebody knows this, like ublock!
> 
> Thank you for your answer!

The kid already disliked my post. please don't be on github ever @pallaswept
