### ISSUE TITLE
empire-stream.dev: detection

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#24083]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://empire-stream.dev/film/Back-to-Black-en-streaming-hd/2017371873a30fb9e032141660035666`

### Category

detection

### Description

This french streaming site detects ublock origin. 

### Other extensions used
Mostly nothing changes the site
- Violentmonkey
- Cookie Editor
- Downthemall
- Sponsorblock
Dont have to count more since its not related to breakage.

### Screenshot(s)

Original (French)
![librewolf_2jT4QF7EKz](https://github.com/uBlockOrigin/uAssets/assets/150899804/0b853761-6d27-4bca-b961-96c279c72757)

Translated (Eng)
![librewolf_Pxc3g6KwZX](https://github.com/uBlockOrigin/uAssets/assets/150899804/676b73e8-4f5e-4673-a88f-4cb8ebaab64e)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 125
filterset (summary):
 network: 162236
 cosmetic: 125846
 scriptlet: 26492
 html: 1854
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51179-184, 5m
  ublock-cookies-easylist: 1213-5, 5m
  easylist-annoyances: 4664-51, 5m
  easylist-chat: 196-0, 5m
  easylist-newsletters: 7539-20, 5m
  easylist-notifications: 3023-164, 5m
  RUS-0: 39515-184, 5m
 default:
  user-filters: 63-3, never
  ublock-filters: 38546-112, 5m
  ublock-badware: 9221-0, 5m
  ublock-privacy: 920-2, 5m
  ublock-unbreak: 2397-2, 5m
  ublock-quick-fixes: 149-8, 8m Δ
  easylist: 86790-173, 5m
  adguard-spyware-url: 1537-120, 5m
  easyprivacy: 51047-65, 5m
  urlhaus-1: 14145-0, 5m
  curben-phishing: 486-1, 5m
  plowe-0: 3556-989, 5m
  LegitimateURLShortener: 2648-160, 1h.23m
filterset (user): [array of 63 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 631 ms (selfie)
 maxAssetCacheWait: 201 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  endowmentoverhangutmost.com: 4
  linkadvdirect.com: 1
 extended:
  ##+js(set-constant, empire.pop, undefined)
  ##+js(set-constant, empire.direct, undefined)
  ##+js(set-constant, empire.directHideAds, undefined)
  ##+js(trusted-replace-node-text, script, '/data: \[.*\],/', 'dat…
  ##+js(adjust-setTimeout, (!1), *)
  ##+js(no-xhr-if, pagead2.googlesyndication.com)
```
</details>

**Comment by mapx-** [comment]
test

`@@||endowmentoverhangutmost.com/*/code.js$script,domain=empire-stream.dev`

**Comment by ThePatriotsXOF** [comment]
> test
> 
> `@@||endowmentoverhangutmost.com/*/code.js$script,domain=empire-stream.dev`

this does the job.

**Comment by Yaroslav-Total** [comment]
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=https%3A%2F%2Fcdn.statically.io%2Fgh%2Fdhowe%2FAdNauseam%2Fmaster%2Ffilters%2Fadnauseam.txt

https://cdn.statically.io/gh/dhowe/AdNauseam/master/filters/adnauseam.txt  Фильтры.
