### ISSUE TITLE
geotastic.net: detection

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#24086]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://geotastic.net/
```

### Description

There is a notice on the Geotastic website requesting users to disable their adblocker. I attached two screenshots below.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1767" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/123986260/ea02a530-881b-4688-b64e-534affe83b44">
<img width="512" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/123986260/279f0e10-3ace-43a0-8566-ab93c53edba9">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
Your config details is empty.

Did you enable `uBlock filters – Annoyances` list ?

**Comment by loadstring1** [comment]
if you are using firefox turning off built-in tracking protection seems to work and bypass this anti adblock notice.

im unsure what browser OP is using so im just letting you know just in case :)
