### ISSUE TITLE
instagram.com: ads (stories)

### ISSUE THREAD

**Issue by shaunangus** [uBlockOrigin/uAssets#24097]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.instagram.com/`
`https://www.instagram.com/stories/americanexpressuk/3382865046273621981/`

### Category

ads

### Description

Starting today, I'm seeing Sponsored ads (in stories only) on Instagram. This also occurs on Chrome (backup browser I never use) - both with and without other extensions enabled, cookies cleared, uBlock settings reset, etc. I use Firefox and am in the UK.

### Other extensions used

I am submitting this with _none_ enabled, and still the issue persists. But my usual extensions are as followed: 

- 7TV
- Allow Right-Click
- cookies.txt
- Don't Accept image/webp
- DownThemAll!
- Ghostery Tracker Ad Blocker - Privacy Adblock
- Image Max URL
- Internet Archive Downloader
- Reddit Enhancement Suite
- Return YouTube Dislike
- Search by Image on Google
- Tampermonkey
- TinEye Reverse Image Search
- To Google Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/91890031/98de0392-f149-477b-b43a-85c6b9c3a19e)

![image](https://github.com/uBlockOrigin/uAssets/assets/91890031/de33990b-4493-481e-a4c0-487e85edbc43)

![image](https://github.com/uBlockOrigin/uAssets/assets/91890031/f6fd641f-8f2f-453a-b298-812d531ff12c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 137647
 cosmetic: 46450
 scriptlet: 19738
 html: 1838
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38569-112, 4m
  ublock-badware: 9221-0, 1m Δ
  ublock-privacy: 920-2, 4m
  ublock-unbreak: 2397-2, 4m
  ublock-quick-fixes: 153-8, 1m Δ
  easylist: 86798-173, 1m Δ
  easyprivacy: 51049-65, 1m Δ
  urlhaus-1: 14515-0, 4m
  plowe-0: 3556-989, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2453 ms
 maxAssetCacheWait: 393 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  instagram.com: 7
  doubleclick.net: 1
  facebook.com: 1
 extended:
  ##main > div div[style*="flex-direction: column;"] > article > d…
  ##article:has(a[href^="https://www.facebook.com/ads/"]):style(he…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
```
</details>

**Comment by PootisPowah** [comment]
Same issue here...

**Comment by Fatcavill** [comment]
![Screenshot_20240807-135801](https://github.com/user-attachments/assets/462bcf23-900e-4637-8227-53733a71d540)
in reels tab scrolling to bottom makes this screen

**Comment by D4niloMR** [comment]
@Fatcavill Try:

```adb
instagram.com###fb-root ~ div[data-visualcompletion="ignore"][style] + div[class][style*="--ig-dropdown-background:"]
```

**Comment by Fatcavill** [comment]
works.tnx bro
