### ISSUE TITLE
bloomberg.com: breakage

### ISSUE THREAD

**Issue by deten** [uBlockOrigin/uAssets#24090]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bloomberg.com/markets/economic-calendar`

### Category

break

### Description

The content on this page is being blocked (the calendar)

### Other extensions used

verified it was only ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/6029514/4a01a71b-1f60-4b49-8bcc-cedb8f961a42)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 165420
 cosmetic: 224182
 scriptlet: 51531
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79531-722, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99622-23409, now
  adguard-generic: 81217-6205, now
  ublock-annoyances: 5915-14, now
  ublock-quick-fixes: 153-0, now
 default:
  user-filters: 28-3, never
  easylist: 86792-564, now
  easyprivacy: 51049-656, now
  plowe-0: 3556-0, now
  ublock-badware: 9219-0, now
  ublock-filters: 38454-281, now
  ublock-privacy: 929-0, now
  ublock-unbreak: 2338-1, now
  urlhaus-1: 14505-0, now
filterset (user): [array of 28 redacted]
trustedset:
 added: [array of 45 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3131 ms
 maxAssetCacheWait: 882 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  bloomberg.com: 4
  bbthat.com: 1
  doubleclick.net: 1
  forexprostools.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  ml314.com: 1
  moatads.com: 1
  newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||econcal.forexprostools.com^$frame,domain=bloomberg.com`

@ryanbr

**Comment by deten** [comment]
Thank you, this fixed it perfectly.     
    On Thursday, June 13, 2024 at 10:30:58 AM PDT, mapx ***@***.***> wrote:  
 
 


add

@@||econcal.forexprostools.com^$frame,domain=bloomberg.com

@ryanbr
