### ISSUE TITLE
odysee.com: ads

### ISSUE THREAD

**Issue by MillionsToOne** [uBlockOrigin/uAssets#24091]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://odysee.com/`

### Category

ads

### Description

Premium ads on Odysee aren't removed automatically and can't be removed manually by using the picker tool. Only element zapper works, but it isn't permanent. Note that the banner ads aren't visible when logged in.

### Other extensions used

Bitwarden: Active
User-Agent Switcher: Not active
Privacy Badger: Active
ViolentMonkey: Not active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/113781708/26e17457-328b-40d3-8a53-f02c06a7a0dc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 142279
 cosmetic: 48504
 scriptlet: 19766
 html: 1844
listset (total-discarded, last-updated):
 added:
  FIN-0: 2284-1, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38562-112, 17m Δ
  ublock-badware: 9221-0, 17m Δ
  ublock-privacy: 920-2, 17m Δ
  ublock-unbreak: 2397-2, 17m Δ
  ublock-quick-fixes: 153-8, 17m Δ
  easylist: 86792-173, 17m Δ
  adguard-spyware-url: 1538-120, now
  easyprivacy: 51049-65, 17m Δ
  urlhaus-1: 14505-0, now
  curben-phishing: 556-2, now
  plowe-0: 3556-989, now
  LegitimateURLShortener: 2648-160, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 471 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
  odysee.tv: 3
```
</details>

**Comment by mapx-** [comment]
We do not block self-promotion stuff.

add
`odysee.com##.claim-preview--premium-plus`
