### ISSUE TITLE
telkomsel.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#24098]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.telkomsel.com/jelajah/jelajah-lifestyle/bacaan-doa-untuk-bayi-baru-lahir-beserta-arti-dan-manfaatnya`

### Category

breakage

### Description

break

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/c451ac37-b3f6-4e79-8340-ba9613f194c3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 146788
 cosmetic: 162336
 scriptlet: 34354
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8596-15, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 208-1, now
  adguard-other-annoyances: 14435-8, now
  adguard-popup-overlays: 27192-61, now
  easylist-annoyances: 4664-227, now
  easylist-chat: 196-0, now
  easylist-newsletters: 7511-536, now
  easylist-notifications: 3023-401, now
  fanboy-cookiemonster: 51180-259, now
  fanboy-social: 16256-50, now
  ublock-annoyances: 5915-174, 55m Δ
  ublock-cookies-easylist: 1214-1, now
 default:
  user-filters: 51-1, never
  easylist: 86798-646, 55m Δ
  easyprivacy: 51049-107, 55m Δ
  plowe-0: 3556-615, now
  ublock-badware: 9219-1, 55m Δ
  ublock-filters: 38461-695, 55m Δ
  ublock-privacy: 929-5, 55m Δ
  ublock-quick-fixes: 153-0, 55m Δ
  ublock-unbreak: 2338-21, 55m Δ
  urlhaus-1: 14515-0, now
filterset (user): [array of 51 redacted]
trustedset:
 added: [array of 30 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 727 ms (selfie)
 maxAssetCacheWait: 247 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  adsrvr.org: 1
  googletagmanager.com: 1
  pubmatic.com: 4
 extended:
  ###cookiesSection
  ##.cookies-section
  ##.cookies-wrapper
  ##.cookies-content
  ##.cookies-row
  ##.sticky-share
  ##.sticky-ads-right
  ##.sticky-ads
  ###adsContainer
  ##.ads-desktop
```
</details>

**Comment by stephenhawk8054** [comment]
I don't understand. What is broken?

**Comment by stephenhawk8054** [comment]
@ryanbr
