### ISSUE TITLE
kisscartoon.me videos don't play

### ISSUE THREAD

**Issue by Bluberius** [uBlockOrigin/uAssets#241]
### URL(s) where the issue occurs

`http://kisscartoon.me/Cartoon/The-Simpsons-Season-08/Episode-001?id=458`

### Describe the issue

Videos on kisscartoon.me don't play with the default settings.

### Versions

- Browser/version: Waterfox 50.1.0
- uBlock Origin version: 1.10.4

### Settings

- default settings

### Notes

I tracked the issue down to the "uBlock filters‎" list. With this filter list disabled the video plays.

**Comment by uBlock-user** [comment]
`kisscartoon.me##script:inject(abort-on-property-write.js, _0x408a)`

That's the one causing the videos not to load.

**Comment by uBlock-user** [comment]
Thanks. Kissanime also needs to be updated as they swapped their domain to .ru from .to, just an FYI

**Comment by okiehsch** [comment]
**Notes:** The fix works with HTML5 Player, can't test with flash.
