### ISSUE TITLE
t-online.de/tv/tv-highlights/…

### ISSUE THREAD

**Issue by bestoernesto** [uBlockOrigin/uAssets#2410]
### URL(s) where the issue occurs 
Anti adblock killer doesn't work: 
`t-online.de/tv/tv-highlights/pro7sat1/id_83841120/frankreich-feiert-den-spiderman-aus-mali.html`

### Describe the issue 
Anti adblock killer doesn't work

### Versions

- Browser/version: [firefox 56.02]
- uBlock Origin version: [1.16.8]

**Comment by okiehsch** [comment]
Already fixed with https://github.com/uBlockOrigin/uAssets/commit/92cde3329d9df76f39d5b1ba08dae6422654884b
