### ISSUE TITLE
wetransfer.com: breakage

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#24105]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://wetransfer.com/
```

### Description

The cookie prompt background is still there and means you can't click on anything.

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/6c396416-4be1-4149-a2d3-a29b8e9aed4e)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 219034
 cosmetic: 253100
 scriptlet: 51578
 html: 2100
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81205-4026, 4d.12m
  adguard-mobile: 9440-58, 4d.12m
  adguard-spyware-url: 1534-120, 4d.12m
  adguard-spyware: 69770-1513, 4d.12m
  block-lan: 68-0, 4d.12m
  curben-phishing: 511-1, 7h.44m
  adguard-social: 23197-55, 4d.12m
  adguard-cookies: 30021-50, 4d.12m
  ublock-cookies-adguard: 1191-15, 4d.12m
  adguard-popup-overlays: 27157-1077, 4d.12m
  adguard-mobile-app-banners: 5293-25, 4d.12m
  adguard-other-annoyances: 14425-469, 4d.12m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38613-116, 50m Δ
  ublock-badware: 9226-0, 50m Δ
  ublock-privacy: 920-2, 50m Δ
  ublock-unbreak: 2397-3, 50m Δ
  ublock-quick-fixes: 147-0, 50m Δ
  easylist: 86866-2257, 50m Δ
  easyprivacy: 51050-28851, 50m Δ
  urlhaus-1: 14515-0, 10h.44m
  plowe-0: 3555-1483, 4d.12m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 438 ms (selfie)
 maxAssetCacheWait: 183 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  wetransfer.com: 1
  ethyca.com: 1
  googlesyndication.com: 1
  profitwell.com: 1

```
</details>

**Comment by the9655a** [comment]
There's also a second agree screen which you dont reach unless you either reject or accept the first prompt. If you don't, the nav buttons break and don't work.

Also a nuisance:
![image](https://github.com/uBlockOrigin/uAssets/assets/149513282/a1d6d071-c77f-4c68-a3a7-6e68c42efc35)

**Comment by mapx-** [comment]
enable `uBlock filters – Cookie Notices`
