### ISSUE TITLE
qwant.com: breakage

### ISSUE THREAD

**Issue by jbastruz** [uBlockOrigin/uAssets#24112]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.qwant.com/?llm_force=true&q=test+de+recherche&t=web`

### Category

breakage

### Description

qwant doesn't work properly

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 138454
 cosmetic: 46579
 scriptlet: 21220
 html: 0
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 default:
  user-filters: 0-0, never
  easylist: 86880-564, 1h.15m Δ
  easyprivacy: 51051-639, 1h.15m Δ
  plowe-0: 3552-0, now
  ublock-badware: 9224-0, 1h.15m Δ
  ublock-filters: 38544-276, 1h.15m Δ
  ublock-privacy: 929-0, 1h.15m Δ
  ublock-quick-fixes: 148-0, 1h.15m Δ
  ublock-unbreak: 2338-0, 1h.15m Δ
  urlhaus-1: 15220-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 875 ms (selfie)
 maxAssetCacheWait: 142 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  qwant.com: 13
```
</details>

**Comment by JobcenterTycoon** [comment]
What doesn’t work?
