### ISSUE TITLE
macwelt.de ads show

### ISSUE THREAD

**Issue by thetommes** [uBlockOrigin/uAssets#2411]
### URL(s) where the issue occurs

All macwelt.de sites, for example: 
`https://www.macwelt.de/a/airplay-2-fragen-und-antworten-zur-neuen-technologie,3438893`

### Describe the issue

Ads show after a while, even though all filterlists are up-to date.

### Screenshot(s)

https://imgur.com/a/NZxJruQ

### Versions

- Browser/version:  Chrome 67.0.3396.62 (64-Bit)
- uBlock Origin version: 1.16.8

### Settings

My filterlists: https://i.imgur.com/9tg1e6C.png

### Notes

I don't know if uAssets is the right place for posting this but it seems all ads come from XXXXXXX.ofzrnqi.com. If i block the domain, the ads disappear.

**Comment by mapx-** [comment]
test these filters
```
||macwelt.de^$csp=script-src 'self' 'unsafe-eval' 'unsafe-inline' data: *.apester.com *.accengage.net *.googleapis.com *.disqus.com *.spoods.io *.googletagservices.com *.googletagmanager.com *.outbrain.com *.sharethrough.com *.onthe.io *.cloudflare.com
macwelt.de##.loaded.standard.marketplace
```

**Comment by KiLL4FuNK** [comment]
the filters work very well

**Comment by thetommes** [comment]
Yeah, filters work. Please add them.
