### ISSUE TITLE
dev.to: nuisance

### ISSUE THREAD

**Issue by Simon-Tang** [uBlockOrigin/uAssets#24120]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dev.to/oliverjumpertz/making-good-use-of-ts-expect-error-in-typescript-1f41`

### Category

nuisance

### Description

There is a bottom banner that acts as a way to funnel visitors into making a new account. The docs (https://dev.to/billboards) give some more context. The banner uses some dark patterns (or just plain confusing text) to get people to sign up for an account.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/5322400/34c24207-233e-43d7-af85-22777e7a452d)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 138343
 cosmetic: 46459
 scriptlet: 19742
 html: 1840
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38634-112, 1h.45m Δ
  ublock-badware: 9231-0, 1h.45m Δ
  ublock-privacy: 918-2, 1h.45m Δ
  ublock-unbreak: 2398-2, 1h.45m Δ
  ublock-quick-fixes: 88-3, 1h.45m Δ
  easylist: 86896-180, 1h.45m Δ
  easyprivacy: 51057-65, 1h.45m Δ
  urlhaus-1: 15115-0, now
  plowe-0: 3552-988, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2240 ms
 maxAssetCacheWait: 799 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  dev.to: 2
  duckduckgo.com: 2
  googletagmanager.com: 1
 extended:
  ##.popover-billboard
```
</details>

**Comment by peace2000** [comment]
@Simon-Tang Easylist Annoyances list is already handling that banner. Please enable it in your settings.
