### ISSUE TITLE
fake bloxstrap websites

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#24123]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://bloxstrapmenu.com/
https://bloxstrap.com/
https://bloxstrap.org/
https://bloxstrap.io/
https://bloxstrap.dev/
https://bloxstrap.app/
https://bloxstrap.co/
https://bloxstrap.pro/
```

### Description

All of these sites are fake bloxstrap domains that claim to be official and very likely host malicious links/versions of the bloxstrap installer. They're hosted on the site, one hosts it on archive.org, so they're not fan sites for example that redirect to the official gh repo, the only official place to get it. These sites are also found high up in search results from popular search engines. So they need adding to the badware risks filter.

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
not needed I think

```
</details>

**Comment by JobcenterTycoon** [comment]
We don’t block sites just because they are "unofficial" or because they "maybe host malware". We only block real threads.

**Comment by k-awn** [comment]
bloxstrap.org shows up higher than github so I downloaded that one before I found out wasn't official, it immediately updated me to 2.6.1 when I launched it and when I scan for viruses Windows Defender can't find any. should I factory reset my computer? I don't really know what to do rn
