### ISSUE TITLE
RBTV77.com: detection

### ISSUE THREAD

**Issue by Vaskiemaia** [uBlockOrigin/uAssets#24129]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.rbtv77.com/
```

### Description

The website (and any subsequent links inside it) detect UBO and block the page.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![RBTV](https://github.com/uBlockOrigin/uAssets/assets/80223024/e4cff688-d4db-4357-805b-cf03e8b70293)

### Configuration

uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139247
 cosmetic: 50499
 scriptlet: 21624
 html: 0
listset (total-discarded, last-updated):
 added:
  spa-1: 5761-28, 1h.42m
 default:
  user-filters: 8-0, never
  easylist: 86897-609, 1h.44m Δ
  easyprivacy: 51057-814, 1h.44m Δ
  plowe-0: 3552-0, 1h.42m
  ublock-badware: 9229-0, 1h.44m Δ
  ublock-filters: 38531-108, 1h.38m
  ublock-privacy: 929-0, 1h.44m Δ
  ublock-quick-fixes: 95-3, 1h.44m Δ
  ublock-unbreak: 2339-5, 1h.44m Δ
  urlhaus-1: 14695-0, 1h.44m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 514 ms (selfie)
 maxAssetCacheWait: 326 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  acscdn.com: 1
  googletagmanager.com: 1
  paiddesertjil3m.autos: 2
  yandex.ru: 1
 extended:
  ##+js(abort-on-stack-trace, document.getElementById, /(?=^(?!.*(…

**Comment by stephenhawk8054** [comment]
Just continue in the old thread. Don't open duplicated issue.
