### ISSUE TITLE
alfalfalfa.com: nuisance

### ISSUE THREAD

**Issue by SatoshiITO** [uBlockOrigin/uAssets#24122]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://alfalfalfa.com/`

### Category

nuisance

### Description

Overlay popup still exist.

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 140369
 cosmetic: 59095
 scriptlet: 21350
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  JPN-1: 14796-4, now
  easylist: 86896-488, 22m Δ
  easyprivacy: 51057-665, 22m Δ
  plowe-0: 3552-5, now
  ublock-badware: 9229-11, 22m Δ
  ublock-filters: 38530-384, 22m Δ
  ublock-privacy: 927-0, 22m Δ
  ublock-quick-fixes: 88-2, 22m Δ
  ublock-unbreak: 2339-3, 22m Δ
  urlhaus-1: 15115-0, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 535 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##div[style$="height:250px;"]
  ###Sticky-Left
  ##div[id^="crt-"][style]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by peace2000** [comment]
What popup are you referring to?

If this one:

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/bd7eb152-f4fc-4268-87d7-355512c788f0)

Then you need to enable either Easylist/uBO or Adguard/uBO Cookie notices list in your settings.
