### ISSUE TITLE
xoilacz.dev: ads

### ISSUE THREAD

**Issue by ducdunggl2014** [uBlockOrigin/uAssets#24127]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://xoilacz.dev/`

### Category

ads

### Description

ads

### Other extensions used

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138406
 cosmetic: 47823
 scriptlet: 21356
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  VIE-1: 1936-0, 1h.12m
  easylist: 86896-589, 1h.12m Δ
  easyprivacy: 51057-641, 1h.12m Δ
  plowe-0: 3552-0, now
  ublock-badware: 9229-0, 1h.12m Δ
  ublock-filters: 38531-281, 1h.12m Δ
  ublock-privacy: 927-0, 1h.12m Δ
  ublock-quick-fixes: 88-0, 1h.12m Δ
  ublock-unbreak: 2339-0, 1h.12m Δ
  urlhaus-1: 14695-0, 1h.12m
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 872 ms (selfie)
 maxAssetCacheWait: 526 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  xoilacz.dev: 1
  googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/abpvn/abpvn/issues/775

**Comment by stephenhawk8054** [comment]
Fixed in https://github.com/abpvn/abpvn/commit/5787c744be332ed240b9809e6ba2fce437e29bad
