### ISSUE TITLE
[nsfw] 4kporn.xxx: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#24138]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://4kporn.xxx/videos/1094134/fucking-my-college-girlfriend-in-hotel-room/?utm_source=pbw&utm_campaign=plugs`

### Category

popups

### Description

click play
has banner ad

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 110
filterset (summary):
 network: 147342
 cosmetic: 145644
 scriptlet: 29097
 html: 0
listset (total-discarded, last-updated):
 added:
 ublock-annoyances: 5947-42, now
 default:
  user-filters: 32-6, never
  ublock-filters: 38989-833, 1h.7m Δ
  ublock-badware: 9229-1, 1h.7m Δ
  ublock-privacy: 932-0, 1h.7m Δ
  ublock-unbreak: 2343-2, 1h.7m Δ
  ublock-quick-fixes: 89-0, 1h.7m Δ
  adguard-mobile: 9503-11, now
  easylist: 86909-702, 1h.7m Δ
  easyprivacy: 51058-758, 1h.7m Δ
  urlhaus-1: 15130-0, now
  plowe-0: 3552-83, now
filterset (user): [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1451 ms (selfie)
 maxAssetCacheWait: 118 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  4kporn.xxx: 3
  googletagmanager.com: 1
  magsrv.com: 2
  o333o.com: 1
 extended:
  ##.bottom-adv
  ##.lists > li:has(> a[href="#tab_share"])
  ##.footer-margin
  ##a[href^="https://go.xlirdr.com"]
  ##a[href^="https://go.xlivrdr.com"]
  ##a[href^="https://s.zlink3.com/"]
  ##+js(set-constant, flashvars.popunder_url, )
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
4kporn.xxx##.myadswarning
4kporn.xxx##.sponsorbig
```

@ryanbr

**Comment by Fatcavill** [comment]
I tested filter but still when i click play there is a popup

**Comment by Fatcavill** [comment]
Kiwi browser/chrome

**Comment by stephenhawk8054** [comment]
Kiwi browser is not officially supported. Test again in Firefox mobile.

**Comment by Fatcavill** [comment]
oh works in firefox but popups appear in any chrome based browser

**Comment by JobcenterTycoon** [comment]
Additional:
```
||dl.4kporn.xxx^
||4kporn.xxx/static/analytics/
4kporn.xxx##.ads
4kporn.xxx##.item:has(> [class*="ads"])
```

**Comment by Fatcavill** [comment]
works for me in kiwi thanks bro
