### ISSUE TITLE
lyngsat.com: breakage

### ISSUE THREAD

**Issue by ilikenwf** [uBlockOrigin/uAssets#24139]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lyngsat.com/Eutelsat-117-West-A-B.html`

### Category

breakage

### Description

The main page content disappears after the page loads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 172578
 cosmetic: 253018
 scriptlet: 50021
 html: 2103
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79569-137, now
  https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/TrackParamFilter/sections/general_url.txt: 223-0, now
  https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/TrackParamFilter/sections/specific.txt: 1273-5, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99682-23262, now
  adguard-generic: 81296-4044, now
  adguard-mobile: 9503-72, now
  block-lan: 68-0, now
  adguard-social: 23274-1654, now
  fanboy-thirdparty_social: 68-19, now
  fanboy-cookiemonster: 51211-51211, now
  fanboy-social: 16259-16259, now
  ublock-annoyances: 5867-250, 17m Δ
 default:
  user-filters: 56-1, never
  ublock-filters: 38658-448, 17m Δ
  ublock-badware: 9237-0, 17m Δ
  ublock-privacy: 922-118, 17m Δ
  ublock-unbreak: 2399-8, 17m Δ
  ublock-quick-fixes: 82-5, 17m Δ
  easylist: 86920-2339, 17m Δ
  adguard-spyware-url: 1538-1485, now
  easyprivacy: 51058-326, 17m Δ
  urlhaus-1: 15130-0, now
  curben-phishing: 423-1, now
  plowe-0: 3552-1078, now
  LegitimateURLShortener: 2653-160, 17m
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 665 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 171 redacted]
hostRuleset:
 added: [array of 389 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1769 ms (selfie)
 maxAssetCacheWait: 490 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  lyngsat.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##tr[valign="baseline"]
  ##a[href="http://www.lyngsat.com/advert.html"]
  ##td[width="160"][height="600"]
  ##[width="728"]
  ##img[width="728"][height="90"]
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `lyngsat.com##[width="728"]`

**Comment by ilikenwf** [comment]
Thank you all.

**Comment by ghost** [comment]
There are two ad leftovers:

https://github.com/user-attachments/assets/f1e61f56-0fbc-4186-ba50-8894ecce1f52
https://github.com/user-attachments/assets/99468020-8da0-4a4f-abb5-0859847d91f3

**Comment by ghost** [comment]
The ad leftovers are still here:
<img width="1398" height="851" alt="Image" src="https://github.com/user-attachments/assets/b1ac4257-584b-44ef-8c57-87a4c71de986" />
