### ISSUE TITLE
[nsfw] 2chan.net: ads

### ISSUE THREAD

**Issue by q03993u** [uBlockOrigin/uAssets#24131]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://www.2chan.net/`

### Category

ads

### Description

some nsfw ads make it past filters, all boards
ad leftovers on all boards

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 138211
 cosmetic: 46560
 scriptlet: 21166
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 86896-568, 1h.31m Δ
  easyprivacy: 51057-618, 1h.31m Δ
  plowe-0: 3552-0, 49m
  ublock-badware: 9229-0, 1h.31m Δ
  ublock-filters: 38531-275, 1h.31m Δ
  ublock-privacy: 927-3, 1h.31m Δ
  ublock-quick-fixes: 88-0, 1h.31m Δ
  ublock-unbreak: 2339-18, 1h.31m Δ
  urlhaus-1: 14950-0, 49m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1723 ms (selfie)
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  ad-stir.com: 2
  gsspcln.jp: 1
  i-mobile.co.jp: 22
  microad.net: 2
  reajyu.net: 1
 extended:
  ###rightad
```
</details>

**Comment by stephenhawk8054** [comment]
Enable ` jp: AdGuard Japanese` list and test again.
