### ISSUE TITLE
usanetwork.com: breakage 

### ISSUE THREAD

**Issue by UncleAdolfH** [uBlockOrigin/uAssets#24142]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.usanetwork.com/race-to-survive-new-zealand/video/water-and-ice/9000394410`

### Category

breakage

### Description

Video doesn't play when ublock enabled on the site. Will play when turned off

### Other extensions used

File Centipede, go back with backspace, gnome shell extension.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.1b6
Chromium: 124
filterset (summary):
 network: 138423
 cosmetic: 46565
 scriptlet: 21185
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38559-376, 31m Δ
  ublock-badware: 9235-0, 31m Δ
  ublock-privacy: 931-0, 31m Δ
  ublock-unbreak: 2340-0, 31m Δ
  ublock-quick-fixes: 82-0, 31m Δ
  easylist: 86920-467, 31m Δ
  easyprivacy: 51058-638, 31m Δ
  urlhaus-1: 15130-0, 31m
  plowe-0: 3552-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 279 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 no-popups: true
 network:
  adobedtm.com: 2
  amplitude.com: 1
  branch.io: 1
  brightline.tv: 2
  googletagmanager.com: 1
  iterable.com: 1
  nbcuni.com: 1
  scorecardresearch.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr There's video ads as well

For EP breakage

```adb
@@||assets.adobedtm.com/extensions/*/AppMeasurement.min.js$domain=usanetwork.com
```

For video ads

```adb
||video-ads-module.ad-tech.nbcuni.com^
```
