### ISSUE TITLE
x.com: breakage

### ISSUE THREAD

**Issue by rawesomeawesome** [uBlockOrigin/uAssets#24140]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://x.com/`

### Category

breakage

### Description

Videos autopause themselves as if clicked by the user, the cause seems to be an "interaction detection" that twitter is using to look for button presses and scrolling to pause the video/gif, but that the removal of certain kinds of loaded ads triggers as well. Only a best guess, as the pausing happens at about the rate that new banner ads and such are loaded/removed

There are no visual issues, just a non-buffering related video pausing effect.
 
most importantly of all, disabling Ublock fixes the issue, regardless of other factors

### Other extensions used

Keeper (passwords, all sites)
Sponsorblock (youtube only)
ublock (this, all sites)
adblock for youtube (also youtube only)
Hide google Ai overviews (Google only)
Tabs for a cause (new tabs only)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138422
 cosmetic: 46565
 scriptlet: 21180
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86920-566, 15m Δ
  easyprivacy: 51058-638, 15m Δ
  plowe-0: 3552-0, now
  ublock-badware: 9235-0, 15m Δ
  ublock-filters: 38553-277, 15m Δ
  ublock-privacy: 931-0, 15m Δ
  ublock-quick-fixes: 82-0, 15m Δ
  ublock-unbreak: 2340-0, 15m Δ
  urlhaus-1: 15130-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 393 ms (selfie)
 maxAssetCacheWait: 218 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 335
 network:
  x.com: 334
  ads-twitter.com: 1
 extended:
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by rawesomeawesome** [comment]
in before this issue gets closed on a technicality (despite being unfixed), because I always have that happen ayylmao

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by PixsaOJ** [comment]
Fresh browser, no settings changed for uBlock Origin.  Can not log in, it loads infinietly.

POST requiest to `	https://api.x.com/1.1/jot/client_event.json` is Getting blocked.

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by PixsaOJ** [comment]
> Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

Sorry, it was actually my browsers enhanced tracking protection

**Comment by stephenhawk8054** [comment]
Please read the prerequisites in the 1st post of the issue thread before reporting please

> - [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.

**Comment by PixsaOJ** [comment]
Well I did not post

**Comment by stephenhawk8054** [comment]
The prerequisites apply to all reports

> read the prerequisites in the 1st post of the issue thread before reporting
