### ISSUE TITLE
hail-the-apocalypse.forumactif.com: breakage

### ISSUE THREAD

**Issue by MsPhoebeParker** [uBlockOrigin/uAssets#24145]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hail-the-apocalypse.forumactif.com/`

### Category

breakage

### Description

Forumactif has a Search fonction on every one of its forums. Apparently, from what some people managed to find out, there is a "new" rule in ad blockers extentions that hides all fields with a "_" character in the onclick attribute, which is the case for the Search link.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

No adult material in this but it's easier for me to post with links : 
This is what appears WITH Ublock : https://zupimages.net/up/24/25/wh3d.jpg
This is what appears WITHOUT Ublock : https://zupimages.net/up/24/25/58fl.jpg ( that's the way the site should appear )

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 155602
 cosmetic: 53061
 scriptlet: 19923
 html: 1841
listset (total-discarded, last-updated):
 default:
  user-filters: 5-3, never
  ublock-filters: 38674-112, 41m Δ
  ublock-badware: 9237-0, 41m Δ
  ublock-privacy: 922-2, 41m Δ
  ublock-unbreak: 2399-2, 41m Δ
  ublock-quick-fixes: 82-3, 41m Δ
  easylist: 86936-178, 41m Δ
  easyprivacy: 51060-64, 41m Δ
  urlhaus-1: 14875-0, now
  plowe-0: 3552-988, now
  FRA-0: 24677-403, now
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 310 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  criteo.net: 2
  doubleclick.net: 2
  google.com: 6
  googletagmanager.com: 1
  youtube.com: 9
 extended:
  ##.croco_wrapper, [onclick*="_"], [onclick*="var"], [onmousedown…
  ##div[id^="crt-"][style]
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
```
</details>

**Comment by stephenhawk8054** [comment]
@smed79 Sorry, can you check this?
