### ISSUE TITLE
unsplash.com: popups cookies banner

### ISSUE THREAD

**Issue by arrond2** [uBlockOrigin/uAssets#24159]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://unsplash.com/s/photos/razer`

### Category

popups

### Description

Cookie banner still displayed

### Other extensions used

Easylist Cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-18 172558](https://github.com/uBlockOrigin/uAssets/assets/173185269/04f0debb-894f-427b-9831-c4b397547c12)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 140395
 cosmetic: 91693
 scriptlet: 24960
 html: 1843
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51218-185, now
  ublock-cookies-easylist: 1214-3, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38713-112, now
  ublock-badware: 9237-0, now
  ublock-privacy: 922-2, now
  ublock-unbreak: 2399-2, now
  ublock-quick-fixes: 82-3, now
  easylist: 86953-179, now
  easyprivacy: 51063-64, now
  urlhaus-1: 15230-0, now
  plowe-0: 3552-988, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 240 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  unsplash.com: 4
  adzerk.net: 3
  doubleclick.net: 3
  google.com: 4
  googletagmanager.com: 1
  imrworldwide.com: 1
  insightexpressai.com: 4
  sentry.io: 6
 extended:
  ##div:has(> div[data-affiliates-grid-container])
  ##div[data-test^="masonry-grid"] > div[style^="--row"] > div:not…
  ##a[rel^="sponsored"]
  ##div[data-ad="true"]
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?
