### ISSUE TITLE
blackwoodacademy.org: detection

### ISSUE THREAD

**Issue by shenawy36** [uBlockOrigin/uAssets#24157]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://blackwoodacademy.org/how-to-secure-a-business-loan-essential-tips-and-common-pitfalls/`
used in "kyshort.xyz/OW8cepong14"

### Category

detection

### Description

Hello,
This was previously mentioned 4 days ago but the problem was not resolved
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-9772450
I would like to ask another question, please
How can I cancel an existing filter in the basic Ubo filter, such as Ubo filters - ads?

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 142964
 cosmetic: 196093
 scriptlet: 16017
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
 added:
  adguard-cookies: 30087-70, now
  adguard-mobile-app-banners: 5300-8, now
  adguard-other-annoyances: 14450-10, now
  adguard-popup-overlays: 27201-967, now
  adguard-social: 23280-1649, now
  adguard-widgets: 2543-17, now
  easylist-annoyances: 4670-133, now
  easylist-chat: 197-0, now
  easylist-newsletters: 7529-27, now
  easylist-notifications: 3025-1376, now
  fanboy-cookiemonster: 51218-3976, now
  fanboy-social: 16273-19, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 2789-215, never
  easylist: 86940-549, 1h.50m Δ
  easyprivacy: 51061-90, 1h.51m Δ
  plowe-0: 3552-615, now
  ublock-badware: 9235-0, 1h.50m Δ
  ublock-privacy: 931-5, 1h.50m Δ
  ublock-quick-fixes: 82-0, 1h.51m Δ
  ublock-unbreak: 2340-21, 1h.50m Δ
  urlhaus-1: 15230-0, now
filterset (user): [array of 795 redacted]
trustedset:
 added: [array of 62 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 44502 ms (selfie)
 maxAssetCacheWait: 8678 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
</details>

**Comment by shenawy36** [comment]
@ghajini Where is the solution to the problem, brother ?
Has it been solved because I see the problem still exists ?

**Comment by gwarser** [comment]
> * This is **NOT** a ... [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
