### ISSUE TITLE
isthereanydeal.com: breakage

### ISSUE THREAD

**Issue by My-life-is-over** [uBlockOrigin/uAssets#24153]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://isthereanydeal.com/game/pikuniku/info/
https://isthereanydeal.com/game/hotline-miami-2-wrong-number/info/
https://isthereanydeal.com/game/hotline-miami/info/
```

### Description

When clicking on any game that goes to GOG store on IsThereAnyDeal, the tab that is suppose to go to GOG just open for a second then closes, but if i copy the link and enter it in another tab , I can get the normal strict blocking page. After some investigation it seems like Easylist is blocking the tab that I clicked open as popup. After applying the following filter , the issue does not persist. `@@||track.adtraction.com^$popup,domain=isthereanydeal.com
`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1680" alt="the logger" src="https://github.com/uBlockOrigin/uAssets/assets/74965584/99d2d830-8e1d-48bc-b63a-54b8b7508036">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 129
filterset (summary):
 network: 155091
 cosmetic: 102429
 scriptlet: 25193
 html: 1842
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 67326-16361, 7d.2h.31m
  ublock-cookies-easylist: 1214-3, 1h.59m
  CHN-0: 26293-197, 1d.19h.11m
 default:
  user-filters: 37-0, never
  ublock-filters: 38683-112, 4h.59m Δ
  ublock-badware: 9237-0, 4h.59m Δ
  ublock-privacy: 922-2, 4h.59m Δ
  ublock-unbreak: 2399-2, 4h.59m Δ
  ublock-quick-fixes: 82-3, 4h.59m Δ
  easylist: 86938-178, 4h.59m Δ
  easyprivacy: 51060-64, 4h.59m Δ
  urlhaus-1: 14875-0, 2h.59m
  plowe-0: 3555-989, 7d.2h.31m
filterset (user): [array of 37 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 113 ms (selfie)
 maxAssetCacheWait: 65 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  adtraction.com: 1
  sentry.io: 6
  twitch.tv: 1

```
</details>

**Comment by stephenhawk8054** [comment]
Do you know if there's any domain besides `gog.com`? If not, I'll add this filter instead

```adb
@@||track.adtraction.com/*www.gog.com$popup,domain=isthereanydeal.com
```

**Comment by My-life-is-over** [comment]
As far as i know only the link that goes to GOG have this problem , but i don't experience it with other link, probably because only GOG use adtraction.
