### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by alienkeep** [uBlockOrigin/uAssets#24152]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://e.mail.ru/inbox/`

### Category

ads

### Description

shows empty blocks on the top and right side of page

### Other extensions used

Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок](https://github.com/uBlockOrigin/uAssets/assets/173164683/55d1e5b2-d507-42c8-b92f-126599c3459a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 161156
 cosmetic: 137240
 scriptlet: 32908
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1702-5, 7m
  adguard-cookies: 30091-55, now
  ublock-cookies-adguard: 1214-0, now
  fanboy-cookiemonster: 51216-3957, now
  ublock-cookies-easylist: 1214-1214, now
  ublock-annoyances: 5921-34, 7m
 default:
  user-filters: 3-0, never
  ublock-filters: 38577-376, 11m
  ublock-badware: 9235-16, 11m
  ublock-privacy: 931-10, 11m
  ublock-unbreak: 2340-19, 11m
  ublock-quick-fixes: 82-1, 11m
  easylist: 86940-44, now
  easyprivacy: 51061-248, now
  urlhaus-1: 15230-0, now
  plowe-0: 3552-989, now
  RUS-0: 39302-175, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 324 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  mail.ru: 14
 extended:
  ###app-canvas .paginator-container:style(right: 8px !important)
  ##+js(href-sanitizer, [data-cke-saved-href^="https://checklink.m…
  ##+js(set-constant, Object.prototype.onLinkClick, noopFunc)
  ##+js(set-constant, Object.prototype.onLinkMouseDown, noopFunc)
  ##+js(json-prune, [].slot)
  ##+js(no-setTimeout-if, slot:fail)
  ##+js(no-setTimeout-if, NO_MIMIC_ON_)
  ##+js(set-constant, Object.prototype.hasAdBlockWhiteList, false)
  #@#+js(prevent-fetch, /\/res\//)
  #@#+js(set-constant, Object.prototype.mimic, undefined)
  #@#+js(set-constant, document.title, null)
  #@#+js(set-constant, mr._mimic.locator.transform, undefined)
  #@#+js(abort-on-stack-trace, Object.prototype.ssrAds, completeRa…
```
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/a02f3d77fe171d15c12b14b6e639cae61a663a85

**Comment by MartaWild** [comment]
This fix does nothing for me.

```
e.mail.ru,octavius.mail.ru##+js(set-constant, Object.prototype.hasAdBlock, null)
e.mail.ru,octavius.mail.ru##body > div > .letter-list-item-adv:style(display: block !important)

! 2024-05-22 https://e.mail.ru
||r.mradx.net/img/29/3439A2.png$image
e.mail.ru##.R6XQhEo_R6XQhEx.R6XQhEo_R6XQhEE.R6XQhEo
e.mail.ru##.R6XQhxe_R6XQhxp.R6XQhxe_R6XQhxG.R6XQhxe

! 2024-05-23 https://e.mail.ru
e.mail.ru##.jplwo6O_jplwo6v.jplwo6O_jplwo66.jplwo6O
e.mail.ru##.jplwovb
e.mail.ru##.jplwovN_jplwov7.jplwovN_jplwov0.jplwovN
e.mail.ru##.r5dq0bc_r5dq0bx.r5dq0bc_r5dq0bb.r5dq0bc

! May 25, 2024 https://e.mail.ru
e.mail.ru##.background-0-2-10
e.mail.ru###octavius-popup-cloud-subscribe > div
e.mail.ru###octavius-popup-cloud-subscribe
e.mail.ru##.XIChVJN_XIChVJO.XIChVJN_XIChVJJ.XIChVJN
```
![image](https://github.com/uBlockOrigin/uAssets/assets/47245850/5e064c15-fe59-4205-81ce-d65005dd31f9)

**Comment by alienkeep** [comment]
just update each uBlock filter manually. it helped me.

**Comment by dimisa-RUAdList** [comment]
@MartaWild 
Enable RU AdList in the dashboard (Filter lists -> scroll down to Regions, languages).

**Comment by MartaWild** [comment]
That helped. Thanks!
