### ISSUE TITLE
Sponsorships are not Ads

### ISSUE THREAD

**Issue by Rebel459** [uBlockOrigin/uAssets#24164]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://modrinth.com/
```

### Description

_I know the path of action around here thus far seems to be immediately closing down complaints, even if the discussion is largely one-sided against the decisions that have been made, but at least consider hearing me out before you do the same here._

The recent decision to block sponsor links to 3 particular server hosts on 1 particular website feels extremely targeted, inconsistent, and arguably against uBlock’s own default purposes. uBlock has been historically known for blocking content such as ads and trackers. Take YouTube, for example - uBlock blocks all ads, but it does _not_ block sponsors, regardless how egregious those sponsor segments may be. That functionality is reserved for other extensions such as SponsorSkip, which serves a completely different function to uBlock.

However, the recent decision targets and hurts already-well-underpaid mod authors on only one specific site, with 3 specific server hosts. This decision is both extremely targeted, unfair when accounting for the myriad of other sites and hosts out there, and against uBlock’s own goals. You’re not going to block sponsors on websites… except you’ll block the most ethical implementation (a literal link in a png) _for 3 specific websites_. This decision lacks consistency with both uBlock’s past decisions and with the range of websites it has arbitrarily chosen to affect.

I greatly respect uBlock, and the time put forward by its contributors, to provide a safer, faster and cleaner internet, all for free, with no strings attached. These actions are commendable, but this it not it. You are targeting an extremely particular minority of “sponsors” which goes against both fairness and uBlock’s advertised goals, in the one place where little to no people have a problem with it - and when you receive universal backlash to these arguably discriminatory actions as well as feedback on how to proceed, you shortly shut down any requests or issues without addressing feedback or leaving room for further discussion. These weren’t “heated discussions” that needed to be closed down - the majority of ublock users affected by this change are quite simply against it.

I know I, as one person, cannot change anything, especially with these decisions being made, but I can at least ask. Ask you to go back on this decision, ask you to hear others out. Ask you to be consistent with uBlock’s own goals, and ask you for clarity in this seemingly targeted decision. I know this is a long post, and whether you chose to close it down and ignore it like the rest, I would still like to thank you for your time reading this.

Please reconsider.

### Other extensions used

none

### Screenshot(s)

NA

### Configuration

NA

**Comment by sylv256** [comment]
These *are* heated discussions, and you need to stop spamming the issue tracker with them. I do not speak for the uBlock administrators, but it is not for you to decide these things. Disable uBlock Origin; stop using it; disable cosmetic filtering, but don't come crying when an adblocker blocks ads as was intended.

**Comment by ave9858** [comment]
Please check the [easylist policy](https://easylist.to/pages/policy.html), which the uAssets policy is based on. Affiliate links/images/widgets count as content that should be blocked.

**Comment by stephenhawk8054** [comment]
[uAssets follow EasyList's policy](https://github.com/uBlockOrigin/uAssets#uassets), including `Affiliate images` that lead to 3rd-party sites not owned or operated by the websites themselves when users click on them. We will only re-consider when there are:

1. Noticeable performance issue backed by actual profiling data from the [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/),
2. Potentially many false positives / breakages,

caused by the filters. EasyList used to hide sponsored links in YouTube's descriptions until there were reports of performance issue, due to the nature of its big dynamic site, that we had to remove the filters.

**Comment by uBlock-user** [comment]
That is your opinion and nothing more than that. uBO follows its policy and will continue to do so. Repeatedly opening and issue or a discussion about this will result in a ban. Accept the decision and beg your visitors to disable blockers. This is the only thing you can do.
