### ISSUE TITLE
comicxy.com: detection

### ISSUE THREAD

**Issue by shadeless2455** [uBlockOrigin/uAssets#24163]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://comicxy.com/`

### Category

detection

### Description

Website stops function as the adblock is detected

### Other extensions used

NordVPN (Not active to replicate issue)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 138519
 cosmetic: 46611
 scriptlet: 21219
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 38620-375, 8m
  ublock-badware: 9235-0, 8m
  ublock-privacy: 931-0, 8m
  ublock-unbreak: 2340-0, 8m
  ublock-quick-fixes: 82-0, 8m
  easylist: 86973-467, 8m
  easyprivacy: 51061-638, 8m
  urlhaus-1: 15185-0, 8m
  plowe-0: 3552-0, 8m
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1051 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 191
 network:
  2mdn.net: 32
  acuityplatform.com: 4
  adform.net: 4
  doubleclick.net: 24
  fonts.googleapis.com: 1
  google-analytics.com: 1
  google.com: 16
  googleadservices.com: 10
  googlesyndication.com: 83
  googletagmanager.com: 1
  googletagservices.com: 7
  onesignal.com: 1
  simpli.fi: 2
  tribalfusion.com: 4
  trustarc.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##.adsbygoogle-noablate
  ###teaser3
  ###ad_unit
  ###abgc
  ##.jar
  ##+js(set-constant, rwt, noopFunc)
  #@#div[id^="ad_position_"]
```
</details>

**Comment by huyszn** [comment]
Test in a new browser profile with only uBO with default settings.
