### ISSUE TITLE
biqugen.net: ads

### ISSUE THREAD

**Issue by China-MYJSY** [uBlockOrigin/uAssets#24169]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://m.biqugen.net/book/104535/58870069.html`

### Category

ads

### Description

no

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium Mobile: 125
filterset (summary):
 network: 154923
 cosmetic: 65602
 scriptlet: 21563
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39063-349, 1h.49m Δ
  ublock-badware: 9134-0, 1h.49m Δ
  ublock-privacy: 932-0, 1h.49m Δ
  ublock-unbreak: 2345-0, 1h.49m Δ
  ublock-quick-fixes: 82-0, 1h.49m Δ
  adguard-mobile: 9504-97, 1d.29m
  easylist: 86983-657, 1h.49m Δ
  easyprivacy: 51064-645, 1h.49m Δ
  urlhaus-1: 15185-0, now
  plowe-0: 3552-0, 1d.29m
  CHN-0: 26311-164, 1d.29m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 555 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  baidu.com: 2
```
</details>

**Comment by China-MYJSY** [comment]
> which browser are you using? try on firefox mobile browser

edge mobile browser

**Comment by China-MYJSY** [comment]
![Screenshot_2024-06-19-23-29-04-37_df198e732186825c8df26e3c5a10d7cd](https://github.com/uBlockOrigin/uAssets/assets/94955855/03d38585-6e2a-4047-99ab-79e979a42baf)
look

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/6c46192980ca232a14f3ef3b6417a1de63fb334c

**Comment by China-MYJSY** [comment]
> [easylist/easylistchina@6c46192](https://github.com/easylist/easylistchina/commit/6c46192980ca232a14f3ef3b6417a1de63fb334c)

你这规则真棒

**Comment by China-MYJSY** [comment]
> test `*$image,3p,domain=biqugen.net`
> 
> @cjx82630 can you see?

It works, but there's still a transparent ad on the page that covers the entire screen. Whenever you click anywhere on the page, it redirects to an advertisement website.

![73aae553a64c9da71b2267a26e03c2c](https://github.com/uBlockOrigin/uAssets/assets/94955855/5021f22f-331b-4f03-946b-fc8be5695255)
