### ISSUE TITLE
azmath.info: detection

### ISSUE THREAD

**Issue by dreminh** [uBlockOrigin/uAssets#24168]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

keep saying am using addblock 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/23002308/83034106-a5ad-407d-a41a-63df11dcd5b7)

### A specific URL where the issue occurs.

```yaml
https://azmath.info/
```

### Steps to Reproduce

just click on link that lead to https://azmath.info/ 

### Expected behavior

wait for the link 

### Actual behavior

spam addblock and new tab add poker game 

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 138477
 cosmetic: 46611
 scriptlet: 21221
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86976-568, 1h.26m Δ
  easyprivacy: 51063-2, 1h.26m Δ
  plowe-0: 3555-615, 9d.17h.8m
  ublock-badware: 9140-0, 1h.26m Δ
  ublock-filters: 38625-275, 1h.26m Δ
  ublock-privacy: 931-3, 1h.26m Δ
  ublock-quick-fixes: 82-0, 1h.26m Δ
  ublock-unbreak: 2342-18, 1h.26m Δ
  urlhaus-1: 15230-0, 21h.4m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 304 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
```
</details>

**Comment by JobcenterTycoon** [comment]
But all the annoyances they run after detection (anti right click, short cuts) are still here.

**Comment by JobcenterTycoon** [comment]
`azmath.info##+js(aeld, DOMContentLoaded, document.documentElement.lang.toLowerCase)` works for me
