### ISSUE TITLE
cuevana3.com [Pop-up] [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2416]
URL(s) where the issue occurs

`http://www.cuevana3.com/4881/ver-the-shadow-effect-online`

Describe the issue

![](https://i.imgur.com/zx1cpMh.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.8

Settings

Default

**Comment by KiLL4FuNK** [comment]
Pop-up Fake Button

`https://www.cuevana3.co/4881/the-shadow-effect`

**Comment by lain566** [comment]
There's a popup on chrome.
And the video player is broken.

`https://www.cuevana3.co/8634/creed-ii-54wci`

**Comment by mapx-** [comment]
could you test
```
||cuevana3.*/*.php$subdocument,badfilter
cuevana3.*##+js(window.open-defuser.js)
```

and do you see those fake buttons ? (after removing the php filter)

**Comment by mapx-** [comment]
oh, @okiehsch was faster

**Comment by lain566** [comment]
It's still broken for me. 
I really do not see any fake button if I add `||cuevana3.*/*.php$subdocument,badfilter`

![87c4fa92-daac-4ef8-8b65-5036fc16efbb](https://user-images.githubusercontent.com/27441315/53727345-4700ba00-3e70-11e9-995f-babeb1e14cf9.png)

**Comment by mapx-** [comment]
still broken adding my filters ?

**Comment by lain566** [comment]
This filter is still breaking the player
`||cuevana3.*/*.php$subdocument`

**Comment by mapx-** [comment]
ok, removed, test now

**Comment by lain566** [comment]
This filter is blocking the share buttons, just that
`cuevana3.*##+js(window.open-defuser.js)`
okiehsch had already fixed the popups

**Comment by mapx-** [comment]
removed
