### ISSUE TITLE
datanodes.to: ads

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#24166]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://datanodes.to/download`

### Category

ads

### Description

Apprently [ I have reported this before](https://github.com/uBlockOrigin/uAssets/issues/23848) however they manage to make the popup back again, I guess they will do this periodically by changing the redirect ad popup url.
this time it redirects to:
https://dhux7ijh.click/

### Other extensions used

Mostly nothing changes the site

- Violentmonkey
- Cookie Editor
- Downthemall
- Sponsorblock

I dont have to count more since its not related to breakage.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 125
filterset (summary):
 network: 163722
 cosmetic: 127328
 scriptlet: 30269
 html: 2121
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51217-185, 1m
  ublock-cookies-easylist: 1214-3, 1m
  easylist-annoyances: 4670-51, 1m
  easylist-chat: 197-0, 1m
  easylist-newsletters: 7542-20, 1m
  easylist-notifications: 3025-164, 1m
  ublock-annoyances: 5868-84, 2m Δ
  RUS-0: 39339-195, 2m Δ
 default:
  user-filters: 63-3, never
  ublock-filters: 38732-112, 2m Δ
  ublock-badware: 9237-0, 2m Δ
  ublock-privacy: 922-2, 2m Δ
  ublock-unbreak: 2399-2, 2m Δ
  ublock-quick-fixes: 82-3, 2m Δ
  easylist: 86976-179, 2m Δ
  adguard-spyware-url: 1538-120, 1m
  easyprivacy: 51063-64, 2m Δ
  urlhaus-1: 15185-0, 2m
  curben-phishing: 467-2, 2m
  plowe-0: 3552-988, 1m
  LegitimateURLShortener: 2653-160, 1m
filterset (user): [array of 63 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 532 ms (selfie)
 maxAssetCacheWait: 203 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  scarcerpokomoo.com: 2
 extended:
  ##.grecaptcha-badge
  ##.grecaptcha-badge[data-style]
  ##+js(remove-attr, disabled, .downloadbtn)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue commenting in the old thread. All volunteers are notified with new comments. No need to open duplicated issue.
