### ISSUE TITLE
wetransfer.com: nuisance

### ISSUE THREAD

**Issue by zbrsssss** [uBlockOrigin/uAssets#24175]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wetransfer.com/downloads/e09ea743934f15dd975ae8514d1fa88220240619064121/e8c7a0`

### Category

breakage

### Description

Website does not fuction without the cookie notice being accepted (shown in image below)
![image](https://github.com/uBlockOrigin/uAssets/assets/83305468/405c371b-92af-4e55-909d-7429985515e5)
This service previously let users download files without agreeing to the the usage of cookies

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 138278
 cosmetic: 46550
 scriptlet: 19811
 html: 1843
listset (total-discarded, last-updated):
 default:
  user-filters: 13-0, never
  ublock-filters: 38745-112, 1h.47m Δ
  ublock-badware: 9142-0, 1h.47m Δ
  ublock-privacy: 922-2, 1h.47m Δ
  ublock-unbreak: 2401-2, 1h.47m Δ
  ublock-quick-fixes: 83-3, 1h.47m Δ
  easylist: 87003-179, 1h.47m Δ
  easyprivacy: 51064-64, 1h.47m Δ
  urlhaus-1: 15060-0, now
  plowe-0: 3552-988, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 572 ms (selfie)
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  wetransfer.com: 4
  ethyca.com: 1
  googlesyndication.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Enable uBlock filters – Cookie Notices list.
