### ISSUE TITLE
modrinth.com: ads (bit.ly bypass)

### ISSUE THREAD

**Issue by sylv256** [uBlockOrigin/uAssets#24174]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://modrinth.com/mod/not-enough-animations`

### Category

ads

### Description

The creator of this mod decided to bypass the detection using a `bit.ly` link instead. AFAIK uBlock Origin goes through link shorteners, so I assume all that would need done is adding Shockbyte to the list. Also, there is now a message below with a link to the `bit.ly` URL.

### Other extensions used

- Bitwarden Password Manager
- Dark Mode
- DeArrow
- FastForward
- Indie Wiki Buddy
- Jazz-Midi
- JPEG XL Viewer
- Open Same Tab
- Override Text Encoding
- Plasma Integration
- Ruffle - Flash Emulator
- Shinigami Eyes
- Simple Tab Groups
- SimpleLogin:Receive & Send emails anonymously
- SoundFixer
- SponsorBlock for YouTube - Skip Sponsorships 5.6.1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/18603248/9456cf82-ed89-4004-8bfd-d2190e6d67b4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 138335
 cosmetic: 46480
 scriptlet: 19781
 html: 1842
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38683-112, now
  ublock-badware: 9237-0, now
  ublock-privacy: 922-2, now
  ublock-unbreak: 2401-2, now
  ublock-quick-fixes: 83-3, now
  easylist: 86938-178, now
  easyprivacy: 51064-64, now
  urlhaus-1: 15060-0, now
  plowe-0: 3552-988, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2047 ms
 maxAssetCacheWait: 21 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.GBBNWLJVGRHFLYVGSZKSSKNTHFYXHMBD
  ##a[rel*="sponsored"]:upward(.normal-page__content > div)
```
</details>

**Comment by sylv256** [comment]
I opened a new issue because the previous one is locked, and I wanted to make y'all aware that they're using `bit.ly` now.

**Comment by ferriarnus** [comment]
And we will keep doing it... This is user content, not some google add in your face.

**Comment by MundM2007** [comment]
Exactly, we will use github.io and other stuff to Bypass this, it's Not Like you can  completely ban that

**Comment by sylv256** [comment]
I fumbled up some filters for myself.
```adblock
modrinth.com##section.normal-page__content [href^="://bit.ly/"] > img
modrinth.com##section.normal-page__content > :xpath(//.[a[contains(@href,"://bit.ly")]])
```
Please go ahead and improve upon it if you can.

**Comment by ferriarnus** [comment]
This is a shotgun approach that will hit much more then just this one project with one add.

**Comment by MundM2007** [comment]
Adding a laugh emoji everywere won't help this xd

**Comment by Artaeth** [comment]
To have a problem with literally a small bit of text in the bottom right and below the banner is ridiculous

**Comment by sylv256** [comment]
Hey y'all, stop spamming the issue tracker. If you have nothing constructive to say, don't say it. This is an adblocker; it blocks ads. If you have a problem with it, you can [disable cosmetic filtering yourself](https://gist.github.com/sylv256/428f525c3a45f46d77c9b422c68d4e23). Otherwise, stop raiding the issue tracker.

**Comment by MundM2007** [comment]
You are raiding the issue tracker making new issues with lots more to come xd

**Comment by phase** [comment]
bit.ly is not for advertisements, it's an arbitrary link shortener. This will surely break non-ad content.

**Comment by sylv256** [comment]
> bit.ly is not for advertisements, it's an arbitrary link shortener. This will surely break non-ad content.

The filter I made for myself is a temporary measure. Hopefully we can block specifically sponsored `bit.ly` links.

**Comment by uBlock-user** [comment]
> I opened a new issue because the previous one is locked, and I wanted to make y'all aware that they're using bit.ly now.

Re-opened the issue, will be deleting spammers there now. Post there.
