### ISSUE TITLE
launcherleaks.net: cannot scroll after loading the page

### ISSUE THREAD

**Issue by DeadLector** [uBlockOrigin/uAssets#24179]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://launcherleaks.net/`

### Category

breakage

### Description

Unable to scroll on the website, but can click to sub-pages of the website.

### Other extensions used

DuckDuckGo, 1Password, Coupert, Bypass Paywalls Clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 333197
 cosmetic: 125903
 scriptlet: 31432
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 421-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 760-8, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 95223-2353, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2653-75, 22m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 79813-9624, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 294-0, now
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/antimalware.txt: 44184-1160, now
  https://raw.githubusercontent.com/iam-py-test/uBlock-combo/main/list.txt: 120308-118824, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2108-95, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1174-5, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/block_third_party_fonts.txt: 77-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 104-0, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 17-1, never
  easylist: 87003-22587, 22m Δ
  easyprivacy: 51064-764, 22m Δ
  plowe-0: 3552-6, now
  ublock-badware: 9140-0, 22m Δ
  ublock-filters: 38646-532, 22m Δ
  ublock-privacy: 931-126, 22m Δ
  ublock-quick-fixes: 83-0, 22m Δ
  ublock-unbreak: 2342-7, 22m Δ
  urlhaus-1: 15060-0, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 462 ms (selfie)
 maxAssetCacheWait: 242 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  fonts.googleapis.com: 1
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##.ads_container:not(.text-ad)
  ##.swal2-show.swal2-icon-info.swal2-modal.swal2-popup
  ##.swal2-backdrop-show.swal2-center.swal2-container
```
</details>

**Comment by huyszn** [comment]
The site gave me a detection message. One of your added lists probably hid the detection message.
