### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by LeHman93** [uBlockOrigin/uAssets#24188]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kimcartoon.li/Cartoon/Smiling-Friends-Season-2/Episode-7?id=117747&s=hx`

### Category

detection

### Description

Initialy nothing happens but a few seconds after the video loads, it pops up the error please disable ablock

### Other extensions used

Hoxx VPN(not activated)
Meta Mask
KellyC Show Youtube Dislikes
Lightshot
I dont care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 117
filterset (summary):
 network: 137881
 cosmetic: 46554
 scriptlet: 19815
 html: 1844
listset (total-discarded, last-updated):
 added:
  https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 0-0, never
  ublock-quick-fixes: 84-4, 10m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 38764-112, 10m Δ
  ublock-badware: 9097-0, 10m Δ
  ublock-privacy: 924-2, 10m Δ
  ublock-unbreak: 2403-2, 10m Δ
  easylist: 87042-178, 10m Δ
  easyprivacy: 51077-64, 10m Δ
  plowe-0: 3552-989, now
  urlhaus-1: 14655-0, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6473 ms
 maxAssetCacheWait: 407 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  abysscdn.com: 1
  adskeeper.co.uk: 1
  bidgear.com: 1
  ceegriwuwoa.net: 1
  cloudflare.com: 1
  feedyourtralala.com: 3
  google-analytics.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  idocdn.com: 5
  oaphoace.net: 1
  pk910324e.com: 1
  sharethis.com: 1
 extended:
  ##.kcAds1
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
```
</details>

**Comment by LeHman93** [comment]
Also if relevant i did try disabling I dont care about cookies, didnt change anything

**Comment by FunWithMyHole** [comment]
Why is this closed? i have the same issue

**Comment by stephenhawk8054** [comment]
It's fixed in this commit: https://github.com/uBlockOrigin/uAssets/commit/86c2bdeb7e188bd0ed3b5420bd4343272959ab28

The filter lists will auto update to you in a few hours

**Comment by LeHman93** [comment]
Thanks

**Comment by tsteele1126** [comment]
still not working

**Comment by Yuki2718** [comment]
Working fine on my end.

**Comment by tsteele1126** [comment]
well i get nothing

**Comment by Yuki2718** [comment]
Fixed, but as the site owner is watching us, nothing will work for more than a day.
