### ISSUE TITLE
mangakatana.com: ads

### ISSUE THREAD

**Issue by JDinKorea** [uBlockOrigin/uAssets#24184]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mangakatana.com/manga/please-go-home-akutsu-san.24297/c177`

### Category

ads

### Description

Ads in multiple locations

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/173324489/2542df6f-5aa9-4799-ac6a-7697cccce38a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 137921
 cosmetic: 46655
 scriptlet: 21235
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 9-0, never
  easylist: 87013-44, now
  easyprivacy: 51067-17, now
  plowe-0: 3552-988, now
  ublock-badware: 9140-16, now
  ublock-filters: 38649-375, now
  ublock-privacy: 931-6, now
  ublock-quick-fixes: 84-1, now
  ublock-unbreak: 2344-33, now
  urlhaus-1: 14655-0, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 125 ms (selfie)
 maxAssetCacheWait: 24 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 65
 network:
  4dex.io: 5
  a-ads.com: 2
  a-mo.net: 8
  a-mx.com: 1
  adform.net: 1
  adnxs.com: 2
  adskeeper.co.uk: 1
  adskeeper.com: 6
  amazon-adsystem.com: 1
  bidgear.com: 2
  bidswitch.net: 3
  casalemedia.com: 2
  creativecdn.com: 1
  e-planning.net: 1
  google-analytics.com: 5
  googletagmanager.com: 2
  id5-sync.com: 2
  iqm.com: 1
  lijit.com: 1
  mgid.com: 1
  onetag-sys.com: 1
  openx.net: 2
  prplads.com: 1
  pubmatic.com: 2
  purpleads.io: 7
  script.ac: 1
  smartadserver.com: 1
  wp.com: 2
 extended:
  ##.ad-content-wrapper
  ##HTML
  ##.size300x250
  ##a[href^="https://a-ads.com/"]
```
</details>

**Comment by huyszn** [comment]
> ### Other extensions used
> none

You have other extensions enabled in your screenshot. Test again in a new browser profile with only uBO with default settings and no other extensions enabled.
