### ISSUE TITLE
Dangerous fake KMS activation websites

### ISSUE THREAD

**Issue by PhoenixFossGR** [uBlockOrigin/uAssets#24189]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
kms-full.com
kmspico.ws
kmspico.io
```

### Description

These websites deceives users into downloading malware by making them believe they are installing a legitimate Windows activator.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
Most files are detected as a "HackTool" on virustotal.

**Comment by MIOGMIOG** [comment]
(This comment will be talking primarly about KMSpico, but it applies to 99% of other windows/office "activators")
Hello, this is kinda like fitgirl repacks situation, where there are many fake websites pretending to be the original. (but KMSpico doesn’t have any website in the first place, the original is a forum post from 2013 on Mydigitallife forums),
so I suggest adding wildcard filters, I have made these filters that can be added to Badware risks filter (not just for kmspico, but for other fake activator websites, also I would suggest moving already added fake activators domains here too to their cathegories, also feel free to remove dead domains):
```
! KMSpico - Official site: https://forums.mydigitallife.net/threads/abandoned-kmspico-official-thread.65739/
||kmspico.*^$all,domain=~forums.mydigitallife.net
||kmspicoofficial.*^$all,domain=~forums.mydigitallife.net
||kmspico-official.*^$all,domain=~forums.mydigitallife.net
||official-kmspico.*^$all,domain=~forums.mydigitallife.net
||officialkmspico.*^$all,domain=~forums.mydigitallife.net
||oficial-kmspico.*^$all,domain=~forums.mydigitallife.net
||kmspico-activator.*^$all,domain=~forums.mydigitallife.net
||activator-kmspico.*^$all,domain=~forums.mydigitallife.net
||getkmspico.*^$all,domain=~forums.mydigitallife.net
||get-kmspico.*^$all,domain=~forums.mydigitallife.net
||kmspico10.*^$all,domain=~forums.mydigitallife.net
||activator-kmspico.net^$all,domain=~forums.mydigitallife.net
||ativadorkmspico.com^$all,domain=~forums.mydigitallife.net
||get-kmspico.com^$all,domain=~forums.mydigitallife.net
||getkmspico.com^$all,domain=~forums.mydigitallife.net
||kmspico-activator-crack.com^$all,domain=~forums.mydigitallife.net
||kmspico-activator-free.com^$all,domain=~forums.mydigitallife.net
||kmspico-activator.in^$all,domain=~forums.mydigitallife.net
||kmspico-mafia.com^$all,domain=~forums.mydigitallife.net
||kmspico-official.xyz^$all,domain=~forums.mydigitallife.net
||kmspico-oficial.com^$all,domain=~forums.mydigitallife.net
||kmspico-software.net^$all,domain=~forums.mydigitallife.net
||kmspico-tools2.site^$all,domain=~forums.mydigitallife.net
||kmspico.co^$all,domain=~forums.mydigitallife.net
||kmspico.icu^$all,domain=~forums.mydigitallife.net
||kmspico.io^$all,domain=~forums.mydigitallife.net
||kmspico.space^$all,domain=~forums.mydigitallife.net
||kmspico.uno^$all,domain=~forums.mydigitallife.net
||kmspico.ws^$all,domain=~forums.mydigitallife.net
||kmspico10.com^$all,domain=~forums.mydigitallife.net
||kmspicoactivator.net^$all,domain=~forums.mydigitallife.net
||kmspicoativador.org^$all,domain=~forums.mydigitallife.net
||kmspicodownloads.com^$all,domain=~forums.mydigitallife.net
||kmspicofficial.com^$all,domain=~forums.mydigitallife.net
||kmspicoofficial.com^$all,domain=~forums.mydigitallife.net
||kmspicoportable.com^$all,domain=~forums.mydigitallife.net
||mrkmspico.com^$all,domain=~forums.mydigitallife.net
||official-kmspico.co^$all,domain=~forums.mydigitallife.net
||official-kmspico.com^$all,domain=~forums.mydigitallife.net
||official-kmspico.org^$all,domain=~forums.mydigitallife.net
||officialkmspico.com^$all,domain=~forums.mydigitallife.net
||officialkmspico.download^$all,domain=~forums.mydigitallife.net
||officialkmspico.net^$all,domain=~forums.mydigitallife.net
||officials-kmspico.com^$all,domain=~forums.mydigitallife.net
||oficial-kmspico.com^$all,domain=~forums.mydigitallife.net
! Microsoft Activation Scripts - Official site: massgrave.dev
||massgrav.*^$all,domain=~massgrave.dev
||massgrave.*^$all,domain=~massgrave.dev
||massgraves.*^$all,domain=~massgrave.dev
! Windows loader by Daz - Official site: https://forums.mydigitallife.net/forums/windows-loader.39/
||dazactivator.*^$all,domain=~forums.mydigitallife.net
||dazloaderteam.*^$all,domain=~forums.mydigitallife.net
||winloader.*^$all,domain=~forums.mydigitallife.net
||dazactivator.com^$all,domain=~forums.mydigitallife.net
||dazloaderteam.com^$all,domain=~forums.mydigitallife.net
||winloader.io^$all,domain=~forums.mydigitallife.net
||winloader.org^$all,domain=~forums.mydigitallife.net
||windows-7-activator.com^$all,domain=~forums.mydigitallife.net
```
(there is also malwarebytes blog post about fake kmspico websites if someone is interested I guess: <https://www.threatdown.com/blog/kmspico-explained-no-kms-is-not-kill-microsoft/>)
