### ISSUE TITLE
getkmspico.com: Badware

### ISSUE THREAD

**Issue by PhoenixFossGR** [uBlockOrigin/uAssets#24187]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
http://getkmspico.com/
```

### Description

This website is a total nightmare. It is filled with malicious and phishing ads and pop-ups. Clicking anywhere results in a random malicious website appearing. I recommend blocking this domain entirely, as there are multiple associated malicious domains. Something might slip past uBO, potentially leading to users being scammed or worse.

Here are a few of the many malicious/phishing/adware domains it connects to:
```
download.artificusbrowser.com
poperblocker.com
ak.itponytaa.com
ad.install-adblockers.com
veepteero.com
rnofor4ht.top
ads.download-adblockers.com
file.fan
file.fan/38131da0f904a05
baldappetizingun.com
tracking.trackingrouter.com
app-rush.com
ak.oneegrou.net
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the popup despite clicking many places on the page.

**Comment by JobcenterTycoon** [comment]
https://www.virustotal.com/gui/file/67547d29f8cb79697566a4446c617ffca59dc0bdc982afbf64cd7de189999098?nocache=1

Most AV vendors flagging the download as a "HackTool", "Crack" or "AutoKMS" so its not malware. Same for the download on many sites you reported in https://github.com/uBlockOrigin/uAssets/issues/24193

"I get popups with uBO off" is not a reason to hard block a site. When we would start to block sites with this reason we would block the half internet...

**Comment by JobcenterTycoon** [comment]
<img width="551" alt="pic" src="https://github.com/uBlockOrigin/uAssets/assets/48647394/76509697-670d-4032-9564-57b9d4fe1244">

**Comment by JobcenterTycoon** [comment]
`kms-full.com` got added 10 hours ago already https://github.com/uBlockOrigin/uAssets/commit/5dc64eed2e6876a9e9e34ba290522614c4a0f128
