### ISSUE TITLE
arto.dk: ads

### ISSUE THREAD

**Issue by eaxiumnet** [uBlockOrigin/uAssets#24180]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.arto.dk/`

### Category

ads

### Description

This appears.

	<div xonclick="window.open('https://www.hokuskrokus.dk/');">
	
		<div style="display: inline-block;">
			<a target="_blank" href="https://www.hokuskrokus.dk/foderbraetter/wildlife-garden-foderlade-roed-174"><img src="gfx/1.jpg"></a>
			<a target="_blank" href="https://www.hokuskrokus.dk/foderbraetter/wildlife-world-foderbraet-vindue-1474"><img src="gfx/2.jpg"></a>
			<a target="_blank" href="https://www.hokuskrokus.dk/fuglebade/wildlife-world-fuglebad-keramik-1012"><img src="gfx/3.jpg"></a>
			<a target="_blank" href="https://www.hokuskrokus.dk/egern-pindsvin/wildlife-world-pindsvinehus-1029"><img src="gfx/4.jpg"></a>
			<a target="_blank" href="https://www.hokuskrokus.dk/insekter/wildlife-world-vildbi-hus-1638"><img src="gfx/5.jpg"></a>
		</div>
	
		<div style="display: inline-block; width: 200px; padding-top: 18px; padding-right: 18px; float: right;">
			<div style="text-align: center;">
			<a href="https://www.hokuskrokus.dk/" target="_blank">
				<img src="gfx/logo.png" style="width: 200px; height: auto; border: 0px; border-radius: 0px;">
				Unikt udvalg til have og bolig
				</a>
			</div>
		</div>

	</div>
	

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80918589/062aa8c8-71e5-436c-9395-68e73b42d34e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 222078
 cosmetic: 255960
 scriptlet: 51783
 html: 2106
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81530-494, now
  adguard-mobile: 9506-58, now
  adguard-spyware-url: 1539-120, now
  adguard-spyware: 68707-1514, now
  block-lan: 68-0, now
  curben-phishing: 514-0, now
  adguard-social: 23294-55, now
  adguard-cookies: 30094-47, now
  ublock-cookies-adguard: 1217-14, now
  adguard-popup-overlays: 27221-1003, now
  adguard-mobile-app-banners: 5303-24, now
  adguard-other-annoyances: 14453-414, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38750-3437, 1h.33m Δ
  ublock-badware: 9142-106, 1h.33m Δ
  ublock-privacy: 922-2, 1h.33m Δ
  ublock-unbreak: 2401-74, 1h.33m Δ
  ublock-quick-fixes: 83-4, 1h.33m Δ
  easylist: 87003-2277, 1h.33m Δ
  easyprivacy: 51064-26892, 1h.33m Δ
  urlhaus-1: 15060-0, now
  plowe-0: 3552-1483, now
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 433 ms (selfie)
 maxAssetCacheWait: 124 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||artodata.net/site/ads/$subdocument
```

@DandelionSprout Sorry, can you check this?

**Comment by DandelionSprout** [comment]
Sure thing. Give me 15min.
