### ISSUE TITLE
nextplz.fr: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#24186]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nextplz.fr/telerealite/366304-maeva-ghennam-tacle-mariage-magali-berdah`

### Category

breakage

### Description

The site no longer displays images or videos

### Other extensions used

None that interfere with uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 177975
 cosmetic: 157128
 scriptlet: 29627
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1083-0, 17m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 17m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51239-12108, 17m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-6, 17m
  adguard-cookies: 30098-1653, 17m
  ublock-cookies-adguard: 1217-1217, 17m
  fanboy-cookiemonster: 51239-51239, 17m
  ublock-cookies-easylist: 1217-0, 17m
  RUS-0: 39301-261, 39m Δ
 default:
  user-filters: 1-0, never
  ublock-filters: 38659-108, 17m
  ublock-badware: 9095-0, 17m
  ublock-privacy: 933-0, 17m
  ublock-unbreak: 2344-2, 17m
  ublock-quick-fixes: 84-3, 45m Δ
  easylist: 87028-618, 17m
  easyprivacy: 51075-802, 17m
  urlhaus-1: 14655-0, 17m
  plowe-0: 3552-0, 17m
  FRA-0: 24679-379, 17m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 814 ms
 maxAssetCacheWait: 275 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  nextplz.fr: 1
  fastcmp.com: 1
  flashb.id: 1
  googletagmanager.com: 1
  mrf.io: 1
  opti-digital.com: 1
  outbrain.com: 1
  permutive.app: 1
  sparteo.com: 1
  taboola.com: 1
  viously.com: 7
  wonderpush.com: 1
 extended:
  ###dfp_inread
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||sonar.viously.com/*/js?$script,domain=nextplz.fr
```

@ryanbr
