### ISSUE TITLE
AdBlock Detection (spidergame.online)

### ISSUE THREAD

**Issue by fa1rid** [uBlockOrigin/uAssets#24195]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://spidergame.online/
```

### Description

AdBlock Detection

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/6115961/68caff40-8e50-4b6d-b4ac-b8e99f7e218a)

### Configuration

<details>
<summary>Details</summary>

```
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 137887
 cosmetic: 46554
 scriptlet: 19817
 html: 1844
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38765-112, 36m Δ
  ublock-badware: 9102-0, 36m Δ
  ublock-privacy: 924-2, 36m Δ
  ublock-unbreak: 2404-20, 36m Δ
  ublock-quick-fixes: 84-3, 36m Δ
  easylist: 87042-194, 36m Δ
  easyprivacy: 51078-31, 36m Δ
  urlhaus-1: 14655-0, 6h.8m
  plowe-0: 3552-989, 5d.2h.52m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 90 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  googlesyndication.com: 4
  googletagmanager.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder

```
</details>

**Comment by fa1rid** [comment]
Thanks man for the fast action. How much does it take to reflect in the browser?

I clicked update in the screen below but still not reflecting.

![image](https://github.com/uBlockOrigin/uAssets/assets/6115961/43d4dbbd-fc3f-483b-a4e4-609a96f4ab81)

**Comment by gorhill** [comment]
You should receive within ~6 hours.
