### ISSUE TITLE
rtalabel.org: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#24194]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rtalabel.org/`

### Category

ads

### Description

There is an input box on the page. Although it looks like a normal widget, it is an ad actually, I guess.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/35957435/889ccc27-9011-4810-810e-dce4647b5785

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 129
filterset (summary):
 network: 221343
 cosmetic: 233514
 scriptlet: 50915
 html: 2106
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81553-4001, 5m
  adguard-spyware-url: 1539-120, 5m
  adguard-spyware: 68710-1500, 5m
  curben-phishing: 507-0, 1m
  fanboy-cookiemonster: 51240-190, 5m
  ublock-cookies-easylist: 1217-3, 5m
  adguard-social: 23298-56, 5m
  fanboy-social: 16288-742, 5m
  fanboy-thirdparty_social: 68-19, 5m
  adguard-popup-overlays: 27224-1042, 5m
  adguard-mobile-app-banners: 5305-24, 5m
  adguard-other-annoyances: 14455-426, 5m
  [6 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 38765-112, 5m
  ublock-badware: 9102-0, 5m
  ublock-privacy: 924-2, 28m Δ
  ublock-unbreak: 2404-2, 5m
  ublock-quick-fixes: 84-3, 5m
  easylist: 87042-2216, 28m Δ
  easyprivacy: 51077-26885, 28m Δ
  urlhaus-1: 14950-0, 5m
  plowe-0: 3552-1082, 5m
  CHN-0: 26341-225, 5m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  cloudflareinsights.com: 2
  google-analytics.com: 2
  googletagmanager.com: 1
  ivisa.s3.amazonaws.com: 2
  paypal.com: 1
  statcounter.com: 2
 extended:
  ##.header-social
```
</details>

**Comment by ryanbr** [comment]
Looks legit? https://www.ivisa.com/widgets/visa-checker?utm_source=rtalabel&utm_medium=affiliate&background_color=v2-bg-blue-50&widget_width=340&widget_height=400

Unless its a fake/scam site? do comment.
