### ISSUE TITLE
pawread.com: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#24198]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pawread.com/`

### Category

nuisance

### Description

forced login after 20 reading 20 cheapters 

### Other extensions used

not relevant

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-20 204244](https://github.com/uBlockOrigin/uAssets/assets/100969549/78dd416f-05f1-4b63-979a-4193b622bb22)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 274092
 cosmetic: 285808
 scriptlet: 54081
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4332-9, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-132, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all: 2098-1, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-0, now
  CHN-0: 26347-130, now
  JPN-1: 14839-90, now
  KOR-1: 5006-57, now
  adguard-cookies: 30108-84, now
  [22 lists not shown]: [too many]
 default:
  user-filters: 78-0, never
  DEU-0: 7494-5, now
  easylist: 87056-999, now
  easyprivacy: 51078-996, now
  plowe-0: 3552-2, now
  ublock-badware: 9127-0, now
  ublock-filters: 38670-719, now
  ublock-privacy: 938-116, now
  ublock-quick-fixes: 85-0, now
  ublock-unbreak: 2352-6, now
  urlhaus-1: 14950-0, now
filterset (user): [array of 79 redacted]
trustedset:
 added: [array of 11 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 68 redacted]
hostRuleset:
 added: [array of 107 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings:
 debugScriptlets: true
 loggerPopupType: normal
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 678 ms (selfie)
 maxAssetCacheWait: 312 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  disqus.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##.icon-facebook-circle
  ##.share-icons-wrapper
  ###form
  ###reactions__container
  ##.tab-user.nav-tab--primary.nav-tab
  ###footer
  ###email-signup
  ###thread-subscribe-button
  ###thread-share-bar
  ###placement-top
```
</details>

**Comment by D4niloMR** [comment]
Add:

`pawread.com##+js(set-local-storage-item, countChapterNum, $remove$)`

**Comment by ave9858** [comment]
> Add:
> 
> `pawread.com##+js(set-local-storage-item, countChapterNum, $remove$)`

Works for me, tested 20 chapters in a row and had no issue after applying this filter.
