### ISSUE TITLE
investor-web.hdfcfund.com: breakage

### ISSUE THREAD

**Issue by ajangir** [uBlockOrigin/uAssets#24191]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://investor-web.hdfcfund.com/`

### Category

breakage

### Description

When uBlockOrigin is enabled, site malfunctions and cannot load properly.

### Other extensions used

onetab, vimium.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 138212
 cosmetic: 46655
 scriptlet: 21240
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87042-568, 1h.40m Δ
  easyprivacy: 51077-638, 1h.40m Δ
  plowe-0: 3552-0, now
  ublock-badware: 9095-0, 1h.40m Δ
  ublock-filters: 38664-275, 1h.40m Δ
  ublock-privacy: 933-0, 1h.40m Δ
  ublock-quick-fixes: 84-0, 1h.40m Δ
  ublock-unbreak: 2344-0, 1h.40m Δ
  urlhaus-1: 14950-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 328 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  hdfcfund.com: 1
  demdex.net: 2
  googletagmanager.com: 2
  netcore.co.in: 1
```
</details>

**Comment by ajangir** [comment]
EasyPrivacy line
@@||netcoresmartech.com/smartechclient.js$domain=hdfcfund.com

My filter that unbreaks the website with normal function when applied
@@||tw.netcore.co.in/smartechclient.js$script,domain=investor-web.hdfcfund.com

Filter = ||netcore.co.in^$3p
Filter list = EasyPrivacy
Context = investor-web.hdfcfund.com
Partyness = (3) hdfcfund.com ⇒ netcore.co.in
Type = script
URL = https://tw.netcore.co.in/smartechclient.js

**Comment by stephenhawk8054** [comment]
It's already fixed in https://github.com/uBlockOrigin/uAssets/commit/b67727dc2343abdda54238e171e36e4d0d93cc16
