### ISSUE TITLE
ya.ru: ads

### ISSUE THREAD

**Issue by abdusamadzoidov17** [uBlockOrigin/uAssets#24190]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ya.ru/search/?text=free+hosting+website&lr=10318`

### Category

ads

### Description

ads

### Other extensions used

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 79956
 cosmetic: 66190
 scriptlet: 22886
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
  easyprivacy: null
  urlhaus-1: null
 added:
  ublock-cookies-easylist: 1217-0, now
 default:
  ublock-filters: 38664-108, 2m
  easylist: 87003-520, now
  plowe-0: 3552-0, 2m
  RUS-0: 39310-61, now
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
 hyperlinkAuditingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6049 ms (selfie)
 maxAssetCacheWait: 865 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  yandex.ru: 2
 extended:
  ##.b-page.overlay[data-serp-metrika]:style(overflow-y: auto !imp…
  ##+js(abort-on-property-read, MarketFeed)
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
removed:
  user-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
  easyprivacy: null
  urlhaus-1: null
 added:
  ublock-cookies-easylist: 1217-0, now
 default:
  ublock-filters: 38664-108, 2m
  easylist: 87003-520, now
  plowe-0: 3552-0, 2m
  RUS-0: 39310-61, now
```

Test again in a new browser profile with only uBO and its default settings.

**Comment by dimisa-RUAdList** [comment]
See also: https://github.com/uBlockOrigin/uAssets/issues/16208
