### ISSUE TITLE
upfiles.com: detection

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#24199]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://upfiles.com/S8ztvja`

### Category

detection

### Description

Link redirects to another site that probably causes it.
Android 10 
Kiwi browser latest version 
Ubo
Default + Ubo and easylist annoyance 

### Other extensions used

Non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240621-011711_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/51786709/5cf3a546-1b6c-44b3-bdd8-e800e6983300)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium Mobile: 124
filterset (summary):
 network: 142724
 cosmetic: 80413
 scriptlet: 27099
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4672-19, 7m
  easylist-chat: 197-0, 7m
  easylist-newsletters: 7587-11, 7m
  easylist-notifications: 3029-84, 7m
  ublock-annoyances: 5952-51, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 39102-351, 7m Δ
  ublock-badware: 9133-0, 7m
  ublock-privacy: 939-0, 7m
  ublock-unbreak: 2355-0, 7m Δ
  ublock-quick-fixes: 85-0, 7m
  adguard-mobile: 9509-23, 8m
  easylist: 87056-653, 7m
  easyprivacy: 51078-115, 7m
  urlhaus-1: 14950-0, 7m
  plowe-0: 3552-697, 7m
  TUR-0: 13219-20, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2812 ms
 maxAssetCacheWait: 723 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  dampedvisored.com: 1
```
</details>

**Comment by dportvine** [comment]
I have another problem: **EasyList's** general rules hide download link.

`https://upfiles.com/wiVp`

```adblock
##.ad-element
##.ad-inner
```

<details>
<summary>Screen</summary>

![2024-08-08_153444](https://github.com/user-attachments/assets/133237f6-bc0b-4279-9eb3-17f9a29daa21)
![2024-08-08_153321](https://github.com/user-attachments/assets/11ac0ec6-4918-4136-b45b-d8a57a1b430e)
</details>
