### ISSUE TITLE
Any way to resolve anti-adblocker on maxisciences.com?

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#242]
Hi,

I cannot find the formula to prevent the anti-adblocker on maxisciences.com.
Their anti-adblocker doesn't show up on the front page, only within articles, for example:

> http://www.maxisciences.com/oreille/pourquoi-a-t-on-mal-aux-oreilles-en-avion-et-comment-l-039-eviter_art38892.html

I like the site, I'd trully appreciate your help. Thanks.

**Comment by SMed79** [comment]
Hi, 
see https://forums.lanik.us/viewtopic.php?p=105906#p105906

**Comment by zymase** [comment]
Hi @SMed79 , the page you mention has 2 scripts pertinent to maxisciences.com, and neither works here.
Thanks.

**Comment by uBlock-user** [comment]
add

`maxisciences.com##script:inject(setTimeout-defuser)`

**Comment by okiehsch** [comment]
> `maxisciences.com##script:inject(setTimeout-defuser)`

This will break the video player, if you click play it will not start.
If you do not want to use an exception filter, add 
`||maxisciences.com/jsad/advertisement.js$xmlhttprequest,redirect=nooptext,domain=maxisciences.com`

**Comment by zymase** [comment]
Right, uBlock-user's filter breaks the video player, or rather, here, it forces Flash when html5 is available and offered otherwise. Also the page isn't rendered correctly.

The filter mentioned above, found on the page linked by SMed79 works perfectly. 

Anyway, thanks to all three of you.

**Comment by uBlock-user** [comment]
Works fine for me. I tested the filter and the video played.

**Comment by zymase** [comment]
Well, here,  okiehsch's filter doesn't make it as well ... only the first filter up to now works here:

> @@/jsad/advertisement.js|$xmlhttprequest,~third-party,domain=exclusivomen.com|gentside.com|gentside.com.br|gentside.de|maxisciences.com|ohmirevista.com|ohmymag.com|ohmymag.com.br|ohmymag.de|simplyvoyage.com

Looks like the demonstration that filters may render differently depending maybe on their interaction with other installed filters ...

**Comment by uBlock-user** [comment]
Though you're right about html5 not playing and instead flash starts playing. Didn't notice that.

Try this `maxisciences.com##script:inject(abort-on-property-read.js, IS_BLOCKED)`

This one seems to work and the HTML 5 video plays.

**Comment by okiehsch** [comment]
You are right, my filter doesn´t work with firefox, just tested it, sorry I use Chrome as default browser.
The filter works with Chrome and Edge, atleast at my end.

**Comment by rjkpa** [comment]
add
 
`||static.mxstatic.com/static/mscripts/index_303.js$script,redirect=noopjs`

**Comment by gorhill** [comment]
Thanks @rjkpa, filter works fine.

(sorry about the delay for this issue, it fell off my radar)

**Comment by zymase** [comment]
@rjkpa your filter works correctly but at least on maxisciences.com where I've tested it, if it does block the anti-adblocker on article pages, it also happens to block on the site's homepage a mxstatic jpg file:
`mxstatic.com/une/slide2067-w960.jpg`

**Comment by rjkpa** [comment]
@zymase Sorry, this is the best I came up with, unless @gorhill can concoct a better one.

**Comment by zymase** [comment]
Thanks @rjkpa 
The first one proposed here (above) works fine, blocks the anti-adblocker without breaking the front-page:

> @@/jsad/advertisement.js|$xmlhttprequest,~third-party,domain=exclusivomen.com|gentside.com|gentside.com.br|gentside.de|maxisciences.com|ohmirevista.com|ohmymag.com|ohmymag.com.br|ohmymag.de|simplyvoyage.com

**Comment by gorhill** [comment]
How about:

    maxisciences.com##body > div[id]:has(:scope > img[src$="adb-arrow.png"])
    maxisciences.com##body > div[id$="-after"]

**Comment by gorhill** [comment]
> The first one proposed here

Looks fine to me (it's a first-party exception). It's not part of EasyList France?

**Comment by zymase** [comment]
The filter was proposed above by @SMed79 and comes from  https://forums.lanik.us/viewtopic.php?p=105906#p105906
If the blocked original rule comes from EasyList France, I have no idea
