### ISSUE TITLE
carter-cash.com: breakage

### ISSUE THREAD

**Issue by obistro** [uBlockOrigin/uAssets#24202]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.carter-cash.com/pieces-auto/p/yeti-batterie-voiture-12v-start-stop-72ah-720a-l3-n32b-23828087/5991969`

### Category

breakage

### Description

The comments do not appear correctly.

### Other extensions used

nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 8014
 cosmetic: 14502
 scriptlet: 19071
 html: 1735
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
  FRA-0: null
 added:
  easylist-annoyances: 4675-18, now
 default:
  ublock-filters: 38786-112, 41m Δ
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 308 ms (selfie)
 maxAssetCacheWait: 30 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  avis-verifies.com: 1
```
</details>

**Comment by obistro** [comment]
I tested again and indeed the issue does not appear with the defaults settings. The problematic list is "EasyList – Other Annoyances"

**Comment by obistro** [comment]
I still have the same issue (no comment on the bottom of the page). Is it normal?

**Comment by obistro** [comment]
I did it but i have the same behavior.

**Comment by stephenhawk8054** [comment]
It will take time for the list to be auto updated. You can use this filter as a custom filter in the meantime

```adb
||avis-verifies.com^$third-party,badfilter
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by obistro** [comment]
Thank you @stephenhawk8054
It works perfectly !
