### ISSUE TITLE
tv5mondeplus.com: breakage

### ISSUE THREAD

**Issue by cedk** [uBlockOrigin/uAssets#24201]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tv5mondeplus.com/fr/culture-et-art-de-vivre/vie-culturelle-et-artistique/derriere-les-paroles-s-1-e1-julien-dore-la-fievre/play?t=49.91779688644753`

### Category

breakage

### Description

The video does not play and an error message "Erreur 1001 – Erreur réseau : vérifiez votre connexion internet" is displayed.

### Other extensions used

Privacy Badger
I don't care about cookies
Decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 155774
 cosmetic: 53171
 scriptlet: 19986
 html: 1846
listset (total-discarded, last-updated):
 added:
  FRA-0: 24679-403, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38789-112, now
  ublock-badware: 8986-0, now
  ublock-privacy: 929-2, now
  ublock-unbreak: 2412-2, now
  ublock-quick-fixes: 83-2, now
  easylist: 87083-179, now
  easyprivacy: 51081-64, now
  urlhaus-1: 15175-0, now
  plowe-0: 3550-989, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 941 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  aswpsdkeu.com: 2
  aticdn.net: 1
  doubleclick.net: 1
  fwmrm.net: 1
  go-mpulse.net: 1
  googletagmanager.com: 2
  sentry.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Even when I don't use any extensions, the error still appears for me sometimes

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/7f2a4dcb-1f7a-4bfe-af64-2ce9a077d929)

**Comment by mapx-** [comment]
@stephenhawk8054 even so I get that error on refreshing the page.

Could you test:

```
tv5mondeplus.com##+js(cookie-remover, /^/)
tv5mondeplus.com##+js(set-local-storage-item, /^/, $remove$)
```

**Comment by stephenhawk8054** [comment]
@mapx- I did test when opening in a fresh profile without uBO and the error reappeared when I refreshed too. But I'll check more carefully later.

**Comment by mapx-** [comment]
yes, it's a site issue too

**Comment by mapx-** [comment]
@cedk 

add & test:

```
@@||mssl.fwmrm.net/libs/adm/*/AdManager.js$script,domain=tv5mondeplus.com
tv5mondeplus.com##+js(cookie-remover, /^/)
tv5mondeplus.com##+js(set-local-storage-item, /^/, $remove$)
```

**Comment by stephenhawk8054** [comment]
@mapx- I think removing `didomi_token` is enough. Do these work on your side?

```adb
@@||mssl.fwmrm.net/libs/adm/*/AdManager.js$script,domain=tv5mondeplus.com
tv5mondeplus.com##+js(cookie-remover, didomi_token)
tv5mondeplus.com##+js(set-local-storage-item, didomi_token, $remove$)
```
