### ISSUE TITLE
live8.vebo18.net: ads

### ISSUE THREAD

**Issue by Hungcter1** [uBlockOrigin/uAssets#24209]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://live8.vebo18.net/home`

### Category

ads

### Description

s

### Other extensions used

y

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 138827
 cosmetic: 47974
 scriptlet: 21472
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  VIE-1: 1977-0, now
  easylist: 87095-489, now
  easyprivacy: 51081-640, now
  plowe-0: 3550-0, now
  ublock-badware: 8984-0, now
  ublock-filters: 38697-380, now
  ublock-privacy: 938-0, now
  ublock-quick-fixes: 82-0, now
  ublock-unbreak: 2353-0, now
  urlhaus-1: 15175-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 139 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by huyszn** [comment]
@hoang-rio ads

`https://live8.vebo18.net/home` also redirects me to `https://live9.vebo18.net/home`

**Comment by hoang-rio** [comment]
> @hoang-rio ads
> 
> `https://live8.vebo18.net/home` also redirects me to `https://live9.vebo18.net/home`

You can use this tool to update domain redirection that exits in ABPVN List: http://abpvn.com/report/

**Comment by huyszn** [comment]
https://github.com/abpvn/abpvn/commit/cfb143189daf63cecf27ab1aa8fd8db8643abc77
https://github.com/abpvn/abpvn/commit/aa01449ba11849b2a99f800d9bed272a9488017f
