### ISSUE TITLE
fetedelamusique.culture.gouv.fr: breakage

### ISSUE THREAD

**Issue by SmilingGit** [uBlockOrigin/uAssets#24205]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fetedelamusique.culture.gouv.fr/programme`

### Category

breakage

### Description

There is a map on this site (provided by wemap by what I see when I disable ublock origin), and it doesn’t load with ublock enabled. Since it’s the only content of the website, it becomes pretty much useless without. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 168697
 cosmetic: 195978
 scriptlet: 32572
 html: 2108
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 79658-137, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99873-23306, now
  ublock-annoyances: 5868-213, 1h.45m Δ
  FRA-0: 24679-437, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38789-448, 1h.45m Δ
  ublock-badware: 8986-0, 1h.45m Δ
  ublock-privacy: 929-4, 1h.45m Δ
  ublock-unbreak: 2412-7, 1h.45m Δ
  ublock-quick-fixes: 83-2, 1h.45m Δ
  easylist: 87083-259, 1h.45m Δ
  easyprivacy: 51081-223, 1h.45m Δ
  urlhaus-1: 15175-0, now
  plowe-0: 3550-990, now
  DEU-0: 7503-43, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 524 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  tarteaucitron.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||et-gv.fr^$3p` in EP

@ryanbr
