### ISSUE TITLE
emtv.com.pg: ads

### ISSUE THREAD

**Issue by esaieman** [uBlockOrigin/uAssets#24219]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://emtv.com.pg/`

### Category

ads

### Description

most ads are blocked but some are not

### Other extensions used

Google Translate
Pocket
Grammarly
Video Speed Controller

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (7)](https://github.com/uBlockOrigin/uAssets/assets/173564225/5919dade-5a73-4b1f-8616-5fabd58baa67)
![Screenshot (8)](https://github.com/uBlockOrigin/uAssets/assets/173564225/a7ddee57-146d-4b9e-92d8-8cec2c45f3e2)
![Screenshot (9)](https://github.com/uBlockOrigin/uAssets/assets/173564225/1033682e-cee7-4503-9964-a7bab71e143d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 207308
 cosmetic: 217906
 scriptlet: 54050
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1084-0, 3m
  adguard-generic: 81531-7197, now
  adguard-mobile: 9534-14, now
  adguard-spyware-url: 1544-120, now
  adguard-spyware: 68703-27408, never
  block-lan: 68-0, never
  curben-phishing: 483-0, now
  adguard-cookies: 30128-32, now
  ublock-cookies-adguard: 1224-14, never
  fanboy-cookiemonster: 67481-20105, now
  ublock-cookies-easylist: 1224-1224, never
  adguard-popup-overlays: 27237-963, 1m
  [8 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 38789-624, 24m Δ
  ublock-badware: 8700-3, 24m Δ
  ublock-privacy: 938-0, 24m Δ
  ublock-unbreak: 2353-0, 24m Δ
  ublock-quick-fixes: 83-0, 24m Δ
  easylist: 87122-743, 24m Δ
  easyprivacy: 51085-787, 24m Δ
  urlhaus-1: 14040-0, now
  plowe-0: 3550-84, 3m
filterset (user): [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1588 ms (selfie)
 maxAssetCacheWait: 799 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  emtv.com.pg: 8
  google.com: 1
  googletagmanager.com: 1
  popt.in: 1
  youtube.com: 2
 extended:
  ##.advads-target
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by mapx-** [comment]
add

```
emtv.com.pg##.advads-slider
emtv.com.pg##[id^="advads"]
```

report here: https://github.com/easylist/easylist/issues

**Comment by esaieman** [comment]
how do I add that to EasyList?

**Comment by mapx-** [comment]
- report the ads at EL repository 
- add those filters in "my filters" (click uBO icon, open the dashboard, "my filters" tab)
