### ISSUE TITLE
thwiki.cc: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#24215]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thwiki.cc/`

### Category

ads

### Description

Ad shows on the page.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/35957435/383ae11b-a141-465a-a414-75c6f288ec23

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 129
filterset (summary):
 network: 211458
 cosmetic: 233652
 scriptlet: 50997
 html: 2107
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81775-4014, now
  adguard-spyware-url: 1543-120, now
  adguard-spyware: 68731-1505, now
  curben-phishing: 511-2, now
  fanboy-cookiemonster: 51247-191, now
  ublock-cookies-easylist: 1224-3, now
  adguard-social: 23305-56, now
  fanboy-social: 16291-742, now
  fanboy-thirdparty_social: 68-19, now
  adguard-popup-overlays: 27235-1042, now
  adguard-mobile-app-banners: 5305-24, now
  adguard-other-annoyances: 14459-427, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 38793-112, now
  ublock-badware: 8702-0, now
  ublock-privacy: 929-2, 17m Δ
  ublock-unbreak: 2412-2, now
  ublock-quick-fixes: 83-2, 17m Δ
  easylist: 87105-2220, 17m Δ
  easyprivacy: 51085-26890, 17m Δ
  urlhaus-1: 5265-0, now
  plowe-0: 3550-1082, now
  CHN-0: 26373-226, now
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 165 ms (selfie)
 maxAssetCacheWait: 114 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  baidu.com: 2
  google-analytics.com: 1
  googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you check this?

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/658eb36fe79a6c2087aed8377202ff438edb7cd7
