### ISSUE TITLE
kimcartoon.li: detection / breakages

### ISSUE THREAD

**Issue by Ema66** [uBlockOrigin/uAssets#24217]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kimcartoon.li/`

### Category

detection

### Description

The following message is showing up blocking the stream:
Please disable AdBlock (or any ads blocking) to watch video on KimCartoon. You can [Go Premium](https://kimcartoon.li/Message/GoPremium) to disable ads.
If you are using Kaspersky Anti-Virus Software, please disable Anti-Banner feature.
If you think this is an error, please report [here](https://kimcartoon.li/Message/ReportError)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![issue](https://github.com/uBlockOrigin/uAssets/assets/173560872/7e55ede6-3fda-4a18-8385-123106d57696)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 302159
 cosmetic: 379069
 scriptlet: 58994
 html: 0
listset (total-discarded, last-updated):
 added:
  ALB-0: 305-0, now
  BGR-0: 1040-1, now
  CHN-0: 26376-143, now
  CZE-0: 833-2, now
  DEU-0: 7504-0, now
  EST-0: 464-1, now
  FIN-0: 2281-0, now
  FRA-0: 24699-514, now
  GRC-0: 1095-0, now
  HRV-0: 389-2, now
  HUN-0: 2104-4, now
  IDN-0: 9960-0, now
  [46 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ITA-0: 8538-72, now
  easylist: 87122-1238, now
  easyprivacy: 51085-989, now
  plowe-0: 3550-67, now
  ublock-badware: 8700-4, now
  ublock-filters: 38789-922, now
  ublock-privacy: 938-117, now
  ublock-quick-fixes: 83-0, now
  ublock-unbreak: 2353-23, now
  urlhaus-1: 14040-0, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 726 ms (selfie)
 maxAssetCacheWait: 433 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  kimcartoon.li: 1
  bidgear.com: 1
  facebook.com: 2
  gamescdnfor.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  jsdelivr.net: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  oaphoace.net: 1
  sharethis.com: 1
  staticmoly.me: 6
  vidmoly.to: 1
  vmring.cc: 1
  yandex.ru: 1
 extended:
  ##[href="#"]
  ##.kcAds1
  ###hideAds
  ###ad-promo
  ##.st_facebook_hcount
  ##.st_twitter_hcount
  ##+js(set-constant, alb, false)
  ##+js(json-prune, *, pop_type)
  ##+js(json-prune, *, rot_url)
  ##+js(abort-current-script, globalThis, break;case)
  ##+js(no-xhr-if, method:HEAD)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
```
</details>

**Comment by Ema66** [comment]
I forgot to mention that i had the same problem yesterday, after updating filters it was gone but now is back

**Comment by Ema66** [comment]
i disabled Easylist in the filter list and now is working.

**Comment by stephenhawk8054** [comment]
Don't disable EasyList

**Comment by mapx-** [comment]
@Ema66 

>  [46 lists not shown]: [too many]

reset uBO to defaults, add ONLY your specific regional list, test again

**Comment by LeHman93** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/44226902/83a1dcb8-5e05-4f3d-be5c-4a24a63ad68a)
Guess whos back

**Comment by uBlock-user** [comment]
@LeHman93 no, works fine. Tested at `https://kimcartoon.li/Cartoon/SpongeBob-SquarePants-Season-10/Episode-26A-Mutiny-on-the-Krusty?id=72055`

**Comment by BluCaekz** [comment]
tested just now for the link above. does not work, issue is still ongoing.

**Comment by mapx-** [comment]
as you can see an update has been added 3 hours ago, wait 5-6 hours or add

`kimcartoon.*##+js(no-xhr-if, method:get)`

**Comment by BluCaekz** [comment]
alright

**Comment by AUISHAIUSHIUAHSUIA** [comment]
The reason why people are still getting this adblock detection (at least in Chromium I don't know/use Firefox) is:
https://github.com/uBlockOrigin/uAssets/blob/35f3dcc52a333e55cb431ecc3f2e332228e62119/filters/filters-2024.txt#L265

adding the the exception ( `Kimcartoon.*,kisscartoon.se,kc.linksgen.com#@#+js(rmnt, script, /adb/i)` ) works okay and no detections anymore

Plus, it seems seems like it was always an unnecessary rule, that script would be _returning_ `isAdb` as false anyway, so the other rules are already made sure adblocker wouldn't be 'detected' (= 'true').

I will delete this comment so hope someone caught it to fix it for everyone.

**Comment by DesperatePea** [comment]
Problem seems to have returned. adding kimcartoon.*##+js(no-xhr-if, method:get) did not fix it.

**Comment by cinnamondev** [comment]
+1, updating filters did not change outcome. blocking /scripts/ozzz.min.js worked for me.
||kimcartoon.li/scripts/ozzz.min.js$script,1p

**Comment by of-me-is** [comment]
none of the suggested filters are working + they cause the prompt to disable ads to appear before the video even starts playing (meanwhile without them the video plays for about 5 seconds, then the popup appears)

**Comment by DesperatePea** [comment]
None of the mentioned filters are working as of today.

**Comment by Lucius6** [comment]
![afbeelding](https://github.com/uBlockOrigin/uAssets/assets/49132759/d3d08a30-345b-40cf-8d28-a1d9fe0d5701)

**Comment by CoolestGuy94** [comment]
Hello, seems like the adblock detection was updated.

**Comment by DesperatePea** [comment]
The filters are bypassed as fast as they are updated. Surely there must be a better way of doing this? At this moment there is an eternal game of cat and mouse with this site. What are some long-term solutions that could be attempted?

**Comment by Lucius6** [comment]
Apparently, he's following the development here. At this rate, he can kiss his ass and his site.

**Comment by DesperatePea** [comment]
Excactly, so either the filters need to update in secret, or ..well..not sure.

**Comment by stephenhawk8054** [comment]
There's nothing called long term solution if the website owners deliberately circumvent our filters. uBO is a tool, it cannot change website owners anti-user behaviors. Users are the only ones who can affect the websites by their own feedbacks and decisions.

**Comment by Lucius6** [comment]
This guy just don't want to listen. The biggest problem is that the adds are malicious too. Otherwise I wouldn't use a blocker all the time. Someone tried to talk sense into him but he blocked him, he doesn't want te cooperate.

https://www.reddit.com/r/KissCartoon/comments/1dyypsz/heated_issue_with_kc/

If he keeps this up...

**Comment by Rachitidk** [comment]
You may close the issue at the site is closed due to DMCA.
