### ISSUE TITLE
Compromised websites

### ISSUE THREAD

**Issue by PhoenixFossGR** [uBlockOrigin/uAssets#24211]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
margopassadorestylist.com
agisakis.gr
agyria.gr
alzo.gr
anasathalassas.gr
diathermiki.gr
alpha1047.gr
```

### Description

These websites are compromised by PIKABOT and other types of malware

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
What do you mean with compromised? Are there any malware payloads? Malicious subdomains?

**Comment by JobcenterTycoon** [comment]
What do you mean with compromised? Are there any malware payloads? Malicious subdomains?

**Comment by JobcenterTycoon** [comment]
Why you don’t add active payloads to https://urlhaus.abuse.ch/ ? Please check if there is a thread active and don’t just collect random domains from the internet or other databases. We can’t check hundrets of payloads, URLhaus can.

Also please post a way to reproduce like: "You can find the malware by opening X and clicking on the button Y" or "Here is the malicious URL: `https://example.com/spamredirect.html`" or "There is a spam campaign active, see this post on social media X with examples" (maybe it can be covered up with a regex)

**Comment by JobcenterTycoon** [comment]
uBlock Origin has the lite version enabled by default (lite = only active payloads). This is how it works:

1. A user adding a payload to URLhaus.
2. The payload getting checked (to prevent false positives and trolling) and after this the URL being added to the official list. The list can be viewed on https://urlhaus.abuse.ch/browse/
3. Payloads with the "Online" status will be included to the filterlist. Old entrys with the "Offline" status will be removed.
4. The filterlist will be updated like other filterlists.
