### ISSUE TITLE
plurk.com: ads

### ISSUE THREAD

**Issue by punchpolygons** [uBlockOrigin/uAssets#24210]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.plurk.com/`

### Category

ads

### Description

![26gh4PekGxCmkRJxJ9ykNR](https://github.com/uBlockOrigin/uAssets/assets/173504830/2d0d03c4-345c-4de6-9dd3-ad08c2682885)
when clicking on an entry in order to type a comment, there is a second of delay before an ad appears below the text entry box

### Other extensions used

privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![26gh4PekGxCmkRJxJ9ykNR](https://github.com/uBlockOrigin/uAssets/assets/173504830/b4f5c6cc-dfcb-4929-b5c5-167635dd5c88)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 138341
 cosmetic: 46591
 scriptlet: 19846
 html: 1846
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38799-112, 4m
  ublock-badware: 8991-0, 4m
  ublock-privacy: 929-2, 4m
  ublock-unbreak: 2412-2, 4m
  ublock-quick-fixes: 82-2, 4m
  easylist: 87104-178, 4m
  easyprivacy: 51084-64, 4m
  urlhaus-1: 15175-0, 4m
  plowe-0: 3550-989, 4m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 389 ms
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  cloudflareinsights.com: 4
  googletagmanager.com: 1
  googletagservices.com: 1
  maps.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by punchpolygons** [comment]
Canada

**Comment by stephenhawk8054** [comment]
Hmm... I still can't see the ads even after using VPN to Canada

**Comment by mapx-** [comment]
@stephenhawk8054 "plurk" something then you'll see it at the top pf the page => click it in order to comment it and you'll get the ad

@punchpolygons 

add
`plurk.com###resp_banner_ads`

@ryanbr
