### ISSUE TITLE
cuty.io: ads

### ISSUE THREAD

**Issue by Batlightyear** [uBlockOrigin/uAssets#24222]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://plkedv.cfd/?tvZNEyJcDCnBIGVmiA9b2sj8KrulXedQz4p56R1OSxaFqTL0U-t37XAoycgFxerwiKEhzM9Q2CPufInOU0aZSV-re5EQSAW9cOMpGT7JfP
```

### Description

Fake download redirect.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 154438
 cosmetic: 53282
 scriptlet: 21419
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38692-274, 8m Δ
  ublock-badware: 8700-0, 19m
  ublock-privacy: 938-0, 19m
  ublock-unbreak: 2353-0, 10m Δ
  ublock-quick-fixes: 83-0, 19m
  easylist: 87122-594, 10m Δ
  easyprivacy: 51085-638, 19m
  urlhaus-1: 14040-0, 19m
  plowe-0: 3550-0, 19m
  FRA-0: 24699-379, 19m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 630 ms
 maxAssetCacheWait: 117 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
Where can we see that redirect link ? provide the original page link

**Comment by Batlightyear** [comment]
Hello the redirect link is from this website : cety.app it's a shortcut
however after the countdown when click on the go there is the redirect that
apparease with a malware in it.

**Comment by Batlightyear** [comment]
https://cuty.io/

**Comment by Batlightyear** [comment]
Hello the redirect link is from this website : https://cuty.io/ it's a
shortcut however after the countdown when click on the go there is the
redirect that apparease with a malware in it.

**Comment by mapx-** [comment]
provide the complete link

**Comment by Batlightyear** [comment]
It's on all redirect from this website https://cuty.io/

**Comment by stephenhawk8054** [comment]
It's a shortener site, provide the full URL to reproduce your issue. Your link is just the home page.

**Comment by Batlightyear** [comment]
Here : https://cuty.io/blIkkHQyyEnvoyé de mon iPhoneLe 23 juin 2024 à 04:43, stephenhawk8054 ***@***.***> a écrit :﻿
It's a shortener site, provide the full URL to reproduce your issue. Your link is just the home page.

**Comment by Batlightyear** [comment]
Hello it's happening again a malware was downloaded to my computer i deleted without open and please fix it https://cuty.io/blIkkHQyy

**Comment by stephenhawk8054** [comment]
Please comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361
