### ISSUE TITLE
veev.to: detection

### ISSUE THREAD

**Issue by fredred1445** [uBlockOrigin/uAssets#24220]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://veev.to/
```

### Description

Adblock detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
provide workable video links

**Comment by dportvine** [comment]
**[NSFW]** `https://veev.to/e/ffx51qa3zkcw` https://github.com/AdguardTeam/AdguardFilters/issues/175439

**Comment by stephenhawk8054** [comment]
```adb
||veev.to/assets/videoplayer/*.js$script,replace=/\bhttps:\/\/securepubads\.g\.doubleclick\.net\/pagead\/js\/adsbygoogle\.js/https:\/\/veev\.to\/assets\/videoplayer\/7ea94a8\.js/
```

works for me but cache might affect it.

@ghajini Can you check if the filter still works?

**Comment by stephenhawk8054** [comment]
@ghajini If you Ctrl + Shift + R to bypass cache, does it work?

**Comment by D4niloMR** [comment]
`veev.to##+js(set, Object.prototype.urlCheck, noopFunc)` or 

`@@||securepubads.g.doubleclick.net/pagead/js/adsbygoogle.js$xhr,domain=veev.to`

works on my end.

**Comment by CoolestGuy94** [comment]
Hello, the issue seems to come back.

**Comment by 055110** [comment]
Hello, it's detecting adblock again.

**Comment by 055110** [comment]
Hello, adblock is detected again.

**Comment by fredred1445** [comment]
Adblock detected again

**Comment by Bug-Cache** [comment]
![Image](https://github.com/user-attachments/assets/645d7655-d548-4668-93e6-bb860d9c5169)

uBOL Complete, Chrome

anti adblock show up
