### ISSUE TITLE
duolingo.com: privacy

### ISSUE THREAD

**Issue by divaltor** [uBlockOrigin/uAssets#24227]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.duolingo.com
```

### Description

There is URL which ping every few seconds to send analytics to Duolingo server - `https://excess.duolingo.com/batch`

### Other extensions used

Only uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1799" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/29837527/166148dd-2ac2-447d-afa1-f26089f4ea2a">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 223156
 cosmetic: 206397
 scriptlet: 49987
 html: 2125
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2654-0, 9m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1177-1, 3d.20h.40m
  adguard-generic: 81818-4031, 9m
  adguard-spyware-url: 1538-233, 4d.22h.4m
  adguard-spyware: 68703-1499, 4d.22h.4m
  block-lan: 67-0, 25d.2h.19m
  adguard-popup-overlays: 27221-245, 3d.11h.13m
  easylist-annoyances: 4673-214, 1d.57m
  easylist-chat: 196-1, 7d.17h.8m
  fanboy-cookiemonster: 51229-218, 3d.17h.40m
  ublock-cookies-easylist: 1224-3, never
  easylist-newsletters: 7589-541, 1d.58m
  [5 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 38904-114, 9m Δ
  ublock-badware: 8734-0, 9m Δ
  ublock-privacy: 929-49, 9m Δ
  ublock-unbreak: 2414-2, 9m Δ
  ublock-quick-fixes: 100-2, 9m Δ
  easylist: 87128-2256, 9m Δ
  easyprivacy: 51085-26885, 9m Δ
  urlhaus-1: 14040-0, 16h.21m
  plowe-0: 3552-1081, 6d.20h.13m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 autoUpdateDelayAfterLaunch: 10
 cnameMaxTTL: 1080
 filterAuthorMode: true
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 297 ms (selfie)
 maxAssetCacheWait: 135 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  cookielaw.org: 1
  google.com: 1
  sentry.io: 8
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
```
</details>

**Comment by uBlock-user** [comment]
filter - `||excess.duolingo.com/batch^`

@ryanbr

**Comment by stephenhawk8054** [comment]
@onmyouji Does it work?
