### ISSUE TITLE
premio.io: breakage

### ISSUE THREAD

**Issue by poptins** [uBlockOrigin/uAssets#24225]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://premio.io/`

### Category

breakage

### Description

It seems like cdn.chatway.app is being blocked for no reason. Chatway is a live chat product that has nothing to do with ads.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 138381
 cosmetic: 47792
 scriptlet: 19931
 html: 1854
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38889-112, 4m
  ublock-badware: 8707-0, 4m
  ublock-privacy: 929-2, 4m
  ublock-unbreak: 2413-2, 4m
  ublock-quick-fixes: 100-2, 4m
  easylist: 87124-178, 4m
  easyprivacy: 51085-64, 4m
  urlhaus-1: 14780-0, 4m
  plowe-0: 3550-989, 4m
  ISR-0: 1888-3, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1429 ms
 maxAssetCacheWait: 12 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  premio.io: 2
  cloudflare.com: 1
  google.com: 3
  googletagmanager.com: 1
  popt.in: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need an account? What is broken? What are the steps to reproduce the issue?

I go to your link above and I don't know what to look at and what to do next

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/e10bbc0c-250e-4fb3-bc96-7f650d167974)

**Comment by poptins** [comment]
This live chat widget should appear on that page (should load from https://cdn.chatway.app)
Screenshot:
![image](https://github.com/uBlockOrigin/uAssets/assets/49234453/6045ae05-6bda-4b2d-8a29-e3eaeebcbb05)

**Comment by poptins** [comment]
I can see you closed the issue, but I meant that cdn.chatway.app in general, should be allowed as it's used by many websites:
https://apps.shopify.com/chatway
https://www.wix.com/app-market/chatway-live-chat
https://wordpress.org/plugins/chatway-live-chat/
https://squareup.com/au/en/app-marketplace/app/chatway-live-chat

**Comment by stephenhawk8054** [comment]
uBO doesn't block `cdn.chatway.app` by default. The issue was `cloudflare.com/cdn-cgi/trace` being blocked

**Comment by poptins** [comment]
Got it :)
When do you expect this fix to be pushed to prod?

**Comment by stephenhawk8054** [comment]
The fix will be pushed in about 5-6 hours.

**Comment by poptins** [comment]
Thanks, I'll keep monitoring. Will it fix the issue for all websites that use Chatway?

**Comment by stephenhawk8054** [comment]
I don't know. Just report the sites with breakages to this thread.

**Comment by poptins** [comment]
Chatway is used by many websites, I'd like the fix to be a general fix for all websites please

**Comment by stephenhawk8054** [comment]
We need to know where the other breakages first. We cannot guess just based on one website.

And I don't know why `chatway.app` is related to `cloudflare.com/cdn-cgi/trace`, is it because of the website or is it because of `chatway.app`? We don't know.
