### ISSUE TITLE
chatgpt.com: breakage

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uAssets#24229]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://chatgpt.com/c/afb41ec8-f2da-449d-8736-646e3020a514`

### Category

breakage

### Description

for example on my account, you have to create a free account and test it yourself
since gpt4o is out it is grate in recherching things on the web, but that will resoult in a list of links in its responses, when i click them with ublock origin on firefox enabled i get mad cause they dont work (sometimes sometimes not, just after F5 i guess). So please have a look into it so that there convoluted javascript (why ever they use javascript for links maybe to track ther users) still works so i can open links without asking it to give me the link in plaintext! thx in advance, keep up the good work, its an easy miss, dont want to be rude but i am a bit frustraded today for other resons.

### Other extensions used

i dont care about cookies (tried to disable ), dark reader, singlefile (both dont bother changing anything but css or only when they are run manually on a page)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 139338
 cosmetic: 51848
 scriptlet: 19884
 html: 1845
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 38908-114, 1h.48m Δ
  ublock-badware: 8734-0, 1h.48m Δ
  ublock-privacy: 929-2, 1h.48m Δ
  ublock-unbreak: 2416-2, 1h.48m Δ
  ublock-quick-fixes: 100-2, 1h.48m Δ
  easylist: 87184-179, 1h.48m Δ
  easyprivacy: 51093-64, 1h.48m Δ
  urlhaus-1: 14040-0, now
  plowe-0: 3552-989, now
  DEU-0: 7504-37, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8258 ms (selfie)
 maxAssetCacheWait: 2311 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by nanderer** [comment]
PS: im not particular sure about all of that i checked, but it is happening on multiple devices whithout sync enabled so its an common enough issue i guessd

**Comment by loadstring1** [comment]
can you include screenshots? everything seems to be working for me
