### ISSUE TITLE
yesmovies.ag: detection

### ISSUE THREAD

**Issue by greypowerOz** [uBlockOrigin/uAssets#24236]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ww.yesmovies.ag/movie/dark-matter-season-1-1630857014.html`

### Category

detection

### Description

seem like "some videos" play fine, so it might  be the "source servers" for the actual content.   One of your team on reddit was unable to reproduce this, so there's still a chance it's a "me problem".

I can only offer that I've changed nothing on my  Ubuntu laptop overnight :) 

IF it's just me, all good.  Thanks again for this tool. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/screenshot-WbMUwGF

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 137953
 cosmetic: 46848
 scriptlet: 21301
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 87180-467, 5m
  easyprivacy: 51096-638, 5m
  plowe-0: 3550-0, 5m
  ublock-badware: 8802-0, 5m
  ublock-filters: 38808-376, 5m
  ublock-privacy: 938-0, 5m
  ublock-quick-fixes: 101-0, 5m
  ublock-unbreak: 2357-0, 5m
  urlhaus-1: 14905-0, 5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 845 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  d1e28xq8vu3baf.cloudfront.net: 1
  heardaccumulatebeans.com: 1
  jwpltx.com: 1
 extended:
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, AaDetector)
  ##+js(nowebrtc)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(no-setTimeout-if, afterOpen)
  ##+js(set-constant, PlayerConfig.config.CustomAdSetting, [])
```
</details>

**Comment by mapx-** [comment]
- reproducible even disabling uBO
- running episode 4 => only sound, no video 
- site issue

**Comment by greypowerOz** [comment]
update: https://imgur.com/screenshot-Sp7DbgE 

I found this in the logger, references https://listeamed.net/adblock If I block this url, the stream still fails with "blocked by an extension" but if I choose a different "server" for the file, it works OK. So I suspect it's just that server (??)
thanks team

**Comment by greypowerOz** [comment]
"click episode 5, choose server 3, can you reproduce?"
- i see server 1,2,3 listed. When in choose "3" the list refreshes and says "playing on server 5"

https://imgur.com/UOcqLG1.png     fails to play, due to me adding https://listeamed.net/adblock to the rules I think...

https://imgur.com/5gK5LKk.png  yes, removing the filter goes back to this .

SERVER 2, episode 5 plays ok.     Just not 1 / 3

**Comment by greypowerOz** [comment]
problem went away after reset uBlock to defaults.   Thanks for taking the time to help out.
