### ISSUE TITLE
mackabler.dk: breakage

### ISSUE THREAD

**Issue by jonathanparisi** [uBlockOrigin/uAssets#24237]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mackabler.dk/`

### Category

breakage

### Description

MacKabler uses Algolia for search only but search functionality is not working because Algolia scripts are blocked. Website only uses old version of algolia and no ads, statistic, analytics are stored. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139465
 cosmetic: 49150
 scriptlet: 21330
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  NOR-0: 3855-4, 27m
  easylist: 87187-567, 27m
  easyprivacy: 51085-639, 27m
  plowe-0: 3550-0, 27m
  ublock-badware: 8802-0, 27m
  ublock-filters: 38808-279, 27m
  ublock-privacy: 938-0, 27m
  ublock-quick-fixes: 101-0, 27m
  ublock-unbreak: 2357-0, 27m
  urlhaus-1: 14905-0, 27m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 742 ms
 maxAssetCacheWait: 158 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  mackabler.dk: 1
  algolia.io: 3
  cloudflareinsights.com: 1
  klaviyo.com: 2
  mouseflow.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
