### ISSUE TITLE
buzzheavier.com: ads 

### ISSUE THREAD

**Issue by detyso** [uBlockOrigin/uAssets#24231]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

web https://buzzheavier.com/
`https://buzzheavier.com/f/GQymN4fyoAA=`

### Category

ads

### Description

when pressing click here to unlock link it goes to a malware site
also the red button is a fake download link 

video on it

https://github.com/uBlockOrigin/uAssets/assets/163365484/e367a6e4-e5ff-423f-a318-f2276a0fac20

### Other extensions used

bitwarden violentmonkey darkreader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG_0642](https://github.com/uBlockOrigin/uAssets/assets/163365484/7a13c855-b88d-4ef5-b76b-dc81243af2ca)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 138021
 cosmetic: 46666
 scriptlet: 19871
 html: 1845
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38873-114, 4m
  ublock-badware: 8707-0, 4m
  ublock-privacy: 929-2, 4m
  ublock-unbreak: 2416-2, 4m
  ublock-quick-fixes: 100-2, 4m
  easylist: 87128-178, 4m
  easyprivacy: 51085-64, 4m
  urlhaus-1: 15120-0, 4m
  plowe-0: 3550-989, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2808 ms
 maxAssetCacheWait: 12 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by detyso** [comment]
the ads are again on the website

**Comment by ave9858** [comment]
New ad on `https://buzzheavier.com/notfound`:

![Image](https://github.com/user-attachments/assets/5e413003-bd7c-4428-94ac-4cfe63642905)

**Comment by playonevideo** [comment]
If you click these buttons on `https://bzzhr.co/v46cmtnbsjjy` when you first enter the site, it tries to open a popup:

<img width="447" height="83" alt="Image" src="https://github.com/user-attachments/assets/519eab51-04fd-463f-9f1d-3f5b1563a952" />

This is one of their mirror sites.

**Comment by BlazeFTL** [comment]
fixed

**Comment by playonevideo** [comment]
> If you click these buttons on `https://bzzhr.co/v46cmtnbsjjy` when you first enter the site, it tries to open a popup:
> <img alt="Image" width="447" height="83" src="https://private-user-images.githubusercontent.com/277447603/583779260-519eab51-04fd-463f-9f1d-3f5b1563a952.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODAwNjI1ODgsIm5iZiI6MTc4MDA2MjI4OCwicGF0aCI6Ii8yNzc0NDc2MDMvNTgzNzc5MjYwLTUxOWVhYjUxLTA0ZmQtNDYzZi05ZjFkLTNmNWIxNTYzYTk1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDUyOVQxMzQ0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjQwODgzNjg3Mjk1YTFlZTI5MWUxYzAxZGY5MTY3OWZkYmM0NjFiNTMwMWNlMDM2ZGY5M2Y0YjhkNTU0ZDcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.CQW1HNPdHuUKc0hQDJEBXOf1ZbmRxIFtyJcBB1BEnJA">
> 
> This is one of their mirror sites.

It happens again.

Link: https://bzzhr.co/9n9wdrc9hw6s

**Comment by playonevideo** [comment]
On `https://buzzheavier.com/fw94dro960b3` and `https://bzzhr.co/z9c0q3ejf7dq` if you click the "Open in browser instead" button, it tries to open a popup.
