### ISSUE TITLE
corendonairlines.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#24238]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.corendonairlines.com/de`

### Category

nuisance

### Description

This is a third party request. loaded from cookiesuit.com

![img03](https://github.com/uBlockOrigin/uAssets/assets/173714801/aa1b72d2-2306-4538-88e8-d631fdb296d9)

### Other extensions used

Windscribe VPN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 142106
 cosmetic: 98741
 scriptlet: 30403
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51263-189, now
  ublock-cookies-easylist: 1227-0, now
  ublock-annoyances: 5924-66, never
 default:
  user-filters: 0-0, never
  ublock-filters: 38774-292, 1m
  ublock-badware: 8802-0, 1m
  ublock-privacy: 938-0, 1m
  ublock-unbreak: 2357-0, 1m
  ublock-quick-fixes: 101-0, 1m
  easylist: 87124-576, 1m
  easyprivacy: 51096-647, 1m
  urlhaus-1: 14525-0, 1m
  plowe-0: 3550-0, 1m
  DEU-0: 7503-3, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1439 ms
 maxAssetCacheWait: 158 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.grecaptcha-badge
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by mapx-** [comment]
add

`||cdn.cookiesuit.com^$3p`

@ryanbr
