### ISSUE TITLE
yoututosjeff.blogspot.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2423]
URL(s) where the issue occurs

`http://yoututosjeff.blogspot.com/2015/05/sony-vegas-pro-13-full.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.8

Settings

Default

**Comment by KiLL4FuNK** [comment]
`https://yoututosjeff1.blogspot.com/2016/07/genarts-sapphire-plug-ins-61-13-sshake.html`

**Comment by kulfoon** [comment]
Again:

### Screenshot(s)

![capture_032_13-05-2020_13-48-33](https://user-images.githubusercontent.com/43844449/81809122-1c54cb80-9521-11ea-9612-d0718c05dc05.gif)

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.26.2

### Settings

Default
