### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by Ema66** [uBlockOrigin/uAssets#24239]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kimcartoon.li/`

### Category

detection

### Description

i already open an another issue #24217 the problem is exactly the same

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![issue](https://github.com/uBlockOrigin/uAssets/assets/173560872/50842a21-dca8-4323-a775-28b3d0b7db1a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139285
 cosmetic: 53649
 scriptlet: 21302
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  ublock-filters: 38809-286, 9m
  ublock-badware: 8802-0, 9m
  ublock-privacy: 938-0, 9m
  ublock-unbreak: 2357-0, 4m Δ
  ublock-quick-fixes: 101-0, 9m
  easylist: 87189-574, 2m Δ
  easyprivacy: 51096-23, 9m
  urlhaus-1: 14525-0, 9m
  plowe-0: 3550-615, 9m
  ITA-0: 8538-19, 9m
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 403 ms
 maxAssetCacheWait: 124 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  kimcartoon.li: 8
  bidgear.com: 1
  gamescdnfor.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  jquery.com: 1
  jsdelivr.net: 1
  sharethis.com: 1
  staticmoly.me: 1
 extended:
  ##.kcAds1
  ##+js(abort-current-script, setTimeout, adsbygoogle.js)
  ##+js(remove-node-text, script, /adb/)
  ##+js(no-xhr-if, method:HEAD)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
  ###vope
  ###mg_vd
  ###dos_vlock
  ###adsblock
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/\{"brs_content_label":[^,]…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
```
</details>

**Comment by mapx-** [comment]
continue in the old issue

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/43734e55f0aa7061beca8eb24b993739788805ff
