### ISSUE TITLE
highspeedinternet.com: ads

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#24234]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.highspeedinternet.com/va/fairfax?zip=22033`

### Category

ads

### Description

Advertisements placed by ISP companies are clearly visible and show the text "Ad" above them

### Other extensions used

_none_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/306c3296-e80f-4a5f-bb34-c623b7530f0d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 137845
 cosmetic: 46724
 scriptlet: 19871
 html: 1845
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 38873-114, 27m Δ
  ublock-badware: 8734-0, 27m Δ
  ublock-privacy: 929-2, 27m Δ
  ublock-unbreak: 2416-2, 27m Δ
  ublock-quick-fixes: 101-2, 27m Δ
  easylist: 87184-178, 27m Δ
  easyprivacy: 51095-64, 27m Δ
  urlhaus-1: 14905-0, now
  plowe-0: 3550-989, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1291 ms
 maxAssetCacheWait: 849 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by uBlock-user** [comment]
`highspeedinternet.com##.provider-ads`
