### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by tomdog86** [uBlockOrigin/uAssets#24235]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kimcartoon.li/Cartoon/When-the-Wind-Blows/Movie?id=32905&s=vg`

### Category

detection

### Description

It detected that I have a ad blocker

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 137882
 cosmetic: 46831
 scriptlet: 21292
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 87184-44, now
  easyprivacy: 51095-650, now
  plowe-0: 3550-377, now
  ublock-badware: 8732-16, now
  ublock-filters: 38774-376, now
  ublock-privacy: 938-3, now
  ublock-quick-fixes: 101-0, now
  ublock-unbreak: 2357-15, now
  urlhaus-1: 14905-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10247 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  kimcartoon.li: 1
  bidgear.com: 1
  facebook.com: 1
  googletagmanager.com: 1
  heardaccumulatebeans.com: 1
  listeamed.net: 1
  sharethis.com: 1
 extended:
  ###ad-promo
  ##.kcAds1
  ##+js(remove-node-text, script, /adb/)
  ##+js(no-xhr-if, method:HEAD)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/\{"brs_content_label":[^,]…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed few hours ago. Update your filter lists again. Then continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/24217
