### ISSUE TITLE
sport890.com.uy: detection

### ISSUE THREAD

**Issue by Juanmsan** [uBlockOrigin/uAssets#24233]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sport890.com.uy/envivo/`

### Category

detection

### Description

Hi there, in the last weeks the site started to detect uBlock Origin (or ABP). I use LibreWolf, and even with other extensions disabled, uBo is detected.

### Other extensions used

Chameleon
Grammar.com
Native MPEG-Dash + HLS Playback

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-06-24 at 01-15-09 Radio en vivo - Sport 890 - La Radio Deportiva del Uruguay](https://github.com/uBlockOrigin/uAssets/assets/173407445/ca1a9a0c-5ce8-4ecc-a788-e69580a43408)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 166248
 cosmetic: 149927
 scriptlet: 30855
 html: 2123
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 67489-16424, 42m
  ublock-cookies-easylist: 1224-3, 42m
  fanboy-social: 16306-11, 42m
  fanboy-thirdparty_social: 68-16, 42m
  easylist-annoyances: 4681-53, 42m
  easylist-chat: 197-0, 42m
  easylist-newsletters: 7606-24, 42m
  easylist-notifications: 3032-164, 42m
  ublock-annoyances: 5865-84, 45m Δ
  RUS-0: 39415-195, 45m Δ
  spa-0: 4064-34, 45m
  spa-1: 5792-255, 45m
 default:
  user-filters: 0-0, never
  ublock-filters: 38874-114, 45m Δ
  ublock-badware: 8734-0, 45m Δ
  ublock-privacy: 929-2, 45m Δ
  ublock-unbreak: 2416-2, 45m Δ
  ublock-quick-fixes: 101-2, 45m Δ
  easylist: 87180-178, 45m Δ
  adguard-spyware-url: 1544-120, 45m
  easyprivacy: 51095-64, 45m Δ
  urlhaus-1: 14905-0, 45m
  curben-phishing: 497-2, 45m
  plowe-0: 3550-989, 42m
  LegitimateURLShortener: 2654-162, 45m
filterset (user): [empty]
hostRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 415 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  chartbeat.com: 1
  clarity.ms: 1
  doubleclick.net: 2
  getadjacent.com: 1
  googletagmanager.com: 1
  parsely.com: 2
 extended:
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##ned-ad
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?
