### ISSUE TITLE
silive.com: detection

### ISSUE THREAD

**Issue by kurtisnelson** [uBlockOrigin/uAssets#24232]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.silive.com/news/2008/08/faresaving_walk_now_less_of_a.html`

### Category

detection

### Description

Using `https://www.getadmiral.com/pb`

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 138097
 cosmetic: 46827
 scriptlet: 21292
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87184-567, 1h.45m Δ
  easyprivacy: 51095-638, 1h.45m Δ
  plowe-0: 3550-0, now
  ublock-badware: 8732-0, 1h.45m Δ
  ublock-filters: 38774-276, 1h.45m Δ
  ublock-privacy: 938-0, 1h.45m Δ
  ublock-quick-fixes: 101-0, 1h.45m Δ
  ublock-unbreak: 2357-0, 1h.45m Δ
  urlhaus-1: 15120-0, 1h.45m
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 640 ms (selfie)
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 52
 network:
  silive.com: 17
  ads-twitter.com: 1
  amazon-adsystem.com: 1
  ambrosialsummit.com: 2
  arc.pub: 1
  associates-amazon.com: 1
  blueconic.net: 2
  crwdcntrl.net: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  doubleclick.net: 1
  ex.co: 1
  facebook.com: 4
  go-mpulse.net: 2
  google-analytics.com: 2
  google.com: 1
  googletagmanager.com: 1
  licdn.com: 1
  linkedin.com: 1
  matheranalytics.com: 1
  moatads.com: 1
  ntv.io: 1
  rubiconproject.com: 1
  sail-horizon.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
  succeedscene.com: 1
  taboola.com: 1
  teads.tv: 1
  trackonomics.net: 1
 extended:
  ###below-toprail
  ##.ad
  ##.ad-observer
  ##.ads--no-preload
  ##.ad--sponsor-content
  ##.ad-unit:not(.text-ad):not(.textads)
  #@#.ad-unit
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
  ##+js(abort-on-property-read, _sp_._networkListenerData)
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by kurtisnelson** [comment]
Could it be that I am traveling in Mexico?

**Comment by stephenhawk8054** [comment]
I can't reproduce when using VPN to Mexico either.

**Comment by mapx-** [comment]
@kurtisnelson reset uBO to defaults, disable any other extension, test again
