### ISSUE TITLE
decathlon.pl: breakage

### ISSUE THREAD

**Issue by AlecClaire** [uBlockOrigin/uAssets#24244]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.decathlon.pl/p/rower-gorski-mtb-st-530-s-27-5/_/R-p-311716`

### Category

breakage

### Description

"Product details" are not shown when uBO is enabled.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 138844
 cosmetic: 54970
 scriptlet: 20101
 html: 1856
listset (total-discarded, last-updated):
 added:
  POL-0: 8694-45, now
  POL-2: 1283-48, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38925-114, now
  ublock-badware: 8835-0, now
  ublock-privacy: 929-2, now
  ublock-unbreak: 2421-2, now
  ublock-quick-fixes: 102-2, now
  easylist: 87222-178, now
  easyprivacy: 51097-64, now
  urlhaus-1: 14315-0, 11m
  plowe-0: 3550-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 260 ms (selfie)
 maxAssetCacheWait: 63 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  baqend.com: 3
  googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
You mean this section?

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/a11da5b4-f179-4126-ae4d-e2be6c8c8e9e)

**Comment by AlecClaire** [comment]
Well, yes. I didn;t even close the browser (FF) and now when reopening this
page (been done before during this session) now it seems to work just fine.
I guess the topic can be closed if everything is working properly.

wt., 25 cze 2024 o 11:46 stephenhawk8054 ***@***.***>
napisał(a):
