### ISSUE TITLE
kotobank.jp: detection

### ISSUE THREAD

**Issue by noirblack666** [uBlockOrigin/uAssets#24245]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kotobank.jp/word/%E9%81%B8%E6%8C%99%E5%85%AC%E5%96%B6-88113`

### Category

detection

### Description

Recently this site started to apply their anti-ad block scheme to work,some enthusiasts had made some filters tweak to counteract but now they tune it to function again .

### Other extensions used

![snap0000028](https://github.com/uBlockOrigin/uAssets/assets/61659562/36631066-b82f-445d-a3a8-85552ec0ec81)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![snap0000026](https://github.com/uBlockOrigin/uAssets/assets/61659562/962b8784-9911-4b14-b284-5584d995b77f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 242409
 cosmetic: 245878
 scriptlet: 53275
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 26399-168, 30m
  IRN-0: 3066-0, 30m
  JPN-1: 14862-85, 30m
  KOR-1: 5013-19, 46m
  RUS-0: 39385-533, 30m
  TUR-0: 13223-11, 30m
  adguard-cookies: 30156-52, 30m
  adguard-generic: 81927-7388, 31m
  adguard-mobile: 9545-66, 31m
  adguard-mobile-app-banners: 5308-10, 30m
  adguard-other-annoyances: 14494-77, 30m
  adguard-popup-overlays: 27240-231, 30m
  [7 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 87222-841, 31m
  easyprivacy: 51095-44, 31m
  plowe-0: 3552-717, 30m
  ublock-badware: 8833-2, 31m
  ublock-filters: 38815-728, 31m
  ublock-privacy: 938-5, 31m
  ublock-quick-fixes: 101-0, 31m
  ublock-unbreak: 2357-25, 31m
  urlhaus-1: 14315-0, 31m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1336 ms (selfie)
 maxAssetCacheWait: 341 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.header-ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, return, 7400)
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed already: https://github.com/uBlockOrigin/uAssets/commit/f8b9dc2bf8604c92647b0622faa72aac0511e34d

Update your filter lists again
