### ISSUE TITLE
matchendirect.fr: ads

### ISSUE THREAD

**Issue by malfoyez** [uBlockOrigin/uAssets#24252]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.matchendirect.fr/live-score/pologne-france.html`

### Category

ads

### Description

A <div> to access boosted odds for the Euro is displayed

### Other extensions used

none.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2](https://github.com/uBlockOrigin/uAssets/assets/169759235/5e59cadc-114a-4bae-80f9-8ec74b1fc1a8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 278473
 cosmetic: 275693
 scriptlet: 52120
 html: 2107
listset (total-discarded, last-updated):
 added:
  https://curbengh.github.io/pup-filter/pup-filter.txt: 199-0, now
  adguard-generic: 81960-502, now
  adguard-mobile: 9543-260, now
  adguard-spyware-url: 1570-120, now
  adguard-spyware: 68795-2014, now
  block-lan: 68-0, now
  curben-phishing: 561-1, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 23-0, never
  ublock-filters: 38923-3882, 1h.54m Δ
  ublock-badware: 8840-126, 1h.54m Δ
  ublock-privacy: 929-8, 1h.54m Δ
  ublock-unbreak: 2421-98, 1h.54m Δ
  ublock-quick-fixes: 102-3, 1h.54m Δ
  easylist: 87244-87244, 1h.54m Δ
  easyprivacy: 51097-28725, 1h.54m Δ
  urlhaus-1: 14860-0, now
  plowe-0: 3550-1601, now
  FRA-0: 24703-631, now
filterset (user): [array of 37 redacted]
trustedset:
 added: [array of 45 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 330 ms (selfie)
 maxAssetCacheWait: 159 ms
 cacheBackend: indexedDB
 unsuspendAfter: 138 ms
popupPanel:
 blocked: 9
 network:
  bkrtx.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  optinly.net: 1
  privacy-center.org: 2
  sportslocalmedia.com: 2
  yandex.ru: 1
 extended:
  ##.bloc_coldroite[style]
  ###tux728x90
```
</details>

**Comment by mapx-** [comment]
explain better your issue, step by step, if an account is required etc
