### ISSUE TITLE
arras.io: detection / nuisance / breakage

### ISSUE THREAD

**Issue by zephiii** [uBlockOrigin/uAssets#24250]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://arras.io/`

### Category

detection

### Description

Page displays a popup banner on the home screen and ingame.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screenshot 2024-06-25 at 14 11 29" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/7abff5d1-a43c-4572-af9b-c244d04de27e">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 140084
 cosmetic: 73693
 scriptlet: 22542
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30109-35, now
 default:
  user-filters: 97-0, never
  easylist: 87222-571, 58m Δ
  easyprivacy: 51097-638, 58m Δ
  plowe-0: 3550-0, now
  ublock-badware: 8833-0, 58m Δ
  ublock-filters: 38824-277, 58m Δ
  ublock-privacy: 938-0, 58m Δ
  ublock-quick-fixes: 102-0, 58m Δ
  ublock-unbreak: 2362-0, 58m Δ
  urlhaus-1: 14860-0, 58m
filterset (user): [array of 99 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  broadborder.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  intergi.com: 1
  intergient.com: 1
```
</details>

**Comment by mapx-** [comment]
- if it's an annoyance enable uBlock filters – Annoyances 

test
`arras.io##+js(nostif, , 3000)`

**Comment by Zephiii** [comment]
> test `arras.io##+js(nostif, , 3000)`

That breaks the main menu and stops me from clicking the play button.

**Comment by JobcenterTycoon** [comment]
I get no detection without uBO when i accepted the cookie banner already.

They checking something deeper, i was not able to get a good solution.

**Comment by avotoko** [comment]
works for me.
```
! avoid detection
||cdn.intergient.com/1024850/73985/ramp.js$script,redirect-rule=noopjs,domain=arras.io
arras.io##+js(rpnt, script, /Function\(r\)\(\)/, '"function"')
```

**Comment by JobcenterTycoon** [comment]
I get "The connection was closed by the server due to a unknown reason" with the filter when i try to join a game.

**Comment by avotoko** [comment]
I have reproduced that message. It seems I didn't look into it properly. I'll look into it again.

**Comment by avotoko** [comment]
please try the following filters again. the game starts fine on my end.
```
||cdn.intergient.com/1024850/73985/ramp.js$script,redirect-rule=noopjs,domain=arras.io
arras.io##+js(rpnt, script, /Function\(r\)\(\)/, r.startsWith("return typeof")?"function":Function(r)())
```

**Comment by JobcenterTycoon** [comment]
Thanks works well.

**Comment by avotoko** [comment]
fixed the second line. works for me. tested on firefox and chrome.
```
||cdn.intergient.com/1024850/73985/ramp.js$script,redirect-rule=noopjs,domain=arras.io
arras.io##+js(set, ramp.addUnits, noopFunc)
```

**Comment by Zephiii** [comment]
Still affects Firefox, but not Chromium.
<img width="1440" alt="Screenshot 2024-07-29 at 18 06 54" src="https://github.com/user-attachments/assets/a89bd9cd-1eff-45dc-8f69-8c3b05b2de5c">

**Comment by JobcenterTycoon** [comment]
Works all fine for me. Do you enabled `uBlock filters – Annoyances`?

**Comment by zephiii** [comment]
> Works all fine for me. Do you enabled `uBlock filters – Annoyances`?

same issue.

**Comment by mapx-** [comment]
working fine here, reset uBO to defaults

**Comment by TheGreenSquare** [comment]
> > Works all fine for me. Do you enabled `uBlock filters – Annoyances`?
> 
> doesn't work.

Update, this seems to work fine now
