### ISSUE TITLE
[nsfw] freeshot.live: detection

### ISSUE THREAD

**Issue by djjjjjjjpj** [uBlockOrigin/uAssets#24260]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freeshot.live/live-tv/bein-sports-max-4/51`
`https://www.freeshot.live/live-tv/france`

### Category

detection

### Description

impossible de lire le streaming

### Other extensions used

en aucune

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 155820
 cosmetic: 53498
 scriptlet: 21482
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  ublock-filters: 38848-110, now
  ublock-badware: 8869-0, now
  ublock-privacy: 938-0, now
  ublock-unbreak: 2364-2, now
  ublock-quick-fixes: 103-2, now
  easylist: 87253-595, now
  easyprivacy: 51096-800, now
  urlhaus-1: 15190-0, now
  plowe-0: 3551-0, now
  FRA-0: 24703-379, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 483 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 no-popups: true
 network:
  a-ads.com: 1
  adligature.com: 2
  alwingulla.com: 1
  conditioneavesdroppingbarter.com: 1
  d3mr7y154d2qg5.cloudfront.net: 1
  histats.com: 3
  intellipopup.com: 1
  outbrain.com: 1
  quantserve.com: 1
  srvtrck.com: 2
  wkqqdchbbz.com: 1
  wwicnmksxd.com: 1
  yandex.ru: 1
  zovidree.com: 1
 extended:
  ##+js(set-constant, bb, false)
  ###ad_container
  ##.ad_container
  ###ad_header
  ##.ad_header
  ###ad_close
  ###ad_content
  ##.ad_content
  ###fixedban
```
</details>

**Comment by mapx-** [comment]
tested link:
`https://www.freeshot.live/live-tv/bein-sports-1-fr/38`

**Comment by stephenhawk8054** [comment]
Duplicated issue of https://github.com/uBlockOrigin/uAssets/issues/24299 . OP constantly ignores

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

**Comment by djjjjjjjpj** [comment]
merci

Le jeu. 11 juil. 2024 à 10:51, stephenhawk8054 ***@***.***> a
écrit :
