### ISSUE TITLE
eczacidergisi.com.tr: detection

### ISSUE THREAD

**Issue by cmnbhgt** [uBlockOrigin/uAssets#24269]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eczacidergisi.com.tr/haberler/titck-uygulamayi-duzeltti/`

### Category

detection

### Description

anti-adblock alert

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/173935722/3093a799-b3ed-4866-8a8f-eb613cd445ab)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.1b11
Chromium: 126
filterset (summary):
 network: 139077
 cosmetic: 57067
 scriptlet: 22968
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38862-110, now
  ublock-badware: 8874-0, now
  ublock-privacy: 938-0, now
  ublock-unbreak: 2364-2, now
  ublock-quick-fixes: 103-2, never
  easylist: 87253-572, never
  easyprivacy: 51096-805, never
  urlhaus-1: 14520-0, now
  plowe-0: 3551-0, now
  TUR-0: 13220-24, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4215 ms
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.widget-ad-image
  ##.advert-wrap
  ##.advert-image
  ##.ad-wrap:not(#google_ads_iframe_checktag)
  #@#.ad-wrap
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by cmnbhgt** [comment]
I can reproduce it in Brave browser even without uBO.

**Comment by D4niloMR** [comment]
So it's caused by brave shields?
