### ISSUE TITLE
[NSFW] efukt.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2426]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

```
http://efukt.com/
```

### Describe the issue

Popups clicking any URL. Tries to open following link.
```
https://crptentry.com/pu/?psid=ed_fkt&site=jsm&targ
```

### Screenshot(s)

Popups

### Versions

- Browser/version: Firefox Quantum Latest.
- uBlock Origin version: Latest.

### Settings

Default.

### Notes

None popups.

**Comment by C0nw0nk** [comment]
Even more missed ads with a HTML classname.

```
class="8db635 col plugs-nice-try-adblockers"
``

URl's
```
https://efukt.com/videos/naughty/don-t-tell-your-mother_1715/
https://efukt.com/videos/naughty/white-girl-destroyed_1712/
https://efukt.com/videos/naughty/18-year-old-debut_1713/
https://efukt.com/videos/naughty/legendary-anal_1714/
```

Bottom above footer allot of external links advertising rougue sites.
```
class="hardlinks font700"
https://www.honestpornreviews.com/default.cfm
etc
etc
```

Top of page in header bar.

```
http://www.nothingtoxic.com/?utm_source=efukt&utm_medium=nav&utm_campaign=nav01
http://crazyshit.com/?utm_source=efukt&utm_medium=nav&utm_campaign=nav2
```

**Comment by C0nw0nk** [comment]
Following fake video URL's still on pages.

These fake video URL's redirect of site to adverts.
```
https://efukt.com/videos/naughty/don-t-tell-your-mother_1715/
https://efukt.com/videos/naughty/white-girl-destroyed_1712/
https://efukt.com/videos/naughty/18-year-old-debut_1713/
https://efukt.com/videos/naughty/legendary-anal_1714/
```

This is what real video URL's look like.
```
https://efukt.com/22448_Most_Fucked_Up_Movie_Ever.html
```

Clearly very different.

**Comment by C0nw0nk** [comment]
Not sure what this is since now I am struggling to replicate it but I had a ad message when i clicked a random video on the homepage.

Here is the screenshot i took.
![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40960783-b161ccbc-6898-11e8-98c4-430e8ac362df.jpg)

I guess something new in their anti-adblock methods.

**Comment by C0nw0nk** [comment]
@okiehsch @mapx- 

Got the same above ad again from clicking a video the Iframe URL.
```
https://crptentry.com/pu/?target=postfbrttr&psid=ed_fkt&site=jsm&utm_medium=partner&utm_source=CSC&cap=12&ms_notrack=1&categoryName=girl
```

But I caught their code this time sneaky.

The script that loads it.
```
<script src="https://static.efukt.com/js/efukt.js
```

The contents inside of this script that does it.
```
// @20160902 - prevent first click every 24 hours to allow popunder to load page in new tab
		(function() {
			var landing_cookie_name = "ef_landing_click";
			var cookies_value = "; "+ document.cookie;
			var cookies_parts = cookies_value.split("; "+ landing_cookie_name +"=");
			var landing_cookie_exists = (cookies_parts.length == 2);
			var landing_overlay_id = "ef_landing_overlay";
			var landing_overlay_css = {};
			var landing_overlay_events = "click.ef_landing_cookie";
			
			if(landing_cookie_exists || !$("body").hasClass("popunder_watcher")) {
				return;
			}
			
			landing_overlay_css['position'] = "absolute";
			landing_overlay_css['z-index'] = "1000";
			landing_overlay_css['top'] = "0";
			landing_overlay_css['right'] = "0";
			landing_overlay_css['bottom'] = "0";
			landing_overlay_css['left'] = "0";
			landing_overlay_css['opacity'] = "0";
			
			if(/iP/.test(navigator.userAgent)) {
				landing_overlay_css['cursor'] = "pointer";   // required for mobile browsers (iPhone/iPad)
				
				landing_overlay_events = "click.ef_landing_cookie touchstart.ef_landing_cookie";
			}
			
			$("<div/>", {
				'id': landing_overlay_id
			}).css(landing_overlay_css).appendTo("body");
			
			$("html").on(landing_overlay_events, function(e) {
				var landing_cookie_date = new Date();
				
				if(e.type == "touchstart") {
					// touchstart = dragging, single tap = click
					return;
				}
				
				landing_cookie_date.setTime((landing_cookie_date.getTime() + (24 * 60 * 60 * 1000)));
				
				document.cookie = landing_cookie_name +"=1; expires="+ landing_cookie_date.toGMTString() +"; path=/";
				
				$("#"+ landing_overlay_id).empty().remove();
				
				$("html").off(landing_overlay_events);
				
				// track event
				if(typeof ga == "function") {
					ga('send', 'event', "Popover Overlay Click", "click", "Overlay click", {
						'transport':	"beacon"
					});
				}
			});
			
			// window close event
			$(window).on('beforeunload', function(e) {
				if($("#"+ landing_overlay_id).length) {
					// track event when element is still active
					if(typeof ga == "function") {
						ga('send', 'event', "Popover Overlay Window", "close", "Overlay active on window close", {
							'transport':	"beacon"
						});
					}
				}
			});
		}());
```


And this

```
// @20180228 - efukt-popup
obfuscated javascript code
```

```
// @20180222 - adblock-anchors - placed at the beginning to prevent menu from splitting
```

```
$(".efukt-widget-slider-nice-try-adblockers").each(function() {
```

So much inside that script.

**Comment by C0nw0nk** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/12204587/42128766-f62cd2bc-7caa-11e8-9ea0-1a0c5a83d5a4.png)

More in the adblock bypassing etc.

Pages are now trying to preform sneaky mobile and desktop redirects to advertisements.

**Comment by C0nw0nk** [comment]
@okiehsch 

Now they have added banner ads to bypass instead under afgr3.com domain they load from.

```
http://www.afgr3.com/servlet/click/zone?zid=
```

**Comment by smed79** [comment]
```
/servlet/click/zone?
##a[href*="/servlet/click/zone?"]
```
```
||afgr3.com^
||afgr4.com^
||slfsmf.com^
||seethisinaction.com^
```
@ryanbr

**Comment by C0nw0nk** [comment]
@okiehsch  @smed79  @ryanbr

New domains bypassing blocks of banner ads.

old domains where afgr1.com afgr2.com etc etc

New
```
http://www.afgr10.com/servlet/click/zone?zid=
```

**Comment by C0nw0nk** [comment]
@okiehsch @ryanbr

New domains / Missed banner ads.
https://efukt.com/


afgr11.com
```
http://www.afgr11.com/region/us/zone?zid=
```

**Comment by ZaphodBeebblebrox** [comment]
Maybe try something more generic like `zone?zid$subdocument,domain=efukt.com` in easylist?

**Comment by C0nw0nk** [comment]
@okiehsch @ryanbr

Another new domain.

```
http://www.afgtrwd1.com/region/us/zone?
```

**Comment by okiehsch** [comment]
Does
````
*$subdocument,third-party,domain=efukt.com
@@||twitter.com^$subdocument,domain=efukt.com
````
work without breaking anything?

**Comment by C0nw0nk** [comment]
@okiehsch sorry for the late reply.

Yes that works absolutely perfectly. 💯
