### ISSUE TITLE
NanoAdblocker Issue - gitcdn.xyz down

### ISSUE THREAD

**Issue by nadrojisk** [uBlockOrigin/uAssets#24268]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt
https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt
```

### Description

The `gitcdn` project no longer appears to be supported. The repository has been [archived](https://github.com/schme16/gitcdn.xyz) as of June 2023, and the domain expired on May 25, 2023, and is now hosted elsewhere. Accessing any of the domains results in a 404 error. Additionally, VirusTotal and Palo Alto classify the domain as malicious and greyware, respectively, although only one vendor on VirusTotal flags it, which might be a false positive.

If the project is no longer actively maintained, an attacker could potentially register the domain and host malicious data, which uBlock Origin might inadvertently access.

### Other extensions used

1Password
DarkReader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/37343577/2840b489-6054-4707-af9f-5959b522122c)
![image](https://github.com/uBlockOrigin/uAssets/assets/37343577/272315b4-e95d-44ab-b9c8-36a2c12b462a)
![image](https://github.com/uBlockOrigin/uAssets/assets/37343577/78e3d937-c7b3-4a04-999e-935f911f0091)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by gothic-bum** [comment]
>    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt
>    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt
  
Those lists are already included in `badlists.txt` and importing them is forbidden by uBO.
