### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by majczelgaming** [uBlockOrigin/uAssets#24267]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aternos.org/`

### Category

detection

### Description

yesterday everything was okay and now aternos detects.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/132778559/1f632917-0a18-4eed-8b09-32b64b793c42)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 139179
 cosmetic: 55140
 scriptlet: 21543
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38856-110, now
  ublock-badware: 8874-0, now
  ublock-privacy: 938-0, now
  ublock-unbreak: 2364-2, now
  ublock-quick-fixes: 109-5, now
  easylist: 87321-587, now
  easyprivacy: 51101-185, now
  urlhaus-1: 14520-0, 1h.4m
  plowe-0: 3551-615, now
  POL-0: 8690-34, 1h.4m
  POL-2: 1280-46, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1565 ms
 maxAssetCacheWait: 241 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  aternos.org: 1
  ad-delivery.net: 1
  amazon-adsystem.com: 1
  quantserve.com: 1
  script.ac: 1
  venatusmedia.com: 1
  vntsm.com: 1
 extended:
  ##+js(no-setTimeout-if, hasAdblock)
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13144

**Comment by JobcenterTycoon** [comment]
Try `aternos.org#@#+js(nostif, hasAdblock)`
