### ISSUE TITLE
itemku.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#24278]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://itemku.com/t/dunia-digital?from=productdetail`

### Category

breakage

### Description

break product feature

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/c8305634-8b1a-49ab-acae-640733134fd4)

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/a3a8f7e9-ae94-42b5-82cc-8b6962527d29)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 146611
 cosmetic: 163396
 scriptlet: 34629
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8609-10, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 209-0, now
  adguard-other-annoyances: 14694-8, now
  adguard-popup-overlays: 27281-940, now
  easylist-annoyances: 4690-102, now
  easylist-chat: 197-0, now
  easylist-newsletters: 7540-28, now
  easylist-notifications: 3089-281, now
  fanboy-cookiemonster: 51278-260, now
  fanboy-social: 16321-19, now
  ublock-annoyances: 5930-106, 1h.11m Δ
  ublock-cookies-easylist: 1227-0, now
 default:
  user-filters: 51-0, never
  easylist: 87429-660, 1h.11m Δ
  easyprivacy: 51101-86, 1h.11m Δ
  plowe-0: 3551-615, now
  ublock-badware: 8961-1, 1h.11m Δ
  ublock-filters: 38888-691, 1h.11m Δ
  ublock-privacy: 938-5, 1h.11m Δ
  ublock-quick-fixes: 109-0, 1h.11m Δ
  ublock-unbreak: 2364-21, 1h.11m Δ
  urlhaus-1: 14170-0, now
filterset (user): [array of 51 redacted]
trustedset:
 added: [array of 29 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 661 ms (selfie)
 maxAssetCacheWait: 274 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  amplitude.com: 1
  clarity.ms: 1
  crazyegg.com: 1
  facebook.com: 1
  google.com: 2
  googletagmanager.com: 1
  tiktok.com: 2
 extended:
  ##.grid > a:has(div > div:has-text(Ad))
```
</details>

**Comment by stephenhawk8054** [comment]
Your link returns 404 Page not found for me

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/e2fc7d4d-191d-41c1-b497-c1e677a3bc0b)

**Comment by Yuki2718** [comment]
Provide stesp to reproduce, otherwise we can't check.

**Comment by stephenhawk8054** [comment]
So it's caused by an external list? @3xploiton3 Please respect the prerequisites before reporting:

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
