### ISSUE TITLE
npo.nl: ads

### ISSUE THREAD

**Issue by ludodv** [uBlockOrigin/uAssets#24275]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://npo.nl/start/serie/wie-is-de-mol/seizoen-22/wie-is-de-mol_65/afspelen`

### Category

ads

### Description

Video playback has 2 advertisement videos.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![afbeelding](https://github.com/uBlockOrigin/uAssets/assets/31469881/02829e2f-a096-4204-9002-6ba9f585a772)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 128952
 cosmetic: 48645
 scriptlet: 19954
 html: 1846
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38991-140, 1m Δ
  ublock-badware: 8958-0, 1m Δ
  ublock-privacy: 929-5, 2m Δ
  ublock-unbreak: 2423-20, 1m Δ
  ublock-quick-fixes: 109-2, 2m Δ
  easylist: 87430-202, 1m
  easyprivacy: 51101-2, now
  urlhaus-1: 5155-0, 1m
  plowe-0: 3551-989, 1m
  NLD-0: 2307-42, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2498 ms
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 66
 network:
  npo.nl: 51
  bitmovin.com: 13
  sentry.io: 2
 extended:
  ##+js(json-prune, assets.preroll)
```
</details>

**Comment by D4niloMR** [comment]
Add:

`||kjdsfjisdfjr23.azurewebsites.net^`

**Comment by krystian3w** [comment]
Should be needed ping someone from AdGuard team due drop support Dutch Boys and EL Dutch are busy.
