### ISSUE TITLE
leerolymp.com: breakage

### ISSUE THREAD

**Issue by Zahyra16** [uBlockOrigin/uAssets#24286]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://leerolymp.com/`

### Category

nuisance

### Description

website crashes when adblock is enabled

### Other extensions used

"Bitwarden", "Save to Pocket" and "Show Youtube Dislikes "

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/92189825/864024f6-c9e3-445c-a37b-25b9272a84e8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 140101
 cosmetic: 53798
 scriptlet: 21832
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 87455-630, 1h.14m Δ
  easyprivacy: 51101-651, 1h.14m Δ
  plowe-0: 3552-2, now
  spa-0: 4064-3, now
  spa-1: 5803-186, now
  ublock-badware: 9003-0, 1h.14m Δ
  ublock-filters: 38891-293, 1h.14m Δ
  ublock-privacy: 938-0, 1h.14m Δ
  ublock-quick-fixes: 110-0, 1h.14m Δ
  ublock-unbreak: 2364-4, 1h.14m Δ
  urlhaus-1: 14375-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 28 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 31612 ms (selfie)
 maxAssetCacheWait: 1262 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  leerolymp.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  myrtolbanzai.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||leerolymp.com/_nuxt/300-250.$script,1p
```

@ryanbr
