### ISSUE TITLE
fandom.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#24282]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vsrecommendedgames.fandom.com/wiki/Gamecube`

### Category

nuisance

### Description

Text selection annoyance.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 1](https://camo.githubusercontent.com/2cd839735a19e4a8b455e6bb4940e35325c3917a549ee2d935c19c73ab5d6c70/68747470733a2f2f63646e2e616467756172642e696e666f2f736974657265706f7274732f70387178616276767331636f30306338383877776373776b34677377636b736b34787862756869376a342e706e673f6e633d31)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 142301
 cosmetic: 89575
 scriptlet: 27169
 html: 2108
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27281-312, never
  adguard-mobile-app-banners: 5327-10, never
  adguard-other-annoyances: 14694-277, never
  adguard-widgets: 2564-8, never
  ublock-annoyances: 5873-94, never
 default:
  user-filters: 0-0, never
  ublock-filters: 38992-114, now
  ublock-badware: 8963-0, now
  ublock-privacy: 929-2, now
  ublock-unbreak: 2423-2, now
  ublock-quick-fixes: 109-2, now
  easylist: 87393-186, now
  easyprivacy: 51101-64, now
  urlhaus-1: 14170-0, now
  plowe-0: 3551-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2656 ms
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ###featured-video__player-container
  ###WikiaBar:has(> #WikiaBarWrapper > .wikia-bar-anon > .message[…
  ##.banner-notifications-placeholder
  ##body:style(margin-top: 0!important;)
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
```
</details>

**Comment by stephenhawk8054** [comment]
You can use this as custom filter:

```adb
fandom.com##+js(aeld, pointerup)
```

I think uAssets only addresses websites who completely block right click/selection.
