### ISSUE TITLE
semirallsport.wapsite.me: ads

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#24280]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://semirallsport.wapsite.me/Bein/1`
`https://semir.site123.me/`
`https://semirtvturkish.wap.sh/`
`https://semir5.mobie.in/`
`https://semir-film.wap.sh/`
`https://xshteyariya.wapsite.me/`
`https://semir2.mobie.in/`
`https://semir8.mobie.in/`
`https://semir-tv.wap.sh/`
`https://sem1r.wapsite.me/`

### Category

ads

### Description

I get ads and blue & white empty space at the bottom. On some of the sites I mentioned, sometimes a blank space (yellow?) appears at the top. 
It may also be necessary to block this site. 

`||xtgem.com^`

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![aa](https://github.com/uBlockOrigin/uAssets/assets/51531027/f722380a-272a-4d8c-bbce-986b13d38513)
![bbb](https://github.com/uBlockOrigin/uAssets/assets/51531027/9a46ac54-1add-4f7b-adf0-28ae9ba07042)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 138869
 cosmetic: 57201
 scriptlet: 22986
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13223-14, now
  easylist: 87429-580, 4m Δ
  easyprivacy: 51101-643, 4m Δ
  plowe-0: 3551-0, now
  ublock-badware: 8961-0, 4m Δ
  ublock-filters: 38888-286, 4m Δ
  ublock-privacy: 938-0, 4m Δ
  ublock-quick-fixes: 109-0, 4m Δ
  ublock-unbreak: 2364-0, 4m Δ
  urlhaus-1: 14170-0, 4m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 339 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  google-analytics.com: 1
  quantserve.com: 1
```
</details>

**Comment by punisher018** [comment]
In addition, the following filters improve the look and usability of websites. (at least for me)

```
wapsite.me,mobie.in,wap.sh##.xt_navigation
site123.me###showSmallAdOnScroll
mobie.in,wap.sh#$#iframe { height: 1080px !important; }
wapsite.me,mobie.in,wap.sh#$#.video-js.vjs-default-skin { padding-top: 0px !important; }
```

**Comment by Yuki2718** [comment]
It's not only these sites. But I'm not sure if generic-block is safe e.g. `http://produksi-fiberglass.com/`.

**Comment by Yuki2718** [comment]
> In addition, the following filters improve the look and usability of websites. (at least for me)

Not a job of public lists
