### ISSUE TITLE
cfxstores.com: nuisance

### ISSUE THREAD

**Issue by TheBuddmeister** [uBlockOrigin/uAssets#24287]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://cfxstores.com/%E2%9B%94%EF%BC%83%F0%9D%97%AF%F0%9D%97%B9%F0%9D%97%BC%F0%9D%97%B0%F0%9D%97%B8%F0%9D%97%B2%F0%9D%97%B1%EF%BC%83%E2%9B%94`

### Category

nuisance

### Description

I was attempting to download a manual from Manualslib.com and it gave me one of those old-fashioned "You've been compromised" overlay ransomware attack ads. Nasty stuff for the uninformed.  It will probably be gone in a day or two but I don't know if there is anything you guys can capture from this to prevent them from loading.

### Other extensions used

Microsoft Translator
Microsoft Editor

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/61038282/6ad564cc-52c6-4915-8461-97dbc4ffdc03)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 137720
 cosmetic: 47053
 scriptlet: 21363
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38891-276, 1h.28m Δ
  ublock-badware: 9003-0, 1h.28m Δ
  ublock-privacy: 938-0, 1h.28m Δ
  ublock-unbreak: 2364-0, 1h.28m Δ
  ublock-quick-fixes: 110-0, 1h.28m Δ
  easylist: 87455-575, 1h.28m Δ
  easyprivacy: 51101-23, 1h.28m Δ
  urlhaus-1: 14375-0, now
  plowe-0: 3543-615, now
filterset (user): [empty]
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 219 ms (selfie)
 maxAssetCacheWait: 87 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Give the exact original URL and describe the steps to reproduce the issue
