### ISSUE TITLE
freeshot.live: detection

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#24299]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freeshot.live/live-tv/sic-radical/401`

### Category

detection

### Description

Has to do with popcdn.day, but i can't figure out what exactly to change in the code. Player won't start due to adblock message being displayed

### Other extensions used

Only TWP and Pop-up Blocker Strict.

None of these have impact on this issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 137381
 cosmetic: 48530
 scriptlet: 23730
 html: 2132
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5873-32, 1h Δ
 default:
  user-filters: 126-2, never
  ublock-filters: 39020-114, 1h Δ
  ublock-badware: 8907-0, 1h Δ
  ublock-privacy: 929-2, 1h Δ
  ublock-unbreak: 2423-2, 1h Δ
  easylist: 86276-185, 1h Δ
  easyprivacy: 51106-64, 1h Δ
  urlhaus-1: 15005-0, 1h
  plowe-0: 3551-989, 1h
  ublock-quick-fixes: 108-5, 1h Δ
filterset (user): [array of 87 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 134 redacted]
hostRuleset:
 added: [array of 469 redacted]
urlRuleset:
 added: [array of 104 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 273 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  a-ads.com: 1
  alwingulla.com: 1
  chatango.com: 2
  d3mr7y154d2qg5.cloudfront.net: 1
  histats.com: 2
  intellipopup.com: 1
  sport-tv-guide.live: 1
  wkqqdchbbz.com: 1
  wwicnmksxd.com: 1
  yandex.ru: 1
 extended:
  ##+js(abort-on-property-write, _pop)
  ###ad_container
  ##.ad_container
  ###ad_header
  ##.ad_header
  ###ad_close
  ###ad_content
  ##.ad_content
  ###fixedban
```
</details>

**Comment by Alphamen16** [comment]
Thanks!

**Comment by punisher018** [comment]
**(NSFW)**
`https://www.freeshot.live/live-tv/miamitv/770`

The video player in this link detects adblocker.
