### ISSUE TITLE
watch.shout-tv.com: ads

### ISSUE THREAD

**Issue by wblamkin** [uBlockOrigin/uAssets#24297]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://watch.shout-tv.com/video/639142?seasonId=21722`

### Category

ads

### Description

Shout TV's video web player recently updated, and now a series of unskippable ads plays before the video.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 137179
 cosmetic: 47059
 scriptlet: 21368
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 86275-573, 5m
  easyprivacy: 51106-638, 5m
  plowe-0: 3543-0, 5m
  ublock-badware: 9011-0, 5m
  ublock-filters: 38896-276, 5m
  ublock-privacy: 938-0, 5m
  ublock-quick-fixes: 108-0, 25m Δ
  ublock-unbreak: 2364-0, 5m
  urlhaus-1: 15005-0, 6m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1481 ms
 maxAssetCacheWait: 1001 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googletagmanager.com: 2
  litix.io: 1
  sentry.io: 2
  springserve.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by wblamkin** [comment]
I'm accessing from the United States; I've attempted accessing the site with a VPN to see if other countries would work but that produces an error that prevents video playback.

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
watch.shout-tv.com##+js(json-prune-fetch-response, adsConfiguration, , propsToMatch, /vod)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by wblamkin** [comment]
This worked! Tried it on multiple videos and it worked on all of them. Thank you.
