### ISSUE TITLE
colonist.io: detection

### ISSUE THREAD

**Issue by awesomesauceis1** [uBlockOrigin/uAssets#24294]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://colonist.io/`

### Category

detection

### Description

site detects adblocker and prevents further usage of site

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 122
filterset (summary):
 network: 137740
 cosmetic: 47057
 scriptlet: 21367
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87471-472, 12m Δ
  easyprivacy: 51103-638, 12m Δ
  plowe-0: 3543-0, now
  ublock-badware: 9010-0, 12m Δ
  ublock-filters: 38895-379, 12m Δ
  ublock-privacy: 938-0, 12m Δ
  ublock-quick-fixes: 109-0, 12m Δ
  ublock-unbreak: 2364-0, 12m Δ
  urlhaus-1: 14375-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 578 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  googleoptimize.com: 1
  googletagmanager.com: 2
  jsdelivr.net: 1
  sentry.io: 12
  vlitag.com: 2
```
</details>

**Comment by D4niloMR** [comment]
How to reproduce the detection?

**Comment by stephenhawk8054** [comment]
If I'm not wrong, it needs an account that has played for a while?

**Comment by awesomesauceis1** [comment]
yes. after using the site, trying to start a game results in a popup, requiring disabling of adblocker.

![Screenshot 2024-06-29 221038](https://github.com/uBlockOrigin/uAssets/assets/136399456/b5dd0b90-8229-49b1-a774-d21409f8172d)

**Comment by mapx-** [comment]
@awesomesauceis1 
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by awesomesauceis1** [comment]
I think the account is linked to my Discord, which I would rather not share. Don't worry about it then. Thanks.
