### ISSUE TITLE
Blasting News Anti-Adblock

### ISSUE THREAD

**Issue by Buffmutti** [uBlockOrigin/uAssets#243]
### URL(s) where the issue occurs

`[http://de.blastingnews.com/gesundheit/2016/12/e-zigarette-mussen-dampfer-2017-tabaksteuer-bezahlen-001351147.html]`

### Describe the issue

I tried to read that article, but after like 1 second the whole area of the brwoser window was blocked by sort of a payment wall, just without a needed payment, all they ask is that you create a account on blastingnews.com (and maybe then they will ask for a payment, no clue, didn't try that) 

### Screenshot(s)

![ad_wall](https://cloud.githubusercontent.com/assets/22818031/21498832/90e9d58e-cc30-11e6-9f47-7b7b91479cd7.JPG)

### Versions

- Browser/version: Chrome  Version 55.0.2883.87 m (64-bit)
- uBlock Origin version: uBlock Origin v1.10.4

### Settings

Activated these Filters:
uBlock Filters,
uBlock Filters - Badware risks,
uBlock Filters - Privacy,
uBlock Filters - Unbreak,
EasyList,
Adblock Warning Removal List
Anti-Adblock Killer | Reek
Peter Lowe's Ad Server List,
EasyPrivacy,
Malware Domain List,
Malware domains,
DEU EasyList Germany
AakList (Anti-Adblock Killer)

### Notes

It could be that this is just a detection of how often you read on that page (with using a cookie maybe?) or its really a anti-adblock wall (the message on that wall says that you can read the article without ads after creating an account on that page, so i guess its really a anti-adblock wall)

**Comment by yoshimo** [comment]
`    <script type='text/plain' class='cookie-script'>

        if (typeof blockAdBlock === 'undefined') { console.log("adblock detected (blockAdBlock non definito), carico webpack"); adblockManager.adblockFound(); loadWebpack(); } else { blockAdBlock.onDetected(function() { console.log("adblock detected, carico webpack"); adblockManager.adblockFound(); loadWebpack(); }); var counterAdblockCheck = 0; var iteratoradblock = setInterval(function(){ if(counterAdblockCheck
        < 20){ counterAdblockCheck++; blockAdBlock.check(true); }else{ iteratoradblock=n ull; } }, 2000); } </script>`

rest is in http://srs.blastingnews.com/js/blasting-bpb-manager.js?v=5.1.2.24df6a0651261dd4e4b9cc126f6cc4d3

**Comment by gorhill** [comment]
Does this work?

    de.blastingnews.com###blasting-modal-login-ad-block
    de.blastingnews.com##.modal-backdrop-login-ad-block

**Comment by uBlock-user** [comment]
Try `blastingnews.com##script:inject(overlay-buster.js)`

**Comment by ghajini** [comment]
@gorhill 
thumbnails got blocked under most discussed news
![screenshot 105 _li](https://cloud.githubusercontent.com/assets/20338483/21581579/2d907188-d05d-11e6-920d-9acc75c16866.jpg)

see original thumbnails 

![screenshot 104 _li](https://cloud.githubusercontent.com/assets/20338483/21581580/38488ca0-d05d-11e6-9690-f21ef1d9c816.jpg)
