### ISSUE TITLE
tvaplus.ca: detection

### ISSUE THREAD

**Issue by maforget** [uBlockOrigin/uAssets#24303]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.tvaplus.ca/tva/en-direct
https://www.tvaplus.ca/tva/le-guide-de-l-auto-2024/saison-1/episode-22-tesla-model-3-112737582
```

### Description

Site says that playback is refused, asks to deactivate ad blocker.

I was able to fix it by adding the following exception, probably a better exception can be done but I am not an expert. But this works for me.

```adblock-filter-list
@@||api.cxense.com^$script,domain=www.tvaplus.ca
@@||cdn.cxense.com^$script,domain=www.tvaplus.ca
@@||ads.rubiconproject.com^$script,domain=www.tvaplus.ca
``` 

### Other extensions used

- HTTPS Everywhere
- Decentraleyes
- Tab Session Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![TVA Blocked](https://github.com/uBlockOrigin/uAssets/assets/11904426/42bbfcf8-7713-4d49-acd3-1257a0632a76)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 137128
 cosmetic: 46959
 scriptlet: 19960
 html: 1850
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39011-114, now
  ublock-badware: 8925-0, now
  ublock-privacy: 929-2, now
  ublock-unbreak: 2423-2, now
  ublock-quick-fixes: 109-3, now
  easylist: 86299-176, now
  easyprivacy: 51107-64, now
  urlhaus-1: 15055-0, now
  plowe-0: 3543-988, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1676 ms
 maxAssetCacheWait: 23 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mapx-** [comment]
@stephenhawk8054 Canada
