### ISSUE TITLE
cpux.net: breakage

### ISSUE THREAD

**Issue by rojona** [uBlockOrigin/uAssets#24301]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cpux.net/cpu-stress-test-online`

### Category

breakage

### Description

The stress test seems to be blocked as nothing happens when it is clicked. Ironically the ad above the test gauges does show.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 138693
 cosmetic: 49859
 scriptlet: 21648
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38915-276, 50m Δ
  ublock-badware: 8905-0, 50m Δ
  ublock-privacy: 938-0, 50m Δ
  ublock-unbreak: 2364-0, 50m Δ
  ublock-quick-fixes: 108-0, 50m Δ
  easylist: 86276-580, 50m Δ
  easyprivacy: 51106-645, 50m Δ
  urlhaus-1: 15005-0, 49m
  plowe-0: 3543-0, now
  SWE-1: 4704-8, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 746 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  hostcontent.live: 16
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||hostcontent.live^$websocket,domain=cpux.net
```

@ryanbr

**Comment by ryanbr** [comment]
Was/is a server for coin mining server, which I suspect this is done to "stress" the cpu

**Comment by stephenhawk8054** [comment]
Yeah, looks like coin miner domain

- https://x.com/anyrun_app/status/1792548060708405317
- https://forum.eset.com/topic/34974-eset-block-cpu-stress-test/?do=findComment&comment=161173
- https://xelc.app/Welcome/index.html
