### ISSUE TITLE
driveseed.org: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#24309]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://driveseed.org/file/xIEopPXGU6`

### Category

ads

### Description

ads in main page..also in next download page(video)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 110
filterset (summary):
 network: 146352
 cosmetic: 146637
 scriptlet: 29598
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5961-45, 1h.53m
 default:
  user-filters: 34-3, never
  ublock-filters: 39364-866, 1h.52m
  ublock-badware: 8948-0, 1h.52m
  ublock-privacy: 939-0, 1h.52m
  ublock-unbreak: 2367-0, 1h.52m Δ
  ublock-quick-fixes: 109-0, 1h.52m
  adguard-mobile: 9555-14, 1h.53m
  easylist: 86289-702, 1h.53m
  easyprivacy: 51112-758, 1h.52m Δ
  urlhaus-1: 15255-0, 1h.53m
  plowe-0: 3543-83, 1h.53m
filterset (user): [array of 34 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1593 ms
 maxAssetCacheWait: 510 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  dialoguemarvellouswound.com: 1
  googletagmanager.com: 3
  push-sdk.com: 1
 extended:
  ##.text-muted
  ##center > .card > .card-header
```
</details>

**Comment by mapx-** [comment]
add

`driveseed.org##[src*=".gif"]`

report at easylist repository
