### ISSUE TITLE
apkmoddone.com : nuisance

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#24313]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.apkmoddone.com/?direct=9YT8P
```

### Description

cant continue

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by Fatcavill** [comment]
there is apopup next page

**Comment by stephenhawk8054** [comment]
Next page is which page? Please describe in details with screenshots

**Comment by Fatcavill** [comment]
click not robo in dl.apkmoddone.com

**Comment by Fatcavill** [comment]
clicking get link in dl.apkmoddone.com causes a ads load faile

**Comment by Fatcavill** [comment]
with ublock on the page doesnot go to next page
`https://www.apkmoddone.com/?direct=vMoMH`

**Comment by D4niloMR** [comment]
@gorhill `nowoif` doesn't support [matching all arguments](https://github.com/gorhill/uBlock/commit/0bd4b600cf78a988b8ed677780ec258518822663) anymore? Navigating to that site is a hassle so example is not from there:

1. Open https://example.com/
2. Add `example.com##+js(nowoif, /4 _0)`
3. Reload the page and execute on console: `window.open("https://okautchalt.net/4/8443017", "_0");`

**Comment by gorhill** [comment]
The description says:

> all the arguments are joined as a single space-spearated string, and the result is used as the target for matching the pattern

So joining all the arguments results in `https://okautchalt.net/4/8443017 _0`, which won't match `/4 _0`. If you want a match with any characters in between the two argument, you need to use `/\/4.+_0/`.

**Comment by D4niloMR** [comment]
Oh ok, my bad.

**Comment by Rachitidk** [comment]
https://github.com/user-attachments/assets/397409da-ee67-4133-af94-7ba983d65f98

Not solved, reopen.

**Comment by D4niloMR** [comment]
Your device is probably blocking `https://ipinfo.io/json`. But anyway, the site is detecting at the final site even if uBO is entirely disabled.
