### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2431]
### URL(s) where the issue occurs

```
https://openload.co/embed/aqALxfqQpy0/
https://openload.co/f/aqALxfqQpy0/
```

### Describe the issue

constantly Making browser requests to some thirdparty advertiser.

### Screenshot(s)

None

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default

### Notes

The following rule should fix it and block any more pointless thidparty requests .
```
||www.vidcpm.com^$xmlhttprequest,domain=openload.co
```

**Comment by mapx-** [comment]
tested `https://openload.co/f/aqALxfqQpy0/` 
no `.pw` here

**Comment by mapx-** [comment]
tested `https://openload.pw/f/aqALxfqQpy0/` modifying `openload.co => openload.*`

**Comment by ghajini** [comment]
openload player here is giving popups here
`https://worldtvhd.net/the-tomorrow-man/`
![screenshot 117](https://user-images.githubusercontent.com/20338483/52532008-28f9db00-2d44-11e9-9d7e-699708dce389.png)

**Comment by mapx-** [comment]
I guess that behaviour is ON when the movie does not exist anymore on site.
I'll add (and you'll get a blank frame when the movie was removed)
`||openloed.co/not_found.php$frame`

**Comment by ghajini** [comment]
Add this as annoyance filter
`openload.co###M162831ScriptRootC253504`

**Comment by okiehsch** [comment]
`openload.co##[id*="ScriptRoot"]` looks better ;)
I will add it to `uBO-filters`.
`##[id*="ScriptRoot"]` is part of `EasList` but the generichide filter disables it.

**Comment by uBlock-user** [comment]
@mapx- openload.*, oload.*, streamango and streamcherry all suspended/taken over by ACE --

`https://torrentfreak.com/openload-and-others-taken-down-by-anti-piracy-alliance-ace-191031/`

**Comment by okiehsch** [comment]
`verystream.com` is also down but that could be because of all the additional traffic. 😀

**Comment by uBlock-user** [comment]
> 
> 
> `verystream.com` is also down but that could be because of all the additional traffic. 😀

It's overwhelmed by traffic as per Error 503, or it could that admin got scared and shut it down.

**Comment by okiehsch** [comment]
I am always amazed that after a shutdown other similar sites get scared.
It's like they are surprised that something like this could happen.

**Comment by uBlock-user** [comment]
>  It's like they are surprised that something like this could happen.

Anybody would get scared if it happened out of nowhere or if the lawyers tracked you down and started sending threats/cease & desist letters.

**Comment by okiehsch** [comment]
Well. yes but it comes with the territory. If you start such a service are you really surprised if it leads to legal problems?

**Comment by uBlock-user** [comment]
or it could be that they just to want to avoid any further legal repercussions and believe that if they give up, they will get away with minimum fine, like the RapidVideo admin did last week ago.
