### ISSUE TITLE
tmailweb.com: breakage

### ISSUE THREAD

**Issue by the9655a** [uBlockOrigin/uAssets#24327]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://tmailweb.com/
```

### Description

Home page contents shifted to the left due to ubo filters.

### Other extensions used

****

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 218375
 cosmetic: 254682
 scriptlet: 52130
 html: 2112
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82165-4093, 17h.36m
  adguard-mobile: 9555-57, 17h.36m
  adguard-spyware-url: 1572-120, 17h.36m
  adguard-spyware: 68807-1530, 17h.36m
  block-lan: 68-0, 11d.22h.9m
  curben-phishing: 522-6, 17h.36m
  adguard-social: 23022-55, 17h.36m
  adguard-cookies: 30184-52, 17h.36m
  ublock-cookies-adguard: 1227-14, 4d.20h.42m
  adguard-popup-overlays: 27307-1080, 17h.36m
  adguard-mobile-app-banners: 5286-26, 17h.36m
  adguard-other-annoyances: 14699-467, 17h.36m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39050-122, 35m Δ
  ublock-badware: 9070-0, 35m Δ
  ublock-privacy: 930-0, 35m Δ
  ublock-unbreak: 2425-3, 35m Δ
  ublock-quick-fixes: 110-0, 35m Δ
  easylist: 86330-2264, 35m Δ
  easyprivacy: 51115-28366, 35m Δ
  urlhaus-1: 14870-0, 17h.36m
  plowe-0: 3552-1485, 11d.22h.9m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 329 ms (selfie)
 maxAssetCacheWait: 179 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  googlesyndication.com: 13
  googletagmanager.com: 1
  shareasale.com: 4
 extended:
  ##.row > div[class^="col-"]:has(> div.d-none > ins.adsbygoogle)
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]

```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
it seems to be due to

`tmailweb.com##.row > div[class^="col-"]:has(> div.d-none > ins.adsbygoogle)`

in AdGuard – Mobile Ads

@Yuki2718
