### ISSUE TITLE
censor.net: [unknown] - blank page when trying to access the recent activity page

### ISSUE THREAD

**Issue by YumbaMumba** [uBlockOrigin/uAssets#24326]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://censor.net/ua/activity`

### Category

[unknown]

### Description

Blank page when trying to access the recent activity page

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-07-01_113835](https://github.com/uBlockOrigin/uAssets/assets/62180023/642361bb-c60f-4c62-9891-47b7943c1645)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 155614
 cosmetic: 67449
 scriptlet: 21465
 html: 1867
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39067-114, 1h.2m Δ
  ublock-badware: 9070-0, 1h.2m Δ
  ublock-privacy: 930-2, 1h.2m Δ
  ublock-unbreak: 2425-2, 1h.2m Δ
  ublock-quick-fixes: 110-5, 1h.2m Δ
  easylist: 86335-179, 1h.2m Δ
  easyprivacy: 51116-64, 1h.2m Δ
  urlhaus-1: 14790-0, 54m
  plowe-0: 3543-988, 54m
  RUS-0: 40673-147, 1h.2m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8004 ms (selfie)
 maxAssetCacheWait: 2111 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Don't open duplicated issue

**Comment by YumbaMumba** [comment]
Sorry, I must've misuderstood you.

I still don't get it. What exactly am I supposed to do?

1) Reproduce the issue
2) Click on the Ublock icon in the browser
3) Click on 'Report a problem with this site'
4) Fill out a form
5) Submit a report

Is that it? If it is, then where do I put the information you asked me for?



пн, 1 июл. 2024 г. в 11:50, stephenhawk8054 ***@***.***>:

**Comment by stephenhawk8054** [comment]
> 4) Fill out a form
> 5) Submit a report

No, I didn't tell you to do these steps. These are the steps I told you: https://github.com/uBlockOrigin/uAssets/issues/24324#issuecomment-2199456453

1. Open new tab
2. reproduce the issue
3. on that page > click on uBO icon
4. Click on 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools)
5. scroll to the bottom
6. click on `Troubleshooting Information` 
7. copy paste it here

Because from the troubleshooting information, there are nothing blocked on your side

```yml
popupPanel:
 blocked: 0
```

On that page, can you click on uBO and screenshot the panel, and copy paste the screenshot to your old thread? Don't continue in this thread, and please, don't reply via email.
