### ISSUE TITLE
censor.net: breakage

### ISSUE THREAD

**Issue by YumbaMumba** [uBlockOrigin/uAssets#24324]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://censor.net/ua/activity
```

### Description

I get a blank page when trying to access the recent activity page. Other users are also reporting this isuue.

### Other extensions used

No other extensions used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-07-01_101733](https://github.com/uBlockOrigin/uAssets/assets/62180023/5a9958c2-87c0-4f7d-8156-0215cbe48013)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Please don't remove the troubleshooting information in the report.

Open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here.

**Comment by YumbaMumba** [comment]
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 155614
 cosmetic: 67449
 scriptlet: 21465
 html: 1867
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39067-114, 9m Δ
  ublock-badware: 9070-0, 9m Δ
  ublock-privacy: 930-2, 9m Δ
  ublock-unbreak: 2425-2, 9m Δ
  ublock-quick-fixes: 110-5, 9m Δ
  easylist: 86335-179, 9m Δ
  easyprivacy: 51116-64, 9m Δ
  urlhaus-1: 14790-0, 1m
  plowe-0: 3543-988, 1m
  RUS-0: 40673-147, 9m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8004 ms (selfie)
 maxAssetCacheWait: 2111 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0

пн, 1 июл. 2024 г. в 10:41, stephenhawk8054 ***@***.***>:

**Comment by YumbaMumba** [comment]
Apologies for that.

Did I get it right this time?

пн, 1 июл. 2024 г. в 10:47, John Doe ***@***.***>:

**Comment by stephenhawk8054** [comment]
I mean, reproducing the issue first, then click on uBO icon to get the troubleshooting information right at that page.

And please don't reply via email.

**Comment by YumbaMumba** [comment]
**@stephenhawk8054**

_On that page, can you click on uBO and screenshot the panel, and copy paste the screenshot to your old thread?_ 

![2024-07-01_121548](https://github.com/uBlockOrigin/uAssets/assets/62180023/125ebc83-9d05-4ce4-a226-e6894aee0cfb)

Is that the panel you were rteferring to?

**Comment by stephenhawk8054** [comment]
Can you click on the eye icon under the power button?

**Comment by YumbaMumba** [comment]
![2024-07-01_122044](https://github.com/uBlockOrigin/uAssets/assets/62180023/d2f22a77-6f3a-4827-8f80-e9ea3a6e8f81)

**Comment by YumbaMumba** [comment]
Nope ((

**Comment by stephenhawk8054** [comment]
What happens if you click on the power button to turn off uBO?

**Comment by YumbaMumba** [comment]
Just a blank page.

Let me just add that I'm not the only one reporting this issue.

**Comment by YumbaMumba** [comment]
> What happens if you click on the power button to turn off uBO?

Nothing. Just a blank page

**Comment by stephenhawk8054** [comment]
I know. It means that uBO is not the one causing the issue.

Can you go to `about:addons` page, turn off uBO and test again?

**Comment by YumbaMumba** [comment]
Nothing :(

**Comment by stephenhawk8054** [comment]
Then it's not uBO issue.

**Comment by YumbaMumba** [comment]
The interesting thing is that I'm experiencing the same problem on my tablet

**Comment by stephenhawk8054** [comment]
Yeah, please contact that website instead.
