### ISSUE TITLE
freedompop.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#24331]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freedompop.com/contact-us`

### Category

breakage

### Description

Chatbot icon isn't visible even though I have widgets and chat filters disabled. 

### Other extensions used

FastForward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1680" alt="Screen Shot 2024-07-01 at 11 37 47 AM" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/5caaa234-9e7d-4534-8a93-925d159bb833">
<img width="1680" alt="Screen Shot 2024-07-01 at 11 38 00 AM"src="https://github.com/uBlockOrigin/uAssets/assets/69532417/52a78e82-06b2-40e5-9377-bc708b7af2d0">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 207768
 cosmetic: 234150
 scriptlet: 53848
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 80123-77569, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99942-83643, now
  adguard-cookies: 30208-86, now
  adguard-generic: 82166-7209, now
  adguard-mobile: 9558-107, now
  adguard-mobile-app-banners: 5292-1117, now
  adguard-other-annoyances: 14700-364, now
  adguard-popup-overlays: 27332-907, now
  adguard-spyware: 69638-29055, now
  adguard-spyware-url: 1572-5, now
  block-lan: 68-0, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 86337-604, now Δ
  easyprivacy: 51116-746, now Δ
  plowe-0: 3543-0, now
  ublock-badware: 9078-3, now Δ
  ublock-filters: 38965-709, now Δ
  ublock-privacy: 947-115, now Δ
  ublock-quick-fixes: 113-0, now Δ
  ublock-unbreak: 2366-3, now Δ
  urlhaus-1: 14945-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5965 ms
 maxAssetCacheWait: 2062 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  hs-scripts.com: 1
  livechatinc.com: 1
  mplxtms.com: 1
  truevaultcdn.com: 2
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(set-constant, rwt, noopFunc)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by mapx-** [comment]
you have enabled [AdGuard Annoyances filter](https://filters.adtidy.org/extension/ublock/filters/14.txt) which contains widgets and chat filters

add
`@@||secure.livechatinc.com/customer/action/open_chat$frame,domain=freedompop.com`

**Comment by jimmysofat6864** [comment]
> you have enabled [AdGuard Annoyances filter](https://filters.adtidy.org/extension/ublock/filters/14.txt) which contains widgets and chat filters
> 
> add `@@||secure.livechatinc.com/customer/action/open_chat$frame,domain=freedompop.com`

@mapx- I have widgets disabled for this exact reason so I don't know why it leaked in. 


<img width="719" alt="Screen Shot 2024-07-01 at 12 02 44 PM" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/65ea916a-94d5-43e7-9dcd-205046a6a40e">

**Comment by mapx-** [comment]
you added 

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/cc834178-8b42-458c-abfb-5eac92d69c5d)

disable it

**Comment by jimmysofat6864** [comment]
> you added
> 
> ![image](https://private-user-images.githubusercontent.com/10303732/344784326-cc834178-8b42-458c-abfb-5eac92d69c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NjU0MDAsIm5iZiI6MTcxOTg2NTEwMCwicGF0aCI6Ii8xMDMwMzczMi8zNDQ3ODQzMjYtY2M4MzQxNzgtOGI0Mi00NThjLWFiZmItNWVhYzkyZDY5YzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIwMTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZjBiZWUyM2I4ZmVmZTgwMzVmZTQ1YWNkMDUzMmE5M2NmYjI2NzE2N2JiYzYzZjgyZjIwYTZjYjVkMGNiMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QgByl7s99H4WJlo36g2PcyGtEUn4_C4lANewx_d8BIE)
> 
> disable it

I reset uBlock origin and removed all filter lists and then added it all back manually. I also made sure that the widgets section isn't checked marked. I still have the same issue. Refer to my new configuration below. 

<img width="1037" alt="Screen Shot 2024-07-01 at 1 24 36 PM" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/04cae38f-6ab0-4e9b-b3b6-c1c8688be6d5">

<img width="709" alt="Screen Shot 2024-07-01 at 1 24 45 PM" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/3c4e0caf-3eb8-4785-93e1-b27a1fd9d4cd">




### Configuration

<details>

```
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 217124
 cosmetic: 216795
 scriptlet: 53842
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82297-7216, never
  adguard-mobile: 9558-187, never
  adguard-spyware-url: 1572-120, never
  adguard-spyware: 69638-29056, never
  block-lan: 68-0, never
  curben-phishing: 537-3, never
  adguard-cookies: 30208-3804, never
  ublock-cookies-adguard: 1247-1219, never
  fanboy-cookiemonster: 51281-223, never
  ublock-cookies-easylist: 1227-0, never
  adguard-popup-overlays: 27332-1046, never
  adguard-mobile-app-banners: 5292-1119, never
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 38966-373, 3m
  ublock-badware: 9078-0, 3m
  ublock-privacy: 947-0, 3m
  ublock-unbreak: 2366-0, 3m
  ublock-quick-fixes: 113-0, 3m
  easylist: 86337-473, 3m
  easyprivacy: 51116-638, 3m
  urlhaus-1: 14945-0, 3m
  plowe-0: 3543-0, 3m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2037 ms
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  hs-scripts.com: 1
  livechatinc.com: 1
  mplxtms.com: 1
  truevaultcdn.com: 2
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by mapx-** [comment]
[AdGuard Tracking Protection](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-spyware) issue too

add
`@@||cdn.livechatinc.com/tracking.js$script,domain=freedompop.com`

**Comment by jimmysofat6864** [comment]
When will this be fixed in an AdGuard list?

**Comment by jimmysofat6864** [comment]
> AdGuard Tracking Protection issue too
> 
> add `@@||cdn.livechatinc.com/tracking.js$script,domain=freedompop.com`

Can you reopen the issue until it is fixed by adguard?

**Comment by D4niloMR** [comment]
You can report at https://github.com/AdguardTeam/AdguardFilters
