### ISSUE TITLE
techedubyte.com: detection

### ISSUE THREAD

**Issue by tetoksn** [uBlockOrigin/uAssets#24337]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.techedubyte.com/`

### Category

detection

### Description

AdBlock detection while scrolling

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-07-02-09-43-45-026](https://github.com/uBlockOrigin/uAssets/assets/131806396/648a09ce-880e-4e5b-9a6c-5b55a16fdc4d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 216903
 cosmetic: 221759
 scriptlet: 53883
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  VIE-1: 1960-0, 6m
  adguard-cookies: 30208-70, 6m
  adguard-generic: 82297-7228, 6m
  adguard-other-annoyances: 14700-369, 4m
  adguard-popup-overlays: 27332-940, 4m
  adguard-spyware: 69638-29095, 6m
  adguard-spyware-url: 1572-5, 6m
  block-lan: 68-0, 2m
  curben-phishing: 540-0, 31m
  dpollock-0: 11688-458, 2m
  easylist-annoyances: 4687-95, 2m
  easylist-chat: 198-0, 2m
  [8 lists not shown]: [too many]
 default:
  easylist: 86337-835, 6m
  easyprivacy: 51125-854, 2m
  plowe-0: 3543-0, 2m
  ublock-badware: 9048-3, 2m
  ublock-filters: 38969-609, 2m
  ublock-privacy: 947-114, 2m
  ublock-quick-fixes: 116-0, 2m
  ublock-unbreak: 2366-3, 2m
  urlhaus-1: 14835-0, 30m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 18 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3761 ms (selfie)
 maxAssetCacheWait: 945 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  doubleclick.net: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##.gmr-floatbanner
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##iframe[name="googlefcPresent"]
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.adsbygoogle-noablate
  ##+js(noeval-if, /chp_?ad/)
  ##+js(set-constant, checkAdsStatus, noopFunc)
  ##+js(noeval-if, deblocker)
  ##+js(prevent-fetch, googlesyndication)
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
```
</details>

**Comment by huyszn** [comment]
I still get detected, for example, when clicking the `Click Here` link next to `Cookies 1` on `https://www.techedubyte.com/canva-cookies/`. It redirects to `https://www.techedubyte.com/` where you get the detection message.
