### ISSUE TITLE
atwiki.jp: breakage / ads

### ISSUE THREAD

**Issue by r4oz8** [uBlockOrigin/uAssets#24330]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://w.atwiki.jp/aniwotawiki/
https://w.atwiki.jp/gtav/
```

### Description

The access counter in the left sidebar is not loading on both links.
This seems to happen on all sites related to "atwiki.jp".

In addition, only on the second link (https://w.atwiki.jp/gtav/*), affiliate link text and banners are displayed within the main content and at the bottom of the left sidebar.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139084
 cosmetic: 59703
 scriptlet: 21625
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38963-289, 33m Δ
  ublock-badware: 9068-0, 33m Δ
  ublock-privacy: 947-0, 33m
  ublock-unbreak: 2366-0, 33m Δ
  ublock-quick-fixes: 113-0, 33m Δ
  easylist: 86337-586, 33m Δ
  easyprivacy: 51116-638, 33m Δ
  urlhaus-1: 14790-0, 33m
  plowe-0: 3552-0, 7d.17h.57m
  JPN-1: 14877-49, 1d.3h.58m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 368 ms
 maxAssetCacheWait: 139 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
You can use this as custom filter

```adb
@@||w.atwiki.jp/common/dist/js/counter.js$script,1p
```

The connection sends and tracks user's cookie ID as well, so I don't think it should be unblocked.

**Comment by r4oz8** [comment]
I understand. Thank you.

**Comment by r4oz8** [comment]
Excuse me, what about the second issue I mentioned?

> In addition, only on the second link (https://w.atwiki.jp/gtav/*), affiliate link text and banners are displayed within the main content and at the bottom of the left sidebar.

**Comment by stephenhawk8054** [comment]
```adb
w.atwiki.jp###wikibody a[href^="https://amzn.to/"]
w.atwiki.jp###wikibody a[href^="https://hb.afl.rakuten.co.jp/"]
w.atwiki.jp###wikibody a[href^="https://px.a8.net/"]
```

@Yuki2718 For Adguard JP?

**Comment by r4oz8** [comment]
I'm not sure if this is subject to blocking, but on the website 'https://w.atwiki.jp/gtav', Amazon affiliate links with the leading 'h' removed are being posted.
This seems to be done intentionally.

![ss](https://github.com/user-attachments/assets/17ba1e6f-f77e-43e6-b5b6-6d1c888e1129)

**Comment by Yuki2718** [comment]
As user have to manually copy and paste the affiliate links, I'll leave them for now.

**Comment by r4oz8** [comment]
It appears that the text and banner for affiliate links are also displayed on the following page.
https://w.atwiki.jp/anime_wiki

**Comment by Yuki2718** [comment]
> It appears that the text and banner for affiliate links are also displayed on the following page. https://w.atwiki.jp/anime_wiki

They have pages for producets like `https://w.atwiki.jp/anime_wiki/pages/14326.html`. Hid only irrelevant items.
