### ISSUE TITLE
windguru.cz

### ISSUE THREAD

**Issue by Francois-dag** [uBlockOrigin/uAssets#2433]
### URL(s) where the issue occurs

https://www.windguru.cz/9417
### Describe the issue
 ....
Advertising can be annoying, but allows Windguru to offer weather information for free. We use ad networks from Google and other partners who can collect personal data in order to show you more relevant ads. Personalized ads are disabled by default for EU users, but enabling personalized ads can provide better experience for you and helps us to keep free content easier. Find more information in our Terms & Privacy Policy (links open a new window) 

....

### Versions

- Browser/version: last firefox 60.0.1
- uBlock Origin version: 1.16.8

### Settings

tryed with the following (does not work)

windguru.cz###jBoxId9
windguru.cz##jBox-container

### Notes
cheers !

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.

**Comment by Khrin** [comment]
@okiehsch Just for curiosity, why the generichide filter?

**Comment by Khrin** [comment]
Understood. Thank you.
