### ISSUE TITLE
[NSFW] avxhm.se: ads

### ISSUE THREAD

**Issue by 65wat** [uBlockOrigin/uAssets#24344]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
NSFW
https://avxhm.se/
```

### Description

Big ad for generative AI website - highlighted in red rectangle.
If this isn't fitting for inclusion to ads filter lists, it may possibly be added to annoyances filter.
Site is intl/english, .se domain is only used for legal reasons.

### Other extensions used

ClearURLs
Return YouTube Dislike
LibRedirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**NSFW**
https://i.postimg.cc/RV8w6G9C/avxhm.png

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 271038
 cosmetic: 321298
 scriptlet: 56064
 html: 2210
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 80010-140, 3d.21h.46m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 12h.41m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, 12h.41m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 99981-23319, 4d.22h.35m
  adguard-generic: 82161-4099, 3d.21h.46m
  fanboy-thirdparty_social: 68-16, 4d.22h.35m
  fanboy-social: 16321-16321, 3d.19h.45m
  ublock-annoyances: 5878-252, 12h.42m Δ
  dpollock-0: 11686-386, 11d.14h.12m
  ara-0: 2335-31, 12h.41m
  CHN-0: 26443-226, 3d.21h.46m
  CZE-0: 834-35, 12h.41m
  [28 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  ublock-filters: 39069-447, 12h.42m Δ
  ublock-badware: 9050-0, 12h.42m Δ
  ublock-privacy: 938-4, 12h.42m Δ
  ublock-unbreak: 2425-7, 12h.42m Δ
  ublock-quick-fixes: 116-5, 9m
  easylist: 86338-2332, 12h.42m Δ
  adguard-spyware-url: 1571-120, 3d.21h.45m
  easyprivacy: 51123-317, 12h.42m Δ
  urlhaus-1: 14945-0, 12h.41m
  curben-phishing: 537-3, 12h.41m
  plowe-0: 3552-1373, 11d.14h.12m
  LegitimateURLShortener: 2656-162, 9m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms (selfie)
 maxAssetCacheWait: 202 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
```adb
avxhm.se##[data-localize]:has(a[href^="https://canv.ai/"])
```

@ryanbr

**Comment by stephenhawk8054** [comment]
```adb
avxhm.se##[data-localize]:has(a[href^="https://icerbox.com/"])
```

@ryanbr
