### ISSUE TITLE
qidiantu.com: breakage

### ISSUE THREAD

**Issue by hdloader11** [uBlockOrigin/uAssets#24346]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.qidiantu.com/`

### Category

breakage

### Description

Entire site seems to break when uBlock Origin is enabled, with the UI elements becoming text only.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 152709
 cosmetic: 221808
 scriptlet: 33209
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7509-3, 11m
  NLD-0: 2310-39, now
  TUR-0: 13226-14, now
  adguard-cookies: 30232-67, now
  adguard-mobile-app-banners: 5295-1117, now
  adguard-other-annoyances: 14705-318, now
  adguard-popup-overlays: 27339-885, now
  adguard-social: 23033-1659, now
  adguard-widgets: 2591-44, now
  easylist-annoyances: 4690-95, 10m
  easylist-chat: 198-0, 10m
  easylist-newsletters: 7406-15, 10m
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 86352-659, 11m Δ
  easyprivacy: 51125-746, 11m Δ
  plowe-0: 3543-0, now
  ublock-badware: 9091-0, 11m Δ
  ublock-filters: 38977-629, 11m Δ
  ublock-privacy: 1027-2, 11m Δ
  ublock-quick-fixes: 117-0, 11m Δ
  ublock-unbreak: 2366-4, 11m Δ
  urlhaus-1: 15055-5, 11m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 334 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  bootcdn.net: 3
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ###ad-slot
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
The domain `bootcdn.net` being blocked in the site belongs to `polyfill.io` who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.

**Comment by chinazyq123** [comment]
However, thousands of Chinese websites use mirrors to achieve better webpage loading speeds. Adding them to the blocked directory may have a significant impact
