### ISSUE TITLE
[nsfw] datexurlove.com: ads

### ISSUE THREAD

**Issue by JoseGonzalezCircus** [uBlockOrigin/uAssets#24342]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://datexurlove.com/gms2/?domain=%7Bsource%7D`

### Category

ads

### Description

When I try to enter to Gmail (www.gmail.com), sometimes I have written it wrongly, gmai.com. Normally I would expect an error or that autocomplete make it works. But basically I arrive to a nasty and fake webpage of "dates" (https://datexurlove.com/gms2/?domain=%7Bsource%7D).
![screencapture-datexurlove-gms2-2024-07-02-11_35_20](https://github.com/uBlockOrigin/uAssets/assets/159544651/03654c82-5caa-410c-81b5-6a3f69bd26c2)

### Other extensions used

- GoFullPage - Full Page Screen Capture: https://chromewebstore.google.com/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl

- Auto Refresh Plus | Page Monitor: https://chromewebstore.google.com/detail/auto-refresh-plus-page-mo/hgeljhfekpckiiplhkigfehkdpldcggm

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 137167
 cosmetic: 47112
 scriptlet: 21520
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86349-567, 8m Δ
  easyprivacy: 51125-638, 8m Δ
  plowe-0: 3543-0, now
  ublock-badware: 9111-0, 8m Δ
  ublock-filters: 38969-279, 8m Δ
  ublock-privacy: 1026-2, 8m Δ
  ublock-quick-fixes: 116-0, 8m Δ
  ublock-unbreak: 2366-0, 8m Δ
  urlhaus-1: 14835-0, 8m
filterset (user): [empty]
trustedset:
 added: [array of 37 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 538 ms (selfie)
 maxAssetCacheWait: 183 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  google.com: 7
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check again exactly which typo you entered that redirected to the above page? I tried `gmai.com` but it leads to `http://iyfbodn.com/?dn=gmai.com&pbsubid=1e6d6bd1-13a1-4564-9aec-3c38fcb584c5&pid=9POT3387I` which is blocked by uBO.

**Comment by JoseGonzalezCircus** [comment]
Hello,

Well, right now it doesn't redirect to anything because it's blocked after
the report. But before, gmai.com redirected me to the url that I described
in the issue (https://datexurlove.com/gms2/?domain=%7Bsource%7D).

Best regards,
Jose Sanchez

**Comment by JoseGonzalezCircus** [comment]
Sorry, I was wrong.

   - If I enter www.gmai.com, it tries to redirect to:
   https://datexurlove.com/gms2/?domain=%7Bsource%7D
   - If I enter ww1.gmai.com, it tries to redirect to the link that you
   pointed:
   https://iyfbodn.com/?dn=gmai.com&pbsubid=49d52c93-0679-4f9f-aff7-1ec6f113bdad&pid=9POT3387I


Checking the historial I can see that there are several redirects before
arrive the destination (all of them blocked):

   -
   https://iovia-pmj.com/zclkvisitor/ce0f4ea5-3855-11ef-9ed7-12e32186f081/b4fe5730-c930-11e7-a121-0ad5c55a6ed0?campaignid=ce1b0e73-3855-11ef-9ed7-12e32186f081
   -
   https://tq.starvalue-4.online/filter?q=gmai%2Cgmai.com%2Cgmail%2Cemail%2Cemail+accounts&i=fZt4f6KEWt8_0&ci=-3072103106717919453&t=1279833070&h=30
   -
   https://track.auroraveil.bid/proceed.php?domain=gmai.com&hash=e411fec004da43db0c9d845c29828adb&u=eyJkb21haW4iOiJnbWFpLmNvbSIsImRvbWFpbl9pZCI6Ijc0NTc5NCIsImZvbGRlcl9pZCI6bnVsbCwibWlkIjoiMTUxIiwiZmlsdGVyX2lkIjpudWxsLCJhZHZlcnRpc2VyX2lkIjoiMTI4IiwidGFyZ2V0IjoiaHR0cDpcL1wveG1sLXY0LnN0YXJ2YWx1ZS00Lm9ubGluZVwvY2xpY2s/aT0xbzd2ekJlckc4c18wIiwiaXBfYWRkcmVzcyI6IjIxMy42MS4xMTguMjI2IiwidHlwZSI6ImphdmFfcmVkaXJlY3QiLCJiaWQiOiIwLjAyOCJ9


Also I notice that the domain https://datexurlove.com/ is blocked, but the
subdomain https://datexurlove.com/gms2 is still available. How can I block
it?

Best Regards,
Jose Sanchez
