### ISSUE TITLE
instacart.ca: ads

### ISSUE THREAD

**Issue by github72933** [uBlockOrigin/uAssets#24355]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.instacart.ca/store/real-canadian-superstore/storefront`

### Category

ads

### Description

There are large advertisements (some with video) on Instacart that are not detected by the adblocker

![mTJCE1F](https://github.com/uBlockOrigin/uAssets/assets/174573634/3326294e-e2a1-4987-b279-ef0945f07183)

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 156080
 cosmetic: 97219
 scriptlet: 43379
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82359-503, 6m
  adguard-mobile: 9559-128, 6m
  ublock-annoyances: 5935-55, 1h.49m
 default:
  user-filters: 108-5, never
  easylist: 86376-2557, 1h.49m
  easyprivacy: 51129-757, 1h.49m
  plowe-0: 3543-25, 1h.49m
  ublock-badware: 8662-109, 1h.49m
  ublock-filters: 38968-3727, 1h.49m
  ublock-privacy: 1027-2, 1h.49m
  ublock-quick-fixes: 117-2, 1h.49m
  ublock-unbreak: 2366-78, 1h.49m
  urlhaus-1: 14800-5, 1h.49m
filterset (user): [array of 110 redacted]
trustedset:
 added: [array of 19 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 contextMenuEnabled: false
 largeMediaSize: 1000
hiddenSettings: [none]
supportStats:
 allReadyAfter: 184 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  instacart.ca: 1
  d2lxqodqbpy7c2.cloudfront.net: 1
  forter.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
  sentry.io: 1
 extended:
  ##.e-19ewqfx
```
</details>

**Comment by github72933** [comment]
This issue has returned, this type of advertisement is no longer being blocked

![image](https://github.com/user-attachments/assets/4599e9b4-7b6a-4b12-aef4-ca280f34c937)

**Comment by stephenhawk8054** [comment]
@github72933 Please give exact URL where you see the issue.

**Comment by github72933** [comment]
The ads are appearing on this URL and on each other store

https://www.instacart.ca/store/real-canadian-superstore/storefront

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
instacart.ca##ul > div:has(> li[data-testid^="item_list"] img[alt="This is a boosted product paid for by advertisers"])
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by github72933** [comment]
The filter doesn't seem to change anything

**Comment by github72933** [comment]
Sadly they're still appearing

**Comment by stephenhawk8054** [comment]
I can't reproduce with the above filter any more. They match the sponsored posts on my side so I can't investigate more

![image](https://github.com/user-attachments/assets/5eb3346c-1f0c-4e77-b15f-d4f4b57d13cb)

I'm signing in to the site btw.

**Comment by github72933** [comment]
Those sponsored products are gone for me too, thank you! Just have these large sized ads still.

![heLKB8Y](https://github.com/user-attachments/assets/22cdfa51-a0f1-45c4-af66-90687c4110a2)

**Comment by stephenhawk8054** [comment]
Ok, I misunderstood the issue. But I still can't see that section even though I tried to scroll down a lot. It just looks like this to me

![image](https://github.com/user-attachments/assets/f07a0bb2-509b-4017-a681-64b10c65fe10)

**Comment by github72933** [comment]
Weird, maybe they're only rolled out in select regions or to certain users
