### ISSUE TITLE
anek.gr: nuisance

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#24358]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.anek.gr/
https://www.anek.gr/en-gb
```

### Description

when I try to make a new booking most of the fields (if not all of them) are marked with the following css:
class="e-prevent-paste"
I can't figure out how they do it but pasting is blocked,
can someone help re-enable again?
thanks a lot!

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
anek.gr##+js(rc, e-prevent-paste, .e-prevent-paste)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by patrickdrd** [comment]
no, it doesn't work, still can't paste here for example:
![image](https://github.com/uBlockOrigin/uAssets/assets/24896778/9ba3d8e0-e8be-431b-b7f0-4e4b9d137a8a)

**Comment by stephenhawk8054** [comment]
You removed your configuration report before submitting the issue.

Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by patrickdrd** [comment]
yes, sure, I got other filters too, sorry (and a bit previous ver too) :(

uBlock Origin: 1.47.4
Chromium: 118
filterset (summary): 
  network: 381852
  cosmetic: 139319
  scriptlet: 41952
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/: 25840-4, 2d.19h.28m
    https://cdn.adblockcdn.com/filters/adblock_custom.txt: 29-0, 2d.23h.52m
    https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, 2d.19h.30m
    https://crapblock.theel0ja.info/crapblock-annoyances.txt: 0-0, never
    https://fanboy.co.nz/fanboy-problematic-sites.txt: 0-0, 22h.49m
    https://filters.adtidy.org/android/filters/15_optimized.txt: 67602-15, 2d.19h.32m
    https://filters.adtidy.org/extension/chromium/filters/11.txt: 9397-812, 9d.1m
    https://filters.adtidy.org/extension/chromium/filters/2.txt: 148282-41977, 9d.2m
    https://filters.adtidy.org/extension/chromium/filters/3.txt: 67629-4865, 9d.3m
    https://gist.githubusercontent.com/balupton/6960605/raw/16bfeff88761b16296ed3ee15fbacf6840f1701a/filter-feedlyads.txt: 5-0, 3d.4m
    https://gist.githubusercontent.com/patrickdrd/a843a86d78e5a9827025958f1827643b/raw/chefkoch.txt: 19558-4606, 3d.3m
    https://gist.githubusercontent.com/patrickdrd/bec5b4727c3740d2ad7da830aaa19d96/raw/filters.txt: 3085-36, 1d.15m
    https://gist.githubusercontent.com/patrickdrd/c13b1fde771aeedc079dc18ae79dbb59/raw/hosts.txt: 214753-67527, 22h.37m
    https://github.com/reek/anti-adblock-killer/raw/master/anti-adblock-killer-filters.txt: 2196-43, 22h.40m
    https://raw.github.com/liamja/Prebake/master/obtrusive.txt: 1072-236, 22h.51m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 759-8, 22h.34m
    https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt: 3891-80, 22h.48m
    https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt: 651-75, 3d.1m
    https://raw.githubusercontent.com/LordBadmintonofYorkshire/Overlay-Blocker/master/blocklist.txt: 50-0, 22h.57m
    https://raw.githubusercontent.com/Manu1400/i-don-t-care-about-newsletters/master/adp.txt: 94-0, 22h.42m
    [23 lists not shown]: [too many]
  default: 
    user-filters: 1-0, never
    easylist: 86337-86055, 1d.17h.54m
    easyprivacy: 51124-30257, 1d.17h.55m
    ublock-badware: 9007-174, 2d.23h.55m
    ublock-filters: 37303-3640, 2d.23h.54m
    ublock-privacy: 963-71, 22h.50m
    ublock-quick-fixes: 117-9, 16m
    ublock-unbreak: 2361-135, 2d.23h.53m
    urlhaus-1: 14800-0, 22h.36m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 5 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  collapseBlocked: false
modifiedHiddenSettings: 
  selfieAfter: 11
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 3473 ms (selfie)
  maxAssetCacheWait: 863 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1

**Comment by stephenhawk8054** [comment]
You are using an version of uBO, old version of browser and also using a heavily modified configuration too.

I can't help more. Good luck.
