### ISSUE TITLE
dailythanthi.com: ads

### ISSUE THREAD

**Issue by Ramar121** [uBlockOrigin/uAssets#24350]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.dailythanthi.com
```

### Description

Getting blank spaces in the ad blocked areas 

### Other extensions used

Violetmonkey

### Screenshot(s)

![Screenshot 2024-07-03 014323](https://github.com/uBlockOrigin/uAssets/assets/146962304/b2064187-0c77-4a6e-88de-01179d452aa8)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 325918
 cosmetic: 256865
 scriptlet: 52264
 html: 2115
listset (total-discarded, last-updated):
 removed:
  IND-0: null
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 436-3, 2d.51m
  https://raw.githubusercontent.com/iam-py-test/uBlock-combo/main/list.txt: 120754-1141, 14h.8m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1191-34, 6h.36m
  adguard-generic: 82174-6282, 4d.1h.59m
  adguard-mobile: 9550-129, 4d.4h
  adguard-spyware-url: 1571-239, 4d.1h.59m
  adguard-spyware: 68803-29711, 4d.1h.59m
  block-lan: 68-0, 6d.13h.39m
  curben-phishing: 540-2, 14h.8m
  adguard-social: 23031-56, 15h.9m
  adguard-cookies: 30179-48, 4d.1h.59m
  ublock-cookies-adguard: 1227-14, 5d.3h.38m
  [12 lists not shown]: [too many]
 default:
  user-filters: 190-24, never
  ublock-filters: 39083-114, 3h.8m Δ
  ublock-badware: 8673-0, 3h.8m Δ
  ublock-privacy: 1018-60, 3h.8m Δ
  ublock-unbreak: 2425-2, 3h.8m Δ
  ublock-quick-fixes: 117-7, 3h.8m Δ
  easylist: 86363-170, 3h.8m Δ
  easyprivacy: 51126-61, 3h.8m Δ
  urlhaus-1: 14835-5, 14h.9m
  plowe-0: 3552-1160, 12d.4h.29m
filterset (user): [array of 191 redacted]
trustedset:
 added: [array of 77 redacted]
switchRuleset:
 added: [array of 38 redacted]
hostRuleset:
 added: [array of 302 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 842 ms (selfie)
 maxAssetCacheWait: 594 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
dailythanthi.com##.popup-ad-content-wrap
dailythanthi.com##.bottom_snackbar_common
dailythanthi.com##.header_ad
dailythanthi.com##.inside-post-ad
```

@mediumkreation Sorry, can you check this?

**Comment by Ramar121** [comment]
No the filters didn't work. Remains the same with the blank spaces getting through

**Comment by stephenhawk8054** [comment]
Does continue adding this work?

```adb
dailythanthi.com##.to-be-async-loaded-ad:has(.hocal-ad)
```

**Comment by Ramar121** [comment]
Thanks guys. It worked👍

**Comment by mapx-** [comment]
@Ramar121 

report here: https://github.com/mediumkreation/IndianList/issues
