### ISSUE TITLE
adguard.com + adguard-vpn.com: Cookie prompt bar

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#24359]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://reports.adguard.com/en/new_issue.html
https://adguard.com/en/welcome.html
https://adguard-vpn.com/en/android/overview.html
```

### Description

Sticky cookie prompt on bottom. I propose `adguard.*,adguard-vpn.com##.cookie-terms`

For logistical reasons, AdGuard Cookie Notices Filter and uAssets Cookie Notices were also turned on during the testing, whereas EasyList Cookie List was not turned on; as albeit the lattermost list has fixed it already, I (unfortunately?) don't currently have plans to enable 3 cookie lists at the same time to remove all cookie prompts.

And my usual strategy of submitting the reports to AdGuard's issue tracker(s) would be impractical for this particular issue report, as there is of course a conflict of interest when it's about their own site.

### Other extensions used

None that I'm aware of.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/22780683/51c030ac-8ab6-4a67-8f22-d26994eda8be)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.58.1b11
Chromium: 126
filterset (summary):
 network: 140926
 cosmetic: 74127
 scriptlet: 23823
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30236-51, 11m
  ublock-cookies-adguard: 1249-0, 11m
 default:
  user-filters: 0-0, never
  ublock-filters: 38997-278, 11m
  ublock-badware: 8703-0, 11m
  ublock-privacy: 1027-2, 11m
  ublock-unbreak: 2366-0, 11m
  ublock-quick-fixes: 117-0, 11m
  easylist: 86383-565, 11m
  easyprivacy: 52708-638, 11m
  urlhaus-1: 15240-5, 11m
  plowe-0: 3543-0, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1530 ms
 maxAssetCacheWait: 15 ms
 cacheBackend: indexedDB

```
</details>    

(If it was to be of interest, the exact browser is Vivaldi 6.8.3381.46 64-bit, and not Chromium or Chrome as such.)

**Comment by mapx-** [comment]
> don't currently have plans to enable 3 cookie lists at the same time to remove all cookie prompts

use a custom filter
