### ISSUE TITLE
metric.sonix.network: breakage

### ISSUE THREAD

**Issue by bluecmd** [uBlockOrigin/uAssets#24351]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://metric.sonix.network/grafana/d/jKdZekQ4z/overview?orgId=1&refresh=1m`

### Category

breakage

### Description

As per https://github.com/easylist/easylist/issues/19380 this is an EasyList false positive, but the EasyList community seems unwilling to fix this.

This breaks self-hosted Grafana instances.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149442/82c835f2-0e09-4f61-b5dc-887bb91f5334)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 136925
 cosmetic: 46993
 scriptlet: 20123
 html: 1851
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39076-113, now
  ublock-badware: 8664-0, now
  ublock-privacy: 1018-4, now
  ublock-unbreak: 2425-2, now
  ublock-quick-fixes: 117-5, now
  easylist: 86376-174, now
  easyprivacy: 51129-65, now
  urlhaus-1: 15055-5, now
  plowe-0: 3543-988, now
filterset (user): [empty]
trustedset:
 added: [array of 34 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1110 ms
 maxAssetCacheWait: 217 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  sonix.network: 1
```
</details>

**Comment by stephenhawk8054** [comment]
What is broken here? The site looks normal for me

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/ceb13598-6356-4560-a4d1-218c1f84f82e)

**Comment by bluecmd** [comment]
I've installed a specific Grafana version on the site to a version that doesn't have the error message. The API call still happens however, so you should still see the block in uBO.

**Comment by SeamlessRelaxation** [comment]
And apart of an error message, was there anything actually broken on the user's side?

**Comment by bluecmd** [comment]
No, the error message was just a visual issue.

**Comment by stephenhawk8054** [comment]
> No, the error message was just a visual issue.

Then we can't address it as breakage for clients / users. The most we can do is hiding the error message site by site as annoyance issue.

**Comment by bluecmd** [comment]
Ah, I see. That makes sense! Do you require anything from me to add such hiding? As far as I understand the error dialog is generic so getting just this particular error hidden might be hard.

**Comment by stephenhawk8054** [comment]
Currently I don't know how to reproduce it. Can you right click on the error message and open the inspect elements of it?

**Comment by bluecmd** [comment]
Sure, here is the popup on a non-patched Grafana instance I have access to:

![image](https://github.com/uBlockOrigin/uAssets/assets/149442/503ccdb5-803c-474e-bee1-07358999ecb9)

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
metric.sonix.network##+js(no-fetch-if, /frontend-metrics)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
