### ISSUE TITLE
id.vk.com: breakage

### ISSUE THREAD

**Issue by suprunchuk** [uBlockOrigin/uAssets#24354]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://id.vk.com/` + `https://api.vk.com/method/statEvents.addVKUI`

### Category

breakage

### Description

Hi, I am faced with excessive blocking of statistics, which is why website id.vk.com is not working. [I found](https://github.com/uBlockOrigin/uAssets/blob/a6553ee5b9fc860dd0d7f1996b0248c318e04dcc/thirdparties/easylist/easyprivacy.txt#L13147) that the filters are blocked `api.vk.com/method/statEvents. `
Is it possible to add an exception so that all this is blocked except `https://api.vk.com/method/statEvents.addVKUI`

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![img-2024-07-03-02-35-40](https://github.com/uBlockOrigin/uAssets/assets/57152612/f4a06cbd-f1a3-4c13-8b1c-7d8117b24302)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 155548
 cosmetic: 67620
 scriptlet: 23039
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 129-0, never
  ublock-filters: 38968-302, 1h.17m Δ
  ublock-badware: 8662-0, 1h.17m Δ
  ublock-privacy: 1027-2, 1h.17m Δ
  ublock-unbreak: 2366-0, 1h.17m Δ
  ublock-quick-fixes: 117-0, 1h.17m Δ
  easylist: 86376-582, 1h.17m Δ
  easyprivacy: 51129-639, 1h.17m Δ
  urlhaus-1: 15055-5, 1m
  plowe-0: 3543-0, 1m
  RUS-0: 40633-105, 1h.17m Δ
filterset (user): [array of 85 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 631 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  vk.com: 10
  mail.ru: 1
 extended:
  ##+js(abort-on-property-read, Groups.showDisclaimer)
  ##+js(href-sanitizer, a[href*="/away.php?"], ?to)
  ##+js(set-constant, PageBottomBanners, undefined)
  ##+js(set-constant, Unauthorized2, undefined)
  ##+js(set-constant, noAdsAtAll, {})
```
</details>

**Comment by suprunchuk** [comment]
And also please exclude `https://api.vk.com/method/statEvents.addVKIDAnonymously`

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
id.vk.com##+js(no-fetch-if, api.vk.com/method/statEvents.)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by dimisa-RUAdList** [comment]
@suprunchuk 
What exactly is broken due to this blockage?

**Comment by suprunchuk** [comment]
> @suprunchuk 
> What exactly is broken due to this blockage?

The "confirmation via T-id" section does not open

**Comment by dimisa-RUAdList** [comment]
@ryanbr
@Khrin

**Comment by suprunchuk** [comment]
@dimisa-RUAdList  Also, authorization through other services using vk ID does not work. for example, you open https://id.vk.com/business/go and click log in via VK id. you are getting a network error.

![img-2024-07-03-01-53-06](https://github.com/uBlockOrigin/uAssets/assets/57152612/b5b6a6fc-78f9-4eb0-aac9-ec5f19b0eb00)

**Comment by dimisa-RUAdList** [comment]
@ryanbr 
This exception does not solve the problem, it simply does not work there (the target domain is id.vk.com). Your best bet is to remove the blocking rule.

**Comment by suprunchuk** [comment]
> @dimisa-RUAdList Also, authorization through other services using vk ID does not work. for example, you open https://id.vk.com/business/go and click log in via VK id. you are getting a network error.
> 
> ![img-2024-07-03-01-53-06](https://private-user-images.githubusercontent.com/57152612/345352732-b5b6a6fc-78f9-4eb0-aac9-ec5f19b0eb00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTc4ODgsIm5iZiI6MTcxOTk5NzU4OCwicGF0aCI6Ii81NzE1MjYxMi8zNDUzNTI3MzItYjViNmE2ZmMtNzhmOS00ZWIwLWFhYzktZWM1ZjE5YjBlYjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA5MDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMTU3OThhYzI1NWI2NmUxMWQ4MTJlZmJkNjdhZDY3MGRjODcyYmQ4MjE3YmU2ZmJkMDEyNDBmNmJiNDViOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6itVfCQwomwLY-L01ac4PTOJoWk7p6aZULIt55pk4rk)

FIX

**Comment by suprunchuk** [comment]
> > @suprunchuk
> > What exactly is broken due to this blockage?
> 
> The "confirmation via T-id" section does not open

FIX

**Comment by suprunchuk** [comment]
> @ryanbr This exception does not solve the problem, it simply does not work there (the target domain is id.vk.com). Your best bet is to remove the blocking rule.

Why doesn't it solve it? My problem is solved.

1. My account confirmation page is not blocked.
2. I open a third-party authorization via https://id.vk.com/business/go

![image](https://github.com/uBlockOrigin/uAssets/assets/57152612/12c11579-35f3-4cef-8a81-e887eec0b3ce)

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/a7d485650a4e617fccff509be737a2a47ec6ab48

**Comment by suprunchuk** [comment]
> [easylist/easylist@a7d4856](https://github.com/easylist/easylist/commit/a7d485650a4e617fccff509be737a2a47ec6ab48)

Thx!!

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
This exception is not enough. The target domain in some cases is not `api.vk.com`, but `id.vk.com`. Therefore, I had to add to RU AdList: `@@||api.vk.com/method/statEvents.$xmlhttprequest,domain=api.vk.com|id.vk.com`

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList `$~third-party` includes all subdomains of `vk.com` I think?
