### ISSUE TITLE
online-south-park.ru: popups

### ISSUE THREAD

**Issue by vritme** [uBlockOrigin/uAssets#24356]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://online-south-park.ru/`

### Category

popups

### Description

Obviously the site has some clever way of avoiding popups blocking, because Chrome's built-in disabling popups and redirects for the site doesn't work at all - site periodically opens warface and similar gaming sites in new tabs.

Default uBlock settings block maybe 20-30% percent of popups - instead of opening gaming site, uBlock opens extension page with notification about site blocked.

I tried uBlock setting "Block all popups on this site", expecting that it will forcibly disallow all popups, but no, it had no effect whatsoever.

Might be interesting case of strong anti-filtering behavior, especially considering bypassing "block all popups" setting.

### Other extensions used

AdBlock, but it doesn't have any popup blocking functionality

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 94
filterset (summary):
 network: 136705
 cosmetic: 47106
 scriptlet: 21547
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86383-451, 1h.33m Δ
  easyprivacy: 51129-618, 1h.33m Δ
  plowe-0: 3543-0, now
  ublock-badware: 8662-0, 1h.33m Δ
  ublock-filters: 38972-371, 1h.33m Δ
  ublock-privacy: 1027-8, 1h.33m Δ
  ublock-quick-fixes: 117-0, 1h.33m Δ
  ublock-unbreak: 2366-33, 1h.33m Δ
  urlhaus-1: 14800-5, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 247 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 no-popups: true
 network:
  vak345.com: 1
  yadro.ru: 1
  yandex.ru: 1
```
</details>

**Comment by vritme** [comment]
Just have tried whitelisting the site for AdBlock to test for possible conflicts - still opens popups.

**Comment by SeamlessRelaxation** [comment]
Enable RuAdList in the dashboard (Filter lists -> scroll down to `Regions, languages`

**Comment by D4niloMR** [comment]
> ### Other extensions used
> AdBlock

Use just uBlock Origin.

**Comment by vritme** [comment]
> Enable RuAdList in the dashboard (Filter lists -> scroll down to `Regions, languages`)

Thanks a lot!
Now site loads several times faster, and no popus so far).
