### ISSUE TITLE
skyblock.bz: ads

### ISSUE THREAD

**Issue by Oqarshi** [uBlockOrigin/uAssets#24353]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.skyblock.bz/`

### Category

ads

### Description

Theres these leftover spots where ads are suppose to be.

### Other extensions used

Tampermonkey, Anti-Grabify

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/4648a1b9-7323-419a-9173-6dc164f483fe)
![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/69073fc2-04ba-489f-a35c-5b29072d763f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 147027
 cosmetic: 170004
 scriptlet: 35455
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30232-57, now
  ublock-cookies-adguard: 1248-0, now
  fanboy-cookiemonster: 51292-3987, now
  ublock-cookies-easylist: 1248-1248, now
  adguard-popup-overlays: 27340-1004, now
  adguard-mobile-app-banners: 5295-10, now
  adguard-other-annoyances: 14705-643, now
  adguard-widgets: 2591-25, now
  easylist-annoyances: 4695-174, now
  easylist-chat: 198-0, now
  easylist-newsletters: 7416-5, now
  easylist-notifications: 3090-1186, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 9-2, never
  ublock-filters: 38968-109, now
  ublock-badware: 8662-0, now
  ublock-privacy: 1027-2, now
  ublock-unbreak: 2366-2, now
  ublock-quick-fixes: 117-5, now
  easylist: 86376-195, now
  easyprivacy: 51129-186, now
  urlhaus-1: 15055-5, now
  plowe-0: 3543-989, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3887 ms
 maxAssetCacheWait: 739 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  nitropay.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by Oqarshi** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/94034118/406d56cc-c25c-4172-9c56-4c2dd621d256)
Its still here

**Comment by dportvine** [comment]
`https://www.skyblock.bz/flips`

<details>
<summary>Screen</summary>

![2024-07-04_072404](https://github.com/uBlockOrigin/uAssets/assets/111344219/7efebf78-7488-40d7-831c-b651fe0b74c8)
</details>

**Comment by stephenhawk8054** [comment]
```adb
skyblock.bz##[id^="flips-"]
```

@ryanbr

**Comment by Oqarshi** [comment]
thx

**Comment by Oqarshi** [comment]
@stephenhawk8054 

This: `skyblock.bz##[id^="flips-"]`
Only works for this url: [https://www.skyblock.bz/flips](url)

These need to be added
`skyblock.bz##[id^="crafts-"]`
`skyblock.bz##[id^="npc-"]`
`skyblock.bz##[id^="manipulate-"]`
`skyblock.bz##[id^="reverse_npc-"]`
`skyblock.bz##[id^="crash-"]`

for these urls:

[https://www.skyblock.bz/crafts](url)
[https://www.skyblock.bz/npc](url)
[https://www.skyblock.bz/manipulate](url)
[https://www.skyblock.bz/reverse_npc](url)
[https://www.skyblock.bz/crash](url)

There is probably filter rule to block all of these at once but this is what im using right now.

**Comment by Oqarshi** [comment]
Thank you :)
