### ISSUE TITLE
viafree.no / viafree.se ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#2435]
### URL(s) where the issue occurs

https://www.viafree.no/programmer/livsstil/businessfellen/sesong-1/episode-1
https://www.viafree.se/program/livsstil/vad-grillar-du-pa/sasong-1/avsnitt-1

### Describe the issue

My issue is both with viafree.no and viafree.se . Video doesn't start to play. Just a message that ask me to turn off adblocker. In chrome the video player doesn't even appear for me with ublock origin enabled.

### Screenshot(s)

https://i.imgur.com/7gALRan.png

### Versions

- Browser/version: Google Chrome Version 67.0.3396.62 (Official Build) (64-bit)
- uBlock Origin version: 1.16.8

### Settings

- Enabled filter: uBlock filters – Annoyances​​​​​​​​​
- Enabled filter: Adguard’s Annoyance List​​​​​​​​​
- Enabled filter: Fanboy’s Cookiemonster List​​​​​​​​​
- Enabled filter: Fanboy’s Social Blocking List​​​​​​​​​

### Notes

Before it used to work flawlessly with ublock origin enabled. I used this script to skip the commercials, but it doesn't work anymore?

@@||fwmrm.net/*MTG$script,domain=viafree.no
||fwmrm.net/ad/$xmlhttprequest,redirect=nooptext,domain=viafree.no
||freewheel-mtgx-tv.akamaized.net/$media,domain=viafree.no

@@||fwmrm.net/*MTG$script,domain=viafree.se
||fwmrm.net/ad/$xmlhttprequest,redirect=nooptext,domain=viafree.se
||freewheel-mtgx-tv.akamaized.net/$media,domain=viafree.se

**Comment by DandelionSprout** [comment]
I am not currently noticing any problems with Viafree Norway on my end with the Norwegian filter list, though that may admittedly be because I also use such other filter lists as Nano Defender.

So just to be 100% certain, are you (lassekongo83) intending for me to add the six test filters above into my adblock list, or not?

**Comment by okiehsch** [comment]
@DandelionSprout can you watch
`https://www.viafree.no/programmer/livsstil/businessfellen/sesong-1/episode-1`
if you disable `uBO-filters`?

**Comment by DandelionSprout** [comment]
Having now tested the watching of that link with various filter lists turned on/off, I believe I've found the issue. I don't think Schanzation has actually turned on the Norwegian or Swedish filter lists in uBO, as indeed I was able to watch the Viafree.no link until I turned off _Dandelion Sprouts norske filtre_

@Schanzation Can you test out the Viafree videos while having turned on _NOR: Dandelion Sprouts norske filtre_ and/or _SWE: Frellwit's Swedish Filter_, since I currently believe that they contain filters that help play Viafree videos?

**Comment by okiehsch** [comment]
@DandelionSprout you should also add
`@@||playapi.mtgx.tv/*/adinfo?$xmlhttprequest,domain=viafree.no`
if I enable your list and disable `uBO-filters` list the video will not show up.

**Comment by DandelionSprout** [comment]
While I haven't noticed the same scenario on my end, I'll of course add that entry to my list. 🙂 

https://github.com/DandelionSprout/adfilt/commit/1b3a666e5afb34a1c529935826ddfce70a1cbbd1 (which is connected to the main Norwegian list through an !include tag).

**Comment by Schanzation** [comment]
Both viafree.no and .se works now after enabling SWE and NOR filters. Thanks!

It works in both vivaldi and firefox, but in chrome the video player don't appear, even if I open in incognito mode with only ublock origin enabled. Anyone have a clue why?

Just look like this: https://imgur.com/a/dY7qpx4

**Comment by DandelionSprout** [comment]
There's been added a very recent new entry to the Norwegian list 10min ago, so can you update the NOR list manually on your end, just to be certain of that?

**Comment by okiehsch** [comment]
@Schanzation did you force an update of your `uBO-filter` list?

The filter that DandelionSprout added 10 minutes ago is already part of `uBO-filters` and it fixes the issue in your screenshot on my end.

**Comment by Schanzation** [comment]
Yeah wasn't working earlier so I guess it's the recent change in that list that made it work for me :)

Still can't get the video player to show in chrome. Don't know why I got this bug all of a sudden. But I can use firefox/vivaldi meanwhile.

**Comment by DandelionSprout** [comment]
In that case I'm stumped, because I never had any issues with the video player in my Chrome, and thus would have major problems trying to solve a problem that I can't replicate.

I'm happy to hear that there's been some progress, however. 👍

**Comment by okiehsch** [comment]
It works with Chrome/Chromium and Firefox on my end.

**Comment by Schanzation** [comment]
Was enabling / disabling filters to check which one was causing the issue. When disabling and re-enabling easyList it now works on chrome also. Got it working on all browsers now. Thanks so much guys <3
