### ISSUE TITLE
drakecomic.com: detection

### ISSUE THREAD

**Issue by c0tangent** [uBlockOrigin/uAssets#24360]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://drakecomic.com/`

### Category

detection

### Description

adblock detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_4axIekTzWh](https://github.com/uBlockOrigin/uAssets/assets/28670199/742910bc-2245-4973-8f29-d29c3391ceb7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 137092
 cosmetic: 46990
 scriptlet: 20144
 html: 1851
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39099-112, now
  ublock-badware: 8664-0, now
  ublock-privacy: 1018-4, now
  ublock-unbreak: 2425-2, now
  ublock-quick-fixes: 117-5, now
  easylist: 86352-174, now
  easyprivacy: 51129-65, now
  urlhaus-1: 15240-5, now
  plowe-0: 3543-988, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 813 ms
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  bidgear.com: 2
  googlesyndication.com: 2
  lyonthrill.com: 1
  netpub.media: 2
  wp.com: 2
 extended:
  ##.top_ads
  ##.blockad
  ##.adplacement
  ##.ad300x250
  ##.ajaxads
  ##.header_ads
  ##.adtxt
  ##.companion_ad
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by MonfGeiger** [comment]
unfortunately, this has relapsed in the latest ublock origin, guess they implemented ANOTHER adblock detection setup

proof
<details>
![Capture](https://github.com/user-attachments/assets/8a88e39f-acab-43a9-b677-a843482815a4)
</details>
my addons
<details>
![addons](https://github.com/user-attachments/assets/589ca880-657e-4411-b3c5-9b94eb99eae2)
</details>
and to top it off, my uBO deets
<details>

```yaml
uBlock Origin: 1.59.1b14
Firefox: 129
filterset (summary):
 network: 392331
 cosmetic: 320832
 scriptlet: 72074
 html: 2281
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt?a=1: 2326-2324, 7m
  https://easylist.to/easylist/fanboy-social.txt: 17002-2, 7m
  https://filters.adtidy.org/extension/ublock/filters/14.txt?_=5r67756675657: 82480-1486, 7m
  https://github.com/DandelionSprout/adfilt/raw/master/LegitimateURLShortener.txt: 2671-0, 7m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 104466-0, 7m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 7m
  https://neuter.mchang.xyz/filter/sponsorblock: 34-1, 7m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-1, 7m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=rawlist: 152-0, 7m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=rawlist: 22597-153, 7m
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 484-21, 7m
  https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/enhancedstats-addon.txt-old: 2771-72, 7m
  [28 lists not shown]: [too many]
 default:
  user-filters: 468-2, never
  ublock-filters: 40089-2421, 7m
  ublock-badware: 10983-12, 7m
  ublock-privacy: 1116-58, 7m
  ublock-unbreak: 2530-7, 7m Δ
  ublock-quick-fixes: 90-5, 7m Δ
  easylist: 85832-2388, 7m
  easyprivacy: 53028-25408, 7m Δ
  urlhaus-1: 21175-10541, 7m
  plowe-0: 3547-1632, 7m
filterset (user): [array of 469 redacted]
trustedset:
 added: [array of 164 redacted]
hostRuleset:
 added: [array of 55 redacted]
userSettings:
 advancedUserEnabled: true
 cnameUncloakEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
 cnameMaxTTL: 60
 extensionUpdateForceReload: true
supportStats:
 allReadyAfter: 424 ms (selfie)
 maxAssetCacheWait: 304 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  bidgear.com: 4
  lyonthrill.com: 1
  pubfuture-ad.com: 1
  wp.com: 4
 extended:
  ##+js(set-constant, checkAdBlocker, noopFunc)
  ##+js(noeval-if, /chp_?ad/)
  ##+js(noeval-if, /fairAdblock|chp_?adblock|adsbygoogle\.js/)
```
</details>

**Comment by MonfGeiger** [comment]
> @MonfGeiger `drakecomic.com##+js(nostif, console)`

updated filter lists, tried it out, all workin like a charm, GG :)
