### ISSUE TITLE
vectorpea.com: breakage

### ISSUE THREAD

**Issue by NickAcPT** [uBlockOrigin/uAssets#24363]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vectorpea.com/`

### Category

breakage

### Description

Web page is completely blank.

It appears that some rule is matching one of the main JS files used to start the web application.
![image](https://github.com/uBlockOrigin/uAssets/assets/32451103/443d7f5c-b4db-42e8-9937-702af7cc5fc9)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/32451103/2e71cd30-861d-4f99-b8ee-c76697ff5c4b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 142446
 cosmetic: 109841
 scriptlet: 25161
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-mobile-app-banners: 5300-9, 4m
  adguard-other-annoyances: 14711-10, 4m
  adguard-popup-overlays: 27349-893, 4m
  adguard-social: 23041-160, 4m
  adguard-widgets: 2590-1, 4m
 default:
  easylist: 86432-617, 32m Δ
  easyprivacy: 51129-626, 2m
  plowe-0: 3543-0, 4m
  ublock-badware: 8708-0, 32m Δ
  ublock-filters: 38984-599, 32m Δ
  ublock-privacy: 1032-2, 32m Δ
  ublock-quick-fixes: 119-0, 32m Δ
  ublock-unbreak: 2367-19, 32m Δ
  urlhaus-1: 15240-5, 4m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 79 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1088 ms (selfie)
 maxAssetCacheWait: 314 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  photopea.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 Do you know previous cases of this filter? Not sure if we can extract some headers from them.

**Comment by Yuki2718** [comment]
This is for the old PopAds and you can find by https://publicwww.com/websites/%22h%3DdecodeURIComponent%22/
