### ISSUE TITLE
[nsfw] kemono.su: popup

### ISSUE THREAD

**Issue by ColaCherry12** [uBlockOrigin/uAssets#24365]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kemono.su/`

### Category

popups

### Description

Hello. I am getting pop-ups, redirects and push-to-new-tabs to sites like StripChat & LiveJasmine, etc. whenever I right/middle/left click any link/button on this site. I am using Brave Browser, and this problem DOES NOT happen with Chrome. This problem started with me recently, today in fact. I last used the site about 2-3 days ago. Please help. 

### Other extensions used

7TV
AdGuard AdBlocker
Allow right click - simple copy
Google Docs Offline
Google Translate
IDM Integration Module
Permanent Inspect Element
Picture-in-Picture Extension
Redirector
Return YouTube Dislike
Session Buddy
simple-modify-headers
Sound Booster & Pro equalizer
Tampermonkey
YouTube Ad Speed Up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139544
 cosmetic: 50510
 scriptlet: 21563
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4133-77, never
  easylist: 86482-45, 3m
  easyprivacy: 52710-650, 3m
  plowe-0: 3543-376, 3m
  ublock-badware: 8728-17, 3m
  ublock-filters: 38982-370, 3m
  ublock-privacy: 1032-5, 3m
  ublock-quick-fixes: 119-1, 3m
  ublock-unbreak: 2367-15, 3m
  urlhaus-1: 15235-5, 3m
filterset (user): [array of 4556 redacted]
trustedset:
 added: [array of 24 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 178 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-large-media: true
 no-popups: true
 extended:
  ##.ad-container
  ##article.post-card--preview.post-card:has-text(Ada)
  ##article.post-card--preview.post-card:has-text(Ada )
  ##+js(addEventListener-defuser, , popMagic)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings

**Comment by ColaCherry12** [comment]
Video examples: (slightly spicy)

[What Keeps Happening](https://bunkrrr.org/v/uOsURtzmL6ttH)

[What I'd LIKE to happen](https://bunkr.black/v/1KxF6LMHmsBTk)

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
kemono.su##+js(acs, String.fromCharCode, \x)
```

**Comment by ColaCherry12** [comment]
> Test again in a new browser profile with only uBO and its default settings

still the same problem 😬

**Comment by ColaCherry12** [comment]
> Can you test this filter?
> 
> ```
> kemono.su##+js(acs, String.fromCharCode, \x)
> ```
seems to be working now. thank you 🙏
