### ISSUE TITLE
videogamemods.com: ads

### ISSUE THREAD

**Issue by SolarP212** [uBlockOrigin/uAssets#24362]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://videogamemods.com/xenoverse/mods/`

### Category

ads

### Description

It shows ads although uBlock Origin is active, i have no other custom filters or extensions nor other adblockers, i'm using standard firefox browser and i've not changed any settings within uBlock Origin itself, if i recall correctly this issue was not present mere days ago

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![immagine](https://github.com/uBlockOrigin/uAssets/assets/174645335/0ef1a93a-a64c-489c-ab02-a22809a07df2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 140508
 cosmetic: 53910
 scriptlet: 20138
 html: 1851
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39092-112, 10m Δ
  ublock-badware: 8705-0, 10m Δ
  ublock-privacy: 1018-4, 10m Δ
  ublock-unbreak: 2426-2, 10m Δ
  ublock-quick-fixes: 119-5, 10m Δ
  easylist: 86427-174, 10m Δ
  easyprivacy: 52709-65, 10m Δ
  urlhaus-1: 15240-5, now
  plowe-0: 3543-987, now
  ITA-0: 8673-38, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 151 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 33
 network:
  amazon-adsystem.com: 1
  anonymised.io: 2
  btloader.com: 2
  cloudflareinsights.com: 2
  criteo.com: 1
  criteo.net: 1
  doubleclick.net: 1
  google.com: 3
  googletagmanager.com: 2
  html-load.com: 2
  moatads.com: 2
  network-n.com: 3
  newrelic.com: 2
  pbstck.com: 2
  permutive.app: 2
  primis.tech: 1
  privacy-mgmt.com: 2
  scorecardresearch.com: 1
  script.ac: 1
 extended:
  ##.adcontainer
  ##.topbanners
  ##.desktop-ad
  ##.mobile-ad
  ##.adinner
```
</details>

**Comment by SeamlessRelaxation** [comment]
@JobcenterTycoon
