### ISSUE TITLE
weather.com: breakage

### ISSUE THREAD

**Issue by itzViking** [uBlockOrigin/uAssets#24366]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://weather.com/en-GB/weather/today/l/8d3f33c60c9c91238bd7f750a05c61643e3aa608acd60fc11dc969f25c2aa950?par=samsung_widget_XME&cm_ven=L1_current_weather&theme=samsungDark`

### Category

breakage

### Description

When cookie notice is blocked by ublock, page keeps refreshing in never ending loop

### Other extensions used

ClearURLs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 151619
 cosmetic: 214507
 scriptlet: 33879
 html: 2115
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30190-43, 2d.22h.52m
  ublock-cookies-adguard: 1285-16, 2d.19h.52m
  fanboy-cookiemonster: 51278-3958, 5d.19h.28m
  ublock-cookies-easylist: 1285-1285, 2d.19h.52m
  adguard-social: 23022-51, 2d.22h.52m
  fanboy-social: 16340-745, 3d.17h.28m
  fanboy-thirdparty_social: 68-19, 4d.19h.19m
  adguard-popup-overlays: 27310-1105, 2d.22h.52m
  adguard-mobile-app-banners: 5286-35, 2d.22h.52m
  adguard-other-annoyances: 14700-486, 2d.22h.52m
  adguard-widgets: 2564-16, 2d.22h.51m
  easylist-annoyances: 4689-320, 2d.19h.52m
  [4 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 39540-113, 48m Δ
  ublock-badware: 8724-0, 48m Δ
  ublock-privacy: 1024-10, 48m Δ
  ublock-unbreak: 2429-2, 48m Δ
  ublock-quick-fixes: 119-10, 48m Δ
  adguard-mobile: 9555-146, 2d.22h.51m
  easylist: 86482-172, 48m Δ
  easyprivacy: 52710-61, 48m Δ
  urlhaus-1: 15240-5, 14h.3m
  plowe-0: 3551-1063, 6d.21h.53m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 866 ms (selfie)
 maxAssetCacheWait: 133 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  confiant-integrations.net: 2
  effulgenttempest.com: 1
  go-mpulse.net: 2
  googlesyndication.com: 2
  instana.io: 3
 extended:
  ##.adWrapper
  ##.adLabel
  ##.ad_module
  ##div[id^="Taboola-main-"]
  ##div[class*="adWrapper"]
  ##div[id^="WxuPrivacyDataNotice-"]
  ##.PrivacyFeedCard--PrivacyFeedCard--3_Fk5
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(trusted-set-cookie, consentUUID, de9ed9d6-0a43-4074-9349-e…
  ##+js(set-cookie, __adblocker, false, , reload, 1)
  ##+js(remove-class, modalOpen, body, stay)
  ##+js(set-constant, adBlockerReady, false)
  ##+js(prevent-fetch, securepubads.g.doubleclick.net/pagead/ppub_…
  ##+js(abort-on-property-read, setNptTechAdblockerCookie)
```
</details>

**Comment by stephenhawk8054** [comment]
Update your filter lists again.

**Comment by itzViking** [comment]
It is better, thank you.
      
      Some UI elements on that weather page like "Hourly" or "Daily"
      buttons don't work without accepting the cookie notice, but I can
      live with that.
      Cheers.

**Comment by stephenhawk8054** [comment]
> Some UI elements on that weather page like "Hourly" or "Daily" buttons don't work without accepting the cookie notice, but I can live with that.

@JobcenterTycoon Hmm... I can reproduce that with new profile as well.

**Comment by stephenhawk8054** [comment]
These work for me:

```adb
weather.com##+js(trusted-set-cookie, consentUUID, df843851-527a-4aec-8dab-5ba35e570618_32_33)
weather.com##+js(trusted-set-local-storage-item, userConsents, {"functional-technology":true})
```

**Comment by stephenhawk8054** [comment]
Looks like the `consenUUID` filter is causing endless reloading in `https://weather.com/news/trending/video/video-shows-hydrothermal-explosion-at-yellowstone-national-park`

https://www.reddit.com/r/uBlockOrigin/comments/1eb0wlg/weathercom_cannot_load/

**Comment by Marko-98** [comment]
I started to get the constant refresh loop a week ago. I tried resetting uBO to default settings and enabling Cookie notices filters only and the issue still appears. It definitely has something to do with their cookie notice script; because when the website finally loads, the cookie notice is briefly shown, then website is refreshed again with cookie notice removed.

**URL:** https://weather.com/hr-HR/vrijeme/danas/l/HRXX0005:1:HR?Goto=Redirected

**Country:** Croatia

`https://github.com/user-attachments/assets/cbf52039-7284-49f0-bb8c-62e3d0ed71a6`

**Comment by mapx-** [comment]
did you try first to delete all cookies / local storage ?

**Comment by Marko-98** [comment]
Yes. It might happen because of it. I set Firefox to delete all cookies and site data for sites not on my exceptions list and I don't have `weather.com` there.

Once website loads after few minutes, I can normally access site again until I delete site data. Then this redirect loop happens again.

**Comment by mapx-** [comment]
however, I cannot reproduce your issue. Maybe some other your extension is interfering ?!

**Comment by Marko-98** [comment]
I don't really have any other extension installed that has something to do with websites except uBlock Origin. I enter `weather.com` in the address bar, and it automatically redirects me to mentioned URL (regional site). 

Try to set Croatian as first website language in Firefox; it should then take you from `weather.com` to the URL I mentioned. Maybe then you'll be able to reproduce the issue.

**Comment by Marko-98** [comment]
I still have this issue unfortunately.

I'm on Firefox 149.0 and issue can be reproduced by either changing the preferred website language to Croatian and/or just using a Croatian VPN. 

<details>
<summary>Screenshot</summary>




<img width="2559" height="1377" alt="Image" src="https://github.com/user-attachments/assets/2a476f37-f1ad-4d3b-88f3-ae90b4b2f798" />



</details>

When entering `weather.com` in the address bar, it should automatically redirect you to Croatian version of the site where the issue is present.

<details>
<summary>Video</summary>




https://github.com/user-attachments/assets/b4d01eba-8722-4876-a2a2-ba8bd8d9f061



</details>

My uBlock Origin configuration is following:

<details>

```yaml
uBlock Origin: 1.70.0
Firefox: 149
filterset (summary):
 network: 359783
 cosmetic: 218861
 scriptlet: 66921
 html: 3294
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-generic: 93757-5791, now
  block-lan: 89-0, now
  curben-phishing: 159021-50, now
  fanboy-cookiemonster: 46174-95, now
  ublock-cookies-easylist: 5597-42, now
  adguard-social: 26001-42, now
  fanboy-thirdparty_social: 69-3, now
  adguard-popup-overlays: 30535-952, now
  adguard-mobile-app-banners: 6975-101, now
  adguard-other-annoyances: 15840-295, now
  adguard-widgets: 3071-22, now
  easylist-annoyances: 5089-437, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 23-0, never
  ublock-filters: 51228-79, now
  ublock-badware: 10705-30, now
  ublock-privacy: 3955-2, now
  ublock-unbreak: 2808-1, now
  ublock-quick-fixes: 450-13, now
  easylist: 99314-1232, now
  easyprivacy: 55629-122, now
  urlhaus-1: 26680-10, now
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 213 ms (selfie)
 maxAssetCacheWait: 159 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  weather.com: 5
  appsflyer.com: 1
  ay.delivery: 2
  google.com: 1
  googlesyndication.com: 1
  newrelic.com: 2
  p-n.io: 3
  scorecardresearch.com: 1
  taboola.com: 1
  w-x.co: 1
 extended:
  ##.adWrapper
  ##.adLabel
  ##.ad_module
  ###credential_picker_container
  ##.taboola-module
  ##div[id^="Taboola-main-"]
  ##.combinedTopAdsSectionWrapper
  ##div[id^="WxuAd-"]
  ##.Footer--Footer--T3yVr
  ##+js(abort-on-property-read, setNptTechAdblockerCookie)
  ##+js(prevent-fetch, securepubads.g.doubleclick.net/pagead/ppub_…
  ##+js(set-constant, adBlockerReady, false)
  ##+js(trusted-set-local-storage-item, userConsents, {"functional…
  ##+js(set-cookie, __adblocker, false, '', reload, 1)
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(abort-current-script, admiral)
  ##+js(remove-node-text, script, `/"v4ac1eiZr0"|""\)\.split\(","\…
```
</details>

**Comment by Marko-98** [comment]
This still remains an issue for me. Issue isn't present when using AdGuard browser extension, just with uBlock Origin. I also tried to use uBlock Origin for ad blocking and AdGuard just for cookie blocking at the same time and everything works well.

**Comment by stephenhawk8054** [comment]
Please share your uBO troubleshooting information while reproducing the issue and describe what exactly is broken. Don't use multiple cookie lists at the same time.

Also, give exact link where you see the issue.

**Comment by Marko-98** [comment]
@stephenhawk8054 

It happens when I enter `weather.com` in address bar, website takes me directly to Croatian variant of the website with the URL `https://weather.com/hr-HR/vrijeme/danas/l/HRXX0005:1:HR?Goto=Redirected`. From what I understand, that happens because I have preferred website language in Firefox settings set as Croatian.

Troubleshooting information: <details>
```
uBlock Origin: 1.70.0
Firefox: 150
filterset (summary):
 network: 365129
 cosmetic: 267203
 scriptlet: 70864
 html: 3548
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-generic: 95701-5827, now
  adguard-spyware-url: 2493-134, now
  block-lan: 91-0, now
  curben-phishing: 158993-47, now
  adguard-cookies: 38339-89, now
  ublock-cookies-adguard: 5658-82, now
  fanboy-cookiemonster: 46428-3771, now
  ublock-cookies-easylist: 5658-5658, now
  adguard-social: 26218-43, now
  fanboy-social: 17557-853, now
  fanboy-thirdparty_social: 69-18, now
  adguard-popup-overlays: 31019-1023, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 20-0, never
  ublock-filters: 52093-70, now
  ublock-badware: 11183-29, now
  ublock-privacy: 4010-2, now
  ublock-unbreak: 2821-1, now
  ublock-quick-fixes: 473-13, now
  easylist: 96531-1223, now
  easyprivacy: 55979-121, now
  urlhaus-1: 28385-6, now
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 350 ms (selfie)
 maxAssetCacheWait: 267 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  weather.com: 5
  appsflyer.com: 1
  ay.delivery: 2
  googlesyndication.com: 1
  newrelic.com: 2
  scorecardresearch.com: 1
  taboola.com: 2
  w-x.co: 1
 extended:
  ##.adWrapper
  ##.adLabel
  ##.ad_module
  ##.taboola-module
  ##div[id^="WxuPrivacyDataNotice-"]
  ##div[id^="Taboola-main-"]
  ##.combinedTopAdsSectionWrapper
  ##div[id^="WxuAd-"]
  ##+js(abort-on-property-read, setNptTechAdblockerCookie)
  ##+js(prevent-fetch, securepubads.g.doubleclick.net/pagead/ppub_…
  ##+js(set-constant, adBlockerReady, false)
  ##+js(set-cookie, __adblocker, false, '', reload, 1)
  ##+js(trusted-set-local-storage-item, userConsents, {"functional…
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(abort-current-script, admiral)
  ##+js(remove-node-text, script, `/"v4ac1eiZr0"|""\)\.split\(","\…
```
</details>

If I enable only `AdGuard/uBO – Cookie Notices`, I'm not getting any redirects—cookie prompt is briefly shown, but uBO takes care of it and then website is refreshed once again and fully functional.

If I enable only `EasyList/uBO – Cookie Notices`, I get constant redirects from the video above. It eventually calms down and lets me access the website after a few seconds.

Unfortunately, there are a lot of websites with cookie notices that are fixed either by only EasyList or by only AdGuard, so I have no other choice than to use both. This didn't create any issues for me before so far, but it seems like EasyList Cookie filter causes issues here, not AdGuard.

As a temporary solution, I blocked JavaScript completely for `weather.com` and while cookie notice isn't shown at all then, it also breaks rain forecast and radar.

Thanks so much for trying to fix the issue.

**Comment by stephenhawk8054** [comment]
> Unfortunately, there are a lot of websites with cookie noticed that are fixed either only by EasyList or only by AdGuard, so I have no other choice than to use both.

Solutions don't fall from the sky. If users don't bother to report the issues and just pile on more and more lists, we won't help further, it's your choices to increase the breakages chances.

We are not wizards, we can't fix all issues on the internet by reading users' minds.

**Comment by stephenhawk8054** [comment]
> It happens when I enter weather.com in address bar, website takes me directly to Croatian variant of the website with the URL https://weather.com/hr-HR/vrijeme/danas/l/HRXX0005:1:HR?Goto=Redirected

Test again in a new Firefox profile with only uBO and its default settings + `EasyList/uBO – Cookie Notices` lists. Don't enable any other lists.

**Comment by Marko-98** [comment]
@stephenhawk8054 Completely new profile with following settings:

<details>

<img width="1015" height="1451" alt="Image" src="https://github.com/user-attachments/assets/e426f83b-8872-4d32-98e5-1d661ee62f11" />

</details>

Still the same. 🫤

<details>

https://github.com/user-attachments/assets/f564e101-6f53-4e7a-9476-be2cbd3ddeb3

</details>

**Comment by Marko-98** [comment]
> Solutions don't fall from the sky. If users don't bother to report the issues and just pile on more and more lists, we won't help further, it's your choices to increase the breakages chances.

> We are not wizards, we can't fix all issues on the internet by reading users' minds.

I thought by using AdGuard Cookie filter I also get benefits of EasyList Cookie filter. Because AdGuard Base filter is fork of EasyList with some AdGuard additional filters.

**Comment by stephenhawk8054** [comment]
No, AG cookie list is totally independent of EL cookie list with separate solutions. That's why they interfere with each other a lot, especially in the realm of cookie/storage values.

**Comment by stephenhawk8054** [comment]
I tried using VPN to Croatia, but I still can't reproduce the `https://weather.com/hr-HR/vrijeme/danas/l/HRXX0005:1:HR?Goto=Redirected` link

https://github.com/user-attachments/assets/6dad4837-79e3-444e-99e3-f549e47f4ba1

**Comment by Marko-98** [comment]
@stephenhawk8054 Go to Firefox settings -> `General` -> under `Language` and `Choose your preferred language for displaying pages` click on `Choose...` -> click on `Select a language to add...` drop-down and find `Croatian [hr]` -> click on `Add` and make sure Croatian is at first on the list.

Then open an incognito window and enter `weather.com`.

This site serves you local version depending on the website language setting in the browser, not by the IP address.

**Comment by stephenhawk8054** [comment]
I still can't reproduce that many refreshes:

https://github.com/user-attachments/assets/1914e2f5-621b-4759-bfe3-fad9c722c9b2

**Comment by Marko-98** [comment]
You don't even get a cookie prompt at all...

Any ideas what to try next? 😐

**Comment by stephenhawk8054** [comment]
There's a cookie banner, but it's handled by the cookie lists correctly on my side (it auto-clicks on the accept button).

**Comment by Marko-98** [comment]
I don't know what else to try so I give up. I just disabled EasyList Cookie filter and instead use AdGuard one as it works perfectly with it enabled.

Thanks anyway though! 🙂

**Comment by Marko-98** [comment]
Hey @stephenhawk8054, I managed to fix the issue with the help of ChatGPT. Problematic rule in EasyList is `weather.com##+js(set-cookie, __adblocker, false, '', reload, 1)`. 

After adding `weather.com#@#+js(set-cookie, __adblocker, false, '', reload, 1)` in **My filters**, redirect loop stopped and now the website behaves just like it does in your videos.

@ryanbr Is it possible to fix this in EasyList Cookie filter?
