### ISSUE TITLE
mskins.net: ads

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#24369]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mskins.net/`

### Category

ads

### Description

fake button

### Other extensions used

no comment (non ublock/ adblock related)

### Screenshot(s)

![librewolf_tAthrJOn4L](https://github.com/uBlockOrigin/uAssets/assets/150899804/b24c8c48-310c-48e7-8d63-8c3982e672f1)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 165356
 cosmetic: 127987
 scriptlet: 30721
 html: 2132
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51301-232, 23m
  ublock-cookies-easylist: 1248-3, 24m
  easylist-annoyances: 4700-67, 24m
  easylist-chat: 198-0, 24m
  easylist-newsletters: 7428-31, 24m
  easylist-notifications: 3092-181, 24m
  ublock-annoyances: 5888-32, 4m Δ
  RUS-0: 40680-147, 4m Δ
 default:
  user-filters: 64-3, never
  ublock-filters: 39107-112, 4m Δ
  ublock-badware: 8730-0, 4m Δ
  ublock-privacy: 1023-4, 4m Δ
  ublock-unbreak: 2426-2, 4m Δ
  ublock-quick-fixes: 118-9, 4m Δ
  easylist: 86491-173, 4m Δ
  adguard-spyware-url: 1579-120, 23m
  easyprivacy: 52710-64, 4m Δ
  urlhaus-1: 15235-5, 23m
  curben-phishing: 485-2, 23m
  plowe-0: 3543-991, 24m
  LegitimateURLShortener: 2656-165, 24m
filterset (user): [array of 64 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 703 ms (selfie)
 maxAssetCacheWait: 231 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  googlesyndication.com: 2
  mastershik.com: 2
  my1elitclub.com: 1
  sheisnotateacher.com: 2
  yadro.ru: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##div[id^="adfox_"]
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry can you check this?

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/726ad8c27963fadfa934fc35b2742079f7ce1f51
