### ISSUE TITLE
mgtv.com: breakage

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#24364]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mgtv.com/b/292162/3066530.html`

### Category

breakage

### Description

The video cannot be played correctly. It suggests a "DRM problem".

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 129
filterset (summary):
 network: 219669
 cosmetic: 234476
 scriptlet: 51509
 html: 2114
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82423-4048, now
  adguard-spyware-url: 1579-120, now
  adguard-spyware: 69657-1521, now
  curben-phishing: 485-2, 1h.26m
  fanboy-cookiemonster: 51295-191, now
  ublock-cookies-easylist: 1248-3, now
  adguard-social: 23041-56, now
  fanboy-social: 16352-750, now
  fanboy-thirdparty_social: 68-19, now
  adguard-popup-overlays: 27349-1044, now
  adguard-mobile-app-banners: 5300-25, now
  adguard-other-annoyances: 14711-427, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 39092-112, now
  ublock-badware: 8730-0, now
  ublock-privacy: 1023-4, now
  ublock-unbreak: 2426-2, now
  ublock-quick-fixes: 119-5, 1h.27m Δ
  easylist: 86482-2200, now
  easyprivacy: 52710-30644, now
  urlhaus-1: 15235-5, 1h.27m
  plowe-0: 3543-1080, now
  CHN-0: 26507-227, now
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 173 ms (selfie)
 maxAssetCacheWait: 112 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.share-icon
  #@#a[target="_blank"] > img[src*="hitv.com"]
```
</details>

**Comment by stephenhawk8054** [comment]
DRM issue is usually due to browser issue. Does the issue occur if you turn off uBO?

**Comment by Linisdjxm** [comment]
@stephenhawk8054  I am quite sure that after disabling uBO this problem will no longer occur.

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

Also which country are you when accessing the site?

**Comment by Linisdjxm** [comment]
It is confirmed that the issue was caused by browser.
