### ISSUE TITLE
sitepoint.com: ads

### ISSUE THREAD

**Issue by goutam1312** [uBlockOrigin/uAssets#24367]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sitepoint.com/obsidian-beginner-guide/`

### Category

ads

### Description

Showing ads

### Other extensions used

Twp translator 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 128
filterset (summary):
 network: 140214
 cosmetic: 55366
 scriptlet: 20212
 html: 1853
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39540-113, now
  ublock-badware: 8724-0, now
  ublock-privacy: 1024-4, now
  ublock-unbreak: 2429-2, now
  ublock-quick-fixes: 118-4, now
  adguard-mobile: 9559-74, now
  easylist: 86491-240, now
  easyprivacy: 52710-73, now
  urlhaus-1: 15220-0, now
  plowe-0: 3556-1063, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4143 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  adpushup.com: 1
  adrecover.com: 1
  bing.com: 2
  facebook.net: 1
  googletagmanager.com: 1
  mixpanel.com: 1
  posthog.com: 16
  sentry.io: 3
  tapfiliate.com: 1
 extended:
  ##._ap_apex_ad
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
sitepoint.com##div.inline-content
sitepoint.com##._ap_apex_ad-container
```

@ryanbr
