### ISSUE TITLE
baidu.com: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#24376]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.baidu.com/baidu?ie=utf-8&wd=Haidilao`

### Category

ads

### Description

Ad in the page.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/35957435/152b92f6-f3ec-4ca0-a774-8cf8743462a1

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 129
filterset (summary):
 network: 220245
 cosmetic: 234611
 scriptlet: 51613
 html: 2117
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82463-4050, now
  adguard-spyware-url: 1579-120, now
  adguard-spyware: 69672-1521, now
  curben-phishing: 601-1, 9m
  fanboy-cookiemonster: 51301-191, now
  ublock-cookies-easylist: 1249-3, now
  adguard-social: 23046-56, now
  fanboy-social: 16358-750, now
  fanboy-thirdparty_social: 68-19, now
  adguard-popup-overlays: 27356-1044, now
  adguard-mobile-app-banners: 5306-25, now
  adguard-other-annoyances: 14724-428, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 39132-112, now
  ublock-badware: 8798-1, now
  ublock-privacy: 1023-4, now
  ublock-unbreak: 2429-2, now
  ublock-quick-fixes: 122-5, 9m Δ
  easylist: 86526-2204, now
  easyprivacy: 52709-30645, now
  urlhaus-1: 15545-6, 8m
  plowe-0: 3543-1080, now
  CHN-0: 26545-226, 1m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1160 ms
 maxAssetCacheWait: 609 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  baidu.com: 17
  bdstatic.com: 1
 extended:
  ###content_left > div:not([class]) > div[data-placeid]
  ###content_left > .result ~ div:not([class]):not([style])
  ###content_right > table > tbody > tr > td > div:not(#con-ar):no…
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry can you check this?

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/5bd48d9cb37bcd05d0bc876c696bc0c442871ec1
