### ISSUE TITLE
business3.cryptednews.space (paycut.io): detection

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#24370]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://business3.cryptednews.space/`
`https://business.cryptednews.space/`

### Category

detection

### Description

The website detects adblockers.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/354cb93b-a7ad-4f20-9d40-a425c47c6107)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 139063
 cosmetic: 47174
 scriptlet: 21574
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39001-369, 37m Δ
  ublock-badware: 8796-1, 37m Δ
  ublock-privacy: 1032-2, 37m Δ
  ublock-unbreak: 2367-0, 37m Δ
  ublock-quick-fixes: 119-0, 37m Δ
  easylist: 86499-469, 37m Δ
  easyprivacy: 52710-638, 37m Δ
  urlhaus-1: 15380-5, now
  plowe-0: 3543-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 668 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  acscdn.com: 1
  b2c.com: 1
  doubleclick.net: 3
  google.com: 3
  googletagmanager.com: 1
  profitsfly.com: 1
  youtube.com: 10
 extended:
  ##+js(prevent-fetch, ads)
  ##+js(prevent-fetch, method:HEAD)
  ##+js(trusted-replace-node-text, script, /^([^{])/, "document.ad…
  ##+js(set-constant, document.hasFocus, trueFunc)
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/\"adSlots.*?\}\]\}\}\],/…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by Hazuki-san** [comment]
link to test on: `paycut.io/gMoMhCrN`

**Comment by stephenhawk8054** [comment]
For future issues of shortener links, please comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361

Don't open issues about these sites.
