### ISSUE TITLE
kimcartoon.li: breakage

### ISSUE THREAD

**Issue by LeHman93** [uBlockOrigin/uAssets#24373]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kimcartoon.li/`

### Category

breakage

### Description

I reported this before about the buttons to scroll shows left/right not working and it got fixed, but the issue seems to be back again
![image](https://github.com/uBlockOrigin/uAssets/assets/44226902/e123da51-17e8-4e6a-b9e5-e224d4d008b6)
this button

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 117
filterset (summary):
 network: 139037
 cosmetic: 47075
 scriptlet: 20174
 html: 1855
listset (total-discarded, last-updated):
 added:
  https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 0-0, never
  ublock-quick-fixes: 122-7, 29m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 39132-112, now
  ublock-badware: 8798-1, now
  ublock-privacy: 1023-4, now
  ublock-unbreak: 2426-2, now
  easylist: 86515-172, now
  easyprivacy: 52709-64, now
  plowe-0: 3543-987, now
  urlhaus-1: 15380-5, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7812 ms
 maxAssetCacheWait: 2098 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  facebook.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(spoof-css, .kcAds1, display, block)
  ##+js(abort-current-script, setTimeout, /Adb|_0x/i)
  ##+js(remove-node-text, script, /adb/i)
  ##+js(no-xhr-if, /googlesyndication|mgid\.com/)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
  ##+js(remove-node-text, script, /^\s+setTimeout|setTimeout[^(]*\…
  ##+js(abort-on-stack-trace, document.getElementById, Scripts)
  ##+js(no-setTimeout-if, '/^(?!function\(\){var c=d\(b\);f\.body\…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
```
</details>

**Comment by D4niloMR** [comment]
#24217

**Comment by LeHman93** [comment]
But thats a completely diferent issue

**Comment by stephenhawk8054** [comment]
Just continue in that thread
