### ISSUE TITLE
4gtv.tv: ads

### ISSUE THREAD

**Issue by kclonline** [uBlockOrigin/uAssets#24374]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.4gtv.tv/channel/4gtv-4gtv152?set=1&ch=292`

### Category

ads

### Description

There are still ads, and the content will not be displayed until the video is finished, but the ads are not displayed and the sound is still there.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 154273
 cosmetic: 57947
 scriptlet: 21871
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39023-295, now
  ublock-badware: 8728-0, now
  ublock-privacy: 1027-2, now
  ublock-unbreak: 2367-0, now
  ublock-quick-fixes: 122-0, now
  easylist: 86491-595, now
  easyprivacy: 52710-638, now
  urlhaus-1: 15380-5, now
  plowe-0: 3543-0, now
  CHN-0: 26535-146, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2967 ms
 maxAssetCacheWait: 65 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 104
 network:
  2mdn.net: 1
  33across.com: 1
  adnxs-simple.com: 1
  adnxs.com: 10
  creativecdn.com: 1
  criteo.net: 1
  crwdcntrl.net: 1
  dable.io: 3
  doubleclick.net: 28
  google-analytics.com: 11
  google.com: 15
  google.com.tw: 4
  googlesyndication.com: 3
  googletagmanager.com: 1
  googletagservices.com: 2
  gstatic.com: 11
  imasdk.googleapis.com: 1
  imrworldwide.com: 7
  openxcdn.net: 1
  scupio.com: 1
 hasUnprocessedRequest: true
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.TopAd
  ##.ima-ad-container
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry can you check this?

**Comment by stephenhawk8054** [comment]
Needs Taiwan IP
