### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by dragonslayer667** [uBlockOrigin/uAssets#24378]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kimcartoon.li/Cartoon/Star-Trek-Prodigy-Season-2/Episode-19?id=118158`

### Category

detection

### Description

was working hours ago now is detected

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 139181
 cosmetic: 47016
 scriptlet: 20165
 html: 1855
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39132-112, now
  ublock-badware: 8798-1, now
  ublock-privacy: 1018-4, now
  ublock-unbreak: 2429-2, now
  ublock-quick-fixes: 118-5, now
  easylist: 86432-173, now
  easyprivacy: 52709-65, now
  urlhaus-1: 15545-5, now
  plowe-0: 3543-987, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1252 ms
 maxAssetCacheWait: 25 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  kimcartoon.li: 1
  bidgear.com: 1
  gamescdnfor.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  jsdelivr.net: 1
  jwpcdn.com: 1
  sharethis.com: 1
  staticmoly.me: 5
  vidmoly.to: 1
  yandex.ru: 1
 extended:
  ##.kcAds1
  ##+js(spoof-css, .kcAds1, display, block)
  ##+js(abort-current-script, setTimeout, /Adb|_0x/i)
  ##+js(no-xhr-if, /googlesyndication|mgid\.com/)
  ##+js(no-xhr-if, method:/get|head/i)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
  ##+js(remove-node-text, script, /^\s+setTimeout|setTimeout[^(]*\…
  ##+js(no-setTimeout-if, '/^(?!function\(\){var c=d\(b\);f\.body\…
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ###vope
  ###mg_vd
  ###dos_vlock
  ###adsblock
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues/24217
