### ISSUE TITLE
github.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#24385]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://github.com/session`

### Category

breakage

### Description

Can't log into GitHub when using issue reporter but login works fine on GitHub main website. Refer to the video. 

### Other extensions used

FastForward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/69532417/3283ea41-8dc7-4803-a8f9-3bf91267a1c8

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 217301
 cosmetic: 217048
 scriptlet: 54095
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82467-6307, never
  adguard-mobile: 9564-178, never
  adguard-spyware-url: 1581-122, never
  adguard-spyware: 69678-32144, never
  block-lan: 68-0, never
  curben-phishing: 557-1, never
  adguard-cookies: 30254-86, never
  ublock-cookies-adguard: 1251-1248, never
  fanboy-cookiemonster: 51303-3990, never
  ublock-cookies-easylist: 1249-0, never
  adguard-popup-overlays: 27366-893, 9m
  adguard-mobile-app-banners: 5312-9, 9m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39001-600, 9m
  ublock-badware: 8796-1, 9m
  ublock-privacy: 1034-2, 9m
  ublock-unbreak: 2374-0, 9m
  ublock-quick-fixes: 112-0, 9m
  easylist: 86515-636, 9m
  easyprivacy: 52709-741, 9m
  urlhaus-1: 15750-5, 9m
  plowe-0: 3542-0, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2730 ms
 maxAssetCacheWait: 28 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  github.com: 2
```
</details>

**Comment by SeamlessRelaxation** [comment]
@gorhill

**Comment by mapx-** [comment]
test using only the defaults (settings + lists) and no other enabled extension

**Comment by SeamlessRelaxation** [comment]
couldn't it be related to the URL parameters?

**Comment by gwarser** [comment]
How long is the URL in the address bar on the login page?

**Comment by jimmysofat6864** [comment]
@Yuki2718 @mapx- Reset to default settings and it works fine. Enabling the filter lists I have shown causes login issues. Refer to my attached lists below. 

![image](https://github.com/uBlockOrigin/uAssets/assets/69532417/79812504-fcdb-48d5-914d-82f9f4b4a15f)
![image](https://github.com/uBlockOrigin/uAssets/assets/69532417/a6fed022-562b-4a54-a093-658be6334ddb)

**Comment by Yuki2718** [comment]
>  Enabling the filter lists I have shown causes login issues. Refer to my attached lists below.
> 

> * [x]  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> * [x]  I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

Find the list causing the issue and report to its maintainer.

**Comment by gorhill** [comment]
> Enabling the filter lists I have shown causes login issues. Refer to my attached lists below.

It's probably a case of the URL being too long. See if you still suffer the issue once you are logged in. From what I see the site is crafting an even longer URL so that you are redirecting to the original destination once you are logged in. GitHub imposes a limit on the size of URL.

**Comment by jimmysofat6864** [comment]
Issue doesn’t occur when already logged in. Is this an issue that can be
fixed?
