### ISSUE TITLE
cnbc.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#24384]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cnbc.com/2023/08/30/jim-cramers-guide-to-investing-listen-to-your-teenagers.html`

### Category

breakage

### Description

Video player not working when enabled

### Other extensions used

FastForward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 217301
 cosmetic: 217048
 scriptlet: 54095
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82467-6307, never
  adguard-mobile: 9564-178, never
  adguard-spyware-url: 1581-122, never
  adguard-spyware: 69678-32144, never
  block-lan: 68-0, never
  curben-phishing: 557-1, never
  adguard-cookies: 30254-86, never
  ublock-cookies-adguard: 1251-1248, never
  fanboy-cookiemonster: 51303-3990, never
  ublock-cookies-easylist: 1249-0, never
  adguard-popup-overlays: 27366-893, 2m
  adguard-mobile-app-banners: 5312-9, 2m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39001-600, 2m
  ublock-badware: 8796-1, 2m
  ublock-privacy: 1034-2, 3m
  ublock-unbreak: 2374-0, 3m
  ublock-quick-fixes: 112-0, 3m
  easylist: 86515-636, 3m
  easyprivacy: 52709-741, 3m
  urlhaus-1: 15750-5, 3m
  plowe-0: 3542-0, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2730 ms
 maxAssetCacheWait: 28 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 36
 network:
  cnbc.com: 1
  admantx.com: 1
  amazon-adsystem.com: 1
  bing.com: 1
  bounceexchange.com: 1
  cookielaw.org: 4
  demdex.net: 6
  doubleclick.net: 1
  googletagmanager.com: 4
  imrworldwide.com: 1
  iteratehq.com: 1
  micpn.com: 1
  moatads.com: 1
  nbcudigitaladops.com: 1
  nbcuni.com: 3
  onetrust.com: 1
  rokt.com: 1
  sail-personalize.com: 1
  sail-track.com: 1
  scorecardresearch.com: 1
  taboola.com: 1
  tinypass.com: 1
  tvsquared.com: 1
 extended:
  ##.BoxRail-ad
  ###taboola-right-rail-thumbnails
  ##.ot-sdk-show-settings
  ###onetrust-consent-sdk
  ##.onetrust-pc-dark-filter
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##.CNBCFooter-info
  ##.TopBanner-container
  ##div[class^="TopBanner-"]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, admiral, noopFunc)
  ##+js(set-constant, cnbc.canShowAds, true)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by SeamlessRelaxation** [comment]
> ```yaml
>   [6 lists not shown]: [too many]
> ```

please try a new profile with a fresh uBO install

**Comment by jimmysofat6864** [comment]
> I cannot reproduce it. Please try to disable filter lists one by one and check which one causes this problem.

I don't think I made it clear enough but it's not the first video on the top it's the second video below the article.

**Comment by jimmysofat6864** [comment]
> > ```yaml
> >   [6 lists not shown]: [too many]
> > ```
> 
> please try a new profile with a fresh uBO install

Already did, same issue.

**Comment by jimmysofat6864** [comment]
@ghajini @SeamlessRelaxation 

Refer to the video below. 

https://github.com/uBlockOrigin/uAssets/assets/69532417/760dfad7-76fc-4c7f-b0bb-4f3a23860b14

**Comment by mapx-** [comment]
test

@@||cdn.tinypass.com/api/tinypass.min.js$script,domain=cnbc.com

@Yuki2718 [AdGuard – Popup Overlays](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-popup-overlays)

**Comment by jimmysofat6864** [comment]
login shows and pops up now thanks

**Comment by Yuki2718** [comment]
> Already did, same issue.

AdGuard – Popup Overlays is not default.
