### ISSUE TITLE
manhuabaiku.com: breakage

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#24388]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.manhuabaiku.com/chapter/7695_641221.html`

### Category

breakage

### Description

Comic couldn't load when uBlock Origin enabled. And here're an ad. 

### Other extensions used

None. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-07-06-14-16-12-674_org mozilla firefox-edit](https://github.com/uBlockOrigin/uAssets/assets/56181919/19f9257b-dd63-45ca-a571-762488df497a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 223230
 cosmetic: 107042
 scriptlet: 39017
 html: 1858
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82535-4058, 1m
  adguard-spyware-url: 1581-122, 1h.33m
  adguard-spyware: 69679-1537, 4m
  block-lan: 68-0, 4m
  curben-phishing: 500-1, 6m
  dpollock-0: 11688-484, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 39586-113, now
  ublock-badware: 8710-1, now
  ublock-privacy: 1026-4, now
  ublock-unbreak: 2436-2, now
  ublock-quick-fixes: 115-2, 1m
  adguard-mobile: 9564-104, 1m
  easylist: 86541-2273, 1m
  easyprivacy: 52720-30652, 4m
  urlhaus-1: 15695-5, 6m
  plowe-0: 3542-1482, 6m
  CHN-0: 26562-242, 6m
filterset (user): [empty]
userSettings:
 prefetchingDisabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3843 ms
 maxAssetCacheWait: 1821 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  bootcdn.net: 2
 extended:
  ###googlead
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
blocked: 2
 network:
  bootcdn.net: 2
```

Please check this: https://github.com/uBlockOrigin/uAssets/issues/24346#issuecomment-2204987189
