### ISSUE TITLE
unbreak macys.com

### ISSUE THREAD

**Issue by snafuy** [uBlockOrigin/uAssets#2438]
### URL(s) where the issue occurs

`https://www.macys.com/shop/womens-clothing/basic-clothing?id=135942&cm_sp=us_hdr-_-women-_-135942_basics_COL1`
(and all of the other inventory pages)

### Describe the issue

Shopping features at Macys.com do not work right when coremetrics.com is blocked:
1: left side: the large +/- buttons for the "Filter By" lists do not work
2: bottom: the "Show [60] [120]" buttons do not work
3: bottom: the < [page 1 of 9] > forward/backward arrows do not work

### Screenshot(s)

![macys-filter-by](https://user-images.githubusercontent.com/10090126/40817315-c298761a-651f-11e8-8b72-16286bd5d694.png)
![macys-show-page](https://user-images.githubusercontent.com/10090126/40817316-c2a69434-651f-11e8-83cb-d8eb357b27f0.png)

### Versions

- Browser/version: Chrome 67
- uBlock Origin version: 1.16.8

### Settings

- I only use the built-in filters and malware filters (not Easy List or Peter Lowe)

### Notes

Using Advanced Mode, I selectively enabled each of the blocked domains one at a time and tested the buttons. They worked again when I enabled coremetrics.com

**Comment by okiehsch** [comment]
I can't reproduce with a default setup, the site works fine on my end.

**Comment by snafuy** [comment]
Crud, my mistake. Coremetrics.com is blocked by the Disconnect Malvertising filter set. Disabling that fixes the problem.
