### ISSUE TITLE
pelisenhd.org: banner ad

### ISSUE THREAD

**Issue by detyso** [uBlockOrigin/uAssets#24383]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pelisenhd.org/`

### Category

ads

### Description

betwinner banner ads showing

### Other extensions used

bitwarden violent monkey darkreader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-07-05 175437](https://github.com/uBlockOrigin/uAssets/assets/163365484/c352ec1e-e764-4cc0-bf1b-01b089cb711b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.1b11
Chromium: 124
filterset (summary):
 network: 139463
 cosmetic: 47184
 scriptlet: 21599
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39029-277, now
  ublock-badware: 8796-1, now
  ublock-privacy: 1034-2, now
  ublock-unbreak: 2374-0, now
  ublock-quick-fixes: 118-0, now
  easylist: 86530-561, now
  easyprivacy: 52712-640, now
  urlhaus-1: 15750-5, now
  plowe-0: 3542-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2084 ms
 maxAssetCacheWait: 24 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by SeamlessRelaxation** [comment]
@Khrin

**Comment by mapx-** [comment]
add

`pelisenhd.org###image_banner_turk_id`

for the spanish list @Yuki2718
