### ISSUE TITLE
topperlearning.com: ads

### ISSUE THREAD

**Issue by Broken-Glass1** [uBlockOrigin/uAssets#24382]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.topperlearning.com/answer/mohan-bought-20-dining-table-for-rs-12000-and-sold-them-at-the-profit-equal-to-s-p-of-4-dining-table-find-the-s-p-of-1-dining-table/knjc6fdd
```

### Description

Ads annoyance and tracking.
Os:- Android
Web browser:- ubo on Firefox

### Other extensions used

No

### Screenshot(s)

![68747470733a2f2f63646e2e616467756172642e696e666f2f736974657265706f7274732f657262746b6d717532646330777338776f6f38306f776377776334736730676e753968766e6e74306c772e706e673f6e633d31](https://github.com/uBlockOrigin/uAssets/assets/159278763/5cada77c-4fde-4252-9711-9bcd68824d32)

### Configuration

Ubo default

**Comment by mapx-** [comment]
report here:
https://github.com/mediumkreation/IndianList/issues
