### ISSUE TITLE
thwiki.cc: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#24380]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thwiki.cc/`

### Category

ads

### Description

#24215 didn't fix it. The ad remains there.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 129
filterset (summary):
 network: 220250
 cosmetic: 234581
 scriptlet: 51601
 html: 2118
listset (total-discarded, last-updated):
 added:
  adguard-generic: 82464-4050, now
  adguard-spyware-url: 1579-122, now
  adguard-spyware: 69672-1521, now
  curben-phishing: 601-1, now
  fanboy-cookiemonster: 51301-191, now
  ublock-cookies-easylist: 1249-3, now
  adguard-social: 23046-56, now
  fanboy-social: 16356-750, now
  fanboy-thirdparty_social: 68-19, now
  adguard-popup-overlays: 27356-1044, now
  adguard-mobile-app-banners: 5306-25, now
  adguard-other-annoyances: 14724-428, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 20-0, never
  ublock-filters: 39132-112, now
  ublock-badware: 8798-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2430-2, now
  ublock-quick-fixes: 112-5, now
  easylist: 86526-2204, now
  easyprivacy: 52709-30645, now
  urlhaus-1: 15545-6, now
  plowe-0: 3543-1080, now
  CHN-0: 26547-226, 1m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 238 ms (selfie)
 maxAssetCacheWait: 142 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  baidu.com: 2
  google-analytics.com: 1
  googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please report Chinese sites to this repo first: https://github.com/easylist/easylistchina/issues
