### ISSUE TITLE
Brainly.in

### ISSUE THREAD

**Issue by MenacingPerson** [uBlockOrigin/uAssets#24398]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://brainly.in/question/17916363
```

### Description

NOTE: I reset UBlock Origin to its default configuration and reloaded, issue is still present

When trying to view an answer, it prompts me to sign up. [1]

When I try to skip by playing a video, an anti-adblock banner pops up. [2]

### Other extensions used

Better Youtube Shorts

Bitwarden

Bypass Paywalls Clean

Dark Reader

Ecosia

Facebook Container

FastForward

Firefox Multi-Account Containers

Return Youtube Dislike

Shinigami Eyes

SponsorBlock for Youtube

Tampermonkey BETA (Note: no userscripts for this site)

User-Agent Switcher and Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/59611020/cd7f1d37-416a-4ccf-99c4-4d50ace18c48)
![image](https://github.com/uBlockOrigin/uAssets/assets/59611020/d6caed48-f63e-4968-9e62-fd7eed23e957)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 140431
 cosmetic: 47130
 scriptlet: 20166
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39156-112, now
  ublock-badware: 8742-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2433-2, now
  ublock-quick-fixes: 108-2, now
  easylist: 86594-173, now
  easyprivacy: 52720-65, now
  urlhaus-1: 16770-5, now
  plowe-0: 3542-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11845 ms
 maxAssetCacheWait: 4713 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  brainly.in: 4
  adlightning.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 2
  datadome.co: 1
  doubleclick.net: 2
  google.com: 5
  googletagmanager.com: 1
  opti-digital.com: 2
  primis.tech: 1
  rubiconproject.com: 1
  sentry-cdn.com: 1
 extended:
  ##[class^="BrainlyAdsPlaceholder"]
  ##.brn-ads-box
  ##[data-testid="brainly_ads_placeholder"]
  ##+js(no-setTimeout-if, trigger, 0)
  ##+js(abort-on-property-read, __brn_private_mode)

```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Annoyances` list and test again.

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
brainly.*##+js(set-local-storage-item, simple-funnel-name, $remove$)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Fatcavill** [comment]
hello is it possible to completely remove sign up and when i click get answer..the answer show ?
