### ISSUE TITLE
24h.com.vn: nuisance

### ISSUE THREAD

**Issue by error-reporting** [uBlockOrigin/uAssets#24394]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.24h.com.vn/media-24h/so-tre-em-su-dung-thuoc-la-dien-tu-tang-hon-gap-doi-c762a1583399.html`

### Category

nuisance

### Description

A 3rd party sponsored post in a different place

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-07-07-09-51-20-31_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/166897813/7962ebb1-f377-47d6-b3df-73d5f75395e5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 142288
 cosmetic: 56713
 scriptlet: 20453
 html: 1858
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  ublock-filters: 39609-113, 4m Δ
  ublock-badware: 8736-1, 4m Δ
  ublock-privacy: 1026-4, 4m Δ
  ublock-unbreak: 2436-6, now
  ublock-quick-fixes: 114-2, 4m Δ
  adguard-mobile: 9563-74, now
  easylist: 86594-240, 4m Δ
  easyprivacy: 52720-73, 4m Δ
  urlhaus-1: 16770-5, now
  plowe-0: 3542-1063, now
  VIE-1: 1952-31, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 14 redacted]
hostRuleset:
 added: [array of 31 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 assetFetchTimeout: 60
 cnameIgnore1stParty: false
 cnameIgnoreRootDocument: false
supportStats:
 allReadyAfter: 2412 ms (selfie)
 maxAssetCacheWait: 1061 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  24h.com.vn: 2
  criteo.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  w5.akamai.net: 8
 extended:
  ##div[id^="div_inpage_banner"]
  ###div_inpage_banner
  ##.boxbannerinfeed-kh
  ##[id^="ADS_"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by error-reporting** [comment]
if this is a duplicate then how do i put things in this template in comment of the other issue

**Comment by stephenhawk8054** [comment]
Please report to: https://github.com/abpvn/abpvn/issues
