### ISSUE TITLE
[nsfw] crazystudy.info: breakage

### ISSUE THREAD

**Issue by DaisukeDaisuke** [uBlockOrigin/uAssets#24395]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
NSFW(Japanese) https://crazystudy.info/sharehouse-self-pleasure
```

### Description

The body text will be removed by the content filter
This seems to be caused by the easylist generic filter
However, I have looked for pages that are not nsfw and they are not broken except for this one, so I think it is safe to ignore it
https://github.com/easylist/easylist/blob/52d4158d3d6dfe0b19c51da083c9fa783455c5eb/easylist/easylist_general_hide.txt#L9435

As a workaround, I suggest this (I don't know if this might cause ad leaks)
```
crazystudy.info#@#.category-advertorial
```
Thank you for reading

### Other extensions used

All disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Desktop Screenshot 2024 07 07 - 14 49 14 67](https://github.com/uBlockOrigin/uAssets/assets/17798680/f8c30c7b-146d-4807-8274-263dc7968a2a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 141615
 cosmetic: 59472
 scriptlet: 21177
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38327-382, 5h.25m Δ
  ublock-badware: 8734-0, 3h.25m Δ
  ublock-privacy: 924-0, 3h.25m Δ
  ublock-unbreak: 2278-0, 3h.25m Δ
  ublock-quick-fixes: 151-0, 3h.25m Δ
  easylist: 87324-479, 3h.25m Δ
  easyprivacy: 50953-809, 3h.25m Δ
  urlhaus-1: 16770-0, 19m
  plowe-0: 3726-0, 3d.32m
  JPN-1: 14947-49, 19m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1922 ms
 maxAssetCacheWait: 22 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  crazystudy.info: 1
  clarity.ms: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  moshimo.com: 1
  onesignal.com: 1
  twitter.com: 2
  valuecommerce.com: 2
  wp.com: 1
 extended:
  ##.category-advertorial
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/\{"brs_content_label":[^,]…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…

```
</details>

**Comment by DaisukeDaisuke** [comment]
For reference, other pages do not use ".category-advertorial"
`NSFW(Japanese) https://crazystudy.info/nengo-review`

```
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 141615
 cosmetic: 59473
 scriptlet: 21177
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 38327-284, 5h.43m Δ
  ublock-badware: 8734-0, 3h.43m Δ
  ublock-privacy: 924-0, 3h.43m Δ
  ublock-unbreak: 2278-0, 3h.43m Δ
  ublock-quick-fixes: 151-0, 3h.43m Δ
  easylist: 87324-570, 3h.43m Δ
  easyprivacy: 50953-23, 3h.43m Δ
  urlhaus-1: 16770-0, 37m
  plowe-0: 3726-786, 3d.51m
  JPN-1: 14947-56, 37m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1922 ms
 maxAssetCacheWait: 22 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  crazystudy.info: 1
  clarity.ms: 1
  facebook.com: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  onesignal.com: 1
  twitter.com: 1
  valuecommerce.com: 1
  wp.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, '/\{"brs_content_label":[^,]…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
```

**Comment by DaisukeDaisuke** [comment]
In hindsight, it was inappropriate to post this on uAssets as this is an easylist issue
I apologize for the burden I placed on the volunteers

**Comment by stephenhawk8054** [comment]
@Yuki2718 For EL or Adguard JP?

**Comment by Yuki2718** [comment]
It seems the filter is more problematic than useful, e.g. hiding all the contents on `https://persoblogger.de/2024/06/24/der-echte-fachkraeftekampf-beginnt-nach-dem-recruiting` as well. It's 12-years old filter and I no longer see hit on the original commit of first results on publicwww. I'll remove this.

**Comment by DaisukeDaisuke** [comment]
I'll leave a link to the commit for future reference (it's for me)
https://github.com/easylist/easylist/commit/940cb25467bedc3a5a7d570542f4259a6a386232

**Comment by Yuki2718** [comment]
Looks targetting advertorial articles like in `https://caon.ro/`. Not something worth risking breakage. cc: @mapx- In case you want to address in ROad-Block.
