### ISSUE TITLE
rangerdrilling.velpic.net: breakage

### ISSUE THREAD

**Issue by shanept** [uBlockOrigin/uAssets#24399]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rangerdrilling.velpic.net/`

### Category

breakage

### Description

The specific site is work-related and requires login. The website loads resources from atlassian and zendesk which are both blocked, resulting in the website loading as a blank screen.
Turning off uBlock Origin for the site solves this issue.

### Other extensions used

Dashlane, Adobe PDF Reader.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/5936269/cb226e06-11fb-4b48-9a9c-b7b93c392c83)

![image](https://github.com/uBlockOrigin/uAssets/assets/5936269/02c67635-6c34-455a-af24-d1d96ade1238)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 140839
 cosmetic: 47244
 scriptlet: 21600
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86611-469, 36m Δ
  easyprivacy: 52722-640, 36m Δ
  plowe-0: 3542-0, now
  ublock-badware: 8809-1, 36m Δ
  ublock-filters: 39049-366, 36m Δ
  ublock-privacy: 1034-2, 36m Δ
  ublock-quick-fixes: 108-0, 36m Δ
  ublock-unbreak: 2374-0, 36m Δ
  urlhaus-1: 17070-5, never
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 366 ms (selfie)
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  atlassian.net: 1
  zendesk.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||damstratechnology.atlassian.net/rest/collectors/1.0/configuration/trigger/$script,domain=rangerdrilling.velpic.net
```

@ryanbr
