### ISSUE TITLE
danpod.work [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2439]
URL(s) where the issue occurs

`http://danpod.work/2R2m`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.8

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
fixed here:
https://github.com/uBlockOrigin/uAssets/commit/c2d02d16c02cf5614bba687f8e4a21e435d6aa0d
