### ISSUE TITLE
Popunders.com is opening new windows

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#244]
### URL(s) where the issue occurs

`skidrowreloaded.com
`
### Describe the issue

The site opens a new window with advertising

### Versions

- Browser/version:  Firefox Nightly 530A1
- uBlock Origin version: 1.10.4

### Notes

The company providing that nasty script seems to be popunderjs.com 
there are rotating garbage urls involved like `ssvolkkihcyp.com`

**Comment by gorhill** [comment]
Does this work?

    skidrowreloaded.com##script:inject(popads.net.js)

**Comment by SMed79** [comment]
Alternative filters https://forums.lanik.us/viewtopic.php?f=62&t=32174

**Comment by yoshimo** [comment]
That injection seems to work unless the site triggers the popunder only every other time

**Comment by gorhill** [comment]
With the filter above, I can't reproduce popups/popunders. You have repro steps?

**Comment by gorhill** [comment]
Alternatively there is:

    skidrowreloaded.com##script:inject(abort-on-property-write.js, popns)

**Comment by rjkpa** [comment]
Blocking third-party scripts will also put a stop to those popups(/unders).

`||$third-party,script,domain=skidrowreloaded.com`

**Comment by yoshimo** [comment]
`skidrowreloaded.com##script:inject(popads.net.js)` 
is fine
