### ISSUE TITLE
bantenexis.com: detection

### ISSUE THREAD

**Issue by ediners** [uBlockOrigin/uAssets#24406]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bantenexis.com/the-power-of-5-key-sales-performance-metrics/`

### Category

detection

### Description

Site detected adblock upon arrival

### Other extensions used

fastforward, tampermonkey (no script related), bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 140551
 cosmetic: 47146
 scriptlet: 20173
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39159-112, now
  ublock-badware: 8855-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2437-2, now
  ublock-quick-fixes: 115-2, now
  easylist: 86619-173, now
  easyprivacy: 52726-65, now
  urlhaus-1: 16755-5, now
  plowe-0: 3542-989, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 405 ms (selfie)
 maxAssetCacheWait: 67 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  google-analytics.com: 2
  googlesyndication.com: 12
  googletagmanager.com: 1
 extended:
  ##div[id^="wpsafe-wait"]
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link? Can you give original URL?

**Comment by stephenhawk8054** [comment]
Next time please comment here for future shortener links: https://github.com/uBlockOrigin/uAssets/discussions/17361

Don't open new issues about these shortener sites.
