### ISSUE TITLE
lilymanga.net: detection

### ISSUE THREAD

**Issue by 5aw5a** [uBlockOrigin/uAssets#24404]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lilymanga.net/`

### Category

manga reading site

### Description

it detects the adblock

### Other extensions used

sponserblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 103
filterset (summary):
 network: 140795
 cosmetic: 47147
 scriptlet: 20172
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39165-112, 8m Δ
  ublock-badware: 8811-1, 8m Δ
  ublock-privacy: 1025-4, 8m Δ
  ublock-unbreak: 2433-2, 8m Δ
  ublock-quick-fixes: 109-2, 8m Δ
  easylist: 86611-173, 8m Δ
  easyprivacy: 52722-65, 8m Δ
  urlhaus-1: 17060-5, 8m
  plowe-0: 3542-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 157 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  amazon-adsystem.com: 1
  google-analytics.com: 1
  media.net: 1
  quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how it looks like?
