### ISSUE TITLE
croxyproxy.com: popups

### ISSUE THREAD

**Issue by 05unit** [uBlockOrigin/uAssets#24403]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.croxyproxy.com/`

### Category

popups

### Description

Everytime i use croxyproxy it opens a random website, the website is often considered a advertisement.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-07-07 112256](https://github.com/uBlockOrigin/uAssets/assets/174961073/e7ba7c73-b251-4802-bef9-3b5fb9a8227a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 140795
 cosmetic: 47147
 scriptlet: 20172
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39165-112, 1h.3m Δ
  ublock-badware: 8811-1, 1h.3m Δ
  ublock-privacy: 1025-4, 1h.3m Δ
  ublock-unbreak: 2433-2, 1h.3m Δ
  ublock-quick-fixes: 109-2, 1h.3m Δ
  easylist: 86611-173, 1h.3m Δ
  easyprivacy: 52722-65, 1h.3m Δ
  urlhaus-1: 17060-5, now
  plowe-0: 3542-989, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 329 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google-analytics.com: 1
  googleadservices.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce
