### ISSUE TITLE
gadgetizedpanda.com: nuisance

### ISSUE THREAD

**Issue by Tegual** [uBlockOrigin/uAssets#24400]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gadgetizedpanda.com/2024/01/16/seems-to-be-the-main-heroine-volume-1-illustrations/`

### Category

nuisance

### Description

overlay popup that happens on ever page. when blocked with a generic filter the page cannot be used at all.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 152248
 cosmetic: 206735
 scriptlet: 35597
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30259-69, 6m
  ublock-cookies-adguard: 1251-0, 6m
  fanboy-cookiemonster: 67559-20245, 6m
  ublock-cookies-easylist: 1251-1251, 6m
  adguard-social: 23070-792, 6m
  fanboy-social: 16390-32, 6m
  fanboy-thirdparty_social: 68-0, 6m
  adguard-popup-overlays: 27367-1668, 6m
  adguard-mobile-app-banners: 5311-9, 6m
  adguard-other-annoyances: 14728-505, 6m
  adguard-widgets: 2593-19, 6m
  easylist-annoyances: 4695-51, 6m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39049-599, 1h.37m Δ
  ublock-badware: 8809-6, 1h.37m Δ
  ublock-privacy: 1034-2, 1h.37m Δ
  ublock-unbreak: 2374-0, 1h.37m Δ
  ublock-quick-fixes: 108-0, 1h.37m Δ
  easylist: 86611-643, 1h.37m Δ
  easyprivacy: 52722-751, 1h.37m Δ
  urlhaus-1: 17060-0, now
  plowe-0: 3542-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1140 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  gadgetizedpanda.com: 4
  cloudflareinsights.com: 3
  google.com: 10
  googletagmanager.com: 1
  msecnd.net: 2
  paypal.com: 2
 extended:
  ##.heateor_sss_sharing_container
  ##.heateor_sss_sharing_ul
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[href^="http://reddit.com/submit?url="]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="http://reddit.com/submit"]
  ##+js(no-xhr-if, method:POST url:/logImpressions)
  ##.like-box
  ###share-container
  ###fb-root:not(body):not(html)
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
gadgetizedpanda.com##+js(nostif, isOpen)
```

@ryanbr
