### ISSUE TITLE
Annoyance - Privacy Policy Pop-in

### ISSUE THREAD

**Issue by smed79** [uBlockOrigin/uAssets#2441]
### URL(s) where the issue occurs

```
http://www.dorkly.com/
http://www.collegehumor.com/
```

### Describe the issue

Annoyance >> Privacy Policy Pop-in.

### Screenshot(s)

http://i.imgur.com/KOPNxhU.png
http://i.imgur.com/tJ9D1Ct.png

### Filter lists

- Fanboy's Annoyance List
- uBlock filters – Annoyances

**Comment by ryanbr** [comment]
Not sure how to fix this

**Comment by okiehsch** [comment]
`example.com##script:inject(abort-on-property-read.js, jQuery.cookie)` will work but that could break site functionality.

I do not think there is a way to fix this with standard filter syntax without breaking the site completely.

**Comment by krystian3w** [comment]
```
collegehumor.com,dorkly.com##.privacy-modal
collegehumor.com,dorkly.com##body.has-modal:style(overflow: auto!important;)
collegehumor.com,dorkly.com##body:before
```

How about to this workaround for uBlock Origin / AdGuard AdBlocker?
