### ISSUE TITLE
vejr.tv2.dk: breakage

### ISSUE THREAD

**Issue by MrJohnHanson** [uBlockOrigin/uAssets#24412]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vejr.tv2.dk/`

### Category

breakage

### Description

When uBlock Origin (uBO) is enabled, approx. 60 - 70 % of the page disappears. When uBO is disabled, the page looks correct. Using uBO on this page has worked for several years without any problems, but around june 15 - june 20 (2024), the problem occured and has been there ever since. Latest updates to uBO hasn't solved the problem.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 109
filterset (summary):
 network: 142121
 cosmetic: 49572
 scriptlet: 21701
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 26-0, never
  NOR-0: 3862-4, 1h.26m
  easylist: 86619-563, 10m
  easyprivacy: 52726-641, 10m
  plowe-0: 3542-0, 10m
  ublock-badware: 8853-6, 10m
  ublock-filters: 39135-284, 10m
  ublock-privacy: 1034-2, 10m
  ublock-quick-fixes: 115-0, 10m
  ublock-unbreak: 2380-0, 10m
  urlhaus-1: 16755-0, 10m
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2629 ms (selfie)
 maxAssetCacheWait: 220 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  2mdn.net: 1
  adobedtm.com: 5
  brightcove.com: 5
  doubleclick.net: 2
  googlesyndication.com: 1
  k5a.io: 1
  relevant-digital.com: 1
  tv2a.dk: 1
 extended:
  ##div[class="tc_deck"]
  ##.tc_ad
  ##.vjs-ima3-ad-container
  ##+js(xml-prune, VAST, , adnxs)
  ##+js(xml-prune, VAST, , barstoolsports.com)
```
</details>

**Comment by DandelionSprout** [comment]
I can't seem to reproduce it at all. I need a screenshot.

**Comment by DandelionSprout** [comment]
Okay, now I see it… I think. The initial landing page looked such that I thought that only the search bar was supposed to be visible by TV2. Give me some minutes.
