### ISSUE TITLE
realcanadiansuperstore.ca: breakage

### ISSUE THREAD

**Issue by asandhu3** [uBlockOrigin/uAssets#24414]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.realcanadiansuperstore.ca/search?search-bar=bacon`

### Category

breakage

### Description

When logged in with an account with previous orders, items marked as "previously-purchased" are not shown in the product listing. It seems they are being hidden along with "sponsored" items. When uBlock is disabled both sponsored and previously purchased products appear. I've confirmed that the /search API call does indeed return the previously purchased items in both cases so perhaps a JS file needed to show them is being blocked?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/14942829/5db1cabd-5900-4a85-9672-db3a1bdca7c9)

![image](https://github.com/uBlockOrigin/uAssets/assets/14942829/43ec709f-e4d3-4127-9651-2027896d7c81)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 158420
 cosmetic: 47152
 scriptlet: 20243
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39245-119, 1h.47m Δ
  ublock-badware: 8855-1, 1h.47m Δ
  ublock-privacy: 1025-4, 1h.47m Δ
  ublock-unbreak: 2439-2, 1h.47m Δ
  ublock-quick-fixes: 115-2, 1h.47m Δ
  easylist: 86622-173, 1h.47m Δ
  easyprivacy: 52726-65, 1h.47m Δ
  urlhaus-1: 34615-5, now
  plowe-0: 3542-989, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 44 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 33 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  kameleoon.eu: 4
  launchdarkly.com: 2
  loblaw.digital: 7
  moengage.com: 1
  signalayer.com: 1
  techlab-cdn.com: 7
 extended:
  ##[data-testid="product-grid"] > .css-0:has([data-testid="produc…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
realcanadiansuperstore.ca#@#[data-testid="product-grid"] > .css-0:has([data-testid="product-badge"])
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by asandhu3** [comment]
Yes, that works, however both sponsored and previously purchased products are being shown. Would there be any way to only exclude sponsored items?

**Comment by asandhu3** [comment]
That seems to be hiding both types.

**Comment by stephenhawk8054** [comment]
@asandhu3 Can you screenshot "My filters" here?

**Comment by asandhu3** [comment]
<img width="1553" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/14942829/15d1c04d-36cb-423a-a9e8-bbe7753e4bfe">

**Comment by stephenhawk8054** [comment]
@asandhu3 Keep the 1st filter and continue adding the 2nd one. Don't remove the 1st filter.

**Comment by asandhu3** [comment]
Ah, sorry. Yes that does work, I'm seeing previously purchased without the sponsored items. Thank you!

**Comment by stephenhawk8054** [comment]
@ryanbr
