### ISSUE TITLE
rumble.com: breakage

### ISSUE THREAD

**Issue by OGHersch** [uBlockOrigin/uAssets#24411]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rumble.com`

### Category

[unknown]

### Description

The chat section in rumble does not load with firefox, whether i use FF standalone, or with ghostery privacy browser. It does work with Brave Browser or other chrome browsers. 

### Other extensions used

I don't use any other extensions that relate to pages loading. 
- Convertcase
- language tool
- skip redirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 125
filterset (summary):
 network: 140861
 cosmetic: 47149
 scriptlet: 20173
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 10-2, never
  ublock-filters: 39159-112, 24m Δ
  ublock-badware: 8855-1, 24m Δ
  ublock-privacy: 1025-4, 24m Δ
  ublock-unbreak: 2437-2, 24m Δ
  ublock-quick-fixes: 115-2, 24m Δ
  easylist: 86619-173, 24m Δ
  easyprivacy: 52726-65, 24m Δ
  urlhaus-1: 17060-5, now
  plowe-0: 3542-989, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 908 ms (selfie)
 maxAssetCacheWait: 190 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  rumble.com: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  rmbl.ws: 1
 extended:
  ##.a-break
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
