### ISSUE TITLE
realclearpolicy.com: breakage

### ISSUE THREAD

**Issue by mdhsc02** [uBlockOrigin/uAssets#24418]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.realclearpolicy.com/`

### Category

breakage

### Description

The nav-bar and sub-nav-bar are removed when uBlock Origin is active. If the extension is disable (either page or globally), the nav bars are present. The following is an image with uBlock Origin disabled for the page. Additional pages in this site have the same issue.
![image_2024-07-08_161901086](https://github.com/uBlockOrigin/uAssets/assets/117037710/a2be3f22-19b0-4fb3-8895-0dbd3dd092b4)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 158459
 cosmetic: 47247
 scriptlet: 21673
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39123-281, 1h.27m Δ
  ublock-badware: 8853-1, 1h.27m Δ
  ublock-privacy: 1034-2, 1h.27m Δ
  ublock-unbreak: 2380-0, 1h.27m Δ
  ublock-quick-fixes: 123-0, 1h.27m Δ
  easylist: 86625-561, 1h.27m Δ
  easyprivacy: 52727-640, 1h.27m Δ
  urlhaus-1: 34615-5, now
  plowe-0: 3542-0, now
filterset (user): [empty]
trustedset:
 added: [array of 28 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 639 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  realclearpolicy.com: 2
  spot.im: 1
 extended:
  ##.RC-AD
  ##.RC-AD-TOP-BANNER
  ##.RC-AD-BOX-TOP
  ##.RC-AD-BOX-MIDDLE
  ##.RC-AD-BOX-BOTTOM
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||realclearpolicy.com/esm/assets/js/analytics/gaAnalytics.js$xhr,1p
@@||realclearpolicy.com/esm/assets/js/analytics/chartbeat.js$xhr,1p
```

@ryanbr

**Comment by mdhsc02** [comment]
The same rule is needed for the sister sites:
https://www.realclearmarkets.com/
https://www.realclearworld.com/
https://www.realcleardefense.com/
https://www.realclearenergy.org/
https://www.realclearhealth.com/
https://www.realclearscience.com/
https://www.realclearreligion.org/
https://www.realcleareducation.com/
https://www.realclearinvestigations.com/
https://www.realclearhistory.com/
https://www.realclearbooks.com/
https://www.realclearflorida.com/
https://www.realclearpennsylvania.com/
