### ISSUE TITLE
roblox.com: breakage

### ISSUE THREAD

**Issue by temporarylol33** [uBlockOrigin/uAssets#24413]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.roblox.com/login`

### Category

breakage

### Description

When UBO is turned on, I cannot login into the site and gives me the message "Unknown error occurred. Please try again later." It breaks on other blockers too, but even if i have them turned off (with UBO the only one on), it wont allow me to log in.

### Other extensions used

EFF Privacy Badger
PopUpOff

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 158420
 cosmetic: 47152
 scriptlet: 20243
 html: 1857
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39245-119, 14m Δ
  ublock-badware: 8855-6, 14m Δ
  ublock-privacy: 1025-4, 14m Δ
  ublock-unbreak: 2439-2, 14m Δ
  ublock-quick-fixes: 115-2, 14m Δ
  easylist: 86622-173, 14m Δ
  easyprivacy: 52726-65, 14m Δ
  urlhaus-1: 34615-0, now
  plowe-0: 3542-989, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 846 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  roblox.com: 17
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
