### ISSUE TITLE
courses.monoprix.fr: breakage

### ISSUE THREAD

**Issue by Raziel-Akira** [uBlockOrigin/uAssets#24426]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://courses.monoprix.fr/content/page-idees-recettes`

### Category

breakage

### Description

I noticed a problem on the site of one of my usual reseller. I usually do my shopping using recipes visible here: https://courses.monoprix.fr/content/page-idees-recettes

This page no longer loads. I have to deactivate my ad blocker except here it is not about advertising. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 175045
 cosmetic: 53841
 scriptlet: 21829
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39131-350, 15m
  ublock-badware: 8799-1, 15m
  ublock-privacy: 1034-2, 15m
  ublock-unbreak: 2378-0, 15m
  ublock-quick-fixes: 121-0, 15m
  easylist: 86619-599, 15m
  easyprivacy: 52726-640, 15m
  urlhaus-1: 33745-5, 15m
  plowe-0: 3542-0, 15m
  FRA-0: 24767-312, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 766 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  bing.com: 1
  cookielaw.org: 1
  googletagmanager.com: 1
  newrelic.com: 2
  nr-data.net: 4
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=courses.monoprix.fr
```

@ryanbr
