### ISSUE TITLE
smartserve-ams.vocalmeet.com: breakage

### ISSUE THREAD

**Issue by BowzasaurusRex** [uBlockOrigin/uAssets#24420]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://smartserve-ams.vocalmeet.com/login/`

### Category

breakage

### Description

uBlock seems to be blocking CSS and Javascript from loading on this website, which said website detects. The website works properly if uBlock origin is disabled for the affected website. I tried disabling cosmetic filtering and updating the default filter lists, but unfortunately that didn't fix the issue.

I've included a list of extensions used, but the issue persists even if I disable everything but uBlock Origin.

Here is the troubleshooting information:
`uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 157552
 cosmetic: 47147
 scriptlet: 20242
 html: 1859
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39235-119, now
  ublock-badware: 8855-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2439-2, now
  ublock-quick-fixes: 123-2, now
  easylist: 86625-173, now
  easyprivacy: 52724-65, now
  urlhaus-1: 33745-5, now
  plowe-0: 3542-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3067 ms
 maxAssetCacheWait: 39 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 50
 network:
  vocalmeet.com: 50`

### Other extensions used

1Password
BetterTTV
ChatReplay
Facebook Container
Greasemonkey
LibRedirect
Reddit Enhancement Suite
Ruffle
Stylus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/13355923/a98c2ce7-c890-4847-87d5-6ed03b71e9a4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 157556
 cosmetic: 47146
 scriptlet: 20243
 html: 1859
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39235-119, 21m Δ
  ublock-badware: 8855-6, 21m Δ
  ublock-privacy: 1026-4, 21m Δ
  ublock-unbreak: 2439-2, 21m Δ
  ublock-quick-fixes: 123-2, 21m Δ
  easylist: 86625-173, 21m Δ
  easyprivacy: 52727-65, 21m Δ
  urlhaus-1: 33745-0, now
  plowe-0: 3542-989, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 378 ms (selfie)
 maxAssetCacheWait: 245 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 80
 network:
  vocalmeet.com: 49
  cloudflare.com: 31
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `/smartserve-` in EP

@ryanbr
