### ISSUE TITLE
aniwavetv.to: breakage

### ISSUE THREAD

**Issue by Ethanants** [uBlockOrigin/uAssets#24425]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniwavetv.to/watch/lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life.kwmmw/ep-5`

### Category

breakage

### Description

Upon trying to load any site's show, i'm now suddenly prompted with:
"vid2a41.site is blocked"
"vid2a41.site refused to connect."
"ERR_BLOCKED_BY_RESPONSE"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/uBlockOrigin/uAssets/assets/22051326/c5905e4c-ee7d-4c83-9222-12510f925bd7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 157718
 cosmetic: 47275
 scriptlet: 21680
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39144-115, now
  ublock-badware: 8980-1, now
  ublock-privacy: 1035-2, now
  ublock-unbreak: 2380-2, now
  ublock-quick-fixes: 125-2, now
  easylist: 86639-561, now
  easyprivacy: 52726-802, now
  urlhaus-1: 33745-5, now
  plowe-0: 3542-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 168 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cubeuptownpert.com: 1
  googletagmanager.com: 1
  pubadx.one: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Are you sure it's related to uBO?

Same happens to me even when I don't use any extensions:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/a68a3a99-7b83-407e-8411-22fed5177a76)

**Comment by JobcenterTycoon** [comment]
Works fine for me.
