### ISSUE TITLE
arkgacha.kwer.top: breakage

### ISSUE THREAD

**Issue by SchwarzXia** [uBlockOrigin/uAssets#24427]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://arkgacha.kwer.top/`

### Category

breakage

### Description

Enabling UBO breaks the CSS and some js functionalities of the website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 177045
 cosmetic: 132567
 scriptlet: 27430
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51307-199, 2m
  ublock-cookies-easylist: 1256-0, 2m
  fanboy-social: 16378-7, 2m
  easylist-annoyances: 4704-16, 4m
  easylist-chat: 198-0, 4m
  easylist-newsletters: 7467-24, 4m
  easylist-notifications: 3102-82, 4m
 default:
  user-filters: 10-0, never
  ublock-filters: 39144-307, 31m Δ
  ublock-badware: 8980-1, 31m Δ
  ublock-privacy: 1035-2, 31m Δ
  ublock-unbreak: 2380-2, 31m Δ
  ublock-quick-fixes: 125-0, 31m Δ
  easylist: 86639-620, 31m Δ
  easyprivacy: 52726-729, 31m Δ
  urlhaus-1: 33745-5, 2m
  plowe-0: 3542-0, 2m
  CHN-0: 26600-147, 2m
filterset (user): [array of 10 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 726 ms (selfie)
 maxAssetCacheWait: 102 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  staticfile.net: 2
```
</details>

**Comment by stephenhawk8054** [comment]
The domain `staticfile.net` being blocked in the site belongs to `polyfill.io` who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.
