### ISSUE TITLE
pronosoft.com: ads

### ISSUE THREAD

**Issue by malfoyez** [uBlockOrigin/uAssets#24435]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pronosoft.com/`

### Category

ads

### Description

a lot of advertising on this site, impossible to block

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran 2024-07-09 212816](https://github.com/uBlockOrigin/uAssets/assets/169759235/c929c8d6-7222-48bc-b511-ab0c2585f879)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 289904
 cosmetic: 270342
 scriptlet: 54308
 html: 0
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 added:
  https://curbengh.github.io/pup-filter/pup-filter.txt: 199-0, now
  https://easylist.to/easylist/easylist.txt: 86683-981, now
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 80319-80319, now
  https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt: 42535-174, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 100230-100230, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-8, now
  adguard-generic: 82800-7367, now
  adguard-mobile: 9583-145, now
  adguard-spyware-url: 1583-123, now
  adguard-spyware: 78688-31385, now
  block-lan: 68-0, now
  curben-phishing: 455-0, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 39149-620, 35m Δ
  ublock-badware: 8981-8, 35m Δ
  ublock-privacy: 1035-3, 35m Δ
  ublock-unbreak: 2380-0, 35m Δ
  ublock-quick-fixes: 131-2, 35m Δ
  easylist: 86675-86675, 35m Δ
  easyprivacy: 52726-1070, 35m Δ
  urlhaus-1: 34670-5, now
  plowe-0: 3549-835, now
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 813 ms
 maxAssetCacheWait: 525 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  pronosoft.com: 1
  eacdn.com: 3
  googletagmanager.com: 1
 extended:
  ##.m-ad
  ###cookie-warning
```
</details>

**Comment by mapx-** [comment]
- reset uBO to defaults
- enable the regional french list
- test again

If you still see ads report here:
https://github.com/easylist/listefr/issues

@smed79

**Comment by smed79** [comment]
@malfoyez 
Ads shown on your photo are already blocked in **Liste FR**.
Try the recommended above.
