### ISSUE TITLE
Unbreak circumvention of copyright access control via uBO scriptlet and pricklydebt/knitstamp domain blocks

### ISSUE THREAD

**Issue by admiral-pubhelp** [uBlockOrigin/uAssets#24431]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://sporcle.com
```

### Description

The site's copyright access control message giving multiple options to support the site via allowlisting or subscribing is currently being circumvented by uBO.  The message is soft/dismissable, which is consistent with [uBO's unbreak policy](https://x.com/gorhill/status/1072990091625328641).  

The following exception rules appear to fix it:
@@||pricklydebt.com^
@@||knitstamp.com^
sporcle.com#@#+js(acs, document.createElement, admiral)

Since it doesn't engage on every pageview, you should always refresh with cleared cookies/cache to recreate consistently.

### Other extensions used

This has been isolated to uBO with default filters.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

This is easy to describe/recreate without visual.  The unbreak fix can be seen by applying the exception rules listed above.  Happy to provide visual if needed.

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 158618
 cosmetic: 47282
 scriptlet: 21685
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 39147-281, 25m Δ
  ublock-badware: 8981-1, 25m Δ
  ublock-privacy: 1035-2, 25m Δ
  ublock-unbreak: 2380-0, 25m Δ
  ublock-quick-fixes: 125-0, 25m Δ
  easylist: 86674-561, 25m Δ
  easyprivacy: 52726-640, 25m Δ
  urlhaus-1: 34615-5, 15h.39m
  plowe-0: 3542-0, 15h.39m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 77 ms (selfie)
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  github.com: 16

```
</details>

**Comment by gorhill** [comment]
`pricklydebt.com` and `knitstamp.com` are parts of many privacy- and malware-related blocklists, including 3rd-party lists used by uBO, we are not going to challenge or circumvent the presence of these domains in these community-driven lists.
