### ISSUE TITLE
kraloyun.com: breakage

### ISSUE THREAD

**Issue by cmnbhgt** [uBlockOrigin/uAssets#24436]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kraloyun.com/Oyun/Ates-ve-Su`

### Category

breakage

### Description

When you click Play, the game does not start. I don't know, but it looks like a cookie issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 160679
 cosmetic: 94012
 scriptlet: 29174
 html: 2115
listset (total-discarded, last-updated):
 added:
  ublock-cookies-adguard: 1261-0, 1m
  fanboy-cookiemonster: 51307-189, 1m
  ublock-cookies-easylist: 1261-1261, 1m
  ublock-annoyances: 5897-66, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39258-119, 1m
  ublock-badware: 8855-1, 1m
  ublock-privacy: 1026-4, 1m
  ublock-unbreak: 2439-2, 1m
  ublock-quick-fixes: 123-2, 1m
  easylist: 86639-173, 1m
  easyprivacy: 52726-64, 1m
  urlhaus-1: 34670-5, 1m
  plowe-0: 3549-991, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2114 ms
 maxAssetCacheWait: 1269 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  spielaffe.de: 1
 extended:
  ##div[id^="sp_message_container_"]
  ##.alice-root-header-ads__ad--top
  ##.alice-adslot
  ##.advertising-container
```
</details>

**Comment by stephenhawk8054** [comment]
Working fine for me
