### ISSUE TITLE
convertingcolors.com: breakage

### ISSUE THREAD

**Issue by icaru52** [uBlockOrigin/uAssets#24433]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://convertingcolors.com/image-picker.html`

### Category

breakage

### Description

The "Upload your image to extract color palette" box is removed by uBlock cosmetic filtering. 

(Fresh Firefox profile with no other extensions and default uBlock settings)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-07-09 at 13-36-33 Converting Colors - I](https://github.com/uBlockOrigin/uAssets/assets/86861628/010fc423-53a3-4b6d-9528-15e6f7b97531)
![Screenshot 2024-07-09 at 13-36-50 Converting Colors - I](https://github.com/uBlockOrigin/uAssets/assets/86861628/7f7c945f-b44a-441a-9e97-8539d772a511)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 158644
 cosmetic: 47185
 scriptlet: 20254
 html: 1859
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39258-119, now
  ublock-badware: 8983-1, now
  ublock-privacy: 1026-4, now
  ublock-unbreak: 2439-2, now
  ublock-quick-fixes: 131-4, now
  easylist: 86675-173, now
  easyprivacy: 52726-63, now
  urlhaus-1: 34670-5, 1m
  plowe-0: 3549-991, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1306 ms
 maxAssetCacheWait: 63 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  servedby-buysellads.com: 2
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.abc
```
</details>

**Comment by D4niloMR** [comment]
Add:

`convertingcolors.com#@#.abc`
