### ISSUE TITLE
aniwave.to: ads

### ISSUE THREAD

**Issue by RandomPersonUMet** [uBlockOrigin/uAssets#24439]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniwave.to/home`

### Category

ads

### Description

This is admittedly a duplicate as I have not been able to get my previous report (https://github.com/uBlockOrigin/uAssets/issues/24397) reopened. I have added a new screenshot (3rd pic) since [reinstalling UBO without modifying it at all](https://github.com/uBlockOrigin/uAssets/issues/24397#issuecomment-2213548933), to show the issue persists. 

--------------------------------------------------------------------------------------------

When loading the AniWave website (https://aniwave.to/home) or one of its anime pages (eg: https://aniwave.to/watch/one-piece.ov8/ep-1111) a banner ad will often appear after a delay and will take over a significant amount of the screen.

Most of the time it will appear blank, as I suspect that uBlock 'strips' the ads image off, but the banner still remains. When clicking the "Close ad" icon it often (but not always) redirects to https://aniwave.to/#.

The element picker mode is only useful for 'stripping' the ad image on top of the banner as the element picker can't seem to detect the banner at all.

### Other extensions used

- MAL-Sync
- Return YouTube Dislike
- SponsorBlock for YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/135276391/0988126e-eb17-47f5-b784-c611020ab59a)
![image](https://github.com/uBlockOrigin/uAssets/assets/135276391/33ebe4bd-f7f7-497f-869b-e1042ac01f3c)
![image](https://github.com/uBlockOrigin/uAssets/assets/135276391/925f904d-f650-4203-bd92-6f9289533143)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 158694
 cosmetic: 47287
 scriptlet: 21688
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39151-115, now
  ublock-badware: 8986-1, now
  ublock-privacy: 1035-2, now
  ublock-unbreak: 2380-2, now
  ublock-quick-fixes: 131-4, now
  easylist: 86683-561, now
  easyprivacy: 52729-802, now
  urlhaus-1: 34670-5, now
  plowe-0: 3549-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2579 ms
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 69
 network:
  360yield.com: 4
  a-mo.net: 2
  a3cloud.net: 1
  adform.net: 2
  adingo.jp: 1
  adnxs.com: 13
  adroll.com: 6
  adrta.com: 7
  amung.us: 1
  andbeyond.media: 1
  bidgear.com: 1
  bidswitch.net: 1
  connatix.com: 1
  creativecdn.com: 4
  criteo.com: 1
  criteo.net: 3
  cubeuptownpert.com: 1
  doubleclick.net: 1
  exelator.com: 1
  google-analytics.com: 2
  googletagmanager.com: 1
  krxd.net: 1
  media.net: 1
  pubmatic.com: 1
  rkdms.com: 2
  rqtrk.eu: 1
  sharethis.com: 2
  swarthsfulk.com: 1
  track.us.org: 2
  tribalfusion.com: 1
  w55c.net: 1
  zombisarake.top: 1
 extended:
  ##.adx
  ##+js(no-window-open-if, _blank)
  ##+js(set-cookie, __pf, 1)
  ##+js(abort-on-property-read, AaDetector)
```
</details>

**Comment by D4niloMR** [comment]
> Comment here:
https://github.com/uBlockOrigin/uAssets/issues/19779

**Comment by RandomPersonUMet** [comment]
> > Comment here:
> > #19779

@D4niloMR This is a completely different type of ad from #19779 as it does not involve the video player at all but the website itself.

**Comment by stephenhawk8054** [comment]
Just continue in that thread.

**Comment by RandomPersonUMet** [comment]
> Just continue in that thread. Ads means all ads.

Ok @stephenhawk8054 , so should I re-explain my issue in that thread or just reference #24439 and say that my issue persists?
Sorry I'm pretty new to GitHub, so I'm not sure on the etiquette or what's normal.
