### ISSUE TITLE
[Anti-adblock] brainly.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2443]
### URL(s) where the issue occurs

`https://brainly.com/question/10346999`

### Describe the issue

Anti-adblock, refresh the page 4 times to trigger. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/40877427-e20a1714-663d-11e8-9aaf-f2c8d2a1484a.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.8

### Settings

All default

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/40879538-ed8b4176-66a1-11e8-9088-a3edf7a8dac4.png)

Without login.

**Comment by zaphodbeebblebrox** [comment]
`||brainly.*/app/js/*$script,first-party`

**Comment by okiehsch** [comment]
@krystian3w the fix -  https://github.com/uBlockOrigin/uAssets/commit/111ded98bf2a1f56b0f4e91096bf2eb2cf8430e4 - also works for the polish version on my end.
