### ISSUE TITLE
cargurus.com: detection

### ISSUE THREAD

**Issue by storjak** [uBlockOrigin/uAssets#24443]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cargurus.com/Cars/new/searchresults.action?sourceContext=homePageNewCarTab_false_0&selectedEntity=&zip=56273`

### Category

detection

### Description

Cargurus home page works fine, but searching for a new, or other vehicle redirects to a simple page that only states "Please enable JS and disable any ad blocker"  I don't have any Javascript services disabled.

### Other extensions used

BetterTTV 7.6.5
Close Duplicate Tab 2.5
DarkCloud - SoundCloud Dark Mode 1.6.4
Disconnect 20.3.1.1
Earth View from Google Earth 3.1.1
Flip this 0.3.3
Google Analytics Opt-out Add-on (by Google) 5
Google Docs Offline 1.78.1
Indie Wiki Buddy 3.8.0
Media Harvest : twitter Media Downloader 4.2.7
PayPal Honey 16.6.2
Rakuten 5.46.0
Reddit Enhancement Suite 5.24.6

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 155330
 cosmetic: 47310
 scriptlet: 21676
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 86697-45, 2m
  easyprivacy: 52729-653, 2m
  plowe-0: 3549-376, 2m
  ublock-badware: 8986-18, 2m
  ublock-filters: 39147-372, 2m
  ublock-privacy: 1035-5, 2m
  ublock-quick-fixes: 131-3, 2m
  ublock-unbreak: 2382-15, 2m
  urlhaus-1: 31295-0, 2m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 630 ms (selfie)
 maxAssetCacheWait: 282 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
