### ISSUE TITLE
flight.com.gr: detection

### ISSUE THREAD

**Issue by amigaflame** [uBlockOrigin/uAssets#24445]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://flight.com.gr/`

### Category

detection

### Description

part of the lower screen is blocked with a message 

### Other extensions used

i don't care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 161997
 cosmetic: 85166
 scriptlet: 27778
 html: 2116
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27392-94, now
  adguard-mobile-app-banners: 5314-34, now
  adguard-other-annoyances: 14747-300, now
  adguard-widgets: 2594-45, now
  easylist-annoyances: 4704-1172, now
  easylist-chat: 198-28, 41m
  easylist-newsletters: 7485-2124, now
  easylist-notifications: 3103-1789, now
  ublock-annoyances: 5897-183, now Δ
 default:
  user-filters: 8-0, never
  ublock-filters: 39264-397, now Δ
  ublock-badware: 9058-1, now Δ
  ublock-privacy: 1026-5, now Δ
  ublock-unbreak: 2441-4, now Δ
  ublock-quick-fixes: 132-4, now Δ
  easylist: 86697-14196, now Δ
  easyprivacy: 52729-124, now Δ
  urlhaus-1: 31295-0, 41m
  plowe-0: 3549-991, now
  GRC-0: 1095-25, 41m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 750 ms
 maxAssetCacheWait: 366 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  flight.com.gr: 2
  doubleclick.net: 1
  google.com: 7
  googletagmanager.com: 2
  orangeclickmedia.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by amigaflame** [comment]
it is ok like this, so i guess it is a problem of "i don't care about cookies" expansion. Thanx a lot
