### ISSUE TITLE
publicearn.com: ads

### ISSUE THREAD

**Issue by tetoksn** [uBlockOrigin/uAssets#24451]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://publicearn.com/vRauC`

### Category

ads

### Description

Ads

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 282951
 cosmetic: 343294
 scriptlet: 59423
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  EST-0: 464-1, 34m
  FIN-0: 2281-0, 34m
  FRA-0: 24764-261, 34m
  GRC-0: 1095-0, 34m
  HRV-0: 397-2, 34m
  HUN-0: 2104-5, 34m
  IDN-0: 9990-1, 34m
  IND-0: 13422-2, 34m
  IRN-0: 3049-10, 34m
  ISL-0: 194-1, 34m
  ISR-0: 1879-0, 34m
  ITA-0: 8685-23, 34m
  [40 lists not shown]: [too many]
 default:
  easylist: 86751-920, now
  easyprivacy: 52748-1105, now
  plowe-0: 3550-25, 41m
  ublock-badware: 9171-5, now
  ublock-filters: 39189-945, now
  ublock-privacy: 1034-119, now
  ublock-quick-fixes: 135-2, now
  ublock-unbreak: 2384-15, now
  urlhaus-1: 15585-5, now
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4528 ms (selfie)
 maxAssetCacheWait: 1087 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  clarity.ms: 1
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###ast-scroll-top
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361
