### ISSUE TITLE
ublock origin seems to be unable to block ads from looped videos

### ISSUE THREAD

**Issue by gn4rpz** [uBlockOrigin/uAssets#24450]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

This might be a bit niche so I get why it was missed, but ads play between loops when I loop a video.

### A specific URL where the issue occurs.

```yaml
everywhere, so long as the video is looping
```

### Steps to Reproduce

1. Right click video and set it to loop
2. Let the video play a couple times
3. Eventually, an ad will appear.

### Expected behavior

The ad shouldn't be there. I'm actually appalled that youtube added them here to begin with.

### Actual behavior

There are random and entirely unskippable ads. It also freezes, and I have to pause and unpause to get it working again.

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 132263
 cosmetic: 47206
 scriptlet: 20276
 html: 1861
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39295-119, 2h.54m Δ
  ublock-badware: 9058-18, 2h.54m Δ
  ublock-privacy: 1025-4, 2h.54m Δ
  ublock-unbreak: 2441-2, 2h.54m Δ
  ublock-quick-fixes: 133-5, 2h.54m Δ
  easylist: 86733-155, 2h.54m Δ
  easyprivacy: 52737-63, 2h.54m Δ
  urlhaus-1: 8150-5, 11h.52m
  plowe-0: 3549-991, 11h.52m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 270 ms (selfie)
 maxAssetCacheWait: 100 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Follow this thread: https://github.com/uBlockOrigin/uAssets/issues/20586

**Comment by gn4rpz** [comment]
> Follow this thread: #20586

I'm having trouble telling where I'm supposed to look here; there's a lot of technical stuff there that I don't understand and don't know how to apply to my situation.

**Comment by stephenhawk8054** [comment]
Comment your issue in that thread. Don't comment here.
