### ISSUE TITLE
freeshot.live: detection

### ISSUE THREAD

**Issue by djjjjjjjpj** [uBlockOrigin/uAssets#24455]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.freeshot.live/live-tv/bein-sports-1-fr/disable-adblock`

### Category

detection

### Description

site ne fonctionne plus correctement et en plus me detecte un bloqueur de pub que je n'est pas.

### Other extensions used

aucune autre

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 157385
 cosmetic: 53927
 scriptlet: 21864
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  ublock-filters: 39192-280, 40m Δ
  ublock-badware: 9171-1, 40m Δ
  ublock-privacy: 1034-2, 40m Δ
  ublock-unbreak: 2384-0, 40m Δ
  ublock-quick-fixes: 135-2, 40m Δ
  easylist: 86751-601, 40m Δ
  easyprivacy: 52748-641, 40m Δ
  urlhaus-1: 15585-5, 10m
  plowe-0: 3550-0, 10m
  FRA-0: 24764-381, 10m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 392 ms (selfie)
 maxAssetCacheWait: 148 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Don't open duplicated issues
