### ISSUE TITLE
wochenblitz.com: breakage

### ISSUE THREAD

**Issue by digitalray78** [uBlockOrigin/uAssets#24457]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wochenblitz.com/news/erschuetterung-schlangenbiss-4-meter-lange-python-in-firmentoilette-gefunden?utm_source=Wochenblitz+Newsletter+Thailand&utm_campaign=803e3c6de6-EMAIL_CAMPAIGN_2024_07_11_04_42&utm_medium=email&utm_term=0_34a48916ce-803e3c6de6-%5BLIST_EMAIL_ID%5D`

### Category

breakage

### Description

website pops up that an ad blocker is used and the website will not work when using an adblocker and asks to turn off ublock.

### Other extensions used

none for blocking

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 139872
 cosmetic: 47323
 scriptlet: 21710
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86751-561, 1h.14m Δ
  easyprivacy: 52748-641, 1h.14m Δ
  plowe-0: 3550-0, now
  ublock-badware: 9171-6, 1h.14m Δ
  ublock-filters: 39192-280, 1h.14m Δ
  ublock-privacy: 1034-2, 1h.14m Δ
  ublock-quick-fixes: 135-2, 1h.14m Δ
  ublock-unbreak: 2384-0, 1h.14m Δ
  urlhaus-1: 15585-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1680 ms (selfie)
 maxAssetCacheWait: 991 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  wochenblitz.com: 9
  doubleclick.net: 1
  ezodn.com: 3
  ezoic.net: 7
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
 extended:
  ##.ezoic-adpicker-ad
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ##.ez-sidebar-wall
  ##.ez-sidebar-wall-ad
  ##span[data-ez-ph-id]
  ##span[id^="ezoic-pub-ad-placeholder-"]
```
</details>

**Comment by DocSniper** [comment]
AdBlock detection active again on https://www.wochenblitz.com/ with ads showing despite uBlock Origin.

Environment: uBO 1.65.0, Firefox 141, Arch Linux, filter lists updated

Screenshot attached:

<img width="2479" height="1726" alt="Image" src="https://github.com/user-attachments/assets/0ef894d7-bd2b-455e-b1c3-96640970f3c6" />

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

---

Ok, I can reproduce it now.
