### ISSUE TITLE
watchseriesx.to: nuisance

### ISSUE THREAD

**Issue by LivingAtHome** [uBlockOrigin/uAssets#24468]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://watchseriesx.to/movie`

### Category

nuisance

### Description

Overlays and pop-ups 

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 128
filterset (summary):
 network: 142876
 cosmetic: 55562
 scriptlet: 20368
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39757-180, 1h.24m Δ
  ublock-badware: 9252-2, 1h.24m Δ
  ublock-privacy: 1025-4, 1h.24m Δ
  ublock-unbreak: 2448-4, 1h.24m Δ
  ublock-quick-fixes: 143-4, 1h.24m Δ
  adguard-mobile: 9596-11, now
  easylist: 86808-237, 1h.24m Δ
  easyprivacy: 52758-71, 1h.24m Δ
  urlhaus-1: 17070-5, 1h.24m
  plowe-0: 3544-1063, now
filterset (user): [array of 1 redacted]
trustedset:
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2854 ms
 maxAssetCacheWait: 519 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  amung.us: 1
  cubeuptownpert.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can reproduce. These work for me

```adb
watchseriesx.to##+js(nowoif, _blank)
watchseriesx.to##+js(set-cookie, __pf, 1)
```
