### ISSUE TITLE
baidu.com: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#24465]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.baidu.com/baidu?ie=utf-8&wd=steam%E6%B8%B8%E6%88%8F%E4%B8%AD%E5%BF%83`

### Category

ads

### Description

ads

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/user-attachments/assets/6ae4100d-7b31-4e57-9b23-cd775263897e

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 130
filterset (summary):
 network: 231530
 cosmetic: 235032
 scriptlet: 51846
 html: 2117
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83112-4134, now
  adguard-spyware-url: 1585-123, now
  adguard-spyware: 78703-1560, now
  curben-phishing: 512-3, 1m
  fanboy-cookiemonster: 51323-191, 1m
  ublock-cookies-easylist: 1261-3, 1m
  adguard-social: 23107-56, 1m
  fanboy-social: 16393-754, 1m
  fanboy-thirdparty_social: 68-19, 1m
  adguard-popup-overlays: 27417-1049, 1m
  adguard-mobile-app-banners: 5319-25, 1m
  adguard-other-annoyances: 14757-427, 1m
  [6 lists not shown]: [too many]
 default:
  user-filters: 20-0, never
  ublock-filters: 39313-119, now
  ublock-badware: 9173-1, now
  ublock-privacy: 1024-4, now
  ublock-unbreak: 2445-2, now
  ublock-quick-fixes: 142-4, now
  easylist: 86800-2213, now
  easyprivacy: 52758-30502, 1m
  urlhaus-1: 16665-5, 1m
  plowe-0: 3550-1085, 2m
  CHN-0: 26649-227, 1h.34m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 555 ms (selfie)
 maxAssetCacheWait: 120 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  baidu.com: 18
  bdstatic.com: 2
 extended:
  ##.ad-widget
  ###content_left > div:not([class]) > div[data-placeid]
  ###content_left > .result ~ div:not([class]):not([style])
  ##.result-op[tpl="right_game_recommend"]
  ##style[id*="s-m"] + div[id^="m"]
  ##div[id$="_canvas"]
  ##.c-container:has(.t > a[data-landurl])
  ###content_right > table > tbody > tr > td > div:not(#con-ar):no…
  ##div:not([id]) > style[id^="s-"] + div[id]
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you reproduce it?

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/85be545419a26bc0479772e7cd4b6c9a789ee9b8
