### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by sleaze** [uBlockOrigin/uAssets#24464]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.reddit.com/r/dogpictures/submit/?type=TEXT`

### Category

breakage

### Description

Unable to create posts with ublock enabled, but it works fine when ublock is disabled.

Firefox latest: 128.0 (64-bit)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Not needed.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 140969
 cosmetic: 47282
 scriptlet: 20285
 html: 1861
listset (total-discarded, last-updated):
 default:
  user-filters: 74-5, never
  ublock-filters: 39312-120, 22m Δ
  ublock-badware: 9173-1, 22m Δ
  ublock-privacy: 1025-4, 22m Δ
  ublock-unbreak: 2445-2, 22m Δ
  easylist: 86790-175, 22m Δ
  easyprivacy: 52751-63, 22m Δ
  plowe-0: 3550-991, now
  urlhaus-1: 16665-5, 22m
  ublock-quick-fixes: 136-5, 22m Δ
filterset (user): [array of 74 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1032 ms (selfie)
 maxAssetCacheWait: 123 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  reddit.com: 1
  redditstatic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/5a74fa13740d89b6f74548e02a478010c786408d
