### ISSUE TITLE
wetransfer.com: nuisance

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#24460]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wetransfer.com/`

### Category

nuisance

### Description

Cookie notice

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/3dbb69a7-1ef9-4cef-ada9-86184c32ba70)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 145544
 cosmetic: 123490
 scriptlet: 31135
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51313-228, 5m
  ublock-cookies-easylist: 1261-0, 5m
  fanboy-social: 16384-11, 5m
  easylist-annoyances: 4704-26, 5m
  easylist-chat: 199-0, 5m
  easylist-newsletters: 7487-15, 5m
  easylist-notifications: 3104-160, 5m
  ublock-annoyances: 5957-50, 5m
 default:
  user-filters: 0-0, never
  ublock-filters: 39192-115, 5m
  ublock-badware: 9171-6, 5m
  ublock-privacy: 1034-7, 5m
  ublock-unbreak: 2386-22, 5m
  ublock-quick-fixes: 138-4, 5m
  easylist: 86753-590, 5m Δ
  easyprivacy: 52748-793, 5m Δ
  urlhaus-1: 16970-0, 5m
  plowe-0: 3550-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3614 ms (selfie)
 maxAssetCacheWait: 617 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  wetransfer.com: 1
  adzerk.net: 1
  googlesyndication.com: 1
```
</details>

**Comment by krystian3w** [comment]
Works fine on Firefox.

Try avoid open this page as homepage or from e-mail/comunicator (chat) until uBo are ready in Chromium.

**Comment by SeriousHoax** [comment]
> Works fine on Firefox.
> 
> Try avoid open this page as homepage or from e-mail/comunicator (chat) until uBo are ready in Chromium.
> 
> https://downdetector.pl/status/wetransfer/ - regional down today https://downdetector.com/status/wetransfer/ - looks fine for USA or Canada.

Oh, so at the moment it's specific to uBO in Chrome only? I also reported this for AdGuard and they had to change the previous rule:
https://github.com/AdguardTeam/AdguardFilters/commit/dd7bb1e83959bd64bb82035738f9451f807ac997

**Comment by xandaronox** [comment]
@stephenhawk8054  Can you add them into ublock cookie notices filters? I reported it already in adguard and it wont work because of 3th trusted rules.

```adb
pandotree.wetransfer.com#@%#//scriptlet('trusted-click-element', '#fides-banner-container .fides-reject-all-button', '!cookie:fides_consent')
wetransfer.com#@%#//scriptlet('trusted-click-element', '.terms-conditions button.transfer__button')
wetransfer.com#@%#//scriptlet('trusted-click-element', '.fides-tcf-banner-container .fides-banner-button-group > button.fides-reject-all-button')
```

<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/eb93b836-898f-48e6-bf7d-71ef4de33945)

</p>
</details> 

`https://wetransfer.com/downloads/5b791554f2f4090a9aeb165bdaa6aa5620250825175747/c348c8?t_exp=1756403867&t_lsid=982e4c2c-9d63-4e11-a946-56e98e1dd993&t_network=link&t_rid=YXV0aDB8NjEyNDFiYzVlM2U1OGQwMDY4OGE3NTEz&t_s=download_link&t_ts=1756144687`

**Comment by stephenhawk8054** [comment]
`#@%#` means disabling the filter, which means nothing because those filters are not used from beginning.

**Comment by xandaronox** [comment]
> `#@%#` means disabling the filter, which means nothing because those filters are not used from beginning.

@alex302 said it.
https://github.com/AdguardTeam/AdguardFilters/issues/212119#issuecomment-3228907706

**Comment by stephenhawk8054** [comment]
It's a typo. As I said, `#@##` means disabling the filters.

But anyways, I can't reproduce that screenshot on your side, even when I use VPN to Turkey or some other countries.
