### ISSUE TITLE
za.pinterest.com: detection

### ISSUE THREAD

**Issue by C-Puff** [uBlockOrigin/uAssets#24473]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://za.pinterest.com/`

### Category

detection

### Description

Pinterest is blocking me from using them until adblock is disabled. I was able to fool it by simply refreshing the page a few days ago but now it simply continues to block me upon refresh.

### Other extensions used

Enhancer for youtube
Malwarebytes
Ecosia
Better Twitter
Unhook
Return YouTube Dislike
Don't Accept WebP
ChatReplay
Thumbnail Ratio Bar for Youtube
Hide Shorts for Youtube
XKit Rewritten
uBlacklist
Tampermonkey
Minimal Twitter
Better TTV
User-Agent Switcher

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-07-13 at 18-59-39 (14) Pinterest](https://github.com/user-attachments/assets/51bf4c0d-0f98-4479-9e95-43693ef53181)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 141144
 cosmetic: 47219
 scriptlet: 20309
 html: 1861
listset (total-discarded, last-updated):
 default:
  user-filters: 8-1, never
  ublock-filters: 39313-119, now
  ublock-badware: 9192-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2445-2, now
  easylist: 86815-168, now
  easyprivacy: 52761-63, now
  urlhaus-1: 16785-0, now
  plowe-0: 3544-989, now
  ublock-quick-fixes: 150-5, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 32 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2487 ms
 maxAssetCacheWait: 947 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  pinterest.com: 4
 extended:
  ##[data-grid-item]:has([data-test-pin-id] [data-test-id^="one-ta…
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
