### ISSUE TITLE
withnews.jp: nuisance

### ISSUE THREAD

**Issue by DaisukeDaisuke** [uBlockOrigin/uAssets#24476]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://withnews.jp/photo-gallery/1000000968/13?article=f0161214002qq000000000000000W00o10101qq000014427A
```

### Description

Every time I scroll through 3 or 4 images, I get a popup of the wreckage (I don't know if you can call this a popup...). The view is blocked until I click somewhere

Before adding filters, it must be ensured that normal articles are not breakage
`https://withnews.jp/article/f0161214002qq000000000000000W00o10101qq000014427A`

### Other extensions used

I verified using the new profile

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Desktop Screenshot 2024 07 14 - 19 22 17 14](https://github.com/user-attachments/assets/804e7239-b04e-4b63-8f03-458eb2fe77c1)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 143245
 cosmetic: 60024
 scriptlet: 21955
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39232-290, 12m
  ublock-badware: 9190-1, 12m
  ublock-privacy: 1034-2, 12m
  ublock-unbreak: 2386-0, 12m
  ublock-quick-fixes: 149-2, 12m
  easylist: 86835-574, 12m
  easyprivacy: 52761-640, 12m
  urlhaus-1: 16815-5, 12m
  plowe-0: 3544-0, 12m
  JPN-1: 15002-57, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1778 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  withnews.jp: 2
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  im-apps.net: 2
  nakanohito.jp: 1
  outbrain.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.article-ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…

```
</details>

**Comment by DaisukeDaisuke** [comment]
When I auto generate it using a picker, it looks like this
```
withnews.jp##.is-active.pickup-news-modal
```

**Comment by stephenhawk8054** [comment]
@Yuki2718
