### ISSUE TITLE
jasminetesttry.com: detection voe.sx 

### ISSUE THREAD

**Issue by CySecZH** [uBlockOrigin/uAssets#24479]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jasminetesttry.com/`

### Category

detection

### Description

New voe.sx domain

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 145403
 cosmetic: 60665
 scriptlet: 20376
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39760-180, 2h.53m Δ
  ublock-badware: 9186-2, 2h.53m Δ
  ublock-privacy: 1026-4, 2h.53m Δ
  ublock-unbreak: 2448-4, 2h.53m Δ
  ublock-quick-fixes: 150-4, 2h.53m Δ
  adguard-mobile: 9597-11, now
  easylist: 86815-237, 2h.53m Δ
  easyprivacy: 52761-71, 2h.53m Δ
  urlhaus-1: 17285-5, now
  plowe-0: 3544-1063, now
  DEU-0: 7524-50, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4156 ms (selfie)
 maxAssetCacheWait: 88 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  ads-twitter.com: 2
  detentionquasipairs.com: 2
  imasdk.googleapis.com: 2
  sharethis.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed 13 hours ago already https://github.com/uBlockOrigin/uAssets/commit/d785f826a1dc8ad1578cf03f303692c26cd5a7fb
