### ISSUE TITLE
psa.wf: breakage

### ISSUE THREAD

**Issue by gigachaand** [uBlockOrigin/uAssets#24477]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://psa.wf/movie/the-boy-and-the-heron-kimitachi-wa-do-ikiru-ka-2023/`

### Category

breakage

### Description

Can u make bypass for these site ... 
There are two types of shorten... 

Click on the download button..... 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 127
filterset (summary):
 network: 151344
 cosmetic: 122661
 scriptlet: 29382
 html: 2119
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
 added:
  adguard-spyware-url: 1585-123, 1h.49m
  fanboy-cookiemonster: 67584-16443, 1h.48m
  ublock-cookies-easylist: 1302-12, 1h.49m
  fanboy-social: 16416-25, 1h.48m
  easylist-annoyances: 4721-52, 1h.49m
  easylist-chat: 199-0, 1h.49m
  ublock-annoyances: 5935-80, 1h.49m
  IND-0: 13436-16, 1h.49m
 default:
  user-filters: 1-0, never
  ublock-filters: 39764-120, 49m Δ
  ublock-badware: 9248-1, 1h.48m
  ublock-privacy: 1027-4, 1h.48m
  ublock-unbreak: 2448-2, 1h.48m
  ublock-quick-fixes: 149-4, 1h.48m
  easylist: 86835-171, 1h.14m Δ
  easyprivacy: 52762-63, 49m Δ
  urlhaus-1: 16815-5, 1h.48m
  plowe-0: 3544-989, 1h.48m
filterset (user): [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1523 ms
 maxAssetCacheWait: 967 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  doubleclick.net: 2
  google.com: 7
  youtube.com: 3
 extended:
  ##.wc_social_plugin_wrapper
  ##.social-tooltip
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
For shortener sites, comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361 

Don't open new issues about these shorteners sites.
