### ISSUE TITLE
en.y2mate.is: detection

### ISSUE THREAD

**Issue by blehhguh** [uBlockOrigin/uAssets#24487]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://en.y2mate.is/v64/`

### Category

detection

### Description

Attempting to download mp3/mp4, it says "Please disable adblock to download videos.".

### Other extensions used

Tampermonkey, disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://blehhguh.blahaj.shop/veggiedance/tfalrlpo.png/

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 141128
 cosmetic: 47313
 scriptlet: 21771
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 39237-115, now
  ublock-badware: 9251-1, now
  ublock-privacy: 1034-2, now
  ublock-unbreak: 2388-2, now
  ublock-quick-fixes: 134-2, now
  easylist: 86850-557, now
  easyprivacy: 52769-801, now
  urlhaus-1: 16635-0, now
  plowe-0: 3544-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1286 ms (selfie)
 maxAssetCacheWait: 113 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  clarity.ms: 1
  googlesyndication.com: 1
  paidlemirkily.com: 1
 extended:
  ##+js(abort-on-property-write, afStorage)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by blehhguh** [comment]
> I can't reproduce

Open website mentioned above > Enter YT url (eg. https://www.youtube.com/watch?v=YE7VzlLtp-4) > Message shows "Please disable adblock to download videos" above Video/Audio tabs

Video to the steps if needed: https://blehhguh.blahaj.shop/veggiedance/5dak26ua.mp4

**Comment by stephenhawk8054** [comment]
As said, I still can't reproduce it

![image](https://github.com/user-attachments/assets/a103d1cc-78a1-4997-ad5f-e1d493cc8087)
