### ISSUE TITLE
github.com: breakage

### ISSUE THREAD

**Issue by chemputer** [uBlockOrigin/uAssets#24489]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://github.com/Edditoria/markdown-plus-plus/tree/master`

***All*** GitHub repos are affected.

### Category

breakage

## List creation window hangs when uBlock Origin's Cosmetic Filtering is enabled on Firefox

Normally, when you create a list, you click the little down arrow next to the Star button: ![Star button.](https://i.imgur.com/Xr9g03s.png)

It'll then show a dropdown where you can select from your previously created lists or create a new list. Selecting create a new list,
then making a title and description for the new list (the content of those fields doesn't matter, I tried it 5 different times, and it only worked with Cosmetic Filtering disabled.) Normal behavior is for the box to immediately close after you click the Create button: ![Create test box
/](https://i.imgur.com/ciy7DIL.png)

However, if you have Cosmetic Filtering enabled, as is default behavior, it hangs, and just stays like this indefinitely, until you refresh the page. It *does* create the list immediately, adding the repo to the list, but the create list box never closes. ![hung create list box](https://i.imgur.com/lfwfGvw.png) 

Disabling Cosmetic Filtering fixes the issue. I do not know if there is a more granular approach.

### Other extensions used

- Bitwarden
- Sponsorblock
- Return YouTube Dislike
- TamperMonkey
- Firefox Multi-Account Containers

None except Bitwarden are active on GitHub.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 162956
 cosmetic: 47215
 scriptlet: 20268
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39284-119, 1h.2m Δ
  ublock-badware: 9290-1, 1h.2m Δ
  ublock-privacy: 1025-4, 1h.2m Δ
  ublock-unbreak: 2447-2, 1h.2m Δ
  ublock-quick-fixes: 130-2, 1h.2m Δ
  easylist: 86856-170, 1h.2m Δ
  easyprivacy: 52766-63, 1h.2m Δ
  urlhaus-1: 38460-0, now
  plowe-0: 3545-989, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1110 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 48
 no-cosmetic-filtering: true
 network:
  github.com: 48
```
</details>

**Comment by krystian3w** [comment]
It's strange that I don't see any filters in your config log.

**Comment by stephenhawk8054** [comment]
The issue occurs to me even when I turn off uBO completely in browser's extension settings

**Comment by krystian3w** [comment]
It would be useful to test how it works on Chrome, then it is worth giving a label specific to Firefox
