### ISSUE TITLE
fullmatch.info: ads

### ISSUE THREAD

**Issue by god-damnit** [uBlockOrigin/uAssets#24482]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fullmatch.info/`

### Category

ads

### Description

Ads are shown even with uBlock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/3e45ce78-ff33-4538-b1ab-1df940e8f111)
![image](https://github.com/user-attachments/assets/dc4e295b-bc7f-4dc3-8845-91b514f9d487)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 226851
 cosmetic: 173698
 scriptlet: 25871
 html: 1983
listset (total-discarded, last-updated):
 added:
  ALB-0: 309-0, now
  ara-0: 2337-15, now
  BGR-0: 1040-4, now
  CHN-0: 26669-199, now
  CZE-0: 834-12, now
  DEU-0: 7524-37, now
  EST-0: 465-62, now
  FIN-0: 2287-1, now
  FRA-0: 24627-455, 1m
  GRC-0: 1095-8, now
  HRV-0: 397-4, now
  HUN-0: 2120-18, now
  [24 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39320-119, 51m Δ
  ublock-badware: 9253-1, 51m Δ
  ublock-privacy: 1026-4, 51m Δ
  ublock-unbreak: 2445-2, 51m Δ
  ublock-quick-fixes: 135-2, 51m Δ
  easylist: 86847-170, 51m Δ
  easyprivacy: 52763-63, 51m Δ
  urlhaus-1: 17285-5, now
  plowe-0: 3544-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 365 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
fullmatch.info##[class*="wp-image"]
```

@ryanbr
