### ISSUE TITLE
filehaus.top: nuisance

### ISSUE THREAD

**Issue by detyso** [uBlockOrigin/uAssets#24483]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://filehaus.top/`
https://filehaus.su/

### Category

nuisance

### Description

ad banner showing

### Other extensions used

bitwarden captcha

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-07-14 192136](https://github.com/user-attachments/assets/bba8c34b-56f3-4a66-b93a-6796298c1f5b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 141738
 cosmetic: 47208
 scriptlet: 20309
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39320-119, now
  ublock-badware: 9253-1, now
  ublock-privacy: 1025-4, now
  ublock-unbreak: 2445-2, now
  ublock-quick-fixes: 134-2, now
  easylist: 86850-170, now
  easyprivacy: 52769-63, now
  urlhaus-1: 17285-5, now
  plowe-0: 3544-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 582 ms (selfie)
 maxAssetCacheWait: 112 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by CoolestGuy94** [comment]
> [x] I did not answer truthfully to ALL the above checkboxes.
Checks out.
