### ISSUE TITLE
[nsfw] 1337x.to: userscripts breakage

### ISSUE THREAD

**Issue by XyuBAM** [uBlockOrigin/uAssets#24485]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://1337x.to/`

### Category

breakage

### Description

uBlock seems to be causing fatal error accessing `localStorage` via a userscript

### Other extensions used

Tampermonkey v5.2.2

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a3e6952c-fe2d-4cc1-91b7-40cc8e5e0cc8)

![image](https://github.com/user-attachments/assets/f540e851-bf6f-4c39-a262-228aae902cdd)

![image](https://github.com/user-attachments/assets/74d99e22-372b-47e6-88cc-0b1b67ce1dfb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 141751
 cosmetic: 47322
 scriptlet: 21773
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39237-280, 7m
  ublock-badware: 9251-1, 7m
  ublock-privacy: 1034-2, 7m
  ublock-unbreak: 2388-0, 6m Δ
  ublock-quick-fixes: 149-2, 6m Δ
  easylist: 86835-556, 6m Δ
  easyprivacy: 52762-640, 6m Δ
  urlhaus-1: 17285-5, 7m
  plowe-0: 3544-0, 7m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 300 ms
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(remove-node-text, script, style)
  ##+js(abort-on-stack-trace, document.createElement, _0x)
  ##+js(no-window-open-if, , 1)
  ##+js(abort-on-property-read, afScript)
  ##+js(no-setTimeout-if, adb)
  ##+js(nowebrtc)
  ##+js(abort-on-property-read, AaDetector)
  ##+js(addEventListener-defuser, popstate)
  ##+js(abort-on-stack-trace, navigator, FingerprintJS)
  ##+js(abort-on-stack-trace, localStorage, .js)
  ##+js(abort-on-stack-trace, onload, .js)
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
```
</details>

**Comment by stephenhawk8054** [comment]
Which exact userscript are you using?

**Comment by krystian3w** [comment]
Looks as private user script (wrong name in `// @name` line).

**Comment by XyuBAM** [comment]
No particular script, just a simple test script that contains `localStorage` in it. Metadata is default provided by the Tampermonkey when created a new script. The only change was made is removed anonymous function to simplify the example:
```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      2024-07-12
// @description  try to take over the world!
// @author       You
// @match        https://1337x.to/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @run-at       document-start
// @ grant        none
// @grant unsafeWindow
// ==/UserScript==

localStorage;

console.log("hello world");
alert("hello world");
```

**Comment by stephenhawk8054** [comment]
I can't reproduce with your script. It shows the alert correctly for me

Screenshot:

<details>

![image](https://github.com/user-attachments/assets/f4a456f1-e356-4f24-8013-6a0ec9ff6504)

</details>

**Comment by XyuBAM** [comment]
Strange, I'm testing with unchanged new profile (with turn on developer mode), default settings in both uBlock Origin 1.58.0 and Tampermonkey 5.2.2 (no other extensions installed):
![image](https://github.com/user-attachments/assets/e9336f9d-c319-473c-865d-d324c79587eb)

Both Chrome and Edge - same result on 2 computers.

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
1337x.*#@#+js(aost, localStorage, .js)
1337x.*##+js(aost, localStorage, /https:\/\/1337x\.to\/\S+\.js/)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by XyuBAM** [comment]
Yes, that worked. Thank you.
But I'm curious why this seems to only affect this domain?

**Comment by stephenhawk8054** [comment]
The filter aborts the execution of a popup script link in this site. The `.js` is to match the stack trace but it can include other userscript extensions' script links.
