### ISSUE TITLE
carscoops.com: ads

### ISSUE THREAD

**Issue by JamisonsBrain** [uBlockOrigin/uAssets#24493]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.carscoops.com/`

### Category

ads

### Description

Ads still showing, even after picking them and manually blocking. 

### Other extensions used

LastPass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 163006
 cosmetic: 47329
 scriptlet: 21728
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 86858-45, now
  easyprivacy: 52784-652, now
  plowe-0: 3545-375, now
  ublock-badware: 9286-18, now
  ublock-filters: 39199-369, now
  ublock-privacy: 1035-5, now
  ublock-quick-fixes: 134-1, now
  ublock-unbreak: 2388-15, now
  urlhaus-1: 38460-0, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 57 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  adpushup.com: 1
  adrecover.com: 3
  criteo.net: 1
  doubleclick.net: 1
  ebxcdn.com: 1
  googletagmanager.com: 4
  oko.net: 1
  taboola.com: 1
 extended:
  ##.adwrap
  ##._ap_apex_ad
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/519cadf0fc6ee15a96d466e30a92d141ad93aa62
