### ISSUE TITLE
telescopius.com: ads

### ISSUE THREAD

**Issue by C7C8** [uBlockOrigin/uAssets#24494]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://telescopius.com/deep-sky-objects?types=&page=1&con=&cat=&comet_orbit=&hour_max=sunrise&hour_min=sunset&min_alt=15&min_alt_minutes=120&mag_min=1&mag_max=20&mag_unknown=1&size_unknown=1&subr_unknown=1&order=popularity&order_asc=1&results_per_page=10&list_ids=&size_max=18000&size_min=600`

### Category

ads

### Description

Ads still appear; it appears this site is using shadow roots (probably it's based on React or Angular or similar) and UBlock does not seem able to work around it. I cannot create simple filters for the custom elements present in the DOM to block them either.

### Other extensions used

* Bypass Paywalsl Clean
* Cookie AutoDelete
* CORS Everywhere
* Firefox Multi-Account Containers
* FoxReplace
* HTTPS Everywhere
* Jazz-MIDI
* JetBrains Toolbox Extension
* KeePassXC-Browser
* Mendeley Web Importer
* Old Reddit Redirect
* Personas Plus
* Privacy Badger
* Recipe Filter
* Reddit Enhancement Suite
* Reddit Masstagger
* Regex Search
* Stop AutPlay Next for YouTube
* Tabby Cat
* Tamper Data for FF Quantum
* Tampermonkey
* The Camelizer
* Tree Style Tab
* uBlacklist
* User-Agent Switcher
* Viewhance
* VTT Enhancement Suite
* Vue.js devtools
* Web MIDI API
* YouTube NonStop

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 164751
 cosmetic: 69701
 scriptlet: 20277
 html: 1862
listset (total-discarded, last-updated):
 added:
  adguard-social: 23130-34, now
  fanboy-thirdparty_social: 68-3, now
  ublock-quick-fixes: 134-3, 13m Δ
 default:
  user-filters: 1127-6, never
  ublock-filters: 39284-128, 13m Δ
  ublock-badware: 9288-1, 13m Δ
  ublock-privacy: 1026-5, 13m Δ
  ublock-unbreak: 2447-2, 13m Δ
  easylist: 86858-170, 13m Δ
  easyprivacy: 52784-67, 13m Δ
  plowe-0: 3545-989, now
  urlhaus-1: 38460-0, now
filterset (user): [array of 1127 redacted]
trustedset:
 added: [array of 37 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 760 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  maps.googleapis.com: 1
  sentry-cdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
telescopius.com##tlc-ad-banner
```

@ryanbr
