### ISSUE TITLE
prisjakt.nu: ads

### ISSUE THREAD

**Issue by AdiProdan** [uBlockOrigin/uAssets#24496]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.prisjakt.nu/c/robotdammsugare?3666=104967%7C104012`

### Category

ads

### Description

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/ca39b16a-7d60-41f3-89e2-d53916c8ac2a">
add section still visible 

### Other extensions used

privacy badger, but tested with it on and off, no change

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 139762
 cosmetic: 47225
 scriptlet: 20272
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39283-119, now
  ublock-badware: 9291-1, now
  ublock-privacy: 1026-4, now
  ublock-unbreak: 2447-2, now
  ublock-quick-fixes: 137-2, now
  easylist: 86870-169, now
  easyprivacy: 52787-63, now
  urlhaus-1: 15235-0, 1h.1m
  plowe-0: 3545-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 526 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  prisjakt.nu: 1
  adnxs.com: 1
  appsflyer.com: 1
  cloudflareinsights.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  schibsted.com: 20
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `Frellwit's Swedish Filter` list and test again.
