### ISSUE TITLE
gamer.com.tw anti-adblock

### ISSUE THREAD

**Issue by procesx** [uBlockOrigin/uAssets#245]
### URL(s) where the issue occurs

`https://gnn.gamer.com.tw`
One of the subdomains.

### Describe the issue

The site will resort to deface all images when detects ads blocked and using EasyList + EasyList China does not work well due to Adblock Plus limitation.

### Versions

- Browser/version: Firefox 45.6.0
- uBlock Origin version: 1.10.4

### Settings

- Default settings with EasyList China

### Notes

There are two ways to reproduce the issue.

1. Add custom filter `gamer.com.tw##IMG[onload="AntiAd.check(this)"]`
2. Block `googlesyndication.com` at `gamer.com.tw`

Two filters work fine for me.
`gamer.com.tw##script:inject(abort-on-property-read.js, AntiAd.flag)`
`gamer.com.tw##IMG[onload="AntiAd.check(this)"]`

**Comment by gorhill** [comment]
I have not been able to reproduce the image defacement with default settings/lists + EasyList China + blocking `googlesyndication.com` in dynamic filtering pane. Being unable to reproduce gets in the way of testing solutions.

**Comment by procesx** [comment]
You can add custom filter `gamer.com.tw##IMG[onload="AntiAd.check(this)"]` and browse `https://gnn.gamer.com.tw` or `https://www.gamer.com.tw` to reproduce the issue too.

Block `googlesyndication.com` at `gamer.com.tw` is not able to reproduce the image defacement at `https://www.gamer.com.tw`

**Comment by procesx** [comment]
The site added an adblock warning below the web page recently.
![9ac2d554a9d4b4a6b9018f5ab1ba373f](https://cloud.githubusercontent.com/assets/24699693/23709494/9731b4c8-0454-11e7-9eee-58287691ffa7.PNG)
This filter works fine for me.
`gamer.com.tw##script:inject(abort-on-property-read.js, mercyadblock)`

**Comment by SMed79** [comment]
> The site added an adblock warning below the web page recently.

Is this message limits the site functionality?

`@@||gamer.com.tw^$generichide`

**Comment by procesx** [comment]
>Is this message limits the site functionality?

No, but it is annoying at this site. The adblock warning is still triggered based on its value even if turn off.
I would prefer to abort anti-adblock related script execution rather than whitelist.
