### ISSUE TITLE
zippyshare.day: detection

### ISSUE THREAD

**Issue by glassesglasses8** [uBlockOrigin/uAssets#24500]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.zippyshare.day

### Category

detection

### Description

Add block message on zippyshare.day wont go away

### Other extensions used

no other extentions used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e3cb5dac-49bd-4459-bf0d-27cc687da834)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 151267
 cosmetic: 160511
 scriptlet: 34093
 html: 2118
listset (total-discarded, last-updated):
 added:
  adguard-social: 23130-1223, 9m
  adguard-cookies: 30361-1645, 9m
  ublock-cookies-adguard: 1271-14, 9m
  adguard-popup-overlays: 27446-1029, 9m
  adguard-mobile-app-banners: 5331-36, 9m
  adguard-other-annoyances: 14777-415, 9m
  adguard-widgets: 2605-48, 9m
  fanboy-thirdparty_social: 68-4, 9m
  easylist-annoyances: 4713-1184, 9m
  easylist-chat: 199-28, 9m
  fanboy-cookiemonster: 51334-19825, 9m
  ublock-cookies-easylist: 1266-1266, 9m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39283-320, 18m Δ
  ublock-badware: 9347-1, 18m Δ
  ublock-privacy: 1026-5, 18m Δ
  ublock-unbreak: 2447-3, 18m Δ
  ublock-quick-fixes: 140-2, 18m Δ
  easylist: 86870-14166, 18m Δ
  easyprivacy: 52787-65, 18m Δ
  urlhaus-1: 15235-0, now
  plowe-0: 3545-990, now
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6900 ms (selfie)
 maxAssetCacheWait: 4088 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 no-popups: true
 network:
  acscdn.com: 1
  doubleclick.net: 4
  googlesyndication.com: 5
  googletagmanager.com: 1
  pubtrky.com: 2
  yandex.ru: 1
```
</details>

**Comment by glassesglasses8** [comment]
please fix this issue

**Comment by stephenhawk8054** [comment]
Test link: `https://www.zippyshare.day/ect1bKztArviA5m/file`
