### ISSUE TITLE
thehill.com: breakage

### ISSUE THREAD

**Issue by hsrstud** [uBlockOrigin/uAssets#24513]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thehill.com/policy/national-security/4776277-former-cia-analyst-charged-foreign-agent-south-korea/`

### Category

breakage

### Description

When I open a news story on this website in a new tab and then switch to that tab, I'm not able to scroll the webpage.  I need to refresh the webpage and then I can scroll.

Here is the starting page from which I open up new tabs.

`https://thehill.com/news/`

If I disable uBlock, this problem goes away and I'm able to scroll new tabs in TheHill fine.

### Other extensions used

Dark reader
swipeGesture
Google Search Fixer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 128
filterset (summary):
 network: 141452
 cosmetic: 55557
 scriptlet: 20344
 html: 1863
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39709-120, now
  ublock-badware: 9341-1, now
  ublock-privacy: 1028-4, now
  ublock-unbreak: 2451-2, now
  ublock-quick-fixes: 140-2, now
  adguard-mobile: 9598-74, now
  easylist: 86870-238, now
  easyprivacy: 52789-71, now
  urlhaus-1: 15470-0, now
  plowe-0: 3546-1063, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2592 ms
 maxAssetCacheWait: 33 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 41
 network:
  thehill.com: 7
  amazon-adsystem.com: 1
  chartbeat.com: 2
  civicscience.com: 2
  confiant-integrations.net: 2
  dmpxs.com: 1
  googletagmanager.com: 2
  htlbid.com: 2
  imasdk.googleapis.com: 4
  minute.ly: 1
  nexstardigital.net: 3
  onesignal.com: 1
  permutive.app: 2
  sail-horizon.com: 2
  springserve.com: 2
  stickyadstv.com: 1
  taboola.com: 2
  teads.tv: 2
  wp.com: 2
 extended:
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.ad-unit--leaderboard
  #@#.ad-unit
  ##+js(abort-current-script, atob)
```
</details>

**Comment by hsrstud** [comment]
Here is the starting page from which I open up new tabs. 

https://thehill.com/news/

**Comment by stephenhawk8054** [comment]
I can't reproduce either. Test with only uBO and its default settings (no other add-ons).
