### ISSUE TITLE
sonycrackle.com

### ISSUE THREAD

**Issue by Royal2000H** [uBlockOrigin/uAssets#2451]
### URL(s) where the issue occurs

`https://www.sonycrackle.com/snatch/2502116`

### Describe the issue

The video cannot load without disabling uBlock Origin. This is true for all the crackle pages I tried.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/822546/40881559-53336f0e-667e-11e8-99bf-159f035efb44.png)

### Versions

- Browser/version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- uBlock Origin version: 1.16.8

### Settings

- Should be default. All "built-in" uBlock filters enabled except "experimental", tried also with uBlock Annoyances filter disabled. EasyList and EasyPrivacy enabled. Malware Domains List and Malware domains enabled. Peter Lowe's ad and tracking server list enabled. Tried also enabling/disabling Adguard's and Fanboy's Annoyance lists.

### Notes

Works with uBlock disabled. Tried the filter changes described above.

**Comment by okiehsch** [comment]
The whole site does not work on my, end even if I disable uBlock.

Here is your link on my end with uBO disabled.
![unbenannt](https://user-images.githubusercontent.com/16838044/40881700-bae32b4a-66cd-11e8-87b2-c93e0fb5837d.JPG)

And here the homepage.
![unbenannt1](https://user-images.githubusercontent.com/16838044/40881722-537f6d28-66ce-11e8-878b-2e9729d10a88.JPG)

**Comment by Royal2000H** [comment]
Regional? I'm in the US, they may have geo-restrictions depending where you are.
Maybe you have another privacy/script-oriented extension at play here?

**Comment by okiehsch** [comment]
I have no other extension besides `uBO-extra` and `uBO-scope` installed, I tried u US-proxy and could not connect at all.

@zaphodbeebblebrox can you reproduce the issue?

**Comment by jspenguin2017** [comment]
I can confirm. Test link: `https://www.sonycrackle.com/playlist/2129410/2489564`. 
![image](https://user-images.githubusercontent.com/7283682/40882092-c39d8502-6694-11e8-8f3e-faf946d0b410.png)
![image](https://user-images.githubusercontent.com/7283682/40882095-d6268c0a-6694-11e8-8b1f-bdbc5ba10915.png)

**Comment by jspenguin2017** [comment]
Fix: 
```
@@||secure-dcr.imrworldwide.com/novms/js/2/ggcmb510$script,domain=sonycrackle.com
```
![image](https://user-images.githubusercontent.com/7283682/40882139-31b69424-6696-11e8-8fbe-080146ba5a3a.png)

**Comment by okiehsch** [comment]
Thx.

**Comment by Royal2000H** [comment]
Can confirm the fix works. Thank you @jspenguin2017
