### ISSUE TITLE
itv.com: ads / detection / breakages

### ISSUE THREAD

**Issue by daniel72100** [uBlockOrigin/uAssets#24517]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.itv.com/watch/agatha-christie's-poirot/L0830/L0830a0017`

### Category

detection

### Description

ITV can detect Ublocker and ask to deactivate it 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 140187
 cosmetic: 47339
 scriptlet: 20285
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39280-119, now
  ublock-badware: 9460-1, now
  ublock-privacy: 1028-4, now
  ublock-unbreak: 2448-2, now
  ublock-quick-fixes: 152-3, now
  easylist: 86900-168, now
  easyprivacy: 52897-70, now
  urlhaus-1: 15470-0, 42m
  plowe-0: 3546-990, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 236 ms (selfie)
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  amplitude.com: 6
  googletagmanager.com: 1
 extended:
  ##+js(json-prune, Playlist.ContentBreaks)
  ##+js(no-window-open-if)
```
</details>

**Comment by 1rv1n3** [comment]
![Capture](https://github.com/user-attachments/assets/b131c1ad-1986-4424-aba4-a0b989c4e570)

**Comment by stephenhawk8054** [comment]
I can't reproduce the breakage. I went to `https://www.itv.com/`, clicked on this show `https://www.itv.com/watch/changing-ends/10a3919/10a3919a0007` and the video plays normally for me. I went to the positions that have the dots which are the ads points, and it skips the ads correctly for me.

**Comment by Fit4GHub** [comment]
Weird I just tested it too and its not doing it now, hmmmm, if it does it again I'll try and use the UBO logger to capture what's going on.

Meanwhile thanks for looking into it again and I'll only update this again if the issue lasts longer than say 3 days to avoid wasting peoples time.

Many thanks.

**Comment by Kevbar3** [comment]
Can anyone help fix this detection? im using the most up to date filter lists and no other extensions/vpn etc. but it always detects it when i try play something and asks to disable before it can play

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by Kevbar3** [comment]
> Test again in a new browser profile with only uBO and its default settings.

I've just tested in a new browser profile and installed a fresh uBO and it worked! so i reset mine to default settings and its now working. Thanks!

**Comment by stephenhawk8054** [comment]
Please give exact link where you see the issue.

**Comment by mapx-** [comment]
no detection on my end for the new issues above

https://github.com/uBlockOrigin/uAssets/issues/32326
https://github.com/uBlockOrigin/uAssets/issues/32327

**Comment by MartinEden** [comment]
Weird. I had this problem yesterday as well and it's gone today. I wonder if ITV rolled it back?

**Comment by clearoak** [comment]
So I was watching Sharp on ITVX quite happily, no problem.   Then my son wants to watch Futurama and it detects UBO, which is the only extension on chrome, which is fully updated as of 17-apr-2026.   To try to make Futurama work, I totally wipe out all browsing history forever, (includes cookies, of course) then log back in.   Now it won't play either one.    Detects UBO.    Tried turning off all filtering via the toolbar icon, and it still detects it.    So, looks like Sharp was being routed through an old path, ITVX have updated their detection, and wiping out cookies somehow routed Sharp through the updated path.

**Comment by stephenhawk8054** [comment]
> Tried turning off all filtering via the toolbar icon, and it still detects it.

What happens if you turn off uBOL in `chrome://extensions` page?

**Comment by clearoak** [comment]
Ah, I mis-wrote and was editing as that comment came in.    It does not find it after going to no filter and wiping all history.   But plays ads.    In basic, it works and plays ads.   Then I tried optimal and it works and blocks ads, so basically, it works and I don't know what the problem was.   But Futurama won't work with the same tricks.   It claims the brand new up to date chrome is out of date.   Different problem, I think.

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBOL and its default settings.
