### ISSUE TITLE
itv.com: detection

### ISSUE THREAD

**Issue by Bowiewowie** [uBlockOrigin/uAssets#24529]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.itv.com/watch/love-island/2a3697/2a3697a0606`

### Category

detection

### Description

Using ad blocking?
To watch ITVX, you’ll need to remove any ad blocking software you have installed. Click on 'ITVX Help' below for how to do this, then come back and click on 'Refresh'.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Image 18-07-2024 at 11 49](https://github.com/user-attachments/assets/a23f36e1-ece0-4285-8dc5-11b04a247c78)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 140276
 cosmetic: 47506
 scriptlet: 21757
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87065-560, now
  easyprivacy: 52810-644, now
  plowe-0: 3546-0, now
  ublock-badware: 9534-1, now
  ublock-filters: 39261-281, now
  ublock-privacy: 1037-2, now
  ublock-quick-fixes: 156-0, 38m
  ublock-unbreak: 2389-0, now
  urlhaus-1: 15380-0, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3907 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  amplitude.com: 10
  conviva.com: 2
  googletagmanager.com: 2
 extended:
  ##+js(json-prune, Playlist.ContentBreaks)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed already: https://github.com/uBlockOrigin/uAssets/commit/b405253ac7ba33101e546f59dff6367bf227d1dd

Update your filter lists again.

---

Also, please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

> - [X] I did not answer truthfully to **ALL** the above checkboxes.
