### ISSUE TITLE
[nsfw] mirrored.to: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#24527]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mirrored.to/getlink/N7UOWFVC/164/?hid=LzE5b3ZjT3VYYmdvenFGZUUrckxiM3NUQWsxcWhGUThyMjNyWEVpYk9ITT0qOiraoq6TpsxPc%2BAU1DGKPDQT&tid=69bb02b6988cc610c67002b257427b84`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/84a10162-4c7c-49d4-80bb-af52ce94cfb9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 144583
 cosmetic: 107943
 scriptlet: 31663
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8793-0, 1h.26m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 208-1, 31m
  easylist-annoyances: 4609-14, 31m
  easylist-notifications: 3107-83, 31m
  fanboy-cookiemonster: 51342-225, 31m
  ublock-annoyances: 5976-23, 1h.27m Δ
  ublock-cookies-easylist: 1272-0, 31m
 default:
  user-filters: 10-0, never
  easylist: 87065-482, 1h.27m Δ
  easyprivacy: 52794-756, 1h.27m Δ
  plowe-0: 3546-0, 31m
  ublock-badware: 9458-2, 1h.27m Δ
  ublock-filters: 39258-467, 1h.27m Δ
  ublock-privacy: 1037-2, 1h.27m Δ
  ublock-quick-fixes: 155-0, 1h.27m Δ
  ublock-unbreak: 2389-3, 1h.27m Δ
  urlhaus-1: 15380-0, 1h.27m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 470 ms (selfie)
 maxAssetCacheWait: 226 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  fgfdrfl.cfd: 2
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
mirrored.to##form[action^="//filesdl.cloud/"]
```

@ryanbr
