### ISSUE TITLE
gothicbeauty.com: breakage

### ISSUE THREAD

**Issue by 777moneymaker** [uBlockOrigin/uAssets#24524]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gothicbeauty.com/`

### Category

breakage

### Description

Images in blog posts and images in thumbnails are not working

### Other extensions used

Privacty badger, clearurls

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/user-attachments/assets/aa7d3e52-9917-406c-978c-cecf10684ea9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 206944
 cosmetic: 104204
 scriptlet: 39169
 html: 1819
listset (total-discarded, last-updated):
 removed:
  ublock-unbreak: null
 added:
  adguard-generic: 83656-4082, now
  adguard-mobile: 9604-57, now
  adguard-spyware-url: 1586-122, now
  adguard-spyware: 78985-1511, now
  block-lan: 69-0, now
  curben-phishing: 543-1, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39340-119, now
  ublock-badware: 9460-1, now
  ublock-privacy: 1029-4, now
  ublock-quick-fixes: 155-3, now
  easylist: 87065-2283, now
  easyprivacy: 52794-30140, now
  urlhaus-1: 14290-0, now
  plowe-0: 3546-1157, now
  POL-0: 8758-244, now
  POL-2: 1283-103, now
filterset (user): [empty]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 537 ms (selfie)
 maxAssetCacheWait: 206 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  acint.net: 1
  doubleclick.net: 1
  google.com: 5
  youtube.com: 3
 extended:
  ##.td-a-rec
  ##img[width="728"][height="90"]
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
