### ISSUE TITLE
[nsfw] 18comic.vip: breakage

### ISSUE THREAD

**Issue by phantasmwww** [uBlockOrigin/uAssets#24526]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://18comic.vip/`

### Category

breakage

### Description

can't see the cover

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![QQ截图20240718100214](https://github.com/user-attachments/assets/877c710c-0996-4692-8198-1b9b00903406)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 155615
 cosmetic: 58300
 scriptlet: 22034
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39258-281, 16m Δ
  ublock-badware: 9458-1, 16m Δ
  ublock-privacy: 1037-2, 16m Δ
  ublock-unbreak: 2389-0, 16m Δ
  ublock-quick-fixes: 155-0, 16m Δ
  easylist: 87065-594, 1m
  easyprivacy: 52794-642, 16m Δ
  urlhaus-1: 15380-0, now
  plowe-0: 3546-0, now
  CHN-0: 26705-166, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1660 ms
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  18comic.vip: 1
  bullionglidingscuttle.com: 1
  clarity.ms: 1
  exoclick.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  magsrv.com: 2
 extended:
  ##.adsbyexoclick
  ##div[class="row"][style="display: flex;flex-wrap: wrap;"]
  ###guide-modal
  ##.row[style="display: flex;flex-wrap: wrap;"]
  ##a[href*="//"]:not([href*="comic."]) > img
  ##:has(> script + ins)
  ##.modal-body > ul.pop-list
  ##a[href^="https://l.hyenadata.com/"]
  ##a[href*=".erodatalabs.com/"]
  ##a[href*=".hyenadata.com/"]
  ##a[href*=".sng.link/"]
  #@#:has(> ins + script)
  ##+js(no-setTimeout-if, float_right > div)
  ##+js(abort-current-script, document.dispatchEvent, /getexoloade…
  ##+js(set-constant, adv_resize, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `18comic.vip##+js(set-constant, adv_resize, noopFunc)`

cc @Yuki2718 Does disabling the filter cause any issues?

**Comment by Yuki2718** [comment]
I don't see noticeble issue, disabled.

**Comment by phantasmwww** [comment]
> 我没有看到明显的问题，已被禁用。

thanks for your fix！

**Comment by Yuki2718** [comment]
> thanks for your fix！

The auto-update frequency of the Chinese filter is 5 days, so update Chinese filters manually in a few hours.
