### ISSUE TITLE
console.cloud.google.com: breakage

### ISSUE THREAD

**Issue by jukryt** [uBlockOrigin/uAssets#24533]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
console.cloud.google.com
```

### Description

The Cloud DNS section either does not open at all or opens with an error

### Other extensions used

tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/f5774ab5-f1fe-4536-8ac2-ebe4c96fac1d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 158868
 cosmetic: 68061
 scriptlet: 23217
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39261-281, 1h.26m Δ
  ublock-badware: 9534-1, 1h.26m Δ
  ublock-privacy: 1037-2, 1h.26m Δ
  ublock-unbreak: 2389-0, 1h.26m Δ
  ublock-quick-fixes: 156-0, 1h.26m Δ
  easylist: 87085-581, 1h.26m Δ
  easyprivacy: 52810-643, 1h.26m Δ
  urlhaus-1: 15380-0, 4h.17m
  plowe-0: 3545-0, 2d.17h.35m
  RUS-0: 40743-127, 1h.26m Δ
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 580 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
```
</details>

**Comment by jukryt** [comment]
You can create a new account or use your account. And use the trial for 90 days

**Comment by jukryt** [comment]
Adding console.cloud.google.com to the whitelist fixes the problem.

**Comment by mapx-** [comment]
@jukryt 

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by jukryt** [comment]
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 | \|\|play.google.com/log | -- | console.cloud.google.com | 1 | post | xhr | `https://play.google.com/log?format=json&hasfast=true&authuser=0` |
| +0 | \|\|play.google.com/log | -- | console.cloud.google.com | 1 | post | xhr | `https://play.google.com/log?format=json&hasfast=true&authuser=0` |
| +0 | googletagmanager_gtm.js:5 | << | console.cloud.google.com | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-5CVQBG&l=gtmDataLayer` |
| +0 | \|\|googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | console.cloud.google.com | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-5CVQBG&l=gtmDataLayer` |
| +0 | \|\|googletagmanager.com^ | -- | console.cloud.google.com | 3 | get | script | `https://www.googletagmanager.com/gtm.js?id=GTM-5CVQBG&l=gtmDataLayer` |
</details>

**Comment by mapx-** [comment]
test

`@@||googletagmanager.com/gtm.js$script,domain=console.cloud.google.com`

**Comment by mapx-** [comment]
@jukryt closing for now. Continue here with your feedback / comment.
