### ISSUE TITLE
northwestern.edu: breakage

### ISSUE THREAD

**Issue by NewoIsTaken** [uBlockOrigin/uAssets#24539]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://ugadmission.northwestern.edu/portal/visit
```

### Description

uBlock Origin is blocking the campus visit form's POST request upon submission. The specific date I used was August 23rd with the 12:30 tour and 4:00 engineering info session.

### Other extensions used

None that should interfere.
Font Fingerprint Defender
Return YouTube Dislike
User-Agent Switcher and Manager
Firefox Multi-Account Containers
Rebrandly
CORS Everywhere
DuckDuckGo Privacy essentials
Zotero Connector
Twich Chat pronouns
Plasma Integration

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 140403
 cosmetic: 47414
 scriptlet: 20295
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39343-119, 18m Δ
  ublock-badware: 9536-1, 18m Δ
  ublock-privacy: 1029-4, 18m Δ
  ublock-unbreak: 2448-2, 18m Δ
  ublock-quick-fixes: 156-3, 18m Δ
  easylist: 87085-172, 18m Δ
  easyprivacy: 52810-67, 18m Δ
  urlhaus-1: 15530-0, 18m
  plowe-0: 3546-990, 18m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 393 ms (selfie)
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `/visit?id=` in EP

```adb
@@||ugadmission.northwestern.edu/portal/visit$subdocument
```

@ryanbr

**Comment by NewoIsTaken** [comment]
Out of curiosity, do you know why this url was blocked in the first place?

**Comment by NewoIsTaken** [comment]
Also, not sure if this is helpful, but the specific POST request that is blocked is to this URL: `https://ugadmission.northwestern.edu/portal/visit?id=c679428d-aba3-4e31-846b-2dc023e6a78f&cmd=submit&output=xdm&embedElement=form_c679428d-aba3-4e31-846b-2dc023e6a78f`.

**Comment by stephenhawk8054** [comment]
The URL is not blocked, the URL path is just matched with the filter `/visit?id=` in EasyPrivacy list, probably due to some tracker links in the past have the same match.

**Comment by NewoIsTaken** [comment]
Ohhh now I see. That's why I couldn't find that specific URL in the filter lists, but `/visit?id=` does show up.
