### ISSUE TITLE
vw.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#2453]
### URL(s) where the issue occurs

`http://www.vw.com/find-a-dealer/`

### Describe the issue

Find a dealer, try to contact them. Submit button won't work.

### Notes

`@@btstatic.com`

**Comment by mapx-** [comment]
Where is that button ?

**Comment by nimasaj** [comment]
Cannot reproduce. Submit button is working for me.
`https://cdn.pbrd.co/images/HokXMtF.png`

**Comment by nimasaj** [comment]
@mapx- insert a zip code, (e.g. 53214) > click on a flag on the map > in the right pane, click on "Contact Dealer" > a new page opens and there is a submit button there.

**Comment by mapx-** [comment]
without whitelisting btstatic I cannot conform the address

`@@||btstatic.com/tag.js$script,domain=vw.com`
