### ISSUE TITLE
dreamdth.com, onlytech.com: detection

### ISSUE THREAD

**Issue by Manikandan-Vanniyar** [uBlockOrigin/uAssets#24538]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://onlytech.com/community/
https://dreamdth.com/community/
```

### Description

Ubo is getting detected in both these sites and it can only be solved by blocking the javascript in Ubo

### Other extensions used

Violetmonkey
Dark reader
Scroll anywhere

### Screenshot(s)

https://github.com/user-attachments/assets/d435e216-8f07-476a-a5a9-80aa993483fc
https://github.com/user-attachments/assets/e15e62f6-b998-4b74-baa2-847bfe3f8e60

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by sheikh-azharuddin** [comment]
these 2 sites are again detecting ublock

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue

![image](https://github.com/user-attachments/assets/8d73f5d3-04e1-41e0-8eea-b9f663af33e2)

**Comment by mapx-** [comment]
@sheikh-azharuddin 

reset uBO to defaults, do not use any other blocking extension, do not touch uBO settings, test again

**Comment by sheikh-azharuddin** [comment]
> @sheikh-azharuddin
> 
> reset uBO to defaults, do not use any other blocking extension, do not touch uBO settings, test again

Yep I have reset ublock origin to default also but getting same popup

**Comment by Manikandan-Vanniyar** [comment]
![Uploading Screenshot 2024-10-30 132504.png…]()

Once again these sites are detecting Ubo

**Comment by Manikandan-Vanniyar** [comment]
Once again getting the same popup "adblock detected".

**Comment by Manikandan-Vanniyar** [comment]
@mapx- 

![Screenshot_2024-10-31-14-00-09-82_9c7ad408470e52983cc8816adf9ff347](https://github.com/user-attachments/assets/79818fdc-e7fb-4968-8952-fa8d18199cd6)

Once again getting the popup adblock detected. tried in both default mode as well as in medium mode but no use.
