### ISSUE TITLE
Potential trackers

### ISSUE THREAD

**Issue by cOnRiTCh** [uBlockOrigin/uAssets#24548]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
pah3ots.tech
paham.tech
pahtag.tech
pahtbt.tech
pahtch.tech
pahtdz.tech
pahtef.tech
pahter.tech
pahtfi.tech
pahtgq.tech
pahthf.tech
pahtkm.tech
pahtky.tech
pahtlf.tech
pahtmb.tech
pahtnf.tech
pahtpw.tech
pahtqo.tech
paht.tech
pahtuo.tech
pahtuz.tech
pahtvs.tech
pahtwt.tech
pahtzc.tech
pahtzh.tech
palibzh.tech
htagpa.tech
aghtag.tech
agorahtag.tech
```

### Description

They load when visiting certain Greek websites like `enaklik.com`. Some websites load specific ones, while others seem more random in the domains they load, from what I understand.

For some reason, they are mostly six-letter domains that usually start with `pah` and always end with `.tech`, like the ones mentioned above.

What even are these `paht` and `.tech` domains? To me, they seem like they are trackers, because they having nothing to do with the content of the websites they're on. At this point, I even recommend a filter like `^pah.*\.tech$`.

On my main computer, I block the .tech TLD altogether, and I haven't ran into any issues with any website, so I recommend blocking these.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Do you any other websites that have this besides `enaklik.com`?
