### ISSUE TITLE
esscctv.com: nuisance

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#24544]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://www.esscctv.com/security-products-1907-HNC5241E-IR-28-SavvyTech-HNC5241E-IR-28-4MP-IP-Dome-Camera-with-WDR-2.8mm-Fixed-Lens.html`

### Category

nuisance

### Description

The site has an overlay that prevents copying and pasting text

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/b056dd67-e249-4631-93fc-f186973ab9b8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 140016
 cosmetic: 47416
 scriptlet: 20285
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  ublock-filters: 39340-119, 19m
  ublock-badware: 9192-1, 19m Δ
  ublock-privacy: 1025-4, 19m Δ
  ublock-unbreak: 2445-2, 19m Δ
  ublock-quick-fixes: 152-3, 19m
  easylist: 87096-172, 19m
  easyprivacy: 52761-63, 19m Δ
  urlhaus-1: 15530-0, 19m
  plowe-0: 3546-989, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 239 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  authorize.net: 3
  google-analytics.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed in `uBlock filters – Annoyances` list
