### ISSUE TITLE
caracoltv.com: breakage

### ISSUE THREAD

**Issue by Forero-0** [uBlockOrigin/uAssets#24543]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.caracoltv.com/senal-vivo
```

### Description

When playing the live feed of the page, it remains gray and does not load.
If I disable uBlock Origin, this problem goes away.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 142810
 cosmetic: 54275
 scriptlet: 22236
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39261-298, 16m
  ublock-badware: 9534-1, 16m
  ublock-privacy: 1037-2, 16m
  ublock-unbreak: 2389-0, 16m
  ublock-quick-fixes: 156-0, 16m
  easylist: 87086-611, 16m
  easyprivacy: 52810-657, 16m
  urlhaus-1: 15530-0, 16m
  plowe-0: 3546-0, 16m
  spa-0: 4065-5, 16m
  spa-1: 5826-191, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2489 ms
 maxAssetCacheWait: 25 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 2
  googletagmanager.com: 3
  imasdk.googleapis.com: 1
  mdstrm.com: 1
  mrf.io: 1
  navdmp.com: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
 extended:
  ##.GoogleDfpAd-Float-Content
  ##.GoogleDfpAd-Content
  ##.GoogleDfpAd
  ##.GoogleDfpAd-Float

```
</details>

**Comment by stephenhawk8054** [comment]
Needs Colombian IP.

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=mdstrm.com
```

cc @Yuki2718 For EL or Adguard Spanish?

**Comment by Yuki2718** [comment]
If breakage is due to EL, it's EL.

**Comment by Yuki2718** [comment]
@jellizaveta https://github.com/AdguardTeam/AdguardFilters/commit/0d678db86e8ab41dbbbfacc0ab2ff16ce9cf1972 is causing this, it the exception still needed?

**Comment by jellizaveta** [comment]
Was fixed, the rule has been removed

**Comment by Forero-0** [comment]
When I open an article that contains a video, the video stays grey and doesn’t play.

I use Edge

https://www.caracoltv.com/tu-nos-ves-caracol-te-ve/talento-de-caracol-television-fue-testigo-del-desove-de-los-corales-en-colombia-te-veo-bien-ed45

<details>
<summary>Screenshot(s)</summary>

<img width="1898" height="935" alt="Image" src="https://github.com/user-attachments/assets/58693fa6-2e31-42ce-be58-68ba6fa599e5" />

</details>

<details>

```yaml
uBlock Origin: 1.66.2
Chromium: 140
filterset (summary):
 network: 158540
 cosmetic: 49435
 scriptlet: 26062
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41024-82, 1h.34m Δ
  ublock-badware: 11264-31, 1h.34m Δ
  ublock-privacy: 3478-4, 1h.34m Δ
  ublock-unbreak: 2681-1, 1h.34m Δ
  ublock-quick-fixes: 307-0, 1h.34m Δ
  easylist: 80542-545, 1h.34m Δ
  easyprivacy: 54518-644, 1h.34m Δ
  urlhaus-1: 28450-5, 1h.34m
  plowe-0: 3421-0, now
  spa-0: 3705-10, now
  spa-1: 6374-264, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1457 ms
 maxAssetCacheWait: 388 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  amazon-adsystem.com: 1
  brightspotcdn.com: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  membrana.media: 1
  mgid.com: 1
  mrf.io: 1
  navdmp.com: 1
  rubiconproject.com: 2
  s3-sa-east-1.amazonaws.com: 1
  sentry.io: 1
 extended:
  ##.GoogleDfpAd-Content
  ##.GoogleDfpAd
  ##.GoogleDfpAd-Float
  ##.GoogleDfpAd-Float-Content
```
</details>

**Comment by Yuki2718** [comment]
Fixed by the Spanish list
