### ISSUE TITLE
lekulumovies.com: popups

### ISSUE THREAD

**Issue by semperfi1945** [uBlockOrigin/uAssets#24547]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lekulumovies.com/`

### Category

popups

### Description

Note: I apologize if this site counts as a hosting site, I'm just unsure as to what counts as a "hosting" site. 

This site loads up and after a few seconds something like an invisible window pops up, you can't click anywhere on the site because if you do, another tab opens (which then closes fast, though I assume it's ublock doing its job)

### Other extensions used

None, or at least none that would even remotely interfere with this site or ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 139935
 cosmetic: 47534
 scriptlet: 21785
 html: 0
listset (total-discarded, last-updated):
 added:
  curben-phishing: 523-0, now
 default:
  user-filters: 0-0, never
  easylist: 87110-472, 33m Δ
  easyprivacy: 52816-644, 33m Δ
  plowe-0: 3546-0, 6m
  ublock-badware: 9534-3, 33m Δ
  ublock-filters: 39265-368, 33m Δ
  ublock-privacy: 1057-2, 33m Δ
  ublock-quick-fixes: 159-0, 33m Δ
  ublock-unbreak: 2389-0, 33m Δ
  urlhaus-1: 14495-0, 11m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1148 ms (selfie)
 maxAssetCacheWait: 374 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 no-popups: true
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  neshigreek.com: 4
  rtmark.net: 4
```
</details>

**Comment by stephenhawk8054** [comment]
@ghajini Looks like it's also because `/^https?:\/\/[a-z]{8,15}\.[a-z]{2,3}\/5\/\d{6,7}(?:\?_=\d+)?$/$script,3p` only covers scripts while when sw loads the pp domain again, it loads in XHR

Does this work for you if sw is on?

```adb
/^https?:\/\/[a-z]{8,15}\.[a-z]{2,3}\/5\/\d{6,7}(?:\?_=\d+)?$/$script,xhr,3p
```

**Comment by semperfi1945** [comment]
Thanks a bunch fellas, working for me now!
