### ISSUE TITLE
[Anti-adblock] cellmapper.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2454]
### URL(s) where the issue occurs

`https://www.cellmapper.net/map?MCC=244&MNC=91&type=LTE&latitude=60.167579100000005&longitude=24.943804499999942&zoom=9&showTowers=true&clusterEnabled=true&tilesEnabled=true&heatMapEnabled=false&showOrphans=false&showNoFrequencyOnly=false&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=Last&showHex=false&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showBand=0&mapType=custom_map&showSectorColours=true`

### Describe the issue

Soft anti-adblock but show up on every refresh. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/40889631-a9930720-6727-11e8-9b17-e67936a0d3e0.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.8

### Settings

All default.

**Comment by zaphodbeebblebrox** [comment]
`cellmapper.net##script:inject(set-constant.js, adTestPass, true)`
