### ISSUE TITLE
itv.com: detection ongoing 19/07

### ISSUE THREAD

**Issue by Fit4GHub** [uBlockOrigin/uAssets#24546]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.itv.com/watch/love-island/2a3697/2a3697a0607`

### Category

detection

### Description

itv.com is still detecting ubo and blocking the feed until its disabled for that site
no other blockers running and default ubo setupin latest firefox
this has been the case every day for the last 3 days
im in the uk so not a geo issue
as soon as i disable ubo site works
otherwise it detects ubo and issues a window saying so
hope my report helps fix this and happy to check again if it helps

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://www.itv.com/watch/love-island/2a3697/2a3697a0607

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 139303
 cosmetic: 47417
 scriptlet: 20296
 html: 1862
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 39340-119, 3m
  ublock-badware: 9460-1, 3m
  ublock-privacy: 1029-4, 3m
  ublock-unbreak: 2448-2, 3m
  easylist: 87096-172, 3m
  easyprivacy: 52813-67, 3m
  urlhaus-1: 14495-0, 3m
  plowe-0: 3546-990, 3m
  ublock-quick-fixes: 158-3, 3m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 10 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2131 ms (selfie)
 maxAssetCacheWait: 714 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  amplitude.com: 9
  conviva.com: 2
  googletagmanager.com: 1
 extended:
  ##+js(json-prune, Playlist.ContentBreaks)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed already: https://github.com/uBlockOrigin/uAssets/commit/b405253ac7ba33101e546f59dff6367bf227d1dd

Update your filter lists again.

---

Also, please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

**Comment by Fit4GHub** [comment]
Hi just checked it again and can confirm its now fixed. Thanks so much for
your effort in resolving this.

Regards.

**Comment by Fit4GHub** [comment]
Hi recent fix has blocked the ads but now the player stops after the ads are blocked and only way to restart the stream is by refreshing the page. Once done the player restarts and plays on as if the ads had finished running.

Basically stream plays as expected then stops at ad break, will not moving onto the next section of steam unless page is manually refreshed.

Not urgent but would be great if this was also fixed.

Thanks again:-)
