### ISSUE TITLE
vccircle.com: ads

### ISSUE THREAD

**Issue by Stealthinator16** [uBlockOrigin/uAssets#24549]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vccircle.com/nazaratechnologybuys-out-promoters-in-paper-boat-raises-stake-to-100`

### Category

ads

### Description

adboxes are left behind on the webpage although the ads are blocked. 

### Other extensions used

I dont care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/2228c307-37ca-41af-82c8-3b28c3a00dca)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 156174
 cosmetic: 215847
 scriptlet: 34182
 html: 2123
listset (total-discarded, last-updated):
 added:
  adguard-social: 23160-50, now
  adguard-cookies: 30443-45, now
  ublock-cookies-adguard: 1274-14, now
  adguard-popup-overlays: 27505-982, now
  adguard-mobile-app-banners: 5340-24, now
  adguard-other-annoyances: 14807-409, now
  adguard-widgets: 2616-13, now
  fanboy-thirdparty_social: 68-3, now
  easylist-annoyances: 4623-295, now
  easylist-chat: 199-16, now
  fanboy-cookiemonster: 51370-3962, now
  ublock-cookies-easylist: 1274-1274, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 39365-119, 1h.46m Δ
  ublock-badware: 9536-1, 1h.46m Δ
  ublock-privacy: 1052-4, 1h.46m Δ
  ublock-unbreak: 2448-2, 1h.46m Δ
  ublock-quick-fixes: 163-3, 1h.46m Δ
  easylist: 87110-171, 1h.46m Δ
  easyprivacy: 52841-67, 1h.46m Δ
  urlhaus-1: 14985-0, now
  plowe-0: 3546-990, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 619 ms (selfie)
 maxAssetCacheWait: 367 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  clarity.ms: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 5
  htmedia.in: 1
  moengage.com: 1
 extended:
  ##a[href^="https://twitter.com/share"]
  ##a[href^="https://web.whatsapp.com/send?text="]
  ##a[href^="http://www.facebook.com/sharer.php?"]
  ##a[href^="http://www.linkedin.com/shareArticle"]
  ##a[href^="http://www.facebook.com/sharer.php"]
  ##a[href^="http://www.linkedin.com/shareArticle?"]
  ##div.ads_ads__qsWIu:nth-of-type(13)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
vccircle.com##.ads_ads__qsWIu
```

@ryanbr
