### ISSUE TITLE
freefontsfamily.net: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#24553]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://freefontsfamily.net/anurati-font-free-download/`

### Category

ads

### Description

ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a9c59976-b0a8-4fc1-b519-7cc196190e91)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 149155
 cosmetic: 164360
 scriptlet: 35242
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8797-11, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 208-0, now
  adguard-other-annoyances: 14810-8, now
  adguard-popup-overlays: 27508-928, now
  easylist-annoyances: 4624-180, now
  easylist-chat: 199-0, now
  easylist-newsletters: 7393-40, now
  easylist-notifications: 3109-199, now
  fanboy-cookiemonster: 51371-263, now
  fanboy-social: 16454-15, now
  ublock-annoyances: 5982-86, now
  ublock-cookies-easylist: 1274-0, now
 default:
  user-filters: 52-0, never
  easylist: 87117-638, now
  easyprivacy: 52842-731, now
  plowe-0: 3547-0, now
  ublock-badware: 9557-2, now
  ublock-filters: 39285-694, now
  ublock-privacy: 1057-2, now
  ublock-quick-fixes: 170-0, 1h.28m Δ
  ublock-unbreak: 2389-22, now
  urlhaus-1: 14985-0, now
filterset (user): [array of 52 redacted]
trustedset:
 added: [array of 36 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 288 ms (selfie)
 maxAssetCacheWait: 133 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  btloader.com: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  notifpush.com: 1
  onnetwork.tv: 1
  setupcmp.com: 2
  stpd.cloud: 2
 extended:
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##iframe[name="googlefcPresent"]
  ##.share-post
  ##.share-text
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
freefontsfamily.net##.code-block
```

@ryanbr

**Comment by stephenhawk8054** [comment]
Next time just report these ads at https://github.com/easylist/easylist/issues
