### ISSUE TITLE
galaxytranslations10.com: detection

### ISSUE THREAD

**Issue by gudgeme** [uBlockOrigin/uAssets#24552]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://galaxytranslations10.com/manga/i-became-a-genius-swordsman-in-the-pretty-girl-game/chapter-150/`

### Category

detection

### Description

Site detects uBlock and overlays an anti AdBlock Pop-up 

### Other extensions used

https://github.com/onikienko/TabHamster
https://mybrowseraddon.com/custom-useragent-string.html
https://betterttv.com

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 142289
 cosmetic: 52664
 scriptlet: 21793
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7519-1, 12m
  easylist: 87110-567, 40m Δ
  easyprivacy: 52841-653, 40m Δ
  plowe-0: 3547-0, 12m
  ublock-badware: 9534-1, 40m Δ
  ublock-filters: 39281-297, 40m Δ
  ublock-privacy: 1057-2, 40m Δ
  ublock-quick-fixes: 163-0, 40m Δ
  ublock-unbreak: 2389-2, 40m Δ
  urlhaus-1: 14985-0, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 926 ms (selfie)
 maxAssetCacheWait: 204 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  bidgear.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  pubfuture-ad.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by gudgeme** [comment]
Forgot to add:

uBlock Origin: 1.58.0
Chromium: 123
filterset (summary):
 network: 142289
 cosmetic: 52664
 scriptlet: 21793
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7519-1, 12m
  easylist: 87110-567, 40m Δ
  easyprivacy: 52841-653, 40m Δ
  plowe-0: 3547-0, 12m
  ublock-badware: 9534-1, 40m Δ
  ublock-filters: 39281-297, 40m Δ
  ublock-privacy: 1057-2, 40m Δ
  ublock-quick-fixes: 163-0, 40m Δ
  ublock-unbreak: 2389-2, 40m Δ
  urlhaus-1: 14985-0, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 926 ms (selfie)
 maxAssetCacheWait: 204 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  bidgear.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  pubfuture-ad.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]

**Comment by stephenhawk8054** [comment]
It's fixed already

https://github.com/uBlockOrigin/uAssets/commit/fc4540a7b08673007505333afed7eebce16f4b23

**Comment by gudgeme** [comment]
damn you guys work fast, thanks
