### ISSUE TITLE
tvtropes.org detects adblocking

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#2455]
### URL(s) where the issue occurs

`http://tvtropes.org/pmwiki/pmwiki.php/Wiki/SCPFoundation`

### Describe the issue

Visiting any site on tvtropes.org causes an obnoxious banner to be displayed at the bottom of every page. It can be dismissed, but every new page load brings it back.

### Screenshot(s)

![capture2](https://user-images.githubusercontent.com/16061266/40890151-5785bab4-673f-11e8-876b-2a7815657252.PNG)

### Versions

- Browser/version: Chrome 66.0.3359.181
- uBlock Origin version: 1.16.8

### Settings

- No changes from defaults

### Notes

Things I tried that didn't work:
* Disabling element hiding
* Whitelisting `http://static.tvtropes.org/design/js/ads.js`
* Blocking `https://contributor.google.com/scripts/`
* Blocking `raresummer.com`

Here's the JavaScript that I believe is responsible for this: https://gist.github.com/josephcsible/ab251fabc67035321ebbd79a67ea5022

**Comment by josephcsible** [comment]
This works, though it may be overkill (or possibly break things for logged-in users, not sure): `||tvtropes.org$inline-script`

**Comment by josephcsible** [comment]
No to both. I found another one that does though: `tvtropes.org##script:inject(setTimeout-defuser.js, .)`

It doesn't break the collapsibles.

**Comment by okiehsch** [comment]
I can not reproduce that banner on my end.
`tvtropes.org##script:inject(abort-on-property-read.js, Uint8Array)`
will break https://gist.github.com/josephcsible/ab251fabc67035321ebbd79a67ea5022

Does it fix your issue?

**Comment by josephcsible** [comment]
Yep, that works.
