### ISSUE TITLE
hwcooling.net: ads

### ISSUE THREAD

**Issue by BeachTrampoline** [uBlockOrigin/uAssets#24559]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hwcooling.net/en/big-little-ryzen-out-officially-phoenix-2-apu-with-zen-4c-cores/`

### Category

ads

### Description

top and right side showing ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 139782
 cosmetic: 47465
 scriptlet: 20340
 html: 1867
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 39378-119, 52m Δ
  ublock-badware: 9559-1, 52m Δ
  ublock-privacy: 1052-4, 52m Δ
  ublock-unbreak: 2448-2, 52m Δ
  ublock-quick-fixes: 170-3, 52m Δ
  easylist: 87154-171, 52m Δ
  easyprivacy: 52845-67, 52m Δ
  urlhaus-1: 14805-0, 35m
  plowe-0: 3547-989, 35m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 420 ms (selfie)
 maxAssetCacheWait: 131 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  hwcooling.net: 2
  ampproject.org: 3
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
 extended:
  ##.left-ad
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.right-ad
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
hwcooling.net##.banner_wrapper
hwcooling.net##.heureka-affiliate-category
```

@ryanbr

**Comment by stephenhawk8054** [comment]
@BeachTrampoline Next time, please report these ads at https://github.com/easylist/easylist/issues

**Comment by BeachTrampoline** [comment]
Thanks! I just clicked on "Report an issue" in my uBlock Firefox addon, how can I report to easylist with that?

**Comment by stephenhawk8054** [comment]
Just go to the link above and click on `New issue` button to report.
