### ISSUE TITLE
[NSFW] javwhores.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2456]
### URL(s) where the issue occurs

```
https://www.javwhores.com/
```

### Describe the issue

Popups / Popads and possibly other missed ads like banners etc on video pages / urls.

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default.

### Notes
Popups / Popads and possibly other missed ads like banners etc on video pages / urls.

**Comment by zaphodbeebblebrox** [comment]
```
||javwhores.com^$csp=script-src 'self' 'unsafe-inline' *.googleapis.com *.gstatic.com *.google.com
javwhores.com##.table
```
