### ISSUE TITLE
bakashi.tv: nuisance

### ISSUE THREAD

**Issue by JoaoLucasSR** [uBlockOrigin/uAssets#24564]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bakashi.tv/`

### Category

nuisance

### Description

Wait a few seconds after the page loads, and there will be a div that covers the entire page that is capturing the click to open the ad. the div's class is generated a new one with each reload.

### Other extensions used

KeePassXC-Browser

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/ef5dc34c-82cf-437c-a53e-b72bda252b0c)
![image](https://github.com/user-attachments/assets/ffb3cc75-f57f-47ce-b3c1-2a809803daa8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 141128
 cosmetic: 51441
 scriptlet: 20831
 html: 1869
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 39402-119, now
  ublock-badware: 9352-2, now
  ublock-privacy: 1053-4, now
  ublock-unbreak: 2449-2, now
  ublock-quick-fixes: 166-3, now
  easylist: 87165-171, now
  easyprivacy: 52845-67, now
  urlhaus-1: 15055-0, now
  plowe-0: 3547-989, now
  spa-1: 5826-85, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 290 ms (selfie)
 maxAssetCacheWait: 53 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 36
 no-cosmetic-filtering: true
 no-popups: true
 no-remote-fonts: true
 network:
  disqus.com: 3
  disquscdn.com: 3
  googlesyndication.com: 1
  googletagmanager.com: 2
  gstatic.com: 17
  jsdelivr.net: 2
  jwpsrv.com: 2
  kauraishojy.com: 2
  rtmark.net: 4
```
</details>

**Comment by fcap788** [comment]
Hello! The issue still happens in 10/14/2024, exactly the same.
