### ISSUE TITLE
sanctum.shop: breakage

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uAssets#24568]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sanctum.shop/en-at`

### Category

breakage

### Description

Cannot scroll the page.
Can with ublock disabled.

### Other extensions used

tampermonkey
hypestat
modify header value
return youtube dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 141565
 cosmetic: 107790
 scriptlet: 30240
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  block-lan: 69-0, now
  curben-phishing: 532-0, now
  fanboy-cookiemonster: 51386-225, now
  easylist-annoyances: 4630-16, now
  easylist-chat: 200-0, now
  easylist-newsletters: 7370-22, now
  easylist-notifications: 3109-84, now
  ublock-annoyances: 5982-29, 49m Δ
 default:
  user-filters: 3-0, never
  ublock-filters: 39322-290, 49m Δ
  ublock-badware: 9395-2, 49m Δ
  ublock-privacy: 1058-2, 49m Δ
  ublock-unbreak: 2390-0, 49m Δ
  ublock-quick-fixes: 166-0, 49m Δ
  easylist: 87166-205, 49m Δ
  easyprivacy: 52845-127, 49m Δ
  urlhaus-1: 15055-0, now
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1024 ms (selfie)
 maxAssetCacheWait: 290 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  sanctum.shop: 9
  googletagmanager.com: 1
  sendinblue.com: 2
  shopify.com: 2
  shopifysvc.com: 1
  sibautomation.com: 1
 extended:
  ###pandectes-banner
  ###gdpr-blocking-page-overlay
```
</details>

**Comment by mapx-** [comment]
add

`sanctum.shop##body:style(overflow: auto !important)`

@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/f7359cd3a633ad3f81b6017f39bd2a247d25f91f
