### ISSUE TITLE
bigpara.hurriyet.com.tr: ads

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#24569]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bigpara.hurriyet.com.tr/`

### Category

ads

### Description

The empty part at the top.

 `##.advMasthead` 

Adguard base filter has this filter, maybe it can be considered similar for Easylist. 

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![aaa](https://github.com/user-attachments/assets/cedb6be6-8e52-43a5-8f45-5435faaf5f6f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 141306
 cosmetic: 57766
 scriptlet: 23449
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13247-13, now
  easylist: 87166-562, now Δ
  easyprivacy: 52845-649, now Δ
  plowe-0: 3547-0, now
  ublock-badware: 9395-2, now Δ
  ublock-filters: 39322-291, now Δ
  ublock-privacy: 1058-2, now Δ
  ublock-quick-fixes: 166-0, now Δ
  ublock-unbreak: 2390-0, now Δ
  urlhaus-1: 15055-0, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 360 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  btloader.com: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  hurpass.com: 1
  medyanetads.com: 1
  taboola.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[data-ad-width]:not([style$="left: -10000px !important; top: -…
  ##.adRenderer
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-width]
```
</details>

**Comment by D4niloMR** [comment]
Enable AdGuard Turkish regional list.

**Comment by D4niloMR** [comment]
`https://bigpara.hurriyet.com.tr/` returns 403 without Turkish IP so I didn't test it there, anyway, should be reported at https://github.com/easylist/easylist/issues.

**Comment by punisher018** [comment]
I opened the topic so that Ublock's default filters can display websites correctly, or I can add it to the user filters as well. I made a suggestion for Easylist, that it could be put there if you see it appropriate. Maybe it will be added to the Base filter like Adguard. Maybe it will be filtered only for this site and not as a general filter. That's why I brought the topic here.

**Comment by D4niloMR** [comment]
Filter issues that doesn't require the extended syntax are preferred to be fixed in EasyList, which is enabled by default.
