### ISSUE TITLE
tvi.la: detection

### ISSUE THREAD

**Issue by KeremDgGG** [uBlockOrigin/uAssets#24560]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tvi.la/Zxp9jOYxc0`

### Category

detection

### Description

Detects ublock origin

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 130
filterset (summary):
 network: 142377
 cosmetic: 65999
 scriptlet: 22046
 html: 1868
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39827-120, now
  ublock-badware: 9346-2, now
  ublock-privacy: 1053-4, now
  ublock-unbreak: 2452-2, now
  ublock-quick-fixes: 170-3, now
  adguard-mobile: 9610-74, now
  easylist: 87155-240, now
  easyprivacy: 52845-75, now
  urlhaus-1: 14805-0, now
  plowe-0: 3547-1063, now
  TUR-0: 13247-33, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 305 ms (selfie)
 maxAssetCacheWait: 69 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  tvi.la: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  #@#.ad-unit
  #@#.banner-ads
  #@#.banner_ads
  #@#.ad-zone
  #@#.ad-space
```
</details>

**Comment by stephenhawk8054** [comment]
For future shortener sites, please comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361

Don't open new issues about these sites.
