### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by theslayer0439** [uBlockOrigin/uAssets#24567]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dropgalaxy.com/drive/lw2gvmdew35o`

### Category

Website detected the adblocker and telling me to turn off the ad blocker.

### Description

Website detected the adblocker and telling me to turn off the ad blocker.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/9748ee2c-4013-4308-ae0a-a9693607be2b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139911
 cosmetic: 47578
 scriptlet: 21817
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39322-120, 22m Δ
  ublock-badware: 9395-2, 22m Δ
  ublock-privacy: 1058-2, 22m Δ
  ublock-unbreak: 2390-0, 22m Δ
  ublock-quick-fixes: 166-0, 22m Δ
  easylist: 87166-558, 22m Δ
  easyprivacy: 52845-805, 22m Δ
  urlhaus-1: 15055-0, now
  plowe-0: 3547-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 862 ms (selfie)
 maxAssetCacheWait: 129 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 59
 network:
  4dex.io: 1
  a-ads.com: 1
  a-mo.net: 7
  a-mx.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  creativecdn.com: 4
  criteo.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  gstatic.com: 1
  id5-sync.com: 1
  imasdk.googleapis.com: 1
  pocpoc.io: 6
  quantumdex.io: 7
  vliplatform.com: 22
  vlitag.com: 2
 extended:
  ##+js(no-window-open-if)
  ##+js(set-constant, supportedBrowsers, )
  ##+js(set-constant, supportedTimezoness, [])
  ##+js(set-constant, userTimezoneOffset, )
  ##+js(addEventListener-defuser, visibilitychange)
  ##+js(set-local-storage-item, rateLimitData, $remove$)
  ##+js(set-constant, ads, yes)
  ##+js(trusted-replace-node-text, script, /\.cloudfront\.net|wind…
```
</details>

**Comment by JobcenterTycoon** [comment]
@BlazeFTL

**Comment by mapx-** [comment]
ask here for help: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by anburocky3** [comment]
Again they are not working today. @BlazeFTL 
https://dgdrive.pro/ysmmgbisss9e
