### ISSUE TITLE
anitube.vip, hinatasoul.com: detection

### ISSUE THREAD

**Issue by Hakkyon** [uBlockOrigin/uAssets#24575]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.hinatasoul.com/videos/381711
```
```yaml
https://www.anitube.vip/video/510222
```

### Category

detection

### Description

when I try to see a show/video on "hinatasoul.com" ublock is detected on dicasgostosas.com

### Other extensions used

none

### Screenshot(s)

![Captura de tela 2024-07-20 172024](https://github.com/user-attachments/assets/5e12d3a1-aefd-45ac-8cc1-c74268f731df)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139838
 cosmetic: 47578
 scriptlet: 21823
 html: 0
listset (total-discarded, last-updated):
 removed:
  spa-1: null
 default:
  user-filters: 5-1, never
  easylist: 87166-559, 59m Δ
  easyprivacy: 52845-643, 59m Δ
  plowe-0: 3544-0, 6d.20h.18m
  ublock-badware: 9395-2, 59m Δ
  ublock-filters: 39324-281, 59m Δ
  ublock-privacy: 1058-2, 59m Δ
  ublock-quick-fixes: 166-0, 59m Δ
  ublock-unbreak: 2390-0, 59m Δ
  urlhaus-1: 14985-0, 21h.9m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 583 ms (selfie)
 maxAssetCacheWait: 83 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 no-popups: true
 network:
  adligature.com: 2
  amazon-adsystem.com: 7
  demand.supply: 1
  doubleclick.net: 3
  outbrain.com: 1
  quantserve.com: 1
  srvtrck.com: 2
  waust.at: 1
 extended:
  ##.demand-supply
  ##.ad-1
  ##.ads-2
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(no-setTimeout-if, hasAdblock)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by LightnessSenpai** [comment]
I've created a issue reporting about this, but it's happening again. I don't know if I could just comment here.

**Comment by D4niloMR** [comment]
Yes, please continue here.

**Comment by LightnessSenpai** [comment]
> Yes, please continue here.

Okay.
I'm not used to GitHub so I hope you're patient. Haha.

**Comment by LightnessSenpai** [comment]
It's fixed! Thank you!

**Comment by LightnessSenpai** [comment]
It's happening again. It's detecting the uBlock.

**Comment by D4niloMR** [comment]
Do you see any ads? The player is not loading here. If so, 

```adb
||anicdn.net^$media,removeparam=wmsAuthSign
```

May fix it.

**Comment by LightnessSenpai** [comment]
> Do you see any ads with the filter added? The player is not loading here with or without uBO. If so,
> 
> ```
> ||anicdn.net^$media,removeparam=wmsAuthSign
> ```
> 
> May fix it.

It is showing a image saying that a adblock was detected.

**Comment by D4niloMR** [comment]
Test after adding this filter:

```adb
@@||ads.anitube.vip^$xhr,domain=anitube.*|hinatasoul.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by LightnessSenpai** [comment]
> Test after adding this filter:
> 
> ```
> @@||ads.anitube.vip^$xhr,domain=anitube.*|hinatasoul.com
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Worked like a charm. Thank you!

**Comment by JobcenterTycoon** [comment]
```
||popads.net/js/adblock.js$script,xhr,redirect-rule=prebid-ads.js
dicasgostosas.com##+js(nostif, hasAdblock)
```

?

**Comment by LightnessSenpai** [comment]
> ```
> ||popads.net/js/adblock.js$script,xhr,redirect-rule=prebid-ads.js
> dicasgostosas.com##+js(nostif, hasAdblock)
> ```
> 
> ?

Now it's showing a 5 seconds video saying to disable the adblocker. What a pain.
Is it for me to add this in the filters?

**Comment by gabriel-batistuta** [comment]
same problem here

**Comment by JobcenterTycoon** [comment]
I see its geo locked sorry.

**Comment by LightnessSenpai** [comment]
Geo locked? I don't understand. lol

**Comment by LightnessSenpai** [comment]
It's happening here as well:
https://www.dattebayo-br.com/videos/281925

**Comment by huyszn** [comment]
> Geo locked? I don't understand. lol

These sites block you from accessing them unless you are using a Brazil IP.

**Comment by D4niloMR** [comment]
Fixed for hinatasoul, anitube is not working.

**Comment by Beniih** [comment]
They're watching this issue closely. The site acripts has a lot of traps to ublock. I'm avoiding those sites for now on.

**Comment by LightnessSenpai** [comment]
> > Geo locked? I don't understand. lol
> 
> These sites block you from accessing them unless you are using a Brazil IP.

Aaaah. Can't you use a VPN or something?

**Comment by LightnessSenpai** [comment]
> They're watching this issue closely. The site scripts has a lot of traps to ublock. I'm avoiding those sites for now on.

Isn't there a way to hide this issue from them?

**Comment by LightnessSenpai** [comment]
> Fixed for hinatasoul, anitube is not working.

What about the Dattebayo-br?

**Comment by D4niloMR** [comment]
> What about the Dattebayo-br?

Added to the filters https://github.com/uBlockOrigin/uAssets/commit/b88e46ac1bf5a6cd739d931ae70f22e33e2df32b

**Comment by LightnessSenpai** [comment]
> > What about the Dattebayo-br?
> 
> Added to the filters [b88e46a](https://github.com/uBlockOrigin/uAssets/commit/b88e46ac1bf5a6cd739d931ae70f22e33e2df32b)

The button for update the filter list isn't appearing for me for some reason. I don't know why.

**Comment by D4niloMR** [comment]
You can also click on this link to update https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1

**Comment by LightnessSenpai** [comment]
> You can also click on this link to update https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1

Simply clicking it? Then it's done. But I managed to add the filters manually just like you advised me before.

**Comment by LightnessSenpai** [comment]
Ah, almost forgot to tell it's working again due to the filters, thanks. If something happens again I'll let you guys know about it.

**Comment by LightnessSenpai** [comment]
It's happening again on hinatasoul. They've changed the website instead of using the "dicasgostosas" they're using the "caroloportunidades.com.br".
I don't know much, but I think this will be easier to solve as the warning to disable the adblock seems simpler.
uBlock Origins still works on "dattebayo-br" though.

**Comment by LightnessSenpai** [comment]
It's fixed. TY.

**Comment by LightnessSenpai** [comment]
The extension It's being detected in Dattebayo-br. Just letting you know, @D4niloMR

**Comment by MandarimdoGitHub** [comment]
There is a piece of code that appears to have some kind of cache test on a website to see if the adblock is detectable:
![Copied_Item_1725486349538](https://github.com/user-attachments/assets/bfe40462-354b-4f47-8891-b979f935fc45)

**Comment by MandarimdoGitHub** [comment]
even after turning it off, it keeps saying it's on 
![Screenshot_20240904_201414_Firefox Beta](https://github.com/user-attachments/assets/2740f65c-9629-466f-948c-4b88b1cb66bb)

**Comment by gwarser** [comment]
Again? https://www.reddit.com/r/uBlockOrigin/comments/1hzxemn/hinata_soul_detected/

**Comment by D4niloMR** [comment]
I can't reproduce with https://github.com/uBlockOrigin/uAssets/commit/d7bbf7c36eea7fb2c60672473b1acd01245028d9 and AdGuard Spanish/Portuguese.

**Comment by D4niloMR** [comment]
> Again? https://www.reddit.com/r/uBlockOrigin/comments/1hzxemn/hinata_soul_detected/

The issue is that uBO on Opera addons is still stuck at 1.60.0 which doesn't have the required scriptlet `trusted-prevent-xhr`
