### ISSUE TITLE
account.bhvr.com: breakage

### ISSUE THREAD

**Issue by TickDracy** [uBlockOrigin/uAssets#24574]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://account.bhvr.com/`

### Category

breakage

### Description

This website doesn't load when using uBlock Origin. If I disable it, it works as expected.

### Other extensions used

- Augmented Steam
- Bitwarden
- Cookie Quick Manager
- DeArrow
- Facebook Container
- LanguageTool
- LibRedirect
- Reddit Enhancement Suite
- SponsorBlock
- Tampermonkey
- Return Youtube Dislikes
- Wayback Machine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 205701
 cosmetic: 220729
 scriptlet: 35260
 html: 2128
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 759-8, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2658-75, now
  https://raw.githubusercontent.com/brunomiguel/antinonio/master/antinonio.txt: 29-0, 13m
  https://raw.githubusercontent.com/ethan-xd/ethan-xd.github.io/master/fb.txt: 151-0, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/amazonannoyances.txt: 263-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 100282-17566, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-9282, now
  adguard-spyware-url: 1588-277, now
  adguard-spyware: 78995-621, now
  curben-phishing: 532-0, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39405-138, 13m Δ
  ublock-badware: 9397-2, 13m Δ
  ublock-privacy: 1053-58, 13m Δ
  ublock-unbreak: 2449-6, 13m Δ
  ublock-quick-fixes: 166-3, 13m Δ
  easylist: 87166-193, 13m Δ
  easyprivacy: 52845-30182, 13m Δ
  urlhaus-1: 15055-0, now
  plowe-0: 3547-1068, now
  spa-1: 5826-91, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 644 ms (selfie)
 maxAssetCacheWait: 206 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 2
  osano.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
