### ISSUE TITLE
mangagezgini.net: detection

### ISSUE THREAD

**Issue by Perseus0123** [uBlockOrigin/uAssets#24573]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mangagezgini.net/`

### Category

detection

### Description

The website detects Adblock.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 141216
 cosmetic: 48569
 scriptlet: 21819
 html: 0
listset (total-discarded, last-updated):
 removed:
  TUR-0: null
 default:
  user-filters: 2196-23, never
  ublock-filters: 39324-281, 12m
  ublock-badware: 9534-1, 13m
  ublock-privacy: 1058-2, 13m
  ublock-unbreak: 2389-0, 13m
  ublock-quick-fixes: 166-0, 13m
  easylist: 87154-558, 13m
  easyprivacy: 52841-644, 13m
  urlhaus-1: 15055-0, 13m
  plowe-0: 3547-0, 13m
filterset (user): [array of 1995 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1074 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  admatic.com.tr: 10
  flarby.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  ppcnt.pro: 2
 extended:
  ##.c-ads
  ##.body-top-ads
  ##.footer-ads
```
</details>

**Comment by D4niloMR** [comment]
@Perseus0123 Do you still reproduce the detection?

**Comment by Perseus0123** [comment]
Hey, there. I solved the problem after adding this filter, which some random guy made in reddit:

"mangagezgini.net##+js(aeld, DOMContentLoaded, adsbygoogle.js)
mangagezgini.net##+js(nostif, adsbygoogle.js)
"
