### ISSUE TITLE
dailycamera.com: breakage

### ISSUE THREAD

**Issue by NanoExplorer** [uBlockOrigin/uAssets#24576]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dailycamera.com/events-calendar/`

### Category

breakage

### Description

The calendar doesn't appear when ublock is enabled. As soon as I disable ublock with the giant power button, it works again. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 128
filterset (summary):
 network: 141132
 cosmetic: 55823
 scriptlet: 20425
 html: 1873
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39852-120, now
  ublock-badware: 9373-2, now
  ublock-privacy: 1054-4, now
  ublock-unbreak: 2453-2, now
  ublock-quick-fixes: 167-3, now
  adguard-mobile: 9612-75, now
  easylist: 87169-240, now
  easyprivacy: 52845-75, now
  urlhaus-1: 14915-0, now
  plowe-0: 3547-1063, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 20 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3706 ms (selfie)
 maxAssetCacheWait: 269 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 34
 network:
  dailycamera.com: 6
  amazon-adsystem.com: 1
  cityspark.com: 2
  criteo.net: 1
  doubleverify.com: 4
  google.com: 2
  googlesyndication.com: 8
  htlbid.com: 2
  msecnd.net: 2
  ntv.io: 1
  p-n.io: 2
  pranmcpkx.com: 1
  wp.com: 2
 extended:
  ##.dfp-ad
  ##.dfp-interstitial
  ##.dfp-top_leaderboard
  ###mobile-adhesion:not(#style_important)
  ###mobile-adhesion
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, n.trigger, 1)
  ##+js(set-constant, CnnXt.Event.fire, noopFunc)
  ##+js(set-session-storage-item, nxt_is_incognito, false)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||portal.cityspark.com/PortalScripts/DailyCamera$script,domain=dailycamera.com
@@||portal.cityspark.com/v1/event$xhr,domain=dailycamera.com
```

@ryanbr
