### ISSUE TITLE
funeraltimes.com: ads

### ISSUE THREAD

**Issue by Gummomarx** [uBlockOrigin/uAssets#24579]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.funeraltimes.com/death-notices/1/10/60`

### Category

ads

### Description

Zapped elements don't remain zapped in following visits.

### Other extensions used

See screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![001](https://github.com/user-attachments/assets/d931d353-c049-42e9-ab6c-05d122f14215)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 139782
 cosmetic: 47497
 scriptlet: 20361
 html: 1872
listset (total-discarded, last-updated):
 default:
  user-filters: 24-0, never
  ublock-filters: 39409-119, now
  ublock-badware: 9430-2, now
  ublock-privacy: 1052-4, now
  ublock-unbreak: 2450-2, now
  ublock-quick-fixes: 165-3, now
  easylist: 87174-171, now
  easyprivacy: 52854-67, now
  urlhaus-1: 14915-0, 1h.23m
  plowe-0: 3547-989, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 869 ms (selfie)
 maxAssetCacheWait: 215 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  chartbeat.net: 1
  dotmetrics.net: 1
  fuseplatform.net: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  typekit.net: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by AdblockReporters** [comment]
Try:
```
||www.funeraltimes.com/databaseimages/adv_$image
||www.funeraltimes.com/images/Banner-ad$image
www.funeraltimes.com##.ad
```

**Comment by Gummomarx** [comment]
Thank you for the very quick reply.  Isn't it possible to have it extend to the extra path?
**/1/10/60**

**Comment by AdblockReporters** [comment]
> Isn't it possible to have it extend to the extra path?

It is already across the entire domain
<img width="1160" alt="" src="https://github.com/user-attachments/assets/9211dab7-2994-4d1e-a57d-cc53b6139374">

**Comment by Gummomarx** [comment]
This is what I'm finding after www.funeraltimes.com##.ad:

https://github.com/user-attachments/assets/edbb2a28-5b25-4562-ad8e-374a2e37d98a

**Comment by AdblockReporters** [comment]
@Gummomarx you need to add all 3 rules:
```
||www.funeraltimes.com/databaseimages/adv_$image
||www.funeraltimes.com/images/Banner-ad$image
www.funeraltimes.com##.ad
```

the .ad one cleans up some empty divs, the two first blocks the ad images from loading

**Comment by Gummomarx** [comment]
Thanks very much - by belatedly learning how to add rules.

**Comment by Gummomarx** [comment]
I've fixed my confusing previous comment - apologies.
