### ISSUE TITLE
telecom.economictimes.indiatimes.com: nuisance

### ISSUE THREAD

**Issue by Ramar121** [uBlockOrigin/uAssets#24572]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://telecom.economictimes.indiatimes.com/
```

### Description

Getting newsletter nuisance while reading the articles

### Other extensions used

Violetmonkey
PopupOff
Dark reader

### Screenshot(s)

![Screenshot 2024-07-20 233215](https://github.com/user-attachments/assets/accab9c2-0699-459e-a46e-dd88af982fc2)

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 316553
 cosmetic: 253955
 scriptlet: 52236
 html: 2125
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 436-1, 1d.3h.3m
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/antimalware.txt: 42025-126, 40m
  https://raw.githubusercontent.com/iam-py-test/uBlock-combo/main/list.txt: 122567-21072, 39m
  adguard-generic: 83659-4216, 1d.1h.14m
  adguard-spyware-url: 1588-243, 1d.1h.14m
  block-lan: 68-0, 24d.11h.39m
  adguard-social: 23140-53, 3d.4h.7m
  adguard-cookies: 30452-47, 1d.1h.14m
  ublock-cookies-adguard: 1274-14, 1d.11h.20m
  adguard-popup-overlays: 27508-997, 1d.1h.14m
  adguard-other-annoyances: 14810-409, 1d.1h.14m
  adguard-widgets: 2616-13, 1d.1h.14m
  [8 lists not shown]: [too many]
 default:
  user-filters: 168-19, never
  ublock-filters: 39403-133, 2h.23m Δ
  ublock-badware: 9397-1025, 2h.23m Δ
  ublock-privacy: 1053-56, 2h.23m Δ
  ublock-unbreak: 2449-2, 2h.23m Δ
  ublock-quick-fixes: 166-3, 2h.23m Δ
  easylist: 87166-2718, 2h.23m Δ
  easyprivacy: 52845-163, 2h.23m Δ
  urlhaus-1: 15055-6, 39m
  plowe-0: 3546-1011, 3d.4h.7m
  IND-0: 13438-48, 39m
filterset (user): [array of 167 redacted]
trustedset:
 added: [array of 89 redacted]
switchRuleset:
 added: [array of 23 redacted]
hostRuleset:
 added: [array of 309 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2875 ms (selfie)
 maxAssetCacheWait: 448 ms
 cacheBackend: indexedDB
```
</details>

**Comment by AdblockReporters** [comment]
This seems to work: 
`telecom.economictimes.indiatimes.com##+js(no-setTimeout-if, '/cbsOnPortal\.includes/')`

<img width="639" alt="Screenshot 2024-07-21 at 18 01 22" src="https://github.com/user-attachments/assets/ceef4d56-920c-4f11-b8f1-4dd1ba38e7cd">

One would not want to override `is_loggedin`, the sessionStorage nor the window.cbsOnPortal as it seems to be used for other things
Since it calls the normal `EtB2b.system.login(t, 'show-login-layer-article')`, as a user can call themselves by clicking the login button, one would not want to override that either

So by preventing the showLoginLayeronArticle that fires to show the popup could work

**Comment by stephenhawk8054** [comment]
@ryanbr
