### ISSUE TITLE
upscaler.stockphotos.com: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#24581]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://upscaler.stockphotos.com/`

### Category

ads

### Description

When I upload a picture, it shows a video ad while it's being processed

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

I don't have anymore credits so I can't run another upscale, sorry

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 229027
 cosmetic: 245462
 scriptlet: 54635
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83697-7416, now
  adguard-spyware-url: 1588-123, now
  adguard-spyware: 78997-30768, now
  block-lan: 69-0, now
  curben-phishing: 526-0, now
  adguard-cookies: 30461-75, 1m
  ublock-cookies-adguard: 1280-0, 1m
  fanboy-cookiemonster: 51406-4004, 1m
  ublock-cookies-easylist: 1280-1280, 1m
  adguard-social: 23162-799, 1m
  fanboy-social: 16486-2, 1m
  adguard-popup-overlays: 27509-1750, 1m
  [9 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 39338-115, now
  ublock-badware: 9433-5, now
  ublock-privacy: 1057-2, now
  ublock-unbreak: 2391-2, now
  ublock-quick-fixes: 167-3, 37m Δ
  easylist: 87183-813, now
  easyprivacy: 52857-1014, now
  urlhaus-1: 14830-0, now
  plowe-0: 3547-459, 1m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 77 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1763 ms (selfie)
 maxAssetCacheWait: 670 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  cookie-script.com: 1
  crisp.chat: 1
  googletagmanager.com: 1
  sentry-cdn.com: 2
  wistia.com: 8
```
</details>

**Comment by AdblockReporters** [comment]
Try:
`upscaler.stockphotos.com##+js(json-prune, placements.processingFile)`

They inject processingFile thats loaded by parsing JSON from the dom. processingFile is an ad placement only for non-paying users

`||wistia.com^$domain=upscaler.stockphotos.com`
could also work, but risk breaking other video placements

<img width="333" alt="Screenshot 2024-07-22 at 00 20 12" src="https://github.com/user-attachments/assets/bd54bb68-d28f-4071-b49e-50555f89c224">
<img width="665" alt="Screenshot 2024-07-22 at 00 19 34" src="https://github.com/user-attachments/assets/bec9470b-bde0-4b04-a459-d590fff277aa">

**Comment by D4niloMR** [comment]
> Try:
> `upscaler.stockphotos.com##+js(json-prune, placements.processingFile)`

Works for me.
