### ISSUE TITLE
theplatform.kiwi: ads

### ISSUE THREAD

**Issue by aviationhacker** [uBlockOrigin/uAssets#24589]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://theplatform.kiwi/`

### Category

ads

### Description

Two ads in a landscape format on the page - one directly underneath the navigation bar (sometimes an in-house ad which I'm fine with, other times then external advertising), and one right down the bottom above the "Welcome" Section.
![The Platform Ads](https://github.com/user-attachments/assets/d1b28802-dfc2-4342-922e-d0b9c77f0a1a)

Also some ads on the Opinion and Pod pages - one on the left hand sidebar, have attached a screenshot :)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![The Platform Ads](https://github.com/user-attachments/assets/c13713f5-438e-4e2e-8804-f8a33f54ba67)
![The Platform Ads 2](https://github.com/user-attachments/assets/c49bdbc7-dde5-4e81-bbc6-69acd0d7b489)
![The Platform Ads 3](https://github.com/user-attachments/assets/c680a026-75aa-4873-b58c-19647be22554)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139901
 cosmetic: 47608
 scriptlet: 21839
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87198-49, now
  easyprivacy: 52862-657, now
  plowe-0: 3547-374, now
  ublock-badware: 9505-19, now
  ublock-filters: 39367-368, now
  ublock-privacy: 1057-5, now
  ublock-quick-fixes: 169-0, now
  ublock-unbreak: 2391-15, now
  urlhaus-1: 14890-0, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 171 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`||theplatform.kiwi/ads/$image`

@ryanbr
