### ISSUE TITLE
mp3-convert.org: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#24583]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mp3-convert.org/youtube-to-mp3-converterss/`

### Category

ads

### Description

There's a banner after submitting a video (YouTube) link that has a text in the bottom right corner saying "Advertisement". It can be easily removed by using: 
```txt
###banner
```

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/245f621b-99f6-4ab3-b053-a0b9eabfd4c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 228988
 cosmetic: 245462
 scriptlet: 54637
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83697-7417, now
  adguard-spyware-url: 1588-122, now
  adguard-spyware: 78997-30728, now
  block-lan: 69-0, now
  curben-phishing: 488-0, now
  adguard-cookies: 30461-76, now
  ublock-cookies-adguard: 1280-0, now
  fanboy-cookiemonster: 51406-4002, now
  ublock-cookies-easylist: 1280-1280, now
  adguard-social: 23162-798, now
  fanboy-social: 16486-8, now
  adguard-popup-overlays: 27509-1764, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 39339-115, now
  ublock-badware: 9434-7, now
  ublock-privacy: 1057-2, now
  ublock-unbreak: 2391-6, now
  ublock-quick-fixes: 169-3, now
  easylist: 87183-855, now
  easyprivacy: 52857-1014, now
  urlhaus-1: 14830-0, now
  plowe-0: 3547-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 77 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1763 ms (selfie)
 maxAssetCacheWait: 670 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
