### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by sunrah27** [uBlockOrigin/uAssets#24584]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.google.com/
https://www.google.com/?authuser=0
https://www.google.com/search?authuser=0&q=pizza+near+me&ct=ifl&cad=2:hungry&ei=hrGdZtSFKqmEhbIPhfWG4Aw&ved=0ahUKEwjU4NWwu7mHAxUpQkEAHYW6AcwQnRsIHw&rct=j
```

### Description

UBO is preventing Google dark mode from working. The issue sometimes does not occure. That is sometimes I will do a search from the search bar or from googles search bar and the result page is in dark mode. Or I'd go to google.com and the page is in dark mode.

I have disabled UBO and tested this and the issue is resolved. I even reset UBO and deleted all custom filters and the issue is still there.

Sometimes when I am on googles search page if I spam refresh suddenly the page will switch to dark mode and will stay in dark mode. 

If I go into my accounts setting and remove dark mode and then select dark mode nothing happens.

Only way to be certain dark mode will for is to go to Google.com, click settings on the bottom left and select dark mode. If I close the tab and return to Google.com almost everytime the option is set back to light mode.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139810
 cosmetic: 47625
 scriptlet: 21827
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 37-0, never
  ublock-filters: 39338-120, 4h.22m Δ
  ublock-badware: 9433-2, 4h.22m Δ
  ublock-privacy: 1057-2, 3h.22m Δ
  ublock-unbreak: 2391-0, 4h.22m Δ
  ublock-quick-fixes: 169-0, 4h.22m Δ
  easylist: 87183-559, 4h.22m Δ
  easyprivacy: 52857-805, 4h.22m Δ
  urlhaus-1: 14890-0, 22m
  plowe-0: 3546-0, 3d.2h.36m
filterset (user): [array of 37 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 242 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
see duplicate https://github.com/uBlockOrigin/uAssets/issues/24003

**Comment by sunrah27** [comment]
@mapx- you linked to a closed issue which doens't really help much. So am I to assume UBO is not interested into resolving this issue?

**Comment by mapx-** [comment]
it means we cannot reproduce your issue and you can read the old one for the various comments.
