### ISSUE TITLE
index.hr: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#24592]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.index.hr/`

### Category

nuisance

### Description

Cookie pop-up isn't blocked.

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/399084d8-7633-4961-bd62-1dff76ccc746)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 244722
 cosmetic: 248668
 scriptlet: 53047
 html: 2128
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-92, now
  adguard-generic: 83731-9085, now
  adguard-spyware-url: 1588-123, now
  adguard-spyware: 78997-25884, now
  curben-phishing: 502-0, now
  adguard-cookies: 30469-84, now
  ublock-cookies-adguard: 1280-14, now
  fanboy-cookiemonster: 51407-4003, now
  ublock-cookies-easylist: 1280-1280, now
  adguard-social: 23169-58, now
  fanboy-social: 16487-758, now
  adguard-popup-overlays: 27516-1113, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  ublock-filters: 39445-119, now
  ublock-badware: 9507-74, now
  ublock-privacy: 1052-21, now
  ublock-unbreak: 2450-3, now
  ublock-quick-fixes: 165-2, now
  easylist: 87198-23154, now
  easyprivacy: 52862-40513, now
  urlhaus-1: 15185-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 222 ms (selfie)
 maxAssetCacheWait: 129 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  index.hr: 3
  adpushup.com: 1
  adrecover.com: 1
  amazon-adsystem.com: 3
  cloudflareinsights.com: 2
  criteo.net: 2
  dotmetrics.net: 1
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  openx.net: 1
  permutive.app: 2
  privacy-center.org: 2
  rubiconproject.com: 2
 extended:
  ##.padding-bottom-25
  ##.categories > div.cube-holder:has(> div[data-css-class="google…
  ###fb-root:not(body):not(html)
```
</details>

**Comment by mapx-** [comment]
Necessary filter already included in `uBlock filters – Cookie Notices`
Reset uBO to defaults, test again

**Comment by Marko-98** [comment]
Banners at the bottom started appearing today. 

<details>
<summary>Screenshots</summary>

<img width="2559" height="1384" alt="Image" src="https://github.com/user-attachments/assets/9086ec49-f0b4-4c86-9578-f471c30824dd" />

<img width="2558" height="1386" alt="Image" src="https://github.com/user-attachments/assets/bdf60f80-8583-4338-af4e-9e321232e7aa" />

</details>

URL: https://www.index.hr/

<details>
<summary>uBlock Origin configuration</summary>

```yaml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 363477
 cosmetic: 232587
 scriptlet: 66467
 html: 3748
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-generic: 96137-5835, 3m
  adguard-spyware-url: 2526-134, 3m
  block-lan: 91-0, 3m
  curben-phishing: 163748-44, 4m
  adguard-cookies: 38580-99, 3m
  ublock-cookies-adguard: 5671-82, 3m
  adguard-social: 26338-42, 3m
  fanboy-social: 17625-860, 3m
  fanboy-thirdparty_social: 69-18, 3m
  adguard-popup-overlays: 31256-1041, 3m
  adguard-mobile-app-banners: 7386-107, 3m
  adguard-other-annoyances: 16092-306, 3m
  [7 lists not shown]: [too many]
 default:
  user-filters: 17-0, never
  ublock-filters: 52428-70, 3m
  ublock-badware: 10340-28, 3m
  ublock-privacy: 4022-2, 3m
  ublock-unbreak: 2827-1, 3m
  ublock-quick-fixes: 481-13, 4m Δ
  easylist: 97063-1212, 4m Δ
  easyprivacy: 55798-121, 3m
  urlhaus-1: 24325-6, 4m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 488 ms (selfie)
 maxAssetCacheWait: 260 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  index.hr: 1
  adrecover.com: 1
  cloudflareinsights.com: 2
  criteo.net: 2
  dotmetrics.net: 1
  doubleclick.net: 2
  facebook.net: 1
  freshatl.azurewebsites.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  openx.net: 1
  permutive.app: 2
  permutive.com: 1
  privacy-center.org: 1
  rubiconproject.com: 2
 extended:
  ##.categories > div.cube-holder:has(> div[data-css-class="google…
  ###fb-root:not(body):not(html)
  ##+js(trusted-set-cookie, euconsent-v2, CP_K6QAP_K6QAAHABBENA1Es…
  ##+js(set-constant, as_retry, 0)
  ##+js(remove-attr, onerror, script[id][onerror], asap stay)
  ##+js(trusted-replace-argument, HTMLScriptElement.prototype.setA…
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion so I don't know if it's in the scope of regional list or not

```adb
index.hr##.premium-sticky
```

@DandelionSprout Sorry, can you check this?

**Comment by DandelionSprout** [comment]
It's not in the scope, unfortunatey.

**Comment by Marko-98** [comment]
Unfortunately, this annoying bar is still present. Video playback is also broken which I reported here: https://github.com/uBlockOrigin/uAssets/issues/17803#issuecomment-4639768473

**Comment by Marko-98** [comment]
@stephenhawk8054 Can we implement this in any filter? `index.hr##.premium-sticky` does work perfectly.

**Comment by stephenhawk8054** [comment]
We don't address self promotion. You can ask in EasyList repo to see if they address it.

**Comment by Marko-98** [comment]
Will do, thanks! 

May I know what classifies as _nuisance_ beside cookie notices? So I don't have to report these here...

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets#uassets-will-not-address-the-following
