### ISSUE TITLE
[NSFW] shooshtime.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2459]
### URL(s) where the issue occurs

```
https://shooshtime.com/videos/xxx/i-plowed-my-friend-s-hot-daughter_166001/
```

### Describe the issue

Missed advertisement urls / links on pages and in menus that redirect of site in missleading manner since you think you are staying on the site.

### Screenshot(s)

N/a

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default

### Notes

Advertisement URLs i can see there are proborly more some are in menus some are fake videos.

Menu ads.
```
LIVE SEX = https://ads.traffichaus.com/aff/zbo.php?offer=ZS&sub=44653&sub2=43831
discounts = https://www.discountedporn.com/
```

Fake video images that clicking take you elsewhere " Best of the Web"
div class="plugs clearfix"
```
http://donkparty.com/videos/paying-back-a-debt_165439/
http://www.alrincon.com/en/blog/bitten-by-shark-on-her-honeymoon.html
http://www.entensity.net/?content=dailywow&loadurl=http://poststuffx.entensity.net/dailywow/811/9.flv
http://www.phun.org/index.php?navigation=big_ass_boobies
http://donkparty.com/videos/raw-video-found-on-refurbished-iphone_165427/
http://www.alrincon.com/en/blog/the-weekend-you-decide-not-to-go-out.html
http://www.entensity.net/?content=dailywow&loadurl=http://poststuffx.entensity.net/dailywow/0515/27.mp4
```

**Comment by okiehsch** [comment]
I have no time right now to take a closer look, but some points I want to make.

I will not "fix" issues like 

````
Fake video images that clicking take you elsewhere " Best of the Web"
````
Of course this takes you elswhere, that's why it is called "Best of the Web".
I will not disable all links to third-party sites.

**Comment by C0nw0nk** [comment]
That is cool and understandable even though they are technically still ads since they are advertising an external site.
