### ISSUE TITLE
sconde.net: breakage

### ISSUE THREAD

**Issue by skgsergio** [uBlockOrigin/uAssets#24599]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sconde.net/tinypot/`

### Category

breakage

### Description

Charts are not loading.

This is my site that displays some charts using tinybird.co, I have some VPS that sends data regarding SSH attacks and HTTP scans, processes the data in the platform, and then I create some charts using tinybird's endpoints and charts library.

### Other extensions used

none (tested on incognito with just uBlock)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 140205
 cosmetic: 47602
 scriptlet: 21854
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87216-49, now
  easyprivacy: 52856-657, now
  plowe-0: 3548-374, now
  ublock-badware: 9553-19, now
  ublock-filters: 39384-367, now
  ublock-privacy: 1059-5, now
  ublock-quick-fixes: 166-0, now
  ublock-unbreak: 2392-15, now
  urlhaus-1: 15125-0, now
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 446 ms (selfie)
 maxAssetCacheWait: 166 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  cloudflareinsights.com: 1
  tinybird.co: 8
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||api.tinybird.co/v0/pipes/$xhr,domain=sconde.net
```

@ryanbr
