### ISSUE TITLE
scorely.eu: breakage

### ISSUE THREAD

**Issue by bernardcornet** [uBlockOrigin/uAssets#24591]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.scorely.eu/`

### Category

breakage

### Description

The typeform (an embeded form) isn't working

### Other extensions used

Google docs online 
Acid tabs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1885" alt="image" src="https://github.com/user-attachments/assets/5170cd87-f223-47f8-955a-d8a9e3404713">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 139889
 cosmetic: 47590
 scriptlet: 21838
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39367-281, 17m
  ublock-badware: 9505-2, 17m
  ublock-privacy: 1057-2, 17m
  ublock-unbreak: 2391-0, 17m
  ublock-quick-fixes: 169-0, 17m
  easylist: 87174-558, 17m
  easyprivacy: 52855-644, 17m
  urlhaus-1: 14890-0, 17m
  plowe-0: 3547-0, 17m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1375 ms
 maxAssetCacheWait: 19 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  browser-intake-datadoghq.com: 3
  clarity.ms: 1
  geojs.io: 1
  googletagmanager.com: 1
  rudderlabs.com: 3
  typeform.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||get.geojs.io/v1/ip/geo.json$xhr,domain=scorely.eu
```

@ryanbr

**Comment by bernardcornet** [comment]
Thanks for the super quick response!
However, it is still not working. My understanding is the problem was
related ...typeform.com
Let me know if I can clarify anything!

**Comment by stephenhawk8054** [comment]
@bernardcornet Can you screenshot "My filters" pane? 

Please reply directly on github. Don't reply via email, images / screenshots can't be sent via email.

**Comment by bernardcornet** [comment]
Sure!

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/88f0cfea-319f-482a-a786-67bedf6712e1">

**Comment by stephenhawk8054** [comment]
@bernardcornet Add this filter

```adb
||geojs.io^$third-party,badfilter
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by bernardcornet** [comment]
Fixed! Thank you! 🙌
