### ISSUE TITLE
uBlock (1.58.0) Privacy filter Aww Snaps (Code 11) Chrome Canary (128.0.6612.0) Mac (12.7.5 (21H1222)) on some sites

### ISSUE THREAD

**Issue by godzfire** [uBlockOrigin/uAssets#24598]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://support.google.com/
https://www.youtube.com/
https://www.twitch.tv/
```

### Description

As of today, certain uBlock filters – Privacy are causing Chrome Canary Mac on some sites to constantly Aww Snap Error Code 11.

Verified by first isolating uBlock Origin as the cause, then separately testing each filter:
uBlock filters – Privacy breaks all the above.
uBlock filters – Ads seems to be also breaking youtube.com

Not occurring on Chrome Beta or Regular.

### Other extensions used

NA, testing eliminated all other extensions and isolated uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="342" alt="SS 2024-07-22 at 5 09 13 PM" src="https://github.com/user-attachments/assets/cbb35235-7512-42f1-9156-a3194d176709">
<img width="393" alt="SS 2024-07-22 at 5 09 01 PM" src="https://github.com/user-attachments/assets/ef6428ef-11e6-49a9-b7ef-2b032e1bc3c8">
<img width="646" alt="image" src="https://github.com/user-attachments/assets/a0a92755-7744-4700-a745-6a06bd1c1a06">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
Extension: uBlock (1.58.0)
Error: Aww Snap (Error Code 11)
Browser: Chrome Canary (128.0.6612.0)
OS: MacOS Intel (12.7.5 (21H1222))

! Title: uBlock filters
! Expires: 5 days
! Last modified: Mon, 22 Jul 2024 16:56:45 +0000
! Diff-Path: ../patches/2024.7.22.1281.patch#ublock-filters

! Title: uBlock filters – Privacy
! Expires: 7 days
! Last modified: Sun, 21 Jul 2024 17:22:00 +0000
! Diff-Path: ../patches/2024.7.21.1225.patch#ublock-privacy

```
</details>

**Comment by stephenhawk8054** [comment]
Does it occur in stable chrome?

**Comment by godzfire** [comment]
> Does it occur in stable chrome?

As stated not occurring on Chrome Beta or Regular / stable. I utilize/sync uBlock across all three though with the same Google profile.

**Comment by stephenhawk8054** [comment]
Looks like it's similar to this issue: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2869

which is caused by this chromium canary bug: https://issues.chromium.org/issues/352436134 .

This is why chromium canary / dev version is not officially supported: https://github.com/uBlockOrigin/uBlock-issues/issues/3217#issuecomment-2227376037

You'll need to wait the fix from chromium themselves. Please just report if it happens to beta or stable version.
