### ISSUE TITLE
mail.yahoo.com: nuisance

### ISSUE THREAD

**Issue by Vantas99** [uBlockOrigin/uAssets#24607]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mail.yahoo.com/`

### Category

nuisance

### Description

There's a bottom sticky pencil ad box that won't go away and when I put on cosmetic filtering it kinda obscures some emails. 

### Other extensions used

Umatrix, DuckDuckGo Privacy Essentials

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pencil bar](https://github.com/user-attachments/assets/ec853980-0dab-4443-9384-8b40a325d8c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 164542
 cosmetic: 142513
 scriptlet: 46117
 html: 2134
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.13m
  adguard-generic: 83621-6280, 1h.3m
  ublock-annoyances: 5922-73, 1h.4m Δ
  adguard-popup-overlays: 27527-294, 1h.5m
  adguard-mobile-app-banners: 5346-23, 1h.5m
  adguard-other-annoyances: 14808-351, 1h.5m
  adguard-widgets: 2619-15, 1h.5m
  easylist-annoyances: 4643-320, 1h.5m
  easylist-chat: 202-17, 1h.5m
  easylist-newsletters: 7366-546, 1h.5m
  easylist-notifications: 3107-1543, 1h.5m
 default:
  user-filters: 331-20, never
  ublock-filters: 39216-119, 24m
  ublock-badware: 9590-2, 24m
  ublock-privacy: 1054-4, 24m
  ublock-unbreak: 2451-2, 8m
  easylist: 87237-172, 1h.4m Δ
  easyprivacy: 52859-67, 24m Δ
  plowe-0: 3550-990, 1h.5m
  urlhaus-1: 14860-0, 1h.5m
  ublock-quick-fixes: 167-13, 24m
filterset (user): [array of 330 redacted]
trustedset:
 added: [array of 98 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 9 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 53 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 824 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 no-cosmetic-filtering: true
 network:
  yahoo.com: 26
  yahoo.net: 11
  yimg.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
```

You are disabling "Hide placeholders of blocked elements" and using other custom configurations.

Test again in a new Firefox profile with only uBO and its default settings.

**Comment by Vantas99** [comment]
Okay I did that and what do I just port over the settings?

**Comment by Vantas99** [comment]
it's something in my custom filters

**Comment by stephenhawk8054** [comment]
> what do I just port over the settings?

I don't understand. Does the issue occur in the new profile with default settings?

**Comment by Vantas99** [comment]
I fixed it, it was an old custom filter that was the problem.

**Comment by Vantas99** [comment]
So I just went through my custom filters and just deleted anything that was yahoo mail and that fixed it right up.

No more bar and no more email getting covered up when cosmetic filtering is enabled.

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
> - [X] I did not answer truthfully to **ALL** the above checkboxes.
