### ISSUE TITLE
deutsche-bank.de: breakage

### ISSUE THREAD

**Issue by skyynet** [uBlockOrigin/uAssets#24603]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://deutsche-bank.de/pk/filialen/nordwest/ostwestfalen/paderborn.html
https://deutsche-bank.de/pk/filialen/*
```

### Description

On the above given website(s) there is a Google reviews widget. The site asks the user, if they want to show it, since their IP address is transferred to the content provider Yext.
If user accepts, a cookie is set and Google widget supposed to show. With uBlock origin, content is not shown. Deactivating extension for website fixes problem.

### Other extensions used

non relevant. Deactivating uBlock origin fixes problem

### Screenshot(s)

<details>
<summary>uBlock active</summary>

<summary>uBlock inactive</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 142567
 cosmetic: 52620
 scriptlet: 20381
 html: 1878
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39419-119, 5h.7m Δ
  ublock-badware: 9585-2, 5h.7m Δ
  ublock-privacy: 1054-4, 5h.7m Δ
  ublock-unbreak: 2451-2, 5h.7m Δ
  ublock-quick-fixes: 165-2, 5h.7m Δ
  easylist: 87218-171, 5h.7m Δ
  easyprivacy: 52857-67, 5h.7m Δ
  urlhaus-1: 15185-0, 1d.7m
  plowe-0: 3550-991, 12d.12h.37m
  DEU-0: 7515-37, 1d.7m
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 77 ms (selfie)
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  github.com: 17
</details>

**Comment by JobcenterTycoon** [comment]
`@@||assets.adobedtm.com/*-source.min.js$script,domain=deutsche-bank.de`
