### ISSUE TITLE
now14.co.il: breakage

### ISSUE THREAD

**Issue by Halbour** [uBlockOrigin/uAssets#24605]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.now14.co.il/live/`

### Category

breakage

### Description

When trying to view the site with uBlock Origin, the live window will not play. It works fine when disabled.

### Other extensions used

![image](https://github.com/user-attachments/assets/e635151f-f637-418b-8657-58e2c55e417b)
![image](https://github.com/user-attachments/assets/d6a95aff-db19-4fa1-8c17-fa6a91a8e6ca)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 319258
 cosmetic: 96089
 scriptlet: 29431
 html: 2143
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 99711-3, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2658-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt: 68185-54, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 338-2, now
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/antimalware.txt: 42023-2776, now
  fanboy-cookiemonster: 51400-194, now
  ublock-cookies-easylist: 1283-5, now
  ublock-annoyances: 5922-63, 55m Δ
  ISR-0: 1893-13, now
 default:
  user-filters: 45-0, never
  ublock-filters: 39216-293, 55m Δ
  ublock-badware: 9590-1406, 55m Δ
  ublock-privacy: 1054-82, 55m Δ
  ublock-unbreak: 2451-3, 55m Δ
  ublock-quick-fixes: 167-2, 55m Δ
  easylist: 87237-23043, 55m Δ
  easyprivacy: 52859-7566, 55m Δ
  urlhaus-1: 15260-6, now
  plowe-0: 3550-2249, now
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 365 ms (selfie)
 maxAssetCacheWait: 115 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  now14.co.il: 1
  clarity.ms: 1
  doubleclick.net: 3
  dxmdp.com: 1
  googletagmanager.com: 2
  sentry-cdn.com: 2
  springserve.com: 1
  taboola.com: 1
  univtec.com: 1
 extended:
  ##.cookies-container
  ##.cookies-text
  ##.googleAd
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by CoolestGuy94** [comment]
Hello, please try making a new profile with the default uBlockOrigin settings and see if this issue re-occurs.

**Comment by mapx-** [comment]
disable all other extensions, reset uBO to defaults, test again
