### ISSUE TITLE
[nsfw] mitaku.net: popups

### ISSUE THREAD

**Issue by ssmiull** [uBlockOrigin/uAssets#24618]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mitaku.net/

### Category

popups

### Description

Popup tabs appear despite having the extension active

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox Mobile: 128
filterset (summary):
 network: 141700
 cosmetic: 55679
 scriptlet: 20490
 html: 1879
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39715-179, 7m Δ
  ublock-badware: 9709-2, 7m Δ
  ublock-privacy: 1055-4, 7m Δ
  ublock-unbreak: 2453-4, 7m Δ
  ublock-quick-fixes: 172-3, 7m Δ
  adguard-mobile: 9619-11, 1m
  easylist: 87225-239, 7m Δ
  easyprivacy: 52872-74, 7m Δ
  urlhaus-1: 15110-0, 1m
  plowe-0: 3550-1064, 1m
filterset (user): [empty]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 366 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  ajscdn.com: 2
  blurbreimbursetrombone.com: 1
  endowmentoverhangutmost.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
```
</details>

**Comment by jimmysofat6864** [comment]
Website now has Adblock detection and pop up advertising. 

Browser: Safari 
iOS Version: iOS 26.2.1

URL: `https://mitaku.net/category/online-video/`


Screenshots: 

https://ibb.co/zhfkLsjR
https://ibb.co/qYccBwwd
