### ISSUE TITLE
wiflix-catalogue.pro: breakage

### ISSUE THREAD

**Issue by fiketek** [uBlockOrigin/uAssets#24614]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wiflix-catalogue.pro/`

### Category

breakage

### Description

hello, several options on my site disappear when ublock origin is activated, like favorites, some players too, can you fix this?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 157982
 cosmetic: 54116
 scriptlet: 20535
 html: 1878
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39462-119, now
  ublock-badware: 9711-1, 46m Δ
  ublock-privacy: 1054-4, 46m Δ
  ublock-unbreak: 2450-2, 46m Δ
  ublock-quick-fixes: 171-2, 46m Δ
  easylist: 87269-171, 46m Δ
  easyprivacy: 52872-66, 46m Δ
  urlhaus-1: 15345-0, now
  plowe-0: 3550-990, now
  FRA-0: 24643-426, 46m
filterset (user): [empty]
trustedset:
 added: [array of 59 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 299253 ms (selfie)
 maxAssetCacheWait: 938 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 no-cosmetic-filtering: true
 network:
  ads2550.bid: 2
  gannetsmechant.com: 2
  googletagmanager.com: 1
  ungatedsynch.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
wiflix-catalogue.pro#@#a[href*=".php"]
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by mapx-** [comment]
@fiketek 

report here too for the regional list "Liste FR"
https://github.com/easylist/listefr/issues

**Comment by fiketek** [comment]
ok thanks :)
