### ISSUE TITLE
hackerrank.com: detection

### ISSUE THREAD

**Issue by nascentt** [uBlockOrigin/uAssets#24611]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hackerrank.com/codepair/nsdlzcbucpdunurearttde/check?b=eyJpbnRlcnZpZXdfayMTQ5MjIsInJvbGUiOiJpbnRlcnZpZXdlciIsInNob3J0X3VybCI6Imh0zOi8vaHIuZ3MvYzMxOGYyMSIsImNhbmRpZGF1cmwiOiJodHRwczovL2hyLmdzLzNkZTE1MTAifQ`

### Category

detection

### Description

site works without issues if ublock origin is disabled. when enabled a dialog requiring as blockers are disabled as well as cors blocks
disabling ublock origin for the site is enough for the site to fully work

### Other extensions used

sentinelone

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![hackerrank](https://github.com/user-attachments/assets/0d69484c-0a27-4ce1-a40b-798d09054b90)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 138455
 cosmetic: 47318
 scriptlet: 20177
 html: 1877
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39233-118, now
  ublock-badware: 9666-1, now
  ublock-privacy: 1054-4, now
  ublock-unbreak: 2451-2, now
  easylist: 87252-171, now
  easyprivacy: 50604-32, now
  plowe-0: 3550-527, now
  ublock-quick-fixes: 166-2, never
  urlhaus-1: 14860-0, never
filterset (user): [empty]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2899 ms
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  fullstory.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  licdn.com: 1
  newrelic.com: 3
  pendo.io: 2
```
</details>

**Comment by AdblockReporters** [comment]
Their adblock detection work by first trying to call `https://googlesyndication.com/` and se if it is blocked
It also tries to create elements with these: `textads banner-ads banner_ads ad-unit ad-zone ad-space adsbox`

<img width="616" alt="Screenshot 2024-07-24 at 17 39 59" src="https://github.com/user-attachments/assets/e6d28fa7-b263-4eae-8801-f89c5060bd20">
<img width="823" alt="Screenshot 2024-07-24 at 17 38 40" src="https://github.com/user-attachments/assets/7cedb8f9-d3f3-4a03-b7bb-c4a67efd3e6a">
<img width="893" alt="Screenshot 2024-07-24 at 17 39 28" src="https://github.com/user-attachments/assets/33bd7761-9112-4b91-8532-e5671e8f7ccd">

The src: https://hrcdn.net/codepair-frontend/assets/check_view-8bd6c62f.js

**Comment by stephenhawk8054** [comment]
@AdblockReporters Can you test if this filter works?

```adb
*$xhr,redirect-rule=nooptext:-1,to=~fundingchoicesmessages.google.com|~sentry.io,domain=hackerrank.com
```

**Comment by AdblockReporters** [comment]
![Uploading Screenshot 2024-07-24 at 18.52.38.png…]()
It seems so 👀

**Comment by stephenhawk8054** [comment]
How to reproduce the issue? I see 2 options: join as candidate and join as interviewer

**Comment by AdblockReporters** [comment]
I just join as a candidate, and put a dummy name there
@stephenhawk8054

**Comment by stephenhawk8054** [comment]
Hmm... I can no longer access the link above, so I go to `https://www.hackerrank.com/codepair/` instead, then click on `Launch Demo`, but I can't reproduce the issue.

**Comment by mapx-** [comment]
@nascentt 

- provide a new link for testing
- did you test the filter above ?

`*$xhr,redirect-rule=nooptext:-1,to=~fundingchoicesmessages.google.com|~sentry.io,domain=hackerrank.com`

**Comment by AdblockReporters** [comment]
I did test the filter above and it worked. But we can wait for the OP if you would like

**Comment by nascentt** [comment]
Many thanks. The new filters seem to work for me and others I've asked to test
