### ISSUE TITLE
plyty.kyiv.ua: breakage

### ISSUE THREAD

**Issue by bookerok** [uBlockOrigin/uAssets#24612]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://plyty.kyiv.ua/`

### Category

breakage

### Description

site is brokken when use ublock

### Other extensions used

site is brokken when use ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 158630
 cosmetic: 67945
 scriptlet: 23314
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39139-389, now
  ublock-badware: 9664-1, now
  ublock-privacy: 1059-2, now
  ublock-unbreak: 2392-0, now
  ublock-quick-fixes: 168-0, now
  easylist: 87239-493, now
  easyprivacy: 52872-645, now
  urlhaus-1: 14860-0, 17m
  plowe-0: 3550-0, now
  RUS-0: 40739-103, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1892 ms (selfie)
 maxAssetCacheWait: 878 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  tildacdn.one: 23
```
</details>

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry, can you check this?
