### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by YagoMCampos** [uBlockOrigin/uAssets#24623]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=KsCsn--S9k4`

### Category

ads

### Description

having ads even with uorigin on

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 141827
 cosmetic: 51309
 scriptlet: 20902
 html: 1878
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39274-118, 26m Δ
  ublock-badware: 9840-1, 26m Δ
  ublock-privacy: 1054-4, 26m Δ
  ublock-unbreak: 2450-2, 26m Δ
  ublock-quick-fixes: 171-2, 26m Δ
  easylist: 87327-170, 26m Δ
  easyprivacy: 52999-66, 26m Δ
  urlhaus-1: 15005-0, now
  plowe-0: 3551-990, now
  spa-1: 5837-85, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 388 ms (selfie)
 maxAssetCacheWait: 120 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 39
 network:
  youtube.com: 16
  doubleclick.net: 3
  google.com: 7
  google.com.br: 1
  googlesyndication.com: 2
  googlevideo.com: 10
 extended:
  ##.ytp-featured-product
  ###masthead-ad
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> #content > ytd-ad-slot-renderer)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
```
</details>

**Comment by VaelophisNyx** [comment]
Honestly the way UBO handles this prevents effective fixes for specific sites because they get funneled to a lengthy thread that puts people off from bothering to report the bug(s) :/

**Comment by stephenhawk8054** [comment]
Then what should we do? Shove every report of 1 site to the volunteers to close duplicated issue one-by-one? Close and open the big thread after 10 comments every day? The big thread only tells you to follow the 1st post. It doesn't tell you to read all of the posts in that thread. Github also collapses the thread to prevent it being too long.
