### ISSUE TITLE
dafont.com: breakage

### ISSUE THREAD

**Issue by damsmcfly** [uBlockOrigin/uAssets#24629]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dafont.com/forum/read/556120/logo-de-tps`

### Category

breakage

### Description

Images attached to forum posts, such as `https://www.dafont.com/forum/attach/orig/1/1/1176090.png` are hidden by uBlock

### Other extensions used

Privacy Badger (disabled) and many more, but most are disabled for this website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 144892
 cosmetic: 121801
 scriptlet: 24969
 html: 1879
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 100435-17664, now
 default:
  user-filters: 71-1, never
  ublock-filters: 39362-137, 42m Δ
  ublock-badware: 9970-1, 42m Δ
  ublock-privacy: 1055-5, 42m Δ
  ublock-unbreak: 2456-6, 42m Δ
  ublock-quick-fixes: 177-2, 42m Δ
  easylist: 87403-191, 42m Δ
  easyprivacy: 52967-199, 42m Δ
  urlhaus-1: 15445-0, now
  plowe-0: 3547-989, now
filterset (user): [array of 71 redacted]
trustedset:
 added: [array of 48 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 516 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  consentframework.com: 3
  googlesyndication.com: 1
 extended:
  ###sky
  ##.tooltip_google
```
</details>

**Comment by mapx-** [comment]
add

`dafont.com#@#.tooltip_google`

@ryanbr
