### ISSUE TITLE
laviola.it: ads

### ISSUE THREAD

**Issue by cloduehr** [uBlockOrigin/uAssets#24622]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.laviola.it/`

### Category

ads

### Description

In backround of the page appears ads

### Other extensions used

i am using only ublockorigin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-07-25 at 15-58-04 Home](https://github.com/user-attachments/assets/36be482e-7cea-4e39-a983-d16c699cb4a9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 142227
 cosmetic: 54285
 scriptlet: 20425
 html: 1878
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 39274-118, now
  ublock-badware: 9840-1, now
  ublock-privacy: 1055-4, now
  ublock-unbreak: 2450-2, now
  ublock-quick-fixes: 176-2, now
  easylist: 87355-170, now
  easyprivacy: 52957-66, now
  urlhaus-1: 15005-0, now
  plowe-0: 3551-990, now
  ITA-0: 8691-37, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 40
 network:
  laviola.it: 34
  googlesyndication.com: 1
  googletagmanager.com: 4
  quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`laviola.it##.adv-link`

@khrin
