### ISSUE TITLE
TVTropes content cosmetically filtered away.

### ISSUE THREAD

**Issue by ShimmerFairy** [uBlockOrigin/uAssets#2462]
### URL(s) where the issue occurs

`http://tvtropes.org/pmwiki/pmwiki.php/YMMV/DoctorWho`
`http://tvtropes.org/pmwiki/posts.php?discussion=15248664670A37258600&page=1`

### Describe the issue

The content of any tvtropes page is invisible, and you need to disable cosmetic filtering to make it appear.

### Versions

- Browser/version: Firefox 60.0
- uBlock Origin version: 1.16.8

### Notes

This may be related to the fixes made in #2455 , but in any case I have no clue how to disable any of the possible culprit filters.

**Comment by okiehsch** [comment]
My bad, the filter 
`tvtropes.org##.ad-content-top`
works fine with Chrome, but causes your issue with Firefox, I will remove it.
