### ISSUE TITLE
filmweb.pl - detection

### ISSUE THREAD

**Issue by bazyliszku** [uBlockOrigin/uAssets#24627]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.filmweb.pl/film/Skarby-2023-10041176
https://www.filmweb.pl/film/Substancja-2024-10051631
https://www.filmweb.pl/film/Love+Lies+Bleeding-2024-10011975
```

### Description

When uBlock is enabled, bottom side of the webpage is covered by "Turn off adblock" message.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/507a291d-0feb-4b94-9fe4-b6af2f888d0e">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 140870
 cosmetic: 47334
 scriptlet: 20421
 html: 1878
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39274-118, 22h.38m Δ
  ublock-badware: 9840-1, 22h.38m Δ
  ublock-privacy: 1054-4, 22h.38m Δ
  ublock-unbreak: 2450-2, 22h.38m Δ
  ublock-quick-fixes: 171-2, 22h.38m Δ
  easylist: 87327-170, 22h.38m Δ
  easyprivacy: 52999-66, 22h.38m Δ
  urlhaus-1: 15345-0, 1d.18h.17m
  plowe-0: 3547-989, 3d.18h.31m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1020 ms
 maxAssetCacheWait: 15 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
enable the regional lists Oficjalne Polskie Filtry
