### ISSUE TITLE
kinepolis.be: breakage

### ISSUE THREAD

**Issue by ThowZzy** [uBlockOrigin/uAssets#24620]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://kinepolis.be/fr/direct-vista-redirect/275263/0/METRO/0
https://kinepolis.be/fr/direct-vista-redirect/275317/0/METRO/0
https://kinepolis.lu/en/direct-vista-redirect/73843/0/UBVAL/0
```

### Description

It is the most popular website in belgium to watch movies in a theater.

To reproduce: 

1. go to https://kinepolis.be/
2. Select any language
3. Select any movie
4. Select any complex, any date
5. Click on any time where the movie is playing, to get redirected on the page to pay
6. Get a "Page not found"

Without Ublock, clicking on the time correctly redirects to the reservation site.

Note : Kinepolis have several domain names for the different countries it covers.

### Other extensions used

![image](https://github.com/user-attachments/assets/a09ce049-3b32-4f1b-8da2-415160f1033e)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 158008
 cosmetic: 53929
 scriptlet: 20575
 html: 1878
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 39274-118, 2h.36m Δ
  ublock-badware: 9840-1, 2h.36m Δ
  ublock-privacy: 1054-4, 2h.36m Δ
  ublock-unbreak: 2450-2, 2h.36m Δ
  ublock-quick-fixes: 171-2, 2h.36m Δ
  easylist: 87327-170, 2h.36m Δ
  easyprivacy: 52999-66, 2h.36m Δ
  urlhaus-1: 15110-0, 6h.13m
  plowe-0: 3544-989, 10d.6h.38m
  FRA-0: 24629-427, 3d.5h.28m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 311 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtm.js$script,domain=kinepolis.be
@@||googletagmanager.com/gtag/js$script,domain=kinepolis.be
```

@ryanbr

**Comment by ThowZzy** [comment]
> add
> 
> ```
> @@||googletagmanager.com/gtm.js$script,domain=kinepolis.be
> @@||googletagmanager.com/gtag/js$script,domain=kinepolis.be
> ```
> 
> @ryanbr
Thank you!

Any easy way to include the other domains as well ? I don't use them but some people do.

kinepolis.be
kinepolis.es
kinepolis.fr
kinepolis.ch
kinepolis.nl
kinepolis.lu

**Comment by mapx-** [comment]
```
@@||googletagmanager.com/gtm.js$script,domain=kinepolis.*
@@||googletagmanager.com/gtag/js$script,domain=kinepolis.*
```
