### ISSUE TITLE
Incorrectly blocked all using uni-app developed pages.

### ISSUE THREAD

**Issue by copyliu** [uBlockOrigin/uAssets#24631]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://m.qinxuan.honor.com/
```

### Description

in https://github.com/uBlockOrigin/uAssets/blame/5de82a3d61f2de3a888502d4464fccd0ed247b3c/filters/badware.txt#L4553 , it will Incorrectly blocked all using uni-app developed pages. uni-app is a popular web development framework for mobile phones. 
it generated `body:not([id]) > uni-app > uni-page[data-page] > uni-page-wrapper > uni-page-body`  as a signature.

more uni-app cases https://en.uniapp.dcloud.io/case.html
about uni-app framework: https://github.com/dcloudio/uni-app

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2024-07-26 at 22 05 51](https://github.com/user-attachments/assets/677ee969-8e6c-4f13-8213-687cecf2a3dc)
![Screen Shot 2024-07-26 at 22 06 19](https://github.com/user-attachments/assets/187da481-774c-4ffd-a3a2-a1a1b8ff4450)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 130
filterset (summary):
 network: 156800
 cosmetic: 103592
 scriptlet: 25972
 html: 1879
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51400-187, now
  ublock-cookies-easylist: 1283-5, now
  CHN-0: 25306-195, now
 default:
  user-filters: 1-0, never
  ublock-filters: 39362-118, now
  ublock-badware: 9969-1, now
  ublock-privacy: 1055-4, now
  ublock-unbreak: 2456-2, now
  ublock-quick-fixes: 180-2, now
  easylist: 87405-171, now
  easyprivacy: 52967-66, now
  urlhaus-1: 15205-0, now
  plowe-0: 3547-989, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 285 ms (selfie)
 maxAssetCacheWait: 105 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  fraudmetrix.cn: 1
  tongdun.net: 1
 extended:
  ##html[lang][style] > body:not([id]) > uni-app.uni-app--maxwidth…
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed. Please click [this link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=240728) to force update the quick fix list.
