### ISSUE TITLE
cinelatino.net: detection

### ISSUE THREAD

**Issue by ragg102** [uBlockOrigin/uAssets#24632]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cinelatino.net/`

### Category

detection

### Description

the website detect the adblock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 143239
 cosmetic: 54221
 scriptlet: 20920
 html: 1879
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39362-118, 5m Δ
  ublock-badware: 9970-1, 5m Δ
  ublock-privacy: 1055-4, 5m Δ
  ublock-unbreak: 2456-2, 5m Δ
  ublock-quick-fixes: 177-2, 5m Δ
  easylist: 87403-171, 5m Δ
  easyprivacy: 52967-66, 5m Δ
  urlhaus-1: 15205-0, now
  plowe-0: 3547-989, now
  spa-0: 4065-26, now
  spa-1: 5840-254, 5m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 151 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  dj2550.com: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  heimalesssinpad.com: 2
  moustachepoke.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
cinelatino.net##+js(set, checkAdBlock, noopFunc)
```

@Yuki2718 For AdGuard Spanish?

**Comment by ragg102** [comment]
Yea

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
