### ISSUE TITLE
umod.org: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#24636]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://umod.org/plugins`

### Category

ads

### Description

There's an ad for Gameserver Kigns with their (uMod) coupon code for 10% off forever.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/6abd831d-0b20-48bc-b7aa-cdbba80adf15)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 231758
 cosmetic: 245445
 scriptlet: 54805
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83745-6479, 4m
  adguard-spyware-url: 1593-122, 4m
  adguard-spyware: 80533-31938, 4m
  block-lan: 69-0, 4m
  curben-phishing: 580-0, 4m
  adguard-cookies: 30567-89, 4m
  ublock-cookies-adguard: 1283-0, 4m
  fanboy-cookiemonster: 51419-3999, 4m
  ublock-cookies-easylist: 1283-1283, 4m
  adguard-social: 23190-799, 4m
  fanboy-social: 16502-8, 4m
  adguard-popup-overlays: 27557-1746, 4m
  [9 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 39281-114, 4m
  ublock-badware: 9941-4, 4m
  ublock-privacy: 1060-2, 4m
  ublock-unbreak: 2397-3, 4m
  ublock-quick-fixes: 187-2, 4m
  easylist: 87434-817, 4m
  easyprivacy: 52970-1013, 4m
  urlhaus-1: 15205-0, 4m
  plowe-0: 3548-0, 5m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 78 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 555 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  umod.org: 1
  placeholder.com: 2
 extended:
  ###cookiebanner
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
umod.org##ins[data-revive-id]
```

@ryanbr
