### ISSUE TITLE
upera.co :: counter issue

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#2464]
### URL(s) where the issue occurs

`https://public.upera.co/aq83s34y`

### Describe the issue

There is a decreasing counter on top-right side of the page, after choosing "Regular Download". Counter starts with 25 and its code is in the source of the page. A copy of related code is pasted below.
I tried with `upera.co##script:inject(nano-setInterval-booster.js)` and it accelerates the counter, but after finishing, counter gets reloaded and goes into a never-ending loop.

Following scriptlets, didn't work too:
```
upera.co##script:inject(set-constant.js, function, counter, 0)
upera.co##script:inject(setInterval-defuser.js, function, counter, 25)
```

### Screenshot(s)

`https://cdn.pbrd.co/images/HoiUojH.png`
`https://cdn.pbrd.co/images/HoiWUvJ.png`

### Versions

- Browser/version: Chrome 66.0.3359.181
- uBlock Origin version: 1.16.8

### Settings

Using following filter list:
`http://mynext.pro/BLF.txt`

### Notes

```
(function(){
  var counter = 25;

  setInterval(function() {
    counter--;
    if (counter >= 0) {
      span = document.getElementById("count");
      span.innerHTML = counter;
    }
    // Display 'counter' wherever you want to display it.
    if (counter === 0) {
	    $.ajax({
            url: 'https://public.upera.co/aq83s34y?interadv=nj675b14f162d6ba9&showrecaptcha=1&ns=&referrer=',
			dataType: "html",
			success: function(data) {
					if(data.length<=5000){
						$('#dlbox').removeClass( "m-t-sm" ).addClass( "m-t-xs" ).html(data);
					}else
						location.reload();
			}

	    });
        clearInterval(counter);
    }

  }, 1000);

})();
```

**Comment by okiehsch** [comment]
The site uses server-side validation for the timer, it is not bypassable.

**Comment by okiehsch** [comment]
Just fyi, file hosting services who use timers almost always validate on server side.
