### ISSUE TITLE
ledenicheur.fr: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#24646]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ledenicheur.fr/search?search=CERM600B`

### Category

ads

### Description

There are several empty inserts on the page

### Other extensions used

None that interfere with uBkock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 189073
 cosmetic: 158778
 scriptlet: 30475
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1103-0, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, now
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51427-12108, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-4, now
  adguard-cookies: 30572-1667, now
  ublock-cookies-adguard: 1283-1283, now
  fanboy-cookiemonster: 51427-51427, now
  ublock-cookies-easylist: 1283-0, now
  RUS-0: 40766-270, now
 default:
  user-filters: 1-0, never
  ublock-filters: 39303-114, now
  ublock-badware: 9979-1, now
  ublock-privacy: 1043-2, now
  ublock-unbreak: 2398-1, now
  ublock-quick-fixes: 160-2, now
  easylist: 87461-629, now
  easyprivacy: 52981-805, now
  urlhaus-1: 22010-0, now
  plowe-0: 3548-0, now
  FRA-0: 24643-377, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2300 ms (selfie)
 maxAssetCacheWait: 121 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  adnxs.com: 1
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
ledenicheur.fr##[class^="AdPlacement"]
ledenicheur.fr##.outsider-ads
ledenicheur.fr##.pjra-relative:has-text(Publicit)
```

report the issue at Liste FR repository:
https://github.com/easylist/listefr/issues

@smed79
