### ISSUE TITLE
outlook.live.com: nuisance

### ISSUE THREAD

**Issue by aviationhacker** [uBlockOrigin/uAssets#24649]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://outlook.live.com/mail/0/inbox/id/AQQkADAwATZiZmYAZC05NWFmLTBmMTQtMDACLTAwCgAQANM8qpypBBRCpp0TVO9UD3c%3D`

### Category

nuisance

### Description

Has ad-blocker detection, where even though it won't show an ad, it will occupy the space on the web browser to try cause an inconvenience and make you pay for microsoft services :L

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Outlook Web Snip](https://github.com/user-attachments/assets/e7f387d8-e91a-4532-95bf-ebc18c28023f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 148084
 cosmetic: 47569
 scriptlet: 21917
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87468-49, now
  easyprivacy: 52981-653, now
  plowe-0: 3548-373, now
  ublock-badware: 9979-18, 4m
  ublock-filters: 39304-365, 4m
  ublock-privacy: 1043-4, now
  ublock-quick-fixes: 162-0, 4m Δ
  ublock-unbreak: 2399-15, 4m
  urlhaus-1: 22315-0, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 645 ms (selfie)
 maxAssetCacheWait: 427 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  live.com: 3
  3lift.com: 2
  adnxs.com: 3
  crunchyroll.com: 1
  ebayadservices.com: 1
  office.net: 1
  pbtech.co.nz: 1
  repco.co.nz: 2
  scarabresearch.com: 4
  taboola.com: 2
 extended:
  ##.VdboX[tabindex="0"]:has(img[src="https://res.cdn.office.net/a…
  ##.Ogt7j
  ##div[data-app-section="MessageList"] div[class][id*="-"]:has(> …
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/23933
