### ISSUE TITLE
analyticsvidhya.com: nuisance

### ISSUE THREAD

**Issue by gtxPrime** [uBlockOrigin/uAssets#24643]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.analyticsvidhya.com/blog/2023/03/python-certification-guide-best-python-certifications-for-all-levels-free-paid/`

### Category

nuisance

### Description

Login popup showing

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/75d5f8c4-bf93-4c1c-b509-e0335b5c8251)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 147729
 cosmetic: 47561
 scriptlet: 21912
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39281-278, 55m Δ
  ublock-badware: 9941-1, 55m Δ
  ublock-privacy: 1060-2, 55m Δ
  ublock-unbreak: 2398-0, 55m Δ
  ublock-quick-fixes: 187-0, 55m Δ
  easylist: 87441-557, 55m Δ
  easyprivacy: 52970-644, 55m Δ
  urlhaus-1: 22010-0, now
  plowe-0: 3548-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 24398 ms (selfie)
 maxAssetCacheWait: 886 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 no-cosmetic-filtering: true
 no-popups: true
 no-scripting: true
 network:
  cloudflareinsights.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by mapx-** [comment]
>  no-cosmetic-filtering: true
>  no-popups: true
>  no-scripting: true
> 

- reset uBO to defaults

add
`analyticsvidhya.com##+js(nostif, modal)`
 
@ryanbr
