### ISSUE TITLE
 user-uploads.perchance.org: privacy

### ISSUE THREAD

**Issue by crunchy-1dimensional** [uBlockOrigin/uAssets#24648]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://user-uploads.perchance.org/file/06b63cbc807acaf79bc25f114bb0dda1.webp`

### Category

privacy

### Description

I deactivated the adblocker ublock origin **HOWEVER** this site doesn't stop spamming notification to turn off adblocker **EVEN** when it's turned off, and all cookie-deleters are turned off too.

My suspicion: a script rolls every minute or so to make sure ads are displayed, thus it is a potential PRIVACY issue, as _this proves the site is actively checking whether ads are playing_, instead of checking whether adblocker was deactivated. 

### Other extensions used

cookie auto delete (turned off)
decentraleyes
duckduckgo privacy essentials
popup off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7a43c56d-a7cf-4156-adac-09a63f3f4e5e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 147745
 cosmetic: 47466
 scriptlet: 20448
 html: 1881
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39393-118, 10m Δ
  ublock-badware: 9981-1, 10m Δ
  ublock-privacy: 1038-4, 10m Δ
  ublock-unbreak: 2458-1, 10m Δ
  ublock-quick-fixes: 162-2, 10m Δ
  easylist: 87468-543, 10m Δ
  easyprivacy: 52981-678, 10m Δ
  urlhaus-1: 22010-0, 10m
  plowe-0: 3548-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 257 ms (selfie)
 maxAssetCacheWait: 77 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/20666
