### ISSUE TITLE
dicasgostosas.com: detection

### ISSUE THREAD

**Issue by LightnessSenpai** [uBlockOrigin/uAssets#24657]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hinatasoul.com/videos/224675`
`https://dicasgostosas.com/cacarola-de-atum/`

### Category

detection

### Description

I'm not sure if this would count as a duplicate since there was a issue posted by the user named Hakkyon (I had to search manually to find his issue) so I apologize in advance if that happens.
When I go to hinatasoul.com to watch anime it opens the video player in this "dicasgostosas.com" website then it detects the uBlock Origin extension. This issue was solved last week I guess but it's happening again.

Sorry about the two URLs, I just want to help.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![report ublock hinatasoul](https://github.com/user-attachments/assets/147abbbc-62a8-45f7-b15c-fecbc23d2f76)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 149108
 cosmetic: 51448
 scriptlet: 20918
 html: 1882
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39352-118, now
  ublock-badware: 9837-1, now
  ublock-privacy: 1037-4, now
  ublock-unbreak: 2465-2, now
  ublock-quick-fixes: 172-0, 1h.16m Δ
  easylist: 87502-170, now
  easyprivacy: 52988-62, now
  urlhaus-1: 22190-0, 1h.16m
  plowe-0: 3548-989, now
  spa-1: 5850-85, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2100 ms (selfie)
 maxAssetCacheWait: 171 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  adligature.com: 1
  demand.supply: 1
  googletagmanager.com: 1
  waust.at: 1
 extended:
  ##.ad-1
  ##.demand-supply
  ##.ads-2
  ##+js(no-setTimeout-if, hasAdblock)
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-on-property-write, detectedAdblock)
  ##+js(abort-on-property-read, adBlockFunction)
  ##+js(abort-current-script, document.getElementsByTagName, adsby…
  ##+js(set-constant, detectedAdblock, noopFunc)
  ##+js(prevent-fetch, /pagead2\.googlesyndication\.com|outbrain\.…
```
</details>

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uAssets/issues/24575

**Comment by LightnessSenpai** [comment]
> #24575

Uh... Ok. And sorry.
