### ISSUE TITLE
dtf.ru: breakage

### ISSUE THREAD

**Issue by DimetryBadcoder** [uBlockOrigin/uAssets#24659]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dtf.ru/`

### Category

breakage

### Description

Some videos such as gif animations and animated avatars should be auto played and should not contain GUI. 
If you disable Ublock Origins or Russian filter, everything is alright

### Other extensions used

I disabled all other extensions for the testing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок экрана 2024-07-29 035412](https://github.com/user-attachments/assets/85ea16bd-d6df-4ead-8b8f-183e9704b411)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.1rc11
Chromium: 124
filterset (summary):
 network: 166754
 cosmetic: 68150
 scriptlet: 23413
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39354-278, 1h.46m Δ
  ublock-badware: 9835-1, 1h.46m Δ
  ublock-privacy: 1042-2, 1h.46m Δ
  ublock-unbreak: 2406-0, 1h.46m Δ
  ublock-quick-fixes: 172-0, 1h.46m Δ
  easylist: 87502-577, 1h.46m Δ
  easyprivacy: 52988-640, 1h.46m Δ
  urlhaus-1: 22500-0, now
  plowe-0: 3548-0, now
  RUS-0: 40755-127, 46m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1600 ms
 maxAssetCacheWait: 95 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  adlooxtracking.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  osnova.io: 1
  rambler.ru: 1
  wi-fi.ru: 1
  yandex.ru: 1
 extended:
  ##.ALMGcspq
  ##.distribution
  ##.rotator
  ##.supbar--top
  ##video:remove-attr(autoplay)
```
</details>

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
This issue is known. It is better to discuss it here: https://forums.lanik.us/viewtopic.php?t=28740-dtf-ru-vc-ru
