### ISSUE TITLE
welt.de: breakage

### ISSUE THREAD

**Issue by jglathe** [uBlockOrigin/uAssets#24650]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.welt.de/`

### Category

breakage

### Description

With uBlock Origin enabled, and strangely not on Windows (other Firefox?), the comments section is not displayed. You only get it when disabling and reloading the site.

### Other extensions used

I don't care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/83289d72-16cf-4933-9ac9-14115523f53f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 130
filterset (summary):
 network: 148023
 cosmetic: 47478
 scriptlet: 20462
 html: 1882
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39414-118, 1h.12m Δ
  ublock-badware: 9948-1, 1h.12m Δ
  ublock-privacy: 1038-4, 1h.12m Δ
  ublock-unbreak: 2463-1, 1h.12m Δ
  ublock-quick-fixes: 162-2, 1h.12m Δ
  easylist: 87468-543, 1h.12m Δ
  easyprivacy: 52988-678, 1h.12m Δ
  urlhaus-1: 22315-0, 1h.12m
  plowe-0: 3548-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 849 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  welt.de: 5
  asadcdn.com: 1
  axelspringer.de: 1
  bing.com: 1
  chartbeat.com: 2
  cxense.com: 2
  doubleclick.net: 1
  facebook.net: 1
  googleadservices.com: 1
  googletagmanager.com: 1
  kameleoon.eu: 2
  kameleoon.io: 3
  nmrodam.com: 1
  outbrain.com: 2
  taboola.com: 2
 extended:
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(json-prune, vastUrl)
  ##+js(remove-attr, onmousedown, .ob-dynamic-rec-link, stay)
```
</details>

**Comment by jglathe** [comment]
Screenshot when uBlock Origin disabled and reloaded:

![image](https://github.com/user-attachments/assets/01168b1f-34a6-4f1d-8c54-6a73f0783b49)

**Comment by stephenhawk8054** [comment]
Enable `EasyList Germany` list and test again.

**Comment by jglathe** [comment]
That worked nicely, thank you!

**Comment by digitalfrost84** [comment]
I have the same issue. Easylist germany is enabled, it does not help.

**Comment by mapx-** [comment]
reset uBO to defaults (filter lists + settings), disable any other extension, test again

**Comment by stephenhawk8054** [comment]
The comment appears normally for me in `https://www.welt.de/politik/ausland/article253527980/Frankreichs-EU-Kommissar-tritt-nach-Streit-mit-von-der-Leyen-zurueck.html`.

@JobcenterTycoon Can you reproduce?

**Comment by Symbai** [comment]
This is how it looks for me when I open the link with ublock enabled:

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/8db88b07-0ebb-4829-be3d-48f973a4699f)

</details>

FYI: If I disable ublock, reload. Comments section appears. If I enable ublock and reload, for some reason comments section is still there. So when trying/testing please always open the link in a new tab with ublock enabled.

**Comment by stephenhawk8054** [comment]
Ah ok, I can reproduce now. Caused by `welt.de##[id^="outbrain_widget_"]:has-text(/anzeige/i)`

**Comment by JobcenterTycoon** [comment]
Can’t reproduce at all. Removing `welt.de##[id^="outbrain_widget_"]:has-text(/anzeige/i)` bring ads back.

**Comment by stephenhawk8054** [comment]
It's pretty random. I forgot to screenshot with uBO logger overlay on the comments.

**Comment by stephenhawk8054** [comment]
It looks like this to me:

![image](https://github.com/user-attachments/assets/9fd6c4e4-e7b0-4645-b7d8-ad29cd89cf4e)

**Comment by Symbai** [comment]
FYI: At the moment the comments are working again. I dont know if there was a filter update or not. If not, maybe it depends on what ads they are showing or they did some changes on their end 🤷‍♂️

**Comment by JobcenterTycoon** [comment]
Still can’t reproduce but what about more specific filter like `welt.de##[id^="outbrain_widget_"].OUTBRAIN[data-src]:has(> .ob-widget > .ob-widget-items-container > .ob-dynamic-rec-container > a[data-adv-id][rel*="sponsored"])` ?

It should hide the ads marked with "ANZEIGE"

<details>

<img width="823" alt="ggg" src="https://github.com/user-attachments/assets/8376bf17-925b-4402-8f5e-0d5530076f22">

</details>

**Comment by stephenhawk8054** [comment]
I think that is better
