### ISSUE TITLE
apfeltalk.de: breakage

### ISSUE THREAD

**Issue by bansheeat** [uBlockOrigin/uAssets#24651]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.apfeltalk.de/community/forums/iphone-und-ios.114/`

### Category

breakage

### Description

The Webpage is not loading

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 150369
 cosmetic: 52598
 scriptlet: 20462
 html: 1882
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39414-118, 47m
  ublock-badware: 9948-1, 47m Δ
  ublock-privacy: 1038-4, 47m Δ
  ublock-unbreak: 2463-1, 47m Δ
  easylist: 87468-170, 47m
  easyprivacy: 52981-62, 17m Δ
  plowe-0: 3548-989, 47m
  DEU-0: 7515-37, 47m
  urlhaus-1: 22315-0, 47m
  ublock-quick-fixes: 162-2, 47m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 38 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 282 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googlesyndication.com: 6
  googletagmanager.com: 1
 extended:
  ##.samCodeUnit
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
What do you mean "The Webpage is not loading"? Can you screenshot it?
