### ISSUE TITLE
web.skype.com: breakage

### ISSUE THREAD

**Issue by georg122** [uBlockOrigin/uAssets#24667]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
web.skype.com
```

### Description

*Use a clear incognito mode* If you create a new microsoft account through the above website or another one of microsoft, and you visit the specific website for the first time (for that account - it has to be a new account), the webpage will infinitely be loading, trying to load something (maybe trackers) which get blocked by ublock origin. If I disable Ublock Origin, the website loads. If I enable it again after web.skype.com has loaded one time (with ublock off) it will still load, but probably the website got the information it needed from my computer/browser. Please fix it, but still protect the privacy, thanks!

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a34f9a05-10bc-4081-b678-4662b743be79)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 155073
 cosmetic: 47652
 scriptlet: 21960
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39375-117, 4m Δ
  ublock-badware: 9897-1, 4m Δ
  ublock-privacy: 1042-2, 4m Δ
  ublock-unbreak: 2406-0, 4m Δ
  ublock-quick-fixes: 173-0, 4m Δ
  easylist: 87552-556, 30m
  easyprivacy: 52996-182, 4m Δ
  urlhaus-1: 29325-0, 30m
  plowe-0: 3548-619, 30m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 747 ms
 maxAssetCacheWait: 277 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  bing.com: 2
  microsoft.com: 10
```

</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce again, step-by-step using `-`?

**Comment by georg122** [comment]
@stephenhawk8054 
Sure!

In the above case I used latest version of Edge. (I have also used Brave but seems that their filter is also causing this on top of ublock origin)

Firstly make sure you got the latest version of ublock origin extension from Chrome store and also that you have allowed it to run in private windows

Then make sure you've closed the browser before (because if you used private windows and have one window opened, the cookies of the websites you visited persist until you close all the private windows)

1. Click the sandwich icon at the top right
2. Click New InPrivate window 
3. Visit web.skype.com
4. Create a new microsoft account (ending in outlook for example) - it's not necessary to add any recovery details or anything just follow the steps there until verification of the robot 
5. visit web.skype.com 
6. it will keep loading infinitely (I noticed the ublock counter increases over the time, while the website keeps loading)

**Comment by stephenhawk8054** [comment]
> until verification of the robot

Do I need to complete the verification?

**Comment by georg122** [comment]
@stephenhawk8054  yes, in order to create a new account

**Comment by georg122** [comment]
after having it loading infinitely, now the ublock shows this

uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 155073
 cosmetic: 47652
 scriptlet: 21960
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39375-117, 1h.13m Δ
  ublock-badware: 9897-1, 1h.13m Δ
  ublock-privacy: 1042-2, 1h.13m Δ
  ublock-unbreak: 2406-0, 1h.13m Δ
  ublock-quick-fixes: 173-0, 1h.13m Δ
  easylist: 87552-556, 1h.39m
  easyprivacy: 52996-182, 1h.13m Δ
  urlhaus-1: 29325-0, 1h.39m
  plowe-0: 3548-619, 1h.39m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 747 ms
 maxAssetCacheWait: 277 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  bing.com: 2
  microsoft.com: 24

**Comment by georg122** [comment]
![image](https://github.com/user-attachments/assets/f23e8a99-bc68-4a4c-a630-c48a38da3f83)

**Comment by stephenhawk8054** [comment]
I can't reproduce it. I created a new account and the page logged in normally

![image](https://github.com/user-attachments/assets/c3dc755e-2ef9-4608-b55c-14cd2f11b6e3)

**Comment by georg122** [comment]
@stephenhawk8054 I just tried with Brave browser too and it won't work. I tried on mobile and on another laptop still nothing. I have to disable their shields and then ublock origin and then if I reload it works. Are you sure you only have one private window, because at the top right it says 2 private windows open. Maybe the cache wasn't cleared. Try a new browser on your computer

**Comment by stephenhawk8054** [comment]
The other private window is the uBO logger window. That's the first incognito window that I created an account to test. I won't create another account to test any more when it gave me 20 captchas with very small images to solve (and I failed one, so it's 40 captchas).

**Comment by georg122** [comment]
@stephenhawk8054 This is probably IP related, if you are sharing Wi-Fi or anything. I got that too, but mostly it asks for one or 4 captchas. Try to renew your IP address or a VPN. Maybe someone else could try too. I posted on Brave community too, and they confirmed that this happens with the filters on. 
https://community.brave.com/t/web-skype-com-doesnt-load/555623/21

**Comment by stephenhawk8054** [comment]
Test this filter

```adb
/c.gif?$image,redirect-rule=1x1.gif,domain=web.skype.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by georg122** [comment]
@stephenhawk8054 it works. What that rule is or does?

**Comment by stephenhawk8054** [comment]
It redirects the tracking image to a local 1x1 pixel gif image.

**Comment by georg122** [comment]
> It redirects the tracking image to a local 1x1 pixel gif image.

Is this something I should add manually in each new laptop/browser? or can be integrated in the filters by default?

**Comment by stephenhawk8054** [comment]
It's already added to the main list: https://github.com/uBlockOrigin/uAssets/commit/472a07ac65d71f81dba48cfb342b2e2c4689690f

The fix will be auto-updated to users in about 5-6 hours.

**Comment by georg122** [comment]
@stephenhawk8054 Thank you very much for detecting this and for your help. I appreciate it!
