### ISSUE TITLE
Twitter Embedded Tweets

### ISSUE THREAD

**Issue by Miterion** [uBlockOrigin/uAssets#2466]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://edition.cnn.com/2018/06/04/politics/donald-trump-pardon-tweet/index.html`

### Describe the issue

Twitter offers users to embed tweets as cards. They have a graceful fallback (without pictures) but it would be nice if they could be activated more easily.

### Before
![screenshot-2018-6-4 trump i have absolute right to pardon myself](https://user-images.githubusercontent.com/4395770/40922967-ec66a5ec-6813-11e8-8d8f-9bc501a019ba.png)
### After
![screenshot-2018-6-4 trump i have absolute right to pardon myself](https://user-images.githubusercontent.com/4395770/40922982-f45c1e76-6813-11e8-889c-67dc7ce4ae79.png)

### Versions

- Browser/version: Firefox 60.0.1 (64-bit)
- uBlock Origin version: latest

### Settings
```
- Twitter as 3rd-party
	* platform.twitter.com
		_ cdn.syndication.twimg.com script allow
		_ platform.twitter.com frame allow
		_ platform.twitter.com script allow
		_ syndication.twitter.com frame allow
		_ syndication.twitter.com xhr allow
```

**Comment by gorhill** [comment]
Taking into account the guidelines for recipes, I come up with:

    Twitter as 3rd-party
    	* platform.twitter.com
    		_ cdn.syndication.twimg.com script allow
    		_ platform.twitter.com * allow
    		_ platform.twitter.com script allow
    		_ platform.twitter.com frame allow

**Comment by gwarser** [comment]
@Miterion where you learn how to write recipes? https://github.com/gorhill/uMatrix/wiki/Ruleset-recipes#contributing-recipes
