### ISSUE TITLE
euroszeilen.utwente.nl: breakage

### ISSUE THREAD

**Issue by MartijnVerkleij** [uBlockOrigin/uAssets#24660]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
euroszeilen.utwente.nl
```

### Description

The logo's in the footer are incorrectly hidden by "cosmetic filtering".

Specifically, the rule `.uk-flex-center.uk-grid-collapse,` is triggering it.

the rule below it, `.uk-flex-center.uk-grid-collapse,` may cause a similar issue for other sites than this one.

Both these rules are a combination of two directives of the uikit css framework and are too broad to use as a cosmetic filter. They should be replaced by more specific filters on the websites they were intended to block content in.

### Other extensions used

tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 159620
 cosmetic: 207087
 scriptlet: 34423
 html: 2144
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-social: 23187-50, 7m
  fanboy-thirdparty_social: 68-3, 7m
  fanboy-cookiemonster: 51431-188, 7m
  fanboy-social: 16022-753, 7m
  ublock-annoyances: 5930-63, 56m Δ
  adguard-cookies: 30573-3793, 7m
  adguard-popup-overlays: 27563-1110, 7m
  adguard-mobile-app-banners: 5357-27, 7m
  adguard-other-annoyances: 14813-474, 7m
  adguard-widgets: 2619-19, 7m
  easylist-annoyances: 4650-308, 7m
  easylist-chat: 203-17, 7m
  [4 lists not shown]: [too many]
 default:
  ublock-filters: 39436-118, 56m Δ
  ublock-badware: 9837-1, 56m Δ
  ublock-privacy: 1037-4, 56m Δ
  ublock-unbreak: 2465-1, 56m Δ
  easylist: 87502-170, 56m Δ
  easyprivacy: 52988-62, 56m Δ
  urlhaus-1: 22500-0, 7m
  plowe-0: 3548-989, 7m
  ublock-quick-fixes: 172-2, 56m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 456 ms (selfie)
 maxAssetCacheWait: 133 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.uk-flex-center.uk-grid-collapse

```
</details>

**Comment by krystian3w** [comment]
Broken by EasyList Cookie Notices.

You can start test:
```adb
utwente.nl#@#.uk-flex-center.uk-grid-collapse
```
