### ISSUE TITLE
astrobin.com: breakage

### ISSUE THREAD

**Issue by SWlvl60** [uBlockOrigin/uAssets#24664]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.astrobin.com/r982xl/`

### Category

breakage

### Description

With uBO enabled, images **sometimes** dont load. I have made sure that its not caused by any of my other extensions and i have observed this behavior over multiple days. It doesnt always happen but i can recreate it when opening this link 

https://app.astrobin.com/equipment/explorer/telescope/495/ts-optics-ed-80mm-f7-tsed80f7

and middle clicking on any of the images below to open them in a new tab. It happens on the entire site, not only this equipment filter site.

Sometimes they load, sometimes they dont and i have to refresh many times for the image to load. If i do this when uBO is disabled, all images load on the first try. 

### Other extensions used

SponsorBlock, AhaMusic, enhanced-264ify. Better Youtube shorts, auto quality for youtube, FastForward, Lightshot, Honey, Tampermonkey, Save image as type (local), CRX Extractor, Hyperchat for Youtube, Kachelmann Unblocker (local), Pixiv Toolkit, Return Youtube dislike, WebRTC leak shield. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2](https://github.com/user-attachments/assets/441566ac-55e4-45f0-94dd-1938580488d4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 160756
 cosmetic: 111606
 scriptlet: 27552
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51431-200, now
  ublock-cookies-easylist: 1284-0, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4650-15, now
  easylist-chat: 203-0, now
  easylist-newsletters: 7418-26, now
  easylist-notifications: 3118-82, now
  DEU-0: 7515-4, now
 default:
  user-filters: 22-2, never
  ublock-filters: 39375-302, 3m Δ
  ublock-badware: 9897-1, 3m Δ
  ublock-privacy: 1042-2, 3m Δ
  ublock-unbreak: 2406-2, 3m Δ
  ublock-quick-fixes: 173-0, 3m Δ
  easylist: 87552-581, 3m Δ
  easyprivacy: 52996-733, 3m Δ
  urlhaus-1: 29325-0, now
  plowe-0: 3548-0, now
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 493 ms (selfie)
 maxAssetCacheWait: 93 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  astrobin.com: 2
  cloudflareinsights.com: 1
  doubleclick.net: 1
 extended:
  ##.back-to-top:not(body):not(html)
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
test

`||placeholder.com^$3p,badfilter`

**Comment by SWlvl60** [comment]
Works! Thank you.
