### ISSUE TITLE
ensonhaber.com: breakage

### ISSUE THREAD

**Issue by hknx** [uBlockOrigin/uAssets#24665]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ensonhaber.com/`

### Category

breakage

### Description

daha fazla yorum yükle butonu kayboluyor. veya etkin olmuyor. 

**Load more comments button disappears or is inactive.**

### Other extensions used

yok

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran görüntüsü 2024-07-29 181921](https://github.com/user-attachments/assets/22f0ea41-37d1-4786-b911-5f86849b06b2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 157579
 cosmetic: 57943
 scriptlet: 23603
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, never
  https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
 default:
  user-filters: 0-0, never
  TUR-0: 13371-10, now
  easylist: 87552-560, 1h.9m Δ
  easyprivacy: 52996-645, 1h.9m Δ
  plowe-0: 3548-1, 13m
  ublock-badware: 9897-1, 1h.9m Δ
  ublock-filters: 39375-291, 1h.9m Δ
  ublock-privacy: 1042-2, 1h.9m Δ
  ublock-quick-fixes: 173-0, 1h.9m Δ
  ublock-unbreak: 2406-2, 1h.9m Δ
  urlhaus-1: 29325-0, now
filterset (user): [empty]
trustedset:
 added: [array of 41 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 369 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  bik.gov.tr: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  mrf.io: 1
 extended:
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ###sticky-ads
  ##.ad
  ##.aksa
  ##.hd-280.text-center
  ###top-adbar
  ##+js(remove-attr, data-href, span[data-href^="https://ensonhabe…
  ##+js(no-setInterval-if, flipHover)
```
</details>

**Comment by mapx-** [comment]
tested here:

`https://www.ensonhaber.com/gundem/saldiri-hazirligindaki-pkkkckli-teroristler-vesile-duran-ve-dilan-oklu-olduruldu`

the button is visible and usable

**Comment by punisher018** [comment]
`||api-stg.ensonhaber.com/api/v2/promote`

This rule breaks it. (In Adguard Turkish list) But it doesn't on everypage. You can look at it on this page.

`https://www.ensonhaber.com/gundem/cumhurbaskani-erdogan-kalles-suikasti-lanetliyorum`

**Comment by stephenhawk8054** [comment]
I can still see the button and clicking on it works normally for me with Turkish list.

**Comment by punisher018** [comment]
Btw on my side there is only the disappearance of the button on some pages. It works if there is a load more button.
