### ISSUE TITLE
ntp.msn.com: breakage

### ISSUE THREAD

**Issue by dedestem** [uBlockOrigin/uAssets#24661]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
edge home page

or ntp.msn.com (URL DOES NOT WORK) but the adblocker tells this is the domain
```

### Description

Everthing is fine execept that your favorite boxes are broken you cant click them to go to that page

### Other extensions used

I turned off every extension extensions were not the problem anyways here is the list

Cookie editor
Color picker
This adblocker

Anyone have extension recommendations?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.2
Chromium: 127
filterset (summary):
 network: 148511
 cosmetic: 49325
 scriptlet: 21971
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39359-278, 5m Δ
  ublock-badware: 9836-1, 5m Δ
  ublock-privacy: 1042-2, 5m Δ
  ublock-unbreak: 2406-0, 5m Δ
  ublock-quick-fixes: 172-0, 5m Δ
  easylist: 87493-561, 5m Δ
  easyprivacy: 52995-640, 5m Δ
  urlhaus-1: 22315-0, 1d
  plowe-0: 3547-0, 6d.13h.46m
  NLD-0: 2315-39, 1d.13h.39m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 234 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how the whole screen looks like (including the URL bar)?

**Comment by stephenhawk8054** [comment]
Then that page is a privilege page and no extensions are allowed to run on that, including uBO: https://github.com/gorhill/uBlock/wiki/Privileged-Pages

If that page is broken, your Edge is having issue or something outside the browser is blocking things.
