### ISSUE TITLE
Multiple website crash on latest chromium with ublock enabled

### ISSUE THREAD

**Issue by 514guy** [uBlockOrigin/uAssets#24666]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://metro.co.uk/
https://www.youtube.com
https://pastebin.com/
```

### Description

Latest edge canary 129.0.2744.0  borks with Error code: STATUS_ACCESS_VIOLATION, with ubo 1.58.1rc11. Chromium/EDGE beta 127.0.2651.74 and Firefox is not affected. Using ubo's logger is almost useless, as the SAV occurs on pastebin before any visible page loading occurs. Issue does not occur in igcognito tab, or if UBO is disabled.

### Other extensions used

Violentmonkey 2.20.1
Return Youtube Dislike 3.0.0.16
CNL Decryptor 2.1.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.1rc11
Chromium: 128
filterset (summary):
 network: 155076
 cosmetic: 47652
 scriptlet: 21966
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 87552-556, never
  easyprivacy: 52996-640, 8m
  plowe-0: 3548-0, 8m
  ublock-badware: 9897-1, 8m
  ublock-filters: 39382-278, 8m
  ublock-privacy: 1042-2, 8m
  ublock-quick-fixes: 173-0, 8m
  ublock-unbreak: 2406-0, 8m
  urlhaus-1: 29325-0, 8m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 389 ms (selfie)
 maxAssetCacheWait: 83 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: **1**

```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uBlock-issues/issues/3205

Remind that

> Chrome/Edge Canary are not officially supported, too high likelihood of breakage ([example](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2869)). Use either beta or stable.

https://github.com/uBlockOrigin/uBlock-issues/issues/3217#issuecomment-2227376037

**Comment by garry-ut99** [comment]
> stephen: Continue here: [uBlockOrigin/uBlock-issues#3205](https://github.com/uBlockOrigin/uBlock-issues/issues/3205)

Looking at OP's description, it might look like so, but might be a different cause as well:

>  514guy: borks with Error code: STATUS_ACCESS_VIOLATION

A duplicate of:

- https://github.com/uBlockOrigin/uBlock-issues/issues/3205
- https://github.com/uBlockOrigin/uBlock-issues/issues/3319

Also invalid like already stated in documentation:

- https://github.com/gorhill/uBlock/wiki/Can-uBO-crash-a-browser%3F
