### ISSUE TITLE
studocu.com: nuisance

### ISSUE THREAD

**Issue by ionixio** [uBlockOrigin/uAssets#24663]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.studocu.com/row/document/uganda-martyrs-university/information-technology/disks-and-disk-partitions-in-linux/65208434`

### Category

nuisance

### Description

trash popup banner

### Other extensions used

CanvasBlocker, SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 166798
 cosmetic: 68081
 scriptlet: 21941
 html: 1903
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39448-118, 1h.48m Δ
  ublock-badware: 9893-1, 1h.48m Δ
  ublock-privacy: 1037-4, 1h.48m Δ
  ublock-unbreak: 2465-1, 1h.48m Δ
  ublock-quick-fixes: 172-2, 1h.48m Δ
  easylist: 87521-170, 1h.48m Δ
  easyprivacy: 52996-62, 1h.48m Δ
  urlhaus-1: 22500-0, 39m
  plowe-0: 3548-989, 39m
  RUS-0: 40798-148, 48m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 135 ms (selfie)
 maxAssetCacheWait: 47 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  studocu.com: 1
  segment.com: 1
 extended:
  ##.ad-block
  ##.sponslink
  ##.banner-ads:not(.textads)
  ##.block-adv
  ##.amp-ad
```
</details>

**Comment by stephenhawk8054** [comment]
Which banner? Can you screenshot it?

**Comment by ionixio** [comment]
понедельник, 29 июля 2024 г. в 15:41:42 GMT+3, stephenhawk8054 ***@***.***> написал(-а):  
 
 


Which banner? Can you screenshot it?

**Comment by stephenhawk8054** [comment]
Please reply directly on github. Don't reply via email. Images cannot be sent via email.

**Comment by ionixio** [comment]
![Снимок экрана_2024-07-29_15-47-38](https://github.com/user-attachments/assets/ebeaf7f5-3456-475c-9636-65f32087fca8)

**Comment by stephenhawk8054** [comment]
It's paywall. You can use these as your custom filters:

```adb
studocu.com##article div[style^="margin-top"]:has(a[data-test-selector="preview-banner-upload-first-cta"]):style(visibility: hidden !important;)
studocu.com##._869f7c361ca9:style(visibility: hidden !important;)
studocu.com##.page-content:style(display: block !important; filter: none !important;)
```

**Comment by ionixio** [comment]
I add these 3 custom filters to my uBlock Origin. Now, all fixed, trash banner is removed! Thank You very much for your answer!:)
