### ISSUE TITLE
nbcolympics.com: breakage

### ISSUE THREAD

**Issue by SheaM29** [uBlockOrigin/uAssets#24669]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nbcolympics.com/videos/fink-peaty-tie-silver-wild-100m-breaststroke-final`

### Category

breakage

### Description

The video player does not initialize when Ublock origin is enabled. When I disable it, the video loads properly

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 155080
 cosmetic: 47667
 scriptlet: 21967
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 173-0, now
 default:
  user-filters: 0-0, never
  easylist: 87552-469, now
  easyprivacy: 52996-621, now
  plowe-0: 3548-0, now
  ublock-badware: 9897-1, now
  ublock-filters: 39399-365, now
  ublock-privacy: 1047-2, now
  ublock-unbreak: 2406-19, now
  urlhaus-1: 29325-0, now
filterset (user): [empty]
trustedset:
 added: [array of 66 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 547 ms (selfie)
 maxAssetCacheWait: 251 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  celtra.com: 1
  lightboxcdn.com: 2
  micpn.com: 1
  nbcuni.com: 1
 extended:
  ##+js(set-constant, adblockDetect, noopFunc)
```
</details>

**Comment by mapx-** [comment]
update chrome, uBO to the last versions, test again, disable any other extension
