### ISSUE TITLE
support.google.com: breakage

### ISSUE THREAD

**Issue by Daplugg23** [uBlockOrigin/uAssets#24678]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://support.google.com/android/answer/12623953?visit_id=638579113802438411-3905677561&p=restricted_settings&rd=1`

### Category

breakage

### Description

Site will not load with ublock origin enabled

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.1rc11
Chromium Mobile: 128
filterset (summary):
 network: 165809
 cosmetic: 168215
 scriptlet: 36114
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30613-61, 1m
  ublock-cookies-adguard: 1323-0, 1m
  fanboy-cookiemonster: 51431-4007, 1m
  ublock-cookies-easylist: 1322-1322, 1m
  adguard-popup-overlays: 27584-301, 1m
  adguard-mobile-app-banners: 5365-19, 1m
  adguard-other-annoyances: 14818-314, 1m
  adguard-widgets: 2619-13, 1m
  ublock-annoyances: 6010-12, now Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 39858-116, now Δ
  ublock-badware: 9891-1, 2m
  ublock-privacy: 1048-2, 2m
  ublock-unbreak: 2409-21, now Δ
  ublock-quick-fixes: 175-2, 2m
  adguard-mobile: 9622-166, 2m
  easylist: 87560-679, 2m
  easyprivacy: 52996-4, now Δ
  urlhaus-1: 29760-0, 2m
  plowe-0: 3548-619, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2643 ms
 maxAssetCacheWait: 1002 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  google.com: 2
  google-analytics.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Which browser are you using?

**Comment by krystian3w** [comment]
Lemur, Kiwi, Ungoogled Chromium (legacy), Edge Nightly or Yandex Mobile browser (if there are no blocks against using uBo, uBo dev and uBo lite as on PC and macOS).

If the error does not occur with Edge Nightly/Dev/Beta, there is probably no point in wasting time.

**Comment by Daplugg23** [comment]
The latest Edge CanaryAndroid

**Comment by stephenhawk8054** [comment]
Edge Canary is not officially supported: https://github.com/uBlockOrigin/uBlock-issues/issues/3217#issuecomment-2227376037
