### ISSUE TITLE
tvline.com: detection

### ISSUE THREAD

**Issue by 3052** [uBlockOrigin/uAssets#24677]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tvline.com/interviews/the-boys-erin-moriarty-shapeshifter-annie-season-4-finale-1235306119/`

### Category

detection

### Description

Disable Your Adblocker

### Other extensions used

!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 121
filterset (summary):
 network: 155489
 cosmetic: 47570
 scriptlet: 20502
 html: 1887
listset (total-discarded, last-updated):
 default:
  user-filters: 17-0, never
  ublock-filters: 39486-118, now
  ublock-badware: 9899-1, now
  ublock-privacy: 1042-4, now
  ublock-unbreak: 2465-1, now
  ublock-quick-fixes: 174-2, now
  easylist: 87560-170, now
  easyprivacy: 52996-62, now
  urlhaus-1: 29760-0, now
  plowe-0: 3548-989, now
filterset (user): [array of 34 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 added: [array of 138 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4821 ms (selfie)
 maxAssetCacheWait: 218 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 31
 network:
  blogherads.com: 4
  connatix.com: 1
  fouanalytics.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  jwplatform.com: 1
  lightboxcdn.com: 1
  mediavoice.com: 2
  onetrust.com: 1
  pinterest.com: 1
  pmc-pp-tou.s3.us-west-1.amazonaws.com: 2
  pmc.com: 2
  scorecardresearch.com: 1
  skimresources.com: 1
  snowmentor.com: 2
  succeedscene.com: 1
  swiftypecdn.com: 2
  taboola.com: 1
  trackonomics.net: 1
  tru.am: 1
  wp.com: 2
 extended:
  ###skin-ad-left-rail-container
  ###skin-ad-right-rail-container
  ##.admz
  ##.pmc-adm-boomerang-pub-div
  ###adm-inline-article-ad-1
  ##.ad-text
  ###taboola-below-article-thumbnails
  ##.widget_pmc-ads-widget
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-on-property-write, _sp_)
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
```
</details>

**Comment by 3052** [comment]
I think its fixed now

**Comment by PlaceboPRS** [comment]
I updated with the latest version through Firefox/addons/update and it's detecting the adblocker again, whereas yesterday when I'd temporarily installed the version on Git it wasn't detecting it...
