### ISSUE TITLE
nytimes.com: breakage

### ISSUE THREAD

**Issue by LocutusOfNord** [uBlockOrigin/uAssets#24679]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.nytimes.com/games/connections`

### Category

breakage

### Description

After completing NYT's daily Connections puzzle and clicking on "View Results", a different view pops up showing the player's daily results and a black "Share Your Results" button at the bottom. Under normal circumstances, clicking on this button copies the results to the clipboard, and a small black notification appears to inform you it has done so, which I have screenshotted and (hopefully - not sure I've done it correctly) attached to this report. 

With uBlock enabled, this results _are_ still copied to the clipboard, but the notification that it has done so is absent. I've tried to address this myself with custom filters, but I really have no idea what I'm doing. 

While it's technically a breakage, the issue is more of a minor annoyance, as ultimately, the copying functionality _does_ still work - I'd just like the notification that it has happened.

Thanks for your help!

### Other extensions used

BetterTTV, Enhancer for YouTube, Twitch Chat Pronouns

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/b9bce460-2d6e-4f6b-936b-1f0334955454)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 155490
 cosmetic: 47553
 scriptlet: 20502
 html: 1887
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39486-118, 1h.1m Δ
  ublock-badware: 9899-1, 1h.1m Δ
  ublock-privacy: 1042-4, 1h.1m Δ
  ublock-unbreak: 2465-1, 1h.1m Δ
  ublock-quick-fixes: 174-2, 1h.1m Δ
  easylist: 87560-170, 1h.1m Δ
  easyprivacy: 52996-62, 1h.1m Δ
  urlhaus-1: 29760-0, now
  plowe-0: 3548-989, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2907 ms (selfie)
 maxAssetCacheWait: 2622 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  nytimes.com: 3
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.pz-ad-box
  ###ad-top
  ###ad-bottom
```
</details>

**Comment by krystian3w** [comment]
At my side guilty is EasyPrivacy and all other projects with blockade `sentry.io` host:

```adb
||sentry.io^$3p
```

So unlock can be risky for privacy.

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
nytimes.com#@#.pz-ad-box
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by LocutusOfNord** [comment]
> Can you test this filter?
> 
> ```
> nytimes.com#@#.pz-ad-box
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

With this change applied as instructed, the notification box is back. Thank you.
