### ISSUE TITLE
nypost.com: detection

### ISSUE THREAD

**Issue by DanNJ316** [uBlockOrigin/uAssets#24672]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nypost.com/sports/`

### Category

detection

### Description

Adblock detection

### Other extensions used

FB Purity

Show History Frequent Sites Button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 115
filterset (summary):
 network: 155048
 cosmetic: 47583
 scriptlet: 20504
 html: 1887
listset (total-discarded, last-updated):
 default:
  user-filters: 41-1, never
  ublock-filters: 39481-118, 1h.58m Δ
  ublock-badware: 9899-1, 1h.58m Δ
  ublock-privacy: 1042-4, 1h.58m Δ
  ublock-unbreak: 2465-1, 1h.58m Δ
  easylist: 87552-170, 1h.58m Δ
  easyprivacy: 52996-62, 1h.58m Δ
  urlhaus-1: 29325-0, 11m
  plowe-0: 3548-989, 11m
  ublock-quick-fixes: 173-2, 1h.58m Δ
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5016 ms
 maxAssetCacheWait: 1905 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  nypost.com: 1
  adlightning.com: 1
  adsafeprotected.com: 2
  advertising.com: 1
  amazon-adsystem.com: 1
  bounceexchange.com: 1
  cxense.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gracenote.com: 1
  merequartz.com: 2
  p-n.io: 1
  p7cloud.net: 1
  permutive.app: 1
  scorecardresearch.com: 1
  speedcurve.com: 1
  typekit.net: 2
  wp.com: 2
  yahoo.com: 2
  zqtk.net: 1
 extended:
  ##.widget_nypost_dfp_ad_widget
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.ad--container
  ##.ad__wrapper
  ##.ad__placeholder
  ##.dfp-ad
  ##.ad-wrapper
  ##.ad__label
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-slot
  ##+js(abort-on-property-read, googletag.cmd)
  ##+js(abort-on-property-write, _sp_)
  ##+js(json-prune, dataLayer.trackingId user.trackingId)
  ##+js(remove-cookie, blaize_tracking_id)
  ##+js(abort-current-script, document.createElement, admiral)
  ##+js(abort-on-property-read, googletag)
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
```
</details>

**Comment by Cain57** [comment]
Yep, me too!!  NY Post is blocking me. 

![image](https://github.com/user-attachments/assets/bea6439b-b520-4ae0-92be-7c7161451219)

**Comment by zenstorage** [comment]
Try: 

```
nypost.com##+js(acs, decodeURI, createElement)
```

**Comment by DanNJ316** [comment]
> Try:
> 
> ```
> nypost.com##+js(acs, decodeURI, createElement)
> ```

It works, thank you very much!

**Comment by Yuki2718** [comment]
They have admiral script on src too, scriptlet alone doesn't work. It's probably @stephenhawk8054 's fix a few hours ago.

**Comment by Yuki2718** [comment]
@pgl
