### ISSUE TITLE
[nsfw] rule34porn.net: detection

### ISSUE THREAD

**Issue by Thimble15446** [uBlockOrigin/uAssets#24688]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rule34porn.net/`

### Category

detection

### Description

![image](https://github.com/user-attachments/assets/3880f88f-caf6-4452-8887-421d0f99d856)

### Other extensions used

![image](https://github.com/user-attachments/assets/60fbf7f2-e5a8-4216-8be0-9655dc2a5b1b)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Page loads then media box turns into the box in the screenshot below

![image](https://github.com/user-attachments/assets/c0a7dc1c-49a6-40d2-b2c9-5be792a206fc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 125
filterset (summary):
 network: 155169
 cosmetic: 47670
 scriptlet: 21970
 html: 0
listset (total-discarded, last-updated):
 added:
  curben-phishing: 500-0, now
 default:
  user-filters: 14-0, never
  easylist: 87565-555, now
  easyprivacy: 53009-641, now
  plowe-0: 3548-0, now
  ublock-badware: 9913-3, now
  ublock-filters: 39410-277, now
  ublock-privacy: 1045-2, now
  ublock-quick-fixes: 144-0, now
  ublock-unbreak: 2411-0, now
  urlhaus-1: 28880-0, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 396 ms (selfie)
 maxAssetCacheWait: 293 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  magsrv.com: 8
 extended:
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(abort-current-script, Math.random, ExoLoader)
  ##+js(abort-on-property-read, decodeURI)
  ##+js(no-setTimeout-if, showModal)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by Yuki2718** [comment]
Wondering if it worth generic redirect.

**Comment by stephenhawk8054** [comment]
We can add if there are more sites that need it. Currently not many as far as I see?

**Comment by Yuki2718** [comment]
Yeah, we will see. If to add it should be `/ad-provider.js|$xhr,redirect-rule=nooptext` as `magsrv.com` is just one of `realsrv.com` variants.

**Comment by Yuki2718** [comment]
Seen in https://manga18fx.com/manga/a-wonderful-new-world-02 too if you disable `manga18fx.com##+js(nostif, fetch)`.
