### ISSUE TITLE
e.mail.ru: ads

### ISSUE THREAD

**Issue by Dr3Dko** [uBlockOrigin/uAssets#24684]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://e.mail.ru/inbox/`

### Category

ads

### Description

too much ads from 30.07

### Other extensions used

too much ads from 30.07

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 174034
 cosmetic: 68082
 scriptlet: 21955
 html: 1902
listset (total-discarded, last-updated):
 default:
  user-filters: 11-0, never
  ublock-filters: 39465-118, 11m
  ublock-badware: 9899-1, 11m
  ublock-privacy: 1043-4, 11m
  ublock-unbreak: 2465-1, 11m
  ublock-quick-fixes: 174-2, 11m
  easylist: 87468-170, 11m
  easyprivacy: 52996-62, 11m
  urlhaus-1: 29760-0, 11m
  plowe-0: 3548-989, 12m
  RUS-0: 40799-148, 12m
filterset (user): [array of 11 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2532 ms
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 39
 network:
  mail.ru: 27
  imgsmail.ru: 2
  mradx.net: 10
 extended:
  ##a[title="Экосистема VK"]
  ###app-canvas .paginator-container:style(right: 8px !important)
  ##+js(href-sanitizer, [data-cke-saved-href^="https://checklink.m…
  ##+js(set-constant, Object.prototype.onLinkClick, noopFunc)
  ##+js(set-constant, Object.prototype.onLinkMouseDown, noopFunc)
  ##+js(json-prune, [].slot)
  ##+js(set-constant, Object.prototype.hasAdBlock, null)
  #@#+js(prevent-fetch, /\/apic\//)
  #@#+js(remove-node-text, script, violatedDirective)
  #@#+js(set-constant, Object.prototype.mimic, undefined)
  #@#+js(set-constant, document.title, null)
  #@#+js(set-constant, mr._mimic.locator.transform, undefined)
  #@#+js(abort-on-stack-trace, Object.prototype.ssrAds, completeRa…
  ##+js(prevent-fetch, /\/apic\//)
  ##+js(remove-node-text, script, violatedDirective)
  ##+js(set-constant, Object.prototype.mimic, undefined)
  ##+js(set-constant, document.title, null)
  ##+js(set-constant, mr._mimic.locator.transform, undefined)
  ##+js(abort-on-stack-trace, Object.prototype.ssrAds, completeRad…
```
</details>

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
The problem does not repeat itself. But I am still investigating this case. Most likely, there is a conflict with some third-party content blocking or filtering tool. I am considering adding additional rules that will prevent the consequences of the conflict. But for this, I need to know what third-party tools are used.
