### ISSUE TITLE
xe.com: nuisance

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#24681]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.xe.com/currencyconverter/`

### Category

nuisance

### Description

cookie warning

### Other extensions used

violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://github.com/user-attachments/assets/b07b5255-a2fe-45a1-abe8-b9768f8e0a87)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 160458
 cosmetic: 118215
 scriptlet: 31464
 html: 2145
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 67737-16489, now
  ublock-cookies-easylist: 1284-5, now
  easylist-annoyances: 4650-42, now
  easylist-chat: 203-0, now
  easylist-newsletters: 7400-34, now
  easylist-notifications: 3118-164, now
  ublock-annoyances: 5930-79, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39489-118, now Δ
  ublock-badware: 9899-18, now
  ublock-privacy: 1042-6, now
  ublock-unbreak: 2468-1, now Δ
  ublock-quick-fixes: 174-2, now
  easylist: 87562-151, now Δ
  easyprivacy: 52996-62, now Δ
  urlhaus-1: 29760-0, now
  plowe-0: 3548-989, now
  TUR-0: 13371-35, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1474 ms
 maxAssetCacheWait: 350 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  amplitude.com: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##.advertSlot
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by gototheskinny** [comment]
> Hello @gototheskinny, why are you using AdGuard and Popup Blocker with uBlock Origin? Those extensions are redundant with uBlock Origin. Disable the extensions and try again.

I'll try it again OK. But this site has that cookie warning in adguard as well.

**Comment by mapx-** [comment]
@gototheskinny 
test:

`xe.com##button:has-text(Accept):upward(section)`

@ryanbr @Alex-302

**Comment by Alex-302** [comment]
Done.

**Comment by gototheskinny** [comment]
> @gototheskinny test:
> 
> `xe.com##button:has-text(Accept):upward(section)`
> 
> @ryanbr @Alex-302

tested, it's working correctly.
