### ISSUE TITLE
welsh-dictionary.ac.uk: breakage

### ISSUE THREAD

**Issue by jchoules** [uBlockOrigin/uAssets#24683]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://welsh-dictionary.ac.uk/gpc/gpc.html
```

### Description

This domain serves the same website as geiriadur.ac.uk, whose breakage was reported in #22726. The symptoms are identical: the pane-based layout breaks down and only some header elements are visible. The cause also appears to be identical: the blocking of `fingerprint.js` causes `get_fingerprint` to be undefined.

### Other extensions used

_Indie Wiki Buddy_ 3.8.0
_Google search engine with udm=14 preset_ 1.0
I was still able to repro the problem with both disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 155055
 cosmetic: 47558
 scriptlet: 20505
 html: 1887
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 39489-118, 8m Δ
  ublock-badware: 9899-1, 8m Δ
  ublock-privacy: 1043-4, 8m Δ
  ublock-unbreak: 2468-1, 8m Δ
  ublock-quick-fixes: 174-2, 8m Δ
  easylist: 87562-170, 8m Δ
  easyprivacy: 52996-62, 8m Δ
  urlhaus-1: 29325-0, 11h.14m
  plowe-0: 3548-989, 7d.3m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 201 ms (selfie)
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Next time please just contiue commenting in that old thread if it's about the same collection of sites. All volunteers are notified with new comments.

**Comment by jchoules** [comment]
Thank you, will do.
