### ISSUE TITLE
infodolar.com: detection

### ISSUE THREAD

**Issue by davidmvk** [uBlockOrigin/uAssets#24697]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.infodolar.com/cotizacion-dolar-blue.aspx`

### Category

detection

### Description

Ublock is detected and ads appear on the site.

### Other extensions used

IDM extension, poper blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 155247
 cosmetic: 47678
 scriptlet: 21977
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87602-49, now
  easyprivacy: 53012-654, now
  plowe-0: 3548-372, now
  ublock-badware: 9917-18, now
  ublock-filters: 39441-364, now
  ublock-privacy: 1045-4, now
  ublock-quick-fixes: 138-0, now
  ublock-unbreak: 2412-15, now
  urlhaus-1: 29415-0, now
filterset (user): [empty]
trustedset:
 added: [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2078 ms (selfie)
 maxAssetCacheWait: 154 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 463
 no-scripting: true
 network:
  infodolar.com: 4
  360yield.com: 1
  4dex.io: 6
  a-mo.net: 11
  adform.net: 15
  adkernel.com: 3
  adnxs.com: 17
  amazon-adsystem.com: 18
  bidswitch.net: 1
  bootstrapcdn.com: 1
  cleverwebserver.com: 2
  cloudflare.com: 1
  createjs.com: 1
  creativecdn.com: 1
  criteo.com: 18
  criteo.net: 2
  datatables.net: 2
  doubleclick.net: 19
  eu-1-id5-sync.com: 2
  fastclick.net: 1
  google-analytics.com: 2
  google.com: 16
  googlesyndication.com: 9
  googletagmanager.com: 3
  gstatic.com: 1
  id5-sync.com: 7
  jquery.com: 1
  kaspersky-labs.com: 37
  kueezrtb.com: 5
  lijit.com: 3
  media.net: 7
  omnitagjs.com: 5
  onetag-sys.com: 10
  openx.net: 4
  pbstck.com: 11
  postrelease.com: 1
  presage.io: 1
  pubmatic.com: 29
  rubiconproject.com: 6
  scorecardresearch.com: 2
  script.ac: 1
  sddan.com: 7
  seedtag.com: 17
  sitescout.com: 1
  smartadserver.com: 12
  smilewanted.com: 5
  snigelweb.com: 6
  sportslocalmedia.com: 1
  springserve.com: 13
  stickyadstv.com: 78
  taboola.com: 2
  teads.tv: 1
  uidapi.com: 1
  vidoomy.com: 25
  yellowblue.io: 1
  zemanta.com: 6
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.adTop
  ##.adMiddle
  ##.adsbygoogle-noablate
  ##div[id^="adngin-"]
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by davidmvk** [comment]
Hi! Accessing from Argentina! I cannot upload a screenshot right now since I'm unable to replicate the issue. Is it possible it was fixed already?

**Comment by davidmvk** [comment]
Was able to reproduce the issue today. Here's a screenshot. 

![Screenshot_1](https://github.com/user-attachments/assets/f36de167-2eab-4bfb-a499-836bd3665165)
