### ISSUE TITLE
bjs.com: breakage

### ISSUE THREAD

**Issue by 42RoiDesRois42** [uBlockOrigin/uAssets#24690]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bjs.com/search?visualVariant.nonvisualVariant.mfname=Wellsley%20Farms`

### Category

breakage

### Description

Searches are broken due to blocking of elements on the page. Once disabled everything loads.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 127
filterset (summary):
 network: 154663
 cosmetic: 47664
 scriptlet: 21972
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87565-555, 5m Δ
  easyprivacy: 53009-641, 5m Δ
  plowe-0: 3548-0, now
  ublock-badware: 9913-1, 5m Δ
  ublock-filters: 39411-277, 5m Δ
  ublock-privacy: 1045-2, 5m Δ
  ublock-quick-fixes: 145-0, 5m Δ
  ublock-unbreak: 2411-0, 5m Δ
  urlhaus-1: 28880-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  bjs.com: 2
  adobedtm.com: 2
  facebook.net: 1
  lr-ingest.io: 1
  monetate.net: 1
  newrelic.com: 1
  pendo.io: 1
  redditstatic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||assets.adobedtm.com/*-source.min.js$script,domain=bjs.com
@@||cdn.pendo.io/agent/static/*/pendo.js$script,domain=bjs.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by 42RoiDesRois42** [comment]
That works. Thanks.
