### ISSUE TITLE
akefu.rf.gd: ads / nuisance

### ISSUE THREAD

**Issue by 055110** [uBlockOrigin/uAssets#24696]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
http://akefu.rf.gd/eso
http://akefu.rf.gd/ryan
```

### Description

1. "Privacy Policy" window that won't close
2. Notifications at the top reopening
3. 3 banners at the top of the page
4. Some ads at the bottom of the page
5. Fake threads that direct to advertisements

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 159122
 cosmetic: 47551
 scriptlet: 20512
 html: 1887
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39503-118, 6m Δ
  ublock-badware: 9919-4, 6m Δ
  ublock-privacy: 1040-53, 6m Δ
  ublock-unbreak: 2471-1, 6m Δ
  ublock-quick-fixes: 138-2, 6m Δ
  easylist: 87592-170, 6m Δ
  adguard-spyware-url: 1600-239, 2d.1h.8m
  easyprivacy: 53009-63, 6m Δ
  urlhaus-1: 28880-0, 6m
  curben-phishing: 504-0, 6m
  plowe-0: 3548-988, 2d.1h.8m
  LegitimateURLShortener: 2658-0, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15561 ms (selfie)
 maxAssetCacheWait: 3430 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Please report to here: https://github.com/easylist/easylist/issues/
