### ISSUE TITLE
yoreparo.com: nuisance

### ISSUE THREAD

**Issue by Agusstine** [uBlockOrigin/uAssets#24709]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.yoreparo.com/es/computadoras/notebooks/preguntas/5765886/mi-tecla-ctrl-se-queda-precionada-no-fisicamente`

### Category

nuisance

### Description

Can't remove blur on page with remove tool.

### Other extensions used

none.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 109
filterset (summary):
 network: 157050
 cosmetic: 54476
 scriptlet: 22447
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 87637-524, 11m Δ
  easyprivacy: 53014-654, 11m Δ
  plowe-0: 3548-0, 29m
  spa-0: 4065-3, 30m
  spa-1: 5859-190, now
  ublock-badware: 9973-1, 11m Δ
  ublock-filters: 39422-377, 11m Δ
  ublock-privacy: 1048-2, 11m Δ
  ublock-quick-fixes: 136-0, 11m Δ
  ublock-unbreak: 2416-4, 11m Δ
  urlhaus-1: 28765-0, 30m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14815 ms (selfie)
 maxAssetCacheWait: 7617 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.blur.solucion.post
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
yoreparo.com##.cta-bajo-pregunta + div[class^="div-block"]
yoreparo.com##.post.blur:style(filter: none !important;)
```

**Comment by stephenhawk8054** [comment]
Fixed in `EasyList – Other Annoyances` list
