### ISSUE TITLE
laprovence.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#24704]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.laprovence.com/`

### Category

ads

### Description

There are empty inserts that take up space.

### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 196748
 cosmetic: 158920
 scriptlet: 30521
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1107-0, 28m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 28m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51439-12121, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-4, 1h.17m
  adguard-cookies: 30639-1665, now
  ublock-cookies-adguard: 1284-1284, now
  fanboy-cookiemonster: 51439-51439, now
  ublock-cookies-easylist: 1284-0, now
  RUS-0: 40720-262, 28m Δ
 default:
  user-filters: 1-0, never
  ublock-filters: 39417-114, now
  ublock-badware: 9973-1, now
  ublock-privacy: 1048-2, now
  ublock-unbreak: 2414-1, now
  ublock-quick-fixes: 138-2, 28m Δ
  easylist: 87615-629, now
  easyprivacy: 53015-801, now
  urlhaus-1: 29495-0, 28m
  plowe-0: 3548-0, now
  FRA-0: 24690-379, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 137 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  laprovence.com: 1
  abtasty.com: 1
  aticdn.net: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 2
  opti-digital.com: 1
  pbstck.com: 1
  sparteo.com: 1
  viously.com: 3
 extended:
  ###div-gpt-ad-Habillage
  ###div-gpt-ad-Banniere_Haute
  ###div-gpt-ad-Rectangle
  ###div-gpt-ad-Pave_Bas
  ##body:not(.didomi-popup-open) #didomi-host
  ##div[data-iab-tag]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-current-script, document.createElement, __esModule)
```
</details>

**Comment by mapx-** [comment]
add

`laprovence.com##[class*="Ads"]`

@smed79 

@x-R0b0T-x report here: https://github.com/easylist/listefr/issues
