### ISSUE TITLE
v2.videoland.com: breakage

### ISSUE THREAD

**Issue by QueenDennis** [uBlockOrigin/uAssets#24703]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://v2.videoland.com/welcome`

### Category

breakage

### Description

website wont go past loading page

### Other extensions used

2fas, icloud, videodownloader, darkreader, pip,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 167219
 cosmetic: 209215
 scriptlet: 36195
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30630-73, 47m
  adguard-mobile-app-banners: 5368-1122, 47m
  adguard-other-annoyances: 14831-374, 47m
  adguard-popup-overlays: 27601-966, 47m
  adguard-social: 23212-1656, 47m
  adguard-widgets: 2619-46, 47m
  easylist-annoyances: 4654-94, now
  easylist-chat: 204-0, now
  easylist-newsletters: 7421-26, now
  easylist-notifications: 3120-3, now
  fanboy-cookiemonster: 51438-4007, now
  fanboy-social: 16002-24, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  NLD-0: 2317-39, 47m
  easylist: 87592-639, 47m Δ
  easyprivacy: 53009-736, 47m Δ
  plowe-0: 3548-0, now
  ublock-badware: 9917-1, 47m Δ
  ublock-filters: 39417-599, 47m Δ
  ublock-privacy: 1045-2, 47m Δ
  ublock-quick-fixes: 138-0, 47m Δ
  ublock-unbreak: 2412-2, 47m Δ
  urlhaus-1: 29415-0, 47m
filterset (user): [empty]
trustedset:
 added: [array of 21 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1310 ms (selfie)
 maxAssetCacheWait: 461 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  videoland.com: 1
  cookielaw.org: 1
  newrelic.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Do you know any free links that can reproduce the issue?
