### ISSUE TITLE
curseforge.com: ad left-over

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#24706]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.curseforge.com/minecraft/mc-mods/no-chat-reports
```

### Description

![image](https://github.com/user-attachments/assets/5f872e9d-97b6-4d93-8e20-26a4ce1fdc83)

Tested with a clean profile, default settings, no other extensions.
Only changes were adding uBlock Origin and disabling Firefox Enhanced Tracking Protection (Custom, disabling all checkboxes).

### Other extensions used

None.

### Screenshot(s)

Provided above.

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 155267
 cosmetic: 47567
 scriptlet: 20512
 html: 1890
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39543-118, 3m
  ublock-badware: 9899-1, 3m
  ublock-privacy: 1043-4, 3m
  ublock-unbreak: 2470-1, 3m
  ublock-quick-fixes: 138-2, 3m
  easylist: 87603-170, 3m
  easyprivacy: 52996-61, 3m
  urlhaus-1: 29495-0, 3m
  plowe-0: 3548-988, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3132 ms
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 70
 network:
  clarity.ms: 2
  doubleclick.net: 12
  google.com: 30
  googlesyndication.com: 4
  googletagmanager.com: 2
  nitropay.com: 2
  overwolf.com: 4
  scorecardresearch.com: 2
  youtube.com: 12
 extended:
  ##.project-description [href^="/linkout?remoteUrl="][href*="bise…
  ##+js(adjust-setInterval)
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
```
</details>

**Comment by mapx-** [comment]
add

`curseforge.com##.maho-container`

@ryanbr
