### ISSUE TITLE
globo.com

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#24707]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://g1.globo.com/
```

### Description

There are some background sites that are running in g1.globo.com which I believe should be blocked (but I'm just assuming; don't have any proof for them, except for one).
![image](https://github.com/user-attachments/assets/9557a08e-7252-4faa-bdb3-6658eb461f9d)

For `globo-mab`, I believe it should be blocked because `globo-ab` is.

For `horizon-schemas`, I believe it should be blocked because `horizon-track` is.

For `weather.api` and `geo-api` I believe they should be blocked for privacy reasons. The site asks for location permission, but even if you deny it still uses GeoData for the weather API (there's a weather widget in the site).

For `topics-privacy-sandbox`, I believe it should be blocked due to privacy reasons — see https://en.wikipedia.org/wiki/Privacy_Sandbox#Criticism.

Although this issue is for g1.globo.com, it can also be applied for all *.globo.com sites. (see `https://globo.com/` for the front-page of all sites).

And also, in the same site, `googletagmanager.com` is not fully blocked and I don't know why.
![image](https://github.com/user-attachments/assets/7b07f995-06c3-4f6d-abdd-39382b980eeb)

Tested with a clean profile, default settings, no other extensions.
Only changes were adding uBlock Origin and disabling Firefox Enhanced Tracking Protection (Custom, disabling all checkboxes).

### Other extensions used

None.

### Screenshot(s)

Provided above.

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 155267
 cosmetic: 47567
 scriptlet: 20512
 html: 1890
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39543-118, 15m
  ublock-badware: 9899-1, 15m
  ublock-privacy: 1043-4, 15m
  ublock-unbreak: 2470-1, 15m
  ublock-quick-fixes: 138-2, 15m
  easylist: 87603-170, 15m
  easyprivacy: 52996-61, 15m
  urlhaus-1: 29495-0, 15m
  plowe-0: 3548-988, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3132 ms
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 71
 network:
  globo.com: 45
  ads-twitter.com: 1
  aswpsdkus.com: 1
  chartbeat.com: 2
  clarity.ms: 1
  doubleclick.net: 2
  doubleverify.com: 1
  facebook.net: 1
  glbimg.com: 3
  google.com: 4
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  mrf.io: 1
  navdmp.com: 1
  permutive.app: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
  youtube.com: 2
 extended:
  ##.publicidade
  ##+js(no-setTimeout-if, f.parentNode.removeChild(f), 100)
  ##+js(trusted-set-cookie, _ga, GA1.1.000000000.1900000000, , , d…
```
</details>

**Comment by mapx-** [comment]
report here: https://github.com/easylist/easylist/issues
