### ISSUE TITLE
steamcommunity.com blocked

### ISSUE THREAD

**Issue by RVK1987** [uBlockOrigin/uAssets#24710]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://leetify.com/app/profile/
https://steamcommunity.com/
```

### Description

While on any Leetify user profile page, click the Steam icon to go to that person's Steam profile page to find that it did not load. Clicking on the reload button on the blocked steamcommunity page allows it to load normally. I found out that the steam profile page is blocked by the default filter list on uBOL. By disabling "Annoyances" and "Miscellaneous" the page is still blocked. By disabling those two categories plus the default allows the steamcommunity page to load immediately from Leetify's link. FYI uBOL is set to Optimal for me, changing it to Basic did not fix the problem. If I add the steamcommunity.com link to the ignore list the page loads normally from Leetify.

### Other extensions used

Steam Inventory Expert 1.0.0.0
Augmented Steam 4.0.1
Automatic Twitch: Drops, Moments and Points 1.6.2
Google Docs Offline 1.78.1
Idle Code Redeemer 1.9.1
Picture-in-Picture Extension (by Google) 1.11
Reddit Enhancement Suite 5.24.6
Save image as Type 1.2.4
SteamDB 4.5
Stream Cleaner 1.17.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Duplicated here: https://github.com/uBlockOrigin/uBOL-home/issues/156

For uBOL issues, please follow that repo.
