### ISSUE TITLE
Fake/badware Vercel domains

### ISSUE THREAD

**Issue by rANdecHo** [uBlockOrigin/uAssets#24719]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app
m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app
m-isist-emai-nmu-ne-qefa68dvbd. vercel.app
```

### Description

They are being posted by hacked/hijacked Facebook accounts. I have tried opening one of them but for some reason it redirects me to Amazon. Can someone check it?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s) (NSFW)</summary>

https://github.com/user-attachments/assets/316ddd43-4784-411c-b5a1-58397b696dc2

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

```
</details>

**Comment by JobcenterTycoon** [comment]
Known. The redirect is clientside, to see the code open the URL with `view-source:` at the beginning. This is the reason for the amazon redirect:

```
<script type="text/javascript">
//<![CDATA[
 function h(r, a) { var t = ""; if ("mix" == a) var h = 
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; else var h = 
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; for (var n = 0; r > n; n++) t += h.charAt(Math.floor(Math.random() * 
h.length)); return t };
 var device = navigator.userAgent
 
 if (device.match(/Iphone/i)|| device.match(/Ipod/i)|| device.match(/Android/i)|| device.match(/J2ME/i)|| device.match(/BlackBerry/i)|| device.match(/iPhone|iPad|iPod/i)|| device.match(/Opera Mini/i)|| device.match(/IEMobile/i)|| device.match(/Mobile/i)|| device.match(/Windows Phone/i)|| device.match(/windows mobile/i)|| device.match(/windows ce/i)|| device.match(/webOS/i)|| device.match(/palm/i)|| device.match(/bada/i)|| device.match(/series60/i)|| device.match(/nokia/i)|| device.match(/symbian/i)|| device.match(/HTC/i))
 {
 window.location = "./yismelbi.html?"+ h(7, '')+"";
 }else
{
window.location = "./dilainecpu.html?"+ h(7, '')+"";
}
//]]>
</script>
```

To prevent this use the dev tools to fake a mobile device.

I see its clearly malicious and redirect to phishing, i will block

**Comment by JobcenterTycoon** [comment]
Fake porn site, when i click on a "video" it redirect me to a facebook phishing site "facebook needs to verify your account information to allow access to this video" but only with a mobile user agent. Pretty stealthy.

`https://thepatrones.blob.core.windows.net/thepatrone/thepatrones.html`

The site itself is blank, the facebook source coming from `https://xyzxyz55.xyz/?api=1&lan=facebooknew&ht=1`

<details>

<img width="644" alt="Unbenannt" src="https://github.com/user-attachments/assets/5e5e6834-77b5-4097-b6f3-7b77cbce352f">



</details>

**Comment by rANdecHo** [comment]
Is there a reason why they do this? I've seen many phishing domains redirect to websites like Google or Amazon, but I thought they were just baits or something. Do they do this to avoid analysis by cybersecurity professionals or simple antivirus detection, for example?

**Comment by JobcenterTycoon** [comment]
Exacly. This is also why the source code is outsourced, a bot which doesn’t run javascript will "see" a blank site. A user will report `https://thepatrones.blob.core.windows.net/thepatrone/Facebook-Video-[...]` because its the landing page but when opened directly it just throws a error because the site checks the redirect chain.

**Comment by rANdecHo** [comment]
Wow. Now I'm wondering how many phishing sites I never reported because of this. Even though I reported some of them elsewhere, they were not acknowledged because 'there wasn't any malware or phishing.' Thanks for the explanation!

**Comment by JobcenterTycoon** [comment]
Yes many of them are advanced today. Suggestions for the future:

1. Open the uBO logger before you open a site you want to check. It will show the redirect chain and external requests.
2. When you get redirected to google or whatever check the source code with `view-source:`. A client side redirect will be exposed and mostly the real malicious landing page can be obtained from the inline script or HTML meta tag.
3. You can fake a mobile device with the developer tools (works 95%).
4. Don’t use a VPN or Proxy, they are mostly blocked or redirected.

Full URL list related for this issue:

```
https://m-isist-emai-nmu-ne-yx8nu6hs7k.vercel.app/
https://m-isist-emai-nmu-ne-6zft4bsbqh.vercel.app/
https://m-isist-emai-nmu-ne-qefa68dvbd.vercel.app/
https://thepatrones.blob.core.windows.net/thepatrone/thepatrones.html
https://xyzxyz55.xyz/?api=1&lan=facebooknew&ht=1
```
