### ISSUE TITLE
msdn.itellyou.cn: breakage

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#24711]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://msdn.itellyou.cn/`

### Category

breakage

### Description

Website is broken when uBlock Origin is enabled. I think it's due to cdn.staticfile.org has been blocked. 

### Other extensions used

No.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 252449
 cosmetic: 107387
 scriptlet: 39737
 html: 1897
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83921-4173, now
  adguard-mobile: 9624-57, now
  adguard-spyware-url: 1608-123, now
  adguard-spyware: 83685-1566, now
  block-lan: 70-0, now
  curben-phishing: 551-6, now
  dpollock-0: 11690-490, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39564-118, now
  ublock-badware: 10052-1, now
  ublock-privacy: 1043-4, now
  ublock-unbreak: 2475-1, now
  ublock-quick-fixes: 140-2, now
  easylist: 87658-2322, now
  easyprivacy: 53020-30347, now
  urlhaus-1: 28765-0, now
  plowe-0: 3548-1484, now
  CHN-0: 25315-240, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 276 ms (selfie)
 maxAssetCacheWait: 110 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  baidu.com: 1
  staticfile.org: 15
```
</details>

**Comment by stephenhawk8054** [comment]
The domain `staticfile.org` being blocked in the site belongs to `polyfill.io` who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.

**Comment by 0x391F** [comment]
Oh, I get it. Thanks!
