### ISSUE TITLE
limetorrents.ninjaproxy1.com: ads

### ISSUE THREAD

**Issue by Annoyed4ads** [uBlockOrigin/uAssets#24716]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://limetorrents.ninjaproxy1.com/A-Quiet-Place-Day-One-2024-1080p-WEBRip-1400MB-DD5-1-x264-Galaxy-torrent-18541330.html`

### Category

ads

### Description

gamestoday.org add keeps showing. I also tried a custom filter, it did not work :(

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 154890
 cosmetic: 47683
 scriptlet: 20538
 html: 1897
listset (total-discarded, last-updated):
 default:
  user-filters: 97-7, never
  ublock-filters: 39568-118, 3m
  ublock-badware: 10052-1, 3m
  ublock-privacy: 1043-4, 3m
  ublock-unbreak: 2475-1, 4m
  ublock-quick-fixes: 155-2, 4m
  easylist: 87676-170, 4m
  easyprivacy: 53021-62, 4m
  urlhaus-1: 28880-0, 4m
  plowe-0: 3548-989, 4m
filterset (user): [array of 97 redacted]
trustedset:
 added: [array of 109 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 396 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 no-large-media: true
 no-popups: true
 network:
  betteradsystem.com: 1
  d2kk0o3fr7ed01.cloudfront.net: 1
  mivrbnbwv.com: 1
  xkcfiyrjezauas.com: 1
 extended:
  ##.torrentvoting
  ###output
  ###rightbar > center
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
limetorrents.ninjaproxy1.com##[href^="https://gamestoday.org/"]
```

@ryanbr
