### ISSUE TITLE
ebay.com: breakage

### ISSUE THREAD

**Issue by Redroadsl** [uBlockOrigin/uAssets#24717]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ebay.com/sch/i.html?_from=R40&_nkw=Berlin+Wall&_sacat=0`

### Category

breakage

### Description

Good list on eBay search page was removed by uBlock after a while when page was loaded.
Everything was ok without uBlock.

### Other extensions used

tampermonkey(with no script installed)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-02 at 01-01-25 Berlin Wall for sale eBay](https://github.com/user-attachments/assets/c607f7a8-8b2d-4294-8e85-e72f26a46efc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 168913
 cosmetic: 58392
 scriptlet: 20818
 html: 1897
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39568-118, 8m
  ublock-badware: 10052-1, 8m
  ublock-privacy: 1043-4, 8m
  ublock-unbreak: 2475-1, 8m
  ublock-quick-fixes: 155-2, 8m
  easylist: 87658-170, 8m
  easyprivacy: 53021-62, 8m
  urlhaus-1: 28880-0, 8m
  plowe-0: 3548-989, 8m
  CHN-0: 25320-198, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5803 ms
 maxAssetCacheWait: 71 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  ebay.com: 5
  ebaystatic.com: 1
  perfdrive.com: 2
 extended:
  ##div[title="ADVERTISEMENT"]
  ##li.s-item:has(span[role="text"]>span:has-text(助))
```
</details>

**Comment by JobcenterTycoon** [comment]
Does `ebay.com#@?#li.s-item:-abp-has(span[role="text"]>span:-abp-contains(助))` works?

**Comment by Redroadsl** [comment]
It worked after I added it to uBlock settings.
but originally doesn't work.

**Comment by JobcenterTycoon** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
@Redroadsl Are you logged in?

**Comment by Yuki2718** [comment]
I can't reproduce, but the rule is from EL China @cjx82630

**Comment by Redroadsl** [comment]
> @Redroadsl Are you logged in?

Yes.
