### ISSUE TITLE
canva.com: breakage

### ISSUE THREAD

**Issue by mcwick002** [uBlockOrigin/uAssets#24713]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.canva.com/`

### Category

breakage

### Description

when ublock is turned on, canva and youtube breaks.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-01 183730](https://github.com/user-attachments/assets/5d20e332-e670-46d6-aaf6-40a289113d58)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 128
filterset (summary):
 network: 154773
 cosmetic: 47707
 scriptlet: 21971
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 87656-556, now
  easyprivacy: 53020-641, now
  plowe-0: 3548-0, now
  ublock-badware: 10050-1, now
  ublock-filters: 39435-273, now
  ublock-privacy: 1048-2, now
  ublock-quick-fixes: 138-0, now
  ublock-unbreak: 2416-0, now
  urlhaus-1: 28765-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 157 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
are you using canary ?

duplicate https://github.com/uBlockOrigin/uAssets/issues/24666

**Comment by mcwick002** [comment]
no edge

**Comment by mcwick002** [comment]
and also it always happens when i go to canva and youtube, the only way i could fix it was disable it and use another adblocker

**Comment by mapx-** [comment]
What exactly is your browser (and complete version) ?

**Comment by mcwick002** [comment]
sorry i just replied but Microsoft Edge
Version 128.0.2739.5 (Official build) dev (64-bit)
