### ISSUE TITLE
dnevnik.hr: breakage

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#24725]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dnevnik.hr/video/vlada-na-godisnjem---62876683`

### Category

breakage

### Description

Videos don't work until you accept cookies in cookie pop-up. Cookie pop-up is blocked with _uBlock filters – Cookie Notices_ filter.

_AdGuard – Cookie Notices_ doesn't block cookie pop-up, but the videos work after accepting cookies.

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With _uBlock filters – Cookie Notices_ filter active (no cookie pop-up, no video):
![Screenshot_1](https://github.com/user-attachments/assets/197bee3b-fff7-4bdf-8a78-e3bf65e1a936)

With _AdGuard – Cookie Notices_ filter active (cookie pop-up present, video works after accepting it):
![Screenshot_2](https://github.com/user-attachments/assets/f777837e-da3a-49fd-a55a-76e3be5630ad)
![Screenshot_3](https://github.com/user-attachments/assets/054e818a-3a1f-4f9f-8d4b-d989e36e9470)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 262626
 cosmetic: 225093
 scriptlet: 52292
 html: 2157
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-91, now
  adguard-generic: 83944-8943, now
  adguard-spyware-url: 1615-123, now
  adguard-spyware: 83691-26070, now
  curben-phishing: 506-2, now
  ublock-cookies-adguard: 1284-0, 4m
  fanboy-cookiemonster: 51451-271, now
  ublock-cookies-easylist: 1284-1284, now
  adguard-social: 23227-57, now
  fanboy-social: 16018-742, now
  adguard-popup-overlays: 27636-1105, now
  adguard-mobile-app-banners: 5378-27, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  ublock-filters: 39577-118, now
  ublock-badware: 10108-74, now
  ublock-privacy: 1044-17, now
  ublock-unbreak: 2480-2, now
  ublock-quick-fixes: 155-2, now
  easylist: 87720-23200, now
  easyprivacy: 53043-40532, now
  urlhaus-1: 29150-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 243 ms (selfie)
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  cloudflare.com: 15
  contentexchange.me: 1
  dotmetrics.net: 1
  facebook.net: 1
  gemius.pl: 1
  linker.hr: 1
  privacy-center.org: 1
  upscore.com: 3
 extended:
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##.share-article
  ##.article__social
  ##.share-side
  ##.share-label
  ##.footer__social
  ##.in-social
  ###fb-root:not(body):not(html)
  ##html:style(overflow:auto!important)
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr For ELC

```adb
@@||sdk.privacy-center.org^$script,domain=dnevnik.hr
```

**Comment by Marko-98** [comment]
Cookie notice started appearing. 

<img width="2559" height="1385" alt="Image" src="https://github.com/user-attachments/assets/130e4562-500f-4484-b26e-e8e769165b54" />
