### ISSUE TITLE
pagesix.com: detection

### ISSUE THREAD

**Issue by 3052** [uBlockOrigin/uAssets#24721]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pagesix.com/2022/01/27/fans-think-suki-waterhouse-shaded-ex-bradley-cooper-on-tiktok/`

### Category

detection

### Description

This site is supported by our trusted ad partners. Please consider disabling your adblocker to help support Page Six and our valuable content. Thank you!

### Other extensions used

!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 121
filterset (summary):
 network: 154877
 cosmetic: 47603
 scriptlet: 20506
 html: 1887
listset (total-discarded, last-updated):
 default:
  user-filters: 17-0, never
  ublock-filters: 39486-118, now
  ublock-badware: 10065-1, now
  ublock-privacy: 1043-4, now
  ublock-unbreak: 2475-1, now
  ublock-quick-fixes: 155-2, now
  easylist: 87717-172, now
  easyprivacy: 53027-65, now
  urlhaus-1: 28845-0, now
  plowe-0: 3548-989, now
filterset (user): [array of 34 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 added: [array of 140 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11257 ms (selfie)
 maxAssetCacheWait: 7127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 80
 network:
  pagesix.com: 2
  3lift.com: 1
  adlightning.com: 1
  adnxs.com: 1
  amazon-adsystem.com: 1
  bidswitch.net: 1
  bounceexchange.com: 1
  casalemedia.com: 1
  cloudflare.com: 1
  criteo.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 2
  id5-sync.com: 1
  kargo.com: 1
  liadm.com: 6
  media.net: 2
  metajaws.com: 2
  onetrust.com: 1
  optimizely.com: 2
  outbrain.com: 1
  p-n.io: 1
  p7cloud.net: 1
  permutive.app: 1
  privacymanager.io: 1
  qsearch-a.akamaihd.net: 1
  rubiconproject.com: 4
  sail-horizon.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
  speedcurve.com: 1
  spot.im: 2
  spotifycdn.com: 24
  succeedscene.com: 1
  the-ozone-project.com: 1
  wp.com: 2
  yahoo.com: 4
  zergnet.com: 1
  zqtk.net: 1
 extended:
  ##.billboard-overlay
  ##div[id^="zergnet-widget"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.ad--container
  ##.ad__wrapper
  ##.ad__placeholder
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.dfp-ad
  ##.ad-wrapper
  ##.single__outbrain
  ##.zergnet-widget
  ##.ad__label
  #@#.recirc
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-slot
  ##+js(json-prune, dataLayer.trackingId user.trackingId)
  ##+js(remove-cookie, blaize_tracking_id)
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
```
</details>

**Comment by Yuki2718** [comment]
@pgl
