### ISSUE TITLE
foxnews.com: ads

### ISSUE THREAD

**Issue by undeference** [uBlockOrigin/uAssets#24720]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.foxnews.com/politics/white-house-announces-new-defensive-military-deployments-aide-israel-against-iran-proxies`

### Category

ads

### Description

Within the comments (ew, why?!) there are plenty of blank spaces where ads are supposed to be. I cannot create cosmetic filters to remove them.

### Other extensions used

nothing relevant

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-02 at 04-07-03 White House announces new defensive deployments to help Israel Fox News](https://github.com/user-attachments/assets/9a481287-72a4-48c4-9cc2-a0026a5684e7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 101526
 cosmetic: 13364
 scriptlet: 21198
 html: 1906
listset (total-discarded, last-updated):
 removed:
  easylist: null
  plowe-0: null
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1105-0, now
  ISR-0: 1898-3, now
 default:
  user-filters: 36-0, never
  ublock-filters: 39568-118, now
  ublock-badware: 10065-1, now
  ublock-privacy: 1043-4, now
  ublock-unbreak: 2475-1, now
  ublock-quick-fixes: 155-2, now
  easyprivacy: 53027-50, now
  urlhaus-1: 28845-0, now
filterset (user): [array of 36 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1135 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1631
 network:
  foxnews.com: 3
  adsrvr.org: 3
  amazon-adsystem.com: 5
  amp.akamaized.net: 2
  appboycdn.com: 7
  aswpsdkus.com: 6
  atp.fox: 4
  bidswitch.net: 1
  bing.com: 1
  browser-intake-datadoghq.com: 3
  chartbeat.com: 2
  criteo.net: 1
  datadoghq-browser-agent.com: 1
  demdex.net: 11
  doubleclick.net: 7
  geoedge.be: 3
  google.com: 5
  googlesyndication.com: 3
  googletagmanager.com: 2
  h-cdn.com: 2
  imrworldwide.com: 2
  knotch-cdn.com: 1
  omtrdc.net: 49
  outbrain.com: 1
  pix.pub: 1
  pubmatic.com: 1
  scorecardresearch.com: 3
  spot.im: 1497
  streamrail.com: 3
  taplytics.com: 1
 extended:
  ##.site-header:style(min-height: 90px !important)
  ##+js(set-constant, Taplytics, {})
  ##+js(set-constant, Taplytics.featureFlagEnabled, noopFunc)
  ##+js(set-constant, Taplytics.runningExperiments, noopFunc)
  ##+js(remove-attr, class, div[class*="gated-overlay"])
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##+js(xml-prune, VAST, , adnxs)
  ##+js(xml-prune, VAST, , barstoolsports.com)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
