### ISSUE TITLE
flickr.com: breakage

### ISSUE THREAD

**Issue by random844** [uBlockOrigin/uAssets#24724]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.flickr.com/explore`

### Category

breakage

### Description

When entering any photos' detail, it's ok. After coming "back" either by a button or browser function, there is no way to enter another photos. It appears like there are no hypertexts anymore.

### Other extensions used

Facebook Container
I don't care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 160444
 cosmetic: 154329
 scriptlet: 27080
 html: 1899
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30674-44, 37m
  ublock-cookies-adguard: 1284-14, 37m
  fanboy-cookiemonster: 51451-3940, 37m
  ublock-cookies-easylist: 1284-1284, 37m
  adguard-social: 23227-52, 37m
  fanboy-social: 16018-738, 37m
  fanboy-thirdparty_social: 68-19, 37m
 default:
  user-filters: 0-0, never
  ublock-filters: 39576-118, 4m
  ublock-badware: 10108-1, 4m
  ublock-privacy: 1044-4, 4m
  ublock-unbreak: 2480-1, 4m
  ublock-quick-fixes: 155-2, 4m
  easylist: 87720-172, 4m
  easyprivacy: 53043-64, 4m
  urlhaus-1: 28845-0, 37m
  plowe-0: 3548-990, 37m
  CZE-0: 839-13, 37m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1270 ms (selfie)
 maxAssetCacheWait: 128 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  flickr.com: 4
  consensu.org: 1
  siftscience.com: 1
  staticflickr.com: 1
  trustarc.com: 1
 extended:
  ##.share-icon
  ##.foot-social
  ###consent_blackbar
  ##section:has([href*="istockphoto.com"])
  ##div[class^="main view"]:has(a[href$="&ref=sponsored"])
  ##+js(set-constant, appContext.adManager.context.current.adFrien…
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults (filter lists / settings), disable all other extensions, test again

**Comment by Yuki2718** [comment]
Neither could I.
