### ISSUE TITLE
uBlockOrigin will not create permanent block to greenmedinfo.com popup banner

### ISSUE THREAD

**Issue by JohnDohe** [uBlockOrigin/uAssets#24727]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://greenmedinfo.com/content/militarization-public-health-dr-hotezs-controversial-call-arms
```

### Description

Everytime I go to this site for the first time, a large banner pops up 
along the bottom: see 
<img width="1265" alt="GreenMed banner will not create block of popup" src="https://github.com/user-attachments/assets/7124ce18-0770-43a3-938e-6904ef6e1ffa">

I try to create a permanent block to it, but it will not work!
Try, try, try and the popup banner stays there.

However, when I choose to zap it, this works to clear the popup banner.
But when I return to the website again after closing it, there is the popup again.

What to do?

### Other extensions used

Please see these screenshots:

<img width="337" alt="uBlockOrigin-other extensions in use-3" src="https://github.com/user-attachments/assets/8175f445-6d28-4736-8dc7-7673ca7d22ab">

<img width="330" alt="uBlockOrigin-other extensions in use-2" src="https://github.com/user-attachments/assets/9512f4ab-d171-4993-954c-81b3d7892bb4">

<img width="340" alt="uBlockOrigin-other extensions in use-1" src="https://github.com/user-attachments/assets/8f0ea940-a796-49b3-ad11-b03c5fd47d38">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 155302
 cosmetic: 47766
 scriptlet: 20541
 html: 1899
listset (total-discarded, last-updated):
 default:
  user-filters: 236-49, never
  ublock-filters: 39577-118, 55m Δ
  ublock-badware: 10108-1, 55m Δ
  ublock-privacy: 1044-4, 55m Δ
  ublock-unbreak: 2480-1, 55m Δ
  ublock-quick-fixes: 155-2, 55m Δ
  easylist: 87720-172, 55m Δ
  easyprivacy: 53043-64, 55m Δ
  urlhaus-1: 29150-0, 55m
  plowe-0: 3548-989, 2d.20h.26m
filterset (user): [array of 236 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 495 ms (selfie)
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
enable EasyList/uBO – Cookie Notices

or add

`/cookies-message.min.js`

**Comment by JohnDohe** [comment]
Hi!

Thank you so much!

However, I'm not a "techie" . . .

Can you provide with more detailed instructions on how to implement
your solution?

Thanks!
CONFIDENTIALITY NOTICE- This email and any files transmitted with it are
intended solely for the use of the individual or entity to which they are
addressed and may contain confidential and or privileged material. Any
review, retransmission, dissemination or other use of, or taking of any
action in reliance upon, this information by persons or entities other than
the intended recipient is prohibited. If you have received this e-mail in
error, please contact the sender and delete the material from your
computer. Please note that any view or opinions presented in this e-mail
are solely those of the author and do not necessarily represent those of
any individual, entity or Corporation and/or affiliates. Finally, the
recipient should check this e-mail and any attachments for the presence of
viruses. The individual, entity and/or Corporation accepts no liability for
any damage caused by any virus transmitted by this email. © Copyright
2024.  All rights reserved.
***********************************************************************************************************

**Comment by mapx-** [comment]
- click uBO icon, click the last icon on the right at the bottom ("open the dashboard")
- go to `filter lists` tab
- find `cookie notices` section
- enable `EasyList/uBO – Cookie Notices`
- click `apply changes`

**Comment by JohnDohe** [comment]
Hi!

Thank you!

How to . . .

*add*

*/cookies-message.min.js*
CONFIDENTIALITY NOTICE- This email and any files transmitted with it are
intended solely for the use of the individual or entity to which they are
addressed and may contain confidential and or privileged material. Any
review, retransmission, dissemination or other use of, or taking of any
action in reliance upon, this information by persons or entities other than
the intended recipient is prohibited. If you have received this e-mail in
error, please contact the sender and delete the material from your
computer. Please note that any view or opinions presented in this e-mail
are solely those of the author and do not necessarily represent those of
any individual, entity or Corporation and/or affiliates. Finally, the
recipient should check this e-mail and any attachments for the presence of
viruses. The individual, entity and/or Corporation accepts no liability for
any damage caused by any virus transmitted by this email. © Copyright
2024.  All rights reserved.
***********************************************************************************************************

**Comment by mapx-** [comment]
as above, go to "my filters" tab, add 
`/cookies-message.min.js`

click `apply changes`

**Comment by JohnDohe** [comment]
Hi!

Like this:

[image: image.png]

?
CONFIDENTIALITY NOTICE- This email and any files transmitted with it are
intended solely for the use of the individual or entity to which they are
addressed and may contain confidential and or privileged material. Any
review, retransmission, dissemination or other use of, or taking of any
action in reliance upon, this information by persons or entities other than
the intended recipient is prohibited. If you have received this e-mail in
error, please contact the sender and delete the material from your
computer. Please note that any view or opinions presented in this e-mail
are solely those of the author and do not necessarily represent those of
any individual, entity or Corporation and/or affiliates. Finally, the
recipient should check this e-mail and any attachments for the presence of
viruses. The individual, entity and/or Corporation accepts no liability for
any damage caused by any virus transmitted by this email. © Copyright
2024.  All rights reserved.
***********************************************************************************************************

**Comment by mapx-** [comment]
- do not reply via email
- however you can read wiki
https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters
