### ISSUE TITLE
streamruby.com: detection

### ISSUE THREAD

**Issue by rANdecHo** [uBlockOrigin/uAssets#24735]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://streamruby.com/dyue1dlzbxvq
```

### Description

Both uBO and AdGuard are being detected. A 'Disable console!' message pops up, and then I'm redirected to google.com. If I try to click the back button, the message keeps spamming indefinitely until I close the tab. This issue started occurring with both uBO and AdGuard today, which is why I'm mentioning both.

There is also a very high chance of encountering malware or phishing if uBO is turned off. After I disabled it and clicked on 'Play,' the domain `vibehatpin.click` opened up. This domain is not blocked by uBO btw. and redirected me to Amazon, which seems very suspicious. Therefore, you'll likely find many blockable domains.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 250800
 cosmetic: 257351
 scriptlet: 55137
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83951-7485, 4h.37m
  adguard-mobile: 9633-105, 4h.37m
  adguard-spyware-url: 1616-123, 4h.37m
  adguard-spyware: 83693-30980, 4h.37m
  block-lan: 70-0, 4h.37m
  curben-phishing: 506-0, 4h.37m
  adguard-cookies: 30686-92, 4h.37m
  ublock-cookies-adguard: 1284-0, 4h.37m
  fanboy-cookiemonster: 51451-4013, 4h.37m
  ublock-cookies-easylist: 1284-1284, 4h.37m
  adguard-social: 23230-1658, 4h.37m
  fanboy-social: 16022-28, 4h.37m
  [12 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39454-114, 2m Δ
  ublock-badware: 10114-20, 2m Δ
  ublock-privacy: 1049-8, 2m Δ
  ublock-unbreak: 2421-1, 2m Δ
  ublock-quick-fixes: 151-15, 2m Δ
  easylist: 87733-153, 2m Δ
  easyprivacy: 53053-192, 2m Δ
  urlhaus-1: 29150-0, 4h.38m
  plowe-0: 3548-1064, 1d.10h.56m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 233 ms (selfie)
 maxAssetCacheWait: 68 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  streamruby.com: 2
  b194c1c862.com: 1
  branleranger.com: 1
  cloudflareinsights.com: 1
  google.com: 1
  googletagmanager.com: 1
  wpadmngr.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Don't remove the troubleshooting information. Open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by stephenhawk8054** [comment]
Report to https://github.com/easylist/easylist/issues

And please respect the prerequisites before reporting:

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
