### ISSUE TITLE
kickstarter.com: breakage

### ISSUE THREAD

**Issue by DiscworldDeath** [uBlockOrigin/uAssets#24733]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kickstarter.com/profile/2074786394`

### Category

breakage

### Description

The "follow" button on creators' profiles does not appear with uBO enbled, and appears with it disabled, or when disabling cosmetic filtering.

### Other extensions used

Reddit Enhancement Suite
Old Reddit Redirect
Augmented Steam
Is there any deal.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/aec9ec5b-bd4c-4d5d-87d6-47b1552425b0)
![image](https://github.com/user-attachments/assets/b7e11222-add0-459b-8914-dfdd4c5fae8b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 184528
 cosmetic: 214376
 scriptlet: 49134
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81180-4420, now
  adguard-generic: 83910-6398, now
  adguard-spyware-url: 1616-6, now
  block-lan: 70-0, now
  fanboy-cookiemonster: 51451-189, now
  fanboy-social: 16062-1, now
 default:
  user-filters: 4-0, never
  easylist: 87733-559, now
  easyprivacy: 53053-648, now
  plowe-0: 3547-0, now
  ublock-badware: 10134-1, now
  ublock-filters: 39454-285, now
  ublock-privacy: 1049-119, now
  ublock-quick-fixes: 151-0, now
  ublock-unbreak: 2421-1, now
  urlhaus-1: 29150-0, 1h.46m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1106 ms
 maxAssetCacheWait: 429 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 no-cosmetic-filtering: true
 network:
  kickstarter.com: 1
  facebook.net: 1
  googletagmanager.com: 2
  siftscience.com: 1
  transcend-cdn.com: 1
 extended:
  ##.section_footer-social-links
  ##.js-follow-user
  ###react-consent-modal
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(set-cookie, twtr_pixel_opt_in, N)
```
</details>

**Comment by mapx-** [comment]
add

`kickstarter.com#@#.js-follow-user`

**Comment by DiscworldDeath** [comment]
It's more that they send you email notifications when these people start new campaigns that makes it useful.
