### ISSUE TITLE
163.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2473]
### URL(s) where the issue occurs

```
http://163.com/
```

### Describe the issue

Popups / Popads and possibly othrr missed ads.

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default.

**Comment by gorhill** [comment]
Report to Chinese filter list maintainers please.

**Comment by C0nw0nk** [comment]
@gorhill who are they ? Can i do @ them in a comment here ?

**Comment by gorhill** [comment]
Click the "home" icon aside any of the Chinese filter lists in the "Filter lists" pane in the dashboard. It's best that filter issue specific to a language are taken care of by lists for that language.
