### ISSUE TITLE
tvaplus.ca: detection

### ISSUE THREAD

**Issue by Albert9999** [uBlockOrigin/uAssets#24730]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tvaplus.ca/tva/sucre-sale/saison-23/episode-1763-64467767`

### Category

detection

### Description

Website shows a message saying ad block was detected and must be disabled to view content

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![AD-BLOCK](https://github.com/user-attachments/assets/a2b2469c-51d2-4833-b4e6-0040605f1ec1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 127
filterset (summary):
 network: 155301
 cosmetic: 47732
 scriptlet: 21984
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39454-114, 6m
  ublock-badware: 10114-1, 6m
  ublock-privacy: 1049-2, 6m
  ublock-unbreak: 2421-1, 6m
  ublock-quick-fixes: 151-15, 6m
  easylist: 87727-557, 6m
  easyprivacy: 53045-798, 6m
  urlhaus-1: 29150-0, 6m
  plowe-0: 3547-0, 6m
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 396 ms (selfie)
 maxAssetCacheWait: 264 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  brightcove.com: 8
  chartbeat.com: 1
  cxense.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/26071

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/93d7e142fdedfcc8d7d96087750729233659ead9

**Comment by stephenhawk8054** [comment]
@mapx- I think redirection is enough?

```adb
||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,domain=tvaplus.ca,redirect=google-ima.js,important
||rubiconproject.com^$script,redirect=noopjs,domain=tvaplus.ca
```

**Comment by mapx-** [comment]
yes, it's working fine

**Comment by et-the-extra-terrestrial** [comment]
The problem is still there.

**Comment by stephenhawk8054** [comment]
Backup your uBO configuration, reset uBO to default settings, open new tab and test again.

**Comment by et-the-extra-terrestrial** [comment]
The problem is present on different devices and networks.

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Video plays fine for me

![image](https://github.com/user-attachments/assets/9a906559-b350-4300-99b9-2c30d8ed6cdc)

**Comment by et-the-extra-terrestrial** [comment]
The issue happens on my Android phone, my laptop and my computer and work, all using Firefox. Phone runs under a VPN, but that isn't the case for the work computer.

I am in Canada. I don't know if the website detects the ad block only for Canadian users or if it's specific to Firefox.

![Screenshot_20241225-233846](https://github.com/user-attachments/assets/cdaac459-e6af-4047-84f0-ed180f187ea4)

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO?

**Comment by et-the-extra-terrestrial** [comment]
The same message happens. It seems to be blocking Firefox then, I guess!

**Comment by stephenhawk8054** [comment]
Turn off Firefox Enhanced Tracking Prevention and test again.

And please respect the prerequisites:

> - [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin

**Comment by et-the-extra-terrestrial** [comment]
Turning off Firefox enhanced tracking prevention solved the issue.

**Comment by stephenhawk8054** [comment]
You didn't even bother to read any of prerequisites

> - [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
