### ISSUE TITLE
[nsfw] streamkiste.tv: detection  

### ISSUE THREAD

**Issue by themalwarehunter77** [uBlockOrigin/uAssets#24745]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://streamkiste.tv/movie/atomic-reporter-1990-0102784`

### Category

detection

### Description

with voe.sx hoster it still detect it i have updated all filters
![grafik](https://github.com/user-attachments/assets/971aea6b-91e8-49b0-b734-30ec917702cc)

### Other extensions used

no 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 157250
 cosmetic: 52766
 scriptlet: 20543
 html: 1900
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39611-118, 4m
  ublock-badware: 10179-1, 4m
  ublock-privacy: 1044-4, 4m
  ublock-unbreak: 2510-1, 4m
  ublock-quick-fixes: 150-15, 4m
  easylist: 87758-172, 4m
  easyprivacy: 53057-65, 4m Δ
  urlhaus-1: 28645-0, now
  plowe-0: 3547-988, 4m
  DEU-0: 7518-37, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 601 ms
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  streamkiste.tv: 3
  ads-twitter.com: 2
  antiadblocksystems.com: 1
  d3cod80thn7qnd.cloudfront.net: 1
  imasdk.googleapis.com: 2
  suozmtcc.com: 1
  zombyfairfax.com: 1
```
</details>

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uAssets/issues/24744#issuecomment-2267074386

**Comment by D4niloMR** [comment]
You can temporarily add

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect=google-ima.js,domain=alleneconomicmatter.com,important
alleneconomicmatter.com##+js(nowoif)
alleneconomicmatter.com##+js(set, console.clear, undefined)
```

**Comment by themalwarehunter77** [comment]
> You can temporarily add
> 
> ```
> ||imasdk.googleapis.com/js/sdkloader/ima3.js$script,3p,redirect=google-ima.js,domain=alleneconomicmatter.com,important
> alleneconomicmatter.com##+js(nowoif)
> alleneconomicmatter.com##+js(set, console.clear, undefined)
> ```

how can i find out the current voe.sx domain because they change it all the time?

**Comment by D4niloMR** [comment]
> how can i find out the current voe.sx domain because they change it all the time?

shift right click the voe iframe => click "this frame" => click "open frame in new tab"
