### ISSUE TITLE
[NSFW] femefun.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2474]
### URL(s) where the issue occurs

```
https://femefun.com/videos/38051/lick-my-pussy-i-ll-suck-your-dick-clamping-her-legs-together-to-give-his-cock-a-tight-fit-inside-her-pussy/
```

### Describe the issue

Push notifications and possibly other missed ads. Some hilltopads advertisement codes on site.

### Screenshot(s)

![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40961982-20b06e04-689c-11e8-8d57-ab2e31330563.jpg)

### Versions

- Browser/version: Firefox Quantum Latest
- uBlock Origin version: Latest

### Settings

Default.

**Comment by C0nw0nk** [comment]
@mapx- @okiehsch 

Femefun popup ads and redirects now.

**Comment by mapx-** [comment]
I cannot reproduce the popups.
Try
`femefun.com##+js(abort-current-inline-script.js, Math, zfgloaded)`

**Comment by C0nw0nk** [comment]
@mapx-  that code works.

**Comment by C0nw0nk** [comment]
@mapx-  another website same code required as above.
```
pervertslut.com##+js(abort-current-inline-script.js, Math, zfgloaded)
```
