### ISSUE TITLE
pinterest.co.uk: detection

### ISSUE THREAD

**Issue by foyiwae** [uBlockOrigin/uAssets#24747]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pinterest.co.uk/`

### Category

detection

### Description

![image](https://github.com/user-attachments/assets/3646ba1b-fc76-4e3c-8254-7923df3386de)
This pop up occurs on pinterest when trying to access

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/76210bec-338d-4bf0-8c50-afc5ffe415e1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 154916
 cosmetic: 47664
 scriptlet: 20546
 html: 1900
listset (total-discarded, last-updated):
 default:
  user-filters: 21-1, never
  ublock-filters: 39614-118, now
  ublock-badware: 10179-1, now
  ublock-privacy: 1044-4, now
  ublock-unbreak: 2511-1, now
  ublock-quick-fixes: 150-15, now
  easylist: 87775-172, now
  easyprivacy: 53058-65, now
  urlhaus-1: 28645-0, now
  plowe-0: 3547-988, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 573 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  pinterest.co.uk: 1
 extended:
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to log in to reproduce the issue?

**Comment by foyiwae** [comment]
Yes, I do not have any problems when I'm logged out of pinterest, the problem arises when I'm logged in.

**Comment by Yuki2718** [comment]
Does it happen on every login? What if you add `pinterest.*#@#+js(json-prune, resource_response.data.[-].pin_promotion_id)` to  My filters and refesh the page?
