### ISSUE TITLE
careersides.com: breakage

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#24743]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://careersides.com/the-history-and-invention-of-credit-cards/`

### Category

breakage

### Description

site - `https://publicearn.com/Opw0jXY8`
while using this site something unusual happens at the last page after clicking the button it starts again from first page

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium Mobile: 110
filterset (summary):
 network: 167885
 cosmetic: 216897
 scriptlet: 36773
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30686-92, now
  ublock-cookies-adguard: 1343-0, now
  fanboy-cookiemonster: 51454-4007, now
  ublock-cookies-easylist: 1343-1343, now
 default:
  user-filters: 32-4, never
  ublock-filters: 39923-873, 1h.33m Δ
  ublock-badware: 10171-2, 1h.33m Δ
  ublock-privacy: 1050-2, 1h.33m Δ
  ublock-unbreak: 2454-2, 1h.33m Δ
  ublock-quick-fixes: 149-1, 1h.33m Δ
  adguard-mobile: 9633-11, now
  easylist: 87758-697, 1h.33m Δ
  easyprivacy: 53057-789, 1h.33m Δ
  urlhaus-1: 28645-0, now
  plowe-0: 3547-83, now
filterset (user): [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1469 ms (selfie)
 maxAssetCacheWait: 296 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  clarity.ms: 1
  google.com: 1
  googlesyndication.com: 2
 extended:
  ###tp98, #btn6:style(display: block !important;)
  ##+js(set-constant, count, 0)
  ##+js(noeval-if, /chp_?ad/)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
Comment here next time: https://github.com/uBlockOrigin/uAssets/discussions/17361
