### ISSUE TITLE
alleneconomicmatter.com: detection

### ISSUE THREAD

**Issue by NBA2K1** [uBlockOrigin/uAssets#24744]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://alleneconomicmatter.com/imtlropifyzg`

### Category

detection

### Description

One of voe.sx 's many domains. They change it very frequently. I know that the fix for it is this:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=alleneconomicmatter.com
alleneconomicmatter.com##+js(nowoif)`

But every time VOE decides to change their domain name again, I have to add another rule with the changed domain name.
Is there a "permanent fix" for this problem?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/1ff73981-9ccd-4daa-92b0-e60c569165e4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 174212
 cosmetic: 202932
 scriptlet: 36030
 html: 2158
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81182-3925, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 0-0, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2658-0, 38m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2108-6, 38m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/antipaywall_filters_without_element_hiding.txt: 252-95, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 100189-71285, now
  adguard-spyware-url: 1616-239, now
  curben-phishing: 618-3, 38m
  fanboy-cookiemonster: 51454-126, now
  fanboy-thirdparty_social: 68-16, now
  ublock-annoyances: 5930-212, 31m Δ
  DEU-0: 7518-43, 38m
  [1 lists not shown]: [too many]
 default:
  user-filters: 44-0, never
  ublock-filters: 39611-462, 31m Δ
  ublock-badware: 10179-1, 31m Δ
  ublock-privacy: 1044-54, 31m Δ
  ublock-unbreak: 2510-6, 31m Δ
  ublock-quick-fixes: 150-15, 31m Δ
  easylist: 87758-260, 31m Δ
  easyprivacy: 53057-243, 31m Δ
  urlhaus-1: 28645-0, 38m
  plowe-0: 3547-989, now
filterset (user): [array of 44 redacted]
trustedset:
 added: [array of 70 redacted]
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 568 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 335 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  ads-twitter.com: 2
  imasdk.googleapis.com: 2
  sharethis.com: 2
  zombyfairfax.com: 1
 extended:
  ##.sharethis-inline-share-buttons
```
</details>

**Comment by mapx-** [comment]
already fixed https://github.com/uBlockOrigin/uAssets/commit/d1edc08f30687fc1ab2331e8a1bc251975283d1d

**Comment by NBA2K1** [comment]
Ah, thanks. I've updated ublock and searched through the open issues and couldn't find it, so I opened this issue. Sry for any inconvenience
