### ISSUE TITLE
techedubyte.com: detection

### ISSUE THREAD

**Issue by nlsnmlna** [uBlockOrigin/uAssets#24751]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.techedubyte.com/get-free-warp-plus-unlimited-data-key-apk/`

### Category

detection

### Description

website detection adblock

### Other extensions used

![image](https://github.com/user-attachments/assets/75d99fa1-e022-4a44-8442-435887296423)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 258453
 cosmetic: 262746
 scriptlet: 53965
 html: 2158
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8831-0, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 207-0, now
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 2328-24, now
  https://filters.adtidy.org/windows/filters/17.txt: 1620-6, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2658-154, 1m
  https://raw.githubusercontent.com/rokibhasansagar/AAK-Cont-fork/master/dist/aak-cont-list-ubo.txt: 2194-23, 1m
  adguard-generic: 83892-5248, now
  adguard-spyware-url: 1616-1615, now
  adguard-spyware: 83693-153, now
  block-lan: 70-0, now
  curben-phishing: 451-3, never
  adguard-social: 23230-56, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 56-0, never
  ublock-filters: 39616-265, 36m Δ
  ublock-badware: 10179-2, 36m Δ
  ublock-privacy: 1044-411, 36m Δ
  ublock-unbreak: 2511-67, 36m Δ
  ublock-quick-fixes: 150-15, 36m Δ
  easylist: 87775-2323, 36m Δ
  easyprivacy: 53058-30347, 36m Δ
  urlhaus-1: 28945-0, now
  plowe-0: 3547-1432, now
filterset (user): [array of 66 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5495 ms
 maxAssetCacheWait: 2387 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  techedubyte.com: 1
  doubleclick.net: 1
  google.com: 5
  googletagmanager.com: 2
 extended:
  ##.gmr-banner-insidecontent
  ##.gmr-floatbanner
  ##div[style*="box-shadow: rgb(136, 136, 136) 0px 0px 12px; color…
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##iframe[name="googlefcPresent"]
  ##.gmr-floatbanner-left
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
  ##.gmr-floatbanner-right
  ##.gmr-topbanner
  ##.content-share
  ##.gmr-banner-beforecontent
  ##.gmr-banner-aftercontent
  ##.gmr-banner-afterrelpost
  ##.gmr-footerbanner
  ##+js(noeval-if, /chp_?ad/)
  ##+js(addEventListener-defuser, load, [native code])
  ##+js(addEventListener-defuser, DOMContentLoaded, document.docum…
  ##+js(set-constant, checkAdsStatus, noopFunc)
  ##+js(noeval-if, deblocker)
  ##+js(prevent-fetch, googlesyndication)
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
```
</details>

**Comment by stephenhawk8054** [comment]
Comment original URL here: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by punisher018** [comment]
while looking at the page I saw that when I press the downloads button to download the contents of the page itself (not as a shortener) it doesn't work.

`https://www.techedubyte.com/url-ott-navigator-terbaru/`

**Comment by BlazeFTL** [comment]
Use As Custom Filters
```
techedubyte.com###gmr-popupwrap
techedubyte.com##+js(nano-sib, r, *)
techedubyte.com#@#+js(addEventListener-defuser, load, [native code])
@@||static.doubleclick.net/instream/ad_status.js$xhr,domain=techedubyte.com
