### ISSUE TITLE
https://stfly.xyz/62XJj: detection

### ISSUE THREAD

**Issue by PeterGlitch** [uBlockOrigin/uAssets#24758]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

https://stfly.xyz/62XJj

### Category

detection

### Description

I am being redirected to different websites from the initial website provided but i am unable to proceed since these websites are detecting an adblock.

### Other extensions used

Ghostery

### Screenshot(s)

![Screenshot_20240804_124548_Firefox](https://github.com/user-attachments/assets/6b2e16c2-a08d-4348-b2fa-1f27b1fb8739)
FIRST PAGE I AM ABLE TO CLICK PROCEED

![Screenshot_20240804_124554_Firefox](https://github.com/user-attachments/assets/d059d65d-8958-473d-9e96-63b0b96a2620)
SECOND PAGE LOADS

![Screenshot_20240804_124609_Firefox](https://github.com/user-attachments/assets/b9dbe4c8-7eec-4b58-9ae0-78f95e1a13a4)
ADBLOCK DETECTED ON SECOND PAGE BEFORE I CAN EVEN CLICK PROCEED.

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 128
filterset (summary):
 network: 156429
 cosmetic: 56019
 scriptlet: 20621
 html: 1899
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40070-120, now
  ublock-badware: 10217-1, now
  ublock-privacy: 1038-4, now
  ublock-unbreak: 2529-1, now
  adguard-mobile: 9633-74, now
  easylist: 87781-241, now
  easyprivacy: 53064-69, now
  urlhaus-1: 28680-0, now
  plowe-0: 3547-1062, now
  ublock-quick-fixes: 137-3, now
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3600 ms
 maxAssetCacheWait: 669 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  googlesyndication.com: 1
  netpub.media: 5
  pwpjducwoxnrty.com: 2
  zunsoach.com: 1
 extended:
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
```
</details>

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uAssets/issues/24739#issuecomment-2267414966
