### ISSUE TITLE
farmasave.it: breakage

### ISSUE THREAD

**Issue by rcorsari** [uBlockOrigin/uAssets#24752]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.farmasave.it
```

### Description

I'm using Firefox on pretty updated windows 10 latest version and updated with latest updates

On the e-commerce in subject, after having searched and found a product,
hovering on the product makes to appear a div with button "vai alla scheda"

this button is fundamental because it would open the product page and allow to add it to the shopping cart

If uBlock Origin is active clicking on "vai alla scheda" won't work
If deactivated it works

I use uBlock origin just installed with its default settings

### Other extensions used

- Save Open Tabs
- uBlock Origin
- WAVE Evaluation Tool (deactivated)
- AdBlocker for YouTube™ (deactivated)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![immagine](https://github.com/user-attachments/assets/19fdb5c2-0a96-4604-b00b-6cc56a6f1fb7)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 156976
 cosmetic: 54686
 scriptlet: 20550
 html: 1900
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39625-118, 30m Δ
  ublock-badware: 10189-1, 30m Δ
  ublock-privacy: 1044-4, 30m Δ
  ublock-unbreak: 2514-1, 30m Δ
  easylist: 87773-172, 30m Δ
  easyprivacy: 53063-65, 30m Δ
  urlhaus-1: 28945-0, 30m
  plowe-0: 3551-990, 9d.11h.52m
  ITA-0: 8815-38, 30m
  ublock-quick-fixes: 150-15, 30m Δ
filterset (user): [empty]
trustedset:
 added: [array of 36 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 354 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
add
`@@||sgtm.farmasave.it/$script,1p`

@ryanbr EP issue
`.js?id=gtm-`
