### ISSUE TITLE
truyenfull.io: ads

### ISSUE THREAD

**Issue by Jacques200** [uBlockOrigin/uAssets#24750]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://truyenfull.io/`

### Category

ads

### Description

Ads still appear while using extensions and even after element picker was used
![Screenshot_20240804-055648_Firefox](https://github.com/user-attachments/assets/45de671a-6fb9-4690-9d52-5c629ef08b2a)

### Other extensions used

Translate this Page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 128
filterset (summary):
 network: 156334
 cosmetic: 56016
 scriptlet: 20618
 html: 1901
listset (total-discarded, last-updated):
 default:
  user-filters: 13-2, never
  ublock-filters: 40062-120, 2m Δ
  ublock-badware: 10173-1, 2m Δ
  ublock-privacy: 1045-4, 2m Δ
  ublock-unbreak: 2514-1, 2m Δ
  ublock-quick-fixes: 151-15, 2m Δ
  adguard-mobile: 9633-75, now
  easylist: 87775-241, 2m Δ
  easyprivacy: 53058-73, 2m Δ
  urlhaus-1: 28645-0, 2m
  plowe-0: 3547-1062, now
filterset (user): [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6367 ms
 maxAssetCacheWait: 2255 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  truyenfull.io: 7
  admicro.vn: 4
  amcdn.vn: 1
  contineljs.com: 1
  googletagmanager.com: 2
  staticscdn.net: 1
 extended:
  ###header-ads
  ##.header-ads
  ##path:nth-of-type(2)
  ##.smf-close-button
  ##.smf-flyicon-btnclose-6667fa7f4680f1312c306f63
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `ABPVN List` and test again.

**Comment by Jacques200** [comment]
> Enable `ABPVN List` and test again.

It worked, thanks.
