### ISSUE TITLE
vbb.de: breakage

### ISSUE THREAD

**Issue by zedd-0** [uBlockOrigin/uAssets#24767]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vbb.de/fahrinfo/`

### Category

breakage

### Description

webside is blocked,
if 'ublock' is on and "EasyList – Cookie Notices" is used.

### Other extensions used

to much.
webside works if  'ublock' / "EasyList – Cookie Notices" is disabled
--> [x] have verified that other extensions are not causing the issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 223687
 cosmetic: 251543
 scriptlet: 47128
 html: 1946
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83969-514, now
  adguard-mobile: 9633-57, now
  curben-phishing: 487-3, now
  adguard-cookies: 30702-46, now
  ublock-cookies-adguard: 1304-20, now
  fanboy-cookiemonster: 51458-3941, now
  ublock-cookies-easylist: 1304-1304, now
  adguard-social: 23233-54, now
  fanboy-social: 16084-743, now
  ara-0: 2332-30, now
  CHN-0: 25333-233, now
  IND-0: 13459-50, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 357-2, never
  ublock-filters: 39642-3576, 1h.53m Δ
  ublock-badware: 10213-113, 1h.53m Δ
  ublock-privacy: 1038-4, 1h.53m Δ
  ublock-unbreak: 2527-86, 1h.53m Δ
  ublock-quick-fixes: 136-16, 1h.53m Δ
  easylist: 87784-2336, 1h.53m Δ
  easyprivacy: 53067-164, 1h.53m Δ
  urlhaus-1: 28650-0, now
  plowe-0: 3547-1078, now
  DEU-0: 7518-56, now
filterset (user): [array of 357 redacted]
trustedset:
 added: [array of 29 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 366 ms (selfie)
 maxAssetCacheWait: 165 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cookiebot.com: 1
  hacon.de: 3
```
</details>

**Comment by D4niloMR** [comment]
What is not working on the site?
