### ISSUE TITLE
dnews.dn.ua - Please block pop-up ads on the site

### ISSUE THREAD

**Issue by pilgrim92** [uBlockOrigin/uAssets#2476]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://dnews.dn.ua/`

### Describe the issue

At the entrance to the site does not block pop-up ads. Please make this advertisement in filters. In the manual filter (my filters), advertising is blocked if you add a link to the list `https://9dkcppyxhs.site/`

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Mozilla Firefox 52.0
- uBlock Origin version: uBlock Origin 1.13.8

### Settings

- Default

### Notes

In the manual filter (my filters), advertising is blocked if you add a link to the list `https://9dkcppyxhs.site/`

**Comment by gorhill** [comment]
I don't see a "popup ad". You are going to provide better details for others to reproduce.

**Comment by mapx-** [comment]
update your browser / uBo, then re-test

**Comment by uBlock-user** [comment]
I don't see any ads from the aformentioned ad domain but it does have a `piguiqproxy` anti adb script with a different domain to check and deface.

Try - `dnews.dn.ua##script:inject(abort-current-inline-script.js, atob, null)`

**Comment by gorhill** [comment]
> Try - `dnews.dn.ua##script:inject(abort-current-inline-script.js, atob, null)`

`null` is rather generic, for `piguiqproxy` the signature is the trailing comment:

    dnews.dn.ua##script:inject(abort-current-inline-script.js, atob, /\/\*\w{40}\*\/$/)

**Comment by uBlock-user** [comment]
`null` is only used with `atob` once, so I used that after checking the `inline-script.` It's a clone of `piguiqproxy` but with different domain(zmctrack.net), so I went with that.
