### ISSUE TITLE
lootdest.org: detection

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#24768]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lootdest.org/s?41e6ebbd&data=g6ssgedma%2BtLur0XLOCZKXISwzM00fZUALAxKzx5p8ECWmFBXd2SXu0EVUcB24Cg`

### Category

detection

### Description

detection

### Other extensions used

no comment (mostly non related to the website, my userscripts dosent have anything to do on that specific website except [the bypass all shortlinks debloated ](https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/)but I think the adblock detection prevents the bypassing)

I have to check all the tickboxes because github wont let me post this issue, I do have custom filters and other filters but they seem unrelated

### Screenshot(s)

![librewolf_hRxfVtk1MR](https://github.com/user-attachments/assets/b34cc7f0-1dd3-44bd-80d3-ae4377b59dd1)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 127
filterset (summary):
 network: 195674
 cosmetic: 139508
 scriptlet: 31643
 html: 2171
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51459-187, now
  ublock-cookies-easylist: 1304-4, now
  easylist-annoyances: 4671-42, now
  easylist-chat: 205-0, now
  easylist-newsletters: 7474-34, now
  easylist-notifications: 3124-164, now
  ublock-annoyances: 5929-80, 34m Δ
  CHN-0: 25335-200, now
  RUS-0: 40734-194, 34m Δ
 default:
  user-filters: 70-3, never
  ublock-filters: 39661-118, 34m Δ
  ublock-badware: 10213-1, 34m Δ
  ublock-privacy: 1039-4, 34m Δ
  ublock-unbreak: 2531-1, 34m Δ
  ublock-quick-fixes: 136-2, 34m Δ
  easylist: 87793-173, 34m Δ
  adguard-spyware-url: 1618-123, now
  easyprivacy: 53067-61, 34m Δ
  urlhaus-1: 28650-0, now
  curben-phishing: 487-3, now
  plowe-0: 3547-988, now
  LegitimateURLShortener: 2659-165, now
filterset (user): [array of 70 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 701 ms (selfie)
 maxAssetCacheWait: 196 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  taboola.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Comment in here: https://github.com/uBlockOrigin/uAssets/discussions/17361

Don't open new issues about shortener sites.
