### ISSUE TITLE
eurointegration.com.ua: ads

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#24781]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.eurointegration.com.ua/news/2024/08/5/7191539/`

### Category

ads

### Description

Open this link in a new tab https://www.eurointegration.com.ua/news/2024/08/5/7191539/
Wait 10 seconds and click on the tab, the empty space at the top is not hidden. You need clear cache after reload page.

Google Chrome 127.0.6533.89, uBO 1.59.0, uBOL 2024.8.5.925

### Other extensions used

**enhanced-h264ify
Keep One Pinned Tab**

### Screenshot(s)

<details>
<summary>Video uBO</summary>

https://github.com/user-attachments/assets/2f073484-f3d4-4a02-be65-81ecc5454252
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 148690
 cosmetic: 119250
 scriptlet: 30107
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 24586-243, 8m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1714-21, 8m
  adguard-cookies: 30723-36, 8m
  ublock-cookies-adguard: 1505-19, 8m
  ublock-annoyances: 5983-17, 23m Δ
 default:
  user-filters: 6-0, never
  ublock-filters: 39568-278, 23m Δ
  ublock-badware: 10217-1, 23m Δ
  ublock-privacy: 1044-10, 23m Δ
  ublock-unbreak: 2470-5, 23m Δ
  ublock-quick-fixes: 134-0, 23m Δ
  easylist: 87835-229, 23m Δ
  easyprivacy: 53073-342, 23m Δ
  RUS-0: 40726-247, 23m Δ
filterset (user): [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 308 ms (selfie)
 maxAssetCacheWait: 147 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  criteo.net: 2
  doubleclick.net: 2
  facebook.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  html-load.com: 3
  membrana.media: 1
  onthe.io: 2
 extended:
  ##.nts-ad
  ##.advtext
  ##.post__social
  ##.post__social__item
  ##.post__subscribe_bottom
  ##.top__social__item
  ##.news_divide-banner
  ##.unit_header-banner
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##.right_column_content > .block_news:style(margin-top: 0 !impor…
  ##header.header:style(margin-top: 0 !important)
  ##html:style(overflow:auto!important)
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(set-cookie, twtr_pixel_opt_in, N)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
  ##a[href*=".xyz/"] div
  ##iframe[title="3rd party ad content"]
```
</details>

**Comment by dimisa-RUAdList** [comment]
Try using: `eurointegration.com.ua##+js(aopr, as_retry)`

**Comment by stephenhawk8054** [comment]
@dportvine Does this work?

```adb
*$doc,csp=script-src-attr 'none',to=eurointegration.com.ua
```

**Comment by dportvine** [comment]
Both works for me
