### ISSUE TITLE
zeenews.india.com: breakage

### ISSUE THREAD

**Issue by kookieman12** [uBlockOrigin/uAssets#24786]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://zeenews.india.com/technology/airtel-launches-new-plan-with-unlimited-calling-with-extended-validity-airtel-vs-jio-vs-bsnl-plan-offer-benefits-compared-2773794.html`

### Category

[unknown]

### Description

When ubo is enabled and read more button is pressed, then nothing happens and the full article cannot be read. 

### Other extensions used

Bypass paywalls clean 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 128
filterset (summary):
 network: 161420
 cosmetic: 125253
 scriptlet: 27230
 html: 1901
listset (total-discarded, last-updated):
 added:
  curben-phishing: 491-4, now
  adguard-cookies: 30733-44, now
  ublock-cookies-adguard: 1543-21, now
  fanboy-cookiemonster: 51460-3950, now
  ublock-cookies-easylist: 1543-1543, now
 default:
  user-filters: 2-0, never
  ublock-filters: 40171-120, now
  ublock-badware: 10207-1, now
  ublock-privacy: 1040-4, now
  ublock-unbreak: 2532-1, now
  ublock-quick-fixes: 136-2, now
  adguard-mobile: 9638-74, now
  easylist: 87773-241, now
  easyprivacy: 53067-69, now
  urlhaus-1: 29210-0, now
  plowe-0: 3548-1064, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 580 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  amazon-adsystem.com: 1
  chartbeat.com: 2
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  izooto.com: 2
  pubmatic.com: 2
  scorecardresearch.com: 1
  taboola.com: 1
  vdo.ai: 1
  zeenews.com: 1
 extended:
  ###cookiepolicy-wrap
  ##div[class^="ads-"]
  ##.ad_container
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adv_txt
  ###taboola-below-article-thumbnails
  ##.cookiepolicy-wrap
  ##.screen-overlay-cookie
  ##.cookiepolicy
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
test

```
zeenews.india.com#@#div[class^="ads-"]
zeenews.india.com##.ads-placeholder-internal
zeenews.india.com##.first-ad
zeenews.india.com##.ads-box-300x250::before
```
