### ISSUE TITLE
trello.com: breakage

### ISSUE THREAD

**Issue by PAGWatson** [uBlockOrigin/uAssets#24789]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://trello.com/`

### Category

breakage

### Description

All I see when loading trello.com with uBlock Origin enabled is a grey bar at the top. If I disable uBlock Origin for trello.com, the site loads fine.

This is in Chrome 126.0.6478.128 64-bit, running in Windows 11.

### Other extensions used

Disable HTML5 Autoplay (disabling this makes no difference)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Chromium: 126
filterset (summary):
 network: 231067
 cosmetic: 256826
 scriptlet: 54186
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81316-5469, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 100308-87453, now
  adguard-generic: 83810-7476, now
  adguard-mobile: 9638-95, now
  adguard-social: 23246-771, now
  adguard-spyware: 84943-30544, now
  fanboy-cookiemonster: 51470-224, now
  fanboy-social: 16102-18, now
  fanboy-thirdparty_social: 68-0, now
  ublock-annoyances: 5983-11, now
 default:
  user-filters: 0-0, never
  easylist: 87842-662, now
  easyprivacy: 53073-674, now
  plowe-0: 3549-0, now
  ublock-badware: 10217-1, now
  ublock-filters: 39565-295, now
  ublock-privacy: 1044-2, now
  ublock-quick-fixes: 135-0, now
  ublock-unbreak: 2468-3, now
  urlhaus-1: 21325-0, now
filterset (user): [empty]
trustedset:
 added: [array of 154 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 631 ms (selfie)
 maxAssetCacheWait: 406 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  trello.com: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by PAGWatson** [comment]
It seems to be working for me now - possibly it was a glitch of some kind.
