### ISSUE TITLE
duckduckgo.com: breakage

### ISSUE THREAD

**Issue by hugo9655** [uBlockOrigin/uAssets#24787]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://duckduckgo.com/
```

### Description

On firefox mobile, no search results appear when searching on ddg with ubo on. ETP doesnt affect this.

### Other extensions used

** **

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/00cd2874-35f8-4841-a80f-a6dd9db60fa9)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 128
filterset (summary):
 network: 261545
 cosmetic: 277545
 scriptlet: 55110
 html: 2174
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83810-5185, 2m
  adguard-spyware-url: 1626-123, 2m
  adguard-spyware: 84943-166, 2m
  block-lan: 70-0, 2m
  curben-phishing: 472-0, 2m
  adguard-social: 23248-56, 2m
  adguard-cookies: 30733-53, 2m
  adguard-popup-overlays: 27662-1016, 2m
  adguard-mobile-app-banners: 5390-32, 2m
  adguard-other-annoyances: 14858-408, 2m
  adguard-widgets: 2626-17, 2m
  fanboy-thirdparty_social: 68-3, 2m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40171-230, 4m Δ
  ublock-badware: 10213-2, 4m Δ
  ublock-privacy: 1040-281, 4m Δ
  ublock-unbreak: 2530-67, 4m Δ
  ublock-quick-fixes: 142-2, 4m Δ
  adguard-mobile: 9638-11, 2m
  easylist: 87841-2385, 4m Δ
  easyprivacy: 53073-30057, 4m Δ
  urlhaus-1: 21325-0, 2m
  plowe-0: 3549-1486, 3m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5183 ms (selfie)
 maxAssetCacheWait: 359 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  duckduckgo.com: 13

```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by CinderBH** [comment]
In my case, it turned out the issue was caused by the Huge AI Blocklist custom filter.

**Comment by stephenhawk8054** [comment]
> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

Respect the prerequisites please.
