### ISSUE TITLE
es.aliexpress.com: breakage

### ISSUE THREAD

**Issue by veb-xenon** [uBlockOrigin/uAssets#24798]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://es.aliexpress.com/`

### Category

breakage

### Description

AliExpress website broken in Firefox using uBlock Origin. Same issue does not happen for now in Microsoft Edge (2nd screenshot). 

### Other extensions used

VideoDownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagen](https://github.com/user-attachments/assets/eb2a8969-d5bd-49dd-a3e4-97fc5e96722f)

![imagen](https://github.com/user-attachments/assets/05b35e66-902c-4a39-921e-c8361bd95755)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 158265
 cosmetic: 54778
 scriptlet: 21682
 html: 1900
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1108-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39729-118, 16m Δ
  ublock-badware: 10224-1, 16m Δ
  ublock-privacy: 1039-4, 16m Δ
  ublock-unbreak: 2527-1, 16m Δ
  ublock-quick-fixes: 147-2, 16m Δ
  easylist: 87883-172, 16m Δ
  easyprivacy: 53074-63, 16m Δ
  urlhaus-1: 29190-0, now
  plowe-0: 3558-997, now
  spa-0: 4071-27, now
  spa-1: 5870-255, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 122 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  go-mpulse.net: 1
  x.akamaiedge.net: 20
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/issues/24796

**Comment by EmEiBee** [comment]
same. Complete 1st line with Login and so on missing
