### ISSUE TITLE
binge.com.au: ads

### ISSUE THREAD

**Issue by MissJPJW** [uBlockOrigin/uAssets#24797]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://binge.com.au/shows/show-game-of-thrones!1446`

### Category

ads

### Description

unlike youtube or other sites binge still plays video ads with ublock on, like five of them in a row several times throughout watching a show

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 155664
 cosmetic: 47702
 scriptlet: 20597
 html: 1900
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39729-118, 13m Δ
  ublock-badware: 10224-1, 13m Δ
  ublock-privacy: 1039-4, 13m Δ
  ublock-unbreak: 2527-1, 13m Δ
  ublock-quick-fixes: 147-2, 13m Δ
  easylist: 87883-172, 13m Δ
  easyprivacy: 53074-61, 13m Δ
  urlhaus-1: 29190-0, now
  plowe-0: 3558-997, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 165 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 network:
  binge.com.au: 2
  adobedtm.com: 7
  ads-twitter.com: 1
  adsrvr.org: 1
  bing.com: 1
  branch.io: 1
  d34r8q7sht0t9k.cloudfront.net: 1
  demdex.net: 1
  everestjs.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  id5-sync.com: 1
  impactradius-event.com: 1
  newrelic.com: 2
  pdst.fm: 1
  pinimg.com: 1
  quantserve.com: 1
  redditstatic.com: 1
  sc-static.net: 1
  segment.com: 1
  streamotion.com.au: 5
  tiktok.com: 1
  youborafds01.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Do you know any free links that can reproduce the issue?
