### ISSUE TITLE
[Anti-Adblock] blockadblock.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2479]
### URL(s) where the issue occurs

`https://blockadblock.com/`

### Describe the issue

A horrible filthy dirty putrid filth of a anti-adblock message.

### Screenshot(s)

![screenshot-2018-5-20](https://user-images.githubusercontent.com/12204587/40999932-51b62e86-6904-11e8-8679-a102420c5341.jpg)

### Versions

- Browser/version: Firefox Latest
- uBlock Origin version: Latest

### Settings

Default

### Notes

The worst kind of sites.

**Comment by mapx-** [comment]
read
https://github.com/gorhill/uBlock/issues/3476

**Comment by C0nw0nk** [comment]
Understandable.

So I can add a custom user filter of this.

```
@@||blockadblock.com^$generichide
```

Should fix it.

Allowing me to browse and read the sites contents.

I tested with adguard extension and it seems adguard has them in their filters.
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L1908

**Comment by cup** [comment]
- http://github.com/uBlockOrigin/uAssets/issues/3020
- http://github.com/uBlockOrigin/uAssets/issues/2479
- http://github.com/uBlockOrigin/uAssets/issues/2105

**Comment by cup** [comment]
1. Dashboard
2. Filter lists
3. Ads
4. Adguard Base Filters​
