### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by DenTechs** [uBlockOrigin/uAssets#24796]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.aliexpress.us/` `https://www.aliexpress.com/`

### Category

breakage

### Description

Site does not load properly. Main page is missing search bar and shopping cart. Item pages dont load at all except for about page info. 

### Other extensions used

`Bitwarden Password Manager` `Dark Reader` `SponsorBlock for YouTube` `To Google Translate`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7f09ff28-dff9-4fe4-9c90-29b3016fb6c6)
![image](https://github.com/user-attachments/assets/89860dd1-1c90-4c87-b44d-a7dab638e815)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 155661
 cosmetic: 47702
 scriptlet: 20595
 html: 1900
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39727-207, now
  ublock-badware: 10224-18, now
  ublock-privacy: 1039-6, now
  ublock-unbreak: 2527-16, now
  ublock-quick-fixes: 143-2, now
  easylist: 87883-49, now
  easyprivacy: 53074-61, now
  urlhaus-1: 29190-0, now
  plowe-0: 3558-997, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 180 ms (selfie)
 maxAssetCacheWait: 60 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  go-mpulse.net: 1
  x.akamaiedge.net: 28
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `e11956.x.akamaiedge.net` in EasyList

@ryanbr

**Comment by DenTechs** [comment]
Thank you!

**Comment by trulyx** [comment]
I'm currently experiencing the same issue, already updated my lists.

**Comment by stephenhawk8054** [comment]
@trulyx The filter list will update to you in about 4-5 hours. You can also add this as a custom filter in the meantime:

```adb
||e11956.x.akamaiedge.net^$badfilter
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
