### ISSUE TITLE
crackle.com: breakage

### ISSUE THREAD

**Issue by CyborgManBeast** [uBlockOrigin/uAssets#24795]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.crackle.com/details/34589606-5860-4b02-bef3-f68b231eaf48/hell's-kitchen/day-one`

### Category

breakage

### Description

When trying to watch anything on Crackle it seems to detect Ublock Origin. You can see in the attached screenshot the error message which is displayed. If I disable Ublock Origin, it works properly again. 

### Other extensions used

No other extension were used at the time I encountered this issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-06 222454](https://github.com/user-attachments/assets/facdccbd-0faf-46d6-a1d8-807753421dac)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 160321
 cosmetic: 89405
 scriptlet: 24238
 html: 1900
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27666-214, 5m
  adguard-mobile-app-banners: 5391-23, 5m
  adguard-other-annoyances: 14860-290, 5m
  adguard-widgets: 2627-12, 5m
 default:
  user-filters: 13-1, never
  ublock-filters: 39727-118, 1m
  ublock-badware: 10224-1, 1m
  ublock-privacy: 1039-4, 1m
  ublock-unbreak: 2527-1, 1m
  ublock-quick-fixes: 147-2, 1m
  easylist: 87870-172, 1m
  easyprivacy: 53073-61, 1m
  urlhaus-1: 29190-0, 1m
  plowe-0: 3558-997, 1m
filterset (user): [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1568 ms (selfie)
 maxAssetCacheWait: 197 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  bitmovin.com: 1
  google.com: 1
  googletagmanager.com: 1
  mparticle.com: 2
 extended:
  ##+js(json-prune-fetch-response, data.device.adsParams data.devi…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
- it seems to be a FF issue: disabling uBO => I get a 20 seconds ad and then the OP error. 
- no issues in chrome
