### ISSUE TITLE
pcgameshardware.de: ads

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#24802]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pcgameshardware.de/SSD-Hardware-255552/News/Micron-PCI-Express-6-0-1453138/`

### Category

ads

### Description

Shows two kind of ads next to the article text. The first ad is a link to another article where they offer links to products and get revenue from a purchase. The image of this link has the German word for "ad" on it.

The other kind of ad is right below advertising some AI voices. This ad also leads to an 'article' but on top of this article is also the German word for "ad".

So, both are ads.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/af731612-6d7f-4a25-b9d2-a62c0285550c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 127
filterset (summary):
 network: 129195
 cosmetic: 54596
 scriptlet: 26034
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  ublock-annoyances: 5983-12, now
 default:
  user-filters: 20-0, never
  DEU-0: 7520-1, now
  easylist: 87882-569, now
  easyprivacy: 53074-675, now
  plowe-0: 3558-0, now
  ublock-badware: 10263-6, now
  ublock-filters: 39583-290, now
  ublock-privacy: 1044-2, now
  ublock-quick-fixes: 147-0, now
  ublock-unbreak: 2468-2, now
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1275 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  pcgameshardware.de: 5
  adscale.de: 2
  chartbeat.com: 2
  cleverpush.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  m6r.eu: 1
  outbrain.com: 1
  theadex.com: 1
  userreport.com: 1
  vgwort.de: 1
  yieldlove.com: 1
 extended:
  ##.wadtag
  ##.rectad
  ##.innerContentAd
  ##.OUTBRAIN
  ##.contentFrameEddie
  ##.topFrameEddie
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-promotion?

@JobcenterTycoon Sorry, what do you think?

**Comment by JobcenterTycoon** [comment]
The startpage is full with these promotion articles.

Similar issues got declined by EL germany already https://github.com/easylist/easylistgermany/issues/170

Also its not a case for uAssets.
