### ISSUE TITLE
smartmeter.netz-noe.at: breakage

### ISSUE THREAD

**Issue by arminfuerst** [uBlockOrigin/uAssets#24804]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://smartmeter.netz-noe.at/`

### Category

breakage

### Description

Login is not possible, when deactivating uBlock Origin, the login is working properly. Even selecting the passwort-field is not possible with the mouse, selecting it with the keyboard is working. Sending the login with <ENTER> is also working.
When reloading the site, the behavior changes randomly, sometimes even Login is not selectable, sometimes Password is working.

### Other extensions used

Autoplay No More
Binnen-I be gone
Consent Blocker
Cookie AutoDelete
Cookie Quick Manager
Ghostery
Sponsorblock for YouTube
Video DownloadHelper
YouTube Classic

 -> The site is working properly with all those enabled and having uBlock Origin disabled. The site is even working with AdBlockPlus enabled together with all those extensions (and without uBO).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 155701
 cosmetic: 47705
 scriptlet: 20600
 html: 1900
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39736-118, now
  ublock-badware: 10265-6, now
  ublock-privacy: 1039-4, now
  ublock-unbreak: 2527-1, now
  ublock-quick-fixes: 149-2, now
  easylist: 87882-172, now
  easyprivacy: 53074-61, now
  urlhaus-1: 29190-0, 1h.5m
  plowe-0: 3558-997, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 981 ms (selfie)
 maxAssetCacheWait: 380 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  etracker.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
@@||code.etracker.com/code/e.js$script,domain=smartmeter.netz-noe.at
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by arminfuerst** [comment]
> Can you test this filter?
> 
> ```
> @@||code.etracker.com/code/e.js$script,domain=smartmeter.netz-noe.at
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Thanks you for the fast response, but this does not change the behavior, so the filter does not help.

**Comment by arminfuerst** [comment]
Is this the log you were writing about?

<details><summary>Logger output</summary>

```
+19
smartmeter.netz-noe.at
3
options
xhr
https://c.datareporter.eu/e/1/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/01/2j/deny/f1bb5da0-54a5-11ef-893b-cfdecce00454
```
```
+18
smartmeter.netz-noe.at
3
get
xhr
https://c.datareporter.eu/e/1/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/01/2j/deny/f1bb5da0-54a5-11ef-893b-cfdecce00454
```
```
+18
smartmeter.netz-noe.at
1
get
font
https://smartmeter.netz-noe.at/resources/35288d5e-681e-4b64-a930-438d2b2551d6.b8df483613e9b715.woff
```
```
+18
smartmeter.netz-noe.at
1
get
font
https://smartmeter.netz-noe.at/resources/5f3f5b96-b77d-497d-a916-d483bc9c6c3f.1e51a0883cb9c392.woff
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/navigation-footer.2270a274c619d163.png
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/phone-icon.c9bcec381b9ee588.png
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/footer-navi-bg.d6ebd8eda91056ad.jpg
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/arrow-red.0be2773621473524.png
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/navigation-main.9ca11554cbd7ed88.png
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/header-top-gradient.4833da29a798eb94.jpg
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/resources/header-top-bg.97acd1ddceb95c1e.jpg
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/assets/images/logo.png
```
```
+18
smartmeter.netz-noe.at
1
get
xhr
https://smartmeter.netz-noe.at/orchestration/User/GetBasicInfo
```
```
+18
smartmeter.netz-noe.at
1
get
xhr
https://smartmeter.netz-noe.at/undefined/Settings/LoggingSettings
```
```
+18
smartmeter.netz-noe.at
1
get
xhr
https://smartmeter.netz-noe.at/assets/i18n/de.json
```
```
+18
smartmeter.netz-noe.at
1
get
xhr
https://smartmeter.netz-noe.at/environment/environment.json
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://smartmeter.netz-noe.at/assets/images/favicon.ico
```
```
+18
smartmeter.netz-noe.at
1
get
xhr
https://smartmeter.netz-noe.at/assets/i18n/de.json
```
```
+18
smartmeter.netz-noe.at
3
options
xhr
https://c.datareporter.eu/e/1/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/01/88/o/-
```
```
+18
smartmeter.netz-noe.at
3
get
xhr
https://c.datareporter.eu/e/1/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/01/88/o/-
```
```
+18
smartmeter.netz-noe.at
3
get
image
https://www6.evn.at/
aliasURL=https://www.netz-noe.at/App_Themes/Netz-noe/images/logo.png
```
```
+18
smartmeter.netz-noe.at
1
get
image
https://www.netz-noe.at/App_Themes/Netz-noe/images/logo.png
```
```
+18
smartmeter.netz-noe.at
1
get
css
https://smartmeter.netz-noe.at/styles.fbab997bf7666238.css
```
```
+18
smartmeter.netz-noe.at
1
get
font
https://smartmeter.netz-noe.at/resources/d74de079-587d-4049-9cca-50ba02a536f9.9d4d48b5388fd4cd.woff
```
```
+18
smartmeter.netz-noe.at
1
get
script
https://smartmeter.netz-noe.at/main.77298a38093df222.js
```
```
+18
smartmeter.netz-noe.at
1
get
script
https://smartmeter.netz-noe.at/scripts.683ce21c4e83bdee.js
```
```
+18
smartmeter.netz-noe.at
1
get
script
https://smartmeter.netz-noe.at/polyfills.611dfcfdd95cb2ee.js
```
```
+18
smartmeter.netz-noe.at
1
get
script
https://smartmeter.netz-noe.at/runtime.bb89ffeac3e14504.js
```
```
+18
smartmeter.netz-noe.at
3
get
script
https://webcache.b-cdn.net/
aliasURL=https://webcache-eu.datareporter.eu/c/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/MMo/banner.js
```
```
+18
smartmeter.netz-noe.at
3
get
script
https://webcache-eu.datareporter.eu/c/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/MMo/banner.js
```
```
+18
smartmeter.netz-noe.at
3
get
css
https://webcache.b-cdn.net/
aliasURL=https://webcache-eu.datareporter.eu/c/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/MMo/banner.css
```
```
+18
smartmeter.netz-noe.at
3
get
css
https://webcache-eu.datareporter.eu/c/b4aa2ff2-7e18-4674-9a07-1a29935acbcc/Y55Ce0zVDnMA/MMo/banner.css
```
```
+18
@@||code.etracker.com/code/e.js$script,from=smartmeter.netz-noe.at
++
smartmeter.netz-noe.at
3
get
script
https://code.etracker.com/code/e.js
```
```
+18
smartmeter.netz-noe.at
1
get
doc
https://smartmeter.netz-noe.at/#/login
```
```
+18
https://smartmeter.netz-noe.at/#/login
```
```
+0
github.com
0,1
get
websocket
wss://alive.github.com/_sockets/u/29121472/ws?session=eyJ2IjoiVjMiLCJ1IjoyOTEyMTQ3MiwicyI6MTQzOTU1NzA1OCwiYyI6MjcwODc2MzI0MSwidCI6MTcyMzAyNDY3OH0%3D--d010ae18f26a1cf5f353c5204e3095d7a69d1675e38a191d3b10fa14dd6581cb&shared=true&p=616436578_1723017295.12
```
</details>

**Comment by stephenhawk8054** [comment]
Hmm... There's nothing blocked in uBO. Can you click on uBO icon and screenshot to here?

**Comment by arminfuerst** [comment]
You mean a screenshot of the website? Or the log? Or something else?

**Comment by arminfuerst** [comment]
It's strange, I already saw "Blocked on this page: 1" today. And it's still working every time, when I disable uBO, and after seeing this now, I am very confused...
![image](https://github.com/user-attachments/assets/e4506b09-4b02-4ba2-b294-027909df3b7e)

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings + this filter: https://github.com/uBlockOrigin/uAssets/issues/24804#issuecomment-2273050306

**Comment by arminfuerst** [comment]
I will, but I can't do this right now. Thanks so far!

**Comment by arminfuerst** [comment]
> Test again in a new Firefox profile with only uBO and its default settings + this filter: [#24804 (comment)](https://github.com/uBlockOrigin/uAssets/issues/24804#issuecomment-2273050306)

I assume, it's an issue in combination with "Consent Blocker". If I disable either CB or uBO, the site is working, with uBO even without the custom rule.
Thanks for your help, I will close this issue.

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I am not using uBlock Origin along with other content blockers.
