### ISSUE TITLE
fr.aliexpress.com: breakage

### ISSUE THREAD

**Issue by Cartoon-Dude** [uBlockOrigin/uAssets#24806]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fr.aliexpress.com/?gatewayAdapt=glo2fra`

### Category

breakage

### Description

Everything from https://e11956.x.akamaiedge.net/ blocked   
No menu in the site
Fine when deactivating ublock

### Other extensions used

umatrix

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/8f821c04-8e7c-4cd7-a074-cd5136dfc222)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 155666
 cosmetic: 47704
 scriptlet: 20597
 html: 1900
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 default:
  user-filters: 4-0, never
  ublock-filters: 39729-118, 47m Δ
  ublock-badware: 10224-1, 47m Δ
  ublock-privacy: 1039-4, 47m Δ
  ublock-unbreak: 2527-1, 47m Δ
  easylist: 87883-172, 47m Δ
  easyprivacy: 53074-61, 47m Δ
  plowe-0: 3558-997, now
  urlhaus-1: 29190-0, now
  ublock-quick-fixes: 147-2, 47m Δ
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 14 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 447 ms (selfie)
 maxAssetCacheWait: 215 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  x.akamaiedge.net: 21
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/issues/24796

Update your filter lists again
