### ISSUE TITLE
iskon.hr: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#24809]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.iskon.hr/`

### Category

nuisance

### Description

Cookie notice present on the right side of the screen

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/844006b8-d18d-4afa-a428-c8f8b4b81302)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 264967
 cosmetic: 226537
 scriptlet: 52579
 html: 2156
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-91, now
  adguard-generic: 83850-8732, now
  adguard-spyware-url: 1631-123, now
  adguard-spyware: 84944-25820, now
  curben-phishing: 562-2, now
  ublock-cookies-adguard: 1505-0, now
  fanboy-cookiemonster: 51474-270, now
  ublock-cookies-easylist: 1505-1505, now
  adguard-social: 23248-57, now
  fanboy-social: 16786-746, now
  adguard-popup-overlays: 27678-1110, now
  adguard-mobile-app-banners: 5392-27, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  ublock-filters: 39740-118, now
  ublock-badware: 10265-80, now
  ublock-privacy: 1040-16, now
  ublock-unbreak: 2524-2, now
  ublock-quick-fixes: 149-2, now
  easylist: 87886-23209, now
  easyprivacy: 53074-40481, now
  urlhaus-1: 29415-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 194 ms (selfie)
 maxAssetCacheWait: 122 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  midas-network.com: 2
  pushpushgo.com: 2
 extended:
  ##.list-inline.social
  ##.grecaptcha-badge
  ##.grecaptcha-badge[data-style]
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by krystian3w** [comment]
What does not work if you hide by picker and repair scrolling?

**Comment by Marko-98** [comment]
Buttons and links anywhere on the site.

**Comment by krystian3w** [comment]
If nobody found obvious breakage then will be moved to ELC.

The hardest will be test hidden under login wall panel.
