### ISSUE TITLE
[nsfw] wiflix-catalogue.online: ads

### ISSUE THREAD

**Issue by gravvou** [uBlockOrigin/uAssets#24805]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wiflix-catalogue.online/series-en-streaming/31386-mayor-of-kingstown-saison-3-1dksl.html`

### Category

ads

### Description

Hello this site contains too many ads and misleading advertising banners

### Other extensions used

Hello this site contains too many ads and misleading advertising banners

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 173131
 cosmetic: 54386
 scriptlet: 22192
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 24693-92, now
  easylist: 87883-520, 48m Δ
  easyprivacy: 53074-865, 48m Δ
  plowe-0: 3558-0, now
  ublock-badware: 10222-1, 48m Δ
  ublock-filters: 39576-429, 48m Δ
  ublock-privacy: 1044-2, 48m Δ
  ublock-quick-fixes: 145-0, 48m Δ
  ublock-unbreak: 2468-0, 48m Δ
  urlhaus-1: 29190-0, now
filterset (user): [empty]
trustedset:
 added: [array of 46 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5515 ms (selfie)
 maxAssetCacheWait: 2042 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  addthis.com: 1
  crazesmalto.com: 1
  glossydollyknock.com: 2
  googletagmanager.com: 1
  pimplyhauling.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@smed79 Sorry, can you check this?

**Comment by mapx-** [comment]
@gravvou report here: https://github.com/easylist/listefr/issues
