### ISSUE TITLE
Youtube ads started playing today and skip button is missing while running ublock

### ISSUE THREAD

**Issue by SwiftXQ** [uBlockOrigin/uAssets#24808]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.youtube.com/watch?v=w_IwHcaT1h4
```

### Description

As of today when playing videos i started getting ads that sometimes are 2minutes long and the skip button is missing, disabling ublock makes the skip button appear, i looked through all the posts and i couldnt find any solutions to this.

I did everything as instructed in this post but nothing changed

![image](https://github.com/user-attachments/assets/be81ce20-7aa2-48ae-a87c-0ff788c93ab4)

⚠️ P-L-E-A-S-E, PLEASE, PLEASE, PLEASE read and follow all of the instructions first ⚠️

### Other extensions used

Global twitch emotes
Ublock origin
Video Downloader plus
Watch2gether
7TV
BetterTTV
Volume Master
Autotube Yotube nonstop
Shazam
Sponsorblock for Yotube (This extension was installed today but the issue was already present before downloading this)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/953b04b3-dbd2-482d-9363-998520002123)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 155704
 cosmetic: 47803
 scriptlet: 22041
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39583-272, 30m
  ublock-badware: 10263-6, 30m
  ublock-privacy: 1044-2, 21m Δ
  ublock-unbreak: 2468-0, 30m
  ublock-quick-fixes: 147-0, 21m
  easylist: 87861-557, 21m Δ
  easyprivacy: 53074-649, 21m Δ
  urlhaus-1: 29190-0, 30m
  plowe-0: 3558-0, 30m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 963 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 116
 network:
  youtube.com: 64
  doubleclick.net: 9
  google.com: 43
 extended:
  ##.ytp-featured-product
  ###masthead-ad
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> #content > ytd-ad-slot-renderer)
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…

```
</details>

**Comment by SwiftXQ** [comment]
As i post this i realize my mistake lol, i was confused what it meant when clicking on (This is NOT a [YouTube]) as it would just send me to the post, thought it was gonna send me to another forum but i assume that i was meant to make a comment on that post, sorry

**Comment by stephenhawk8054** [comment]
Don't just make comment in that post: 

> 🟥 ALL YouTube issues: D-O-N-'T COMMENT without reading the 1st post🟥

**Comment by SwiftXQ** [comment]
> Don't just make comment in that post:
> 
> > 🟥 ALL YouTube issues: D-O-N-'T COMMENT without reading the 1st post🟥

Then where am i supposed to report this issue?

**Comment by stephenhawk8054** [comment]
> reading the 1st post

Read and follow the 1st post of that thread.
