### ISSUE TITLE
graphy.com: breakage 

### ISSUE THREAD

**Issue by Moksha099** [uBlockOrigin/uAssets#24801]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://graphy.com/signup/
```

### Description

With ublock origin enabled clicking on the sign in link returns a blank page. To make the site function as usual, I've to disable ublock.

### Other extensions used

I've made sure ublock is what's causing the issue.

### Screenshot(s)

![ublock_issue](https://github.com/user-attachments/assets/cf5bb0e5-a479-4600-8b38-ad758ad221d6)

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 128
filterset (summary):
 network: 177033
 cosmetic: 225060
 scriptlet: 35008
 html: 2174
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1731-0, 2h.20m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2653-9, 2h.20m
  adguard-social: 23230-51, 1d.23h.25m
  adguard-cookies: 30697-46, 1d.23h.25m
  ublock-cookies-adguard: 1543-22, 1d.29m
  adguard-popup-overlays: 27646-989, 1d.23h.25m
  adguard-mobile-app-banners: 5380-32, 1d.23h.24m
  adguard-other-annoyances: 14847-407, 1d.23h.25m
  adguard-widgets: 2625-16, 1d.23h.26m
  fanboy-thirdparty_social: 68-3, 6d.5m
  easylist-annoyances: 4687-300, 1d.29m
  easylist-chat: 204-17, 6d.5m
  [7 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 40176-120, 2h.20m Δ
  ublock-badware: 10218-1, 2h.20m Δ
  ublock-privacy: 1040-54, 2h.20m Δ
  ublock-unbreak: 2530-5, 2h.20m Δ
  ublock-quick-fixes: 147-2, 2h.20m Δ
  adguard-mobile: 9633-77, 1d.23h.26m
  easylist: 87883-245, 2h.20m Δ
  easyprivacy: 53074-277, 2h.20m Δ
  urlhaus-1: 29190-0, 2h.19m
  plowe-0: 3548-1065, 5d.13h.30m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 586 ms (selfie)
 maxAssetCacheWait: 299 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  firstpromoter.com: 1
  google-analytics.com: 1
  google.com: 2
  googleoptimize.com: 1
  googletagmanager.com: 2
  youtube.com: 3
  zohocdn.com: 1
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(remove-attr, jsaction, #islsp c-wiz a[href^="http"][data-v…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
  ##+js(remove-attr, data-jsarwt, #rcnt [data-ved] a)
  #@#+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9…

```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@Moksha099 

add

`graphy.com#@#.bottom-0`

ELC issue @ryanbr

**Comment by Moksha099** [comment]
> @Moksha099
> 
> add
> 
> `graphy.com#@#.bottom-0`
> 
> ELC issue @ryanbr

Thanks! Now the site's functioning as usual and I didn't face any difficulty logging in..
