### ISSUE TITLE
namu.wiki: breakage

### ISSUE THREAD

**Issue by spurseoul** [uBlockOrigin/uAssets#24817]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://namu.wiki/w/%EB%B6%84%EB%A5%98:%EC%98%81%EA%B5%AD%EC%9D%98%20%EB%8F%84%EC%8B%9C`

### Category

breakage

### Description

Turned on:
![스크린샷_8-8-2024_12372_namu wiki](https://github.com/user-attachments/assets/b671d396-2808-49b2-b6cd-65c63dd10d59)
Turned off:
![스크린샷_8-8-2024_123637_namu wiki](https://github.com/user-attachments/assets/658ebc30-f88c-4870-a39b-3d3cb6ecbf3a)

### Other extensions used

uBlacklist

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![스크린샷_8-8-2024_123637_namu wiki](https://github.com/user-attachments/assets/d14805b7-aadf-41f4-a6ba-6d302cb66a33)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 157487
 cosmetic: 51273
 scriptlet: 22203
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 15-5, never
  KOR-1: 5061-45, 14m
  easylist: 87908-592, 14m Δ
  easyprivacy: 53074-658, 14m Δ
  plowe-0: 3558-0, now
  ublock-badware: 10269-6, 14m Δ
  ublock-filters: 39587-275, 14m Δ
  ublock-privacy: 1045-4, 14m Δ
  ublock-quick-fixes: 144-0, 14m Δ
  ublock-unbreak: 2465-0, 14m Δ
  urlhaus-1: 29575-0, 14m
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1800 ms (selfie)
 maxAssetCacheWait: 459 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  doubleclick.net: 1
  googlesyndication.com: 3
 extended:
  ##div:not([class*=" "]) ~ div div + div[class]:has(> div[id][cla…
  ##div[id][class]:empty
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
namu.wiki##div:not([class*=" "]) ~ div div + div[class]:has(> div[id][class])
```

in `List-KR`

cc @piquark6046 Sorry, can you check this?

**Comment by piquark6046** [comment]
https://github.com/uBlockOrigin/uAssets/issues/24817#issuecomment-2275001765
The breakage cannot be reproduced with AdGuard Browser Extension. I will try with uBO. Just a sec.

**Comment by piquark6046** [comment]
Cannot reproduce.

**Comment by piquark6046** [comment]
Okay. I can reproduce with Proton VPN KR#14.
