### ISSUE TITLE
[nsfw] uzx.com: popups

### ISSUE THREAD

**Issue by polita73** [uBlockOrigin/uAssets#24815]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uzx.com/`

### Category

popups

### Description

Brings a pop up on every new window or just by itself.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1096" alt="Screen Shot 2024-08-07 at 20 17 24" src="https://github.com/user-attachments/assets/78cbcd91-28fe-4d25-a4a0-4bd36d64aa71">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 158527
 cosmetic: 54508
 scriptlet: 21088
 html: 1899
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39740-118, 39m
  ublock-badware: 10308-6, 39m
  ublock-privacy: 1040-4, 39m
  ublock-unbreak: 2524-1, 39m
  ublock-quick-fixes: 150-2, 39m
  easylist: 87910-172, 39m
  easyprivacy: 53074-61, 39m
  urlhaus-1: 29575-0, 39m
  plowe-0: 3558-997, 39m
  spa-0: 4071-27, 39m
  spa-1: 5871-255, 39m
filterset (user): [empty]
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2997 ms
 maxAssetCacheWait: 421 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  uzx.com: 8
  googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
> Brings a pop up on every new window or just by itself.

It's likely your computer is infected by malwares
