### ISSUE TITLE
aneurismuox.click: Potentially malicious

### ISSUE THREAD

**Issue by MEtICaRT** [uBlockOrigin/uAssets#24810]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
aneurismuox.click
```

### Description

When attempting to install cracked software from macfiles.org by clicking the download button, a random website opens. Google Safe Browsing shows a warning, and VirusTotal indicates that it is malicious. Various DNS filters have blocked it, citing AI Threat Detection, and it is also flagged as a Newly Registered Domain. While I cannot personally confirm whether it contains malware, there are numerous indicators suggesting it does. Screenshots are provided below.

I also have suspicions that this URL ([example](https://aneurismuox.click/?up=5bd293dd38f34c46314c&k=2127&down=e0abf43a4766&j=Adobe%20Photoshop%202024%20v25.9.1%20macOS)) redirects to phishing or malware sites, as there are multiple redirections on PC. Therefore, please use a mobile user agent in addition to PC user agent while researching the 'Download' button.

[URL with the "Download" button](https://www.macfiles.org/adobe-premiere-pro-2024-v24-3/)

[VirusTotal Scan](https://www.virustotal.com/gui/url/91a743709eddf19459b26dc96efb04613e2b3863bb715da7240e6148023b3893?nocache=1)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="799" alt="image" src="https://github.com/user-attachments/assets/c6b4a8e1-5040-4aa8-a5a8-f478f4175acf">
<img width="372" alt="image" src="https://github.com/user-attachments/assets/5b431126-1058-4ed3-af5a-b17912420598">
<img width="509" alt="image" src="https://github.com/user-attachments/assets/5e54030c-56de-4db9-874f-345edf8ee481">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
The popup is blocked by `/?*&gkss=$doc,domain=click|pro|xyz|cfd|world` on my end.

**Comment by JobcenterTycoon** [comment]
Redirect chain:

```
https://aneurismuox.click/?up=9ed404e0295a674c5&k=2127&down=cd23bdfee&j=Adobe%20Premiere%20Pro%202024%20v24.3
http://nonlibeloueim.click/?66b3aa74b29ea=0d7ac774b7cdaa8fa703d05c5d313a93&66b3aa74b2a04=2127&66b3aa74b2a05=_adobe-premiere-pro-2024-v24-3&gkss=542050
https://nuyjhuyklki.b-cdn.net/index.html
```

**Comment by stephenhawk8054** [comment]
There are many types of random domains like that, and it's not possible to block all of those domains

```
https://vnie0kj3.cfd/?iU3cQ4okdesmGHCM1ng=u7DsJ18EIgponCRiOxqSBV3WrGFZLhzA&{12_hash}={5_digit}&7BD8PYTWFbmOM103f=3_Download-Bandicam-7-0-1-2132-Free-Full-Activated&gkss=634570
```

We block based on the path, not just the domains.
