### ISSUE TITLE
hulu.com: breakage

### ISSUE THREAD

**Issue by ryanww0629** [uBlockOrigin/uAssets#24818]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hulu.com/watch/d26c460a-b7b4-42d0-a169-e7fe7f5274b2`

### Category

breakage

### Description

Refuses to load video when Ublock is enabled.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 156168
 cosmetic: 47726
 scriptlet: 20588
 html: 1899
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39744-118, now
  ublock-badware: 10307-6, now
  ublock-privacy: 1040-4, now
  ublock-unbreak: 2524-1, now
  ublock-quick-fixes: 134-2, now
  easylist: 87938-172, now
  easyprivacy: 53077-62, now
  urlhaus-1: 29575-0, now
  plowe-0: 3558-997, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 496 ms
 maxAssetCacheWait: 180 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 165
 network:
  hulu.com: 42
  adsrvr.org: 14
  doubleclick.net: 2
  doubleverify.com: 11
  extremereach.io: 6
  googlesyndication.com: 3
  imrworldwide.com: 3
  innovid.com: 5
  ispot.tv: 3
  moatads.com: 1
  omtrdc.net: 49
  pointmediatracker.com: 1
  scorecardresearch.com: 8
  tremorhub.com: 14
  truoptik.com: 3
 extended:
  ##+js(set-constant, Object.prototype._parseVAST, noopFunc)
  ##+js(set-constant, Object.prototype.createAdBlocker, noopFunc)
  ##+js(set-constant, Object.prototype.isAdPeriod, falseFunc)
  ##+js(json-prune-fetch-response, breaks pause_ads video_metadata…
  ##+js(json-prune, breaks pause_ads video_metadata.end_credits_ti…
  ##+js(xml-prune, `xpath(//*[name()="MPD"]/@mediaPresentationDura…
```
</details>

**Comment by alexanderwestm** [comment]
You're running version 129 of Firefox. There's currently an issue with version 129 that broke something with Hulu videos. This shouldn't be an issue with the uBlock filters themselves. Two fixes that I've seen work are downgrade Firefox to version 128 or enter `about:config` into your address bar and change `media.eme.mfcdm.origin-filter.enabled` from a 1 to a 0.

**Comment by stephenhawk8054** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1911283
