### ISSUE TITLE
https://www.twitch.tv/fastydubs

### ISSUE THREAD

**Issue by Papitafria** [uBlockOrigin/uAssets#24814]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/fastydubs`

### Category

ads

### Description

antes me funcionaba y ahora no

### Other extensions used

ninguna

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 158539
 cosmetic: 54604
 scriptlet: 22529
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39576-290, now
  ublock-badware: 10306-6, now
  ublock-privacy: 1045-2, now
  ublock-unbreak: 2465-2, now
  ublock-quick-fixes: 144-0, now
  easylist: 87910-611, now
  easyprivacy: 53074-662, now
  urlhaus-1: 29575-0, now
  plowe-0: 3558-0, now
  spa-0: 4071-3, now
  spa-1: 5871-192, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 818 ms (selfie)
 maxAssetCacheWait: 317 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 no-large-media: true
 network:
  amazon-adsystem.com: 2
  d2v02itv0y9u9t.cloudfront.net: 1
  googletagmanager.com: 1
  scorecardresearch.com: 3
  sentry.io: 4
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
