### ISSUE TITLE
footybite.to: detection

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#24812]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.footybite.to/Sturm-Graz-vs-PSG/30248`

### Category

detection

### Description

After clicking on pages like "Hesgoal", "TOP STREAMS", "Sports streamer", etc., the ublock is detected on the page that opens (whose name is `fan*.ssstik.cam` (with a number instead of a star)).

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![adblock detected](https://github.com/user-attachments/assets/9ada5927-d35e-474f-8173-8a673d5c7bb4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 157369
 cosmetic: 58140
 scriptlet: 23693
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  TUR-0: 13414-12, now
  easylist: 87901-561, 2m Δ
  easyprivacy: 53074-635, 2m Δ
  plowe-0: 3558-0, now
  ublock-badware: 10269-6, 2m Δ
  ublock-filters: 39587-286, 2m Δ
  ublock-privacy: 1045-2, 2m Δ
  ublock-quick-fixes: 147-0, 2m Δ
  ublock-unbreak: 2465-22, 2m Δ
  urlhaus-1: 29415-0, 2m
filterset (user): [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 479 ms
 maxAssetCacheWait: 149 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by punisher018** [comment]
`https://www.footybite.to/Egypt-vs-Morocco/30270` same for this link. After clicking on "Hesgoal" and "TOP STREAMS" , the ublock is detected on the page that opens (whose name is fan*.ssstik.cam (with a number instead of a star)).

Yesterday, as soon as I opened the topic here (maybe 5 minutes later) the adblock warning went away, so I closed the topic.

**Comment by stephenhawk8054** [comment]
I don't see where "Hesgoal" or "TOP STREAMS" are:

![image](https://github.com/user-attachments/assets/cbb6e652-769e-4420-b0dd-f90076b267d5)

Can you describe and screenshot where to click in more details?

**Comment by mapx-** [comment]
added filters for 2 hesgoal sites

detection
https://github.com/uBlockOrigin/uAssets/commit/c3f542823e206b0238b2819188b1603bafe65e54

popups
https://github.com/uBlockOrigin/uAssets/commit/dcc8dee04f6c61d543d6346cfa3d03645dc92ae9

**Comment by mapx-** [comment]
provide other testable links

**Comment by mapx-** [comment]
test

```
@@*$xhr,domain=homesports.net
||ssstik.cam^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation
```

**Comment by mapx-** [comment]
meaning you have to click twice ? I get no new popup

**Comment by mapx-** [comment]
what about

```adb
maxicast.click###openLinks
```

**Comment by kodiakhub** [comment]
Breakage:

`https://www.btvsports.my/stream2`

**Comment by mapx-** [comment]
> Breakage:
> 
> `https://www.btvsports.my/stream2`

no breakage on my end

**Comment by kodiakhub** [comment]
> > Breakage:
> > `https://www.btvsports.my/stream2`
> 
> no breakage on my end

<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/e9dfd1b9-c3a6-425f-9276-743d607e0aec)

https://github.com/user-attachments/assets/a29ed282-175b-426b-985d-7b874bb562e4

</p>
</details>

**Comment by mapx-** [comment]
```adb
thestreamhub.net##.ad-banner
```
report at easylist

**Comment by kodiakhub** [comment]
Popup:

`https://fsportshd.xyz/embed/f1-hungarian-grand-prix-live-streams.php`

**Comment by kodiakhub** [comment]
Popup:

`https://live3.totalsportek1000.com/MotoGP-Austrian-Grand-Prix-vs-Live/38703`

**Comment by kodiakhub** [comment]
Popup:

`https://alexsports.cv/HD/ch-7.php`

**Comment by kodiakhub** [comment]
Popup:

`https://worldsports.st/soccer/manchester-united-vs-arsenal-live-coverage/5`

To reproduce it, see:

<details><summary>GIF</summary>
<p>

![Image](https://github.com/user-attachments/assets/129fad3f-6864-4dc9-b72c-9623ab6456be)

</p>
</details>

**Comment by punisher018** [comment]
@stephenhawk8054 this rule breaks website

`totalsportek1000.com##+js(prevent-window-open)`

**Comment by stephenhawk8054** [comment]
@punisher018 Please give exact link and how to reproduce the issue.

**Comment by punisher018** [comment]
`https://www.footybite.to/Manchester-United-vs-Arsenal/44987`

This website provides links to broadcasts. It lists websites where broadcasts are available. When I click on a link, I should be taken to the website where the broadcast is available. However, since pop-up windows are blocked, nothing happens when I click on the broadcast links.

**Comment by stephenhawk8054** [comment]
> When I click on a link, I should be taken to the website where the broadcast is available. 

Please describe with screenshots where to click. Don't assume that we are familiar with every site.

**Comment by kodiakhub** [comment]
Popup:

`https://cdn.snapinstadownload.xyz/live/embed.php?ch=es3`

<img width="1272" height="147" alt="Image" src="https://github.com/user-attachments/assets/df59d2a8-3394-47b9-acfd-bc57d0436093" />

**Comment by punisher018** [comment]
@stephenhawk8054 When I opened the link I mentioned earlier and clicked on one of the match links, nothing happened when the window that normally opens the website where the broadcast is located should have opened. And when I checked the log, I saw that the specified filter was the cause. When I allowed the filter, I saw that clicking on it redirected me to the website. However, when I opened the link I mentioned earlier, I noticed that the filter wasn't loading, and the website was working fine. I don't know, maybe the website wasn't working properly at that moment. Sorry about that.

`https://sportstohfa.online/vacni100/c7/`
Btw pop up on this link too

**Comment by stephenhawk8054** [comment]
When I clicked on this button, it works for me:

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/0fe48c1b-8cd1-4fb4-8d02-5eb116e6f74f" />

That page domain is `footybite.to`, the `totalsportek1000.com##+js(prevent-window-open)` filter is not related to that page.

**Comment by punisher018** [comment]
I gave you the wrong link. I had several tabs open and got confused. Can you take a look at this website?

`https://live5.totalsportek1000.com/Manchester-United-vs-Arsenal/44987`

**Comment by kodiakhub** [comment]
Ads and multiple Anti-adblock:

`https://streamshunters.eu/soccer/manchester-united-arsenal-tnt3e1186`

To reproduce it, see:

<details><summary>GIF</summary>
<p>

![Image](https://github.com/user-attachments/assets/e0a04d85-8363-4acb-86a3-6ac8e7a0fb97)

</p>
</details>

**Comment by kodiakhub** [comment]
Also unable to click play button:

Working link:

`https://streamshunters.eu/football/new-orleans-saints-jacksonville-jaguars-tnt3e11e0?l=534716040`

```adb
cdn256.xyz###overover
cdn256.xyz###obrazek
```

See:

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/dd18539d-d706-477b-92e6-c51bda995cbd

</p>
</details>

**Comment by kodiakhub** [comment]
Anti-adblock:

`https://vipotv.com/`

**Comment by kodiakhub** [comment]
Popup:

`https://ihdstreams.cv/Embed/nfl/ch1.php`

<img width="1278" height="174" alt="Image" src="https://github.com/user-attachments/assets/ef16f9d3-023f-460d-8bba-dc35f042d18c" />

**Comment by kodiakhub** [comment]
Popup:

`https://powerover.site//total/stream1.php`

<details><summary>Screenshot</summary>
<p>

<img width="1273" height="183" alt="Image" src="https://github.com/user-attachments/assets/12b13acd-3296-43c3-8c2d-8e1985f1344d" />

</p>
</details>

`https://kakarotfoot.ru/yu/3/1`

<details><summary>Screenshot</summary>
<p>

<img width="1275" height="180" alt="Image" src="https://github.com/user-attachments/assets/2bbdedb3-c7bc-46fa-a50f-90113756beb7" />

</p>
</details>

`https://e2link.link/ch.php?id=1`

<details><summary>Screenshot</summary>
<p>

<img width="1279" height="178" alt="Image" src="https://github.com/user-attachments/assets/81e21d3b-9b9c-4ab3-a28d-0d97d33c401c" />

</p>
</details>

`https://voodc.com/embed/1/85818b96a28a9984847a8597a28f98858482.html`

<details><summary>Screenshot</summary>
<p>

<img width="1276" height="144" alt="Image" src="https://github.com/user-attachments/assets/6ce7c74f-9c32-41cd-a3a0-3b5a24ea368a" />

</p>
</details>

**Comment by stephenhawk8054** [comment]
Next time you can just give the links. We'll tell you if we need screenshots.

**Comment by punisher018** [comment]
popup
`https://www.btvsports.my/stream2`
`https://cr7-soccer.store/cr3/005.php`
`https://www.pelotalibrevivo.net/en-vivo/capo-deportes.php`

**Comment by kodiakhub** [comment]
Popup:

`https://nativesurge.net/nfl-v-redzone/`

**Comment by ghost** [comment]
The domain is with .is at the end now (footybite.is). Maybe the title of the issue can be changed.

**Comment by punisher018** [comment]
Pop up

`https://www.redditsoccerstreams.name/br6/`

**Comment by kodiakhub** [comment]
Popup:

`https://streamcenter.xyz/embed/ch49.php`
