### ISSUE TITLE
stake.com: popups

### ISSUE THREAD

**Issue by BIGtrevorb** [uBlockOrigin/uAssets#24816]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://stake.com/?c=erF81PQG`

### Category

popups

### Description

This is a pop up from eztv

### Other extensions used

I use Windscribe vpn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/376fd1ca-9c50-4ff8-a458-8b1c1cf8f951)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 155989
 cosmetic: 47716
 scriptlet: 20600
 html: 1899
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39740-118, now
  ublock-badware: 10307-6, now
  ublock-privacy: 1040-4, now
  ublock-unbreak: 2524-1, now
  ublock-quick-fixes: 150-2, now
  easylist: 87910-172, now
  easyprivacy: 53074-61, now
  urlhaus-1: 29415-0, never
  plowe-0: 3558-997, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1129 ms (selfie)
 maxAssetCacheWait: 676 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  cloudflareinsights.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Give original link where you see the issue.

**Comment by BIGtrevorb** [comment]
Here is the website: https://eztv.tf/home

I think it is an overlay on most of its pages.  It appears and then when I
click the page and the pop up opens in a new tab, I can go back to the page
and it no longer pops up.  However, if I wait like 30 seconds and click
again on the page, it pops up again.  If I do get to another page on the
website, the process will happen again.  Hope that makes sense.


Cheers
Trevor Baker
Executive Director
403-701-1687

https://experiorfinancial.com/

*What does Experior Do For Canadians?*

https://hi.switchy.io/canadaoverviewunlicensed



*Why Are Agents Leaving Their Companies To Join Experior Canada???*

*https://hi.switchy.io/10reasonswhyexperior*
<https://hi.switchy.io/10reasonswhyexperior>


*Why Are Agents Leaving Their Companies To Join Experior USA???*

*https://hi.switchy.io/8reasonswhyexperiorusa*
<https://hi.switchy.io/8reasonswhyexperiorusa>


*CEO Explains Why Experior Is **THE IMO* *of the Future!!!*

*https://api.vadoo.tv/landing_page?vid=MKM_A8TY4pkFUeGmB3WEnimzsgZgLiFp*
<https://api.vadoo.tv/landing_page?vid=MKM_A8TY4pkFUeGmB3WEnimzsgZgLiFp>
