### ISSUE TITLE
aliagents.ai: breakage

### ISSUE THREAD

**Issue by Ramzansmith** [uBlockOrigin/uAssets#24811]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://Aliagents.ai 
https://api.aliagents.ai/api/v1/acitivty
```

### Description

The global ticker of the website doesn't work when UBO is enabled. The filter /api/v1/activity is getting blocked

### Other extensions used

NIL

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image (7)](https://github.com/user-attachments/assets/c94b21dd-d1d9-48ad-8522-199ba287f30a)
![image (3)](https://github.com/user-attachments/assets/db351cdd-b419-41ea-a914-4f8b1d320752)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by Ramzansmith** [comment]
There is problem in the checklist 
![image](https://github.com/user-attachments/assets/01f1dd34-93bd-4bb2-a177-e9f016cf667a)

**Comment by stephenhawk8054** [comment]
Don't remove the troubleshooting information.

Open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here

---

Also how can I reproduce the issue?

This is my screen when I accessed `https://aliagents.ai/`

![image](https://github.com/user-attachments/assets/9abc18c8-de03-44b5-940c-b9b70e0570a9)

**Comment by Ramzansmith** [comment]
you need password to access the site . Its closed  beta now . please use Password _**`GTAVI`**_ at the bottom to access the site . 

Here is the troubleshooting information after accessing the site 
==================================================================
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 156149
 cosmetic: 47716
 scriptlet: 20600
 html: 1899
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39740-118, now
  ublock-badware: 10307-6, now
  ublock-privacy: 1040-4, now
  ublock-unbreak: 2524-1, now
  ublock-quick-fixes: 150-2, now
  easylist: 87910-172, now
  easyprivacy: 53074-61, now
  urlhaus-1: 29575-0, now
  plowe-0: 3558-997, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 287 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  aliagents.ai: 1
  googletagmanager.com: 1

==============================With UBO ON  ====================================

![image](https://github.com/user-attachments/assets/17b5d4f6-6997-4f87-b2bb-3bb2c25b373c)


===========================After turning off UBO=======================================
![image](https://github.com/user-attachments/assets/21e7fa07-89bb-4ca6-add8-26b450778acc)

**Comment by stephenhawk8054** [comment]
Caused by `/api/v1/activity|$xhr` in EasyPrivacy

@ryanbr

**Comment by Ramzansmith** [comment]
@stephenhawk8054  Thankyou for the resolution.  i have a simple question whats the expected time frame this changeset gets included in the new ublock or is it that the temporary fix that will get verified and then pushed globally .

**Comment by stephenhawk8054** [comment]
The filter lists will be auto-updated to users in about 5-6 hours.
