### ISSUE TITLE
hepsiburada.com: privacy

### ISSUE THREAD

**Issue by xqtp** [uBlockOrigin/uAssets#24819]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hepsiburada.com/ara?q=erkek%20ti%C5%9F%C3%B6rt`

### Category

privacy

### Description

is it possible to use href-sanitizer here? see screenshot.
The "Reklam" products first redirect you to adservice.hepsiburada.com and then you go to the real page.

### Other extensions used

Bitwarden
Simple Translate
Search by Image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-08-08 11_48_04](https://github.com/user-attachments/assets/a571a80a-10b7-4a59-874e-7b2b84003aff)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 130184
 cosmetic: 125633
 scriptlet: 31852
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
  TUR-0: null
 added:
  https://raw.githubusercontent.com/xqtp/List-TR/master/List-TR.txt: 982-10, 1h.14m
  adguard-spyware-url: 1635-123, now
  fanboy-cookiemonster: 51482-232, now
  ublock-cookies-easylist: 1508-0, now
  fanboy-social: 16796-2, now
  easylist-annoyances: 4688-22, now
  easylist-chat: 205-0, now
  easylist-newsletters: 7506-27, now
  easylist-notifications: 3468-88, now
  ublock-annoyances: 5976-29, now
 default:
  user-filters: 58-0, never
  ublock-filters: 39591-114, now
  ublock-badware: 10354-6, now
  ublock-privacy: 1045-2, now
  ublock-unbreak: 2465-1, now
  ublock-quick-fixes: 128-2, now
  easylist: 87938-193, now
  easyprivacy: 53077-301, now
filterset (user): [array of 61 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1501 ms
 maxAssetCacheWait: 766 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 58
 network:
  hepsiburada.com: 25
  adform.net: 1
  ads-twitter.com: 1
  creativecdn.com: 2
  facebook.net: 1
  featuregates.org: 3
  google-analytics.com: 1
  googletagmanager.com: 3
  googletagservices.com: 1
  hepsiburada.net: 10
  hotjar.com: 1
  ssevt.com: 1
  statsigapi.net: 6
  useinsider.com: 1
  webtrekk.net: 1
 extended:
  ##.google-ad:not(.testAd)
  ##.footer__link--social
  ##.footer__social-icon
  ##.sponsored-merchant-tab
```
</details>

**Comment by stephenhawk8054** [comment]
Do you want to hide the ads products?

**Comment by mapx-** [comment]
hiding the ads ("Reklam")

```
hepsiburada.com##.hepsiads-src-universal-partials-SponBrands-styles-SponBrand__root
hepsiburada.com##li[class^="productListContent-"]:has([data-test-id="product-sponsored-label"])
```
