### ISSUE TITLE
suamusica.com.br: breakage

### ISSUE THREAD

**Issue by Rafatrl** [uBlockOrigin/uAssets#24824]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.suamusica.com.br/`

### Category

breakage

### Description

I try to log in and I get a loading loop. When I disable ublock the site works.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/cec8f36b-e868-4c87-8ddc-2344e8fb4c2f)

![image](https://github.com/user-attachments/assets/979dd706-b5e1-491c-9053-42bef630e8da)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 157530
 cosmetic: 51831
 scriptlet: 22517
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 87938-597, 42m Δ
  easyprivacy: 53077-664, 42m Δ
  plowe-0: 3559-0, now
  spa-1: 5871-15, now
  ublock-badware: 10354-6, 42m Δ
  ublock-filters: 39591-287, 42m Δ
  ublock-privacy: 1045-2, 1h.35m Δ
  ublock-quick-fixes: 128-0, 42m Δ
  ublock-unbreak: 2465-3, 42m Δ
  urlhaus-1: 29575-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8324 ms (selfie)
 maxAssetCacheWait: 171 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  suamusica.com.br: 4
  doubleclick.net: 5
  google.com: 9
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  navdmp.com: 1
  spot.im: 5
  youtube.com: 5
 extended:
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
suamusica.com.br##+js(set, gtag, noopFunc)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Rafatrl** [comment]
Login problem has been resolved, now I can't open any album because I'm
stuck in a loop redirecting to this page:
https://www.suamusica.com.br/error-report

[image: image.png]

Em qui., 8 de ago. de 2024 às 09:42, stephenhawk8054 <
***@***.***> escreveu:
