### ISSUE TITLE
hey.link: badware

### ISSUE THREAD

**Issue by MEtICaRT** [uBlockOrigin/uAssets#24828]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
http://hey.link/0iEoc/#BOS
```

### Description

This link is being shared on YouTube bot channels, and when you open it, it appears to be a basic scam involving girls. If you click on the button on the website, it redirects you to `youtube.com`.

Due to my current setup, I'm unable to fully analyze the redirection process or test it using a mobile user agent. 

If someone could check this and verify if it's actually malicious, I would really appreciate it.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
Redirect chain:
```
https://www.kissablepopsyv.click/go/f40c8323-0e1c-426c-833a-06b525cbb855?&utm_medium=social&utm_source=heylink.me
https://kissablepopsyv43.com/?utm_source=DJ2HjEVBT2Ejse&utm_campaign=bw
https://kissablepopsyv43.com/?a=2014692&cr=65938&lid=40448&mh=UXlVenNFdkVNVE5Wb2RUV0FLVHlxZ3ltUG9MQnFHZGNCbVhSVGxiLTM1Nzg1&mmid=4034&p=0&rf=&rn=zc4ZodGUys4WmdeVEhG&t=bw
https://kissablepopsyv43.com/go/?a=2014692&cr=65938&lid=40448&mh=S01VTHNFekVHVGdWUHBDb2tlY2x6cGxFQnhsS2RQcUNOQXpyc0tSLTM1Nzg1&mmid=4034&p=0&rf=&rn=zc4ZodGUys4WmdeVEhG&t=bw
```
The malicious buttons in the third requests are blocked by `##html[lang] > body.ishome:not([id]) > div.adult:not([id]) + main.main:not([id])`

Last request is blocked by `^mh=*&mmid=$doc,script`
