### ISSUE TITLE
lol.ps: breakage

### ISSUE THREAD

**Issue by jongho1202** [uBlockOrigin/uAssets#24827]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lol.ps/`

### Category

breakage

### Description

when open page 
page is blank

### Other extensions used

x

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 177141
 cosmetic: 93940
 scriptlet: 40414
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/SlowMemory/List-KR/raw/master/filter.txt: 0-0, never
  adguard-generic: 83887-518, now
 default:
  user-filters: 3201-47, never
  KOR-1: 5061-44, now
  easylist: 87939-2692, now
  easyprivacy: 53077-802, now
  plowe-0: 3559-52, now
  ublock-badware: 10386-118, now
  ublock-filters: 39600-3738, now
  ublock-privacy: 1044-4, now
  ublock-quick-fixes: 128-8, now
  ublock-unbreak: 2466-87, now
  urlhaus-1: 29575-0, 1h.9m
filterset (user): [array of 3201 redacted]
trustedset:
 added: [array of 63 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 4 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 105 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  lol.ps: 1
  btloader.com: 1
  cloudflareinsights.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  kueezrtb.com: 1
  primis.tech: 2
```
</details>

**Comment by mapx-** [comment]
> user-filters: 3201-47

Maybe it's a wrong a custom filter.
Reset uBO to defaults (before resetting backup your settings / filters), then test again
