### ISSUE TITLE
empire-streamz.fr: [unknown]

### ISSUE THREAD

**Issue by Gryliix** [uBlockOrigin/uAssets#24820]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://empire-streamz.fr/film/Bad-Boys-Ride-or-Die-en-streaming-hd/8412c162a1a5226533631e0091967777`

### Category

Streaming

### Description

For a few days now, the site has been detecting Ublock. I'm letting you know to see if it would be possible to correct it.

### Other extensions used

Nothing

### Screenshot(s)

![ublock](https://github.com/user-attachments/assets/5c092c2b-1b75-4918-ab70-fa7cd900a349)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 173821
 cosmetic: 54415
 scriptlet: 22183
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39591-341, 12m Δ
  ublock-badware: 10354-6, now
  ublock-privacy: 1045-2, now
  ublock-unbreak: 2465-0, now
  ublock-quick-fixes: 128-0, 13m Δ
  easylist: 87938-609, now
  easyprivacy: 53077-650, now
  urlhaus-1: 29575-0, now
  plowe-0: 3558-0, now
  FRA-0: 24841-309, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 294 ms (selfie)
 maxAssetCacheWait: 27 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  brittlesturdyunlovable.com: 4
 extended:
  ##+js(set-constant, empire.pop, undefined)
  ##+js(set-constant, empire.direct, undefined)
  ##+js(set-constant, empire.directHideAds, undefined)
  ##+js(trusted-replace-node-text, script, '/data: \[.*\],/', 'dat…
  ##+js(adjust-setTimeout, (!1), *)
  ##+js(no-window-open-if)
  ##+js(no-xhr-if, pagead2.googlesyndication.com)
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed here: https://github.com/uBlockOrigin/uAssets/commit/60c421ded82ff6097defd6b9c19ae5acfa155af1

**Comment by Gryliix** [comment]
I just tried it doesn't work. What should I do then? Will it be fixed or do I have to do an update?

**Comment by Gryliix** [comment]
Sorry if my question is stupid.

**Comment by Gryliix** [comment]
![image](https://github.com/user-attachments/assets/c05ac451-144c-406e-b869-f2c580ee0346)
I did this but it doesn't change anything
@stephenhawk8054

**Comment by stephenhawk8054** [comment]
Can you go to `chrome://extensions` page (type in URL bar) and screenshot it here?

**Comment by Gryliix** [comment]
> Can you go to `chrome://extensions` page (type in URL bar) and screenshot it here?

![image](https://github.com/user-attachments/assets/79e2c0af-5702-4afb-a2b2-8f06f63830c3)

**Comment by Gryliix** [comment]
If you want vocal discord I can

**Comment by stephenhawk8054** [comment]
Can you turn off all other extensions (except uBO), restart the browser, open new tab and test again?

**Comment by Gryliix** [comment]
> Can you turn off all other extensions (except uBO), restart the browser, open new tab and test again?

![image](https://github.com/user-attachments/assets/23ec2a66-c690-4469-96e5-881345c74bab)
![image](https://github.com/user-attachments/assets/85f0c132-3bb1-4a36-b2f1-d6dda66c3870)

**Afterwards, maybe I did something wrong? The fix you made, I have to add it somewhere or is it automatic?**

**Comment by stephenhawk8054** [comment]
Can you continue adding this filter?

```adb
@@||brittlesturdyunlovable.com/get/$script,3p,domain=empire-stream.*|empire-streaming.*|empire-streamz.*
```

Then open new tab and test again?

**Comment by Gryliix** [comment]
> Can you continue adding this filter?
> 
> ```
> @@||brittlesturdyunlovable.com/get/$script,3p,domain=empire-stream.*|empire-streaming.*|empire-streamz.*
> ```
> 
> Then open new tab and test again?

![image](https://github.com/user-attachments/assets/4602b748-77f4-4e3b-a282-3a23d049e0fc)
![image](https://github.com/user-attachments/assets/54d096cc-7afb-4dd2-a730-dbe4ad5f1e58)

**It works! Thank you! :) you are so fast to solve problems, incredible. Thanks again!!**

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, in this site `https://empire-anime.com/plateforme?t=serie&s=jerherktk`, with the filters at commit https://github.com/uBlockOrigin/uAssets/commit/9fc5dfef82d54503c59390fbfa41d573ba9b990e , there's an issue I don't know how to solve with `nowoif`

1. Open `https://empire-anime.com/plateforme?t=serie&s=jerherktk`
2. Select `Episode 1` at the right side
3. Select `Avec de la pub`
4. Select `VF`
5. Select `Rapide`
6. There's a countdown bar, click on `Continuer` -> A popup occur which is blocked by `nowoif`. However, the video player will not start until I switch to other tab and switch back (it's like the site checks if the popup tab is opened correctly or not)

**Comment by gorhill** [comment]
I think they use a `visibilitychange` handler to figure out whether the popup is opened or not, in `/build/plateforme.2c9f1ef9.js`:

```js
 document.addEventListener("visibilitychange", (function() {
                    document.hidden ? H(!0) : H(!1)
                }
```

If you put a breakpoint at `document.hidden` line, you can see the property changes in real time according to whether the tab is active or not.

**Comment by stephenhawk8054** [comment]
@x-R0b0T-x Switch to the other tab and switch back
