### ISSUE TITLE
softzspot.com: badware

### ISSUE THREAD

**Issue by MEtICaRT** [uBlockOrigin/uAssets#24821]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
softzspot.com
```

### Description

I came across a website that supposedly offers cracked software for free. When I tried to open it, NextDNS's AI Threat Detection blocked it. I decided to open the site in a virtual machine instead and attempted to download Affinity Photo and Premiere Pro. After clicking the 'Download' button, I was redirected to a download page with the correct title matching the software I wanted. However, the file that actually downloaded was a small and very suspicious .msi file.

When I opened the .msi file, it claimed to be WinRAR. But after a quick analysis on VirusTotal, the file was flagged as malicious. Furthermore, VirusTotal also marked the website itself as malicious. I've included some screenshots below.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="940" alt="image" src="https://github.com/user-attachments/assets/5f595097-9d1d-4754-98b6-64a37857e356">
<img width="190" alt="image" src="https://github.com/user-attachments/assets/91171509-6371-4d96-953e-6a06156b70a1">
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/c449738d-abae-4cc2-805c-0f8a8269d251">
<img width="295" alt="image" src="https://github.com/user-attachments/assets/c55e1801-33ce-4b88-8140-512926018550">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
Redirect chain

```
https://afiletoget.click/go.php?a_aid=648adb2ebbf11&fn=Affinity%20Photo%202.5.3%20Crack%20Free%20Download%20Full%20Version%202024
https://track.redis08.sbs/go/19a45436-cb73-4be8-8e51-8ee0e9a6e90d?affiliate=648adb2ebbf11&channel=&keyword=Affinity%20Photo%20%20Crack%20Free%20Download%20Full%20Version%20&clickid=
https://filexstorage.site/d/VILHMQL?title=Affinity%20Photo%20%20Crack%20Free%20Download%20Full%20Version&tracker=F51a8R3s17zNQgRZvKVNFV
https://jourl.live/?xwuxin=ef34522cd1bb090c8b23322f8d32a324&ayai=TudfVZsMYDbTlnOKZrhlg2IHOyP5CQF1oPsTROfk%2Bji9AA8BLFDrNTgicQC2Xy9nz%2Fh22KQSLnAkhnvOlEQ7afs7%2FHiRSX8pdh6kmnG5j6P16ETJzdMIj9KCBwTFa9GBFJSEVE66KPgkAs3aCOaUHhKiWrVqjURWY0Bgp%2FGl6rbwJwS%2FQPSvFmYqEAoDF49D&trck=F51a8R3s17zNQgRZvKVNFV&src=
https://sleetposition.website/julk87?click_id=4&o=235&s5=F51a8R3s17zNQgRZvKVNFV&title=AffinityPhotoCrackFreeDownloadFullVersion&s1=140594&s2=0&s3=Windows_10|Firefox&s4=filexstorage.site&t=download_v5&c2=MA%3D%3D
https://funfilenow.com/locatefile/AffinityPhotoCrackFreeDownloadFullVersion/140594/0/Windows_10|Firefox/filexstorage.site/F51a8R3s17zNQgRZvKVNFV/4?t=download_v5&rr=59081168&c2=MA==
```

@Yuki2718 please take a look

**Comment by stephenhawk8054** [comment]
We are having

```adb
^s1=*&click_id=$doc
```

so maybe another

```adb
^click_id=*&s1=$doc
```

would be good?

**Comment by Yuki2718** [comment]
Maybe
