### ISSUE TITLE
amp-lasexta-com.cdn.ampproject.org: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#24823]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://amp-lasexta-com.cdn.ampproject.org/v/s/amp.lasexta.com/programas/al-rojo-vivo/joaquim-bosch-aclara-puigdemont-podria-votar-investidura-illa-carcel_2024080766b3752476ed0d000127ad35.html?amp_js_v=0.1&amp_gsa=1`

### Category

[unknown]

### Description

I cannot scroll and the site appears darkened when the uBlock Origin extension is enabled.

### Other extensions used

aapbdbdomjkkjkaonfhkkikfgjllcleb : Traductor de Google : version 2_0_15
ahfgeienlihckogmohjhadlkjgocpleb : Chrome Web Store : version 0_2
bmnlcjabgnpnenekpadlanbbkooimhnj : Honey: Automatic Coupons & Rewards : version 16_6_3
cidlcjdalomndpeagkjpnefhljffbnlo : Toggle JavaScript : version 2_0
cjpalhdlnbpafiamejdnhcphjbkeiagm : uBlock Origin : version 1_59_0
cnpniohnfphhjihaiiggeabnkjhpaldj : Image Downloader : version 3_4_2
dhdgffkkebhmkfjojejmpbldmpobfkfo : Tampermonkey : version 5_2_3
dnhpnfgdlenaccegplpojghhmaamnnfp : Augmented Steam : version 4_0_1
efkkjffdefaaioagghcaflicdajfhceo : Web Timer : version 1_4_9
eignhdfgaldabilaaegmdfbajngjmoke : Black Menu for Google™ : version 25_42_1
ekhbcipncbkfpkaianbjbcbmfehjflpf : descargador de videos - CocoCut : version 3_31
emehklffcaphknhhfhadkjhpfapcbpco : Strong Password Generator : version 1_6
gdijeikdkaembjbdobgfkoidjkpbmlkd : Google Play Películas : version 1_629_0
ghbmnnjooekpmoecnnnilnnbdlolhkhi : Documentos de Google sin conexión : version 1_62_0
gppongmhjkpfnbhagpmjfkannfbllamg : Wappalyzer - Technology profiler : version 6_10_70
hgeljhfekpckiiplhkigfehkdpldcggm : Auto Refresh Plus | Page Monitor : version 8_0_9
hhljghnmjahiaofikeljkjnhbeoiclbh : OSI: Servicio AntiBotnet : version 1_6_1
hmjkmjkepdijhoojdojkdfohbdgmmhki : Google Keep: notas y listas : version 4_24312_540_1
icncamkooinmbehmkeilcccmoljfkdhp : Wolfram|Alpha (Official) : version 2_0
idmnciiknelklflhdlnkokcoihkidkln : Dark Space : version 2
jhknlonaankphkkbnmjdlpehkinifeeg : Formularios de Google : version 0_8
jjicbefpemnphinccgikpdaagjebbnhg : CSFloat Market Checker : version 4_3_1
kdbmhfkmnlmbkgbabkdealhhbfhlmmon : SteamDB : version 4_5
kenfcfndncbbggmafjjeihkdclggbojn : Player para ver Movistar+ : version 1_9_4_86
knaodoefkjbgmmilogebghadhmnphjih : Twitch Enhancer : version 4_0_14
lpcaedmchfhocbbapmcbpinfpgnhiddi : Extensión de Google Keep para Chrome : version 4_24312_540_1
mcbpblocgmgfnpjjppndjkmgjaogfceg : Captura de página completa - FireShot : version 1_12_18
meagmjlgkihmljnchdjagbcgfclobkho : Trustpilot : version 1_101_0
mfengiknfnndchbhjmgjjffjndklkpcm : Remove YouTube End Cards & End Screen Videos : version 1_0_4
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
mkaakpdehdafacodkgkpghoibnmamcme : Dibujos de Google : version 1_1
mmioliijnhnoblpgimnlajmefafdfilb : Shazam: identifica música desde tu navegador : version 2_2_0
mmpokgfcmbkfdeibafoafkiijdbfblfg : Merge Windows : version 2_1_0_1
mnjggcdmjocbbbhaepdhchncahnbgone : SponsorBlock para YouTube - Omitir Sponsors : version 5_7
nakplnnackehceedgkgkokbgbmfghain : Fakespot Fake Amazon Reviews and eBay Sellers : version 1_3_3
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_21
nmmhkkegccagdldgiimedpiccmgmieda : Sistema de pagos de Chrome Web Store : version 1_0_0_6
oeopbcgkkoapgobdbedcemjljbihmemj : Checker Plus for Gmail™ : version 24_4_2
ponfpcnoihfmfllpaingbgckeeldkhle : Enhancer for YouTube™ : version 2_0_126

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 158611
 cosmetic: 54620
 scriptlet: 22517
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87938-611, 2m Δ
  easyprivacy: 53077-2, now
  plowe-0: 3559-629, now
  spa-0: 4071-178, 12m
  spa-1: 5871-28, now
  ublock-badware: 10354-6, 2m Δ
  ublock-filters: 39591-290, 2m Δ
  ublock-privacy: 1045-2, 2m Δ
  ublock-quick-fixes: 128-1, 2m Δ
  ublock-unbreak: 2465-23, 2m Δ
  urlhaus-1: 29575-0, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 189 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  ampproject.org: 4
  atresmedia.com: 2
  imasdk.googleapis.com: 2
  richaudience.com: 1
 extended:
  ##AMP-AD
  ##amp-ad
  ##amp-embed[type="taboola"]
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by rodrigosambadesaa** [comment]
In the new Chrome profile after I accept cookies the site works correcly, so I'm going to change the settings for this in my main Chrome profile.

**Comment by mapx-** [comment]
@ryanbr 

`@@||cdn.ampproject.org/*/amp-consent-$script,domain=amp-lasexta-com.cdn.ampproject.org`

ELC issue
