### ISSUE TITLE
filmweb.pl: breakage

### ISSUE THREAD

**Issue by premiumsmart** [uBlockOrigin/uAssets#24834]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.filmweb.pl/video/Zwiastun/Borderlands+Zwiastun+nr+2+polski-69624`

### Category

breakage

### Description

The trailer cannot be watched because it is blocking the player.

### Other extensions used

I don't care about cookies, Polska Ciasteczkowa

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/823ff92e-0d02-432b-8a27-687d85570769)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 123
filterset (summary):
 network: 620764
 cosmetic: 221444
 scriptlet: 33286
 html: 0
listset (total-discarded, last-updated):
 added:
  https://alleblock.pl/alleblock/alleblock.txt: 94-0, now
  https://easylist-downloads.adblockplus.org/easylistpolish.txt: 4510-180, now
  https://easylist.to/easylist/easylist.txt: 87945-549, now
  https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter.txt: 155490-213, now
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-online.txt: 15927-0, now
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt: 300396-225, now
  https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 24243-124, now
  https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt: 1117-0, now
  https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt: 15431-387, now
  https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt: 599-599, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  POL-0: 8758-9, now
  POL-2: 1280-208, now
  easylist: 87945-87945, now
  easyprivacy: 53081-663, now
  plowe-0: 3559-1589, now
  ublock-badware: 10404-6, now
  ublock-filters: 39604-426, now
  ublock-privacy: 1044-4, now
  ublock-quick-fixes: 128-0, now
  ublock-unbreak: 2466-22, now
  urlhaus-1: 27255-15816, now
filterset (user): [empty]
trustedset:
 added: [array of 67 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 7357 ms (selfie)
 maxAssetCacheWait: 593 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  filmweb.pl: 2
  clarity.ms: 1
  fwcdn.pl: 1
  gemius.pl: 1
  googletagmanager.com: 1
  nsaudience.pl: 1
  pushpushgo.com: 2
 extended:
  ##.sitemap__socialLogos
  ###didomi-host
  ##+js(remove-node-text, script, window.open)
  ##+js(abort-current-script, addEventListener, /faBar[\s\S]*?inse…
  ##+js(nano-remove-elements-onready, #skyBanner)
  ##+js(set-constant, rodo.waitForConsent, noopPromiseResolve)
  ##+js(set-constant, rodo.validateStoragePurpose, noopPromiseReso…
  ##+js(set-constant, consentManagerIsOn, false)
  ##+js(set-constant, rodo.checkIsDidomiConsent, noopFunc)
  ##+js(remove-class, rodo, body.rodo)
  ##+js(abort-current-script, IRI, Adblock)
  ##+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCg…
  ##+js(abort-on-property-read, webPushPublicKey)
  #@#+js(abort-current-script, decodeURIComponent, newAdblockBoard…
  #@#+js(no-setTimeout-if, notDetected)
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, disable any other extension, test again
