### ISSUE TITLE
library.jhu.edu: breakage

### ISSUE THREAD

**Issue by ellequelle** [uBlockOrigin/uAssets#24836]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.library.jhu.edu/`

### Category

breakage

### Description

The page loads but immediately vanishes. Page works correctly when cosmetic filtering is disabled.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 195239
 cosmetic: 249901
 scriptlet: 53040
 html: 2158
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83941-4176, now
  curben-phishing: 546-2, 20m
  adguard-social: 23259-52, now
  adguard-cookies: 30833-49, now
  adguard-popup-overlays: 27748-995, 1h.22m
  adguard-mobile-app-banners: 5396-25, now
  adguard-other-annoyances: 14860-405, now
  adguard-widgets: 2633-14, now
  easylist-annoyances: 4686-328, now
  easylist-chat: 205-17, now
  fanboy-cookiemonster: 51483-3973, now
  easylist-newsletters: 7507-569, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39757-118, 20m Δ
  ublock-badware: 10406-6, 20m Δ
  ublock-privacy: 1039-4, 20m Δ
  ublock-unbreak: 2525-1, 20m Δ
  ublock-quick-fixes: 134-2, 20m Δ
  easylist: 87945-2269, 20m Δ
  easyprivacy: 53081-157, 20m Δ
  urlhaus-1: 27255-0, 20m
  plowe-0: 3559-1382, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14884 ms (selfie)
 maxAssetCacheWait: 409 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 no-cosmetic-filtering: true
 network:
  googletagmanager.com: 3
 extended:
  ##div.eupopup
  ##.icon-flickr
```
</details>

**Comment by mapx-** [comment]
add

`library.jhu.edu#@#div.eupopup`

@ryanbr ELC issue
