### ISSUE TITLE
[nsfw] fightodds.io: ads

### ISSUE THREAD

**Issue by unreality1490** [uBlockOrigin/uAssets#24839]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fightodds.io/`

### Category

ads

### Description

It's just a single ad. Sometimes does not appear on first visit, but appears to always appear upon refresh. Hopefully I did the reporting right. I did my best to confirm all the prerequisites.

Question: Are you guys aware that the final checkboxin the reporting form says "I did not answer truthfully to ALL the above checkboxes." ? Because that delayed my submission by longer than it took for me to verify proper submission. In my opinion, that should say "I answered truthfully to ALL the above checkboxes." Thanks for your time.

### Other extensions used

EFF Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/c047ec8f-68af-4ce1-80fc-074b996c1b51)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153960
 cosmetic: 47734
 scriptlet: 20594
 html: 1901
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39760-118, now
  ublock-badware: 10406-6, now
  ublock-privacy: 1039-4, now
  ublock-unbreak: 2525-1, now
  ublock-quick-fixes: 135-2, now
  easylist: 87945-172, now
  easyprivacy: 53081-62, now
  urlhaus-1: 27255-0, now
  plowe-0: 3559-998, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 265 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  fightodds.io: 3
  ezoic.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  revenuenetwork.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by unreality1490** [comment]
Argentina

**Comment by stephenhawk8054** [comment]
Hmm... I don't see any popups on the page:

![image](https://github.com/user-attachments/assets/cc789232-ce3e-4a72-8f8d-44de39606591)

---

> Question: Are you guys aware that the final checkboxin the reporting form says "I did not answer truthfully to ALL the above checkboxes." ? Because that delayed my submission by longer than it took for me to verify proper submission. In my opinion, that should say "I answered truthfully to ALL the above checkboxes." Thanks for your time.

Yes, that's deliberately. That's how we caught users just blindly clicking without reading the prerequisites.

**Comment by mapx-** [comment]
@unreality1490 you should scan your system for malware.

**Comment by Yuki2718** [comment]
Neither can I even with uBO turned off.
