### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by AvrahamTsaban** [uBlockOrigin/uAssets#24830]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/finance/quote/SPUU:NYSEARCA?sa=X&ved=2ahUKEwjjxIbgq-KGAxX7zgIHHe1oDfEQ3ecFegQIHxAf&comparison=NYSEARCA%3AUPRO%2CNASDAQ%3AQQQM%2CINDEXCBOE%3ASIXT&window=5Y`

### Category

breakage

### Description

price charts not showing while adguard is on

### Other extensions used

enhancer for youtube, Facebook container, VT4browsers
checked when all of them are disabed - only disabling ublock fixed the issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 130
filterset (summary):
 network: 154628
 cosmetic: 48864
 scriptlet: 20653
 html: 1909
listset (total-discarded, last-updated):
 added:
  ISR-0: 1906-3, now
 default:
  user-filters: 1-0, never
  ublock-filters: 39753-118, never
  ublock-badware: 10388-6, never
  ublock-privacy: 1039-4, never
  ublock-unbreak: 2525-1, never
  ublock-quick-fixes: 134-2, never
  easylist: 87939-172, never
  easyprivacy: 53077-62, never
  urlhaus-1: 27255-0, now
  plowe-0: 3548-989, never
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9955 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  google.com: 7
  google-analytics.com: 2
  googletagmanager.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
> price charts not showing while adguard is on

adguard ?

I cannot reproduce the issue in uBO

**Comment by AvrahamTsaban** [comment]
whoops
I intended to write ublock
I will check again

**Comment by AvrahamTsaban** [comment]
Cannot reproduce (but it was twice checked before submitting!)
