### ISSUE TITLE
my.yahoo.com: breakage

### ISSUE THREAD

**Issue by Joel0757** [uBlockOrigin/uAssets#24838]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

my.yahoo.com. Will not keep my Homepage. Keeps asking me to sign in each time and when I do requests to send me by Text or E-mail a set of numbers. UDP somehow is the cause. Please help me to find a solution.

### Category

breakage

### Description

my.yahoo.com. Will not keep my Homepage. Keeps asking me to sign in each time and when I do requests to send me by Text or E-mail a set of numbers. UDP somehow is the cause. Please help me to find a solution.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 165388
 cosmetic: 163720
 scriptlet: 36533
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 30833-1686, now
  ublock-cookies-adguard: 1511-1511, now
  fanboy-cookiemonster: 51483-19874, now
  ublock-cookies-easylist: 1511-0, now
  adguard-social: 23259-1538, now
  fanboy-social: 16798-10678, now
  adguard-popup-overlays: 27748-1828, now
  adguard-mobile-app-banners: 5396-1130, now
  adguard-other-annoyances: 14860-734, now
  adguard-widgets: 2633-90, now
  easylist-annoyances: 4686-820, now
  easylist-chat: 205-12, now
  [3 lists not shown]: [too many]
 default:
  ublock-filters: 39605-311, now
  ublock-badware: 10404-9, now
  ublock-privacy: 1044-3, now
  ublock-unbreak: 2466-24, now
  ublock-quick-fixes: 129-2, now
  easylist: 87945-14747, now
  easyprivacy: 53081-160, now
  urlhaus-1: 27255-0, now
  plowe-0: 3559-630, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1645 ms (selfie)
 maxAssetCacheWait: 1376 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  yahoo.com: 3
  scorecardresearch.com: 1
  yimg.com: 6
 extended:
  ##[data-content="Advertisement"]
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mapx-** [comment]
@Joel0757 did you try disabling completely uBO and test again ?
