### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by 1stKingSolomon** [uBlockOrigin/uAssets#24844]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bild.de/`

### Category

detection

### Description

The site loads normally, but then the scrollbar gets removed and i cant scroll the page, if i open the inspector it says something about a message but i dont see one, so the message gets blocked it seems but the site is not scrollable

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 157555
 cosmetic: 53009
 scriptlet: 22054
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 41-7, never
  ublock-filters: 39604-288, 14m
  ublock-badware: 10404-6, 14m
  ublock-privacy: 1045-2, 14m
  ublock-unbreak: 2469-0, 14m
  ublock-quick-fixes: 144-0, 14m
  easylist: 87945-566, 14m
  easyprivacy: 53077-659, 15m
  urlhaus-1: 28475-0, 15m
  plowe-0: 3559-0, 15m
  DEU-0: 7545-3, 15m
filterset (user): [array of 41 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1670 ms
 maxAssetCacheWait: 8 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  bild.de: 4
  asadcdn.com: 2
 extended:
  ###mrec
  ###superbanner
  ##a[href*="/partner/"]
  ##.ad-wrapper
  ##div:matches-css-before(content:/Anzeige/i)
  ##+js(abort-on-property-read, SmartAdServerASMI)
  ##+js(trusted-replace-node-text, script, "adBlockWallEnabled":tr…
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, disable any other extension, test again

**Comment by JobcenterTycoon** [comment]
Blocked cookie banner?

```
filterset (user): [array of 41 redacted]
```

Maybe one of your user filter causing this. The cookie banner should not be blocked, it breaks the page.

**Comment by 1stKingSolomon** [comment]
True, my bad. The Cookiebanner disables the pagescroll.
