### ISSUE TITLE
farsroid.com: detection

### ISSUE THREAD

**Issue by prouser790** [uBlockOrigin/uAssets#24849]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.farsroid.com/`

### Category

detection

### Description

This site detect ad blockers and doesn't allow to get access to any content on site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-09 at 20-37-03 فارسروید دانلود بازی و برنامه اندروید](https://github.com/user-attachments/assets/f898d77a-840d-4d32-b8b9-ffe4e14eda84)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 165623
 cosmetic: 51248
 scriptlet: 20804
 html: 1933
listset (total-discarded, last-updated):
 added:
  https://ideone.com/plain/K452p: 1229-17, now
  https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianAnnoyance.txt: 8-0, 1h.41m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, now
  https://raw.githubusercontent.com/nimasaj/uBOPa/master/uBOPa.txt: 2847-1, now
  curben-phishing: 524-4, never
  IRN-0: 3063-44, now
 default:
  user-filters: 41-1, never
  ublock-filters: 39761-118, now
  ublock-badware: 10445-10, now
  ublock-privacy: 1039-5, now
  ublock-unbreak: 2528-2, now
  ublock-quick-fixes: 140-2, now
  easylist: 87971-186, now
  easyprivacy: 53076-64, now
  urlhaus-1: 27740-0, never
  plowe-0: 3555-1000, now
filterset (user): [array of 38 redacted]
trustedset:
 added: [array of 111 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 autoUpdate: false
 cloudStorageEnabled: true
 colorBlindFriendly: true
 largeMediaSize: 1000
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5611 ms (selfie)
 maxAssetCacheWait: 2557 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 no-large-media: true
 network:
  adwisedfs.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(abort-on-property-read, ShowPopUp)
  ##+js(abort-on-property-read, faPa)
  ##+js(no-window-open-if)
```
</details>

**Comment by mapx-** [comment]
remove this list: `https://raw.githubusercontent.com/nimasaj/uBOPa/master/uBOPa.txt`

or add:

```
farsroid.com#@#*[class*="-ads "]
farsroid.com#@#*[class$="-ads"]
```

**Comment by prouser790** [comment]
> remove this list: `https://raw.githubusercontent.com/nimasaj/uBOPa/master/uBOPa.txt`
> 
> or add:
> 
> ```
> farsroid.com#@#*[class*="-ads "]
> farsroid.com#@#*[class$="-ads"]
> ```

did not work

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by prouser790** [comment]
The problem was the interference with Adblock list
I deleted it and it was fixed

Thankyou

**Comment by stephenhawk8054** [comment]
You ignore all of the prerequisites

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
> - [X] I am not using uBlock Origin along with other content blockers.

**Comment by prouser790** [comment]
all?
only persian filter list for test
