### ISSUE TITLE
forum.dji.com: breakage

### ISSUE THREAD

**Issue by theofficialgman** [uBlockOrigin/uAssets#24850]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://forum.dji.com/forum.php?mod=forumdisplay&fid=129&filter=typeid&typeid=766
```

### Description

clicking the "New Thread" button does nothing with Ublock Origin enabled. Disabling it fixes the issue.

### Other extensions used

none

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 155252
 cosmetic: 47839
 scriptlet: 22042
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87970-558, 12m Δ
  easyprivacy: 53077-641, 12m Δ
  plowe-0: 3548-0, 7d.14h.6m
  ublock-badware: 10443-6, 12m Δ
  ublock-filters: 39609-272, 12m Δ
  ublock-privacy: 1044-2, 12m Δ
  ublock-quick-fixes: 129-0, 12m Δ
  ublock-unbreak: 2470-0, 12m Δ
  urlhaus-1: 28475-0, 15h.2m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 223 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  dji.com: 1
  aliyuncs.com: 4
  djicdn.com: 1
  djiops.com: 3

```
</details>

**Comment by D4niloMR** [comment]
Test:

```adb
dji.com##+js(set, sensorsDataAnalytic201505, {})
dji.com##+js(set, sensorsDataAnalytic201505.track, noopFunc)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by theofficialgman** [comment]
Yes this appears to work.
