### ISSUE TITLE
paramountplus.com: breakage

### ISSUE THREAD

**Issue by frustrated-user-1** [uBlockOrigin/uAssets#24855]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As stated in the title

### A specific URL where the issue occurs.

```yaml
paramountplus.com
```

### Steps to Reproduce

Go to Paramount+
Try to log in
Get told there's a problem and 'try again later'
Disable uBlock Origin (and other extensions: NoScript, Cookie Autodelete) then login possible
Still won't allow login if only uBlock Origin is enabled
Setting uBlock Origin to 'disabled for this site' makes no difference, must have extension completely disabled

### Expected behavior

I expected to not have to disable extensions that protect my privacy and online safety just to use a website!

### Actual behavior

Described above

### uBO version

1.59.0

### Browser name and version

Firefox 129.0

### Operating System and version

Ubuntu 24.04

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
