### ISSUE TITLE
dicasgostosas.com: detection

### ISSUE THREAD

**Issue by DiilSilva** [uBlockOrigin/uAssets#24857]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dicasgostosas.com/pesto-de-frango-cremoso/`

### Category

detection

### Description

detecta o adblock origin 

### Other extensions used

não utilizo 

### Screenshot(s)

<
![Captura de tela 2024-08-10 092301](https://github.com/user-attachments/assets/0e8c69c8-8d6e-433f-a39b-0357fbd46a81)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 156936
 cosmetic: 51856
 scriptlet: 22516
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39617-293, 38m Δ
  ublock-badware: 10477-6, 38m Δ
  ublock-privacy: 1044-2, 38m Δ
  ublock-unbreak: 2472-0, 38m Δ
  ublock-quick-fixes: 135-0, 38m Δ
  easylist: 87989-597, 38m Δ
  easyprivacy: 53076-663, 38m Δ
  urlhaus-1: 28805-0, now
  plowe-0: 3555-0, now
  spa-1: 5872-19, now
filterset (user): [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 208 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  anitube.vip: 1
  cloudflareinsights.com: 1
  demand.supply: 1
  googletagmanager.com: 1
  waust.at: 1
 extended:
  ##.ad-1
  ##.demand-supply
  ##.ads-2
  ##+js(no-setTimeout-if, hasAdblock)
  ##+js(no-xhr-if, popads.net)
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(set-constant, detectedAdblock, noopFunc)
  ##+js(adjust-setTimeout, asdFHqwe, *, 0.001)
  ##+js(no-xhr-if, /pagead2\.googlesyndication\.com|outbrain\.com|…
  ##+js(prevent-fetch, /pagead2\.googlesyndication\.com|outbrain\.…
  ##+js(set-constant, ATESTADO, 1)
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by D4niloMR** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/issues/24575
