### ISSUE TITLE
happytime.zigcou.com: popups

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#24856]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://happytime.zigcou.com/post/652c98fb9f68ed68b1ca0444`

### Category

popups

### Description

clicking the arrow open a popup to aliexeprss

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 110
filterset (summary):
 network: 168568
 cosmetic: 218577
 scriptlet: 37217
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30841-96, now
  ublock-cookies-adguard: 1575-6, now
  fanboy-cookiemonster: 51485-4021, now
  ublock-cookies-easylist: 1575-1575, now
 default:
  user-filters: 32-4, never
  ublock-filters: 40112-553, 50m Δ
  ublock-badware: 10440-6, 50m Δ
  ublock-privacy: 1045-2, 50m Δ
  ublock-unbreak: 2475-0, 50m Δ
  ublock-quick-fixes: 133-0, 50m Δ
  adguard-mobile: 9660-14, now
  easylist: 87971-700, 50m Δ
  easyprivacy: 53075-34, 50m Δ
  urlhaus-1: 28805-0, 50m
  plowe-0: 3555-710, now
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1605 ms (selfie)
 maxAssetCacheWait: 270 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  alicdn.com: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  impactify.io: 1
  taboola.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe

```adb
happytime.zigcou.com##[class^="Post_continue_coupang"]
happytime.zigcou.com##.post-contents > div[style]:style(height: auto !important;)
```

@piquark6046 Sorry, can you check this?

**Comment by piquark6046** [comment]
Will be checked soon.
