### ISSUE TITLE
tiktok.com: breakage

### ISSUE THREAD

**Issue by FlightXamb** [uBlockOrigin/uAssets#24862]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tiktok.com/messages?lang=fr`

### Category

breakage

### Description

the textbox( in that page the one to send messages) acts normally until you send a message  or delete characters, it deletes them but when you hit send it sends everything even the deleted characters and after sending it breaks, some characters are not removed after sending the message theyre just stacked and everything, this also happens in the comments but not in the search bar. When pressing enter it just remove the content and expand the message bar you can only send if you press the send icon

### Other extensions used

privacy badger, canvas blocker, clear url, decentraleyes
i tested if all extensions are activated except ubo it works correctly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

before pressing enter to send
![image](https://github.com/user-attachments/assets/217eb674-7800-4ea0-87bf-6769a6bed533)
when pressing enter to send
![image](https://github.com/user-attachments/assets/ceda6bf5-3c53-41ea-8847-907f7b4eea0e)
excepted result
![image](https://github.com/user-attachments/assets/aeda83a1-a15b-4eef-a494-2a32b491e926)
i wasnt able to reproduce the stacking character bug but sometime it happens

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 270048
 cosmetic: 264917
 scriptlet: 53993
 html: 2168
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83887-4135, now
  adguard-mobile: 9660-57, now
  adguard-spyware-url: 1637-123, now
  adguard-spyware: 85005-1557, now
  block-lan: 70-1, now
  curben-phishing: 514-3, now
  adguard-cookies: 30841-54, now
  ublock-cookies-adguard: 1536-23, now
  fanboy-cookiemonster: 51485-3946, now
  ublock-cookies-easylist: 1536-1536, now
  adguard-social: 23267-58, now
  fanboy-social: 16830-748, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 25-0, never
  ublock-filters: 39773-118, 12m Δ
  ublock-badware: 10490-6, 12m Δ
  ublock-privacy: 1041-4, 12m Δ
  ublock-unbreak: 2533-1, 12m Δ
  ublock-quick-fixes: 143-8, 12m Δ
  easylist: 87991-2355, 12m Δ
  easyprivacy: 53095-30078, 12m Δ
  urlhaus-1: 29235-0, now
  plowe-0: 3555-1492, now
  FRA-0: 24854-625, now
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1086 ms (selfie)
 maxAssetCacheWait: 289 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 57
 network:
  tiktok.com: 6
  byteoversea.com: 1
  tiktokv.com: 47
  tiktokw.eu: 3
 extended:
  ##tiktok-cookie-banner
  ##*:style(-webkit-touch-callout: default !important; -webkit-use…
  ##+js(json-prune-fetch-response, itemList.[-].ad_info.ad_id, , p…
  ##+js(addEventListener-defuser, touchmove, .preventDefault():voi…
  ##+js(set-session-storage-item, webapp_first_open_cta, 1)
  ##+js(addEventListener-defuser, keydown)
  ##+js(addEventListener-defuser, contextmenu, preventDefault)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
