### ISSUE TITLE
yjys02.com: ads

### ISSUE THREAD

**Issue by soloadam** [uBlockOrigin/uAssets#24866]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.yjys02.com/s/dongzuo`

### Category

ads

### Description

ads

### Other extensions used

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 128
filterset (summary):
 network: 171208
 cosmetic: 66934
 scriptlet: 20928
 html: 1912
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 40231-120, now
  ublock-badware: 10488-6, now
  ublock-privacy: 1042-4, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 142-8, now
  adguard-mobile: 9660-74, now
  easylist: 87997-245, now
  easyprivacy: 53095-70, now
  urlhaus-1: 28815-0, now
  plowe-0: 3555-1071, 6m
  CHN-0: 25386-218, now
filterset (user): [array of 5 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 349 ms (selfie)
 maxAssetCacheWait: 77 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  baidu.com: 1
  googletagmanager.com: 1
  ymmiyun.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe and screenshot where the ads are in more details?
