### ISSUE TITLE
highratecpm.com: popups

### ISSUE THREAD

**Issue by MikoTom** [uBlockOrigin/uAssets#24860]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.highratecpm.com/wip5bmxmh?key=8318e171333dfe4b33267e1eacd15fd4`

### Category

popups

### Description

ublock block keeps popping up for this website, I (stupidly) downloaded a sus program last night which opened up a command prompt which I quickly closed. Tried using windows defender and malwarebytes to no avail.

### Other extensions used

Twitch Channel Points Autoclicker
Return Youtube Dislike
ChatReplay
FastFoward
Grammarly
600% Sound Volume
Tab Session Manager
BetterTTV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-10 084735](https://github.com/user-attachments/assets/d7071531-6f32-48fe-a0f1-8d1528eb654d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 156051
 cosmetic: 47748
 scriptlet: 20574
 html: 1911
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39773-118, 3m
  ublock-badware: 10479-6, 3m
  ublock-privacy: 1041-4, 3m
  ublock-unbreak: 2533-1, 3m
  ublock-quick-fixes: 139-4, 3m
  easylist: 87970-172, 3m
  easyprivacy: 53076-62, 3m
  urlhaus-1: 29235-0, 3m
  plowe-0: 3555-997, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1670 ms
 maxAssetCacheWait: 78 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-popups: true
```
</details>

**Comment by MikoTom** [comment]
popup doesn't occur on any particular website, appears randomly while on Firefox, have already scanned with windows defender and Malwarebytes to no avail

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
