### ISSUE TITLE
Funimation subtitles

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2487]
### URL(s) where the issue occurs

`https://www.funimation.com/shows/blood-c/it-is-for-thy-sake/uncut/?lang=japanese&a=1`

### Describe the issue

The subtitles are broken

### Settings

- Default settings

### Notes

It will ask you for an account. Here is a random one I created Email: `namenamenamename12349@outlook.com` Password: `Password12349~`

**Comment by okiehsch** [comment]
I am geo locked, even if I use a US-Proxy, so I can't help.

**Comment by zaphodbeebblebrox** [comment]
I got 
```
@@||mssl.fwmrm.net/p/release/latest-JS/adm/prd/AdManager.js$script,domain=funimation.com
@@||v.fwmrm.net/ad/*$script,domain=funimation.com
||mediausamns-a.akamaihd.net^$media,domain=www.funimation.com
``
but the guy who was asking about it said it didn't work for him. Can anyone else with a us IP confirm if this works or not?

**Comment by mapx-** [comment]
working for me, added

**Comment by SlippyFist** [comment]
Yeah so I'm that guy from the reddit exchange he was referring to, and this didn't work for me

**Comment by okiehsch** [comment]
Well, the problem is that it works for everybody else and finding a fix without having a problem is rather difficult ;).
