### ISSUE TITLE
channel4.com: ads

### ISSUE THREAD

**Issue by bainn41** [uBlockOrigin/uAssets#24873]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.channel4.com/programmes/24-hours-in-police-custody/on-demand/73855-009`

### Category

ADS Showing

### Description

Ads being showing whilst using UBO on Firefox. 

Tried with other browsers, still doesn't work. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 155721
 cosmetic: 47751
 scriptlet: 20584
 html: 1911
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39788-118, now
  ublock-badware: 10175-6, now
  ublock-privacy: 1041-4, now
  ublock-unbreak: 2535-1, now
  ublock-quick-fixes: 140-8, now
  easylist: 88001-173, now
  easyprivacy: 53104-62, now
  urlhaus-1: 29150-0, 25m
  plowe-0: 3555-997, now
filterset (user): [empty]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 258 ms (selfie)
 maxAssetCacheWait: 63 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 40
 network:
  channel4.com: 4
  2cnt.net: 2
  braze.eu: 3
  c4assets.com: 1
  conviva.com: 1
  demdex.net: 1
  fwmrm.net: 6
  moatads.com: 1
  mparticle.map.fastly.net: 1
  optimizely.com: 20
 extended:
  ##+js(no-xhr-if, /\/ad\/g\/1/)
```
</details>

**Comment by stephenhawk8054** [comment]
Where does the ads appear? At the start, in the middle or the end of the videos?

**Comment by stephenhawk8054** [comment]
@bainn41 @eden536 Can you test this filter?

```adb
channel4.com##+js(json-prune, adverts.breaks)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by bainn41** [comment]
That worked! you're a genius thank you. That removed the adds from the
start and throughout.

I don't mind adds but the problem with channel 4 if you mute them or change
tab, it pauses? very annoying.

Thanks again.

**Comment by eden536** [comment]
doesn't work for me
![Screenshot 2024-08-13 at 15-52-13 Watch Copshop Stream free on Channel 4](https://github.com/user-attachments/assets/7a81d2db-9f52-4fbd-b8ec-ab73fdef1d52)

**Comment by stephenhawk8054** [comment]
@eden536 Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

Also, please give exact URL where you see the issue as well.

**Comment by eden536** [comment]
I've already fixed it myself no worries

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25829

**Comment by stephenhawk8054** [comment]
@shmall03 I can't reproduce the issue. I accessed your link and video plays without ads for me. Where do you see the ads: at beginning, in the middle or at the end of the video?
