### ISSUE TITLE
hltv.org: breakage

### ISSUE THREAD

**Issue by silasmartins** [uBlockOrigin/uAssets#24874]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hltv.org/

### Category

breakage

### Description

Icons crash

### Other extensions used

Adguard
Decentraleyes
Firefox Relay

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 158431
 cosmetic: 60137
 scriptlet: 21145
 html: 1912
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40235-180, 13m Δ
  ublock-badware: 10169-7, 13m Δ
  ublock-privacy: 1042-4, 13m Δ
  ublock-unbreak: 2538-3, 13m Δ
  ublock-quick-fixes: 140-8, 13m Δ
  adguard-mobile: 9660-11, now
  easylist: 88001-246, 13m Δ
  easyprivacy: 53104-70, 13m Δ
  urlhaus-1: 29150-0, now
  plowe-0: 3555-1071, now
  spa-1: 5872-86, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1720 ms (selfie)
 maxAssetCacheWait: 321 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  hltv.org: 2
  cloudflareinsights.com: 3
  googlesyndication.com: 2
  googletagmanager.com: 2
  rtmark.net: 2
  vntsm.com: 2
 extended:
  ##.gen-firstcol-box
  ##.mid-container
  ##.night-only
  ##a:matches-attr(href=/[a-zA-Z0-9]{100,}/)
  ##body, body::before:style(background-image: unset !important;)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
> - [X] I did not answer truthfully to **ALL** the above checkboxes.
