### ISSUE TITLE
euronews.com: ads

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#24877]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.euronews.com/next/2024/08/12/turkey-suddenly-reinstates-access-to-instagram-after-more-than-a-week`

### Category

ads

### Description

For every news story on the site, there is a large gap at the top of the story from blocked ads.
I wrote to Easylist but was redirected here. 
https://github.com/easylist/easylist/issues/19778

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![aa](https://github.com/user-attachments/assets/f2fade7c-a966-4b06-8f2f-c9032143e3e2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 157151
 cosmetic: 58180
 scriptlet: 23692
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  TUR-0: 13432-11, now
  easylist: 88001-562, 1m Δ
  easyprivacy: 53104-655, 1m Δ
  plowe-0: 3555-1, now
  ublock-badware: 10173-6, 1m Δ
  ublock-filters: 39636-300, 1m Δ
  ublock-privacy: 1046-2, 1m Δ
  ublock-quick-fixes: 134-0, 1m Δ
  ublock-unbreak: 2476-3, 1m Δ
  urlhaus-1: 29155-0, 1m
filterset (user): [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 356 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  euronews.com: 1
  adobedtm.com: 3
  chartbeat.com: 2
  cloudflareinsights.com: 1
  connatix.com: 2
  demdex.net: 1
  doubleclick.net: 1
  durationmedia.net: 1
  facebook.net: 1
  geoedge.be: 1
  gscontxt.net: 1
  ml314.com: 2
  moatads.com: 1
  pixels.ai: 1
  poool.fr: 1
  privacy-center.org: 1
  qwtag.com: 1
  teads.tv: 1
  useinsider.com: 1
  vuukle.com: 6
 extended:
  ##[data-ad-name]
  ##.c-ad
  ##.js-adzone
  ##.OUTBRAIN
```
</details>

**Comment by dportvine** [comment]
Leftover.

`https://www.euronews.com/next/2025/03/02/first-ever-landing-of-a-commercial-craft-on-the-moon`

<details>
<summary>Screen</summary>

![Image](https://github.com/user-attachments/assets/6ab346e1-e30c-46a8-9936-282dcefd1e3d)
![Image](https://github.com/user-attachments/assets/b78f7a2c-fcd6-40ec-be3c-416999da7397)
</details>

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.62.0
Firefox Mobile: 136
filterset (summary):
 network: 164186
 cosmetic: 124759
 scriptlet: 31986
 html: 2615
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 23976-26, 10m
  adguard-cookies: 33457-295, 10m
  ublock-cookies-adguard: 3503-47, 10m
  ublock-annoyances: 5994-40, 12m Δ
  RUS-1: 1786-255, 10m
 default:
  user-filters: 24-0, never
  ublock-filters: 41185-119, 12m Δ
  ublock-badware: 12023-7, 12m Δ
  ublock-privacy: 2540-34, 12m Δ
  ublock-unbreak: 2621-2, 12m Δ
  ublock-quick-fixes: 313-12, 12m Δ
  adguard-mobile: 10652-95, 9m
  easylist: 69986-301, 12m Δ
  easyprivacy: 53383-148, 12m Δ
  urlhaus-1: 20495-0, 9m
  plowe-0: 3469-1004, 10m
  RUS-0: 40939-265, 12m Δ
filterset (user): [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 358 ms (selfie)
 maxAssetCacheWait: 191 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 31
 network:
  adobedtm.com: 3
  chartbeat.com: 2
  cloudflare.com: 5
  cloudflareinsights.com: 1
  demdex.net: 1
  doubleclick.net: 1
  doubleverify.com: 1
  durationmedia.net: 1
  facebook.net: 1
  geoedge.be: 1
  googletagmanager.com: 1
  ml314.com: 2
  non.li: 1
  poool.fr: 1
  privacymanager.io: 1
  qwtag.com: 1
  teads.tv: 1
  vuukle.com: 6
 extended:
  ##.c-ad
  ##.js-adzone
  ##.OUTBRAIN
  ##.c-social-share
  ###poool-fullscreen-widget
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://vk.com/share.php"]
  ##a[href^="whatsapp://send"]
  ##a[href^="https://share.flipboard.com/bookmarklet/popout?"]
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://www.facebook.com/dialog/send?"]
  ##a[href^="https://www.facebook.com/share.php?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##a[href^="https://www.reddit.com/submit?"]
  ##a[href^="whatsapp://send?text="]
  ##[data-ad-name]
  ###o-site-hr__leaderboard-wallpaper.u-show-for-xlarge:remove()
  ###didomi-host:style(visibility: hidden !important;)
```
</details>

**Comment by dportvine** [comment]
>Also `https://www.euronews.com/just-in`

<details>
<summary>Screen</summary>

![Image](https://github.com/user-attachments/assets/b581ee0e-86e2-4c29-8cb2-244f743f5b9a)

</details>

Check please.
