### ISSUE TITLE
x265rips.xyz: detection

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#24888]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://x265rips.xyz/`

### Category

detection

### Description

Detecton in homepage itself. When i disable javascript it works.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 128
filterset (summary):
 network: 419029
 cosmetic: 233099
 scriptlet: 54796
 html: 2170
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 84131-5721, now
  adguard-mobile: 9663-540, now
  adguard-spyware-url: 1637-239, now
  block-lan: 71-1, 51m
  curben-phishing: 467-1, never
  fanboy-cookiemonster: 51498-201, now
  ublock-annoyances: 5935-147, 59m Δ
  IND-0: 13475-52, now
  adguard-spyware: 87750-32478, now
  adguard-cookies: 30877-3830, now
  adguard-popup-overlays: 27782-399, now
  adguard-mobile-app-banners: 5404-27, now
  [8 lists not shown]: [too many]
 default:
  ublock-filters: 39799-300, 59m Δ
  ublock-badware: 10177-1340, 1h.1m Δ
  ublock-privacy: 1043-153, 59m Δ
  ublock-unbreak: 2538-7, 59m Δ
  ublock-quick-fixes: 135-8, 59m Δ
  easylist: 84976-24538, 59m Δ
  easyprivacy: 53116-7739, 1h.1m Δ
  urlhaus-1: 28680-11, now
  plowe-0: 3556-2276, 51m
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4869 ms (selfie)
 maxAssetCacheWait: 2197 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  x265rips.xyz: 1
  a-ads.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 3
  gyanilinks.com: 3
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
x265rips.*##+js(rmnt, script, /advanced_ads_check_adblocker|adsbygoogle\.js/)
