### ISSUE TITLE
dicasgostosas.com: detection

### ISSUE THREAD

**Issue by gabriel-batistuta** [uBlockOrigin/uAssets#24897]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

https://dicasgostosas.com/costeletas-de-frango-com-salada-de-rucula/
https://blog.dicasgostosas.com/rectube/?token=WUFmcDJmekladkNIMWlxZlEzNWY2TG5xci96cmpEM2YrL1RSbk5xVUN4UmFISzlQWnBTczNPWDN4NzhKZEdBTk9LbGgwaEo3Q25sOEdkK3BsdHgrU1ZsOWpVUGc4dTZFNWtPajhuTTBidGZFMDlhaWJUWjJLNUFzYW5SSEtmTnNLZWlsemNLbUhjdStYcHlBTWY2dUpvdEc5SG42ZzZGN0ZOL1RJWkdmVGN4WHJXeUdKYnVHOXhxQWttakxmSFR2RG1zc1ZCR2ZXdUNmaVVkN01kOVdRWDBaNkF5UXkzcUliVE82aDdlYnFERT0=

### Category

detection

### Description

The player in page detect the uBO and is not possible to see the video

scripts with ad relation in page:  
posible functions of problem: 

!function(e){e(document).ready(function(){setTimeout(function(){(function(){var e=document.createElement("div");e.innerHTML="&nbsp;",e.className="ads ad adsbox doubleclick ad-placement carbon-ads adglare";var t=!(e.style="width: 1px !important; height: 1px !important; position: absolute !important; left: -5000px !important; top: -5000px !important;");try{document.body.appendChild(e);var o=document.getElementsByClassName("adsbox")[0];if(0!==o.offsetHeight&&0!==o.clientHeight||(t=!0),void 0!==window.getComputedStyle){var n=window.getComputedStyle(o,null);!n||"none"!=n.getPropertyValue("display")&&"hidden"!=n.getPropertyValue("visibility")||(t=!0)}document.body.removeChild(e)}catch(o){}return t})()&&(e(".detectadb").show(),e(".wrap").remove())},3e3)})}(jQuery)

        (function($) {
            $(document).ready(function() {
                async function hasAdblock() {
                    const popAdsUrl = 'https://www.popads.net/js/adblock.js';
                    try {
                        await $.ajax({
                            url: popAdsUrl,
                            cache: false
                        });
                    } catch (error) {
                        $('.detectadb').show();
                        $('.wrap').remove();
                    }
                }
                setTimeout(function() {
                    hasAdblock();
                }, 3000);
            });
        })(jQuery);
    

### Other extensions used

Gifs auto play for google
Grepper
Octotree - Githube code tree
Foxy proxy
Anti-adblock blocker
Wayback machine
Enhancer for youtube
Gnome shell integration
Refined github
Search anime by screenshot
To google Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de tela de 2024-08-13 13-59-39](https://github.com/user-attachments/assets/72100dbe-b485-4583-b6db-d5c3214f579f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153507
 cosmetic: 51785
 scriptlet: 21091
 html: 1913
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39784-118, now
  ublock-badware: 10213-6, now
  ublock-privacy: 1050-4, now
  ublock-unbreak: 2540-1, now
  ublock-quick-fixes: 129-8, now
  easylist: 84920-179, now
  easyprivacy: 53119-66, now
  urlhaus-1: 28705-0, now
  plowe-0: 3556-997, now
  spa-1: 5899-85, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 146 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 1
  demand.supply: 1
  googletagmanager.com: 1
  waust.at: 1
 extended:
  ##.ad-1
  ##.demand-supply
  ##.ads-2
  ###player:style(display: block !important;)
  ##+js(no-setTimeout-if, hasAdblock)
  ##+js(no-xhr-if, popads.net)
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(set-constant, detectedAdblock, noopFunc)
  ##+js(no-xhr-if, /pagead2\.googlesyndication\.com|outbrain\.com|…
  ##+js(prevent-fetch, /pagead2\.googlesyndication\.com|outbrain\.…
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, ATESTADO, 1)
```
</details>

**Comment by huyszn** [comment]
Continue in https://github.com/uBlockOrigin/uAssets/issues/24575
