### ISSUE TITLE
winfuture.de: ads

### ISSUE THREAD

**Issue by Si13n7** [uBlockOrigin/uAssets#24891]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://winfuture.de/`

### Category

ads

### Description

I've tried different browsers and almost all filters. UBO no longer seems to have any effect on this website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-13 at 09-12-10 WinFuture de - Die ganze Welt der IT](https://github.com/user-attachments/assets/c67502bb-b3a4-4d83-b7be-d167f457d935)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 249946
 cosmetic: 304491
 scriptlet: 56045
 html: 2186
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 24060-75, now
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, 6m
  https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 515-11, now
  https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5883-10, now
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-53, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 101549-17764, now
  https://winhelp2002.mvps.org/hosts.txt: 8729-354, now
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, now
  adguard-generic: 83889-4259, now
  adguard-cookies: 30890-3825, now
  ublock-cookies-adguard: 1541-27, now
  adguard-social: 23281-796, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 5-0, never
  ublock-filters: 39762-160, 6m Δ
  ublock-badware: 10177-11, 6m Δ
  ublock-privacy: 1043-68, 6m Δ
  ublock-unbreak: 2540-7, 6m Δ
  ublock-quick-fixes: 135-8, 6m Δ
  easylist: 84913-3294, 6m Δ
  easyprivacy: 53118-627, 6m Δ
  urlhaus-1: 29340-0, now
  plowe-0: 3556-2490, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 60 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 40 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 hyperlinkAuditingDisabled: false
hiddenSettings:
 autoUpdatePeriod: 7
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 1400 ms
 maxAssetCacheWait: 755 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  adpushup.com: 1
  chartbeat.com: 2
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  html-load.com: 5
  qualitymedianetwork.de: 1
  taboola.com: 1
 extended:
  ##.adsbygoogle
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
  ###rightWrap > div.rightBx:has(> div.rightBx_btm > a[href="/beis…
  ##.topnews > .clearfix
  ##.topnews > div[class]:has(> h2 > a[href*="/special/"][href*="/…
  ##.billboard
  ##div[id^="div-gpt-ad"]
  ##[id^="div-gpt-ad-"]
  ##[id^="taboola-below"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.topnews > div:has(span:contains(/(Anzeige)|Schnäppchen|sale|(…
  ##.topnews > div:has(a:contains(/(Anzeige)|Schnäppchen|sale|(?<!…
  ###container:style(margin: auto auto!important;)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(json-prune, adtagparameter, enabled)
  ##body > div[style*="z-index"][style*="bottom"][style*="right"]
```
</details>

**Comment by Klaus1189** [comment]
+1

**Comment by Klaus1189** [comment]
How do I get update loaded?

**Comment by stephenhawk8054** [comment]
Wait about 3-4 hours and update the filter lists again.

**Comment by Klaus1189** [comment]
OK, thank you

**Comment by chrisknife** [comment]
Reloading the Filterlist did help with most of the ads.
But there are still a few left. For example on the right and if you scroll down on the newsticker, between the days.

I am unable to block those and those weren't there yesterday, just like the other ones which got fixed already.

**Comment by stephenhawk8054** [comment]
Add this filter as well:

```adb
||html-load.com/loader.min.js$domain=winfuture.de
```

**Comment by chrisknife** [comment]
Thanks, with this Filter everything is gone and the Page is usable again.
I was about to delete the Bookmark :D 

Great work!

**Comment by JobcenterTycoon** [comment]
Fixed in https://github.com/uBlockOrigin/uAssets/commit/c0feba08fd7039c813cb3c0e4c7b335640aed1d8
