### ISSUE TITLE
anitube.vip, dicasgostosas.com: detection

### ISSUE THREAD

**Issue by MathsTTU** [uBlockOrigin/uAssets#24894]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dicasgostosas.com/`

### Category

detection

### Description

I watch anime using anitube, he redirects to that 'dicasgostosas.com' and the fix on #24575 dont work either...

### Other extensions used

onetab and MAL-sync

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e8abe281-5a72-428c-8940-3c9a88980cc9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 161723
 cosmetic: 116027
 scriptlet: 28940
 html: 2184
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 67-0, 14m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 405-1, 14m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 44-44, 14m
  https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-1, 14m
  adguard-mobile: 9666-187, never
  adguard-popup-overlays: 27792-341, 14m
  adguard-mobile-app-banners: 5407-23, 14m
  adguard-other-annoyances: 14868-294, 14m
  adguard-widgets: 2639-12, 14m
  easylist-annoyances: 4706-288, 14m
  easylist-chat: 206-17, 14m
  easylist-newsletters: 7563-555, 14m
  [2 lists not shown]: [too many]
 default:
  user-filters: 947-7, never
  ublock-filters: 39765-122, 39m Δ
  ublock-badware: 10213-6, 39m Δ
  ublock-privacy: 1045-4, 39m Δ
  ublock-unbreak: 2540-1, 39m Δ
  ublock-quick-fixes: 134-8, 39m Δ
  easylist: 84915-181, 39m Δ
  easyprivacy: 53119-74, 39m Δ
  urlhaus-1: 28705-0, 14m
  plowe-0: 3556-1007, 14m
  spa-1: 5899-90, 14m
filterset (user): [array of 707 redacted]
trustedset:
 added: [array of 42 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4380 ms (selfie)
 maxAssetCacheWait: 1714 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 1
  demand.supply: 2
  googletagmanager.com: 1
  waust.at: 2
 extended:
  ##.ad-1
  ##.demand-supply
  ##.ads-2
  ##+js(no-setTimeout-if, hasAdblock)
  ##+js(no-xhr-if, popads.net)
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(set-constant, detectedAdblock, noopFunc)
  ##+js(adjust-setTimeout, asdFHqwe, *, 0.001)
  ##+js(no-xhr-if, /pagead2\.googlesyndication\.com|outbrain\.com|…
  ##+js(prevent-fetch, /pagead2\.googlesyndication\.com|outbrain\.…
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, ATESTADO, 1)
```
</details>

**Comment by huyszn** [comment]
Continue in #24575
