### ISSUE TITLE
dairyqueen.com: breakage

### ISSUE THREAD

**Issue by MDawg957** [uBlockOrigin/uAssets#24899]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dairyqueen.com/en-us/menu/`

### Category

breakage

### Description

Disabling uBO allows site to load, when it's active, it break.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 159907
 cosmetic: 140446
 scriptlet: 30505
 html: 2167
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81622-31023, now
  ublock-annoyances: 5935-171, 39m Δ
  adguard-social: 23293-929, 9m
  adguard-cookies: 30912-38, now
  adguard-popup-overlays: 27795-27795, now
  adguard-mobile-app-banners: 5408-5408, now
  adguard-other-annoyances: 14868-14868, now
  adguard-widgets: 2639-2639, now
  ublock-cookies-adguard: 1536-24, now
 default:
  user-filters: 3-0, never
  ublock-filters: 39784-437, 39m Δ
  ublock-badware: 10213-6, 39m Δ
  ublock-privacy: 1050-4, 39m Δ
  ublock-unbreak: 2540-3, 39m Δ
  easylist: 84920-239, 39m Δ
  easyprivacy: 53119-136, 39m Δ
  plowe-0: 3556-998, 9m
  urlhaus-1: 28705-0, 9m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 709 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  braze.com: 2
  cookielaw.org: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site? Do you need to sign in?

**Comment by MDawg957** [comment]
> Which country are you when accessing the site? Do you need to sign in?

I'm in the US, no sign in required.

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@MDawg957 

add

`||sdk.*.braze.com^$3p,badfilter`


AdGuard – Popup Overlays issue
@Alex-302
