### ISSUE TITLE
www.15min.lt full-screen anti-adblock overlay after opening an article and scrolling down a bit

### ISSUE THREAD

**Issue by Fruit-basket89** [uBlockOrigin/uAssets#249]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.15min.lt/naujiena/aktualu/vilniaus-zinios/saulius-skvernelis-gedimino-kalnas-bus-tvarkomas-nebe-pripuolamai-793-733424`

### Describe the issue

Full-screen overlay pops up complaining about the usage of ad-blockers. It cannot be removed with Inspect Element. Neither AdBlockPlus nor uBlock Origin works. Tried Anti-Adblock-Killer (the Tampermonkey script) but that doesn't work either. 

### Versions

- Browser/version: Chrome 55.0.2883.87 m (64-bit)
- uBlock Origin version: 1.10.4

**Comment by mapx-** [comment]
add
```
@@||15min.lt^$generichide
@@||15min.lt/*ads
@@||15minlt.adocean.pl^
```

**Comment by rjkpa** [comment]
`||static.mxstatic.com/static/mscripts/index_303.js$script,redirect=noopjs`

**Comment by uBlock-user** [comment]
try - `15min.lt##script:inject(abort-on-property-read.js, __adblock_js_test)`

**Comment by okiehsch** [comment]
Site works fine with Chrome and Firefox on my end, so I will close.
