### ISSUE TITLE
itv.com: breakage

### ISSUE THREAD

**Issue by largeruk** [uBlockOrigin/uAssets#24907]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.itv.com/watch/motogp-live/10a1452/10a1452a0016`

### Category

breakage

### Description

When I go to play a streamed video (eg [MotoGP Live - Series 4 - Episode 3 - ITVX](https://www.itv.com/watch/motogp-live/10a1452/10a1452a0016)), the adblock is not detected but nothing happens. The video will only play when uBO is disabled.

I have disabled all other extensions, reloaded the page and still the same issue.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 126
filterset (summary):
 network: 152863
 cosmetic: 47873
 scriptlet: 22042
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 84919-567, 18h
  easyprivacy: 53119-651, 18h
  plowe-0: 3556-0, 18h
  ublock-badware: 10211-6, 18h
  ublock-filters: 39629-286, 18h
  ublock-privacy: 1055-2, 18h
  ublock-quick-fixes: 132-0, now Δ
  ublock-unbreak: 2481-0, 18h
  urlhaus-1: 29340-0, 18h
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 367 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  itv.com: 1
  amplitude.com: 9
  conviva.com: 11
  googletagmanager.com: 1
 extended:
  ##+js(xml-prune, VAST > Ad, , /tserver)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

[Please respect the prerequisites](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+itv.com)

---

Continue here: https://github.com/uBlockOrigin/uAssets/issues/24517
