### ISSUE TITLE
myanimelist.net: breakage

### ISSUE THREAD

**Issue by LightningVoid** [uBlockOrigin/uAssets#24900]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://myanimelist.net/`

### Category

breakage

### Description

Whenever I try to open a different page than the default page, like by searching an show and pressing 'Enter', I never leave the default page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 103669
 cosmetic: 12111
 scriptlet: 22042
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
 default:
  user-filters: 0-0, never
  ublock-filters: 39632-286, 13m
  ublock-badware: 10211-6, 9m Δ
  ublock-privacy: 1055-2, 9m Δ
  ublock-unbreak: 2481-0, 9m Δ
  ublock-quick-fixes: 129-0, 13m
  easyprivacy: 53119-651, 9m Δ
  urlhaus-1: 28705-0, 13m
  plowe-0: 3556-0, 13m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 114 ms (selfie)
 maxAssetCacheWait: 32 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 42
 network:
  myanimelist.net: 1
  1rx.io: 1
  3lift.com: 1
  btloader.com: 1
  casalemedia.com: 1
  criteo.com: 2
  google-analytics.com: 1
  google.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 1
  googletagservices.com: 1
  pubmatic.com: 22
  sascdn.com: 1
  servenobid.com: 1
  smartadserver.com: 1
  vntsm.com: 1
  yellowblue.io: 1
 extended:
  ##[src*="/c/img/images/event/"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details? I have accessed `https://myanimelist.net/` and it looks like this to me

![image](https://github.com/user-attachments/assets/51fcdec7-daff-434f-b60a-aeae70a7f57b)

Which buttons should I click next to reproduce the issue?

**Comment by mapx-** [comment]
> easylist: null

reset uBO to defaults, do not use any other extension, test again

**Comment by LightningVoid** [comment]
@stephenhawk8054 When I go to the searchbar, type something in, and press enter it never stops loading and doesn't exit the current page to go to the right page.

@mapx- I have pressed the "reset to defaults" buttons many times now, nothing changes.

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by LightningVoid** [comment]
@stephenhawk8054 I created two fresh profiles, installed ublock origin without touching anything else. Went to myanimelist.net, but still can't search anything.

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by stephenhawk8054** [comment]
I can't reproduce:

https://github.com/user-attachments/assets/f350e2fb-ae24-468c-a5ff-cadce1617d16

Which browser are you using?

**Comment by LightningVoid** [comment]
I was making a video of my own to show. As to answer your question: I'm using Opera GX.
In the video I make a fresh profile, like @ mapx- said. Here I do it to show that it doesn't work even if I reset everything. (I have also reset my entire browser without succes. A new profile should simulate this.)

https://streamable.com/5d1g5b

**Comment by stephenhawk8054** [comment]
Can you disable Opera's built-in blocker and test again?

**Comment by LightningVoid** [comment]
the build in blockers have caused issues in the past so they are already disabled. They also weren't enabled on the new profile in the video. I checked in my own video and furthermore made another new profile to check whether it enables automatically to confirm they do not enable automatically.

**Comment by stephenhawk8054** [comment]
In the profile of the video, what happens if you turn off uBO?

**Comment by LightningVoid** [comment]
On any profile, whenever I turn off uBO through it's native button, it still stops me from using the search feature. I have to disable the entire extension for the site to work propperly. I have also tested it with Amazon and Belgium specific sites resembling amazon, and i cannot use the search feature on any of them with the extension enabled.

**Comment by stephenhawk8054** [comment]
Then I don't know. I can't reproduce in Opera GX either:

https://github.com/user-attachments/assets/19f5701a-4597-4328-b2a8-4a19018d94a0

**Comment by LightningVoid** [comment]
could it be that @ mapx- 's comment on the "easylist: null" thing could be the problem? What should I do/enable/disable besides resetting to uBO to default to put this 'easylist' value right?

**Comment by mapx-** [comment]
@LightningVoid are you using some antivirus / security software with some web (filtering) capabilities ?

**Comment by LightningVoid** [comment]
@mapx- I use Kaspersky Free. I have tried disabling it and then opening myanimelist.net and searching something, but it's not fixed.

**Comment by LightningVoid** [comment]
I have found an inconsistency: after all the testing i've done, sometimes i do get search results. Also, the 'popup' (or 'pop-down'?) search results before pressing enter do appear. It's the part after pressing enter that doesn't happen for me.
