### ISSUE TITLE
milliyet.com.tr: breakage

### ISSUE THREAD

**Issue by kodiakhub** [uBlockOrigin/uAssets#24908]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.milliyet.com.tr/ekonomi/bayraktar-kalkan-dihanin-sistem-tanima-testi-yapildi-7171333`

### Category

breakage

### Description

Dailymotion video is missing.

Similar to this issue:
https://github.com/uBlockOrigin/uAssets/issues/24885

```adblock
@@||fundingchoicesmessages.google.com/i/pub-$script,domain=milliyet.com.tr
@@||fundingchoicesmessages.google.com/f/$script,domain=milliyet.com.tr
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/1c3f9b34-7914-454b-9643-3073238ff3db)
![image](https://github.com/user-attachments/assets/3912c83b-f065-4b5b-9a43-0a0223426f52)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 153439
 cosmetic: 58216
 scriptlet: 23708
 html: 0
listset (total-discarded, last-updated):
 added:
  TUR-0: 13445-11, 4m
 default:
  user-filters: 0-0, never
  ublock-filters: 39635-300, 4m
  ublock-badware: 10292-6, 4m
  ublock-privacy: 1056-2, 4m
  ublock-unbreak: 2481-3, 4m Δ
  ublock-quick-fixes: 128-0, 4m
  easylist: 85081-571, 4m
  easyprivacy: 53121-655, 5m
  urlhaus-1: 28270-0, 5m
  plowe-0: 3556-1, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 574 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  milliyet.com.tr: 1
  btloader.com: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  medyanetads.com: 1
  netmera-web.com: 1
  taboola.com: 1
 extended:
  ##.adRenderer
  ##.adv
  ##[data-ad-width]:not([style$="left: -10000px !important; top: -…
  ##.medyanet-inline-adv
  #@#[data-ad-width]
  ##+js(abort-current-script, Date, ='\x)
  ##+js(abort-current-script, document.head.appendChild, ='\x)
  ##+js(abort-on-property-read, __eiPb)
```
</details>

**Comment by stephenhawk8054** [comment]
Next time please just continue in that thread. Thanks.
