### ISSUE TITLE
[nsfw] njavtv.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#24903]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://njavtv.com/dm50/id/mide-275`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/854aa276-7bf0-478e-9b7e-ef547311cdfc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 166369
 cosmetic: 176991
 scriptlet: 34753
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8832-0, 59m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 210-1, 55m
  adguard-cookies: 30912-86, 55m
  ublock-cookies-adguard: 1545-6, 55m
  fanboy-cookiemonster: 51503-4003, 55m
  ublock-cookies-easylist: 1545-1545, 55m
  fanboy-social: 16848-4, 55m
  adguard-popup-overlays: 27797-435, 55m
  easylist-annoyances: 4706-15, 55m
  easylist-notifications: 3473-83, 55m
  ublock-annoyances: 5989-24, 59m Δ
  IDN-0: 10045-451, 55m
 default:
  user-filters: 18-0, never
  ublock-filters: 39632-474, 59m Δ
  ublock-badware: 10211-7, 59m Δ
  ublock-privacy: 1055-2, 59m Δ
  ublock-unbreak: 2481-2, 59m Δ
  ublock-quick-fixes: 132-0, 59m Δ
  easylist: 84920-634, 59m Δ
  easyprivacy: 53119-758, 59m Δ
  urlhaus-1: 28270-0, 59m
  plowe-0: 3556-0, 55m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2218 ms
 maxAssetCacheWait: 593 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  diffusedpassionquaking.com: 1
  google.com: 4
  googletagmanager.com: 1
  myavlive.com: 1
  partwithner.com: 2
  rmhfrtnd.com: 1
  trackwilltrk.com: 1
  tsyndicate.com: 1
 extended:
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
```
</details>

**Comment by mapx-** [comment]
add

`njavtv.com##[src="javascript:window.location.replace(this.frameElement.dataset.link)"]`

report here: https://github.com/ABPindo/indonesianadblockrules/issues
