### ISSUE TITLE
netflix.com: ads

### ISSUE THREAD

**Issue by RyzeR0it** [uBlockOrigin/uAssets#24914]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://netflix.com
```

### Description

Tried using uBlockOrigin to block ads in Netflix, but they ALWAYS play, and NO ads are ever blocked. I have tried changing settings (i.e filter list to be more strict) I have tried to add in a script specifically for netflix to no avail. Tried resetting everything back to default, as well as uninstalling and reinstalling the extension, but nothing seems to be working.

### Other extensions used

Tampermonkey (NOT Active, only used for Twitch ads)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 152219
 cosmetic: 47778
 scriptlet: 20597
 html: 1913
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39784-118, now
  ublock-badware: 10321-6, now
  ublock-privacy: 1052-4, now
  ublock-unbreak: 2540-1, now
  ublock-quick-fixes: 128-8, now
  easylist: 85081-179, now
  easyprivacy: 53121-65, now
  urlhaus-1: 28455-0, 1m
  plowe-0: 3556-997, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1649 ms
 maxAssetCacheWait: 29 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  netflix.com: 2

```
</details>

**Comment by mapx-** [comment]
@RyzeR0it if you can share your account credentials just comment here (and we'll provide an email address where you can send the info). Closing for now.

**Comment by stephenhawk8054** [comment]
@bburns123 Can you test these filters:

```adb
netflix.com##+js(json-prune-fetch-response, result.adverts, , propsToMatch, /manifest)

netflix.com##+js(json-prune-xhr-response, result.adverts, , propsToMatch, /manifest)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by mapx-** [comment]
@RyzeR0it could you test the filters above ?

**Comment by Raza-0007** [comment]
@stephenhawk8054,

Your filters from Sept 19 are not working not Netflix. Attached below are two log files taken when the video passed over an ad break. The first log file is the complete log. The second one is with first-party filter applied, so its easier to read. 

In the log files search for keywords: `adBreakHydration ` `adProgress` `adComplete` `adBreakComplete`

Based on these logs, is there a way to create a custom filter to block ads on Netflix?

Thanks,

[Netflix Log.txt](https://github.com/user-attachments/files/17759240/Netflix.Log.txt)


[Netflix log Filtered.txt](https://github.com/user-attachments/files/17759242/Netflix.log.Filtered.txt)

**Comment by stephenhawk8054** [comment]
@Raza-0007 

> Ads on streaming sites are investigated thanks to users willing to share account credentials. However, if I'm not mistaken, Netflix is strict with account sharing so I'm not sure if it's good to do that or not.
> 
> If you are still willing to share, we can give you emails so you can share the accounts.

**Comment by Raza-0007** [comment]
OK. Thanks.

**Comment by yunarii** [comment]
> @Raza-0007 No, these logs are not enough. The only way is investigating it directly
> 
> > Ads on streaming sites are investigated thanks to users willing to share account credentials. However, if I'm not mistaken, Netflix is strict with account sharing so I'm not sure if it's good to do that or not.
> > If you are still willing to share, we can give you emails so you can share the accounts.

I'm fine with sharing my login information temporarily. Just let me know.

Thanks!

**Comment by stephenhawk8054** [comment]
@yunarii Can you send account to this email: `stephenhawk8054@protonmail.com` ?

Also, which country are you when accessing the site?

**Comment by FTOtter** [comment]
Is there any fix for this? I am seeing ads on Netflix on windows 11 but I did not see them on windows 10. This also just started recently for me, previously ads were being blocked on Windows 11 too. I tried the filters earlier in this discussion and they did not work. I am accessing from the US.

**Comment by stephenhawk8054** [comment]
We cannot investigate without accounts.

**Comment by yunarii** [comment]
> @yunarii Can you send account to this email: `stephenhawk8054@protonmail.com` ?
> 
> Also, which country are you when accessing the site?

Oh this sucks, I'm sorry. I only just now noticed the update from today on this issue come through to my email. I did not notice the other notification from 3 weeks back.

I've sent the details along! I appreciate your time and help.

**Comment by FTOtter** [comment]
I sent mine to the account as well.

**Comment by stephenhawk8054** [comment]
@yunarii @FTOtter Can you test this filter:

```adb
netflix.com##+js(json-prune, result.adverts)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by yunarii** [comment]
> @yunarii @FTOtter Can you test this filter:
> 
> ```
> netflix.com##+js(json-prune, result.adverts)
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Tested it out on at least a dozen different things, between movies and tv shows. Absolutely zero ads on all of them now. You rock! Thank you so much!

**Comment by FTOtter** [comment]
Yes this seems to work now! Awesome, thank you!!

**Comment by 5h1b** [comment]
For anyone getting ads when pausing, add this to your filters
`netflix.com##*:matches-attr(data-uia="pause-ad")`
I just want to add that this is my first time doing this, so this is **most likely not be the best way of doing it!**

**Comment by stephenhawk8054** [comment]
@5h1b Does this work?

```adb
netflix.com##[data-uia="pause-ad"]
```

**Comment by 5h1b** [comment]
> [@5h1b](https://github.com/5h1b) Does this work?
> 
> netflix.com##[data-uia="pause-ad"]

yes

**Comment by 5h1b** [comment]
> > [@5h1b](https://github.com/5h1b) Does this work?
> > netflix.com##[data-uia="pause-ad"]
> 
> yes

wait, nvm, it was netflix hiding it i believe not ublock
