### ISSUE TITLE
file-upload.in: detection

### ISSUE THREAD

**Issue by Cyclamer** [uBlockOrigin/uAssets#24917]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://file-upload.in/`

### Category

detection

### Description

It shows a popup to disable adblock.

### Other extensions used

Privacy Badger
LocalCDN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-15 091225](https://github.com/user-attachments/assets/6c4b5259-46ba-4589-89d1-f48f0bbe52cd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 151555
 cosmetic: 47787
 scriptlet: 20605
 html: 1914
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39795-118, 5m Δ
  ublock-badware: 10321-6, 5m Δ
  ublock-privacy: 1052-4, 5m Δ
  ublock-unbreak: 2542-1, 5m Δ
  ublock-quick-fixes: 128-8, 5m Δ
  easylist: 85099-179, 5m Δ
  easyprivacy: 52959-65, 5m Δ
  urlhaus-1: 27940-0, now
  plowe-0: 3556-997, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 66 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  demand.supply: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.demand-supply
  ##+js(noeval-if, ppu)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, document.getElementById, undefined)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-current-script, getCookie, setCookie)
  ##+js(abort-on-property-write, Fingerprint2)
```
</details>

**Comment by stephenhawk8054** [comment]
Is it a shortener link? Give original URL.

**Comment by mapx-** [comment]
@Cyclamer ask for help here (providing a real/original  link)
https://github.com/uBlockOrigin/uAssets/discussions/17361
