### ISSUE TITLE
[nsfw] travize.net: detection

### ISSUE THREAD

**Issue by gudarks** [uBlockOrigin/uAssets#24926]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://travize.net/cambodia-itinerary-for-one-week-trip/`

### Category

detection

### Description

when i acess the website it gets detected

### Other extensions used

no other

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 154315
 cosmetic: 51944
 scriptlet: 22577
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39647-296, 1m
  ublock-badware: 10352-6, 1m Δ
  ublock-privacy: 1065-2, 1m
  ublock-unbreak: 2485-0, 1m Δ
  ublock-quick-fixes: 142-0, 1m
  easylist: 85130-607, 23m Δ
  easyprivacy: 52958-660, 1m
  urlhaus-1: 29325-0, 1m
  plowe-0: 3547-0, 1m
  spa-1: 5930-19, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 569 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  cleverwebserver.com: 1
  googlesyndication.com: 1
  gstatic.com: 2
  netpub.media: 3
  rfsmptgrwahsaux.com: 1
  waisheph.com: 1
 extended:
  ##.clever-core-ads
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
```
</details>

**Comment by mapx-** [comment]
How did you get the detection:

- visiting directly the page above
or
- being redirected from other original page ?

**Comment by D4niloMR** [comment]
Fixed in https://github.com/uBlockOrigin/uAssets/commit/e4bd97c60ded35d72e9902eb01fcb7f6f28161e5
