### ISSUE TITLE
pravda.com.ua: ads

### ISSUE THREAD

**Issue by zyrzys** [uBlockOrigin/uAssets#24927]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pravda.com.ua/`

### Category

ads

### Description

pravda.com.ua newspaper started to show adds on the right side of the news feed since today 16.08.2024. Browser - mozilla firefox v129.0.1

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 152985
 cosmetic: 47813
 scriptlet: 20618
 html: 1915
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39801-118, 1h.58m Δ
  ublock-badware: 10354-6, 1h.58m Δ
  ublock-privacy: 1058-4, 1h.58m Δ
  ublock-unbreak: 2544-1, 1h.58m Δ
  ublock-quick-fixes: 137-4, 1h.58m Δ
  easylist: 85130-180, 1h.58m Δ
  easyprivacy: 52958-65, 1h.58m Δ
  urlhaus-1: 29325-0, now
  plowe-0: 3547-993, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8731 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  becdn.net: 2
  criteo.net: 1
  doubleclick.net: 1
  gemius.pl: 1
  googletagmanager.com: 1
  gravitec.net: 5
  onthe.io: 2
 extended:
  ##.advtext
  ##.nts-ad
  ##.unit_side_banner
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/fbb8decb75e5b521e2bad2d8614a038dd49c1134
