### ISSUE TITLE
magesypro.com: nuisance

### ISSUE THREAD

**Issue by shodan5000** [uBlockOrigin/uAssets#24928]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://magesypro.com/software/win/`

### Category

nuisance

### Description

Blur overlay

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/user-attachments/assets/5860ad81-8e00-4682-986c-ee3cc622eb7a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 253430
 cosmetic: 258969
 scriptlet: 55628
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84238-517, 7m
  adguard-mobile: 9638-159, 7m
  adguard-spyware-url: 1642-123, 7m
  adguard-spyware: 87779-30647, 7m
  block-lan: 71-0, 7m
  curben-phishing: 550-0, 7m
  adguard-cookies: 30949-82, 7m
  ublock-cookies-adguard: 1548-6, 7m
  fanboy-cookiemonster: 51521-4007, 7m
  ublock-cookies-easylist: 1548-1548, 7m
  adguard-social: 23300-908, 7m
  fanboy-social: 16875-27, 7m
  [11 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  ublock-filters: 39647-4037, 17m Δ
  ublock-badware: 10352-120, 17m Δ
  ublock-privacy: 1065-2, 17m Δ
  ublock-unbreak: 2485-86, 17m Δ
  ublock-quick-fixes: 142-20, 17m Δ
  easylist: 85130-3158, 17m Δ
  easyprivacy: 52958-945, 17m Δ
  urlhaus-1: 29325-0, 7m
  plowe-0: 3547-25, 7m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1220 ms (selfie)
 maxAssetCacheWait: 233 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 4
 extended:
  ##.mdpDeblocker-wrapper
  ##.active.mdpDeblocker-blackout
  ##+js(nobab)
  ##+js(addEventListener-defuser, load, aadb_get_data)
  ##+js(abort-on-property-read, adsBlocked)
  ##+js(noeval-if, /fairAdblock|chp_?adblock|adsbygoogle\.js/)
  ##+js(prevent-fetch, pagead2.googlesyndication.com)
  ##+js(abort-current-script, onload, .offsetHeight<=0)
  ##+js(abort-current-script, document.getElementById, document.wr…
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
magesypro.com##+js(aost, document.getElementsByTagName, adsBlocked)

**Comment by JobcenterTycoon** [comment]
Doesn’t work on Firefox.

**Comment by BlazeFTL** [comment]
Weird I Tested On FF Only : (
& It Works
