### ISSUE TITLE
vogue.com.tr: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#24920]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vogue.com.tr/gundem/brat-summer-nedir`

### Category

ads

### Description

self promo email

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://github.com/user-attachments/assets/7a752645-8f3d-4aba-b17e-b84f678c81f0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 197045
 cosmetic: 175100
 scriptlet: 35339
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/fake.txt: 29790-0, 1h.9m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt: 23935-325, 14h.5m
  adguard-cookies: 30841-84, 3d.19h.48m
  easylist-annoyances: 4708-122, 14h.5m
  easylist-chat: 205-0, 3d.19h.48m
  easylist-newsletters: 7566-27, 14h.5m
  easylist-notifications: 3474-75, 14h.5m
  fanboy-cookiemonster: 67840-20307, 14h.5m
  fanboy-social: 16882-40, 14h.5m
  fanboy-thirdparty_social: 68-0, 3d.19h.48m
  ublock-annoyances: 5990-12, 1h.9m Δ
  ublock-cookies-easylist: 1545-6, 14h.5m
 default:
  user-filters: 0-0, never
  TUR-0: 13432-20, 3d.19h.48m
  easylist: 85101-595, 1h.9m Δ
  easyprivacy: 52959-667, 1h.9m Δ
  plowe-0: 3556-0, 1d.18h.5m
  ublock-badware: 10329-6, 1h.9m Δ
  ublock-filters: 39644-309, 1h.9m Δ
  ublock-privacy: 1057-2, 1h.9m Δ
  ublock-quick-fixes: 129-0, 1h.9m Δ
  ublock-unbreak: 2483-1, 1h.9m Δ
  urlhaus-1: 28705-0, 1h.9m
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  bkrtx.com: 1
  condenastdigital.com: 1
  doubleclick.net: 1
  gemius.pl: 1
  google-analytics.com: 1
  google.com: 4
  googletagmanager.com: 2
  typekit.net: 1
  yandex.ru: 1
  youtube.com: 1
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/sharing/share-offsite/?"]
  ##a[href^="https://www.pinterest.com/pin/create/button/"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
for easylist annoyances report here: https://github.com/easylist/easylist/issues

**Comment by gototheskinny** [comment]
> for easylist annoyances report here: https://github.com/easylist/easylist/issues

It's local so I don't think they'll cover this issue.
