### ISSUE TITLE
hexanaut.io: ads

### ISSUE THREAD

**Issue by gambyent** [uBlockOrigin/uAssets#24922]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hexanaut.io/`

### Category

ads

### Description

After clicking the "Play" button on the website to start the game, there is sometimes an interstitial screen for ADINPLAY which says "loading advertisement".   No ad actually loads and the game does start after a few seconds.   It seems that there may be a cookie which determines how often the screen shows up.   I can always get it to show up if I start in an InPrivate window.    The ad screen only started showing up in the last week or so.  

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/494f2f31-ffa1-406d-a398-bcf408c7e104)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 152358
 cosmetic: 47897
 scriptlet: 22054
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 85109-437, 1h.39m Δ
  easyprivacy: 52959-630, 1h.39m Δ
  plowe-0: 3556-0, now
  ublock-badware: 10329-26, 1h.39m Δ
  ublock-filters: 39647-371, 1h.39m Δ
  ublock-privacy: 1057-5, 1h.39m Δ
  ublock-quick-fixes: 129-8, 1h.39m Δ
  ublock-unbreak: 2483-35, 1h.39m Δ
  urlhaus-1: 28705-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2113 ms (selfie)
 maxAssetCacheWait: 1899 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 50
 network:
  3lift.com: 3
  4dex.io: 4
  adinplay-venatus.workers.dev: 1
  adinplay.com: 2
  adnxs.com: 4
  amazon-adsystem.com: 1
  bidswitch.net: 4
  btloader.com: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  onetag-sys.com: 4
  pubmatic.com: 4
  rubiconproject.com: 4
  script.ac: 1
  servenobid.com: 3
  sharethrough.com: 1
  the-ozone-project.com: 3
  unrulymedia.com: 2
  yellowblue.io: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 i see `@@||api.adinplay.com/libs/aiptag/$script` whitelisted by EL but the game starts perfectly when i add `||api.adinplay.com^$script,important,domain=hexanaut.io`

**Comment by Yuki2718** [comment]
Looks it was made generic by repeated breakage: https://github.com/easylist/easylist/commit/9a48a39c5272a1e5905cb1ab3adeee1fe9da6b1d
@ryanbr

**Comment by ryanbr** [comment]
Whats the best way to address in EL, remove `@@||api.adinplay.com/libs/aiptag/$script` or make ||adinplay.com^$third-party or return to the large exceptions

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon @Yuki2718 I think keeping the exceptions in EL is better. uBO can override with `important` depending on the case.

**Comment by JobcenterTycoon** [comment]
Why override in uBO? EL can do the same with `,domain=~example.com`
