### ISSUE TITLE
zonaflix.net: detection

### ISSUE THREAD

**Issue by daveox** [uBlockOrigin/uAssets#24931]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://zonaflix.net/episodios/revenge-1-temporada-x-episodio-1/`

### Category

detection

### Description

Video player is not visible

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 114
filterset (summary):
 network: 101638
 cosmetic: 73412
 scriptlet: 27466
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt: 51083-483, 3d.22h.25m
  https://filters.adtidy.org/extension/ublock/filters/118_optimized.txt: 13623-217, 3d.22h.24m
  https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt: 43970-471, 3d.22h.24m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2666-50, 8h.9m
 default:
  user-filters: 249-1, never
  plowe-0: 3558-0, 8d.22h.57m
  spa-1: 5883-43, 3d.22h.24m
  ublock-badware: 10352-6, 5h.9m Δ
  ublock-filters: 39644-114, 5h.9m Δ
  ublock-privacy: 1065-2, 5h.9m Δ
  ublock-quick-fixes: 140-4, 5h.9m Δ
  ublock-unbreak: 2485-1, 5h.9m Δ
  urlhaus-1: 29325-0, 8h.9m
filterset (user): [array of 256 redacted]
trustedset:
 added: [array of 21 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 839 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 110822 ms (selfie)
 maxAssetCacheWait: 10801 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  amung.us: 2
  dtscout.com: 1
```
</details>

**Comment by zenstorage** [comment]
Try:
```
cozinhabr.top##+js(acs, document.onkeydown, adsbygoogle.js)
```

**Comment by stephenhawk8054** [comment]
```adb
cozinhabr.top##+js(nostif, Adblock)
```

@Yuki2718 For Adguard Portuguese?

**Comment by daveox** [comment]
> Try:
> 
> ```
> cozinhabr.top##+js(aopw, document.onkeydown)
> ```

Thanks.

**Comment by Yuki2718** [comment]
@daveox You don't need that, just update AdGuard Spanish/Portuguese.
