### ISSUE TITLE
d20pfsrd.com: nuisance

### ISSUE THREAD

**Issue by suspiciousRaccoon** [uBlockOrigin/uAssets#24935]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.d20pfsrd.com/`

### Category

nuisance

### Description

The website has popups.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/1abcf9af-d0e9-4007-8005-a4202d4bd867)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 154348
 cosmetic: 49418
 scriptlet: 24404
 html: 2176
listset (total-discarded, last-updated):
 added:
  curben-phishing: 486-3, now
  ublock-annoyances: 5924-34, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39831-125, now
  ublock-badware: 10363-6, now
  ublock-privacy: 1063-4, now
  ublock-unbreak: 2555-1, now
  ublock-quick-fixes: 157-4, now
  easylist: 85198-180, now
  easyprivacy: 52976-65, now
  urlhaus-1: 29815-0, now
  plowe-0: 3547-993, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1692 ms (selfie)
 maxAssetCacheWait: 111 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  nitropay.com: 1
  shopifysvc.com: 3
 extended:
  ##.videoad
  ##html:style(overflow:auto!important)
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-promotion. You can use this as a custom filter:

```adb
d20pfsrd.com##.ognannouncement-container
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
