### ISSUE TITLE
sainsburys.co.uk: breakage

### ISSUE THREAD

**Issue by incident57** [uBlockOrigin/uAssets#24937]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sainsburys.co.uk/gol-ui/product/funkin-nitro-cocktails-strawberry-daiquiri-200ml`

### Category

breakage

### Description

The Description and Reviews panels are hidden when "uBlock filters – Ads" is enabled. This also happens with other product pages on the site.

### Other extensions used

Tested with all other extensions disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/8880d331-d815-4554-a206-e03eaf73c321)

![image](https://github.com/user-attachments/assets/1895074e-6fe4-48c7-b911-499a174c14be)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153484
 cosmetic: 47838
 scriptlet: 20647
 html: 1919
listset (total-discarded, last-updated):
 default:
  user-filters: 28-0, never
  ublock-filters: 39831-250, never
  ublock-badware: 10354-6, 11m
  ublock-privacy: 1063-2, 11m
  ublock-unbreak: 2555-0, 11m
  ublock-quick-fixes: 138-0, 11m
  easylist: 85119-86, 12m
  easyprivacy: 52969-41, 12m
  urlhaus-1: 29815-0, 12m
  plowe-0: 3547-993, 12m
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1668 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  ads-twitter.com: 1
  adsrvr.org: 2
  bing.com: 6
  citrusad.com: 7
  doubleclick.net: 2
  facebook.net: 1
  gbqofs.com: 1
  googletagmanager.com: 1
  ist-track.com: 3
  newrelic.com: 1
  pinimg.com: 1
  sc-static.net: 1
  taggstar.com: 1
  tealiumiq.com: 2
 extended:
  ##li:has(.product-header):has-text(Sponsored)
  ##html,body:style(overflow: visible !important;)
```
</details>

**Comment by D4niloMR** [comment]
I can't reproduce ads right now but 

```adb
sainsburys.co.uk##+js(json-prune, ads.[-].ad_id)
```

should work

**Comment by davefiddes** [comment]
Thanks. That seems to fix the site for me now.
