### ISSUE TITLE
megafilmeshd2.to: breakage

### ISSUE THREAD

**Issue by daveox** [uBlockOrigin/uAssets#24938]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://megafilmeshd2.to/series/assistir-expresso-do-amanha-online-hd/`

### Category

breakage

### Description

Hidden video player

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 114
filterset (summary):
 network: 101971
 cosmetic: 73422
 scriptlet: 27526
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt: 50957-23, now
  https://filters.adtidy.org/extension/ublock/filters/118_optimized.txt: 13528-224, now
  https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt: 43994-467, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2666-50, now
 default:
  user-filters: 251-4, never
  plowe-0: 3547-325, now
  spa-1: 5930-37, now
  ublock-badware: 10361-11, 5m Δ
  ublock-filters: 39667-217, 5m Δ
  ublock-privacy: 1070-3, 5m Δ
  ublock-quick-fixes: 169-0, 5m Δ
  ublock-unbreak: 2496-34, 5m Δ
  urlhaus-1: 29815-0, now
filterset (user): [array of 258 redacted]
trustedset:
 added: [array of 21 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 841 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 98290 ms (selfie)
 maxAssetCacheWait: 7937 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 33
 network:
  amung.us: 1
  doubleclick.net: 3
  google.com: 18
  youtube.com: 11
 extended:
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##body:style(overflow-x: hidden !important;)
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
```
</details>

**Comment by zenstorage** [comment]
Try:
```
financeiropronto.vip##+js(set-local-storage-item, last_ads, yes)
```

**Comment by daveox** [comment]
> Try:
> 
> ```
> financeiropronto.vip##+js(set-local-storage-item, last_ads, yes)
> ```

Thanks. You guys are aewsome.

**Comment by stephenhawk8054** [comment]
@Yuki2718 For Adguard Portuguese?
