### ISSUE TITLE
vrcmods.com: ads

### ISSUE THREAD

**Issue by zephiii** [uBlockOrigin/uAssets#24949]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vrcmods.com/search`

### Category

ads

### Description

Shows a leftover asking the user to "upgrade to [an] ad-free experience".

### Other extensions used

_none_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1359" alt="Screenshot 2024-08-18 at 20 11 58" src="https://github.com/user-attachments/assets/642e9988-01ed-49da-ae4a-36e565ded8ae">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 117
filterset (summary):
 network: 158342
 cosmetic: 75475
 scriptlet: 23453
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 30953-42, now
 default:
  user-filters: 2771-0, never
  easylist: 85251-477, 1h.10m Δ
  easyprivacy: 53030-647, 1h.10m Δ
  plowe-0: 3547-0, now
  ublock-badware: 10440-6, 1h.10m Δ
  ublock-filters: 39683-380, 1h.10m Δ
  ublock-privacy: 1066-51, 1h.10m Δ
  ublock-quick-fixes: 168-0, 1h.10m Δ
  ublock-unbreak: 2497-0, 1h.10m Δ
  urlhaus-1: 29620-0, now
filterset (user): [array of 2783 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 136 ms (selfie)
 maxAssetCacheWait: 34 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  vrcmods.com: 1
  ad.plus: 2
  googletagmanager.com: 3
  pub.network: 2
 extended:
  ##[data-freestar-ad][id]
  ##+js(adjust-setInterval, timeLeft)
  ##+js(no-setTimeout-if, height)
  ##+js(no-setInterval-if, height)
```
</details>

**Comment by JobcenterTycoon** [comment]
Its fixed in `uBlock filters – Annoyances` you can enable the filterlist in the filterlist panel.
