### ISSUE TITLE
vgbaike.com: breakage

### ISSUE THREAD

**Issue by PMisRIGHT** [uBlockOrigin/uAssets#24946]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vgbaike.com/`

### Category

breakage

### Description

uBO block the css and js file which be used to composing load by cdn, make webpage breakage

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![图片](https://github.com/user-attachments/assets/8dc4fdca-829d-481b-864c-2381ac2f8293)
![图片](https://github.com/user-attachments/assets/c8c17c33-2d3f-43e9-b448-c0bfefcee741)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 178144
 cosmetic: 197800
 scriptlet: 30337
 html: 1918
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81691-153, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 101796-23826, now
 default:
  user-filters: 24-0, never
  ublock-filters: 39840-457, 1h.19m Δ
  ublock-badware: 10398-6, 1h.19m Δ
  ublock-privacy: 1058-5, 1h.19m Δ
  ublock-unbreak: 2556-6, 1h.19m Δ
  ublock-quick-fixes: 157-4, 1h.19m Δ
  easylist: 85219-258, 1h.19m Δ
  easyprivacy: 52976-226, 1h.19m Δ
  urlhaus-1: 29785-0, now
  plowe-0: 3547-994, now
  CHN-0: 25448-206, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 819 ms (selfie)
 maxAssetCacheWait: 172 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  baidu.com: 1
  bdstatic.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  qhimg.com: 1
  staticfile.org: 16
```
</details>

**Comment by stephenhawk8054** [comment]
The domain `staticfile.org` being blocked in the site belongs to `polyfill.io` who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.
