### ISSUE TITLE
patreon.com: breakage

### ISSUE THREAD

**Issue by MDawg957** [uBlockOrigin/uAssets#24941]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.patreon.com/gamegrumps`

### Category

breakage

### Description

The share and ... buttons do not show with uBO enabled. I'm in the US and login is not required to see the missing buttons. I've included a screenshot with what should be present, but currently is not.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/user-attachments/assets/d1f72eb6-a370-4707-a388-b26df74e3f67)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 161254
 cosmetic: 140576
 scriptlet: 30549
 html: 2172
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81691-470, now
  ublock-annoyances: 5924-172, now
  adguard-social: 23298-929, now
  adguard-cookies: 30953-30953, now
  adguard-popup-overlays: 27807-27807, now
  adguard-mobile-app-banners: 5402-5402, now
  adguard-other-annoyances: 14890-14890, now
  adguard-widgets: 2639-2639, now
  ublock-cookies-adguard: 1549-24, now
 default:
  user-filters: 3-0, never
  ublock-filters: 39836-125, now
  ublock-badware: 10373-6, now
  ublock-privacy: 1058-4, now
  ublock-unbreak: 2556-3, now
  easylist: 85212-240, now
  easyprivacy: 52976-135, now
  plowe-0: 3547-994, now
  urlhaus-1: 29785-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1268 ms (selfie)
 maxAssetCacheWait: 154 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  patreon.com: 1
  google.com: 1
  sentry.io: 1
  siftscience.com: 1
  sprig.com: 1
  transcend-cdn.com: 2
 extended:
  ##div[class] > div[class^="sc-"]:has(> button > div > span > svg…
  ##button[data-tag="pages-creator-public-page-Header-ShareCampaig…
  ##button[data-tag="share-post-icon"]
  ##body:style(overflow: auto !important;)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by josephcsible** [comment]
> - [x]  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

But it looks to me like this only happens because you have the additional filter list "AdGuard – Social Widgets" enabled.

**Comment by mapx-** [comment]
@MDawg957 disable that social list or add

```
patreon.com#@#button[data-tag="share-post-icon"]
patreon.com#@#button[data-tag="pages-creator-public-page-Header-ShareCampaign"]
patreon.com#@#div[class] > div[class^="sc-"]:has(> button > div > span > svg[data-tag="IconShare"])
```
