### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by isthisyoursocialsecuritynumber** [uBlockOrigin/uAssets#24943]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=MjecOkKGgWs`

### Category

ads

### Description

Ads on youtube are no longer blocked

### Other extensions used

No other ex tenstions used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 153602
 cosmetic: 47955
 scriptlet: 22107
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39671-121, now
  ublock-badware: 10396-6, now
  ublock-privacy: 1065-2, now
  ublock-unbreak: 2497-1, now
  ublock-quick-fixes: 167-4, 1h.33m Δ
  easylist: 85219-567, now
  easyprivacy: 52976-805, now
  urlhaus-1: 29785-0, now
  plowe-0: 3547-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 779 ms (selfie)
 maxAssetCacheWait: 187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 37
 network:
  doubleclick.net: 4
  google.com: 9
  google.com.au: 1
  googleadservices.com: 1
  googlesyndication.com: 5
  youtube.com: 17
 extended:
  ##.ytp-featured-product
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
```
</details>

**Comment by zephiii** [comment]
> * [x]  This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
> * [x]  I did not answer truthfully to **ALL** the above checkboxes.
