### ISSUE TITLE
[nsfw] 4play.to: ads

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#24942]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://4play.to/`

### Category

nuisance

### Description

A large pop-up to a betting site

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 159296
 cosmetic: 67671
 scriptlet: 22506
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 10045-10, 5m
  easylist-annoyances: 4716-25, 5m
  easylist-chat: 206-0, 5m
  easylist-newsletters: 7629-30, 5m
  easylist-notifications: 3476-85, 5m
 default:
  user-filters: 0-0, never
  easylist: 85219-49, 1m
  easyprivacy: 52976-748, 1m
  plowe-0: 3547-371, 1m
  ublock-badware: 10396-26, 1m
  ublock-filters: 39671-402, 1m
  ublock-privacy: 1065-4, 1m
  ublock-quick-fixes: 167-0, 1h.51m Δ
  ublock-unbreak: 2497-18, 1m
  urlhaus-1: 29785-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1251 ms (selfie)
 maxAssetCacheWait: 60 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  4play.to: 2
  a-ads.com: 4
  cloudflareinsights.com: 1
  facebook.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
4play.to##.davwheat-ad
```

@gmarcher Sorry, can you check this?
