### ISSUE TITLE
wifi.delta.com: breakage

### ISSUE THREAD

**Issue by DoraTheExploder** [uBlockOrigin/uAssets#24947]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wifi.delta.com/`

### Category

breakage

### Description

When attempting to connect to on-board WiFi on a Delta Airlines flight you are required to visit this site. There is a video advertisement served before your connection is activated, which loads in its entirety (this is not the issue I'm reporting). After the mandatory video advertisement is completed the site attempts to redirect you to a dashboard page that will load indefinitely while uBO is active, thus disallowing use of on+board WiFi.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 154920
 cosmetic: 56230
 scriptlet: 20728
 html: 1919
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40286-127, now
  ublock-badware: 10435-6, now
  ublock-privacy: 1059-4, now
  ublock-unbreak: 2559-1, now
  ublock-quick-fixes: 159-4, now
  adguard-mobile: 9638-74, now
  easylist: 85226-253, now
  easyprivacy: 53030-73, now
  urlhaus-1: 29620-0, now
  plowe-0: 3547-1067, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 251 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  adoberesources.net: 1
  qualtrics.com: 1
  quantummetric.com: 1
```
</details>

**Comment by DoraTheExploder** [comment]
I do not have a screenshot of the affected page, but it's simply a loading spinner on a navy blue field.

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by DoraTheExploder** [comment]
I'll have to wait until I'm back on another Delta flight. The reason I suspect that uBO did it is because I disabled it and refreshed the page and it loaded instantly. I then re-enabled the extension and it went back to the described behavior.

**Comment by stephenhawk8054** [comment]
@DoraTheExploder Continue commenting here to get the log as above instruction when you can reproduce the issue again. All volunteers are notified with new comments. I'll close the issue for now.
