### ISSUE TITLE
apk-indir.online: ads

### ISSUE THREAD

**Issue by Zezu5** [uBlockOrigin/uAssets#24945]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://apk-indir.online/apk-indir.html`

### Category

ads

### Description

Its fake file download site

### Other extensions used

ClearURLs ,Decelanteries, Privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 158146
 cosmetic: 66559
 scriptlet: 22399
 html: 1919
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-spyware-url: 1642-124, now
  block-lan: 71-0, now
 default:
  user-filters: 1-0, never
  ublock-filters: 40284-187, 2m Δ
  ublock-badware: 10367-7, 2m Δ
  ublock-privacy: 1059-4, 3m Δ
  ublock-unbreak: 2559-3, 2m Δ
  ublock-quick-fixes: 157-4, 3m Δ
  adguard-mobile: 9638-11, now
  easylist: 85212-253, 2m Δ
  easyprivacy: 52976-75, 2m Δ
  urlhaus-1: 29785-0, now
  plowe-0: 3547-1067, now
  TUR-0: 13463-39, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 33 redacted]
userSettings:
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 637 ms (selfie)
 maxAssetCacheWait: 187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
> Its fake file download site


we need more information on why it's fake
