### ISSUE TITLE
proininews.gr: breakage

### ISSUE THREAD

**Issue by MEtICaRT** [uBlockOrigin/uAssets#24959]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.proininews.gr/aggelies/
```

### Description

This URL contains important job listings, but it has been redesigned recently, and because of this, the listings are now incorrectly blocked by uBO.

AdGuard faces the same issue on Safari.

I have attached screenshots and troubleshooting information below.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBO on:

<img width="1778" alt="image" src="https://github.com/user-attachments/assets/91a46745-d762-4de1-acc3-3b061c4ba440">

uBO off:

<img width="1777" alt="image" src="https://github.com/user-attachments/assets/871d58a2-4ff0-477c-a05c-f20712e84402">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 153917
 cosmetic: 47972
 scriptlet: 22119
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39699-284, 1m
  ublock-badware: 10460-6, 1m
  ublock-privacy: 1066-2, 1m
  ublock-unbreak: 2497-0, 1m
  ublock-quick-fixes: 170-0, 2m
  easylist: 85219-568, 2m
  easyprivacy: 53039-650, 2m
  urlhaus-1: 29965-0, 2m
  plowe-0: 3556-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 254 ms
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  proininews.gr: 1
  googlesyndication.com: 2
  histats.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.small-ads
  ##.single-ads
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
proininews.gr#@#.small-ads
```

@ryanbr
