### ISSUE TITLE
crackshash.com / download4allfree.com : ads

### ISSUE THREAD

**Issue by rrrcabral** [uBlockOrigin/uAssets#24953]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://crackshash.com/`

### Category

ads

### Description

After clicking on a download link of a PC program for example, on the "crackshash" website, a pop-up opens, for example from the url "download4allfree" containing a fake download link automatically generated to deceive the inattentive user.
and this Fake page was not blocked.

### Other extensions used

nome

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://imgbox.com/hTxEOx6D

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 155191
 cosmetic: 52003
 scriptlet: 22619
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39683-298, 6m Δ
  ublock-badware: 10440-6, 6m Δ
  ublock-privacy: 1066-2, 6m Δ
  ublock-unbreak: 2497-0, 6m Δ
  ublock-quick-fixes: 166-0, 6m Δ
  easylist: 85251-607, 6m Δ
  easyprivacy: 53030-660, 6m Δ
  urlhaus-1: 29950-0, 3m
  plowe-0: 3547-0, 3m
  spa-1: 5930-19, 3m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 414 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  crackshash.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Redirection chain:

```ini
https://restabbingenologistwoollies.com/cMrb382fec4b1b1ab8619245b167e76b0576445aad055?q=Benvista+PhotoZoom+Pro+v9.0.2+%28x64%29+%2B+Fix
https://download4allfree.com/s/?file=ADOXwmYvYwUAdXoCAEhLFwAMAAAAAABl.Benvista_PhotoZoom_Pro_v9.0.2_%28x64%29___Fix.zip
```
