### ISSUE TITLE
satisfactory-calculator.com: ads

### ISSUE THREAD

**Issue by PolyacovYury** [uBlockOrigin/uAssets#24950]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://satisfactory-calculator.com/en/interactive-map/`

### Category

ads

### Description

Left-over ad containers under page header, below right panel (with a HUGE `margin-bottom`) and under the map itself.  

<details>
<summary>P.S.</summary>

`configuration['popupPanel']['extended']` contains 3 filters I made for myself to hide the extraneous divs with their margins, borders and stuff, feel free to use :)

</details>

<details>
<summary>P.P.S.</summary>

The other 3 filters, redacted in `configuration['filterset (user)']`, re-enable access to Sentry.io using `badfilter`, since [I am a software dev myself](https://i.kym-cdn.com/entries/icons/original/000/025/351/afoeeee.jpg) and don't want to disable the whole EasyList out of solidarity with [other software devs' struggles](https://github.com/easylist/easylist/issues/6963).

</details>

### Other extensions used

<details>
<summary>List of installed extensions</summary>

Don't seem to affect this website at all:  
- Facebook Container  
- Firefox Multi-Account Containers  
- Indie Wiki Buddy  
- Savefrom.net helper  
- Stylus  
- To Google Translate  
- YouTube High Definition  
- YouTube NonStop  

Disabled on this website via in-extension config, toggling doesn't change observed behavior:  
- Dark Reader  

Disabled via in-extension config, toggling doesn't change observed behavior:  
- BrowSec VPN  
- Hoxx VPN Proxy  

Actively alter the website, don't seem to be the cause of the issue, but still:  
- I don't care about cookies  

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Visible immediately:
![image](https://github.com/user-attachments/assets/2eab0033-183a-4c7b-88f0-7e55bfa530c4)
Visible when scrolling all the way to the bottom:
![image](https://github.com/user-attachments/assets/2602c6f8-795d-466f-9760-a52d221af45f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 271296
 cosmetic: 279184
 scriptlet: 55483
 html: 2192
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 84246-4145, 30m
  adguard-mobile: 9638-59, 30m
  adguard-spyware-url: 1643-124, 30m
  adguard-spyware: 87785-1555, 30m
  block-lan: 71-0, 30m
  curben-phishing: 486-3, 30m
  adguard-social: 23299-56, 30m
  adguard-cookies: 30953-55, 30m
  adguard-popup-overlays: 27809-1018, 30m
  adguard-mobile-app-banners: 5402-27, 30m
  adguard-other-annoyances: 14890-409, 30m
  adguard-widgets: 2639-17, 30m
  [11 lists not shown]: [too many]
 default:
  ublock-filters: 39853-125, 1h.32m Δ
  ublock-badware: 10442-6, 1h.32m Δ
  ublock-privacy: 1059-4, 1h.32m Δ
  ublock-unbreak: 2556-1, 1h.32m Δ
  ublock-quick-fixes: 159-4, 1h.32m Δ
  easylist: 85251-2550, 1h.32m Δ
  easyprivacy: 53030-29064, 1h.32m Δ
  urlhaus-1: 29620-0, now
  plowe-0: 3547-1488, now
  RUS-0: 40780-1674, 32m Δ
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 311 ms (selfie)
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflare.com: 2
  googletagmanager.com: 1
  paypalobjects.com: 2
  vntsm.com: 1
 extended:
  ##.container-fluid:has(#DynamicWidth-Slot-2)
  ##.mt-3:has(#DynamicWidth-Slot-1)
  ##.mt-2:has(#DynamicSquare-Slot-1)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
satisfactory-calculator.com##div[id^="DynamicWidth-Slot"]
satisfactory-calculator.com##div[id^="DynamicInStream-Slot"]
```

@ryanbr
