### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by ozarkbunnyboy** [uBlockOrigin/uAssets#24967]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.amazon.com/gp/video/detail/B00C175J3I/ref=atv_hm_hom_c_lZOsi7_2_2?jic=8%7CEgNhbGw%3D`

### Category

ads

### Description

unexpected ad

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 125
filterset (summary):
 network: 154020
 cosmetic: 48007
 scriptlet: 22134
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 85356-568, 20m Δ
  easyprivacy: 53042-647, 20m Δ
  plowe-0: 3547-0, 20m
  ublock-badware: 10460-6, 20m Δ
  ublock-filters: 39725-284, 20m Δ
  ublock-privacy: 1066-2, 21m Δ
  ublock-quick-fixes: 164-0, 21m Δ
  ublock-unbreak: 2497-0, 20m Δ
  urlhaus-1: 29965-0, 20m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1732 ms (selfie)
 maxAssetCacheWait: 689 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 151
 network:
  amazon.com: 149
  amazon-adsystem.com: 1
  atl58-p9.cloudfront.net: 1
 hasUnprocessedRequest: true
 extended:
  ###nav-swmslot
  ##+js(json-prune, cuepointPlaylist)
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] |…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > &#9636; ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Open new tab and reproduce the issue
3. Switch to the logger window that was opened in step 1
4. Copy the logger via &#128203; [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by ozarkbunnyboy** [comment]
So far I can't reproduce the issue. It is intermittent.


*ॐ*
