### ISSUE TITLE
ridejetson.com: detection

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#24964]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ridejetson.com/products/copperhead-extreme-terrain-electric-scooter`

### Category

detection

### Description

Impossible to leave review for item when uBlock origin is enabled

### Other extensions used

Rakuten Shopping Extension 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-19 110220](https://github.com/user-attachments/assets/dadf073b-d99b-4156-9a45-fa7869781d5c)
![Screenshot 2024-08-19 110145](https://github.com/user-attachments/assets/51dca968-c3e6-4d82-b0e1-84ba080431ce)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 246913
 cosmetic: 220122
 scriptlet: 55721
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84356-6682, never
  adguard-mobile: 9643-182, never
  adguard-spyware-url: 1643-124, never
  adguard-spyware: 79738-27915, never
  block-lan: 71-2, never
  curben-phishing: 451-3, never
  adguard-cookies: 31005-3851, never
  ublock-cookies-adguard: 1551-6, never
  fanboy-cookiemonster: 51620-231, never
  ublock-cookies-easylist: 1551-1551, never
  adguard-popup-overlays: 27826-1063, never
  adguard-mobile-app-banners: 5405-1123, never
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39693-284, 7m
  ublock-badware: 10460-6, 7m
  ublock-privacy: 1066-2, 7m
  ublock-unbreak: 2497-0, 7m
  ublock-quick-fixes: 170-0, 7m
  easylist: 85355-574, 7m
  easyprivacy: 53039-647, 7m
  urlhaus-1: 29965-0, 7m
  plowe-0: 3547-0, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2517 ms
 maxAssetCacheWait: 22 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30081
 network:
  ridejetson.com: 15
  bazaarvoice.com: 2
  bugsnag.com: 30045
  cookielaw.org: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  iesnare.com: 2
  klaviyo.com: 2
  shopify.com: 1
  shopifysvc.com: 7
  signifyd.com: 1
  wknd.ai: 1
  zdassets.com: 1
 extended:
  ##.ot-sdk-show-settings
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by jimmysofat6864** [comment]
> Test again in a new browser profile with only uBO and its default settings.

Already tested that with the same issue. Also account isn't needed to leave a review anybody can do it. 

<img width="1680" alt="Screen Shot 2024-08-20 at 9 38 18 AM" src="https://github.com/user-attachments/assets/ed6c436d-7d50-47aa-b21d-a353c938d36c">

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||iesnare.com^$script,3p,redirect=noopjs,domain=ridejetson.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by jimmysofat6864** [comment]
> `https://ridejetson.com/products/copperhead-extreme-terrain-electric-scooter`

I tried writing a review but nothing appears to be happening when I press the post review button.

**Comment by stephenhawk8054** [comment]
Remove the previous filter. Can you test this?

```adb
@@||mpsnare.iesnare.com/snare.js^$script,domain=ridejetson.com
```

**Comment by jimmysofat6864** [comment]
> Remove the previous filter. Can you test this?
> 
> ```
> @@||mpsnare.iesnare.com/snare.js^$script,domain=ridejetson.com
> ```

That worked review went through.
