### ISSUE TITLE
ajc.com: nuisance

### ISSUE THREAD

**Issue by jmbphd** [uBlockOrigin/uAssets#24966]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ajc.com/politics/trumps-pit-bulls-on-georgia-election-board-face-new-pressure/M3DPD4IUSZAD3EG2C7W75ON6NQ/`

### Category

nuisance

### Description

Upon loading, when I begin scrolling down the page and overlay asking me to login or subscribe appears across the bottom of the page.

### Other extensions used

Bypass Paywalls Clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="871" alt="image" src="https://github.com/user-attachments/assets/d2710a8e-f0c2-448b-960a-ff1e7a53e991">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 158985
 cosmetic: 91294
 scriptlet: 28030
 html: 2176
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5923-34, 1m
  adguard-popup-overlays: 27826-291, 1m
  adguard-mobile-app-banners: 5405-25, 1m
  adguard-other-annoyances: 14893-346, 1m
  adguard-widgets: 2639-16, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 39903-125, now
  ublock-badware: 10462-6, now
  ublock-privacy: 1059-4, now
  ublock-unbreak: 2556-1, now
  ublock-quick-fixes: 155-4, now
  easylist: 85356-181, now
  easyprivacy: 53042-65, now
  urlhaus-1: 29965-0, now
  plowe-0: 3547-993, now
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 771 ms
 maxAssetCacheWait: 316 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  ajc.com: 2
  chartbeat.com: 1
  cxense.com: 1
  facebook.net: 1
  go-mpulse.net: 2
  google-analytics.com: 1
  googletagmanager.com: 2
  htlbid.com: 2
  impactcdn.com: 1
  includemodal.global.ssl.fastly.net: 1
  litix.io: 2
  npttech.com: 1
  ntv.io: 2
  unwieldyimpulse.com: 1
 extended:
  ##.arc_ad
  ##html:style(overflow:auto!important)
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
  ##a[href^="https://twitter.com/intent/follow?"]
```
</details>

**Comment by stephenhawk8054** [comment]
It's paywall. You can use these as your custom filters:

```adb
||tinypass.com^$domain=ajc.com
ajc.com##.story-paygate_placeholder:remove-class(story-paygate_placeholder)
```
