### ISSUE TITLE
[Fake Button, Ads] streamwoop.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2497]
### URL(s) where the issue occurs

`https://streamwoop.tv/replay/Berisha-sent-off-2nd-Yellow-Card-for-diving-and-1st-yellow-for-complaining-to-the-ref`

`https://streamwoop.net/`

### Describe the issue

Fake button and ads. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/41137601-3adc32dc-6a99-11e8-8ffd-d824e96c7bf7.png)
![image](https://user-images.githubusercontent.com/7283682/41137605-455c4cba-6a99-11e8-81f7-6ae06af72f36.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.8

### Settings

All default

**Comment by mapx-** [comment]
```
streamwoop.net##[href="https://www.varanida.com/download"]
streamwoop.net##[href^="https://taptaptop.streamwoop.tv/imp"]
```
@ryanbr @Khrin
