### ISSUE TITLE
financial.mtcremix.com: detection

### ISSUE THREAD

**Issue by 123SONIC321** [uBlockOrigin/uAssets#24979]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://financial.mtcremix.com/`

### Category

detection

### Description

Detects AdBlocker

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-08-21-10-54-56-391_org mozilla fennec_fdroid](https://github.com/user-attachments/assets/026de03c-da59-42aa-8bff-b6fe56eea2b4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 125
filterset (summary):
 network: 377794
 cosmetic: 240423
 scriptlet: 54280
 html: 2199
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl/: 171432-0, 22m
  https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianAnnoyance.txt: 8-0, 3m
  https://raw.githubusercontent.com/furkun/Anti-IP-Grabber-Hosts/main/hosts: 1013-54, 3m
  https://secure.fanboy.co.nz/fanboy-annoyance.txt: 83832-247, 3m
  adguard-generic: 84242-8406, 3m
  adguard-spyware-url: 1648-124, 3m
  adguard-spyware: 79745-5287, 3m
  block-lan: 71-0, 3m
  curben-phishing: 527-22, 3m
  adguard-cookies: 31038-3866, 3m
  ublock-cookies-adguard: 1639-42, 3m
  fanboy-cookiemonster: 51691-51691, 3m
  [13 lists not shown]: [too many]
 default:
  user-filters: 39-0, never
  ublock-filters: 40415-329, 22m Δ
  ublock-badware: 10520-923, 22m Δ
  ublock-privacy: 1062-25, 22m Δ
  ublock-unbreak: 2560-6, 22m Δ
  ublock-quick-fixes: 158-4, 22m Δ
  adguard-mobile: 9650-714, 3m
  easylist: 85392-28964, 22m Δ
  easyprivacy: 53053-28843, 22m Δ
  urlhaus-1: 29365-239, 3m
  plowe-0: 3547-2688, 3m
filterset (user): [array of 36 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1409 ms (selfie)
 maxAssetCacheWait: 646 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  mtcremix.com: 1
  doubleclick.net: 4
  googlesyndication.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  ##a[id][href="https://toolkitspro.com"][rel="noopener noreferrer…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by mapx-** [comment]
it's some shortener / hosting site

ask for help here:
https://github.com/uBlockOrigin/uAssets/discussions/17361

**but provide the original link**
