### ISSUE TITLE
play.max.com: ads

### ISSUE THREAD

**Issue by daenyraine** [uBlockOrigin/uAssets#24976]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://play.max.com/video/watch/97719e6c-53f1-41dd-8aa4-39069f7dca90/8666d2b8-c648-4012-9dd0-6e9d37af9c62`

### Category

ads

### Description

When starting new video, loading screen spinning wheel will overlay player, sometimes preventing usage of media bar completely. Loading screen will not always play, just most times when starting new video.

### Other extensions used

Honey, DuckDuckGo Privacy Essentials, Dark Reader

### Screenshot(s)

![image](https://github.com/user-attachments/assets/e1caea98-fb35-49de-bca8-7440ed4ee628)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 159479
 cosmetic: 103370
 scriptlet: 28394
 html: 2176
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5924-34, 6m Δ
  adguard-popup-overlays: 27836-291, 7m
  adguard-mobile-app-banners: 5410-25, 7m
  adguard-other-annoyances: 14894-346, 7m
  adguard-widgets: 2640-16, 7m
  easylist-annoyances: 4720-293, 7m
  easylist-chat: 206-17, 7m
  easylist-newsletters: 7665-566, 7m
  easylist-notifications: 3476-1544, 7m
 default:
  user-filters: 0-0, never
  ublock-filters: 39958-125, 1h.25m Δ
  ublock-badware: 10516-6, 1h.25m Δ
  ublock-privacy: 1061-4, 1h.25m Δ
  ublock-unbreak: 2556-1, 1h.25m Δ
  ublock-quick-fixes: 156-4, 1h.25m Δ
  easylist: 85374-181, 1h.25m Δ
  easyprivacy: 53047-65, 1h.25m Δ
  urlhaus-1: 29100-0, 3m
  plowe-0: 3547-993, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 100 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  max.com: 7
  app.link: 3
  brightline.tv: 2
  demdex.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  litix.io: 6
 extended:
  ##+js(json-prune, ssaiInfo fallback.ssaiInfo)
  ##+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="Seg…
  ##+js(json-prune, adtech-brightline adtech-google-pal adtech-iab…
```
</details>

**Comment by xdmds** [comment]
I am experiencing the same issue with the same versions of firefox and ublock origin.

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/22074

We cannot investigate without the accounts. If anyone is willing to share account credentials, please comment in that thread and I'll give you an email.
