### ISSUE TITLE
client.falixnodes.net: Breakage/Dection

### ISSUE THREAD

**Issue by SmtWarren** [uBlockOrigin/uAssets#24978]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
client.falixnodes.net/server/console
```

### Description

When using client.falixnodes.net/server/console, it detects uBlock and when disabling JavaScript to prevent detection it breaks the main server console used for the site. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="889" alt="Screenshot 2024-08-20 at 3 59 39 PM" src="https://github.com/user-attachments/assets/6dfac204-e27a-40c4-8943-6c43182a6447">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 337327
 cosmetic: 327973
 scriptlet: 61425
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84233-8840, 4d.11h.50m
  adguard-mobile: 9637-252, 4d.11h.49m
  adguard-spyware-url: 1642-123, 4d.11h.49m
  adguard-spyware: 87772-29820, 4d.11h.50m
  block-lan: 70-0, 9d.18h.41m
  curben-phishing: 537-0, 18h.30m
  adguard-cookies: 30949-1720, 4d.11h.50m
  ublock-cookies-adguard: 1549-1549, 2d.18h.25m
  fanboy-cookiemonster: 67894-36241, 2d.18h.24m
  ublock-cookies-easylist: 1549-6, 2d.18h.24m
  adguard-social: 23300-1566, 4d.11h.50m
  fanboy-social: 16886-10706, 2d.18h.24m
  [47 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39783-1068, 1h.52m Δ
  ublock-badware: 10489-14, 1h.52m Δ
  ublock-privacy: 1068-4, 1h.52m Δ
  ublock-unbreak: 2497-12, 1h.52m Δ
  ublock-quick-fixes: 165-0, 1h.52m Δ
  easylist: 85375-15328, 1h.52m Δ
  easyprivacy: 53047-1041, 1h.52m Δ
  urlhaus-1: 29600-0, 18h.30m
  plowe-0: 3556-16, 6d.4h.58m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 colorBlindFriendly: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
 tooltipsDisabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 572 ms (selfie)
 maxAssetCacheWait: 278 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 46
 network:
  falixnodes.net: 1
  2mdn.net: 2
  4dex.io: 2
  amazon-adsystem.com: 1
  casalemedia.com: 1
  cloudflareinsights.com: 2
  criteo.com: 1
  doubleclick.net: 1
  google.com: 2
  googlesyndication.com: 8
  googletagmanager.com: 1
  id5-sync.com: 1
  kueezrtb.com: 6
  minutemedia-prebid.com: 1
  onetag-sys.com: 1
  polyfill.io: 1
  rubiconproject.com: 6
  script.ac: 1
  smartadserver.com: 3
  snigelweb.com: 3
  yellowblue.io: 1
 extended:
  ##+js(remove-node-text, script, /detectAdBlock|\(typeof [a-z]{10…
  ##+js(trusted-replace-node-text, script, typeof window.loadscrip…
  ##+js(trusted-replace-node-text, script, (window.loadscript, (wi…
  ##+js(abort-on-property-write, detectAdBlock)

```
</details>

**Comment by zenstorage** [comment]
You have many lists, one of them is causing the detection. Try using the default uBO or create a new profile in the browser with just uBO default.

**Comment by SmtWarren** [comment]
Thank you i reset uBO and its working now.
