### ISSUE TITLE
[nsfw] sexinsex.net: detection

### ISSUE THREAD

**Issue by loveqianool** [uBlockOrigin/uAssets#24974]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://sexinsex.net/bbs/forum-383-1.html`

### Category

detection

### Description

请关闭广告屏蔽插件以支持我们的网站

我们依赖广告来维持网站的运营，请关闭广告屏蔽插件并刷新页面。

--

**Please disable the adblock plugin to support our site!**

**We rely on ads to keep our site running, please turn off adblocking plugins and refresh the page.**

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240820-204103_Paranoid_Launcher](https://github.com/user-attachments/assets/1389aff0-3c4b-4813-90ef-7548d2eaebd4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 130
filterset (summary):
 network: 168798
 cosmetic: 67106
 scriptlet: 21054
 html: 1920
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40396-187, 29m Δ
  ublock-badware: 10510-7, 29m Δ
  ublock-privacy: 1060-4, 29m Δ
  ublock-unbreak: 2559-3, 29m Δ
  ublock-quick-fixes: 156-4, 29m Δ
  adguard-mobile: 9646-11, 1m
  easylist: 85374-254, 29m Δ
  easyprivacy: 53047-73, 29m Δ
  urlhaus-1: 29100-0, 1m
  plowe-0: 3547-1067, 1m
  CHN-0: 25467-218, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1001 ms (selfie)
 maxAssetCacheWait: 109 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  sexinsex.net: 8
  googletagmanager.com: 1
 extended:
  ###ad_headerbanner
  ##.ad_text
```
</details>

**Comment by zenstorage** [comment]
It needs an account, but from what I could see, try:
```adb
||/adblock.js$domain=sexinsex.net
```

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you check this?

**Comment by cjx82630** [comment]
already blocked by the https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt or https://filters.adtidy.org/extension/ublock/filters/220.txt
