### ISSUE TITLE
cined.com: detection

### ISSUE THREAD

**Issue by joskezelensky** [uBlockOrigin/uAssets#24975]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cined.com/new-google-ai-image-upscaling-makes-science-fiction-a-reality/`

### Category

detection

### Description

```
We need your support!
Please disable your ad blockers for cined.com
Ads help keep the lights on.

Turn off your ad blocker to keep supporting CineD.

```
is the error i'm getting

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 291760
 cosmetic: 48055
 scriptlet: 22153
 html: 0
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl/: 172349-7011, 3m
 default:
  user-filters: 22-2, never
  ublock-filters: 39780-284, 3m Δ
  ublock-badware: 10514-6, 3m Δ
  ublock-privacy: 1068-2, 3m Δ
  ublock-unbreak: 2497-0, 3m Δ
  ublock-quick-fixes: 165-0, 3m Δ
  easylist: 85374-27386, 3m Δ
  easyprivacy: 53047-647, 3m Δ
  urlhaus-1: 29100-0, now
  plowe-0: 3547-0, now
filterset (user): [array of 22 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 269 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cined.com: 2
  cloudflareinsights.com: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  matomo.cloud: 1
  webpushr.com: 1
 extended:
  ###header-ads
  ##.header-ads-container
  ##.widget-ad
  ##.ads-desktop
  ##.ad-item
  ##.ads-large
  ##.ads-mobile
  ##.ads-label
  ##.content-leaderboard-ad
  ###right-widget-top-ads_widget-23
  ###right-widget-b-ads_widget-9
  ###right-widget-c-ads_widget-7
  ###right-widget-d-ads_widget-36
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by JobcenterTycoon** [comment]
It got fixed in the `uBlock filters – Annoyances` filterlist which can be enabled in the filterlist panel.
