### ISSUE TITLE
animeyabu.org: detection

### ISSUE THREAD

**Issue by gv01d** [uBlockOrigin/uAssets#24987]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.animeyabu.org/videos/31914`

### Category

detection

### Description

It pops up a diferent video when using any addblock

### Other extensions used

return dislikes, yt video and audio dowloader, lenguage tool, colorZilla, youtube noonstop, enhancer for youtube, google translator for firefox amd MyJDowloader Browser Extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153394
 cosmetic: 47809
 scriptlet: 20629
 html: 1922
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39683-125, now
  ublock-badware: 10560-6, now
  ublock-privacy: 1061-4, now
  ublock-unbreak: 2556-1, now
  ublock-quick-fixes: 158-4, now
  easylist: 85426-182, now
  easyprivacy: 53052-65, now
  urlhaus-1: 29245-0, now
  plowe-0: 3547-993, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2498 ms
 maxAssetCacheWait: 82 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  adskeeper.co.uk: 2
  anitube.vip: 1
  arc.io: 2
  deckedsi.com: 2
  disqus.com: 3
  evykssdlrp.xyz: 1
  googletagmanager.com: 1
  jwpcdn.com: 1
  popads.net: 3
 extended:
  ##div[id*="ScriptRoot"]
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by stephenhawk8054** [comment]
It looks like a bait connection. Should we allow for all?

**Comment by D4niloMR** [comment]
Same as #24575

**Comment by D4niloMR** [comment]
We can fix ~10 sites with (both baits)

```adb
@@||ads.anitube.vip^$xhr
@@||www.popads.net/js/adblock.js
```

`https://www.google.com/search?q="Patrocinador+●+スポンサー"`

**Comment by Yuki2718** [comment]
Are all these sites Spanish/Portuguese and can I just copy to AdGuard Spanish/Portuguese ?

**Comment by Yuki2718** [comment]
The script sets `isAdblockActive` to false so we can redirect to `prebid-ads.js`.

**Comment by Yuki2718** [comment]
```
@@||ads.anitube.vip^|$xmlhttprequest
@@||ads.anitube.vip/*.php|$xmlhttprequest
@@||ads.anitube.vip/?token=$xmlhttprequest
```
are included in AdGuard Spanish/Portuguese. Some rules in our list can be removed later.

**Comment by D4niloMR** [comment]
Yes, these are all brazilian sites. You can also add

```
animefire.info|animesonlinecc.us|animesup.info|animeyabu.net|animeyabu.org|anitube.vip|dattebayo-br.com|drstonebr.com|goanimes.vip|goyabu.us|hinatasoul.com|isekaibrasil.com|meuanime.info|otakuanimess.net
```
