### ISSUE TITLE
lovepet.cn: breakage

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#24989]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lovepet.cn/a/maomibaike/zhidao/2020/0212/12800.html`

### Category

breakage

### Description

Menu in this site couldn't pop-up when uBlock Origin enabled on Fenix (Firefox for Android). 

### Other extensions used

N/A. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-08-22-16-15-09-050_org mozilla firefox-edit](https://github.com/user-attachments/assets/3b476b85-4a00-4e5f-a4e8-cdd73f5591df)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 251291
 cosmetic: 108223
 scriptlet: 39981
 html: 1922
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84423-4141, 4m
  adguard-spyware-url: 1648-124, 5m
  adguard-spyware: 79752-1551, 5m
  block-lan: 71-0, 5m
  curben-phishing: 503-2, 6m
  dpollock-0: 11694-486, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 40135-127, 2m
  ublock-badware: 10576-6, 4m
  ublock-privacy: 1062-4, 4m
  ublock-unbreak: 2567-1, 4m
  ublock-quick-fixes: 158-4, 4m
  adguard-mobile: 9650-107, 4m
  easylist: 85426-2570, 4m
  easyprivacy: 53056-26407, 5m
  urlhaus-1: 29245-0, 6m
  plowe-0: 3547-1488, 6m
  CHN-0: 25489-243, 5m
filterset (user): [empty]
userSettings:
 prefetchingDisabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 571 ms (selfie)
 maxAssetCacheWait: 189 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  baidu.com: 1
  bootcdn.net: 6
  googlesyndication.com: 2
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
```
</details>

**Comment by 0x391F** [comment]
This bug still reproduce when AdGuard Chinese list is diabled.

**Comment by mapx-** [comment]
The domain `bootcdn.net` being blocked in the site belongs to polyfill.io who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.
