### ISSUE TITLE
[nsfw] techlike.net: detection

### ISSUE THREAD

**Issue by malitoporra** [uBlockOrigin/uAssets#24986]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://techlike.net/power-players-fan-experience-technology/`

### Category

detection

### Description

When I start to advance, I start on this website: https://stfly.biz/7hqSy then the problem is elsewhere, it only appears in step number 6, following the order, until I get here: https://techlike.net/why -you-shouldnt-measure-seo-performance-solely-by-roi/ (note: if you click on it, without following the initial steps, everything will appear to be normal)

### Other extensions used

no another extensions 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 154336
 cosmetic: 51936
 scriptlet: 22589
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39506-394, now Δ
  ublock-badware: 10558-26, now Δ
  ublock-privacy: 1068-4, now Δ
  ublock-unbreak: 2499-15, now Δ
  ublock-quick-fixes: 167-0, now Δ
  easylist: 85426-49, now Δ
  easyprivacy: 53052-680, now Δ
  urlhaus-1: 28850-0, 35m
  plowe-0: 3559-372, 12d.20h.45m
  spa-1: 5930-59, 2d.19h.38m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
  ##.clever-core-ads
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

@malitoporra For future shortener sites, comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361

Don't open new issues about these sites.
