### ISSUE TITLE
fxmag.pl: detection

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uAssets#24996]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.fxmag.pl/finanse-osobiste/tak-dzialaja-dofinansowania-rzad-zwieksza-o-dwa-tysiace-firma-podnosi-ceny`

### Category

detection

### Description

AA dialog after ~15s.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0664dc8c-1cbc-4d78-9dcb-01f7c35d9644)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 155072
 cosmetic: 0
 scriptlet: 20844
 html: 1932
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39696-10953, now Δ
  ublock-badware: 10622-718, now Δ
  ublock-privacy: 1061-16, now Δ
  ublock-unbreak: 2564-366, now Δ
  ublock-quick-fixes: 159-46, now
  easylist: 85392-36000, now Δ
  easyprivacy: 53057-70, now Δ
  urlhaus-1: 29365-0, now
  plowe-0: 3555-997, 11d.7h.56m
  POL-0: 8763-7498, now
  POL-2: 1283-847, 1d.8h.1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 560 ms
 maxAssetCacheWait: 192 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 3
  imasdk.googleapis.com: 2
  onnetwork.tv: 15
  pushpushgo.com: 2
 extended:
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by garry-ut99** [comment]
Info: it's fixed with "AdGuard – Ads" enabled, related issue:
- https://github.com/AdguardTeam/AdguardFilters/issues/184088

(not that I'm saying it shouldn't be fixed separately in uAssets, but might be helpful)

**Comment by stephenhawk8054** [comment]
```adb
fxmag.pl##+js(no-xhr-if, googlesyndication)
```

@MajkiIT Sorry, can you check this?

**Comment by garry-ut99** [comment]
It works. Besides, there are many empty ad lefotovers with text "Reklama", example:
`fxmag.pl##text, [class*="Container_header_ad_"] > div[style^="min-height"]`

**Comment by garry-ut99** [comment]
The ad placeholder atop header is still here:
![ss_19](https://github.com/user-attachments/assets/44f7fa87-853f-4326-8e42-9e40a66a4390)
