### ISSUE TITLE
webnovelworld.org: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#24991]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.webnovelworld.org/`

### Category

nuisance

### Description

Advertisment leftover 

### Other extensions used

non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-22 132813](https://github.com/user-attachments/assets/e24cf09a-09a5-461e-ae74-26e62e14f811)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 300942
 cosmetic: 291677
 scriptlet: 56432
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4332-9, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-132, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 484-0, now
  https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all: 2098-1, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 34-1, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-0, now
  CHN-0: 25489-129, now
  JPN-1: 15135-79, now
  KOR-1: 5071-57, now
  adguard-cookies: 31103-80, now
  [22 lists not shown]: [too many]
 default:
  user-filters: 69-0, never
  DEU-0: 7541-5, now
  easylist: 85392-3198, now
  easyprivacy: 53057-1005, now
  plowe-0: 3547-2, now
  ublock-badware: 10588-9, now
  ublock-filters: 39518-4145, now
  ublock-privacy: 1068-120, now
  ublock-quick-fixes: 168-0, now
  ublock-unbreak: 2505-6, now
  urlhaus-1: 29245-1, now
filterset (user): [array of 70 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 70 redacted]
hostRuleset:
 added: [array of 104 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings:
 debugScriptlets: true
 loggerPopupType: normal
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 7130 ms
 maxAssetCacheWait: 2446 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  webnovelworld.org: 2
  duckduckgo.com: 5
  googletagmanager.com: 1
  inmobi.com: 1
  pubfuture-ad.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`webnovelworld.org##.tYRDL_ks`

**Comment by big-cat-loaf** [comment]
doesn't work! 
![20240611_172325](https://github.com/user-attachments/assets/9c5a960f-5c11-432d-8f33-c46afd15ea4e)

**Comment by big-cat-loaf** [comment]
doesn't work 
![Screenshot 2024-08-22 180117](https://github.com/user-attachments/assets/7a782328-1422-4c0c-9b4a-d4c9ca94f572)

**Comment by D4niloMR** [comment]
```
webnovelworld.org###pfvidad
webnovelworld.org###chapter-container > div[class]:has([id^="pf-"])
webnovelworld.org##.comment-list > div[class]:has([id^="pf-"])
```

**Comment by big-cat-loaf** [comment]
works partly, found https://www.webnovelworld.org/ranking-04061612 were it doesn't work 
![Screenshot 2024-08-22 211600](https://github.com/user-attachments/assets/275e21cd-4ab8-4c0c-b58b-a3247dfb8746)
