### ISSUE TITLE
avis.com.tr: breakage

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#24999]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.avis.com.tr/`

### Category

breakage

### Description

on this car rental site, when ublock is enabled, after selecting the pickup and return date, after pressing the "Rent X days" button, nothing happens, but when ublock is off, the vehicles come out, so it works smoothly

### Other extensions used

fastforward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240822_204925](https://github.com/user-attachments/assets/463605ed-6bab-4b37-9e32-7a2657d1aaf1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 129
filterset (summary):
 network: 250198
 cosmetic: 270339
 scriptlet: 57505
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84412-7658, now
  adguard-spyware-url: 1648-123, now
  adguard-spyware: 79767-27043, now
  block-lan: 71-0, now
  curben-phishing: 499-0, now
  adguard-cookies: 31116-94, now
  ublock-cookies-adguard: 1644-1644, now
  fanboy-cookiemonster: 51702-4038, now
  ublock-cookies-easylist: 1644-9, now
  adguard-social: 23338-793, now
  fanboy-social: 16937-22, now
  fanboy-thirdparty_social: 68-0, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39965-686, 1h.12m Δ
  ublock-badware: 10614-6, 1h.12m Δ
  ublock-privacy: 1069-2, 1h.12m Δ
  ublock-unbreak: 2508-1, 1h.12m Δ
  ublock-quick-fixes: 168-0, 1h.12m Δ
  adguard-mobile: 9651-98, now
  easylist: 85392-882, 1h.12m Δ
  easyprivacy: 53057-837, 1h.12m Δ
  urlhaus-1: 29400-0, now
  plowe-0: 3547-0, now
  TUR-0: 13588-31, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3902 ms (selfie)
 maxAssetCacheWait: 617 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  clarity.ms: 1
  googletagmanager.com: 1
  netmera-web.com: 2
  pingdom.net: 1
 extended:
  ##.social-list:not(html):not(body)
  ###cookieModule
  ##.modal
```
</details>

**Comment by stephenhawk8054** [comment]
Edge Mobile is not officially supported. Test again in Firefox Mobile with only uBO and its default settings.

**Comment by Raidware** [comment]
> Edge Mobile is not officially supported. Test again in Firefox Mobile with only uBO and its default settings.

same.

**Comment by stephenhawk8054** [comment]
In Firefox, can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?
