### ISSUE TITLE
timesofindia.indiatimes.com: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#24992]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://timesofindia.indiatimes.com/life-style/health-fitness/fitness/11-minutes-of-walking-can-unlock-these-11-benefits/articleshow/112661386.cms`

### Category

nuisance

### Description

get a social button (whatsapp) icon popup on the middle right of my screen when using firefox with ublock origin on android. Enabling easylist social didn't help.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 163587
 cosmetic: 113552
 scriptlet: 29961
 html: 2179
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2668-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 338-0, now
  adguard-spyware-url: 1648-240, now
  curben-phishing: 503-2, 13m
  fanboy-cookiemonster: 51702-186, now
  ublock-cookies-easylist: 1606-13, now
  fanboy-social: 16936-10, now
  ublock-annoyances: 5925-65, now
  NOR-0: 4720-11, now
 default:
  user-filters: 1-0, never
  ublock-filters: 39696-125, now
  ublock-badware: 10622-6, now
  ublock-privacy: 1061-53, now
  ublock-unbreak: 2564-1, now
  ublock-quick-fixes: 159-4, now
  easylist: 85392-182, now
  easyprivacy: 53057-65, now
  urlhaus-1: 29245-0, 13m
  plowe-0: 3547-993, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 700 ms (selfie)
 maxAssetCacheWait: 182 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 37
 network:
  indiatimes.com: 4
  amazon-adsystem.com: 1
  clmbtech.com: 1
  cookielaw.org: 1
  debugbear.com: 1
  doubleclick.net: 1
  google.com: 3
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  scorecardresearch.com: 1
  survicate.com: 1
  toiimg.com: 3
  tvid.in: 18
 extended:
  ##div[class*="personaliseWidgetLoader"]
  ##.CeUoi
  ##.mgid_second_mrec_parent
  ##.paisa-wrapper
  ##.relatedVideoWrapper
  ##.topBand_adwrapper
  ##[data-contentprimestatus]
  ##.wdt-taboola
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adplaceholder
  ##.nonAppView > div div[class]:not([id]) > div[id^="div-gpt-ad"]…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, nsShowMaxCount, 0)
  ##+js(addEventListener-defuser, , adb)
  ##+js(no-setTimeout-if, adb)
  ##+js(prevent-fetch, tvid.in/log/)
  ##+js(addEventListener-defuser, copy)
```
</details>

**Comment by mapx-** [comment]
enable `AdGuard – Social Widgets`

or add:

`indiatimes.com##.UvMqU`
