### ISSUE TITLE
animeyabu.net: detection

### ISSUE THREAD

**Issue by FrostMage5** [uBlockOrigin/uAssets#24998]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.animeyabu.net/`__

### Category

detection

### Description

is detecting ublock origin

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20240822-132701](https://github.com/user-attachments/assets/a790dbe4-e14a-4b47-8708-0b08e8b5653a)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 124
filterset (summary):
 network: 156365
 cosmetic: 60292
 scriptlet: 22672
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  adguard-mobile: 9651-97, 1h.39m
  easylist: 85392-674, 1h.39m
  easyprivacy: 53057-668, now Δ
  plowe-0: 3547-0, 1h.37m
  spa-1: 5942-17, 1h.39m
  ublock-badware: 10614-6, now Δ
  ublock-filters: 39965-360, now Δ
  ublock-privacy: 1069-2, 1h.37m
  ublock-quick-fixes: 168-0, now Δ
  ublock-unbreak: 2508-4, now Δ
  urlhaus-1: 29400-0, 1h.39m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2103 ms (selfie)
 maxAssetCacheWait: 245 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  adskeeper.co.uk: 2
  arc.io: 2
  deckedsi.com: 2
  disqus.com: 1
  googletagmanager.com: 1
  jwpcdn.com: 1
  popads.net: 3
 extended:
  ##div[id*="ScriptRoot"]
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by D4niloMR** [comment]
Fixed here https://github.com/uBlockOrigin/uAssets/commit/620b797a7f6f5350d4544ea601116b0f2d27830a

Click on this link to update filters https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1

**Comment by FrostMage5** [comment]
How do you install these filters?

**Comment by D4niloMR** [comment]
You can click on the link above or add these in "My filters"

```
@@||ads.anitube.vip^$xhr,domain=animeyabu.net
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=animeyabu.net
@@||www.popads.net/js/adblock.js$xhr,domain=animeyabu.net
```

**Comment by FrostMage5** [comment]
This filter worked perfectly and really helped me avoid that annoying video asking me to disable my AdBlock on sites like this. I was trying several solutions and nothing worked, Thank you very much for investing your time and knowledge to help the community.
