### ISSUE TITLE
[nsfw] galactic-worship.com: popups

### ISSUE THREAD

**Issue by iamrazab** [uBlockOrigin/uAssets#24994]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://galactic-worship.com/lp-ebook/?utm_medium=Special_Interest&utm_source=easyaffiliate&utm_campaign=1279&utm_content=LandingPage_Ebook_Keyword&emid=66c741fd54974222e408b5f5&trs=66c741fd54974222e408b5f4&ext_publisher_id=1279&fn=A+Silent+Voice+%282016%29+Multi+Audio+_Hindi-English-Japanese_+720p+Bluray+ESubs+%5BBollyFlix%5D.mkv`

### Category

Adware Site

### Description

Adware Site

### Other extensions used

Adware Site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 153808
 cosmetic: 53287
 scriptlet: 22951
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 420-1, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 3965-36, 1h.5m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2114-1, now
 default:
  user-filters: 6-0, never
  ublock-filters: 39519-135, 5m Δ
  ublock-badware: 10620-6, 5m Δ
  ublock-privacy: 1068-2, 5m Δ
  ublock-unbreak: 2505-0, 5m Δ
  ublock-quick-fixes: 168-0, 5m Δ
  easylist: 85392-581, 5m Δ
  easyprivacy: 53057-817, 5m Δ
  urlhaus-1: 29400-0, 1h.6m
  plowe-0: 3547-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 421 ms (selfie)
 maxAssetCacheWait: 143 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
How did you get the page above ? clicking what other page / link ?
