### ISSUE TITLE
rule34hentai.net mobile [nsfw]

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2499]
### URL(s) where the issue occurs

`https://rule34hentai.net/post/list/d.va/`

### Describe the issue

Site content does not load

### Screenshot(s)

https://fotos.subefotos.com/50e2c6287a5b632c11bcd8ac698de57fo.png

### Settings

-Default settings

### Notes

`@@||rule34hentai.net^$csp=script-src 'self' *.googleapis.com` fixes it, but that is clearly not a final solution.

**Comment by mapx-** [comment]
The site is correctly loaded for me (tested in FF / chrome)

**Comment by zaphodbeebblebrox** [comment]
To reproduce:
Open Firefox
Open the developer console and click on the button labeled responsive design mode
Switch the device to Apple iPad Air 2
Go to `https://rule34hentai.net/post/list/D.Va/1`

**Comment by mapx-** [comment]
ok, modified the csp filter, could you test again ?

**Comment by zaphodbeebblebrox** [comment]
It works.

**Comment by krystian3w** [comment]
Firefox do not have "Switch the device to Apple iPad Air 2" in "responsive design mode" or I do not know about something?
