### ISSUE TITLE
walla.co.il - Video Ads

### ISSUE THREAD

**Issue by DanIbba** [uBlockOrigin/uAssets#250]
http://news.walla.co.il/item/3026999

video ads using "blob: + base 64"

![screen shot 2016-12-29 at 13 14 03](https://cloud.githubusercontent.com/assets/24211092/21543671/476d8bf6-cdd1-11e6-9013-d75d47652ad4.png)

- Browser/version: Chrome
- uBlock Origin version:  1.10.4

uBO's default settings

https://github.com/easylist/EasyListHebrew/issues/225

**Comment by SMed79** [comment]
@DanIbba Report here https://github.com/easylist/EasyListHebrew/issues

**Comment by nakoMaron** [comment]
By the screenshot you've sent, you are using ABP instead of UBO, can't reproduce on UBO.

**Comment by gorhill** [comment]
Report to EasyList Hebrew maintainers.
