### ISSUE TITLE
lifehacker.jp: breakage

### ISSUE THREAD

**Issue by r4oz8** [uBlockOrigin/uAssets#25003]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.lifehacker.jp/article/130926firefox_memory/
```

### Description

The article's text is not displaying.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 155438
 cosmetic: 60628
 scriptlet: 20834
 html: 1921
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39688-125, 14h.55m
  ublock-badware: 10567-6, 14h.54m
  ublock-privacy: 1061-4, 14h.55m
  ublock-unbreak: 2557-1, 14h.54m
  ublock-quick-fixes: 170-4, 10m
  easylist: 85415-182, 14h.55m
  easyprivacy: 53056-65, 14h.55m
  urlhaus-1: 29245-0, 14h.55m
  plowe-0: 3547-993, 5d.2h.58m
  JPN-1: 15138-89, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 112 ms (selfie)
 maxAssetCacheWait: 44 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `lifehacker.jp##div[class^="article_pArticle_Embed"]` in "AdGuard Japanese"

cc @Yuki2718
