### ISSUE TITLE
flashscoreusa.com: nuisance

### ISSUE THREAD

**Issue by swissmas** [uBlockOrigin/uAssets#25000]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.flashscoreusa.com/`

### Category

nuisance

### Description

Cookie notice stays on screen in loading state.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-22 at 2 02 20 PM](https://github.com/user-attachments/assets/f65b6fca-6ac2-4c43-98d0-ec54ca2fb11a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 161925
 cosmetic: 125417
 scriptlet: 30310
 html: 2179
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2668-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/youtube_clear_view.txt: 33-0, now
  adguard-spyware-url: 1648-240, now
  fanboy-cookiemonster: 51702-186, now
  ublock-cookies-easylist: 1606-13, now
  fanboy-social: 16937-10, now
  easylist-annoyances: 4726-45, now
  easylist-chat: 206-0, now
  easylist-newsletters: 7685-37, now
  easylist-notifications: 3478-163, now
  ublock-annoyances: 5925-81, now
 default:
  user-filters: 25-1, never
  ublock-filters: 39708-126, now
  ublock-badware: 10622-6, now
  ublock-privacy: 1061-53, now
  ublock-unbreak: 2565-1, now
  ublock-quick-fixes: 170-4, now
  easylist: 85422-182, now
  easyprivacy: 53060-65, now
  urlhaus-1: 29400-0, now
  plowe-0: 3547-993, now
filterset (user): [array of 25 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 autoUpdateDelayAfterLaunch: 10
 filterAuthorMode: true
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 199 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cookielaw.org: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.seoAdWrapper
  ##.adsenvelope
  ##.adstextpad
  ##.selfPromo__box--social
  ##.footer__advert
  ##.privacySettings:not(html):not(body)
  ##.optanon-show-settings
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
flashscoreusa.com##.otPlaceholder
```

@ryanbr
