### ISSUE TITLE
tyla.com: ads (placeholders)

### ISSUE THREAD

**Issue by Lord-McSweeney** [uBlockOrigin/uAssets#25009]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.tyla.com/news/crime/merseyside-detectives-the-murders-of-ashley-and-olivia-channel-4-393916-20240822
```

### Description

Tyla articles have large ADVERT boxes on the right side of the page, though with no ads in them.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/04e2d5e3-3ff9-42da-98f8-d55ee820fe4c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 153707
 cosmetic: 47808
 scriptlet: 20656
 html: 1922
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 39715-126, 5m Δ
  ublock-badware: 10622-6, 5m Δ
  ublock-privacy: 1061-4, 5m Δ
  ublock-unbreak: 2565-1, 5m Δ
  ublock-quick-fixes: 170-4, 5m Δ
  easylist: 85435-182, 5m Δ
  easyprivacy: 53062-65, 5m Δ
  urlhaus-1: 29450-0, now
  plowe-0: 3547-993, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 11 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2533 ms (selfie)
 maxAssetCacheWait: 96 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  github.com: 22
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
tyla.com##[class^="advert-placeholder_advertPlaceholder"]
```

@ryanbr
