### ISSUE TITLE
theguardian.com: ads

### ISSUE THREAD

**Issue by hazza4257** [uBlockOrigin/uAssets#25006]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.theguardian.com/australia-news/live/2024/aug/23/government-rapid-review-family-sexual-and-domestic-violence-prevention-rex-administration-hearing-anthony-albanese-peter-dutton-ntwnfb`

### Category

ads

### Description

uBlock no longer blocks any ads on The Guardian website. I tried to manually pick elements but the entire page is seemingly covered by one big element - called "###sv-content" - so I'm unable to add any filter without the whole page becoming blank. I tested this with the Chrome element inspector thing and I have the same issue - I can't even locate the elements corresponding to the banner ad across the top of the page. We have had some IT changes at work very recently but I'm not seeing this issue on any other site. I assume it's something done by the website owner to circumvent ad blockers.

### Other extensions used

Fullscreen Anthing 2
Old Reddit Redirect 2.0.0
PB Comments Plugin 0.8.15 (only applies to one niche website)
Return Youtube Dislike 3.0.0.16
Volume Booster 1.0.0

*I disabled all these and the issue persists.*

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![latest](https://github.com/user-attachments/assets/dbd45c0e-f9e8-439b-ad12-5f8672804f66)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153669
 cosmetic: 47882
 scriptlet: 22098
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39531-284, 7m
  ublock-badware: 10620-6, 7m
  ublock-privacy: 1068-2, 7m
  ublock-unbreak: 2498-0, 7m
  ublock-quick-fixes: 168-0, 8m
  easylist: 85422-569, 8m
  easyprivacy: 53057-647, 8m
  urlhaus-1: 29400-0, 8m
  plowe-0: 3547-0, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3062 ms
 maxAssetCacheWait: 16 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by hazza4257** [comment]
Hello,

I’m unable to install ublock from the chrome store on a new profile, I
imagine due to some organisational restriction. It seems it was only
installed on my main profile when I signed in and all my extension were
synced.

Could you pass me the link to manually download and “unpack” it into
chrome? I can’t find it in GitHub.

Thanks for your help.

Regards,
Liam Harris

**Comment by stephenhawk8054** [comment]
You can download from this: https://github.com/gorhill/uBlock/releases/tag/1.59.0

**Comment by hazza4257** [comment]
My org’s security policy is blocking the download. I guess I’ll just have
to give up for now! I’m sure if this is a genuine issue with the Guardian
site, you will get more people reporting this issue.

Regards,
Liam Harris

**Comment by stephenhawk8054** [comment]
It could be due to your org's policy set up in the browser / computer to whitelist the site.

As I can't reproduce the issue, I'll close for now. You can continue commenting here if you have more information. All volunteeres are notified with new comments.
