### ISSUE TITLE
wp57.localhost: breakage

### ISSUE THREAD

**Issue by Wutime** [uBlockOrigin/uAssets#25008]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://wp57.localhost/wp-admin/admin.php?page=wp_content_guard_demo_page`

### Category

breakage

### Description

uBlock prevents the default features of WordPress Carbon Fields from rendering options because it blocks the JavaScript.

It's this popular WordPress plugin for settings and options rendering in WordPress: `https://carbonfields.net/`

It blocks all carbon fields containers creating javascript issue:

 Uncaught TypeError: Cannot read properties of undefined (reading 'initialize')
    at admin.php?page=wp_content_guard_demo_page:1684:25

### Other extensions used

`https://carbonfields.net/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1353" alt="Screenshot 2024-08-23 at 1 34 00 AM" src="https://github.com/user-attachments/assets/29c2885d-79e5-4b4c-89d0-7b4cd76bf9dc">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 153726
 cosmetic: 47890
 scriptlet: 22129
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39541-284, 1h.36m Δ
  ublock-badware: 10620-6, 1h.36m Δ
  ublock-privacy: 1068-2, 1h.36m Δ
  ublock-unbreak: 2506-0, 1h.36m Δ
  ublock-quick-fixes: 179-0, 1h.36m Δ
  easylist: 85435-569, 1h.36m Δ
  easyprivacy: 53062-647, 1h.36m Δ
  urlhaus-1: 29450-0, now
  plowe-0: 3547-0, never
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 369 ms (selfie)
 maxAssetCacheWait: 19 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  wp57.localhost: 7
```
</details>

**Comment by stephenhawk8054** [comment]
Use [uBO's logger](https://github.com/gorhill/uBlock/wiki/The-logger) and check what are blocked in the logger.

**Comment by Wutime** [comment]
Thank you, I will do that this afternoon and figure it out.
