### ISSUE TITLE
filme.imyfone.com: breakage

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#25004]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://filme.imyfone.com/voice-changer/pricing/`

### Category

breakage

### Description

Cannot select Monthly, Yearly, and Lifetime buttons when U-Block is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/f924edcc-0cdf-4519-b97b-9c432d3ae4f1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153654
 cosmetic: 47792
 scriptlet: 20652
 html: 1922
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39709-126, 4m Δ
  ublock-badware: 10622-6, 4m Δ
  ublock-privacy: 1061-4, 4m Δ
  ublock-unbreak: 2565-1, 4m Δ
  ublock-quick-fixes: 170-4, 4m Δ
  easylist: 85422-182, 4m Δ
  easyprivacy: 53060-65, 4m Δ
  urlhaus-1: 29400-0, now
  plowe-0: 3547-993, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 262 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  imyfone.com: 6
  bing.com: 1
  clarity.ms: 2
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 1
 extended:
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||filme.imyfone.com/assets/js/gatrack.js^$script,1p
```

@ryanbr
