### ISSUE TITLE
shinigami03.com: ads

### ISSUE THREAD

**Issue by Zokala** [uBlockOrigin/uAssets#25011]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://shinigami03.com/`

### Category

ads

### Description

Betting sites ads

### Other extensions used

Buster captcha

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_2024-08-23-22-17-31-145_com kiwibrowser browser](https://github.com/user-attachments/assets/cb6ffc6f-d09e-4ef8-916c-72b862cf2c52)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 124
filterset (summary):
 network: 158993
 cosmetic: 61944
 scriptlet: 22255
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-1, never
  ublock-filters: 40017-363, 6m
  ublock-badware: 10656-6, 6m
  ublock-privacy: 1069-2, 2m Δ
  ublock-unbreak: 2504-0, 6m
  ublock-quick-fixes: 193-0, 6m
  adguard-mobile: 9649-105, 6m
  easylist: 85447-642, 6m
  easyprivacy: 53063-657, 7m Δ
  urlhaus-1: 28920-0, 20m
  plowe-0: 3545-0, now
  IDN-0: 10057-3, 20m
filterset (user): [array of 6 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 975 ms
 maxAssetCacheWait: 185 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  shinigami03.com: 4
  cloudflareinsights.com: 1
  doubleclick.net: 1
  histats.com: 1
 extended:
  ##[href^="https://domaininnovations.com/"]
  ##[href^="https://vpnnawala.site"]
```
</details>

**Comment by stephenhawk8054** [comment]
Please follow this thread: https://github.com/ABPindo/indonesianadblockrules/pull/573
