### ISSUE TITLE
worldsurfleague.com: breakage

### ISSUE THREAD

**Issue by Sharkinator1198** [uBlockOrigin/uAssets#25014]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.worldsurfleague.com/posts/533717/its-on-finals-day-of-the-corona-fiji-pro`

### Category

breakage

### Description

Video Player doesn't play when ublock is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153232
 cosmetic: 47834
 scriptlet: 20677
 html: 1922
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39748-126, 11m Δ
  ublock-badware: 10669-6, 11m Δ
  ublock-privacy: 1061-4, 11m Δ
  ublock-unbreak: 2560-1, 11m Δ
  easylist: 85449-182, 11m Δ
  easyprivacy: 53065-66, 11m Δ
  urlhaus-1: 28920-0, now
  plowe-0: 3545-993, now
  ublock-quick-fixes: 185-4, 11m Δ
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1847 ms (selfie)
 maxAssetCacheWait: 648 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  worldsurfleague.com: 2
  amazon-adsystem.com: 1
  doubleclick.net: 3
  extremereach.io: 1
  google-analytics.com: 2
  googleadservices.com: 2
  googletagmanager.com: 2
  gstatic.com: 2
  naivestatement.com: 1
  rubiconproject.com: 2
  snapchat.com: 1
 extended:
  #@#div[data-ad-targeting]
```
</details>

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, can uBO support redirecting to noop XML with the format of `VMAP` and `VAST`?

Currently, Adguard is supporting `noopvmap-1.0` and `noopvast-2/3/4.0`: https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#-available-redirect-resources

With this we don't need to allow and replace the ads connection

```adb
@@||pubads.g.doubleclick.net/gampad/ads?*www.worldsurfleague.com$xhr,domain=imasdk.googleapis.com
||pubads.g.doubleclick.net/gampad/ads?*www.worldsurfleague.com$xhr,domain=imasdk.googleapis.com,replace=/<vmap:VMAP.+//
```

I have to use replace because somehow `xml-prune` and `trusted-replace-xhr-response` don't work (it still logs successfully but it doesn't have effects like `replace`: the ads connections still occur).

But I think redirection to noop VMAP/VAST resources is still better.

**Comment by gorhill** [comment]
`noop-vmap1.0.xml` is already supported, see <https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/noop-vmap1.0.xml>. I can add the others.

**Comment by stephenhawk8054** [comment]
Confirm

```adb
||pubads.g.doubleclick.net/gampad/ads?*www.worldsurfleague.com$xhr,redirect=noop-vmap1.0.xml:5,domain=imasdk.googleapis.com
```

works for me.

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, I think there's VAST version 1.0 as well. It appears in this issue: https://github.com/uBlockOrigin/uAssets/issues/16014

The connection being allowed is `secure.adnxs.com/ptv` and the content looks like this

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><VAST version="4.2"><Ad id="511644551"></Ad></VAST>
```

**Comment by dimisa-RUAdList** [comment]
uBlock Origin 1.59.1b18 + RU AdList

I found a problem in Firefox: `https://fanserial.fun/748-kami-no-tou-2021-02-18-15-48/2-season/9-episode.html`

 When using `||v*.plrjs.org/*.xml$important,xmlhttprequest,redirect=noopvast-3.0` the player does not work, while in Google Chrome everything is fine. I had to add `fanserial.fun,fanserialstv.net##+js(json-prune, *.preroll)`, but this fixes the problem only on a couple of sites, while I would like to apply a universal rule that will work correctly everywhere.

**Comment by gorhill** [comment]
Probably because of <https://github.com/uBlockOrigin/uAssets/issues/25014>?

**Comment by dimisa-RUAdList** [comment]
In order for the rule `||v*.plrjs.org/*.xml$important,xmlhttprequest,redirect=noopvast-3.0` to work and break the player, you need to add the exception `fanserial.fun,fanserialstv.net##+js(json-prune, *.preroll)`.

**Comment by gorhill** [comment]
Ok so I get:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at data:text/xml;base64,PFZBU1QgdmVyc2lvbj0iMy4wIj48L1ZBU1Q+Cg==. (Reason: CORS request not http).

So same issue as <https://github.com/uBlockOrigin/uAssets/issues/25014>.

**Comment by gorhill** [comment]
I can make it work with that filter:

    fanserial.fun##+js(no-xhr-if, url:/v.*\.plrjs\.org\/.*\.xml/, war:noop-vast3.xml)

**Comment by dimisa-RUAdList** [comment]
The thing is, I'm trying to avoid site-specific fixes. This is a pretty popular player and there could be hundreds of sites like this. The idea was to use a single rule everywhere: `||v*.plrjs.org/*.xml$important,xmlhttprequest,redirect=noopvast-3.0`

This can't be fixed? In Google Chrome this rule works perfectly. Using this rule in AdGuard + FF also does not cause any problems.

**Comment by gorhill** [comment]
Oops, I used the wrong link in comments, I meant same issue as <https://github.com/uBlockOrigin/uBlock-issues/issues/1222>. this can't be fixed.

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Which filter did you use in Adguard?

**Comment by dimisa-RUAdList** [comment]
The one they have in RussianFilter: `||v*.plrjs.org/*.xml$xmlhttprequest,redirect=noopvast-3.0`

**Comment by stephenhawk8054** [comment]
If I'm not wrong, Adguard uses extension's ID (`moz-extension://extension-id`) to access `web-accessible-resources`, not `data:`. That would lead to no CORS error, but will leak extension's ID to the website. In Firefox, each extension ID after intalling is unique so leaking this ID is a privacy concern.

You can test by using the filter

```adb
||example.com^$xhr,redirect=noopvast-3.0
```

then load `https://example.com`, go to the console and type

```js
fetch('https://example.com').then(response => console.log(response));
```

This is the result with Adguard:

![image](https://github.com/user-attachments/assets/630f7790-9d8f-4fbf-9eb2-2770ca979d0f)

This is the result with uBO:

![image](https://github.com/user-attachments/assets/8cd5bd32-bc94-4b79-ac48-5444b6fb7e96)

**Comment by stephenhawk8054** [comment]
Not a perfect solution but this filter might help in unknown cases?

```adb
||cdn.plrjs.com/player/*.js^$script,replace=/preroll/nopreroll/g
```

It depends on the cache as well, so better to test when refreshing while bypassing the cache.

**Comment by dimisa-RUAdList** [comment]
I can't put this in RU AdList because trusted rules only work from uBlock filters.

**Comment by stephenhawk8054** [comment]
If they work fine, I'll put them to uAssets' lists

**Comment by stephenhawk8054** [comment]
@gorhill Could there be any ways to have some non-trusted `replace` versions that replace with the text in `war`? Currently with my above `replace` filter, I just simply remove all of the contents with `noopvast-3.0`

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
> If they work fine, I'll put them to uAssets' lists

Yes, it works fine, but for stable operation I will need to disable some rules for FF in RU AdList.

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList I have edited to have a full version of network filters for both Firefox and Chromium. Can you check again? They should work with your current scriptlet filters in RuAdlist. The only concern is the `important` since it will override the `@@||plrjs.org/*.xml^$3p,xhr`

---

On another note, I think non-trusted versions for `replace` like my comment above might help for regional lists. We did talk about a quite similar issue in https://github.com/uBlockOrigin/uAssets/issues/25164#issuecomment-2326647258 , but let's see how it turns out.

**Comment by dimisa-RUAdList** [comment]
No problem. I will disable `||v*.plrjs.org/*.xml$important,xmlhttprequest,badfilter,redirect=noopvast-3.0` for FF.

**Comment by dimisa-RUAdList** [comment]
Disabled: https://github.com/easylist/ruadlist/commit/5393f6c158cb2488b2537d9cb67df7d6ee0b9dbe

**Comment by stephenhawk8054** [comment]
Oh, forgot that `noopvast` is still in dev build, not in stable yet.

**Comment by dimisa-RUAdList** [comment]
That's why I haven't deleted it yet: `fanserial.fun,fanserialstv.net##+js(set-constant, Object.prototype.preroll, undefined)`

**Comment by gorhill** [comment]
> could there be any ways to have some non-trusted `replace` versions that replace with the text in `war`?

Would need to experiment with this.
