### ISSUE TITLE
webtoons.com: breakage

### ISSUE THREAD

**Issue by MDawg957** [uBlockOrigin/uAssets#25013]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.webtoons.com/en/`

### Category

breakage

### Description

When you click the Log In button on the top-left corner of the site, the login options do not appear as expected.

I'm in the US and login is not required to see the missing buttons. I've included screenshots with uBO enabled and what it should look like when you turn off uBO.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/aeaacbb5-1942-4a59-9caa-a37ed7f7f1be)
![image](https://github.com/user-attachments/assets/d497d8ce-b423-4cc1-81d9-5c2a3191722b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 160952
 cosmetic: 140874
 scriptlet: 30619
 html: 2176
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 81987-470, now
  ublock-annoyances: 5925-172, now
  adguard-social: 23343-929, now
  adguard-cookies: 31135-31135, now
  adguard-popup-overlays: 27875-27875, now
  adguard-mobile-app-banners: 5418-5418, now
  adguard-other-annoyances: 14910-14910, now
  adguard-widgets: 2649-2649, now
  ublock-cookies-adguard: 1612-27, now
 default:
  user-filters: 3-0, never
  ublock-filters: 39748-126, now
  ublock-badware: 10669-6, now
  ublock-privacy: 1061-4, now
  ublock-unbreak: 2560-3, now
  easylist: 85449-242, now
  easyprivacy: 53065-136, now
  plowe-0: 3545-994, now
  urlhaus-1: 28920-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1935 ms
 maxAssetCacheWait: 926 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  webtoons.com: 3
  amazon-adsystem.com: 1
  appsflyer.com: 1
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  ntv.io: 2
 extended:
  ##.ad_area
  ##.sns_list
  ##.foot_app
  ##+js(remove-attr, onselectstart|ondragstart|oncontextmenu, img[…
```
</details>

**Comment by josephcsible** [comment]
> - [x]  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

But it looks to me like this only happens because you have the additional filter list "AdGuard – Social Widgets" enabled.

**Comment by mapx-** [comment]
add

`webtoons.com#@#.sns_list`

**Comment by mapx-** [comment]
@Yuki2718
