### ISSUE TITLE
Infinityscans.net: Detection

### ISSUE THREAD

**Issue by RReaperrr** [uBlockOrigin/uAssets#25017]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://infinityscans.net
https://infinityscans.net/comic/315/worlds-strongest-troll/chapter/74984/k9o43aph1gce8l4ujlogjuemsa
```

### Description

I've made an issue with this site before, but it seems they've patched it. Infinityscans is once again able to detect Ublock Origin, and because of that, the comics on the site refuse to load. I've tried without Ublock and the site works fine. Strangely, the Ad-Block detection message doesn't pop up this time around (save for a single strange occurence.)

Another thing to note is that, despite Ublock being enabled, the site is still able to redirect me to other sites. Said sites are prevented from actually loading by Ublock, but the fact that they can even be redirected to in the first place is an issue.

### Other extensions used

Volume Master, Return Youtube Dislikes, Youtube-shorts block, Wayback Machine, Youtube Comment Translate, Rogold - Level Up Roblox, Picture in Picture - floating video player, Tampermonkey, Youtube paid promotion hider

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="779" alt="image" src="https://github.com/user-attachments/assets/e4a64f48-0ecd-4d91-a6f2-9c3004860be7">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 154998
 cosmetic: 48585
 scriptlet: 22155
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 2328-6, now
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, never
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, never
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
 default:
  user-filters: 4-0, never
  easylist: 85455-570, now
  easyprivacy: 53067-647, now
  plowe-0: 3545-0, now
  ublock-badware: 10667-6, now
  ublock-filters: 39571-287, now
  ublock-privacy: 1068-2, now
  ublock-quick-fixes: 198-0, now
  ublock-unbreak: 2508-0, now
  urlhaus-1: 29000-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1081 ms (selfie)
 maxAssetCacheWait: 160 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  infinityscans.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  pubfuture-ad.com: 1

```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/20401
