### ISSUE TITLE
witanime.cyou: breakage

### ISSUE THREAD

**Issue by alansari87** [uBlockOrigin/uAssets#25029]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://witanime.cyou/episode/nierautomata-ver1-1a-part-2-%d8%a7%d9%84%d8%ad%d9%84%d9%82%d8%a9-7/`

### Category

nuisance

### Description

download buttons can't be clicked 
and the video servers buttons as well unless i turn off ublock origin

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153632
 cosmetic: 47840
 scriptlet: 20691
 html: 1923
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39760-126, now
  ublock-badware: 10669-6, now
  ublock-privacy: 1064-4, now
  ublock-unbreak: 2570-1, now
  ublock-quick-fixes: 187-4, now
  easylist: 85438-182, now
  easyprivacy: 53067-65, now
  urlhaus-1: 29315-0, now
  plowe-0: 3556-997, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1953 ms
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  disqus.com: 3
  forcefulpacehauled.com: 1
  googletagmanager.com: 1
  viglink.com: 2
 extended:
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by mapx-** [comment]
what exactly button does not work ? upload a screenshot indicating it / them

**Comment by alansari87** [comment]
The problem is fixed I don’t know how but if everything is working correctly now
