### ISSUE TITLE
bethshouldercan.com: breakage

### ISSUE THREAD

**Issue by Zunshin** [uBlockOrigin/uAssets#25028]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bethshouldercan.com/zi8g9ymdcvlo`

### Category

breakage

### Description

Can''t play Video on Voe cause off adblock detection

### Other extensions used

Sponsorblock; 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153642
 cosmetic: 47844
 scriptlet: 20682
 html: 1923
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  ublock-filters: 39751-126, 1m Δ
  ublock-badware: 10669-6, 1m Δ
  ublock-privacy: 1061-4, 1m Δ
  ublock-unbreak: 2567-1, 1m Δ
  ublock-quick-fixes: 189-4, 1m Δ
  easylist: 85456-182, 1m Δ
  easyprivacy: 53067-66, 1m Δ
  urlhaus-1: 29315-0, now
  plowe-0: 3545-993, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1385 ms (selfie)
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  ads-twitter.com: 2
  hiredeitysibilant.com: 2
  imasdk.googleapis.com: 2
  sharethis.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/a8c9f67cbee2ef2cba499e94df9f84bd2c794eac
