### ISSUE TITLE
usatoday.com: nuisance

### ISSUE THREAD

**Issue by einstein95** [uBlockOrigin/uAssets#25022]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.usatoday.com/story/entertainment/music/2024/08/13/trump-using-copyrighted-songs/74768391007/`

### Category

nuisance

### Description

On the left and right sides of the page are invisible boxes that return you to the entertainment section. There is additionally a floating (X) that also does the same thing. I've highlighted these areas in the screenshot.

Both cases are solved with `a[aria-label="Close"]`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/785dbaf8-5aca-4859-aabb-a86f538d0ec7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153302
 cosmetic: 47828
 scriptlet: 20677
 html: 1923
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39751-126, now
  ublock-badware: 10669-6, now
  ublock-privacy: 1061-4, now
  ublock-unbreak: 2560-1, now
  ublock-quick-fixes: 170-4, now
  easylist: 85447-182, now
  easyprivacy: 53063-65, now
  urlhaus-1: 29000-0, now
  plowe-0: 3545-993, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1902 ms
 maxAssetCacheWait: 32 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 34
 network:
  usatoday.com: 3
  3lift.com: 1
  adsafeprotected.com: 1
  amazon-adsystem.com: 1
  bidswitch.net: 1
  brandmetrics.com: 1
  btloader.com: 1
  casalemedia.com: 1
  channelexco.com: 1
  confiant-integrations.net: 1
  criteo.com: 2
  criteo.net: 2
  doubleclick.net: 1
  ex.co: 2
  gannettdigital.com: 1
  gannettinnovation.com: 4
  media.net: 1
  openx.net: 1
  pubmatic.com: 1
  smaato.net: 1
  taboola.com: 4
  teads.tv: 1
  yieldmo.com: 1
 extended:
  ##.gnt_x
  ##.gnt_x__lbl
  ##.pbs__player
  ###gnt_atomsnc
  ##.gnt_tb.gnt_tbb
  ##.gnt_flp
  ##.gnt_rr_xpst
  ##.gnt_tbr.gnt_tb
  ##.gnt_rr_xst
  ##[aria-label="advertisement"]
  ##+js(abort-on-property-read, _sp_._networkListenerData)
  ##+js(set-constant, gnt.x.adm, )
```
</details>

**Comment by mapx-** [comment]
needing us ip

`usatoday.com##a[aria-label="Close"]`
