### ISSUE TITLE
[nsfw] erogen.club: breakage

### ISSUE THREAD

**Issue by tyamtyaka** [uBlockOrigin/uAssets#25026]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://erogen.club/threads/25880/`

### Category

breakage

### Description

Breaks XenForo 2.3 functionality due to a rule in the uBlock filters list - Ads.

### Other extensions used

No.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 171956
 cosmetic: 68442
 scriptlet: 23628
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39574-380, 1m Δ
  ublock-badware: 10667-26, 1m Δ
  ublock-privacy: 1068-4, 14m
  ublock-unbreak: 2508-15, 14m
  ublock-quick-fixes: 199-0, 14m
  easylist: 85456-49, 1m Δ
  easyprivacy: 53067-664, 1m Δ
  urlhaus-1: 29000-0, 14m
  plowe-0: 3545-371, 14m
  RUS-0: 40760-147, 14m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 82 ms (selfie)
 maxAssetCacheWait: 18 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  erogen.club: 1
 extended:
  ##+js(abort-on-property-read, document.dispatchEvent)
```
</details>

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry can you check this?

**Comment by dimisa-RUAdList** [comment]
At first glance, the problem does not manifest itself in any way.

@tyamtyaka 
Please describe the sequence of steps, the repetition of which leads to the problem.

**Comment by tyamtyaka** [comment]
When you click on the Login and Register buttons, forms should appear, but they don't when uBlockOrigin is enabled.

In the form for publishing a post (available after authorisation only) the editor panel is not loaded).

I added screenshots to make it clearer.
And many other similar problems.

![erogen_login-reg](https://github.com/user-attachments/assets/71f9430b-9cd0-40f8-9438-99713d9ec538)
![erogen_post-edit](https://github.com/user-attachments/assets/fa7e8bc2-3078-4140-b31d-e6e8819fde89)
![erogen_error](https://github.com/user-attachments/assets/b0621a94-4325-4ec8-af03-7fa88347e6cf)

**Comment by dimisa-RUAdList** [comment]
See: https://github.com/uBlockOrigin/uAssets/issues/6114

Need to replace: `erogen.*##+js(aopr, document.dispatchEvent)` ~> `erogen.su##+js(aopr, document.dispatchEvent)`
