### ISSUE TITLE
[nsfw] superheromaniac.com: ads

### ISSUE THREAD

**Issue by arslanashraf445** [uBlockOrigin/uAssets#25025]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://superheromaniac.com/`

### Category

ads & timers 

### Description

Timer not skipped here

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 124
filterset (summary):
 network: 154753
 cosmetic: 56323
 scriptlet: 22224
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 19-0, never
  ublock-filters: 40020-346, 13m Δ
  ublock-badware: 10661-6, 13m Δ
  ublock-privacy: 1069-2, 13m Δ
  ublock-unbreak: 2511-0, 13m Δ
  ublock-quick-fixes: 199-0, 13m Δ
  adguard-mobile: 9649-97, now
  easylist: 85456-635, 13m Δ
  easyprivacy: 53067-655, 13m Δ
  urlhaus-1: 29000-0, now
  plowe-0: 3545-0, now
filterset (user): [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3399 ms (selfie)
 maxAssetCacheWait: 487 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  superheromaniac.com: 1
  clarity.ms: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ##.BR-Footer-Ads-content
  ##.jhfdiuh0.BR-Footer-Ads
  ##.SoumyaHelp-Ads-content
  ##.jhfdiuh0.SoumyaHelp-Ads
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link? Give original URL.

**Comment by BlazeFTL** [comment]
Test Url
`https://publicearn.com/sSeLFdr`

**Comment by mapx-** [comment]
@arslanashraf445 ask for help here: https://github.com/uBlockOrigin/uAssets/discussions/17361
