### ISSUE TITLE
beinsports.com.tr: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25021]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://beinsports.com.tr/`

### Category

nuisance

### Description

Cookie notice at the right, bottom corner

### Other extensions used

Cooke AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2](https://github.com/user-attachments/assets/def98637-1b0a-4df0-af38-3d63c3796864)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 260928
 cosmetic: 227804
 scriptlet: 52924
 html: 2180
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-85, now
  adguard-generic: 84465-8744, now
  adguard-spyware-url: 1662-124, now
  adguard-spyware: 79777-22411, now
  curben-phishing: 486-3, now
  ublock-cookies-adguard: 1612-9, now
  fanboy-cookiemonster: 51709-269, now
  ublock-cookies-easylist: 1612-1612, now
  adguard-social: 23343-57, now
  fanboy-social: 16959-754, now
  adguard-popup-overlays: 27877-1111, now
  adguard-mobile-app-banners: 5422-28, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 8-0, never
  ublock-filters: 39756-126, now
  ublock-badware: 10669-81, now
  ublock-privacy: 1064-16, now
  ublock-unbreak: 2570-2, now
  ublock-quick-fixes: 189-4, 20m Δ
  easylist: 85457-23469, now
  easyprivacy: 53067-40233, now
  urlhaus-1: 29000-0, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 177 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  beinsports.com.tr: 1
  clarity.ms: 1
  doubleclick.net: 1
  gemius.pl: 1
  googleoptimize.com: 2
  googletagmanager.com: 1
  netmera-web.com: 2
  visualstudio.com: 1
```
</details>

**Comment by mapx-** [comment]
enable [AdGuard – Cookie Notices](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-cookies)
