### ISSUE TITLE
flashflashrevolution.com: breakage

### ISSUE THREAD

**Issue by lolololer1337228** [uBlockOrigin/uAssets#25037]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.flashflashrevolution.com`

### Category

breakage

### Description

Site by itself is functional, but it displays incorrectly due to failing to load the .js file needed, happens all across the site

### Other extensions used

FoxyProxy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/df412747-778e-4da3-8444-118095f5ddb8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153660
 cosmetic: 47870
 scriptlet: 20673
 html: 1931
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39785-127, now
  ublock-badware: 10779-6, now
  ublock-privacy: 1064-4, now
  ublock-unbreak: 2560-1, now
  ublock-quick-fixes: 189-4, now
  easylist: 85516-182, now
  easyprivacy: 53067-66, now
  urlhaus-1: 29165-0, now
  plowe-0: 3545-993, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1994 ms (selfie)
 maxAssetCacheWait: 675 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  flashflashrevolution.com: 1
  cloudflareinsights.com: 2
```
</details>

**Comment by huyszn** [comment]
Do you need an account to reproduce the breakage?

**Comment by stephenhawk8054** [comment]
I can't reproduce

![image](https://github.com/user-attachments/assets/c94ca93a-49d0-45b4-a05b-29d9c6917767)

Test again in a new browser profile with only uBO and its default settings.
