### ISSUE TITLE
nxbrew.com: detection

### ISSUE THREAD

**Issue by johnglen559** [uBlockOrigin/uAssets#25033]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nxbrew.com/`

### Category

detection

### Description

"Ads Blocker Detected!!!" covers entire page when using Ublock Origin.

![2024-08-25](https://github.com/user-attachments/assets/902b0c4d-d718-40a8-b4fc-3ea7c62f9d74)

### Other extensions used

Application Launcher For Drive (by Google) 3.10
Better Battlelog Fix(BBLog) 5.3.2
Google Docs Offline 1.78.1
Proton VPN: Fast & Secure 1.2.2
Return YouTube Dislike 3.0.0.16
Ruffle - Flash Emulator 0.1.0 nightly 2024-08-21
SteamDB 4.5
uBlacklist 8.9.2

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 154999
 cosmetic: 47954
 scriptlet: 22148
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-3, never
  easylist: 85516-570, 1h.25m Δ
  easyprivacy: 53067-647, 1h.25m Δ
  plowe-0: 3545-0, now
  ublock-badware: 10727-6, 1h.25m Δ
  ublock-filters: 39606-286, 1h.25m Δ
  ublock-privacy: 1071-2, 1h.25m Δ
  ublock-quick-fixes: 197-0, 1h.25m Δ
  ublock-unbreak: 2505-0, 1h.25m Δ
  urlhaus-1: 30530-0, 1h.24m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1801 ms
 maxAssetCacheWait: 338 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  nxbrew.com: 2
  cleanresound.com: 1
  googlesyndication.com: 2
  highratecpm.com: 1
  histats.com: 1
  sicilywring.com: 1
 extended:
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/9929a829a9e50fd7a5e37031047fa953dbb127c1
