### ISSUE TITLE
auto.creavite.co: ads

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25039]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://auto.creavite.co/animated-banners`

### Category

ads

### Description

there ads banner ads

### Other extensions used

fast forward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240825_193736](https://github.com/user-attachments/assets/639d7814-b448-47c2-9d36-bf51ee484433)
![Screenshot_20240825_194007](https://github.com/user-attachments/assets/e6bef38f-0c36-48d5-9066-9dc7476bf29b)
![Screenshot_20240825_193954](https://github.com/user-attachments/assets/e0065804-2ca7-4a21-95cd-9c4952c61779)
![Screenshot_20240825_193946](https://github.com/user-attachments/assets/72bd36ad-ce3d-43f4-9bda-74f1c74288a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 129
filterset (summary):
 network: 232546
 cosmetic: 192500
 scriptlet: 39299
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/furkun/Anti-IP-Grabber-Hosts/main/hosts: 1013-0, now
  adguard-spyware-url: 1662-123, now
  adguard-spyware: 79780-27037, now
  block-lan: 71-0, now
  curben-phishing: 501-0, now
  adguard-cookies: 31140-82, now
  ublock-cookies-adguard: 1693-9, now
  fanboy-cookiemonster: 51734-4038, now
  ublock-cookies-easylist: 1693-1693, now
  adguard-popup-overlays: 27877-963, now
  adguard-mobile-app-banners: 5422-1125, now
  adguard-other-annoyances: 14911-376, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40043-685, 10m Δ
  ublock-badware: 10771-10, 10m Δ
  ublock-privacy: 1072-2, 10m Δ
  ublock-unbreak: 2504-5, 10m Δ
  ublock-quick-fixes: 188-0, 10m Δ
  adguard-mobile: 9650-11, now
  easylist: 85517-925, 10m Δ
  easyprivacy: 53070-856, 10m Δ
  urlhaus-1: 29165-0, now
  plowe-0: 3545-84, now
  TUR-0: 13740-26, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4353 ms
 maxAssetCacheWait: 1717 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  clarity.ms: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  sentry.io: 2
  servedby-buysellads.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by mapx-** [comment]
add

```
auto.creavite.co##[href*="?utm_medium=ads"]
auto.creavite.co##[href*="?aff="]
```

**Comment by Raidware** [comment]
> add
> 
> ```
> auto.creavite.co##[href*="?utm_medium=ads"]
> auto.creavite.co##[href*="?aff="]
> ```

![Screenshot_20240825_213637](https://github.com/user-attachments/assets/a8a9c952-c94a-49dc-a69f-3f244da6bd9e)
![Screenshot_20240825_213547](https://github.com/user-attachments/assets/6dd3eb48-df3e-4bd2-a62d-6caf915029f9)

**Comment by Raidware** [comment]
`auto.creavite.co##.max-w-full.mx-auto.rounded-lg.h-auto.w-\[728px\]`

Can you add this for fix banner ad

https://github.com/user-attachments/assets/5302d5cc-b86e-4f60-9309-d5c3e7b56730

@stephenhawk8054

**Comment by ghost** [comment]
again, there are same ad banners. is they can be blocked @mapx- 

<details>

![Image](https://github.com/user-attachments/assets/376332f8-ef93-4213-8a3a-7a2b43165d05)
![Image](https://github.com/user-attachments/assets/f49d13d3-87a3-4cbf-bc68-691711ca31a0)

</details>

**Comment by mapx-** [comment]
```adb
auto.creavite.co##[class*="justify-"]:has([href*="&utm"])
```

**Comment by ryanbr** [comment]
For a personal list its fine,  unless these banner ads are hosted on other sites? It says discord banners, so maybe we should filter those.

**Comment by ghost** [comment]
> For a personal list its fine, unless these banner ads are hosted on other sites? It says discord banners, so maybe we should filter those.

these banner ads are 3rd party

**Comment by ryanbr** [comment]
This site is advertising banners for other sites, like discord. Helps no one if we block them, it's consider a self-promo on their own site. The moment the banners are used outside of `auto.creavite.co`, then would consider it.
