### ISSUE TITLE
[NSFW] repack-games.com: nuisance

### ISSUE THREAD

**Issue by ThePatriotsXOF** [uBlockOrigin/uAssets#25031]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://repack-games.com/`

### Category

nuisance

### Description

The site blurs some game titles, it will be unblur if you put your mouse near to the game title but its pretty annoying,
I have custom filters on but nothing changes even if all is turned off. 

### Other extensions used

no comment - mostly not really related to the website.

### Screenshot(s)

![librewolf_RkfXbqrUSr](https://github.com/user-attachments/assets/0d5d9cb7-10bc-4927-bdc5-af32a26f7a41)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 195944
 cosmetic: 140611
 scriptlet: 32115
 html: 2197
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51710-186, now
  ublock-cookies-easylist: 1615-13, now
  easylist-annoyances: 4733-43, now
  easylist-chat: 206-0, now
  easylist-newsletters: 7710-35, now
  easylist-notifications: 3481-163, now
  ublock-annoyances: 5925-81, 1h.35m Δ
  CHN-0: 25514-200, now
  RUS-0: 40814-194, now
 default:
  user-filters: 70-3, never
  ublock-filters: 39781-128, 1h.35m Δ
  ublock-badware: 10729-6, 1h.35m Δ
  ublock-privacy: 1064-4, 1h.35m Δ
  ublock-unbreak: 2564-1, 1h.35m Δ
  ublock-quick-fixes: 189-4, 1h.35m Δ
  easylist: 85516-182, 1h.35m Δ
  adguard-spyware-url: 1662-124, now
  easyprivacy: 53067-66, 1h.35m Δ
  urlhaus-1: 30530-0, now
  curben-phishing: 532-2, now
  plowe-0: 3545-993, now
  LegitimateURLShortener: 2669-165, 1h.35m
filterset (user): [array of 70 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 548 ms (selfie)
 maxAssetCacheWait: 206 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  histats.com: 1
 extended:
  ###back-top
  ##+js(remove-node-text, script, ai_adb)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-current-script, jQuery, contextmenu)
```
</details>

**Comment by stephenhawk8054** [comment]
You can use this as your custom filter:

```adb
repack-games.com##li.category-adult, li.category-3d-comics:style(filter: none !important;)
```

**Comment by ThePatriotsXOF** [comment]
> Why not use the button `18+ On/Off` at the bottom?

I haven't noticed that, my bad.
