### ISSUE TITLE
Several French streaming sites: [ads, fake buttons, popups].

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#25042]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

```
https://1jour1film.cyou
https://wvw.wookafr.org
https://wiflix-catalogue.net
https://www.streamscape.fr
https://www.voirseries.de
https://seriescultes.store
https://sadisflix.beauty
https://www.hdss.at
https://french-stream.black
https://fanstream.ink
https://empire-streamz.fr
https://empire-anime.com
https://direct-streamfr.online
https://cpasfo.dev
https://www.cineplateforme.co
```

### Category

[ads, fake buttons, popups]

### Description

Hello, this is the first time I've done this and I hope I won't get yelled at ^^
Rather than open a topic for each site, I preferred to compile the list of current French streaming sites. All of them suffer from problems with residuals, ads, fake buttons, empty frames... in short, I trust you to clean up these sites, which are really very good.

### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

https://github.com/user-attachments/assets/41666e16-ffef-427e-936e-a215b4d51fd7
https://github.com/user-attachments/assets/91824641-4e92-41fe-86d2-e46bf58805d5
https://github.com/user-attachments/assets/21bc0f83-760b-422d-9d13-d6998b6a9534

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 195381
 cosmetic: 159870
 scriptlet: 31161
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt&commit=3cdec68106fa58c9f9b5b981203442a2180e85bc: 1105-0, 1h.56m
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=userscript%2Fbpc.fr.user.js&commit=3cdec68106fa58c9f9b5b981203442a2180e85bc: 148-53, 3m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 1h.56m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51735-12078, 3m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-1615, 3m
  adguard-cookies: 31140-38, 3m
  ublock-cookies-adguard: 1655-27, 3m
  fanboy-cookiemonster: 51734-51734, 3m
  ublock-cookies-easylist: 1655-1655, 3m
  RUS-0: 40768-268, 1h.2m Δ
 default:
  user-filters: 1-0, never
  ublock-filters: 39595-141, 46m Δ
  ublock-badware: 10668-6, 46m Δ
  ublock-privacy: 1071-2, 46m Δ
  ublock-unbreak: 2497-0, 46m Δ
  ublock-quick-fixes: 188-0, 46m Δ
  easylist: 85537-669, 46m Δ
  easyprivacy: 53073-853, 46m Δ
  urlhaus-1: 29165-0, 1h.56m
  plowe-0: 3545-1, 3m
  FRA-0: 25023-379, 3m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 126 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  emmmbed.com: 1
  googletagmanager.com: 1
  nossairt.net: 2
  yduxmakjfmnerfu.com: 2
 extended:
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
```
</details>

**Comment by stephenhawk8054** [comment]
Please report to this repo: https://github.com/easylist/listefr/issues

**Comment by mapx-** [comment]
I'll add only the first 2 filters to uBO, the others are for Liste FR @smed79 

```
melaniezettofrais.online##+js(nostif, sandbox)
1jour1film.cyou###fakeplayer
```

```
wiflix-catalogue.net##.btnnew
voirseries.de##.report-pub
seriescultes.store###fakeplayer
hdss.at##a.myButton
cpasfo.dev##a.myButton
cineplateforme.co##a.myButton
```

**Comment by mapx-** [comment]
@x-R0b0T-x for the next issues report them 1 by 1, indicating exactly what's the specific issue / specific page
