### ISSUE TITLE
variety.com: breakage

### ISSUE THREAD

**Issue by AndreiVernon** [uBlockOrigin/uAssets#25040]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://variety.com/lists/alien-movies-ranked-worst-to-best/aliens-vs-predator-requiem-2007/
```

### Description

When enabling ublock origin, all of the items in the movie ranking disappear. The article content ends early at `Variety ranked the “Alien” films.`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/04193a1b-75fb-4e32-9b20-5454d61e9f6c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 153673
 cosmetic: 47952
 scriptlet: 22147
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39597-283, 3h.35m Δ
  ublock-badware: 10777-6, 3h.35m Δ
  ublock-privacy: 1071-2, 3h.35m Δ
  ublock-unbreak: 2501-0, 3h.35m Δ
  ublock-quick-fixes: 188-0, 3h.35m Δ
  easylist: 85517-570, 3h.35m Δ
  easyprivacy: 53070-647, 3h.35m Δ
  urlhaus-1: 29165-0, 3h.35m
  plowe-0: 3547-0, 6d.15h.39m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 199 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
