### ISSUE TITLE
console.statsig.com: breakage

### ISSUE THREAD

**Issue by alex-statsig** [uBlockOrigin/uAssets#25068]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://latest.console.statsig.com/metrics/metrics_catalog?view=table
https://console.statsig.com/metrics/metrics_catalog?view=table
```

### Description

This page loads a static nextjs asset from "https://console.statsig.com/_next/static/chunks/pages/%5Bcompany_id%5D/metrics/metrics_catalog-9919500d117039e3.js". The asset is named the same as the URL page, which contains "metrics/metrics" which is an EasyPrivacy blocked pattern.

Currently this file is allowlisted after a previous report (https://github.com/uBlockOrigin/uAssets/issues/13965). However, we recently rolled out a new CDN under "https://console.statsigcdn.com/" (ex. https://console.statsigcdn.com/_next/static/chunks/pages/%5Bcompany_id%5D/metrics/metrics_catalog-9919500d117039e3.js) and got reports from customers about this page not functioning again. We had to rollback the change to avoid breaking this for customers.

We're planning on moving the CDN to "cdn.console.statsig.com" to make it a subdomain, but regardless the solution applied to https://github.com/uBlockOrigin/uAssets/issues/13965 will not fix these CDN cases.

If possible, we would like "*.console.statsig.com/_next/static/chunks" to be allowlisted.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 141905
 cosmetic: 47972
 scriptlet: 22129
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 85549-471, 15m
  easyprivacy: 53055-647, 15m
  plowe-0: 3545-0, 15m
  ublock-badware: 10760-6, 16m
  ublock-filters: 39574-378, 16m
  ublock-privacy: 1072-2, 15m
  ublock-quick-fixes: 214-0, 16m
  ublock-unbreak: 2508-0, 16m
  urlhaus-1: 17386-0, 16m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1002 ms
 maxAssetCacheWait: 471 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  statsigcdn.com: 1
```
</details>

**Comment by mapx-** [comment]
easyprivacy has already

`@@||console.statsig.com/_next/$~third-party`

which will whitelist any subdomain but not for third-party pages

**Comment by alex-statsig** [comment]
> easyprivacy has already
> 
> `@@||console.statsig.com/_next/$~third-party`
> 
> which will whitelist any subdomain but not for third-party pages

Ah let me double-check if this works for "console.statsig.com" requesting an asset from "cdn.console.statsig.com" then (our initial URL was "console.statsigcdn.com" which was definitely getting blocked, but maybe our mitigation of moving to a subdomain will just fix it actually)

**Comment by alex-statsig** [comment]
Ok it is looking good with "cdn.console.statsig.com" (misinterpreted the rule and assumed it would still be blocked like our other domain); I think we won't require any changes then, thanks for the help!
