### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by aurifelix** [uBlockOrigin/uAssets#25064]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.reddit.com/`

### Category

breakage

### Description

When disabling auto-play videos in Reddit's user preferences, videos endless buffer and do not play. Enabling auto-play videos resolves the issue. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 153465
 cosmetic: 47981
 scriptlet: 22131
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39578-282, 37m Δ
  ublock-badware: 10748-6, 37m Δ
  ublock-privacy: 1072-2, 37m Δ
  ublock-unbreak: 2508-0, 37m Δ
  ublock-quick-fixes: 212-0, 37m Δ
  easylist: 85581-566, 37m Δ
  easyprivacy: 53049-647, 37m Δ
  urlhaus-1: 28940-0, 19m
  plowe-0: 3545-0, 19m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 200 ms (selfie)
 maxAssetCacheWait: 69 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  reddit.com: 6
  redditstatic.com: 1
 extended:
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by aurifelix** [comment]
Hi stephenhawk8054, apologies. It is happening on the new profile with no extensions. It's also happening on every other browser too. I think uBO can be safely ruled out
