### ISSUE TITLE
youtube.com: nuisance - button lock and video playback

### ISSUE THREAD

**Issue by chass999** [uBlockOrigin/uAssets#25061]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/`

### Category

nuisance

### Description

Opening YouTube with uBlock enabled results in a screen where no videos appear and no YouTube menu buttons work (see screenshot #1). Additionally, reducing the zoom to 30% generates video thumbnails further down the webpage (see screenshot #2), but no buttons work, and clicking on any thumbnail opens the video URL but does not play the video and the buttons do not function. The website menu also does not appear (see screenshot #3). Disabling uBlock Origin for www.youtube.com completely fixes the issue (see screenshot #4).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Screenshot 1
https://i.postimg.cc/y8bVNmhn/captura-1.png
Screenshot 2
https://i.postimg.cc/cJtdtvXW/captura-2.png
Screenshot 3
https://i.postimg.cc/kg4J91SB/captura-3.png
Screenshot 4
https://i.postimg.cc/9McN5S4k/captura-4.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153825
 cosmetic: 54750
 scriptlet: 22526
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 85587-48, now
  easyprivacy: 53049-687, now
  plowe-0: 3545-371, now
  spa-0: 4074-23, now
  spa-1: 5950-226, now
  ublock-badware: 8824-21, 16m Δ
  ublock-filters: 39574-405, now
  ublock-privacy: 1034-5, 16m Δ
  ublock-quick-fixes: 112-0, 53m Δ
  ublock-unbreak: 2374-21, 22m Δ
  urlhaus-1: 28940-0, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 766 ms (selfie)
 maxAssetCacheWait: 248 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(trusted-replace-node-text, script, (function() {window.ytp…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
