### ISSUE TITLE
app.studysmarter.de: ads

### ISSUE THREAD

**Issue by nathanoy** [uBlockOrigin/uAssets#25070]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.studysmarter.de/`

### Category

ads

### Description

There are multiple ads showing on this site. Most notably the sidebar and frequent popups.
An account is required to get access to the site (Free).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**Sidebar:**
![Sidebar](https://github.com/user-attachments/assets/0b5c0468-2669-48c8-94bd-cbd2e328ac33)

**Popup**
![Popup](https://github.com/user-attachments/assets/e9a5f21d-aab6-45f4-bc37-fd025e7a67d2)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 155701
 cosmetic: 53090
 scriptlet: 20656
 html: 1936
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 39841-128, 45m Δ
  ublock-badware: 10762-6, 45m Δ
  ublock-privacy: 1065-2, 45m Δ
  ublock-unbreak: 2526-1, 45m Δ
  ublock-quick-fixes: 205-4, 45m Δ
  easylist: 85624-577, 45m Δ
  easyprivacy: 53055-44, 45m Δ
  urlhaus-1: 28790-0, now
  plowe-0: 3545-625, now
  DEU-0: 7541-27, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 833 ms (selfie)
 maxAssetCacheWait: 584 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 49
 network:
  amplitude.com: 38
  facebook.net: 1
  googlesyndication.com: 3
  googletagmanager.com: 2
  logr-ingest.com: 1
  paypal.com: 2
  sentry.io: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

_Edit: I edited this post because i accidentally pressed `Shift + Enter` which submitted this prematurely._

**Comment by stephenhawk8054** [comment]
Is the site redirected to `https://app.vaia.com/`?

**Comment by nathanoy** [comment]
> Is the site redirected to `https://app.vaia.com/`?

This site looks very similar. But it doesn't redirect. The ads are on the domain I have reported. Did it redirect for you?

**Comment by stephenhawk8054** [comment]
Yeah, it tells me this:

![image](https://github.com/user-attachments/assets/e39d0dd8-6198-404e-bd85-322cdbb5bdcf)

---

Can you test these filters:

```adb
app.studysmarter.de##+js(trusted-replace-xhr-response, "ads_disabled":false, "ads_disabled":true, payments)
app.studysmarter.de##aside > .ng-star-inserted
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Remember to turn on `Allow custom filters requiring trust` in "My filters" pane.**

**Comment by nathanoy** [comment]
These filters work perfectly! (I'm reporting later today if the random ads during studying still show)

On a side note:
This occurred on my secondary device. On my primary device these ads don't show. And the redirect is also only shown on my primary device. To be honest I have no clue how exactly this all correlates.

Thank you very much!
