### ISSUE TITLE
uBlock Origin not working correctly at Funimation

### ISSUE THREAD

**Issue by SlippyFist** [uBlockOrigin/uAssets#2508]
### URL(s) where the issue occurs

`https://www.funimation.com/shows/blood-c/it-is-for-thy-sake/`

### Describe the issue

So it does block all of the ads at the site, without triggering the site's adblocker detection, so there's that- but when I play a video, I immediately notice the video player GUI is screwed up- buttons are not the right size, and they are shifted over so the (time played) / (time remaining) is displayed where the / has been word-wrapped down to the next line and the (time remaining) has been word-wrapped down another line under that so when you mouse-over the bottom area of the video player where the progress bar and timestamp are, it comes up way too high and looks weird.  Also the volume control button has been overlaid directly on top of the pause button.  And, more importantly, while the video still plays, the real issue that initiated all of this is that it blocks the subtitles from coming through (funimation apparently uses a separate script to handle its subtitles).  This has not happened with any other video player from any other site I've ever been to.

Also, note that if you want to test the site, you need a free account- you can do this by clicking login, clicking create account, and it will look like it's forcing you to start a free trial period.  All you have to do is enter an email address and a password, and when it prompts you to input either a Paypal or CC# for a subscription payment method, hit Cancel at the bottom and it will leave you in the free account with the email you just created.

### Screenshot(s)

[![firefox_2018-06-08_20-01-55.png](https://s22.postimg.cc/bdpkblsxd/firefox_2018-06-08_20-01-55.png)](https://postimg.cc/image/vxuea38od/)

### Versions

- Browser/version: Firefox Quantum: 61.0b11 (64-bit)/ Microsoft Edge 42.17134.1.0/ Google Chrome 67.0.3396.79 (Official Build) (64-bit)
- uBlock Origin version: Firefox- 1.16.8/ Edge- 1.15.24/ Chrome- 1.16.8

### Settings

All default.

### Notes

I originally did a google search for the issue, which took me to an old reddit thread on the ublock origin subreddit from someone having the issue with a different site; i did try the suggestions there which did not resolve the issue.  I did at one point open the logger and refresh the site and try both the dynamic and static filtering on the various elements being blocked, and nothing i tried worked.  I then created my own reddit post on the subreddit (link: `https://www.reddit.com/r/uBlockOrigin/comments/8p3nq2/blocking_subtitles_on_funimation/`) and had a lengthy exchange with someone there; same story- everything i tried has changed nothing.

For the record, I tried removing it and reinstalling the extension (which didn't do anything as i had never changed any of the default settings or made my own rules/filters). I then used both Edge and downloaded Chrome to try the site with their respective ublock origin extensions; With edge, the video would not even play, and with Chrome I had the exact same issue.  I have no idea what to try from here.

**Comment by mapx-** [comment]
Did you update ublock filters ? It was fixed 2 days go:
https://github.com/uBlockOrigin/uAssets/issues/2487

**Comment by SlippyFist** [comment]
Hey, so do you think you could confirm with me if this solution worked or not before closing my post?

I'm the person that guy in that other post was referring to, and as i told him in our reddit exchange, that solution wasn't working for me.  So this wasn't actually fixed 2 days ago- the site still isn't working in all 3 browsers
