### ISSUE TITLE
vueling.com: breakage

### ISSUE THREAD

**Issue by TiagoPT** [uBlockOrigin/uAssets#25097]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vueling.com/en`

### Category

breakage

### Description

Upon loading the page I get an Access Denied message, I am using Firefox with Enhanced Tracking Protection, EFF Private Badger along with uBlock origin but I have disabled all of them and validated that uBO being the only extension enabled the issue remains.

### Other extensions used

Firefox built-in Enhanced Tracking Protection, EFF Private Badger.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBO Error Screenshot](https://github.com/user-attachments/assets/dbfec370-5753-4ec6-8b53-311b287abab5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153964
 cosmetic: 47964
 scriptlet: 20681
 html: 1941
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  ublock-filters: 39851-126, 14m Δ
  ublock-badware: 10864-6, 14m Δ
  ublock-privacy: 1081-4, 14m Δ
  ublock-unbreak: 2528-1, 14m Δ
  ublock-quick-fixes: 199-4, 14m Δ
  easylist: 85664-180, 14m Δ
  easyprivacy: 53070-64, 14m Δ
  urlhaus-1: 29270-0, 14m
  plowe-0: 3556-997, 14m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 832 ms (selfie)
 maxAssetCacheWait: 72 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  quantummetric.com: 3
  techlab-cdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO?
