### ISSUE TITLE
jpopsingles.eu: detection

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#25098]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.jpopsingles.eu/?s=moona&search=`

### Category

detection

### Description

Adblocker is detected and the message occasionally shows up

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1728" alt="Screenshot 2024-08-28 at 2 34 02 PM" src="https://github.com/user-attachments/assets/bc7bf245-de89-4c05-ba53-57ded424523f">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 246218
 cosmetic: 220967
 scriptlet: 55935
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84835-7631, never
  adguard-mobile: 9651-181, never
  adguard-spyware-url: 1662-124, never
  adguard-spyware: 77778-26136, never
  block-lan: 71-2, never
  curben-phishing: 522-6, never
  adguard-cookies: 31353-94, never
  ublock-cookies-adguard: 1688-9, never
  fanboy-cookiemonster: 51751-4002, never
  ublock-cookies-easylist: 1688-1688, never
  adguard-popup-overlays: 27915-962, never
  adguard-mobile-app-banners: 5429-1125, never
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 39673-271, now
  ublock-badware: 10862-6, now
  ublock-privacy: 1088-2, now
  ublock-unbreak: 2467-0, now
  ublock-quick-fixes: 216-0, 1m
  easylist: 85656-568, 1m
  easyprivacy: 53070-647, 1m
  urlhaus-1: 29270-0, 1m
  plowe-0: 3545-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1202 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  jpopsingles.eu: 1
  a-ads.com: 1
  acscdn.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  h12-media.com: 2
  prplads.com: 2
  wp.com: 1
 extended:
  ##style[id$="-css"]:remove()
  ##*:style(-webkit-touch-callout: default !important; -webkit-use…
  ##+js(adjust-setInterval, downloadTimer)
  ##+js(abort-current-script, document.createElement, /l\.parentNo…
  ##+js(noeval-if, adsBlocked)
  ##+js(abort-current-script, document.createElement, break;case)
  ##+js(addEventListener-defuser, DOMContentLoaded, document.docum…
  ##+js(remove-node-text, script, adsSrc)
  ##+js(prevent-fetch, ads, length:10, {"type": "cors"})
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
  ##+js(adjust-setInterval, downloadTimer, , 0.02)
  ##+js(abort-current-script, document.oncontextmenu)
  ##+js(addEventListener-defuser, contextmenu, preventDefault)
  ##+js(abort-current-script, document.onkeydown)
  ##+js(abort-on-property-write, stopPrntScr)
  ##+js(abort-current-script, jQuery, contextmenu)
  ##+js(abort-current-script, document.addEventListener, keydown)
  ##+js(addEventListener-defuser, DOMContentLoaded, adsBlocked)
  ##+js(abort-on-stack-trace, document.createElement, adsBlocked)
  ##+js(abort-on-property-read, adsBlocked)
  ##+js(set-constant, adblock.check, noopFunc)
  ##+js(abort-on-stack-trace, DOMTokenList.prototype.contains, man…
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, atob, /popundersPerIP[\s\S]*?Date[\s…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+jpopsingles.eu

---

Continue here: https://github.com/uBlockOrigin/uAssets/issues/14388

**Comment by mapx-** [comment]
I cannot reproduce the detection => reset uBO to defaults - disable any other extension - test again

**Comment by jimmysofat6864** [comment]
> I cannot reproduce the detection => reset uBO to defaults - disable any other extension - test again

I tried factory settings and got the same issue. It takes some time to show up but it will show up eventually. I found that navigating around the site and using the search bar and other general website navigation got it to show up.

![Screenshot 2024-08-29 152503](https://github.com/user-attachments/assets/7356e6c5-8b7d-4cac-b4b1-4352559d32b4)
