### ISSUE TITLE
idnes.cz: ads

### ISSUE THREAD

**Issue by BebeMischa** [uBlockOrigin/uAssets#25096]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.idnes.cz/`

### Category

ads

### Description

Shows ads. Using zapper or picker clears everything, not just ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/4a40f506-1a0d-436c-a70f-edbaed73fd43)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 154489
 cosmetic: 49684
 scriptlet: 20699
 html: 1941
listset (total-discarded, last-updated):
 added:
  NLD-0: 2317-44, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39851-126, now
  ublock-badware: 10864-6, now
  ublock-privacy: 1081-4, now
  ublock-unbreak: 2528-1, now
  ublock-quick-fixes: 199-4, now
  easylist: 85664-180, now
  easyprivacy: 53070-64, now
  urlhaus-1: 29270-0, now
  plowe-0: 3545-993, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1354 ms
 maxAssetCacheWait: 445 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  criteo.net: 5
  gemius.pl: 1
  google.com: 1
  googletagmanager.com: 1
  pubmatic.com: 1
  seznam.cz: 9
  tpls.cz: 2
 extended:
  ##div[id^="crt-"][style]
  ##span:matches-css(background-image:/url.*//www.idnes.cz/):upwar…
  ##+js(no-setTimeout-if, /Adform|didomi|adblock|forEach/)
  ##+js(addEventListener-defuser, click, pingUrl)
  ##+js(addEventListener-defuser, mousedown, scoreUrl)
```
</details>

**Comment by addisr** [comment]
For some time now (if uBlock is detected) client gets "different" version (assets served from "random" urls, longer loading times, ...). Seems like it only does that with Czech IP. No ads and no random assets url with SK IP.

For example `https://www.idnes.cz/zpravy/zahranicni/video-trump-pensylvanie-tanec-mitink-usa-volby.A241015_133831_zahranicni_ert` - video ads and banners

**Comment by JobcenterTycoon** [comment]
Works fine for me i tried a VPN. @Yuki2718 can you reproduce?

**Comment by addisr** [comment]
Try going through the page few times, homepage, some article and it should appear (now I'm also not getting video ads, but the rest is there).

**Comment by Yuki2718** [comment]
I can't reproduce.
