### ISSUE TITLE
myanimelist.net: breakage

### ISSUE THREAD

**Issue by smileyhead** [uBlockOrigin/uAssets#25091]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://myanimelist.net/anime/55791/Oshi_no_Ko_2nd_Season
https://myanimelist.net/manga/3082/Nichijou
```

### Description

Whenever filtering is enabled on any MyAnimeList entry page, the Related Entries section is removed. This applies to both anime and manga pages.

### Other extensions used

BetterTTV
Checker Plus for Gmail
Chrome Remote Desktop
Control Panel for Twitter
Disable Keyboard Shortcuts
Fandom Enhance
Google Docs Offline
Google Translate
Hones: Automatic Coupons & Rewards
Imagus
Indie Wiki Buddy
Journey Buster
Mouse Pinch-To-Zoom
Open-as-Popup
Return YouTube Dislike
SposorBlock for YouTube
Steam URL Opener
superagent - Automatic cookie consent
Take Webpage Screenshots Entirely - Fireshot
Video Maximizer
Yeah! for Twitter

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/10cfa324-26c4-436e-813b-8bab5d086339)
_Filtering off_

![image](https://github.com/user-attachments/assets/df7382e0-1ef6-42ba-97c9-98ade729cc32)
_Filtering on_

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 154238
 cosmetic: 49811
 scriptlet: 22206
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.17h.50m
  HUN-0: 2096-1, 12m
  ublock-quick-fixes: 206-0, 12m Δ
 default:
  user-filters: 58-3, never
  easylist: 85656-472, 12m
  easyprivacy: 53069-657, 12m
  plowe-0: 3545-4, 12m
  ublock-badware: 10813-6, 12m Δ
  ublock-filters: 39673-371, 12m Δ
  ublock-privacy: 1072-2, 12m Δ
  ublock-unbreak: 2467-0, 12m Δ
  urlhaus-1: 29270-0, 12m
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 22 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 583 ms (selfie)
 maxAssetCacheWait: 137 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  myanimelist.net: 2
  btloader.com: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  pinterest.com: 1
  primis.tech: 1
  sascdn.com: 1
  smartadserver.com: 1
  taboola.com: 1
  vntsm.com: 1
 extended:
  ##.pb24 > .widget-content
  ##tr:nth-of-type(2) > .pb24
  ##.border_top
  ##[src*="/c/img/images/event/"]
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
default:
  user-filters: 58-3, never
```

Remove all your custom filters, open new tab and test again

**Comment by smileyhead** [comment]
Oh yeah, it was one of my filters. It must've been something I set up before the redesign of the Related Entries section:

```myanimelist.net##tr:nth-of-type(2) > .pb24```

Sorry for the inconvenience!
