### ISSUE TITLE
[nsfw] cambb.xxx: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#25105]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://cambb.xxx/
https://cambb.xxx/page/2
```

### Description

Anti-adblock on main page and subpages:
- it appears for me only in Firefox, but not in Chromium
- it appears sometimes / randomly (not every page load)
   - lets say it appears every few page reloads,
   (max 20 page reloads is sufficient to always reproduce for me)
- reproduced even with both regional PL lists disabled

I noticed that in Firefox when logger says the following scriptlet message, the anti-adblock never appears:
`[cambb.xxx][prevent-xhr ⁝ googlesyndication ⁝ ] Prevented with response: `
And the opposite: if the logger lacks the above message, anti-adblock will always appear.
Here is the example screenshoot: [SCREENSHOOT LOGGER](https://github.com/user-attachments/assets/394c22cb-eb34-42a7-b42e-86452409ac81)
(the bottom part anti-adblock didn't appear, the upper part anti-adblock did appear)
In Chromium the scriptlet message always appear in the logger, and anti-adblock never appears.

By the way, before I noticed anti-adblock appearance triggered by only uBO (and no other extensions installed), 
it was triggered also by [ClearURLs addon](https://addons.mozilla.org/en-US/firefox/addon/clearurls/) (updated: to fix anti-adblock in ClearURLs, it's required to go to settings and untick "Allow domain blocking (can lead to problems on sites that do not allow ad blockers)” .

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ss_08](https://github.com/user-attachments/assets/728b3345-8d97-403a-b735-0f5ce9b76284)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBO dev, default
```
</details>

**Comment by BlazeFTL** [comment]
I Have Also Noticed This Where No-fetch-if Is Not Working With FireFox But Working With Chrome Or Not Needed At All
`https://nanolinks.in/jelw1vxI`

**Comment by zenstorage** [comment]
> I Have Also Noticed This Where No-fetch-if Is Not Working With FireFox But Working With Chrome Or Not Needed At All `https://nanolinks.in/jelw1vxI`

Works fine for me with:
```adb
advicefunda.com##+js(no-fetch-if, adsbygoogle)
```

**Comment by zenstorage** [comment]
For ```cambb.xxx``` I reloaded the page more than 20 times and didn't receive any anti-adb warnings

**Comment by BlazeFTL** [comment]
> Works fine for me with:

It Also Works For Me Now...Seems To Be Random Issue With The Site Or Browser...But It Does Happen

**Comment by garry-ut99** [comment]
> For `cambb.xxx` I reloaded the page more than 20 times and didn't receive any anti-adb warnings

I've reloaded the main page 20 times in a row right now, and anti-adblock has appeared at the following reloads: `8 10,12,13,16,17,19`, means averagely: 1 time per 3 reloads.

I've also noticed in dev console, that everytime anti-adblock appears, the same error appears: [SCREENSHOOT ERROR](https://github.com/user-attachments/assets/09bd4cf0-6a69-4c63-baac-6f74942afe24) ==> [Reason: CORS request not HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp), and the opposite: if no anti-adblock appears, no error appears. The anti-adblock and the error appear at the same time, hence it's hard to say which one appears first: the error or the anti-adblock, it might be that it's the error which triggers anti-adblock, or vce-versa: it might be the anti-adblock which triggers the error. Depending on the case: the former or the latter, the error might be related or not related to the anti-adblock. In the end it might turn out to be a site's issue or to be not a site's issue, or even maybe some race condition.

**Comment by stephenhawk8054** [comment]
The CORS error means the `no-fetch-if` can't activate (usually due to race conditions, which sometimes happen to `no-fetch/xhr-if`) so the redirection takes the job of the blocked `adsbygoogle` requests and triggers the CORS error.

**Comment by garry-ut99** [comment]
Still not fixed: I've added the same filter to "My filters" as in the commit above, but the issue still occurs like before.

By the way, in the logger, sometimes/randomly appears an error related to the newly added scriptlet: [SCREENSHOOT SET](https://github.com/user-attachments/assets/118f162a-6371-4998-ab06-9868d8485ea6), it appears sometimes/randomly, regardless of whether the anti-adblock has appeared or not.

**Comment by garry-ut99** [comment]
Just: `cambb.xxx###adb` works, maybe this is funny but the anti-adblock is just a simple popup and nothing more.

**Comment by garry-ut99** [comment]
I've discovered one more site: `nudecams.xxx` of the same category with anti-adblock appearing in uBO: [SCREENSHOOT AA](https://github.com/user-attachments/assets/e9fdacf3-2dd9-457e-9ded-8882c6dca588), enabling _"AdGuard – Ads"_ fixes the anti-adblock, they used similiar filters, their commit works:
- https://github.com/AdguardTeam/AdguardFilters/issues/169962

<hr>

Another issue is video breakage by EasyList: some videos not loading on `nudecams.xxx` [SCREENSHOOT VIDEO](https://github.com/user-attachments/assets/e79e7c5e-e442-4dd1-8de2-ddbca9ec7c87), example video link:  `https://nudecams.xxx/models/cam4/Luxymin/`, due to this filter: `||pinklabel.com/live-banners` https://github.com/easylist/easylist/blob/a5017b30d745051eb940185132fac0f1735b60bc/easylist_adult/adult_thirdparty.txt#L200

By the way, before you get to the breakage caused by EasyList, don't forget that videos on `cambb.xxx` and `nudecams.xxx`, like already mentioned in my first comment: https://github.com/uBlockOrigin/uAssets/issues/25105#issue-2494762895, are additionally broken:
- by ClearURLs extension 
- and on Firefox: by Enhanced Tracking Protection

**Comment by D4niloMR** [comment]
I can't reproduce this breakage

**Comment by garry-ut99** [comment]
I can still reproduce the video breakage, on both Firefox and Chromium.
Like I already mentioned "**some** videos not loading", maybe you tried a wrong video.
Given a fact, the old video link I provided is currently "offline", here is another new link to a broken video: 
`https://nudecams.xxx/models/cam4/MildredCumby/`
For a comparison I also provide a link to a not-broken video, where EasyList filter doesn't show up in logger: 
`https://nudecams.xxx/models/stripchat/AmandaBby03/`

**Comment by D4niloMR** [comment]
Ok, seems the problem is specific to `/models/cam4/`

**Comment by zenstorage** [comment]
add an exception to the set, work for me:
```adb
nudecams.xxx#@#+js(set-constant, adbPopup, noopFunc)
```

**Comment by zenstorage** [comment]
on /cam4/ it seems to work:
```adb
@@||pinklabel.com$frame,domain=nudecams.xxx
```
