### ISSUE TITLE
urbtix.hk: privacy

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uAssets#25102]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.urbtix.hk/
```

### Description

Tracking.

1. (POST) `https://www.urbtix.hk/api/internet/log/add?[snipped]`

Request payload

```json
{
    "ua": "[navigator.userAgent]",
    "sdk_ver": "0.0.2",
    "ch": "web",
    "sc": "[viewport]",
    "appnm": "PROD",
    "fpid": "[snipped]",
    "utm": {
        "utm_source": ""
    },
    "evs": [{
            "nm": "PV",
            "tm": [unixtimestamp],
            "url": "https://www.urbtix.hk/",
            "val_lab": {
                "tabid": "[snipped]",
                "token": false,
                "expire_time": -1,
                "custom": "{}"
            },
            "ref_url": ""
        }
    ]
}
```

Response payload

```json
{
    "code": 200000,
    "msg": null,
    "data": "success",
    "paging": null,
    "tracing": null,
    "metadata": {
        "requestId": "[snipped]",
        "date": [unixtimestamp],
        "expireAt": -1,
        "expire": -1
    },
    "extraData": null,
    "success": true
}
```

2. (POST) `https://www.urbtix.hk/api/internet/view/response/log/add?[snipped]`

Request payload

```json
{
    "pathName": "www.urbtix.hk/",
    "reportType": "error",
    "data": [{
            "error": {
                "type": "www.urbtix.hk_hotEventsError",
                "url": "https://www.urbtix.hk/",
                "now": [unixtimestamp],
                "errorInfo": {
                    "serverTime": "2024-00-00 00:00:00",
                    "resultTime": "20240000000000",
                    "eventList": {}
                },
                "user": null,
                "clientId": "[snipped]"
            },
            "isNet": true,
            "message": "{\"type\":\"www.urbtix.hk_hotEventsError\",\"url\":\"https://www.urbtix.hk/\",\"now\":[unixtimestamp],\"errorInfo\":{\"serverTime\":\"2024-00-00 00:00:00\",\"resultTime\":\"20240000000000\",\"eventList\":{}},\"user\":null,\"clientId\":\"[snipped]\"}"
        }
    ],
    "pageUrl": "https://www.urbtix.hk/",
    "webPort": "internet",
    "ua": "[navigator.userAgent]"
}
```

Response payload

```json
{
    "code": 200000,
    "msg": null,
    "data": "Interface Call Success!",
    "paging": null,
    "tracing": null,
    "metadata": {
        "requestId": "[snipped]",
        "date": [unixtimestamp],
        "expireAt": -1,
        "expire": -1
    },
    "extraData": null,
    "success": true
}
```

### Other extensions used

_none_

### Configuration

<details>
<summary>Details</summary>

### uBlock Origin version

uBlock Origin v1.59.0

### Browser name and version

Firefox 115.14.0
</details>

**Comment by stephenhawk8054** [comment]
```adb
||urbtix.hk/api/internet/log/add?
```

@ryanbr
