### ISSUE TITLE
Potential badware domains

### ISSUE THREAD

**Issue by MEtICaRT** [uBlockOrigin/uAssets#25108]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
vip󠄺u󠄺rl󠄺.󠄺pro/hotlady
https://w80q7h4j6ti8ivp3jjdmtqd8.find-singles-online.com/vlm-woo-wooi/

(There are many more potential domains that could be blocked, just a few visits to the first link can reveal dozens of different URLs)
```

### Description

The first URL is being posted by fake accounts on xHamster, as seen in the screenshot I attached below.

After opening it, you're being redirected and  prompted with a few questions before being redirected again to a "legit-looking" website that asks for your email to create an account.

However, after entering fake credentials, no account is actually created, from what I understand. Instead, you're redirected to yet another website with more questions, and at the end, it asks you to create another account. This process repeats again and again, with multiple redirects. 

Sometimes, the redirect is blocked by uBO, for example, when it leads to `snapdates9.com`, but in my experience, it can redirect to a variety of other websites as well, including the second link I provided. Each browsing session seems to result in a different redirect.

Even if I'm wrong and `snapdates9.com` is the only redirect, clicking "Proceed" on uBO still leads to unexpected redirects that are not being blocked. Every single redirect seems scammy.

Another potential indication that this might be a scam domain is the fact that it exists under multiple TLDs, such as .online and .in.

Please take a look, and based on your expertise, does this seem malicious, and do you think it's worth adding to the Badware list?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="400" alt="image" src="https://github.com/user-attachments/assets/6ce78469-a01f-479e-a667-89ede6fc1de1">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by JobcenterTycoon** [comment]
Its fine enough as long the redirector are blocked.
