### ISSUE TITLE
[nsfw] hanime.tv: breakage

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25107]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hanime.tv/`

### Category

breakage

### Description

None of the image on pages show also, can't open the menu button when clicked on 3 line at left top as shown in ss. Works fine when blocker is turned off.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

When enabled 

![1000077271](https://github.com/user-attachments/assets/de6cecd1-7c85-49da-a1bf-204b18b38a17)

When disabled 

![1000077272](https://github.com/user-attachments/assets/ef43c970-a09d-4059-9cb3-2453991043c5)

![1000077273](https://github.com/user-attachments/assets/0be77ade-e7c1-44a1-aad4-981ef503b5ab)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 415123
 cosmetic: 232196
 scriptlet: 54251
 html: 2201
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 172937-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 435-1, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 402-34, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 84130-39581, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  adguard-generic: 84812-8668, now
  adguard-spyware-url: 1662-124, now
  block-lan: 71-0, now
  curben-phishing: 540-16, now
  fanboy-cookiemonster: 51759-201, now
  ublock-annoyances: 5953-143, 8m Δ
  IND-0: 13530-52, now
  [12 lists not shown]: [too many]
 default:
  ublock-filters: 40361-325, 8m Δ
  ublock-badware: 10905-1010, 8m Δ
  ublock-privacy: 1087-32, 8m Δ
  ublock-unbreak: 2531-3, 8m Δ
  ublock-quick-fixes: 212-71, 8m Δ
  adguard-mobile: 9634-758, now
  easylist: 85759-30066, 8m Δ
  easyprivacy: 53075-9161, 8m Δ
  urlhaus-1: 28720-252, now
  plowe-0: 3545-2964, 8m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 suspendUntilListsAreLoaded: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1114 ms (selfie)
 maxAssetCacheWait: 545 ms
 cacheBackend: indexedDB
 unsuspendAfter: 517 ms
popupPanel:
 blocked: 0
 extended:
  ##div:has(> a[href^="https://track.aftrk1.com/"])
  ##.subtext + div.event-container
  ##+js(set-constant, ABLK, false)
  ##+js(set-cookie, in_d0, 1)
  ##+js(set-cookie, in_d4, 1)
  ##+js(set-cookie, in_m4, 1)
```
</details>

**Comment by zenstorage** [comment]
```I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.```

You have many filterlist

**Comment by Rachitidk** [comment]
Yes, ik but that didn't affect the result, I turn everything off and used only and only ublock default settings, but the problem persist. If you want I can turn them off and submit new issue. I have again checked it while writing the msg, they doesn't affect the website.

**Comment by Rachitidk** [comment]
> `I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.`
> 
> You have many filterlist

Yes, ik but that didn't affect the result, I turn everything off and used only and only ublock default settings, but the problem persist. If you want I can turn them off and submit new issue. I have again checked it while writing the msg, they doesn't affect the website.

**Comment by zenstorage** [comment]
> Yes, ik but that didn't affect the result, I turn everything off and used only and only ublock default settings, but the problem persist. If you want I can turn them off and submit new issue. I have again checked it while writing the msg, they doesn't affect the website.

Did you send the information for troubleshooting when you still had the filters enabled? I can't reproduce it on Chrome or Firefox, mobile or desktop with the default uBO

**Comment by stephenhawk8054** [comment]
@Rachitidk Backup your configuration, reset uBO to default settings, restart the browser and test again.

**Comment by Rachitidk** [comment]
Figured 😸 it out, it's soo laughable.
It is caused by dark reader + ublock.
When you turn off any one of them, site works. Look at the recording

https://github.com/user-attachments/assets/486be772-cd3e-4e08-83f5-7b04d3997db0

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I have verified that other extensions are not causing the issue.
