### ISSUE TITLE
gtx.mtcremix.com: detection

### ISSUE THREAD

**Issue by DARKBOYJYOTI** [uBlockOrigin/uAssets#25109]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gtx.mtcremix.com/`

### Category

detection

### Description

Adblock Detected

Please disable adblock to proceed to the destination page

### Other extensions used

Nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 252975
 cosmetic: 269223
 scriptlet: 54245
 html: 2201
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84857-4140, 6h.1m
  adguard-spyware-url: 1662-124, 6h.1m
  adguard-spyware: 77780-1548, 6h.1m
  block-lan: 71-0, 6h.1m
  curben-phishing: 613-3, 6h.1m
  adguard-cookies: 31361-57, 6h.1m
  ublock-cookies-adguard: 1728-30, 6h.1m
  fanboy-cookiemonster: 51759-3985, 6h.1m
  ublock-cookies-easylist: 1728-1728, 6h.1m
  adguard-social: 23364-58, 6h.1m
  fanboy-social: 16990-754, 6h.1m
  fanboy-thirdparty_social: 68-19, 6h.1m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40361-128, 32m Δ
  ublock-badware: 10905-6, 32m Δ
  ublock-privacy: 1087-4, 32m Δ
  ublock-unbreak: 2531-1, 32m Δ
  ublock-quick-fixes: 212-71, 32m Δ
  adguard-mobile: 9646-104, 6h.3m
  easylist: 85759-2582, 32m Δ
  easyprivacy: 53075-25570, 32m Δ
  urlhaus-1: 28840-0, 6h.3m
  plowe-0: 3545-1489, 6h.3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3412 ms
 maxAssetCacheWait: 2514 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  mtcremix.com: 2
  doubleclick.net: 4
  googlesyndication.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###ast-scroll-top
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(noeval-if, /chp_?ad/)
  ##+js(abort-on-stack-trace, document.getElementsByTagName, adsBl…
```
</details>

**Comment by zenstorage** [comment]
```I did not answer truthfully to ALL the above checkboxes.```

**Comment by DARKBOYJYOTI** [comment]
Original link: https://indianshortner.in/LsAg

**Comment by zenstorage** [comment]
Seems working:
```adb
gtx.mtcremix.com##+js(no-fetch-if, adsbygoogle)
```
