### ISSUE TITLE
[Anti-Adlbock, Source Point, Ads] programme-tv.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2510]
### URL(s) where the issue occurs

`http://www.programme-tv.net/programme/sport/r390877-football-match-de-preparation-a-la-coupe-du-monde/12619922-france-etats-unis/`

### Describe the issue

1. Anti-Adblock, after a few refresh, it is no longer closable
2. The video player plays preroll ads anyway

### Screenshot(s)

Anti-adblock
![image](https://user-images.githubusercontent.com/7283682/41186901-463da28c-6b5c-11e8-8aa7-531c3d582f1f.png)

Video ads
![image](https://user-images.githubusercontent.com/7283682/41186911-718eb322-6b5c-11e8-8a61-018b7a0135dc.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.8

### Settings

English default + `FRA: EasyList Liste FR`

Since the website is French, this should be the default setup. 

### Notes

Fix anti-adblock (the usual rule works): 
`programme-tv.net##+js(abort-on-property-read.js, _sp_._networkListenerData)`

I haven't looked into the preroll ads

**Comment by okiehsch** [comment]
Can't reproduce pre-roll ads, fixed the rest.

**Comment by jspenguin2017** [comment]
I can't reproduce preroll ads anymore neither, you just fixed it.

**Comment by smed79** [comment]
@okiehsch check these sites too
```
businessinsider.fr
caminteresse.fr
capital.fr
cuisineactuelle.fr
femmeactuelle.fr
gala.fr
gentside.com
geo.fr
hbrfrance.fr
nationalgeographic.fr
neonmag.fr
ohmymag.com
prima.fr
programme.tv
serengo.net
voici.fr
vsd.fr
```

**Comment by okiehsch** [comment]
Well, it would be helpufl to narrow it down a bit, what exactly am I looking for?

**Comment by okiehsch** [comment]
I could reproduce two anti adblock messages and six adback reinsertions, fixed with https://github.com/uBlockOrigin/uAssets/commit/ba3ce088de284e966080d43becec9a45b61d4746

**Comment by smed79** [comment]
Thank you for your time.
