### ISSUE TITLE
simkl.com: breakage

### ISSUE THREAD

**Issue by deadman616** [uBlockOrigin/uAssets#25117]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://simkl.com/`

### Category

breakage

### Description

Can't login to the website the links on it are not there. When I disabled Ublock everything is OK I log-in to the website then re re-enabled Ublock it broke some links. 

### Other extensions used

No Ublock is the only one I use.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153565
 cosmetic: 47985
 scriptlet: 20692
 html: 1943
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39915-126, 28m Δ
  ublock-badware: 10916-6, 28m Δ
  ublock-privacy: 1086-4, 28m Δ
  ublock-unbreak: 2528-1, 28m Δ
  ublock-quick-fixes: 221-71, 28m Δ
  easylist: 85778-180, 28m Δ
  easyprivacy: 53075-64, 28m Δ
  urlhaus-1: 28720-0, now
  plowe-0: 3545-993, 28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16760 ms (selfie)
 maxAssetCacheWait: 893 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  cloudflareinsights.com: 2
  google.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  posthog.com: 1
  simkl.in: 9
  uservoice.com: 1
 extended:
  ##+js(abort-on-property-read, decodeURI)
  ##+js(addEventListener-defuser, load, head)
```
</details>

**Comment by deadman616** [comment]
Problem no solved.

**Comment by stephenhawk8054** [comment]
Wait about 3-4 hours and update the filter lists again. Or you can add these as custom filters in the meantime

```adb
simkl.com#@#+js(aopr, decodeURI)
*$script,3p,denyallow=b-cdn.net|disqus.com|jsdelivr.net|jwpcdn.com|fastly.net|fastlylb.net|jquery.com|hetrixtools.com|hwcdn.net|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com|twimg.com|twitter.com|x.com,domain=simkl.com,badfilter
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
