### ISSUE TITLE
tvline.com: breakage

### ISSUE THREAD

**Issue by NetMage** [uBlockOrigin/uAssets#25116]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tvline.com/lists/cancelled-tv-shows-list-fall-2024/`

### Category

breakage

### Description

Parts of the page are missing. Happens on multiple pages but not all.

### Other extensions used

TamperMonkey (no scripts apply)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153581
 cosmetic: 48087
 scriptlet: 22194
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 29-0, never
  ublock-filters: 39724-337, 1h.37m Δ
  ublock-badware: 10914-6, 1h.37m Δ
  ublock-privacy: 1093-2, 1h.37m Δ
  ublock-unbreak: 2469-0, 1h.37m Δ
  ublock-quick-fixes: 230-0, 1h.37m Δ
  easylist: 85778-569, 1h.37m Δ
  easyprivacy: 53075-647, 1h.37m Δ
  urlhaus-1: 28720-0, now
  plowe-0: 3545-0, now
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1963 ms (selfie)
 maxAssetCacheWait: 392 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  blogherads.com: 2
  connatix.com: 1
  fouanalytics.com: 1
  fwpixel.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  lightboxcdn.com: 1
  mediavoice.com: 1
  pinterest.com: 1
  pmc.com: 1
  skimresources.com: 1
  taboola.com: 1
  trackonomics.net: 1
  tru.am: 1
  typekit.net: 1
  wp.com: 1
 extended:
  ###skin-ad-left-rail-container
  ###skin-ad-right-rail-container
  ##.admz
  ##.pmc-adm-boomerang-pub-div
  ##.ad-text
  ##[class^="_aside_"]
  ##[class^="_whatToWatchWidget_"]
  ##[class^="_mostCommentedWidget_"]
  ##[class^="_footerWrapper_"]
  ##[class^="_socialMedia_"]
  ##[class^="_articleFooter_"] > [class^="_cards_"]
  ##[class^="_newsletter_"]
  ###taboola-below-article-thumbnails
  ##.widget_pmc-ads-widget
  ##+js(remove-node-text, script, '"v4ac1eiZr0"')
  ##+js(abort-on-property-write, _sp_)
  ##+js(remove-node-text, script, /adm|adb/i)
```
</details>

**Comment by PsyberWolf** [comment]
This is not fixed.  It's cutting off when they start posting images with their media..
