### ISSUE TITLE
mojmaxtv.hrvatskitelekom.hr: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25110]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mojmaxtv.hrvatskitelekom.hr/`

### Category

nuisance

### Description

Cookie notice at the top of the page

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/feaa5909-d6b7-45ef-b88e-810a7d86c250)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 262456
 cosmetic: 252404
 scriptlet: 54148
 html: 2200
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-0, now
  adguard-generic: 84751-8722, now
  adguard-spyware-url: 1662-124, now
  adguard-spyware: 77788-21586, now
  curben-phishing: 540-4, now
  adguard-cookies: 31370-3909, never
  ublock-cookies-adguard: 1688-9, now
  fanboy-cookiemonster: 51759-270, now
  ublock-cookies-easylist: 1690-1688, now
  adguard-social: 23360-57, now
  fanboy-social: 16990-755, now
  adguard-popup-overlays: 27912-1108, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 8-0, never
  ublock-filters: 39916-211, now
  ublock-badware: 10916-81, now
  ublock-privacy: 1086-16, now
  ublock-unbreak: 2528-2, now
  ublock-quick-fixes: 221-71, now
  easylist: 85778-23480, now
  easyprivacy: 53075-40216, now
  urlhaus-1: 28720-0, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 115 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  icanhazip.com: 1
  yo-digital.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
mojmaxtv.hrvatskitelekom.hr##[class*="styles__HeaderInfoBarStyled"]:has(a[href="https://www.hrvatskitelekom.hr/podrska/privatnost-podataka"])
```

cc @ryanbr @Alex-302
