### ISSUE TITLE
[nsfw] ultrasurfing.com: popups

### ISSUE THREAD

**Issue by NOBACHA** [uBlockOrigin/uAssets#25115]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ultrasurfing.com/`

### Category

popups

### Description

unwanted pop up windows

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153468
 cosmetic: 48027
 scriptlet: 22194
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-2, never
  easylist: 85630-441, now
  easyprivacy: 53075-645, now
  plowe-0: 3545-0, now
  ublock-badware: 10914-6, now
  ublock-filters: 39724-435, now
  ublock-privacy: 1093-2, now
  ublock-quick-fixes: 230-0, 15m Δ
  ublock-unbreak: 2469-31, now
  urlhaus-1: 28720-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1961 ms
 maxAssetCacheWait: 507 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-popups: true
 extended:
  ###container
  ###ad_top
  ##._ap_apex_ad
  ##.ad-skyscraper
  ###taboola-below-article-thumbnails
  ###ad-300
  ###taboola-right-rail-thumbnails
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate. https://github.com/uBlockOrigin/uAssets/issues/25072
