### ISSUE TITLE
word-grabber.com: ads

### ISSUE THREAD

**Issue by gerwyn1205** [uBlockOrigin/uAssets#25114]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.word-grabber.com/words-with-friends-cheat?ws=game&ws-r=icrgsev&ws-p=&ws-b=0&ws-o=weight`

### Category

ads

### Description

The site is now showing ads,  never had this before whilst using ublock origin.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 153560
 cosmetic: 47984
 scriptlet: 20694
 html: 1943
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39919-320, now
  ublock-badware: 10911-26, now
  ublock-privacy: 1086-7, now
  ublock-unbreak: 2528-0, now
  ublock-quick-fixes: 221-0, now
  easylist: 85778-60, now
  easyprivacy: 53075-41, now
  urlhaus-1: 28720-0, now
  plowe-0: 3545-993, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 largeMediaSize: 40
hiddenSettings: [none]
supportStats:
 allReadyAfter: 30191 ms (selfie)
 maxAssetCacheWait: 1284 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 no-large-media: true
 no-popups: true
 network:
  word-grabber.com: 1
  criteo.com: 1
  criteo.net: 1
  dn0qt3r0xannq.cloudfront.net: 2
  googletagmanager.com: 1
  html-load.com: 6
  wort-suche.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Ok i see its a site group.

```
word-grabber.com
wort-suchen.de
palabr.as
motscroises.fr
cruciverba.it
```

**Comment by JobcenterTycoon** [comment]
@piquark6046

**Comment by piquark6046** [comment]
Done.
