### ISSUE TITLE
trakt.tv: ads

### ISSUE THREAD

**Issue by Dantasstic** [uBlockOrigin/uAssets#25124]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://trakt.tv/movies/trending`

### Category

ads

### Description

Ads are visible in lower left corner

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-08-30 - 0036-10](https://github.com/user-attachments/assets/f732516d-5a42-4445-a31e-4650eb367695)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 232832
 cosmetic: 197046
 scriptlet: 52901
 html: 2204
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1h.41m
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, now
  ublock-annoyances: 5926-13, now
  adguard-generic: 84657-4157, now
  adguard-mobile: 9635-58, now
  fanboy-cookiemonster: 51877-220, now
  adguard-spyware-url: 1662-124, now
  block-lan: 71-2, now
  curben-phishing: 512-2, 1h.41m
  adguard-spyware: 77790-27034, now
  adguard-cookies: 31376-3840, now
  adguard-mobile-app-banners: 5428-14, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 132-5, never
  ublock-filters: 39940-126, now
  ublock-badware: 10922-6, now
  ublock-privacy: 1106-4, now
  ublock-unbreak: 2530-2, now
  easylist: 85783-2584, now
  easyprivacy: 53075-180, now
  plowe-0: 3545-1082, now
  urlhaus-1: 29995-0, 1h.41m
  ublock-quick-fixes: 221-87, now
filterset (user): [array of 132 redacted]
trustedset:
 added: [array of 97 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1429 ms
 maxAssetCacheWait: 823 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  trakt.tv: 5
  googletagmanager.com: 1
 extended:
  ###cc-main
  ###om1gYCfRiN-IGJj59JMAC-wrapper
  ##+js(set-constant, hucksterInit, trueFunc)
  ##+js(set-constant, artemisDisplays, [])
  ##+js(set-constant, artemisItemNames, [])
  ##+js(set-constant, artemisInit, noopFunc)
```
</details>

**Comment by RandomDork** [comment]
This fix for those ads seems to have removed the external ratings from the movie and show pages. The IMDB, TMDB, and both Rotten Tomatoes scores.

@mapx- , are you seeing this as well?

[Example movie](https://trakt.tv/movies/deadpool-wolverine-2024) and [example show](https://trakt.tv/shows/the-lord-of-the-rings-the-rings-of-power)  . I think external ratings have to be turned on, in settings, under Additional Site Ratings (Not sure if they are on by default.).

Now the area is just blank. It works fine if I turn off the Ublock filters - Ads list.

**Comment by stephenhawk8054** [comment]
@RandomDork Can you screenshot what are being hidden?

**Comment by RandomDork** [comment]
![Filters](https://github.com/user-attachments/assets/67a9c430-a995-475c-b5f7-5382e214f4ad)

![No Filters](https://github.com/user-attachments/assets/9c08f237-64ef-4d62-b8cb-d2009f16dd67)

It is the bar across the top. When the filter is active, it wipes out the ratings.

You probably have to be logged in with the setting on.

**Comment by stephenhawk8054** [comment]
@RandomDork Which country are you when accessing the site?

**Comment by RandomDork** [comment]
@stephenhawk8054 

I'm in the US.

**Comment by Dantasstic** [comment]
> This fix for those ads seems to have removed the external ratings from the movie and show pages. The IMDB, TMDB, and both Rotten Tomatoes scores.
> 
> @mapx- , are you seeing this as well?
> 
> [Example movie](https://trakt.tv/movies/deadpool-wolverine-2024) and [example show](https://trakt.tv/shows/the-lord-of-the-rings-the-rings-of-power) . I think external ratings have to be turned on, in settings, under Additional Site Ratings (Not sure if they are on by default.).
> 
> Now the area is just blank. It works fine if I turn off the Ublock filters - Ads list.

I can confirm the same issue with the fix. Accessing from Canada.

**Comment by RandomDork** [comment]
It appears to be working now that the new fix has been applied. Thank you @stephenhawk8054 . I appreciate it.
