### ISSUE TITLE
giga-streaming.com: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#25121]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://giga-streaming.com/film/alien-romulus-vf-cam`

### Category

nuisance

### Description

The site is excellent, but riddled with nuisances. I leave it to you to judge and see what you can do to make the site more pleasant. 👍🏻 

### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

![{88721EE4-4881-4875-8D7D-D390C70EA477}](https://github.com/user-attachments/assets/1b78939e-92f3-4611-9d69-b26a74ffe568)
![{9B8B7F3A-4DE5-43F1-B0A0-6B44A9D92B08}](https://github.com/user-attachments/assets/f6607156-abc6-4bdc-be4b-f1caba76950f)
Lots of popups

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 196675
 cosmetic: 160228
 scriptlet: 31375
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt&commit=3cdec68106fa58c9f9b5b981203442a2180e85bc: 1105-0, 22m
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=userscript%2Fbpc.fr.user.js&commit=3cdec68106fa58c9f9b5b981203442a2180e85bc: 148-53, 22m
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/sponsorblock.txt: 34-1, 22m
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt: 51875-12151, 22m
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-4, 22m
  adguard-cookies: 31374-1682, 22m
  ublock-cookies-adguard: 1690-9, 22m
  fanboy-cookiemonster: 51759-51759, 22m
  ublock-cookies-easylist: 1690-1690, 22m
  RUS-0: 40778-281, 22m
 default:
  user-filters: 1-0, never
  ublock-filters: 39726-122, 22m
  ublock-badware: 10920-6, 22m
  ublock-privacy: 1113-2, 22m
  ublock-unbreak: 2471-1, 22m
  ublock-quick-fixes: 230-71, 22m
  easylist: 85782-642, 22m
  easyprivacy: 53075-793, 22m
  urlhaus-1: 29995-0, 22m
  plowe-0: 3545-0, 22m
  FRA-0: 25016-376, 22m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 102 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  adsco.re: 1
  blaring-arrival.com: 1
  blurbreimbursetrombone.com: 2
  cdn4ads.com: 1
  d18t35yyry2k49.cloudfront.net: 2
  d3g5ovfngjw9bw.cloudfront.net: 1
  du0pud0sdlmzf.cloudfront.net: 2
  googletagmanager.com: 6
  tsyndicate.com: 2
 extended:
  ##+js(abort-on-property-write, DoodPop)
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(abort-on-property-read, __aaZoneid)
  ##+js(no-window-open-if)
  ##+js(remove-node-text, script, /adblock|popunder/)
  ##+js(abort-current-script, WebAssembly, _0x)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by stephenhawk8054** [comment]
What nuisances? I don't understand what to do with this site:

![image](https://github.com/user-attachments/assets/17f2d832-1a14-4145-9524-729d03fc09d3)

**Comment by stephenhawk8054** [comment]
Maybe, I can't reproduce so I don't know if the header still matches or not. Can you check those XHR requests in the devtools?

**Comment by stephenhawk8054** [comment]
I'll add XHR too

**Comment by Yuki2718** [comment]
I can't even visit the site, it returns 500 error.
