### ISSUE TITLE
chroniclelive.co.uk: breakage

### ISSUE THREAD

**Issue by Scoopage** [uBlockOrigin/uAssets#25128]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.chroniclelive.co.uk/`

### Category

breakage

### Description

wont load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-30 at 11-04-33 Chronicle Live Number one for news opinion sport   celebrity news](https://github.com/user-attachments/assets/4e9fcd64-d8cf-469f-81e8-ba19c98edcf4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.1b8
Firefox: 131
filterset (summary):
 network: 154853
 cosmetic: 48062
 scriptlet: 20726
 html: 1947
listset (total-discarded, last-updated):
 default:
  user-filters: 67-1, never
  ublock-filters: 39944-126, 53m Δ
  ublock-badware: 10922-6, 53m Δ
  ublock-privacy: 1106-4, 53m Δ
  ublock-unbreak: 2530-1, 53m Δ
  easylist: 85783-180, 53m Δ
  easyprivacy: 53075-64, 53m Δ
  plowe-0: 3545-993, now
  urlhaus-1: 29995-0, now
  ublock-quick-fixes: 221-71, 53m Δ
filterset (user): [array of 67 redacted]
trustedset:
 added: [array of 117 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 288 ms (selfie)
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 122
 network:
  adnxs.com: 2
  adsafeprotected.com: 1
  amazon-adsystem.com: 1
  amplitude.com: 1
  aswpsdkus.com: 3
  btloader.com: 1
  casalemedia.com: 1
  chartbeat.com: 1
  cootlogix.com: 26
  criteo.com: 3
  criteo.net: 1
  crwdcntrl.net: 1
  dotmetrics.net: 1
  doubleclick.net: 1
  ebxcdn.com: 2
  googlesyndication.com: 12
  googletagmanager.com: 1
  gumgum.com: 1
  indexww.com: 1
  newsroom.bi: 2
  pubmatic.com: 1
  pusher.com: 1
  richaudience.com: 24
  smartadserver.com: 22
  the-ozone-project.com: 2
  tm-awx.com: 4
  viafoura.co: 4
  webcontentassessor.com: 1
 extended:
  ##.gpt.top-slot
  ##.click-track.partner
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by Scoopage** [comment]
> Test again in a new Firefox profile with only uBO and its default settings.

Still the same, have tried with Edge and same results

**Comment by stephenhawk8054** [comment]
In the new profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by garry-ut99** [comment]
I can reproduce, on both Firefox and Chromium, to reproduce: load page and scroll down a bit (lets say one screen down), disabling EasyPrivacy fixes the issue, hard to track which filter is causing the breakage, as there is plenty of blocked requests in logger.

**Comment by garry-ut99** [comment]
This works:
`@@||feliz-web.data.tm-awx.com/smile-web.min.js$script,third-party,domain=chroniclelive.co.uk`
`@@||feliz.data.tm-awx.com/smile-web-v2/rootEvent$xhr,domain=chroniclelive.co.uk`

**Comment by garry-ut99** [comment]
The breakage definately exists, but it seems it's random, sometimes happens and sometimes not,
seems like another case of broken site's jQuery library:
- https://github.com/uBlockOrigin/uAssets/issues/17228#issuecomment-1475200298

it seems what "fixes" the breakage, apart of adding the exception filters or disabling uBO,
is slowing the site's loading speed, as the breakage doesn't occur:
- a) with dev console opened (F12)
- b) or when connecting via proxy (different country IP)
- c) or when simulated via [throttling](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/throttling/index.html), for example when slowed down to "Regular 3G"

What is interesting, is that the breakage is fixed after adding the exception filters or disabling uBO, it would indicate that the breakage is caused by EasyPrivacy filters. But on the other hand even without exception filters present, with only a) / b) / c) applied, there is no breakage despite the both requests are still blocked by EasyPrivacy.
