### ISSUE TITLE
[nsfw] redgifs.com: ads

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#25131]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.redgifs.com/gifs/non-nude?order=top28&tab=gifs`

### Category

ads

### Description

On mobile change the layout using the = button to the right. Then scroll until you see an ad.
They look very similar to regular posts. You can differentiate them by the big pink button at the bottom that replaces the tags.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 158584
 cosmetic: 56371
 scriptlet: 20777
 html: 1950
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40399-250, 16m
  ublock-badware: 10878-6, 1m Δ
  ublock-privacy: 1087-7, 1m Δ
  ublock-unbreak: 2533-32, 1m Δ
  ublock-quick-fixes: 221-71, 16m
  adguard-mobile: 9642-151, 16m
  easylist: 85784-68, 1m Δ
  easyprivacy: 53075-22, 1m Δ
  urlhaus-1: 32345-0, 16m
  plowe-0: 3547-1068, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 279 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 60
 network:
  redgifs.com: 47
  amplitude.com: 2
  bugsnag.com: 10
  googletagmanager.com: 1
```
</details>

**Comment by zenstorage** [comment]
For boost you can try:
```adb
||api.redgifs.com/v2/gifs/boost^$xhr,domain=redgifs.com
```

**Comment by zenstorage** [comment]
> There is also an ad on the right side of every post (red circle, green text says Live, opens `ptosrd.com`).

Try:
```adb
redgifs.com##[class^="_adLiveButton"]:upward(1)
```

**Comment by JobcenterTycoon** [comment]
```
||api.redgifs.com/v2/ads/slots
||go.redgifs.com^
||redgifs.com/assets/js/goCtrl
redgifs.com##[class*="defaultAd"]
redgifs.com##.SideBar-Item:has(> [class^="_adLiveButton"])
redgifs.com##.previewFeed > [id^="gif_"]:has(+ [class*="defaultAd"]):has(button[aria-label].BaseButton_isPrimary):style(visibility: hidden !important;)
```

The last filter hiding the ads inside the infinity scroll but placeholder are left. Maybe there is a better solution for this.

**Comment by JobcenterTycoon** [comment]
So does this works without any breakage?
```
||api.redgifs.com/v2/gifs/boost
||api.redgifs.com/v2/ads/slots
||go.redgifs.com^
||redgifs.com/assets/js/goCtrl
redgifs.com##[class*="defaultAd"]
redgifs.com##.SideBar-Item:has(> [class^="_adLiveButton"])
```

**Comment by stephenhawk8054** [comment]
Fixed in https://github.com/easylist/easylist/commit/6a24c1f63561110f230a65df7e29d8b310200090
