### ISSUE TITLE
thedefensepost.com: ads

### ISSUE THREAD

**Issue by BillyBobMcInbredYahoo** [uBlockOrigin/uAssets#25136]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.thedefensepost.com/
```

### Description

There's a (non-static) ad at `https://www.thedefensepost.com/` for a company called Galvion that can't be permanently blocked.

To reproduce this issue:

Go to `https://www.thedefensepost.com/`

Use the uBO element picker on the ad, which creates this filter in "My filters":
- ! 31 Aug 2024 `https://www.thedefensepost.com`
||www.thedefensepost.com/wp-content/uploads/2024/08/Defense-Post-Ad_Banner_1470x620px-2.gif$image

The ad disappears

Reload the page and the ad is back

How do I permanently block this ad?

### Other extensions used

I still don't care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
> Reload the page and the ad is back

You are creating network filter to block images, so the images are cached when normal reloading. Refresh the website while bypassing the cache (`Ctrl` + `Shift` + `R` on windows) to make it blocked.

**Comment by BillyBobMcInbredYahoo** [comment]
> ```
> thedefensepost.com##[href="https://www.galvion.com/"]
> thedefensepost.com##[href="https://www.resecurity.com/"]

Thank you, this works.

**Comment by BillyBobMcInbredYahoo** [comment]
> > Reload the page and the ad is back
> 
> You are creating network filter to block images, so the images are cached when normal reloading. Refresh the website while bypassing the cache (`Ctrl` + `Shift` + `R` on windows) to make it blocked.

Thanks, this works. I'm using Linux Mint, but Ctrl + Shift + R works the same on Mint as on Windows.

Also the following "My filters" mentioned above work:
thedefensepost.com##[href="https://www.galvion.com/"]
thedefensepost.com##[href="https://www.resecurity.com/"]
