### ISSUE TITLE
btvsport.bg: detection

### ISSUE THREAD

**Issue by tarnovoruns** [uBlockOrigin/uAssets#25137]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://btvsport.bg/drugi/zlatnijat-ruzhdi-za-btv-v-tozi-medal-ima-mnogo-trud-pot-i-krav-video.html`

### Category

detection

### Description

Playing the VIDEO on the site detects the presence of the ad-blocker. Firstly, I tried with the standard filter set and the issues is there. Then I tried to enable the annoyances anti-ad-block filter, but it still detects the ad-blocker. 

### Other extensions used

Session buddy, YouTube enhancer, Stop autoplay.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 159824
 cosmetic: 104195
 scriptlet: 30176
 html: 0
listset (total-discarded, last-updated):
 added:
  BGR-0: 1040-4, never
  ublock-annoyances: 5980-12, 3h.58m
  adguard-popup-overlays: 27856-923, 3h.58m
  adguard-mobile-app-banners: 5429-11, 3h.58m
  adguard-other-annoyances: 14935-387, 3h.58m
  adguard-widgets: 2662-23, 3h.58m
  easylist-annoyances: 4748-59, 3h.58m
  easylist-chat: 215-0, 3h.58m
  easylist-newsletters: 7739-32, 3h.58m
  easylist-notifications: 3486-1192, 3h.58m
 default:
  user-filters: 10-0, never
  easylist: 85794-643, 3h.58m Δ
  easyprivacy: 53077-753, 3h.58m Δ
  plowe-0: 3547-0, 4h.6m
  ublock-badware: 10886-6, 3h.58m Δ
  ublock-filters: 39758-653, 3h.58m Δ
  ublock-privacy: 1119-2, 4h.6m
  ublock-unbreak: 2471-1, 4h.6m
  ublock-quick-fixes: 242-0, 4h.6m
  urlhaus-1: 28060-0, 4h.6m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2508 ms
 maxAssetCacheWait: 1383 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  btvsport.bg: 4
  adform.net: 1
  btv.bg: 1
  caroda.io: 1
  ebxcdn.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  performax.cz: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###top_ad_container
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by tarnovoruns** [comment]
![image](https://github.com/user-attachments/assets/fb4b5eeb-6d69-4758-87da-15e7daf1d225)

Here how it looks when the video detects the adblocker.

**Comment by tarnovoruns** [comment]
![btv](https://github.com/user-attachments/assets/7d4e48a9-ef37-42b6-ba19-92f3eb09f2c7)
Here how it looks when uBlock is detected.

**Comment by tarnovoruns** [comment]
Do you mind if you make this work also for their sub-page btvnovinite.bg , it is part of the same btv.bg websites. I think I can make it work, but I do not want to brake the syntax.

Here is the additional faulty link: https://btvnovinite.bg/bulgaria/btv-pusna-dron-nad-letnija-saraj-na-ahmed-dogan-bi-li-mogal-da-se-evakuira.html

**Comment by stephenhawk8054** [comment]
Updated here: https://github.com/uBlockOrigin/uAssets/commit/6a78dc9b3940feb011c31356ee617f9ff736bdab

**Comment by mystiquewolf** [comment]
The site detects uBlock yet again.... 

    https://btvsport.bg/drugi/lindzi-von-bolkata-se-otplashta-video.html

Shows the same video popup blocker.
