### ISSUE TITLE
rashboakal.co.in: popups

### ISSUE THREAD

**Issue by dubbleup99** [uBlockOrigin/uAssets#25140]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rashboakal.co.in/click.php?key=9kxrucn1k4h3f7yysxjx&SUB_ID_SHORT=410c1f17ee964fa887abd87d6e302c22&PLACEMENT_ID=19724395&CAMPAIGN_ID=1108174&PUBLISHER_ID=163589&ZONE_ID=1119865`

### Category

popups, redirect

### Description

On a website and it directs me.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-08-31 110803](https://github.com/user-attachments/assets/2308b8c8-70d7-4386-905d-aef5872a28c8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 165121
 cosmetic: 211187
 scriptlet: 37085
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31429-39, 1m
  adguard-mobile-app-banners: 5429-1125, 55m
  adguard-other-annoyances: 14935-495, 55m
  adguard-popup-overlays: 27856-1696, 55m
  adguard-social: 23314-785, 1m
  adguard-widgets: 2662-46, 55m
  easylist-annoyances: 4748-103, 1h.7m
  easylist-chat: 215-0, 1m
  easylist-newsletters: 7741-32, 1h.6m
  easylist-notifications: 3488-4, 1h.7m
  fanboy-cookiemonster: 51891-4046, 1m
  fanboy-social: 16990-24, 1h.6m
  [4 lists not shown]: [too many]
 default:
  user-filters: 15-0, never
  easylist: 85822-649, 1h.7m Δ
  easyprivacy: 53094-765, 1h.7m Δ
  plowe-0: 3547-1, 1m
  ublock-badware: 10885-6, 1h.7m Δ
  ublock-filters: 39790-658, 1h.7m Δ
  ublock-privacy: 1119-2, 1h.7m Δ
  ublock-quick-fixes: 242-0, 1h.7m Δ
  ublock-unbreak: 2471-2, 1h.7m Δ
  urlhaus-1: 28670-0, 1m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 24 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 109 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
Its blocked already on my end.

Do you got redirected from a other site? Post this site instead.
