### ISSUE TITLE
toonstream.co: popups

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25152]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://toonstream.co/episode/why-does-nobody-remember-me-in-this-world-1x5/`

### Category

popups

### Description

I have reported the issue in #25148. It was closed as solve but it still persist. I don't know if there a way to reopen it.
`popups appear when clicked multiple times on 'short video player' option 3 in above case and played. Rest video player works fine. Recording was also provided in previous issues been provided.`

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 413958
 cosmetic: 232301
 scriptlet: 54319
 html: 2209
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 173995-183, 1h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 435-2, 1h.14m
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 402-34, 1h.14m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 84102-40172, 1h.14m
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, 1h.14m
  adguard-generic: 84727-8675, 1h.14m
  adguard-spyware-url: 1662-124, 1h.14m
  block-lan: 71-0, 1h.14m
  curben-phishing: 545-17, 1h.14m
  fanboy-cookiemonster: 51891-201, 1h.14m
  ublock-annoyances: 5954-143, 1h.14m
  IND-0: 13529-52, 1h.14m
  [12 lists not shown]: [too many]
 default:
  ublock-filters: 40438-128, now
  ublock-badware: 10901-1017, now
  ublock-privacy: 1114-32, now
  ublock-unbreak: 2533-3, now
  ublock-quick-fixes: 230-72, now
  adguard-mobile: 9647-758, 1h.14m
  easylist: 84962-30145, now
  easyprivacy: 53094-9504, 1h.14m
  urlhaus-1: 28275-253, 1h.14m
  plowe-0: 3547-2963, 1h.14m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 suspendUntilListsAreLoaded: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1484 ms (selfie)
 maxAssetCacheWait: 330 ms
 cacheBackend: indexedDB
 unsuspendAfter: 1069 ms
popupPanel:
 blocked: 13
 network:
  acscdn.com: 2
  adskeeper.co.uk: 2
  endowmentoverhangutmost.com: 2
  googletagmanager.com: 3
  shareusads.com: 1
  wordfence.me: 1
  zarebasdezaley.com: 2
 extended:
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##+js(set-constant, Div_popup, )
  ##+js(no-setInterval-if, devtoolsDetector)
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in your old thread. All volunteers are notified with new comments. No need to open duplicated issue.
