### ISSUE TITLE
comss.ru: ads

### ISSUE THREAD

**Issue by vhd0** [uBlockOrigin/uAssets#25153]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.comss.ru/`

### Category

ads

### Description

Ads leftover

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.1b9
Chromium: 127
filterset (summary):
 network: 75828
 cosmetic: 43421
 scriptlet: 31948
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
  urlhaus-1: null
  plowe-0: null
 added:
  http://abpvn.com/vip/admin.txt: 2107-23, 1h.37m
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.37m
  fanboy-cookiemonster: 51892-17480, now
  ublock-cookies-easylist: 1692-9, now
  fanboy-thirdparty_social: 68-1, now
  ublock-annoyances: 5981-34, now
 default:
  user-filters: 2-0, never
  ublock-filters: 39810-546, 35m Δ
  ublock-badware: 10905-11, 35m Δ
  ublock-privacy: 1119-3, 35m Δ
  ublock-unbreak: 2471-1, 35m Δ
  ublock-quick-fixes: 243-0, 35m Δ
  easyprivacy: 53094-35, 35m Δ
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 120
 autoUpdatePeriod: 7
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 574 ms (selfie)
 maxAssetCacheWait: 202 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  comss.ru: 1
  cloudflareinsights.com: 1
  getsitecontrol.com: 1
  google.com: 2
  googletagmanager.com: 1
  translate.googleapis.com: 1
  webvisor.org: 1
  yandex.ru: 6
```
</details>

**Comment by dimisa-RUAdList** [comment]
This is a russian site. You need to enable RU AdList (Regions, languages).
