### ISSUE TITLE
neevo.definedcrowd.com: nuisance

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#25162]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://neevo.definedcrowd.com/en-us/account/login/`

### Category

nuisance

### Description

Cookie notice. Can be fixed with this fiter:
neevo.definedcrowd.com##.visible.cookie-preferences-alert

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 247636
 cosmetic: 260676
 scriptlet: 54310
 html: 2208
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84712-4138, 12m
  adguard-mobile: 9647-58, 12m
  adguard-spyware-url: 1662-124, 12m
  adguard-spyware: 77809-1547, 12m
  block-lan: 71-0, 12m
  curben-phishing: 472-2, 12m
  adguard-cookies: 31430-59, 12m
  ublock-cookies-adguard: 1691-28, 12m
  fanboy-cookiemonster: 51892-3981, 12m
  ublock-cookies-easylist: 1691-1691, 12m
  adguard-social: 23314-52, 12m
  fanboy-social: 16991-755, 12m
  [12 lists not shown]: [too many]
 default:
  user-filters: 56-0, never
  ublock-filters: 39999-126, 20m Δ
  ublock-badware: 10907-6, 20m Δ
  ublock-privacy: 1112-4, 20m Δ
  ublock-unbreak: 2530-1, 20m Δ
  ublock-quick-fixes: 230-72, 20m Δ
  easylist: 85080-2585, 20m Δ
  easyprivacy: 53094-25570, 20m Δ
  urlhaus-1: 28460-0, 12m
  plowe-0: 3547-1490, 12m
filterset (user): [array of 56 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1766 ms
 maxAssetCacheWait: 658 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  intercom.io: 1
```
</details>

**Comment by D4niloMR** [comment]
https://github.com/easylist/easylist/commit/89469625959c9b195462ac924bf6141a14bda23f
