### ISSUE TITLE
play.virginmediatelevision.ie: ads

### ISSUE THREAD

**Issue by Ashurel** [uBlockOrigin/uAssets#25164]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://play.virginmediatelevision.ie/shows
```

### Description

Doesn't block ad segments when playing shows

### Other extensions used

Tamper Monkey
Ground News Checker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 152643
 cosmetic: 48121
 scriptlet: 22249
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 85080-569, 1h.5m Δ
  easyprivacy: 53094-647, 1h.5m Δ
  plowe-0: 3547-0, now
  ublock-badware: 10905-6, 1h.5m Δ
  ublock-filters: 39807-337, 1h.5m Δ
  ublock-privacy: 1118-2, 1h.5m Δ
  ublock-quick-fixes: 243-0, 1h.5m Δ
  ublock-unbreak: 2471-0, 1h.5m Δ
  urlhaus-1: 28460-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1008 ms (selfie)
 maxAssetCacheWait: 131 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 158
 network:
  bluebillywig.com: 33
  doubleclick.net: 67
  flashtalking.com: 1
  google.com: 3
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  npaw.com: 50
  privacy-mgmt.com: 1
  youtube.com: 1
 extended:
  ###pauseAd
  ##+js(set-constant, google.ima.dai, {})
  ##+js(no-xhr-if, /froloa.js)

```
</details>

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, somehow I can't use any filters to target the XML with the URL

```yml
https://699f4b4fd221407ead714c33183bba51.mediatailor.eu-west-1.amazonaws.com/v1/dash/774d979dd66704abea7c5b62cb34c6815fda0d35/virgin-vod/virginmedia/remix/virgin_four/52572531/52572531.ism/manifest.mpd?aws.sessionId=fb22fed2-09b5-4593-9a6e-baaea0d65b30
```

even with `replace`. I tried very simple filters for each case but none is success

```adb
play.virginmediatelevision.ie##+js(xml-prune, Period, , amazonaws.com/v1/dash/)
play.virginmediatelevision.ie##+js(trusted-replace-xhr-response, e, , amazonaws.com/v1/dash/)
||amazonaws.com/v1/dash/$replace=/e//gms
```

**Comment by gorhill** [comment]
The VPN I use does not offer a server for Ireland, so I can't reproduce.

What is the `Content-Type` header for that resource?

**Comment by gorhill** [comment]
Has there been many cases of using `replace=` for XML data or even other types of structured data?

**Comment by stephenhawk8054** [comment]
> Has there been many cases of using `replace=` for XML data or even other types of structured data?

Not yet as far as I know. But ability to perform non-regex pruning (`json/xml/m3u-prune`) for `replace` could be helpful.

---

There's actually another case of `xml-prune` not working: https://github.com/uBlockOrigin/uAssets/issues/9764#issuecomment-1779719435 , although in that case, uBO does log the scriptlet. I haven't tested that case with `replace` yet.

**Comment by stephenhawk8054** [comment]
@gorhill Hmm... `xml-prune` still doesn't work yet.

`replace` is working with these though

```adb
play.virginmediatelevision.ie##+js(json-prune, avails)
||amazonaws.com/v1/dash/$replace=/<Period[^\n]+\n[^<]+<BaseURL>https:\/\/vod-virginmedia-ssai.+?<\/Period>//gms
||amazonaws.com/v1/dash/$replace=/(?:mediaPresentationDuration|start)="[^"]+"//g
```

**Comment by gorhill** [comment]
For the case I could reproduce, I was able to take the breakpoint, and the code path I added which I believe is the issue was taken:

US VPN
URL: `https://pluto.tv/us/on-demand/movies/6111bbe29b91f300138dc5d9`
Filter: `pluto.tv##+js(xml-prune, Period, , .mpd)`

This breaks the player, as expected -- this was just to confirm the new code path is indeed needed -- the player was not broken before modifying the code.

**Comment by stephenhawk8054** [comment]
A temp solution is

```adb
play.virginmediatelevision.ie##+js(trusted-replace-outbound-text, JSON.stringify, /^.+$/s, {}, condition, adsParams)
```

but it's weird that I can't use any `trusted-prune-inbound/outbound-object` for `JSON.stringify`.

Both of these don't work for me

```adb
play.virginmediatelevision.ie##+js(trusted-prune-outbound-object, JSON.stringify, adsParams)
play.virginmediatelevision.ie##+js(trusted-prune-inbound-object, JSON.stringify, adsParams)
```

The JSON passed to `JSON.stringify` looks like this:

```json
{"adsParams":{"ip":"146.70.48.5,for=64.252.114.42","app_bundle":"app_bundle","app_store_url":"app_store_url","app_version":"app_version","content_id":"52572531","content_title":"A+Touch+of+Frost","platform":"firefox","gam_child_ad_unit_1":"VirginMedia_Player_VOD/VirginMedia_Player_ROS","gam_child_ad_unit_2":"Desktop","gam_description_url":"https://play.virginmediatelevision.ie/replay/52572531","device_type":"device_type","lmt":"0","gdpr":"1","gdpr_consent":"CQEbF4AQEbF4AAGABBENBFFgAAAAAEPAABAgAAAMEgBALzAYIAAA.YAAAAAAAAAAA","cmsid":"2683343","testing":"false"}}
```
