### ISSUE TITLE
yinghuajinju.com: breakage

### ISSUE THREAD

**Issue by chunmuheye** [uBlockOrigin/uAssets#25175]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://www.yinghuajinju.com/v/6185-2.html`

### Category

breakage

### Description

video wont  show,but when turn off ublock,ads come back,and video show,there is some rule block the video it just make it black no video control.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 192049
 cosmetic: 132926
 scriptlet: 42428
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84767-6657, 2m
  adguard-mobile: 9648-97, 2m
  adguard-popup-overlays: 27862-103, 11m
  THA-0: 1485-3, 1m
  VIE-1: 2074-3, 1m
 default:
  user-filters: 68-4, never
  ublock-filters: 39814-551, 18m Δ
  ublock-badware: 10905-6, 18m Δ
  ublock-privacy: 1118-2, 18m Δ
  ublock-unbreak: 2471-0, 18m Δ
  ublock-quick-fixes: 243-0, 1m
  easylist: 85113-625, 18m Δ
  easyprivacy: 53094-655, 18m Δ
  urlhaus-1: 28790-0, now
  plowe-0: 3547-0, 4m
  CHN-0: 25591-167, now
filterset (user): [array of 68 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 287 ms (selfie)
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  baidu.com: 3
  staticfile.net: 2
  stgowan.com: 3
```
</details>

**Comment by mapx-** [comment]
The domain `staticfile.net` being blocked in the site belongs to `polyfill.io` who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.
