### ISSUE TITLE
github.com: nuisance

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#25188]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://github.com/github-copilot/signup`

### Category

nuisance

### Description

Cookie notice appears. Can be fixed with this filter:
github.com###wcpConsentBannerCtrl

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 242587
 cosmetic: 260804
 scriptlet: 53870
 html: 2211
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83564-4100, now
  adguard-mobile: 9664-58, now
  adguard-spyware-url: 1665-124, now
  adguard-spyware: 78282-1544, now
  block-lan: 71-0, now
  curben-phishing: 523-4, now
  adguard-cookies: 31497-60, now
  ublock-cookies-adguard: 1693-28, now
  fanboy-cookiemonster: 51904-3987, now
  ublock-cookies-easylist: 1693-1693, now
  adguard-social: 23322-52, now
  fanboy-social: 17016-756, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 57-0, never
  ublock-filters: 40037-138, now
  ublock-badware: 10922-6, now
  ublock-privacy: 1114-4, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 203-79, now
  easylist: 85757-2124, now
  easyprivacy: 53021-25015, now
  urlhaus-1: 21870-0, now
  plowe-0: 3547-1491, now
filterset (user): [array of 57 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 723 ms (selfie)
 maxAssetCacheWait: 227 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  github.com: 3
```
</details>

**Comment by krystian3w** [comment]
Enable AdGuard Cookie notices or EasyList Cookie notices intead address in uBo Annoyances aka uBo Cookie Notices...

**Comment by Dani-1-2** [comment]
@krystian3w I was told by one member of the uBO team that I can report cookie issues here. 
https://www.reddit.com/r/uBlockOrigin/comments/1f3aniw/comment/lkds8c2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by krystian3w** [comment]
As we collect simple cosmetic and network filters here, it will be 3 big cookie list.

**Comment by B1ack3ye** [comment]
### URL address of the web page

`https://github.com/login`

### Category

nuisance

### Description

I got a cookie notice on the login page.

### Other extensions used

- Bitwarden
- DeArrow
- Return YouTube Dislike
- Sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>




![Image](https://github.com/user-attachments/assets/923fd150-4a40-4883-9ccc-412d2e59648d)



</details>


### Configuration

```yaml
version: uBOL 2025.3.2.1298
mode: complete / complete
rulesets:
 default
 badware
 block-lan
 adguard-spyware-url
 annoyances-cookies
 annoyances-overlays
 annoyances-social
 annoyances-widgets
 annoyances-others
 urlhaus-full
 openphish-domains
 deu-0
```
