### ISSUE TITLE
datacamp.com: nuisance

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#25189]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.datacamp.com/blog/best-ai-coding-assistants`

### Category

nuisance

### Description

Cookie notie appears. Can be removed with this filter:
www.datacamp.com##.dc-cookie-banner-wrapper

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 242587
 cosmetic: 260806
 scriptlet: 53870
 html: 2211
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83564-4100, 10m
  adguard-mobile: 9664-58, 10m
  adguard-spyware-url: 1665-124, 10m
  adguard-spyware: 78282-1544, 10m
  block-lan: 71-0, 10m
  curben-phishing: 523-4, 10m
  adguard-cookies: 31497-59, 10m
  ublock-cookies-adguard: 1693-28, 10m
  fanboy-cookiemonster: 51904-3987, 10m
  ublock-cookies-easylist: 1693-1693, 10m
  adguard-social: 23322-52, 10m
  fanboy-social: 17016-756, 10m
  [12 lists not shown]: [too many]
 default:
  user-filters: 59-8, never
  ublock-filters: 40037-138, 10m
  ublock-badware: 10922-6, 10m
  ublock-privacy: 1114-4, 10m
  ublock-unbreak: 2530-1, 10m
  ublock-quick-fixes: 203-79, 10m
  easylist: 85757-2124, 10m
  easyprivacy: 53021-25015, 10m
  urlhaus-1: 21870-0, 10m
  plowe-0: 3547-1491, 10m
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 723 ms (selfie)
 maxAssetCacheWait: 227 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  datacamp.com: 1
  onesignal.com: 1
  profitwell.com: 1
  requestmetrics.com: 1
  sentry.io: 6
 extended:
  ##.dc-cookie-banner-wrapper
  ##.dc-ps-banner-wrapper
  ##a[href^="https://www.facebook.com/dialog/share?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
```
</details>

**Comment by krystian3w** [comment]
Since you don't see the damage on the site, see if the problem is reported to EasyList: https://github.com/easylist/easylist/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+datacamp.com

**Comment by Dani-1-2** [comment]
> Since you don't see the damage on the site
What do you mean?

**Comment by Dani-1-2** [comment]
> Since you don't see the damage on the site

What do you mean?

**Comment by krystian3w** [comment]
No obligation to repair with `replace` or `trusted-` scriptlet.

If we start blowing on each page with a unique replace or trusted scriptlet it will also become a mega-long list.

**Comment by Dani-1-2** [comment]
@krystian3w Well there is no need to use a scriptlet. Usually when I report a similar issue a commit is made to the easylist repo (See https://github.com/uBlockOrigin/uAssets/issues/25162 for example)

**Comment by stephenhawk8054** [comment]
For simple filters, please report to https://github.com/easylist/easylist/issues or https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by stephenhawk8054** [comment]
cc @ryanbr @Alex-302

**Comment by Alex-302** [comment]
Fixed.

**Comment by Dani-1-2** [comment]
> For simple filters, please report to https://github.com/easylist/easylist/issues or https://github.com/AdguardTeam/AdguardFilters/issues

So I should not report similar issues here? @stephenhawk8054

**Comment by stephenhawk8054** [comment]
@Dani-1-2 Report to the above repos first. If the issues are closed but the solutions don't work for you, report to here.
