### ISSUE TITLE
megane.com.pl: detection

### ISSUE THREAD

**Issue by menelki** [uBlockOrigin/uAssets#25185]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

```yml
https://megane.com.pl
```

### Category

detection

### Description

Each time I open this website, it  notify that I use adblocker and not allow me to enter.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/54e88f5d-43e3-45ef-965c-36211f0d5b9b)
![obraz_2024-09-03_142332629](https://github.com/user-attachments/assets/f9cd0230-a83a-4783-ade4-2b3657374c12)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 154152
 cosmetic: 56368
 scriptlet: 22440
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  POL-0: 8759-11, 26m
  POL-2: 1280-12, now
  easylist: 85419-583, now
  easyprivacy: 53020-628, now
  plowe-0: 3547-16, now
  ublock-badware: 10915-6, now
  ublock-filters: 39822-396, now
  ublock-privacy: 1120-2, now
  ublock-quick-fixes: 214-0, now
  ublock-unbreak: 2471-20, now
  urlhaus-1: 28220-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 28 redacted]
switchRuleset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1226 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  doubleclick.net: 3
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 6
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@MajkiIT Sorry, can you check this?

---

@menelki Please also report to https://github.com/MajkiIT/polish-ads-filter/issues if possible.
