### ISSUE TITLE
cafemom.com IL / g00

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#2519]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://thestir.cafemom.com/baby/204647/baby_chokes_breast_milk_hospital

### Describe the issue

g00 crap is firing, cafemom.com needs to be added to uBO Extra.

### Screenshot(s)

Can provide if needed.

### Versions

- Browser/version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)
- uBlock Origin version: 1.16.9rc0

### Settings

- Stock filters / Settings on test profile wih only uBO dev build & uBO Extra 2.71 installed.

### Notes

Not much else to add...

**Comment by smed79** [comment]
@okiehsch Please, check the list you find [\_**here**\_](https://forums.lanik.us/viewtopic.php?f=62&t=37604) for possible missed IL sites.
- https://pastebin.com/raw/WLKUjXQ9

**Comment by okiehsch** [comment]
`streetchopperweb.com` uses IL. I can't reproduce with any other mentioned site.
