### ISSUE TITLE
wiflix.al: [unknown]

### ISSUE THREAD

**Issue by grafuss** [uBlockOrigin/uAssets#25198]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wiflix.al/318463-dans-la-peau-de-blanche-houellebecq`

### Category

UNKNOWN

### Description

hello this site uses too many fack buttons (POP2WATCH) can you block these buttons?

### Other extensions used

NO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 109
filterset (summary):
 network: 146661
 cosmetic: 48114
 scriptlet: 22230
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39801-336, 10m
  ublock-badware: 10920-6, 10m
  ublock-privacy: 1118-2, 10m
  ublock-unbreak: 2471-0, 10m
  ublock-quick-fixes: 216-0, 10m
  easylist: 85757-572, 10m
  easyprivacy: 53020-647, 10m
  urlhaus-1: 21870-0, 10m
  plowe-0: 3547-0, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2229 ms
 maxAssetCacheWait: 225 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  pop2watch.com: 2
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by mapx-** [comment]
@grafuss report here: https://github.com/easylist/listefr/issues

**Comment by stephenhawk8054** [comment]
@x-R0b0T-x Report to here: https://github.com/easylist/listefr/issues
