### ISSUE TITLE
sc2casts.com

### ISSUE THREAD

**Issue by rjkpa** [uBlockOrigin/uAssets#252]
### URL(s) where the issue occurs

http://sc2casts.com/

### Describe the issue

Anti Adblock overlay blocks access.

### Screenshot(s)

https://i.gyazo.com/1f76e288b5c2f3c48340863fe6e51f8e.png

### Versions

- Browser/version: [here] Chrome 55
- uBlock Origin version: [here] 1.10.4

**Comment by gorhill** [comment]
Does this work:

    sc2casts.com##script:inject(abort-on-property-read.js, scriptfailed)

**Comment by SMed79** [comment]
Try 
`sc2casts.com##SCRIPT + DIV[id][style] DIV[class]:last-child`
or
`@@||pagead2.googlesyndication.com^$script,domain=sc2casts.com`

https://forums.lanik.us/viewtopic.php?f=62&t=33174

**Comment by rjkpa** [comment]
@gorhill Perfect! I tried aborting with others, but never tried that one.

**Comment by gorhill** [comment]
> or
> `@@||pagead2.googlesyndication.com^$script,domain=sc2casts.com`

This won't work with uBO, I disagree with such solutions which require to allow connections to a 3rd-party ad servers when a solution not requiring this exists, and thus I created a filter a while ago with the `important` option in _uBlock filters_ to ensure the exception filter above which is in EasyList is ignored.

**Comment by rjkpa** [comment]
> or
@@||pagead2.googlesyndication.com^$script,domain=sc2casts.com

No thanks. If you're going to go that route, you might as well uninstall your adblocker and put it aside. Opening 3rd party connections like these defeats the very purpose of a content blocker like uBO.

**Comment by SMed79** [comment]
> No thanks...

Just tring to help & i'm not forcing you !!

**Comment by rjkpa** [comment]
> Just tring to help

That's no help mate. That's a disaster waiting to happen.

**Comment by rjkpa** [comment]
variable changed to `scriptfailed2`

filter - `sc2casts.com##script:inject(abort-on-property-read.js, scriptfailed)`

**Comment by uBlock-user** [comment]
Patched again. Might I add, usage of variable based scriptlets is of no use, the webmaster keeps a check on this issue and foils it as soon any change is made in the filters. Blocking inline-script would be a long lasting solution rather than playing `whack-a-mole` with the stalker admin. 

`sc2casts.com$inline-script`
