### ISSUE TITLE
techtnet.com: detection

### ISSUE THREAD

**Issue by Ungic** [uBlockOrigin/uAssets#25206]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://techtnet.com/reviews/laptops/samsung-notebook-9-2022-review-51`

### Category

detection

### Description

When i click download in this website `https://linkneverdie.net/game/dredge-b-8033`, techtnet is apear and detect the ublock. but when i reload techtnet page, the capcha is disapear

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150985
 cosmetic: 127428
 scriptlet: 32546
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 51904-233, 3m
  ublock-cookies-easylist: 1698-9, 3m
  fanboy-social: 17034-20, 3m
  easylist-annoyances: 4753-19, 3m
  easylist-chat: 215-0, 3m
  easylist-newsletters: 7759-26, 3m
  easylist-notifications: 3489-84, 3m
  ublock-annoyances: 5985-29, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 39861-373, 3m
  ublock-badware: 10913-6, 3m Δ
  ublock-privacy: 1120-2, 3m
  ublock-unbreak: 2471-0, 3m Δ
  ublock-quick-fixes: 219-0, 3m
  easylist: 85786-617, 3m
  easyprivacy: 53022-753, 3m
  urlhaus-1: 21430-0, 3m
  plowe-0: 3547-0, 3m
  VIE-1: 2082-4, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2248 ms
 maxAssetCacheWait: 888 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  bovidsacate.com: 1
  dmca.com: 1
  dooloust.net: 1
  doubleclick.net: 1
  facebook.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  linkneverdie.top: 1
 extended:
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://plus.google.com/share?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="whatsapp://send?text="]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.td-scroll-up
  ##.td-social-icon-wrap
  ##.td-icon-facebook
  ##.td-icon-twitter
  ##.td-icon-youtube
  ##.td-icon-instagram
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ###ads-right
  ###ads-left
  ##.td-post-sharing-top
  ##.td-post-sharing
  ##.td-social-sharing-button
  ##.td-post-sharing-bottom
  ##.td-post-sharing-style1
  ##.td_block_social_counter
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
> When i click download in this website

where is the download button ? screenshot ?
