### ISSUE TITLE
[nsfw] simpcity.su: breakage

### ISSUE THREAD

**Issue by Dark-Thoughts** [uBlockOrigin/uAssets#25203]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://simpcity.su/`

### Category

breakage

### Description

With the standard "uBlock filters – Ads" filter enabled the image zoom function breaks, so nothing happens when clicking on an image. Tested this with everything else disabled but this filter and with everything but this filter enabled.

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 231829
 cosmetic: 257938
 scriptlet: 54412
 html: 2211
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1091-2, now
  adguard-generic: 83538-726, 2m
  adguard-spyware-url: 1665-124, 2m
  adguard-spyware: 78286-1480, 2m
  block-lan: 71-0, 2m
  curben-phishing: 515-6, 2m
  adguard-social: 23324-41, now
  adguard-cookies: 31526-58, now
  adguard-popup-overlays: 27890-893, 3m
  adguard-mobile-app-banners: 5436-26, 3m
  adguard-other-annoyances: 14946-176, 3m
  adguard-widgets: 2662-16, 3m
  [11 lists not shown]: [too many]
 default:
  user-filters: 118-13, never
  ublock-filters: 40050-4086, never
  ublock-badware: 10915-6, 1m
  ublock-privacy: 1114-2, 1m
  ublock-unbreak: 2530-0, 1m
  ublock-quick-fixes: 231-0, 1m
  easylist: 85786-1974, 2m
  easyprivacy: 53020-24986, 2m
  urlhaus-1: 21430-0, 2m
  plowe-0: 3547-1091, 2m
filterset (user): [array of 119 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 839 ms (selfie)
 maxAssetCacheWait: 284 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  adglare.net: 2
  bunkr-cache.se: 2
 extended:
  ##.u-scrollButtons
  ##.p-navEl > a[target="_blank"]
  ##+js(addEventListener-defuser, click, popMagic)
  ##+js(set-cookie, zone-cap-papi-hates-blocks, 1)
  ##+js(addEventListener-defuser, , open)
```
</details>

**Comment by Dark-Thoughts** [comment]
Had to look around a bit since there seem to be some inconsistencies. I'm unsure about the different methods used, but a couple examples which both seem to be directly uploaded / embedded and not third party hosted (I'll try to stick to some random IG threads but viewers discretion still applies):

1. https://simpcity.su/threads/abru_shaddixx-xmiss_sweetnessx.25025/post-91034
Main example like the one I encountered, seems to be actually hosted at https://jpg5.su/ but still provides some file info on the enlarged image but not on hover like the attachments.
With or without an account, and with the filter enabled, it just does not do anything when clicking on the image.
With or without an account, but with the filter disabled, it correctly enlarges the image.

2. https://simpcity.su/threads/miafitz.13150/post-24257
With an account and without the filter it opens sort of a zoomed gallery view, also has some file info on hover and requires an account.
With an account and with the filter it opens the direct linked picture in a new tab.

3. https://simpcity.su/threads/abru_shaddixx-xmiss_sweetnessx.25025/post-618852
Just for some reference, this is not an issue but since it is the same hoster as 1. But I guess here it is hotlinked instead of possibly embedded as image via formatting? Pulls the image still into the post but directly links to the hoster and opens it consequently in a new tab on that page.

**Comment by stephenhawk8054** [comment]
@Dark-Thoughts Can you test these filters?

```adb
simpcity.su#@#+js(aeld, , open)
simpcity.su##+js(aeld, , shouldShow)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Dark-Thoughts** [comment]
That seems to have done the trick.
