### ISSUE TITLE
nicematin.com :‌ breakage

### ISSUE THREAD

**Issue by WhiskasChaton** [uBlockOrigin/uAssets#25205]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.nicematin.com
```

### Description

(random ?) ad block detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 252961
 cosmetic: 159463
 scriptlet: 47611
 html: 2211
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84746-4139, 2d.4h.44m
  adguard-mobile: 9647-58, 2d.4h.45m
  adguard-spyware-url: 1662-124, 2d.4h.45m
  adguard-spyware: 77810-1547, 2d.4h.45m
  block-lan: 70-0, 25d.23h.57m
  curben-phishing: 515-6, 3h.47m
  adguard-popup-overlays: 27861-241, 2d.4h.45m
  adguard-mobile-app-banners: 5427-25, 2d.4h.45m
  adguard-other-annoyances: 14938-295, 2d.4h.45m
  adguard-widgets: 2662-15, 2d.4h.45m
  easylist-annoyances: 4749-324, 1d.22h.41m
  easylist-chat: 215-18, 2d.4h.44m
  [5 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 40050-141, 47m Δ
  ublock-badware: 10915-6, 47m Δ
  ublock-privacy: 1114-2, 47m Δ
  ublock-unbreak: 2530-0, 47m Δ
  ublock-quick-fixes: 204-79, 47m Δ
  easylist: 85786-2590, 47m Δ
  easyprivacy: 53022-25564, 47m Δ
  urlhaus-1: 21430-0, 3h.47m
  plowe-0: 3545-1488, 9d.4h.42m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings:
 autoUpdateDelayAfterLaunch: 0
supportStats:
 allReadyAfter: 1166 ms (selfie)
 maxAssetCacheWait: 214 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
enable the regional list AdGuard Français
