### ISSUE TITLE
False positive - simulation domains on Phish Insight 

### ISSUE THREAD

**Issue by jcctc** [uBlockOrigin/uAssets#25211]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
http://www.webfun.website
http://www.eservicebits.com
http://www.onlineservicetec.com
http://www.e-serviceparts.info
http://www.solutionfun.info
http://www.onlineservicetech.website
http://www.forupsite.com
```

### Description

My name is James Chen from Phish Insight, a security awareness product provided by Trend Micro. https://phishinsight.trendmicro.com/ 
If you check [who.is](http://who.is/) you will see that the domain is registered by Trend Micro. You can also see information in the HTML source code indicating this is a phishing simulation page. 

We see our simulated Phishing Webpages blocked by Microsoft from time to time and this can have a big impact on our customers when trying to train their employees. Can you please unblock the domain listed above?
I would also like to request that our domains are added to a Microsoft Allowed List to prevent this issue happening in the future. Thanks.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Can you give exact links where they are blocked by uBO?

Currently when I access your links above, only `solutionfun.info` is being blocked.
