### ISSUE TITLE
Block piano.io

### ISSUE THREAD

**Issue by otakuu** [uBlockOrigin/uAssets#25212]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.nzz.ch/
https://www.nzz.ch/meinung/den-zahlen-im-abstimmungsbuechlein-ist-nicht-mehr-zu-trauen-doch-es-gibt-auswege-aus-der-misere-ld.1845727
```

### Description

Piano.io is just an annoying popup for paywalls.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="692" alt="image" src="https://github.com/user-attachments/assets/df479ce5-60e3-4547-8a79-e7d31814bf16">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 146848
 cosmetic: 48140
 scriptlet: 22253
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 85798-49, 1h.56m Δ
  easyprivacy: 53026-21, 1h.56m Δ
  plowe-0: 3545-993, 11d.1h.4m
  ublock-badware: 10977-26, 1h.56m Δ
  ublock-filters: 39863-374, 1h.56m Δ
  ublock-privacy: 1122-5, 1h.56m Δ
  ublock-quick-fixes: 216-81, 1h.56m Δ
  ublock-unbreak: 2471-32, 1h.56m Δ
  urlhaus-1: 21950-0, 19h.3m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 410 ms (selfie)
 maxAssetCacheWait: 21 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets#uassets

> uAssets will not address the following:
> - Paywalls
> - Porn Farms

**Comment by stephenhawk8054** [comment]
Blocking it will break the paywalls, for example: https://www.ruhrnachrichten.de/dortmund/dortmund-nordstadt-polizei-kontrolle-kiosk-gefaelschte-potenzmittel-unter-der-ladentheke-w932248-2001359229/

**Comment by stephenhawk8054** [comment]
Go to some articles, the paywalls will appear

![image](https://github.com/user-attachments/assets/064950c1-9fc6-4463-9790-79c53cd395b5)

**Comment by otakuu** [comment]
Where would you report this `piano.io` to help people to get rid of such paywalls?

**Comment by otakuu** [comment]
> Go to some articles, the paywalls will appear
> 
> ![image](https://private-user-images.githubusercontent.com/66517106/364761565-064950c1-9fc6-4463-9790-79c53cd395b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzcwMTUsIm5iZiI6MTcyNTUzNjcxNSwicGF0aCI6Ii82NjUxNzEwNi8zNjQ3NjE1NjUtMDY0OTUwYzEtOWZjNi00NDYzLTk3OTAtNzljNTNjZDM5NWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMTJkNTQ3NDIzZjdkZGRhMmVkMWMwN2JkNjk2OTNhZjZkZDk4Y2Q3Zjk0NGQ2NGJkMjYzNDI0OTIzYzRhOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0S0XE7OSaKET3Z9GUX64PB3wjt5rH4Xe-Z2Rem_Ays)

Willi Wurst FTW
