### ISSUE TITLE
y2mate.nu: ads

### ISSUE THREAD

**Issue by TheZipCreator** [uBlockOrigin/uAssets#25217]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://y2mate.nu/Pio1/`

### Category

ads

### Description

After converting a video to mp3 on this site, an advertisement appears.

### Other extensions used

DarkReader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura desde 2024-09-05 13-44-37](https://github.com/user-attachments/assets/dc22e802-7386-4eb2-bccf-06a8760b6f89)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 150531
 cosmetic: 48064
 scriptlet: 20741
 html: 1957
listset (total-discarded, last-updated):
 removed:
  spa-0: null
  spa-1: null
 default:
  user-filters: 1-0, never
  ublock-filters: 40086-138, 35m Δ
  ublock-badware: 10988-6, 35m Δ
  ublock-privacy: 1116-4, 35m Δ
  ublock-unbreak: 2530-1, 35m Δ
  ublock-quick-fixes: 90-4, 35m Δ
  easylist: 85807-184, 35m Δ
  adguard-spyware-url: 1682-126, now
  easyprivacy: 53028-63, 35m Δ
  urlhaus-1: 21100-0, now
  curben-phishing: 487-3, now
  plowe-0: 3547-994, now
  LegitimateURLShortener: 2671-165, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3949 ms (selfie)
 maxAssetCacheWait: 768 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  tobaltoyon.com: 1
 extended:
  ##+js(abort-on-property-write, afStorage)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||mnuu.nu/y2mate/$subdocument
y2mate.nu###i
```

@ryanbr

**Comment by ghost** [comment]
Most likely some affiliated domain: `https://freechoice.co.za/convert/` (because it says Y2Mate on the page and has even the favicon, I don't want to risk opening another issue that would be closed as duplicate)

If you add a link there is a small "download" button which is actually an ad.
https://github.com/user-attachments/assets/ce9ecd1f-662a-4d5f-8b0e-99f6a77c3e25
https://github.com/user-attachments/assets/99a95871-a240-4448-baad-ff1850bdb1e9

**Comment by stephenhawk8054** [comment]
If it's a different site (that has not been reported yet), you can report at a new issue thread. We don't assume users to know which website is affiliated to some other websites.
