### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#25223]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/search?q=emoji+kitchen&oq=emoji+kitchen&gs_lcrp=EgZjaHJvbWUyDAgAEEUYORixAxiABDIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABNIBCDI2NzRqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8`

### Category

breakage

### Description

emoji kitchen doesnt work when ubo activate

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/c9dfc210-de4d-4f26-a722-10d47822bf57)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 160821
 cosmetic: 178513
 scriptlet: 35226
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 8964-0, 1h.12m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 210-1, 1h.12m
  adguard-cookies: 31562-39, now
  ublock-cookies-adguard: 1699-28, now
  fanboy-cookiemonster: 51911-4038, now
  ublock-cookies-easylist: 1699-1699, now
  fanboy-social: 17017-4, now
  adguard-popup-overlays: 27884-445, now
  easylist-annoyances: 4753-24, now
  easylist-notifications: 3491-84, now
  ublock-annoyances: 5985-27, 1h.12m Δ
  IDN-0: 10085-453, 1h.12m
 default:
  user-filters: 18-0, never
  ublock-filters: 39895-471, 1h.12m Δ
  ublock-badware: 10986-7, 1h.12m Δ
  ublock-privacy: 1122-2, 1h.12m Δ
  ublock-unbreak: 2471-2, 1h.12m Δ
  ublock-quick-fixes: 103-0, 1h.12m Δ
  easylist: 85832-640, 1h.12m Δ
  easyprivacy: 53028-757, 1h.12m Δ
  urlhaus-1: 21175-0, 1h.12m
  plowe-0: 3547-1, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3227 ms (selfie)
 maxAssetCacheWait: 259 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  google.com: 24
  doubleclick.net: 2
  googleadservices.com: 1
  youtube.com: 1
 extended:
  ###before-appbar + #lb[style="visibility: visible;"]
  ###taw > div > [data-ved]
  ##html.TaoyYc:style(overflow: auto !important;)
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by Bug-Cache** [comment]
```
www.google.com###before-appbar + #lb[style="visibility: visible;"]
www.google.com##html.TaoyYc:style(overflow: auto !important;)
```

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
