### ISSUE TITLE
aliprice.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#25228]
![image](https://github.com/user-attachments/assets/dc03dc1c-e594-4a4c-a617-5224a18625a9)
![image](https://github.com/user-attachments/assets/0d3a18aa-dd15-428f-90ae-07a679bbc119)

Complete mode

https://www.aliprice.com/

**Comment by krystian3w** [comment]
I would advise to watch if global slicing will be added by:

`###share-modal` without list of domains with unlocked scroll and disabled fog.
