### ISSUE TITLE
roblox.github.io: breakage

### ISSUE THREAD

**Issue by break-core** [uBlockOrigin/uAssets#25221]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://roblox.github.io/
https://roblox.github.io/lua-style-guide
```

### Description

roblox.github.io is an official GitHub Pages domain used for projects created by Roblox. Most pages on here are for documentation related to official, public Roblox libraries.

Recently after visiting a page on the site (https://roblox.github.io/lua-style-guide), it had told me the page was blocked due to a filter, which was displayed as this:
```
||roblox.$document,to=~roblox.com|roblox.*
```

This filter appears to try and block badware that is related to Roblox, but it has accidentally flagged `roblox.github.io`. This may impact some users of uBlock Origin who use `roblox.github.io`. Disabling uBlock on the website is the only way to fix it. CSS will break on the site if I go to the site with uBlock enabled and I click the Proceed button on the warning screen.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/aa14a386-6640-4ffb-bdc3-76b61695ba08)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 132
filterset (summary):
 network: 145999
 cosmetic: 48060
 scriptlet: 20730
 html: 1957
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40086-138, now Δ
  ublock-badware: 10988-26, 9m
  ublock-privacy: 1116-7, now Δ
  ublock-unbreak: 2530-1, now Δ
  ublock-quick-fixes: 90-4, now Δ
  easylist: 85807-162, now Δ
  easyprivacy: 53028-62, now Δ
  urlhaus-1: 21100-0, 9m
  plowe-0: 3547-994, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 255 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Hmm... I didn't know `github.io` is registered as a suffix: https://publicsuffix.org/list/public_suffix_list.dat
