### ISSUE TITLE
worldmak.com: detection

### ISSUE THREAD

**Issue by Givanilton** [uBlockOrigin/uAssets#25226]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://worldmak.com/`

### Category

detection

### Description

Ublock detect

### Other extensions used

Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 130
filterset (summary):
 network: 149142
 cosmetic: 62221
 scriptlet: 26829
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6012-14, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 40343-460, 10m Δ
  ublock-badware: 10975-7, 10m Δ
  ublock-privacy: 1123-2, 10m Δ
  ublock-unbreak: 2474-6, 10m Δ
  ublock-quick-fixes: 103-0, 10m Δ
  adguard-mobile: 9618-11, now
  easylist: 85832-575, 10m Δ
  easyprivacy: 53029-685, 10m Δ
  urlhaus-1: 21175-0, now
  plowe-0: 3542-83, now
  spa-1: 5979-15, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2713 ms (selfie)
 maxAssetCacheWait: 265 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link? Give original URL.

**Comment by Givanilton** [comment]
> Is it from a shortener link? Give original URL.

https://worldmak.com/?c1d952d8

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

For future shortener sites, please comment in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361 . Don't open new issues for these sites.
