### ISSUE TITLE
liblib.art: breakage

### ISSUE THREAD

**Issue by hao0427** [uBlockOrigin/uAssets#25235]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.liblib.art/`

### Category

breakage

### Description

The webpage is severely lagging! Filter accumulated over hundreds of thousands... Closing and reopening the plugin will re accumulate the count, temporary solution.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.1rc11
Firefox: 130
filterset (summary):
 network: 160079
 cosmetic: 58858
 scriptlet: 21014
 html: 1958
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 40083-138, 1h.28m Δ
  ublock-badware: 10995-6, 1h.28m Δ
  ublock-privacy: 1116-4, 1h.28m Δ
  ublock-unbreak: 2530-1, 1h.28m Δ
  ublock-quick-fixes: 77-5, 1h.28m Δ
  easylist: 85837-184, 1h.28m Δ
  easyprivacy: 53030-63, 1h.28m Δ
  urlhaus-1: 20820-0, now
  plowe-0: 3542-993, now
  CHN-0: 25531-106, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 132 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 39
 network:
  aliyuncs.com: 2
  baidu.com: 36
  googletagmanager.com: 1
 extended:
  ##.mantine-7ujnna.BaseLayout_navbar__4Ueq5.mantine-Navbar-root
  ##.mb-4.relative
```
</details>

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > ▤ ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Open new tab and reproduce the issue
3. Switch to the logger window that was opened in step 1, [click on search bar, choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output)
4. Copy the logger via 📋 [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here
