### ISSUE TITLE
engineering-designer.com: ads

### ISSUE THREAD

**Issue by npuumalainen** [uBlockOrigin/uAssets#25230]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://engineering-designer.com/the-create-the-trophy-competition-is-now-open/?awt_a=22e4A&awt_l=O1hQMn&awt_m=hdSiLQZ73jM1a4A`

### Category

ads

### Description

Banner ads remain in half the sections labeled "advertisement" on the webpage, as well as at the top of the page

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 146671
 cosmetic: 48047
 scriptlet: 20729
 html: 1958
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40079-138, now
  ublock-badware: 10995-6, now
  ublock-privacy: 1116-4, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 77-5, now
  easylist: 85837-184, now
  easyprivacy: 53030-63, now
  urlhaus-1: 21745-0, now
  plowe-0: 3542-993, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 666 ms
 maxAssetCacheWait: 246 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  engineering-designer.com: 2
  aweber.com: 4
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed in https://github.com/easylist/easylist/commit/840647cef87021a85c8083a9692b40df378850b1
