### ISSUE TITLE
skool.com: nuisance

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25236]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.skool.com/data-alchemy`

### Category

nuisance

### Description

Signup popup appear at a while.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 408338
 cosmetic: 232498
 scriptlet: 53875
 html: 2213
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 174744-0, 32m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 435-1, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 402-38, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 84259-40359, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  adguard-generic: 83443-8414, now
  adguard-spyware-url: 1687-126, now
  block-lan: 71-0, now
  curben-phishing: 541-17, now
  fanboy-cookiemonster: 51911-201, now
  ublock-annoyances: 5957-143, now
  IND-0: 13529-52, now
  [11 lists not shown]: [too many]
 default:
  ublock-filters: 40496-333, now
  ublock-badware: 10989-1012, now
  ublock-privacy: 1117-32, 33m Δ
  ublock-unbreak: 2533-3, 33m Δ
  ublock-quick-fixes: 77-4, 33m Δ
  adguard-mobile: 9621-760, now
  easylist: 85837-30385, now
  easyprivacy: 53030-9543, 33m Δ
  urlhaus-1: 20820-242, now
  plowe-0: 3542-2962, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9789 ms
 maxAssetCacheWait: 5262 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  sentry.io: 4
  stripe.com: 20
```
</details>

**Comment by mapx-** [comment]
you should ask for help here: https://github.com/DandelionSprout/adfilt/issues
