### ISSUE TITLE
sigtrib.com: ads

### ISSUE THREAD

**Issue by brad-s-prog** [uBlockOrigin/uAssets#25237]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sigtrib.com/what-did-long-beachs-federal-and-state-representatives-do-in-august/`

### Category

ads

### Description

ads not blocked on this website only

### Other extensions used

bypass paywalls clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/276ce6b6-65f1-40b3-a8d1-cfface2c681d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 145794
 cosmetic: 48338
 scriptlet: 20730
 html: 1958
listset (total-discarded, last-updated):
 default:
  user-filters: 352-12, never
  ublock-filters: 40079-138, now
  ublock-badware: 10995-6, now
  ublock-privacy: 1116-4, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 77-5, now
  easylist: 85837-203, now
  easyprivacy: 53030-44, now
  urlhaus-1: 20820-0, 40m
  plowe-0: 3542-993, now
filterset (user): [array of 352 redacted]
trustedset:
 added: [array of 27 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2303 ms (selfie)
 maxAssetCacheWait: 1454 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  github.com: 7
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how the ads look like?

**Comment by brad-s-prog** [comment]
Hi Stephen,

Thanks for you help.

https://sigtrib.com/full-issue-september-6-2024/
[https://sigtrib.com/wp-content/uploads/2024/09/FINAL-FRONT-COVER-e1725580757255-1024x832.jpg]<https://sigtrib.com/full-issue-september-6-2024/>
Full Issue: September 6, 2024 - Signal Tribune<https://sigtrib.com/full-issue-september-6-2024/>
https://sigtrib.com/wp-content/uploads/2024/09/FINAL-ST46_36_September-6-8-page.pdf
sigtrib.com

[cid:9b8e12b7-6748-4a60-b73c-db1d1ff08af7]
[cid:31ec3469-0e1d-41f7-bf31-9cc3b7327b43]

________________________________

**Comment by brad-s-prog** [comment]
Screenshots of ads were posted above 9/6/24 and sent by email 9/7/24.

**Comment by brad-s-prog** [comment]
The ad screenshots were posted 9/6/24, emailed 9/7/24, and shown below.

[cid:a9937a97-2895-442a-af0a-38d13a354900]

[cid:e6a2c76f-446a-486f-b8d4-1f8255c687ba]
________________________________

**Comment by stephenhawk8054** [comment]
Phase reply and upload screenshots directly on github. Don't reply or send via email. Images cannot be sent via email.

**Comment by mapx-** [comment]
@brad-s-prog 

add

`sigtrib.com##.size-large.wp-block-image`

report the issue at [easylist repository](https://github.com/easylist/easylist/issues)
