### ISSUE TITLE
finya.de: breakage

### ISSUE THREAD

**Issue by xf650** [uBlockOrigin/uAssets#25241]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.finya.de/MyFinya/`

### Category

breakage

### Description

some links are not avaliable

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 153886
 cosmetic: 53221
 scriptlet: 20732
 html: 1958
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40082-138, 29m Δ
  ublock-badware: 10995-6, 29m Δ
  ublock-privacy: 1116-4, 29m Δ
  ublock-unbreak: 2530-1, 29m Δ
  easylist: 85874-183, 29m Δ
  easyprivacy: 53031-63, 29m Δ
  urlhaus-1: 26590-0, now
  plowe-0: 3542-993, now
  DEU-0: 7547-37, now
  ublock-quick-fixes: 79-6, 1h.30m
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3262 ms (selfie)
 maxAssetCacheWait: 225 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  finya.de: 2
  amazon-adsystem.com: 1
  ayads.co: 2
  brwsrfrm.com: 2
  doubleclick.net: 1
  hirsung.de: 1
 extended:
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to sign in to reproduce the issue?

**Comment by mapx-** [comment]
@xf650 I guess we need an account. 
Are you willing to give us the credentials of your account? (I'll provide an email address in case you agree)
