### ISSUE TITLE
ftuapps.io: detection

### ISSUE THREAD

**Issue by FishFeng** [uBlockOrigin/uAssets#25249]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ftuapps.io/`

### Category

detection

### Description

![螢幕擷取畫面 2024-09-08 091027](https://github.com/user-attachments/assets/cade1b4a-866e-4a0e-8088-76497b977d33)

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 165102
 cosmetic: 58991
 scriptlet: 22545
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  CHN-0: 25540-36, now
  easylist: 85871-505, now
  easyprivacy: 53032-641, now
  plowe-0: 3542-2, now
  ublock-badware: 10962-6, now
  ublock-filters: 39916-397, now
  ublock-privacy: 1126-2, now
  ublock-quick-fixes: 95-0, 28m Δ
  ublock-unbreak: 2471-20, now
  urlhaus-1: 25845-0, 28m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 440 ms (selfie)
 maxAssetCacheWait: 89 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  biaxalstiles.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  onesignal.com: 1
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by alanliongar** [comment]
Hello, the problem started again: If you visit the website its detecting the ublock origin... Can you guys solve it? @stephenhawk8054

**Comment by ShadowSpawnFromBeyondTheStarsGF** [comment]
@FishFeng @alanliongar please STOP visiting FTUApps as they were caught distributing malware: https://www.reddit.com/r/Piracy/comments/120xk62/psa_ftuapps_removed_from_megathread_for/
https://www.reddit.com/r/haitenjp_is_scam_site/comments/1g5ho5i/ftuapps_included_malware_in_their_topaz_video_ai/
I propose that we add every FTUApps domain (ftuapps.dev, ftuapps.io, etc.) to the block list.

**Comment by alanliongar** [comment]
Thank you for the advice my friend, I wasnt aware of it. Really appreciate that you alerted us.
