### ISSUE TITLE
sportowefakty.wp.pl: breakage

### ISSUE THREAD

**Issue by janekiwan** [uBlockOrigin/uAssets#25243]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
sportowefakty.wp.pl
sportowefakty.wp.pl/zuzel
sportowefakty.wp.pl/pilka-nozna
```

### Description

Main webpage of sportowefakty.wp.pl is working, but when you choose any of subpage it is greyed out.
<img width="1058" alt="sportowefakty" src="https://github.com/user-attachments/assets/6228b546-0092-4c62-950a-11ed0aac419f">

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 148073
 cosmetic: 56418
 scriptlet: 22471
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  POL-0: 8759-26, 17h.29m
  POL-2: 1280-14, 293d.12h.29m
  easylist: 85875-484, 2h.14m Δ
  easyprivacy: 53032-647, 2h.14m Δ
  plowe-0: 3547-0, 5d.5h.26m
  ublock-badware: 10893-6, 2h.14m Δ
  ublock-filters: 39897-422, 2h.14m Δ
  ublock-privacy: 1127-2, 2h.14m Δ
  ublock-quick-fixes: 92-0, 2h.14m
  ublock-unbreak: 2471-0, 2h.14m Δ
  urlhaus-1: 21745-0, 17h.29m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 539 ms (selfie)
 maxAssetCacheWait: 146 ms
 cacheBackend: indexedDB
```
</details>

**Comment by JobcenterTycoon** [comment]
Caused by `pl: Oficjalne polskie filtry przeciwko alertom o Adblocku` last update `19 November 2023` (can be verified by disabling uBO base list -> same issue)
