### ISSUE TITLE
steam.design: ads

### ISSUE THREAD

**Issue by 404unknownCoder** [uBlockOrigin/uAssets#25244]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://steam.design/`

### Category

ads

### Description

On the side there's an advertisement

### Other extensions used

keeppassxc
dark reader
sponsorblock
fontanello
unhooked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0fbe49c1-12ed-4e9e-91a5-0e758cedbcc3)
![image](https://github.com/user-attachments/assets/f92e747d-a012-4c5d-92c9-efb02c5ac141)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 131
filterset (summary):
 network: 201532
 cosmetic: 245564
 scriptlet: 37208
 html: 2233
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31604-49, now
  ublock-cookies-adguard: 1699-28, now
  fanboy-cookiemonster: 51911-3986, now
  ublock-cookies-easylist: 1699-1699, now
  adguard-social: 23324-47, now
  fanboy-social: 17023-754, now
  fanboy-thirdparty_social: 68-19, now
  adguard-popup-overlays: 27902-986, now
  adguard-mobile-app-banners: 5445-27, now
  adguard-other-annoyances: 14946-422, now
  adguard-widgets: 2654-16, now
  easylist-annoyances: 4760-305, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40087-138, now
  ublock-badware: 10964-6, now
  ublock-privacy: 1121-4, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 79-5, now
  easylist: 85871-186, now
  easyprivacy: 53032-62, now
  urlhaus-1: 26590-0, now
  plowe-0: 3542-994, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 79 ms (selfie)
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
steam.design##a.profile_video[href^="https://duobot.com/"]
```

@ryanbr
