### ISSUE TITLE
alza.cz: breakage

### ISSUE THREAD

**Issue by Antraider** [uBlockOrigin/uAssets#25242]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.alza.cz/EN/media/hry-site-porno-d7075474.htm`

### Category

breakage

### Description

not showing page correctly(without images and some parts not working)

### Other extensions used

Alitools Shopping Assistant (checked without it)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/86c81bcc-e734-491b-8d55-e986f7f35514)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 170170
 cosmetic: 68662
 scriptlet: 23747
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39897-280, 1m
  ublock-badware: 10993-6, 1m
  ublock-privacy: 1127-2, 1m
  ublock-unbreak: 2471-0, 1m
  ublock-quick-fixes: 92-0, 1m
  easylist: 85874-593, 1m
  easyprivacy: 53030-647, 1m
  urlhaus-1: 26590-0, 1m
  plowe-0: 3542-0, 1m
  RUS-0: 40775-125, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1189 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  1603811301.rsc.cdn77.org: 9
  clarity.ms: 1
  cloudflareinsights.com: 1
  googleoptimize.com: 1
  googletagmanager.com: 1
  speedcurve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||cdn77.org/*.js$script,3p` in "RU AdList"

cc @dimisa-RUAdList Sorry, can you check this? It's a pretty broad filter as far as I see.

**Comment by dimisa-RUAdList** [comment]
I added this blocking some time ago when I noticed that a script from this domain was embedding frames of disposable ad servers (see comment): https://github.com/easylist/ruadlist/commit/d943e49b4a2379e6d9da48084f08a87b4f87cf81

But since it causes breakages, I will look for other ways to solve this problem. Removed: https://github.com/easylist/ruadlist/commit/62c548086d22fc29c0f96e7f981ade90ed7ea5ec
