### ISSUE TITLE
ebay.com: breakage

### ISSUE THREAD

**Issue by lightronics** [uBlockOrigin/uAssets#25247]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ebay.com/itm/174326188116`

### Category

breakage

### Description

"Add to Watchlist" does not work.
.
THIS IS THE PROBLEMATIC ENTRY:
Filter||www.ebay.$removeparam=_trksid
.
Filter list	uBlock filters – Privacy
Context	www.ebay.com
Partyness	(1) ebay.com ⇒ ebay.com
Typ	exhr

### Other extensions used

NoScript

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/02ece782-cb95-465e-9dc6-6e2ede6dbfb2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151497
 cosmetic: 48278
 scriptlet: 20740
 html: 1957
listset (total-discarded, last-updated):
 default:
  user-filters: 188-3, never
  ublock-filters: 40106-138, 1h.42m Δ
  ublock-badware: 10964-6, 1h.42m Δ
  ublock-privacy: 1121-4, 1h.42m Δ
  ublock-unbreak: 2530-1, 1h.42m Δ
  easylist: 85871-185, 1h.42m Δ
  easyprivacy: 53032-62, 1h.42m Δ
  plowe-0: 3542-994, 2m
  urlhaus-1: 26590-0, 2m
  ublock-quick-fixes: 79-6, 1h.42m Δ
filterset (user): [array of 189 redacted]
trustedset:
 added: [array of 243 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 204 ms (selfie)
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  ebay.com: 11
  ebay-us.com: 1
  ebayrtm.com: 1
  ebaystatic.com: 2
 extended:
  ##.ifh-content
  ##.gh-eb-li-a.ghn-b.gh-control
  ##.ghnp
```
</details>

**Comment by stephenhawk8054** [comment]
cc @Alex-302 @iam-py-test

**Comment by iam-py-test** [comment]
Thank you for notifying me @stephenhawk8054. Thank you @lightronics for reporting this.
I have disabled the problematic filter in https://github.com/DandelionSprout/adfilt/commit/175cc1f7cf801cc665be764e512087af9ddb9e58.
