### ISSUE TITLE
phimbet.biz: ads

### ISSUE THREAD

**Issue by levankhoa280420** [uBlockOrigin/uAssets#25248]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://phimbet.biz/`

### Category

ads

### Description

https://phimbet.biz/

### Other extensions used

https://phimbet.biz/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151989
 cosmetic: 49490
 scriptlet: 22483
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39917-286, 3m
  ublock-badware: 10962-6, 3m
  ublock-privacy: 1122-2, 3m
  ublock-unbreak: 2471-0, 3m
  ublock-quick-fixes: 90-0, 3m
  easylist: 85842-595, 3m
  easyprivacy: 53031-649, 3m
  urlhaus-1: 26590-0, 3m
  plowe-0: 3542-0, 3m
  VIE-1: 2085-0, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3403 ms
 maxAssetCacheWait: 27 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  facebook.com: 1
  googletagmanager.com: 1
 extended:
  ##.ads-top
  ##.ads-list
  ###mobileCatfish
  ##+js(trusted-replace-xhr-response, '/\{"brs_c[^\n]+?"SponsoredD…
  ##+js(trusted-replace-xhr-response, '/\{"cnt_lbl_brs"[^\n]+?"Spo…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
  ##+js(json-prune-xhr-response, data.viewer.instream_video_ads da…
```
</details>

**Comment by stephenhawk8054** [comment]
@hoang-rio Sorry, can you check this?

**Comment by stephenhawk8054** [comment]
@levankhoa280420 For future issues with Vietnamese sites, please report to https://github.com/abpvn/abpvn/issues
