### ISSUE TITLE
kdi-ppi.com: nuisance

### ISSUE THREAD

**Issue by BurtHarris** [uBlockOrigin/uAssets#25245]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kdi-ppi.com/article/rj45-connector-pinout-diagram/`

### Category

popups

### Description

Diagrams selector (or something) from article pop up repeatedly.

 

### Other extensions used

Grammarly: AI Writing and Grammar Checker App
Kami for Microsoft Edge™
Microsoft Power Automate
Privacy Badger
Wayback Machine
uBlock Origin
Chrome Remote Desktop
Google Docs Offline

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/94132000-7c5d-465b-b339-983b3202bf9b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151503
 cosmetic: 48181
 scriptlet: 22264
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39917-277, 1h.17m Δ
  ublock-badware: 10962-6, 1h.17m Δ
  ublock-privacy: 1127-2, 1h.17m Δ
  ublock-unbreak: 2471-0, 1h.17m Δ
  ublock-quick-fixes: 92-0, 1h.17m Δ
  easylist: 85871-572, 1h.17m Δ
  easyprivacy: 53032-647, 1h.17m Δ
  urlhaus-1: 26590-0, now
  plowe-0: 3542-0, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 574 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||kdi-ppi.com/modal.
```

@ryanbr

**Comment by stephenhawk8054** [comment]
Fixed in `EasyList – Other Annoyances` list
