### ISSUE TITLE
dictionary.com: nuisance

### ISSUE THREAD

**Issue by Moeen007** [uBlockOrigin/uAssets#25252]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dictionary.com/`

### Category

nuisance

### Description

If you scroll through the page, a sticky mini video player gets stuck to a bottom corner causing hindrance & nuisance.

### Other extensions used

2 other extensions: IDM Integration Module, Enhancer for Youtube.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150800
 cosmetic: 48115
 scriptlet: 20740
 html: 1958
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 40111-138, 24m Δ
  ublock-badware: 11008-6, 24m Δ
  ublock-privacy: 1120-4, 24m Δ
  ublock-unbreak: 2530-1, 24m Δ
  ublock-quick-fixes: 79-5, 24m Δ
  easylist: 85893-557, 24m Δ
  easyprivacy: 53032-684, 24m Δ
  urlhaus-1: 25845-0, 24m
  plowe-0: 3542-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 30548 ms
 maxAssetCacheWait: 1779 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 191
 network:
  dictionary.com: 14
  1rx.io: 2
  adobedtm.com: 4
  adsrvr.org: 2
  agkn.com: 2
  amazon-adsystem.com: 4
  anyclip.com: 126
  btloader.com: 1
  carambo.la: 3
  demdex.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  icanhazip.com: 2
  imasdk.googleapis.com: 16
  openx.net: 2
  proper.io: 1
  rubiconproject.com: 2
  sonobi.com: 2
  springserve.com: 2
  yieldmo.com: 2
 extended:
  ##.SZjJlj7dd7R6mDTODwIT
  ##[class] > p:has-text(Advertisement)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
enable [AdGuard – Other Annoyances](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-other-annoyances)

or 

[EasyList – Other Annoyances](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=easylist-annoyances)
