### ISSUE TITLE
filmotip.com: detection

### ISSUE THREAD

**Issue by vanjafuto** [uBlockOrigin/uAssets#25255]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://filmotip.com/`

### Category

detection

### Description

A lot of sites started detecting uBlocker as an adblocker tool, with that lots of movies and series are also blocked from watching. (in my state its legal to watch them online)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/4071b750-e63a-4445-9880-e91ff013f266)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150826
 cosmetic: 48194
 scriptlet: 22273
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 39935-275, 22m Δ
  ublock-badware: 11013-6, 22m Δ
  ublock-privacy: 1126-2, 22m Δ
  ublock-unbreak: 2471-0, 22m Δ
  ublock-quick-fixes: 94-0, 22m Δ
  easylist: 85888-572, 22m Δ
  easyprivacy: 53032-647, 22m Δ
  urlhaus-1: 25845-0, now
  plowe-0: 3542-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 264 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It returns 404 for me

<details>

![image](https://github.com/user-attachments/assets/244a28db-f83f-4cd4-b42e-0c9ecc86c49a)

</details>

**Comment by vanjafuto** [comment]
The same problem appears even after trying both ways
