### ISSUE TITLE
stitichsports.com: detection

### ISSUE THREAD

**Issue by tailscale7** [uBlockOrigin/uAssets#25251]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://stitichsports.com/
```

### Description

Adblocker detected

### Other extensions used

none

### Screenshot(s)

![Capture](https://github.com/user-attachments/assets/46ac61c1-3158-465c-b836-80d2f8215904)

### Configuration

uBlock Origin: 1.59.0
Chromium: 109
filterset (summary):
 network: 150832
 cosmetic: 48351
 scriptlet: 22269
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 173-1, never
  ublock-filters: 39922-275, 3h.27m Δ
  ublock-badware: 11006-6, 3h.27m Δ
  ublock-privacy: 1126-5, 3h.27m Δ
  ublock-unbreak: 2471-0, 3h.27m Δ
  ublock-quick-fixes: 94-0, 3h.27m Δ
  easylist: 85893-202, 3h.27m Δ
  easyprivacy: 53032-21, 3h.27m Δ
  urlhaus-1: 25845-0, 1h.27m
  plowe-0: 3545-993, 11d.14h.23m
filterset (user): [array of 173 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 20359 ms (selfie)
 maxAssetCacheWait: 3296 ms
 cacheBackend: indexedDB

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/df61de4b53c8d6cf6091c79e0fe8629dbcad14e2
