### ISSUE TITLE
darko.audio: ads

### ISSUE THREAD

**Issue by magor34** [uBlockOrigin/uAssets#25259]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://darko.audio/`

### Category

ads

### Description

Ads on top, on sides, inbetween content and beneth the content on any given page. Ublock Origin tools does remove the ads but some of them come back after a refresh.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 166476
 cosmetic: 113127
 scriptlet: 26833
 html: 2038
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52014-187, now
  ublock-cookies-easylist: 1706-13, now
  fanboy-social: 17030-10, now
  dpollock-0: 11695-344, now
 default:
  user-filters: 14-4, never
  ublock-filters: 40125-138, now
  ublock-badware: 11054-6, now
  ublock-privacy: 1120-4, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 80-5, now
  easylist: 85896-187, now
  easyprivacy: 53045-62, now
  urlhaus-1: 26255-0, now
  plowe-0: 3542-1360, now
  SWE-1: 4881-39, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 14 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 163 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  darko.audio: 8
  wp.com: 2
 extended:
  ###ubm-banners-29 > .ubm_banner > [href] > video
  ###ubm-banners-19 > div.ubm_banner > [href] > video
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://www.facebook.com/dialog/share?"]
  ###sb_instagram
  ##.cmplz-show-banner
  ##.pswp__button--share
  ###cmplz-cookiebanner-container
  ##.cookie-statement
  ##.bimber-microshare-item-share
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
darko.audio##.ubm_banner
```

@ryanbr
