### ISSUE TITLE
10play.com.au: detection

### ISSUE THREAD

**Issue by ThreeeDots** [uBlockOrigin/uAssets#25253]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://10play.com.au/ambulance-australia`

### Category

detection

### Description

10play detects uBlock origin (detects an adblocker) and refuses to play media.

### Other extensions used

- AdBlock (disabled on the webpage, and webpage reloaded)
- NordPass
- Gmail unsubscribe
- ScribeHow

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150824
 cosmetic: 48192
 scriptlet: 22267
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39922-378, now Δ
  ublock-badware: 11013-26, now Δ
  ublock-privacy: 1126-4, now Δ
  ublock-unbreak: 2471-0, now Δ
  ublock-quick-fixes: 94-1, now Δ
  easylist: 85888-60, now Δ
  easyprivacy: 53032-662, now Δ
  urlhaus-1: 25845-0, 1h.1m
  plowe-0: 3547-372, 5d.3h.28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1432 ms
 maxAssetCacheWait: 292 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  10play.com.au: 1
  appboycdn.com: 1
  bing.com: 1
  googletagmanager.com: 3
  proxycheck.io: 1
  tiqcdn.com: 1
  trackjs.com: 4
  yimg.com: 1
 extended:
  ##.content__ad__content
  ###mpu_top
  ###adhesion
  ##.adhesion:not(body)
  ##.mrec
  ##+js(set-constant, moatPrebidApi, {})
  ##+js(set-constant, moatPrebidApi.getMoatTargetingForPage, noopF…
  ##+js(m3u-prune, /^https?:\/\/redirector\.googlevideo\.com.*/, /…
  ##+js(json-prune, cuepoints, cuepoints.[].start cuepoints.[].end…
```
</details>

**Comment by ThreeeDots** [comment]
I have completely removed AdBlock and the issue persists. Issue persists regardless of if uBlock is switched on or not (I.e., I pause it on the site and the site still says "adblocker detected")

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/22964
