### ISSUE TITLE
linkneverdie2.com: detection

### ISSUE THREAD

**Issue by tumo07** [uBlockOrigin/uAssets#25269]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://linkneverdie2.com/game/the-last-of-us-c-b-8016`

### Category

detection

### Description

website detected an adblocker

### Other extensions used

fastforward sponsorblock for youtube youtube auto hd + fps

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 150759
 cosmetic: 48200
 scriptlet: 22278
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39941-275, 28m Δ
  ublock-badware: 11052-6, 28m Δ
  ublock-privacy: 1126-2, 28m Δ
  ublock-unbreak: 2471-0, 28m Δ
  ublock-quick-fixes: 96-0, 28m Δ
  easylist: 85897-573, 28m Δ
  easyprivacy: 53047-647, 28m Δ
  urlhaus-1: 25720-0, now
  plowe-0: 3542-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 856 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  doubleclick.net: 2
  google.com: 8
  googlesyndication.com: 2
  googletagmanager.com: 1
  holahupa.com: 1
  jwpcdn.com: 1
  jwpltx.com: 2
  youtube.com: 11
```
</details>

**Comment by stephenhawk8054** [comment]
@hoang-rio Sorry, can you check this?

**Comment by stephenhawk8054** [comment]
Fixed in `ABPVN List`. Please enable that list.
