### ISSUE TITLE
Blacklisted site

### ISSUE THREAD

**Issue by dusanpudar** [uBlockOrigin/uAssets#25267]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://klikercentar.rs/
```

### Description

Dear,

last night we were hacked, where malware was introduced and these two files were infected:

https://klikercentar.rs/sgf.exe
https://klikercentar.rs/vrgeh.exe

We deleted the malware, but the site is still blacklisted, so please remove us if we are blacklisted.

Thank you, 
Dusan 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/user-attachments/assets/9d9db871-dd62-4de6-9bab-f2d51ffc0f3a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151034
 cosmetic: 48200
 scriptlet: 22278
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39941-142, 3h.9m Δ
  ublock-badware: 11052-6, 3h.9m Δ
  ublock-privacy: 1126-2, 3h.9m Δ
  ublock-unbreak: 2471-0, 3h.9m Δ
  ublock-quick-fixes: 96-0, 3h.9m Δ
  easylist: 85897-573, 3h.9m Δ
  easyprivacy: 53047-780, 3h.9m Δ
  urlhaus-1: 25995-0, 4h.9m
  plowe-0: 3542-0, 3h.9m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1537 ms
 maxAssetCacheWait: 430 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 113
 network:
  klikercentar.rs: 108
  googletagmanager.com: 1
  hs-analytics.net: 1
  hs-banner.com: 1
  hsadspixel.net: 1
  hsforms.com: 1

```
</details>

**Comment by stephenhawk8054** [comment]
Don't open duplicated issue
