### ISSUE TITLE
[nsfw] sankakucomplex.com: ads

### ISSUE THREAD

**Issue by herzblutnord** [uBlockOrigin/uAssets#25266]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.sankakucomplex.com/
https://www.sankakucomplex.com/de?tags=threshold%3A0%20watanabe_akio%20matsushima_michiru
```

### Description

after enabling the beta website ui at the top of the website,
not all ads on sankaku complex's search results are filtered

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot - search results](https://safe.herz.moe/tmD4QLXO.png)
[Screenshot - top page](https://safe.herz.moe/OT6qH44x.png)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153395
 cosmetic: 53347
 scriptlet: 22278
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39941-291, 42m Δ
  ublock-badware: 11052-6, 42m Δ
  ublock-privacy: 1126-2, 42m Δ
  ublock-unbreak: 2471-0, 42m Δ
  ublock-quick-fixes: 96-0, 42m Δ
  easylist: 85897-584, 42m Δ
  easyprivacy: 53047-655, 42m Δ
  urlhaus-1: 25995-0, 42m
  plowe-0: 3547-0, 5d.17h.9m
  DEU-0: 7547-3, 42m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 420 ms
 maxAssetCacheWait: 114 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  sankakucomplex.com: 2
  google.com: 3
  google.de: 2
  otaserve.net: 1
 extended:
  ##+js(no-setInterval-if, visibility, 1000)
  ##+js(abort-on-property-read, BetterJsPop)
  ##+js(abort-on-property-read, popns)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)

```
</details>

**Comment by D4niloMR** [comment]
Test:

```adb
sankakucomplex.com##+js(set, Object.prototype.hideAds, true)
````

Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by herzblutnord** [comment]
Ah nice, all the little "hide ads" texts and the smaller ad spaces are gone now,
but the big ad gallery that appears in searches is still there

[screenshot of the remaining ads](https://safe.herz.moe/Goo7CnUU.png)

**Comment by D4niloMR** [comment]
Are they really ads? It looks like it's just their own blog posts.

**Comment by herzblutnord** [comment]
Oh yeah, they go to https://news.sankakucomplex.com/, i hadnt actually clicked on them since they looked like ads to me. sorry, my mistake

then yeah its resolved now, thank you a lot :)
