### ISSUE TITLE
civitai.com: breakage

### ISSUE THREAD

**Issue by SleepingCrows** [uBlockOrigin/uAssets#25260]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://civitai.com/models`

### Category

breakage

### Description

Civitai's adblock detection appears to be re-injecting the detection banner in it's model list every second, causing it to be near impossible to use.

It's related to the rules created back in #22203, though there was no mention of this occurring at that time.

### Other extensions used

Dark Reader (Disabled)
Violentmonkey (no userscripts installed for civitai.com)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screencast_20240908_180613.webm](https://github.com/user-attachments/assets/e931adaa-4dad-4108-98a7-f691f753b06a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 155835
 cosmetic: 48127
 scriptlet: 20759
 html: 1958
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40125-138, 1h.36m Δ
  ublock-badware: 11054-6, 1h.36m Δ
  ublock-privacy: 1120-4, 1h.36m Δ
  ublock-unbreak: 2530-1, 1h.36m Δ
  ublock-quick-fixes: 80-5, 1h.36m Δ
  easylist: 85896-187, 1h.36m Δ
  adguard-spyware-url: 1687-125, now
  easyprivacy: 53045-62, 1h.36m Δ
  urlhaus-1: 26255-0, now
  curben-phishing: 516-3, now
  plowe-0: 3542-993, now
  LegitimateURLShortener: 2670-165, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 109 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  civitai.com: 1
  cloudflareinsights.com: 1
  stripe.com: 4
  uniconsent.com: 2
 extended:
  ##+js(prevent-fetch, googlesyndication)
```
</details>

**Comment by D4niloMR** [comment]
Caused by https://github.com/uBlockOrigin/uAssets/commit/38908fa3b521d254c4976089ff37b899d3020040

**Comment by D4niloMR** [comment]
Can you test if this works fine on your end?

```adb
civitai.com#@#div.shadow:has(a[href="/pricing"] img[alt="Please support civitai and creators by disabling adblock"])
civitai.com##div.shadow:has(a[href="/pricing"] img[alt="Please support civitai and creators by disabling adblock"]):remove()
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by SleepingCrows** [comment]
> Can you test if this works fine on your end?
> 
> ```
> civitai.com#@#div.shadow:has(a[href="/pricing"] img[alt="Please support civitai and creators by disabling adblock"])
> civitai.com##div:is(.shadow, .flex.w-full.justify-center.p-3[style=""]):has(a[href="/pricing"] img[alt="Please support civitai and creators by disabling adblock"]):remove()
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Works great, thanks!
