### ISSUE TITLE
alternativeto.net: ads

### ISSUE THREAD

**Issue by Antsy4904** [uBlockOrigin/uAssets#25262]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://alternativeto.net/software/invidious/`

### Category

ads

### Description

Sponsored alternatives shows up on some pages but not all, they also show up on the info pages like this one: `https://alternativeto.net/software/invidious/about/`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pic](https://github.com/user-attachments/assets/07f963fe-684c-46ec-ba66-ebae7b4e6a57)
![pic2](https://github.com/user-attachments/assets/5b14f2fe-b8ae-42b5-819f-ab48a1dd7321)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151709
 cosmetic: 47552
 scriptlet: 20497
 html: 1887
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39481-118, 3m Δ
  ublock-badware: 9899-1, 3m Δ
  ublock-privacy: 1042-4, 3m Δ
  ublock-unbreak: 2465-1, 3m Δ
  ublock-quick-fixes: 173-2, 3m Δ
  easylist: 87552-170, 3m Δ
  easyprivacy: 52996-62, 3m Δ
  urlhaus-1: 25995-0, now
  plowe-0: 3542-989, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1315 ms
 maxAssetCacheWait: 22 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  requestmetrics.com: 2
  trackjs.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
alternativeto.net##.bannerLink
```

@ryanbr
