### ISSUE TITLE
foxnews.com: breakage

### ISSUE THREAD

**Issue by GitHubBJW** [uBlockOrigin/uAssets#25273]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.foxnews.com/media/pelosi-suggests-trump-might-skip-presidential-debate-against-harris-i-know-cowardice-when-i-see-it`

### Category

breakage

### Description

I noticed the comments section has disappeared when UBO is on.

### Other extensions used

LastPass, Webroot, Video Speed Controller, Absolute Enable Right-Click & Copy, Chrome Remote Desktop

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150754
 cosmetic: 48293
 scriptlet: 22253
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 136-10, never
  easylist: 85889-468, 2h Δ
  easyprivacy: 53047-629, 2h Δ
  plowe-0: 3543-0, now
  ublock-badware: 11085-6, 2h Δ
  ublock-filters: 39941-372, 2h Δ
  ublock-privacy: 1126-2, 2h Δ
  ublock-unbreak: 2471-19, 2h Δ
  urlhaus-1: 25720-0, now
filterset (user): [array of 137 redacted]
trustedset:
 added: [array of 103 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 819 ms (selfie)
 maxAssetCacheWait: 547 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  foxnews.com: 1
  amazon-adsystem.com: 1
  appboycdn.com: 1
  atp.fox: 1
  b2c.com: 2
  bing.com: 1
  criteo.net: 1
  datadoghq-browser-agent.com: 1
  doubleclick.net: 1
  doubleverify.com: 1
  google.com: 5
  googletagmanager.com: 2
  h-cdn.com: 1
  imrworldwide.com: 1
  ketchcdn.com: 1
  knotch-cdn.com: 1
  outbrain.com: 1
  peer-39.com: 2
  yahoo.com: 2
  yimg.com: 1
 extended:
  ##.ad-w-300
  ##.sticky-ads
  ##.ad-w-728
  ##.OUTBRAIN
  ##div.tablet-desktop.vendor-unit:nth-of-type(4)
  ##div.tablet-desktop.vendor-unit:nth-of-type(3)
  ##.ad
  ##.ad-container
  ##.vendor-unit
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
- needing a us ip to see the comments (european ip => no comment)

**Comment by gelliss** [comment]
August 2, 2026   I loaded a new profile in the latest Brave browser, disabled all built in shields,. tested foxnews and their videos played. I then installed ublock origin from brave://settings/extensions/v2 so everything was defaults. I then get a network error on those videos. I also installed Firefox with only ublock origin and that worked and did not give any network error. So it appears to be only chomium browsers affected as Edge also gives the network error if I install ublock origin. Google Chrome also gives the network error with Ublock origin Lite installed.

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO?

**Comment by gelliss** [comment]
The video starts to play with uBO off but an ad plays before the actual video.

**Comment by stephenhawk8054** [comment]
Ignore the ads. Does the real video play on your side?

**Comment by gelliss** [comment]
No, it does not play. All I get in the video window is a message saying I lost network connection.

**Comment by stephenhawk8054** [comment]
Then it's website's issue, not uBO's issue.

**Comment by gelliss** [comment]
Ok.  It works in firefox with uBO so I figured it was an issue with uBO and chromium browsers.  With uBO turned on in Brave or Edge, all I get is a network error on the video screens  With uBO removed, the video plays normally but with the ad first.

**Comment by stephenhawk8054** [comment]
I mean the real video doesn't play normally on my side either. The reason you see errors with uBO on is simply because the ads are blocked and you go straight to the real videos. Without uBO, after you let the ads play, the real videos give the same errors.

**Comment by gelliss** [comment]
Tested across multiple browsers to narrow down the video playback error on Fox News in Windows 11:

    Brave (Normal Window, Shields OFF, uBO removed): Video immediately fails with "Network Connection Lost".

    Brave (Private Window, Shields OFF, uBO removed): The pre-roll ad plays, but as soon as it tries to hand off to the main video, the "Network Connection Lost" error pops up.

    Edge (Normal & Private Windows, uBO removed): Immediately throws the "Network Connection Lost" error.

    Firefox (with uBO enabled): The ad is blocked cleanly, and the main video plays with zero errors.

It looks like Fox News's video player script/handoff is fundamentally broken on Chromium engines when tracking/ad calls fail or get handled natively, whereas Firefox with uBO handles the stream handoff properly.
