### ISSUE TITLE
selfassessment.eastherts.gov.uk: breakage

### ISSUE THREAD

**Issue by RobertEves92** [uBlockOrigin/uAssets#25275]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://selfassessment.eastherts.gov.uk/
```

### Description

Blocks content of webpage from loading once an account is logged in to

### Other extensions used

Adobe Acrobat PDF
Application launcher foor drive
avg online security
fluff busting purity
microsoft single sign on
top cash back

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-09-09 204152 - without blocking](https://github.com/user-attachments/assets/ba5f3c31-948e-454a-92aa-d5e841dbc37c)
![Screenshot 2024-09-09 204234 - with blocking](https://github.com/user-attachments/assets/1280999d-44e9-4b22-a0b0-0ff4fb2ef1d4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150785
 cosmetic: 48202
 scriptlet: 22276
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-1, never
  easylist: 85889-573, 24m Δ
  easyprivacy: 53047-648, 24m Δ
  plowe-0: 3543-0, 13m
  ublock-badware: 11085-6, 24m Δ
  ublock-filters: 39941-275, 24m Δ
  ublock-privacy: 1126-2, 24m Δ
  ublock-quick-fixes: 96-0, 24m Δ
  ublock-unbreak: 2471-0, 24m Δ
  urlhaus-1: 25720-0, 13m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 49 redacted]
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 372 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0

```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
