### ISSUE TITLE
glitch.com: breakage

### ISSUE THREAD

**Issue by HyperSourceGithub** [uBlockOrigin/uAssets#25276]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://glitch.com/edit/`

### Category

breakage

### Description

When opening the editor it does not load, and returns an alert saying to reload. Reloading does nothing. (Desktop/Windows 11)

EDIT: Found another issue. I cannot turn off uBO from the menu, only when going into extensions and disabling it.
### Other extensions used

Headgear
DarkReader
Tabby Cat
SponsorBlock for YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/b1fe3020-ebac-4eae-a54c-bde2242cee71)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 150772
 cosmetic: 48136
 scriptlet: 20748
 html: 1958
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40130-138, 31m Δ
  ublock-badware: 11087-6, 31m Δ
  ublock-privacy: 1120-4, 31m Δ
  ublock-unbreak: 2530-1, 31m Δ
  ublock-quick-fixes: 80-5, 31m Δ
  easylist: 85904-558, 31m Δ
  easyprivacy: 53049-685, 31m Δ
  urlhaus-1: 25720-0, 31m
  plowe-0: 3543-0, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 690 ms
 maxAssetCacheWait: 323 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by HyperSourceGithub** [comment]
Retested. Turn-off issue gets fixed. Turns out that uBO was blocking it from asking me to sign-in.
