### ISSUE TITLE
www.infinityfree.com: breakage

### ISSUE THREAD

**Issue by Rivaraav** [uBlockOrigin/uAssets#25277]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.infinityfree.com/
```

### Description

Just like last time, the warning pop-up only appears on the InfinityFree website when using uBO.

### Other extensions used

Nothing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="824" alt="image" src="https://github.com/user-attachments/assets/7cc58b2c-baf8-405e-94af-ad843129ad85">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150498
 cosmetic: 48230
 scriptlet: 22277
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39957-134, now
  ublock-badware: 11085-6, now
  ublock-privacy: 1126-2, now
  ublock-unbreak: 2471-1, now
  ublock-quick-fixes: 96-7, 1h.39m Δ
  easylist: 85924-573, now
  easyprivacy: 53049-781, now
  urlhaus-1: 25410-0, 1h.39m
  plowe-0: 3543-0, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 242 ms (selfie)
 maxAssetCacheWait: 19 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

Continue in https://github.com/uBlockOrigin/uAssets/issues/25178
