### ISSUE TITLE
octopusenergy.de: breakage

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#25282]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://octopusenergy.de/signup/1-start`

### Category

breakage

### Description

Click Verbrauch schätzen
Doesn't load
The following cookie has to be allowed: under Marketing, the second Typeform entry

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 153945
 cosmetic: 84967
 scriptlet: 23518
 html: 1960
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31707-71, never
  ublock-cookies-adguard: 1744-9, never
 default:
  user-filters: 0-0, never
  ublock-filters: 40593-140, 4m
  ublock-badware: 11096-6, 3m Δ
  ublock-privacy: 1121-4, 4m
  ublock-unbreak: 2532-1, 4m
  ublock-quick-fixes: 80-5, 3m Δ
  adguard-mobile: 9628-73, 5m
  easylist: 85937-260, 3m Δ
  easyprivacy: 53050-71, 3m Δ
  urlhaus-1: 25220-0, 5m
  plowe-0: 3543-1068, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4057 ms
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  consentmanager.net: 1
  vercel-insights.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||delivery.consentmanager.net/delivery/$script,xhr,domain=octopusenergy.de
```

cc @Alex-302

**Comment by Alex-302** [comment]
@stephenhawk8054 Done.

**Comment by Alex-302** [comment]
@IDKwhattoputhere Please test 
```
octopusenergy.de#$#body div[id^="cmpbox"] { display: none !important; }
octopusenergy.de#$#body { overflow: auto !important; }
```
Replaced trusted scriptlet by CSS rules.

**Comment by stephenhawk8054** [comment]
What is broken if clicking on refusing cookie button?

**Comment by stephenhawk8054** [comment]
The cookies are set as encrypted value so they could potentially cause breakages if we use `set-cookie` approach. To prevent breakages, the only option is using `trusted-click-element` on `Accept all` button (or `a.cmptxt_btn_yes` button).

@Alex-302 Sorry, what do you think?

**Comment by Alex-302** [comment]
@stephenhawk8054 But why not `cmptxt_btn_no`?

**Comment by stephenhawk8054** [comment]
@Alex-302 I think OP means the (type) forms on the site would be broken, but I'm not too familiar with this site

> It's a questionnaire to get an estimate of how much gas and energy you need.
> It's not a core functionality of the website but I thought I should report it anyways.

**Comment by Alex-302** [comment]
On my end, all good when cookie popup is just hidden

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/4238ea6f-fb44-4e6f-b5c9-fd1d7839a831)


</details>

**Comment by stephenhawk8054** [comment]
@Alex-302 Looks like these steps for me:

1. Click on "Reject all"
2. Fill in the form
3. Scroll down and click on the `? Verbrauch schätzen` button

Then I see this

![image](https://github.com/user-attachments/assets/7f530b70-4e01-4959-839d-1fb3d1c869d0)

**Comment by Alex-302** [comment]
Hmm. I think this popup is better, than allow cookies for all Typeform partners on all sites.

**Comment by stephenhawk8054** [comment]
@Alex-302 I think another way is using `trusted-set` for `cmp_importvendors` to this value: `["s23","s2564"]`

```adb
octopusenergy.de##+js(trusted-set, cmp_importvendors, '{"value": ["s23","s2564"]}')
```

This way we don't need to allow cookies for all partners. I see the values of those vendors in this:

<details>

![image](https://github.com/user-attachments/assets/94e24ba5-3ca5-464f-8657-11e9c67a77f0)

</details>

After I apply that rule, the form auto opens

**Comment by Alex-302** [comment]
With this rule the next step is broken on my end

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/b3a62e08-1345-4a5f-ae8a-6892fc6ef1d8)


</details>

All good when you checked?

**Comment by stephenhawk8054** [comment]
Hmm... Next steps look working for me:

![image](https://github.com/user-attachments/assets/48f24bed-3f75-4a5b-972c-e556f71960a1)

I don't see those error messages either, the `cmpblocker.alwaysonvendors` returns the above array for me

![image](https://github.com/user-attachments/assets/ee8961d4-19ca-4e06-9d1f-083dee532ad5)

**Comment by Alex-302** [comment]
@stephenhawk8054 Hm. Now with a bit changed rule in AG syntax and two CSS rules for hiding cookie consent all good, no the gray popup
`octopusenergy.de#%#//scriptlet('trusted-set-constant', 'cmp_importvendors', '["s23","s2564"]')`

**Comment by stephenhawk8054** [comment]
@Alex-302 I haven't checked yet, but from OP's comment above, looks like there's still issues on mobile.

**Comment by Alex-302** [comment]
Added also `form.typeform.com##div[data-qa="cookie-region"]` (in iframe)

**Comment by Alex-302** [comment]
@IDKwhattoputhere Better post also screenshots.

**Comment by Alex-302** [comment]
@IDKwhattoputhere Broken by `octopusenergy.de#%#//scriptlet('trusted-set-constant', 'cmp_importvendors', '["s23","s2564"]')`?

**Comment by stephenhawk8054** [comment]
@Alex-302 Ok, I think @IDKwhattoputhere means the scriptlet is working fine. I can open the form normally in Firefox mobile with `trusted-set`. I'll add the trusted rule to uBO later.
