### ISSUE TITLE
allb.game-db.tw: breakage

### ISSUE THREAD

**Issue by Sithobi1** [uBlockOrigin/uAssets#25281]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://allb.game-db.tw/memoria/%E3%82%B3%E3%83%BC%E3%83%AB%E3%83%BB%E3%83%A6%E3%82%A2%E3%83%BB%E3%83%8D%E3%83%BC%E3%83%A0`

### Category

breakage

### Description

There is dynamically loaded content at the bottom of the page which only shows with adblock disabled.

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7d2b9dde-1387-4f99-904a-8635c2525266)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150564
 cosmetic: 48254
 scriptlet: 22282
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 28-0, never
  easylist: 85937-48, now
  easyprivacy: 53050-663, now
  plowe-0: 3543-371, now
  ublock-badware: 11135-26, now
  ublock-filters: 39960-378, now
  ublock-privacy: 1126-4, now
  ublock-quick-fixes: 96-1, now
  ublock-unbreak: 2470-12, now
  urlhaus-1: 25410-0, now
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 612 ms (selfie)
 maxAssetCacheWait: 170 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=allb.game-db.tw
```

@Yuki2718 I'm not sure for which list?
