### ISSUE TITLE
10play.com.au: detection

### ISSUE THREAD

**Issue by GamingMindfreak** [uBlockOrigin/uAssets#25290]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://10play.com.au/the-amazing-race-australia`

### Category

detection

### Description

When specifically on The Amazing Race show on 10play I get **"Stream initialization failed
An unexpected error has occurred"** When i turn uBlock off it starts working with ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1486" alt="Screenshot 2024-09-11 at 4 04 36 PM" src="https://github.com/user-attachments/assets/ebf574d5-4c80-474e-b4db-8441b459663e">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150463
 cosmetic: 48239
 scriptlet: 22266
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 85981-574, 20m
  easyprivacy: 53053-648, 20m Δ
  plowe-0: 3543-0, 20m
  ublock-badware: 11153-6, 20m
  ublock-filters: 39957-275, 20m
  ublock-privacy: 1112-2, 20m
  ublock-quick-fixes: 97-0, 20m
  ublock-unbreak: 2470-0, 20m
  urlhaus-1: 25255-0, 20m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  10play.com.au: 1
  adsrvr.org: 1
  appboycdn.com: 1
  bing.com: 1
  branch.io: 1
  doubleclick.net: 4
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 3
  imasdk.googleapis.com: 1
  imrworldwide.com: 2
  moatads.com: 2
  proxycheck.io: 1
  tealiumiq.com: 2
  tiktok.com: 1
  tiqcdn.com: 1
  trackjs.com: 4
  tremorhub.com: 1
  yimg.com: 1
 extended:
  ##.content__ad__content
  ###mpu_top
  ###adhesion
  ##.adhesion:not(body)
  ###adSkinLeft
  ###adSkinRight
  ##.mrec
  ##+js(set-constant, moatPrebidApi, {})
  ##+js(set-constant, moatPrebidApi.getMoatTargetingForPage, noopF…
  ##+js(m3u-prune, /^https?:\/\/redirector\.googlevideo\.com.*/, /…
  ##+js(json-prune, cuepoints, cuepoints.[].start cuepoints.[].end…
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
```
</details>

**Comment by Sidewindr** [comment]
This is not a duplicate... I am having the same issue with just this show.

**Comment by stephenhawk8054** [comment]
Just continue in that thread

**Comment by Sidewindr** [comment]
![image](https://github.com/user-attachments/assets/cb4fb830-b348-4eba-8592-3d1cc1a54faa)

This is only for this show... all other shows work fine.
