### ISSUE TITLE
repack.me: ads

### ISSUE THREAD

**Issue by 055110** [uBlockOrigin/uAssets#25298]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://repack.me/software/repacks/multimedia/505-topaz-video-enhance-ai.html`
`https://repack.me/download`

### Category

ads / badware

### Description

It shows an ad for Aeza, a hosting service on the side. When you are logged out, instead of giving you the real download link, they give you a fake download link which redirects to Yandex PUP, which has nothing to do with downloading the intended file.

### Other extensions used

none that would interfere with standard adblocking functions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://qu.ax/gMP.png
https://qu.ax/sBod.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 175914
 cosmetic: 192941
 scriptlet: 33368
 html: 2237
listset (total-discarded, last-updated):
 added:
  block-lan: 71-0, now
  adguard-cookies: 31739-50, now
  ublock-cookies-adguard: 1706-28, 1h.20m
  fanboy-cookiemonster: 68655-20610, 1h.20m
  ublock-cookies-easylist: 1706-1706, 1h.20m
  adguard-social: 23054-47, now
  fanboy-social: 17049-756, now
  fanboy-thirdparty_social: 68-19, now
  easylist-annoyances: 4768-57, now
  easylist-chat: 215-0, now
  easylist-newsletters: 7841-43, now
  easylist-notifications: 3497-164, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  ublock-filters: 40154-138, now Δ
  ublock-badware: 10965-6, now Δ
  ublock-privacy: 1097-2, now Δ
  ublock-unbreak: 2528-1, now
  ublock-quick-fixes: 85-4, 1h.20m
  easylist: 85978-187, now Δ
  easyprivacy: 53053-64, now Δ
  urlhaus-1: 25255-0, now
  plowe-0: 3543-995, now
  RUS-0: 40830-227, 1h.19m Δ
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 12693 ms (selfie)
 maxAssetCacheWait: 163 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ###back-top
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/01fca9278d02a0e9fc0c0a295b27b283ba268aff

**Comment by 055110** [comment]
its back, more ads

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/ebd2239d747f903399e719e48d70a76cf579dd15
