### ISSUE TITLE
swiftuploads.com: popups

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#25302]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [ ] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.swiftuploads.com/2WVGr6AWGkx7/file`

### Category

popups

### Description

free dow. button has this popup, misleading, malicious

### Other extensions used

...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![safasfasfasf](https://github.com/user-attachments/assets/73faa5ba-1c05-4d77-b1e1-004372d28baa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 178076
 cosmetic: 175134
 scriptlet: 35739
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/fake.txt: 12710-0, 5m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt: 23958-136, 1m
  adguard-cookies: 31752-80, 5m
  easylist-annoyances: 4768-15, 1m
  easylist-chat: 215-0, 5m
  easylist-newsletters: 7850-26, 1m
  easylist-notifications: 3497-82, 1m
  fanboy-cookiemonster: 52040-4034, 1m
  fanboy-social: 17049-21, 1m
  fanboy-thirdparty_social: 68-0, 5m
  ublock-annoyances: 5997-29, 5m Δ
  ublock-cookies-easylist: 1718-9, 1m
 default:
  user-filters: 0-0, never
  TUR-0: 11274-11, 5m
  easylist: 85988-672, 5m Δ
  easyprivacy: 53053-761, 5m Δ
  plowe-0: 3543-0, 5m
  ublock-badware: 11103-6, 5m Δ
  ublock-filters: 39889-414, 5m Δ
  ublock-privacy: 1112-3, 5m Δ
  ublock-quick-fixes: 101-0, 5m Δ
  ublock-unbreak: 2469-6, 5m Δ
  urlhaus-1: 25255-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 888 ms (selfie)
 maxAssetCacheWait: 158 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
```
swiftuploads.com##+js(nowoif)
swiftuploads.com##div.mt-5
swiftuploads.com##.fw-500.w-100.radius.btn-md.btn-primary.btn
swiftuploads.com##.mt-auto.footer
