### ISSUE TITLE
nextbase.co.uk: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25306]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nextbase.co.uk/hub/european-dash-cam-legality-2022-/`

### Category

nuisance

### Description

Cookie notice present

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/569df92d-4472-48db-a93f-2fe9c792dfaa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 261708
 cosmetic: 252873
 scriptlet: 53856
 html: 2221
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-84, now
  adguard-generic: 83622-8450, now
  adguard-spyware-url: 1694-125, now
  adguard-spyware: 79767-21316, now
  curben-phishing: 523-0, now
  adguard-cookies: 31756-94, now
  ublock-cookies-adguard: 1718-28, now
  fanboy-cookiemonster: 52040-4064, now
  ublock-cookies-easylist: 1718-1718, now
  adguard-social: 23056-53, now
  fanboy-social: 17049-760, now
  adguard-popup-overlays: 27942-1065, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  ublock-filters: 40159-138, now
  ublock-badware: 11155-77, now
  ublock-privacy: 1097-14, now
  ublock-unbreak: 2528-2, now
  ublock-quick-fixes: 86-4, now
  easylist: 85988-23180, now
  easyprivacy: 53056-40237, now
  urlhaus-1: 25475-0, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 179 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  bigcommerce.com: 4
  config-security.com: 10
  danv01ao0kdr2.cloudfront.net: 1
  dwin1.com: 2
  facebook.net: 1
  geotargetly-api-2.com: 1
  googletagmanager.com: 2
  pushowl.com: 2
  trustpilot.com: 2
  unpkg.com: 1
 extended:
  ##.socialLinks
  ##.icon--facebook
  ##.icon--twitter
  ##.icon--instagram
  ##.icon--youtube
  ##.icon--linkedin
```
</details>

**Comment by gorhill** [comment]
This works for me:

    nextbase.co.uk##.consent-managermain
