### ISSUE TITLE
y2mate.is: detection

### ISSUE THREAD

**Issue by igtbap** [uBlockOrigin/uAssets#25307]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://en.y2mate.is/v94/`

### Category

detection

### Description

I haven't seen old site, Y2Mate triggers adblock detection, I made my short custom filter to prevent the detection from being triggered.

### Other extensions used

I used VPN Ultimate extension, still works without detection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 169324
 cosmetic: 68718
 scriptlet: 23757
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  ublock-filters: 39894-399, now
  ublock-badware: 11153-6, now
  ublock-privacy: 1112-2, now
  ublock-unbreak: 2469-0, now
  ublock-quick-fixes: 102-0, now
  easylist: 85988-467, now
  easyprivacy: 53056-648, now
  urlhaus-1: 25475-0, never
  plowe-0: 3543-0, 1m
  RUS-0: 40803-124, 1m
filterset (user): [array of 44 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 93893 ms (selfie)
 maxAssetCacheWait: 11712 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  acscdn.com: 1
  googletagmanager.com: 1
  sharethis.com: 1
 extended:
  ##+js(set-constant, MutationObserver.prototype.observe, noopFunc…
  ##+js(abort-on-property-write, afStorage)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
```
</details>

**Comment by igtbap** [comment]
If my issue is duplicate, you can delete it because I forgot about that.

**Comment by stephenhawk8054** [comment]
It just says `Sorry! Downloading Geo-restricted content is not possible.` on my side

![image](https://github.com/user-attachments/assets/1755f6d5-77a2-4661-8587-772586a11b21)

Which youtube link did you use to test?

**Comment by igtbap** [comment]
I tried https://www.youtube.com/watch?v=NU_cVvddz8A and it worked

**Comment by stephenhawk8054** [comment]
I can only reproduce if I enable Edge's Tracking Prevention. Turn off that and try again.

**Comment by igtbap** [comment]
> I can only reproduce if I enable Edge's Tracking Prevention. Turn off that and try again.
If I add my custom filter and I have Tracking Prevention enabled, no detection was triggered, I think it's Tracking Prevention bug

**Comment by stephenhawk8054** [comment]
> - [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.

Please report the issue to Edge.

**Comment by igtbap** [comment]
> > * [x]  I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
> 
> Please report the issue to Edge.

Thanks!
