### ISSUE TITLE
blick.ch: detection

### ISSUE THREAD

**Issue by reneschnell** [uBlockOrigin/uAssets#25309]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.blick.ch/`

### Category

detection

### Description

The news webpage i am visiting is blocking me from reading anything, because it detects ublock installation

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/d5e22dd9-e9b4-4c63-8a2d-bc8cd9bc5f7e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153259
 cosmetic: 53341
 scriptlet: 22263
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7557-1, 15m
 default:
  user-filters: 0-0, never
  easylist: 85988-583, 15m Δ
  easyprivacy: 53053-656, 15m Δ
  plowe-0: 3543-0, now
  ublock-badware: 11103-6, 15m Δ
  ublock-filters: 39889-290, 15m Δ
  ublock-privacy: 1112-2, 15m Δ
  ublock-quick-fixes: 101-0, 15m Δ
  ublock-unbreak: 2469-2, 15m Δ
  urlhaus-1: 25745-0, 15m
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 869 ms (selfie)
 maxAssetCacheWait: 170 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  cxense.com: 2
  googletagmanager.com: 1
  onesignal.com: 1
  ringier-advertising.ch: 1
  sentry.io: 5
 extended:
  ##+js(abort-on-property-read, _sp_._networkListenerData)
  ##+js(set-constant, Object.prototype.isAdDisabled, true)
  ##+js(remove-node-text, script, setNptTechAdblockerCookie)
  ##+js(remove-cookie, __adblocker)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue in https://github.com/uBlockOrigin/uAssets/issues/24977
