### ISSUE TITLE
bfmtv.com: nuisance

### ISSUE THREAD

**Issue by MoustaphaElPsyCongroo** [uBlockOrigin/uAssets#25317]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bfmtv.com/economie/international/la-chine-releve-fortement-l-age-legal-de-la-retraite-a-partir-de-2025_AD-202409130345.html?at_brand=BFMTV&at_compte=BFMTV&at_plateforme=twitter`

### Category

nuisance

### Description

Cookie notice appears on load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-09-14 17_52_19-La Chine relève fortement l'âge légal de la retraite, une première depuis les an](https://github.com/user-attachments/assets/321f0977-d1fc-4475-a9ac-be3379bf96bc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 139154
 cosmetic: 150093
 scriptlet: 48294
 html: 2222
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  adguard-generic: 83628-4109, now
  fanboy-cookiemonster: 52065-144, now
  ublock-cookies-easylist: 1720-13, now
  easylist-annoyances: 4769-59, now
  easylist-notifications: 3499-91, now
  ublock-annoyances: 5942-110, now Δ
 default:
  user-filters: 15-2, never
  ublock-filters: 40200-140, now Δ
  ublock-badware: 11151-6, now Δ
  ublock-privacy: 1101-2, now Δ
  ublock-unbreak: 2528-1, now Δ
  ublock-quick-fixes: 111-4, now Δ
  easylist: 86073-2069, now Δ
  urlhaus-1: 26055-0, now
  plowe-0: 3542-387, now
  FRA-0: 25303-438, now
filterset (user): [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 250 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  beop.io: 1
  opecloud.com: 1
  sascdn.com: 2
  utiq-aws.net: 1
 extended:
  ##.bloc_center_full
  ##.banner_top
  ##.BeOpWidget
  ##.OUTBRAIN
  ##.publicite
  #@#.display_ad
```
</details>

**Comment by stephenhawk8054** [comment]
Update the filter lists, open new tab and test again.

**Comment by MoustaphaElPsyCongroo** [comment]
Updated filter lists and isabled extensions - didn't work
Deleted cookies for this site in Firefox: now it works (??)
Anyways, fixed it seems, ty
