### ISSUE TITLE
vuighe3.com: ads

### ISSUE THREAD

**Issue by URF6160** [uBlockOrigin/uAssets#25312]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vuighe3.com/`

### Category

ads

### Description

when i try watch anything movie or video in there it still has ads 
Note: it still has chance that ads don't pop up sometimes
Another note: every time you click on another video it will pop up ads
### Other extensions used

Note: none of these affect uBO
Enhancer for YouTube™ 2.0.126
FastForward 0.2383
Free VPN for Edge - VPN Proxy VeePN 2.7.20 (doesn't use)
Microsoft Rewards 1.5
RoQoL - Improve your Roblox experience 2.35.0
Screenshot YouTube 2.4.1
SponsorBlock for YouTube - Skip Sponsorships 5.7
Stylish - Custom themes for any website 3.4.2 (no theme use)
Tampermonkey 5.1.1 (disabled)
Video DownloadHelper 9.1.0.43
Volume Booster - Increase your sound 1.1.10 (doesn't use)
vidIQ Vision for YouTube 3.115.0
Chess Assist 28.3
AHA Music - Song Finder for Browser 2.0.4
BTRoblox - Making Roblox Better 3.6.7
Better YouTube Shorts 3.7.2
Google Translate 2.0.16
HyperChat [Improved YouTube Chat] 3.0.1
Multiselect for YouTube™ 3.5
Music Score Downloader 0.5.8
RoGold - Level Up Roblox 1.6.3
RoPro - Enhance Your Roblox Experience 1.5.10.2
Truffle 4.7.1
WebNowPlaying 3.0.1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/af08024b-7e8d-4892-9dfe-e1fcebbbec13)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 151442
 cosmetic: 48233
 scriptlet: 22276
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39916-270, 28m Δ
  ublock-badware: 11149-6, 27m Δ
  ublock-privacy: 1117-2, 27m Δ
  ublock-unbreak: 2469-0, 27m Δ
  ublock-quick-fixes: 103-0, 28m Δ
  easylist: 86083-571, 27m Δ
  easyprivacy: 53057-646, 28m Δ
  urlhaus-1: 26160-0, now
  plowe-0: 3542-0, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1716 ms (selfie)
 maxAssetCacheWait: 744 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `ABPVN List` and test again.

**Comment by URF6160** [comment]
> Enable `ABPVN List` and test again.

ok it doesn't show ads but every time it will have a little bit of loading at start
thanks for the answer
