### ISSUE TITLE
littlecaesars.com: breakage

### ISSUE THREAD

**Issue by IronErro** [uBlockOrigin/uAssets#25311]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://littlecaesars.com/`

### Category

breakage

### Description

Clicking on various parts of the page will show that the page moves to the next part via the url however the page itself won't change until the page is refreshed. Example: Going to the website I find "https://littlecaesars.com/en-us/" as the home page. I click the "pickup" button on the page. The url at the top changes to "https://littlecaesars.com/en-us/order/pickup/" however the page itself does not change until hitting the "refresh" button. 

### Other extensions used

none, other extensions being used were filtered out while finding the problem extension. the problem only appeared while ublock was active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151249
 cosmetic: 48192
 scriptlet: 20735
 html: 1962
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40177-138, now
  ublock-badware: 11151-6, 1m
  ublock-privacy: 1102-2, 1m
  ublock-unbreak: 2528-1, now Δ
  ublock-quick-fixes: 86-4, 1m
  easylist: 86026-185, now Δ
  easyprivacy: 53057-62, 1m
  urlhaus-1: 26010-0, 1m
  plowe-0: 3542-992, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 514 ms
 maxAssetCacheWait: 278 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  accdab.net: 1
  adsrvr.org: 1
  cookielaw.org: 1
  googletagmanager.com: 1
  kochava.com: 1
  sentry.io: 3
  sift.com: 1
  treasuredata.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by IronErro** [comment]
Apologies, USA

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue.

**Comment by IronErro** [comment]
Hmmm I will take it down then and see if perhaps there is some interaction I am missing.
