### ISSUE TITLE
panel.freemcserver.net: ads

### ISSUE THREAD

**Issue by cD1rtX3** [uBlockOrigin/uAssets#25316]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://panel.freemcserver.net/`

### Category

ads

### Description

Quite a few ads left on the page. I think I've only experienced this today.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (671)](https://github.com/user-attachments/assets/ee40216c-b191-494b-a803-d59a8829a217)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151326
 cosmetic: 48248
 scriptlet: 22286
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  easylist: 86070-467, 33m Δ
  easyprivacy: 53056-646, 33m Δ
  plowe-0: 3542-0, now
  ublock-badware: 11149-6, 33m Δ
  ublock-filters: 39939-374, 33m Δ
  ublock-privacy: 1117-2, 33m Δ
  ublock-quick-fixes: 103-0, 33m Δ
  ublock-unbreak: 2469-0, 33m Δ
  urlhaus-1: 26055-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 338 ms (selfie)
 maxAssetCacheWait: 135 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  freemcserver.net: 1
  33across.com: 1
  3lift.com: 1
  4dex.io: 2
  a-mo.net: 2
  adition.com: 1
  adlightning.com: 1
  adnxs.com: 3
  amazon-adsystem.com: 1
  casalemedia.com: 1
  cloudflareinsights.com: 1
  creativecdn.com: 1
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  html-load.com: 2
  id5-sync.com: 1
  openx.net: 2
  pubmatic.com: 2
  rubiconproject.com: 2
  script.ac: 1
  setupad.net: 2
  smartadserver.com: 1
  trustpilot.com: 1
  uidapi.com: 1
  vntsm.com: 1
 extended:
  ##+js(set-constant, apstag.fetchBids.name, )
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  #@#+js(no-setTimeout-if, 0x)
```
</details>

**Comment by cD1rtX3** [comment]
GOD I FORGOT MY SERVER WAS CALLED THAT

**Comment by fish-token** [comment]
New issue; `panel.freemcserver.net` or just any `freemcserver.net` subdomain and path has strict adblock detection, **detecting** uBO Lite and breaking the site, forcing you to **disable** your adblocker.
