### ISSUE TITLE
nesmaps.com: ads

### ISSUE THREAD

**Issue by EmiliaLolaico** [uBlockOrigin/uAssets#25314]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.nesmaps.com/
```

### Description

still shows ads, tested with and without custom lists

### Other extensions used

tempermonkey but without any ad blocking scripts

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151389
 cosmetic: 48236
 scriptlet: 20736
 html: 1962
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 408-3, 2d.13h.33m
 default:
  user-filters: 0-0, never
  ublock-filters: 40180-138, 35m Δ
  ublock-badware: 11151-40, 35m Δ
  ublock-privacy: 1102-2, 35m Δ
  ublock-unbreak: 2528-32, 35m Δ
  ublock-quick-fixes: 87-4, 35m Δ
  easylist: 86083-155, 35m Δ
  easyprivacy: 53057-43, 35m Δ
  urlhaus-1: 25745-0, 1d.11m
  plowe-0: 3542-993, 7d.16h.47m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3337 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||nesmaps.com/images/ads/$image
nesmaps.com##[src^="images/ads/"]
```

@ryanbr
