### ISSUE TITLE
plutomovies.com: detection

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#25323]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://plutomovies.com/movie/717618/trevor-wallace-pterodactyl-20`

### Category

detection

### Description

uBlock Origin is detected and download button isn't visible as well as some additional general advertising on the page

### Other extensions used

Free Download Manager Extension 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1680" alt="Screen Shot 2024-09-14 at 4 19 55 PM" src="https://github.com/user-attachments/assets/125ef1e6-6904-4d6d-b4c3-20196cf3649c">
<img width="1680" alt="Screen Shot 2024-09-14 at 4 20 12 PM" src="https://github.com/user-attachments/assets/9265712d-3935-4bd0-ad15-8821f75276ec">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 160826
 cosmetic: 172182
 scriptlet: 37152
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31750-102, 14m
  ublock-cookies-adguard: 1720-9, 14m
  fanboy-cookiemonster: 52065-4067, 14m
  ublock-cookies-easylist: 1718-1715, 14m
  adguard-popup-overlays: 27920-40, now
  adguard-mobile-app-banners: 5445-1142, 14m
  adguard-other-annoyances: 14446-383, 14m
  easylist-annoyances: 4769-150, now
  easylist-newsletters: 7851-556, 14m
  easylist-notifications: 3499-206, 14m
  ublock-annoyances: 6000-102, 14m
 default:
  user-filters: 0-0, never
  ublock-filters: 39934-590, 14m
  ublock-badware: 11208-6, 14m
  ublock-privacy: 1114-2, 14m
  ublock-unbreak: 2469-2, 14m
  ublock-quick-fixes: 131-0, 14m
  easylist: 86104-644, 14m
  easyprivacy: 53056-767, 14m
  urlhaus-1: 26055-0, 14m
  plowe-0: 3542-1, 14m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1133 ms
 maxAssetCacheWait: 523 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  cybertronads.com: 1
  dioxidtoluyls.com: 1
  dochaseadx.com: 1
  doubleclick.net: 2
  google.com: 5
  googletagmanager.com: 2
  outheelrelict.com: 1
  pemsrv.com: 1
  push-sdk.com: 1
  youtube.com: 9
 extended:
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.ytp-pause-overlay
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  #@#+js(json-prune-xhr-response, playerAds adPlacements adSlots p…
  #@#+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}…
  #@#+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"…
```
</details>

**Comment by jimmysofat6864** [comment]
Also detected on the the download link part of the site as well. 

[https://dl.plutomovies.com/c96d010fc5eb4c97bda974c12961aced/trevor-wallace-pterodactyl-2023-waploaded-43556-mkv](https://dl.plutomovies.com/c96d010fc5eb4c97bda974c12961aced/trevor-wallace-pterodactyl-2023-waploaded-43556-mkv)
https://github.com/user-attachments/assets/3d40730e-2914-40f4-bee7-3102126d542c

**Comment by odopo** [comment]
I'm facing this on plutomovies.com with updated uBlock Origin Lite. Download button is not visible on content page and download page as mentioned in the original post. Button becomes visible when site is set to 'no filtering' in uBlock Origin Lite.

Content page:
`https://plutomovies.com/series/833777/second-shot-at-love-s01-e04`

Download page:
`https://dl.plutomovies.com/ddf6ce6ed6434aadb9c8ae138dc01e34/second-shot-at-love-s01e04-5883-mkv`

https://github.com/user-attachments/assets/c468f5ee-4e71-4197-b9d9-41c415ba7190


Troubleshooting information:

```yml
name: uBlock Origin Lite
version: 2025.709.1622
browser: Chrome Mobile 135 (android)
filtering:
 site: complete
 default: complete
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 adguard-mobile
 block-lan
 annoyances-cookies
 annoyances-others
 ind-0
 ubol-tests
```

**Comment by stephenhawk8054** [comment]
Use the slider and set that site to `Optimal` mode instead of `Complete` mode.

**Comment by odopo** [comment]
> Use the slider and set that site to `Optimal` mode instead of `Complete` mode.

Thanks! That worked now. I believe I had tried it before and there was no change but it works now.
