### ISSUE TITLE
ticketmaster.sg: detection

### ISSUE THREAD

**Issue by Xenonym** [uBlockOrigin/uAssets#25326]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ticketmaster.sg/ticket/area/24sg_goose/1779`

### Category

detection

### Description

When uBlock Origin is enabled on a Ticketmaster SG seat selection screen, a modal asking the user to disable Adblock is displayed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/919386df-121f-4c46-93ea-49be1acdc784)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151830
 cosmetic: 48293
 scriptlet: 20770
 html: 1963
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40258-138, now
  ublock-badware: 11215-6, now
  ublock-privacy: 1101-2, now
  ublock-unbreak: 2528-1, now
  easylist: 86134-183, now
  easyprivacy: 53060-62, now
  urlhaus-1: 26450-0, now
  plowe-0: 3542-992, now
  ublock-quick-fixes: 108-6, now
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 507 ms (selfie)
 maxAssetCacheWait: 112 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
 extended:
  ##+js(set-constant, detectAdblock, noopFunc)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by BlazeFTL** [comment]
Try
```
ticketmaster.sg##+js(nosiif, detector)
||ticketmaster.sg/js/adblock.js$script,1p
