### ISSUE TITLE
last.fm: breakage

### ISSUE THREAD

**Issue by julsehn** [uBlockOrigin/uAssets#25328]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.last.fm/`

### Category

breakage

### Description

Hello uBlock! Nice to meet you, and thanks for making this possible.

I'm facing issues that uBlock is blocking the reproduction of the YouTube video.

Also, this post may be a bit duplicated, but I started to experience these issues like 5–3 days ago or something

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlock
![image](https://github.com/user-attachments/assets/a7b3ee83-ebaf-449a-bc61-6a06fa509879)
Without uBlock
![image](https://github.com/user-attachments/assets/27a4d0a8-d044-4c93-b670-916cc25bbe27)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 152980
 cosmetic: 55145
 scriptlet: 21273
 html: 1963
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40258-138, now
  ublock-badware: 11215-6, now
  ublock-privacy: 1101-2, now
  ublock-unbreak: 2528-1, now
  ublock-quick-fixes: 87-4, 1m
  easylist: 86070-184, 1m
  easyprivacy: 53058-62, 1m
  urlhaus-1: 25255-0, 1m
  plowe-0: 3542-992, 1m
  spa-0: 4076-27, 1m
  spa-1: 5995-255, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9825 ms
 maxAssetCacheWait: 336 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  confiant-integrations.net: 1
  doubleclick.net: 1
  newrelic.com: 2
 extended:
  ###adSkinLeft
  ###adSkinRight
  ##.related-ads
  ##.tonefuze
  ##.full-bleed-ad-container
  ##.sidebar-ad-container
  ##.sticky-ad-container
```
</details>

**Comment by julsehn** [comment]
Sorry for creating another post.

**Comment by mapx-** [comment]
@julsehn 

I cannot reproduce your issue => from https://www.last.fm/music/Kraftwerk I'm able to click "play artist" and just playing fine

Reset uBO to defaults, disable ETP in firefox, disable any other extension and test again

**Comment by morrinson** [comment]
Hi.
I have a similar problem with this specific filter.
When active, the scrobbling from Deezer to Last.fm is blocked.
When disabled, everything's fine.
It took me a while to narrow down which filter was causing the issue among all of them.

Scrobbling info can be found here: https://www.last.fm/about/trackmymusic

Should I open a new specific issue for this matter?
Thanks in advance.

**Comment by stephenhawk8054** [comment]
Describe the steps to reproduce in details. I don't know what `the scrobbling from Deezer to Last.fm` means.

**Comment by morrinson** [comment]
First of all, you have to have a Last.fm account.
Scrobbling is described in the URL I provided: it enables you to "track" all the music you're listening to, either locally (with softwares such as Windows Media Player) or online (Deezer, Spotify).
After having listened to music, you can see on your account all the songs, albums, artists you've listened to.
This is enabled under the sharing preferences on your Deezer account (see pic below).
https://github.com/user-attachments/assets/414f7fcc-1fe7-4696-8ce5-28462dcbdc2d

When this specific filter is activated, the scrobbling does not work.
When I turn it off, it works just fine.
You can check this as all the tracks scrobbled appear on your account under the "recent tracks" section on top of your account main page.
Here is an example of a user's main page: 
`https://www.last.fm/fr/user/chouchou58`

Hope this helps.

**Comment by mapx-** [comment]
No issue on my end, tested with spotify.

> When this specific filter is activated, the scrobbling does not work.

What specific filter are you talking about ?
Did you try uBO with default settings / filter lists ?

provide also all your info (uBOL or uBO; if uBO go into uBO dashboard, support tab, copy and paste here: Troubleshooting Information)

**Comment by morrinson** [comment]
The filter "uBlock  filters - Privacy" (I double check this behavior on one of my computers yesterday, and on another one, scrobbling does not work at all with or without this filter / both with Firefox).
https://github.com/user-attachments/assets/8c1ffcd9-63fe-4a9f-975d-e78cbfa88347

I indeed do not have issue with Spotify, whatever the filters used.
In case it could help: I tried another ad blocker (adguard) on Firefox + Deezer and the scrobbling worked just fine.

Here are all the details:
- uBlock Origin
- copy of the Troubleshooting Information:

<details>

```yml
uBlock Origin: 1.66.4
Firefox: 143
filterset (summary):
 network: 438800
 cosmetic: 270212
 scriptlet: 58173
 html: 2697
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 118025-215, 1d.19h.23m
  adguard-generic: 87586-1457, 3d.6h.24m
  adguard-mobile: 11414-68, 3d.6h.24m
  adguard-social: 24806-44, 3d.6h.24m
  fanboy-thirdparty_social: 69-3, 6d.14h.26m
  fanboy-cookiemonster: 46459-150, 20h.22m
  fanboy-social: 17492-840, 6h.22m
  ublock-annoyances: 4562-78, 3h.21m Δ
  dpollock-0: 11756-455, 4d.21h.25m
  adguard-spyware-url: 2255-19, 3d.6h.24m
  block-lan: 86-2, 13d.22h.4m
  curben-phishing: 137550-8, 5h.22m
  [11 lists not shown]: [too many]
 default:
  user-filters: 70-1, never
  ublock-filters: 41293-3933, never
  ublock-badware: 10849-245, never
  ublock-privacy: 3504-610, never
  ublock-unbreak: 2759-189, never
  easylist: 78981-1246, 3h.21m Δ
  easyprivacy: 54668-29011, 3h.21m Δ
  plowe-0: 3444-1425, 4d.21h.25m
  FRA-0: 19332-375, 3d.6h.24m
  urlhaus-1: 30815-2, 5h.22m
  ublock-quick-fixes: 365-56, never
filterset (user): [array of 70 redacted]
trustedset:
 added: [array of 15 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2303 ms
 maxAssetCacheWait: 1553 ms
 cacheBackend: indexedDB
```

</details>

Let me know if I can provide you with any other relevant information.

**Comment by stephenhawk8054** [comment]
Please describe which buttons to click in details. I don't understand what to do with your description.

I have logged in to `last.fm` account, what should I click next in this screen:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/7c824694-2e01-4b0e-9db6-3a6c21dd667f" />

</details>

**Comment by mapx-** [comment]
fixed for deezer

**Comment by morrinson** [comment]
Thanks!
I guess the fix will come on my side with the next update.
I'll let you know about it.

**Comment by stephenhawk8054** [comment]
@morrinson You can add this as your custom filter and check again:

```adb
||deezer.com/ajax/gw-light.php?method=log.listen$badfilter
```

Go to uBO's settings > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by morrinson** [comment]
Thanks a lot both for your efforts, it works again!
