### ISSUE TITLE
indianshortner.in: detection

### ISSUE THREAD

**Issue by DARKBOYJYOTI** [uBlockOrigin/uAssets#25338]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

https://indianshortner.in/WpyOe
https://indianshortner.in/XB59paC3

### Category

Adblock Detected

Please disable adblock to proceed to the destination page

### Description

Adblock Detected

Please disable adblock to proceed to the destination page

### Other extensions used

Free download manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151882
 cosmetic: 48336
 scriptlet: 20817
 html: 1971
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40318-142, 13m Δ
  ublock-badware: 11215-6, 15m
  ublock-privacy: 1151-27, 15m
  ublock-unbreak: 2528-1, 13m Δ
  ublock-quick-fixes: 125-0, 10m Δ
  easylist: 85384-186, 15m
  easyprivacy: 53063-62, 15m
  urlhaus-1: 27245-0, 15m
  plowe-0: 3542-992, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 332 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  doubleclick.net: 5
  googlesyndication.com: 2
  wp.com: 2
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by BlazeFTL** [comment]
Test
```
nsp20.in###wpsafe-link:style(display: block !important;)
nsp20.in###wpsafe-link:others()
