### ISSUE TITLE
hgspot.hr: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25331]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hgspot.hr/`

### Category

nuisance

### Description

Cookie notice present

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/f4ad35e7-ff6f-43c8-bd60-5c0553edfc53)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 262869
 cosmetic: 252806
 scriptlet: 53961
 html: 2223
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-84, now
  adguard-generic: 83702-8486, now
  adguard-spyware-url: 1695-125, now
  adguard-spyware: 79771-21316, now
  curben-phishing: 515-1, now
  adguard-cookies: 31760-94, now
  ublock-cookies-adguard: 1741-28, now
  fanboy-cookiemonster: 52089-4072, now
  ublock-cookies-easylist: 1741-1741, now
  adguard-social: 23029-53, now
  fanboy-social: 17059-762, now
  adguard-popup-overlays: 27921-1057, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  ublock-filters: 40258-138, now
  ublock-badware: 11215-77, now
  ublock-privacy: 1101-14, now
  ublock-unbreak: 2528-2, now
  ublock-quick-fixes: 110-4, now
  easylist: 86144-23188, now
  easyprivacy: 53060-40240, now
  urlhaus-1: 26450-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 172 ms (selfie)
 maxAssetCacheWait: 119 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  facebook.net: 1
  onesignal.com: 2
 extended:
  ##.social-icons-top
  ##.cookies-header
  ##div.cookies-body
  ##.cookies-footer
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
hgspot.hr###cookies
```

cc @ryanbr @Alex-302
