### ISSUE TITLE
fanfox.net: ads

### ISSUE THREAD

**Issue by R3dflyter1** [uBlockOrigin/uAssets#25339]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fanfox.net/manga/dame_skill_auto_mode_ga_kakuseishimashita_are_guild_no_scout_san_ore_wo_iranai_tte_itte_masendeshita/c058/1.html`

### Category

ads

### Description

There is a top and bottom add banners on all the reading pages that were blocked before.

### Other extensions used

on operagx 
addguard( even disabeled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 167869
 cosmetic: 54940
 scriptlet: 22546
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 25303-39, now
  easylist: 85384-580, 5m Δ
  easyprivacy: 53063-853, 5m Δ
  plowe-0: 3542-31, now
  ublock-badware: 11213-22, 5m Δ
  ublock-filters: 40053-441, 5m Δ
  ublock-privacy: 1164-27, 5m Δ
  ublock-quick-fixes: 145-6, 5m Δ
  ublock-unbreak: 2469-5, 5m Δ
  urlhaus-1: 25255-0, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 882 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google-analytics.com: 1
  googletagmanager.com: 2
 extended:
  ##.ad-reader-con-item
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||adsmg.fanfox.net^
fanfox.net##.ad-reader
```

@ryanbr
