### ISSUE TITLE
[nsfw] ybupmr8.mymembermatchmagic.life: popups

### ISSUE THREAD

**Issue by Josepbennet** [uBlockOrigin/uAssets#25334]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ybupmr8.mymembermatchmagic.life/rw524dh?t=keitaro-xxx&cid=2ff2hq8jea8`

### Category

popups

### Description

Self directed web page that cannot be closed, instantly redirects to several other pages.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 130
filterset (summary):
 network: 153137
 cosmetic: 56879
 scriptlet: 20853
 html: 1964
listset (total-discarded, last-updated):
 default:
  user-filters: 13-1, never
  ublock-filters: 40722-139, now
  ublock-badware: 11209-6, now
  ublock-privacy: 1112-2, now
  ublock-unbreak: 2531-1, now
  ublock-quick-fixes: 112-4, now
  adguard-mobile: 9827-81, now
  easylist: 85383-258, now
  easyprivacy: 53061-71, now
  urlhaus-1: 27100-0, now
  plowe-0: 3542-1066, now
filterset (user): [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1932 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
What is your original page that leads to the above link?
