### ISSUE TITLE
gitflic.ru: ads

### ISSUE THREAD

**Issue by along02** [uBlockOrigin/uAssets#25342]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gitflic.ru/project/magnolia1234/bpc_uploads`

### Category

ads

### Description

There is an ad on the left.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1502" alt="Screenshot 2024-09-16 at 3 09 52 PM" src="https://github.com/user-attachments/assets/6d4c3d13-43de-4601-98dd-1bf4a3551074">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151966
 cosmetic: 48327
 scriptlet: 22357
 html: 0
listset (total-discarded, last-updated):
 added:
  block-lan: 71-0, now
 default:
  user-filters: 0-0, never
  easylist: 85384-572, now Δ
  easyprivacy: 53063-648, now Δ
  plowe-0: 3542-0, now
  ublock-badware: 11213-6, now Δ
  ublock-filters: 40030-271, now Δ
  ublock-privacy: 1164-27, now Δ
  ublock-quick-fixes: 142-0, now Δ
  ublock-unbreak: 2469-0, now Δ
  urlhaus-1: 27245-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 274 ms
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  yandex.ru: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/b701659ac2a900d7530ffa4cd42d83ade959f6c8

**Comment by stephenhawk8054** [comment]
@along02 Fixed in `RU AdList`. Please enable that list.
