### ISSUE TITLE
ssyou.tube: popups

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#25341]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ssyou.tube/convert/?videoId=hWiyAGbQwKE`

### Category

popups

### Description

Click Convert button.

### Other extensions used

enhanced-h264ify
Keep One Pinned Tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-09-16_231938](https://github.com/user-attachments/assets/c2f28693-d316-455e-a099-df0eb0afbc4e)
![2024-09-16_232108](https://github.com/user-attachments/assets/d9a5aad1-e846-40b2-b56e-522c57ecddf6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 147009
 cosmetic: 120801
 scriptlet: 30723
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 24641-249, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1726-21, now
  adguard-cookies: 31792-41, now
  ublock-cookies-adguard: 1741-28, now
  ublock-annoyances: 6004-18, 1h.59m Δ
 default:
  user-filters: 6-0, never
  ublock-filters: 40053-277, 1h.59m Δ
  ublock-badware: 11213-6, 1h.59m Δ
  ublock-privacy: 1164-35, 1h.59m Δ
  ublock-unbreak: 2469-5, 1h.59m Δ
  ublock-quick-fixes: 145-0, 1h.59m Δ
  easylist: 85384-246, 1h.59m Δ
  easyprivacy: 53063-343, 1h.59m Δ
  RUS-0: 40723-238, 59m Δ
filterset (user): [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 645 ms (selfie)
 maxAssetCacheWait: 255 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  googletagmanager.com: 2
  grapseex.com: 1
  hossonxlqwf.com: 2
  midgerelativelyhoax.com: 1
 extended:
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
```
</details>

**Comment by dportvine** [comment]
`https://ssyou.tube/convert/?videoId=hWiyAGbQwKE`

<details>
<summary>Screen</summary>

https://github.com/user-attachments/assets/0e32b167-7cda-49f4-bd97-61000824305d
</details>

**Comment by mapx-** [comment]
test

`mmnm.store##+js(nowoif)`

**Comment by dportvine** [comment]
> test
> 
> ```
> mmnm.store##+js(nowoif, _blank)
> ```

Works for me.

<details>
<summary>Screen</summary>

![2024-11-14_124837](https://github.com/user-attachments/assets/f8bee5f1-1ab0-4b3d-92ac-a7d7b302d116)
</details>

**Comment by dportvine** [comment]
`https://ssyou.tube/convert/?videoId=hWiyAGbQwKE`

Another domain `y2meta-uk.com`, this rule works for me `y2meta-uk.com##+js(nowoif, _blank)`
