### ISSUE TITLE
viefaucet.com: breakage

### ISSUE THREAD

**Issue by Keksrok308** [uBlockOrigin/uAssets#25346]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://viefaucet.com/app/faucet`

### Category

breakage

### Description

When uBlock is turned on, part of the site disappears

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/d96c8e0a-9be5-4e95-ba1c-444c33bde10f)
![image](https://github.com/user-attachments/assets/bdbf4572-38c7-41bf-a05c-a38d4b208522)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 174023
 cosmetic: 139316
 scriptlet: 30989
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31834-65, 1m
  ublock-cookies-adguard: 1742-9, 1m
  fanboy-cookiemonster: 52148-4010, 1m
  ublock-cookies-easylist: 1742-1742, 1m
 default:
  user-filters: 3-0, never
  ublock-filters: 40088-273, 42m Δ
  ublock-badware: 11240-6, 42m Δ
  ublock-privacy: 1184-27, 42m Δ
  ublock-unbreak: 2466-0, 42m Δ
  ublock-quick-fixes: 144-0, 42m Δ
  easylist: 85301-575, 42m Δ
  easyprivacy: 53073-22, 42m Δ
  urlhaus-1: 26780-0, now
  plowe-0: 3542-624, now
  RUS-0: 40725-174, 42m Δ
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2021 ms (selfie)
 maxAssetCacheWait: 256 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  viefaucet.com: 1
  bmcdn5.com: 3
  coinzillatag.com: 1
  czilladx.com: 3
  google-analytics.com: 1
  googletagmanager.com: 1
 extended:
  ##.left-ads
  ##.right-ads
  ##.ads
  ##.is-guttered > .ads:upward(.is-guttered)
  ##+js(no-setTimeout-if, showAdblock)
```
</details>

**Comment by mapx-** [comment]
@Keksrok308 

see if helps:

`viefaucet.com#@#.is-guttered > .ads:upward(.is-guttered)`

**Comment by Keksrok308** [comment]
What helped me was adding to the rules:
no-cosmetic-filtering: viefaucet.com true
however, I thought you would fix this bug in uBlock itself

**Comment by mapx-** [comment]
I asked you to test the filter above

**Comment by Keksrok308** [comment]
Yes, this filter works too
