### ISSUE TITLE
filext.com: detection

### ISSUE THREAD

**Issue by hdbordercollie** [uBlockOrigin/uAssets#25358]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://filext.com/online-file-viewer.html`

### Category

detection

### Description

After uploading a file, it asks you to turn off your adblocker before it will let you interact with the file.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240918-110627_Firefox Beta](https://github.com/user-attachments/assets/f46202c4-2dc5-4c79-8b70-403a1a6218c0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 130
filterset (summary):
 network: 343526
 cosmetic: 266424
 scriptlet: 54238
 html: 2241
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 435-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 102962-3, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2666-2, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 408-1, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1210-2, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 102-0, now
  adguard-generic: 83686-4129, now
  adguard-spyware-url: 1708-244, now
  adguard-spyware: 80534-1535, now
  curben-phishing: 528-1, now
  adguard-cookies: 31869-61, now
  ublock-cookies-adguard: 1785-30, now
  [15 lists not shown]: [too many]
 default:
  user-filters: 137-12, never
  ublock-filters: 40933-143, 56m Δ
  ublock-badware: 11263-404, 56m Δ
  ublock-privacy: 1176-75, 56m Δ
  ublock-unbreak: 2525-1, 56m Δ
  ublock-quick-fixes: 123-4, 56m Δ
  adguard-mobile: 9784-127, now
  easylist: 85319-2238, 56m Δ
  easyprivacy: 53072-24914, 56m Δ
  urlhaus-1: 25640-0, now
  plowe-0: 3542-1162, now
filterset (user): [array of 137 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
 removed:
  no-csp-reports: * true
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11983 ms
 maxAssetCacheWait: 5986 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  github.com: 8
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
filext.com#@##b3c
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by hdbordercollie** [comment]
That works! Thanks for your contribution to this great project

**Comment by stephenhawk8054** [comment]
cc @Yuki2718 The filter is in EL. I can reproduce on Firefox desktop too.

**Comment by Yuki2718** [comment]
> The filter is in EL. I can reproduce on Firefox desktop too.

Hmm, I can't.

**Comment by Yuki2718** [comment]
> Disabling that filter leaves a 250px ad placeholder in the page where the uploaded file is read. We should fix this.

Actually hidind that or not doesn't change overall appearance much, as `.content-top` has `min-height: 620px`.

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/f22348ba4acae6812cb05af42a94f45137e928e1

**Comment by Yuki2718** [comment]
@uBlock-user Anyway not possible in EL, if you think it's needed, feel free to add any appropriate filters.

**Comment by igtbap** [comment]
Adblock detected triggered again!!!
Can you fix it? (Wait a few seconds for adblock detection to trigger)

**Comment by stephenhawk8054** [comment]
Please give exact link

**Comment by hdbordercollie** [comment]
That is the exact link. There is no specific link for an already-uploaded file.

**Comment by Yuki2718** [comment]
No problem on my end

**Comment by igtbap** [comment]
> ### URL address of the web page
> `https://filext.com/online-file-viewer.html`

It is exact link.

**Comment by gorhill** [comment]
Post a screenshot of how the detection looks like, and also your troubleshooting information for that page: Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)


> I use Microsoft Edge and I have tracking prevention disabled.

Did you try disabling to find out if this is what causes detection?

**Comment by igtbap** [comment]
> Post a screenshot of how the detection looks like, and also your troubleshooting information for that page: Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)
>

Here's my techincal infomation:

```
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 160455
 cosmetic: 70492
 scriptlet: 24752
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 40882-132, 4h.6m Δ
  ublock-badware: 12464-1, 4h.6m Δ
  ublock-privacy: 1654-28, 4h.6m Δ
  ublock-unbreak: 2542-1, 4h.6m Δ
  ublock-quick-fixes: 194-10, 4h.6m Δ
  easylist: 78571-222, 4h.6m Δ
  easyprivacy: 53312-145, 4h.6m Δ
  urlhaus-1: 23310-0, 5h.6m
  plowe-0: 3549-996, 1d.22h.59m
  RUS-0: 41043-145, 4h.6m Δ
filterset (user): [array of 45 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 108431 ms (selfie)
 maxAssetCacheWait: 6814 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  filext.com: 1
 extended:
  ###c1c
```

> Did you try disabling to find out if this is what causes detection?
Yes

**Comment by igtbap** [comment]
![image](https://github.com/user-attachments/assets/c39ffdf3-9672-4b79-aa0a-7929ff08a6fe)
Also, adblock detected popup

**Comment by igtbap** [comment]
I clicked "Accept" button, I don't think there will have ads

**Comment by igtbap** [comment]
Thanks! It worked!

**Comment by igtbap** [comment]
> > Also, adblock detected popup
> 
> Nope, that's not adblock detected popup, could be cookie consent or paywall popup
> 
> @igtbap Add `||privacy-mgmt.com^`

Can we update this filter? It works fine!

**Comment by stephenhawk8054** [comment]
It's cookie popup. You can enable cookie lists to block it. We don't block cookie popups by default.
