### ISSUE TITLE
feather-wallet.org + sparrowwallet.net + electrum.is: badware

### ISSUE THREAD

**Issue by HardenedSteel** [uBlockOrigin/uAssets#25353]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://feather-wallet.org/
https://sparrowwallet.net/
https://electrum.is/
```

### Description

Possibly all domains are owned by same person: https://wiki.archlinux.org/index.php?title=List_of_applications/Other&diff=prev&oldid=811318

The user banned from Archwiki: https://wiki.archlinux.org/index.php?title=Special:Log&logid=290835

### Other extensions used

N/A

### Screenshot(s)

N/A

### Configuration

N/A

**Comment by stephenhawk8054** [comment]
I can't access the last link (`https://electrum.is/`)

**Comment by nahuhh** [comment]
@stephenhawk8054  why would you want to?
the links are _not_ the official links.

**Comment by stephenhawk8054** [comment]
We need to confirm the websites' contents and also only add the links that can be accessed.

**Comment by HardenedSteel** [comment]
would web archive link help? https://web.archive.org/web/20240823125226/https://electrum.is/

**Comment by stephenhawk8054** [comment]
Maybe. Any more info would still be better.
