### ISSUE TITLE
bmo.com: breakage

### ISSUE THREAD

**Issue by akemi12** [uBlockOrigin/uAssets#25359]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www1.bmo.com/onlinebanking/cgi-bin/netbnx/NBmain
https://www1.bmo.com/banking/digital/login
```

### Description

Redirects to https://www1.bmo.com/banking/digital/error/system which shows a blank page. 
In incognito mode, this does not happen (I'm using Chrome on a mac)

### Other extensions used

Turned off other extensions to isolate it. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.1b22
Chromium: 128
filterset (summary):
 network: 150335
 cosmetic: 48444
 scriptlet: 22444
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  ublock-filters: 40219-373, 20m
  ublock-badware: 11268-24, 20m
  ublock-privacy: 1211-27, 12m Δ
  ublock-unbreak: 2464-31, 20m
  ublock-quick-fixes: 145-0, 12m Δ
  easylist: 85320-53, 12m Δ
  easyprivacy: 53072-21, 12m Δ
  urlhaus-1: 25640-0, 20m
  plowe-0: 3542-992, 20m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 13 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 29 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 5136 ms (selfie)
 maxAssetCacheWait: 611 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
