### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by JRM1962** [uBlockOrigin/uAssets#25354]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.facebook.com/?sk=h_chr`

### Category

ads

### Description

Starting 9-17-2024, "sponsored posts" on Facebook stopped being blocked. Prior to this, uBlockOrigin was doing a perfect job of blocking these posts. The site has become unbearable.

### Other extensions used

AdBlockPlus and Social Fixer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/3a2202c4-65b6-4ebf-9417-da150e7ed63f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 149913
 cosmetic: 48413
 scriptlet: 22424
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40169-135, now
  ublock-badware: 11267-6, now
  ublock-privacy: 1188-28, now
  ublock-unbreak: 2463-1, now
  ublock-quick-fixes: 145-6, now
  easylist: 85319-571, 44m
  easyprivacy: 53072-774, 43m
  urlhaus-1: 25255-0, 43m
  plowe-0: 3542-0, 43m
filterset (user): [empty]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2339 ms (selfie)
 maxAssetCacheWait: 161 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  facebook.com: 1
 hasUnprocessedRequest: true
 extended:
  ##:matches-path(/^\/(\?[a-z]+=\w+)?$/) div[aria-posinset] :is(h3…
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
