### ISSUE TITLE
xda-developers.com: breakage

### ISSUE THREAD

**Issue by shadowstepxda** [uBlockOrigin/uAssets#25357]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.xda-developers.com/windows-12-concept-video-makes-us-crave-for-features-that-dont-exist/
https://www.xda-developers.com/best-windows-tweaks-cant-live-without/
```

### Description

The default filter "uBlock filters – Ads" is breaking a few things on xda-developers.com. I've added two example URLs. In the first URL, under "PowerToys FancyZones", there is supposed to be a image viewer widget. That doesn't show up when "uBlock filters – Ads" is enabled. Similarly in the second URL, there is supposed to be at the end of the article, under "What's more you see in the Windows 12.1 concept video". That also doesn't show up when "uBlock filters – Ads" is enabled.

### Other extensions used

Bitwarden Password Manager, Blank Tab, Enhancer for YouTube™, IDM Integration Module, Redirect AMP to HTML, SponsorBlock for YouTube - Skip Sponsorships

### Screenshot(s)

<details>
<summary>URL 1 - With Filter Enabled</summary>

![URL 1 - With Filter Enabled](https://github.com/user-attachments/assets/32e2a4fc-57d6-4aef-a313-b4cb8840b6ea)

</details>

<details>
<summary>URL 1 - With Filter Disabled</summary>

![URL 1 - With Filter Disabled](https://github.com/user-attachments/assets/0ff494f2-00a7-43ee-b8b5-c3e6cd52d964)

</details>

<details>
<summary>URL 2 - With Filter Enabled</summary>

![URL 2 - With Filter Enabled](https://github.com/user-attachments/assets/b43d5ea3-4b2f-4758-add0-ae226fe02862)

</details>

<details>
<summary>URL 2 - With Filter Disabled</summary>

![URL 2 - With Filter Disabled](https://github.com/user-attachments/assets/d15e08dd-238c-4c4f-b0a0-94bd68f96551)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 136915
 cosmetic: 47667
 scriptlet: 21967
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39399-365, never
  ublock-badware: 9897-1, never
  ublock-privacy: 1047-2, never
  ublock-unbreak: 2406-0, never
  ublock-quick-fixes: 173-0, never
  easylist: 87552-83, never
  easyprivacy: 52996-37, never
  urlhaus-1: 11160-0, never
  plowe-0: 3548-989, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1836 ms
 maxAssetCacheWait: 17 ms
 cacheBackend: indexedDB
```
</details>

**Comment by dnet890** [comment]
@stephenhawk8054 it looks like the adblock blocker is coming up again. What do you think?
https://www.xda-developers.com
![Image](https://github.com/user-attachments/assets/b846a94f-1245-4675-a606-822cf5548827)

**Comment by stephenhawk8054** [comment]
I can't reproduce
