### ISSUE TITLE
tatrck.com: popups

### ISSUE THREAD

**Issue by kectalron** [uBlockOrigin/uAssets#25368]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tatrck.com/h/0Hu30vzr0XTq?url=https://pinzhicrafts.en.alibaba.com/productgrouplist-942019757/Diamond_Painting_Round_Frame.html?spm=a2700.shop_index.88.15.15be1b18fGV07P&r=https%3A%2F%2Fproductsearch.app%2F`

### Category

popups

### Description

When working in multiple tabs, it constantly gives an error saying the first 2 tabs are blocked by ublock. I can't understand why.
![Ekran görüntüsü 2024-09-19 134909](https://github.com/user-attachments/assets/9426566e-b902-4564-8668-c2b70bfa36c4)

### Other extensions used

![Ekran görüntüsü 2024-09-19 134909](https://github.com/user-attachments/assets/ac6e69e5-27b1-46fc-8c81-fcdde595e34e)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151734
 cosmetic: 56943
 scriptlet: 23857
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40211-283, 22m Δ
  ublock-badware: 11269-6, 22m Δ
  ublock-privacy: 1190-27, 22m Δ
  ublock-unbreak: 2464-0, 22m Δ
  ublock-quick-fixes: 146-0, 22m Δ
  easylist: 85348-579, 22m Δ
  easyprivacy: 53073-651, 22m Δ
  urlhaus-1: 25635-0, 14m
  plowe-0: 3550-0, 14m
  TUR-0: 11358-15, 14m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 505 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
What is the original link that leads you to the above URL?

**Comment by kectalron** [comment]
It's always on ebay

**Comment by stephenhawk8054** [comment]
Can you share the exact ebay link and describe how to reproduce the issue in more details?
