### ISSUE TITLE
redecanais.africa: nuisance

### ISSUE THREAD

**Issue by daveox** [uBlockOrigin/uAssets#25360]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://redecanais.africa/`

### Category

nuisance

### Description

I wanted to block the overlay on the site. Sometimes, it takes the whole screen width and there's no visible ''x'' to close it.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 114
filterset (summary):
 network: 150363
 cosmetic: 48619
 scriptlet: 22451
 html: 0
listset (total-discarded, last-updated):
 removed:
  spa-1: null
 default:
  user-filters: 254-7, never
  easylist: 85320-48, now
  easyprivacy: 53073-661, now
  plowe-0: 3542-371, 14m
  ublock-badware: 11269-24, 14m
  ublock-filters: 40210-373, 14m
  ublock-privacy: 1190-29, 14m
  ublock-quick-fixes: 148-3, 14m
  ublock-unbreak: 2464-12, 14m
  urlhaus-1: 25640-0, 14m
filterset (user): [array of 261 redacted]
trustedset:
 added: [array of 22 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 6 redacted]
hostRuleset:
 added: [array of 846 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms
 maxAssetCacheWait: 192 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  redecanais.africa: 1
  amung.us: 1
 extended:
  ##ul.list-unstyled [href="https://redisex.club/enter.php"]
  ##.pm-ads-banner
  ##+js(remove-attr, target, [target="_blank"], stay)
  ##+js(remove-node-text, script, ;}}};break;case $.)
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by daveox** [comment]
> Which country are you when accessing the site?

Brazil

**Comment by Alex-302** [comment]
Can't access. Which type of annoyance it - cookies of what?

**Comment by mapx-** [comment]
annoyance, needing a set-cookie filter

`redecanais.africa##+js(set-cookie, modalVisited, true)`

![image](https://github.com/user-attachments/assets/f00de1e8-a5fa-4702-8f16-81ec1ee92392)

**Comment by ryanbr** [comment]
can we get a desciption of the popup/ why its being used on the site. Just guage what we're trying to fix

**Comment by D4niloMR** [comment]
It warns that some Brazilian internet providers are blocking the site and advising to use Cloudflare DNS to circumvent.

```
Warning!

Internet operators are constantly blocking the RedeCanais address, so the site seems to be offline or having problems, which is not true!

But how do you unblock it?

Below are tutorials on how to unblock the site quickly to stop this censorship! These tutorials were used in the Google Chrome browser - we strongly recommend using this browser!
...
```

**Comment by daveox** [comment]
> annoyance, needing a `set-cookie` filter
> 
> ```
> redecanais.africa##+js(set-cookie, modalVisited, true)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/10303732/369381205-f00de1e8-a5fa-4702-8f16-81ec1ee92392.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDIxOTEsIm5iZiI6MTcyNjkwMTg5MSwicGF0aCI6Ii8xMDMwMzczMi8zNjkzODEyMDUtZjAwZGUxZTgtYTVmYS00NzAyLThmMTYtODFlYzFlZTkyMzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA2NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYzhlN2MwYTA0MTcyMjM5ZGVkMjkyZmE5ZGQzOTZiZDc1ZmQ0ODFmZjNjYzNjNmQ2Zjk1NGI1Njk3YzYwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GfUN36DZ2xrVAGfMIlz4xk4sEyN6-5hWKQFfPBhDoQU)

I've tried that with the eyedropper. It won't work. You can't click anything after that. Like if the popup was invisible.

**Comment by daveox** [comment]
> `redecanais.africa##body > .overlay` @Alex-302

I've tried that with the eyedropper. It won't work. You can't click anything after that. Like if the popup was invisible.

**Comment by daveox** [comment]
> annoyance, needing a `set-cookie` filter
> 
> ```
> redecanais.africa##+js(set-cookie, modalVisited, true)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/10303732/369381205-f00de1e8-a5fa-4702-8f16-81ec1ee92392.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDM1NTQsIm5iZiI6MTcyNjkwMzI1NCwicGF0aCI6Ii8xMDMwMzczMi8zNjkzODEyMDUtZjAwZGUxZTgtYTVmYS00NzAyLThmMTYtODFlYzFlZTkyMzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA3MjA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTcwYzI5NGM0MWY1NjA5ZjRmOGYyZWU3NDdmMDcwMGEyZjBkNTMwMjY4OTY0MzQ5MzczMTM4YzFjNWNlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5EFJiMDhZWdErE3LGU-IgkVN09yGrf4uXRHMaYn-Ngo)

Thanks. It solves that. ;)

Where do I find where to look for this kind of script? The inspect page? Ignore my question if there's no simple/short answer to this.

**Comment by mapx-** [comment]
- about this scriptlet: https://github.com/gorhill/uBlock/wiki/Resources-Library#set-cookiejs-
- to see the `modalVisited` cookie => f12 in your browser => `application` tab => `storage` => `Cookies`

**Comment by mapx-** [comment]
@daveox enable `uBlock filters – Annoyances`

**Comment by daveox** [comment]
Oh, mapx (sorry I don't know to 'quote' you),  just to let you know, since that filter may be in some lists, they change their domain from time to time. Right now, the 'africa' domain and two other ones (.dev and .mov), doesn't work anymore. Actually, there's another 'hidden' domain. 

They do that to keep the site 'alive', I guess, which kind is the reason behind the message in the ovelay/popup.

**Comment by daveox** [comment]
> * about this scriptlet: https://github.com/gorhill/uBlock/wiki/Resources-Library#set-cookiejs-
> * to see the `modalVisited` cookie => press f12 key => `application` tab => `storage` => `Cookies`

Thanks, once again.

**Comment by mapx-** [comment]
updated => it will work for any `redecanais.*` (now `redecanais.ec`))

**Comment by daveox** [comment]
> updated => it will work for any `redecanais.*` (now `redecanais.ec`)

They are also using .ac and .tw domains now.

Oh, there's  also the "redecanaistv" with the same overlay and domains.  

The other 'hidden one" I can't open right now.

Is there a way to send you the ''hidden'' URL in private? Maybe you can find something about it. 

Maybe 1 year ago, I could not access any of the domanis I knew they had at the time, so the only I knew was to use this ''hidden'' url.

**Comment by mapx-** [comment]
I added `redecanaistv.*` too

for ''hidden'' url => send it to `axis.trivia@gmail.com`

**Comment by daveox** [comment]
> I added `redecanaistv.*` too
> 
> for ''hidden'' url => send it to `axis.trivia@gmail.com`

Ok. I've just sent you an email.

**Comment by mapx-** [comment]
as discussed, I'll remove the filter from annoyances list (it could result useful for some users)
