### ISSUE TITLE
imgur.com: ads

### ISSUE THREAD

**Issue by dan96kid** [uBlockOrigin/uAssets#25376]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://imgur.com/`

### Category

ads

### Description

Transformers One ads on Imgur are getting past uBlock Origin

### Other extensions used

- BlockTube
- DownThemAll!
- Firefox Multi-Account Containers
- Reddit Enhancement Suite
- Return YouTube Dislikes
- Simple Translate
- Stylus
- Tampermonkey
- TTV LOL PRO
- uBlacklist
- YouTube Search Fixer
- Youtube-shorts block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/fd668e62-cf36-4476-ac1c-5ef8e843ff02)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150131
 cosmetic: 48473
 scriptlet: 20893
 html: 1981
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/Craftplacer/04089c2c666c89e10818124c92d9c65b/raw/FuckFandom.txt: 18-0, now
 default:
  user-filters: 2-0, never
  ublock-filters: 40493-139, 1m Δ
  ublock-badware: 11273-6, 1m Δ
  ublock-privacy: 1179-22, 1m Δ
  ublock-unbreak: 2523-1, 1m Δ
  ublock-quick-fixes: 131-4, 1m Δ
  easylist: 85363-186, 1m Δ
  easyprivacy: 53075-62, 1m Δ
  urlhaus-1: 25435-0, now
  plowe-0: 3550-995, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 117 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  assemblyexchange.com: 2
  btloader.com: 2
  ccgateway.net: 1
  d3c8j8snkzfr1n.cloudfront.net: 2
  google-analytics.com: 1
  googletagmanager.com: 2
  imgur.map.fastly.net: 1
  outbrain.com: 1
  sascdn.com: 3
  sentry.io: 3
  stretchsquirrel.com: 1
 extended:
  ##.BannerAd-cont
  ##+js(set-constant, ADBLOCKED, false)
  ##+js(set-cookie, WHITELISTED_CLOSED, 1)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/22684
