### ISSUE TITLE
cardiagn.com: detection

### ISSUE THREAD

**Issue by sppmasterspp** [uBlockOrigin/uAssets#25375]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cardiagn.com/2015-dodge-charger-ewd-body-control-modules-circuit/`

### Category

detection

### Description

Site detects usage of adblock software and doesn't display the content.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/6c373ba9-4fc9-433d-8424-4705a3a30a33)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 196725
 cosmetic: 220325
 scriptlet: 55004
 html: 0
listset (total-discarded, last-updated):
 added:
  BGR-0: 1040-1, now
  RUS-0: 40710-155, now
  adguard-cookies: 31908-76, now
  adguard-generic: 83980-6407, now
  adguard-other-annoyances: 14518-149, now
  adguard-popup-overlays: 27961-1552, now
  curben-phishing: 595-0, now
  easylist-annoyances: 4786-15, now
  fanboy-cookiemonster: 52134-4074, now
  ublock-annoyances: 5970-19, now
 default:
  user-filters: 0-0, never
  easylist: 85363-668, now
  easyprivacy: 53075-676, now
  plowe-0: 3550-0, now
  ublock-badware: 11271-7, now
  ublock-filters: 40224-617, now
  ublock-privacy: 1190-22, now
  ublock-quick-fixes: 148-0, now
  ublock-unbreak: 2464-3, now
  urlhaus-1: 25925-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 963 ms (selfie)
 maxAssetCacheWait: 304 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  jsdelivr.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The site is unstable for me. Even when I don't use any extensions, it can also return detection

![image](https://github.com/user-attachments/assets/90df9a77-1813-4fa6-91c2-8c067a11aa6d)

It's random. Refreshing a few times can show content again.
