### ISSUE TITLE
wsj.com: breakage

### ISSUE THREAD

**Issue by jleider** [uBlockOrigin/uAssets#25371]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wsj.com/economy/central-banking/big-rate-cut-forces-fed-to-contend-with-new-obstacles-0bc63c6a?mod=hp_lead_pos7`

### Category

breakage

### Description

The video player fails to load or takes a very long time (60+ seconds) to load when uBO is enabled. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 152534
 cosmetic: 94317
 scriptlet: 28364
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52132-126, now
  ublock-cookies-easylist: 1757-13, now
  ublock-quick-fixes: 147-0, 30m Δ
 default:
  user-filters: 0-0, never
  easylist: 85351-474, 30m Δ
  easyprivacy: 53074-694, 30m Δ
  plowe-0: 3550-0, now
  ublock-badware: 11271-6, 30m Δ
  ublock-filters: 40222-382, 30m Δ
  ublock-privacy: 1190-22, 30m Δ
  ublock-unbreak: 2464-2, 30m Δ
  urlhaus-1: 25925-0, 1h.30m
filterset (user): [empty]
trustedset:
 added: [array of 78 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 118 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9511
 network:
  wsj.com: 1
  adsafeprotected.com: 9501
  amazon-adsystem.com: 1
  aswpsdkus.com: 1
  cxense.com: 1
  doubleclick.net: 1
  imasdk.googleapis.com: 1
  moatads.com: 1
  newrelic.com: 2
  privacy-mgmt.com: 1
 extended:
  ##.uds-ad-container
  ##.adWrapper
  ##.staticAd
  #@##footer-ads
```
</details>

**Comment by chkbm** [comment]
I am having the same issue

**Comment by stephenhawk8054** [comment]
Looks like the link needs an account? Do you know any free links that have the same issue?

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||static.adsafeprotected.com/vans-adapter-google-ima.js^$script,domain=wsj.com
@@||static.adsafeprotected.com/iasPET.$script,domain=wsj.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by chrmod** [comment]
On the Ghostery side we've already shipped a fix https://github.com/ghostery/broken-page-reports/commit/9f85ef72171a7d01e2404a3eeda6d4aebac9a197

**Comment by jleider** [comment]
I can confirm this is working again. Thank you!
