### ISSUE TITLE
netflix.com: ads

### ISSUE THREAD

**Issue by bburns123** [uBlockOrigin/uAssets#25377]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.netflix.com/watch/81682971?trackId=253448517`

### Category

ads

### Description

Seems like Netflix's new ad plan that was forced on us is displaying ads through ublock 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0d6864d4-5e1c-4c70-b7a3-52932b48ebba)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150130
 cosmetic: 48455
 scriptlet: 20893
 html: 1981
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40493-138, 54m Δ
  ublock-badware: 11273-6, 54m Δ
  ublock-privacy: 1179-22, 54m Δ
  ublock-unbreak: 2523-1, 54m Δ
  ublock-quick-fixes: 131-4, 54m Δ
  easylist: 85363-186, 54m Δ
  easyprivacy: 53075-62, 54m Δ
  urlhaus-1: 25435-0, now
  plowe-0: 3550-995, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 214 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 75
 network:
  netflix.com: 74
  bing.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/24914#issuecomment-2290093934
