### ISSUE TITLE
gamingonlinux.com: breakage

### ISSUE THREAD

**Issue by osoitz** [uBlockOrigin/uAssets#25388]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Context:
`https://www.gamingonlinux.com/2024/09/29-games-are-getting-delisted-from-gog/`

At the bottom of that article they say:
_PSA: If our GOG links don't open - blame your plugins. Some browser plugins at some point decided to just auto-close certain affiliate links, the same links we've used for a long time now. They used to give a message asking if you wish to proceed, now some just…don't. You should report the issue to the developer of whatever plugins you're using._

This did happen to me, when clicking the link a new tab is opened and immediately closed without warning.

- Disabling Ublock Origin for the gamingonlinux.com domain, brings back the old behaviour where, instead of just closing the window without warning, Ublock warns about the `https://track.adtraction.com` link where the original af.gog.com link redirects to.
- Copy and pasting the link in a new tab also works the same way, Ublock warns about the adtraction redirection, but does not close the window.
- Disabling EasyList also has the same effect, the af.gog.com link works, but then Ublock warns about adtraction because adtraction is in "Peter Lowe’s Ad and tracking server list". But adtracktion has been in Easylist for years, I don´t see changes

### A specific URL where the issue occurs.

```yaml
https://www.gamingonlinux.com/2024/09/29-games-are-getting-delisted-from-gog/
```

### Steps to Reproduce

1. Click on one of the affiliate links that point to af.gog.com

### Expected behavior

The link opens and Ublock warns about the redirection to `https://track.adtraction.com`

### Actual behavior

A new tab is opened and immediately closed without warning

### uBO version

1.59.0

### Browser name and version

Firefox 130.0

### Operating System and version

Fedora 40

**Comment by osoitz** [comment]
One comment about the solution. 
It seems to me, by looking at the commit, that the fix is specific for gamingonlinux.com, but it happens in other domains too, like:
https://rpgcodex.net/forums/threads/links-to-gog-embedded-with-adtraction-com.140452/

**Comment by stephenhawk8054** [comment]
Just continue reporting other sites in this thread.
