### ISSUE TITLE
duolingo.com: ads

### ISSUE THREAD

**Issue by Pretentiousness** [uBlockOrigin/uAssets#25385]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.duolingo.com/lesson`

### Category

ads

### Description

shows a video ad for duolingo super after a lession. happens occasionally not every time. disabling other filters lists doesnt help

### Other extensions used

decentraleyes , sponsorblock , YT dislike, enhancer for YT, bitwarden, simple translate, IDM extension , copy plain text

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/25f5d342-9c07-42fa-9785-46d86c748caa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 375505
 cosmetic: 167560
 scriptlet: 34328
 html: 2250
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1098-2, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 102961-6, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2673-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 338-2, now
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/antimalware.txt: 42789-2445, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2126-18, now
  adguard-spyware-url: 1709-244, now
  adguard-spyware: 80542-580, now
  block-lan: 62-0, now
  curben-phishing: 566-2, now
  adguard-cookies: 31927-60, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 29-0, never
  ublock-filters: 40517-138, now
  ublock-badware: 11273-1048, now
  ublock-privacy: 1229-73, now
  ublock-unbreak: 2523-1, now
  ublock-quick-fixes: 137-4, now
  easylist: 85369-676, now
  easyprivacy: 53075-24837, now
  urlhaus-1: 25605-15, now
  plowe-0: 3547-1430, now
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 466 ms (selfie)
 maxAssetCacheWait: 192 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  duolingo.com: 1
  cookielaw.org: 1
  google.com: 1
  sentry.io: 2
 extended:
  ##.grecaptcha-badge
  ##.grecaptcha-badge[data-style]
  ##+js(no-xhr-if, excess.duolingo.com/batch)
```
</details>

**Comment by D4niloMR** [comment]
uBO doesn't address self-promotion.
