### ISSUE TITLE
pllsfored.com: ads

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25389]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pllsfored.com/`

### Category

ads

### Description

i see bet ads. its annoying

### Other extensions used

decentraleyes
fastforward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240921_154955](https://github.com/user-attachments/assets/c5246eab-c3e3-45f6-9dc1-76f6fc1f14c6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 130
filterset (summary):
 network: 230573
 cosmetic: 191982
 scriptlet: 39670
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1709-125, now
  adguard-spyware: 80548-25554, now
  block-lan: 62-0, now
  curben-phishing: 529-0, now
  adguard-cookies: 31932-100, now
  ublock-cookies-adguard: 1794-9, now
  fanboy-cookiemonster: 52137-4085, now
  ublock-cookies-easylist: 1794-1794, now
  adguard-popup-overlays: 27979-959, now
  adguard-mobile-app-banners: 5466-1132, now
  adguard-other-annoyances: 14529-375, now
  adguard-widgets: 2665-47, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40773-697, 5m Δ
  ublock-badware: 11267-9, 5m Δ
  ublock-privacy: 1248-22, 5m Δ
  ublock-unbreak: 2468-3, 5m Δ
  ublock-quick-fixes: 158-0, 5m Δ
  adguard-mobile: 9813-11, now
  easylist: 85381-886, 5m Δ
  easyprivacy: 53083-854, 5m Δ
  urlhaus-1: 25550-0, now
  plowe-0: 3547-83, now
  TUR-0: 11367-26, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2434 ms (selfie)
 maxAssetCacheWait: 335 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  pllsfored.com: 1
  duckduckgo.com: 3
  googletagmanager.com: 1
  waust.at: 1
 extended:
  ##body > div[style^="bottom:0;height:50px;left:0;position:fixed;…
  ##.topReklam
  ##+js(set-constant, window.config.adv, {})
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25391#issuecomment-2365178919
