### ISSUE TITLE
bollywoodchamp.in: detection

### ISSUE THREAD

**Issue by vrop-zo** [uBlockOrigin/uAssets#25386]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bollywoodchamp.in/`

### Category

detection

### Description

The website is detecting the ad blocker.

### Other extensions used

Not used any other extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 130
filterset (summary):
 network: 151486
 cosmetic: 57048
 scriptlet: 21027
 html: 1991
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 41027-223, 12m Δ
  ublock-badware: 11267-7, 12m Δ
  ublock-privacy: 1230-22, 12m Δ
  ublock-unbreak: 2526-3, 12m Δ
  ublock-quick-fixes: 137-4, 12m Δ
  adguard-mobile: 9813-11, 9m
  easylist: 85381-259, 12m Δ
  easyprivacy: 53075-71, 12m Δ
  urlhaus-1: 25365-0, 12m
  plowe-0: 3547-1069, 9m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 590 ms (selfie)
 maxAssetCacheWait: 236 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 7
  googlesyndication.com: 2
  homeloanis.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link?

**Comment by vrop-zo** [comment]
Yes
It's a shortener link

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

Comment original link in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361 . Don't open new issues about these sites.

**Comment by vrop-zo** [comment]
The shortener link just redirected me to this link 
https://get2short.com/PML_D39vDKXs6l13VhaRt9FIJVinA1
The above link is the shortener link
