### ISSUE TITLE
skyscanner.dk: breakage

### ISSUE THREAD

**Issue by svendsvin** [uBlockOrigin/uAssets#25383]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.skyscanner.dk/transport/flights/bll/vie/241207/241215/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&rtn=1`

### Category

breakage

### Description

Can't scroll

### Other extensions used

i still dont care about cookie (disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 140830
 cosmetic: 82971
 scriptlet: 45245
 html: 2241
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  urlhaus-1: null
 added:
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2126-19, now
  adguard-generic: 84021-823, now
  adguard-spyware-url: 1713-126, now
  adguard-spyware: 80541-1499, now
  adguard-popup-overlays: 27972-207, now
  ublock-annoyances: 5911-135, 1m Δ
  dpollock-0: 11697-166, now
  NOR-0: 4735-387, 1m
  THA-0: 1485-15, now
 default:
  user-filters: 65-0, never
  ublock-filters: 40502-3806, 1m Δ
  ublock-badware: 11273-125, 1m Δ
  ublock-privacy: 1179-23, 1m Δ
  ublock-unbreak: 2523-78, 1m Δ
  ublock-quick-fixes: 134-5, 1m Δ
  plowe-0: 3547-615, now
filterset (user): [array of 65 redacted]
trustedset:
 added: [array of 61 redacted]
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 170 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 120
 autoUpdateDelayAfterLaunch: 180
 autoUpdatePeriod: 7
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 644 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  skyscanner.dk: 2
  google-analytics.com: 1
  newrelic.com: 2
```
</details>

**Comment by mapx-** [comment]
You have a heavily modified setup:

- reset uBO to defaults
- do not add / enable other lists
- test again
- then you could add 1 by 1 other lists and see which one is breaking the page (let us know which one)

**Comment by svendsvin** [comment]
Actually it was not my uBo settings, but my extension, I still don't care about cookies, that was the problem.
________________________________
Fra: mapx ***@***.***>
Sendt: 20. september 2024 15:22
Til: uBlockOrigin/uAssets ***@***.***>
Cc: svendsvin ***@***.***>; Author ***@***.***>
Emne: Re: [uBlockOrigin/uAssets] skyscanner.dk: breakage (Issue #25383)


You have a heavily modified setup:

  *   reset uBO to defaults
  *   do not add / enable other lists
  *   test again
  *   then you could add 1 by 1 other lists and see which one is breaking the page (let us know which one)
