### ISSUE TITLE
dizipal739.com: ads

### ISSUE THREAD

**Issue by parminn** [uBlockOrigin/uAssets#25384]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dizipal739.com/`

### Category

ads

### Description

this site changes domains in every month usually and after like 20 change ads are popping up again.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 151729
 cosmetic: 56953
 scriptlet: 23875
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40233-282, 31m Δ
  ublock-badware: 11271-6, 31m Δ
  ublock-privacy: 1192-22, 31m Δ
  ublock-unbreak: 2464-0, 31m Δ
  ublock-quick-fixes: 153-0, 31m Δ
  easylist: 85363-580, 31m Δ
  easyprivacy: 53075-651, 31m Δ
  urlhaus-1: 25605-0, now
  plowe-0: 3547-0, now
  TUR-0: 11359-15, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 777 ms
 maxAssetCacheWait: 169 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  dizipal739.com: 26
  googletagmanager.com: 1
  waust.at: 1
 extended:
  ##.g-title > div.containerAds
  ###bottomAd
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
> this site changes domains in every month usually and after like 20 change ads are popping up again.

This is an open issue: https://github.com/AdguardTeam/FiltersCompiler/issues/204

**Comment by stephenhawk8054** [comment]
@Yuki2718 Hmm... I think we can test generic filters like these, no need for regex

```adb
##div.bb[style="margin:auto;"] > a[target="_blank"][rel="nofollow"] > img.web[src^="/reklamlar/"]
##div.bb[style="margin:auto;"] > a[target="_blank"][rel="nofollow"] > img.mobile[src^="/reklamlar/"]
```

**Comment by Yuki2718** [comment]
I don't see unblocked ads with Turkish filter enabled, and as far as possible they should be addressed in regional filter.

**Comment by stephenhawk8054** [comment]
I mean, to address future changing domains without waiting for the list adding the new domain. That's what the regex filters in both lists are doing?

**Comment by Yuki2718** [comment]
Isn't `/reklamlar/*` in Turkish list enough for them?

**Comment by stephenhawk8054** [comment]
Yes, the original intention is covering both network and cosmetic in case they change 1 of them.

If you think network is enough, then it's fine to remove our section.

**Comment by Yuki2718** [comment]
> in case they change 1 of them.

For that matter `[src^="/reklamlar/"]` should be replaced by something. But if you think of a good cosmetic filters, tell me and I can add to Turkish list.

**Comment by stephenhawk8054** [comment]
Yeah the `[src^="/reklamlar/"]` can be removed. I just did it due to habits.

**Comment by punisher018** [comment]
@stephenhawk8054 `/^dizipal\d+\.com$/##.pre-player` 

this filter breaks video players on dizipal846.com
