### ISSUE TITLE
selcuksports.me: ads

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25390]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://selcuksports.me/`

### Category

ads

### Description

i see banners without ads. its annoying. "Reklam Alanı"

### Other extensions used

decentraleyes
fastforward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240921_155301](https://github.com/user-attachments/assets/6c4d173d-c163-4299-9301-ce2ca8665f89)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium Mobile: 130
filterset (summary):
 network: 230573
 cosmetic: 191982
 scriptlet: 39670
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1709-125, 2m
  adguard-spyware: 80548-25554, 2m
  block-lan: 62-0, 2m
  curben-phishing: 529-0, 2m
  adguard-cookies: 31932-100, 2m
  ublock-cookies-adguard: 1794-9, 2m
  fanboy-cookiemonster: 52137-4085, 2m
  ublock-cookies-easylist: 1794-1794, 2m
  adguard-popup-overlays: 27979-959, 2m
  adguard-mobile-app-banners: 5466-1132, 2m
  adguard-other-annoyances: 14529-375, 2m
  adguard-widgets: 2665-47, 2m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40773-697, 7m Δ
  ublock-badware: 11267-9, 7m Δ
  ublock-privacy: 1248-22, 7m Δ
  ublock-unbreak: 2468-3, 7m Δ
  ublock-quick-fixes: 158-0, 7m Δ
  adguard-mobile: 9813-11, 2m
  easylist: 85381-886, 7m Δ
  easyprivacy: 53083-854, 7m Δ
  urlhaus-1: 25550-0, 2m
  plowe-0: 3547-83, 3m
  TUR-0: 11367-26, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2434 ms (selfie)
 maxAssetCacheWait: 335 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  duckduckgo.com: 5
  twitter.com: 1
  waust.at: 1
 extended:
  ##.topReklam
  ##html:style(overflow:auto!important)
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  ##+js(set-cookie, twtr_pixel_opt_in, N)
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
  ##a[href^="https://twitter.com/intent/follow?"]
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25391#issuecomment-2365178919
