### ISSUE TITLE
tumblr.com: breakage

### ISSUE THREAD

**Issue by ellequelle** [uBlockOrigin/uAssets#25398]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tumblr.com/?redirect_to=%2F&source=explore_floating_sign_up`

### Category

breakage

### Description

The login screen doesn't work unless I disable uBlock.

### Other extensions used

I have EFF's privacy badger installed but disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 191881
 cosmetic: 252908
 scriptlet: 53540
 html: 2250
listset (total-discarded, last-updated):
 added:
  adguard-generic: 83959-4185, now
  curben-phishing: 529-2, now
  adguard-social: 23052-47, now
  adguard-cookies: 31932-53, now
  adguard-popup-overlays: 27979-932, now
  adguard-mobile-app-banners: 5466-27, now
  adguard-other-annoyances: 14529-411, now
  adguard-widgets: 2665-15, now
  easylist-annoyances: 4788-328, now
  easylist-chat: 215-18, now
  fanboy-cookiemonster: 52139-4042, now
  easylist-newsletters: 7877-593, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40552-138, 1h.5m Δ
  ublock-badware: 11275-6, 1h.5m Δ
  ublock-privacy: 1234-22, 1h.5m Δ
  ublock-unbreak: 2529-1, 1h.5m Δ
  ublock-quick-fixes: 138-4, 1h.5m Δ
  easylist: 85389-2080, 1h.5m Δ
  easyprivacy: 53084-151, 1h.5m Δ
  urlhaus-1: 25550-0, now
  plowe-0: 3547-1378, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 12311 ms (selfie)
 maxAssetCacheWait: 887 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  tumblr.com: 11
  doubleclick.net: 1
  pubmatic.com: 1
  sentry.io: 2
  wp.com: 4
 extended:
  ##.Yc2Sp h1, .Yc2Sp a:style(font-size: 0 !important;)
  ##body:style(overflow: auto !important;)
  #@#.Qrht9
  #@#.Yc2Sp
  ##+js(json-prune-fetch-response, response.timeline.elements.[-].…
  ##+js(no-setTimeout-if, adBlockEnabled, 3000)
  ##+js(set-cookie-reload, logged_in, 1)
  ##+js(no-setTimeout-if, Premium)
  ##+js(set-cookie, logged_in, 1, , reload, 1)
  ##+js(trusted-click-element, .cmp__dialog-footer-buttons > .is-s…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@ellequelle 

add

`||assets.tumblr.com/pop/js/modern/async-login-wall-$badfilter`

@Alex-302 @Yuki2718 
`AdGuard – Popup Overlays` issue
