### ISSUE TITLE
forums.golfwrx.com: ads

### ISSUE THREAD

**Issue by leezer99** [uBlockOrigin/uAssets#25392]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://forums.golfwrx.com/forum/84-juniorscollege-golf-talk/`

### Category

ads

### Description

Big ol' youtube ad in the middle of the page.
![Screenshot 2024-09-21 065743](https://github.com/user-attachments/assets/d2c69236-070b-4428-9e58-677a19eadd6d)

### Other extensions used

Big ol' ad in the middle of the page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/bb004516-4bb4-4ba1-a7c0-965ed9ba86f6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 150293
 cosmetic: 48470
 scriptlet: 22538
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40265-143, 45m Δ
  ublock-badware: 11273-6, 45m Δ
  ublock-privacy: 1247-22, 45m Δ
  ublock-unbreak: 2465-0, 45m Δ
  ublock-quick-fixes: 158-0, 45m Δ
  easylist: 85381-575, 45m Δ
  easyprivacy: 53083-773, 45m Δ
  urlhaus-1: 25550-0, now
  plowe-0: 3547-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 218 ms (selfie)
 maxAssetCacheWait: 34 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  cloudflareinsights.com: 1
  dn0qt3r0xannq.cloudfront.net: 3
  doubleclick.net: 2
  google.com: 4
  googletagmanager.com: 1
  googletagservices.com: 1
  quantserve.com: 1
  youtube.com: 14
 extended:
  ##.ad-wrapper
  ###pb-slot-top
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
forums.golfwrx.com##ol.cTopicList > li.ipsDataItem:not([data-rowid])
```

@ryanbr
