### ISSUE TITLE
inmanga.com: detection

### ISSUE THREAD

**Issue by KNDaniel** [uBlockOrigin/uAssets#25396]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://inmanga.com/lock/adblock`

### Category

detection

### Description

The site detect ad block

### Other extensions used

Tapermonkey and Zotero integration.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagen](https://github.com/user-attachments/assets/713a77e2-a2cb-441e-978b-987f15b569ba)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 158572
 cosmetic: 133444
 scriptlet: 31414
 html: 2249
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1709-125, never
  fanboy-cookiemonster: 52139-174, now
  ublock-cookies-easylist: 1756-13, now
  fanboy-social: 17095-10, now
  easylist-annoyances: 4787-45, now
  easylist-chat: 215-0, now
  easylist-newsletters: 7869-37, now
  easylist-notifications: 3441-164, now
  ublock-annoyances: 5912-82, now
 default:
  user-filters: 0-0, never
  ublock-filters: 40535-170, now
  ublock-badware: 11275-6, never
  ublock-privacy: 1151-28, now
  ublock-unbreak: 2529-22, never
  ublock-quick-fixes: 138-4, now Δ
  easylist: 85384-204, now
  easyprivacy: 53084-2, now
  urlhaus-1: 25550-0, now
  plowe-0: 3547-995, now
  spa-0: 4076-27, now
  spa-1: 6006-257, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1672 ms
 maxAssetCacheWait: 768 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  inmanga.com: 3
  cloudflareinsights.com: 2
  gnashesfanfare.com: 1
  google-analytics.com: 2
  possibilityfoundationwallpaper.com: 1
 extended:
  ##+js(abort-current-script, setTimeout, manageAntiBlock)
```
</details>

**Comment by D4niloMR** [comment]
Caused by `||inmanga.com/ads/` in EasyList Spanish.
