### ISSUE TITLE
[nsfw] androidadult.com: detection

### ISSUE THREAD

**Issue by UmerArshadAbbasi** [uBlockOrigin/uAssets#25394]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://androidadult.com/?s=Our+red+string+&id=145781&post_type=post`

### Category

detection

### Description

It just shows ad blocker detected every three to 4 second

### Other extensions used

Dark mode

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 129
filterset (summary):
 network: 151381
 cosmetic: 57057
 scriptlet: 21045
 html: 1991
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41046-139, 1m
  ublock-badware: 11269-6, now
  ublock-privacy: 1235-22, now
  ublock-unbreak: 2532-1, now
  ublock-quick-fixes: 142-4, 1m
  adguard-mobile: 9813-98, 1m
  easylist: 85381-259, 1m
  easyprivacy: 53075-71, now
  urlhaus-1: 25255-0, 1m
  plowe-0: 3543-1068, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 501 ms (selfie)
 maxAssetCacheWait: 154 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  androidadult.com: 1
  acscdn.com: 1
  adtng.com: 1
  agqoshfujku.com: 1
  cldup.com: 8
  eroadvertising.com: 1
  exosrv.com: 3
  googletagmanager.com: 1
  nrs6ffl9w.com: 1
  runative-syndicate.com: 2
 extended:
  ##a[href^="https://join.dreamsexworld.com/"]
  ##a[href^="https://join.sexworld3d.com/track/"]
  ##a[href^="https://join.virtuallust3d.com/"]
  ##a[href^="https://www.nutaku.net/signup/landing/"]
  ##+js(noeval-if, /chp_?ad/)
  ##+js(set-constant, chp_adblock_browser, noopFunc)
```
</details>

**Comment by zenstorage** [comment]
Try:
```adb
androidadult.com##+js(acs, setTimeout, ads-blocked)
```

**Comment by rakleed** [comment]
Ads on `https://androidadult.com/latest-games/`.

Timer on `https://androidadult.com/summertime-saga-apk/` (click `Download Summertime Saga 21.0.0 wip.5605 Android`, then click `DOWNLOAD APK (1.13GB)`).
 
<details><summary>Screenshots:</summary>

Ads:
- https://cln.sh/JQbxtjzzK1FfmbFH12Qm
- https://cln.sh/JdQL6Bptj4ZJRrmQpWhj

Timer:
- https://cln.sh/W4csXMvHpv33rCdv6tsv

</details> 

<details><summary>Details</summary>

```yaml
uBlock Origin: 1.62.0
Chromium: 134
filterset (summary):
 network: 174222
 cosmetic: 223092
 scriptlet: 42851
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 2023-136, 5m
  adguard-cookies: 33641-110, 5m
  ublock-cookies-adguard: 3753-21, 5m
  fanboy-cookiemonster: 44543-3725, 5m
  ublock-cookies-easylist: 3753-3753, 5m
  adguard-social: 23772-825, 5m
  fanboy-social: 16645-2, 5m
  adguard-popup-overlays: 28955-3132, 5m
  adguard-mobile-app-banners: 5932-1136, 5m
  adguard-other-annoyances: 14747-716, 5m
  adguard-widgets: 2914-23, 5m
  easylist-annoyances: 4794-145, 5m
  [6 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40576-116, 5m
  ublock-badware: 11939-7, 5m
  ublock-privacy: 2755-34, 5m
  ublock-unbreak: 2572-6, 5m
  ublock-quick-fixes: 246-8, 1h.23m Δ
  easylist: 69846-639, 5m
  easyprivacy: 53413-972, 5m
  urlhaus-1: 25105-0, 5m
  plowe-0: 3464-0, 5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 367 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  androidadult.com: 1
  acscdn.com: 1
  adtng.com: 2
  diagramjawlineunhappy.com: 1
  googlesyndication.com: 1
  lectureolympics.com: 1
  magsrv.com: 3
  superonclick.com: 2
 extended:
  ###ads-blocked
  ##.headerlinks
  ##.navitem.color-3
  ##a[href^="https://join.dreamsexworld.com/"]
  ##a[href^="https://www.nutaku.net/signup/landing/"]
  ##+js(remove-node-text, script, /h=decodeURIComponent|popundersP…
  ##+js(trusted-suppress-native-method, eval, '"/chp_?ad/"')
  ##+js(set-constant, chp_adblock_browser, noopFunc)
  ##+js(addEventListener-defuser, DOMContentLoaded, .clientHeight)
  ##+js(prevent-setTimeout, ads)
  ##+js(remove-node-text, script, ads-blocked)
``` 

</details>

**Comment by rakleed** [comment]
@stephenhawk8054 could you please also add auto-click on "Skip Ad" so I automatically was redirected to the actual download link?

<details><summary>Screenshot:</summary>

![Image](https://github.com/user-attachments/assets/b038e17f-1436-4c7d-b50e-b77c2db7afff)

</details>

And it seems like there is another domain with a timer: `https://adultcomixxx.com/`(you need to open a few links for downloading, since it changes each time)

**Comment by stephenhawk8054** [comment]
We don't use `trusted-click` on ad-riddled redirection links.
