### ISSUE TITLE
ihg.com: breakage

### ISSUE THREAD

**Issue by EWSupport** [uBlockOrigin/uAssets#25393]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ihg.com/rewardsclub/us/en/sign-in?fwdest=%2Frewardsclub%2Fus%2Fen%2Faccount-mgmt%2Fhome&cm_mmc=EMAIL-_-IHGRC-_-AMER-_-en-_-PTR-_-HCV_1413351-_-SENDURLID5561698-_-256266&mi_u=117053536&mi_ecmp=256266`

### Category

breakage

### Description

Site does not display login (username password) when extension is enabled. Disabling extension allows username and password fields to show up.

### Other extensions used

Privacy Badger
Privacy Redirect
Duck Duck Go Privacy Essentials

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 149984
 cosmetic: 48467
 scriptlet: 20970
 html: 1990
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40537-138, 1h.52m Δ
  ublock-badware: 11275-6, 1h.52m Δ
  ublock-privacy: 1234-22, 1h.52m Δ
  ublock-unbreak: 2524-1, 1h.52m Δ
  ublock-quick-fixes: 138-4, 1h.52m Δ
  easylist: 85381-560, 1h.52m Δ
  easyprivacy: 53083-683, 1h.52m Δ
  urlhaus-1: 25255-0, 52m
  plowe-0: 3547-0, now
filterset (user): [empty]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 577 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@EWSupport 

add

`@@*$frame,domain=ihg.com,1p`
or
`&mi_ecmp=$badfilter`

@ryanbr EP issue
