### ISSUE TITLE
auva.at: breakage

### ISSUE THREAD

**Issue by Stofferl** [uBlockOrigin/uAssets#25407]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://auva.at/unfall-melden/`

### Category

breakage

### Description

Website form to be filled out does not work

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 152640
 cosmetic: 53604
 scriptlet: 22551
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7526-1, now
  easylist: 85380-483, 8m Δ
  easyprivacy: 53083-655, 8m Δ
  plowe-0: 3550-0, now
  ublock-badware: 11266-6, 16m Δ
  ublock-filters: 40280-389, 16m Δ
  ublock-privacy: 1247-22, 16m Δ
  ublock-quick-fixes: 145-0, 16m Δ
  ublock-unbreak: 2471-2, 16m Δ
  urlhaus-1: 25560-0, now
filterset (user): [empty]
trustedset:
 added: [array of 18 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 324 ms
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  sozialversicherung.gv.at: 1
```
</details>

**Comment by mapx-** [comment]
add

`&event=view&$badfilter`

@ryanbr
