### ISSUE TITLE
dictionary.com: nuisance

### ISSUE THREAD

**Issue by Doominator1** [uBlockOrigin/uAssets#25406]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dictionary.com/browse/smart`

### Category

nuisance

### Description

The word of the day video popup appears and stays in the corner of the screen when you scroll down.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1445" alt="Screenshot 2024-09-23 at 8 30 44 PM" src="https://github.com/user-attachments/assets/ce026275-7875-4fa9-95c1-089e6d8f1a48">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 126
filterset (summary):
 network: 150313
 cosmetic: 48452
 scriptlet: 22551
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 85380-576, 1h.49m Δ
  easyprivacy: 53083-647, 1h.49m Δ
  plowe-0: 3550-0, now
  ublock-badware: 11266-6, 1h.49m Δ
  ublock-filters: 40280-270, 1h.49m Δ
  ublock-privacy: 1247-22, 1h.49m Δ
  ublock-quick-fixes: 145-0, 1h.49m Δ
  ublock-unbreak: 2471-0, 1h.49m Δ
  urlhaus-1: 25560-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 130 ms (selfie)
 maxAssetCacheWait: 26 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 210
 network:
  dictionary.com: 3
  1rx.io: 2
  3lift.com: 2
  adform.net: 2
  adnxs.com: 2
  adobedtm.com: 4
  adsrvr.org: 2
  agkn.com: 2
  amazon-adsystem.com: 4
  anyclip.com: 137
  bidswitch.net: 2
  btloader.com: 1
  carambo.la: 2
  demdex.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  icanhazip.com: 2
  imasdk.googleapis.com: 12
  lijit.com: 2
  mathtag.com: 2
  media.net: 2
  onetag-sys.com: 2
  openx.net: 2
  proper.io: 1
  pubmatic.com: 2
  richaudience.com: 2
  rubiconproject.com: 2
  smartadserver.com: 2
  sonobi.com: 2
  springserve.com: 2
  tremorhub.com: 2
  yieldmo.com: 2
 extended:
  ##.SZjJlj7dd7R6mDTODwIT
  ##[class] > p:has-text(Advertisement)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
enable `AdGuard – Other Annoyances` list or `EasyList – Other Annoyances` list
