### ISSUE TITLE
eznamka.sk: breakage

### ISSUE THREAD

**Issue by jozefizso** [uBlockOrigin/uAssets#25409]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eznamka.sk/selfcare/purchase/singlepurchase/purchaseredirect/`

### Category

breakage

### Description

When buying a new highway ticket, the 4th step on the page should have the **Confirm** button available. With uBlock enabled, the button is not visible and the user cannot buy electronic ticket.

### Other extensions used

1Password
Refined GitHub

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/7ba8b047-30cc-4726-9722-cbe81b89b560">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 158716
 cosmetic: 151553
 scriptlet: 29946
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31950-41, now
  adguard-popup-overlays: 27991-713, now
  easylist-chat: 215-0, 1h.1m
  easylist-newsletters: 7879-25, now
  easylist-notifications: 3442-4, now
  fanboy-cookiemonster: 52140-4038, now
 default:
  user-filters: 2-0, never
  easylist: 85383-514, 1h.1m Δ
  easyprivacy: 53082-744, 1h.1m Δ
  plowe-0: 3550-1, now
  ublock-badware: 11271-6, 1h.1m Δ
  ublock-filters: 40277-453, 1h.1m Δ
  ublock-privacy: 1247-22, 1h.1m Δ
  ublock-quick-fixes: 146-0, 1h.1m Δ
  ublock-unbreak: 2471-0, 1h.1m Δ
  urlhaus-1: 25880-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 18 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1193 ms
 maxAssetCacheWait: 266 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.gdpr-button
  ###cookieagreed
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
add

`eznamka.sk#@#.gdpr-button`

@ryanbr `EasyList – Cookie Notices` issue
