### ISSUE TITLE
[nsfw] chatgpt.com: nuisance

### ISSUE THREAD

**Issue by sigmaguy25** [uBlockOrigin/uAssets#25404]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://chatgpt.com/`

### Category

nuisance

### Description

when your free trial runs out on the GPT plus version it has a text saying Wait to get this model back

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150407
 cosmetic: 48453
 scriptlet: 20986
 html: 1990
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 40555-138, 24m Δ
  ublock-badware: 11268-6, 24m Δ
  ublock-privacy: 1234-22, 24m Δ
  ublock-unbreak: 2529-1, 24m Δ
  ublock-quick-fixes: 140-4, 24m Δ
  easylist: 85380-186, 24m Δ
  easyprivacy: 53083-62, 24m Δ
  urlhaus-1: 25655-0, now
  plowe-0: 3550-997, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1125 ms
 maxAssetCacheWait: 808 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  chatgpt.com: 23
```
</details>

**Comment by mapx-** [comment]
> it has a text saying Wait to get this model back

it seems to me this could be a helpful warning for the users

If you disagree report it at easylist repository (for annoyances lists)
