### ISSUE TITLE
sporza.be: breakage

### ISSUE THREAD

**Issue by SeBr28** [uBlockOrigin/uAssets#25401]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sporza.be/nl/matches/formule-1/2024-02/grote-prijs-van-singapore-live-ongenaakbaar-lando-norris-demonstreert-met-zijn-mclaren-in-singapore~1707749665394/`

### Category

breakage

### Description

twitter posts are not shown. (embedded i think) When iI turn off ublockOrigin it works immidiately.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-09-22_15-05-14](https://github.com/user-attachments/assets/59733225-ac1a-4d9c-bfb8-0dc98fc4b792)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 150953
 cosmetic: 50209
 scriptlet: 22565
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40286-270, 2m Δ
  ublock-badware: 11260-6, 2m Δ
  ublock-privacy: 1247-22, 2m Δ
  ublock-unbreak: 2470-0, 2m Δ
  ublock-quick-fixes: 156-0, 2m Δ
  easylist: 85415-579, 2m Δ
  easyprivacy: 53084-648, 2m Δ
  urlhaus-1: 25655-0, 2m
  plowe-0: 3548-0, now
  NLD-0: 2318-39, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 339 ms
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  adobedtm.com: 8
  clarity.ms: 1
  criteo.net: 1
  pbstck.com: 2
  qualtrics.com: 1
  sentry.io: 2
  smartocto.com: 1
  vrt.be: 3
 extended:
  ##._embedTwitter_1kngp_20
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
user-filters: 1-0, never
extended:
  ##._embedTwitter_1kngp_20
```

Check your "My filters" pane again.

**Comment by mapx-** [comment]
it's a EP issue on my end too

@SeBr28 remove that cosmetic filter and add:

`||t.vrt.be^$badfilter`

@ryanbr

**Comment by mapx-** [comment]
![image](https://github.com/user-attachments/assets/1fb17efc-47eb-452a-bf61-3e8afd7a29ac)

**Comment by mapx-** [comment]
@MasterKia I guess you should scroll down getting the twitter sections (to get those requests)

**Comment by SeBr28** [comment]
@mapx- your answer did the trick... thnx!
