### ISSUE TITLE
tiplanet.org: ads

### ISSUE THREAD

**Issue by Oqarshi** [uBlockOrigin/uAssets#25403]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tiplanet.org/forum/archives_voir.php`

### Category

ads

### Description

shows ads/website ads 

### Other extensions used

Tampermonkey, Anti-Grabify, and Return Youtube Dislikes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2](https://github.com/user-attachments/assets/44b072d1-1b88-4296-a977-324074ea4ed3)
![1](https://github.com/user-attachments/assets/2a94ad7c-7f85-4bd5-a293-226f9ddc55bd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 155725
 cosmetic: 157119
 scriptlet: 29699
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 31933-68, now
  ublock-cookies-adguard: 1756-9, now
  fanboy-cookiemonster: 52140-4013, now
  ublock-cookies-easylist: 1756-1756, now
  adguard-social: 23052-788, now
  fanboy-social: 17104-18, now
  fanboy-thirdparty_social: 68-0, now
 default:
  user-filters: 4-0, never
  ublock-filters: 40279-280, 16m Δ
  ublock-badware: 11266-6, 16m Δ
  ublock-privacy: 1247-22, 16m Δ
  ublock-unbreak: 2470-0, 16m Δ
  ublock-quick-fixes: 146-0, 16m Δ
  easylist: 85380-583, 16m Δ
  easyprivacy: 53083-651, 16m Δ
  urlhaus-1: 25655-0, now
  plowe-0: 3548-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1569 ms (selfie)
 maxAssetCacheWait: 945 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 1
  google.com: 3
  googlesyndication.com: 1
  translate.googleapis.com: 2
 extended:
  ##iframe[name="googlefcPresent"]
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ###socialWidget
```
</details>

**Comment by stephenhawk8054** [comment]
For the 1st screenshot (upper left and the banner at the bottom):

```adb
tiplanet.org###left_column > .archive:not([id])
tiplanet.org##.navbar > .inner > div:has(.sprite-jarrety)
```

I don't think the bottom left (partner websites) are ads.

---

I don't know what is the link of the 2nd screenshot.

---

cc @ryanbr

**Comment by Oqarshi** [comment]
> For the 1st screenshot (upper left and the banner at the bottom):
> 
> ```
> tiplanet.org###left_column > .archive:not([id])
> tiplanet.org##.navbar > .inner > div:has(.sprite-jarrety)
> ```
> 
> I don't think the bottom left (partner websites) are ads.
> 
> I don't know what is the link of the 2nd screenshot.
> 
> cc @ryanbr

Yep those filters fixed it! also the top left and bottom left arnt really ads sorry about that

**Comment by stephenhawk8054** [comment]
cc @smed79

**Comment by mapx-** [comment]
@Oqarshi as a french site report the issue at Liste FR repository (indicating there the filters above)
https://github.com/easylist/listefr/issues
