### ISSUE TITLE
gazzetta.gr: breakage

### ISSUE THREAD

**Issue by m33ts4k0z** [uBlockOrigin/uAssets#25402]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After some recent update (maybe on the website side), uBlock origin started blocking the comments section of that website. Disabliing UBO, the comments show again. Tested on Firefox for Android and Chrome on Windows

### A specific URL where the issue occurs.

```
https://www.gazzetta.gr/gmotion/2372937/f1-sigkapoyri-o-noris-pire-mia-epiblitiki-niki
```

### Steps to Reproduce

Just open the website. You see no comments when UBO is active. Deactivate UBO and refresh the page. After clicking the comments button, you will be scrolled down to the comments section and the comments will be visible.

### Expected behavior

The comments are visible

### Actual behavior

The comments are not visible

### uBO version

1.59.0

### Browser name and version

Firefox for android  130.0.1 and Chrome for Windows 129

### Operating System and version

Android and Windows

**Comment by mapx-** [comment]
@m33ts4k0z 

open uBO dashboard, support tab, copy and paste here the `Troubleshooting Information`

**Comment by m33ts4k0z** [comment]
Sure:

```
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 150007
 cosmetic: 48448
 scriptlet: 22550
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40280-373, 3h.55m Δ
  ublock-badware: 11266-24, 3h.55m Δ
  ublock-privacy: 1247-24, 3h.55m Δ
  ublock-unbreak: 2470-12, 3h.55m Δ
  ublock-quick-fixes: 145-2, 3h.55m Δ
  easylist: 85379-49, 3h.55m Δ
  easyprivacy: 53084-661, 3h.55m Δ
  urlhaus-1: 25255-0, 22h.6m
  plowe-0: 3547-374, 22h.6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 443 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
```
