### ISSUE TITLE
dragontea.ink: breakage

### ISSUE THREAD

**Issue by henryabram** [uBlockOrigin/uAssets#25408]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dragontea.ink/novel/im-the-male-leads-brother/`

### Category

breakage

### Description

Site text changes to gibberish
![image](https://github.com/user-attachments/assets/64defcc4-f17b-4f4c-8809-05be9245e82e)

### Other extensions used

none, I tried it with only ublock origin on my pc and mobile device

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://github.com/user-attachments/assets/36592b1b-1b35-4108-9ff5-7beec5b3b638)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 150312
 cosmetic: 48451
 scriptlet: 22551
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 85380-473, 1m Δ
  easyprivacy: 53083-628, 1m Δ
  plowe-0: 3550-0, now
  ublock-badware: 11266-6, 1m Δ
  ublock-filters: 40280-373, 1m Δ
  ublock-privacy: 1247-22, 1m Δ
  ublock-quick-fixes: 145-0, 1m Δ
  ublock-unbreak: 2471-19, 1m Δ
  urlhaus-1: 25560-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 199 ms (selfie)
 maxAssetCacheWait: 57 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  dragontea.ink: 10
  ko-fi.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/23485

**Comment by JobcenterTycoon** [comment]
@alex-302 Adguard contains a similar userscript, just the CSS path need to be updated to `https://dragontea.ink/wp-content/cache/autoptimize/css/autoptimize_5bd1c33b717b78702e18c3923e8fa4f0.css`

**Comment by Alex-302** [comment]
Thanks. As I see, Adam updated it.
