### ISSUE TITLE
nsw2u.com: detection

### ISSUE THREAD

**Issue by yttxz** [uBlockOrigin/uAssets#25413]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nsw2u.com/`

### Category

detection

### Description

Adblock detected with notice covering the webpage disabling any interaction

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 150067
 cosmetic: 48454
 scriptlet: 22565
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 40288-270, 1h.27m Δ
  ublock-badware: 11271-6, 1h.27m Δ
  ublock-privacy: 1252-22, 1h.27m Δ
  ublock-unbreak: 2471-0, 1h.27m Δ
  ublock-quick-fixes: 147-0, 1h.27m Δ
  easylist: 85425-578, 1h.27m Δ
  easyprivacy: 53082-646, 1h.27m Δ
  urlhaus-1: 25265-0, now
  plowe-0: 3552-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 315 ms (selfie)
 maxAssetCacheWait: 53 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  cloudflareinsights.com: 1
  ezodn.com: 1
  googletagmanager.com: 1
  rangauck.com: 1
  wp.com: 3
 extended:
  ##.code-block
  ##[href^="https://bit.ly/"]
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, eval, replace)
  ##+js(no-xhr-if, googlesyndication)
  ##+js(remove-node-text, script, ;}}};break;case $.)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/16904
