### ISSUE TITLE
juneauempire.com: detection

### ISSUE THREAD

**Issue by Droidem** [uBlockOrigin/uAssets#25414]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.juneauempire.com/news/cruise-industry-giving-opponents-of-ship-free-saturday-a-dominant-campaign-cash-advantage/`

### Category

nuisance

### Description

It detects the blocker and even when trying to narrow it down to what is the overlay, it still won't allow me to read it. 

### Other extensions used

BetterTTV, Bitwarden Password Manager, Checkmarks, CloudHole, ColorPick Eyedropper, Cookie Remover, Disable HTML5 Autoplay, DownThemAll!, DuckDuckGo Privacy Essentials, Enhancer for YouTube, Load Reddit Images Directly, NZB Unity, Privacy | Protect Your Payments, Reddit Enhancement Suite, Rotate Image, Sponsor Block for YouTube, TWP - Translate Web Pages, Video DownloadHelper, Violetmonkey, Wayback Machine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150065
 cosmetic: 48449
 scriptlet: 20991
 html: 1988
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40558-138, 58m Δ
  ublock-badware: 11273-6, 58m Δ
  ublock-privacy: 1234-22, 58m Δ
  ublock-unbreak: 2530-1, 58m Δ
  ublock-quick-fixes: 140-4, 58m Δ
  easylist: 85425-187, 58m Δ
  easyprivacy: 53082-62, 58m Δ
  urlhaus-1: 25265-0, now
  plowe-0: 3552-997, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms
 maxAssetCacheWait: 188 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  juneauempire.com: 3
  amazon-adsystem.com: 1
  automatad.com: 2
  doubleclick.net: 2
  facebook.net: 1
  googletagmanager.com: 4
  googletagservices.com: 1
  jsdelivr.net: 1
  jwpcdn.com: 1
  matheranalytics.com: 1
  scorecardresearch.com: 1
  sendtonews.com: 2
 extended:
  ##.ad.module
  ##.gpt-ad
  ##.OUTBRAIN
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##[class^="s2nPlayer"]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Did you open in private / incognito mode?

**Comment by Droidem** [comment]
thank you.
