### ISSUE TITLE
patreon.com: nuisance

### ISSUE THREAD

**Issue by muziqaz** [uBlockOrigin/uAssets#25418]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.patreon.com
```

### Description

Hi,
it seems Patron has implemented this very anoying pop up which suggests to download their app for better experience. This pop up is showing up every time you enter patreon. However, if you punch in www.patreon.com, this pop up does not show up, it only shows up if I am clicking on the patreon link sent to my email as notification, and I click on the link to view content, and that pop up is in my face every single time. I had a bunch of videos to catch up on patreon and this drove me nuts.
Ublock element zapper seems to not work. It just removes the object there and then, and if I launch another (or the same) patreon link, pop up still shows up.
This pop up has been introduced just recently. My patreon notification emails go to gmail, and being launched from there.
Thanks
Regards

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![patreon](https://github.com/user-attachments/assets/b2ae9023-4064-4646-a44d-745deee29450)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 249197
 cosmetic: 220575
 scriptlet: 49856
 html: 2017
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84221-4194, 11h.4m
  adguard-mobile: 9816-59, 11h.4m
  adguard-spyware-url: 1709-126, 11h.4m
  adguard-spyware: 76837-1557, 11h.5m
  block-lan: 71-0, 9d.13h.25m
  curben-phishing: 508-1, 6h.4m
  adguard-cookies: 31950-61, 11h.4m
  ublock-cookies-adguard: 1744-28, 6d.11h.24m
  fanboy-cookiemonster: 52135-4015, 3d.11h.22m
  ublock-cookies-easylist: 1744-1744, 6d.11h.24m
  adguard-popup-overlays: 27991-282, 11h.5m
  LTU-0: 1259-41, 6d.11h.24m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40559-139, 2h.4m Δ
  ublock-badware: 11273-6, 2h.4m Δ
  ublock-privacy: 1239-22, 2h.4m Δ
  ublock-unbreak: 2530-0, 2h.4m Δ
  ublock-quick-fixes: 141-4, 2h.4m Δ
  easylist: 85425-2153, 2h.4m Δ
  easyprivacy: 53082-24341, 2h.4m Δ
  urlhaus-1: 25265-0, 8h.4m
  plowe-0: 3542-1161, 8d.11h.25m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 974 ms (selfie)
 maxAssetCacheWait: 102 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  doubleclick.net: 1
  google.com: 3
  sentry.io: 4
  siftscience.com: 1
  sprig.com: 1
  transcend-cdn.com: 1
  transcend.io: 1
  youtube.com: 9
 extended:
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  #@#+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9…

```
</details>

**Comment by mapx-** [comment]
> it only shows up if I am clicking on the patreon link sent to my email as notification, and I click on the link to view content, and that pop up is in my face every single time

you should share such patreon link

**Comment by muziqaz** [comment]
> > it only shows up if I am clicking on the patreon link sent to my email as notification, and I click on the link to view content, and that pop up is in my face every single time
> 
> you should share such patreon link

Hi, thanks for the reply, however, this is a bit embarrassing, as I checked the email links closer today, and the one which I would tap or click, says `View in App`. So I guess page opened by that link had all the right to pester me with that pop up. There is a secondary link a bit lower which takes it to Patreon website and pop up does not show up. The reason I always tapped/clicked on the `View in App` link, that 99% of the time I view those videos on my smartphone, and phone has an app. This time I done it on the desktop, and clicked this particular link from the habbit without actually noticing that it actually says `View in App`.
I would like to appologise for waisting your time with this.
Sorry about that
