### ISSUE TITLE
satisfactory-calculator.com: ads

### ISSUE THREAD

**Issue by mikeloeven** [uBlockOrigin/uAssets#25412]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://satisfactory-calculator.com/`

### Category

ads

### Description

Related to Issue #24950 Do not believe this is a duplicate since the original was marked as closed / fixable with easylist in august however ads are now back on the site with easylist enabled both banner ads as well as video popups. So it looks like the website intentionally changed things to circumvent the fix.

### Other extensions used

![image](https://github.com/user-attachments/assets/94894394-53a9-44fa-8c73-4e1c71128386)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/063b12c1-c156-4b25-b4c6-728c0c900057)
![image](https://github.com/user-attachments/assets/6ba911b8-5180-403a-86c3-f3c2fe4aa093)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 21019
 cosmetic: 14156
 scriptlet: 25097
 html: 2249
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1063-0, never
  ublock-annoyances: 5911-14, 8m
 default:
  ublock-filters: 40559-138, 8m
  ublock-badware: 11273-6, 8m
  ublock-privacy: 1239-22, 8m
  ublock-unbreak: 2530-1, 8m
  ublock-quick-fixes: 141-4, 2m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 33 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 285 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  celtra.com: 1
  doubleclick.net: 9
  google-analytics.com: 1
  googlesyndication.com: 10
  googletagmanager.com: 2
  pubmatic.com: 7
  qbk1.com: 1
  smartadserver.com: 10
  stickyadstv.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Please report all ads issue in 1 thread.

**Comment by stephenhawk8054** [comment]
Also you are removing many default lists here:

```yml
 removed:
  user-filters: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
```

Reset to default settings please

> - [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
>
> - [X] I did not answer truthfully to **ALL** the above checkboxes.

Please respect the prerequisites and instructions. They are not there just for you to ignore. I see you reported ads issues in youtube thread, and it's related to you removing default filter lists.

**Comment by mikeloeven** [comment]
I was not even aware they were disabled or at least not intentionally disabled by me unsure what happened there.
