### ISSUE TITLE
zoomg.ir: breakage

### ISSUE THREAD

**Issue by AliShakiba1** [uBlockOrigin/uAssets#25415]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.zoomg.ir/`

### Category

breakage

### Description

hi
i fond bug for this addons on this website
if the addons enable site reload him self automatically every 5-8 sec

### Other extensions used

![image](https://github.com/user-attachments/assets/5bd8da2c-45ec-4771-be4b-663312fafab9)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150054
 cosmetic: 48453
 scriptlet: 20999
 html: 1990
listset (total-discarded, last-updated):
 default:
  user-filters: 9-0, never
  ublock-filters: 40559-138, 1h.26m Δ
  ublock-badware: 11273-6, 1h.26m Δ
  ublock-privacy: 1239-22, 1h.26m Δ
  ublock-unbreak: 2530-1, 1h.26m Δ
  ublock-quick-fixes: 141-4, 1h.26m Δ
  easylist: 85425-187, 1h.26m Δ
  easyprivacy: 53082-62, 1h.26m Δ
  urlhaus-1: 25255-0, never
  plowe-0: 3547-995, never
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7225 ms (selfie)
 maxAssetCacheWait: 2417 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  theforge.ir: 3
 extended:
  ##.kAyFio.container__Container-cgzihn-0 > .AlceL.flex__Flex-le1v…
```
</details>

**Comment by mapx-** [comment]
You are using adblocker ultimate and other extensions => disable all these extensions, keep only uBO, test again (without touching uBO settings).

Enable the regional list too => PersianBlocker
