### ISSUE TITLE
8042-1.portal.athenahealth.com: breakage

### ISSUE THREAD

**Issue by PortableTech** [uBlockOrigin/uAssets#25426]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://8042-1.portal.athenahealth.com/?section=welcome&CSRFPROTECT=2de7bea82e18c9e96c6b555f42c812a62dcd580186018e17a5273e7424865cd5`

### Category

breakage

### Description

Page fails to load and shows error after logging in when cdn.amplitude.com is blocked.  

### Other extensions used

Lastpass, Rakuten, Dark Reader, Capital One Savings

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/4e72b9dd-a4dc-4d7f-a85b-b4d6d82ad89b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151367
 cosmetic: 48457
 scriptlet: 20997
 html: 1993
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40574-138, 1h.48m Δ
  ublock-badware: 11323-6, 1h.48m Δ
  ublock-privacy: 1239-22, 1h.48m Δ
  ublock-unbreak: 2530-1, 1h.48m Δ
  ublock-quick-fixes: 130-4, 1h.48m Δ
  easylist: 85453-186, 1h.48m Δ
  easyprivacy: 53086-62, 1h.48m Δ
  urlhaus-1: 26490-0, now
  plowe-0: 3552-997, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 117 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 325 ms (selfie)
 maxAssetCacheWait: 223 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  amplitude.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to log in to reproduce the issue?

**Comment by mapx-** [comment]
@PortableTech could you test this filter:

`@@||api.amplitude.com^$xhr,domain=athenahealth.com`
