### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by DrgnTox** [uBlockOrigin/uAssets#25427]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 153091
 cosmetic: 55464
 scriptlet: 22568
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40303-143, 43m Δ
  ublock-badware: 11321-6, 43m Δ
  ublock-privacy: 1252-22, 43m Δ
  ublock-unbreak: 2471-0, 43m Δ
  ublock-quick-fixes: 136-0, 43m Δ
  easylist: 85453-584, 43m Δ
  easyprivacy: 53086-772, 43m Δ
  urlhaus-1: 26490-0, now
  plowe-0: 3552-0, now
  ITA-0: 8765-32, now
filterset (user): [array of 1 redacted]
hostRuleset:
 added: [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 261 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 50
 network:
  twitch.tv: 4
  amazon-adsystem.com: 1
  d2v02itv0y9u9t.cloudfront.net: 1
  scorecardresearch.com: 43
  ttvnw.net: 1
 extended:
  ##.stream-display-ad__wrapper
  ##+js(twitch-videoad)
  ##+js(no-window-open-if, amazon-adsystem)

### Other extensions used

ttv lol pro

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 153091
 cosmetic: 55464
 scriptlet: 22568
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40303-143, 43m Δ
  ublock-badware: 11321-6, 43m Δ
  ublock-privacy: 1252-22, 43m Δ
  ublock-unbreak: 2471-0, 43m Δ
  ublock-quick-fixes: 136-0, 43m Δ
  easylist: 85453-584, 43m Δ
  easyprivacy: 53086-772, 43m Δ
  urlhaus-1: 26490-0, now
  plowe-0: 3552-0, now
  ITA-0: 8765-32, now
filterset (user): [array of 1 redacted]
hostRuleset:
 added: [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 261 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 50
 network:
  twitch.tv: 4
  amazon-adsystem.com: 1
  d2v02itv0y9u9t.cloudfront.net: 1
  scorecardresearch.com: 43
  ttvnw.net: 1
 extended:
  ##.stream-display-ad__wrapper
  ##+js(twitch-videoad)
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5184
