### ISSUE TITLE
[Anti-adblock] reshet.tv

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2542]
### URL(s) where the issue occurs

`http://reshet.tv/item/news/abroad/world/newsitem-717790/`

### Describe the issue

Anti-adblock. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/41266350-c19d672e-6db3-11e8-9dbf-3a2de18f3bf0.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.8

### Settings

All default. 

### Notes

This is fixed by `/dfp/dfp.` rule in `FRA: EasyList Liste FR`. But the language of the website is not French, so that filter list would not count towards the default setup.

**Comment by KiLL4FuNK** [comment]
Anti-adblock
