### ISSUE TITLE
android.com.pl: ads

### ISSUE THREAD

**Issue by rvp777** [uBlockOrigin/uAssets#25429]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://android.com.pl/tech/818506-iphone-16-pro-ceramic-shield-drop-test/`

### Category

ads

### Description

Despite attempts to mark elements for hiding, ads still appear after refreshing the page.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 151763
 cosmetic: 56714
 scriptlet: 22776
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40299-177, 14m Δ
  ublock-badware: 11321-6, 14m Δ
  ublock-privacy: 1252-22, 14m Δ
  ublock-unbreak: 2471-0, 14m Δ
  ublock-quick-fixes: 137-0, 14m Δ
  easylist: 85484-591, 14m Δ
  easyprivacy: 53089-772, 14m Δ
  urlhaus-1: 25375-0, 4m
  plowe-0: 3552-0, 4m
  POL-0: 8759-33, 4m
  POL-2: 1280-12, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 718 ms (selfie)
 maxAssetCacheWait: 236 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  android.com.pl: 4
  clarity.ms: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  hbrd.io: 1
  imasdk.googleapis.com: 2
  onnetwork.tv: 15
  pushpushgo.com: 2
 extended:
  ##.banner--big.banner
  ##.banner--vertical.banner
  ##.banner--content.banner
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
android.com.pl##.banner
```

@MajkiIT Sorry, can you check this?

**Comment by mapx-** [comment]
@rvp777 report directly here: https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by MajkiIT** [comment]
@stephenhawk8054 I added. Thanks
