### ISSUE TITLE
nsw2u.com: detection / breakage

### ISSUE THREAD

**Issue by Mario1981** [uBlockOrigin/uAssets#25434]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nsw2u.com/`

### Category

breakage

### Description

Page reloads always to this below.

nsw2u.com
Verifying you are human. This may take a few seconds.
nsw2u.com needs to review the security of your connection before proceeding.

If disabeling on firefox site works but with ads, on brave disableing ublock not changing anything.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 150006
 cosmetic: 48461
 scriptlet: 22572
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 40300-143, 23m Δ
  ublock-badware: 11321-6, 23m Δ
  ublock-privacy: 1252-22, 23m Δ
  ublock-unbreak: 2471-0, 23m Δ
  ublock-quick-fixes: 141-0, 23m Δ
  easylist: 85483-576, 23m Δ
  easyprivacy: 53089-772, 23m Δ
  urlhaus-1: 25100-0, 10m
  plowe-0: 3548-0, never
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 hyperlinkAuditingDisabled: false
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 229 ms (selfie)
 maxAssetCacheWait: 115 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, eval, replace)
  ##+js(no-xhr-if, googlesyndication)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(trusted-replace-argument, document.createElement, 0, '', c…
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by stephenhawk8054** [comment]
On Firefox, can you test this:

```adb
nsw2u.*#@#+js(trusted-replace-argument, document.createElement, 0, "''", condition, iframe)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Mario1981** [comment]
Ok, seems to work for firefox. 
Need to check how to get it to work on Brave. Seems that they use also have an adblock layer to prevent acces to this page and other cloudflare sites.
Thx.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25823

**Comment by stephenhawk8054** [comment]
@Mario1981 Does the site use cloudflare on your side?

**Comment by Mario1981** [comment]
Hi there, I think so, when disabling I get the cloudflare verification that auto enabled itself and then goes to the main page.
