### ISSUE TITLE
gry-online.pl: breakage

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#25439]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gry-online.pl/newsroom/premiera-crusader-kings-3-roads-to-power-to-sukces-paradoxu/zb2ac0e`

### Category

breakage

### Description

Embeded Dailymotion videos in the articles do not play – clicking on them will sometimes ask you to confirm your age (if the video is age restricted), but after that only a black box is shown. If you disable uBlock Origin – the embedded videos work fine, but they always start with an ad.

Some other examples of articles with Dailymotion videos embedded:
- https://www.gry-online.pl/newsroom/pierwszy-gameplay-z-batman-arkham-shadow-nietypowa-odslona-przygo/z02a517
- https://www.gry-online.pl/newsroom/alan-wake-2-otrzyma-przerazajace-rozszerzenie-lake-house-zadebiut/z02abef

### Other extensions used

- Google Docs Offline

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-09-26 125816](https://github.com/user-attachments/assets/894f3a52-4655-41bd-981f-5b5ec2e5a7e1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 151097
 cosmetic: 56718
 scriptlet: 22777
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 8760-45, never
  POL-2: 1280-48, never
 default:
  user-filters: 0-0, never
  ublock-filters: 40300-143, now
  ublock-badware: 11321-6, now
  ublock-privacy: 1256-22, now
  ublock-unbreak: 2471-0, now
  ublock-quick-fixes: 137-0, now
  easylist: 85492-562, now
  easyprivacy: 53089-788, now
  urlhaus-1: 24700-0, now
  plowe-0: 3553-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4931 ms
 maxAssetCacheWait: 886 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  dm-event.net: 6
  getjad.io: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  inmobi.com: 4
  mrf.io: 1
  primis.tech: 1
 extended:
  ##.ban-fp-970x200, .if-no-baner.gp16-box-baner1, #baner-outer
  ###baner-outer
  ##[class^="ad-"]
  ##.js-ad
  ##.AdSense
  ##+js(abort-on-property-write, ub_ct_load)
```
</details>

**Comment by przemo20** [comment]
Thanks, the fix you did helped with the video from the first article I linked, but the videos that require age verification still don't load (the links to some articles with age-gated vids are under “Some other examples of articles with Dailymotion videos embedded:” in my original post). From my testing, this rule should also be added:
`@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=www.gry-online.pl` – at least that's what did the trick for me (after adding it to My filters).

**Comment by stephenhawk8054** [comment]
Please give exact link where you see the issue
