### ISSUE TITLE
gamepix.com: detection

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#25437]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gamepix.com/play/twerk-run-3d`

### Category

detection

### Description

Unity game detects adblocker

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7892b60d-0bc2-4614-acc3-d47e7c113fa5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150032
 cosmetic: 48467
 scriptlet: 22575
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40306-269, 18m Δ
  ublock-badware: 11321-6, 18m Δ
  ublock-privacy: 1252-22, 18m Δ
  ublock-unbreak: 2471-0, 18m Δ
  ublock-quick-fixes: 143-0, 18m Δ
  easylist: 85509-577, 18m Δ
  easyprivacy: 53089-647, 18m Δ
  urlhaus-1: 25100-0, now
  plowe-0: 3553-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1741 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  gamepix.com: 1
  doubleclick.net: 2
  google.com: 7
  googlesyndication.com: 2
  googletagmanager.com: 1
  headerlift.com: 2
  jsdelivr.net: 1
  youtube.com: 9
 extended:
  ##div[id^="gpx-banner"]
  ##.adsbygoogle-noablate
  ##+js(prevent-fetch, api)
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by mapx-** [comment]
@Tornadoalley try resetting uBO to defaults, do not use any other extension, test again

**Comment by ghost** [comment]
Their game player, if embedded on other sites, in my case: `https://www.pomu.ro/joc/tom-and-jerry-mouse-maze.html` causes detection, while if you want to play something on the Gamepix site, it doesn't trigger any detections.

<img width="1911" height="922" alt="Image" src="https://github.com/user-attachments/assets/7f47e6b7-6044-44d3-b5d5-114241880ad7" />

**Comment by jespertheend** [comment]
I suspect that this change caused breakage on https://splix.io/ and https://ducklings.io/. Please see #30250
