### ISSUE TITLE
shop.clifbar.com: breakage

### ISSUE THREAD

**Issue by geofft** [uBlockOrigin/uAssets#25433]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://shop.clifbar.com/account/register`

### Category

breakage

### Description

Creating a new account fails; the request hangs and does not respond.

I believe it's trying and failing to load scripts from Shopify. I did see a uBO-blocked POST request in devtools but I can't reproduce it.

### Other extensions used

1Password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 132
filterset (summary):
 network: 150006
 cosmetic: 48459
 scriptlet: 21004
 html: 1993
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40573-138, now
  ublock-badware: 11323-6, now
  ublock-privacy: 1239-22, now
  ublock-unbreak: 2530-1, now
  ublock-quick-fixes: 136-4, now
  easylist: 85485-186, now
  easyprivacy: 53089-62, now
  urlhaus-1: 25100-0, now
  plowe-0: 3553-998, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4031 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  clifbar.com: 1
  foo.software: 2
  sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
test

`@@||googletagmanager.com/gtm.js$script,domain=shop.clifbar.com`
