### ISSUE TITLE
blackhatworld.com: breakage

### ISSUE THREAD

**Issue by backlink-market** [uBlockOrigin/uAssets#25431]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.blackhatworld.com/seo/pbn-blog-post-tf40-rd500-handwritten-content-aged-auction-domains-20yrs-sticky-addon.1150844/page-29#post-18220257`

### Category

breakage

### Description

Ublock filters all image attachements

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![U_Block_Disabled](https://github.com/user-attachments/assets/befa5634-3e73-4f93-b133-704a0fc55864)

![U_Block_Enabled](https://github.com/user-attachments/assets/781ac085-c090-4b0a-b54b-b30ecbd8c90f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 152607
 cosmetic: 53605
 scriptlet: 20998
 html: 1993
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40572-138, 33m Δ
  ublock-badware: 11323-6, 33m Δ
  ublock-privacy: 1239-22, 33m Δ
  ublock-unbreak: 2530-1, 33m Δ
  ublock-quick-fixes: 131-4, 33m Δ
  easylist: 85484-186, 33m Δ
  easyprivacy: 53089-62, 33m Δ
  urlhaus-1: 25375-0, now
  plowe-0: 3552-997, now
  DEU-0: 7516-37, now
filterset (user): [empty]
trustedset:
 added: [array of 142 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  advertserve.com: 1
  cloudflareinsights.com: 2
  googletagmanager.com: 1
 extended:
  ##.bhw-advertise-link
  ##.bhw-banners
  ##.link--external.link > .bbImage
  ##+js(no-setTimeout-if, show)
```
</details>

**Comment by mapx-** [comment]
@backlink-market reset uBO to defaults, don't use any other extension, test again

**Comment by backlink-market** [comment]
I just noticed that the url leads to the first post of this thread so I corrected the link to show the Post in thread I was talking about. Please check this url: https://www.blackhatworld.com/seo/pbn-blog-post-tf40-rd500-handwritten-content-aged-auction-domains-20yrs-sticky-addon.1150844/page-29#post-18220257

**Comment by stephenhawk8054** [comment]
Caused by `blackhatworld.com##.link--external.link > .bbImage` in EL

@ryanbr

**Comment by backlink-market** [comment]
If you don't want to wait for easylist to update and publish you can add this to "my filter" option in ublock setting:

blackhatworld.com#@#.link--external.link > .bbImage

**Comment by bolach** [comment]
> If you don't want to wait for easylist to update and publish you can add this to "my filter" option in ublock setting:
> 
> blackhatworld.com#@#.link--external.link > .bbImage


For the first time I got blocked by blackhatworld. I applied that filter, but did not worked. Shoud I made a new report since this one is almost a month old?

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/26744

**Comment by BillAnt1** [comment]
I'm having a similar issue, but it's only happening when I click to "EDIT" one of my own messages, the text box is blank/empty.
I have uninstalled, reinstalled uBO, disabled all other extensions, cleared cache/history, restarted Chrome, but as soon as I enable uBO, this issue is repeatable.  Preferably I don't wish to make an exception for this site, just fix the blank text box during edit if possible.  If you have any suggestions I could try, please email me at billa.4you@yahoo.com

The first screenshot is with uBO disabled with a working edit screen
The second screenshot is with uBO enabled with a blank edit screen

![Blackhatworld com_2025-01-06_uBO_Off](https://github.com/user-attachments/assets/82e9272c-5631-4d1f-849c-3f1ae781c3b7)

![Blackhatworld com_2025-01-06_uBO_On](https://github.com/user-attachments/assets/423982c3-f51c-4e2a-853f-a437d7d50773)

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7b10cf608747cedccb1c8046c3124963d069a4f6#commitcomment-150952020
