### ISSUE TITLE
flipkart.com: ads

### ISSUE THREAD

**Issue by olumolu** [uBlockOrigin/uAssets#25438]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
Flipkart.com
Flipkart.net
```

### Description

This website does not show stuff
Half of them are broken

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240926-112606](https://github.com/user-attachments/assets/eec33adb-17ff-449f-a48e-f2b380935a2b)
![Screenshot_20240926-112409](https://github.com/user-attachments/assets/402f8638-d9d6-441f-a379-7dab6218f601)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 130
filterset (summary):
 network: 207441
 cosmetic: 57314
 scriptlet: 21782
 html: 1994
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1711-126, 21h.1m
  adguard-spyware: 80550-25436, 3d.18h.7m
 default:
  user-filters: 0-0, never
  ublock-filters: 41094-139, 2h.7m Δ
  ublock-badware: 11317-6, 2h.7m Δ
  ublock-privacy: 1240-25, 2h.7m Δ
  ublock-unbreak: 2533-1, 2h.7m Δ
  ublock-quick-fixes: 136-5, 2h.7m Δ
  adguard-mobile: 9816-178, 2d.1h.33m
  easylist: 85509-185, 2h.7m Δ
  easyprivacy: 53089-61, 2h.7m Δ
  urlhaus-1: 25375-0, 18h.38m
  plowe-0: 3542-1066, 8d.1h.38m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 463 ms (selfie)
 maxAssetCacheWait: 138 ms
 cacheBackend: indexedDB

```
</details>

**Comment by olumolu** [comment]
![Screenshot_20240926-112606](https://github.com/user-attachments/assets/1f7c0393-b77c-4d41-b67a-2b09a16a249e)
![Screenshot_20240926-112409](https://github.com/user-attachments/assets/6d865676-a12d-427e-906c-7095e4fc5b44)

**Comment by mapx-** [comment]
@olumolu do you still get breakages ? if YES provide more details

**Comment by mapx-** [comment]
oh, ads, maybe:

`flipkart.com##[style^="--sm-order"]:has-text(Sponsored)`

**Comment by stephenhawk8054** [comment]
This might work when searching on the page

```adb
flipkart.com##+js(json-prune-fetch-response, RESPONSE.slots.[-].widget.data.products.[].value.adInfo, , propsToMatch, /fetch)
```

but might not work when refreshing the search page, because the data is in `view-source` instead.

**Comment by olumolu** [comment]
Now it seems to be working fine.
I am closing the report if you guys need you can reopen for specific task.
I am closing so minimize clutter.
