### ISSUE TITLE
ffxiv.eorzeacollection.com: ads

### ISSUE THREAD

**Issue by berrymage** [uBlockOrigin/uAssets#25448]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ffxiv.eorzeacollection.com/`

### Category

ads

### Description

website is still serving advertisements on all its pages. you have to scroll down on each page before an ad is served, but it pops up as a box hanging on the bottom right corner of the screen. I also once saw a translucent white bar appear on the bottom of the screen, possibly the remnant of an ad the site tried to serve but was partially blocked.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151533
 cosmetic: 48181
 scriptlet: 1268
 html: 117
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40573-139, 1d.7h.5m Δ
  ublock-badware: 11323-6, 1d.7h.5m Δ
  ublock-privacy: 1239-22, 1d.7h.5m Δ
  ublock-unbreak: 2530-1, 1d.7h.5m Δ
  ublock-quick-fixes: 136-0, 1d.7h.5m Δ
  easylist: 85484-185, 1d.7h.5m Δ
  easyprivacy: 53089-40, 1d.7h.5m Δ
  urlhaus-1: 26490-0, 2d.7h.22m
  plowe-0: 3542-992, 11d.8h.24m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 402 ms
 maxAssetCacheWait: 103 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how the ads look like? Do you need to log in?

**Comment by berrymage** [comment]
this is what they look like. you do not need to log in, I got the same
result while logged out.

[image: image.png]

**Comment by berrymage** [comment]
I have no other extensions besides ublock origin. it shows me with zero
blocked resources.

[image: image.png]

**Comment by mapx-** [comment]
do not reply using the email, come here, on github and upload your screenshot

**Comment by berrymage** [comment]
sorry about that, the footer message on the email made it sound like either was an acceptable option. this is the screenshot.
that box with ads keeps popping up in the bottom right corner. (first screenshot)

additionally, since opening this ticket, I found that after browsing for a while, I would occasionally have pages redirect to ad websites, with no way to go back (hitting the back button would cause it to jump to a similar ad page). I was not able to replicate that just now, but while flicking through pages to see if I could catch it, a mysterious file automatically downloaded instead. (second screenshot)

![image](https://github.com/user-attachments/assets/08cf2139-db45-4018-9c0c-694bb77ce83a)

![image](https://github.com/user-attachments/assets/01d7bb5b-5fa5-4f8b-af16-4b3b8ad24009)

**Comment by mapx-** [comment]
No such ad on my end.

Reset uBO to defaults, do not touch any setting in uBO, do not use any other blocking extension, test again

**Comment by berrymage** [comment]
I reset it to defaults and that seems to have fixed the problem, thank you.
