### ISSUE TITLE
jetfilmizle.link: nuisance

### ISSUE THREAD

**Issue by 0x733** [uBlockOrigin/uAssets#25442]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://ply.jetv.xyz/assets/js/devtools-detector.js
https://jetfilmizle.link/olumcul-ates-killer-heat-izle.html
```

### Description

Devtools are being detected on the relevant site.

### Other extensions used

None

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 352146
 cosmetic: 321189
 scriptlet: 55721
 html: 2255
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 84257-4055, 23h.39m
  adguard-spyware-url: 1711-210, 23h.41m
  adguard-spyware: 76845-1457, 23h.39m
  block-lan: 62-0, 23h.39m
  curben-phishing: 548-0, 23h.39m
  [17 lists not shown]: [too many]
 default:
  ublock-filters: 40595-144, 1m Δ
  ublock-badware: 11169-500, 1m Δ
  ublock-privacy: 1243-152, 1m Δ
  ublock-unbreak: 2537-140, 1m Δ
  ublock-quick-fixes: 133-4, 1m Δ
  easylist: 85520-2240, 1m Δ
  easyprivacy: 53090-24338, 1m Δ
  urlhaus-1: 25100-0, 23h.41m
  plowe-0: 3552-1443, 23h.41m
  TUR-0: 11396-65, 23h.40m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1956 ms (selfie)
 maxAssetCacheWait: 1094 ms
 cacheBackend: indexedDB
```
</details>

**Comment by D4niloMR** [comment]
This works on my end:

```adb
||jetv.xyz/assets/js/devtools-detector.js$script,1p
jetv.xyz##+js(trusted-suppress-native-method, Function.prototype.constructor, '"debugger"', abort)
jetv.xyz##+js(nosiif, devtoolsDetector)
```

**Comment by 0x733** [comment]
> This works on my end:
> 
> 
> 
> ```adb
> 
> ||jetv.xyz/assets/js/devtools-detector.js$script,1p
> 
> jetv.xyz##+js(trusted-suppress-native-method, Function.prototype.constructor, '"debugger"', abort)
> 
> jetv.xyz##+js(nosiif, devtoolsDetector)
> 
> ```

Thank you very much for your support.
