### ISSUE TITLE
realestate.com.au: ads

### ISSUE THREAD

**Issue by joelkoen** [uBlockOrigin/uAssets#25449]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.realestate.com.au/property-house-tas-windermere-146158540`

### Category

ads

### Description

ad in media gallery, click on an image and wait a few seconds

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/4b42246c-8399-47b0-9a45-e599ebcdec28)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 115
filterset (summary):
 network: 154601
 cosmetic: 48472
 scriptlet: 21037
 html: 1995
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40595-138, 1h.59m Δ
  ublock-badware: 11164-6, 1h.59m Δ
  ublock-privacy: 1248-22, 1h.59m Δ
  ublock-unbreak: 2538-1, 1h.59m Δ
  ublock-quick-fixes: 134-4, 1h.59m Δ
  easylist: 85550-186, 1h.59m Δ
  adguard-spyware-url: 1719-126, 8m
  easyprivacy: 53092-62, 1h.59m Δ
  urlhaus-1: 25170-0, 8m
  curben-phishing: 524-1, 8m
  plowe-0: 3553-998, 8m
  LegitimateURLShortener: 2677-167, 9m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 519 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 63
 network:
  realestate.com.au: 5
  adform.net: 4
  adsafeprotected.com: 4
  adsrvr.org: 2
  aimatch.com: 4
  casalemedia.com: 2
  criteo.net: 3
  demdex.net: 5
  dotmetrics.net: 1
  doubleclick.net: 12
  facebook.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  imrworldwide.com: 1
  indexww.com: 1
  newrelic.com: 4
  reagroupdata.com.au: 2
  reamedia.com.au: 1
  rubiconproject.com: 1
  seenthis.se: 1
  tealiumiq.com: 4
  yimg.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||sasinator.realestate.com.au^
realestate.com.au##.media-viewer__sidebar
```

@ryanbr

**Comment by joelkoen** [comment]
Thank you :)
