### ISSUE TITLE
etoro.com: breakage

### ISSUE THREAD

**Issue by Sainan** [uBlockOrigin/uAssets#25453]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.etoro.com/home
```

### Description

There typically is a search box at the top of the page, but as of recent, there no longer is with uBO enabled.

### Other extensions used

I use a lot. Privacy Badger, Stylus, Dark Reader are of note, but they should not be causing this.

### Screenshot(s)

![image](https://github.com/user-attachments/assets/a64773fb-23aa-4744-8ddd-0a46162f707e)

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 152146
 cosmetic: 53623
 scriptlet: 22598
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 85562-573, 1h.48m Δ
  easyprivacy: 53092-645, 1h.48m Δ
  plowe-0: 3542-0, 10d.56m
  ublock-badware: 11167-6, 1h.48m Δ
  ublock-filters: 40321-268, 1h.48m Δ
  ublock-privacy: 1261-22, 1h.48m Δ
  ublock-quick-fixes: 139-0, 1h.48m Δ
  ublock-unbreak: 2479-0, 1h.48m Δ
  urlhaus-1: 24990-0, 18h.41m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 176 ms (selfie)
 maxAssetCacheWait: 69 ms
 cacheBackend: indexedDB
```
</details>    

I think your instructions here are outdated:
> On the affected site: 🛡️ uBO's icon > 💬 Report > Click "Troubleshooting information" > Select all > Copy > Paste it below.

There is no " 💬 Report" button, but I found it in the Support section of the settings.

**Comment by Sainan** [comment]
For what it's worth, I think this one being blocked might be the issue:
> GET https://web-sdk.urbanairship.com/notify/v1/ua-sdk.min.js net::ERR_BLOCKED_BY_CLIENT

I have no idea how to "whitelist" a specific URL to test this, tho.

**Comment by stephenhawk8054** [comment]
Caused by `||urbanairship.com^` in EP

```adb
@@||web-sdk.urbanairship.com/notify/v1/ua-sdk.min.js$script,domain=etoro.com
```

@ryanbr

**Comment by Sainan** [comment]
Adding that to my custom rules fixed it.
