### ISSUE TITLE
startse.com: breakage

### ISSUE THREAD

**Issue by douglas-pereira-startse** [uBlockOrigin/uAssets#25456]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.startse.com/`

### Category

breakage

### Description

AdBlock removing authentication token from website. I can login in my account but AdBlock is removing authStartseToken after authentication, causing problems in my access. I do some tests without AdBlock and over anonymous tab and works ok. The problem only occurs when adblock is active. 

### Other extensions used

1password, Adobe Acrobat, Cuponomia

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/d2bcc992-a5b2-48f4-b8e0-f4ebe8bf18dd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 129
filterset (summary):
 network: 149843
 cosmetic: 48473
 scriptlet: 22598
 html: 0
listset (total-discarded, last-updated):
 removed:
  spa-1: null
 default:
  user-filters: 0-0, never
  easylist: 85562-577, 1h.42m Δ
  easyprivacy: 53092-642, 1h.42m Δ
  plowe-0: 3546-0, 7m
  ublock-badware: 11167-6, 1h.42m Δ
  ublock-filters: 40321-268, 1h.42m Δ
  ublock-privacy: 1261-22, 1h.42m Δ
  ublock-quick-fixes: 139-0, 1h.42m Δ
  ublock-unbreak: 2479-0, 1h.42m Δ
  urlhaus-1: 25010-0, 7m
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 812 ms
 maxAssetCacheWait: 173 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  startse.com: 1
  cloudflareinsights.com: 1
  google-analytics.com: 2
  googletagmanager.com: 1
  newrelic.com: 1
  omappapi.com: 1
  onesignal.com: 1
  segment.com: 1
  typekit.net: 1
  vercel-insights.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||google-analytics.com/mp/collect?$xhr,domain=startse.com
```

@ryanbr
