### ISSUE TITLE
nosdevoirs.fr: detection

### ISSUE THREAD

**Issue by covuk** [uBlockOrigin/uAssets#25457]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nosdevoirs.fr/`

### Category

detection

### Description

When I click 'Unlock the answer' _(Débloque la réponse)_, the website detects uBO (uBlock Origin).

### Other extensions used

Wappalyzer V6.10.74

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**Screenshot 1 :**
![image](https://github.com/user-attachments/assets/1e1daf16-3ab8-4755-b5d0-cd0454044e11)
> Translation : "You have reached your daily limit of free responses.
Download the app for more responses - without interruptions or Unlock the answer by watching a video."

**Screenshot 2 :**
![image](https://github.com/user-attachments/assets/e7f43669-905e-44b6-98c5-6ca3884f5494)
 > Translation : "Thanks to ads, Nosdevoirs is free
Alright, you like blocking ads, but wouldn’t you like us a little more? :-D
Disable your ad blocker to support Nosdevoirs and see this answer!
Learn how to disable the ad blocker"

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 149835
 cosmetic: 48470
 scriptlet: 21027
 html: 1997
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40595-138, 51m
  ublock-badware: 11169-6, 51m
  ublock-privacy: 1248-22, 51m
  ublock-unbreak: 2538-1, 51m
  ublock-quick-fixes: 134-4, 51m
  easylist: 85562-186, 51m
  easyprivacy: 53092-62, 51m
  urlhaus-1: 25010-0, 52m
  plowe-0: 3546-993, 52m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11093 ms
 maxAssetCacheWait: 1187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  nosdevoirs.fr: 3
  adlightning.com: 1
  cloudflareinsights.com: 2
  connatix.com: 3
  datadome.co: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  opti-digital.com: 2
  rubiconproject.com: 1
  sentry-cdn.com: 1
  stripe.com: 12
 extended:
  ##.ads_banner
  ##.brn-ads-mobile-container
  ##.brn-ads-sticky-wrapper
  ##.brn-ads-box
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give a more detailed, exact link and describe the steps to reproduce with non-cropped screenshots?

**Comment by stephenhawk8054** [comment]
@055110 Does this filter work?

```adb
nosdevoirs.fr##+js(acs, document.getElementById, adBlock)
```

**Comment by stephenhawk8054** [comment]
@055110 Can you screenshot where the `Débloque la réponse` text occurs?

**Comment by stephenhawk8054** [comment]
@055110 Does this work?

```adb
nosdevoirs.fr##+js(set-local-storage-item, simple-funnel-name, $remove$)
```

**Comment by stephenhawk8054** [comment]
Fixed in `uBlock filters – Annoyances` list.

**Comment by covuk** [comment]
Thanks y'all for the solution !
