### ISSUE TITLE
saal-digital.de: breakage

### ISSUE THREAD

**Issue by szotsaki** [uBlockOrigin/uAssets#25450]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.saal-digital.de/WebshopConfigurator/` - .de, .hu, .etc.

### Category

breakage

### Description

Account registration is broken because of hidden checkbox:
```
+33
##div.gdpr
www.saal-digital.de
get
dom
https://www.saal-digital.de/WebshopConfigurator/#/0c253600cfb83e672b8939e843f01084/de/Settings/
```
This webpage is available under many other domains.

Filter list: EasyList – Cookie Notices

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 215642
 cosmetic: 212350
 scriptlet: 34271
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7516-0, now
  adguard-cookies: 31988-75, now
  adguard-mobile-app-banners: 5479-12, now
  adguard-other-annoyances: 14554-40, now
  adguard-popup-overlays: 28019-1436, now
  adguard-social: 23098-908, now
  adguard-spyware: 76853-24801, now
  adguard-spyware-url: 1719-7, now
  adguard-widgets: 2665-22, now
  block-lan: 62-0, now
  easylist-chat: 215-0, now
  easylist-newsletters: 7866-19, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 77-1, never
  HUN-0: 2096-1, now
  easylist: 85550-590, 1h.49m Δ
  easyprivacy: 53092-662, 1h.49m Δ
  plowe-0: 3553-5, now
  ublock-badware: 11162-6, 1h.49m Δ
  ublock-filters: 40321-770, 1h.49m Δ
  ublock-privacy: 1261-142, 1h.49m Δ
  ublock-quick-fixes: 140-0, 1h.49m Δ
  ublock-unbreak: 2479-22, 1h.49m Δ
  urlhaus-1: 25170-0, now
filterset (user): [array of 78 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 394 ms (selfie)
 maxAssetCacheWait: 110 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  cookiepro.com: 1
 extended:
  ##div.gdpr
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@/otBannerSdk.js$domain=saal-digital.de
```

@Yuki2718 For ELC

**Comment by Yuki2718** [comment]
> This webpage is available under many other domains.

The page is blank even with uBO turned off on my end. Can you list the domains?

**Comment by szotsaki** [comment]
To reproduce it:
1. https://www.saal-digital.de
2. In the upper right corner click on the user account button
3. Erstell dir einen Account
4. The first checkbox, starting with "Ich willige ein, dass meine personenbezogenen Daten auf Basis der..." was not visible

Other domains:
1. https://www.saal-digital.de
2. Jetzt bestellen
3. Jetzt Gestalten (first column)
4. (scroll down, left) Sprache: Deutsch (de)
5. You can substitute www.saal-digital **.de** with the language codes shown in the parentheses in the drop-down. The reproducer is the same (account icon > create account > first checkbox)

**Comment by mapx-** [comment]
unhiding the first checkbox:

`saal-digital.de#@#div.gdpr`

it should be removed => `##div.gdpr`

@Yuki2718

**Comment by Yuki2718** [comment]
@ryanbr `##div.gdpr` has many exception already. Maybe it is better to change to specific?
