### ISSUE TITLE
vim.org: ads

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#25458]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.vim.org/`

### Category

ads

### Description

ads on the right side

### Other extensions used

- Bitwarden Passwortmanager
- SponsorBlock 
- AdGuard Extra
- Gumbo
- Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/ed7af3b3-1eff-4966-b543-fced6953472d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 160817
 cosmetic: 131852
 scriptlet: 32884
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2677-49, never
  adguard-spyware-url: 1720-244, never
  fanboy-cookiemonster: 52156-228, never
  ublock-cookies-easylist: 1771-9, never
  fanboy-social: 17104-10, never
  easylist-annoyances: 4794-122, never
  easylist-chat: 216-0, never
  easylist-newsletters: 7867-48, never
  easylist-notifications: 3442-81, never
  ublock-annoyances: 5974-42, never
 default:
  user-filters: 0-0, never
  ublock-filters: 40325-284, 1m
  ublock-badware: 11171-6, 1m
  ublock-privacy: 1282-22, 1m
  ublock-unbreak: 2480-0, 1m
  ublock-quick-fixes: 140-0, 1m
  easylist: 85562-587, 1m
  easyprivacy: 53092-650, 1m
  urlhaus-1: 25255-0, 1m
  plowe-0: 3546-0, 1m
  DEU-0: 7520-3, 1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1722 ms
 maxAssetCacheWait: 27 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
add in "my filters"

`vim.org##[href="https://iccf-holland.org/clickkindle.html"]`

report at easylist repository
