### ISSUE TITLE
stash.clash.gg: ads

### ISSUE THREAD

**Issue by mutlupide** [uBlockOrigin/uAssets#25454]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://stash.clash.gg/`

### Category

ads

### Description

clash.gg ad on the left side of the page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/user-attachments/assets/40892aeb-aa37-4cbe-bcfa-c177c65ef210)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 151419
 cosmetic: 57081
 scriptlet: 22369
 html: 1997
listset (total-discarded, last-updated):
 default:
  user-filters: 7-1, never
  ublock-filters: 40595-138, 1h.33m Δ
  ublock-badware: 11169-6, 1h.33m Δ
  ublock-privacy: 1248-22, 1h.33m Δ
  ublock-unbreak: 2538-1, 1h.33m Δ
  ublock-quick-fixes: 134-4, 1h.33m Δ
  easylist: 85562-186, 1h.33m Δ
  easyprivacy: 53092-62, 1h.33m Δ
  urlhaus-1: 25170-0, now
  plowe-0: 3546-993, now
  TUR-0: 11403-37, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 436 ms (selfie)
 maxAssetCacheWait: 93 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  google-analytics.com: 1
  google.com: 10
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
self-promotion

add in "my filters"

`||stash.clash.gg/img/clash-banners/$image`
