### ISSUE TITLE
filmweb.pl: breakage - videos do not play with "uBlock filters – Unbreak" enabled

### ISSUE THREAD

**Issue by occasionalbughunter** [uBlockOrigin/uAssets#25466]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.filmweb.pl/video/Zwiastun/Wielkie+pi%C4%99kno+Zwiastun+nr+1+polski-32642`

### Category

breakage

### Description

When "uBlock filters – Unbreak" is enabled, video does not play on this site. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/user-attachments/assets/d34232a9-babe-4cf8-86d5-4e901a8b1a62)
![obraz](https://github.com/user-attachments/assets/fe37c07b-d5ed-4f46-ba2b-ac3b356b886c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 20348
 cosmetic: 12363
 scriptlet: 20818
 html: 1998
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  plowe-0: null
  POL-0: null
  POL-2: null
  urlhaus-1: null
 default:
  user-filters: 68-1, never
  ublock-filters: 40545-138, 1m
  ublock-badware: 11169-6, 1m
  ublock-privacy: 1253-22, 1m
  ublock-unbreak: 2538-1, never
  ublock-quick-fixes: 140-8, 1m
filterset (user): [array of 68 redacted]
trustedset:
 added: [array of 219 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 34 redacted]
userSettings:
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 363 ms
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
 unsuspendAfter: 83 ms
popupPanel:
 blocked: 1
 network:
  smartadserver.com: 1
```
</details>

**Comment by mapx-** [comment]
> removed:
>   easylist: null
>   easyprivacy: null
>   plowe-0: null
>   POL-0: null
>   POL-2: null
>   urlhaus-1: null
> 

very very bad.

Reset uBO to defaults, add the regional PL lists too, do not touch any setting in uBO, do not use any other blocking extension

**Comment by occasionalbughunter** [comment]
I had to disable these lists, because when they were enabled, they also caused blocking this page. This smartadserver seems to be blocked by many filters so I will have to write to each list creator.

**Comment by mapx-** [comment]
No issue on my end using uBO defaults.

**Comment by occasionalbughunter** [comment]
I did as you asked but issue still persist.
This is my config after reset:
![config](https://github.com/user-attachments/assets/5868dcce-401f-4cab-8d5f-005de0a35bbd)

From my limited understanding of this issue, ad server is blocked via EasyList:
![obraz](https://github.com/user-attachments/assets/bb2f2bbc-351c-4563-bf89-26800fd9923c)

When I disable it, is blocked via Polish uBlock Filters:
![obraz](https://github.com/user-attachments/assets/599f095a-2464-49e5-be85-154e8e9d0431)

When I disable them too, this is now blocked by uBlock Unbreak I reported earlier:
![obraz](https://github.com/user-attachments/assets/a910799a-6e98-464e-8025-feb049663543)

Then by Peter Lowe's Ad and tracking list:
![obraz](https://github.com/user-attachments/assets/f65aaaa2-0247-45eb-9834-0a8d714a2e56)

Only when I disable all 4, this site works:
![obraz](https://github.com/user-attachments/assets/0068ffa3-1d37-4a93-be8e-820e2d75af04)
and this is what remains in config:
![obraz](https://github.com/user-attachments/assets/ebdcdbe4-45ea-4537-9b07-ce391fd0dc4d)

**Comment by occasionalbughunter** [comment]
Nevermind. I had to ENABLE additional filter: AdGuard – Ads. 
It is right below Easy List, but it is disabled on default.
When I enabled it, I was able to enable all 4 lists and it still works!
It must contain some exclusion which fixes this page.

**Comment by mapx-** [comment]
uBO defaults is enough on my end.

Did you disable ETP (Enhanced Tracking Protection) in firefox ?

**Comment by occasionalbughunter** [comment]
Yes I have it disabled on this site. 
Tried setting it to standard or custom with all disabled in general browser settings but it changed nothing.

**Comment by stephenhawk8054** [comment]
Video plays fine on my side with default settings + POL lists

![image](https://github.com/user-attachments/assets/c3bd514c-c610-4b4b-ac01-0a127705558f)
