### ISSUE TITLE
myprivacy.dpgmedia.nl: breakage

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uAssets#25468]
When surfing to NU.NL a cookie consent notification is triggered.

The grey notification overlay is not removed: https://myprivacy.dpgmedia.nl/consent?

Version: uBlock Origin Lite 2024.9.22.986

Filters:
15,986 rules, converted from 123,516 network filters

nl nl be be: AdGuard Dutch
462 rules, converted from 532 network filters

AdGuard URL Tracking Protection
514 rules, converted from 1,699 network filters

EasyList/uBO – Overlay Notices
297 rules, converted from 441 network filters

EasyList/uBO – Cookie Notices
1,620 rules, converted from 1,949 network filters

EasyList – Social Widgets
608 rules, converted from 689 network filters

EasyList – Other Annoyances
408 rules, converted from 728 network filters

EasyList – Chat Widgets
46 rules, converted from 193 network filters

**Comment by gorhill** [comment]
> `||myprivacy-static.dpgmedia.net^$domain=nu.nl`

Same issue. For me only `myprivacy.dpgmedia.nl#@##pg-modal` works.

**Comment by Kees1958** [comment]
Thanks that seems to solve it (running ABP besides uBol with no filters, only to block ads at some Dutch websites, Ghostery now also offers user rules)Op 29 sep 2024 15:15 schreef uBlock-user ***@***.***>:
||myprivacy-static.dpgmedia.net^$domain=nu.nl ?

**Comment by gorhill** [comment]
From the comment in the filter list, it seems the solution is to add `myprivacy.dpgmedia.nl` to `myprivacy.dpgmediagroup.net##+js(set-cookie, dummy, 1, , reload, 1)`.
