### ISSUE TITLE
nullforums.net: nuisance

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25465]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nullforums.net/resources/categories/minecraft-leaks.112/?page=4`

### Category

nuisance

### Description

text cannot copy. they blocked to copy texts.

### Other extensions used

localcdn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 131
filterset (summary):
 network: 227592
 cosmetic: 192298
 scriptlet: 39708
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1720-125, now
  adguard-spyware: 76866-24890, now
  block-lan: 64-0, now
  curben-phishing: 629-0, now
  adguard-cookies: 31998-100, now
  ublock-cookies-adguard: 1815-9, now
  fanboy-cookiemonster: 52161-4086, now
  ublock-cookies-easylist: 1815-1815, now
  adguard-popup-overlays: 28024-961, now
  adguard-mobile-app-banners: 5486-1132, now
  adguard-other-annoyances: 14563-377, now
  adguard-widgets: 2666-20, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40785-859, 22m Δ
  ublock-badware: 11165-9, 22m Δ
  ublock-privacy: 1288-22, 22m Δ
  ublock-unbreak: 2483-5, 22m Δ
  ublock-quick-fixes: 145-0, 22m Δ
  adguard-mobile: 9845-11, now
  easylist: 85651-826, 22m Δ
  easyprivacy: 53103-850, 22m Δ
  urlhaus-1: 25380-0, now
  plowe-0: 3546-83, now
  TUR-0: 11416-26, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2497 ms (selfie)
 maxAssetCacheWait: 323 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  nullforums.net: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 extended:
  ##.samBannerUnit
  ##.p-footer-rssLink
  ##.js-notice.notice--cookie
  ##.notice--cookie:not(body):not(html)
  ##.u-scrollButtons
  ##+js(no-setTimeout-if, show)
```
</details>

**Comment by mapx-** [comment]
enable uBlock filters – Annoyances
