### ISSUE TITLE
99bitcoins.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#2546]
![2018-06-12-99bitcoins _ buy bitcoin bitcoin guides reviews for bitcoin newbies](https://user-images.githubusercontent.com/5884000/41301688-f20be97a-6e68-11e8-8577-3538adcab5aa.png)

scroll blocked

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.8
 ND 14.52
 Chr 67.0.3396.79
</details>

**Comment by krystian3w** [comment]
```
99bitcoins.com##html.tve-o-hidden.tve-hide-overflow.tve-l-open, body.tve-o-hidden.tve-hide-overflow.tve-l-open:style(overflow: visible !important)
``` 

You can use how long no fixed in Fanoboy Annoyances.

**Comment by gwarser** [comment]
![screenshot_20180613_133537](https://user-images.githubusercontent.com/886325/41349004-c457be4a-6f0e-11e8-954a-1b9039c20bf6.png)

This dialog appears after ~30s of scrolling, is hidden by Fanboy Annoyances.

**Comment by krystian3w** [comment]
Yes, form my side I cannot block start this newsletter.

**Comment by adranger** [comment]
@mapx- This hasn't been fixed by Fanboy (https://github.com/ryanbr/fanboy-adblock/issues/440). Please prevent the generation of this overlay.

**Comment by mapx-** [comment]
Could you check if works for you ?

`99bitcoins.com##script:inject(setTimeout-defuser.js, (), overlay)`

**Comment by adranger** [comment]
That seems to be enough. 

@KonoromiHimaries make sure to enable **uBlock filters – Annoyances​​​​​** and update it.
