### ISSUE TITLE
hgtv.com: breakage

### ISSUE THREAD

**Issue by kevomac12** [uBlockOrigin/uAssets#25463]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hgtv.com/shows/10k-your-way?lid=j1m7t8i738jw&nl=R-HGTV:Sweeps2024_2024-09-27_EnterHGTV`

### Category

detection

### Description

This page has been blocked by an extension
I disabled ABP, and all third-party parameters are allowed (not comfortable w/malicious entities 'possible' access), I turned of uBlock and didn't get the message "This page has been blocked by an extension".

### Other extensions used

Malwarebytes, Webroot web threat shield

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150278
 cosmetic: 48476
 scriptlet: 22611
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40275-134, now
  ublock-badware: 11171-6, now
  ublock-privacy: 1287-23, now
  ublock-unbreak: 2480-1, now
  ublock-quick-fixes: 142-10, now
  easylist: 85650-577, now
  easyprivacy: 53101-768, now
  urlhaus-1: 25380-0, now
  plowe-0: 3546-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 8017 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1457 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  adobedtm.com: 5
  demdex.net: 1
  engageplatform.com: 1
  facebook.net: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  imrworldwide.com: 1
  qualtrics.com: 1
  serving-sys.com: 1
  skimresources.com: 1
  snidigital.com: 1
  trackonomics.net: 1
  tru.am: 1
  wmcdp.io: 7
  yimg.com: 1
 extended:
  ###dfp_leaderboard
  ##.rr-ad
  ##.bigbox-ad
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce:

![image](https://github.com/user-attachments/assets/7d18800f-e35f-4bdd-9a17-4bf23180a836)

Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
you are using Malwarebytes, ABP etc

**remove these blocking extensions**, keep only uBO, reset it to defaults, do not touch any uBO setting, test again

**Comment by kevomac12** [comment]
They don't interfere. All I did was enable 3rd party parameters... 

***************************************************
"When you pass through the waters, I will be with you: and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned: the flames will not set you ablaze."      
Isaiah 43:2
 

    On Sunday, September 29, 2024 at 01:01:09 AM MDT, mapx ***@***.***> wrote:  
 
 


you are using Malwarebytes, ABP etc

remove these blocking extensions, keep only uBO, reset it to defaults, do not touch any uBO setting, test again

**Comment by stephenhawk8054** [comment]
> Test again in a new browser profile with only uBO and its default settings.

And don't reply via email. Reply directly on github please.

**Comment by kevomac12** [comment]
I did that, it worked on the HGTV pages, don't know about Food Network or TLC! But enabling 3rd party parameters, achieved my end, after I've finished with these contests, I disable them again.

**Comment by stephenhawk8054** [comment]
I don't understand what you mean by `enabling 3rd party parameters`. There's nothing like that in uBO.

```yml
hostRuleset:
 added: [array of 8017 redacted]
userSettings:
 advancedUserEnabled: true
```

Anyways, you are enabling "Advanced user settings" and using a heavily modified configurations (>8k dynamic rules), so please read [documentation](https://github.com/gorhill/uBlock/wiki) and investigate the issue yourself.
