### ISSUE TITLE
inficourses.com: ads

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#25467]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.inficourses.com/course/vueschool-the-vuejs-3-masterclass`

### Category

ads

### Description

This site has javascript that turns legit download links such as `https://send.cm/d/...` into "shortened" links like `https://shrinkearn.com/full?api=...&url=...&type=1`

I found that this filter fixes the problem
`||www.inficourses.com/_next/static/chunks/pages/course/%5Bslug%5D-dd27fffe2602e332.js$script,domain=www.inficourses.com`

But I'm not sure where to add it in the lists, or if it is optimized, hence opening this issue.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="526" alt="image" src="https://github.com/user-attachments/assets/cf31f6f2-de75-4921-92b3-b35a843b9a1d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 186451
 cosmetic: 201730
 scriptlet: 33499
 html: 2269
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 439-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 759-8, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2677-76, now
  https://raw.githubusercontent.com/chainapsis/phishing-block-list/main/block-list.txt: 1130-6, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 408-1, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4013-36, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 100-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/refs/heads/main/youtube_clear_view.txt: 33-0, now
  adguard-spyware-url: 1720-286, now
  adguard-cookies: 31998-50, now
  ublock-cookies-adguard: 1778-28, now
  adguard-social: 23107-47, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 239-11, never
  ublock-filters: 40573-157, now
  ublock-badware: 11174-22, now
  ublock-privacy: 1253-76, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 140-2, 37m Δ
  easylist: 85652-188, now
  easyprivacy: 53103-63, now
  urlhaus-1: 25380-0, now
  plowe-0: 3546-994, now
filterset (user): [array of 174 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 20 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 662 ms (selfie)
 maxAssetCacheWait: 351 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  inficourses.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by gorhill** [comment]
Might also be a case to improve the new option `urlskip=`. The original link is in the `url=` parameter, but encoded in base64. So another solution which would work for all `shrinkearn.com/full?` instance anywhere would be to add ability to decode base64 in `urlskip=` and create a filter resembling:

    ||shrinkearn.com/full?$urlskip=?url -base64
