### ISSUE TITLE
accounts.google.com: breakage

### ISSUE THREAD

**Issue by JustSxm** [uBlockOrigin/uAssets#25475]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?response_type=code&client_id=xxxxxxxxxxxxxxx&flowName=GeneralOAuthFlow`

### Category

breakage

### Description

uBlock breaks autorization flows for some reason. When I use ublock origin I get a "Something went wrong" after selecting an account to continuing with. 

Everything works fine if ublock origin is disabled.

**EDIT** : It happens only when selecting an account with multiple channels and it asks to choose a channel

### Other extensions used

PocketTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e4dc4ab8-3054-4bff-ac6a-674626516749)
![image](https://github.com/user-attachments/assets/56cf0ed3-f69d-4be1-93fd-9124bc8987f6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 149930
 cosmetic: 48450
 scriptlet: 21043
 html: 2000
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40547-138, now
  ublock-badware: 11173-6, now
  ublock-privacy: 1257-22, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 139-8, now
  easylist: 85568-184, now
  easyprivacy: 53111-62, now
  urlhaus-1: 25105-0, now
  plowe-0: 3546-993, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 91 ms (selfie)
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  google.com: 4
  youtube.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
