### ISSUE TITLE
kakaku.com: ads

### ISSUE THREAD

**Issue by cheekyclaire** [uBlockOrigin/uAssets#25478]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kakaku.com/bb/`

### Category

ads

### Description

It seems ads on both side and inside the page won't be removed by default filter lists.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 156500
 cosmetic: 114427
 scriptlet: 25596
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1h.55m
  adguard-cookies: 31998-66, 4m
  adguard-social: 23107-36, 4m
  adguard-widgets: 2666-2, 4m
  curben-phishing: 517-0, 1h.55m
  fanboy-thirdparty_social: 68-0, 4m
  ublock-cookies-adguard: 1779-9, 4m
 default:
  user-filters: 23-0, never
  JPN-1: 15219-12, 4m
  easylist: 85568-497, 1h.55m Δ
  easyprivacy: 53111-662, 1h.55m Δ
  plowe-0: 3546-0, 4m
  ublock-badware: 11176-25, 1h.55m Δ
  ublock-filters: 40277-390, 1h.55m Δ
  ublock-privacy: 1292-22, 1h.55m Δ
  ublock-quick-fixes: 144-0, 1h.55m Δ
  ublock-unbreak: 2480-22, 1h.55m Δ
  urlhaus-1: 25255-0, 1h.55m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 36 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 668 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  kakaku.com: 1
  adobedtm.com: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  geoedge.be: 1
  k-img.com: 1
  rubiconproject.com: 1
 extended:
  ##.c-ad
  ##.p-planbox_pr
  ##.bnSuper
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-promotion

```adb
kakaku.com##.c-global_pr
```

cc @Yuki2718
