### ISSUE TITLE
litres.ru: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#25473]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.litres.ru/`

### Category

nuisance

### Description

It looks like there are a couple of rules for cookie notices in _"EasyList – Cookie Notices"_ for this site, but at least one of them is deprecated:

`litres.ru##.CookieAcceptPopup-module__container_UndPF `

So cookie pops up in the bottom right corner. I've found the correct rule in _AdGuard Cookie Annoyances_ list:

`litres.ru##div[data-testid="cookieAcceptPopup"]`

Replace the first one with the second, so that cookie notice on litres successfully get blocked again. Thanks in advance!

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 94494
 cosmetic: 138349
 scriptlet: 32101
 html: 2291
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 24654-26, 30m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1737-21, 30m
  fanboy-cookiemonster: 52234-342, 30m
  ublock-cookies-easylist: 1779-13, 30m
  ublock-annoyances: 5918-63, 30m
 default:
  user-filters: 2-0, never
  ublock-filters: 40547-138, 30m
  ublock-badware: 11163-6, 30m
  ublock-privacy: 1253-30, 30m
  ublock-unbreak: 2538-6, 30m
  ublock-quick-fixes: 141-8, 30m
  easylist: 85558-198, 30m
  RUS-0: 40803-187, 30m
filterset (user): [array of 2 redacted]
userSettings:
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 119 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  litres.io: 1
  yandex.ru: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/56bf6764d67f8d899349a792a731068805a791db
