### ISSUE TITLE
hln.be: breakage

### ISSUE THREAD

**Issue by SeBr28** [uBlockOrigin/uAssets#25484]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.hln.be/video/productie/dit-zijn-de-ministers-van-diependaele-i-775255
```

### Description

if you disable ublock the video works. With it enabled you get error. When you diasble, open video it works. Enable it and first time it will work.. click on another video.. won't work anymore.

### Other extensions used

1password
wappalyzer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/75ae6508-1251-42e4-9072-53ed764f072c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150671
 cosmetic: 50207
 scriptlet: 22633
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40278-271, 11m Δ
  ublock-badware: 11177-6, 11m Δ
  ublock-privacy: 1294-22, 11m Δ
  ublock-unbreak: 2480-0, 11m Δ
  ublock-quick-fixes: 131-0, 11m Δ
  easylist: 85575-578, 11m Δ
  easyprivacy: 53112-647, 11m Δ
  urlhaus-1: 25255-0, 11m
  plowe-0: 3548-0, 8d.4h.2m
  NLD-0: 2372-39, 3d.3h.22m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 740 ms (selfie)
 maxAssetCacheWait: 24 ms
 cacheBackend: indexedDB
```

</details>

**Comment by gorhill** [comment]
I get the issue without uBO, and with no extension installed.

**Comment by mapx-** [comment]
@SeBr28 reset uBO to defaults, disable any other extension, test again
