### ISSUE TITLE
online-filmek.ac: detection

### ISSUE THREAD

**Issue by noobodyl** [uBlockOrigin/uAssets#25482]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://online-filmek.ac/film/37963-egy-cica-10-elete`

### Category

detection

### Description

the detection happens in a small box under the synopsis(the red box is the detection,the links should apear there) 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240930_172307_com kiwibrowser browser](https://github.com/user-attachments/assets/e94055e9-4fdd-4cc0-b80b-ecef28dc253f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 124
filterset (summary):
 network: 151679
 cosmetic: 58809
 scriptlet: 22729
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  HUN-0: 2097-3, 27m
  adguard-mobile: 9854-11, now
  easylist: 85574-640, now
  easyprivacy: 53112-660, now
  plowe-0: 3546-86, now
  ublock-badware: 11171-7, now
  ublock-filters: 40788-358, now
  ublock-privacy: 1293-22, now
  ublock-quick-fixes: 131-0, now
  ublock-unbreak: 2483-2, now
  urlhaus-1: 25105-0, 27m
filterset (user): [array of 58 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4068 ms (selfie)
 maxAssetCacheWait: 183 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  disqus.com: 7
  facebook.com: 2
  geozo.com: 5
  gloaphoo.net: 1
  mipfohaby.com: 2
  notix.io: 1
  srvtrck.com: 1
  viglink.com: 2
 extended:
  ##.adslot_1
  ##+js(prevent-fetch, adligature)
  ##.ad-content:not(:empty)
  #@#.ad-content
  ##+js(trusted-replace-xhr-response, '/null,"category_sensitive"[…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"role":"SEARCH_A…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Ma…
  ##+js(trusted-replace-xhr-response, /\{"node":\{"__typename":"Vi…
  ##+js(json-prune-xhr-response, data.viewer.instream_video_ads da…
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce using default settings/lists, no other extension.

**Comment by mapx-** [comment]
I'm able to reproduce:

@noobodyl add:

`online-filmek.ac##+js(rpnt, script, (res), (1==2))`

**Comment by mapx-** [comment]
or

`online-filmek.ac##+js(no-fetch-if, api)`
