### ISSUE TITLE
sport1.de: ads

### ISSUE THREAD

**Issue by angrypeestain** [uBlockOrigin/uAssets#25485]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.sport1.de/`

### Category

ads

### Description

Seems like ubo doesnt block ads on this site anymore. It worked fine yesterday tho... I would gladly provide a screenshot of the website but it seems I'm to stupid figuring out how to upload one here..

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 152297
 cosmetic: 53582
 scriptlet: 21068
 html: 2001
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  ublock-filters: 40548-138, now
  ublock-badware: 11175-6, now
  ublock-privacy: 1259-22, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 126-2, now
  easylist: 85595-185, now
  easyprivacy: 53112-40, now
  urlhaus-1: 25105-0, now
  plowe-0: 3546-993, now
  DEU-0: 7520-37, now
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 5196 ms
 maxAssetCacheWait: 2877 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 69
 network:
  sport1.de: 15
  abtasty.com: 1
  adscale.de: 3
  amazon-adsystem.com: 3
  aniview.com: 4
  apester.com: 15
  batch.com: 6
  chartbeat.com: 2
  cxense.com: 1
  doubleclick.net: 4
  ebxcdn.com: 2
  edioca.com: 1
  googletagmanager.com: 1
  hotjar.com: 1
  m6r.eu: 1
  mookie1.com: 1
  outbrain.com: 1
  rubiconproject.com: 3
  theadex.com: 1
  undom.net: 1
  userreport.com: 1
  yieldlove.com: 1
 extended:
  ##.s1-ad
  ##+js(addEventListener-defuser, load, hard_block)
```
</details>

**Comment by JobcenterTycoon** [comment]
@alex-302 i get the same on Adguard

**Comment by angrypeestain** [comment]
why is this closed?

**Comment by stephenhawk8054** [comment]
![image](https://github.com/user-attachments/assets/94e75feb-45fa-49bc-bb01-82f8a6eea990)

It's fixed in https://github.com/uBlockOrigin/uAssets/commit/e8c3ba7d2a362d7a12b7d243843a6978beb3e093

Update your filter lists again.

**Comment by angrypeestain** [comment]
oh thats tricky to spot ... thanks tho
