### ISSUE TITLE
picrew.me: ads

### ISSUE THREAD

**Issue by DrLycFerno** [uBlockOrigin/uAssets#25483]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://picrew.me/en/image_maker/614903`

### Category

ads

### Description

There still is an ad under the Picrew despite blocking it over and over again.

### Other extensions used

AdBlock Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 127
filterset (summary):
 network: 168244
 cosmetic: 55060
 scriptlet: 22800
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40277-146, 1m
  ublock-badware: 11176-6, 1m
  ublock-privacy: 1292-22, 1m
  ublock-unbreak: 2480-0, 1m
  ublock-quick-fixes: 145-0, 1m
  easylist: 85612-691, 1m
  easyprivacy: 53111-768, 1m
  urlhaus-1: 25105-0, 1m
  plowe-0: 3546-0, 1m
  FRA-0: 25595-372, 1m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16349 ms
 maxAssetCacheWait: 47 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  html-load.com: 3
 extended:
  ##.play-Imagemaker_Footer
```
</details>

**Comment by gorhill** [comment]
Post a screenshot of the page with the ad highlighted so that we know what is the issue. I can't see any ad when using default settings/lists and no other extension.

**Comment by Yuki2718** [comment]
> AdBlock Plus

![warning](https://github.com/user-attachments/assets/052f81bf-dc2e-4fbe-aae9-5ad55d85d0a8)

> despite blocking it over and over again.

Sure, as the picker is an assistant tool for filter author and not a magic wand.
