### ISSUE TITLE
gidadedektifi.com: ads

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25480]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gidadedektifi.com/gundem/coca-cola-yaninda-ucretsiz-verilen-firma-isbirligini-inkar-etti-soz-konusu-firmaya-bir-iliskimiz-yoktur-5608`

### Category

ads

### Description

there are advertising leftovers. so there is extra unnecessary white space

### Other extensions used

localcdn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20240930_175713](https://github.com/user-attachments/assets/09d68982-5e30-4cfb-80e9-b88cbba1d909)
![Screenshot_20240930_175657](https://github.com/user-attachments/assets/ede1676e-8a2e-4f88-965f-0d288cd1e4fa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 131
filterset (summary):
 network: 152943
 cosmetic: 65691
 scriptlet: 24032
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40787-368, now
  ublock-badware: 11170-6, now
  ublock-privacy: 1288-22, now
  ublock-unbreak: 2483-0, now
  ublock-quick-fixes: 145-0, now
  adguard-mobile: 9854-97, now
  easylist: 85567-645, now
  easyprivacy: 53111-650, now
  urlhaus-1: 25255-0, now
  plowe-0: 3546-0, now
  TUR-0: 11417-21, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3118 ms
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
```
</details>

**Comment by Raidware** [comment]
also same on mainpage "https://gidadedektifi.com/"

![Screenshot_20240930_180533](https://github.com/user-attachments/assets/1dbaf929-27e6-4152-8a19-b135dff5e14a)
![Screenshot_20240930_180516](https://github.com/user-attachments/assets/167947b3-f666-4a51-b751-2ab35fd39fd7)

**Comment by gorhill** [comment]
This needs to be fixed in AdGuard Turkish:

    gidadedektifi.com##[class^="XAd_"]

**Comment by Raidware** [comment]
@alexbcberio

**Comment by Raidware** [comment]
Working. Maybe alex looks adguard turkish

**Comment by Raidware** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Added.
