### ISSUE TITLE
devuploads.com: ads leftover

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25496]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://devuploads.com/2hrkd2vw1ogb`

### Category

ads leftover

### Description

`There is other issues about this website but about detection`. Blank white space of ads leftover with a small button "advertise here" bottom right corner of each leftover.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG_20241002_094658](https://github.com/user-attachments/assets/871ba784-09f6-4642-8109-df6d68824195)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 130
filterset (summary):
 network: 400711
 cosmetic: 254363
 scriptlet: 56015
 html: 2278
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 136770-0, 7m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 437-1, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 409-36, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 85142-40506, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  adguard-generic: 84527-8774, now
  adguard-spyware-url: 1721-126, now
  block-lan: 71-0, now
  curben-phishing: 604-12, now
  fanboy-cookiemonster: 52226-202, now
  ublock-annoyances: 5945-147, 7m Δ
  IND-0: 13572-52, now
  [12 lists not shown]: [too many]
 default:
  ublock-filters: 41099-337, 7m Δ
  ublock-badware: 11199-1010, 7m Δ
  ublock-privacy: 1265-50, 7m Δ
  ublock-unbreak: 2540-3, 7m Δ
  ublock-quick-fixes: 134-15, 7m Δ
  adguard-mobile: 9817-782, now
  easylist: 85667-29943, 7m Δ
  easyprivacy: 53116-9548, 7m Δ
  urlhaus-1: 24475-258, now
  plowe-0: 3546-2968, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 640 ms (selfie)
 maxAssetCacheWait: 304 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(no-window-open-if, _blank)
  ##+js(trusted-replace-node-text, script, window._country, '/*sta…
  ##+js(addEventListener-defuser, DOMContentLoaded, antiAdBlockerH…
  ##+js(no-xhr-if, /adtrue\.com|eningspon\.com|freychang\.fun|orqu…
  ##+js(prevent-fetch, /a-mo\.net|adnxs\.com|prebid|creativecdn\.c…
```
</details>

**Comment by JobcenterTycoon** [comment]
The space can’t be fixed.

**Comment by Rachitidk** [comment]
Reopen the issue, ads leftover still present.
![IMG_20241003_101644](https://github.com/user-attachments/assets/a9493b41-78a8-484a-a537-a4371a9a21da)

All updated

**Comment by Rachitidk** [comment]
Reopen the issue.
![IMG_20241003_101831](https://github.com/user-attachments/assets/72daa131-92cc-440f-946e-ab4aada9ca68)
All updated.

**Comment by Rachitidk** [comment]
Reopen this issue, not yet fixed

**Comment by JobcenterTycoon** [comment]
Its all fixed with latest filter.

**Comment by Rachitidk** [comment]
> Its all fixed with latest filter.

Updated just now, not fixed yet.

**Comment by JobcenterTycoon** [comment]
Its caused by the Adguard base List @Yuki2718

**Comment by JobcenterTycoon** [comment]
I mean all the whitelist filter are uneeded on my end (except the ghide)

**Comment by Yuki2718** [comment]
> I mean all the whitelist filter are obsolete on my end (except the ghide) and they cause placeholder and the one picture ad in uBO.

But they might be needed for iOS/Content blocker. I'll exclude uBO then.

**Comment by JobcenterTycoon** [comment]
Test link is `https://hyp.sh/y8mfgHOl`

i don’t know if spoof-css works, i just tested with ghide and the hiding filter and it worked.

**Comment by Rachitidk** [comment]
https://github.com/user-attachments/assets/7ddb5770-f561-4d9b-b917-90bbbd5e1bcf

**Comment by Rachitidk** [comment]
Will the popup ads on click in blank space m also be blocked?

**Comment by JobcenterTycoon** [comment]
@Yuki2718 many filter are still not excluded like `#@##featuredimage`

**Comment by Yuki2718** [comment]
> many filter are still not excluded like `#@##featuredimage`

https://github.com/AdguardTeam/AdguardFilters/commit/1b276c6a454610e11487785c22068a0a8ed52238

**Comment by Rachitidk** [comment]
This ads can't be removed?

https://github.com/user-attachments/assets/c2b35b0e-2ba2-4565-b760-a1190547eb8e

**Comment by JobcenterTycoon** [comment]
There is no ad with default config. Also the issue with the Adguard base list is fixed already.

**Comment by Rachitidk** [comment]
Working, thank you very much.

> There is no ad with default config. Also the issue with the Adguard base list is fixed already. If its still not working after a update try `djxmaza.in,jytechs.in,miuiflash.com,thecubexguide.com###featuredimage:style(display: none !important;)`

**Comment by Rachitidk** [comment]
> There is no ad with default config. Also the issue with the Adguard base list is fixed already. If its still not working after a update try `djxmaza.in,jytechs.in,miuiflash.com,thecubexguide.com###featuredimage:style(display: none !important;)`

Add this filter to the main list.

**Comment by JobcenterTycoon** [comment]
EasyList already contains `djxmaza.in,jytechs.in,miuiflash.com,thecubexguide.com###featuredimage`. When the element still appear its pretty sure whitelisted by one of the filterlists you enabled. We don’t fix issues caused by a other filterlists.

`djxmaza.in,jytechs.in,miuiflash.com,thecubexguide.com###featuredimage:style(display: none !important;)` just bypassing the whitelist. You can find the filterlist which causing this by disabling custom filterlists once by once and test until you found the filterlist. Then you can open a issue.

**Comment by Rachitidk** [comment]
Working now, expect for his redirect to `https://djxmaza.in/`

https://github.com/user-attachments/assets/cc2a2292-06ec-4c56-bb23-1e9d3dfca8ad

Thanks

**Comment by JobcenterTycoon** [comment]
Its done already.

**Comment by Rachitidk** [comment]
Not working for djxmaza.in
![1000106400](https://github.com/user-attachments/assets/878744bf-24f8-40ca-a59c-90294ae90d62)

**Comment by Rachitidk** [comment]
@JobcenterTycoon 
Tried to clone firefox with only ublock present 
Not working when website redirect to djxmaza.in, it works when get redirected to thecubexguide, jytechs.

**Comment by Rachitidk** [comment]
Reopen this issue, it not working for djxmaza, It has been 3 day not getting any reply. @JobcenterTycoon sorry for tagging.

**Comment by BlazeFTL** [comment]
@Rachitidk Reset UBO To Default & Use Default UBO Filters

**Comment by Rachitidk** [comment]
> @Rachitidk Reset UBO To Default & Use Default UBO Filters
Found the problem, the problem is with `adguard - ads` in ublock
![1000107503](https://github.com/user-attachments/assets/37c77a96-272d-4f53-a665-062bfc0f78e5)

**Comment by Rachitidk** [comment]
Will this be solved by adguard lists, or I have to keep it disabled.

**Comment by BlazeFTL** [comment]
You Really Dont Need Adguard List...Ublock Default List Are More Than Enough To Block 99% Ads On This World...If You See Ads With Default List Just Report Here It Will Be Fixed
