### ISSUE TITLE
investopedia.com: breakage

### ISSUE THREAD

**Issue by myclevorname** [uBlockOrigin/uAssets#25499]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.investopedia.com/simulator/games/my-games`

### Category

breakage

### Description

"GraphQL error: Something went wrong" replacing the list of games. The configuration notes I had some custom rules, but I disabled them after starting the submission of this issue, making sure to see if it still worked. I have every filter list shown in the `Filter Lists` tab enabled.

I had to lie on the additional filters/rules because of [the issue with this template](https://github.com/uBlockOrigin/uBlock-issues/issues/3397).

### Other extensions used

Ctrl+Number to switch tabs
Auto Tab Discard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![20241002_15h11m09s_grim](https://github.com/user-attachments/assets/99c793a8-9442-4342-8ae4-cda08b6a7cd3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 337815
 cosmetic: 387091
 scriptlet: 59972
 html: 2420
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84566-4213, now
  adguard-mobile: 9822-59, now
  adguard-spyware-url: 1721-126, now
  adguard-spyware: 85369-1552, now
  block-lan: 71-0, now
  curben-phishing: 561-0, now
  adguard-cookies: 32060-61, now
  ublock-cookies-adguard: 1785-28, now
  fanboy-cookiemonster: 52226-4028, now
  ublock-cookies-easylist: 1785-1785, now
  adguard-social: 23167-52, now
  fanboy-social: 17142-765, now
  [47 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 40568-131, now
  ublock-badware: 11258-6, now
  ublock-privacy: 1264-22, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 134-13, now
  easylist: 85678-2198, now
  easyprivacy: 53116-23637, now
  urlhaus-1: 24765-0, now
  plowe-0: 3546-1492, 1m
filterset (user): [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 912 ms (selfie)
 maxAssetCacheWait: 744 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  cookielaw.org: 1
  doubleclick.net: 2
  hotjar.com: 1
  p-n.io: 1
  proper.io: 1
  sentry.io: 12
  zdassets.com: 1
 extended:
  ##.logo-ad
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@myclevorname 

add

`@@||static.zdassets.com/ekr/snippet.js$script,domain=investopedia.com`

@ryanbr EasyList – Other Annoyances issue
