### ISSUE TITLE
Anilinkz.to has new Adblock Detector

### ISSUE THREAD

**Issue by Aizaniri** [uBlockOrigin/uAssets#2549]
### Url

www.anilinkz.to

### Describe the issue

Site has a new Adblock detector

### Versions

- Browser/version: 53.0.2907.99
- uBlock Origin version: v1.16.6

### Settings

- activate all Filters

**Comment by uBlock-user** [comment]
```
anilinkz.to##.advid.james
anilinkz.to###jade
anilinkz.to##script:inject(set-constant.js, daganKwarta, true)
```

**Comment by Aizaniri** [comment]
"
anilinkz.to##.advid.james
anilinkz.to###jade
anilinkz.to##script:inject(set-constant.js, daganKwarta, true)
"


Where do i add this?

**Comment by uBlock-user** [comment]
in _My Filters_ or wait till a volunteer adds it to uBlock Filters.

**Comment by Aizaniri** [comment]
Thank you so much, works fine :)
