### ISSUE TITLE
mangareader.to: ads

### ISSUE THREAD

**Issue by usedtoliveonmars** [uBlockOrigin/uAssets#25494]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mangareader.to/`

### Category

ads

### Description

Ads are being blocked but it will still pop up with a redirect option to ad website. This only happens on mobile: 

`https://doruffleton.com/4/5594791`

Because of the following filter:

/^https?:\/\/(?:ak\.)?[a-z]{6,12}\.(?:com|net)\/4\/\d{7}/$document
Found in:

    uBlock filters – Ads
     

Don't warn me again about this site

### Other extensions used

Privacy badger. However even when disabling it, the issue still shows.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241001-214957](https://github.com/user-attachments/assets/f2501843-88a4-4299-b729-c4ec22d6ad18)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox Mobile: 133
filterset (summary):
 network: 151609
 cosmetic: 57016
 scriptlet: 21174
 html: 2002
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41090-214, 6m Δ
  ublock-badware: 11198-7, 6m Δ
  ublock-privacy: 1265-22, 6m Δ
  ublock-unbreak: 2540-3, 6m Δ
  ublock-quick-fixes: 134-13, 6m Δ
  adguard-mobile: 9815-11, 1m
  easylist: 85661-260, 6m Δ
  easyprivacy: 53113-71, 6m Δ
  urlhaus-1: 25255-0, 6m
  plowe-0: 3546-1067, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 468 ms (selfie)
 maxAssetCacheWait: 104 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  doruffleton.com: 1
  googletagmanager.com: 1
  oygoctluxqrhv.com: 3
 extended:
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by JobcenterTycoon** [comment]
Can also reproduce on firefox desktop. Should be fixed now.
