### ISSUE TITLE
KnowYourMeme HTML ads

### ISSUE THREAD

**Issue by Rudxain** [uBlockOrigin/uAssets#25493]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://knowyourmeme.com/memes/*
```

### Description

EasyList has this generic filter:
```adblock
##.ad-unit-wrapper
```
But it would be better if it was a specific HTML filter:
```adblock
knowyourmeme.com##^.ad-unit-wrapper
```

### Other extensions used

DarkReader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 128
filterset (summary):
 network: 256414
 cosmetic: 221208
 scriptlet: 55034
 html: 2269
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84527-4560, 3h.54m
  adguard-mobile: 9815-91, 3h.54m
  adguard-spyware-url: 1721-126, 3h.54m
  adguard-spyware: 85366-1568, 3h.51m
  block-lan: 71-0, 17d.15h.10m
  curben-phishing: 508-1, 3h.55m
  adguard-cookies: 32038-1682, 3h.54m
  ublock-cookies-adguard: 1774-28, 3d.5h.1m
  fanboy-cookiemonster: 52156-19884, 3d.5h.1m
  ublock-cookies-easylist: 1771-1771, 3d.5h.1m
  adguard-social: 23157-1237, 3h.54m
  fanboy-social: 17106-11006, 3d.5h.1m
  [13 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  ublock-filters: 40582-322, 24m Δ
  ublock-badware: 11204-11, 24m Δ
  ublock-privacy: 1264-23, 24m Δ
  ublock-unbreak: 2537-3, 24m Δ
  ublock-quick-fixes: 134-13, 24m Δ
  easylist: 85657-16140, 24m Δ
  easyprivacy: 53113-23656, 24m Δ
  urlhaus-1: 25255-0, 3h.55m
filterset (user): [array of 6 redacted]
trustedset:
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 64 redacted]
hostRuleset:
 added: [array of 67 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 largeMediaSize: 16
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7304 ms
 maxAssetCacheWait: 5928 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 no-large-media: true
 no-scripting: true
 network:
  beehiiv.com: 1
  blogherads.com: 4
  browsiprod.com: 2
  googletagmanager.com: 2
  kym-cdn.com: 2
  p-n.io: 2
 extended:
  ##.fb-page-like
  ##.floating-share-bar
  ##.shopify-container
  ##.beehiiv-newsletter-signup-container
  ##+js(abort-current-script, document.createElement, admiral)
  ##+js(no-setInterval-if, blogherads)
  ##+js(nofab)
  ##+js(abort-current-script, document.createElement, '/admiral|St…
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue in your discussion thread. No need to open an issue thread about it. HTML filtering forces the site to reload again, so we only use it for tough cases of ads / anti-adb..., not for visual annoyance.

**Comment by Rudxain** [comment]
> Please continue in your discussion thread.

[This one?](https://github.com/uBlockOrigin/uBlock-issues/discussions/3395) That's only tangentially/orthogonally related, not a dupe 😕

> HTML filtering forces the site to reload again, so we only use it for tough cases

I understand now, thanks for explaining. It'd be nice if that caveat was mentioned in [The Wiki page](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#html-filters)
