### ISSUE TITLE
[nsfw] now.gg: detection

### ISSUE THREAD

**Issue by melqueen8273** [uBlockOrigin/uAssets#25498]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://now.gg/`

### Category

detection

### Description

can you unblocked now.gg

### Other extensions used

Roblox.com

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 149734
 cosmetic: 48431
 scriptlet: 22679
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40298-262, 28m
  ublock-badware: 11207-6, 28m
  ublock-privacy: 1283-22, 28m
  ublock-unbreak: 2479-0, 29m
  ublock-quick-fixes: 139-0, 29m
  easylist: 85669-577, 29m
  easyprivacy: 53116-642, 29m
  urlhaus-1: 24765-0, 29m
  plowe-0: 3546-0, 29m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3092 ms
 maxAssetCacheWait: 28 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by melqueen8273** [comment]
unblocked now.gg pls

**Comment by stephenhawk8054** [comment]
Describe the steps to reproduce the issue. The site appears normal for me

![image](https://github.com/user-attachments/assets/0cb322af-8b27-4ecf-a9d9-28e4c448911f)

**Comment by drippypop** [comment]
If something's wrong, just whitelist the site.
