### ISSUE TITLE
cumhuriyet.com.tr: breakage

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25491]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cumhuriyet.com.tr/gundem`

### Category

breakage

### Description

ublockorigin breaks the website. Also "Daha fazla haber göster" button broken

### Other extensions used

localcdn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241001_164101](https://github.com/user-attachments/assets/78376aba-3ee7-4c4f-a625-6ef0dfadf329)
![Screenshot_20241001_164049](https://github.com/user-attachments/assets/9823b231-99c3-4a64-9523-e125ae0325d9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 131
filterset (summary):
 network: 236319
 cosmetic: 192336
 scriptlet: 39806
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1721-125, now
  adguard-spyware: 85363-24262, now
  block-lan: 64-0, now
  curben-phishing: 520-0, now
  adguard-cookies: 32028-87, now
  ublock-cookies-adguard: 1823-9, now
  fanboy-cookiemonster: 52226-4096, now
  ublock-cookies-easylist: 1823-1823, now
  adguard-popup-overlays: 28038-975, now
  adguard-mobile-app-banners: 5496-1133, now
  adguard-other-annoyances: 14637-378, now
  adguard-widgets: 2674-46, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 40849-747, 31m Δ
  ublock-badware: 11191-10, 31m Δ
  ublock-privacy: 1300-22, 31m Δ
  ublock-unbreak: 2482-5, 31m Δ
  ublock-quick-fixes: 139-0, 31m Δ
  adguard-mobile: 9815-11, now
  easylist: 85634-890, 31m Δ
  easyprivacy: 53111-850, 31m Δ
  urlhaus-1: 24945-0, now
  plowe-0: 3546-83, now
  TUR-0: 11422-26, now
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4620 ms
 maxAssetCacheWait: 1417 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  cumhuriyet.com.tr: 3
  bik.gov.tr: 1
  clarity.ms: 2
  cloudflareinsights.com: 1
  doubleclick.net: 1
  google.com: 1
  googlesyndication.com: 4
  googletagmanager.com: 1
  mrf.io: 1
  netmera-web.com: 2
  newsroom.bi: 2
  taboola.com: 1
  yandex.ru: 1
 extended:
  ##.row > div.col-xs-12:has(> div[id^="div-gpt-ad"])
  ##div[class^="col-sm-"] > div.row:has(> div > div[id^="div-gpt-a…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##body:style(overflow: auto !important;)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
cumhuriyet.com.tr##.row > div.col-xs-12:has(> div[id^="div-gpt-ad"])
cumhuriyet.com.tr##div[class^="col-sm-"] > div.row:has(> div > div[id^="div-gpt-ad"])
```

in Adguard Turkish list.

cc @Alex-302

**Comment by Alex-302** [comment]
Done. Thanks.

**Comment by Raidware** [comment]
@stephenhawk8054 @Alex-302 still broken in mobile view

**Comment by Alex-302** [comment]
Fixed again)
