### ISSUE TITLE
seznam.cz: nuisance

### ISSUE THREAD

**Issue by Houfino** [uBlockOrigin/uAssets#25509]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.seznam.cz/`

### Category

ads

### Description

I wanted to enter seznam.cz and it shows me 
![seznam cz](https://github.com/user-attachments/assets/ff6aa9a1-d0b3-4d7b-b2e2-985452b48381)

### Other extensions used

I still dont care about cookies + Ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 128
filterset (summary):
 network: 152371
 cosmetic: 94795
 scriptlet: 27244
 html: 2006
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52230-126, 5m
  ublock-cookies-easylist: 1785-13, 5m
 default:
  user-filters: 0-0, never
  ublock-filters: 40581-143, 1h.46m Δ
  ublock-badware: 11570-6, 1h.46m Δ
  ublock-privacy: 1270-22, 1h.46m Δ
  ublock-unbreak: 2537-3, 1h.46m Δ
  ublock-quick-fixes: 144-15, 1h.46m Δ
  easylist: 85699-187, 1h.46m Δ
  easyprivacy: 53129-108, 1h.46m Δ
  urlhaus-1: 24860-0, 22m
  plowe-0: 3546-993, 5m
  CZE-0: 844-12, 22m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1451 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  seznam.cz: 12
  adnxs.com: 1
  criteo.com: 1
  id5-sync.com: 1
  pubmatic.com: 1
 extended:
  ##+js(no-setTimeout-if, 0x)
  ##+js(trusted-set-cookie, euconsent-v2, CP-wiwAP-wiwAD3ACLCSA1Es…
  ##+js(abort-on-property-write, Fisher)
  ##+js(addEventListener-defuser, message, fishing)
```
</details>

**Comment by Houfino** [comment]
No one? Interesting that it worked before.....Now it doesn't work...strange.

**Comment by mapx-** [comment]
test

`cmp.seznam.cz##+js(trusted-click-element, .szn-cmp-dialog-container >>> button[data-testid="cw-button-non-targeted-ad"], , 500)`

**Comment by Houfino** [comment]
> test
> 
> ```
> cmp.seznam.cz##+js(trusted-click-element, .szn-cmp-dialog-container >>> button[data-testid="cw-button-non-targeted-ad"], , 500)
> ```

add to "your filter", right?

**Comment by mapx-** [comment]
yes, and be sure **Allow custom filters requiring trust** is enabled

**Comment by Houfino** [comment]
> yes, and be sure **Allow custom filters requiring trust** is enabled

It doesn't work...It still shows :-/

![Screenshot 2024-10-04 at 12-12-41 uBlock₀ — Ovládací panel](https://github.com/user-attachments/assets/3d398aa0-c37a-4a63-b42d-5e62d236cc83)

**Comment by stephenhawk8054** [comment]
@Houfino You are disabling "My filters". Tick on the 1st checkbox to enable it

**Comment by mapx-** [comment]
@Houfino 

keep the filter above and enable this list too:
`AdGuard/uBO – Cookie Notices`

**Comment by Houfino** [comment]
It doesn't work.. Probably the end :-/

They worked about 3-4 months ago.. We already solved it... now it doesn't work anymore....

https://github.com/uBlockOrigin/uAssets/issues/23727

**Comment by stephenhawk8054** [comment]
Just comment in 1 thread. No need to ping in multiple threads.

Test again in a new Firefox profile with only uBO and its default settings + `EasyList/uBO – Cookie Notices` list

**Comment by mapx-** [comment]
firefox is terribly slow with this site

for the trusted-click-element above I get often "timed out"

`[about:blank][trusted-click-element ⁝ .szn-cmp-dialog-container >>> button[data-testid="cw-button-non-targeted-ad"] ⁝  ⁝ 500] Timed out`


maybe using 1000 

test

    cmp.seznam.cz##+js(trusted-click-element, .szn-cmp-dialog-container >>> button[data-testid="cw-button-non-targeted-ad"], , 1000)
