### ISSUE TITLE
us.creative.com: breakage

### ISSUE THREAD

**Issue by Necessarycoot72** [uBlockOrigin/uAssets#25500]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://us.creative.com/p/sound-blaster/sound-blaster-ae-7`

### Category

breakage

### Description

The images don't load in the image gallery. 

Steps to reproduce:

Click the small product images, as seen on image two.

If uBlock is enabled, the images won't load, as in image one.

### Other extensions used

Violentmonkey (no scrips are running)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/953eed2e-8125-41f7-b660-642aea0ba87a)
![image](https://github.com/user-attachments/assets/71411294-4abf-4913-9bf5-e9d4de6aa7b4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 131
filterset (summary):
 network: 133470
 cosmetic: 150396
 scriptlet: 35255
 html: 2263
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  https://raw.githubusercontent.com/bpc-clone/bypass-paywalls-clean-filters/main/bpc-paywall-filter.txt: 1106-0, never
  fanboy-cookiemonster: 52226-126, now
  ublock-cookies-easylist: 1785-13, now
  adguard-popup-overlays: 28064-244, 43m
  adguard-mobile-app-banners: 5509-26, 43m
  adguard-other-annoyances: 14658-331, 43m
  adguard-widgets: 2685-13, 43m
  easylist-annoyances: 4799-294, now
  easylist-chat: 216-17, now
  easylist-newsletters: 7913-581, now
  easylist-notifications: 3442-1556, now
  ublock-annoyances: 5922-211, 1h.43m Δ
 default:
  user-filters: 6-1, never
  ublock-filters: 40568-143, 1h.43m Δ
  ublock-badware: 11258-6, 1h.43m Δ
  ublock-privacy: 1264-22, 1h.43m Δ
  ublock-unbreak: 2538-3, 1h.43m Δ
  ublock-quick-fixes: 134-13, 1h.43m Δ
  easylist: 85669-188, 1h.43m Δ
  easyprivacy: 53116-110, 1h.43m Δ
  plowe-0: 3546-993, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6206 ms (selfie)
 maxAssetCacheWait: 195 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  browser-update.org: 1
  google-analytics.com: 2
  googletagmanager.com: 1
  typekit.net: 1
  zdassets.com: 2
 extended:
  ##.ck-notiz
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
add

`||zdassets.com/ekr/snippet.js$badfilter`

EasyList – Other Annoyances issue @ryanbr
