### ISSUE TITLE
911it.com: breakage

### ISSUE THREAD

**Issue by hackerTiger21** [uBlockOrigin/uAssets#25503]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://911it.com/`

### Category

breakage

### Description

Upon loading the website with uBlock Origin enabled, the page only shows white, even though the HTML document shows that there are indeed elements present. 

Loading the website without uBlock enabled results in the proper page being shown. Re-enabling uBlock and reloading the website in the same tab results in a properly rendered page, with slight differences in the filter list (most notably the `myfonts.net` domain). This cannot be reproduced in a new tab without disabling uBlock first.

### Other extensions used

Simple Tag Groups: https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/
FoxyTab: https://addons.mozilla.org/en-US/firefox/addon/foxytab/
Search By Image: https://addons.mozilla.org/en-US/firefox/addon/search_by_image/
Pomodoro clock extension: https://addons.mozilla.org/en-US/firefox/addon/pomodoro-clock/
Tampermonkey: https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/
(Note: the reported website does not run any user scripts installed on Tampermonkey)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Filter list upon initial load with uBlock enabled
![image](https://github.com/user-attachments/assets/aaf7a303-0a4b-4c6d-ba57-b39bbde5e27b)

Filter list when page is loaded with uBlock disabled, uBlock gets re-enabled, and the page is reloaded in the same tab
![image](https://github.com/user-attachments/assets/2e1715f3-ed0c-42af-bf85-1603d4b2f1df)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 149778
 cosmetic: 48434
 scriptlet: 21098
 html: 2001
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 40568-131, now
  ublock-badware: 11258-6, now
  ublock-privacy: 1264-22, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 134-13, now
  easylist: 85678-186, now
  easyprivacy: 53116-62, now
  urlhaus-1: 24765-0, now
  plowe-0: 3546-993, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 526 ms
 maxAssetCacheWait: 218 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  app-us1.com: 1
  googletagmanager.com: 3
  infusionsoft.app: 3
  licdn.com: 1
  maps.googleapis.com: 2
  myfonts.net: 1
  stripe.com: 9
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by hackerTiger21** [comment]
> Test again in a new Firefox profile with only uBO and its default settings.

Just did, same behavior as previously detailed.

**Comment by stephenhawk8054** [comment]
In the new profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

Then can you go to `about:addons` page (type in URL bar) and screenshot it here?

**Comment by hackerTiger21** [comment]
```uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 149892
 cosmetic: 48426
 scriptlet: 21097
 html: 2001
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40572-131, 1m
  ublock-badware: 11262-6, 1m
  ublock-privacy: 1286-22, 1m
  ublock-unbreak: 2539-1, 1m
  ublock-quick-fixes: 134-13, 1m
  easylist: 85667-186, 1m
  easyprivacy: 53113-62, 1m
  urlhaus-1: 24860-0, 1m
  plowe-0: 3546-993, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1502 ms
 maxAssetCacheWait: 35 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  app-us1.com: 1
  googletagmanager.com: 3
  infusionsoft.app: 2
  licdn.com: 1
  maps.googleapis.com: 2
  myfonts.net: 1```

![image](https://github.com/user-attachments/assets/6dcb523b-4e9d-4423-9af6-239e6d2080c9)

**Comment by hackerTiger21** [comment]
![image](https://github.com/user-attachments/assets/6dcb523b-4e9d-4423-9af6-239e6d2080c9)

**Comment by stephenhawk8054** [comment]
@hackerTiger21 Which country are you when accessing the site?

**Comment by hackerTiger21** [comment]
United States

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. The page appears normal for me

![image](https://github.com/user-attachments/assets/82466919-b99d-4901-b6d7-769e596f591e)

**Comment by hackerTiger21** [comment]
This is what I'm getting on initial load.
![image](https://github.com/user-attachments/assets/1ee5730b-136c-4018-beea-104f969a7b8d)

**Comment by stephenhawk8054** [comment]
I still can't reproduce it so I can't investigate more.

**Comment by hackerTiger21** [comment]
There were a lot of console errors both with and without uBlock enabled, it's possible that it's an issue that has to be fixed with the site itself.
