### ISSUE TITLE
seclore.com: breakage

### ISSUE THREAD

**Issue by Pat-willi** [uBlockOrigin/uAssets#25504]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.seclore.com/why-seclore/customer-stories/
```

### Description

Ublock is breaking the case studies section on one of our company pages. It displays as a white bar with no content filled. I have attached two images, 1st how it displays with ublock turned off. 2nd is with ublock on.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![seclore_CaseStudy_brokentile](https://github.com/user-attachments/assets/0ae911fa-ae3f-4472-bbb9-a5aa71d4ef13)

![seclore_CaseStudy_brokentile2](https://github.com/user-attachments/assets/ac59f890-5d7e-4d75-9857-20bd1a0d5d64)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 149492
 cosmetic: 48430
 scriptlet: 22678
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40289-262, 3h.59m Δ
  ublock-badware: 11260-6, 3h.59m Δ
  ublock-privacy: 1283-22, 3h.59m Δ
  ublock-unbreak: 2480-0, 3h.59m Δ
  ublock-quick-fixes: 139-0, 3h.59m Δ
  easylist: 85668-577, 3h.59m Δ
  easyprivacy: 53116-647, 3h.59m Δ
  urlhaus-1: 24475-0, 20h.36m
  plowe-0: 3553-0, 6d.22h.50m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 716 ms (selfie)
 maxAssetCacheWait: 455 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||api.omappapi.com/v3/geolocate/json$xhr,domain=seclore.com
```

@ryanbr
