### ISSUE TITLE
streamsilk.com: popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#25510]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://streamsilk.com/d/66fef1e5f0d37`

### Category

popups

### Description

clicking 480/720 generates new popup window which is closed due to matching EL filter

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241004-013110-381](https://github.com/user-attachments/assets/18d404de-bba9-49df-a291-e9eb509029d0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 133
filterset (summary):
 network: 151321
 cosmetic: 57025
 scriptlet: 21199
 html: 2003
listset (total-discarded, last-updated):
 default:
  user-filters: 14-0, never
  ublock-filters: 41078-216, 2m Δ
  ublock-badware: 11256-7, 2m Δ
  ublock-privacy: 1271-22, 2m Δ
  ublock-unbreak: 2540-3, 2m Δ
  ublock-quick-fixes: 159-13, 2m Δ
  adguard-mobile: 9828-11, now
  easylist: 85686-259, 2m Δ
  easyprivacy: 53129-71, 2m Δ
  urlhaus-1: 24860-0, now
  plowe-0: 3546-1068, now
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1059 ms (selfie)
 maxAssetCacheWait: 361 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  vklljvzzezvy.top: 3
  yandex.ru: 1
 extended:
  ##.div_pop
  ###pop.div_pop
  ##+js(addEventListener-defuser, click, pop)
  ##+js(trusted-set-constant, premium, "'1'")
  ##+js(no-window-open-if)
  ##+js(no-setTimeout-if, window.open)
  ##+js(trusted-replace-node-text, script, /openNewTab\(".*?"\)/g,…
```
</details>

**Comment by D4niloMR** [comment]
The code responsible for the popup is in the first lines in `https://streamsilk.com/build/assets/download-BFOXNMjL.js`

This works here:
```
streamsilk.com##+js(set, HTMLElement.prototype.click, noopFunc)
```

**Comment by stephenhawk8054** [comment]
I think we can limit the element to anchor elements only

```adb
streamsilk.com##+js(set, HTMLAnchorElement.prototype.click, noopFunc)
```

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/commit/95b0ce5e3a64d966924dd701d1e336402d586b25>. This should work:

`streamsilk.com##+js(trusted-override-element-method, HTMLAnchorElement.prototype.click, a[target="_blank"][style])`

**Comment by gorhill** [comment]
> how to see which specific elements it has overrided(if its possible)?

The only way I can think of is to output the element at the console. Maybe this could be done when verbose mode is enabled?

**Comment by gorhill** [comment]
You will never see elements themselves in the logger, elements or element references are not serializable, they can't be transported across document. We can output an element to the browser dev console, and from there the browser tools will let you find it in the DOM. In any case, the element is removed from the DOM immediately by the page code, so it's not very useful. Triggering a breakpoint in the code when the override occurs is a better approach, because it will let you examine the element while it still is in the DOM.

**Comment by gorhill** [comment]
Anyway, how do I trigger the filter on that site? I don't get a report that the method was overridden.

**Comment by gorhill** [comment]
Next build you can try `abysscdn.com##+js(trusted-override-element-method, HTMLAnchorElement.prototype.click, a[target="_blank"], debug)` with logger opened to trigger a breakpoint in the scriptlet. The element should still be part of the DOM, and you can examine the caller's code to se what they are doing.

**Comment by gorhill** [comment]
With the new `debug` disposition value, I could break into the scriptlet code at override time. Had to use Anti Anti Debug extension. To my surprise, the `a` element is not part of the DOM, I thought this was a requirement for the `click()` method to work. Anyway, when the breakpoint triggers, you can inspect the element properties and the caller's code:

<details><summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/d9982d2f-2c9a-4dac-a14c-f71de0621987)

![image](https://github.com/user-attachments/assets/6c22e1f1-e137-42ca-ba7d-bd648594d86d)
</details>

**Comment by gorhill** [comment]
Forgot about `disable-newtab-links` but anyway this one acts on all `click` events, including legitimate (`isTrusted` is `true`) ones by the user, while specifically trapping `click()` targets non-trusted clicks, and the new scriptlet also allows to narrow down further using a selector, and is more logger friendly.

**Comment by gorhill** [comment]
Why invest time on this unless there are actual cases to solve?

**Comment by gorhill** [comment]
`abysscdn.com##+js(disable-newtab-links)` does not work, need to specifically trap `click()`.

**Comment by gorhill** [comment]
I just reproduce successfully. Did you enable `debugger` statement in dev tools?

![image](https://github.com/user-attachments/assets/290cc4a9-c5bd-46bb-947f-c9a563f0b21d)

My steps:
- Enable Anti Anti Debug
- Add `abysscdn.com#@#+js(aost, HTMLElement.prototype.click, _0x)`
- Add `abysscdn.com##+js(trusted-override-element-method, HTMLAnchorElement.prototype.click, a[target="_blank"], debug)`
- Open logger
- Open `https://toonstream.co/episode/pokemon-journeys-the-series-23x2/` in a new tab
- Open dev tools for that tab
- Click "SEVER 2"
- Click play
- Stop play (just to keep environment quiet)
- Maximize player
- Minimize player
- Debug statement triggered as seen in screenshot

**Comment by D4niloMR** [comment]
Can `nowoif` also have a `debug` value?

**Comment by gorhill** [comment]
I could add a special case for the url parameter:

    ##+js(nowoif, debug)

Which would trigger a `debugger;` for all calls to `window.open()` without preventing them. Would that work?

**Comment by D4niloMR** [comment]
Yes, that should work. I was thinking of using it on `https://filemoon.sx/e/dpgw5dfyk8p8` (There's no popup on Firefox because of injected CSP).

**Comment by mapx-** [comment]
> clicking 480/720 generates new popup window which is closed due to matching EL filter

no popup on my side even disabling `HTMLAnchorElement.prototype.click` filter, so it could be removed

**Comment by stephenhawk8054** [comment]
They still keep that script:

```adb
function openNewTab(url) {
  var a = document.createElement("a");
  a.href = url;
  a.target = "_blank";
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}
```

**Comment by stephenhawk8054** [comment]
@ghajini Does this work on your side?

```adb
streamsilk.com##+js(nostif, adDiv)
```

**Comment by stephenhawk8054** [comment]
Oh sorry, I checked wrong page.

**Comment by mapx-** [comment]
popups only on mobile ?

**Comment by mapx-** [comment]
ok, popups on the first link in the issue, not on the last link
