### ISSUE TITLE
anjunadeep.com: breakage

### ISSUE THREAD

**Issue by Jaxc** [uBlockOrigin/uAssets#25517]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://anjunadeep.com/gb/events/explorations`

### Category

Breakage

### Description

Sign up form dissapears when ublock origin is enabled. Disabling ublock origin for the site reenables the form.

### Other extensions used

Privacy badger
Facebook container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bild](https://github.com/user-attachments/assets/f7df8220-61a6-4aa8-8dd7-ed9e596d4542)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 130
filterset (summary):
 network: 152252
 cosmetic: 51379
 scriptlet: 21412
 html: 2084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40622-130, now
  ublock-badware: 11583-6, now
  ublock-privacy: 1282-22, now
  ublock-unbreak: 2536-1, now
  ublock-quick-fixes: 159-11, now
  easylist: 85716-184, now
  easyprivacy: 53133-62, now
  urlhaus-1: 25210-0, now
  plowe-0: 3546-993, now
  SWE-1: 4920-22, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 628 ms
 maxAssetCacheWait: 197 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  activehosted.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||activehosted.com^$3p` in `Frellwit's Swedish Filter` list

cc @lassekongo83 Sorry, can you check this?
