### ISSUE TITLE
fandom.com: ads

### ISSUE THREAD

**Issue by thedev2203** [uBlockOrigin/uAssets#25514]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.fandom.com/`

### Category

ads

### Description

An ad appears on the sidebar. The ad is highlighted by the red square in the screenshot.

### Other extensions used

None

### Screenshot(s)

![firefox_hxdIYbQxi1](https://github.com/user-attachments/assets/fdbfa686-8ebe-4a60-9587-5b4cfaacbcf0)
![firefox_W6f35UjgCK](https://github.com/user-attachments/assets/b2b0fc94-bdf7-4265-a7ce-742cff275b6b)

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 150569
 cosmetic: 48434
 scriptlet: 21144
 html: 2005
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40582-235, 7m
  ublock-badware: 11579-24, 8m
  ublock-privacy: 1264-24, 8m
  ublock-unbreak: 2537-13, 3m Δ
  ublock-quick-fixes: 159-13, 3m Δ
  easylist: 85707-49, 3m Δ
  easyprivacy: 53130-679, 3m Δ
  urlhaus-1: 25210-0, 8m
  plowe-0: 3546-376, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 184 ms (selfie)
 maxAssetCacheWait: 114 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  fandom.com: 3
  ad.gt: 2
  adsafeprotected.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 2
  doubleclick.net: 2
  doubleverify.com: 1
  fastly-insights.com: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  liadm.com: 1
  quantserve.com: 2
  s3.amazonaws.com: 2
  scorecardresearch.com: 2
  wikia-services.com: 9
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.gpt-ad
  ##.hidead
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by thedev2203** [comment]
I used this cosmetic filter to remove it.

`fandom.com###sponsored-logo > .global-navigation__link`

**Comment by thedev2203** [comment]
I verified that the ad no longer shows up with uBlock Origin turned

![firefox_ItEOtVi2WW](https://github.com/user-attachments/assets/fcdaaf10-2d45-44ec-b8ee-a2a7ccc094be)

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue

![image](https://github.com/user-attachments/assets/7ab87792-dd60-443a-a234-69d346835c08)

**Comment by gorhill** [comment]
I am also unable to reproduce.
