### ISSUE TITLE
letroso.com: breakage

### ISSUE THREAD

**Issue by KaXaSA** [uBlockOrigin/uAssets#25515]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://letroso.com/`

### Category

breakage

### Description

Site is blank when uBlock Origin is enabled. 
Disabling the extension or Cosmetic Filtering fix the issue.

### Other extensions used

none 
tested on a few devices, including an android phone with firefox and only uBlockOrigin extension installed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0c50ab03-845d-427c-8169-9369d3bc4d69)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 133
filterset (summary):
 network: 154074
 cosmetic: 125153
 scriptlet: 26142
 html: 2005
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103374-18181, now
 default:
  user-filters: 525-16, never
  ublock-filters: 40614-149, now
  ublock-badware: 11583-6, now
  ublock-privacy: 1270-23, now
  ublock-unbreak: 2537-5, now
  easylist: 85710-206, now
  easyprivacy: 53130-195, now
  urlhaus-1: 24860-0, now
  plowe-0: 3546-993, now
  ublock-quick-fixes: 161-13, now
filterset (user): [array of 525 redacted]
trustedset:
 added: [array of 231 redacted]
switchRuleset:
 added: [array of 26 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 7592 ms
 maxAssetCacheWait: 305 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  intergient.com: 1
 extended:
  ##.ad-padding
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
letroso.com#@#.ad-padding
```

@ryanbr
