### ISSUE TITLE
uBlock Origin not Working with anilinkz.to

### ISSUE THREAD

**Issue by mrehanabbasi** [uBlockOrigin/uAssets#2551]
### URL(s) where the issue occurs

`http://anilinkz.to`

### Describe the issue

Since today, anilinkz.to has been detecting uBlock Origin and giving the message as per below screenshots. It's not letting me play videos either. I've even tried Nano Defender extension but it ain't working.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/19202888/41372660-5f8e595c-6f67-11e8-81b0-6e8348cac840.png)

![image](https://user-images.githubusercontent.com/19202888/41372773-b406a390-6f67-11e8-8aad-01e4c552b955.png)

### Versions

- Browser/version: Google Chrome Version 67.0.3396.79 (Official Build) (64-bit)
- uBlock Origin version: 1.16.8

**Comment by mapx-** [comment]
It was fixed 8 hours ago. Update your filters.
https://github.com/uBlockOrigin/uAssets/issues/2549

**Comment by mrehanabbasi** [comment]
I've updated my filters but it isn't working.. Moreover, I can't seem to find the filters.txt file in my filter lists..

**Comment by mapx-** [comment]
filters.txt is listed as "`uBlock filters`"
