### ISSUE TITLE
post-gazette.com: detection

### ISSUE THREAD

**Issue by j-espinoz** [uBlockOrigin/uAssets#25529]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.post-gazette.com/news/election-2024/2024/10/04/pilgrimage-trump-return-to-butler/stories/202410030106`

### Category

detection

### Description

overlay coving article detecting adblocker

### Other extensions used

peardeck

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 144435
 cosmetic: 48469
 scriptlet: 22748
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  plowe-0: null
 default:
  ublock-filters: 40351-126, now
  ublock-badware: 11584-6, now
  ublock-privacy: 1295-23, now
  ublock-unbreak: 2477-1, now
  ublock-quick-fixes: 159-13, now
  easylist: 85735-202, now
  easyprivacy: 53137-140, now
  urlhaus-1: 21500-0, now
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 527 ms (selfie)
 maxAssetCacheWait: 127 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 41
 network:
  amazon-adsystem.com: 1
  aswpsdkus.com: 1
  chartbeat.com: 1
  civicscience.com: 1
  cxense.com: 1
  google-analytics.com: 2
  googletagmanager.com: 2
  googletagservices.com: 1
  krxd.net: 1
  ntv.io: 1
  openx.net: 1
  piano.io: 1
  rackcdn.com: 1
  rtk.io: 1
  spot.im: 23
  tinypass.com: 2
 extended:
  ##.pg-adtarget
  ##.pgevoke-story-topads
  ##.pg-adnotice
  ##.pgevoke-story-rightrail-ad1
  ###benn-poll-iframe-container
  ##.pg-mobile-adhesionbanner
```
</details>

**Comment by gorhill** [comment]
> - [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.

> `removed:`
> `  plowe-0: null`

You removed "Peter Lowe’s Ad and tracking server list", re-enable it and please answer the prerequisite steps truthfully next time.
