### ISSUE TITLE
Is wondershare safe and erroneously blocked?

### ISSUE THREAD

**Issue by undrline** [uBlockOrigin/uAssets#2552]
### URL(s) where the issue occurs
`http://cbs.wondershare.com/go.php?pid=2990&m=c6`

### Describe the issue

- Using PDFelement, clicking on a support link brings me to the link:
`http://cbs.wondershare.com/go.php?pid=2990&m=c6`
- Which, in turn, gives a warning page that it's blocked according to the EasyPrivacy rule:
`||cbs.wondershare.com^`
- Clicking on the EasyPrivacy link on the warning page brings me to the EasyList forums.  Searching for wondershare there, brings up a relevant thread on the topic:
`https://forums.lanik.us/viewtopic.php?f=64&t=30961&p=96640&hilit=wondershare#top`
- Where wondershare themselves request to be removed from the blocklist.  The EasyList author says to report the issue to uB, and another user links them to:
`https://github.com/gorhill/uBlock/issues`
- Which, in turn, says it's depreciated:
`https://github.com/gorhill/uBlock/issues/3726`
- Searching for wondershare there, no issues are returned, so I attempted to ask, essentially "should I be worried about this site and their products," by creating a new issue.  But, the pre-populated submission text says to come here:
`https://github.com/uBlockOrigin/uAssets/issues`
- Again, searching for wondershare returns nothing.  But, since I've come all this way, I'm going to go ahead and tell my story, and ask my question.

### Versions

- Browser/version: Opera 53.0.2907.99
- uBlock Origin version: v1.16.6

**Comment by mapx-** [comment]
Does this filter work for you ?
`@@||cbs.wondershare.com/*pid=`

**Comment by undrline** [comment]
Not sure.  I'm travelling atm, and can't check.  Is the site supposed to be blocked?  Does it present a danger to privacy?
