### ISSUE TITLE
whatitismyip.net: ads

### ISSUE THREAD

**Issue by yassin193** [uBlockOrigin/uAssets#25522]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://whatitismyip.net/`

### Category

ads

### Description

some ads are unexpectedly showing

### Other extensions used

NoScript, Privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://paste.pics/75bf48f4057c5bc01102f5a49aa2b

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 129
filterset (summary):
 network: 923380
 cosmetic: 252981
 scriptlet: 49053
 html: 2008
listset (total-discarded, last-updated):
 added:
  https://blocklistproject.github.io/Lists/ransomware.txt: 1904-0, 1m
  https://raw.githubusercontent.com/PeterDaveHello/url-shorteners/master/list: 1537-0, 1m
  https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt: 8141-0, 1m
  https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt: 435214-2606, 1m
  https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt: 500328-253105, 1m
  adguard-generic: 84580-5085, now
  adguard-spyware-url: 1733-126, now
  adguard-spyware: 85380-20611, now
  adguard-cookies: 32097-63, now
  ublock-cookies-adguard: 1823-30, now
  fanboy-cookiemonster: 52230-4040, now
  ublock-cookies-easylist: 1823-1823, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 77-67, never
  ublock-filters: 41129-156, 1h.41m Δ
  ublock-badware: 11577-29, 1h.41m Δ
  ublock-privacy: 1283-38, 1h.41m Δ
  ublock-unbreak: 2539-2, 1h.41m Δ
  ublock-quick-fixes: 153-11, 1h.41m Δ
  adguard-mobile: 9970-587, now
  easylist: 85718-4954, 1h.41m Δ
  easyprivacy: 53133-32282, 1h.41m Δ
  urlhaus-1: 21500-38, now
  plowe-0: 3539-1884, now
filterset (user): [array of 78 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 contextMenuEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2427 ms (selfie)
 maxAssetCacheWait: 988 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed in https://github.com/easylist/easylist/commit/9a44421e883a2cb0966321cb92fe68b926e3589a
