### ISSUE TITLE
nakedwines.co.uk: breakage

### ISSUE THREAD

**Issue by PKMD23** [uBlockOrigin/uAssets#25527]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.nakedwines.co.uk/wines/index
```

### Description

Filtering, e.g. by style, just shows an infinite spinner. Disabling uBlock Origin makes the filter work.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

It should look like this:

![image](https://github.com/user-attachments/assets/827c5277-a6cd-4813-a104-0c4648ccec71)

Instead, it looks like this forever:

![image](https://github.com/user-attachments/assets/c21b4b10-9b38-464d-b715-2f9a59d377c5)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 150240
 cosmetic: 48469
 scriptlet: 21150
 html: 2007
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 83-0, 6d.2h.59m
 default:
  user-filters: 0-0, never
  ublock-filters: 40619-131, 1h.57m Δ
  ublock-badware: 11582-6, 1h.57m Δ
  ublock-privacy: 1276-105, 1h.57m Δ
  ublock-unbreak: 2535-0, 1h.57m Δ
  easylist: 85718-184, 1h.57m Δ
  easyprivacy: 53133-62, 1h.57m Δ
  urlhaus-1: 24860-0, 23h.57m
  plowe-0: 3553-998, 8d.5h.59m
  ublock-quick-fixes: 153-11, 1h.57m Δ
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 396 ms (selfie)
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  nakedwines.co.uk: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  report-uri.com: 1

```
</details>

**Comment by gorhill** [comment]
False positive from EasyPrivacy's `@@/hitcount?`, causing `https://www.nakedwines.co.uk/search/hitcount?` to be blocked.

cc @ryanbr
