### ISSUE TITLE
gazetadopovo.com.br: detection

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#25525]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gazetadopovo.com.br/mundo/com-fuzil-na-mao-lider-do-ira-elogia-massacre-do-hamas-e-volta-a-ameacar-israel/`

### Category

detection

### Description

Annoying nag screen

### Other extensions used

Nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e320fa01-6311-4270-bec8-e44e78636a7a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 145736
 cosmetic: 52570
 scriptlet: 21678
 html: 2007
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 default:
  user-filters: 5-0, never
  ublock-filters: 40621-130, 37m Δ
  ublock-badware: 11586-6, 37m Δ
  ublock-privacy: 1282-22, 37m Δ
  ublock-unbreak: 2536-1, 37m Δ
  ublock-quick-fixes: 157-11, 37m Δ
  easylist: 85718-184, 37m Δ
  easyprivacy: 53133-62, 37m Δ
  urlhaus-1: 21500-0, now
  spa-1: 6029-83, now
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 274 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  gazetadopovo.com.br: 1
  cxense.com: 3
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 4
  googletagmanager.com: 1
  igodigital.com: 1
  taboola.com: 1
 extended:
  ###ads-header
  ##.c-ads
  ##.ads-header
  ##.ads-desktop
  ##.ads-mobile
  ##.OUTBRAIN
  ##.ads-stick-footer
  ##.banner-topo
  ##div[class^="box-ads-header"]
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by gorhill** [comment]
> `removed:`
> ` plowe-0: null`

You removed "Peter Lowe’s Ad and tracking server list", re-enable it.

Please mind:

> - [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
> ...
> - [x] I did not answer truthfully to ALL the above checkboxes.
