### ISSUE TITLE
rezkify.com: ads

### ISSUE THREAD

**Issue by SunnyVolh** [uBlockOrigin/uAssets#25526]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://rezkify.com/cartoons/comedy/2136-rik-i-morti-2013.html`

### Category

ads

### Description

ads not blocked

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 146898
 cosmetic: 48471
 scriptlet: 21155
 html: 2007
listset (total-discarded, last-updated):
 removed:
  RUS-0: null
 default:
  user-filters: 32-2, never
  ublock-filters: 40617-130, 22m Δ
  ublock-badware: 11582-6, 22m Δ
  ublock-privacy: 1276-22, 22m Δ
  ublock-unbreak: 2535-1, 22m Δ
  ublock-quick-fixes: 157-11, 22m Δ
  easylist: 85718-184, 22m Δ
  easyprivacy: 53133-62, 22m Δ
  urlhaus-1: 21500-0, now
  plowe-0: 3539-991, now
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9921 ms (selfie)
 maxAssetCacheWait: 76 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 120
 network:
  adpod.in: 6
  aj2517.bid: 2
  clarity.ms: 1
  franecki.net: 43
  franeski.net: 1
  getter.cfd: 4
  jsdelivr.net: 1
  reichelcormier.bid: 20
  serv01001.xyz: 42
```
</details>

**Comment by gorhill** [comment]
> `removed:`
> ` RUS-0: null`

You removed "RU AdList", re-enable it.
