### ISSUE TITLE
www1.flightrising.com: ads

### ISSUE THREAD

**Issue by redwes1** [uBlockOrigin/uAssets#25533]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www1.flightrising.com/`

### Category

ads

### Description

All pages on website show ad placeholder "Flight Rising is supported primary by ads..." on side bar.
Shows as "ponies" under inspect element.

### Other extensions used

Chrome Remote Desktop 2.1
Google Docs Offline 1.80.1
HDS / HLS Video Downloader 3.1.8
Return YouTube Dislike 3.0.0.17
Ruffle - Flash Emulator 0.1.0 nightly 2024-10-02
SponsorBlock for YouTube - Skip Sponsorships 5.9.4
User-Agent Switcher for Chrome 2.0.1
Zoom to Fill - Ultrawide Video 2.1.6

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-10-04 172331](https://github.com/user-attachments/assets/8a014504-ccc6-44b2-b887-8579d154958b)

</details>

### Configuration

```yaml
version: uBOL 2024.9.29.1273
mode: basic / complete
rulesets:
 default
```

**Comment by stephenhawk8054** [comment]
```adb
flightrising.com###skybanner
```

@ryanbr For EL annoyance list?

**Comment by stephenhawk8054** [comment]
Fixed in `EasyList – Other Annoyances` list
