### ISSUE TITLE
haaretz.co.il: detection

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#25535]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.haaretz.co.il`

### Category

detection

### Description

ads

### Other extensions used

1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 130
filterset (summary):
 network: 161168
 cosmetic: 179850
 scriptlet: 32760
 html: 2280
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  block-lan: 64-0, 15m
  adguard-social: 23183-44, 15m
  ublock-cookies-adguard: 1823-9, 15m
  adguard-popup-overlays: 28094-920, 15m
  fanboy-thirdparty_social: 68-3, 15m
  easylist-annoyances: 4803-177, 15m
  easylist-chat: 216-1, 15m
  fanboy-cookiemonster: 52232-229, 15m
  ublock-cookies-easylist: 1823-1823, 15m
  easylist-newsletters: 7925-564, 15m
  easylist-notifications: 3444-246, 15m
  fanboy-social: 16838-811, 15m
  [2 lists not shown]: [too many]
 default:
  ublock-filters: 41133-213, 28m Δ
  ublock-badware: 11580-7, 28m Δ
  ublock-privacy: 1284-22, 28m Δ
  ublock-unbreak: 2533-3, 28m Δ
  ublock-quick-fixes: 161-11, 28m Δ
  adguard-mobile: 9970-11, 15m
  easylist: 85741-258, 28m Δ
  easyprivacy: 53137-73, 28m Δ
  urlhaus-1: 25350-0, 15m
  plowe-0: 3539-1066, 15m
filterset (user): [empty]
trustedset:
 added: [array of 19 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 671 ms (selfie)
 maxAssetCacheWait: 188 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  ads-twitter.com: 1
  analysis.fi: 1
  brandmetrics.com: 1
  chartbeat.com: 1
  cookielaw.org: 1
  crazyegg.com: 1
  doubleclick.net: 3
  dxmdp.com: 1
  facebook.net: 1
  firstimpression.io: 1
  geoedge.be: 1
  google.com: 6
  googletagmanager.com: 1
  outbrain.com: 1
  taboola.com: 1
  valuad.cloud: 1
  youtube.com: 3
 extended:
  ##[href^="https://www.themarker.com/labels/"]
  ##html:style(height: auto !important; overflow: auto !important)
  ##+js(addEventListener-defuser, load, hblocked)
  ##+js(abort-current-script, $, AdBlockUtil)
  ##+js(set-constant, showAds, true)
  ##+js(addEventListener-defuser, , hblocked)
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.web_bind_fetch, …
  ##+js(trusted-click-element, ytd-button-renderer.ytd-consent-bum…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, be sure you have `EasyList Hebrew` enabled, disable any other blocking extension / app, test again
