### ISSUE TITLE
jetfilmizle.link: ads

### ISSUE THREAD

**Issue by 0x733** [uBlockOrigin/uAssets#25534]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://jetfilmizle.link/
```

### Description

Fleeing ads.

### Other extensions used

Mullvad Browser Extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![img](https://github.com/user-attachments/assets/de32a54a-5e6e-4d0c-9922-b708d92690b9)

![img2](https://github.com/user-attachments/assets/a17098dd-6e67-4578-a877-0eb0faaa409a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.60.0
Firefox: 115
filterset (summary):
 network: 199224
 cosmetic: 158091
 scriptlet: 51191
 html: 2269
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  easylist: null
 added:
  adguard-generic: 84580-5255, 17h.41m
  adguard-spyware-url: 1733-125, 17h.47m
  adguard-spyware: 85380-528, 17h.40m
  block-lan: 64-0, 17h.41m
  curben-phishing: 493-2, 17h.40m
  adguard-cookies: 32097-59, 17h.40m
  ublock-cookies-adguard: 1785-28, 17h.41m
  adguard-social: 23182-49, 17h.40m
  adguard-popup-overlays: 28093-929, 17h.40m
  adguard-mobile-app-banners: 5521-27, 17h.40m
  adguard-other-annoyances: 14675-458, 17h.40m
  adguard-widgets: 2687-13, 17h.40m
  [2 lists not shown]: [too many]
 default:
  ublock-filters: 40627-130, 13m Δ
  ublock-badware: 11586-6, 13m Δ
  ublock-privacy: 1283-22, 13m Δ
  ublock-unbreak: 2530-2, 13m Δ
  ublock-quick-fixes: 161-11, 13m Δ
  easyprivacy: 53137-23534, 13m Δ
  urlhaus-1: 21500-0, 17h.47m
  plowe-0: 3539-1142, 17h.47m
  TUR-0: 11419-57, 17h.40m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1746 ms (selfie)
 maxAssetCacheWait: 922 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
```yml
removed:
  user-filters: null
  easylist: null
```

You are removing EasyList, one of the default filter lists. Reset uBO to default settings and test again.

**Comment by 0x733** [comment]
> You are removing EasyList, one of the default filter lists. Reset uBO to default settings and test again.

I'm sorry, I missed it. Thank you, my problem has been fixed.
