### ISSUE TITLE
[nsfw] flycutlink.com: detection

### ISSUE THREAD

**Issue by Ruzz23** [uBlockOrigin/uAssets#25531]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://flycutlink.com/367wWNX
```

### Description

I'm trying to download nsfw content but I can't move on from their 2nd page of shorteners (flycutlink.com) because it detects ublocker. I've already tried changing the browser from chrome to firefox, disabling all extensions and it still detects ublock.

### Other extensions used

none

### Screenshot(s)

<a href="https://ibb.co/YRY7KsT"><img src="https://i.ibb.co/0D8jWbV/ublock-001.png" alt="ublock-001" border="0"></a>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 153037
 cosmetic: 55340
 scriptlet: 21672
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40581-131, 48m
  ublock-badware: 11586-6, 48m
  ublock-privacy: 1282-22, 48m
  ublock-unbreak: 2537-1, 48m
  ublock-quick-fixes: 161-15, 48m
  easylist: 85718-185, 48m
  easyprivacy: 53133-62, 48m
  urlhaus-1: 25255-0, 48m
  plowe-0: 3539-991, 48m
  spa-0: 4080-26, 48m
  spa-1: 6029-256, 48m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6376 ms
 maxAssetCacheWait: 225 ms
 cacheBackend: indexedDB

**Comment by gorhill** [comment]
> - [x] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or https://github.com/uBlockOrigin/uAssets/discussions/17361 report. These sites MUST be reported by clicking their respective links.

As asked, please report shortener issues to <https://github.com/uBlockOrigin/uAssets/discussions/17361>.
