### ISSUE TITLE
YT music doesn't play audio despite the video loading.

### ISSUE THREAD

**Issue by Nanashi-afk** [uBlockOrigin/uAssets#25539]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
music.youtube.com
```

### Description

Essentially the videos load perfectly well but no audio is played. Using InPrivate Tabs on my broswer makes this problem disappear. I don't use any other extentions, so I thought this might be a Ublock origin problem.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150748
 cosmetic: 48476
 scriptlet: 22752
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40355-259, 1m
  ublock-badware: 11584-6, 1m
  ublock-privacy: 1296-22, 1m
  ublock-unbreak: 2471-0, 1m
  ublock-quick-fixes: 159-0, 1m
  easylist: 85764-576, 1m
  easyprivacy: 53130-640, 1m
  urlhaus-1: 25330-0, 1m
  plowe-0: 3539-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3039 ms
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
```
</details>

**Comment by D4niloMR** [comment]
> - [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.

Disable uBO and try again.

**Comment by Nanashi-afk** [comment]
> > * [x]  If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
> 
> Disable uBO and try again.

Yeah I've removed and added it that didn't work
