### ISSUE TITLE
netflix.com: ads

### ISSUE THREAD

**Issue by shaunjr** [uBlockOrigin/uAssets#25530]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.netflix.com/browse?jbv=80117552`

### Category

ads

### Description

ads still play, was working for the past couple weeks with better call saul. now ads with ozark appearing 

### Other extensions used

lastpass, dark reader, super agent, honey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot (4)](https://github.com/user-attachments/assets/725744e1-c8aa-419c-a625-4b31aeaae0e5)

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 130
filterset (summary):
 network: 146895
 cosmetic: 48466
 scriptlet: 21159
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40621-130, now
  ublock-badware: 11582-6, now
  ublock-privacy: 1276-22, now
  ublock-unbreak: 2535-1, now
  ublock-quick-fixes: 157-11, now
  easylist: 85735-184, now
  easyprivacy: 53137-62, now
  urlhaus-1: 21500-0, 1h.32m
  plowe-0: 3539-991, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 326
 network:
  netflix.com: 324
  bing.com: 2
```
</details>

**Comment by gorhill** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/24914#issuecomment-2290093934

**Comment by shaunjr** [comment]
> Please respect the prerequisites:
> 
> > * [ ]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
> 
> Continue here: [#24914 (comment)](https://github.com/uBlockOrigin/uAssets/issues/24914#issuecomment-2290093934)

Apologies, that button was not working for me. Took me to another windows and there was no response on anything I clicked
