### ISSUE TITLE
yahoo.com: ads

### ISSUE THREAD

**Issue by redwes1** [uBlockOrigin/uAssets#25532]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.yahoo.com/`

### Category

ads

### Description

Homepage shows ad placeholder "Advertisement" visible above page content-- only started happening today.

### Other extensions used

Chrome Remote Desktop 2.1
Google Docs Offline 1.80.1
HDS / HLS Video Downloader 3.1.8
Return YouTube Dislike 3.0.0.17
Ruffle - Flash Emulator 0.1.0 nightly 2024-10-02
SponsorBlock for YouTube - Skip Sponsorships 5.9.4
User-Agent Switcher for Chrome 2.0.1
Zoom to Fill - Ultrawide Video 2.1.6

### Screenshot(s)

![Screenshot 2024-10-04 171828](https://github.com/user-attachments/assets/a06c8f27-ffce-48a5-864c-049b5ab2db68)

</details>

### Configuration

```yaml
version: uBOL 2024.9.29.1273
mode: complete / complete
rulesets:
 default
```

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by redwes1** [comment]
> Which country are you when accessing the site?

I'm located in the US. Thanks for the timely reply. ^^

**Comment by redwes1** [comment]
I did not mean to close-- it forced me to close in order to comment.
