### ISSUE TITLE
coempregos.com.br: detection

### ISSUE THREAD

**Issue by oPenta** [uBlockOrigin/uAssets#25546]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://coempregos.com.br/v/vagas/89/atendente-de-distribuidora-de-bebidas`
`https://www.hinatasoul.com/videos/381711`

### Category

detection

### Description

Hinata Souls detect the adblock and i cant see the anime 

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 152008
 cosmetic: 52585
 scriptlet: 23284
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40363-273, 8m Δ
  ublock-badware: 11580-6, 8m Δ
  ublock-privacy: 1290-22, 8m Δ
  ublock-unbreak: 2468-3, 8m Δ
  ublock-quick-fixes: 167-0, 8m Δ
  easylist: 85783-615, 8m Δ
  easyprivacy: 53139-653, 8m Δ
  urlhaus-1: 25255-0, 8m
  plowe-0: 3541-0, 1m
  spa-1: 6029-16, 1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3166 ms (selfie)
 maxAssetCacheWait: 573 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 2
  qlfedijakjky.com: 3
  veristouh.net: 2
 extended:
  ##.ad-1
  ##.ads-2
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
  ##+js(no-setTimeout-if, hasAdblock)
  ##+js(set-constant, detectedAdblock, noopFunc)
  ##+js(prevent-fetch, /outbrain\.com|adligature\.com|quantserve\.…
  ##+js(trusted-prevent-xhr, outbrain.com, outbrain)
  ##+js(set-constant, ATESTADO, 1)
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
```
</details>

**Comment by oPenta** [comment]
fecha o meu inssue

**Comment by stephenhawk8054** [comment]
Don't change the title
