### ISSUE TITLE
kibagames.com: breakage

### ISSUE THREAD

**Issue by desant5** [uBlockOrigin/uAssets#25543]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kibagames.com/Game/Fireboy-and-Watergirl`

### Category

breakage

### Description

"start game" button is not visible, you just get a black screen

same design, different domain names. all three have the same problem.

```
https://www.kibagames.com/
https://www.spielaffe.de/
https://www.kraloyun.com/
```

### Other extensions used

null

### Screenshot(s)

https://i.ibb.co/hccgGfd/bug1111.png

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 151089
 cosmetic: 48474
 scriptlet: 21096
 html: 2002
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40599-139, 7m
  ublock-badware: 11586-6, 7m
  ublock-privacy: 1283-22, 7m
  ublock-unbreak: 2530-0, 7m
  ublock-quick-fixes: 162-2, 7m
  easylist: 85764-185, 7m
  easyprivacy: 53139-62, 7m
  urlhaus-1: 25615-0, 7m
  plowe-0: 3539-991, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2748 ms
 maxAssetCacheWait: 1027 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  kibagames.com: 1
  adscale.de: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  imasdk.googleapis.com: 1
  m6r.eu: 1
  speedcurve.com: 1
  spielaffe.de: 1
  theadex.com: 1
  userreport.com: 1
  yieldlove.com: 1
 extended:
  ##.alice-root-header-ads__ad--top
  ##.alice-adslot
  ##.advertising-container
```
</details>

**Comment by stephenhawk8054** [comment]
```
https://www.spielaffe.de/
https://www.kraloyun.com/
```

I can't reproduce the issue with these sites. They are already fixed in https://github.com/uBlockOrigin/uAssets/blob/df8eaeb24adfa3b84f4e8c8d76be23f74ac6e529/filters/unbreak.txt#L5080

**Comment by desant5** [comment]
> I can't reproduce the issue with these sites

I don't know, it's not working on my end. 
Closing
Thanks
