### ISSUE TITLE
mail.yahoo.com: ads

### ISSUE THREAD

**Issue by mmaalouf97** [uBlockOrigin/uAssets#25540]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mail.yahoo.com/d/folders/1`

### Category

ads

### Description

Ad showing above list of emails. Element zapper removes ad but leaves blank space, until webpage is refreshed. Element picker will not allow me to pick the ad and defaults to picking background of Yahoo Mail page. Inspect element of ad included but not sure how to add the correct filter

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ad Yahoo Mail](https://github.com/user-attachments/assets/536bf248-8e36-42bb-b994-347d3c0bce57)
![Ad Yahoo Mail Inspect Element](https://github.com/user-attachments/assets/0d36a0e9-649f-472e-b71d-810d3d37cbb8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 130
filterset (summary):
 network: 150747
 cosmetic: 48477
 scriptlet: 21167
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40633-130, 14m Δ
  ublock-badware: 11582-6, 14m Δ
  ublock-privacy: 1277-22, 14m Δ
  ublock-unbreak: 2529-1, 14m Δ
  ublock-quick-fixes: 162-11, 14m Δ
  easylist: 85764-185, 14m Δ
  easyprivacy: 53139-62, 14m Δ
  urlhaus-1: 25330-0, 11m
  plowe-0: 3539-991, 11m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 118 ms (selfie)
 maxAssetCacheWait: 48 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  yahoo.com: 23
  doubleclick.net: 1
  scorecardresearch.com: 1
  taboola.com: 7
  yahoo.net: 2
  yimg.com: 1
 extended:
  ##[data-test-id="gam-iframe"]
  #@#a[href^="https://ad.doubleclick.net/"]
  ##+js(no-setTimeout-if, ADB)
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(set-constant, navigator.globalPrivacyControl, false)
```
</details>

**Comment by gorhill** [comment]
Probably need to add:

    mail.yahoo.com##[data-test-id^="taboola-ad-"]

**Comment by mmaalouf97** [comment]
> Probably need to add:
> 
> ```
> mail.yahoo.com##[data-test-id^="taboola-ad-"]
> ```

Fixed! Thanks!

**Comment by gorhill** [comment]
cc @ryanbr

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
mail.yahoo.com##div[data-test-id="virtual-list"] > ul[role="list"] > li:has(a[href^="https://api.taboola.com/"])
```

**Comment by mmaalouf97** [comment]
> Does this work?
> 
> ```
> mail.yahoo.com##div[data-test-id="virtual-list"] > ul[role="list"] > li:has(a[href^="https://api.taboola.com/"])
> ```

Fixed! Thank you!!!! Also I don't know if this one can be blocked as well but could you please take a look?
![image](https://github.com/user-attachments/assets/35b68c5b-19eb-4d3b-8626-32504f268614)

**Comment by mmaalouf97** [comment]
Yahoo mail being Yahoo mail again... any idea how to block this one?? @stephenhawk8054 

<img width="1719" height="766" alt="Image" src="https://github.com/user-attachments/assets/e088c7e0-a4c3-451b-8a0e-8328009a06f4" />

**Comment by stephenhawk8054** [comment]
Can you right click on that element in the console, then choose "Copy outer HTML" and share to here?

---

Or can you test this filter:

```adb
mail.yahoo.com##[data-test-id^="leaderboard-ad"]
```

**Comment by mmaalouf97** [comment]
I added the filter, no change :(

Here is outer HTML:

<details>

```html
<div class="W_6D6F D_F H_3n2AO d_3n2AO o_A gl_C p_a B_0 k_w P_1HT1B4 I_ZD6Uwa bj_a0xJ8 is_26ISAR" data-test-id="leaderboard-ad"><div aria-hidden="true" class="k_w W_3LAgP a_3LAgP iz_h iy_h P_0 H_7GHz"><iframe name="Z3B0LWlmcmFtZS1tZXNzYWdlX2xpc3QtMQ==" class="W_6D6F H_6D6F b_n I_T" id="Z3B0LWlmcmFtZS1tZXNzYWdlX2xpc3QtMQ==" allow="geolocation 'none'; fullscreen 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; microphone 'none'; gyroscope 'none'; magnetometer 'none'; midi 'none'; payment 'none'; serial 'none'; speaker-selection 'none'" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts" scrolling="no" src="https://gpt.mail.yahoo.net/sandbox?client=mail&amp;version=0.1&amp;ymreqid=c813c2aa-0ac8-b01a-1c6d-8d0000017500&amp;haq=1#config=%7B%22positions%22%3A%5B%7B%22adUnitPath%22%3A%22%2F22888152279%2Fus%2Fymail%2Fmessage%2Fdt%2Fus_ymail_message_dt_mid_center_pg%22%2C%22adLocation%22%3A%22message_list%22%2C%22size%22%3A%5B%5B728%2C90%5D%5D%2C%22div%22%3A%22gpt-passback%22%2C%22positionUnits%22%3A%5B%22DESKTOP_LEADERBOARD_FOOTER%22%5D%2C%22adIndex%22%3A1%7D%5D%2C%22pageUrl%22%3A%22https%3A%2F%2Fmail.yahoo.com%22%2C%22yahooPrebid%22%3Atrue%2C%22npa%22%3Afalse%2C%22limited%22%3Afalse%2C%22adStackingV2Enabled%22%3Atrue%2C%22benjiFeatures%22%3A%5B%22benji-enableAYGrowthCode%22%2C%22benji-mpca-prod%22%5D%2C%22geoCountryCode%22%3A%22US%22%2C%22tosCountryCode%22%3A%22us%22%2C%22collapseWhenNoFill%22%3Afalse%2C%22allowFirstPartyAds%22%3Atrue%2C%22userSegments%22%3Atrue%2C%22narrowScreenWidth%22%3A1300%2C%22targetingConfig%22%3A%7B%22colo%22%3A%22bf1%22%2C%22lu%22%3A%221%22%2C%22device%22%3A%22desktop%22%2C%22region%22%3A%22us%22%2C%22lang%22%3A%22en-US%22%2C%22spaceId%22%3A%22159600009%22%2C%22adLocation%22%3A%22message_list%22%2C%22ud%22%3A%22WzNjCMmdpKUBAo72.E4rx0nboqEgB8iSlQRsjn%2FQPJB8bkQJtZiwXmp5UCouW5vGIfa7EhG7BbBh0S%2BU49uX6nC3V8lGZq21cmdxRP7iKhqDZY6EwKijP%2B8C88w%3D%3D%22%2C%22ubid%22%3A%22IRRUUNZZGNEDMVSYHAXTKSLPKQXG6TZQOVJXIY2YJI3DCQLNI5TFERCZHBJTCRDSPJHU653GOJHEYTDXJ5HGWRZXM5UWUWJRGIZEMV2TPFVUMQJUPBBWC53QG44XSVCVJ43TONZRJQ4TIK3VGFDEUUSOG5IUK6CXMFGGMS2DKRNC6WCQKF3UMMLFHBKDS2SGKIVTOR3FJRWFMYLQGBKVKSCZMVXXINCVHU%22%2C%22age%22%3A%223%22%2C%22gender%22%3A%222%22%2C%22dmiConsent%22%3A%22false%22%2C%22theme%22%3A%22SUNSET_AUSSIE%22%2C%22pd%22%3A%22norrin%22%2C%22gaMeasurementId%22%3A%22G-MQBT164R4Q%22%7D%2C%22headerBidderConfig%22%3A%7B%22buckets%22%3A%5B%22ymail_norrin_fixedfooterad_900px_r1%22%2C%22ComAud_TOM_Toddler_AIQ_Desktop%22%2C%22ComAud_TOM_FastFood_GLP1_AIQ_Desktop%22%2C%22CDS_Test_Geo_Jurisdiction_Test%22%2C%22YMail_XStreaks_A_T01%22%2C%22ComAud_TOM_United_Conquesting_AIQDesktop%22%2C%22ComAud_TOM_United_Frequent_AIQ_Desktop%22%2C%22ComAud_TOM_Cap_One_Corp_Serv_AIQ_Desktop%22%2C%22ComAud_TOM_PFMortgageLoan_AIQ_Desktop%22%2C%22mailintel_pers_ci_q2mv_t03%22%2C%22ComAud_Cord_Cutters_AIQ_Desktop%22%2C%22ymail_norrin_20sadrotation_t01%22%2C%22ay-growthcode-mail-test%22%2C%22offers_inbox_desktop_ctrl%22%2C%22YMail_SummerChallenge_Ramp%22%2C%22UG_GmailAdsFree_T02_30d%22%2C%22ComAud_TOM_Stream_AIQ_WCInterest_Desktop%22%2C%22ComAud_TOM_AIQ_HairLoss_Desktop%22%2C%22ComAud_TOM_Kima_HighIncome_Desktop%22%2C%22unsub_oasis_control%22%2C%22ComAud_TOM_AIQ_HiIncTravelCC_Desktop%22%2C%22YMail_XChallenges_T01%22%2C%22production%22%2C%22sticky_summary_notifs_c01%22%2C%22imapUserLoggedOut20260728%22%2C%22imapOut_1_20260728%22%5D%2C%22cobrand%22%3A%22%22%7D%7D" fq0dkhyxw=""></iframe></div></div>
```

</details>

**Comment by stephenhawk8054** [comment]
Well, the element matches the filter so I don't know why it doesn't work. I can't reproduce the issue so I can't investigate further.

**Comment by gorhill** [comment]
> I added the filter, no change :(

Provide troubleshooting information while on the web page: Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by mmaalouf97** [comment]
<details>

```yml
uBlock Origin: 1.72.2
Firefox: 152
filterset (summary):
 network: 188845
 cosmetic: 43405
 scriptlet: 34066
 html: 3762
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  ublock-filters: 53350-72, now
  ublock-badware: 10502-27, now
  ublock-privacy: 4082-2, now
  ublock-unbreak: 2855-1, now
  ublock-quick-fixes: 500-13, 6m
  easylist: 92184-136, now
  easyprivacy: 56104-41, now
  urlhaus-1: 48435-11, now
  plowe-0: 3513-1022, now
filterset (user): [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 970 ms (selfie)
 maxAssetCacheWait: 68 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 177
 network:
  yahoo.com: 100
  googletagmanager.com: 1
  taboola.com: 23
  yahoo.net: 48
  yahoodns.net: 1
  yimg.com: 3
  yusercontent.com: 1
 extended:
  ##div[data-test-id="virtual-list"] > ul[role="list"] > li:has(a[…
  ##li:has(a[href^="https://api.taboola.com/"])
  ##a[href^="https://api.taboola.com/"]
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(prevent-setTimeout, adblock)
  ##+js(prevent-setTimeout, ADB)
  ##+js(json-prune, result.responses.[].response.result.cards.[-].…
  ##+js(trusted-json-edit-xhr-response, ..adshieldAdblockRecovery.…
  ##+js(trusted-json-edit-xhr-response, ..adshieldAdblockRecovery=…
  ##+js(set-constant, AppState.reduxState.features.adshieldAdblock…
  ##+js(set-constant, AppBootstrapData.__initializeFeatures__.adsh…
  ##+js(set-constant, AppBootstrapData.config.adshieldNativeAdReco…
  ##+js(set-constant, AppBootstrapData.config.adshieldAdblockRecov…
  #@#+js(prevent-clipboard-write, /^mshta |^(bash <<<|curl -kfsSL)…
```

</details>
