### ISSUE TITLE
[nsfw] drinkspartner.com: breakage

### ISSUE THREAD

**Issue by tarunjangid12** [uBlockOrigin/uAssets#25542]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://drinkspartner.com/top-10-countries-to-study-in-europe/`

### Category

breakage

### Description

The site not showing because of ublock filter so not able to complete task of this shorter website
Task not showing properly 
![Screenshot_2024-10-06-09-13-14-00_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/bcabdd7f-f963-4c36-919d-3cfee86f948a)
![Screenshot_2024-10-06-09-13-14-00_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/b55db545-db44-40f4-b952-c3346d731a40)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 124
filterset (summary):
 network: 152472
 cosmetic: 57403
 scriptlet: 22831
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 342-1, never
  ublock-filters: 40869-343, 20m Δ
  ublock-badware: 11578-6, 20m Δ
  ublock-privacy: 1297-22, 20m Δ
  ublock-unbreak: 2474-0, 20m Δ
  ublock-quick-fixes: 166-0, 20m Δ
  adguard-mobile: 9815-97, now
  easylist: 85780-642, 20m Δ
  easyprivacy: 53139-648, 20m Δ
  urlhaus-1: 25615-0, now
  plowe-0: 3539-0, now
filterset (user): [array of 342 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 756 ms (selfie)
 maxAssetCacheWait: 240 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cleverwebserver.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##div.pro_ad_top_sticky_container:nth-of-type(3)
  ##.pro_ad_bottom_sticky_container
  ##.entry-content
  ##.entry-header
  ##.comments-area
  ##.grid-container.inside-navigation
  ##.entry-meta
  ##.wpjankari-social-wrapper
  ##.inside-right-sidebar
  ##.site-footer
  ##._th_times
  ##.content-area
  ##div.pro_ad_top_sticky_container:nth-of-type(2)
  ##body:style(overflow: auto !important;)
  ##+js(noeval-if, /fairAdblock|chp_adblock|adsbygoogle\.js/)
  ##+js(adjust-setInterval, /.?/, *, 0.02)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

Please respect the prerequisites and report the original shortener link in this thread: https://github.com/uBlockOrigin/uAssets/discussions/17361
