### ISSUE TITLE
cp24.com: ads

### ISSUE THREAD

**Issue by codedipper** [uBlockOrigin/uAssets#25541]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.cp24.com/
https://www.cp24.com/local/toronto/2024/10/05/ontario-science-centre-to-open-up-temporary-satellite-locations-months-after-sudden-shutdown/
```

### Description

This site recently went through a redesign. uBO detects and blocks Google ads correctly, but leaves behind words where the ads used to be (e.g. ADVERTISEMENT). It also doesn't block sponsored content part of the site itself, that was not injected by a script from any ad company. Tested on a fresh ungoogled-chromium 129.0.6668.89 profile with uBO MV2 1.60.0 built from source.

The following custom filters fix each of these problems:
```
cp24.com##.b-ads-custom
cp24.com##.b-ads-custom--leaderboard_large
cp24.com##.b-large-manual-promo
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/8d166437-1fb0-486b-9f16-e2197761a6ec)
![image](https://github.com/user-attachments/assets/c59b8776-7eb2-42bb-a48c-e330ab22f006)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150688
 cosmetic: 48481
 scriptlet: 22758
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 40364-259, 18m
  ublock-badware: 11584-6, 18m
  ublock-privacy: 1296-22, 18m
  ublock-unbreak: 2471-0, 18m
  ublock-quick-fixes: 166-0, 18m
  easylist: 85764-576, 18m
  easyprivacy: 53139-640, 18m
  urlhaus-1: 25255-0, 18m
  plowe-0: 3539-0, 18m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2094 ms
 maxAssetCacheWait: 177 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 717
 network:
  amazon-adsystem.com: 1
  chartbeat.com: 2
  confiant-integrations.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  mparticle.com: 704
  ntv.io: 1
  permutive.com: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
  tapad.com: 1
  tru.am: 1

```
</details>

**Comment by stephenhawk8054** [comment]
For advertisement placeholders

```adb
cp24.com##.b-ads-custom
```

About the sponsored posts, look like they are all belongs to BellMedia so not sure if they count as self-promotion

cc @ryanbr
