### ISSUE TITLE
dw.com: cookie notice

### ISSUE THREAD

**Issue by Happypig375** [uBlockOrigin/uAssets#25544]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.dw.com/zh-hant/%E7%B7%9A%E4%B8%8A%E5%A0%B1%E5%B0%8E/s-9058
```

### Description

This cookie notice appears after a few seconds.
Both `EasyList/uBO – Cookie Notices` and `AdGuard/uBO – Cookie Notices` do not fix it.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/d8d265b6-d031-4a04-a04f-76b57ab771ab)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 152700
 cosmetic: 94417
 scriptlet: 27134
 html: 2007
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52233-126, 2m
  ublock-cookies-easylist: 1785-13, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 40639-142, 6m Δ
  ublock-badware: 11586-6, 6m Δ
  ublock-privacy: 1283-22, 6m Δ
  ublock-unbreak: 2528-3, 6m Δ
  ublock-quick-fixes: 164-11, 6m Δ
  easylist: 85783-187, 6m Δ
  easyprivacy: 53139-108, 6m Δ
  urlhaus-1: 25330-0, 17h.1m
  plowe-0: 3553-998, 2d.17h.34m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 947 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
```
</details>'

**Comment by stephenhawk8054** [comment]
It will break embeds like here: https://www.dw.com/en/after-brazils-x-ban-what-social-media-alternatives-exist/a-70146551

**Comment by stephenhawk8054** [comment]
These could work without `trusted-click`:

```adb
dw.com###cmpwrapper
dw.com##body[style="overflow: hidden;"]:style(overflow: auto !important;)
dw.com##+js(set, Object.prototype.hasConsent, trueFunc)
```

**Comment by mapx-** [comment]
working fine, @ryanbr for ELC

**Comment by ryanbr** [comment]
https://winfuture.de/videos/Spiele/New-World-Aeternum-Der-Launch-Trailer-laeutet-eine-neue-Aera-ein-26728.html 

```
winfuture.de###cmpwrapper
winfuture.de##body[style="overflow: hidden;"]:style(overflow: auto !important;)
winfuture.de##+js(set, Object.prototype.hasConsent, trueFunc)
```

?
