### ISSUE TITLE
[nsfw] simpcity.su: ads

### ISSUE THREAD

**Issue by Pureblood4936** [uBlockOrigin/uAssets#25547]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://simpcity.su/`

### Category

ads

### Description

a yellow advertising bar is displayed

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bildschirmfoto_6-10-2024_192638_simpcity su](https://github.com/user-attachments/assets/17f7b170-7463-46ea-904e-8b960bf64fa7)

</details>

### Configuration

```yaml
version: uBOL 2024.9.29.1273
mode: optimal / optimal
rulesets:
 default
 deu-0
```

**Comment by dportvine** [comment]
For generic rules, you need `complete` mode. `##a[href^="https://a.adtng.com/"]` ~> **EasyList**

<details>
<summary>Screen</summary>

![2024-10-06_232302](https://github.com/user-attachments/assets/e4b61c27-c94e-4727-8fbc-663713a171fb)
![2024-10-06_232302](https://github.com/user-attachments/assets/3ae9e2b9-3e28-4a7f-85d1-075604505ece)
</details>
