### ISSUE TITLE
x.com: breakage

### ISSUE THREAD

**Issue by suncoastkid** [uBlockOrigin/uAssets#25545]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://x.com/home`

### Category

breakage

### Description

Delete post/comment confirmation modal is blocked.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 255480
 cosmetic: 262113
 scriptlet: 54686
 html: 2269
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83085-160, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 5m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103123-24345, now
  adguard-generic: 84574-4303, now
  adguard-mobile: 9970-65, now
  adguard-spyware-url: 1733-126, now
  adguard-spyware: 85381-1614, now
  block-lan: 64-0, now
  curben-phishing: 471-1, 5m
  adguard-social: 23187-1620, now
  adguard-cookies: 32102-32102, now
  ublock-cookies-adguard: 1787-32, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 269-21, never
  ublock-filters: 40638-490, 5m Δ
  ublock-badware: 11586-6, 5m Δ
  ublock-privacy: 1283-23, 5m Δ
  ublock-unbreak: 2530-6, 5m Δ
  ublock-quick-fixes: 164-11, 5m Δ
  easylist: 85780-2276, 5m Δ
  easyprivacy: 53139-23790, 5m Δ
  urlhaus-1: 25615-0, 5m
  plowe-0: 3540-1491, now
filterset (user): [array of 290 redacted]
trustedset:
 added: [array of 47 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 40 redacted]
hostRuleset:
 added: [array of 583 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1659 ms
 maxAssetCacheWait: 1295 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 61
 no-remote-fonts: true
 network:
  x.com: 59
  twimg.com: 2
 extended:
  ##div.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.r-1kqtdi0…
  ##div[aria-label="Trending"] > div div:has(> aside[aria-label="S…
  ##html:style(overflow:auto!important)
  ##+js(set-cookie, twtr_pixel_opt_in, N)
  ##+js(json-prune-xhr-response, data.home.home_timeline_urt.instr…
  ##+js(json-prune-xhr-response, data.search_by_raw_query.search_t…
  ##+js(json-prune-xhr-response, data.threaded_conversation_with_i…
  ##+js(json-prune-xhr-response, data.user.result.timeline_v2.time…
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
```
</details>

**Comment by Yuki2718** [comment]
> * I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

Your Configuration is heavily customized, do you REALLY tested with default settinigs?

**Comment by Yuki2718** [comment]
>  extended:
>   ##div.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.r-1kqtdi0…

No idea what it is, Google search returned this: https://www.reddit.com/r/Twitter/comments/1cu6x6d/hiding_sidebars_on_the_new_x/

I never had trouble in deleting posts on X.
