### ISSUE TITLE
yagpdb.xyz: nuisances

### ISSUE THREAD

**Issue by Happypig375** [uBlockOrigin/uAssets#25558]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://docs.yagpdb.xyz/reference/templates/functions
```

### Description

The Cookie Notice on bottom right is still shown even with `EasyList/uBO – Cookie Notices` enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0f15894b-f43b-4a2b-86e0-de10f29eaaa8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 153885
 cosmetic: 94418
 scriptlet: 27137
 html: 2007
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52233-188, 22h.24m
  ublock-cookies-easylist: 1787-13, 22h.24m
 default:
  user-filters: 0-0, never
  ublock-filters: 40640-141, now Δ
  ublock-badware: 11586-6, now Δ
  ublock-privacy: 1283-22, now Δ
  ublock-unbreak: 2528-1, now Δ
  ublock-quick-fixes: 166-0, now Δ
  easylist: 85783-185, now Δ
  easyprivacy: 53139-62, now Δ
  urlhaus-1: 26520-0, 22h.44m
  plowe-0: 3541-992, 22h.44m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 992 ms (selfie)
 maxAssetCacheWait: 227 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
docs.yagpdb.xyz##div[data-testid="cookies-dialog"]
```
