### ISSUE TITLE
vod.tvp.pl: breakage

### ISSUE THREAD

**Issue by sratadobrytatapl** [uBlockOrigin/uAssets#25551]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vod.tvp.pl/programy,88/rolnik-szuka-zony-odcinki,284514/odcinek-4,S11E04,1633934`

### Category

breakage

### Description

missing video player

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 153806
 cosmetic: 67198
 scriptlet: 23234
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt: 10994-26, 8m
  https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt: 145-1, 8m
  ublock-quick-fixes: 168-0, 8m
 default:
  user-filters: 5-0, never
  POL-0: 8761-31, 8m
  POL-2: 1280-12, 8m
  easylist: 85783-594, 8m
  easyprivacy: 53142-641, 8m
  plowe-0: 3541-9, 8m
  ublock-badware: 11580-6, 8m
  ublock-filters: 40359-299, 1h.24m Δ
  ublock-privacy: 1290-22, 24m
  ublock-unbreak: 2468-2, 8m
  urlhaus-1: 26520-0, 8m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 46 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4298 ms
 maxAssetCacheWait: 193 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  tvp.pl: 2
  gemius.pl: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  snrbox.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by garry-ut99** [comment]
A known old breakage, caused by this filter list: `https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt`, it was reported already a long time ago two times:
- https://github.com/olegwukr/polish-privacy-filters/issues/149
- https://github.com/MajkiIT/polish-ads-filter/issues/21962

but it was never fixed, like many other breakages caused by this filter list, because the filter lists is unmaintentained for a long time already, as the last  commit was 10 months ago (by the way the owner is Urkainian).

Hence either this filter list should not be used anymore, or you can handle breakages yourself, you can fix the current breakage and few others by adding these exception filters to "My filters": https://github.com/MajkiIT/polish-ads-filter/issues/21962#issuecomment-1722222816.
