### ISSUE TITLE
paypal.com: breakage

### ISSUE THREAD

**Issue by Frank-Steiner** [uBlockOrigin/uAssets#25550]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.paypal.com/`

### Category

breakage

### Description

After upgrading from FF 115 esr to 128 esr every login attempt to my paypal account requires SMS authentification, although the device should be remembered. Deleting all cookies/storage and removing the "known devices" and going through the "you are logging in from a new device, remember it?" dialog of paypal, it won't work.
But when I am on the "SMS authentification required" page (after entering my password) and disable uBlock, then go back and enter my password again, I'm getting in without the SMS dialog.
So, whenever enabling uBlock, I'm asked for the SMS authentification, whenever I disable it, I get in.

It seems that with FF 128 uBlock is blocking something that Firefox tries to send so that paypal can identify the device as known. Maybe uBlock considers this as tracking information or sth. and therefore blocks it.

I can workaround it by disabling uBlock, but in case you would like to figure out what this piece of data is that uBlock falsely blocks, let me know if I can help debugging it.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 128
filterset (summary):
 network: 154297
 cosmetic: 53641
 scriptlet: 21174
 html: 2007
listset (total-discarded, last-updated):
 added:
  DEU-0: 7527-37, now
  ublock-quick-fixes: 165-11, 7m Δ
 default:
  user-filters: 12-1, never
  ublock-filters: 40636-130, 7m Δ
  ublock-badware: 11586-6, 7m Δ
  ublock-privacy: 1283-22, 7m Δ
  ublock-unbreak: 2528-1, 7m Δ
  easylist: 85781-185, 7m Δ
  easyprivacy: 53142-62, 7m Δ
  urlhaus-1: 26520-0, now
  plowe-0: 3541-992, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 216 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 121
 network:
  paypal.com: 114
  sprig.com: 7
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
