### ISSUE TITLE
linkedin.com: breakage

### ISSUE THREAD

**Issue by orochiheat** [uBlockOrigin/uAssets#25555]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.linkedin.com/feed/`

### Category

breakage

### Description

Anything related to search is broken. Have to then reload the page with CTRL+F5

### Other extensions used

Duckduckgo, PrivacyBadger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/c0edd2c0-4911-4005-9b92-f496b0bfbc82)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 153629
 cosmetic: 48491
 scriptlet: 21165
 html: 2025
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 40643-130, now
  ublock-badware: 11586-6, now
  ublock-privacy: 1291-22, now
  ublock-unbreak: 2526-1, now
  easylist: 85788-185, now
  easyprivacy: 53135-62, now
  urlhaus-1: 28190-0, now
  plowe-0: 3541-992, now
  ublock-quick-fixes: 166-11, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 23 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1174 ms (selfie)
 maxAssetCacheWait: 590 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  linkedin.com: 6
  cedexis.com: 1
  clean.gg: 1
  script.ac: 1
  xlgmedia.com: 1
 extended:
  ##.ad-banner-container
  ##.ad-banner
  ##a[href^="https://ad.doubleclick.net/"]
  ##div.feed-shared-update-v2:has(span.update-components-actor__su…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by orochiheat** [comment]
I tried on a private profile with uBO and default settings and it did not
work. I tried with only a private profile and it did not work (tried this
before). This leads me to believe it's a firefox issue.

**Comment by mapx-** [comment]
Did you disable ETP in firefox ?

**Comment by orochiheat** [comment]
That's the shield next to the padlock? Yes.

**Comment by mapx-** [comment]
in firefox go to 
`about:preferences#privacy`

![image](https://github.com/user-attachments/assets/f38ceb3e-0e60-4f1e-bfde-bf5589c68c63)
