### ISSUE TITLE
fuckmonstercock.com  [NSFW]

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#2555]
### URL(s) where the issue occurs

`https://fuckmonstercock.com/`

### Describe the issue

Many Ads

### Versions

- Browser/version: Opera Stabe
- uBlock Origin version:  1.16.11

### Settings

uBO's default settings

**Comment by mapx-** [comment]
if you still get ads give us more details

**Comment by PoRtvine** [comment]
https://fuckmonstercock.com/videos/12836858/Eri-Ueno-gets-cum-on-big-ass-cheeks-10-min-after-is-fucked-under-uniform.jsp

Screen:
http://jpeg.im/d8jy
http://jpeg.im/d8jz
