### ISSUE TITLE
wsj.com: ads

### ISSUE THREAD

**Issue by kjjf91** [uBlockOrigin/uAssets#25557]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wsj.com/`

### Category

ads

### Description

The first wide banner under the WSJ title keeps appearing

### Other extensions used

firefox relay

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="983" alt="Screenshot 2024-10-07 at 13 34 05" src="https://github.com/user-attachments/assets/a62b2cf9-9ab0-44a2-83ac-28b26655ae12">

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 153630
 cosmetic: 48492
 scriptlet: 21168
 html: 2025
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 40644-130, now
  ublock-badware: 11581-6, now
  ublock-privacy: 1291-22, now
  ublock-unbreak: 2532-1, now
  ublock-quick-fixes: 167-11, now
  easylist: 85790-185, now
  easyprivacy: 53135-62, now
  urlhaus-1: 28190-0, now
  plowe-0: 3541-992, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 198 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 38
 no-popups: true
 network:
  wsj.com: 2
  ads-twitter.com: 2
  amazon-adsystem.com: 2
  bing.com: 1
  brandmetrics.com: 1
  cxense.com: 2
  d1z2jf7jlzjs58.cloudfront.net: 1
  d2xupcbyjjjfoa.cloudfront.net: 2
  datadome.co: 1
  demdex.net: 2
  dianomi.com: 2
  doubleclick.net: 2
  dowjoneson.com: 1
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  licdn.com: 1
  ml314.com: 1
  newrelic.com: 2
  newscgp.com: 2
  outbrain.com: 2
  redditstatic.com: 1
  rlcdn.com: 1
  sc-static.net: 1
  scorecardresearch.com: 1
  typekit.net: 1
 extended:
  ##.adWrapper
  ##.staticAd
  ##.dianomi_context
  ##.OUTBRAIN
  ##div[id^="wrapper-AD_"]
  ##.uds-ad-container
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Please respect the prerequisites and don't open duplicated issue: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+wsj.com+

**Comment by stephenhawk8054** [comment]
@Yuki2718 Btw, I can only reproduce this issue when using VPN to US. They counter quite regularly too.
