### ISSUE TITLE
dotabuff.com: ads

### ISSUE THREAD

**Issue by confeden** [uBlockOrigin/uAssets#25553]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dotabuff.com/`

### Category

ads

### Description

3 gif banners (left, top and right side)

### Other extensions used

none other ad blocking ext

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/aee452aa-bcae-4894-b8c3-d786c34af6ac)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 153890
 cosmetic: 94418
 scriptlet: 28731
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52240-126, now
  ublock-cookies-easylist: 1787-13, now
 default:
  user-filters: 0-0, never
  ublock-filters: 40364-269, now Δ
  ublock-badware: 11584-6, now Δ
  ublock-privacy: 1296-22, now Δ
  ublock-unbreak: 2469-2, now Δ
  ublock-quick-fixes: 168-0, now Δ
  easylist: 85783-579, now Δ
  easyprivacy: 53142-689, now Δ
  urlhaus-1: 26520-0, 1m
  plowe-0: 3541-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 181 ms (selfie)
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  elo.io: 6
  google-analytics.com: 1
 extended:
  ##+js(prevent-fetch, ads)
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by confeden** [comment]
Russia

**Comment by stephenhawk8054** [comment]
Test

```adb
||attr-shift.dotabuff.com^
```

**Comment by confeden** [comment]
yes it works
now ads is gone
