### ISSUE TITLE
top.gg: breakage

### ISSUE THREAD

**Issue by Happypig375** [uBlockOrigin/uAssets#25559]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://top.gg/bot/1099712961733472327/vote
```

### Description

After logging in with a Discord account,
Half the time it displays "You will be able to vote after this ad." (stuck here) and the other half of the time it displays "You can vote now!" (skipping the ad).

It may be a timing issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/529ef54b-06ca-41cb-bc8f-a50acb3d5b3e)
![image](https://github.com/user-attachments/assets/391a9e25-20d9-49a8-a10f-e7c7f0f9c7f4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 150594
 cosmetic: 48468
 scriptlet: 21146
 html: 2007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40637-130, 2m
  ublock-badware: 11586-6, 2m
  ublock-privacy: 1291-22, 2m
  ublock-unbreak: 2526-1, 2m
  ublock-quick-fixes: 134-11, 2m
  easylist: 85686-185, 2m
  easyprivacy: 53116-62, 2m
  urlhaus-1: 25255-0, 2m
  plowe-0: 3541-992, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2418 ms
 maxAssetCacheWait: 39 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
in quick succession I get "You will be able to vote after this ad." and immediately "You can vote now!", so it seems to be some timing issue or another issue on your end

try resetting uBO to defaults and test again disabling any other extension
