### ISSUE TITLE
gr.pinterest.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#25556]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gr.pinterest.com/`

### Category

nuisance

### Description

Popup to connect with Google account. Other annoyances lists don’t cover this type of elements.

Suggested rule:
pinterest.com###credential_picker_container

You already have it for other sites in uBlock filters -  Annoyances.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-10-07 at 11-40-56 Pinterest](https://github.com/user-attachments/assets/4b680700-dc2d-4c35-84f4-fac5a9df1c76)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 115
filterset (summary):
 network: 388479
 cosmetic: 266220
 scriptlet: 54723
 html: 2284
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 65368-4759, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 112794-132, 1h.48m
  https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt: 908-24, now
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 555-0, 1h.37m
  adguard-generic: 84567-6261, now
  adguard-mobile: 9966-11, now
  adguard-spyware-url: 1733-244, now
  adguard-spyware: 85384-169, now
  block-lan: 64-0, now
  curben-phishing: 515-4, now
  adguard-cookies: 32118-61, now
  ublock-cookies-adguard: 1796-28, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40638-281, 48m Δ
  ublock-badware: 11586-446, 48m Δ
  ublock-privacy: 1291-336, 48m Δ
  ublock-unbreak: 2526-65, 48m Δ
  ublock-quick-fixes: 166-11, 48m Δ
  easylist: 85788-39235, 48m Δ
  easyprivacy: 53135-24950, 48m Δ
  urlhaus-1: 28190-0, now
  plowe-0: 3541-1872, now
  GRC-0: 1119-18, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user- https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1
supportStats:
 allReadyAfter: 62513 ms (selfie)
 maxAssetCacheWait: 3391 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  pinterest.com: 3
 extended:
  ##body:style(overflow: visible!important; touch-action: auto!imp…
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by stephenhawk8054** [comment]
There's `@@||pinterest.com^$generichide` in EL, so could be fixed in EL annoyance lists.

cc @Yuki2718
