### ISSUE TITLE
stadt-bremerhaven.de: detection

### ISSUE THREAD

**Issue by Paredroi** [uBlockOrigin/uAssets#25562]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://stadt-bremerhaven.de/postbank-zinsaktion-fuer-tagesgeld/`

### Category

detection

### Description

Message below website, see screenshot

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/user-attachments/assets/66ae6e42-9082-4bb2-9017-26960456433b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 226890
 cosmetic: 111530
 scriptlet: 39861
 html: 2026
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2678-0, now
  adguard-generic: 84126-516, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-social: 16783-27, 8m
  adguard-spyware-url: 1733-244, now
  adguard-spyware: 70124-21577, now
 default:
  user-filters: 90-0, never
  ublock-filters: 40646-3629, 8m Δ
  ublock-badware: 11581-125, 8m Δ
  ublock-privacy: 1292-71, 8m Δ
  ublock-unbreak: 2529-77, 8m Δ
  easylist: 85792-2118, 8m Δ
  easyprivacy: 53135-151, 8m Δ
  plowe-0: 3541-1009, now
  DEU-0: 7527-41, now
  urlhaus-1: 28410-0, now
  ublock-quick-fixes: 168-14, 8m Δ
filterset (user): [array of 90 redacted]
trustedset:
 added: [array of 36 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1143 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  stadt-bremerhaven.de: 2
  google-analytics.com: 1
  google.com: 12
  googlesyndication.com: 3
  googletagmanager.com: 2
  storage.googleapis.com: 2
 extended:
  ##.aawp
  ##.psw-container
  ##img[width="468"][height="60"]
  ##a[href^="https://telegram.me/share/url?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="whatsapp://send?text="]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.social-tooltip
  ###shr-btns
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by Paredroi** [comment]
Hm, strangely enough, that works. I'll have to keep looking for the exact reason, sorry for reporting it!
