### ISSUE TITLE
caminteresse.fr: nuisance

### ISSUE THREAD

**Issue by MoustaphaElPsyCongroo** [uBlockOrigin/uAssets#25568]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.caminteresse.fr/societe/dans-ce-pays-s-evader-de-prison-est-un-droit-mais-pourquoi-11197598/`

### Category

nuisance

### Description

Cookie notice appears on load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-10-07 23_34_19-NVIDIA GeForce Overlay DT](https://github.com/user-attachments/assets/9a44440e-3ba2-4692-8936-0a7fe791d0ad)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 141710
 cosmetic: 150929
 scriptlet: 50949
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  adguard-generic: 84126-6390, now
  fanboy-cookiemonster: 52242-196, now
  ublock-cookies-easylist: 1796-9, now
  easylist-annoyances: 4807-97, 4m
  easylist-notifications: 3446-7, now
  ublock-annoyances: 5987-22, 4m
 default:
  user-filters: 12-2, never
  ublock-filters: 40391-126, now
  ublock-badware: 11579-6, now
  ublock-privacy: 1305-23, now
  ublock-unbreak: 2471-3, now
  ublock-quick-fixes: 170-13, now
  easylist: 85824-696, now
  urlhaus-1: 28410-0, now
  plowe-0: 3541-0, now
  FRA-0: 25608-177, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 724 ms (selfie)
 maxAssetCacheWait: 87 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  opti-digital.com: 1
  pmdstatic.net: 1
 extended:
  ##.grid-main > div.quiz:has(> div#BeOpWidget)
  ##body .ads
  ##.OUTBRAIN
  ##[data-ads-core]
  ##.coreads-wrapper
  ##.ads-core-placer
  ##.ads-placeholder
  ##.ads-text
  ##.BeOpWidget
```
</details>

**Comment by stephenhawk8054** [comment]
Need

```adb
@@||googletagmanager.com/gtm.js$script,domain=caminteresse.fr
@@||tra.scds.pmdstatic.net/sourcepoint/*/sourcepoint.esm.min.js$script,domain=caminteresse.fr
```

to display cookie notices and play the media.
