### ISSUE TITLE
ita-airways.com: breakage

### ISSUE THREAD

**Issue by federicociro** [uBlockOrigin/uAssets#25561]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ita-airways.com/es_es/booking.html`

### Category

breakage

### Description

ITA Airways login does not work with uBlock enabled :(

### Other extensions used

Privacy Badger, also disabled temporally for testing purposes. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 156256
 cosmetic: 55381
 scriptlet: 21694
 html: 2026
listset (total-discarded, last-updated):
 added:
  spa-0: 4080-26, now
  spa-1: 6024-256, now
 default:
  user-filters: 0-0, never
  ublock-filters: 40648-130, now
  ublock-badware: 11581-6, now
  ublock-privacy: 1292-22, now
  ublock-unbreak: 2529-1, now
  ublock-quick-fixes: 168-11, now
  easylist: 85792-185, now
  easyprivacy: 53135-62, now
  urlhaus-1: 28410-0, now
  plowe-0: 3541-992, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 543 ms (selfie)
 maxAssetCacheWait: 136 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  ita-airways.com: 2
  adobedc.net: 1
  go-mpulse.net: 1
  googletagmanager.com: 3
  kleecks-stats.com: 1
```
</details>

**Comment by mapx-** [comment]
What exactly does not work ? Provide all the steps to get the issue / breakage

**Comment by gorhill** [comment]
> - [x] I did not answer truthfully to ALL the above checkboxes.

Since you checked that box, did you first confirm that the issue is not caused by Firefox Enhanced Tracking Protection (FETP)? If not, disable it for that site then try to log in again. If the issue persists, you can re-enable FETP for that site.

**Comment by mapx-** [comment]
> ITA Airways login does not work with uBlock enabled

no issue on my end => tested in chrome / firefox

reset uBO to defaults, disable ALL other extensions, disable ETP in firefox (if custom => unselect all the entries)

**Comment by federicociro** [comment]
Thank you @mapx- , it worked now. Closing the Issue.
