### ISSUE TITLE
winfuture.de: ads / breakage / detection

### ISSUE THREAD

**Issue by hammaschlach** [uBlockOrigin/uAssets#25560]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://winfuture.de/`

### Category

ads

### Description

Since today no ad is blocked on this site anymore.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 158399
 cosmetic: 100793
 scriptlet: 29458
 html: 2287
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52241-189, 18m
  ublock-annoyances: 5928-65, 18m
 default:
  user-filters: 9-2, never
  ublock-filters: 40645-130, 18m
  ublock-badware: 11581-6, 18m
  ublock-privacy: 1292-22, 18m
  ublock-unbreak: 2529-1, 18m
  easylist: 85790-185, 18m
  easyprivacy: 53135-62, 18m
  urlhaus-1: 28410-0, 18m
  plowe-0: 3541-992, 18m
  DEU-0: 7527-37, 18m
  ublock-quick-fixes: 167-11, 18m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 25 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 163 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  adpushup.com: 1
  chartbeat.com: 1
  consentmanager.net: 2
  criteo.com: 1
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  qualitymedianetwork.de: 1
  taboola.com: 1
 extended:
  ##.billboard
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(json-prune, adtagparameter, enabled)
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
```
</details>

**Comment by sweethoneybeee** [comment]
Big thanks for your help and all the best for all of you!

**Comment by sweethoneybeee** [comment]
Winfuture is blocking uBlock Origin again on several news pages: https://winfuture.de/news,147618.html

Would appreciate an update for this case. Please help. Thanks in advance.
