### ISSUE TITLE
http://www.phpbb3bbcodes.com [Anti-Adblock]

### ISSUE THREAD

**Issue by venfare** [uBlockOrigin/uAssets#2556]
### URL(s) where the issue occurs

`http://www.phpbb3bbcodes.com/viewtopic.php?f=14&t=2694`

### Describe the issue

This site use the method from `http://antiblock.org`, although the site has it own method to implementing the anti-adblock based from the post here `http://www.phpbb3bbcodes.com/viewtopic.php?t=2327`. Most post from the site forum cannot be accessed if you turned on the adblocker.

### Screenshot(s)

with uBlock Origin enabled:
![Anti-Adblock](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28129%29.png)

with uBlock Origin disabled:
![Anti-Adblock](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28130%29.png)

### Versions

- Browser/version: Vivaldi 1.15.1147.42 (Stable channel) (64-bit)
- uBlock Origin version: 1.16.8
- uBlock Origin Extra version: 2.72 

### Settings

easier to explain with screenshot:
![dashboard#Setting](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28131%29.png)
![dashboard#Filter_List](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28132%29.png)
![dashboard#/Filter-List-cont](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28133%29.png)
![dashboard#My_Filter](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28134%29.png)
![dashboard#My_Rules](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28135%29.png)
![dashboard#Whitelist](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28136%29.png)

### Notes

Tutorial from post `http://www.phpbb3bbcodes.com/viewtopic.php?t=2327` in case this will help solving the issue (Specific for blocking the content from Adblock user. Cannot be bypassed by disabling javascript):

>First example is how I have done it here.
>
>Open styles/prosilver/template/overall_header.html
>Find:
>
>```
>// ]]>
></script>
>```
>
>Before add:
>
>```
>function gandalf()
>	{
>	if(document.getElementById("gimli").offsetHeight==0)
>	{
>	document.getElementById("block-body").innerHTML="<div class='navbar bg1' style='margin-bottom:4px;margin-top:4px;'><div class='inner'><span class='corners-top'><span></span></span><strong style='color: red; padding:12px;'><span style='font-size: 36px;'>Oops, looks like you are blocking our ads!</span><br /><br /><span style='font-size: 18px;'>Thats not a nice thing to do...<br />Please note that functions and access has been removed because you block our ads.<br />Also notice that Donators doesnt see ads or this message.<br /><br />Regards Stoker</span></strong></div><span class='corners-bottom'><span></span></span></div>";
>	}
>	}
>
>	onload_functions.push('gandalf()');
>	
>	function steve() 
>	{
>	document.getElementById('block-body').style.display = "inline";
>	}
>	onload_functions.push('steve()');
>```
>
>(You need to edit the message to suit your need)
>
>Find:
>
>```
><a name="start_here"></a>
>```
>
>After add:
>
>```
><noscript>
>			<div class='navbar bg1' style='text-align:center; margin-bottom:4px;margin-top:4px;'><div class='inner'><span class='corners-top'><span></span></span><strong style='color: red; padding:12px;'><span style='font-size: 20px;'>You need to enable javascript to browse this site</span></strong></div><span class='corners-bottom'><span></span></span></div>
>			</noscript>
>```
>
>Now we have set up the first part. A script that detects if a specified ID height is zero, in the case the ID is named gimli. 
>This means that you MUST wrap your ad code in a div with the ID gimli.
>Just like this:
>
>```
><div id="gimli">
>						ad code here
>						</div>
>```
>
>Remember only to do this with 1 ad!
>The script will now detect if the height of this div is zero which it will be if you block the ad inside it.
>Also we have done the first part ensuring that people doesnt bypass our script by disabling javascript >in their browser.
>
>Last step is to decide which content we want to hide for ad-block users.
>All we need to do is the wrap the content we want to hide in a div with the correct ID and style.
>Just like this:
>
>```
><div id="block-body" style="display:none;">
>the content you want to hide here
></div>
>```

Based from the guide at this post `http://www.phpbb3bbcodes.com/viewtopic.php?t=2327` if the website script detect the ads space height equal to 0, then the script will block the content, in this case forum post will not be showed and instead will display "turn off adblocker" message.

**Comment by mapx-** [comment]
We need a test account

**Comment by okiehsch** [comment]
Fix works with Chrome and Firefox on my end without a test account.

**Comment by venfare** [comment]
@okiehsch it worked thank you.

before [9b59851](https://github.com/uBlockOrigin/uAssets/commit/9b59851349fce50a7d59f842cac3997901e6adb3)

![Before 9b59851](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28129%29.png)

after [9b59851](https://github.com/uBlockOrigin/uAssets/commit/9b59851349fce50a7d59f842cac3997901e6adb3)

![After 9b59851](https://raw.githubusercontent.com/venfare/images/master/Screenshot%20%28139%29.png)
