### ISSUE TITLE
picrew.me: ads

### ISSUE THREAD

**Issue by CyanSalvatore** [uBlockOrigin/uAssets#25565]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://picrew.me/en/search?s=2`

### Category

ads

### Description

There are ad leftovers with uBO still present.
![image](https://github.com/user-attachments/assets/4f43ec74-3ea6-4b56-9e2a-d900378d549a)

### Other extensions used

![image](https://github.com/user-attachments/assets/400c9cc7-faaa-4715-addb-6d51e2c39c2e)
![image](https://github.com/user-attachments/assets/8dc6ae59-cca1-46ea-87d4-26f8693ad7ea)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 153890
 cosmetic: 48492
 scriptlet: 22791
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 85824-473, 19m Δ
  easyprivacy: 53135-640, 19m Δ
  plowe-0: 3541-0, now
  ublock-badware: 11579-6, 19m Δ
  ublock-filters: 40391-363, 19m Δ
  ublock-privacy: 1305-22, 19m Δ
  ublock-quick-fixes: 170-0, 19m Δ
  ublock-unbreak: 2471-0, 19m Δ
  urlhaus-1: 28410-0, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1990 ms
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 31
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 network:
  picrew.me: 1
  adingo.jp: 1
  anymind360.com: 1
  cloudflare.com: 6
  content-loader.com: 2
  criteo.com: 1
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  gstatic.com: 9
  html-load.com: 3
  script.ac: 1
  sentry.io: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
working fine only in firefox

for chrome could be:

```
picrew.me##+js(aost, btoa, html-load.com)
picrew.me##+js(aopr, alert)
```

**Comment by stephenhawk8054** [comment]
Ah ok, I can reproduce now. I'll update in AS section.
