### ISSUE TITLE
[nsfw] w.sslkn.icu: ads

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25573]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://w.sslkn.icu/models/notsoamateur/`

### Category

ads

### Description

Banner ads

### Other extensions used

None 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 1285843
 cosmetic: 259423
 scriptlet: 56125
 html: 2305
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 137232-0, 1h.50m
  https://hosts.ubuntu101.co.za/domains.list: 539818-24100, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 107085-270, 1m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2672-2, 1h.50m
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 452-39, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 85811-48506, now
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/refs/heads/main/antitypo.txt: 2071-33, 1m
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4037-36, 1m
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  https://urlhaus.abuse.ch/downloads/text/: 275011-0, now
  adguard-generic: 84562-8822, now
  [18 lists not shown]: [too many]
 default:
  ublock-filters: 41124-344, 1h.50m Δ
  ublock-badware: 11575-1522, 1h.50m Δ
  ublock-privacy: 1299-101, 1h.50m Δ
  ublock-unbreak: 2532-3, 1h.50m Δ
  ublock-quick-fixes: 169-12, 1h.50m Δ
  adguard-mobile: 9968-887, now
  easylist: 85844-30157, 1h.50m Δ
  easyprivacy: 53135-10351, 1h.50m Δ
  urlhaus-1: 28630-258, now
  plowe-0: 3541-3528, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7388 ms
 maxAssetCacheWait: 4098 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  sslkn.icu: 1
  gaveasword.com: 2
  rdrctgoweb.com: 2
  yadro.ru: 1
  yandex.ru: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `RU AdList` list and test again.

**Comment by Rachitidk** [comment]
Already enabled

**Comment by garry-ut99** [comment]
`sslkn.icu##.spot`

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
I checked both the mobile and desktop versions of the layout of this page, and did not find any missed ads. But I did it in the default configuration uBO (+RU AdList), whereas the problem is stated in the custom configuration.

**Comment by Rachitidk** [comment]
Reopen the issue.
Sorry for the late reply here the picture after disabling all custom filter.
![1000107490](https://github.com/user-attachments/assets/2b6ab650-74a3-4eea-a8bd-81623ca15383)

**Comment by mapx-** [comment]
that ad is self-promotion (for their app) and I get it only on mobile.

`||sslkn.icu/contents/banners/`

**Comment by Rachitidk** [comment]
> `sslkn.icu##.spot`

This worked, add it to the list.

**Comment by Rachitidk** [comment]
> that ad is self-promotion (for their app) and I get it only on mobile.
> 
> `||sslkn.icu/contents/banners/`

This one is not working properly.

![1000107495](https://github.com/user-attachments/assets/7e8a0bad-02fa-41bd-89b3-dd07ead81780)

**Comment by dimisa-RUAdList** [comment]
Since this is not a third party ad but an announcement of their own app, I added a rule to BitBlock: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

https://github.com/easylist/ruadlist/commit/e170a783ff0d258631df291a4232dc0b0557e196
