### ISSUE TITLE
tieba.baidu.com: breakage

### ISSUE THREAD

**Issue by thetristanteng** [uBlockOrigin/uAssets#25577]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://tieba.baidu.com/f?kw=%E9%AB%98%E9%80%9A&ie=utf-8
https://tieba.baidu.com/f?kw=wp7&frs=yqtb
```

### Description

This site tieba.baidu.com is a SNS in Chinese community.
UBO blocked preview images in front page of all sub-forum.

### Other extensions used

1Password
Vimium
Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-10-08 193358](https://github.com/user-attachments/assets/02789441-d4df-4493-adb1-7b872f224c44)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.60.0
Firefox: 130
filterset (summary):
 network: 183653
 cosmetic: 100759
 scriptlet: 39397
 html: 2026
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84565-4211, now
  CHN-0: 25379-117, 15m
 default:
  user-filters: 3-0, never
  ublock-filters: 40620-130, 1h.39m Δ
  ublock-badware: 11581-6, 1h.39m Δ
  ublock-privacy: 1298-22, 1h.39m Δ
  ublock-unbreak: 2529-1, 1h.39m Δ
  ublock-quick-fixes: 169-11, 1h.39m Δ
  easylist: 85844-2120, 1h.39m Δ
  easyprivacy: 53135-151, 15m
  urlhaus-1: 25255-0, 15m
  plowe-0: 3541-1009, 15m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5533 ms (selfie)
 maxAssetCacheWait: 92 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 60
 network:
  github.com: 60
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings + "Adguard Chinese" list

**Comment by thetristanteng** [comment]
> Test again in a new Firefox profile with only uBO and its default settings + "Adguard Chinese" list

It's seems worked. Thanks.
