### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Ylli24** [uBlockOrigin/uAssets#25586]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=w39qx5X_Owg&list=PLDd5Brqj2yem2jiJORY3vu8WO7Bbie7ZQ&index=5`

### Category

ads

### Description

The adds show but its just in a black background instead of the add itself and also no sound comes from the add i just see the 15second timer of the add or 30second timer on the bottom of the video where theres the forward,back and pause buttons

### Other extensions used

the opera add blocker which its turned on from a long time ago and the issue is only happening in the last couple weeks or month maybe

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 151267
 cosmetic: 48483
 scriptlet: 22801
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40370-258, 1h.18m Δ
  ublock-badware: 11575-6, 1h.18m Δ
  ublock-privacy: 1309-22, 1h.18m Δ
  ublock-unbreak: 2475-0, 1h.18m Δ
  ublock-quick-fixes: 167-0, 1h.18m Δ
  easylist: 85846-577, 1h.18m Δ
  easyprivacy: 53140-640, 1h.18m Δ
  urlhaus-1: 25780-0, now
  plowe-0: 3541-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3934 ms (selfie)
 maxAssetCacheWait: 169 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  youtube.com: 8
  doubleclick.net: 3
  google.com: 7
  googlesyndication.com: 2
  googlevideo.com: 10
 extended:
  ##.ytp-featured-product
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
```
</details>

**Comment by Ylli24** [comment]
i dont understand how this github works man im just here to report the problem its the first time im in here

**Comment by stephenhawk8054** [comment]
@Ylli24 Please follow the 1st post in the thread: https://github.com/uBlockOrigin/uAssets/issues/20586
