### ISSUE TITLE
yahoo.com: breakage

### ISSUE THREAD

**Issue by TheRoyalScam** [uBlockOrigin/uAssets#25580]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.yahoo.com/`

### Category

breakage

### Description

Page appears blank more than occasionally. Sometimes refresh helps, sometimes it doesn't. Screenshot shows what I see after a refresh, and after hitting the Home button (since Yahoo is set as my Home Page)
![Screenshot 2024-10-08 at 10 02 38 AM](https://github.com/user-attachments/assets/8f2fe5d9-a1eb-4aa2-ab2a-61b189c4d485)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-10-08 at 10 02 38 AM](https://github.com/user-attachments/assets/402abae4-c804-498a-82a5-11175747af95)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 151274
 cosmetic: 48478
 scriptlet: 21161
 html: 2026
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40620-130, 2m Δ
  ublock-badware: 11581-6, 2m Δ
  ublock-privacy: 1298-22, 2m Δ
  ublock-unbreak: 2529-1, 2m Δ
  ublock-quick-fixes: 169-11, 2m Δ
  easylist: 85844-185, 2m Δ
  easyprivacy: 53135-62, 2m Δ
  urlhaus-1: 25780-0, now
  plowe-0: 3541-992, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 864 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  yimg.com: 2
 extended:
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(set-attr, img.caas-lazy[data-src]:not([src]), src, [data-s…
  ##+js(set-constant, rapidInstance, {})
  ##+js(set-constant, rapidInstance.beaconLinkViews, noopFunc)
  ##+js(set-constant, rapidInstance.beaconClick, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25579#issuecomment-2399926965

**Comment by arejfour** [comment]
I'm having the same problem but it only occurs in Firefox. No problem with Chrome, Edge, or Opera. I have to disable UBO on the Yahoo web page to alleviate the problem.

**Comment by stephenhawk8054** [comment]
Already fixed in that thread. Wait about 5-6 hours and update the filter lists again.

**Comment by arejfour** [comment]
Thanks for the help. Have a nice day.
    On Tuesday, October 8, 2024 at 10:49:35 AM EDT, stephenhawk8054 ***@***.***> wrote:   

 


Already fixed in that thread. Wait about 5-6 hours and update the filter lists again.
