### ISSUE TITLE
football.fantasysports.yahoo.com: breakage

### ISSUE THREAD

**Issue by ben4643** [uBlockOrigin/uAssets#25582]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://football.fantasysports.yahoo.com/f1/848491/4`

### Category

breakage

### Description

When clicking into a players details on yahoo fantasy (little page icon to see stats, news, etc.) window loads in front of page for a split second then appears to go completely white with the background of the rest of the page being grey. Clicking out of the window returns me to team page like normal but unable to do anything inside player details window

### Other extensions used

Lastpass
Dark Reader (Turned off dark reader and confirmed issue was still present with ublock enabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

My team page to set lineup
![image](https://github.com/user-attachments/assets/1226641f-1b99-4500-a677-63ea11308d36)

Clicking into blue page icon next to Jauan Jennings (UBO enabled)
![image](https://github.com/user-attachments/assets/e42773b8-064e-4a6a-8790-582f24365d37)

What clicking the blue page icon is supposed to look like (UBO disabled)
![image](https://github.com/user-attachments/assets/26df0f65-99ff-41a8-9a31-c0c80da8a416)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 151279
 cosmetic: 48482
 scriptlet: 21180
 html: 2027
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 165-10, 12m Δ
 default:
  user-filters: 3-0, never
  ublock-filters: 40633-130, 12m Δ
  ublock-badware: 11581-6, 12m Δ
  ublock-privacy: 1302-22, 12m Δ
  ublock-unbreak: 2534-1, 12m Δ
  easylist: 85846-185, 12m Δ
  easyprivacy: 53140-62, 12m Δ
  plowe-0: 3541-992, now
  urlhaus-1: 25780-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 116 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 307 ms (selfie)
 maxAssetCacheWait: 77 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  yahoo.com: 14
  ay.delivery: 1
  clean.gg: 1
  doubleclick.net: 1
  yahoodns.net: 1
  yimg.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/issues/25579#issuecomment-2400092816

**Comment by ben4643** [comment]
Apologies didnt notice the yahoo.com issue from earlier today when clicking the find similar reports button. Force updating worked. Thanks for quick response

**Comment by bidet-sandy** [comment]
football.fantasysports.yahoo.com on the League page and scrolling down causes every button on the page to become non-interactive while any sort of filtering is enabled with uBOL. Setting uBOL to no filtering allows it to work. Changing tabs and going back in while filtering is enabled causes the screen to go completely white. 
URL: https://football.fantasysports.yahoo.com/f1/155178
Steps to reproduce: Don't reduce optimal or basic filtering in uBOL to break the page. Set no filtering to make the page usable.

**Comment by gothic-bum** [comment]
@bidet-sandy 

Not everyone is familiar with the site and knows what the "League page" is.

Please post the exact URL where the issue occurs and the specific steps necessary to reproduce the issue.

**Comment by stephenhawk8054** [comment]
This site requires proper accounts to reproduce the issues, so without having those accounts, we can't investigate further.
