### ISSUE TITLE
hiraethtranslation.com: detection

### ISSUE THREAD

**Issue by Salvora** [uBlockOrigin/uAssets#25588]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://hiraethtranslation.com
```

### Description

I have reported this before, but I think website got updated and I am getting this popup now.
https://github.com/uBlockOrigin/uAssets/issues/24625

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e40275b4-9399-4ca7-9a48-049b4ff754a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 131
filterset (summary):
 network: 175876
 cosmetic: 175847
 scriptlet: 46855
 html: 2027
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 2326-6, 23h.45m
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 23h.45m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103299-18139, 8d.21h.37m
  adguard-generic: 84122-4261, 1d.8h.45m
  fanboy-cookiemonster: 68897-68842, 3d.11h.57m
  ublock-cookies-easylist: 1785-13, 5d.13h.57m
  TUR-0: 11424-42, 1d.8h.45m
 default:
  user-filters: 18-1, never
  ublock-filters: 40629-163, 1h.17m Δ
  ublock-badware: 11577-6, 1h.17m Δ
  ublock-privacy: 1277-22, 1h.17m Δ
  ublock-unbreak: 2534-0, 1h.17m Δ
  ublock-quick-fixes: 171-0, 1h.17m Δ
  easylist: 85846-2140, 1h.17m Δ
  easyprivacy: 53140-285, 1h.17m Δ
  urlhaus-1: 25255-0, 23h.45m
  plowe-0: 3541-1009, 4h.17m
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 8 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 contextMenuEnabled: false
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 990 ms (selfie)
 maxAssetCacheWait: 553 ms
 cacheBackend: indexedDB
```
</details>

**Comment by D4niloMR** [comment]
It's caused by AdGuard – Ads list: `hiraethtranslation.com##+js(prevent-fetch, pagead2.googlesyndication.com)`

But it should work now with the new filter.
