### ISSUE TITLE
cram.com: breakage

### ISSUE THREAD

**Issue by kk0krishna** [uBlockOrigin/uAssets#25585]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cram.com/`

### Category

breakage

### Description

Context meunu of websites not opening,
 not able to log in in website
![image](https://github.com/user-attachments/assets/08e80393-5c1f-4757-ab0d-dac006ebc2e3)
icon not clicable

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 150750
 cosmetic: 48496
 scriptlet: 21171
 html: 2026
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 40650-130, 54m Δ
  ublock-badware: 11581-6, 54m Δ
  ublock-privacy: 1292-22, 54m Δ
  ublock-unbreak: 2529-1, 54m Δ
  easylist: 85842-185, 54m Δ
  easyprivacy: 53135-62, 54m Δ
  urlhaus-1: 25255-0, 54m
  plowe-0: 3541-992, 54m
  ublock-quick-fixes: 168-11, 54m Δ
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 45 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 981 ms (selfie)
 maxAssetCacheWait: 147 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  cookielaw.org: 2
  googletagmanager.com: 1
  quantserve.com: 1
  sentry-cdn.com: 2
  wurfl.io: 1
 extended:
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(json-prune-xhr-response, data.viewer.instream_video_ads da…
```
</details>

**Comment by mapx-** [comment]
test

```
@@||googletagmanager.com/gtm.js$script,domain=cram.com
@@||googletagmanager.com/gtag/js$script,domain=cram.com
@@||wurfl.io/wurfl.js$script,domain=cram.com
```
