### ISSUE TITLE
cloundminer.online: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#25590]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cloundminer.online/blog/winrar`

### Category

detection

### Description

link = https://currencynews.sbs/hFMe5c

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 124
filterset (summary):
 network: 157086
 cosmetic: 62939
 scriptlet: 22971
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 172-0, never
  IDN-0: 10119-10, 17m
  adguard-mobile: 9960-11, now
  easylist: 85859-652, 17m Δ
  easyprivacy: 53140-650, 17m Δ
  plowe-0: 3541-84, now
  ublock-badware: 11573-7, 17m Δ
  ublock-filters: 40890-401, 17m Δ
  ublock-privacy: 1297-22, 17m Δ
  ublock-quick-fixes: 173-0, 17m Δ
  ublock-unbreak: 2480-2, 17m Δ
  urlhaus-1: 25780-0, 17m
filterset (user): [array of 72 redacted]
trustedset:
 added: [array of 32 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3345 ms
 maxAssetCacheWait: 606 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  alwingulla.com: 2
  googletagmanager.com: 2
  mrmnd.com: 1
  nwemnd.com: 3
  surfe.pro: 1
  webtrafic.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

Respect the prerequisites please.

Comment the full link to here: https://github.com/uBlockOrigin/uAssets/discussions/17361
