### ISSUE TITLE
loadout.tf: ads

### ISSUE THREAD

**Issue by N3er0O** [uBlockOrigin/uAssets#25595]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://loadout.tf/`

### Category

ads

### Description

There is a leftover banner on the right side of the screen.

### Other extensions used

Dark Reader, Bitwarden, Wayback Machine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/4351ebc5-a9a8-493f-b246-889874f2a67e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 130
filterset (summary):
 network: 158847
 cosmetic: 162602
 scriptlet: 35586
 html: 2289
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32092-50, now
  ublock-cookies-adguard: 1799-28, now
  fanboy-cookiemonster: 52259-4027, now
  ublock-cookies-easylist: 1799-1799, now
  adguard-popup-overlays: 27926-251, now
  adguard-mobile-app-banners: 5427-27, now
  adguard-other-annoyances: 14654-331, now
  adguard-widgets: 2696-13, now
  ublock-annoyances: 5928-200, 59m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 40649-130, 59m Δ
  ublock-badware: 11625-6, 59m Δ
  ublock-privacy: 1289-22, 59m Δ
  ublock-unbreak: 2537-1, 59m Δ
  ublock-quick-fixes: 171-10, 59m Δ
  easylist: 85870-187, 59m Δ
  easyprivacy: 53140-62, 59m Δ
  urlhaus-1: 24210-0, now
  plowe-0: 3541-993, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 358 ms (selfie)
 maxAssetCacheWait: 196 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 no-cosmetic-filtering: true
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
>  no-cosmetic-filtering: true

enable the cosmetic filtering

**Comment by N3er0O** [comment]
I swear I *manually* enabled it yesterday night hmm

**Comment by mapx-** [comment]
just to be sure, you could reset uBO to defaults

**Comment by N3er0O** [comment]
Yeah, I'll do that next time. I checked and it was globally disabled again in settings.
