### ISSUE TITLE
[nsfw] 85po.com: detection

### ISSUE THREAD

**Issue by imagayfurryxd** [uBlockOrigin/uAssets#25598]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.85po.com/`

### Category

detection

### Description

the video loads and after ~5 seconds, it'll stop the video and state it's because the site detected an AdBlocker.

### Other extensions used

TTV LOL Pro, Youtube Sponsorblock, Decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 238939
 cosmetic: 193188
 scriptlet: 46490
 html: 2027
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 82803-160, now
  adguard-generic: 84072-4259, now
  adguard-social: 23033-832, now
  CHN-0: 25397-124, 16m
  adguard-spyware-url: 1734-126, now
  adguard-spyware: 70132-21623, now
  adguard-cookies: 32096-32096, now
  adguard-popup-overlays: 27928-27928, now
  adguard-mobile-app-banners: 5427-5427, now
  adguard-other-annoyances: 14656-14656, now
  adguard-widgets: 2696-2696, now
  ublock-cookies-adguard: 1800-28, now
 default:
  user-filters: 24-0, never
  ublock-filters: 40653-477, now
  ublock-badware: 11629-6, now
  ublock-privacy: 1289-22, now
  ublock-unbreak: 2538-3, now
  easylist: 85870-2180, now
  easyprivacy: 53141-222, now
  urlhaus-1: 24210-0, now
  plowe-0: 3541-1010, now
  ublock-quick-fixes: 174-13, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 82 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 627 ms (selfie)
 maxAssetCacheWait: 142 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  85po.com: 2
  googletagmanager.com: 1
  inherentdecide.com: 1
  magsrv.com: 1
```
</details>

**Comment by gorhill** [comment]
Caused by `/player/stats.php?` from EasyPrivacy. This works on my side:

    ||85po.com/player/stats.php?$1p,image,redirect=1x1.gif
