### ISSUE TITLE
[nsfw] yande.re: breakage

### ISSUE THREAD

**Issue by Antedeguemon6** [uBlockOrigin/uAssets#25592]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yande.re/post`

### Category

breakage

### Description

Site loads fine on the first time but trying to open anything on the site (or loading it a second time) simply doesn't work. I'm using firefox.

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 151316
 cosmetic: 52576
 scriptlet: 21700
 html: 2027
listset (total-discarded, last-updated):
 added:
  spa-1: 6017-84, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 40648-130, 2m
  ublock-badware: 11625-6, 2m
  ublock-privacy: 1287-22, 2m
  ublock-unbreak: 2535-1, 2m
  ublock-quick-fixes: 171-10, 2m
  easylist: 85870-187, 2m
  easyprivacy: 53140-62, 2m
  urlhaus-1: 24430-0, 36m
  plowe-0: 3541-992, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 117 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
- no issue on chrome
- on firefox there are lot of delays even disabling uBO => site issue with firefox
