### ISSUE TITLE
playtube.tv: detection

### ISSUE THREAD

**Issue by yavnest** [uBlockOrigin/uAssets#25591]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://playtube.tv/watch/%D0%B1%D0%B8%D0%B3-%D0%B1%D1%80%D0%B0%D0%B4%D1%8A%D1%80-%D1%81%D0%B5%D0%B7%D0%BE%D0%BD-6-%D0%B5%D0%BF%D0%B8%D0%B7%D0%BE%D0%B4-1-08-10-2024_ssFvyUiHPgNbAob.html`

### Category

detection

### Description

Playing the video of this show worked until a few hours ago, now, after clicking the play button, the screen becomes all black and in the middle it says: Please disable AdBlock to watch this video

### Other extensions used

DownThemAll!, Emoji, Dark Reader, HTTPS Everywhere, Unhook, Happy Right-Click, TinEye Reverse Image Search, Video DownloadHelper, To Google Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 100533
 cosmetic: 50459
 scriptlet: 24705
 html: 2288
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  ublock-annoyances: 5928-17, now
  BGR-0: 1040-3, 4m
  curben-phishing: 508-2, 4m
 default:
  user-filters: 3-0, never
  ublock-filters: 40633-130, 4m
  ublock-badware: 11581-6, 4m
  ublock-privacy: 1283-22, now
  ublock-unbreak: 2535-1, 4m
  easylist: 85859-187, 4m
  urlhaus-1: 25780-0, 4m
  plowe-0: 3541-377, now
  ublock-quick-fixes: 171-10, 4m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 21 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3218 ms (selfie)
 maxAssetCacheWait: 1089 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  boostaubeehy.net: 1
  googletagmanager.com: 2
  imasdk.googleapis.com: 3
  tkuckjgdeqr.com: 2
 extended:
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
  ##.ads-placment
```
</details>

**Comment by playonevideo** [comment]
Popups if you click the play button.
`https://playtube.tv/v/ECPvXe`
