### ISSUE TITLE
uBlock filters – Privacy‎

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#256]
The **Privacy‎ list** causes an endless loader to appear over articles on **_qz.com_**. 
This is caused by this filter: `||googletagservices.com/tag/js/gpt.js$script` in the list.

**Error URL:** http://qz.com/877193/how-this-hyderabad-resident-built-an-illegal-marijuana-plantation-in-his-three-bedroom-apartment/

**Screenshot:** http://i.imgur.com/XD1fNxa.png

This can be fixed by changing the above filter (`||googletagservices.com/tag/js/gpt.js$script`) to:
`||googletagservices.com/tag/js/gpt.js$script,domain=~qz.com`

**Versions**

- Browser/version: Chrome 55 
- uBlock Origin version: uBO v1.10.4

**Comment by gotitbro** [comment]
@gorhill Should not hide header(`qz.com###header:style(position: relative !important; top: 0 !important;`), when I scroll up the stickied header does not appear, this is important for navigation.

**Comment by gorhill** [comment]
> when I scroll up the stickied header does not appear, this is important for navigation.

Just like if not using any blocker -- site's design, bring the issue to them.

**Comment by gotitbro** [comment]
A blank space is created at the end of articles on https://qz.com due to the default filter lists in uBO (I can't pinpoint which list causes this but the blank space doesn't appear when using only **EasyList**).

**SS:** https://i.imgur.com/4tWRSHZ.png

**Error URL:** 
https://qz.com/1037297/greyoranges-akash-gupta-inside-a-young-indian-engineers-very-human-struggle-to-build-a-global-robotics-company/

**Comment by gorhill** [comment]
@gotitbro The blank space is because of <https://github.com/gorhill/uBlock/issues/1885>. Workaround is to use a specific cosmetic filter.
