### ISSUE TITLE
autoscout24.nl: ads

### ISSUE THREAD

**Issue by rodrigoAbril** [uBlockOrigin/uAssets#25600]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.autoscout24.nl/`

### Category

ads

### Description

shows adds on the sides, if I block them manually they come back after a few mins

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 149790
 cosmetic: 48496
 scriptlet: 22805
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  easylist: 85870-51, now
  easyprivacy: 53141-655, now
  plowe-0: 3541-377, now
  ublock-badware: 11627-24, now
  ublock-filters: 40395-362, now
  ublock-privacy: 1302-24, now
  ublock-quick-fixes: 177-0, now
  ublock-unbreak: 2480-12, now
  urlhaus-1: 24210-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 552 ms (selfie)
 maxAssetCacheWait: 39 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  autoscout24.nl: 1
  benelph.de: 2
  brwsrfrm.com: 2
  googletagmanager.com: 1
 extended:
  ##.cl-ad-billboard
  ##.ad-top-slot
  ##.ad_block
  ##.adslot
  ##.ad_slot
  ##.advert1
  ##.content-ad
  ##+js(no-setTimeout-if, /Detect|adblock|style\.display|\[native …
```
</details>

**Comment by stephenhawk8054** [comment]
Where are the ads? Please screenshot the whole screen and describe the steps to reproduce in details.

**Comment by gorhill** [comment]
In any case, AdGuard Dutch should be enabled when browsing `.nl` websites.
