### ISSUE TITLE
komikindo.lol: ads

### ISSUE THREAD

**Issue by shinamahiro** [uBlockOrigin/uAssets#25602]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

```yml
https://komikindo.lol/
```

### Category

ads

### Description

still shwowing pop up on every 1-3 minute

### Other extensions used

idm, yt nonstop, auth

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (10)](https://github.com/user-attachments/assets/1edecdbd-e24b-4356-aa38-497519692640)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 220366
 cosmetic: 75700
 scriptlet: 41473
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 84072-7378, now
  adguard-spyware: 70132-20654, now
 default:
  ublock-filters: 40395-317, now
  ublock-badware: 11627-12, now
  ublock-privacy: 1302-24, now
  ublock-unbreak: 2480-2, now
  ublock-quick-fixes: 177-12, now
  easylist: 85872-14655, now
  easyprivacy: 53141-760, now
  urlhaus-1: 28920-0, never
  plowe-0: 3541-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 autoUpdate: false
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1368 ms (selfie)
 maxAssetCacheWait: 284 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 no-popups: true
 network:
  komikindo.lol: 1
  baghlachalked.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  oxhoftarius.com: 5
  taxismaned.top: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@gmarcher Sorry, can you check this?
