### ISSUE TITLE
br.pinterest.com: [unknown]

### ISSUE THREAD

**Issue by Dartmoul** [uBlockOrigin/uAssets#25616]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://br.pinterest.com/`

### Category

[unknown]

### Description

page have uBlock detected

### Other extensions used

one tab
imagus 
translator
darkreader
LanguageTool

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/400962f1-3a41-4104-a498-d0f507e81562)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 169521
 cosmetic: 68990
 scriptlet: 24350
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  RUS-0: 40831-101, 10m Δ
  easylist: 85899-602, 1h.10m Δ
  easyprivacy: 53143-640, 1h.10m Δ
  plowe-0: 3541-0, now
  ublock-badware: 11639-6, 1h.10m Δ
  ublock-filters: 40404-283, 1h.10m Δ
  ublock-privacy: 1296-22, 1h.10m Δ
  ublock-quick-fixes: 180-0, 1h.10m Δ
  ublock-unbreak: 2479-0, 1h.10m Δ
  urlhaus-1: 25255-0, 10m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 31 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1636 ms (selfie)
 maxAssetCacheWait: 155 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Please respect the prerequisites.

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25614
