### ISSUE TITLE
pinterest.de: detection

### ISSUE THREAD

**Issue by affinno** [uBlockOrigin/uAssets#25613]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pinterest.de/`

### Category

breakage

### Description

![grafik](https://github.com/user-attachments/assets/f12a5cac-dfda-4368-9fda-d9cb38d91b71)
Gives me a popup that asks me to disable my adblocker to continue using the site

### Other extensions used

Auto Tab Discard
Beyond 20
Bitwarden Passwortmanager
BlockTube
Chameleon (turned off)
Control Panel for Twitter
Cookie Auto Delete
Dark Reader
Facebook Container
Firefox Relay
Google Search Engine with udm014 preset
Hide Twitter Trends
I don't care about cookies
Indie Wiki Buddy
Keepa
Rivet
Save as PDF
Save Webp as PNG or JPG
Search on Google Lens
Shinigami Eyes
ToS, Didnt Read
Tabliss
XKIT Rewritten
Zoom Image

All on Firefoxe

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/user-attachments/assets/bc1d8cc9-94a1-4c76-8edd-89054c71e4f9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 152073
 cosmetic: 57723
 scriptlet: 21184
 html: 2028
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4088-36, 1h.26m
 default:
  user-filters: 6-0, never
  ublock-filters: 40668-130, 26m Δ
  ublock-badware: 11645-6, 26m Δ
  ublock-privacy: 1289-22, 26m Δ
  ublock-unbreak: 2538-1, 26m Δ
  ublock-quick-fixes: 177-10, 26m Δ
  easylist: 85899-188, 26m Δ
  easyprivacy: 53143-62, 26m Δ
  urlhaus-1: 24115-0, 1h.26m
  plowe-0: 3541-992, 4m
  DEU-0: 7537-37, 1h.26m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 276 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  pinterest.de: 3
  cedexis.com: 1
  pinterest.com: 1
 extended:
  ##[data-grid-item]:has([data-test-pin-id] [data-test-id^="one-ta…
  ##.A6h.tkf.un8.jx-.hs0
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by gorhill** [comment]
> - [x] I did not answer truthfully to ALL the above checkboxes.

Go through all the steps again and this time follow to the letter. I cannot reproduce an anti-content blocker message when navigating `https://www.pinterest.de/`.

If there is a need to be logged in, inform us about this.

**Comment by stephenhawk8054** [comment]
I think we can continue in 1 thread: https://github.com/uBlockOrigin/uAssets/issues/25614
