### ISSUE TITLE
animesonliner4.com: detection

### ISSUE THREAD

**Issue by Brvnogr** [uBlockOrigin/uAssets#25617]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.animesonliner4.com/`

### Category

detection

### Description

detection in videos

### Other extensions used

<img width="235" alt="image" src="https://github.com/user-attachments/assets/62237d73-01f0-4577-94b9-e82ca0c60d82">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/c1c183ac-83f1-4d56-ad25-4d55ed045281)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 251166
 cosmetic: 265788
 scriptlet: 57123
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 82835-82835, 1m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1m
  https://raw.githubusercontent.com/fabiom/br-paywall/master/br-paywall.txt: 25-0, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103073-103057, now
  https://winhelp2002.mvps.org/hosts.txt: 8729-316, 1m
  adguard-cookies: 32106-76, now
  adguard-generic: 84108-7395, 1m
  adguard-mobile: 9965-138, 1m
  adguard-mobile-app-banners: 5431-1122, now
  adguard-other-annoyances: 14661-325, now
  adguard-popup-overlays: 27939-907, now
  adguard-social: 23038-1575, now
  [16 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  easylist: 85899-928, 1m Δ
  easyprivacy: 53143-1089, 1m Δ
  plowe-0: 3541-0, now
  spa-1: 6020-25, 1m
  ublock-badware: 11643-11, 1m Δ
  ublock-filters: 40408-788, 1m Δ
  ublock-privacy: 1302-140, 1m Δ
  ublock-quick-fixes: 180-0, 1m Δ
  ublock-unbreak: 2480-10, 1m Δ
  urlhaus-1: 25205-0, 1m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 305 ms (selfie)
 maxAssetCacheWait: 215 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  jsdelivr.net: 1
  jwpcdn.com: 1
  outbrain.com: 1
  veristouh.net: 1
 extended:
  ##div[style="position: fixed; inset: 0px; z-index: 2147483647; p…
  ##html > div[style="position: fixed; inset: 0px; z-index: 214748…
  ##.ad-title
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/24575
