### ISSUE TITLE
Pinterest pins not loading, or taking really long time to load.

### ISSUE THREAD

**Issue by iirlyaccess** [uBlockOrigin/uAssets#25619]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.pinterest.com
```

### Description

When the page loads, spaces for pins are loaded but only show background colours and no pins this occurs 70-80% of the time.  Sometimes they load partially (top third of the page) further scrolling shows blank, coloured squares where pins should be. Turning off Ublock loads all pins normally)

### Other extensions used

BetterTTV, Checker plus for Gmail, Checker plus for Google Calender

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![brokenPinterest](https://github.com/user-attachments/assets/d35617a9-a8e7-43fa-936a-77cc78da3dee)

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 216415
 cosmetic: 136419
 scriptlet: 39921
 html: 2028
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84056-6238, 1d.22h.30m
  adguard-mobile: 9960-140, 1d.22h.30m
  adguard-spyware: 70132-21514, 1d.22h.30m
  adguard-social: 23027-49, 1d.22h.30m
  fanboy-social: 17041-760, 6d.23h.11m
 default:
  user-filters: 11-0, never
  ublock-filters: 40668-130, 18m Δ
  ublock-badware: 11645-24, 18m Δ
  ublock-privacy: 1276-25, 6d.23h.11m
  ublock-unbreak: 2541-32, 18m Δ
  ublock-quick-fixes: 178-10, 18m Δ
  easylist: 84161-156, 18m Δ
  easyprivacy: 53145-42, 18m Δ
  urlhaus-1: 23990-0, 20h.38m
  plowe-0: 3546-1163, 6d.23h.11m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1255 ms (selfie)
 maxAssetCacheWait: 122 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  github.com: 17
```yaml


```
</details>

**Comment by mapx-** [comment]
already fixed
