### ISSUE TITLE
play.nova.bg: detection

### ISSUE THREAD

**Issue by Hriskata17** [uBlockOrigin/uAssets#25611]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://play.nova.bg/video/igri-na-volyata/season-6/igri-na-volyata-2024-10-09/637012`

### Category

detection

### Description

This is a specific episode but the site overall detects the blocker.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 151388
 cosmetic: 49162
 scriptlet: 22809
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 2326-6, 2m
 default:
  user-filters: 0-0, never
  easylist: 85899-580, 14m Δ
  easyprivacy: 53143-640, 14m Δ
  plowe-0: 3541-0, now
  ublock-badware: 11639-6, 14m Δ
  ublock-filters: 40404-261, 14m Δ
  ublock-privacy: 1296-22, 14m Δ
  ublock-quick-fixes: 180-0, 14m Δ
  ublock-unbreak: 2479-0, 14m Δ
  urlhaus-1: 24115-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3096 ms (selfie)
 maxAssetCacheWait: 208 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-xhr-if, googlesyndication)
```
</details>

**Comment by gorhill** [comment]
Caused by `||jwpcdn.com/player/*/googima.js` from EasyList.

This seems to work:

    play.nova.bg##+js(prevent-xhr, /googima.js)

**Comment by stephenhawk8054** [comment]
On my machine, the filter works but there's no video playing even when turning off uBO. Maybe it requires an account.

---

@Hriskata17 Can you test the above filter? Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by lordzerg** [comment]
The issue still exists, "adblocker detected" it is from around 01.07.2026(July), in 2024 it was solved, but now Ubo is not working again. It was problematic in 2025 also. They constantly trying to block adblockers. both "nova.bg" and "play.nova.bg" are not watchable now. First is the main site, which has live TV. The second is the same live TV plus archive, it detects ubo on watching live or on watching from archive, for now if I want to watch something, I can only download it with another method.
I wrote this because a user reported it already, but it is closed as a duplicate.

**Comment by gorhill** [comment]
Provide troubleshooting info for the site as if you were creating a new issue: Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here. Also be sure you go through the pre-requisite steps.

**Comment by lordzerg** [comment]
<details><summary>troubleshooting info</summary>

```yaml
uBlock Origin: 1.72.0
Chromium: 150
filterset (summary):
 network: 216135
 cosmetic: 259349
 scriptlet: 75185
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 9m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94933-33658, 9m
  BGR-0: 1156-1, 9m
  adguard-cookies: 39250-96, 9m
  adguard-generic: 98005-7231, never
  adguard-mobile: 12554-169, never
  adguard-mobile-app-banners: 7554-25, 9m
  adguard-other-annoyances: 16186-25, 9m
  adguard-popup-overlays: 31960-178, 9m
  adguard-widgets: 3143-27, 9m
  easylist-annoyances: 5228-407, 9m
  easylist-chat: 276-0, 9m
  [7 lists not shown]: [too many]
 default:
  user-filters: 101-6, never
  easylist: 86024-424, 9m
  easyprivacy: 55942-797, 9m
  plowe-0: 3518-0, 9m
  ublock-badware: 10287-51, 9m
  ublock-filters: 51902-378, 9m
  ublock-privacy: 4074-22, 9m
  ublock-quick-fixes: 468-0, 9m
  ublock-unbreak: 2777-39, 9m
  urlhaus-1: 47895-11, 9m
filterset (user): [array of 102 redacted]
trustedset:
 added: [array of 15 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 38 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 585 ms (selfie)
 maxAssetCacheWait: 210 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  nova.bg: 1
  cdn.bg: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  netinfo.bg: 3
  onesignal.com: 1
  s3.eu-central-1.amazonaws.com: 1
  teads.tv: 2
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
```
</details>

I found out that filters for adguard ads and mobile ads were not enabled and I enabled them and play.nova.bg now works but nova.bg/live is still detecting it. This report troubleshoot is for nova.bg/play
Browser is - Brave,  also I have tried few days ago to add anti-adblock killer filters but they not work anyways.
