### ISSUE TITLE
client.falixnodes.net: detection

### ISSUE THREAD

**Issue by HelloIamarandomperson** [uBlockOrigin/uAssets#25618]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://client.falixnodes.net/server/console
```

### Description

Falixnodes used to have a different method of adblocker which Ublock easily bypassed, to make it harder to deal with it made it so the adblocker doesn't run until you 1. have a account, 2. set a game 3. set up a server, and only when you press the "start" button on the server does it actually block you from using the site. They also block people from using inspect tool on console (But not on other parts of the site) by making it so it continually runs debugger, pausing it instantly forever. 

If all of that is too annoying for you to deal with and you just close this honestly that's fine with me, I spent too long trying to figure it out. The only thing I have to add is that it seems to be primarily using "snigel.web" as the bait (Though I don't see the bait actually doing any adverts if you turn of the filter for it.)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Picture of the anti adblock at work, the "start" button caused it to show up</summary>

![aaaa](https://github.com/user-attachments/assets/94b943d0-e885-4138-8da9-a6a709f7f6ce)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 222043
 cosmetic: 198661
 scriptlet: 48701
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84108-7203, 18m
  adguard-spyware: 70137-20639, 18m
  adguard-cookies: 32106-82, never
  ublock-cookies-adguard: 1808-9, never
  fanboy-cookiemonster: 52270-4038, never
  ublock-cookies-easylist: 1802-1802, never
  adguard-social: 23038-794, never
  fanboy-social: 16675-11, never
  fanboy-thirdparty_social: 68-19, never
 default:
  user-filters: 0-0, never
  ublock-filters: 40408-258, 18m
  ublock-badware: 11627-6, 18m
  ublock-privacy: 1302-22, 18m
  ublock-unbreak: 2480-0, 19m
  ublock-quick-fixes: 180-0, 19m
  easylist: 85870-579, 19m
  easyprivacy: 53143-640, 19m
  urlhaus-1: 25255-0, 19m
  plowe-0: 3541-0, 19m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3343 ms
 maxAssetCacheWait: 131 ms
 cacheBackend: indexedDB
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+falixnodes

---

Continue here: https://github.com/uBlockOrigin/uAssets/issues/18260

**Comment by HelloIamarandomperson** [comment]
Sorry, I thought all of the issues for the site were closed, I swear I checked that previously.

**Comment by stephenhawk8054** [comment]
Just continue commenting previous issues. All volunteers are notified with new comments.
