### ISSUE TITLE
fyers.in: breakage

### ISSUE THREAD

**Issue by audiobybashab** [uBlockOrigin/uAssets#25610]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fyers.in/`

### Category

breakage

### Description

Sign in isn't working. Also, on the right of Sign Up Now, there is a menu button which expands to a list of several other website links. None of them are working as well.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 149750
 cosmetic: 48498
 scriptlet: 22809
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40408-126, now
  ublock-badware: 11643-6, now
  ublock-privacy: 1302-23, now
  ublock-unbreak: 2480-1, now
  ublock-quick-fixes: 180-12, now
  easylist: 85899-580, now
  easyprivacy: 53143-758, now
  urlhaus-1: 24115-0, 1h.49m
  plowe-0: 3541-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 249 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  fyers.in: 1
  d2r1yp2w7bby2u.cloudfront.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 3
```
</details>

**Comment by gorhill** [comment]
Caused by `/analytics/analytics.js` in EasyPrivacy.

This seems to work:

    ||fyers.in/Lib/analytics/analytics.js$1p,script,redirect=noop.js

**Comment by audiobybashab** [comment]
Thanks @gorhill. I gather you have found the solution, can you please guide me as to how to resolve the issue? Thank you again!
