### ISSUE TITLE
uploadmall.com: detection

### ISSUE THREAD

**Issue by dnet890** [uBlockOrigin/uAssets#25615]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://uploadmall.com/rirzr536k5el
```

### Description

the adblock blocker is active

### Other extensions used

I have no other extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="543" alt="image" src="https://github.com/user-attachments/assets/c86385ba-a0af-42fe-81a3-4e6374b051ec">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 149630
 cosmetic: 48541
 scriptlet: 21196
 html: 2028
listset (total-discarded, last-updated):
 default:
  user-filters: 110-49, never
  ublock-filters: 40668-130, 21m Δ
  ublock-badware: 11645-6, 21m Δ
  ublock-privacy: 1289-22, 21m Δ
  ublock-unbreak: 2538-20, 21m Δ
  ublock-quick-fixes: 177-10, 21m Δ
  easylist: 85899-206, 21m Δ
  easyprivacy: 53143-25, 21m Δ
  urlhaus-1: 23990-0, 19h
  plowe-0: 3546-993, 6d.21h.40m
filterset (user): [array of 109 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2173 ms (selfie)
 maxAssetCacheWait: 635 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  aeelookithdifyf.com: 1
  proxycheck.io: 1
  skillsombineukdw.com: 3
  ukankingwithea.com: 2
 extended:
  ##+js(set-constant, navigator.brave, undefined)
  ##+js(no-window-open-if, zigi_tag_id, 10, obj)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by ItsProfessional** [comment]
I can reproduce.
