### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by EntonyHop** [uBlockOrigin/uAssets#25620]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yandex.ru/images/search?from=tabbar&img_url=https%3A%2F%2Fchzs.ru%2Fwp-content%2Fuploads%2F0%2F6%2F5%2F0651f46ed5bc819dd7a9c53afe90826a.jpeg&lr=213&pos=2&rpt=simage&text=%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%20%D0%BF%D1%80%D0%B8%20%D0%B4%D0%BE%D0%B1%D1%80%D0%BE%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%BC%20%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8`

### Category

ads

### Description

ads are not blocked on this site

### Other extensions used

sponsor block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/c23e862d-d4bb-465c-a681-7eb675ebcb28">

</details>

### Configuration

```yaml
version: uBOL 2024.10.6.1334
mode: complete / optimal
rulesets:
 default
 rus-0
 dpollock-0
 adguard-spyware-url
 annoyances-cookies
 annoyances-social
 annoyances-others
 stevenblack-hosts
 annoyances-overlays
 annoyances-widgets
 block-lan
```

**Comment by stephenhawk8054** [comment]
Don't open duplicated issues.
