### ISSUE TITLE
pinterest.com: detection

### ISSUE THREAD

**Issue by afeso** [uBlockOrigin/uAssets#25622]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pinterest.com/`

### Category

detection

### Description

Pinterest detects Ublock and loads up some overlays to asking to disable. 

I've used the element picker to block the overlays but there's an invincible element that stops me from scrolling.

here are the elements i disabled so far:
- ||i.pinimg.com/*/4e/33/34/4e3334c8a6849f5e2f9ee0b09fb9b99a.jpg$image
- www.pinterest.com##.Hsu.iyn.zI7.ujU.fBv.XiG.XbT.QDA
- www.pinterest.com##.Cii.ojN.p6V.QLY.Rym.MIw.JJV
- www.pinterest.com##div.Hsu.iyn.zI7.xuU.XiG > .Hsu.iyn.zI7.fBv.QDA
- www.pinterest.com##.L4E.KS5.QLY.Rym.mQ8._O1.Hsu._he.Fwt

The last element that seems possible to be disabled, causes all pins to disappear.

Site was working fine yesterday. 

### Other extensions used

- duckduckgo privacy essentials
- dark reader
- Internet Download Manager
- Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 149234
 cosmetic: 48486
 scriptlet: 22813
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 84218-475, 1h.26m Δ
  easyprivacy: 53145-640, 1h.26m Δ
  plowe-0: 3541-0, now
  ublock-badware: 11643-6, 1h.26m Δ
  ublock-filters: 40411-363, 1h.26m Δ
  ublock-privacy: 1303-22, 1h.26m Δ
  ublock-quick-fixes: 182-0, 1h.26m Δ
  ublock-unbreak: 2483-0, 1h.26m Δ
  urlhaus-1: 25255-0, never
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 351 ms (selfie)
 maxAssetCacheWait: 92 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  pinterest.com: 8
 extended:
  ##.Hsu.iyn.zI7.ujU.fBv.XiG.XbT.QDA
  ##.Cii.ojN.p6V.QLY.Rym.MIw.JJV
  ##div.Hsu.iyn.zI7.xuU.XiG > .Hsu.iyn.zI7.fBv.QDA
  ##.L4E.KS5.QLY.Rym.mQ8._O1.Hsu._he.Fwt
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

```yml
user-filters: 6-0, never
```

Reset uBO to default settings and test again.

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues/25614#issuecomment-2406406971
