### ISSUE TITLE
lamycosphere.com: breakage

### ISSUE THREAD

**Issue by Mr-Sim** [uBlockOrigin/uAssets#25626]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://lamycosphere.com/collections/ballots-de-culture`

### Category

breakage

### Description

When Ublock is enabled, images of the store are not displayed. 

### Other extensions used

DarkReader, CookieQuickManager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With Ublock :
![image](https://github.com/user-attachments/assets/9b70e851-c515-4ada-a00b-aaf7e8af3c14)

Without Ublock : 
![image](https://github.com/user-attachments/assets/5a584c76-368a-4724-a956-f56b2938d109)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 167596
 cosmetic: 55061
 scriptlet: 21291
 html: 2028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40534-130, 39m Δ
  ublock-badware: 11645-6, 39m Δ
  ublock-privacy: 1290-22, 39m Δ
  ublock-unbreak: 2543-1, 39m Δ
  ublock-quick-fixes: 179-10, 39m Δ
  easylist: 84231-188, 39m Δ
  easyprivacy: 53147-62, 39m Δ
  urlhaus-1: 25390-0, now
  plowe-0: 3548-1000, now
  FRA-0: 25612-493, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 148 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  lamycosphere.com: 10
  shopify.com: 1
  shopifysvc.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`@@||lamycosphere.com/cdn/shop/*/assets/pixel.gif$image,1p`
