### ISSUE TITLE
uBlock detected on vod.tvp.pl 

### ISSUE THREAD

**Issue by pufpuf89** [uBlockOrigin/uAssets#2563]
### URL(s) where the issue occurs

`vod.tvp.pl `

### Describe the issue

uBlock works on every other website from Poland just not on this one. I suspect they prepared themselves for FIFA World Cup.

### Versions

- Browser/version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- uBlock Origin version: v1.16.8

### Settings

Tried everything. Also I always used 'Regions, languages: POL: polskie filtry do Adblocka i uBlocka'

**Comment by mapx-** [comment]
tested this channel 
`https://vod.tvp.pl/video/mistrzostwa-swiata-w-pilce-noznej-rosja-2018,ceremonia-otwarcia,37645075`

using the default setup + the polish list

All fine for me.

**Comment by mapx-** [comment]
However, you should report here the filter issues for polish sites:
https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by krystian3w** [comment]
Fixed in Polish list: https://github.com/MajkiIT/polish-ads-filter/issues/8058

https://github.com/MajkiIT/polish-ads-filter/commit/8fcdc44559e5afa5b5003e9235d615e5130daa12
https://github.com/MajkiIT/polish-ads-filter/commit/3982e2e1d1b2cd3bab996df2e94b818117546d41

**Comment by krystian3w** [comment]
@MajkiIT

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/8fcdc44559e5afa5b5003e9235d615e5130daa12
https://github.com/MajkiIT/polish-ads-filter/commit/3982e2e1d1b2cd3bab996df2e94b818117546d41

**Comment by pufpuf89** [comment]
Thanks guys! Works like a charm 👍

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://vod.tvp.pl/video/na-sygnale,odc-207,39951209`

**Comment by okiehsch** [comment]
Fixed in the regional list.

**Comment by krystian3w** [comment]
https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/

**Comment by okiehsch** [comment]
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku` is enabled by deault for users with a polish browser locale.

**Comment by krystian3w** [comment]
but not in South America (Colombia, Venezuela, Brazil, Argentina, Chile etc.).

**Comment by okiehsch** [comment]
> but not in South America (Colombia, Venezuela, Brazil, Argentina, Chile etc.).

The polish, italian, german, etc. diaspora will have to manually enable their respective regional filter list.

**Comment by krystian3w** [comment]
I was more concerned with forcing more steps beyond the report on the default uBO settings.

 Although not after every list, you can expect fixu in regional filters.

EOT.
