### ISSUE TITLE
plati.market: nuisance

### ISSUE THREAD

**Issue by lucelem** [uBlockOrigin/uAssets#25632]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://plati.market/`

### Category

nuisance

### Description

Cookie notice in the bottom

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[scr](https://imgur.com/9Sck0nb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 118608
 cosmetic: 137930
 scriptlet: 32238
 html: 2324
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 24172-26, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1742-21, now
  curben-phishing: 541-1, now
  fanboy-cookiemonster: 52280-342, now
  ublock-cookies-easylist: 1819-14, now
  ublock-annoyances: 5919-63, now
 default:
  user-filters: 2-0, never
  ublock-filters: 40477-130, now
  ublock-badware: 11655-6, now
  ublock-privacy: 1295-30, now
  ublock-unbreak: 2545-6, now
  ublock-quick-fixes: 157-8, now
  easylist: 83745-202, now
  urlhaus-1: 24965-0, now
  RUS-0: 40877-187, now
filterset (user): [array of 2 redacted]
userSettings:
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 153 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googletagmanager.com: 2
  yandex.ru: 1
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(remove-attr, jsaction, #islsp c-wiz a[href^="http"][data-v…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##+js(remove-attr, data-jsarwt, #rcnt [data-ved] a)
```
</details>

**Comment by mapx-** [comment]
enable `AdGuard/uBO – Cookie Notices`

**Comment by mapx-** [comment]
I said `AdGuard`
