### ISSUE TITLE
mconverter.eu: detection

### ISSUE THREAD

**Issue by wertzuz** [uBlockOrigin/uAssets#25639]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mconverter.eu/`

### Category

detection

### Description

Detects ad-block and limits conversions, when Ad-Block is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/16812559-5e26-4bc5-9df7-c4c89f80a1fa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 151110
 cosmetic: 82600
 scriptlet: 25496
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  DEU-0: 7546-0, 10m
  adguard-cookies: 32111-60, 10m
  curben-phishing: 541-0, 10m
  ublock-cookies-adguard: 1819-9, 10m
 default:
  user-filters: 135-1, never
  easylist: 83818-222, 10m
  easyprivacy: 53149-34, 10m
  ublock-badware: 11653-7, 10m
  ublock-filters: 40223-275, 10m
  ublock-privacy: 1309-22, 10m
  ublock-quick-fixes: 163-0, 10m
  ublock-unbreak: 2487-2, 10m
  urlhaus-1: 24965-0, 10m
filterset (user): [array of 135 redacted]
trustedset:
 added: [array of 27 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3347 ms (selfie)
 maxAssetCacheWait: 615 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  mconverter.eu: 1
  sentry-cdn.com: 1
  setupcmp.com: 2
  stpd.cloud: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##.ad-label
  ##+js(no-setTimeout-if, offsetHeight)
```
</details>

**Comment by D4niloMR** [comment]
Does this works fine?

```adb
mconverter.eu##+js(set, abd, {})
```

---

Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
