### ISSUE TITLE
duden.de: ads: plz remove anoying marque text

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uAssets#25637]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.duden.de/rechtschreibung/diffizil`

### Category

ads

### Description

could you remove this annoying 200x style marque text

### Other extensions used

dark reader

### Screenshot(s)

![Screenshot from 2024-10-12 22-34-45](https://github.com/user-attachments/assets/43c7d05a-4617-4c81-9d5d-d44fd68c273a)

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 128
filterset (summary):
 network: 152226
 cosmetic: 124436
 scriptlet: 26083
 html: 2031
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103108-18209, now
  fanboy-cookiemonster: 52280-52280, now
  fanboy-social: 16676-16676, now
 default:
  user-filters: 14-0, never
  ublock-filters: 40482-149, 1h.36m Δ
  ublock-badware: 11655-6, 1h.36m Δ
  ublock-privacy: 1296-23, 1h.36m Δ
  ublock-unbreak: 2545-5, 1h.36m Δ
  ublock-quick-fixes: 158-8, 1h.36m Δ
  easylist: 83812-212, 1h.36m Δ
  easyprivacy: 53149-196, 1h.36m Δ
  urlhaus-1: 24965-0, now
  plowe-0: 3548-1000, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1985 ms (selfie)
 maxAssetCacheWait: 205 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  duden.de: 8
  adnxs.com: 1
  bing.com: 1
  criteo.net: 1
  doubleclick.net: 2
  google-analytics.com: 3
  googlesyndication.com: 4
  mitself.net: 1
  smaato.net: 1
  taboola.com: 1
  yieldlove.com: 2
 extended:
  ##[id*="billboard"]
  ##.tabloid__side-column
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.back-to-top:not(body):not(html)
  ###taboola-below-article-thumbnails
  ##.ads-box
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(addEventListener-defuser, DOMContentLoaded, isMobile)
```
</details>

**Comment by JobcenterTycoon** [comment]
self advertisment doesn’t getting fixed in uAssets.
