### ISSUE TITLE
saymineapp.com: breakage

### ISSUE THREAD

**Issue by wertzuz** [uBlockOrigin/uAssets#25638]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://saymineapp.com/overview`

### Category

breakage

### Description

After logging in with a google account on top of the site following message occurs in a red banner "Oops! Something went wrong. Please refresh the page."
The site continues to not function probably in general.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 151110
 cosmetic: 82600
 scriptlet: 25496
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  DEU-0: 7546-0, now
  adguard-cookies: 32111-60, now
  curben-phishing: 541-0, now
  ublock-cookies-adguard: 1819-9, now
 default:
  user-filters: 135-1, never
  easylist: 83818-222, now
  easyprivacy: 53149-34, now
  ublock-badware: 11653-7, now
  ublock-filters: 40223-275, now
  ublock-privacy: 1309-22, now
  ublock-quick-fixes: 163-0, now
  ublock-unbreak: 2487-2, now
  urlhaus-1: 24965-0, now
filterset (user): [array of 135 redacted]
trustedset:
 added: [array of 28 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3347 ms (selfie)
 maxAssetCacheWait: 615 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
weird:

![image](https://github.com/user-attachments/assets/6e9a20a4-610d-4ef9-9d5b-630ce8734325)

**Comment by mapx-** [comment]
@wertzuz 

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by wertzuz** [comment]
![image](https://github.com/user-attachments/assets/fedc09fb-0beb-40b0-97e6-8d9dc2ea6011)

**Comment by mapx-** [comment]
add and then test again

`@@||googletagmanager.com/gtm.js$xhr,domain=saymineapp.com`

**Comment by wertzuz** [comment]
seems to work but hard to say cause error is flakey and does not always occur reliably.

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO?

**Comment by mapx-** [comment]
@wertzuz 

> post again the blocked requests

**Comment by wertzuz** [comment]
It works fine with Ublock turned off.
