### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by berogeng** [uBlockOrigin/uAssets#25634]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://electrum.is/
```

### Description

when navigating to the site, it triggers `|||electrum.is^$document,to=~electrum.org`. the site has never been linked or affilated to `electrum.org`.

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 115
filterset (summary):
 network: 147988
 cosmetic: 48476
 scriptlet: 21064
 html: 2030
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40477-130, 1h.31m Δ
  ublock-badware: 11655-6, 1h.31m Δ
  ublock-privacy: 1295-23, 1h.31m Δ
  ublock-unbreak: 2545-1, 1h.31m Δ
  ublock-quick-fixes: 157-8, 1h.31m Δ
  easylist: 83387-579, 1h.31m Δ
  easyprivacy: 53149-43, 1h.31m Δ
  urlhaus-1: 24905-0, 13h.13m
  plowe-0: 3546-620, 11d.2h.25m
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 283 ms (selfie)
 maxAssetCacheWait: 164 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue here: https://github.com/uBlockOrigin/uAssets/issues/25353
