### ISSUE TITLE
denemebonusukullan.com: ads

### ISSUE THREAD

**Issue by twi-cmd** [uBlockOrigin/uAssets#25641]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://denemebonusukullan.com/`

### Category

ads

### Description

this site is ads

### Other extensions used

ı dont know

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150103
 cosmetic: 57099
 scriptlet: 24035
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40223-267, 55m Δ
  ublock-badware: 11653-6, 55m Δ
  ublock-privacy: 1309-22, 55m Δ
  ublock-unbreak: 2487-0, 55m Δ
  ublock-quick-fixes: 164-0, 55m Δ
  easylist: 83786-592, 55m Δ
  easyprivacy: 53150-654, 55m Δ
  urlhaus-1: 25210-0, 55m
  plowe-0: 3548-0, now
  TUR-0: 11411-15, 55m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 190 ms (selfie)
 maxAssetCacheWait: 67 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  cloudflareinsights.com: 1
```
</details>

**Comment by mapx-** [comment]
This page has only a tiktok video.
Did you get it being redirected from some other page ?
