### ISSUE TITLE
louisderrac.com: nuisance

### ISSUE THREAD

**Issue by dreirund** [uBlockOrigin/uAssets#25646]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://louisderrac.com/eloge-du-bug-version-ratp/`

### Category

nuisance

### Description

Shows a banner that advertises to use an ad-blocker.

---

![image](https://github.com/user-attachments/assets/756b595e-ea8a-4581-baf1-cb15668de542)

---

### Other extensions used

* Cookie Dialog Monster
* Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/cfb6038b-0689-4f8a-8eed-118fb42ac001)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 239308
 cosmetic: 167840
 scriptlet: 47477
 html: 2294
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 84145-829, now
  adguard-mobile: 9973-92, now
  adguard-spyware-url: 1739-126, now
  adguard-spyware: 70155-1529, now
  block-lan: 64-0, now
  curben-phishing: 219-0, now
  adguard-social: 23043-1234, now
  adguard-popup-overlays: 27947-967, now
  adguard-mobile-app-banners: 5436-43, now
  adguard-other-annoyances: 14666-471, now
  adguard-widgets: 2698-54, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40494-3809, 3m Δ
  ublock-badware: 11655-131, 3m Δ
  ublock-privacy: 1296-23, 3m Δ
  ublock-unbreak: 2545-78, 3m Δ
  ublock-quick-fixes: 168-17, 3m Δ
  easylist: 83864-16149, 3m Δ
  easyprivacy: 53154-20173, 3m Δ
  urlhaus-1: 25595-0, now
  plowe-0: 3548-1497, now
filterset (user): [empty]
trustedset:
 added: [array of 21 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3098 ms (selfie)
 maxAssetCacheWait: 262 ms
 cacheBackend: indexedDB
 unsuspendAfter: 2741 ms
popupPanel:
 blocked: 2
 network:
  buymeacoffee.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mapx-** [comment]
>  ignoreGenericCosmeticFilters: true

unselect `Ignore generic cosmetic filters`

or add 

`louisderrac.com##.native-ad`
