### ISSUE TITLE
en.numista.com: ads

### ISSUE THREAD

**Issue by FlagLover64** [uBlockOrigin/uAssets#25648]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://en.numista.com/`

### Category

ads

### Description

Ads for website like catawiki still appear by default.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 149065
 cosmetic: 48497
 scriptlet: 21079
 html: 2032
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40494-130, 1m
  ublock-badware: 11655-6, 1m
  ublock-privacy: 1296-22, 1m
  ublock-unbreak: 2545-1, 1m
  ublock-quick-fixes: 179-10, 1m
  easylist: 83786-195, 1m
  easyprivacy: 53149-62, 1m
  urlhaus-1: 25595-0, 1m
  plowe-0: 3548-1000, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2221 ms
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  numista.com: 1
  cloudflareinsights.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
numista.com##.catawiki_list
```

**Comment by mapx-** [comment]
other:
https://en.numista.com/catalogue/index.php?ct=exonumia

```
||numista.com/*/banners/$image
numista.com##.ad_picture
numista.com###rightpub
numista.com###bottompub_container
en.numista.com###fiche_buy_links
```
