### ISSUE TITLE
[nsfw] aussiebum.com: breakage

### ISSUE THREAD

**Issue by natsuj** [uBlockOrigin/uAssets#25654]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.aussiebum.com/mens/underwear`

### Category

breakage

### Description

When click on any product from the domain name or open the product list page(https://www.aussiebum.com/mens/underwear) instead of product page, it shows "about the site text". It display all product normally if uBlockOrigin is disable. 
Only happened to PC version, the android version doesn't have the problem.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 149560
 cosmetic: 48507
 scriptlet: 22735
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 83816-51, now
  easyprivacy: 53158-645, 8m Δ
  plowe-0: 3548-377, now
  ublock-badware: 11654-24, 8m Δ
  ublock-filters: 40260-373, 8m Δ
  ublock-privacy: 1303-26, 8m Δ
  ublock-quick-fixes: 173-0, now
  ublock-unbreak: 2486-32, 8m Δ
  urlhaus-1: 26080-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1015 ms (selfie)
 maxAssetCacheWait: 397 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  cfjump.com: 2
  clarity.ms: 2
  d38xvr37kwwhcm.cloudfront.net: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 1
  redditstatic.com: 1
  trustpilot.com: 6
  typekit.net: 3
  woopra.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||static.ads-twitter.com/uwt.js$script,domain=aussiebum.com`

@ryanbr

**Comment by stephenhawk8054** [comment]
Needs

```adb
@@||googletagmanager.com/gtm.js$script,domain=aussiebum.com
```

on my side too.
