### ISSUE TITLE
latercera.com: nuisance

### ISSUE THREAD

**Issue by Residentcl** [uBlockOrigin/uAssets#25658]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.latercera.com/pulso/noticia/martin-vaca-a-sus-seis-meses-como-ceo-de-wom-hemos-enfrentando-y-superado-momentos-complejos/B7AH6OHGGJGDLFCJL2QQPGZCY4/`

### Category

nuisance

### Description

This page in some notes has this message for payment.

### Other extensions used

EditThisCookie, MyJDownloader Browser Extension, Traductor de Google and Trocker

### Screenshot(s)

![Sin título](https://github.com/user-attachments/assets/85f3fd0d-a975-4138-a561-7f40123fbc5f)

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 151999
 cosmetic: 55393
 scriptlet: 23228
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40231-126, now
  ublock-badware: 11663-6, now
  ublock-privacy: 1309-23, now
  ublock-unbreak: 2487-2, now
  ublock-quick-fixes: 170-14, now
  easylist: 83832-643, now
  easyprivacy: 53158-780, now
  urlhaus-1: 26080-0, now
  plowe-0: 3548-0, now
  spa-0: 4081-6, now
  spa-1: 6022-211, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 261 ms (selfie)
 maxAssetCacheWait: 161 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  152media.info: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  scorecardresearch.com: 1
  typekit.net: 1
 extended:
  ##div[class^="spm |"]
  ##.spm
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).

We don't fix paywalls.

You can use these as your custom filters:

```adb
www.latercera.com##.pw-frontier
www.latercera.com##.container-all:style(position: unset !important;)
```
