### ISSUE TITLE
dump.li: ads

### ISSUE THREAD

**Issue by 055110** [uBlockOrigin/uAssets#25655]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dump.li/`

### Category

ads

### Description

a line of ads for dark market drugs

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 238450
 cosmetic: 227651
 scriptlet: 33121
 html: 2451
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32125-50, now
  ublock-cookies-adguard: 1813-27, now
  adguard-social: 23043-44, now
  ublock-annoyances: 5905-37, 1h.15m Δ
  ALB-0: 309-1, now
  ara-0: 2330-15, now
  BGR-0: 1040-4, now
  CHN-0: 25463-102, now
  CZE-0: 844-12, now
  DEU-0: 7537-39, now
  EST-0: 466-63, now
  FIN-0: 2296-2, now
  [28 lists not shown]: [too many] 
 default:
  user-filters: 0-0, never
  ublock-filters: 40523-130, 1h.15m Δ
  ublock-badware: 11660-6, 1h.15m Δ
  ublock-privacy: 1296-22, 1h.15m Δ
  ublock-unbreak: 2545-1, 1h.15m Δ
  ublock-quick-fixes: 170-12, 1h.15m Δ
  easylist: 83811-197, 1h.15m Δ
  easyprivacy: 53158-64, 1h.15m Δ
  urlhaus-1: 26080-0, now
  plowe-0: 3548-1001, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 17519 ms (selfie)
 maxAssetCacheWait: 5878 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
`dump.li##[class^="banner"]`
