### ISSUE TITLE
karriere.heldele.de: breakage

### ISSUE THREAD

**Issue by hrrd** [uBlockOrigin/uAssets#25656]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://karriere.heldele.de/jobs
```

### Description

Cookie Banner is blocked. This leads to the point where you can't select any filter option and select it. 

### Other extensions used

canvasblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 219056
 cosmetic: 96911
 scriptlet: 43508
 html: 2294
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84108-4209, 3d.20h.10m
  adguard-spyware-url: 1734-126, 3d.20h.10m
  adguard-spyware: 70137-1498, 3d.20h.10m
  curben-phishing: 219-0, 21h.54m
  ublock-annoyances: 5905-75, 2h.14m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 40527-142, 2h.14m Δ
  ublock-badware: 11660-6, 2h.14m Δ
  ublock-privacy: 1296-22, 2h.14m Δ
  ublock-unbreak: 2545-1, 2h.14m Δ
  ublock-quick-fixes: 170-0, 2h.14m Δ
  easylist: 83790-2136, 2h.14m Δ
  easyprivacy: 53158-20161, 2h.14m Δ
  urlhaus-1: 25255-0, 21h.54m
  plowe-0: 3548-1096, 2d.8h.14m
  DEU-0: 7546-43, 21h.54m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1330 ms
 maxAssetCacheWait: 447 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
No issue in chrome.
Firefox: It seems to be broken even disabling uBO

**Comment by stephenhawk8054** [comment]
Test

```adb
@@||googletagmanager.com/gtm.js$script,domain=karriere.heldele.de
```

Also turn off Firefox' Enhanced Tracking Protection.

**Comment by mapx-** [comment]
@stephenhawk8054 

using chrome, I get no cookie notice **but** the filtering is ok.
in FF the filtering does not work even disabling uBO

**Comment by stephenhawk8054** [comment]
@mapx- Hmm... I can see the cookie banner after adding the filter

![image](https://github.com/user-attachments/assets/384cacbe-b5cb-4e44-a3e2-075423f0d8a3)
