### ISSUE TITLE
interiordecoratingcolors.com: ads

### ISSUE THREAD

**Issue by GhinNanamin** [uBlockOrigin/uAssets#25657]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://interiordecoratingcolors.com/`

### Category

ads

### Description

too much ads that appear on/in those site

### Other extensions used

please update twice a month

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Opera Snapshot_2024-10-15_035300_interiordecoratingcolors com](https://github.com/user-attachments/assets/b94135c1-c17c-40e3-a885-443c2d4df6eb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 149573
 cosmetic: 48500
 scriptlet: 22703
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40222-126, now
  ublock-badware: 11659-6, now
  ublock-privacy: 1303-23, now
  ublock-unbreak: 2486-1, now
  ublock-quick-fixes: 170-14, now
  easylist: 83826-591, now
  easyprivacy: 53158-767, now
  urlhaus-1: 26080-0, now
  plowe-0: 3548-0, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 105 ms (selfie)
 maxAssetCacheWait: 35 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `ABPindo` list and test again.
