### ISSUE TITLE
amazon.com: breakage

### ISSUE THREAD

**Issue by ickybus** [uBlockOrigin/uAssets#25667]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.amazon.com/gp/product/handle-buy-box-bbf_1_glance`

### Category

breakage

### Description

Adding any amazon product to cart redirects to 404 page

### Other extensions used

Bitwarden, Auto Refresh Plus, Ghostery (disabled), Fakespot, Keepa, RES, Web Scrobbler

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 155762
 cosmetic: 104437
 scriptlet: 30603
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-mobile-app-banners: 5437-1125, now
  adguard-other-annoyances: 14674-318, now
  adguard-popup-overlays: 28024-964, now
  adguard-widgets: 2704-18, now
  easylist-annoyances: 4813-130, now
  easylist-chat: 216-0, now
  easylist-newsletters: 7974-28, now
  easylist-notifications: 3453-3, now
  ublock-annoyances: 5965-90, 1h.2m Δ
 default:
  user-filters: 31-1, never
  easylist: 83967-550, 1h.2m Δ
  easyprivacy: 53160-755, 1h.2m Δ
  plowe-0: 3548-0, now
  ublock-badware: 11770-6, 1h.2m Δ
  ublock-filters: 40211-702, 1h.2m Δ
  ublock-privacy: 1311-22, 1h.2m Δ
  ublock-quick-fixes: 171-0, 1h.2m Δ
  ublock-unbreak: 2488-3, 1h.2m Δ
  urlhaus-1: 25750-0, now
filterset (user): [array of 31 redacted]
trustedset:
 added: [array of 20 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 453 ms (selfie)
 maxAssetCacheWait: 109 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  scriptcdn.net: 1
 extended:
  ##+js(json-prune, cuepointPlaylist)
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] |…
```
</details>

**Comment by ickybus** [comment]
video of the issue:  https://youtu.be/23Ihdq76pwU

**Comment by mapx-** [comment]
@stephenhawk8054
