### ISSUE TITLE
hsbc.com: nuisance

### ISSUE THREAD

**Issue by Den0702** [uBlockOrigin/uAssets#25666]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hsbc.com/`

### Category

breakage

### Description

When using the _element zapper_ mode after selecting the "welcome" popup the interaction with the page is narrowed to scrolling. Buttons do not work. 

When using the _element picker_ mode both buttons and scrolling do not work.

### Other extensions used

no any  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 117
filterset (summary):
 network: 152320
 cosmetic: 65607
 scriptlet: 21358
 html: 2043
listset (total-discarded, last-updated):
 default:
  user-filters: 56-1, never
  ublock-filters: 40970-131, 1m
  ublock-badware: 11766-6, 1m
  ublock-privacy: 1299-22, 1m
  ublock-unbreak: 2548-1, 1m
  ublock-quick-fixes: 168-12, 1m
  adguard-mobile: 9978-97, 1m
  easylist: 83967-267, 1m
  easyprivacy: 53160-73, 1m
  urlhaus-1: 25750-0, 1m
  plowe-0: 3548-1075, 1m
  POL-0: 8765-45, 1m
  POL-2: 1283-48, 1m
filterset (user): [array of 56 redacted]
trustedset:
 added: [array of 29 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4812 ms (selfie)
 maxAssetCacheWait: 277 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  tiqcdn.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how the "welcome" banner looks like?
