### ISSUE TITLE
pixlr.com: nuisance

### ISSUE THREAD

**Issue by xqtp** [uBlockOrigin/uAssets#25669]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pixlr.com/tr/express/?tool=remove-object`

### Category

nuisance

### Description

They show this popup every time when you visit the site

This rule fixes the problem
`||pixlr.com/api/news/poll/`

### Other extensions used

Bitwarden
Simple Translate
Search by Image
Video Control for Instagram

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![p1](https://github.com/user-attachments/assets/5a6ce6b8-5ada-4c5b-b11f-a694b8c7c9db)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 127355
 cosmetic: 127431
 scriptlet: 33127
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
  TUR-0: null
 added:
  https://raw.githubusercontent.com/xqtp/List-TR/master/List-TR.txt: 1082-0, 11m
  adguard-spyware-url: 1739-7, 11m
  fanboy-cookiemonster: 52301-225, 20m
  ublock-cookies-easylist: 1813-9, 20m
  fanboy-social: 16706-10, 20m
  easylist-annoyances: 4813-52, 20m
  easylist-chat: 216-0, 11m
  easylist-newsletters: 7974-48, 20m
  easylist-notifications: 3453-165, 20m
  ublock-annoyances: 5965-12, 11m
 default:
  user-filters: 52-0, never
  ublock-filters: 40212-131, 11m
  ublock-badware: 11770-6, 11m
  ublock-privacy: 1311-141, 20m Δ
  ublock-unbreak: 2488-3, 20m Δ
  ublock-quick-fixes: 171-14, 20m Δ
  easylist: 83967-222, 11m
  easyprivacy: 53160-160, 20m Δ
filterset (user): [array of 54 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 753 ms (selfie)
 maxAssetCacheWait: 534 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable [AdGuard – Popup Overlays](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-popup-overlays)
