### ISSUE TITLE
ignitetv.rogers.com: breakage

### ISSUE THREAD

**Issue by jay21317** [uBlockOrigin/uAssets#25668]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ignitetv.rogers.com/`

### Category

breakage

### Description

disabling ublock lets the site load

### Other extensions used

malwarebytes browser guard, no script, and facebook container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 149410
 cosmetic: 48572
 scriptlet: 21079
 html: 2032
listset (total-discarded, last-updated):
 default:
  user-filters: 9-0, never
  ublock-filters: 40470-130, 2m
  ublock-badware: 11757-6, 2m
  ublock-privacy: 1296-22, 2m
  ublock-unbreak: 2547-1, 2m
  ublock-quick-fixes: 168-12, 2m
  easylist: 83967-194, 2m
  easyprivacy: 53158-64, 2m
  urlhaus-1: 25750-0, 2m
  plowe-0: 3548-1000, 2m
filterset (user): [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1173 ms
 maxAssetCacheWait: 19 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  rogers.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||ignitetv.rogers.com/js/api/fingerprint.js$script,1p`

@ryanbr

**Comment by jay21317** [comment]
that did it thank you so much.
