### ISSUE TITLE
[nsfw] adictox.com: popups

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#25665]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://adictox.com/2024/05/04/brenda-trindade-fucking-outdoors/`

### Category

popups

### Description

Popup opens when clicked.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150840
 cosmetic: 56676
 scriptlet: 23864
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 10726-10, now
  easylist: 83967-470, now
  easyprivacy: 53160-633, now
  plowe-0: 3548-1, now
  ublock-badware: 11755-6, 2m Δ
  ublock-filters: 40211-365, now
  ublock-privacy: 1309-23, 2m Δ
  ublock-quick-fixes: 171-15, 2m Δ
  ublock-unbreak: 2489-35, 2m Δ
  urlhaus-1: 25750-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 491 ms
 maxAssetCacheWait: 228 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cleantalk.org: 2
  googletagmanager.com: 2
  wobbly-birth.com: 1
 extended:
  ##.bannerADS
  ##.ads-footer
```
</details>

**Comment by Yuki2718** [comment]
Fixed, update filters in about 6 hours.
