### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by Troyfmh** [uBlockOrigin/uAssets#25664]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/track/1SU92PvmDTowaZGmo5oI82`

### Category

ads

### Description

Spotify is still playing adverts very occassionally, I got none for around 2 hours and then 2 ads played. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.10.14.189
mode: complete / basic
rulesets:
 default
```

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/22198

**Comment by gorhill** [comment]
> `mode: complete / basic`

You likely need to raise the default blocking mode to _Optimal_ or _Complete_, some important filters cannot be enforced when using _Basic_ as default mode.

**Comment by Troyfmh** [comment]
> > `mode: complete / basic`
> 
> You likely need to raise the default blocking mode to _Optimal_ or _Complete_, some important filters cannot be enforced when using _Basic_ as default mode.

Here is a picture I have tried to attach. I am using the complete version of uBlock 

![image](https://github.com/user-attachments/assets/852d2429-6fd4-4754-ad55-7390004fa4e9)
![Spotify ads](https://github.com/user-attachments/assets/e2987ed2-bdd8-4268-afc1-fb3889d81b36)

**Comment by Troyfmh** [comment]
![image](https://github.com/user-attachments/assets/175eceb6-af52-4b2e-a1af-11f37071ce76)

![image](https://github.com/user-attachments/assets/1cb7edda-72a4-4aa7-bb5e-57f07352cf6b)

The issue still seems to persist, after changing this setting, however the ad didn't play it just stayed unpaused but without progressing so the music just stopped and nothing would happen until i refreshed page.

**Comment by gorhill** [comment]
Be sure you open the page in a new tab after you make changes to filter lists or filtering mode.

**Comment by Troyfmh** [comment]
> Be sure you open the page in a new tab after you make changes to filter lists or filtering mode.

Thanks yeah this happened after making the change and then completely shutting down and restarting my computer

**Comment by stephenhawk8054** [comment]
> 2 ads played.

> The issue still seems to persist, after changing this setting, however the ad didn't play it just stayed unpaused but without progressing

So, what is your issue now? Are the ads played or paused?

**Comment by Troyfmh** [comment]
> > 2 ads played.
> 
> > The issue still seems to persist, after changing this setting, however the ad didn't play it just stayed unpaused but without progressing
> 
> So, what is your issue now? Are the ads played or paused?

Like spotify is playing music, then the music will stop and an ad will "play" (as in, the next song is an ad as you can see in the screenshot) but it didn't automatically start playing the ad, it looks unpaused on inspection but the ad is not progressing in time, and no audio is heard from the ad, because no audio is heard at all. It just froze. The only way to fix and resume music playing is to refresh the site. The ad is played, and looks unpaused, but you don't hear it, and it doesn't progress, it's as if the website just crashes.

**Comment by stephenhawk8054** [comment]
Can you open browser devtools -> Network tab -> Reproduce the issue and check which domains are blocked?
