### ISSUE TITLE
cssbattle.dev: ads

### ISSUE THREAD

**Issue by yklitnick** [uBlockOrigin/uAssets#25675]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cssbattle.dev/`

### Category

ads

### Description

under the daily targets it displays an ad

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-10-16 002540](https://github.com/user-attachments/assets/074a05c0-a2ed-4e6c-bef8-6eabdde2c524)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150231
 cosmetic: 48567
 scriptlet: 22709
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40216-142, now
  ublock-badware: 11770-6, now
  ublock-privacy: 1309-22, now
  ublock-unbreak: 2488-0, now
  ublock-quick-fixes: 170-0, now
  easylist: 83967-587, 1m
  easyprivacy: 53160-766, 1m
  urlhaus-1: 26550-0, 1m
  plowe-0: 3548-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2004 ms
 maxAssetCacheWait: 25 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googletagmanager.com: 1
  sentry.io: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
cssbattle.dev###sponsor
```

**Comment by yklitnick** [comment]
Yes, that did it!
