### ISSUE TITLE
False positive on Github

### ISSUE THREAD

**Issue by Verity-Freedom** [uBlockOrigin/uAssets#25676]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://github.com/matinrco/tor/releases/download/v0.4.5.10/tor-expert-bundle-v0.4.5.10.zip
```

### Description

That's just a very old Tor Expert Bundle from Github. I know this because I have my own custom Tor Expert Bundle on Github that is much newer and that is used by many people, mostly Russians, and one guy showed me this one, asked if they are similar. I checked every file on Virustotal and it didn't find any virus here.

### Other extensions used

Well I use some extensions but they are not adblock related, like, OmegaZero proxy extension for my own configured Tor Expert which I mentioned, or AHA music search. They are completely not related.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/382ef059-c63b-48b7-93d2-6a3d946391e4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Please report to https://gitlab.com/malware-filter/urlhaus-filter

**Comment by Verity-Freedom** [comment]
@stephenhawk8054 
![image](https://github.com/user-attachments/assets/35a810c2-19ba-4644-9d2f-1f9873ff1367)

They will not even let me to verify here. They are not verifying Russian phone numbers. I need to buy a virtual number just to verify here. How am I supposed to report...
![image](https://github.com/user-attachments/assets/4c249e8c-ca10-45eb-ba96-73a155f3abc6)

**Comment by stephenhawk8054** [comment]
You can also go to https://urlhaus.abuse.ch/url/3213897/ -> Actions dropdown -> `Report a false positive`

cc @curbengh

**Comment by Verity-Freedom** [comment]
> You can also go to https://urlhaus.abuse.ch/url/3213897/ -> Actions dropdown -> `Report a false positive`
> 
> cc @curbengh

I bought a virtual number already but thanks, I am trying, I hope everyone can see the problem here.

**Comment by Verity-Freedom** [comment]
@stephenhawk8054 https://gitlab.com/malware-filter/urlhaus-filter/-/issues/100
