### ISSUE TITLE
francetvinfo.fr: breakage

### ISSUE THREAD

**Issue by tintou** [uBlockOrigin/uAssets#25670]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.francetvinfo.fr/`

### Category

breakage

### Description

The short videos under the "A regarder" section do not launch on click

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 168966
 cosmetic: 63923
 scriptlet: 21343
 html: 2033
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40977-131, now
  ublock-badware: 11766-6, now
  ublock-privacy: 1299-22, now
  ublock-unbreak: 2548-1, 9m Δ
  ublock-quick-fixes: 168-12, now
  adguard-mobile: 9979-97, now
  easylist: 83971-267, now
  easyprivacy: 53159-73, 9m Δ
  urlhaus-1: 25750-0, now
  plowe-0: 3548-1075, now
  FRA-0: 25614-599, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3077 ms
 maxAssetCacheWait: 1323 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  francetvinfo.fr: 1
  aswpsdkeu.com: 2
  aticdn.net: 1
  estat.com: 2
  fwmrm.net: 2
  youborafds01.com: 2
 extended:
  ##.ad-layer
```
</details>

**Comment by stephenhawk8054** [comment]
Can you turn off Firefox' Enhanced Tracking Protection and test again?

**Comment by tintou** [comment]
Oh yes that was this, sorry for the noise
