### ISSUE TITLE
skillheadlines.in: detection

### ISSUE THREAD

**Issue by symentium** [uBlockOrigin/uAssets#25673]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://skillheadlines.in/`

### Category

detection

### Description

Adblock detection in the specified URL. Other filters and userscripts have been disabled.
![Screenshot 2024-10-16 090119](https://github.com/user-attachments/assets/734bdd6d-a97d-43f2-a290-27ef607ba4b3)

### Other extensions used

Undo Close Tab
dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 262363
 cosmetic: 261975
 scriptlet: 54720
 html: 2294
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84557-4225, 13m
  adguard-mobile: 9979-60, 13m
  adguard-spyware-url: 1739-126, 13m
  adguard-spyware: 93721-1544, 13m
  curben-phishing: 560-8, 13m
  adguard-cookies: 32146-62, 13m
  ublock-cookies-adguard: 1815-27, 13m
  fanboy-cookiemonster: 52307-4044, 13m
  ublock-cookies-easylist: 1815-1815, 13m
  adguard-social: 23050-51, 13m
  fanboy-social: 16706-762, 13m
  fanboy-thirdparty_social: 68-19, 13m
  [10 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 40475-130, 13m
  ublock-badware: 11772-6, 13m
  ublock-privacy: 1298-22, 13m
  ublock-unbreak: 2546-1, 13m
  ublock-quick-fixes: 168-12, 10m Δ
  easylist: 83974-2216, 13m
  easyprivacy: 53161-23794, 13m
  urlhaus-1: 26550-0, 13m
  plowe-0: 3548-1499, 13m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 11 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4812 ms (selfie)
 maxAssetCacheWait: 3920 ms
 cacheBackend: indexedDB
 unsuspendAfter: 554 ms
popupPanel:
 blocked: 11
 network:
  doubleclick.net: 5
  googlesyndication.com: 4
  wp.com: 2
 extended:
  ###ast-scroll-top
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Is it from a shortener link? If yes, can you give original URL?

**Comment by symentium** [comment]
https://f.technicalatg.in/6iTpuM1

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

Comment in that thread.
