### ISSUE TITLE
stream4free.tv: detection

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#25679]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.stream4free.tv/`

### Category

detection

### Description

Overlayer appears saying that we have an adblocker. Tried a few scripts to remove but i think it's cosmetic related.

If we remove any bit of Javascript, it seems to detect it and ask the user to enable Javascript, even though only a fraction as removed

### Other extensions used

TWP translate pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 150614
 cosmetic: 50173
 scriptlet: 24869
 html: 2319
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5908-35, now
 default:
  user-filters: 144-0, never
  ublock-filters: 40492-131, now
  ublock-badware: 11781-6, now
  ublock-privacy: 1303-22, now
  ublock-unbreak: 2546-1, now
  easylist: 83985-194, now
  easyprivacy: 53161-63, now
  urlhaus-1: 26550-0, now
  plowe-0: 3548-1000, now
  ublock-quick-fixes: 171-13, now
filterset (user): [array of 93 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 134 redacted]
hostRuleset:
 added: [array of 486 redacted]
urlRuleset:
 added: [array of 104 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 434 ms (selfie)
 maxAssetCacheWait: 126 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  audiencegarret.com: 1
  google-analytics.com: 3
  outheelrelict.com: 2
  shebudriftaiter.net: 1
 extended:
  ###ad_728x90
  ###head_ads
  ###page-ad-top
  ###popupadunit
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054 i see older filter with the domain `stream4free.live` but the site only redirect to `stream4free.tv`.

Also i see ads when i open a stream. It can be fixed with

```
||stream4free.tv/*.php$frame,1p
stream4free.tv###promo
```

**Comment by x-R0b0T-x** [comment]
https://github.com/user-attachments/assets/9e0a7e9b-c796-47ec-862b-22857ad6764f

**Comment by stephenhawk8054** [comment]
Please give exact link where you see the issue.

**Comment by x-R0b0T-x** [comment]
`https://www.stream4free.tv/kaamelott-hd`

**Comment by stephenhawk8054** [comment]
Can you copy your troubleshooting information to here?

**Comment by x-R0b0T-x** [comment]
https://github.com/user-attachments/assets/4682463d-513c-4f6f-af8f-5a7b94b8510b

https://github.com/user-attachments/assets/ef67443d-59a1-4a81-aa4c-4d0579c1562c

I actually think there must be a bad setting in my "uBlock Origin Lite". Where are the aesthetic filtering settings?

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings + `Adguard French` list + use `Complete` mode.

**Comment by x-R0b0T-x** [comment]
The same with Floorp

**Comment by stephenhawk8054** [comment]
I can't reproduce:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/791657d9-6455-4364-a80e-6a1697ef4103" />

</details>
