### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by 88Heker88** [uBlockOrigin/uAssets#25684]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=WvKGc3kqrLw`

### Category

ads

### Description

ssgdfgd

### Other extensions used

gdfgdg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.10.14.189
mode: complete / complete
rulesets:
 default
 alb-0
 bgr-0
 chn-0
 cze-0
 deu-0
 fin-0
 fra-0
 grc-0
 hrv-0
 hun-0
 idn-0
 ind-0
 irn-0
 isl-0
 isr-0
 ita-0
 jpn-1
 kor-1
 ltu-0
 lva-0
 mkd-0
 nld-0
 nor-0
 pol-0
 rou-1
 rus-0
 spa-0
 spa-1
 svn-0
 swe-1
 tha-0
 tur-0
 vie-1
 block-lan
 dpollock-0
 adguard-spyware-url
 annoyances-cookies
 annoyances-overlays
 annoyances-social
 annoyances-widgets
 annoyances-others
 stevenblack-hosts
```

**Comment by zephiii** [comment]
> - [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
> 
> - [x] I did not answer truthfully to **ALL** the above checkboxes.
