### ISSUE TITLE
katmoviehd.fi: [unknown]

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25685]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://katmoviehd.fi/?cc91539a13=RXpUUHR2Uy9HTkNjTHFCaHNBS01pTERCV2ptdkJGN0FES25wK0FBaVlLcXdvUzJYK0hVWlpVekYrMTR4Z2VkQmJ5ZTc5enVrTU5OVG11VmNhYjVyVkljNVAzWWY4WHE2UDRYZ0w4M3phSTQ9`

### Category

[unknown]

### Description

Can the time of ads shortner be bypassed?

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1000108978](https://github.com/user-attachments/assets/ccff4000-3640-4c9f-af01-51037d53d4a9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 1130870
 cosmetic: 218372
 scriptlet: 37449
 html: 2315
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 137007-611, now
  https://hosts.ubuntu101.co.za/domains.list: 539820-24137, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 107117-265, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2683-2, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 452-36, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 86659-48776, now
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/refs/heads/main/antitypo.txt: 2076-32, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4109-36, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  https://urlhaus.abuse.ch/downloads/text/: 185341-0, now
  curben-phishing: 568-16, now
  [14 lists not shown]: [too many]
 default:
  ublock-filters: 41004-408, 2m Δ
  ublock-badware: 11775-1516, 2m Δ
  ublock-privacy: 1313-102, 2m Δ
  ublock-unbreak: 2548-5, 2m Δ
  ublock-quick-fixes: 177-13, 2m Δ
  adguard-mobile: 9979-12, now
  easylist: 84011-29673, 2m Δ
  easyprivacy: 53164-10261, 2m Δ
  urlhaus-1: 26185-289, now
  plowe-0: 3548-3534, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1002 ms (selfie)
 maxAssetCacheWait: 612 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  ads2550.bid: 2
  googletagmanager.com: 1
  puyyrala.xyz: 1
 extended:
  ##+js(abort-current-script, Math.imul)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
