### ISSUE TITLE
ddwloclawek.pl: detection

### ISSUE THREAD

**Issue by jakubstaszak-com** [uBlockOrigin/uAssets#25686]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://ddwloclawek.pl/
```

### Description

Ublock is still being detected. For a few years now despite 2 solved issues 🤷🏿

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241016-214035](https://github.com/user-attachments/assets/c194059e-2408-4d05-a794-f517901f250a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 152835
 cosmetic: 65566
 scriptlet: 21371
 html: 2048
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 41004-131, 1h.23m Δ
  ublock-badware: 11775-6, 1h.23m Δ
  ublock-privacy: 1313-25, 1h.23m Δ
  ublock-unbreak: 2548-32, 1h.23m Δ
  ublock-quick-fixes: 177-13, 1h.23m Δ
  adguard-mobile: 9973-178, 2d.2h.25m
  easylist: 84011-181, 1h.23m Δ
  easyprivacy: 53164-43, 1h.23m Δ
  urlhaus-1: 26185-0, 3h.47m
  plowe-0: 3548-1075, 3d.31m
  POL-0: 8765-45, 23h.35m
  POL-2: 1283-48, 1d.4m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 624 ms (selfie)
 maxAssetCacheWait: 71 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 25
 network:
  ddwloclawek.pl: 4
  clarity.ms: 1
  doubleclick.net: 1
  facebook.com: 4
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  mgid.com: 2
  onnetwork.tv: 4
  optad360.io: 2
  reonews.pl: 4
 extended:
  ##.ablck-overlay
  ##+js(set-constant, questpassGuard, noopFunc)
  ##+js(set-constant, isAdBlockerEnabled, false)

```
</details>

**Comment by stephenhawk8054** [comment]
Just comment in the old thread. All volunteers are notified with new comments. No need to open duplicated issues.
