### ISSUE TITLE
wayfair.com: breakage

### ISSUE THREAD

**Issue by anzenketh** [uBlockOrigin/uAssets#25690]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wayfair.com/furniture/pdp/latitude-run-llanas-1158-wide-leather-match-cushion-back-manual-reclining-long-sofa-with-glider-fdxy3317.html?piid=101007500`

### Category

breakage

### Description

Show more or show less information does not expand and show data. 

### Other extensions used

I turned off the block and it worked. So none relevant. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150711
 cosmetic: 48582
 scriptlet: 22727
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40239-369, 31m Δ
  ublock-badware: 11779-6, 31m Δ
  ublock-privacy: 1327-22, 31m Δ
  ublock-unbreak: 2489-0, 31m Δ
  ublock-quick-fixes: 181-0, 31m Δ
  easylist: 84023-476, 31m Δ
  easyprivacy: 53169-649, 31m Δ
  urlhaus-1: 26935-0, now
  plowe-0: 3548-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 581 ms
 maxAssetCacheWait: 126 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2172
 network:
  wayfair.com: 5
  adgrx.com: 1
  adnxs.com: 4
  adsrvr.org: 4
  adswizz.com: 2
  attn.tv: 1
  audiohook.com: 2
  bing.com: 1
  cnnx.link: 1
  d2lxqodqbpy7c2.cloudfront.net: 1
  d34r8q7sht0t9k.cloudfront.net: 1
  datasteam.io: 1
  doubleclick.net: 1
  facebook.com: 3
  facebook.net: 1
  forter.com: 1
  googleadservices.com: 1
  googletagmanager.com: 1
  impactradius-event.com: 1
  ispot.tv: 1
  liadm.com: 2
  linkedin.com: 2
  mczbf.com: 1
  nanigans.com: 1
  narrativ.com: 1
  pinterest.com: 4
  redditstatic.com: 1
  riskified.com: 1
  salsify-ecdn.com: 2113
  siftscience.com: 1
  signifyd.com: 1
  snapchat.com: 2
  taboola.com: 2
  tiktok.com: 1
  trkn.us: 2
  tvpixel.com: 1
  yahoo.com: 2
 extended:
  ##div[data-node-id^="SponsoredListingCollectionItem"]
  ##+js(no-xhr-if, t.wayfair.com/b.php?)
  ##+js(set-constant, navigator.sendBeacon, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
add

`||salsify-ecdn.com/sdk/$badfilter`

@ryanbr EP issue
