### ISSUE TITLE
hellorayo.co.uk: breakage

### ISSUE THREAD

**Issue by Cinbor** [uBlockOrigin/uAssets#25693]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hellorayo.co.uk/absolute-radio/play/`

### Category

breakage

### Description

Won't play with Ublock origin on

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150665
 cosmetic: 48563
 scriptlet: 22626
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84023-476, 3m Δ
  easyprivacy: 53169-648, 3m Δ
  plowe-0: 3548-0, now
  ublock-badware: 11779-6, 3m Δ
  ublock-filters: 40239-355, 3m Δ
  ublock-privacy: 1327-22, 3m Δ
  ublock-unbreak: 2489-0, 3m Δ
  urlhaus-1: 26935-0, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 540 ms (selfie)
 maxAssetCacheWait: 182 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  adswizz.com: 2
  amazon-adsystem.com: 1
  covatic.io: 1
  google-analytics.com: 1
  googleoptimize.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  insurads.com: 1
  the-ozone-project.com: 1
```
</details>

**Comment by Cinbor** [comment]
Hi, I had already tried adding the web address, I tried your string - _||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=hellorayo.co.uk,redirect=google-ima.js_
That completely broke the site I couldn't even sign in!
I've just right clicked and turned it off too busy and only want to listen to the radio whilst working 😬
Thanks

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
@@||browser.covatic.io/sdk/v1/bauer.js$script,domain=hellorayo.co.uk
```

**Comment by Cinbor** [comment]
That's it buddy 🏋🏻 thanks for your help.
