### ISSUE TITLE
perplexity.ai: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25695]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.perplexity.ai/`

### Category

nuisance

### Description

When you ask a question for the second time, small pop-up in the corner is shown asking you to sign in. 
Then, if you ask it again (third time), entire screen is covered with a pop-up asking you to sign in.

And while you can close them, it's annoying because even after you close them, they'll appear again if you continue asking questions.

I tried to block it with element picker, but didn't succeed.

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

After second query:
![Screenshot_2](https://github.com/user-attachments/assets/25dd9b4d-9925-44e0-be92-c43bef962236)

After third query:
![Screenshot_1](https://github.com/user-attachments/assets/f6069c82-ffb1-4b11-8bd4-d784cf675d8b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 279237
 cosmetic: 254172
 scriptlet: 54769
 html: 2299
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-4054, now
  adguard-generic: 84775-526, now
  adguard-spyware-url: 1748-127, now
  adguard-spyware: 93733-19834, now
  curben-phishing: 573-0, now
  adguard-cookies: 32186-95, now
  ublock-cookies-adguard: 1831-27, now
  fanboy-cookiemonster: 52318-4108, now
  ublock-cookies-easylist: 1831-1831, now
  adguard-social: 23056-51, now
  fanboy-social: 16715-762, now
  adguard-popup-overlays: 28032-1035, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  ublock-filters: 40498-3697, 1h.11m Δ
  ublock-badware: 11781-186, 1h.11m Δ
  ublock-privacy: 1313-35, 1h.11m Δ
  ublock-unbreak: 2547-79, 1h.11m Δ
  ublock-quick-fixes: 178-17, 1h.11m Δ
  easylist: 84023-21854, 1h.11m Δ
  easyprivacy: 53169-40194, 1h.11m Δ
  urlhaus-1: 26935-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 178 ms (selfie)
 maxAssetCacheWait: 119 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  perplexity.ai: 1
  cloudflareinsights.com: 2
  google.com: 1
  sentry.io: 1
  singular.net: 1
 extended:
  ###cookie-consent
  ##+js(abort-on-stack-trace, window.screen.height, setTimeout)
  ##+js(set-cookie, trackingAllowed, false)
  ##+js(set-session-storage-item, signUpBannerDismissed, false)
  ##+js(set-session-storage-item, shouldShowAuthBannerAfterQuery, …
  ##+js(set-local-storage-item, appDownloadBannerDismissed, true)
  ##+js(set-session-storage-item, signUpBannerDismissed, true)
  ##+js(set-session-storage-item, appDownloadBannerDismissed, true…
```
</details>

**Comment by gorhill** [comment]
The cookie `pplx.metadata` contains the question count.

**Comment by gorhill** [comment]
This works for me:

    perplexity.ai##body > div:has([class*="bg-backdrop"])

But then the cookie `pplx.metadata` contains the question count, so it should probably be removed.

**Comment by mapx-** [comment]
@Marko-98 

use

```
perplexity.ai##+js(cookie-remover, pplx.metadata)
perplexity.ai##.hidden.right-md.bottom-md.fixed
perplexity.ai##body > div:has([class*="bg-backdrop"])
```

**Comment by stephenhawk8054** [comment]
Test

```adb
perplexity.ai##+js(trusted-replace-argument, Array.prototype.includes, 0, undefined, condition, visitor-gate)
perplexity.ai##.hidden.right-md.bottom-md.fixed
```

**Remember to turn on `Allow custom filters requiring trust` in "My filters" pane.**
