### ISSUE TITLE
peing.net: nuisance

### ISSUE THREAD

**Issue by DaisukeDaisuke** [uBlockOrigin/uAssets#25707]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://peing.net/ja/q/26fa5151-f4f0-4926-8607-9dd08d6c3f8b
```

### Description

It blocks ads successfully, but when I open a page I see a huge ad remnant
I could delete it with the x mark, but this is annoying

Here is the filter I propose:

```
peing.net##div[id^="ad-instream-container"]
peing.net##.ad-interstitial-container > .close-interstitial-button
```

I don't know anything about the performance of the filter syntax, so I hope volunteers can create better filters
```
! This targets id="ad-instream-container-2cb4bc01-5a2a-430a-9a3e-14b1e0de59b0"
peing.net##div[id^="ad-instream-container"]
```

<details>

<summary>ad-instream-container</summary>
  
![Desktop Screenshot 2024 10 18 - 16 22 08 45](https://github.com/user-attachments/assets/0b2496da-4b05-4f20-834e-96ca5fbc5814)

</details>

```
peing.net##.ad-interstitial-container > .close-interstitial-button
```
<details>

<summary>close-interstitial-button</summary>
  
![Desktop Screenshot 2024 10 18 - 16 28 14 02](https://github.com/user-attachments/assets/f5474d6f-b3b1-45a5-ac10-a44d5443c71a)

</details>

### Other extensions used

Tested with dedicated empty profiles

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Desktop Screenshot 2024 10 18 - 16 14 21 59](https://github.com/user-attachments/assets/0e60ae92-023e-407b-92e5-b6a7b81b4b14)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 154552
 cosmetic: 117437
 scriptlet: 30840
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 28037-1039, now
  adguard-mobile-app-banners: 5441-1127, now
  adguard-other-annoyances: 14690-383, now
  adguard-widgets: 2715-19, now
  easylist-annoyances: 4813-133, now
  easylist-chat: 216-0, now
  easylist-newsletters: 7987-28, now
  easylist-notifications: 3459-3, now
  ublock-annoyances: 5968-35, now Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 40246-526, now
  ublock-badware: 11779-22, now
  ublock-privacy: 1332-22, now Δ
  ublock-unbreak: 2488-3, now
  ublock-quick-fixes: 182-8, now Δ
  easylist: 79919-673, now Δ
  easyprivacy: 53170-782, 2d.8h.1m
  urlhaus-1: 26460-0, 1m
  plowe-0: 3548-4, 2d.8h.1m
  JPN-1: 15342-6, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 884 ms
 maxAssetCacheWait: 326 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  adpon.jp: 5
  googletagmanager.com: 1
  sentry.io: 13
 extended:
  ##.ad-overlay
  ##.ad-wrapper
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 For AG Japanese?

**Comment by DaisukeDaisuke** [comment]
I just noticed that it seems to block scrolling until you click the X in the popup
This is seriously broken

**Comment by stephenhawk8054** [comment]
```adb
peing.net##[id^="ad-interstitial-container"]
peing.net##[id^="ad-instream-container"]
peing.net##body[style="overflow: hidden;"]:style(overflow: auto !important;)
```
