### ISSUE TITLE
smartkeeda.com : nuisance

### ISSUE THREAD

**Issue by Manikandan-Vanniyar** [uBlockOrigin/uAssets#25701]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.smartkeeda.com/quantitative-aptitude/linear-inequalities-questions
```

### Description

popup Nuisance while accessing the website

### Other extensions used

violetmonkey
bypass paywall
dark reader

### Screenshot(s)

![Screenshot 2024-10-18 005725](https://github.com/user-attachments/assets/00dd5dcd-00e8-41fc-b92a-0d2b042d8cff)

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 344276
 cosmetic: 259731
 scriptlet: 54565
 html: 2299
listset (total-discarded, last-updated):
 added:
  https://neuter.mchang.xyz/filter/sponsorblock: 35-1, 4h.56m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 461-1, 9h.20m
  https://raw.githubusercontent.com/iam-py-test/uBlock-combo/main/list.txt: 115992-10, 4h.56m
  adguard-generic: 84557-4271, 1d.14h.21m
  adguard-spyware-url: 1739-244, 1d.14h.21m
  adguard-spyware: 70156-1497, 3d.9h.29m
  adguard-social: 23043-50, 3d.9h.28m
  adguard-cookies: 32146-63, 1d.14h.21m
  ublock-cookies-adguard: 1811-28, 6d.24m
  adguard-popup-overlays: 28024-941, 1d.14h.21m
  adguard-other-annoyances: 14674-461, 1d.14h.21m
  adguard-widgets: 2704-19, 1d.14h.21m
  [7 lists not shown]: [too many]
 default:
  user-filters: 138-4, never
  ublock-filters: 40499-138, 4h.56m Δ
  ublock-badware: 11781-871, 4h.56m Δ
  ublock-privacy: 1313-73, 4h.56m Δ
  ublock-unbreak: 2547-1, 4h.56m Δ
  ublock-quick-fixes: 181-12, 4h.56m Δ
  easylist: 79868-2330, 4h.56m Δ
  easyprivacy: 53170-20168, 4h.56m Δ
  urlhaus-1: 26805-15, 4h.55m
  plowe-0: 3541-1091, 11d.5h.54m
  IND-0: 13577-51, 4h.56m
filterset (user): [array of 135 redacted]
trustedset:
 added: [array of 55 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 17 redacted]
hostRuleset:
 added: [array of 315 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 795 ms (selfie)
 maxAssetCacheWait: 416 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
smartkeeda.com###BannerModal
```

**Comment by Manikandan-Vanniyar** [comment]
yes stephen bro that code solves the issue

**Comment by mapx-** [comment]
@Manikandan-Vanniyar you are using adguard lists, report here: https://github.com/adguardteam/adguardfilters/issues
