### ISSUE TITLE
secure.coventrybuildingsociety.co.uk: breakage

### ISSUE THREAD

**Issue by idanyd** [uBlockOrigin/uAssets#25700]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://secure.coventrybuildingsociety.co.uk/online-services/error?aspxerrorpath=/Online-Services/Login/ContactPreference`

### Category

breakage

### Description

The site needs to call the user for verification. On clicking the "Call me now" button I'm getting a "Page not available" error.

I tried removing cache and cookies, a different browser, using incognito mode. Only one I disabled uBlock Origin I managed to get the phone call.
When I reenabled the extension the issue returned.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a51d939b-785a-4f1a-b4c8-4307ccbc758e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 146438
 cosmetic: 48578
 scriptlet: 22734
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 79870-49, now
  easyprivacy: 53170-665, now
  plowe-0: 3548-376, now
  ublock-badware: 11779-24, now
  ublock-filters: 40242-365, now
  ublock-privacy: 1327-24, now
  ublock-quick-fixes: 182-0, now
  ublock-unbreak: 2489-12, now
  urlhaus-1: 26805-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1673 ms (selfie)
 maxAssetCacheWait: 435 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  adobedtm.com: 2
  demdex.net: 1
  teads.tv: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details?

> On clicking the "Call me now" button

Where is the "Call me now" button on your link above? What is the original URL that has that button to click on?

**Comment by idanyd** [comment]
Hi @stephenhawk8054.

The original URL is https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/ContactPreference.
However, if you're not in the middle of the logging-in process it'll automatically forward you to the "Page not available" page.

If you do have an account with Coventry and are trying to log-in, this is how the page looks (after entering your user/password in a previous page):
![image](https://github.com/user-attachments/assets/14732c7d-fb8a-4032-b192-0a3e3a04a490)

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > ▤ ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Open new tab and reproduce the issue
3. Switch to the logger window that was opened in step 1, [click on search bar, choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output)
4. Copy the logger via 📋 [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by idanyd** [comment]
Hi @stephenhawk8054,

These are the logs you requested:

+11
https://secure.coventrybuildingsociety.co.uk/online-services/error?aspxerrorpath=/Online-Services/Login/ContactPreference

+11
https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/ContactPreference

+9
https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/ContactPreference

+9
https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/Authenticate

+3
https://secure.coventrybuildingsociety.co.uk/Online-Services/

+0
https://secure.coventrybuildingsociety.co.uk/Online-Services/

**Comment by stephenhawk8054** [comment]
@idanyd Can you screenshot the logger?

**Comment by idanyd** [comment]
Sure.
![image](https://github.com/user-attachments/assets/5150b216-eb96-44db-85e7-b9c4348afed0)

**Comment by stephenhawk8054** [comment]
No, I don't mean you to **type** `blocked` in the search bar. I mean

> [click on search bar, choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output)

1. Click on the search bar
2. There are options to filter the results
3. Choose `blocked`

![image](https://github.com/user-attachments/assets/8dfdf340-016c-49a5-ad5e-c77f04b38112)

**Comment by idanyd** [comment]
Sorry, I think I misunderstood your request.

Here it is:

+159
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+148
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+51
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+35
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+34
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+33
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+32
||x.com/i/api/1.1/jot
--
x.com
0,1
post
xhr
https://x.com/i/api/1.1/jot/client_event.json

+10
||teads.tv^
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://p.teads.tv/teads-fellow.js

+10
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement_Module_ActivityMap.min.js

+10
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement.min.js

+10
https://secure.coventrybuildingsociety.co.uk/online-services/error?aspxerrorpath=/Online-Services/Login/ContactPreference

+10
https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/ContactPreference

+8
||iovation.com^$3p
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://first.iovation.com/general5/static_wdp.js?loaderVer=5.2.2&compat=false&tp=true&tp_split=false&fp_static=true&fp_dyn=true&flash=false

+7
||iesnare.com^
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://mpsnare.iesnare.com/general5/wdp.js?loaderVer=5.2.2&compat=false&tp=true&tp_split=false&fp_static=true&fp_dyn=true&flash=false

+7
||teads.tv^
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://p.teads.tv/teads-fellow.js

+7
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement_Module_ActivityMap.min.js

+7
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement.min.js

+7
https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/ContactPreference

+6
https://secure.coventrybuildingsociety.co.uk/Online-Services/Login/Authenticate

+3
||iovation.com^$3p
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://first.iovation.com/general5/static_wdp.js?loaderVer=5.2.2&compat=false&tp=true&tp_split=false&fp_static=true&fp_dyn=true&flash=false

+2
||iesnare.com^
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://mpsnare.iesnare.com/general5/wdp.js?loaderVer=5.2.2&compat=false&tp=true&tp_split=false&fp_static=true&fp_dyn=true&flash=false

+2
||teads.tv^
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://p.teads.tv/teads-fellow.js

+2
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement_Module_ActivityMap.min.js

+2
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement.min.js

+2
https://secure.coventrybuildingsociety.co.uk/Online-Services/

+0
||teads.tv^
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://p.teads.tv/teads-fellow.js

+0
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement_Module_ActivityMap.min.js

+0
||adobedtm.com^$3p,from=~adobe.com|~costco.com
--
secure.coventrybuildingsociety.co.uk
3
get
script
https://assets.adobedtm.com/extensions/EPe51f9b26f7c243dfa8d1d3ea2bf16f5f/AppMeasurement.min.js

+0
https://secure.coventrybuildingsociety.co.uk/Online-Services/

**Comment by stephenhawk8054** [comment]
Can you test these filters, one-by-one (don't add all of them at once, continue adding next one if the previous don't work so we can narrow down which one works for you):

```adb
@@||assets.adobedtm.com/extensions/*/AppMeasurement.min.js$domain=secure.coventrybuildingsociety.co.uk
@@||assets.adobedtm.com/extensions/*/AppMeasurement_Module_ActivityMap.min.js$domain=secure.coventrybuildingsociety.co.uk
@@||mpsnare.iesnare.com^$script,domain=secure.coventrybuildingsociety.co.uk
@@||iovation.com^$domain=secure.coventrybuildingsociety.co.uk
@@||teads.tv^$domain=secure.coventrybuildingsociety.co.uk
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by idanyd** [comment]
I added the filters one by one until the third one worked.
I then removed the first two and checked again, and still managed to log in.

So I think it's safe to say that the third one's the charm.

**Comment by stephenhawk8054** [comment]
Thanks for your testing.
