### ISSUE TITLE
web.archive.org: nuisance

### ISSUE THREAD

**Issue by andrewr31** [uBlockOrigin/uAssets#25706]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://web.archive.org/web/20070310023655/http://www.stardoll.com:80/en/dolls/530/Beyonce_3.html`

### Category

nuisance

### Description

Flash emulator not blocked

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 146141
 cosmetic: 48578
 scriptlet: 22742
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 79919-579, 27m Δ
  easyprivacy: 53170-630, 35m
  plowe-0: 3548-0, 35m
  ublock-badware: 11779-6, 34m Δ
  ublock-filters: 40246-259, 35m
  ublock-privacy: 1332-22, 35m
  ublock-quick-fixes: 182-0, 35m
  ublock-unbreak: 2488-19, 27m Δ
  urlhaus-1: 26460-0, 35m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 88 ms (selfie)
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 no-large-media: true
 network:
  archive.org: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I don't understand. Can you screenshot the nuisances?

**Comment by andrewr31** [comment]
[image: image.png]

**Comment by stephenhawk8054** [comment]
Please reply directly on github. Don't reply via email. Images cannot be sent via email.

**Comment by mapx-** [comment]
`web.archive.org###dollflash`

?

**Comment by andrewr31** [comment]
Thanks but that blocks the whole thing. I am looking for something to only
block Ruffle. The previous filter I had that used to work buy no longer
does was this:

https://web-static.archive.org/_static/js/ruffle/ruffle.js

**Comment by andrewr31** [comment]
![Image 10-18-24 at 4 49 PM](https://github.com/user-attachments/assets/331a963b-41d3-44c4-8cd5-d6cd788b62ef)

**Comment by stephenhawk8054** [comment]
Please point to the nuisances in your screenshot above.

**Comment by andrewr31** [comment]
![Image 10-18-24 at 8 33 PM](https://github.com/user-attachments/assets/29d289c7-08b1-41e8-82dc-f910f1f8dc9c)


The "Something went wrong" screen is the nuisance that overlays the Ruffle screen (see above screenshot)

**Comment by stephenhawk8054** [comment]
Test

```adb
web.archive.org##ruffle-embed:shadow(#container)
web.archive.org##ruffle-embed:shadow(#splash-screen.hidden):remove-class(hidden)
```

**Comment by andrewr31** [comment]
> Test
> 
> ```
> web.archive.org##ruffle-embed:shadow(#container)
> web.archive.org##ruffle-embed:shadow(#splash-screen.hidden):remove-class(hidden)
> ```

Hmm that blocked the "Something went wrong" screen but now it just has the Ruffle screen loading (but never actually loads).

I am trying to use it with the ModernKit.one Flash player, which when working has a screen like this:

![Image 10-19-24 at 12 04 AM](https://github.com/user-attachments/assets/fb110cef-d480-4e1c-8fd4-bd9e64a40494)

**Comment by stephenhawk8054** [comment]
Then it's the website's issue. Nothing we can do.

**Comment by krystian3w** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/25706#issuecomment-2423207173
> was:
> `web-static.archive.org/_static/js/ruffle/ruffle.js`

New path may be:

```
||web.archive.org/_static/js/ruffle/core.ruffle.*.js
||web.archive.org/_static/js/ruffle/ruffle.js
```

Looks killed "web&#8203;**`-static`**" subdomain.
