### ISSUE TITLE
superpsx.com: detection

### ISSUE THREAD

**Issue by cheesermangg** [uBlockOrigin/uAssets#25716]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.superpsx.com/`

### Category

detection

### Description

A pop-up appears when I am using ublock-origin

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/5c1c0fc7-19d5-4089-a40f-22097b1d3f5c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 273981
 cosmetic: 228615
 scriptlet: 55206
 html: 2300
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84861-4535, now
  adguard-mobile: 9985-92, now
  adguard-spyware-url: 1753-127, now
  adguard-spyware: 93743-1563, now
  block-lan: 64-0, now
  curben-phishing: 559-1, now
  adguard-cookies: 32202-1684, now
  ublock-cookies-adguard: 1833-27, now
  fanboy-cookiemonster: 52316-19874, now
  ublock-cookies-easylist: 1833-1833, now
  adguard-social: 23065-1236, now
  fanboy-social: 16716-10511, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 17-1, never
  ublock-filters: 40528-322, 46m Δ
  ublock-badware: 11785-12, 46m Δ
  ublock-privacy: 1318-23, 46m Δ
  ublock-unbreak: 2548-2, 46m Δ
  ublock-quick-fixes: 191-12, 46m Δ
  easylist: 80019-16158, 46m Δ
  easyprivacy: 53177-23812, 46m Δ
  urlhaus-1: 24520-0, now
  plowe-0: 3545-1498, now
filterset (user): [array of 18 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 805 ms (selfie)
 maxAssetCacheWait: 500 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  gekeebsirs.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(no-xhr-if, googlesyndication)
  ##+js(abort-on-stack-trace, document.getElementById, adsBlocked)
  ##+js(trusted-suppress-native-method, fetch, '"adsbygoogle.js"',…
```
</details>

**Comment by SuperPSX-Official** [comment]
Hi @cheesermangg and @cheesermangg

**Comment by SuperPSX-Official** [comment]
Hello, I've noticed that recent changes to uBlock’s filters are negatively impacting website, superpsx.com, by disabling ad detection. This has led to significant revenue losses. I request a review of these changes. Your attention to this matter is appreciated. @uBlockOrigin @stephenhawk8054

**Comment by SuperPSX-Official** [comment]
uBlock users laughing while they help destroy others' revenue under the name of 'begging.' What exactly are they earning by causing millions in losses? 😂 Just think, what if YouTube rolls out an update that uBlock can never bypass? It wouldn’t take long for them to go bankrupt 😂. uBlock users couldn’t create content themselves, so now they block ads on content creators’ work, living off the money meant for them. YouTube, for example, 😂.

Please do not delete this comment,

**Comment by SuperPSX-Official** [comment]
I spoke of the devil, and the devil appeared, U Block needs something new ASAP. Maybe U Block Light (Already Published) 😂

![image](https://github.com/user-attachments/assets/cd8f0de0-acfd-49ff-87c9-9982890425b6)
