### ISSUE TITLE
torrentfreak.com: ads

### ISSUE THREAD

**Issue by 055110** [uBlockOrigin/uAssets#25719]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://torrentfreak.com/iptv-piracy-lawsuit-targets-dmca-ignored-host-after-500-notices-ignored-241016/`

### Category

ads

### Description

"sponsors"

### Other extensions used

none that would interfere with standard adblocking functions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 169708
 cosmetic: 147244
 scriptlet: 32869
 html: 2317
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2689-0, 37m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/privacy_essentials.txt: 887-4, 37m
  adguard-spyware-url: 1753-244, 37m
  fanboy-cookiemonster: 52316-192, 37m
  ublock-cookies-easylist: 1833-14, 37m
  fanboy-social: 16716-10, 37m
  easylist-annoyances: 4813-48, 37m
  easylist-chat: 216-4, 37m
  easylist-newsletters: 7993-39, 37m
  easylist-notifications: 3461-166, 37m
  ublock-annoyances: 5909-82, 37m
  RUS-0: 41015-196, 37m
 default:
  user-filters: 0-0, never
  ublock-filters: 40531-132, 37m
  ublock-badware: 11785-6, 37m
  ublock-privacy: 1318-71, 37m
  ublock-unbreak: 2548-6, 37m
  ublock-quick-fixes: 194-12, 37m
  easylist: 80024-200, 37m
  easyprivacy: 53177-81, 37m
  urlhaus-1: 22085-0, 37m
  plowe-0: 3545-1003, 37m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4182 ms
 maxAssetCacheWait: 559 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  torrentfreak.com: 1
 extended:
  ##[href*="://go.nordvpn.net/"]
  ##a[href^="https://go.nordvpn.net/aff"] > img
  ##a[href^="https://www.privateinternetaccess.com/"] > img
```
</details>

**Comment by mapx-** [comment]
`torrentfreak.com##.o-widget:has([rel*="sponsored"])`
