### ISSUE TITLE
blockchair.com: ads

### ISSUE THREAD

**Issue by Monoverde888** [uBlockOrigin/uAssets#25713]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://blockchair.com/bitcoin-cash/address/qp4epj9c40rdt5nm2pj6wt895dcjjkhtduay5xws2z`

### Category

ads

### Description

its still showing ads

### Other extensions used

![image](https://github.com/user-attachments/assets/b49dcb73-ff83-4aba-8544-6888e6fbca3a)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/5397bf06-ce1a-4082-88e1-8a22c5d80f1d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 276522
 cosmetic: 289620
 scriptlet: 58809
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83087-83087, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/bcye/Hello-Goodbye/master/filterlist.txt: 129-0, now
  RUS-0: 40951-258, 1h.45m Δ
  adguard-cookies: 32196-42, now
  adguard-generic: 84874-7569, now
  adguard-mobile: 9985-133, now
  adguard-mobile-app-banners: 5441-1126, now
  adguard-other-annoyances: 14692-385, now
  adguard-popup-overlays: 28042-3033, now
  adguard-social: 23060-906, now
  adguard-spyware: 93743-24485, now
  [15 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 80019-959, now
  easyprivacy: 53177-876, now
  plowe-0: 3545-1, now
  spa-0: 4081-181, now
  spa-1: 6041-18, now
  ublock-badware: 11783-8, now
  ublock-filters: 40268-650, now
  ublock-privacy: 1332-141, now
  ublock-quick-fixes: 194-0, now
  ublock-unbreak: 2490-8, now
  urlhaus-1: 24520-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 130 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 795 ms (selfie)
 maxAssetCacheWait: 222 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.d-block
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
blockchair.com##.okane-top
```
