### ISSUE TITLE
spotifydown.com: breakage

### ISSUE THREAD

**Issue by jake01756** [uBlockOrigin/uAssets#25712]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://spotifydown.com/`

### Category

breakage

### Description

The "Download Zip" button is non functional when using uBlock. I have isolated the issue to uBlock. Without uBlock the button brings up a popup asking if you want to download the whole playlist. I have this feeling it is somehow related to #23597.

This is a cosmetic issue as it works if I disable "Parse and enforce cosmetic filters" in settings.

Here is a sample playlist you can use:
``https://open.spotify.com/playlist/4Wt1SGKKKjxRjHQg5b1ehK``

### Other extensions used

1Password
User-agent switcher
Pacifist Web Extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 115
filterset (summary):
 network: 148862
 cosmetic: 126548
 scriptlet: 28510
 html: 2038
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32196-51, 7m
  ublock-cookies-adguard: 1833-27, 8m
  fanboy-cookiemonster: 52315-4040, 8m
  ublock-cookies-easylist: 1833-1833, 8m
  adguard-mobile-app-banners: 5441-14, 9m
  easylist-notifications: 3458-1197, 8m
 default:
  user-filters: 0-0, never
  ublock-filters: 40528-131, 9m Δ
  ublock-badware: 11785-6, 9m Δ
  ublock-privacy: 1318-22, 9m Δ
  ublock-unbreak: 2546-1, 9m Δ
  ublock-quick-fixes: 191-12, 9m Δ
  easylist: 80007-188, 9m Δ
  easyprivacy: 53177-64, 9m Δ
  urlhaus-1: 24520-0, 52m
  plowe-0: 3545-1000, 52m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1958 ms (selfie)
 maxAssetCacheWait: 417 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##.semi-transparent
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
spotifydown.com#@#.semi-transparent
spotifydown.com##.semi-transparent:has(ins.adsbygoogle[data-ad-slot])
```
