### ISSUE TITLE
thelocal.at: detection

### ISSUE THREAD

**Issue by ExteriorCloth20** [uBlockOrigin/uAssets#25715]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thelocal.at/20241018/the-10-best-employers-in-austria`

### Category

detection

### Description

thelocal.at started detecting ad blockers

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/2441effc-ebaa-4557-bb5d-7b1cd6a2ef97)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 149879
 cosmetic: 57210
 scriptlet: 25732
 html: 2300
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 461-1, 3m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2689-2, 11m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/WikiaPureBrowsingExperience.txt: 80-0, 3m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2126-1, 3m
  block-lan: 64-0, 3m
  ublock-annoyances: 5909-73, 56m Δ
  DEU-0: 7548-38, 56m
  HRV-0: 397-4, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 40528-140, 56m Δ
  ublock-badware: 11785-6, 56m Δ
  ublock-privacy: 1318-71, 56m Δ
  ublock-unbreak: 2548-1, 56m Δ
  ublock-quick-fixes: 191-12, 56m Δ
  easylist: 80019-200, 56m Δ
  easyprivacy: 53177-80, 56m Δ
  urlhaus-1: 24520-0, 55m
  plowe-0: 3545-999, 3m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 prefetchingDisabled: false
hiddenSettings:
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 5
 filterAuthorMode: true
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 730 ms
 maxAssetCacheWait: 303 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  doubleclick.net: 1
  google.com: 2
  googletagmanager.com: 1
  mailerlite.com: 1
  npttech.com: 1
  piano.io: 1
  protagcdn.com: 2
  taboola.com: 1
  thelocal.com: 2
 extended:
  ##.ad-container
  ##.tl-ad-container
  ##.dfp-ad
  ###taboola-below-article-thumbnails
```
</details>

**Comment by mapx-** [comment]
You are using some other filter lists blocking the paywall => piano / tinypass is blocked => detection
We do not block the paywalls.

for your personal use add:

`thelocal.at##+js(rmnt, script, onerror)`
