### ISSUE TITLE
thedailybeast.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#25718]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.thedailybeast.com/cheat-sheet/`

### Category

breakage

### Description

breakage

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/81bd43c4-42c8-4a92-babf-27d6ea836473)
![image](https://github.com/user-attachments/assets/1b1c9628-46d8-4b4c-8553-f1b36b2b6aa4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 141777
 cosmetic: 48582
 scriptlet: 22769
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40271-259, now
  ublock-badware: 11779-6, now
  ublock-privacy: 1332-22, now
  ublock-unbreak: 2488-0, now
  ublock-quick-fixes: 195-0, now
  easylist: 79919-579, now
  easyprivacy: 53177-649, now
  urlhaus-1: 22085-0, now
  plowe-0: 3545-0, now
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2478 ms
 maxAssetCacheWait: 37 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  thedailybeast.com: 1
  amazon-adsystem.com: 1
  cxense.com: 1
  doubleverify.com: 1
  go-mpulse.net: 2
  googletagmanager.com: 2
  npttech.com: 1
  ntv.io: 1
  p-n.io: 1
  pubmatic.com: 1
  sail-horizon.com: 1
  spot.im: 5
  teads.tv: 1
 extended:
  ###adhesion
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
add

```
@@||thedailybeast.com/pf/resources/js/ads/arcads.js$script,1p
thedailybeast.com##.tdb-ads-block
thedailybeast.com##.ad-container
```
