### ISSUE TITLE
sites detecting ublock origin

### ISSUE THREAD

**Issue by sheikh-azharuddin** [uBlockOrigin/uAssets#25720]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://onlytech.com/community/
https://dreamdth.com/community/
```

### Description

both sites detecting ublock origin

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_2024-10-19-23-43-50-92_984e1414ae90666a90f12ff17ec14a7f](https://github.com/user-attachments/assets/e371d87d-f05b-4aa1-a922-f83af774464f)

### Configuration

<details>
<summary>Details</summary>

<!-- ⬇️ Paste the troubleshooting information here ⬇️ 
uBlock Origin: 1.60.0
Firefox Mobile: 133
filterset (summary):
 network: 143292
 cosmetic: 57332
 scriptlet: 21207
 html: 2040
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41040-214, 1h.28m Δ
  ublock-badware: 11779-7, 1h.28m Δ
  ublock-privacy: 1319-22, 1h.28m Δ
  ublock-unbreak: 2550-3, 1h.28m Δ
  ublock-quick-fixes: 194-12, 1h.28m Δ
  adguard-mobile: 9985-12, 6m
  easylist: 80024-262, 1h.28m Δ
  easyprivacy: 53177-73, 1h.28m Δ
  urlhaus-1: 22085-0, 6m
  plowe-0: 3545-1074, 6m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 349 ms (selfie)
 maxAssetCacheWait: 123 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  dreamdth.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##.samCodeUnit
  ##ins.adsbygoogle[data-ad-client]
  ##+js(abort-on-property-write, wutimeBotPattern)
  ##+js(set-constant, adBlockDetected, false)
  ##+js(abort-current-script, $, show)
  ##+js(abort-current-script, eval, replace)
</details>

**Comment by D4niloMR** [comment]
Continue in #24538
