### ISSUE TITLE
play1.kirastream.my.id: ads

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25724]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://play1.kirastream.my.id/page-server/?to-st=https://short.ink/fmJ9cYnpT?image=https://raretoonindia.fun/wp-content/uploads/2023/07/Jujutsu-Kaisen-Season-2.jpg&to-stt=https://short.ink/fmJ9cYnpT&to-dlink=https://new1.filepress.skin/file/650d27a9745975af035693f0&to-name=Jujutsu%20Kaisen%20Season%202%20Episode%2001%20-%20Hidden%20Inventory/?ref=nosess`

### Category

ads

### Description

Streamlink is provided by https://raretoonindia.fun/jujutsu-kaisen-season-2-anime-in-hindi/

![1000109236](https://github.com/user-attachments/assets/dda2b91d-9f4d-49e0-971f-cbbab3902f53)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 394107
 cosmetic: 218737
 scriptlet: 38099
 html: 2319
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://big.oisd.nl: 137389-0, now
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1090-2, 9m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-2, 9m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 107117-257, 9m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2683-2, 21m
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 451-34, 9m
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/refs/heads/main/antitypo.txt: 2080-24, 9m
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4109-36, 9m
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, 9m
  curben-phishing: 502-424, 9m
  fanboy-cookiemonster: 52317-201, 9m
  ublock-annoyances: 5936-102, 9m
  [12 lists not shown]: [too many]
 default:
  ublock-filters: 41053-310, 9m
  ublock-badware: 11779-1440, 9m
  ublock-privacy: 1319-92, 9m
  ublock-unbreak: 2546-2, 9m
  ublock-quick-fixes: 186-11, 9m
  adguard-mobile: 9985-708, 9m
  easylist: 80014-27209, 9m
  easyprivacy: 53177-4656, 9m
  urlhaus-1: 23215-333, 9m
  plowe-0: 3545-2607, 9m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4042 ms
 maxAssetCacheWait: 1988 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  brutishlylifevoicing.com: 2
  google-analytics.com: 1
  googletagmanager.com: 4
  highrevenuenetwork.com: 2
  jdi5.com: 2
  news-xdafuwi.today: 1
  ptailadsol.net: 2
  udzpel.com: 1
  wb4.xyz: 1
 extended:
  ###overlay
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##+js(set-constant, document.ontouchend, null)
  ##+js(set-constant, document.onclick, null)
  ##+js(abort-on-stack-trace, HTMLElement.prototype.click, _0x)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, devtoolsDetector.launch, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
play1.kirastream.my.id##[href="https://t.me/Crypto_Journey_WITH_DOGS"]
||cank.xyz^
```

**Comment by Rachitidk** [comment]
Not working fully, there is some leftover space in place of fast download and download now is unclickable but still present.
![1000109245](https://github.com/user-attachments/assets/1d4caf18-1d41-459f-b229-bf9cb6f4992d)


> Test
> 
> ```
> play1.kirastream.my.id##[href="https://t.me/Crypto_Journey_WITH_DOGS"]
> ||cank.xyz^
> ```

**Comment by mapx-** [comment]
report at easylist repository

**Comment by Rachitidk** [comment]
> report at easylist repository

How?

**Comment by Rachitidk** [comment]
Done

**Comment by Rachitidk** [comment]
Hey, guys easylist is taking forever to fix can't you all fix this. Also this ads are not self promotion.
Thanks you
Best regards.

**Comment by Rachitidk** [comment]
Hey, Guys the real `download now` present  at middle button has disappeared and fake download now is hidden at bottom but still there.

**Comment by stephenhawk8054** [comment]
Caused by `kirastream.my.id##.dwnLink` in EL.

cc @Yuki2718
