### ISSUE TITLE
pan.baidu.com: breakage

### ISSUE THREAD

**Issue by ChaoSection** [uBlockOrigin/uAssets#25735]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pan.baidu.com/s/16fj4BJpD2FVdymo6KOU8UA`

### Category

breakage

### Description

使用完全模式时隐藏了内容列表，优化模式没有问题

--

**TL: Content list hidden when using full mode, no problem with optimized mode**

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.10.14.189
mode: complete / complete
rulesets:
 default
 chn-0
 block-lan
 dpollock-0
 adguard-spyware-url
 annoyances-cookies
 annoyances-overlays
 annoyances-social
 annoyances-widgets
 annoyances-others
 stevenblack-hosts
```

**Comment by ChaoSection** [comment]
v5xg

**Comment by stephenhawk8054** [comment]
It shows error

![image](https://github.com/user-attachments/assets/03804572-d34d-4c6b-bb9b-d140cb9e564e)

**Comment by ChaoSection** [comment]
> 它显示错误
> 
> ![图像](https://private-user-images.githubusercontent.com/66517106/378448543-03804572-d34d-4c6b-bb9b-d140cb9e564e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTc5MjUsIm5iZiI6MTcyOTU1NzYyNSwicGF0aCI6Ii82NjUxNzEwNi8zNzg0NDg1NDMtMDM4MDQ1NzItZDM0ZC00YzZiLWJiOWItZDE0MGNiOWU1NjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAwNDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDY0ZTExNzA5NWQ0ZmQ1ODlkNjNkMTliMDNlZWFmNGFlNjYzZmE1ODQ0NzkxNjdjOWJlYWY1NDg5OGVlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XWqLSal9ptLcJcwdSNYtlop5GYX86B8TD8VZlIezIME)

这是网站识别为不安全时的安全识别，正确输入框右面显示的字符就可以，无法识别可以使用右边的刷新
我自行建立了一个链接，可以用于测试：https://pan.baidu.com/s/1EkfsqISi1Nea1gtnza8_NA?pwd=zg7m

**Comment by stephenhawk8054** [comment]
It's caused by the generic filter `##.share-list` in `EasyList – Social Widgets`, which is solved by `baidu.com#@#.share-list` in the same list. However, [exceptions for generic cosmetic filters are not supported at the moment](https://github.com/uBlockOrigin/uBOL-home/issues/181#issuecomment-2293869807), so currently there are no solutions except you have to lower the mode of this site to `Optimize` or not using `EasyList – Social Widgets` list.
