### ISSUE TITLE
appointment.diplomatie.be: breakage

### ISSUE THREAD

**Issue by saucefrog** [uBlockOrigin/uAssets#25738]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://appointment.diplomatie.be/Home/Welcome
```

### Description

This website is used to make an appointment at the embassy. There will be a referrer ID after the "Welcome", which I obviously omitted. Once I had filled out the form and sent it, I was shown a blank page and my data wasn't transmitted.

I had to switch off uBlock Origin and fill out the form again so it would work correctly and show me a page that says my data was successfully transmitted.

### Other extensions used

A lot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 244018
 cosmetic: 221431
 scriptlet: 53468
 html: 2304
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83065-2363, 4d.3h.1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103241-52761, 3d.12m
  adguard-generic: 84842-6527, 4d.3h.1m
  adguard-mobile: 9979-174, 4d.3h.2m
  adguard-social: 23057-2337, 4d.3h.2m
  fanboy-thirdparty_social: 68-19, 3d.12m
  fanboy-cookiemonster: 69015-69013, 1d.10h.32m
  fanboy-social: 16737-16737, 3d.5h.46m
  ublock-annoyances: 5906-257, 2h.41m Δ
  adguard-spyware: 93734-25339, 4d.3h.2m
 default:
  ublock-filters: 40541-322, 2h.41m Δ
  ublock-badware: 11790-12, 2h.41m Δ
  ublock-privacy: 1327-26, 2h.41m Δ
  ublock-unbreak: 2538-38, 2h.41m Δ
  easylist: 80040-14253, 2h.41m Δ
  easyprivacy: 53178-45, 2h.41m Δ
  urlhaus-1: 22975-0, 12h.37m
  plowe-0: 3541-1083, 12d.22h.2m
  DEU-0: 7552-460, 12h.37m
  ublock-quick-fixes: 186-13, 2h.41m Δ
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 75 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 639 ms (selfie)
 maxAssetCacheWait: 229 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  google-analytics.com: 1

```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
