### ISSUE TITLE
littlebigsnake.com: detection

### ISSUE THREAD

**Issue by sysgender** [uBlockOrigin/uAssets#25736]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://littlebigsnake.com/`

### Category

detection

### Description

Site detects adblock & prevents skipping ads. Tried private window with no other extensions, disabling extra filters, enabling extra filters, disabling FF tracking prevention, still detected though. Report uses my normal settings & no VPN.

### Other extensions used

Leechblock & 7TV but issue persisted with all extensions disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/bc9318c7-280b-4969-a0b2-26b2006ef7a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 130
filterset (summary):
 network: 147575
 cosmetic: 119552
 scriptlet: 28406
 html: 2040
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32209-51, 3m
  ublock-cookies-adguard: 1841-27, 3m
  fanboy-cookiemonster: 52317-4040, 3m
  ublock-cookies-easylist: 1833-1816, 3m
 default:
  user-filters: 3-0, never
  ublock-filters: 40542-131, 14m
  ublock-badware: 11790-6, 14m
  ublock-privacy: 1327-22, 14m
  ublock-unbreak: 2538-1, 14m
  ublock-quick-fixes: 183-8, 14m
  easylist: 80074-187, 14m
  easyprivacy: 53181-63, 14m
  urlhaus-1: 23685-0, 14m
  plowe-0: 3545-1000, 14m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5480 ms (selfie)
 maxAssetCacheWait: 158 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  littlebigsnake.com: 8
  adinplay.com: 1
  googletagmanager.com: 1
  scorecardresearch.com: 1
  unity3d.com: 3
  zendesk.com: 1
 extended:
  ###advertisement_banner
  ###adsContainer
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25250
