### ISSUE TITLE
emol.com: ads

### ISSUE THREAD

**Issue by nstraub** [uBlockOrigin/uAssets#25737]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.emol.com/`

### Category

ads

### Description

I get a full-page ad when the site loads. also, ads to the side of the page, and the mobile page is full of ads

### Other extensions used

privacybadger. issues still show up after I disable it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/4c69ccce-7d23-4bc3-8072-f07ae5b9c347)

![image](https://github.com/user-attachments/assets/708290ef-ad36-49ad-93f4-cc8031d18c9f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 143545
 cosmetic: 48584
 scriptlet: 21140
 html: 2040
listset (total-discarded, last-updated):
 default:
  user-filters: 2-1, never
  ublock-filters: 40542-131, now
  ublock-badware: 11790-6, now
  ublock-privacy: 1327-22, now
  ublock-unbreak: 2538-1, now
  ublock-quick-fixes: 185-8, now
  easylist: 80074-187, now
  easyprivacy: 53181-63, now
  urlhaus-1: 23685-0, now
  plowe-0: 3545-999, now
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 581 ms (selfie)
 maxAssetCacheWait: 71 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  emol.com: 6
  ecn.cl: 5
  emol.cl: 2
  google-analytics.com: 2
  pdnegocios.cl: 12
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable the regional filterlists `AdGuard Spanish/Portuguese` and `EasyList Spanish`
