### ISSUE TITLE
bsky.app: breakage

### ISSUE THREAD

**Issue by rrika** [uBlockOrigin/uAssets#25744]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bsky.app/`

### Category

breakage

### Description

Video uploads fail when featuregates.org is unreachable

### Other extensions used

tampermonkey (not active on bsky.app)
firefox multi-account containers (not active in tab showing the issue)
foxyproxy (not active on bsky.app)

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 143409
 cosmetic: 48587
 scriptlet: 21202
 html: 2041
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 40604-131, now
  ublock-badware: 11844-6, now
  ublock-privacy: 1335-22, now
  ublock-unbreak: 2541-1, now
  ublock-quick-fixes: 183-8, now
  easylist: 80094-188, now
  easyprivacy: 53181-63, now
  urlhaus-1: 23470-0, now
  plowe-0: 3545-999, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 562 ms
 maxAssetCacheWait: 211 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  featuregates.org: 1
  statsigapi.net: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me.

**Comment by rrika** [comment]
works now, might've been fixed service side

**Comment by neoapps-dev** [comment]
doesn't work for me :/
