### ISSUE TITLE
support.industry.siemens.com: breakage

### ISSUE THREAD

**Issue by JanB1** [uBlockOrigin/uAssets#25745]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://support.industry.siemens.com/forum/ch/en/posts/wincc-unified-simulation-partly-running/272593`

### Category

breakage

### Description

Website loads properly if "Online Malicious URL Blocklist" is deactivated. I don't know if this is a default list or not.
Websites delivers HTTP error 500.
Additional website that is also broken:
https://support.industry.siemens.com/forum/ch/en/posts/an-incorrect-runtime-version-is-installed-the-installed-runtime-cannot-process-the-project-install-the-runtime-manually-on-the-target-device/314992

### Other extensions used

Privacy Badger, but the problem persists if Privacy Badger is deactivated.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 145727
 cosmetic: 53782
 scriptlet: 21202
 html: 2041
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40604-131, now
  ublock-badware: 11844-6, now
  ublock-privacy: 1335-22, now
  ublock-unbreak: 2541-1, now
  ublock-quick-fixes: 183-8, now
  easylist: 80094-188, now
  easyprivacy: 53181-63, now
  urlhaus-1: 23470-0, now
  plowe-0: 3545-999, now
  DEU-0: 7559-38, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

![image](https://github.com/user-attachments/assets/3e231cbc-20f3-45d1-99dc-249db398869a)

**Comment by JanB1** [comment]
Okay, I tried around a little more. It seems to be a combination of uBlock and Privacy Badger. If I deactivate privacy badger, it mostly works. Weirdly enough, it also works in a private session with both of those extensions activated. And the website still doesn't work if I deactivate Privacy Badger just for this site through the Privacy Badger extension.

I don't know exactly what seems to be the problem here, I sporadically had issues with this website before, but not like today. Maybe someone can reproduce?

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I am not using uBlock Origin along with other content blockers.
