### ISSUE TITLE
dailypost.co.uk , dailystar.co.uk , mirror.co.uk , the-express.com : breakage

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [uBlockOrigin/uAssets#25759]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.mirror.co.uk/news/uk-news/storm-ashley-terrifying-videos-show-33933980
https://www.dailystar.co.uk/news/eight-toothed-tree-eating-critter-33933758
https://www.dailypost.co.uk/news/north-wales-news/michael-palin-welshness-shaped-terry-30063737
https://www.the-express.com/entertainment/movies/151590/I-Robot-director-Elon-Musk-Tesla-product
```

### Description

**No video.**
Private browsing + VPN
Firefox + uBlock Origin +/- **EasyList/uBO – Cookie Notices**

Solution + more info: 
https://github.com/easylist/easylist/issues/20182

**Can you reproduce?**
Please address this in `quick-fixes.txt`.
Thank you

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    

Firefox/Chromium
Default configuration +/-  **EasyList/uBO – Cookie Notices**

**Comment by stephenhawk8054** [comment]
About these

```yml
https://www.mirror.co.uk/news/uk-news/storm-ashley-terrifying-videos-show-33933980
https://www.dailystar.co.uk/news/eight-toothed-tree-eating-critter-33933758
https://www.dailypost.co.uk/news/north-wales-news/michael-palin-welshness-shaped-terry-30063737
```

I only need these:

```adb
@@||micro.rubiconproject.com/prebid/dynamic/$script,domain=dailypost.co.uk|dailystar.co.uk|mirror.co.uk
dailypost.co.uk,dailystar.co.uk,mirror.co.uk##+js(nano-stb, native code, 15000)
dailypost.co.uk,dailystar.co.uk,mirror.co.uk##+js(nano-stb, (null), 5000)
```

Note that you'll need to accept the cookie and open the links again in new tab to make the videos play. This happens even when I don't use any extensions.

---

> ` https://www.the-express.com/entertainment/movies/151590/I-Robot-director-Elon-Musk-Tesla-products`

Video plays fine after I accept the cookie.

**Comment by stephenhawk8054** [comment]
### With cookie lists

These work for me:

```adb
@@||cmp.inmobi.com^$script,domain=dailypost.co.uk|the-express.com
@@||cmp.inmobi.com/*.json^$xhr,domain=dailypost.co.uk|the-express.com
@@||cdn-images.the-express.com/*/dist/gdpr-$script,1p
dailypost.co.uk,the-express.com##+js(trusted-click-element, button[mode="primary"])
dailypost.co.uk,the-express.com###qc-cmp2-container:style(visibility: hidden !important;)
```

**Comment by Hebrew-uBO-User** [comment]
@stephenhawk8054 
`mirror.co.uk` and `dailystar.co.uk` are still broken...

`https://www.mirror.co.uk/tv/tv-news/itv-big-brother-fans-left-33989487`
`https://www.dailystar.co.uk/showbiz/oasis-fans-set-heartbreak-50000-33989064`

( Firefox + uBO + **EasyList/uBO – Cookie Notices** + **Private Browsing** + **VPN** )

**Comment by stephenhawk8054** [comment]
This works for me with `mirror.co.uk`:

```adb
mirror.co.uk##+js(no-xhr-if, cmp.inmobi.com/geoip)
```

With `dailystar.co.uk`, looks like it has 2 types of cookie dialogs so I don't know which one is causing issue. These look like working for me with the cookie appearing at the bottom:

```adb
dailystar.co.uk##+js(no-xhr-if, cmp.inmobi.com/geoip)
@@||cmp.inmobi.com/GVL-$xhr,domain=dailystar.co.uk
||jwpcdn.com/player/plugins/googima/*/googima.js^$script,redirect=google-ima.js,domain=dailystar.co.uk
```

**Comment by Hebrew-uBO-User** [comment]
@stephenhawk8054 

You need `@@||cmp.inmobi.com/geoip$xhr,domain=dailypost.co.uk` for `dailypost.co.uk` when EasyList **Cookie** is enabled.

`dailystar.co.uk` is partly broken (recommended articles) + placeholder `dailystar.co.uk##.commercial-label-style`

also videos on `dailyrecord.co.uk` are broken: `https://www.dailyrecord.co.uk/entertainment/music/oasis-murrayfield-live-edinburgh-35695431`

**Comment by Marko-98** [comment]
Cookie notice

URL: `https://www.the-express.com/news/world-news/196794/real-reason-macron-was-wearing`

<details>
<summary>Screenshot(s)</summary>




<img width="2559" height="1379" alt="Image" src="https://github.com/user-attachments/assets/7b7c1c39-5029-4523-a2c1-85b3b0d9d403" />



</details>

<details>

```yaml
uBlock Origin: 1.68.0
Firefox: 147
filterset (summary):
 network: 324408
 cosmetic: 243503
 scriptlet: 60818
 html: 3212
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-generic: 91950-533, now
  block-lan: 89-0, now
  curben-phishing: 132723-58, 42m
  adguard-cookies: 36633-82, now
  ublock-cookies-adguard: 5344-76, now
  fanboy-cookiemonster: 45050-3608, now
  ublock-cookies-easylist: 5344-5344, now
  adguard-social: 25573-43, now
  fanboy-thirdparty_social: 69-3, now
  adguard-popup-overlays: 29838-957, now
  adguard-mobile-app-banners: 6748-96, now
  adguard-other-annoyances: 15521-292, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 44347-4973, 42m Δ
  ublock-badware: 11076-157, 42m Δ
  ublock-privacy: 3579-11, 42m Δ
  ublock-unbreak: 2784-88, 42m Δ
  ublock-quick-fixes: 419-90, 42m Δ
  easylist: 89008-1190, 42m Δ
  easyprivacy: 55215-120, 42m Δ
  urlhaus-1: 25975-6, 42m
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 248 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  amplitude.com: 1
  express.co.uk: 2
  googletagmanager.com: 1
  inmobi.com: 1
  onesignal.com: 2
  privacymanager.io: 1
  pub.network: 2
  webcontentassessor.com: 2
 extended:
  ##.taboola-above-article
  ##.taboola-container
  ##.sharebar
  ##.share-button
  ##.ad-wrapper
  ###ad-vip-article
  ###taboola-ad
  ###taboola-below-article-thumbnails-express
  ###taboola-right-rail-express
  ###bottomad
  ###ovp-primis
  ##[data-tb-non-consent]
  ###mantis-recommender-placeholder
  ##body [id^="div-gpt-ad"]:not(#style_important)
  ##[data-freestar-ad][id]
  ##[title="Share on LinkedIn"]
  ##[title="Share on Reddit"]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
```
</details>
