### ISSUE TITLE
paramountplus.com: breakage

### ISSUE THREAD

**Issue by matthew02** [uBlockOrigin/uAssets#25769]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.paramountplus.com/shows/video/2WtIfaACgX8zRBk6_QOqZikO7NBQ3oiH/`

### Category

breakage

### Description

Video will not load on page unless I disable "EasyList - Cookie Notices", "AdGuard - Cookie Notices", and allow local 3rd-party scripts. I must do all three things in order to watch a video. Verified in a new profile with UBO as the only extension.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 255385
 cosmetic: 163882
 scriptlet: 47809
 html: 2307
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85183-4541, 6m
  adguard-mobile: 10009-92, 6m
  adguard-spyware-url: 1764-128, 6m
  block-lan: 64-0, 6m
  curben-phishing: 540-6, 5m
  adguard-social: 23085-1231, 7m
  fanboy-thirdparty_social: 68-4, 7m
  fanboy-social: 16734-10524, 7m
  ublock-annoyances: 5910-78, 7m
  dpollock-0: 11702-405, 5m
  adguard-spyware: 98014-25392, 6m
  adguard-popup-overlays: 28070-2234, 7m
  [7 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40630-322, 6m
  ublock-badware: 11844-12, 6m
  ublock-privacy: 1345-23, 6m
  ublock-unbreak: 2547-2, 6m Δ
  ublock-quick-fixes: 185-8, 6m Δ
  easylist: 80195-16172, 6m
  easyprivacy: 53181-166, 5m Δ
  urlhaus-1: 23915-0, 5m
  plowe-0: 3545-1435, 5m
filterset (user): [empty]
trustedset:
 added: [array of 128 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 980 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 468 ms (selfie)
 maxAssetCacheWait: 165 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 44
 network:
  paramountplus.com: 1
  adoberesources.net: 1
  ads-twitter.com: 1
  appboycdn.com: 2
  bing.com: 1
  branch.io: 1
  cbsaavideo.com: 5
  cbsivideo.com: 12
  cedexis.com: 2
  doubleclick.net: 1
  googletagmanager.com: 1
  impactradius-event.com: 1
  kochava.com: 1
  mtvnservices.com: 2
  newrelic.com: 4
  nr-data.net: 1
  ns1p.net: 2
  pinimg.com: 1
  sc-static.net: 1
  scorecardresearch.com: 1
  tiktok.com: 1
  yahoo.com: 1
 extended:
  ##+js(set-constant, hasAdBlocker, false)
  ##+js(xml-prune, Period[id*="-roll-"][id*="-ad-"], , pubads.g.do…
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by matthew02** [comment]
US. Sorry I forgot to mention that.

**Comment by KikoN12** [comment]
I have the same issue today Oct. 24, when i disable UB, video plays

**Comment by stephenhawk8054** [comment]
The link looks like need an account. Do you know any free links that have the same issue?

**Comment by Raza-0007** [comment]
I have the same issue. Since the last 2 days no video on Paramountplus will load with ubo enabled. I have been unable to figure out the actual cause.

**Comment by stephenhawk8054** [comment]
Do the videos here play fine for anyone?

```yml
https://www.paramountplus.com/shows/video/pW1a3CChtGACVvkHY4uS4Uai3rkPGArK
https://www.paramountplus.com/shows/video/QWjVcJwoP0De8RwVSncw_c4kjH_Ooo95
```

**Comment by Raza-0007** [comment]
Both of the above links do not work. The page loads with the menu bar, as well as the other episodes at the bottom, but where the actual video is supposed to be is all blank.

**Comment by Raza-0007** [comment]
So I figured something out. You need disable Firefox's Enhanced Tracking Protection and allow the following tracker on ubo dynamic filtering: `www.paramountplus.com consent-api.onetrust.com * allow`

Then everything works fine. But I am not sure whether the adds are blocked now or not. I am testing and will report back.

**Comment by stephenhawk8054** [comment]
@Raza-0007 Are you enabling any cookie lists in uBO?

**Comment by Raza-0007** [comment]
Yes, EasyList/uBO – Cookie Notices 2/2 are enabled.

**Comment by stephenhawk8054** [comment]
@Raza-0007 Can you backup uBO's configuration, reset to default settings, restart the browser, open new tab and test again? (disable Firefox Enhanced Tracking Protection too)

**Comment by Raza-0007** [comment]
@stephenhawk8054, I just tested it. With UBO on default settings and Enhanced Tracking Protection in FF disabled or on the standard mode, everything works fine.

I believe the culprit is `consent-api.onetrust.com`. When this gets blocked, Paramountplus breaks. They must have changed something in the last 2 days becasue it used to work fine before.

**Comment by stephenhawk8054** [comment]
Please report to EL about the cookie issue: https://github.com/easylist/easylist/issues

**Comment by mapx-** [comment]
@Raza-0007 could you test again using the filters @ryanbr added [above](https://github.com/easylist/easylist/commit/1f45140455f10a0cd942d8442e19d0b646c7da42) ?

**Comment by Raza-0007** [comment]
@mapx- I just tested it after removing the custom rule I entered and then updating all my UBO filters, which hopefully included the commit that @ryanbr added 17 hrs ago, but the issue remains **unresolved**. 

I had to re-add this custom rule under "My rules" `www.paramountplus.com consent-api.onetrust.com * allow` in order for the video to load in FF with UBO enabled. (I have Enhanced Tracking Protection disabled for paramountplus).

**Comment by stephenhawk8054** [comment]
@Raza-0007 Can you remove your custom rules/filters and do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > ▤ ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Open new tab and reproduce the issue
3. Switch to the logger window that was opened in step 1, [click on search bar, choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output)
4. Copy the logger via 📋 [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by Raza-0007** [comment]
@stephenhawk8054, The log is attached.

[Logger.txt](https://github.com/user-attachments/files/17528432/Logger.txt)

**Comment by stephenhawk8054** [comment]
@Raza-0007 Can you test this filter:

```adb
@@||consent-api.onetrust.com/v1/preferences^$xhr,domain=paramountplus.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Raza-0007** [comment]
@stephenhawk8054, this filter rule has fixed the issue.

**Comment by stephenhawk8054** [comment]
Thanks for your testing.

**Comment by Raza-0007** [comment]
@stephenhawk8054. No problem, and thank you for taking time to fix this issue.
