### ISSUE TITLE
lefigaro.fr: nuisance

### ISSUE THREAD

**Issue by gut1414** [uBlockOrigin/uAssets#25765]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lefigaro.fr/conjoncture/une-majorite-de-francais-soutient-la-legalisation-des-casinos-en-ligne-selon-une-etude-20241022`

### Category

nuisance

### Description

A cookiewall who force you to accept ALL cookies or pay a subscription. 

### Other extensions used

Adblocker Ultimate (disabled for this site). Same when uninstalled. Problems in Firefox. No problems in Chrome after same tests in Chrome browser.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Une majorité de Français soutient la légalisation des casinos en ligne, selon une étude 2024-10-23](https://github.com/user-attachments/assets/3da2b3eb-5d03-41c3-bb78-66c9792dc236)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 148627
 cosmetic: 48613
 scriptlet: 21236
 html: 2043
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 default:
  user-filters: 0-0, never
  ublock-filters: 40630-131, now
  ublock-badware: 11844-6, now
  ublock-privacy: 1345-22, now
  ublock-unbreak: 2547-1, now
  ublock-quick-fixes: 185-8, now
  easylist: 80195-188, now
  adguard-spyware-url: 1764-128, now
  easyprivacy: 53181-64, now
  urlhaus-1: 23915-0, now
  curben-phishing: 540-6, now
  plowe-0: 3545-999, now
  LegitimateURLShortener: 2689-166, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5943 ms (selfie)
 maxAssetCacheWait: 216 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.fig-ad-content
```
</details>

**Comment by D4niloMR** [comment]
Enable uBlock filters – Cookie Notices list.

**Comment by gut1414** [comment]
Thanks you very much. There are so mush list i'm lost, but efficient!
