### ISSUE TITLE
elevenforum.com: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#25767]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

`https://www.elevenforum.com/t/add-or-remove-recycle-bin-in-navigation-pane-of-file-explorer-in-windows-11.6255/#Two`

`https://www.elevenforum.com/attachment-download-timer/28348`

### Description

Brinks team added timer before download own `reg` or `zip` files from forum. Maybe not implemented server side delay yet.

### Other extensions used

N/A

### Screenshot(s)

N/A

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
SRWare Iron: 126
filterset (summary):
 network: 145739
 cosmetic: 58513
 scriptlet: 27052
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5969-36, never
 default:
  user-filters: 0-0, never
  ublock-filters: 40370-179, now
  ublock-badware: 11842-6, now
  ublock-privacy: 1359-22, now
  ublock-unbreak: 2489-0, now
  ublock-quick-fixes: 184-0, now
  easylist: 80195-593, now
  easyprivacy: 53181-764, now
  urlhaus-1: 23915-0, now
  plowe-0: 3545-0, now
  POL-0: 8761-27, now
  POL-2: 1280-12, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4210 ms
 maxAssetCacheWait: 30 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like they still apply server delay. I added

```adb
elevenforum.com##+js(nano-sib, timeLeft)
```

but the timer just resets.

**Comment by 3xploiton3** [comment]
![Image](https://github.com/user-attachments/assets/331f679e-fc70-420b-8491-b55be03c54c2)

https://www.elevenforum.com/t/enable-or-disable-facts-tips-and-tricks-on-lock-screen-in-windows-11.7079/

**Comment by stephenhawk8054** [comment]
@3xploiton3 Please report to https://github.com/easylist/easylist/issues
