### ISSUE TITLE
moviekhhd.biz: ads

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25775]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://moviekhhd.biz/`

### Category

ads

### Description

Banner ads, poster ads, video ads, at every page.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 925264
 cosmetic: 219005
 scriptlet: 38148
 html: 2322
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl: 136233-0, 1m
  https://divested.dev/blocklists/Fingerprinting.ubl: 66-1, now
  https://divested.dev/hosts-domains-wildcards: 625257-58108, now
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1090-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 109812-279, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2683-2, 1m
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 451-36, now
  https://raw.githubusercontent.com/iam-py-test/my_filters_001/refs/heads/main/antitypo.txt: 2090-42, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4232-36, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, now
  curben-phishing: 565-20, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  ublock-filters: 41053-321, now
  ublock-badware: 11838-1456, now
  ublock-privacy: 1346-94, now
  ublock-unbreak: 2549-3, now
  ublock-quick-fixes: 185-12, 1m Δ
  adguard-mobile: 10009-867, now
  easylist: 80203-32230, now
  easyprivacy: 53181-37416, now
  urlhaus-1: 23630-302, now
  plowe-0: 3545-3093, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 813 ms (selfie)
 maxAssetCacheWait: 563 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  flagcounter.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  openmindedaching.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
moviekhhd.biz###Ads
moviekhhd.biz##a[alt="Sponsor Ads"]
||moviekhhd.biz/ads/
||moviekhhd.biz/images/DownloadAds
||drugstoredemuretake.com^
```

**Comment by Rachitidk** [comment]
![1000109801](https://github.com/user-attachments/assets/8ae047ba-32fe-4306-b473-8518e767f33e)


> Test
> 
> ```
> moviekhhd.biz###Ads
> moviekhhd.biz##a[alt="Sponsor Ads"]
> ||moviekhhd.biz/ads/
> ||moviekhhd.biz/images/DownloadAds
> ||drugstoredemuretake.com^
> ```

Many are still there

**Comment by stephenhawk8054** [comment]
The first red section is self-promotion. We don't fix that.

I can't reproduce the 2nd red section. Give exact link please.

**Comment by Rachitidk** [comment]
> The first red section is self-promotion. We don't fix that. You can use these as your custom filters
> 
> ```
> moviekhhd.biz##div5:has(a[alt="Buying Advertising Space"])
> moviekhhd.biz##.tooltip
> ```
> 
> I can't reproduce the 2nd red section. Give exact link please.

Ss from while ago but can't reproduce now, maybe got fixed.
https://github.com/user-attachments/assets/2429eba4-4c29-4e7e-87c7-bd571f5d997a
Can't the shelf promotion be added to annoyance?

**Comment by stephenhawk8054** [comment]
No, we don't fix self-promotion. You can report the other filters to EasyList

**Comment by Rachitidk** [comment]
First 

> > Test
> > ```
> > moviekhhd.biz###Ads
> > moviekhhd.biz##a[alt="Sponsor Ads"]
> > ||moviekhhd.biz/ads/
> > ||moviekhhd.biz/images/DownloadAds
> > ||drugstoredemuretake.com^
> > ```
> 
> Many are still there
Add this to the list then. 
Thanks

**Comment by Rachitidk** [comment]
Add the sponser filter to the ublock list.
