### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by Banjokeith** [uBlockOrigin/uAssets#25774]
### Prerequisites

- [ ] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.google.com/search?q=canva&rlz=1C1GCEA_enAU1133AU1133&oq=&gs_lcrp=EgZjaHJvbWUqCQgBEEUYOxjCAzIJCAAQRRg7GMIDMgkIARBFGDsYwgPSAQkxMjkxajBqMTWoAgKwAgE&sourceid=chrome&ie=UTF-8`

### Category

breakage

### Description

it will not let me in to google classroom and canva

### Other extensions used

grammarly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143954
 cosmetic: 48613
 scriptlet: 22865
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 40370-255, 6m Δ
  ublock-badware: 11842-6, 6m Δ
  ublock-privacy: 1359-22, 6m Δ
  ublock-unbreak: 2489-0, 26m
  ublock-quick-fixes: 186-0, 26m
  easylist: 80195-580, 6m Δ
  easyprivacy: 53181-649, 6m Δ
  urlhaus-1: 23915-0, 26m
  plowe-0: 3545-0, 26m
filterset (user): [array of 4 redacted]
trustedset:
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1787 ms
 maxAssetCacheWait: 348 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  google.com: 8
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by mapx-** [comment]
no issue on my end, I'm able to log in canva
