### ISSUE TITLE
elle.com: nuisance

### ISSUE THREAD

**Issue by 2024-09-12** [uBlockOrigin/uAssets#25777]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```
https://www.elle.com/uk/fashion/what-to-wear/g62681738/best-british-knitwear-brands/
```

### Description

Privacy overlay.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 239825
 cosmetic: 188585
 scriptlet: 50657
 html: 2307
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84878-4234, 3d.15h.3m
  adguard-spyware-url: 1753-127, 3d.15h.3m
  adguard-spyware: 93743-1534, 3d.15h.3m
  block-lan: 64-0, 7d.1h.32m
  adguard-cookies: 32202-62, 3d.15h.3m
  ublock-cookies-adguard: 1833-27, 5d.19h.2m
  adguard-social: 23065-50, 3d.15h.3m
  adguard-popup-overlays: 28042-2081, 3d.15h.3m
  adguard-mobile-app-banners: 5441-29, 3d.15h.3m
  adguard-other-annoyances: 14693-462, 3d.15h.3m
  adguard-widgets: 2716-19, 3d.15h.3m
  ublock-annoyances: 5910-212, now Δ
  [1 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 40638-131, now Δ
  ublock-badware: 11844-6, now Δ
  ublock-privacy: 1350-22, now Δ
  ublock-unbreak: 2547-1, now Δ
  ublock-quick-fixes: 182-8, now
  easylist: 80211-2144, now Δ
  easyprivacy: 53189-23803, now Δ
  urlhaus-1: 23915-0, 3d.15h.3m
  plowe-0: 3548-1097, 9d.17h.22m
filterset (user): [array of 16 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1311 ms
 maxAssetCacheWait: 964 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  adsafeprotected.com: 1
  adsrvr.org: 1
  amazon-adsystem.com: 1
  brandmetrics.com: 1
  doubleclick.net: 1
  ensighten.com: 1
  facebook.net: 1
  googletagmanager.com: 1
  instagram.com: 1
  onetrust.com: 2
  permutive.app: 1
  permutive.com: 1
  rlcdn.com: 1
  sail-horizon.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
  speedcurve.com: 1
  tru.am: 1
 extended:
  ##main > div[class^="css-"]:has(> .ad-disclaimer)
  ###gpt-leaderboard-ad
  ##.gpt-breaker-container
  ##.breaker-ad
  ##.ad-disclaimer
  ##.vertical-ad
  ##.right-rail-ad
  #@##onetrust-consent-sdk
  ##+js(set-constant, pianoOfferDisplayed, true)
  ##+js(remove-class, glimmer-sticky, .content-lede-video.glimmer-…
  ##body:style(overflow: visible!important;)
  ##[class]:style(-webkit-touch-callout: default !important; -webk…
  ##+js(json-prune, data.xdt_injected_story_units.ad_media_items)
  ##+js(trusted-set-cookie, ig_did, 0C826C21-17C3-444A-ABB7-EBABD3…
  ##+js(set-constant, _sharedData.is_whitelisted_crawl_bot, true)
  ##+js(set-session-storage-item, loggedOutAppSheetIsMinimized, 1)

```
</details>

**Comment by mapx-** [comment]
enable `EasyList/uBO – Cookie Notices`

if you want the filters in adguard cookies list report at adguard repository
