### ISSUE TITLE
uhdmovies.icu: popups

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#25787]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uhdmovies.icu/`

### Category

popups

### Description

Website has some kind of click event that tries to open up a pop-up site that is already blocked by Easilist (1winpost), as seen on the screenshot i shared.

Detected by the Pop-up Blocker strict extenstion, but if i disable it and try to open the website again in a new Private Window, the pop-up is still triggered to the blocked page i mentioned.

Tried several scripts to remove whatever is in the script that keeps calling this invisible click thing, but nothing has really fixed it yet

### Other extensions used

TWP Pages translate
Pop-up Blocker Strict

### Screenshot(s)

![image](https://github.com/user-attachments/assets/6b9c6c2d-5b7c-4240-92fb-441e48cf93e7)

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 143171
 cosmetic: 50228
 scriptlet: 25027
 html: 2333
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5910-34, 1h.22m
 default:
  user-filters: 149-2, never
  ublock-filters: 40660-135, 1h.22m
  ublock-badware: 11578-6, 1h.22m
  ublock-privacy: 1356-22, 1h.22m
  ublock-unbreak: 2549-1, 1h.22m
  easylist: 80274-187, 1h.22m
  easyprivacy: 53189-63, 1h.22m
  urlhaus-1: 22965-0, 1h.22m
  plowe-0: 3545-999, 1h.22m
  ublock-quick-fixes: 186-11, 1h.23m
filterset (user): [array of 97 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 134 redacted]
hostRuleset:
 added: [array of 488 redacted]
urlRuleset:
 added: [array of 104 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 279 ms (selfie)
 maxAssetCacheWait: 94 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  aj2627.bid: 3
  cloudflareinsights.com: 2
  google.com: 2
  googletagmanager.com: 1
  raglanyakking.com: 2
 extended:
  ##.gridlove-ad
  ##+js(no-window-open-if)
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by Alphamen16** [comment]
Seems to not be happening anymore, i think maybe sometimes Pop-up Blocker Strict picks up stuff that UBO has already taken care of for some reason?

Could also be a timed response and if i leave the page open for a while longer something will trigger, but for now it's not trying to open any links so i suspect it might've been the extension identifying something even though UBO has it fixed.

Weird if so but not impossible

**Comment by stephenhawk8054** [comment]
uBO proxies browser's `open` method to prevent opening popups:

https://github.com/uBlockOrigin/uAssets/blob/33d2b869282ff1d07d91d680cea84aa18de5460f/filters/filters-2024.txt#L2470

Any other extensions that do the same will interfere with uBO, for example popup blocker extensions. Therefore, please respect the prerequisites:

> - [X] I am not using uBlock Origin along with other content blockers.

**Comment by Alphamen16** [comment]
@stephenhawk8054 You're right, i ment that i had tried both with AND without the extension open, but not before i had created a new profile to test like you said. In that sense, i didn't try all avenues before posting this here so apologies

Anyway i do see the fix you applied as well and it makes sense, i didn't find it in the code when i looked at it for the first time.

To confirm though, the nowoif scriplet you mentioned does achieve the desired affect of no pop-up activating, but it does not fix the core issue if there's something in the code programmed to pop-up right? Meaning that it just prevents it from happening but does not remove the trigger, that requires something else

**Comment by stephenhawk8054** [comment]
It comes from this script, and I have added another filter to block it: https://github.com/uBlockOrigin/uAssets/commit/33d2b869282ff1d07d91d680cea84aa18de5460f
