### ISSUE TITLE
motorbikecatalog.com: ads

### ISSUE THREAD

**Issue by failedthetutorial** [uBlockOrigin/uAssets#25785]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.motorbikecatalog.com/moto/2004/25535/aprilia_rs_125.html`

### Category

ads

### Description

Adds showing up, whenever i manually block one it pops rigth back in about 3 seconds
I do not know what defines a site issue

### Other extensions used

Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 143635
 cosmetic: 48616
 scriptlet: 21235
 html: 2043
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 40642-131, 1h.19m Δ
  ublock-badware: 11577-6, 1h.19m Δ
  ublock-privacy: 1353-22, 1h.19m Δ
  ublock-unbreak: 2547-1, 1h.19m Δ
  ublock-quick-fixes: 186-8, 1h.19m Δ
  easylist: 80247-189, 1h.19m Δ
  easyprivacy: 53189-64, 1h.19m Δ
  urlhaus-1: 23800-0, now
  plowe-0: 3545-999, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5615 ms (selfie)
 maxAssetCacheWait: 3716 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  content-loader.com: 2
  criteo.net: 1
  duckduckgo.com: 3
  google.com: 3
  googlesyndication.com: 8
  googletagmanager.com: 2
  html-load.com: 2
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054 do you know why HTML filtering doesn’t work here anymore? I remember there was a issue but i don’t know where. I checked the character encoding with `document.characterSet` already but its fine `UTF-8`.

**Comment by stephenhawk8054** [comment]
Hmm... I'm not really sure. The site's source code use capital letters for tag names. Not sure if it's related.

@gorhill Sorry, can you check this?

**Comment by gorhill** [comment]
The charset of the page is `iso-8859-2`, not supported by response filtering code.

**Comment by JobcenterTycoon** [comment]
Ok now i know how to get: `Content-Type: text/html; charset=iso-8859-2` from the answer header of the HTML request.

**Comment by JobcenterTycoon** [comment]
I did exacly this https://github.com/uBlockOrigin/uAssets/issues/25785#issuecomment-2436494050 but it throws `UTF-8`

**Comment by JobcenterTycoon** [comment]
Sorry my error, `document.characterSet` works fine on my uBlock Origin firefox dev browser.
