### ISSUE TITLE
gaiagps.com: breakage

### ISSUE THREAD

**Issue by DieselDrax** [uBlockOrigin/uAssets#25791]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gaiagps.com/map/`

### Category

breakage

### Description

GaiaGPS (https://www.gaiagps.com/map) appears to be routing traffic through Amplitude.com APIs / AVMWS CDNs which are being blocked.  Disabling uBLock allows the site to load properly.

### Other extensions used

FB Purity

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-10-25 103135](https://github.com/user-attachments/assets/40f67edd-5625-4fb3-82a2-c31efc135671)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143147
 cosmetic: 48630
 scriptlet: 22880
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80274-472, 22m Δ
  easyprivacy: 53189-630, 22m Δ
  plowe-0: 3542-0, now
  ublock-badware: 11576-6, 22m Δ
  ublock-filters: 40401-369, 22m Δ
  ublock-privacy: 1370-22, 22m Δ
  ublock-quick-fixes: 188-0, 22m Δ
  ublock-unbreak: 2491-19, 22m Δ
  urlhaus-1: 23285-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1402 ms (selfie)
 maxAssetCacheWait: 1116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  amplitude.com: 17
  appsflyer.com: 1
  avmws.com: 1
  googletagmanager.com: 1
  sentry.io: 3
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, disable any other extension, disable tracking prevention in edge, test again

**Comment by DieselDrax** [comment]
> reset uBO to defaults, disable any other extension, disable tracking prevention in edge, test again

After resetting to defaults uBO is completely broken.  I've also removed and re-installed the extension, fully quit Edge, disabled all other extensions.  I can't even get to uBO settings now, I just get a blank page.  This is the error I'm getting now.

![Screenshot 2024-10-25 110128](https://github.com/user-attachments/assets/466372af-52ed-46db-a622-0dd2ed579421)

**Comment by DieselDrax** [comment]
I've also confirmed the same behavior in Chrome.

**Comment by mapx-** [comment]
From which country are you accessing the site?

**Comment by mapx-** [comment]
mmhmm, I get a breakage only using an account

test

`@@||api.lab.amplitude.com/v1/vardata$xhr,domain=gaiagps.com`

**Comment by DieselDrax** [comment]
> mmhmm, I get a breakage only using an account
> 
> test
> 
> `@@||api.lab.amplitude.com/v1/vardata$xhr,domain=gaiagps.com`

Added to "My Filters" and now the map loads with uBO enabled.
