### ISSUE TITLE
cliente.meo.pt: breakage

### ISSUE THREAD

**Issue by cereais** [uBlockOrigin/uAssets#25799]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cliente.meo.pt/perfil/mensagens/abrir-pedido`

### Category

breakage

### Description

I noticed a while ago that some important functionality under the create request ("Criar pedido") page on cliente.meo.pt stopped working, showing a blank page instead. This mainly includes the official form to cancel the contract ("Cancelar contrato"), but also seems to affect some, other less important contact forms. You need to be a customer and use the client area in order to experience this.

At first I thought this was a temporary website issue, but later after experimenting I figured it out it was due to EasyPrivacy indiscriminate blocking of `webcare.byside.com`. I have also seen at least an user on a Portuguese forum complaining about this issue, not knowing it is due to EasyPrivacy.

I have reported this to EasyList via their official email and their GitHub issue tracker https://github.com/easylist/easylist/issues/20181 but after weeks received no response.

I fixed this by including the following in my filters:
`@@||webcare.byside.com$domain=cliente.meo.pt|my.uzo.pt|my.moche.pt`
I ask for this to be added to the uBlock filters - Unbreak list (or Quick fixes). I understand you may be hesitant to do this given EasyPrivacy and uBlock Origin goals, however I believe this is an acceptable tradeoff since only the client area is listed and being a paying customer is required to use the form.

I also included the client areas of the other ISP brands (UZO, MOCHE) owned by MEO (Altice Portugal). I am not able to test if they are also affected by this issue, but given they are the same company (and use the same SSO), it's very likely. You can ignore `my.uzo.pt` and `my.moche.pt` from the domains if this is reasoning is not enough.

For the record, initially I tried to only unblock a single file with:
`@@||webcare.byside.com/agent/byside_webcare.js$script,domain=cliente.meo.pt`
This seems to partially fix the issue but, for some reason, this resulted in worst problems, like not being able to pay the bill using a local payment processor.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Here is what it looks like:
![image](https://github.com/user-attachments/assets/95478132-8d65-4339-adda-8f2f98f0cefe)
Here is what it should look like:
![meo](https://github.com/user-attachments/assets/4edc92fa-d477-42d4-9dcd-acb12a4cc114)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 142631
 cosmetic: 48667
 scriptlet: 21234
 html: 2043
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40694-135, 4m
  ublock-badware: 11584-6, 4m
  ublock-privacy: 1356-22, 5m
  ublock-unbreak: 2549-1, 5m
  ublock-quick-fixes: 206-8, 5m
  easylist: 80285-195, 5m
  easyprivacy: 53192-64, 5m
  urlhaus-1: 22735-0, 5m
  plowe-0: 3545-999, never
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 353 ms (selfie)
 maxAssetCacheWait: 133 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  byside.com: 3
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Do you have a working filter?
