### ISSUE TITLE
w.dyxs.sbs: nuisance

### ISSUE THREAD

**Issue by linmaaam** [uBlockOrigin/uAssets#25796]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://w.dyxs.sbs/paly-275720-4-1/`

### Category

nuisance

### Description

Media playback webpage pop-up cannot be blocked

### Other extensions used

[unknown]

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 131
filterset (summary):
 network: 157119
 cosmetic: 59570
 scriptlet: 23145
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  CHN-0: 25499-40, now
  easylist: 80282-616, 50m Δ
  easyprivacy: 53190-662, 50m Δ
  plowe-0: 3542-2, now
  ublock-badware: 11582-6, 50m Δ
  ublock-filters: 40427-279, 50m Δ
  ublock-privacy: 1370-22, 50m Δ
  ublock-quick-fixes: 199-0, 50m Δ
  ublock-unbreak: 2491-1, 50m Δ
  urlhaus-1: 23020-0, 1h.50m
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 231 ms (selfie)
 maxAssetCacheWait: 39 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  baidu.com: 1
  clarity.ms: 1
  google-analytics.com: 1
  googletagmanager.com: 1
 extended:
  ##.player-rm > a[target="_blank"]
  ##.player-rm-float
  ###dy_card_dy
  ###mui-player + #player_pic
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `##.player-rm > a[target="_blank"]`.

@cjx82630 Sorry, can you check this?

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/873cc20a7dea2c76a291e495522302725a0db6e3
