### ISSUE TITLE
japscan.lol: detection

### ISSUE THREAD

**Issue by Dorgam796** [uBlockOrigin/uAssets#25798]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.japscan.lol/`

### Category

detection

### Description

detect adblock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 161237
 cosmetic: 55289
 scriptlet: 21426
 html: 2043
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40692-135, 1h.40m
  ublock-badware: 11584-6, 1h.40m
  ublock-privacy: 1356-22, 1h.40m
  ublock-unbreak: 2549-1, 1h.40m
  ublock-quick-fixes: 208-8, 29m
  easylist: 80282-195, 1h.40m
  easyprivacy: 53190-64, 1h.40m
  urlhaus-1: 23020-0, 1h.40m
  plowe-0: 3542-998, 1h.40m
  FRA-0: 25618-393, 1h.40m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 466 ms (selfie)
 maxAssetCacheWait: 98 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  bowermisrule.com: 1
  cloudflareinsights.com: 1
 extended:
  ##body > .container.text-center > .mb-2.mt-2[style="margin: 0px …
  ##body > .container.text-center > div.mt-3[style="margin: 0px au…
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(no-setTimeout-if, detectImgLoad)
  ##+js(abort-on-stack-trace, onload, inlineScript)
  ##+js(addEventListener-defuser, load, setTimeout)
  ##+js(no-setTimeout-if, getElementById)
  ##+js(addEventListener-defuser, DOMContentLoaded, HoLi)
  ##+js(remove-node-text, script, /\}\);\}\}\}\(\)\)\)\);|\]\(\)\)…
  ##+js(addEventListener-defuser, DOMContentLoaded, HoLa)
  ##+js(no-setTimeout-if, sessionStorage)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

> - [X] I did not answer truthfully to **ALL** the above checkboxes.
