### ISSUE TITLE
[nsfw] wan.xingga.com: ads

### ISSUE THREAD

**Issue by laoyang100** [uBlockOrigin/uAssets#25795]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wan.xingga.com/tg/grYJO3?showid=Ee0Vh0SfGH5H`

### Category

ads

### Description

it is the game web

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 157090
 cosmetic: 59569
 scriptlet: 23145
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  CHN-0: 25470-40, now
  easylist: 80282-508, now
  easyprivacy: 53190-662, now
  plowe-0: 3542-2, now
  ublock-badware: 11582-6, now
  ublock-filters: 40428-387, now
  ublock-privacy: 1370-22, now
  ublock-quick-fixes: 199-0, now
  ublock-unbreak: 2491-1, now
  urlhaus-1: 23020-0, never
filterset (user): [array of 1 redacted]
trustedset:
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 194 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you check this?

**Comment by cjx82630** [comment]
If popup Ads,return to original page and report.
