### ISSUE TITLE
pastpapers.co: ads

### ISSUE THREAD

**Issue by Sadia2000** [uBlockOrigin/uAssets#25805]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pastpapers.co/`

### Category

ads

### Description

PapaCambridge's ads visible at the bottom of the page.

### Other extensions used

enhanced-h264ify

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/c6e23fc1-98ff-4108-9ab8-9bb2df9a651e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 115
filterset (summary):
 network: 143148
 cosmetic: 48669
 scriptlet: 21236
 html: 2043
listset (total-discarded, last-updated):
 added:
  curben-phishing: 517-0, 26m
 default:
  user-filters: 2-0, never
  ublock-filters: 40694-135, 51m Δ
  ublock-badware: 11585-6, 51m Δ
  ublock-privacy: 1356-22, 51m Δ
  ublock-unbreak: 2549-1, 51m Δ
  ublock-quick-fixes: 209-8, 51m Δ
  easylist: 80285-195, 51m Δ
  easyprivacy: 53192-64, 51m Δ
  urlhaus-1: 22735-0, 26m
  plowe-0: 3542-998, 26m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4187 ms
 maxAssetCacheWait: 959 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 no-cosmetic-filtering: true
 no-large-media: true
 network:
  googletagmanager.com: 1
```
</details>

**Comment by gorhill** [comment]
> `no-cosmetic-filtering: true`

Don't disable cosmetic filtering -- it's enabled by default, you disabled it, and this is the consequence.

> - [x]  I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

You didn't answer truthfully, please do so next time to prevent burdening volunteers with invalid reports.
