### ISSUE TITLE
gecmisi.com.tr: detection

### ISSUE THREAD

**Issue by hurgir** [uBlockOrigin/uAssets#25803]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://gecmisi.com.tr/`

### Category

detection

### Description

site detects ad blocker when ublock origin is on.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/3f958495-0d60-41e6-8f35-ae65d1cd5be9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 243986
 cosmetic: 192892
 scriptlet: 53281
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2691-0, 6m
  adguard-cookies: 32257-80, 6m
  adguard-generic: 85291-7360, 6m
  adguard-mobile-app-banners: 5516-15, 6m
  adguard-other-annoyances: 14719-67, 6m
  adguard-popup-overlays: 27896-1188, 6m
  adguard-social: 23088-148, 6m
  adguard-spyware: 98024-24409, 6m
  adguard-widgets: 2732-2, 6m
  block-lan: 64-0, 6m
  ublock-annoyances: 5969-17, 6m Δ
  ublock-cookies-adguard: 1854-9, 6m
 default:
  user-filters: 23-0, never
  TUR-0: 10738-13, 6m
  easylist: 80282-659, 6m Δ
  easyprivacy: 53192-1552, 6m Δ
  plowe-0: 3548-0, never
  ublock-badware: 11582-6, 6m Δ
  ublock-filters: 40434-606, 6m Δ
  ublock-privacy: 1370-71, 6m Δ
  ublock-quick-fixes: 207-0, 6m Δ
  ublock-unbreak: 2491-4, 6m Δ
  urlhaus-1: 22735-0, 6m
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 774 ms
 maxAssetCacheWait: 373 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  yandex.ru: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(trusted-set-cookie, _ga, GA1.1.1908932164.2839771695)
  ##+js(no-setInterval-if, showAdBlockMessage)
  ##+js(no-setTimeout-if, /adElement\.innerHTML|=document\[_0x/)
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue in the old thread: https://github.com/uBlockOrigin/uAssets/issues/25421
