### ISSUE TITLE
hdfilmcehennemi1.net: ads

### ISSUE THREAD

**Issue by leysivle** [uBlockOrigin/uAssets#25806]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hdfilmcehennemi1.net/blink-twice-1/`

### Category

ads

### Description

Page shows advertisements

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 144058
 cosmetic: 56784
 scriptlet: 24030
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 10738-10, now
  easylist: 80315-484, 36m Δ
  easyprivacy: 53198-654, 36m Δ
  plowe-0: 3542-1, now
  ublock-badware: 11571-6, 36m Δ
  ublock-filters: 40426-379, 36m Δ
  ublock-privacy: 1346-22, 36m Δ
  ublock-quick-fixes: 210-0, 36m Δ
  ublock-unbreak: 2491-3, 36m Δ
  urlhaus-1: 22735-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5677 ms (selfie)
 maxAssetCacheWait: 329 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  adbetnetwork.com: 1
  aj2550.bid: 1
  googletagmanager.com: 1
  heimalesssinpad.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||hdfilmcehennemi1.net/rekla/$media
hdfilmcehennemi1.net##.money-child
hdfilmcehennemi1.net##.money-text
```

@Alex-302
