### ISSUE TITLE
vijesti.hrt.hr: breakage

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25804]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vijesti.hrt.hr/gospodarstvo/potrosacki-kod-92-11828389`

### Category

breakage

### Description

Cookie prompt is blocked, and because of that embedded videos aren't shown. When you disable uBlock Origin, it shows the embedded video, but asks for your permission to play it.

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlock Origin enabled:
![Screenshot_1](https://github.com/user-attachments/assets/bc53edf4-337a-4cac-b501-ce6ad344ef4b)

With uBlock Origin disabled:
![Screenshot_2](https://github.com/user-attachments/assets/082813b0-268c-474e-a4f1-6c125a52288f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 275481
 cosmetic: 254571
 scriptlet: 55043
 html: 2307
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-81, now
  adguard-generic: 85291-8287, now
  adguard-spyware-url: 1764-128, now
  adguard-spyware: 98024-19861, now
  curben-phishing: 517-0, now
  adguard-cookies: 32257-95, now
  ublock-cookies-adguard: 1854-27, now
  fanboy-cookiemonster: 52335-4107, now
  ublock-cookies-easylist: 1854-1854, now
  adguard-social: 23088-52, now
  fanboy-social: 16739-763, now
  adguard-popup-overlays: 27896-2190, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  ublock-filters: 40694-135, now
  ublock-badware: 11585-77, now
  ublock-privacy: 1356-35, now
  ublock-unbreak: 2549-2, now
  ublock-quick-fixes: 209-8, 15m Δ
  easylist: 80313-20800, now
  easyprivacy: 53192-40211, now
  urlhaus-1: 22735-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 209 ms (selfie)
 maxAssetCacheWait: 138 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  consentmanager.net: 1
  doubleclick.net: 1
  gemius.pl: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  ipromcloud.com: 1
  thenewsbox.net: 1
  upscore.com: 1
 extended:
  ##.iAdserver
  ##.mt-4 > .hidden > .h-screen:has(> a[title="E-mail"])
  ##.h-screen
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce, even after enabling stock lists related to cookies, annoyances. You have too many lists, investigate on your side which list is causing your issue.

Mind what is asked from you:

- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

**Comment by mapx-** [comment]
cname issue:

@Marko-98 add

`@@||delivery.consentmanager.net^$script,domain=vijesti.hrt.hr`

**Comment by Marko-98** [comment]
Videos on the website refuse to play until cookies are accepted. To see videos you may need Croatian IP address.

URL: https://www.hrt.hr/

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/10217f54-c673-40e0-a40c-b226c6f21cc2

</details>

<details>

```yaml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 192631
 cosmetic: 166533
 scriptlet: 65592
 html: 3875
listset (total-discarded, last-updated):
 added:
  adguard-generic: 96432-5815, 1h.49m
  adguard-spyware-url: 2534-134, 1h.49m
  block-lan: 91-0, 1h.49m
  fanboy-cookiemonster: 46881-121, 1h.49m
  ublock-cookies-easylist: 5694-46, 1h.49m
  fanboy-social: 17701-16, 1h.49m
  easylist-annoyances: 5220-64, 1h.49m
  fanboy-ai-suggestions: 254-0, 1h.49m
  easylist-newsletters: 9342-38, 1h.49m
  easylist-notifications: 2509-177, 1h.49m
  ublock-annoyances: 4934-103, 1h.49m
  HRV-0: 527-110, 1h.49m
 default:
  user-filters: 3-0, never
  ublock-filters: 52183-68, 1h.48m
  ublock-badware: 10362-28, 1h.48m
  ublock-privacy: 4032-2, 1h.48m
  ublock-unbreak: 2831-1, 1h.49m
  ublock-quick-fixes: 448-12, 1h.49m
  easylist: 89813-1226, 1h.49m
  easyprivacy: 55843-125, 1h.49m
  urlhaus-1: 26910-11, 1h.49m
  plowe-0: 3505-1039, 1h.49m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 108 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  hrt.hr: 1
  dotmetrics.net: 1
  gemius.pl: 2
  google.com: 1
  google.hr: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  thenewsbox.net: 1
  upscore.com: 4
  wtg-ads.com: 2
```
</details>

**Comment by gorhill** [comment]
Doesn't this also happen without uBO installed?

**Comment by Marko-98** [comment]
@gorhill It does, as long as cookies aren't accepted. More specifically, until `Ostalo` isn't accepted.

<details>
<summary>Screenshot</summary>

<img width="1073" height="1084" alt="Image" src="https://github.com/user-attachments/assets/fe9ed53d-7fd2-4f95-afce-368a75627c07" />
</details>

I presume uBO just hides the pop-up using cosmetic filtering, doesn't alter the cookies for `hrt.hr`. Right? 
Would it be possible for uBO to select `Ostalo` and accept cookie? That would prevent broken video playback.

**Comment by gorhill** [comment]
If this also happens without uBO, then this isn't breakage issue to be fixed? I don't see uBO filtering out that cookie notice on that site, most likely because the choice to break the site or not is left to the user.

**Comment by Marko-98** [comment]
I mean... uBO does remove cookie notice though EasyList Cookie filter. I think it would be a good idea to use scriptlet to set cookie, so user doesn't have to interact with the notice, considering notice is already blocked. uBlock Cookie filter already does this for a lot of websites though.

**Comment by Marko-98** [comment]
@stephenhawk8054 Thanks! This solution works great. But I do have a question; is it possible for scriptlet to select just certain cookies and not all of them? 

Accepting all of them also means accepting marketing and tracking ones when in fact just `Funkcionalnost`, `Društvene mreže` and `Ostalo` is enough for website to work correctly.
