### ISSUE TITLE
[nsfw] roblox.qq.com: badware

### ISSUE THREAD

**Issue by CouldBear** [uBlockOrigin/uAssets#25808]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://roblox.qq.com/`

### Category

badware

### Description

i mean this website let cn players cant open the roblox website

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 157009
 cosmetic: 59569
 scriptlet: 23159
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 25480-40, now
  easylist: 80315-508, 25m Δ
  easyprivacy: 53198-662, 25m Δ
  plowe-0: 3542-2, now
  ublock-badware: 11583-6, 25m Δ
  ublock-filters: 40434-387, 25m Δ
  ublock-privacy: 1370-22, 25m Δ
  ublock-quick-fixes: 210-0, 25m Δ
  ublock-unbreak: 2491-1, 25m Δ
  urlhaus-1: 22885-0, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 471 ms (selfie)
 maxAssetCacheWait: 84 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  qq.com: 9
  gtimg.cn: 2
 extended:
  ##+js(json-prune, ad)
```
</details>

**Comment by stephenhawk8054** [comment]
I don't understand.

**Comment by mapx-** [comment]
@CouldBear report here: https://github.com/cjx82630/cjxlist/issues

providing all the info to reproduce your issue
