### ISSUE TITLE
[nsfw] mail.yandex.ru: ads

### ISSUE THREAD

**Issue by MRX9420** [uBlockOrigin/uAssets#25810]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mail.yandex.ru/`

### Category

ads

### Description

очень часто не удаляет рекламу

### Other extensions used

![{BDAC7A80-F4AF-44F8-A745-4E33E85B2067}](https://github.com/user-attachments/assets/139e918f-fb20-46a5-b862-25c1de7b8bbe)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 161471
 cosmetic: 69326
 scriptlet: 24422
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-2, never
  ublock-filters: 40442-286, 1h.39m Δ
  ublock-badware: 11583-6, 1h.39m Δ
  ublock-privacy: 1370-22, 1h.39m Δ
  ublock-unbreak: 2491-0, 1h.39m Δ
  ublock-quick-fixes: 210-0, 1h.39m Δ
  easylist: 80316-608, 1h.39m Δ
  easyprivacy: 53198-649, 1h.39m Δ
  urlhaus-1: 22885-0, now
  plowe-0: 3542-0, now
  RUS-0: 40984-101, 1h.39m Δ
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 612 ms (selfie)
 maxAssetCacheWait: 80 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 393
 no-cosmetic-filtering: true
 network:
  yandex.ru: 393
 extended:
  ##.ns-view-id-47.ns-view-zkcdjppyy-box
  ##.js-fill-height-placeholder.mail-FillHeightPlaceholder.ns-view…
  ##div.sni7ID3nDbWI:nth-of-type(1)
```
</details>

**Comment by mapx-** [comment]
- go to https://github.com/easylist/ruadlist/wiki/RU-Adlist-links
- subscribe RU AdList: Counters list

If you have other issues with that site report here: https://github.com/easylist/ruadlist/issues
