### ISSUE TITLE
aternos.org: ads

### ISSUE THREAD

**Issue by Inkytube** [uBlockOrigin/uAssets#25815]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aternos.org/`

### Category

ads

### Description

![Screenshot 2024-10-27 133234](https://github.com/user-attachments/assets/39472a0d-a6d0-4ead-a750-75676d1c3c12)
the site detects Ublock origin and also shows ads even if I activated Ublock origin

### Other extensions used

ClearURLs and BTRoblox - Making Roblox Better
![Screenshot 2024-10-27 133439](https://github.com/user-attachments/assets/cc01cecd-b0db-46b7-81e3-9a9b69824448)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 132556
 cosmetic: 37259
 scriptlet: 1272
 html: 117
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: never
  ublock-badware: 11173-6, never
  ublock-privacy: 1264-22, never
  ublock-unbreak: 2538-0, never
  ublock-quick-fixes: 133-0, never
  easylist: 85550-474, never
  easyprivacy: 53091-647, never
  urlhaus-1: 15052-0, never
  plowe-0: 3553-0, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14549 ms
 maxAssetCacheWait: 111 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
duplicate, continue here: https://github.com/uBlockOrigin/uAssets/issues/13144
