### ISSUE TITLE
[nsfw] xfreehd.com: breakage

### ISSUE THREAD

**Issue by miltonjsvidal** [uBlockOrigin/uAssets#25817]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.xfreehd.com/video/747023/argentina-casting-steff`

### Category

breakage

### Description

When I try to enter the page, the website show me this massage 

### Other extensions used

ClearURL
Canvas Blocker
Todavia no mr importa los cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241027-115453_Iceraven](https://github.com/user-attachments/assets/d5c7fb41-cdfe-4f14-8897-ad601db4d701)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 309222
 cosmetic: 210358
 scriptlet: 52190
 html: 2312
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2686-0, 3m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 86774-0, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1200-3, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/privacy_essentials.txt: 890-25, now
  adguard-generic: 85264-5759, now
  adguard-spyware-url: 1764-245, now
  adguard-spyware: 98024-8327, now
  curben-phishing: 516-1, now
  adguard-cookies: 32257-87, now
  fanboy-cookiemonster: 52340-4044, now
  ublock-cookies-easylist: 1894-43, now
  fanboy-social: 16750-18, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 41220-296, 3m Δ
  ublock-badware: 11579-551, 3m Δ
  ublock-privacy: 1357-90, 3m Δ
  ublock-unbreak: 2551-7, 3m Δ
  ublock-quick-fixes: 209-10, 3m Δ
  adguard-mobile: 9928-616, now
  easylist: 80316-24140, 3m Δ
  easyprivacy: 53198-27030, 3m Δ
  urlhaus-1: 23055-1, now
  spa-0: 4098-58, now
  spa-1: 6072-284, now
filterset (user): [array of 2 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3724 ms
 maxAssetCacheWait: 2498 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  googletagmanager.com: 1
  magsrv.com: 5
  pemsrv.com: 1
 extended:
  ##.ad-body:remove()
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(prevent-fetch, ads.exosrv.com)
  ##+js(abort-current-script, $, abk_vmsg)
  ##+js(abort-on-stack-trace, String.fromCharCode, HTMLScriptEleme…
  ##+js(abort-on-property-write, axtest01)
  ##+js(abort-current-script, setTimeout, .ad)
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in your old thread. All volunteers are notified with new comments. No need to open duplicated issues.

**Comment by M1nnesota** [comment]
> Just continue in your old thread. All volunteers are notified with new comments. No need to open duplicated issues.

Actually this is a new problem that appeared today. I am facing the same problem right now, I just don't want to make duplicates.
