### ISSUE TITLE
microsoft.com : Breakage

### ISSUE THREAD

**Issue by ThowZzy** [uBlockOrigin/uAssets#25827]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.microsoft.com/fr-fr/software-download/windows11
```

### Description

When trying to download the Windows 11 ISO (not the installation tool), after selecting the language, I get an error and can't download it. It is fixed if I disable ublock.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/13f553a3-478b-493d-8546-f0b7194a2e2a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 162514
 cosmetic: 55302
 scriptlet: 21443
 html: 2045
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 40722-136, 2h.38m Δ
  ublock-badware: 11585-6, 2h.38m Δ
  ublock-privacy: 1356-22, 2h.38m Δ
  ublock-unbreak: 2549-0, 2h.38m Δ
  ublock-quick-fixes: 218-10, 2h.38m Δ
  easylist: 80328-195, 2h.38m Δ
  easyprivacy: 53198-64, 2h.38m Δ
  urlhaus-1: 24230-0, 5h.38m
  plowe-0: 3542-998, 5h.38m
  FRA-0: 25623-394, 5h.38m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 487 ms (selfie)
 maxAssetCacheWait: 97 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  microsoft.com: 8
  msecnd.net: 1
  online-metrix.net: 1
```
</details>

**Comment by ThowZzy** [comment]
> Test again in a new Firefox profile with only uBO and its default settings.

Same outcome

**Comment by mapx-** [comment]
I get the error even disabling uBO

**Comment by ThowZzy** [comment]
Yeah just tested more and it may not be related to ublock, I may have had luck downloading the ISO after disabling uBlock but I can't reproduce reliably

**Comment by ThowZzy** [comment]
Microsoft side
