### ISSUE TITLE
uii.io [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2582]
URL(s) where the issue occurs

`http://uii.io/1kVpUm`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.8

Settings

Default

**Comment by KiLL4FuNK** [comment]
Pop-up

fill captcha

**Comment by dumbusernameidk** [comment]
@mapx- 

site has been renamed to `http://szs.pw` test link still works.

**Comment by lain566** [comment]
Anti adblock
`http://szs.pw/spY8q`

**Comment by lain566** [comment]
Popup when clicked on anywhere

**Comment by dumbusernameidk** [comment]
fake push notification new test link:

`http://uii.io/E9Ipp6`

**Comment by dumbusernameidk** [comment]
@okiehsch 
popup when clicking anywhere on `uii.io` the script responsible is `https://uii.io/js/health.js`

**Comment by lain566** [comment]
Infinite loop, does not load the web page.
`http://uii.io/E9Ipp6`

**Comment by okiehsch** [comment]
I can only reproduce with Chromium/Chrome the cloudflare check works fine with Firefox. on my end.
