### ISSUE TITLE
nsw2u.com: breakage

### ISSUE THREAD

**Issue by DuaneAbrames** [uBlockOrigin/uAssets#25823]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nsw2u.com/`

### Category

nuisance

### Description

Starting today when visiting the site, all of the images on the front page (game covers) are missing with uBlock on.  If I turn uBlock off, they reappear.  In troubleshooting, I turned off filter lists until I isolated the issue to the uBlock - ads filter list.  The site runs some anti-adblock code, and we have been dodging around that for the last month or so, and I assume that the site has made another change intended to mess with uBlock users.  Usually we can use the element picker to select the whole-page overlay which takes you off into some junk site, but that also does not seem to work now.  When attempting to pick an overlay on the site, either the site gets my click and opens the junk site, or the picker just finds "##.site" which of course would block everything.

### Other extensions used

Keeper Password Manager
Free Download Manager
Easy YouTube downloader
RecipeSage 
VideoDownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/user-attachments/assets/fb57c51c-c735-41ca-b53e-3052f589cb1a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 144311
 cosmetic: 48717
 scriptlet: 21272
 html: 2046
listset (total-discarded, last-updated):
 default:
  user-filters: 202-3, never
  ublock-filters: 40717-135, 1m
  ublock-badware: 11585-6, 1m
  ublock-privacy: 1356-22, 1m
  ublock-unbreak: 2549-1, 1m
  ublock-quick-fixes: 213-9, 1m
  easylist: 80328-195, 1m
  easyprivacy: 53198-64, 1m
  urlhaus-1: 24230-0, 6m
  plowe-0: 3542-998, 1m
filterset (user): [array of 105 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 139 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.code-block
  ##[href^="https://bit.ly/"]
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, eval, replace)
  ##+js(no-xhr-if, googlesyndication)
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/25434
