### ISSUE TITLE
moviedokan.fun: ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#25825]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://moviedokan.fun/movies/martin-2024/`

### Category

ads

### Description

banner ads & ad popups

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 133
filterset (summary):
 network: 145613
 cosmetic: 57374
 scriptlet: 21329
 html: 2051
listset (total-discarded, last-updated):
 default:
  user-filters: 14-2, never
  ublock-filters: 41247-136, now
  ublock-badware: 11579-6, now
  ublock-privacy: 1357-22, now
  ublock-unbreak: 2551-1, now
  ublock-quick-fixes: 220-10, now
  adguard-mobile: 9929-97, now
  easylist: 80328-268, now
  easyprivacy: 53198-73, now
  urlhaus-1: 24230-0, now
  plowe-0: 3542-1072, now
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 785 ms (selfie)
 maxAssetCacheWait: 232 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  onesignal.com: 1
 extended:
  ##.module_single_ads
```
</details>

**Notes**
```
moviedokan.*##+js(nowoif)
||moviedokan.*/wp-content/plugins/popup-builder/public/js/Popup.js
||jayabaji3.com/bn-bd?aff=$doc
moviedokan.*##.resp
moviedokan.*##.resps
||unequaledchair.com^
||lnk2.cfd^
xcloud.*##.ads-btns
```

**Comment by stephenhawk8054** [comment]
Looks like `moviedokan.*##+js(nowoif)` can affect share buttons popup. I'll adjust to `moviedokan.*##+js(acs, document.addEventListener, popunder)`, is it good?

**Comment by stephenhawk8054** [comment]
Yeah, that could work
