### ISSUE TITLE
channel4.com: ads

### ISSUE THREAD

**Issue by shmall03** [uBlockOrigin/uAssets#25829]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.channel4.com/programmes/the-good-doctor/on-demand/75163-013`

### Category

ads

### Description

New issue for me, as it has been fine in the past:
Channel 4 site showing unskippable ads before, during and between episodes. Using Arc on Windows, but as said, this has worked okay previously so I'm unsure what I can do about this.

### Other extensions used

SponsorBlock (Youtube)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143514
 cosmetic: 48690
 scriptlet: 22909
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80344-585, now Δ
  easyprivacy: 53198-649, now Δ
  plowe-0: 3542-0, now
  ublock-badware: 11583-6, now Δ
  ublock-filters: 40503-265, now Δ
  ublock-privacy: 1371-22, now Δ
  ublock-quick-fixes: 224-0, now Δ
  ublock-unbreak: 2491-0, now Δ
  urlhaus-1: 23525-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1058 ms (selfie)
 maxAssetCacheWait: 342 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 77
 network:
  channel4.com: 2
  2cnt.net: 1
  braze.eu: 3
  c4assets.com: 1
  conviva.com: 3
  demdex.net: 1
  fwmrm.net: 4
  optimizely.com: 61
  videologygroup.com: 1
 extended:
  ##+js(no-xhr-if, /\/ad\/g\/1/)
  ##+js(json-prune, adverts.breaks)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/24873
