### ISSUE TITLE
Hard anti-adblock on sltrib.com through Google cache

### ISSUE THREAD

**Issue by avengah** [uBlockOrigin/uAssets#2583]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://webcache.googleusercontent.com/search?q=cache:x_wn_O-bDeQJ:https://www.sltrib.com/opinion/letters/2018/03/11/letter-if-you-elect-a-clown-expect-a-circus/+&cd=4&hl=en&ct=clnk&gl=uk`

### Describe the issue

A big white box pops up, saying "To unlock, unblock". Sltrib is blocked in Europe so I can only view it through Google cache for now, so I don't know whether the actual website or just the Google cached version is affected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/285430/41500848-824d3946-7191-11e8-9d32-2287b38219ab.png)

### Versions

- Browser/version: Google Chrome is up to date
Version 67.0.3396.87 (Official Build) (64-bit)
- uBlock Origin version: Nano Adblocker 1.0.0.53, Nano Defender 14.55

### Settings

- Default

### Notes

None

**Comment by mapx-** [comment]
sltrib is already fixed i ublock filters
`@@||sltrib.com/*/scripts/utils/ads/ads.js$first-party,script`

so, for webcache just use the filter above
