### ISSUE TITLE
arras.io: breakage

### ISSUE THREAD

**Issue by zephiii** [uBlockOrigin/uAssets#25839]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://arras.io/`

### Category

breakage

### Description

The "Play" button takes an extremely long amount of time until it becomes properly clickable. It does not take this long if it manages to detect an adblocker or if uBO is not present.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 128
filterset (summary):
 network: 148203
 cosmetic: 48823
 scriptlet: 21281
 html: 2050
listset (total-discarded, last-updated):
 default:
  user-filters: 2790-4, never
  ublock-filters: 40765-137, 9m Δ
  ublock-badware: 11612-6, 9m Δ
  ublock-privacy: 1357-72, 9m Δ
  ublock-unbreak: 2549-1, 9m Δ
  ublock-quick-fixes: 225-10, 9m Δ
  easylist: 80375-197, 9m Δ
  adguard-spyware-url: 1764-244, 3m
  easyprivacy: 53199-64, 9m Δ
  urlhaus-1: 23480-0, 3m
  curben-phishing: 518-1, 3m
  plowe-0: 3545-999, never
  LegitimateURLShortener: 2692-2638, 9m
filterset (user): [array of 2803 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 858 ms
 maxAssetCacheWait: 252 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  intergient.com: 1
 extended:
  ##+js(set-constant, ramp.addUnits, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in your old thread. Don't open duplicated issue.

**Comment by zephiii** [comment]
> Just continue in your old thread. Don't open duplicated issue.

Okay, fine.
