### ISSUE TITLE
kotobank.jp: detection

### ISSUE THREAD

**Issue by parfait8566** [uBlockOrigin/uAssets#25833]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://kotobank.jp
https://kotobank.jp/word/kotoba-1815099
```

### Description

Open the second link (or any link that contains an actual entry) and wait for a few seconds.
A warning will pop up saying "広告ブロッカーの利用を検出しました" - "use of adblocker detected"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143839
 cosmetic: 48680
 scriptlet: 22899
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40473-263, 1m
  ublock-badware: 11583-6, 1m
  ublock-privacy: 1371-22, 1m
  ublock-unbreak: 2491-0, 1m
  ublock-quick-fixes: 224-0, 1m
  easylist: 80318-586, 1m
  easyprivacy: 53198-649, 1m
  urlhaus-1: 23885-0, 1m
  plowe-0: 3542-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2676 ms
 maxAssetCacheWait: 28 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.header-ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]

```
</details>

**Comment by stephenhawk8054** [comment]
Please enable `jp: AdGuard Japanese` list and test again.
