### ISSUE TITLE
speedtest.net: breakage

### ISSUE THREAD

**Issue by HerusInteritus** [uBlockOrigin/uAssets#25849]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.speedtest.net/`

### Category

breakage

### Description

Can't do a speed test with logged in to the site. Ad removal works without breaking the site if I'm logged out.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7c0139c4-87d9-4511-9c0a-5c64d5428470)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143275
 cosmetic: 48799
 scriptlet: 22939
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80408-588, 16m Δ
  easyprivacy: 53200-649, 16m Δ
  plowe-0: 3542-0, now
  ublock-badware: 11724-6, 16m Δ
  ublock-filters: 40511-265, 16m Δ
  ublock-privacy: 1391-22, 16m Δ
  ublock-quick-fixes: 235-0, 16m Δ
  ublock-unbreak: 2493-0, 16m Δ
  urlhaus-1: 23180-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 531 ms (selfie)
 maxAssetCacheWait: 405 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  app-us1.com: 1
  cdnst.net: 2
  googletagmanager.com: 1
  liadm.com: 1
 extended:
  ##.ads-left
  ##.ads-right
  ###zdcFloatingBtn
  ###adchoicesBtn
  ##.pure-u-custom-ad-rectangle
  ##.top-placeholder
  ##div[data-ad-placeholder]
  ##+js(abort-on-property-read, _sp_)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by HerusInteritus** [comment]
I tried it same result. After logging in I can't do a speedtest.

**Comment by stephenhawk8054** [comment]
In the new profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by HerusInteritus** [comment]
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143303
 cosmetic: 48799
 scriptlet: 22937
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80408-98, 3m Δ
  easyprivacy: 53201-3, 3m Δ
  plowe-0: 3542-998, 23m
  ublock-badware: 11752-6, 3m Δ
  ublock-filters: 40511-375, 3m Δ
  ublock-privacy: 1391-22, 3m Δ
  ublock-quick-fixes: 229-6, 40m Δ
  ublock-unbreak: 2493-19, 3m Δ
  urlhaus-1: 23180-0, 23m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms
 maxAssetCacheWait: 182 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  app-us1.com: 1
  cdnst.net: 2
  googletagmanager.com: 1
  liadm.com: 1
 extended:
  ##.ads-left
  ##.ads-right
  ###zdcFloatingBtn
  ###adchoicesBtn
  ##.pure-u-custom-ad-rectangle
  ##.top-placeholder
  ##div[data-ad-placeholder]
  ##+js(abort-on-property-read, _sp_)

**Comment by stephenhawk8054** [comment]
Did you create a new profile yet?

**Comment by HerusInteritus** [comment]
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143283
 cosmetic: 48785
 scriptlet: 22920
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40512-266, now
  ublock-badware: 11752-6, now
  ublock-privacy: 1372-22, now
  ublock-unbreak: 2493-0, now
  ublock-quick-fixes: 229-0, now
  easylist: 80376-585, now
  easyprivacy: 53199-648, now
  urlhaus-1: 23180-0, now
  plowe-0: 3542-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2298 ms
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  app-us1.com: 1
  cdnst.net: 2
  googletagmanager.com: 1
  liadm.com: 1
 extended:
  ##.ads-left
  ##.ads-right
  ###zdcFloatingBtn
  ###adchoicesBtn
  ##.pure-u-custom-ad-rectangle
  ##.top-placeholder
  ##div[data-ad-placeholder]
  ##+js(abort-on-property-read, _sp_)

**Comment by HerusInteritus** [comment]
Yes I did. Isn't this the thing you wanted to see?

**Comment by stephenhawk8054** [comment]
Your uBO is not at default settings in the troubleshooting information above.

Can you go to `chrome://extensions` page (type in URL bar) and screenshot it here?

**Comment by HerusInteritus** [comment]
![image](https://github.com/user-attachments/assets/f1efad6e-ce70-487a-b4b9-5294e149ccfa)
how can it be I just installed to that profile should I try with another PC?

**Comment by stephenhawk8054** [comment]
Create a new browser profile, and don't login or don't sync anything. Just install uBO and test again. You are having other extensions, which should not happen when you create a new browser profile.

**Comment by HerusInteritus** [comment]
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143284
 cosmetic: 48786
 scriptlet: 22933
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40512-265, 1m
  ublock-badware: 11752-6, 1m
  ublock-privacy: 1391-22, 1m
  ublock-unbreak: 2493-0, 1m
  ublock-quick-fixes: 226-0, 1m
  easylist: 80376-587, 1m
  easyprivacy: 53200-649, 1m
  urlhaus-1: 23180-0, 1m
  plowe-0: 3542-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1552 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  app-us1.com: 1
  cdnst.net: 2
  googletagmanager.com: 1
  liadm.com: 1
 extended:
  ##.ads-left
  ##.ads-right
  ###zdcFloatingBtn
  ###adchoicesBtn
  ##.pure-u-custom-ad-rectangle
  ##.top-placeholder
  ##div[data-ad-placeholder]
  ##+js(abort-on-property-read, _sp_)

**Comment by HerusInteritus** [comment]
I did just that what you asked

**Comment by HerusInteritus** [comment]
![image](https://github.com/user-attachments/assets/b496ecc7-0784-405f-b469-7f9f0d0e10de)
only extension I created new offline profile I just logged in to the speedtest site and speed test was gone

**Comment by stephenhawk8054** [comment]
I can't reproduce. The page appears normal for me:

![image](https://github.com/user-attachments/assets/7660d623-bdc9-47d8-9b69-3f55b72b04a9)

**Comment by HerusInteritus** [comment]
Strange, could be something wrong with my chrome install then?
