### ISSUE TITLE
ajanstv.com.tr: detection

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25846]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ajanstv.com.tr/diamond-tema-islam-dini-ve-hz-muhammede-hakaret-sucundan-yakalama-karari-aldi/`

### Category

detection

### Description

adblock detected its annoying

### Other extensions used

LocalCDN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241030_111704](https://github.com/user-attachments/assets/6f6d911b-514b-4903-a976-732050aaf065)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium Mobile: 132
filterset (summary):
 network: 146417
 cosmetic: 65508
 scriptlet: 24146
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40968-147, 1m
  ublock-badware: 11718-6, 1m
  ublock-privacy: 1392-22, 1m
  ublock-unbreak: 2493-1, 1m
  ublock-quick-fixes: 235-0, 1m
  adguard-mobile: 9934-97, 1m
  easylist: 80376-656, 1m
  easyprivacy: 53200-778, 1m
  urlhaus-1: 23420-0, 1m
  plowe-0: 3542-83, 1m
  TUR-0: 10750-26, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3953 ms
 maxAssetCacheWait: 46 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
ajanstv.com.tr##+js(nostif, adblock)
```

@Alex-302 For AG Turkish

**Comment by Alex-302** [comment]
Can be closed. Blocked in Annoyances.
