### ISSUE TITLE
mindbodygreen.com: ads

### ISSUE THREAD

**Issue by skullriot** [uBlockOrigin/uAssets#25844]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mindbodygreen.com/articles/cartomancy`

### Category

ads

### Description

Large video ad break in the text of the page "mindbodygreen Functional Nutrition Training"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e0af8885-33fb-4806-a9e5-647f9549c00e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 245397
 cosmetic: 253087
 scriptlet: 51469
 html: 2051
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85457-529, now
  adguard-spyware-url: 1764-127, now
  adguard-spyware: 96153-1532, now
  adguard-social: 23106-49, now
  adguard-cookies: 32305-62, now
  adguard-popup-overlays: 27904-2082, now
  adguard-mobile-app-banners: 5525-33, now
  adguard-other-annoyances: 14732-462, now
  adguard-widgets: 2737-19, now
  fanboy-thirdparty_social: 68-3, now
  easylist-annoyances: 4820-344, now
  easylist-chat: 216-18, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 40771-3650, 1h.23m Δ
  ublock-badware: 11716-125, 1h.23m Δ
  ublock-privacy: 1358-22, 1h.23m Δ
  ublock-unbreak: 2549-78, 1h.23m Δ
  ublock-quick-fixes: 230-19, 1h.23m Δ
  easylist: 80397-2174, 1h.23m Δ
  easyprivacy: 53200-22571, 1h.23m Δ
  urlhaus-1: 23420-0, now
  plowe-0: 3542-1097, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 262 ms (selfie)
 maxAssetCacheWait: 171 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  chartbeat.com: 1
  d2wy8f7a9ursnm.cloudfront.net: 2
  doubleclick.net: 1
  dwin1.com: 3
  htlbid.com: 1
  jwpcdn.com: 3
  jwpltx.com: 8
  refersion.com: 1
  segment.com: 1
  segment.io: 1
 extended:
  ##div:has(> section > .network-ad)
  ###article-leaderboard-ad
  ##.sc-10p0iao-0
  ##div[data-exp-id="right-rail-email"]
  ##.inline-ad
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##.right-rail-ad
  ##span > section:has(> div > h5:contains(/^Advertisement$/))
  ##aside:style(background: transparent !important;)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
I get only the text part, however it's about self-promotion
