### ISSUE TITLE
seznam.cz: breakage

### ISSUE THREAD

**Issue by sexsamba2** [uBlockOrigin/uAssets#25848]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.seznam.cz/`

### Category

breakage

### Description

The page is not displaying properly

### Other extensions used

The page is not displaying properly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 145168
 cosmetic: 57910
 scriptlet: 21530
 html: 2054
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 41282-138, 17m Δ
  ublock-badware: 11720-6, 17m Δ
  ublock-privacy: 1378-22, 17m Δ
  ublock-unbreak: 2553-1, 17m Δ
  ublock-quick-fixes: 234-10, 17m Δ
  adguard-mobile: 9927-97, 5m
  easylist: 80404-269, 17m Δ
  easyprivacy: 53200-73, 17m Δ
  urlhaus-1: 23420-0, 5m
  plowe-0: 3542-1072, 5m
  CZE-0: 844-12, 5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2078 ms (selfie)
 maxAssetCacheWait: 162 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  seznam.cz: 4
  adnxs.com: 1
  criteo.com: 1
  id5-sync.com: 1
  pubmatic.com: 1
 extended:
  ##[class*="advert"]
  ##[data-draggable-target]:has-text(Rekl):not(*:has([href*="radio…
  ##+js(no-setTimeout-if, 0x)
  ##+js(remove-node-text, script, adComm)
  ##+js(abort-on-property-write, Fisher)
  ##+js(addEventListener-defuser, message, fishing)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

> - [X] I did not answer truthfully to **ALL** the above checkboxes.

Continue here: https://github.com/uBlockOrigin/uAssets/issues/17862
