### ISSUE TITLE
reddit.com: nuisance

### ISSUE THREAD

**Issue by Manikandan-Vanniyar** [uBlockOrigin/uAssets#25847]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
reddit.com
```

### Description

Getting the irritating login popup while using reddit

### Other extensions used

Dark reader
Localcdn
bypass paywall clean

### Screenshot(s)

https://github.com/user-attachments/assets/e54735e5-3f32-405f-ab77-2e0768805903

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 291880
 cosmetic: 208994
 scriptlet: 49755
 html: 2316
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-1, 18h.13m
  https://raw.githubusercontent.com/iam-py-test/uBlock-combo/main/list.txt: 118838-61, 12h.48m
  adguard-generic: 85459-4301, 18h.13m
  adguard-spyware-url: 1764-244, 1d.1h.37m
  fanboy-cookiemonster: 69032-16895, 6d.22h.48m
  ublock-cookies-easylist: 1889-23, 3d.19h.39m
  adguard-social: 23090-48, 1d.22h.21m
  fanboy-social: 16736-783, 8d.19h.41m
  easylist-annoyances: 4810-80, 3d.19h.40m
  easylist-chat: 216-0, 3d.19h.38m
  easylist-newsletters: 7985-48, 3d.19h.40m
  easylist-notifications: 3464-169, 3d.19h.40m
  [1 lists not shown]: [too many]
 default:
  user-filters: 59-0, never
  ublock-filters: 41280-156, 1m Δ
  ublock-badware: 11710-888, 1m Δ
  ublock-privacy: 1378-22, 1m Δ
  ublock-unbreak: 2551-1, 1m Δ
  ublock-quick-fixes: 234-0, 1m Δ
  adguard-mobile: 9933-131, 18h.13m
  easylist: 80397-2440, 1m Δ
  easyprivacy: 53200-163, 1m Δ
  urlhaus-1: 23480-10, 12h.47m
  plowe-0: 3542-1091, 2d.14h.40m
  IND-0: 13604-52, 12h.47m
filterset (user): [array of 57 redacted]
trustedset:
 added: [array of 11 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
hostRuleset:
 added: [array of 59 redacted]
 removed:
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 627 ms (selfie)
 maxAssetCacheWait: 322 ms
 cacheBackend: indexedDB
```
</details>

**Comment by skyler544** [comment]
Can we reopen this? I'm getting this popup on every single reddit thread in Firefox on Android. Scrolling down far enough, clicking "View more comments", or uncollapsing a comment thread triggers it.

**Comment by skyler544** [comment]
> Can't reproduce.

It's clearly happening for some users, even if you're unable to reproduce it. We should work together to improve the filter list for everyone who *is* affected. 

What steps are you trying? Do you have any suggestions for how to further debug the issue? 

I'm interested in creating a pull request for this if I can find out what the proper selector is; I'm on mobile so I don't have the inspector.

**Comment by skyler544** [comment]
I found a filter that can block it:

```
reddit.com##inline-auth-landing-experience-xpromo-shell
```

I'll see about opening a PR against this issue.

**Comment by stephenhawk8054** [comment]
Please report to https://github.com/easylist/easylist/issues and https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by Rudxain** [comment]
> mobile so I don't have the inspector

https://addons.mozilla.org/en-US/android/addon/mobidevtools
