### ISSUE TITLE
app.navan.com: breakage

### ISSUE THREAD

**Issue by tmccombs** [uBlockOrigin/uAssets#25841]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.navan.com/app/user2/auth/openid-connect/return`

### Category

breakage

### Description

Logging in to Navan with Okta results in the page getting stuck in "processing" and never finishes.

If I disable uBO, it works fine. 

### Other extensions used

1password
Okta
Sidebery
Zoom Closer
Zoom Extension
AWS Extend Switch Role

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/ca43dda9-27a5-45fc-b187-b2b609cb01e8)

</details>

<details><summary>Logger output</summary>

```
+1
||cloudflareinsights.com^
--
app.navan.com
3
get
script
https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015
```
```
+1
||newrelic.com^$3p
--
app.navan.com
3
get
script
https://js-agent.newrelic.com/nr-loader-spa-1.264.0.min.js
```
```
+0
||cloudflareinsights.com^
--
app.navan.com
3
get
script
https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015
```
```
+0
||newrelic.com^$3p
--
app.navan.com
3
get
script
https://js-agent.newrelic.com/nr-loader-spa-1.264.0.min.js
```
```
+0
https://app.navan.com/app/user2/auth/openid-connect/return?state=REDACTED
```
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 143620
 cosmetic: 48698
 scriptlet: 21276
 html: 2050
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40769-137, 43m Δ
  ublock-badware: 11716-6, 43m Δ
  ublock-privacy: 1359-23, 43m Δ
  ublock-unbreak: 2549-1, 43m Δ
  ublock-quick-fixes: 229-10, 43m Δ
  easylist: 80376-571, 43m Δ
  easyprivacy: 53199-687, 43m Δ
  urlhaus-1: 23480-0, 43m
  plowe-0: 3542-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1579 ms (selfie)
 maxAssetCacheWait: 78 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  newrelic.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
> Logging in to Navan with Okta results in the page

I don't understand this part. Can you describe the steps to reproduce in more details?

**Comment by tmccombs** [comment]
hmm, I can't reproduce now. 

Maybe the site was just completely broken, and it just happened to come back up at the same time I tried accessing it with uBO disabled.
