### ISSUE TITLE
kuramanime.red: ads

### ISSUE THREAD

**Issue by nuha1012** [uBlockOrigin/uAssets#25840]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kuramanime.red/anime/3140/arifureta-shokugyou-de-sekai-saikyou-season-3/episode/3`

### Category

ads

### Description

show ads with shortlink tinyurl

### Other extensions used

adobe acrobat, idm, google translate, google docs offline,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0d633459-cb3f-40c8-be25-b34b31810fcd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 154544
 cosmetic: 48699
 scriptlet: 22916
 html: 0
listset (total-discarded, last-updated):
 added:
  dpollock-0: 11702-460, 17m
 default:
  user-filters: 3-1, never
  ublock-filters: 40507-266, 17m Δ
  ublock-badware: 11641-6, 17m Δ
  ublock-privacy: 1372-22, 17m Δ
  ublock-unbreak: 2491-0, 17m Δ
  ublock-quick-fixes: 226-0, 17m Δ
  easylist: 80376-747, 17m Δ
  easyprivacy: 53199-736, 17m Δ
  urlhaus-1: 23480-0, 17m
  plowe-0: 3542-0, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1160 ms
 maxAssetCacheWait: 255 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 1
  google.com: 4
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  onesignal.com: 1
```
</details>

**Comment by mapx-** [comment]
enable the regional list ABPindo
