### ISSUE TITLE
msn.com: breakage

### ISSUE THREAD

**Issue by GordFather** [uBlockOrigin/uAssets#25855]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.msn.com/en-ca?checklang=1`

### Category

breakage

### Description

When UBlock is activated, page will not load.   After turning UBlock off, page loads but full of ads

### Other extensions used

Bitdefender Antitracker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/user-attachments/assets/c065727f-91ae-40f9-a6f9-29733cdd4f18)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 140344
 cosmetic: 48809
 scriptlet: 22937
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 80140-476, 6m
  easyprivacy: 53213-648, 6m
  plowe-0: 3542-0, 6m
  ublock-badware: 11753-6, 6m
  ublock-filters: 40518-377, 6m
  ublock-privacy: 1391-22, 7m
  ublock-quick-fixes: 229-0, 7m
  ublock-unbreak: 2493-0, 7m
  urlhaus-1: 20480-0, 7m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 950 ms
 maxAssetCacheWait: 93 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 24
 network:
  msn.com: 23
  scorecardresearch.com: 1
 extended:
  ##+js(json-prune-fetch-response, properties.componentConfigs.sli…
  ##+js(json-prune-fetch-response, *, list.*.link.ad list.*.link.k…
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by GordFather** [comment]
Same Result.  Screenshot showing UBlock into

![Untitled](https://github.com/user-attachments/assets/c4d5571f-2422-4bf7-868e-c54d5edc84b3)

**Comment by stephenhawk8054** [comment]
Don't change any settings inside uBO

> a new browser profile with only uBO and **its default settings.**

**Comment by GordFather** [comment]
I never changed any setting in uBO.   I don't know how so it should still be default.

**Comment by stephenhawk8054** [comment]
I see that you are having bookmarks in your screenshot which should not happen with a new browser profile. You are also enabling advanced settings inside uBO and using custom rules

```yml
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 collapseBlocked: false
```

![image](https://github.com/user-attachments/assets/c23326af-4fd1-4b06-aab8-3cdf232d484f)

---

Create a new profile like this instruction: https://support.google.com/chrome/answer/2364824

DON'T login or sync anything in the new profile. Just install uBO on that profile and test again.

**Comment by GordFather** [comment]
Ok it loads the old style MSN.  Its format has changed.   Do you know how I can move back to the old style ( I don't like the new one )

**Old Style:**  

![Untitled](https://github.com/user-attachments/assets/833297b3-bab2-49f1-a5dd-a3a866d838d8)

**New Style Site**

![Untitled](https://github.com/user-attachments/assets/19c9851f-b9a4-481c-ac26-c8bd5cda01a5)

**Comment by stephenhawk8054** [comment]
I don't know. The issue here is the page being blank. Please just focus to solve that.

In your old profile, can you reset uBO to default settings: Click uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) -> Go to "Settings" tab -> Scroll down and click on "Reset to default settings" then test again.

**Comment by GordFather** [comment]
Still shows up blank after reseting to defaults

**Comment by stephenhawk8054** [comment]
In your old profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by GordFather** [comment]
Not sure what happened.   All of a sudden it is loading properly - I think it may have gotten screwed up on MSN Login information.   I haven't use the logon to MSN for a long time because it wasn't retaining my credentials.

Thank you for your time
