### ISSUE TITLE
z-library.sk: breakage

### ISSUE THREAD

**Issue by olumolu** [uBlockOrigin/uAssets#25850]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
yadro.ru
```

### Description

This url is used in z library for loading images and in there website kindly onblock this domain to get a better experience in z library 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241030-222624](https://github.com/user-attachments/assets/3089779d-3811-451b-b247-06fd032186e8)
![Screenshot_20241030-222633](https://github.com/user-attachments/assets/ffc5defd-c8f2-43f7-b418-ff7b11d5987c)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 132
filterset (summary):
 network: 221037
 cosmetic: 103797
 scriptlet: 28096
 html: 2053
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1764-127, 3d.15h.32m
  adguard-spyware: 98024-24293, 3d.15h.54m
  block-lan: 64-2, 5d.10h.5m
  fanboy-cookiemonster: 52335-192, 4d.17m
  ublock-cookies-easylist: 1888-23, 6d.9h.50m
 default:
  user-filters: 0-0, never
  ublock-filters: 41283-138, 9m Δ
  ublock-badware: 11748-6, 9m Δ
  ublock-privacy: 1378-25, 9m Δ
  ublock-unbreak: 2553-1, 9m Δ
  ublock-quick-fixes: 228-16, 9m Δ
  adguard-mobile: 9928-176, 3d.15h.54m
  easylist: 80415-189, 9m Δ
  easyprivacy: 53201-62, 9m Δ
  urlhaus-1: 23180-0, 4h.33m
  plowe-0: 3545-1155, 8d.2h.44m
filterset (user): [empty]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 569 ms (selfie)
 maxAssetCacheWait: 144 ms
 cacheBackend: indexedDB

```
</details>

**Comment by stephenhawk8054** [comment]
Please give exact link where issue occurs.

**Comment by olumolu** [comment]
https://z-library.sk

**Comment by stephenhawk8054** [comment]
I don't see any images being blocked with your link above.

**Comment by olumolu** [comment]
I find the fix closing this report sorry.
