### ISSUE TITLE
evite.com: ads

### ISSUE THREAD

**Issue by GeorgeMcTavern** [uBlockOrigin/uAssets#25854]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.evite.com/event
```

### Description

On Evite invitation pages there are two banner ads that won't block.  Manually blocking them doesn't work as they reappear after reloading the page. Also, when you block one ad, then the next, the first one pops back up. 

### Other extensions used

Privacy Badger (shut off temporarily to troubleshoot)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Evite 1](https://github.com/user-attachments/assets/44fb04f6-6a07-499e-ad9a-383de05eed64)
![Evite 2](https://github.com/user-attachments/assets/e84ce362-2337-44e0-a46e-e8d650ebd8ba)
![Evite 3](https://github.com/user-attachments/assets/306aba46-9914-4811-854f-63e4cea3c297)

</details>

### Configuration

<details>
<summary>Details</summary>

 uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 143357
 cosmetic: 48863
 scriptlet: 21291
 html: 2052
listset (total-discarded, last-updated):
 default:
  user-filters: 125-36, never
  ublock-filters: 40780-137, 3m Δ
  ublock-badware: 11755-6, 3m Δ
  ublock-privacy: 1377-22, 3m Δ
  ublock-unbreak: 2551-1, 3m Δ
  ublock-quick-fixes: 228-10, 3m Δ
  easylist: 80420-195, 3m Δ
  easyprivacy: 53212-63, 3m Δ
  urlhaus-1: 23180-0, 4h.17m
  plowe-0: 3545-999, 10d.8h.6m
filterset (user): [array of 125 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2748 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
You are creating network filters, so you need to refresh the page while bypassing the cache (`Ctrl + Shift + R`).

Or you can choose the filters under the `Cosmetic filters`. Can you test this one:

```adb
evite.com##.fabric-free-banner-ad__wrapper
```

**Comment by GeorgeMcTavern** [comment]
Copy and pasted that filter in and it worked! Thanks much.
   On Wednesday, October 30, 2024 at 09:57:01 PM EDT, stephenhawk8054 ***@***.***> wrote:  
 
 


You are creating network filters, so you need to refresh the page while bypassing the cache (Ctrl + Shift + R).

Or you can choose the filters under the Cosmetic filters. Can you test this one:
evite.com##.fabric-free-banner-ad__wrapper
