### ISSUE TITLE
shopgoodwill.com: nuisance

### ISSUE THREAD

**Issue by PUNKANDGOTH** [uBlockOrigin/uAssets#25852]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://shopgoodwill.com/shopgoodwill/order/51328620`

### Category

nuisance

### Description

Uptick comes up and is annoying ( comes up after purchase ) 
![image](https://github.com/user-attachments/assets/11ee251b-1a0f-4d83-9a3a-ec34eec90d65)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a29e8814-a0c3-4559-9c40-06072d29c904)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 143328
 cosmetic: 48806
 scriptlet: 22937
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 80420-47, now
  easyprivacy: 53212-664, now
  plowe-0: 3542-375, now
  ublock-badware: 11753-24, now
  ublock-filters: 40518-375, now
  ublock-privacy: 1391-24, now
  ublock-quick-fixes: 229-6, now
  ublock-unbreak: 2493-12, now
  urlhaus-1: 23180-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 532 ms (selfie)
 maxAssetCacheWait: 174 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 no-cosmetic-filtering: true
 network:
  adobedtm.com: 3
  demdex.net: 1
  fuseplatform.net: 1
  googletagmanager.com: 1
  scarabresearch.com: 1
  uptick.com: 1
 extended:
  ##.uptick-content
```
</details>

**Comment by mapx-** [comment]
> comes up after purchase

needing account, needing .. purchase. Nothing to do.
