### ISSUE TITLE
skipthecommericals.xyz: detection

### ISSUE THREAD

**Issue by pop-dahaka** [uBlockOrigin/uAssets#25865]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://skipthecommericals.xyz/`

### Category

detection

### Description

Please turn off your ad blocker.

when disabled it and reload its work.

### Other extensions used

nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![skipthecommericals xyz](https://github.com/user-attachments/assets/873ea6d4-2f1e-4283-88ea-351316d4f23a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 129970
 cosmetic: 56960
 scriptlet: 24113
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
  TUR-0: 10754-10, now
 default:
  user-filters: 49-11, never
  easylist: 80185-482, 2m Δ
  easyprivacy: 53221-653, 2m Δ
  plowe-0: 3542-1, now
  ublock-badware: 11771-6, 2m Δ
  ublock-filters: 40540-382, 2m Δ
  ublock-privacy: 1396-22, 2m Δ
  ublock-quick-fixes: 237-0, 2m Δ
  ublock-unbreak: 2494-3, 2m Δ
  urlhaus-1: 8565-0, 2m
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 765 ms (selfie)
 maxAssetCacheWait: 162 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  google.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's a parked domain.
