### ISSUE TITLE
abcya.com: breakage

### ISSUE THREAD

**Issue by toasty-teacher** [uBlockOrigin/uAssets#25863]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.abcya.com/`

### Category

breakage

### Description

Website detects an adblocker and asks for it to be turned off. Students attempting to play games are able to enter the game's page and even press the play button, but nothing loads. On Ublock Origin, the site worked well, but Ublock Lite is seemingly having issues. All filter levels do not work. I have to turn filtering off to get the site to work.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/user-attachments/assets/f275ba79-710c-45a1-a37e-bfd60493600c)

</details>

### Configuration

```yaml
version: uBOL 2024.10.28.929
mode: complete / complete
rulesets:
 default
 block-lan
 dpollock-0
 adguard-spyware-url
 annoyances-cookies
 annoyances-overlays
 annoyances-social
 annoyances-widgets
 annoyances-others
 stevenblack-hosts
```

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details? I accessed the page and it looks normal for me

![image](https://github.com/user-attachments/assets/ba8c4eb3-85c9-48e0-befa-43f0ed269b08)

**Comment by toasty-teacher** [comment]
Hello, I'm not sure if this should be reopened, but I figured I would add a note and question here. After the November 19th update, the website's games do work, but only on the Optimal and Complete settings. On Basic, the games display a gray screen after pressing the play button. Is it possible to get the site working on the Basic filtering setting?

**Comment by stephenhawk8054** [comment]
Not possible.

**Comment by toasty-teacher** [comment]
Ah bugger. I appreciate the reply. So I'm stuck waiting for whenever Chrome allows a permission-less extension because having to manually click "Allow" for Optimal settings on hundreds of PCs just isn't feasible at the moment.
