### ISSUE TITLE
[nsfw] huiagun.com: ads

### ISSUE THREAD

**Issue by BeyondArc** [uBlockOrigin/uAssets#25861]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.huiagun.com/colors/23`

### Category

ads

### Description

an ad below and at right, a notification at the top show "this site only show 10 windows (of ads) per day, this notification will close in 5seconds"

### Other extensions used

noscript

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241031_132706_Firefox](https://github.com/user-attachments/assets/61badf50-68f2-41bf-882b-37f9fdbbaee4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 156028
 cosmetic: 68406
 scriptlet: 21660
 html: 2053
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 41292-133, 6m
  ublock-badware: 11765-6, 6m
  ublock-privacy: 1383-22, 6m
  ublock-unbreak: 2554-1, 6m
  ublock-quick-fixes: 233-10, 6m
  adguard-mobile: 9942-97, 6m
  easylist: 80162-269, 6m
  easyprivacy: 53217-72, 6m
  urlhaus-1: 20480-0, 6m
  plowe-0: 3542-1072, 6m
  CHN-0: 25520-121, 6m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 789 ms
 maxAssetCacheWait: 337 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  clarity.ms: 1
```
</details>

**Comment by mapx-** [comment]
@cjx82630

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/8726e11a68b54b293c302a896e07fb8bd7dd9143
