### ISSUE TITLE
app.plex.tv: breakage

### ISSUE THREAD

**Issue by tekwarfare** [uBlockOrigin/uAssets#25862]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://app.plex.tv/desktop/`

### Category

breakage

### Description

uBlock enabled results in 'No Content Available' message for Plex when accessed via plex.tv
Pressing the power button remedies this

### Other extensions used

Same issue with all other extensions disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/06df98a3-d33c-4495-888d-f06da8af1c60)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 232110
 cosmetic: 226817
 scriptlet: 53297
 html: 2316
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83234-242, now
  https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 0-0, never
  https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser: 3556-8, now
  adguard-generic: 85482-529, now
  adguard-social: 23113-834, now
  fanboy-cookiemonster: 52373-4073, now
  ublock-annoyances: 5918-241, 24m Δ
  adguard-spyware-url: 1764-127, now
  block-lan: 64-2, 24m
  adguard-spyware: 96072-24073, now
 default:
  user-filters: 122-0, never
  ublock-filters: 40783-3952, 24m Δ
  ublock-badware: 11761-125, 24m Δ
  ublock-privacy: 1377-22, 24m Δ
  ublock-unbreak: 2552-80, 24m Δ
  easylist: 80162-2246, 24m Δ
  easyprivacy: 53214-1409, 24m Δ
  urlhaus-1: 8565-0, now
  plowe-0: 3542-1017, now
  ublock-quick-fixes: 228-25, 24m Δ
filterset (user): [array of 123 redacted]
trustedset:
 added: [array of 62 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 193 ms (selfie)
 maxAssetCacheWait: 141 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  plex.tv: 1
  googletagmanager.com: 1
  plex.direct: 3
  sentry.io: 1
 extended:
  ##.NavBarAccountMenu-navbarAvatarBadge-aUFsOp
  ##+js(json-prune, MediaContainer.Metadata.[].Ad)
  ##+js(set-cookie, plex_tv_cookie_consent, 2)
  ##+js(prevent-fetch, plex.tv/api/v2/ads/vendors, emptyStr)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by holysoles** [comment]
> Test again in a new Firefox profile with only uBO and its default settings.

I am experiencing the same issue, and tested as recommended, no luck

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by holysoles** [comment]
Ah sorry I was mistaken. It was a combination of the `block-lan` rule and my local DNS override. An allow rule to override the resolved the issue. Thanks for the prompt response!
