### ISSUE TITLE
admin.corrata.com: breakage

### ISSUE THREAD

**Issue by stephenobrien93** [uBlockOrigin/uAssets#25878]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://admin.corrata.com/console/`

### Category

breakage

### Description

https://admin.corrata.com/console/dcconsolews/event-log endpoint is mistakenly blocked by uBlock origin

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 139788
 cosmetic: 48938
 scriptlet: 21318
 html: 2055
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40808-132, 35m Δ
  ublock-badware: 11804-6, 35m Δ
  ublock-privacy: 1383-22, 35m Δ
  ublock-unbreak: 2556-1, 35m Δ
  ublock-quick-fixes: 242-10, 35m Δ
  easylist: 80311-198, 35m Δ
  easyprivacy: 53224-63, 35m Δ
  urlhaus-1: 19800-0, now
  plowe-0: 3542-998, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 362 ms (selfie)
 maxAssetCacheWait: 70 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  corrata.com: 1
```
</details>

**Comment by gorhill** [comment]
Can you open [the logger](https://github.com/gorhill/uBlock/wiki/The-logger), force a reload of the page, then report which network request is being blocked?

**Comment by stephenobrien93** [comment]
Hi there, I just checked which URL was being blocked and this is it:

https://admin.corrata.com/console/dcconsolews/event-log?accountId=100000&startDate=1730077201770&endDate=1730764799770

Is there any way to whitelist this URL? It is urgent, as it's breaking some functionality on our site

**Comment by stephenhawk8054** [comment]
Can you screenshot what is broken on the page for users?

**Comment by stephenobrien93** [comment]
![Screenshot from 2024-11-04 11-39-25](https://github.com/user-attachments/assets/065f4bf4-5b8f-400d-8622-eff7b1bce6ca)

uBlock origin is blocking access to the URL that loads the data to fill this table. This is a pretty important feature for our customers, and we currently have no way of fixing the issue for them aside from telling them to disable uBlock origin on the site.

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > ▤ ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Open new tab and reproduce the issue
3. Switch to the logger window that was opened in step 1, [click on search bar, choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output)
4. Copy the logger via 📋 [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by stephenobrien93** [comment]
Here's the logs!

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
@@||admin.corrata.com/console/dcconsolews/event-log?$xhr,1p
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by stephenobrien93** [comment]
Ok, the page appears to be loading correctly now. Is there any reason why this URL is being blocked by uBlock in the first place? Obviously this is a better workaround for our customers, but we'd prefer not to have this issue in the at all.

**Comment by stephenhawk8054** [comment]
It's blocked by the filter `/event-log?` [by EasyPrivacy list](https://github.com/easylist/easylist) which is used to block tracking URLs. uBO blocks ads and trackers by default.

> we'd prefer not to have this issue in the at all.

I don't understand what you mean. uBO can't guarantee there's no false positives 100% for all websites in the internet. If there's any breakages, just report the issues.
