### ISSUE TITLE
chesskid.com: breakage

### ISSUE THREAD

**Issue by mauserk98grenaderifle** [uBlockOrigin/uAssets#25877]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.chesskid.com/learn/articles/count-attackers-and-defenders`

### Category

breakage

### Description

The site loads when ublock is deactivated, ALL filters are on (except the region/language filters)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 257435
 cosmetic: 262715
 scriptlet: 54931
 html: 2258
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83259-83259, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103450-34560, 1m
  adguard-generic: 85477-7343, 2m
  adguard-mobile: 9941-189, 2m
  adguard-spyware: 96073-23172, 2m
  block-lan: 64-2, 2m
  adguard-social: 23115-919, 2m
  adguard-cookies: 32338-3940, 2m
  ublock-cookies-adguard: 1862-1862, 2m
  adguard-popup-overlays: 27921-2965, 2m
  adguard-mobile-app-banners: 5526-1140, 2m
  adguard-other-annoyances: 14733-678, 2m
  [11 lists not shown]: [too many]
 default:
  user-filters: 16-0, never
  ublock-filters: 40599-143, 2m
  ublock-badware: 11173-6, 2m
  ublock-privacy: 1264-22, 2m
  ublock-unbreak: 2538-0, 2m
  ublock-quick-fixes: 133-0, 2m
  easylist: 85550-577, 2m
  adguard-spyware-url: 1764-244, 2m
  easyprivacy: 53091-44, 2m
  urlhaus-1: 15052-0, 2m
  curben-phishing: 506-1, 2m
  plowe-0: 3553-625, 1m
  LegitimateURLShortener: 2692-49, 1m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7714 ms
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  chesskid.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||chesskid.com/js/client-prod/assets/cookie-banner$script,1p`

AAc issue @Alex-302 @Yuki2718
