### ISSUE TITLE
tportal.hr: ads

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#25879]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tportal.hr/`

### Category

ads

### Description

Large ad placeholder visible.

`##.banner--billboard-top.banner--billboard.banner` hides it.

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/117dcc06-fce9-404a-a245-18a516d14dd0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 273265
 cosmetic: 255181
 scriptlet: 55149
 html: 2319
listset (total-discarded, last-updated):
 added:
  https://o0.pages.dev/Lite/adblock.txt: 90025-82, now
  adguard-generic: 85485-8295, now
  adguard-spyware-url: 1764-131, now
  adguard-spyware: 96074-18689, now
  curben-phishing: 506-1, now
  adguard-cookies: 32336-94, now
  ublock-cookies-adguard: 1862-27, now
  fanboy-cookiemonster: 52374-4116, now
  ublock-cookies-easylist: 1862-1862, now
  adguard-social: 23116-51, now
  fanboy-social: 16779-765, now
  adguard-popup-overlays: 27923-2192, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 40809-132, now
  ublock-badware: 11804-77, now
  ublock-privacy: 1383-35, now
  ublock-unbreak: 2556-2, now
  ublock-quick-fixes: 242-10, now
  easylist: 80335-20675, now
  easyprivacy: 53225-40119, now
  urlhaus-1: 19800-0, now
  plowe-0: 3542-2458, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 419 ms (selfie)
 maxAssetCacheWait: 184 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  dotmetrics.net: 2
  gemius.pl: 1
  googletagmanager.com: 1
  html-load.com: 1
  newrelic.com: 2
  privacy-center.org: 1
  upscore.com: 2
  wtg-ads.com: 1
 extended:
  ##.footer__newsletter
  ##.positionFrame:has([src*="native.tportal"])
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(remove-class, advertisingActive, div.gpElement.hasSidebarB…
  ##+js(json-prune, options.displayBannerAfterEntry)
  ##+js(set-constant, Object.prototype.displayBannerAfterEntry, {}…
```
</details>

**Comment by gorhill** [comment]
Need `tportal.hr##.banner`, should be fixed in _"Dandelion Sprout's Serbo-Croatian filters"_.

cc @DandelionSprout

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/26619#issuecomment-3146744346

**Comment by stephenhawk8054** [comment]
@ryanbr For ELC: `https://www.tportal.hr/sport/clanak/zabio-je-za-dinamovo-vodstvo-pa-poslao-jasnu-poruku-napadac-zivi-od-golova-20250802` video breakage

```adb
@@||sdk.privacy-center.org^$script,domain=tportal.hr
```

**Comment by Marko-98** [comment]
Top part of the website is missing and giant red ad widget is being shown. The ad widget is served from URL `https://assets.tportal.hr/DT/Native/`.

URL: https://www.tportal.hr/

<details>
<summary>With uBO enabled</summary>




<img width="2560" height="21925" alt="Image" src="https://github.com/user-attachments/assets/3fc71c8d-6bbf-4ffe-90bf-25564afa8f8a" />



</details>


<details>
<summary>With uBO disabled</summary>




<img width="2560" height="25501" alt="Image" src="https://github.com/user-attachments/assets/fe9575ce-61aa-4ce8-9996-c868e8130775" />



</details>

<details>

```yaml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 188745
 cosmetic: 166433
 scriptlet: 65702
 html: 3837
listset (total-discarded, last-updated):
 added:
  adguard-generic: 96362-5811, now
  adguard-spyware-url: 2530-134, now
  block-lan: 91-0, now
  fanboy-cookiemonster: 46639-116, now
  ublock-cookies-easylist: 5680-46, now
  fanboy-social: 17695-16, now
  easylist-annoyances: 5214-64, now
  fanboy-ai-suggestions: 252-0, now
  easylist-newsletters: 9327-37, now
  easylist-notifications: 2508-177, now
  ublock-annoyances: 4932-103, now
  HRV-0: 526-110, now
 default:
  user-filters: 3-0, never
  ublock-filters: 52560-70, now
  ublock-badware: 10356-28, now
  ublock-privacy: 4029-2, now
  ublock-unbreak: 2831-1, now
  ublock-quick-fixes: 442-14, now
  easylist: 88106-1224, now
  easyprivacy: 55813-122, now
  urlhaus-1: 24720-11, now
  plowe-0: 3509-1039, now
filterset (user): [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 248 ms (selfie)
 maxAssetCacheWait: 157 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.footer__newsletter
  ##.banner
  ##.positionFrame:has([src*="native.tportal"])
  ##.footer__social_media
  ##+js(trusted-click-element, #didomi-notice-agree-button)
  ##+js(set-constant, Object.prototype.displayBannerAfterEntry, {}…
  ##+js(json-prune, options.displayBannerAfterEntry)
  ##+js(remove-class, advertisingActive, div.gpElement.hasSidebarB…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_bGFzdF9iZmFfYXQ=$/, $remove$)
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
```
</details>

**Comment by gorhill** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
I can reproduce it on my end in a hurry, so I'll see if I can cook up a fast fix for it.
