### ISSUE TITLE
flaticon.com: ads

### ISSUE THREAD

**Issue by MapleGingerOatmeal** [uBlockOrigin/uAssets#25871]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.flaticon.com/search/7?word=applications`

### Category

ads

### Description

Ads for stock image websites like Adobe Stock and Getty Images appear in the bottom right corner after you navigate through at least a few pages of search results, most often somewhere between page 4 and 7 of the results.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![flaticon-01](https://github.com/user-attachments/assets/971bc7a0-d088-4ee1-a3ec-695fa1b302db)
<img width="1118" alt="flaticon-02" src="https://github.com/user-attachments/assets/72747505-41de-4209-bb32-0784c3599e7a">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 139734
 cosmetic: 48826
 scriptlet: 21309
 html: 2055
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40805-132, 14m
  ublock-badware: 11761-6, 14m
  ublock-privacy: 1382-22, 14m
  ublock-unbreak: 2552-1, 14m
  ublock-quick-fixes: 236-10, 14m
  easylist: 80185-197, 14m
  easyprivacy: 53221-63, 14m
  urlhaus-1: 19810-0, 14m
  plowe-0: 3542-998, 14m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1164 ms
 maxAssetCacheWait: 18 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  7eer.net: 8
  abtasty.com: 2
  go-mpulse.net: 2
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 2
  hs-analytics.net: 1
  hs-banner.com: 1
  ssm.codes: 2
 extended:
  ##li[id^="bn-icon-list"]
  ##+js(abort-on-property-read, pu_url)
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
flaticon.com##.soul-p-nsba
||api.gettyimages.com/v3/search/images/creative?*referral_destinations$xhr,domain=flaticon.com
||fps.cdnpk.net^
||sps.cdnpk.net^
||sp.cdnpk.net^
```
