### ISSUE TITLE
hnonline.sk: breakage

### ISSUE THREAD

**Issue by myxal** [uBlockOrigin/uAssets#25876]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hnonline.sk/users`

### Category

breakage

### Description

After logging in, the "My Profile" page doesn't work - the part where subscription/payment information should be etc. is missing.

### Other extensions used

steam inventory helper
(in incognito mode, where this was reproduced; I use many, many more in normal mode)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-01 at 11 51 14](https://github.com/user-attachments/assets/53edfbed-1ee0-488a-a0cf-310e89782183)
![Screenshot 2024-11-01 at 11 51 27](https://github.com/user-attachments/assets/a9476498-72b8-4169-8610-2a8a2ea02855)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 146490
 cosmetic: 142049
 scriptlet: 29571
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83250-83250, 56m
  CZE-0: 844-1, 56m
  adguard-cookies: 32335-76, 56m
  adguard-mobile-app-banners: 5526-15, 55m
  adguard-other-annoyances: 14731-126, 55m
  adguard-popup-overlays: 27917-1979, 56m
  adguard-social: 23115-34, 56m
  adguard-widgets: 2741-2, 56m
  ublock-cookies-adguard: 1862-9, 56m
 default:
  user-filters: 27-0, never
  easylist: 80307-544, 57m
  easyprivacy: 53224-664, 57m
  plowe-0: 3542-0, now
  ublock-badware: 11786-6, 56m
  ublock-filters: 40543-706, 56m
  ublock-privacy: 1397-22, now
  ublock-quick-fixes: 237-0, 56m
  ublock-unbreak: 2494-0, 57m
  urlhaus-1: 19810-0, 56m
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 985 ms (selfie)
 maxAssetCacheWait: 59 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  adform.net: 1
  adocean.pl: 1
  aticdn.net: 1
  caroda.io: 1
  cloudflareinsights.com: 1
  cpex.cz: 1
  cxense.com: 1
  doubleclick.net: 1
  ebxcdn.com: 1
  engerio.sk: 1
  gemius.pl: 3
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  mrf.io: 1
  npttech.com: 1
  strossle.com: 1
 extended:
  ##.piano-pushnotify--hnonline
  ##+js(addEventListener-defuser, beforeunload, ())
  ##+js(abort-current-script, document.createElement, adbDetect)
  ##+js(remove-cookie, /^_?adb/)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
