### ISSUE TITLE
trendyol.com: breakage

### ISSUE THREAD

**Issue by ahmetaa** [uBlockOrigin/uAssets#25875]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.trendyol.com/twist/kapitone-detayli-mont-p-861940604?boutiqueId=61&merchantId=1138&sav=true`

### Category

breakage

### Description

When u-block origin is active, I cannot click on body size selection buttons (below the word `Beden`), which prevents adding product to cart. Once extension is disabled and refreshed (may require shift-refresh), it works. 

This site is a major e-commerce site and it should be white listed.

### Other extensions used

None, I disabled all other extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="586" alt="image" src="https://github.com/user-attachments/assets/f377b7e8-f3af-4fef-b1c2-b887c70cc0d2">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 139780
 cosmetic: 48939
 scriptlet: 22959
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40543-260, 1h.38m Δ
  ublock-badware: 11786-6, 1h.38m Δ
  ublock-privacy: 1397-22, 1h.38m Δ
  ublock-unbreak: 2498-0, 1h.38m Δ
  ublock-quick-fixes: 237-0, 1h.38m Δ
  easylist: 80307-589, 1h.38m Δ
  easyprivacy: 53224-648, 1h.38m Δ
  urlhaus-1: 19810-0, now
  plowe-0: 3542-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 97 ms (selfie)
 maxAssetCacheWait: 24 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=trendyol.com`

@ryanbr

**Comment by Mr-Blondie** [comment]
the problem reappeared

**Comment by stephenhawk8054** [comment]
What issue are you having? Please give exact link and describe the steps to reproduce.

**Comment by stephenhawk8054** [comment]
Test this filter:

```adb
trendyol.com##+js(set, process.env, {})
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by Mr-Blondie** [comment]
> What issue are you having? Please give exact link and describe the steps to reproduce.

Sorry for short info
Problem mentioned in the main topic. Can't click on filters buttons. But I suppose it already fixed. Thank you

**Comment by 96273** [comment]
Rule hides images on the trendyol‑milla.com website.

||cdn.dsmcdn.com/sfx/mergen/ 

`https://www.trendyol-milla.com/sr?q=erkek%20sweatshirt&qt=erkek%20sweatshirt&st=erkek%20sweatshirt&os=1`

**Comment by 96273** [comment]
https://i.ibb.co/tMFszhR0/trendyol.png

The following filter rule breaks the login functionality on trendyol.com, resulting in a generic "Bir hata oluştu" (An error occurred) error message when attempting to log in:

`trendyol.com##+js(remove-cookie, /anonUserId|pid|sid/)`

Whitelisting this rule resolves the issue and allows users to log in successfully:

`trendyol.com#@#+js(remove-cookie, /anonUserId|pid|sid/)`

Browser: Firefox + uBlock Origin
