### ISSUE TITLE
jiocinema.com: ads

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25874]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.jiocinema.com/sports/cricket/india-vs-new-zealand-3rd-test-day-1/4033144?mediaID=4033144`

### Category

ads

### Description

While watching cricket match. During over there is a different type of ads whicH doesn't let you exit or use use other funtion for timing.
Any Indian number will works, there is no subscription.
It doesn't occur everytime.
![Screenshot 2024-11-01 155632](https://github.com/user-attachments/assets/f00f5c6f-3080-4168-abfa-890dbf7a7b97)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 457158
 cosmetic: 211754
 scriptlet: 39350
 html: 2335
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl: 136969-1, 37m
  https://github.com/DandelionSprout/adfilt/raw/refs/heads/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 760-8, 51m
  https://github.com/DandelionSprout/adfilt/raw/refs/heads/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 109826-254, 56m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/BrowseWebsitesWithoutLoggingIn.txt: 461-1, 58m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/LegitimateURLShortener.txt: 2692-76, 59m
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 456-34, 40m
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4236-36, 38m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2129-10, 41m
  adguard-spyware-url: 1764-290, 1h.7m
  adguard-spyware: 96073-5347, 1h.7m
  block-lan: 64-0, 1h.7m
  curben-phishing: 509-8, 1h.7m
  [14 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40805-329, 1h.9m
  ublock-badware: 11788-1385, 1h.9m
  ublock-privacy: 1383-97, 1h.9m
  ublock-unbreak: 2556-0, 2m Δ
  ublock-quick-fixes: 236-12, 1h.9m
  easylist: 80307-26942, 1h.9m
  easyprivacy: 53223-25670, 2m Δ
  urlhaus-1: 19810-233, 1h.9m
  plowe-0: 3542-2612, 1h.9m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6650 ms
 maxAssetCacheWait: 2606 ms
 cacheBackend: indexedDB
 unsuspendAfter: 674 ms
popupPanel:
 blocked: 79
 network:
  jiocinema.com: 43
  adsmoloco.com: 1
  clevertap-prod.com: 3
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  moloco.com: 11
  sentry.io: 14
  voot.com: 4
```
</details>

**Comment by Rachitidk** [comment]
Also it doesn't occur everytime.

**Comment by Rachitidk** [comment]
Hey dev, why no is replying?

**Comment by mapx-** [comment]
> Any Indian number will works

**Comment by mapx-** [comment]
> It doesn't occur everytime.

closing for now. If you can provide steps to reproduce at will, let us know commenting here.

**Comment by Rachitidk** [comment]
Tommorow match will start around 9:30 am IST, after every over ends you will see this maximum time. I will share the recording then. reopen, because I always face this. There is no way to bypass ads because it is integrated, but ads taking control over the screen can be stopped I think.

**Comment by Rachitidk** [comment]
https://github.com/user-attachments/assets/1a67aba4-121b-4479-a590-b5ebc7a41d8d

Reopen now. Look touch is not working while ads.

**Comment by Rachitidk** [comment]
Any update?

**Comment by stephenhawk8054** [comment]
Don't urge. It's an account-locked site that can only be signed in with an Indian phone number, so very few volunteers are able to investigate.

**Comment by Rachitidk** [comment]
Will take time to verify, as there is no cricket match for a while.
There are other sources where ads appear, but I don't know where.

**Comment by Rachitidk** [comment]
Reopen the issue, issue persist.

https://github.com/user-attachments/assets/424774ff-ab4a-4d91-8fce-cd2b24270c43

**Comment by Rachitidk** [comment]
Dev, something reopen this issue.

**Comment by mapx-** [comment]
live streams, the ads are part of the transmission, closing

**Comment by Rachitidk** [comment]
> live streams, the ads are part of the transmission, closing

What about ads taking control over screen for the moment.
