### ISSUE TITLE
17track.net: breakage

### ISSUE THREAD

**Issue by ianamk** [uBlockOrigin/uAssets#25885]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.17track.net/en`

### Category

breakage

### Description

when ublock0 is enabled clicking the login link does not work, disabling ublock restores the website functionality.

### Other extensions used

Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Ant Video downloader	extension	4.18	true	anttoolbar@ant.com
Bing	extension	1.7	true	bing@search.mozilla.org
DownThemAll!	extension	4.13.1	true	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
DuckDuckGo	extension	1.5	true	ddg@search.mozilla.org
Facebook Container	extension	2.3.11	true	@contain-facebook
FastForward	extension	0.2383	true	addon@fastforward.team
Flagfox	extension	6.1.79	true	{1018e4d6-728f-4b20-ad56-37578a4de76b}
Free Download Manager	extension	3.0.64	true	fdm_ffext2@freedownloadmanager.org
Google	extension	1.5	true	google@search.mozilla.org
ImTranslator: Translator, Dictionary, TTS	extension	16.93	true	{9AA46F4F-4DC7-4c06-97AF-5035170634FE}
MEGA	extension	4.2.1	true	firefox@mega.co.nz
Reload in address bar	extension	1.10	true	{e1ed7a80-7c11-4f7e-968b-79b551a0067f}
Return YouTube Dislike	extension	3.0.0.18	true	{762f9885-5a13-4abd-9c77-433dcd38b8fd}
uBlock Origin	extension	1.60.0	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.4	true	wikipedia@search.mozilla.org
Zoom Image	extension	2.7.1	true	{b14f4076-e80d-4baa-8c7d-8c65dfd2519c}
Dark	theme	1.2	true	firefox-compact-dark@mozilla.org
Firefox Alpenglow	theme	1.4	false	firefox-alpenglow@mozilla.org
Light	theme	1.2	false	firefox-compact-light@mozilla.org
System theme — auto	theme	1.3	false	default-theme@mozilla.org

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://imgur.com/c9tr4Bw

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 139736
 cosmetic: 48824
 scriptlet: 21308
 html: 2055
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40802-132, 23m Δ
  ublock-badware: 11773-6, 23m Δ
  ublock-privacy: 1382-22, 23m Δ
  ublock-unbreak: 2552-1, 23m Δ
  ublock-quick-fixes: 236-10, 23m Δ
  easylist: 80185-572, 23m Δ
  easyprivacy: 53221-686, 23m Δ
  urlhaus-1: 19800-0, 23m
  plowe-0: 3542-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 974 ms (selfie)
 maxAssetCacheWait: 163 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  17track.net: 6
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  #@#.ad-slot
```
</details>

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/00ac66d31fa3587af7c22ee8e26520c939710fcb
