### ISSUE TITLE
crates.io: breakage

### ISSUE THREAD

**Issue by abonander** [uBlockOrigin/uAssets#25880]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://crates.io/crates/metrics`

### Category

breakage

### Description

More context here: https://github.com/metrics-rs/metrics/issues/539#issuecomment-2452468431

uBlock Origin is blocking a request because the URL contains `/metrics/metrics` even though it's not in the list of domains that the filter should match. Because the request for the README content fails, crates.io thinks it does not exist and thus says "appears to have no README.md". I'll be reporting that as a bug to crates.io as well.

### Other extensions used

Reddit Enhancement Suite
Firefox Multi-Account Containers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/d5fc9a10-1489-41ba-a272-f093a00d91bb)

![image](https://github.com/user-attachments/assets/19e0a983-3a00-4590-8b55-3904038c3b1e)
![image](https://github.com/user-attachments/assets/3b23cac9-d252-4eb7-bd3e-1028777c56f8)

What SHOULD be shown (after disabling uBlock Origin):
![image](https://github.com/user-attachments/assets/fdd3009f-3e83-492c-8544-106b067e9101)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 139820
 cosmetic: 48938
 scriptlet: 21319
 html: 2055
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40809-132, now
  ublock-badware: 11804-6, now
  ublock-privacy: 1383-22, now
  ublock-unbreak: 2556-1, now
  ublock-quick-fixes: 242-10, now
  easylist: 80340-198, now
  easyprivacy: 53227-63, now
  urlhaus-1: 19800-0, now
  plowe-0: 3542-998, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1234 ms
 maxAssetCacheWait: 268 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  crates.io: 1
```
</details>

**Comment by abonander** [comment]
I thought it could end up matching one of the domains if `static.crates.io` had a `CNAME` record for one of them, but this does not appear to be the case:

```
$ dig static.crates.io

; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> static.crates.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45753
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;static.crates.io.		IN	A

;; ANSWER SECTION:
static.crates.io.	300	IN	CNAME	fastly-static.crates.io.
fastly-static.crates.io. 60	IN	CNAME	dualstack.k.sni.global.fastly.net.
dualstack.k.sni.global.fastly.net. 8 IN	A	151.101.42.137

;; Query time: 125 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Fri Nov 01 12:45:41 PDT 2024
;; MSG SIZE  rcvd: 136

```

**Comment by gorhill** [comment]
Caused by EasyPrivacy's `/metrics/metrics$from=...`.

Need to add `~crates.io` to the list of excluded domains.

cc @ryanbr

**Comment by abonander** [comment]
Oh I see, that's the list of domains to _exclude_, yeah.
