### ISSUE TITLE
alison.com: detection

### ISSUE THREAD

**Issue by ososstar** [uBlockOrigin/uAssets#25888]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://alison.com/topic/learn/131142/understanding-a-workflow`

### Category

detection

### Description

it shows "This page has been blocked by an extension" in take course content box

### Other extensions used

when i disable uBO the issue resolves

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 165716
 cosmetic: 145773
 scriptlet: 45177
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/kbinani/adblock-youtube-ads/master/signed.txt: 16-0, now
  https://raw.githubusercontent.com/thedoggybrad/Frame-Blocker-Filter/main/googleyt-exception.txt: 1-0, now
  https://rawcdn.githack.com/kbinani/adblock-youtube-ads/master/signed.txt: 16-16, 1h.51m
  adguard-generic: 85453-6430, now
  adguard-mobile-app-banners: 5527-1129, now
  adguard-other-annoyances: 14739-319, now
  adguard-popup-overlays: 27929-1217, now
  adguard-widgets: 2742-18, now
  ara-0: 2330-0, now
  easylist-annoyances: 4801-131, now
  easylist-chat: 216-0, now
  easylist-newsletters: 8015-28, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 10-2, never
  easylist: 80329-560, 1h.51m Δ
  easyprivacy: 53226-1575, 1h.51m Δ
  plowe-0: 3543-2, now
  ublock-badware: 11818-6, 1h.51m Δ
  ublock-filters: 40553-703, 1h.51m Δ
  ublock-privacy: 1397-22, 1h.51m Δ
  ublock-quick-fixes: 247-0, 1h.51m Δ
  ublock-unbreak: 2499-2, 1h.51m Δ
  urlhaus-1: 20305-0, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 30 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5752 ms (selfie)
 maxAssetCacheWait: 330 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  adnxs.com: 2
  adsrvr.org: 1
  casalemedia.com: 1
  cloudflareinsights.com: 2
  criteo.com: 3
  criteo.net: 4
  doubleclick.net: 1
  google.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 2
  indexww.com: 1
  intercom.io: 1
  openx.net: 2
  pubmatic.com: 2
  rubiconproject.com: 2
  smartlook.com: 1
  trustpilot.com: 1
  vimeo.com: 1
 extended:
  ##.sticky-ad
  ##.trustpilot-widget
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
