### ISSUE TITLE
yourcountdown.to: nuisance

### ISSUE THREAD

**Issue by gregoryG6440** [uBlockOrigin/uAssets#25884]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://yourcountdown.to/stranger-things`

### Category

nuisance

### Description

Obnoxious birthday buddies banner on every countdown on this website

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 132
filterset (summary):
 network: 141241
 cosmetic: 57637
 scriptlet: 21391
 html: 2056
listset (total-discarded, last-updated):
 default:
  user-filters: 5-1, never
  ublock-filters: 41319-215, 28m Δ
  ublock-badware: 11798-7, 29m Δ
  ublock-privacy: 1384-22, 29m Δ
  ublock-unbreak: 2558-3, 29m Δ
  ublock-quick-fixes: 242-10, 29m Δ
  adguard-mobile: 9942-12, 4m
  easylist: 80335-270, 28m Δ
  easyprivacy: 53225-72, 28m Δ
  urlhaus-1: 19800-0, 4m
  plowe-0: 3542-1072, 4m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1159 ms (selfie)
 maxAssetCacheWait: 78 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  google.be: 1
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  pulsatingmeadow.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot how it looks like?

**Comment by gregoryG6440** [comment]
![Screenshot_20241102_104121_Firefox.jpg](https://github.com/user-attachments/assets/a79cab73-55f1-426d-95bf-b018818a59a6)

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by gregoryG6440** [comment]
I just did a bit of testing with a vpn and the ad popped up when connecting to:
UK, Italy, Poland, Brazil, Belgium and Spain (also without a vpn).
No ad when connecting to Australia, USA, Japan or Ukraine

**Comment by stephenhawk8054** [comment]
I can't reproduce the ads

![image](https://github.com/user-attachments/assets/685649e6-13b4-4e39-926e-abd8c39467d7)
