### ISSUE TITLE
[nsfw] 2028p.com: breakage

### ISSUE THREAD

**Issue by Azuri001** [uBlockOrigin/uAssets#25881]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.2028p.com/watch/27199589/122152272.html`

### Category

breakage

### Description

- website updated recently;
- video player doesn't load now when uBlock origin is enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 102193
 cosmetic: 46146
 scriptlet: 25146
 html: 2318
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  block-lan: 64-0, 4m
  ublock-annoyances: 5923-21, 41m Δ
  CHN-0: 25534-1165, 4m
 default:
  user-filters: 151-14, never
  ublock-filters: 40809-321, 41m Δ
  ublock-badware: 11804-12, 41m Δ
  ublock-privacy: 1383-23, 41m Δ
  ublock-unbreak: 2556-2, 41m Δ
  ublock-quick-fixes: 242-15, 41m Δ
  easylist: 80335-14277, 41m Δ
  urlhaus-1: 19800-0, 4m
  plowe-0: 3542-375, 4m
filterset (user): [array of 151 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 userFiltersTrusted: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1026 ms (selfie)
 maxAssetCacheWait: 75 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  staticfile.org: 4
```
</details>

**Comment by stephenhawk8054** [comment]
The domain `staticfile.org` being blocked in the site belongs to `polyfill.io` who was found responsible for their supply chain attack on many websites: https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

Please contact to the website owner not to use that domain in their website.
