### ISSUE TITLE
getcomics.org: ads

### ISSUE THREAD

**Issue by blechonla** [uBlockOrigin/uAssets#25889]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://getcomics.org/marvel/x-men-x-tinction-agenda-omnibus-vol-1-2024/`

### Category

ads

### Description

![AIWaifuAd](https://github.com/user-attachments/assets/7fe61de7-a872-403b-8c95-5e31eb5871ab)

### Other extensions used

1. Old Reddit Redirect
2. 600% Sound Volume
3. Greasemonkey
4. Bypass Paywalls for Firefox

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![AIWaifuAd](https://github.com/user-attachments/assets/a05ee1f7-94ce-48b6-a3e8-0addc349f015)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 140350
 cosmetic: 48924
 scriptlet: 21321
 html: 2056
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40814-132, 1h.44m Δ
  ublock-badware: 11820-6, 1h.44m Δ
  ublock-privacy: 1383-22, 1h.44m Δ
  ublock-unbreak: 2557-1, 1h.44m Δ
  ublock-quick-fixes: 246-10, 1h.44m Δ
  easylist: 80329-573, 1h.44m Δ
  easyprivacy: 53226-687, 1h.44m Δ
  urlhaus-1: 20305-0, 44m
  plowe-0: 3543-0, now
filterset (user): [empty]
trustedset:
 added: [array of 22 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 756 ms (selfie)
 maxAssetCacheWait: 212 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  cloudflareinsights.com: 1
  current.us: 2
  google.com: 2
  googletagmanager.com: 1
  sunmedia.tv: 1
  whizzco.com: 3
  wp.com: 2
 extended:
  ##.ads_container:not(.text-ad)
```
</details>

**Comment by gorhill** [comment]
Need `getcomics.org##[id^="getco-"]`. This could be fixed in EasyList.

**Comment by gorhill** [comment]
@ryanbr Really need `getcomics.org##[id^="getco-"]`, see <https://github.com/uBlockOrigin/uAssets/issues/26764>.
