### ISSUE TITLE
Malicious domains

### ISSUE THREAD

**Issue by ExtRIELICi** [uBlockOrigin/uAssets#25899]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://7ng6v3lu3c.execute-api.us-east-1.amazonaws.com
https://kra18.com/
```

### Description

Malicious domains, part of a malicious Chrome extension. More info [here](https://gist.github.com/c0m4r/45e15fc1ec13c544393feafca30e74de) and [here](https://palant.info/2024/10/30/the-karma-connection-in-chrome-web-store/).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by Yuki2718** [comment]
I don't think uBO can block requests from other extensions, so blocking them would be pointless.

**Comment by ExtRIELICi** [comment]
[kra18.com is commonly associated with affiliate fraud](https://palant.info/2024/10/30/the-karma-connection-in-chrome-web-store/#affiliate-fraud-functionality), at least from what I understand, so blocking it would be beneficial overall, as it is likely used in other malicious domains and scams as well.

**Comment by Yuki2718** [comment]
Also added `7ng6v3lu3c.execute-api.us-east-1.amazonaws.com` as EL can be used in network-level.

**Comment by stephenhawk8054** [comment]
@Yuki2718 uBOL doesn't have strict-blocked unless specified with `$all` or `$doc`, so I think it's still better to address in our list with type too.

**Comment by Yuki2718** [comment]
> uBOL doesn't have strict-blocked unless specified with `$all` or `$doc`, so I think it's still better to address in our list with type too.

Didn't know that, but I doubt this is intended behavior. Or is it?
