### ISSUE TITLE
toddpartneranimal.com: detection

### ISSUE THREAD

**Issue by samuelplankel** [uBlockOrigin/uAssets#25894]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://toddpartneranimal.com/cm2fm5b6ucj3`

### Category

detection

### Description

VOE detects uBlock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 133
filterset (summary):
 network: 140591
 cosmetic: 48928
 scriptlet: 21326
 html: 2059
listset (total-discarded, last-updated):
 added:
  https://work.ink/adblock-whitelist.txt: 0-0, never
 default:
  user-filters: 1-0, never
  ublock-filters: 40824-133, now
  ublock-badware: 11820-6, now
  ublock-privacy: 1390-22, now
  ublock-unbreak: 2557-1, now
  ublock-quick-fixes: 242-10, 12m
  easylist: 80351-199, now
  easyprivacy: 53226-64, now
  urlhaus-1: 20525-0, now
  plowe-0: 3543-999, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2492 ms (selfie)
 maxAssetCacheWait: 193 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  ads-twitter.com: 1
  imasdk.googleapis.com: 2
  sharethis.com: 3
  sinisterdrippingcircuit.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Already fixed https://github.com/uBlockOrigin/uAssets/commit/43e61f352f10c7b368bef10b762512902a8c4ddf
