### ISSUE TITLE
novelasportuguesas.online: detection

### ISSUE THREAD

**Issue by Susymei** [uBlockOrigin/uAssets#25895]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://novelasportuguesas.online/serie/chiquititas/`

### Category

detection

### Description

Voe detects Ublock Origin again 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 159007
 cosmetic: 55550
 scriptlet: 21521
 html: 2058
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40822-133, now
  ublock-badware: 11820-6, now
  ublock-privacy: 1383-22, now
  ublock-unbreak: 2557-1, now
  ublock-quick-fixes: 250-10, now
  easylist: 80351-199, now
  easyprivacy: 53226-63, now
  urlhaus-1: 20525-0, now
  plowe-0: 3543-999, now
  FRA-0: 25704-388, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 745 ms
 maxAssetCacheWait: 257 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  acscdn.com: 2
  ads-twitter.com: 2
  amung.us: 1
  daly2024.com: 2
  dalysv.com: 2
  googletagmanager.com: 2
  hlswish.com: 2
  imasdk.googleapis.com: 2
  sinisterdrippingcircuit.com: 1
  vidhideplus.com: 2
  wp.com: 2
  yandex.ru: 2
 extended:
  ##.content-ads
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by JobcenterTycoon** [comment]
Its already fixed. Run https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=1 to force update the filterlist.
