### ISSUE TITLE
es.pinterest.com: detection

### ISSUE THREAD

**Issue by Serph** [uBlockOrigin/uAssets#25890]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://es.pinterest.com/`

### Category

detection

### Description

the website detects ublock origin

### Other extensions used

decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 140571
 cosmetic: 53124
 scriptlet: 21323
 html: 2056
listset (total-discarded, last-updated):
 removed:
  spa-0: null
  spa-1: null
 added:
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4236-36, now
 default:
  user-filters: 0-0, never
  ublock-filters: 40814-132, 1h.22m Δ
  ublock-badware: 11820-6, now
  ublock-privacy: 1383-22, 21m Δ
  ublock-unbreak: 2557-1, 1h.22m Δ
  ublock-quick-fixes: 249-10, now
  easylist: 80329-198, 1h.22m Δ
  easyprivacy: 53226-63, 1h.22m Δ
  urlhaus-1: 20525-0, now
  plowe-0: 3543-999, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1423 ms
 maxAssetCacheWait: 530 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  pinterest.com: 4
  cedexis.com: 1
  google.com: 1
 extended:
  ##div[data-grid-item]:has([data-test-pin-id] [data-test-id^="one…
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25614
