### ISSUE TITLE
geeksforgeeks.org: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#25897]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.geeksforgeeks.org/open-systems-interconnection-model-osi/`

### Category

ads

### Description

ads on right side of screen

### Other extensions used

FDM extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/b53563f2-2dd3-497a-8741-6365dc4b960d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 253984
 cosmetic: 224120
 scriptlet: 57127
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85508-7462, now
  adguard-mobile: 9943-110, now
  adguard-spyware-url: 1764-130, now
  adguard-spyware: 96080-23217, now
  block-lan: 64-0, now
  curben-phishing: 543-0, now
  adguard-cookies: 32353-97, now
  ublock-cookies-adguard: 1862-9, now
  fanboy-cookiemonster: 52210-4119, now
  ublock-cookies-easylist: 1862-1862, now
  adguard-popup-overlays: 27933-2176, now
  adguard-mobile-app-banners: 5529-1130, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40583-131, now
  ublock-badware: 11818-7, now
  ublock-privacy: 1405-23, now
  ublock-unbreak: 2499-3, now
  ublock-quick-fixes: 239-8, now
  easylist: 80359-888, 39m Δ
  easyprivacy: 53226-961, 39m Δ
  urlhaus-1: 21170-0, now
  plowe-0: 3543-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 355 ms (selfie)
 maxAssetCacheWait: 185 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  geeksforgeeks.org: 4
  clarity.ms: 1
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 2
  pubmatic.com: 1
 extended:
  ###openInApp-modal
  ##.cookie-consent
  ###text-15
  ###text-16
  ##div[id^="GFG_AD_"]
  ##div[id^="AP_"]
  ##div.cookie-consent
  ##+js(no-setTimeout-if, onscroll, 5500)
  ##+js(no-setTimeout-if, login, 5000)
  ##+js(abort-current-script, showAdblockerModal)
  ##+js(no-setTimeout-if, .login-modal-btn:eq(0))
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. You can use this as your custom filter:

```adb
geeksforgeeks.org##.OINTechPromoRightBarBanner
```
