### ISSUE TITLE
fernsehserien.de: ads

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uAssets#25891]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.fernsehserien.de/xena/episodenguide`

### Category

ads

### Description

there where annoying loading animations at every ad locations, i added this to get rid of them

! Nov 2, 2024 https://www.fernsehserien.de
www.fernsehserien.de##.werbemittel

### Other extensions used

i still dont care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 128
filterset (summary):
 network: 144319
 cosmetic: 124955
 scriptlet: 26380
 html: 2058
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103162-18197, now
  fanboy-cookiemonster: 52202-52202, now
  fanboy-social: 16769-16769, now
 default:
  user-filters: 15-0, never
  ublock-filters: 40822-152, 1h.24m Δ
  ublock-badware: 11820-6, 1h.24m Δ
  ublock-privacy: 1390-23, 1h.24m Δ
  ublock-unbreak: 2557-5, 1h.24m Δ
  ublock-quick-fixes: 253-10, 1h.24m Δ
  easylist: 80349-220, 1h.24m Δ
  easyprivacy: 53226-197, 1h.24m Δ
  urlhaus-1: 20525-0, now
  plowe-0: 3543-999, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 863 ms (selfie)
 maxAssetCacheWait: 298 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  consentmanager.net: 2
  imfernsehen.de: 2
 extended:
  ##.sharebar
  ##.werbemittel
  ##+js(abort-on-property-read, googlefc)
```
</details>

**Comment by mapx-** [comment]
german site, enable [EasyList Germany](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=DEU-0)
