### ISSUE TITLE
grammarist.com

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#259]
### URL(s) where the issue occurs
`http://grammarist.com`

### Describe the issue

`grammarist.com` uses `iframe[src="about:blank"]` to reinsert ads.

### Screenshot(s)

![grammn](https://cloud.githubusercontent.com/assets/16838044/21738964/022eb3ca-d48f-11e6-9515-3529ef408c7a.JPG)

### Versions

- Browser/version: Chrome 55
- uBlock Origin version: 1.10.4

### Settings

- default

### Notes
The filter
`grammarist.com##script:inject(abort-on-property-write.js, upManager)`
solves the issue.

**Comment by okiehsch** [comment]
**Off-Topic**

@gorhill 
Regarding the E-Mail I received, sorry if I sound clueless, but I wasn't expecting this, so
what would this actually mean for me?
If you want to answer you can send it to a junk e-mail account of mine
`gitjunk@web.de`

**Comment by gorhill** [comment]
In settings I added you as collaborator so you can commit filters, GitHub is probably asking you if you accept.

**Comment by okiehsch** [comment]
I gathered as much, but would I be expected to respond to issue reports by third users, or would this simply mean that I can commit filters when I see fit?

**Comment by gorhill** [comment]
To be clear there are no expectations -- I just offer you to commit directly whatever voluntary contributions you chose to make rather than have it done through me. From what I've seen you are thorough with the filter solutions you come up with and so I am fine with you committing them directly yourself.
