### ISSUE TITLE
program.smyk.com: breakage

### ISSUE THREAD

**Issue by AlecClaire** [uBlockOrigin/uAssets#25905]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://program.smyk.com/program-lojalnosciowy/`

### Category

breakage

### Description

Most of the page that is available without uBlock (different browser - bare Edge, no add-ons) isn't even visible in FireFox with uBlock.

### Other extensions used

Download Helper.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 142504
 cosmetic: 57210
 scriptlet: 21552
 html: 2075
listset (total-discarded, last-updated):
 added:
  POL-0: 8766-44, now
  POL-2: 1283-48, now
 default:
  user-filters: 2-0, never
  ublock-filters: 40862-133, now
  ublock-badware: 11846-6, now
  ublock-privacy: 1391-22, now
  ublock-unbreak: 2557-1, now
  ublock-quick-fixes: 245-6, now
  easylist: 80381-199, now
  easyprivacy: 53227-64, now
  urlhaus-1: 20905-0, now
  plowe-0: 3543-999, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 714 ms
 maxAssetCacheWait: 479 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  nd0.pl: 1
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce with default settings/lists + Polish lists.

You have two custom filters, did you check whether these are the cause?

**Comment by AlecClaire** [comment]
1. I don't know any other custom list despite the Polish one.

2. I've unchecked the Polish list and saved settings. It worked. I've
reached the Polish list again, saved again and.. it still works. Even after
browser restart.
So.. I don't know how it works. I guess my problem is solved but there's
some problem that this happens I guess.

Anyways, thank you for contacting me. Your suggestions helped in resolving
my issue.

Cheers

pon., 4 lis 2024 o 00:09 Raymond Hill ***@***.***> napisał(a):
