### ISSUE TITLE
bihon.ro: ads

### ISSUE THREAD

**Issue by LeventeCornea** [uBlockOrigin/uAssets#25904]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bihon.ro/`

### Category

ads

### Description

The user goes to the website https://www.bihon.ro, the adblocking extension uBlock Origin Lite having enabled on the respective, but after scrolling down one ad is still being shown.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.10.28.929
mode: basic / basic
rulesets:
 default
```

**Comment by mapx-** [comment]
- where are the ads ? provide a screenshot indicating them
- did you enable the romanian list ? `Romanian Ad (ROad) Block List Light`

**Comment by gorhill** [comment]
@mapx-, from <https://github.com/uBlockOrigin/uBOL-home/issues/243>:

![Screenshot 2024-11-03 175213](https://github.com/user-attachments/assets/e933f197-eb6a-4191-8fbe-a4f1d403b39f)

**Comment by LeventeCornea** [comment]
I am new to Github. Please, tell me is this a valid bug for it to be reported?

**Comment by mapx-** [comment]
yes. Just tell me: is the romanian list enabled in uBOL ? (the romanina list will have the needed filter)

**Comment by gorhill** [comment]
This seems to work:

    bihon.ro##.et_pb_code:has(> div > a > img)

**Comment by mapx-** [comment]
@LeventeCornea added to the romanian list
It will be active in the next release of uBOL

**Comment by LeventeCornea** [comment]
@mapx- The Romanian list is enabled. What do you mean by "It will be active in the next release of uBOL"?

**Comment by mapx-** [comment]
uBOL is manifest v3, new filters added to various lists are not immediately available. A new version of the extension must be published in the play store.
