### ISSUE TITLE
sfl.gl: detection/Anti-Adblock

### ISSUE THREAD

**Issue by FLAV1N** [uBlockOrigin/uAssets#25900]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sfl.gl/wocasOxD`

### Category

detection

### Description

the link itself will redirect me to random page on `https://app.khaddavi.net/aplikasi-untuk-mencari-dan-memesan-jasa-profesional-temukan-layanan-terbaik-untuk-berbagai-kebutuhan/`
which then detected me using adblock. 

### Other extensions used

none, already disabled all other extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot1](https://github.com/user-attachments/assets/f5ac3fc8-47da-4c2e-890f-583707e63660)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 240318
 cosmetic: 147096
 scriptlet: 43930
 html: 2070
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85527-4251, 3m
  adguard-mobile: 9943-60, 3m
  adguard-spyware: 96080-24052, 3m
  adguard-popup-overlays: 27934-1406, 5m
  adguard-mobile-app-banners: 5529-32, 5m
  adguard-other-annoyances: 14742-351, 5m
  adguard-widgets: 2744-18, 5m
 default:
  user-filters: 63-8, never
  ublock-filters: 40841-133, 3m
  ublock-badware: 11846-6, 3m
  ublock-privacy: 1391-22, 3m
  ublock-unbreak: 2557-1, 3m
  ublock-quick-fixes: 238-6, 3m
  easylist: 80374-2257, 3m
  easyprivacy: 53226-162, 3m
  urlhaus-1: 20905-0, 3m
  plowe-0: 3543-1089, 3m
  IDN-0: 10195-74, 3m
filterset (user): [array of 63 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1684 ms (selfie)
 maxAssetCacheWait: 138 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

 > - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

Comment in https://github.com/uBlockOrigin/uAssets/discussions/17361
