### ISSUE TITLE
crackwatcher.com: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#25903]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://crackwatcher.com/`

### Category

ads

### Description

There's an ad to Kinguin, it says to use their code.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/b804e21b-0f95-4e2d-bbd4-0f4e86af2d4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 141021
 cosmetic: 48950
 scriptlet: 22992
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40583-131, now
  ublock-badware: 11844-6, now
  ublock-privacy: 1405-23, now
  ublock-unbreak: 2499-1, now
  ublock-quick-fixes: 244-8, now
  easylist: 80379-590, now
  easyprivacy: 53226-765, now
  urlhaus-1: 20905-0, now
  plowe-0: 3543-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 546 ms
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  optad360.io: 2
```
</details>

**Comment by mapx-** [comment]
```
crackwatcher.com##[href^="https://www.kinguin.net"]
crackwatcher.com##[style="background:none !important;"]:has([href^="https://www.kinguin.net"])
```

the first one for home page, the second for the specific pages

**Comment by abiogenetic** [comment]
try now
