### ISSUE TITLE
fomo.id: ads

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#25902]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fomo.id/beranda`

### Category

ads

### Description

The site contains sponsored posts, visible upon scrolling down far enough.

Information regarding the sponsored post is received via different fetch request endpoints, depending on current site path. Some of these paths might require an account to access.

Suggested filter:
`fomo.id##+js(json-prune-fetch-response, data.[-].inner.ctaCopy)`

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.1rc5
Firefox: 132
filterset (summary):
 network: 141024
 cosmetic: 48949
 scriptlet: 21328
 html: 2064
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 40840-133, now
  ublock-badware: 11846-6, now
  ublock-privacy: 1402-22, now
  ublock-unbreak: 2557-1, now
  ublock-quick-fixes: 238-6, now
  easylist: 80379-199, now
  easyprivacy: 53226-64, now
  urlhaus-1: 20905-0, now
  plowe-0: 3543-999, now
filterset (user): [array of 31 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 autoCommentFilterTemplate: {{isodate}} {{origin}}
 filterAuthorMode: true
supportStats:
 allReadyAfter: 251 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
I think it's better to specify the URLs when using `json-prune-fetch/xhr-response`, or the scriptlet will go through all `fetch/XHR` connections and can potentially slow down the page if there are too many connections.

**Comment by stephenhawk8054** [comment]
@partingscientist Can you share the full URLs of those links?

**Comment by stephenhawk8054** [comment]
Thanks. I think this could cover more cases:

```adb
fomo.id##+js(json-prune-fetch-response, data.[-].inner.ctaCopy, , propsToMatch, ?page=)
```
