### ISSUE TITLE
Potential spam/badware domains

### ISSUE THREAD

**Issue by ExtRIELICi** [uBlockOrigin/uAssets#25906]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
jyfrsjdkkhue.com
cognatesyringe.com
blackoutarchertender.com
astronomyfitmisguided.com
chesssorrydescend.com
trkucibqy.com
bertasxt.com
secrity2redline.com
ucureo.com
```

### Description

Most of them redirect to legit websites like `google.com`, similarly to a lot of phishing domains. A mobile user agent might be necessary.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
What are the contents of these sites? Please we don't address "potential" domains here. Give us exact full links that can reproduce the issue. Don't throw multiple "potential" domains like this.

**Comment by garry-ut99** [comment]
They were reported recently as spam sites, related issues (on which the OP most likely based his current report):
- https://github.com/AdguardTeam/AdguardFilters/issues/191963 (this thread contains steps to reproduce)
- https://github.com/hagezi/dns-blocklists/issues/4170 (most likely OP copied & pasted domains from the first comment, as they are identical)
