### ISSUE TITLE
diskpart.com: nuisance

### ISSUE THREAD

**Issue by cybergon** [uBlockOrigin/uAssets#25908]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.diskpart.com/help/make-bootable-cd-wizard.html`

### Category

ads

### Description

Overlay that says HURRY! ONLY 24 HOURS LEFT!

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 141120
 cosmetic: 48956
 scriptlet: 21345
 html: 2064
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 40862-139, 35m
  ublock-badware: 11846-6, 35m
  ublock-privacy: 1391-22, 35m
  ublock-unbreak: 2557-1, 35m
  ublock-quick-fixes: 245-0, now
  easylist: 80381-199, 35m
  easyprivacy: 53227-64, 35m
  urlhaus-1: 21000-0, 35m
  plowe-0: 3543-999, 35m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 785 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  clarity.ms: 1
  doubleclick.net: 2
  google.com: 2
  googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25907#issuecomment-2453701097
