### ISSUE TITLE
graveyardkeeper.fandom.com: breakage

### ISSUE THREAD

**Issue by maettle** [uBlockOrigin/uAssets#25901]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

```
https://graveyardkeeper.fandom.com/wiki/Clotho?so=search
https://graveyardkeeper.fandom.com/wiki/Quality_fertilizer_II
https://vampire-survivors.fandom.com/wiki/PowerUps
https://graveyardkeeper.fandom.com/wiki/Clotho
```

### Category

breakage

### Description

images do not load in Firefox 132.0 with disabled Firefox anti tracking and deleted cookies; happens on every fandom.com subpage

### Other extensions used

Kee

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/user-attachments/assets/1fc96bf7-6409-4932-b17e-7818077c86d2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 241373
 cosmetic: 157873
 scriptlet: 45299
 html: 2063
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1063-0, never
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-0, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25840-4, never
  adguard-generic: 85527-6322, now
  fanboy-cookiemonster: 52374-9449, 6m
  adguard-spyware: 96080-23963, now
 default:
  user-filters: 31-0, never
  ublock-filters: 40841-133, now
  ublock-badware: 11846-9, now
  ublock-privacy: 1391-22, now
  ublock-unbreak: 2557-1, now
  easylist: 80379-200, now
  easyprivacy: 53226-67, now
  DEU-0: 7780-40, now
  urlhaus-1: 20905-0, now
filterset (user): [array of 31 redacted]
trustedset:
 added: [array of 51 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 189 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 192
 network:
  3lift.com: 5
  ad.gt: 6
  adnxs.com: 8
  amazon-adsystem.com: 3
  amplitude.com: 1
  casalemedia.com: 4
  doubleclick.net: 5
  doubleverify.com: 3
  fastly-insights.com: 6
  googletagmanager.com: 3
  imrworldwide.com: 2
  media.net: 4
  nocookie.net: 10
  pubmatic.com: 5
  quantserve.com: 3
  rubiconproject.com: 11
  seedtag.com: 4
  servenobid.com: 5
  the-ozone-project.com: 4
  wikia-services.com: 100
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.bottom-ads-container
  ##.ot-sdk-show-settings
  ##.gpt-ad
  ##.hidead
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.advertisement-label
  ###featured-video__player-container
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
  ##+js(json-prune, sponsored)
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

Your configuration is heavily customized, you will have to investigate on your side what customization is causing your issue. As per your troubleshooting information, you didn't _really_ follow these steps:

> - [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
