### ISSUE TITLE
spiegel.de: nuisance

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#25911]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.spiegel.de/netzwelt/web/passkeys-fuer-wen-sich-der-umstieg-auf-die-passwort-alternative-bei-amazon-paypal-und-co-lohnt-a-69d9b50c-e8ec-4641-aa38-d8224726d2c5`

### Category

nuisance

### Description

Cookie banner

### Other extensions used

- Bitwarden
- Dark Reader
- Gumbo
- Return Youtube Dislike
- SponsorBlock
- Violentmonkey (no scripts on this site)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/user-attachments/assets/e6915062-f23d-4b94-b902-12cfefd23e39)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 151789
 cosmetic: 132378
 scriptlet: 31545
 html: 2322
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2693-0, 55m
  adguard-spyware-url: 1764-248, 55m
  fanboy-cookiemonster: 52185-194, 55m
  ublock-cookies-easylist: 1879-5, 55m
  fanboy-social: 16781-11, 55m
  easylist-annoyances: 4804-45, 55m
  easylist-chat: 216-0, 55m
  easylist-newsletters: 8041-39, 55m
  easylist-notifications: 3454-162, 55m
  ublock-annoyances: 5924-82, 55m
 default:
  user-filters: 0-0, never
  ublock-filters: 40822-133, 56m
  ublock-badware: 11820-6, 56m
  ublock-privacy: 1390-71, 56m
  ublock-unbreak: 2557-1, 56m
  ublock-quick-fixes: 250-10, 56m
  easylist: 80363-199, 56m
  easyprivacy: 53227-64, 34m Δ
  urlhaus-1: 21000-0, 56m
  plowe-0: 3543-999, 56m
  DEU-0: 7780-42, 57m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 211 ms (selfie)
 maxAssetCacheWait: 82 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  spiegel.de: 3
  adobedtm.com: 1
 extended:
  ##[data-area="vouchers"]
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(trusted-click-element, button[title^="Consent"])
  ##+js(trusted-set-cookie, consentUUID, 4de1a7f3-4c2d-4f4e-9d18-b…
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, enable `EasyList/uBO – Cookie Notices`, test again

**Comment by B1ack3ye** [comment]
> reset uBO to defaults, enable `EasyList/uBO – Cookie Notices`, test again

cookie notice still pops up

**Comment by mapx-** [comment]
test

`spiegel.de##+js(trusted-click-element, button[title^="Einwilligen"])`

be sure `Allow custom filters requiring trust` is enabled (in "my filters")

**Comment by B1ack3ye** [comment]
> test
> 
> ```
> spiegel.de##+js(trusted-click-element, button[title^="Einwilligen"])
> ```
> 
> be sure `Allow custom filters requiring trust` is enabled (in "my filters")

Works, thanks!
