### ISSUE TITLE
animeseries.so: breakage

### ISSUE THREAD

**Issue by CJRodgers2001** [uBlockOrigin/uAssets#25915]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://animeseries.so/`

### Category

breakage

### Description

Website shows  

**Content blocked
Please turn off your ad blocker.**

when uBO Lite is running with any level of filtering. Setting uBO Lite to 'No Filtering' instead gives the message

**No Sponsors
animeseries.so currently does not have any sponsors for you.**

### Other extensions used

Dark Reader, EPUBReader, 7TV, BetterTTV, Better PathofExile Trading, Chrome Remote Desktop, OldTweetDeck, Picarto Notifier, Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/982cfd03-0f0f-46e3-81e2-8039178f7585)
![image](https://github.com/user-attachments/assets/1fb85166-21e9-4da9-8f29-fbaa42de37e9)
![image](https://github.com/user-attachments/assets/12abb792-487f-4bc2-b73f-c188d58e6634)

</details>

### Configuration

```yaml
version: uBOL 2024.10.28.929
mode: optimal / optimal
rulesets:
 default
 annoyances-widgets
 annoyances-social
 adguard-spyware-url
```

**Comment by stephenhawk8054** [comment]
It's a parked domain.
