### ISSUE TITLE
animeseries.so: detection

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [uBlockOrigin/uAssets#25918]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://animeseries.so/`

### Category

detection

### Description

large center message saying: "Content blocked
Please turn off your ad blocker."

built in sources will load a black page
adding easylist will show the block message

### Other extensions used

no-script (shows nothing blocked)

i did try disabling DNS filters at my router, maybe i did it wrong?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241104_144446](https://github.com/user-attachments/assets/a6e85b12-7366-42d5-b044-07dfadf004ef)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 133
filterset (summary):
 network: 137915
 cosmetic: 53129
 scriptlet: 21337
 html: 2064
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4236-36, 1h.30m
 default:
  user-filters: 0-0, never
  ublock-filters: 40861-133, now
  ublock-badware: 11901-6, now
  ublock-privacy: 1393-22, now
  ublock-unbreak: 2558-1, now
  ublock-quick-fixes: 239-6, now
  easylist: 76998-197, now
  easyprivacy: 53227-64, now
  urlhaus-1: 21095-0, 1h.29m
  plowe-0: 3543-1000, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 728 ms (selfie)
 maxAssetCacheWait: 78 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  google.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues/25915#issuecomment-2455018670
