### ISSUE TITLE
multimovies.bond: ads

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#25923]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://multimovies.bond/`

### Category

ads

### Description

Banner ads

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 131
filterset (summary):
 network: 496607
 cosmetic: 219603
 scriptlet: 39102
 html: 2348
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl: 135333-189, 1h.9m
  https://divested.dev/blocklists/Fingerprinting.ubl: 66-1, now
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1083-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-3, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 109828-243, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2687-2, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 456-34, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 85986-39643, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4236-36, now
  adguard-spyware-url: 1764-248, now
  curben-phishing: 635-384, now
  fanboy-cookiemonster: 52188-206, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 13-1, never
  ublock-filters: 41383-134, now
  ublock-badware: 11975-1455, now
  ublock-privacy: 1397-101, now
  ublock-unbreak: 2560-3, now
  ublock-quick-fixes: 239-8, 1h.10m Δ
  adguard-mobile: 9946-764, now
  easylist: 77142-27098, now
  easyprivacy: 53232-9545, now
  urlhaus-1: 20990-284, now
  plowe-0: 3543-2966, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
 removed:
  no-large-media: behind-the-scene false
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 suspendUntilListsAreLoaded: false
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1368 ms (selfie)
 maxAssetCacheWait: 1011 ms
 cacheBackend: indexedDB
 unsuspendAfter: 286 ms
popupPanel:
 blocked: 7
 network:
  comparepoisonous.com: 5
  google-analytics.com: 1
  googletagmanager.com: 1
 extended:
  ##.module_home_ads
```
</details>

**Comment by mapx-** [comment]
test

`multimovies.bond##.SH-Ads`

if you get other ads provide a screenshot showing them

**Comment by Rachitidk** [comment]
![1000111777](https://github.com/user-attachments/assets/10ce428e-e6e4-4284-93c8-00a3f2217f9a)
It's this also ads (not a self promotion), the telegram channel contains ads.

**Comment by mapx-** [comment]
- updated above
- in your next issues provide all the necessary info to identify correctly all the ads

**Comment by Rachitidk** [comment]
Ok

> * updated above
> 
>     * in your next issues provide all the necessary info to identify correctly all the ads
