### ISSUE TITLE
rutube.ru: nuisance

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#25926]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://2x2tv.ru/`

### Category

nuisance

### Description

The Rutube player on third-party sites starts automatically and at maximum volume. 

Example: `https://2x2tv.ru/`

Please add: `rutube.ru##+js(trusted-click-element, #app > #raichuLoaderTemplate [aria-label^="Остановить"])`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2x2](https://github.com/user-attachments/assets/a5fa10f5-4fb7-4a7d-a1a9-0f2a667bba7e)

</details>

### Configuration

<details>

uBlock Origin 1.60.1rc5 default + RU AdList + uBlock filters – Annoyances
FF 115.17.0esr

</details>

**Comment by dimisa-RUAdList** [comment]
Please replace with: `rutube.ru##+js(trusted-click-element, #app > [data-testid="embed-wrapper"] [aria-label*="становить"])`

**Comment by dimisa-RUAdList** [comment]
@mapx-

**Comment by mapx-** [comment]
Could you create a PR? I'm on phone

**Comment by dimisa-RUAdList** [comment]
Please remove this rule. It turns out that `trusted-click-element` doesn't always work perfectly. In some cases, when this player's frame is embedded without the autoplay feature, `trusted-click-element` stops playback after the user launches it.

Instead of the rule being removed, I added the following to RU AdList: `rutube.ru##+js(json-prune-fetch-response, appearance.auto_start, , propsToMatch, 2x2tv.ru)`

https://github.com/easylist/ruadlist/commit/ebe7eae92563d026525fc3be8e398731818ac9a0

Unfortunately, the new rule requires specifying each domain where it should work. I'm looking for a way to use a regular expression so that the rule works in all cases where the rutube.ru frame is embedded, but not on rutube.ru itself.

This means the rule shouldn't work, for example, here: `https://rutube.ru/video/d637fed365175b47a40fb4f632686c0a/`

I'd appreciate any ideas.

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList The video in the above link does not play due to detecting me as using VPN. Do you know any other sites that have the same issue?

**Comment by dimisa-RUAdList** [comment]
`https://tnt-online.ru/live`

**Comment by stephenhawk8054** [comment]
I have no idea what I'm supposed to look at here:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/8609798a-d82d-4e67-b943-1d5a7d98fbb6" />

</details>

**Comment by dimisa-RUAdList** [comment]
Well, they're talking about geoblocking here. Try using AdGuard VPN and selecting Finland.

**Comment by stephenhawk8054** [comment]
Looks like all videos on `rutube.ru` have `video_balancer.default` in `/api/play` request while the ones embedded do not?

**Comment by dimisa-RUAdList** [comment]
Yes, that's right. All embedded videos have `video_balancer: {}`. How can this be used to adapt the rule?

**Edit**
It seems to work like this: `rutube.ru##+js(json-prune-fetch-response, appearance.auto_start, , stackToMatch, !rutube.ru/video)`

https://github.com/easylist/ruadlist/commit/4c2d171e998eda3e87583160a0113d4ef4f6dfe8

**Comment by stephenhawk8054** [comment]
Yeah, `stackToMatch` is fine.

**Comment by dimisa-RUAdList** [comment]
Thanks for your help! I didn't have enough discussion to find a solution.

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList uBO now also supports [JSONPath](https://www.rfc-editor.org/rfc/rfc9535.html) via `json-edit` scriptlets so you can also use some scriptlets like:

```adb
rutube.ru##+js(json-edit-fetch-response, [?.video_balancer==={}].appearance.auto_start, propsToMatch, /api/play)
```

---

Hopefully when the [caching issue with scriptlets for URL path](https://github.com/uBlockOrigin/uBlock-issues/discussions/1755#discussioncomment-13359428) is addressed, we can use this scriptlet:

```adb
rutube.ru/play/embed/##+js(json-prune-fetch-response, appearance.auto_start, , propsToMatch, /api/play)
```

cc @gorhill We have another case that can benefit from URL path for scriptlets. Need Finland IP:

```yml
https://tnt-online.ru/live
https://rutube.ru/video/d637fed365175b47a40fb4f632686c0a/
```

He wants to use the scriptlet on `rutube.ru/play/embed/` path only, not `rutube.ru/video/`

**Comment by dimisa-RUAdList** [comment]
Yes, the simplest and most logical solution would be to use URL paths for scriptlets. It's a shame it doesn't work as intended yet.

As for `json-edit-fetch-response` scriptlet , I don't see a description of its syntax in [Resources Library](https://github.com/gorhill/uBlock/wiki/Resources-Library), but rule `rutube.ru##+js(json-edit-fetch-response, [?.video_balancer==={}].appearance.auto_start, propsToMatch, /api/play)` works on `rutube.ru/video/`, even though it shouldn't.

**Comment by mapx-** [comment]
[json-edit-related scriptlets](https://github.com/gorhill/uBlock/commit/87e0434c90eaff27a5b6eabf6426537e2f7a1643)

**Comment by stephenhawk8054** [comment]
> rule rutube.ru##+js(json-edit-fetch-response, [?.video_balancer==={}].appearance.auto_start, propsToMatch, /api/play) works on rutube.ru/video/, even though it shouldn't.

Hmm... I'm not at my computer now. I'll check it later.

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, what is the syntax of jsonpath to check a value of a key contains some strings?

---

Oh nvm, it's `^=` and similar: https://github.com/gorhill/uBlock/blob/master/src/js/jsonpath.js

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList I think this works if using jsonpath approach

```adb
rutube.ru##+js(json-edit-fetch-response, $[?!.video_balancer.default].appearance.auto_start, propsToMatch, /api/play)
```

They are new scriptlets so there are no documentations for it yet. JSONPath is quite complicated so I don't know how to write documentations for it either honestly.

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
Yes, that works as it should. It seems like it just needed a negation `?!`, because it works even like this: 

`rutube.ru##+js(json-edit-fetch-response, [?!.video_balancer.default].appearance.auto_start, propsToMatch, /api/play)`

But for now I will leave the current rule, its logic is the easiest to understand.
