### ISSUE TITLE
shahid.mbc.net: detection

### ISSUE THREAD

**Issue by oldhunter22** [uBlockOrigin/uAssets#25922]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://shahid.mbc.net/en/player/episodes/Asateer-Future%E2%80%99s-Folktales-season-2-episode-1/id-1038818`

### Category

detection

### Description

It detects that I use an adblocker and prevents me from watching the video.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1089" alt="Capture" src="https://github.com/user-attachments/assets/4ec0fa32-c900-4ec9-b016-4da97528840d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 137951
 cosmetic: 48932
 scriptlet: 21348
 html: 2065
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40870-133, 12m Δ
  ublock-badware: 11923-6, 12m Δ
  ublock-privacy: 1399-22, 12m Δ
  ublock-unbreak: 2558-1, 12m Δ
  ublock-quick-fixes: 239-6, 12m Δ
  easylist: 77113-198, 12m Δ
  easyprivacy: 53232-64, 12m Δ
  urlhaus-1: 20990-0, 7m
  plowe-0: 3543-1000, 7m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 142 ms (selfie)
 maxAssetCacheWait: 46 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 99
 network:
  mbc.net: 1
  bitmovin.com: 6
  bugsnag.com: 8
  crwdcntrl.net: 1
  d2r1yp2w7bby2u.cloudfront.net: 1
  doubleclick.net: 6
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  mparticle.com: 71
  npaw.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like the website needs a subscribed account? Do you know any free links that have the same issue?

**Comment by oldhunter22** [comment]
> Looks like the website needs a subscribed account? Do you know any free links that have the same issue?

No, it doesn't need a subscription. If you disable uBlock, it will play the video, but with ads.

**Comment by stephenhawk8054** [comment]
When I access your link even without any extension, I see this:

![image](https://github.com/user-attachments/assets/a547cdcf-b7f5-44bd-a0cd-8a74201352f0)

**Comment by oldhunter22** [comment]
> When I access your link even without any extensions, I see this:
> 
> ![image](https://private-user-images.githubusercontent.com/66517106/383001374-a547cdcf-b7f5-44bd-a0cd-8a74201352f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Nzk1MzMsIm5iZiI6MTczMDc3OTIzMywicGF0aCI6Ii82NjUxNzEwNi8zODMwMDEzNzQtYTU0N2NkY2YtYjdmNS00NGJkLWEwY2QtOGE3NDIwMTM1MmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA0MDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYmU2Njg4ZjdmY2IxNWJmOTFiNWNmM2JlNWFiNjBkYWFlZTdlYWI4ODQ0ZTJiN2JjYjg4ZDM2YmYxMzgzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1pyxrvELRYKmvOSydSL_Olfy-DzH1XSrlrHvKrYGtok)

try this.

It seems this site has different free content depending on your country.

**Comment by oldhunter22** [comment]
> When I access your link even without any extensions, I see this:
> 
> ![image](https://private-user-images.githubusercontent.com/66517106/383001374-a547cdcf-b7f5-44bd-a0cd-8a74201352f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Nzk1MzMsIm5iZiI6MTczMDc3OTIzMywicGF0aCI6Ii82NjUxNzEwNi8zODMwMDEzNzQtYTU0N2NkY2YtYjdmNS00NGJkLWEwY2QtOGE3NDIwMTM1MmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA0MDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYmU2Njg4ZjdmY2IxNWJmOTFiNWNmM2JlNWFiNjBkYWFlZTdlYWI4ODQ0ZTJiN2JjYjg4ZDM2YmYxMzgzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1pyxrvELRYKmvOSydSL_Olfy-DzH1XSrlrHvKrYGtok)

It seems this site has different free content depending on your country.

try this:
https://shahid.mbc.net/en/player/episodes/Breaking-Bones-season-1-episode-1/id-949558

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
shahid.mbc.net##+js(no-fetch-if, /gampad/ads?)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by oldhunter22** [comment]
> Can you test this filter:
> 
> ```
> shahid.mbc.net##+js(no-fetch-if, /gampad/ads?)
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

it works now!
Thank You!!
