### ISSUE TITLE
wattpad.com: breakage

### ISSUE THREAD

**Issue by JtheHollowUser** [uBlockOrigin/uAssets#25925]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wattpad.com/home`

### Category

breakage

### Description

So..I am very new just like one hour fresh and I just simply downloaded firefox and then immediately got uBlockOrigin, and I didn't mess with the settings and Important system due to me not understanding them at all. When I went to wattpad it show missing parts of the UI and I don't know what to do so I need help please. Since unfortunately I am very not smart on things like breakage and advanced tech stuff. Also I am using mobile only and have no computer.

### Other extensions used

I am using a extension called  Dark Reader since Wattpad has no dark mode(since dark mode will always be good) and further more I turn off Dark Reader to see if that was the problem but I don't know if deleting it will help, Since Wattpad light mode is to bright and I like dark mode alot. And this issue apppear before I got Dark Reader. And it only gives me dark mode and nothing else.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://photos.google.com/share/AF1QipP4xFA8JM048xsNLPkoLUtjvkJyuMd-k3ABVBB7_bcWFqbZ2-gNgRI5NF13osYBQw?key=aFYyLTBtdWNOMTJ5dmpCNFVmcVVPYmZiNmd0OVdR

https://photos.google.com/share/AF1QipPGGub5AkCWUUYDOOR-wyXTlHEiSEqleMIDbXA5Z1KVdWxli3wsREhEpoZYSX22kw?key=NGxDQXp5b2NUTnJpT2pfNUFVWGU3VXoxeE9kWnFR

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox Mobile: 132
filterset (summary):
 network: 139402
 cosmetic: 57633
 scriptlet: 21423
 html: 2067
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41383-252, 54m
  ublock-badware: 11917-24, 37m Δ
  ublock-privacy: 1397-24, 37m Δ
  ublock-unbreak: 2560-13, 37m Δ
  ublock-quick-fixes: 239-12, 37m Δ
  adguard-mobile: 9946-167, 54m
  easylist: 77143-45, 37m Δ
  easyprivacy: 53232-73, 54m
  urlhaus-1: 20990-0, 54m
  plowe-0: 3543-1074, 54m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2416 ms (selfie)
 maxAssetCacheWait: 384 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  wattpad.com: 2
  btloader.com: 2
  casalemedia.com: 1
  googletagmanager.com: 1
  pubmatic.com: 2
  rubiconproject.com: 2
  wp-e.net: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you go to `about:addons` page (type in URL bar), turn off all other extensions there (except uBO), restart the browser and test again?

**Comment by JtheHollowUser** [comment]
> Can you go to Firefox' add-ons settings page, turn off all other extensions there (except uBO), restart the browser and test again?

Unfortunately I have done that right now and it doesn't work at all so I don't know what else to look for or do.

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO too?

**Comment by JtheHollowUser** [comment]
> What happens if you turn off uBO too?

I turn off uBO then check after that, I deleted uBO and check then I re-download uBO then check, and it's still give the same results. I don't know if it's just because I am a mobile user only or something else that causing the issue since I have no computer to check for different results

**Comment by stephenhawk8054** [comment]
Then the issue is not caused by uBO.
