### ISSUE TITLE
NanoDefender 14.56 not working on KissCartoon.ac w/ Chrome 67

### ISSUE THREAD

**Issue by RomanADavis** [uBlockOrigin/uAssets#2592]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://kisscartoon.ac/Cartoon/Star-vs-The-Forces-of-Evil.37250/Episode-001?id=40026`

### Describe the issue

Notice to disable ad blocker where the video should be

### Screenshot(s)

`https://ibb.co/ekUVjd`

### Versions

- Browser/version: Chrome 67 on Windows 10 according to [according to this site.](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)
- uBlock Origin version: NanoDefend 14.56

### Settings

- No changes made to the NanoDefender settings.

**Comment by okiehsch** [comment]
Works fine on my end with uBO and a default setup.
@jspenguin2017

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/41503449-fc81f7ce-7191-11e8-8190-d87afed06bbb.png)

**Comment by okiehsch** [comment]
@RomanADavis If you open an issue disable all other Adblockers or atleast indicate in your "Settings" that you are using other blocking extensions.

**Comment by RomanADavis** [comment]
@okiehsch. It works when I disable my other adblockers. *However*, this should probably be added to the known issues for nanodefender and uBlockOrigin.

**Comment by jspenguin2017** [comment]
Why? If another adblocker breaks it, then it's their issue. Nano Defender can only protect Nano Adblocker or uBlock Origin.

**Comment by okiehsch** [comment]
Well, the issue is with your other adblockers not nanodefender or uBlockOrigin work as expected.

**Comment by jspenguin2017** [comment]
I have clear instructions on my home page, it's up to you to read.
