### ISSUE TITLE
meteomedia.com: ads

### ISSUE THREAD

**Issue by FrancoisBrousseau** [uBlockOrigin/uAssets#25928]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.meteomedia.com/fr/ville/ca/quebec/brossard/actuelle`

### Category

ads

### Description

Filtered ads return when reloading page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 138080
 cosmetic: 48980
 scriptlet: 21351
 html: 2065
listset (total-discarded, last-updated):
 default:
  user-filters: 72-14, never
  ublock-filters: 40870-133, 46m Δ
  ublock-badware: 12040-6, 46m Δ
  ublock-privacy: 1398-22, 46m Δ
  ublock-unbreak: 2558-1, 46m Δ
  ublock-quick-fixes: 225-6, 46m Δ
  easylist: 77182-192, 46m Δ
  easyprivacy: 53232-64, 46m Δ
  urlhaus-1: 20935-0, 46m
  plowe-0: 3543-1000, now
filterset (user): [array of 73 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 265 ms (selfie)
 maxAssetCacheWait: 177 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  meteomedia.com: 4
  amazon-adsystem.com: 1
  doubleclick.net: 3
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwpltx.com: 3
  theweathernetwork.com: 2
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ###ad-2
  ###ad-1
  ###ad-3
  ###ad-4
  ###bottom-ad
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
do you mean "Publicité" rectangles ?

maybe

`meteomedia.com##[data-testid="content-feed-ad-slot"]`

you should enable the french list too

**Comment by mapx-** [comment]
@FrancoisBrousseau report the issue here: https://github.com/easylist/listefr/issues
