### ISSUE TITLE
newscon.org/d3 detection

### ISSUE THREAD

**Issue by gabri25ele** [uBlockOrigin/uAssets#25924]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.newscon.org/d3/
```

### Description

Site detects adblock: Adblocker detected

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2024-11-05 09 29 16 www newscon org 841a66bb2ac0](https://github.com/user-attachments/assets/33d26fa3-58c3-42dc-9d6d-4e02ef8d09eb)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.60
Firefox: 132
filterset (summary):
 network: 105681
 cosmetic: 43388
 scriptlet: 18838
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75145-16, 2m
  easyprivacy: 32837-64, 2m
  plowe-0: 3721-1073, 2m
  ublock-badware: 7430-135, 2m
  ublock-filters: 35153-148, 2m
  ublock-privacy: 660-6, 2m
  ublock-quick-fixes: 141-86, 2m
  ublock-unbreak: 2133-31, 2m
  urlhaus-1: 12395-0, 2m
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 375 ms (selfie)
 maxAssetCacheWait: 136 ms
popupPanel:
 blocked: 12
 network:
  megaup.net: 4
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
 extended:
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(replace-node-text, script, /\$\(_\S+?\):/)

```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

https://github.com/uBlockOrigin/uAssets/issues/24368

**Comment by runebalot** [comment]
Detected again
