### ISSUE TITLE
thedaddy.to: detection

### ISSUE THREAD

**Issue by Classic33** [uBlockOrigin/uAssets#25937]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thedaddy.to/stream/stream-347.php`

### Category

detection

### Description

 it wont let me watch cause it says im using an ad block but i was using it all day and it didnt detect 

### Other extensions used

just ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 138027
 cosmetic: 48932
 scriptlet: 21345
 html: 2065
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40862-133, now
  ublock-badware: 11981-6, now
  ublock-privacy: 1394-22, now
  ublock-unbreak: 2558-1, 1m
  ublock-quick-fixes: 239-6, 1m
  easylist: 77201-198, 1m
  easyprivacy: 53227-64, 1m
  urlhaus-1: 20935-0, 1m
  plowe-0: 3543-1000, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2156 ms
 maxAssetCacheWait: 238 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  a-ads.com: 4
  ajscdn.com: 2
  arkabstoppit.com: 1
  google-analytics.com: 1
  histats.com: 3
  ilovetoplay.xyz: 1
  taboola.com: 1
  waust.at: 2
 extended:
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
  ##+js(abort-on-property-read, Adcash)
```
</details>

**Comment by huyszn** [comment]
Fixed with https://github.com/uBlockOrigin/uAssets/commit/c36929d3ea60cf709063fc50b4506cf1c3d05d83

**Comment by Classic33** [comment]
still does not work am i doing something wrong?

**Comment by huyszn** [comment]
Wait about 5-6 hours and update the filter lists again.

**Comment by Classic33** [comment]
Ok, thanks.
