### ISSUE TITLE
[nsfw] southpark.de: detection

### ISSUE THREAD

**Issue by AwZaji** [uBlockOrigin/uAssets#25935]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.southpark.de/folgen/d7grkc/south-park-die-passion-der-juden-staffel-8-ep-3`

### Category

detection

### Description

The site is able to detect uBlock Origin.

I can view the content if i disable the blocker.
A Message pops up if I have uBlock active, which translated reads:

"Oh no, it looks like you are using an ad blocker.
Please deactivate your ad blocker and try it again.
If you think you receiving this message is an error, please contact customer support."

I did get the message sometimes before but i could just refresh the site one or two times and everything worked.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-05 at 22-39-40 South Park - Season 8 Ep  3 - Die Passion der Juden - Full Episode South Park Studios Deutsch](https://github.com/user-attachments/assets/20426abb-a1b0-4ca0-8643-d227acecabae)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 140400
 cosmetic: 54343
 scriptlet: 21343
 html: 2065
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40871-133, 51m Δ
  ublock-badware: 12040-6, 51m Δ
  ublock-privacy: 1396-22, 51m Δ
  ublock-unbreak: 2558-1, 51m Δ
  ublock-quick-fixes: 205-6, 51m Δ
  easylist: 77201-192, 51m Δ
  easyprivacy: 53233-64, 51m Δ
  urlhaus-1: 20935-0, 33m
  plowe-0: 3543-1000, 33m
  DEU-0: 7779-40, 33m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4246 ms
 maxAssetCacheWait: 173 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  southpark.de: 1
  imasdk.googleapis.com: 1
  mtvnservices.com: 1
  newrelic.com: 4
  paramount.tech: 2
 extended:
  ##+js(prevent-fetch, ima3_dai)
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/a613dd3667517a8da25b23b2cb10a0ab0e210614
