### ISSUE TITLE
reddit.com: popups

### ISSUE THREAD

**Issue by BlohoJo** [uBlockOrigin/uAssets#25934]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.reddit.com/`

### Category

popups

### Description

"Sign in with Google / Use your Google Account to sign in to Reddit" popup occurs on Reddit as well as many other sites. In the past the general advise is to enable (in addition to default filters) the `uBlock filters – Annoyances` filter and the four `AdGuard – Annoyances` filters. This no longer works.

### Other extensions used

I used Firefox Portable with just uBlock Origin and the issue still occurs. It is happening without signing in to or even visiting google.com.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://github.com/user-attachments/assets/86ab3464-140c-4b55-a24c-b0ed9234a508)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 194141
 cosmetic: 155542
 scriptlet: 31912
 html: 2346
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 9m
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt: 87-0, 9m
  fanboy-cookiemonster: 52189-194, 9m
  ublock-annoyances: 5928-65, 9m
  CHN-0: 25559-103, 9m
  DEU-0: 7779-39, 9m
  FRA-0: 25704-410, 9m
  JPN-1: 15438-86, 9m
  RUS-0: 41044-281, 3m Δ
  spa-0: 3631-66, 9m
 default:
  user-filters: 4-0, never
  ublock-filters: 40872-133, 3m Δ
  ublock-badware: 12040-6, 9m
  ublock-privacy: 1396-109, 3m Δ
  ublock-unbreak: 2558-1, 9m
  ublock-quick-fixes: 205-6, 3m Δ
  easylist: 77201-193, 9m
  easyprivacy: 53233-64, 3m Δ
  urlhaus-1: 20935-0, 9m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 38 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1318 ms
 maxAssetCacheWait: 603 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  reddit.com: 20
  ad-delivery.net: 1
  google.com: 1
  redditstatic.com: 1
 extended:
  ##.promotedlink:not([style^="height: 1px;"])
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
Enable "EasyList – Other Annoyances" list and test again.
