### ISSUE TITLE
grubhub.com: breakage

### ISSUE THREAD

**Issue by joshtriplett** [uBlockOrigin/uAssets#25939]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.grubhub.com/
```

checkout page, after picking a restaurant, adding something to the cart, and initiating checkout process. Only available if logged in; URLs are of the form `https://www.grubhub.com/checkout/(unique token here)/review`

### Description

The delivery speed selection (shown in screenshot) is missing if uBlock Origin is enabled. Disabling uBlock Origin and refreshing makes the delivery speed selection show up.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/da54ed75-e5ed-41ee-983b-64ac2a34ddec)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 117166
 cosmetic: 49030
 scriptlet: 21345
 html: 2065
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  plowe-0: 3543-0, now
  ublock-quick-fixes: 206-6, 1h.51m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 40862-133, 1h.51m Δ
  ublock-badware: 12040-6, 1h.51m Δ
  ublock-privacy: 1397-22, 1h.51m Δ
  ublock-unbreak: 2558-1, 1h.51m Δ
  easylist: 77333-568, 1h.51m Δ
  easyprivacy: 53232-688, 1h.51m Δ
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15740 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 46
 network:
  grubhub.com: 3
  adsrvr.org: 1
  adxcel-ec2.com: 1
  airpr.com: 1
  amazon-adsystem.com: 1
  bing.com: 2
  branch.io: 1
  browser-intake-datadoghq.com: 13
  chtbl.com: 1
  doubleclick.net: 2
  facebook.net: 1
  forter.com: 2
  google-analytics.com: 2
  googletagmanager.com: 1
  havasedge.com: 1
  impactradius-event.com: 1
  mathtag.com: 1
  mountain.com: 1
  pinterest.com: 1
  redditstatic.com: 1
  sentry.io: 1
  tealiumiq.com: 1
  tiktok.com: 1
  trkn.us: 1
  tvsquared.com: 1
  twitter.com: 1
  videoamp.com: 1
  w55c.net: 1

```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
@@||taplytics-umami.grubhub.com/jssdk/$script,1p
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
