### ISSUE TITLE
thedaddy.to: nuisance

### ISSUE THREAD

**Issue by immeanyway** [uBlockOrigin/uAssets#25938]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thedaddy.to/stream/stream-613.php`

### Category

nuisance

### Description

Popup stating the need to disable ad blocker.

### Other extensions used

Video DownloadHelper
Read Aloud: A Text to Speech Voice Reader
Social Video Downloader
Lastpass
Metamask

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![popup](https://github.com/user-attachments/assets/93c9fdbf-83ac-472d-83b1-99d7800de6fc)
![popup](https://github.com/user-attachments/assets/e6171e22-1606-442f-9361-d25c15a54d48)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 138391
 cosmetic: 49030
 scriptlet: 21345
 html: 2065
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40862-133, 55m Δ
  ublock-badware: 12040-6, 55m Δ
  ublock-privacy: 1397-22, 55m Δ
  ublock-unbreak: 2558-1, 55m Δ
  ublock-quick-fixes: 206-6, 55m Δ
  easylist: 77333-192, 55m Δ
  easyprivacy: 53232-64, 55m Δ
  urlhaus-1: 21225-0, now
  plowe-0: 3543-1000, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1113 ms (selfie)
 maxAssetCacheWait: 124 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  a-ads.com: 4
  ajscdn.com: 2
  arkabstoppit.com: 1
  google-analytics.com: 1
  histats.com: 2
  ilovetoplay.xyz: 1
  taboola.com: 1
  waust.at: 1
 extended:
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
  ##+js(abort-on-property-read, Adcash)
```
</details>

**Comment by huyszn** [comment]
Already fixed and continue in https://github.com/uBlockOrigin/uAssets/issues/25937
