### ISSUE TITLE
apps.npr.org: ads

### ISSUE THREAD

**Issue by sodle** [uBlockOrigin/uAssets#25930]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://apps.npr.org/2024-election-results/`

### Category

ads

### Description

Ad does not load, but its container is left behind, leaving a large blank space before the page content.

### Other extensions used

BitWarden

Arc browser on Mac

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/92294d0e-08ab-4879-850e-36c189113dc4">

</details>

### Configuration

```yaml
version: uBOL 2024.10.28.929
mode: optimal / optimal
rulesets:
 default
```

**Comment by stephenhawk8054** [comment]
Did you choose "Complete" mode yet?

> - [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).

**Comment by sodle** [comment]
Yes, it still appears in Complete mode.

**Comment by mapx-** [comment]
@ryanbr 

`apps.npr.org##.has-sponsorship`
