### ISSUE TITLE
m6.fr: detection

### ISSUE THREAD

**Issue by Guid0Craft** [uBlockOrigin/uAssets#25931]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.m6.fr/top-chef-p_872/s13-e2-c_12950685`

### Category

detection

### Description

![image](https://github.com/user-attachments/assets/b8b3cbb4-b493-47b4-8f58-c1cd18f9aa87)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 156499
 cosmetic: 55555
 scriptlet: 23201
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-1, never
  FRA-0: 25704-39, now
  easylist: 77201-606, 1h.4m Δ
  easyprivacy: 53233-857, 1h.4m Δ
  plowe-0: 3543-30, now
  ublock-badware: 12038-22, 1h.4m Δ
  ublock-filters: 40615-320, 1h.4m Δ
  ublock-privacy: 1410-22, 1h.4m Δ
  ublock-quick-fixes: 206-6, 1h.4m Δ
  ublock-unbreak: 2500-5, 1h.4m Δ
  urlhaus-1: 20935-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 561 ms (selfie)
 maxAssetCacheWait: 176 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  estat.com: 1
  facebook.net: 1
  fwmrm.net: 3
  googletagmanager.com: 1
  googletagservices.com: 1
  imrworldwide.com: 1
  newrelic.com: 2
  outbrain.com: 1
  stickyadstv.com: 4
  tealiumiq.com: 12
  usabilla.com: 1
  youborafds01.com: 4
```
</details>

**Comment by tanguycc** [comment]
Yes I confirm same issue here

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
m6.fr##+js(no-xhr-if, fwmrm.net)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by QuentinLeFourbe** [comment]
@stephenhawk8054 I tried your solution, the issue persist

**Comment by stephenhawk8054** [comment]
@QuentinLeFourbe Test again in a new browser profile with only uBO and its default settings + that filter.

**Comment by mapx-** [comment]
the filter above is working fine on my end, tested FF / chrome

**Comment by stephenhawk8054** [comment]
@Yuki2718 For AdGuard Français?

**Comment by QuentinLeFourbe** [comment]
@stephenhawk8054 My bad ! It's working now, I reseted my uBO settings => added the filter => close and reopen my chrome. 

Thank you !

**Comment by Yuki2718** [comment]
What exact `fwmrm.net` request should be allowed if go with an exception?

**Comment by stephenhawk8054** [comment]
@Yuki2718 It's in the form of `https://7cbf2.v.fwmrm.net/`

![image](https://github.com/user-attachments/assets/d0ec100c-539d-4694-b6f3-fb4314cb5376)

**Comment by Guid0Craft** [comment]
Working for me thank you guys

**Comment by contribucious** [comment]
Hi there. Please see https://github.com/AdguardTeam/AdguardFilters/issues/192425#issuecomment-2470835069.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e45568fec5473e80013b06f8f11ab2191f3ea2ff

**Comment by LeGeek01** [comment]
I made a new issue since this was closed, but i've been told to continue here so that's what i'm doing.

M6 founded a way to bypass uBlock filters and is showing ads on on-demand videos.

Please see #32754 for all the details

**Comment by LeGeek01** [comment]
so after doing some research i found a domain that seems to be providing the ads, and after adding a custom filter in ublock, all the ads are gone and the player skip them instantly, playing the video, it was easy lol
here's the filter:
```adb
||vizchoice.viznet.tv/ads^
```
and there are no ad block detection

**Comment by mapx-** [comment]
enable the regional list AdGuard Français
