### ISSUE TITLE
helicomicro.com: detection

### ISSUE THREAD

**Issue by FeisarFPV** [uBlockOrigin/uAssets#25932]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.helicomicro.com/`

### Category

detection

### Description

Site detects uBlock, impossible to bypass for now.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_CywZYzpA41](https://github.com/user-attachments/assets/260f59c2-f422-4077-80ec-1f53ca383a5a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 161666
 cosmetic: 111479
 scriptlet: 29221
 html: 2330
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27942-1374, 1m
  adguard-mobile-app-banners: 5536-31, 1m
  adguard-other-annoyances: 14740-307, 1m
  adguard-widgets: 2754-15, 1m
  easylist-annoyances: 4805-296, 1m
  easylist-chat: 216-17, 1m
  easylist-newsletters: 8042-583, 1m
  easylist-notifications: 3457-1548, 1m
  ublock-annoyances: 5927-180, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 40871-133, 1h.51m Δ
  ublock-badware: 12040-6, 1h.51m Δ
  ublock-privacy: 1396-22, 1h.51m Δ
  ublock-unbreak: 2558-1, 1h.51m Δ
  ublock-quick-fixes: 205-6, 1h.51m Δ
  easylist: 77201-192, 1h.51m Δ
  easyprivacy: 53233-64, 1h.51m Δ
  urlhaus-1: 20935-0, now
  plowe-0: 3543-1000, now
  FRA-0: 25704-408, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 208 ms (selfie)
 maxAssetCacheWait: 71 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  helicomicro.com: 2
  cloudflareinsights.com: 2
  google.com: 7
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##.tnp-subscription-minimal
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by JobcenterTycoon** [comment]
Got fixed a hour ago already.

**Comment by FeisarFPV** [comment]
Could it be possible to expend to the whole site ? because on every news uBlock is still detected. Thank you
For exemple: https://www.helicomicro.com/2024/11/14/geprc-t-cube-18/

![image](https://github.com/user-attachments/assets/dc6c4b74-2367-4a46-8d8e-cf5ab9f4e1d6)

**Comment by mapx-** [comment]
no other detection on my end

**Comment by FeisarFPV** [comment]
> no other detection on my end

Does the filters has been updated since ? because uBlock is still detected in :
https://www.helicomicro.com/news/
https://www.helicomicro.com/lois/
https://www.helicomicro.com/newsletter/

And many other various articles like :
https://www.helicomicro.com/2022/05/24/dji-mini-3-pro-comment-recuperer-les-journaux-de-vol-avec-la-radiocommande-dji-rc/

(I well updated my local filters before just trying now)

**Comment by mapx-** [comment]
use this link to update your lists

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters,ublock-quick-fixes&manual=1

**Comment by FeisarFPV** [comment]
Many thanks, I confirm it now works well after trying your link to update filters

**Comment by FeisarFPV** [comment]
Hello, it seems to be back, can you please check ? Many thanks in advance

![Image](https://github.com/user-attachments/assets/35074489-fd6f-4e7a-be1b-e03957911450)
