### ISSUE TITLE
trendyol-milla.com: breakage

### ISSUE THREAD

**Issue by cengizcmataraci** [uBlockOrigin/uAssets#25946]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.trendyol-milla.com/trendyol-man/indigo-oversize-genis-kesim-cicek-nakisli-ici-polar-sicak-tutan-sweatshirt-tmnaw24sw00012-p-759050658?boutiqueId=651724&merchantId=968
```

### Description

When u-block origin is active, I cannot click on body size selection buttons (below the word Beden), which prevents adding product to cart. Once extension is disabled and refreshed (may require shift-refresh), it works.

This site is a major e-commerce site and it should be white listed. Before this issue, we have a similar one for trendyol.com so the issue is basically the same.

### Other extensions used

None, I disabled all other extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="541" alt="Ekran Resmi 2024-11-06 21 19 21" src="https://github.com/user-attachments/assets/3607d7b5-7c23-4151-9ef0-3a9a9c659efe">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 138612
 cosmetic: 49034
 scriptlet: 23029
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40628-374, 3h.56m Δ
  ublock-badware: 12137-6, 3h.56m Δ
  ublock-privacy: 1416-22, 3h.56m Δ
  ublock-unbreak: 2500-0, 3h.56m Δ
  ublock-quick-fixes: 210-0, 3h.56m Δ
  easylist: 77446-469, 3h.56m Δ
  easyprivacy: 53232-649, 3h.56m Δ
  urlhaus-1: 21225-0, 10h.25m
  plowe-0: 3542-0, 5d.6h.51m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1199 ms
 maxAssetCacheWait: 2 ms
 cacheBackend: indexedDB

```
</details>

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtm.js$script,domain=trendyol-milla.com
@@||connect.facebook.net^*/fbevents.js$domain=trendyol-milla.com
@@||connect.facebook.net/signals/config/$script,domain=trendyol-milla.com
```

@ryanbr

**Comment by ryanbr** [comment]
I have my doubts on this. Even with the select exceptions on facebook, it didn't work.

**Comment by mapx-** [comment]
weird, I need the exceptions in chrome, FF seems fine.
When you click a size nothing special happens but you can click the button bellow => becoming green (otherwise the size line is flashing => nothing has been chosen)

**Comment by stephenhawk8054** [comment]
On my side, I need

```adb
@@||googletagmanager.com/gtag/js$script,domain=trendyol-milla.com
```

too
