### ISSUE TITLE
new.uwufufu.com: ads

### ISSUE THREAD

**Issue by SaifulLukman** [uBlockOrigin/uAssets#25940]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://new.uwufufu.com/quiz/worldcup/672993facf03d978f94a6e0e?round=1&isFirst=true`

### Category

ads

### Description

It has a big ad space at the top and I see an anti-ad blocker window.

https://i.postimg.cc/tRD9fL7M/u2.png
https://i.postimg.cc/YqsM2Y6N/u1.png

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 142644
 cosmetic: 54582
 scriptlet: 21243
 html: 2006
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40599-138, 2m
  ublock-badware: 11923-6, 2m
  ublock-privacy: 1397-22, 2m
  ublock-unbreak: 2558-1, 2m
  ublock-quick-fixes: 206-2, 2m
  easylist: 77201-199, 2m
  easyprivacy: 53227-64, 2m
  urlhaus-1: 21225-0, 2m
  plowe-0: 3543-1000, 2m
  IDN-0: 10195-27, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4435 ms
 maxAssetCacheWait: 620 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  cloudflareinsights.com: 2
  cookieyes.com: 2
  google.com: 2
  googletagmanager.com: 2
  vntsm.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
That "anti-ad blocker window" appears even when I don't use any extensions.

**Comment by SaifulLukman** [comment]
should still be blocked because it is a disruptive element.

**Comment by stephenhawk8054** [comment]
At most it would just go to annoyance lists. Please report it to EasyList.

About the placeholder, I can't reproduce it.
