### ISSUE TITLE
[nsfw] saint.to: ads

### ISSUE THREAD

**Issue by Pureblood4936** [uBlockOrigin/uAssets#25947]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://simpcity.su/threads/strawberrytabby-tabithalookofsky.15886/page-19`

### Category

ads

### Description

the embedded video shows ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bildschirmfoto_6-11-2024_213626_simpcity su](https://github.com/user-attachments/assets/ef8a4ff3-40e3-46da-9343-611b4339d655)

</details>

### Configuration

```yaml
version: uBOL 2024.11.3.1351
mode: complete / complete
rulesets:
 default
 deu-0
```

**Comment by mapx-** [comment]
the embed video:

`https://saint2.cr/embed/wcshIDM6tXR`

it seems in uBOL this filter does not work:

```adb
/^https:\/\/[a-z]{8,12}\.com\/en\/(?:[a-z]{2,5}\/){0,2}[a-z]{2,}\?(?:[a-z]+=(?:\d+|[a-z]+)&)*?id=[12]\d{6}/$script,3p,match-case,header=etag,to=com
```

needing:

```adb
||nmimatrme.com^
```

**Comment by mapx-** [comment]
@stephenhawk8054 

AG using this 1 - working in mv3 too:

```adb
/^https:\/\/[a-z]{8,12}\.com\/en\/(?:[a-z]{2,5}\/){0,2}[a-z]{2,}\?(?:[a-z]+=(?:\d+|[a-z]+)&)*?id=[12]\d{6}/$script,third-party,match-case
```

**Comment by stephenhawk8054** [comment]
@mapx- MV3's regex is kind of black box, [this regex](https://github.com/uBlockOrigin/uBlock-discussions/discussions/790#discussioncomment-9824184) did not work on MV3 due to `memoryLimitExceeded` so I'm not sure about this one.

I'll check it later.

---

@Yuki2718 Btw, looks like it's clickadu regex. Is the `*?id=` part correct or is `?` meant to be escaped: `*\?id=`

**Comment by stephenhawk8054** [comment]
Ah right, I forgot about that case.

**Comment by Yuki2718** [comment]
> I don't remember if AG uses DNR?

AGMV3 of course uses DNR.

**Comment by stephenhawk8054** [comment]
Then I think we can use that regex without header in uBO too. I think the FP chances would be quite low.

**Comment by mapx-** [comment]
AG mv3 
https://chromewebstore.google.com/detail/adguard-adblocker-mv3-bet/apjcbfpjihpedihablmalmbbhjpklbdf
