### ISSUE TITLE
client.schwab.com: breakage

### ISSUE THREAD

**Issue by craigarno** [uBlockOrigin/uAssets#25949]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://client.schwab.com/Areas/Access/Login`

### Category

breakage

### Description

When uBlock is enabled, I can't login.  When uBlock is disabled, I can login.  Once logged in, I can logout, reenable uBlock, the login again.  It appears to be the 2-factor auth used by Schwab that seems to cause the issue.  When blocked the first time, I see the Schwab page with a spinner running that is still there 30-minutes after the first attempt.

It might be worth noting, I'm using the latest Windows 11 Pro version of Firefox 132.0.1 (64-bit).

### Other extensions used

None (all others are disabled).  Disabled "Privacy Possum", and "Privacy Badger".  It isn't until I disable uBlock that 2FA works.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 139378
 cosmetic: 49042
 scriptlet: 21366
 html: 2067
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40891-133, now
  ublock-badware: 12139-6, now
  ublock-privacy: 1402-22, now
  ublock-unbreak: 2558-1, now
  easylist: 77539-196, now
  easyprivacy: 53234-64, now
  urlhaus-1: 21905-0, now
  plowe-0: 3543-1000, 1h.58m
  ublock-quick-fixes: 211-6, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5963 ms
 maxAssetCacheWait: 726 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  schwab.com: 1
  demdex.net: 1
  glancecdn.net: 1
  globalsiteanalytics.com: 2
  go-mpulse.net: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
