### ISSUE TITLE
wikipedia.org: popups

### ISSUE THREAD

**Issue by alexg0** [uBlockOrigin/uAssets#25943]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wikipedia.org/`

### Category

popups

### Description

Wikipedia donation request popup is not blocked

### Other extensions used

1password, etc

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.11.3.1351
mode: basic / basic
rulesets:
 default
```

**Comment by stephenhawk8054** [comment]
Can you screenshot how the popup looks like? Also which country are you when accessing the site?

**Comment by mapx-** [comment]
us ip, tested in uBO

![image](https://github.com/user-attachments/assets/a24ba5b8-8be0-43cd-9c79-90116d20c6bc)

```adb
wikipedia.org##.banner
```

@ryanbr

**Comment by mapx-** [comment]
@alexg0 already fixed by `EasyList – Other Annoyances` => subscribe it in uBOL
