### ISSUE TITLE
harvey.utulsa.edu: breakage

### ISSUE THREAD

**Issue by jakester0010** [uBlockOrigin/uAssets#25958]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://harvey.utulsa.edu/`

### Category

breakage

### Description

Breaks when trying to use any of the folders, then the X buttons dont work

### Other extensions used

Darkreader
Honey
7TV
Return Youtube Dislike
Social Blade

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 139735
 cosmetic: 49022
 scriptlet: 23041
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40630-377, 57m Δ
  ublock-badware: 12157-6, 57m Δ
  ublock-privacy: 1421-22, 57m Δ
  ublock-unbreak: 2500-0, 57m Δ
  ublock-quick-fixes: 199-0, 57m Δ
  easylist: 77675-469, 57m Δ
  easyprivacy: 53238-650, 57m Δ
  urlhaus-1: 22100-0, now
  plowe-0: 3543-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 203 ms (selfie)
 maxAssetCacheWait: 79 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  newrelic.com: 2
  pendo.io: 1
```
</details>

**Comment by mapx-** [comment]
Are you able to provide an account ? and the steps to reproduce your issue

**Comment by mapx-** [comment]
@jakester0010 if you want to provide an account just let us know (commenting here) and I'll provide an email address where you can send the necessary info. 
Closing for now.
