### ISSUE TITLE
k2.kpfr.fun: ads

### ISSUE THREAD

**Issue by Sevoos** [uBlockOrigin/uAssets#25956]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://k2.kpfr.fun/film/4067/`

### Category

ads

### Description

It's impossible to get rid of ads, those just appear before the video starts playing and that's it.

### Other extensions used

CanvasBlocker
CORS Everywhere
Firefox Multi-Account Containers
Firefox Relay
Return YouTube Dislike
SponsorBlock for YouTube
User-Agent Switcher

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/fa114e0a-9725-4cfc-838c-554344de54a3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 139300
 cosmetic: 49017
 scriptlet: 21367
 html: 2068
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40865-132, now
  ublock-badware: 12159-6, now
  ublock-privacy: 1407-22, now
  ublock-unbreak: 2558-1, now
  ublock-quick-fixes: 200-6, 17m Δ
  easylist: 77643-196, now
  easyprivacy: 53235-64, now
  urlhaus-1: 21710-0, 17m
  plowe-0: 3543-1000, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 726 ms (selfie)
 maxAssetCacheWait: 53 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  doubleclick.net: 1
  franecki.net: 4
  getaim.org: 23
  legitcode.ws: 1
  serv01001.xyz: 2
  vak345.com: 2
  yadro.ru: 1
  yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
enable the russian list: RU AdList, test again
