### ISSUE TITLE
knowt.io: ads

### ISSUE THREAD

**Issue by HeyCurare** [uBlockOrigin/uAssets#25950]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
Knowt.io
```

### Description

Doesn't block banners/ads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1470" alt="Screenshot 2024-11-06 at 8 35 53 PM" src="https://github.com/user-attachments/assets/6edbddd1-3f9c-4b0a-8f45-e389eae4d8b0">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 139188
 cosmetic: 49043
 scriptlet: 23033
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40635-375, 3h.21m Δ
  ublock-badware: 12137-6, 3h.21m Δ
  ublock-privacy: 1416-22, 3h.21m Δ
  ublock-unbreak: 2500-0, 3h.21m Δ
  ublock-quick-fixes: 212-0, 3h.21m Δ
  easylist: 77539-469, 3h.21m Δ
  easyprivacy: 53234-649, 3h.21m Δ
  urlhaus-1: 21710-0, 3h.21m
  plowe-0: 3542-0, 11d.11h.37m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 183 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  knowt.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  mxpnl.com: 1
  pub.network: 5
  sentry.io: 19
```
</details>

**Comment by stephenhawk8054** [comment]
Describe the steps to reproduce the issue.
