### ISSUE TITLE
antakyagazetesi.com: ads

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#25963]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://antakyagazetesi.com/`

### Category

ads

### Description

the are ads on that website

### Other extensions used

localcdn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241108_120805](https://github.com/user-attachments/assets/f02fcc8a-ac2e-496a-8c4c-03011edc6592)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium Mobile: 132
filterset (summary):
 network: 239312
 cosmetic: 193391
 scriptlet: 40068
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1765-130, now
  adguard-spyware: 99330-23919, now
  block-lan: 64-0, now
  curben-phishing: 552-0, 1h.28m
  adguard-cookies: 32417-102, now
  ublock-cookies-adguard: 1923-0, now
  fanboy-cookiemonster: 52194-4128, now
  ublock-cookies-easylist: 1923-1923, now
  adguard-popup-overlays: 27955-622, now
  adguard-mobile-app-banners: 5549-1151, now
  adguard-other-annoyances: 14559-643, now
  adguard-widgets: 2757-25, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41141-230, 1h.28m Δ
  ublock-badware: 12151-8, 1h.28m Δ
  ublock-privacy: 1433-22, 1h.28m Δ
  ublock-unbreak: 2502-4, 1h.28m Δ
  ublock-quick-fixes: 202-0, 1h.28m Δ
  adguard-mobile: 9984-12, now
  easylist: 77752-641, 1h.28m Δ
  easyprivacy: 53239-1818, 1h.28m Δ
  urlhaus-1: 21850-0, 1h.27m
  plowe-0: 3543-83, now
  TUR-0: 10989-45, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2575 ms (selfie)
 maxAssetCacheWait: 418 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  bik.gov.tr: 1
  bildirt.com: 1
  cloudflareinsights.com: 1
  google.com: 7
  googlesyndication.com: 2
  googletagmanager.com: 1
  ilan.gov.tr: 1
  yandex.ru: 1
  youtube.com: 1
 extended:
  ##iframe[name="googlefcPresent"]
```
</details>

**Comment by mapx-** [comment]
add

`antakyagazetesi.com##[src*="VEGA"]`

for turkish pages report directly at [AG repository](https://github.com/adguardteam/adguardfilters/issues)
