### ISSUE TITLE
ipalibrary.me: detection

### ISSUE THREAD

**Issue by hugo9655** [uBlockOrigin/uAssets#25961]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://ipalibrary.me/
```

### Description

Detects ubo

### Other extensions used

** **

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/1aa3e1f2-5c76-43d5-a6f6-a9a2d7002434)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 275592
 cosmetic: 283769
 scriptlet: 56847
 html: 2349
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85584-4262, now
  adguard-mobile: 9983-60, now
  adguard-spyware-url: 1765-131, now
  adguard-spyware: 99330-1546, now
  block-lan: 64-0, now
  curben-phishing: 629-2, now
  adguard-cookies: 32421-62, now
  ublock-cookies-adguard: 1885-18, now
  fanboy-cookiemonster: 68861-20726, now
  ublock-cookies-easylist: 1885-1885, now
  adguard-social: 23135-52, now
  fanboy-social: 16818-788, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 40857-132, now
  ublock-badware: 12159-6, now
  ublock-privacy: 1407-22, now
  ublock-unbreak: 2558-1, now
  ublock-quick-fixes: 211-6, now
  easylist: 77526-2250, now
  easyprivacy: 53234-23272, now
  urlhaus-1: 22100-0, now
  plowe-0: 3543-1501, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5373 ms
 maxAssetCacheWait: 115 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  alwingulla.com: 2
  gloacmug.net: 1
  googletagmanager.com: 1
 extended:
  ##+js(no-setInterval-if, _0x)
  ##+js(no-setInterval-if, offsetHeight)
  ##+js(adjust-setInterval, countdown)
  ##+js(adjust-setInterval, countdown, *, 0.001)
  ##+js(no-setTimeout-if, afterRedirectUrl)

```
</details>

**Comment by stephenhawk8054** [comment]
@gorhill Somehow this doesn't work on my side:

```adb
ipalibrary.me##+js(no-fetch-if, /^/)
```

**Comment by stephenhawk8054** [comment]
@gorhill Yeah, I did disable other scriptlets, but sometimes it doesn't work when refreshing the page

![image](https://github.com/user-attachments/assets/e3be5768-cb43-4b64-97e0-00d3c3744034)

**Comment by stephenhawk8054** [comment]
Yeah, I mean even when I disable all other scriptlets (including `aost`), `no-fetch-if` still doesn't work for me sometimes.

**Comment by mapx-** [comment]
removed obsolete filters https://github.com/uBlockOrigin/uAssets/commit/a0b3a8327d7b1b0141e5064fb5ea2a29c44daa22

**Comment by gorhill** [comment]
Firefox still suffers race condition until the injected scriptlets are [registered](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register). Keep in mind all the scriptlets are unregistered when first visiting a site, every time filter lists need to be reloaded, whether through list update of adding/removing custom filters, toggling an exception in the logger, etc.

**Comment by gorhill** [comment]
[Yes.](https://github.com/gorhill/uBlock/blob/652f1787878ba434c3a65287afcd84082c409397/platform/firefox/vapi-background-ext.js#L357-L365)

**Comment by nqlp** [comment]
They are back:

<img width="1917" height="916" alt="Image" src="https://github.com/user-attachments/assets/c43bc219-4f07-442a-9c8b-08cfda82a8f3" />
