### ISSUE TITLE
forocoches.com: breakage

### ISSUE THREAD

**Issue by Kroji** [uBlockOrigin/uAssets#25970]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://forocoches.com/foro/
(Any other from forocoches.com, actually)
```

### Description

Breakage: getting near-blank page after last filter update, see screenshot 1. NOTE: this issue occurs with a specific skin that should be enabled in the site account options, by default site may show a different skin, so access with an account may be required.

The page is correctly shown if the following cosmetic filter is disabled: AdGuard Spanish/Portuguese > 
`forocoches.com##[align="center"]:has(div[id^="optidigital-adslot-"])`
, see screenshot 2.

### Other extensions used

Behave! 0.9.7.1 {17c7f098-dbb8-4f15-ad39-8b578da80f7e}
ClearURLs 1.26.1 {74145f27-f039-47ce-a470-a662b129930a} (issue occurs with filtering disabled)
Enterprise Policy Generator 6.1.0
FastForward 0.2383
FireMonkey 2.72
LibRedirect 3.0.2

(Omitting Mozilla ones, let me know if they may be related)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Screenshot 1: issue with all filters enabled

![imagen](https://github.com/user-attachments/assets/ceb0f52c-2400-4983-a4ad-5907b3802ed0)

Screenshot 2: expected result with specific filter `AdGuard Spanish/Portuguese > 

`forocoches.com##[align="center"]:has(div[id^="optidigital-adslot-"])` 
disabled

![imagen](https://github.com/user-attachments/assets/63ab4ca4-1a2b-42ef-a939-829dc19a2308)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 150504
 cosmetic: 142779
 scriptlet: 33959
 html: 2336
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2693-49, 11h.35m
  adguard-spyware-url: 1765-248, 1h.4m
  block-lan: 71-0, 22d.23h.51m
  ublock-cookies-adguard: 1879-0, 4d.22h.3m
  adguard-other-annoyances: 14560-257, 1h.4m
  easylist-annoyances: 4801-132, 4d.22h.3m
  fanboy-cookiemonster: 68854-16873, 2d.23h.44m
  ublock-cookies-easylist: 1879-1879, 4d.22h.3m
  easylist-newsletters: 8037-55, 4d.22h.3m
  fanboy-social: 16778-23, 4d.22h.3m
  ublock-annoyances: 5928-132, 4m Δ
 default:
  user-filters: 28-0, never
  ublock-filters: 40884-138, 4m Δ
  ublock-badware: 12196-6, 4m Δ
  ublock-privacy: 1407-22, 4m Δ
  ublock-unbreak: 2559-1, 4m Δ
  ublock-quick-fixes: 198-0, 4m Δ
  easylist: 77765-199, 4m Δ
  easyprivacy: 53239-66, 4m Δ
  urlhaus-1: 22295-0, 2h.5m
  plowe-0: 3543-1000, 1d.10h.46m
  spa-0: 3651-21, 1h.5m
  spa-1: 6078-263, 1h.4m
filterset (user): [array of 28 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 364 redacted]
hostRuleset:
 added: [array of 567 redacted]
urlRuleset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 filterAuthorMode: true
 loggerPopupType: normal
supportStats:
 allReadyAfter: 118 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
backup your current setup then reset uBO to defaults, disable any other extension, test again

**Comment by mapx-** [comment]
` To register at ForoCoches you need to have an invitation`

@Kroji you should provide a test account

**Comment by Yllelder** [comment]
How do I deactivate the filter you mentioned?

`forocoches.com##[align="center"]:has(div[id^="optidigital-adslot-"])`

**Comment by mapx-** [comment]
add

```adb
forocoches.com#@#[align="center"]:has(div[id^="optidigital-adslot-"])
```

**Comment by mapx-** [comment]
@Fierno does this filter works for you ?

`forocoches.com#@#[align="center"]:has(div[id^="optidigital-adslot-"])`

**Comment by Fierno** [comment]
Done! It works. Thanks!
