### ISSUE TITLE
[nsfw] spankbang.com: breakage

### ISSUE THREAD

**Issue by Adbekunkus** [uBlockOrigin/uAssets#25974]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://spankbang.com/`

### Category

breakage

### Description

When uBlock is activated, it is not possible to play videos. When deactivated, videos play OK.

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 140064
 cosmetic: 49076
 scriptlet: 21367
 html: 2080
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40895-133, 1h.16m Δ
  ublock-badware: 12197-6, 1h.16m Δ
  ublock-privacy: 1407-22, 1h.16m Δ
  ublock-unbreak: 2559-1, 1h.16m Δ
  ublock-quick-fixes: 198-6, 1h.16m Δ
  easylist: 77820-198, 1h.16m Δ
  easyprivacy: 53239-64, 1h.16m Δ
  urlhaus-1: 22295-0, now
  plowe-0: 3549-1000, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1000 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 34
 network:
  spankbang.com: 5
  cherrytv.media: 1
  cloudflareinsights.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  ptgncdn.com: 25
 extended:
  ##.video-inline-ads
  ##.partner_ads
  ##.s-ad
  ###shorts-frame
  ##.ptgncdn_holder
  ##.ttaa2v3
  ##.lv_cm_int_come_on
  ##.download-promo
  ##+js(no-window-open-if)
  ##+js(set-constant, chrome, undefined)
```
</details>

**Comment by Adbekunkus** [comment]
@stephenhawk8054: how do I implement this? I cannot find a privacy.txt file. I use uBlock on Firefox under Linux.

**Comment by stephenhawk8054** [comment]
Wait about 5-6 hours and update the filter lists again. Or you can add this as your custom filter:

```adb
spankbang.com##+js(set, send_gravity_event, noopFunc)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
