### ISSUE TITLE
techradar.com (anti adblock)

### ISSUE THREAD

**Issue by alexara** [uBlockOrigin/uAssets#2597]
### URL(s) where the issue occurs

`https://www.techradar.com`

### Describe the issue

The website detects uBlock and redirects to `https://www.techradar.com/cc.html`

### Screenshot(s)

![screenshot_20180617_183147](https://user-images.githubusercontent.com/13819719/41509973-cf44ea7a-725c-11e8-81ed-62bed6bdcda2.png)

### Versions

- Browser/version: FF 60.0.2
- uBlock Origin version: 1.16.10

### Settings

- Default

**Comment by mapx-** [comment]
it's fixed in ublock anoyances, are you using that list ?

**Comment by alexara** [comment]
> it's fixed in ublock annoyances, are you using that list ?

Is it it new? I haven't used it but after activating it the anti adblock warning is gone! Thanks :-)

**Comment by mapx-** [comment]
it was added some months ago (and as any annoyances list is not enabled by default)
