### ISSUE TITLE
online.vinschool.edu.vn: breakage

### ISSUE THREAD

**Issue by DinhHuy2010** [uBlockOrigin/uAssets#25978]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://online.vinschool.edu.vn/login
```

### Description

Blank page at https://online.vinschool.edu.vn/login (redirect from lms.vinschool.edu.vn)
(Note is only happened at LibreWolf (Firefox), using chrome with ublock still work)

### Other extensions used

![image](https://github.com/user-attachments/assets/c4462b3c-617c-46a6-9a64-6c4eef996329)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0f0d7ee1-b31d-458a-8c05-d60845f2321d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 402024
 cosmetic: 264663
 scriptlet: 55371
 html: 2345
listset (total-discarded, last-updated):
 added:
  https://curbengh.github.io/malware-filter/vn-badsite-filter.txt: 16843-0, 22h.49m
  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts: 132203-336, 22h.44m
  https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts: 20751-7902, 22h.44m
  adguard-generic: 85517-4443, 22h.49m
  adguard-mobile: 9984-528, 22h.49m
  adguard-spyware: 99330-3320, 22h.49m
  block-lan: 64-0, 28d.22h.48m
  adguard-cookies: 32417-65, 22h.49m
  ublock-cookies-adguard: 1885-18, 21h.19m
  fanboy-cookiemonster: 52194-4058, 21h.19m
  ublock-cookies-easylist: 1885-1885, 21h.19m
  adguard-social: 23134-52, 22h.49m
  [13 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40893-158, 5m Δ
  ublock-badware: 12231-48, 5m Δ
  ublock-privacy: 1408-26, 5m Δ
  ublock-unbreak: 2562-1, 5m Δ
  ublock-quick-fixes: 199-6, 5m Δ
  easylist: 77834-4808, 5m Δ
  adguard-spyware-url: 1764-131, 3d.22h.38m
  easyprivacy: 53239-24436, 5m Δ
  urlhaus-1: 21850-171, 22h.50m
  curben-phishing: 552-3, 22h.49m
  plowe-0: 3542-3540, 9d.2h.50m
  LegitimateURLShortener: 2693-166, 5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5834 ms
 maxAssetCacheWait: 2892 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by DinhHuy2010** [comment]
hold on, please wait (also using Librewolf)

**Comment by DinhHuy2010** [comment]
no breakage on default settings

**Comment by stephenhawk8054** [comment]
In your old profile, backup your configuration, reset uBO to default settings, open new tab and test again.

**Comment by DinhHuy2010** [comment]
does that include filter lists

**Comment by DinhHuy2010** [comment]
I reset settings and it did work
![image](https://github.com/user-attachments/assets/970403c4-48ea-43a8-b3f0-ad182cda900c)
![image](https://github.com/user-attachments/assets/46af58f3-8bbc-4dd6-b0da-ed5c6b12befb)

**Comment by DinhHuy2010** [comment]
also note, even without resetting, it still work (as long is not on private browsing)

**Comment by stephenhawk8054** [comment]
Yeah, then you'll need to investigate yourself which configuration (filter lists, settings...) is causing the issue.

> - [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

**Comment by DinhHuy2010** [comment]
I did reset filter lists, still wouldn't work on private browsing

**Comment by stephenhawk8054** [comment]
Does it work in private browsing in the new profile?

**Comment by DinhHuy2010** [comment]
nope, it did not work
![image](https://github.com/user-attachments/assets/9d37ff25-a9c5-4913-bc2b-221fd884d672)

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO in private browsing?

**Comment by DinhHuy2010** [comment]
Disable the extension or exclude site

**Comment by stephenhawk8054** [comment]
Disable in `about:addons`

**Comment by DinhHuy2010** [comment]
nope, blank page (uBO turn off)
![image](https://github.com/user-attachments/assets/367eac4b-ae2c-41bf-aba1-ab876a73b9ec)

**Comment by DinhHuy2010** [comment]
may be post this issue on the librewolf issue tracker?

**Comment by stephenhawk8054** [comment]
> nope, blank page (uBO turn off)

Then it's not uBO's issue.

**Comment by Stridre** [comment]
i think its just librewolf, have you  tried just using google or tor

**Comment by DinhHuy2010** [comment]
Hi @Stridre,
sorry for waiting,
first of, I didn't install tor
also google still work
![image](https://github.com/user-attachments/assets/a741d4ae-d0b9-4471-968e-3014f551d409)
