### ISSUE TITLE
Anti-adblock overlay on videos at jagobd.com

### ISSUE THREAD

**Issue by silentsky** [uBlockOrigin/uAssets#2598]
### URL(s) where the issue occurs

`http://www.jagobd.com/dbcnews`

### Describe the issue

Anti-Adblock overlay on Videos (see screenshot).

### Screenshot(s)

https://screenshotscdn.firefoxusercontent.com/images/2c9738d7-9159-4ab9-8f5e-0bdcf1a678f1.png

### Versions

- Browser/version: Firefox/60.0.2 (32-bit)
- uBlock Origin version: 1.16.10

### Settings

- Default filterlist and settings.

**Comment by garry-ut99** [comment]
Ad placeholders cause by `ghide` from "uBlock filters".
Main page: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217247018-c5f5e80c-eb38-4281-907a-30df870505c7.png) Example subpage (`https://www.jagobd.com/asiantv`): [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217247084-ea3c05df-32a6-4089-927e-de7e639b9833.png)
