### ISSUE TITLE
ainonline.com: detection

### ISSUE THREAD

**Issue by erkinalp** [uBlockOrigin/uAssets#25988]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.ainonline.com/aviation-news/business-aviation/2023-03-29/daher-plans-production-add-hybrid-electric-tbm`

### Category

detection

### Description

totally unable to work

### Other extensions used

uBO detected, not relevant

### Screenshot(s)

> Ad Blocking Detected
> AIN is supported by advertisers. Please disable your ad blocker on our website and refresh the page.
> Using AdBlock Plus?
>
> To allow ads to show on the site you're currently visiting, click the AdBlock toolbar icon to open the AdBlock menu. For "this website", uncheck the active blocking slider.

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 133 beta
filterset (summary):
 network: 1385209
 cosmetic: 272931
 scriptlet: 56311
 html: 2346
listset (total-discarded, last-updated):
 added:
  https://curbengh.github.io/urlhaus-filter/urlhaus-filter-online.txt: 8331-0, now
  https://fanboy.co.nz/fanboy-turkish.txt: 823-0, now
  https://filters.adtidy.org/extension/ublock/filters/5.txt: 16-0, now
  https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt: 6-0, now
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/BadIpList.txt: 14-3, now
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/HostsList.txt: 9872-38, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 0-0, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiBadCapitalismList.txt: 427-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiFunctionalityRemovalList.txt: 27-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt: 299-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/EmptyPaddingRemover.txt: 78-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/I Don't Want to Download Your Browser.txt: 61-0, now
  [33 lists not shown]: [too many]
 default:
  user-filters: 29-1, never
  ublock-filters: 40905-133, now
  ublock-badware: 12261-124, now
  ublock-privacy: 1408-47, now
  ublock-unbreak: 2562-3, now
  ublock-quick-fixes: 193-9, now
  easylist: 77879-30908, now
  easyprivacy: 53249-32930, now
  urlhaus-1: 21255-8216, now
  plowe-0: 3549-3355, now
  TUR-0: 10990-224, now
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 20 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 allowGenericProceduralFilters: true
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 600
 filterAuthorMode: true
 trustedListPrefixes: ublock- user- adguard- easylist-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 4603 ms
 maxAssetCacheWait: 2060 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  ainonline.com: 1
  doubleclick.net: 1
  google.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  typekit.net: 1
 extended:
  ##p:-moz-only-whitespace
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
Did you test the filter I added in uBO default setup ?

**Comment by erkinalp** [comment]
btw interrupting the page load is useless for this page, a javascript fetches the text after the no-AB is detected
