### ISSUE TITLE
sudachiemu.com: badware

### ISSUE THREAD

**Issue by democat3457** [uBlockOrigin/uAssets#25984]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://sudachiemu.com
```

### Description

sudachiemu.com is a badware site posing to be the site for the Sudachi emulator, whose actual site is https://sudachi.emuplace.app/. Download links on sudachiemu.com lead to sketchy link-outs and the blog posts are not very consistent (especially with an open-source project).

### Other extensions used

none

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 226242
 cosmetic: 213291
 scriptlet: 38972
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32375-101, 4d.22h.28m
  adguard-mobile-app-banners: 5534-1139, 4d.22h.28m
  adguard-other-annoyances: 14736-516, 4d.22h.28m
  adguard-popup-overlays: 27943-2929, 4d.22h.28m
  adguard-social: 23123-794, 4d.22h.28m
  adguard-spyware: 99320-23834, 4d.22h.28m
  adguard-spyware-url: 1764-8, 4d.22h.28m
  adguard-widgets: 2752-58, 4d.22h.28m
  curben-phishing: 577-0, 9m
  easylist-annoyances: 4808-134, 3d.3h.13m
  easylist-chat: 216-0, 1d.4h.24m
  easylist-newsletters: 8042-33, 3d.9h.11m
  [6 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 77860-45, 9m Δ
  easyprivacy: 53248-752, 9m Δ
  plowe-0: 3542-376, 10d.10h.56m
  ublock-badware: 12249-26, 9m Δ
  ublock-filters: 40652-644, 9m Δ
  ublock-privacy: 1422-146, 9m Δ
  ublock-quick-fixes: 208-0, 9m Δ
  ublock-unbreak: 2504-14, 9m Δ
  urlhaus-1: 21190-0, 5h.56m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 990 ms (selfie)
 maxAssetCacheWait: 256 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  consensu.org: 1
  quantcast.com: 1
 extended:
  ##+js(addEventListener-defuser, contextmenu)
  ##+js(adjust-setInterval, downloadTimer, , 0.02)
  ##+js(set-constant, blurred, false)
  ##+js(abort-current-script, String.fromCharCode, /btoa|break/)
  ##+js(abort-on-property-read, clickCount)
```
</details>

**Comment by stephenhawk8054** [comment]
We need other analysis about the site or the downloaded files or more confirmation of the project itself. Without those, we cannot block any site just based on a report like this.

**Comment by 3052** [comment]
@stephenhawk8054 LOL boths threads are locked so I cant comment on either

https://github.com/uBlockOrigin/uAssets/issues/25989
https://github.com/uBlockOrigin/uAssets/issues/25991

**Comment by jordansworld** [comment]
this is a legit site
![Screenshot_20241111_101542_Samsung Internet](https://github.com/user-attachments/assets/f7ed9638-b24a-4333-ac7e-1fd3fe8ea301)
