### ISSUE TITLE
curiosityu.com: breakage

### ISSUE THREAD

**Issue by erkinalp** [uBlockOrigin/uAssets#25987]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.curiosityu.com/videos/a-two-hundred-year-problem-the-environmental-effects-of-the-industrial-revolution/`

### Category

breakage

### Description

Video player not opening properly, making the whole site useless

### Other extensions used

Dark Reader (cosmetic only)
Greasemonkey (no userscripts affecting the site)
Consent-O-Matic (validated it is not the reason)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBO on: 
![resim](https://github.com/user-attachments/assets/81e0a05a-cb12-4c83-ad4f-62cc5f255bd9)
With uBO off:
![resim](https://github.com/user-attachments/assets/683d2218-0d83-456d-85c7-6e3fbfc27947)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 133 beta
filterset (summary):
 network: 1385185
 cosmetic: 272934
 scriptlet: 56323
 html: 2346
listset (total-discarded, last-updated):
 added:
  https://curbengh.github.io/urlhaus-filter/urlhaus-filter-online.txt: 8331-0, now
  https://fanboy.co.nz/fanboy-turkish.txt: 823-0, now
  https://filters.adtidy.org/extension/ublock/filters/5.txt: 16-0, now
  https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt: 6-0, now
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/BadIpList.txt: 14-3, now
  https://gitlab.com/huzunluartemis/TurkishAdblockList/-/raw/main/src/HostsList.txt: 9872-38, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 0-0, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiBadCapitalismList.txt: 427-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiFunctionalityRemovalList.txt: 27-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt: 299-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/EmptyPaddingRemover.txt: 78-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/I Don't Want to Download Your Browser.txt: 61-0, now
  [33 lists not shown]: [too many]
 default:
  user-filters: 29-1, never
  ublock-filters: 40903-133, now
  ublock-badware: 12251-124, now
  ublock-privacy: 1408-47, now
  ublock-unbreak: 2562-3, now
  ublock-quick-fixes: 193-9, now
  easylist: 77862-30907, now
  easyprivacy: 53248-32930, now
  urlhaus-1: 21255-8216, now
  plowe-0: 3549-3355, now
  TUR-0: 10990-224, now
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 20 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 allowGenericProceduralFilters: true
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 600
 filterAuthorMode: true
 trustedListPrefixes: ublock- user- adguard- easylist-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 4603 ms
 maxAssetCacheWait: 2060 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  brightcove.net: 3
  googleoptimize.com: 2
  hs-scripts.com: 2
  nextdoor.com: 1
 extended:
  ###ast-scroll-top
  ##section:remove-class(image-copy-protection)
  ##p:has-text(/^\xA0$/):not(:has-text(/\S/)):not(:has(img))
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by erkinalp** [comment]
Ran the logger and found the offending rule: Turns out it's related to DeadEnd, not uBO filter set.
