### ISSUE TITLE
karistudio.com: detection

### ISSUE THREAD

**Issue by templeofshadow** [uBlockOrigin/uAssets#25990]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://karistudio.com/`

### Category

detection

### Description

When uBlock Origin is enabled, the webpage content for novels fails to load. No other content on the website appears to be affected.

I tried moving to Firefox (where I also have uBlock installed and active), and while it worked for a moment, it then detected the adblock and blocked access, redirecting to [https://karistudio.com/adblocker/](https://karistudio.com/adblocker/) (see screenshots). I cleared site data for the website, but this detection process didn't occur again, only serving webpages with no novel content.

However, weirdly, Firefox's "reader mode" viewer seems to still display the content. Upon getting to the empty chapter webpage, enabling reader mode on Firefox seems to """fix""" the issue from the perspective of the user. 

All screenshots are with [https://karistudio.com/chapter-135-persona-pyxis/](https://karistudio.com/chapter-135-persona-pyxis/), but I tested multiple random chapters from random novels and it was the same.

Please let me know if you need any additional information from me.

### Other extensions used

Linguist 
Dark Reader 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock enabled (Chrome):
![image](https://github.com/user-attachments/assets/f1352004-28a0-4f22-b9c6-3594207504a2)

uBlock disabled (and webpage slightly zoomed out) (Chrome):
![image](https://github.com/user-attachments/assets/f42bf407-1c42-425f-b742-aa06a6431265)

uBlock enabled, redirected to [https://karistudio.com/adblocker/](https://karistudio.com/adblocker/) (Firefox):
![image](https://github.com/user-attachments/assets/e2770e95-be8b-43d7-ac04-d9ae1adc5608)

uBlock enabled, chapter page (Firefox):
![image](https://github.com/user-attachments/assets/18364c57-0d86-4227-8f80-6b6303189ea5)

uBlock enabled, reader mode enabled (Firefox):
![image](https://github.com/user-attachments/assets/2fd11c31-c99d-4532-b327-63d31ceaec0f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 139152
 cosmetic: 49083
 scriptlet: 23053
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 77862-469, now
  easyprivacy: 53249-631, now
  plowe-0: 3549-0, now
  ublock-badware: 12259-6, now
  ublock-filters: 40655-377, now
  ublock-privacy: 1422-22, now
  ublock-quick-fixes: 199-0, now
  ublock-unbreak: 2504-19, now
  urlhaus-1: 21255-0, now
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1593 ms
 maxAssetCacheWait: 332 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 37
 no-large-media: true
 no-popups: true
 no-scripting: true
 network:
  karistudio.com: 19
  cloudflareinsights.com: 1
  doubleclick.net: 4
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 5
  googletagmanager.com: 2
  infolinks.com: 1
  netpub.media: 1
  pubfuture-ad.com: 1
  trvdp.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by templeofshadow** [comment]
@mapx- This issue persists. I suspect there is something different with how Kari Studio does the adblock detection process. HTML/Web isn't my area of expertise though, so all I can say as a user is that even with the updated filter it still doesn't work.

Also, they added DOM elements that mess up the Firefox reader mode workaround that I mentioned, so for anyone looking to use that workaround, it no longer works.

**Comment by DrCryllus** [comment]
Issue Persists. Added filter suggested by @uBlock-user to custom filters- did not seem to make a difference. Also blocked check2.js- no change. On desktop, if the back button lets you go back to the chapter from the modification warning page (Inconsistent, baffling), the cached chapter will not run the redirect.
