### ISSUE TITLE
computerbase.de: breakage

### ISSUE THREAD

**Issue by Faustpfand** [uBlockOrigin/uAssets#25993]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.computerbase.de/news/pc-systeme/verbrauch-im-leerlauf-was-ist-fuer-euch-eigentlich-idle-und-ist-das-relevant.90227/`

### Category

breakage

### Description

Survey forms cannot be submitted (onclick action doesnt fire)

### Other extensions used

doesnt matter, because everyone in the comments of that web page is complaining about this in connection with ublock origin and  there is an explicit filter in "uBlock Filter - quick fixes" that causes the problem

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 130
filterset (summary):
 network: 141460
 cosmetic: 54481
 scriptlet: 22942
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-quick-fixes: null
 default:
  user-filters: 0-0, never
  ublock-filters: 40656-266, 43m Δ
  ublock-badware: 12259-6, 33m Δ
  ublock-privacy: 1422-22, 43m Δ
  ublock-unbreak: 2504-0, 43m Δ
  easylist: 77897-601, 33m Δ
  easyprivacy: 53249-658, 43m Δ
  urlhaus-1: 21255-0, 43m
  plowe-0: 3549-0, now
  DEU-0: 7795-3, 43m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1522 ms (selfie)
 maxAssetCacheWait: 245 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  computerbase.de: 4
  vgwort.de: 1
```
</details>

**Comment by ghost** [comment]
Unfortunately, it’s not working again - this time the website is just blurred.
It’s because of “EasyList/uBO – Cookie Notices”.

<details>
<summary>Screenshot(s)</summary>




<img width="2557" height="1297" alt="Image" src="https://github.com/user-attachments/assets/81437b92-6160-4680-80bf-215d67f2c59d" />



</details>
