### ISSUE TITLE
carbonite.co.za: detection

### ISSUE THREAD

**Issue by r1337x** [uBlockOrigin/uAssets#25992]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://carbonite.co.za/`

### Category

detection

### Description

After browsing and checking out about 3-4 pages, you get a persistent overlay asking you to disable your adblocker.

You can view this by browsing the site and then click a few threads and it should pop up.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 182722
 cosmetic: 227804
 scriptlet: 70135
 html: 2395
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83267-164, 5m
  adguard-generic: 85517-4810, now
  adguard-spyware-url: 1767-131, 5m
  adguard-social: 23136-834, 5m
  fanboy-cookiemonster: 52201-4084, now
  ublock-annoyances: 5895-254, 6m Δ
  [3 lists not shown]: [too many]
 default:
  user-filters: 53-0, never
  ublock-filters: 40908-2298, now
  ublock-badware: 12261-6, now
  ublock-privacy: 1408-23, now Δ
  ublock-unbreak: 2562-3, now Δ
  easylist: 77897-2256, now
  easyprivacy: 53249-1402, 6m Δ
  urlhaus-1: 21255-0, now
  plowe-0: 3549-1386, now
  ublock-quick-fixes: 193-13, now
filterset (user): [array of 53 redacted]
trustedset:
 added: [array of 88 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 219 ms (selfie)
 maxAssetCacheWait: 121 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  carbonite.co.za: 3
  doubleclick.net: 1
  googletagmanager.com: 2
 extended:
  ##.notice-content
  ##div[data-widget-definition="share_page"]
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.samCodeUnit
  ##.shareButtons
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-current-script, $, AdBlock)
  ##+js(set-constant, adsBlocked, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to sign in to reproduce the issue?
