### ISSUE TITLE
Zeus Anti Adblock

### ISSUE THREAD

**Issue by rjkpa** [uBlockOrigin/uAssets#260]
### URL(s) where the issue occurs

http://www.menshealth.com/fitness/best-gyms/slide/1
http://www.womenshealthmag.com/sex-and-love/dating-an-older-man/slide/1
http://www.prevention.com/weight-loss/whole30-diet-and-25-pound-weight-loss/slide/1
http://www.runnersworld.com/cold-weather-running/10-tips-to-make-winter-running-less-miserable
http://www.bicycling.com/beginners/bicycling-skills/five-signs-youre-not-a-beginner-anymore/slide/1
http://www.rodalesorganiclife.com/wellbeing/who-knew-corn-syrups-not-the-most-evil-sweetener-in-your-kitchen
http://www.rodalewellness.com/health/50-healthy-new-years-resolutions [1]
http://www.rodale.tv/video/ageless-remarkable-story-ernestine-shepherd [1]

### Describe the issue

anti adblock overlay blurs the article body and demands to subscribe or disable adblock

### Notes

`##script:inject(setTimeout-defuser.js, showForm, 100)`  works for all the aformentioned websites.

filter - `rodale.tv,rodalewellness.com,rodalesorganiclife.com,bicycling.com,runnersworld.com,prevention.com,menshealth.com,womenshealthmag.com##script:inject(setTimeout-defuser.js, showForm, 100)`

[1] cannot reproduce, but the detection is present.

**Comment by okiehsch** [comment]
@rjkpa if `generichide` also works on your end, this issue is best dealt with by Easylist.
`https://forums.lanik.us/index.php`
For `menshealth.com` the filter `@@||menshealth.com^$generichide` was already mentioned there.
`https://forums.lanik.us/viewtopic.php?f=62&t=34698`

**Comment by uBlock-user** [comment]
@okiehsch Yes, it does. Fine by me. Will close it now.

**Comment by rjkpa** [comment]
@okiehsch Yes, `$generichide` works fine and will do.

**Comment by okiehsch** [comment]
`$generichide` does not work anymore, I will add a fix.

**Comment by mapx-** [comment]
simple filters (for example the first 2 sites)
```
@@||menshealth.com/*ads
@@||womenshealthmag.com/*ads
```

**Comment by okiehsch** [comment]
@gorhill I can add the filter
`example.com##script:inject(abort-on-property-read.js, Drupal.behaviors.ad_block_interrupter)`
works with every mentioned site.
As mentioned by @mapx- this issue can also be solved by a 1st-party exception filter.
Do you prefer such issues to be fixed by Easylist, or should I add a uBO-specific filter`?

**Comment by gorhill** [comment]
Probably `@@||menshealth.com/*ads` will end up in EasyList anyways so `script:inject` would become pointless anyways. uBO-Scope does not show any worsening (3rd-party exposure) when using `@@||menshealth.com/*ads`, so it's all fine, though I would personally prefer `@@||menshealth.com/*ads$~third-party` to be sure.

**Comment by uBlock-user** [comment]
The filter suggested by the OP works just fine, why not jut add that ?

**Comment by gotitbro** [comment]
@rjkpa @okiehsch What is Zeus anti adblock?

**Comment by okiehsch** [comment]
I do not know, the mentioned sites use [Zeus Drupal Hosting Platform](https://www.drupal.org/project/zeus), maybe he thought that this includes an anti-adblock script.

**Comment by gotitbro** [comment]
Oh alright, thanks for the info :)

**Comment by uBlock-user** [comment]
It's the name of the anti adblock script used by the company behid these mags.
