### ISSUE TITLE
twitch.tv: breakage

### ISSUE THREAD

**Issue by AlvaroHonorio** [uBlockOrigin/uAssets#26004]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/agurin`

### Category

breakage

### Description

Loads the main page of twitch (https://www.twitch.tv/directory/following/live) but does not load any stream at all, it sticks to a black loading page. When opening the link to a direct stream in incognite mode (adBlock is disabled by default) it loads perfectly.

I have trying disabling adblock and loading the page again and it still does not load, only works in incognite mode.

![imagen](https://github.com/user-attachments/assets/e1844e81-5e9c-4f84-bb1f-977d2dd38916)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 141326
 cosmetic: 56009
 scriptlet: 21904
 html: 2082
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40924-133, 2m Δ
  ublock-badware: 12305-6, 2m Δ
  ublock-privacy: 1410-22, 2m Δ
  ublock-unbreak: 2562-1, 2m Δ
  ublock-quick-fixes: 196-6, 2m Δ
  easylist: 77901-198, 2m Δ
  easyprivacy: 53249-69, 2m Δ
  urlhaus-1: 21345-0, 2m
  plowe-0: 3549-1000, 2m
  spa-0: 3666-21, 2m
  spa-1: 6078-260, 2m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 175 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  d2v02itv0y9u9t.cloudfront.net: 1
 extended:
  ##.stream-display-ad__wrapper
  ##+js(no-window-open-if, amazon-adsystem)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
