### ISSUE TITLE
helicomicro.com: detection

### ISSUE THREAD

**Issue by FeisarFPV** [uBlockOrigin/uAssets#26009]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.helicomicro.com/news/`

### Category

detection

### Description

site detects ublock (again now)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_N5ttSAc4LC](https://github.com/user-attachments/assets/230a9703-20ad-449f-839a-26c41812ef97)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 163213
 cosmetic: 111672
 scriptlet: 29106
 html: 2349
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 27969-1376, now
  adguard-mobile-app-banners: 5536-31, now
  adguard-other-annoyances: 14560-278, now
  adguard-widgets: 2758-15, now
  easylist-annoyances: 4821-300, now
  easylist-chat: 216-17, now
  easylist-newsletters: 8053-584, now
  easylist-notifications: 3461-1549, now
  ublock-annoyances: 5895-176, 59m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 40929-133, 59m Δ
  ublock-badware: 12305-6, 59m Δ
  ublock-privacy: 1420-22, 59m Δ
  ublock-unbreak: 2564-1, 59m Δ
  ublock-quick-fixes: 194-11, 59m Δ
  easylist: 78134-198, 59m Δ
  easyprivacy: 53261-69, 59m Δ
  urlhaus-1: 21395-0, now
  plowe-0: 3549-1000, now
  FRA-0: 25730-415, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 437 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  helicomicro.com: 4
  cloudflareinsights.com: 2
  google.com: 7
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##.tnp-subscription-minimal
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in your old thread. All volunteers are notified with new comments. No need to open duplicated issue.
