### ISSUE TITLE
dzen.ru: breakage

### ISSUE THREAD

**Issue by Trixlight** [uBlockOrigin/uAssets#26007]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://dzen.ru/
```

### Description

Line 22965 in the RU AdList filter breaks the functionality of the Gesturefy extension.
See https://github.com/Robbendebiene/Gesturefy/issues/731#issue-2648764490

### Other extensions used

Gesturefy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/user-attachments/assets/66d18f54-2059-4ec8-8187-e8e690b96859)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 128
filterset (summary):
 network: 200506
 cosmetic: 237764
 scriptlet: 51088
 html: 2116
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1756-0, 1h.1m
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 22917-92, 1h.1m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83285-176, 1h.1m
  https://winhelp2002.mvps.org/hosts.txt: 8729-20, 1h.1m
  adguard-generic: 85611-4338, 59m
  curben-phishing: 610-1, 59m
  adguard-cookies: 32455-32455, 57m
  fanboy-cookiemonster: 52201-4081, 57m
  fanboy-thirdparty_social: 68-0, 1h
  adguard-popup-overlays: 27962-27962, 57m
 default:
  user-filters: 27-0, never
  ublock-filters: 40928-452, 59m
  ublock-badware: 12305-7, 39m Δ
  ublock-privacy: 1420-29, 59m
  ublock-unbreak: 2564-8, 59m
  ublock-quick-fixes: 196-12, 59m
  easylist: 77978-2561, 59m
  easyprivacy: 53257-1879, 59m
  urlhaus-1: 21410-0, 59m
  plowe-0: 3549-1266, 1h
  RUS-0: 41067-3143, 1h.1m Δ
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 contextMenuEnabled: false
 prefetchingDisabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2054 ms
 maxAssetCacheWait: 1053 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 137
 network:
  dzen.ru: 107
  mail.ru: 4
  yandex.net: 6
  yandex.ru: 20
 extended:
  ###ya-dist-popup
  ###ya-dist-teaser
  ##div[class*="bannerMain"]
  ##div[id$="-link_bro"]
  ##.adv-skeleton___main
  ##[class^="dzen-desktop--top-micro-app__"] [class^="dzen-desktop…
  ##[id*="-teaser"] > div[id]
  ##div:has(> .adv-skeleton___main)
  ##a[href*="://yandex.ru/an/count/"]
  ##a[href*="://yandex.ru/an/count/"] ~ a[href*="://yandex.ru/an/c…
  ##[class*="desktop"] ~ [id*="teaser"]
  ##[class^="dzen-desktop"] ~ div[id$="-popup"]
  ##div[class*="widget"] > div[class*="container"] > div ~ div
  ##[aria-label*="Лент"] article:has(> div:matches-css(display: no…
  ##body:style(overflow: auto !important;)
  ##div[class*="--top-micro-app__"] > div[style$="position: relati…
  ##body:style(overflow-y: unset !important)
  ##div[class*="dzen-wrapper-with-top-content-desktop__topContent-…
  ###LayoutTopMicroRoot div[style*="%"]:style(padding-top: unset !…
  ##.zen-page .content div[class*="__bannerMain"]:style(display: n…
  ##div[class*="linkBro-"]:style(display: none !important)
  ##div[class*="widgetContainer"] div[style^="padding-top:"][style…
  ##+js(remove-cookie, /blcrm|bltsr|zmFQeXtI|JPIqApiY|computer/)
  ##+js(set-constant, Object.prototype.checkBundleIsSSP, undefined…
  ##+js(abort-on-stack-trace, Promise, initContext)
  ##+js(adjust-setTimeout, ()=>r(t), 15000)
  ##+js(no-xhr-if, strm.yandex.ru/get/)
  ##+js(set-constant, Object.prototype.DirectProduct, undefined)
  ##+js(set-constant, Object.prototype.getAutoplay, noopFunc)
  ##+js(set-constant, Object.prototype.getUaasConfig, undefined)
  ##+js(set-constant, Object.prototype.partnerId, {})
  ##+js(set-constant, Object.prototype.hasPreroll, null)
  ##+js(set-constant, Object.prototype.useExperimentFlag, undefine…
  ##+js(json-prune, direct rtb seatbid)

```
</details>

**Comment by stephenhawk8054** [comment]
cc @dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
This issue is best discussed here: https://github.com/easylist/ruadlist/issues
