### ISSUE TITLE
puzzle-thermometers.com: breakage

### ISSUE THREAD

**Issue by Dansiman** [uBlockOrigin/uAssets#26015]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.puzzle-thermometers.com/`

### Category

breakage

### Description

I am logged in to the website. One benefit of being logged in is that, next to the special daily, weekly, and monthly puzzle links, there will be a green checkmark if you have already completed that puzzle. But recently I noticed that I was not getting those checkmarks. Then I observed that the icon in the very top-left corner of the page, which normally shows your "level" when logged in, was instead showing the generic anonymous user icon that indicates not logged in. When I click that icon, a login box appears briefly, then immediately disappears, as if the site suddenly realizes "Oh, you're already logged in!" and then everything looks like normal for being logged in... until the next page load, at which point it returns to the acting-like-you're-not-logged-in presentation.

With uBlock Origin disabled, the logged-in interface shows up correctly on the initial page load.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/bab8a805-b411-4619-8eda-818fbcb08f84)
Appearance of the left side navbar upon initial load with uBO enabled

![image](https://github.com/user-attachments/assets/55d15b1d-a711-4700-9934-7eb8b2d83727)
The login dialog that displays momentarily upon clicking the profile icon

![image](https://github.com/user-attachments/assets/a23db7bd-6a4f-42ce-9963-47a301b69555)
Appearance of the left side navbar after the login dialog disappears. Also how it looks upon initial page load when uBO is disabled.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 130
filterset (summary):
 network: 139201
 cosmetic: 49092
 scriptlet: 23072
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, 12m
 default:
  user-filters: 2-0, never
  ublock-filters: 40667-130, 12m
  ublock-badware: 11655-1, 12m
  ublock-privacy: 1445-23, 12m
  ublock-unbreak: 2506-1, 12m
  ublock-quick-fixes: 202-13, 12m
  easylist: 78179-595, 12m
  easyprivacy: 53261-763, 12m
  urlhaus-1: 21560-0, 1h.46m
  plowe-0: 3557-0, 12m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3984 ms (selfie)
 maxAssetCacheWait: 1426 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  proper.io: 1
 extended:
  ###MainContainer > [id^="bannerTopSpacer"]
  ###MainContainer + [id]:has(> #bannerSide)
  ###MainContainer > [id]:has(> [id^="btIn"] > #bannerTop)
  ##div[id]:has(> #bannerSide)
  ##div[id]:has(> #bannerTop)
```
</details>

**Comment by Dansiman** [comment]
In case it's relevant, I am logged in via email/password, not via Google/Facebook/Discord.

**Comment by stephenhawk8054** [comment]
Does the issue occur if you turn off uBO?

**Comment by mapx-** [comment]
it's a site issue:

- disable uBO
- F5 => all fine
- ctrl-F5 => "generic anonymous user icon that indicates not logged in"
