### ISSUE TITLE
coincodex.com: ads

### ISSUE THREAD

**Issue by TheHeroBrine422** [uBlockOrigin/uAssets#26019]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://coincodex.com/sentiment/`

### Category

ads

### Description

Is displaying a ad for pepe unchained

### Other extensions used

Lastpass, Grammarly, Phantom, Metamask

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/e460cfff-60d0-4986-baef-1419f0416de8">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 131
filterset (summary):
 network: 139179
 cosmetic: 49086
 scriptlet: 21377
 html: 2083
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 87-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 40909-132, now
  ublock-badware: 11657-1, now
  ublock-privacy: 1420-109, now
  ublock-unbreak: 2564-1, now
  ublock-quick-fixes: 195-11, now
  easylist: 78179-198, now
  easyprivacy: 53261-69, now
  urlhaus-1: 21560-0, now
  plowe-0: 3557-1000, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2035 ms (selfie)
 maxAssetCacheWait: 46 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  coincodex.com: 1
  clarity.ms: 1
  googletagmanager.com: 1
  onesignal.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
||coincodex.com/*/position/ccx_pos-min2.php$script
coincodex.com##.ldb-top3
```

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/27737

```adb
||coincodex.com/*/position/ccx_pos-min$script
coincodex.com##.hot-box-list
```

@ryanbr
