### ISSUE TITLE
amtraktrains.com: ads

### ISSUE THREAD

**Issue by Swimmable7861** [uBlockOrigin/uAssets#26028]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.amtraktrains.com/threads/bi-level-long-distance-ld-fleet-replacement-rfp-discussion-h2-2024.87606/`

### Category

ads

### Description

Starting this week, this site shows a rotating list of Amazon items for sale somewhere in the list of posts in a thread. Sometimes it's at the bottom of the thread, in this case it's about 20% down the page. I tried using the element picker and can pick the frames for the individual items and the left and right scroll arrows, but cannot figure out how to block the entire frame.

### Other extensions used

Bitwarden
Cookie AutoDelete
History Cleaner
Bookmarks Organizer
Don't touch my tabs!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-12 212638](https://github.com/user-attachments/assets/322e239b-8bf7-41d5-90a2-e17c518d64c3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 139454
 cosmetic: 66775
 scriptlet: 25106
 html: 2348
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 87-0, 50m
  fanboy-thirdparty_social: 68-0, 3m
  fanboy-social: 16801-25, 3m
  ublock-annoyances: 5896-34, 3m
  ublock-quick-fixes: 195-11, 3m
 default:
  user-filters: 23-0, never
  ublock-filters: 40909-132, 3m
  ublock-badware: 11657-1, 3m
  ublock-privacy: 1420-109, 3m
  ublock-unbreak: 2564-1, 3m
  easylist: 78187-198, 3m
  easyprivacy: 53268-69, 3m
  urlhaus-1: 20775-0, 3m
  plowe-0: 3557-1000, 3m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 130 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 12 redacted]
 removed:
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5396 ms (selfie)
 maxAssetCacheWait: 253 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 129
 network:
  adthrive.com: 1
  cloudflareinsights.com: 2
  doubleclick.net: 4
  google.com: 7
  googletagmanager.com: 1
  media-amazon.com: 104
  paypalobjects.com: 2
  skimresources.com: 2
  videoplayerhub.com: 1
  youtube.com: 5
 extended:
  ##.shareButtons
  ##.shareButtons-label
  ##.shareButtons-buttons
  ##.shareButtons-button
  ##.p-body-content > .gb-sponsored-wrapper
  ##._right.productslider-arrow
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.web_bind_fetch, …
```
</details>

**Comment by mapx-** [comment]
add

```
amtraktrains.com##.productslider
amtraktrains.com##.gb-sponsored
```

@ryanbr
