### ISSUE TITLE
mylink.tel: breakage

### ISSUE THREAD

**Issue by vasa-chi** [uBlockOrigin/uAssets#26033]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://mylink.tel
```

### Description

As far as I can tell, external scripts are blocked for all mylink.* domains. https://mylink.tel is a homepage of an ISP, not an ad redirect site (which caused the addition of mylink.*, re: #4163), and this filter makes it quite difficult to use some integrations we need.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 157851
 cosmetic: 69775
 scriptlet: 22928
 html: 2100
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40916-132, 44m Δ
  ublock-badware: 11657-1, 44m Δ
  ublock-privacy: 1422-22, 44m Δ
  ublock-unbreak: 2564-1, 44m Δ
  ublock-quick-fixes: 195-11, 44m Δ
  easylist: 78189-198, 44m Δ
  easyprivacy: 53268-69, 44m Δ
  urlhaus-1: 21560-0, 12h.31m
  plowe-0: 3549-1000, 1d.17h.4m
  RUS-0: 41068-150, 44m Δ
filterset (user): [empty]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 462 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  getsale.io: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  jivosite.com: 1
  payselection.com: 1
  vk.com: 1
  yandex.ru: 1
 extended:
  ##+js(abort-current-script, decodeURIComponent, shift)
  ##+js(no-setInterval-if, /0x|google|ecoded|==/)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…

```
</details>

**Comment by mapx-** [comment]
Test

```adb
*$script,3p,denyallow=cloudflare.com|cloudflare.net|consensu.org|google.com|googleapis.com|gstatic.com|hcaptcha.com|hwcdn.net|recaptcha.net|twitter.com|x.com,domain=mylink.*|my1ink.*|myl1nk.*|myli3k.*,badfilter
*$script,3p,denyallow=cloudflare.com|cloudflare.net|consensu.org|google.com|googleapis.com|gstatic.com|hcaptcha.com|hwcdn.net|recaptcha.net|twitter.com|x.com,domain=mylink.*|my1ink.*|myl1nk.*|myli3k.*|~mylink.tel
```

**Comment by vasa-chi** [comment]
Yes, with this everything works.
