### ISSUE TITLE
zenradio.com: detection

### ISSUE THREAD

**Issue by fenavi** [uBlockOrigin/uAssets#26034]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.zenradio.com/about-blockers`

### Category

detection

### Description

uBlock is detected.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 141797
 cosmetic: 93902
 scriptlet: 21925
 html: 2084
listset (total-discarded, last-updated):
 added:
  adguard-social: 23146-29, now
  fanboy-thirdparty_social: 68-3, now
  fanboy-social: 16801-777, now
 default:
  user-filters: 57-1, never
  ublock-filters: 40916-141, 1h.36m Δ
  ublock-badware: 11657-1, 1h.36m Δ
  ublock-privacy: 1422-23, 1h.36m Δ
  ublock-unbreak: 2564-1, 1h.36m Δ
  easylist: 78189-198, 1h.36m Δ
  easyprivacy: 53268-73, 1h.36m Δ
  urlhaus-1: 20775-0, 36m
  plowe-0: 3557-1000, now
  spa-0: 3686-21, 36m
  spa-1: 6094-259, now
  ublock-quick-fixes: 195-13, 1h.36m Δ
filterset (user): [array of 57 redacted]
trustedset:
 added: [array of 81 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 717 ms
 maxAssetCacheWait: 395 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 network:
  adswizz.com: 2
  amazon-adsystem.com: 3
  audioaddict.com: 11
  criteo.net: 1
  d2r1yp2w7bby2u.cloudfront.net: 1
  errorception.com: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 1
  google.es: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  primis.tech: 2
  pub.network: 1
  smartadserver.com: 2
```
</details>

**Comment by mapx-** [comment]
Did you get detection visiting this (normal) page ?

`https://www.zenradio.com`

**Comment by gorhill** [comment]
Unable to reproduce.

Does it happen only if logged in?
