### ISSUE TITLE
newrepublic.com: nuisance

### ISSUE THREAD

**Issue by Bunell5090** [uBlockOrigin/uAssets#26038]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://newrepublic.com/post/188254/trump-white-nationalist-stephen-miller-second-term-policy`

### Category

nuisance

### Description

I have the abti-adblocker adblocker filter enabled, but the website still shows an abti-adblocker message when viewing an article. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium Mobile: 124
filterset (summary):
 network: 266736
 cosmetic: 228780
 scriptlet: 57284
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 2332-14, now
  https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 8425-0, now
  https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 415-11, 3m
  https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-57, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 152-2, now
  adguard-generic: 85666-530, now
  adguard-spyware-url: 1777-130, now
  adguard-spyware: 100352-25388, now
  block-lan: 64-0, now
  curben-phishing: 559-0, 3m
  adguard-cookies: 32476-105, now
  ublock-cookies-adguard: 1940-0, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 41194-4157, 3m Δ
  ublock-badware: 11667-139, 3m Δ
  ublock-privacy: 1450-22, 3m Δ
  ublock-unbreak: 2508-81, 3m Δ
  ublock-quick-fixes: 197-12, 3m Δ
  adguard-mobile: 9931-163, now
  easylist: 78174-2886, 3m Δ
  easyprivacy: 53271-946, 3m Δ
  urlhaus-1: 20720-189, 2m
  plowe-0: 3557-26, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 40 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1771 ms (selfie)
 maxAssetCacheWait: 245 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cookielaw.org: 1
  google.com: 3
  site-config.com: 1
 extended:
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.ad-unit:not(.textads)
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.newsletter-cta
  ##.OUTBRAIN
  ###ot-sdk-btn:not(button)
  ##.ot-sdk-show-settings
  ##.footer__middleRow
  ##.upArrow
  ##.ad-container
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.web_bind_fetch, …
  ##+js(trusted-click-element, ytd-button-renderer.ytd-consent-bum…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(set-constant, yt.config_.openPopupConfig.supportedPopups.a…
  ##+js(set-constant, Object.prototype.adBlocksFound, 0)
  ##+js(set-constant, ytplayer.config.args.raw_player_response.adP…
  ##+js(set-constant, Object.prototype.hasAllowedInstreamAd, true)
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by Bunell5090** [comment]
It might have been a one-off issue. I will re-report it if the issue comes back.

**Comment by huyszn** [comment]
Fixed in `uBlock filters – Annoyances` list.

**Comment by Bunell5090** [comment]
Thanks a million!
