### ISSUE TITLE
startpage.com: ads

### ISSUE THREAD

**Issue by BTHeeler** [uBlockOrigin/uAssets#26030]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.startpage.com/do/dsearch?q=calm&cat=web&language=english`

### Category

ads

### Description

Search results on Startpage.com forcibly display "Sponsored" ad links for Walmart and AliExpress on top of the page.
I've tried disabling other extensions to no avail of any positive changes.

### Other extensions used

Behind the Overlay, ClearURLs, Decentraleyes, DeArrow, Sponsorblock, Enhancer for YouTube, FastForward, Indie Wiki Buddy, Ruffle - Flash Emulator, Tampermonkey, Startpage - Private Search Engine, Sound Booster, GitZip, Malwarebytes Browser Guard (ads protection turned off), User-Agent Switcher, VettedAI

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_780](https://github.com/user-attachments/assets/f39e2493-68a9-41e8-adad-c0845743b705)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 130
filterset (summary):
 network: 276689
 cosmetic: 287316
 scriptlet: 58615
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85633-7622, 1h.14m
  adguard-mobile: 9928-142, 1h.14m
  adguard-spyware-url: 1773-130, 1h.14m
  adguard-spyware: 100357-24472, 1h.14m
  block-lan: 64-0, 1h.14m
  curben-phishing: 611-0, 1h.14m
  adguard-cookies: 32469-98, 1h.14m
  ublock-cookies-adguard: 1890-0, 1h.14m
  fanboy-cookiemonster: 52202-4133, 1h.14m
  ublock-cookies-easylist: 1890-1890, 1h.14m
  adguard-social: 23144-798, 1h.14m
  fanboy-social: 16801-24, 1h.14m
  [12 lists not shown]: [too many]
 default:
  user-filters: 54-5, never
  ublock-filters: 40658-616, 1h.14m
  ublock-badware: 11655-2, 1h.14m
  ublock-privacy: 1445-22, 1h.14m
  ublock-unbreak: 2506-3, 1h.15m
  ublock-quick-fixes: 202-4, 1h.14m Δ
  easylist: 78186-929, 1h.14m Δ
  easyprivacy: 53268-859, 1h.14m
  urlhaus-1: 20775-0, 1h.14m
  plowe-0: 3557-1, 1h.14m
filterset (user): [array of 53 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 20 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 853 ms (selfie)
 maxAssetCacheWait: 222 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  startpage.com: 10
 extended:
  ##.social
  ##.a-bg
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by BTHeeler** [comment]
> Test again in a new browser profile with only uBO and its default settings.

Thanks for the suggestion. I tried this just now, but sadly it still shows the Sponsored links. I even decided to try it on another browser with uBO installed and it does the same thing.

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by BTHeeler** [comment]
> Which country are you when accessing the site?

United States.

**Comment by mapx-** [comment]
us ip, working for me:

```adb
startpage.com##[style]:has(path):has([href*="aff"])
```

**Comment by stephenhawk8054** [comment]
> ```
> ##[style]:has(path):has([href*="aff"])
> ```

This doesn't work when I use Germany IP and search for "kitchen".

Does this work on your side?

```adb
startpage.com###main > div[style]:not([class]):has(path)
```

**Comment by mapx-** [comment]
yes

**Comment by BTHeeler** [comment]
> us ip, working for me:
> 
> ```
> startpage.com##[style]:has(path):has([href*="aff"])
> ```

Nice, this worked!

**Comment by ygoe** [comment]
Shall I report this again or is it enough to comment that this isn't working for me? I'm in Germany, if that helps. I see those ads that are added to the page around 2 seconds after the page has loaded. It's super annoying because it's a full page or useless content and it moves the links I want to click further down so that I will inadvertently click on their ads instead.

**Comment by stephenhawk8054** [comment]
Just continue commenting in the old thread. No need to open duplicated issue.

Which search term did you use to reproduce?

**Comment by svenjacobs** [comment]
[This query](https://eu.startpage.com/do/dsearch?q=sops&cat=web&language=english) shows ads for me.

**Comment by svenjacobs** [comment]
```
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 143082
 cosmetic: 55772
 scriptlet: 38186
 html: 2195
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=rawlist: 22597-12, 2h.40m
  DEU-0: 7799-40, 32m
 default:
  user-filters: 1-0, never
  ublock-filters: 40939-1935, 4h.47m Δ
  ublock-badware: 11977-1, 4h.47m Δ
  ublock-privacy: 1502-23, 4h.47m Δ
  ublock-unbreak: 2565-1, 4h.47m Δ
  ublock-quick-fixes: 221-10, 4h.47m Δ
  easylist: 79081-213, 4h.47m Δ
  easyprivacy: 53272-88, 4h.47m Δ
  urlhaus-1: 19195-0, 32m
  plowe-0: 3557-1000, 7d.21h.5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  startpage.com: 3
 extended:
  ##.a-bg
```

**Comment by stephenhawk8054** [comment]
You are using `fuckfuckadblock` which is a bad list that whitelists many ads connections. Remove it.

**Comment by svenjacobs** [comment]
I just added the list today because I thought this might fix the problem but I actually have been seeing ads on Startpage for the past few days. Even after removing this list I still see the ads.

```
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 139726
 cosmetic: 55214
 scriptlet: 21393
 html: 2146
listset (total-discarded, last-updated):
 added:
  DEU-0: 7799-40, 1h.4m
 default:
  user-filters: 1-0, never
  ublock-filters: 40939-135, 4m Δ
  ublock-badware: 11977-1, 4m Δ
  ublock-privacy: 1505-22, 4m Δ
  ublock-unbreak: 2565-1, 4m Δ
  ublock-quick-fixes: 221-10, 4m Δ
  easylist: 79080-206, 4m Δ
  easyprivacy: 53272-69, 4m Δ
  urlhaus-1: 19195-0, 1h.5m
  plowe-0: 3557-1000, 7d.21h.37m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  startpage.com: 3
 extended:
  ##.a-bg
```

**Comment by stephenhawk8054** [comment]
I still can't reproduce it

![image](https://github.com/user-attachments/assets/2f22d1ac-0df9-4ea9-9c1e-80c163808e56)

Does this filter work: https://github.com/uBlockOrigin/uAssets/issues/26030#issuecomment-2472751548

**Comment by svenjacobs** [comment]
![Screenshot 2024-11-22 at 12-07-53 sops - Startpage](https://github.com/user-attachments/assets/ac7b41fc-b5ce-4986-9268-bc5d2648cc9e)

**Comment by stephenhawk8054** [comment]
Can you test the filter in https://github.com/uBlockOrigin/uAssets/issues/26030#issuecomment-2472751548

**Comment by svenjacobs** [comment]
> Can you test the filter in [#26030 (comment)](https://github.com/uBlockOrigin/uAssets/issues/26030#issuecomment-2472751548)

Yes, this works.

**Comment by ygoe** [comment]
> Can you test the filter in [#26030 (comment)](https://github.com/uBlockOrigin/uAssets/issues/26030#issuecomment-2472751548)

Ah, that one also works for me now. Guess I had the wrong one mentioned in this discussion somewhere.

**Comment by TrainingArc** [comment]
Hello, I'm encountering this issue on Firefox mobile and have tried using the filters mentioned in[ #26030 (comment)](https://github.com/uBlockOrigin/uAssets/issues/26030#issuecomment-2472751548) and [#26030 (comment)](https://github.com/uBlockOrigin/uAssets/issues/26030#issuecomment-2472744262). I can recreate the issue using the search term "kitchen".

**Screenshot of issue**

<details>

![Image](https://github.com/user-attachments/assets/71b89867-7146-4f27-b798-32be1c1d3d58)

</details>

**UBlock Origin Troubleshooting information**

<details>

```yml
uBlock Origin: 1.65.0
Firefox Mobile: 141
filterset (summary):
 network: 154609
 cosmetic: 51243
 scriptlet: 23201
 html: 2358
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  ublock-filters: 40662-82, 16m Δ
  ublock-badware: 11434-18, 16m Δ
  ublock-privacy: 3344-2, 16m Δ
  ublock-unbreak: 2730-1, 16m Δ
  ublock-quick-fixes: 283-13, 16m Δ
  adguard-mobile: 11188-66, 1d.12h.50m
  easylist: 74777-283, 16m Δ
  easyprivacy: 54338-64, 16m Δ
  urlhaus-1: 30870-0, 16m
  plowe-0: 3422-971, 5d.4h.7m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3362 ms (selfie)
 maxAssetCacheWait: 82 ms
 cacheBackend: indexedDB
```

</details>

**Screenshot of My Filters**

<details>

![Image](https://github.com/user-attachments/assets/a44671aa-cbe4-43e4-8f75-56b165c94449)

</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
startpage.com##.pa-bg
```

**Comment by TrainingArc** [comment]
Thanks for the reply, but I am still having the issue after adding it to the filter list.

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by TrainingArc** [comment]
USA

**Comment by stephenhawk8054** [comment]
Can you test this filter:

```adb
startpage.com##.a-bg
```

**Comment by TrainingArc** [comment]
> Can you test this filter:
> 
> startpage.com##.a-bg

This worked. Thank you very much!

**Comment by stephenhawk8054** [comment]
@ryanbr
