### ISSUE TITLE
english.almayadeen.net: breakage

### ISSUE THREAD

**Issue by QuinoaMillet** [uBlockOrigin/uAssets#26039]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://english.almayadeen.net/articles/opinion/the-zionist-regime-front-and-the-beren-family`

### Category

breakage

### Description

The web site TTS feature is broken with uBOL turned on basic filter, and only works with uBOL turned off.
![image](https://github.com/user-attachments/assets/b008ba1f-d91a-4907-b7bd-a5bf487dec97)

### Other extensions used

Brave shield is turned off.
![image](https://github.com/user-attachments/assets/516d0a10-a566-4e55-9a38-c76e7f8038fd)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.11.3.1351
mode: basic / complete
rulesets:
 default
 fra-0
 spa-0
 spa-1
```

**Comment by gorhill** [comment]
It works after the site finishes loading completely, the site just takes long to load. This also happens without a content blocker enabled.

**Comment by QuinoaMillet** [comment]
Merci  <3

**Comment by gorhill** [comment]
Without any extension, it takes 20 seconds for the `load` event to be fired, at which point the "Listen" button becomes available:

![image](https://github.com/user-attachments/assets/055ae7b9-d24b-493c-8582-983b13eb4455)

It's a site issue, best to report to webmaster.
