### ISSUE TITLE
time.is detection

### ISSUE THREAD

**Issue by RedLight-Scratch** [uBlockOrigin/uAssets#26042]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://time.is/
```

### Description

Detected by time.is

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://github.com/user-attachments/assets/5877a304-44e1-4ead-b8f4-be0439e36853)

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 138392
 cosmetic: 49086
 scriptlet: 21386
 html: 2085
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40936-132, 34m Δ
  ublock-badware: 11675-1, 34m Δ
  ublock-privacy: 1424-22, 34m Δ
  ublock-unbreak: 2564-1, 34m Δ
  ublock-quick-fixes: 192-11, 34m Δ
  easylist: 78189-198, 34m Δ
  easyprivacy: 53271-71, 34m Δ
  urlhaus-1: 20720-0, 2h.10m
  plowe-0: 3557-1000, 2h.10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 771 ms (selfie)
 maxAssetCacheWait: 382 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  time.is: 2
  pub.network: 1
  quantserve.com: 1
 extended:
  ##.rad
  ##[data-freestar-ad][id]
</details>

**Comment by RedLight-Scratch** [comment]
It seems like `time.is###attention` fixes it

**Comment by stephenhawk8054** [comment]
Fixed in "uBlock filters – Annoyances" list.

**Comment by krystian3w** [comment]
It seems problem back on Android with Firefox 136 and uBo dev 1.63.3b5.

**Comment by krystian3w** [comment]
#time.is #26298
