### ISSUE TITLE
forocoches.com: breakage

### ISSUE THREAD

**Issue by Fierno** [uBlockOrigin/uAssets#26045]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://forocoches.com/`

### Category

breakage

### Description

uBlock is blocking the threads

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 130
filterset (summary):
 network: 140855
 cosmetic: 56025
 scriptlet: 23601
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40658-271, now
  ublock-badware: 12348-6, now
  ublock-privacy: 1445-22, now
  ublock-unbreak: 2506-0, now
  ublock-quick-fixes: 202-4, now
  easylist: 78174-643, now
  easyprivacy: 53268-663, now
  urlhaus-1: 20500-0, now
  plowe-0: 3557-0, now
  spa-0: 3686-4, now
  spa-1: 6096-199, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1194 ms
 maxAssetCacheWait: 15 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  adform.net: 1
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  opti-digital.com: 1
  sddan.com: 1
 extended:
  ###AutoNumber30
  ###notice-wrapper
  ##[align="center"]:has(div[id^="optidigital-adslot-"])
  ##tbody > tr > td[valign="top"]:has(div[id^="optidigital-adslot-…
  ###vbnotices
  ##div[id^="optidigital-adslot"]
  ##+js(abort-on-property-read, pbjsChunk)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25970
