### ISSUE TITLE
purplexity.ai: detection

### ISSUE THREAD

**Issue by 123SONIC321** [uBlockOrigin/uAssets#26047]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://purplexity.ai/`

### Category

detection

### Description

This website only works if ad blockers are disabled. Please disable ad block and refresh to continue.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

.

**Comment by stephenhawk8054** [comment]
I think you make typo to the website domain. I think you want to go to `https://www.perplexity.ai/`?

**Comment by stephenhawk8054** [comment]
It's better to not let users turning off uBO because of the warning on these sites, if the filters don't require whitelisting.

**Comment by gorhill** [comment]
@stephenhawk8054 Maybe we could have a list for parked sites that work like badware? At least this would be just a hostname-based filter like `||purplexity.ai^$doc` so as to not bloat the lists with complex filters. At the same time, visitors would be made aware this is a parked site with no value.

**Comment by stephenhawk8054** [comment]
@gorhill For the typosquat domains like this, it's ok to address in badware list, so another list is not really needed. But for other websites, I think blocking them are a bit too much. The point of addressing these anti-adb is also not to interrupt the experience when [the websites becomes active again](https://github.com/uBlockOrigin/uAssets/commit/219a567ce1a891cf06eacc3cbd3933c3d48ddb8e), like the variable `__parkour` will likely not appear if websites are active and the filters won't cause any further effects.
