### ISSUE TITLE
scribd.com: ads

### ISSUE THREAD

**Issue by Cyclamer** [uBlockOrigin/uAssets#26046]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.scribd.com/document/683094787/Pratical-Physics-by-Dr-Giasuddin-Ahmed-A`

### Category

ads

### Description

it shows ads while displaying pdfs.

### Other extensions used

violentmonkey with only a script for youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2024-11-14 174605](https://github.com/user-attachments/assets/0ac50baa-24a0-4a90-b38b-2fe7703aefdc)

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 130
filterset (summary):
 network: 138207
 cosmetic: 49733
 scriptlet: 23088
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40707-254, 15m Δ
  ublock-badware: 11673-1, 15m Δ
  ublock-privacy: 1449-22, 15m Δ
  ublock-unbreak: 2507-0, 15m Δ
  ublock-quick-fixes: 198-4, 15m Δ
  easylist: 78840-598, 15m Δ
  easyprivacy: 53271-652, 15m Δ
  urlhaus-1: 20500-0, now
  plowe-0: 3557-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 149 ms (selfie)
 maxAssetCacheWait: 32 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  scribd.com: 19
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 1
  pub.network: 1
  sentry-cdn.com: 1
  siftscience.com: 1
 extended:
  ##div[class]:has(> [data-e2e="dismissible-ad-header-scribd_adhes…
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/22656
