### ISSUE TITLE
video-igrice.com: ads

### ISSUE THREAD

**Issue by SaifulLukman** [uBlockOrigin/uAssets#26057]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.video-igrice.com/coloring-games-for-kids/`
https://prnt.sc/1rpOP5eejcfR

### Category

ads

### Description

Sometimes ads are also shown in the Talking Tom game. > https://www.video-igrice.com/talking-tom-funny-time/

### Other extensions used

nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 142434
 cosmetic: 55506
 scriptlet: 21411
 html: 2088
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40931-132, now
  ublock-badware: 11688-1, now
  ublock-privacy: 1435-22, now
  ublock-unbreak: 2564-1, now
  ublock-quick-fixes: 192-11, now
  easylist: 78846-201, now
  easyprivacy: 53271-71, now
  urlhaus-1: 20365-0, now
  plowe-0: 3557-1000, now
  IDN-0: 10199-27, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5184 ms
 maxAssetCacheWait: 51 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 2
  wgplayer.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(no-setTimeout-if, /Adb|moneyDetect/)
```
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
yiv.com##.GUIAdvertisement
```

**Comment by SaifulLukman** [comment]
Yes, it hides the ad.
