### ISSUE TITLE
hhdstreams.club: detection

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#26060]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hhdstreams.club/`

### Category

detection

### Description

See screenshot. Happens as soon as you enter the link, works if UBO is disabled

### Other extensions used

TWP

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/bd539713-6930-41c1-9e33-03b7e9385b8a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 138448
 cosmetic: 51335
 scriptlet: 25165
 html: 2382
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5901-34, 1h.29m
 default:
  user-filters: 150-2, never
  ublock-filters: 40937-132, 1h.29m
  ublock-badware: 11702-1, 1h.29m
  ublock-privacy: 1437-22, 1h.29m
  ublock-unbreak: 2565-1, 1h.29m
  easylist: 78860-201, 1h.29m
  easyprivacy: 53272-69, 1h.29m
  urlhaus-1: 20365-0, 1h.29m
  plowe-0: 3557-1000, 1h.29m
  ublock-quick-fixes: 201-11, 1h.29m
filterset (user): [array of 98 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 134 redacted]
hostRuleset:
 added: [array of 493 redacted]
urlRuleset:
 added: [array of 104 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 757 ms (selfie)
 maxAssetCacheWait: 77 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  google.com: 1
 extended:
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by Alphamen16** [comment]
![image](https://github.com/user-attachments/assets/5619fa64-3f2d-486d-baac-cd99126e394e)

**Comment by Alphamen16** [comment]
Oh, so it's useless now. WIll remove bookmark i guess, thanks!

**Comment by stephenhawk8054** [comment]
> Don't these all use the same IP?

Blocking based on IP can be good idea. But currently only available for FF.

**Comment by stephenhawk8054** [comment]
So if could be like this for FF:

```adb
*$doc,ipaddress=199.59.243.227,to=~parked.domain|hhdstreams.club
```

**Comment by stephenhawk8054** [comment]
Or maybe a generic cosmetic filter is better?

```adb
###target.pk-page-ready > #pk-status-message
```
