### ISSUE TITLE
pikabu.ru: breakage

### ISSUE THREAD

**Issue by 4815162342lost** [uBlockOrigin/uAssets#26065]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pikabu.ru/story/geshtalt_zakryit_12025907`

### Category

breakage

### Description

Issue occur only on mobile version of Firefox. On PC version no issue.

Sometimes (randomly) comments on site is not loaded. See screen.
https://github.com/user-attachments/assets/23d04ce5-2f8f-44ec-9660-626f731141cf

Issue occur randomly. Just go to https://pikabu.ru/best and open 5-10 posts.  Go to tab with post and read comments (swipe down) . And sometimes comments will not load.

### Other extensions used

No. On mobile i USE only uBlock Orign/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![photo_2024-11-16_20-13-55](https://github.com/user-attachments/assets/02dbe239-0af7-44ad-807c-4d5de56aca2c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 156870
 cosmetic: 70432
 scriptlet: 22893
 html: 2107
listset (total-discarded, last-updated):
 added:
  RUS-0: 41068-150, 1h.30m Δ
 default:
  user-filters: 2-0, never
  ublock-filters: 40874-132, 1h.30m Δ
  ublock-badware: 11720-1, 1h.30m Δ
  ublock-privacy: 1444-22, 1h.30m Δ
  ublock-unbreak: 2565-1, 1h.30m Δ
  easylist: 78897-577, 1h.30m Δ
  easyprivacy: 53276-689, 1h.30m Δ
  urlhaus-1: 20445-0, 1h.30m
  plowe-0: 3537-0, now
  ublock-quick-fixes: 206-10, 1h.30m Δ
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 27 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 260 ms (selfie)
 maxAssetCacheWait: 64 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  googletagmanager.com: 1
  tns-counter.ru: 1
  vk.com: 1
  yandex.ru: 9
 extended:
  ##.ads-placeholder
  ##.comments__adv
  ##.header-right-menu > a[href][target="_blank"]
  ##.sidebar-block_half
  ##.sidebar-block_placeholder
  ##.stories-feed__container > .story:has(> .story__placeholder)
  ##a[href*="//ads.adfox.ru/"]
  ###menu-subs > [href]::after
  ##.stories-feed__container > .story[data-author-name] ~ .story:n…
  ##div[id^="adfox_"]
  ##+js(abort-on-property-read, Object.prototype.loadBanner)
  ##+js(abort-on-property-read, Ya)
  ##+js(json-prune, data, errors)
  ##+js(json-prune, isVideoAutoplayMode swUrl)
  ##+js(remove-node-text, script, addPlaceholder)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by mapx-** [comment]
Did you test the site keeping uBO disabled ?

**Comment by 4815162342lost** [comment]
> Did you test the site keeping uBO disabled ?

Yes. With disabled uBO all works fine.

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This issue is best discussed here: https://github.com/easylist/ruadlist/issues
