### ISSUE TITLE
de.help.shokz.com: breakage

### ISSUE THREAD

**Issue by lonkamikaze** [uBlockOrigin/uAssets#26069]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://de.help.shokz.com/s/submit-case-form?recordType=Consultancy`

### Category

breakage

### Description

There is a whole contact form missing.

### Other extensions used

- Video DownloadHelper
-  reMarkable

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Enabled:
![image](https://github.com/user-attachments/assets/786360b4-0427-48b1-91ee-436dd30a4907)

Disabled:
![image](https://github.com/user-attachments/assets/017e1fde-7843-4acb-86b8-3bcc9d3ca464)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Firefox: 132
filterset (summary):
 network: 138201
 cosmetic: 49734
 scriptlet: 21344
 html: 2092
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40842-132, now
  ublock-badware: 11720-1, now
  ublock-privacy: 1433-22, now
  ublock-unbreak: 2565-1, now
  ublock-quick-fixes: 206-10, now
  easylist: 78923-202, now
  easyprivacy: 53276-69, now
  urlhaus-1: 20445-0, now
  plowe-0: 3537-996, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 97 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  ipgeolocation.io: 2
```
</details>

**Comment by mapx-** [comment]
add

```adb
@@||api.ipgeolocation.io/ipgeo?apiKey$xhr,domain=shokz.com
```
