### ISSUE TITLE
revijahak.hr: nuisance

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#26074]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://revijahak.hr/2024/11/17/sedamdeset-godina-tomosa-marka-za-sve-potrebe/`

### Category

nuisance

### Description

Cookie notice shown

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/14fec9cd-5db6-4dc2-aef9-de5c363ad004)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 270355
 cosmetic: 256308
 scriptlet: 55124
 html: 2381
listset (total-discarded, last-updated):
 added:
  https://o0.pages.dev/Lite/adblock.txt: 89572-0, 1m
  adguard-generic: 85731-10059, 1m
  adguard-spyware-url: 1788-132, 1m
  adguard-spyware: 100386-20332, 1m
  curben-phishing: 658-6, 1m
  adguard-cookies: 32526-102, now
  ublock-cookies-adguard: 1904-20, now
  fanboy-cookiemonster: 52229-4181, never
  ublock-cookies-easylist: 1904-1904, never
  adguard-social: 23154-50, 1m
  fanboy-social: 16812-765, 1m
  adguard-popup-overlays: 28013-2180, 1m
  [8 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 40827-240, 1h.7m Δ
  ublock-badware: 11717-80, 1h.7m Δ
  ublock-privacy: 1461-39, 1h.7m Δ
  ublock-unbreak: 2565-2, 1h.7m Δ
  ublock-quick-fixes: 206-10, 1h.7m Δ
  easylist: 78924-22427, 1h.7m Δ
  easyprivacy: 53256-40242, 1h.7m Δ
  urlhaus-1: 20350-0, 1m
  plowe-0: 3537-2446, 1m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 181 ms (selfie)
 maxAssetCacheWait: 123 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  revijahak.hr: 2
 extended:
  ##a[href^="https://twitter.com/intent/tweet/?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##.icon--share
  ##.share__link
```
</details>

**Comment by mapx-** [comment]
```adb
revijahak.hr##.modal-gdpr
revijahak.hr##html:style(overflow: auto !important)
```

@ryanbr
