### ISSUE TITLE
cnet.com: ads

### ISSUE THREAD

**Issue by RedLight-Scratch** [uBlockOrigin/uAssets#26076]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.cnet.com/home/internet/wi-fi-on-a-plane-which-airlines-offer-it-free-and-which-will-charge-you/
```

### Description

An ad appears embedded in the article
There are also embedded areas that link to other somewhat unrelated cnet articles, although these are less intrusive.
I have also tried this with only the default filter lists.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cnet ads](https://github.com/user-attachments/assets/3e3abf66-0fb4-4617-8c2b-469167e4a9bf)

</details>

### Configuration

uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 257709
 cosmetic: 257487
 scriptlet: 55989
 html: 2381
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 461-1, 14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2694-2, 14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 56-0, 14m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2078-1, 14m
  adguard-generic: 85685-4231, 14m
  adguard-spyware-url: 1788-250, 14m
  adguard-spyware: 100386-1543, 14m
  block-lan: 64-0, 13m
  curben-phishing: 658-1, 13m
  adguard-cookies: 32531-65, 13m
  ublock-cookies-adguard: 1904-20, 13m
  fanboy-cookiemonster: 68908-20744, 14m
  [14 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 40827-150, 14m
  ublock-badware: 11717-1, 14m
  ublock-privacy: 1461-75, 14m
  ublock-unbreak: 2565-1, 14m
  ublock-quick-fixes: 206-0, 3m
  easylist: 78924-2168, 14m
  easyprivacy: 53256-23799, 14m
  urlhaus-1: 20350-0, 14m
  plowe-0: 3537-1445, 13m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 44 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 added: [array of 5 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 5
hiddenSettings:
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 5
 filterAuthorMode: true
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 8782 ms
 maxAssetCacheWait: 121 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ###top-wrapper
  ##.ad
  ##div[id*="_MAIN_CONTENT_"][data-testid="region"]
  ##body .ad
  ##body:style(overflow: initial !important)
  #@##bottom-wrapper
  ##+js(trusted-click-element, button.fides-reject-all-button, , 5…
  ##+js(prevent-fetch, api.theathletic.com/graphql body:/PostEvent…
  ##+js(prevent-fetch, headers:x-nyt-entitlements)
  ##+js(set-constant, webkitRequestFileSystem, noopFunc)
  ##+js(set-constant, Navigator.prototype.joinParakeetInterestGrou…
  ##+js(set-constant, _adBlockCheck, true)

**Comment by mapx-** [comment]
add

```adb
cnet.com###MyFiAd
```
