### ISSUE TITLE
hianime.to: ads

### ISSUE THREAD

**Issue by CozyHQ** [uBlockOrigin/uAssets#26077]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hianime.to/home`

### Category

ads

### Description

Has "Want your Ads here?" Boxes on the front page and on anime

### Other extensions used

Allow right click, whatfont, violentmonkey, user-agent switcher, enable copy, bitwarden, etc

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chrome_ikBM5X54io](https://github.com/user-attachments/assets/5a3d3ed0-56ef-4e61-9543-ba5b5fab9432)
![chrome_QDImpYtvcu](https://github.com/user-attachments/assets/6ae1bf35-8862-4eea-bf8c-2d694b5215c6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 131
filterset (summary):
 network: 224548
 cosmetic: 178043
 scriptlet: 38845
 html: 0
listset (total-discarded, last-updated):
 added:
  ROU-1: 1420-1, now
  adguard-cookies: 32531-87, now
  adguard-mobile-app-banners: 5546-1130, now
  adguard-other-annoyances: 14578-373, now
  adguard-popup-overlays: 28013-2142, now
  adguard-spyware: 100386-24362, now
  adguard-spyware-url: 1788-9, now
  adguard-widgets: 2765-18, now
  easylist-annoyances: 4828-132, now
  easylist-chat: 216-0, now
  easylist-newsletters: 8066-28, now
  easylist-notifications: 3464-3, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 78924-567, 25m Δ
  easyprivacy: 53256-760, 25m Δ
  plowe-0: 3537-10, now
  ublock-badware: 11715-1, 25m Δ
  ublock-filters: 40552-698, 25m Δ
  ublock-privacy: 1475-144, 25m Δ
  ublock-quick-fixes: 213-4, 25m Δ
  ublock-unbreak: 2507-5, 25m Δ
  urlhaus-1: 20350-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3177 ms (selfie)
 maxAssetCacheWait: 401 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  sharethis.com: 2
 extended:
  ##.grecaptcha-badge[data-style]
  ##.grecaptcha-badge
  ##+js(prevent-window-open)
  ##+js(set-constant, devtoolsDetector.launch, noopFunc)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by mapx-** [comment]
```adb
hianime.to##.pizza
```
