### ISSUE TITLE
iframeTracker packaged inside Ultimate slider Wordpress Plugin

### ISSUE THREAD

**Issue by piotr-cz** [uBlockOrigin/uAssets#2608]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.etoilewebdesign.com/ultimate-slider/`

### Describe the issue

[iframeTracker jQuery Plugin](https://github.com/vincepare/iframeTracker-jquery) is used by [Ultimate slider](https://wordpress.org/plugins/ultimate-slider/) pluin for WordPress to track element blur event to stop video playback.
When uBlock blocks script from loading it, page throws `Uncaught TypeError: jQuery(...).iframeTracker is not a function` and breaks the site.

Test case: [Slider Demo Website](http://www.etoilewebdesign.com/ultimate-slider/)

### Screenshot(s)

`http://www.etoilewebdesign.com/ultimate-slider/`

### Versions

- Browser/version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- uBlock Origin version: 1.16.10

### Settings

- Default settings as of when installed the plugin

### Notes

Code used by plugin:
```js
	//Stop slider on video play
	jQuery('.ewd-us-video').iframeTracker({
		blurCallback: function(){
			clearInterval(ewd_slider.interval);
		},
	});
```

I suggest that the plugin is whitelisted when used inside WordPress Ultimate slide Plugin like so:
[`uAssets/filters/unbreak.txt`](https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt):
```
! This unbreaks iframeTracker jQuery Plugin when packaged with Ultimate slider Plugin for Wordpress
/wp-content/plugins/ultimate-slider/js/jquery.iframetracker.js$script,first-party
```

**Comment by mapx-** [comment]
Maybe you mean
`@@/wp-content/plugins/ultimate-slider/js/jquery.iframetracker.js$script,first-party`

@ryanbr

**Comment by piotr-cz** [comment]
Yes, this is probably what I mean.
Is it okay to prepare a pull request?

**Comment by piotr-cz** [comment]
Is https://github.com/easylist/easylist/tree/master/easyprivacy source of https://easylist.to/ privacy list?
I've tried to get in touch with them (no response) or add a thread on forums but there is some problem with reCAPTCHA integration and I can't register.
