### ISSUE TITLE
vyvymanga.net: nuisance

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#26089]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://vyvymanga.net/manga/great-zhou-immortal-officials`

### Category

nuisance

### Description

There are three issues with the site, all related to the development tools:

1. The console is always cleared.
2. The script vyvymanga.net/web/js/devtools-detector.js redirects you to Google.com when you try to use the developer tools.
3. If the script is blocked or unreachable, the site shows a "Disconnected" status, as though there's no internet connection, even though my connection is working properly. "[Violation] Forced reflow while executing JavaScript took"

### Other extensions used

Test with Google Chrome, no extensions, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-18 173709](https://github.com/user-attachments/assets/efb4aff3-9f11-43d2-a88d-c8932daaf3e8)

https://github.com/user-attachments/assets/64831768-b93d-4712-b94b-839a8727d0ee

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 131
filterset (summary):
 network: 151260
 cosmetic: 219775
 scriptlet: 38190
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32569-93, 21m
  ublock-cookies-adguard: 1905-0, 21m
  fanboy-cookiemonster: 52235-4106, 21m
  ublock-cookies-easylist: 1906-1903, 21m
  adguard-social: 23157-799, 21m
  fanboy-social: 17125-23, 21m
  adguard-popup-overlays: 28023-2950, 21m
  adguard-mobile-app-banners: 5547-1130, 21m
  adguard-other-annoyances: 14580-717, 21m
  adguard-widgets: 2765-20, 21m
  easylist-annoyances: 4820-138, 21m
  easylist-chat: 216-0, 21m
  [3 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 40608-141, 21m
  ublock-badware: 11777-1, 19m Δ
  ublock-privacy: 1473-22, 21m
  ublock-unbreak: 2507-1, 21m
  ublock-quick-fixes: 220-4, 19m Δ
  easylist: 78931-659, 1m Δ
  easyprivacy: 53259-873, 19m Δ
  urlhaus-1: 20630-0, 21m
  plowe-0: 3537-0, 21m
  DEU-0: 7799-23, 21m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 943 ms
 maxAssetCacheWait: 551 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  vyvymanga.net: 1
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
test

```adb
vyvymanga.net##+js(rmnt, script, window.location.href)
||vyvymanga.net/web/js/devtools-detector.js$script,1p
```

**Comment by big-cat-loaf** [comment]
No it doesn't work, this is tested with Ungoogled Chromium

https://github.com/user-attachments/assets/6125d57e-67a3-471e-8a59-607166e808f5

**Comment by D4niloMR** [comment]
On my end it works well on Firefox/Chrome

**Comment by stephenhawk8054** [comment]
The filters work fine for me on chromium

![image](https://github.com/user-attachments/assets/e36396a1-392c-4efe-b1ab-1e388ceaaa0c)

**Comment by dportvine** [comment]
@big-cat-loaf 

Can you add a screenshot of the **[Logger](https://github.com/gorhill/uBlock/wiki/The-logger)** like this one?

<details>
<summary>Screen</summary>

![2024-11-19_091240](https://github.com/user-attachments/assets/13c14270-3f7a-4c94-a351-fc4b2b48dc2f)
</details>

**Comment by mapx-** [comment]
@big-cat-loaf try resetting uBO to defaults, do not add any other list
