### ISSUE TITLE
rightmove.co.uk: ads

### ISSUE THREAD

**Issue by evomthgir** [uBlockOrigin/uAssets#26084]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION%5E1019&maxPrice=300000&sortType=6&propertyTypes=&includeSSTC=false&mustHave=&dontShow=&furnishTypes=&keywords=`

### Category

ads

### Description

Ad banners and sponsored content is showing on the page, the sponsored content looks similar to genuine listings  

### Other extensions used

I don't care about cookies and Privacy Badger are disabled, ads are coming up intermittently

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1040" alt="Screenshot 2024-11-18 at 10 26 35" src="https://github.com/user-attachments/assets/a84101db-2f69-4d47-9f91-d40ceb9bbf52">

<img width="1018" alt="Screenshot 2024-11-18 at 10 26 18" src="https://github.com/user-attachments/assets/12a773ba-0649-4180-afda-4f0b5dcb6ba1">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 138174
 cosmetic: 49767
 scriptlet: 21362
 html: 2134
listset (total-discarded, last-updated):
 default:
  user-filters: 60-7, never
  ublock-filters: 40897-135, now
  ublock-badware: 11719-1, now
  ublock-privacy: 1463-22, now
  ublock-unbreak: 2565-1, now
  ublock-quick-fixes: 208-10, now
  easylist: 78931-202, now
  easyprivacy: 53258-69, now
  urlhaus-1: 20385-0, now
  plowe-0: 3537-996, now
filterset (user): [array of 60 redacted]
trustedset:
 added: [array of 34 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 237 ms (selfie)
 maxAssetCacheWait: 90 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  elastic-cloud.com: 1
  fuseplatform.net: 2
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```adb
rightmove.co.uk##[id^="interstititalSlot"]
```
