### ISSUE TITLE
dash.infinityfree.com: detection

### ISSUE THREAD

**Issue by Gabriel7218** [uBlockOrigin/uAssets#26098]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dash.infinityfree.com/`

### Category

detection

### Description

it is detecting the uBlocker Origin

### Other extensions used

i'm only using this extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/f19de416-9b0c-4b51-a213-72975b732796)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 139531
 cosmetic: 53897
 scriptlet: 21912
 html: 2139
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40915-135, 2m Δ
  ublock-badware: 11813-1, 2m Δ
  ublock-privacy: 1470-22, 2m Δ
  ublock-unbreak: 2565-1, 2m Δ
  ublock-quick-fixes: 212-10, 2m Δ
  easylist: 78953-203, 2m Δ
  easyprivacy: 53260-69, 2m Δ
  urlhaus-1: 20325-0, now
  plowe-0: 3537-996, now
  spa-1: 6100-88, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 822 ms (selfie)
 maxAssetCacheWait: 162 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  cloudflareinsights.com: 2
  error-report.com: 1
  fuseplatform.net: 2
  google.com: 7
  googlesyndication.com: 1
  googletagmanager.com: 1
  html-load.com: 5
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##+js(trusted-replace-argument, String.prototype.includes, 0, ''…
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25178
