### ISSUE TITLE
Kim Cartoon is now detecting Ublock Origin

### ISSUE THREAD

**Issue by Charred01** [uBlockOrigin/uAssets#2609]
Even with Nano Defender installed.  Only detects when playing with the Kimcartoon Beta player

**Comment by mapx-** [comment]
Provide example link (and how to test the beta player)

**Comment by elpanoli** [comment]
The same for me, I get an anti-adblock warning
`http://kimcartoon.me/Cartoon/Marvel-s-Spider-Man-Season-2/Episode-1?id=84674&s=beta`

**Comment by uBlock-user** [comment]
@elpanoli Add k`imcartoon.me##.top_page_alert`

**Comment by gwarser** [comment]
This may be the cause:

>429. That’s an error.

>The rate limit for this service has been exceeded. That’s all we know.

**Comment by uBlock-user** [comment]
@gwarser that's from Google's servers, not related to anti adblock in any way.

**Comment by elpanoli** [comment]
@uBlock-user That only hides the warning, the player does not work, if I disable ublock then it does work.

**Comment by uBlock-user** [comment]
Did you force update uBlock Filters - Unbreak list ? Easylist filter broke the player which was discussed here - https://github.com/uBlockOrigin/uAssets/commit/466f0b90796f221826738d71e57519140e6af5e3

**Comment by elpanoli** [comment]
@uBlock-user Nothing. I've updated the filters and it's not working.
