### ISSUE TITLE
pluralsight.com: breakage

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#26096]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.pluralsight.com/pricing/skills?type=individual
```

### Description

With uBlock Origin active, I cannot complete the purchase of any individual subscription.
By disabling uBlock Origin, the purchase goes through successfully.

### Other extensions used

- Bitwarden Password Manager
- Fakespot Fake Amazon Reviews and eBay Sellers
- Grammarly: AI Writing and Grammar Checker App
- Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://github.com/user-attachments/assets/6b1f6ff8-a89a-4e40-824a-ff153c736018)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 140215
 cosmetic: 56765
 scriptlet: 21370
 html: 2139
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40910-136, 58m Δ
  ublock-badware: 11787-1, 58m Δ
  ublock-privacy: 1470-22, 58m Δ
  ublock-unbreak: 2565-0, 58m Δ
  ublock-quick-fixes: 212-10, 58m Δ
  easylist: 78953-203, 58m Δ
  easyprivacy: 53260-69, 58m Δ
  urlhaus-1: 20630-0, 9h.52m
  plowe-0: 3537-996, 1d.23h.52m
  ITA-0: 8787-42, 9h.52m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 93 ms (selfie)
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
-
