### ISSUE TITLE
lineupexperts.com: detection

### ISSUE THREAD

**Issue by whothefvckk** [uBlockOrigin/uAssets#26103]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lineupexperts.com/account_ad_blocker.php?&type=r&origin=https%3A%2F%2Fwww.lineupexperts.com%2Faccount_team_optimize_lineup.php%3Flid%3DZmLmAQZkZmNmAN%253D%253D7ss603849or7nr4182s9384s97p9o824%26tid%3DZmRmAwZlZmNmBGZ0Zmt%253D6q0o2n4q1r980ooo686208q5pp4nr9s3%26flt_proj_time_period%3DToday`

### Category

detection

### Description

lineupexperts.com detects uBO. Attempted to block all trackers/ad domains associated with the site and it still detects it.

### Other extensions used

Dark Reader
Translate Web Pages
Auto Clear Browsing Data
Enhancer for YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 122
filterset (summary):
 network: 148985
 cosmetic: 214074
 scriptlet: 38216
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32580-41, now
  adguard-mobile-app-banners: 5556-23, now
  adguard-other-annoyances: 14588-383, now
  adguard-popup-overlays: 28029-1342, now
  adguard-social: 23160-1583, now
  adguard-widgets: 2771-18, now
  easylist-annoyances: 4805-53, now
  easylist-chat: 217-0, now
  easylist-newsletters: 8071-32, now
  easylist-notifications: 3464-1201, now
  fanboy-cookiemonster: 52238-4095, now
  fanboy-social: 16814-7, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 206-7, never
  easylist: 78987-557, now
  easyprivacy: 53263-1597, now
  plowe-0: 3537-1, now
  ublock-badware: 11863-1, now
  ublock-filters: 40623-692, now
  ublock-privacy: 1486-23, now
  ublock-quick-fixes: 222-4, now
  ublock-unbreak: 2507-2, now
  urlhaus-1: 20325-0, now
filterset (user): [array of 206 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 964 ms (selfie)
 maxAssetCacheWait: 257 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  lineupexperts.com: 3
  googlesyndication.com: 6
  googletagmanager.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Please describe the steps to reproduce in the most details as possible.

**Comment by stephenhawk8054** [comment]
> try to use any of their tools

> describe the steps to reproduce in the most details as possible

Please don't assume others are familiar with your site.

I have logged in here:

![image](https://github.com/user-attachments/assets/5ccdfd14-e7d1-4c9e-a3a7-f478ca3a7226)

What should I click next? Please give detailed steps of what buttons should I click.

**Comment by whothefvckk** [comment]
> > Click "Your Leagues", choose a league
> 
> When I click on `Your Leagues`, it just shows `Sync a new leage`
> 
> ![image](https://private-user-images.githubusercontent.com/66517106/388159380-9f9b9826-41e2-4675-8f37-ef938a0bd44a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTI3MTcsIm5iZiI6MTczMjE1MjQxNywicGF0aCI6Ii82NjUxNzEwNi8zODgxNTkzODAtOWY5Yjk4MjYtNDFlMi00Njc1LThmMzctZWY5MzhhMGJkNDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAxMjY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MzA4ZDM5NTZiMzllYmNmN2U5MjRkOGRkZjQ0Y2E2ZDZhMjZhYmUwNjc0NTVkODdjNGExMjIzMmY3NzNjY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yd2ALw25tPf3SqSAjkwDxzVRF2Bz-294nbSNUiXgZTQ)

You need to have a Yahoo Fantasy Sports account, then login through Lineup Experts to sync a league. You won't be able to do it without a Yahoo Fantasy Sports account.

**Comment by stephenhawk8054** [comment]
> Yahoo Fantasy Sports account

What is the link to create that account?

**Comment by whothefvckk** [comment]
> meanwhile does this work ?
> 
> ```
> lineupexperts.com##+js(no-fetch-if, googlesyndication)
> ```

Where would I put this string? In my filters?

**Comment by whothefvckk** [comment]
> > > meanwhile does this work ?
> > > ```
> > > lineupexperts.com##+js(no-fetch-if, googlesyndication)
> > > ```
> > 
> > 
> > Where would I put this string? In my filters?
> 
> yeah you have to go into ublock settings> my filters > add above filter >Apply Changes > clear cookie & test site in a new window

Thanks for trying, but this did not work.

**Comment by stephenhawk8054** [comment]
> > What is the link to create that account?
> 
> a normal yahoo account

I know it's Yahoo, but what is "Yahoo fantasy sport". When I search it, I see 2 links:

1. https://sports.yahoo.com/fantasy/
2. https://football.fantasysports.yahoo.com/

What is the right link?

**Comment by mapx-** [comment]
@stephenhawk8054 you should join a league, I joined this 1 and you could try this invitation

https://basketball.fantasysports.yahoo.com/nba/254704/invitation

**Comment by mapx-** [comment]
@whothefvckk you could provide us an invitation for a working league to reproduce the detection

**Comment by dokaebii** [comment]
> #26525

Apologies, I am new to posting and thought I wasn't allowed to post in closed issue threads. 


@MasterKia I reset uBO to default settings. I was able to replicate the issue for my existing lineupexperts.com account only. I tried reproducing the issue with a newly created account and it appears to function without a problem.

I guess there's something that has flagged my account to detect when uBO is active as I can only reproduce this issue when logged into my own account with uBO active.

**Comment by dokaebii** [comment]
Sure, I don't mind.

**Comment by c-do** [comment]
Looks like they have updated their blocking as I am getting the same issue again.

**Comment by stephenhawk8054** [comment]
We can't investigate without accounts. If you are willing to share account credentials, I'll give you an email.
