### ISSUE TITLE
Solution: uBlock Origins Causing Formatting Issues on TvTropes

### ISSUE THREAD

**Issue by entourian** [uBlockOrigin/uAssets#2610]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

TvTropes.org/*

### Describe the issue

When uBlock Origins was enabled, the TvTropes Ad Platform "Instant Logic" and their Advertisers 'g00' were causing redirects to procedurally generated redirect links, which broke internal page links, pictures, trope names, and caused general weirdness on other pages. 

### Versions

- Browser/version: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- uBlock Origin version: 1.16.10

### Solution/Workaround

I found a work around to the g00 issue that was occuring in TvTropes. Please see below.

Please add the following lines to your "uBlock Origins" "My Filters" list:

`tvtropes.org#@#script:inject(abort-on-property-read.js, Uint8Array)`

`||tvtropes.org^$subdocument,first-party`

`tvtropes.org##iframe`

`tvtropes.org##div > a[href="#report-ad"]`

`tvtropes.org##.sticky-btm`

`tvtropes.org##script:inject(abort-current-inline-script.js, atob, INSTART)`

This however, breaks reCaptcha. Which I found can be solved by adding the following lines to your "uBlock Origins" "My Filters" list:

`@@www.google.com/recaptcha*`

`@@www.gstatic.com/recaptcha*`

`tvtropes.ord##rc-anchor-center-container`

**Comment by uBlock-user** [comment]
Just install `uBO-Extra` and `g00` will stop.
