### ISSUE TITLE
cbc.ca: ads

### ISSUE THREAD

**Issue by thedev2203** [uBlockOrigin/uAssets#26109]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cbc.ca/news`

### Category

ads

### Description

An advertisement leftover is displayed. 

Steps to Reproduce:
1. Scroll down and click "Load More" 

### Other extensions used

None

### Screenshot(s)

https://github.com/user-attachments/assets/4ecbab69-f8e4-4d7f-8345-14a08cef74a6
https://github.com/user-attachments/assets/afbe7b2d-109b-4191-9b95-fb17c5c5212c

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 137927
 cosmetic: 49713
 scriptlet: 21342
 html: 2134
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40897-135, now Δ
  ublock-badware: 11904-1, now
  ublock-privacy: 1442-22, now Δ
  ublock-unbreak: 2565-20, now
  ublock-quick-fixes: 199-10, now Δ
  easylist: 78868-598, now Δ
  easyprivacy: 53272-26, now Δ
  urlhaus-1: 20010-0, now
  plowe-0: 3537-623, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2458 ms
 maxAssetCacheWait: 1117 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  cbc.ca: 12
  adlightning.com: 2
  chartbeat.com: 2
  conductrics.com: 1
  cxense.com: 1
  demdex.net: 5
  doubleclick.net: 1
  imasdk.googleapis.com: 1
  radio-canada.ca: 1
  scorecardresearch.com: 1
  sentry-cdn.com: 1
  sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
Which are ads (leftover ?!) ? the ones in the red border?

**Comment by mapx-** [comment]
I see it only if I disable uBO.

Reset uBO to defaults, do not touch any setting, test again
