### ISSUE TITLE
winfuture.de: breakage

### ISSUE THREAD

**Issue by sweethoneybeee** [uBlockOrigin/uAssets#26101]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://winfuture.de/`

### Category

breakage

### Description

Can´t open Winfuture.de anymore without deaktivating uBO.

### Other extensions used

Real-Debrid, JDownloader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Message](https://github.com/user-attachments/assets/1e2e9e99-5e5d-48f3-989d-a847373effdb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 126
filterset (summary):
 network: 140634
 cosmetic: 55175
 scriptlet: 23081
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 40622-270, 1h.21m Δ
  ublock-badware: 11861-1, 1h.21m Δ
  ublock-privacy: 1485-22, 1h.21m Δ
  ublock-unbreak: 2507-0, 1h.21m Δ
  ublock-quick-fixes: 222-4, 1h.21m Δ
  easylist: 78978-611, 1h.21m Δ
  easyprivacy: 53263-654, 1h.21m Δ
  urlhaus-1: 20325-0, now
  plowe-0: 3537-0, now
  DEU-0: 7799-3, now
filterset (user): [array of 4 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 331 ms (selfie)
 maxAssetCacheWait: 93 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  consentmanager.net: 1
  criteo.net: 2
  googlesyndication.com: 2
  html-load.com: 2
  qualitymedianetwork.de: 1
 extended:
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(json-prune, adtagparameter, enabled)
  ##+js(no-setTimeout-if, error-report.com)
  ##+js(remove-node-text, script, error-report.com)
```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/25560
