### ISSUE TITLE
uploadfox.net: badware

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#26102]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uploadfox.net/vfgqcgsqgk9q`

### Category

badware

### Description

this site serves .exe which is malicious when clicked on free download

detection = 

`https://www.virustotal.com/gui/file/a5db6404a86d083afa17a2929c8c4174d8d9a6e3ef86cc9c2cc68b2f547e778f/summary`

`https://www.virustotal.com/gui/url/07345eb44c1a7b83afa90024eac5dd831f766524785dfdb3d20528a76ff2889d?nocache=1`

it has infected win os
![opera_aXnelBI8Jp_084259](https://github.com/user-attachments/assets/2f6a4615-8b1a-4419-b977-a3a8995904c7)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox Mobile: 134
filterset (summary):
 network: 139735
 cosmetic: 58437
 scriptlet: 21447
 html: 2144
listset (total-discarded, last-updated):
 default:
  user-filters: 16-0, never
  ublock-filters: 41430-138, 3m Δ
  ublock-badware: 11857-1, 3m Δ
  ublock-privacy: 1472-22, 3m Δ
  ublock-unbreak: 2567-1, 3m Δ
  ublock-quick-fixes: 214-10, 3m Δ
  adguard-mobile: 9939-179, 3m
  easylist: 78978-643, 3m Δ
  easyprivacy: 53263-697, 3m Δ
  urlhaus-1: 20325-0, 3m
  plowe-0: 3537-0, now
filterset (user): [array of 17 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 699 ms (selfie)
 maxAssetCacheWait: 171 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 1
  hotjar.com: 1
  plausible.io: 2
```
</details>

**Comment by Yuki2718** [comment]
Looks to be an uploader, serveing benigh files too. I think the best to only hide the bad link `uploadfox.net###downloadxaa`.

**Comment by Alex-302** [comment]
Maybe this?
```adblock
uploadfox.net##div[id^="qs-ad-"]
```

The first click starts "the loader" downloading, the second - opens the download page with a timer (that rule applied here for the fake image button).

The requested file may be downloaded:
![image](https://github.com/user-attachments/assets/97eea5a3-94d5-4c00-b471-ca93dd2774fb)

**Comment by Yuki2718** [comment]
> Maybe this?

Oh, yes, that link is hidden too by the rule @ghajini added. But the blue "Create download link" button downloads wanted .mp4 file after timer. Maybe `uploadfox.net##+js(nano-stb, tick, 1000)` or a css filter can be added (haven't tested, as required to wait long).

**Comment by Alex-302** [comment]
Btw the loader works)

![image](https://github.com/user-attachments/assets/d817c153-de65-4424-94ae-108653601912)

Did not check network activity. But popular antiviruses don't triggered. Maybe they use EXE packer.
