### ISSUE TITLE
nxbrew.net: detection

### ISSUE THREAD

**Issue by Kenryoku95** [uBlockOrigin/uAssets#26104]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://nxbrew.net
```

### Description

The site has changed domain and now shows this notice:
Ads Blocker Detected!!!
We have detected that you are using extensions to block ads. Please support us by disabling these ads blocker.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/cfd18128-38a8-473e-b507-95eed6b9575a)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.61.0
Chromium: 131
filterset (summary):
 network: 227602
 cosmetic: 249335
 scriptlet: 51801
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85822-6738, now
  adguard-mobile: 9939-110, now
  adguard-cookies: 32580-70, now
  ublock-cookies-adguard: 1907-0, now
  fanboy-cookiemonster: 52238-4072, now
  ublock-cookies-easylist: 1907-1907, now
  CHN-0: 25667-93, now
  DEU-0: 7799-37, now
  FRA-0: 25723-470, now
  IDN-0: 10208-26, now
  JPN-1: 15484-105, now
  RUS-0: 41048-292, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 57-5, never
  ublock-filters: 40624-186, now
  ublock-badware: 11863-1, now
  ublock-privacy: 1486-22, now
  ublock-unbreak: 2507-1, now
  ublock-quick-fixes: 222-4, now
  easylist: 78987-864, now
  easyprivacy: 53263-788, now
  urlhaus-1: 20325-0, now
  plowe-0: 3537-0, now
  ITA-0: 8789-93, now
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 115 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1911 ms
 maxAssetCacheWait: 850 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  nxbrew.net: 1
  googlesyndication.com: 2
  histats.com: 1
 extended:
  ##a[id][href="https://toolkitspro.com"][rel^="noopener noreferre…
  ##a[id][href="https://toolkitspro.com"][rel="noopener noreferrer…
```
</details>

**Comment by MelonCakey** [comment]
Similar detection popup for me today, screenshot is attached. Like OP, not using anything custom or extra on uBO.

![Image](https://github.com/user-attachments/assets/c6241c98-2685-498a-a2ae-79ab7623f1ff)

**Comment by SwiftWinds** [comment]
It seems to be a problem again.

For example:

https://nxbrew.net/mario-party-superstars-switch-xci-update/

![Image](https://github.com/user-attachments/assets/cad19070-daf5-4fc7-b5f9-4d60283d2953)

**Comment by stephenhawk8054** [comment]
Update your filter lists (go to `Filter lists` tab, click on the clock icon at the end of `uBlock filters`), open new tab and test again.
