### ISSUE TITLE
nxbrew.net: detection

### ISSUE THREAD

**Issue by Ozzy-Dingo** [uBlockOrigin/uAssets#26107]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://nxbrew.net/life-is-strange-double-exposure-switch-nsp-update-eshop/`

### Category

detection

### Description

![nxbrew_net_adblockdetection](https://github.com/user-attachments/assets/2bf20cbb-6a16-4ebf-8f8b-d537c735157c)

### Other extensions used

![image](https://github.com/user-attachments/assets/44be3a83-e2ec-48fc-9c7b-36f751dc3d84)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e71e33dd-8ddf-4213-bc2a-b7d924fce33b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 131
filterset (summary):
 network: 138003
 cosmetic: 49746
 scriptlet: 23083
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40624-252, 6m Δ
  ublock-badware: 11863-1, 6m Δ
  ublock-privacy: 1486-22, 6m Δ
  ublock-unbreak: 2507-0, 6m Δ
  ublock-quick-fixes: 222-4, 6m Δ
  easylist: 78987-600, 6m Δ
  easyprivacy: 53263-646, 6m Δ
  urlhaus-1: 20010-0, now
  plowe-0: 3537-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 330 ms (selfie)
 maxAssetCacheWait: 31 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  condemnfundraiserjune.com: 1
  googlesyndication.com: 2
  histats.com: 1
  ouo.io: 1
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
