### ISSUE TITLE
lttstore.com: breakage

### ISSUE THREAD

**Issue by BigFlubba** [uBlockOrigin/uAssets#26110]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.lttstore.com/pages/circuit-board`

### Category

breakage

### Description

When visiting the site scrolling for products and clicking on the faq don't work as intended.

### Other extensions used

https://github.com/user-attachments/assets/3f6ff4cf-d682-414d-986f-d353e2945335

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241120_040014_Firefox Beta](https://github.com/user-attachments/assets/c4ce6cb1-67a4-48aa-84dd-8954857c7f4d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox Mobile: 133
filterset (summary):
 network: 139488
 cosmetic: 58445
 scriptlet: 21441
 html: 2144
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41435-217, 4m Δ
  ublock-badware: 11908-2, 4m Δ
  ublock-privacy: 1483-22, 4m Δ
  ublock-unbreak: 2567-3, 4m Δ
  ublock-quick-fixes: 211-10, 4m Δ
  adguard-mobile: 9939-12, now
  easylist: 78997-275, 4m Δ
  easyprivacy: 53263-78, 4m Δ
  urlhaus-1: 20010-0, 3m
  plowe-0: 3537-1070, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 873 ms (selfie)
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  lttstore.com: 11
  google-analytics.com: 1
  googletagmanager.com: 1
  klaviyo.com: 2
  shopifysvc.com: 1
```
</details>

**Comment by mapx-** [comment]
I don't understand, what's wrong on your side ?

**Comment by stephenhawk8054** [comment]
Reset uBO to default settings and test again.

**Comment by stephenhawk8054** [comment]
Can you screenshot extensions' list in the browser?

**Comment by stephenhawk8054** [comment]
Turn off all other extensions, except uBO, restart the browser and test again.

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I have verified that other extensions are not causing the issue.
