### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by dani7959** [uBlockOrigin/uAssets#26115]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://outlook.live.com/
```

### Description

The current uBO filters (including uBlock filters – Annoyances) successfuly block all ads however space is still wasted in two places:
- the ad placeholder when using Mailbox Ads
- the ad placeholder above the mailbox when using Banner Ads.
Also the unsubscribe prompts, which are just crap IMHO are still there.

![mailbox](https://github.com/user-attachments/assets/0b7af7b3-7d76-4dae-88fa-9563fe15deb3)

![topside](https://github.com/user-attachments/assets/d93114e4-dc63-4334-8236-44ca67c814a6)

![unsubscribe](https://github.com/user-attachments/assets/fede6737-6ae7-47da-b9df-6cfda15a200a)

I though about sharing my own filters which create a fully ad free experience for Outlook.com, feel free to use them or not.

```
! Hide right side Banner Ads.
outlook.live.com##div[id="MainModule"] > div > div > div:has( > div > div > span:has-text(Ad Choices))
! Hide bottom side Banner Ads (visible on narrower viewports).
outlook.live.com##div[id="mainApp"] > div > div > div:has( > div > div > span:has-text(Ad Choices))
! Hide top side Banner Ads.
outlook.live.com##div[id="Skip to message list-region"] > div[id]:not([id="MailList"])
! Hide Mailbox Ads.
outlook.live.com##div[id="MailList"] > div > div > div > div > div > div > div > div:has( > div > div:not([data-convid]))
! Hide everything in the reading pane except emails (such as the mobile app QR code)
outlook.live.com##div[id="ReadingPaneContainerId"] > div > div > div > div:not([id="ItemReadingPaneContainer"])
! Hide the message bar under the email header (containing things such as unsubscribe prompts).
outlook.live.com##div[class^="fui-MessageBarGroup"]
```

I've seen [23933](https://github.com/uBlockOrigin/uAssets/issues/23933) please merge if you consider.

### Other extensions used

None

### Configuration

Edge 131, uBO 1.61, lists update 20.11.2024

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
