### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by Sarisisop** [uBlockOrigin/uAssets#26116]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deezer.com/`

### Category

breakage

### Description

Since yesterday Deezer will not play, I have tried default settings and stopped all other add-ons. Cleared cookies and cache when I turn uBO off it works, and ad comes up first then the music starts playing. 

Firefox Linux Mint 132.0.1 

France.

Thank you. 

### Other extensions used

All disabled to test

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 275181
 cosmetic: 271041
 scriptlet: 55476
 html: 2407
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85829-4265, 1h.46m
  adguard-mobile: 9939-59, 1h.46m
  adguard-spyware-url: 1794-132, 1h.46m
  adguard-spyware: 106889-1552, 1h.46m
  block-lan: 64-0, 1h.46m
  curben-phishing: 582-1, 1h.46m
  adguard-cookies: 32597-67, 1h.46m
  ublock-cookies-adguard: 1907-20, 1h.46m
  fanboy-cookiemonster: 52238-4069, 1h.46m
  ublock-cookies-easylist: 1907-1907, 1h.46m
  adguard-social: 23163-52, 1h.46m
  fanboy-social: 16815-768, 1h.46m
  [12 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40924-136, 48m Δ
  ublock-badware: 11914-1, 48m Δ
  ublock-privacy: 1483-22, 1h.48m
  ublock-unbreak: 2565-2, 1h.48m
  ublock-quick-fixes: 211-10, 1h.48m
  easylist: 78953-2230, 48m Δ
  easyprivacy: 53263-29856, 48m Δ
  urlhaus-1: 20155-0, 1h.48m
  plowe-0: 3537-1497, 1h.48m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1371 ms
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 1
  dzcdn.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  segment.com: 1
  sentry.io: 3
 extended:
  ##.css-128ibte.chakra-stack
  ##+js(abort-on-property-read, onbeforeunload)
  ##+js(trusted-click-element, .chakra-portal .chakra-modal__conte…
  ##+js(no-setTimeout-if, bait)
  ##+js(json-prune-fetch-response, results, , propsToMatch, deezer…
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

**Comment by Sarisisop** [comment]
Sorry I did see those but they say "Unable to Reproduce" I thought giving more information may help. 

Should I have posted in one of those rather than start a new one ?

**Comment by Sarisisop** [comment]
Ok sorry, noted for future reference.
