### ISSUE TITLE
colonist.io: detection

### ISSUE THREAD

**Issue by aishot** [uBlockOrigin/uAssets#26119]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://colonist.io/`

### Category

[unknown]

### Description

Ad blocker detection. Must disable to use page

### Other extensions used

Tamper monkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 131
filterset (summary):
 network: 138291
 cosmetic: 49760
 scriptlet: 23084
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40632-133, now
  ublock-badware: 11965-1, now
  ublock-privacy: 1497-23, now
  ublock-unbreak: 2507-1, now
  ublock-quick-fixes: 219-12, 1m
  easylist: 79029-601, now
  easyprivacy: 53263-755, now
  urlhaus-1: 20155-0, now
  plowe-0: 3537-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 822 ms
 maxAssetCacheWait: 193 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  colonist.io: 1
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

How do you trigger the anti-blocker? Do you need to be logged in?

I have a lot more stuff blocked on my side, and no anti-blocker:

```
popupPanel:
 blocked: 12
 network:
  colonist.io: 1
  cloudflareinsights.com: 1
  googleoptimize.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  jsdelivr.net: 1
  sentry.io: 3
  vlitag.com: 2
```

**Comment by stephenhawk8054** [comment]
@aishot Respect the prerequisites please:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

There are [a lot of same duplicated issues of this site](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+colonist.io)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/20649
