### ISSUE TITLE
[nsfw] bestthots.com: ads

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#26118]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bestthots.com/dystorra`
`https://leakedzone.com/dystorra`

### Category

ads

### Description

Many ads

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/user-attachments/assets/3d87373c-cf6c-4f55-8f92-9d24c29a1cb3

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox Mobile: 132
filterset (summary):
 network: 509062
 cosmetic: 220899
 scriptlet: 39048
 html: 2374
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl: 138675-0, 13m
  https://divested.dev/blocklists/Fingerprinting.ubl: 66-1, now
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1085-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 109831-245, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2688-2, now
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 456-34, 13m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 87711-40170, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4299-36, now
  adguard-spyware-url: 1794-250, now
  block-lan: 64-0, now
  curben-phishing: 582-34, now
  [16 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 41396-365, now
  ublock-badware: 11961-1481, now
  ublock-privacy: 1484-105, now
  ublock-unbreak: 2567-3, now
  ublock-quick-fixes: 211-15, 14m Δ
  adguard-mobile: 9941-771, now
  easylist: 79029-28003, now
  easyprivacy: 53263-9556, now
  urlhaus-1: 20155-332, now
  plowe-0: 3537-3007, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 4 redacted]
 removed:
  no-large-media: behind-the-scene false
userSettings:
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4322 ms
 maxAssetCacheWait: 2014 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  qzzzzzzzzzqq.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```adb
bestthots.com##[href^="https://v6.realxxx.com/"]
```

@ryanbr
