### ISSUE TITLE
uBlock is blocking some features on Gogoanime

### ISSUE THREAD

**Issue by ShingoukiSon** [uBlockOrigin/uAssets#2611]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

[https://www2.gogoanime.se]

### Describe the issue

[uBlock blocks the episode selecter, the server choosing and the search bar]

### Screenshot(s)

[
![screenshot-2018-6-19 watch anime online english anime online - gogoanime](https://user-images.githubusercontent.com/39024675/41611912-0234cdd0-73fa-11e8-932e-7a3386d3352a.png)
![screenshot-2018-6-19 page not found](https://user-images.githubusercontent.com/39024675/41611921-06600a46-73fa-11e8-9f0f-a3e2c4648555.png)
![screenshot-2018-6-19 list all anime at gogoanime anime list](https://user-images.githubusercontent.com/39024675/41611924-077a682c-73fa-11e8-9cb2-4fab5f1321a3.png)
![screenshot-2018-6-19 captain tsubasa 2018 at gogoanime](https://user-images.githubusercontent.com/39024675/41611932-0bd3a122-73fa-11e8-88a0-4da6c6aa21bd.png)
![screenshot-2018-6-19 watch captain tsubasa 2018 episode 12 english subbedat gogoanime](https://user-images.githubusercontent.com/39024675/41611934-0d0de00c-73fa-11e8-823b-84f602285ed6.png)]

### Versions

- Browser/version: [Firefox Quantum Version 60.0.2 64 Bits Edition ]
- uBlock Origin version: [1.16.10]

### Settings

- [no changes]

### Notes

[If i eliminate uBlock from my Add-ons, install it again and restart the browser, it would work like it used to for about an hour.]

**Comment by zaphodbeebblebrox** [comment]
@okiehsch there is another one `/^https?:\/\/([0-9a-z\-]+\.)?(9anime|animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime|igg-games|kimcartoon|memecenter|readcomiconline|toonget|toonova)\.[a-z]{2,4}\/(?!([Ss]cripts|[Uu]ploads|[Ii]mages|assets|combined|content|cover|img|static|thumbs|wp-content|wp-includes))(.*)/$first-party,script` that is breaking at the very least, animeland.tv

**Comment by okiehsch** [comment]
They are trying to fix the `bebi-reinsertion` script and in the process breaking some sites.

**Comment by okiehsch** [comment]
I will just disable them from now on I have better things to do then to check the sites for breakage.
