### ISSUE TITLE
traderepublic.community: detection

### ISSUE THREAD

**Issue by ckuenzle** [uBlockOrigin/uAssets#26113]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.traderepublic.community/threads/zahlungen-von-dividenden.129/`

### Category

detection

### Description

The website detects that I am using uBlock Origin. It displays a popup that demands me to create an account or to disable the ad blocker.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-20 at 14-48-08 Dividenden Termine Zahlungen Infos Trade Republic Forum](https://github.com/user-attachments/assets/8413a921-eebe-4847-b38c-d29fca8afe2a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 140580
 cosmetic: 55245
 scriptlet: 21372
 html: 2142
listset (total-discarded, last-updated):
 default:
  user-filters: 66-1, never
  ublock-filters: 40922-135, 8m Δ
  ublock-badware: 11967-1, 8m Δ
  ublock-privacy: 1483-22, 8m Δ
  ublock-unbreak: 2565-1, 8m Δ
  easylist: 78997-202, 8m Δ
  easyprivacy: 53263-69, 8m Δ
  urlhaus-1: 20155-0, now
  plowe-0: 3537-996, now
  DEU-0: 7799-40, now
  ublock-quick-fixes: 211-11, 8m Δ
filterset (user): [array of 66 redacted]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 18 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 541 ms (selfie)
 maxAssetCacheWait: 62 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  traderepublic.community: 1
  google.com: 7
  googlesyndication.com: 9
  googletagmanager.com: 1
 extended:
  ##.samCodeUnit
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ##a[href^="https://www.financeads.net/tc.php?"]
  ##+js(no-setTimeout-if, show)
```
</details>

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues/12746
