### ISSUE TITLE
pcpartpicker.com: breakage

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [uBlockOrigin/uAssets#26126]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://pcpartpicker.com/product/RKYmP6/samsung-990-pro-4-tb-m2-2280-pcie-40-x4-nvme-solid-state-drive-mz-v9p4t0bw
```

### Description

Links (_Newegg_, _Best Buy_, _Samsung_) are blocked by _**Peter Lowe’s Ad and tracking server list**_...

My suggestion:
`||linksynergy.com^$badfilter`
`||bestbuy.7tiv.net^$badfilter`

(no need to add `||linksynergy.com^$third-party`, it's in _EasyPrivacy_)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
They are click trackers so I don't think we will unblock it.

I'll add `urlskip` filter to show the destination links to users. That's the most we can do.

**Comment by Hebrew-uBO-User** [comment]
@stephenhawk8054 
Can the Best Buy links be fixed that way too?

**Comment by Hebrew-uBO-User** [comment]
@stephenhawk8054 
I get this message when I click on the Best Buy link:

uBlock Origin has prevented the following page from loading:
`https://bestbuy.7tiv.net/c/[...]`
Because of the following filter:
`||bestbuy.7tiv.net^`
Found in:
Peter Lowe’s Ad and tracking server list
     
The blocked page wants to redirect to another site. If you choose to proceed, you will navigate directly to:
`https://www.bestbuy.com/site/-/[...]`

**Comment by stephenhawk8054** [comment]
> The blocked page wants to redirect to another site. If you choose to proceed, you will navigate directly to:
> `https://www.bestbuy.com/site/-/[...]`

Yes, that's the purpose of `urlskip`, if there are other filters blocking the link, it will show the destination link to users and users will decide whether they want to proceed or not. Click trackers can be abused to deliver phishing and malware sites and automatically redirecting to the site while there are other filters trying to block it is not the behavior uBO wants to pursue:

- https://unit42.paloaltonetworks.com/rare-phishing-page-delivery-header-refresh
- https://forum.trezor.io/t/emails-from-trezor-appear-as-a-phishing-attack/13865

**Comment by Hebrew-uBO-User** [comment]
@stephenhawk8054 
I understand.
Thank you!
