### ISSUE TITLE
[nsfw] baddiehub.com: ads

### ISSUE THREAD

**Issue by MaxximilianC** [uBlockOrigin/uAssets#26124]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://baddiehub.com/`

### Category

ads

### Description

There is a small NSFW banner ad that pops up on the bottom that is not able to be eliminated with the neither the zapper or picker.

### Other extensions used

Carrot
DeepL
Mobile View Switch
Honey
Ruffle
TWP translate
Zoom for opera

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://baddiehub.com

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 137931
 cosmetic: 49771
 scriptlet: 23086
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 16-1, never
  easylist: 79032-476, 8m Δ
  easyprivacy: 53266-646, 8m Δ
  plowe-0: 3537-0, 1m
  ublock-badware: 11970-1, 8m Δ
  ublock-filters: 40632-377, 8m Δ
  ublock-privacy: 1486-26, 8m Δ
  ublock-quick-fixes: 222-0, 8m Δ
  ublock-unbreak: 2507-0, 8m Δ
  urlhaus-1: 19790-0, 7m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1866 ms
 maxAssetCacheWait: 489 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  adtng.com: 2
  go-srv.com: 1
  pemsrv.com: 1
  tsyndicate.com: 2
 extended:
  ##a[href^="https://a.adtng.com/"]
  ##a[href^="https://t.acam.link/"]
  ##+js(no-setTimeout-if, css_class.scroll)
```
</details>

**Comment by gorhill** [comment]
This works for me:

    ||go-static.info^$from=baddiehub.com
    ||gosrv.cl^$from=baddiehub.com
