### ISSUE TITLE
crunchyscan.fr: detection

### ISSUE THREAD

**Issue by RedSkull-666** [uBlockOrigin/uAssets#26122]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://crunchyscan.fr/`

### Category

detection

### Description

After few time, open `https://crunchyscan.fr/adblock`

### Other extensions used

Ghostery

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 275304
 cosmetic: 270638
 scriptlet: 54026
 html: 2407
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83566-173, 2m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103370-24454, 2m
  adguard-generic: 85846-4318, 1m
  adguard-mobile: 9941-66, 1m
  adguard-spyware-url: 1794-132, 1m
  block-lan: 64-0, 1m
  curben-phishing: 582-1, 1m
  adguard-social: 23167-1590, 1m
  fanboy-thirdparty_social: 68-19, 1m
  fanboy-cookiemonster: 52238-52238, 1m
  fanboy-social: 16816-16816, 1m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40923-450, 1m
  ublock-badware: 11972-1, 1m
  ublock-privacy: 1483-23, 1m
  ublock-unbreak: 2565-6, 1m
  ublock-quick-fixes: 214-11, 1m
  easylist: 79032-2317, 1m
  easyprivacy: 53266-1491, 1m
  urlhaus-1: 20155-0, 1m
  plowe-0: 3537-1434, 1m
  FRA-0: 25725-573, 1m
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1306 ms (selfie)
 maxAssetCacheWait: 249 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  adskeeper.co.uk: 3
  cloudflareinsights.com: 2
  googletagmanager.com: 2
  magsrv.com: 1
  pemsrv.com: 2
 extended:
  ##div[id*="ScriptRoot"]
  ##+js(abort-on-property-read, addMultiEventListener)
  ##+js(abort-current-script, document.write, detect)
  ##+js(abort-current-script, eval, replace)
  ##+js(abort-on-property-read, open)
  ##+js(addEventListener-defuser, DOMContentLoaded, adsBlocked)
  ##+js(nobab)
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, atob, /popundersPerIP[\s\S]*?Date[\s…
  ##+js(abort-current-script, document.oncontextmenu)
  ##+js(abort-current-script, document.write, alert)
  ##+js(abort-current-script, setTimeout, bloqueur)
  ##+js(abort-current-script, Promise, alert)
```
</details>

**Comment by gorhill** [comment]
This works for me:

    crunchyscan.fr##+js(prevent-xhr, url:!/api/)
    crunchyscan.fr##+js(prevent-fetch, url:!/upload/)

But somebody will have to figure out if this breaks something on that site. For example maybe subscribing or logging in is broken.

**Comment by stephenhawk8054** [comment]
I think this works too, and not prone to other XHR

```adb
crunchyscan.fr##+js(aeld, DOMContentLoaded, localStorage)
```

@Yuki2718 For "AdGuard Français"?

**Comment by Yuki2718** [comment]
I can't access the site even with French VPN. Can you create exception rules for platforms without advanced capability?

**Comment by Yuki2718** [comment]
No, can't access either.

**Comment by mapx-** [comment]
`crunchyscan.fr##+js(no-fetch-if, adskeeper)`

or

`@@||jsc.adskeeper.co.uk/c/r/crunchyscan.fr$xhr,domain=crunchyscan.fr`
