### ISSUE TITLE
youtube ads

### ISSUE THREAD

**Issue by cashshac** [uBlockOrigin/uAssets#26138]
### Prerequisites

- [ ] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=Hy8kmNEo1i8`

### Category

ads

### Description

youtube shows a black screen of ads before video

### Other extensions used

vevee transşator idontcareaboutcookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot_20241122_045112](https://github.com/user-attachments/assets/e08ae0d7-28ef-421f-b289-499e7730bc3e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 138823
 cosmetic: 58154
 scriptlet: 24260
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40640-389, 1h.24m Δ
  ublock-badware: 11975-1, 1h.24m Δ
  ublock-privacy: 1501-22, 1h.24m Δ
  ublock-unbreak: 2507-0, 1h.24m Δ
  ublock-quick-fixes: 228-4, 1h.24m Δ
  easylist: 79080-455, 1h.24m Δ
  easyprivacy: 53272-672, 1h.24m Δ
  urlhaus-1: 19195-0, 3m
  plowe-0: 3538-0, 3m
  TUR-0: 11007-20, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 639 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 32
 network:
  youtube.com: 10
  doubleclick.net: 3
  google.com: 7
  googlesyndication.com: 2
  googlevideo.com: 10
 extended:
  ##.ytp-featured-product
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.web_bind_fetch, …
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by stephenhawk8054** [comment]
Don't deliberately ignore this

> This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586) report. _These sites MUST be reported by clicking their **respective links**_.
