### ISSUE TITLE
toyota.it: breakage

### ISSUE THREAD

**Issue by MilosBranko** [uBlockOrigin/uAssets#26134]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Page does not load all the objects when uBO is enabled, but when uBO is disabled the page works correctly.

### A specific URL where the issue occurs.

```yaml
https://www.toyota.it/gamma/prius-plugin
```

### Steps to Reproduce

Load the page with uBO on, the disabe uBO and reload the page

### Expected behavior

loading all the objects in the page

### Actual behavior

When uBO is on the page is loaded but without all its objects

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 139667
 cosmetic: 56800
 scriptlet: 21383
 html: 2145
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40929-135, 1h.18m Δ
  ublock-badware: 11972-1, 1h.18m Δ
  ublock-privacy: 1498-22, 1h.18m Δ
  ublock-unbreak: 2565-1, 1h.18m Δ
  ublock-quick-fixes: 215-10, 1h.18m Δ
  easylist: 79047-206, 1h.18m Δ
  easyprivacy: 53270-69, 1h.18m Δ
  urlhaus-1: 19790-0, 5h.17m
  plowe-0: 3549-1000, 11d.6h.3m
  ITA-0: 8789-42, 6h.17m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 32 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 17167 ms
 maxAssetCacheWait: 2826 ms
 cacheBackend: indexedDB
```
</details>

**Comment by MilosBranko** [comment]
Hi there,

this is the screen shot in which the 3 red circles are spinning all the time without loading anything…

But now it does no more seem to be a problem of uBO, so please:

*	consider the issue not existent and close it for me.

Thank you

 



 

 

 

Da: mapx ***@***.***> 
Inviato: giovedì 21 novembre 2024 18:19
A: uBlockOrigin/uAssets ***@***.***>
Cc: MilosBranko ***@***.***>; Author ***@***.***>
Oggetto: Re: [uBlockOrigin/uAssets] toyota.it: breakage (Issue #26134)

 

provide an example of missing object (screenshot)

**Comment by stephenhawk8054** [comment]
Please reply directly on github. Don't reply via email. Images cannot be sent via email.
