### ISSUE TITLE
hdblog.it

### ISSUE THREAD

**Issue by mclovin74** [uBlockOrigin/uAssets#2613]
URL(s) where the issue occurs

`https://mobile.hdblog.it/2018/06/19/roaming-zero-consapevolezza-europa-2018/`

Describe the issue
adblock detected (not in homepage)

Versions
- Browser/version: firefox 60.0.2
- uBlock Origin version: 1.16.10

Settings
default setting

**Comment by okiehsch** [comment]
I can only reproduce if I enable `ITA: ABP X Files`, which is not part of the default setup.

**Comment by zaphodbeebblebrox** [comment]
You can fix it by adding:
```
hdblog.it#@#[id^="banner"]
hdblog.it#@#.ads_block
```
but this needs to be reported to the maintainers of ABP X Files.
