### ISSUE TITLE
startpage.com: breakage

### ISSUE THREAD

**Issue by BredMan0** [uBlockOrigin/uAssets#26143]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.startpage.com/sp/search`

### Category

breakage

### Description

I am on Firefox Android. 

When I click on an image, the screen becomes white instead of showing the image. I then have to reload the page. Many images don't work, some do, and sometimes even the images that don't work in the beginning work once after I have reloaded the page a couple of times. Those images then stop working again after another reload. 

This only happens when uBlock is enabled. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/user-attachments/assets/0ff3ce2f-8992-42f8-b836-228883c1de11

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox Mobile: 132
filterset (summary):
 network: 138826
 cosmetic: 58474
 scriptlet: 21465
 html: 2148
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 41451-136, now
  ublock-badware: 11971-1, now
  ublock-privacy: 1507-22, now
  ublock-unbreak: 2567-1, now
  ublock-quick-fixes: 221-10, now
  adguard-mobile: 9944-96, now
  easylist: 79080-278, now
  easyprivacy: 53272-78, now
  urlhaus-1: 19195-0, now
  plowe-0: 3538-1070, now
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 324 ms (selfie)
 maxAssetCacheWait: 99 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 extended:
  ##.a-bg
  ##+js(trusted-replace-argument, Array.prototype.find, 0, undefin…
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by stephenhawk8054** [comment]
Caused by `startpage.com##[style]:has(path):has([href*="aff"])` in EL

**Comment by mapx-** [comment]
@uBlock-user  already notified, maybe you want to get back to the Slack channel?

**Comment by mapx-** [comment]
tell me (eventually on private discussions) your email

**Comment by mapx-** [comment]
however your email will be visible in slack - I cannot create an invitation without the email

**Comment by ryanbr** [comment]
No email received here?
