### ISSUE TITLE
mail.aol.com: ads

### ISSUE THREAD

**Issue by 42RoiDesRois42** [uBlockOrigin/uAssets#26148]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mail.aol.com/d/folders/1?reason=invalid_cred`

### Category

ads

### Description

Taboola ads are being presented when uBlock shows - next to it (supposed to be blocked).

### Other extensions used

Toby

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/9eb9a785-5dce-4809-bbc4-493891b76fac)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 137407
 cosmetic: 49791
 scriptlet: 23109
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 79084-476, 16m Δ
  easyprivacy: 53273-639, 16m Δ
  plowe-0: 3530-0, now
  ublock-badware: 11980-1, 16m Δ
  ublock-filters: 40649-379, 16m Δ
  ublock-privacy: 1524-22, 16m Δ
  ublock-quick-fixes: 229-4, 16m Δ
  ublock-unbreak: 2507-0, 16m Δ
  urlhaus-1: 19195-0, 16m
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 476 ms (selfie)
 maxAssetCacheWait: 28 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  aol.com: 1
  scorecardresearch.com: 1
  taboola.com: 5
  yahoo.com: 14
  yimg.com: 1
```
</details>

**Comment by mapx-** [comment]
Does enabling `AdGuard – Ads` list fix your issue ?

**Comment by mapx-** [comment]
report at easylist repository, maybe someone is using / has an aol account
https://github.com/easylist/easylist/issues
