### ISSUE TITLE
tumblr.com: nuisance

### ISSUE THREAD

**Issue by Clovernudl** [uBlockOrigin/uAssets#26150]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tumblr.com/dashboard/following`

### Category

nuisance

### Description

The picker does not work, and does not select anything other than images.

When using the "Zapper" tool, all elements are able to be selected and individually temporarily blocked.

When using the "Picker" tool, nothing but the images themselves are able to be selected, and nothing highlights at all other than images.

### Other extensions used

Noscript
Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 136927
 cosmetic: 49842
 scriptlet: 21396
 html: 2146
listset (total-discarded, last-updated):
 default:
  user-filters: 78-13, never
  ublock-filters: 40943-135, 37m Δ
  ublock-badware: 11977-1, 37m Δ
  ublock-privacy: 1510-22, 37m Δ
  ublock-unbreak: 2566-1, 37m Δ
  easylist: 79087-205, 37m Δ
  easyprivacy: 53273-69, 37m Δ
  plowe-0: 3530-989, now
  urlhaus-1: 18715-0, now
  ublock-quick-fixes: 221-11, 37m Δ
filterset (user): [array of 78 redacted]
trustedset:
 added: [array of 71 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 largeMediaSize: 200
hiddenSettings: [none]
supportStats:
 allReadyAfter: 613 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 82
 no-cosmetic-filtering: true
 no-large-media: true
 no-remote-fonts: true
 network:
  tumblr.com: 32
  doubleclick.net: 7
  google.com: 12
  gstatic.com: 6
  moatads.com: 1
  pubmatic.com: 1
  sentry.io: 5
  wp.com: 5
  youtube.com: 13
```
</details>

**Comment by stephenhawk8054** [comment]
> `no-cosmetic-filtering: true`

You are disabling cosmetic filters. Enable it.
