### ISSUE TITLE
login.mos.ru: breakage

### ISSUE THREAD

**Issue by a2kolbasov** [uBlockOrigin/uAssets#26153]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://login.mos.ru/sps/profile/social`

### Category

breakage

### Description

When uBO is enabled, the linked accounts and linking buttons are not displayed on the linked social network account management page. The script with this functionality is blocked.

<details>
<summary>Error message in browser devtools</summary>

```
Uncaught Error: Script error for: social
http://requirejs.org/docs/errors.html#scripterror
    C https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    onScriptError https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    load https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    load https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    load https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    fetch https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    check https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    enable https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    enable https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    enable https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    u https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    v https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    enable https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    init https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    u https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    setTimeout handler*g.nextTick< https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    u https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    configure https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    requirejs https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    <anonymous> https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
    <anonymous> https://login.mos.ru/sps/assets/ilib/requirejs/require.min.js:1
require.min.js:1:798
```

</details>
<details>
<summary>uBO logger (with "blocked" filter)</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 | /javascripts/social.js | -- | login.mos.ru | 1 | get | script | `https://login.mos.ru/sps/profile/assets/javascripts/social.js` |
| +0 | /.*/$document,permissions=identity-credentials-get=() | -- | login.mos.ru | 1 | get | doc | `https://login.mos.ru/sps/profile/social` |

</details>

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

When uBO enabled:
"Searching..." (endless)
![](https://github.com/user-attachments/assets/bd8b8528-bd72-4595-98e8-748088cae6c4)

When disabled:
(message that I can add (link) other accounts; buttons for that)
![](https://github.com/user-attachments/assets/0357c61a-4282-4c0e-b536-3601509e6c0b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 185886
 cosmetic: 282996
 scriptlet: 51081
 html: 2162
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83634-173, 1h.36m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103502-24462, 1h.36m
  adguard-generic: 85900-4320, 1h.36m
  adguard-mobile: 9944-66, 1h.36m
  adguard-social: 23177-1589, 1h.36m
  fanboy-social: 16930-16930, 1h.36m
 default:
  user-filters: 0-0, never
  ublock-filters: 40943-451, 36m Δ
  ublock-badware: 11977-1, 1h.36m
  ublock-privacy: 1510-23, 14m
  ublock-unbreak: 2566-6, 1h.36m
  ublock-quick-fixes: 221-10, 36m Δ
  easylist: 79097-2321, 14m
  easyprivacy: 53273-1490, 14m
  urlhaus-1: 18715-0, 1h.36m
  plowe-0: 3530-1080, 1h.36m
  RUS-0: 41096-627, 36m Δ
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14879 ms (selfie)
 maxAssetCacheWait: 5093 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  mos.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
`/javascripts/social.js`

probably it's fanboy's social, I cannot access the site
@dimisa-RUAdList could you please take a look ?

**Comment by a2kolbasov** [comment]
It was fixed after the commit. Thank you!
