### ISSUE TITLE
pimylifeup.com: ads

### ISSUE THREAD

**Issue by moefear85** [uBlockOrigin/uAssets#26155]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://pimylifeup.com/ubuntu-exfat/`

### Category

ads

### Description

video plays at top on androi despite me blocking audio/video autoplay in site settings. it is visually annoying & distracting.

### Other extensions used

dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox Mobile: 132
filterset (summary):
 network: 138434
 cosmetic: 58478
 scriptlet: 21469
 html: 2149
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41456-217, 17m Δ
  ublock-badware: 11971-2, 17m Δ
  ublock-privacy: 1515-22, 17m Δ
  ublock-unbreak: 2568-3, 17m Δ
  ublock-quick-fixes: 222-10, 17m Δ
  adguard-mobile: 9944-12, now
  easylist: 79102-278, 17m Δ
  easyprivacy: 53275-78, 17m Δ
  urlhaus-1: 18775-0, now
  plowe-0: 3530-1063, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3159 ms
 maxAssetCacheWait: 902 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 113
 network:
  3lift.com: 4
  adnxs.com: 4
  adsrvr.org: 5
  adthrive.com: 37
  amazon-adsystem.com: 1
  bidswitch.net: 4
  casalemedia.com: 4
  cloudflareinsights.com: 2
  confiant-integrations.net: 1
  consentmanager.net: 3
  criteo.com: 5
  crwdcntrl.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  id5-sync.com: 1
  jwpcdn.com: 1
  jwpltx.com: 5
  kargo.com: 4
  openx.net: 4
  pubmatic.com: 4
  rlcdn.com: 1
  rubiconproject.com: 10
  scorecardresearch.com: 1
  sharethrough.com: 4
  videoplayerhub.com: 1
  yahoo.com: 4
 extended:
  ##.adthrive-ad
  ##.adthrive-content
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  #@#.adthrive
  ##+js(abort-on-property-read, adthrive.config)
  ##+js(prevent-fetch, marmalade)
```
</details>

**Comment by gorhill** [comment]
This works for me:

    ||adthrive.com^

But we have this filter in _Unbreak_:

    @@||ads.adthrive.com/sites/*/ads.min.js$script,from=a-z-animals.com|brewerfanatic.com|fishonfirst.com|northsidebaseball.com|pimylifeup.com|twinsdaily.com

**Comment by stephenhawk8054** [comment]
Yeah, they are ads videos disguised as related videos.

**Comment by stephenhawk8054** [comment]
I think the other sites in the exception filter are also in similar situation. For example: `https://a-z-animals.com/animals/swallow/pictures/`.

I think we can temporarily disable the filters and see what happens.

**Comment by gorhill** [comment]
For example one of these embedded videos was about how to install NodeJS in Raspberry, so I search for this, and found an article about this: <https://pimylifeup.com/raspberry-pinodejs/>. The supposed tutorial video should have been embedded there but it's not, instead there is an unrelated video about "AI Assistant".

Yes, we should definitely block `adthrive.com`, and if something report breakage, we will point out these videos are just spam, we can tell them how to unblock on their site if they really want these.
