### ISSUE TITLE
picrew.me: ads

### ISSUE THREAD

**Issue by starbyte42** [uBlockOrigin/uAssets#26167]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://picrew.me/en/image_maker/1473879/complete?cd=8l7JSNH62e`

### Category

ads

### Description

Ads continue popping up even with Ublock enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/aa56be84-38ff-4d4c-b3e7-6cb5bd8c10ee)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 128
filterset (summary):
 network: 137250
 cosmetic: 49787
 scriptlet: 23112
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 40657-252, 31m Δ
  ublock-badware: 11975-1, 31m Δ
  ublock-privacy: 1523-26, 31m Δ
  ublock-unbreak: 2508-0, 31m Δ
  ublock-quick-fixes: 233-0, 31m Δ
  easylist: 79106-602, 31m Δ
  easyprivacy: 53276-639, 31m Δ
  urlhaus-1: 19000-0, 31m
  plowe-0: 3530-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1613 ms (selfie)
 maxAssetCacheWait: 225 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 no-cosmetic-filtering: true
 network:
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  html-load.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Respect the prerequisites please

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

https://github.com/uBlockOrigin/uAssets/issues/23005
