### ISSUE TITLE
freeltc.online: detection

### ISSUE THREAD

**Issue by c11c11c** [uBlockOrigin/uAssets#26161]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://freeltc.online/`

### Category

detection

### Description

`https://freeltc.online/`  detect uBlock Origin: 1.61.2

### Other extensions used

`https://freeltc.online/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 130
filterset (summary):
 network: 137261
 cosmetic: 49778
 scriptlet: 23115
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40662-133, now
  ublock-badware: 11975-1, now
  ublock-privacy: 1534-23, now
  ublock-unbreak: 2507-1, now
  ublock-quick-fixes: 227-14, now
  easylist: 79107-602, now
  easyprivacy: 53276-748, now
  urlhaus-1: 19000-0, now
  plowe-0: 3530-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9917 ms (selfie)
 maxAssetCacheWait: 1073 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 no-popups: true
 network:
  bmcdn6.com: 3
  coinzillatag.com: 2
  czilladx.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(noeval-if, ads)
```
</details>

**Comment by D4niloMR** [comment]
Go to https://github.com/uBlockOrigin/uAssets/discussions/17361
