### ISSUE TITLE
dizipal820.com: ads

### ISSUE THREAD

**Issue by STORMRIS3** [uBlockOrigin/uAssets#26179]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://dizipal820.com/`

### Category

ads

### Description

Even though ublock is on, the site is still full of ads.

### Other extensions used

tested only using Winscribe. still full of ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 137477
 cosmetic: 49880
 scriptlet: 23129
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 79210-45, now
  easyprivacy: 53280-641, now
  plowe-0: 3530-376, now
  ublock-badware: 12005-20, now
  ublock-filters: 40686-376, now
  ublock-privacy: 1543-24, now
  ublock-quick-fixes: 223-1, now
  ublock-unbreak: 2501-31, now
  urlhaus-1: 19165-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 855 ms (selfie)
 maxAssetCacheWait: 251 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  adform.net: 6
  cdnhipter.xyz: 4
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Enable ` tr: AdGuard Turkish` list and test again.
