### ISSUE TITLE
thecw.com: breakage

### ISSUE THREAD

**Issue by ddhanna** [uBlockOrigin/uAssets#26170]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://thecw.com/series/superman-and-lois/?viewContext=Home+Swimlane`

### Category

breakage

### Description

videos used to play on this site, they no longer do

### Other extensions used

Autoplayerstopper - issue happens even if this one is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 137669
 cosmetic: 49779
 scriptlet: 23122
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 79112-45, now
  easyprivacy: 53278-641, now
  plowe-0: 3530-376, now
  ublock-badware: 11986-20, now
  ublock-filters: 40672-376, now
  ublock-privacy: 1540-24, now
  ublock-quick-fixes: 220-1, now
  ublock-unbreak: 2507-31, now
  urlhaus-1: 19380-0, now
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 586 ms
 maxAssetCacheWait: 95 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  bing.com: 1
  branch.io: 1
  facebook.net: 1
  googleadservices.com: 1
  googletagmanager.com: 2
  newrelic.com: 2
  permutive.app: 1
  scorecardresearch.com: 1
  shakegoldfish.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||googleadservices.com/pagead/conversion_async.js$script,domain=thecw.com
@@||googletagmanager.com/gtm.js$script,domain=thecw.com
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima.js:5,domain=thecw.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by mapx-** [comment]
us ip, these are enough on my end (FF/chrome)

```adb
@@||googletagmanager.com/gtm.js$script,domain=thecw.com
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima.js,domain=thecw.com
```
