### ISSUE TITLE
mako.co.il: detection

### ISSUE THREAD

**Issue by C0ffeeF1ower** [uBlockOrigin/uAssets#26173]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mako.co.il/news-science/2024_q4/Article-8d5f7eceb7b5391027.htm?sCh=31750a2610f26110&pId=173113802`

### Category

detection

### Description

when trying to play videos on this news site, the news site detects that ublock origin is enabled and wont let watch the videos on the site.
I also tested both in chrome and firefox, this issue exists in both browsers with ublock origin.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2024-11-24 at 11 37 45" src="https://github.com/user-attachments/assets/b482f2c4-8f69-46e5-bed7-e58da3369161">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 129
filterset (summary):
 network: 137699
 cosmetic: 49784
 scriptlet: 23125
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 41-4, never
  easylist: 79112-476, 19m Δ
  easyprivacy: 53278-639, 19m Δ
  plowe-0: 3530-0, now
  ublock-badware: 11986-1, 19m Δ
  ublock-filters: 40672-376, 19m Δ
  ublock-privacy: 1540-22, 19m Δ
  ublock-quick-fixes: 223-0, 19m Δ
  ublock-unbreak: 2507-0, 19m Δ
  urlhaus-1: 19380-0, now
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 27 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 620 ms (selfie)
 maxAssetCacheWait: 353 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  mako.co.il: 3
  cooladata.com: 1
  doubleclick.net: 1
  dxmdp.com: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  h-cdn.com: 1
  imasdk.googleapis.com: 1
  outbrain.com: 1
  sekindo.com: 1
  upapi.net: 1
  valuad.cloud: 1
 extended:
  ##.OUTBRAIN
  ##.outbrain-wrap
```
</details>

**Comment by mapx-** [comment]
enable the regiona list `EasyList Hebrew`
