### ISSUE TITLE
codepromo.ouest-france.fr: ads

### ISSUE THREAD

**Issue by gut1414** [uBlockOrigin/uAssets#26187]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://codepromo.ouest-france.fr/code-promo/sncf-connect`

### Category

ads

### Description

Two little vertical banner ads each side of page.

### Other extensions used

Only uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![s](https://github.com/user-attachments/assets/a9f23243-181f-47bd-9875-7f418de10406)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 127
filterset (summary):
 network: 163301
 cosmetic: 158817
 scriptlet: 37234
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-mobile-app-banners: 5556-15, now
  adguard-other-annoyances: 14614-385, now
  adguard-popup-overlays: 28069-2142, now
  adguard-widgets: 2781-19, now
  easylist-annoyances: 4818-56, now
  easylist-chat: 217-0, now
  easylist-newsletters: 8283-26, now
  easylist-notifications: 3459-1202, now
  fanboy-cookiemonster: 52266-237, now
  ublock-annoyances: 5922-34, now
  ublock-cookies-easylist: 1913-0, now
 default:
  user-filters: 2-0, never
  FRA-0: 25729-37, now
  easylist: 79222-585, now
  easyprivacy: 53280-931, now
  plowe-0: 3530-30, now
  ublock-badware: 12022-16, now
  ublock-filters: 40705-752, now
  ublock-privacy: 1548-22, now
  ublock-quick-fixes: 223-7, 48m Δ
  ublock-unbreak: 2499-26, now
  urlhaus-1: 19445-0, 48m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1096 ms (selfie)
 maxAssetCacheWait: 697 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  privacy-center.org: 1
 extended:
  ##+js(set-constant, ultimediaVisiblePlayer.scrollVisiblePlayer, …
```
</details>

**Comment by mapx-** [comment]
@smed79 

```adb
codepromo.ouest-france.fr##t1-ad-side-bars
```

**Comment by gut1414** [comment]
New banners ad (apparently one change per day).

**Comment by gut1414** [comment]
I found this filters:

! 26 nov. 2024 https://codepromo.ouest-france.fr
||cdn-codepromo-img.ouest-france.fr/img/showroomprive-promo-habillage.png?v=638657226184357844$image
codepromo.ouest-france.fr##t1-ad-side-bars.mt-1

But it targed specific showroomprive picture, and new ad appear if picture change.

**Comment by stephenhawk8054** [comment]
The filter in https://github.com/uBlockOrigin/uAssets/issues/26187#issuecomment-2501065402 still works for me.

**Comment by stephenhawk8054** [comment]
@gut1414 Please report to https://github.com/easylist/listefr/issues also.
