### ISSUE TITLE
nytimes.com:‌ breakage

### ISSUE THREAD

**Issue by daveolson53** [uBlockOrigin/uAssets#26188]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://myaccount.nytimes.com/auth/login?response_type=cookie&client_id=vi&redirect_uri=https%3A%2F%2Fwww.nytimes.com%2F2024%2F11%2F24%2Fcrosswords%2Fwordle-review-1255.html%3Flogin%3Demail%26auth%3Dlogin-email%23commentsContainer
```

### Description

When I'm on the comments section of wordle with unblock enabled, then I'm unable to click recommend on android firefox. It sends me to the login page above.  
I login, I am returned to the comments. And it repeats. 

If I disable uorigin, login, renable uorigin and manually go back to comments, the same thing happens. 

If I disable uorigin, go to the base login page https://myaccount.nytimes.com/auth/login
And manually go back to comments, then all is well. 

This started between 2 and 4 days ago, with no other changes that were intentional on my part. 

My android software is all current, as far as the updated is concerned. 

Firefox 132.0.2 , Android 15, November 5, 2024 update

### Other extensions used

Bitwarden, but I installed it yesterday, and the problem occurred prior to that install. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

I can't find anything labeled troubleshooting anywhere
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

Continue here: https://github.com/uBlockOrigin/uAssets/issues/24679

**Comment by daveolson53** [comment]
I verified that the filter suggested in #24679 fixes the issue for me also. No surprise, since it's the same underlying comment system as connections. 

Thanks.
