### ISSUE TITLE
tureng.com: ads

### ISSUE THREAD

**Issue by Raidware** [uBlockOrigin/uAssets#26185]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tureng.com/tr/turkce-ingilizce/strict`

### Category

ads

### Description

Extra space due to advertising residuals

### Other extensions used

localcdn fastforward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20241125_150822_Quetta](https://github.com/user-attachments/assets/c8f39a5f-3955-47ae-a895-6925e0ebb47b)
![Screenshot_20241125_150807_Quetta](https://github.com/user-attachments/assets/2f327550-4c58-4baf-ad1b-65a7860324a6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium Mobile: 124
filterset (summary):
 network: 249293
 cosmetic: 194861
 scriptlet: 40234
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1798-9, now
  adguard-spyware: 117832-30498, now
  block-lan: 64-0, now
  curben-phishing: 584-0, now
  adguard-cookies: 32657-99, now
  ublock-cookies-adguard: 1951-0, now
  fanboy-cookiemonster: 52267-4116, now
  ublock-cookies-easylist: 1951-1951, now
  adguard-popup-overlays: 28062-2140, now
  adguard-mobile-app-banners: 5556-1134, now
  adguard-other-annoyances: 14611-391, now
  adguard-widgets: 2781-47, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41197-782, now
  ublock-badware: 12016-3, now
  ublock-privacy: 1549-144, now
  ublock-unbreak: 2501-3, now
  ublock-quick-fixes: 223-0, now
  adguard-mobile: 9948-127, now
  easylist: 79221-785, now
  easyprivacy: 53280-847, now
  urlhaus-1: 19165-0, now
  plowe-0: 3530-0, now
  TUR-0: 11081-26, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8075 ms
 maxAssetCacheWait: 1403 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  adform.net: 1
  criteo.net: 2
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  pixad.com.tr: 5
  virgul.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please report to https://github.com/AdguardTeam/AdguardFilters/issues for normal ads / placeholders

**Comment by xandaronox** [comment]
Since i havent encountered this leftover in adguard, is it can be added into uBO filters? It only occurs at mobile view.

```adb
tureng.com###tureng-cambly-ad-placeholder
```
`https://tureng.com/en/turkish-english/lock`

<details>

![Image](https://github.com/user-attachments/assets/4af6ed10-ff0b-4d4d-bab7-d57d805c27cd)

</details>

**Comment by xandaronox** [comment]
same thing of above adleftover. I only see this at any chromium based browser.

```adb
tureng.com##.debug-ad
```
