### ISSUE TITLE
[nsfw] simpcity.su: ads

### ISSUE THREAD

**Issue by Guts565** [uBlockOrigin/uAssets#26194]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://simpcity.su/`

### Category

ads

### Description

I've tried to filter the ads by blocking the domain(lwoqroszooq.com) or the script that injected, but no luck

### Other extensions used

Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/35f29652-d7f2-4d1f-9fb8-49504c49dd04)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 137383
 cosmetic: 49919
 scriptlet: 23151
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-2, never
  ublock-filters: 40720-133, now
  ublock-badware: 12116-1, now
  ublock-privacy: 1558-23, now
  ublock-unbreak: 2501-1, now
  ublock-quick-fixes: 217-6, now
  easylist: 79048-605, now
  easyprivacy: 53280-745, now
  urlhaus-1: 19120-0, 16m
  plowe-0: 3532-0, now
filterset (user): [array of 36 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 524 ms
 maxAssetCacheWait: 154 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 196
 network:
  adglare.net: 4
  bankingbloatedcaptive.com: 15
  coosync.com: 16
  divisiondrearilyunfiled.com: 15
  lwoqroszooq.com: 146
 extended:
  ##+js(addEventListener-defuser, , shouldShow)
```
</details>

**Comment by stephenhawk8054** [comment]
Are you signed in to the site?

**Comment by stephenhawk8054** [comment]
At which exact link do you see the issue?
