### ISSUE TITLE
yacht.de: detection

### ISSUE THREAD

**Issue by novatrix01** [uBlockOrigin/uAssets#26191]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.yacht.de/`

### Category

detection

### Description

Popup that offers special deal for adblocker users. Content behind the popup is behind a grey shadow.

### Other extensions used

Nextthink, VideoDownloadHelper, Image Forward, Previous / Next Page, I don't care about cookies, ClearURLs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-26 155550](https://github.com/user-attachments/assets/a0a5067d-5b7f-4e2f-9804-7a6bf5cffb9d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 132
filterset (summary):
 network: 139661
 cosmetic: 55343
 scriptlet: 21427
 html: 2154
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 41007-135, 1m
  ublock-badware: 12110-1, 1m
  ublock-privacy: 1539-22, 1m
  ublock-unbreak: 2559-1, 1m
  ublock-quick-fixes: 222-4, 1m
  easylist: 79026-206, 1m
  easyprivacy: 53280-69, 1m
  urlhaus-1: 19120-0, 1m
  plowe-0: 3532-990, 1m
  DEU-0: 7804-40, 1m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1603 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  upscore.com: 2
 extended:
  ##atf-ad-slot
  ##.ape-ads-container
  ##.dk-ad-ident
  ###ad_sponsored
```
</details>

**Comment by Chathund** [comment]
Popup appears again.
