### ISSUE TITLE
[nsfw] kemono.su: breakage

### ISSUE THREAD

**Issue by SixEyedVixen** [uBlockOrigin/uAssets#26197]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kemono.su/patreon/user/61763369`

### Category

breakage

### Description

Can't favourite artist here

### Other extensions used

ClearUrls
Dark Reader 
Search by Image on Android

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 132
filterset (summary):
 network: 138764
 cosmetic: 58603
 scriptlet: 21504
 html: 2155
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41519-158, 9m Δ
  ublock-badware: 12104-1, 46m
  ublock-privacy: 1540-24, 46m
  ublock-unbreak: 2559-20, 9m Δ
  ublock-quick-fixes: 222-4, 46m
  adguard-mobile: 9955-106, 46m
  easylist: 79026-310, 46m
  easyprivacy: 53280-2, 36m Δ
  urlhaus-1: 19120-0, 46m
  plowe-0: 3532-1064, 46m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1193 ms
 maxAssetCacheWait: 480 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  kemono.su: 7
  divisiondrearilyunfiled.com: 1
  isolatedovercomepasted.com: 1
  mnaspm.com: 1
  ovjagtxasv.com: 3
  shakingtacklingunpeeled.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Turn off all other extensions (except uBO), restart the browser and test again.

**Comment by Yuki2718** [comment]
Fixed by https://github.com/easylist/easylist/commit/185f3f5563643277dca29c4df726eb6aeee2c617
