### ISSUE TITLE
adblock detector - any generic workaround?

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#262]
### URL(s) where the issue occurs
http://watchers.to/1vxmsclvs9li.html
### Describe the issue
This site is pretty good playground. They have three inline scripts to enforce popus/popunders and it is madness.
First of all to keep this sane those filters should be added. Those domain are used to dispatch ads and are not blocked currently.
```
||parserwords.info^$document,popunder,popup
||pop.redirect.adsjudo.com^$document,popunder,popup
```
But this fixes only some issues. Popups are blocked uBlock works nicely. But there is one thing that uBlock doesn't handle currently. 

They have script to detect adblocker and if it is detected following HTML is injected. Long story short it does unconditional replace window location to this link (base64 part). Note the `ADBLOCK_WATCHERS` part they are easy to spot in logger. If adblock is disabled this HTML is not injected and only dozens of popups are opened. I mean really they chain many popups.

```
<a style="width:100%; height:100%; display:block!important; position:fixed; top:0px; left:0px;cursor: pointer;z-index: 2147483647;" onclick="mainWidget_globalTm.kesdfpyzzgwubvqdzjjthaxwynjdam('PGh0bWw+PGhlYWQ+PC9oZWFkPjxib2R5PjxzY3JpcHQ+ZG9jdW1lbnQubG9jYXRpb24uaHJlZj0naHR0cDovL3BvcC5yZWRpcmVjdC5hZHNqdWRvLmNvbS9yZC9yZHAuaHRtbD91PWh0dHAlMjUzQSUyNTJGJTI1MkZwMTg4NzU0LmNsa3NpdGUuY29tJTI1MkZhZFNlcnZlJTI1MkZiYW5uZXJzJTI1M0Z0aWQlMjUzREFEQkxPQ0tfV0FUQ0hFUlMlMjUyNmFjdGlvbiUyNTNEciZjbD04MmI4OTUwNy0zMDhkLTRkOGItOGU5My0wODJhMmY1ODA0MDkmZD13YXRjaGVycy50byZwYm5tPWludGFnX2ludGFuZ28nPC9zY3JpcHQ+PC9ib2R5PjwvaHRtbD4=');mainWidget_globalTm.close_all();"></a>
```

To reproduce clear cookies (or block them).
1. open url 
2. anywhere once - popup will get closed 
2. click again window location will be replaced. 

I don't know if you care enough to try find generic solution for this detector. For this specific site there are few solutions.

First block all malicious scripts
```
watchers.to##script:contains(ppu_main)
watchers.to##script:contains(ActiveXObject)
watchers.to##script:contains(beginMainCheckerAB)
```

**or** just block this `a` node. `watchers.to##[onclick*="mainWidget_globalTm"]` this could actually be made generic filter for other sites that uses the same detector. 

Also they chain all popups from `about:blank` so this is not bad addition too `|about:blank$popup,domain=watchers.to`. 

What is your view on this site? Do you even care? :) I noticed it in one other issue.

### Versions
- Browser/version: Firefox Nightly (latest)
- uBlock Origin version: 1.10.5b9

**Comment by migueldemoura** [comment]
https://github.com/uBlockOrigin/uAssets/issues/263#issuecomment-272615772
