### ISSUE TITLE
heye.kr: breakage

### ISSUE THREAD

**Issue by Forberg21** [uBlockOrigin/uAssets#26203]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.heye.kr/board/index.html?pcno=32&q=new&page=1&id=hawk1&no=21218
```

### Description

Hi. There are several mp4/webp etc. files are in this site. This is one of the example of the site. 

If I turn off the Ublock origin, the videos show clearly. However, if I turn on, images are fine but videos are all become hidden.

Some of the pages are fine, and also some of the pages are randomly show up videos but not regularly. 

Plz check.

### Other extensions used

editthiscookie
enablerightclick
ublacklist
httpseverywhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![turn off](https://github.com/user-attachments/assets/b4a8595a-1d49-43a4-a40d-42c43d84012b)
![turn on](https://github.com/user-attachments/assets/51ce30d5-5473-4288-8297-b3e8b09fcee7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 137601
 cosmetic: 53534
 scriptlet: 23325
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 5254-24, 23m
  easylist: 77895-513, 23m Δ
  easyprivacy: 53277-631, 23m Δ
  plowe-0: 3530-26, 3d.42m
  ublock-badware: 12122-1, 23m Δ
  ublock-filters: 40735-377, 23m Δ
  ublock-privacy: 1563-24, 23m Δ
  ublock-quick-fixes: 221-0, 23m Δ
  ublock-unbreak: 2501-19, 23m Δ
  urlhaus-1: 19120-0, 22h.3m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 976 ms
 maxAssetCacheWait: 144 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||blog.kakaocdn.net/dn/$domain=heye.kr` in "List-KR"

Maybe change to

```adb
||blog.kakaocdn.net/dn/$image,domain=heye.kr
```

?

**Comment by Forberg21** [comment]
https://www.heye.kr/board/index.html?pcno=32&q=new&page=1&id=idol&no=91054

agian happening. Would you guys please check again?

**Comment by mapx-** [comment]
maybe

```adb
heye.kr##.first.banner-wrap
@@||blog.kakaocdn.net/*.gif$image,domain=heye.kr
```

**Comment by stephenhawk8054** [comment]
cc @piquark6046

**Comment by piquark6046** [comment]
Resolved
