### ISSUE TITLE
klsescreener.com: detection

### ISSUE THREAD

**Issue by nolongtail** [uBlockOrigin/uAssets#26201]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.klsescreener.com/`

### Category

detection

### Description

in-page javascript (available in page source) that detect adblock and show dialog box with timer that block the normal usage. It uses cookie `_ad` in the detection code. tried turn off additional filter, custom filter and firefox built-in blocker but issue persist. 

[filter given](https://www.reddit.com/r/uBlockOrigin/comments/1crhv1q/ubo_detected_on_klsescreener/) by contributor before and the extra filter in "ublock filter - Annonyances" only remove the ad detection banner at the top but not the dialog box

### Other extensions used

search by image, firefox multi-account container, tree style tab, auto tab discard, darkreader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-11-27 at 12-06-40 Markets KLSE Screener](https://github.com/user-attachments/assets/767c6cc0-f427-4a63-97da-e6164c02a93a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 132
filterset (summary):
 network: 154059
 cosmetic: 75533
 scriptlet: 25620
 html: 2421
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5865-34, 54m
  CHN-0: 25742-109, 1h.7m
  JPN-1: 15506-81, 1h.7m
 default:
  user-filters: 10-0, never
  ublock-filters: 41016-135, 1h.12m
  ublock-badware: 12118-1, 12m Δ
  ublock-privacy: 1534-22, 12m Δ
  ublock-unbreak: 2559-1, 12m Δ
  ublock-quick-fixes: 224-4, 1h.12m
  easylist: 79048-207, 12m Δ
  easyprivacy: 53280-69, 12m Δ
  urlhaus-1: 18995-0, 1h.12m
  plowe-0: 3537-991, 1h.12m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3019 ms
 maxAssetCacheWait: 53 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 77
 no-popups: true
 no-scripting: true
 network:
  klsescreener.com: 28
  ajax.googleapis.com: 2
  cloudflare.com: 20
  googlesyndication.com: 3
  googletagmanager.com: 6
  gstatic.com: 2
  jsdelivr.net: 14
  zurb.github.io: 2
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ###aLegMYzGHfnR
  ##+js(abort-current-script, document.getElementById, adblock)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters:

```adb
klsescreener.com##+js(rmnt, script, adblock)
klsescreener.com##+js(set-cookie, _ad, 0)
```

**Comment by nolongtail** [comment]
Tested for 1st line alone, 2nd line alone, and both at the time:
- 1st line alone (`remove-node-text`) is working fine for blocking the dialog box.
- 2nd line alone (`set-cookie`) failed to block it.
- applied both line able to block the dialog box.

From the test is seems 1st filter is enough to block it. However the dom filter given in reddit (`www.klsescreener.com###aLegMYzGHfnR`) still needed to block the banner.
