### ISSUE TITLE
vidburner.com: detection

### ISSUE THREAD

**Issue by alanliongar** [uBlockOrigin/uAssets#26218]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://vidburner.com/#url=https://ifunny.co/video/how-is-bro-not-in-the-league-UybDYZLxB?s=cl
```

### Description

This website can detect the ublock origin, can you help please?

### Other extensions used

No other extensions, ive tested it isolated on another chrome settings profile.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublockoriginvidburner27 11 2024](https://github.com/user-attachments/assets/b5d31864-a4a2-4958-8b1f-01a75576683b)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
Looks like your ad blocker is on.
```
</details>

**Comment by D4niloMR** [comment]
This is fixed in the annoyance lists https://github.com/uBlockOrigin/uAssets/blob/e59ee2fe41287ca0473f43b6fbad8e785a6cf570/filters/annoyances-others.txt#L7258-L7260

But since it's also used with hard adblock wall we should move to uBO filters.
