### ISSUE TITLE
slashdot.org: privacy

### ISSUE THREAD

**Issue by do-not-share-my-personal-information** [uBlockOrigin/uAssets#26217]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://slashdot.org/`

### Category

privacy

### Description

* Slashdot now tries to force connections to `html-load.com`
* The script that calls it can be safely removed with `slashdot.org##^script:has-text(html-load.com)`

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 251606
 cosmetic: 186957
 scriptlet: 50504
 html: 2426
listset (total-discarded, last-updated):
 added:
  adguard-generic: 86037-4237, now
  adguard-spyware-url: 1804-132, now
  adguard-spyware: 117843-1553, now
  block-lan: 64-0, now
  adguard-cookies: 32646-64, now
  ublock-cookies-adguard: 1919-20, now
  adguard-social: 23192-50, now
  adguard-popup-overlays: 28093-2099, now
  adguard-mobile-app-banners: 5565-33, now
  adguard-other-annoyances: 14622-434, now
  adguard-widgets: 2784-19, now
  ublock-annoyances: 5872-203, now
 default:
  user-filters: 18-0, never
  ublock-filters: 41051-135, now
  ublock-badware: 12179-1, now
  ublock-privacy: 1560-22, now
  ublock-unbreak: 2561-1, now
  ublock-quick-fixes: 224-4, now
  easylist: 78012-2176, now
  easyprivacy: 53277-29841, now
  urlhaus-1: 21085-0, now
  plowe-0: 3537-1089, now
filterset (user): [array of 16 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 311 ms (selfie)
 maxAssetCacheWait: 187 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  slashdot.org: 4
  6sc.co: 1
  ad-delivery.net: 2
  btloader.com: 1
  criteo.net: 1
  d3tglifpd8whs6.cloudfront.net: 2
  fsdn.com: 2
  googlesyndication.com: 1
  ml314.com: 1
  slashdotmedia.com: 1
 extended:
  ###announcement
  ###main-nav-badge-link
  ###slashdot_deals
  ##.deals-wrapper
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.adwrap
  ###slashboxes > .deals-rail
  ##.scroll-fixable.rail-right > .deals-rail
  ##.railad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.icon-facebook-squared
  #@#.nav-social:not(body):not(html)
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/635a9011be61abbbc9c3feb67b0c5e2ee789a583
