### ISSUE TITLE
Using uBlock sometimes redirect me to some shady website

### ISSUE THREAD

**Issue by HateFireFox96** [uBlockOrigin/uAssets#26225]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.youtube.com/
https://www.zillow.com/slaton-tx/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22isMapVisible%22%3Atrue%2C%22mapBounds%22%3A%7B%22west%22%3A-101.71154342114258%2C%22east%22%3A-101.57661757885742%2C%22south%22%3A33.4107113922501%2C%22north%22%3A33.49936473825817%7D%2C%22usersSearchTerm%22%3A%22Slaton%20TX%22%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A16144%2C%22regionType%22%3A6%7D%5D%2C%22filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22pricea%22%7D%2C%22land%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A13%7D
```

### Description

Ever since reusing uBlock I sometimes get redirects to some website called, https://buybutwhere.com when I disabled uBlock when I then try clicking sometime i get random pop ups, so i then have to re-enable uBlock. Is ypur crap program trying to i fect my pc with viruses with redirecting me to this https://buybutwhere.com website? Your extension even does this to me when trying to go to my OWN EMAIL WHICH IS VERY SECURED BY THE WAY. Which then makes me think your extension is trying to steal my info for my email. I rate your extension a negative 10 stars, mainly because it tries to redirect me when trying to access my email ( i use proton, a very encrypted and secure email provider). 

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 138187
 cosmetic: 49928
 scriptlet: 23188
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40882-133, 2m
  ublock-badware: 12177-1, 2m
  ublock-privacy: 1574-23, 2m
  ublock-unbreak: 2525-1, 2m
  ublock-quick-fixes: 220-6, 2m
  easylist: 78032-607, 2m
  easyprivacy: 53276-741, 2m
  urlhaus-1: 20735-0, 2m
  plowe-0: 3537-0, 2m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1126 ms
 maxAssetCacheWait: 275 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Your computer is infected. Use other programs to scan your machine. uBO does not collect any information and does not redirect to other websites automatically.

**Comment by JobcenterTycoon** [comment]
Also be sure you using the original uBlock Origin. There are plenty of malicious "ad blocker" around the web which using uBlock Origin as a codebase but adds adware.

Original (also with the real addon store links): https://github.com/gorhill/uBlock

Also be sure your antivirus supports adware cleaning or try a specialised adware cleaning tool like [Malwarebytes AdwCleaner](https://www.malwarebytes.com/de/adwcleaner). Regular antivirus software may not detect adware.
