### ISSUE TITLE
deezer.com: detection

### ISSUE THREAD

**Issue by Muumuufelin** [uBlockOrigin/uAssets#26224]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.deezer.com/`

### Category

detection

### Description

Hello!

I get a message saying "Ad-blocker detected. Please disable your ad-blocker to use Deezer" whenever I try to play a song on Deezer. Any idea how to fix this?

Thanks! 

### Other extensions used

none!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d'écran 2024-11-28 231737](https://github.com/user-attachments/assets/20618b07-567e-473d-a0bd-3257beafee3d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 164288
 cosmetic: 156528
 scriptlet: 47365
 html: 2426
listset (total-discarded, last-updated):
 added:
  adguard-generic: 86041-4238, 14m
  adguard-mobile: 9960-60, 14m
  adguard-popup-overlays: 28094-1399, 14m
  adguard-mobile-app-banners: 5567-32, 14m
  adguard-other-annoyances: 14624-319, 14m
  adguard-widgets: 2785-16, 14m
  easylist-annoyances: 4817-340, 14m
  easylist-chat: 217-17, 14m
  easylist-newsletters: 8286-592, 15m
  easylist-notifications: 3460-1548, 14m
  ublock-annoyances: 5886-217, 15m
 default:
  user-filters: 0-0, never
  ublock-filters: 41167-135, 21m
  ublock-badware: 12179-1, 21m
  ublock-privacy: 1560-22, 21m
  ublock-unbreak: 2583-1, 3m Δ
  ublock-quick-fixes: 225-4, 3m Δ
  easylist: 78025-2246, 21m
  easyprivacy: 53277-168, 3m Δ
  urlhaus-1: 21085-0, 21m
  plowe-0: 3537-1080, 21m
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 291 ms (selfie)
 maxAssetCacheWait: 116 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 no-cosmetic-filtering: true
 no-popups: true
 network:
  doubleclick.net: 1
  dzcdn.net: 1
  googletagmanager.com: 1
  segment.com: 1
  sentry.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
RESPECT the prerequisites PLEASE

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
