### ISSUE TITLE
leboncoin.fr: breakage

### ISSUE THREAD

**Issue by draxx31** [uBlockOrigin/uAssets#26220]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.leboncoin.fr/messages`

### Category

breakage

### Description

Hello,

From yesterday, I am not able to reach the message box into Le Bon Coin website. The website shows me a strange message : Messaging is not accessible to professionals in your sector

I tried to disconnect and to reconnect but the connexion workflow has issues too.

If I disable ublock, the website works. Else I need to retrieve several times and waiting time between new try to reach the message box.

### Other extensions used

Allociné Search
ClearURLs
LanguageTool
Facebook container
Bitwarden
IMDb Search
Save WebP as PNG or JPEG
Simple Translate
Singlefile
Youtube NonStop

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran 2024-11-28 à 18 55 36](https://github.com/user-attachments/assets/6bdab4f5-1021-4da5-8b3f-7ac4db4c6a7c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 156803
 cosmetic: 56555
 scriptlet: 21653
 html: 2157
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41058-135, 1h.4m Δ
  ublock-badware: 12179-1, 1h.4m Δ
  ublock-privacy: 1560-22, 1h.4m Δ
  ublock-unbreak: 2562-1, 1h.4m Δ
  ublock-quick-fixes: 224-4, 1h.4m Δ
  easylist: 78012-209, 1h.4m Δ
  easyprivacy: 53277-69, 1h.4m Δ
  urlhaus-1: 21085-0, now
  plowe-0: 3537-990, now
  FRA-0: 25731-399, now
filterset (user): [empty]
trustedset:
 added: [array of 40 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1063 ms (selfie)
 maxAssetCacheWait: 222 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  leboncoin.fr: 1
  ati-host.net: 1
  aticdn.net: 1
  criteo.net: 2
  doubleclick.net: 1
  googletagmanager.com: 1
  hubvisor.io: 1
  pinimg.com: 1
  realytics.io: 3
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

or 

if you agree to share your account credentials (in order to permit us to investigate the issue) I'll provide an email address where you can send the info
