### ISSUE TITLE
bsky.app: breakage

### ISSUE THREAD

**Issue by neoapps-dev** [uBlockOrigin/uAssets#26221]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bsky.app/`

### Category

breakage

### Description

uBlock Origin blocks `bsky.app`'s servers. it can't load posts, users, or anything

Browser: Zen
Browser Family: Firefox-based
Browser Version: Firefox 132
OS: Windows 11 Pro

uBO blocked access to some routes of `bsky.app`,`sentry.io`,`statsigapi.net` as i checked the Network tab in Dev Tools

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/47e61689-bc1c-4cc7-b792-c93aa38d3487)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 132
filterset (summary):
 network: 138378
 cosmetic: 49931
 scriptlet: 21459
 html: 2157
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 41058-135, 13m Δ
  ublock-badware: 12179-1, 13m Δ
  ublock-privacy: 1560-22, 13m Δ
  ublock-unbreak: 2562-1, 13m Δ
  ublock-quick-fixes: 224-4, 13m Δ
  easylist: 78012-209, 13m Δ
  easyprivacy: 53277-69, 13m Δ
  urlhaus-1: 21085-0, now
  plowe-0: 3537-990, now
filterset (user): [array of 5 redacted]
trustedset:
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 476 ms (selfie)
 maxAssetCacheWait: 140 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  bsky.app: 17
  sentry.io: 1
  statsigapi.net: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in the old thread.
