### ISSUE TITLE
dfbplay.tv: detection

### ISSUE THREAD

**Issue by goooglefc** [uBlockOrigin/uAssets#26234]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.dfbplay.tv/vod/vod.7555-fc-ingolstadt-04-vfl-osnabruck-highlights
https://www.dfbplay.tv/vod/vod.6673-hertha-bsc-1-fc-heidenheim-highlights
https://www.dfbplay.tv/vod/vod.6672-sv-darmstadt-98-sg-dynamo-dresden-highlights
```

### Description

First of all you will need to create a free account using this link https://www.dfbplay.tv/register and login
Then try playing any of the videos or live streams on the home page, hopefully you'll see the disable adblock message.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ScreenShot Tool -20241129234507](https://github.com/user-attachments/assets/87084589-2b67-4f99-abf0-7335b8db3e71)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 138566
 cosmetic: 49949
 scriptlet: 21465
 html: 2159
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 41177-138, 1h.28m Δ
  ublock-badware: 12209-1, 1h.28m Δ
  ublock-privacy: 1565-22, 1h.28m Δ
  ublock-unbreak: 2583-1, 1h.28m Δ
  ublock-quick-fixes: 225-0, 1h.28m Δ
  easylist: 78048-209, 1h.28m Δ
  easyprivacy: 53278-69, 1h.28m Δ
  urlhaus-1: 21085-0, 19h.9m
  plowe-0: 3537-990, 1d.22h.49m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1180 ms (selfie)
 maxAssetCacheWait: 813 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  usercentrics.eu: 1
```
</details>

**Comment by D4niloMR** [comment]
@goooglefc test:

```adb
@@||dfbplay.tv^$ghide
dfbplay.tv##+js(no-fetch-if, googlesyndication)
||api.app.dfbplay.tv/V1/Adverts/GetVast$xhr,1p

```
Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.


---

The play button is also broken by `||usercentrics.eu^$3p` in AdGuard/EasyList cookie lists.

@Alex-302 @ryanbr

**Comment by goooglefc** [comment]
> ```
> @@||dfbplay.tv^$ghide
> dfbplay.tv##+js(no-fetch-if, googlesyndication)
> ||api.app.dfbplay.tv/V1/Adverts/GetVast$xhr,1p
> ```

That does the job. Cheers!

**Comment by Alex-302** [comment]
@blazDT Please take a look. Can't check with VPNs.

**Comment by BlazDT** [comment]
@Alex-302 The same with real German IP. But available with Austrian VPN.
Generichide was not required in my case.
