### ISSUE TITLE
[nsfw] planetminecraft.com: privacy

### ISSUE THREAD

**Issue by YouTubeMC-hash** [uBlockOrigin/uAssets#26235]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.planetminecraft.com/texture-pack/vanillapvp-5431434/`

### Category

privacy

### Description

I COULDNT EVEN GET IN

### Other extensions used

nope

### Screenshot(s)

[](url) 
![image](https://github.com/user-attachments/assets/584a9d94-9fa5-47ac-ae11-d1ab2ae1f131)

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 138466
 cosmetic: 49999
 scriptlet: 21465
 html: 2159
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41178-134, now
  ublock-badware: 12209-1, now
  ublock-privacy: 1565-22, now
  ublock-unbreak: 2583-1, now
  ublock-quick-fixes: 225-4, now
  easylist: 78186-208, now
  easyprivacy: 53279-69, now
  urlhaus-1: 20900-0, now
  plowe-0: 3536-990, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 716 ms (selfie)
 maxAssetCacheWait: 252 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Why is it uBO's issue?
