### ISSUE TITLE
elcucodigital.com: ads

### ISSUE THREAD

**Issue by Alvarodroid** [uBlockOrigin/uAssets#26241]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.elcucodigital.com/`

### Category

ads

### Description

not ads blocked

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 138456
 cosmetic: 49991
 scriptlet: 21477
 html: 2159
listset (total-discarded, last-updated):
 removed:
  spa-0: null
  spa-1: null
 default:
  user-filters: 16-3, never
  ublock-filters: 41182-134, 7m Δ
  ublock-badware: 12229-1, 7m Δ
  ublock-privacy: 1572-22, 7m Δ
  ublock-unbreak: 2583-1, 7m Δ
  ublock-quick-fixes: 226-4, 7m Δ
  easylist: 78296-207, 7m Δ
  easyprivacy: 53281-69, 7m Δ
  urlhaus-1: 20735-0, 2m
  plowe-0: 3537-990, 2m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms
 maxAssetCacheWait: 335 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  googlesyndication.com: 5
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
```
</details>

**Comment by mapx-** [comment]
- Enable the spanish lists
- if you still get ads report here: https://github.com/AdguardTeam/AdguardFilters/issues
