### ISSUE TITLE
apkmoddone.com: detection

### ISSUE THREAD

**Issue by Rachitidk** [uBlockOrigin/uAssets#26261]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.apkmoddone.com/2023/06/facebook-mod-menu.html`

### Category

detection

### Description

Detection while trying to download

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 132
filterset (summary):
 network: 503397
 cosmetic: 221765
 scriptlet: 39148
 html: 2484
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl: 140539-0, 1h.14m
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1046-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 459-2, 1h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Anti-Malware List.txt: 91353-207, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2692-2, 1h.14m
  https://raw.githubusercontent.com/fmhy/FMHYFilterlist/main/filterlist.txt: 456-34, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt: 87222-40343, now
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4698-42, now
  adguard-spyware-url: 1805-250, now
  block-lan: 64-0, now
  curben-phishing: 493-20, now
  fanboy-cookiemonster: 52231-207, now
  [15 lists not shown]: [too many]
 default:
  user-filters: 8-0, never
  ublock-filters: 41672-373, 6m Δ
  ublock-badware: 12223-1471, 6m Δ
  ublock-privacy: 1577-106, now
  ublock-unbreak: 2586-3, 6m Δ
  ublock-quick-fixes: 232-13, 6m Δ
  adguard-mobile: 9960-774, now
  easylist: 78328-27642, 6m Δ
  easyprivacy: 53280-9533, 6m Δ
  urlhaus-1: 20865-311, now
  plowe-0: 3537-3006, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 4 redacted]
 removed:
  no-large-media: behind-the-scene false
userSettings:
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3430 ms
 maxAssetCacheWait: 2102 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  blogger.com: 4
  google.com: 5
 extended:
  ###sn-AnchorAd
  ###sn-Notif
  ###ckWrp
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ###adTop
  ##+js(trusted-replace-node-text, script, ;return;, , condition, …
  ##+js(trusted-replace-node-text, script, /return Array[^;]+/, re…
  ##+js(no-setTimeout-if, 1e3*)
  ##+js(prevent-window-open, /wheceelt\.net|shopee\./, 10, obj)
  ##.grecaptcha-badge
  ##.grecaptcha-badge[data-style]
  ##+js(trusted-set-cookie, SOCS, CAISNQgQEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by D4niloMR** [comment]
#24313
