### ISSUE TITLE
spiele.connect.de: breakage

### ISSUE THREAD

**Issue by yunosh** [uBlockOrigin/uAssets#26265]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://spiele.connect.de/adventskalender/`

### Category

breakage

### Description

raffle area doesn't load. same on https://spiele.spiegel.de/adventskalender/.

### Other extensions used

Sponsor Block for YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140577
 cosmetic: 54782
 scriptlet: 21449
 html: 2195
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41163-134, now
  ublock-badware: 12229-1, now
  ublock-privacy: 1576-22, now
  ublock-unbreak: 2583-1, now
  ublock-quick-fixes: 232-4, now
  easylist: 77696-206, now
  easyprivacy: 53282-69, now
  urlhaus-1: 20510-0, now
  plowe-0: 3537-990, now
  DEU-0: 7809-39, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5507 ms (selfie)
 maxAssetCacheWait: 72 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  consentmanager.net: 3
  das-onlinespiel.de: 2
  ebxcdn.com: 2
  googletagmanager.com: 2
  netpoint-media.de: 1
  upscore.com: 1
  wlct-one.de: 1
 extended:
  ##.adslot
  ##.ad--p1
  ##.adcontainer_footer
  ##.ad--p7
  ##.ad--p2
  ##.ad--p4
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||partners2.das-onlinespiel.de^$3p`.

cc @JobcenterTycoon Sorry, do you know which this filter is for? I'll use `@@||partners2.das-onlinespiel.de/client.js^$script,3p,domain=spiele.connect.de|spiele.spiegel.de` as temporary solution.

**Comment by JobcenterTycoon** [comment]
As far i know because it tried to load ads on `https://spiele.bild.de/kreuzwortraetsel/` . EL germany contains

```
||partners2.das-onlinespiel.de/client.js?pid=*&_=2.12.3|$script,domain=games.focus.de|spiele.bild.de|spiele.stern.de
||partners2.das-onlinespiel.de/client.js?pid=pg_bildnew_kwr&zone=crosswords$domain=spiele.bild.de
```
