### ISSUE TITLE
flashscore.dk: ads

### ISSUE THREAD

**Issue by TotoYY07** [uBlockOrigin/uAssets#26263]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.flashscore.dk/kamp/WEwjCePQ/`

### Category

ads

### Description

Top header not fully blocked.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
version: uBOL 2024.11.25.1376
mode: complete / complete
rulesets:
 default
 adguard-spyware-url
 annoyances-cookies
 nor-0
```

**Comment by DandelionSprout** [comment]
Sure thing.

I see AdGuard Base Filter has `flashscore.*###detail > .detailLeaderboard` (which works as intended on uBO Standard), so I'll borrow their entry from them for shared convenience.

**Comment by TotoYY07** [comment]
Hi @stephenhawk8054 and @DandelionSprout,

I'm seeing ads on flashscore.dk again. Could you please look into this issue once more?

**Comment by mapx-** [comment]
```adb
flashscore.dk##[style*="banner"]
```

**Comment by DandelionSprout** [comment]
These ones seem to fix the newest ads:
```
||content.livesportmedia.eu/api/v*/banners^$3p
flashscore.*##div.banner
flashscore.*###box-over-content-revive
```
But I need to recover from having got home from a hiking trip first.

**Comment by TotoYY07** [comment]
This is what I see with the same settings

![Image](https://github.com/user-attachments/assets/5ce07c6a-c463-436a-8197-cb1efbe647a0)

**Comment by mapx-** [comment]
@TotoYY07 use my filter above, however it will be fixed directly in easylist

**Comment by mapx-** [comment]
fixed for all countries by EL
https://github.com/easylist/easylist/commit/2de7cba82acaf86e646f8f623acc77da06fe71e5
