### ISSUE TITLE
bk.com: breakage

### ISSUE THREAD

**Issue by vehosah** [uBlockOrigin/uAssets#26270]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bk.com/`

### Category

breakage

### Description

Something went wrong with the page, please reload the page

### Other extensions used

I don't have any more extensions 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 132
filterset (summary):
 network: 209100
 cosmetic: 300921
 scriptlet: 37838
 html: 2525
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83792-173, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1066-3, never
  https://raw.githubusercontent.com/acnapyx/paywall-remover/master/paywall-remover-list.txt: 40-1, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 0-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 0-0, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 2079-20, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103449-24502, now
  adguard-social: 23204-1579, now
  fanboy-thirdparty_social: 68-19, now
  fanboy-cookiemonster: 52235-52235, now
  fanboy-social: 16751-16751, now
  [26 lists not shown]: [too many]
 default:
  ublock-filters: 41680-470, 31m Δ
  ublock-badware: 12346-1, 31m Δ
  ublock-privacy: 1579-23, 31m Δ
  ublock-unbreak: 2586-6, 31m Δ
  ublock-quick-fixes: 232-0, now
  adguard-mobile: 9963-105, now
  easylist: 77691-374, 31m Δ
  easyprivacy: 53285-1417, 31m Δ
  urlhaus-1: 20025-0, 1h.31m
  plowe-0: 3540-1066, now
filterset (user): [array of 474 redacted]
trustedset:
 added: [array of 28 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6231 ms
 maxAssetCacheWait: 3384 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
> [26 lists not shown]: [too many]

reset uBO to defaults, test again

**Comment by vehosah** [comment]
> > [26 lists not shown]: [too many]
> 
> reset uBO to defaults, test again

It didn't work

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by stephenhawk8054** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/1h3u2b9/visiting_bkcom_burger_king_with_ublock_origin_on/m0229rf/
