### ISSUE TITLE
bing.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#26279]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bing.com/search?pglt=385&q=install+outdoor+camera+without+drilling&gs_lcrp=EgRlZGdlKgYIABBFGDkyBggAEEUYOTIGCAEQABhAMgYIAhAAGEAyBggDEAAYQDIGCAQQABhAMgYIBRAAGEAyBggGEAAYQDIGCAcQABhAMgYICBAAGEDSAQg0MjYxajBqMagCALACAA&FORM=ANSPA1&adppc=EDGEXST&PC=LCTS`

### Category

ads

### Description

Sponsored results show up when google sponsored results don't show up

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/afddb432-2506-482d-b641-1a11d53b2bbe">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 253893
 cosmetic: 225352
 scriptlet: 57475
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 86147-7436, now
  adguard-mobile: 9963-111, now
  adguard-spyware-url: 1804-130, now
  adguard-spyware: 116425-30473, now
  block-lan: 64-0, now
  curben-phishing: 736-0, now
  adguard-cookies: 32683-91, now
  ublock-cookies-adguard: 1935-0, now
  fanboy-cookiemonster: 52236-4109, now
  ublock-cookies-easylist: 1935-1935, now
  adguard-popup-overlays: 28109-2247, now
  adguard-mobile-app-banners: 5574-1127, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40824-132, now
  ublock-badware: 12350-4, now
  ublock-privacy: 1593-23, now
  ublock-unbreak: 2525-3, now
  ublock-quick-fixes: 226-8, now
  easylist: 77757-870, now
  easyprivacy: 53290-936, now
  urlhaus-1: 9500-0, now
  plowe-0: 3540-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 623 ms (selfie)
 maxAssetCacheWait: 129 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  bing.com: 26
 extended:
  ###b_pole
  ##.b_bnp_bopc
  ##.b_ad:style(position: absolute !important; top: -9999px !impor…
  ##.b_ad:style(display: block !important; position: absolute !imp…
  #@#.b_ad
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
  ##+js(trusted-set-cookie, BCP, AD=0&AL=0&SM=0)
  ##+js(json-prune, relatedAds)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25344
