### ISSUE TITLE
mako.co.il: detection

### ISSUE THREAD

**Issue by yotavm** [uBlockOrigin/uAssets#26277]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.mako.co.il/mako-vod-keshet/save_the_date-s1`

### Category

detection

### Description

this is israel network for watching news and tv shows

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 137948
 cosmetic: 49306
 scriptlet: 23203
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40824-367, now
  ublock-badware: 12350-1, now
  ublock-privacy: 1592-22, now
  ublock-unbreak: 2525-0, now
  ublock-quick-fixes: 227-0, now
  easylist: 77737-480, now
  easyprivacy: 53289-639, now
  urlhaus-1: 20025-0, now
  plowe-0: 3540-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1100 ms
 maxAssetCacheWait: 18 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  clarity.ms: 1
  criteo.net: 1
  doubleclick.net: 3
  dxmdp.com: 1
  google.co.il: 1
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  permutive.com: 3
  valuad.cloud: 1
 extended:
  ##.adunitContainer
  ##.adBox
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

**Comment by stephenhawk8054** [comment]
Also enable "EasyList Hebrew" list in uBO dashboard.
