### ISSUE TITLE
transinfo.pl: detection

### ISSUE THREAD

**Issue by maxw9172** [uBlockOrigin/uAssets#26276]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://transinfo.pl/
```

### Description

The Transinfo website detects uBlock Origin. It says "You can't see this article because you block ads using an adblocker. This is what you can do: Turn off the adblocker. Try a TransInfo.pl subscription (from as little as 15zł per year), which will limit your advertising and you won't see this message again." I disabled all extra filter lists which I added manually and I still get the pop-up.

### Other extensions used

StartPage Privacy Extension, I don't care about cookies, User-Agent Switcher and Manager (using default user agent), Don't track me Google, other extensions which are unrelated to privacy issues. I disabled all extensions except for uBlock Origin but I still get the adblocker pop-up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_tlhyXRKpdZ](https://github.com/user-attachments/assets/86c6d1af-a1ef-4794-9cb0-447f4aafb048)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 139520
 cosmetic: 57583
 scriptlet: 21644
 html: 2208
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock: 135-0, 5h.38m
 default:
  user-filters: 45-7, never
  ublock-filters: 41120-171, 38m Δ
  ublock-badware: 12352-1, 38m Δ
  ublock-privacy: 1578-23, 38m Δ
  ublock-unbreak: 2583-1, 38m Δ
  ublock-quick-fixes: 231-6, 38m Δ
  easylist: 77737-212, 38m Δ
  easyprivacy: 53289-90, 38m Δ
  urlhaus-1: 20025-0, 5h.38m
  plowe-0: 3538-1011, 11d.4h.18m
  POL-0: 8766-46, 1d.21h.36m
  POL-2: 1283-12, now
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1379 ms (selfie)
 maxAssetCacheWait: 125 ms
 cacheBackend: indexedDB

```
</details>

**Comment by krystian3w** [comment]
@majkiit / @olegwukr

**Comment by maxw9172** [comment]
> Need to add `~transinfo.pl` to `/plugins/advanced-ads/*$from=~wordpress.org` in EasyList.
> 
> Then maybe the following in POL list:
> 
> ```
> transinfo.pl##[data-nowet-trackid]:has(.adv-link)
> ```

How can I do this?

**Comment by stephenhawk8054** [comment]
Update your EasyList list.

**Comment by maxw9172** [comment]
> Update your EasyList list.

I did that, but it didn't work. I still get the adblocker pop-up.

**Comment by gorhill** [comment]
The [fix](https://github.com/easylist/easylist/commit/3454c15f863067f748d738aa14dea36390bcb697) was applied to `/advanced-ads-$domain=~wordpress.org`, not `/plugins/advanced-ads/*$domain=~wordpress.org`. It needs to be applied to the latter.
