### ISSUE TITLE
igetintopc.com: badware

### ISSUE THREAD

**Issue by Abhijith4124** [uBlockOrigin/uAssets#26280]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://igetintopc.com/`

### Category

badware

### Description

`https://igetintopc.com/` is a phishing version of `https://getintopc.com/` spreading malware

### Other extensions used

None

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 127448
 cosmetic: 49312
 scriptlet: 23204
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40822-132, now
  ublock-badware: 12357-1, now
  ublock-privacy: 1596-23, now
  ublock-unbreak: 2525-1, now
  ublock-quick-fixes: 227-8, now
  easylist: 77759-605, now
  easyprivacy: 53290-739, now
  urlhaus-1: 9500-0, now
  plowe-0: 3540-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 556 ms (selfie)
 maxAssetCacheWait: 58 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  igetintopc.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  juglansovening.com: 1
  wp.com: 1
```
</details>

**Comment by mapx-** [comment]
![image](https://github.com/user-attachments/assets/eaa1ac95-df0b-45e5-a214-492673539263)
