### ISSUE TITLE
igromania.ru: breakage

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#26286]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [X] uBO Lite is the only extension.
- [X] using a new, unmodified browser profile.

### Description

news feed not loading

### A specific URL where the issue occurs.

```text
https://www.igromania.ru/
```

### Steps to Reproduce
0.full  ublock origin lite mode enabled
1.go to site igromania.ru

### Expected behavior

On the left, a block with all the site news is displayed
![image](https://github.com/user-attachments/assets/dfe3fc6d-2903-4212-ab35-60d09f02588e)

### Actual behavior

![image](https://github.com/user-attachments/assets/ab1e218c-7ba8-4cdd-8e2b-085d0b2fe6a5)
when the page is reloaded it works correctly, but not the first time you visit it

### uBO Lite version

2024.12.2.22

**filters
Ads, trackers, miners, and more
EasyList/uBO – Cookie Notices
RU AdList
RU AdList: Counters**

### Browser name and version

microsoft edge 131.0.2903.70 

### Operating system and version

windows 11 24h2

**Comment by electrifying** [comment]
> What is your default filtering mode, and what is the filtering mode for that site? I cannot reproduce using Chromium.

the problem is floating, the filtering mode is in full.I can reproduce the problem if I throttle the network

**Comment by dimisa-RUAdList** [comment]
@electrifying 
> microsoft edge 131.0.2903.70


Does the problem reproduce in other browsers?

**Comment by electrifying** [comment]
> @electrifying
> 
> > microsoft edge 131.0.2903.70
> 
> Does the problem reproduce in other browsers?

nope

**Comment by dimisa-RUAdList** [comment]
Opera, like Edge, has its own privacy tools. Try disabling them. Also check if the problem occurs after disabling uBO Lite.

**Comment by electrifying** [comment]
I can't reproduce it anymore, closing the ticket
