### ISSUE TITLE
streamingcommunity.computer: detection

### ISSUE THREAD

**Issue by T0NN0** [uBlockOrigin/uAssets#26285]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://streamingcommunity.computer/watch/4145?e=80721`

### Category

detection

### Description

ubo detected, black screen with a banner in the middle 

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 129169
 cosmetic: 56346
 scriptlet: 23208
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 40827-132, 2m
  ublock-badware: 12357-1, 2m
  ublock-privacy: 1596-23, 2m
  ublock-unbreak: 2525-1, 2m
  ublock-quick-fixes: 227-8, 2m
  easylist: 77759-614, 2m
  easyprivacy: 53290-739, 2m
  urlhaus-1: 9500-0, 2m
  plowe-0: 3540-0, 2m
  ITA-0: 8793-33, 2m
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1987 ms (selfie)
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  streamingcommunity.computer: 2
 extended:
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(remove-node-text, script, ;}}};break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(prevent-xhr, /thaudray\.com|putchumt\.com/)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(addEventListener-defuser, click, popName)
  ##+js(prevent-window-open, _blank)
  ##+js(remove-node-text, script, blockAdBlock)
```
</details>

**Comment by T0NN0** [comment]
forgot to add banner img 
![Screenshot (559)](https://github.com/user-attachments/assets/ba921c1f-7e92-4f83-91af-e06c8c33166f)

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
