### ISSUE TITLE
manhuaus.com: breakage

### ISSUE THREAD

**Issue by Nani86** [uBlockOrigin/uAssets#26282]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://manhuaus.com/manga/im-an-evil-god-1/chapter-510/`

### Category

breakage

### Description

It's a webcomic site and it doesn't work when I have ublock enabled in Firefox. It works okay in chrome without ublock. This is on an android phone

### Other extensions used

I only have pop up blocker enabled in Firefox mobile but there is no popup issues on this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 133
filterset (summary):
 network: 128881
 cosmetic: 58021
 scriptlet: 21510
 html: 2199
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 41627-217, 11m Δ
  ublock-badware: 12353-2, 11m Δ
  ublock-privacy: 1583-22, 11m Δ
  ublock-unbreak: 2586-3, 11m Δ
  ublock-quick-fixes: 232-6, 11m Δ
  adguard-mobile: 9963-12, now
  easylist: 77760-280, 11m Δ
  easyprivacy: 53290-78, 11m Δ
  urlhaus-1: 9500-0, now
  plowe-0: 3540-1065, now
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3850 ms (selfie)
 maxAssetCacheWait: 113 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  bidgear.com: 2
  disqus.com: 6
  googletagmanager.com: 1
  infolinks.com: 2
  koaptouw.com: 2
  muthfourre.com: 1
  pubfuture-ad.com: 2
  viglink.com: 2
 extended:
  ##.c-ads
  ##.body-top-ads
  ##+js(set-constant, rwt, noopFunc)
  ##+js(href-sanitizer, #main a[href^="/url?q=http"], ?q)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##.ad-content:not(:empty)
```
</details>

**Comment by stephenhawk8054** [comment]
Turn off all other extensions (except uBO), restart the browser and test again.
