### ISSUE TITLE
hifitorget.se: breakage

### ISSUE THREAD

**Issue by Klifords** [uBlockOrigin/uAssets#26289]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hifitorget.se/`

### Category

breakage

### Description

Almost nothing is shown on the page, however I noticed that by deactivating cosmetic filtering it seems to work sometimes.

### Other extensions used

Alternate player for twitch.tv, Enhancer for youtube, Hide shorts for youtube, I don't care about cookies, Return youtube dislike, Sponsorblock for youtube, User-agent switcher

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 139263
 cosmetic: 216824
 scriptlet: 36661
 html: 2553
listset (total-discarded, last-updated):
 added:
  adguard-social: 23209-43, 8m
  fanboy-cookiemonster: 52236-195, 8m
  fanboy-social: 16759-753, 8m
  ublock-annoyances: 5862-38, 1h.7m Δ
  adguard-cookies: 32721-3928, 8m
  adguard-popup-overlays: 28119-2208, 8m
  adguard-mobile-app-banners: 5574-35, 8m
  adguard-other-annoyances: 14635-454, 8m
  adguard-widgets: 2795-25, 8m
  easylist-annoyances: 4703-336, 8m
  easylist-chat: 217-17, 8m
  easylist-newsletters: 8310-606, 8m
  [3 lists not shown]: [too many]
 default:
  user-filters: 55-0, never
  ublock-filters: 41128-134, 1h.7m Δ
  ublock-badware: 12359-1, 1h.7m Δ
  ublock-privacy: 1582-22, 1h.7m Δ
  ublock-unbreak: 2583-1, 1h.7m Δ
  easylist: 77768-203, 1h.7m Δ
  easyprivacy: 53290-69, 1h.7m Δ
  urlhaus-1: 9175-0, 8m
  plowe-0: 3540-990, 8m
  SWE-1: 4867-30, 8m
  ublock-quick-fixes: 233-11, 1h.7m Δ
filterset (user): [array of 55 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 534 ms (selfie)
 maxAssetCacheWait: 108 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 no-cosmetic-filtering: true
 network:
  doubleclick.net: 2
  googlesyndication.com: 8
  googletagmanager.com: 2
  stpd.cloud: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
