### ISSUE TITLE
substack.com: breakage

### ISSUE THREAD

**Issue by chrmod** [uBlockOrigin/uAssets#26299]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
All substacks, eg. https://substack.com/leaderboard/culture/paid
```

### Description

Annoyance filter caused endless reloads
`substack.com##+js(trusted-set-cookie, intro_popup_last_hidden_at, $currentDate$, , , reload, 1)`

The `intro_popup_last_hidden_at` does not seem to take affect on this page, I assume the filter is no longer valid.

### Other extensions used

none

### Configuration

```
{
  "timeStamp": 1733390191210,
  "version": "1.61.2",
  "userSettings": {
    "advancedUserEnabled": true,
    "importedLists": [],
    "userFiltersTrusted": true
  },
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "urlhaus-1",
    "plowe-0",
    "fanboy-cookiemonster",
    "ublock-cookies-easylist",
    "adguard-cookies",
    "ublock-cookies-adguard",
    "easylist-chat",
    "easylist-newsletters",
    "easylist-notifications",
    "easylist-annoyances",
    "ublock-annoyances"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "edge-scheme",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-csp-reports: * true",
  "userFilters": ""
}
```

**Comment by chrmod** [comment]
Looks like it is fixed on the substack side. Can no longer reproduce neither with uBO nor Ghostery.

**Comment by stephenhawk8054** [comment]
Hmm... I can't reproduce at `https://whattocook.substack.com/`

**Comment by stephenhawk8054** [comment]
Do these work better?

```adb
entra.news,microsoftsecurityinsights.com,substack.com##[class*="_coverTheme"]:has(> .intro-popup)
entra.news,microsoftsecurityinsights.com,substack.com##.has-intro-popup.show-intro-popup #main:not(:has(.intro-popup)):style(visibility: visible !important;)
entra.news,microsoftsecurityinsights.com,substack.com##html.show-intro-popup:style(overflow: auto !important;)
entra.news,microsoftsecurityinsights.com,substack.com##html.show-intro-popup:remove-class(show-intro-popup)
entra.news,microsoftsecurityinsights.com,substack.com##+js(trusted-set-cookie, intro_popup_last_hidden_at, $currentDate$)
```

**Comment by chrmod** [comment]
@stephenhawk8054 can confirm that the new filters work as expected. Tested at:
* https://whattocook.substack.com/
* https://www.microsoftsecurityinsights.com/podcast
* https://entra.news/
* https://substack.com/leaderboard/culture/paid
