### ISSUE TITLE
time.is: detection

### ISSUE THREAD

**Issue by Giwayume** [uBlockOrigin/uAssets#26298]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://time.is/GMT
```

### Description

Popup displays, begging you to pay a subscription

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/0b1ff619-b88d-4b55-bd17-d792cf489251)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 127142
 cosmetic: 49339
 scriptlet: 21441
 html: 2204
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 41141-134, 1h.29m Δ
  ublock-badware: 12370-1, 1h.29m Δ
  ublock-privacy: 1589-22, 1h.29m Δ
  ublock-unbreak: 2583-1, 1h.29m Δ
  ublock-quick-fixes: 224-6, 1h.29m Δ
  easylist: 77786-208, 1h.29m Δ
  easyprivacy: 53291-69, 1h.29m Δ
  urlhaus-1: 9175-0, 17h.48m
  plowe-0: 3540-990, 1d.17h.50m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 137 ms (selfie)
 maxAssetCacheWait: 56 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  time.is: 1
  pub.network: 1
  quantserve.com: 1
 extended:
  ##.rad
  ##[data-freestar-ad][id]

```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
