### ISSUE TITLE
uk.pinterest.com: ads

### ISSUE THREAD

**Issue by LartoriaPendragon** [uBlockOrigin/uAssets#26293]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uk.pinterest.com/`

### Category

ads

### Description

When searching for content sponsored content as pins are still shown. These are indistinguishable from non-ads, when attempting to use the element picker only the image url can be extracted. No other elements can be extracted, this is the same for both ads and non ads. In the home page ads are shown as well. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 245112
 cosmetic: 215803
 scriptlet: 55401
 html: 2470
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2698-0, 1m
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 4698-42, 35m
  adguard-generic: 86122-4534, 1m
  adguard-spyware-url: 1804-249, 1m
  adguard-spyware: 116429-1571, 1m
  adguard-cookies: 32726-1692, 1m
  ublock-cookies-adguard: 1937-20, 1m
  fanboy-cookiemonster: 52236-19881, 27m
  ublock-cookies-easylist: 1937-1937, 27m
  adguard-social: 23209-1240, 1m
  fanboy-social: 16759-10456, 1m
  adguard-popup-overlays: 28119-2209, 1m
  [8 lists not shown]: [too many]
 default:
  user-filters: 28-0, never
  ublock-filters: 41128-327, 1m
  ublock-badware: 12364-10, 1m
  ublock-privacy: 1582-72, 1m
  ublock-unbreak: 2583-2, 1m
  ublock-quick-fixes: 233-6, 17m
  easylist: 77768-16075, 1m
  easyprivacy: 53291-29832, 1m
  urlhaus-1: 9175-0, 1h.22m
  plowe-0: 3540-1089, 1m
filterset (user): [array of 28 redacted]
switchRuleset:
 added: [array of 28 redacted]
hostRuleset:
 added: [array of 46 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 177 ms (selfie)
 maxAssetCacheWait: 132 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 no-cosmetic-filtering: true
 no-remote-fonts: true
 network:
  pinterest.com: 5
  recaptcha.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

Continue here: https://github.com/uBlockOrigin/uAssets/issues/25614

**Comment by amandello-afk** [comment]
Pinterest now detects UBlock, and says I have to disable it in order to use the website - if I don't disable it, it doesn't load
