### ISSUE TITLE
15min.lt: breakage

### ISSUE THREAD

**Issue by Vartotojas1234** [uBlockOrigin/uAssets#26290]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.15min.lt/video/panevezio-siaubas-nusivylimai-ryte-ir-zalgirio-laikas-supykti-be-driblingo-casino-admiral-261112`

### Category

breakage

### Description

Video does not work when uBlock Origin is switch on.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 273249
 cosmetic: 277312
 scriptlet: 56890
 html: 2486
listset (total-discarded, last-updated):
 added:
  adguard-generic: 86122-4228, 12m
  adguard-spyware-url: 1804-131, 35m
  adguard-spyware: 116428-1555, 12m
  curben-phishing: 712-3, 35m
  adguard-social: 23209-49, 35m
  adguard-cookies: 32722-65, 35m
  ublock-cookies-adguard: 1937-20, 12m
  adguard-popup-overlays: 28119-2100, 12m
  adguard-mobile-app-banners: 5574-33, 12m
  adguard-other-annoyances: 14630-432, 12m
  adguard-widgets: 2795-19, 12m
  easylist-annoyances: 4703-356, 12m
  [10 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 41128-134, 35m Δ
  ublock-badware: 12364-1, 35m Δ
  ublock-privacy: 1582-22, 35m Δ
  ublock-unbreak: 2583-1, 35m Δ
  ublock-quick-fixes: 233-6, 35m Δ
  easylist: 77768-2177, 35m Δ
  easyprivacy: 53290-29830, 35m Δ
  urlhaus-1: 9175-0, 35m
  plowe-0: 3540-1438, 12m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2382 ms (selfie)
 maxAssetCacheWait: 1225 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  15min.lt: 1
  cloudflareinsights.com: 4
  cxense.com: 4
  dimatter.ai: 2
  doubleclick.net: 3
  ebxcdn.com: 2
  gemius.pl: 2
  googlesyndication.com: 1
  imasdk.googleapis.com: 2
  inmobi.com: 2
  npttech.com: 1
  piano.io: 1
  stpd.cloud: 2
  teads.tv: 2
 extended:
  ###fb-root:not(body):not(html)
  ##.share--facebook
  ##.share--twitter
  ##.ads-cnt
  ##.share--vertical
  ##.dfp
  ##.page-item-lazyload
  ##.wrapper:style(margin-top: 0 !important)
  ##+js(no-setTimeout-if, insertBefore)
  ##+js(abort-current-script, setTimeout, '/admiral|String\.fromCh…
  ##+js(set-constant, admiral, noopFunc)
  ##+js(abort-on-property-read, _renderAdblock)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@Vartotojas1234 

add

```adb
15min.lt#@#+js(abort-current-script, setTimeout, '/admiral|String\.fromCharCode\(97,( )*?100,( )*?109,( )*?105,( )*?114,( )*?97,( )*?108\)|a%64%6d%69%72%61%6c|adm%69%72%61l|%61%64m%69r%61l|-engaged[\s\S]*?googletag[\s\S]*?decodeURI|ad%6dr%6c%4c%6fa%64%65%64|succeedscene\.com/')
```

`AdGuard – Popup Overlays` issue
@Alex-302

**Comment by Vartotojas1234** [comment]
> @Vartotojas1234
> 
> add
> 
> ```
> 15min.lt#@#+js(abort-current-script, setTimeout, '/admiral|String\.fromCharCode\(97,( )*?100,( )*?109,( )*?105,( )*?114,( )*?97,( )*?108\)|a%64%6d%69%72%61%6c|adm%69%72%61l|%61%64m%69r%61l|-engaged[\s\S]*?googletag[\s\S]*?decodeURI|ad%6dr%6c%4c%6fa%64%65%64|succeedscene\.com/')
> ```
> 
> `AdGuard – Popup Overlays` issue @Alex-302

Thank You

**Comment by Vartotojas1234** [comment]
> @Vartotojas1234
> 
> add
> 
> ```
> 15min.lt#@#+js(abort-current-script, setTimeout, '/admiral|String\.fromCharCode\(97,( )*?100,( )*?109,( )*?105,( )*?114,( )*?97,( )*?108\)|a%64%6d%69%72%61%6c|adm%69%72%61l|%61%64m%69r%61l|-engaged[\s\S]*?googletag[\s\S]*?decodeURI|ad%6dr%6c%4c%6fa%64%65%64|succeedscene\.com/')
> ```
> 
> `AdGuard – Popup Overlays` issue @Alex-302

Thank you so much

**Comment by Vartotojas1234** [comment]
@mapx- thank you so much
