### ISSUE TITLE
primevideo.com: breakage

### ISSUE THREAD

**Issue by tm48** [uBlockOrigin/uAssets#26291]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.primevideo.com/detail/0G58QC0EC0JAODYVH606Y1J5I1/ref=atv_hm_hom_c_cjm7wb_6_1?jic=8%7CEgNhbGw%3D`

### Category

breakage

### Description

When watching a video, at the moment an ad would play (the overlay for the remaining time of the ad shows up, althought does not) the subtitles begin to be out of sync (by the length of the ad that was supposed to be shown)

### Other extensions used

ghostery

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 137476
 cosmetic: 213512
 scriptlet: 34905
 html: 2470
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83840-173, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 103488-24516, now
  adguard-social: 23209-1578, now
  fanboy-thirdparty_social: 68-19, now
  fanboy-cookiemonster: 52236-52235, now
  fanboy-social: 16759-16759, now
  ublock-annoyances: 5865-180, 31m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 41128-447, 31m Δ
  ublock-badware: 12364-1, 31m Δ
  ublock-privacy: 1582-23, 31m Δ
  ublock-unbreak: 2583-6, 31m Δ
  easylist: 77768-287, 31m Δ
  easyprivacy: 53290-1395, 31m Δ
  urlhaus-1: 9175-0, now
  plowe-0: 3540-991, now
  ublock-quick-fixes: 233-11, 31m Δ
filterset (user): [empty]
trustedset:
 added: [array of 56 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1645 ms
 maxAssetCacheWait: 774 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 33
 network:
  primevideo.com: 5
  amazon.com: 28
```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/14512

**Comment by stephenhawk8054** [comment]
Country: Australia

**Comment by moto-ctrl** [comment]
same issue (strange AD overlay with timer in a middle of video, subtitles out of sync) - only started happening 3 or 4 days ago. Location: UK

**Comment by stephenhawk8054** [comment]
We can't investigate without the accounts. If you are willing to share account credentials, I'll give you email.
