### ISSUE TITLE
nowvideo.sx

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#263]
Hi, 

#### URL(s) where the issue occurs

`http://www.nowvideo.sx/video/f5d41e15b8ee6`

#### Describe the issue

Need to know why the `*$popup` filter doesn't catch the `about:blank` & `javascript` popups?

#### Versions

- Browser/version: Firefox 50.1.0

- uBlock Origin version: 1.10.4

#### Settings 

- http://i.imgur.com/ClkFCsW.png
- http://i.imgur.com/27IyofE.png

#### Screenshot 

![http://i.imgur.com/qRVpgPL.png](http://i.imgur.com/qRVpgPL.png)

Thank you.

**Comment by gorhill** [comment]
Did you try with 1.10.5b9?

**Comment by SMed79** [comment]
> Did you try with 1.10.5b9?

No, Before posting i just checked for a new update.

with the dev build 1.10.5b9 the popups are correctly managed.

![http://i.imgur.com/aIubZkf.png](http://i.imgur.com/aIubZkf.png)

Sorry & thanks for your time.

**Comment by SMed79** [comment]
Just noticed that uBO doesn't catch the `javascript` popups.
e.g `http://watchers.to/embed-b74061ffbrzk.html`

**OK**
`*$popup`
![http://i.imgur.com/urBj4ky.png](http://i.imgur.com/urBj4ky.png)

---

**OK**
`about:blank$popup`
![http://i.imgur.com/8GlUZRi.png](http://i.imgur.com/8GlUZRi.png)

---

**Fail**
```
javascript$popup
|javascript:$popup
|javascript^$popup
```
![http://i.imgur.com/gRpzLvq.png](http://i.imgur.com/gRpzLvq.png)

---
**Fail**
```
*$popup
@@about:blank$popup
```
![http://i.imgur.com/9dRTfz3.png](http://i.imgur.com/9dRTfz3.png)

**Comment by migueldemoura** [comment]
Try this:
`watchers.to##script:contains(window.open)`

These two are allowed by Easylist, probably as a fix for some adblock detection or something. I disabled them and nothing seems broken.

```
||hwcdn.net/ads/advertisement.js$script,important
||adsjudo.com^*/advertisement.js$script,important
```
You also add `,domain=watchers.to` to it.

**Comment by SMed79** [comment]
The filter `*$popup` also have no effect here `http://www.wholecloud.net/video/d1810bdddcc7b`

![http://i.imgur.com/IWGasa5.png](http://i.imgur.com/IWGasa5.png)

**Comment by ghajini** [comment]
`http://nowvideo.club/videos/a5w2nzl976t5`
unwanted redirects to shady sites
