### ISSUE TITLE
redketchup.io: detection

### ISSUE THREAD

**Issue by addisonxx** [uBlockOrigin/uAssets#26305]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://redketchup.io/image-resizer
```

### Description

Website now detects an adblocker and adds a 30 second countdown timer to download a photo after editing. 

### Other extensions used

Tampermonkey, Raindrop, and Dashlane

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="650" alt="Popup" src="https://github.com/user-attachments/assets/50e88f42-896a-4731-a5ff-bb1cf86a8373">
<img width="1334" alt="Logger" src="https://github.com/user-attachments/assets/4ca3e6b5-abf3-4778-b581-17c3ef73c0f7">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 125
filterset (summary):
 network: 137792
 cosmetic: 94969
 scriptlet: 27863
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52236-184, 18h.19m
 default:
  user-filters: 228-0, never
  easylist: 77770-481, now Δ
  easyprivacy: 53291-639, now Δ
  plowe-0: 3540-0, 16h.19m
  ublock-badware: 12368-1, now Δ
  ublock-filters: 40836-377, now Δ
  ublock-privacy: 1603-22, now Δ
  ublock-quick-fixes: 219-0, now Δ
  ublock-unbreak: 2525-0, now Δ
  urlhaus-1: 17855-0, 23h.34m
filterset (user): [array of 248 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 4 redacted]
urlRuleset:
 added: [array of 4 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 225 ms (selfie)
 maxAssetCacheWait: 36 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.

https://github.com/uBlockOrigin/uAssets/issues/16076
