### ISSUE TITLE
amazon.com: breakage

### ISSUE THREAD

**Issue by colibri-pi** [uBlockOrigin/uAssets#26304]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.amazon.com/Face-Off-John-Travolta/dp/B002PT1KH6?crid=3JCK1HV8HR4V5&dib=eyJ2IjoiMSJ9.YRnHLZkIMHaJaBAer7Jtv8D7p4_A_jAEcdswIlxkZd2ehYGgeJiOii1WwVcTfYvu28CNpj2EkOmn3V6fYJCsG3Wis8Kqz3L7E9Rx1N8E4b_iTG773Wg2ljiS6vbfmEPkrdkZArBolBWH6_X7BpZCJRBYEikhx86Zss6f7_8wuIVm_41Bt8KgKooR4ZXVzbeOfwj5vWvR6p8cnHWNfuoJdGbRG4Jzsfop_npnjwTgnv0.IZFctky6SNwKU7fxbW-hXgue8fYPVMkpj1cxKM_n7nA&dib_tag=se&keywords=face%2Foff&qid=1733281405&s=instant-video&sprefix=face%2Fo%2Cinstant-video%2C323&sr=1-1
```

### Description

When I pause a video it's staying paused even after I click play and reload the page. Also video previews are not playing with sound. When I click unmute they just stop playing.

### Other extensions used

I have firefox extensions for emojis and language translation.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
(I don't know what this is asking for)

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>    
(I don't know what this is asking for)

**Comment by stephenhawk8054** [comment]
> Configuration

> (I don't know what this is asking for)

Open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here.

**Comment by colibri-pi** [comment]
Okay, going to try to do that now.

**Comment by colibri-pi** [comment]
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 127150
 cosmetic: 49328
 scriptlet: 21428
 html: 2204
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41104-140, 2h.12m Δ
  ublock-badware: 12370-1, 2h.12m Δ
  ublock-privacy: 1590-22, 2h.12m Δ
  ublock-unbreak: 2583-1, 2h.12m Δ
  ublock-quick-fixes: 224-0, 2h.12m Δ
  easylist: 77810-208, 2h.12m Δ
  easyprivacy: 53291-69, 2h.12m Δ
  urlhaus-1: 9175-0, 1d.10m
  plowe-0: 3537-990, 5d.22h.53m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 835 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 54
 network:
  amazon.com: 51
  amazon-adsystem.com: 1
  d1y002tclu9djj.cloudfront.net: 1
  media-amazon.com: 1
 extended:
  ###nav-swmslot
  ##+js(json-prune, cuepointPlaylist)
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[@value="Ad"]] |…

**Comment by colibri-pi** [comment]
It just happened now with a Netflix video:

uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 127150
 cosmetic: 49328
 scriptlet: 21428
 html: 2204
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41104-140, 2h.19m Δ
  ublock-badware: 12370-1, 2h.19m Δ
  ublock-privacy: 1590-22, 2h.19m Δ
  ublock-unbreak: 2583-1, 2h.19m Δ
  ublock-quick-fixes: 224-0, 2h.19m Δ
  easylist: 77810-208, 2h.19m Δ
  easyprivacy: 53291-69, 2h.19m Δ
  urlhaus-1: 9175-0, 1d.18m
  plowe-0: 3537-990, 5d.23h.1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 835 ms (selfie)
 maxAssetCacheWait: 85 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 87
 network:
  netflix.com: 87

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.
