### ISSUE TITLE
screenshot-media.com: ads

### ISSUE THREAD

**Issue by monsteragarden** [uBlockOrigin/uAssets#26319]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://screenshot-media.com/politics/human-rights/angelina-jolie-brad-pitt-abuse-allegations/`

### Category

ads

### Description

Amazon ads are all over the page, repeating regularly

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 138790
 cosmetic: 49326
 scriptlet: 21432
 html: 2207
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 41112-134, 10m Δ
  ublock-badware: 12379-1, 10m Δ
  ublock-privacy: 1591-22, 10m Δ
  ublock-unbreak: 2585-1, 10m Δ
  ublock-quick-fixes: 228-6, 10m Δ
  easylist: 77860-604, 10m Δ
  easyprivacy: 53295-682, 10m Δ
  urlhaus-1: 20755-0, 1h.10m
  plowe-0: 3542-0, 5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 228 ms (selfie)
 maxAssetCacheWait: 46 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 70
 no-large-media: true
 network:
  facebook.net: 10
  getnitropack.com: 10
  googletagmanager.com: 10
  nitrocdn.com: 10
  quantserve.com: 10
  tiktok.com: 10
  tru.am: 10
```
</details>

**Comment by gorhill** [comment]
This works for me:

    screenshot-media.com##[href^="https://www.tryamazonmusic.com/"]
