### ISSUE TITLE
poki.com: detection

### ISSUE THREAD

**Issue by Guillito30** [uBlockOrigin/uAssets#26315]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://poki.com/es`

### Category

detection

### Description

x

### Other extensions used

s

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
x

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 123
filterset (summary):
 network: 140800
 cosmetic: 56402
 scriptlet: 23755
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40810-403, 1h.2m Δ
  ublock-badware: 12377-1, 1h.2m Δ
  ublock-privacy: 1605-22, 1h.2m Δ
  ublock-unbreak: 2527-1, 1h.2m Δ
  ublock-quick-fixes: 222-0, 1h.2m Δ
  easylist: 77845-529, 1h.2m Δ
  easyprivacy: 53294-652, 1h.2m Δ
  urlhaus-1: 20755-0, now
  plowe-0: 3542-0, now
  spa-0: 3809-3, now
  spa-1: 6122-193, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 663 ms (selfie)
 maxAssetCacheWait: 213 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 no-remote-fonts: true
 network:
  google.com: 5
```
</details>x

**Comment by Guillito30** [comment]
f

**Comment by gorhill** [comment]
We are unable to reproduce.

> - [x] I did not answer truthfully to ALL the above checkboxes.

Go through all steps again, and truthfully apply them this time -- something else on your side you might have dismissed in the prerequisite steps is likely causing your issue.

**Comment by mapx-** [comment]
@Guillito30 reset uBO to defaults, disable other extensions, test again
