### ISSUE TITLE
[nsfw] bestcam.tv: breakage

### ISSUE THREAD

**Issue by Anonxyz01** [uBlockOrigin/uAssets#26312]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bestcam.tv/`

### Category

breakage

### Description

play button doesn't work on any video

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140797
 cosmetic: 56406
 scriptlet: 21980
 html: 2207
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41110-134, 33m Δ
  ublock-badware: 12379-1, 33m Δ
  ublock-privacy: 1591-22, 33m Δ
  ublock-unbreak: 2585-1, 33m Δ
  ublock-quick-fixes: 228-6, 33m Δ
  easylist: 77845-224, 33m Δ
  easyprivacy: 53294-69, 33m Δ
  urlhaus-1: 20755-0, 1h.36m
  plowe-0: 3542-992, 1h.36m
  spa-0: 3809-23, 1h.36m
  spa-1: 6122-251, 1h.36m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 233 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  qzzzzzzzzzqq.com: 2
 extended:
  ##+js(remove-node-text, script, pre_roll_url)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
```
</details>

**Comment by gorhill** [comment]
Caused by `bestcam.tv##+js(remove-node-text, script, pre_roll_url)` in uBO's filters.
