### ISSUE TITLE
web.skype.com: breakage

### ISSUE THREAD

**Issue by jerrwu** [uBlockOrigin/uAssets#26316]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://web.skype.com/`

### Category

breakage

### Description

Chats are blank, functions normally with ublock origin disabled.

### Other extensions used

SponsorBlock for youtube, control panel for twitter, tampermonkey, return youtube dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/user-attachments/assets/754b1215-7d1f-46fc-b7aa-f0e9892f139e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 132
filterset (summary):
 network: 250087
 cosmetic: 143643
 scriptlet: 29578
 html: 2207
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1046-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2698-0, 1h.31m
  adguard-spyware-url: 1814-249, 22m
  adguard-spyware: 116435-599, 22m
  adguard-cookies: 32754-61, 22m
  ublock-cookies-adguard: 1941-20, 22m
  adguard-popup-overlays: 28136-1429, 22m
  adguard-mobile-app-banners: 5578-34, 22m
  adguard-other-annoyances: 14636-283, 22m
  CHN-0: 25823-43, now
  JPN-1: 15545-110, now
 default:
  user-filters: 82-0, never
  ublock-filters: 41110-154, 22m
  ublock-badware: 12379-1, 22m
  ublock-privacy: 1591-71, 22m
  ublock-unbreak: 2585-2, 22m
  ublock-quick-fixes: 228-6, 22m
  easylist: 77845-253, 22m
  easyprivacy: 53294-29757, 22m
  urlhaus-1: 20755-0, 22m
  plowe-0: 3542-1076, 22m
filterset (user): [array of 82 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 798 ms (selfie)
 maxAssetCacheWait: 186 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  skype.com: 2
  microsoft.com: 3
 extended:
  ###rx-vlv-28
  ##.r-13awgt0.css-1dbjc4n > .r-13awgt0.css-1dbjc4n > div > div > …
  ##.r-13awgt0.css-1dbjc4n > div > div > div:nth-of-type(2)
```
</details>

**Comment by gorhill** [comment]
Your uBO settings/lists are heavily modified from default settings/lists.

Did you really try with default settings/lists?

**Comment by jerrwu** [comment]
It was a custom filter, my bad everyone.

**Comment by jerrwu** [comment]
Resolved by removing outdated custom filter.
