### ISSUE TITLE
gotfreefax.com: breakage

### ISSUE THREAD

**Issue by ibigfire** [uBlockOrigin/uAssets#26323]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.gotfreefax.com/`

### Category

breakage

### Description

With uBlock's Cosmetic Filtering on the section for uploading PDF/Doc/JPG files to fax gets removed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With filtering off: 
![image](https://github.com/user-attachments/assets/ead4e392-de75-49e6-ab22-c0b22a295abe)

With filtering on: 
![image](https://github.com/user-attachments/assets/bb85da0d-5cfb-4358-9eab-51e8a6dc4846)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 138951
 cosmetic: 49346
 scriptlet: 21434
 html: 2207
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=rawlist: 152-0, 13m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=rawlist: 0-0, 13m
 default:
  user-filters: 21-1, never
  ublock-filters: 41117-134, 13m
  ublock-badware: 12379-1, 13m
  ublock-privacy: 1591-22, 13m
  ublock-unbreak: 2585-1, 13m
  easylist: 77870-221, 13m
  easyprivacy: 53295-72, 13m
  plowe-0: 3542-992, 13m
  urlhaus-1: 20755-0, 13m
  ublock-quick-fixes: 228-10, 13m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 102 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1707 ms
 maxAssetCacheWait: 450 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 1
  intergient.com: 3
 extended:
  ##div:nth-of-type(2) > div:nth-of-type(2)
  ###adContainer
  #@#div#contentRight.col-12.col-lg-6
```
</details>

**Comment by D4niloMR** [comment]
Remove `gotfreefax.com##div:nth-of-type(2) > div:nth-of-type(2)` from your "[My filters](https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-My-filters)"

**Comment by ibigfire** [comment]
> Remove `gotfreefax.com##div:nth-of-type(2) > div:nth-of-type(2)` from your "[My filters](https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-My-filters)"

That doesn't fix it, that was me trying to sort out the issue and was already commented out at the time of making this issue.
