### ISSUE TITLE
cbc.ca: nuisance

### ISSUE THREAD

**Issue by Apocalypso36** [uBlockOrigin/uAssets#26321]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.cbc.ca/amp/1.7395621`

### Category

nuisance

### Description

Ublock fails to block a privacy notice that shows up at the top of the website. 

### Other extensions used

None 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20241205-145239](https://github.com/user-attachments/assets/096453d4-bfc2-4941-b7b9-b2095bfc1351)

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 133
filterset (summary):
 network: 228166
 cosmetic: 193833
 scriptlet: 46656
 html: 2208
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  easyprivacy: null
  plowe-0: null
 added:
  adguard-generic: 86055-4224, 1h.55m
  adguard-spyware-url: 1814-131, 1h.55m
  adguard-spyware: 116435-1572, 1h.55m
  curben-phishing: 755-0, 1h.55m
  adguard-cookies: 32754-62, 1h.55m
  ublock-cookies-adguard: 1979-22, 1h.55m
  adguard-social: 23219-47, 1h.55m
  adguard-popup-overlays: 28136-885, 1h.55m
  adguard-mobile-app-banners: 5578-40, 1h.55m
  adguard-other-annoyances: 14636-433, 1h.55m
  adguard-widgets: 2794-15, 1h.55m
 default:
  ublock-filters: 41622-135, 1h.55m
  ublock-badware: 12373-1, 1h.55m
  ublock-privacy: 1591-22, 1h.55m
  ublock-unbreak: 2586-1, 1h.55m
  ublock-quick-fixes: 228-6, 1h.55m
  adguard-mobile: 9973-131, 1h.55m
  easylist: 77813-2252, 1h.55m
  urlhaus-1: 20755-0, 1h.55m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4358 ms
 maxAssetCacheWait: 299 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  cbc.ca: 4
  ampproject.org: 3
  conductrics.com: 2
  cxense.com: 2
  demdex.net: 3
  imasdk.googleapis.com: 1
 extended:
  ##.social-box
  ##.ad
  ##AMP-AD
  ##amp-ad
  ##amp-social-share
  ##amp-app-banner
  ##+js(abort-on-property-write, xhr.prototype.realSend)
  ##+js(addEventListener-defuser, click, /event_callback=function\…
  ##.sharelinks
```
</details>

**Comment by gorhill** [comment]
This works for me:

    cbc.ca##.privacy-notice
