### ISSUE TITLE
aniwave.se: popups

### ISSUE THREAD

**Issue by upsidupsis** [uBlockOrigin/uAssets#26329]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://aniwave.se/`

### Category

popups

### Description

when trying to use this website to watch anime as I click play on the episode I am redirected to google ad pages and even to aliexpress

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://www.aliexpress.com/gcp/300001528/Aliexpress?af=7299098&dp=888994905681302221&aff_fcid=0ccbbd26ddc94fee84170ef9cb170459-1733516423194-00370-_DFAXD1L&tt=CPS_NORMAL&aff_fsk=_DFAXD1L&aff_platform=portals-promotion&sk=_DFAXD1L&aff_trace_key=0ccbbd26ddc94fee84170ef9cb170459-1733516423194-00370-_DFAXD1L&terminal_id=176f40abe21942e88aa79f5d8b150233&wh_html=csr&forcebottom=true&aff_downgrade=true&wh_ttid=pc&OLP=1094500508_f&o_s_id=1094500508

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 140043
 cosmetic: 49349
 scriptlet: 23241
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40852-141, 39m Δ
  ublock-badware: 12377-1, 39m Δ
  ublock-privacy: 1619-22, 39m Δ
  ublock-unbreak: 2528-1, 39m Δ
  ublock-quick-fixes: 204-0, 39m Δ
  easylist: 77904-621, 39m Δ
  easyprivacy: 53293-738, 39m Δ
  urlhaus-1: 21985-0, now
  plowe-0: 3538-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 935 ms (selfie)
 maxAssetCacheWait: 255 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  amung.us: 1
  bidgear.com: 1
  disqus.com: 3
  googletagmanager.com: 1
  jwpltx.com: 1
  narrative.io: 2
  nozoakamsaun.net: 1
  pippio.com: 1
  rezync.com: 1
  rqtrk.eu: 1
  rtmark.net: 4
  sharethis.com: 2
  twiebayed.com: 1
  tzegilo.com: 1
  viglink.com: 2
 extended:
  ##+js(prevent-window-open, _blank)
  ##+js(set-cookie, __pf, 1)
  ##+js(abort-current-script, document.write)
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
> the episode

Please give exact link and which server you chose.

**Comment by upsidupsis** [comment]
https://aniwave.se/anime-watch/inazuma-eleven/ep-3

also not sure how i would know what server I'm on

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
