### ISSUE TITLE
layarkaca21.nexus: breakage

### ISSUE THREAD

**Issue by bocauman** [uBlockOrigin/uAssets#26327]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://layarkaca21.nexus/parallel-2024/`

### Category

breakage

### Description

seemed like ABPINDO filter is the culprit. unchecking it, it will work but with tons ads unfiltered.
maybe filter is outdated.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 147881
 cosmetic: 131633
 scriptlet: 29874
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52246-211, 3m
  ublock-cookies-easylist: 1941-0, 3m
  fanboy-social: 16622-2, 3m
  easylist-annoyances: 4712-99, 3m
  easylist-chat: 217-0, 3m
  easylist-newsletters: 8313-32, 3m
  easylist-notifications: 3463-3, 3m
  IDN-0: 10209-3, 5m
 default:
  user-filters: 0-0, never
  ublock-filters: 40826-410, 1h.18m Δ
  ublock-badware: 12377-1, 1h.18m Δ
  ublock-privacy: 1619-22, 1h.18m Δ
  ublock-unbreak: 2528-0, 1h.18m Δ
  ublock-quick-fixes: 222-0, 1h.18m Δ
  easylist: 77884-506, 1h.18m Δ
  easyprivacy: 53293-728, 1h.18m Δ
  urlhaus-1: 21535-0, 3m
  plowe-0: 3542-0, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 496 ms
 maxAssetCacheWait: 195 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  histats.com: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  rts.gdn: 5
  sharethis.com: 1
 extended:
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="whatsapp://send?text="]
  ##[href^="https://vpnnawala.site"]
  ##[title^="388HERO" i]
  ##[title^="BANDARXL" i]
  ##[title^="BISNIS4D" i]
  ##[title^="ENAKSLOT" i]
  ##[title^="EnakSlot" i]
  ##[title^="PENTASLOT" i]
  ##[title^="Pentaslot" i]
  ##[title^="RUSIA777" i]
  ##[title^="bandarxl" i]
  ##[title^="rusia777" i]
  ##a[href^="https://vpn89.site/"]
  ##img[alt="GAZA88" i]
  ##img[alt="INDO666" i]
  ##img[alt="PENTASLOT" i]
  ##img[alt^="388HERO" i]
  ##img[alt^="BANDARXL" i]
  ##img[alt^="BISNIS4D" i]
  ##img[alt^="BandarXL" i]
  ##img[alt^="Bisnis4D" i]
  ##img[alt^="EnakSlot" i]
  ##img[alt^="Enakslot" i]
  ##img[alt^="JUDI89" i]
  ##img[alt^="PENTASLOT" i]
  ##img[alt^="Pentaslot" i]
  ##img[alt^="RUSIA777" i]
  ##img[alt^="bandarxl" i]
  ##.jw-wrapper > div[style="opacity: 0; visibility: hidden; overf…
```
</details>

**Comment by stephenhawk8054** [comment]
> breakage

What breakages?

Also please report to here: https://github.com/ABPindo/indonesianadblockrules/issues
