### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by EnzoDIWLK** [uBlockOrigin/uAssets#26326]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://open.spotify.com/playlist/37i9dQZF1E38CmO6CZNZx8`

### Category

breakage

### Description

from time to time, the music stops when an ads is supposed to start. Need to refresh to work again

### Other extensions used

nordpass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/b4a463ee-0219-4246-97df-c285676f13cb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 139593
 cosmetic: 49333
 scriptlet: 21449
 html: 2210
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41125-134, 20m Δ
  ublock-badware: 12379-1, 20m Δ
  ublock-privacy: 1605-22, 20m Δ
  ublock-unbreak: 2586-1, 20m Δ
  ublock-quick-fixes: 228-6, 20m Δ
  easylist: 77884-224, 20m Δ
  easyprivacy: 53293-69, 20m Δ
  urlhaus-1: 21535-0, now
  plowe-0: 3542-992, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1338 ms (selfie)
 maxAssetCacheWait: 131 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 2
  spotifycdn.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
