### ISSUE TITLE
moappmovies.blogspot.com: detection

### ISSUE THREAD

**Issue by VXsz** [uBlockOrigin/uAssets#26322]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://moappmovies.blogspot.com/`

### Category

detection

### Description

The pop-up only happens with uBlock, disabling it doesn't show the pop up (and I get instantly bomber-ed with insane ads and redirects). Since I have had some light toggles and added filter lists, to ensure it's not my custom filters, I've backed up my ublock settings and then reset it to default settings, but the anti-adblock pop still popped up.

I'd love to know how to fix these issues btw if any contributes can share some lightly-detailed steps, would be great as I want to contribute to ublock and kill these anti-adblocker pop ups :p (I don't have as much webdev experience, but have good general code understanding)

### Other extensions used

- Privacy badger
- Privacy Pass
- Bypass Paywalls Clean
These are the most relevant, because I have a lot of extensions (most are neiche like X website bypass and such), I don't listing them would help since only ublock is affecting the status of detection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-12 Mo App Movies](https://github.com/user-attachments/assets/f7624369-4acd-419c-a8ee-e4a25d3b364a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 138813
 cosmetic: 49396
 scriptlet: 21434
 html: 2207
listset (total-discarded, last-updated):
 default:
  user-filters: 92-11, never
  ublock-filters: 41117-134, now
  ublock-badware: 12379-1, now
  ublock-privacy: 1591-22, now
  ublock-unbreak: 2585-1, now
  easylist: 77870-221, now
  easyprivacy: 53295-69, now
  urlhaus-1: 20755-0, now
  plowe-0: 3542-992, now
  ublock-quick-fixes: 228-10, now
filterset (user): [array of 93 redacted]
trustedset:
 added: [array of 59 redacted]
switchRuleset:
 added: [array of 11 redacted]
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 17350 ms (selfie)
 maxAssetCacheWait: 48 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 no-scripting: true
 network:
  sharethis.com: 1
  vulnerableimmigrateaboveaverage.com: 1
```
</details>

**Comment by VXsz** [comment]
Seems like a simple
`##.sy-adblock`
does the trick. Not sure how robust it is tho.

**Comment by D4niloMR** [comment]
> if any contributes can share some lightly-detailed steps

There is https://github.com/uBlockOrigin/uBlock-issues/wiki/Introduction-to-basic-filtering-syntax#investigating-anti-adblock-scripts
