### ISSUE TITLE
wetteronline.de: breakage

### ISSUE THREAD

**Issue by VolkerAC** [uBlockOrigin/uAssets#26336]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.wetteronline.de/wetter/aachen/walheim`

### Category

breakage

### Description

none

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 142594
 cosmetic: 54816
 scriptlet: 21466
 html: 2214
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41167-134, 2m
  ublock-badware: 12385-1, 2m
  ublock-privacy: 1607-22, 2m
  ublock-unbreak: 2589-1, 2m Δ
  easylist: 77942-222, 2m
  easyprivacy: 53297-70, 2m
  urlhaus-1: 22160-0, 2m
  plowe-0: 3540-991, 2m
  DEU-0: 7820-39, 2m
  ublock-quick-fixes: 217-6, 2m
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 114 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  wetteronline.de: 7
 extended:
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(abort-on-property-read, __eiPb)
```
</details>

**Comment by D4niloMR** [comment]
> breakage

What is broken?

**Comment by mapx-** [comment]
@VolkerAC reset uBO to defaults, disable other extensions, test again

**Comment by elmo667** [comment]
I can help even though the reporter seems to have disappeared. Wetteronline now does this - WITH DEFAULT FILTERING RULES -:    
"This page could not be loaded properly due to incorrect / bad filtering rule(s) of adblockers in use. Please disable all adblockers to continue using the website. (click OK if you'd like to learn more)". "OK" forwards you to https://report.error-report.com    
    
which seemingly is a site owned by ad sellers that tells you that you can ""fix"" the ""incorrect"" filtering rules by whitelisting the domain in question. Havent managed to track down which .js resource inplements this nagging dialog box yet.

**Comment by JobcenterTycoon** [comment]
If it was the issue it should be fixed now.

**Comment by elmo667** [comment]
> If it was the issue it should be fixed now.

yes it is, can confirm!  amazing work, thanks!!
