### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by mpissarello** [uBlockOrigin/uAssets#26333]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.aliexpress.com/`

### Category

breakage

### Description

- Hovering with the mouse on "Welcome Sign in / Register" does not shows the submenu popup
- On the articles pages, you cannot switch between the images
- All goes ok if you switch down to "basic" filtering or disabling the "EasyList – Other Annoyances"

I already seen the [issue #24796](https://github.com/uBlockOrigin/uAssets/issues/24796), but it can be applied only to uBO, I cannot find how to apply to uBOL

### Other extensions used

Application Launcher For Drive (by Google) 3.10
Checker Plus for Gmail™ 30.0
Checker Plus for Google Calendar™ 39.1.1
Google Documents offline 1.84.1
Google Translate 2.0.16
Keepa - Amazon Price Tracker 5.42

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

**"EasyList – Other Annoyances" enabled:**

![enabled](https://github.com/user-attachments/assets/cefad51f-005d-46fa-b8d8-6c1dfd37d0b2)

<hr>

**"EasyList – Other Annoyances" disabled:**

![disabled](https://github.com/user-attachments/assets/46d3bd61-3a4f-4b88-a0a7-c946cf2dee6b)

</details>

### Configuration

```yaml
version: uBOL 2024.12.2.22
mode: complete / complete
rulesets:
 default
 block-lan
 dpollock-0
 adguard-spyware-url
 annoyances-cookies
 annoyances-overlays
 annoyances-social
 annoyances-widgets
 annoyances-others
 stevenblack-hosts
 ita-0
```

**Comment by Yuki2718** [comment]
@gorhill EasyList – Other Annoyances (maybe ``aliexpress.com##+js(addEventListener-defuser, mouseleave)` `) is causing this only on uBOL.

**Comment by Yuki2718** [comment]
@mpissarello It was fixed in upstream filter 2 days ago. Wait for next update of uBOL itself.
