### ISSUE TITLE
Ad-placeholders are not being hidden

### ISSUE THREAD

**Issue by Magciool** [uBlockOrigin/uAssets#2633]
### URL(s) where the issue occurs

https://www.youtube.com/
https://www.computerbase.de/

### Describe the issue
Ad-placeholders are not being hidden

### Screenshot(s)

https://i.imgur.com/twji1o6.png
https://i.imgur.com/BhQOVUg.png

### Versions

- Browser/version: Chrome 67.0.3396.87 + Firefox 60.0.2
- uBlock Origin version: 1.16.10

### Settings

- block WEB-RTC
- expert view

**Comment by llacb47** [comment]
Can this be closed?

**Comment by okiehsch** [comment]
Yes.

**Comment by wertzuz** [comment]
They are back again on computerbase.de
@okiehsch

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon Sorry, can you reproduce?

**Comment by JobcenterTycoon** [comment]
No its all fine.
