### ISSUE TITLE
bjs.com: breakage

### ISSUE THREAD

**Issue by Monomancer** [uBlockOrigin/uAssets#26348]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bjs.com/search`

### Category

breakage

### Description

No products will load when using the search feature or when shopping by category. Searching for anything, or navigating to any category will just display the nav bar, some banner ads, and a blank screen where the products should be. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140566
 cosmetic: 49376
 scriptlet: 21478
 html: 2215
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41195-134, now
  ublock-badware: 12385-1, now
  ublock-privacy: 1608-22, now
  ublock-unbreak: 2590-1, now
  ublock-quick-fixes: 217-6, now
  easylist: 77972-223, now
  easyprivacy: 53299-70, now
  urlhaus-1: 22420-0, now
  plowe-0: 3540-991, now
filterset (user): [empty]
trustedset:
 added: [array of 19 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 257 ms (selfie)
 maxAssetCacheWait: 40 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  bjs.com: 4
  btttag.com: 3
  cnstrc.com: 1
  lr-ingest.io: 1
  monetate.net: 1
  newrelic.com: 1
  pendo.io: 12
  redditstatic.com: 1
  riskified.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Reproduced on `https://www.bjs.com/category/grocery/3000000000000244989`

Test

```adb
@@||ac.cnstrc.com/browse/$xhr,domain=bjs.com
```
