### ISSUE TITLE
[Anti-adblock] rockpapershotgun.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2634]
### URL(s) where the issue occurs

`https://www.rockpapershotgun.com/`

### Describe the issue

Anti-adblock. Comes up on every refresh so it is considered hard anti-adblock. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/41754339-39a3e742-758f-11e8-94a6-11492ba59552.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.10

### Settings

English default.

**Comment by zaphodbeebblebrox** [comment]
Update filter lists, fixed earlier today.

**Comment by jspenguin2017** [comment]
Ah, I totally missed that.
