### ISSUE TITLE
news.tvb.com: breakage

### ISSUE THREAD

**Issue by Happypig375** [uBlockOrigin/uAssets#26341]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://news.tvb.com/tc/greaterchina/67543910830efd4d7983d30b/%E5%85%A9%E5%B2%B8-%E6%B7%B1%E5%9C%B3%E6%9C%89%E5%85%AC%E5%BB%81%E5%A2%9E%E8%A8%AD%E8%B6%9F%E9%96%80%E8%83%BD%E5%BF%AB%E9%80%9F%E5%B0%87%E5%BB%81%E6%A0%BC%E7%94%B1%E7%94%B7%E8%BD%89%E5%A5%B3-%E6%BB%BF%E8%B6%B3%E5%A5%B3%E5%BB%81%E9%9C%80%E6%B1%82%E9%87%8F
```

### Description

uBlock Origin loaded: after the page finishes loading, the news becomes "目前沒有相關新聞內容" which means "relevant news currently unavailable".
uBlock Origin not loaded: page is displayed normally.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without uBlock Origin
![image](https://github.com/user-attachments/assets/de221558-6830-4510-9f0e-0b56ccabf0f7)
With uBlock Origin
![image](https://github.com/user-attachments/assets/9db0da8f-e279-404e-9431-51ceaefcdff3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140147
 cosmetic: 49323
 scriptlet: 21459
 html: 2215
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41177-134, now
  ublock-badware: 12385-1, now
  ublock-privacy: 1605-22, now
  ublock-unbreak: 2589-1, now
  ublock-quick-fixes: 224-28, now
  easylist: 77768-208, now
  easyprivacy: 53293-69, now
  urlhaus-1: 22160-0, now
  plowe-0: 3540-991, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 510 ms
 maxAssetCacheWait: 321 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
enable the regional list AdGuard Chinese
