### ISSUE TITLE
abs-cbn.com: ads / breakage

### ISSUE THREAD

**Issue by thedev2203** [uBlockOrigin/uAssets#26346]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.abs-cbn.com/news/nation/2024/12/7/woman-dies-after-being-run-over-by-bus-in-qc-2306`

### Category

ads

### Description

An advertisement placeholder is displayed.

Steps to Reproduce:
1. Visit homepage and click on an article.
2. Scroll down until you see an "ADVERTISEMENT" box.

Filter for ad placeholder:
`##.css-4dbdht.MuiBox-root`

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_mk5jgeGOtv](https://github.com/user-attachments/assets/7cfdca9f-0374-40ea-8096-16c869346aaa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140272
 cosmetic: 49369
 scriptlet: 21472
 html: 2215
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41177-134, now
  ublock-badware: 12385-1, now
  ublock-privacy: 1607-22, now Δ
  ublock-unbreak: 2589-1, now Δ
  ublock-quick-fixes: 221-6, now Δ
  easylist: 77942-222, now Δ
  easyprivacy: 53297-70, now Δ
  urlhaus-1: 22160-0, now
  plowe-0: 3540-991, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1275 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 54
 network:
  abs-cbn.com: 3
  amplitude.com: 18
  datazoom.io: 1
  doubleclick.net: 6
  go-mpulse.net: 1
  google.com: 6
  googletagmanager.com: 2
  outbrain.com: 1
  skypack.dev: 1
  techlab-cdn.com: 4
  youtube.com: 11
 extended:
  ##.OUTBRAIN
  ##div[style*="999999"]:has(div[style^="background-color:#ECEDEF;…
  ##div[id^="div-articleOOP"] ~ div:has(.imp-adSlot-0)
  ##.css-168qn5i, .css-1slfery, .css-xcd31q:has(div[class^="imp-ad…
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.web_bind_fetch, …
  ##+js(trusted-prevent-dom-bypass, Node.prototype.appendChild, fe…
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/26347

**Comment by stephenhawk8054** [comment]
> Scroll down until you see an "ADVERTISEMENT" box.

I can't reproduce.

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

Next time, just comment in your old thread: https://github.com/uBlockOrigin/uAssets/issues/26246

---

Fixed here: https://github.com/uBlockOrigin/uAssets/commit/344df0e26ab931a46c80f1f2d6eb2b4c770af04e
