### ISSUE TITLE
abs-cbn.com: breakage

### ISSUE THREAD

**Issue by thedev2203** [uBlockOrigin/uAssets#26347]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.abs-cbn.com/entertainment/studios/tv/2024/12/7/bts-asap-stars-bring-holiday-party-vibes-to-abs-cbn-christmas-id-2024-0036`

### Category

breakage

### Description

Video player does not show up when uBlock Origin is enabled.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock Origin enabled
![firefox_qcyjCo5x2Y](https://github.com/user-attachments/assets/4ada79e6-bbbb-4963-869b-bb50cee17102)
![firefox_QhusUetZ33](https://github.com/user-attachments/assets/d7c523dc-6396-417f-a2c8-496fd7ab62c8)
uBlock Origin disabled

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140304
 cosmetic: 49369
 scriptlet: 21472
 html: 2215
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41177-134, now
  ublock-badware: 12385-1, now Δ
  ublock-privacy: 1608-22, now Δ
  ublock-unbreak: 2589-20, now
  ublock-quick-fixes: 221-6, now
  easylist: 77972-624, now
  easyprivacy: 53299-26, now
  urlhaus-1: 22160-0, now
  plowe-0: 3540-615, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1275 ms
 maxAssetCacheWait: 7 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 35
 network:
  abs-cbn.com: 2
  amplitude.com: 6
  datazoom.io: 1
  doubleclick.net: 2
  go-mpulse.net: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  gstatic.com: 1
  outbrain.com: 1
  skypack.dev: 1
  techlab-cdn.com: 5
  viralize.tv: 10
 extended:
  ##div[style*="999999"]:has(div[style^="background-color:#ECEDEF;…
  ##div[id^="div-articleOOP"] ~ div:has(.imp-adSlot-0)
  ##.css-168qn5i, .css-1slfery, .css-xcd31q:has(div[class^="imp-ad…
  ##.OUTBRAIN
```
</details>

**Comment by stephenhawk8054** [comment]
Just continue in 1 thread.
