### ISSUE TITLE
die-schoensten-wanderwege.de: nuisance

### ISSUE THREAD

**Issue by repofodu** [uBlockOrigin/uAssets#26357]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.die-schoensten-wanderwege.de/`

### Category

nuisance

### Description

I did enable cookies lists.
Cookie banner at the bottom.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![grafik](https://github.com/user-attachments/assets/fb00942a-7280-4e26-a2a1-a000887626f2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 159349
 cosmetic: 132785
 scriptlet: 31807
 html: 2488
listset (total-discarded, last-updated):
 added:
  block-lan: 64-0, now
  curben-phishing: 623-0, now
  fanboy-cookiemonster: 52241-194, now
  ublock-cookies-easylist: 1959-6, now
  fanboy-social: 16524-11, now
  easylist-annoyances: 4722-46, now
  easylist-chat: 217-0, now
  easylist-newsletters: 8328-41, now
  easylist-notifications: 3467-163, now
  ublock-annoyances: 5881-54, 13m
  dpollock-0: 11715-338, now
 default:
  user-filters: 0-0, never
  ublock-filters: 41204-134, now
  ublock-badware: 12392-1, 13m
  ublock-privacy: 1610-22, now
  ublock-unbreak: 2593-1, now
  ublock-quick-fixes: 220-6, 13m
  easylist: 77998-223, now
  easyprivacy: 53299-72, now
  urlhaus-1: 22875-0, now
  plowe-0: 3540-1359, now
  DEU-0: 7820-41, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 749 ms
 maxAssetCacheWait: 494 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/96e822461e042aecec90003464cadbee46367dbf
