### ISSUE TITLE
budni.de: breakage

### ISSUE THREAD

**Issue by repofodu** [uBlockOrigin/uAssets#26368]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.budni.de/`

### Category

breakage

### Description

I did enable additional filters. Broken with cookie filters (grey overlay, no scrolling). Is it ok to report this here?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 159253
 cosmetic: 132786
 scriptlet: 31808
 html: 2490
listset (total-discarded, last-updated):
 added:
  block-lan: 64-0, 46m
  curben-phishing: 623-0, 46m
  fanboy-cookiemonster: 52241-194, 46m
  ublock-cookies-easylist: 1959-6, 46m
  fanboy-social: 16524-11, 46m
  easylist-annoyances: 4722-46, 46m
  easylist-chat: 217-0, 46m
  easylist-newsletters: 8328-41, 46m
  easylist-notifications: 3467-163, 46m
  ublock-annoyances: 5884-54, 53m
  dpollock-0: 11715-338, 46m
 default:
  user-filters: 0-0, never
  ublock-filters: 41205-134, 46m
  ublock-badware: 12296-1, 53m
  ublock-privacy: 1610-22, 46m
  ublock-unbreak: 2593-1, 46m
  ublock-quick-fixes: 220-6, 53m
  easylist: 77998-223, 46m
  easyprivacy: 53299-72, 46m
  urlhaus-1: 22875-0, 46m
  plowe-0: 3540-1359, 46m
  DEU-0: 7820-41, 46m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 192 ms (selfie)
 maxAssetCacheWait: 88 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  aticdn.net: 2
  cleverpush.com: 3
  trustcommander.net: 1
 extended:
  ###tc-privacy-wrapper
  ###footer_tc_privacy
  ##.tc-privacy-banner
```
</details>

**Comment by gorhill** [comment]
Needed in EasyList Cookie Notice:

    budni.de##body:style(overflow:initial!important;position:initial!important)
    budni.de###grey-overlay

cc @ryanbr
