### ISSUE TITLE
chat.tchatche.com: detection

### ISSUE THREAD

**Issue by Ploppoeur** [uBlockOrigin/uAssets#26370]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://chat.tchatche.com/chat`

### Category

detection

### Description

le bloqueur est détecter de suite résultat le site est impraticable car il y a trop de publicité dessus.

--

**TL: The blocker is detected immediately, resulting in the site being unusable because there is too much advertising on it.**

### Other extensions used

j'en utilise pas d'autre

--

**TL: I don't use any other**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 159507
 cosmetic: 55990
 scriptlet: 23462
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 25732-37, now
  easylist: 77998-460, 1h.28m Δ
  easyprivacy: 53299-867, 1h.28m Δ
  plowe-0: 3540-30, now
  ublock-badware: 12390-35, 1h.28m Δ
  ublock-filters: 40904-451, 1h.28m Δ
  ublock-privacy: 1624-22, 1h.28m Δ
  ublock-quick-fixes: 214-6, 1h.28m Δ
  ublock-unbreak: 2535-17, 1h.28m Δ
  urlhaus-1: 22875-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 642 ms (selfie)
 maxAssetCacheWait: 93 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 191
 network:
  tchatche.com: 4
  criteo.net: 1
  dailymotion.com: 25
  dm-event.net: 80
  dmxleo.com: 4
  doubleclick.net: 41
  doubleverify.com: 10
  googlesyndication.com: 5
  hhkld.com: 4
  onetag-sys.com: 6
  outbrain.com: 3
  rubiconproject.com: 2
  scorecardresearch.com: 3
  track-selectmedia.com: 3
 extended:
  ##+js(prevent-fetch, secure.adnxs.com/ptv, war:noop-vast4.xml)
  ##+js(xml-prune, VAST, , barstoolsports.com)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

https://github.com/uBlockOrigin/uAssets/issues/19156
