### ISSUE TITLE
perplexity.ai: breakage

### ISSUE THREAD

**Issue by mikhoul** [uBlockOrigin/uAssets#26372]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.perplexity.ai/`

### Category

breakage

### Description

When UBO is activated I can't click on the button to switch to anonymous account and I can't delete a thread when I click on the ... button in the upper page. or even use the New thread button.

### Other extensions used

None for testing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 188282
 cosmetic: 241044
 scriptlet: 56557
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 83704-83704, now
  https://secure.fanboy.co.nz/fanboy-annoyance.txt: 84599-60699, now
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 89-0, now
  adguard-cookies: 32780-83, now
  adguard-generic: 85614-6549, now
  adguard-mobile-app-banners: 5581-1126, now
  adguard-other-annoyances: 14410-366, now
  adguard-popup-overlays: 28138-1620, now
  adguard-widgets: 2795-3, now
  easylist-annoyances: 4722-137, now
  easylist-notifications: 3467-9, now
  fanboy-cookiemonster: 52241-4094, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 41-1, never
  FRA-0: 25732-37, now
  easylist: 77998-592, 1h.56m Δ
  easyprivacy: 53299-948, 1h.56m Δ
  plowe-0: 3540-30, now
  ublock-badware: 12390-16, 1h.56m Δ
  ublock-filters: 40904-734, 1h.56m Δ
  ublock-privacy: 1624-111, 1h.56m Δ
  ublock-quick-fixes: 214-6, 1h.56m Δ
  ublock-unbreak: 2535-8, 1h.56m Δ
  urlhaus-1: 22875-0, now
filterset (user): [array of 41 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 allowGenericProceduralFilters: true
supportStats:
 allReadyAfter: 7504 ms
 maxAssetCacheWait: 2264 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  perplexity.ai: 1
  cloudflareinsights.com: 1
  google.com: 1
  sentry.io: 2
  singular.net: 1
 extended:
  ##+js(trusted-replace-argument, Array.prototype.includes, 0, und…
  ##+js(set-session-storage-item, appDownloadBannerDismissed, true…
  ##+js(abort-on-stack-trace, window.screen.height, setTimeout)
  ##+js(set-local-storage-item, appDownloadBannerDismissed, true)
  ##+js(set-session-storage-item, signUpBannerDismissed, true)
  ##+js(set-session-storage-item, shouldShowAuthBannerAfterQuery, …
  ##+js(set-cookie, trackingAllowed, false)
  ##+js(addEventListener-defuser, wheel, ===a){var n="deltaY"in t?…
  ##+js(set-session-storage-item, signUpBannerDismissed, false)
```
</details>

**Comment by stephenhawk8054** [comment]
You are using many additional and custom lists / filters. Backup your configuration, reset to default settings and test again.
