### ISSUE TITLE
tk.de: nuisance

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#26377]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tk.de/techniker`

### Category

nuisance

### Description

Cookie notice

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/user-attachments/assets/4c1ff84b-18e0-464e-8034-5041bdd46d06)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 145221
 cosmetic: 100719
 scriptlet: 27665
 html: 2218
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 52241-200, never
  ublock-cookies-easylist: 1959-0, never
 default:
  user-filters: 0-0, never
  ublock-filters: 41211-134, now
  ublock-badware: 12296-1, now
  ublock-privacy: 1610-22, now
  ublock-unbreak: 2593-1, now
  ublock-quick-fixes: 217-6, now
  easylist: 77997-223, now
  easyprivacy: 53299-70, now
  urlhaus-1: 22875-0, now
  plowe-0: 3540-991, now
  DEU-0: 7820-39, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1438 ms
 maxAssetCacheWait: 20 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by Endurance4390** [comment]
It's back.

<details>
<summary>Screenshot(s)</summary>




<img width="2552" height="1274" alt="Image" src="https://github.com/user-attachments/assets/16b70dcf-e4ca-4a29-b0f6-67c5f2cb0dc0" />



</details>

```yaml
name: uBlock Origin Lite
version: 2026.426.1536
browser: Edge 147 (win)
filtering:
 site: complete
 default: complete
permission: all
badge: 1
rules: 25573
rulesets:
 +adguard-spyware-url
 +annoyances-ai
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +annoyances-social
 +annoyances-widgets
 +block-lan
 deu-0
 easylist
 easyprivacy
 pgl
 ublock-badware
 ublock-filters
 urlhaus-full
scripting:
 ublock-filters.main
 ublock-filters.isolated
 easyprivacy.main
 easyprivacy.isolated
 ublock-badware.main
 annoyances-cookies.main
 annoyances-cookies.isolated
 annoyances-overlays.main
 annoyances-overlays.isolated
 annoyances-social.isolated
 annoyances-others.main
 annoyances-others.isolated
 annoyances-notifications.main
 annoyances-notifications.isolated
 css-generic-all
 css-generic-some
 css-generichigh
 prevent-popup
 css-specific
 css-procedural
```
