### ISSUE TITLE
tonordersitye.com: detection

### ISSUE THREAD

**Issue by 95jay** [uBlockOrigin/uAssets#26376]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tonordersitye.com/s?dbfb4543`

### Category

detection

### Description

this website says adblock detected please disable it.

### Other extensions used

only ublock origin i use

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 140985
 cosmetic: 49362
 scriptlet: 21485
 html: 2218
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41211-134, 12m Δ
  ublock-badware: 12296-1, 12m Δ
  ublock-privacy: 1610-22, 12m Δ
  ublock-unbreak: 2593-1, 12m Δ
  ublock-quick-fixes: 220-6, 12m Δ
  easylist: 77997-223, 12m Δ
  easyprivacy: 53299-70, 12m Δ
  urlhaus-1: 22875-0, now
  plowe-0: 3540-991, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 153 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  dfdgfruitie.xyz: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Its a fake website without real content. "To reach the target page, complete the following steps:" is fake.
