### ISSUE TITLE
[nsfw] cash.app: popups

### ISSUE THREAD

**Issue by Manitra1976** [uBlockOrigin/uAssets#26378]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://cash.app/?utm_source=launch-card-ndef`

### Category

popups

### Description

This website pops up everytime i open my phone to use it

### Other extensions used

None but Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 133
filterset (summary):
 network: 142424
 cosmetic: 58082
 scriptlet: 21558
 html: 2220
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41721-217, 1m Δ
  ublock-badware: 12290-2, 1m Δ
  ublock-privacy: 1611-22, 1m Δ
  ublock-unbreak: 2596-3, 1h.31m Δ
  ublock-quick-fixes: 220-6, 1m Δ
  adguard-mobile: 9980-12, now
  easylist: 77997-296, 1h.31m Δ
  easyprivacy: 53299-79, 1m Δ
  urlhaus-1: 22875-0, now
  plowe-0: 3540-1065, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 188 ms (selfie)
 maxAssetCacheWait: 74 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  fullstory.com: 1
```
</details>

**Comment by Manitra1976** [comment]
![Uploading Screenshot_20241208_175728_Firefox.jpg…]()

**Comment by gorhill** [comment]
Something else on your phone is causing that page to open, you will have to investigate on your side what is causing this.

**Comment by Manitra1976** [comment]
Where would I start?

**Comment by Manitra1976** [comment]
Anyone know how to fix this issue?

**Comment by stephenhawk8054** [comment]
Check your phone apps if there are any suspicious apps or not. Better to ask for help in other android communities.
