### ISSUE TITLE
blick.ch: breakage

### ISSUE THREAD

**Issue by tnr20** [uBlockOrigin/uAssets#26383]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.blick.ch/wirtschaft/id20391444.html
```

### Description

All Video Player in this News Site are not working. it seems that ublock block too much

### Other extensions used

i use only ublock , no other extensions are installed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-12-09 ](https://github.com/user-attachments/assets/0adfeb78-c5a9-47e9-839b-183cd42fb7fb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 148909
 cosmetic: 107770
 scriptlet: 25971
 html: 2219
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32782-41, now
  ublock-cookies-adguard: 1964-21, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 4723-50, now
  easylist-chat: 217-0, now
  easylist-newsletters: 8321-38, now
  easylist-notifications: 3467-163, now
  TUR-0: 11093-36, now
 default:
  user-filters: 1-0, never
  ublock-filters: 41214-136, 47m Δ
  ublock-badware: 12295-1, 47m Δ
  ublock-privacy: 1472-22, 5d.14h.56m
  ublock-unbreak: 2597-1, 47m Δ
  ublock-quick-fixes: 219-6, 47m Δ
  easylist: 78958-202, 5d.14h.56m
  easyprivacy: 53262-73, 5d.14h.56m
  urlhaus-1: 22835-0, 3h.7m
  plowe-0: 3537-997, 7d.20m
  DEU-0: 7820-40, 3h.7m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 612 ms (selfie)
 maxAssetCacheWait: 117 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.

Continue here: https://github.com/uBlockOrigin/uAssets/issues/12446
