### ISSUE TITLE
picrew.me: breakage

### ISSUE THREAD

**Issue by alextiang** [uBlockOrigin/uAssets#26388]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://picrew.me/ja/`

### Category

[breakage]

### Description

1. Set the uBO-L filtering mode to "complete."  
2. Return to the web page and click the uBO-L icon in the toolbar.  
3. After clicking the icon, change the filtering mode to "basic," and the web page will break.  

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-12-10 at 11 46 30 AM](https://github.com/user-attachments/assets/271d340e-a354-4955-b5a9-0679aca1c226)

![Screenshot 2024-12-10 at 12 00 38 PM](https://github.com/user-attachments/assets/a0db872f-227b-4c81-ad80-5b8b3b71eb27)

</details>

### Configuration

```yaml
version: uBOL 2024.12.2.22
mode: basic / complete
rulesets:
 default
 cze-0
 deu-0
 jpn-1
 kor-1
 ltu-0
```

**Comment by stephenhawk8054** [comment]
Yes, the site needs "complete" mode to not break.
