### ISSUE TITLE
https://dankmemer.lol/freemium: detection

### ISSUE THREAD

**Issue by luftra** [uBlockOrigin/uAssets#26380]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://dankmemer.lol/freemium
```

### Description

![Screenshot 2024-12-08 211304](https://github.com/user-attachments/assets/7ece0e15-fdf3-4847-ba11-56d22fae69ee)
UBlock Origin is detected.

### Other extensions used

Brave Shields disabled, Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-12-08 211304](https://github.com/user-attachments/assets/a611d544-fced-4c18-bc46-d9804616c115)

</details>

### Configuration

<details>
<summary>Details</summary>

 uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 140941
 cosmetic: 35146
 scriptlet: 23264
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 40897-583, 54m Δ
  ublock-badware: 12294-12, 57m
  ublock-privacy: 1624-23, 57m
  ublock-unbreak: 2535-1, 54m Δ
  ublock-quick-fixes: 214-0, 57m
  easylist: 77997-14460, 57m
  easyprivacy: 53299-662, 57m
  urlhaus-1: 22835-0, 57m
  plowe-0: 3540-0, 57m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 512 ms (selfie)
 maxAssetCacheWait: 36 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 1
  doubleclick.net: 1
  nitropay.com: 4
 extended:
  ##+js(no-setTimeout-if, nads)
```yaml


```
<
![Screenshot 2024-12-08 211857](https://github.com/user-attachments/assets/f0ffca76-0dd1-4afc-92af-23e0894cec20)
>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.

**Comment by luftra** [comment]
Turns out it was actually an issue with the Privacy Badger extension. 😅

**Comment by luftra** [comment]
> > * [x]  I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.

Sorry about that.
