### ISSUE TITLE
ydr.com: breakage

### ISSUE THREAD

**Issue by crazy4orioles** [uBlockOrigin/uAssets#26386]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
ydr.com
```

### Description

The videos to the site do not pop up when ublock Origin is active.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![![image](https://github.com/user-attachments/assets/50e8c305-3422-4477-8385-64ede09ebc33)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 141137
 cosmetic: 49362
 scriptlet: 23286
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 78033-478, 42m Δ
  easyprivacy: 53297-619, 42m Δ
  plowe-0: 3540-0, 3m
  ublock-badware: 12334-1, 42m Δ
  ublock-filters: 40910-388, 42m Δ
  ublock-privacy: 1631-22, 42m Δ
  ublock-quick-fixes: 221-0, 42m Δ
  ublock-unbreak: 2539-19, 42m Δ
  urlhaus-1: 22950-0, 3m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 698 ms (selfie)
 maxAssetCacheWait: 92 ms
 cacheBackend: indexedDB
```
</details>

**Comment by mapx-** [comment]
reset uBO to defaults, do not touch any setting, disable other extensions, test again

**Comment by D4niloMR** [comment]
@crazy4orioles test:

```adb
@@||player.ex.co/player/$script,domain=ydr.com
ydr.com#@#.pbs__player
```

Click on uBO icon > :gear: [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
