### ISSUE TITLE
theguardian.com: breakage

### ISSUE THREAD

**Issue by thamesynne** [uBlockOrigin/uAssets#26389]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.theguardian.com/politics/live/2024/dec/10/uk-politics-live-rachel-reeves-spending-review-keir-starmer-cyprus`

### Category

breakage

### Description

The entire live feed disappears when uBlock Origin is enabled. It doesn't complain about it; it just... disappears.

### Other extensions used

SingleFile

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/85fb1f7a-9719-4048-9430-3271ad676501)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 128
filterset (summary):
 network: 142227
 cosmetic: 49379
 scriptlet: 21498
 html: 2221
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 41211-134, now
  ublock-badware: 12336-1, now
  ublock-privacy: 1617-22, now
  ublock-unbreak: 2598-1, now
  ublock-quick-fixes: 228-6, now
  easylist: 78045-224, now
  easyprivacy: 53301-70, now
  urlhaus-1: 24040-0, now
  plowe-0: 3540-991, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7330 ms
 maxAssetCacheWait: 3029 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 no-remote-fonts: true
 network:
  theguardian.com: 14
  guim.co.uk: 2
  optoutadvertising.com: 1
 extended:
  ##.js-ad-slot
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
  ##section.dcr-1xdhyk6
  ##div[id^="dfp-ad-"]
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

**Comment by thamesynne** [comment]
I was POSITIVE it wasn't a duplicate. Hence clicking that box. But no, rather than assume I made an honest mistake, do please be smug and condescending in as few characters as possible, that'll really encourage people to report problems.

I even followed the link to the button to make sure. Guess what? It doesn't work for me.

**Comment by thamesynne** [comment]
So I went back and checked again. If it is a duplicate, it's not of one that's obvious when you click the "check for duplicates" button. I couldn't find the report it's a duplicate of, and I checked all of them. So please, tell me which article _is_ it a duplicate of?

**Comment by stephenhawk8054** [comment]
Report all breakages of the same site in 1 thread, there are a lot of "breakage" threads already: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22theguardian.com%22

**Comment by thamesynne** [comment]
"of the same site" - that would perhaps be a good thing to not *in the template*, don't you think?. there were four breakage threads, and none of them described the issue i was reporting. was i supposed to intuit that you meant something other than the obvious by "duplicate" using clairvoyance?

Anyway, thanks for putting me off uBlock Origin. And no, I don't think I'll be reporting this issue again. Or, you know, any issue.

(...not for the first time, I wonder if I'd have got a slightly less dismissive reponse with a different screen name - say, to pick an example completely at random, "Stephen"? Or maybe "James"?)
