### ISSUE TITLE
evowars.io

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#2639]
![2018-06-22-evowars io](https://user-images.githubusercontent.com/5884000/41786626-51708274-7646-11e8-8735-da7133948cf0.png)
`https://evowars.io/?v=1.3.8`

game don't load

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by mapx-** [comment]
I fixed the anti adb appearing on the page (and limiting the  game).

However, using the default setup, the game still loads well for me.
