### ISSUE TITLE
index.hu: breakage

### ISSUE THREAD

**Issue by cybericius** [uBlockOrigin/uAssets#26390]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://index.hu/belfold/2024/12/09/m0-s-autout-magyar-kozut-savvaltas-baleset-autos/`

### Category

breakage

### Description

the video is blocked, that's a normal content

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 153086
 cosmetic: 170709
 scriptlet: 36410
 html: 2512
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32807-1678, now
  ublock-cookies-adguard: 1967-21, now
  fanboy-cookiemonster: 51895-19752, now
  ublock-cookies-easylist: 1967-1967, now
  adguard-social: 23231-1234, now
  fanboy-social: 16496-10143, now
  fanboy-thirdparty_social: 68-19, now
  adguard-popup-overlays: 28145-2187, now
  adguard-mobile-app-banners: 5581-47, now
  adguard-other-annoyances: 14426-384, now
  adguard-widgets: 2803-55, now
  easylist-annoyances: 4726-1114, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41213-329, now
  ublock-badware: 12336-12, now
  ublock-privacy: 1617-23, now
  ublock-unbreak: 2598-2, now
  ublock-quick-fixes: 228-6, now
  easylist: 78045-14227, now
  easyprivacy: 53301-72, now
  urlhaus-1: 24040-0, now
  plowe-0: 3540-992, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 673 ms (selfie)
 maxAssetCacheWait: 263 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  adocean.pl: 1
  facebook.net: 2
  gemius.pl: 1
  google-analytics.com: 2
  googletagmanager.com: 2
  inmobi.com: 1
  onesignal.com: 2
 extended:
  ##.itemShare
  ##.megoszt
  ##[class*="ad-container"]
  ###ad_null_position
  ##body:style(overflow: auto !important)
```
</details>

**Comment by cybericius** [comment]
Fanboy – Anti-Facebook causes it

**Comment by stephenhawk8054** [comment]
It's a video from facebook. That list blocks correctly. If you want to watch videos from facebook, you should not use that list: https://github.com/uBlockOrigin/uAssets/discussions/26325#discussioncomment-11483418

**Comment by cybericius** [comment]
> It's a video from facebook. That list blocks correctly. If you want to watch videos from facebook, you should not enable that list: [#26325 (reply in thread)](https://github.com/uBlockOrigin/uAssets/discussions/26325#discussioncomment-11483418)

Oh, yeah, I just realized it after I checked the content source. Thanks.
