### ISSUE TITLE
xlogic.org: nuisance

### ISSUE THREAD

**Issue by Dodi25-droid** [uBlockOrigin/uAssets#26397]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://xlogic.org/`

### Category

nuisance

### Description

the coockie banner is removed correctly as you can see in the screenshots. However, the darkening of the page is not removed and prevents scrolling the page.

### Other extensions used

none other

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With active ublock
![immagine](https://github.com/user-attachments/assets/cb682f35-b6bc-43e0-85db-f59a40a7af77)

With ublock not activated
![immagine](https://github.com/user-attachments/assets/c0ba726c-b0a4-4841-88f5-777445f6498d)

Normal webpage view
![immagine](https://github.com/user-attachments/assets/155d8644-d754-4175-bacf-79ddf9337b20)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 1004226
 cosmetic: 270959
 scriptlet: 55188
 html: 2498
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl: 125157-65132, never
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/multi.txt: 156009-57809, never
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt: 653035-60160, never
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/filters.txt: 40755-40742, never
  adguard-generic: 85685-10757, never
  adguard-mobile: 10000-748, never
  adguard-spyware-url: 1816-131, never
  adguard-spyware: 116453-41380, never
  block-lan: 64-2, never
  curben-phishing: 524-15, never
  adguard-cookies: 32821-3986, never
  ublock-cookies-adguard: 1967-1967, never
  [15 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41210-134, 37m
  ublock-badware: 12336-1, 37m
  ublock-privacy: 1617-22, 37m
  ublock-unbreak: 2598-1, 37m
  ublock-quick-fixes: 227-6, 37m
  easylist: 78045-224, 37m
  easyprivacy: 53297-70, 37m
  urlhaus-1: 23485-0, 37m
  plowe-0: 3541-991, 37m
  ITA-0: 8793-42, 37m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3206 ms
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  trustpilot.com: 1
 extended:
  ##.trustpilot-widget
  ###wpca-popup-modal
  ###wpca-bar
```
</details>

**Comment by gorhill** [comment]
Need:

    xlogic.org###wpca-lay-out-wrapper
    xlogic.org##html:style(overflow:initial!important)

Fixable in EasyList Cookie Notices and/or AdGuard Cookie Notices.
