### ISSUE TITLE
ev01.to:  ads placeholder

### ISSUE THREAD

**Issue by david79111** [uBlockOrigin/uAssets#26395]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ev01.to/`

### Category

ads leftover

### Description

<details><summary>Without adblocker it looks like this</summary>

![Screenshot_20241210-201325_Firefox Nightly](https://github.com/user-attachments/assets/f58a3a21-0ad2-4155-b9a4-88e3662f525a)
</details>

<details><summary>With adblocker like this</summary>

![Screenshot_20241210-201339_Firefox Nightly](https://github.com/user-attachments/assets/8efc23d9-2d11-448f-a181-1acb20ccc9e5)
</details>

As can be seen the is a space between the search and view full site button. And if you click that space it leads you to the links that were turned invisible by ublock.
The space shouldnt be there and the space shouldnt lead you anywhere as it is meant to be blocked by ublock.

### Other extensions used

no other extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 135
filterset (summary):
 network: 143134
 cosmetic: 58122
 scriptlet: 21570
 html: 2222
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41723-135, now
  ublock-badware: 12335-1, now
  ublock-privacy: 1618-22, now
  ublock-unbreak: 2601-1, now
  ublock-quick-fixes: 226-6, now
  adguard-mobile: 10000-97, now
  easylist: 78066-298, now
  easyprivacy: 53301-79, now
  urlhaus-1: 23485-0, now
  plowe-0: 3541-1066, now
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1632 ms
 maxAssetCacheWait: 559 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  ev01.to: 2
  googletagmanager.com: 1
  ptugnins.net: 2
  sharethis.com: 2
  sysmeasuring.net: 1
  wfpwsfwk.com: 2
```
</details>

**Comment by gorhill** [comment]
Enable "EasyList -- Social Widgets" in "Filter lists" pane in the dashboard.
