### ISSUE TITLE
[nsfw] bl103.pafmo.cn: [unknown]

### ISSUE THREAD

**Issue by oddvestiges** [uBlockOrigin/uAssets#26394]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bl103.pafmo.cn/13.html`

### Category

[unknown]

### Description

一个未经拦截的nsfw网址

### Other extensions used

没有其他扩展

--

**TL: An unblocked NSFW URL**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium Mobile: 131
filterset (summary):
 network: 159943
 cosmetic: 98573
 scriptlet: 26601
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32821-71, 1m
  ublock-cookies-adguard: 2000-0, 1m
 default:
  user-filters: 37-1, never
  ublock-filters: 41423-225, 23m Δ
  ublock-badware: 12328-2, 23m Δ
  ublock-privacy: 1632-22, 23m Δ
  ublock-unbreak: 2543-2, 23m Δ
  ublock-quick-fixes: 222-0, 23m Δ
  adguard-mobile: 10000-12, now
  easylist: 78045-722, 23m Δ
  easyprivacy: 53301-746, 23m Δ
  urlhaus-1: 23485-0, now
  plowe-0: 3541-83, now
  CHN-0: 25868-96, now
filterset (user): [array of 37 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4805 ms
 maxAssetCacheWait: 709 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 no-cosmetic-filtering: true
 no-large-media: true
 no-remote-fonts: true
 no-scripting: true
 network:
  pafmo.cn: 4
```
</details>

**Comment by gorhill** [comment]
What is the issue?

You are using an unsupported browser -- which one is this?

Also you disabled cosmetic filtering, disabled javascript, disabled large media elements, etc. We do not investigate of fix issue arising from heavy customizations.
