### ISSUE TITLE
desidime.com - Missed ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#264]
There are ads created as posts in the **_`https://www.desidime.com`_** forums, these posts are created by user "**Ad Bot**". These ads might be selected by the **_Ad Bot_** text field.

**Error URL:** `https://www.desidime.com/forums/hot-deals-online/topics/air-asia-domestic-tickets-at-99-international-at-999`

**SS:** https://i.imgur.com/2JZk1eR.png

_**Note:** Using uBO v1.10.4 & Chrome 55 with default filters._

**Comment by mapx-** [comment]
add
`desidime.com##.wcard:has(.ico-ad-bot1)`

**Comment by gotitbro** [comment]
@mapx- That does it, thanks.
