### ISSUE TITLE
uploadhaven.com: breakage

### ISSUE THREAD

**Issue by ITAXHIxD** [uBlockOrigin/uAssets#26406]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://uploadhaven.com/download/d35610b7daac5798fa36078444139ec1`

### Category

breakage

### Description

i am downloading a game and its not getting downloaded

### Other extensions used

![image](https://github.com/user-attachments/assets/51caba16-243c-4986-84ec-5482daa8fddf)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 128
filterset (summary):
 network: 141836
 cosmetic: 49377
 scriptlet: 23290
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40915-142, 3m
  ublock-badware: 12339-1, 3m
  ublock-privacy: 1631-22, 3m
  ublock-unbreak: 2540-0, 3m
  ublock-quick-fixes: 223-0, 3m
  easylist: 78058-626, 3m
  easyprivacy: 53297-737, 3m
  urlhaus-1: 23630-0, 3m
  plowe-0: 3541-0, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1253 ms
 maxAssetCacheWait: 9 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  uploadhaven.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by waterfluoridation** [comment]
you can try to get links from `steamunlocked.net`

**Comment by mapx-** [comment]
@ITAXHIxD reset uBO to defaults, disable other extensions, test again
