### ISSUE TITLE
gamepressure.com: ads

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#26403]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

`https://www.gamepressure.com/newsroom/gta-6-is-paralyzing-rival-publishers-they-make-their-decisions-co/za7676`

### Description

ads are blocked but their spaces in some places of the page arent removed.

### Other extensions used

IDA extension (an add-on for internet download manager)

### Configuration

```yaml
uBlock Origin: 1.61.2
Firefox: 128
filterset (summary):
 network: 120729
 cosmetic: 129022
 scriptlet: 27096
 html: 2220
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
 added:
  https://secure.fanboy.co.nz/r/fanboy-ultimate.txt: 215934-445, 2d.2h
  spa-1: 6122-89, 2d.3h.1m
 default:
  user-filters: 13-1, never
  ublock-filters: 41211-325, 1h.29m Δ
  ublock-badware: 12341-1, 1h.29m Δ
  ublock-privacy: 1617-27, 1h.29m Δ
  ublock-unbreak: 2598-36, 1h.29m Δ
  ublock-quick-fixes: 226-0, 1h.29m Δ
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1490 ms
 maxAssetCacheWait: 526 ms
 cacheBackend: indexedDB
```

**Comment by gorhill** [comment]
Need `gamepressure.com##.ad`.

cc @ryanbr

**Comment by gorhill** [comment]
@Felipefpl Please us the chat icon button in the popup panel to report a filter issue next time, this way a template will be autofilled and we will better know what happened on your side with the page.

**Comment by x-R0b0T-x** [comment]
<img width="1032" height="280" alt="Image" src="https://github.com/user-attachments/assets/259c6179-1981-4bcd-89a8-4ae10ffd40a2" />

<img width="331" height="285" alt="Image" src="https://github.com/user-attachments/assets/d4389c12-377c-4e76-bcf8-58120b3d3795" />

**Comment by gorhill** [comment]
What's the point of posting cropped screenshots without any context on how to reproduce?

**Comment by x-R0b0T-x** [comment]
Because the topic title already exists.
I didn't intend to start another one.
Did I?
There are empty frames reserved for advertisements that are visible.

**Comment by gorhill** [comment]
I can't reproduce what I see in your screenshots anywwhere on the page at the URL in opening comment.
