### ISSUE TITLE
econodata.com.br: breakage

### ISSUE THREAD

**Issue by 00b00** [uBlockOrigin/uAssets#26417]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.econodata.com.br/consulta-empresa/32487278000121-METROLAB-SOLUCOES-EM-ENGENHARIA-CLINICA-LTDA`

### Category

breakage

### Description

The website initially loads and displays content correctly. However, after some time (a few seconds), the content is replaced with a 404 error message, making it impossible to view the intended information.

This behavior occurs consistently when uBlock Origin is active.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

ublock on:
![image](https://github.com/user-attachments/assets/1f8ac680-fc88-49be-b6db-565b57aece23)
ublock off:
![image](https://github.com/user-attachments/assets/064b2a27-457e-4f20-a5f9-128b24b10496)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 142839
 cosmetic: 53575
 scriptlet: 23849
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 78076-514, 36m Δ
  easyprivacy: 53302-652, 36m Δ
  plowe-0: 3541-0, now
  spa-1: 6138-17, now
  ublock-badware: 12355-1, 36m Δ
  ublock-filters: 40944-406, 36m Δ
  ublock-privacy: 1635-22, 36m Δ
  ublock-quick-fixes: 216-0, 36m Δ
  ublock-unbreak: 2541-4, 36m Δ
  urlhaus-1: 23275-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2341 ms
 maxAssetCacheWait: 503 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  econodata.com.br: 1
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
```adb
@@||econodata.com.br/_nuxt3/web-vitals$script,1p
econodata.com.br##.ad-container
```

the second filter for `AdGuard Spanish/Portuguese`

@ryanbr 
@Alex-302
