### ISSUE TITLE
1fichier.com again

### ISSUE THREAD

**Issue by Francois-dag** [uBlockOrigin/uAssets#2641]
### URL(s) where the issue occurs

`https://1fichier.com/?6te9680ronk6q1fh7knu&af=2330946`

### Describe the issue

On this page you can see a button "Access to download", when you select it, previously you
would have get a page with a submit button and then the download starts. By now the form
element is bypassed and of course we are button less.

### Versions

- Browser/version: [last firefox and last chrome]
- uBlock Origin version: [1.16.10]

Cheers !

**Comment by mapx-** [comment]
test
`1fichier.com#@#a[style]`

@smed79
