### ISSUE TITLE
freepreset.net: detection

### ISSUE THREAD

**Issue by ComradePoula** [uBlockOrigin/uAssets#26422]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://freepreset.net/`

### Category

detection

### Description

![image](https://github.com/user-attachments/assets/126d81a6-69db-48f0-bf9e-092951f4f76e)

### Other extensions used

![image](https://github.com/user-attachments/assets/3b9b8a57-3fa8-40b4-95a1-ddec4b228430)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/7b7e31ab-0dd9-479c-9c69-cfa07d972342)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 141529
 cosmetic: 49389
 scriptlet: 21512
 html: 2221
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41247-134, 48m Δ
  ublock-badware: 12362-1, 48m Δ
  ublock-privacy: 1621-22, 48m Δ
  ublock-unbreak: 2599-1, 48m Δ
  ublock-quick-fixes: 222-6, 48m Δ
  easylist: 78076-604, 48m Δ
  easyprivacy: 53302-683, 48m Δ
  urlhaus-1: 23275-0, 48m
  plowe-0: 3541-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 440 ms (selfie)
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  doubleclick.net: 3
  googletagmanager.com: 1
  pubfuture-ad.com: 2
  stpd.cloud: 2
  thisiswaldo.com: 1
  vlitag.com: 2
 extended:
  ##+js(prevent-fetch, googlesyndication)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/bb6e3e6f4ccf31a8e1d24fe81b576f95cedec598
