### ISSUE TITLE
hulu.com: ads

### ISSUE THREAD

**Issue by Luft87** [uBlockOrigin/uAssets#26427]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.hulu.com/watch/451bd0c3-073f-4e66-9268-4fb834fde001`

### Category

ads

### Description

Does not filter ads on HBO content on hulu but does for other shows.

### Other extensions used

Google Translate
Video Download Helper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 141500
 cosmetic: 49792
 scriptlet: 23309
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40953-142, 32m Δ
  ublock-badware: 12360-1, 32m Δ
  ublock-privacy: 1635-22, 32m Δ
  ublock-unbreak: 2541-0, 32m Δ
  ublock-quick-fixes: 220-0, 32m Δ
  easylist: 78484-626, 32m Δ
  easyprivacy: 53299-738, 32m Δ
  urlhaus-1: 23240-0, now
  plowe-0: 3541-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 243 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 188
 network:
  hulu.com: 188
 extended:
  ##+js(set-constant, Object.prototype._parseVAST, noopFunc)
  ##+js(set-constant, Object.prototype.createAdBlocker, noopFunc)
  ##+js(set-constant, Object.prototype.isAdPeriod, falseFunc)
  ##+js(json-prune-fetch-response, breaks pause_ads video_metadata…
  ##+js(json-prune, breaks pause_ads video_metadata.end_credits_ti…
  ##+js(xml-prune, `xpath(//*[name()="MPD"]/@mediaPresentationDura…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.

> - [X] I did not answer truthfully to **ALL** the above checkboxes.

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+hulu.com

We can't investigate without the accounts. If you are willing to share account credentials, I will give you email to contact.

**Comment by chkbm** [comment]
I'm having the same issue:

uBlock Origin: 1.61.2
Chromium: 132
filterset (summary):
 network: 141712
 cosmetic: 49783
 scriptlet: 23263
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 78525-424, 21m Δ
  easyprivacy: 53301-741, 21m Δ
  plowe-0: 3542-0, 9d.7h.38m
  ublock-badware: 12406-20, 21m Δ
  ublock-filters: 40918-289, 21m Δ
  ublock-privacy: 1648-22, 21m Δ
  ublock-quick-fixes: 201-1, 21m Δ
  ublock-unbreak: 2541-32, 21m Δ
  urlhaus-1: 23345-0, 21m
filterset (user): [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 318 ms
 maxAssetCacheWait: 68 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  hulu.com: 5
  sc-static.net: 1
  yimg.com: 1
 extended:
  ##+js(set-constant, Object.prototype._parseVAST, noopFunc)
  ##+js(set-constant, Object.prototype.createAdBlocker, noopFunc)
  ##+js(set-constant, Object.prototype.isAdPeriod, falseFunc)
  ##+js(json-prune-fetch-response, breaks pause_ads video_metadata…
  ##+js(json-prune, breaks pause_ads video_metadata.end_credits_ti…
  ##+js(xml-prune, `xpath(//*[name()="MPD"]/@mediaPresentationDura…

**Comment by stephenhawk8054** [comment]
@chkbm 

> https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+hulu.com

> We can't investigate without the accounts. If you are willing to share account credentials, I will give you email to contact.

Don't comment here.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/22825
