### ISSUE TITLE
elamigosedition.com: detection

### ISSUE THREAD

**Issue by bonyjose** [uBlockOrigin/uAssets#26428]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://elamigosedition.com/1978-cyberpunk-2077-free-download-01.html`

### Category

detection

### Description

![image](https://github.com/user-attachments/assets/7cfa1dea-8656-48e8-9398-68eb2894f9cf)

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 141495
 cosmetic: 49799
 scriptlet: 21513
 html: 2223
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 41252-134, now Δ
  ublock-badware: 12362-1, now Δ
  ublock-privacy: 1621-22, now Δ
  ublock-unbreak: 2599-1, now Δ
  ublock-quick-fixes: 223-6, now Δ
  easylist: 78484-225, now Δ
  easyprivacy: 53299-70, now Δ
  urlhaus-1: 23240-0, now
  plowe-0: 3541-992, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 618 ms (selfie)
 maxAssetCacheWait: 239 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  cloudflareinsights.com: 2
  doubleclick.net: 2
  google.com: 4
  googletagmanager.com: 1
  youtube.com: 7
 extended:
  ##.ad_box
  ###boxads
  ###sponsorAd1
  ###topadvert
  ###topleaderAd
  ##+js(abort-on-stack-trace, document.addEventListener, blocker)
  ##+js(prevent-window-open)
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.web_bind_fetch, …
  ##+js(trusted-prevent-dom-bypass, Node.prototype.appendChild, fe…
```
</details>

**Comment by stephenhawk8054** [comment]
I can reproduce

**Comment by waterfluoridation** [comment]
@stephenhawk8054 
![image](https://github.com/user-attachments/assets/5e26d0f8-5f16-4548-980e-0a47f894fe2d)
