### ISSUE TITLE
video player showing no controls or progress bar

### ISSUE THREAD

**Issue by xejogot** [uBlockOrigin/uAssets#2642]
### URL(s) where the issue occurs

All videos on site, this is one example
`http://www.ondemandkorea.com/kbs-news-9-e20180622.html`

### Describe the issue

Video controls are gone (no pause/play, volume, fullscreen buttons at all, and no progress bar)

### Screenshot(s)

n/a, seems pretty self explanatory

### Versions

- Browser/version: Chrome, most recent
- uBlock Origin version: 1.16.10

### Settings

- Don't have any custom filters or anything like that, but filters that are checked are: all 7 in built-in category, all 4 in ads category, easyprivacy, all 4 in malware domains category, adguard's annoyance list, fanboy's annoyance list, and peter lowe's ad and tracking server list

### Notes

- I don't know enough at all to tell where the problem may be coming from, but the videos on the site have ads included, so maybe blocking the ads also make the video controls disappear?

**Comment by kowith337** [comment]
I don't know because of recent update of chrome have "New media control" update, can you try disable this flag in `chrome://flags` and then reproduce again?

**Comment by mapx-** [comment]
@ryanbr

**Comment by xejogot** [comment]
@kowith337 Tried both, but doesn't work, unfortunately.

What I tried doing on both Chrome and Firefox is uninstalling and then reinstalling ublock origin (and leaving it on all the default settings, didn't touch anything). I noticed that the yellow triangles (the ones that show that filters need updating) were next to most of the filters, so I'm guessing that these are not up-to-date when you first install ublock? Anyway, the video controls appeared this time, but as soon as I went ahead and updated all the filters, the controls disappeared again. So I guess there's something in the updated filters that's causing this problem?

**Comment by mapx-** [comment]
As you can see I added a filter. Update your lists and test again.

**Comment by xejogot** [comment]
@mapx- Thanks! Updated and tried again, but it seems to be working on and off on Chrome. Doesn't work in incognito mode (but that's okay I guess), but works fine in a regular window. However, if I open a video in incognito mode first and then on a regular window second, it won't work in the regular window either. I end up needing to restart my browser and not use incognito mode.

Works perfectly fine in Firefox though! :)

**Comment by mapx-** [comment]
add also
`@@||production-static.ondemandkorea.com/vendor/js/js.cookie.js$script,domain=ondemandkorea.com`

see if works in chrome too

**Comment by xejogot** [comment]
@mapx- It works! Thank you so much!
Why is everyone so smart here...
