### ISSUE TITLE
ads.tuver.ru: breakage

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#26430]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ads.tuver.ru/`

### Category

breakage

### Description

Multiple mask blocks: `://ads.` **uBlock filters** – Ads, and when it is turned off - **EasyList**

### Other extensions used

other extensions are missing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.3b4
Chromium: 131
filterset (summary):
 network: 166064
 cosmetic: 137897
 scriptlet: 33567
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 23932-48, now
  fanboy-cookiemonster: 51714-407, now
  ublock-annoyances: 5954-12, now
  RUS-1: 1742-15, now
 default:
  user-filters: 3-0, never
  ublock-filters: 40953-146, now
  ublock-badware: 12360-1, now
  ublock-privacy: 1635-22, now
  ublock-unbreak: 2541-4, now
  ublock-quick-fixes: 220-0, now
  easylist: 78077-668, now
  easyprivacy: 53301-1049, now
  urlhaus-1: 23240-0, now
  plowe-0: 3541-0, now
  RUS-0: 41062-223, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 937 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 100
 network:
  tuver.ru: 97
  google.com: 1
  google.ru: 1
  wp.com: 1
 extended:
  ##.ad-type
  ##.et_pb_scroll_top
```
</details>

**Comment by gwarser** [comment]
Looks like service for advertisers?

**Comment by dimisa-RUAdList** [comment]
@ryanbr
For EasyList the problem remains unresolved.

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/64646cb71da3f965678280e964e6e8d3b2a91927
