### ISSUE TITLE
freepreset.net: detection

### ISSUE THREAD

**Issue by ofbakirci** [uBlockOrigin/uAssets#26437]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://freepreset.net/`

### Category

detection

### Description

Website detects uBlock origin is being used. Adding different filters cannot solve the problem. 

### Other extensions used

None while testing for the problem. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1512" alt="Screenshot 2024-12-12 at 19 07 01" src="https://github.com/user-attachments/assets/c9a93a20-04e5-47b0-a08d-e2c141db5738" />

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 151906
 cosmetic: 185511
 scriptlet: 39562
 html: 0
listset (total-discarded, last-updated):
 added:
  TUR-0: 11103-36, never
  adguard-cookies: 32827-89, never
  adguard-mobile-app-banners: 5584-25, never
  adguard-other-annoyances: 14439-403, never
  adguard-popup-overlays: 28175-2199, never
  adguard-widgets: 2804-45, never
  easylist-annoyances: 4727-53, never
  easylist-chat: 216-17, never
  easylist-newsletters: 8329-21, never
  easylist-notifications: 3467-1548, never
  fanboy-cookiemonster: 51715-4090, never
  ublock-annoyances: 5954-48, never
  [2 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 78484-456, 31m Δ
  easyprivacy: 53299-661, 31m Δ
  plowe-0: 3541-0, now
  ublock-badware: 12395-1, 31m Δ
  ublock-filters: 40919-389, 31m Δ
  ublock-privacy: 1637-22, 31m Δ
  ublock-quick-fixes: 201-0, 31m Δ
  ublock-unbreak: 2541-0, 31m Δ
  urlhaus-1: 22895-0, 31m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 632 ms (selfie)
 maxAssetCacheWait: 67 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 3
  googletagmanager.com: 1
  pubfuture-ad.com: 1
  stpd.cloud: 1
  thisiswaldo.com: 1
  vlitag.com: 1
 extended:
  ##.adsbyvli
  ##+js(prevent-fetch, googlesyndication)
```
</details>

**Comment by ofbakirci** [comment]
Thanks for incredible response time. I've updated EasyList and EasyList Annoyances but still having the same problem. I must be doing something wrong or missing something, what should I do?

**Comment by mapx-** [comment]
- the fix has been added in uBO filters list and will be automatically added in your uBO in 5-6 hours
- you can manually update your list using:
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1

**Comment by ofbakirci** [comment]
I sadly need to revive this. 
I've updated all my lists and waited for some time too but still freepreset.net detects my uBO. I am having the same pop up.
