### ISSUE TITLE
sarajevotimes.com: detection

### ISSUE THREAD

**Issue by elsandosgrande** [uBlockOrigin/uAssets#26439]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sarajevotimes.com/`

### Category

detection

### Description

When I try to view a Sarajevo Times article with uBlock Origin enabled, I get an “AdBlock Detected” popup/error and I can't proceed until I disable uBlock Origin — even disabling the Annoyances and Social Widgets filter lists didn't work. I tried deleting some `<div>`s in developer tools, but it seems like the page contents are completely removed upon detection.

Interestingly enough, it seems like Firefox's Enhanced Tracking Protection alone is able to block the ads, but it leaves empty space where the ads would otherwise be. 

### Other extensions used

I'm not sure how this is relevant when I can reproduce the issue with all but uBlock Origin disabled, but here goes:
* Augmented Steam
* Bitwarden Password Manager
* Bypass Paywalls Clean
* enhanced-h264ify
* Enhancer for YouTube™
* Facebook Container
* Firefox Multi-Account Containers
* Flagfox
* Indie Wiki Buddy
* LocalCDN
* Native MathML
* Plasma Integration
* Return YouTube Dislike
* Ruffle - Flash Emulator
* Side View
* Tab Session Manager
* Tab Unloader
* Tabliss
* To Google Translate
* User-Agent Switcher
* Wappalyzer - Technology Profiler
* Yomitan

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock Origin disabled: 
![image](https://github.com/user-attachments/assets/29b45fc0-399a-4585-868c-525ea1b4b21e)

uBlock Origin enabled: 
![image](https://github.com/user-attachments/assets/6d862676-c5e7-4ed1-af84-49c3ba74c449)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 352104
 cosmetic: 320615
 scriptlet: 53138
 html: 2680
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85976-4239, 28m
  adguard-mobile: 10007-60, 28m
  adguard-spyware-url: 1816-131, 28m
  adguard-spyware: 116531-1570, 28m
  block-lan: 64-0, 28m
  curben-phishing: 532-2, 28m
  adguard-social: 23254-50, 28m
  fanboy-social: 16540-757, 28m
  fanboy-thirdparty_social: 68-18, 28m
  adguard-popup-overlays: 28179-2135, 28m
  adguard-mobile-app-banners: 5584-34, 28m
  adguard-other-annoyances: 14439-412, 28m
  [44 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41227-134, 28m
  ublock-badware: 12402-1, 28m
  ublock-privacy: 1623-22, 28m
  ublock-unbreak: 2599-1, 28m
  ublock-quick-fixes: 211-16, 28m
  easylist: 78515-2295, 28m
  easyprivacy: 53300-29844, 28m
  urlhaus-1: 22895-0, 28m
  plowe-0: 3545-1491, 28m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 679 ms (selfie)
 maxAssetCacheWait: 335 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  sarajevotimes.com: 4
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##.header-social-list
  ##.ad-wrap:not(#google_ads_iframe_checktag)
  ##ins.adsbygoogle[data-ad-slot]
  ##ins.adsbygoogle[data-ad-client]
  ##.adsbygoogle
  ##.sb-social-counter
  ###back-top
```
</details>

**Comment by mapx-** [comment]
>  [44 lists not shown]: [too many]

You enabled all the filter lists
The greek list has some wrong filters => report at their repository or use ONLY the necessary / default lists

**Comment by elsandosgrande** [comment]
Looks like disabling the Greek filter lists resolves it, thank you. Now I just need to find said repository.

**Comment by elsandosgrande** [comment]
One more thing: “I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.” refers to enabling filter lists beyond the enabled-by-default ones, right? I thought it just referred to adding and enabling lists which aren't included with uBlock Origin to begin with 😅

**Comment by mapx-** [comment]
Greek list repo https://github.com/kargig/greek-adblockplus-filter/issues
