### ISSUE TITLE
bs.cimanow.cc: detection

### ISSUE THREAD

**Issue by shenawy36** [uBlockOrigin/uAssets#26444]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://bs.cimanow.cc/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b1%d9%82%d9%85-%d8%b3%d8%b1%d9%8a-%d8%a7%d9%84%d8%ad%d9%84%d9%82%d8%a9-5-%d8%a7%d9%84%d8%ae%d8%a7%d9%85%d8%b3%d8%a9/watching/`

### Category

detection

### Description

Detected ubo "please disable your AdBlock to continue"

Main page : "bs.cimanow.cc/home"

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-12-13 063217](https://github.com/user-attachments/assets/586fc27a-b103-415d-aa00-211be8dcca1c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 88955
 cosmetic: 51778
 scriptlet: 23377
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
  easyprivacy: null

 default:
  user-filters: 5586-1227, never
  ublock-badware: 12400-1, 1h.39m Δ
  ublock-privacy: 1639-22, 1h.39m Δ
  ublock-unbreak: 2541-1, 1h.39m Δ
  ublock-quick-fixes: 206-9, 1h.39m Δ
  easylist: 78518-591, 1h.39m Δ
  urlhaus-1: 23105-0, now
  plowe-0: 3550-0, now
filterset (user): [array of 1250 redacted]
trustedset:
 added: [array of 25 redacted]
 removed:
  chrome-extension-scheme
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 31785 ms (selfie)
 maxAssetCacheWait: 10503 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  cimanow.cc: 1
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ##+js(abort-on-property-read, navigator.brave)
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a8bbf651dbf803894e8143f839454885b1c5d120
