### ISSUE TITLE
123moviestv.net: detection

### ISSUE THREAD

**Issue by FranzQSR** [uBlockOrigin/uAssets#26445]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://123moviestv.net/`

### Category

detection

### Description

The website detects the adblocker which prevents users from accessing the site.

### Other extensions used

Dark Reader
Debug CSS
Free Download Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/1b062195-a714-413d-9a62-615bc18c85a0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 141473
 cosmetic: 35572
 scriptlet: 23268
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 78518-14047, now
  easyprivacy: 53301-663, now
  plowe-0: 3550-379, now
  ublock-badware: 12405-31, now
  ublock-filters: 40931-593, now
  ublock-privacy: 1648-25, now
  ublock-quick-fixes: 207-1, now
  ublock-unbreak: 2541-13, now
  urlhaus-1: 23105-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 637 ms (selfie)
 maxAssetCacheWait: 270 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  google.com: 1
  parklogic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The domain is parked.
