### ISSUE TITLE
duolingo.com: detection

### ISSUE THREAD

**Issue by TheOneQGuy** [uBlockOrigin/uAssets#26458]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.duolingo.com/`

### Category

detection

### Description

Detects adblocker on the main page and after lessons. I can block the one on the main page using the Element picker, but I can't remove the one after lessons using element picker properly (there will be space as if the adblocker detection message is there)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Main page:
![image](https://github.com/user-attachments/assets/3bc382aa-4f6a-4364-9235-1c7185a69a4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 141713
 cosmetic: 49783
 scriptlet: 23265
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40926-151, 1h.58m Δ
  ublock-badware: 12405-1, 1h.58m Δ
  ublock-privacy: 1648-22, 1h.58m Δ
  ublock-unbreak: 2541-1, 1h.58m Δ
  ublock-quick-fixes: 210-0, 1h.58m Δ
  easylist: 78517-626, 1h.58m Δ
  easyprivacy: 53301-738, 1h.58m Δ
  urlhaus-1: 23345-0, 15m
  plowe-0: 3549-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 590 ms (selfie)
 maxAssetCacheWait: 205 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 28
 network:
  duolingo.com: 1
  googlesyndication.com: 1
  sentry.io: 26
 extended:
  ##+js(prevent-xhr, excess.duolingo.com/batch)
```
</details>

**Comment by mapx-** [comment]
annoyance => enable this list: `uBlock filters – Annoyances`

**Comment by TheOneQGuy** [comment]
@mapx- still doesn't remove where the ad/detector would be at the end of lessons
![image](https://github.com/user-attachments/assets/87dd5b8e-6559-4759-8995-114bdbae4d9c)

**Comment by mapx-** [comment]
I cannot reproduce it, reset uBO to defaults, test again

**Comment by TheOneQGuy** [comment]
@mapx- reset to defaults and turned on annoyances, still the space shows up (It only sometimes shows up)
