### ISSUE TITLE
dziennik.pl: [unknown]

### ISSUE THREAD

**Issue by noahkim123** [uBlockOrigin/uAssets#26451]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.dziennik.pl/`

### Category

[unknown]

### Description

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/58484b07-313d-4c4a-89d8-567e28e8d3b8" />

### Other extensions used

Only uBO.

<img width="320" alt="image" src="https://github.com/user-attachments/assets/1cdd302a-213e-4fc3-821a-9e6738628673" />

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/1b7d7470-b300-4715-943b-eeb2fe9b2d0a" />
<img width="325" alt="image" src="https://github.com/user-attachments/assets/313170d4-ecbb-4914-a227-5a1ab47301f4" />

<img width="551" alt="image" src="https://github.com/user-attachments/assets/ae357eed-210d-418f-9087-f75034208dd6" />

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 142958
 cosmetic: 58046
 scriptlet: 23477
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 8774-44, never
  POL-2: 1280-48, never
 default:
  user-filters: 0-0, never
  easylist: 78518-478, 9m Δ
  easyprivacy: 53300-620, 9m Δ
  plowe-0: 3550-0, 10m
  ublock-badware: 12405-1, 10m
  ublock-filters: 40931-400, 10m
  ublock-privacy: 1648-22, 9m Δ
  ublock-quick-fixes: 207-0, 10m
  ublock-unbreak: 2541-19, 10m
  urlhaus-1: 23105-0, 10m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 458 ms
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  error-report.com: 1
  gemius.pl: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  html-load.com: 5
  imasdk.googleapis.com: 2
  ocdn.eu: 3
  onnetwork.tv: 14
  qwtag.com: 1
 extended:
  ##.textAds
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(no-setTimeout-if, error-report.com)
  ##+js(remove-node-text, script, error-report.com)
  ##+js(remove-node-text, script, .slice(-2);return decodeURICompo…
  ##+js(abort-on-property-write, ub_ct_load)
  #@#+js(abort-current-script, parseInt, adblock)
```
</details>

**Comment by stephenhawk8054** [comment]
Already fixed here: https://github.com/uBlockOrigin/uAssets/commit/b929d0ba809e603386331a70dec18e242bdaf245

**Comment by stephenhawk8054** [comment]
There's a redirect filter for it.

**Comment by stephenhawk8054** [comment]
cc @Yuki2718
