### ISSUE TITLE
tportal.hr: detection

### ISSUE THREAD

**Issue by loman7560** [uBlockOrigin/uAssets#26450]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tportal.hr/`

### Category

[unknown]

### Description

issue in basic filter.

### Other extensions used

Nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="477" alt="image" src="https://github.com/user-attachments/assets/a82c2c35-f64a-45f6-b529-81ed91d5b11d" />

<img width="525" alt="image" src="https://github.com/user-attachments/assets/d1b09466-a7cc-4077-a65e-dbd8b9efab2f" />

</details>

### Configuration

```yaml
version: uBOL 2024.12.10.932
mode: basic / basic
rulesets:
 default
 urlhaus.full
 kor-1
```

**Comment by stephenhawk8054** [comment]
Then why did you tick on this:

> - [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
