### ISSUE TITLE
spox.com: breakage

### ISSUE THREAD

**Issue by VascoDuckGama** [uBlockOrigin/uAssets#26468]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.spox.com/mehrsport/listen/die-neuen-apps-neue-kommentarfunktion-und-technische-aenderungen-was-sich-bei-spox-aendert/`

### Category

breakage

### Description

This German sport news side "hides" their comment section between thousand adds. It's either 'filter all ads and also the comment section' or 'disable adblock to see the comment section but have to live with 1.000 ads' :-(

Can you please fix that? 

### Other extensions used

None. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 133
filterset (summary):
 network: 155612
 cosmetic: 228081
 scriptlet: 36400
 html: 2503
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32840-50, 2m
  ublock-cookies-adguard: 2017-23, 2m
  fanboy-cookiemonster: 51599-4053, 1h.9m
  ublock-cookies-easylist: 2017-2017, 2m
  adguard-social: 23261-46, 2m
  fanboy-social: 16541-758, 2m
  fanboy-thirdparty_social: 68-18, 2m
  adguard-popup-overlays: 28197-2142, 2m
  adguard-mobile-app-banners: 5587-41, 2m
  adguard-other-annoyances: 14418-377, 2m
  adguard-widgets: 2805-20, 2m
  easylist-annoyances: 4729-331, 2m
  [4 lists not shown]: [too many]
 default:
  user-filters: 70-3, never
  ublock-filters: 41679-217, 1h.9m Δ
  ublock-badware: 12403-2, 1h.9m Δ
  ublock-privacy: 1641-22, 1h.9m Δ
  ublock-unbreak: 2603-3, 1h.9m Δ
  ublock-quick-fixes: 207-6, 1h.9m Δ
  adguard-mobile: 10013-12, 2m
  easylist: 78532-298, 1h.9m Δ
  easyprivacy: 53302-79, 1h.9m Δ
  urlhaus-1: 22920-0, 2m
  plowe-0: 3549-1067, 2m
  DEU-0: 7826-61, 1h.9m
filterset (user): [array of 70 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1616 ms (selfie)
 maxAssetCacheWait: 145 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  spox.com: 2
 extended:
  ##.ad-wrapper
  ###ad-leaderboard
  ##.fco-hide-on-desktop.fco-ad-wrapper
  ##.fco-fc-video-player
  ##.fco-openweb-ad__slot
  ##.fco-openweb-ad__header
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by JobcenterTycoon** [comment]
@khrin i see a bunch of placeholder

**Comment by mapx-** [comment]
@VascoDuckGama 

- disable all your custom filters (in "my filters")
- test again

for placeholders

```adb
spox.com##.fco-ad-wrapper
spox.com##.fco-openweb-ad
```

**Comment by mapx-** [comment]
@VascoDuckGama report directly here for the placeholders
https://github.com/easylist/easylistgermany/issues

**Comment by Khrin** [comment]
> https://www.spox.com/mehrsport/listen/die-neuen-apps-neue-kommentarfunktion-und-technische-aenderungen-was-sich-bei-spox-aendert/

https://github.com/easylist/easylistgermany/commit/45fa4666873d2b75bab1406f1dadeea8b40c5abe

**Comment by Khrin** [comment]
> @Khrin i see a bunch of placeholder (EL germany)

https://github.com/easylist/easylistgermany/commit/45fa4666873d2b75bab1406f1dadeea8b40c5abe

**Comment by VascoDuckGama** [comment]
Hi there, the EL Germany guys checked it also and are sure it's not caused by them.
As you mentioned, I disabled my custom filters but it still didn't work.

Only of I disable uBlock Origins completely. It must be a filter list then, right?!
But which one?

**Comment by VascoDuckGama** [comment]
Hi there, that worked! But in a weird way:

after resetting uBlock Origins to default settings and not enabling any filter lists, it worked.

After enabling EL Germany, it still worked.
So I enabled all filters again. Afterwards, the comment section was gone again.

I was suspecting the Social Widget filters - but that wasn't it.
Only after disabling the two Cookie Notices filter lists (Easy List and AdGuard), it worked again.

I can't explain it to myself but I'm happy it finally works again.

Thanks for your help
