### ISSUE TITLE
rwnews.tw: ads

### ISSUE THREAD

**Issue by jameslee0623** [uBlockOrigin/uAssets#26462]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://rwnews.tw/article.php?news=18503`

### Category

ads

### Description

Add a line should be able to remove these ads.
`rwnews.tw###ArticleAsideAD`

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/9adcc0fa-17c8-4e76-aa42-7f0fcfaa813d" />

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 283680
 cosmetic: 254370
 scriptlet: 55457
 html: 2501
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/gijsdev/ublock-hide-yt-shorts/master/list.txt: 25-0, now
  adguard-generic: 86003-538, now
  adguard-mobile: 10013-60, now
  adguard-spyware-url: 1816-131, now
  adguard-spyware: 116530-1570, now
  block-lan: 64-0, now
  curben-phishing: 515-1, now
  adguard-cookies: 32840-64, now
  ublock-cookies-adguard: 1979-21, now
  fanboy-cookiemonster: 51619-4049, now
  ublock-cookies-easylist: 1979-1979, now
  fanboy-social: 16541-14, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  ublock-filters: 41220-3619, 17m Δ
  ublock-badware: 12409-127, 17m Δ
  ublock-privacy: 1634-22, 17m Δ
  ublock-unbreak: 2599-77, 17m Δ
  ublock-quick-fixes: 204-20, 17m Δ
  easylist: 78531-2295, 17m Δ
  easyprivacy: 53301-29844, 17m Δ
  urlhaus-1: 22850-0, now
  plowe-0: 3549-1492, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1812 ms
 maxAssetCacheWait: 532 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  rwnews.tw: 1
  cloudflareinsights.com: 2
  facebook.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##.fb-share-button
  ##.fb-xfbml-parse-ignore
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you check this?

**Comment by cjx82630** [comment]
Those are self-promotion
