### ISSUE TITLE
odiadance.com: detection

### ISSUE THREAD

**Issue by superislam** [uBlockOrigin/uAssets#26476]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://odiadance.com/`

### Category

detection

### Description

detection

### Other extensions used

IDM

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/e738dd2d-dc65-4f75-920a-ff25d08f3092)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 145078
 cosmetic: 66742
 scriptlet: 25593
 html: 2501
listset (total-discarded, last-updated):
 added:
  block-lan: 64-0, now
  ublock-annoyances: 5890-33, now
  ara-0: 2330-15, now
  easylist-annoyances: 4730-50, now
  easylist-chat: 216-0, now
  easylist-newsletters: 8344-41, now
  easylist-notifications: 3464-163, now
 default:
  user-filters: 8-0, never
  ublock-filters: 41170-134, now
  ublock-badware: 12466-1, now
  ublock-privacy: 1640-22, now
  ublock-unbreak: 2600-1, now
  ublock-quick-fixes: 201-9, now
  easylist: 78570-225, now
  easyprivacy: 53308-73, now
  urlhaus-1: 23270-0, now
  plowe-0: 3549-992, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 36 redacted]
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-csp-reports: * true
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2298 ms (selfie)
 maxAssetCacheWait: 662 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ###ast-scroll-top
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by D4niloMR** [comment]
As already said many times, comment on https://github.com/uBlockOrigin/uAssets/discussions/17361 and provide the link that made you get on `https://odiadance.com/`
