### ISSUE TITLE
forum.infinityfree.com: breakage

### ISSUE THREAD

**Issue by Grendel7** [uBlockOrigin/uAssets#26477]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://forum.infinityfree.com/`

### Category

breakage

### Description

With uBlock Origin active, the entire forum just doesn't load. Only the background color is shown on all pages.

The browser console shows errors like these:

```
Uncaught Error: Could not find module `./quz` imported from `foo/bar`
    h loader.js:247
    h loader.js:258
    findDeps loader.js:168
    h loader.js:262
    findDeps loader.js:168
    h loader.js:262
    requireModule loader.js:24
    <anonymous> loader.js:328
    <anonymous> vendor.6f1929e16c84d825f1e134b0a5a6bf6d-ed21b08557694a2386531fb8b5bd479da7fe4ec9cffd9278c49f382c5e7bc3a4.br.js:1
[loader.js:247](https://forum-cdn.infinityfree.net/rewritten-packages/@embroider/synthesized-vendor/vendor/loader/loader.js)

None of the “sha512” hashes in the integrity attribute match the content of the subresource. The computed hash is “z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==”.

Uncaught Error: Could not find module `I18n` imported from `discourse/plugins/discourse-docs/discourse/initializers/setup-docs`
    h loader.js:247
    h loader.js:258
    findDeps loader.js:168
    h loader.js:262
    requireModule loader.js:24
    k app.js:170
    x app.js:193
    start app.js:156
    start app.js:50
    <anonymous> start-app.js:5
    <anonymous> discourse-boot.js:13
    <anonymous> discourse-boot.js:1

Uncaught (in promise) TypeError: WeakMap key null must be an object
    Ember 52
    <anonymous> start-app.js:4
    <anonymous> discourse-boot.js:13
    <anonymous> discourse-boot.js:1
```

This seems to be caused by some rules in the "uBlock filters – Quick fixes" list. With this list disabled, the forum works.

There appear to be specific rules configured for infinityfree.com to circumvent Ad Shield, which is present on the main site but not the forum.

https://github.com/uBlockOrigin/uAssets/blob/28cc18bb02521152281917d8d05c9583eff3bab9/filters/quick-fixes.txt#L185

### Other extensions used

N/A

When I disabled the Quick Fixes list in my uBlock Origin installation, the issue was resolved.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 256320
 cosmetic: 187361
 scriptlet: 47654
 html: 2502
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2700-0, now
  adguard-generic: 86007-4233, now
  adguard-spyware-url: 1816-249, now
  adguard-spyware: 116533-1555, now
  adguard-social: 23261-49, now
  fanboy-social: 16541-756, now
  fanboy-thirdparty_social: 68-18, now
  adguard-popup-overlays: 28197-2133, now
  adguard-mobile-app-banners: 5595-33, now
  adguard-other-annoyances: 14427-418, now
  adguard-widgets: 2805-21, now
  easylist-annoyances: 4730-356, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41176-134, now
  ublock-badware: 12466-1, now
  ublock-privacy: 1640-71, now
  ublock-unbreak: 2600-1, now
  ublock-quick-fixes: 209-6, 1h.29m
  easylist: 78570-2231, now
  easyprivacy: 53308-29840, now
  urlhaus-1: 23270-0, now
  plowe-0: 3549-1090, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2018 ms
 maxAssetCacheWait: 1018 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  infinityfree.net: 1
 extended:
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(trusted-replace-argument, String.prototype.split, 0, json:…
```
</details>

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054
