### ISSUE TITLE
wallpapercat.com: nuisance

### ISSUE THREAD

**Issue by AndroidMaster24** [uBlockOrigin/uAssets#26478]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wallpapercat.com/the-goblet-of-fire-wallpapers`

### Category

nuisance

### Description

There is 10 sec waiting time when downloading a wallpaper. Would be nice if it can be skipped

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/012ea70c-69e6-4b9b-857b-1e0ddb848e3d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 130
filterset (summary):
 network: 144126
 cosmetic: 52173
 scriptlet: 23309
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40932-141, now
  ublock-badware: 12464-1, now
  ublock-privacy: 1638-22, now
  ublock-unbreak: 2542-1, now
  ublock-quick-fixes: 207-0, now
  easylist: 78532-628, now
  easyprivacy: 53303-739, now
  urlhaus-1: 23270-0, now
  plowe-0: 3549-0, now
  NOR-0: 4850-5, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1638 ms
 maxAssetCacheWait: 4 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  yadro.ru: 1
  yandex.ru: 1
 extended:
  ###ads1
  ##.adsblock
  ##ins.adsbygoogle[data-ad-client]
  ##ins.adsbygoogle[data-ad-slot]
  ###ads2
  ###ads3
```
</details>

**Comment by D4niloMR** [comment]
Added to  uBlock filters – Annoyances list.
