### ISSUE TITLE
ageetsaimouphih.net: popups

### ISSUE THREAD

**Issue by SenryKaz09** [uBlockOrigin/uAssets#26481]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://ageetsaimouphih.net/`

### Category

popups

### Description

Keeps popping up on multiple websites and stops me from doing anything and then sends me to some random websites 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 130
filterset (summary):
 network: 270318
 cosmetic: 220036
 scriptlet: 55163
 html: 2501
listset (total-discarded, last-updated):
 added:
  https://ageetsaimouphih.net: 0-0, never
  adguard-generic: 86007-6683, never
  adguard-mobile: 10014-213, never
  adguard-spyware-url: 1816-131, never
  adguard-spyware: 116533-31397, never
  block-lan: 64-2, never
  curben-phishing: 582-3, never
  adguard-cookies: 32840-4201, never
  ublock-cookies-adguard: 1979-1979, never
  fanboy-cookiemonster: 51580-17018, never
  ublock-cookies-easylist: 1979-0, never
  adguard-social: 23261-1674, never
  [12 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 41177-330, 10m
  ublock-badware: 12466-12, 10m
  ublock-privacy: 1640-23, 10m
  ublock-unbreak: 2600-2, 10m
  ublock-quick-fixes: 197-9, 6m Δ
  easylist: 78571-14228, 10m
  easyprivacy: 53309-73, 6m Δ
  urlhaus-1: 23310-0, 10m
  plowe-0: 3549-992, 10m
filterset (user): [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 529 ms (selfie)
 maxAssetCacheWait: 146 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
- scan your system with antivirus / anti-malware software: use this one https://www.malwarebytes.com/adwcleaner
- reset uBO to defaults, do not touch any setting, then test again
