### ISSUE TITLE
midilibre.fr: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#26485]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.midilibre.fr/2024/12/11/video-un-nourrisson-etait-a-linterieur-une-maison-de-perpignan-visee-a-larme-lourde-une-balle-finit-dans-le-canape-12384549.php`

### Category

breakage

### Description

Video not visible

### Other extensions used

None that interfere with uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/38de28d2-cc0f-4cc7-a6a9-fb7ada87473a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 128
filterset (summary):
 network: 179108
 cosmetic: 77421
 scriptlet: 23685
 html: 2242
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1050-2, now
  RUS-0: 41085-268, now
 default:
  user-filters: 7-0, never
  ublock-filters: 41183-134, 53m Δ
  ublock-badware: 12466-1, 53m Δ
  ublock-privacy: 1640-22, now
  ublock-unbreak: 2600-1, 53m Δ
  ublock-quick-fixes: 197-9, 53m Δ
  easylist: 78571-225, now
  easyprivacy: 53312-73, now
  urlhaus-1: 23310-0, now
  plowe-0: 3549-992, now
  FRA-0: 25851-399, now
filterset (user): [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 165 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  on.aws: 1
 extended:
  ###pub_dfp_banniere_basse
  ###pub_dfp_banniere_haute
  ##.ad--banniere_haute
  ###ultimedia_wrapper
  ###pub_dfp_droite_haute
  ##.ad--droite_haute
  ##.ad--droite_middle
  ##.ad--droite_basse
  ##.ad--banniere_basse
  ##.ad--outstream
  ###pub_dfp_article
  ##.ad--article
  ###taboola-below-article-thumbnails
  ###immobilier
  ##div[data-iab-tag]
  ##+js(remove-attr, style|data-state, div.p402_premium)
```
</details>

**Comment by mapx-** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=midilibre.fr
```

**Comment by mapx-** [comment]
all fine on my end using default uBO + french list

**Comment by stephenhawk8054** [comment]
Video plays fine on my side too.

**Comment by mapx-** [comment]
no issue on my end
