### ISSUE TITLE
[nsfw] xvideos.com: breakage

### ISSUE THREAD

**Issue by Ziko577** [uBlockOrigin/uAssets#26495]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.xvideos.com/video.hlookuke35e/little_horny_asian_aicha_gets_anal_sex
```

### Description

The sidebar ad isn't being blocked anymore like it usually would be which makes watching anything impossible without constantly clicking to hide it. 

### Other extensions used

N/A

### Screenshot(s)

[NSFW](https://drive.google.com/file/d/153RI1G-g8jgI3Kek5R2Iq2aOdLfHCH-k/view?usp=sharing)

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 109
filterset (summary):
 network: 142179
 cosmetic: 82
 scriptlet: 27279
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/Sorrow-San/9anime-adblock-filters/raw/master/9Anime%20filter%20list: 148-60, 16h.37m
  ublock-annoyances: 5956-1671, now Δ
 default:
  user-filters: 114-3, never
  ublock-filters: 40892-11488, now Δ
  ublock-badware: 12464-702, now Δ
  ublock-privacy: 1654-39, now Δ
  ublock-unbreak: 2544-342, now Δ
  ublock-quick-fixes: 194-43, now Δ
  easylist: 78603-37559, now Δ
  easyprivacy: 53315-150, now Δ
  urlhaus-1: 23310-0, 16h.37m
  plowe-0: 3540-994, 7d.17h.1m
filterset (user): [array of 114 redacted]
trustedset:
 added: [array of 45 redacted]
switchRuleset:
 added: [array of 7 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 contextMenuEnabled: false
 ignoreGenericCosmeticFilters: true
 parseAllABPHideFilters: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16053 ms
 maxAssetCacheWait: 3589 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by Ziko577** [comment]
I can confirm the issue wasn't resolved when doing that under Brave Browser
and I shut the shields off for good measure.

**Comment by stephenhawk8054** [comment]
It's self-promotion. You can use this as your custom filter:

```adb
xvideos.com###video-right ~ div:has(.live_model_thumb)
```

---

Also

> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.

https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+%22xvideos.com%22
