### ISSUE TITLE
wite.ru: breakage

### ISSUE THREAD

**Issue by CRAZY41** [uBlockOrigin/uAssets#26498]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.wite.ru/komputeri-i-noutbuki/komplektuyuwie/processory/intel/core-i5-12400f-alder-lake-2-5-ghz-lga1700-18432-kb/oem/
```

### Description

Button "Купить" is not working, when uBlock activated
It redirects to cart (checkout) without adding item. If filter disabled - all work. 

### Other extensions used

nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/727aa276-67ef-47b8-af16-4edb917a16a3)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.61.2
Firefox: 132
filterset (summary):
 network: 162179
 cosmetic: 70521
 scriptlet: 22970
 html: 2248
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41197-144, 29m Δ
  ublock-badware: 12467-1, 29m Δ
  ublock-privacy: 1650-22, 29m Δ
  ublock-unbreak: 2602-0, 29m Δ
  ublock-quick-fixes: 199-0, 29m Δ
  easylist: 78611-227, 29m Δ
  easyprivacy: 53315-71, 29m Δ
  urlhaus-1: 25000-0, 2h.29m
  plowe-0: 3542-992, 12d.1m
  RUS-0: 41093-152, 4h.29m Δ
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2160 ms
 maxAssetCacheWait: 822 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 9
 network:
  artfut.com: 1
  begun.ru: 1
  google-analytics.com: 1
  googletagmanager.com: 3
  vk.com: 1
  yandex.ru: 2
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This issue is best discussed here: https://github.com/easylist/ruadlist/issues
