### ISSUE TITLE
titulky.com: detection

### ISSUE THREAD

**Issue by impnet** [uBlockOrigin/uAssets#26493]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.titulky.com/What-We-Do-in-the-Shadows-S01E01-337808.htm`

### Category

detection

### Description

On site is HTML element `<a class="tlacitko titulkydownloadajax"  href="idown.php?R=1734372064&titulky=337808&zip=z&histstamp=" id="opendown" onclick="//OpenDownload('39990','z',''); return false;" >What We Do in the Shadows S01E01</a>`. When i enter to site, this element are replaced with `div` contain information about "blocked ads".
Replaced DIV looks like this `<div class="adbdown" onclick="showADowninfo()">zablokovaná reklama</div>`

### Other extensions used

Lighthouse
Return youtube dislike
Youtube Nonstop
ESET Browser search extension
Enchacer for Youtube

### Screenshot(s)

![ublock OFF](https://github.com/user-attachments/assets/0b84e61f-956e-4125-bae2-2690a6ba41a7)
![ublock ON](https://github.com/user-attachments/assets/f569ab92-5906-4c54-85d8-f25a40d0909d)

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 143216
 cosmetic: 50215
 scriptlet: 21620
 html: 2230
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41193-134, now
  ublock-badware: 12466-1, now
  ublock-privacy: 1640-22, now
  ublock-unbreak: 2602-1, now
  ublock-quick-fixes: 197-9, now
  easylist: 78603-227, now
  easyprivacy: 53315-71, now
  urlhaus-1: 24480-0, now
  plowe-0: 3549-992, now
  CZE-0: 849-12, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 137 ms (selfie)
 maxAssetCacheWait: 45 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  titulky.com: 5
  adform.net: 3
  adobedtm.com: 2
  aimatch.com: 2
  gemius.pl: 1
  google.com: 2
  googletagmanager.com: 1
  seznam.cz: 3
  youtube-nocookie.com: 1
 extended:
  ##[id^="sklikReklama"]
  ###ContentAd
  ##+js(remove-attr, style, div[id^="head"])
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.[-].__bbox.r…
  ##+js(json-prune, require.0.3.0.__bbox.require.[].3.1.__bbox.res…
  ##+js(json-prune-xhr-response, data.viewer.instream_video_ads da…
  ##+js(trusted-replace-node-text, script, '/null,"category_sensit…
```
</details>

**Comment by impnet** [comment]
Thank you. I added filter from 5015a0a to "custom filters" and it works. :-)

**Comment by bt4ibwem8** [comment]
@stephenhawk8054 
It is broken again
