### ISSUE TITLE
hackernoon.com: ads

### ISSUE THREAD

**Issue by yassin193** [uBlockOrigin/uAssets#26492]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://hackernoon.com/c-performance-optimization-best-practices`

### Category

ads

### Description

simply, there is an ad that is shown and i can't remove it unless i sign up or something

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://ibb.co/yBPz4K0

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox Mobile: 133
filterset (summary):
 network: 164523
 cosmetic: 65879
 scriptlet: 21722
 html: 2231
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41710-135, 1m
  ublock-badware: 12460-1, 1m
  ublock-privacy: 1641-22, 1m
  ublock-unbreak: 2603-1, 1m
  ublock-quick-fixes: 197-9, 1m
  adguard-mobile: 10015-97, 1m
  easylist: 78571-298, 1m
  easyprivacy: 53312-80, 1m
  urlhaus-1: 24480-0, 1m
  plowe-0: 3549-1066, 1m
  ara-0: 2330-16, 1m
  FRA-0: 25851-405, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 21156 ms
 maxAssetCacheWait: 88 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  cloudflareinsights.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 2
 extended:
  ##.ad-tag
  ##ins.adsbygoogle[data-ad-client]
  ##a[href^="https://ad.doubleclick.net/"]
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 EL filter suggestion:

```
||hackernoon.com/images/ad-assets/
||hackernoon.imgix.net/images/ad-assets/
||hackernoon.imgix.net/images/write-ad
hackernoon.com##div[style*="ad-assets"]
hackernoon.com##.dabytag
hackernoon.com##.articles-wrapper > div:has(> div > div > .text > strong > a[href^="https://ad.doubleclick.net/"])
```

**Comment by Yuki2718** [comment]
> ```

> hackernoon.com##div[style*="ad-assets"]
> ```

Isn't this a self-promo?
