### ISSUE TITLE
popups and popunders on arenabg

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#265]
Firefox 50.1.0 Windows
uBlock origin 1.10.4
All filters are up-to-date

Pages:
http://arenabg.com/
http://arenabg.com/torrents/

Just click some links or anywhere in page. There are many popunders slips through without being blocked. Especially one that starts with viralture.com

**Comment by SMed79** [comment]
I cannot reproduce. No popups / popunders.

**Comment by toshiya44** [comment]
You didn't mention which filter lists you have.

**Comment by Hrxn** [comment]
No popups / popunders for me either.

**Comment by ahmedtds** [comment]
I just clicked a few pages and that opened as a popunder without blocked: http://30daychange.biz/
But these addresses are varying, that's just the last one I see now.

My filters are default ones. So they are:
- uBlock filters‎
- uBlock filters – Badware risks‎
- uBlock filters – Privacy‎
- uBlock filters – Unbreak‎
- EasyList‎
- EasyPrivacy‎
- Malware Domain List‎
- Malware domains‎
- Peter Lowe’s Ad and tracking server list‎

**Comment by toshiya44** [comment]
The default filter lists are okay, but you should really consider subscribing to a few more.
Try adding the following filters. (these two were found in `Dan Pollock’s hosts file`‎ and `MVPS HOSTS‎` filter lists)
```
||grabo.bg$important
||d31qbv1cthcecs.cloudfront.net^
```

**Comment by SMed79** [comment]
> Do you still get popups?

`d31qbv1cthcecs.cloudfront.net` > already blocked by `/atrk.js` (EasyPrivacy‎)
`grabo.bg` > blocked by  `||grabo.bg^$third-party` (EasyList)

For the iframe (non related to the popups) add:
`||webcafe.bg^$subdocument,third-party`

**Comment by toshiya44** [comment]
welp, i was only checking the logger and it shows filters that are the most specific.
So, between `b.grabo.bg` and `grabo.bg`, logger will show the former. That's why I saw different items n the logger than you @SMed79 

Also, popups only occurs when `||pdn-1.com` is not blocked, but the filter to block it already exists in Easylist. Just to be sure that it isn't getting cancelled, add `||pdn-1.com$important` to your filters.

**Comment by uBlock-user** [comment]
Block all third party content and that should kill any existing popups for you, add exceptions for css, images and youtube related content.

**Comment by SMed79** [comment]
@ahmedtds Use [The logger](https://github.com/gorhill/uBlock/wiki/The-logger), uploade a screenshots at **imgur.com** then post here the links... so that someone can help you.

@toshiya44 Thank you.

**Comment by IDKwhattoputhere** [comment]
Yes, the logger is most likely to give an answer here. Easier than uploading to Imgur is [this](https://help.github.com/assets/images/help/pull_requests/dragging_images.gif).
Just to be clear, @toshiya44: It's not only the logger displaying that filter but AFAIK it's also the filter that uBO used to filter the network request. So uBO will not apply any other filters if the request was already blocked to save resources.

**Comment by kasper93** [comment]
Only not blocked popups I can see are when clicking on "Download" button. To block add this redirect url filter.
```
||xml.pdn-1.com/redirect^$document,popunder,popup
```
Other things that you might want to get blocked. 
```
||profitshare.bg$third-party
||cdn.arenabg.com/share/jscripts/analytics.js
```

**Comment by ahmedtds** [comment]
Here's a log when a popunder passed: http://i.imgur.com/3aAmC76.png
so maybe jscripts/analytics.js causes these popups?

I think I don't get them anymore after applied kasper93's filters. Look fine for now.

**Comment by SMed79** [comment]
@ahmedtds Could you please try:

`@@||arenabg.ch/share/jscripts/adframe.js$script,domain=arenabg.ch`

**Comment by ahmedtds** [comment]
@SMed79 

I removed other filters and only added these:
```
@@||arenabg.ch/share/jscripts/adframe.js$script,domain=arenabg.ch
@@||arenabg.com/share/jscripts/adframe.js$script,domain=arenabg.com
```
and popups started to show up again especially viralture one. So I deleted these and added following filters which I compiled from suggestions in this thread and no popup or popunder appears anymore:
```
||xml.pdn-1.com/redirect^$document,popunder,popup
||profitshare.bg$third-party
||cdn.arenabg.com/share/jscripts/analytics.js
||webcafe.bg^$subdocument,third-party
```
I'm not sure which filter prevents but I feel like it might be analytics.js

**Comment by SMed79** [comment]
Ok, more generic add:
```
://xml.*/click$popup,popunder
://xml.*/redirect$popup,popunder
```
Because maybe they use a revolving adservers e.g http://pastebin.com/raw/SYXFY8RG
