### ISSUE TITLE
channel4.com video-ads and anti-adblock

### ISSUE THREAD

**Issue by ZaphodBeebblebrox** [uBlockOrigin/uAssets#2651]
### URL(s) where the issue occurs

`http://www.channel4.com/programmes/formula-1/on-demand`
Requires UK IP (or at least not us)

### Describe the issue

Anti-adblock, cannot figure out how to beat it without allowing video ads

### Settings

- Default settings

### Notes

```
@@||webstat.channel4.com/b/*$object,domain=channel4.com
@@||v.fwmrm.net/ad/$object,domain=channel4.com
@@||cdn.http.anno.channel4.com^*.mp4$object,domain=channel4.com
@@||mssl.fwmrm.net^$object,domain=channel4.com
```
This gets past the anti-adblock, but it allows multiple minute video ads. I do not know how to deal with flash based ads.

**Comment by jspenguin2017** [comment]
This is a known issue for a long time: https://github.com/jspenguin2017/uBlockProtector/issues/712

I don't really know how to inspect Flash ActionScript, and since Flash will reach end of life in 2020, I'm not too worried.

**Comment by mapx-** [comment]
A guy on easylist forum said he decompiled swf player

https://pastebin.com/raw/T8RM7JtM
https://pastebin.com/raw/wTfVaMjf

https://forums.lanik.us/viewtopic.php?p=131243#p131243

**Comment by jspenguin2017** [comment]
Hum, that is pretty difficult to get around...

**Comment by zaphodbeebblebrox** [comment]
Should we just whitelist the ads until another solution is found?

**Comment by mapx-** [comment]
Sure, the main issue is the anti adb crap.

**Comment by jspenguin2017** [comment]
Isn't the anti-adblock just a short timer? Or they changed it to a hard anti-adblock?

**Comment by zaphodbeebblebrox** [comment]
Its a short timer, but it will repeat indefinably as long as the video ads are blocked.

**Comment by okiehsch** [comment]
The anti-adblock message is **the** main issue, but the video ads are obviously also a big issue.
If there is a working fix that solves both, that would obviously be preferable.

**Comment by AndnixSH** [comment]
I found a video that uses HTML5
https://www.channel4.com/programmes/ramsays-24-hours-to-hell-and-back/on-demand/68319-006

Blocking ads works fine
If video player breaks, add this filter

@@||2a7e9.v.fwmrm.net/ad/$script,domain=channel4.com
