### ISSUE TITLE
bing.com: ads

### ISSUE THREAD

**Issue by eEfiuys** [uBlockOrigin/uAssets#26513]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.bing.com/search?pglt=2465&q=vscode&cvid=e8aacd8c295f4d4988a060fc6d7c6747&gs_lcrp=EgRlZGdlKgYIABBFGDsyBggAEEUYO9IBCDEwODFqMGoxqAIAsAIA&FORM=ANNTA1&PC=NMTS&mkt=zh-CN`

### Category

ads

### Description

Ads are shown on bing.com with uBlockOrigin active.

### Other extensions used

Tempermonkey(with no 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 157740
 cosmetic: 60687
 scriptlet: 23562
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40830-270, 57m Δ
  ublock-badware: 12521-1, 58m
  ublock-privacy: 1666-23, 58m
  ublock-unbreak: 2545-0, 59m
  ublock-quick-fixes: 191-0, 59m
  easylist: 78598-656, 56m Δ
  easyprivacy: 53316-640, 57m Δ
  urlhaus-1: 24690-0, 59m
  plowe-0: 3549-0, 59m
  CHN-0: 25877-59, 59m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 495 ms
 maxAssetCacheWait: 109 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 23
 network:
  bing.com: 23
 extended:
  ##li.b_algo:has(> :is(.b_tpcn, .b_title, h2) a[href^="https://ww…
  ##.b_ad:style(position: absolute !important; top: -9999px !impor…
  #@#.b_ad
  #@#a[href*="/aclick?ld="]
  ##+js(href-sanitizer, a[href^="/rebates/welcome?url=http"], ?url…
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
  ##+js(trusted-replace-argument, HTMLLIElement.prototype.querySel…
  ##+js(trusted-override-element-method, HTMLDivElement.prototype.…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.

https://github.com/uBlockOrigin/uAssets/issues/25344
