### ISSUE TITLE
faceitanalyser.com: ads

### ISSUE THREAD

**Issue by dayz2015** [uBlockOrigin/uAssets#26510]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://faceitanalyser.com/`

### Category

ads

### Description

It shows a gambling advertisement on top of the website
||faceitanalyser.com/static/stats/i/sponsors/clash_christmas.png

### Other extensions used

NoScript (website on)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 161705
 cosmetic: 56423
 scriptlet: 21655
 html: 2230
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41130-134, now
  ublock-badware: 12518-1, never
  ublock-privacy: 1652-23, never
  ublock-unbreak: 2603-1, never
  ublock-quick-fixes: 194-23, now
  easylist: 78613-227, now
  easyprivacy: 53316-71, now
  urlhaus-1: 24690-0, now
  plowe-0: 3549-992, now
  FRA-0: 25851-399, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1194 ms
 maxAssetCacheWait: 41 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by dayz2015** [comment]
> `||faceitanalyser.com/static/stats/i/sponsors/`
> 
> @ryanbr

oh so i must report to easylist, my bad reading quickly through the requirements... :)

**Comment by dayz2015** [comment]
> @dayz2015 I have pinged him now about this on Slack

Cheers, how can I report further websites?.

**Comment by stephenhawk8054** [comment]
You can report to here: https://github.com/easylist/easylist/issues
