### ISSUE TITLE
filecrypt.cc [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2652]
URL(s) where the issue occurs

`https://filecrypt.cc/Container/D353C522D8.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by KiLL4FuNK** [comment]
continue Captcha

**Comment by mapx-** [comment]
I get no anti adb stuff (only ads + popups)

try
```
filecrypt.cc##script:inject(abort-current-inline-script.js, popsThisDay, under)
filecrypt.cc##script:inject(set-constant.js, isAdblock, false)
filecrypt.cc##.support
filecrypt.cc##.buttons
filecrypt.cc##[src^="https://filecrypt.cc/images/"]
```

**Comment by KiLL4FuNK** [comment]
the filters do not work
![](https://i.imgur.com/zduaRhp.png)

**Comment by vicokoby** [comment]
This issue can currently be reproduced with this link: https://filecrypt.co/Container/D353C522D8.html

**Comment by stephenhawk8054** [comment]
It shows even when I don't use any extensions:

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/fa879b44-a03a-4b01-8e40-0c594222c833)

It's because their captcha domain/link `https://v2.cutcaptcha.net/captcha/SAs61IAI.js` has certificate error.

**Comment by stephenhawk8054** [comment]
Caused by

```adb
*$script,third-party,domain=filecrypt.cc
```

in "Liste FR"

cc @smed79 

---

@x-R0b0T-x Please report to https://github.com/easylist/listefr/issues
