### ISSUE TITLE
blu-ray.com: breakage

### ISSUE THREAD

**Issue by Jacob-Tate** [uBlockOrigin/uAssets#26539]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.blu-ray.com/deals/?sortby=popularity&category=2kbluray`

### Category

breakage

### Description

Cant use filters

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/87c9bbcc-b3ce-4127-9fe7-36d6d48fe858)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 142616
 cosmetic: 49811
 scriptlet: 21354
 html: 2230
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41018-131, now
  ublock-badware: 12529-1, now
  ublock-privacy: 1662-23, now
  ublock-unbreak: 2603-1, now
  ublock-quick-fixes: 180-9, now
  easylist: 77870-248, now
  easyprivacy: 53328-72, now
  urlhaus-1: 24890-0, now
  plowe-0: 3549-991, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2313 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 1
  intergient.com: 3
 extended:
  ##+js(prevent-window-open)
```
</details>

**Comment by krystian3w** [comment]
Something is blocking him/her from refreshing the page, apparently (It refreshes for me and I see anime category).

**Comment by Jacob-Tate** [comment]
I appears to be working now sorry about the confusion I tested pretty thoroughly wonder what was going on.
