### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Gobbochune** [uBlockOrigin/uAssets#26545]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=daM3rEdFd4Q`

### Category

detection

### Description

This IS a youtube detection problem, but the guide that exists for youtube issues is outdated. The guide references buttons that no longer seem to exist, so I'm not sure how I am supposed to fix it on my end. 

Youtube is detecting the adblocker, but I am confused what does or doesn't constitute a 'duplicate' report. I have no option to purge caches myself like it says on the advice for the youtube issues. I can't figure out how to fix this myself as none of the buttons on any of the guides seem to exist anymore, and the help buttons only lead me back to here. 

### Other extensions used

Simple translate
Cookie AutoDelete
Express VPN
Xkit

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 255179
 cosmetic: 156909
 scriptlet: 47320
 html: 2505
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 85687-4233, 10m
  adguard-mobile: 10029-62, 10m
  adguard-spyware-url: 1850-135, 10m
  adguard-spyware: 116582-1597, 10m
  block-lan: 64-0, 10m
  curben-phishing: 530-0, 9m
  adguard-popup-overlays: 28119-58, 9m
  adguard-mobile-app-banners: 5601-31, 9m
  adguard-other-annoyances: 14422-300, 9m
  adguard-widgets: 2811-19, 9m
  easylist-annoyances: 4732-350, 9m
  easylist-chat: 216-18, 9m
  [3 lists not shown]: [too many]
 default:
  ublock-filters: 41014-197, 39m Δ
  ublock-badware: 12530-1, 39m Δ
  ublock-privacy: 1662-23, 39m Δ
  ublock-unbreak: 2603-2, 39m Δ
  ublock-quick-fixes: 179-8, 39m Δ
  easylist: 78083-2477, 39m Δ
  easyprivacy: 53328-30917, 39m Δ
  urlhaus-1: 24920-0, 13m
  plowe-0: 3548-1164, 13m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 423 ms (selfie)
 maxAssetCacheWait: 172 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 30
 network:
  youtube.com: 17
  csp.withgoogle.com: 2
  doubleclick.net: 3
  google.com: 8
 extended:
  ##.ytp-featured-product
  ###masthead-ad
  ###player-ads
  ##.ytd-merch-shelf-renderer
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> #content > ytd-ad-slot-renderer)
  ###ticker.ytd-masthead
  ##.video-annotations
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##ytd-rich-grid-renderer ytd-rich-item-renderer div > ytd-displa…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-prevent-dom-bypass, Node.prototype.appendChild, fe…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by ElainaxMariex** [comment]
I'm having the same problem
