### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by DamienMarie** [uBlockOrigin/uAssets#26559]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

3 videos block. uBlock detected.

### Other extensions used

SponsorBlock

Tried deactivating it, doesn't change anything.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 162048
 cosmetic: 164863
 scriptlet: 29105
 html: 2230
listset (total-discarded, last-updated):
 added:
  adguard-social: 23273-43, 14m
  fanboy-thirdparty_social: 68-3, 14m
  fanboy-cookiemonster: 51647-201, 14m
  fanboy-social: 16505-771, 14m
  adguard-cookies: 32835-3905, 14m
  ublock-cookies-adguard: 1985-25, 14m
  ublock-cookies-easylist: 1985-1985, 14m
 default:
  user-filters: 38-2, never
  ublock-filters: 41014-131, 9m
  ublock-badware: 12530-1, 14m
  ublock-privacy: 1662-23, 14m
  ublock-unbreak: 2603-1, 14m Δ
  ublock-quick-fixes: 179-8, 14m
  easylist: 78083-252, 14m
  easyprivacy: 53328-73, 14m Δ
  urlhaus-1: 24920-0, 14m
  plowe-0: 3548-994, 14m
  FRA-0: 21056-363, 13m
filterset (user): [array of 38 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1122 ms
 maxAssetCacheWait: 579 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  youtube.com: 5
  doubleclick.net: 1
  google.com: 2
 extended:
  ##.ytp-featured-product
  ###masthead-ad
  ###player-ads
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ###offer-module
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(adjust-setTimeout, resolve(1), *, 0.001)
  ##+js(set-constant, yt.config_.openPopupConfig.supportedPopups.a…
  ##+js(ensemble, Object.prototype.adBlocksFound, 0)
  ##+js(ensemble, ytplayer.config.args.raw_player_response.adPlace…
  ##+js(set-constant, Object.prototype.hasAllowedInstreamAd, true)
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-prevent-dom-bypass, Node.prototype.appendChild, fe…
  ##+js(trusted-click-element, ytd-button-renderer.ytd-consent-bum…
```
</details>

**Comment by TheSkyDog203** [comment]
I had the same problem. If you use Firefox pls delete your browser data (cookies, ...). after this it works on my device
