### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by geilocd** [uBlockOrigin/uAssets#26560]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.youtube.com/watch?v=JI4kVJJxEkE`

### Category

detection

### Description

Typical Youtube blocking videos. Couldnt watch any other issue reports, dont get to the right website, when clicking named button. sorry

### Other extensions used

I used deepl translate. All others are deactivaded on Youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 155662
 cosmetic: 219276
 scriptlet: 38284
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32835-96, 4m
  adguard-mobile-app-banners: 5600-1126, 4m
  adguard-other-annoyances: 14421-343, 4m
  adguard-popup-overlays: 28114-1247, 3m
  adguard-social: 23273-1577, 3m
  adguard-widgets: 2811-20, 4m
  easylist-annoyances: 4729-134, 6d.13h.26m
  easylist-chat: 216-0, 6d.3h.26m
  easylist-newsletters: 8342-29, 6d.13h.26m
  easylist-notifications: 3467-3, 6d.13h.26m
  fanboy-cookiemonster: 51509-4090, 3d.5h.2m
  fanboy-social: 16506-69, 1d.1h.28m
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  DEU-0: 7829-0, 1h.43m
  easylist: 78083-579, 1h.43m Δ
  easyprivacy: 53328-1594, 1h.44m Δ
  plowe-0: 3545-1, 8d.4h.8m
  ublock-badware: 12528-1, 1h.44m Δ
  ublock-filters: 40716-693, 1h.43m Δ
  ublock-privacy: 1676-23, 1h.44m Δ
  ublock-quick-fixes: 176-0, 1h.44m Δ
  ublock-unbreak: 2545-24, 1h.44m Δ
  urlhaus-1: 24920-0, 1h.43m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 221 ms (selfie)
 maxAssetCacheWait: 102 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 26
 network:
  youtube.com: 15
  doubleclick.net: 3
  google.co.jp: 1
  google.com: 7
 extended:
  ##.ytp-featured-product
  ###ticker.ytd-masthead
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ###masthead-ad
  ###player-ads
  ##.ytd-merch-shelf-renderer
  ##.ytp-suggested-action > button.ytp-suggested-action-badge
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> #content > ytd-ad-slot-renderer)
  ##+js(trusted-replace-node-text, script, (function serverContrac…
  ##+js(adjust-setTimeout, [native code], 17000, 0.001)
  ##+js(json-prune-fetch-response, playerAds adPlacements adSlots …
  ##+js(json-prune-xhr-response, playerAds adPlacements adSlots pl…
  ##+js(trusted-replace-xhr-response, '/"adPlacements.*?([A-Z]"\}|…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-prevent-dom-bypass, Node.prototype.appendChild, fe…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(trusted-click-element, ytd-button-renderer.ytd-consent-bum…
  ##+js(trusted-replace-fetch-response, '/"adPlacements.*?([A-Z]"\…
  ##+js(trusted-replace-fetch-response, '/"adSlots.*?\}\}\],"adBre…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
```
</details>

**Comment by TheSkyDog203** [comment]
I had the same problem. If you use Firefox pls delete your browser data (cookies, ...). after this it works on my device
