### ISSUE TITLE
youtube restrictions and ineffective blocker on twitch

### ISSUE THREAD

**Issue by Phil995511** [uBlockOrigin/uAssets#26575]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello,

Since 20.12.2024 youtube detects uBlockOrigin and limits the viewing of videos to 3 per 24 hours. Could you prevent this ?

This is a nice Christmas present they are giving us there... It made me start to stop using the google search engine and their various other tools :) They want to make me pay to watch youtube... by doing this I will make them lose income.

The other problem I am having is related to twitch, it is impossible to all publicity, even with all available block lists selected.

Best regards and happy end of year holidays

### A specific URL where the issue occurs.

```yaml
https://www.youtube.com

https://www.twitch.tv/
```

### Steps to Reproduce

Log in with your youtube account, play more than 3 video.

### Expected behavior

To be able to continue to read a video

### Actual behavior

Impossible to continue to read more video

### uBO version

1.61.2

### Browser name and version

Firefox

### Operating System and version

Debian 12

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.

**Comment by Phil995511** [comment]
> Youtube is already fixed, force update uBlock Quick Fixes list.
> 
> For twitch, I have firefox specific filters if you want to test.

Thank you, I will be very happy if you share this list with me.
