### ISSUE TITLE
winfreebigwindeal.top: badware

### ISSUE THREAD

**Issue by webhunted** [uBlockOrigin/uAssets#26570]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.winfreebigwindeal.top/1ifjjd7qt/l?btd=dHJrLmNvbG9ueS1zY29yZS1yZWxhdGVkLWRvbmtleS5ydW4&exptoken=MTczNDc1MTAxMjYwOQ%3D%3D&lang=en&lid=bc424d50-1e42-426e-9130-7446cf6fc5fd&ltd=dHJrLmxlYWQtd2hpbGUtc3ltYm9sLWF0LnJ1bg&pd2q=YTE9YmM0MjRkNTAtMWU0Mi00MjZlLTkxMzAtNzQ0NmNmNmZjNWZkJmEyPTE2NzUyZGExLTlmNDQtNGY0Ni1iYzhlLWYzYWFjMmFiYmVjNCZhMz0yNzM3Ng&r_countrycode=US&r_ip=71.163.165.91&r_lang=en&r_okeyword=wm%24750&td=dHJrLmhhcHB5LWNvcnJlY3RseS1idXktaHVudC5ydW4vc253ZGFydGY&lvc=02ed5ca0`

### Category

badware

### Description

Scam site needs to be added to blocked list

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/ffefa9ff-e45b-44bf-913a-a9dcfcd3907e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 142719
 cosmetic: 49812
 scriptlet: 21348
 html: 2231
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41014-131, now
  ublock-badware: 12530-1, now
  ublock-privacy: 1662-23, now
  ublock-unbreak: 2603-1, now
  ublock-quick-fixes: 180-8, now
  easylist: 78125-252, now
  easyprivacy: 53328-73, now
  urlhaus-1: 24745-0, now
  plowe-0: 3548-994, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 126 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by JobcenterTycoon** [comment]
The redirect is already blocked.

From where do you got this? When you got this as a popup from a website we could fx the popups.
