### ISSUE TITLE
flamecomics.xyz: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#26586]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://flamecomics.xyz/`

### Category

ads

### Description

Adversing is showing, the picture blocked (not showing), but the advertising remains. 
The 3rd party that is delivering the advertising is zoeacaring.com.
My suggestion: ||mg.zoeacaring.com^ $domain=flamecomics.xyz

### Other extensions used

non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2024-12-22 193800](https://github.com/user-attachments/assets/56788be1-2b5f-4200-9376-d9984bd9d635)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 155504
 cosmetic: 219337
 scriptlet: 38519
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32835-100, now
  ublock-cookies-adguard: 1988-0, now
  fanboy-cookiemonster: 51597-4095, now
  ublock-cookies-easylist: 1988-1988, now
  adguard-social: 23273-790, now
  fanboy-social: 16529-2, now
  adguard-popup-overlays: 28114-2857, now
  adguard-mobile-app-banners: 5600-1126, now
  adguard-other-annoyances: 14422-533, now
  adguard-widgets: 2812-21, now
  easylist-annoyances: 4733-137, now
  easylist-chat: 216-0, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 40864-516, 1m Δ
  ublock-badware: 12548-1, 1m Δ
  ublock-privacy: 1684-23, 1m Δ
  ublock-unbreak: 2545-0, 1m Δ
  ublock-quick-fixes: 175-0, 1m Δ
  easylist: 78226-752, 1m Δ
  easyprivacy: 53330-759, 1m Δ
  urlhaus-1: 24645-0, now
  plowe-0: 3548-0, now
  DEU-0: 7829-5, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 541 ms (selfie)
 maxAssetCacheWait: 152 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  23.109.170.98: 1
  adskeeper.com: 2
  bidgear.com: 1
  captorbaryton.com: 1
  cloudflareinsights.com: 1
  crueltysugar.shop: 4
  googlesyndication.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 

The ad script is `https://mg.zoeacaring.com/t4OPzvaa0T1zp/113482?t=g-ads-1000-1251766560511` CNAME of `bealafulup.com`

**Comment by Yuki2718** [comment]
We have to adjust the regex.
