### ISSUE TITLE
genius.com: ads

### ISSUE THREAD

**Issue by ExtRIELICi** [uBlockOrigin/uAssets#26589]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://genius.com/Kendrick-lamar-not-like-us-lyrics
```

### Description

There are empty ad boxes on this website. Screenshots attached below.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="511" alt="image" src="https://github.com/user-attachments/assets/592d04ed-446f-4e66-9fb2-1a7ddf39b6f5" />
<img width="935" alt="image" src="https://github.com/user-attachments/assets/3136eedc-1507-480b-8f99-ac14df7a3d53" />
<img width="1698" alt="image" src="https://github.com/user-attachments/assets/5f5ee34e-cee7-419c-a17e-a6f212a7e28c" />

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by huyszn** [comment]
```adb
genius.com##div[class^="LeaderboardOrMarquee-"]
genius.com##div[class^="InreadContainer-"]
genius.com##div[class^="SectionLeaderboard-"]
```
@ryanbr

**Comment by nqlp** [comment]
Ad leftovers are back:

https://github.com/user-attachments/assets/b481dd2c-9cee-4a80-97d0-63b74df2f309" />

https://github.com/user-attachments/assets/2a1bba95-0fba-4288-a63e-f8ed6c6a62d4" />

https://github.com/user-attachments/assets/e4f3b2a6-81e9-4505-9191-5188897c974d" />

**Comment by solomoncyj** [comment]
ads are removed on sign in. is it possible to emulate that state (execpt for the sign in button)

**Comment by stephenhawk8054** [comment]
Please describe the steps to reproduce in details with screenshots.

**Comment by solomoncyj** [comment]
iirc the site got a revamp so old filters need to be re-done.

go to a song page, eg 

    https://genius.com/Katseye-pinky-up-lyrics

ensure you are logged out (they remove ads if you are logged in)

scroll for a bit

ad placce hoders appear that disappears after a bit

https://github.com/user-attachments/assets/5e15673e-cb3b-4839-ac70-c4239cacbfac

https://github.com/user-attachments/assets/a3b6fcbd-4d3d-4fd6-af66-1ce6e4a4efbf

**Comment by solomoncyj** [comment]
they also remove some page elements, maybe to allocate  ads, eg in their homepage. similar like the above ad place holders, the content  gets added back in after a bit

### loged in

https://github.com/user-attachments/assets/b799b533-570c-45f1-9729-ad5f7e0fdf61

### not logged in

https://github.com/user-attachments/assets/31fd79d1-e65b-4a82-9d3d-75c91432f60a

**Comment by BlazeFTL** [comment]
@ryanbr
```
genius.com##[class^="SectionLeaderboard__Container-sc-"]:has([id^="div-gpt-ad-"])
