### ISSUE TITLE
[nsfw] 2dfan.com: ads

### ISSUE THREAD

**Issue by niuxianggong** [uBlockOrigin/uAssets#26583]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://2dfan.com/`

### Category

ads

### Description

Unable to block ads

### Other extensions used

Privacy Badger
Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 142529
 cosmetic: 49820
 scriptlet: 21486
 html: 2235
listset (total-discarded, last-updated):
 default:
  user-filters: 6-2, never
  ublock-filters: 41161-134, 25m Δ
  ublock-badware: 12550-1, 25m Δ
  ublock-privacy: 1670-23, 25m Δ
  ublock-unbreak: 2603-1, 25m Δ
  ublock-quick-fixes: 175-5, 25m Δ
  easylist: 78184-253, 25m Δ
  easyprivacy: 53330-72, 25m Δ
  urlhaus-1: 24470-0, 17m
  plowe-0: 3548-994, 17m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 859 ms
 maxAssetCacheWait: 409 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  achost.top: 2
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
2dfan.com##+js(acs, $, scroll_ad)
2dfan.com###adv-fixed-square
2dfan.com##.adv-couplets
2dfan.com##.banner
2dfan.com##img[src^="https://img.achost.top/uploads/ads/"]
||img.achost.top/uploads/ads/$image
```

@Yuki2718 For AG Japanese?

**Comment by Yuki2718** [comment]
No, this is a Chinese site and I don't see ads with Chinese filter enabled.
