### ISSUE TITLE
itv.com: detection

### ISSUE THREAD

**Issue by Kevbar3** [uBlockOrigin/uAssets#26581]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.itv.com/watch/the-chase/1a7842/1a7842a1860`

### Category

detection

### Description

i get "Ad blocker detected" pop-up (error code 06-01) when i try to watch anything on itv.
This is not a geo problem as im from the UK, and when i disable ublock origin it works fine but have tons of unskippable ads.
Other browsers all give the same problem.
I'm using the most up to date filter lists but it still detects ad blocker

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 254623
 cosmetic: 185563
 scriptlet: 49341
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85675-7529, now
  adguard-spyware-url: 1850-134, now
  adguard-spyware: 116581-30253, now
  block-lan: 64-0, now
  curben-phishing: 553-0, now
  adguard-social: 23273-796, now
  fanboy-social: 16505-2, now
  adguard-popup-overlays: 28114-2913, now
  adguard-mobile-app-banners: 5600-1126, now
  adguard-other-annoyances: 14422-720, now
  adguard-widgets: 2812-21, now
  easylist-annoyances: 4732-139, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 40724-129, now
  ublock-badware: 12548-1, now
  ublock-privacy: 1681-24, now
  ublock-unbreak: 2545-2, now
  ublock-quick-fixes: 175-7, 1h.31m Δ
  easylist: 78133-737, 1h.31m Δ
  easyprivacy: 53328-847, 1h.31m Δ
  urlhaus-1: 24470-0, now
  plowe-0: 3548-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2374 ms
 maxAssetCacheWait: 1489 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 52
 network:
  itv.com: 7
  amplitude.com: 6
  conviva.com: 6
  googletagmanager.com: 3
  toots-a.akamaihd.net: 30
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##+js(xml-prune, VAST > Ad, , /tserver)
  ##+js(prevent-window-open)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.

https://github.com/uBlockOrigin/uAssets/issues/24517
