### ISSUE TITLE
kvkmodule.4dq.com: badware

### ISSUE THREAD

**Issue by WHH2024** [uBlockOrigin/uAssets#26596]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://kvkmodule.4dq.com/`

### Category

badware

### Description

phising website

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 143943
 cosmetic: 51653
 scriptlet: 21505
 html: 2238
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41168-134, 5m Δ
  ublock-badware: 12555-1, 5m Δ
  ublock-privacy: 1672-23, 5m Δ
  ublock-unbreak: 2605-1, 5m Δ
  easylist: 78316-249, 5m Δ
  easyprivacy: 53330-71, 5m Δ
  urlhaus-1: 25210-0, 5m
  plowe-0: 3548-994, now
  NLD-0: 2438-47, now
  ublock-quick-fixes: 169-10, 5m Δ
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 666 ms (selfie)
 maxAssetCacheWait: 179 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
The site is empty for me

![image](https://github.com/user-attachments/assets/c74ec0c7-65f4-41e8-8da6-0b4170952612)

**Comment by JobcenterTycoon** [comment]
I was able to reproduce.

<details>

<img width="1654" alt="Unbenannt" src="https://github.com/user-attachments/assets/83daed63-e2d4-4fcf-88e7-11f22e8b770a" />

</details>
