### ISSUE TITLE
flycutlink.com: detection

### ISSUE THREAD

**Issue by Utkarshjadon** [uBlockOrigin/uAssets#26597]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://flycutlink.com/ffKPCDw`

### Category

detection

### Description

helppppp it detects you

### Other extensions used

privacy badger.   

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Firefox: 132
filterset (summary):
 network: 148401
 cosmetic: 60356
 scriptlet: 25190
 html: 2513
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5891-33, 27m Δ
  IND-0: 13700-19, 1h.28m
 default:
  user-filters: 4-0, never
  ublock-filters: 41168-134, 27m Δ
  ublock-badware: 12555-1, 1h.28m
  ublock-privacy: 1672-23, 1h.28m
  ublock-unbreak: 2605-1, 27m Δ
  ublock-quick-fixes: 169-5, 27m Δ
  easylist: 78316-253, 1h.28m
  easyprivacy: 53330-72, 27m Δ
  urlhaus-1: 25180-0, 1h.28m
  plowe-0: 3548-994, 27m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 13 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 326 ms (selfie)
 maxAssetCacheWait: 65 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  magsrv.com: 10
  pemsrv.com: 2
 extended:
  ###ad-728-90
  ###ad_halfpage
  ###adzone
```
</details>

**Comment by stephenhawk8054** [comment]
>- [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

Comment here: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by jordansworld** [comment]
hmm website still shows antiadblock

**Comment by huyszn** [comment]
I don't see the anti-adblock.
