### ISSUE TITLE
tutti.ch: ads

### ISSUE THREAD

**Issue by LSmartGlasses** [uBlockOrigin/uAssets#26598]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tutti.ch/`

### Category

ads

### Description

On search result pages, results from ricardo.ch show up, even if "Nur Inserate von tutti.ch" (Only listings from tutti.ch) is checked. These results also do not adhere to sorting by price, or limiting the search to a certain geographical area.

The screenshot shows the search results for the "Musical Instruments" category, with the aforementioned option enabled, sorted by price ascending. Between two results that are free (Gratis) there is a result from Ricardo (marked with the orange text "auf Ricardo", which is not free.

The configuration is with custom filters, but the same occurs without them.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/user-attachments/assets/b4899d35-12cf-4f1b-8e50-54cf6fe97ebc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 145734
 cosmetic: 55284
 scriptlet: 21491
 html: 2241
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 41175-134, 11m Δ
  ublock-badware: 12555-1, 11m Δ
  ublock-privacy: 1672-23, 11m Δ
  ublock-unbreak: 2605-1, 11m Δ
  ublock-quick-fixes: 173-5, 11m Δ
  easylist: 78317-253, 11m Δ
  easyprivacy: 53332-72, 11m Δ
  urlhaus-1: 25210-0, 11m
  plowe-0: 3548-994, now
  DEU-0: 7828-39, 11m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6488 ms
 maxAssetCacheWait: 477 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  ricardostatic.ch: 2
  sentry.io: 2
 extended:
  ##.mui-style-z954cu
  ###adsense-container-bottom
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||tutti.ch/api/v10/externalRecommendations/listingsBySearchToken?*&utmPositionOnScreen=$xhr,1p
```

will block those results, but it will also block when users turn off "Only listings from tutti.ch". Better to add as your custom filter or report the issue to the website themselves.

**Comment by LSmartGlasses** [comment]
> ```
> ||tutti.ch/api/v10/externalRecommendations/listingsBySearchToken?*&utmPositionOnScreen=$xhr,1p
> ```
> 
> will block those results, but it will also block when users turn off "Only listings from tutti.ch". Better to add as your custom filter or report the issue to the website themselves.


Thank you very much for the filter!

it seems to work, although while scrolling there are entries showing up as if still loading which then disappear which makes it look a bit janky but it doesn't bother me much. I feel like it could make sense to classify the non-tutti listings as ads (especially with the toggle switch resetting on every new search), but maybe there are some users that see this as a feature.

**Comment by elosha** [comment]
In meanwhile the situation is worse, because "Nur von Tutti" doesn't exist anymore but is "Tutti & Ricardo"

I would rather suggest to generally block all "external recommendations" (ads)
`||www.tutti.ch/api/*/externalRecommendations*`

I also blocked
`||www.tutti.ch/api/*/placements.json*` (conventional ad placements)
`||www.tutti.ch/api/*/clientmetrics*` (for privacy)
