### ISSUE TITLE
my.diia.gov.ua: breakage

### ISSUE THREAD

**Issue by Mystic-Mirage** [uBlockOrigin/uAssets#26604]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/d63c43eb-5ab0-49dc-8aec-e31bc28f7532), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`http://my.diia.gov.ua/`

### Category

breakage

### Description

Ukrainian Filters seem broken for multiple websites including government and banking

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/user-attachments/assets/5940c915-780a-4b47-a63d-b822b6ffdc47)

### Configuration

```yaml
version: uBOL 2024.12.23.23
mode: complete / complete
rulesets:
 default
 urlhaus.full
 openphish.domains
 ukr-0
```

**Comment by stephenhawk8054** [comment]
@gorhill Not sure if it's caused by this filter?

```adb
diia*.*/$document,domain=~gov.ua|~diiacityunited.org|~fedoriv.com|~spivdiia.com|~spivdiia.org.ua
```

due to `doc` and `domain` in DNR.

**Comment by serhiyguryev** [comment]
As I've already mentioned [here](https://github.com/ukrainianfilters/lists/issues/148), the rules for the above-mentioned sites work without any problems in Google Chrome using uBlock Origin (Manifest V2). Therefore, the problem appears only in the Lite version of the extension.

The patterns for the rules are optimized in terms of excluding situations where the names diia or monobank are used not in the domain name, but in the name of, for example, a website page.

**Comment by stephenhawk8054** [comment]
@serhiyguryev I think it's due to MV3 DNR's understanding of `initiator` when using `document` and `domain` is different to uBO: https://github.com/uBlockOrigin/uBOL-home/issues/156#issuecomment-2256039304

So currently for all the filters that have `document`, you can use `to` instead of `domain`.

**Comment by gorhill** [comment]
The rule being triggered is:

```json
{
  "action": {
    "type": "block"
  },
  "condition": {
    "excludedInitiatorDomains": [
      "diiacityunited.org",
      "fedoriv.com",
      "gov.ua",
      "spivdiia.com",
      "spivdiia.org.ua"
    ],
    "resourceTypes": [
      "main_frame"
    ],
    "urlFilter": "diia*.*/"
  },
  "id": 41,
  "priority": 10
}
```

So it looks like for `document` type, the rule should use `excludedRequestDomains`.

**Comment by serhiyguryev** [comment]
What should this rule look like, so that it can be processed in the Lite version without any problems?

`diia*.*/$document,domain=~gov.ua|~diiacityunited.org|~fedoriv.com|~spivdiia.com|~spivdiia.org.ua` 
=> 
`diia*.*/$document,to=~gov.ua|~diiacityunited.org|~fedoriv.com|~spivdiia.com|~spivdiia.org.ua`

**Comment by stephenhawk8054** [comment]
Yes, it's correct.

**Comment by serhiyguryev** [comment]
Thanks for the advice! Today we will update the rules so that they are processed correctly in the Lite version

**Comment by gorhill** [comment]
Meanwhile until a new version of uBOL is published, the workaround is to toggle the site to no-filtering.
