### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by ZWyldDestroyer** [uBlockOrigin/uAssets#26600]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.twitch.tv/sneegsnag`

### Category

ads

### Description

WHile using uBlockOrigin i am recieving ads while watching a twitch stream.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 271946
 cosmetic: 264419
 scriptlet: 55008
 html: 2516
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85624-4225, 13m
  adguard-mobile: 10030-60, 13m
  adguard-spyware-url: 1862-135, 13m
  adguard-spyware: 116584-1573, 13m
  block-lan: 64-0, now
  curben-phishing: 580-1, 13m
  adguard-cookies: 32841-66, 12m
  ublock-cookies-adguard: 1988-21, 12m
  fanboy-cookiemonster: 51609-4055, 12m
  ublock-cookies-easylist: 1988-1988, 12m
  adguard-social: 23275-52, 12m
  fanboy-social: 16529-760, 12m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 41175-134, 12m
  ublock-badware: 12560-1, 12m
  ublock-privacy: 1672-23, 12m
  ublock-unbreak: 2605-1, 12m
  ublock-quick-fixes: 173-5, 12m
  easylist: 78226-2440, 12m
  easyprivacy: 53330-29696, 12m
  urlhaus-1: 25210-0, 12m
  plowe-0: 3548-1493, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2616 ms
 maxAssetCacheWait: 1660 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  amazon-adsystem.com: 6
  d2v02itv0y9u9t.cloudfront.net: 1
  imrworldwide.com: 1
  scorecardresearch.com: 5
  sprig.com: 5
  ttvnw.net: 2
 extended:
  ##.stream-display-ad__wrapper
  ##button[data-a-target="share-button"]
  ##.social-media-link
  ###twilight-sticky-footer-root
  ##.side-info-container
  ##+js(prevent-window-open, amazon-adsystem)
```
</details>

**Comment by gwarser** [comment]
> This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
