### ISSUE TITLE
inducks.org: breakage

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#26606]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://inducks.org/`

### Category

breakage

### Description

* Enter "Sir Tops" into the `Character` field and press `Enter`
* Press the Firefox `Back` button to go back to the front page

Result with AdGuard Annoyances: the form is reset.
Result without AdGuard Annoyances: the form is filled out with the fields you've changed.

**Open new tabs** after toggling this list.

**I've already tried reporting this to AdGuard, but they said they couldn't reproduce it. I can reproduce it even with clean virtual machines.**

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 146694
 cosmetic: 92221
 scriptlet: 24926
 html: 2140
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 28128-1386, now
  adguard-mobile-app-banners: 5603-30, now
  adguard-other-annoyances: 14429-255, now
  adguard-widgets: 2813-16, now
 default:
  user-filters: 0-0, never
  ublock-filters: 40919-135, never
  ublock-badware: 12561-1, now
  ublock-privacy: 1810-27, now
  ublock-unbreak: 2605-1, 1m
  ublock-quick-fixes: 169-2, 1m
  easylist: 78382-242, 1m
  easyprivacy: 53332-72, 1m
  urlhaus-1: 24985-0, 1m
  plowe-0: 3548-994, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4532 ms
 maxAssetCacheWait: 30 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by gorhill** [comment]
I can reproduce with _AdGuard – Popup Overlays_, looks like it's caused by `/.*/$document,permissions=identity-credentials-get=()`. Not sure why this wouldn't happen with AdGuard.

**Comment by gorhill** [comment]
Even though this doesn't happen with AdGuard, the issue is with the filter in AdGuard, and AdGuard would suffer the same issue if it would apply the filter -- I do not know why they do not apply it, I don't see any directive disabling that filter for Firefox.

**Comment by Alex-302** [comment]
Hm. How uBO changes permissions in FF?

FF does not support them according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy#browser_compatibility
`navigator.permissions` is read only.

**Comment by gorhill** [comment]
We use an `!#if` directive in uBO lists:

![image](https://github.com/user-attachments/assets/32f2cf17-6f37-4565-9fe9-c7f2854f462e)

The day Firefox supports the `Permissions-Policy` header we can start to create filters for it without changing the extension code.

**Comment by Alex-302** [comment]
Ah, got it.
