### ISSUE TITLE
apemc85.fr: ads

### ISSUE THREAD

**Issue by grafuss** [uBlockOrigin/uAssets#26611]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://apemc85.fr/film-en-streaming/40908-Wicked-3qgUM.html`

### Category

ads + fack links

### Description

salut, ce site utilise des fack liens pour inviter les visiteurs à utiliser leur carte bleu

Hi, this site uses fake links to invite visitors to use their credit cards.

### Other extensions used

salut, ce site utilise des fack liens pour inviter les visiteurs à utiliser leur carte bleu

Hi, this site uses fake links to invite visitors to use their credit cards.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 109
filterset (summary):
 network: 141960
 cosmetic: 49824
 scriptlet: 23463
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40900-132, now
  ublock-badware: 12321-1, now
  ublock-privacy: 1808-28, now
  ublock-unbreak: 2547-1, now
  ublock-quick-fixes: 172-7, now
  easylist: 78382-652, now
  easyprivacy: 53357-735, now
  urlhaus-1: 23910-0, now
  plowe-0: 3548-0, now
filterset (user): [empty]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 20046 ms (selfie)
 maxAssetCacheWait: 2818 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  yadro.ru: 1
```
</details>

**Comment by gorhill** [comment]
Please provide a screenshot with the ads and fake links highlighted.

**Comment by grafuss** [comment]
hello

![Capture](https://github.com/user-attachments/assets/4a633f88-893d-4eb8-9a43-87c9310ca277)

**Comment by gorhill** [comment]
The site says you must register to keep watching, and all those buttons navigate to a page to register:

![image](https://github.com/user-attachments/assets/f077fd7f-5afd-4f87-9e2c-e9a1c5fd6efe)

**Comment by smed79** [comment]
> The site says you must register to keep watching

fake/scam streaming site

> might be more familiar with these sites

fake copy of wiflix sites ⮕ `wiflix.name`
