### ISSUE TITLE
[nsfw] letgo.com: badware

### ISSUE THREAD

**Issue by gokhantinmaz** [uBlockOrigin/uAssets#26613]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.letgo.com/chat/user/511615387/1686161536`

### Category

badware

### Description

Phishing

### Other extensions used

Phishing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 143433
 cosmetic: 58281
 scriptlet: 22804
 html: 2246
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41197-134, now
  ublock-badware: 12333-1, now
  ublock-privacy: 1810-27, now
  ublock-unbreak: 2605-1, now
  ublock-quick-fixes: 172-5, now
  easylist: 78392-251, now
  easyprivacy: 53358-71, now
  urlhaus-1: 23910-0, now
  plowe-0: 3548-994, now
  TUR-0: 11101-36, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 167 ms (selfie)
 maxAssetCacheWait: 43 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 4
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
  newrelic.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
What's phishing here? Please describe in more details. Don't just put "Phishing" in the description like that.
