### ISSUE TITLE
tportal.hr: ads

### ISSUE THREAD

**Issue by Marko-98** [uBlockOrigin/uAssets#26619]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.tportal.hr/`

### Category

ads

### Description

Ad placeholder on top of the page

### Other extensions used

Cookie AutoDelete

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/user-attachments/assets/dd773df2-4420-4ced-8934-cf1533a49a90)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 257074
 cosmetic: 256442
 scriptlet: 55110
 html: 2522
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85239-4224, 1h.32m
  adguard-spyware: 117484-1564, 1h.32m
  curben-phishing: 591-0, 1h.32m
  adguard-cookies: 32859-66, 1h.32m
  ublock-cookies-adguard: 1990-21, 1h.32m
  fanboy-cookiemonster: 51605-4055, 1h.32m
  ublock-cookies-easylist: 1990-1990, 1h.32m
  adguard-social: 23278-51, 1h.32m
  fanboy-social: 16530-760, 1h.32m
  fanboy-thirdparty_social: 68-18, 1h.32m
  adguard-popup-overlays: 28134-2153, 1h.32m
  adguard-mobile-app-banners: 5612-33, 1h.32m
  [7 lists not shown]: [too many]
 default:
  user-filters: 19-0, never
  ublock-filters: 41201-134, now
  ublock-badware: 12333-1, now
  ublock-privacy: 1810-27, now
  ublock-unbreak: 2605-1, now
  ublock-quick-fixes: 172-5, now
  easylist: 78439-2258, now
  easyprivacy: 53358-29663, now
  urlhaus-1: 23910-0, 1h.42m
  plowe-0: 3548-1091, 1h.42m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 953 ms
 maxAssetCacheWait: 779 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  criteo.net: 3
  dotmetrics.net: 2
  gemius.pl: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  html-load.com: 3
  newrelic.com: 2
  privacy-center.org: 1
  upscore.com: 3
  wtg-ads.com: 2
 extended:
  ##.positionFrame:has([src*="native.tportal"])
  ##.banner
  ##.footer__newsletter
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, /_fa_bGFzdF9iZmFfYXQ=$/, $remove$)
  ##+js(set-local-storage-item, /_fa_dXVpZA==$/, $remove$)
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWNjZ…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfaXNfYmxvY2tpbmdfYWRz$…
  ##+js(set-local-storage-item, /_fa_Y2FjaGVfYWRibG9ja19jaXJjdW12Z…
  ##+js(remove-class, advertisingActive, div.gpElement.hasSidebarB…
  ##+js(json-prune, options.displayBannerAfterEntry)
  ##+js(set-constant, Object.prototype.displayBannerAfterEntry, {}…
```
</details>

**Comment by stephenhawk8054** [comment]
All volunteers are notified with new comments. We will re-open if we can reproduce the issue.

**Comment by Marko-98** [comment]
New issue on `tportal.hr`. Articles that contain videos have video player hidden until cookies are accepted, which cannot be done due to cookie notice being removed by cookie filter(s).

**URL:** https://www.tportal.hr/sport/clanak/zabio-je-za-dinamovo-vodstvo-pa-poslao-jasnu-poruku-napadac-zivi-od-golova-20250802

**Note:** Site is Croatian and there is a chance videos won't play if visiting from non-Croatian IP addresses.

**Screenshots:**

uBO enabled:

<img width="2559" height="1382" alt="Image" src="https://github.com/user-attachments/assets/721a1141-9447-4c07-8f7f-61c431f5005f" />

uBO disabled:

<img width="2559" height="1388" alt="Image" src="https://github.com/user-attachments/assets/684d6e2d-5879-4ff0-bd94-f1918f6752d6" />

**Comment by stephenhawk8054** [comment]
Continue at the pointed thread: https://github.com/uBlockOrigin/uAssets/issues/25879 . Don't continue here.
