### ISSUE TITLE
bing.com: breakage

### ISSUE THREAD

**Issue by TKINGNAMe** [uBlockOrigin/uAssets#26623]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.) Comment in the old issue threads even when they are closed.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.bing.com/search?
```

### Description

When viewing the bing search engine results, their class="cico siteicon" element is partially blocked

### Other extensions used

![PixPin_2024-12-26_10-21-36](https://github.com/user-attachments/assets/6f29fcfa-ca6a-4bba-88ad-33225a1d4712)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by stephenhawk8054** [comment]
Which search term did you use? What is hidden? Please screenshot it.

**Comment by TKINGNAMe** [comment]
![PixPin_2024-12-26_10-26-23](https://github.com/user-attachments/assets/09729030-910f-49fc-b040-2dd1f1668db0)

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by TKINGNAMe** [comment]
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 177976
 cosmetic: 156343
 scriptlet: 47971
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85243-6354, never
  adguard-mobile: 10043-232, never
  fanboy-cookiemonster: 51603-205, 20m
  ublock-cookies-easylist: 1990-0, 20m
 default:
  user-filters: 0-0, never
  ublock-filters: 40904-141, 3h.11m Δ
  ublock-badware: 12331-1, 3h.11m Δ
  ublock-privacy: 1824-27, 3h.11m Δ
  ublock-unbreak: 2547-0, 3h.11m Δ
  ublock-quick-fixes: 172-0, 3h.11m Δ
  easylist: 78439-676, 3h.11m Δ
  easyprivacy: 53358-734, 3h.11m Δ
  urlhaus-1: 24205-0, 21h.12m
  plowe-0: 3548-0, 3d.21h.34m
  CHN-0: 24866-80, 2d.21h.13m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 340 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  github.com: 17

**Comment by TKINGNAMe** [comment]
I'm sorry that was posted wrong

uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 177976
 cosmetic: 156343
 scriptlet: 47971
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 85243-6354, never
  adguard-mobile: 10043-232, never
  fanboy-cookiemonster: 51603-205, 23m
  ublock-cookies-easylist: 1990-0, 23m
 default:
  user-filters: 0-0, never
  ublock-filters: 40904-141, 3h.15m Δ
  ublock-badware: 12331-1, 3h.15m Δ
  ublock-privacy: 1824-27, 3h.15m Δ
  ublock-unbreak: 2547-0, 3h.15m Δ
  ublock-quick-fixes: 172-0, 3h.15m Δ
  easylist: 78439-676, 3h.15m Δ
  easyprivacy: 53358-734, 3h.15m Δ
  urlhaus-1: 24205-0, 21h.15m
  plowe-0: 3548-0, 3d.21h.38m
  CHN-0: 24866-80, 2d.21h.17m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 340 ms (selfie)
 maxAssetCacheWait: 55 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 36
 network:
  bing.com: 36
 extended:
  ##li.b_algo:has(.b_algoSlug, p.b_lineclamp2):remove-class(b_algo…
  ##+js(href-sanitizer, a[href^="/rebates/welcome?url=http"], ?url…
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
  ##+js(trusted-set-cookie, BCP, AD=0&AL=0&SM=0)
  ##+js(json-prune, relatedAds)

**Comment by stephenhawk8054** [comment]
Can you test these filters:

```adb
bing.com#@#li.b_algo:has(.b_algoSlug, p.b_lineclamp2):remove-class(b_algo)
bing.com##li.b_algo:has(a[href^="https://www.bing.com/aclick?"], a[href^="https://www.bing.com/aclk?"]):has(.b_algoSlug, p.b_lineclamp2):remove-class(b_algo)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by TKINGNAMe** [comment]
Can work normally thank you

![PixPin_2024-12-26_10-49-00](https://github.com/user-attachments/assets/2de90cc6-6422-409a-9c60-c461be0c33cc)
