### ISSUE TITLE
newsblaze.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#2662]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://newsblaze.com/`
`https://newsblaze.com/business/legal/the-second-amendment-is-in-a-coma-ten-years-after-the-heller-decision_134067/`

### Describe the issue

Images in `Latest Legal News from PR Newswire` section won't load.

### Notes

`@@mma/?t`

**Comment by mapx-** [comment]
@ryanbr
