### ISSUE TITLE
skmedix.pl: breakage

### ISSUE THREAD

**Issue by Pseudonix19** [uBlockOrigin/uAssets#26638]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://skmedix.pl/`

### Category

breakage

### Description

there seems to be an invisible element which breaks the website. none of the buttons work. as an example the sign in button does not work. the mouse cursor does not change to the click cursor. disabling ublock fixes the website again.
element picker detects a full page ad but it does not remove it even after i click create.
the issues related to this are all closed and i have seen reddit posts of ppl with same issue mentioning that disabling adblocker fixes it

### Other extensions used

not applicable as issue persists even after i disable all extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 93403
 cosmetic: 59109
 scriptlet: 22216
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  ublock-privacy: null
 added:
  https://gitlab.com/Sorrow-San/9anime-adblock-filters/raw/master_with_banners/9Anime%20filter%20list: 166-5, now
  IND-0: 13742-0, now
 default:
  user-filters: 10-0, never
  easylist: 78642-413, 47m Δ
  plowe-0: 3545-4, now
  ublock-badware: 12364-22, 47m Δ
  ublock-filters: 40893-322, 47m Δ
  ublock-quick-fixes: 173-0, 47m Δ
  ublock-unbreak: 2547-12, 47m Δ
  urlhaus-1: 23535-0, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1661 ms (selfie)
 maxAssetCacheWait: 1459 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 46
 network:
  adtrafficquality.google: 1
  cloudflareinsights.com: 2
  criteo.com: 6
  doubleclick.net: 10
  google.com: 6
  googlesyndication.com: 20
  googletagmanager.com: 1
 extended:
  ###aswift_4_host
```
</details>

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/24746

**Comment by mapx-** [comment]
@Pseudonix19 reset uBO to defaults, test again
