### ISSUE TITLE
storage.googleapis.com: popups

### ISSUE THREAD

**Issue by notmaxkelly** [uBlockOrigin/uAssets#26640]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://storage.googleapis.com/bs-promo/ny2025/extension/index.html`

### Category

popups

### Description

The aforementioned website opens as a new tab on its own, displaying a variety of spam/phishing links. In this case, a 2025 VPN promo, though in the past it has manifested as other things - always originating from an automatically-opened tab under the storage.googleapis url.

### Other extensions used

OneTab, MetaMask

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screenshot 2024-12-27 at 1 32 27 PM" src="https://github.com/user-attachments/assets/299fde38-1f60-4943-b739-0a65e308ad97" />

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 141674
 cosmetic: 50096
 scriptlet: 21640
 html: 2245
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 41190-122, 1h.33m Δ
  ublock-badware: 12366-1, 1h.33m Δ
  ublock-privacy: 1812-27, 1h.33m Δ
  ublock-unbreak: 2605-1, 1h.33m Δ
  easylist: 78642-597, 1h.33m Δ
  easyprivacy: 53367-685, 1h.33m Δ
  urlhaus-1: 23535-0, 1h.33m
  plowe-0: 3545-0, now
  ublock-quick-fixes: 173-6, 1h.33m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2251 ms
 maxAssetCacheWait: 200 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
> The aforementioned website opens as a new tab on its own

I don't understand. At which website do you see the popup?

If you see it everywhere, you need to scan your computer or check your other extensions.

**Comment by notmaxkelly** [comment]
I apologize for the lack of clarity. The webpage I linked is _itself_ the popup. And it doesn't seem to be related to any other tabs I have open, nor any of my extensions. It opens by itself randomly a few times a week. Malwarebytes detects no threats on my Mac.

**Comment by stephenhawk8054** [comment]
As I said, if it happnes randomly without being triggered by any sites, something else on your machine is doing that, better to find the source of that. You can test in a new browser profile with only uBO and its default settings.
