### ISSUE TITLE
tonordersitye.com: detection

### ISSUE THREAD

**Issue by AadiVIP** [uBlockOrigin/uAssets#26644]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://tonordersitye.com/s?c813c414&r=aHR0cHM6Ly9pd29vemllLmJhYnkvYnlwYXNz`

### Category

detection

### Description

Detected

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium Mobile: 124
filterset (summary):
 network: 151502
 cosmetic: 143818
 scriptlet: 30379
 html: 0
listset (total-discarded, last-updated):
 added:
  IND-0: 13742-2, 1h.12m
  easylist-annoyances: 4734-95, 1h.12m
  easylist-chat: 216-0, 1h.12m
  easylist-newsletters: 8365-29, 1h.12m
  easylist-notifications: 3461-3, 1h.12m
  fanboy-cookiemonster: 68705-17307, 1h.12m
  fanboy-social: 16553-28, 1h.12m
  ublock-cookies-easylist: 2047-0, 1h.12m
 default:
  user-filters: 0-0, never
  adguard-mobile: 10240-102, 1h.12m
  easylist: 78654-544, 10m Δ
  easyprivacy: 53369-736, 10m Δ
  plowe-0: 3545-0, 1h.12m
  ublock-badware: 12365-1, 10m Δ
  ublock-filters: 41416-496, 10m Δ
  ublock-privacy: 1833-27, 10m Δ
  ublock-quick-fixes: 175-1, 10m Δ
  ublock-unbreak: 2550-2, 10m Δ
  urlhaus-1: 23245-0, 1h.14m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3922 ms
 maxAssetCacheWait: 1415 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  dfdgfruitie.xyz: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.

**Comment by stephenhawk8054** [comment]
Hmm...

```adb
||tonordersitye.com/s?*&r=aHR0c$doc,urlskip=?r -base64
```

works for me?
