### ISSUE TITLE
NSFW porndig.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#2664]
![2018-06-25](https://user-images.githubusercontent.com/5884000/41828343-02cfd19c-7835-11e8-9a19-ac5bd855785c.png)
`https://www.porndig.com/videos/99365/two-lesbians-wrestle-before-the-action.html`

broken site

Adblock Warning Removal List + Fanboy’s Annoyance List

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.10
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by okiehsch** [comment]
If I enable `Fanboy’s Annoyance List` the video plays but the picture is blurred. Disabling cosmetic filters fixes it on my end.

**Comment by mapx-** [comment]
Even enabling Annoyance List still able to see the video.

**Comment by okiehsch** [comment]
This is what I see with `Fanboy’s Annoyance List` enabled using Chrome.
![unbenannt](https://user-images.githubusercontent.com/16838044/41872767-333440dc-78c3-11e8-97be-492fbabf7b1d.JPG)

**Comment by mapx-** [comment]
Weird, I tested in FF / chrome, no such issue for me.

**Comment by KonoromiHimaries** [comment]
maybe a session of teamviewer?

**Comment by mapx-** [comment]
However, @ryanbr should test this issue

**Comment by okiehsch** [comment]
I found the issue. `Fanboy’s Annoyance List` has this filter `##.disclaimer_wrapper`.
This hides this disclaimer on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/41873327-f2ab3f96-78c4-11e8-898c-9f494e94ce3a.PNG)
I have to click Enter to see an "unblurred" video, once I have clicked Enter, the issue is fixed, even if I reenable `Fanboy’s Annoyance List`.

**Comment by mapx-** [comment]
Maybe the disclaimer is enabled on regional / country basis.

**Comment by KonoromiHimaries** [comment]
`porndig.com#@#.noadblock`

**Comment by ryanbr** [comment]
Is porndig.com#@#.disclaimer_wrapper needed?

**Comment by okiehsch** [comment]
On my end it still is needed.

Without the exception.
![unbenannt](https://user-images.githubusercontent.com/16838044/42738752-5e30cf28-8889-11e8-9a70-f4be36c3ddaf.JPG)

After adding `porndig.com#@#.disclaimer_wrapper`

![image](https://user-images.githubusercontent.com/16838044/42738760-848e5398-8889-11e8-8621-0375238ac366.png)
If I click `Enter` the unblurred video starts.

**Comment by spodermenpls** [comment]
@ryanbr 
> Is `porndig.com#@#.disclaimer_wrapper` needed?

The site `tukif.com` uses the same website framework as `porndig.com` and doesn't work with EasyList Cookie / Fanboy's Annoyances being activated, can you please add `tukif.com#@#.disclaimer_wrapper` to the allow list?

**Comment by spirillen** [comment]
A suggestion to block a few image/menu links

```css
! 2021-09-13 https://www.porndig.com
porndig.com##.dynamic_menu_item_snap
porndig.com##.co_sponsor
```

But missing the "Webcam" link from the menu

![image](https://user-images.githubusercontent.com/44526987/133075740-f4fa830b-7043-4e2c-a71f-2a9eaec46bf9.png)
