### ISSUE TITLE
wow.realmofmetal.org: breakage

### ISSUE THREAD

**Issue by RainerMathey** [uBlockOrigin/uAssets#26641]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://wow.realmofmetal.org/`

### Category

breakage

### Description

... the whole site is completely black.

### Other extensions used

Proton Pass
Proton VPN (not active)
MyJdownloader
Cookie-Editor
Clear Browsing Data
Flagfox
Livemarks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.3rc3
Firefox: 133
filterset (summary):
 network: 203227
 cosmetic: 132801
 scriptlet: 32173
 html: 2523
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2700-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/pro.mini.txt: 84247-0, 12m
  fanboy-cookiemonster: 51613-207, 1m
  ublock-cookies-easylist: 2009-5, 1m
  fanboy-social: 16530-11, 1m
  easylist-annoyances: 4734-56, 1m
  easylist-chat: 216-1, now
  easylist-newsletters: 8363-47, 1m
  easylist-notifications: 3460-171, 1m
  ublock-annoyances: 5900-54, 12m Δ
 default:
  user-filters: 0-0, never
  ublock-filters: 41192-347, 12m Δ
  ublock-badware: 12373-546, 12m Δ
  ublock-privacy: 1812-105, 12m Δ
  ublock-unbreak: 2605-2, 12m Δ
  ublock-quick-fixes: 175-8, 12m Δ
  easylist: 78652-21992, 12m Δ
  easyprivacy: 53369-8071, 12m Δ
  urlhaus-1: 23535-2, 12m
  plowe-0: 3545-2286, now
  DEU-0: 7828-66, 12m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 59 redacted]
hostRuleset:
 added: [array of 532 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7413 ms (selfie)
 maxAssetCacheWait: 3452 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 27
 network:
  realmofmetal.org: 2
  a-ads.com: 5
  ajax.googleapis.com: 1
  discord.com: 1
  ferendum.com: 1
  googletagmanager.com: 1
  histats.com: 1
  net.cdn.cloudflare.net: 12
  sli.do: 1
  tiennguyenvan.github.io: 2
 extended:
  ##.header-social-icons
  ##.top-ad
  ##.adsfloat
  ##.footer-ad
```
</details>

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by gorhill** [comment]
Looks like you are using dynamic filtering and you are blocking `ajax.googleapis.com`.

Please mind the [warning in the documentation](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) regarding advanced user features

Additionally, regarding [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode):

> However, be ready to accept that you will have to un-break websites

It's for you to websites broken as a result of using advanced blocking modes.
