### ISSUE TITLE
fearmp4.ru: detection

### ISSUE THREAD

**Issue by NotErixl** [uBlockOrigin/uAssets#26642]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://fearmp4.ru/temnaya-storona-nauki/`

### Category

detection

### Description

Блокировка воспроизведения ролика при включении uBlock/обнаружение uBlock

![image](https://github.com/user-attachments/assets/bdfd9414-c97b-4750-bc92-40bdc478e3a3)

### Other extensions used

DeepL: ИИ-переводчик и редактор
SponsorBlock для YouTube
Редактор Microsoft
Dark Reader
FrankerFaceZ
Google Переводчик
LastPass: Free Password Manager
Return YouTube Dislike
Shazam
Tampermonkey
Twitch VOD Downloader
Youtube Audio Compressor

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Chromium: 131
filterset (summary):
 network: 160088
 cosmetic: 70816
 scriptlet: 24990
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40896-120, 1m
  ublock-badware: 12371-1, 1m
  ublock-privacy: 1832-28, 1m
  ublock-unbreak: 2547-1, 1m
  ublock-quick-fixes: 179-7, 1m
  easylist: 78654-643, 1m
  easyprivacy: 53369-735, 1m
  urlhaus-1: 23245-0, 1m
  plowe-0: 3545-0, 1m
  RUS-0: 41068-128, 1m
filterset (user): [empty]
trustedset:
 added: [array of 1232 redacted]
switchRuleset:
 added: [array of 26 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 701 ms
 maxAssetCacheWait: 130 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  yandex.ru: 2
 extended:
  ###ads_banner
  ##div[id^="yandex_rtb"]
```
</details>

**Comment by dimisa-RUAdList** [comment]
This is a Russian site. The rules for it should be contained in RU AdList.

Fix: https://github.com/easylist/ruadlist/commit/b7f1f70d5c23c9284f26c2cea19e76e178334f63

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054

**Comment by stephenhawk8054** [comment]
I included the fix in uAssets because there's race condition issue with scriptlets in Firefox in version `1.61.2`, hence there using of HTML filtering.

Version `1.62` won't have that issue any more and I will remove the filters.

**Comment by dimisa-RUAdList** [comment]
In cases where the scriptlet fails to execute, a cosmetic exception should work: `fearmp4.ru#@##ads_banner`
