### ISSUE TITLE
[nsfw] sextb.net: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#26645]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/d63c43eb-5ab0-49dc-8aec-e31bc28f7532), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site or browser issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://sextb.net/uncensored?genre=all&studio=all&quality=all&year=all&sort=liked`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/3a11da73-8099-4f5a-9a28-dfbeadf2b7b6)

</details>

### Configuration

```yaml
version: uBOL 2024.12.23.23
mode: complete / complete
rulesets:
 default
 annoyances-cookies
 annoyances-overlays
 annoyances-others
 urlhaus.full
 openphish.domains
 idn-0
```

**Comment by Yuki2718** [comment]
> * there are popup ads nsfw `https://sextb.net/juy-883-sub` & some players such as **TB** does not work on **UBOL**

I don't get popup on TB with uBOL 2024.12.23.23.

**Comment by Yuki2718** [comment]
Can you add to ubol-filters?

**Comment by Yuki2718** [comment]
No with Optimal mode, will be applied with Complete mode.

**Comment by stephenhawk8054** [comment]
Maybe similar to this case for generic cosmetic filters: https://github.com/uBlockOrigin/uBOL-home/issues/250#issuecomment-2506237308

**Comment by Yuki2718** [comment]
> can you transfer this issue to UBOL repo & add suitable tag so that it's not missed?

I think no need, as it's linked to the issue.

**Comment by Bug-Cache** [comment]
leftovers

https://github.com/user-attachments/assets/8ff85e89-8fda-4eb0-a1f4-96a9538e9c71

**Comment by mapx-** [comment]
add as custom filter

`sextb.net##.msg-alert.notice`
