### ISSUE TITLE
[nsfw] r34.app: ads

### ISSUE THREAD

**Issue by TYTheBeast** [uBlockOrigin/uAssets#26648]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://r34.app/posts/rule34.xxx?page=6&tags=wisp_%28warframe%29`

### Category

ads

### Description

Ads displayed as posts are still shown

### Other extensions used

Privacy Badger

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 128
filterset (summary):
 network: 141604
 cosmetic: 50098
 scriptlet: 21651
 html: 2251
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41197-122, 47m Δ
  ublock-badware: 12373-1, 47m Δ
  ublock-privacy: 1819-27, 47m Δ
  ublock-unbreak: 2605-1, 47m Δ
  ublock-quick-fixes: 179-5, 47m Δ
  easylist: 78654-218, 47m Δ
  easyprivacy: 53369-72, 47m Δ
  urlhaus-1: 23445-0, 1h.47m
  plowe-0: 3545-994, 1m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 128 ms (selfie)
 maxAssetCacheWait: 44 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  sentry.io: 11
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718 a suggestion for the easylist filterlists:

for the ads:
`r34.app##figure:has(> a[href^="http"][href*="&utm_"])`

get premium annoyance (self advertisment)
`r34.app##figure:has(> a[href^="/premium?"][href*="&utm_"])`

**Comment by Yuki2718** [comment]
I can't reproduce either, is it random?

**Comment by JobcenterTycoon** [comment]
Scroll more.

**Comment by Yuki2718** [comment]
If you mean `hentaiporn.app` banner, it's a self-promotion. Click it and it jumps to `https://www.hentaiporn.app/posts`.
