### ISSUE TITLE
jeanmarcmorandini.com: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#26658]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.jeanmarcmorandini.com/article-594413-la-video-de-ce-livreur-uber-eats-dechaine-les-passions-sur-twitter-il-decide-de-manger-la-commande-car-le-client-lui-demande-de-monter-a-l-etage-ce-qu-il-refuse-regardez.html`

### Category

breakage

### Description

The video player is not displayed.

### Other extensions used

None that interfere with uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/a281415f-e292-42c8-b2a4-1a63f85c3d8f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 128
filterset (summary):
 network: 173706
 cosmetic: 77770
 scriptlet: 23901
 html: 2266
listset (total-discarded, last-updated):
 added:
  https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt: 1052-2, now
  RUS-0: 41120-256, now
 default:
  user-filters: 14-0, never
  ublock-filters: 41203-122, now
  ublock-badware: 12386-1, now
  ublock-privacy: 1822-27, now
  ublock-unbreak: 2605-1, now
  ublock-quick-fixes: 172-3, 22m Δ
  easylist: 78748-224, now
  easyprivacy: 53376-74, now
  urlhaus-1: 23575-0, now
  plowe-0: 3545-994, now
  FRA-0: 20238-300, now
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 334 ms (selfie)
 maxAssetCacheWait: 141 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  opti-digital.com: 1
  pmdstatic.net: 1
  sparteo.com: 1
  taboola.com: 1
  viously.com: 4
 extended:
  ##.ads-core-placer
  ###taboola-right-rail-thumbnails
  ###taboola-below-article-thumbnails
  ##div[id^="jmm_ads_"]
  ##.ban-bottom-desktop
  ##.ads-ban-header
  ##.block-jmm-ads-prisma
  ##[data-ads-core]
  ###node-story > h2.story_subtitle_title:contains(/^Ailleurs sur …
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||sonar.viously.com/*/js^$script,domain=jeanmarcmorandini.com
```

@ryanbr
