### ISSUE TITLE
baseball-reference.com: ads

### ISSUE THREAD

**Issue by gmkohler** [uBlockOrigin/uAssets#26665]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.baseball-reference.com/players/w/westbjo01.shtml`

### Category

ads

### Description

Ads have started showing up on firefox with baseball-reference.com.  They also run basketball-reference.com, hockey-reference.com, pro-football-reference.com, among other websites.

### Other extensions used

<img width="783" alt="Screenshot 2024-12-29 at 22 26 36" src="https://github.com/user-attachments/assets/4dd5842c-9a34-4081-b73c-a11c843167f1" />

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2117" alt="Screenshot 2024-12-29 at 22 27 19" src="https://github.com/user-attachments/assets/4c2ee30a-15ac-4074-82d2-2a4a2a7e79af" />

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 142044
 cosmetic: 50151
 scriptlet: 21653
 html: 2250
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41206-122, now
  ublock-badware: 12402-1, now
  ublock-privacy: 1822-27, now
  ublock-unbreak: 2605-1, now
  ublock-quick-fixes: 169-3, now
  easylist: 78748-224, now
  easyprivacy: 53377-72, now
  urlhaus-1: 23810-0, now
  plowe-0: 3546-994, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2761 ms (selfie)
 maxAssetCacheWait: 29 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0
 no-popups: true
 extended:
  ##.GoogleActiveViewElement:not(:has(> #reward_close_button_widge…
  ##.GoogleActiveViewElement > div:not(#reward_close_button_widget…
  ###abgb
  ##+js(set-constant, rwt, noopFunc)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##+js(prevent-xhr, vod.provider.plex.tv/ad?, war:noop-vast3.xml)
  ##+js(prevent-fetch, secure.adnxs.com/ptv, war:noop-vast4.xml)
  ##+js(xml-prune, VAST, , barstoolsports.com)
  ##+js(prevent-xhr, worldsurfleague.com, war:noop-vmap1.0.xml)
```
</details>

**Comment by Yuki2718** [comment]
I see only placeholder there.

**Comment by stephenhawk8054** [comment]
Test again in a new Firefox profile with only uBO and its default settings.

**Comment by gmkohler** [comment]
Looks like whatever was going wrong has fixed itself, with and without the separate profile having only uBO installed.  Sorry for the extra work.
