### ISSUE TITLE
rojadirectaonlinetv.com, etc.

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#2666]
### URL(s) where the issue occurs

`http://www.rojadirectaonlinetv.com/canal-3.php`
`http://www.rojadirectaonlinetv.com/canal-17.php`
`http://www.extremotvplay.com/canal-4.php`

### Describe the issue

Ads in video

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/41850443-8d74e9f0-7852-11e8-8fd1-8c54247212d9.png)

**Comment by mapx-** [comment]
test
```
||netdna-ssl.com^$subdocument,domain=telerium.tv
*$popup,domain=rojadirectaonlinetv.com
*$popup,domain=extremotvplay.com
peer2cast.pro###ads
```

**Comment by okiehsch** [comment]
Also
`capodeportes.net##script:inject(abort-on-property-write.js, _pop)`

**Comment by terrorist96** [comment]
Clicking links from the home page no longer works due to the aggressive popup blocking,
`http://www.rojadirectaonlinetv.com/`

**Comment by mapx-** [comment]
test
```
*$popup,domain=rojadirectaonlinetv.com,badfilter
*$popup,domain=rojadirectaonlinetv.com,third-party
*$popup,domain=extremotvplay.com,badfilter
*$popup,domain=extremotvplay.com,third-party
```

**Comment by terrorist96** [comment]
That works. Also an unblocked video ad here:
`http://www.rojadirectaonlinetv.com/azteca-7-en-vivo.php`
"WATCH NOW" button
