### ISSUE TITLE
webhallen.com: breakage

### ISSUE THREAD

**Issue by rob-katt** [uBlockOrigin/uAssets#26679]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.webhallen.com/se/category/187-Gamepads`

### Category

breakage

### Description

Breaks the cookie confirmation by removing the buttons but not the bar that takes over half the screen

### Other extensions used

none that is relevant in this case, since disabling ad block on the site fixes it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 133
filterset (summary):
 network: 146079
 cosmetic: 120780
 scriptlet: 29283
 html: 2253
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32881-52, now
  ublock-cookies-adguard: 2015-21, now
  fanboy-cookiemonster: 51554-4043, now
  ublock-cookies-easylist: 2015-2015, now
 default:
  user-filters: 1-0, never
  ublock-filters: 41211-122, 1h.30m Δ
  ublock-badware: 12408-1, 1h.30m Δ
  ublock-privacy: 1822-27, 1h.30m Δ
  ublock-unbreak: 2606-1, 1h.30m Δ
  ublock-quick-fixes: 169-3, 1h.30m Δ
  easylist: 78828-223, 1h.30m Δ
  easyprivacy: 53377-72, 1h.30m Δ
  urlhaus-1: 23680-0, now
  plowe-0: 3547-995, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1842 ms
 maxAssetCacheWait: 582 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  newrelic.com: 2
 extended:
  ###cookie-banner
  ##.cookie-info:not(body):not(html)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
webhallen.com##.cookie-consent
webhallen.com##+js(set-local-storage-item, necessaryConsent, true)
webhallen.com##+js(set-local-storage-item, marketingConsent, false)
webhallen.com##+js(set-local-storage-item, personalisationConsent, false)
```

@ryanbr @Alex-302
