### ISSUE TITLE
windowsreport.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#26671]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/d63c43eb-5ab0-49dc-8aec-e31bc28f7532), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I am not using uBO Lite along with other content blockers.
- [X] I have verified that the issue still exists after using the [`Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBOL Lite and isn't a site or browser issue.
- [X] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://windowsreport.com/how-to-stop-microsoft-edge-from-screenshots/`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/57ba9f60-ec18-4050-a83a-3cadf3f4a9d5)

</details>

### Configuration

```yaml
version: uBOL 2024.12.23.23
mode: complete / complete
rulesets:
 default
 annoyances-cookies
 annoyances-overlays
 annoyances-others
 urlhaus-full
 openphish-domains
 idn-0
```

**Comment by stephenhawk8054** [comment]
@gorhill Hmm... weird, this filter

```adb
/^https:\/\/[0-9a-f]{10}\.[0-9a-f]{10}\.com\/[0-9a-f]{32}\.js$/$script,3p,to=com
```

works in Firefox but somehow the regex not matched in chromium?

If I change the `$` at the end to `\b`, it works

```adb
/^https:\/\/[0-9a-f]{10}\.[0-9a-f]{10}\.com\/[0-9a-f]{32}\.js\b/$script,3p,to=com
```

**Comment by gorhill** [comment]
Need to investigate. I stepped into the code and I can see the regex internally is `^https:\/\/[0-9a-f]{10}\.[0-9a-f]{10}\.com\/[0-9a-f]{32}\.js$`, which matches `https://577c231052.a91e9c75f8.com/1f73d9b08f0e105bc80ef1970dafe1db.js`, but no match is found when using the following in uBO's dev tools page (after adding `||a91e9c75f8.com^$badfilter`):

    snfe?https://577c231052.a91e9c75f8.com/1f73d9b08f0e105bc80ef1970dafe1db.js
    url: https://577c231052.a91e9c75f8.com/1f73d9b08f0e105bc80ef1970dafe1db.js
    not blocked

**Comment by stephenhawk8054** [comment]
> In uBOL it might not work though because the regex might be rejected by the DNR API

Hmm... When I checked the `log.txt` file in uBOL-home, I didn't see the filter being listed as rejected?

**Comment by gorhill** [comment]
The regex is a valid [RE2 regex](https://en.wikipedia.org/wiki/RE2_(software)), so it passes the compile-time test and a rule is created for it. However there is a further test at run-time using [`isRegexSupported()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/isRegexSupported) before the rule is used and that test fails, and these are reported at the console. See <https://github.com/uBlockOrigin/uBOL-home/issues/15#issuecomment-1332760988>.

Unfortunately `isRegexSupported()` is browser-dependent and this cannot be used at rule compile-time, there is an open webextensions issue about this: <https://github.com/w3c/webextensions/issues/344>.

**Comment by stephenhawk8054** [comment]
Ah I see, I always thought `isRegexSupported` is at compile-time.

About browser-dependent, is it different depending on users' machine power as well, or all chromium browsers would be the same? If it's the former, that would be really difficult to evaluate the filters.

**Comment by gorhill** [comment]
I expect all Chromium-based browsers would be the same, but since it's currently implementation-dependent and not API-dependent, there is no 100% guarantee.

It's the reason for the webextensions issue I linked above, to make it easier for extension authors to figure out at rule compile-time what is a valid regex and what is not, but beside [a bit of talk about it in August 2023](https://github.com/w3c/webextensions/blob/main/_minutes/2023-08-31-wecg.md), nothing has moved forward.
