### ISSUE TITLE
Handelsblatt.com - Overlay asking to turn off adblocker

### ISSUE THREAD

**Issue by Snow8** [uBlockOrigin/uAssets#267]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

handelsblatt.com and every link to one of their articles.

### Describe the issue

Complete page overlay, asking you to turn off your adblocker.

You get redirected from handelsblatt.com to http://www.handelsblatt.com/impressum/nutzungshinweise/blocker/?callback=%2F

### Screenshot(s)

![handelsblatt-fullpage](https://cloud.githubusercontent.com/assets/11486958/22012086/af4196e4-dc92-11e6-843e-72edc5299301.png)

### Versions

- Browser/version: Firefox Dev Edition v52
- uBlock Origin version: 1.10.4

### Settings

Advanced User (+) with the following lists

![ublock-fullpage](https://cloud.githubusercontent.com/assets/11486958/22012141/ee710e30-dc92-11e6-8b2e-1f70d9b61b90.png)

I also use Easylist Germany (not on the screenshot).

**Comment by mapx-** [comment]
add
`@@||handelsblatt.com/js/*/iqadcontroller.js`

**Comment by Snow8** [comment]
Works. Thank you :)

**Comment by uBlock-user** [comment]
add - `||vhb.de^`
