### ISSUE TITLE
thexvid.com [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2684]
URL(s) where the issue occurs

`https://thexvid.com/video/0fOZ4Nwm5Pg/drake-s-dad-claps-back-at-wendy-williams-he-calls-her-rupaul-after-she-dissed-drake-on-her-show.html`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by mapx-** [comment]
Where are the ads ?

**Comment by okiehsch** [comment]
I can reproduce with Chrome.

**Comment by KiLL4FuNK** [comment]
![](https://i.imgur.com/ik1IeEA.jpg)
