### ISSUE TITLE
yesmovies.to

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2689]
URL(s) where the issue occurs

`https://yesmovies.to/movie/edge-of-seventeen-2016-19170/576707-16/watching.html`

Describe the issue

YOU CAN NOT SEE THE VIDEO

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by KiLL4FuNK** [comment]
YOU CAN NOT SEE THE VIDEO

**Comment by mapx-** [comment]
try
```
loadvid.online#@#script:inject(set-constant.js, pop_cnt, 3)
loadvid.online##script:inject(set-constant.js, pop_cnt, 2)
```

**Comment by KiLL4FuNK** [comment]
It works perfect

**Comment by ghajini** [comment]
`https://yesmovies.gg`
`https://yesmovies.cloud/genre/comedy/`

Ads

**Comment by ghajini** [comment]
`https://www5.yesmovies.org/movies-fighting-with-my-family-2019-yesmovies.html`
There's a popup

**Comment by ghajini** [comment]
popups
`yesmovies.to`

**Comment by ghajini** [comment]
Clone of yesmovies....
3rd party tracking

`https://cdn.yesmovies.is/embed?id=1488672&t=Wake+Up+&y=2019&referrer=link&server=1`

`https://yesmovies.is/wake-up-stream-1488672.html`

Filter
`||cdn.yesmovies.is/sw-vodlocker.to.js$domain=cdn.yesmovies.is,important`

`||yesmovies.is/sw.js$important`

**Comment by ghajini** [comment]
Hello @mapx-
it is good to add
`/sw-vodlocker.to.js$important` as it prevents 3rd party garbabge on many sites
Present here on sites
`xmovies8.is`
`cmovieshd.is`
`flixtor.life`
`yesmovies.is`
`rainierland.is`
