### ISSUE TITLE
http://www.timeout.com

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#269]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.timeout.com/london/offers`

### Describe the issue

Unable to hide the cookie message with ##DIV[data-module="cookie_banner"] using uBo.

### Screenshot(s)

http://i.imgur.com/LzfzkC1.png

### Versions

- Chrome 55

- uBlock Origin 1.10.4

### Settings

default I believe.

### Notes

Filter works in Firefox / Adblock Plus, just not uBo.

**Comment by mapx-** [comment]
the filter is working fine for me chrome / ff + ubo

**Comment by ryanbr** [comment]
Okay, seems to be working for me now. Not sure why it didnt in the first place.

Closing.
