### ISSUE TITLE
short.pe & clik.pw

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#2699]
### URL(s) where the issue occurs

`http://short.pe/jr6upH`
`http://clik.pw/eJacCa`

### Describe the issue

After you solve the captcha, an overlay ad becomes active. Notice the url upon mouse hover. It's `http://zukxd6fkxqn.com/*.html`.
This makes it impossible to click anything.

### Screenshot(s)

![capture_001_27062018_001620](https://user-images.githubusercontent.com/12146319/41932858-d8e6ae0c-799f-11e8-83de-55969420e4ba.png)

**Comment by mapx-** [comment]
update ublock filters (clik.pw was already fixed)

**Comment by version365** [comment]
oh.. ok. thanks..

**Comment by ghajini** [comment]
`https://short.pe/efXA2`
Popup ads after captcha solving when clicked anywhere in page....
IP block `||35.194.16.41^$important` helps to prevent popup ads on handfull of sites
@ryanbr

**Comment by monkeyde98** [comment]
in firefox browser is detecting!
