### ISSUE TITLE
not blocked popups

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#270]
Firefox 50.1.0 Windows
uBlock origin 1.10.4
All filters are up-to-date (default filters)

Page: http://showdramapacks.com/

Click any links, always a popup ad opens without being blocked.

**Comment by mapx-** [comment]
```
|http://$script,domain=showdramapacks.com,third-party
@@||wp.com^$script,domain=showdramapacks.com
```
openload / thevideo popups
```
@@|https://4*.info/*.js|$domain=openload.co
@@|https://ch*.info/*.js|$domain=openload.co
||openload.co/*license
||openload.co/*script
@@||thevideo.me/js/jspc.js?ab
```

**Comment by gorhill** [comment]
Add `showdramapacks.com##script:inject(popads.net.js)` as custom filter, or force an update of _"uBlock filters"_.

**Comment by uBlock-user** [comment]
For openload popups add - ````
openload.co##script:inject(abort-on-property-read.js, adblock2)
openload.co##script:inject(setTimeout-defuser)
````
