### ISSUE TITLE
sinoptik.com.ru, sinoptik.ua

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#2702]
### URL(s) where the issue occurs

sinoptik.com.ru, sinoptik.ua

### Describe the issue

Many ads

### Screenshot(s)

https://imgur.com/a/pjmpFJb

### Versions

- Browser/version: Opera Stable
- uBlock Origin version: 1.16.11rc2

### Settings

uBO's default settings

**Comment by mapx-** [comment]
@okiehsch  filter

**Comment by PoRtvine** [comment]
Many ads again

Screenshot(s)

http://jpeg.im/doxq

**Comment by mapx-** [comment]
ruadlist is working for sinoptik.com.ru, for sinoptik.ua add a similar filter
`||sinoptik.ua/|$csp=script-src 'self' * blob: data:`
