### ISSUE TITLE
www.chip.de Pop-Up

### ISSUE THREAD

**Issue by amaru7** [uBlockOrigin/uAssets#2703]
`www.chip.de`

A Pop Up that suggests disabling Adblock comes up, not closable, makes site not usable.

**Comment by zaphodbeebblebrox** [comment]
I cannot reproduce.

**Comment by okiehsch** [comment]
If you mean
![unbenannt](https://user-images.githubusercontent.com/16838044/42059307-3e7d7370-7b23-11e8-8f82-de7dbdefa893.PNG)

That is already fixed, I can only reproduce if I disable `uBO-filters`
