### ISSUE TITLE
KissAnime.ru and Anti-Adblock

### ISSUE THREAD

**Issue by Yumire** [uBlockOrigin/uAssets#2704]
### URL(s) where the issue occurs

`http://kissanime.ru/Anime/Steins-Gate-0/Episode-001?id=144735&s=rapidvideo`
`All episode pages I would assume`

### Describe the issue

KissAnime has updated their Anti-AdBlock and is preventing users from viewing videos when uBlock Origin (or any adblocker) is enabled on the site.

### Screenshot(s)

https://i.imgur.com/12qemq1.png

### Versions

- Browser/version: 68.0.3440.33
- uBlock Origin version: 1.16.10

### Settings

- Default settings with the exception of my own filters added under **My Filters**.

### Notes

The url `http://kissanime.ru/oueyf/nyars.aspx` is loaded into an iframe and makes 3 http requests to urls from their ad providers. After 45 seconds it will check to see if the requests failed and if so will call a function from the parent window that will remove the video and display a "Please disable adblock" message.

Also I have reason to believe that the url may change in the future since the url used to be `http://kissanime.ru/xyz/check.aspx`.

**Comment by RomanADavis** [comment]
As a temporary fix, add  http://kissanime.ru/oueyf/nyars.aspx to your filters list.

**Comment by RomanADavis** [comment]
Yeah, just adding the url to the filters list is being passed around as the temp fix right now.

**Comment by Yumire** [comment]
Fix no longer works. They changed the function name from `Check` to something that appears to just be random characters and the setTimeout time from `45` to `37` seconds.

**Comment by Yumire** [comment]
@zaphodbeebblebrox I really hate to be a bother but they changed `.aspx` to `.asp` so the fix no longer works again.

I have a feeling that they will keep changing things to avoid the filters. Something similar happened with a popular KissAnime chrome extension which ended with the dev of the extension forced to remove the adblocking feature from it.
