### ISSUE TITLE
eu.turboserver.tk [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2705]
URL(s) where the issue occurs

`https://eu.turboserver.tk/index.php`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by FranciscoPaixao** [comment]
This is my website, you son of a bitch.

**Comment by TurboServer** [comment]
TurboServer is in a new domain:
https://turboserver.info

It's ugly to want to use adblock on a nonprofit project.

Curiosity: I'm Brazilian and you're Argentine. kkkkkkkkkkkkkkkkkkk
