### ISSUE TITLE
[Anti-adblock] kissanime.ru

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2708]
### URL(s) where the issue occurs

`http://kissanime.ru/Anime/Steins-Gate-0/Episode-010?id=146783&s=rapidvideo`

### Describe the issue

Anti-adblock, I updated filters just now (Thu Jun 28 2018 18:39:19 GMT-0600, just before time of this post). Takes ~40 seconds to trigger. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/42067255-79ca554a-7b02-11e8-898a-b33fc0119667.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.10

### Settings

English default.

**Comment by jspenguin2017** [comment]
Hum, I can't reproduce anymore. Closing for now.

**Comment by okiehsch** [comment]
Fixed by https://github.com/uBlockOrigin/uAssets/commit/f5833bc9907cb1d412fb177cbfebe09851b631e9
The detection: `view-source:http://kissanime.ru/oueyf/nyars.aspx`
Nooping the three scripts also works on my end, so if you still have issues I can add those too.

**Comment by jspenguin2017** [comment]
Could be some cache issue, I have noted this down, I'll test it again tomorrow or Saturday.

**Comment by juppaluri** [comment]
Hello.  I have followed all of these instructions and the issue still stands.  I followed all troubleshooting instructions.  Is this just a problem with my browser?
Thank you

**Comment by zaphodbeebblebrox** [comment]
Filter just got updated again, if you force an update of your filter lists it should work.
