### ISSUE TITLE
Captch Me (Attentive ADs) is blocked

### ISSUE THREAD

**Issue by BMitrovic17** [uBlockOrigin/uAssets#2709]
### URL(s) where the issue occurs

`https://freebitcoin.win/faucet/bitcoin`

### Describe the issue

Website uses 3 types of captchas and two of them works fine while third one gets blocked. This is the Captch Me by Attentive ADs. Do note that in order to get CaptchME you have to refresh few times since all 3 captchas are rotated.

### Screenshot(s)

![2018-06-29_14-10-40](https://user-images.githubusercontent.com/25082525/42091727-bcb7005c-7ba6-11e8-83c6-8fa001a579e4.png)

### Versions

- Browser/version: Firefox 61
- uBlock Origin version: 1.16.10

### Settings

- Default settings + uBlockProtector `https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin`

--
Any help in which direction to look at is greatly appreciated.

**Comment by mapx-** [comment]
I get anti adb on the page with solve media (I get no other captcha)

**Comment by BMitrovic17** [comment]
You have to refresh several times before solve media is switched to Captch Me

**Comment by okiehsch** [comment]
Do I have to be logged in?
Even if I refresh 10+ times, I  get the solve media captcha every time.

**Comment by smed79** [comment]
Only "solve media captcha" here.

**Comment by BMitrovic17** [comment]
Seems like you have to be logged in, indeed. Any proper way of capturing everything so i can provide data in order to spare you guys from wasting time registering.

**Comment by mapx-** [comment]
I found another case using Captch Me
`https://freecoinsfor.me/`

Could you test these filters ?
```
freecoinsfor.me##script:inject(bab-defuser.js)
@@||ppcadmedia.com/$script,domain=freecoinsfor.me
```

**Comment by BMitrovic17** [comment]
@okiehsch Yup, that does fix the issue at hand. Thank you very much.

**Comment by BMitrovic17** [comment]
@mapx- You can also expand it for `coindice.win`. They've added it today.
Using `coindice.win##script:inject(set-constant.js, CaptchmeState.adb, undefined)` works just fine.

**Comment by BMitrovic17** [comment]
@mapx- 
And another one added it as of today.
`yannik.biz##script:inject(set-constant.js, CaptchmeState.adb, undefined)`
