### ISSUE TITLE
xrares.com [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2713]
URL(s) where the issue occurs

`https://www.xrares.com/video/13262/spying-on-sweet-teen-ass-in-shorts`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 66 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by mapx-** [comment]
add
```
xrares.com###aclose
||afgr4.com^
```

**Comment by smed79** [comment]
@KiLL4FuNK https://forums.lanik.us/viewtopic.php?f=62&t=39694&p=130908&hilit=xrares.com#p130908

**Comment by dportvine** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/158521

**Comment by Yuki2718** [comment]
Not reproduced. Removed `xrares.com##+js(acs, gigaCS)`

**Comment by dportvine** [comment]
`https://www.xrares.com/video/1141/indian-pussy-groping-at-workplace`

<details>
<summary>Video [NSFW]</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/eb7869cf-6d88-4ef7-ba48-3b5d8cbd6ae5
</details>

`https://www.xrares.com/xopind.js`
<details>
<summary>Screen</summary>

![2023-08-07_195910](https://github.com/uBlockOrigin/uAssets/assets/111344219/8cf0cedb-d4b5-4070-a946-689a425eee9f)
</details>
