### ISSUE TITLE
lanjutkeun.blogspot.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2715]
URL(s) where the issue occurs

`https://lanjutkeun.blogspot.com/p/golink.html?url=aHR0cHM6Ly9hbm9uZmlsZS5jb20vZWZmZVNiYzRiMC9GTF9TdHVkaW9fMTIuNS4xLjUua3V5aEFhLk1lLnJhcg==`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by mikhaelkh** [comment]
Logger shows `Invalid cosmetic filter in ublock-annoyances : ##body:style(-moz-user-select: text !important;)` during update.

**Comment by okiehsch** [comment]
I can't reproduce, my logger does not show any invalid filters if I update `uBO-annoyances`.

**Comment by mikhaelkh** [comment]
@okiehsch Chrome latest [dev build](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).
![logger](https://user-images.githubusercontent.com/8005688/50545247-be229380-0c1e-11e9-9600-d137f2a4aef2.png)

**Comment by okiehsch** [comment]
With Chrome uBO-dev build
![image](https://user-images.githubusercontent.com/16838044/50545401-3daa6580-0c13-11e9-97e3-0b6220408b6e.png)

With Chrome uBO-stable
![image](https://user-images.githubusercontent.com/16838044/50545418-8bbf6900-0c13-11e9-8a62-54643ecc2eb2.png)

With Firefox uBO-dev build
![image](https://user-images.githubusercontent.com/16838044/50545432-d8a33f80-0c13-11e9-94f3-b06073b94bc2.png)

So only Chrome + uBO-dev build seems to be affected. @gorhill

**Comment by okiehsch** [comment]
With Chrome uBO-dev build
![image](https://user-images.githubusercontent.com/16838044/50545401-3daa6580-0c13-11e9-97e3-0b6220408b6e.png)

With Chrome uBO-stable
![image](https://user-images.githubusercontent.com/16838044/50545418-8bbf6900-0c13-11e9-8a62-54643ecc2eb2.png)

With Firefox uBO-dev build
![image](https://user-images.githubusercontent.com/16838044/50545432-d8a33f80-0c13-11e9-94f3-b06073b94bc2.png)

**Comment by okiehsch** [comment]
Well, using the picker shows that `##body:style(-moz-user-select: text !important;)` is not a valid filter using Chrome.
![image](https://user-images.githubusercontent.com/16838044/50545519-cb3b8480-0c16-11e9-9228-247ecc604a58.png)

It is a valid filter using Firefox, anyway all `https://lanjutkeun.blogspot.com` filters can be removed the site has been deleted.

**Comment by mikhaelkh** [comment]
@gorhill, is the difference in behavior caused by bug?

**Comment by gwarser** [comment]
On Chrome try `##body:style(-webkit-user-select: text !important)`

`-moz...` and `-webkit...` means these rules are experimental https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by gorhill** [comment]
I would like to understand why this wasn't reported as an invalid filter in 1.17.4, I need to investigate.

**Comment by gorhill** [comment]
I don't need to investigate, I remember. The filter was also rejected with 1.17.4, but _silently_. I've re-work a bit the code in 1.17.5 to be able to report those invalid filters which were not reported.
