### ISSUE TITLE
[IP Ban] Kissanime.ru

### ISSUE THREAD

**Issue by SakhJack** [uBlockOrigin/uAssets#2719]
### URL(s) where the issue occurs

`http://kissanime.ru/ToYou/Banned/`
or any url of that domain in my case

### Describe the issue

They basically IP ban if they detect adblock; used different browser w/o any extensions - still banned

### Screenshot(s)

[Message](https://imgur.com/a/BDCWAM8)

### Versions

- Browser/version: Firefox 61.0 x64
- uBlock Origin version: 1.16.12

### Settings

I blacklisted adsterra.com in both uMatrix and uBlock since it wasn't in your filters yet
I also have Nano Defender and it's integration into uBlock
[Filters I use](https://imgur.com/a/HKrWKzL)
I use NoScript and Privacy Badger as well to block ads/tracking, so not sure which takes effect first to trigger anti-adblock
### Notes

They recently partnered up with adsterra.com and I saw a lot of different issues popped up here as a consequence
Your team would try to bypass anti-adblock but they would counter soon
I guess they lost patience and straight up started to ban people who misbehave continuously
[Reddit thread](https://www.reddit.com/r/KissAnime/comments/8uycz1/admin_is_banning_users_who_are_blocking_ads/)

**Comment by okiehsch** [comment]
Well, what do you think uBlock can do?
It can't change your IP.

I just checked, after my IP was banned changing it fixed the issue for me, so I suggest you do the same.

**Comment by SakhJack** [comment]
I don't expect you to do anything, just a heads up

**Comment by uBlock-user** [comment]
No IP bans on my end. Works fine, whatever you extensions you're using disable and then only keep uBlock Origin enabled.

**Comment by okiehsch** [comment]
I only have uBlock enabled.
![image](https://user-images.githubusercontent.com/16838044/42122952-130aa2d0-7c4a-11e8-9d9e-622a1dbc9ac2.png)

**Comment by SakhJack** [comment]
Ban is permanent, meaning they don't lift it if you stop using adblock apps, like normal companies do
I'm just gonna switch to different streaming service, since that's what they want anyway apparently 
Just because something is free it doesn't have to come with inconvenience as a price

**Comment by uBlock-user** [comment]
@okiehsch Then they're mass banning select IP blocks, based on false positives. 

Use a VPN or Chrome Data Saver extension on Chrome.

**Comment by uBlock-user** [comment]
lol now I'm banned too, yup this is a mass ban.

**Comment by uBlock-user** [comment]
Working again??

![](https://i.gyazo.com/2e6e626b42095eb98e4d137ff5a3f10d.png)

**Comment by uBlock-user** [comment]
This appears to be the ban script


```
$(function () {
--
  | setTimeout('YANMKABFYWRW()', 500);
  | });
  |  
  | function YANMKABFYWRW() {
  | if (!$('#adsIfrme10').is(":visible")) {
  | $.ajax(
  | {
  | type: "POST",
  | url: "/Special/TemporaryBlockZ",
  | success: function (message) {
  |  
  | }
  | });
  | }
  | }
```

**Comment by uBlock-user** [comment]
@SakhJack Add `||kissanime.ru/*/TemporaryBlockZ^$xmlhttprequest` and try again, it should work now.

**Comment by SakhJack** [comment]
But for how long is the question

if I have to create new rules and change my IP every other day, it's just too much trouble

**Comment by okiehsch** [comment]
As long as `||kissanime.ru/*/TemporaryBlockZ^$xmlhttprequest` is not part of any `uBlock-filter` list, it should work, kissanime clearly was watching this repo and changed their detection script accordingly, see https://github.com/uBlockOrigin/uAssets/issues/2704

After I added https://github.com/uBlockOrigin/uAssets/commit/f0ebe25fd581ec7fa13ab8fb45b3381042f8304f they started the IP-bans.

**Comment by uBlock-user** [comment]
> But for how long is the question

This is the game of cat and mouse, it only stops until one gives up, otherwise never. It's upto to you. Ofcourse, the wise choice would be to move away and find another alternative which is less anal about their ads getting blocked or not.

**Comment by SakhJack** [comment]
Here we go again
![again](https://user-images.githubusercontent.com/10335530/42335724-4b2b791a-804f-11e8-8a25-89ef398cc889.PNG)

**Comment by okiehsch** [comment]
`kissanime.ru##script:inject(abort-current-inline-script.js, $, elem.hide)`

**Comment by runboy93** [comment]
https://raw.githubusercontent.com/Yumire/kiss-filters/master/filters.txt

Obviously you need change IP first, then use this filter.

**Comment by uBlock-user** [comment]
To unhide the Alpha and Beta players,

```
kissanime.ru###my_video_1:style(display: block !important;)
kissanime.ru###my_video_1_html5_api:style(display: block !important;)
```

**Comment by uBlock-user** [comment]
Disable AA - `kissanime.ru##script:inject(setTimeout-defuser.js, YANMKABFYWRW)`

**Comment by uBlock-user** [comment]
new popup/under - `kissanime.ru##+js(abort-current-inline-script.js, parseInt, incrementClicks)`

**Comment by C0nw0nk** [comment]
Not possible to block all POST requests to that url: "/Special/*

Breaks the auto ban Issue.

**Comment by MonfGeiger** [comment]
I am having this same problem (have not been perma IP Banned yet, thankfully enough)

My version of Chrome (Stable) is 69.0.3497.100, im using the dev version of ublock origin from the google extensions store (v1.17.1b1) along with nano defender from the same store (configured to link with origin), windows 10 pro 1803 (OS Build 17134.320), and a number of other extensions, and I think I isolated the problem

I turned off "usable in incognito mode" for 3 extensions I thought were the culprit: poper blocker, privacy possum, and nano defender, and I disabled ublock origin's nano filters, and unset the userResourcesLocation in the advanced settings. I also got rid of any filters in "my filters" relating to kissanime; one by one, I re-enabled incognito mode starting with poper blocker (no ads, kissanime unbroken), privacy possum (no ads, kissanime still unbroken), and re-enabled everything related to nano defender, and surprise surprise, kissanime is HATING nano defender

here's a zip file with screenshots and log if it helps
[Kissanime screenshot and logs.zip](https://github.com/uBlockOrigin/uAssets/files/2470618/Kissanime.screenshot.and.logs.zip)

**Comment by okiehsch** [comment]
`http://kissanime.ru/Anime/JoJo%60s-Bizarre-Adventure-Golden-Wind/Episode-004?id=151444&s=default`
@Zetawilk add 
````
||kissanime.ru^$xmlhttprequest,first-party
kissanime.ru##script:inject(abort-on-property-read.js, InitCloseButton)
````
to your filter list, works on my end.
If you are already "banned" you may have to change your IP.

**Comment by ShockRocky** [comment]
Hey @SakhJack , it is nice of you to report the issue, I see you are a fellow anime fan as well, if you have a static IP assigned by your ISP and you don't use a proxy/VPN, I would suggest you to use this anime site instead of kissanime, which is gogoanimes :- https://gogoanimes.co/

It always is up to date with the latest anime titles and episodes, and has almost all anime ever released, plus it works well with adblockers and script blockers such as ublock origin and umatrix[have to find the right cdns to unblock, but once you get it right, you are set, just don't forget to make a offline backup of the script permissions] .

Sorry if I have gone a little off topic, but if any website does this to it's users, it is better to abandon it for better and go look for a better alternative, which I hope I have provided for the OP .

**Comment by SakhJack** [comment]
@ShockRocky I appreciate the suggestion and I used the website in the past, but found it laggy and interface is kinda bad in my opinion 
I switched to [masterani.me](masterani.me) ever since this issue, and never turned back
You always know when new episodes comes up in your "watching list", quality is always 1080p and everything is smooth

P.S. I don't follow this anymore so mods can close if it's no longer an issue, sorry for flood

**Comment by ShockRocky** [comment]
> @ShockRocky I appreciate the suggestion and I used the website in the past, but found it laggy and interface is kinda bad in my opinion
> I switched to [masterani.me](masterani.me) ever since this issue, and never turned back
> You always know when new episodes comes up in your "watching list", quality is always 1080p and everything is smooth
> 
> P.S. I don't follow this anymore so mods can close if it's no longer an issue, sorry for flood

Thanks, I like this one better than gogoanimes :)

**Comment by uBlock-user** [comment]
kissanime added another check for anti-adblock. New filter --

`kissanime.ru##+js(setTimeout-defuser.js, /YANMKABFYWRW|YANABWEKA/)`

**Comment by Freekystar** [comment]
Most internet providers change your IP-address every <period of time> and with VPN it really is an ineffective and intrusive method of preventing people accessing your site. 

I find twist.moe a better website for watching anime, completely ad-free and no registration or anything required.

**Comment by mapx-** [comment]
It seems to work, at least now.
Closing.
