### ISSUE TITLE
Adguard safari filter list breaks youtube video ad blocking

### ISSUE THREAD

**Issue by ethus3h** [uBlockOrigin/uAssets#272]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.youtube.com/watch?v=hWLDRqOj_V0 (depends on what Google account is logged into)

### Describe the issue

Adguard Safari filter list contains the rule `@@||youtube.com/get_video_info?`, which allows video adverts in YouTube for some accounts. Consequently, I'd suggest adding a warning to the list description on the list subscriptions page.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Firefox 45.6.0
- uBlock Origin version: 1.10.4

### Settings

- see attached: 
[my-ublock-backup_2017-01-20_22.07.56.txt](https://github.com/uBlockOrigin/uAssets/files/720868/my-ublock-backup_2017-01-20_22.07.56.txt)

**Comment by IDKwhattoputhere** [comment]
I suppose by `Adguard Safari filter list` you mean the `Adguard Mobile Safari` filter list listed on `filterlists.com`? I'd suggest you [contact](https://filterlists.com/contribute/) the author of `filterlists.com`, @collinbarrett, instead.

**Comment by ethus3h** [comment]
Oh, it's in my custom lists subsection. I thought the custom ones were just in the text box. I kinda feel dumb now, sorry for the bother. Thanks for the help and for spotting that, @IDKwhattoputhere :)

**Comment by Alex-302** [comment]
@ethus3h that filter is for Safari only
