### ISSUE TITLE
adfloz.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2722]
URL(s) where the issue occurs

`http://adfloz.com/EQbiq2`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by IThinkIAmCool** [comment]
parked domain according to `http://adfloz.com/`

**Comment by IThinkIAmCool** [comment]
https://github.com/uBlockOrigin/uAssets/pull/9228/commits/1155293d7a29f115fb92fcba3ee06dd0aae5289e

**Comment by mapx-** [comment]
`adfloz.co`
