### ISSUE TITLE
Ublock caught by adblock blocker on cwtv.com

### ISSUE THREAD

**Issue by badtzmaru** [uBlockOrigin/uAssets#273]
### URL(s) where the issue occurs

`[http://www.cwtv.com/shows/the-flash/the-present/?play=d08d09a0-6379-428e-b09e-0d5ab844c272]`

### Describe the issue

[When attempting to watch a video on cwtv.com/ uBlock is detected, and the video will not play without disabling the extension.]

### Screenshot(s)

[http://i.imgur.com/wrYwJua.png]

### Versions

- Browser/version: [Google Chrome Version 55.0.2883.87 m]
- uBlock Origin version: [1.10.4]

### Settings

- [default]

### Notes

[I tried disabling only certain types of ads, but it still catches it if uBlock is enabled at all!]

**Comment by mapx-** [comment]
add
`cwtv.com##script:inject(abort-on-property-write.js, wallConfig)`

**Comment by okiehsch** [comment]
I would add the proposed filter if I could reproduce,
unfortunately I can't even access the mainsite 
![cwtv](https://cloud.githubusercontent.com/assets/16838044/22263579/395a0040-e275-11e6-89a8-1f50fc573c90.PNG)
so some feedback would be appreciated.

**Comment by badtzmaru** [comment]
Would you mind trying with a proxy or with a different browser? I can access it fine.

**Comment by mapx-** [comment]
@badtzmaru , did you test the filter ?

**Comment by okiehsch** [comment]
Same result with Chrome Firefox and Edge.
I can access the site with a US proxy but the video won't load.
I only need to know if the filter works and nothing is broken.

**Comment by mapx-** [comment]
it's working fine (tested using a us shell server). The video loads in 1-2 minutes
