### ISSUE TITLE
skylinewebcams.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2735]
URL(s) where the issue occurs

`http://www.skylinewebcams.com/es/webcam/maldives/lhaviyani-atoll/kurendhoo/kuredu-island.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by ghost** [comment]
Ad leftover

<img width="1670" height="813" alt="Image" src="https://github.com/user-attachments/assets/649e8821-60f4-4f43-8ea7-fe4e9f74382d" />
