### ISSUE TITLE
RapidVideo: Anti-Addblock

### ISSUE THREAD

**Issue by Hexoft** [uBlockOrigin/uAssets#2739]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

"``http://kissanime.ru/Anime/Steins-Gate-0/Episode-001?id=144735&s=rapidvideo``"

### Describe the issue

Rapid video is providing an anti addblock page in the video which only just came into affect in the last 30 minutes or so as of posting this. Reading to disable addblock or pay for premium.
### Screenshot(s)

![image](https://user-images.githubusercontent.com/26858826/42166921-62ed8d4c-7e04-11e8-9d27-a82c11c26ed8.png)

### Versions

- Browser/version: Version 67.0.3396.99 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.16.12

### Settings
uBlock filters​​​​​6,730 used out of 6,731​​​​
uBlock filters – Annoyances​​​​​186 used out of 186​​​​
uBlock filters – Badware risks​​​​​14 used out of 14​​​​
uBlock filters – Experimental​​​​​6 used out of 6​​​​
uBlock filters – Privacy​​​​​96 used out of 97​​​​
uBlock filters – Resource abuse​​​​​259 used out of 261​​​​
uBlock filters – Unbreak​​​​​481 used out of 481​​​​
Ads (4/4)
Adblock Warning Removal List​​​​​441 used out of 452​​​​
Adguard Base Filters​​​​​17,248 used out of 18,223​​​​
Adguard Mobile Filters​​​​​1,882 used out of 2,373​​​​
EasyList​​​​​82,521 used out of 83,087​​​​
Privacy (3/3)
Adguard Spyware Filters​​​​​2,622 used out of 6,475​​​​
EasyPrivacy​​​​​14,031 used out of 15,218​​​​
Fanboy’s Enhanced Tracking List​​​​​2,364 used out of 2,405​​​​
Malware domains (4/4)
Malvertising filter list by Disconnect​​​​​393 used out of 3,643​​​​
Malware Domain List​​​​​1,115 used out of 1,131​​​​
Malware domains​​​​​23,933 used out of 23,950​​​​
Spam404​​​​​6,534 used out of 6,534​​​​
Annoyances (5/5)
Adguard’s Annoyance List​​​​​11,561 used out of 13,528​​​​
Fanboy’s Annoyance List​​​​​10,221 used out of 40,582​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​68 used out of 68​​​​
Fanboy’s Cookiemonster List​​​​​10,267 used out of 10,269​​​​
Fanboy’s Social Blocking List​​​​​20,032 used out of 20,060​​​​
Multipurpose (4/4)
Dan Pollock’s hosts file​​​​​9,941 used out of 13,530​​​​
hpHosts’ Ad and tracking servers​​​​​41,649 used out of 45,720​​​​
MVPS HOSTS​​​​​12,111 used out of 12,615​​​​
Peter Lowe’s Ad and tracking server list​​​​​2,626 used out of 2,630​​​​

### Notes

Tried disabling and enabling different filters to no difference.
Looked at logger to see what appears to be where they've implemented it but could be wrong-

![image](https://user-images.githubusercontent.com/26858826/42167103-e435ac5e-7e04-11e8-8c74-93425e0f1cc0.png)

**Comment by ringosham** [comment]
It's not a kissanime issue, it's just rapidvideo.

**Comment by gavbn** [comment]
No,see their reddit page,it seems that they are blocking anyone who uses adblock on their and they ban them

**Comment by ringosham** [comment]
The above case only covers rapidvideo and it has nothing to do with Kissanime. The IP ban is another issue.

**Comment by Hexoft** [comment]
Sorry, I wasnt trying to insinuate it was a kiss anime problem just that it occurred for me first on the site.
I'm aware its just a rapid video issue and all I wanted to do was highlight it as I hadn't seen anyone else post anything regarding it yet.

**Comment by zaphodbeebblebrox** [comment]
Better example link: `https://www.rapidvideo.com/e/FRY04YDTS8`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1883b2e383c6ca691950e516d140e05cdf001088
