### ISSUE TITLE
Blocking the Web browser unexpected issuu.com/ when I open a document

### ISSUE THREAD

**Issue by Albert456** [uBlockOrigin/uAssets#274]
Replace the bracketed [...] placeholders with your own information.

### `https://issuu.com/`
https://issuu.com/vodafonenovedades/docs/epaper_revista_94_cast_

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Web issuu.com when I open a document in full screen, the tool bar below, hidden and can not recover.

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### [removed URL because hosted on dubious site]

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Google Chrome, Version 55.0.2883.87 m (64-bit)
- uBlock Origin version: uBlock Origin 1.10.4

### Settings

Your custom filters (if any)

    @@||iptvbin.com^$generichide
    @@||sport.es^$generichide
    @@||elperiodico.cat^$generichide
    @@||pagead2.googlesyndication.com^$domain=iptvbin.com
    @@.png#$domain=iptvbin.com
    ||rolinda.work
    http://s.click.aliexpress.com/e/bMbmIAqvf

### Notes

With Firefox without any ad blocker, I have the same problem.

**Comment by gorhill** [comment]
I removed your image link to tinypic. Post an image here, not on a garbage image hosting site.

> With Firefox without any ad blocker, I have the same problem

So why would you think the issue is a filter issue rather than a site issue?

**Comment by Albert456** [comment]
Issuu.com with the Chrome browser works very badly. No problem is uBlock forgive.
