### ISSUE TITLE
filecrypt.cc overblocking (Click'n Load & dlc buttons filtered)

### ISSUE THREAD

**Issue by salim-b** [uBlockOrigin/uAssets#2742]
### URL(s) where the issue occurs

`https://filecrypt.cc/Container/15C1059246` (after captcha is solved)

### Describe the issue

The relevant buttons to get the download links are hidden by the cosmetic filter `##.buttons`. 

### Screenshot(s)

I've framed the buttons in yellow which are hidden; additionally the buttons which are actually relevant are framed in red.

![bildschirmfoto vom 2018-07-02 16-17-56](https://user-images.githubusercontent.com/20040931/42169657-a368433e-7e14-11e8-8668-5a4a20ec4e80.png)

### Versions

- Browser/version: Firefox 60.0.2 | Chromium 66.0.3359.181
- uBlock Origin version: 1.16.12 | 1.16.10

### Settings

- I've enabled all language-agnostic filter lists which are installed by default + Easylist Germany

### Notes

Adding the following exception to _My filters_ solves the issue (screenshot was taken after doing so):

```
filecrypt.cc#@#.buttons
```

**Comment by zaphodbeebblebrox** [comment]
Your link died, can you provide another example?

**Comment by okiehsch** [comment]
Working link: `https://filecrypt.cc/Container/D3BBE2CBE4.html`

**Comment by Maxxee** [comment]
The filters still are breaking the site.

**Comment by mapx-** [comment]
Provide details: what's broken, specific test page, browser version, uBo version.
Did you test using only the default setup ? (and no other blocking extension)

**Comment by Maxxee** [comment]
The second link in this issue is still valid: https://filecrypt.cc/Container/D3BBE2CBE4.html

Having the built-in filter list "uBlock filters" enabled removes the two buttons in the upper section, the very important one of them is called "Click'n Load".

Disabling the filter list  "uBlock filters" OR adding filecrypt.cc to the whitelist shows the buttons.

**Comment by mapx-** [comment]
ok, removed

**Comment by zaito-fr** [comment]
Same error i can't downlaod the DLC with ublock origin actived

**Comment by stephenhawk8054** [comment]
@Zaitooo Please give exact link where the issue occurs and point exactly to where the `DLC` is.

**Comment by zaito-fr** [comment]
> [@Zaitooo](https://github.com/Zaitooo) Please give exact link where the issue occurs and point exactly to where the `DLC` is.

URL : https://filecrypt.cc/Container/5E422C9959.html
The point = ##.dlcdownload

**Comment by stephenhawk8054** [comment]
@Zaitooo Please share your troubleshooting information while reproducing the issue.

**Comment by zaito-fr** [comment]
<details>

```yml
uBlock Origin: 1.69.0
Firefox: 147
filterset (summary):
 network: 180927
 cosmetic: 47928
 scriptlet: 26266
 html: 3052
listset (total-discarded, last-updated):
 default:
  user-filters: 10-0, never
  ublock-filters: 44469-73, now
  ublock-badware: 10602-30, now
  ublock-privacy: 3617-2, now
  ublock-unbreak: 2789-1, now
  ublock-quick-fixes: 453-13, now
  easylist: 93748-159, now
  easyprivacy: 55401-29, now
  urlhaus-1: 26140-5, now
  plowe-0: 3504-1007, now
  FRA-0: 19583-271, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 534 ms (selfie)
 maxAssetCacheWait: 49 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  filecrypt.cc: 3
  filecrypt.to: 16
 extended:
  ##img[style^="display:"]
  ##[class*="adb"]
  ##div:has(> [href*=".html"])
  ###ad-728-90
  ##+js(remove-attr, onclick, button[id][onclick*=".html"])
  ##+js(set-constant, isAdblock, false)
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
```

</details>

> [@Zaitooo](https://github.com/Zaitooo) Please share your troubleshooting information while reproducing the issue.

**Comment by stephenhawk8054** [comment]
Test

```adb
*$script,3p,from=filecrypt.cc,badfilter
```

**Comment by zaito-fr** [comment]
> Test
> 
> *$script,3p,from=filecrypt.cc,badfilter

It works thanks mate
