### ISSUE TITLE
k-gen.fr [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2746]
URL(s) where the issue occurs

`http://k-gen.fr/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by smed79** [comment]
`||k-gen.fr/wp-content/uploads/$script`

**Comment by garry-ut99** [comment]
Many ad placeholders due to `ghide` from "uBlock filters":  [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217257311-63ec685e-bdf7-4850-95ad-dc3a9992fbc5.png)
