### ISSUE TITLE
Rapidvideo Anti-Adblock

### ISSUE THREAD

**Issue by Luxuride** [uBlockOrigin/uAssets#2747]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
- `https://otakustream.tv/anime/shakugan-no-shana/episode-11/`

### Describe the issue

- Message "It seems you are using Adblocker, please disable it. You can buy Premium Account to continue, while using it." jups into video window.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/39569690/42177727-1d0efbce-7e2e-11e8-9f90-b37f1e284311.png)

### Versions

- Browser/version: Opera 53.0.2907.99
- uBlock Origin version: uBlock Origin 1.16.6

### Settings

- No changes

### Notes
- Video is completely gone, there is only that message.

**Comment by KiLL4FuNK** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/2739

**Comment by ringosham** [comment]
Actually no, they updated the site to anti adblock again.
I can confirm that it doesn't work with updated filters.

**Comment by ghajini** [comment]
Reversed

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1883b2e383c6ca691950e516d140e05cdf001088
