### ISSUE TITLE
yabiladi.com unblocked ads (only with uBlock Origin, not Adblock Plus)

### ISSUE THREAD

**Issue by maxxyme** [uBlockOrigin/uAssets#275]
### URL(s) where the issue occurs

`http://www.yabiladi.com/forum/bible-falsifiee--docteur-theologie-bart-80-7736627.html`

### Describe the issue

Some ads coming from Adikteev and/or adsafeprotected.com (according to maintainer: https://forums.lanik.us/viewtopic.php?f=91&t=35157 ) do not seem to be blocked when using uBlock Origin.
This does not happen when using Adblock Plus 1.12.4 with the specified filter list (see below).

### Screenshot(s)

![screenshot-www yabiladi com-2017-01-23-10-19-58](https://cloud.githubusercontent.com/assets/60419/22198918/f1fab75c-e158-11e6-9926-bba3f3c1ef7c.png)

### Versions

- Browser/version: Google Chrome Version 55.0.2883.87 m
- uBlock Origin version: uBlock Origin v1.10.4

### Settings

Checked:
- Hide placeholders of blocked elements
- Show the number of blocked requests on the icon
- Make use of context menu where appropriate
- Disable pre-fetching (to prevent any connection for blocked network requests) 
- Disable hyperlink auditing 

3rd-party filters:
- Parse and enforce cosmetic filters
only list:
- FRA: EasyList Liste FR `https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt`

### Notes

1. Go to the specified URL
2. Scroll down a little bit and see an unblocked ad after post #2.

**Comment by gorhill** [comment]
Can't reproduce.

> only list:
> FRA: EasyList Liste FR `https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt`

You have **only** "FRA: EasyList Liste FR‎" selected?

**Comment by maxxyme** [comment]
Yes, I only let this list because I wanted to properly isolate the problem.
Under Adblock Plus, no ad. In uBlock, ad.

However, the thing is I'm a French user, and those are French ads. So maybe the fact you're not, may not make the ads display.

**Comment by maxxyme** [comment]
Here's what's not filtered:
![screenshot-cjpalhdlnbpafiamejdnhcphjbkeiagm-2017-01-23-14-42-31](https://cloud.githubusercontent.com/assets/60419/22206123/3ea09b28-e17a-11e6-92c7-424131a2db84.png)

**Comment by gorhill** [comment]
These ads are blocked by EasyList. You disabled EasyList, hence the ads are no longer blocked. EasyList is selected by default in ABP. Disable EasyList in ABP and you will get the same issue.

Also, _uBlock filters_ should not be disabled, it contains optimal filters for uBO which takes care of a lot of filtering issues regardless of the locale.

**Comment by maxxyme** [comment]
What?!
"FRA: EasyList Liste FR‎" IS the EasyList plus additional filters from French targeted-audience websites.

And even if I let the uBlock filters checked, it doesn't change anything: ads are still shown.

But now I get it: in uBlock the lists are SPLIT, not in ABP..!!!!

**Comment by gorhill** [comment]
> in uBlock the lists are SPLIT, not in ABP..!!!!

Yes, everything under Regional is complementary to EasyList -- no point having EasyList duplicated in all the regional lists. When uBO is first installed, the filter lists automatically selected are optimal, no fiddling around required.

**Comment by SMed79** [comment]
@maxxyme the issue comme from ou side, adikteev ads is correctly blocked by uBO.

* yabiladi.com http://i.imgur.com/xbPTficg.jpg

![capture](https://cloud.githubusercontent.com/assets/1873139/22216595/fec134e2-e19f-11e6-9fb8-15555e47880c.PNG)

**Comment by gorhill** [comment]
> yabiladi.com http://i.imgur.com/xbPTficg.jpg

C'est quoi l'application pour imprimer tout le contenu d'une page?

**Comment by SMed79** [comment]
1. Depuis Firefox 32 il ya un [bouton capture d'écran](http://i.imgur.com/rQTpWyH.png) de la page entière dans les outils de dev (F12).

https://developer.mozilla.org/fr/docs/Outils/Outils_boite_%C3%A0_outils#Outils_suppl.C3.A9mentaires

2. Pour prendre une capture d'écran de la page entière et la uploader directement sur imgur: 

Ouvrir la barre de développement (Shift+F2) et taper la commande: `screenshot --fullpage --imgur`

`--delay` : Capturer l'image après x secondes.
`--fullpage` Capture d'écran de la page entière.
`--selector` : Récupérer un élément à partir de son sélecteur CSS.
`--chrome` : Avoir une capture avec une fenêtre de navigateur autour.
`--clipboard` : Stocker l'image dans le presse-papier
`--imgur` : Envoyer l'image à imgur.com
`--dpr` : Définit un rapport de pixel de l'appareil
