### ISSUE TITLE
Rapidvideo detects ublock origin

### ISSUE THREAD

**Issue by Kotosif** [uBlockOrigin/uAssets#2750]
### URL(s) where the issue occurs

`https://www.rapidvideo.com/e/FRY04YDTS8`

### Describe the issue
Rapidvideo detects UBlock Origin and denies watching. Shows an request to turn off Ad-Blocker

### Screenshot(s)

[Screenshot](https://i.imgur.com/v5263F5.png)

### Versions

- Browser/version: Firefox 60.0.2 (64-bit)
- uBlock Origin version: 1.16.12

**Comment by mapx-** [comment]
update ublock filters

**Comment by okiehsch** [comment]
To avoid numersous rapidvideo related issues this one will remain open for now.

**Comment by ghajini** [comment]
https://www.reddit.com/r/KissAnime/comments/6me2e3/psa_do_not_use_rapidvideo/

**Comment by ghajini** [comment]
`https://kissanime.ru/Anime/Tensei-shitara-Slime-Datta-Ken/Episode-010?id=152867&s=rapidvideo`
error- connection was reset
![screenshot 68](https://user-images.githubusercontent.com/20338483/49722058-cde73180-fc89-11e8-89ff-e804675cf5b6.png)
