### ISSUE TITLE
wicr.me [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2751]
URL(s) where the issue occurs

`http://wicr.me/Q3f1K`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by KiLL4FuNK** [comment]
ADS

fill captchas

**Comment by KiLL4FuNK** [comment]
Redirects

`http://wicr.me/1em0iv`

Continue ----- Get Link

**Comment by lain566** [comment]
Website redirects, click anywhere when the countdown appears.
`http://wicr.me/1em0iv`

**Comment by lain566** [comment]
Popups again, click on `Get Link`

**Comment by lain566** [comment]
There's a popup.

**Comment by mapx-** [comment]
Does this filter work for you ?
`wicr.me##+js(remove-attr.js, action)`

**Comment by okiehsch** [comment]
> Does this filter work for you ?
`wicr.me##+js(remove-attr.js, action)`

No, if you remove cookies the popup is still there.


I end up with the same domain no matter what.
To illustrate go to
`http://wicr.me/93tmit`
I actually end up at `facebook.com` if I trigger the popup or by clicking "Click here to continue".

Can you reproduce?

**Comment by mapx-** [comment]
wicr => wikiall => FB

without the action filter => wikimotors => a text page, no waiting, no links

So, it seems the action filter skip the wikimotors crap and bring you to the counting page

**Comment by lain566** [comment]
Cosmetic filter works for me
`wicr.me###overly`

**Comment by mapx-** [comment]
yes, even simpler using lain566 filter
