### ISSUE TITLE
ouo.press [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2752]
URL(s) where the issue occurs

`https://ouo.press/AwMdVa`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by KiLL4FuNK** [comment]
fill captchas

**Comment by KiLL4FuNK** [comment]
ads

fill captchas

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by okiehsch** [comment]
Don't see anything obvious, can you point to the ads?

**Comment by lain566** [comment]
@okiehsch When you click anywhere on the page after solving the CAPTCHA, the site tries to open a popup and show ad.

`https://ouo.press/h7z71i`

**Comment by ghajini** [comment]
`https://ouo.press/U8yWyl`

`||ouo.press/sw-mav.js$important`

**Comment by ghajini** [comment]
@mapx-

**Comment by ghajini** [comment]
Last added filter invalid now

`||ouo.press/sw*.js$important`

**Comment by ghajini** [comment]
`http://ouo.press/Gg6dZm9`
Popup ads in last page

**Comment by ghajini** [comment]
This is extra script served to firefox android &not desktop browsers, blocking it stops the popup ads
`http://ouo.press/js/jbitly.js?2`
![IMG_20201216_115051](https://user-images.githubusercontent.com/20338483/102312681-29dda280-3f95-11eb-9fd3-74df54d8f61e.jpg)

**Comment by okiehsch** [comment]
`ouo.*##+js(aopr, AaDetector)`
should also disable the popup.

**Comment by ghajini** [comment]
Yes
