### ISSUE TITLE
ouo.io [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2754]
URL(s) where the issue occurs

`http://ouo.io/5i5rGL`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.10

Settings

Default

**Comment by KiLL4FuNK** [comment]
fill captchas

**Comment by lain566** [comment]
@okiehsch Can you reproduce the popup? try these urls

```
http://ouo.io/6cRmEJ
https://ouo.io/0Lj85G
http://ouo.io/mIlCLHw
https://ouo.io/6NRkDo
http://ouo.io/YSVhcF
```

**Comment by okiehsch** [comment]
Tried all of them without any popups on my end.
