### ISSUE TITLE
ninjakiwi.com

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#2755]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
[www.ninjakiwi.com]

### Describe the issue
Ads show up anywhere on the mentioned website, they do not get blocked at all.

### Versions
Browser version is firefox quantum 61.0
Ublock origin version is 1.16.12
### Settings
Settings are all default

### Notes
I haven't done any investigation work, as i don't really know how to do so.

**Comment by okiehsch** [comment]
Add
`||cdn.nkstatic.com/images/BTD6_Site-skins.jpg$image`
to your filter list.

**Comment by smed79** [comment]
or
```
ninjakiwi.com##.local-skin
||cdn.nkstatic.com/images/*-skins.
```
