### ISSUE TITLE
Anti-Adblock factsreporter.com

### ISSUE THREAD

**Issue by AlbertJ1982** [uBlockOrigin/uAssets#2758]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

factsreporter.com

### Describe the issue
The website started to detect my extension and bothers me with a website i dont want to see.  

### Screenshot(s)

just try to open factsreporter.com

### Versions

- Browser/version: FF 61
- uBlock Origin version: 1.16.12

### Settings

- none

### Notes

could you update the filters to stop that insult?

**Comment by okiehsch** [comment]
I can't reproduce with a default setup, only way to reproduce is to disable `uBO-filters` on my end.

**Comment by smed79** [comment]
@AlbertJ1982 test 
```
factsreporter.com##script:inject(set-constant.js, AlobaidiDetectAdBlock, true)
```
or
```
factsreporter.com##script:inject(set-constant.js, window.AlobaidiDetectAdBlock, false)
```

**Comment by okiehsch** [comment]
@smed79 so you can reproduce?

**Comment by smed79** [comment]
Sorry, no anti adblock with the default setup.
I thought that probably the anti adblock is geo conditional and I wanted the user to test the filter.

**Comment by okiehsch** [comment]
I can reproduce if I block `https://factsreporter.com/wp-content/plugins/detect-adblock/js/ads.js`, but 
`@@/wp-content/plugins/detect-adblock/js/ads.js$script,first-party` is already part of `uBO-filters`, so
this request is allowed by default.

**Comment by smed79** [comment]
Ok, thank for your time.
