### ISSUE TITLE
javascript popup

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#276]
### URL(s) where the issue occurs

`https://uplod.ws/032o3lgltvo2`

### Describe the issue
1. go to above link 
2. click anywhere in page
3.a popup opened of 
`javascript:window opener=            `

4 a series of popups open as per shown in logger....

### Screenshot(s)

![screenshot 109](https://cloud.githubusercontent.com/assets/20338483/22214230/eec1acee-e1bc-11e6-8c98-196b13ba5f9f.png)

### Versions

- Browser/version: 
                                `mozilla firefox 50.1.0`
- uBlock Origin version: 1.10.4
### Settings

-  uBO's default settings+adblock warning removal list+antiadblock killer

### Notes

javascript popups should be closed

**Comment by ghajini** [comment]
also whats this 
`ads by adstract`
https://onhax.me/glary-utilities-pro-2
![screenshot 111](https://cloud.githubusercontent.com/assets/20338483/22214618/482a69e6-e1be-11e6-997c-3878fa36c6de.png)

**Comment by okiehsch** [comment]
The popup issue is fixed in `uBO 1.10.5rc0`.

**Comment by gorhill** [comment]
The popup `javascript:window.opener=null;setTimeout...` will be properly closed by the EasyList filter `javascript:*settimeout*location.href$popup` with uBO 1.10.5rc0 and beyond. uBO 1.10.5rc0 is available on dev channel on AMO. Another solution is to just use the no-popups switch for that site: https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups

**Comment by gorhill** [comment]
> also whats this

Report to EasyList maintainer please: `onhax.me###top-promo-dload`.

**Comment by ghajini** [comment]
i can reproduce here javascript popup 
http://q.gs/CYuvS
![screenshot 118](https://cloud.githubusercontent.com/assets/20338483/22626488/a10e9256-ebd4-11e6-8bf1-ed5941ca223b.png)

**Comment by SMed79** [comment]
@ghajini 
> i can reproduce here javascript popup
> ublock origin 1.10.6

Already fixed in uBO 1.10.7rc4 https://addons.mozilla.org/firefox/addon/ublock-origin/versions/beta

![uBO 1.10.7rc4](https://cloud.githubusercontent.com/assets/1873139/22627002/bcd4a9aa-ebb9-11e6-8b8f-1cf2fbac6269.png)

**Comment by ghajini** [comment]
it was previously fixed in both 1.10.5rc0 and 1.10.6 as per gorhill comment.
it was present on 1.10.6.....
yes latest beta again fixes issue

**Comment by gorhill** [comment]
It's fixes in dev build, not in stable. 1.10.5rc0 is not stable.
