### ISSUE TITLE
serialomaniak.pl

### ISSUE THREAD

**Issue by lukjan32** [uBlockOrigin/uAssets#2764]
no icons are available for articles under the text, on the site serialomaniak.pl

![1](https://user-images.githubusercontent.com/17565773/42278614-b6819a1e-7f9b-11e8-8ff8-0628ebc18d8b.jpg)

as I add to the exceptions

![2](https://user-images.githubusercontent.com/17565773/42278790-29f870b2-7f9c-11e8-9f84-c9860a62ad13.jpg)

opera 54, ublock origins

**Comment by zaphodbeebblebrox** [comment]
Polish sites should be reported to MajkiIT/polish-ads-filter. @MajkiIT

**Comment by hawkeye116477** [comment]
@zaphodbeebblebrox It's issue with uBO Privacy.

**Comment by mapx-** [comment]
not only that 1 (for me)

test
```
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org,badfilter
||addthis.com/*/addthis_widget.js$script,badfilter
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~serialomaniak.pl
||addthis.com/*/addthis_widget.js$script,domain=~serialomaniak.pl
@@||addthis.com/live/$script,domain=serialomaniak.pl
@@||addthisedge.com/live$script,domain=serialomaniak.pl
```

**Comment by lukjan32** [comment]
please add

**Comment by krystian3w** [comment]
No works for my side in Opera 54 and uBO 1.16.6.

Show when unlock `xmlhttprequest` from `m.addthisedge.com`:

```
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org,badfilter
||addthis.com/*/addthis_widget.js$script,badfilter
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~serialomaniak.pl
||addthis.com/*/addthis_widget.js$script,domain=~serialomaniak.pl
@@||addthis.com/live/$script,domain=serialomaniak.pl
@@||addthisedge.com/live$script,domain=serialomaniak.pl
@@||m.addthisedge.com/live/*$xmlhttprequest,domain=serialomaniak.pl
````

**Comment by lukjan32** [comment]
as I added it works, please add to the filters

**Comment by okiehsch** [comment]
This will not be fixed in `uAssets`.

Quote from gorhill:
"The hostnames currently excluded (he means `missingkids.com` and `missingkids.org`) are there because of [severe site breakage](https://github.com/uBlockOrigin/uAssets/issues/1713). If the breakage is only the Addthis widget failing to load, I rather not have the fix in uBO's filter lists -- or else the logical consequence is to remove addthis.com from "uBlock filters -- Privacy", which is not something I see as a good thing."

**Comment by lukjan32** [comment]
will not be added to the filters?

**Comment by mapx-** [comment]
@MajkiIT

**Comment by lukjan32** [comment]
ok

**Comment by okiehsch** [comment]
@lukjan32 the `uBO-privacy` filters causing this issue will not be changed by `uAssets`, if the polish list wants to override them it can by adding
````
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org,badfilter
||addthis.com/*/addthis_widget.js$script,badfilter
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~serialomaniak.pl
||addthis.com/*/addthis_widget.js$script,domain=~serialomaniak.pl
````

**Comment by krystian3w** [comment]
No works in Opera 54.

Chromium allow only add:

`@@||addthisedge.com/live$script,xmlhttprequest,domain=serialomaniak.pl` to your rules.

**Comment by okiehsch** [comment]
The filters I mentioned only fix the `uBO-privacy` part of the issue, for the `EasyPrviacy` part you will also need
````
@@||addthis.com/live/$script,domain=serialomaniak.pl
@@||addthisedge.com/live$script,xmlhttprequest,domain=serialomaniak.pl
````
as far as I can see.

**Comment by MajkiIT** [comment]
@lukjan32 @mapx- @hawkeye116477 @krystian3w @okiehsch Thanks
https://github.com/MajkiIT/polish-ads-filter/commit/e938c1bfb8a584d864484c1191dd67c5566e63da#diff-711027ed0794992ae3b8710d874f3df7

**Comment by lukjan32** [comment]
thank
