### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by lukjan32** [uBlockOrigin/uAssets#2765]
on player.pl, there is a blockade

![1](https://user-images.githubusercontent.com/17565773/42279134-1aff6286-7f9d-11e8-80f7-c38c4528bfdb.jpg)

opera 54, ublock origins

**Comment by zaphodbeebblebrox** [comment]
Polish sites should be reported to MajkiIT/polish-ads-filter. @MajkiIT

**Comment by hawkeye116477** [comment]
It was reported, but actually from 11 days no one found solution for antiadblock. Strange is that it's only on Chromium/Chrome 66+, on other browsers is fine.

**Comment by mapx-** [comment]
```
Wyświetlenie tego materiału bez zakupionego pakietu w Twojej lokalizacji jest niemożliwe
Ze względu na ograniczenia licencyjne dostęp do wybranego materiału

na terenie krajów UE innych niż Polska możesz uzyskać

tylko po wykupieniu pakietu.
```

**Comment by hawkeye116477** [comment]
@mapx- Geolocation unfortunately

**Comment by mapx-** [comment]
using hola vpn I get a blur video

![image](https://user-images.githubusercontent.com/10303732/42287625-6cb9525c-7fb7-11e8-8e8a-f59560e755be.png)

**Comment by hawkeye116477** [comment]
Strange, I too now, but that's only on Chromium/Chrome 66+, on other web browsers is ok.
Previously sometimes I got antiadblock or they tried to load some ads from redcdn and only the blue circle was spinning.

**Comment by jspenguin2017** [comment]
They changed their detection again?

**Comment by mapx-** [comment]
for example
`https://player.pl/seriale-online/kasia-i-tomek-odcinki,1`

but you have to use a vpn

**Comment by jspenguin2017** [comment]
Does my current solution in ND still works?

**Comment by hawkeye116477** [comment]
I haven't used ND for long time, but checked and it works :smile: OP probably wanted rather solution on uBO side, strange that it works ok on Chromium 65 and Firefox without ND, but not on Chromium 67, something changed for Chromium 67?

**Comment by krystian3w** [comment]
Hola vpn show only blurred background and empty video box 😜.

**Comment by jspenguin2017** [comment]
I only see one rule in ND: 
```js
if (a.domCmp(["itvn.pl", "itvnextra.pl", "kuchniaplus.pl", "miniminiplus.pl", "ttv.pl", "tvn.pl", "tvn24.pl",
    "tvn24bis.pl", "tvn7.pl", "tvnfabula.pl", "tvnstyle.pl", "tvnturbo.pl", "x-news.pl", "player.pl"])) {
    a.readOnly("isAdBlockEnabled", () => {
        "use strict";
        window.adBlockEnabled = false;
        return false;
    });
    a.loopbackXHR((ignored, url) => {
        const re = /^https?:\/\/tvn\.adocean\.pl\/ad\.xml/;
        if (re.test(url)) {
            return `<VAST version="2.0"></VAST>`;
        }
    });
}
```

**Comment by hawkeye116477** [comment]
```
-adserver/$badfilter
/pix.gif?$badfilter
*www.mp4$media,redirect=noopmp4-1s
@@|https://tools.services.tvn.pl/_ads/advert.js
@@redataredir
```
It helps, but unfortunately causes lags for about 2 minutes.

**Comment by krystian3w** [comment]
It's rather unsuitable, my browser overloads the browser and closes the card.

> https://support.google.com/chrome/answer/95669?hl=en
