### ISSUE TITLE
zigforums.com has an anti-adblock detector

### ISSUE THREAD

**Issue by avengah** [uBlockOrigin/uAssets#2791]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://zigforums.com/thread/11791054/politics/lets-dox-this-nigger.html`

### Describe the issue

The site tells you to disable your adblocker. You can sort of bypass it by enabling force scroll in Nano Adblocker but the first part of the comments is covered with diagonal lines, meaning links in that first part can't be clicked, and the entire comments window is blurred.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/285430/42376442-1151de14-8117-11e8-9905-e3ce645f42ea.png)
![image](https://user-images.githubusercontent.com/285430/42376458-2165471e-8117-11e8-9ed0-5e85bf57bb97.png)

### Versions

- Browser/version:

Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}
### 

- uBlock Origin version: Nano Adblocker 1.0.0.55, Nano Defender 15.0.0.5

### Settings

- None

### Notes

Trying to zap elements doesn't seem to work; it gets rid of the entire comments section. The best I could do was force enable scrolling, which gives the following result:
![image](https://user-images.githubusercontent.com/285430/42376567-79e64bb8-8117-11e8-8059-b1dda892fb05.png)

(This site is rather unsavoury, I was reading it following a link from a news story and I don't approve of its contents, However, I thought it should still be reported.)

**Comment by huyszn** [comment]
On the main page, there is a "Disable AdBlock to view this page" box and forum posts are hidden.
