### ISSUE TITLE
quora.com: site blocked on mobile due to ublock origins

### ISSUE THREAD

**Issue by spittingmadtruth** [uBlockOrigin/uAssets#2796]
### URL(s) where the issue occurs

`https://www.quora.com/How-do-I-learn-machine-learning-1`

### Describe the issue

The entire site blocked on mobile when ublock origins is enabled.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40901446/42400405-454bee8a-8126-11e8-865c-78706490601a.png)

### Versions

- Browser/version: 67.0.3396.99 (Official Build) (64-bit)
- uBlock Origin version: v1.16.12

### Settings

Default

### Notes

The offending filter seems to be `quora.com##[id*=wrapper]:has-text(/ad\s{1,}by /i)`

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/2404#issuecomment-402963096

update your filters, test again

**Comment by krystian3w** [comment]
`(/promoted\s{1,}by /i)` also add.

**Comment by spittingmadtruth** [comment]
I confirm that this is an issue for me even after clearing the caches; this is being caused by the same filter I mentioned earlier.

![image](https://user-images.githubusercontent.com/40901446/42478208-b3082cd6-8388-11e8-8f07-cbd34b3380e3.png)

**Comment by okiehsch** [comment]
Are you using an actual mobile device, or are you simply changing the user agent?
If it is the latter, see https://github.com/uBlockOrigin/uAssets/commit/8f42fafd9287e8041559ca4d127903afd18a6149#commitcomment-29628141
