### ISSUE TITLE
onlinevideoconverter

### ISSUE THREAD

**Issue by brunopereira322** [uBlockOrigin/uAssets#2798]
### URL(s) where the issue occurs

`https://www.onlinevideoconverter.com/pt/mp3-converter`

### Describe the issue

If you try to convert something with ublock on, the conversion will not occur.

### Versions

- Browser/version: [Chrome 67.0.3396.99 64 bits]
- uBlock Origin version: [1.16.12]

**Comment by mapx-** [comment]
no issue for me, the conversion is starting and ends normally 

Are you using the default setup ? only uBo or some other blocking extensions ?
