### ISSUE TITLE
Cosmetic Filter: Wired - Hide empty flash ad frame in footer of all posts

### ISSUE THREAD

**Issue by collinbarrett** [uBlockOrigin/uAssets#28]
### One or more specific URLs where the issue occurs

`http://www.wired.com/2016/04/average-webpage-now-size-original-doom/`

### Describe the issue

There is an empty flash ad frame at the bottom left corner of all (or at least a decent sized sample I just tested) posts on Wired.

### Screenshot(s)

![wiredcosmeticfix](https://cloud.githubusercontent.com/assets/6483057/14763596/b815dfa2-095f-11e6-8394-5529b4da079d.jpg)

### Your settings

- Browser/version: Chrome 50.0.2661.86 (64-bit) Mac
- uBlock Origin version: 1.6.8

**Comment by collinbarrett** [comment]
pr coming soon. trying to include checksum update as well.

**Comment by gorhill** [comment]
I don't see that empty placeholder on my side. Anyways, the rule is way too complicated. I guess it's what uBO offered, but no filter list maintainers would come up with such a rule.

Other point, as said last time, no need to open an issue separate from the pull request, the pull request itself can be documented just as well.

**Comment by collinbarrett** [comment]
Ok. Gotchya. I was thinking that I should still create an issue but it would be automatically created during the pr process, but I couldn't get that to work. Won't submit issues prior to prs in the future. Thanks.

**Comment by gorhill** [comment]
I still would like to understand how you ended up with a placeholder at that position, as said I can't see this on my side. You say "Flash ad frame", but your picture is that of an `iframe` element not being collapsed. What would be useful is the URL for that `iframe`.

**Comment by collinbarrett** [comment]
@gorhill hmm, ok, I am still trying to learn how to inspect, etc. Here's a capture in Chrome on Mac with both uBlock Origin and Reek's anti-adblocker script disabled. Maybe it's just an unsold ad space? I'm not sure. I see it in Safari on Mac, too.

![cap](https://cloud.githubusercontent.com/assets/6483057/14769774/3668ab0c-0a26-11e6-8481-465b9806f8de.jpg)

**Comment by gorhill** [comment]
The iframe src is `googleads.g.doubleclick.net/[...]`, so I expect this should be blocked. Can you look at what the logger reports?

**Comment by collinbarrett** [comment]
So, the logger reports the following:

> Static filter ||googleads.g.doubleclick.net^ found in:
>   - hpHosts’ Ad and tracking servers
>   - Dan Pollock’s hosts file
>   - MVPS HOSTS

There is no visible ad showing up, but without the complex rule that the UBO picker generates, the html frame around where the ad should go is still visible. The rule, copied again below, hides the entire frame (not sure if "frame" is the right word).

`www.wired.com###prefooter > .flex-box.clearfix.site-container > .mob-order-2.flex-row > .mob-order-1.big-col-12.med-col-10.col.float-l-med.float-l-big.article-group > .items-3.items.flex-row > .med-order-2.col.big-col-9.med-col-18 > .flex-row > .hide-mob.big-marg-b-med.med-marg-b-med.big-col-18.med-col-10.justify-c.align-m.flex-box.col.rad.bg-white`

**Comment by okiehsch** [comment]
I can only reproduce your issue if i use a "allow" rule for
`https://pagead2.googlesyndication.com/pagead/show_ads.js`

![wire1](https://cloud.githubusercontent.com/assets/16838044/14771509/fc041cea-0a8d-11e6-8904-4a223adeb033.PNG)

![aufzeichnen1](https://cloud.githubusercontent.com/assets/16838044/14771499/9bd71d9a-0a8d-11e6-9887-f1396928df5b.JPG)


If I block
`https://pagead2.googlesyndication.com/pagead/show_ads.js`

![wire](https://cloud.githubusercontent.com/assets/16838044/14771505/d7fb80e0-0a8d-11e6-9946-028a7f5fbba7.PNG)

![aufzeichnen](https://cloud.githubusercontent.com/assets/16838044/14771489/12dcb55e-0a8d-11e6-88c7-27cc97dafc2e.JPG)



there is no iframe.

**Comment by collinbarrett** [comment]
@okiehsch , interesting. thanks! hmm... when filtering for that in logger, this is what I see. What is the order of operations in which the rules are applied? is one of the green rules overriding the red rule?

![cap](https://cloud.githubusercontent.com/assets/6483057/14771551/b01f2664-0a54-11e6-8d47-f7348f48f3cf.jpg)

**Comment by collinbarrett** [comment]
oh, oops, you specified it was the show_ads.js which does have an allow rule applied. the allow rule is coming from Fanboy+Easylist-Merged Ultimate List. I'll have to dig around their forums and see why that is allowed. Thanks.

**Comment by collinbarrett** [comment]
ok, it's being allowed by that list in the following block. is there a way I can temporarily override that one rule from the list?

```
!---------- Anti Adblock Warnings ------
!
@@||g.doubleclick.net/gampad/ads?gdfp_req=1&$script,domain=forbes.com
@@||pagead2.googlesyndication.com/pagead/*/show_ads_impl.js$domain=playonlinux.com|wired.com
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=playonlinux.com|wired.com
@@||wired.com/ams/page-ads.js
@@||wired.com^$generichide
```

**Comment by gorhill** [comment]
So it's possibly rules for ABP to work around Wired's anti blocker scheme? In that case, they should be overridden for the sake of uBO's users. Can you try:

    ||pagead2.googlesyndication.com/pagead/*/show_ads_impl.js$important,domain=wired.com
    ||pagead2.googlesyndication.com/pagead/show_ads.js$important,domain=wired.com
    ||wired.com/ams/page-ads.js$important

**Comment by collinbarrett** [comment]
@gorhill yep, adding those rules fixes it. this is the only rule that seems to be needed for the specific issue I'm seeing.

||pagead2.googlesyndication.com/pagead/show_ads.js$important,domain=wired.com

**Comment by gorhill** [comment]
We need to find out why this exception filter was added.

**Comment by collinbarrett** [comment]
ok, narrowed it down to the Fanboy Enhanced Tracking list. https://fanboy.co.nz/enhancedstats.txt will update if I find any reasons why it was added.

**Comment by ryanbr** [comment]
Was added because of the Anti-adblock stuff, has the requirement for this rule changed?

**Comment by okiehsch** [comment]
If you use Adblock Plus `wired.com` articles will be blocked without 
@@||pagead2.googlesyndication.com/pagead/*/show_ads_impl.js$domain=playonlinux.com|wired.com
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=playonlinux.com|wired.com

The exception filter
@@||wired.com/ams/page-ads.js is unnecessary.

**Comment by gorhill** [comment]
Restored blocking filters using the `important` keyword.
