### ISSUE TITLE
mokeedev.com

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#280]
### URL(s) where the issue occurs

https://download.mokeedev.com/

### Describe the issue

Ad block detection blocks download of files.

### Screenshot(s)

https://i.gyazo.com/7f291144b15f0c580c21c1b36798eb6c.png

### Versions

- Browser/version: Chromium 58
- uBlock Origin version: 1.10.4

### Steps to Reproduce

Browse to - https://download.mokeedev.com/
Click on the first download link from the list
https://download.mokeedev.com/ad-dl.php will be opened and the adblock notice will appear blocking the download of the file.

**Comment by gorhill** [comment]
Does this work?

    download.mokeedev.com##script:inject(fuckadblock.js-3.2.0)

The site is essentially using FuckAdBlock, but just renamed the script file to avoid uBO's redirect filter for `fuckadblock`.

**Comment by uBlock-user** [comment]
No change.
