### ISSUE TITLE
popmatters.com detects Nano

### ISSUE THREAD

**Issue by avengah** [uBlockOrigin/uAssets#2800]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.popmatters.com/gorillaz-the-now-now-2583303134.html`

### Describe the issue

Not on the main page but on all articles, a big image obscures the page with a popup in the middle.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/285430/42422211-d1aea4a8-82d9-11e8-993c-eafdf42f89ad.png)

### Versions

- Browser/version: 

Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}

- uBlock Origin version: Nano Adblocker 1.0.0.55, Nano Defender 15.0.0.7

### Settings

- None

### Notes

You can click "Naah, news should be free" to make it go away, but the link is tiny and people might easily miss it.

**Comment by okiehsch** [comment]
If I click he message away I get it again with the next page load, so I will add a fix to `uBO-filters`.
