### ISSUE TITLE
facepunch.io, biters.io, skyroyale.io, fisp.io

### ISSUE THREAD

**Issue by SkeletalDemise** [uBlockOrigin/uAssets#2803]
### URL(s) where the issue occurs
`https://facepunch.io` `https://biters.io` `https://skyroyale.io` `https://fisp.io`

### Describe the issue
Anti-adblock.

### Versions

- Browser/version: Chrome 67.0.3396.99
- uBlock Origin version: 1.16.12

### Settings
Default.

**Comment by KiLL4FuNK** [comment]
Anti-adblock.

`https://facepunch.io`
`https://biters.io`
`https://skyroyale.io`
`https://fisp.io`

**Comment by okiehsch** [comment]
I can't reproduce an anti-adblock message, all of these sites won't start even if I disabe uBlock.

**Comment by ZaphodBeebblebrox** [comment]
They start in chrome, it just takes them forever. They do not have an anti-adblock message for me either.

**Comment by IThinkIAmCool** [comment]
Ads on `https://facepunch.io`.
@ryanbr
