### ISSUE TITLE
dream-sound.com

### ISSUE THREAD

**Issue by Freso** [uBlockOrigin/uAssets#2804]
### URL(s) where the issue occurs

* `http://www.dream-sound.com/dl/id8767`

### Describe the issue

The site has a full page "adblock blocking" overlay, rendering it useless when using an adblocker such a uBlock₀.

### Screenshot(s)

![billede](https://user-images.githubusercontent.com/177659/42440400-efdb7726-8365-11e8-9f24-9f60d50bfa69.png)

### Versions

- Browser/version: Firefox 61.0.1 (`Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0`)
- uBlock Origin version: 1.16.12

### Settings

- Can't think of any.

### Notes

I looked into various anti-adblock blocking filters, but none of them seems to have been able to remove them.

**Comment by uBlock-user** [comment]
It's BAB, so `dream-sound.com##script:inject(bab-defuser.js)`
