### ISSUE TITLE
crackwatch.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#2805]
![2018-07-09-dragon ball fighterz price comparison _ crackwatch](https://user-images.githubusercontent.com/5884000/42462367-5e125362-83a3-11e8-98e8-b8f84b64026d.png)
`https://crackwatch.com/game/dragon-ball-fighterz/prices`

ref baner

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.12
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by mapx-** [comment]
add
`crackwatch.com##a[href*="goo.gl"]`

**Comment by gwarser** [comment]
https://crackwatch.com/#!

If I hide banner with for example:

`crackwatch.com##div[id]:has(>a>span[style*="data:image"])`

anti-adblock message is shown.

https://old.reddit.com/r/uBlockOrigin/comments/935rmd/crackwatch_adds/

**Comment by mapx-** [comment]
does it break some functionality ?

`crackwatch.com##.ab.row`

**Comment by okiehsch** [comment]
````
crackwatch.com##.ab.row
crackwatch.com##div[id]:has(>a>span[style*="data:image"])
````
works on my end without any noticable breakage.

**Comment by gwarser** [comment]
Maybe /u/myhv will answer. 

`||crackwatch.com^$csp=img-src *` may prevent flickering on load.

**Comment by myhv-a** [comment]
With okiehsch's and gwarser's filters no adds are displayed. Also no flickering adds during load.

**Comment by SylveonBottle** [comment]
![image](https://user-images.githubusercontent.com/17802843/82948912-4fa74980-9f68-11ea-9432-e68a9d98dcab.png)

**Comment by llacb47** [comment]
```
crackwatch.com##.bg-container+.container>div[id]
crackwatch.com##.game-gallery>div[id][style]
```

**Comment by Alex4567890** [comment]
There are some banners as of now.

**Comment by Alex4567890** [comment]
There are some banners on crackwatch.com as of now.
