### ISSUE TITLE
[Anti-adblock] overclockers.ru

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2808]
### URL(s) where the issue occurs

`https://overclockers.ru/`

### Describe the issue

Anti-adblock, takes 5~10 seconds to trigger. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/42483037-605fe6de-83a8-11e8-95c9-c36806e9881b.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.12

### Settings

English default + Russian filters. Tried without Russian filters, same result.

**Comment by KiLL4FuNK** [comment]
Anti-adblock

**Comment by jspenguin2017** [comment]
Broke again.
