### ISSUE TITLE
'galleryad.com' blocked and should not be

### ISSUE THREAD

**Issue by LanceNorskog** [uBlockOrigin/uAssets#281]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
www.galleryad.com

### Describe the issue
Gallery AD is an art gallery in downtown San Jose, CA, USA. I'm not affiliated with it, just a fan. They are an actual bricks&mortar business with skater punk and graffiti art for sale.

Their site, www.galleryad.com, has existed since the early 2000s. It is blocked by a rule with 'galleryad' which I assume some advertising thing.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Firefox 50.1.10
- uBlock Origin version: 1.10.6

### Settings

No changes

### Notes

Cheers, and thanks for all of your hard work!
I can see how this would just be an endless treadmill.

**Comment by toshiya44** [comment]
Did you check the logger? Which filter lists do you have?
The site was not blocked when I tried to access it and I use most of the default lists.

**Comment by gorhill** [comment]
Report to the filter list maintainer(s) of whichever filter list contains the filter `galleryad`.

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=35264

**Comment by gorhill** [comment]
So the URL in the description was wrong, the issue was with `http://galleryad.com/`, not `http://www.galleryad.com/`.

**Comment by SMed79** [comment]
Yes, & Easy to fix, if they force the '[www](http://www.htaccessbasics.com/force-www-nonwww-domain/)'.
