### ISSUE TITLE
spycock.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2813]
URL(s) where the issue occurs

`https://www.spycock.com/videos/6531/that-white-bottom-is-struggling-and-screaming-taking-big-african-dick.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by SkeletalDemise** [comment]
There is a redundancy. You added `spycock.com##script:inject(abort-on-property-write.js, Fingerprint2)` twice.

**Comment by kulfoon** [comment]
Many ads again: 
`https://www.spycock.com` (main page)
`https://www.spycock.com/video/my-cousin-helps-me-while-i-drive-him-home-1508.html` (example video)
