### ISSUE TITLE
"Remove ads" links on solidfiles.com

### ISSUE THREAD

**Issue by teohhanhui** [uBlockOrigin/uAssets#283]
### URL(s) where the issue occurs

`http://www.solidfiles.com/v/4ABN5ZXxYappj` (basically any file hosted there)

### Describe the issue

Ad scripts from `*.clksite.com/adServe/banners?...` are blocked, but there are "Remove ads" links left behind.

### Screenshot(s)

None.

### Versions

- Browser/version: Firefox 51.0.1
- uBlock Origin version: 1.10.6

### Settings

All default.

### Notes

Can be resolved by adding a cosmetic filter:

```
solidfiles.com##[class*="bnr-"] > .remove
```

(If we hide the whole `.bnr-*` element, it affects the page layout.)

**Comment by gorhill** [comment]
Report to EasyList maintainers please:

    solidfiles.com##.top-section
    solidfiles.com##.left
