### ISSUE TITLE
Popups on solidfiles.com

### ISSUE THREAD

**Issue by teohhanhui** [uBlockOrigin/uAssets#284]
### URL(s) where the issue occurs

`http://www.solidfiles.com/v/4ABN5ZXxYappj` (basically any file hosted there)

### Describe the issue

A popup is opened when clicking on the "Download" button (not fake). The ad-serving domains are `educing.info` and `onderlea.info` (refer to script sample).

### Screenshot(s)

None.

### Versions

- Browser/version: Firefox 51.0.1
- uBlock Origin version: 1.10.6

### Settings

All default.

### Notes

Example of the inline script: https://gist.github.com/teohhanhui/ff9187f64acd24dc754f9a6004e920b6

I'm not sure how / if we can block this, but perhaps the relevant ad-serving domains can be added to the block list?

**Comment by SMed79** [comment]
Try using the dev build https://addons.mozilla.org/firefox/addon/ublock-origin/versions/beta

**Comment by teohhanhui** [comment]
It's the same with 1.10.7rc2

Thanks for the link. So we should wait for EasyList to fix it, right? (But how responsive are they to changes? That thread seems to be half a year old...)

**Comment by SMed79** [comment]
The popups are manage by uBO **1.10.7rc2**

![popup](https://cloud.githubusercontent.com/assets/1873139/22506673/fc9ee932-e881-11e6-957d-892701e27075.PNG)

**Comment by gorhill** [comment]
You can also use the no-popups switch meanwhile for that site: https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups.
