### ISSUE TITLE
simpsonsua.com.ua [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2850]
URL(s) where the issue occurs

`http://simpsonsua.com.ua/sezon-23/581-23-sezon-16-seriia.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by mapx-** [comment]
test
```
simpsonsua.com.ua##script:inject(set-constant.js, canRunAds, true)
@@*$image,domain=simpsonsua.com.ua
@@||loadercdn.com^$xmlhttprequest,domain=simpsonsua.com.ua
@@||simpsonsua.com.ua/test-ad.php
/preroll/*mp4$media
```

**Comment by KiLL4FuNK** [comment]
IT WORKS GREAT

**Comment by okiehsch** [comment]
Does not work on my end with a default setup.

**Comment by okiehsch** [comment]
RU-Adlist breaks the site with the filter
`*$script,domain=simpsonsua.com.ua`

**Comment by mapx-** [comment]
right, I tested without that list
`*$script,domain=simpsonsua.com.ua, badfilter`

**Comment by okiehsch** [comment]
If I enable `RU-Adlist` and `Adguard Russian Filters`, i.e. the default setup for russian/ukrainian sites

````
simpsonsua.com.ua##script:inject(abort-current-inline-script.js, atob, void)
||megastock.ru/doc/*/azure_rus.gif$image,redirect=32x32-transparent.png,domain=simpsonsua.com.ua
*$script,domain=simpsonsua.com.ua, badfilter
/preroll/*mp4$media
````
works on my end.

**Comment by okiehsch** [comment]
`/preroll/*mp4$media` could lead to some broken videoplayers, so I am not sure if adding this is a good idea.

**Comment by mapx-** [comment]
`/preroll/*.mp4$media,domain=td7vccbywda3.ru`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by okiehsch** [comment]
Site works fine if I enable the corresponding regional filter lists.
