### ISSUE TITLE
Would you allow "cc.naver.com" ?

### ISSUE THREAD

**Issue by ndaesik** [uBlockOrigin/uAssets#2852]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

I found this issue on https://cafe.naver.com/jssct for first. but it occurs all the other community starts with url : https://cafe.naver.com , the "cafe.naver.com" is like a Reddit version of in korea. and the cafe.naver.com/jssct is a sub reddit of the thing.

### Describe the issue

when you try to read a post on the cafe(≒ sub Reddit). it says '서버에 대한 요청이 확장 프로그램에 의해 차단되었습니다.', which means 'Server request has banned by an extension'
so have to turn off ublock and reload page every time.

### Screenshot(s)

now on computer is so laggy so I'll attach soon 

### Versions

- Browser/version: Chrome canary ver.69.0.3488.0
- uBlock Origin version: 1.5.2

### Settings

- default

### Notes

You may not access the page directly as they need to have a "naver" id also need a permission to join the sub cafe. but this problem notified already long ago, on the other posts already give a solution to put "@@cc.naver.com" on custom filter list.

**Comment by okiehsch** [comment]
`@@||cc.naver.com/cc$subdocument,first-party` seems to work on my end, does it work for you?

**Comment by ndaesik** [comment]
here is alternate for the screenshot as may can't see without account to access 

https://www.useloom.com/share/7476f67b451149a5a709550cb3dfa08d

**Comment by ndaesik** [comment]
@okiehsch I've tested on the video with @@cc.naver.com and it works fine.
I didn't tested with your code yet, I'll check right now

**Comment by ndaesik** [comment]
@okiehsch Yeah it works fine, I don't know which code would be more effective, however that would be great to add the line on default filter without edit custom filter for most of korean users.

**Comment by okiehsch** [comment]
I will add `@@||cc.naver.com/cc$subdocument,first-party`  to the `uBO-unbreak` list.

By the way, you do realize that you are using `uBlock Plus Adblocker` a `uBlock origin` knock-off?

**Comment by ndaesik** [comment]
D: shoot !
I've tested several adblock apps, after that I just confused with fake one !
I'm reinstalling the real one, thanks for solve the matter and thanks for make me notice to make me use real one XD!
