### ISSUE TITLE
resourcepack.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#2854]
blocked right click

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.12
 ND 14.58
 Chr 67.0.3396.87
</details>

**Comment by ghost** [comment]
there are adleftovers in mobile view. @stephenhawk8054 
`https://resourcepack.net/res/minecraft-1-21-resource-packs/#gsc.tab=0`
<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/337c1385-9345-4bdb-901e-72d08f99a093)

![Image](https://github.com/user-attachments/assets/21c84e5d-1c82-454a-b6af-85f411fcd3b6)

</p>
</details>

**Comment by stephenhawk8054** [comment]
Please report to https://github.com/AdguardTeam/AdguardFilters/issues
