### ISSUE TITLE
unblocked popups

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#286]
Last version of firefox and ublock origin with default filters.

page: http://freerls.org/

there are popups unblocked. happens after click a few times somewhere.

some log entries:
http://i.imgur.com/vRlP1le.png
http://i.imgur.com/ciUHA4m.png

**Comment by uBlock-user** [comment]
Report to Easylist maintainers, not here - https://forums.lanik.us/viewforum.php?f=62

**Comment by gorhill** [comment]
The solution for uBO is to turn on the no-popups switch for that site: <https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups>.

This feature was added exactly for these cases where filter lists can't keep up with popup spammers.

**Comment by ahmedtds** [comment]
@uBlock-user "The goal of this repository is to receive all the reports for the need of new filters, or reports of web pages broken by existing filters..."

@gorhill
is there a way to enable this setting globally, not per-site-basis?

**Comment by gorhill** [comment]
Manually adding the rule `no-popups: * true` in _"My rules"_ will prevent all popups everywhere.

**Comment by uBlock-user** [comment]
@ahmedtds No new filters are needed because popup filters are missing in the first place, that means Easylist should have placed filters for that website, so report there and nothing is broken here either. Your justification is plainly irrelevant.

**Comment by ahmedtds** [comment]
@uBlock-user 
https://github.com/uBlockOrigin/uAssets/commit/f96f074f366ee6d599b50838d1a0f913be25ebe9
https://github.com/uBlockOrigin/uAssets/issues/270

**Comment by gorhill** [comment]
It's ok to report here, it's just that sometimes the proposed solution will not necessarily be to add another filter to _uBlock filters_ -- especially that I do not always have the time to scrutinize every site's code.

Look at it now, how about:

    freerls.org##script:inject(noeval.js)

Does it break any functionality for the site?

**Comment by ahmedtds** [comment]
@gorhill 
It looks fine, everything works and no popups. Thanks.

**Comment by ahmedtds** [comment]
@gorhill 
Looks like this domain is no longer active and I don't see any unblocked popups in their new domain. So you might wanna remove this filter from ublock filters.
