### ISSUE TITLE
driverdestek.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2860]
URL(s) where the issue occurs

`http://www.driverdestek.com/ekran-karti-suruculeri/geforce-gt-730-graphics-card-driver.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by mapx-** [comment]
At least in firefox, the uBo "classic" filters don't work for me

working ones
```
@@||driverdestek.com^$generichide
@@*.png#$image,domain=driverdestek.com
driverdestek.com##.adsbygoogle
```

**Comment by KiLL4FuNK** [comment]
works well in Chrome

@@||driverdestek.com^$generichide
@@*.png#$image,domain=driverdestek.com
driverdestek.com##.adsbygoogle

**Comment by victorcarr59** [comment]
I have an issue with the Administration user account, will not let me sign in nor will it allow any downloads which require Admin User Acc.
I have tried signing into A,U,A. with my own acc. ''to become only Admin.acc user'' but will not allow download.

**Comment by mapx-** [comment]
It's about `driverdestek` ?
