### ISSUE TITLE
animeflv.net

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#287]
### URL(s) where the issue occurs

http://animeflv.net/

### Describe the issue

Anti adblock overlay blocks access

### Screenshot(s)

https://i.gyazo.com/0dcaf96d2e14b535b727658ac64677d1.png

### Versions

- Browser/version: Chromium 58
- uBlock Origin version: 1.10.4

**Comment by gorhill** [comment]
Does this work?

    @@||animeflv.net/js/ads.js$xmlhttprequest,first-party

If so, best is to report to EasyList maintainers, as this is plain ABP-compatible filter syntax.

**Comment by uBlock-user** [comment]
Yes, that would work. I would prefer not to whitelist and in that hope I posted this issue. Is there any other filter which I can use without whitelisting ?

**Comment by gorhill** [comment]
It's a narrow (`xmlhttprequest`) first party (`~third-party`) whitelisting, I see no issue with this.

**Comment by uBlock-user** [comment]
Okay but is any alternate filter available besides this one ?

**Comment by okiehsch** [comment]
`||animeflv.net/js/ads.js$xmlhttprequest,redirect=nooptext,domain=animeflv.net`
works on my end, only tested with Chrome 56.

**Comment by uBlock-user** [comment]
No change on Chromium 58

**Comment by SMed79** [comment]
3 days ago https://forums.lanik.us/viewtopic.php?p=112610#p112610

**Comment by uBlock-user** [comment]
Didn't you read ? I don't want to whitelist. Don't bother posting any Easylist solutions here.

**Comment by SMed79** [comment]
> Didn't you read ? I don't want to whitelist. Don't bother posting any Easylist solutions here.

No problem, just ignore me when i post.

**Comment by uBlock-user** [comment]
Do me a favour, just stay out of the issues that **I** post here, got that ?
