### ISSUE TITLE
infowars.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#2870]
### URL(s) where the issue occurs

`https://www.infowars.com/`

### Describe the issue

Banner blocked

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/42649008-7695821c-85d6-11e8-80ba-97b5a596a085.png)

### Versions

- Browser/version: Chrome 67
- uBlock Origin version: 1.16.12

### Settings

Default

### Notes

`@@||www.infowars.com/*.png$image`

**Comment by terrorist96** [comment]
@mapx- closed without explanation?

**Comment by mapx-** [comment]
as usually, simple ads fixable with classic easylist filters have to be reported at their repository

**Comment by terrorist96** [comment]
It's not an ad. I'm reporting the site banner being improperly blocked.

**Comment by mapx-** [comment]
oh, sorry.

However, I can see

THE
ALEX JONES RADIO SHOW
LISTEN NOW

if that one was your problem

Did you try using only the default setup ?

**Comment by terrorist96** [comment]
Did you see my screenshot above?
This is what it *should* look like:
![image](https://user-images.githubusercontent.com/12802056/42649827-b4528e04-85d8-11e8-90f6-e7043c3a9209.png)

> Did you try using only the default setup ?

Yes, as I noted above in my original report. :)

**Comment by mapx-** [comment]
test these filters
```
||www.infowars.com/*.png$image,badfilter
infowars.com##.hero-ad-special
```

**Comment by terrorist96** [comment]
Works. Regarding the second filter: isn't that technically self-advertisement that should be allowed? I'm not complaining if it's blocked, just wanna understand the rationale.
Thanks!

**Comment by mapx-** [comment]
yes, it seems self-adv

**Comment by terrorist96** [comment]
`https://www.infowars.com/why-is-president-trump-committing-suicide/`

Video blocked, comments blocked

`@@https://$third-party,script,domain=infowars.com` fixes it, but I'm sure there's a good reason for that filter.

**Comment by terrorist96** [comment]
@okiehsch video works but comments still blocked.

**Comment by terrorist96** [comment]
@okiehsch comments aren't loading again.

**Comment by terrorist96** [comment]
Is there anything preventing fixing the site? It's still broken for me.

**Comment by mapx-** [comment]
Does this work for you ?
`@@||api.infowarsmedia.com/videojs-event-tracking/$script,1p`

tested here (comments already visible, only the video was broken)
`https://www.infowars.com/watch/?video=5d6ee92e230eeb0013b6cff2`

**Comment by mapx-** [comment]
@ryanbr

**Comment by terrorist96** [comment]
> `@@||api.infowarsmedia.com/videojs-event-tracking/$script,1p`

That works to fix the link you provided, but video still broken here:
`https://www.infowars.com/why-is-president-trump-committing-suicide/`

And comments are still blocked for me at both links.

**Comment by mapx-** [comment]
- on that page I get 3 videos all running fine (even without my filter)
- even disabling uBo the comments are broken

**Comment by terrorist96** [comment]
This rule is causing the video to be blocked

`|https://$third-party,script,domain=infowars.com`

by blocking:

`https://gateway.zscalertwo.net......` which my company uses for security.

This fixes it.
`@@|https://$third-party,script,domain=infowars.com`
