### ISSUE TITLE
Facebook Player Won't Go Away and It Takes Over Every Video in Every Player

### ISSUE THREAD

**Issue by Grip555** [uBlockOrigin/uAssets#2871]
### URL(s) where the issue occurs

`kimcartoon.me`

### Describe the issue

Every single video is replaced by a 1 second long video hosted by Facebook that's just a blank screen with no sound.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/33988522/42650951-c82ea16a-8605-11e8-9cf6-e64ca8e06d3f.png)

### Versions

- Browser/version: [Firefox Quantum 61.0.1 (64-bit)]
- uBlock Origin version: [v1.16.12]

### Settings

Default

### Notes

I tried adding @@||kimcartoon.me/ads/fb.aspx^$first-party,subdocument to filters, but it did nothing and whenever I try to block the element, it comes back when I reload the page or change video player. I also whitelisted Kimcartoon, but that didn't work either.
My filters: https://textsaver.flap.tv/lists/229f

**Comment by mapx-** [comment]
tested:
`http://kimcartoon.me/Cartoon/Dennis-and-Gnasher-Unleashed/Episode-39-Gnash-Hit?id=85622`

no issue for me

**Comment by uBlock-user** [comment]
Try 

```
kimcartoon.me###my_video_1:style(display: block!important;)
kimcartoon.me###my_video_1_html5_api:style(display: block!important;)
```

I don't get that 1 sec video, probably because I run a strict CSP policy which blockw `data:` URI's when loaded as `media-src`.

**Comment by Grip555** [comment]
Maybe I have too many filters already? Mapx, edited first post to list all filters I have.

**Comment by Grip555** [comment]
uBlock-user, it didn't make a difference.

**Comment by mapx-** [comment]
remove all those custom filters, upfdate all the lists (use the default setup), test gain

**Comment by Grip555** [comment]
Mapx, tried that just now, but it didn't work. Maybe AdGuard or NoScript are messing with the filter somehow?

**Comment by mapx-** [comment]
Use only uBo for your tests (it's useless using 2 adblockers)

**Comment by Grip555** [comment]
Yeah just got rid of AdGuard, but it also did nothing.

**Comment by mapx-** [comment]
disable noscript as well

**Comment by okiehsch** [comment]
`http://kimcartoon.me/Cartoon/Big-City-Greens/Episode-9-10?id=84976` I have to click twice before the actual video starts.

**Comment by Grip555** [comment]
Hmm... odd, I just reset Origin to default, so the only filter there is `@@||kimcartoon.me/ads/fb.aspx^$first-party,subdocument` and only whitelisted websites other than default are Kimcartoon and Kissanime.

**Comment by okiehsch** [comment]
I tried all streaming options at `http://kimcartoon.me/Cartoon/Big-City-Greens/Episode-9-10?id=84976`
they all work fine.

**Comment by Grip555** [comment]
I tried to see if it was my internet provider blocking the videos, by changing my server to America, but it's the same thing. I guess it's a Firefox setting.

**Comment by okiehsch** [comment]
I can reproduce if I use [uBlock-medium](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) mode, but that is not a default setup.
Did you disable noscript?

**Comment by Grip555** [comment]
No, but I did temporarily allow everything.

**Comment by Grip555** [comment]
Tried uBlock in Chrome with the filter and I have the same issue.

**Comment by Grip555** [comment]
And yeah... I disabled noscript and it's working. Is there a way to add a filter to Nosccript so this doesn't happen?

**Comment by okiehsch** [comment]
No, you have to allow the `vjs.zencdn.net` requests in noscript for it to work and please before you open an issue try with only uBO and a default setup, or atleast indicate in "Settings" that you are using additional extensions like noscript.
Saves everybody time and work.
