### ISSUE TITLE
anti-adblocker in fxnetworks.com

### ISSUE THREAD

**Issue by anonymoustrash** [uBlockOrigin/uAssets#2873]
### **URL(s) where the issue occurs**

`https://www.fxnetworks.com/`

### Describe the issue

I've tried everything to stop this windows that doesn't disappear, it doesn't let you watch the video and it gets stuck in the window saying that you have to deactivate adblock

### Screenshot(s)

https://imgur.com/a/1oPexQ5

### Versions

- Browser/version: Chrome 67.0.3396.99
- uBlock Origin version: 1.15.24

### Settings

- Pretty much all filters are on, nothing on the whitelist and nothing custom-made, these are the advanced settings: 
" assetFetchTimeout 30
  autoUpdateAssetFetchPeriod 120
            autoUpdatePeriod 7
       ignoreRedirectFilters false
   ignoreScriptInjectFilters false
manualUpdateAssetFetchPeriod 2000
               popupFontSize unset
   streamScriptInjectFilters false
       suspendTabsUntilReady false
       userResourcesLocation https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt"

### Notes

Sorry if this has been repeated a lot, i'm new to this haha, i'm like a 60 y/o dad discovering the internet, i've tried a lot of custom made rules but none of them work, nanodefender only works in fox and mylifetime but nothing works with fx

**Comment by mapx-** [comment]
Test these filters (I have no provider / account)

```
@@||fwmrm.net/p/fox_live/AdManager.js$script,domain=fxnetworks.com
@@||ads.freewheel.tv^$media,domain=fxnetworks.com
@@||v.fwmrm.net/ad/$script,domain=fxnetworks.com
```

**Comment by zaphodbeebblebrox** [comment]
I can get it to work with 
```
@@||fwmrm.net/p/fox_live/AdManager.js$script,domain=fxnetworks.com
@@||v.fwmrm.net/ad/$script,domain=fxnetworks.com
@@||player.foxdcg.com/shared/finn//playback.js$xmlhttprequest,domain=fxnetworks.com
@@||media.truex.com/release/*TrueXRenderer.js$script,domain=fxnetworks.com
```
The media.truex,com can be redirected, but that causes an ad to play for some reason.

**Comment by okiehsch** [comment]
It is your call, if it works you can add the filters, better than beeing forced to disable `uBO`.
