### ISSUE TITLE
https://www.mirrored.to/

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#2874]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.mirrored.to/files/VE5GRXKT/AdGuard_Windows_Premium_v6.2.x___v6.3.x_nGen_Fix_Only.rar_links`

### Describe the issue

[The site won't generate download links when ublock origin is active.]

### Screenshot(s)

[https://imgur.com/daY2kyX]

### Versions

- Browser/version: [Firefox Quantum 61.0.1]
- uBlock Origin version: [1.16.12]

### Settings

- [https://imgur.com/w2SVssP]

### Notes

[The site refuse generate download link when ublock origin is active.]

**Comment by krystian3w** [comment]
Empty pools / ads:

```
userscloud.com##.innerTB > center + br, .innerTB > center, userscloud.com##.container > center
datafilehost.com##a > h4 > mark
sendit.cloud##section.widget-tasks:has-text(Ads)
```

**Comment by exodius48** [comment]
@mapx- When UBO active, Open link above, then click "Click to view the file links". The site won't generate download links. Then compare with UBO disabled.

@krystian3w whe to add them?

**Comment by krystian3w** [comment]
You can add to own filters and try report to EasyList?

**Comment by exodius48** [comment]
@krystian3w so, that won't resolved?

**Comment by krystian3w** [comment]
Upload your uBO setting i try find  who block generate links.

https://gist.github.com/

**Comment by exodius48** [comment]
@krystian3w here bro https://gist.github.com/exodius48/c51e74585f7c098c290140c17ba4b262

**Comment by krystian3w** [comment]
`@@^ads^$xmlhttprequest,domain=www.mirrored.to`

https://github.com/k2jp/abp-japanese-filters/blob/831cedc78b5da6c105e035076a0dd2173df270dd/abpjf.txt#L3617

**Comment by okiehsch** [comment]
krystian3w's filter should fix our issue, if you want to use `abp-japanese-filters` you will have to live with site breakage.

**Comment by ghajini** [comment]
`https://www.mirrored.to/downlink/1XR3C74N`
clicking on `click here to visit the..............`
sitr opens proper url in new tab while original tab is flooded with revolving ad server ads

**Comment by mapx-** [comment]
I see no `"click here to visit"`

**Comment by ghajini** [comment]
I mean if you choose dropjiffy then in next page if you click on `Click here to visit the file page on Dropjiffy`
Opens destination URL in new tab with original tab loaded with ads

**Comment by krystian3w** [comment]
OK...

**Comment by mapx-** [comment]
you should test the added filters just to be sure ..

**Comment by ghajini** [comment]
Looks good

**Comment by smed79** [comment]
https://github.com/easylist/easylist/commit/e7f7162fc50c53aec7cabc6f530ac9823635e120
