### ISSUE TITLE
 uBO-Personal-Filters‎ issue

### ISSUE THREAD

**Issue by mozkan007** [uBlockOrigin/uAssets#288]
Hi,
I added  uBO-Personal-Filters‎ to Ublock Origin.There is "###comments" filter rule in the list and thus this filter rule is blocking comment section of any site.You can reproduce  this issue on [http://www.sinemalar.com/film/236219/sully] . So how can I allow to this "###comments" filter rule?I hope I could tell you to my problem.Thanks.

**Comment by gorhill** [comment]
I don't know what is "uBO-Personal-Filters‎", it's not from the project here. Report to whoever is maintaining that filter list.

**Comment by gorhill** [comment]
Meanwhile to override the cosmetic filter, use `#@##comments`.
