### ISSUE TITLE
Posts on Facebook Containing the String "Suggested" Being Hidden

### ISSUE THREAD

**Issue by sebastianbell** [uBlockOrigin/uAssets#2885]
### URL(s) where the issue occurs

https://www.facebook.com/

### Describe the issue

Using the exact string "Suggested" (no quotes, initial cap) anywhere in the content of any Facebook post (groups, feed, etc.) "removes" the post.

### Screenshot(s)

uBlock off (expected): https://i.imgur.com/fF9ovPP.png

uBlock on:  https://i.imgur.com/EVWL0wv.png

### Versions

- Browser/version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- uBlock Origin version: 1.16.12

### Settings

Default settings

**Comment by uBlock-user** [comment]
You can add `facebook.com#@#.userContentWrapper:has-text(/Suggested|Proponowany/)` until this issue is addressed.

**Comment by okiehsch** [comment]
I will remove the filter. I do not have a facebook account, so if the removal causes some ads to show up somebody else will have to add a fix.

**Comment by ghajini** [comment]
i see this
`popular across facebook`  & `suggested pages`
![screenshot 23](https://user-images.githubusercontent.com/20338483/43047933-08f0f7bc-8dfd-11e8-8637-5b733ee7aaa6.png)
