### ISSUE TITLE
quora.com - Missed ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#289]
I am seeing "**Promoted by**" ads on `https://www.quora.com/`, these are text based ads but track the user when clicked upon. They appear below the question and another one below the initial answer.

**SS:** https://i.imgur.com/cLdD8VC.png
**Error URL:**  `https://www.quora.com/How-much-would-Wikipedia-be-worth-if-it-were-a-business`

Note: Using **_uBO v1.10.4_** on **_Chrome 56_** with default settings.

**Comment by gorhill** [comment]
Does this work?

    ##.layout_2col_main > div[id]:has(.PromotedLink)

**Comment by gotitbro** [comment]
@gorhill Works but only for the ad below the question not for the ad below the first/initial answer.

**Comment by mapx-** [comment]
add
`quora.com##.upper_content:has(.PromotedLink)`

**Comment by gotitbro** [comment]
@mapx- Filter works for both ads, thanks.

**Comment by gorhill** [comment]
> add
> `quora.com##.upper_content:has(.PromotedLink)`

Probably better, as it selects the whole containing div:

    quora.com##.pagedlist_item:has(.PromotedLink)

**Comment by gotitbro** [comment]
@gorhill I have started seeing ads that appear on overlay answers on the home page feed. These ads appear at the bottom of these overlay answers with the tag "**Ads by**".

**SS:** http://i.imgur.com/RBT4vJQ.png
**Error URL:** https://www.quora.com

The ads do not appear on every answer overlay, here is a video screencapture I have created to explain the issue much better: https://vimeo.com/208098121

**Test account for [quora.com](https://www.quora.com)**:
_**Email:**_ _dnanr@mailed.ro_
_**Password:**_ _test#account567_

**Comment by gorhill** [comment]
Did you try to find out if you can filter it using standard filter syntax? Did you try to use element picker?

**Comment by gotitbro** [comment]
@gorhill I was getting the random div id when trying to hide the hide, turns out it was nested in a fixed class and the following filter should work:
`quora.com##.modal_promoted_content`

You can test yourself by using the test account above, if you get a notice to verify your login here is a link to the email account: https://mytemp.email/2/#!/inbox/dnanr@mailed.ro/05f3850d

**Comment by SMed79** [comment]
```
quora.com##.core_promo
quora.com##.PromptsList
quora.com##.content_marker
quora.com##.modal_promoted_content
```
from https://forums.lanik.us/viewtopic.php?p=107570#p107570 ...

**Comment by gotitbro** [comment]
@gorhill  I thought the filter I added `quora.com##.modal_promoted_content` will work for the issue mentioned here https://github.com/uBlockOrigin/uAssets/issues/289#issuecomment-286044324 but apparently its not.

I am not sure how to hide these ads that appear on answer popups (as detailed in the issue above). Filters from element picker and standard filters don't seem to be working. Please help.

**Comment by mapx-** [comment]
I get no such ad trying with one my account. Your account does not work.

your link:
https://www.quora.com/Can-technology-become-the-reason-for-human-life-destruction-in-future/answer/Tanmay-Lata

**Comment by gotitbro** [comment]
@mapx- These ads do not appear on specific **_quora.com_** posts but on the homepage https://www.quora.com (much like the _Facebook News Feed_), they appear when clicking to view answers in the feed as captured in the video: https://vimeo.com/208098121

I have already `quora.com##.modal_promoted_content` which should select the ad but isn't. Here is the screenshot of the element selected in the **_Dev Console_**:
![screenshot 19](https://cloud.githubusercontent.com/assets/20359493/24317130/7c86ac3c-111a-11e7-9ef1-38d120345a73.png)

**Comment by mapx-** [comment]
try
```
quora.com##.upper_content:has(.PromotedLink)
quora.com##.upper_content:has(.promoted_link)
```

**Comment by gotitbro** [comment]
@mapx- Not sure if `:has` filters appear in the logger but the ads haven't appeared ever since I added the above filters (nothing in the logger though).

**Comment by gotitbro** [comment]
@okiehsch @gorhill The filters previously added to uBO Filters https://github.com/uBlockOrigin/uAssets/commit/1a92b5439c1b4f7d9ba1ae4444ca1b1ad7550b31 do not work: https://forums.lanik.us/viewtopic.php?p=115365#p115365).

This filter `quora.com##.upper_content:has(.promoted_link)` by @mapx- should work for both the in feed ads and the previously reported ones as well.

**Comment by gotitbro** [comment]
@okiehsch I am again seeing the ads on Quora.

**SS:** https://i.imgur.com/fEemsBy.png
**Error URL:** `https://www.quora.com/What-type-of-people-should-I-not-trust-in-life`

**Comment by gotitbro** [comment]
@okiehsch Yet again I have started seeing the ads on Quora.

**Error URL:** `https://www.quora.com/South-Korea-Why-do-Korean-Won-have-big-denominations`

**Comment by gotitbro** [comment]
@okiehsch Still getting these ads on Quora. After the first answer and in between answers.

**Error URL:** 
`https://www.quora.com/Which-was-the-first-mobile-phone-provider-in-india-And-which-company-was-the-first-cellular-network-provider`

**Comment by mapx-** [comment]
it's not `"Still getting these ads on Quora"` , they simply updated their approach.

**Comment by gotitbro** [comment]
@mapx- Sorry, I wanted to say the same thing as in the previous comment. But I thought repeating it would make me seem like a parrot or bot :(

**Comment by gotitbro** [comment]
@okiehsch Seeing the ads on Quora again (below the question, the first answer; and in between other answers).

**Error URL:** 
`https://www.quora.com/What-is-the-best-logo-ever-created-Best-being-defined-as-a-logo-that-is-memorable-and-has-a-voice-of-its-own`

**Comment by gotitbro** [comment]
Looks like the ads are back again on Quora (below the question).

**Error URL:** `https://www.quora.com/What-does-the-number-of-seconds-written-on-a-Google-search-signify`

**Comment by mapx-** [comment]
I see no ad, upload a screenshot

**Comment by gotitbro** [comment]
@mapx- Here: https://i.imgur.com/TQB2xft.png

**Comment by mapx-** [comment]
I still cannot reproduce, try:
`quora.com##.upper_content:has(.advertiser_url)`

**Comment by gotitbro** [comment]
@mapx- Sorry for the late reply. The filter works, all ads are hidden on the page should be added to the list.

**Comment by gotitbro** [comment]
@mapx- The ads are being displayed again on https://www.quora.com (below the question; and first and second answers).

**SS:** https://i.imgur.com/7QOYbte.png

**Error URL:** `https://www.quora.com/How-can-I-find-the-LinkedIn-user-profile-based-on-their-email-address-through-LinkedIn-API`

_**Note:** Using uBO 1.15.18 on Chrome 65 with the default filters and settings._

**Comment by okiehsch** [comment]
`quora.com##.content_container:has(.featured_text_wrapper)`

**Comment by gotitbro** [comment]
@okiehsch Thanks, the filter works should be added to the list.

**Comment by mapx-** [comment]
already fixed by easylist, update the list & test again
https://github.com/easylist/easylist/commit/0f4cc9bdf1128a5ca0f008467f3d789cd663b455

**Comment by zaphodbeebblebrox** [comment]
Quora ads are back again.

**Comment by mapx-** [comment]
I get no ad, example page ?

**Comment by zaphodbeebblebrox** [comment]
Just `https://www.quora.com/`
![image](https://user-images.githubusercontent.com/22801430/40662191-a44b275a-6323-11e8-8b50-7ae8cacd5598.png)

**Comment by mapx-** [comment]
Weird, still nothing.

**Comment by zaphodbeebblebrox** [comment]
It might require an account?

**Comment by mapx-** [comment]
sure, I tested using an account.
