### ISSUE TITLE
[Breakage] kanald.com.tr

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2890]
### URL(s) where the issue occurs

`https://www.kanald.com.tr/askimemnu/39-bolum/4037`

### Describe the issue

Video doesn't play. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/42726386-b165f4be-8750-11e8-98f3-b4d91d6bba7d.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.12

### Settings

English default. Tried with `IDN: ABPindo`, didn't change anything.

**Comment by okiehsch** [comment]
@jspenguin2017 just fyi that is a turkish website, so `TUR: Adguard Turkish Filter` is the associated regional list.
@zaphodbeebblebrox `js.dogannet.tv/q/s/player/html5` is already allowed in that regiona list, so the filter can be removed.

**Comment by jspenguin2017** [comment]
Google Translate thinks it's Indonesian...
