### ISSUE TITLE
Broken page on rsaconference.com

### ISSUE THREAD

**Issue by Myer** [uBlockOrigin/uAssets#290]
### URL(s) where the issue occurs

`https://www.rsaconference.com/events/us17/agenda/sessions`

### Describe the issue

The whole list of sessions & events is missing.

### Screenshot(s)

![rsaconference](https://cloud.githubusercontent.com/assets/2845251/22628205/43bc5aec-ebd0-11e6-900b-9b734aad71c2.PNG)

### Versions

- Browser/version: Firefox 51.0.1 (64-Bit) & Edge 38.14393.0.0
- uBlock Origin version: 1.10.6 (Firefox), 1.10.2 (Edge)

### Notes

Looks like the reason is the static filter `||getclicky.com` which is inside "Malvertising filter list by Disconnect" and "Peter Lowe’s Ad and tracking server list".
At least for Edge the list is shown when I allow this request.

**Comment by okiehsch** [comment]
Does 
`||getclicky.com^$script,redirect=noopjs,domain=rsaconference.com`
work with Edge?

**Comment by Myer** [comment]
In Firefox this works, Edge still doesn't show the "sessions & events" if I add your line.
This is how it looks in the logger with Edge:

![logger](https://cloud.githubusercontent.com/assets/2845251/22628993/55c757ec-ebde-11e6-891b-7ac96fd88cbb.PNG)

**Comment by okiehsch** [comment]
Seems to be a Edge specific problem, only workaround that I can see for now is to allow
that request if you use Edge and report it at https://github.com/nikrolls/uBlock-Edge.
`||getclicky.com^$script,redirect=noopjs,domain=rsaconference.com` works with Chrome and Firefox,
 so I will add it to a uBlock filter list.
