### ISSUE TITLE
popup blocked but redirected to another site

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#291]
### URL(s) where the issue occurs

`https://www.worldfree4u.lol/category/300mb-movies/`

### Describe the issue

1. go to above link
2.click anywhere on page, popup will be opened and closed simjltaneously but redireced to another sites as shown in ss
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]
![screenshot 121](https://cloud.githubusercontent.com/assets/20338483/22694193/3923e634-ed6c-11e6-93b3-c74d8515e526.png)

### Versions

- Browser/version: opera browser 43.0.2442.806 (PGO)
- uBlock Origin version: 1.11.0

### Settings

- uBO's default settings

### Notes

similar browser chrome doesn't show problem letting me think that ublock origin is actively developed for chrome only

**Comment by gorhill** [comment]
> letting me think that ublock origin is actively developed for chrome only

You assumed wrong. uBO is developed for Chromium, which makes it compatible with both Chrome and Opera and whatever other Chromium-based browser. I could reproduce with Chrome -- just clear cookies before each test.

Also, this is a case of popunder.

**Comment by ghajini** [comment]
in my chrome after clearing cookies, popups/popunders are not opened from that site

**Comment by gorhill** [comment]
> seriously?

That is with Chrome and without the fix:

![a](https://cloud.githubusercontent.com/assets/585534/22695288/4470d276-ed18-11e6-9a7f-e0323eb64e4c.png)

If you can't reproduce in Chrome you will have to figure why yourself -- it could also be that the script on the page is behaving randomly such that sometimes the popups are generated in different manners.
