### ISSUE TITLE
identi.li [Anti-Adblock]

### ISSUE THREAD

**Issue by bestemutter** [uBlockOrigin/uAssets#2910]
### URL(s) where the issue occurs

`https://www.identi.li/index.php?topic=514137`

### Describe the issue

Anti-adblock

### Screenshot(s)

![ww141w identi li_index php_topic 514137 ipad pro](https://user-images.githubusercontent.com/41264459/42734902-e4d862a4-884b-11e8-8256-12262e14b30f.png)

![redirector desbloqueadnnnnor org__ ipad pro](https://user-images.githubusercontent.com/41264459/42734926-3fe2eb24-884c-11e8-84ee-35a8d90fe716.png)

![larosquilla com_sacrificaron-gorila-zoologico-proteger-nino_ ipad pro](https://user-images.githubusercontent.com/41264459/42734315-ff4897c6-8841-11e8-8b23-7f1be16804e6.png)

### Versions

- Browser/version: Chrome 67
- uBlock Origin version: 1.16.12

### Settings

Default settings.

### Notes

You have to click on Ver Links De Descarga and HAZ CLIC AQUI

**Comment by lain566** [comment]
@okiehsch Can you add these filters? to show the link directly
```
identi.li##+js(set-constant.js, t_spoiler, 0)
identi.li##+js(nano-setInterval-booster.js, , ,0.02)
```

test link
`https://www.identi.li/index.php?topic=527409`

![Anotación 2019-05-31 010242](https://user-images.githubusercontent.com/27441315/58670583-e2a2a900-833f-11e9-9c5e-bceb654a9f1d.png)
