### ISSUE TITLE
christianforums.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#2911]
### URL(s) where the issue occurs

`https://www.christianforums.com/`
`https://www.christianforums.com/threads/what-s-really-wrong-with-society.8073175/`

### Describe the issue

Banner after first featured thread on the frontpage.
Banner after first post on a thread page.

### Versions

- Browser/version: Firefox 61.0.1 
- uBlock Origin version: uBlock Origin 1.16.12

### Settings

Default.

**Comment by okiehsch** [comment]
Add
`christianforums.com##[href^="http://go.tryonlinetherapy.com/"]`
to your filter list.
