### ISSUE TITLE
EasyList broke KimCartoon Functionality

### ISSUE THREAD

**Issue by Ziko577** [uBlockOrigin/uAssets#2914]
It's been several days but I still have trouble navigating KimCartoon.me despite some filters I put in. The search bar doesn't work and the slider for shows is not working. I'm using the advanced search now and that's all I can do. Videos play fine though and I tried using the logger to get the site to work but I am having trouble identifying what is causing this behavior. I'm on Pale Moon 27.9.3 and am using uBlock Origin 1.16.4.2. I suspect EasyList broke something somewhere. These filters helped to restore the videos for me: 

kimcartoon.me###my_video_1:style(display: block!important;)
kimcartoon.me###my_video_1_html5_api:style(display: block!important;)

Also, these are the current ones I am using as well as my Filter Lists:

kimcartoon.me##.videoAdClose
kimcartoon.me###hideAds
kimcartoon.me##.w-right
##.kcAds
||kimcartoon.me^$csp=script-src 'self' 'unsafe-eval' 'unsafe-inline' *.zencdn.net blob:
||kimcartoon.me^$csp=connect-src 'self'
kimcartoon.me##script:inject(abort-current-inline-script.js, document.createElement, jsc.mgid.com)
kimcartoon.me##script:inject(abort-current-inline-script.js, MutationObs

![filter lists](https://user-images.githubusercontent.com/6496151/42739203-0fc03c18-8882-11e8-86a9-cccc324280a7.jpg)

**Comment by okiehsch** [comment]
`||kimcartoon.me^$csp=script-src 'self' 'unsafe-eval' 'unsafe-inline' *.zencdn.net blob:` breaks search

![image](https://user-images.githubusercontent.com/16838044/42739273-b1a0158c-8894-11e8-8f99-c706ce1fc893.png)

What is this filter supposed to do?

**Comment by gwarser** [comment]
`kimcartoon.me##script:inject(abort-current-inline-script.js, MutationObs`

Something is lost.

**Comment by Ziko577** [comment]
Oh shit here's the correct one!: kimcartoon.me##script:inject(abort-current-inline-script.js, MutationObserver, 676574456c656d656

**Comment by okiehsch** [comment]
That filter, the MutationObserver one, is obsolete anyway, there is no inline-script at  `kimcartoon.me`
that it can abort.
If I remove 
`||kimcartoon.me^$csp=script-src 'self' 'unsafe-eval' 'unsafe-inline' *.zencdn.net blob:`
search works on my end,
![image](https://user-images.githubusercontent.com/16838044/42740169-bc29e2da-88a3-11e8-8f73-98486389394c.png)

**Comment by Ziko577** [comment]
I did remove the offending scripts but it still isn't doing anything now.

**Comment by okiehsch** [comment]
Have you tried `kimcartoon.me` with a default setup? I have no issues with it.

**Comment by Ziko577** [comment]
It didn't work sadly.

**Comment by okiehsch** [comment]
Do you have any other extensions installed?

**Comment by Ziko577** [comment]
Here's a screenshot: 
![extensions](https://user-images.githubusercontent.com/6496151/42740248-1075ff1e-8894-11e8-948b-2e38cbf7d0f1.jpg)

**Comment by okiehsch** [comment]
Any Greasemonkey scripts concerning kissanime?

The only way to break search using `uBO`, other than your `csp-filter` is to block 
`http://code.jquery.com/jquery-1.7.min.js`
You can look in your logger if something is blocking it.

**Comment by Ziko577** [comment]
It turns out it was a script I had for KissAnime. I could modify it so it won't screw up this site. It's only on my account and I installed it to counter the former's relentless assault of ads. I can have it be excluded and see what happens. You can close this issue now. I'm sorry I wasted ya'll's time!
