### ISSUE TITLE
Anti Adblock

### ISSUE THREAD

**Issue by Steiner29** [uBlockOrigin/uAssets#2918]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.investing.com/markets/united-states `

### Describe the issue

The above URL is showing an adblock warning that can't be removed. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/41305561/42778107-1155bc28-890a-11e8-9e0f-09149c87b857.png)

### Versions

- Browser/version: Google Chrome [67.0.3396.99]
- uBlock Origin version: [1.16.12]

### Settings

- [None]

**Comment by okiehsch** [comment]
I can't reproduce.
![image](https://user-images.githubusercontent.com/16838044/42780166-d01564b4-8942-11e8-81cf-f87e07ba3347.png)

Maybe the detection depends on the location.
@zaphodbeebblebrox can you reproduce?

**Comment by zaphodbeebblebrox** [comment]
I get nothing as well. They set a cookie called `adBlockerNewUserDomains`, so it is probably something time based.

**Comment by zaphodbeebblebrox** [comment]
To reproduce, lower the value of the cookie `adBlockerNewUserDomains`, which appears to just be the unix time of your first visit to the site. I lowered it to `143177033`.
