### ISSUE TITLE
linkshrink

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#292]
### URL(s) where the issue occurs

`linkshrink.net/7LUW44`

### Describe the issue

1.click anywhere in page and it opens too much popups ...

2.eventually closing legit one site also

### Screenshot(s)

`http://imgur.com/a/plKdq`

`http://imgur.com/a/S9cs9`

`http://imgur.com/a/HyDNY`

### Versions

- Browser/version: chrome Version 56.0.2924.87 (64-bit)

- uBlock Origin version: 1.11

### Settings

- uBO's default settings

### Notes

SeT `No popup` switch for site but site manages to bypass it...

looked in easylist; it seems they don't found solution

**Comment by okiehsch** [comment]
Does `linkshrink.net##script:inject(abort-on-property-write.js, _$_6a3f)`
work?

**Comment by ghajini** [comment]
works...
how to find these scripts for the page...
i don't want gorhill to lock my threads or block me...iam posting true things here
