### ISSUE TITLE
Google reCaptcha

### ISSUE THREAD

**Issue by Tealk** [uBlockOrigin/uAssets#2925]
Hello,

I just wanted to say that it would be enough to share script,XHR and frame:
```
Google reCaptcha
	* www.google.com
		_ www.google.com script
		_ www.google.com XHR
		_ www.google.com frame
		_ www.gstatic.com script
```

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/pull/1997

**Comment by gwarser** [comment]
>The only types which should be used explicitly in a recipe ruleset are the following: `*`, `script`, `frame` -- these are the only types needed to accommodate the strictest supported ruleset. There is an exception however: you may declare a rule for any other types if and only if this the only type necessary to unbreak the site.

@gorhill does this rule apply here? Is XHR third? Fourth? Or _only one additional_?

**Comment by gorhill** [comment]
It does not apply here since `_ www.google.com script` is also needed. With default ruleset, `_ www.google.com *` would fix both `script` and `xhr`.
