### ISSUE TITLE
[Ads bypass] Quora.com

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#2937]
Ads are being bypassed on Quora.

Here are the filters to fix this. 
```
www.quora.com##.FeedStory.feed_item > div > div:has-text(/Promoted/i)
www.quora.com##.FeedStory.feed_item > div > div:has-text(/by Quora for Business/i)
www.quora.com##.Toggle.SimpleToggle.ToggleAnswerFooterWrapper > div:has-text(/Promoted/i)
www.quora.com##.u-inherit > .FeedStory.feed_item:matches-css(height: 0px)
```

**Comment by gorhill** [comment]
Please provide a specific URL where this can be seen -- this eliminates all guesswork from our side.

**Comment by ReyCobin** [comment]
Quora.com (login required)

**Comment by ReyCobin** [comment]
You need all of them because of quora for business insted of promoted.
And www.quora.com##.Toggle.SimpleToggle.ToggleAnswerFooterWrapper > div:has-text(/Promoted/i)
is for ads inside the answers in the news feed.

**Comment by terrorist96** [comment]
Specific URLs included here #2404

**Comment by krystian3w** [comment]
Yes, but this rules not block for old specific links.

**Comment by uBlock-user** [comment]
Adguard filters are still working, I don't see any ads with these.

```
quora.com##.UnifiedAnswerPagedList > .paged_list_wrapper > div[id]:if(a[href][target="_blank"][rel="noopener nofollow"]:not(.external_link)
quora.com##.grid_page > .layout_2col_main > div[id]:not(.AnswerListDiv):not(.answer_text_small):not(:last-child):if(a[href][target="_blank"][rel="noopener nofollow"])
```

**Comment by krystian3w** [comment]
I see a little problem.

Rule one no have closed `:if`, I assume it is a copying error.

**Comment by silverbacknet** [comment]
Ah. Thanks, that did it. Finally tracked it down, only to find I was too late!
