### ISSUE TITLE
uptostream.com/voirfilms.ws [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2938]
URL(s) where the issue occurs

`https://uptostream.com/eu2tt6cy1e9q#=_=`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by okiehsch** [comment]
I can't reproduce.
![image](https://user-images.githubusercontent.com/16838044/42971892-0036311a-8bae-11e8-8e5f-358587ba654f.png)

**Comment by KiLL4FuNK** [comment]
`http://www.voirfilms.ws/tomb-raider.htm`

![](https://i.imgur.com/4l7Gyg0.png)

**Comment by KiLL4FuNK** [comment]
`https://ww1.voirfilms.ws/les-indestructibles-2-DjGlUSUzfq.htm`

ADS

**Comment by ghajini** [comment]
preroll ads in player
`https://uptostream.com/jhv1ll2ac71k`

**Comment by FanOfRootBeer** [comment]
it looks like they removed anti-adb from uptostream

any alive voirfilms site?
