### ISSUE TITLE
antiadblock

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#294]
### URL(s) where the issue occurs

`https://www.flashx.tv/1ek77pp2m6f1.html`

### Describe the issue

1.go to above site
2.click on proceed to video
3. you will next get " this is prohibited....." warning related to antiadblock

### Screenshot(s)

![screenshot 133](https://cloud.githubusercontent.com/assets/20338483/22853451/97a6fe5e-f07c-11e6-8eaa-c5cd87fb268c.png)

### Versions

- Browser/version: chrome Version 56.0.2924.87 (64-bit)

- uBlock Origin version: 1.11.0

### Settings

- uBO's default settings+antiadblock killer+adblock warning removal list
### Notes

 clear cookies ,restart browser to produce problem

**Comment by SMed79** [comment]
Try
```
||flashx.tv/js/code.js
@@/showad_.js$domain=flashx.tv
@@||educing.info/popunder.gif
@@/jquery2.js$domain=flashx.tv
```
(https://forums.lanik.us/viewtopic.php?p=112212#p112212)

**Comment by ghajini** [comment]
nothing works

**Comment by okiehsch** [comment]
Does 
`flashx.tv##script:inject(abort-on-property-write.js, admvpu)`
`||d31qbv1cthcecs.cloudfront.net/atrk.js$script,redirect=noopjs,domain=flashx.tv`
work?
And by work I mean can you watch the video.

**Comment by SMed79** [comment]
In ubo i get no anti adblock without any additionnel filters http://i.imgur.com/NdnXFZ7.png

**Comment by ghajini** [comment]
no works
adguard chrome `http://i.imgur.com/N7rpXb6.png`
ublock origin chrome http://imgur.com/a/SodlT
ublock origin opera http://imgur.com/a/YgKTo

**Comment by okiehsch** [comment]
> In ubo i get no anti adblock without any additionnel filters

Now I get no anti adblock with default settings either but I could reproduce @ghajini's 
issue literally 15 minutes ago, very strange.

@SMed79 I had to allow or redirect `atrk.js` to be able to play the video, if I blocked it
I got a `media could not be found` error

**Comment by mapx-** [comment]
- probably the site is broken, even disabling ubo + ubo extra I still get the anti adblocking message
- but there is an issue in ubo:

I whitelisted the site, refresh, and I get (in console):

contentscript.js:90 Uncaught Error: uBlock Origin: aborting content scripts for https://eu2.madsone.com/um/4/100271486834653000273/
    at contentscript.js:90
(anonymous)	@	contentscript.js:90

**Comment by ghajini** [comment]
@okiehsch 
no problem here with adguard
is site broken for adblock plus/related users

**Comment by mapx-** [comment]
@ghajini: disable all adblockers, does the site still work for you ?

**Comment by ghajini** [comment]
i have seperate chrome profiles for ublock origin and adguard
each profile having only 1 adblocking extension
even created 3rd profile with only ublock origin,ublock extra and no other extensions,,,
still produce

**Comment by mapx-** [comment]
disable **ALL** the adblockers: does the site works fine ? (I mean: no anti adblocking message)

**Comment by ghajini** [comment]
disabling all extensions
site works
`http://imgur.com/a/jtu7v`

**Comment by ghajini** [comment]
site is messy...ok to go with ''without extensions''[punishing adblock users randomly]

**Comment by gorhill** [comment]
Without any new filters, if I click "Or try to reload the page !! Click here !!", the video will load fine one second try.

**Comment by ghajini** [comment]
video won't play then after following your instructions
`http://imgur.com/a/ahxmb`

**Comment by ghajini** [comment]
@gorhill do you mind trying adguard??
It works there.........are you interested in solving this issue?

**Comment by ghajini** [comment]
Fixed  by ublock protector
