### ISSUE TITLE
aniteca.zlx.com.br [anti-adblock]

### ISSUE THREAD

**Issue by ialexsilva** [uBlockOrigin/uAssets#2943]
### URL(s) where the issue occurs

https://aniteca.zlx.com.br/2fXz5

### Describe the issue

Show a big banner asking for disable adblock 

### Versions

- Browser/version: Chrome 67.0.3396.99 x64 bits
- uBlock Origin version: uBlock Origin 1.16.12

### Settings

- uBlock Default + Adguard’s Annoyance List + spa, por: Adguard Spanish/Portuguese

### Notes

To fix this im add the following rule:
`@@||aniteca.zlx.com.br/themes/flow/frontend_assets/js/advertisement.js$script,domain=aniteca.zlx.com.br`

**Comment by okiehsch** [comment]
This can be fixed without allowing that `script`.
Aborting this
![unbenannt](https://user-images.githubusercontent.com/16838044/42972835-2b138376-8bb1-11e8-8b24-577e675d3113.PNG)
`inline-script` disables the anti-adblock message and is the preferable fix.
