### ISSUE TITLE
coolgames.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2946]
URL(s) where the issue occurs

`http://www.coolgames.com/es/two-player-checkers.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67.0.3396.99 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by krystian3w** [comment]
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=www.coolgames.com`

maybe anyone find better solution / workaround.

**Comment by okiehsch** [comment]
@krystian3w that request has to be allowed, see https://github.com/uBlockOrigin/uAssets/issues/2889#issuecomment-405040048
