### ISSUE TITLE
Ad bypass on owaahh.com

### ISSUE THREAD

**Issue by RobertOrinCharles** [uBlockOrigin/uAssets#2948]
### URL(s) where the issue occurs

`http://owaahh.com/`

### Describe the issue

An ad is being loaded on the home page and all other pages on the site.

### Versions

- Browser/version: Firefox 61.0.1
- uBlock Origin version: 1.16.14

### Settings

- Default

### Notes

This filter seems to fix this.

`owaahh.com###text-13 > .textwidget`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/2949#issuecomment-406719766
