### ISSUE TITLE
Youtube.com pre-roll

### ISSUE THREAD

**Issue by JoshSchreuder** [uBlockOrigin/uAssets#295]
### URL(s) where the issue occurs

Any video that has monetisation enabled, eg.
`https://www.youtube.com/watch?v=nWsoIgHzsEM`
`https://www.youtube.com/watch?v=zrW85fDSq-U`
`https://www.youtube.com/watch?v=2nc9AFcKIuM`

### Describe the issue

Pre-roll ads are no longer caught by uBlock. Looks like a change to Youtube's ad serving scheme. It appears as though ads are being served from YT servers, eg.

`https://r2---sn-ppoxu-ntqe.googlevideo.com/videoplayback?lmt=1485798792862107&expire=1487318234&gir=yes&mime=video%2Fwebm&requiressl=yes&source=youtube&clen=1360684&upn=EhGgsMyQXW0&signature=5360080006FDA15E840CBF6379E736AE6824E1B3.DDCB191FBE919D91A0EEC186DD0B6A202F87C96D&key=yt6&ctier=L&itag=248&ms=au&initcwndbps=1327500&mv=m&dur=5.756&mt=1487296523&id=o-AGso5w9OXzsz97o2tMgWtnyyEf4qSyVa7Fu18pLnk_sP&sparams=clen%2Cctier%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&pl=19&mn=sn-ppoxu-ntqe&ip=REDACTED&mm=31&alr=yes&keepalive=yes&ratebypass=yes&cpn=rbHvvRr6wNaYnHJU&c=WEB&cver=1.20170214&range=0-472787&rn=2&rbuf=0`

### Versions

- Browser/version: Chrome 56.0.2924.87 (64-bit)
- uBlock Origin version: 1.11.0

### Settings

- Advanced user
- All 3 privacy options checked
- Running uBlock Origin Extra

### Notes

As mentioned above, ads appear to be coming from `googlevideo.com` in a similar way to normal videos. I did see a note somewhere (Reddit?) that it might only be happening for logged in users, but I can't confirm.

Normal video:
`https://r4---sn-ppoxu-ntqe.googlevideo.com/videoplayback?gir=yes&upn=g84vHV7jlRk&mime=audio%2Fwebm&ipbits=0&initcwndbps=1341250&expire=1487318202&keepalive=yes&ip=REDACTED&requiressl=yes&itag=251&lmt=1487043051442864&id=o-APy8bqgIWoeqaX1oA_uanGwYdO0JEL3pUCTBrUAX4RWC&dur=577.721&source=youtube&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&mm=31&mn=sn-ppoxu-ntqe&ei=WlimWMrjAYKJ8wS04LeACQ&ms=au&mt=1487296520&mv=m&pl=19&clen=8950931&signature=12756CB1A875628AB285B760FDEEEA04F6D0FC6B.94060F6B688E7D27531CE1644010F107FFE053AF&alr=yes&ratebypass=yes&cpn=Bbv8Z7QPrZUgS1wz&c=WEB&cver=1.20170214&range=1711238-2028205&rn=22&rbuf=108809`

Ad:
`https://r2---sn-ppoxu-ntqe.googlevideo.com/videoplayback?lmt=1485798792862107&expire=1487318234&gir=yes&mime=video%2Fwebm&requiressl=yes&source=youtube&clen=1360684&upn=EhGgsMyQXW0&signature=5360080006FDA15E840CBF6379E736AE6824E1B3.DDCB191FBE919D91A0EEC186DD0B6A202F87C96D&key=yt6&ctier=L&itag=248&ms=au&initcwndbps=1327500&mv=m&dur=5.756&mt=1487296523&id=o-AGso5w9OXzsz97o2tMgWtnyyEf4qSyVa7Fu18pLnk_sP&sparams=clen%2Cctier%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&pl=19&mn=sn-ppoxu-ntqe&ip=REDACTED&mm=31&alr=yes&keepalive=yes&ratebypass=yes&cpn=rbHvvRr6wNaYnHJU&c=WEB&cver=1.20170214&range=0-472787&rn=2&rbuf=0`

**Comment by SMed79** [comment]
I get no video ads. Can you reproduce in firefox ?

Test olso using a portable version of browser:
- http://portableapps.com/apps/internet/firefox_portable
- http://portableapps.com/apps/internet/google_chrome_portable

PS: _Edit your post and remove your ip from the url 59.167.x.x_

**Comment by JoshSchreuder** [comment]
> I get no video ads. Can you reproduce in firefox ?

I cannot.

> Test olso using a portable version of browser:
> 
> http://portableapps.com/apps/internet/firefox_portable
> http://portableapps.com/apps/internet/google_chrome_portable

Same with this.

Both logged in and logged out, I don't get ads.

Yet with my logged in main Chrome instance I do, and logging out stops the ads. Maybe there's some session storage experiment type thing YT is using.

With that said, it's started in the last week or so (I've been using uBO for a loooong time, even before it was called uBO 😄), and I'm not the the only one to have this issue in the last week.
[Example](https://www.reddit.com/r/uBlockOrigin/comments/5ua042/youtube_ads_getting_through/)
[Example 2](https://www.reddit.com/r/uBlockOrigin/comments/5teict/youtube_video_ads_are_not_blocked/)

**Comment by uBlock-user** [comment]
Can't reproduce it. The video loads and I see nothing else.

**Comment by lassekongo83** [comment]
Most likely geo locked ads in counties where YouTube Red is available.

**Comment by ajithhub** [comment]
FWIW,  After some poking...  If i block requests to https://www.youtube.com/get_video_info*, I see no preroll ads as a logged in user in the US.

**Comment by gorhill** [comment]
> If i block requests to `https://www.youtube.com/get_video_info*`, I see no preroll ads

This should be reported to EasyList maintainers.

**Comment by SMed79** [comment]
> This should be reported to EasyList maintainers.

Reported but no one can reproduce https://forums.lanik.us/viewtopic.php?p=113090#p113090

**Comment by rsalmond** [comment]
@lassekongo83 fwiw, even though I cannot replicate with the links posted above I have started to see ads slip through on Youtube here in Canada where Red is very much to my annoyance still not available.

**Comment by ajithhub** [comment]
FYI, I updated my rule to scope it to youtube.com only.  Blocking it on a site that embedded a video prevents the video from starting.  I reported that same in the wasylist forum.

`youtube.com##https://www.youtube.com/get_video_info*`

**Comment by SMed79** [comment]
> FYI, I updated my rule... youtube.com##https:....

@ajithhub  Your filter is invalid 
* https://adblockplus.org/filters
* https://forums.lanik.us/viewtopic.php?p=114030#p114030

**Comment by kowith337** [comment]
Thailand here.
As default setting with Chromium 58.0.3016.0 (NoSync), I cannot reproduce.
No pre-roll ads, no yellow mark at seek bar.
Even use Browsec VPN to switch to Netherlands, Singapore, UK and US.

**Comment by ajithhub** [comment]
> @ajithhub Your filter is invalid
@SMed79 You are right.  I didn't test my attempt to scope the rule well.   The original rule still works, but prevents the embedded player from working for me.   I tried to follow the adblock "Limiting rules to certain domains" section, but I must not be doing it right.  I updated on the forum too.

**Comment by kowith337** [comment]
Is it because of QUIC?
gorhill/uBlock#2562

**Comment by Enzime** [comment]
From my research, it appears that some pre-roll ads are now YouTube videos, and some of the information regarding them is already embedded in normal YouTube watch requests, however as not all of the information is embedded, and thus YouTube is making additional requests which can be filtered out.

When I open a YouTube video, then switch to another YouTube video, I get a request to:

     https://www.youtube.com/watch?v=<video-id>&pbj=1

I suspect that the `pbj=1` means return a JSON response.

Opening this page manually returns a `{"reload":"now"}`, however when I check the response given when YouTube requested the page, the returned JSON has `playerAds` as a key inside `playerResponse` and also includes references to `gmTtT0yKvTY` which is the YouTube video ID of a pre-roll ad.

I believe it's only after it gets given the playerAds through this page, it'll later go onto request data for the ad from pages like:

    https://www.youtube.com/get_video_metadata?video_id=gmTtT0yKvTY&html5=1&page_subscribe=0
    https://www.youtube.com/get_video_info?html5=1&video_id=gmTtT0yKvTY

As far as I can tell, both `get_video_metadata` and `get_video_info` are only requested for pre-roll ads, although I have only looked at the requests made from `watch?v=<video-id>`.

Ad (Apple / iPhone / iPhone 8 Reveal / AU / Non-Carrier / PreRoll):

    https://www.youtube.com/watch?v=gmTtT0yKvTY

Most of this research was from this video:

      https://www.youtube.com/watch?v=nYCURBSSyXw

Although I don't believe the specific video matters as the pre-roll ad doesn't show everytime. To find a pre-roll ad I just opened a playlist and kept clicking next until a pre-roll displayed.

**Comment by terrorist96** [comment]
I'm getting pre-roll YouTube ads.
