### ISSUE TITLE
Wormax.io

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uAssets#2953]
### URL(s) where the issue occurs

`http://wormax.io`

### Describe the issue

After logging into the game and playing for the first time and then losing, I start playing again and the page is reloaded, and the "number of blocks increases and increases, etc". And it happens every time I play again.

### Versions

- Browser/version: Opera Browser 54.0.2952.54
- uBlock Origin version: 1.16.14

### Settings

- All selected filters, and Spanish filters.

**Comment by okiehsch** [comment]
> number of blocks increases and increases, etc

So what exactly is the problem? If you reload a page the number of blocked requests will increase,

I can play the game without any noticable issue.

**Comment by MS-PC** [comment]
The game if it works, what happens is every time I lose and start again, the number of blocks increases and increases. But if you think that something of importance does not close this issue.

Note: It is something that seems strange to me that the number of blocks is increasing and also a little annoying.
