### ISSUE TITLE
[Anti-adblock] FanSided Network websites

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#2954]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

Choose anything from here: https://fansided.com/network/
Network has 300+ websites and anti-adblock is not blocked on most of them.
Example:
https://atlallday.com/
https://thebaltimorewire.com/

### Describe the issue

I'm using Nano Adblocker + Nano Defender. Everything is up-to-date. Still they won't let me to browse sites without disabling adblocker.

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: Nano adblocker latest

### Settings

Default

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
`example.com##script:inject(abort-on-property-read.js, HTMLScriptElement)` should work for all affected websites.
If somebody can make a list of those hundreds of websites, preferably alphabetically ordered, I will add it.

**Comment by SkeletalDemise** [comment]
I made a filter with all 304 alphabetized FanSided sites. Your welcome. Pastebin: `https://pastebin.com/hatFYK3x`

**Comment by ZaphodBeebblebrox** [comment]
Here you go
<details><summary>List of sites</summary>

12thmanrising.com
1428elm.com
8points9seconds.com
acceptthisrose.com
airalamo.com
allfortennessee.com
allstokedup.com
allucanheat.com
amazonadviser.com
americansundercover.com
apptrigger.com
aroundthefoghorn.com
aroyalpain.com
arrowheadaddict.com
artofgears.com
atlallday.com
autzenzoo.com
awinninghabit.com
badgerofhonor.com
balldurham.com
bamahammer.com
bamsmackpow.com
bayernstrikes.com
bealestreetbears.com
beargoggleson.com
behindthebuckpass.com
believelandball.com
beyondtheflag.com
beyondwestworld.com
bigeasybeliever.com
bigredlouie.com
birdswatcher.com
blackandteal.com
blackhawkup.com
blackoutdallas.com
bladesofteal.com
bleedinblue.com
bloggingdirty.com
blogoflegends.com
blogredmachine.com
bluelinestation.com
bluemanhoop.com
boilingwithbias.com
boltbeat.com
boltsbythebay.com
bosoxinjection.com
bricksareawesome.com
broadstreetbuzz.com
buffalowdown.com
bustingbrackets.com
bvbbuzz.com
cagepages.com
callsaulnow.com
calltothepen.com
caneswarning.com
capedcrusades.com
cardiaccane.com
catcrave.com
causewaycrowd.com
champagneandshade.com
chopchat.com
chowderandchampions.com
cincyontheprowl.com
cityofchampionssports.com
claireandjamie.com
claretvillans.com
climbingtalshill.com
clipperholics.com
clonesconfidential.com
cubbiescrib.com
culturess.com
dailyddt.com
dailyknicks.com
dairylandexpress.com
dawgpounddaily.com
dawindycity.com
dawnofthedawg.com
dearoldgold.com
deathvalleyvoice.com
detroitjockcity.com
devilsindetail.com
diredota.com
districtondeck.com
doctorwhowatch.com
dodgersway.com
dogoday.com
dorksideoftheforce.com
duffanddonuts.com
dunkingwithwolves.com
ebonybird.com
editorinleaf.com
emeraldcityswagger.com
empirewritesback.com
everythingbarca.com
eyeonbond.com
eyesonisles.com
factoryofsadness.co
fansided.com
fansoftaylor.com
fantasycpr.com
fightinggobbler.com
flameforthought.com
flywareagle.com
foodsided.com
foregals.com
foreverfortnite.com
foxesofleicester.com
friarsonbase.com
frozenfutures.com
garnetandcocky.com
gbmwolverine.com
geeksided.com
gigemgazette.com
glorycolorado.com
gmenhq.com
gojoebruin.com
goldandgopher.com
goldengatesports.com
gonepuckwild.com
greenstreethammers.com
guiltyeats.com
hailfloridahail.com
hailwv.com
halohangout.com
hardwoodhoudini.com
heatwaved.com
hercape.com
hiddenremote.com
highposthoops.com
hookemheadlines.com
hoopshabit.com
hoosierstateofmind.com
horseshoeheroes.com
hotspurhq.com
houseofhouston.com
howlinhockey.com
hoyosrevenge.com
huluwatcher.com
huskercorner.com
inkonindy.com
insideibrox.com
insidethebbhouse.com
insidetheiggles.com
insidetheloudhouse.com
jaysjournal.com
jetswhiteout.com
jugofsnyder.com
justblogbaby.com
justfantasybaseball.com
kardashiandish.com
kckingdom.com
keepingitheel.com
kingjamesgospel.com
kingsofkauffman.com
lakeshowlife.com
lasportshub.com
lastnighton.com
lawlessrepublic.com
lightlybuzzed.com
lobandsmash.com
localpov.com
lombardiave.com
mancitysquare.com
marlinmaniac.com
maroonandwhitenation.com
milehighmaniac.com
milehighsticking.com
mlsmultiplex.com
motorcitybengals.com
mtgsideboard.com
musketfire.com
netflixlife.com
newcastletoons.com
nflmocks.com
nflspinzone.com
ninernoise.com
nolanwritin.com
nothinbutnets.com
nugglove.com
octopusthrower.com
oilonwhyte.com
oldnorthbanter.com
olehottytoddy.com
onechicagocenter.com
orlandomagicdaily.com
paininthearsenal.com
pelicandebrief.com
penslabyrinth.com
phinphanatic.com
pippenainteasy.com
pistonpowered.com
playingfor90.com
pokespost.com
predlines.com
predominantlyorange.com
princerupertstower.com
progolfnow.com
puckettspond.com
puckprose.com
pucksandpitchforks.com
pucksofafeather.com
purpose2play.com
raisingzona.com
ramblinfan.com
raptorsrapture.com
rayscoloredglasses.com
razorbackers.com
redbirdrants.com
reddevilarmada.com
redshirtsalwaysdie.com
reignoftroy.com
reviewingthebrew.com
rhodyrampage.com
rhymejunkie.com
riggosrag.com
rinkroyalty.com
ripcityproject.com
risingapple.com
roxpile.com
rubbingtherock.com
rumbunter.com
rushthekop.com
sabrenoise.com
saintsmarching.com
saturdayblitz.com
scarletandgame.com
section215.com
senshot.com
showsnob.com
sidelionreport.com
sircharlesincharge.com
slapthesign.com
smartcarting.com
soaringdownsouth.com
sodomojo.com
southboundanddown.com
southsideshowdown.com
spacecityscoop.com
spartanavenue.com
spnhunters.com
sportdfw.com
sportingsota.com
starsandsticks.com
starstepping.com
statliners.com
stillcurtain.com
stormininnorman.com
stripehype.com
survivingtribal.com
swarmandsting.com
tenntruth.com
terrapinstationmd.com
thatballsouttahere.com
thebaltimorewire.com
thecanuckway.com
thecelticbhoys.com
thecruelestsport.com
thehuskyhaul.com
thejetpress.com
thejnotes.com
thelandryhat.com
theoutsidegame.com
thepewterplank.com
theprideoflondon.com
therattrick.com
therealchamps.com
thesixersense.com
thesmokingcuban.com
thesoapies.com
thetopflight.com
thevikingage.com
thisisuscrying.com
throughthephog.com
thunderousintentions.com
tipofthetower.com
titansized.com
tomahawktake.com
torotimes.com
trumanstales.com
turnthatchair.com
twinpeaksfans.com
undeadwalking.com
underthelaces.com
unionandblue.com
valleyofthesuns.com
vegashockeyknight.com
venomstrikes.com
victorybellrings.com
viridianforest.com
vivaligamx.com
wakeupmrwest.com
whateveraspidercan.com
whitecleatbeat.com
whodatdish.com
wildcatbluenation.com
winteriscoming.net
withthefirstpick.com
wizardsandwhatnot.com
wizofawes.com
wreckemred.com
writingillini.com
yanksgoyard.com
yellowjackedup.com
zonazealots.com

</details>

**Comment by okiehsch** [comment]
Thank you.

I have not checked all domains, but the few I randomly picked all had the ant-adblock message, so I will add them all.

**Comment by SkeletalDemise** [comment]
I don't think there's really an easy way to check all the domains.

**Comment by SkeletalDemise** [comment]
Also, you forgot to delete one duplicate, `lastnighton.com`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/99366d9c451b4b4cc753024aa53e2b2b38eb3daf
