### ISSUE TITLE
plg.ovakode.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2957]
URL(s) where the issue occurs

`https://plg.ovakode.com/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67.0.3396.99 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.12

Settings

Default

**Comment by KiLL4FuNK** [comment]
generate link

http://uploaded.net/file/ql0eo2m4/O720DRONES-MVRLS.part1.rar

**Comment by krystian3w** [comment]
`@@||plg.ovakode.com^$generichide` or other smaller exception?

**Comment by krystian3w** [comment]
`https://earn-url.com/swU6` - in loop earn money blocked site:

![obraz](https://user-images.githubusercontent.com/35370833/43038541-2d2d85ce-8d1b-11e8-82ee-c33c95624dfc.png)

**Comment by krystian3w** [comment]
`https://earn-url.com/swU6` - in loop "earn money" blocked site:

![obraz](https://user-images.githubusercontent.com/35370833/43038541-2d2d85ce-8d1b-11e8-82ee-c33c95624dfc.png)

---


`https://linkrag.com/Q9MTK` - simlar blocked website in this loop.


---

`https://earnbig.ca/ci6ldM2r9` - we can't speed up by `earnbig.ca#@#script:inject(nano-setInterval-booster.js)`, I have pop-up bad request.
