### ISSUE TITLE
https://skips.link/

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#2959]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://skips.link/FND9]`

### Describe the issue

[Site won't load till adblocker disabled]

### Screenshot(s)

[https://imgur.com/rwzWaz6]

### Versions

- Browser/version: Firefox Quantum 61.0.1
- uBlock Origin version: 1.16.14

### Settings

- [https://imgur.com/w2SVssP ; https://gist.github.com/exodius48/c51e74585f7c098c290140c17ba4b262]

### Notes

[pop up message to disable adblocker is showing when access the site]

**Comment by krystian3w** [comment]
Nano Defender? From my side block this `https://antiblock.org/?p=v3&demo`

PS. `@@||skips.link^$generichide` does not working.

**Comment by krystian3w** [comment]
```
@@||skips.link^$generichide
skips.link##.adsbygoogle
@@||idsly.bid/download3.png$image,domain=skips.link
```

Works for my side in Firefox 61.0.1 with uBO only.

**Comment by krystian3w** [comment]
`https://antiblock.org/?p=v3&demo` - source for testing in feature.
