### ISSUE TITLE
iplogger filter

### ISSUE THREAD

**Issue by piperun** [uBlockOrigin/uAssets#296]
I'm the author of my own filter list which specializes in blocking websites that tries to get your IP either via shortening link service, javascript, fake image hosting, etc.

Currently people has to know about my repo in order to use it and I think it would be better to have it be part of ublock's "out of box" blocklist.

Which is why I ask if it would be possible to add this list.

Browser: Firefox Stable 51.0.1
ublock version: 1.10.6

list in question:
https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist

Thanks,
piperun

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/pull/2370#issuecomment-288505568>.
