### ISSUE TITLE
[Anti-adblock] macplanete.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2960]
### URL(s) where the issue occurs

`https://www.macplanete.com/politique-de-confidentialite`

### Describe the issue

BAB, takes ~10 seconds to trigger

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43036808-bb547a94-8cc4-11e8-8404-2e4a69a2c01f.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.12

### Settings

English default. Tried with French lists, didn't change anything.

**Comment by krystian3w** [comment]
`macplanete.com##script:inject(bab-defuser.js)` seems works for me.

**Comment by jspenguin2017** [comment]
It's classic BAB, we're just waiting for someone who can push.

**Comment by krystian3w** [comment]
And so I would not be able to dispose of some more advanced "bao**bab**" - too difficult for me..
