### ISSUE TITLE
[Anti-adblock] openproxy.co

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2961]
### URL(s) where the issue occurs

`https://www.openproxy.co/server-5`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43038252-3a632e9e-8cd3-11e8-9e77-800fc9c96c99.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.12

### Settings

English default.

**Comment by krystian3w** [comment]
`@@||openproxy.co^$generichide` maybe anyone unlock create acconut in other method.
