### ISSUE TITLE
[Ads] tornadomovies.to

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#2963]
### URL(s) where the issue occurs

`https://www2.tornadomovies.to/tornado-1`

### Describe the issue

No images load no videos load or play either.

### Versions

- Browser/version: Firefox Quantum Latest.
- uBlock Origin version: Latest.

### Settings

Default.

### Notes

Anti adblock it seems.

**Comment by krystian3w** [comment]
I can not reproduce, you must still waiting for **`@`okiehsch** / **`@`mapx-**  / **`@`ZaphodBeebblebrox** 

I do not really have any magical exceptions fixing a bit this website.

**Comment by krystian3w** [comment]
I can play your demo video, no tested more this website.

**Comment by okiehsch** [comment]
I can't reproduce.

![unbenannt](https://user-images.githubusercontent.com/16838044/43040578-d21914fa-8d47-11e8-9c92-1632996dffe3.JPG)

Site works fine with Chrome and Firefox.

The only way to reproduce your issue and screenshot is to block
`https://www2.tornadomovies.to/addons2/js/scripts.min.js`, this request is not blocked with a default setup on my end.

**Comment by ZaphodBeebblebrox** [comment]
@ryanbr 
```
tornadomovies.to###container_inner
||loadshare.org/custom/*$media,domain=tornadomovies.to
```
for `https://www2.tornadomovies.to/movie/avengers-infinity-war/LygiiwhC-watching.html`

**Comment by ryanbr** [comment]
Considered a self promo?

**Comment by ZaphodBeebblebrox** [comment]
Perhaps the first one is, the second filter list for their video ads.

**Comment by ryanbr** [comment]
i only saw the self promo tbo.

**Comment by okiehsch** [comment]
The video ad is a clip about the "amazing" features of the premium membership of `tornadomovies`.

I would say that is also self advertisement.

**Comment by ryanbr** [comment]
Self promo for the site. would be different if it was advertising for another site/item etc.

**Comment by C0nw0nk** [comment]
In firefox i see these in my error logs.

```
XML Parsing Error: no element found Location: https://seriencev.com/ Line Number 1, Column 1:
```


In google chrome what also has the same problem under defaults

```
mD6l40ir-watching.html:863 Uncaught ReferenceError: $ is not defined

Uncaught ReferenceError: $ is not defined
    at eval (eval at <anonymous> (tornado_jwplayer.php?v=1522428273:1), <anonymous>:1:21904)
```


It is a bunch of javascript errors.

**Comment by C0nw0nk** [comment]
Got it working must of been an outdated cache clearing all caches for that site fixed it.

But they still show ads under the video player that are bypassing ublock.
