### ISSUE TITLE
classicreload.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#2965]
https://classicreload.com/mortal-kombat.html

When you go to "https://classicreload.com/mortal-kombat.html", there's a popup message that says "Please consider disabling your adblocker, so we can pay to host your games for free forever!". Does uBlock Origin have any way to block anti-adblocker messages on classicreload.com and other websites? Thanks.

![classicreload com anti-adblocker](https://user-images.githubusercontent.com/35790889/43040674-f3a00d8e-8d17-11e8-8b1c-e963939fe3ef.jpg)

Windows 7 home premium 64 bit
Waterfox 56.2.2 (64-bit)
uBlock Origin 1.16.14

**Comment by IoanPaleru** [comment]
The filters from "https://github.com/uBlockOrigin/uAssets/commit/68a1fa64b0847d37f3f7b8966dfb6927ea32c28c" work very well. Thanks, and have a good day.

**Comment by stephenhawk8054** [comment]
I'm not sure if I should post a new issue or continue in here, but there's another anti-adblock in this site. 

![image](https://user-images.githubusercontent.com/66517106/135828065-d304a13b-9d5c-4a8e-bdd4-4b99cc7bff17.png)

Ungoogled Chromium 94.0.4606.71 with ublock 1.38.2, default settings with no additional filter list.

Adding this filter helps bypass the anti-adblock

`classicreload.com##+js(set, aawChunk, true)`
