### ISSUE TITLE
Whitelist "inject" filters

### ISSUE THREAD

**Issue by Nojevah** [uBlockOrigin/uAssets#297]
### URL(s) where the issue occurs

`http://www.lequipe.fr/Football/Diaporama/Les-30-meilleurs-joueurs-de-20-ans-ou-moins/6011`

### Describe the issue

FWIS, it is not possible to whitelist filters with "inject" function.
In this example it is not possible to navigate in this gallery.
If you click right button, text below image is not updated, and you can't use left button.

The filter responsible is in "uBlock filters" list. ( I guess lequipe.fr##script:inject(sas-defuser.js))
The only way to make the gallery work is to whitelist the entire site (not with the button "allow +all")

It would be good to have a way to whitelist these "inject" functions.

### Versions

- Browser/version: Version 56.0.2924.87
- uBlock Origin version: 1.11.0

**Comment by okiehsch** [comment]
> It would be good to have a way to whitelist these "inject" functions.


`example.com#@#script:inject(example.js)`
In your specific case `lequipe.fr#@#script:inject(sas-defuser.js)`.

**Comment by uBlock-user** [comment]
Script Injection filters are cosmetic in nature, so undo them just how you undo the cosmetic ones.

**Comment by Nojevah** [comment]
How do you manage to "undo" those cosmetic ones ?
I didn't find a way. At first I though it was the "eye" icon, but it does not change anything.

**Comment by okiehsch** [comment]
You can disable all `ScriptInjectFilters`.
Go to `Advanced user features` and set `ignoreScriptInjectFilters` to true.
![aufzeich](https://cloud.githubusercontent.com/assets/16838044/23271679/b6e552ae-f9f8-11e6-9a29-6f0de4bc7366.PNG)

**Comment by Nojevah** [comment]
I did not know about this setting page. Thanks for this info.
Unfortunately it ignore all ScriptInjectFilters. I think some are surely very useful so I'd prefer to let them enable. But sometimes they break some website and the idea was to whitelist these "ScriptInjectFilters" just for one website thanks to the popup UI.

If you really want to know how I do:
1) I go on a website: something has strange behavior and it looks like uBlock is responsible
2) I open popup UI: I check which domains are blocked thanks to red/yellow/green indicator
3) I whitelist some domains until the page works
4) If I have time (and feel like), I try to report back to the author list

For ScriptInjectFilters, it's tricky, cause I end up whitelisting all domains, and page is still not working until I disable filterlist. Adapt/create a filter is not an option at work.

**Comment by gorhill** [comment]
I can navigate the gallery fine.

**Comment by uBlock-user** [comment]
@gorhill Why do `script:inject` filters don't appear in the logger ? Is it by-design ?

**Comment by gorhill** [comment]
Not by design, just not coded yet.

**Comment by uBlock-user** [comment]
@gorhill So in future, you may add that too ?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues/127

**Comment by uBlock-user** [comment]
I'm asking for script inject specifically, don't they have any effect worthy enough to be reported ?

**Comment by gorhill** [comment]
As far as I am concerned, I will address all cases when I fix that one issue.
