### ISSUE TITLE
About blocking remote fonts

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#298]
I do understand the option to block remote fonts. If enabled remote fonts aren't downloaded.

What is unclear in my mind is this option compared to Firefox's font settings available in about:config,

```
// enable/disable websites downloading their own fonts - (0=block, 1=allow)
user_pref("browser.display.use_document_fonts", 0); // default=1
// enable icon fonts (gylphs) - (false=block, true=allow)
user_pref("gfx.downloadable_fonts.enabled", true); // default=true
```

I'm comparing because Firefox as we see has the option to block remote fonts with the exception of icon fonts.

If I use UBOo' remote fonts blocking then all remote fonts are blocked, that is aren't downloaded, icon fonts as well.
So my question is : does UBO's remote font blocking perform the same as Firefox's browser.display.use_document_fonts set to 0?
I'm assuming Firefox's remote font blocking blocks their download, not only their display: should I be wrong then there would be no possible comparison.

Thanks.

**Comment by Atavic** [comment]
Firefox Prefs say _use document fonts_. That's really generic and allows scripts to run in the background even if set to false. uBlock, by properly blocking the calls related to remote fonts,  is far better privacy-wise.

**Comment by zymase** [comment]
The whole point is there indeed : does browser.display.use_document_fonts in Firefox, when set to 0, mean that remote fonts are not downloaded?

_document_fonts_ is a generic formulation but it can also mean that not using them is implicitly not downloading them ...

The above explanation of the setting, "_// enable/disable websites downloading their own fonts - (0=block, 1=allow)_" is from me, from a long time ago when I assumed then that blocking remote fonts on Firefox meant not downloading them ...but i'm not so sure anymore.

There wouldn't be any problematic in my mind if it weren't that blocking remote fonts with UBO includes icon fonts. I don't care about remote fonts and I block them in Firefox as i'd block them with UBO, but I do care for icon fonts : many pages use them ...

Moeilla's definition of the setting is (now that 've searched for it) :

browser.display.use_document_fonts:
0: Never use document's fonts
1: Allow documents to specify fonts to use

So you might be right, @Atavic , it might very well be that fonts remain downloaded but not used ...
As I said, if it weren't for the icon fonts I'd already have set UBO to block remote fonts.

**Comment by Atavic** [comment]
Most of those fonts are retrieved with scripts that call a CDN as google that easily fingerprint your browser when it loads the scripts. Blocking them reduces the attack surface against your browser (less fingerprinting exposition).

**Comment by zymase** [comment]
I'm aware of that, I'm not wondering if blocking remote fonts is pertinent, I know it is. Concerning Google alone I've set * fonts.googleapis.com * block ... that's not the problem. 

If Firefox blocks downloading of all remote fonts (except icon fonts if that option is chosen) then I keep Firefox rather than UBO because UBO blocks icon fonts as well.

If Firefox blocks use/display of fonts but downloads them whatever, then I choose UBO font blocking.

'see what I mean?

**Comment by Atavic** [comment]
Yes. Firefox doesn't block those scripts, uBlock does it.

**Comment by SMed79** [comment]
**[Fanboy Anti-font Tracking]( https://secure.fanboy.co.nz/fanboy-antifonts.txt)** is an alternative for other adblocker such Adblock Plus, AdBlock, Adgurd...

* https://www.fanboy.co.nz/filters.html
