### ISSUE TITLE
gamereactor.dk [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2990]
URL(s) where the issue occurs

`https://www.gamereactor.dk/nyheder/624143/No+Mans+Skys+NEXTopdatering+udkommer+naeste+uge/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67.0.3396.99 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by BottledSoda** [comment]
`gamereactor.dk##+js(aopw, detectAdblockUser)` -> obsolete
I don't think that there are any issues with DandelionSprout's nordic filter list + uBO's ebd (eng, PC) on the URL given in this issue.

**Comment by BottledSoda** [comment]
obsolete filter.
I don't think that there are any issues with DandelionSprout's nordic filter list + uBO's ebd (eng, PC) on the URL given in this issue.
