### ISSUE TITLE
Q/RFE: RequestPolicyContinued Subscriptions?

### ISSUE THREAD

**Issue by TPS** [uBlockOrigin/uAssets#30]
Can [uBlock](https://github.com/gorhill/uBlock/) or [uMatrix](https://github.com/gorhill/uMatrix/) read the [format](https://github.com/RequestPolicyContinued/subscriptions/#how-to-read-subscriptions-files) from [RequestPolicyContinued subscriptions](https://github.com/RequestPolicyContinued/subscriptions/)?  Is it something that's worth pursuing, or do other subscriptions sufficiently handle that gap?

**Comment by gorhill** [comment]
> Can uBlock or uMatrix [...]

No, and I do not plan on supporting these, raising code complexity for the sake of marginal benefits -- if any dos not sound a good idea.

> do other subscriptions sufficiently handle that gap?

Anybody can find out, it does not have to be me.
