### ISSUE TITLE
howdyho.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3001]
URL(s) where the issue occurs

`http://howdyho.net/download/210`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67.0.3396.99 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by okiehsch** [comment]
Wrong commit, but I can doenload the file without issue with the regional filters enabled.

**Comment by TimofeyFilkin-alt-i-lost-my-codes** [comment]
this shit is still around

**Comment by stephenhawk8054** [comment]
Enable `RU AdList` lists and test again.

**Comment by TimofeyFilkin-alt-i-lost-my-codes** [comment]
antiadblock is the reason. Even if you delete ad element trough devtools,
it will trigger

**Comment by stephenhawk8054** [comment]
Report at https://github.com/easylist/ruadlist/issues
