### ISSUE TITLE
shinden.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3003]
URL(s) where the issue occurs

`https://shinden.pl/external-video/52827-hanebado/view/166990`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67.0.3396.99 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by okiehsch** [comment]
What adblock message?

**Comment by KiLL4FuNK** [comment]
![](https://i.imgur.com/nG4j6et.png)

**Comment by okiehsch** [comment]
That is fixed if I use the regional list on my end.
