### ISSUE TITLE
[NSFW] Gelbooru.com

### ISSUE THREAD

**Issue by kowith337** [uBlockOrigin/uAssets#301]
### URL(s) where the issue occurs

`gelbooru.com`, then make any search to enter image list page.

### Describe the issue

Gelbooru start to serve ads by host ads resource locally, some ads can be blocked, but some cannot, e.g. under page navigation that load ads images from `/thumbnails/0A/` that seems hard to blocking them because it's place same as where actual thumbnails loaded.
also, EasyList still whitelist `exoclick.com` as present, but I think it's must not to be whitelisted, no matter why.

Example of whitelisted rules.
- `@@||exoclick.com/ad_track.js` <-- **Globally whitelisted!?**
- `@@||ads.exoclick.com/*.js$script,domain=gelbooru.com`

Even I've used uMatrix to block other domains except first party (Gelbooru), bottom ads still show because it's loaded from first party, not others.

### Screenshot(s)

Some part will be censored or blurred out before uploading...
![image](https://cloud.githubusercontent.com/assets/16535467/23460418/f680bdae-feb7-11e6-994c-cbf5623c931b.png)
![image](https://cloud.githubusercontent.com/assets/16535467/23460485/36e204e8-feb8-11e6-937e-52f414ef9503.png)
![image](https://cloud.githubusercontent.com/assets/16535467/23460482/32aafee8-feb8-11e6-9db6-55d142169402.png)

### Versions

- Browser/version: Chromium 58.0.3016.0 (NoSync)
- uBlock Origin version: 1.11.1.1

### Settings

- Everything default

### Notes

- Sometimes delete cookies is needed for reproduce.
- It seems they use function to read `advertVar`, if ads cannot load from third party or server-side resources, such as `ads.js` or `application.js.php`, this function will be called to rewrite ads under paginator.
![image](https://cloud.githubusercontent.com/assets/16535467/23460911/28061a7a-feba-11e6-8f56-6c4b8f8cb457.png)
- This is a result after added `gelbooru.com##script:inject(abort-on-property-read.js, advertVar)`
After injected, no request of image ads that placed at `/thumbnails/0A/` anymore, also no placeholder of bottom ads.
![image](https://cloud.githubusercontent.com/assets/16535467/23460569/91fd0170-feb8-11e6-9ae7-728f099c0618.png)
![image](https://cloud.githubusercontent.com/assets/16535467/23460584/a1e91aec-feb8-11e6-9ba3-351803859099.png)
- I don't know when that sites will update to keep showing ads again, but at least this site still not have any antiuser things, such as anti-adblock.

**Comment by SMed79** [comment]
Reported by still not fixed https://forums.lanik.us/viewtopic.php?p=113489#p113489
