### ISSUE TITLE
[Ads Leftover] masterani.me, mp4upload.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3013]
### URL(s) where the issue occurs

`https://www.masterani.me/anime/watch/1269-shingeki-no-kyojin-2nd-season/1`

### Describe the issue

Ads leftover, transparent overlay and its close button not removed. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43110631-555cdf28-8eaa-11e8-8cc3-3f7db1d04f37.png)
![image](https://user-images.githubusercontent.com/7283682/43110641-61509f68-8eaa-11e8-951e-64a2b676719c.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.12

### Settings

English default.

**Comment by KiLL4FuNK** [comment]
ADS

`https://www.masterani.me/anime/watch/2680-hoozuki-no-reitetsu-2nd-season/13`

**Comment by mapx-** [comment]
`masterani.me##.hero`
