### ISSUE TITLE
repelis.io [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3019]
URL(s) where the issue occurs

`https://repelis.io/pelicula/i-daniel-blake-ARSE8`

Describe the issue

Fake Button

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by lain566** [comment]
The video player is broken.
`https://repelisgo.io/pelicula/aquaman-EDsQB`

**Comment by lain566** [comment]
There's a popup
`https://repelisgo.com/`
