### ISSUE TITLE
BlockAdBlock

### ISSUE THREAD

**Issue by Vorrarkul** [uBlockOrigin/uAssets#3020]
### URL(s) where the issue occurs

`https://www.onlinevideoconverter.com/video-converter`
`https://blockadblock.com/` - Source of the AdBlock Blocker

### Describe the issue

Despite my attempts to bypass this BlockAdBlock, I have been unable to get around it.

### Versions

- Browser/version: Firefox Quantum 61.0.1 (64-bit)
- uBlock Origin version: 1.16.14

### Settings

I have attempted both below script additions based on Google searches, as well as various older greasemonkey codes and such, none seem to work.
- @@||*^$generichide
- blockadblock.com##script:inject(bab-defuser.js)

### Notes

Seemingly every counter to BlockAdBlock is out of date.

**Comment by okiehsch** [comment]
`https://www.onlinevideoconverter.com/video-converter` is already fixed in `uBO-filters` and it still works fine on my end using Chrome or Firefox with a default setup.

**Comment by Vorrarkul** [comment]
The BlockAdBlock takes a few seconds to appear, but still reliably appears after I use the generichide filter. It's on a delay.

**Comment by krystian3w** [comment]
<code>**onlinevideoconverter.com**##script:inject(bab-defuser.js)</code>
 instead of 
_`blockadblock.com##script:inject(bab-defuser.js)`_?

**Comment by KiLL4FuNK** [comment]
What extensions do you use?
Maybe another extension is the problem

**Comment by krystian3w** [comment]
https://support.mozilla.org/en-US/kb/tracking-protection - I would recommend shut down if it turns on `onlinevideoconverter.com`.

**Comment by Vorrarkul** [comment]
My only other add-on is AdBlock Plus. I will attempt @krystian3w 's filter in a minute. As far as I can tell, I do not have the default firefox tracking protection active- I have never seen the shield they describe.

I have attempted @krystian3w 's script and it seems to work.

**Comment by okiehsch** [comment]
> My only other add-on is AdBlock Plus.

Using multiple blocking extensions is not advisable, just choose one and disable the other.

If you want to use them both, add  `onlinevideoconverter.com##script:inject(bab-defuser.js)`
to your filter list.

**Comment by cup** [comment]
- http://github.com/uBlockOrigin/uAssets/issues/3020
- http://github.com/uBlockOrigin/uAssets/issues/2479
- http://github.com/uBlockOrigin/uAssets/issues/2105

**Comment by cup** [comment]
1. Dashboard
2. Filter lists
3. Ads
4. Adguard Base Filters​

**Comment by krystian3w** [comment]
uBO not block on demo pages.
