### ISSUE TITLE
[Anti-adblock] bitcoinfaucet.tk

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3022]
### URL(s) where the issue occurs

`http://bitcoinfaucet.tk/`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43173005-9d9f7636-8f6f-11e8-8558-060853b1f7bb.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default.

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
