### ISSUE TITLE
[Popup] farsroid.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3023]
### URL(s) where the issue occurs

`https://www.farsroid.com/signal-strength-android/`

### Describe the issue

Popup, may need to wait for the page to complete loading (which takes a bit for me). 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43173035-d58f6628-8f6f-11e8-888b-bf4a58978e10.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default. I'm not sure if there is a regional filter for this language.

**Comment by okiehsch** [comment]
It's Farsi, `Adblock-Iran`.
