### ISSUE TITLE
[Anti-adblock message] opensubtitles.org

### ISSUE THREAD

**Issue by bobsage123** [uBlockOrigin/uAssets#3024]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.opensubtitles.org`

### Describe the issue

When clicking around on the the page on any link the "ad blocker detected" message will inevitably pop up.

### Screenshot(s)

`https://i.imgur.com/FsU4kk6.png`

### Versions

- Browser/version: Chrome 68
- uBlock Origin version:  v1.16.14

### Notes

`https://i.imgur.com/Nn87B1e.png`

This message appears to be using randomized div IDs. So when I went to block the element it with the picker it just kept coming back.

**Comment by SkeletalDemise** [comment]
`opensubtitles.org##script:inject(abort-current-inline-script.js, adblockmsg)` or `opensubtitles.org##script:inject(set-constant.js, displayed, false)` work for me.

**Comment by ZaphodBeebblebrox** [comment]
Fixed in uBlock Annoyances.

**Comment by bobsage123** [comment]
It looks like this other banner is appearing now - `https://i.imgur.com/kS6k1zS.png`

And there's a big open space under "Why use open subtitles" that wasn't there - What the space looking like before `https://i.imgur.com/iAC7N7M.png`

Thanks for your help.

**Comment by SkeletalDemise** [comment]
Both of those get unhidden due to the new `@@||opensubtitles.org^$generichide` filter that was just added to fix the anti-adblock message.

**Comment by okiehsch** [comment]
`opensubtitles.org##script:inject(set-constant.js, displayed, false)`
seems to the better fix, does that work for you both if you remove the generichide filter?

**Comment by SkeletalDemise** [comment]
It works for me.

**Comment by bobsage123** [comment]
Yup, looks good. Thanks all.

**Comment by Mennaruuk** [comment]
Does anyone still see this occasionally? I have `opensubtitles.org##script:inject(set-constant.js, displayed, false)` in my filters, but it isn't helping anymore.

**Comment by bobsage123** [comment]
Yeah issue is back, they changed the code. Here is what I see for top banner:

`###T540UK\(g > div`
