### ISSUE TITLE
Background color for hltv.org

### ISSUE THREAD

**Issue by inDigazzZ** [uBlockOrigin/uAssets#3025]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
hltv.org

### Describe the issue
There's string in rules
**hltv.org##body:style(background: #e5e7ea !important;)**
but i'm using Night Mode at hltv.org so light background is annoying

### Screenshot(s)
https://imgur.com/a/EGGa7Zq

### Versions

- Browser/version: [Opera Developer 56.0.3023.0]
- uBlock Origin version: [1.16.14]

**Comment by krystian3w** [comment]
`hltv.org#@#body:style(background: #e5e7ea !important;)`

The `:style()` filters you add to exceptions like other cosmetic filters.

https://github.com/uBlockOrigin/uAssets/issues/2307

---

Website still serve background ads, so there is nothing to be expected to remove the background reset.  
Website makes it more difficult to easily detect the night mode - substitution of the style in the head tag and homing on the cookie?

**Comment by okiehsch** [comment]
Like @krystian3w mentioned, add `hltv.org#@#body:style(background: #e5e7ea !important;)`
to your filter list.
