### ISSUE TITLE
coolrom.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#3026]
`http://coolrom.com/roms/dc/15460/Hydro_Thunder.php`

uBlock Origin is a very useful add-on, but when you go to `http://coolrom.com/roms/dc/15460/Hydro_Thunder.php`, with uBlock Origin enabled, it doesn't show the "alternative download link (with ads and timer)", however when you disable uBlock Origin, when the page first loads for a few seconds it shows that link, then the link disappears, although it still shows the "download now" link. Is there a way to fix that? Thanks.

![coolrom with adblocker](https://user-images.githubusercontent.com/35790889/43203967-a8a234c8-8fed-11e8-9cbd-239351454847.jpg)

![coolrom without adblocker 001](https://user-images.githubusercontent.com/35790889/43203971-abf5d3c8-8fed-11e8-82a5-7527b6b5c1db.jpg)

![coolrom without adblocker 002](https://user-images.githubusercontent.com/35790889/43203976-ae7754b4-8fed-11e8-9682-71eac0ec5225.jpg)

Waterfox 56.2.2 (64-bit)
uBlock Origin 1.16.14
Nano Defender 15.0.0.20

**Comment by okiehsch** [comment]
I can't reproduce with a default stetup.
![image](https://user-images.githubusercontent.com/16838044/43217589-54d46e88-9042-11e8-85d7-294c308b5314.png)

**Comment by gwarser** [comment]
I don't see it even with uBO disabled

**Comment by okiehsch** [comment]
With uBO disabled.
![image](https://user-images.githubusercontent.com/16838044/43221158-4d0a4a42-904c-11e8-9967-19fdfa8854f8.png)

**Comment by IoanPaleru** [comment]
I'd like it to show the "download now or add to queue", and "alternative download link (with ads and timer)" links with uBlock Origin enabled, because right now it only shows "You may click the link below to download your file" with uBlock Origin enabled, and "download now or add to queue" with uBlock Origin disabled. Is that possible? uBlock Origin is still a very useful program by the way, even if it doesn't work by default on every website. Thanks, and have a good day.

uBlock Origin 1.16.14
Waterfox 56.2.2 (64-bit)
Nano Defender 15.0.0.16
Adblock Warning Removal List (moz-extension://c5994e26-4984-46a0-bd95-4b22ac70be92/asset-viewer.html?url=awrl-0)
EasyList (moz-extension://c5994e26-4984-46a0-bd95-4b22ac70be92/asset-viewer.html?url=easylist), 
Nano Defender Integration (moz-extension://c5994e26-4984-46a0-bd95-4b22ac70be92/asset-viewer.html?url=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt)
Nano filters (moz-extension://c5994e26-4984-46a0-bd95-4b22ac70be92/asset-viewer.html?url=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt)
Nano filters - Whitelist​ (moz-extension://c5994e26-4984-46a0-bd95-4b22ac70be92/asset-viewer.html?url=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt)

**Comment by krystian3w** [comment]
Try with legacy version: https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.4

**Comment by IoanPaleru** [comment]
Yes, with uBlock Origin 1.16.4.4 legacy version (https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.4), on "http://coolrom.com/roms/dc/15460/Hydro_Thunder.php" it shows "download now or add to queue", but it doesn't show "alternative download link (with ads and timer)". Thanks.

**Comment by krystian3w** [comment]
Maybe have adware in Windows or macOS (and they spoil the site, they generate ads).

If you have any GNU/Linux distro, treat it as if it did not provide links (incompatible programs and a rather less chance for malware).

**Comment by IoanPaleru** [comment]
gwarser, the highlighted area in the attached screenshot is what I'm talking about.

![43218307-54a2708e-9044-11e8-9978-c63495968b45](https://user-images.githubusercontent.com/35790889/43413218-77fb6ace-93fd-11e8-99f2-bcc5faaa60b7.png)

okiehsch, I've confirmed that with a freshly created waterfox profile, and ublock origin with the default setup, all of the links are displayed properly on "http://coolrom.com/roms/dc/15460/Hydro_Thunder.php". Thanks for your help. It seems that it does have to do with a setting or something else that's installed on my browser. I'll try and troubleshoot it further, and if I find out what the issue was, I'll let you know. Keep up the great work on uBlock Origin! Thanks, and have a good day. :)

**Comment by gwarser** [comment]
>It seems that it does have to do with a setting or something else that's installed on my browser.

Or IP / location / ?

Firefox 61, 62, 63, Waterfox 56.2.2, Chromium 67

![image](https://user-images.githubusercontent.com/886325/43416387-68888474-9438-11e8-851d-8662126f8adc.png)
