### ISSUE TITLE
https://www.firstonetv.eu/

### ISSUE THREAD

**Issue by happysurf** [uBlockOrigin/uAssets#303]
### URL(s)
- `https://www.firstonetv.eu/Live/` (The site)
- `https://www.firstonetv.eu/Live/Italy/TV8-20` (The video)
                    
### Problem
- UBO is detected, impossible view the video

### Screenshot
- http://prnt.sc/efvrqh

### Versions

- Browser/version: [Firefox 52]
- uBlock Origin version: [1.11.2]

### Settings

- the problem is present also with default settings

### Notes

- none

**Comment by mapx-** [comment]
`@@||firstonetv.eu^$xmlhttprequest`

**Comment by SMed79** [comment]
`||firstonetv.eu/js/app?`

tested here `https://www.firstonetv.eu/Live/France/RMC-Découverte-35`

**Comment by gorhill** [comment]
How about:

    ||firstonetv.eu^$xmlhttprequest,redirect=nooptext,domain=firstonetv.eu
    @@||firstonetv.eu/*?cacheFucker$xmlhttprequest,domain=firstonetv.eu

**Comment by uBlock-user** [comment]
add - ``firstonetv.eu##script:inject(abort-on-property-write.js, AdFuckBlock)``
