### ISSUE TITLE
NSFW! [Popup] javher.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3031]
### URL(s) where the issue occurs

`https://javher.com/video/watch-cesd00611-1532188800000`

### Describe the issue

Popups, and the video player has ads overlay. 

### Screenshot(s)

Let me know if you need screenshots. 

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default.

**Comment by bobsage123** [comment]
Hmm, tested this on chrome and firefox and clicking the play button nothing happens.

**Comment by ZaphodBeebblebrox** [comment]
You need to click on the tiny blue and white x first.

**Comment by jspenguin2017** [comment]
This is the offending function, unfortunately I see no way around it without patching the code. 
```js
  var closeAd = function (e) {
    try {
      if (!e.screenX || e.originalEvent.isTrusted === false) {
        return;
      }
    } catch (e) {
    }
    if (isEmbedded && !window.open('javascript:close()', '_blank')) {
      window.location = redirectURL + '?from_embed';
      return;
    }
    $('#player_3x2_container').hide();
    $('#aoverlay').hide();
    localStorage[key] = 1;
    /*
    if (!played) {
      player.play();
      $('#close-btn-icon').removeClass('glyphicon-play');
      $('#close-btn-icon').addClass('glyphicon-remove');
      $('#close-btn-text').text(' 閉じる・Close');
      played = true;
    }*/
  };
```

**Comment by bobsage123** [comment]
Ahh I see, I guess that's a weird element that can't be blocked?

**Comment by okiehsch** [comment]
Yes, the popup can't be blocked in `uBO-flters`, even adding
`avgle.com##script:inject(window.open-defuser.js)`
will break the player id you click the x.

@ZaphodBeebblebrox that's a good idea, though 500% seems a bit much
`avgle.com###player_3x2_close:style(font-size: 250% !important;)` should make it obvious enough,
