### ISSUE TITLE
problem with a site when uBlock is activated

### ISSUE THREAD

**Issue by Caln0** [uBlockOrigin/uAssets#3034]
Replace the bracketed [...] placeholders with your own information.

### Describe the issue

Hello,

I would like to report a problem in a site which I daily use and only occurs when uBlock origin is active.

The problem is that when I open an item in the site, there is favorite button and it doesn't work when uBlock is on, otherwise in the page it is working, but it is annoying to go back to the page and click it from there, if you could fix it I would greatly appreciate.  I have tested it in Chrome too and still the same issue.

Note: The favorite button only works if you have registration in the site, I don't know if you can test it without one.

Thank you.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox Quantum 61.0.1
- uBlock Origin version: 1.16.14

### Settings

default settings, no filters

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by krystian3w** [comment]
Works fine in Opera 54 with uBO 1.16.14.

---

> note: The favorite button only works if you have registration in the site, I don't know if you can test it without one.

Without account does not work button - generate login pop-up.

**Comment by krystian3w** [comment]
Button blocked by EasyList: `||scarabresearch.com^$third-party`


```
@@||cdn.scarabresearch.com/js/*/scarab-v2.js$script,domain=remixshop.com
@@||recommender.scarabresearch.com/merchants/*$xmlhttprequest,domain=remixshop.com
```
