### ISSUE TITLE
bild.de is blocking uBlock Origin once again...

### ISSUE THREAD

**Issue by AddyBlocky** [uBlockOrigin/uAssets#3035]
### URL(s) where the issue occurs

`www.bild.de` (one of the biggest news pages in Germany)

### Describe the issue

bild.de did change something once again to prevent using uBlock Origin (and even Chrome's Incognito mode), and the following message appears after loading page.

### Screenshot(s)

https://picload.org/view/dladwidi/adblock_bild_de.png.html

### Versions

- Browser/version: Chrome 67
- uBlock Origin version: 1.16.14

### Settings
---
### Notes

nothing yet, don't know how to solve problem, bild.de was blocked several times before but you always did solve problem after updating filter list :)

**Comment by gorhill** [comment]
I can't reproduce without EasyList DEU, but can reproduce with that list. So something in that list is interfering apparently.

**Comment by gorhill** [comment]
And suddenly I am no longer able to reproduce with EasyList DEU.

**Comment by AddyBlocky** [comment]
What the heck, now I tried to deactivate EasyList Germany and even EasyList, but I still have the same problem :( I also changed my IP and deleted cookies. Should I deactivate anything else on my uBlock settings here? : https://picload.org/view/dlaagrga/ublock_settings.png.html
Thanks!

**Comment by gorhill** [comment]
Be sure to erase the site's cookies when you try to reproduce after changes. I always test with default settings/lists, and default settings/lists + default regional lists. I am no longer able to reproduce on my side.

**Comment by okiehsch** [comment]
I can only reproduce if I disable the  `uBO-filter`
`bild.de##script:inject(setTimeout-defuser.js, _abeh, 700)`
so that fix still works on my end.

**Comment by mapx-** [comment]
I can reproduce the issue ..

**Comment by helptiger** [comment]
me too! :-)

**Comment by TonyTough** [comment]
me too! :-)
they have changed something since yesterday.

**Comment by AddyBlocky** [comment]
And I still have the problem even with default settings ^^
