### ISSUE TITLE
pornvibe.org [Anti-Adblock] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3042]
URL(s) where the issue occurs

`https://pornvibe.org/czech-amateurs-big-tits-blonde-petra/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f9cecce7bdfee3f37c02741e631be668ba1c5ae8

**Comment by SkeletalDemise** [comment]
You added `sexwebvideo.me##script:inject(set-constant.js, canRunAds, true)` twice.

**Comment by okiehsch** [comment]
Great and I did not fix `pornvibe.org` at all, I am getting old.
Thanks for the heads-up.
