### ISSUE TITLE
Google Contributor on Tenga Media news sites

### ISSUE THREAD

**Issue by geoffdutton** [uBlockOrigin/uAssets#3045]
### URL(s) where the issue occurs
I first noticed it on `9news.com`, but then went through all of there other sites that use the same template/format from here: http://www.tegna.com/brands/

The full list is:
```
11alive.com
12news.com
12newsnow.com
13newsnow.com
13wmaz.com
9news.com
abc10.com
cbs19.tv
firstcoastnews.com
fox15abilene.com
kagstv.com
kare11.com
kcentv.com
kens5.com
kgw.com
khou.com
kiiitv.com
king5.com
krem.com
ksdk.com
ktvb.com
kvue.com
myatltv.com
myfoxzone.com
news10.net
newscentermaine.com
thv11.com
todaysthv.com
wbir.com
wcnc.com
wfaa.com
wfmynews2.com
wgrz.com
whas11.com
wkyc.com
wltx.com
wtsp.com
wusa9.com
wvec.com
wwltv.com
wzzm13.com
```

### Describe the issue

It would trigger the "Ad blocker detected" and suggest to buy a pass.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1251360/43289937-15f16c1a-90f2-11e8-93ea-bb551f281c38.png)

### Versions

- Browser/version: Chrome
- uBlock Origin version:  1.16.14

### Settings

- All defaults

### Notes

There are a handful of 3-4 letter domains that are used by Google Contributor, but they all followed the `p.d.*.com` pattern. Also, this duplicated some rules, but this is a more exhaustive list. Should I remove the ones that already are included in a rule like [this one](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L1629)?

### Proposal
This worked for all the sites:
```
||p.d.*.com^$script,domain=11alive.com|12news.com|12newsnow.com|13newsnow.com|13wmaz.com|9news.com|abc10.com|cbs19.tv|firstcoastnews.com|fox15abilene.com|kagstv.com|kare11.com|kcentv.com|kens5.com|kgw.com|khou.com|kiiitv.com|king5.com|krem.com|ksdk.com|ktvb.com|kvue.com|myatltv.com|myfoxzone.com|news10.net|newscentermaine.com|thv11.com|todaysthv.com|wbir.com|wcnc.com|wfaa.com|wfmynews2.com|wgrz.com|whas11.com|wkyc.com|wltx.com|wtsp.com|wusa9.com|wvec.com|wwltv.com|wzzm13.com
```
```
11alive.com,12news.com,12newsnow.com,13newsnow.com,13wmaz.com,9news.com,abc10.com,cbs19.tv,firstcoastnews.com,fox15abilene.com,kagstv.com,kare11.com,kcentv.com,kens5.com,kgw.com,khou.com,kiiitv.com,king5.com,krem.com,ksdk.com,ktvb.com,kvue.com,myatltv.com,myfoxzone.com,news10.net,newscentermaine.com,thv11.com,todaysthv.com,wbir.com,wcnc.com,wfaa.com,wfmynews2.com,wgrz.com,whas11.com,wkyc.com,wltx.com,wtsp.com,wusa9.com,wvec.com,wwltv.com,wzzm13.com##script:inject(abort-on-property-read.js, stop)
```

**Comment by okiehsch** [comment]
Thanks for investigating, I will remove the duplicates.

**Comment by geoffdutton** [comment]
Oh whoops, I just created a PR: https://github.com/uBlockOrigin/uAssets/pull/3047

Should I just delete that?

**Comment by okiehsch** [comment]
Well, I was just about to push, I have already done the commit so that would be best ;).
