### ISSUE TITLE
Destructoid ads

### ISSUE THREAD

**Issue by TheEnhas** [uBlockOrigin/uAssets#305]
### URL(s) where the issue occurs

https://www.destructoid.com

### Describe the issue

Annoying ads will appear on the side of every page, and sometimes also at the top and bottom as well.

### Screenshot(s)

![destructoid](https://cloud.githubusercontent.com/assets/25448414/23596619/adfdf166-0202-11e7-98c8-69e56a92d0b1.png)

### Versions

- Browser/version: Google Chrome 57.0.2987.88 beta (64-bit)
- uBlock Origin version:  1.11.3.0
- uBlock Origin Extra version: 2.11

### Settings

- Default. Destructoid uses WebRTC to bypass blockers and filters, blob filters (which are in EasyList) do not work. They may seem to work for a while but the ads will pop up eventually when navigating the site.

### Notes

Fixed by adding the following:

destructoid.com##script:inject(nowebrtc.js)

**Comment by uBlock-user** [comment]
Not completely, the ads banners are gone, but the WebRTC connection is still active. Run `chrome://webrtc-internals/` and see for yourself. Secondly, the uBO Extra's version of webrtc patcher doesn't work for this website, otherwise having `||$websocket` itself should killed the ads since it also kills any webrtc connections @gorhill

**Comment by gorhill** [comment]
The ad banners don't always go away in my case. When the browser caches the javascript files, the inlined code execute earlier than uBO can inject the noeval scriptlet. To fix the issue is to leverage one of the blocked javascript resource loaded before the eval call:

    ||ads.pro-market.net/ads/scripts/site-120903.js$script,redirect=noeval.js,domain=destructoid.com

**Comment by uBlock-user** [comment]
That doesn't work, but `destructoid.com##script:inject(noeval.js)` stopped the inline-script from creating WebRTC connections. Seems the previous fix was perfect.

**Comment by TheEnhas** [comment]
Make sure your resources file is updated as well, because a new scriptlet was added.

**Comment by uBlock-user** [comment]
How do you update that ? I force updated all uBlock filters.

**Comment by gorhill** [comment]
> Seems the previous fix was perfect.

It was not. Did you read my explanation above?

**Comment by TheEnhas** [comment]
I'm pretty sure it'll update if you purge all caches. At least, it did for me because that second fix works.

**Comment by uBlock-user** [comment]
> Did you read my explanation above?

Yes, I did, however when we **Refresh** the page, it doesn't fetch the resources from cache but rather from the server itself, isn't that correct ? 

> if you purge all caches

Done that too. No change, my resources page hasn't got that `silent-noeval.js` scriptlet still.

**Comment by gorhill** [comment]
> Done that too. No change, my resources page hasn't got that silent-noeval.js scriptlet still.

Your browser is still falling back on the cached version. I think the cache elapses 1 hour after it was last fetched from the server.

**Comment by uBlock-user** [comment]
> I think the cache elapses 1 hour after it was last fetched from the server.

Any setting to force it to use the newer version from the server ?

**Comment by gorhill** [comment]
> Any setting to force it to use the newer version from the server ?

Try clearing your browser cache before clicking "Update now".

**Comment by uBlock-user** [comment]
Thanks, that did it, still WebRTC connection is created -
https://i.gyazo.com/a5dae6b3b67d962730ec9a62bd1094fe.png

**Comment by gorhill** [comment]
As always and it should go without saying, look at uBO's logger: is the script from `ads.pro-market.net` blocked and redirected?

**Comment by uBlock-user** [comment]
> is the script from ads.pro-market.net blocked and redirected?

![](https://i.gyazo.com/ef750f02553ca7a3145c43fd056b1b8a.png)

**Comment by gorhill** [comment]
> still WebRTC connection is created

Can't reproduce. I will leave it to other to dig deeper.

**Comment by uBlock-user** [comment]
Okay, it's working now. I can no longer reproduce the webRTC connection and those ads like before, probably a race condition. Thanks.

**Comment by okiehsch** [comment]
> Can't reproduce. I will leave it to other to dig deeper.

I can reproduce. To avoid any confusion.
1. The ad banners are gone, so no ads are pulled through WebRTC.
2. `chrome://webrtc-internals` indicates an established WebRTC-connection.
I can reliably reproduce that if I restart  my browser.
![image](https://cloud.githubusercontent.com/assets/16838044/23622938/e138ef74-02a0-11e7-9148-7488db45278b.png)
3. `destructoid.com` uses `Uponit` so this is probably related to https://github.com/uBlockOrigin/uAssets/issues/251#issuecomment-276739811
This was the reason why my fix used `noeval.js` and not `nowebrtc.js` like @TheEnhas  suggested.
4. If I add `destructoid.com` to the contentscript in `uBO-Extra` the WebRTC-issue is fixed on my end.
