### ISSUE TITLE
rarbg.to

### ISSUE THREAD

**Issue by pavs** [uBlockOrigin/uAssets#3050]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`rarbg.to`

### Describe the issue

Pop-ups happens everytime I visit the site or if I stay on the site for few minutes and try to click on anything, it doesn't have to be a link - just clicking on white-space gives pop-ups.

### Screenshot(s)

Its pop-up so I don't think screenshot makes any difference.

### Versions

- Browser/version: Chrome 68.0.3440.75 (Official Build) (64-bit)
- uBlock Origin version: 1.16.14

### Settings

- haven't made changes to the best of my knowledge.

### Notes

Nothing else to add.

**Comment by MindTooth** [comment]
Care to try the following filter:
<pre> *rarbg.to##body > div:matches-css(position: fixed; top: 0px; bottom: 0px; left: 0px; right: 0px; background-color: black; opacity: 0.01; background-position: initial initial; background-repeat: initial initial;)
</pre>

**Comment by smed79** [comment]
test
```
?*&refer=*&key=*&scrWidth=*&scrHeight=$popup
```

**Comment by okiehsch** [comment]
@pavs can you post your logger output of the popup you see on your end.

For example if I **disable** `uBO-filters` and `EasyList` I can reproduce a popup if I click anywhere and my logger shows

![image](https://user-images.githubusercontent.com/16838044/43361264-db96ffc8-92ca-11e8-94d4-20950e088564.png)

**Comment by pavs** [comment]
I was able to block popups from the site by clicking the "click to block all popup from this site option".  
My  uBO-filters and EasyList are enabled and everything is default settings. Shouldn't the pop-up blocker be on by default?

**Comment by gwarser** [comment]
>Its pop-up so I don't think screenshot makes any difference.

URL of the popup would be helpful.


On my side this causes captcha dialogs:

Static filter `/a.php?ref=` found in:
EasyPrivacy

**Comment by Hrxn** [comment]
> Shouldn't the pop-up blocker be on by default?

What do you mean? On by default for such a site here? Yes, maybe.
A global default? No. That would break sites that use pop-ups legit.

**Comment by pavs** [comment]
@gwarser you are right. It was aaucwbe.com

I want to mention another site but I don' t use it enough to care about. it's a newsweek.net, but not homepage but individual articles. I have never seen any popular site that successfully deals with anti adblocker to such an extent. Since I don't use the site - if anyone else is interested please feel free to open an issue.

**Comment by KiLL4FuNK** [comment]
`https://rarbggo.org/torrents.php`

pop-up

**Comment by ZaphodBeebblebrox** [comment]
1d294c1
