### ISSUE TITLE
mashable.com video broken

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#3051]
### URL(s) where the issue occurs

`https://mashable.com/2018/07/25/glasses-cure-motion-sickness/#K2I4aEEBnOq0`

### Describe the issue

Video won't play

### Settings

Default

### Notes

Both EasyList and Peter Lowe's list have to be disabled to fix it.
`@@indexww.com`
`@@amazon-adsystem.com`

**Comment by llacb47** [comment]
The filters can be removed now. Test `https://mashable.com/video/morris-worm-computer-virus-kernel-panic/`
