### ISSUE TITLE
[Ads/Fake Button, Popup] ouo.io

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3055]
### URL(s) where the issue occurs

`http://ouo.io/mIlCLHw`

### Describe the issue

Ads, and sometimes popup. Seems random, can't always reproduce. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43351109-a7db0a4a-91ca-11e8-8943-d3f1d0b63213.png)
![image](https://user-images.githubusercontent.com/7283682/43351108-a04d6bec-91ca-11e8-8361-40e9e6b49977.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default.

**Comment by okiehsch** [comment]
I get a completely different document served on my end, there is no aj1110` request or Fake Button or Popup.
If 
`||aj1110.online^$third-party`
fixes your issue I will add it, if not you will have to investigate yourself.

**Comment by jspenguin2017** [comment]
It's hard to reproduce, I tried like 10 times, I got popup once, and that fake buttons once. I'll investigate a bit. 
Page dump: https://pastebin.com/WzheVMxY

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/43351481-d8820662-91cf-11e8-971d-9be39827e979.png)
![image](https://user-images.githubusercontent.com/7283682/43351488-e6dd00c2-91cf-11e8-9419-5b77def9d309.png)

**Comment by jspenguin2017** [comment]
Oh what's going on? Canary has some memory leak? 
![image](https://user-images.githubusercontent.com/7283682/43351510-40445a0c-91d0-11e8-9177-4c767db5c65c.png)

**Comment by okiehsch** [comment]
I get 2 different documents served, the first one
https://gist.github.com/okiehsch/b1a08d20ee90838d78706bd9863fe9b3

If I then try your link again I get
https://gist.github.com/okiehsch/fac4177fdfa6df207a2a6d8552142bfd
which includes `aj1110.online`

I get the same document served unless I delete cookies, in which case I am back to document number 1.

I can't reproduce any ads or popups.

**Comment by ghajini** [comment]
popup ads
`https://ouo.io/go/0Lj85G`

**Comment by mapx-** [comment]
redirects to `https://ouo.io/`

**Comment by lain566** [comment]
I can reproduce. 
@mapx- Remove `/go/`
`https://ouo.io/0Lj85G`
click anywhere on the page after solving the captcha.

**Comment by mapx-** [comment]
I get no popup FF / chrome

**Comment by ghajini** [comment]
`https://ouo.io/Qj1L7Ya`

Popups in between steps.....

**Comment by mapx-** [comment]
test
`ouo.io##+js(aopr, open)`
