### ISSUE TITLE
[Anti-adblock] kissasian.sh

### ISSUE THREAD

**Issue by TheHungryGeek** [uBlockOrigin/uAssets#3058]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://kissasian.sh/Drama/Tomorrow-With-You/Episode-1?id=32346&s=beta`

### Describe the issue

Forces an adblock disable before allowing the video to play

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16078559/43355218-62920bde-928b-11e8-846a-644eae660b22.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.14

### Settings

- All default

### Notes

kissasian.ch moved domain to kissasian.sh - possibly resulting in old issues recurring

**Comment by uBlock-user** [comment]
`kissasian.*##+js(abort-on-property-read.js, xaZlE)`

**Comment by TheHungryGeek** [comment]
there appears to be a lot of other filters that have to be updated from the old kissasian.ch as well, the popups now seem to be going through, etc

**Comment by uBlock-user** [comment]
> the popups now seem to be going through, etc

I don't get any.
