### ISSUE TITLE
rebrandly.com and rebrand.ly

### ISSUE THREAD

**Issue by ilyaigpetrov** [uBlockOrigin/uAssets#3059]
### URL(s) where the issue occurs

```
https://rebrand.ly/ac-contact
https://rebrand.ly/ac-webstore
https://rebrand.ly/ac-pacs
```

### Describe the issue

I use URL shortener rebrandly.com in my software, because this way I may change button/link targets without publishing a new version of my software.
I don't use it for ads or malware as you can see from the examples above.
Could you, please, consider whitelisting it.

### Screenshot(s)

![ublock-rebrandly](https://user-images.githubusercontent.com/1090811/43357786-478a81e4-92a0-11e8-8e5d-bb0e9c651fac.jpg)

### Versions

- Browser/version: Google Chrome | 67.0.3396.99 (Official Build) (64-bit)
- uBlock Origin version: 1.16.14

### Settings

- No changes were made to the defaults.

### Updates

Have sent an email to `https://www.malwaredomains.com`. Ticket was created.

**Comment by krystian3w** [comment]
`@@||rebrand.ly^` = to time remove from malwaredomains?

**Comment by ilyaigpetrov** [comment]
@krystian3w Sorry, I don't understand your response, what do you mean?
I think we should wait for malwaredomains to remove it from the list.
After that ublock shouldn't block it.

**Comment by krystian3w** [comment]
>After that ublock shouldn't block it.

Yes, when uBO update list on computer clients.

**Comment by okiehsch** [comment]
> I think we should wait for malwaredomains to remove it from the list.

That is indeed the best way to proceed, looking through the list `rebrand.ly` was added because of phishing,
![image](https://user-images.githubusercontent.com/16838044/43361092-a1db06ac-92c6-11e8-92ba-c7851be3ebc0.png)

Probably some `rebrand.ly` link directed the user to a "phishy" domain and they decided to blacklist the whole shortener.

**Comment by okiehsch** [comment]
Domain was removed.
![image](https://user-images.githubusercontent.com/16838044/43539496-51221258-95c5-11e8-8261-3f56d310edcd.png)

If you update your `malware domains` list the issue is fixed.
