### ISSUE TITLE
Filter Updates

### ISSUE THREAD

**Issue by IsraeliAdblocker** [uBlockOrigin/uAssets#306]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://easylist-downloads.adblockplus.org/israellist+easylist.txt

### Describe the issue

The above filter (an any other filter) update frequency is set to 1 day, but the lists are updating each four days instead. 

### Versions

- Browser/version: Firefox 51  & Chrome 56
- uBlock Origin version: 1.11.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
> uBO will now respect the Expires: directive in Adblock Plus-compatible filter lists, if present. However the minimal interval is set to 2 days.    https://github.com/gorhill/uBlock/pull/2314#issue-201106730

I have multiple lists enabled with an update frequency set at 1 day, for example `easylistgermany`,
they all update fine after 2 days. If no update frequency is set the filterlist updates after 5 days if
I am not mistaken.
