### ISSUE TITLE
CBS Anti-Adblock

### ISSUE THREAD

**Issue by chefboz** [uBlockOrigin/uAssets#3061]
### URL(s) where the issue occurs

`https://www.cbssports.com/college-football/news/otb-new-ucf-coach-josh-heupel-has-thoughts-on-the-college-football-playoff-system/`

### Describe the issue

CBS visuals identify my anti adblock with Adblock Warning Removal List and Nano Defender. 

### Screenshot(s)

![cbs](https://user-images.githubusercontent.com/41844363/43361921-be367950-92ab-11e8-9839-b4549aaef096.png)

### Versions

- Browser/version: Firefox 61.0.1
- uBlock Origin version: v1.16.14

### Settings

- Advanced user. Blocked 3rd party filters/scripts. Applied majority of filters. 

### Notes

This issue seems to simply be an unpatched anti-adblock by a large company.

**Comment by SkeletalDemise** [comment]
I can't reproduce with default settings. Probably has something to do with you blocking all 3rd party scripts.
