### ISSUE TITLE
tomshw.it

### ISSUE THREAD

**Issue by xates** [uBlockOrigin/uAssets#3062]
### URL(s) where the issue occurs

`https://www.tomshw.it/obsolescenza-programmata-francia-prime-etichette-95701`
(and any other article on the website)

### Describe the issue

They aggressively inject auto-playing self-promoting videos unrelated from the content in every article.

### Screenshot(s)

![screenshot of the video in the middle of the article](https://i.imgur.com/z0hlspB.png)

### Versions

- Browser/version: any
- uBlock Origin version: any

### Settings

- [default settings]

### Notes

Please add the following to _uBlock filters – Annoyances_
```
||theoutplay.com^$domain=tomshw.it
```

**Comment by smed79** [comment]
@ryanbr
