### ISSUE TITLE
estream.to

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3063]
![untitled-project](https://user-images.githubusercontent.com/5884000/43368104-0bae5caa-9358-11e8-9f37-9bffecfc2cde.gif)
`https://estream.to/lqf9g94wxhq0`

x button

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

 uBO 1.16.14
 ND 15.0.0.21
 Chr 68.0.3440.75 
</details>

**Comment by uBlock-user** [comment]
How is that an issue ? That `X` button is part of the browser to quit fullscreen, nothing to do with uBO.
