### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by OtakuPL** [uBlockOrigin/uAssets#3067]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

```
https://a-o.ninja/
https://a-o.ninja/anime/boku-no-hero-academia-3-2018/16
```

### Describe the issue

Error 2 does not play literally any player with the filters enabled anti miner. Home no longer uses the miner more than two months.

### Screenshot(s)

http://scr.hu/2ci4/afg28

### Versions

- Browser/version: chrome 68.0.3440.75 (64-bit)
- uBlock Origin version: [here]

### Settings

http://scr.hu/2ci4/qoerr

### Notes

Do not operate any video player.

**Comment by okiehsch** [comment]
The video works fine on my end
![image](https://user-images.githubusercontent.com/16838044/43413096-5b135372-942f-11e8-8c07-daa5f285c434.png)



which is not surprising looking at your [screenshot](https://scr.hu/2ci4/qoerr), you are using AdBlock.

I don't know why you opened an issue here, but I woud suggest opening an issue with AdBlock or the author of the anti-mining list they use.
