### ISSUE TITLE
cbssports.com video not playing

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#307]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.cbssports.com/college-basketball/video/legacy-bob-hurley-episode-3/`

### Describe the issue

going to page with default ublock settings and click on play button,nothing happens
### Screenshots
none,can't give in this situation

### Versions

- Browser/version: Version 56.0.2924.87 (64-bit)

- uBlock Origin version: 1.11.0

### Settings

- uBO's default settings+adblock warning removal list+youtube pure video experience

**Comment by mapx-** [comment]
add
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=cbssports.com`

**Comment by ghajini** [comment]
I don't think easylist authors are going to fix that issue,they even don't add these filter list solutions

In already reported this to easylist

**Comment by ghajini** [comment]
@gorhill 
can you please fix this issue,it seems easylist is not interested in adding filters for this site

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/2bf03097a2262fc1474f8237ca285f119f7c0586

**Comment by gh3tt0gangst3r** [comment]
this issue still persists on the PGA tour player on CBS as well

**Comment by okiehsch** [comment]
Hm, on my end something seems wrongly coded on the site.
Even if I disable uBO I have to reload one time before the video plays.
`https://www.cbssports.com/golf/pga-tour/live`
Fixing it on my end with uBO enabled needs
````
@@||plotrabbit.com^$script,xhr,domain=cbssports.com
@@||at.cbsi.com/lib/api/client-info$xhr,domain=cbssports.com
````
then reload and you will get a anti adblock message that you can simply ignore by reloading once more and you can then watch the video.
