### ISSUE TITLE
news.com.au Image Tab Disabled

### ISSUE THREAD

**Issue by UbuntuMetal** [uBlockOrigin/uAssets#3074]
### URL(s) where the issue occurs

`https://www.news.com.au/entertainment/movies/star-wars-episode-ix-cast-revealed-with-carrie-fisher-to-return/news-story/b0b4e2cb38fd5c8de1867996277c56a7#`

### Describe the issue

Hi. I've noted that in all news articles at news.com.au (sample page above) that have a video frame at the top under the headline (which is most of them), the Image tab above the vid no longer works (to clarify: you click it, it does nothing, and the frame stays on the video). You can check out the screenshot below to see what the tab looks like.

### Screenshot(s)

![image tab](https://user-images.githubusercontent.com/41879371/43435582-fe023bae-94c3-11e8-9ce6-581e7d400d62.jpg)

### Versions

- Browser/version: Firefox Quantum 61.0.1 (64-bit)
- uBlock Origin version: 1.16.14

### Settings

@@||tags.news.com.au/prod/metrics/metrics.js$script,~third-party

### Notes

Using uBlock's logger I ascertained it uses EasyList's filters, so did report the issue there, but since this appears to be a uBlock-specific issue - I recently switched over from AdBlock Plus, and that didn't cause this issue - they said I should report it here. In "Settings" above, you can see the filter code one of the EasyList guys gave me to fix the issue on my end.

**Comment by smed79** [comment]
@UbuntuMetal When you [ask for help](https://forums.lanik.us/viewtopic.php?f=64&t=41281), always provide your feedback.
