### ISSUE TITLE
A2zWordFinder detects uBlock & uses obstructive overlay

### ISSUE THREAD

**Issue by graciecat** [uBlockOrigin/uAssets#3075]
### URL(s) where the issue occurs

`https://www.a2zwordfinder.com/anagram.html`

### Describe the issue

Site works at first. Then an overlay appears and interferes with user's ability to use site.

### Screenshot(s)

![screen shot 2018-07-31 at 01 15 31](https://user-images.githubusercontent.com/18286141/43439101-73243910-945f-11e8-9f8e-872b960b88d0.png)

### Versions

- Pale Moon 28.0.0b1 (64-bit) (2018-06-28)
- uBlock Origin v1.16.4.4

### Settings

No changes to default settings other than filter lists:
    
Built-in (6/7)
- uBlock filters​
- uBlock filters – Annoyances​​​​​
- ​​uBlock filters – Badware risks​​​​​
- uBlock filters – Privacy​​​​​​​
- uBlock filters – Resource abuse
- uBlock filters – Unbreak​​​​​    ​​ 

Ads (3/4)
- Adblock Warning Removal List
- Adguard Base Filters​
- EasyList​

​​​​Privacy (3/3)
- Adguard Spyware Filters​
- EasyPrivacy​
- Fanboy’s Enhanced Tracking List​

Malware domains (2/4)
- Malware Domain List​​​​​
- Malware domains​
​​​​
Annoyances (3/5)
- Adguard’s Annoyance List​
- Fanboy’s Annoyance List​
- Fanboy’s Social Blocking List

Multipurpose (1/4)
- Peter Lowe’s Ad and tracking server list​

### Notes
Not sure what I was doing wrong, but I couldn't get element-picker to block it

UPDATE: Tried again and was able to block with this in My Filters:
```
! 7/31/2018, 1:24:20 AM https://www.a2zwordfinder.com/anagram.html
www.a2zwordfinder.com##frame:nth-of-type(3)
```

**Comment by mapx-** [comment]
test again using the default setup

**Comment by graciecat** [comment]
I tried it again with a clean browser profile and default settings. I got the same results as before. I should mention that I am using the **legacy** uBlock , as Pale Moon cannot do WebExtensions.  I have modified original post to clarify this .

**Comment by okiehsch** [comment]
If `a2zwordfinder.com##frame:nth-of-type(3)` works for you, there is nothing more to add unless someone who uses `PaleMoon` can reproduce and comes up with a different fix.

I can't reproduce with a default setup using Chrome or Firefox and no filter will be added to `uAssets` for a `PaleMoon/legacy-uBlock` issue anyway.

**Comment by mapx-** [comment]
tested in PaleMoon Version: 27.9.4 (64-bit) + legacy uBlock => no issue here.
