### ISSUE TITLE
Ads on NewAge Bangladesh Online News Site While Running uBlock Origin

### ISSUE THREAD

**Issue by confider** [uBlockOrigin/uAssets#3076]
### URL(s) where the issue occurs

`http://www.newagebd.net`
`http://www.newagebd.net/article/47105/un-at-risk-of-running-out-of-cash-warns-chief`

### Describe the issue

Hi,
I'm seeing ads in NewAge newspaper's online site. I've included an example page herewith.
Sorry if my issue submission is incomplete in any angle and thanks in advance.

### Screenshot(s)

![screenshot_2018-07-31_11-34-49](https://user-images.githubusercontent.com/41938624/43439613-c21b82ac-94b5-11e8-9e77-3d5013637267.png)

### Versions

- Browser/version: Firefox 52.9
- uBlock Origin version: 1.16.14

### Settings

- I didn't make any change to the default settings

### Notes

Reproduced this issue with Chromium 68 and Opera 54.

**Comment by mapx-** [comment]
add (in "my filters")
```
||newagebd.com/files/contents/images/sfl_worldwide.jpg$image
newagebd.net##[href="#"]
newagebd.net##.adv
```

**Comment by confider** [comment]
Still seeing the ad. Forced updated the filters and tried again. Didn't work.

**Comment by mapx-** [comment]
As I wrote above add the filters in "my filters"

**Comment by confider** [comment]
Sorry, my bad. 
It worked! Thank you.
