### ISSUE TITLE
Anti-AdBlock PopUp in Doridro(dot)com

### ISSUE THREAD

**Issue by confider** [uBlockOrigin/uAssets#3077]
### URL(s) where the issue occurs

`http://doridro.com/forum/viewtopic.php?f=25&t=3878860`

### Describe the issue

I'm seeing anti-adblocker popups in Doridro(dot)com. I've included the specific URL herewith. I'm seeing this anti-adblocker sign while using Firefox 52.9; but I cannot reproduce this issue while using Chromium 68 or Opera 54 browsers in Debian 9.

### Screenshot(s)

![screenshot_2018-07-31_12-12-42](https://user-images.githubusercontent.com/41938624/43440989-175e5956-94bb-11e8-9df9-08c5377f4b2d.png)

### Versions

- Browser/version: Firefox 52.9, Chromium 68, Opera 54
- uBlock Origin version: 1.16.14
- Operating System: Debian 9

### Settings

- Didn't change the default settings. Just force-updated the lists.

### Notes

Couldn't reproduce this issue with Chromium or Opera. Only happens with Firefox.

**Comment by confider** [comment]
Forced update uBlock filters, but still seeing this anti-adblocker.

**Comment by mapx-** [comment]
add in my filters:
`doridro.com##script:inject(addEventListener-defuser.js, load, 2000)`

test again

**Comment by confider** [comment]
I just did! Still seeing that anti-adblocker. I forced updated the filter lists and tried again. Didn't work.

**Comment by confider** [comment]
I added this line in "my filters" and it worked! Thank you.
