### ISSUE TITLE
Movie-Blog PopUps

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#308]
### URL(s) where the issue occurs

http://www.movie-blog.org/

### Describe the issue

If you click anywhere on that page or try to use the search new windows and tabs open.
First they show about:blank then advertisments for sunmaker get shown.

### Versions

- Browser/version: FF54
- uBlock Origin version: 1.11.0

### Notes

All i can find so far is a heavily obfuscated reference to PopAds.net in the inline code.

**Comment by uBlock-user** [comment]
That `BetterJsPop` variable needs to be locked down to prevent triggering the popups.

**Comment by okiehsch** [comment]
`movie-blog.org##script:inject(abort-on-property-write.js, DCVU)` , but a simple
`||sunmaker.com^$popup` also closes the popup.

**Comment by uBlock-user** [comment]
`movie-blog.org##script:inject(abort-on-property-read.js, iJ9A)`

or

`movie-blog.org##script:inject(abort-on-property-read.js, DCVU)`

Those will do the job too.
