### ISSUE TITLE
vercanalestv.com / verbeinlaliga.com anti adblocking

### ISSUE THREAD

**Issue by cmooon** [uBlockOrigin/uAssets#3081]
### URL(s) where the issue occurs

`vercanalestv.com` 
example:
`https://vercanalestv1.com/ver-eurosport-2-online-y-en-vivo-gratis-las-24-horas/`

`verbeinlaliga.com`
example:
`http://verbeinlaliga.com/historia-espana/`

### Describe the issue

Hello, I cannot  longer watch the tv through internet with ublock origin  because now the webpages detect it. Could you please see if it is possible to use ublock origin in the future in those webs? I am not really a fan of malware and adults adds.

Thank you very much for what you can do to help me.

### Versions

- Browser/version: Opera Browser 54.0.2952.64 (64-bit) and Firefox 61.0.1 (64-bit)
- uBlock Origin version: 1.16.14

### Settings

- I have followed the "Extra installation steps for uBlock Origin" of https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin in Opera and Firefox and it helped me with other webpages. I have added https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt to my list of filters and activated all the lists of filters that are in ublock origin.

**Comment by mapx-** [comment]
I get no anti-adb issues, fixing only popups on verbeinlaliga

**Comment by KiLL4FuNK** [comment]
I recommend you use only uBlock Origin

**Comment by lain566** [comment]
More popups when closing iframes on the player
`https://vercanalestv1.com/ver-motogp-en-directo-y-online-24h-gratis/`
`https://vercanalestv1.com/ver-canal-plus-partidazo-online-y-directo-gratis/`
`http://vercanalestv1.com/tv/deportes/beinliga.html`
`https://vercanalestv1.com/ver-bein-sports-la-liga-en-directo-24h-online/`
