### ISSUE TITLE
mystatesman.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#3082]
### URL(s) where the issue occurs

`https://www.mystatesman.com/`

### Describe the issue

Popular section won't load

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/43469757-ec2f3102-94b4-11e8-8d93-27785648b901.png)

### Settings

Default

### Notes

`@@chartbeat.com`

**Comment by mapx-** [comment]
@ryanbr
