### ISSUE TITLE
qaru.site [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3085]
URL(s) where the issue occurs

`http://qaru.site/questions/351670/difference-between-and-within-lua`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 67 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://forums.lanik.us/viewtopic.php?f=102&t=41260 >
https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
fixed by adguard list
