### ISSUE TITLE
http://ethfw0370q.com creating ads 

### ISSUE THREAD

**Issue by Mspy1** [uBlockOrigin/uAssets#3086]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`http://ethfw0370q.com/pvb34yszbs?key=7a4f1e968aa7846ef59a816bda8ffa09&psid=14555701`
`http://ethfw0370q.com`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
This random numbered site has to be blocked.
[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [Chrome Version 68.0.3440.75]
- uBlock Origin version: [Latest]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
You have to provide example sites / pages where you see such site

**Comment by Mspy1** [comment]
http://mp3fiber.com/

**Comment by Mspy1** [comment]
occured in this site.

**Comment by mapx-** [comment]
test these filters (anti adblocking, popups)

```
mp3fiber.com##script:inject(addEventListener-defuser.js, load, nextFunction)
mp3fiber.com##script:inject(set-constant.js, _pop, noopFunc)
mp3fiber.com##script:inject(abort-on-property-read.js, encodeURIComponent)
```

**Comment by Mspy1** [comment]
Working @mapx- . Sorry for duplicate post thought you're not looking closed issues.

**Comment by Mspy1** [comment]
Just realized the site is not redirecting to download ip,
after converting.
@mapx- 
Stuck at %100.

**Comment by Mspy1** [comment]
Redirection fail, site won't redirect to download page after this fix.
@mapx- 
Sorry didn't properly test.

**Comment by okiehsch** [comment]
Should work now, add
````
mp3fiber.com#@#script:inject(abort-on-property-read.js, encodeURIComponent)
mp3fiber.com##script:inject(setInterval-defuser.js, (), 500)
mp3fiber.com##script:inject(addEventListener-defuser.js, /^(?:click|mousedown)$/, _0x)
````
to your filters, works on my end.

**Comment by Mspy1** [comment]
Works.~

**Comment by adranger** [comment]
Add the green fake download button to the list:

![button](https://user-images.githubusercontent.com/35470489/43539567-99dc894e-959b-11e8-964a-31476fd66c74.png)

`<a href="http://p275784.clksite.com/adServe/banners?tid=MP3FIBER_DIRECT&amp;action=r"><img src="http://mp3fiber.com/download.png" width="150" height="40"></a>
`

**Comment by okiehsch** [comment]
That is already fixed in `EasyList` by the filters
````
##a[href*=".clksite.com/"]
##a[href*="/adServe/banners?"]
````

**Comment by adranger** [comment]
Ah, it's whitelisted by another list:

```
Static filter @@||mp3fiber.com^$generichide found in:

    Adguard Base Filters
```

**Comment by smed79** [comment]
add
```
mp3fiber.com##a[href*=".clksite.com/"]
mp3fiber.com##a[href*="/adServe/banners?"]
```
@AdamWr fyi.

**Comment by AdamWr** [comment]
Ok, added:
`mp3fiber.com##a[href*="/adServe/banners?"]`

Thank you.
