### ISSUE TITLE
http://mp3fiber.com/

### ISSUE THREAD

**Issue by Mspy1** [uBlockOrigin/uAssets#3087]
### URL(s) where the issue occurs
http://mp3fiber.com/

### Describe the issue
While trying to download every place in site redirects somewhere different.
Example converted file ready to download.
https://bitly.com/2mYg2wd+

### Screenshot(s)
http://i.prntscr.com/JL2XUHw7SHm-I0mKUlDOag.png

### Versions
- Browser/version: [Chrome Version 68.0.3440.75 (Official Build) 64-bit]
- uBlock Origin version: [Latest]

### Settings
Nano Defender Filter Lists~ only.

### Notes
Well this site is at sixth place or something when you want to download mp3.
Ads must be vanished.

**Comment by mapx-** [comment]
just answer my question here:
https://github.com/uBlockOrigin/uAssets/issues/3086#issuecomment-409295684

don't open other dupplicate issues
