### ISSUE TITLE
pornhub.com: Block premium thumbs

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uAssets#309]
### URL(s) where the issue occurs

NSFW: `http://www.pornhub.com/view_video.php?viewkey=1772779562`

### Describe the issue

This filter (not applicable in ABP filter syntax) will remove the annoying premium ad thumbs.
> pornhub.com##.videoblock:if(.premiumIcon)

### Screenshot

NSFW: [screenshot from 2017-03-08 07 16 23](https://cloud.githubusercontent.com/assets/25944158/23692635/2e472c10-03d0-11e7-8186-172bef2466b6.png)

### Versions

- Browser/version: Firefox 48
- uBlock Origin version: 1.11.2

### Settings

None.

### Notes

None.

_Edit by @IDKwhattoputhere: Turned direct link into code and turned NSFW embedded image into link._

**Comment by stanlane** [comment]
@gorhill Can we add this filter then?

**Comment by gorhill** [comment]
Looks to me to be self-promotion. The test is [EasyList's policy](https://easylist.to/pages/policy.html), to remove arbitrariness as much as possible:

> Self-promotion should not be specifically removed by EasyList, although equally should not be whitelisted if it is blocked.

**Comment by stanlane** [comment]
@gorhill Well yes, but they already have the "Premium" and "Upgrade" links in the top of the page.
