### ISSUE TITLE
Image gallery does not appear (rajce.idnes.cz)

### ISSUE THREAD

**Issue by slrslr** [uBlockOrigin/uAssets#3093]
### URL(s) where the issue occurs

`https://jarojaromer.rajce.idnes.cz/Prvni_pulrok_pastvy_divokych_koni_ve_Vychodnich_Cechach/`

### Describe the issue

uBlock Origin 1.16.14 blocked the list of images in an image gallery linked above.
When i click uBlock icon in my Firefox beta to see blocked elements and click "+" next to:
jarojaromer.rajce.idnes.cz
and click refresh button, the gallery start appearing.

### Versions

- Browser/version: Latest Firefox beta
- uBlock Origin version: 1.16.14

**Comment by mapx-** [comment]
add
`idnes.cz#@#script:inject(addEventListener-defuser.js, /^(beforeunload|load)$/)`

report here:
https://github.com/tomasko126/easylistczechandslovak/issues
