### ISSUE TITLE
CBS New York

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#31]
### One or more specific URLs where the issue occurs
`http://newyork.cbslocal.com`

### Describe the issue
Go to `http://newyork.cbslocal.com`, clicking on "Listen Live" is not responsive with
"uBlock filters – Privacy‎" enabled, because of the redirect
||google-analytics.com/ga.js$script,redirect=google-analytics.com/ga.js
If you disable "uBlock filters – Privacy" or just plain block
||google-analytics.com  you can use "Listen Live" as intended.

### Your settings

- Browser/version: Chrome 50.0.2661.87
- uBlock Origin version: 1.6.8

**Comment by gorhill** [comment]
Thanks for reporting.

Purge the cache of only one of your filter list and for an update -- should work after this.
