### ISSUE TITLE
www.mackungfu.org

### ISSUE THREAD

**Issue by ialexryan** [uBlockOrigin/uAssets#310]
### URL(s) where the issue occurs

`http://www.mackungfu.org/`

### Describe the issue

Site is completely blocked when using uBlock Origin. BlockAdBlock is the culprit.

### Screenshot(s)

![image](https://cloud.githubusercontent.com/assets/2292782/23788270/9e786c82-052a-11e7-9b18-90f13b278f4c.png)

### Versions

- Browser/version: Chrome 56.0.2924.87
- uBlock Origin version: 1.11.0

### Settings

- None

### Notes

I tried adding `mackungfu.org##script:inject(bab-defuser.js)` to the My Filters page but it only worked intermittently.

**Comment by mapx-** [comment]
add
`@@||mackungfu.org^$generichide`

**Comment by uBlock-user** [comment]
or

`mackungfu.org##script:inject(noeval.js)`

**Comment by okiehsch** [comment]
`mackungfu.org##script:inject(bab-defuser.js)` works on my end with Chrome 57.
Anyway, if `generichide` works, that is the prefered solution and best dealt with by `Easylist`.
Explanation: https://github.com/uBlockOrigin/uAssets/commit/f340633dc681d6e0fb696359e06f5498dd5e0c39#commitcomment-20429199

**Comment by SMed79** [comment]
Reported https://forums.lanik.us/viewtopic.php?f=62&t=35870
