### ISSUE TITLE
anonyviet.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3100]
URL(s) where the issue occurs

`https://anonyviet.com/share-tool-reg-clone-facebook/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by uBlock-user** [comment]
Try - `@@||anonyviet.com^$generichide`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by stephenhawk8054** [comment]
There's a placeholder annoyance in the site. Placeholders do not appear when testing with only `EasyList` + `VIE: ABPVN List`.

URL:
`https://anonyviet.com/gaugan-ve-tranh-dua-tren-noi-dung-van-bang-bang-ai-cua-nvidia/`

<details><summary>Screenshot</summary>

![4](https://user-images.githubusercontent.com/66517106/146488430-837affb3-7619-41a6-a7f7-1dc750a79bda.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78478
  cosmetic: 41209
  scriptlet: 16363
  html: 607
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2302-2, 41m
  default: 
    ublock-filters: 30587-38, 12m
    ublock-badware: 3573-1, 12m
    ublock-privacy: 184-0, 12m
    ublock-abuse: 81-0, 12m
    ublock-unbreak: 1734-0, 12m
    easylist: 62004-598, 1h.26m
    easyprivacy: 26502-478, 12m
    urlhaus-1: 7269-0, 12m
    plowe-0: 3690-3, 12m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 171
  launchFromSelfie: true
popupPanel: 
  blocked: 21
```
</details>

It is due to the filter

`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js:5`

If I strict block it, the placeholders disappear

```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js:5,badfilter
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js:5,domain=~anonyviet.com
```

**Comment by gorhill** [comment]
Should be `##.adsbygoogle`, it matches more elements on the page.

**Comment by uBlock-user** [comment]
> It is due to the filter


Caused by `@@||anonyviet.com^$generichide`, with `$ghide` present, site specific cosmetic filters are required to be added individually.

**Comment by gorhill** [comment]
Yes, I of course meant should be `anonyviet.com##.adsbygoogle` instead of `anonyviet.com##.adsbygoogle`.

**Comment by stephenhawk8054** [comment]
> > It is due to the filter
> 
> Caused by `@@||anonyviet.com^$generichide`, with `$ghide` present, site specific cosmetic filters are required to be added individually.

I see that there's also a `$generichide` in `ABPVN List`, but when I tested with EL and ABPVN List, those placeholders do not appear. So is it really because of `$ghide`?

**Comment by uBlock-user** [comment]
I add

```
@@||anonyviet.com^$generichide,badfilter
@@||anonyviet.com$generichide,badfilter
```

and I don't see a single placeholder there.

**Comment by stephenhawk8054** [comment]
Oh I see, I didn't realize they have different syntaxes.

**Comment by gorhill** [comment]
Hmm issue in dev build, that is not right:

![Screenshot from 2021-12-17 09-07-56](https://user-images.githubusercontent.com/585534/146556593-1a6cc02c-d475-4721-ab10-3172d2b9d431.png)
