### ISSUE TITLE
discoveryrom.org [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3101]
URL(s) where the issue occurs

`https://www.discoveryrom.org/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by mapx-** [comment]
`@@||pagead2.googlesyndication.com/pagead/$script,domain=discoveryrom.org`

**Comment by ghajini** [comment]
does this filter ever work?

**Comment by okiehsch** [comment]
It works on my end with Chrome and Firefox.

**Comment by mapx-** [comment]
Did you click "read more" ?

**Comment by okiehsch** [comment]
Well, to my shame I must admit no.

So adding your filters is the correct fix.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
