### ISSUE TITLE
https://www.atresplayer.com/directos/lasexta/             anti-adblock

### ISSUE THREAD

**Issue by artisan69** [uBlockOrigin/uAssets#3103]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.atresplayer.com/directos/lasexta/`
`https://www.atresplayer.com/directos/mega/`

### Describe the issue

[Anti-adblock message doesn't pop, up but if you don't turn UBO off, the stream just doesn't play. This is an online TV network]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [chrome/67.0.3396.99]
- uBlock Origin version: [uBlock Origin v1.16.14]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[I used to deal with this with REEk]

**Comment by mapx-** [comment]
Tested (using a spanish IP), no issues here, no anti adblocking message.
Remove aak script (outdated), disable any other blocking extension (keep only uBo), test again.

**Comment by lain566** [comment]
No anti-adblock warning, but the player is broken again.

**Comment by QURANMUBEEN** [comment]
ALLAH HAKEEM
ALLAH KARIM 
ALLAH MAJID
ALLAH MUHEET

**Comment by mapx-** [comment]
all fine here
