### ISSUE TITLE
[Anti-adblock] reevown.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3105]
### URL(s) where the issue occurs

`https://reevown.com/`

### Describe the issue

Anti-adblock. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43555387-178e78be-95b7-11e8-9b82-23cdae8825e5.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default.

**Comment by ghajini** [comment]
its back
`https://reevown.com/uptobox`
![screenshot 105](https://user-images.githubusercontent.com/20338483/51555403-8a453180-1e9d-11e9-8463-adb1ee42be1a.png)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/967e2481fd5761a483df7d758e9e9cea80d6c747
