### ISSUE TITLE
[Anti-adblock] torrentdosfilmeshd.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3106]
### URL(s) where the issue occurs

`http://www.torrentdosfilmeshd.net/vingadores-guerra-infinita-torrent-2018-bluray-720p-1080p-dublado-dual-audio-download/`

### Describe the issue

Block screen can be closed, but comes up every refresh. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/43555472-95a0b79e-95b7-11e8-8d56-643d10771fb7.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default. Tried Spanish regional filters, didn't change anything.

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
