### ISSUE TITLE
On-click advertisement on https://downloadhub.cc

### ISSUE THREAD

**Issue by TontyTon** [uBlockOrigin/uAssets#3107]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://downloadhub.cc/`
A piracy site

### Describe the issue

On the given website, first click on the page opens an advertisement page (1bcde.com) in new tab (which itself is blocked by ublock).

### Versions

-uBlock Origin version: 1.16.14
-Browser Name and version: Google Chrome 67.0.3396.99 (Official Build) (64-bit)

### Settings

On default settings and enabling all filters other than regional filters.

### Notes

URL which is doing this: septembership.com

After blocking this another URL does its work and on blocking it another, these are-
![capture](https://user-images.githubusercontent.com/35778430/43578243-d06fa466-966b-11e8-95aa-0058f338235e.PNG)

I was able to know this as only one of them was loading at a time, when one is blocked then on refresh new one loaded.

After blocking all these then only first click on the page doesn't open the site(1bcde.com).

**Comment by TontyTon** [comment]
@mapx- why the issue is closed? Is it solved? Are links added to filters?

**Comment by mapx-** [comment]
read again:
`closed this in [ed91134](https://github.com/uBlockOrigin/uAssets/commit/ed9113443645aa5ad6f012b1e1472d41f272f89c)`

**Comment by TontyTon** [comment]
@mapx- Oh! I am sorry.
