### ISSUE TITLE
olx.ua

### ISSUE THREAD

**Issue by GoodGuyNick** [uBlockOrigin/uAssets#3108]
### URL(s) where the issue occurs

`olx.ua`

### Describe the issue

Contact button not working in any advert.

### Versions

- Browser/version: [Firefox 61.0.1, Chromium 66.0.3359.181]
- uBlock Origin version: [1.16.14]

### Settings

- Default setting with enabled filters: **Fanboy’s Enhanced Tracking List**, **uBlock filters – Privacy** and **EasyList**

### Notes
Contact button not working in any advert.
Open any advert and try to press contact button.
Registration is not required for testing.

If **uBlock filters – Privacy** enabled and **Fanboy’s Enhanced Tracking List** disabled button will not work.
If **uBlock filters – Privacy** and **EasyList** enabled but **Fanboy’s Enhanced Tracking List** disabled button will work.
If **uBlock filters – Privacy** disabled and **Fanboy’s Enhanced Tracking List** enabled button will work.

**Comment by mapx-** [comment]
test
```
@@||googletagmanager.com/gtm.js$script,domain=olx.ua
@@||ninja.onap.io/ninja-cee.js$script,domain=olx.ua
```

**Comment by GoodGuyNick** [comment]
All good now.

**Comment by mapx-** [comment]
The filters above should be add by the maintainers of Fanboy’s Enhanced Tracking List, + easyprivacy

(you already posted in the right place: 
https://github.com/ryanbr/fanboy-adblock/issues/493 

just re-open that issue)

**Comment by GoodGuyNick** [comment]
Thank you
