### ISSUE TITLE
||estream.*^$script filter

### ISSUE THREAD

**Issue by PlaneteStream** [uBlockOrigin/uAssets#3113]
### URL(s) where the issue occurs

`https://estream.planetestream.org`

### Describe the issue

When accessing a Planet eStream site using uBlock Origin with the uBlock Filter enabled JavaScript is unable to load. This is being caught by [`||estream.*^$script` on line 7275. ](https://github.com/uBlockOrigin/uAssets/blob/32a3dfd045e8d3ff0695550dc1b27d64ba6c64c6/filters/filters.txt#L7275)

### Screenshot(s)

Without uBlock enabled:
![image](https://user-images.githubusercontent.com/12295193/43651092-59461f0e-9739-11e8-88e5-f99c1d780d7c.png)
With uBlock enabled:
![image](https://user-images.githubusercontent.com/12295193/43651124-6f2f6f5a-9739-11e8-936e-651db65c6665.png)

### Versions

- Browser/version: Version 67.0.3396.99 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.16.14

### Settings

No further modifications made.

### Notes

Taking a look at the notes for this block of URLs it references this list: https://forums.lanik.us/viewtopic.php?f=62&t=40609

However this does not contain the lines affecting this issue so I'm wondering if this was either added by accident or was in reference to a previous estream.nu address.

If you need any more information on this then please let me know.

**Comment by valdearg** [comment]
Apologies, I should have been more specific. The filter is too restrictive, we have multiple customers who use estream.domainname for their sites. When uBlock is installed this prevents the JavaScript from running. 

If this could be removed or changed to what is was before (estream.nu?) this will resolve the issue.

**Comment by PlaneteStream** [comment]
Apologies, I should have been more specific. The filter is too restrictive, we have multiple customers who use estream.domainname for their sites. When uBlock is installed this prevents the JavaScript from running.

If this could be removed or changed to what is was before (estream.nu?) this will resolve the issue.
