### ISSUE TITLE
in.xrivonet.info [Anti-Adblock] [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3114]
URL(s) where the issue occurs

`http://in.xrivonet.info/34f.html#3ax`

Describe the issue

Anti-Adblock Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by lain566** [comment]
There's still a popup when click anywhere.

**Comment by okiehsch** [comment]
Does
`xrivonet.info##script:inject(window.open-defuser.js)`
work for you, I can't find a working stream.

**Comment by lain566** [comment]
@okiehsch Yeah, that works.
