### ISSUE TITLE
'umterps.com' does not load

### ISSUE THREAD

**Issue by ogoleman** [uBlockOrigin/uAssets#3115]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://umterps.com/`

### Describe the issue

Site does not load properly with ubo enabled.  Basically site provides not content except a template,

### Screenshot(s)

![screenshot at 2018-08-03 14 36 06](https://user-images.githubusercontent.com/42075113/43659650-a164490a-972a-11e8-87bf-f02ef9520d1f.png)

### Versions

- Browser/version: FF 61.0.1
- uBlock Origin version:  u Block Origin v1.16.14

### Settings

Not sure what the default filter list is, but the following are checked:
All ublock's except experimental
EasyList
Malware Domain List
Malware domains
Adguard’s Annoyance List​​​​​
​​Fanboy’s Annoyance List​
Peter Lowe’s Ad and tracking server list​​​​​

### Notes

Will add as I investigate

**Comment by AdamWr** [comment]
Fixed, thank you.
