### ISSUE TITLE
SK

### ISSUE THREAD

**Issue by pit711** [uBlockOrigin/uAssets#3116]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs 
`https://www.suedkurier.de/region/hochrhein/bad-saeckingen/Rhein-ist-mit-26-26-Grad-so-warm-wie-seit-31-Jahren-nicht-mehr;art372588,9843898`

### Describe the issue

Nano Adblock detected

### Versions

- Browser/version: Chrome 68.0.3440.84
- Nano Adblocker v1.0.0.59

**Comment by okiehsch** [comment]
@pit711 I see that one can only read the articles with a paid subscription at `suedkurier.de`.
Do you have one and can you confirm that the added filter does not break anything?
