### ISSUE TITLE
[NSFW] watchpornfree.ws

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#3118]
### URL(s) where the issue occurs

`https://watchpornfree.ws/faces-covered-7-watch-online-free`

### Describe the issue

Ads and pop-ups when you click on the player and anywhere.

### Screenshot(s)

https://user-images.githubusercontent.com/27441315/43641243-25d6f456-9723-11e8-8c06-51f62379e06d.jpg

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.14

### Settings

Default settings.

**Comment by dumbusernameidk** [comment]
csp breaks download `https://gounlimited.to/5oq814wpve0v/sincityvee-2018-group-show-december.mp4` 

NSFW.
