### ISSUE TITLE
https://www.gamebrew.org/ anti-adblock (blockadblock)

### ISSUE THREAD

**Issue by mariomadproductions** [uBlockOrigin/uAssets#3120]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.gamebrew.org/`

### Describe the issue

A "blockadblock" screen appears telling you to turn your adblock off if you have it on.

### Screenshot(s)

Not need

### Versions

- Browser/version: Google Chrome Version 67.0.3396.99 (Official Build) (32-bit)
- uBlock Origin version: uBlock Origin v1.16.14

### Settings

- None

### Notes

Could not find any other issue regarding blockadblock

**Comment by mariomadproductions** [comment]
closing because of the no "anti-adblock" issue rule

**Comment by okiehsch** [comment]
>  no "anti-adblock" issue rule

What do you mean?

**Comment by mariomadproductions** [comment]
Maybe I misread it :P
Reopened
