### ISSUE TITLE
animeheaven.eu anti-adblock

### ISSUE THREAD

**Issue by Verryn** [uBlockOrigin/uAssets#3121]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://animeheaven.eu/watch.php?a=Overlord%20Dubbed&e=1`

### Describe the issue

Anti-adblock message where the video should be.

### Screenshot(s)

![animeheaven anti-adblock](https://user-images.githubusercontent.com/11181001/43678449-869285c6-97e1-11e8-8b47-7df3a9ba55f2.PNG)

### Versions

- Browser/version: Chrome 68.0.3440.84
- uBlock Origin version: 1.16.14

### Settings

Default

**Comment by ghajini** [comment]
`https://animeheaven.co/watch/jojo-no-kimyou-na-bouken-ougon-no-kaze-sub?ep=151595'
Antiadblock
![screenshot_2019-01-19-00-32-18-375_org mozilla firefox](https://user-images.githubusercontent.com/20338483/51408131-b25b2a80-1b55-11e9-8f79-9b9aeedebcdf.png)
