### ISSUE TITLE
re: animeheaven.eu anti-adblock

### ISSUE THREAD

**Issue by Verryn** [uBlockOrigin/uAssets#3127]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://animeheaven.eu/watch.php?a=Overlord%202nd%20Season%20Dubbed&e=1`

### Describe the issue

Anti-adblock message where the video should be.

### Screenshot(s)

![animeheaven anti-adblock](https://user-images.githubusercontent.com/11181001/43682048-150e4670-9835-11e8-8f22-d77d090b8d76.PNG)

### Versions

- Browser/version: Chrome 68.0.3440.84
- uBlock Origin version: 1.16.14

### Settings

Default

### Notes

They've updated the anti-adblock within 24 hours.

**Comment by okiehsch** [comment]
No need to open a new issue, just use the one you opened 10 hours ago, after all it is the same issue.
