### ISSUE TITLE
City Anti-Adblock

### ISSUE THREAD

**Issue by TheEnhas** [uBlockOrigin/uAssets#313]
### URL(s) where the issue occurs

http://www.citytv.com/toronto/shows/bones/ (Any video on the site, that's just one example page)

### Describe the issue

When trying to load a video, you are redirected to a blocker page telling you to disable your ad blocker.

### Screenshot(s)

![citytvblock](https://cloud.githubusercontent.com/assets/25448414/23823921/12d78a4a-0643-11e7-836c-df1f5d5cd5f8.png)

### Versions

- Browser/version: Google Chrome 57.0.2987.98 beta (64-bit)
- uBlock Origin version:  1.11.2.0
- uBlock Origin Extra version: 2.12

### Settings

- Default.

### Notes

Like I said on the Mozilla Discourse page, I wish there was more documentation towards finding the proper variables or scripts to block. There is plenty for cosmetic filtering but next to none for using redirects or injecting scriptlets.

I think this site is using FuckAdblock 3.2.0 going by what I found in one of the javascript files (utiliyx.js), but redirecting it or using "citytv.com##script:inject(fuckadblock.js-3.2.0)" does not work.

Yes, I'm asking for the fix but at the same time I also want to know a bit of the reasoning behind it. A small tutorial if you will.

**Comment by mapx-** [comment]
try
`@@||citytv.com^$generichide`

**Comment by TheEnhas** [comment]
Thanks, that seems to work.

So white-listing generichide should always be one of the first things to try on a problem site?

**Comment by mapx-** [comment]
yes, it's one of the most common tricks.

**Comment by gorhill** [comment]
Since the solution is a ABP-compatible filter, it should be reported to EasyList maintainers: <https://forums.lanik.us/viewforum.php?f=62>.

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=35882
