### ISSUE TITLE
smotret-anime.ru | anime365 - 20 seconds request for donation before the video

### ISSUE THREAD

**Issue by BoberMod** [uBlockOrigin/uAssets#3131]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://smotret-anime.ru/catalog/satsuriku-no-tenshi-18617/5-seriya-177441/ozvuchka-1892366`
`https://smotret-anime.ru/catalog/roku-de-nashi-majutsu-koushi-to-akashic-records-14867/1-seriya-150238/ozvuchka-1722967`
`https://play.shikimori.org/animes/36316-shichisei-no-subaru/video_online/5/1797338`
`https://play.shikimori.org/animes/y30831-kono-subarashii-sekai-ni-shukufuku-wo/video_online/1/1409636`

### Describe the issue

Before each video in this player window opens, as in the screenshot below. The "Пропустить рекламу" ("skip ads") button appears after 20 seconds. After clicking it, this window is disabled for 6 minutes for all videos. **uBO disables all other ads in the player except this one!**

### Screenshot(s)

![image](https://user-images.githubusercontent.com/8740496/43687880-665651ec-98e6-11e8-95ff-0bb08502fd4b.png)

### Versions

- Browser/version: Chrome 68.0.3440.84
- uBlock Origin version: 1.16.14

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

I tried to block, but after that the whole player is blocked.
ADguard's fix: https://github.com/AdguardTeam/AdguardFilters/issues/14951 (not tested)

**Comment by BoberMod** [comment]
This is loaded before viewing if the advertisement is not skiped
![image](https://user-images.githubusercontent.com/8740496/43688428-e73a3d78-98f0-11e8-93da-d004db6c5f6e.png)

**Comment by okiehsch** [comment]
Disabling the donation request screen with `uBO-filters` will also break the video player as far as I can see.
I could remove the annoying audio message accompanying the donation request, not sure if you are bothered by it, I know I am after listening to it a few times.

**Comment by BoberMod** [comment]
Well, at least something.

**Comment by okiehsch** [comment]
Removed audio message in `uBO-annoyances`.

**Comment by ZaphodBeebblebrox** [comment]
To be honest, I am not sure why that works, but it does, so I added it.

**Comment by okiehsch** [comment]
Does it work if you reload the page?

**Comment by ZaphodBeebblebrox** [comment]
Yes.

**Comment by okiehsch** [comment]
I get ads if I delete cookies and reload, so I would not close it until th OP has said it is fixed on his/her end.
@BoberMod if you update `uBO-annoyances` or add 
````
smotret-anime.ru##div[style*="opacity: 1; z-index: 9600;"]:style(opacity: 0 !important; pointer-events: none !important;)
````
to your filter list is the issue fixed on your end.

**Comment by jspenguin2017** [comment]
How is 20 seconds of anti-adblock block screen just an annoyance? 

![image](https://user-images.githubusercontent.com/7283682/44128783-fc1b2fa0-a001-11e8-94d3-32951dcdf11c.png)

**Comment by okiehsch** [comment]
It does not block site functionality it just annoyingly delays it. :)

Do you think the blocked audio message is an annoyance? I ask because if we add your filter to `uBO-filter` all users with a default setup will hear the audio message while the adblock message is blocked by your filter.

To be clear, I will add both filters to the same list, assuming, they work for the OP, because it makes no sense to split them up from a users perspective.

**Comment by jspenguin2017** [comment]
Well, it's your call. 

The filter doesn't always work, might need some ND treatment for this one.

**Comment by jspenguin2017** [comment]
The offending code is just an inline script with base64 encoded payload. Should be rather easy to edit from ND.

**Comment by okiehsch** [comment]
I am open to arguments, I added the audio-filter to annoyances because at the time there was no working filter for the main issue.
I this anti-adblock message only happens once every browser session I would categorize it as an annoyance, if it happens at the start of every third video I would fix it in `uBO-filters`.

**Comment by jspenguin2017** [comment]
> this window is disabled for 6 minutes

Considering a video is around 24 minutes, it's more like 3 times per video.

**Comment by okiehsch** [comment]
Thanks, I missed that, so in that case I will add the fix to `uBO-filters`.
Let's just wait for the OP to confirm that it works.

**Comment by jspenguin2017** [comment]
It does kind of work, but the play button still gets stuck sometimes. 
I'll investigate later to find a proper fix. 

Meanwhile, can someone figure out what's the current fix in Adguard?

**Comment by okiehsch** [comment]
> Meanwhile, can someone figure out what's the current fix in Adguard?

I think it is not fixed
https://github.com/AdguardTeam/AdguardFilters/issues/21028#issue-349841364
is still open.

**Comment by BoberMod** [comment]
@okiehsch, no, this doesn't work and after pressing the play button starts advertising from youtube.

**Comment by jspenguin2017** [comment]
Does this qualify for uBO-Extra or I should just shove it into ND?

**Comment by okiehsch** [comment]
I don't know what @gorhill thinks about this specific issue.

**Comment by jspenguin2017** [comment]
Can we revert `cd36e9b8b9fe2f12422f990b9ecd5d85006bfbb4` until we are sure that it doesn't break things?

**Comment by gorhill** [comment]
> I don't know what @gorhill thinks about this specific issue.

Doesn't preventing just media from `data:` URI fix the issue? (along with the filter that was removed above)

    ||smotret-anime.ru^$csp=media-src *

There is a small delay when clicking playback, but that doesn't seem too bad.

**Comment by okiehsch** [comment]
````
smotret-anime.ru##div[style*="opacity: 1; z-index: 9600;"]:style(opacity: 0 !important; pointer-events: none !important;)
||smotret-anime.ru^$csp=media-src *
`````
works on my end.
@BoberMod ?

**Comment by BoberMod** [comment]
@okiehsch, It works. No message asking for donation, no sound, just animation loading ~10 seconds.

**Comment by solara322** [comment]
again not work. 20 sec ads all time...

**Comment by solara322** [comment]
again not work

**Comment by BoberMod** [comment]
Confirm 
RU AdList JS Fixes also not working
