### ISSUE TITLE
 Adding 'related videos', 'recommended articles', subscription prompts, etc to Annoyances list

### ISSUE THREAD

**Issue by prodan1234** [uBlockOrigin/uAssets#3132]
"Related videos", "recommended articles", "more on this topic", "subscribe here!", "join our newsletter",  infinite scrolling, slideshows, polls and unrelated videos on a web page are a distraction and should be blocked by the Annoyances filter.

Example webpages: 
`https://www.newyorker.com/magazine/2018/08/06/private-dreams-and-public-ideals-in-san-francisco`
`https://money.cnn.com/2018/08/05/media/jeff-fager-cbs-vacation/`
`https://www.vanityfair.com/news/2018/07/inside-the-trump-2020-campaigns-disorganized-attempt-to-keep-america-great`
`https://www.wired.com/story/tesla-self-driving-car-computer-chip-nvidia/`
`https://www.cnet.com/news/sorry-but-your-iphone-or-android-phone-is-going-to-get-even-more-expensive/`
`https://www.rollingstone.com/politics/politics-news/nra-financial-trouble-706371/`
`https://news.avclub.com/fx-head-says-marvel-killed-off-donald-glovers-deadpool-1828106301`
`https://www.theverge.com/2018/8/5/17648524/colony-cancelation-dystopia-usa-network-carlton-cuse-rip`

Screenshots:
https://imgur.com/a/QiM2bPx 

List Subscriptions you're using:
Easy List, Easy Privacy, uBlock lists

- OS/version: macOS 10.13.6
- Browser/version: Chrome 68.0.3440.84
- Adblock Extension/version: uBlock Origin 1.16.14

**Comment by smed79** [comment]
Why spam three forums at the same time with the same message? 
**Crossposting** is also annoying if you do not know.

- https://github.com/ryanbr/fanboy-adblock/issues/515
- forums.lanik.us (disapproved, read before posting [rules#participation](https://forums.lanik.us/rules#participation))

PS: _...please follow issue template._

**Comment by prodan1234** [comment]
Sorry, didn't know crossposting was discouraged. Feel free to close the other one if you want.

**Comment by VernonStow** [comment]
From Dashboard -> Filter Lists, expand the "Annoyances" listing. Adguard and/or Fanboy's annoyances filter may be what you need.
![annoyances](https://user-images.githubusercontent.com/15573459/43697059-5de0ebc0-98f6-11e8-9b5f-02b9713fa2ae.png)

**Comment by ryanbr** [comment]
Adguard's Annoyances isn't good enough.
