### ISSUE TITLE
ThePirateBay Proxy List

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#3134]
### URL(s) where the issue occurs

`https://piratebays.co/torrent/9940252/The.Legend.of.Zelda.Skyward.Sword.USA.Wii-SUSHi`
 or
`thepiratebay site` + `/torrent/9940252/The.Legend.of.Zelda.Skyward.Sword.USA.Wii-SUSHi`

### Describe the issue

Popups, fake links and buttons.

### Screenshot(s)

![2018-08-04_17-25-19](https://user-images.githubusercontent.com/27441315/43684855-2f0b5e82-98a8-11e8-9c9e-ac1010a69784.png)

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.14

### Settings

Default settings.

### Notes

```
ahoypirate.click
alivbay.org
batpirate.info
baybaypirate.org
baypirate.click
baypiratebay.be
baypirateproxy.pw
bayproxy.eu
baythepirate.fi
capjackproxy.net
duckingproxy.eu
hyperproxy.net
ikwildepiratebay.org
indiaproxy.in
pirat2.club
pirataibay.in
piratbaypirate.link
pirate.bet
pirate.blue
pirate.shiksha
pirate.trade
pirateahoy.net
piratebaai.click
piratebaai.club
piratebay.click
piratebay.red
piratebay247.net
piratebaymirror.eu
piratebayproxy.tf
piratebays.co
piratenbucht.eu
piratepirate.eu
pirateprox.club
pirateproxy.click
pirateproxy.tf
pirateproxy.wf
pirateproxy.yt
piratetoday.click
proxybayduck.fi
proxyfl.info
proxyoneahoy.net
proxypirate.in
proxyproxyproxy.nl
proxyship.click
proxytpb.org
proxytpb.pw
rowpirate.org
thepirate.click
thepiratebay-proxy.com
thepiratebay.bet
thepiratebay.blue
thepiratebay.futbol
thepiratebay.pet
thepiratebay.pictures
thepiratebay.shiksha
thepiratebay.tel
thepiratebay.wtf
tpb.tw
tpbairproxy.in
tpbbay.eu
tpbmirror.us
tpbportal.in
tpbproxy.club
tpbproxyone.org
ukpirate.click
ukpirate.org
ukpirateproxy.xyz
unblockedhyperbay.info
unblocktpb.com
urbanproxy.eu
wearepirates.click
zombay.org
```

**Comment by smed79** [comment]
@ryanbr fyi.

**Comment by ghajini** [comment]
1.Malicious ad redirects 

​common to all sites popup script

`http://49oa3o49b6.com`


`https://piratbaypirate.link/`
`https://unblocktheship.org/`
`https://noobnoob.rocks/`
`https://indiaproxydl.org/browse`
`https://magnetbay.eu/`
`https://airproxyproxy.pw/`
`https://thepirate.xyz/`
`https://pietpiraat.org/`
`https://ahoypirate.in/`
`https://tpb.tw/`
`https://proxyindia.net/`
`https://thepiratebay.blue/`
`https://ahoypiratebaai.eu/`
`https://pirate.bet/`
`https://airproxytpb.red/`
`https://ikwildepiratebay.xyz/browse`
`https://piratebay.tel/browse`
`https://bayception.pw/`
`https://piratebay.town/`
`https://superbay.link/`
`https://thepiratebay.kiwi/`
`https://tpb.one/`
`baypirateproxy.pw`

2.all sites listed in original thread under notes section are either parked domains or require another proxy to serve them -needs testing for those domains, I can't some of them

**Comment by lain566** [comment]
These sites have miners

```
https://hyperproxy.net/
https://hyperbaytpb.top/
https://thepirate.one/
https://bayhypertpb.be/
https://pirata.pw/
https://airproxyboat.in/
https://duckingproxy.eu/
https://unblocktpb.com/
https://proxyproxyproxy.nl/
https://piratebayproxy.tf/
https://pirateproxy.yt/
https://pirate.shiksha/
```

**Comment by Khazbs** [comment]
Due to all these malicous website URLs, BitDefender thinks this file is a threat and blocks it, which is funny. If it happens to you too, safely exclude this file in your AV.
