### ISSUE TITLE
rogers.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#314]
https://www.rogers.com/web/totes/#/signin
When you enter your credentials and try to log into your account it doesn't let you log in unless you disable uBlock Origin on that website.
![rogers com](https://cloud.githubusercontent.com/assets/26278182/23827909/d16d03b4-068d-11e7-974d-d4183f267ec1.jpg)
Firefox 51.0.1
uBlock Origin 1.11.2

**Comment by okiehsch** [comment]
Does it work if you add `@@||assets.adobedtm.com$script,domain=www.rogers.com`?

**Comment by js017** [comment]
Yes. Using @||assets.adobedtm.com$script,domain=www.rogers.com worked. Thanks.
 
-----Original Message-----
