### ISSUE TITLE
LinkNeverDie.com

### ISSUE THREAD

**Issue by Smithienious** [uBlockOrigin/uAssets#3142]
### URL(s) where the issue occurs

`https://linkneverdie.com/Download/e1b660b4-0349-4675-8c8e-3ba48a5ea48c
https://linkneverdie.com/Download/ce23be1b-0e63-4b32-b611-8fd931091aba`
and basically all download links from the site

### Describe the issue

The "load captcha" dialogue would not disappear and the captcha would not load

### Screenshot(s)

https://prnt.sc/kfci2a
After zapping the dialogue: http://prntscr.com/kfcip6

### Versions

- Browser/version: 70.0.3514.0 (Official Build) canary (64-bit)
- uBlock Origin version: 1.16.14

### Settings

- Default

### Notes

I can provide an account if needed

**Comment by Smithienious** [comment]
`Username: baauco`
`Password: 12102001`

**Comment by okiehsch** [comment]
Does adding
````
linkneverdie.com#@#script:inject(setTimeout-defuser.js)
linkneverdie.com##script:inject(setTimeout-defuser.js, _$_, 7000)
linkneverdie.com##[href="https://acegalaxy.asia/"]
````
to your filters work for you?

**Comment by Smithienious** [comment]
It works
