### ISSUE TITLE
bloombergquint.com [Anti-adblock behavior]

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#3144]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.bloombergquint.com/politics/2018/08/06/mueller-secures-firewall-counsel-over-evidence-in-russia-case

### Describe the issue

After page loads, the page is "eaten" and the main page content disappears. I assume this is some sort of anti-adblock but there is no message displayed telling the user to turn off adblock. 

I tried unselecting and disabling all filter lists and reloading with 0 active filters and still the page disappeared with NO active filters. 

Only after disabling uBO through the popup panel for the site was the contents able to load and stay loaded, I assume they are doing some type of testing within the browser to see what plugins are enabled.

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/22258847/43747044-0eb549ce-99d7-11e8-9d8e-6110b1e2e9bf.PNG)

### Versions

- Browser/version: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
- uBlock Origin version: 1.16.15.100
- uBlock Origin Extra 2.74

### Settings

Tested on both (neither keeps the page content loaded):
- Test profile with default settings and lists.
- Test profile with detault settings and NO lists enabled (0 active filters)

### Notes

Page content only stays loaded for me after clicking the power button in uBO popup panel and reloading the site.

**Comment by okiehsch** [comment]
> Page content only stays loaded for me after clicking the power button in uBO popup panel and reloading the site.

I can fix the issue by adding
`@@||google-analytics.com/analytics.js$script,domain=bloombergquint.com`
to my filter list and disabling `uBO-experimental`.

**Comment by SkeletalDemise** [comment]
This isn't anti-adblock as far as I can see. Looking at the website, it just seems to be bad coding. If it fails to get `google-analytics` it breaks a lot of the main code, not by purpose.

**Comment by uBlock-user** [comment]
Can't reproduce, and no anti adblock behaviour either.

> I tried unselecting and disabling all filter lists and reloading with 0 active filters and still the page disappeared with NO active filters.

Probably pulling from the cache, do a cache-free reload.

**Comment by gorhill** [comment]
I can't reproduce -- they fixed their site?

**Comment by yourduskquibbles** [comment]
I can't reproduce anymore either. Thanks for checking -- guess it is bad coding on their end.
