### ISSUE TITLE
Anti-adblock 24sms.net

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#3145]
### URL(s) where the issue occurs
`http://www.24sms.net/`

### Describe the issue
After you try to send a sms, you got "Please turn off ad blocker"

### Screenshot(s)
![i](https://user-images.githubusercontent.com/27068733/43769364-0fdd4016-9a29-11e8-8d94-9e7e0c967ebb.jpg)

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.16.14

**Comment by mapx-** [comment]
test this filter (told me it was sent but .. no sms arrived)
`@@||pagead2.googlesyndication.com/pagead/$script,domain=24sms.net`

**Comment by krystian3w** [comment]
This site do not update ReCaptha.

> ![image](https://user-images.githubusercontent.com/35370833/43776579-9633c280-9a50-11e8-92e9-e5bbf36ba4ff.png)

**Comment by uBlock-user** [comment]
Site is broken, found `Uncaught SyntaxError: Unexpected token ;` in the console.
