### ISSUE TITLE
KissAnime Banning

### ISSUE THREAD

**Issue by mrehanabbasi** [uBlockOrigin/uAssets#3146]
### URL(s) where the issue occurs

`http://kissanime.ru/Anime/Eudemon-Quest/Episode-010?id=148729&s=default`

### Describe the issue

As soon as any video on KissAnime is opened, this message is displayed:

**"Please disable uBlock (or any ads blocking) to watch anime on KissAnime. You have just been banned for a few days because of this."**

And no video will play.

### Screenshot(s)

![KissAnime Screenshot](https://user-images.githubusercontent.com/19202888/43770282-5dede040-9a55-11e8-875c-1bfdf5bba245.png)

### Versions

- Browser/version: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- uBlock Origin version: 1.16.14

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/2719
