### ISSUE TITLE
igg-games.com... annoying  popups on clicking

### ISSUE THREAD

**Issue by lmlim** [uBlockOrigin/uAssets#315]
### URL(s) where the issue occurs

http://igg-games.com

### Describe the issue

clicking on links or any areas almost always will popup a random e-commerce page.

### Versions

- Browser/version: chrome Version 57.0.2987.98 (64-bit)
- uBlock Origin version: 1.11.2

### Settings

none related to this site.

**Comment by mapx-** [comment]
add
```
|http://$script,domain=igg-games.com,third-party
@@||ajax.googleapis.com^$domain=igg-games.com
```

**Comment by lmlim** [comment]
thanks it works....
