### ISSUE TITLE
pornhub.com: Block non-HD thumbs

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uAssets#316]
How do I make non-HD thumb videos in pornhub.com disappear?

### URL(s) where the issue occurs

NSFW: `http://pornhub.com/`

### Describe the issue

HD thumbs are presented in `<li>` that has `<span class="hd-thumbnail">HD</span>` in them, non-HD thumbs lack this setting.

For demostration, this will block HD thumbs:
> pornhub.com##.videoblock:has(.hd-thumbnail)

But I want to block **non-HD** thumbs. I tried this solution without success:

### Versions

- Browser/version: Firefox 52
- uBlock Origin version: 1.11.2

### Settings
Nothing.

### Notes
Nothing.

_Edit by @IDKwhattoputhere: Turned direct link into code and added NSFW warning._

**Comment by okiehsch** [comment]
Does `pornhub.com##.videoblock:if-not(.hd-thumbnail)` work for you?

**Comment by stanlane** [comment]
@okiehsch Sorry, no.

**Comment by stanlane** [comment]
@okiehsch Yes! Your solution works.

@gorhill Can we add this filter to **uBlock filters**?

Perhaps we should start a separate filter list for this category of filter?

**Comment by gorhill** [comment]
> Can we add this filter to uBlock filters?

This has no place in uBlock filters, this is your personal preferences.

**Comment by stanlane** [comment]
@gorhill Ok, but it's still a very useful filter that many people would use. However, I respect your opinion.
