### ISSUE TITLE
Filter no working properly

### ISSUE THREAD

**Issue by SEXXES** [uBlockOrigin/uAssets#3162]
`https://www.basellandschaftlichezeitung.ch/basler-wahlen-2012/der-nette-svpler-patrick-hafner-betont-seine-kompromissbereitschaft-125267636`

**Comment by smed79** [comment]
You pay no one to help you, at least follow the issue template and provide the necessary infos.

**Comment by mapx-** [comment]
original reported here, @smed79  is right: in the future provide all the details !

**Comment by TheSavageOne** [comment]
Sonya
