### ISSUE TITLE
cnet.com "g00" ad reinsertion

### ISSUE THREAD

**Issue by VernonStow** [uBlockOrigin/uAssets#3164]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.cnet.com/news/phones-used-by-verizon-at-t-t-mobile-sprint-filled-with-vulnerabilities-say-researchers/`

### Describe the issue

"g00" ad reinsertion, hanging the page and using over 1 GB of RAM

### Screenshot(s)

![phones at all major us carriers filled with vulnerabilities say researchers - cnet 2018-08-08](https://user-images.githubusercontent.com/15573459/43861210-017ba796-9b0b-11e8-94a9-46a01ec7afe1.png)

### Versions

- Browser/version: Firefox 61.0.1 (32-bit)
- uBlock Origin version: 1.16.14

### Settings

- Default filters + Adguard Annoyances, Fanboy Enhanced Tracking

### Notes

Same exact behavior as I observed with MSN. The URL briefly changes to one including "g00," then the page freezes and the ads slowly appear as the RAM usage climbs rapidly.

**Comment by okiehsch** [comment]
I can't reproduce with uBO-extra enabled.
I closed your [MSN-issue](https://github.com/uBlockOrigin/uAssets/issues/3046), with this [comment](https://github.com/uBlockOrigin/uAssets/issues/3046#issuecomment-408514007).

Nothing has changed.

**Comment by gwarser** [comment]
This time in Firefox?

>Browser/version: Firefox 61.0.1 (32-bit)

I see only one g00 beacon request, no ads (linux).

**Comment by okiehsch** [comment]
Oh, I missed the Firefox part, sorry about that.

**Comment by mapx-** [comment]
only g00 beacon here too

**Comment by okiehsch** [comment]
I can't reproduce either.
`cnet.com##^script:has-text(IXC_)`
will "fix" `the g00-beacon`, you have to bypass the cache for it to work.

@VernonStow does adding
`cnet.com##^script:has-text(IXC_)`
work for you?

**Comment by VernonStow** [comment]
@okiehsch yes, adding the filter `cnet.com##^script:has-text(IXC_)` solves the problem for me. Thanks!

**Comment by ghajini** [comment]
other sites also affected on which ubo extra is useful on FIREFOX

**Comment by ghajini** [comment]
almost every site has g00 beacon issue (`https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful`)
i tested few but list is long
sandiegotribune.org
sun-sentinel.com
baltimoresun.com
boston.com
capitalgazette.com
carrollcountytimes.com
chicagotribune.com
citypaper.com
courant.com
ctnow.com
dailypress.com
delmartimes.net

**Comment by ghajini** [comment]
@mapx-
Are you able to reproduce, g00 beacons still on my end in Firefox in above sites

**Comment by mapx-** [comment]
or test directly this filter
`com,net,org##^script:has-text(IXC_)`

**Comment by ghajini** [comment]
Works on all listed sites

**Comment by ghajini** [comment]
I still see g00 ad reinsertion at `edmunds.com` on ***GOOGLE CHROME STABLE***

**Comment by mapx-** [comment]
right, @gorhill  / @okiehsch  will take a look at it ( already in uBo extra but probably they - instart - have changed something )

**Comment by okiehsch** [comment]
@mapx- you can reproduce at `edmunds.com`?

**Comment by mapx-** [comment]
yes, in chrome 69, US IP
