### ISSUE TITLE
uBlock blocking a plugin I want to use to validate forms

### ISSUE THREAD

**Issue by DaPo** [uBlockOrigin/uAssets#3169]
### URL(s) where the issue occurs

`https://5euros.com`

### Describe the issue

Hi,

On the URL where the issue occurs, I use [https://github.com/lordfpx/AB-formValidation](AB-formValidation).

On the new form we are currently developing when I use uBlock I have the following error:
```
Uncaught TypeError: window.abFormValidation is not a function
```

But if I disable uBlock, I don't have the error and everything seems to be fine.

### Versions

- Browser/version: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.16.14

### Notes

My error is not on the main website since I'm developing this form so I can't really give you an URL where the issue occurs.

**Comment by mapx-** [comment]
- see in the logger what is blocked, post here
- create a test page where we can get the issue

**Comment by gwarser** [comment]
Works fine in demo https://codepen.io/lordfpx/pen/RgdygX?editors=0010

This script: `https://rawgit.com/lordfpx/AB-formValidation/master/dist/AB-formValidation.min.js` ?

**Comment by okiehsch** [comment]
I can reproduce if I add
`codepen.io##script:inject(abort-on-property-read.js, CustomEvent)`
![image](https://user-images.githubusercontent.com/16838044/43974956-5a35d492-9cdc-11e8-9659-9199a5b2fd91.png)

`##script:inject(abort-on-property-read.js, CustomEvent)`
is used on `5euros.com` to disable the [adback](https://landing.adback.co) script.
I will change that filter.

@DaPo does your form work if you add
````
5euros.com#@#script:inject(abort-on-property-read.js, CustomEvent)
5euros.com##script:inject(abort-on-property-read.js, ng)
````
to your filters?

**Comment by DaPo** [comment]
Hello @okiehsch,

Yes id does indeed! Nice catch! What can we do about it?

**Comment by okiehsch** [comment]
I have updated the filter in `uBO-Privacy`, forcing an update of that list should solve your issue.

**Comment by okiehsch** [comment]
The `uBO-Privacy` list auto updates every 5 days.
