### ISSUE TITLE
"uBlock filters – Unbreak​​​​​​​​​" breaks video

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#317]
### URL(s) where the issue occurs

`http://www.transfermarkt.tv/aus-50-metern-depay-mit-unglaublicher-bude/video/video/12922`

### Describe the issue

The video at 
`http://www.transfermarkt.tv/aus-50-metern-depay-mit-unglaublicher-bude/video/video/12922` 
will not play if you have `uBlock filters – Unbreak​​​​​​​​​` enabled.

### Versions

- Browser/version: Chrome 57
- uBlock Origin version: 1.11.2

### Settings

- Default

### Notes

The reason for the broken video is the redirection
`||amazon-adsystem.com/aax2/amzn_ads.js$script,redirect=amazon-adsystem.com/aax2/amzn_ads.js`
if you allow or just  block `amazon-adsystem.com/aax2/amzn_ads.js`
the video plays fine on my end.

**Comment by gorhill** [comment]
Does this fix the issue on your side?

    ||amazon-adsystem.com/aax2/amzn_ads.js$script,redirect=noopjs,domain=player.performgroup.com

If so, you can add it to unbreak, below the main `||amazon-adsystem.com/aax2/amzn_ads.js` one.
