### ISSUE TITLE
What about overflow "pop-up's" on the landing page?

### ISSUE THREAD

**Issue by SEXXES** [uBlockOrigin/uAssets#3173]
I think anyone knows these overflow "pop-ups" asking you to subscribe for newsletters, prompting you about something etc.

It's OK to see them the first time when you access a site. However sometimes they keep coming up every time you click another link on such webpages.

I use the extension called "I don't care about cookies" on Chrome, what helps a little but doesn't work perfectly.
https://www.i-dont-care-about-cookies.eu

Is µBlock planning to add a filter for such kind of webpage behavior?

**Comment by mapx-** [comment]
subscribe "fanboy's annoyances" list

**Comment by SEXXES** [comment]
Thank you very much, I'm going to try it for a week, if it doesn't work as expected I'll let you know!

Thanks again!
