### ISSUE TITLE
Printfriendly.com Browser Extension seems to be blocked by µBO

### ISSUE THREAD

**Issue by SEXXES** [uBlockOrigin/uAssets#3175]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://web.archive.org/web/20150326165657/http://brooksrunning.de/396504/661/de/Trinkempfehlungen.html]` + the brwoser-extension of https://www.printfriendly.com/

### Describe the issue

[Seems like the web app is blocked by some/a filter(s). I'm able to generate a new printable page on the website of printfriendly.com but not with the browser extension.]

### Versions

- Browser/version: [Chrome Version 68.0.3440.106]
- uBlock Origin version: [1.16.14]

### Settings

- [see annex pics]

### Notes

[Reported issue to printfriendly.com support]

![i](https://user-images.githubusercontent.com/42209961/43990877-26b17f0a-9d62-11e8-9bc1-9c31a50f6acc.jpeg)
![ii](https://user-images.githubusercontent.com/42209961/43990879-28695e44-9d62-11e8-9d23-03017005bb9b.jpeg)

**Comment by mapx-** [comment]
You should look into your logger, see what is blocked

**Comment by SEXXES** [comment]
Im a dummy and not an IT-guy, so I dont know how to do that. However it is still not working. I just tried it on Firefox with the same filter settings/extensions and its also NOT working.

**Comment by mapx-** [comment]
- click uBo icon, click the third button under the big blue button => to open the logger
- read more about the logger: https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by SEXXES** [comment]
Thanks a lot, done…

![i](https://user-images.githubusercontent.com/42209961/44001712-22e2e884-9e37-11e8-983c-f9e5a82de392.jpeg)
![ii](https://user-images.githubusercontent.com/42209961/44001714-2535fe64-9e37-11e8-9287-55407e49814c.jpeg)

**Comment by mapx-** [comment]
- well, it's a fanboy's annoyance filter
- you can whitelist that filter
`@@||printfriendly.com^`

**Comment by SEXXES** [comment]
Thank you very much. Worked on the "my filters" list, not on the "whitelist". However as it worked out fine, the problem is solved.

So just for my understanding: where should I report problems with lists if not here?

**Comment by SEXXES** [comment]
I also do not have any more problems after I changed filter settings
so this thread can be closed
