### ISSUE TITLE
scoopwhoop.com - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#318]
There are _**promoted articles**_ on https://www.scoopwhoop.com which appear on article lists on the website. 
The articles in the list always have a css selector `class="cardType3"` but the promoted articles which are marked as "**PARTNER**" also have the additional element `<p class="cat">PARTNER</p>` inside of this class.

I am not familiar with **uBO filters** which should work with this, please help.

**SS:** http://i.imgur.com/3tSHO9A.png
**Error URL:** https://www.scoopwhoop.com/

You can see these promoted articles if you scroll down the page.

_**Note:** Using uBO 1.11.2 with Chrome 57._

**Comment by mapx-** [comment]
`scoopwhoop.com##.cardType3:has-text(PARTNER)`

**Comment by mapx-** [comment]
read about:
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjecthas-textneedle

**Comment by gotitbro** [comment]
Thanks @mapx-  that filter works. I was unwittingly including the **class** in the has: field.
