### ISSUE TITLE
Ad blocker detected a www.cnn.com.

### ISSUE THREAD

**Issue by streetwolf** [uBlockOrigin/uAssets#3187]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`www.cnn.com`

### Describe the issue

I receive a message that an Ad Blocker was detected after going to a few links.

### Screenshot(s)

![screenshot_2018-08-11 kavanaugh argued a president would have to testify before a grand jury if subpoenaed](https://user-images.githubusercontent.com/410799/43995745-0df2fb72-9d82-11e8-8354-fb5ef5172970.png)

### Versions

- Browser/version: Fx 63 Nightlds
- uBlock Origin version: 1.16.17b1

### Settings

          assetFetchTimeout 30
  autoUpdateAssetFetchPeriod 120
            autoUpdatePeriod 7
     cacheStorageCompression true
             debugScriptlets false
       ignoreRedirectFilters false
   ignoreScriptInjectFilters false
manualUpdateAssetFetchPeriod 500
               popupFontSize unset
       suspendTabsUntilReady false
       userResourcesLocation unset

### Notes

None

- Browser/version: Fx63 Nightly
- uBlock Origin version: 1.16.17b1

**Comment by streetwolf** [comment]
My screenshot doesn't lie.  It might take a little while to get it.  Could it be a filter subscription I'm missing.  I'm also going to the USA cnn site.  What other things can I provide you?

**Comment by okiehsch** [comment]
Me adding an "unable to reproduce"  label does not imply that I think you made it all up. :)

It only means that **I** can't reproduce with a default setup using Chrome or Firefox.
Maybe it's dependent on the location, i.e you need a US-IP for example, or there are other factors.

The issue remains open, so if somebody else can reproduce he/she can come up with a working filter.

**Comment by streetwolf** [comment]
Don’t get me wrong.  I know you don’t think I made it up.  I was just pointing out that a picture is worth a 1000 words.  The detection started about 3 days ago btw.  What location are you getting to cnn from?  If not the USA perhaps you can use a VPN server in the USA to reproduce it?

-----
Gary

________________________________

**Comment by okiehsch** [comment]
I can't use a VPN at the moment, anyway @ZaphodBeebblebrox has a US-IP and can check this issue.

**Comment by streetwolf** [comment]
If you need any logs from me let me know.

-----
Gary

________________________________

**Comment by ZaphodBeebblebrox** [comment]
I cannot reproduce either.

**Comment by streetwolf** [comment]
I was playing around with my filter lists and for as of yet unknown reasons I haven’t got the ad-blocker message since then.  My filter list is exactly the way it was before.  Go figure.

-----
Gary

________________________________
