### ISSUE TITLE
kengso.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#3188]
### URL(s) where the issue occurs

`http://www.kengso.com/s?st=&wd=test`

### Describe the issue

**Fanboy’s Annoyance List** (##.user-share) hides the search results.

He says he can't reproduce it, and closed the issue - https://github.com/ryanbr/fanboy-adblock/issues/510

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/35470489/43670896-f24d93ca-9767-11e8-93e3-753a6cf4ceb7.png)

### Versions

- Browser/version: Firefox 61.0.2
-  Adblock Extension/version: uBlock Origin 1.16.14

**Comment by okiehsch** [comment]
@ryanbr I can reproduce

![image](https://user-images.githubusercontent.com/16838044/43996066-17a50cda-9dbb-11e8-9f5c-6415aa628251.png)

**Comment by okiehsch** [comment]
@adranger I will not add filters to `uAssets` for issues that are caused by non default filter lists, if the maintainer of such a list does not fix the issue for whatever reason you will have to fix it in your personal filter list.
