### ISSUE TITLE
fdesouche.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#319]
**URL**

`http://www.fdesouche.com/`

**Describe the issue**

`blockadblock.com` anti adblock 

**Screenshot**

http://i.imgur.com/Txm9LzO.png

### Versions

- Browser/version: FF / 52
- uBlock Origin version: v1.11.5b0

**Settings**

Default settings + Liste FR + Liste AR + Annoyance list

**Fix**

`fdesouche.com##script:inject(bab-defuser.js)`

**Notes**

https://forums.lanik.us/viewtopic.php?p=114716#p114716

**Comment by SMed79** [comment]
@okiehsch Can you please fix the pop-overlay and background amazon ads on [fdesouche.com](https://forums.lanik.us/viewtopic.php?p=132496#p132496)

- http://i.imgur.com/h30Glae.png
- http://i.imgur.com/l5mlWWC.png

Thank you.

**Comment by mapx-** [comment]
test
```
||fdesouche.com/wp-content/uploads/2018/02/Sans-titre-2.jpg$image
fdesouche.com##a[href^="http://amzn.to/"]
||fdesouche.com/wp-content/themes/fdesouche2014/js/libs.js
```

**Comment by SMed79** [comment]
`fdesouche.com##a[href^="http://amzn.to/"]`
already in **Liste FR**

`||fdesouche.com/wp-content/uploads/2018/02/Sans-titre-2.jpg$image`
they put a new background every day or each time is blocked.
* http\://www.fdesouche.com/wp-content/uploads/2018/02/arlo.jpg
* http\://www.fdesouche.com/wp-content/uploads/2018/02/Sans-titre-2.jpg

`||fdesouche.com/wp-content/themes/fdesouche2014/js/libs.js`
added https://hg.adblockplus.org/listefr/rev/091140ebd17d

**Comment by mapx-** [comment]
for the background stuff try
`fdesouche.com###site > div:has(a[href^="http://amzn.to/"])`
