### ISSUE TITLE
anti-adblock pop-up at https://www.wiwo.de/

### ISSUE THREAD

**Issue by prof7bit** [uBlockOrigin/uAssets#3193]
### URL(s) where the issue occurs

https://www.wiwo.de/

### Describe the issue

a modal anti-adblock pop-up immediately pops up in the middle of the screen

### Versions

- Browser/version: Firefox 61.0.1 (64-Bit)
- uBlock Origin version: v1.16.14

**Comment by okiehsch** [comment]
Already fixed. https://github.com/uBlockOrigin/uAssets/commit/4024c3896741da477ec7fd3cab6a91d61ffd10a9

Updating your `uBO-filter` list should solve your issue.
