### ISSUE TITLE
Dailymotion ad before videos

### ISSUE THREAD

**Issue by Matthewus** [uBlockOrigin/uAssets#32]
`http://www.dailymotion.com/video/x4686qy_eng-sub-160411-tvn-dream-players-ep-3-mamamoo-cut`

Sometimes i get ads before videos on Dailymotion. I'm in Hungary, and i get hungarian ads.
If i click on the ad, it opens a new tab with this address: `http://www.dailymotion.com/ac/video/*` and i see an empty site.

- Browser/version: Firefox 45.0.2 64bit
- uBlock Origin version: 1.6.8

**Comment by gorhill** [comment]
I can't reproduce on my side -- I need to be able to reproduce just to be able to start to investigate.

Be sure your dailymotion is using HTML5 player, uBO's fix does not apply to Flash-based player.

**Comment by Matthewus** [comment]
I'm using the HTML5 player.
I took this screenshots of the logger.
'http://www.dailymotion.com/ac/video/x44mjzu?*' appeared many times while the ad played.
![kepernyokep 2016-04-24 - 20 37 25](https://cloud.githubusercontent.com/assets/9383850/14769611/609c4f06-0a5c-11e6-99aa-10b1ac8203db.png)
![kepernyokep 2016-04-24 - 20 33 38](https://cloud.githubusercontent.com/assets/9383850/14769592/25cd2e0e-0a5c-11e6-8d5f-67ce3bfa4d7d.png)
![kepernyokep 2016-04-24 - 20 34 46](https://cloud.githubusercontent.com/assets/9383850/14769596/29f8f2d8-0a5c-11e6-81e1-d103b841c1b3.png)
![kepernyokep 2016-04-24 - 20 35 06](https://cloud.githubusercontent.com/assets/9383850/14769599/2cc60d34-0a5c-11e6-8bb3-c3b5fd73b6f7.png)

**Comment by gorhill** [comment]
What filter lists do you have selected?

**Comment by Matthewus** [comment]
uBlock filters‎
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Unbreak
EasyList‎
Peter Lowe’s Ad server list‎
EasyPrivacy‎
Malware Domain List‎
Malware domains
facebook annoyances blocker
I don't care about cookies

**Comment by gorhill** [comment]
The screenshot of logger output do not match the filter lists you list.

**Comment by Matthewus** [comment]
Here is a screenshot of the selected lists:
![kepernyokep 2016-04-25 - 10 40 29](https://cloud.githubusercontent.com/assets/9383850/14778313/97fd92b8-0ad2-11e6-848f-c0f1b12655bf.png)

**Comment by gorhill** [comment]
> Here is a screenshot of the selected

The logger makes it clear, at least _uBlock filters -- Privacy_ was not selected when you took screenshots of the logger output, and that you did not also select _uBlock filters_ would also explain why you get ads on Daily Motion. I will close as invalid until you come up with a clear way for anybody to reproduce.

**Comment by Matthewus** [comment]
Sorry, i can't give more details. I tried again with a fresh profile, installed uBlock Origin, updated the filters, did not change the settings, and the first video i watched i got an ad.

**Comment by gorhill** [comment]
`googletagservices.com` is blocked and redirected if you are using uBO's filters, your logger screenshots show it is not the case on your side. Same with `google-analytics.com`, it should be redirected using uBO's filters, and your logger screenshots show it is not happening.

**Comment by Matthewus** [comment]
I can show you a log when 'googletagservices.com' is redirected, but i get the ad.

**Comment by gorhill** [comment]
Unless me or someone else ready to investigate is able _to reproduce_ the issue, there is nothing which I personally can do. This is true for whoever maintain filter lists: they need to be able to reproduce to investigate, let alone fix.

**Comment by IDKwhattoputhere** [comment]
Not able to reproduce. But I don't get ads with the flash player either.

**Comment by Matthewus** [comment]
I found one person who saw the same ad using uBlock Origin, he's hungarian too. So i tried using a VPN with US IP, checked several videos, saw no ads, turned VPN off, i get the ad again. The ad is in hungarian.
