### ISSUE TITLE
[Ads / Anti-adblock] wowescape.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3200]
### URL(s) where the issue occurs

`http://www.wowescape.com/play/wow-lost-desert-escape/18974`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/44005806-747cecf4-9e36-11e8-8a5e-16013c00cb08.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default.

**Comment by mapx-** [comment]
```
@@||wowescape.com^$generichide
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=wowescape.com
@@||pagead2.googlesyndication.com/pagead/$script,domain=wowescape.com
@@||googleads.g.doubleclick.net/pagead/*wowescape.com$xmlhttprequest,domain=imasdk.googleapis.com
@@||youtube.com/get_video?$media,domain=wowescape.com
```

**Comment by okiehsch** [comment]
I don't see a better fix without breaking the game.

**Comment by jspenguin2017** [comment]
Eh... I wouldn't call this fixed. 
![image](https://user-images.githubusercontent.com/7283682/44069482-4171eb3c-9f3c-11e8-8d09-bc73e7b349b5.png)

**Comment by jspenguin2017** [comment]
Yea, it's kind of hard to fix in uBO. I'll land a rule in ND.

**Comment by okiehsch** [comment]
I did not see failed request-blocks yesterday
`wowescape.com##[id^=aswift]`
works on my end, I will update the fix.

**Comment by jspenguin2017** [comment]
@okiehsch That doesn't block the video ads: 
![image](https://user-images.githubusercontent.com/7283682/44070693-8bd1002c-9f42-11e8-9674-8fd90a15007d.png)

**Comment by okiehsch** [comment]
I know, I meant the gray failed request 
![image](https://user-images.githubusercontent.com/16838044/44070827-4826d150-9f86-11e8-826b-57d779d300c6.png)

If you can come up with a uBO-compatible filter that blocks the video ads without breaking the "game", I will add it and remove the exceptions.

**Comment by jspenguin2017** [comment]
I don't think there's a way to block the ads without patching the inline scripts, which uBO can't do unless gorhill implements privileged resources.

**Comment by jspenguin2017** [comment]
`onbeforescriptexecute` can be polyfilled: 
https://github.com/jspenguin2017/Snippets/blob/master/onbeforescriptexecute.html

**Comment by jspenguin2017** [comment]
@okiehsch Can we reopen this though? I can be fixed, we just need a scriptlet. I think we can come up with something that won't be too dangerous to let other filter maintainers to use.

**Comment by jspenguin2017** [comment]
Can we make a surrogate for IMA SDK that just say there's no ads to play? Or ads skipped? 

This should be a decent starting point: https://github.com/jspenguin2017/uBlockProtector/blob/master/src/resources/ima3.js

**Comment by jspenguin2017** [comment]
The website updated, I'm not sure if it's working now or it's playing a 9 minutes ads, can someone re-test?

**Comment by jspenguin2017** [comment]
Broke.

**Comment by garry-ut99** [comment]
To make it clear for players: `https://www.wowescape.com/play/escape-from-illusion-forest-html5/32318` still anti-adblock message but it happens even with uBO disabled and it's just annoyance, because still can press Play button to play, so it's nothing to report/bother.
