### ISSUE TITLE
Reddit broken

### ISSUE THREAD

**Issue by brunocassol** [uBlockOrigin/uAssets#3201]
### URL(s) where the issue occurs

`https://www.reddit.com/`

### Describe the issue

Reddit's new design has been broken for me for the last 2 days'ish with uBlock Origin . I'm logged in with a Reddit user and using the new Reddit design. The subreddit dropdown combo on top-left of the screen doesn't load the subs I'm subscribed in. When opening a sub it halts on the first page. It wont load page 2 if you scroll down. When clicking on a post the comments won't load.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/203541/44007771-281be918-9e69-11e8-918e-d74b013d91a6.png)

![image](https://user-images.githubusercontent.com/203541/44007932-2427143e-9e6b-11e8-9542-872945df4f24.png)

Clicking on /r/all instead of typing the address in the browser loads it like this:

![image](https://user-images.githubusercontent.com/203541/44007952-63f34722-9e6b-11e8-8978-380c936eb3f9.png)

### Versions

- Browser/version: 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable) (Windows 10 latest update)
- uBlock Origin version: v1.16.14

### Settings

- All default

### Notes

Temporary solution is to either replace www with dd to use Reddit's old design or disable uBlock Origin. 

For example: https://dd.reddit.com/r/all/ instead of https://www.reddit.com/r/all/

**Comment by okiehsch** [comment]
Has already been fixed in [`uBO-unbreak`](https://github.com/uBlockOrigin/uAssets/commit/d35acffe44d544f32c6012ad649e8231dc041dee) 3 days ago, just update that list, it auto updates every 4 days.

**Comment by brunocassol** [comment]
>  just update that list

thanks!

For the other people with this problem this is how you trigger a manual update of uBlock Origin list:

https://www.reddit.com/r/uBlockOrigin/comments/6ulu7d/how_to_manually_trigger_ublock_origin_lists/

**Comment by okiehsch** [comment]
Or use the wiki. :)
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

**Comment by brunocassol** [comment]
That works too. Reddit is the first link Google gave me :)
