### ISSUE TITLE
http://ah.pe    bypass problem

### ISSUE THREAD

**Issue by skyfire000** [uBlockOrigin/uAssets#3202]
### URL(s) where the issue occurs

`http://ah.pe/biR9`

### Describe the issue

when finish recaptcha , it won't redirect but return to do the captcha agian

### Versions

- Browser/version: Firefox
- uBlock Origin version: uBlock Origin v1.16.14

**Comment by mapx-** [comment]
yeah, I get the same behaviour .. but you have to insist.

However, after finishing recaptcha I get a popunder

`||ah.pe^$popunder`
