### ISSUE TITLE
Can't open link on Mail.ru

### ISSUE THREAD

**Issue by valodka** [uBlockOrigin/uAssets#3203]
### URL(s) where the issue occurs

https://e.mail.ru/messages/inbox/

### Describe the issue

Open https://e.mail.ru/messages/inbox/
Open any letter with external link.
Click on link in letter.
New window can't open.

### Versions

- Browser/version:  Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 IP
- uBlock Origin version: v1.16.14

### Note 
There is broken commit 
https://github.com/uBlockOrigin/uAssets/commit/a534e5e3dedfd445b694333aa321c1b6a4d5a8db

**Comment by mapx-** [comment]
removed
https://github.com/uBlockOrigin/uAssets/commit/df1f0b8843dfbe0f162d71b306dec2f067c19e5b

**Comment by lain566** [comment]
Is there a way to block popups?
This filter works for me https://github.com/uBlockOrigin/uAssets/commit/df1f0b8843dfbe0f162d71b306dec2f067c19e5b

Test link
`https://my.mail.ru/video/embed/9158856564302414963`

**Comment by dportvine** [comment]
@dimisa-RUAdList
Are these rules outdated?

**Comment by dimisa-RUAdList** [comment]
Unfortunately, we don't have any feedback to determine if the `clb670603` property is unique to this video, or generally usable.

One way or another, RU AdList contains universal rules that prevent new windows from opening after a click, even if the target property has a random name.
