### ISSUE TITLE
foreignpolicy.com paywall

### ISSUE THREAD

**Issue by tgr** [uBlockOrigin/uAssets#322]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`foreignpolicy.com`

### Describe the issue

Uses validate.onecount.net to block unpaywalled access after some quota is met (in theory; in practice the logic is crappy so you can get blocked whether you hit the quota or not). 

### Screenshot(s)

![fp1](https://cloud.githubusercontent.com/assets/145412/24069760/3530c1b8-0b6d-11e7-8f28-7c8407ee9e5b.png)
![fp2](https://cloud.githubusercontent.com/assets/145412/24069763/394cdaf2-0b6d-11e7-9a24-a02f17469ad7.png)

### Versions

- Browser/version: 55.0.2883.87 (64-bit)
- uBlock Origin version: v1.11.4

### Notes

Adding the filter `||validate.onecount.net$script` makes the paywall go away and does not cause any obvious problems.

**Comment by gorhill** [comment]
We need to draw a line here: the purpose of uBO filters should not be to work around paywalls, **unless** the site is asking to disable the blocker. I don't see such request here.

**Comment by tgr** [comment]
You might want to put that in CONTRIBUTING.md or otherwise clarify, then. I looked at the filters before submitting (since there weren't any guidelines otherwise), and [there already was one](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L667) to work around the FP paywall, it just didn't work.

(FWIW I tried to just pay first, but the FP subscription page is broken and I was unable to get through it, so I made a filter and figured I might as well share it.)

**Comment by gorhill** [comment]
Looks like this would [fit into Fanboy Annoyances](https://adblockplus.org/forum/viewtopic.php?f=2&t=15309#p76368).

Maybe I could create a "uBlock filters -- Annoyances" (optional) for cases which can't be handled by Fanboy Annoyances -- I can't remember but the reason I may have added this filter is that plain ABP filter syntax was not sufficient as can be seen from the `:style(...)` filter.

**Comment by uBlock-user** [comment]
Noting more than a 3rd party annoyance, they're not offering any premium content but rather putting this annoyance on news articles, that's laughably bad. Just block all third-party scripts there and you're good to go.

**Comment by uBlock-user** [comment]
Nothing more than a 3rd party annoyance, they're not offering any premium content but rather putting this annoyance on news articles, that's laughably bad. Just block all third-party scripts there and you're good to go.

**Comment by Quix0r** [comment]
I have now these block rules added (all were called, some seem to be tracker-pixel stuff):
````
foreignpolicy.com###paywall_bg
*/oc_track/*
||metrics.foreignpolicy.com^
s.jsrdn.com/s/*
validate.onecount.net/js/*
````
