### ISSUE TITLE
vide-greniers.org [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3221]
URL(s) where the issue occurs

`https://vide-greniers.org/43-Haute-Loire/Chenereilles-43/vide-greniers_673820`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by Pshy0** [comment]
Not fixed: Site is displaying a cookie warning, and even when accepted, asks to disable the ad blocker or pay.

To reproduce:
- Visit [vide-greniers.org](https://vide-greniers.org/01-Ain).
- Accept cookies.
- ublock is detected and the site asks to disable it or pay.

**Comment by stephenhawk8054** [comment]
I can't reproduce:

<img width="1260" alt="Image" src="https://github.com/user-attachments/assets/8e902315-cb2a-491d-a4a0-3c914afec6ac" />
