### ISSUE TITLE
[Anti Adblock] animehub.ac

### ISSUE THREAD

**Issue by shirtjs** [uBlockOrigin/uAssets#3224]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`
`https://animehub.ac/watch/pokemon-sun-and-moon-sub`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

The website says to disable adblock or you cannot watch the videos.
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

![screenshot from 2018-08-14 08-10-06](https://user-images.githubusercontent.com/2660574/44090838-83d1d67e-9f99-11e8-9eea-9b256367c126.png)

### Versions

- Browser/version: Chrome 68 on Linux
- uBlock Origin version: 1.16.16

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
popups at https://animehub.ac/watch/one-piece-sub?ep=14407

Filter -- `animehub.ac##+js(abort-current-inline-script.js, RegExp, zfgloaded)`

@mapx-
