### ISSUE TITLE
Redirect rules does not work for XmlHttpRequest requests

### ISSUE THREAD

**Issue by Mirodil** [uBlockOrigin/uAssets#3227]
### URL(s) where the issue occurs

`example.com`

### Describe the issue

I'm trying to redirect a XHR request to `noopmp4-1s` to block videos which comes from through XHR request. 
The steps to reproduce the issue:
- Add one of the filter rules from listed below or all of them
- Click to `Apply Changes` button
- Navigate to any page and open `DevTool` and switch to  `Console` tab
- Execute this snippet `await fetch('https://example.com/load')`
- As you can see redirection does not work(returns 404), request goes to website.

But blocking XHR request works. Here the steps:
- Add `||example.com/$xmlhttprequest` or `||example.com/$xml`
- Execute this snippet `await fetch('https://example.com/load')` in DevTool Console
- As you can see from the console log it does block request

### Versions

- Browser/version:  Google Chrome Version 69.0.3480.0  (Official Build) canary (64-bit)
- uBlock Origin version: 1.16.14

### Settings

- Advanced Mode is ON
- Added the filter rules on `My Filters` tab

### Notes

Here is the filter rules which I tried:
`||example.com/$xmlhttprequest,redirect=noopmp4-1s,domain=github.com`
`||example.com/$xml,redirect=noopmp4-1s,domain=github.com`
`||example.com/$xmlhttprequest,redirect=noopmp4-1s,first-party`
`||example.com/$xml,redirect=noopmp4-1s,first-party`

**Comment by mapx-** [comment]
`noopmp4-1s` can be used only for `$media` requests

**Comment by Mirodil** [comment]
Does it mean I cannot redirect XHR request to `noopmp4-1s`?

**Comment by mapx-** [comment]
Exactly
