### ISSUE TITLE
NSFW czechhq.net popunders and antiadblock

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#323]
### URL(s) where the issue occurs
`czechhq.net` 

### Describe the issue
1.go to above site
2.click on any site ,a new popunder will be opened
3.if we block that popunder using manual rules,it again make another popunders rules
4.clicking video and antiadblock notice is shown
this site regularly injects new popunders and uses new adservers
### Screenshot(s)
`http://prntscr.com/elgqq5`
sorry can't provide link  indicating antiadblock about NSFW site, test yourself by clicking on any video

### Versions

- Browser/version: chrome Version 57.0.2987.110 (64-bit)

- uBlock Origin version: 1.11.4,ubo extra 2.13

### Settings

- uBO's default settings+adblock warning removal list

### Notes

tried easylist filters but their filters are knocked off regularly by site
also easylist offering whitelistes unnecessarily on this site.....

**Comment by mapx-** [comment]
add
```
|http://$xmlhttprequest,third-party,domain=czechhq.net
@@|http://*.video/js/pop.js
||datoporn.co^$popup
29443kmq.video###center-ad
@@||streamdefence.com/view.php?*$domain=czechhq.net
```
