### ISSUE TITLE
[Ads Leftover] visioncloud.info

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3238]
### URL(s) where the issue occurs

`https://animesvision.net/streaming/anv/17/1991/episodios/one-punch-man-dublado/48906/`

### Describe the issue

Ads leftover, rule: `visioncloud.info##+js(setTimeout-defuser.js, .modal();, 2000)`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/44126394-417d2902-9ff5-11e8-86f9-379b2942e221.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.14

### Settings

English default. Tried Portuguese regional filters.

**Comment by okiehsch** [comment]
I would say the anti-adblock message is the main issue, but I will add your filter too of course.

**Comment by jspenguin2017** [comment]
Which anti-adblock?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/44126904-0b705582-a03b-11e8-86e0-3b6bdecde2e6.png)

**Comment by Rapperk** [comment]
This issue have been fixed right? Somehow i still get that popup, i updated the filters, so not sure whats happening :s

**Comment by ZaphodBeebblebrox** [comment]
Filter lists take a few days to update if you don't force an udpate, if you keep getting it after, we'll look into it.

**Comment by Rapperk** [comment]
Hi, yes my system and browser is clean, i haven't checked for malware today, but i do it once a week, no malware found.
I disabled all extensions, but i keep getting the pop-up :s

**Comment by okiehsch** [comment]
@Rapperk can you post your logger output of `https://visioncloud.info/om/a/MDs0ODkwNg`?

- Open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger)

- Load `https://visioncloud.info/om/a/MDs0ODkwNg`

- type `dom` in the "filter log entries" box

**Comment by Rapperk** [comment]
<img width="962" alt="log" src="https://user-images.githubusercontent.com/42440290/44228494-5a2a9180-a18d-11e8-9d9d-205d78e1e583.png">

This?

**Comment by okiehsch** [comment]
Yes, thanks.
Your filters appear to be not up to date, for whatever reason.

Add `visioncloud.info##+js(setTimeout-defuser.js, .modal();, 2000)`
to your own filter list and try again.

`visioncloud.info##script:inject(setTimeout-defuser.js, .modal();, 2000)`
should show up in your logger output.

**Comment by Rapperk** [comment]
I forced an update of all filters today, like 4 or 5 times lol
I added the filter, like this:
<img width="962" alt="myfilters" src="https://user-images.githubusercontent.com/42440290/44229130-015bf880-a18f-11e8-819c-80ff965e6fe5.png">

Then used the logger:
<img width="962" alt="log3" src="https://user-images.githubusercontent.com/42440290/44229147-0d47ba80-a18f-11e8-9c15-e78940dd0795.png">

Something must be wrong i guess...(and yes, pop-up still here)

**Comment by okiehsch** [comment]
That is weird. The popup will be there until the setTimeout-filter shows up in your logger
Add
`visioncloud.info##script:inject(setTimeout-defuser.js)` to your filters
Note that this will break site functionality it is only to test if the filter shows up in your logger.

**Comment by mapx-** [comment]
@Rapperk  what FF version are you using ?

**Comment by Rapperk** [comment]
Well, without it, im automatically reditected to `https://visioncloud.info/home/adblock`
here is the log:
<img width="962" alt="log2" src="https://user-images.githubusercontent.com/42440290/44230245-885ea000-a192-11e8-92ad-ec644f83fcfc.png">

**Comment by okiehsch** [comment]
I am not redirected and I don't see the "advertsing.js" request, do you have to be logged in?
Anyway instead of the "green thing"
Add
`@@||visioncloud.info^$script,first-party`
to your filter list, then try again.

**Comment by Rapperk** [comment]
wait, i sent that screenshot before you edit your comment, here is the updated one:
I removed the `visioncloud.info##script:inject(setTimeout-defuser.js)` and tested it, the pop-up doesnt appear anymore.

<img width="962" alt="sem titulo" src="https://user-images.githubusercontent.com/42440290/44230741-e770e480-a193-11e8-866e-070d332659ee.png">

Since i started to use that website, everytime i had to use the "green thing" (sorry dont know the name lol) otherwhise i would be ALWAYS be redirected (maybe i had a old filter on my filters), but its working now (i also removed the `visioncloud.info##+js(setTimeout-defuser.js, .modal();, 2000)` from my filter list and its working...thanks so much :)

**Comment by okiehsch** [comment]
Remember, if you have added a first-party allow rule - the green thing - to other sites, you will have the same issue, i.e. all script:inject filters for that site will be disabled.
