### ISSUE TITLE
broadbandforum.co - Anti Adb 

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#324]
Anti adb warning is displayed on `https://broadbandforum.co`. 

**SS:** http://i.imgur.com/ViD54kp.png
**Error URL:** `https://broadbandforum.co/forums/263/`

The anti adblock warning is loaded due to `https://broadbandforum.co/js/rellect/AdblockDetector/handler.min.js?rev=33` but blocking this does not help as they apparently have a workaround for that (http://i.imgur.com/6fHjw9P.png) which can be seen in the console.

Please help me with this issue.

_**Note:** Using uBO 1.11.4 on Chrome 57 with default filters._

**Comment by mapx-** [comment]
add
```
broadbandforum.co###exposeMask
broadbandforum.co##.errorOverlay
```

**Comment by gotitbro** [comment]
@mapx- The filters above cause problems and many features which have overlay do not work, relevant discussion: `https://forum.adguard.com/index.php?threads/broadbandforum-co-windows.20240/ `

Some other solution needs to be found.

**Comment by okiehsch** [comment]
Does
|`|broadbandforum.co/js/rellect/AdblockDetector/handler.min.js$script,important,redirect=noopjs,domain=broadbandforum.co`
work for you?

**Comment by gotitbro** [comment]
@okiehsch That works, I do not get the anti adb warning after adding the filter above.

**Comment by mapx-** [comment]
classic filters:
http://forums.lanik.us/viewtopic.php?p=115005&sid=47eddf8fbe81dd526408f94ab614e96a#p115005
