### ISSUE TITLE
http://tv.r7.com/

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#3240]
testing 
`http://tv.r7.com/record-tv/videos/assista-a-integra-da-entrevista-com-jair-bolsonaro-em-o-voto-na-record-2018-15082018`

`tv.r7.com##script:inject(antiAdBlock.js)
`
looks works

alternative 
`tv.r7.com/record-tv/videos##script:inject(antiAdBlock.js)`

**Comment by xqk94524** [comment]
![image](https://user-images.githubusercontent.com/34273204/44156809-daa3821e-a07e-11e8-87d6-5ed089cffbda.png)
without the rule

**Comment by okiehsch** [comment]
I can't reproduce, video plays without issue on my end.

**Comment by xqk94524** [comment]
I get that after some plays

**Comment by xqk94524** [comment]
for the first time is okay, but some plays before, it get block

**Comment by ZaphodBeebblebrox** [comment]
I can reproduce on alternating loads.

**Comment by blockthis** [comment]
@mapx- please remove this (because it has an unnecessary `$generichide`). 

The appropriate rules have been added to the AdGuard Portuguese list: https://github.com/AdguardTeam/AdguardFilters/commit/03488323ec7d0c4e296a25137249e09086390558
