### ISSUE TITLE
https://www.hackintoshzone.com/

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uAssets#3241]
`https://www.hackintoshzone.com/files/file/1044-hackintosh-high-sierra/?do=download&confirm=1`

`www.hackintoshzone.com##.onp-sl-flat-theme.onp-sl-transparence-mode.onp-sl-overlap-box`

**Comment by xqk94524** [comment]
![image](https://user-images.githubusercontent.com/34273204/44158397-902f1f00-a082-11e8-981b-db93cb5c88fd.png)

**Comment by mapx-** [comment]
see if works
`hackintoshzone.com###ipsLayout_mainArea`

**Comment by xqk94524** [comment]
I noted this script 
`https://www.hackintoshzone.com/ips_4/block/lock.js`
blocking this, make the things works fine



using
win10 64bits 1803
firefox 31

**Comment by xqk94524** [comment]
`||www.hackintoshzone.com/ips_4/block/lock.js$script,domain=www.hackintoshzone.com`

**Comment by mapx-** [comment]
seems working too ?

```
hackintoshzone.com##.onp-sl-outer-wrap
hackintoshzone.com##.onp-sl-timer-label
hackintoshzone.com##.onp-sl-flat-theme
```

**Comment by okiehsch** [comment]
That works too and is probably preferable to my fix, so you can remove my filter and add yours.
