### ISSUE TITLE
dospelis.com [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3244]
URL(s) where the issue occurs

`https://www.dospelis.com/movies/no-game-no-life-zero/`

Describe the issue

Fake Button

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.14

Settings

Default

**Comment by mapx-** [comment]
You wanna say the first player is a fake one ?

**Comment by KiLL4FuNK** [comment]
if the first one is false

**Comment by mapx-** [comment]
does this work ?
`dospelis.com###frame-holder`

**Comment by mapx-** [comment]
IT should be added to easylist @ryanbr @Khrin

**Comment by smed79** [comment]
@diaux

**Comment by KiLL4FuNK** [comment]
Mining

`https://www.dospelis.com/movies/no-game-no-life-zero/

`

**Comment by ZaphodBeebblebrox** [comment]
@okiehsch because I'm not confident with dealing with mining, `flashx.co##+js(abort-on-property-read.js, Uint8Array)`?

**Comment by okiehsch** [comment]
`*$csp=worker-src 'none',domain=flashx.co` should work, so you can add `flashx.co` to
https://github.com/uBlockOrigin/uAssets/blob/e014c04eab39d935e60f3e94ef06fd2ee62ffa2a/filters/resource-abuse.txt#L335

I also get a popup that can be fixed by 
`cloudvideo.tv##+js(abort-on-property-write.js, Fingerprint2)`

**Comment by angelfortine** [comment]
Muy buenas todas aunque recomiendo para ver peliculas online http://www.casapelis.net/

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by maria123612** [comment]
Gracias por la idea bastante buena para ver peliculas online
https://gnula.in/
https://www.pelis24hd.net/
