### ISSUE TITLE
Reddit upload doesn't work with Reddit recipe

### ISSUE THREAD

**Issue by theel0ja** [uBlockOrigin/uAssets#3246]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`https://www.reddit.com/r/apple/submit`

### Describe the issue
upload doesn't work

### Screenshot(s)
<img width="733" alt="screen shot 2018-08-16 at 21 30 32" src="https://user-images.githubusercontent.com/5832930/44227563-a11f8380-a19b-11e8-8851-b301ad3f6ed2.png">
<img width="560" alt="screen shot 2018-08-16 at 21 30 46" src="https://user-images.githubusercontent.com/5832930/44227589-abda1880-a19b-11e8-988d-38095d29af23.png">

### Versions

- Browser/version: Firefox 61.0.2
- uBlock Origin version: uMatrix 1.3.12

### Settings

See screenshots.

### Notes

Using Reddit recipe

**Comment by ZaphodBeebblebrox** [comment]
Adding `_ reddit-uploaded-media.s3-accelerate.amazonaws.com xhr` to the recipe should fix it. @gorhill

**Comment by theel0ja** [comment]
Made PR. #3247

**Comment by gorhill** [comment]
Sorry, it was already changed by the time I saw your comment above.
