### ISSUE TITLE
[NSFW] Pornhub thumbnails missing in Vivaldi Browser

### ISSUE THREAD

**Issue by zororo1** [uBlockOrigin/uAssets#3253]
### URL(s) where the issue occurs

`https://www.pornhub.com/view_video.php?viewkey=ph5b623e6371958`

### Describe the issue

Most of the thumbnails are missing, though not all. When viewing a video, only the first 2 recommended video thumbnails are shown, when searching for videos about 1/3 of the thumbnails are shown. Disabling EasyList filters brings back the thumbnail placeholders, the thumbnails themselves still don't load. Disabling both uBlock filters and EasyList brings back ads and the thumbnails.

I tested on Chrome and it works fine there (there is a slight delay in loading the same thumbnails that are missing in Vivaldi).

### Versions

- Browser/version: Vivaldi 1.15.1147.64 (Stable channel) (64-bit)
- uBlock Origin version: 1.16.16

**Comment by mapx-** [comment]
You should see on your side - vivaldi - what filters are triggered on that page - see in your logger

**Comment by jspenguin2017** [comment]
Also reproduced on Chrome. 
```
pornhub.com#@#[src*="base64"]
pornhub.com#@#[src*="data:"]
```

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?p=139748#p139748

**Comment by uBlock-user** [comment]
Can't reproduce on Chromium, all thumbnails are loading.
