### ISSUE TITLE
[Anti-Adblock] schoener-wohnen.de

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#3254]
### URL(s) where the issue occurs

`https://www.schoener-wohnen.de/architektur/27541-rtkl-bauen-bungalows-alle-vor-und-nachteile-die-ein-bungalow-mitbringt`

### Describe the issue

When you visit it the site it redirects you to an error page telling you something went wrong and it has detected an adblocker.

### Screenshot(s)

![a](https://user-images.githubusercontent.com/14368203/44277502-6a4c7a80-a23a-11e8-8517-094838875e66.jpg)

### Versions

- Browser/version: FF 61.0.2
- uBlock Origin version: 1.16.16

### Settings

- Disable prefetching
- Disable hyperlink scan
- Disable IP leak via WebRTC
- Block CSP
- EasyList Germany
- Fanboys Cookie/Social/ThirdParty/Annoyance

### Notes

Honestly I have no idea how to research into this. Therefore I cannot provide any technical useful information regarding the blocking mechanism.

**Comment by huyszn** [comment]
`https://www.schoener-wohnen.de/einrichten/raeume-tipps-zur-planung-und-einrichtung/wandgestaltung-im-jugendzimmer-13596356.html`

After waiting a few seconds, a lot of ads appear on this site like above the article, ad banners to the side, and ads below the article (I have EasyList Germany list enabled).

https://github.com/uBlockOrigin/uAssets/assets/46979193/d4b36127-d986-4532-b046-de71545fdd14

https://github.com/uBlockOrigin/uAssets/assets/46979193/9d19013c-0fc0-43f4-98d2-97e04617bf3f
