### ISSUE TITLE
[Anti-adblock] playpuls.pl

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3256]
### URL(s) where the issue occurs

`http://playpuls.pl/seriale/lombard-zycie-pod-zastaw`

### Describe the issue

I got a report about anti-adblock on this website, I can't read the issues template for Polish filters. 
Who should I ping or it will be fixed in uAssets? 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/44293863-ae487b00-a24c-11e8-812d-3a617ccd3d20.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.16.16

### Settings

English default. Tried Polish filters, no change.

**Comment by okiehsch** [comment]
The polish filter list uses extended syntax and fixes anti-adblock issues, so polish sites should be fixed in the regional list.
@MajkiIT
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=playpuls.pl`
fixes the issue on my end.

**Comment by jspenguin2017** [comment]
I can't read their issues template.

**Comment by okiehsch** [comment]
````
<!--
Thank you for applying to the Polish filters in Adblock and UBlock.
Before taking any action, it is essential that you read CONTRIBUTING.md
-->
### Screenshot
<!--
Drag and drop your screenshot here or link to it.
-->

#### Direct link
<!--
Insert a direct link here to the page where the advertisement or error occurs.
-->

What do I need to do to make an item, advertisement, or error appear?
1. 
2. 
3. 


### My configuration
Internet Browser:**

Extensions and scripts:**

**Filters:**
Polish filters for Adblock and UBlock
2. 
3. 
4. 

Other information that may be relevant (optional):**
````

**Comment by okiehsch** [comment]
You can also simply open your issue here and we ping the polish maintainer.

**Comment by MajkiIT** [comment]
@okiehsch Thanks
