### ISSUE TITLE
pornhub.com - uBlock blocking filter _adds_ trafficjunky

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uAssets#326]
### URL(s) where the issue occurs

(NSFW) [pornhub.com](http://pornhub.com/) main page.

### Describe the issue

**uBlock filters** are affected:
> ||trafficjunky.net^$important,third-party

This filter actually _adds_ a trafficjunky element. This video link in the frame in the screenshot goes to  [iknowthatgirl.com](http://www.iknowthatgirl.com/tour5/?ats=eyJhIjo3NywiYyI6NDU0NzM3MzYsIm4iOjE1LCJzIjoxODEsImUiOjU5MiwicCI6NH0=&ad1=dollar_tits:32&ad2=mpg_384x320_carolina:1&ad3=iktg_1dollar:31&ad4=mpg_piperhope:26&ad5=squirt4_v2:4&AB=1&aclid=VrkuMm0kQouZNQ0rnPmsM0j5Skubkqf0R8Op8G2gQ53hY_HJPQRp79mNW_mCf5_rFcYX7b-diSnYQHiYtUTv0rDv9wai7251GTzP8MAkZ0gXILg2FqAoY6zu5P2lMeLsS5g9DMuFXJX0et7niac46bnbTl8_nOWbm6ILAmKoV3rlAjPvc4G-HlxOnex1F1hNCEjH-z73alGMuGvuVAIR7EPpDAnMJ8l853y-WgZkENyVlQiv8BMdXQQlZcBwAmE-).

I don't see this element in Firefox with all add-ons disabled in safe-mode.

### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/25944158/24119220/b866aaa8-0db0-11e7-9906-1b5d148b1bba.png)

### Versions

- Browser/version: Firefox 52
- uBlock Origin version: 1.11.4

**Comment by gorhill** [comment]
The logger shows that 3rd parties are blocked, except for `phncdn.com`.

Of course uBO does not literally "add trafficjunky element", the page is doing something that causes that element to appear -- not uncommon with sites which try to work around blockers.

There is a data: URI-based video in there, which is itself properly hidden by an EasyList rule. There is no rule in EasyList however for the container element of that video element -- this is what you see.

How about this filter:

    pornhub.com##div video[id]:first-child > source[src^="data:"]:xpath(../../..)

**Comment by stanlane** [comment]
@gorhill That did it!

**Comment by gorhill** [comment]
Maybe someone else will have a better idea to address this case with a classic filter, will wait a bit before adding it to uBlock filters.

**Comment by stanlane** [comment]
@gorhill Ok, thank you for helping me.
