### ISSUE TITLE
BlockAdblock

### ISSUE THREAD

**Issue by cup** [uBlockOrigin/uAssets#3263]
For some reason every single issue at http://github.com/gorhill/uBlock and here
is getting closed and locked without a solution.

I can understand gorhill/uBlock, but my understanding was this repo is
specifically for filter lists, so this action makes no sense unless uBlock has
an agenda to allow BlockAdblock.

Further my comments with a solution are being deleted without explanation, this
is disturbing. Here is the solution for any wanting to stop BlockAdblock. Note
I have no stake in Adguard - its one of the built-in lists that you can choose
with uBlock, but its not selected by default - its the first one i found that
resolves the problem with BlockAdblock. I someone has a better suggestion I am
open to it.

1. Dashboard
2. Filter lists
3. Ads
4. Adguard Base Filters​

**Comment by ZaphodBeebblebrox** [comment]
Your issues have been closed because we do not fix example sites.

**Comment by cup** [comment]
@ZaphodBeebblebrox what do you mean example sites? blockadblock is used with many sites such as

- http://watchhouseonline.net
- http://blockadblock.com

**Comment by jspenguin2017** [comment]
`watchhouseonline.net` needs to be fixed. `blockadblock.com` won't be fixed because it is an example site, which I think is a bad idea but it's up to gorhill. 

```
watchhouseonline.net##+js(bab-defuser.js)
blockadblock.com##+js(bab-defuser.js)
```

**Comment by jspenguin2017** [comment]
Adguard base filter fixes it case by case too. 

`bab-defuser.js` should not be applied globally, even if it's possible, because it will cause breakage.
