### ISSUE TITLE
yify-movies.net

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#3264]
yify-movies.net

Hi, when you go to yify-movies.net for the first time and click in the search bar, it opens a new window with advertising then closes it. Is there a way to fix it so that it doesn't open the new window? Thanks.

Waterfox 56.2.2 (64-bit)
uBlock Origin 1.16.16

**Comment by uBlock-user** [comment]
Can't reproduce.

Try `||amazonaws.com^$domain=yify-movies.net`

**Comment by IoanPaleru** [comment]
Yes, that filter seems to work. Thanks.
