### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by 0lsn** [uBlockOrigin/uAssets#3267]
### URL(s) where the issue occurs

https://derstandard.at

### Describe the issue

Works for a couple of minutes / Pages but you will get a warning for a subsription or to disable the your adblocker. blocking cookies doesnt work. 

### Screenshot(s)

https://imgur.com/a/rZIkcuN

### Versions

- Browser/version: Chrome neweset version
- uBlock Origin version: nano defender / nano adblocker (newest) 20.08.2018

### Settings

- none

### Notes

ublock has the same problem. nano defender doesnt work. No specific url since every url will get this message. only deleting the cookies will resolve the issuses temporarily.

**Comment by mapx-** [comment]
see
https://github.com/uBlockOrigin/uAssets/issues/2632

**Comment by 0lsn** [comment]
thank you
