### ISSUE TITLE
Deviantart - Invisible Div

### ISSUE THREAD

**Issue by AlexQuiniou** [uBlockOrigin/uAssets#3275]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.deviantart.com/notifications/`

### Describe the issue

There is invisible div block that prevent clic things under it

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/34091990/44396870-80aa4d00-a53e-11e8-8898-8e2d94608aaf.PNG)

### Versions

- Browser/version: Firefox/61.0.2
- uBlock Origin version: 1.16.16

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

Maybe we can block this class

- mc-ad-chrome
- atf-top-728x90

**Comment by mapx-** [comment]
it seems working (to be added to easylist or to your custom filters)

`deviantart.com##.mc-ad-chrome`

@ryanbr
