### ISSUE TITLE
whostreams.net (Redirects and Anti-Adblock / AdBlock Bypass)

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#3276]
### URL(s) where the issue occurs

```
http://whostreams.net/embed/ihpa088
```

### Describe the issue

Head Script tag causes redirect to homepage. There are allot of popups and missed ads and they try to hide the entire page.

### Versions

- Browser/version: Firefox Quantum Latest.
- uBlock Origin version: Latest.

### Settings

Default.

### Notes

My Fixes so far (Still displays ads because needs more work).

```
! 20/08/2018, 19:15:53 http://whostreams.net/embed/ihpa088
whostreams.net##.stream-offline.tb
whostreams.net##script:contains(document.location)
whostreams.net##script:contains(PopAds)
$script,subdocument,third-party,domain=whostreams.net
```

**Comment by mapx-** [comment]
Are you sure is directly visible that embed stream ? or do you get that link from other page / site ?
(even disabling uBo I'm redirected to the home page)

**Comment by C0nw0nk** [comment]
@mapx- 

Put the code what i provided into your user-filters above and you will find you can directly view and access it.

It is this code in the webpages head tag that causes redirects the filter above should stop that annoyance.

```
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta name="viewport" content="width=device-width; initial-scale=1.0">
<script>if(window==window.top) document.location="/"</script>
```

**Comment by C0nw0nk** [comment]
With the user-filter i provided above i think it should stop the redirects and ads but would be good for a filter list maintainer to confirm it and add it.

**Comment by mapx-** [comment]
`script:contains`  are working only in firefox (are converted in HTML filtering filters).

**Comment by C0nw0nk** [comment]
@mapx- 

What would a more universal soloution be then ?

**Comment by mapx-** [comment]
What's the real issue ? anti adblocking ? popups ? (because this kind of redirecting just tells us the site is only providing services to third party sites)

If you could provide a page using such embeded whostreams streams would be useful

**Comment by C0nw0nk** [comment]
It was the fact they redirect you for directly accessing the page with javascript and the amount of ads but this filter cleaned up the ads.

```
$script,subdocument,third-party,domain=whostreams.net
```

It is better to directly access that url than to use sites that embed it because here as an example the sites that embed it are displaying allot of ads too.
```
http://elixx.me/arsenal.html
```

**Comment by C0nw0nk** [comment]
Why don't you want to block the redirects ?

**Comment by mapx-** [comment]
Oh, I did not say that ... for FF is ok using html filtering, in chrome I get no fix (probably race condition).
Let's see others if they can find something else for all browsers

For elixx try (I get only popups, no anti adb stuff):
`elixx.me##+js(abort-on-property-write.js, decodeURIComponent)`

**Comment by C0nw0nk** [comment]
I am only using the direct url not that elixx website anymore same as others most likely do with sites of this nature (openload.co) being a prime example direct access.

**Comment by mapx-** [comment]
However, in firefox I need only these 2 filters

```
whostreams.net##^script:has-text(document.location)
whostreams.net##.stream-offline.tb
```

I get no popup or anti adb stuff

**Comment by uBlock-user** [comment]
That redirect was put to disallow users from opening the link on video host's webpage FYI, it's not an anti adblock measure, the video host wants to users to access that link only in embedded form, that's just their policy.

**Comment by okiehsch** [comment]
Not possible to fix the redirect using Chrome with `uBO-filters` and I agree that this is not an `anti-adblock` issue, you will get redirected even if you do not use one.

I do get another popup using Firefox at `http://whostreams.net/embed/ihpa088`, adding
`whostreams.net##+js(abort-on-property-write.js, _pop)`
works on my end.
