### ISSUE TITLE
Last.fm Anti-Adblock

### ISSUE THREAD

**Issue by F0kT** [uBlockOrigin/uAssets#3277]
### URL(s) where the issue occurs

`https://www.last.fm/`

### Describe the issue

An annoying Anti-adblock note at the top of every page on the website.

### Screenshot(s)

![untitled](https://user-images.githubusercontent.com/42579770/44408785-58801580-a561-11e8-929c-96ad4d2c7896.png)

### Versions

- Browser/version: Firefox 61.0.2
- uBlock Origin version: v1.16.16

### Notes

I hope this is the right place for this request.

**Comment by mapx-** [comment]
I get no such message.

**Comment by okiehsch** [comment]
I can't reproduce, no such message with Chrome or Firefox on my end.

**Comment by F0kT** [comment]
How is it that only I see it, then?

![untitled](https://user-images.githubusercontent.com/42579770/44486657-809c7100-a654-11e8-8035-7488950653da.png)

**Comment by mapx-** [comment]
Did you test using the default setup in uBo ? (and disabling all other extensions)

**Comment by F0kT** [comment]
@mapx- I didn't add that I also have NoScript and a bunch of other filters than the default ones checked in uBlock. Blocking all scripts with NoScript seems to remove the note. The note resurged recently so I thought they updated the site or something. Guess it's only me.

**Comment by mapx-** [comment]
Well, something on your side (I guess NoScript) interferes with uBo, so ..it's your call on what to do (blocking all scripts it's not a solution)

**Comment by F0kT** [comment]
@mapx- Blocking inline scripts in uBlock also works. Is that more reasonable?

**Comment by mapx-** [comment]
You need nothing in uBo, so you should whitelist the site in NoScript and let uBo take care of all.
If still does not work narrow down (eventually) what's the "wrong" list.
