### ISSUE TITLE
NYTimes.com bottom "Subscribe" button

### ISSUE THREAD

**Issue by prech** [uBlockOrigin/uAssets#3278]
### URL(s) where the issue occurs

https://www.nytimes.com/2018/08/20/world/asia/china-malaysia.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=first-column-region&region=top-news&WT.nav=top-news

https://www.nytimes.com/2018/08/21/smarter-living/work-desk-improvements-office.html?fb=1&recb=home-living.control&recid=196zbk0QbcLYMPxmR6i5IGWYQlh&contentCollection=smarter-living&mData=articles%255B%255D%3Dhttps%253A%252F%252Fwww.nytimes.com%252F2018%252F08%252F21%252Fsmarter-living%252Fwork-desk-improvements-office.html%253Ffb%253D1%2526recb%253Dhome-living.control%2526recid%253D196zbk0QbcLYMPxmR6i5IGWYQlh%26articles%255B%255D%3Dhttps%253A%252F%252Fwww.nytimes.com%252F2018%252F08%252F08%252Fstyle%252Fgifts-for-hosts-summer-home.html%253Ffb%253D1%2526recb%253Dhome-living.control%2526recid%253D196zbk0QbcLYMPxmR6i5IGWYQlh&hp&action=click&pgtype=Homepage&clickSource=story-heading&module=smarterLiving-promo-region&region=smarterLiving-promo-region&WT.nav=smarterLiving-promo-region

### Describe the issue

Bottom "Subscribe" bar 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/8314103/44411408-4c716500-a51b-11e8-9df7-17c5d1b2bb61.png)

### Notes

The CSS selector seems to dynamically change every page load. I've been playing with "has-text" for the (Subscribe) or (Advertisement), but the selector keeps changing every load

![image](https://user-images.githubusercontent.com/8314103/44411570-ab36de80-a51b-11e8-89fe-f357f26e95a4.png)

Any ideas appreciated

**Comment by uBlock-user** [comment]
Add `nytimes.com##.shown:has-text(Subscribe)`

**Comment by mapx-** [comment]
Probably the real "issue" is the paywall, even hiding "subscribe now" you'll get an incomplete article ?!

**Comment by uBlock-user** [comment]
The filter only removes the black bar highlighted in red rectangle.

**Comment by prech** [comment]
Thank you, that did the trick!

Might it be incorporated into the uBlock filter set?

**Comment by uBlock-user** [comment]
Sure, if mapx sees fit.

**Comment by mapx-** [comment]
@prech  for me it's not even an annoyance, it's related to the paywall issue, so ... just keep it as custom filter

**Comment by uBlock-user** [comment]
I don't get any paywalls and articles aren't hidden either, I browsed 8 of them, consecutively.

**Comment by mapx-** [comment]
I get (in the middle of an article)

![image](https://user-images.githubusercontent.com/10303732/44414156-5de35d00-a56d-11e8-85ae-fc79151c0549.png)

**Comment by mapx-** [comment]
@okiehsch What's your opinion ?

**Comment by prech** [comment]
I use element picker to block that "Subscribe to the Times", but would gladly see it incorporated in the filter set

**Comment by uBlock-user** [comment]
Yeah, saw that, it can be patched cosmetically too, it's not hijacking anything.

Filter - `nytimes.com##.InlineMessage-inline--2ysnq`

**Comment by yourduskquibbles** [comment]
FYI @prech - Both of these annoyances (and a bunch more related to nytimes.com) are fixed in [Web Annoyances Ultralist](https://github.com/yourduskquibbles/webannoyances).

**Comment by okiehsch** [comment]
@mapx- it's up to you, I would not add a filter but if you think this is an annoyance that should be fixed I will not argue the point :)

**Comment by mapx-** [comment]
As I said, for me it's some mixed stuff, eventually @ryanbr  could add it to fanboy's annoyances

**Comment by KiLL4FuNK** [comment]
`https://www.nytimes.com/2018/09/11/opinion/contrarian-college-stjohns.html`

anti adblock
