### ISSUE TITLE
deezer.com - page is squished

### ISSUE THREAD

**Issue by negrihlava** [uBlockOrigin/uAssets#3284]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.deezer.com/en`

### Describe the issue

[When using uBlock Origin the page gets squished in half (almost like a mobile version of the page or when resizing the browser window.)]

### Screenshot(s)

![image](https://user-images.githubusercontent.com/42617584/44477931-69518980-a63c-11e8-90c2-5989ea77687c.png)

### Versions

- Browser/version: Opera 55.0.2994.37
- uBlock Origin version: uBlock Origin 1.16.14

### Settings

- using default settings
- filters:
uBlock filters
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list​
CZE, SVK: EasyList Czech and Slovak

### Notes

![image](https://user-images.githubusercontent.com/42617584/44477991-91d98380-a63c-11e8-9e92-673322c05f1d.png)

Somewhat "fixed" by using
`@@||ak-ns.sascdn.com^$script,domain=www.deezer.com
@@||ww400.smartadserver.com/ac$script,domain=www.deezer.com`
however when refreshing the page it's still squished, only when switching pages it widens to the whole window. Example of latter behavior: `https://gfycat.com/AgileComfortableIbadanmalimbe`

**Comment by negrihlava** [comment]
![image](https://user-images.githubusercontent.com/42617584/44480718-3dd29d00-a644-11e8-8374-8c7f4e02772a.png)
Now there is a weird box below where the advertisement was present.
When using private mode, this issue disappears but again there's the problem with it not widening after refresh.

**Comment by mapx-** [comment]
Do you still see the box if you add
deezer.com##.ads ?

Otherwise do the filters above work for you ?

**Comment by okiehsch** [comment]
No problem on my end.

![image](https://user-images.githubusercontent.com/16838044/44481272-ab32fd80-a645-11e8-9eae-081de782935d.png)

**Comment by negrihlava** [comment]
@mapx- 
it seems like there is an unfortunate side effect right now that I haven't noticed yesterday.
when you're switching songs in the playlist by using the play buttons next to the song names, it can get stuck - meaning, the title, cover and everything gets updated but it's still playing the song originally played before the switch. `https://gfycat.com/ClumsyTinyFluke`
