### ISSUE TITLE
viamichelin.fr does not work properly

### ISSUE THREAD

**Issue by soheirb** [uBlockOrigin/uAssets#3287]
### URL(s) where the issue occurs

`https://www.viamichelin.fr`

### Describe the issue

Hi,
I've noted that viamichelin.fr buttons does not work properly. The buttons that let you choose your itinerary options or the ones on the map are broken. The website is not usable except for browsing maps.

### Versions

- Browser/version: Firefox/61.0.2
- uBlock Origin version: 1.16.16

### Settings

I think I kept uBO's default settings, but here is my list anyway:
- All uBlocks filters
- EasyList
- EasyPrivacy
- Malware Domain List
- Malware domains
- Peter Lowe’s Ad and tracking server list
- FRA: EasyList Liste FR

### Notes

Will add as I investigate

**Comment by mapx-** [comment]
try updating unbreak list could be this mistake in easylist:
https://github.com/easylist/easylist/commit/41eb1d2456a7f23fd8331ff9962f20686c4fa0bf

**Comment by okiehsch** [comment]
The issue is the filter
`viamichelin.*##script:inject(addEventListener-defuser.js, click, undefined)`
in uBO-filters, which disables nearly all clicking functionality and has to be removed.

**Comment by soheirb** [comment]
After updating, everything works again. Thanks a lot for your help.
