### ISSUE TITLE
fulltelevisionhd.li [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3289]
URL(s) where the issue occurs

`http://www.fulltelevisionhd.li/bein-sports-en-vivo-por-internet/`

Describe the issue

Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.16

Settings

Default

**Comment by KiLL4FuNK** [comment]
play video  Pop-up

**Comment by okiehsch** [comment]
Best I can come up with without breaking fullscreen functionality.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://www.fulltelevisionhd.li/tnt-en-vivo-por-internet/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock ?

`http://www.fulltelevisionhd.li/tnt-en-vivo-por-internet/`
`http://www.fulltelevisionhd.li/disney-channel-en-vivo-por-internet/`
`http://www.fulltelevisionhd.li/tlnovelas-en-vivo-por-internet/`
`http://www.fulltelevisionhd.li/fox-en-vivo-por-internet/`
`http://www.fulltelevisionhd.li/cinecanal-en-vivo-por-internet/`
`http://www.fulltelevisionhd.li/discovery-channel-en-vivo-por-internet/`
`http://www.fulltelevisionhd.li/cinemax-en-vivo-por-internet/`

**Comment by KiLL4FuNK** [comment]
Pop-up play video  `http://www.fulltelevisionhd.li/disney-channel-en-vivo-por-internet/`


Pop-up `http://www.fulltelevisionhd.ru/espn-2-en-vivo-por-internet/`
