### ISSUE TITLE
WebRTC circumvention - yad2.co.il

### ISSUE THREAD

**Issue by DanIbba** [uBlockOrigin/uAssets#329]
### URL(s) where the issue occurs

http://www.yad2.co.il/
http://www.yad2.co.il/Nadlan/sales.php

### Describe the issue

**WebRTC circumvention**
Full of webRTC HTML5 crap ads. It seems like they find a way to bypass the uBlock Origin WebRTC blocking ads.   

### Screenshot(s)

<img width="1280" alt="screen shot 2017-03-24 at 23 06 10" src="https://cloud.githubusercontent.com/assets/24211092/24311864/1481f840-10e7-11e7-9013-5a700d419e79.png">

### Versions

- Browser/version: Chrome
- uBlock Origin version: 1.11.4

### Settings

default settings + ISR: EasyList Hebrew

### Notes

I think this is made by a company called Uponit. please see my webRTC investigation below:
<img width="1280" alt="screen shot 2017-03-24 at 23 12 41" src="https://cloud.githubusercontent.com/assets/24211092/24311963/81f0df5e-10e7-11e7-91c9-7436099ad48f.png">

**Comment by okiehsch** [comment]
Does
`||yad2.co.il/js-new/showAds.js$script,redirect=silent-noeval.js,domain=yad2.co.il`
work for you?

**Comment by DanIbba** [comment]
No. This is a new WebRTC circumvention technique. 
@gorhill - I think this is require some development in your end.

**Comment by gorhill** [comment]
I am not getting the WebRTC stuff if I disable EasyList Hebrew.

**Comment by gorhill** [comment]
Ok so if one blocks WebSocket, they fall back onto WebRTC.

**Comment by DanIbba** [comment]
do you think it is a new WebRTC circumvention technique? or just a collision between filters?

**Comment by gorhill** [comment]
If I add `yad2.co.il` to uBO-Extra, seems to solve the issue.

**Comment by gorhill** [comment]
In the coming weeks I will investigate adding inline script tag filtering to uBO itself, but for now uBO-Extra is the solution. Are you willing to use it?

**Comment by DanIbba** [comment]
Just read about the uBO extra, is it like a dev version of ubo?

**Comment by okiehsch** [comment]
@gorhill Is there a reason why 
`||yad2.co.il/js-new/showAds.js$script,redirect=silent-noeval.js,domain=yad2.co.il`
doesn't work on your end because it works on mine, the ads are gone and it is the same issue as
`https://github.com/uBlockOrigin/uAssets/issues/305#issuecomment-284366800

**Comment by gorhill** [comment]
I didn't try since OP said it was not working on his side. I will try now.

**Comment by gorhill** [comment]
Ok, it works on my side. So let's use this as the solution, and OP will have to figure why it does not work on his side.

**Comment by DanIbba** [comment]
Thanks! 
Just if you have an answer to my Q it will be great, do you think it is a new WebRTC circumvention technique?

**Comment by okiehsch** [comment]
It is fairly "new",  read https://github.com/uBlockOrigin/uAssets/issues/251#issuecomment-276739811
@gorhill is it sufficient if the redirect is added to `EasyList Hebrew` or should I add it to the
`uBlock Filter` list?

**Comment by gorhill** [comment]
Does EasyList Hebrew mind using uBO-specific syntax? If not then sure it should go in there. That would be a surprise though as this would make the list unusable with ABP I believe.

@DanIbba you do no need using uBO-Extra, read _carefully_ what has been posted here. Also, there is no guarantee all of uBO will work properly if you use other content blockers at the same time. This is why the solution here did not work for you -- and anyways you gain absolutely nothing to use other blockers on top of uBO, just a whole lot of mem/cpu overhead while preventing uBO to work properly.

**Comment by okiehsch** [comment]
`||ad.doubleclick.net/favicon.ico?ad=$image,important,redirect=2x2-transparent.png,domain=walla.co.il`
`||pagead2.googlesyndication.com/pagead/js$script,important,redirect=noopjs,domain=walla.co.il`
are part of EasyList Hebrew so they don't mind apparently.

**Comment by gorhill** [comment]
I was assuming this would cause issues with ABP, but now I see ABP bails out when it finds an option it can't understand. This is nice, since this opens the door for filter list maintainers to use uBO-specific syntax, at least for static network filtering.

**Comment by gorhill** [comment]
@DanIbba can you ask EasyList Hebrew to use the solution here, and close when done? Thanks.

Solution:

    ||yad2.co.il/js-new/showAds.js$script,redirect=silent-noeval.js,domain=yad2.co.il

**Comment by uBlock-user** [comment]
Try - `yad2.co.il##script:inject(abort-on-property-write.js, window.btoa)`

Works fine on my end, no WebRTC connection.

**Comment by gorhill** [comment]
`window.btoa` is a basic utility function, it should not be touched. The best advice is to actually just use the filter proposed above.

**Comment by uBlock-user** [comment]
Not if it's being pro-actively abused like this, in that case we should use it as long as it's not breaking anything.

**Comment by gorhill** [comment]
Not much activity at EasyList Hebrew lately, so I added the filter to uBO's filter. Will remove once it's in EH.

**Comment by DanIbba** [comment]
@gorhill @okiehsch 
Same problem at walla.co.il - Please add the ubo Extra code to the regular ubo.
