### ISSUE TITLE
deezer.com - switching songs gets stuck

### ISSUE THREAD

**Issue by negrihlava** [uBlockOrigin/uAssets#3290]
### URL(s) where the issue occurs

`https://www.deezer.com/en`

### Describe the issue

After fixing the squished page issue yesterday #3284 , it seems like after Deezer tries to play an ad the song switching can get stuck and you're not actually able to change any song. It will update the title and information but it's still playing the song you played originally. If you wait until it's over it will simply not play anything anymore.

### Screenshot(s)

`https://gfycat.com/ClumsyTinyFluke`

### Versions

- Browser/version: Opera 55.0.2994.37
- uBlock Origin version: uBlock Origin 1.16.14

### Settings

- using default settings
- filters:
uBlock filters
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list​
CZE, SVK: EasyList Czech and Slovak

**Comment by mapx-** [comment]
test this filter
`@@||sascdn.com^$script,domain=deezer.com`

**Comment by okiehsch** [comment]
Why allow all of these requests in `uBO-unbreak`, as far as I can see the filters are fixing an annoyance, there are no ads and the site works fine if I disable `uBO-unbreak`.
![image](https://user-images.githubusercontent.com/16838044/44549472-7a27fb00-a721-11e8-885a-8d85031a89a3.png)

**Comment by okiehsch** [comment]
Well, the fix of https://github.com/uBlockOrigin/uAssets/issues/3284 works on my end and I don't get stuck but if you can reproduce and allowing all `sascdn-script` requests is the only fix add it, unless ads are appearing.

**Comment by okiehsch** [comment]
>  if you want to use the site on the half of your screen, because the filters are blocking something they should not,

I overlooked that, you are correct if I disable uBO there is no "squishing", so adding the filters to `uBO-unbreak` is the right call.

**Comment by Zontir** [comment]
Hi, this fix didn't work for me. The music's still stuck.

**Comment by negrihlava** [comment]
@Zontir @mapx- 
as of today it's getting stuck for me too sometimes...

**Comment by Coeur-Noir** [comment]
…I know issue is closed but…

**URL(s) where the issue occurs too :** 

`https://www.deezer.com/fr`

**Comment by Zontir** [comment]
@Coeur-Noir this is the main page. I've tried Deezer every day and the problem hasn't arisen.

**Comment by Coeur-Noir** [comment]
Oh.
So it might come from another list / filter in my case, do you think ?

**Comment by Coeur-Noir** [comment]
Oops sorry did not see you answered.

I had some filters coming from Easylist.

I disabled those and enabled their adguard counterparts, it sounds ok for the moment.

Inspiration : https://forums.lanik.us/viewtopic.php?f=64&t=37701&p=122089&hilit=deezer#p122089
