### ISSUE TITLE
x button

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3293]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://vidoza.net/1u8fzhplu34v`

### Describe the issue

the same as <https://github.com/uBlockOrigin/uAssets/issues/3063>

### Versions

- Browser/version: chr 68.0.3440.106
- uBlock Origin version: 1.16.16

### Settings

<details><summary>ubo settings</summary>

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

</details>

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
What is the issue?
If you mean
![image](https://user-images.githubusercontent.com/16838044/44559262-0b5e9800-a749-11e8-8306-c2542d4293f3.png)

That is part of the browser, if you want to disable it go to
````
chrome://flags/#enable-experimental-fullscreen-exit-ui
````
Click on the box to the right and select "Disabled".
Relaunch Chrome.
