### ISSUE TITLE
sibnet.ru

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3294]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://video.sibnet.ru/video3419761-850/`

### Describe the issue

ad bar on the player

### Screenshot(s)

![2018-08-24-window](https://user-images.githubusercontent.com/5884000/44559174-85dae800-a748-11e8-820f-069b5884b87f.png)

### Versions

- Browser/version: chr 68.0.3440.106
- uBlock Origin version: 1.16.16

### Settings

<details><summary>ubo settings</summary>

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

</details>

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ZaphodBeebblebrox** [comment]
Already fixed in RU AdList and Adgaurd Russian Filter.

**Comment by KonoromiHimaries** [comment]
@ZaphodBeebblebrox but this player is placed on many other sites
i do not want enable all regional list in my ubo dashboard to fix many similar issues

**Comment by okiehsch** [comment]
Do you have a link to a non russian speaking site with this issue?

**Comment by KonoromiHimaries** [comment]
`http://www.onepiece.wbijam.pl/pierwsza_seria-850.html`
`https://www.animezone.pl/odcinek/boruto-naruto-next-generations/70`

**Comment by okiehsch** [comment]
Well, why not fix it in the polish list, I assume you have that one enabled by default or report it to `EasyList`.
The readme of `uAssets` states:

````
If an issue can be fixed without using extended syntax, i.e. script:inject, redirect or procedural cosmetic filters the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

anti-adblock
ad-reinsertion
popups/popunders
site breakage
will always be fixed in uAssets even if they don't require extended syntax.
````

`video.sibnet.ru###vjs-overlayclip-box`
`video.sibnet.ru##.vjs-overlayclip-box-close`
fixes the issue.

**Comment by KonoromiHimaries** [comment]
@smed79

**Comment by smed79** [comment]
> Do you have a link to a non russian speaking site

- `http://ds-power8992.blogspot.com/2017/03/muro-asalto-al-distrito-stohess-parte-3.html`

> report it to `EasyList`

@ryanbr
