### ISSUE TITLE
[Missed Pop-Ups] kissmanga.com

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#3296]
### URL(s) where the issue occurs

kissmanga.com (but most other pages also have this show up)

### Describe the issue

Hidden popup thing that covers the entire page.

### Screenshot(s)

You can't see my cursor in the screenshot, but there's something that covers the entire page that forces you to click into an ad (the bottom left of the screenshot).

![screenshot](https://user-images.githubusercontent.com/8013408/44608791-b8bdc400-a7ba-11e8-8892-9c1830d59673.png)

### Versions

- Browser/version: Firefox 62b19
- uBlock Origin version: 1.16.16

### Settings

I only changed my filter lists.

> uBlock filters​​​​​
> uBlock filters – Badware risks​
> uBlock filters – Privacy​​​​​
> uBlock filters – Resource abuse​​​​​
> uBlock filters – Unbreak​​
> Adblock Warning Removal List​
> Adguard Base Filters​
> ​​​​EasyList​
> ​​​​Adguard Spyware Filters​
> EasyPrivacy​
> ​​​​Malware Domain List​​​
> Malware domains​
> ​​​​Spam404​
> ​​​​Adguard’s Annoyance List​
> Fanboy’s Anti-Thirdparty Social (see warning inside list)​
> ​​​​Fanboy’s Social Blocking List​
> ​​​​Peter Lowe’s Ad and tracking server list​

Custom filters
> Anti-Facebook List​​
> Nano Defender Integration​​
> ​​​Nano filters​​
> ​​Nano filters - Whitelist​​

### Notes

Reported this to AdGuard (as I use their Safari content blocker on my iPhone, and people on the subreddits for these specific sites do say to use the AdGuard filters, so it would help more people than just me out), and they suggested adding `kissmanga.com#%#!function(a,b){function c(i,j){return"function"!=typeof i||-1===i.toString().indexOf(j)}a=document.addEventListener,document.addEventListener=function(){c(arguments[1],"'popunder'")&&a.apply(document,arguments)},b=window.setInterval,window.setInterval=function(){return c(arguments[0],"'ppu_")?b.apply(window,arguments):void 0},AG_defineProperty("onbeforeunload",{beforeSet:function(j){return c(j,"location.href=options.url")?j:null}})}();` to my filters, and it seems to work with only AdGuard (the hidden popup ad link still shows up).

**Comment by okiehsch** [comment]
That has been fixed two days ago https://github.com/uBlockOrigin/uAssets/commit/35d98b65ba3910a690a411d0ef81c6cff2f772b7
and the fix still works on my end with a default setup, so make sure that your uBO-filter list is up to date.

**Comment by SheepKid12** [comment]
Just checked for updates and it's still happening.

**Comment by SheepKid12** [comment]
Seems to be good now after clearing the sites cookies.
