### ISSUE TITLE
pornvedio.pro [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3302]
URL(s) where the issue occurs

`http://pornvedio.pro/es/video/amateur/wife-with-black-hubby-3`

Describe the issue

ADS NSFW

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.16

Settings

Default

**Comment by ZaphodBeebblebrox** [comment]
Fixed in 7345618, I guess. Same as #3301

**Comment by okiehsch** [comment]
I have no clue why anybody would use such sites, there is no functionality besides redirect

**Comment by ZaphodBeebblebrox** [comment]
Honestly, I think the same thing about half the sites that get posted here.

**Comment by okiehsch** [comment]
Well, I agree about the "strange content of the sites you probably think about, but atleast there is "content".
