### ISSUE TITLE
bagusdl.pro

### ISSUE THREAD

**Issue by ali2134** [uBlockOrigin/uAssets#3306]
this is 4shared generator `http://www.bagusdl.pro/generate.php` 
has antiadblock, any fix please, here and example link:
`https://www.4shared.com/archive/BLpqiull/avolberofe.html`
uBlock Origin v1.16.16
chrome 68.0.3440.106

**Comment by ZaphodBeebblebrox** [comment]
Does `@@||bagusdl.pro^$generichide` work for you?

**Comment by smed79** [comment]
Yes, the suggested filter works.
