### ISSUE TITLE
layer13.net fuckadblock

### ISSUE THREAD

**Issue by adblock321** [uBlockOrigin/uAssets#332]
### URL(s) where the issue occurs

`https://layer13.net/`

### Describe the issue

Anti-adblock overlay appears (with EasyList enabled).

### Versions

- Browser/version: Chromium 53.0.2785.143
- uBlock Origin version: 1.11.4

### Notes

`||layer13.net/js/testing312.js$script,redirect=fuckadblock.js-3.2.0,important` fixes it.

Edit: [The existing `script:contains` rule](https://github.com/uBlockOrigin/uAssets/blob/7d69dd4cc64b2e167410f6a59e0664ad5896b72b/filters/filters.txt#L100) can possibly be removed.

**Comment by gorhill** [comment]
Does this work?

    layer13.net##.modal

**Comment by adblock321** [comment]
`layer13.net##.modal` removes the ability to scroll, as the CSS class `modal-open` is still on the `body` tag which causes `overflow: hidden;`.

**Comment by mapx-** [comment]
add
`@@||layer13.net/ad/$xmlhttprequest`

**Comment by gorhill** [comment]
Ok, try this then:

    layer13.net##.modal
    layer13.net##body:style(overflow: auto !important;)

**Comment by gorhill** [comment]
Yes, `@@||layer13.net/ad/$xmlhttprequest` works well also. I gather this is going to end up in EasyList, so closing.

**Comment by adblock321** [comment]
Shouldn't you remove [the existing `script:contains` rule](https://github.com/uBlockOrigin/uAssets/blob/7d69dd4cc64b2e167410f6a59e0664ad5896b72b/filters/filters.txt#L100) then?

**Comment by gorhill** [comment]
It's actually being used on Firefox, that's why there is no warning with Firefox.

**Comment by adblock321** [comment]
I know. I thought the reasoning behind not adding the fuckadblock-injection is that it can be filtered out without uBlock-specific rules. If that's not the case, then why not use a solution that works on all browsers?

**Comment by gorhill** [comment]
That solution is not in EasyList yet.

**Comment by uBlock-user** [comment]
`layer13.net##script:inject(abort-on-property-read.js, adBlockDetected)`

That should do the job too.
