### ISSUE TITLE
abus.com

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uAssets#3320]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

abus.com

### Describe the issue

The cookie prompts doesn't show up

### Screenshot(s)

With uBO disabled
![screenshot at 2018-08-27 17 28 39](https://user-images.githubusercontent.com/25944158/44669243-aabcad00-aa1f-11e8-8410-d2f650679861.png)

With uBO enabled (doesn't even work with all filters whitelisted)
![screenshot at 2018-08-27 17 29 16](https://user-images.githubusercontent.com/25944158/44669244-ab554380-aa1f-11e8-936f-4e39d5a5a47e.png)

### Versions

- Browser/version: 1.16.20
- uBlock Origin version: 60.0.1 GNU/Linux (64-bit)

### Settings

Default

**Comment by ZaphodBeebblebrox** [comment]
I cannot reproduce on default settings. I can only reproduce if I turn on fanboy's lists, which are supposed to block the cookie promts.

**Comment by stanlane** [comment]
I have not enabled any Fanboy filter.

**Comment by stanlane** [comment]
It was due to a language filter.
