### ISSUE TITLE
quora.com: feed answers getting blocked by uBlock Origin

### ISSUE THREAD

**Issue by spittingmadtruth** [uBlockOrigin/uAssets#3322]
### quora.com

There is no mandatory url for which this issue occurs. To repro you have to signup and visit the home page to see your feed.

### Describe the issue

Most feed answer stories get blocked when they are expanded. The offending rule seems to be `quora.com##.FeedStory:has(a > div:has-text(promoted))`

#### Before expanding:
![image](https://user-images.githubusercontent.com/40901446/44687707-c071a880-aa06-11e8-95c8-3aca893ca001.png)

#### After expanding:
![image](https://user-images.githubusercontent.com/40901446/44688627-b1d8c080-aa09-11e8-9013-33bdd200ce10.png)

(The story just disappears)

### Versions

- Browser/version: Chrome 68.0.3440.106 (Official Build) (64-bit)
- uBlock Origin version: 1.16.18

### Settings

Default

### Notes

The issue seems to be occurring because the feed story div sometimes contains an ad which says "promoted by X". Since the filter mentioned above blocks the parent div itself, the entire answer story gets hidden.

**Comment by dalin-** [comment]
If anyone is interested in a workaround:

1. Open the uBlock dashboard, go to the _My Filters_ tab.
2. Add the following rule on a new line:
`@@quora.com##.FeedStory:has(a > div:has-text(promoted))`

**Comment by mapx-** [comment]
filter removed

**Comment by terrorist96** [comment]
This is still broken for me. I've updated my filters and Quora is still broken. Disabling uBO fixes it.

**Comment by mapx-** [comment]
link ? 
open uBo's logger and post here what cosmetic filters are there

**Comment by gwarser** [comment]
`https://www.quora.com/How-can-I-download-Ustream-TV-videos`

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/44956802-b1bc4300-ae97-11e8-8a80-dca429619b0b.png)

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/44956817-e4663b80-ae97-11e8-9842-c4ba7f811506.png)

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/44956829-019b0a00-ae98-11e8-932b-35fbd1830d25.png)

**Comment by mapx-** [comment]
I still see the page @gwarser  posted above, no issue here

**Comment by terrorist96** [comment]
I can only see it if I disable the `uBlock filters​​​​​ 8,777 used out of 8,778​​​​` list

**Comment by mapx-** [comment]
You should whitelist 1 by 1 the cosmetic filters and see which is bad (for you)

to whitelist such filter for example
`quora.com##.FeedStory:has(a > div:has-text(promoted))`
will become
`quora.com#@#.FeedStory:has(a > div:has-text(promoted))`

**Comment by ZaphodBeebblebrox** [comment]
I can reproduce. For me, it is fixed if I remove `quora.com##.grid_page > .layout_2col_main > div[id]:not(.AnswerListDiv):not(.answer_text_small):not(:last-child):if(a[href][target="_blank"][rel="noopener nofollow"])`

**Comment by terrorist96** [comment]
@mapx- thanks; I wasn't sure how to whitelist cosmetic filters.
@ZaphodBeebblebrox same. I figured out it was that specific filter just as I got an email about your post.
