### ISSUE TITLE
gazetadopovo.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#3325]
### URL(s) where the issue occurs

`https://www.gazetadopovo.com.br/eleicoes/2018/stf-volta-a-discutir-liberdade-de-lula-em-setembro-via-plenario-virtual-6jvmdznyxbkm8yy1qw92mfug6`

### Describe the issue

Annoyance: links and a copyright notice are added to the strings you copy from the article (`function addLink(e)`), even if you copy just a single word to look it up. 

### Versions

- Browser/version: 61.0.2 (64-bit)
- uBlock Origin version: 1.16.20

### Settings

+uBlock filters – Annoyances

**Comment by adranger** [comment]
Please check this again.

@mapx-

**Comment by adranger** [comment]
@mapx- please check `https://www.gazetadopovo.com.br/vida-e-cidadania/publicidade-infantil-regulamentacao-sergio-moro/`

**Comment by llacb47** [comment]
`gazetadopovo.com.br##+js(aeld, copy, getSelection)`

**Comment by adranger** [comment]
@okiehsch  please check the last link again.

**Comment by okiehsch** [comment]
Does the update work without any breakage?

**Comment by adranger** [comment]
The site seems to be working normally. Thanks.
