### ISSUE TITLE
Slader Ads

### ISSUE THREAD

**Issue by oilrig11** [uBlockOrigin/uAssets#3327]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://slader.com/textbook/9780321964670-differential-equations-and-linear-algebra-4th-edition/10/true-false-review/a/#`

### Describe the issue

Slader will block the solution window after a certain number of page loads to get you to watch an ad. It will happen with any textbook if you use the site enough times. Clearing cookies seems to solve the issue for a couple clicks before it pops up again.

### Screenshot(s)

![untitled](https://user-images.githubusercontent.com/34790184/44709228-f42bed00-aa5d-11e8-9a5d-eaefa5ddaf4a.png)

### Versions

- Browser/version: Latest version of Firefox.
- uBlock Origin version: Latest version of Ublock Origin.

### Settings
No real customization other than custom filters and more 3rd party filters in use than default.

**Comment by okiehsch** [comment]
> Slader will block the solution window after a certain number of page loads to get you to watch an ad.

This happens even if I disable `uBO`, so it can't be avoided as far as I can see.
I will add a "fix" to enable the `uBO-user` user to click "Continue by watching an ad", which is currently non functional with uBO enabled.

**Comment by okiehsch** [comment]
If your `uBO-filter` list is up to date you can now click "Continue by watching an ad" and then you click `click to close`.

**Comment by ZaphodBeebblebrox** [comment]
If I manually remove the cookie `sessionid`, the block will not come up, but `slader.com##+js(cookie-remover.js, sessionid)` does not work. Any idea why this happens @gorhill?

**Comment by gorhill** [comment]
`sessionid` is a HTTP-only cookie, it can't be accessed with javascript.
