### ISSUE TITLE
webRTC ads (walla.co.il)

### ISSUE THREAD

**Issue by DanIbba** [uBlockOrigin/uAssets#333]
### URL(s) where the issue occurs

walla.co.il

### Describe the issue

uBlock origin anti webRTC ads doesn't work

### Screenshot(s)

<img width="640" alt="screen shot 2017-03-27 at 14 06 42" src="https://cloud.githubusercontent.com/assets/24211092/24353531/aa6a9be4-12f6-11e7-98c4-dc4df59d1841.png">

![screen shot 2017-03-27 at 14 06 36](https://cloud.githubusercontent.com/assets/24211092/24353596/eb7529f6-12f6-11e7-8167-239b73d182b0.png)

### Versions

- Browser/version: chrome
- uBlock Origin version: 1.11.4

### Settings

+ ISR - Hebrew list

**Comment by adkiller126** [comment]
Use this https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml
Great tool. 
Uno team - you should adopt this code.

**Comment by gorhill** [comment]
This was already fixed, force an update of uBlock filters.

**Comment by gorhill** [comment]
@adkiller126 1) This is **completely** unrelated to the issue here; 2) There is already a setting in uBO to prevent local IP address leak.

**Comment by gorhill** [comment]
Ok, the filter on uBO side does not always reliably work, this means foiling `eval` does not appear sufficient in the current case. This means the fix has to be made in uBO-Extra, and it will have to be used for that site.

**Comment by DanIbba** [comment]
can you fix it for uBO?

**Comment by DanIbba** [comment]
btw - I've downloaded the webrtc-leak-prevent and its works great.

**Comment by gorhill** [comment]
> I've downloaded the webrtc-leak-prevent and its works great;

As said, the purpose of this add-on is **not** to foil WebRTC connections, its purpose is to prevent leaking local IP addresses, and there is already a setting in uBO for this.

I can't prevent people from fooling themselves, but I can at least try to warn others who are willing to not fall for this nonsense:

![a](https://cloud.githubusercontent.com/assets/585534/24356999/14dddf4a-12ca-11e7-8a83-117c6e215026.png)

**Comment by adkiller126** [comment]
Do you see ads with this extension?

**Comment by uBlock-user** [comment]
same as `yad2.co.il` 

If you don't want to use uBO-Extra, add this filter - `walla.co.il##script:inject(abort-on-property-read.js, window.btoa)`

**Comment by adkiller126** [comment]
I think we should find a way to kill the webRTC connection. Adding a specific script for each website will be hard.

**Comment by uBlock-user** [comment]
The filter I posted kills the WebRTC connection, so no ads if you don't want to use uBO-Extra or install uBO-Extra.

**Comment by gorhill** [comment]
> Do you see ads with this extension?

So far, no. However I do see the WebRTC connection being established.

**Comment by gorhill** [comment]
I tested other sites using WebRTC, and yes, it does seem "Disable non-proxied UDP" prevents these sites from tunnelling their ad data through WebRTC, though it does not prevent the WebRTC connection itself from being established. So apparently this is a virtuous side-effect of the setting. This needs investigation -- I suspect using that setting in uBO could lead to issue in some case of legit use of WebRTC.

**Comment by adkiller126** [comment]
This extension success when ubo is not. So i think we should at least look into it.

**Comment by adkiller126** [comment]
Great. I'm not agree about the legit. This is a well known extension.

**Comment by gorhill** [comment]
The current used setting in uBO is "Use the default public interface", and issues have been reported even for this level. Now I would like to know whether increase one level to "Disable non-proxied UDP" will cause more sites to be affected. This is what needs investigation.

**Comment by gorhill** [comment]
Here is a legit use: <https://webtorrent.io/>. Seems to works all fine with "Disable non-proxied UDP".

Given this, I will go ahead and make uBO now use the more strict value for its _"Prevent WebRTC from leaking local IP addresses"_ setting, release the change as rc2, and see what happens from there.

**Comment by gorhill** [comment]
Easy to test case: <https://www.destructoid.com/> -- click-baity ads appears shortly after the page load on the right side.

**Comment by adkiller126** [comment]
Can't see ads on destructoid with the extension and ubo.

**Comment by gorhill** [comment]
Change is in [1.11.5rc2](https://github.com/gorhill/uBlock/releases/tag/1.11.5rc2).

**Comment by gorhill** [comment]
> I think we should find a way to kill the webRTC connection.

See <https://github.com/w3c/webappsec-csp/issues/92>. There is currently no way for uBO to do this using a CSP. It's a hole in the spec, being used against users.

**Comment by uBlock-user** [comment]
> Can't see ads on destructoid with the extension and ubo.

fyi Connection is still established though. Run `chrome://webrtc-internals` there.

**Comment by gorhill** [comment]
It's probably a matter of time before those behind these WebRTC-based ads update their stuff and are no longer foiled by the unexpected side-effect. The primary purpose of "Disable non-proxied UDP" is **not** to block these ads specifically. Once they upgrade their code to do what <https://webtorrent.io/> does for example (which works fine with the stricter setting), then the ads will come back. However, I am willing to use the stricter settings right now due to that nice side effect, which is unrelated to its primary purpose.

**Comment by uBlock-user** [comment]
Webtorrent is using blob, I ran `chrome://webrtc-internals` no webrtc connection is established, yet it's pulling data via `XHRs` via this script - https://webtorrent.io/bundle.js

**Comment by gorhill** [comment]
> I ran `chrome://webrtc-internals` no webrtc connection is established

This is what I see:

![a](https://cloud.githubusercontent.com/assets/585534/24365321/8e43219c-12e3-11e7-9ff6-9cb5c170ec2a.png)

**Comment by uBlock-user** [comment]
This is what I see : -

![](https://i.gyazo.com/6e0685226bf302a0831f3dd059ff4c13.png)

![](https://i.gyazo.com/d78cbc66faca08bf7e3368efdc69e4c7.png)

**Comment by IsraeliUser** [comment]
Why is this option (Prevent WebRTC from leaking local IP addresses) not enabled by default?

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/issues/757#issuecomment-143882515>.

**Comment by krackers** [comment]
The switch to non-proxied UDP seems to have affected Discord, which can no longer do voice chats under the more restrictive policy.
