### ISSUE TITLE
Altmetric

### ISSUE THREAD

**Issue by wolfie717** [uBlockOrigin/uAssets#335]
The domain altmetric.com appears to have been added to uBlock. They provide embeddable badges for academic citations and I'm not sure why they are blacklisted.

https://api.altmetric.com/embeds.html

e.g. https://achim-wolf.com/ under 'Publications'

Thank you.

**Comment by okiehsch** [comment]
`altmetric.com` is part of EasylistPrivacy, so if you want to argue that it does not fall under the 
`EasyPrivacy policy` mentioned here: `https://easylist.to/pages/policy.html` you can do that 
at `https://forums.lanik.us/viewforum.php?f=64`
If you only want to fix the badges at `https://achim-wolf.com` add this filter to your list.
`@@||api.altmetric.com$script,domain=achim-wolf.com`

**Comment by gorhill** [comment]
As said, report to EasyPrivacy maintainers.
