### ISSUE TITLE
muyhistoria.es [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3357]
URL(s) where the issue occurs

`https://www.muyhistoria.es/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 68 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by PIZZA90** [comment]
Anti-Adblock here: 

`https://www.muyhistoria.es/`

**Comment by PIZZA90** [comment]
nevermind i will report here, my bad:

`https://github.com/AdguardTeam/AdguardFilters/issues/65421`

**Comment by PIZZA90** [comment]
nevermind, i will report here, my bad:

`https://github.com/AdguardTeam/AdguardFilters/issues/65421
`
