### ISSUE TITLE
Welt.de [ADS]

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#3358]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://www.welt.de/]`
`[https://www.welt.de/politik/deutschland/article181344492/Michael-Kretschmer-Muessen-verhindern-dass-Chemnitz-Aufmarschgebiet-von-Extremisten-wird.html]`

### Describe the issue

Aggressive ads appeared today on top / bottom / right side. Also in articles. They are loading slowly after the page has been fully rendered.

### Screenshot(s)

https://i.imgur.com/AUBt5Pp.png
https://i.imgur.com/QdskoSK.png

### Versions

- Browser/version: FF 61.0.2 / MS Edge
- uBlock Origin version: 1.16.20

### Settings

- Easylist Germany
- All privacy options enabled (prefetching etc)

### Notes

Reported in Easylist but devs redirected me here because of ublock origin

**Comment by mapx-** [comment]
force an update of ublock filters

**Comment by Symbai** [comment]
Thanks, solved
