### ISSUE TITLE
[NSFW] xhamster

### ISSUE THREAD

**Issue by xevidencex** [uBlockOrigin/uAssets#336]
**Issue 1:**
With the picker, i can't hide that xhamster live banner that is injected in every
third party sites playing xhamster videos..

NSFW: `http://www.oldladyporn.net/lady-movies/91579/lysa-begs-you-to-cum-on-her-feet/`

**Issue 2:** 

Viewing private messages
or trying to login was impossible untill i added those 2 filter exceptions blocking them from "easylist":

`@@|https://$script,third-party,xmlhttprequest,domain=xhamster.com`
`@@$websocket,domain=24video.cc|24video.in|24video.me|24video.sex|24video.xxx|pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|xhamster.com|xtube.com|youporn.com|youporngay.com`

**Comment by gorhill** [comment]
Report to EasyList please: <https://forums.lanik.us/viewforum.php?f=62>.
