### ISSUE TITLE
Reddit opening comments does not work

### ISSUE THREAD

**Issue by nobodynowhereman** [uBlockOrigin/uAssets#3365]
Replace the bracketed [...] placeholders with your own information.

###https://www.reddit.com/

### Versions

- Browser/version: Chrome OS
- uBlock Origin version: v1.16.18
### Settings

- Nano Defender addon is installed

**Comment by ZaphodBeebblebrox** [comment]
Do you still have the issue without nano defender? I cannot reproduce it.

**Comment by nobodynowhereman** [comment]
it looks like Nano defender is actually the issue. I will report to them instead, apologies for the false report.

**Comment by ZaphodBeebblebrox** [comment]
@jspenguin2017

**Comment by jspenguin2017** [comment]
I can't reproduce neither: 
![image](https://user-images.githubusercontent.com/7283682/44826775-93bbbd80-abcd-11e8-8814-3cace027335e.png)

**Comment by ZaphodBeebblebrox** [comment]
I think he means scroll down to buttons that say `[number] more replies` and click on one of them, but I am not certain.

**Comment by jspenguin2017** [comment]
That works fine too. 
![image](https://user-images.githubusercontent.com/7283682/44827140-1133fd80-abcf-11e8-8e76-1ca6759c0356.png)
