### ISSUE TITLE
vidup.io

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3366]
### URL(s) where the issue occurs

`https://vidup.io/p1w6kdq6qmx8`

### Describe the issue

popups

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: chr 68.0.3440.106
- uBlock Origin version: 1.16.16

### Settings

<details><summary>ubo settings</summary>

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

</details>

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
`vidup.io^$csp=sandbox allow-forms allow-presentation allow-scripts allow-top-navigation allow-orientation-lock allow-pointer-lock allow-same-origin allow-popups-to-escape-sandbox`
