### ISSUE TITLE
New circumventing mechanism spotted at welt.de - delayed loading?

### ISSUE THREAD

**Issue by broese** [uBlockOrigin/uAssets#3369]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://www.welt.de/]`

### Describe the issue

[welt.de seems to have deployed a new way to circumvent adblockers, I believe only since yesterday (2018-08-29). When visiting the page, ads are seen appearing on top and the right side while uBlockOrigin is enabled (which otherwise has been working perfectly with this site all the time).

I tried to manually block these elements and create a custom filter. Remarkably, the images always have a very distinguishable name "www.welt.de/img/deutschland/cropXXX/XXX-XXX-XXX/Bilder-zur-Campus-Elite-Uni-GoettingenXXX.jpg", where XXX are random components *). I thought creating a filter like "/Goettingen/" would suffice, and it seemed it does, as uBlock correctly detects the ads (tints them red while in filter editor), and after applying the filter, they disappear.

However, after reloading the page, these ads appear again, but usually just one of them, and note: delayed by a few seconds! Looking at the network monitor (using F12 in Firefox), I see that while the page is loading, there are several requests to images like this are made, and disappear, so my guess the filter is working and blocking the requests. During that time, I don't see any ads popping up.

But then, about 3-5 seconds later, another request is made that goes through and the ad image appears. Notably, the response in this case is 302, the headers show a redirection to healte.de.
My guess is that the checking for ad links stops after a few seconds, and another request made after that is not blocked by uBlockOrigin.
]

### Screenshot(s)

[https://imgur.com/a/pHiEWvc]

### Versions

- Browser/version: [Firefox Quantum 61.0, Linux-x64]
- uBlock Origin version: [uBlock Origin v1.16.20]

### Settings

- [Created a few custom filters based on URLs and CSS]

### Notes

[*) Anyone knows about who or why uses this name ("Pictures of the campus of the elite university Göttingen") for ad images? I saw it appearing in welt.de ads very long time ago. Maybe it made them sound like a stock photo name?]

**Comment by okiehsch** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/3358
