### ISSUE TITLE
[NSFW] returning blocked element..

### ISSUE THREAD

**Issue by xevidencex** [uBlockOrigin/uAssets#337]
Using e-picker, i block:
jizzbunker.com##.banner-popup

NSFW: `http://jizzbunker.com/246927/fat-hairy-white-trash-wifes-dirty-sweaty-pussy-pits.html`

pause the video, & ubo "allows" its return... .

**Comment by okiehsch** [comment]
I can not reproduce ##.banner-popup stays hidden on my end, even after I pause the video or reload the site, also tried with a different random video with the same result.

**Comment by xevidencex** [comment]
so strange.. it's fixed on my side too, but when i created the new filter, i was experiencing it above.
anyways, closed issue.
