### ISSUE TITLE
welt.de [anti-adblock]

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [uBlockOrigin/uAssets#3376]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.welt.de/

### Describe the issue

Adds appear when they didn't before

### Versions

- Browser/version: Firefox 62
- uBlock Origin version: 1.16.21b1

### Settings

None

### Notes
Tried Element blocking, didn't work

**Comment by ZaphodBeebblebrox** [comment]
Already fixed. Force an update of your filter lists.
