### ISSUE TITLE
Filters file - Antivirus False Positive

### ISSUE THREAD

**Issue by jholmes417** [uBlockOrigin/uAssets#3381]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`Actually not relevant in this case...see description and screenshot`

### Describe the issue

Today ESET NOD32 antivirus deleted the filters.txt file stating it was adware (JS/Adware.Agent.AC). Not sure if this is correct, so I reported it to ESET as a false positive...but thought you might like to know about the issue as well. The filters.txt file flagged was from the version of uBlock Origin for MS Edge.

### Screenshot(s)

![esetfalsepositive_ublockorigin](https://user-images.githubusercontent.com/42879981/44938963-875b7000-ad47-11e8-874b-840939842b87.png)

### Versions

- Browser/version: Microsoft Edge/42.17134.1.0
- uBlock Origin version: 1.15.24

### Settings

- No changes to default.

### Notes

I have not seen any popups as would suggest a genuine JS/Adware infection, so I really think this might be a false positive. Perhaps something can be sent to ESET about the file as evidence of the false positive issue. I submitted the file through my installation of NOD32, and hopefully if enough folks get through to ESET they will stop deleting the filters.txt file for MS Edge installations.

Note, that today on a manual scan I also had NOD32 flag the filters.txt file from a older Chrome install that was part of a set of backups (from around December of last year). I can't tell you the version of Chrome that the profile was from, but it looks to be version 1.14.22 of uBLock Origin. The file path that NOD32 deleted that copy of filters.txt from was "....\ChromeProfiles\Default\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\1.14.22_0\assets\ublock".

The newest version for Chrome (1.16.18) did NOT cause NOD32 to be upset and doesn't show up as adware. Something in the old versions of the filters.txt file (that MS Edge still uses) is tripping up NOD32?

**Comment by kowith337** [comment]
You can report to actual [uBlock issues](https://github.com/uBlockOrigin/uBlock-issues/issues)

**Comment by gwarser** [comment]
https://www.virustotal.com/#/url/c446d3b9d4bdefe098d563737a9d4c02f0781f8d565ffbe2307e87ac9332a018/detection
0/70
https://www.virustotal.com/#/file/d5b44e1d61f4ef4b949bf52b606279aae523cd073c996dd6c812dc1f08a69a88/detection
0/57

Already fixed by ESET?
