### ISSUE TITLE
[Clipboard manipulation] emol.com

### ISSUE THREAD

**Issue by sigtus** [uBlockOrigin/uAssets#3382]
### URL(s) where the issue occurs

http://www.emol.com/noticias/Nacional/2018/08/31/919115/Intendente-de-Valparaiso-tras-COE-Indices-de-contaminacion-han-disminuido.html

### Describe the issue

Clipboard manipulation.

### Versions

- Browser/version: Firefox 61.0.2
- uBlock Origin version: uBlock Origin 1.16.20

### Settings

- Default + EasyList Spanish + AdGuard Spanish + uBlock Annoyances + AdGuard Annoyances

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.
