### ISSUE TITLE
dramafever.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3389]
### URL(s) where the issue occurs

`https://www.dramafever.com/drama/5193/18/are-you-human-too/`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]
yellow dots on the progress bar

### Screenshot(s)

![2018-09-02-are you human too_ _ episode 18 _ dramafever](https://user-images.githubusercontent.com/5884000/44954370-38295280-aea1-11e8-88c8-c38b81f85572.png)

### Versions

- Browser/version: [here] chr 68.0.3440.106
- uBlock Origin version: [here] ubo 1.16.18

### Settings

<details><summary>ubo settings</summary>

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

</details>

**Comment by uBlock-user** [comment]
`dramafever.com##.vjs-admarker`

**Comment by THEtomaso** [comment]
I noticed those things @ YouTube Gaming, a long time ago.

Example:
`https://gaming.youtube.com/watch?v=ePI6USOMHec`

I took care of them with this rule (which you might want to add too):
`youtube.com##.ytp-ad-progress`

**Comment by mapx-** [comment]
`##.ytp-ad-progress` is already in easylist

The other annoyance above should go in easylist

**Comment by THEtomaso** [comment]
> The other annoyance above should go in easylist

Reported it here:
https://github.com/easylist/easylist/issues/1778/

**Comment by uBlock-user** [comment]
> Yeah, but for some reason it doesn't work

See if there is a `$generichide` filter overiding it via the logger.

**Comment by THEtomaso** [comment]
I just gave it a try, using EasyList only.
The existing rule doesn't work, and I can't see anything in the logger that should override it.
Weird!

**Comment by okiehsch** [comment]
> The existing rule doesn't work

You mean it does not show up in the logger?

**Comment by THEtomaso** [comment]
> You mean it does not show up in the logger?

That's right.
The only cosmetic rule from EasyList that shows up in the logger is this one:
`##.ad-container`

**Comment by mapx-** [comment]
Try reinstalling uBo and use the default setup.

**Comment by okiehsch** [comment]
![unbenannt](https://user-images.githubusercontent.com/16838044/44960247-1e692900-aefc-11e8-82d4-8a626b7e76b3.PNG)

works with Chrome and Firefox on my end.

**Comment by THEtomaso** [comment]
> Try reinstalling uBo and use the default setup.

I just tried with a fresh Pale Moon Portable, using uBO with everything set to default.
That EasyList rule still doesn't work!

It should be noted that I'm using uBO v1.16.4.4 (XUL)
Perhaps there's a bug in this branch that needs to be fixed?

**Comment by THEtomaso** [comment]
I've double checked it now.
Fresh browser, fresh uBO legacy, and updated filters with everything set to default..

The rule `##.ytp-ad-progress` works just fine at `youtube.com`, but NOT at `gaming.youtube.com`!
adding `youtube.com` in front of it, fixes it right away.
Like this:
`youtube.com##.ytp-ad-progress`

**Comment by mapx-** [comment]
right, on gaming I can reproduce the issue, what do you think @gorhill  ? (working fine in chrome, firefox)

**Comment by THEtomaso** [comment]
I refreshed the page 10 times just now..
The existing EasyList rule didn't work one single time! :(

**Comment by gorhill** [comment]
> what do you think @gorhill

I don't know, I would need to investigate but if only Pale Moon is affected I rather leave the investigation to whoever uses Pale Moon and uBO.

**Comment by gwarser** [comment]
`cssOrigin` was introduced in 53, I can reproduce in 52.9 ESR

**Comment by gorhill** [comment]
He is using uBO/legacy.

**Comment by THEtomaso** [comment]
I've posted a reference in the Pale Moon forum here:
`https://forum.palemoon.org/viewtopic.php?f=46&t=16685&p=151048#p151048`

**Comment by gorhill** [comment]
I can't reproduce with Pale Moon 27.6.0, uBO/legacy and `youtube.com##.ytp-ad-progress`.

**Comment by THEtomaso** [comment]
Yeah, but the EasyList rule looks like this: `##.ytp-ad-progress` (without `youtube.com` in front of it).
Like I've already pointed out; this only works at `youtube.com`, but NOT at `gaming.youtube.com`.
If I add `youtube.com` in front of the rule, like this: `youtube.com##.ytp-ad-progress`, then it works at `gaming.youtube.com` as well!

**Comment by mapx-** [comment]
example link https://gaming.youtube.com/watch?v=SHdLYH8jYV8

**Comment by THEtomaso** [comment]
> it's probably gorhill/uBlock#1885 (comment).

And this is no longer an issue for the WebExtensions version of uBO?

**Comment by gorhill** [comment]
Still an issue -- maybe the timings are different now such that when uBO process the DOM the class `.ytp-ad-progress` is already in there. I am just speculating.

But anyways, thinking about it, if this is the issue, then I will add the filter to uBO filters, there is always the chance it will occur with the webext version.
