### ISSUE TITLE
Pinterest - No access problem

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#3390]
### URL(s) where the issue occurs
Pinterest domains

### Example
`https://www.pinterest.com/phatcatholic/star-trek/`

### Describe the issue
I've always had Web Notifications disabled in my browser (**dom.webnotifications.enabled = false**, in Firefox-based browsers).
Pinterest is the only place that I'm aware of, where this configuration produces a problem.
They seem to specifically search for the presence, and support, for this API in people's browsers.
If it isn't detected, then all Pinterest boards will fail to load!

What do you think?
Is there a way to bypass this check, by targeting a script with some type of advanced injector rule?

### Versions

- Browser/version: Pale Moon v28.0.1 (x64)
- uBlock Origin version: v1.16.4.4 (XUL)

### Notes
I think this script is the culprit, as it contains some lines refering to "notification":
`https://s.pinimg.com/webapp/js/pjs-244-71bf7bf228b5899e8fce.js`

**Comment by mapx-** [comment]
browser side issue, report on bugzilla

**Comment by THEtomaso** [comment]
No, this is NOT a browser issue!
Read my post again.
It's because of Pinterest's aggressive web coding.
Of course, I've already reported the "problem" to them, but let's be realistic here.. The API sniffing is by design, and they're gonna do anything about it.
Therefore, it would be nice to find a way around it, in the interest of maintaining privacy!

**Comment by okiehsch** [comment]
>  think this script is the culprit, as it contains some lines refering to "notification":
https://s.pinimg.com/webapp/js/pjs-244-71bf7bf228b5899e8fce.js

Actually it's 
`https://s.pinimg.com/webapp/js/vendor-react-2684e3f92006f0de8fc5.js`


![image](https://user-images.githubusercontent.com/16838044/45120376-2f18d980-b15e-11e8-81d7-1094ffe6fc88.png)

I don't see a way to fix this issue with `uBO-compatible` filters.

**Comment by THEtomaso** [comment]
Oh well, thanks for looking into it.
