### ISSUE TITLE
Golem.de big banners

### ISSUE THREAD

**Issue by rugk** [uBlockOrigin/uAssets#3391]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.golem.de/news/app-fuer-oeffentlichen-nahverkehr-oeffi-ist-wieder-im-play-store-verfuegbar-1809-136343.html`
(any other Golem.de article)

### Describe the issue

There are very big banners added via JS or so, so that the page jumps around when they are inserted. They are sometimes even animated (although they are JPGs, no idea how they do that…).

Also they are self-hosted.

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/11966684/44957235-3a56d580-aed0-11e8-8420-2b72c71a715c.png)

### Versions

- Browser/version: Firefox 61.0.2
- uBlock Origin version: v1.16.20

### Settings

nothing special

### Notes

Adding `||www.golem.de/*/sp_*-*-i_rc.jpg` as a filter, seems to block the ads.

**Comment by rugk** [comment]
What exactly cannot you reproduce?

**Comment by ZaphodBeebblebrox** [comment]
With the latest filter lists, I do not get any banner ads.

**Comment by rugk** [comment]
Here is my filters list:

![grafik](https://user-images.githubusercontent.com/11966684/44958694-17ceb780-aee4-11e8-8c64-3f2cfc8c9921.png)

**Comment by okiehsch** [comment]
Fixed by
![image](https://user-images.githubusercontent.com/16838044/44958697-21581f80-aee4-11e8-9388-0cd9d0960c86.png)

3 days ago.

If you hover over the clock symbol next to `uBlock filters 8241 benutzt aus 8243`, what does it say?

**Comment by mapx-** [comment]
purge all caches and update the lists
(You should remove the second Resource abuse list)

**Comment by rugk** [comment]
Okay, did both, but banners are still there.
`uBlock filters` is updated, but I cannot find the entry in your screenshot:

![grafik](https://user-images.githubusercontent.com/11966684/44958862-2f0ea480-aee6-11e8-92b2-9192acbc2693.png)

**Comment by gwarser** [comment]
Skip `##`, this is very long list of domains.

**Comment by okiehsch** [comment]
Well, then you probably have the same issue as https://github.com/uBlockOrigin/uAssets/issues/3364#issuecomment-417140343

Adding
`golem.de##script:inject(abort-on-property-read.js, uabpd3)`
to your filter list fixes your issue?

**Comment by rugk** [comment]
> Adding […] to your filter list fixes your issue?

Yes.

**Comment by rugk** [comment]
So If I can do anything to debug this list update issue, let me know.

**Comment by okiehsch** [comment]
You can open an issue at `https://github.com/uBlockOrigin/uBlock-issues` as it is not a filter issue.

**Comment by rugk** [comment]
Actually did so, but now I notice that the list at https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt actually is the one from 2017 and it does not include the filter you mention.

There actually are no golem.de specific filters anyway [in there](https://github.com/uBlockOrigin/uAssets/search?q=golem.de&unscoped_q=golem.de). So are you sure it's not a problem with the filter list??

My one seems to be up-to-date.

**Comment by okiehsch** [comment]
@rugk if you think that the list has last been updated in 2017 because of
`Last updated: 2017-10-10`
That concerns only the `google*##` entries, which were indeed last updated in 2017.

**Comment by rugk** [comment]
But `golem.de##` is nowhere in there… (if you Ctrl+F)

**Comment by okiehsch** [comment]
Like **gwarser** already mentioned `golem.de` is one domain in a long list of domains that all use the same filter, so you have to search for `golem.de` and if you do that you will get the 8 hits.
