### ISSUE TITLE
Medium Blocking and Chase.com

### ISSUE THREAD

**Issue by diego898** [uBlockOrigin/uAssets#340]
### URL(s) where the issue occurs
`www.chase.com`

### Describe the issue
I had the same problem as described in https://github.com/gorhill/uBlock/issues/1816. I couldn't get through to chase using just the dynamic filtering pane so I whitelisted `chase.com`. Now I can login, but the dynamic filtering pane now shows several entries like:

- `doubleclick.net`
- `clixmetrix.com`
- `t.co`

which are concerning. I am trying to just allow the absolute minimum required to use chase, and I'm not sure that whitelisting `chase.com` is the best solution. 

My issues are:

- How can I go about enabling the absolute minimum to be able to use `chase.com` under Medium Blocking Mode?
- Why is `doubleclick.net` green? (see the **Notes** section)

**Note**: I am a _new_  "advanced" user ( :] ) of ublock origin. I am trying to learn. 

### Screenshot(s)

When whitelisting `chase.com` I see this after logging in:
![image](https://cloud.githubusercontent.com/assets/742407/24465350/8e5b6f02-1461-11e7-914a-31b03cda6c85.png)

When `chase.com` is **not** whitelisted, on the login page I see:
![image](https://cloud.githubusercontent.com/assets/742407/24465768/2e0f6d0e-1463-11e7-9225-b9068ab03c7f.png)

### Versions

- Browser/version: Chrome 57.0
- uBlock Origin version: 1.11.4

### Settings

My selected static filters:
![image](https://cloud.githubusercontent.com/assets/742407/24465618/89083c14-1462-11e7-9277-be87ee437393.png)

My filters:
![image](https://cloud.githubusercontent.com/assets/742407/24465639/9960c27a-1462-11e7-9faf-5ed756dbeb94.png)

I have third party scripts and third party frames globally blocked, as per ublock origins ["medium mode"](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode)

### Notes

_I am not sure this is related to my original issue_, but I just noticed it now so I am including it here -
 please let me know if I should make a separate issue for this:

I do not know why doubleclick.net is green on `chase.com`, even when `chase.com` is **not** whitelisted. To investigate, I opened the logger on the login page, and see the following:

![image](https://cloud.githubusercontent.com/assets/742407/24465806/5ad38028-1463-11e7-911e-0acd063cbafb.png)

Clicking it gives the following: 
![image](https://cloud.githubusercontent.com/assets/742407/24465837/6f4a9910-1463-11e7-9288-f6e3479f26f7.png)

saying that: `@@||ad.doubleclick.net/ddm/$image` is coming from Fanboy's. From reading the [documentation on filter syntax](https://adblockplus.org/en/filter-cheatsheet#exceptions), I see that this is an _exception rule:_

> Exception rules are built the same as blocking rules, they define which addresses should be allowed even if matching blocking rules exists.

If I am reading the documentation correctly, I can write;

`{1:@@}{2:||ad.doubleclick.net/ddm/}{3:$}{4:image}`

1. Exception rule
2. Address to be allowed
3. Option separator
4. Type option - the type of element that this exception rule should be applied to:

  
Am I correct in parsing this to mean: Overide any blocking rules, and allow images from `ad.doubleclick.net/ddm`. If my parsing is correct - why does this rule exist?

**Comment by gorhill** [comment]
> I do not know why doubleclick.net is green

Just click on the filter to find out.

**Comment by diego898** [comment]
@gorhill I did - in the notes section I explain it and end with another question

**Comment by gorhill** [comment]
> why does this rule exist?

You have to ask the filter list maintainers -- they created the filter in the first place. Safest assumption is because this was to prevent page breakage as a result of another block filter.

**Comment by gorhill** [comment]
If you want to override what filter is present in a filter list, use dynamic filtering rules, they always override whatever is in filter lists. That's in the wiki.

**Comment by diego898** [comment]
I understand that - thats how I enabled medium mode, and how I intend to get to get chase.com instead of just whitelisting it.

**Comment by gorhill** [comment]
If you can't log in on chase.com, then the logger will help you figure it out. You will have to find out what network request(s) is(are) blocked which prevent the log-in operation from working properly. I don't know what else to say. I don't have an account with chase.

**Comment by diego898** [comment]
ok thank you

**Comment by gorhill** [comment]
From the look of the popup, you quite probably need to locally noop `chasecdn.com`. Did you try that?

**Comment by okiehsch** [comment]
> How can I go about enabling the absolute minimum to be able to use chase.com under Medium Blocking Mode?

Now I have no account and can not test, but you can't login if you noop `chasecdn.com`?

**Comment by diego898** [comment]
I tried noop and even allowing:

![image](https://cloud.githubusercontent.com/assets/742407/24468266/91c19760-146c-11e7-9444-86b64ec6818d.png)

**Comment by gorhill** [comment]
See if in the logger there are still requests to `chasecdn.com` being blocked. It could be that the rule that will work will be `chase.com chasecdn.com * noop`, while the rule created from the UI is `www.chase.com chasecdn.com * noop`.

**Comment by jjohns71** [comment]
@diego898 do you have other addons enabled? I have mirrored your settings and can login to chase.com with my user/pass with no problem.

**Comment by diego898** [comment]
@jjohns71 the only other addons I have enabled that might interfere are:

- uBO-Scope
- uBlock Origin Extra
- Privacy Badger
- HTTPS Everywhere

I will try testing disabling and report back

**Comment by gorhill** [comment]
uBO-Scope only observe, it does not block or modify network requests, so you can rule out this one as being the issue.

**Comment by diego898** [comment]
@jjohns71 I opened an incognito window, and the only extension I have enabled in incognito is ublock origin. With both green listed I still cant login.

**Comment by gorhill** [comment]
> With both green listed I still cant login.

There is no way to avoid the logger to diagnose such issue.

**Comment by diego898** [comment]
I understand - I was just responding to @jjohns71 earlier comment - I will report back after using the logger

**Comment by diego898** [comment]
I had these from the dynamic filtering pane:
```
secure05c.chase.com chasecdn.com * noop
secure05c.chase.com chase.com * noop
```

Using the logger I added:

```
chase.com https://static.chasecdn.com/web/2017.03.12-757/blue-boot/dist/blue-boot/js/main.js script noop
```

And now I can login and use chase. Thank you all for your help. I will ask elsewhere for why that doubleclick.net is allowed

**Comment by uBlock-user** [comment]
Remove all dynamic filtering rules and add

```
||$third-party,domain=chase.com
@@||chasecdn.com^$domain=chase.com
```
