### ISSUE TITLE
Oath redirection for cookie/ad notice

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#3400]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs: Yahoo not a set link but random when clicking to read an article, go to sports. ect
yahoo.com,  news.yahoo.com,  sports.yahoo.com

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

When you click on a link for an article or for the sports page or another random link you get redirected to the new Oath please accept of cookie/ad notice if you simply close the page and reopen you get same redirection 

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions
, 
- Browser/version: [FF 60.0.2]
- uBlock Origin version: [UBO 1.16.21b3 default filterlist]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by troysjanda** [comment]
https://guce.oath.com/collectConsent?sessionId=2_cc-session_88175153-247f-45a8-b856-57082c040758&lang=en-GB&inline=false&jsVersion=null&experiment=null

this is the redirection page displayed I tried to block https://guce.oath.com but not it just shows that is being blocked. We need to figure out a way to bypass the redirection all together. Does not happen on every link I find it randomly, but getthe redirection more times than not.

**Comment by uBlock-user** [comment]
Try `||oath.com^$third-party`

**Comment by hawkeye116477** [comment]
That don't work. The only working fix here is to do auto-click „OK" button, but unfortunately uBO can't do that.
Make new userscript on Violentmonkey/Greasemonkey/Tampermonkey and paste this:
```
var url = location.href;
if(url.match(/guce.oath.com\/collectConsent/))
{
    document.addEventListener("DOMContentLoaded", function(event) {
        var consentbtn = document.body.querySelector(".btn.agree");
        if (consentbtn)
        {
            consentbtn.click();
        }
    });
}
```
or you can ask Nano Adblocker's maintainer to add auto-click for that, but cuz user have choice to not accept that, I suppose that he rather won't add that.

**Comment by okiehsch** [comment]
I will close this as uBO will not add a scriptlet that enables some form of auto-click capability for security reasons.

**Comment by uBlock-user** [comment]
I have that domain blocked and I can't reproduce.

**Comment by okiehsch** [comment]
I get the redirection if I go to `news.yahoo.com`after I click ok I can't reproduce unless I delete cookies.

**Comment by troysjanda** [comment]
||guce.oath.com^$important
||guce.yahoo.com^$important
||oath.com^$third-party

These seem to have stopped the redirection. I have not had the problem since adding this to my custom Filterlist

Also I don't like to use userscripts that auto click.. ect could lead to problems and or security problems

**Comment by uBlock-user** [comment]
> ||guce.oath.com^$important

No need to add that with `||oath.com^$third-party` already in place, you could also `$important` to that filter so no exception filters can overide it.

**Comment by hawkeye116477** [comment]
For me it doesn't work correclty, uBO stoppes fetching page only and I can't see Yahoo.

**Comment by PIZZA90** [comment]
**uBO** cant fix this? some content is hidden if no accept that trash of privacy

`https://es.sports.yahoo.com/noticias/real-madrid-barcelona-085506302.html`


![yhh](https://user-images.githubusercontent.com/33556647/114294383-8d3c9480-9a9e-11eb-9fb8-e41aedcfc3b4.PNG)

**Comment by mapx-** [comment]
Even disabling uBO  still getting the same messages

**Comment by PIZZA90** [comment]
understood thanks.
