### ISSUE TITLE
Lastpass extension sidebar

### ISSUE THREAD

**Issue by bobsage123** [uBlockOrigin/uAssets#3407]
### URL: 

Lastpass chrome extension - chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/vault.html

### Describe the issue

Ublock is able to block the ad on the right in the lastpass free extension but not the whole sidebar. Can this be blocked?

### Screenshot(s)

https://i.imgur.com/aVYlUsQ.png 

### Versions
Chrome 68
Ublock origin latest ver

**Comment by mapx-** [comment]
Did you try the element picker ?

**Comment by bobsage123** [comment]
It's not even an option to choose when on the lastpass extension page.

**Comment by gorhill** [comment]
By design, an extension cannot access another extension's pages.
