### ISSUE TITLE
Radio website

### ISSUE THREAD

**Issue by pKalju** [uBlockOrigin/uAssets#3411]
### URL(s) where the issue occurs

`http://www.radioline.co/`

### Describe the issue

Says in red "AdBlock is activated on your browser and can potentially prevent you from playing several radio stations & podcasts streams".

### Screenshot(s)

![Image](https://i.futureclient.net/cIPdE26e.png)

### Versions

- Browser/version: Chrome 68.0.3440.106
- uBlock Origin version: 1.16.18

### Settings

- Default settings

### Notes

By disabling uBlock the adblock detector does not show a message.

**Comment by mapx-** [comment]
annoyances list, be sure you subscribed that list
