### ISSUE TITLE
forocoches.com [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3413]
URL(s) where the issue occurs

`https://www.forocoches.com/foro/forumdisplay.php?f=17`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by okiehsch** [comment]
`forocoches.com##[href^="https://goo.gl/"]`

**Comment by KiLL4FuNK** [comment]
@diaux

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by mapx-** [comment]
add
`forocoches.com##.infobck`
