### ISSUE TITLE
Adblocker Detected - Admiral

### ISSUE THREAD

**Issue by Jamyn** [uBlockOrigin/uAssets#3417]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://secureyourdigitallife.in/introduction-to-android-and-itss-architecture/`

### Describe the issue

Even with Nano Adblocker and Nano Defender enabled, the site detects ad blockers and prevents access.

### Screenshot(s)

[screenshot](https://i.imgur.com/jO474m9.png)

### Versions

- Browser/version: Google Chrome 69.0.3947
- [Nano Defender](https://github.com/NanoAdblocker/NanoCore2/releases) version: 1.0.0.66

### Settings

- Settings are default.
### Notes

Site appears to be using [Admiral](https://getadmiral.com/) to detect adblockers.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ddd62baf55c3218b6fe25876fb344aa10516daba

**Comment by DoorCar** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/122950
