### ISSUE TITLE
EasyPrivacy whitelists trackers

### ISSUE THREAD

**Issue by KOLANICH** [uBlockOrigin/uAssets#3418]
### URL(s) where the issue occurs
https://github.com/uBlockOrigin/uAssets/blob/9563a70140003f20de555a9ba715a224aabdcf4e/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L14244

### Describe the issue
EasyPrivacy contains a witelist of trackers. I was greatly surprised to find out that 3rd-party lists can undo custom rules done by me. I guess that the policy should be that officially-promoted third-party lists mustn't contain rules whitelisting trackers.

**Comment by mapx-** [comment]
You can enforce your own filters adding `important` key / option

**Comment by KOLANICH** [comment]
Thank you for the advise. I guess user-provided filters should be important implicitly and by default: if a user ever bothered, that means that there is something wrong/missing in subscribtions.

**Comment by mapx-** [comment]
well, there is no such prioritization (in no adblocker as I know)

**Comment by KOLANICH** [comment]
>well, there is no such prioritization (in no adblocker as I know)

I have created a separate issue about it: https://github.com/uBlockOrigin/uBlock-issues/issues/204 , this one is about removing all the lists whitelisting trackers and ads from this repo.

**Comment by okiehsch** [comment]
So if I understand you correctly you want us to remove all filter lists that include exception rules for network requests?

**Comment by uBlock-user** [comment]
> The fact that one filter can undo done by another 

That's been like this since the beginning and it's like that in all content blockers, uBO offers `$important` which can override any whitelists, which is something that adblock/ABP and their clones don't.

**Comment by okiehsch** [comment]
That would be all the lists except the ones based on host files.
All major adblocking lists include filters that whitelist ad/tracking requests for specific sites to avoid site breakage.

**Comment by KOLANICH** [comment]
>All major adblocking lists include filters that whitelist ad/tracking requests for specific sites to avoid site breakage.

These whitelists should be replaced by surrogates.

**Comment by sebast889** [comment]
Related https://github.com/gorhill/uBlock/issues/3353 this would give an option for users whitelist filters to work while disregarding 3rd party whitelists but gorhill said he wouldn't consider it unless more people were interested in it.

**Comment by okiehsch** [comment]
This is not an `uAssets` issue, if you want to argue with **gorhill** that he should remove all filter lists of
````
https://github.com/gorhill/uBlock/blob/7ab0d94f921ac12208cf54923c257fb9c7e48d1c/assets/assets.json
````
from the default setup that include whitlisting for some ad/tracking requests, or if you want uBlock to strip all exception filters from such lists you can open an issue at https://github.com/uBlockOrigin/uBlock-issues/issues/new

**Comment by uBlock-user** [comment]
It's already been declined once, bringing it up again won't change anything. Also please don't open any new issue about removing whitelisting filters, https://github.com/uBlockOrigin/uBlock-issues/issues/204 was opened in that vein and was also declined by him.

**Comment by sebast889** [comment]
I meant to @KOLANICH on my above post just to let him know about a feature which is similar to what he is looking for. I didn't mean for you to respond to it. I have already said my thoughts on the feature and gorhill has said his, there's nothing more for me to argue about it.
