### ISSUE TITLE
AAB on MexaShare

### ISSUE THREAD

**Issue by kowith337** [uBlockOrigin/uAssets#3419]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`mexashare.com`

### Describe the issue
Anti-AdBlock
- The site simple check the `advertisement.js` to be allowed or not to set the value of `jQuery.adblock` as `false`

### Screenshot(s)
![image](https://user-images.githubusercontent.com/16535467/45156128-71e2bc00-b207-11e8-973e-4a5c9bfef3b5.png)

### Versions
- Browser/version: Chromium | 68.0.3424.0 (Official Build) (64-bit)
- uBlock Origin version: 1.16.21b2

### Settings
- I am advanced user
- All filterlists default, except add Thai Paranoid Block, but none of any effects occur to this site

### Notes
Just allow `mexashare.com/advertisement.js` to be loaded, Nano has whitelisted this already.

**Comment by KiLL4FuNK** [comment]
with the link if it appears

`https://www.mexashare.com/2afrasyd1zz3/Los_Autos_Locos.part5.rar.html`

**Comment by KiLL4FuNK** [comment]
Anti-AdBlock

`https://www.mexashare.com/wvyiswfhvhm8/Hola_Instagram_Puzzle.zip.html`

**Comment by okiehsch** [comment]
New domain, example link: 
`https://mexa.sh/z4h11314j9ew/Eternal.Code.2019.HDRip.XviD.AC3-EVO.avi.html`

**Comment by kowith337** [comment]
Also add this js inject to prevent popup laid into the download button.
`mexa.sh##+js(abort-current-inline-script, installBtnvar)`

```javascript
 function installBtnvar(btn_locator, popup_url) {
   var fired = false;
   var onClickCb = (function(fired) {
      return function(evt) {
         if(!fired)
         {
            window.open(popup_url, '_blank');
            evt.preventDefault();
            evt.stopImmediatePropagation();
            fired = true;
         }
      }
   })(fired);
   $(btn_locator).click(onClickCb);
}
 installBtnvar("#downloadbtn", 'https://www.netcpms.com/be07rhnq?key=d48b02d509b849c3460210c5259d1c0a'); 
```

**Comment by kowith337** [comment]
Update popup ads that triggered when click to anywhere of page (first-click steal)

`##+js(acis, ajsPop)`

**Comment by kowith337** [comment]
AdFPoint first-click hijack overlay (z-index), as of 2021/04/17
`mexa.sh##+js(acis, afScript, tabunder)`

**Comment by okiehsch** [comment]
Fixed.
Working link for reference
`https://mexa.sh/6y5xmhlzddym`
