### ISSUE TITLE
Prebake - Filter Obtrusive Cookie Notices list appears no longer maintained.

### ISSUE THREAD

**Issue by aroboto** [uBlockOrigin/uAssets#342]
### URL(s) where the issue occurs

`[twitch.tv]`

### Describe the issue

EU: Prebake - Filter Obtrusive Cookie Notices appears no longer maintained, last update on May 4, 2016. Using the filter on Twitch results in a only partially blocked cookie notification. As this list is 11 months without an update there are likely more filters that no longer work or that will break sites.

### Screenshot(s)

![nmrdbow 1](https://cloud.githubusercontent.com/assets/22084203/24573650/fd1d0ff4-167d-11e7-9f78-9cb95afbf03a.png)

### Versions

- Browser/version: Chrome Version 57.0.2987.133
- uBlock Origin version:  v1.11.4

**Comment by SMed79** [comment]
Hi, 

Subscribe to "[**Fanboy's Cookiemonster List**](https://www.fanboy.co.nz/fanboy-cookiemonster.txt)" instead the list you mentioned.

Reporting Issues at https://github.com/ryanbr/fanboy-adblock/issues

**Comment by Atavic** [comment]
THere's ana active [fork](https://gitlab.com/isaakm/Custom-Prebake/tree/master).

**Comment by gorhill** [comment]
Are all filters in Prebake list also found in Cookiemonster list?

**Comment by gorhill** [comment]
Ok I will add Fanboy's Cookiemonster's List, but this will have to wait for the next version, I want to create a new subgroup, "Annoyances", and this requires enough changes that this would keep delaying the current release candidates.

**Comment by Snapy** [comment]
@gorhill Issue can be closed I suppose.
