### ISSUE TITLE
Vidora on wsj.com

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uAssets#3421]
### URL(s) where the issue occurs

`https://www.wsj.com/video/`

### Describe the issue

Peter Lowe blocks `vidora.com`. Videos at wsj.com want to XHR to vidora for some sort of validation.

Videos play fine with vidora blocked, but I get about twice the CPU churn on Firefox. So I've unblocked these XHRs to be kind to my gear.

I also wonder if a +js could get rid of the churn with them blocked. But I'm not enough of a JS wizard to try this myself.

### Versions

- Browser/version: Firefox 60.1
- uBlock Origin version: 1.16.21b4

**Comment by okiehsch** [comment]
I can't reproduce any difference regarding the CPU churn with Firefox 62 on my end.

**Comment by mapx-** [comment]
me neither

**Comment by joey04** [comment]
Thanks for taking a look at it. I'll close it since you can't repro. Since nothing's truly broken, I'll just continue unblocking.

And since this is my first time posting here, a big thank you to the entire team that maintains these lists. Some of these rules make a huge difference!
