### ISSUE TITLE
searchftps.net

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#3422]
### URL(s) where the issue occurs

`https://www.searchftps.net/`

Search for "test" then open a download page.

### Describe the issue

"Error showing ads" message instead of actual download link.

### Versions

- Browser/version: 62.0 (64-bit)
- uBlock Origin version: uBlock Origin 1.16.20

**Comment by adranger** [comment]
I'm still getting the same error using a clean Firefox profile and the default uBlock Origin settings.

**Comment by mapx-** [comment]
after installing in a new profile did you force update all the lists ?

**Comment by adranger** [comment]
Ah, I have `googlesyndication.com` blocked in my hosts file. Isn't there any way to fool this function not to have to whitelist the ads?

     if ($('iframe[width="336"][height="280"]').length !== 0) {
