### ISSUE TITLE
Spotify ads are playing since today

### ISSUE THREAD

**Issue by mrsamse** [uBlockOrigin/uAssets#3424]
### URL(s) where the issue occurs
https://open.spotify.com/browse/featured

### Describe the issue
Spotify ads are playing since today (07.09.2018)

### Versions
- Browser/version: Chrome under windows (69.0.3497.81)
- uBlock Origin version: 1.16.18

### Settings
No changes from the default settings.

### Notes
URL from where the Ad is loaded: https://audio-ak-spotify-com.akamaized.net/audio/3294ed283d0d7583fb1cf412c939c1ef59278453

**Comment by mapx-** [comment]
try
`||audio-ak-spotify-com.akamaized.net$media,redirect=noopmp3-0.1s,domain=spotify.com`
