### ISSUE TITLE
Missed popup on rarbgprx.org

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#3426]
### URL(s) where the issue occurs

`https://rarbgprx.org`

### Describe the issue

A first click anywhere on the page just opens a popup and does nothing else. After that initial click, all links on the site work normally for rest of the session. After a while or clearing cookies or re-opening browser, the cycle repeats where nothing happens until the initial click registers a successful popup.

### Versions

- Browser/version: Firefox 62.0
- uBlock Origin version: 1.16.20

### Notes

The initial popup status is possibly stored in a cookie. If page finds it, nothing unusual happens. If it doesn't, then the first click anywhere on the page triggers that popup and no link works until that happens.

Enabling the `Click to block all popups on this site` option in uBlock Origin gets rid of the popup by automatically closing it.

**Comment by in4u** [comment]
On every individual torrent page (under Torrents section or any category), there's a VPN ad (`rarbgprx.org##tr:has(>.header2:has-text(VPN:))`) just below the torrent download link.

**Comment by in4u** [comment]
They just changed `VPN:` to `VPN :` so the filter no longer works.

**Comment by mapx-** [comment]
They will keep changing, so nothing to do
use
`rarbg.is,rarbg.to,rarbgget.org,rarbgprx.org,rarbgto.org,rarbg.unblockall.org,rarbg.unblocked.kim,rarbgaccess.org,rarbgdata.org,rarbggo.org,rarbgmirror.*,rarbgproxy.*,rarbgunblock.*,rarbgweb.org##.lista > tbody > tr:has-text(/vpn/i)`

**Comment by mapx-** [comment]
They are receiving notifications on threads like this one or on commits ... like every other user

**Comment by in4u** [comment]
That VPN ad is back.

**Comment by mapx-** [comment]
`proxyrarbg.*,rarbg.is,rarbg.to,rarbgget.org,rarbgprx.org,rarbgto.org,rarbg.unblockall.org,rarbg.unblocked.kim,rarbgaccess.org,rarbgdata.org,rarbggo.org,rarbgmirror.*,rarbgmirrored.org,rarbgproxy.*,rarbgunblock.*,rarbgweb.org##.lista > tbody > tr:has-text(/v\s{1,}p\s{1,}n/i)`
