### ISSUE TITLE
gry.pl

### ISSUE THREAD

**Issue by Humberd** [uBlockOrigin/uAssets#343]
### Describe the issue

I've just installed uBlock origin on my Chrome browser and I can't find a way to remove anti-adblock script from a gaming site. I can't just remove the element from DOM, because the script removed all CSS files from the site and I somehow need to block the script before its execution.

### One or more specific URLs where the issue occurs

[http://www.gry.pl/gra/1001-arabian-nights-7](http://www.gry.pl/gra/1001-arabian-nights-7)

### Screenshot in which the issue can be seen

It's in Polish, but it says that we have an adblock on and we should turn it off.

![image](https://cloud.githubusercontent.com/assets/10242142/24578450/6b9ccb92-1695-11e7-8294-b227258cc56b.png)

### Steps for anyone to reproduce the issue

1. Go on the site provided above.

### Your settings

- Browser/version: Chrome - 49.0.2623.112 m
- uBlock Origin version: 1.11.4
- operating system: Windows XP

##### Your filter lists

Default filter list + Anti-Adblock Killer | Reek

##### Your custom filters (if any)

none

**Comment by uBlock-user** [comment]
add `||flakyfeast.com^`

**Comment by SMed79** [comment]
Other used domains https://bpaste.net/raw/6f4cbc21d74c

Alternative filter:

`/.*[a-z0-9]{130,}/$script,third-party,domain=www.gry.pl`

**Comment by okiehsch** [comment]
Fixed in https://github.com/MajkiIT/polish-ads-filter/commit/a99350907537502722c9423cb7d941f710a340d9
