### ISSUE TITLE
canberratimes.com.au -- ad/fingerprinting script reinjection

### ISSUE THREAD

**Issue by mistral-0** [uBlockOrigin/uAssets#3431]
### URL(s) where the issue occurs

`https://www.canberratimes.com.au/politics/federal/chinese-international-students-take-on-major-parties-at-universities-20180905-p50222.html`
`https://www.canberratimes.com.au/world/north-america/for-two-years-australia-has-been-without-a-us-ambassador-but-that-may-not-be-a-bad-thing-20180907-p502bt.html`

### Describe the issue

While running uBlock Origin on Chrome with uBlock Origin Extra, ads, browser fingerprinting scripts, and other scripts/blocked assets are reinjected into the page.

### Versions

- Browser/version: Chrome stable, 69.0.3497.81 on macOS
- uBlock Origin version: 1.16.18
- uBO Extra version: 2.76

### Settings

- WebRTC leak prevention has been enabled
- No other lists have been added

### Notes

Large quantities of web requests (including the blocked assets) are made following the pattern `canberratimes.com.au/cxresources/<long string of encoded something>`, with very few "regular" requests being made, these are mostly for CSS and font files when they are.

The server identifies itself as 'CX/NGINX'.

Script tags with randomly named attributes are inserted into the page. The name of this attribute changes whenever the page reloads. The `src` attribute points to a long encoded URL as described above, with the randomly named attribute containing a relative path to what is likely the script's original path. Example:
```
<script src="https://www.canberratimes.com.au/cxresources/[removed]" teh6="/assets/vendorReactReduxRelay.a074861c0f86273562a9.js"></script>
```

Reinserted ads are contained within iFrames that have a `data-integralas-id-{UUID}` attribute (example: `data-integralas-id-ebec326a-cd38-47e4-89cb-dde072acf705`) with no value set.

Link targets are also rewritten to use the cxresources path, and when clicked will take the user to a page with obfuscated JavaScript that uses location.replace on a timeout to direct the browser to the real target.

Trying to find out who makes this particular ad injection product hasn't been very fruitful either, googling various combinations of 'CX' with ad-related terms doesn't yield overly much besides analytics stuff.

This particular site uses Akamai for its CDN.

**Comment by lassekongo83** [comment]
Only getting ad reinsertion in Chromium, not Firefox.
To get rid of the ads: `canberratimes.com.au##script:inject(set-constant.js, cxStartDetectionProcess, noopFunc)`
Still a lot of bloat and tracking on the page though.

**Comment by okiehsch** [comment]
Thanks, the filters I tried all got rid of the ad-reinsertion but also broke site functionality.
Your filter is the best fix possible at the moment in my opinion.
