### ISSUE TITLE
golem.de.js script breaks web.de/gmx.net Online Office application

### ISSUE THREAD

**Issue by alessioalex** [uBlockOrigin/uAssets#3438]
### web.de / gmx.net

Make a web.de / gmx.net account. Login, then click on 'mehr' (it means 'more' in English), the last icon in the top toolbar. Then click on 'Online Office' (first left item in the newly displayed menu on top, has a 'beta' icon attached to it). 

### Describe the issue

Click on the 'abc' icon in the top left menu to create an Online Office word document. That document will be saved into the user storage ('Online-Speicher') and it will open for editing. Click on the 'x' icon that appears when you hover the document name in the left menu to close it. Now click on 'Aus Online-Speicher' for the file dialog to open, go to 'Meine Office Dateien' and try to reopen it.

There are 2 issues that happen if the `golem.de.js` script is included in the page:

1) A client needs to click multiple times on 'Aus Online-Speicher' and wait a couple of seconds for the 'File browse' dialog to open (if at all).

2) Upon selecting a file from the dialog the document does not open for editing.

### Screenshot(s)

-

### Versions

- Browser/version: Version 68.0.3440.84 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin development build 1.16.21.7

Note: happens on Firefox/Chrome for the latest ublock versions.

### Settings

default

### Notes

- Removed web.de and gmx.net from the following 2 lines in `filters.txt`: https://github.com/uBlockOrigin/uAssets/blob/f7e08c65c536a1ffd569e38e384e0fd1c9ade7e4/filters/filters.txt#L541-L542

Upon removal the application works as expected, people can browse the documents from their web.de storage ('Online-Speicher') and open them for editing.

**Comment by okiehsch** [comment]
Thanks for reporting, I can reproduce and will remove the entries.
