### ISSUE TITLE
getrelax.club [Anti-Adblock][NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3442]
URL(s) where the issue occurs

`http://getrelax.club/%E6%90%9C%E5%B0%8B_JAV/54154/GetRelax_KTRA-061+%E3%83%AD%E3%82%B1%E3%83%83%E3%83%88%E7%88%86%E4%B9%B3%E5%A6%B9+%E4%B8%AD%E5%87%BA%E3%81%97%E5%A4%A9%E5%9B%BD+%E9%80%A2%E5%92%B2%E3%82%86%E3%81%82`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
it seems fixed in regional lists
