### ISSUE TITLE
over-blocking Facebook posts with 'Suggested Post' anywhere in post or comment

### ISSUE THREAD

**Issue by filbo** [uBlockOrigin/uAssets#3445]
### URL(s) where the issue occurs

`https://facebook.com/socialfixer/posts/10156114476389342`

### Describe the issue

Expression `facebook.com,facebookcorewwwi.onion##.userContentWrapper:has-text(/Suggested Post/i)` is far too broad and wipes out posts _discussing_ ad posts.  The above URL is just one such example.

TO REPRODUCE:

(1) open the above URL.  Facebook account not required; click 'Not Now' on the splash screen.

(2) post does not disappear until comments have been opened.  FB sometimes pre-opens comments, sometimes does not.  If not, click the '270 Comments' part of the '605 Likes 270 Comments 68 Shares' grey line at the bottom.

(3) post disappears.

(4) this particular example is a post dated 'June 21', starting with the words 'An update to Social Fixer is now available!'.  I mention this because if you _are_ logged in to FB, they will send you a page with multiple posts in it, the second of which does not have the trigger words and does not disappear.  So the page will 'look normal' but you'll see 'May 23 · An update to Social Fixer is coming soon...' -- if you see that, uBO **has** disappeared the intended post; you've reproduced the problem.

### Screenshot(s)

1. Top of page upon visiting the URL in 'Incognito Mode' (therefore, no FB login token, I see a guest view).  (NOTE: browser's extension manager must have been instructed to allow uBO in Incognito; else, in normal mode, log out of FB first.  Or not, but you'll see different images.)

![ubo-1](https://user-images.githubusercontent.com/3022180/45464691-95ee4380-b6c6-11e8-8398-ba497738d86a.png)

2. After scrolling to the bottom of the post; the button I am about to click is circled in green.

![ubo-2](https://user-images.githubusercontent.com/3022180/45464714-b3231200-b6c6-11e8-8c93-a24987835bd2.png)

3. After clicking the '270 Comments' to load (some of) the comments.  Post has disappeared, leaving a blank FB UI.

![ubo-3](https://user-images.githubusercontent.com/3022180/45464751-d352d100-b6c6-11e8-8ac0-604c6651bace.png)

### Versions (not actually relevant)

- Browser/version: opera-developer/57.0.3065.0
- uBlock Origin version: v1.16.16

### Settings

- no changes needed; 'uBlock filters' must be enabled (which I believe is default), as the problem is there

### Notes

- verified that disabling 'uBlock filters' fixes it
- verified that with 'uBlock filters' disabled, adding the problem expression `facebook.com,facebookcorewwwi.onion##.userContentWrapper:has-text(/Suggested Post/i)` to 'My filters' brings the problem back
- I use this significantly more specific filter without problem in a different filtering venue (a Social Fixer post filter): `".userContentWrapper>div div>span>span:contains(^Suggested Post$)"`
- this, and any other FB post-filtering expression, should be wrapped in `[id^="hyperfeed_story_id_"]:if( ... )`.  In fact, I would regularize the following expressions (but note, I have not tested them):
```
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:if(h6:has-text(People You May Know))
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:has(span._4dcu)
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:if([id^="feed_subtitle_"] a[href]:matches-css-after(content:/Gesponsert|Sponsored|Sponsrad/))
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:has(a[href*="[is_sponsored]"])
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:if(.userContentWrapper:has(a[href*="/ads/"]))
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:if(.userContentWrapper>div div>span>span:has-text(^Suggested Post$))
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:has(a[href*="client_token"])
facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:has(a[href*="utm_campaign"])
! REMOVE, this is obsolete and would be removing all normal posts if FB hadn't stopped using ID 'substream_1'
! facebook.com,facebookcorewwwi.onion###substream_1:has([id^="feed_subtitle_"]:has-text(Sp))
```
Also, is there a performance benefit to combining things like:

`facebook.com,facebookcorewwwi.onion###stream_pagelet [id^="hyperfeed_story_id_"]:has(a[href*="[is_sponsored]"], a[href*="client_token"], a[href*="utm_campaign"])`

?

**Comment by filbo** [comment]
Note: adding

`facebook.com,facebookcorewwwi.onion##.userContentWrapper:has-text(/Suggested Post/i)`**,badfilter**

to 'My filters' does not fix this.  I thought 'identical expression,badfilter' was supposed to override?

**Comment by kowith337** [comment]
The `$badfilter` can only apply on network filtering, please use `#@#` to apply DOM whitelisting, e.g. `#@#div`, `#@##idname` or `#@#.classname`

**Comment by filbo** [comment]
Where is '#@#' documented?  Can it cancel out an entire complex rule like `facebook.com,facebookcorewwwi.onion##.userContentWrapper:has-text(/Suggested Post/i` ?  I certainly would not want to whitelist '.userContentWrapper', as that would cancel out all the other uBlock facebook post filters.

**Comment by mapx-** [comment]
https://adblockplus.org/en/filters#elemhide_exceptions

**Comment by mapx-** [comment]
You can whitelist exactly the same cosmetic filter (entirely matched)
