### ISSUE TITLE
FYI   NSFW popups/redirects  based on gibberish URLs

### ISSUE THREAD

**Issue by greypowerOz** [uBlockOrigin/uAssets#3446]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://azmovies.xyz/watch.php?title=Sicario%3A+Day+of+the+Soldado]`

### Describe the issue

[NSFW popups/redirects  based on gibberish URL lilke http://dnckawxatc.com/s29isxbbr?wsk=31&refer=https%3A%2F%2Fazmovies.xyz%2F&kw=%5B%22watch%22%2C%22full%22%2C%22movies%22%2C%22and%22%2C%22tv%22%2C%22series%22%2C%22in%22%2C%221080p%22%2C%22for%22%2C%22free%22%2C%22az%22%2C%22movies%22%5D&key=ee1587ee4e8065e7eebb634762fc402a&scrWidth=1920&scrHeight=1080&tz=10&ship=&pst=&res=4.31&dev=r&adb=y ]

I can add manual filters but the core problem is probably the random / stupid domain names.....  

### Versions

- Browser/version: [chrome 69.0.3497.81 ]
- uBlock Origin version: [uBlock Origin v1.16.18]

**Comment by okiehsch** [comment]
I can't reproduce any redirection.
How do you trigger the redirection on your end?

**Comment by mapx-** [comment]
me neither

**Comment by ghajini** [comment]
On going home page 
`https://azmovies.xyz`
Click on any movie , you will be bombarded with random popups one after another

Firefox Android 62
Ublock origin stable
