### ISSUE TITLE
deezer.com

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#3447]
### URL(s) where the issue occurs
For example: `https://www.deezer.com/pl/playlist/1283499335`

### Describe the issue
Just sing in and play some music, then close tab and you will see dialog box that asks for confirmation leaving page.

### Screenshot(s)
![screenshot_20180913_172302](https://user-images.githubusercontent.com/19818572/45498116-b0352980-b779-11e8-8d0d-20399c9fbd3c.png)

### Versions

- Browser/version: Vivaldi 1.15.1147.64

- uBlock Origin version: 1.16.20

### Settings

- ![screenshot_20180913_172516](https://user-images.githubusercontent.com/19818572/45498273-0013f080-b77a-11e8-916a-bb13b0b29970.png)

**Comment by hawkeye116477** [comment]
@mapx- Yes

**Comment by mapx-** [comment]
test this filter
`deezer.com##+js(abort-on-property-write.js, onbeforeunload)`

**Comment by hawkeye116477** [comment]
@mapx- Thanks, works :smile:.

**Comment by cubedj** [comment]
this filter breaks modal dialogs for sharing among some others.. not as big problem but It seems to me that rectifying one annoyance created another much more annoying..

**Comment by mapx-** [comment]
@hawkeye116477  it seems you have to keep it as custom filter, I removed it from the list

**Comment by hawkeye116477** [comment]
@mapx- If i change write to read, then it seems to work properly (modal dialogs for sharing).
`deezer.com##+js(abort-on-property-read.js, onbeforeunload)`

**Comment by mapx-** [comment]
@cubedj  could you confirm the fix @hawkeye116477 proposed above ?
