### ISSUE TITLE
platinmods.com [Anti-Adblock]

### ISSUE THREAD

**Issue by jay33721** [uBlockOrigin/uAssets#3460]
### URL(s) where the issue occurs

https://platinmods.com/

### Describe the issue

An anti-adblock message appears after a short delay when loading the page, preventing any interaction with the page.

### Versions

- Browser/version: Firefox 62.0 (64-bit)
- uBlock Origin version: 1.16.20

**Comment by okiehsch** [comment]
Already [fixed](https://github.com/uBlockOrigin/uAssets/commit/e85c2e3bcc053de452df37189e461664de6a0b15), update your `uBO-filter` list.
