### ISSUE TITLE
watchcartoononline.io ads

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#3464]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
https://www.watchcartoononline.io/
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
Ads appear on both sides of the page.
[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions
Firefox quantum 62.0
- Browser/version: [here]
- uBlock Origin version: [here]
1.16.20
### Settings
default
- [List here all the changes you made to uBO's default settings]

### Notes
I've tried blocking the ads with the element picker, however whenever you change pages or refresh, you just get a new set of ads.
[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
update ublock filters and test again (it was already fixed)

**Comment by rmcin329** [comment]
I tried updating filters and trying again before i made this topic.

**Comment by rmcin329** [comment]
That works great, thanks!
