### ISSUE TITLE
transfermarkt.de

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#347]
Hi, 

**URL**

- `http://www.transfermarkt.de/wettbewerbe/europa`

**Describe the issue**

- Anti adblock.

**Screenshot**

- http://i.imgur.com/675k6GP.png

### Versions

- Browser/version: FF / 52.02
- uBlock Origin version: v1.11.5rc6

**Settings**

Default settings + EasyList Germany

**Fix**

`transfermarkt.de##script:contains(_abpuser_)`

**Source**

- https://github.com/reek/anti-adblock-killer/issues/2434
- https://forums.lanik.us/viewtopic.php?f=90&t=34153

**Comment by okiehsch** [comment]
The filter `@@||tmssl.akamaized.net//ads/ads.js` which is proposed in your sources works for both
Chrome and Firefox on my end, so I think that would be preferable.
@gorhill what is your view about `script:contains` in this case?
I tried a redirect of `tmssl.akamaized.net//ads/ads.js` but that doesn't work for me, I still get the
Anti-Adblock message

**Comment by gorhill** [comment]
Does this work?

    transfermarkt.de##script:inject(abort-on-property-read.js, _abpuser_)

**Comment by okiehsch** [comment]
No, I tried that one already.

**Comment by gorhill** [comment]
How about `transfermarkt.de##body > div[id]:has(a[href^="/intern/adblock"])`?

**Comment by okiehsch** [comment]
That one works with both Chrome and Firefox, thx.
Will you add it? I have some technical issues at the moment.
