### ISSUE TITLE
shink.in

### ISSUE THREAD

**Issue by anewuser** [uBlockOrigin/uAssets#348]
### URL(s) where the issue occurs

http://shink.in/Ti9kB

### Describe the issue

Anti-adblock message replaces captcha/continue button.

### Versions

- Browser/version:  Firefox 51.0.1
- uBlock Origin version: 1.11.4

**Comment by lain566** [comment]
The captcha is broken
`https://shon.xyz/RdEPQ`

**Comment by mapx-** [comment]
no issue for me

**Comment by lain566** [comment]
Try again in incognito mode on Chrome.

**Comment by lain566** [comment]
There's a popup when clicked on `Get Link`
