### ISSUE TITLE
Ads on google.com visible in mobile Firefox/Android

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#3482]
### URL(s) where the issue occurs

`google.com`

### Describe the issue

Ads are visible in the search results page but only in private browsing mode of Firefox for Android. No such issue in the regular (non-private) mode.

### Screenshot(s)

In the screenshot below, left hand column shows regular mode and right hand column shows private browsing mode of Firefox for Android.

![ss](https://user-images.githubusercontent.com/43062185/45581827-2ee9ae00-b8c3-11e8-8100-b49640ade6af.jpg)

### Versions

- Browser/version: Firefox for Android 62.0
- uBlock Origin version: 1.16.20

### Settings

Default

### Notes

Google is serving different layouts in regular and private browsing mode of Firefox/Android. Changing the user agent to Chrome/Android fetches another different but uniform layout in both modes where the ads remain blocked.

**Comment by gwarser** [comment]
Nothing to do with private browsing. You see two different pages. Google served old page to Firefox on Android for long time. Now Firefox is sending different user agent to Google search page to get new Chrome-like ("bubbles") interface and wee don't have cosmetic filters for this new interface yet.

**Comment by gwarser** [comment]
Go to uBO Settings -> Filter lists, and remove selection from "Ignore generic cosmetic filters" checkbox.

**Comment by gwarser** [comment]
I cannot "pick" good filter on Android - nth of type + random classes only :(

**Comment by in4u** [comment]
@uBlock-user I believe @gwarser is on the right track. My limited research tells me that Google notoriously serves [inferior](https://bugzilla.mozilla.org/show_bug.cgi?id=975444) user experience on Firefox for Android. [Recently](https://www.reddit.com/r/firefox/comments/9fxk4p/we_did_boys_firefox_android_finally_shows_googles/) there's been some change where either Firefox is spoofing new user agent in private browsing mode to bypass Google's game or perhaps Google is rolling out new layout or both IDK.

@gwarser Enabling or disabling "Ignore generic cosmetic filters" option doesn't seem to make any noticeable difference in my case, ads remain unblocked regardless of this setting. As of now, my only resolution is to keep Chrome/Android as UA for Google. Hoping for new ad filters to come up and be incorporated in uBO soon!

**Comment by gwarser** [comment]
`google.*##div[data-hveid]`?

**Comment by gwarser** [comment]
I just checked and UA is not spoofed on Firefox Android. On my phone I see `Mozilla/5.0 (Android 7.1.2; Mobile; rv:63.0) Gecko/63.0 Firefox/63.0` When I copy this exact UA to "Custom Device" in Firefox Responsive Design Mode, then I see exact same source on desktop browser.

**Comment by gwarser** [comment]
How about:

```
!#if env_mobile
google.*##div[data-hveid]
!#endif
```

**Comment by okiehsch** [comment]
Works with setting the UA to android using Chrome on my end.
I do not have a device running android, so somebody who does is better equipped to test and add a fix.

**Comment by in4u** [comment]
Same result with the updated filter. It works for Firefox/Android but switching the UA to Chrome/Android, Safari/iPhone or Safari/iPad, hides all the search results.

**Comment by krystian3w** [comment]
`google.*##div[data-hveid]:has([class=" "])` :question: 


only from this can the second "WP.pl" leave, that after just one week someone will notice something wrong cut.

**Comment by in4u** [comment]
@krystian3w I tested both your filters separately. First one has the same problem that @gwarser's filter had - it works in Firefox/Android but hides all search results in many other cases like Chrome/Android, Safari/iPhone, etc. The second filter was working fine until I noticed an ad sneaking past due to its `data-hveid` starting from "CB" instead of "CA".

In all ads, one constant seems to be a `span` element with the text "Ad". I am not sure but maybe some filter targeting `data-hveid` containing this particular `span` element might just do the trick?

**Comment by krystian3w** [comment]
Find text "Ad" in e.g. `<span>` will be good for only English interface.


It's a pity that this class is so dynamic or spoils the site with more powerful masking as Chrome / iOS Safari.

**Comment by in4u** [comment]
Okay guys, I did a little investigation by spoofing the user agent and here's what I found...

**Following is the Tier 1 layout (received by mobile Chrome, Safari, etc.):**

![t1](https://user-images.githubusercontent.com/43062185/45987917-a244aa00-c091-11e8-8e30-f2ec5161ec01.PNG)

All the search results, including ads, are a few levels deep within the highlighted `div` and each of them has `div[data-hveid]`.

**Following is the Tier 2 layout (received by mobile Firefox):**

![t2](https://user-images.githubusercontent.com/43062185/45987927-aa044e80-c091-11e8-9eba-a1a8bfed13ff.PNG)

All the search results, including ads, are children of `div[id="main"]`. But only the ads have `div[data-hveid]` and not the search results.

***

Based on this, I tested the filter `google.*###main > div[data-hveid]` and it seems to do the job without any adverse side effects, i.e. ads get blocked on Firefox and rest of the browsers remain unaffected. I haven't actually tested this in real browsers other than Firefox (just UA spoofing) so there's that.

Now, would all this info be of any help in creating an efficient filter?

**Comment by krystian3w** [comment]
For me works in Firefox Android "`###main > div[data-hveid]`" no affect with desktop version.

But change UA to Chrome 59 & Safarii 11 (I know old version) no have this ad witout use new rule.

**Comment by in4u** [comment]
Ah, alright @krystian3w. Let's see if this filter works for others too without causing any trouble. No problems highlighted by anyone so far, maybe this issue will be closed soon.

**Comment by ZaphodBeebblebrox** [comment]
Given that nothing else seems to be happening on this issue I am considering adding 
```
!#if env_firefox
!#if env_mobile
google.*###main > div[data-hveid]
!#endif
!#endif
```
Does anyone have problems with this?

**Comment by okiehsch** [comment]
Has the issue been fixed by the commit?

**Comment by in4u** [comment]
Well, nobody is coming forward with any problem with this filter. I guess you guys should close the issue and re-open it later if someone does highlight a problem.

**Comment by ZaphodBeebblebrox** [comment]
Does the filter `google.*###main > div[data-hveid]:if-not(span.spell_orig)` work for you? I do not have an android phone, so I cannot test it myself.

**Comment by krystian3w** [comment]
@ZaphodBeebblebrox 

Nope, still cut "improving spellchecker/typo" - I can not find `span.spell_orig` / `.spell_orig`.

`google.*###main > div[data-hveid]:has(span)` **no** cut "improving spellchecker/typo"  - in `<span>`, advert links  have label "<kbd>ad</kbd>".

**Comment by krystian3w** [comment]
@in4u  I think I have to test it, mine started `###main > div[data-hveid]:has(span)` to cut it to much.

**Comment by in4u** [comment]
@krystian3w Yes, do let us know if `google.*###main > div[data-hveid]:if-not(a[href^="/search"])` works for you without causing any other trouble.

@ZaphodBeebblebrox The old filter is inadvertently hiding typo-related suggestions. Can you please re-open this issue until a new acceptable solution is found?

**Comment by krystian3w** [comment]
For my your rule works good, cut only ad search results.

**Comment by gwarser** [comment]
Both looks good, both hide this:


![screenshot_20181027-012920](https://user-images.githubusercontent.com/886325/47596916-4750ec00-d98a-11e8-998d-fbc0cd6854cf.png)

**Comment by in4u** [comment]
@krystian3w @gwarser I noticed not only typo-related suggestions but "Top stories", "Popular on Twitter", etc. sections are also getting hidden. Meanwhile the ads seem to have their link href along the lines of `<google domain>/aclk?...` while also having a new attribute `data-al`. So, I guess our ad blocking approach needs to be changed so as to not hide genuine content.

I tried the following two filters separately:

`google.*###main > div[data-hveid]:has(a[href*="/aclk?"])`

`google.*###main > div[data-hveid]:has(a[data-al])`

Both seem to just block ads without affecting anything else. Can you guys test whether an ad gets through and/or some genuine content gets hidden with any of these filters?

**Comment by kulfoon** [comment]
> 
> 
> I don't have an android phone, so I can't test myself.

Do you really need one? https://www.digitalcitizen.life/emulate-mobile-device-desktop-browser

**Comment by ZaphodBeebblebrox** [comment]
Ok, I was able to test with a combination of responsive design mode and a user agent spoofer. Does `google.*##:xpath(//span[text()="Ad"]//..//..//..//..)` cause any problems for you?

**Comment by krystian3w** [comment]
No works with other languages... report to any regional list?

**Comment by in4u** [comment]
@ZaphodBeebblebrox Unfortunately, that filter would not work on non-English languages. What is your feedback on the two filters I listed earlier?

**Comment by krystian3w** [comment]
> feedback on the two filters I listed earlier?

I do not have section latest articles in search results - who find in Google to show this element?

**Comment by in4u** [comment]
@krystian3w Try searching for "iPhone". It shows "Top stories" section in the search results. On one occasion, I also found "Popular on Twitter" feeds section on the same search results page but could not reproduce it (seems random).

**Comment by krystian3w** [comment]
For me, your rules no cut "latest articles" / "top stories" about iPhone and no cut "Showing results for" / "Search instead for".

**Comment by ZaphodBeebblebrox** [comment]
`google.*###main > div[data-hveid]:has(a[data-al])` appears to work for me as well. Let us know if you have any problems with it.

**Comment by in4u** [comment]
Hey guys, two issues:

1. `Easylist` has this `div#main > div.ZINbbc.xpd.O9g5cc.uUPGi` rule for many Google domains which is breaking the search results page on Firefox for Android. Sections like typo-related suggestions, what people ask, etc. are also getting blocked due to this rule.

2. The conditional rule last added by @ZaphodBeebblebrox needs to be updated where `google.*###main > div[data-hveid]:has(a[data-al])` should possibly be replaced by `google.*###main > div.ZINbbc.xpd.O9g5cc.uUPGi:has(a[data-al])`.

If `Easylist`'s rule in [1] is badfiltered and the one in [2] above is implemented then I think there should not be any issues. Maybe others can highlight any potential breakages and/or come up with a better solution.

**Comment by mapx-** [comment]
Does the filter in [1] breaks something on desktop ? 
Why the change of [2] ?

**Comment by mapx-** [comment]
@ryanbr

**Comment by in4u** [comment]
I have not experienced any breakage with [1] on desktop.

The change of [2] maybe required since I no longer see `div[data-hveid]` but only `div.ZINbbc.xpd.O9g5cc.uUPGi`. Perhaps Google modified their code.

**Comment by mapx-** [comment]
Could you test on mobile:
```
!#if env_mobile
google.*#@#div#main > div.ZINbbc.xpd.O9g5cc.uUPGi
!#endif
```

**Comment by in4u** [comment]
No dice. Breakage is still there on Firefox for Android.

**Comment by mapx-** [comment]
Did you test on a mobile device or only using a desktop simulator ?

**Comment by in4u** [comment]
Both.

**Comment by in4u** [comment]
Okay, after digging around a bit more I think `google.*##a[href*="/aclk?"][data-al]:xpath(../..)` could be a safe rule. It can be wrapped in a conditional mobile directive but it's not really required.

This combined with the `Easylist` exception rule by @mapx- suggested [here](https://github.com/uBlockOrigin/uAssets/issues/3482#issuecomment-589969771) should block just the ads without breaking anything.

It will also eliminate the need for two currently existing rules - [this](https://github.com/uBlockOrigin/uAssets/blob/47672d80f82b5e049c4e35192e2b83ed6d6f1faf/filters/filters.txt#L17580) and [[2]](https://github.com/uBlockOrigin/uAssets/issues/3482#issuecomment-589966985) above.

**Comment by mapx-** [comment]
check again with the last filters

**Comment by mapx-** [comment]
I used `:nth-ancestor(2)` for `:xpath(../..)`

**Comment by in4u** [comment]
Works great! Ads blocked. Nothing broken. Now waiting for the Adguard team to fix their rule.

**Comment by in4u** [comment]
@mapx- You can remove the exception rule now that the concerned filter has been taken off `Easylist`.

**Comment by yaakovfeldman** [comment]
I may have the same issue. On Firefox Android I see 2 ads without ublock and 1 with it on. 

I have unsuccessfully attempted to use the rules above but I may have applied them wrong - I don't understand which comments above are still current. 

![Screenshot_20200310-133042_Firefox](https://user-images.githubusercontent.com/17687145/76317250-cde24100-62d3-11ea-99b9-b258e504bd6b.jpg)

![Screenshot_20200310-133016_Firefox](https://user-images.githubusercontent.com/17687145/76317260-d20e5e80-62d3-11ea-8a73-90d61e8ca063.jpg)

**Comment by in4u** [comment]
Hey @mapx-, perhaps you should modify this filter to replace `:nth-ancestor` with `:upward` as per the deprecation [note](https://github.com/gorhill/uBlock/commit/72bb70056843024b1a31fe1ab9c90bd4e8260ba2) in uBO's latest release.

**Comment by uBlock-user** [comment]
Everyone's not updated to the latest stable release.

**Comment by in4u** [comment]
Oh, right. Didn't realize that!
