### ISSUE TITLE
uMatrix: Ruleset recipes: WikiMedia-Project websites

### ISSUE THREAD

**Issue by TriMoon** [uBlockOrigin/uAssets#3485]
Since uMatrix nowerdays supports Ruleset recipes, here is what i made to allow access to all **WikiMedia-Project website** resources **globally**.

- [WikiMedia.urr](https://github.com/TriMoon-Inc/uMatrix-Ruleset-recipes/blob/master/WikiMedia.urr)

**Comment by okiehsch** [comment]
@TriMoon  You can open a pull request and ping **gorhill** if you think your recipe should be added to https://github.com/uBlockOrigin/uAssets/blob/master/recipes/recipes_en.txt

Other than that there is nothing to fix or add here as none of the maintainers actually use uMatrix as far as I know.
