### ISSUE TITLE
identi.li

### ISSUE THREAD

**Issue by ali2134** [uBlockOrigin/uAssets#3493]
ubo doesn't allow me click on "accede" this is for login, any fix please
uBlock Origin v1.16.18
69.0.3497.92 (64 bits)

**Comment by KiLL4FuNK** [comment]
I hope that ublock fixes it because  @diaux 
do not show up more months ago

the problem is in the easylistspanish list

> https://github.com/uBlockOrigin/uAssets/issues/1268

**Comment by okiehsch** [comment]
`@@||musicatorrents.com/wp-content/themes/Alexis/js/script.js$script,domain=identi.li`
seems to work on my end, but I have to reload a few times before clicking "accede" works.

**Comment by ali2134** [comment]
i tested in a clean browser, something is wrong, worked long time ago, when i added a filter, i am using a browser recently installed, filters updated and not works

**Comment by KiLL4FuNK** [comment]
It works well

`@@||musicatorrents.com/wp-content/themes/Alexis/js/script.js$script,domain=identi.li`

**Comment by ali2134** [comment]
> `@@||musicatorrents.com/wp-content/themes/Alexis/js/script.js$script,domain=identi.li`
> seems to work on my end, but I have to reload a few times before clicking "accede" works.

tested, works, thank you very much

**Comment by okiehsch** [comment]
That can't be helped, see https://github.com/uBlockOrigin/uAssets/issues/1683#issuecomment-371976241
You have to also allow `https://musicatorrents.com/wp-content/themes/Alexis/js/license.js` which would trigger a popup.

**Comment by KiLL4FuNK** [comment]
the filter works fine leave it like this works much better than before

**Comment by ali2134** [comment]
> That can't be helped, see [#1683 (comment)](https://github.com/uBlockOrigin/uAssets/issues/1683#issuecomment-371976241)
> You have to also allow `https://musicatorrents.com/wp-content/themes/Alexis/js/license.js` which would trigger a popup.

looks like it's the only way for works, thanks by reply
@ZaphodBeebblebrox you can close this thread

**Comment by ali2134** [comment]
@okiehsch i just updated my filters, i don't understand you when you say i should allow this: https://musicatorrents.com/wp-content/themes/Alexis/js/license.js

**Comment by okiehsch** [comment]
Add
````
@@||musicatorrents.com/wp-content/themes/Alexis/js/license.js$script,domain=identi.li
||navegacom.com^$popunder
````
to your filter list.

**Comment by ali2134** [comment]
@ZaphodBeebblebrox you can finally close this thread, thank you very much
