### ISSUE TITLE
NSFW FuckAdBlock image sites

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#35]
### URL(s) where the issue occurs

`http://im9.eu/picture/hentai-hq-hentai-and-anime-artwork-66`
`http://random-images-from-imgur.free-forum-or-site.com/`
`http://g9g.eu/`

### Describe the issue

FuckAdBlock is being used here.

### Screenshot(s)

![](https://cloud.githubusercontent.com/assets/16030872/14851239/e388e8ba-0c7e-11e6-9aa4-6e7ac67e8199.png)

### Versions

- Browser/version: Chrome 50
- uBlock Origin version: 1.6.8

### Notes

`! im9.eu`
`||im9.eu*/fa.js$script,redirect=fuckadblock.js-3.2.0`

`! free-forum-or-site.com and g9g.eu`
`||g9g.eu*/fa.js$script,redirect=fuckadblock.js-3.2.0`

**Or:**

`||eu*/fa.js$script,redirect=fuckadblock.js-3.2.0`

**Or:**

`*/fa.js$script,redirect=fuckadblock.js-3.2.0`

Last two might be too broad(?)

**Comment by gorhill** [comment]
Yes last is too broad, as a rule, be fearful of false positives.

First ones are also too broad: why `im9.eu*`?

**Comment by IDKwhattoputhere** [comment]
Didn't know if keeping the port would be a good idea. But I guess there's no reason not to.

**Comment by gorhill** [comment]
My bad, I didn't see the site was using a port. I tried `||im9.eu:*/fa.js` and that did nit work. This needs to be fixed in uBO, definitely an issue.

**Comment by lewisje** [comment]
What about `||im9.eu^*/fa.js`? That's a little more broad, but the purpose of `^` is to represent an arbitrary separator character, just in case this specific anti-ad tech decides to no longer use an explicit port.

**Comment by gorhill** [comment]
> What about `||im9.eu^*/fa.js`?

You are right, using `^` is better, and it works even without the fix (which is still needed).

@IDKwhattoputhere, can you confirm these works for your cases:

    ||im9.eu^*fa.js$script,redirect=fuckadblock.js-3.2.0
    ||g9g.eu^*fa.js$script,redirect=fuckadblock.js-3.2.0

**Comment by IDKwhattoputhere** [comment]
Yes, those work very fine. Good idea, @lewisje.
