### ISSUE TITLE
IMDb - "unbreak" allows calls to amazon

### ISSUE THREAD

**Issue by Procyon-b** [uBlockOrigin/uAssets#3515]
### URL(s) where the issue occurs

`[https://www.imdb.com/tv/canceled-renewed/ls063853872/?ref_=ls_mv_sm]`

### Describe the issue

The page is empty of ads, but an exception filter still allows callbacks to amazon.

### Screenshot(s)

![imdb-b-1](https://user-images.githubusercontent.com/40043075/45646813-b2262200-bac4-11e8-928a-9eaba0aa186e.PNG)

### Versions

- Browser/version: 69.0.3497.92
- uBlock Origin version: 1.16.18

### Notes

The filter is this one.
```
! https://github.com/uBlockOrigin/uAssets/issues/1720
@@||amazon.*^*uedata$image
```

I don't know if this fix (1720) was intended to be this broad: a page with no amazon ads (at least not displayed) calling back amazon...

Also to be noted is the "beacon" connection to amazon (same hostname, see at the top of the screenshot). Should I open a new issue for that one? By the time I write this (8 minutes) I have a total of 20 beacon connections. (I have a personal rule to block it, disabled only for the screenshot)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2f51aed00a33ed8034168bb8fd3b28231084d9b9
