### ISSUE TITLE
Lots of ads on Chicago Tribune

### ISSUE THREAD

**Issue by dandv** [uBlockOrigin/uAssets#3519]
### URL(s) where the issue occurs

`http://www.chicagotribune.com/entertainment/travel/ct-xpm-2014-01-28-sc-trav-0128-travel-mechanic-20140128-story.html`

### Describe the issue

Loading the URL shows ads as if uBlock weren't enabled:

### Screenshot(s)

![image](https://user-images.githubusercontent.com/33569/45710557-cfe29e00-bb3b-11e8-9070-6cb53fb571e4.png)

### Versions

- Browser/version: 69.0.3497.92 (Official Build) (64-bit) and Version 70.0.3538.16 (Official Build) beta (64-bit)
- uBlock Origin version: 1.16.18

### Settings

- Haven't changed anything

### Notes

When opening DevTools, the ads disappear. I found this while trying to take a screenshot of the entire page (including the part below the fold) via DevTools.

**Comment by mapx-** [comment]
Did you install ublock extra ? 
https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco
