### ISSUE TITLE
uBlock blocks disquis comments from loading on Kiss-Asian in Google Chrome

### ISSUE THREAD

**Issue by soysuva** [uBlockOrigin/uAssets#352]
I hope I reported this in the correct section. If this isn't the correct section, then please direct me to correct section.

### URL(s) where the issue occurs
All pages on kissasian with disquis comments.
http://kissasian.com/Drama/Strong-Woman-Do-Bong-Soon/Episode-12?id=33082

### Describe the issue
On Google Chrome, I keep getting this error on Kissasian disqus "**Disqus seems to be taking longer than usual. Reload?**", even though disquis loads fine on other websites. It's also not an internet issue, since I've checked my internet by loading the google homepage and it loaded just fine. I've also tested it without any adblocks and it loaded without any problems. Tried going in incognito mode to see if it worked without any extensions and it also loaded fine. Then I added uBlock Origin to the incognito mode to see if it would load, it stopped loading and gave me the same error again. I also tested it on firefox with uBlock Origin and disquis loaded fine there, just not on chrome.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]
**On Google Chrome with extensions and uBlock Origin:**
<a href="http://imgur.com/R2hZeYq"><img src="http://i.imgur.com/R2hZeYq.png" title="source: imgur.com" /></a>

**In incognito mode - Google Chrome with only uBlock Origin:**
<a href="http://imgur.com/KE43GXy"><img src="http://i.imgur.com/KE43GXy.png" title="source: imgur.com" /></a> 

**In incognito mode - Google Chrome with no extensions:**
<a href="http://imgur.com/cVhZyck"><img src="http://i.imgur.com/cVhZyck.png" title="source: imgur.com" /></a>

**Firefox with uBlock Origin:**
<a href="http://imgur.com/eBSSeEA"><img src="http://i.imgur.com/eBSSeEA.png" title="source: imgur.com" /></a>

**Logs of the page on Google Chrome with extensions:**
<a href="http://imgur.com/OmQEyMA"><img src="http://i.imgur.com/OmQEyMA.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/ZPwXUnl"><img src="http://i.imgur.com/ZPwXUnl.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/6XJuh0F"><img src="http://i.imgur.com/6XJuh0F.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/sBPn9xx"><img src="http://i.imgur.com/sBPn9xx.png" title="source: imgur.com" /></a>

### Versions

- Browser/version: Google Chrome Version 57.0.2987.133 (64-bit), Firefox Version 52.0.2 (32-bit)
- uBlock Origin version: uBlock Origin v1.11.4

### Settings
**I've left most of the settings alone.** 
**3rd party filters:** I've only selected "Anti-Adblock Killer | Reek" script filter and left all the default 3rd party filters alone.
**My filters:** ||kissasian.com/*.aspx
**My rules:** kept it the same when I installed it.
**Whitelist**: kept it the same when I installed it.

### Notes
I added "||kissasian.com/*.aspx" to the filters because videos wouldn't load since the admins of the site added an anti-adblock to make users turn off their adblocks. I tested this without it too and disquis still wouldn't load. Other investigations, I've explained above in description.

**Comment by soysuva** [comment]
EDIT: I've fixed it.

**Comment by SMed79** [comment]
add
`@@||disquscdn.com^$script,domain=destructoid.com`
