### ISSUE TITLE
yts.am 

### ISSUE THREAD

**Issue by ali2134** [uBlockOrigin/uAssets#3523]
`yts.am` i can't see the cloudflare captcha, works with ublock disabled any fix please

uBlock Origin v1.16.18
chrome 69.0.3497.100

**Comment by smed79** [comment]
> Where should you get the captcha ?

https://support.cloudflare.com/hc/en-us/articles/203366080
https://github.com/easylist/easylist/commit/6cf77a025273a29ee7d1d878977457a3c4a820b7#diff-ce6ade6e52352499cfb347f46c329f9fR4922

@ali2134 Post a screenshot of what is blocked in the logger.

**Comment by okiehsch** [comment]
I think he means [cloudflare captcha](https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-).
I can't reproduce, i.e. I don't need to solve a captcha

**Comment by ali2134** [comment]
`https://i.imgur.com/iDvjVX8.png` i hope it helps

**Comment by mapx-** [comment]
No, does not help. I asked you the steps to get the issue.

**Comment by mapx-** [comment]
Tty
```
|http://$script,domain=yts.am,badfilter
|https://$script,domain=yts.am,badfilter
```

**Comment by ali2134** [comment]
fixed, thank you

**Comment by mapx-** [comment]
no popups ? ads ?

**Comment by ali2134** [comment]
@mapx- 
there is an ads "please enable your vpn when downloading torrents" that appears

Maybe this is offtopic but everytime than i visit the site my av detect  JS_Adware.Agent.AA and delete it, maybe someway for stop to load it in ublock?

**Comment by mapx-** [comment]
for vpn add
`yts.am##.ibox-bordered`

**Comment by ali2134** [comment]
added, works

**Comment by okiehsch** [comment]
There is no way to fix the av-detection, your av does not like the part of the inline-script at `yts.am` that triggers a popup. 
That script has been made non functional by a `uBO-filter` so it does not actually do anything with uBO enabled, but it is still there and will be detected.

**Comment by ali2134** [comment]
@okiehsch ok thanks by reply
