### ISSUE TITLE
mangahost-br.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3534]
URL(s) where the issue occurs

`https://mangahost-br.com/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://mangahost2.com/`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7c588afa07ead023aaa0e5ff657eb731d6b5a57d

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://mangahost1.com/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
`https://mangahosted.com`

Anti-Adblock

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://mangahost2.com/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://mangahost2.com/`

**Comment by okiehsch** [comment]
That is the same domain is it not?
