### ISSUE TITLE
TV Tropes has a new anti-adblock.

### ISSUE THREAD

**Issue by weenusboy** [uBlockOrigin/uAssets#3535]
### URL(s) where the issue occurs

tvtropes.org

### Describe the issue

Every time one opens a new page, a pop-up appears that says "This is page number X that you have viewed with an adblocker. We get it, ads aren't what you're here for, but they do pay for the hosting and maintenance of TV Tropes. Please whitelist us or create an account to help support TV Tropes.". The markup for this popup seems to change with every iteration, since I cannot block it with the Element Picker.

### Versions

- Browser/version: Mozilla Firefox 62
- uBlock Origin version: 1.16.20

### Settings

I have, so far, not made any changes to default settings.

### Notes

This is not the first time TV Tropes has been intrusive with adblock warnings. Once they changed the markup of the site so that all links and images would be blocked.

As for why I use uBlock on this site, the ads tend to be incredibly intrusive, and the webmasters refuse to reign in the more toxic elements of the community. But that's neither here nor there.

**Comment by okiehsch** [comment]
This does not block any content, so it is an annoyance and will be fixed in the `uBO-annoyance` filter.
That list is not enabled by default, so you will have to enable it manually.

**Comment by weenusboy** [comment]
How do I do so? I'm sort of new to this.

**Comment by okiehsch** [comment]
I will have to add the filter first, then you have to simply enable the annoyance list.
![image](https://user-images.githubusercontent.com/16838044/45852877-89ab5b80-bd42-11e8-99d0-f4fcd37c8c91.png)
