### ISSUE TITLE
Multiple Scroll Bars at the Racing Post

### ISSUE THREAD

**Issue by ChrisPerryICL** [uBlockOrigin/uAssets#3537]
### URL(s) where the issue occurs

`https://www.racingpost.com/profile/jockey/92728/oisin-murphy`
`https://www.racingpost.com/profile/trainer/23926/ed-walker`

### Describe the issue

  Issue started a few days ago after Restart for Windows 10 Update, which also provoked update for Firefox and presumably uBlock version V1.16.20 . Initially it seemed that any New Tab or Window for the racingpost.com site had two scroll bars. 

Following advice from their Help Desk, I cleared Cookies and data for the site, this reduced it to New Tabs or Windows for Jockey or Trainer Profiles ( either from Bookmarks OR following links in Race Cards) .

Switching OFF uBlock for the site resolved the problem, and restored Ads .
  

### Screenshot(s)

![image](https://user-images.githubusercontent.com/43471800/45881767-163a3600-bda4-11e8-8bd2-8cd41048e556.png)

### Versions

- FireFox Quantum / 62.0 (64-bit)
- uBlock Origin version: [V1.16.20]

### Settings

- [Defaults]

### Notes
 Following this post I find I am still getting Two Scroll Bars, even with uBlock disabled for Site, and even having Removed uBlock from Firefox

**SORRY NOT YOUR PROBLEM**

**Comment by mapx-** [comment]
I get only 1 scrollbar, did you test using only the default filter lists ?

**Comment by ChrisPerryICL** [comment]
I Notice Firefox 62.0 only release 5th September, but probably only started using this a few days ago following Windows 10 Update

Are you not having problems on Quantum 62 ?

**Comment by mapx-** [comment]
using 63.0b7 (64-bit)

Could you test in chrome too ?

**Comment by ChrisPerryICL** [comment]
Caused by 'Tracking Protection' being 'ON'  in Firefox
