### ISSUE TITLE
Ad link on economictimes.indiatimes.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#3538]
### URL(s) where the issue occurs

`https://economictimes.indiatimes.com/`

### Describe the issue

An ad link (highlighted in the screenshot below) sneaks up somewhere near the end of TOP NEWS section on the homepage.

### Screenshot(s)

![et](https://user-images.githubusercontent.com/43062185/45887007-34ba2480-bdd8-11e8-8413-ccfe9f3f9878.png)

### Versions

- Browser/version: Firefox 62.0
- uBlock Origin version: 1.16.20

### Settings

Default

**Comment by mapx-** [comment]
add
`economictimes.indiatimes.com##.active > ul > li:has-text(Ad)`

or

`economictimes.indiatimes.com##.active > ul > li:has(a[onclick*="utm_source"])`

**Comment by in4u** [comment]
@mapx- I tried both of them separately. Somehow ad isn't blocked every time with the second filter. But the first filter works just fine.
