### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by ali2134** [uBlockOrigin/uAssets#3539]
doesn't show me the captcha properly, i will show you what i see:
`https://i.imgur.com/OSCzxqh.png`
when i complete that captcha show me a code, after i insert that code again the page show me the "fake" captcha, with ublock disabled that show me the true captcha without problem 
`https://i.imgur.com/PVoxLjL.png`
any fix please
chrome 69.0.3497.100
uBlock Origin v1.16.18

**Comment by mapx-** [comment]
well, again ... a normal user does not get such captcha, so you should post here all the blocked elements in your logger

**Comment by ali2134** [comment]
`https://i.imgur.com/f6A2MKG.png`

**Comment by mapx-** [comment]
test
`@@||gstatic.com/recaptcha/$script`

**Comment by ali2134** [comment]
fixed, thank you very much

**Comment by smed79** [comment]
@mapx- Is this not the same fix added [\_here\_](https://github.com/easylist/easylist/commit/f96d2aa6321) ?

**Comment by mapx-** [comment]
sure, but it seems it was lately removed, I see no such filter in easylist

**Comment by smed79** [comment]
> I see no such filter in easylist

Still there [easylist_adult/adult_whitelist.txt#L88](https://github.com/easylist/easylist/blob/a100d89eab2257c34822e3e0b233e47ee87e5005/easylist_adult/adult_whitelist.txt#L88)

**Comment by smed79** [comment]
After checking, [adult_whitelist.txt](https://github.com/easylist/easylist/blob/a100d89eab2257c34822e3e0b233e47ee87e5005/easylist_adult/adult_whitelist.txt) is missed in https://easylist.to/easylist/easylist.txt 

No issue with the list downloaded from **Adblock Plus** host 
https://easylist-downloads.adblockplus.org/easylist.txt

@monzta @ryanbr

**Comment by mapx-** [comment]
missing here:
https://easylist.to/easylist/easylist.txt
