### ISSUE TITLE
hdvid.tv [Fake Button] [Pop-up] [Mining]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3542]
URL(s) where the issue occurs

`https://hdvid.tv/zw7herf8olmn.html`

Describe the issue

Fake Button

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by okiehsch** [comment]
Fake button and popups and mining :)

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
`https://vidhd.pw/zw7herf8olmn.html`

**Comment by KiLL4FuNK** [comment]
`site is now named`

`https://ovid.icu/zw7herf8olmn.html`
