### ISSUE TITLE
Youtube - Auto pausing videos if inactive

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#3543]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=Lp6XlsBm_Lw` (or any video)

### Describe the issue

I don't know how long it takes for this to trigger, but recently I've been seeing these messages popup when I don't interact with a YouTube video for a certain time. The video is eventually paused, and you are asked if you're still watching (see the screenshot).

### Screenshot(s)

![screenshot_2018-09-21 relaxing music soft rain relaxing piano music sleep music peaceful music 148 - youtube](https://user-images.githubusercontent.com/8013408/45905934-eac14680-bdb7-11e8-8aa1-e49a2088cd5b.png)

### Versions

- Browser/version: Firefox 63.0b8
- uBlock Origin version: 1.16.20

### Settings

Filter lists enabled:
- uBlock filters​​​​​ (all except annoyances and experimental)
- Adblock Warning Removal List
- Adguard Base Filters
- EasyList​
- AdGuard Spyware Filters
- EasyPrivacy
- Malware Domain List​​
- Malware domains
- Spam404
- Adguard’s Annoyance List
- Fanboy’s Anti-Thirdparty Social
- Fanboy’s Social Blocking List
- Peter Lowe’s Ad and tracking server list

​### Notes

I found this line from inspect element and think it might have something to do with this:

`"youThereRenderer\":{\"configData\":{\"youThereData\":{\"lactThresholdMs\":\"3600000\",\"playbackPauseDelayMs\":10000,\"promptDelaySec\":3601,`

I tried to diffuse the thing with `script:inject` lines, but since I can't figure those out, I got nowhere. I'm probably also very wrong with saying what I just did.

Edit: It seems like going to `https://youtu.be/Lp6XlsBm_Lw?t=1h36m56s` in any browser will trigger this no matter what (with or without uBlock enabled).

Edit 2: It actually triggers at the 1 hour mark of a video.

**Comment by terrorist96** [comment]
This seems to be out of the scope of this project.

**Comment by KonoromiHimaries** [comment]
https://www.reddit.com/r/youtube/comments/9htd5b/how_do_i_stop_youtube_from_automatically_pausing/

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/ah090n/youtube_asking_if_im_still_watching/

Try this extension: https://addons.mozilla.org/firefox/addon/video-background-play-fix/

Edit: VBPF checks for `_lact` variable with last activity date:

https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Ffirefox%2Fdownloads%2Flatest%2Fvideo-background-play-fix%2Fplatform%3A2%2Fvideo-background-play-fix.xpi&qf=video-bg-play-content.js&qb=1

***

Also Foris4 answer:

>Thanks for reply, for now I use this extension: https://github.com/lawfx/YoutubeNonStop 
And is working ok.
