### ISSUE TITLE
powvideo.cc [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3552]
URL(s) where the issue occurs

`https://powvideo.cc/zqmu9us0jne6`

Describe the issue

Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.18

Settings

Default

**Comment by lain566** [comment]
`*$subdocument,domain=powvideo.cc` This filter is breaking the player.


Test link
`https://powvideo.cc/embed-vfyq9c7e5v7p.html`

**Comment by lain566** [comment]
I'm seeing two repeated filters

https://github.com/uBlockOrigin/uAssets/blob/a447860e09633eae06b835909be904c92f6b432e/filters/filters.txt#L6553

and 

https://github.com/uBlockOrigin/uAssets/blob/a447860e09633eae06b835909be904c92f6b432e/filters/filters.txt#L7145

**Comment by lain566** [comment]
There is another duplicate.

https://github.com/uBlockOrigin/uAssets/blob/538b376cb350f8231f04e924913af3a15809c4cc/filters/filters.txt#L6551

https://github.com/uBlockOrigin/uAssets/blob/0605e35a17233be1fff43f3f2a9bd600132bcaa5/filters/filters.txt#L11874
