### ISSUE TITLE
tube8.com [NSFW]

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#3558]
### URL(s) where the issue occurs

`https://tube8.com`

### Describe the issue

Bad rule in 2018 (may good in 2015 when  https  it was not popular) - cut most of images:

```
|https://$image,xmlhttprequest,domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com
```

### Screenshot(s)

`https://i.imgur.com/fcVwzvH.png`

### Versions

- Browser/version: Chrome 71
- uBlock Origin version: uBo 1.17.0

### Settings

- Default EN

### Notes

https://github.com/easylist/easylist/commit/3c13d3341adacb64831ee2045b4e0c82962244b2#r30609349

###### `@@`exception:

```
@@|https://$image,domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com
```

###### `,badfilter` disable:
```
|https://$image,xmlhttprequest,domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com,badfilter
```

**Comment by krystian3w** [comment]
link still not work...

[https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/easylist.txt](https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt&amp;title=Easylist.txt)

# Correct:

```
[https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/easylist.txt](https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt&amp;title=Easylist.txt)
```

**Comment by krystian3w** [comment]
link still not work...

[https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/easylist.txt](https://subscribe.adblockplus.org/?location=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt&amp;title=Easylist.txt)

# Correct:

```
[https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/easylist.txt](https://subscribe.adblockplus.org/?location=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt&amp;title=Easylist.txt)
```

**Comment by gwarser** [comment]
@krystian3w probably GitHub CSP prevents injecting uBO `subscriber.js` scriptlet.

**Comment by krystian3w** [comment]
[https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/easylist.txt](https://subscribe.adblockplus.org/?location=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt)

**Comment by krystian3w** [comment]
link @smed79 do not have `&amp;title=Easylist.txt` title parametr -  "to chyba najbardziej buguje działanie".

**Comment by krystian3w** [comment]
> 
> 
> @krystian3w probably GitHub CSP prevents injecting uBO `subscriber.js` scriptlet.



link @smed79 do not have "`&amp;title=Easylist`" **title** parametr -  "it's probably the most buggy action".

"Then bad coding `&` in html = whitout use entities."

**Comment by okiehsch** [comment]
I can't reproduxe any breakage at `tube8.com` with up to date filters.

**Comment by smed79** [comment]
@krystian3w 

> do not have "&amp;title=Easylist" title parameter (attribute)

The title is automatically taken in the header of the list.

> link still not work...

Both links work with **Adblock Plus** not with **uBlock Origin**.

@gorhill fyi.

**Comment by gwarser** [comment]
uBO requires `&title=` in subscription links - see regex https://github.com/gorhill/uBlock/blob/ff58107dac3a32607f8113e39ed5015584506813/src/js/scriptlets/subscriber.js#L69

**Comment by gorhill** [comment]
@smed79 I would really like to understand why you posted such subscribe link to EasyList when EasyList already enabled by default in uBO, and on top of this the one from ABP-controlled server instead of from the official EasyList repo?

**Comment by gorhill** [comment]
Just to be sure I understand correctly: the discrepancy between the content of EasyList @ `easylist.github.io` and the content of EasyList @ ABP server was just a transient thing? (if so, seconds? minutes? hours?)

**Comment by okiehsch** [comment]
@bug-rules your issue has been fixed by https://github.com/uBlockOrigin/uAssets/commit/1c854563f696926c2ba2cc34893d92f6dd54e6dd
two days ago, just update your `uBO-unbreak` list.
