### ISSUE TITLE
[Anti-Adblock] ourl.io

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#3559]
### URL(s) where the issue occurs

`https://ourl.io/HumrKt`

### Describe the issue

Anti-adblock message.

### Screenshot(s)

![ourl](https://user-images.githubusercontent.com/12146319/45929453-a24c8900-bf6f-11e8-8f93-b1adac3d339c.PNG)

### Versions

- Browser/version: Chrome 67
- uBlock Origin version: 1.16.18

**Comment by KiLL4FuNK** [comment]
update filters @version365

**Comment by okiehsch** [comment]
`ourl.io##+js(abort-on-property-read.js, app_vars.force_disable_adblock)` sill fixes this issue.

**Comment by version365** [comment]
Sorry, but the problem is still there. I updated the filters, and the rule @okiehsch mentioned is inside uBO filters. But, I'm still seeing this.
Actually, it works if uBO is used along with Nano Defender; but that's only in Firefox.
In Chrome, only uBO fails; uBO + Nano Defender also fails.

These are the filter lists I'm using.
https://i.imgur.com/kLE2VRP.png
https://i.imgur.com/kMpit0a.png

**Comment by mapx-** [comment]
Try first using only the default setup. Then remove 1 by 1 the other lists to find the "wrong" one (you have adguard lists, so ...)

**Comment by okiehsch** [comment]
I can reproduce if I add
`@@||ourl.io/js/ads.js$script,first-party`

`@@/js/ads.js$script`
is part of `Fanboy’s Enhanced Tracking List` and causes your issue.

**Comment by version365** [comment]
Aha... Thanks for pointing the main cause. I'll disable that filter.
