### ISSUE TITLE
[NSFW] youjizz.com - Content breakage [uBlock filters]

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#356]
All content is broken on `https://www.youjizz.com` such as images and videos. This happens due to this filter in **uBlock filters**:
`*$script,websocket,third-party,domain=gaytube.com|pornhub.com|redtube.com|redtube.it|tube8.com|tube8.es|tube8.fr|xtube.com|youjizz.com|youporn.com|youporngay.com`

This filter blocks scripts from `https://cdne-static.yjcontentdelivery.com` which seems to be responsible for delivering content on `https://www.youjizz.com`.

**SS:** http://imgur.com/a/2Yw9I (Full page screenshot, no NSFW images as they are all broken)

**Error URL:** 
https://www.youjizz.com/videos/amirah-adara-and-tricia-teen-have-their-first-3way-with-the-teacher-33612121.html

_**Note:** Using uBO 1.11.4 on Chrome 57 with default filter lists._

**Comment by gotitbro** [comment]
@okiehsch @gorhill Ads on `https://www.youjizz.com`. Served as first-party to adblock users as can be seen by the structure of the ad image URLs:
youjizz.com/**neverblock**/cache/482891-17417075249182500_1_xacd.gif (NSFW)

**Error URL:** `https://www.youjizz.com`

The tag above these ads remains the same as when not using adblock, i.e., "**_Ads by Exoclick.com_**". Though I wouldn't be sure if that is actually the case.

**Comment by okiehsch** [comment]
Does
`youjizz.com##script:inject(abort-on-property-write.js, nb)`
work withot breaking anything?
