### ISSUE TITLE
[Anti-Adblock] bild.de 

### ISSUE THREAD

**Issue by spec1re** [uBlockOrigin/uAssets#3560]
Since today bild.de is blocking Ad-blocker again

### URL(s) where the issue occurs

`https://www.bild.de/`

### Describe the issue

Redirected to block notice.

![grafik](https://user-images.githubusercontent.com/11883076/28816552-c3ad5518-7694-11e7-9b3d-ddd3b70aa6c0.png)

### Versions

- Browser/version: Chrome 69.0.3497.100 (Win10) (64-Bit)
- uBlock Origin version: 1.16.18
- uBlock Origin Extra Version: 2.77

### Settings
 * Default settings

**Comment by krystian3w** [comment]
I have to in mobile version:
