### ISSUE TITLE
shaggyimg.pro [NSFW]

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#3564]
Replace the bracketed [...] placeholders with your own information.

`http://shaggyimg.pro/n7.html`

### Describe the issue

click to show full size image and then click on the photo itself and the redirect will happen (fake google icon) and click image again redirect 

### Screenshot(s)

https://a.radikal.ru/a29/1809/2e/e163d9aa7af0.png

### Versions

- Browser/version: cent browser 3.5.3.50 Chromium 67.0.3396.99
- uBlock Origin version: 1.17.0

### Settings

default ubo settings
### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by electrifying** [comment]
redirect again

**Comment by mapx-** [comment]
Did you update your lists ? I get no popup, redirection

**Comment by electrifying** [comment]
> Did you update your lists ? I get no popup, redirection

Yes. redirect occurs when you click on the image a second time

**Comment by mapx-** [comment]
still cannot reproduce the issue

**Comment by okiehsch** [comment]
@electrifying does
`shaggyimg.pro##+js(abort-on-property-read.js, pndrCodeScript)`
work for you ?
