### ISSUE TITLE
redtube.com [NSFW]

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#3569]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`redtube.com`

### Describe the issue

on the right, an empty ad unit

[NSFW] `https://imgur.com/wV9585R`

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: cent browser chromium 67
- uBlock Origin version: 1.17.0

### Settings

default settings

### Notes

none

**Comment by Yuki2718** [comment]
I get ephemeral popup or popunder upon clicking any video on their front page, apparently only on Firefox.
`redtube.com##^script:has-text(popUnderURL)`
works on my end but please check if Chromium does really not have the issue.
