### ISSUE TITLE
Yandex ads in their search results and yadisk

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uAssets#357]
### URL(s) where the issue occurs

https://yandex.by/yandsearch?text=%D0%BE%D1%82%D0%B5%D0%BB%D1%8C&lr=157&clid=*
https://yandex.ru/search/?lr=213&msid=1491639218.72533.22878.26877&text=%D0%BE%D1%82%D0%B5%D0%BB%D1%8C
https://yadi.sk/d/Hhr1kVHa3BH9Qa

### Describe the issue
In recent weeks, Yandex ads (called "Яндекс.Директ") ceased to be blocked in uBO only with EasyList and RU AdList.
@gorhill, please add these filters to uBlock Filters list:
1. yandex.by,yandex.kz,yandex.ru,yandex.ua##.serp-item:if(div:matches-css-after(content: Реклама))
2. yadi.sk##.preview-responsive__image-wrapper:matches-css(margin-top: -16px)
3. yadi.sk##.aside-public__info-wrapper > div[class^="aside-public__info"]:matches-css(width: 300px)
4. yadi.sk##.folder-public__content-wrapper:matches-css(position: absolute)

### Screenshot(s)
Yandex search results (advertising results in yellow rectangles with word "Реклама" appears without filter 1 from above list):
![1](https://cloud.githubusercontent.com/assets/16985985/24828032/7d80f054-1c5d-11e7-843e-a7918330b797.jpg)

Yandex disk (ad frame with words "Яндекс.Директ" appears without filters 2-4 from above list):
![2](https://cloud.githubusercontent.com/assets/16985985/24827667/e4a5c2c0-1c56-11e7-81c9-966830ec4a2f.jpg)

In general, the design of Yandex Disk pages and the location of the frames may vary greatly. For example:
1 (at the top, turquoise highlight with "Яндекс.Директ")
![efqbjju - imgur](https://cloud.githubusercontent.com/assets/16985985/24827851/8f6f07d6-1c5a-11e7-86c8-7060be57f85f.jpg)

2 (on the right, turquoise highlight with "Яндекс.Директ")
![ig9dmin - imgur](https://cloud.githubusercontent.com/assets/16985985/24827853/94a1a768-1c5a-11e7-8601-4733d74c0d2f.jpg)

Filters 2-4 are working fine in all these cases.

### Versions

- Browser/version: Firefox 53.0b9
- uBlock Origin version: 1.11.5rc8

### Settings

- I am an advanced user
- Prevent WebRTC from leaking local IP addresses
are checked.

**Comment by gorhill** [comment]
I could reproduce the 1st picture, I modified slightly your suggested filter to ensure less nodes are visited.

I could not reproduce pictures 1-3, I am guessing I need to be logged on, so I just imported your suggested filters as is.

Thanks.
