### ISSUE TITLE
Anti-adblock ourl.io

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#3570]
### URL(s) where the issue occurs

`https://ourl.io/7vVksm`

### Describe the issue

Anti-adblock

### Screenshot(s)

![432632](https://user-images.githubusercontent.com/27068733/46071914-a09de380-c170-11e8-9e23-633f249bf81f.jpg)

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.17

**Comment by mapx-** [comment]
read
https://github.com/uBlockOrigin/uAssets/issues/3559

try testing using ONLY the default setup

**Comment by bup4gr** [comment]
Yes, i use `Fanboy’s Enhanced Tracking List`.
Is it possible to add a filter to the list `uBlock filters – Unbreak` to bypass the problem?

**Comment by mapx-** [comment]
You should report at 
https://github.com/ryanbr/fanboy-adblock/issues

or add a custom filter
`@@/js/ads.js$script,badfilter`

ubreak list is dealing with the default setup

```
Title: uBlock filters -- Unbreak
! Expires: 4 days
! Description:
!     Filters optimized for uBlock Origin, to unbreak sites broken as
!     a result of 3rd-party filter lists enabled by default.
```

**Comment by bup4gr** [comment]
I have the problem also after the fix of `Fanboy’s Enhanced Tracking List`.

Can you confirm the problem also if you enable `Adguard Base Filters`?

**Comment by mapx-** [comment]
Just disable that list and you'll know if ...

**Comment by bup4gr** [comment]
With `Adguard Base Filters` there is the same problem.

**Comment by mapx-** [comment]
if you want to keep adguard list, just add:
`@@/js/ads.js|$first-party,script,domain=~internethaber.com,badfilter`

**Comment by bup4gr** [comment]
If a have enable `Adguard Base Filters` and your filter `@@/js/ads.js|$first-party,script,domain=~internethaber.com,badfilter`, i can see and solve the captha.
But in the new page i see:
![u2](https://user-images.githubusercontent.com/27068733/47730382-f2e39000-dc59-11e8-9c76-39d51654773f.jpg)
Any solution?

**Comment by mapx-** [comment]
no issue keeping only the default setup
