### ISSUE TITLE
mystream.to

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3571]
### URL(s) where the issue occurs

`https://mystream.to/watch/d1qsoivhm3pa`

### Describe the issue

popup when click play

### Versions

- Browser/version: [here] latest release
- uBlock Origin version: [here] latest release

### Settings

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by mapx-** [comment]
I added a filter 2 hours ago, test it
https://github.com/uBlockOrigin/uAssets/commit/ceb02cc7cdd6ea9307daef3eef446c2839892f5e

**Comment by ghajini** [comment]
Its `mystream.to` not `mstream.to`
BTW not work,tried as custom filter

**Comment by mapx-** [comment]
I know, it's what I get in my logger, maybe it's different for you.

**Comment by mapx-** [comment]
hmm, this 1 should work
`mstream.*##+js(aopr, open)`

**Comment by ghajini** [comment]
I don't see any `mstream` related entry in logger nor above scriptlet(added as custom filter).....

**Comment by mapx-** [comment]
what if you test
`mystream.to##+js(aopr, open)`

**Comment by ghajini** [comment]
Works👍
