### ISSUE TITLE
userscloud.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3573]
### URL(s) where the issue occurs

`https://userscloud.com/36437gnwjhqa`

### Describe the issue

popup when click download button

### Versions

- Browser/version: [here] latest release
- uBlock Origin version: [here] latest release

### Settings

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by ghajini** [comment]
* beiven.pw * block
* wachipho.net * block

**Comment by ghajini** [comment]
Crap xhrs appearing....
`userscloud.com/2ls6mnbqoat9`

**Comment by ghajini** [comment]
Crap xhr's 
`https://userscloud.com/t1wpfxr4tbzt`

**Comment by ghajini** [comment]
`https://userscloud.com/qmzrj6z77psk`
most of the filters are unneeded here, please update and also

 `userscloud.com##+js(acis, JSON.parse)`

**Comment by ghajini** [comment]
`https://userscloud.com/tmui0a8fgg2h`
propeller kicks in

https://user-images.githubusercontent.com/20338483/140661354-a6798ced-d0a8-4a9d-8537-7ee426cf5fbe.png

add only
`userscloud.com##+js(acis, JSON.parse)`
will take care of both pp & FingerprintJS

**Comment by ghajini** [comment]
FingerprintJS code left untouched, so popup request

https://user-images.githubusercontent.com/20338483/140661930-d4de0288-bd9c-4836-b304-45b1682ab7df.png

**Comment by ghajini** [comment]
music player is blocked here 
`https://userscloud.com/j8ey7l3bhzdp`

also check these links 
`https://userscloud.com/tmui0a8fgg2h`
`https://userscloud.com/alcjyjstpc9d`
