### ISSUE TITLE
Anti adblock on rockfile.eu

### ISSUE THREAD

**Issue by grefer3** [uBlockOrigin/uAssets#358]
### URL(s) where the issue occurs
http://rockfile.eu/d5c0aupp0k5n.html

### Describe the issue
Anti adblock on rockfile.eu

### Screenshot(s)
![img](https://cloud.githubusercontent.com/assets/27062833/24828380/4f3cb172-1c4b-11e7-83b6-7ea99c1ab56f.jpg)

**Comment by mapx-** [comment]
add
```
@@||rockfile.eu^$generichide
rockfile.eu##[id^=aswift]
```

**Comment by bup4gr** [comment]
With this solution no more anti adblock message, but a lot of blank space in the page.

Then your solution don't work if i have * googlesyndication.com * block

Is there a way to bypass the anti adblock and leave the rule * googlesyndication.com * block ?

**Comment by gorhill** [comment]
||doubleclick.net^$subdocument,redirect=noopframe,domain=rockfile.eu
    rockfile.eu###containerDiv > div[align="Center"]:style(height: 1px !important)
