### ISSUE TITLE
FIN: Finnish Addition to Easylist has advertising (self-promotion) on the homepage

### ISSUE THREAD

**Issue by 07416** [uBlockOrigin/uAssets#359]
### URL(s) where the issue occurs

http://www.juvander.fi/site/ilpo/Forums/forumid/23/scope/threads, redirected from http://www.juvander.fi/AdblockFinland

### Describe the issue

The list's homepage is hosted under `juvander.fi` domain, homepage for Juvander Consulting Oy (Oy is Finnish equivalent of a limited company). There are promoted links to commercial services "Moto Juvander", "Juvander Consulting", "Varaosia" (spare parts) [on the homepage](http://www.juvander.fi/site/ilpo/Forums/forumid/23/scope/threads), the only place where issues and advertisements can be reported.

**Comment by gorhill** [comment]
Guideline is [EasyList's policy](https://easylist.to/pages/policy.html):

> Self-promotion should not be specifically removed by EasyList

**Comment by 07416** [comment]
@gorhill Did you create the name "FIN: Finnish Addition to Easylist"? The list has no subforum on [EasyList forums](https://forums.lanik.us/index.php) and the developer refers to the list as "Adblocker for Finland". I can't see how the list is affiliated with EasyList.

**Comment by gorhill** [comment]
I am not saying it is affiliated with EasyList, I am saying that EasyList policy is what I use to make decisions about filter issues here.

**Comment by 07416** [comment]
The list has been added to Adblock Plus website: https://adblockplus.org/en/subscriptions
