### ISSUE TITLE
coshurl.co

### ISSUE THREAD

**Issue by anewuser** [uBlockOrigin/uAssets#360]
### URL(s) where the issue occurs

http://coshurl.co/bELp

### Describe the issue

Anti-adblock message replaces captcha/continue button.

### Versions

- Browser/version:  Firefox 51.0.1
- uBlock Origin version: 1.11.4

**Comment by SMed79** [comment]
```
@@||coshurl.co^$generichide
|http://$xmlhttprequest,script,third-party,domain=coshurl.co
|https://$xmlhttprequest,script,third-party,domain=coshurl.co
```

**Comment by okiehsch** [comment]
@gorhill `generichide` fixes the issue, so why it is not the preferred solution in this specific case?

**Comment by gorhill** [comment]
I just pulled the request as is after checking it worked. It can be removed once the `generichide` solution is in EasyList.
