### ISSUE TITLE
It's not an ad nor an anti-adblocker but the ultimate of nonsense

### ISSUE THREAD

**Issue by StanGets** [uBlockOrigin/uAssets#3614]
uBO 1.17.0 / Firefox 62.0.2

Hi,

The site is https://www.tours.fr/

Not sure the conditions are met to ask for help regarding an overlay which appears when the user has set _Do Not Track_ to _true_:` user_pref("privacy.donottrackheader.enabled", true);`

When clicking on a whatever item of the site's homepage the link opens a new page, determines if the user has set DNT and if true pops up an overlay to inform the user what DNT is about and asks him to confirm. If the user confirms a second overlay pops up to inform the user that the site will respect the DNT ...

![greenshot-2018-09-28-004236](https://user-images.githubusercontent.com/42912760/46179065-cf73a100-c2b9-11e8-84a3-5a99d377905e.jpg)

![greenshot-2018-09-28-004247](https://user-images.githubusercontent.com/42912760/46179070-d69aaf00-c2b9-11e8-84b6-92e67b23296e.jpg)

I've seen many things in life but this is the ultimate regarding nonsense, IMO.
The idiocy relies in an inline script and disabling inline scripts breaks this site (when on some others it's just fine for dealing with an overlay).

Thanks!

**Comment by gwarser** [comment]
Block only `https://www.tours.fr/include/js/tagAnalyticsCNIL.php`

**Comment by ZaphodBeebblebrox** [comment]
Fixed in uBlock Annoyances.

**Comment by StanGets** [comment]
Added `/include/js/tagAnalyticsCNIL.php$important `to _My filters_
Thanks @gwarser
