### ISSUE TITLE
AllMusic again

### ISSUE THREAD

**Issue by practik** [uBlockOrigin/uAssets#362]
### URL(s) where the issue occurs

`http://allmusic.com/`

### Describe the issue

The site detects ad blocking and puts up an overlay that prevents access to the site until the visitor either subscribes or allows ads, as previously described in issues [171](https://github.com/uBlockOrigin/uAssets/issues/171) and [182](https://github.com/uBlockOrigin/uAssets/issues/182).

### Versions

- Browser/version: Firefox 52.0.2
- uBlock Origin version: 1.12.0

### Settings

- Defaults, plus advanced features enabled

### Notes

Static filter `allmusic.com##script:contains(googletag)` fixes it for me.

**Comment by mapx-** [comment]
does this work too ?
`||allmusic.com$inline-script`

**Comment by practik** [comment]
Yes, as does the dynamic filtering rule `allmusic.com * inline-script block` – but why block all inline scripts on the site just to squash this one (major) annoyance? I guess you're trying to preemptively block whatever anti-adblock method they come up with next?

**Comment by okiehsch** [comment]
`allmusic.com##script:inject(abort-on-property-read.js, require)` works on my end with 
Chrome and Firefox, if it works for others and doesn't break anything I will add it.

**Comment by practik** [comment]
Works for me too, but I'm not familiar enough with the site to be able to say whether it breaks anything.

**Comment by okiehsch** [comment]
Me neither, that's why I didn't add it immediately.

**Comment by okiehsch** [comment]
After taking a closer look, nothing appears to be broken, I can register, login, listen to the music,
play the videos etc.
The filter also fixes the same issue for `sidereel.com`, sister-site of `allmusic.com`, so I will add
both domains.

**Comment by uBlock-user** [comment]
Blocking all inline scripts on `allmusic.com` doesn't break anything either, it's matter of choice.

**Comment by practik** [comment]
OK, that's good to know. Thanks for checking and fixing!

**Comment by krystian3w** [comment]
No doesn't works?  Or no unlock show ratings review?

```
allmusic.com##+js(abort-current-inline-script.js, googletag)
allmusic.com##^script:has-text(googletag)
```

https://old.reddit.com/r/uBlockOrigin/comments/b2nfej/ublock_origin_blocks_user_ratings_and_reviews_in/
