### ISSUE TITLE
apornoflv.tv[NSFW] 

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#3627]
### URL(s) where the issue occurs

`https://apornoflv.tv/video26586.html`

### Describe the issue

Ads in the player

### Versions

- Browser/version: Opera Stable
- uBlock Origin version: 1.17.1b1

### Settings

uBO's default settings

**Comment by mapx-** [comment]
test
```
*.mp4$media,redirect=noopmp4-1s,domain=apornoflv.tv
@@*/video/*.mp4$media,domain=apornoflv.tv
```

**Comment by PoRtvine** [comment]
it's working
#Gif 
https://imgur.com/a/OLUv68l

**Comment by mapx-** [comment]
reported here
https://forums.lanik.us/viewtopic.php?p=141639#p141639

**Comment by electrifying** [comment]
why not add these rules to the ublock filters

**Comment by mapx-** [comment]
ok, added
