### ISSUE TITLE
Many online shopping recommended site links will be intercepted

### ISSUE THREAD

**Issue by xuyuehang** [uBlockOrigin/uAssets#363]
When i visit this shopping recommendation site: http://www.tepintehui.com/detail/28584
Click the purchase link and find that it will be blocked by ublock filtering rules.

![](http://i4.buimg.com/567571/1791921546e1e27d.png)

![](http://i1.piimg.com/567571/4b50577ff0cf539a.png)

Then I found that because of the link with 'webgains.com' which is a rebate website.

In this situation whether it should be intercepted? I mean there are a lot of shopping recommended site will take this method to get rebate, and most of the rebate site is on ublock's filter rules. Maybe we should only block elements on the page without interfering with the actually access links.

**Comment by SMed79** [comment]
> if you disagree with the strict block you have to click the **Permanently** button.

**Comment by gorhill** [comment]
That page is there to inform you that you are being redirected to a page which matches a block filter -- without this page, you would be redirected without your knowledge. Make a decision based on that information, the choice is yours.
