### ISSUE TITLE
twincities.com anti adblock

### ISSUE THREAD

**Issue by nomisunrider** [uBlockOrigin/uAssets#3638]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.twincities.com/`

### Describe the issue
After you reach article limit, it blocks pages from being read.  Also detects ublockorigin and will not allow you to read further.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/13275125/46300499-7fbb0100-c569-11e8-8f4f-a1f76af9bf6d.png)

### Versions

- Firefox Quantum/62.02 (64bit) and Chrome/69.0.3497.100 (64bit)
- uBlock Origin version: 1.15.4 (firefox) and 1.17.0 (chrome)

### Settings

None

### Notes

None

**Comment by nomisunrider** [comment]
I added this to filters and it doesn't work.  Navigate to an article to truly test.  For example:

https://www.twincities.com/2018/09/30/with-career-possibly-ending-twins-joe-mauer-taking-in-a-little-bit-more-than-i-usually-would/

Thanks

**Comment by mapx-** [comment]
working for me.

What filter lists are enabled in your uBo ? 

Did you add `twincities.com##+js(setTimeout-defuser.js, CnnXt)` or
 `+ twincities.com##+js(setTimeout-defuser.js, CnnXt)` ?

**Comment by nomisunrider** [comment]
The first way:
'twincities.com##+js(setTimeout-defuser.js, CnnXt)'

I forgot to add, you need to open more than 4 articles.  Did you try that?

**Comment by mapx-** [comment]
Yes, sure, tens of articles ...

**Comment by mapx-** [comment]
**What filter lists are enabled in your uBo ?**

**Comment by okiehsch** [comment]
@mapx- the issue is already fixed even without your filter on my end.
`twincities.com##+js(set-constant.js, CnnXt.Utils.detectAdBlock, noopFunc)`
is part of uBlock-filters and still works on my end.

**Comment by mapx-** [comment]
@okiehsch  It doesn't on my end, still needing the second filter.

**Comment by okiehsch** [comment]
Weird, I tried with Chrome and Firefox.
If I only disable the `setTimeout` filter.
![unbenannt](https://user-images.githubusercontent.com/16838044/46315571-1a4d2b80-c5ce-11e8-8de5-90a7b68724c1.JPG)

If I disable the `set-constant` filter too.
![image](https://user-images.githubusercontent.com/16838044/46315541-03a6d480-c5ce-11e8-80f4-3d19d0ab352c.png)

**Comment by mapx-** [comment]
No problem with `sgvtribune` site (no needing `timeout` filter)

**Comment by mapx-** [comment]
@okiehsch  well, I have to say my filter is defeating the paywall ! no anti adblocking message at all

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/46316134-8e3c0380-c5cf-11e8-9d3e-ed742fc67b93.png)

**Comment by okiehsch** [comment]
Well, that is a different issue then the ant-adblock message in my screenshot, if  you clear cache and cookies and remove the setTimeout filter, do you get the "We see you have an adblocker" message?

**Comment by okiehsch** [comment]
>  no anti adblocking message at all

Sorry I missed that.

**Comment by mapx-** [comment]
I repeated my tests, clearing all cookies, no anti adb msg, only "limit for this month"

**Comment by okiehsch** [comment]
Well, as we do not circumvent paywalls your filter should probably be removed.

**Comment by nomisunrider** [comment]
Yes, thought my UBO filter list is much smaller.
And also, I'm sorry, but it IS working, you are correct.  I was not reading close enough as the pop-up for article limit looks similar to the anti-ad-block pop-up
