### ISSUE TITLE
Blurred Images on Bloomberg

### ISSUE THREAD

**Issue by diego898** [uBlockOrigin/uAssets#364]
### URL(s) where the issue occurs

- Articles on https://www.bloomberg.com/
- For example: https://www.bloomberg.com/news/articles/2017-04-10/inside-blue-apron-s-meal-kit-machine

### Describe the issue

I have medium blocking mode enabled, with (reek antiadblock killer). Bloomberg seems to detect the adblocker and instead just show these pixelated images. 

### Screenshot(s)

Images look like:
![image](https://cloud.githubusercontent.com/assets/742407/24939174/57d1490e-1ef0-11e7-8e26-192469a3fe70.png)

My settings:
![image](https://cloud.githubusercontent.com/assets/742407/24939162/4b95a536-1ef0-11e7-90c8-f9f12be450a9.png)

### Versions

- Browser/version: Chrome/57.0.2987
- uBlock Origin version: 1.12.0

### Settings

- My third party filters:
![image](https://cloud.githubusercontent.com/assets/742407/24939223/be290926-1ef0-11e7-91ec-efd22177866d.png)
- My filters
![image](https://cloud.githubusercontent.com/assets/742407/24939235/c6afa19a-1ef0-11e7-939b-250effc63ae0.png)

### Notes
When I disable blocking for 3rd party scripts, the images correctly resolve.

**Comment by okiehsch** [comment]
"Noop" `bwbx.io`, that will solve your issue.
