### ISSUE TITLE
Ads in Quora

### ISSUE THREAD

**Issue by no1xsyzy** [uBlockOrigin/uAssets#3640]
### URL(s) where the issue occurs

`https://www.quora.com/What-does-RAM-frequency-signify`
`https://www.quora.com/Does-the-frequency-of-RAM-matter`

### Describe the issue

Ads not removed.

### Screenshot(s)

![default](https://user-images.githubusercontent.com/7346170/46306988-4fff0e00-c5e8-11e8-81d7-167b792cc537.png)
![default](https://user-images.githubusercontent.com/7346170/46307031-66a56500-c5e8-11e8-8a6a-fcd32768ab74.png)

### Versions

- Browser/version: Firefox 62.0.2
- uBlock Origin version: v1.17.0

### Settings

- Nothing

### Notes

It has random class names and ids, so the only clue is `href` of `<a>` tag.
`www.quora.com##div:has(>div>div>div>a[href="https://www.grammarly.com/?q=writing"])`

**Comment by no1xsyzy** [comment]
@ZaphodBeebblebrox that doesn't work now for the absence of `nav_style`. I remember `nav_style="system_browser"` was present when I started this issue.

After some research, can be this: `www.quora.com##:xpath(//a[@rel="noopener nofollow"]/../../../..)`
I didn't realize that the URL can be different, `rel` works now.

**Comment by ZaphodBeebblebrox** [comment]
Unfortunatly, your filter breaks when other people use external links ( ex: https://www.quora.com/How-useful-and-effective-was-FlaK-88-as-an-anti-tank-gun ).  I think it works with a slight adjustment though.  Does `quora.com##:xpath(//a[@rel="noopener nofollow"][not(@data-qt-tooltip)]/../../../..)` work for you?

**Comment by terrorist96** [comment]
@ZaphodBeebblebrox I see ads again.
