### ISSUE TITLE
powerbot.org[ADS]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#3642]
### URL(s) where the issue occurs

`[powerbot.org/community/]`

### Describe the issue

`[Annoying banner ads top of the page.]`

### Screenshot(s)

`[https://gyazo.com/84cc155c35a82dda4be295185aec0698]`

### Versions

- Browser/version: [69.0.3497.100]
- uBlock Origin version: [1.17.0]

### Settings

- [Default]

**Comment by mapx-** [comment]
add in your filters
`powerbot.org###adMoveHere`
