### ISSUE TITLE
Unable to deal with Cosmetic filters (sp-today.com)

### ISSUE THREAD

**Issue by mbnoimi** [uBlockOrigin/uAssets#3644]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`https://sp-today.com/en`

### Describe the issue

This website somehow fights uBlock and blocks the content so I apply the following filters but I always get a blur content!

```
sp-today.com###adblock-wall
sp-today.com##.content1-ad
sp-today.com##.content2-ad
```
I tried to use the following but it blocks whole content:
```
sp-today.com###content.stop-scrolling.blur.content
```

### Screenshot(s)

![firefox_screenshot_2018-10-02t02-57-46 417z](https://user-images.githubusercontent.com/284547/46327003-2655df00-c608-11e8-8b0e-00322be89618.png)

### Versions

- Browser/version: 62.0 (64-bit)
- uBlock Origin version: 1.17.0

### Settings

I use the default setting except in **My Filters** I use the above filters.
![image](https://user-images.githubusercontent.com/284547/46327316-adf01d80-c609-11e8-8e15-dc529d4aa364.png)

**Comment by okiehsch** [comment]
Update your `uBO-filter` list, the site should work fine after that and you can remove 
`````
sp-today.com###adblock-wall
sp-today.com##.content1-ad
sp-today.com##.content2-ad
````

**Comment by okiehsch** [comment]
> the website doesn't work fine

What exactly does not work?

**Comment by mbnoimi** [comment]
> What exactly does not work?

Currency converter textbox doesn't work

**Comment by okiehsch** [comment]
Seems to work on my end.
![image](https://user-images.githubusercontent.com/16838044/46328439-78e2cb80-c607-11e8-94c4-912dbff0c6f6.png)

**Comment by smed79** [comment]
NO issue here
https://i.imgur.com/q9GMVs3.png
https://i.imgur.com/8wHtdCo.png

**Comment by mbnoimi** [comment]
Really strange, it works after disabling uBO Firefox extension then enable it once again!

Thank you @okiehsch

**Comment by okiehsch** [comment]
I can break the textbox if I block the jquery script, but that is not blocked with a default setup.
