### ISSUE TITLE
bolor-toli.com

### ISSUE THREAD

**Issue by anewuser** [uBlockOrigin/uAssets#365]
### URL(s) where the issue occurs

http://www.bolor-toli.com/dictionary/word?search=dream&selected_lang=4-1&see_usages=true&see_variants=true

### Describe the issue

Anti-adblock overlay called by setTimeout().

### Versions

- Browser/version:  Firefox 51.0.1
- uBlock Origin version: 1.12.0

**Comment by uBlock-user** [comment]
OR adding `@@||bolor-toli.com^$elemhide` will do the job too.

**Comment by SMed79** [comment]
`bolor-toli.com#@#.adsbygoogle`

**Comment by IThinkIAmCool** [comment]
ads
