### ISSUE TITLE
elmercurio.com ads

### ISSUE THREAD

**Issue by magical81** [uBlockOrigin/uAssets#3650]
`https://digital.elmercurio.com/2018/10/04/B/TB3F1MMG#zoom=page-width`
ads don't allow me read, any fix please

ublock last version
chrome last version

**Comment by mapx-** [comment]
Are you talking about 
`Subscribe for $ 1 on the 1st month, and continue reading without limits.`

?

**Comment by magical81** [comment]
yes, can be that fixed, because it's ads for me

**Comment by mapx-** [comment]
It's subscription / paywall, so we don't fix such stuff.

You can add in your "my filters" 
```
digital.elmercurio.com##.in.fade.modal
digital.elmercurio.com##.in.fade.modal-backdrop
```

and see if works

**Comment by magical81** [comment]
works, thank you very much
