### ISSUE TITLE
browardpalmbeach.com [Anti-Adblock]

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#3654]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.browardpalmbeach.com/news/tiffany-trump-cannot-escape-her-pop-song-7717799`

### Describe the issue

After page loads, there is an overlay anti-adblock message.

### Screenshot(s)

![annotation](https://user-images.githubusercontent.com/22258847/46547048-47455b00-c8ba-11e8-9461-d6205015fc66.png)

### Versions

- Browser/version: Chrome Version 70.0.3538.45 (Official Build) beta (64-bit)
- uBlock Origin version: 1.17.1b1
- uBlock Origin Extra 2.76

### Settings

- Test profile with default settings and lists.

### Notes

Looks like same anti-adblock as from #2636 & #2188 so I believe `browardpalmbeach.com##script:inject(set-constant.js, VMG.Components.Adblock, false)` should work. (This worked for me)

**Comment by mapx-** [comment]
thx
