### ISSUE TITLE
houstonpress.com [Anti-Adblock]

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#3656]
https://github.com/uBlockOrigin/uAssets/issues

Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.houstonpress.com/news/cowboys-come-to-town-for-third-time-in-texans-history-10915345`

### Describe the issue

After page loads, there is an overlay anti-adblock message.

### Screenshot(s)

![annotation](https://user-images.githubusercontent.com/22258847/46554365-9053da00-c8cf-11e8-9944-69c0dc6c9938.png)

### Versions

- Browser/version: Chrome Version 70.0.3538.45 (Official Build) beta (64-bit)
- uBlock Origin version: 1.17.1b1
- uBlock Origin Extra 2.76

### Settings

- Test profile with default settings and lists.

### Notes

Looks like same anti-adblock used by other Voice Media Group[1] sites (#3654, #2636 & #2188) so I believe `houstonpress.com##script:inject(set-constant.js, VMG.Components.Adblock, false)` will work.

[1] Voice Media Group News & Entertainment Properties
`https://www.voicemediagroup.com/news-entertainment/`

**Comment by mapx-** [comment]
thx
