### ISSUE TITLE
ez-converter.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3661]
Replace the bracketed [...] placeholders with your own information.

### Describe the issue

hidden convert audio to video button

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by mapx-** [comment]
force an update of ublock filters
