### ISSUE TITLE
uBlock Origin removes buttons from GitHub in Waterfox 56.2.3

### ISSUE THREAD

**Issue by stefanos82** [uBlockOrigin/uAssets#3662]
I use `uBlock Origin v1.17.0` with both `Version 69.0.3497.92 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)` and `Waterfox 56.2.3 (64-bit)` on a GNU / Linux Debian testing 64-bit machine.

On Chromium, with uBlock Origin enabled I have no problems submitting new issue or editing an existing one and updating it.

On Waterfox, if I don't disable uBlock Origin I cannot issue a new ticket nor can I update an existing one.

**Comment by mapx-** [comment]
a wrong filter, already fixed

update `ublock filters`
