### ISSUE TITLE
techradar.com anti adb 

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#3664]
Anti-Adblock Script

Example:
`https://www.techradar.com/news/the-best-free-media-player`

**Comment by krystian3w** [comment]
```
techradar.com##+js(abort-on-property-read.js, _sp_._networkListenerData)
```
Made by @jspenguin2017.

**Comment by krystian3w** [comment]
Maybe moved to main list uBlock Origin.

**Comment by jspenguin2017** [comment]
It's just an annoyance, once you close it, it doesn't come back.

**Comment by krystian3w** [comment]
You can see the author of the issue is not covered by what is an annoying element and a strong anti-blocking (eg something limiting).

**Comment by jspenguin2017** [comment]
It's a soft anti-adblock for me, once I close it, it doesn't come back: 
![image](https://user-images.githubusercontent.com/7283682/46584462-afae4c80-ca20-11e8-88e2-c216a0d4350e.png)

**Comment by mapx-** [comment]
@erosman  you have to enable ublock annoyances list

**Comment by krystian3w** [comment]
[uBO annoyance - Subscribe][uBO annoyance - Subscribe]

[uBO annoyance - Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt&title=annoyances%20uBO

**Comment by erosman** [comment]
@krystian3w Is the subscribe method via above link or is there a setting on the addon?

**Comment by krystian3w** [comment]
Yes, should activate correct list in uBO.

**Comment by mapx-** [comment]
open the dashboard and enable that list.

**Comment by erosman** [comment]
​​​​​​​​Which one?

Annoyances (0/5)

Adguard’s Annoyance List​
Fanboy’s Annoyance List​
​​​Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
​​​​​​​​Fanboy’s Social Blocking List​

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/46585165-7223e080-ca6d-11e8-8f91-4fe54ab68159.png)

**Comment by erosman** [comment]
Thank you @okiehsch

**Comment by okiehsch** [comment]
> Every time I go to
techradar.com/news/the-best-free-media-player
It forwards to
techradar.com/cc.html

I can't reproduce, if I disable `uBO-annoyances`
![image](https://user-images.githubusercontent.com/16838044/46585184-bfa04d80-ca6d-11e8-9466-e39ce726d75d.png)

**Comment by erosman** [comment]
My setting had 5/7

These were off

uBlock filters – Annoyances
uBlock filters – Experimental

**Comment by okiehsch** [comment]
That is the default setup,
