### ISSUE TITLE
EasyPrivacy is blocking Facebook photo upload

### ISSUE THREAD

**Issue by rorosaurus** [uBlockOrigin/uAssets#367]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

facebook.com

### Describe the issue

Can't upload photos in messages on facebook.  I see requests to these domains getting blocked in logger.
pixel.facebook.com
upload.facebook.com

### Notes

Many other users reporting this issue on the main repo: https://github.com/gorhill/uBlock/issues/2536

using the logger, I found:
```
Static filter ||facebook.com/ajax/*logging found in:
EasyPrivacy
Static filter ||pixel.facebook.com^ found in:
EasyPrivacy
```

**Comment by rorosaurus** [comment]
Workaround, for those unwilling to wait for the static filter to update:

Add the below lines to your temporary/permanent rules. These were generated by clicking the "--" column on the problematic rows (during the upload) in logger, then using the "Dynamic URL filtering" UI to toggle all the blocked items to allowed.

```
www.facebook.com https://pixel.facebook.com image allow
www.facebook.com https://pixel.facebook.com/ajax image allow
www.facebook.com https://pixel.facebook.com/ajax/photos image allow
www.facebook.com https://pixel.facebook.com/ajax/photos/waterfall.php image allow
www.facebook.com https://upload.facebook.com xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax/mercury xmlhttprequest allow
www.facebook.com https://upload.facebook.com/ajax/mercury/upload.php xmlhttprequest allow
```

**Comment by SMed79** [comment]
Did you try to update your filter before posting ?!

**Comment by SMed79** [comment]
@rorosaurus No crossposting please https://github.com/gorhill/uBlock/issues/2536#issuecomment-293871863

**Comment by gorhill** [comment]
https://forums.lanik.us/viewtopic.php?p=116562#p116562

Just force an update of EasyPrivacy, this was [fixed in EasyPrivacy more than a day ago](https://github.com/easylist/easylist/commit/ccb52c31d1167a9398ee5cb01f8ed57efdb01a4e).

**Comment by Mikerox9** [comment]
Thank you!

**Comment by rorosaurus** [comment]
@SMed79 per https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md, 

> For filter-related issues, report on the respective filter list support site, or at uBlockOrigin/uAssets.

That's why I created this issue here.

**Comment by neroux** [comment]
> No code change, just a re-package with more recent filter lists to ensure uBlock Origin works out of the box with EasyPrivacy without breaking Facebook

@gorhill Does ublock come for a particular reason with packaged lists? Those pre-configured would get updated on the first run anyhow I would presume
