### ISSUE TITLE
tsa-algerie.com

### ISSUE THREAD

**Issue by BoFFire** [uBlockOrigin/uAssets#3674]
Hi, please add these.

### URL(s) where the issue occurs

```
! 09/10/2018 à 12:14:41 https://www.tsa-algerie.com/
www.tsa-algerie.com##div.ads-bloc:nth-of-type(4)

! 09/10/2018 à 12:15:04 https://www.tsa-algerie.com/
www.tsa-algerie.com###div-gpt-ad-1536847352119-0

! 09/10/2018 à 12:15:21 https://www.tsa-algerie.com/
www.tsa-algerie.com##div.ads-bloc:nth-of-type(2)

! 09/10/2018 à 12:15:32 https://www.tsa-algerie.com/
www.tsa-algerie.com##div.ads-bloc:nth-of-type(5)

! 09/10/2018 à 12:15:45 https://www.tsa-algerie.com/
www.tsa-algerie.com##div.ads-bloc:nth-of-type(6)

! 09/10/2018 à 12:16:22 https://www.tsa-algerie.com/interpellation-dun-de-ses-journalistes-par-les-renseignements-la-folle-matinee-dennahar-tv/
www.tsa-algerie.com##.anarticle__content > .ads-bloc

! 09/10/2018 à 12:16:35 https://www.tsa-algerie.com/interpellation-dun-de-ses-journalistes-par-les-renseignements-la-folle-matinee-dennahar-tv/
www.tsa-algerie.com##div.ads-bloc:nth-of-type(3)

! 09/10/2018 à 12:17:05 https://www.tsa-algerie.com/economie/
www.tsa-algerie.com##.layout__section.mobile-view.ads-under-data

! 09/10/2018 à 12:17:23 https://www.tsa-algerie.com/economie/
www.tsa-algerie.com##li.category__mobile-ads:nth-of-type(3)

! 09/10/2018 à 12:17:46 https://www.tsa-algerie.com/economie/
www.tsa-algerie.com##li.category__mobile-ads:nth-of-type(7)

! 09/10/2018 à 12:18:00 https://www.tsa-algerie.com/economie/
www.tsa-algerie.com##.category__bottom > .category__outer > .category__main > .category__main-wrap > .category__highlighted-grid > .category__mobile-ads

! 09/10/2018 à 12:21:04 https://www.tsa-algerie.com/sport/
www.tsa-algerie.com##.mobile-ads

! 09/10/2018 à 12:22:18 https://www.tsa-algerie.com/piston-a-sonatrach-ould-kaddour-botte-en-touche/
www.tsa-algerie.com##.desktop-ff-ads

! 09/10/2018 à 12:22:51 https://www.tsa-algerie.com/piston-a-sonatrach-ould-kaddour-botte-en-touche/
www.tsa-algerie.com##.article__side > div.nf-aside-ads:nth-of-type(2)

! 09/10/2018 à 12:23:09 https://www.tsa-algerie.com/piston-a-sonatrach-ould-kaddour-botte-en-touche/
www.tsa-algerie.com##div > div.nf-aside-ads:nth-of-type(1)

! 09/10/2018 à 12:23:34 https://www.tsa-algerie.com/piston-a-sonatrach-ould-kaddour-botte-en-touche/
www.tsa-algerie.com###nf-fixed-ads

! 09/10/2018 à 12:24:24 https://www.tsa-algerie.com/piston-a-sonatrach-ould-kaddour-botte-en-touche/
www.tsa-algerie.com##.article__side > div.nf-aside-ads:nth-of-type(1)
```
### Versions

- Browser/version: [Firefox Nightly on Android]
- uBlock Origin version: [1.17.1b1]

**Comment by mapx-** [comment]
Report here:
https://forums.lanik.us/viewforum.php?f=91

explaining the issue

**Comment by BoFFire** [comment]
Already reported. None wants to fix this.

https://forums.lanik.us/viewtopic.php?f=91&t=41658

**Comment by BoFFire** [comment]
Explanation : grey squares everywhere. Is it due to another filterset ?

https://vgy.me/UPKTKK.png

**Comment by mapx-** [comment]
Refrain from such allegations

@smed79 already told you:
`Le problème vient de votre adblock, donc le plus approprié est de signaler votre problème sur son forum.`

**Comment by mapx-** [comment]
provide the page address for this screenshot
https://vgy.me/UPKTKK.png

**Comment by BoFFire** [comment]
The page address for this screenshot is the main domaine name of the Website :)

New screenshot : https://vgy.me/8G0rtV.png

URL :  https://www.tsa-algerie.com/

**Comment by BoFFire** [comment]
May be it’s better to see with a video ?

 https://tube.openalgeria.org/videos/watch/52bd8f8a-4a2e-4880-b415-8dbd9641f740

**Comment by smed79** [comment]
@mapx- 
> explaining the issue

the blank ad spaces is hidden in Adblock Plus (firefox mobile) and Adblock Browser for iOs & Androis but not in uBlockOrigin (firefox mobile)

generic filters found in **Liste FR**
```
##.ads-bloc
##.mobile-ads
##.desktop-ff-ads
##.ads-under-data
##.category__mobile-ads
##.nf-aside-ads
###nf-fixed-ads
```

@BoFFire test these filters
```
tsa-algerie.com##[id*="ads"]
tsa-algerie.com##[class*="ads"]
```

@gorhill fyi.

**Comment by gorhill** [comment]
Un-check _"Disable generic cosmetic filters"_ in _"Filter lists"_ pane.

**Comment by gorhill** [comment]
Best would be however to have specific filters in EasyList France for the site -- for mobile devices, disabling generic and relying strictly on specific cosmetic filters is always best for uBO but also for other blockers.

**Comment by gorhill** [comment]
@BoFFire I suggest you report your issue to Adguard Mobile filters if you do not want to enable generic cosmetic filtering, I see their list also contains filters for various regions, so there is a chance they will accept fixing the issue for their mobile-specific filter list (Adguard Mobile Filters is enabled by default in uBO/Firefox for Mobile).

**Comment by smed79** [comment]
> I’m trying to build a little list on Gitlab

see https://forums.lanik.us/viewtopic.php?f=84&t=35435
