### ISSUE TITLE
Kissmanga.com mass banning people for using ublock

### ISSUE THREAD

**Issue by Question2** [uBlockOrigin/uAssets#3675]
Same issue as the one in this ticket, just for a slightly different site : https://github.com/uBlockOrigin/uAssets/issues/2719

Kissmanga and Kissanime are operated by the same admin. He started mass banning people who use his sites for having ublock. Theres some sort of script that detects if you are using ublok and bans you for using it. 

Any ideas on how to bypass the script? Theres one posted in the other ticket, but its for kissanime, not kissmanga.

**Comment by okiehsch** [comment]
If you are already getting the "Site is down for maintenance" message you have to add
````
||linkedin.com^$script,redirect=noopjs,domain=kissmanga.com
||googletagmanager.com/gtag/js$script,redirect=noopjs,domain=kissmanga.com
````
then delete the sites cookies, change your IP and reload.
Works on my end, example link: 
````
http://kissmanga.com/Manga/Gekiman/Vol--001-Ch-001----The-Extreme-Manga-Artist---Nagai-Geki?id=450520
````

**Comment by uBlock-user** [comment]
Did you try the filters suggested over reddit - https://www.reddit.com/r/uBlockOrigin/comments/9lxpks/kissmangacom_manga_not_loading_revenge_against/e7a9tgg/ ?

**Comment by Question2** [comment]
Gonna see if changing my IP will work, but the filters as they are now do not work.

**Comment by okiehsch** [comment]
> the filters as they are now do not work.

You have to add 

````
||linkedin.com^$script,redirect=noopjs,domain=kissmanga.com
||googletagmanager.com/gtag/js$script,redirect=noopjs,domain=kissmanga.com
````
to **your** filter list.
It still work on my end.

**Comment by Question2** [comment]
Yes, thats what i did, but im still getting the maintenance message.

**Comment by okiehsch** [comment]
If you get the maintenance message you have to delete cookies and change your IP, that's waht I had to do too.
If you don't you will get the maintenance message even if you disable uBlock.

**Comment by uBlock-user** [comment]
`kissmanga.com##+js(setTimeout-defuser.js, /YANABWEKA|HATEDBSDIDSY/) `

that fixes both the ban msg and the hiding of the images.

**Comment by uBlock-user** [comment]
FYI, after adding the above filter I posted, you will still need to delete cookies and all site data related to kissmanga.com if you're already banned.

**Comment by Question2** [comment]
Thanks, its working now.
