### ISSUE TITLE
Twitter user blocked due to name resembling something with ads.

### ISSUE THREAD

**Issue by datastory** [uBlockOrigin/uAssets#3676]
### URL(s) where the issue occurs

`https://twitter.com/adbar`

### Describe the issue

Tweets form twitter user *adbar* can´t be clicked through (it ends with "Something went wrong Twitter message."), it´s caused probably by username resembling some bar with ads. Without uBlock Origin it works fine.

### Versions

- Browser/version: Google Chrome v. 69.0.3497.100 on Win 10
- uBlock Origin version: 1.17.0

**Comment by mapx-** [comment]
Could you test this filter ?
`@@||twitter.com/*/profiles/show/adbar/$xmlhttprequest,first-party`

@ryanbr

**Comment by smed79** [comment]
```
@@||twitter.com^*/status/*?conversation_id=$xmlhttprequest,~third-party
@@||twitter.com/i/profiles/show/*/media_timeline?$xmlhttprequest,~third-party
@@||twitter.com/i/profiles/show/*/timeline/tweets?$xmlhttprequest,~third-party
```

**Comment by mapx-** [comment]
```
@@||twitter.com/*/profiles/show/adbar/$xmlhttprequest,first-party
@@||twitter.com/adbar/$xmlhttprequest,first-party
```

**Comment by smed79** [comment]
other examples
```
https://twitter.com/adsense
https://twitter.com/googletracker
https://twitter.com/adshow
https://twitter.com/advstats
https://twitter.com/adfly
https://twitter.com/advt
https://twitter.com/adsen
https://twitter.com/adserver
```

**Comment by okiehsch** [comment]
How about
````
@@||twitter.com/*/profiles/$xmlhttprequest,first-party
@@||twitter.com/*/status/*conversation_id$xmlhttprequest,first-party
````

**Comment by mapx-** [comment]
other xhr are blocked such as:
```
https://twitter.com/AdSense/following
https://twitter.com/AdSense/likes
```
and so on, but somehow then will land on those pages

so .. let's add those "generic" filters
