### ISSUE TITLE
flickr got broken by unbreak

### ISSUE THREAD

**Issue by lucamp** [uBlockOrigin/uAssets#3679]
### URL(s) where the issue occurs

`https://www.flickr.com/`

### Describe the issue

loading starts but the entire page got blanked

### Versions

- Browser/version: Firefox 60.2.2 esr 64bit
- uBlock Origin version: 1.17.0

### Settings

these are checked on my setting:

Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate 
Disable pre-fetching (to prevent any connection for blocked network requests)
Disable hyperlink auditing

### Notes

disabling ublock unbreak filter resolve this issue, I am afraid but I do not know what part of the filter is involved

Thanks
Luca

**Comment by mapx-** [comment]
- filter lists enabled in uBo ?
- where does happen ? main page ? specific page ? needing login ?
- did you look into the logger ? what filters are triggered ?

**Comment by lucamp** [comment]
filters:

uBlock filters​​​​​
​​uBlock filters – Badware risks​
​​uBlock filters – Privacy​​​​​
​​uBlock filters – Resource abuse​​​​​
Malware Domain List​​​​​
​​Malware domains
IDN: ABPindo​​​​​
​​ITA: ABP X Files​
​​​​X Files: HWS Harmful WebSites​​
​​X Files: NoCoin List

it happens on entire site, login not required

Unbreak and Privacy are triggered. As I wrote disabling unbreak solve it

**Comment by mapx-** [comment]
> did you look into the logger ? what filters are triggered ?

I mean the single filters you see on the left column in the logger

**Comment by lucamp** [comment]
-google-analytics/$third-party found in:    uBlock filters – Unbreak
||google-analytics.com/analytics.js$script found in:    uBlock filters – Privacy

**Comment by mapx-** [comment]
It's fixed in easylist. I don't see easylist in your lists above.

necessary filter:
`@@||yimg.com/zz/combo?*&*.js`

**Comment by lucamp** [comment]
easylist is not installed in my ublock, On my former pc it was just to heavy and I used only ​​"ITA: ABP X Files​", since then I have never feel the need to enable it

Thanks
