### ISSUE TITLE
Kanye West blocks uBlock

### ISSUE THREAD

**Issue by arjunmenon** [uBlockOrigin/uAssets#368]
On Firefox in Private browsing while just wasting time browsing youtube, ads in video were not blocked.
And it was while browsing music and reaching his channel.
This strangely did not work on any other music channels.
![screenshot from 2017-04-13 23 21 15](https://cloud.githubusercontent.com/assets/953959/25017354/0c203aee-20a1-11e7-92d1-afbbfebe0932.png)
You can see that uBlock and Ghostery are both working. _(I am sorry I couldn't get the logger. I had restarted the session)_

This looks like a one off, it didn't happen again with a restarted session.

========
Little update.
It happened again. I am attaching a txt file with the logger output.
[ublock.txt](https://github.com/uBlockOrigin/uAssets/files/920501/ublock.txt)

**Comment by gorhill** [comment]
Can't reproduce, so I won't be able to investigate. Hopefully someone who can reproduce can come up with a filter.

**Comment by uBlock-user** [comment]
Cannot reproduce here either. Force update all your filters, destroy all cache and site data related to `youtube.com`

**Comment by Hrxn** [comment]
Try it without Ghostery, I don't think you really need it..

**Comment by FrostKnight** [comment]
Ghostery sells information and is very proprietary. IF you want privacy do not trust ghostery...

**Comment by 07416** [comment]
Very bad title.

**Comment by FrostKnight** [comment]
On 09/11/2017 12:35 PM, 07416 wrote:
>
> Very bad title.
>
Is this serious? I have a feeling someone is trolling regardless if true
or not.

IT would be entertaining if I didn't dislike Kanye...

**Comment by Hrxn** [comment]
Not really.
BTW, I think this can be closed..
