### ISSUE TITLE
Twitter embedded media got cut off

### ISSUE THREAD

**Issue by blue-lightning** [uBlockOrigin/uAssets#3680]
### URL(s) where the issue occurs

`https://kotaku.com/japanese-crime-recreated-with-cg-hilarity-ensues-1829384584`

### Describe the issue

Twitter embedded media gets cut off.

### Versions

- Browser/version: Firefox 62.0.3 x64 on Windows 10 x64
- uBlock Origin version: 1.17.0

### Settings

- Default

### Notes

Cross-post from the [easylist github](https://github.com/easylist/easylist/issues/1934). The fix in "uBlock filters -- Unbreak" doesn't work for me even after forcing an update.

**Comment by mapx-** [comment]
What filter lists are enabled in uBo ?

**Comment by blue-lightning** [comment]
Only EasyList and uBlock Unbreak.

**Comment by mapx-** [comment]
Test these filters
```
kotaku.com#@##dfp-ad-2
kotaku.com#@##dfp-ad-1
```

**Comment by blue-lightning** [comment]
Just paste them into "My filters", right? The clips are still cut off.

**Comment by mapx-** [comment]
Did you press ctrl F5 ? (bypassing the cache)

**Comment by blue-lightning** [comment]
Yep.

**Comment by okiehsch** [comment]
````
kotaku.com#@##dfp-ad-2
kotaku.com#@##dfp-ad-1
````
works fine on my end.

You can add
`@@||kotaku.com^$generichide`
to your filter list.

**Comment by blue-lightning** [comment]
mapx-'s filters result in all twitter embedded media and css get removed:

![image](https://user-images.githubusercontent.com/11144551/46845218-af3cf980-ce04-11e8-8884-eb652e023a5a.png)

okiehsch's filter sometimes result in some twitter embedded media and css get removed. Did it timeout or something? I'd rather go with okiehsch's since more often than not it works correctly.

![image](https://user-images.githubusercontent.com/11144551/46845329-39855d80-ce05-11e8-8db8-22c3b02a6c7e.png)

**Comment by okiehsch** [comment]
The filters that are causing the issue with Firefox are the ones **mapx-** filters disables.
If this does not work for you, you can add "my" filter to your own list or [disable generic cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) at `kotaku.com`.

**Comment by blue-lightning** [comment]
Disabling generic cosmetic filtering works consistently though it's not really an idea solution, because now there's huge spaces at the top of the site. But I guess that will have to do. Thanks.
