### ISSUE TITLE
quora.com non-ad feed stories getting blocked by uBlock Origin

### ISSUE THREAD

**Issue by spittingmadtruth** [uBlockOrigin/uAssets#3683]
### URL(s) where the issue occurs

`https://www.quora.com/`

### Describe the issue

Quora non-ad feed stories get blocked using uBlock Origin.

#### Without uBlock Origin
![image](https://user-images.githubusercontent.com/40901446/46826524-08e0ed80-cd4b-11e8-83c0-ce9c55005f39.png)

#### With uBlock Origin
![image](https://user-images.githubusercontent.com/40901446/46826508-fa92d180-cd4a-11e8-899f-dd2d33e1f459.png)

### Versions

- Browser/version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.17.0

### Settings

Default

### Notes

Investigated using the uBlock Logger, and found that the problematic filter is `quora.com##:xpath(//a[@rel="noopener nofollow"][not(@data-qt-tooltip)]/../../../..)`

**Comment by ZaphodBeebblebrox** [comment]
I cannot get any link posts to show up in the feed of the test account I created, so I cannot test this.

**Comment by okiehsch** [comment]
I can reproduce, example
`https://www.quora.com/topic/Technology`
all "Link" posts are hidden.
`quora.com##.FeedStory:has-text(promoted)`
seems to work on my end in regard of hiding the ads without any breakage.

**Comment by spittingmadtruth** [comment]
@ZaphodBeebblebrox Try visiting this url with and without enabling uBlock Origin: `https://www.quora.com/link/We-Try-to-Learn-Every-Terrorist-Attack-Inside-the-Top-Secret-Israeli-Anti-Terrorism-Operation-That-s-Changing-the-Game`
