### ISSUE TITLE
fm.tuba.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#3685]
### URL(s) where the issue occurs

`http://fm.tuba.pl/play/58/0/radio-aaliyah`

### Describe the issue

Annoying confirm dialog when changing radio stations.

### Screenshot(s)

![screenshot_20181012_190028](https://user-images.githubusercontent.com/19818572/46883076-197b8b80-ce51-11e8-868a-4f5c2667a5ec.png)

### Versions

- Browser/version: Vivaldi 2.0.1309.29

- uBlock Origin version: 1.17.0

### Settings

- ![screenshot_20180913_172516](https://user-images.githubusercontent.com/19818572/45498273-0013f080-b77a-11e8-916a-bb13b0b29970.png)

### Notes

I tried `fm.tuba.pl##script:inject(set-constant.js, confirm, trueFunc)` and it works, but I would rather safer method :smile:. It'll be maybe better if I can add this rule only for `fm.tuba.pl/play`.

**Comment by ZaphodBeebblebrox** [comment]
@MajkiIT, do you want to deal with this?

**Comment by hawkeye116477** [comment]
I can add that to Polish Annoyance Filters, but as I didn't find better solution, I just wanted to ask for advice from wiser people :smile:.

**Comment by ZaphodBeebblebrox** [comment]
It seems like a fine filter to me. Unfortunately, there is no way to make the filter only apply to fm.tuba.pl/play

**Comment by okiehsch** [comment]
I agree, I don't see a better filter.
