### ISSUE TITLE
Anti adblock on debridnet.com

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#369]
### URL(s) where the issue occurs
http://debridnet.com/

### Describe the issue
When you go on http://debridnet.com/ you are redirect to http://debridnet.com/ad-blocker

### Screenshot(s)
see http://debridnet.com/ad-blocker

### Note
Ublock: 1.12
with default fileters + Fanboy’s Annoyance List + hpHosts’ Ad and tracking servers + MVPS HOSTS

**Comment by xhamid** [comment]
https://github.com/reek/anti-adblock-killer#instruction

**Comment by SMed79** [comment]
@xhamid 

Anti-Adblock Killer **Continued** https://gitlab.com/xuhaiyang1234/AAK-Cont#anti-adblock-killer-continued
**uBlock** Protector https://github.com/jspenguin2017/uBlockProtector
