### ISSUE TITLE
New Unbabify scan

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3692]
@okiehsch 
```
http://animehd24.blogspot.com/
https://www.ostuninotizie.it/
https://www.ogznet.com/
```
![image](https://user-images.githubusercontent.com/7283682/46895292-fe9b1e00-ce34-11e8-9e94-08a1bb2d2d71.png)

Note: Previous scan: https://github.com/NanoMeow/QuickReports/issues/178

---

`https://www.informagiovani-italia.com/` also has BAB installed, but for some reason it crashes itself.

**Comment by mapx-** [comment]
`informagiovani-italia.com` no issue here
