### ISSUE TITLE
NSFW pornoman.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3696]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://pornoman.pl/strony/sliczna-robota-rudej-dziewczyny,13561`

### Describe the issue

anty-adblock

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by ZaphodBeebblebrox** [comment]
@MajkilT popunder `pornoman.pl##+js(abort-current-inline-script.js, atob, tabunder)`
