### ISSUE TITLE
Gravity 3rd-party recommendations

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#37]
### URL(s) where the issue occurs

1.
`http://www.dailymotion.com/video/x43mtv0_eng-sub-160404-tvn-dream-players-ep-2-mamamoo-cut_fun`
NSFW: `http://www.gotporn.com/`

2.
`http://www.engadget.com/2016/04/27/dear-veronica-the-bots-are-taking-over/`
`http://www.cheatsheet.com/`

3.
`http://www.gravity.com/blog/meet-the-graviteers-tom-chappell/`
### Describe the issue

Recently unblocked by EasyList: https://forums.lanik.us/viewtopic.php?f=64&t=30024
Seems like a similar case to [this](https://github.com/uBlockOrigin/uAssets/blob/master/filters/privacy.txt#L32).
Or do they just collect the information? Because I don't see them actually serving any recommendations. Possibly the recommendations are getting served through another channel.
### Notes

1.
`||gravityrd-services.com^$third-party`

2.
`||grvcdn.com^$third-party`

3.
Used on their blog and listed a couple of times in hpHosts. Also applies to sites under 2. when `grvcdn.com` is allowed:
`||gravity.com^$third-party`

**Comment by gorhill** [comment]
I see it used on techcrunch too: `http://techcrunch.com/2016/05/03/adblock-plus-teams-up-with-flattr-to-help-readers-pay-publishers/` ("recommended for you by Gravity"). This deserved to be blocked through a privacy filter.

**Comment by okiehsch** [comment]
Fixed with https://github.com/uBlockOrigin/uAssets/commit/f22a8fe42d10612519668b95d8144fd41280f16d and https://github.com/uBlockOrigin/uAssets/commit/2ef5b89ae6a6dab7f4d08d020b1700344734e279
