### ISSUE TITLE
all-in.de Anti-AdBlock

### ISSUE THREAD

**Issue by thetommes** [uBlockOrigin/uAssets#370]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
Happens on every site on this page, for example:
https://www.all-in.de/
https://www.all-in.de/nachrichten/lokales/Seeger-Bauernfamilie-schickt-Huehner-im-mobilen-Stall-auf-die-Wiese;art26090,2440831

### Describe the issue

This site shows a big red anti-adblock message and changes the font to Comic Sans when using uBlock

### Screenshot(s)

https://i.imgur.com/GheT0Ri.jpg

### Versions

- Browser/version: Chrome 57.0.2987.133 (64-bit)
- uBlock Origin version: 1.12.0

### Settings

My filterlists: https://i.imgur.com/9tg1e6C.png

### Notes

Cleared Cookies, message still appears. Tested on multiple PC's.

**Comment by okiehsch** [comment]
Add `@@||all-in.de^$generichide`
This can be fixed by Easylist , you can report it at `https://forums.lanik.us/viewforum.php?f=90`

**Comment by yoshimo** [comment]
The code mentions BlockAdblock.
Shouldn't
`all-in.de##script:inject(bab-defuser.js)`
solve it as well?

**Comment by okiehsch** [comment]
This site does not use `BlockAdblock` , so `all-in.de##script:inject(bab-defuser.js)` will not work.
If you do not want to use `generichide` you can add
`all-in.de##script:inject(abort-on-property-write.js, blockAdblockUser)`

**Comment by gorhill** [comment]
@yoshimo `bab-defuser.js` is to foil anti-blocker mechanism published by `blockadblock.com`. Sometimes, `blockAdblock` is also a variable name used by the script from `fuckAdBlock` (somewhere here on GitHub). In the current case, it's unrelated to the two former anti-blockers, it's just a custom script from the site itself -- "blockAdblock" is kind of a generic expression.

**Comment by thetommes** [comment]
Reported this to german Easylist but it seems like no one cares...
Any other way to get this filter into an offical list?
https://forums.lanik.us/viewtopic.php?f=90&t=36402&sid=6320396a3336137d55ab472b9b247f46

**Comment by gorhill** [comment]
Probably because it is not really an anti-blocker, it does not prevent the content from being accessed.
