### ISSUE TITLE
msn.com [Ads]

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uAssets#3703]
### URL(s) where the issue occurs

`https://www.msn.com/es-xl/`

### Describe the issue

Ads

### Versions

- Browser/version: Opera browser 56.0.3051.36
- uBlock Origin version: 1.17.0

### Settings

- Checked all filter lists

**Comment by ZaphodBeebblebrox** [comment]
For msn, you need [uBO-extra](https://github.com/gorhill/uBO-Extra) on chromium based browsers.

**Comment by MS-PC** [comment]
Ok, thanks.

**Comment by ghajini** [comment]
ads over here
of `api.taboola.com`
link=
`https://www.msn.com/en-in`
***how to produce***=
click on next arrows 3 times(like swipe news articles)
![screenshot 49 1](https://user-images.githubusercontent.com/20338483/47855285-2b29d080-de0a-11e8-86f0-7e04668294dc.png)

**Comment by kulfoon** [comment]
Not fixed.

**Comment by ghajini** [comment]
yes not fixed

**Comment by kulfoon** [comment]
`msn.com##.extnativeaditem, .serversidenativead > h3` solution effect will be:

<details not-open>
<summary>screenshoot</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47862131-b5673a00-ddf4-11e8-9b8e-fab2b8bcf24b.png)

</details>
.

Only for "sponsored" block of course.
 I just don't know if it is a satisfactory solution.
Anyway, it can serve as a temp solution, until a better one will be found or a script:inject one.

**Comment by ghajini** [comment]
`https://www.msn.com/en-in/entertainment/bollywood/priya-prakash-varrier-and-vicky-kaushal-recreate-her-finger-gun-kiss-and-it-is-adorable-watch-video/ar-BBSaxMc`

i don't know where to report this as instagram embed in this site is broken
after you watch instagram video(1st time),it will play video
![screenshot 96](https://user-images.githubusercontent.com/20338483/51100759-88280680-17fd-11e9-933b-367fc37a20df.png)

 and again if you click 
`watch again on instagram`,
![screenshot 97](https://user-images.githubusercontent.com/20338483/51100752-7a728100-17fd-11e9-958b-881ca4437089.png)

 nothing happens(as should be it to allow that video to watch again)

**Comment by mapx-** [comment]
see if works
```
@@||instagram.com/*embed_video$popup,domain=msn.com
@@||instagram.com/accounts/login/$popup,domain=msn.com
```

**Comment by ghajini** [comment]
thanks

**Comment by mapx-** [comment]
@ryanbr

**Comment by ghajini** [comment]
ads on homepage
`https://www.msn.com/en-in/`
![screenshot 99](https://user-images.githubusercontent.com/20338483/51120121-6b5df400-183a-11e9-802f-e4acbe0f46e9.png)

**Comment by mapx-** [comment]
`msn.com##a.nativead`

@ryanbr
