### ISSUE TITLE
[Annoyance] sabishiidesu.com, naijapary.ng

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3704]
### URL(s) where the issue occurs

`https://sabishiidesu.com`

Update: Also `https://naijapary.ng/`

### Describe the issue

Anti-right click, anti-select, anti-copy, and anti-view-source (Ctrl+U). 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/46911667-4480e080-cf20-11e8-99a9-1acf4d58fbeb.png)

### Versions

- Browser/version: Chrome 71
- uBlock Origin version: 1.17.0

### Settings

All default.

**Comment by jspenguin2017** [comment]
Also FAB.

**Comment by jspenguin2017** [comment]
@okiehsch Another similar one: `https://naijapary.ng/`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/aeae976836caf923be1179021563ee15058747fc
