### ISSUE TITLE
babesxworld.com[NSFW]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#3706]
### URL(s) where the issue occurs

`http://www.babesxworld.com/en/`

### Describe the issue

[Stripper popup and clicking on a gallery launches a completely different page instead of the normal site. The gallery is always hosted on the main site not any of the off brand sites that popup.]

### Versions

- Browser/version: [ 69.0.3497.100]
- uBlock Origin version: [1.17.0]

### Settings

- [Default]

### Notes

About the gallery thing you have to right click or middle mouse click the picture a few times to get the correct site. I don't know why it does this exactly but it's irritating.

**Comment by ZaphodBeebblebrox** [comment]
@mapx-, is there a reason you did not close this issue? The site seems to be fine to me.

**Comment by mapx-** [comment]
yeah, I'm not sure if it's something to do for:
`clicking on a gallery launches a completely different page instead of the normal site`

**Comment by ZaphodBeebblebrox** [comment]
Its being done by the script below, but I do not know how to defuse it without breaking the site.
```
let hreff = document.getElementsByTagName("a");
for (var i = 0; i < hreff.length; i++) {
    if (hreff[i].getAttribute("data-href") !== null) {
        hreff[i].setAttribute("href", hreff[i].getAttribute("href") + hreff[i].getAttribute("data-href"));
    }
    if (hreff[i].getAttribute("data1-href") !== null) {
        hreff[i].setAttribute("href", hreff[i].getAttribute("data1-href"));
    }
}
$("img.lazyload").lazyload({
    threshold: 200
});
```

**Comment by ZaphodBeebblebrox** [comment]
Does `babesxworld.com##+js(set-constant.js, document.getElementsByTagName, trueFunc)` cause anything to break for you?

**Comment by mapx-** [comment]
@ZaphodBeebblebrox it seems working fine

**Comment by ZaphodBeebblebrox** [comment]
Tested some more, it stops thumbnails from expanding.

**Comment by okiehsch** [comment]
`*$third-party,popup,domain=babesxworld.com` seems to be the best fix possible.

**Comment by ZaphodBeebblebrox** [comment]
I hate fixes like this, they just feel ugly.

**Comment by dumbusernameidk** [comment]
Third party script causing fake push notifications to appear `||truesweb.com^` also `onbeforeunload` event being used to "prevent" you from leaving/refreshing the page. 

I also notice this script being one of the many exo type scripts `babesxworld.com/askdrej/quwet.js` but blocking it just prevents images from loading. Bypass possible or is this script a non-issue?
