### ISSUE TITLE
t2online.com - Anti Adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#371]
No content is displayed in articles on http://t2online.com. This seems to be caused by their anti adblock mechanism in the following js (though I am not sure):
`http://t2online.com/app,_components,_search,_DNVRsearchCtrl.js,qver==9e9d4db+app,_components,_others,_DNVRothersCtrl.js,qver==9e9d4db+assets,_js,_common.js,qver==9e9d4db+assets,_js,_angulartics.min.js,qver==9e9d4db+assets,_js,_angulartics-google-tag-manager.min.js,qver==9e9d4db+assets,_js,_checkAdBlock.js,qver==9e9d4db+assets,_js,_custom.js,qver==9e9d4db.pagespeed.jc.cVBMDM71O3.js`

If you look at the above js they seem to be using **_BlockAdblock/FuckAdblock_**. But blocking the above js does not work as its also the core js of the website and blocking it completely stops the pages from loading.

**SS:** https://i.imgur.com/rpPEXVE.png (Full page screenshot showing the blocked article)
**Error URL:** http://t2online.com/tech/five-must-have-apps-for-every-android-user/cid/1.71897

**Note:** Using uBO 1.12.0 on Chrome 57 with default filters.

**Comment by okiehsch** [comment]
@gotitbro I can read all articles if  use dynamic filtering and allow `http://s7.addthis.com/js/300/addthis_widget.js`.

@gorhill this sites articles appears to be broken because of the filter
````
||addthis.com^$third-party,important
||addthis.com/*/addthis_widget.js$script,redirect=addthis.com/addthis_widget.js
````
in `uBlock filters – Privacy`, the filter uses the `important` syntax, so I can't use uBO-unbreak to fix the issue.
