### ISSUE TITLE
Paywall overlay on Liberation.fr

### ISSUE THREAD

**Issue by StanGets** [uBlockOrigin/uAssets#3716]
Hi,

uBlock Origin 1.17.0 / Firefox 62.0.3 (x64) / Windows 7 (x64)

Paywall overlay after having scrolled a few lines on liberation.fr articles, such as:
https://www.liberation.fr/france/2018/10/16/perquisitions-au-siege-de-la-france-insoumise-et-chez-jean-luc-melenchon_1685641

![screengrab-2018-10-16-12 05 16](https://user-images.githubusercontent.com/42912760/47009877-d44fa600-d13d-11e8-807c-22cc4fc409c9.jpg)

No idea if paywalls removal is legitimate considering they are not ads. If not then please forgive my ignorance, I'll know from now on, and feel free to close this thread.

Thanks!

**Comment by uBlock-user** [comment]
```
liberation.fr##.pws
liberation.fr##body:style(overflow: auto !important;)
```

**Comment by mapx-** [comment]
We don't add filters to defeat the paywalls.

**Comment by uBlock-user** [comment]
Logger shows it has anti adblock bait script.

**Comment by StanGets** [comment]
@uBlock-user works nicely, thanks!

I understand the policy that differentiates ads from paywalls and I therefor search for anti-paywall scripts over at GreasyFork but found none for liberation.fr which is why I asked here with the idea my quest could bypass uBO's policy. Nevertheless I appreciate @uBlock-user help.

**Comment by uBlock-user** [comment]
It's likely a mix of both.

**Comment by StanGets** [comment]
> It's likely a mix of both.
That brings legitimacy of intervening to a step forwards :)
Anyway I personally have no scruple to block a paywall given the fact I wouldn't subscribe to a media because of its paywall. But I do acknowledge uBO's policy, honest.
