### ISSUE TITLE
Some ads not being blocked

### ISSUE THREAD

**Issue by Sleazy89** [uBlockOrigin/uAssets#372]
### URL(s) where the issue occurs
`
[http://multiplayer.it/notizie/182215-star-wars-battlefront-ii-la-cooperativa-in-split-screen-di-star-wars-battlefront-ii-sara-unesclusiva-console.html]`

Some ads are not being blocked, e.g. the minigame which appears right OVER the articles in almost every page. 

### Screenshot(s)

![grootcrap](https://cloud.githubusercontent.com/assets/12986766/25085884/be09b472-2364-11e7-9d1d-4f494c3c0c05.jpg)

### Versions

- Browser/version: [Mozilla Firefox 52.0.32 and Chrome 57.0.2987.133]
- uBlock Origin version: [1.12.1]

### Settings

- [Using uBlock filters, ublock filters - badware, privacy and unbreak, adblock warning removal, anti-andblock killer, easylist, easyprivacy, malware domain/s, peter lowe's ad and tracking server list and easylist italy]

### Notes

[Webiste has an anti-ablocker. If you use one, you can't watch videos. I avoided this problem with custom filters:

@@||multiplayer.it^$generichide
@@||imasdk.googleapis.com^$domain=multiplayer.it

but different users don't know that and are lamenting the issue. For what concerns this report issue instead, I managed to block the ad with manual element blocking:

||guardiansofthegalaxy2.movieplayer.it/static/bomba-mani.png$image - etc. for the other images.

Fact being that "movieplayer.it is their "brother" website and everytime a new movie comes out every user has to manually add the filter (those who know how to do that). Isn't there any way to add this to standard filters as an update?

Thanks!

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=116826#p116826
