### ISSUE TITLE
pichotgallery2018c.pw [NSFW]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#3724]
### URL(s) where the issue occurs

`[http://pichotgallery2018c.pw]`

### Describe the issue

[I'm almost positive this website has a miner going to the site sees one of my chrome processes in task manager spike to 80% cpu utilization. Leaving the site returns the cpu usage to normal and the same for disabling inline scripts. I can't seem to find the script itself but I did notice "coinzilla" when i was looking at the html code.]

### Versions

- Browser/version: [69.0.3497.100 ]
- uBlock Origin version: [1.17.0]

### Settings

- [Default]

**Comment by smed79** [comment]
@okiehsch add also `picflowhot.pw`
