### ISSUE TITLE
newsharecounts.s3-us-west-2.amazonaws.com/nsc.js

### ISSUE THREAD

**Issue by ryandaniels** [uBlockOrigin/uAssets#3730]
### URL(s) where the issue occurs

`https://newsharecounts.s3-us-west-2.amazonaws.com/nsc.js`

### Describe the issue

New block needed.
Issue: Malicious redirection javascript on mobile device.
On a mobile device (or desktop with a mobile user agent), a website infected with (includes this) javascript file will be impacted when they press the back button. Their browser redirects to another domain serving ads/malware/etc.

### Screenshot(s)

NA

### Versions

- Browser/version: mobile
- uBlock Origin version: any

### Settings

Default

### Notes

Some websites are using an abandoned twitter count javascript file, which was re-registered by someone else and now serving malicious javascript.
More details: https://blog.sucuri.net/2018/10/malicious-redirects-from-newsharecounts-com-tweet-counter.html

**Comment by smed79** [comment]
e.g.
```
https://byrdnick.com/
http://www.fushionmag.com/
https://ibankcoin.com/
https://www.nexthardware.com/
https://www.onepagecrm.com/
https://www.carbase.my/
https://www.marklogic.com/
https://www.marieforleo.com/
https://klientboost.com/
```
