### ISSUE TITLE
kmbc.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#3731]
### URL(s) where the issue occurs

`https://www.kmbc.com/article/conservative-site-s-hidden-camera-prompts-mccaskill-outrage/23879575`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/47126298-dd339b00-d255-11e8-98bf-d3040aa003e5.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.17.0

**Comment by smed79** [comment]
test
```
kmbc.com##+js(abort-current-inline-script.js, AdBlockDetector)
```

**Comment by terrorist96** [comment]
Doesn't work.

**Comment by okiehsch** [comment]
I am geoblocked and the site does not load correctly with my VPN.

**Comment by smed79** [comment]
@terrorist96 

I get no anti adblock message.

@okiehsch 


`https://assets.htvapps.com/themes/htv/assets/js/dist/app/viewcontrollers/Main.448356c.js`

[Main.448356c.js.txt](https://github.com/uBlockOrigin/uAssets/files/2490112/Main.448356c.js.txt)

https://i.imgur.com/yZzJNY3.png

**Comment by okiehsch** [comment]
@smed79  `adblockDetector` is the variable in `https://assets.htvapps.com/themes/htv/assets/js/dist/app/viewcontrollers/Main.448356c.js`
not `AdBlockDetector`.
Best try with `abort-on-property-read.js`.
