### ISSUE TITLE
Videos not working when uBlockO enabled 

### ISSUE THREAD

**Issue by Questors84** [uBlockOrigin/uAssets#3733]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://www.dailywire.com/podcasts/37197/ep-594-our-fauxchahontas-media]`

### Describe the issue

[www.dailywire.com > podcasts > choose which podcast to watch >  choose which episode to watch > click the watch now (start video) button > nothing happens, video won't load with uBlock Origins enabled]

### Screenshot(s)

[Not applicable - can't show a video not working]

### Versions

- Browser/version: [FireFox Quantum 62.0.3 (64-bit) ]
- uBlock Origin version: [1.17.2]

### Settings

- [no changes]

### Notes

[Disabled add-ons one at a time, cleared cache each time and revisited web site until I was able to watch the videos normally. uBlock Origins ended up being the culprit. Previous version of uBlock Origins was 1.17.0, I checked for a new version, added 1.17.2 to FireFox. Experienced the same result with the videos not working at DailyWire.com with uBlock Origins enabled. There has been no issue at YouTube.]

**Comment by mapx-** [comment]
I tested only the audio podcast (for video you need a subscription)

**Comment by smed79** [comment]
@ryanbr fyi

**Comment by Questors84** [comment]
> 
> 
> I tested only the audio podcast (for video you need a subscription)

I have a subscription.

**Comment by Questors84** [comment]
> 
> 
> ```
> @@||soundcloud.com/oembed?$script,domain=dailywire.com
> @@||googleapis.com^$script,third-party,domain=dailywire.com
> ```
> 
> @ryanbr

Is this a script to use in exceptions or white lists in uBlock Origins? I am afraid I don't know much about this sort of thing.

**Comment by mapx-** [comment]
@Questors84  I already fixed the issue in ublock unbreak. Just go into options, dashboard, filter lists, purge and update the lists

https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

**Comment by Questors84** [comment]
> 
> 
> @Questors84 I already fixed the issue in ublock unbreak. Just go into options, dashboard, filter lists, purge and update the lists
> 
> https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

Thank you.

**Comment by smed79** [comment]
@Questors84 use the logger and post here screenshots of the blocked elements

https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by Questors84** [comment]
> 
> 
> @Questors84 use the logger and post here screenshots of the blocked elements
> 
> https://github.com/gorhill/uBlock/wiki/The-logger

![ublockoriginslog](https://user-images.githubusercontent.com/44266374/47228444-3ce39080-d393-11e8-8668-af1fa26b501a.png)

**Comment by mapx-** [comment]
in "filter log entries" type `--` and post here only those entries

**Comment by Questors84** [comment]
> 
> 
> in "filter log entries" type `--` and post here only those entries

I hope this is what you need. 

![ublockoriginstypelog](https://user-images.githubusercontent.com/44266374/47256326-441aa500-d44c-11e8-9915-a56c5ca2df54.png)

**Comment by mapx-** [comment]
type ...only `--` (without `type`)

**Comment by Questors84** [comment]
> 
> 
> type ...only `--` (without `type`)

Sorry about that. 

![ublockorigins_pt_1](https://user-images.githubusercontent.com/44266374/47258304-62da6500-d467-11e8-92ec-89cab17908c5.png)
![ublockorigins_pt_2](https://user-images.githubusercontent.com/44266374/47258305-64a42880-d467-11e8-83a5-2922e908abc0.png)

**Comment by okiehsch** [comment]
Add 
`@@||vimeo.com/api/oembed$script,domain=dailywire.com`
to your filter list, then try again, if the video still won't play open the logger again and type
`|--` in the box.

**Comment by Questors84** [comment]
> 
> 
> Add
> `@@||vimeo.com/api/oembed$script,domain=dailywire.com`
> to your filter list, then try again, if the video still won't play use the logger again and copy/paste
> `|--` in the box.

added @@||vimeo.com/api/oembed$script,domain=dailywire.com to my filters. I have logged out of Daily Wire, cleared cache, re-logged and it worked. Closed out browser, re-opened three more times for each podcast and they all worked. Thank you.

**Comment by smed79** [comment]
Fixed a day ago https://github.com/easylist/easylist/commit/2bd7363d86184d2e3f2744f06a6f1bb3837c90b6. No ?
