### ISSUE TITLE
webcodegeeks.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3738]
Replace the bracketed [...] placeholders with your own information.

### Describe the issue

after 10-15 sec on join
popup in the same card

### Screenshot(s)

![2018-10-19-window](https://user-images.githubusercontent.com/5884000/47190497-016ca600-d342-11e8-961f-cee8916d8491.png)

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`
