### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by sebasvisser** [uBlockOrigin/uAssets#3739]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://blockadblock.com/

### Describe the issue

Content from webpage disappears, blank page with big warning is inserted

### Screenshot(s)

https://cl.ly/ff1213fa98cb

### Versions

- Browser/version: Version 70.0.3538.67 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.17.0

### Settings

- Added AAKlist, no other settings changed

### Notes

Tried using the element zapper, and element picker. To no avail. Looked at the source code of the website and can see the actual content disappearing after about 7 seconds when the anti ad block message loads.
Also tried nano adblock and nano defender, and tampermonkey with anti-adblock killer script

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/issues/3476

**Comment by krystian3w** [comment]
Remove AAK / AAK-cont.

* Subscribe [ `https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt` ](https://subscribe.adblockplus.org/?location=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt&amp;title=Nano%20Defender%20Integration)

* Subscribe **Nano filters** : [ `https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt` ](https://subscribe.adblockplus.org/?location=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt&amp;title=Nano%20Filters)
*  Subscribe **Nano filters - Whitelist** [ `https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt` ](https://subscribe.adblockplus.org/?location=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt&amp;title=Nano%20filters%20-%20Whitelist)

And install Nano Defender: https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

**Comment by krystian3w** [comment]
Remove AAK / AAK-cont.

* Subscribe **Nano Defender Integration**: [https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt](https://subscribe.adblockplus.org/?location=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt&amp;title=Nano%20Defender%20Integration)

* Subscribe **Nano filters** : [https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt](https://subscribe.adblockplus.org/?location=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt&amp;title=Nano%20Filters)
*  Subscribe **Nano filters - Whitelist** [https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt](https://subscribe.adblockplus.org/?location=https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt&amp;title=Nano%20filters%20-%20Whitelist)

And install Nano Defender: https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb
