### ISSUE TITLE
Are Reddit "Promoted" posts supposed to get through?

### ISSUE THREAD

**Issue by liviu-** [uBlockOrigin/uAssets#3740]
### URL(s) where the issue occurs

Reddit has dynamic personalised content, so it may not show up to you the same place where it showed up to me. Mine was on `reddit.com/r/test`, but this is a direct link to the ad: `https://www.reddit.com/comments/9opo6u/til_fewer_refers_to_items_you_can_count/`

### Describe the issue

Reddit Promoted ads show up, which I thought would be filtered.

### Screenshot(s)

![2018-10-19-101414_652x598_scrot](https://user-images.githubusercontent.com/9915183/47209653-ca6db300-d388-11e8-84c9-a4e495af6e69.png)

### Versions

- Browser/version: Firefox 61.0.1
- uBlock Origin version: 1.17.2

### Settings

I made no changes

### Notes

The classes of the `div` housing the ad indicate that an ad should be present: `promotedlink` and  `promotedvideolink`. However, I believe all ads may link to `https://www.reddit.com/comments/[id]/[slug]` which is unlike typical posts where the standard URL format is `https://www.reddit.com/[subreddit]/comments/[id]/[slug]` (i.e. has a `subreddit`).

**Comment by ZaphodBeebblebrox** [comment]
I cannot reproduce. Are you using old reddit or new reddit, and, if you are using new reddit, which view mode are you using?

**Comment by liviu-** [comment]
Can't seem to reproduce it myself either; will reopen if I manage to reproduce, thank you!
