### ISSUE TITLE
Hearst Stations

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#3745]
### URL(s) where the issue occurs

`https://www.wdsu.com/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/47218734-c76bc600-d37a-11e8-8ff7-107b207fe065.png)

### Notes

Similar to #3731, #1553

More sites owned by the same company (Hearst) with the same anti-adblock message:
`https://www.kcci.com/`
`https://www.kcra.com/`
`https://www.ketv.com/`
`https://www.4029tv.com/`

Full list:
`http://www.hearst.com/broadcasting/our-markets`

Also, live streams are broken too. Add "nowcast" after each URL. For example: `https://www.wdsu.com/nowcast`

**Comment by mapx-** [comment]
@terrorist96  could you test all these sites ? (see if still broken etc)
