### ISSUE TITLE
gelbooru.com: Still show ads when even I use adblock

### ISSUE THREAD

**Issue by maxjame5432** [uBlockOrigin/uAssets#375]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

NSFW: http://gelbooru.com/index.php?page=post&s=list

### Describe the issue

It's still showing up ads and show warning text below ads when I use ublock Origin/Adblock

### Screenshot(s)

NSFW: 
[Screenshot 20-04-2017]( https://cloud.githubusercontent.com/assets/2587798/25224211/e7d1a082-25e7-11e7-85c1-1b95fcc7a71d.png)

### Versions

- Browser/version: Chrome 57.0.2987.133
- uBlock Origin version: 1.12.1

### Settings

- none

### Notes

None

**Comment by mapx-** [comment]
add
`@@||gelbooru.com/ads.js?`

**Comment by maxjame5432** [comment]
Thanks @mapx- 
It's work

**Comment by gorhill** [comment]
Fixed with 7c0828754345c91788497f229ca66483ca8be1a0 (I used wrong issue number in commit message).
