### ISSUE TITLE
kreskowkazone.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3755]
URL(s) where the issue occurs

`http://www.kreskowkazone.pl/odcinki-online_glowa-rodziny-1999_312`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO

**Comment by okiehsch** [comment]
You have to click the "watch/Ogladaj" button, the player starts in a new tab, which Chrome blocks on my end, nothing to do with `uBlock`.
You can open the player by  right clicking "watch" and selecting "Open link in new tab"

**Comment by krystian3w** [comment]
> Ten player ma duza ilosc reklam, dlatego otwiera sie w nowym oknie.

> This player has a lot of ads, so it opens in a new window.

You can see then the ads are cut out better ...
