### ISSUE TITLE
e.olweb.tv

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#3759]
### URL(s) where the issue occurs

`https://e.olweb.tv/big_player.php?adresa=cartoon-network&server=6`

### Describe the issue

"❌"  after cuted pop-up ads.

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/43518394/47253084-023f2e00-d44f-11e8-91dc-4b0c5300b1cf.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: uBO 1.17.0

### Settings

- uBO's default settings + uBO Annoyance

### Notes

`e.olweb.tv###sutexy, #imgpop`

**Comment by ZaphodBeebblebrox** [comment]
@ryanbr
