### ISSUE TITLE
Onion services version of some blocked URLs aren't blocked

### ISSUE THREAD

**Issue by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [uBlockOrigin/uAssets#376]
Onion services version of some blocked URLs aren't blocked.

### URL(s) where the issue occurs

`https://3g2upl4pq6kufc4m.onion/` (requires the Tor Browser to access)

### Describe the issue

Onion services version of some blocked URLs aren't blocked. For example, uBO has a rule for blocking,

`duckduckgo.com/t/`

However this doesn't apply for the onion service of DuckDuckGo*, as you can test,

`https://3g2upl4pq6kufc4m.onion/`

### Versions

- Browser/version: Tor Browser 6.5.2 (based on Firefox ESR 45.9.0)
- uBlock Origin version: v1.12.1

### Settings

- No changes made to uBO's default settings.

### Notes

DuckDuckGo aren't the only ones, I can also think of Facebook's onion service (https://facebookcorewwwi.onion), I will add other URLs (with the same issue) *that I use*.

\* : [Proof that it's really DuckDuckGo's official onion service](https://duck.co/forum/thread/1762/is-the-duckduckgo-hidden-service-legitimate), also see the information on the EV SSL certificate of that onion service which specifies: `Owner: Duck Duck Go, Inc.`

**Comment by gorhill** [comment]
Are you saying that uBO should block `3g2upl4pq6kufc4m.onion/t/` because there is a filter `duckduckgo.com/t/`?

**Comment by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [comment]
Exactly.

**Comment by gorhill** [comment]
This is a completely unrealistic expectation. Declined.

A filter list maintainer will have to step up and provide specific filter list for `.onion` addresses if the demand is there. Could be you.

**Comment by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [comment]
> This is a completely unrealistic expectation.

I disagree with this sentiment, for example there are a reported hundreds of thousands monthly Tor users who reach Facebook using Tor via their onion service. Let's be conservative in our estimates and assume that only a population of 30000 (average daily Tails users, for [whom uBlock Origin is enabled by default](https://tails.boum.org/news/version_2.10/index.en.html)) have uBO installed. That's still a lot! And it can't be labeled as simply an unrealistic expectation. 

> A filter list maintainer will have to step up and provide specific filter list for `.onion` addresses if the demand is there. Could be you.

I agree to make such a list. Will post a list here when I collect all major websites with ads and their official onion addresses.

**Comment by gorhill** [comment]
The "unrealistic expectation" is the expectation of uBO magically knowing that one hostname (`3g2upl4pq6kufc4m.onion` here) is an alias for another hostname (`duckduckgo.com`).

**Comment by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [comment]
Oh sorry, I totally misread your statement, when I agreed that "uBO should block 3g2upl4pq6kufc4m.onion/t/ because there is a filter" I understood that to mean that a rule should be added to block the same resources from that onion service.

To go with your suggestion to create an onion specific block list here's a good start (should I send a PR to create a new `onion.txt` in the `filters` folder?):

```
! https://github.com/uBlockOrigin/uAssets/issues/376
||3g2upl4pq6kufc4m.onion/t/
```

(NB: This only solves the `/t/` issue)

One problem: I expect you to not enable this list by default, so while people at Tails can do that by default in their distribution (by informing them about it), what about regular users of the Tor Browser who happen to have installer the uBlock Origin add-on and aren't aware that there is a list for onion domains (that should be enabled)? Can there be a way by which uBlock automatically identifies the browser as the Tor Browser and then enables that list?

**Comment by gorhill** [comment]
> should I send a PR to create a new `onion.txt` in the filters folder?

I think this is a project which should be taken on elsewhere, it does not have to be here -- there is already enough to do here, piling on even more is not going to work. Best is for whoever sees a need for a specific filter list to step up to create the solution. Whether I include this in the stock filter lists of uBO is another matter, I currently refrain from adding even more stuff (quality and long term commitment of maintainers are factors) -- best is to submit to `filterlists.com`.

**Comment by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [comment]
Thanks for the guidance, will submit the proposal there (and when the list becomes robust enough you can then decide which is the right decision)
