### ISSUE TITLE
showing disable Adblock

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#3763]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://cll.press/F06N4x]`

### Describe the issue
After  reCAPTCHAs than completing the countdown its showing please disable the Adblock
body can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

![screenshot_2018-10-21-08-41-37-343_org mozilla firefox](https://user-images.githubusercontent.com/14991260/47262746-04050200-d4e0-11e8-8985-c931b7950e70.png)
### Versions

- Browser/version: [62]

- uBlock Origin version: [1.17.2]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
Already patched by uBO Filters.

**Comment by KiLL4FuNK** [comment]
@swathigrate update filters

![2018-10-18_19h27_30](https://user-images.githubusercontent.com/36675858/47187876-27775380-d30c-11e8-9149-81c7a318d7b0.png)
