### ISSUE TITLE
salefiles.com

### ISSUE THREAD

**Issue by andrewxyxyxy** [uBlockOrigin/uAssets#377]
### URL(s) where the issue occurs

http://salefiles.com/nddpeqjntekn/Internazionale_n1197_-_30Marzo2017.pdf.html

### Describe the issue

There is an adblock killer that block the download button

### Screenshot(s)

![sf](https://cloud.githubusercontent.com/assets/26189057/25303366/9ab756a0-2751-11e7-9a9d-366df8d9a5f0.png)

### Versions

- Browser/version: Firefox 53.0
- uBlock Origin version: 1.12.1

### Settings

- No changes

### Notes

I fixxed it adding:

`
@@||ximg.link/xxx/show_ads.js$script,domain=salefiles.com
@@||ximg.link/xxx/jquery.min.js$script,domain=salefiles.com
`

**Comment by SMed79** [comment]
Post the filters you suggested [_ here _](https://forums.lanik.us/viewtopic.php?p=117057#p117057) (Not the waitlisting filers).

**Comment by uBlock-user** [comment]
```
salefiles.com##script:inject(abort-on-property-read.js, adblock)
salefiles.com##script:inject(abort-on-property-write.js, window.admvpu)
salefiles.com##script:inject(abort-on-property-write.js, N7f)
```

**Comment by andrewxyxyxy** [comment]
This ones?

`! 24/3/2017, 12:52:00 http://salefiles.com/nddpeqjntekn/Internazionale_n1197_-_30Marzo2017.pdf.html
salefiles.com##script:inject(abort-on-property-read.js, adblock)
salefiles.com##script:inject(abort-on-property-write.js, window.admvpu)
salefiles.com##script:inject(abort-on-property-write.js, N7f`

**Comment by uBlock-user** [comment]
Add the ones I posted here
