### ISSUE TITLE
vidup.io

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3774]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://vidup.io/02w9zyqk6mdk`

### Describe the issue

popups when click play + adblock alert in player

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by smed79** [comment]
mirror sites https://forums.lanik.us/viewtopic.php?p=130319#p130319
