### ISSUE TITLE
leechpremium.link [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3777]
URL(s) where the issue occurs

`http://leechpremium.link/cbox.html`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by dumbusernameidk** [comment]
popups when clicking on the site. seems to be coming from `newjulads.com`. Best to block it.

**Comment by ghajini** [comment]
`http://srt.leechpremium.link/AFqB7j`
Antiadblock

**Comment by ghajini** [comment]
Antiadblock is present at `http://srt.leechpremium.link/AFqB7j`
But filter
`srt.leechpremium.link##+js(aopr, app_vars.force_disable_adblock)`
doesn't work.....
Filter 
`leechpremium.link##+js(aopr, app_vars.force_disable_adblock)`
2 . Antiadblock is not present at `leechpremium.link` but filter `leechpremium.link##+js(aopr, app_vars.force_disable_adblock)` still applied as per logger

Why so?

**Comment by gwarser** [comment]
@ghajini I think this was fixed in dev.

**Comment by ghajini** [comment]
@gwarser thank you...@okiehsch pls add

`srt.leechpremium.link##+js(aopr, app_vars.force_disable_adblock)`
for `http://srt.leechpremium.link/AFqB7j`
Or any other

**Comment by doio** [comment]
https://leechpremium.link/index.php
Seems the site updated adblock detection

**Comment by stephenhawk8054** [comment]
When I check the site

`https://leechpremium.link/download.php`

and add a link to the text box, for example

`https://rapidgator.net/file/79be7ea7c720a2404f0f3032d410d6ab/Tie_Mock-Up-GraphicEx.com.rar.html`

The `Generate` button not working when clicking on it. Whitelisting this filter helps the button to be clicked successfully

`@@||ajax.googleapis.com/ajax/libs/jquery/*/jquery.min.js$script,domain=leechpremium.link`

**Comment by stephenhawk8054** [comment]
The link

`https://leechpremium.link/download.php`

has anti-adblock because of this bait script now (not using `1p` since at the next domain there's this bait script too)

`@@||leechpremium.link/peel.js$script`

Putting this link:

`https://katfile.com/tp97n5r6o7xh/Foxit.Reader-11.2.1.53537.zip.html`

-> Generate, at next page (domain `go.slink.bid`) there are 3rd party domains that cause popup when clicking on download but I don't know how to fix it besides blocking those domains (might be generated randomly in the future).

**Comment by okiehsch** [comment]
````
slink.bid##+js(aopw, _pop)
slink.bid#@#+js(acis, Math, break;case $.)
slink.bid##+js(acis, JSON.parse, break;case $.)
@@||leechpremium.link/peel.js$script
````
