### ISSUE TITLE
Line Messageing API CSS/JS has been blocked

### ISSUE THREAD

**Issue by John-Lin** [uBlockOrigin/uAssets#378]
### URL(s) where the issue occurs

`https://access.line.me/dialog/oauth/weblogin?client_id=1459630796&redirect_uri=https://business.line.me/auth?redirectUri%3Dhttps://business.line.me/&response_type=code&state=lozC8J`

`https://business.line.me`

### Describe the issue

Line Messageing API CSS/JS has been blocked.

[LINE](https://line.me/en-US/) is an instant communication app and it provides messageing API which allow developers  to configure their bots settings on dashboard.  Recently, I found it has been blocked and we can't login to dashboard until disable the uBlock.

### Screenshot(s)
![screen shot 2017-04-23 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/4214069/25311685/1094117c-283a-11e7-9bb9-2a8d9a035304.png)
![screen shot 2017-04-23 at 2 57 09 pm](https://cloud.githubusercontent.com/assets/4214069/25311686/13f6de1c-283a-11e7-9fe1-817e1c52d5bf.png)
![screen shot 2017-04-23 at 3 19 12 pm](https://cloud.githubusercontent.com/assets/4214069/25311691/1ebff6ee-283a-11e7-914f-ab4e15a7bfc3.png)

### Versions

- Browser/version: Firefox 52.0.2, Safari 10.1
- uBlock Origin version: 1.12.1

### Settings

None

### Notes

I found `||line-apps.com^$third-party` in `easyprivacy.txt` could cause this issue. 

https://github.com/uBlockOrigin/uAssets/blob/514a298f52feeb829872a2dece7e093c9fe4920c/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L5928

**Comment by ghajini** [comment]
Report here for easyprivacy issues.....
`https://forums.lanik.us/viewforum.php?f=64`

**Comment by gorhill** [comment]
As said, this should be reported to EasyPrivacy -- best is to the maintainers of a list address issues with their list.

**Comment by gorhill** [comment]
FYI, @ryanbr.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d5bc310805a196668df637d4137215e8436cadd7
