### ISSUE TITLE
Consider removing "FIN: Finnish Addition to Easylist" -filterlist from uBo assets.json

### ISSUE THREAD

**Issue by msrn** [uBlockOrigin/uAssets#3780]
### URL(s) where the issue occurs

superliitto.fi, sak.fi, akt.fi, selry.fi, akava.fi, oaj.fi, stthl.fi, proliitto.fi, pam.fi, sahkoliitto.fi
### Describe the issue

There is currently happening several political strikes in Finland, where unions are taking their stance against the goverment. 
https://yle.fi/uutiset/osasto/news/security_guard_3-day_strike_to_start_on_wednesday/10469154

Few days ago the maintainer of FIN: Finnish Addition to Easylist -list, called Adblocker for Finland. Decided to block several union websites to make political statement about these strikes. 

Direct link to the list - https://adb.juvander.net/Finland_adb.txt
Archive.is -version - https://archive.is/1WYkz#selection-3137.30-3225.2

I don't really think filter lists are suitable enviroment to make political statements and the maintainer is abusing his power with actions like these. Thus please consider removing this filterlist from uBo's assets.json

### Screenshot(s)

[Screenshot of blocking the website pam.fi](https://i.imgur.com/aK37Vh9.png)
[Screenshot of the filters](https://i.imgur.com/9zHcfPB.png)
Rough ranslation: Statement about the union strikes. Will be removed after the strikes.
[Screenshot of FB post made by the maintainer](https://i.imgur.com/XCMwkm2.png)
Rough translation: As a objection to actions of trade unions.The finnish adblocking list now block sites of those unions which are joining the strike. Not all sites are there, but more are coming. They will removed after the unions start to respect the goverment again by stopping these political strikes.

### Versions

- Browser/version: Firefox 63
- uBlock Origin version: uBlock Origin v1.17.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
[Wikipedia page about the Central Organisation of Finnish Trade Unions](https://en.wikipedia.org/wiki/Central_Organisation_of_Finnish_Trade_Unions)

[Strike in the security guarding sector to go ahead – mediation ended without any settlement proposal . PAM.fi](https://www.pam.fi/en/news/notice/2018/10/strike-in-the-security-guarding-sector-to-go-ahead-mediation-ended-without-any-settlement-proposal.html)

Not sure if this is the right repo to make an issue about this list. Sorry in advance.

**Comment by mapx-** [comment]
You should report here:
https://github.com/uBlockOrigin/uBlock-issues/issues
