### ISSUE TITLE
camwhores.video / camwhores.biz / camwhorestv.co / camwhores.cc / camwhorestv.org / camwhores.io [Anti-Adblock][NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3781]
### URL(s) where the issue occurs
`http://www.camwhores.video/`
`http://www.camwhores.biz/`
`http://www.camwhorestv.co/`
`http://www.camwhores.cc/`
`http://www.camwhorestv.org/`
`http://www.camwhores.io/`

### Describe the issue
Anti-Adblock

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47449304-a19f5080-d7c2-11e8-88e5-1328c6310125.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

**Comment by mapx-** [comment]
fixed ads, popups

The anti adb message is there even disabling uBo

**Comment by dumbusernameidk** [comment]
csp filter breaks `camwhores.tv` cloudflare page. must clear cookies to test.
