### ISSUE TITLE
gamereactor.eu / gamereactor.es / gamereactor.no / gamereactor.it / gamereactor.fi [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3787]
### URL(s) where the issue occurs
`https://www.gamereactor.eu/`
`https://www.gamereactor.es/`
`https://www.gamereactor.no/`
`https://www.gamereactor.it/`
`https://www.gamereactor.fi/`

### Describe the issue
Anti-Adblock

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47450818-77e82880-d7c6-11e8-82f7-076c2e0c2cc8.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

**Comment by kulfoon** [comment]
@mapx- I've just found right now: `gamereactor.se`

**Comment by mapx-** [comment]
It should already work, test it and report back

**Comment by kulfoon** [comment]
The Anti-Adblock message is still here on `gamereactor.se`

**Comment by okiehsch** [comment]
It is fixed in the regional list.

**Comment by kulfoon** [comment]
I agree, you're right.

**Comment by kulfoon** [comment]
Found some more which aren't fixed in regional lists:
`https://www.gamereactor.nl/`
`https://www.gamereactor.pt/`
`https://www.gamereactor.asia/`
`https://www.gamereactor.de/`
