### ISSUE TITLE
im-infected.com - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#379]
Anti adb warning is displayed on https://www.im-infected.com. While this can be fixed by:
`@@||im-infected.com^$generichide` or `im-infected.com#@##adsense`

The mechanism it uses for displaying the anti adblock warning is a **WordPress** plugin **_Adblock Notify_** (https://themeisle.com/plugins/adblock-notify/) which is also used by a lot of sites. Can we disable its functionality once and for all?

https://github.com/Codeinwp/adblock-notify-by-bweb

**SS:** http://i.imgur.com/BnCvfG7.png
**Error URL:** `https://www.im-infected.com/hijacker/how-to-remove-planktab.html`

_Note: Using Chrome 58 and uBO 1.12.1 with default filters._

**Comment by mapx-** [comment]
`im-infected.com##script:inject(abort-on-property-read.js, anOptions)`

**Comment by uBlock-user** [comment]
I use 
`/wp-content/uploads/*.js`
