### ISSUE TITLE
bff.today [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3791]
### URL(s) where the issue occurs
`http://bff.today/`

### Describe the issue
Anti-Adblock

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47452091-a4517400-d7c9-11e8-8379-269214cacb2d.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

**Comment by okiehsch** [comment]
The only way to fix the message is to allow `coinhive`, I thnk that is the way the site is supposed to work.
The mining is done openly and can be stopped at any time.

**Comment by ZaphodBeebblebrox** [comment]
```
@@||coinhive.com^$domain=bff.today
@@||coinhive.com/lib/coinhive.min.js$script,first-party
@@||coinhive.com/proxy$websocket,first-party
```
gets it working on my end. Do those filters seem reasonable?

**Comment by okiehsch** [comment]
Yes, that will work.

**Comment by kulfoon** [comment]
I does work, I confirm.
