### ISSUE TITLE
xxxuno.com [Anti-Adblock][NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3794]
### URL(s) where the issue occurs
`http://xxxuno.com/`

### Describe the issue
Anti-Adblock

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47453082-10cd7280-d7cc-11e8-980a-40352d203e69.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

**Comment by mapx-** [comment]
no anti adb message for me, only fixing broken site

**Comment by kulfoon** [comment]
Even if realoading the website (F5) several times? Did you notice that every time the website is refreshed, it serve different content, to a certain point, and then from scratch, on particular refresh(content) the Anti-Adblock message pop ups, and for the other does not, so just try to reload the website X (like 10-15) times and it does pop ups for me every once in a while.

**Comment by ZaphodBeebblebrox** [comment]
I was able to reproduce on `http://desireev-livejasmin.xxxuno.com/girl-steamy/girls/2114838225`

**Comment by kulfoon** [comment]
But I was having the Anti-Adblock message on `http://xxxuno.com/` too.

**Comment by kulfoon** [comment]
I've found one more domain `http://sexanalporn.com/`

**Comment by kulfoon** [comment]
Just have found another one `http://pornoxxxporn.com/`.
