### ISSUE TITLE
limonfree.nl [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3796]
### URL(s) where the issue occurs
`http://limonfree.nl/`

### Describe the issue
Anti-Adblock [blocking] [coin mining], 
enabling Nano Defender doesn't fix the issue
enabling regional lists 2x RUS doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47480404-984ccd00-d830-11e8-8e0e-2c3610441a27.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default

**Comment by kulfoon** [comment]
I've double checked and still can reproduce.

**Comment by mapx-** [comment]
is it a blocking one ? what functionality is broken ?

**Comment by mapx-** [comment]
adding 
`@@||coinhive.com/lib/miner.min.js$script,domain=limonfree.nl` seems to fix it ?!

**Comment by kulfoon** [comment]
> Describe the issue
> Anti-Adblock [blocking] [coin mining],

I can reproduce even with Georgia IP `178.134.71.138:47621`  or USA IP `150.199.194.125:51079`)

After disabling uBO it crypto-mines:
![ss1](https://user-images.githubusercontent.com/43844449/47518037-2b662100-d88a-11e8-8639-596c903082ed.png)

just like there: https://github.com/uBlockOrigin/uAssets/issues/3791

![ss2](https://user-images.githubusercontent.com/43844449/47518187-839d2300-d88a-11e8-851a-5274e780741f.png)

Yes, your filter fix it.
