### ISSUE TITLE
televalltv.net [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3798]
### URL(s) where the issue occurs
`http://www.televalltv.net/`

### Describe the issue
Anti-Adblock [annoyance], enabling regional lists doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47481045-b9aeb880-d832-11e8-92bc-a23f4301831f.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Peter Lowe’s Ad and tracking server list

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

spa, por: Adguard Spanish/Portuguese​​​​​
​​spa: EasyList Spanish​

**Comment by mapx-** [comment]
Even disabling uBo I get that message. Did you try it ?

**Comment by kulfoon** [comment]
Missed.
