### ISSUE TITLE
globalindo.co / caraflashandroid.com + 42 more domains... [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3799]
### URL(s) where the issue occurs
`http://globalindo.co/`
`https://www.caraflashandroid.com/`

### Describe the issue
Anti-Adblock [blocking], enabling regional lists doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47481982-8faac580-d835-11e8-8b5c-e2e7a68cea0b.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Peter Lowe’s Ad and tracking server list

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

IDN: ABPindo

**Comment by mapx-** [comment]
I cannot reproduce your issue with `globalindo`

**Comment by mapx-** [comment]
for `Fanboy’s Enhanced Tracking List` report here:

https://github.com/ryanbr/fanboy-adblock/issues

**Comment by kulfoon** [comment]
I know.

**Comment by kulfoon** [comment]
Found more (enabling Nano Defender doesn't fix it) have fun:

```
US

http://allfreegame.net/
http://autolinkach.com/
http://besthondacars.com/
http://cinemakaca.tv/
http://debroo.net/
http://lewatilink.us/
http://profesorvideo.com/ NSFW
http://www.bitwarrior.xyz/
http://www.pinnpost.website/
http://www.sportnewstop.com/
http://www.thestudentloanrefinance.xyz/
https://azmeme.com/
https://printerdriversdownload.com/
https://www.apritos.com/

IDN (enabling IDN Bindu regional list doesn't fix it):

http://abi-blog.com/
http://bacalagi.online/
http://blog.eksporimpor.com/
http://contohsuratizin.com/
http://dakwahmuslim.info/
http://jadijuara.com/
http://now21.online/
http://penyakit.id/
http://resepbundakreatif.com/
http://ridvanmau.com/
http://teknohot.com/
http://unduh31.net/
http://unikheboh.com/
http://viralkeun.com/
http://www.diminimalis.com/
http://www.downloadbatch.com/
http://www.downloadtanku.com/
http://www.eventzero.org/
http://www.jamandulu.com/
http://www.pelajarz.id/
http://www.sumberpengertian.co/
https://bsierad.com/
https://kicaunews.com/
https://palapanews.com/
https://rukim.id/
https://www.apritos.com/
https://www.enkpowerranger.com/
https://www.softgaleri.com/
```

**Comment by ZaphodBeebblebrox** [comment]
`autolinkach.com` is down for me and the network that I'm on currently blocks `cinemakaca.tv` and `profesorvideo.com`
