### ISSUE TITLE
Techworld

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#38]
### URL(s) where the issue occurs

`http://www.techworld.com/`

### Describe the issue

Techworld.com prevents you from reading any article if you
have ublock enabled.

### Screenshot(s)

![techworld](https://cloud.githubusercontent.com/assets/16838044/14944210/939dda6a-0fec-11e6-9b5e-d3350da0e515.JPG)

### Versions

- Browser/version: Chrome 50
- uBlock Origin version: 1.6.8

### Settings

Blocking mode: Medium

### Notes

I can read the articles if I block
`||cdn4.techworld.com/scripts/thirdparty-pack.js?JS_20160406154718$script`
but I think a scriptlet would be preferable.

**Comment by okiehsch** [comment]
Well, at least on my end the issue is not resolved because of a script error.
I also tried with 1.7.0 and default settings with the same result.

![tech](https://cloud.githubusercontent.com/assets/16838044/14944909/e9269a92-1002-11e6-94d4-ed45245024b5.PNG)

**Comment by ryanbr** [comment]
might be applicable with cityam?

**Comment by okiehsch** [comment]
Yes, exactly the same issue with cityam

![ctyam](https://cloud.githubusercontent.com/assets/16838044/14945497/04e3f896-1013-11e6-9c4c-05ac872b0ee8.JPG)
I can access the articles on both sites by disabling "uBlock filters – Privacy‎".
Probably because of the filter
`||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices.com/gpt.js`

**Comment by gorhill** [comment]
> Well, at least on my end the issue is not resolved after I applied the fix.

Works fine here. How did you "apply" the fix?

**Comment by okiehsch** [comment]
Purged the cache of ublock filters and then forced an update.
Then I tried with a fresh install of ublock 1.7.0 with the same result.

**Comment by gorhill** [comment]
My bad, there was a typo, fixed now. (I was testing from _My filters_, bad copy/paste).

**Comment by gorhill** [comment]
I added cityam while at it -- I thought the anti-blocker scheme was specific to techworld, so I renamed the scriptlet to something more generic.
