### ISSUE TITLE
T411 / Torrent411

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#380]
Hi,

**URL(s) where the issue occurs**

`https://www.t411.ai/torrents/search/?search=test`

**Describe the issue**

fake search result + popunder / redirection

**Screenshot(s)**

https://i.imgur.com/DEI7Ihq.jpg

**Versions**

uBlock Origin 1.12.1
Chromium 58.0.3029.81

**Settings**

default settings + **Liste FR**

**Suggested filters**

```
t411.ai##.results TR:has-text(anonyme & rapide)
t411.ai##script:inject(abort-on-property-write.js, window.atob)
```

**Notes**

source: https://forums.lanik.us/viewtopic.php?p=117288#p117288

**Comment by okiehsch** [comment]
Does 
````
t411.ai##.results TR:has-text(anonyme & rapide)
t411.ai##script:inject(nowebrtc.js)
````
work on your end, or are there more popups? I would rather not disable `window.atob`.

**Comment by SMed79** [comment]
Yes work & popups.
Thank you.

**Comment by SMed79** [comment]
The domain is changed to **t411.al** (old used domains : t411.bz, t411.ai, t411.la, t411.lt, t411.lv, t411.am...)
```
t411.*##.results TR:has-text(anonyme & rapide)
t411.*##script:inject(nowebrtc.js)
```
