### ISSUE TITLE
wpgdadago.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3800]
### URL(s) where the issue occurs
`http://wpgdadago.com`

### Describe the issue
Anti-Adblock [blocking], enabling regional lists doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47482629-655a0780-d837-11e8-8d1b-86914442532c.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2
- Nano Defender 15.0.0.64

### Settings

`userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
​​uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​

Adblock Warning Removal List​
Adguard Base Filters​
EasyList​

Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​

Peter Lowe’s Ad and tracking server list

Nano Defender Integration​​
Nano filters​​
Nano filters - Whitelist​

CHN: CJX's EasyList Lite
CHN: EasyList China

**Comment by mapx-** [comment]
well, fixing the broken images => the anti adb message is gone. Can you confirm it ?

**Comment by kulfoon** [comment]
Yes, fixed.
