### ISSUE TITLE
games-pc.ro [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3804]
### URL(s) where the issue occurs
`http://games-pc.ro/`

### Describe the issue
Anti-Adblock [blocking],
enabling Nano Defender doesn't fix the issue
enabling regional lists  2 x RUS​ doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47495196-d3142c80-d853-11e8-8ced-d13a5f08f0df.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default settings.

**Comment by mapx-** [comment]
It's romanian, but even disabling uBo still getting anti adb message

**Comment by kulfoon** [comment]
Right.
