### ISSUE TITLE
delta-optimist.com / estevanmercury.ca / kamloopsthisweek.com / nsnews.com / princegeorgecitizen.com / thompsoncitizen.net / timescolonist.com / tricitynews.com / vancourier.com / weyburnreview.com / yorktonthisweek.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3816]
### URL(s) where the issue occurs
```
https://www.delta-optimist.com/
https://www.estevanmercury.ca/
https://www.kamloopsthisweek.com/
https://www.nsnews.com/
https://www.princegeorgecitizen.com/
https://www.thompsoncitizen.net/
https://www.timescolonist.com/
https://www.tricitynews.com/
https://www.vancourier.com/
https://www.weyburnreview.com/
https://www.yorktonthisweek.com/
```

### Describe the issue
Anti-Adblock [annoyance],
enabling Nano Defender doesn't fix the issue,
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47513378-69f5de80-d87e-11e8-8ce7-4c840b3ab796.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by kulfoon** [comment]
Still unfixed.

**Comment by mapx-** [comment]
test again

**Comment by kulfoon** [comment]
Fixed now.
