### ISSUE TITLE
URL Blocking still (?) doesnt work

### ISSUE THREAD

**Issue by pbl987** [uBlockOrigin/uAssets#382]
Hi!

I regularly get this ad url, opened by a mod:
https://www.youtube.com/oldskooltv_wot/?sub_confirmation=1

|youtube.com/oldskooltv_wot$important,document

=> doesnt work. What can I do?

By the way: is it possible to redirect it to another url, like in hosts file?

### Versions
- Browser/version: Chrome Beta, updated
- uBlock Origin version: updated

**Comment by gorhill** [comment]
You filter is wrong, be sure you understand fully filter syntax before opening an issue. You want double-pipe, not single-pipe:

    ||youtube.com/oldskooltv_wot$important,document

**Comment by pbl987** [comment]
This doesnt work either, as it was one of my first attempts.

And i tried the single pipe because of this thread (which you have answered):
https://github.com/gorhill/uBlock/issues/400

I have an advice for you too:
be sure you understand fully filter syntax before joining github.
pbl987 added the invalid label 1 minutes ago to gorhill.

Maybe someone else can help me please? I have severals lists activated, but $important should handle it.

**Comment by gorhill** [comment]
> This doesnt work either

Yes it does.

**Comment by pbl987** [comment]
For me it doesnt. I have been trying all day now.

I have cfosSpeed, which does DNS caching. I dont know what it could be...

OS: Win 10 Pro Slow Ring
Chrome Addons: Authy, crxMouse Chrome Gestures, Dream Afar New Tab, Free Download Manager Chrome Extension, HTTPS Everywhere, LEO Wörterbuchsuche, Session Buddy, Signal Private Messenger, Tampermonkey, uBlock, (11 deactivated)

**Comment by gorhill** [comment]
Most likely cause is you are overlooking something on your side, and possibly even misunderstanding how things work, like you did with your original filter.

**Comment by pbl987** [comment]
1. tell me whats wrong with "|"
2. pls stop insulting me, unless you have a proof for your "ideas"

**Comment by okiehsch** [comment]
> proof for your "ideas"

![proof](https://cloud.githubusercontent.com/assets/16838044/25497764/ecf951f6-2b85-11e7-91ed-43f141b6d57a.PNG)

**Comment by uBlock-user** [comment]
`|` is used when you match protocol to the domain, for instance - `|https://example.com^$script`

**Comment by pbl987** [comment]
> uBlock-user commented 6 days ago
> | is used when you match protocol to the domain, for instance - |https://example.com^$script

Thank you very much for the nice answer.
Although it was not part of the problem, i got confused with the meaning of a single pipe, while reading on github. Now everything is clear again.
