### ISSUE TITLE
mysanantonio.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#3823]
### URL(s) where the issue occurs

`https://www.mysanantonio.com/news/houston-texas/houston/article/InfoWars-host-Alex-Jones-filmed-screaming-at-pile-13329479.php#photo-16376993`

### Describe the issue

Video won't load

### Notes

`@@mm-syringe.com`

**Comment by mapx-** [comment]
Even disabling uBo I get no video (not even the seconds bellow).

Even more weird: whitelisting `mm-syringe.com`  I'm able to see the video a couple of seconds but then disappears.

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/47525194-a1f32680-d86a-11e8-85b2-77e089873207.png)

**Comment by ZaphodBeebblebrox** [comment]
I can reproduce, and `@@||mm-syringe.com^$script,domain=mysanantonio.com` fixes it for me. Maybe region dependant?

**Comment by okiehsch** [comment]
Probably, if I use a US-IP through my VPN I get a access denied message.
