### ISSUE TITLE
Gelbooru.com: select image post show advertisement (NSFW)

### ISSUE THREAD

**Issue by tralala1234567** [uBlockOrigin/uAssets#3826]
### URL(s) where the issue occurs

One of waaaaaaaaaaaay too many.
`https://gelbooru.com/index.php?page=post&s=view&id=4458206`

### Describe the issue

Images having a "loli" tag shows advertisement at the top.

### Screenshot(s)

(NSFW) `https://images2.imgbox.com/f5/74/PU2VAM5Y_o.png`

### Versions

- Browser/version: Firefox 62.0.3
- uBlock Origin version: 1.17.2

### Settings

- I have a lot of custom filters. Even some for Gelbooru that are necessary to have. Otherwise, the site is coded to break when an adblocker is detected.

### Notes

I tried adding `||http://media.r18.com/track/^` and `http://media.r18.com/track/*` in filters to get rid of it. But it doesn't work.

**Comment by okiehsch** [comment]
I can't reproduce with a default setup and the site works fine on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/47534662-7b5bdc80-d8b8-11e8-8ddf-42c5a4978297.JPG)

**Comment by tralala1234567** [comment]
I've removed my entire filters list, removed every entry in my whitelist:
+ these filters list: https://i.gyazo.com/0272653a4d769ee6e9ce03af7d9abd4d.png

And I still get that advertising.

However, if I had a simple aesthetic filtering with the built-in tool:
`gelbooru.com##[href="http://media.r18.com/track/NzcxLjEuMS4xLjAuMC4wLjAuMA/videos/vod/movies/list/id=6351/pagesize=30/price=all/sort=popular/type=studio/page=1/"]`
...it disappears and doesn't come back. However, that string (NzcxLjEuMS4xLjAuMC4wLjAuMA) seems to be some kind of token unique to my PC and might not fix the issue.

**Comment by okiehsch** [comment]
I do get served a different document it seems.

**Comment by ZaphodBeebblebrox** [comment]
Apparently. They were giving me http links for whatever reason, no idea why a site would switch away from https, but I guess it works against some cosmetic filters.

**Comment by tralala1234567** [comment]
I still get these.

Here is the code with r18 in it... I don't know if it's enough though.

```</ins></div><a href="http://media.R18.com/track/NzcxLjEuMS4xLjAuMC4wLjAuMA/videos/vod/movies/list/id=6351/pagesize=30/price=all/sort=popular/type=studio/page=1/" target="_blank"><img src="//gelbooru.com/extras/g9001002.jpg"></a><br /><br /><div style="max-width: 728px; overflow: hidden;"></div>	
		<div id="post-view">
			<div id="right-col">
				<div>
					<div id="note-container"></div>
			<img data-original-width="2184" data-original-height="2154" alt="1boy 1girl :d anus ass blush bottomless erection flat_chest hetero loli long_hair looking_through_legs nude open_mouth original penis penis_grab precum pussy_juice shiny shiny_skin smile spread_legs striped striped_legwear testicles textless thighhighs tomoki_k uncensored upper_teeth veins veiny_penis" src="https://gelbooru.com//samples/d0/7e/sample_d07ee4bdf283495200753539f5419fb2.jpg" id="image" style="width:850px;"/>
				<br /><div style="margin-bottom: 1em;">
	<p id="note-count"></p></div>
<section id="notes" style="display: none;">
</section>```

**Comment by ZaphodBeebblebrox** [comment]
Apparently href matching is case sensitive. Added two filters for the sake of redundancy.

**Comment by gwarser** [comment]
@ZaphodBeebblebrox for "R18"? Try with `i`: `gelbooru.com##a[href*="://media.r18.com/" i]`

**Comment by tralala1234567** [comment]
Hi. I've seen your filter a bit too late @gwarser . :\
So, today, I came back and, on those images, the 1-session-time cosmetic filter changed to:

`gelbooru.com##.contain-push > [href="tos.php"]`

Tomorrow, I'll let you know if you are original tweak works. However the update @ZaphodBeebblebrox pushed helped in Chrome.

If I get another ad tomorrow, despite all that, I'll give you guys another page source code.

Cheers.

**Comment by tralala1234567** [comment]
Looks like it's fixed for now!
