### ISSUE TITLE
123movies [multiple sites] [popups]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#3828]
### URL(s) where the issue occurs

`[www0.123moviesfun.org www2.123movie.cc www1.0123movies.sc]`

### Describe the issue

[Clicking on the page opens a new tab popup]

### Versions

- Browser/version: [70.0.3538.77]
- uBlock Origin version: [1.17.0]

### Settings

- [Default]

### Notes

- [When you click the orange play button on a movie/show when on the site `www0.123moviesfun.org` it'll redirect you to another site instead of taking you to the page that plays the video. I only got this to trigger once so not sure how consistent it is.]

**Comment by okiehsch** [comment]
Fixed `0123movies` and `123moviesfun`, I can't reproduce any popups at `123movie.cc`.

**Comment by okiehsch** [comment]
`123movie.*##+js(abort-on-property-read.js, zfgloadedpopup)` is already part of `uBO-filters`.

**Comment by gidgudmate** [comment]
Guess I must've missed it would probably explain why no popups appeared in the first place.

**Comment by okiehsch** [comment]
Just fyi, you can open the logger, load any site and then type `#+js` in the "filter log entries" to quickly see all already existing`script:injections` of that site.

**Comment by gidgudmate** [comment]
Good to know. By the way I am curious but how does one generally defuse these 123movies sites. I've generally just been looking for `zfgloadedpopup` but for one of the filters you put `Fingerprint2`. Where do you usually find that?

**Comment by okiehsch** [comment]
`Fingerprint2` is used to defuse [admaven](https://ad-maven.com) popups, sometimes it is used via the `inline-script`, but most of the times the sites use `cloudfront` to push it.
`123moviesfun` uses `https://djz9es32qen64.cloudfront.net/pYnFxaFNdBRgMblVCRFljUw%3D%3D`

**Comment by gidgudmate** [comment]
Hm pretty interesting might come into handy if I run into any more of these sites thanks.

**Comment by ghajini** [comment]
popup ads back
`https://www5.123movie.cc/movies/venom-hd1/`
