### ISSUE TITLE
vidzi.tv

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#383]
Hi,

**URL(s) where the issue occurs**

`http://vidzi.tv/m195oklpb1mi.html`

**Describe the issue**

popunder / redirection

**Versions**

uBlock Origin 1.12.1
Chromium 58.0.3029.81

**Settings**

default settings

**Suggested filters**

`vidzi.tv##script:inject(nowebrtc.js)`

**Notes**

source: https://forums.lanik.us/viewtopic.php?p=117524#p117524

**Comment by uBlock-user** [comment]
`nowebrtc.js` itself won't stop the popups or popunders from appearing, blocking the mentioned JS in the source at Easylist forum thread is the appropriate solution.
