### ISSUE TITLE
msofficeskills.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3830]
### URL(s) where the issue occurs
` https://msofficeskills.com/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47572234-c8809280-d93a-11e8-9a63-4b894758075f.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by kulfoon** [comment]
Found another one `https://templatebackground.com/`

**Comment by huyszn** [comment]
"Adblock Detected" message: `tinyppt.com/smartart-powerpoint-85.html`

`tinyppt.com##+js(rmnt, script, mdp)`
