### ISSUE TITLE
ideaberita.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3831]
### URL(s) where the issue occurs
`http://www.ideaberita.com/`

### Describe the issue
Anti-Adblock [blocking or annoyance?],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional lists IDN and THA doesn't fix the issue
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47572455-4c3a7f00-d93b-11e8-89bd-fc2c751284d3.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by mapx-** [comment]
IT's annoyance only if ( after closing it first time ) wont appear anymore after refreshing the page
