### ISSUE TITLE
indianringneck.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3832]
### URL(s) where the issue occurs
`http://indianringneck.com/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47573408-86a51b80-d93d-11e8-840a-ee8f1f8848c0.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by kulfoon** [comment]
Have found one more `https://bigfreegiveaway.com/`.

**Comment by okiehsch** [comment]
`bigfreegiveaway.com` is already fixed in `uBO-fiters`.
