### ISSUE TITLE
quickads.net [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3835]
### URL(s) where the issue occurs
`http://quickads.net/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47574015-f36ce580-d93e-11e8-8357-93cc0e27193d.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by smed79** [comment]
Fixing an anti-adblock on advertising network portale comes back with no interest for a classic adblock user.
