### ISSUE TITLE
streamfilmzzz.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#384]
Hi,

**URL(s) where the issue occurs**

```
http://www.streamfilmzzz.com/
http://streamzzz.online/
```

**Describe the issue**

popunder / redirection

**Versions**

uBlock Origin 1.12.1 / Chromium 58.0.3029.81

**Settings**

default settings

**Suggested filters**

`streamfilmzzz.com,streamzzz.online##script:inject(nowebrtc.js)`

**Comment by gorhill** [comment]
What do I need to do exactly to reproduce the popup/popunder?

**Comment by okiehsch** [comment]
Go to `streamfilmzzz.com` and click anywhere.
![strea](https://cloud.githubusercontent.com/assets/16838044/25567299/d2bd4bd2-2dea-11e7-9e5b-24e3e62bf7a0.PNG)
`streamfilmzzz.com,streamzzz.online##script:inject(nowebrtc.js)` 
fixes that issue, but the sites don't work correctly on my end, so I can't tell if there are any other popups.

**Comment by okiehsch** [comment]
@gorhill if you have `Prevent WebRTC from leaking local IP address` enabled, you will not be able to reproduce.

**Comment by gorhill** [comment]
Thanks, that was the "problem". My bad since the report says default settings and it's disabled by default.

**Comment by gorhill** [comment]
Does that work?

    streamfilmzzz.com##script:inject(noeval.js)

**Comment by okiehsch** [comment]
These are streaming sites, so there is potential for breakage if you use `noeval.js`, but like I said I can't play any videos on these two sites even if I whitelist them, so you or the OP would have to tell.

**Comment by okiehsch** [comment]
BTW, just in case there was a misunderstanding, when I said

> streamfilmzzz.com,streamzzz.online##script:inject(nowebrtc.js)
fixes that issue, but the sites don't work correctly on my end, so I can't tell if there are any other popups.

I didn't mean to say the sites do not work correctly **because** of the `nowebrtc.js`.
If I click on any link I get a `connection timed out error`, regardless of any filter I add.

**Comment by mapx-** [comment]
the nowebrtc seems doing nothing ..
add
```
|http://$xmlhttprequest,third-party,domain=voodaith7e.com
||voodaith7e.com/pisto.html
||voodaith7e.com/info.html$popup
||voodaith7e.com/moda1.html$popup
/?zoneid$popup
```

tested on `http://www.streamfilmzzz.com/mes-vies-de-chien/`

**Comment by mapx-** [comment]
the nowebrtc is stopping the popups / popunders on the main page

**Comment by SMed79** [comment]
@mapx- it's not about youwatch player ([#4724](https://issues.adblockplus.org/ticket/4724) example 2)

streamfilmzzz.com & streamzzz.online ==> http://i.imgur.com/BWFpcYx.gif

**Comment by okiehsch** [comment]
Well, if the issue is only the popups on the main page I will add
`streamfilmzzz.com,streamzzz.online##script:inject(nowebrtc.js)`
and the youwatch-popups can be dealt with by Easylist.

**Comment by SMed79** [comment]
> the youwatch-popups can be dealt with by Easylist.

Can do nothing... since more then 1 year youwatch, exashare & allvid, keep escaping adblockers by changing their domain at each add :-/ ([166 domains](https://bpaste.net/raw/7a6e0c0bb8e7) already used).

**Comment by uBlock-user** [comment]
For `voodaith7e.com` 

add

```
voodaith7e.com###OnPlayerClose
voodaith7e.com##.stretch-fill
voodaith7e.com##.fillme
||voodaith7e.com/pisto.html^
voodaith7e.com##script:inject(abort-on-property-write.js, jsPopunder)
```

**Comment by gorhill** [comment]
This looks promising: `navigation-to` ([reference](https://w3c.github.io/webappsec-csp/#directive-navigation-to)).

**Comment by uBlock-user** [comment]
for `ohbuegh3ev.com`

```
||ohbuegh3ev.com/bisto.html^
ohbuegh3ev.com###OnPlayerClose
ohbuegh3ev.com##.stretch-fill
ohbuegh3ev.com##.fillme
ohbuegh3ev.com##script:inject(abort-on-property-read.js, jsPopunder)
```

**Comment by uBlock-user** [comment]
for `coo5shaine.com`

```
coo5shaine.com###OnPlayerClose
coo5shaine.com##.stretch-fill
coo5shaine.com##.fillme
coo5shaine.com##script:inject(abort-on-property-read.js, jsPopunder)
coo5shaine.com##script:inject(abort-on-property-read.js, open)
```

**Comment by uBlock-user** [comment]
Has `navigation-to` been added to the Chromium yet ?
