### ISSUE TITLE
VMWare Web Interface - incorrectly blocking 'clarity-angular1.min.js'

### ISSUE THREAD

**Issue by xrobau** [uBlockOrigin/uAssets#385]
### URL(s) where the issue occurs

VMware vSphere 6.5+ web interface.  This is an application provided by VMware to manage a group of VMware hosts.

### Describe the issue
The core js file for vmware's design layout is being blocked, due to a name collision.

    08:32:23		/clarity-*.js	--	script	https://10.10.9.222/ui/resources/libs/clarity-angular1.min.js

This script is part of the vmware design guidelines. The source of it is available here: https://github.com/vmware/clarity/tree/master/src/clarity-angular

### Versions

- Browser/version: Chrome
- uBlock Origin version: Latest

### Notes

This is probably poor naming on VMware's behalf, but this makes the vmware management interface totally whitepage, as it crashes on init.

![image](https://cloud.githubusercontent.com/assets/457798/25597632/2f289484-2f13-11e7-9fc1-5c3db433a8c9.png)

**Comment by gorhill** [comment]
This is an EasyPrivacy filter, best is that you report to the maintainers of EasyPrivacy: <https://forums.lanik.us/viewforum.php?f=64>.

You can find the origin of a filter by clicking on it in the logger.

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=35937
