### ISSUE TITLE
slivap.ru / chit24.ru [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3856]
### URL(s) where the issue occurs
`https://slivap.ru/`
`http://chit24.ru/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional lists 2 x RUS doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47602073-9d994b80-d9d9-11e8-940a-5635e10b7a97.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`chit24.ru##+js(set-constant.js, adblock, false)`

**Comment by smed79** [comment]
An update is required here.

**Comment by okiehsch** [comment]
The fix in `uBO-annoyances` still works on my end.

**Comment by smed79** [comment]
> The fix in uBO-annoyances still works on my end.

Sorry...

![img](https://i.imgur.com/uxBrkpk.png)
