### ISSUE TITLE
guitaruser.ru [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3857]
### URL(s) where the issue occurs
`https://guitaruser.ru/`

### Describe the issue
Anti-Adblock [annoyance],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional lists 2 x RUS doesn't fix the issue
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47602224-1e594700-d9dc-11e8-8a82-8abde269d5bd.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`guitaruser.ru##+js(setTimeout-defuser.js, adblock)`
