### ISSUE TITLE
leakforums.co / worldaide.fr [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3858]
### URL(s) where the issue occurs
`https://leakforums.co`
`https://www.worldaide.fr/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional lists 2 x ITA doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47602298-3d0c0d80-d9dd-11e8-93a5-33067bba9b8c.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`leakforums.co,worldaide.fr##+js(set-constant.js, adblock, false)`
