### ISSUE TITLE
thevideobee.to

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#386]
Hi,

**Versions**

uBlock Origin 1.12.1 / Chromium 58.0.3029.81

**URL(s) where the issue occurs**

`https://thevideobee.to/`

**Describe the issue**

popup

**Screenshot**

http://i.imgur.com/tYt4tig.gif

**Settings**

default settings

**Suggested filters**

`thevideobee.to##script:inject(nowebrtc.js)`

**EL**

https://forums.lanik.us/viewtopic.php?f=62&t=36622

**Comment by ghajini** [comment]
`thevideobee.to/lrzpx9akulnm.html`

Video not visible

**Comment by mapx-** [comment]
add
`@@||thevideobee.to^$ghide`

however I get no real content to be played

**Comment by mapx-** [comment]
I added a filter for other popups

**Comment by ghajini** [comment]
Yeah I realised that no real video there
