### ISSUE TITLE
schnauzer-forum.co.uk / emulasyonturkiye.org [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3864]
### URL(s) where the issue occurs
`https://www.schnauzer-forum.co.uk/`
`http://emulasyonturkiye.org/`

### Describe the issue
Anti-Adblock [annoyance],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional list TUR doesn't fix the issue
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47603014-709f6580-d9e6-11e8-9654-76ef85b7907f.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by ghost** [comment]
emulasyonturkiye.org domain seems to be dead
