### ISSUE TITLE
watchtvserieslive.org

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#387]
Hi,

**Versions**

uBlock Origin 1.12.1 / Chromium 58.0.3029.81

**URL(s) where the issue occurs**

`http://watchtvserieslive.org/`

**Describe the issue**

popup

**Settings**

default settings

**Suggested filters**

`watchtvserieslive.org##script:inject(nowebrtc.js)`

**EL**

https://forums.lanik.us/viewtopic.php?f=62&t=36623

**Comment by okiehsch** [comment]
I also included circumventing the anti-adblock message preventing me from watching the video.
