### ISSUE TITLE
openspeedtest.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3871]
### URL(s) where the issue occurs
`http://openspeedtest.com/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47603635-31c1dd80-d9ef-11e8-80f9-d03854b0e157.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`openspeedtest.com##+js(setTimeout-defuser.js, google_jobrunner)`

**Comment by smed79** [comment]
No feature is limited on `openspeedtest.com` and the banner link to `chrome.google.com` (self-promo).
