### ISSUE TITLE
savevideo.me [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3874]
### URL(s) where the issue occurs
`http://savevideo.me/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47604726-e5ca6500-d9fd-11e8-85f9-3515cbf786f6.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by smed79** [comment]
The filter should go to the annoyances list.

**Comment by okiehsch** [comment]
I get 
![image](https://user-images.githubusercontent.com/16838044/48306105-31205f80-e536-11e8-9ffe-625496d732d9.png)

after every reload, so the filter is in the correct list.
