### ISSUE TITLE
lindung.in [Anti-Adblock] 

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3878]
### URL(s) where the issue occurs
`http://lindung.in/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47604907-ed8b0900-d9ff-11e8-9d5e-4a5cc9cd07f5.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`lindung.in##+js(setTimeout-defuser.js, adblockvisitor)`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://lindung.me/heart-health-and-clean-arteries/`
