### ISSUE TITLE
lumsearch.com [Anti-Adblock] 

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3879]
### URL(s) where the issue occurs
`https://lumsearch.com/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47604921-2925d300-da00-11e8-92f7-597ddae7a952.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`lumsearch.com##.adsblocked`
