### ISSUE TITLE
droidtekno.com / hentaimx.com / addtobucketlist.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3880]
### URL(s) where the issue occurs
`http://www.droidtekno.com/`
`http://hentaimx.com/`
`http://www.addtobucketlist.com/`

### Describe the issue
Anti-Adblock [blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional lists IDN + 2 x SPA  doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47604964-c1bc5300-da00-11e8-8521-9f3c5620f6fc.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`droidtekno.com,hentaimx.com##+js(setTimeout-defuser.js, google_jobrunner)`

**Comment by snyderp** [comment]
Also on http://www.techsolutiontips.com

**Comment by okiehsch** [comment]
`techsolutiontips.com` is already fixed.
https://github.com/uBlockOrigin/uAssets/commit/b6d4ac06694458af00a160b2ee3a00035f2293d6

**Comment by snyderp** [comment]
Oh hell yea, amazing!  Thanks!
