### ISSUE TITLE
luccisan.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3881]
### URL(s) where the issue occurs
`http://www.luccisan.com/`

### Describe the issue
Anti-Adblock ["annoyance" + blocking],
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### 1
![ss2](https://user-images.githubusercontent.com/43844449/47605142-d699e600-da02-11e8-9f58-a6cd7ab02c42.png)

### 2 after scrolling to the bottom
![ss1](https://user-images.githubusercontent.com/43844449/47605141-d699e600-da02-11e8-9002-1d4babc9278f.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
```
luccisan.com##.warning
||rawgit.com/*/adblocker-detected.js^
```
