### ISSUE TITLE
Fingerprinting done through in-page JavaScript on anilinkz.io

### ISSUE THREAD

**Issue by Okamoi** [uBlockOrigin/uAssets#389]
Hi,

### URL(s) where the issue occurs

`http://anilinkz.io/death-note-episode-36`

### Describe the issue

When you first load this page, your first click anywhere on the page will trigger a connection to a tracking website. The connection is not completely blocked even with almost all filter lists enabled, and the domain and URL change regularly. Here's custom rules I set for 3 of those:
```
||oscarlosun.com^
||planniver.com^
||roughted.com^
```

But instead of blocking a new obscure domain not present in any filter list every week it would be safer to block the JavaScript that triggers this connection instead.

And that's where the problem lies: It's not just a connection triggered on click, there's a whole fingerprinting script in there that should never be allowed to run, regardless of if the results are sent to some obscure domain or anilinkz.io themselves.

So, can uBlock's more advanced features take care of this ? What do such rules look like ?

### Screenshot(s)

No screenshot needed, just mentioning that the script is inlined and enclosed with a `(function (){})` thing, and heavily obfuscated in some parts.

### Versions

- Browser/version: Firefox 53
- uBlock Origin version: 1.12.1

### Settings

- I enabled advanced mode, added custom filter `anilinkz.io###waifu`, and have these rules
```
* * 1p-script noop
* * 3p block
* * 3p-frame noop
* * 3p-script noop
* * inline-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
```

I handle first party scripts with NoScript, same for 3rd party scripts and frames. In that case, I only allow scripts from domain anilinkz.io. I have other resources noop-ed on a case-by-case basis, but nothing that applies to anilinkz.io.

### Notes

`(function(){function m(b) //...` is the culprit. I have no idea how to block its execution since it is inlined and enclosed, otherwise I would have created a NoScript surrogate.

Thanks if you can help!

**Comment by gorhill** [comment]
This will abort the execution of the fingerprint code:

    anilinkz.io##script:inject(abort-on-property-write.js, Fingerprint2)

For the popups, just toggle on the no-popup switch. This would need more investigation to figure whether the cod for these popups can be defused.

Why would you have NoScript handle the 3rd-party scripts/frames? You are forfeiting uBO's ability to block/allow on a per-site basis, i.e. if a script/frame from one undesirable is absolutely needed on a given site, you can do this with uBO, rather than allow everywhere with NoScript (I know about ABE,  point-and-clicking is much more user-friendly).

**Comment by gorhill** [comment]
Note: with the scriptlet suggested above, there is no more connection attempt to `d2nz8k4xyoudsx.cloudfront.net` -- so it seems this is where the fingerprint was sent (seemingly encoded in the URL).

**Comment by uBlock-user** [comment]
for popups,

```
anilinkz.*##script:inject(abort-on-property-read.js, open)
anilinkz.*##script:inject(noeval.js)
```

**Comment by Okamoi** [comment]
Thank you both, that works perfectly. I don't have pop-ups with Gorhill's rule, and without it only on first click if it's a middle click. The pop up is blocked with an annoying Firefox message below the address bar. Probably related to Fingerprint2.

I guess my NoScript configuration makes uBlock-user's rules unnecessary or something.


> Why would you have NoScript handle the 3rd-party scripts/frames? You are forfeiting uBO's ability to block/allow on a per-site basis, i.e. if a script/frame from one undesirable hostname is absolutely needed on a given site, you can do this with uBO, rather than allow everywhere with NoScript (I know about ABE, point-and-clicking is much more user-friendly).

I let NoScript handle it because it has a lot of protections that are beyond the scope of uBlock. It's true that NoScript is missing a per-site permissions whitelist but I only use temporary allows to make up for it. Hoping NoScript 10 will get per-site though, and a UI more like uMatrix or something. I use uMatrix instead of NoScript on a less secure profile.


Next time I need to use an advanced rule like this script injection thingy, do you think I can bother directly EasyPrivacy's maintainer ? Are they familiar with the syntax and willing to use uBlock-only rules ?

**Comment by uBlock-user** [comment]
No, they're not. They will direct you here, so don't bother them. Lastly, NoScript is not known to play well if you run it with uBO. It's best that either you remove it or keep it disabled if it does something unexpected, also uBO offers nothing less than NoScript, infact you don't need the extension if you're already using uBO.

**Comment by Okamoi** [comment]
Ah, I see it's in uBlock-only filters for everyone now. Got it, this place is uBlock's feature-specific equivalent of the forum where you request new EasyList filters.

Thanks again :)

As for NoScript, I never noticed any issue with uBO. Both add-ons work as I would expect them according to Firefox console logs, uBO's logs and firewall logs. I'm not ready to remove NoScript considering that the features of both extensions don't overlap completely.

**Comment by RoxKilly** [comment]
This issue was just mentioned today on [BleepingComputer.com](https://www.bleepingcomputer.com/news/security/malvertising-campaign-finds-a-way-around-ad-blockers/) in a story about a large malvertising campaign -- called RoughTed -- that can circumvent ad-blockers

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b123b601ec280642ce7cbeb2ae50d1c802053a72

**Comment by SMed79** [comment]
`roughted.com` Is blocked in Liste FR [3 weeks ago](https://hg.adblockplus.org/listefr/rev/fcc6f85729ed).

Here other domains from the same ad network (mal advertiser)
```
||bowlingle.com^
||charmstroy.info^
||paradition.com^
||quierest.com^
||oscarlosun.com^
||signoredom.com^
||triction.info^
```
