### ISSUE TITLE
torrentfunk.com popup ads

### ISSUE THREAD

**Issue by sfilie03** [uBlockOrigin/uAssets#3895]
torrentfunk.com

Hi. On torrentfunk.com, when you load it for the first time after clearing all the cookies, and click in the search bar in the top left to search for something, a new tab opens automatically and briefly shows that it's trying to connect to an ip address, then the tab changes to an ad page (sometimes it just opens a new blank tab). How do you fix that? What settings should I used to block all ad content on that site, while still allowing it to work normally? Thanks.

![torrentfunk 001](https://user-images.githubusercontent.com/35790889/47607830-2a9cce80-d9f3-11e8-8af4-5af3110f0bfd.jpg)

![torrentfunk 002](https://user-images.githubusercontent.com/35790889/47607832-338da000-d9f3-11e8-90dc-9b9f73bb526a.jpg)

![torrentfunk 003](https://user-images.githubusercontent.com/35790889/47607834-38eaea80-d9f3-11e8-81c2-d28eca842a26.jpg)

Firefox 63.0 (64-bit)
uBlock Origin 1.17.2

**Comment by IoanPaleru** [comment]
Yeah, now it works. Thanks.
