### ISSUE TITLE
Stop YouPorn's EasyList trickery

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#39]
### URL(s) where the issue occurs

NSFW: `http://www.youporn.com/`
([Currently fixed](https://hg.adblockplus.org/easylist/rev/f5b7bbfd01e7).)

### Describe the issue

It seems like YouPorn and the like aren't running out of exception filters to abuse from EasyList. Maybe add a solution for uBO.

### Notes

Maybe something similar to this: https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/blob/master/uBlock-Filters-Plus.txt#L217
Example:
`/iframe-*.html#zone_id=$domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com,third-party,subdocument,important`

Got the list of domains from the PHN filters in EasyList. Can't say if it's all or if some aren't even involved. PornHub for example (while being referenced in the EasyList changelog) isn't currently using any tricks while YouPorn's trickery is still up (although fixed in EasyList).

**Comment by IDKwhattoputhere** [comment]
https://github.com/uBlockOrigin/uAssets/commit/675cb53774b781261ec23412ddd09e1d5a951686 should fix this if I'm not mistaken.

**Comment by gorhill** [comment]
I hadn't seen this issue. Is `redtube.com` still broken?

**Comment by IDKwhattoputhere** [comment]
Thank you.

**Comment by IDKwhattoputhere** [comment]
`redtube.it` is missing btw.

**Comment by IDKwhattoputhere** [comment]
On [NSFW] `tube8.fr` you can see that they now use XMLHttpRequests. Maybe you want to add `xmlhttprequest` to block those.

**Comment by gorhill** [comment]
There is an exception filter EasyList causing XHR to passthrough: `@@||comeadvertisewithus.com*/ads.js|`.

Do you know why it was added?

Does `||comeadvertisewithus.com.abbp1.pw/ads.js$xmlhttprequest,domain=tube8.fr` fix the issue without whatever issue the above exception filter tried to solve?

**Comment by IDKwhattoputhere** [comment]
I'm not sure why it was added but I remember seeing it on quite a few sites (Yavli and some popunders on NSFW sites if I remember correctly). The issue is simply the abuse of whitelist entries yet again (see https://forums.lanik.us/viewtopic.php?p=106782#p106782 where other entries seem to have been the problem).

**Comment by IDKwhattoputhere** [comment]
Same thing on `redtube.com.br`, `tube8.com` and `xtube.com`.
Sometimes one gets through the hiding filters at the bottom of a video page on `pornhub.com`. Same thing but multiple ones and more often on `youporn.com`.

**Comment by SMed79** [comment]
> There is an exception filter EasyList causing XHRs to passthrough
> Do you know why it was added?

added to block Yavli ads [0eb19b3662db](https://hg.adblockplus.org/easylist/rev/0eb19b3662db) / [viewtopic.php?p=103409#p103409](https://forums.lanik.us/viewtopic.php?p=103409#p103409)

Working filter https://forums.lanik.us/viewtopic.php?p=107216#p107216

**Comment by IDKwhattoputhere** [comment]
Wouldn't `@@||comeadvertisewithus.com^*/ads.js|` have been sufficient? Anyways, the commit works, thanks.

**Comment by gorhill** [comment]
> Wouldn't `@@||comeadvertisewithus.com^*/ads.js|` have been sufficient?

I am at a lost to understand the purpose of the `*` in `@@||comeadvertisewithus.com*/ads.js|`.

**Comment by IDKwhattoputhere** [comment]
They changed it to `comeadvertisewithus.com.abbp1.science/ads.js`.

**Comment by IDKwhattoputhere** [comment]
The switched to `traffichaus.com.abbp1.science/ads.js`, abusing yet another way too broad exception filter in EasyList.

**Comment by SMed79** [comment]
@gorhill see https://forums.lanik.us/viewtopic.php?p=108375#p108375 (jpost.com)

**Comment by IDKwhattoputhere** [comment]
`tube8.es` and `youporngay.com` can be added to the rule too.

**Comment by IDKwhattoputhere** [comment]
`@@?stream=/embed/*&width=*&height=$script` in EasyList being abused.
`||fotzenparty.eu^$important,third-party`

**Comment by SMed79** [comment]
`@@||192.168.*/images/adv_$~third-party`
https://forums.lanik.us/viewtopic.php?p=109578#p109578

**Comment by SMed79** [comment]
`@@||picplzthumbs.com/upload/img/ad/`
https://forums.lanik.us/viewtopic.php?p=109945#p109945

**Comment by gorhill** [comment]
I don't see ads, and there is no `picplzthumbs.com` in the logger.

**Comment by IDKwhattoputhere** [comment]
I'm getting a popunder when clicking on a thumbnail on `http://www.pornhub.com/`. I can open a new issue if necessary. This filter works:
`/fp.eng?id=$popunder`

**Comment by gorhill** [comment]
Does that work?

    pornhub.com##script:inject(abort-on-property-write.js, rAb)
