### ISSUE TITLE
mail.aol.com modal popup

### ISSUE THREAD

**Issue by mattncsu** [uBlockOrigin/uAssets#390]
### URL(s) where the issue occurs

`https://mail.aol.com/webmail-std/en-us/suite` (behind a login)

### Describe the issue

Modal popup hawking various services like spyware scanning, registry cleaning, etc.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Firefox ESR 45.8.9
- uBlock Origin version: 1.12.1

### Settings

Adding this to My Rules `mail.aol.com https://api.gxp.aol.com/v3/AOL_V1/GetOffers script block` or `AOL_V1/GetOffers` to My Filters blocks the popup.

### Notes
Modal pop up displays intermittently.. perhaps once per day per pc and only right after login.

Initially, I tried blocking the modal container with
`mail.aol.com###dijit__WidgetsInTemplateMixin_1bg
mail.aol.com###dijit__WidgetsInTemplateMixin_1`
but I found that other useful dialogs (e.g. "Do you want to delete these messages?") use the same modal.  Watching the log I found `https://api.gxp.aol.com/v3/[b]AOL_V1/GetOffers[/b]?ChannelId=Webmail&RequestData=%7B%22pageContext%22%3A%22webmail_lb.jsp%22%2C%22requestFirstOffer%22%3Afalse%7D&access_token=<REMOVED>c&_content=true&_callback=dojo_request_script_callbacks.dojo_request_script1`

Blocking GetOffers has provided a few weeks of pop-up free use without any obvious things broken.

**Comment by gorhill** [comment]
If I can reproduce, I will not create a filter for this. Also, EasyList policies apply, i.e. if it's self-promotion, it won't go into uBlock filters.
