### ISSUE TITLE
basilmarket.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3906]
### URL(s) where the issue occurs
`http://www.basilmarket.com/`

### Describe the issue
Anti-Adblock [annoyance],
enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47613499-bc0e4e00-da90-11e8-9eef-78a1c2b79a10.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by mapx-** [comment]
or (if will be blocking one)
```
@@||cdm.cursecdn.com/js/$script,domain=basilmarket.com
@@||googletagservices.com/tag/js/gpt.js$script,domain=basilmarket.com
@@||securepubads.g.doubleclick.net^$script,domain=basilmarket.com
```
