### ISSUE TITLE
Disabling onmousedown on Google search results

### ISSUE THREAD

**Issue by kcolbu** [uBlockOrigin/uAssets#391]
### URL(s) where the issue occurs

https://www.google.com/search?hl=en&q=flowers&gws_rd=cr

### Describe the issue

Google modifies the links of search results to add their own tracking strings through an `onmousedown` event, which makes it a burden if you attempt to copy links and image URLs with the context menu. It's also a privacy issue for people who don't want Google to know what specific results they've clicked on.

Is there a uBlock Origin scriptlet/filter that disables the `onmousedown` event? If not, I'm requesting its creation, so we don't need to install another extension just for a single site.

### Versions

- Browser/version: Firefox 53
- uBlock Origin version: 1.12.1

**Comment by gorhill** [comment]
Just disable inline script for Google Search pages:

    ||www.google.com/search$inline-script

**Comment by Hrxn** [comment]
Not sure, but in this case there are maybe unwanted side effects..

**Comment by kcolbu** [comment]
@gorhill The image search stops working if you disable inline scripts. And if you whitelist image searches, the direct links to images will still be modified.

**Comment by gorhill** [comment]
> so we don't need to install another extension just for a single site

This should never ever be used as an argument, reducing one's number of extensions is **not** uBO's purpose.

If you care about privacy, use the Tor browser and another search engine, this won't be a placebo solution -- whatever you are asking here will be a placebo solution, there is no way to guarantee that just blocking `mousedown` events will completely take care of Google knowing which result you clicked in the small set of results presented to you.

Also, the logger shows that some network requests are cancelled by this EasyPrivacy filter `||google.*/gen_204?$other` when we click a result.

**Comment by kcolbu** [comment]
I just mentioned these things as extra incentives. Your extension can already achieve what I want, but I don't know JavaScript to make the scriplet by myself, so I posted here to see if someone would help me. 

The main purpose of this issue is that I copy links (especially image links) from the results all the time, and by default Google prevents me to do that.

**Comment by uBlock-user** [comment]
try - `google.*##script:inject(abort-on-property-read.js, onmousedown)`

**Comment by kcolbu** [comment]
@uBlock-user That doesn't work. The event is fired by the onmousedown attribute in the link (a) tags.

**Comment by uBlock-user** [comment]
@kcolbu It should, it's a `window` property. Try - `google.*##script:inject(abort-on-property-write.js, onmousedown)`

**Comment by gorhill** [comment]
@uBlock-user no, it's a property on most HTML Element instances, declared as an attribute in the current case. Again, this is out of scope of uBO.

**Comment by uBlock-user** [comment]
If so, then how come if I run `JSON.stringify(Object.keys(window));` in the console, it's listed there along with others ?

**Comment by alcoolfire** [comment]
I do appreciate this is a rather old closed issue, but it lacks a satisfactory answer for those of us who have it come up in our search for a solution. My apologies to @gorhill if this is considered inappropriate, but for the next frustrated person searching here is my working filter as of today:

    google.*##+js(remove-attr.js, onmousedown, div#search div.g a[onmousedown^="return rwt(this"])

For reasons I'm currently running an unofficial build of Pale Moon 28.10 with uBlock Origin for Firefox legacy-based browsers 1.16.4.30

**Comment by uBlock-user** [comment]
`www.google.*##+js(set, rwt, noopFunc)` is already present in uBlock Annoyances list.

**Comment by alcoolfire** [comment]
@uBlock-user: The filter in uBlock Annoyances list does not fix the problem for me. The documentation for set.js (https://github.com/gorhill/uBlock/wiki/Resources-Library) references v1.25.0 a few times, so maybe the fact that I'm currently stuck with v1.16.4.30 is the explanation?

**Comment by uBlock-user** [comment]
`www.google.*##+js(set-constant.js, rwt, noopFunc)` for legacy ?

**Comment by alcoolfire** [comment]
@uBlock-user: No, that does not work, but dropping the "www." prefix like this actually does:

    google.*##+js(set-constant.js, rwt, noopFunc)
