### ISSUE TITLE
arduino-board.com detects adblocking

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#392]
### URL(s) where the issue occurs

https://www.arduino-board.com/boards/dfrduino-uno-r3

### Describe the issue

You are redirected to a page with an anti-adblocking message (https://www.arduino-board.com/page/sign-up). Trying to visit it again re-presents it but with "Last chance", and trying to visit it a third time redirects you off of the site entirely.

### Versions

- Browser/version: Firefox 53
- uBlock Origin version: 1.12.1

### Settings

- 100% default

### Notes

All pages on the site contain an inline script that, among other things, does `var abc="true";`. In addition, the script at https://adserver.dca13.com/js/ads2.js is loaded, which just contains `abc='false';`. Later, in site.js (which contains a lot of JavaScript necessary for the site to function properly), there's the following: `$(document).ready(function(){if(abc=='true'){window.location="/page/sign-up";}`. At least for now, adding the rule `@@//adserver.dca13.com/js/ads2.js` works around this, but I'm not sure how long that will work or if it's the best way to proceed.

**Comment by okiehsch** [comment]
Thx for investigating, update your `uBlock-filters` list.
`arduino-board.com##script:inject(abort-on-property-read.js, abc)`
fixes the issue.

**Comment by okiehsch** [comment]
`arduino-board.com##script:inject(abort-on-property-read.js, abc)` breaks the search function on my end.
So actually `arduino-board.com##script:inject(abort-on-property-write-.js,abc)` is the better fix.
