### ISSUE TITLE
ohorse.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3927]
### URL(s) where the issue occurs
`http://ohorse.com/`

### Describe the issue
Anti-Adblock [blocking],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47616116-98f79480-dab8-11e8-950c-b6d09d12e1fe.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by kulfoon** [comment]
@mapx- @ZaphodBeebblebrox @okiehsch 

I still do have it.

**Comment by ZaphodBeebblebrox** [comment]
Just FYI, you don't need to tag us, we see every comment and issue posted in the repository already.

**Comment by kulfoon** [comment]
OK, I know, but it happened one (or two) times that it looked like one of you missed my comment, so I had to tag him (as far I remember it was @mapx- ), so that's why I started to tag, but I understand what you mean, so I'll tag only if I see not responding in 24h.

**Comment by kulfoon** [comment]
Lol sorry mapx-

**Comment by ZaphodBeebblebrox** [comment]
Its fine either way, you can tag if you want, I just did not know if you knew that it was not necessary.
