### ISSUE TITLE
ibtimes.co.uk - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#393]
Anti adb warning is displayed on http://www.ibtimes.co.uk. This can be fixed by:
`@@||ibtimes.co.uk/*adframe.js$script`

*The anti adb is hidden for uBO users as the filter `ibtimes.co.uk###signin_popup` hides it. So users only see a non scrollable page.

**SS:** 
http://i.imgur.com/YKhW6sV.png (As seen b uBO users)
http://i.imgur.com/ScIipB4.png (As it appears for other adblock users)

**Error URL:** 
http://www.ibtimes.co.uk/ever-heard-alcoholic-rats-indian-police-claim-rodents-gulp-down-1-million-litres-liquor-1620118

**Edit:** They seem to be detecting adblock through this js `https://g.ibtimes.co.uk/sys/js/0f272c6adfa6e3dd473e369d034a66e6.js` but blocking it does not help (I don't think it should be blocked though). Any way to null the adblock detection on this site?

**Comment by gotitbro** [comment]
@okiehsch @gorhill Multiple requests are created for an adblock detection URL constantly if its blocked, the issue is resolved if the detection URL is whitelisted.

**SS:** https://i.imgur.com/z89DoYZ.png
**Error URL:** 
http://www.ibtimes.co.uk/facebook-wants-secretly-watch-you-through-your-smartphone-camera-1625061

This can be fixed by whitelisting the URL being checked:
`@@||gc.ibtimes.co.uk/www/js/jan2016/adframe.js$script`

**Comment by okiehsch** [comment]
I will add
`||ibtimes.co.uk/*/adframe.js$script,first-party,redirect=noopjs`, works on my end.
