### ISSUE TITLE
passionedesign.it [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3939]
### URL(s) where the issue occurs
`http://www.passionedesign.it/`

### Describe the issue
Anti-Adblock [blocking + annoyance],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional lists 2 x ITA
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

1
![ss1](https://user-images.githubusercontent.com/43844449/47617348-a0259f00-dac6-11e8-85be-2a8c6ece19f8.png)

2
![ss2](https://user-images.githubusercontent.com/43844449/47617359-b3d10580-dac6-11e8-8520-1bc6c4b62866.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by ZaphodBeebblebrox** [comment]
For me, uBO's redirection of fuckadblock.js works just fine.

**Comment by mapx-** [comment]
I cannot reproduce it either

**Comment by kulfoon** [comment]
Weird, I can't reproduce it anymore, but instead I've noticed some Anti-Adblock remains at the bottom:

![ss1](https://user-images.githubusercontent.com/43844449/47618446-6e670500-dad3-11e8-8f90-8ecccede2ddf.png)
