### ISSUE TITLE
Iframes from content-ad.net

### ISSUE THREAD

**Issue by hant05080** [uBlockOrigin/uAssets#394]
### URL(s) where the issue occurs

`biology-online.org`
`101greatgoals.com`
`eurweb.com`

### Describe the issue

Ad iframes on these websites aren't blocked by uBO. The only way to get rid of them I found is disabling inline-scripts. 

### Screenshots
![2017-05-07 00-41-34](https://cloud.githubusercontent.com/assets/28459131/25776131/8ff29b76-32be-11e7-86cb-8872cedc198e.png)
![2017-05-07 00-40-45](https://cloud.githubusercontent.com/assets/28459131/25776132/91a234f4-32be-11e7-90d9-08daf32cd15b.png)

### Versions

- Browser/version: Mozilla Firefox 53.0 on Debian GNU/Linux
- uBlock Origin version: 1.12.3b2

**Comment by hant05080** [comment]
Some more sites with this stuff:
`allthetests.com`
`jerusalemonline.com`

**Comment by gorhill** [comment]
I couldn't see the ads on `jerusalemonline.com`, but I could see `upManager` being used in the source, so I added it anyways, you will have to confirm that the filter works.

**Comment by SMed79** [comment]
@hant05080 Check also:
```
jpost.com
mako.co.il
x17online.com
rbc.ru
examinationresults.ind.in
freewarefiles.com
fullmatchesandshows.com
hobbyconsolas.com
letras.com
letras.mus.br
lucianne.com
maariv.co.il
phonesreview.co.uk
rbk.ru
status-quote.com
videograbby.com
ynet.co.il
```

**Comment by hant05080** [comment]
@gorhill, yes, it works.

@SMed79
`jpost.com` - clear
`mako.co.il` - there're some banners that can be easily hidden with `mako.co.il##.ad`
**`x17online.com`** - "sponsored" iframes
`rbc.ru`, `rbk.ru` - clear (at least with RU AdList and Adguard Filters)
`examinationresults.ind.in` - clear
`freewarefiles.com` - clear
`fullmatchesandshows.com` - it seems that CSS on this site is broken or some of my filters breaks it
`hobbyconsolas.com` - clear
`letras.com` - clear
`letras.mus.br` - clear
`lucianne.com` - clear
`maariv.co.il` - clear
**`phonesreview.co.uk`** - "sponsored" iframes
`status-quote.com` - clear
`videograbby.com` - can't open the site
`ynet.co.il` - clear

**Comment by gorhill** [comment]
I don't have time to investigate all, but I added filters for `fullmatchesandshows.com` and `x17online.com`, for which I could see ads.

**Comment by gorhill** [comment]
I don't see ads on `phonesreview.co.uk`, however I do see webrtc connections. Does this work?

    phonesreview.co.uk##script:inject(csp.js, script-src 'self' * 'unsafe-inline')

Incidentally, foiling webrtc connections does not work with `phonesreview.co.uk##script:inject(noeval.js)`, but it works if `eval` is foiled using a CSP directive.

**Comment by hant05080** [comment]
It seems like this filter `phonesreview.co.uk##script:inject(csp.js, script-src 'self' * 'unsafe-inline')` works, but I don't sure, because banners on that site appears not on every page. Should I see something in the logger?

**Comment by hant05080** [comment]
One more website: `videotoolbox.com`

**Comment by gorhill** [comment]
This is a case demonstrating why the new `csp=` filter option is needed:

    ||videotoolbox.com^$csp=script-src 'self' * 'unsafe-inline'

Maybe there is another approach, but this one works with dev build of uBO.

**Comment by hant05080** [comment]
Doesn't work for me (uBO 1.12.5b17, Firefox 53.0.3).

**Comment by gorhill** [comment]
Works for me. You will have to investigate on your side.

**Comment by hant05080** [comment]
Ok, clearing cache and restarting browser solved the problem.
