### ISSUE TITLE
Incorrect fix for `live.com`

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3948]
### URL(s) where the issue occurs

`https://outlook.live.com/mail/inbox`

### Describe the issue

The current fix in the annoyance filter is not correct, it leaves a big empty space on the side: 
```
! https://github.com/jspenguin2017/uBlockProtector/issues/975
@@||s.aolcdn.com/ads/adswrappermsni.js$script,domain=outlook.live.com
@@||acdn.adnxs.com/$script,domain=outlook.live.com
```

The correct fix is: 
```
live.com##div:if(:scope > div > div[class^="__Microsoft_Owa_Adsbar_"])
live.com##div:if(:scope > div > div > div[id^="owaadbar"]:not([class^="__Microsoft_Owa_Adsbar_"]))
```

### Screenshots

![image](https://user-images.githubusercontent.com/7283682/47620034-fd135c00-daaa-11e8-9b33-673d8b33843a.png)
![image](https://user-images.githubusercontent.com/7283682/47620037-04d30080-daab-11e8-977d-435491e6c236.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.17.0

### Settings

Default + annoyance.

**Comment by ZaphodBeebblebrox** [comment]
Your cosmetic filters do not work for me. Does `outlook.live.com##:xpath(//a[contains(@href, "ad-free-outlook")]//..//..//..//..)` work for you?

**Comment by jspenguin2017** [comment]
@ZaphodBeebblebrox Nope, doesn't work. Are you on outlook beta?

**Comment by ZaphodBeebblebrox** [comment]
Yes I am. For whatever reason, there are no elements on the page I am served whose class contains `Adsbar`

**Comment by jspenguin2017** [comment]
The beta has `owaadbar` though.

**Comment by jspenguin2017** [comment]
The `:not` is needed, otherwise it breaks the old outlook.

**Comment by ZaphodBeebblebrox** [comment]
Same for divs whose class contains owa, `document.querySelectorAll('[class*=owa]')` give me no results.

**Comment by jspenguin2017** [comment]
That's an ID: 
![image](https://user-images.githubusercontent.com/7283682/47620374-09011d00-daaf-11e8-82fd-26222a8e8ea3.png)

**Comment by ZaphodBeebblebrox** [comment]
Same for the id for me. Apparently I am doing something stupid, I shall defer to okiehsch and mpax-

**Comment by okiehsch** [comment]
I don't use outlook, so you shall not :wink:

**Comment by okiehsch** [comment]
Does either of your filters break anything? If not why not just add both.

**Comment by ZaphodBeebblebrox** [comment]
Here's an account
```
User: owaadbar@outlook.com
Pass: uAssetsTestAccount
```

**Comment by jspenguin2017** [comment]
Well, the whitelist doesn't break anything, it just doesn't fix the problem.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/47620626-65366200-daec-11e8-81c6-8827b1103f76.png)

**Comment by ZaphodBeebblebrox** [comment]
Well, I'm the only one who is having problems, so jspenguis filters work.

**Comment by okiehsch** [comment]
> Well, the whitelist doesn't break anything, it just doesn't fix the problem.

I meant also adding the xpath filter.

**Comment by jspenguin2017** [comment]
@ZaphodBeebblebrox Which browser are you using?

**Comment by ZaphodBeebblebrox** [comment]
I was testing in chrome, specifically `70.0.3538.77 (Official Build) (64-bit)`

**Comment by jspenguin2017** [comment]
Let's call this good for now, and watch for further reports.
