### ISSUE TITLE
Procedural cosmetic filtering issue?

### ISSUE THREAD

**Issue by bananakid** [uBlockOrigin/uAssets#395]
I'm trying to theme chart UI of [BTC-E](https://btc-e.nz) using uBlock Origin 1.12.1 & Google Chrome 57.0. Chart candles are being created via JS, they appear as rect objects with fill value. I assume I should be able to use :has & :style to achieve my goal and change color of green & red candles accordingly. Regular cosmetic styling works for all rect objects:
`btc-e.nz##rect:style(fill: none !important)`
However none of the following code examples work:
```
!btc-e.nz##*:has(fill="#515151"):style(fill: black !important)
btc-e.nz##g:has(rect[fill="#515151"]):style(fill: black !important)
btc-e.nz##rect:has(fill="#515151"):style(fill: black !important)
btc-e.nz##rect[fill][style*=#515151]:style(fill: black !important)
```
I'm trying to implement this following [official wiki article](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters).

Thanks for your wonderful extension.

**Comment by gorhill** [comment]
`:style` cannot be used with procedural cosmetic filters, it has to be a plain declarative CSS selector.

**Comment by bananakid** [comment]
Thanks for the explanation, gorhill! Hope to see this powerful feature someday. In the meanwhile please note this limitation in the article.
![btc-e](https://cloud.githubusercontent.com/assets/17095595/25796457/03d79f02-33f3-11e7-9348-aea3b32c8eef.png)
![btc-e_ublock](https://cloud.githubusercontent.com/assets/17095595/25796474/0bd8997c-33f3-11e7-9bfb-501d427bc9be.png)
