### ISSUE TITLE
it-explain.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3951]
### URL(s) where the issue occurs
`https://it-explain.com/`

### Describe the issue
Anti-Adblock [blocking],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional lists 2 x RUS
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47620118-e0951500-dae6-11e8-8a5e-f141a00087ee.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3854
