### ISSUE TITLE
[Breakage] github.com, gitlab.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#3955]
### URL(s) where the issue occurs

```
https://github.com/uBlockOrigin/uAssets/blob/master/thirdparties/hosts-file.net/ad_servers.txt
https://github.com/jspenguin2017/uBlockProtector/blob/master/src/resources/ima3.js

https://gitlab.com/xuhaiyang1234/Test/blob/master/ima3.js
```

### Screenshots

![image](https://user-images.githubusercontent.com/7283682/47623517-357d5f00-dad8-11e8-97ed-9bda3904d81d.png)
![image](https://user-images.githubusercontent.com/7283682/47623462-85a7f180-dad7-11e8-8194-f0381c180908.png)

### Describe the issue

Generic filters in EasyList breaks some functionalities. 

Note: You may not be able to reproduce if the contributors are cached, in which case they are hard coded into the HTML file. 

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.17.0

### Settings

All default

### Notes

```
@@||github.com^$xhr
@@||gitlab.com^$xhr
```

**Comment by okiehsch** [comment]
````
@@||github.com^$xmlhttprequest,first-party
@@||gitlab.com^$xmlhttprequest,first-party
||github.com/_private/browser/stats$xmlhttprequest,first-party,important
````
I don't see any other xhr hits that need to be blocked on my end, can you confirm that?
`EasyPrivacy` does have more github specific entries.

**Comment by jspenguin2017** [comment]
How about: 
```
@@||github.com/*/contributors$xmlhttprequest,first-party
@@||gitlab.com^$xmlhttprequest,first-party
```

`genericblock` would be the ideal solution, but unfortunately uBO doesn't have it.

**Comment by stephenhawk8054** [comment]
Breakage in this repo, which says `Failed to load latest commit information.`

URL:
`https://github.com/osmanelitok/reklam`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/149684338-eb533d5e-3ad2-4a96-bb58-d2d6c6aac922.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79476
  cosmetic: 40526
  scriptlet: 16417
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30734-30, 11m
    ublock-badware: 3728-1, 11m
    ublock-privacy: 187-0, 11m
    ublock-abuse: 76-0, 11m
    ublock-unbreak: 1734-0, 11m
    easylist: 63044-586, 11m
    easyprivacy: 26627-480, 11m
    urlhaus-1: 8471-0, 11m
    plowe-0: 3682-2, 11m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 617 ms
popupPanel: 
  blocked: 11
```
</details>

Looks like due to this filter:
`/reklam/*$domain=~reklam.com.tr`

Modifying it fixes the issue:

```
/reklam/*$domain=~reklam.com.tr,badfilter
/reklam/*$domain=~reklam.com.tr|~github.com
```
