### ISSUE TITLE
funtik.tv

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#3958]
### URL(s) where the issue occurs

`http://funtik.tv`

### Describe the issue

Wait 10-15 seconds and you will see CPU load
Miner is loaded from **flighty.win** in frame

### Versions

- Browser/version: Opera Stable
- uBlock Origin version: 1.17.3b3

### Settings

- uBO's default settings

**Comment by okiehsch** [comment]
That domain is already blocked in the regional list.
![image](https://user-images.githubusercontent.com/16838044/47631321-f4bc2f00-db45-11e8-8165-158f8b72d869.png)

I will add it to `uBO-ressources`.
