### ISSUE TITLE
#2595

### ISSUE THREAD

**Issue by slrslr** [uBlockOrigin/uAssets#396]
Hello,

please can anyone reply to the issue https://github.com/gorhill/uBlock/issues/2595

@mapx- 

posted an answer, but it do not work and i cant update that issue.

His mentioned filter highlights/disables all tweets on the page. For example i use this page https://twitter.com/namesilo on which i can see Promoted Tweet.

I see that the full filter might be like this:
`###stream-item-tweet-859426120671907840.has-profile-promoted-tweet.separated-module.stream-item.stream-item.js-stream-item`

So i assume only variable inside the filter is that number. Can i use any wildcard placeholder instead of that number? Or any idea how the filter can look like to remove Promoted Tweet? Thank You alot

**Comment by mapx-** [comment]
what about
`##.has-profile-promoted-tweet`

**Comment by jjohns71** [comment]
@slrslr what filter lists do you use? There was a fix provided in uBlock filters [list a while back.](https://github.com/uBlockOrigin/uAssets/commit/bc997f0abd1ababb1ecc364053ce376e68f03934)

Are the following filters included in 'uBlock filters' list not sufficient anymore?
`twitter.com##.tweet[data-card2-type="promo_website"]`
`twitter.com##.promoted-tweet[data-disclosure-type="promoted"]`

**Comment by gorhill** [comment]
> Or any idea how the filter can look like to remove Promoted Tweet? 

Promoted tweets are filtered out with default settings, you should not have them.

**Comment by gorhill** [comment]
> For example i use this page https://twitter.com/namesilo on which i can see Promoted Tweet.

There are promoted tweets on that page, however they are properly filtered by uBO. Did you tampered with default settings.
