### ISSUE TITLE
BlockAdblock [Anti-Adblock] [147 domains]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3960]
As per https://github.com/uBlockOrigin/uAssets/issues/3401#issuecomment-419652191 and https://github.com/uBlockOrigin/uAssets/issues/3401#issuecomment-421703321

### URL(s) where the issue occurs

<details>
  <summary>Click to expand 147 domains</summary>

```
http://artenet.eu/public/
http://audiodusk.com/
http://autoclaim.win/
http://barisalcrimenews.com/
http://chronox.co.in/
http://coinpot.win/
http://crackupscexam.com/
http://crono.news/
http://djidjibidji.com/
http://dogecoins.top/
http://downloadselfishnet.blogspot.com/
http://ebharatportal.com/
http://ejobcircular-24.blogspot.com/
http://folkoteka.org/
http://france-pharmacies.fr/
http://free-btc-faucet.com/
http://freephotocourse.com/index.html
http://freetvall.net/
http://funvit.com/
http://gappsandroid.blogspot.com/
http://generatarjetasdecredito.com/
http://goesbike.com/
http://hachup.com/
http://hotelsevillanoacapulco.com/
http://ilbraccoitaliano.net/
http://indogate.com/
http://kumpulanresepmasakan.info/
http://lewdzone.com/
http://mediamalaya.com/
http://meriaama.com/
http://mobiletvshows.net/
http://modapkapps.com/
http://newautocarreview.com/
http://news.voyage-ile-maurice.info/ile-maurice/
http://nostaljioyunlar.hol.es/
http://openkorebrasil.org/
http://owari.io/
http://pastefull.net/
http://peachdirectory.com/
http://pelispaste.top/
http://peter-wiegel.de/
http://ponsel4g.com/
http://pornotorrentz.com/
http://potcoinlotto.com/
http://premiumproxy.net/
http://radioendirect.net/
http://rviva.com/
http://scinternacional.net/
http://shorten.cash/
http://songlyricsdatabase.info/
http://songlyricsplanet.info/
http://suomipornoa.net/
http://tenryunen.blogspot.com/
http://tv.click/
http://tvfree.me/
http://videorival.com/
http://wallpapersnow.com/
http://weatherx.co.in/
http://wickedhacker.com/
http://www.4download.net/
http://www.acaviet.com/
http://www.androidupdated.com/
http://www.angelpoiwoon.com/
http://www.bitdesire.it/
http://www.burmese-dictionary.org/
http://www.checkitjapan.com/
http://www.chinabuyandsell.com/
http://www.cicadawheels.com/
http://www.dailygkcapsule.com/
http://www.daslot.eu/
http://www.daslot.fr/
http://www.daslot.in/
http://www.daslot.ro/
http://www.eljavatar.com/
http://www.englishlistening.rocks/
http://www.everexam.in/
http://www.highlanderhelp.com/
http://www.icefilms.info/
http://www.jadid-tech.com/
http://www.kaanintavsiyesi.com/
http://www.koerper-entgiften.de/
http://www.liquifact.com/
http://www.magelang1337.com/
http://www.mangabatch.us/en/
http://www.mangamanga.ml/
http://www.michelle-trachtenberg.net/
http://www.mundoemalerta.com/
http://www.nicois.me/
http://www.notiziemusicali.it/
http://www.onecbook.online/
http://www.paesifantasma.it/
http://www.programmi-tv.eu/
http://www.punjabidharti.com/
http://www.qtelldistributorforum.com/
http://www.qtellhousehunter.com/
http://www.qtellperfectmatch.com/
http://www.qtellwebsitehosting.com/
http://www.r34anim.com/
http://www.riausports.com/
http://www.rippednaturally.com/
http://www.savetheworldbonus.com/
http://www.softmafia.com/
http://www.spoilcoconut.com/
http://www.sweetchin.com/
http://www.technoparkjobs.info/
http://www.tv-de.com/
http://www.twitbit.in/
http://www.wallpaperformobile.org/
http://www.wapmasterszone.com/#sthash.Wmzd7yIs.dpbs
http://www.zhoyi.net/
https://ammapettai.com/
https://applicationsandroidfrance.com/?bot_test=1
https://bitcoinfaucet.fun/
https://blockadblock.com/
https://cadsite.be/
https://computerworm.net/
https://dedeleads.com/
https://digitask.ru/
https://ecdlthemes.blogspot.com/
https://formatlux.blogspot.com/
https://freealts.pw/
https://galsen221.com/
https://godisagamer.org/
https://jawsnpaws.in/
https://jobjober.de/
https://konoz1.blogspot.com/
https://lanaparrillabrasil.com/
https://nota-promissoria.com/
https://notevi.com/
https://ossegredosdainformatica.blogspot.com/
https://packmundiales.blogspot.com/
https://pagcraft.com.br/index
https://qrlearn.com/
https://spiritualguidancetarot.com/
https://tataouinet.com/
https://toonstimeindia.com/
https://vstnsamples.blogspot.com/
https://www.best-antidepressanty.ru/
https://www.chopcoin.io/
https://www.cosplayarchive.com/
https://www.instawank.com/
https://www.oldglasgow.com/
https://www.somosbinarios.es/
https://www.therevcounter.co.uk/
https://www.txori.com/
https://www.videoformatter.com/
https://zeroboard.org/

```
</details>

### Describe the issue
Anti-Adblock [blocking] ==> `https://blockadblock.com/`
Some of them will fall into "Fanpage" category https://github.com/uBlockOrigin/uAssets/issues/3401 (THEtomaso)
Some of them might be already fixed by regional lists (very rarely) or other anti-adblock lists / addons.
There is more of them (over 2200), I've found 147 not fixed by uBO def as for now.

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47652112-5e0f6280-db85-11e8-9d21-97d085022a1e.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default + uBO annoyance

**Comment by ZaphodBeebblebrox** [comment]
I didn't check all of the domains because there were a ton of them, but I checked a bunch, and all had bab.

**Comment by kulfoon** [comment]
OK, if THEtomaso (or anyone who wants) check and sort them all one by one, then later, Fanpage ones can be moved to Fanpage filter, but I think it's up for THEtomaso.

**Comment by THEtomaso** [comment]
In that list, I were able to identify three URLs, which can be categorized as being "fansites".
I've reported them here:
https://github.com/uBlockOrigin/uAssets/issues/3401#issuecomment-434008777

**Comment by kulfoon** [comment]
I have a suggestion, merge the both big bab filters into a single one: 

block A [A-Z] (Fanpage domains like ) `aaa.fanpage.com,bbb.fanpage.com,ccc.fanpage.com`... +
block B [A-Z] (non-Fanpage domains) `aaa.non-fanpage.com,bbb.non-fanpage.com,ccc.non-fanpage.com`... 
(or vice versa) , so effect is like this:
`aaa.fanpage.com,bbb.fanpage.com,ccc.fanpage.com,aaa.notfanpage.com,bbb.notfanpage.com,ccc.notfanpage.com##+js(bab-defuser.js)`

The both group will keep the independent internal A-Z order, after joining the both groups no global sorting [A-Z] (messing) will be applied,.

But it's just a suggestion, maybe there is a reason to keep them as separate groups? (THEtomaso)?
And also it will require to convert `aaa.weppage.*` back into separate non `*` domains.

**Comment by THEtomaso** [comment]
> maybe there is a reason to keep them as separate groups? (THEtomaso)?

It's not my decision.
I only report the damn things. :)

**Comment by ZaphodBeebblebrox** [comment]
I see no reason to. I'll wait and see what okiehsch and mpax- say, I am new compared to them.

**Comment by okiehsch** [comment]
It really does not matter one way or the other, just leave them seperate, but if you want to merge all `bab-defuser` instances I will not complain.

**Comment by kulfoon** [comment]
I'm definately not for merging all bab filters (as this can cause too much interference), but I very opt for merging just the 4 biggest ones (combined total about 559 domains !). They are reasonably new (placed near the end of the list), so there is practically no interference, just like typically adding new domains to already existing filters, just merge the given 4 into a one big fish! Wow! 

<details>
  <summary>Click to expand</summary>
1 [Line 10386]

`iwatchgot.com,iwatchseries.online,watch30rockonline.com,watchadventuretime.com,watchamericandad.net,watcharcheronline.com,watcharresteddevelopment.com,watchbreakingbad.online,watchcheersonline.com,watchcommunity.online,watchcurbyourenthusiasm.com,watchdoctorwhoonline.com,watcheverybodylovesraymond.com,watchfamilyguy.cc,watchfearthewalkingdead.net,watchfriendsonline.net,watchgreysanatomyonline.com,watchhowimetyourmother.com,watchhowimetyourmother.net,watchitsalwayssunnyinphiladelphia.com,watchkingofthehill.com,watchonetreehillonline.com,watchparksandrecreation.net,watchprisonbreakonline.com,watchpsychonline.net,watchscrubsonline.com,watchseinfeld.com,watchsmallvilleonline.net,watchsouthpark.cc,watchsupernaturalonline.cc,watchthat70show.com,watchtheofficeonline.net,watchthesopranos.com,watchthevampirediaries.com,watchthewalkingdead.online,watchthexfiles.com,watchtopgearonline.net,watchtwoandahalfmenonline.com##+js(bab-defuser.js) `

2 [Line 11453]
`aj-styles.net,ajlee.org,ajmcleanweb.com,alexandra-daddario.org,alexandradaddariodaily.net,alliefansite.com,alona-tal.com,amandaseyfried.us,amyadams-source.com,anadearmas.net,annakendrick-fr.com,annalise-basso.com,anyataylorjoy.org,archie-panjabi.com,arianatoday.net,aseyfried.org,aubreyk-miller.com,ava-allan.com,avgeropoulos.com,b-larson.net,bailee-madison.org,barbieblanksource.com,beckylynchsource.com,believe-in-rollins.com,bellahadid.*,bellathorne.net,beyonceonline.org,billiekay.com,brynn-rumfallo.net,caitylotz.net,callie-hernandez.net,charlize-theron.fr,chloe-lukasiak.net,chloemoretz.org,chriswoodfan.com,clemencepoesyfan.com,daddariofan.net,daisy-ridley.us,daisyridley.us,danstevensbrasil.com,depplovers.com.br,dianna-agron.org,dove-cameron.org,drew-mcintyre.com,eizagonzalez.com.br,elijah-wood.org,elizabethlailbrasil.com,elizabetholsen.us,emilyosment.net,emma-roberts.org,emma-stone.us,emmaengleonline.com,emmawatson.org,fan.pw,fanningdakota.com,fanningelle.com,fans.bz,fansitehost.com,fergie-web.net,finn-wittrock.net,florian-silbereisenfan.net,foreverrobin.com,freefansitehosting.com,galleryaloud.com,granmetaliksource.com,hailee-steinfeld.*,harrypotterweb.com,hilarie-burton.org,hilary-swank.com,iansomerhalderfan.com,inourharts.com,isabelleallen.net,jade-pettyjohn.com,jamesfranconetwork.net,jan-smitfan.nl,jenna-coleman.org,jennaortega.net,jennifer-lawrence.com,jennifer-lawrence.us,jenniferlawrence.org,jenniferlawrence.us,jessica-chastain.org,jessica-lowndes.net,jlospain.net,joey-king.net,jon-bernthal.com,josh-duhamel.org,jude-law.net,julia-garner.com,julianna-margulies.net,junotemple.us,k-dunst.net,kaley-cuoco.net,kardashianworld.net,katie-mcgrath.com,katyperryonline.com,kaya-scodelario.org,kendallkyliefans.com,kerirussellweb.com,kiernan-shipka.org,landry-bender.com,landycannononline.com,liamhemsworth.org,lilireinhart.us,lily-chee.com,lincedorado.com,lizolsen.com,lizzieolsen.us,lucyhaledaily.us,mackenzie-foy.com,mackenzie-ziegler.net,mackenziefoy.net,maddie-ziegler.net,mandy-rose.com,mandyrose.org,margotrobbieonline.com,marguerite-moreau.com,megan-fox.us,meghan-markle.org,mia-yim.com,michael-french.net,michellekeegan.net,mileyupdateuk.com,mirandakerrfans.com,miriammcdonald.org,missbilliepiper.com,natalia-dyer.com,niajax.com,official-makenzie-moss-fanpage.com,olesyarulin.net,olivia-holt.net,olsenfans.com,paulalacroixbrasil.com,phillipa-soo.com,r-carlylefans.com,r-speightjr.com,raffey-cassidy.com,rey-mysterio.net,rhona-mitra.com,ritaoracentral.org,rowan-blanchard.net,rowanblanchard.net,ryanphillippe.net,sabrina-carpenter.org,shipka.net,sigourney-weaver.net,simplyleighanne.net,smg-france.net,sofia-carson.org,sofiavergaraweb.net,stellahudgensdaily.net,strahovski.net,summer-rae.com,taron-egerton.com,thomasholland.net,timothy-o.com,tom-hiddleston.org,trinity-fatu.net,trishstratus.com,vanessa-kirby.com,viggo-mortensen.com,violett-beane.com,wentworth-miller.org,withlove.info,zoe-kravitz.com,zooey-deschanel.com##+js(bab-defuser.js)`

3 [Line 12346]
`5tawzeef.com,aetools.*,ahorravueltas.com,allartsoftworks.com,androidemulator.org,androprogrammer.com,animetubeitalia.it,arabass.me,arabseries.net,arbitri.com,arenavision.top,artsongcentral.com,asiabusiness.today,autofans.pw,baladag4.com.br,bazarynek.pl,belfastforum.co.uk,bezpolitickekorektnosti.cz,biodatamaker.com,bitclaimer.me,bollystop.tv,borussiadortmund.net.br,boxwares.com,brasilseries.org,camfoot.com,cartoonporn.tv,cdrlabs.com,cimagram.com,claimbtc.in,connect-trojan.net,countrytabs.com,crawlist.net,cricket-tv.me,cryptoaddicted.biz,cybernog.com,daslot.com,davidcuttermusic.com,desitelugu.com,dicasedetonados.com,dificuldadezero.com.br,digitalcomicmuseum.com,digitalpornhub.com,directassuranceauto.fr,doctormalay.com,dopedgeeks.com,e-hiszpanski.com,ecoles-du-web.fr,eduvark.com,emploiads.com,ergasiakanea.eu,eslwriting.org,euamonudes.com,exameninja.com.br,expressfaucet.com,ezyzip.com,farmville2-everinn.eu,farmville2free.com,faucetpot.com,faucetrain.ga,fifaultimateteam.it,filesaver.pro,filmyonline.date,fintel.io,forexwinners.biz,forexwinners.org,formuleonline.*,forum.vorota.de,freearticlespinning.com,freedogecoin.win,freeudemypaidcourse.com,fuckcomix.com,fullsofthome.com,fv2freegifts.org,gamesandroidhvga.net,generadordni.es,getinfos.net,ggulpass.com,gklokam.com,globalssh.net,goldpaste.net,golshoot.com,gozd-les.com,greyhound-data.com,gsmdunya.com,healthremediesforlife.com,hostpics.biz,ilbraccoitaliano.net,indiatyping.com,indohooker.com,instaphotodownloader.com,jamaicanjobsonline.com,jetseotools.com,jobculture.fr,joudymovies.xyz,kallitheacity.gr,kimtaeyeon.com.br,kurditv2.com,l2network.eu,la2world.net,lambingan.su,linuxliteos.com,livetvcafe.me,loan-trading.net,macdailynews.com,magtxt.com,manatelugu.com,mangasave.me,marugujarat.org,marugujarat.org.in,medmedicine.it,megafilmess.com,megsta.com,milanworld.net,miningquiz.com,modsimuladores.com,mostbeautifulman.com,movieproxy.net,mycraftsbetter.com,myicloud.info,myxcamgirl.com,n1bestfreeclassifiedads.com,nangiphotos.com,netrider.net.au,newreleasetoday.com,newxboxone.ru,nhlstreamz.com,nowtvshow.com,nu6i-bg-net.com,obengplus.com,olympine.com,otakugame.fr,otakuindo.net,pelispaste.top,peshdpatch.*,pinayhooker.com,pinaywalkers.net,pinoy-tv.ws,plussizenation.com,pornbaaz.com,premiumleecher.com,premiumproxy.net,press-news.gr,programmingbuddy.club,proxy2018.ml,proxyhub.eu,proxyvideo.net,ps3-id.es,putramelayu.web.id,qtellbuyandsell.com,qtellclassifiedads.com,qtellelectronicsexpress.com,qtelljoblotsforum.com,queissonovinha.com,quotespics.net,raimines.com,readshingekinokyojin.com,readshokugekisoma.com,reviewtv.in,robert-downeyjr.com,s7fanclub.com,saigoneer.com,sambagblog.com,savetubes.com,scoprirelafisica.it,sehatsegar.net,seononline.com,seosocialnews.info,showbiz.gr,siftheadsgames.com,sinepinoy.net,sjcomics.com,sketchupbrasil.com,skidrowfull.com,smartcoin.fr,smartprep.in,sparkplug-crossreference.com,speechtyping.com,spite.cz,stepack.*,streaming-football.club,swertreshearing.net,telluofficial.com,tendancehotellerie.fr,tendermeforfree.com,th3nextlevel.xyz,themelot.me,thoptv.net,tibiawiki.com.br,tntendirect.com,tricksbest.com,tube2gram.com,tutoriaux-excalibur.com,uadforum.com,unlimit-pro.*,usmleexperiences.review,videounblock.com,viply.ga,vivereurbino.it,vlasteneckenoviny.cz,vmwaremine.com,vodiy.ua,vpnjantit.com,w1.motogon.ru,wadaef.com,wallpaperdownload.xyz,watchpornmovies.org,webforefront.com,whois-il.com,wholesalefreeclassifiedads.com,realmofmetal.org,wwtechteam.net,yaartv.tv,yuksoftware.com,zermusicz.com,zigstat.com,zoopertv.com##+js(bab-defuser.js)`

4 [Line 13069]
`4download.net,ammapettai.com,acaviet.com,androidupdated.com,angelpoiwoon.com,applicationsandroidfrance.com,artenet.eu,audiodusk.com,autoclaim.win,barisalcrimenews.com,best-antidepressanty.ru,bitcoinfaucet.fun,bitdesire.it,burmese-dictionary.org,cadsite.be,checkitjapan.com,chinabuyandsell.com,chopcoin.io,cicadawheels.com,chronox.co.in,coinpot.win,computerworm.net,cosplayarchive.com,crackupscexam.com,crono.news,dailygkcapsule.com,daslot.*,dedeleads.com,digitask.ru,djidjibidji.com,dogecoins.top,downloadselfishnet.*,ebharatportal.com,ecdlthemes.*,ejobcircular-24.*,eljavatar.com,englishlistening.rocks,everexam.in,folkoteka.org,formatlux.*,france-pharmacies.fr,free-btc-faucet.com,freealts.pw,freephotocourse.com,freetvall.net,funvit.com,galsen221.com,gappsandroid.*,generatarjetasdecredito.com,godisagamer.org,goesbike.com,hachup.com,highlanderhelp.com,hotelsevillanoacapulco.com,icefilms.info,ilbraccoitaliano.net,indogate.com,instawank.com,jadid-tech.com,jawsnpaws.in,jobjober.de,kaanintavsiyesi.com,koerper-entgiften.de,konoz1.*,kumpulanresepmasakan.info,lanaparrillabrasil.com,lewdzone.com,liquifact.com,magelang1337.com,mangabatch.us,mangamanga.ml,mediamalaya.com,meriaama.com,michelle-trachtenberg.net,mobiletvshows.net,modapkapps.com,mundoemalerta.com,newautocarreview.com,nicois.me,nota-promissoria.com,notevi.com,notiziemusicali.it,nostaljioyunlar.hol.es,oldglasgow.com,onecbook.online,openkorebrasil.org,ossegredosdainformatica.*,owari.io,packmundiales.*,pagcraft.com.br,paesifantasma.it,pastefull.net,peachdirectory.com,pelispaste.top,peter-wiegel.de,ponsel4g.com,pornotorrentz.com,potcoinlotto.com,premiumproxy.net,programmi-tv.eu,punjabidharti.com,qrlearn.com,qtelldistributorforum.com,qtellhousehunter.com,qtellperfectmatch.com,qtellwebsitehosting.com,r34anim.com,radioendirect.net,riausports.com,rippednaturally.com,rviva.com,savetheworldbonus.com,scinternacional.net,shorten.cash,softmafia.com,somosbinarios.es,songlyricsdatabase.info,songlyricsplanet.info,spiritualguidancetarot.com,spoilcoconut.com,suomipornoa.net,sweetchin.com,tataouinet.com,technoparkjobs.info,tenryunen.*,therevcounter.co.uk,toonstimeindia.com,tv-de.com,tv.click,tvfree.me,twitbit.in,txori.com,videoformatter.com,videorival.com,voyage-ile-maurice.info,vstnsamples.*,wallpaperformobile.org,wallpapersnow.com,wapmasterszone.com,weatherx.co.in,wickedhacker.com,zeroboard.org,zhoyi.net##+js(bab-defuser.js)`
</details>
.

**Comment by janolapin2016** [comment]
W10 Pro X64 Palemoon Ublock Origin 1.16.4.5 
Hello 
I have trouble with this website https://www.mega-p2p.net/ 
I add rule but I think you can add too in your own filter list
thanks

**Comment by THEtomaso** [comment]
@mapx-:

Any downside to using the bab-defuser for that site?

**Comment by mapx-** [comment]
A simpler solution is always preferable (and `generichide` is way better than injecting a scriptlet)

**Comment by janolapin2016** [comment]
Tomaso give me this script to add in my filters rule and it work : mega-p2p.net##+js(bab-defuser.js)
He suggest me to ask you to add it in your own filter list

**Comment by ghajini** [comment]
`https://savelinks.me/view/hWQ4rsCSMO`
blockadblock appears after sometime

**Comment by mapx-** [comment]
closing now, for other sites please open separate issues
