### ISSUE TITLE
auto-swiat.pl + komputerswiat.pl + fakt.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3961]
URL(s) where the issue occurs

`http://www.auto-swiat.pl/testy/audi-q8-50-tdi-ma-robic-dobre-wrazenie-test/bk24ec`
`https://www.komputerswiat.pl/`
`http://www.fakt.pl/kobieta`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by ZaphodBeebblebrox** [comment]
@MajkiIT

**Comment by MajkiIT** [comment]
@KiLL4FuNK I don't see Adblock alert.
@krystian3w @hawkeye116477 Can you check it ?

**Comment by kulfoon** [comment]
With POL filter list enabled  I see only on:
 `https://www.komputerswiat.pl/aktualnosci/wydarzenia/qualcomm-apple-jest-nam-winne-7-miliardow-dolarow/4wvfpkp` 

<details>
  <summary>screenshoot</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47655596-9adf5780-db8d-11e8-913c-95bf77145b10.png)

</details>

**Comment by krystian3w** [comment]
Clean!

**Comment by kulfoon** [comment]
I've updated all the filter lists now, and clean.

**Comment by krystian3w** [comment]
@KiLL4FuNK try this for `komputerswiat.pl`

`komputerswiat.pl###ks_breaking_news:style(position: absolute!important; left: -3000px!important;)`

**Comment by krystian3w** [comment]
@KiLL4FuNK try this for `komputerswiat.pl`

`komputerswiat.pl###ks_breaking_news:style(position: absolute!important; left: -3000px!important;)`

---


and temporarily  [subscribe] <code>[POL: polskie filtry do Adblocka i uBlocka][Polskie Filtry Subscribe] </code>
Found on 26. positon in `Regions, language` filters.

[Polskie Filtry Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt&title=Official%20Polish%20filters%20for%20AdBlock,%20uBlock%20Origin%20and%20AdGuard

**Comment by hawkeye116477** [comment]
Clean

**Comment by krystian3w** [comment]
Seems no longer clean after removing https://github.com/olegwukr/polish-privacy-filters/blob/master/anti-adblock.txt from assets.json.

https://github.com/user-attachments/assets/613cdd85-c3d2-404c-9d1b-6505835351a5

https://github.com/MajkiIT/polish-ads-filter/issues/23282

Very similar at `https://plejada.pl/`.
