### ISSUE TITLE
pokemonforever.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3964]
### URL(s) where the issue occurs
`http://pokemonforever.com/`

### Describe the issue
Anti-Adblock [annoyance],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47656285-17bf0100-db8f-11e8-854f-2fe13e35bd2d.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by kulfoon** [comment]
Not fixed.

**Comment by mapx-** [comment]
fixed
