### ISSUE TITLE
pandajogosgratis.com.br [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3965]
### URL(s) where the issue occurs
`http://www.pandajogosgratis.com.br/`

### Describe the issue
Anti-Adblock [blocking],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional list 2 x SPA
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47656730-f0b4ff00-db8f-11e8-8afd-cc665791daf8.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by kulfoon** [comment]
Not fixed.

**Comment by mapx-** [comment]
fixed
