### ISSUE TITLE
small cleaning

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3966]
in ublock-filters

Typo:
`getyourbitco.in##+js9set-constant.js, adBlock, false)` (but the filter still works anyway)

Duplicates:
`@@||sfiles.org^$generichide`

`cinedetodo.*##+js(window.open-defuser.js)`

Redundancies:

`||camsoda1.com/promos/iframe/*$subdocument,domain=camwhores.tv` and
`||lite-iframe.stripcdn.com^$subdocument,domain=camwhores.tv`  have been made redundant by `*$subdocument,domain=camwhores.tv`

`pornqd.net##a[href^="http://www.poweredbyliquidfire.mobi/"]` has been made redundant by `##a[href^="http://www.poweredbyliquidfire.mobi/"]`

<details>
  <summary>Click to expand</summary>

  `stream2watch.cc`

in 

`9xbuddy.com,adf.ly,albumkings.org,ay.gy,azvideo.net,bestfilmeshd.com,bombuj.eu,cloudyfiles.org,crackingpatching.com,daclips.in,dfiles.eu,divxtotal3.net,downsub.com,easyview.eu,english-subtitles.pro,filescdn.com,filmuptobox.net,freegamesdl.net,gomovies.es,gorillavid.in,hulkload.com,j.gs,jkanime.net,karanpc.com,livewidget.net,macserial.com,microify.com,minecraft-forum.net,newmusic.trade,onmovies.to,opensubtitles.org,pintient.com,pirateproxy.*,pleermp3.net,psarips.com,q.gs,ripple.is,security-links.com,snowfiles.com,solidfiles.com,stream2watch.cc,suprafiles.org,thepiratebay.org,torrentexx.com,uploadrocket.net,uptobox.com,vidabc.com,zippyshare.com##+js(abort-on-property-write.js, Fingerprint2) `

has been made redundant by 

`stream2watch.*##+js(abort-on-property-write.js, Fingerprint2)`

so

`stream2watch.*`

from

`stream2watch.*##+js(abort-on-property-write.js, Fingerprint2) `

can be moved into

`9xbuddy.com,adf.ly,albumkings.org,ay.gy,azvideo.net,bestfilmeshd.com,bombuj.eu,cloudyfiles.org,crackingpatching.com,daclips.in,dfiles.eu,divxtotal3.net,downsub.com,easyview.eu,english-subtitles.pro,filescdn.com,filmuptobox.net,freegamesdl.net,gomovies.es,gorillavid.in,hulkload.com,j.gs,jkanime.net,karanpc.com,livewidget.net,macserial.com,microify.com,minecraft-forum.net,newmusic.trade,onmovies.to,opensubtitles.org,pintient.com,pirateproxy.*,pleermp3.net,psarips.com,q.gs,ripple.is,security-links.com,snowfiles.com,solidfiles.com,stream2watch.cc,suprafiles.org,thepiratebay.org,torrentexx.com,uploadrocket.net,uptobox.com,vidabc.com,zippyshare.com##+js(abort-on-property-write.js, Fingerprint2) 
`

as a replacement for

`stream2watch.cc`

or 

`stream2watch.cc`

can be removed from

`9xbuddy.com,adf.ly,albumkings.org,ay.gy,azvideo.net,bestfilmeshd.com,bombuj.eu,cloudyfiles.org,crackingpatching.com,daclips.in,dfiles.eu,divxtotal3.net,downsub.com,easyview.eu,english-subtitles.pro,filescdn.com,filmuptobox.net,freegamesdl.net,gomovies.es,gorillavid.in,hulkload.com,j.gs,jkanime.net,karanpc.com,livewidget.net,macserial.com,microify.com,minecraft-forum.net,newmusic.trade,onmovies.to,opensubtitles.org,pintient.com,pirateproxy.*,pleermp3.net,psarips.com,q.gs,ripple.is,security-links.com,snowfiles.com,solidfiles.com,stream2watch.cc,suprafiles.org,thepiratebay.org,torrentexx.com,uploadrocket.net,uptobox.com,vidabc.com,zippyshare.com##+js(abort-on-property-write.js, Fingerprint2) `

</details>

**Comment by ZaphodBeebblebrox** [comment]
Thanks.
