### ISSUE TITLE
filmesflix.ga [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3967]
URL(s) where the issue occurs

`http://www.filmesflix.ga/filmes/a-justiceira/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by kulfoon** [comment]
I have a question, as Nano Defender fixes it, so why don't use it?

**Comment by ZaphodBeebblebrox** [comment]
Nano defender is used by 118,193 people on chrome (assuming, for the sake of simplicity, that none of the downloads are repeats), while uBO is used by more than 10,000,000 on chrome and 4,695,167 on firefox. Therefore, we have to assume that most people are not using ND, and add filters accordingly.

**Comment by kulfoon** [comment]
I remember AAK-REEK filter list included in uBO with a notification to install the script too, and since ND = AAK-REEK, why aren't the same way ND's filter lists included in uBO with a notification to install ND?
