### ISSUE TITLE
Add uBlock specific cookie consent blocker for Wikia to uBO Annoyances

### ISSUE THREAD

**Issue by theel0ja** [uBlockOrigin/uAssets#3968]
https://github.com/ryanbr/fanboy-adblock/issues/572#issuecomment-428090691

maybe add to uBlock Annoyances?

**Comment by THEtomaso** [comment]
For anyone considering to add those blocking rules; read up on the discussion that theel0ja refered to.
Blocking the cookie consent dialog will result in breakage!

**Comment by okiehsch** [comment]
Cookie consent messages will not beblocked in `uBO-annoyances`.
