### ISSUE TITLE
Google tag manager blocked

### ISSUE THREAD

**Issue by AmiT177** [uBlockOrigin/uAssets#3969]
### URL(s) where the issue occurs

`http://amit.systems/ublocktest.html`
(any URL that uses google tag manager, provided a test one)

### Describe the issue

uBlock is blocking google tag manager from running its scripts.
some websites require on it, for example, loading js scripts and updating titles using it.

### Screenshot(s)

https://i.imgur.com/3bA8zSN.png
https://i.imgur.com/o0dj5KF.png
with uBlock disabled: https://i.imgur.com/2eVu1bX.png

### Versions

- Browser/version: Firefox 64.0b4
- uBlock Origin version: v1.17.2

### Settings

Default settings

### Notes

In my opinion, google tag manager should be added as whitelisted by default, otherwise, it could affect user's experience while browsing websites without knowing it.

**Comment by okiehsch** [comment]
> google tag manager should be added as whitelisted by default

Will not happen, if you find real world examples of sites broken by the [redirection](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L570-L596) `uBO` uses the site will be fixed.
