### ISSUE TITLE
Redbull.tv playback is broken

### ISSUE THREAD

**Issue by sologoub** [uBlockOrigin/uAssets#397]
### URL(s) where the issue occurs

`https://www.redbull.tv/tv`
`https://www.redbull.tv/live/AP-1PWUW9Y591W11/uci-mountain-bike-world-cup`

### Describe the issue

No videos play on redbull.tv

### Screenshot(s)
![redbull_tv_broken](https://cloud.githubusercontent.com/assets/915423/25873038/ba54fbfc-34c1-11e7-9c3e-4a4a34c3a599.png)

### Versions

- Browser/version: Version 57.0.2987.133 (64-bit)
- uBlock Origin version: 1.12.1

### Settings

- No changes

### Notes

Adding the following to filters fixes the playback:
@@||assets.adobedtm.com$script,domain=redbull.tv
@@||redbullmediahouse.hb.omtrdc.net$domain=redbull.tv

**Comment by sologoub** [comment]
Pull request: https://github.com/uBlockOrigin/uAssets/pull/398

**Comment by okiehsch** [comment]
I can watch the video if I add 
`@@||assets.adobedtm.com$script,domain=redbull.tv`
tested with Chrome 58  and Firefox 53.
Does it really only work on your end if you add `@@||redbullmediahouse.hb.omtrdc.net$domain=redbull.tv`?

**Comment by sologoub** [comment]
Haven't tried without it, but the /tv one seems to work as well.

It was spewing a bunch of errors in console and network tabs of devtools in chrome, so I included it.

hb.omtrdc.net is Adobe's video heartbeat analytics solution and appears to be backed into the player.
https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/js_2.0/vhl-2.0_js.pdf

No clue if it will work without it for all videos/use cases.

**Comment by sologoub** [comment]
Btw, I should mention that I work at RBMH. Want me to ask the team that built the player?

**Comment by okiehsch** [comment]
That's up to you. I will add the exception filter `@@||assets.adobedtm.com$script,domain=redbull.tv`
If there are still problems with the player after that with some videos/cases just report it here.

**Comment by sologoub** [comment]
Thanks!

**Comment by SMed79** [comment]
Please care about non-ubo users and report at [easylist forum](https://forums.lanik.us/viewtopic.php?f=64&t=36742).

**Comment by gorhill** [comment]
I think a simple "@ryanbr fyi" when the issue is in EasyList/EasyPrivacy, should be enough, less friction to actually have the issue reported/fixed.
