### ISSUE TITLE
Unable to add more text to My filters

### ISSUE THREAD

**Issue by crim2som** [uBlockOrigin/uAssets#3970]
### URL(s) where the issue occurs
ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62/dashboard.html

### Describe the issue
Open uBlock Origin - Options - My filters. Go to bottom of existing list and unable to type more text into My filter. 

### Screenshot(s)

![my filters](https://user-images.githubusercontent.com/44589181/47683589-ef9fc400-dbc7-11e8-8aa6-70c177930209.jpg)

### Versions
- Operating System: Windows 10 Home (x64) Version 1809 (build 17763.1)
- Browser/version: Microsoft Edge 44.17763.1.0 - Microsoft Edge HTML 18.17763
- uBlock Origin version: 1.15.24

### Settings
Default

### Notes
Internet search does not find this problem or remedy.

**Comment by ZaphodBeebblebrox** [comment]
This is the wrong place. You should report this at [uBlockOrigin/uBlock-issues](https://github.com/uBlockOrigin/uBlock-issues)

**Comment by mapx-** [comment]
or here
https://github.com/nikrolls/uBlock-Edge/issues

**Comment by crim2som** [comment]
Thank you ZaphodBeebblebrox - but https://github.com/uBlockOrigin/uBlock-issues says Do not post any filter list issues (here).
Thank you mapx - but https://github.com/nikrolls/uBlock-Edge/issues says Filter issues **MUST NOT** be reported here.

**Comment by mapx-** [comment]
It' isnt a filter issue. I seems to be a problem with the adblocker itself.

**Comment by crim2som** [comment]
Thank you mapx - Windows updates has auto installed Win10 Ver 1809 and there has been many reported problems about Microsoft releasing yet another update that is not fit for purpose. There is no auto update feature within uBlock Origin and Microsoft Store does not reveal the current version status. 
uBlock Origin does not appear to have a repair feature that can be invoked.  So what is the remedy?
