### ISSUE TITLE
Reddit.com mobile app ads

### ISSUE THREAD

**Issue by chrissnell** [uBlockOrigin/uAssets#3971]
### URL(s) where the issue occurs
https://www.reddit.com

### Describe the issue

When browsing from a mobile browser like Safari on iOS, Reddit displays numerous intrusive ads to get you to use their crappy mobile app.

I realize that uBlock Origin does not support Safari iOS, but many third-party blockers use its block list so I'm hoping that this can be added.

### Versions

- Browser/version: Safari / iOS
- uBlock Origin version: N/A

### Notes
Here are the rules that I created:
```
www.reddit.com##.SnackBar
www.reddit.com##.pulse.TopButton
www.reddit.com##.XPromoPill
www.reddit.com##.XPromoPopup
www.reddit.com##.NavFrame > .xpromoMinimal.DualPartInterstitial

```

**Comment by okiehsch** [comment]
Why not open an issue with `Fanboy Annoyance List` or `Adguard Annoyances` those filters can be added and these lists are certainly more widespread then `uBO-annoyances`.

> but many third-party blockers use its block list so I'm hoping that this can be added.

`uBO-annoyances` is 95% useless unless the adblocker you use supports extended syntax.

**Comment by chrissnell** [comment]
Will do.  Thanks.

**Comment by mapx-** [comment]
@ryanbr
