### ISSUE TITLE
k2n

### ISSUE THREAD

**Issue by 1n5u9r** [uBlockOrigin/uAssets#3973]
### URL(s) where the issue occurs

`https://k2nblog.com/`

### Describe the issue

self host image popup later redirect to sketchy website `glotchat.click`  (Only on mainpage)

### Versions

- Browser/version: Firefox 60.3.0esr (32-bit) \  Win7 32bit
- uBlock Origin version: 1.17.2

### Settings

- Im using medium filtering

### Notes

My resolve is to use the logger and create rule for the popup.
Also what is this 2 website : `eedsaiks.uk` and  `glotchat.click`  ?

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script - BlockAdBlock

`https://k2nblog.com/linkdl.html?url=aHR0cHM6Ly9taXIuY3IvWUI3S1VQUDk=`
