### ISSUE TITLE
halafootmobile.blogspot.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3974]
### URL(s) where the issue occurs
`http://halafootmobile.blogspot.com/`

### Describe the issue
Anti-Adblock [annoyance],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional list ARA
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47713983-e81a0280-dc3b-11e8-905c-803529b51c18.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by ZaphodBeebblebrox** [comment]
I get the anti-adblock bar even with uBlock disabled.

**Comment by uBlock-user** [comment]
```
halafootmobile.blogspot.com###exepopup
halafootmobile.blogspot.com##div:has-text(ad blocker)
```

**Comment by kulfoon** [comment]
> I get the anti-adblock bar even with uBlock disabled.

True.
