### ISSUE TITLE
monero-miner.com [Anti-Adblock] [Popup] 

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3975]
### URL(s) where the issue occurs
`https://www.monero-miner.com/`

### Describe the issue
[Crypto Mining Wall]
1 Anti-Adblock [blocking] - but I don't care as it gets fixed by other filter lists (Nano Defender) for me
2 Popup [blocking] - popups after scrolling the website down or pressing the Start Mining button - must wait 30 sec before mining.

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- uBlock filters – Annoyances​​​​​
- Adguard’s Annoyance List​​​​​
- Fanboy’s Annoyance List​ 
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the Popup issue - it fixes only Anti-Adblock message

### 1 Anti-Adblock

![ss2](https://user-images.githubusercontent.com/43844449/47714368-f6b4e980-dc3c-11e8-8189-87272e01e7ac.png)

### 2 Popup
![ss1](https://user-images.githubusercontent.com/43844449/47714317-d553fd80-dc3c-11e8-9bb5-72f45977ab64.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by pohuiusemail4741** [comment]
Install these extension chrome://extensions/?id=ggolfgbegefeeoocgjbmkembbncoadlb

**Comment by kulfoon** [comment]
I already have it as I mentioned:
>     * Nano Defender + it's lists
It doesn't fix the Popup issue - it fixes only Anti-Adblock message

**Comment by mapx-** [comment]
try
```
@@||monero-miner.com^$generichide
monero-miner.com##+js(abort-on-property-read.js, admiral)
monero-miner.com##.sg-popup-overlay
monero-miner.com###sgpb-popup-dialog-main-div
```

**Comment by kulfoon** [comment]
Effect is the same as if I had Nano Defender enabled, the Anti-Adblock is gone, but the Popup still is here and must wait 30 sec before mining.

**Comment by kulfoon** [comment]
Still no difference on Firefox (the both solutions).

As I didn't check on Opera before, I've also checked on Opera 56 right now the both mapx- 's and ZaphodBeebblebrox 's solutions, and the both solutions remove both the Anti-Adblock and the Popup, but:

<details>
  <summary>in the mapx- 's solution, crypto-mining doesn't load:</summary>

![ss1](https://user-images.githubusercontent.com/43844449/47745645-6f8b6400-dc84-11e8-82fc-74d695e08fd4.png)

</details>
.
<details>
  <summary>The ZaphodBeebblebrox 's solution works fine:</summary>

![ss2](https://user-images.githubusercontent.com/43844449/47745871-f9d3c800-dc84-11e8-840c-f79e97eeed76.png)

</details>
.
but as I've said none of the solutions works on Firefox.

**Comment by kulfoon** [comment]
Right, I didn't notice that somehow I had the website whitelisted in uBO when checking the both solutions in Firefox (forgot to unwhitelist). So now afier I've unwhitelisted the website I've checked again the both solutions in Firefox and the mapx- 's solution behaves the same way like in Opera (crypto-mining doesn't load), and the ZaphodBeebblebrox 's solution works fine just like in Opera.

**Comment by kulfoon** [comment]
New domain `https://www.coinminingonline.com/`.

**Comment by kulfoon** [comment]
The Anti-Adblock still not fixed, STR:
- visit the webpage
- click blue "Read More" button (to start mining)
- scroll the page down

**Comment by mapx-** [comment]
@kulfoon  please refrain from such reproofs and from pinging us. We are all volunteers in our spare time.

try this filter (and report exactly the site where does happen - as you added 2 sites on the same issue)
`coinminingonline.com##.sgpb-popup-overlay`

**Comment by keczuppp** [comment]
> @uBlock-user : https://github.com/uBlockOrigin/uAssets/issues/8348#issuecomment-743214990 : Now you're comparing to yourself to kulfoon ? You have been advised what to do, this back and forth arguement only adds further noise here.

Why are you so nervous, take it easy, do you always block threads when you lose arguments, go to doctor...

**Comment by keczuppp** [comment]
> https://github.com/uBlockOrigin/uAssets/issues/3975#issuecomment-743225608
> This comment was marked as disruptive content.

Haha It seems the truth hurts you so much..., look uBlock-user, the only disruptive behaviour is your agressive behaviour, the one described in the comment you just have hidden, also there is many of your comments on the whole github, in which the comments, you just insult people with multiple vulgarisms, you have serious psychical problems here on github...
