### ISSUE TITLE
icutlink.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3979]
URL(s) where the issue occurs

`https://icutlink.com/znF4`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by lain566** [comment]
There's a popup 
`https://icutlink.com/cLRxbdtiRG`

Suggested filter
`icutlink.com##+js(abort-current-inline-script.js, eval, ppu)`

**Comment by ghajini** [comment]
`https://icutlink.com/DMVdd3zlMF`
There's a pppup

**Comment by dumbusernameidk** [comment]
anti-adblock

**Comment by ghajini** [comment]
`icutlink.com/rz79IjXFB7`
Popup ads

**Comment by mapx-** [comment]
- for ok / skip nothing to do => race condition
- I can remove the notification crap, I get no popups

**Comment by ghajini** [comment]
`https://icutlink.com/JM6nlwIzQ`
After this site in next site `newsten.online` where link is there, is not showing when ubo is active

**Comment by ghajini** [comment]
It doesn't worked

**Comment by okiehsch** [comment]
My commit addressed a popup as the message clearly states. 
It has nothing to do with the coundtdown not showing, which I can't reproduce.
Probably some android specific issue.

**Comment by ghajini** [comment]
Yes android specific. ...there is `newsten.online` where `get link` button appears when ublock disabled....this `get link` not appearing when ubo enabled

**Comment by mapx-** [comment]
I tested in firefox desktop, first whitelisting `newsten.online` then disabling completely uBO from FF => the get link + countdown never appears

**Comment by gwarser** [comment]
Anti adblock again: https://www.reddit.com/r/uBlockOrigin/comments/j8xw40/looking_for_nano_defender_alternative/g93oc6p/
