### ISSUE TITLE
1fichier

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#3984]
### URL(s) where the issue occurs

`https://1fichier.com/?5mzef7ozvfplpqoiel3a`

### Describe the issue

After i download a file, i can't see how many time i must wait for the next download.

### Screenshot(s)

With ublock enable, i see this
![11](https://user-images.githubusercontent.com/27068733/47732376-f8db7000-dc5d-11e8-9743-a6b75f96ea44.jpg)
 
but i don't see this
![12](https://user-images.githubusercontent.com/27068733/47732388-ff69e780-dc5d-11e8-8bfb-8b70a1fe6800.jpg)

### Versions

- Browser/version: Firefox 60 esr
- uBlock Origin version: 1.17.2

### Settings

My list:
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adblock Warning Removal List​
Adguard Base Filters​
Adguard Mobile Filters​
EasyList​
Adguard Spyware Filters​
EasyPrivacy​
Fanboy’s Enhanced Tracking List​
Malvertising filter list by Disconnect​​​​​
Malware Domain List​​​​​
Malware domains​
Spam404​
Adguard’s Annoyance List​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​

**Comment by mapx-** [comment]
unable to reproduce your issue

**Comment by ghajini** [comment]
click on download , did you get the file

**Comment by mapx-** [comment]
yes, tested in firefox, for chrome I have to wait now ...

**Comment by ghajini** [comment]
Anyone reproduce @okiehsch

**Comment by mapx-** [comment]
No issue in chrome too
