### ISSUE TITLE
hdrezka.*(ag)

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#3986]
### URL(s) where the issue occurs

`http://hdrezka.ag/films/drama/28854-zhena-2017.html`

### Describe the issue

Ads in player. Twice.

### Versions

- Browser/version: Opera
- uBlock Origin version: 1.17.3b4

### Settings

- uBO's default settings

**Comment by okiehsch** [comment]
Could you post a screenshot of the ads, I don't see any.
