### ISSUE TITLE
Amazon search sponsored products

### ISSUE THREAD

**Issue by yukunlin** [uBlockOrigin/uAssets#399]
### URL(s) where the issue occurs

* `https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=lego+star+wars&lo=kitchen&rh=i%3Aaps%2Ck%3Alego+star+wars`
* `https://www.amazon.com/gp/search/ref=sr_il_ti_toys-and-games?fst=as%3Aon&rh=k%3Alego+star+wars%2Cn%3A165793011%2Cn%3A166092011&keywords=lego+star+wars&ie=UTF8&qid=1494401119&lo=toys-and-games`
* `https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=coffee+machine&rh=i%3Aaps%2Ck%3Acoffee+machine`

### Describe the issue

Sponsored products on amazon.com search page are sometimes not completely hidden, and the page looks broken. 

### Screenshot(s)

![screen shot 2017-05-10 at 12 27 50 am](https://cloud.githubusercontent.com/assets/3442461/25887575/88772636-3517-11e7-9f60-6f6629e7c678.png)
![screen shot 2017-05-10 at 12 25 45 am](https://cloud.githubusercontent.com/assets/3442461/25887584/90d9d134-3517-11e7-8ab6-25b3c0468e0c.png)
![screen shot 2017-05-10 at 12 23 53 am](https://cloud.githubusercontent.com/assets/3442461/25887588/94e0c09e-3517-11e7-92bb-66f8637543af.png)
![screen shot 2017-05-10 at 12 24 05 am](https://cloud.githubusercontent.com/assets/3442461/25887591/96d76f4c-3517-11e7-9117-e156c262c022.png)

### Versions

- Browser/version: Chrome 58.0.3029.96
- uBlock Origin version:  1.12.1

### Settings

N/A

### Notes

It's probably caused by this rule not working all the time:
https://github.com/uBlockOrigin/uAssets/blob/adc3d55daa4e94c601fcfda3ed0f853476fca846/filters/filters.txt#L822

**Comment by yukunlin** [comment]
Yes, this rule worked for me.

**Comment by gorhill** [comment]
> It's probably caused by this rule not working all the time

Do you know if this other rule is still useful?
