### ISSUE TITLE
stfly.press [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#3990]
URL(s) where the issue occurs

`http://stfly.press/TywZ`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by lain566** [comment]
Anti-adblock
`http://stfly.press/LVSYCdIV`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by ghajini** [comment]
`stfly.me/QIBf72`
Popup ads on clicking **get link**

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/47a9da9347756edc47fd0bad6f6e651b5d24be33

**Comment by doio** [comment]
https://stfly.me/RY9Cw0

Recaptcha box not displaying

**Comment by okiehsch** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/16838044/94361933-11f23300-00b8-11eb-8a2b-895720cd3761.png)

What is your setup?

**Comment by doio** [comment]
> 
> 
> Works fine on my end.
> ![image](https://user-images.githubusercontent.com/16838044/94361933-11f23300-00b8-11eb-8a2b-895720cd3761.png)
> 
> What is your setup?

Sorry. It could be a loading issue, now it's working fine.
