### ISSUE TITLE
porkjizz.com [NSFW] [ADS]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#3991]
### URL(s) where the issue occurs

`http://porkjizz.com`

### Describe the issue

[Ads]

### Versions

- Browser/version: [70.0.3538.77]
- uBlock Origin version: [1.17.0]

### Settings

- [Default]

**Comment by ZaphodBeebblebrox** [comment]
```
||imglnkc.com^$image,domain=porkjizz.com
porkjizz.com##div[id^="nativeAds_"]
```
@ryanbr

**Comment by okiehsch** [comment]
I think we should add a fix, the `nativeAds` stuff is caused by the inline-script which pushes quite a few requests.
````
porkjizz.com##+js(abort-on-property-read.js, _crkRandRotation)
||imglnkc.com^$image,domain=porkjizz.com
porkjizz.com##.happy-footer
porkjizz.com##.happy-sidebar
porkjizz.com##.happy-under-player
````
works on my end.

**Comment by gidgudmate** [comment]
Works for me with the exception of `.happy-under-player` I can only hide it with `.under-player-ad`. There is also an ad at the top when viewing a video `.happy-header-mobile`.

**Comment by okiehsch** [comment]
Ther should not be any ad at all, 
````
porkjizz.com##.happy-footer
porkjizz.com##.happy-sidebar
porkjizz.com##.happy-under-player
````
only hide empty placeholders.
`||imglnkc.com^$image,domain=porkjizz.com` blocks the ads, you may have to load the site bypassing the cache one time for that filter to take effect.

**Comment by gidgudmate** [comment]
Yeah the issue fixed itself after closing the site and re-opening it. Seems all good now.
