### ISSUE TITLE
KissAnime - RapidVideo popups

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#3992]
### URL(s) where the issue occurs

`http://kissanime.ru/Anime/Sword-Art-Online-Alicization/Episode-001?id=150832&s=rapidvideo`

### Describe the issue

Similar to #3764 (my 9anime issue), but this time it's with RapidVideo (and it doesn't happen on 9anime). Just click the play button and RapidVideo's logo comes up. I have also seen a "notification" asking to enable notifications, but since I have denied that notification, it hasn't come back.

### Screenshot(s)

Like the 9anime issue, hopefully it's clear enough.

### Versions

- Browser/version: 64.0b5
- uBlock Origin version: 1.17.2

### Settings

Exact same filter settings as the 9anime issue (minus the custom one for 9anime specifically).

### Notes

Here are some URL's that I have seen in the logger that could be related to the issue, but blocking them doesn't seem to stop the popups:

> glotchat.click
> psoapeez.click
> nompakru.click

**Comment by ZaphodBeebblebrox** [comment]
okiehsch, since rapidvideo keeps adding new popups, would adding `*$third-party,popup,domain=rapidvideo.com` make sense. It gives an intermediate fix whenever they add a new popup, which seems like it could be useful to me.

**Comment by okiehsch** [comment]
That filter works on your end if you remove the fix I added?

**Comment by ZaphodBeebblebrox** [comment]
Nope, I'm just stupid.

**Comment by uBlock-user** [comment]
Why not add `rapidvideo.com##+js(window.open-defuser.js)` I don't get any and I have that too.

**Comment by okiehsch** [comment]
> Why not add `rapidvideo.com##+js(window.open-defuser.js)`

Seems sensible.
