### ISSUE TITLE
dfiles.eu

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#3993]
### Describe the issue

anty-adblock

> We are sorry! But currently no free download slots for adblock users are available.

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by okiehsch** [comment]
Do you have an example link?
`https://dfiles.eu/files/9jtjc1bno`
![image](https://user-images.githubusercontent.com/16838044/47829636-bcf0f980-dd88-11e8-8a9b-67a6e50d0218.png)

works fine on my end.

**Comment by KonoromiHimaries** [comment]
![2018-11-01-depositfiles](https://user-images.githubusercontent.com/5884000/47829938-1279d600-dd8a-11e8-8d0f-e4e9968cf586.png)

**Comment by okiehsch** [comment]
I can't reproduce, I can see that the site checks if some elements are hidden.
Does
`@@||dfiles.eu^$generichide`
work for you?

**Comment by KonoromiHimaries** [comment]
@okiehsch works, but i have cookie alert
![2018-11-01-depositfiles](https://user-images.githubusercontent.com/5884000/47830376-ed866280-dd8b-11e8-9b2a-fea91727eed0.png)

**Comment by okiehsch** [comment]
`dfiles.eu##.cookie_popup`

I will fix the anti-adblock message, you will have to add the cookie filter to your list.

**Comment by uBlock-user** [comment]
> what has been fixed in this case

https://github.com/uBlockOrigin/uAssets/commit/836ad2fdf1f7bdd2862430e0ea82407ed869e31e

**Comment by kulfoon** [comment]
That's not what I meant, I was aware of the commit, I meant what was fixed by the commit, coz neither I nor @okiehsch could reproduce the issue. But it doesn't matter anymore anyway, as I can't reproduce on Firefox (tried several times), but can on Opera after several times, which is a bit weird anyway, sometimes can reproduce on Opera, sometimes not, so maybe that's why okiehsch couldn't reproduce too.

**Comment by okiehsch** [comment]
I still can't reproduce the block, but if I go to `https://dfiles.eu/files/9jtjc1bno` without the fix I have to wait 99 seconds before I can start the download, with the fix I have to wait 5 seconds, that's why I added it.
