### ISSUE TITLE
timesnownews.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#3995]
### URL(s) where the issue occurs

`https://www.timesnownews.com/`

### Describe the issue

`Live tv` doesn't start here

### Screenshot(s)

![screenshot 50](https://user-images.githubusercontent.com/20338483/47857837-adb58e80-de10-11e8-95cc-fdebf0973cdf.png)

### Versions

- Browser/version: google chrome 70 stable
- uBlock Origin version: 1.17.0

### Settings

-  uBO's default settings + decentraleyes+ ubo extra+ other unrelated addons

**Comment by ZaphodBeebblebrox** [comment]
it does not play anything for me even with uBlock disabled.

**Comment by ghajini** [comment]
Check in right upper corner `LIVE TV` , with ublock disabled live tv starts automatically

**Comment by okiehsch** [comment]
Does
`@@||pubads.g.doubleclick.net/gampad/*timesnow_livetv$xmlhttprequest,domain=timesnownews.com``
work for your?

**Comment by terrorist96** [comment]
> Does
> `@@||pubads.g.doubleclick.net/gampad/*timesnow_livetv$xmlhttprequest,domain=timesnownews.com`
> work for your?

Doesn't work for me.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/47876850-a2676080-de1a-11e8-99e5-a89363e6a4df.png)

The video works fine if I disable `uBO`.

**Comment by terrorist96** [comment]
Might be a geolocation issue then.

**Comment by ghajini** [comment]
that filter doesn't work
incognito mode website works fine
![screenshot 51](https://user-images.githubusercontent.com/20338483/47877182-4ebc3d80-de41-11e8-972a-5bad9a001e0e.png)

**Comment by okiehsch** [comment]
That filter works for me in "normal mode"
![image](https://user-images.githubusercontent.com/16838044/47877342-f6267980-de1b-11e8-9a58-54e5acd7f092.png)

**Comment by okiehsch** [comment]
Have you tried with a default setup?

**Comment by ghajini** [comment]
yeah with ubo extra + ublock origin only plus nonrelevant webroot filtering extension(which isn't blocking anything only providing site safety ratings)

**Comment by okiehsch** [comment]
Can you post your log of the site and filter it for all blocked requests.
Type -- in the "filter log entries" box.

**Comment by okiehsch** [comment]
Here is mine
![image](https://user-images.githubusercontent.com/16838044/47879161-35ef6000-de20-11e8-9f59-c4c85d6f4960.png)

The only difference between them is that I don't get any `facebook/instream` requests, you can try to allow them.

**Comment by ghajini** [comment]
restarted computer , now doesn't get that `facebook/instream`
but now with your filter i do get video ad(preroll)
![screenshot 55](https://user-images.githubusercontent.com/20338483/47880223-a9a56300-de48-11e8-9191-b997a6618ae0.png)
exception filter to be removed

**Comment by ghajini** [comment]
@jspenguin2017 
can you help here

**Comment by ghajini** [comment]
these 2 actually work
||p.jwpcdn.com/*/vast.js$domain=timesnownews.com,important
||pubads.g.doubleclick.net/gampad/*timesnow_livetv$important,xmlhttprequest,domain=timesnownews.com

**Comment by ghajini** [comment]
Antiadblock (a couple refreshes may be required to reproduce)

Google chrome/opera/firefox

**URL=**

`https://www.timesnownews.com/live-tv`
`https://hindi.timesnownews.com/live-tv/mirror-now`
`https://www.timesnownews.com/live-tv/et-now`
`https://hindi.timesnownews.com/live-tv/zoom-tv`


all same URL's from parent company but provided all URL's to miss not antiadblock at subsites

**screenshot=**

![image](https://user-images.githubusercontent.com/20338483/103095148-9b68c100-4625-11eb-8b01-15fe7e618f1f.png)

**Comment by mapx-** [comment]
test

```
timesnownews.com##+js(nostif, Adblock)
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=timesnownews.com
```

**Comment by ghajini** [comment]
Doesn't work **mapx-**

**Comment by mapx-** [comment]
test

```
@@||timesnownews.com^$ghide
timesnownews.com##.adunit
timesnownews.com##+js(nostif, Adblock)
```

**Comment by ghajini** [comment]
1.
it works on above mentioned sites

2.
would you address same antiadblocks at their sister sites

**Live TV** section
`https://www.zoomtventertainment.com`
`https://www.timesnowhindi.com`
`https://www.timesnowmarathi.com/live-tv`

**Comment by mapx-** [comment]
test all those pages, sometimes I get errors on running the video

```
@@*$ghide,domain=timesnownews.com|timesnowhindi.com|timesnowmarathi.com|zoomtventertainment.com
timesnownews.com,timesnowhindi.com,timesnowmarathi.com,zoomtventertainment.com##.adunit
timesnownews.com,timesnowhindi.com,timesnowmarathi.com,zoomtventertainment.com##+js(nostif, Adblock)
```

**Comment by ghajini** [comment]
That error `this video file can't be played....` is due to blockade of `doubleclick.net`

Update the existing rule in unbreak list to
@@||pubads.g.doubleclick.net/ssai/$xmlhttprequest,domain=timesnownews.com|

**Comment by ghajini** [comment]
That error `this video file can't be played....` is due to blockade of `doubleclick.net`

Update the existing rule in unbreak list to

`@@||pubads.g.doubleclick.net/ssai/$xmlhttprequest,domain=timesnownews.com|zoomtventertainment.com|timesnowhindi.com|timesnowmarathi.com`

**Comment by garry-ut99** [comment]
`timesnowhindi.com`

Ad placeholders all over the site, caused by `ghide` from "uBlock Filters", on both main page and subpages:
[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219353235-b3a9f08f-bf61-4060-a25e-95c7e5f12ff1.png), I get no AA with `ghide` off but there is AA still in the source code, so if not removing `ghide`, then maybe: `thizissam.in##.ad-container, .adsbygoogle`

<hr>

`timesnowmarathi.com` anti-adblock: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219357349-39dd02a7-4fb6-4064-a6c9-b05453cf8843.png)
