### ISSUE TITLE
(anti-adblock)mediafire

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#3996]
### URL(s) where the issue occurs
`https://www.mediafire.com/file/o1h1e3c3bpud3ml/YoWAV7.70_com.wa_Yousef_Al_Basha.apk `

### Describe the issue
Mediafire showing to disable ad blocker
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [62]
- uBlock Origin version: [1.17.2
![screenshot_2018-11-01-21-45-56-454_org mozilla firefox](https://user-images.githubusercontent.com/14991260/47865138-5654f580-ddf3-11e8-89c6-bcda1ec6d210.png)
]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by Thunder33345** [comment]
add `www.mediafire.com###abnotify` into my filter should do the trick

**Comment by ZaphodBeebblebrox** [comment]
Already fixed in uBlock Annoyances.
