### ISSUE TITLE
[Anti-adblock] oload.fun

### ISSUE THREAD

**Issue by Brolyns** [uBlockOrigin/uAssets#3997]
[NSFW] `https://oload.fun/f/7i-2RFBGvtI` The publisher of this file doesnt allow adblock, please disable and [reload] !

**Comment by okiehsch** [comment]
@Brolyns what is your setup?

**Comment by kulfoon** [comment]
Can't reproduce on Firefox & Opera.

**Comment by uBlock-user** [comment]
Already patched in uBO Filters.

**Comment by Brolyns** [comment]
Hellow! thanks for help, i updated the Adblock Warning Removal List this solved my problem on uBlock.
