### ISSUE TITLE
Unable to update ublock filters list

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#4]
### Describe the issue

Trying to update the ublock filters results in a bad md5 checksum error.

### Screenshot(s)
![error](https://cloud.githubusercontent.com/assets/16838044/14367388/208c58e4-fd18-11e5-930a-aaedec4714a2.PNG)

### Your settings

- Browser/version: 49.0.2623.112
- uBlock Origin version: 1.6.8

**Comment by gorhill** [comment]
Sorry, I see that I forgot to update `checksums.txt` after I changed something in `filters.txt`.
