### ISSUE TITLE
TinyPic popunder

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#40]
### URL(s) where the issue occurs

`http://tinypic.com/`
### Describe the issue

Popunder on TinyPic is not being blocked. Click on the ["tinypic" icon](https://cloud.githubusercontent.com/assets/16030872/14979731/7ab0079c-1124-11e6-8efc-eb07adafcb4c.png) to reproduce.
### Versions
- Browser/version: Chrome 50
- uBlock Origin version: 1.7.4
### Notes

https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/blob/master/uBlock-Filters-Plus.txt#L628

Maybe this is better: `/fp.eng?id=$popunder`

Would target the whole advertising software they use instead of only the exchangeable domain name (`||belwrite.com^$popup`).

**Comment by uBlock-user** [comment]
Try - `tinypic.com#script:inject(pornhub-popup-defuser.js)`

Delete `tinypic.com` cookies if it doesn't work on first instance.

**Comment by okiehsch** [comment]
fixed with https://github.com/uBlockOrigin/uAssets/commit/432f679637892cda786d60d4b220a51b2ea42efb
