### ISSUE TITLE
citipricerewind.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4002]
### URL(s) where the issue occurs

`https://www.citipricerewind.com/`

### Describe the issue

Can't upload file.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/47892309-64276c80-de2d-11e8-8a36-2a2bccd1cffe.png)

### Notes
Need to be logged in. `@@.com/track?$xmlhttprequest` fixes it. See log above for specific link.

**Comment by okiehsch** [comment]
`@@||citipricerewind.com/track?action=upload$xmlhttprequest,first-party`
is this good enough?

**Comment by terrorist96** [comment]
Should be, yeah.

**Comment by terrorist96** [comment]
@okiehsch actually `https://www.citipricerewind.com/track?action=delete` should be added too. Not sure if it should be any more broad.
