### ISSUE TITLE
http://awsubs.co/

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#4005]
### URL(s) where the issue occurs

`http://awsubs.co/`

### Describe the issue

[After page loaded, there is a shadow, i can't click anything on the site]

### Screenshot(s)

https://imgur.com/BguMZL4

### Versions

- Browser/version: Firefox Quantum 63.0.1 32-bit
- uBlock Origin version: v1.17.2

### Settings

- [https://gist.github.com/exodius48/eb07d7c79cafe4770665b18d66f049b6]

### Notes

[The shadow & i can click anything on the site after i deactivate UBO]

**Comment by kulfoon** [comment]
Can't reproduce on uBO default & Firefox & Opera, you have too many filter lists selected, disable them one by one until you find the one which is the culprit.

**Comment by okiehsch** [comment]
I can't reproduce, you can try to add 
`awsubs.co###floatcenter`
to your filter list.

**Comment by kulfoon** [comment]
It seems none of them, as I just've loaded your settings `https://gist.github.com/exodius48/eb07d7c79cafe4770665b18d66f049b6` to uBO and added `awsubs.co###floatcenter` to My Filters pane and then have visited `http://awsubs.co/` and there is no shadow, so I don't know why do still you have the shadow.
