### ISSUE TITLE
Episerver Find Page - site is not usable

### ISSUE THREAD

**Issue by SenuraMalaka** [uBlockOrigin/uAssets#4006]
### URL(s) where the issue occurs

`http://episerverWebsite/login/Find/#overview`

### Describe the issue

The Episerver find page is not working in the latest browsers.

Steps to reproduce

    - Go to Epi Edit Mode
    - Click on 'Find' tab
    - Under the 'Find' tab, click on Overview.

What happened?
The page is not loading. it says 'The Find user interface is currently not available, please try again later.'

### Screenshot(s)

[Page screenshot](https://camo.githubusercontent.com/c4d3ce79ccd77ae0f3b5a8c588be0e014de74f9b/68747470733a2f2f776562636f6d7061742e636f6d2f75706c6f6164732f323031382f31302f64373264616265352d333663332d343365662d393463662d6162363165643265366536362d7468756d622e6a7067)

[Console output](https://user-images.githubusercontent.com/19330762/47631623-c7cf4280-db6c-11e8-9b06-6758066d4433.PNG)

### Versions

- Browser/version: Firefox developer edition ( 64.0b4 (64-bit) ), Safari 12, Firefox Nightly(65.0a1 (2018-10-28)) and the Firefox stable edition (63.0).
- uBlock Origin version: 1.17.2 (Firefox) ,  1.11.3.1 (Safari)

### Settings

<img width="473" alt="screen shot 2018-11-02 at 11 31 56 pm" src="https://user-images.githubusercontent.com/19330762/47932825-bb464380-def8-11e8-87c2-5a6a2bb2e1c0.png">

### Notes

It was happened because of the add-on uBlock Origin 1.17.2. I have also tested in Safari 12, with the uBlock Origin 1.11.3.1. And it also happens of that add-on. When disabled, it just loads perfectly.

This website I have tested is a local site. In order to debug, Need to have a sample site built in Episerver (https://www.episerver.com/) .

**Comment by SenuraMalaka** [comment]
More info : https://github.com/webcompat/web-bugs/issues/20534

**Comment by okiehsch** [comment]
Can you post your logger output?

- Open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger)

- Load `http://episerverWebsite/login/Find/#overview` and reproduce your issue

- Type dom `--` in the "filter log entries" box

**Comment by SenuraMalaka** [comment]
@okiehsch, Here's the log captured on Firefox [65.0a1](https://www.mozilla.org/en-US/firefox/65.0a1/releasenotes/) (2018-11-01) (64-bit). With uBlock Origin 1.17.2. 

<img width="1325" alt="Logger output" src="https://user-images.githubusercontent.com/19330762/47948908-b8326e00-df5f-11e8-9b3d-5f45ecde64c5.png">

**Comment by okiehsch** [comment]
Adding 
`||episerver.net^$third-party,badfilter`
to you filter list fixes the issue?

**Comment by okiehsch** [comment]
Add
````
||episerver.net^$third-party,badfilter
||episerver.net/*/epi-util/$third-party,script
````
to your filter list, you can remove the other two entries, this should fix your issue.

**Comment by SenuraMalaka** [comment]
@okiehsch , Yes :D. After adding the above entries, now it works. Site loads as it should. Thanks. 
If it is possible, please fix this in the next release without having to add specific set of rules. Otherwise, If someone uses Episerver with uBlock Origin, they will get the same issue.

**Comment by jspenguin2017** [comment]
@okiehsch Are you sure that's right? Episerver seems to be an advertiser backend.

**Comment by okiehsch** [comment]
I looked for the `EasyPrivacy` entry and the reason that filter was added.

https://github.com/easylist/easylist/blame/f1bde81d962694acb24468139b8679b63306b932/easyprivacy/easyprivacy_trackingservers.txt#L724

![episer](https://user-images.githubusercontent.com/16838044/47957960-fca22600-dfc0-11e8-85dc-4cb570e26138.PNG)

`||episerver.net/*/epi-util/$third-party,script` fixes that issue and also blocks the tracking  script on pther sites.
I admit I was not sure about gow to fix the site breakage of the OP and I am open to better suggestions.

**Comment by jspenguin2017** [comment]
For my filter lists, my policy is that I don't fix advertiser backend, period. If people need to manage their ads, just whitelist that page. For uAssets, it's up to you and gorhill, but here's another one if you are interested: `https://www.facebook.com/adsmanager/creation`

> Need to have a sample site built in Episerver 

Isn't gorhill's policy that uAssets doesn't handle demos / artificial issues?

**Comment by okiehsch** [comment]
> I don't fix advertiser backend ....   doesn't handle demos / artificial issues

Makes sense, I was only looking at the `fromnorway.com` domain and looked at `https://publicwww.com/websites/%22episerver%22`, where all episerver requests could be blocked by
`||episerver.net/*/epi-util/$third-party,script`.

**Comment by gorhill** [comment]
How about:

    ||episervet.net^$third-party,badfilter
    ||episervet.net^$third-party,domain=~episerver.com

At least until fixed in EasyPrivacy?

But I kind of agree with @jspenguin2017, not keen on adding such filters when the fix should go in EasyPrivacy and the workaround is merely to disable uBO -- acceptable given it's an advertiser site.
