### ISSUE TITLE
planetagibi.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4007]
### URL(s) where the issue occurs

`https://www.planetagibi.com.br/`

### Describe the issue

A script blocks the context menu.

### Versions

- Browser/version: 63.0.1 (64-bit)
- uBlock Origin version: uBlock Origin 1.17.2

### Settings

+uBlock filters – Annoyances​​​​​

**Comment by adranger** [comment]
@okiehsch why has this been removed?

**Comment by mapx-** [comment]
I get (even with brazilian ip)

![image](https://user-images.githubusercontent.com/10303732/94486889-5a0c7500-01e0-11eb-8a68-5cd6b067641a.png)

**Comment by mapx-** [comment]
nvm I 'll add the filters again
