### ISSUE TITLE
Chicago Reader newspaper blocked

### ISSUE THREAD

**Issue by practik** [uBlockOrigin/uAssets#401]
### URL(s) where the issue occurs

`chicagoreader.com`

### Describe the issue

Every page on this newspaper's site is blocked by a full-page overlay that says: "It looks like you're using an adblocker. The support of our advertisers helps us" etc.

### Versions

- Browser/version: Firefox 53.0.2
- uBlock Origin version: 1.12.1

### Settings

- Defaults, plus advanced features enabled

### Notes

Static filter `chicagoreader.com##script:contains(advertisers)` fixes it for me.

**Comment by okiehsch** [comment]
`chicagoreader.com##script:inject(setTimeout-defuser.js, displayNoneImportant)`
works with Chrome and Firefox.

**Comment by practik** [comment]
Dang that was fast :-)
