### ISSUE TITLE
driverfix.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4014]
### URL(s) where the issue occurs

`http://www.driverfix.com/land/hgd/index.php?tracking=HW`

### Describe the issue

Blank page.

### Notes

`@@.php?tracking=`

**Comment by smed79** [comment]
`driverfix.com` should be added to the badware list.

**Comment by ZaphodBeebblebrox** [comment]
Could you elaborate on why?

**Comment by smed79** [comment]
Go to the home of the site.
Download the `.exe` file.
Scan the fale at virustotal.com

**Comment by terrorist96** [comment]
https://www.virustotal.com/#/url/ac1fe407af0592489e7ef1ff2a62e381f05be08311e010fc4a5736b94b08d070/detection

**Comment by smed79** [comment]
[![https://www.virustotal.com/#/file/c636adc855252908d62dac190925c24768e6bf9763f55823d63ded1b3442a7fb/detection](https://user-images.githubusercontent.com/1873139/47959833-bb5b4780-dfbb-11e8-9f06-5f4701dffa06.png)](https://www.virustotal.com/#/file/c636adc855252908d62dac190925c24768e6bf9763f55823d63ded1b3442a7fb/detection)

**Comment by ZaphodBeebblebrox** [comment]
@gorhill, thoughts on this?

**Comment by okiehsch** [comment]
https://www.virustotal.com/#/file/c636adc855252908d62dac190925c24768e6bf9763f55823d63ded1b3442a7fb/detection

I would say that adding it to the badware list, is the correct call.

**Comment by mapx-** [comment]
https://www.scumware.org/report/104.27.174.25.html

**Comment by terrorist96** [comment]
I'm wondering why all three of our submissions to virus total produced different results. They should all be the same .exe.

**Comment by okiehsch** [comment]
Your submission 
````
https://www.virustotal.com/#/url/ac1fe407af0592489e7ef1ff2a62e381f05be08311e010fc4a5736b94b08d070/detection
````
scans the url, not a specific file.

The other two check the same file, but on different dates, which means different virus definitions and different results.
