### ISSUE TITLE
Use ||example.com^$[...] instead of ||example.com$[...]

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#402]
**badware.txt**
||com.com$document

**filters.txt**
||adbutler-meson.com$important,script,domain=uploaded.net
||0mme.com$script,domain=comicbook.com
||mn0e.com$script,domain=wwg.com
||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz$inline-script

**unbreak.txt**
@@||cdn-static.liverail.com$domain=9to5mac.com
@@||imasdk.googleapis.com$domain=twitch.tv
@@||naiadsystems.com$object,domain=streamate.com
@@||assets.adobedtm.com$script,domain=skygo.sky.de
@@||assets.adobedtm.com$script,domain=rogers.com
@@||upload.facebook.com$first-party
@@||assets.adobedtm.com$script,domain=redbull.tv
@@||ticketmaster.122.2o7.net$image,domain=ticketweb.co.uk

**Comment by gorhill** [comment]
You're right, fixed as suggested.
