### ISSUE TITLE
iptvliste.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4025]
### URL(s) where the issue occurs
`http://iptvliste.com/`

### Describe the issue
Anti-Adblock [blocking],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional list DEU
- uBlock filters – Annoyances​​​​​
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47962547-ba0f3680-e01e-11e8-8a8d-c4c7ec8172a9.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by Thunder33345** [comment]
seems to only popup after few reloads of the page
`##.swal2-in.swal2-fade.swal2-container`
seems to do the trick
