### ISSUE TITLE
truyenaudiocv.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4029]
### URL(s) where the issue occurs
`https://truyenaudiocv.com/`

### Describe the issue
Anti-Adblock [blocking],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional list VIE
- uBlock filters – Annoyances​​​​​
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47963134-d06dc000-e027-11e8-811e-8064e991bd89.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by stephenhawk8054** [comment]
Another anti-adblock.

URL: `https://truyenaudiocv.net/dau-pha-thuong-khung/listen?i=0`

![image](https://user-images.githubusercontent.com/66517106/141713547-e62dfcda-58df-4619-b25e-b6f29b46fe3e.png)

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`truyenaudiocv.net##+js(aopw, remove_adblock_html)`
