### ISSUE TITLE
How to Block Popup's and Redirects

### ISSUE THREAD

**Issue by JordanGS** [uBlockOrigin/uAssets#403]
**Environment**

Windows 10
Firefox 53.0.2

**Question**

Trying to figure out how to block redirects and popups such as the ones caused on video streaming sites when you press proceed to video or the play button.

Most links in movie4k.to or tvmuse.com in the comments link to openload or thevideo, etc. They all have popups which i would love to block without affecting the video playback capabilities.

**Example**

[thevideo.me](http://thevideo.me/j26sxse96dof)

with you block, it will prevent all the ads i can see, there is a button **Proceed to Video**, if you click that. It will redirect to the video like it should but it also opens and quickly closes a popup. I would like to know how to prevent such popups. Not only for this site but any site in general.

Could you please shed some light on how i could go about this? If i have posted in the wrong section, please let me know where i should direct my question/support request before you close the topic. Thank you.

**Comment by okiehsch** [comment]
Does
````
thevideo.me##script:inject(abort-on-property-write.js, Fingerprint2)
thevideo.me##script:inject(abort-on-property-read.js, inpage_pop_functions)
````
work for you?

**Comment by JordanGS** [comment]
@okiehsch they work beautifully. Thank you. Can i trouble you to help me understand how you determined that these two scripts would resolve the issue? I want to block popups on as many streaming video sites as i can.

**Comment by okiehsch** [comment]
Sorry, I don't think I am able to give you a tutorial: "How to prevent popups in general"
You have to deal with them on case by case basis.

**Comment by SMed79** [comment]
Fix the popups for all adblockers (vidup.me and thevideo.me)
```
@@||vidup.me/adsense.js?$script,domain=vidup.me
@@||thevideo.me/mba/cds.js?ads_pop$script,domain=thevideo.me
```

optional filters:
```
||vidup.me^$subdocument,~third-party
||thevideo.me^$subdocument,~third-party
```
urls
```
http://vidup.me/embed-072utllx5qp6.html
https://thevideo.me/embed-j26sxse96dof.html
```

**Comment by uBlock-user** [comment]
or

`thevideo.me##script:inject(abort-on-property-read.js, open)`
