### ISSUE TITLE
clk.icu

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4030]
### URL(s) where the issue occurs

`https://clk.icu/HMoDP`

### Describe the issue

Anti-adblock.

### Versions

- Browser/version: 63.0.1 (64-bit)
- uBlock Origin version: uBlock Origin 1.17.2

**Comment by kulfoon** [comment]
I confirm, also what is interesting - there seems to be two Anti-Adblocks:

You visit the webpage and you get:

![ss1](https://user-images.githubusercontent.com/43844449/47964543-f1401080-e03b-11e8-941d-28dbe6a827c3.png)

After several seconds it changes into bab:

![ss2](https://user-images.githubusercontent.com/43844449/47964549-0026c300-e03c-11e8-8e17-839a6c449469.png)

**Comment by okiehsch** [comment]
I get popups using Chromium
Example link: `clk.ink/HMoDP` after solving the captcha and continuing to the countdown site.
