### ISSUE TITLE
owari.io [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4032]
### URL(s) where the issue occurs
`http://owari.io/`

### Describe the issue
double Anti-Adblock [blocking + annoying],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- uBlock filters – Annoyances​​​​​
- Adguard Base Filters
- Adguard Spyware Filters

fixes only the first Anti-Adblock

### Screenshot(s)

1 the first Anti-Adblock (the blocking one)

![ss1](https://user-images.githubusercontent.com/43844449/47965255-184f1000-e045-11e8-9d2e-5dfc42ae0649.png)

2 the second Anti-Adblock (the annoying one)

![ss2](https://user-images.githubusercontent.com/43844449/47965273-4f252600-e045-11e8-83e1-4ee2a6b341a0.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by ZaphodBeebblebrox** [comment]
The second one is there even with uBlock disabled.
