### ISSUE TITLE
yorokobu.es [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4035]
### URL(s) where the issue occurs
`https://www.yorokobu.es/`

### Describe the issue
Anti-Adblock [annoyance],

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional list EST
- uBlock filters – Annoyances​​​​​
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/43844449/47965487-44b85b80-e048-11e8-86f4-5db406305225.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by ZaphodBeebblebrox** [comment]
Fixed in Easylist Spanish.
