### ISSUE TITLE
Ublock-annoyances hiding regular content on youtube

### ISSUE THREAD

**Issue by tendererdegree** [uBlockOrigin/uAssets#4038]
### URL(s) where the issue occurs

www.youtube.com

### Describe the issue

UBlock-Annoyances hiding regular videos recommended on youtube. Some videos are shown, but >1/2 of the recommended video feed is hidden.

### Versions

- Browser/version: Firefox Quantum x64 63.01
- uBlock Origin version: 1.17.2

### Settings

- Default settings and Ublock-annoyances list added

**Comment by okiehsch** [comment]
> UBlock-Annoyances hiding regular videos recommended 

That is the reason the filter was added, to hide recommended videos, so if you want to see them add
`youtube.com#@##dismissable:has-text(Recommended for you)`
to your filter list.

**Comment by tendererdegree** [comment]
> 
> 
> > UBlock-Annoyances hiding regular videos recommended
> 
> That is the reason the filter was added, to hide recommended videos, so if you want to see them add
> `youtube.com#@##dismissable:has-text(Recommended for you)`
> to your filter list.

Thanks for letting me know.

Strange, I do not see this as being an annoyance for many people at all.
There is a bug with the filter anyways, as its not hiding the parent divider there's a big gap where the padding for the element starts.

youtube.com##ytd-compact-video-renderer:has(#dismissable:has-text(Recommended for you))

The above would fix this, but imo most people would not find this annoying.

**Comment by okiehsch** [comment]
> Strange, I do not see this as being an annoyance for many people at all.

I agree with you, that is the reason `uBO-annoyances` is not part of the default setup.
I have not added that filter, but I am not easily annoyed and the question if something is annoying is highly subjective in contrast to the question is this an ad.

**Comment by mapx-** [comment]
removed
