### ISSUE TITLE
[Anti-adblock] ncaa.com, q2.be, vtm.be, ruutu.fi, medialaancdn.be, medialaan.be

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#4039]
### URL(s) where the issue occurs (6 total)

`https://www.ncaa.com/march-madness-live/watch`

`https://www.q2.be/beverly-hills-cop-ii-maandag-2035`

`https://vtm.be/the-voice-kids/een-moeilijke-keuze-voor-k3-aja-amber-en-maelle-zingen-en-dansen-de-pannen-van-het`

`https://www.ruutu.fi/video/3290209`

```
For medialaancdn.be and medialaan.be (according to my notes): 

https://nieuws.vtm.be/buitenland/antwerps-kartel-samen-wordt-voorgesteld
https://www.hln.be/nieuws/binnenland/niels-destadsbader-krijgt-het-aan-de-stok-met-bodyguard-neymar~a9afe004/
```

### Describe the issue

I'm trying to clean up my background script, and this is causing a lot of trouble. 
https://github.com/jspenguin2017/uBlockProtector/issues/344

According to my notes, these domains are affected: 
```
ncaa.com, pga.com (already fixed), q2.be, vtm.be, ruutu.fi, medialaancdn.be, medialaan.be
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/47971934-06289e00-e054-11e8-836c-1ac3698e3673.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.17.0

### Settings

All default.

**Comment by jspenguin2017** [comment]
`medialaancdn.be` and `medialaan.be` are related to `vtm.be`. 

Details in confidential issue here: https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/269
Let me know if you want to have access.

**Comment by bogachenko** [comment]
@mapx- again antiadb + fingerprint + ad

**Comment by bogachenko** [comment]
fingerprint, no?
`<script src="//www.mml-web.ncaa.com/lib_internal/device-fingerprint.bundle.js?pkgVer=1.0.0" async></script>`
