### ISSUE TITLE
random CSS selectors

### ISSUE THREAD

**Issue by Phlipout** [uBlockOrigin/uAssets#404]
What is a strategy for blocking random CSS selectors occupying the same page relative position?

Alternatively/additionally will uBlock Origin support XPath?

**Comment by SMed79** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters

This help?

**Comment by gorhill** [comment]
Submit real cases please, otherwise there is nothing to solve, aka invalid issues.
