### ISSUE TITLE
Ads on economictimes.indiatimes.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4056]
### URL(s) where the issue occurs

1. `https://economictimes.indiatimes.com`

2. `https://economictimes.indiatimes.com/news/international/business/eu-plan-to-tax-facebook-amazon-heads-for-showdown-in-brussels/articleshow/66520374.cms`

3. `https://economictimes.indiatimes.com/tech/software/how-microsoft-is-leading-quantum-computer-race-to-unlock-mysteries-around-us/articleshow/66486082.cms`

4. `https://economictimes.indiatimes.com/magazines/panache/a-look-into-kings-glory-5-iconic-crowns-on-public-display/the-crowning-glory/slideshow/66519416.cms`

### Describe the issue

Ads served served by ColombiaOnline content monetization network are getting through.

Link 1: Scroll down a bit to find `From Around the Web` section which is tagged as "Sponsored by COLOMBIA" and has a bunch of ad links.

Link 2: The above mentioned section appears at the end of article.

Link 3: At the end of article there is `Recommended For You` section which is tagged as "Sponsored by COLOMBIA". However, not all links in here seem to be ads. Ad links have an identifier in the format `Ad: [Advertiser's name]`. Rest are links to other articles on the site.

Link 4: Somewhere in the middle (I got it below 3rd image and also at the end), an ad link appears having the same identifier as above `Ad: [Advertiser's name]`. A small ColombiaOnline icon is also visible within the bottom right of an ad. The page has endless scroll with next stories and ads are visible in all such stories. Current pattern indicates an ad being served after every 3 images.

### Versions

- Browser/version: Firefox 63.0.1
- uBlock Origin version: 1.17.2

### Settings

Default

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/247

**Comment by mapx-** [comment]
test these filters
```
economictimes.indiatimes.com###aroundweb
economictimes.indiatimes.com##:xpath(//span[contains(text(),"More from ")]/../preceding-sibling::div)
economictimes.indiatimes.com##:xpath(//span[contains(text(),"Around")])
economictimes.indiatimes.com##div h2:has(span:matches-css-before(content:/Sponsored/))
economictimes.indiatimes.com##:xpath(//p[contains(text(),"Ad:")]/../..)
||economictimes.indiatimes.com/*/columbia_logo.png$image
```

**Comment by in4u** [comment]
@mapx- Works for me!

**Comment by in4u** [comment]
The article pages (e.g. links 2 and 3 in [original post](https://github.com/uBlockOrigin/uAssets/issues/4056#issue-377789534)) are broken on mobile. Only partial content is visible and `READ MORE` button does not reveal rest of the content. Disabling uBO/Easylist resolves the problem and button works as expected.

Example URL: `https://m.economictimes.com/magazines/panache/tricked-by-tech-hackers-force-a-tesla-model-s-to-enter-the-wrong-lane/articleshow/68775757.cms`

**Comment by mapx-** [comment]
Test this filter
`@@||jsm.etimg.com/js_etsub/*.cms$script,domain=m.economictimes.com`

**Comment by in4u** [comment]
It works. But an app banner now appears on top of the page which turns into a bigger sticky banner on scrolling down.

**Comment by mapx-** [comment]
upload an image with that banner on page

**Comment by in4u** [comment]
Refer to the screenshot below for top banner in LHS and bigger sticky banner on scroll in RHS:

![SS](https://user-images.githubusercontent.com/43062185/55742605-a9d80900-5a4d-11e9-98a1-43334b6a5af2.png)

**Comment by mapx-** [comment]
see if helps 
```
m.economictimes.com##.open-in-app
m.economictimes.com##[href*="/ad"]
m.economictimes.com##.budgetButton
```

**Comment by in4u** [comment]
They do remove certain elements but not the ones I was talking about. The element zapper suggested a few options which nail the rogue elements. Any one of the following 2 combinations removes both the banners:

1. `m.economictimes.com###appBanner,#stickyBanner`

2. `||img.etimg.com/photo/67587082.cms` and `||img.etimg.com/photo/67885009.cms`

You are the best judge as to which of these are more appropriate as filters.

**Comment by mapx-** [comment]
Unfortunately I can not reproduce on desktop + responsive mode / or various user agent, so I'll add exception filter and your first filter

**Comment by in4u** [comment]
Okay, thanks! But it's strange, I can reproduce on desktop without even entering responsive mode just by setting [UASwitcher](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/) to Android Phone / Firefox 66 in private browsing mode.

**Comment by mapx-** [comment]
yep, you're right. I tried other 2 user agent switchers, only this 1 is working.

**Comment by in4u** [comment]
The site has implemented anti-adblocking now. There's an adbock detection message on every article page, except the homepage. The pages are accessible by activating Firefox's reader mode or disabling javascript though.

**Comment by mapx-** [comment]
I cannot reproduce the issue. 
desktop ? android ? specific page ? maybe only for specific country ?

**Comment by in4u** [comment]
Hmmm... strange. Maybe it was fixed in Easylist or some other list. Or maybe the site is testing out a subscription promo. Even I cannot reproduce now but earlier there was anti-adblocking which led to [this](https://economictimes.indiatimes.com/blocked.cms) page.

Please ignore for now. I'll report back if it happens again.

**Comment by llacb47** [comment]
I can reproduce anti-adblock on `https://economictimes.indiatimes.com/news/international/business/eu-plan-to-tax-facebook-amazon-heads-for-showdown-in-brussels/articleshow/66520374.cms`.

It's done with this code 
![image](https://user-images.githubusercontent.com/16567977/68824191-fcbd1300-0663-11ea-9355-ab6e465b71e6.png)
from the script `https://js.etimg.com/js_common/v-906,minify-1.cms`

Add 
```
indiatimes.com#@#.adBanner
indiatimes.com##.hidden.uc.afb
```

**Comment by okiehsch** [comment]
Weird, I can't reproduce even with a US IP, that script `https://js.etimg.com/js_common/v-906,minify-1.cms`  does not get called on my end.

**Comment by okiehsch** [comment]
`indiatimes.com##+js(std, objSubPromo)`
seems to be unlikely to break anything. I will add it.

**Comment by in4u** [comment]
There's this `###pollBudgetWidget` on top of the homepage which seems to be an interactive brand promotional ad for Uber under the guise of polling widget.

**Comment by 0x6900** [comment]
Another ad leftovers., wild card no working "||tpc.googlesyndication.com/simgad/*" or "||googlesyndication.com/simgad/*"

**Comment by stephenhawk8054** [comment]
> Another ad leftovers., wild card no working "||tpc.googlesyndication.com/simgad/_" or "||googlesyndication.com/simgad/_"

Can you give example URL with screenshots?
