### ISSUE TITLE
novagente.pt [Anti-Adblock / Breakage]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4057]
### URL(s) where the issue occurs
`https://www.novagente.pt/`

### Describe the issue
Occurs only in Firefox (can't reproduce on Opera) - the page won't load - showing Anti-Adblock related shadow overlay instead, until "X" button clicked manually (screenshoot 1).

enabling these:
- Adblock Warning Removal List 
- Fanboy’s Enhanced Tracking List
- Nano Defender + it's lists
- regional list 2 x SPA 
- uBlock filters – Annoyances​​​​​
- Adguard Base Filters
- Adguard Spyware Filters

doesn't fix the issue

### 1 uBO default enabled (Firefox) / uBO default enabled + 2 x SPA regional list (Frefox)
![ss1](https://user-images.githubusercontent.com/43844449/48064932-a3591300-e1c9-11e8-9454-96fda2569f9d.png)

### 2 uBO default enabled (Opera)
![ss3](https://user-images.githubusercontent.com/43844449/48064937-a3f1a980-e1c9-11e8-93ea-e140b203661a.png)

### 3 uBO disabled (Firefox/Opera) / uBO default enabled + 2 x SPA regional list (Opera)
![ss2](https://user-images.githubusercontent.com/43844449/48064934-a3591300-e1c9-11e8-8dc1-dbae0ec4b79b.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0.1 64bit (can't reproduce on Opera 56 64bit)
- uBlock Origin version: 1.17.2

### Settings

Default / Default + 2 x SPA

**Comment by krystian3w** [comment]
In Firefox no show image, because Firefox support "`content url`" for only pseudoelements (before, after)

```html
<div id="overlay" style="display: block;">
    <div id="message">
    <a href="/faqs" target="_blank">    
       <img class="image">
    </a>    
       <div id="close"><img src="https://www.worldimpalanet.com/sites/useful/images/cruz.png"></div>
    </div>
</div>
```

```css
image {
    content: url("https://www.worldimpalanet.com/sites/useful/images/adblock_alert_NG.jpg");
}
```

**Comment by adranger** [comment]
@mapx-  clipboard manipulation when you copy links: `https://www.novagente.pt/maria-andrea-gaspar-mais-uma-perda-na-casa-do-artista-partida-de-cantora-lirica-sucede-cinco-mortes`
