### ISSUE TITLE
Anti-adblock message on tvtropes.org is back

### ISSUE THREAD

**Issue by veikk0** [uBlockOrigin/uAssets#4067]
### URL(s) where the issue occurs

`https://tvtropes.org/`

### Describe the issue

An anti-adblock nag banner appears on every page, starting with the second page viewed on the site.

### Screenshot(s)

![tvtropes](https://user-images.githubusercontent.com/7808922/48088123-cf948400-e209-11e8-8ab9-66b73a688f4d.png)

### Versions

- Browser/version: Firefox 63.0
- uBlock Origin version: 1.17.2

### Settings

Enabled the Annoyances filter list. So every built-in uBlock filter list apart from Experimental was enabled.

### Notes

Tested to occur with a fresh, default Firefox profile where the only installed extension was uBlock Origin.

**Comment by veikk0** [comment]
The message is back; should I create a new issue report or could this one be used if/when the issue re-appears in the future?

**Comment by mapx-** [comment]
I cannot reproduce the issue anymore

**Comment by veikk0** [comment]
Strange, it seems that something about my uMatrix setup could somehow be interfering with the uBlock Origin filter. Completely turning off uMatrix for TVtropes.org fixes the issue. I tried to reproduce the issue on a new browser profile to see what exactly the problem is but was unable to do so. The only messages in the browser console don't seem to indicate anything unusual to me:
```
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. TropaholicsAnonymous:1:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://i.clean.gg/1a. (Reason: CORS request did not succeed).[Learn More]
Loading failed for the <script> with source “https://global.proper.io/tvtropes.min.js”. TropaholicsAnonymous:1:1
Loading failed for the <script> with source “https://static.tvtropes.org/design/js/ads.js?_=1544515752448”. TropaholicsAnonymous:1:1 
```

**Comment by mapx-** [comment]
You have to whitelist the last 2 scripts

> Loading failed for the <script> with source “https://global.proper.io/tvtropes.min.js”. TropaholicsAnonymous:1:1
Loading failed for the <script> with source “https://static.tvtropes.org/design/js/ads.js?_=1544515752448”. TropaholicsAnonymous:1:1

**Comment by veikk0** [comment]
Whitelisting global.proper.io did the trick. Looks like that one was also blocking the static.tvtropes.org one.
