### ISSUE TITLE
gamezhero.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4068]
URL(s) where the issue occurs

`http://www.gamezhero.com/games/seaboom`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 69 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by KiLL4FuNK** [comment]
PLAY

Anti-Adblock

**Comment by okiehsch** [comment]
The game loads fine and I don't get any anti-adblock message.

**Comment by mapx-** [comment]
If I wait loading ends and then click on screen I'll get a popup page with all the games and the original screen stays black, no game on it (...same if disable uBo)

If I don't wait the loading and click quickly the play button I get the anti adb message, but as I Said above ...no way to play the game even disabling uBo

**Comment by okiehsch** [comment]
`http://www.gamezhero.com/games/seaboom`
The first play button I see is a promo button.

**Comment by mapx-** [comment]
right, that's promo ... but can you play the game ?

**Comment by okiehsch** [comment]
> If I wait loading ends and then click on screen I'll get a popup page with all the games and the original screen stays black, no game on it (...same if disable uBo)

After the loading ends.
![image](https://user-images.githubusercontent.com/16838044/48861065-ecf94e80-edc2-11e8-8705-68ba8b3c387a.png)

**Comment by mapx-** [comment]
well, is working in chrome not in FF (where if I click the black window I get again the anti adb msg)

**Comment by okiehsch** [comment]
I can't test with Firefox, because it requires flash.
