### ISSUE TITLE
anilinkz.io needs a uBO-only :style( rule that I can't get right

### ISSUE THREAD

**Issue by Okamoi** [uBlockOrigin/uAssets#407]
Hi,

### URL(s) where the issue occurs

`http://anilinkz.io/death-note-episode-36`

### Describe the issue

Go to the page with uBO and, with JavaScript enabled, notice that there's an invisible block area that receives the first click. When you click it some JS is run and a network request is made.

I tried blocking it with `anilinkz.io##body > a:style(display:block!important;)` but it looks like I'm not used enough to the syntax. Removing the :style part hides it successfully.

Some time ago I came here for the same site due to the presence of the Fingerprint2 library and it being triggered on first click coupled with a network request.

Note: The request goes to `anilinkz.io/count.php?pid=xxxxxxx` and there's another identical one that is made on page load without user interaction, so I don't see the need for the invisible blocker in terms of tracking.

### Versions

- Browser/version: Firefox 53
- uBlock Origin version: 1.12.4

### Settings

- I only have `anilinkz.io###waifu` as a custom filter, otherwise I enabled advanced mode and do not load third party resources at all, no exception required for anilinkz.io.

**Comment by okiehsch** [comment]
Does `anilinkz.io##script:inject(abort-on-property-write.js, _$_1923)` work for you?

**Comment by Okamoi** [comment]
Yep! Looks like they removed or obfuscated Fingerprint2 after uBlock blocked it some days ago. I guess they will try and do the same here.

I'm not sure whether `anilinkz.io##script:inject(abort-on-property-write.js, Fingerprint2)` still has a purpose in the "uBlock filters" list now. Is there a way to disable only one filter from an official filter list to test out ?

**Comment by okiehsch** [comment]
> Is there a way to disable only one filter

`anilinkz.io#@#script:inject(abort-on-property-write.js, Fingerprint2)`

Some sites rotate their popup-scripts, so I will not delete this filter yet.
