### ISSUE TITLE
Bitcointalk.org banner ads

### ISSUE THREAD

**Issue by sunk818** [uBlockOrigin/uAssets#4074]
### URL(s) where the issue occurs

`https://bitcointalk.org/index.php?topic=2388064.11380`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

`https://bitcointalk.org/index.php?topic=2388064.11380`

Banner ads between posts are placed. Unable to block because there seems to be random bits of text for div, class, or a href that is inconsistent.

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: Version 1.17.0
Updated September 28, 2018

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
see if works
```
bitcointalk.org##[class$="-ad"]
bitcointalk.org##[class$="-banner"]
bitcointalk.org##span[class]
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by Raidware** [comment]
![image](https://github.com/user-attachments/assets/16d2e653-9b60-42b0-902c-05608f03f93b)

![image](https://github.com/user-attachments/assets/6c440e0a-dc5a-47db-8b29-1bb2132f5dbb)

again bet and casino ads @mapx-

**Comment by mapx-** [comment]
provide link of the page with such ads

test:
`bitcointalk.org##.signature:has(a[href]:not([href*="bitcointalk.org"]))`

**Comment by Raidware** [comment]
> provide link of the page with such ads
> 
> test: `bitcointalk.org##.signature:has(a[href]:not([href*="bitcointalk.org"]))`

https://bitcointalk.org/index.php?topic=5469940.0

this filter blocked ads
