### ISSUE TITLE
[request] downloadhub.link 

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#4075]
### URL(s) where the issue occurs

`[https://downloadhub.link]`

### Describe the issue
when click on  some thing , automatically  open new tab with a pic which is from that  site only .. 

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 63
- uBlock Origin version:  v1.17.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
popups again

**Comment by ghajini** [comment]
popups, need update

**Comment by mapx-** [comment]
test (see if breaks something or still popups there)
`downloadhub.link##+js(abort-on-property-read.js, decodeURIComponent)`

**Comment by ghajini** [comment]
not yet ...popups disappear

**Comment by mapx-** [comment]
You mean still getting popups ?

**Comment by ghajini** [comment]
Popups disappear, I don't know about site breakage, I can download movies

**Comment by ghajini** [comment]
`downloadhub.host`

Please remove obsolete /unneeded scriptlet filters
