### ISSUE TITLE
Chefkoch.de

### ISSUE THREAD

**Issue by penticrack** [uBlockOrigin/uAssets#4076]
### URL(s) where the issue occurs

`https://www.chefkoch.de/`

### Describe the issue

Anti Ad Block issue of Website. You can Block its Layers but its no longer Scrollable.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 63.0.1
- uBlock Origin version: v1.17.2

### Settings

Added these to Filters:
www.chefkoch.de##div[id^="sp_message_id"]
www.chefkoch.de##div[class^="sp_veil"]

### Notes

With above Filters im able to remove this Anti Adblocking Layer, but then the Scrollbars missing. Maybe im to dumb to set the Filter correct. If You Google this sp_message_id and sp_veil it seem to be an well knows anti adblock script.

**Comment by penticrack** [comment]
Sorry ..already closed. So its not an issue, i c . Plz delete this then.

**Comment by okiehsch** [comment]
I added a filter to fix your issue, which I could reproduce.
That commit closed this issue via the commit message.

**Comment by penticrack** [comment]
> 
> 
> I added a filter to fix your issue, which I could reproduce.
> That commit closed this issue via the commit message. [6bbc350](https://github.com/uBlockOrigin/uAssets/commit/6bbc350093b83ae62bbec0cc99da1ba07d829bd1)
> Update your uBO-filter list and you should be able to use chefkoch without issue.

Very THX!!!!

**Comment by matthiashaedrich** [comment]
> I added a filter to fix your issue, which I could reproduce.
> That commit closed this issue via the commit message. [6bbc350](https://github.com/uBlockOrigin/uAssets/commit/6bbc350093b83ae62bbec0cc99da1ba07d829bd1)
> Update your uBO-filter list and you should be able to use chefkoch without issue.

This did not fix the issue for me. The anti-adblock is still popping up. When I use the filters penticrack uses, the overlay disappears but the site is still unscrollable.

**Comment by penticrack** [comment]
insert the complete filter frome here -> https://raw.githubusercontent.com/uBlockOrigin/uAssets/6bbc350093b83ae62bbec0cc99da1ba07d829bd1/filters/filters.txt
should help... helped me

**Comment by matthiashaedrich** [comment]
> insert the complete filter frome here -> https://raw.githubusercontent.com/uBlockOrigin/uAssets/6bbc350093b83ae62bbec0cc99da1ba07d829bd1/filters/filters.txt
> should help... helped me
> 
> Edit:
> What i wrote didn´t work ->
> 
> > [www.chefkoch.de##div[id^="sp_message_id"]](http://www.chefkoch.de##div%5Bid%5E=%22sp_message_id%22%5D)
> > [www.chefkoch.de##div[class^="sp_veil"]](http://www.chefkoch.de##div%5Bclass%5E=%22sp_veil%22%5D)
> 
> and resulting in your behavior.
> 
> Emptied the whole User Based Filters (at Settings of Addon) and pasted the huuuge text from above file into it. That worked by me with firefox, don´t know how to do this with Chrome. Maybe your Filterlist is been overwritten?

Works, thanks!

**Comment by okiehsch** [comment]
> Emptied the whole User Based Filters (at Settings of Addon) and pasted the huuuge text from above file into it.

Well, if that works it tells me that your filter list is not up to date.
You have to [[manually update](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) the `uBO-filters` list, or wait for it to auto-update.
Now even if this does not work on your end for, whatever reason, I would suggest that you remove the "huuuge" text and just add the one relevant filter 
`chefkoch.de##+js(abort-on-property-read.js, _sp_._networkListenerData)`

**Comment by penticrack** [comment]
Again , thx for the hint. Deleted my filterlist and updated filters. Last Update was 3 Days ago and first i have to purge all caches , otherwise the "update now" was not clickable.
