### ISSUE TITLE
2speed.net

### ISSUE THREAD

**Issue by m1m2m3mr** [uBlockOrigin/uAssets#4078]
### URL(s) where the issue occurs
`https://2speed.net/file/773B7EBD6169`

### Describe the issue
Not an issue but is it possible to speedup countdown on 2speed.net like what happen on other sites?

### Screenshot(s)
![image](https://user-images.githubusercontent.com/20967118/48126061-892e3c00-e280-11e8-8747-a42f88eb4982.png)

### Versions
- Browser/version: Chrome Version 69.0.3497.100 (Officiel version) (64-bit)
- uBlock Origin version: 1.17.0

### Settings
- Keeping default settings

**Comment by okiehsch** [comment]
Does 
`2speed.net##+js(nano-setTimeout-booster.js, , 1400)`
work for you?
