### ISSUE TITLE
Fanart.tv

### ISSUE THREAD

**Issue by purevertigo** [uBlockOrigin/uAssets#4083]
`https://fanart.tv`

any search hits an adblock redirects to this page

`https://fanart.tv/membership-account/membership-levels/`

**Comment by uBlock-user** [comment]
@mapx, does `$badfilter` work for you on `@@/wp-content/plugins/google-analytics-for-wordpress/$first-party,script` ?

**Comment by mapx-** [comment]
No. The original filter in easyprivacy is:
`@@/wp-content/plugins/google-analytics-for-wordpress/*$script,stylesheet,~third-party`

so, it works:
`@@/wp-content/plugins/google-analytics-for-wordpress/*$first-party,script,badfilter`

**Comment by uBlock-user** [comment]
> so, it works:
@@/wp-content/plugins/google-analytics-for-wordpress/*$first-party,script,badfilter

Not sure I understand, `@@/wp-content/plugins/google-analytics-for-wordpress/$first-party,script,badfilter` doesn't work for me.

**Comment by mapx-** [comment]
In your filter is missing `*`

**Comment by mapx-** [comment]
As I know, the complex filters are splitted for the various options: `script`, `stylesheet `etc

**Comment by uBlock-user** [comment]
Yeah I got that, but where did `$stylesheet` disappear ? It's present in the original EasyPrivacy filter.

**Comment by mapx-** [comment]
I guess uBo creates 2 filters from that one
```
@@/wp-content/plugins/google-analytics-for-wordpress/$first-party,script
@@/wp-content/plugins/google-analytics-for-wordpress/$first-party,stylesheet
```

but removing `*` (maybe considering it superfluous - but having these weird consequences)

**Comment by uBlock-user** [comment]
Hmmm, `@@/wp-content/plugins/google-analytics-for-wordpress/*$script,stylesheet,~third-party,badfilter` also works.

**Comment by gorhill** [comment]
It should be possible to bad-filter network filters shown in the logger. If it's not working then there is a bug.

On my side I get `@@/wp-content/plugins/google-analytics-for-wordpress/$first-party,script` in the logger, and bad-filtering it does not work: it's a bug. The actual issue is that uBO should log the filter with the asterisk at the end, otherwise the filter is outputted as a regex-based filter, which is not the case.

**Comment by uBlock-user** [comment]
> On my side I get @@/wp-content/plugins/google-analytics-for-wordpress/$first-party,script in the logger, and bad-filtering it does not work: it's a bug. 

Yes, that's what I'm facing too.

**Comment by gorhill** [comment]
I could not reproduce either when I worked on the logger issue.
