### ISSUE TITLE
DI.FM

### ISSUE THREAD

**Issue by kennethb22** [uBlockOrigin/uAssets#4085]
### URL(s) where the issue occurs

`https://www.di.fm/`

### Describe the issue

With uBlock origin and NanoDefender enabled, attempts to play a channel are re-directed to `https://www.di.fm/about-blockers`. I last accessed di.fm a couple of weeks ago, and had not had this issue up to then.

### Versions

- Browser/version: Chrome 70.0.3538.77
- uBlock Origin version: 1.17.0
- NanoDefender version: 15.0.0.71

### Settings

Added to filter lists:

Nano Defender Integration
Nano filters
Nano filters - Whitelist

**Comment by jspenguin2017** [comment]
`https://www.jazzradio.com/` might be related. `https://www.jazzradio.com/about-blockers`

**Comment by kennethb22** [comment]
Yes, jazzradio.com, classicalradio.com, di.fm, rockradio.com, and radiotunes.com are all the same company.

**Comment by uBlock-user** [comment]
Doesn't happen on my side. I select a channel from https://www.di.fm/channels and click on play button the channel thumbnail and it starts playing.

**Comment by kennethb22** [comment]
I verified that that I had the latest NanoDefender and lists, and I purged the list cache, but that didn't fix the problem. I unistalled NanoDefender, removed the nano defender lists from uBlock Origins' filter list, then re-installed NanoDefender, and added the NanoDefender lists back. That fixed the issue.

**Comment by okiehsch** [comment]
Why was this reopened? I still can't reprodce with `uBO` and a default setup.

**Comment by ZaphodBeebblebrox** [comment]
This is a NanoDefender issue, see NanoAdblocker/NanoFilters#218

**Comment by jspenguin2017** [comment]
My patch was 4 days old, which is more than enough time for Chrome to pull the update. 

I see that they are using FuckAdBlock, but there isn't a `generichide` rule, maybe only reproducible when logged in?

**Comment by ZaphodBeebblebrox** [comment]
I am currently testing it with NA+ND and an account, I'll let you know if anything happens in half an hour or so.
