### ISSUE TITLE
Quora

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4093]
### URL(s) where the issue occurs

`quora.com`
`https://www.quora.com/What-are-some-mind-blowing-technologies-that-exist-that-most-people-dont-know-about`

### Describe the issue

Unblocked ad(s)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/48293930-7158e280-e44f-11e8-9296-596ad6bb217d.png)

### Versions

- Browser/version: Chrome 70
- uBlock Origin version: 1.17.0

### Settings

Default.

### Notes

We should probably keep this open as it seems that they actively bypass. Have been seeing ads on this site consistently for several weeks now. (Same with Facebook)

**Comment by uBlock-user** [comment]
q`uora.com##div[class] > div > div > div > div > div > div > div > div > div:has-text(sponsored)`

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by terrorist96** [comment]
> I can't reproduce.

I can reproduce on the home page (requires account).

> `quora.com##div[class] > div > div > div > div > div > div > div > div > div:has-text(sponsored)`

Works, but doesn't block ads labeled like `Promoted by DuckDuckGo`

**Comment by terrorist96** [comment]
Here's a log in you can try:

email: `test_quora@mt2015.com`
pw: `quora`

**Comment by uBlock-user** [comment]
The filter above is was tested as guest user only FYI, also I can't reproduce either.

try `quora.com##div[class] > div > div > div > div > div > div > div > div > div:has-text(/sponsored|promoted/)`

**Comment by terrorist96** [comment]
> The filter above was tested as guest user only FYI, also I can't reproduce either.
> 
> try `quora.com##div[class] > div > div > div > div > div > div > div > div > div:has-text(/sponsored|promoted/)`

This works. Should be added.

**Comment by okiehsch** [comment]
````
quora.com##:xpath(//div[not(@class="ui_qtext_para") and contains(text(), 'ad')]/parent::div/parent::div/parent::div[@id])
````
seems to work.

**Comment by terrorist96** [comment]
Yep, but leaves empty template outlines for where the ads would have been while the other one doesn't.

**Comment by okiehsch** [comment]
`quora.com##.u-inherit:has-text(sponsored)` 
 if you are offended by the empty template outlines.

**Comment by terrorist96** [comment]
That works.

**Comment by uBlock-user** [comment]
> This works. Should be added.

Won't get added unless it's reproducible, the filter posted here are for you to use yourself.

**Comment by krystian3w** [comment]
Catch on Opera 56:

![image](https://user-images.githubusercontent.com/35370833/48781049-81888180-ecdb-11e8-8d39-bda2bb84fc5c.png) | ![image](https://user-images.githubusercontent.com/35370833/48781145-b563a700-ecdb-11e8-9b32-abe1d1b1dff2.png)
--- | ---




I have 99% of the latest filters (purged and updated)

**Comment by terrorist96** [comment]
@mapx- I emailed you a zip of the website with unblocked sponsored ads.

**Comment by mapx-** [comment]
Test
`quora.com##:xpath(//p[contains(text(),"sponsored ")]/../../../..)`

**Comment by terrorist96** [comment]
That works, but the element that holds the ad is visible. It's good enough.
![image](https://user-images.githubusercontent.com/12802056/50182007-20ed6400-02dc-11e9-8826-b888facb998c.png)

**Comment by krystian3w** [comment]
uBO Extra can help?

**Comment by terrorist96** [comment]
@mapx- I'm seeing ads again.

**Comment by mapx-** [comment]
send me a new example test case

**Comment by mapx-** [comment]
test
`quora.com##:xpath(//span[(text()='d')]/../../../../..)`

**Comment by terrorist96** [comment]
That works. Thanks.
