### ISSUE TITLE
studiodunja.com

### ISSUE THREAD

**Issue by einstein95** [uBlockOrigin/uAssets#4097]
### URL(s) where the issue occurs

`http://studiodunja.com/`

### Describe the issue

Via obfuscated JS, this page loads `https://mixology.pw/?5cGKquote` which, depending on the User-Agent used, either gives a blank response, `3`, or JS code which sends the browser on a redirect chain to advertising websites.

### Screenshot(s)

n/a

### Versions

- Browser/version: Vivaldi 1.15.1147.64 (Stable channel) (64-bit); Basilisk 2018.09.27 (64-bit)
- uBlock Origin version: 1.17.0

### Settings

- None

### Notes

I have found that a User-Agent header of `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML`, and any additions to this value, gives a blank response. Any changes to this value gives the redirection JS. A blank User-Agent value also gives no response, as well as a User-Agent value containing `curl`.

**Comment by mapx-** [comment]
killing `mixology` crap
`studiodunja.com##+js(abort-on-property-read.js, encodeURIComponent)`

but..are you sure `studiodunja` has any sort of value ?

**Comment by einstein95** [comment]
I'm not sure it has any value, but `mixology` doesn't have any value either.
