### ISSUE TITLE
temp-mail.org Anti Adblock

### ISSUE THREAD

**Issue by Brolyns** [uBlockOrigin/uAssets#4098]
he prevents me from viewing my emails with anti adblock message

**Comment by mapx-** [comment]
I cannot reproduce the issue.
Could you test this filter:
`temp-mail.org##+js(set-constant.js, checkadBlock, noopFunc)`

**Comment by in4u** [comment]
I can reproduce this. Open site and copy the temporary email address generated. Send a test mail (I tried [this](https://anonymousemail.me)) to that address. Click refresh to check new emails, if the page does not automatically refresh. Click the unread mail in the inbox. It won't let you view that email unless ad-blocker is disabled.

**Comment by mapx-** [comment]
I asked if the filter above is working. @in4u  ?

**Comment by in4u** [comment]
@mapx- It works for me.
