### ISSUE TITLE
AnyClip

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4099]
### URL(s) where the issue occurs

`https://venturebeat.com/2017/08/05/red-hydrogen-smartphone-first-look-explains-the-3d-four-view-content-but-not-vr/`

### Describe the issue

Recommended video powered by AnyClip

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/48319446-0daff000-e5dc-11e8-932b-00aaa2456d6a.png)

**Comment by okiehsch** [comment]
`||player.anyclip.com/anyclip-widget/lre-widget/prod/*$script,domain=venturebeat.com`

**Comment by smed79** [comment]
@terrorist96 Blocked in the annoyance list https://github.com/easylist/easylist/blob/0d4c88049cac919d0fe04ce791f193f147771a17/fanboy-addon/fanboy_annoyance_thirdparty.txt#L22
