### ISSUE TITLE
Rule from uBlock filters – Experimental‎ blocks videos on cbsnews.com

### ISSUE THREAD

**Issue by F4z** [uBlockOrigin/uAssets#41]
Chrome 50.0.2661.94 m (64-bit)
uBlock Origin 1.7.2

This rule from uBlock filters – Experimental‎ <code>||tags.tiqcdn.com^</code> blocks video here - http://www.cbsnews.com/news/california-drought-blackhawk-homeowner-association-ordered-beautify-green-lawns/

**_When uBlock filters – Experimental‎ is enabled_**

![image](https://cloud.githubusercontent.com/assets/11742596/15094104/93f51ce6-149a-11e6-9184-103ae7d48ea9.png)

**_When uBlock filters – Experimental‎ is disabled_**

![image](https://cloud.githubusercontent.com/assets/11742596/15094107/a00391c0-149a-11e6-81f6-71c93ed436cf.png)

**Comment by F4z** [comment]
The same rule `||tags.tiqcdn.com^` blocks video here - http://www.trustedreviews.com/news/nvidia-geforce-gtx-1080-1070-pascal-specs-price-release-date

![image](https://cloud.githubusercontent.com/assets/11742596/15330971/61b4a716-1c5f-11e6-9394-9b38d00a7ecf.png)

**Comment by gorhill** [comment]
I removed `tags.tiqcdn.com`. I may look into a neutered script for this in the future.

**Comment by IDKwhattoputhere** [comment]
@gorhill 
In case there's the need for an example: `http://www.computerbild.de/`
