### ISSUE TITLE
Many links on this site don't work w uBO enabled

### ISSUE THREAD

**Issue by secret-agent-girl** [uBlockOrigin/uAssets#410]
### URL(s) where the issue occurs

`https://www.cpap.com/cpap-filters/philips-respironics.php#:::1:::`
(many of the pages on this site which list out products work - or rather, don't work - in the same fashion, for example: `https://www.cpap.com/cpap-machines/travel-sized-cpap-machine.php`, etc., etc.)
(Also, the navigation tabs at the top of the page don't load fully. There is a spinning double-arrow circle under "Featured ---" that never resolves. Example: `https://www.cpap.com/cpap-comfort-cleaning.php`)

### Describe the issue

When I click on a product link nothing happens. Or, if I disable UBlock Origin and refresh the page, the link works. If I enable uBO and refresh the page again, it doesn't work again. (I've also noticed that if I right click and select Open a New Tab with uBO enabled, it works, which is confusing.)

### Screenshot(s)

(let me know if you need any)

### Versions

- Browser/version: Firefox 53.0.2 32-bit
- uBlock Origin version: 1.12.4

### Settings

None

### Notes

As described above. Let me know if you need anything further

Thanks!

**Comment by gorhill** [comment]
@ryanbr fyi

**Comment by secret-agent-girl** [comment]
Does this mean it will be fixed in an upcoming update?

**Comment by gorhill** [comment]
The fix is in _uBlock filters_, for an update of that one list. [Here is how](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now) if you do not know how to do this.

**Comment by gorhill** [comment]
Sorry, I meant the fix is in _uBlock filters -- Unbreak_, not _uBlock filters_.

**Comment by secret-agent-girl** [comment]
Thank you.

The spinning "loading" symbol is still showing when top-level tabs are clicked, for example, on `https://www.cpap.com/cpap-supplies.php` scroll partway down the page to just below where it says "Featured CPAP Supplies"

**Comment by gorhill** [comment]
An EasyPrivacy filter is block requests from `bizsolutions.strands.com`, an exception filter will be needed ni EasyPrivacy:

    @@||bizsolutions.strands.com^$domain=cpap.com

Again, @ryanbr fyi.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/41374
