### ISSUE TITLE
Votre ordinateur est bloqué

### ISSUE THREAD

**Issue by YPetremann** [uBlockOrigin/uAssets#4103]
### URL(s) where the issue occurs

`https://d13ihrdvhrczld.cloudfront.net/index.html?number=01-70-98-07-42
https://d9w12whn6oel6.cloudfront.net/index.html?number=01-70-98-07-42
https://d1pnf154i2164e.cloudfront.net/index.html?number=01-70-98-07-42
https://d1pnf154i2164e.cloudfront.net/index.html?number=01-70-98-07-42
https://d2bjjtbqswwr0n.cloudfront.net/index.html?number=09-70-38-83-91&url=vidlox.me
https://d398z13wft7isq.cloudfront.net/index.html?number=09-70-38-83-91&url=424121.popcash.net
https://d3uq6qhssk5tbm.cloudfront.net/index.html?number=09-70-38-83-91&url=424121.popcash.net
https://d13ihrdvhrczld.cloudfront.net/assests/fr_ff_auth.html?number=01-70-98-07-42
https://d9w12whn6oel6.cloudfront.net/assests/fr_ff_auth.html?number=01-70-98-07-42
https://d1pnf154i2164e.cloudfront.net/assests/fr_ff_auth.html?number=01-70-98-07-42
https://d1pnf154i2164e.cloudfront.net/assests/fr_ff_auth.html?number=01-70-98-07-42
https://d2bjjtbqswwr0n.cloudfront.net/assests/fr_ff_auth.html?number=09-70-38-83-91&url=vidlox.me
https://d398z13wft7isq.cloudfront.net/assests/fr_ff_auth.html?number=09-70-38-83-91&url=424121.popcash.net
https://d3uq6qhssk5tbm.cloudfront.net/assests/fr_ff_auth.html?number=09-70-38-83-91&url=424121.popcash.net`

### Describe the issue

```
freehelp44.live
||*.cloudfront.net/assests/*.html?*number=$document
||*.cloudfront.net/*fr_ff_auth.html?*number=$document
||*.cloudfront.net/index.html?*number=$document
```

Persistant and annoying scam over cloudfront, should be added in default rules.
First rule disable auth window to appear and thus prevent firefox to be blocked.
Secondary rule block based on a recurent pattern
Third is browser and language specific.
Forth rule is for a variation

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.17.2

**Comment by mapx-** [comment]
Provide the page address where you get the scam

**Comment by ZaphodBeebblebrox** [comment]
At this point, all of the cloudfront links appear to be down anyways
