### ISSUE TITLE
sueddeutsche.de Anti-Adblock is back

### ISSUE THREAD

**Issue by dkas** [uBlockOrigin/uAssets#4106]
### URL(s) where the issue occurs

`[https://www.sueddeutsche.de]`

### Describe the issue

[Anti-Adblock page (log in or disable Adblock) realized on one of the biggest quality newspapers in Germany]

### Screenshot(s)

[![grafik](https://user-images.githubusercontent.com/2921153/48442612-f36a4380-e78e-11e8-8979-aabeddb8319a.png)]

### Versions

- Browser/version: [Firefox 63.0.1]
- uBlock Origin version: [1.17.2]

### Settings

- [I tried incorporating nano defender (yes, I did the extra installation steps) to see if it can bypass the anti-adblock, but to no avail.]

### Notes

[Nothing of note here. I use a vanilla firefox, some site-specific tampermonkey scripts (not on sueddeutsche.de), and ublock origin with nano defender.]

**Comment by mapx-** [comment]
What if you test using **only** uBo ?

**Comment by okiehsch** [comment]
I can't reproduce with Firefox, I can with Chrome.

**Comment by Hrxn** [comment]
Back again, it seems...

### URL(s) where the issue occurs
`https://www.sueddeutsche.de/politik/staatstrojaner-seehofer-ueberwachung-1.4564648`

### Describe the issue

AAB

### Versions

- Browser/version: Chrome 76.0.3809.100 (665002) - Latest Stable official build, 64-bit
- uBlock Origin version: 1.21.6

### Settings

- All uBO default filter settings
 \+ uBlock Filters - Annoyances
 \+ EasyList DEU
 \+ my own small list: `https://raw.githubusercontent.com/Hrxn/assets/master/filters/hrxn.txt`
   - (But domain does not apply)

### Notes

(Other issue for that site  is #174)

PS: Is it somehow possible to enable the re-opening of issues for people reporting, like this here?

**Comment by okiehsch** [comment]
I can't reproduce, I tried a german IP.
![image](https://user-images.githubusercontent.com/16838044/63138011-fbcf0380-bfd8-11e9-82e6-3db3fcb3425d.png)

If I disable `uBO-filters` I can reproduce.
![image](https://user-images.githubusercontent.com/16838044/63138044-173a0e80-bfd9-11e9-8cf3-8858c2766e42.png)

> PS: Is it somehow possible to enable the re-opening of issues for people reporting, like this here?

No, if somebody with write access closes an issue, for example via a commit message only users with write access can reopen.

**Comment by Hrxn** [comment]
@okiehsch 

Just re-tested, AAB is gone for me at the moment, can see the site normally.
I don't see a commit referenced here, but that does not mean it did not happen..

(There are some *"Anzeige: Gutscheine, Vergleichsportal"* sections at the bottom of the page, but I guess it's expected, because it's all the same domain here as I can see..)

> No, if somebody with write access closes an issue, for example via a commit message, only users with write access can reopen.

Yeah, but would be easier if an issue reporter could reopen. I assume this not possible right now, because of GitHub limitations with regard to access control/privilege settings etc..

**Comment by okiehsch** [comment]
> I assume this not possible right now, because of GitHub limitations

That is correct and I agree that it would be better if the OP could reopen closed issues.
