### ISSUE TITLE
uvnc.com detects adblocker

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#411]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

http://uvnc.com/downloads.html

### Describe the issue

A few seconds after the page loads, it's covered with a "Please disable your ad blocker!" message that you can't dismiss for 10 seconds.

### Versions

- Browser/version: Firefox 53.0.2
- uBlock Origin version: 1.12.4

### Settings

- 100% default

### Notes

When the page first loads, it's entirely covered by a fixed position div that says "please enable JavaScript". Inline JavaScript immediately hides this, then sets an event listener when the page loads to check for adblockers, and if they're found, to restore the div with a "please disable your ad blocker" message.

This anti-adblock is particularly devious, though. The ID of the fixed position div is randomized on each page load (something like "q3d4"). The element it uses to test the ad blocker is randomized as well; I've seen "strong", "i", and "font". The "please disable your ad blocker" message is displayed as a PNG with a data: URI to prevent searching for it. The list of ad strings it tries is also slightly different on each page load.

The following looks like the key to taking this out:
```
h.addEventListener?f.addEventListener("load",g,!1):f.attachEvent("onload",g)
```
Nuking that line won't affect hiding of the initial "please enable JavaScript" but will entirely prevent the anti-adblock from running. It looks like a variant of our indiatimes.com.js script:inject resource could do this easily.

**Comment by mapx-** [comment]
add
`@@||uvnc.com^$generichide`

**Comment by gorhill** [comment]
Standard filter takes care of this as suggested by @mapx-, report to EasyList maintainers.

**Comment by mapx-** [comment]
reported months ago ...
https://forums.lanik.us/viewtopic.php?p=106336#p106336
