### ISSUE TITLE
 EasyList and EasyPrivacy won't update

### ISSUE THREAD

**Issue by allanf181** [uBlockOrigin/uAssets#4110]
### URL(s) where the issue occurs

``

### Describe the issue

EasyList and EasyPrivacy won't update.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/14101716/48451230-9ff8f500-e790-11e8-9a60-6c053a4bbcf3.png)

### Versions

- Browser/version: Firefox 63.0.1 64-bits
- uBlock Origin version: v1.17.2

### Settings

-

**Comment by gwarser** [comment]
Private browsing mode? "Firefox will never remember history"? Disabled IndexedDB?

**Comment by ZaphodBeebblebrox** [comment]
Wrong place. You are either looking for [r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin) for support, or [uBlockOrigin/uBlock-issues](https://github.com/ublockOrigin/uBlock-issues) to report a bug.
