### ISSUE TITLE
Ublock filters breaks facebook.com

### ISSUE THREAD

**Issue by maddave27** [uBlockOrigin/uAssets#4113]
### URL(s) where the issue occurs

`www.facebook.com`

### Describe the issue

When the page is loading facebook's publications, publications appears and then disappears leaving only a line for each publications that I believed was removed by the filter.
I disabled all filters and reactivated them one by one to find the culprit : Ublock filters

![filters](https://user-images.githubusercontent.com/45032218/48473530-ec781b00-e7f8-11e8-9222-dae1c100b865.PNG)

### Screenshot(s)

![issue](https://user-images.githubusercontent.com/45032218/48473437-be92d680-e7f8-11e8-896b-a5045cb228b0.PNG)

### Versions

- Browser/version: latest Google Chrome 70.0.3538.102 (Build officiel) (32 bits)
- uBlock Origin version: [1.17.0]

### Settings

Defaults settings, no custom filter.

### Notes

Resetting the settings to defaults did not help.
Clear browser cache, closing and reopening it -> NOK
Updating all filters -> NOK
Only workaround at the moment is to untick the ublock filters (as you can see in the screenshot)

**Comment by mapx-** [comment]
Enabled again ublock filters, go into uBo's logger, refresh FB page.
Post here what filters are triggered.
You could also disable those cosmetic filters one by one to find out which is the wrong one.

To disable such filter just copy it from the logger and whitelist it:

`example.com###filter` becomes => `example.com#@##filter`

**Comment by mapx-** [comment]
After the test above could you test this filter (keeping ublock filters enabled)
`facebook.com,facebookcorewwwi.onion#@#div.userContentWrapper:if-not(span>div a[role="link"]:matches-css(display: none))`

**Comment by quaqo** [comment]
> After the test above could you test this filter (keeping ublock filters enabled)
> `facebook.com,facebookcorewwwi.onion#@#div.userContentWrapper:if-not(span>div a[role="link"]:matches-css(display: none))`

I confirm this works.

**Comment by mapx-** [comment]
ok, filter removed
https://github.com/uBlockOrigin/uAssets/commit/2ea49c0a39c17aa2486b1e555b60cc9be5813ef6

**Comment by maddave27** [comment]
I confirm that the filter you type works.

**Comment by filbo** [comment]
I was 100% certain that filter was going to be bad.

But I feel like I should stop butting in because people don't seem to want to listen to me.
