### ISSUE TITLE
Google Analytics callback not being called

### ISSUE THREAD

**Issue by niklabh** [uBlockOrigin/uAssets#4114]
### URL(s) where the issue occurs

`https://www.cars45.com/`

### Describe the issue

According to google analytics calling ga with a function as the first argument will call that callback with tracker.
https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference

ga(function(tracker) {
  console.log(tracker); // Logs `undefined`.
});

uBlock is replacing ga with its own version `uAssets/filters/resources.txt#373` but callback is not called in its version.

### Versions

- Browser/version: [Chrome Version 70.0.3538.102 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock origin 1.17.0]

### Notes

Please add callback behaviour to mocked ga as well.

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
What specifically is broken on `https://www.cars45.com/` that would be fixed with honoring the callback?

**Comment by niklabh** [comment]
Confirm Booking not working as it waits for the callback to submit form.

**Comment by gorhill** [comment]
> If it is called with a callback it is expected to be called with tracker

This is not that simple. If the neutered script starts to call a callback, it could very well lead to more breakage -- this is not something I can change lightly without evaluating how this affects sites overall. It's why I wanted to find out specifically about this one here, but your answer was to vague, I was never able to figure out the breakage.

**Comment by niklabh** [comment]
The confirm booking button on cars45.com try to get google analytics clientId before submitting the form.

```
button.onclick = function () {
  window.ga(function (tracker) {
    formData.clientId = tracker.get('clientId')
    
    booking.create(formData)
  })
}

```

button was not working due to ga callback not being called.

**Comment by mapx-** [comment]
> Now the issue is patched at cars45

closing, the PR will still stay opened
