### ISSUE TITLE
Cosmetic filtering

### ISSUE THREAD

**Issue by ejtipi** [uBlockOrigin/uAssets#4118]
There is a forum script called Invision Community Suite (formerly ICS or IPB). There is a function to fetch all images from external sources and display it directly from script server (to avoid https errors).

`A[target="_blank"] > IMG`

Above filter is quite rigorous and causes the generated images is not be displayed.

**Comment by mapx-** [comment]
I guess it's an easylist filter, you should report here:
https://github.com/easylist/easylist/issues

You didn't provide page address, steps to reproduce the issue.
