### ISSUE TITLE
yts.ag

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#412]
Hi,

**Versions** : uBlock Origin 1.12.4 / Chromium 58.0.3029.110

**Settings** : default settings

**URL(s) where the issue occurs**

`https://yts.ag/movie/assault-in-paradise-1977`

**Describe the issue** : popunder / redirection

**Screenshot**

- http://i.imgur.com/dI35j8J.png
- http://i.imgur.com/HnJ6pZA.png

**Suggested filters**

```
||104.198.61.40^$popup
yts.ag##script:inject(nowebrtc.js)
```

**EL forum** : https://forums.lanik.us/viewtopic.php?p=118296#p118296

**Comment by okiehsch** [comment]
Thanks, but already fixed https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L1109

**Comment by SMed79** [comment]
Sorry  :flushed:

![http://i.imgur.com/0pbJkBe.png](http://i.imgur.com/0pbJkBe.png)
