### ISSUE TITLE
www.shrink-service.it anti adblock

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#413]
### URL(s) where the issue occurs
http://www.shrink-service.it/s/8k1AovdtlwX9ATrix84M

### Describe the issue
![i9](https://cloud.githubusercontent.com/assets/27068733/26236825/e1fe08ea-3c61-11e7-9fc9-3f04651cad4f.jpg)

### Notes
I try with `www.shrink-service.it##script:inject(bab-defuser.js)` and `www.shrink-service.it##script:inject(overlay-buster.js)` but don't work

**Comment by mapx-** [comment]
add
`@@||shrink-service.it^$generichide`
