### ISSUE TITLE
Unblocked Malware link?

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#4137]
### URL(s) where the issue occurs

`governiamo.com/1338-norges-strste-byer.php` -> redicrets to -> `http://best-datings-girl.com/?u=g4kkd0x&o=5rwbfvn&x=1`

### Describe the issue

Was searching in google for norwegian biggest cities and almost the top search result was this url. The site was very hard to exit out of and lots of porn pop-ups.

### Versions

- Browser/version: Firefox 63.0.1 64bit 
- uBlock Origin version: 1.17.2

### Settings

uBO's default settings + fanboy lists + norwegian filter list

**Comment by mapx-** [comment]
The entire site seems to be a scam one. 
However I get no redirects. 
The page has a lot of nonsense phrases and full of links to other scam pages.

We could block the site in the `uBlock filters – Badware risks` list:
`||governiamo.com^$document`

**Comment by Schanzation** [comment]
Thank you!
