### ISSUE TITLE
bq.si

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#414]
Hi,

**Versions** : 

uBlock Origin 1.12.4 / Chromium 58.0.3029.110

**Settings** : 

default settings

**URL(s) where the issue occurs**

```
http://youtube.bq.si/
http://dailymotion.bq.si/
```

**Describe the issue** : 

popunder

**Suggested filters**

`||bq.si/banner/$popunder`

**EL forum** : 

https://forums.lanik.us/viewtopic.php?f=62&t=36817

**Comment by mapx-** [comment]
using the filter above:
- go to http://youtube.bq.si/
- click "click here..."
- the popunder is closed, youtube is running
- stay in the same tab, type again http://youtube.bq.si/ in the address bar, "click here..", the filter does not work anymore.
- it works only in a new opened tab

**Comment by gorhill** [comment]
> it works only in a new opened tab

But that's true even without the `popunder` filter.

**Comment by mapx-** [comment]
Without the filter I get the banner page and in a new tab the youtube.com page (...the popunder trick)

**Comment by gorhill** [comment]
I mean I get exactly your repro steps above even without the `popunder` filter, that's the way the site is designed. It opens a new tab named "_newtab" the first visit (a new tab is created), and then if you paste again `http://youtube.bq.si/` in the new tab launched by the previous tab, it again tries to open "_newtab", but then this one already exists, it's the _current_ one.

It seems using `||bq.si/banner/$popunder` _and_ `bq.si##script:inject(window.name-defuser)` is what works.

**Comment by mapx-** [comment]
yeah, thanks, now it's working fine.
