### ISSUE TITLE
[Anti-AdBlock] Adblock Detection isn't removed on DI.FM

### ISSUE THREAD

**Issue by matmat07** [uBlockOrigin/uAssets#4140]
### URL(s) where the issue occurs

https://www.di.fm/

### Describe the issue

If I try to start a song, I'm redirected to a "please disable your ad bloquer for this website" message.

### Screenshot(s)

No need for screenshots

### Versions

- Browser/version: Firefox 63.0.1
- uBlock Origin version: 1.17.2

### Settings

Adblock Warning Removal List is checked

### Notes

I tried using adding nanoAdBlock on Firefox too, but that didn't help either. I saw there is another thread relating to this website, but it seems his issues were related to nano, and I wasn't using it when I met the problem the first time

**Comment by okiehsch** [comment]
I still can't reproduce, just like in the other thread.

**Comment by matmat07** [comment]
Even if you try listening to a song until the end?

**Comment by okiehsch** [comment]
Yes, the nextone starts immediately after it without issue on my end.
Note that I don't have an account, so maybe the results are different in that case.

**Comment by ghajini** [comment]
@okiehsch 
`bugmenot.com/view/di.fm`

**Comment by okiehsch** [comment]
Well I tried with an account and I can still not reproduce any redirection with a default setup.

@ghajini can you reproduce ?

**Comment by ghajini** [comment]
Nope

**Comment by jonlandrum** [comment]
I am having this issue also, and was about to open a new ticket until I saw this thread. Please consider reopening this issue.

**Comment by mapx-** [comment]
I cannot reproduce the issue, however try
`@@||di.fm^$generichide`

**Comment by jonlandrum** [comment]
I will try that, thank you

**Comment by jonlandrum** [comment]
So that solution does block the adblock detection script when not logged in, but it doesn't work when logged in. Not logging in isn't a solution, because they eventually cut you off and force you to create an account.

**Comment by mapx-** [comment]
I tested logging in using these 2 filters, no anti adb
```
@@||di.fm^$generichide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=di.fm
```
