### ISSUE TITLE
assimilator.be

### ISSUE THREAD

**Issue by S3rrrjjj** [uBlockOrigin/uAssets#4144]
### URL(s) where the issue occurs

`https://assimilator.be/`
`https://opus.re/`

### Describe the issue

BlockAdBlock

### Versions

- Browser/version: Chrome Version 70, Windows 10
- uBlock Origin version: v1.17.0

### Settings

All Defaults

**Comment by mapx-** [comment]
What site is opus ?
I get 
`opus.re uses an invalid security certificate`

**Comment by S3rrrjjj** [comment]
opus is the old URL. It redirects to assimilator now.
