### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#4145]
### Describe the issue

cookie

https://github.com/ryanbr/fanboy-adblock/issues/657

### Screenshot(s)

![2018-11-13-the verge](https://user-images.githubusercontent.com/5884000/48395660-4523b700-e718-11e8-8047-a100f6821bff.png)

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by mapx-** [comment]
related
https://github.com/uBlockOrigin/uAssets/commit/b4569de97679af87fe891d611c72525c899d9b56

**Comment by gwarser** [comment]
I think they check `_chorus_privacy_consent` cookie server side.
