### ISSUE TITLE
vidlox.me

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#4149]
### URL(s) where the issue occurs

`https://vidlox.me/embed-pdsa0sbik9bg`

### Describe the issue

popups

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by ghajini** [comment]
`https://vidlox.me/qmiwvbq9ufyb`

Antiadblock

![IMG_20200627_145936](https://user-images.githubusercontent.com/20338483/85919212-060f8e80-b887-11ea-93cf-56965ad96e7c.jpg)

Ublock origin 1.27.11rc6
Firefox A.

**Comment by ghajini** [comment]
`vidlox.me/e95fpjzrso7x`
Pls upgrade filters

**Comment by ghajini** [comment]
url= `https://vidlox.me/7zpqm2uod8y1`

update to 
`vidlox.me##+js(acis, String.fromCharCode, /btoa|break/)`

**Comment by mapx-** [comment]
still working fine: `vidlox.*##+js(acis, Math, XMLHttpRequest)`

**Comment by ghajini** [comment]
i see crapy requests

https://user-images.githubusercontent.com/20338483/102907596-4ea5ae80-449c-11eb-814e-9c7eb868ab64.png

**Comment by ghajini** [comment]
`https://vidlox.me/embed-ktid539gsqtg`

Popup ads at this dead page

Also how to defuse this script
``
</script><script>(function(d,z,x,s,e,o){s.src='//'+d+'/tag.min.js';x.withCredentials=true;x.open('GET','//'+d+'/5/'+z+'/?oo=1',!0);s.onerror=x.onerror=E;s.onload=x.onload=g;x.send();(document.body||document.documentElement).appendChild(s);function g(){o=this.response?JSON.parse(this.response):o;o&&window.kkp4a5x5tv&&window.kkp4a5x5tv(o);}function E(){e&&e();e=null;}})('waisheph.com',1649939,new XMLHttpRequest(),document.createElement('script'),_qeywgwv)</script>
``

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/105577443-fb17d080-5d79-11eb-9fcd-824d634f4d2c.png)

**Comment by ghajini** [comment]
Strange😂😂😂 it was online moment back & I created these filters for myself

`||glazegha.com^`
`vidlox.*##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)`

**Comment by ghajini** [comment]
Back online
