### ISSUE TITLE
Weather.us anti-adblock message

### ISSUE THREAD

**Issue by rahidz** [uBlockOrigin/uAssets#4154]
### URL(s) where the issue occurs

`https://weather.us/`

### Describe the issue

All pages on weather.us redirect to `https://weather.us/site/adblockuser`

### Screenshot(s)

![Screenie](https://i.imgur.com/0VtXofs.png)

### Versions

- Browser/version: Firefox Nightly 65
- uBlock Origin version: v1.17.2

### Settings

- Using EasyList, Adblock Warning Removal, Malware, CookieBlocker, and Ad/Tracking server lists, plus defaults.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
update your lists (purge + update)
