### ISSUE TITLE
audioz.download [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4156]
URL(s) where the issue occurs

`https://audioz.download/`

Describe the issue

Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by KiLL4FuNK** [comment]
open the page for a while browse

**Comment by KiLL4FuNK** [comment]
Pop-up   download link

`https://audioz.download/software/win/170933-download_songwish-remidi-sampler-v100-retail-win.html`

**Comment by mapx-** [comment]
Are you talking about `peeplink.in` download page ?

**Comment by x-R0b0T-x** [comment]
All images do not load when uBlock is activated.

![Image](https://github.com/user-attachments/assets/ea3c0889-085f-4849-bfd8-f7f353168416)

**Comment by huyszn** [comment]
All images load for me.

Test again in a new browser profile with only uBO and its default settings.
