### ISSUE TITLE
popups from sites

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4159]
### URL(s) where the issue occurs
***will be updating more sites here***
`https://mirrorace.com/m/2Pfcr/23653189?t=502339aa32df851d0c8751d35f2aa616f67eadc6`
`hdmoviesplus.xyz`
`https://movies-300mb.club/`
`https://filescdn.net/spzsou9wuipv`
`https://www.oboom.com/JUOOSMR5`
`https://vidtodo.me/wdqkw9pbxigc`
`https://dbupload.info/f/mlrgn3-jcikzdfiuweo9`
`http://uppit.com/06lcm405r1fs`
### Describe the issue

ads/popups
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17
### Settings

uBO's default settings
### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
still see popups of` vavoo.tv`
here `https://www.oboom.com/JUOOSMR5`

**Comment by mapx-** [comment]
Do you see this filter in ublock filters ?
`||oboom.com^$popunder`

**Comment by ghajini** [comment]
yes seen

**Comment by mapx-** [comment]
test this filter
`*$popunder,domain=oboom.com`

**Comment by ghajini** [comment]
malicious popups
`https://mirrorace.com/m/2Pfcr/23653196?t=709c32aa4c589ad9d3fa651d5fc02cdb603a3519`
![screenshot 65](https://user-images.githubusercontent.com/20338483/49214093-e171dd00-f3eb-11e8-9308-09dc15694cae.png)

**Comment by mapx-** [comment]
Did you update ublock filters ? It was fixed in the last hours
https://github.com/uBlockOrigin/uAssets/issues/4214

**Comment by ghajini** [comment]
yes, i always report issues after filter update of all

**Comment by mapx-** [comment]
`mirrorace.com##+js(abort-on-property-read.js, document.head.appendChild)`

**Comment by ghajini** [comment]
new site
`https://worldtvhd.net/dj-duvvada-jagannadham-2017-full-hd-movie-hindi-dubbed-download/`

**Comment by ghajini** [comment]
still popups of `ablehed.pro` upon confirming captcha and clicking play button
`https://worldtvhd.net/dj-duvvada-jagannadham-2017-full-hd-movie-hindi-dubbed-download/`
okay my last comment on this issue, will open new, will not spoil this issue tracker

**Comment by okiehsch** [comment]
No need to open a new issue for `worldtvhd.net` I already referenced this issue for the site.

**Comment by okiehsch** [comment]
> still popups of ablehed.pro upon confirming captcha and clicking play button

Should be fixed now.

**Comment by ghajini** [comment]
`https://worldtvhd.net/the-tomorrow-man/`
here is weired issue when openload embedded video is not on openload server, popups are generated through `openloed.co/redir.php` to malicious popups

when video is on openload server no issue at all `https://worldtvhd.net/watch-boss-2013-full-movie-free-download-hd-720p/`

**Comment by ghajini** [comment]
`https://vidtoro.com/egoz6o89qcdb`
Mirror of `vidtodo.me`
Popup ads

**Comment by ghajini** [comment]
`https://worldtvhd.net/fast-and-furious-8-2017-full-hindi-movie-download-hd/`
popups after clicking play
opera browser

**Comment by ghajini** [comment]
`https://vidtodu.com/p228u3nja2vg`
Mirror of `vidtodo.me`
Popup ads

**Comment by ghajini** [comment]
`https://playvidto.com/osyo7h8s27g9`

Popup ads

Mirror of `vidtodo`

**Comment by ghajini** [comment]
`https://playvidto.com/soi9mcczr2id`
again popup ads

**Comment by ghajini** [comment]
😂😂😂
Site changed name again(guess what's the next domain name is🤣🤣)

***popup ads***

`playtovid.com/iaswfnu0eohb`

**Comment by ghajini** [comment]
1.
Popup ads

New name again
`playedvid.com/pu3i0sqgcqo3`

2.
Some Duplicate filters 
`||phokukse.com^$3p` 

`||deloplen.com^`  = both in uBlock filters and Peter Lowe's list

`||reevaipi.com^$3p`
`||viatepigan.com^$3p`

**Comment by ghajini** [comment]
Another mirror
`vidtoply.com/fghj3vbr4f68`

High computer memory usage,
Popup ads

**Comment by ghajini** [comment]
they again changed....
Popup ads

`playtvid.com/1fvoxhpnubhi`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a5ff34b7d2c9e12c52142179fe5644fa30c8bdf4

How to troll a site.

**Comment by llacb47** [comment]
@ryanbr extra pipe in line 3221

**Comment by ghajini** [comment]
Popup ads 
`https://play4vid.com/upgjbngymmzv`

Q= can we make this thread sticky just like at ublock issues repo and update this site filters whenever they change

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c887a2c17e023e100e536632e163d88bbd31089f

**Comment by ghajini** [comment]
`https://playzvid.com/boulatx9snle`
Ads
Duplicate filter
`||phiptams.net^$3p`

**Comment by ghajini** [comment]
`https://vidto-do.com/w94fbtce6dze`
Pop-up ads

Duplicate filter 

`||d1r90st78epsag.cloudfront.net^`

**Comment by mapx-** [comment]
removed `||d1r90st78epsag.cloudfront.net^`

**Comment by ghajini** [comment]
`vidtudu.com/aiq0s7knyy44`

3rd party tracking

**Comment by ghajini** [comment]
`https://playto-vid.com/5k2xf7souxgg`
Popups

**Comment by ghajini** [comment]
`https://vidtedo.com/embed-gq3fhbej5hom.html`

`https://viditodo.com/gq3fhbej5hom

Popup ads
( domain frequently changing )

**Comment by ryanbr** [comment]
Fixed. Just keep posting the domain changes @ghajini . Doing a good job :)

**Comment by ghajini** [comment]
Popup ads

So they are testing us, changing domains every 2 days....
1st domain was `vidtodos.com`
Then 
`https://lasmxciosd201id2s0o2axmelsopco212i1l0m.com/embed-3x65rdvlwqgc.html`

Now `vidtopo.com/5d1bnyd7viqb`
All these domain changes just 2days....

**Comment by ryanbr** [comment]
I think the vidto guys are just annoyed I keep adding their domain to EL.

**Comment by ghajini** [comment]
Popup ads on firefox android 
Mirror of vidtodo

`https://allvids.co/f8513vw9uln5`

**Comment by ghajini** [comment]
NSFW 
`http://uppit.com/nit8ehd4p5pi`

antiadblock

![image](https://user-images.githubusercontent.com/20338483/109125203-c8466b00-7771-11eb-8fe2-b45726aee7e7.png)

this work
`uppit.com##+js(nosiif, visibility, 1000)`
