### ISSUE TITLE
full-serie.co

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#416]
Hello,

**Versions** : 

uBlock Origin 1.12.4 / Chromium 58

**Settings** : 

default settings + Liste FR

**URL**

`http://www.full-serie.co/`

**Issue** : 

redirection + popunder

**Suggested filter**

`full-serie.co##script:inject(noeval.js)`

**Comment by uBlock-user** [comment]
Won't work here - http://www.full-film.me/film-7830-xxx-3-reactivated-streaming.html

**Comment by uBlock-user** [comment]
Add this too - `full-film.me##script:inject(noeval.js)`
