### ISSUE TITLE
site breakage

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4160]
### URL(s) where the issue occurs

`https://watchvideo.us/ovt0vh0z2lr3.html`

### Describe the issue

video player doesn't start 
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
Video not playing by the way....I put that filter in my filters no luck....with ubo disabled player starts

**Comment by mapx-** [comment]
tested again, no issue for me anymore, try now updating unbreak list and remove it from your "my filters"

**Comment by ghajini** [comment]
updated filters, video won't play.....also badfilter is not shown in logger

**Comment by mapx-** [comment]
badfilter is never shown in the logger, you wont see the csp filter

**Comment by mapx-** [comment]
Did you test using only uBo + default setup ^

**Comment by mapx-** [comment]
Did you update easylist too ? 
Post all the blocked requests in your logger

**Comment by ghajini** [comment]
purge all caches> update now
![screenshot 57](https://user-images.githubusercontent.com/20338483/48847939-c76f4380-edc8-11e8-919b-5ce3c1d15249.png)
![screenshot 58](https://user-images.githubusercontent.com/20338483/48847940-c807da00-edc8-11e8-99d5-30f7698b5568.png)

**Comment by mapx-** [comment]
You still have that wrong filter (csp filter). Your unbreak list is not updated.

**Comment by mapx-** [comment]
add in your "my filters"
`@@||watchvideo.us*.html$csp,first-party`

**Comment by ghajini** [comment]
![screenshot 59](https://user-images.githubusercontent.com/20338483/48848723-ad366500-edca-11e8-9e8e-9aa423220bf7.png)

**Comment by mapx-** [comment]
remove those badfilter and keep only the simpler exception filter above, see if works

**Comment by mapx-** [comment]
I don't know why does not work (badfilter) on your side, could be some weird character when you copied the filter, other reason

**Comment by ghajini** [comment]
iam using updated unbreak list on default setup no user filter, still badfilter doesn't get apply on my side, not shown in logger...simple filter works...thanks

**Comment by mapx-** [comment]
some other blocking extension ? antivirus webshield ?

**Comment by ghajini** [comment]
yes webroot filtering extension.....but that hasn't blocking anything, i just tested with disabled all except ubo

**Comment by mapx-** [comment]
well, the real bad filter in easylist is:
`|blob:$domain=101greatgoals.com|1337x.to|1channel.biz|1movies.is|4chan.org|allthetests.com|ancient-origins.net|androidcentral.com|antonymsfor.com|auroravid.to|biology-online.org|bitvid.sx|breakingisraelnews.com|britannica.com|btdb.in|btdb.to|champion.gg|cloudtime.to|colourlovers.com|connectedly.com|convert-me.com|convertcase.net|couch-tuner.at|couch-tuner.me|couchtuner.ac|couchtuner.us|crackberry.com|datpiff.com|demonoid.pw|destructoid.com|dietlast.com|dreamfilm.se|episodetube.com|episodetube.net|ewatchseries.to|fastpic.ru|filme-streamz.com|filmlinks4u.is|firstrowau.eu|firstrowus1.eu|fmovies.is|fmovies.se|fmovies.to|fullmatchesandshows.com|getinmybelly.com|gofirstrow.eu|gogoanime.sh|gorillavid.in|hdfilme.tv|homerun.re|igvnews.co.uk|imagefap.com|imgadult.com|imgtaxi.com|imgwallet.com|imore.com|israelnationalnews.com|jerusalemonline.com|jewsnews.co.il|keepvid.com|kickass.cd|kino-streamz.com|kiplinger.com|kissmanga.com|kshowonline.com|letmewatchthis.pl|letmewatchthis.video|livecricketz.org|lolcounter.com|ludokado.com|merriam-webster.com|movies4stream.com|movpod.in|mylivecricket.org|mywatchseries.to|newtvworld.com|noslocker.com|nosvideo.com|nowfeed2all.eu|nowvideo.li|nowvideo.sx|nowvideo.to|olympicstreams.me|onwatchseries.to|openload.co|pcgames-download.net|phonearena.com|phonesreview.co.uk|pocketnow.com|primewire.is|primewire.to|primewire.unblockall.xyz|psu.com|rinf.com|roadracerunner.com|serietvsubita.net|sgvideos.net|skidrowcrack.com|snowysmile.com|sockshare.net|sportspickle.com|streamazone.com|streamgaroo.com|strikeout.co|strikeout.me|strikeout.mobi|teamliquid.net|tetrisfriends.com|textsfromlastnight.com|thefreethoughtproject.com|thevideo.me|thewatchseries.ac|torrentz2.eu|torrentz2.me|trifind.com|tv-series.me|unblckd.org|veteranstoday.com|videotoolbox.com|vidtodo.com|vidup.me|vidwatch3.me|vipbox.bz|vipbox.is|vipbox.nu|vipbox.sx|vipbox.tv|vipboxeu.co|vipboxoc.co|vipboxtv.me|vipleague.ch|vipleague.co|vipleague.is|vipleague.me|vipleague.mobi|vipleague.se|vipleague.sx|vipleague.tv|vipleague.ws|vipstand.is|vivo.sx|vrheads.com|watchcartoononline.io|watchepisodes-tv.com|watchseries.sk|watchvideo.us|watchvideo10.us|watchvideo11.us|watchvideo12.us|watchvideo13.us|watchvideo14.us|watchvideo15.us|webfirstrow.eu|wholecloud.net|windowscentral.com|world4ufree.ws,badfilter`

try it (I added badfilter)

**Comment by ghajini** [comment]
doesn't work either

**Comment by mapx-** [comment]
it's something wrong on your side, you could save you current config, and reset uBo, then test again

**Comment by ghajini** [comment]
created new chrome profile, new extensions installed still same problem.....badfilter not working here only.....don't know whats happening, iam open to provide any logs

**Comment by mapx-** [comment]
I'm using the dev build
https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii

You ?

**Comment by ghajini** [comment]
stable versions always

**Comment by jspenguin2017** [comment]
`badfilter` for `csp` won't work until next release right? Are you on 1.17.0 or 1.17.2? 

`@@||watchvideo.us^$csp` works for me.

**Comment by mapx-** [comment]
Now is badfilter for `|blob`, I guess should already work for sll versions ?!

**Comment by jspenguin2017** [comment]
Does it work for you? Did you test on 1.17.0 or 1.17.2?

**Comment by mapx-** [comment]
1.17.3.102

However, in original is |blob so it should work but probably the badfilter is applied only after the compiled / changed filter (from blob to csp) in uBo

**Comment by jspenguin2017** [comment]
Yea, `badfilter` seems to apply to in-memory representation. 

I guess we can wait for next release.

**Comment by ghajini** [comment]
IAM on 1.17 stable
