### ISSUE TITLE
mylink.love [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4163]
URL(s) where the issue occurs

`https://mylink.love/next/cord`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by bogachenko** [comment]
@okiehsch antiadb @mapx-

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e0ff10136679882d2f0ac19c94c3dbf8c6d2c91f

**Comment by ghajini** [comment]
Antiadblock
![IMG_20201206_003404](https://user-images.githubusercontent.com/20338483/101261115-d11f3600-375a-11eb-9339-157522386037.jpg)

### link=
`https://myl1nk.org/ruax3BBwVu9s`
Link came from

`https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A4F75FA64AFC9F3EF360DEB74B1CFF49FD5162E04%26dn%3DLudo%2B%25282020%2529%2BHindi%2B720p%2BNF%2BWEB-DL%2B-%2B1%2BGB%2B-%2BESub%2BAAC%2Bx264%2B-%2BShadow%2B%2528BonsaiHD%2529%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.cyberia.is%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.me%253A2780%252Fannounce%26tr%3Dudp%253A%252F%252Fp4p.arenabg.com%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Fexplodie.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.tiny-vps.com%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fexodus.desync.com%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.torrent.eu.org%253A451%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.moeking.me%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fipv4.tracker.harry.lu%253A80%252Fannounce%26tr%3Dudp%253A%252F%252Fopen.stealth.si%253A80%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2710%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.zer0day.to%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fcoppersurfer.tk%253A6969%252Fannounce`

Firefox android browser, ublock origin stable

**Comment by ghajini** [comment]
Antiadblock

link=
`https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A267BFC138BAC2DD17590E9A6DB5FC1494E9ADE7D%26dn%3DWonder%2BWoman%2B1984.2020.IMAX.HDRip.XviD.AC3-EVO%255BTGx%255D%2B%25E2%25AD%2590%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker.foreverpirates.co%253A80%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.cyberia.is%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.birkenwald.de%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fexplodie.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.tiny-vps.com%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fexodus.desync.com%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.torrent.eu.org%253A451%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.moeking.me%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fipv4.tracker.harry.lu%253A80%252Fannounce%26tr%3Dudp%253A%252F%252Fopen.stealth.si%253A80%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2710%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.zer0day.to%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fcoppersurfer.tk%253A6969%252Fannounce`

came from `https://kickasstorrents.space/t3-Wonder-Woman-1984-2020-IMAX-HDRip-XviD-AC3-EVO-TGx-tt4720861.html`

**Comment by ghajini** [comment]
Antiadblock again

**Comment by JobcenterTycoon** [comment]
I still get Anti Adblock

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by mapx-** [comment]
```
mylink.*#@#+js(aost, performance.getEntries, inlineScript)
@@||in-page-push.com^$script,xhr,domain=mylink.*
```

**Comment by JobcenterTycoon** [comment]
yes this works

**Comment by okiehsch** [comment]
`@@||in-page-push.com^$script,domain=mylink.*`
works on my end, no need to whitelist xhr.

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back, Console crasher and they spam the uBlock Origin logger full with stuff
<img width="50" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/105869930-0e37d400-5ff8-11eb-83ee-11ad4b06440a.PNG">

and i think dropgalaxy was hard ...

**Comment by mapx-** [comment]
`mylink.*##+js(nosiif, break)`

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by mapx-** [comment]
`@@||googleads.g.doubleclick.net/pagead/test_domain.js$script,domain=mylink.*|my1ink.*|myl1nk.*|myli3k.*`

**Comment by JobcenterTycoon** [comment]
Yes it works
