### ISSUE TITLE
map is blocked on airbnb

### ISSUE THREAD

**Issue by jimmerjohn123** [uBlockOrigin/uAssets#417]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

www.airbnb.com

### Describe the issue

map results on www.airbnb.com is blocked when searching for airbnb listings.

1) go to www.airbnb.com
2) search city ie. Chicago, IL (leave other search fields to default)
3) see results

### Screenshot(s)

With ublock
![1](https://cloud.githubusercontent.com/assets/26662282/26325945/0819d066-3f07-11e7-94a9-c6ab42ae5442.png)

Without ublock
![2](https://cloud.githubusercontent.com/assets/26662282/26325947/09491c58-3f07-11e7-9916-8cb997afc0b2.png)

### Versions

- Browser/version: Version 58.0.3029.110 (64-bit)

- uBlock Origin version: 1.12.4

### Settings

Default settings

**Comment by okiehsch** [comment]
The map works on my end, if I reload the page.
Does `@@||bat.bing.com/bat.js$script,domain=airbnb.com` work for you?

**Comment by gwarser** [comment]
Blocked for me if any script from Tampermonkey is running.

**Comment by okiehsch** [comment]
With Firefox -- and without Tampermonkey -- I can't reproduce the issue, the map always shows.

**Comment by gwarser** [comment]
Works in Fx when this is set to 'no' in advanced settings:

>Security Add Tampermonkey to the site's content security policy (CSP) if there is one

**Comment by jimmerjohn123** [comment]
Tested on edge 40.15063.0.0 with default-only ublock origin. I was able to reproduce the issue.

@@||bat.bing.com/bat.js$script,domain=airbnb.com worked to unblock the map on both edge and chrome. thanks all.

**Comment by okiehsch** [comment]
EasyPrivacy fix already proposed  https://forums.lanik.us/viewtopic.php?p=118340#p118340
