### ISSUE TITLE
thesimsresource.com [Anti-Adblock]

### ISSUE THREAD

**Issue by HrBingR** [uBlockOrigin/uAssets#4170]
### URL(s) where the issue occurs

`[thesimsresource.com; https://www.thesimsresource.com/downloads/download/itemId/1432046/format/zip/time/1542829199]`

### Describe the issue

[With adblocker enabled, it shows either a "please wait" countdown timer for 10 seconds, and warns that you're using an adblocker, or a "but first a message from our sponsors" with a countdown timer for 10 seconds. The time decreases to 0 almost instantly, after which it takes you to a page that says "session expired". This occurs on all downloads on this site. With adblocker disabled, the "message from our sponsors" appears with ads everywhere, and a countdown timer that counts down normally from 10]

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7275577/48864786-4d45bb80-edd6-11e8-9ede-41ae5d4c000f.png)
![image](https://user-images.githubusercontent.com/7275577/48864808-62224f00-edd6-11e8-90bb-3da532cb48b0.png)

### Versions

- Browser/version: [Version 70.0.3538.102 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock Origin v1.17.0

]

### Settings

- [Added the nano filtering with extra steps, and added two rules previously suggested on a previous thread about this site. These two rules no longer work, namely:]
[thesimsresource.com##script:inject(nano-setInterval-booster.js)]
[thesimsresource.com##script:inject(set-constant.js, isAdBlocked, false)]

### Notes

[I attempted to block a myriad of scripts as well as elements in ublock, this did not rectify the issue. The site is unbearable, and unbearably slow with ads turned on, and despite them saying that the download will start in 10 seconds with your adblocker enabled, it will not, I've tested this on 2 PC's with similar configs]

**Comment by mapx-** [comment]
test
`thesimsresource.com#@#+js(nano-setInterval-booster.js)`

**Comment by okiehsch** [comment]
`thesimsresource.com##+js(nano-setInterval-booster.js)` has to be removed, it breaks the download.

**Comment by mapx-** [comment]
yeah, exactly, I wanted @HrBingR to check it
