### ISSUE TITLE
filesupload.org antiadblock

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4172]
### URL(s) where the issue occurs

`https://www.filesupload.org/df19f3ef2cf07424fd8ce55f09cbfa3a/5_Weddings_2018_Hindi_www.downloadhub.link_720p_HDRip_ESubs.mkv`

### Describe the issue

adblock detected on clicking ***watch/download***
### Screenshot(s)

![screenshot 62](https://user-images.githubusercontent.com/20338483/48905741-60b15f00-ee88-11e8-974c-85027b641126.png)

### Versions

- Browser/version: chrome 70 stable
- uBlock Origin version: 1.17

### Settings

- uBO's default settings+ decentraleyes

**Comment by ghajini** [comment]
`https://filesupload.org/7591a94257bb9c6a?unlock`
clicking on `download now` results in ads ,not actual link

**Comment by jspenguin2017** [comment]
@ghajini https://github.com/NanoMeow/QuickReports/issues/3052

**Comment by uBlock-user** [comment]
@ghajini fixed with `filesupload.org##+js(multiup, form[action], input[name="link"], action, value)`

scriptlet -- https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L481

**Comment by ghajini** [comment]
Thank you
I wish it might include in ublock origin one day if gorhill wish
