### ISSUE TITLE
latimes.com | Firefox

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4175]
### URL(s) where the issue occurs

`http://articles.latimes.com/1986-08-25/local/me-16102_1_brain`

### Describe the issue

Link for the next page of article or page 2 doesn't work.

### Versions

- Browser/version: Firefox 63.0.3 (basic tracking protection enabled)
- uBlock Origin version: 1.17.2

### Settings

Basic tracking list by Disconnect

### Notes

This issue isn't there if FF's tracking protection is disabled. I understand this may not be directly relevant to uBO so feel free to close this issue. Am just curious regarding a few things so would appreciate some insights.

If I'm not mistaken, FF's tracking protection should only kick in when uBO misses something. In this case, since both FF and uBO are using the same basic tracking list by Disconnect, what is uBO missing here that is being caught by FF? And is there some filter rule that can ensure the site isn't broken without disabling FF's tracking protection?

**Comment by mapx-** [comment]
No issue here even (enabling tracking protection)

**Comment by mapx-** [comment]
I was able to test today, now not anymore (site avoided in Europe), so .. just report the site @ryanbr

**Comment by krystian3w** [comment]
Paywall comeback?

**Comment by in4u** [comment]
The site is detecting and blocking access in private browsing mode.
