### ISSUE TITLE
mediapason.it

### ISSUE THREAD

**Issue by adreporter** [uBlockOrigin/uAssets#4176]
### URL(s) where the issue occurs

`https://www.mediapason.it/topcalcio24/guarda-in-streaming-top-calcio-24/`

### Describe the issue

Please scroll down the page a little bit to see the player. 
If you go back in the stream, after about 10 minutes of playback, the stream will go LIVE, instead of continuing the playback.
This is what I see in the logger after 10 minutes of playback:
<img width="861" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/48911782-06a69e80-ee74-11e8-9cfd-09c76687453b.PNG">

and this is what I see in the console after 10 minutes of playback:
![obraz](https://user-images.githubusercontent.com/18214146/48906661-7cefd480-ee65-11e8-9cb9-e58ee7042900.png)

### Versions

- Browser/version: Firefox 63.0.3 (64 bit)
- uBlock Origin version: 1.17.2

### Settings

- Default settings + Polish filters

### Notes

This problem doesn't occur with uBlock Origin disabled.
Adding italian filters doesn't help.

**Comment by mapx-** [comment]
Test this filter
`@@||pubads.g.doubleclick.net/gampad/live/*.mediapason.it$xmlhttprequest,domain=imasdk.googleapis.com`

**Comment by adreporter** [comment]
@mapx- Thank you, it seems to work. 

After about 10 minutes I see a blue spinning circle on the player for just a second, so the filter helped.
I don't know if it's a useful information, but now I see this in the logger:
<img width="860" alt="testing" src="https://user-images.githubusercontent.com/18214146/48917039-1d092600-ee85-11e8-927f-87042888417f.PNG">
and no errors in the console, so the AbortError is gone.

If I will have some issues again with the player, I'll let you know.

**Comment by mapx-** [comment]
added
