### ISSUE TITLE
Plus-Premieres Anti-Adblock

### ISSUE THREAD

**Issue by SpaceHoliday** [uBlockOrigin/uAssets#4177]
[(https://www.pluspremieres.eu/)]

Describe the issue

[Anti-Adblock blocks download links from being displayed and only shows links for Apple Music and iTunes.]

Screenshot(s)

![43150690-6db5c0d6-8f62-11e8-9ed6-3651d8031b03](https://user-images.githubusercontent.com/39375169/48919725-7cb6ff80-ee8c-11e8-964e-01d39b10fe45.png)

Versions

Browser/version: [Firefox Quantum 63.0.3]
uBlock Origin version: [1.17.2]

Settings

[Default]

Notes

[Every time this website changes domain name, this issue returns. Is there a way to stop the script that blocks adblock entirely?]

**Comment by okiehsch** [comment]
> Every time this website changes domain name.

I guess you mean the site changes it's top-level domain. That does not matter, because the filter `pluspremieres.*` applies to all TLD's.
