### ISSUE TITLE
[Anti-AdBlock] news24.com

### ISSUE THREAD

**Issue by toiletspider** [uBlockOrigin/uAssets#4178]
### URL(s) where the issue occurs

`news24.com`
`channel24.co.za`
`health24.com`
`fin24.com`
`sport24.co.za`
`wheels24.co.za`
`w24.co.za`
`traveller24.com`
`parent24.com`

### Describe the issue

The company has implemented `https://getadmiral.com/` as a anti-adblocker. The site is unusable if you have ublock enabled.

### Versions

- Browser/version: Firefox 63.0.3 64bit
- uBlock Origin version: v1.17.2

### Settings

Added to my My filter:
`news24.com##script:contains(admiral)`
`channel24.co.za##script:contains(admiral)`
`health24.com##script:contains(admiral)`
`fin24.com##script:contains(admiral)`
`sport24.co.za##script:contains(admiral)`
`wheels24.co.za##script:contains(admiral)`
`w24.co.za##script:contains(admiral)`
`traveller24.com##script:contains(admiral)`
`parent24.com##script:contains(admiral)`

**Comment by mapx-** [comment]
`script:contains` is deprecated
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters

> With the introduction of HTML filtering, the script:contains(...) is now deprecated and internally converted into an equivalent ##^script:has-text(...)

However, we search for filters available for both browsers, so, please test this filter for all those sites:

`channel24.co.za,fin24.com,health24.com,news24.com,parent24.com,sport24.co.za,traveller24.com,wheels24.co.za,w24.co.za##+js(abort-on-property-read.js, admiral)`

**Comment by krystian3w** [comment]
news24.com - no have

`channel24.co.za` - works 
`health24.com` - works
`wheels24.co.za` - works
`w24.co.za` - works
`traveller24.com` - works
`parent24.com` - works

`sport24.co.za` Fixed in Annoynace file uBO:

https://github.com/uBlockOrigin/uAssets/blob/003fd5933ae4789fa98d785064c6a78b5329cde3/filters/annoyances.txt#L194

**Comment by mapx-** [comment]
thanks for testing @krystian3w
