### ISSUE TITLE
WoWtoken Info Adblock Warning

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#418]
### Describe the issue

Instead of the price history there is a note saying that the ads shouldn't be blocked

### Versions

- Browser/version: Firefox 55
- uBlock Origin version: 1.12.4

**Comment by mapx-** [comment]
add
```
wowtoken.info#@#.adsbygoogle
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$script,domain=wowtoken.info
wowtoken.info##.adsbygoogle:style(height: 1px !important; overflow-y: hidden !important;)
```

**Comment by gorhill** [comment]
Force an update of _uBlock filters_.

**Comment by mapx-** [comment]
@gorhill , I get a weird behaviour:

- if I try to block main.js script uBo does not see it (I see no main.js in the logger)
- tested in firefox + ABP, chrome + ABP ==> main.js can be blocked (and seen in ABP logger)
- when I'm back from chrome + ABP ==> I can finally see main.js and is also blocked, but after some other tests ==> uBo does not see it anymore

main.js is launched wuth defer keyword:
`src="js/main.js?46" defer`:

**Comment by gorhill** [comment]
Sometimes Chromium will pull stuff from its short-term memory-based cache, and stuff pull from short-term memory-based cache is not reported to webRequest API. Stuff from longer-term disk-based is reported to webRequest API. Might be what you are experiencing?

**Comment by mapx-** [comment]
It seems working using shift-click refreshing. Could be for the defer execution in this case ?

**Comment by gorhill** [comment]
I don't think it's related to `defer`, this has always been the observed behavior, this is why there is the method [`chrome.webRequest.handlerBehaviorChanged`](https://developer.chrome.com/extensions/webRequest#method-handlerBehaviorChanged) in the Chrome webRequest API. uBO does not make use of it though, it comes with too many warnings about slowness, and also a quota -- this would need to be called every time the filtering profile changes, and given the quota, not even guaranteed it would do the job, so I decided against using it.

**Comment by mapx-** [comment]
I see now ... ABP is using that method ==> different behaviour.
