### ISSUE TITLE
Slovak TV Show site- Turn off ads or leave

### ISSUE THREAD

**Issue by bubinek000** [uBlockOrigin/uAssets#4180]
### URL(s) where the issue occurs

```
https://sledujserialy.to/episode/brooklyn-nine-nine-s03e03#26400
https://sledujserialy.to/episode/brooklyn-nine-nine-s03e04

```
### Describe the issue

[I know this might be a tough one since it isnt in english, but it is a large TV Show site (Czech/Slovak) and until recent it was fine, but now instead of video, i get Turn off Adblock or leave ad]

### Screenshot(s)

[https://imgur.com/ncwUenM]
[Translation: Turn off AdBlock so that the page can work correctly]

### Versions

- Browser/version: [here]
- uBlock Origin version: [1.17.0]

### Settings

- Set userResourceLocation to `https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt` so that an extension to UO called nano defender which blocked the ads until now could work

**Comment by okiehsch** [comment]
I get a different message
![image](https://user-images.githubusercontent.com/16838044/48960419-b3644700-ef6c-11e8-9c40-b73581fc32c3.png)

I assume this means I am geo-blocked.

**Comment by bubinek000** [comment]
Yep. Shit.

**Comment by okiehsch** [comment]
I can see a bait script, so you can try adding
`@@||sledujserialy.to/theme/js/ads.js$script,first-party`
to your filter list and see if it works for you.

**Comment by mapx-** [comment]
probably should add also
`@@||sledujserialy.to^$generichide`

```
setTimeout(function() {
                        if (jQuery('#ad-box').css("display") == "none") {
                           //jQuery('.episode-player').html('');
                           //jQuery('.episode-footerbar, .episode-embedcode, #ad-box').remove();
                        }
                        }, 60);
```

**Comment by okiehsch** [comment]
`@@||sledujserialy.sk^$generichide` is part of the regional list.

**Comment by okiehsch** [comment]
`sledujserialy.sk^$generichide` is part of the regional list, the filter is obsolete because of the differen TLD used now.

**Comment by mapx-** [comment]
well, now it's `.to` so 
`@@||sledujserialy.*^$generichide`

**Comment by okiehsch** [comment]
@tomasko126

**Comment by bubinek000** [comment]
Adding these:

@@||sledujserialy.to/theme/js/ads.js$script,first-party
@@||sledujserialy.to^$generichide
@@||sledujserialy.*^$generichide

works! thank you!!
