### ISSUE TITLE
3dgames.com.ar Anti-Adblock

### ISSUE THREAD

**Issue by Ghost8652** [uBlockOrigin/uAssets#4189]
### URL(s) where the issue occurs

`https://foros.3dgames.com.ar/forums/144-discusion-general`

### Describe the issue
"We have detected that you are using an Ad-Block, please disable it" message.

### Screenshot(s)

https://i.imgur.com/Q2Z9Lpc.png

### Versions

- Browser/version: Firefox 63.0.3
- uBlock Origin version: uBlock Origin v1.17.2

### Settings

- Default

**Comment by mapx-** [comment]
You should report the issue here too:
https://github.com/AdguardTeam/AdguardFilters/issues

(for the spanish adguard list)

**Comment by smed79** [comment]
@AdamWr

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/f55a1553808b8a4941322e9122d5df2c91f609f0
