### ISSUE TITLE
Audible Web Player Issue

### ISSUE THREAD

**Issue by ayalfishey** [uBlockOrigin/uAssets#4190]
### URL(s) where the issue occurs

[audible.com]

### Describe the issue

Audible has a web player and one of the features is a time skip button that jumps a few seconds behind or ahead. ubo for some reason causes the buttons to gray out and be unusable after you click them once.

### Screenshot(s)

[https://user-images.githubusercontent.com/11432766/48977920-dfb5bb80-f071-11e8-912e-44423c1c161d.png]

### Versions

- Browser/version: [Firefox/63.0.3 (64-bit)] and [Chrome/70.0.3538.102 (64-bit)]
- uBlock Origin version: [Firefox/1.17.2] and [Chrome/1.17.0]

### Settings

No changes

### Notes

Happens both on chrome and firefox since version 1.17.0 the problem stops once i turn off ubo.

**Comment by mapx-** [comment]
@ayalfishey needing account, subscription ... so you should post here all the blocked requests in your logger when the issue gets in

**Comment by ayalfishey** [comment]
19:04:34 |   | \|\|fls-*.amazon.*% | -- | image | https://fls-na.amazon.com/1/batch/1/OP/AF2M0KC94RCEA:141-6421024-0322355:QATRYQJ333FD1319C82G$uedata=s:%2Fuedata%2Fuedata%3Fat%26v%3D0.202330.0%26id%3DQATRYQJ333FD1319C82G%26ctb%3D1%26m%3D1%26sc%3DQATRYQJ333FD1319C82G%26pc%3D90360%26at%3D90360%26t%3D1543277074817%26bfform%3D1%26ec%3D7%26ecf%3D7%26pty%3DBrowse%26spty%3DApps%26pti%3Dundefined%26tid%3DSY4WQ904MEM6HBEX24Y7%26aftb%3D1:90361
-- | -- | -- | -- | -- | --

19:04:34 |   | /uedata? | -- | image | https://www.audible.com/uedata/uedata?at&v=0.202330.0&id=QATRYQJ333FD1319C82G&ctb=1&m=1&sc=QATRYQJ333FD1319C82G&pc=90360&at=90360&t=1543277074817&bfform=1&ec=7&ecf=7&pty=Browse&spty=Apps&pti=undefined&tid=SY4WQ904MEM6HBEX24Y7&aftb=1

this is what gets highlighted in red when i press the buttons

**Comment by mapx-** [comment]
test
`@@*uedata$image,domain=audible.com`

**Comment by ayalfishey** [comment]
didnt work though this part of the log came in green this time


16:01:40 |   | @@*uedata$image,domain=audible.com | ++ | image | https://fls-na.amazon.com/1/batch/1/OP/AF2M0KC94RCEA:141-6421024-0322355:GDXW31Q93J3V4WWQVY7Q$uedata=s:%2Fuedata%2Fuedata%3Fat%26v%3D0.202330.0%26id%3DGDXW31Q93J3V4WWQVY7Q%26ctb%3D1%26m%3D1%26sc%3DGDXW31Q93J3V4WWQVY7Q%26pc%3D10435%26at%3D10435%26t%3D1543352500724%26ec%3D3%26ecf%3D3%26pty%3DBrowse%26spty%3DApps%26pti%3Dundefined%26tid%3DGDXW31Q93J3V4WWQVY7Q%26aftb%3D1:10436
-- | -- | -- | -- | -- | --
16:01:40 |   | @@*uedata$image,domain=audible.com | ++ | image | https://www.audible.com/uedata/uedata?at&v=0.202330.0&id=GDXW31Q93J3V4WWQVY7Q&ctb=1&m=1&sc=GDXW31Q93J3V4WWQVY7Q&pc=10435&at=10435&t=1543352500724&ec=3&ecf=3&pty=Browse&spty=Apps&pti=undefined&tid=GDXW31Q93J3V4WWQVY7Q&aftb=1
-- | -- | -- | -- | -- | --

**Comment by ayalfishey** [comment]
found the filter that works

**Comment by mapx-** [comment]
Select only the blocked requests (type  `--` in the search box) then take a screenshot of all those blocked requests (or more screenshots if there are more pages) and post here the pics

**Comment by mapx-** [comment]
Does this work ?
`@@||ssl-images-amazon.com^$image,domain=audible.com`
