### ISSUE TITLE
Similar to blockadblock but different variable

### ISSUE THREAD

**Issue by aczire** [uBlockOrigin/uAssets#4192]
### URL(s) where the issue occurs

`https://123moviesfreez.es/watch/the-shape-of-water-2017-1080p-i.1-online-free-123movies.html`

### Describe the issue

If you have ABP or UBlock/UBlock Origin, then the video wont start. Instead the warning to add the site url to whitelist will come up. 
> Please Disable Your AdBlock.
> Video will be visible once you whitelist 123moviesfreez.es on your adblocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/612190/48984255-89736780-f0c7-11e8-8e9d-7a4fdb066287.png)

### Versions

- Browser/version: Google Chrome, Version 70.0.3538.102 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.17.0

### Notes
There is an inline javascript that checks for a variable's value, just like blockadblock. The script snippet is given below.
`<script type="text/javascript">
    var poster_desktop = '';
    var poster_mobile = '';
    var movie = {
        id: 29587,
        name: "The Shape of Water (2017)",
        slug: "the-shape-of-water-2017-1080p",
        episode_slug: "default",
        episode_id: 103851,
        df_sv: 'fserver',
        use_nsv: '1',
    };
    var current_url =
        "/watch/the-shape-of-water-2017-1080p-online-free-123movies.html?episode_id=103851&amp;s=fserver";
    $(document).ready(function() {
        if (window.check_adblock ===
            undefined) {
            $("#media-player").html(
                '<div style="top:50%;z-index:15;position:absolute;width:50%;left:50%;transform:translate(-50%,-50%);margin:0;" class="alert alert-danger notice" role="alert"> <h4>Please Disable Your AdBlock</h4><p style="color:red; font-weight: normal;">Video will be visible once you whitelist 123moviesfreez.es on your adblocker.</p></div>'
            );
        } else {
            load_player(
                '103851');
        }
    });`

As you can see the core part is, `if (window.check_adblock === undefined)` which is almost similar to blockadblock variable. But I tried setting the variable to true, (which is the actual value in case there is no adblocker is present) using `123moviesfreez.es##script:inject(set-constant.js, check_adblock, true)`, but then the page went into an infinite refresh sequence. I cannot use `abort-on-property-read/write`
 because the variable is critical for the proper functioning of that  part.

**Comment by okiehsch** [comment]
> but then the page went into an infinite refresh sequence

That is a site issue, the site is pretty broken, for example go to
`https://123moviesfreez.es/watch/avengers-infinity-war-2018-1080p.70124-online-free-123movies.html`
![image](https://user-images.githubusercontent.com/16838044/48984555-2f8d9480-f0fd-11e8-91ac-b99c436a32e8.png)
or `https://123moviesfreez.es/watch/ant-man-and-the-wasp-2018-1080p.15565-online-free-123movies.html`

![image](https://user-images.githubusercontent.com/16838044/48984575-78454d80-f0fd-11e8-81e5-ec8cb4f726b8.png)

**Comment by okiehsch** [comment]
I found a working site
`https://123moviesfreez.es/watch/titans-season-1-2018-1080p.78018-online-free-123movies.html`

**Comment by aczire** [comment]
Cool. Thanks!
Was wondering how you managed to find that Fingerprint2 variable.

**Comment by okiehsch** [comment]
`https://d4ngwggzm3w7j.cloudfront.net/kUVZ5a1huIhAPZWZjTl5vYQ%3D%3D`

Note that `123moviesfreez.*##+js(abort-on-property-write.js, Fingerprint2)` does not concern the anti-adblock message, it disables the cloudfront script whic triggers a popup/redirection.
