### ISSUE TITLE
Admiral anti-adblock on sport24.co.za

### ISSUE THREAD

**Issue by igitur** [uBlockOrigin/uAssets#4196]
### URL(s) where the issue occurs

`https://www.sport24.co.za/Rugby/Springboks/rassie-erasmus-v-allister-coetzee-what-the-numbers-say-20181126`

### Describe the issue

Admiral anti-adblocker notice pops up

### Screenshot(s)

![image](https://user-images.githubusercontent.com/145854/49003228-330b3500-f16a-11e8-8f27-004418dc35f6.png)

### Versions

- Browser/version: Google Chrome 70.0.3538.110 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.17.0

### Settings

- None

### Notes

Sorry, nothing

**Comment by igitur** [comment]
Also same issue on their partner websites, e.g. news24.co.za , fin24,com and others.

**Comment by mapx-** [comment]
fixes were added some days ago
https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L194
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L13936

enable ublock annoyances list and update all the lists

**Comment by krystian3w** [comment]
`news24.co.za##+js(abort-on-property-read.js, admiral)` 

@igitur  try if works for you, because I do not have `Admiral` on `news24` (Opera 56 / Firefox 63) (that's why he is not on the list yet).

**Comment by igitur** [comment]
Ok, I updated the lists, and it seems to work now. I will continue monitoring.
