### ISSUE TITLE
Tourism Australia's Trip Planner fails to search

### ISSUE THREAD

**Issue by numbermaniac** [uBlockOrigin/uAssets#4197]
### URL(s) where the issue occurs

`https://trip-planner.australia.com/`

### Describe the issue

With uBlock enabled, try to use the Itinerary Planner search at the top of the page. As an example, enter "Sydney" as the destination and click on "Sydney - Australia", then select any start and end dates underneath. (this is just an example - any location will have the same result)

When you click on the "See your plan" button, the loading circle will spin forever and an error will appear in the console: `ReferenceError: _satellite is not defined`

### Versions

- Browser/version: Firefox 64
- uBlock Origin version: 1.17.2

### Settings

No settings changes that I know of.

### Notes

The website appears to depend on a library from
`https://assets.adobedtm.com/6fb6e65091abb6d979e09e86ef9f60bfab63fe46/satelliteLib-a7cbeb25ca5db5731606b57a50a7f7440e287963.js` - uBlock is blocking this, resulting in the error.

The error also appears in the console just when loading the home page, before searching - but you won't see the effect of it until you try to search.

**Comment by mapx-** [comment]
Does this filter work for you ?
`@@||adobedtm.com^*/satellitelib-$script,domain=australia.com`

**Comment by numbermaniac** [comment]
Yes, looks like it does work! Search works and shows results, no error in the console.

**Comment by smed79** [comment]
https://github.com/easylist/easylist/commit/7ec3334e3e32511e552cd0bf682e0a5fafa029fd

**Comment by mapx-** [comment]
thx
