### ISSUE TITLE
mega-mkv.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4198]
URL(s) where the issue occurs

`http://mega-mkv.com/los-increibles-2-2018-hd-720p-latino-dual-00/`

Describe the issue

![2018-11-26_10h23_47](https://user-images.githubusercontent.com/36675858/49016701-a8283b80-f165-11e8-9225-4a7578fd3e4c.png)
![2018-11-26_10h24_31](https://user-images.githubusercontent.com/36675858/49016707-ac545900-f165-11e8-86cb-c70f412fd0b5.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by okiehsch** [comment]
Does
`||code.jquery.com/jquery-$script,domain=mega-mkv.com`
break anything? You have to bypass the cache once or it to work.

**Comment by KiLL4FuNK** [comment]
the filter works well
