### ISSUE TITLE
reader.bookmate.com

### ISSUE THREAD

**Issue by aphelion1** [uBlockOrigin/uAssets#4199]
`reader.bookmate.com`
i tested reading a book and take too much time loading something in chrome, but i tested the same in firefox and load the page faster, maybe is something related to ublock i don't know, i hope you can help me with this

**Comment by aphelion1** [comment]
can you close this please, was my mistake, it's fixed now

**Comment by mapx-** [comment]
You are able to close it too (you created the issue)
