### ISSUE TITLE
Chip.de malicious installers

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#42]
### URL(s) where the issue occurs

`http://www.chip.de/downloads/Maxthon-Cloud-Browser_13008149.html`
`http://www.chip.de/downloads/Tor-Browser-Paket_22479695.html`

### Describe the issue

Instead of adding it to the Badware list how about hiding the links to their malicious installers? That should be able to close https://github.com/gorhill/uBlock/issues/673.

### Screenshot(s)

![](https://cloud.githubusercontent.com/assets/16030872/15099945/ca6b7930-1564-11e6-9a18-d5ca225f1b0c.png)

### Notes

https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/blob/master/uBlock-Filters-Plus.txt#L269
`chip.de##[href^="javascript:DSinitDl"]`

**Comment by gorhill** [comment]
On my side:

- I do not see a "Manuelle installation" button.
- The filter `chip.de##[href^="javascript:DSinitDl"]` matches nothing on the page.
- There are two buttons as the one you highlighted above: one at the top, one at the bottom.

**Comment by IDKwhattoputhere** [comment]
That's quite odd. I get the button ([two times like you said](https://cloud.githubusercontent.com/assets/16030872/15117103/500e7316-1606-11e6-872a-9c6b0204fcb5.png)) which links to `javascript:DSinitDl('060520161706','54386105','')` for the first link I provided. It happens in both Firefox (new profile) and Chrome. Also tried a Canadian VPN exit but same result.

**Comment by SARG04** [comment]
The CHIP-Installer is not shown to every one and not every time and not for every software. If you get the installer or the real download link deepens on multiple factors:
- User-Agent
- language settings
- installed Add-ons (AdBlock ...)
- Referrer
- the software you are trying to download

Best chance to get the installer, Firefox on Windows, with the  preferred language set to German, Ad blocked and coming from a Goggle search result (tested with VLC).

A non Windows User-Agent will never get the installer as far as I know.

http://anleitung.trojaner-board.de/chip-installer
http://www.randombrick.de/downloads-von-chip-de-ueber-den-chip-installer-vermeiden/
http://www.chip.de/secured-installer-support/faq

**Comment by tobbi** [comment]
I used the "User Agent Overrider" add-on from https://addons.mozilla.org/de/firefox/addon/user-agent-overrider/ and set the User Agent to "Windows / IE 11". If that's done, the Download button and the "Manuelle Installation" link can be seen!

**Comment by wakkabakkamakka** [comment]
i too get the installer pretty much all the time... its absolute trashware...
using windows 10 firefox 64 bits

**Comment by wakkabakkamakka** [comment]
this is still on the "waiting list" to be added to badware risks... id really like to see this solved.

can only gorhill himself add this ? if so: @gorhill have you tried changing your user agent to windows so you can see it for yourself ?

**Comment by gorhill** [comment]
Would `||www.chip.de/downloads/$document` solve the issue?

**Comment by tobbi** [comment]
Yes, it would definitely display a warning when opening a chip.de download page. If there's a more sophisticated method available (one that prefers the bundle-less download), I'd prefer that, though.

**Comment by wakkabakkamakka** [comment]
chip.de##[href^="javascript:DSinitDl"] removes the link to the adware installer so only the link to the normal installer is left

**Comment by Hrxn** [comment]
Even better: Avoid sites like chip.de like the plague. If their traffic takes a significant hit, maybe they will learn.

There isn't one good reason to use them in the first place. For what? Downloads? Always use the original source, if possible.

**Comment by IDKwhattoputhere** [comment]
They have a very high rank on Google in Germany if you search for any software, often appearing even above the official page.
People have connected a good image with chip.de because it has been around and popular for quite some time. Chip.de can now freely abuse this and since many people don't even realize where the malware comes from or that it's even malware, chip.de will probably be able to continue this for some time.

Blocking them would help inexperienced users (which if I understand correctly is the point of `badware.txt` in the first place), not us who know to get the software from the official page.

**Comment by krystian3w** [comment]
Update #42, #178, gorhill/uBlock#673, #6587
