### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4201]
### URL(s) where the issue occurs

Hard block these links:
```
whatsaappp.com
check-now.net
googlo.co
yahoo-news.co
```

### Describe the issue

They are used for pop ups.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/49041331-f30c7800-f192-11e8-8ff9-2c800f7d0abc.png)

**Comment by krystian3w** [comment]
And how it works on the phone - probably not from Chrome.

**Comment by kowith337** [comment]
They are none of extensions works with Chrome for Android yet.

**Comment by terrorist96** [comment]
`https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjbmayjyZHgAhULTt8KHS0PC88Qjxx6BAgBEAI&url=https%3A%2F%2Flavfd.net%2Fpics%2Fvertical-gallery-called-elevate&psig=AOvVaw3js83lfrFx5ge5vFrydslj&ust=1548802485650245`

leads to spam/fake sites. `5qg9ibt1a6.com` which will redirect to mostly fake sites, but also some legit looking sites. Incomplete list of the spammy sites:

```
lameterthenhep.info
axxmtjambo.xyz
viewmypdf.com
chairgaubsy.com
epailseptox.com
microsoft.com-repair-windows.live
notification-time.com
browsergames2018.com
jobhelpr.com
hentaiplaytime.com
```

Seems like just blocking `5qg9ibt1a6.com` may be enough, but blocking the list of sites wouldn't be bad either.

**Comment by terrorist96** [comment]
Same thing:
`http://atreus.hexenschmiede.info/atreus/`

Leads to `o4uxrk33.com` which then leads to shit sites.

**Comment by terrorist96** [comment]
Thanks. That looks like it would be a good list to include by default or merge with an existing list. Here is also other lists maintained by Lanik:
https://github.com/LanikSJ/ubo-filters/tree/master/filters

**Comment by LanikSJ** [comment]
@smed79 I've fixed most of the list titles best I could if you have suggestions let me know.

@terrorist96 would be nice if these became mainstream but we all know how quickly that happens. 🙂

**Comment by terrorist96** [comment]
@gorhill what do you think about including some/all of @LanikSJ's lists by default?

**Comment by gorhill** [comment]
Since it's domains linked to Admiral, why it it not integrated into EasyList?

**Comment by sebast889** [comment]
@LanikSJ Any chance you can create a single combined list containing of the main lists from https://github.com/LanikSJ/ubo-filters/tree/master/filters?

**Comment by LanikSJ** [comment]
@sevast889 I created those from what @smed79 already did: http://smed79.surge.sh/up/adb.txt

**Comment by LanikSJ** [comment]
I see I haven't noticed that thanks.

**Comment by ryanbr** [comment]
Probably a bad idea to include some many wholesale domain changes. Ideally we address them as people see them, so atleast we can see how current each domain is (and its not unused or a dead domain)
