### ISSUE TITLE
Problem: overlay with dynamic name, impossible to block.

### ISSUE THREAD

**Issue by NessunoIM** [uBlockOrigin/uAssets#4206]
### URL(s) where the issue occurs
http://toplive.info  --> https://telerium.tv/embed/*.html

### Describe the issue
I open this link [http://toplive.info/player.php?id=embed.php?id=live1] but the commands (volume) of player are not showned, then I open with the right click the embed video in another page: [https://telerium.tv/embed/31487.html]
Now I can block the overlay mask...but if I update the page, name of class change, and I must block again and again...

### Versions

- Browser/version: [Firefox 63.0.3 (64 bit)]
- uBlock Origin version: [1.17.2]

### Settings

- as default

### Notes
There is a dynamic named overlay that I can't block.
Another problem is the popup when I click on player. Popup is blocked by firefox (I receive notification that a popup was blocked), but I want add a specific filter for popup in this site, to remove it completely.

**Comment by okiehsch** [comment]
> but I still see the overlay

Can you post a screenshot? If you mean the small `x`.
![image](https://user-images.githubusercontent.com/16838044/49190014-d9288c00-f370-11e8-8268-977b7a3ec092.png)

That can't be fixed in uAssets without breaking full screen functionality, you have to click it, the resulting popup has been defused.

**Comment by NessunoIM** [comment]
Ok thanks! Now I resolved. I have blocked the close icon, this was the problem! 
I have a question, I see (with firefox element analizer) that the "overlay rules" are in stylesheet inline 2.
There is a way to block a specific stylesheet?
