### ISSUE TITLE
proxfree.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4207]
### URL(s) where the issue occurs

`https://www.proxfree.com/`

### Describe the issue

Leftover space that may be corrected with: 

`proxfree.com###pftop:style(height: auto !important;padding-bottom:5px !important)`

### Versions

- Browser/version: 63.0.3 (64-bit)
- uBlock Origin version: uBlock Origin 1.17.2

### Settings
+Annoyances

**Comment by smed79** [comment]
banner ads
- https://i.imgur.com/FqXH5Qx.png
- https://forums.lanik.us/viewtopic.php?p=46733#p46733
