### ISSUE TITLE
viid.me anti adblock

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#421]
### URL(s) where the issue occurs
http://viid.me/qwZlwM

### Describe the issue
Anti adblock

### Screenshot(s)
![im4](https://cloud.githubusercontent.com/assets/27068733/26530944/1c10af3c-43cf-11e7-8e7a-86d4b6bae254.jpg)

### Versions
uBlock Origin version: 1.12.4
uBO's default filters + Fanboy’s Annoyance List + Dan Pollock + hpHosts + MVPS + Peter Lowe

**Comment by gorhill** [comment]
With `@@||viid.me^$generichide`, the warning disappears. With the warning, I was not blocked from accessing the content.

**Comment by SMed79** [comment]
Not an anti adblock but just a warning fixed in **Adblock Warning Removal List**.

https://hg.adblockplus.org/antiadblockfilters/rev/ff06316ae716
