### ISSUE TITLE
newegg.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4210]
### URL(s) where the issue occurs

`newegg.com`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/49174888-56beae80-f315-11e8-8426-7a754fd8ae62.png)
![image](https://user-images.githubusercontent.com/12802056/49174980-8a99d400-f315-11e8-8207-ecd1443f5bb1.png)

### Notes

`@@monetate.net`

**Comment by okiehsch** [comment]
I can't reproduce.
