### ISSUE TITLE
mirrorace.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#4214]
### URL(s) where the issue occurs

`https://mirrorace.com/m/29zxt`

### Describe the issue

broken capatcha

### Screenshot(s)

![2018-11-28-window](https://user-images.githubusercontent.com/5884000/49186651-84334880-f365-11e8-80f5-60bc89d776d8.png)

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by mapx-** [comment]
test these filters
```
mirrorace.com#@#+js(abort-on-property-write.js, encodeURIComponent)
mirrorace.com##+js(abort-on-property-read.js, Date.prototype.toUTCString)
```

**Comment by KonoromiHimaries** [comment]
@mapx- i do not can change my language
![2018-11-29-window](https://user-images.githubusercontent.com/5884000/49190046-0412e000-f371-11e8-9e64-47a88d01202e.png)

**Comment by okiehsch** [comment]
````
mirrorace.com#@#+js(abort-on-property-read.js, Date.prototype.toUTCString)
mirrorace.com##+js(abort-on-property-read.js, eddOptions)
````
works for you?

**Comment by mapx-** [comment]
@KonoromiHimaries  another change here, could you test again - after updating the filter lists ? It seems ok for me changing the language.

**Comment by KonoromiHimaries** [comment]
@mapx- broken capatcha
![2018-12-21-attention required _ cloudflare](https://user-images.githubusercontent.com/5884000/50329416-89645d00-04f7-11e9-96b5-381d7ef5c716.png)

tested with proxy
```
chrome.exe --proxy-server="socks5://52.192.76.155:1080"
```

**Comment by mapx-** [comment]
@KonoromiHimaries 

test
`mirrorace.com#@#+js(abort-on-property-read.js, document.head.appendChild)`

and see also if you **get any popup**

**Comment by okiehsch** [comment]
`https://mirrorace.com/m/29zxt/24786187?t=c8c3b2ea219f24442e94efd2373ae51498ced4ab` 
I get a popup with that filter enabled, so it can probably be removed anyway.
````
mirrorace.com##+js(abort-on-property-read.js, eddOptions)
||ajjhtetv87.com^$3p
````
fixes the popup on my end.

**Comment by KiLL4FuNK** [comment]
popup

`https://mirrorace.com/m/4aBca`

**Comment by smed79** [comment]
No popup here !!

**Comment by mapx-** [comment]
fixed by @okiehsch  
https://github.com/uBlockOrigin/uAssets/commit/9f8b6de6d0d06383b5a37b3ee5d1796d700fe2cd

but strangely no trace here

**Comment by mapx-** [comment]
yeah, because the site has other issue too
https://github.com/uBlockOrigin/uAssets/issues/3646

**Comment by ghajini** [comment]
`https://mirrorace.com/m/2V87h/45603418?t=076a2c6b0779387f5733e85f0e576636210f1e65`

Filter =

`##[href^="https://speedtest.apkelite.com/search/"]`

**Comment by ryanbr** [comment]
What exactly does that hide on that site? I couldn't see a difference.

**Comment by ghajini** [comment]
You have to click one of the file server say openload server
on next page you see fake download option

![IMG_20191028_150003](https://user-images.githubusercontent.com/20338483/67667662-2e489580-f966-11e9-97d4-921a6f185512.jpg)
