### ISSUE TITLE
Mywatchseries  popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4216]
### URL(s) where the issue occurs

`https://w3.mywatchseries.stream/`

### Describe the issue

Ads/popups

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox Android 63 stable
- uBlock Origin version: 1.17.2

### Settings

- uBO's default settings

### Notes

**Comment by ghajini** [comment]
Popups again
Firefox android, ublock origin stable

**Comment by mapx-** [comment]
Tested on desktop => give it a try on android

**Comment by ghajini** [comment]
`https://get.mywatchseries.stream/`
Popups back

Screenshots =
`https://user-images.githubusercontent.com/20338483/60397362-de82ca80-9b3b-11e9-8f68-ac74b211c064.jpg`

`https://user-images.githubusercontent.com/20338483/60397366-eb072300-9b3b-11e9-9911-04b7edb73fcc.jpg`

`https://user-images.githubusercontent.com/20338483/60397367-f22e3100-9b3b-11e9-8236-ae9d6c52f867.jpg`

**Comment by mapx-** [comment]
@ghajini test the added filters

**Comment by ghajini** [comment]
Working, make filters `mywatchseries.*`

**Comment by ghajini** [comment]
`||get.mywatchseries.stream/sw.js$important`
