### ISSUE TITLE
hellporno.com (ads) (nsfw)

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#4221]
### URL(s) where the issue occurs

`[hellporno. com]`

### Describe the issue

[Ads at the top of the page and a floating banner ad.]

### Versions

- Browser/version: [Firefox/Mobile v63.02]
- uBlock Origin version: [1.17.2]

### Settings

- [default]

### Notes

[Sorry if you guys don't do mobile versions of sites. I can imagine the same issues are in the desktop version as well but I'm unable to test this.]

**Comment by mapx-** [comment]
test these filters

```
||smartclick.net^
hellporno.com##.bnnr
hellporno.com##.bnnrs-player
m.hellporno.com###fltd-inner
m.hellporno.com##.banner
```

**Comment by okiehsch** [comment]
Does 
`||hellporno.com^$subdocument,first-party`
break anything using the mobile version?

**Comment by gidgudmate** [comment]
Don't see any breakage and it does block the ads.

**Comment by okiehsch** [comment]
Sorry, I missed your last comment before I commited, only
`m.hellporno.com###fltd-inner`
should be added?

**Comment by gidgudmate** [comment]
Yeah removes some blank space on the bottom of the page. But it's more of an annoyance and isn't really necessary it's up to you really.
