### ISSUE TITLE
autoexpress.co.uk [Anti-Adblock]

### ISSUE THREAD

**Issue by hoonkai** [uBlockOrigin/uAssets#4222]
### URL(s) where the issue occurs

`https://www.autoexpress.co.uk`

### Describe the issue

Anti-Adblock.

### Screenshot(s)

![screen shot 2018-11-30 at 10 45 02 pm](https://user-images.githubusercontent.com/14197204/49290106-b8d40b00-f4f1-11e8-8290-0ecbd59f3d82.png)

### Versions

Browser/version: [Version 70.0.3538.110 (Official Build) (64-bit)]
uBlock Origin version: [uBlock Origin v1.17.0]

**Comment by mapx-** [comment]
I cannot reproduce your issue.
Did you update all the lists in uBo ? 
Are you testing using the default lists ?
other blocking extensions in chrome ?
