### ISSUE TITLE
1337x.to | Popunders

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4225]
### URL(s) where the issue occurs

`https://1337x.to`

### Describe the issue

Search for anything. On the result page, clicking `Sort by...` leads to a popunder ad. Open any result. Click the `FILES` tab. This also opens another popunder. Such popunders appear randomly on few other occasions as well.

### Versions

- Browser/version: Firefox 63.0.3
- uBlock Origin version: 1.17.2

### Settings

Default + Adguard Base Filter

### Notes

Adguard's base filter warns about opening the link in popunder ad's page.

**Comment by smed79** [comment]
add also `https://x1337x.ws/`

**Comment by in4u** [comment]
`1337x.to` has the following official mirrors: `1337x.st`, `x1337x.ws`, `x1337x.eu` and `x1337x.se`.

There are 2 ad links on the side of any search result - `PLAYNOW (STREAM)` and `ANONYMOUS DOWNLOAD`. Below them is a VPN ad.

Adguard's base filter has the following rules which take care of these ads on `1337x.to` domain:

`1337x.to##a[href^="/vpn"][href*=".php"]`

`1337x.to##a[href^="/streamredirect"]`

`1337x.to##a[href^="/vpn"][href*=".php"]`

`1337x.to##.box-info-detail > div[class]:not([class="manage-box"]):not([class^="torrent-"]):not([class="pagination"]):not([class="table-list-wrap"]) > a[id]`

Adguard's spyware filter has an additional `||cdn.1337x.to/ip*.php` filter.

Please include these filters in uBO so that all 1337x mirrors are also covered. Something like `1337x.*,x1337x.*##a[href^="/vpn"][href*=".php"],a[href^="/streamredirect"],a[href^="/vpn"][href*=".php"]` along with `||cdn.1337x.to/ip*.php` and `||cdn.x1337x.*/ip*.php`.

**Comment by mapx-** [comment]
test
`1337x.*,x1337x.*##[href*=".php"]`

already ON for 1337x.st

Does it break any functionality ?

**Comment by in4u** [comment]
Not for me.

**Comment by in4u** [comment]
There's a slight twist this time. Not every ad link (1st of those two ad link buttons, i.e. red one) has an `href` starting with `/stredir`. It varies with the type of content. Go to browse torrents section in the sidebar and try opening links from different categories to see the wide variations.

**Comment by mapx-** [comment]
if you get other exceptions => provide example pages

**Comment by in4u** [comment]
Those two ad link buttons are back again.

**Comment by mapx-** [comment]
add
```
1337x.*,x1337x.*##.btn:has-text(/play/i)
1337x.*,x1337x.*##.btn:has-text(/An‌on‌ymous/i)
```

**Comment by in4u** [comment]
One of those two ad buttons still shows up in some categories, e.g. Applications, Music, Games and Other. Example pages:

`https://1337x.to/torrent/2453094/LibreOffice-v5-4-1-Windows-x64/`
`https://1337x.to/torrent/1103703/The-Animals-House-of-the-Rising-Sun-128kbps-MP3/`
`https://1337x.to/torrent/919513/Xonotic-0-7-0/`

**Comment by in4u** [comment]
Those two ad buttons are back again.

**Comment by in4u** [comment]
Perhaps an additional rule is required for [this](https://github.com/uBlockOrigin/uAssets/issues/4225#issuecomment-452731858) missed button.

**Comment by mapx-** [comment]
However, they are watching this thread, so ...

**Comment by in4u** [comment]
What's the `1337x.*,x1337x.*##.btn:has-text(/‌/i)` rule for?

There is a VPN ad which I noted [here](https://github.com/uBlockOrigin/uAssets/issues/4225#issuecomment-447078244) and is blocked by Adguard's `1337x.to##.box-info-detail > div[class]:not([class="manage-box"]):not([class^="torrent-"]):not([class="pagination"]):not([class="table-list-wrap"]) > a[id]` rule. Please include a filter for this ad too since Adguard's rule is only applicable for primary domain and not the mirror domains.

**Comment by in4u** [comment]
All sites, except the mirror `1337x.is`, are broken / inaccessible perhaps due to the following Easylist rules:

`||1337x.to^$csp=script-src 'self' 'unsafe-inline'`
`||1337x.st^$csp=script-src 'self' 'unsafe-inline'`
`||x1337x.eu^$csp=script-src 'self' 'unsafe-inline'`
`||x1337x.se^$csp=script-src 'self' 'unsafe-inline'`
`||x1337x.ws^$csp=script-src 'self' 'unsafe-inline'`

Upon initial site visit (clear cookies and site data, or try private browsing mode), there is a "DDoS protection by Cloudflare" page with the message "Checking your browser before accessing <domain name>. This process is automatic. Your browser will redirect to your requested content shortly. Please allow up to 5 seconds…". However, the page gets stuck there permanently and nothing happens. But if uBO/Easylist is disabled then the site loads normally within 5 seconds.

**Comment by mapx-** [comment]
I cannot reproduce (neither in private mode)

Does this filter help ?
`||1337x.to^$csp=script-src 'self' 'unsafe-inline',badfilter`

**Comment by in4u** [comment]
Strange that you can't reproduce the issue even in private browsing mode. Maybe Cloudflare triggers this protection page based on some other criteria like geo-IP, etc.

Anyways, with `badfilter` the sites are unbroken and accessible again. Please include these exclusion filters in the relevant list if possible.

**Comment by mapx-** [comment]
@ryanbr

**Comment by in4u** [comment]
Those 2 ad link buttons and the VPN ad link are back.

**Comment by mapx-** [comment]
test - see if breaks something
```
1337xproxy.info,1337x.*,x1337x.*,1337x.unblock2.xyz##ul > li:has-text(/‌/i)
1337xproxy.info,1337x.*,x1337x.*,1337x.unblock2.xyz##:xpath(//*[contains(text(),"Address")]/..)
```

**Comment by in4u** [comment]
Works great, no breakage for me.

**Comment by in4u** [comment]
The rule `1337x.unblock2.xyz,1337x.unblockit.*##+js(aopr, Math.floor)` is now causing breakage on `1337x.unblockit.*` because opening the site `https://1337x.unblockit.uno` results in an endless loop with the page displaying `Checking your browser before accessing unblockit.uno. This process is automatic. Your browser will redirect to your requested content shortly. Please allow up to 5 seconds… DDoS protection by Cloudflare`. This page just keeps refreshing every 5 seconds and the actual site doesn't load.

**Comment by in4u** [comment]
@mapx-, @okiehsch, @uBlock-user, anyone? The breakage on `1337x.unblockit.*` as noted above is yet to be fixed!
