### ISSUE TITLE
 vidmo.org (nsfw) (ads)

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#4228]
### URL(s) where the issue occurs

`[vidmo.org]`

### Describe the issue

[ads on the top of the page probably elsewhere.)

### Versions

- Browser/version: [Firefox android v63]
- uBlock Origin version: [1.17.2]

### Settings

- [default]

**Comment by smed79** [comment]
@okiehsch mirror site (NSFW) `https://en.sexmo.org/`
