### ISSUE TITLE
express.co.uk - Content breakage [Peter Lowe's List]

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#423]
Image slideshows are broken on http://www.express.co.uk due to "_Peter Lowe’s Ad and tracking server list_".

**Screencapture:** https://streamable.com/iijt6

**Error URL:** 
http://www.express.co.uk/comment/columnists/adam-helliker/807274/the-crown-netflix-queen-fan-royal-family

I am not able to pin down the exact filter causing the issue but as is evident from the screencapture the issue is caused by Peter Lowe's list.

_**Note:** Using uBO 1.12.4 on Chrome 58 with default settings._

**Comment by gorhill** [comment]
Can't reproduce, works fine here with default settings.

**Comment by okiehsch** [comment]
@gotitbro the filter causing your issue with Peter Lowe's list is `parsely.com`, but if you use uBO
with default settings the exception filter `@@||static.parsely.com^$script,domain=dailystar.co.uk|express.co.uk` in `EasylistPrivacy`
fixes that issue.
In your screencapture you do **not** use `EasylistPrivacy`.

**Comment by gotitbro** [comment]
@okiehsch @gorhill I should have been more clear. In other issues I open I mention using _**default settings and default filters**_. In this issue I only mentioned default settings and not the filters taking into consideration that settings usually mean alteration with the extension's functionality.

Sorry for squandering your time. My mistake I will be more explicit in providing details when the default settings and **filters** are not the same.

**Comment by gorhill** [comment]
To be clear, no fix will be added to uBO's own filters when an issue arises as a result of removing default lists.

**Comment by gotitbro** [comment]
@gorhill Thanks for clarifying. I always make sure to post if the filters and settings are default or have been changed, I will make sure to include more details if settings/filters have been changed in the future.

Also, if an issue arises of **adding** a list that should be reported to that list's maintainer and this gets put in the same rule as above I assume?

**Comment by gorhill** [comment]
For whatever issue, help will be provided, but whatever filter solves the issue, it will be added to uBO's filters only if the issue exists with default filter lists.
