### ISSUE TITLE
thedailybeast.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4231]
### URL(s) where the issue occurs

`https://www.thedailybeast.com/judge-napolitano-patiently-explains-michael-cohens-plea-to-dismissive-fox-news-hosts`

### Describe the issue

Unblocked sponsored content at end of article.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/49332563-15c8d300-f57d-11e8-8e23-bc32d76db1b5.png)

### Notes

`||embed.actionbutton.co/widget/widget-iframe.html`

**Comment by okiehsch** [comment]
Why open an issue, you know

**Comment by terrorist96** [comment]
Sorry. Made an issue here: https://github.com/easylist/easylist/issues/2373
