### ISSUE TITLE
brtfix.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4232]
URL(s) where the issue occurs

`https://brtfix.com/indir/?file=07cc8393fd`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by mapx-** [comment]
I don't understand how is working the site, however, a filter could be
`brtfix.com##+js(setTimeout-defuser.js, nextFunction, 2000)`

**Comment by KiLL4FuNK** [comment]
It works perfect
