### ISSUE TITLE
m.hclips.com (nsfw) (popunder)

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#4234]
### URL(s) where the issue occurs

`[m.hclips.com`]

### Describe the issue

[When clicking on the play button for a video a new tab opens that's the URL is always out.tubecorporate.com]

### Versions

- Browser/version: [Firefox android v63]
- uBlock Origin version: [1.17.2]

### Settings

- [default]

### Notes

[I can already see a filter for this site but it appears it doesn't work right for the mobile version or maybe works differently. Testing might need to be done on mobile as I'm not sure this issue persists onto the desktop version although it's possible.]

**Comment by gidgudmate** [comment]
did you try on the mobile version? not sure if the issue carries over to the desktop but it happens on android at least.

I'm not sure but what about the giant script on line 89 when you view the page source. I see a couple references to popup, popunder, and even the site the popups go to.

**Comment by okiehsch** [comment]
I tried with the User Agent set to `Firefox Android Mobile`. I do not have an Android device.
If I use a device running `iOS` and `Adguard` I can reproduce a popup/popunder to `out.tubecorporate.com`.

**Comment by gidgudmate** [comment]
Weird might be specific to me idk is there a fix I can test and maybe see if it'll work for me?

**Comment by mapx-** [comment]
try
`m.hclips.com##+js(abort-current-inline-script.js, decodeURIComponent, getTDSUrl)`

**Comment by okiehsch** [comment]
Or 
`m.hclips.com##+js(abort-current-inline-script.js, setTimeout, popunder)`

**Comment by gidgudmate** [comment]
second one works tried a few videos and nothing popped up.

**Comment by gidgudmate** [comment]
@okiehsch

You can remove that filter as it seems it's not needed. Just add `m.hclips. com##.nopop` managed to notice it when long pressing on the video player and would see the `out.tubecorporate.com` link.
