### ISSUE TITLE
shoppable.com [Cookie Wall]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4235]
### URL(s) where the issue occurs

`https://www.shoppable.com/`

### Describe the issue
Cookie Wall - from https://github.com/ryanbr/fanboy-adblock/issues/733

### Screenshot(s)

![ss2](https://user-images.githubusercontent.com/43844449/47718439-b8bdc280-dc48-11e8-9e69-482b794842e8.png)

### Versions

- Browser/version: Firefox 63.0.3 64bit / Opera 56 64bit
- uBlock Origin version: 1.17.4

### Settings

uBO default + uBO annoyances

**Comment by kulfoon** [comment]
Actually I've decied to close it and wait for a new version of I don't care about cookies addon, if it still won't be fixed in the addon, I'll reopen the issue here.

**Comment by mapx-** [comment]
```
shoppable.com###cookiesModal
shoppable.com##.in.fade.modal-backdrop
shoppable.com##body:style(overflow: auto !important;)
```

**Comment by krystian3w** [comment]
`shoppable.com###cookiesModal`
`shoppable.com##.in.fade.modal-backdrop`

combine with one?

`shoppable.com###cookiesModal, .in.fade.modal-backdrop`

**Comment by uBlock-user** [comment]
I have also started combining multiple cosmetic filters in one filter for the said website in my own personal filter list, that reduces filter count and better performance.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3059334aa8e240c4e558ae22e9ce93fd799dd3ff

**Comment by smed79** [comment]
May i know why my comment has been deleted here ?!!

**Comment by mapx-** [comment]
What comment ?

**Comment by krystian3w** [comment]
Maybe GitHub failure.

**Comment by krystian3w** [comment]
@mapx-  have both notifcations (e-mail and :bell:)?

**Comment by mapx-** [comment]
I'm trashing them, however from my trash I see no smed79 post.

**Comment by smed79** [comment]
> What comment ?

May reply to @krystian3w that say "_having a per-line filter change will be cleaner for list maintainers_".

> Maybe GitHub failure.

It's possible.

> I see no smed79 comment.

Sorry and thank you for your time.

**Comment by okiehsch** [comment]
No comment has been deleted by any user or admin in the last 24 hours, so this seems to be a Github issue.
![image](https://user-images.githubusercontent.com/16838044/49472321-6fe0c700-f80f-11e8-9e47-c424275223bf.png)

**Comment by krystian3w** [comment]
As long as they cut out only one element, for me they do not disturb development, IMO.
