### ISSUE TITLE
brackets.dnbard.com fraud website

### ISSUE THREAD

**Issue by ArtemBernatskyy** [uBlockOrigin/uAssets#4236]
Hi, brackets.dnbard.com from time to time redirects to some fraud websites 

How to reproduce (at least for my google search bubble)

Visit this [google search](https://www.google.com/search?client=safari&rls=en&ei=AJIDXNLrMsrKrgSyj7vQBw&q=utf+8+chemical+brackets&oq=utf+8+chemical+brackets&gs_l=psy-ab.3..33i22i29i30l10.118054.118281..118459...0.0..0.82.160.2......0....1..gws-wiz.......0i71.1VKNX6OHiWA) or google for `utf 8 chemical brackets`.
Click on brackets.dnbard.com/extension/** website

Website will mask itself by modifying history so you won't see google (via `window.location.replace('http://hidereferrer.com')`)

Testes on MacOS Safari

**Comment by mapx-** [comment]
You provided the "virus website" but not the original page where you get the redirects !?

**Comment by ArtemBernatskyy** [comment]
@mapx- my bad, i've updated issue, feel free to ask for more details

**Comment by smed79** [comment]
`dnbard.com` is just a parked domain and not a "virus website" as said above.

other examples
```
camload.com
spanktube.com
bamholyland.com
ganadinerohoy.net
ganadinerohoy.net
wohapnasa.com
krosisfansub.com
mycodingtricks.com
alotamovies.info
...
```
I think that this issue have nothing to do with the purpose of the badware list.

**Comment by mapx-** [comment]
other examples of "virus" stuff, right ?
dnbard is - partially - infested by malware, so it's the reason to be in the list.
