### ISSUE TITLE
maketecheasier.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#424]
Hi,

**URL**

`https://www.maketecheasier.com/`

**Describe the issue**

sponsored post

**Screenshot**

* http://i.imgur.com/KVENUrP.png

**Versions**

uBlock Origin 1.12.4 / Chromium 58.

**Settings**

default settings

**Suggested filters**

`maketecheasier.com##ARTICLE[id^="post-"]:has(:scope > .entry-header + div + .sponsored_tag)`

**Additional filters for EL**

* https://forums.lanik.us/viewtopic.php?f=62&t=36931

**Comment by okiehsch** [comment]
@SMed79 why did you close?
Your filter works on my end, I didn't notice this issue until now, so if nothing breaks because of your filter
just reopen the issue and I will add your fix.

**Comment by SMed79** [comment]
Apologies, i said to myself that maybe something is wrong with my report and I did not want bump to say nothing.
