### ISSUE TITLE
mindgames.com + neongames.com + solitaireonline + classicgame.com + games-site.co.uk + timemanagementgame.com + actiongame.com + mahjong.com + match3games.com + hiddenobjectgames.com + brain-games.co.uk + mahjong.co.uk + match3.co.uk + neongames.co.uk [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4241]
URL(s) where the issue occurs

`https://www.mindgames.com/game/Word+Wipe`
`https://www.neongames.com/game/Halloween+Mahjong`
`https://www.solitaireonline.com/game/Kings+Klondike`
`https://www.classicgame.com/game/Disc+Pool+1+Player`
`https://www.games-site.co.uk/game/Super+Pon+Goal`
`https://www.timemanagementgame.com/game/Ice+Cream+Bar`
`https://www.actiongame.com/game/Bowling`
`https://www.mahjong.com/game/Flower+Mahjong+Connect`
`https://www.match3games.com/game/Neon+3`
`https://www.hiddenobjectgames.com/game/Circus+Hidden+Letters`
`https://www.brain-games.co.uk/game/2048+Solitaire`
`https://www.mahjong.co.uk/game/Mahjongg+Alchemy`
`https://www.match3.co.uk/game/Jungle+Legend`
`https://www.neongames.co.uk/game/Halloween+Connect`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.0

Settings

Default

**Comment by KiLL4FuNK** [comment]
PLAY

**Comment by mapx-** [comment]
test this filter for all those sites

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=actiongame.com|brain-games.co.uk|classicgame.com|games-site.co.uk|hiddenobjectgames.com|mahjong.co.uk|mahjong.com|match3.co.uk|match3games.com|mindgames.com|neongames.co.uk|neongames.com|solitaireonline.com|timemanagementgame.com`

**Comment by KiLL4FuNK** [comment]
IT WORKS PERFECT

**Comment by Daxy7** [comment]
AdBlock Detected Annoyance for all the websites listed above,

`actiongame.com,brain-games.co.uk,classicgame.com,games-site.co.uk,hiddenobjectgames.com,mahjong.co.uk,mahjong.com,match3.co.uk,match3games.com,mindgames.com,neongames.co.uk,neongames.com,solitaireonline.com,timemanagementgame.com##.adBlocked,.banner`

**Comment by Daxy7** [comment]
@mapx-
