### ISSUE TITLE
https://www.denofgeek.com/

### ISSUE THREAD

**Issue by xisini** [uBlockOrigin/uAssets#4243]
### URL(s) where the issue occurs

`https://www.denofgeek.com/movies/movie-posters/where-do-movie-poster-quotes-come-from`

### Describe the issue

Site detects ad blocker and redirects you to another site.

### Screenshot(s)

![adblocker](https://user-images.githubusercontent.com/24823324/49366508-86e1c500-f6fa-11e8-902c-0324ee8547dc.JPG)
`

### Versions

- Browser/version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.17.0

### Settings

filters i use

TUR: Adguard Turkish Filter​​​​​
uBlock filters​​​​​10,752 used out of 10,754​​​​
uBlock filters – Badware risks​​​​​47 used out of 47​​​​
uBlock filters – Experimental​​​​​6 used out of 6​​​​
uBlock filters – Privacy​​​​​147 used out of 148​​​​
uBlock filters – Resource abuse​​​​​286 used out of 287​​​​
uBlock filters – Unbreak​​​​​683 used out of 685​​​​
Adblock Warning Removal List​​​​​592 used out of 599​​​​
EasyList​​​​​85,925 used out of 86,098​​​​
EasyPrivacy​​​​​15,642 used out of 15,833​​
Malware Domain List​​​​​1,095 used out of 1,110​​​​
Malware domains​​​​​26,858 used out of 26,858​​​​
Peter Lowe’s Ad and tracking server list​​​​​2,925 used out of 2,926​​​​
AakList (Anti-Adblock Killer)​​​​​2,105 used out of 2,178​​​​

### Notes
Sometimes site doesn't recognise adblocker you have to refresh it to capture

**Comment by uBlock-user** [comment]
Cannot preoduce. Already patched by uBlock Filters.
