### ISSUE TITLE
sexodx.com (NSFW) (anti-adblock)

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#4247]
### URL(s) where the issue occurs

`[sexodx.com]`

### Describe the issue

[A message appears in the video player telling you to disable adblock to watch the video.]

### Versions

- Browser/version: [Firefox Android v63]
- uBlock Origin version: [1.17.4]

### Settings

- [default]

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
