### ISSUE TITLE
Adblock Protector changed name and url

### ISSUE THREAD

**Issue by ale5000-git** [uBlockOrigin/uAssets#425]
### URL(s) where the issue occurs

Ref: `https://github.com/jspenguin2017/uBlockProtector/issues/237`

### Describe the issue

Adblock Protector List changed name and url so update no longer work

### Versions

- Browser/version: Google Chrome 58.0.3029.110 (64-bit)
- uBlock Origin version: 1.12.4

### Settings

- Enabled Adblock Protector List, Adblock Warning Removal List​ and Anti-Adblock Killer

### Notes

`https://github.com/jspenguin2017/AdBlockProtector` redirect to `https://github.com/jspenguin2017/uBlockProtector`.

**Comment by SMed79** [comment]
https://github.com/uBlockOrigin/uAssets/issues/419#issuecomment-304120845

**Comment by gorhill** [comment]
This was fixed days ago with 0ae695f8b1ac595e536a9a69dda86240e21d37dc.
