### ISSUE TITLE
Add Fandom/Wikia Featured Videos to filter

### ISSUE THREAD

**Issue by joootdooot** [uBlockOrigin/uAssets#4256]
### URL(s) where the issue occurs
This page has a list of fandom/wikia pages that have video ads, for the warframe fandom:
`https://warframe.fandom.com/wiki/Category:FANDOM_Video`

### Describe the issue

Fandom/Wikia runs videos on select wikia pages. They profit from the pre-roll ads, and the video content is supposed to be relevant to the page. As the videos are added by Fandom/Wikia and not the wiki community, they are often outdated and without value even after the pre-roll ads have been blocked by uBO. The video frame should be treated as an ad, and blocked.

### Settings
This filter works on all fandoms, not just warframe:
`fandom.com##.featured-video`

### Notes

The main issue for argument is that the videos are not ads per se, but as I mentioned it is added by Fandom/Wikia for monetization, and not curated by the wiki community.

**Comment by mapx-** [comment]
eventually for easylist ?!
@ryanbr

**Comment by okiehsch** [comment]
> The video frame should be treated as an ad, and blocked.

I disagree, how can the video - without the blocked pre-roll ad - be considered an ad?
What is it advertising beyond the topic it describes, I take your point that the information may be outdated or withot value, but even though it at best an annoyance and not an ad in my opinion.

**Comment by okiehsch** [comment]
@joootdooot this should be fixed with `fandom.com##.featured-video__wrapper`,
which is now part of `uBO-annoyances`.
