### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by zoron1** [uBlockOrigin/uAssets#426]
bild.de blocks ublock origin use. Starting this morning bild.de has implemented antiadblock with ublock origin.

bild.de

![image](https://cloud.githubusercontent.com/assets/22475607/26554739/cad4ad44-445f-11e7-9085-69b0ac7c208f.png)

1. go to bild.de. Access is blocked.
2. No issues until yesterday with ublock origin. 
3. Adblock plus has been broken for a long time- not ublock origin.
4. Bild.de block message specifically mentions ublock origin. It's in German but you can see it in the second line from bottom
5. I have tried disabling individual 3rd party filter lists, no success
6. Therefore this issue must be elsewhere
7. I have custom filter @@||bild.de^$generichide

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Mac OSX 10.12.5
- Chrome Version 58.0.3029.110
- uBlock Origin version: 1.12.4

##### Your filter lists
uBlock filters​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
uBlock filters – Unbreak
Adblock Warning Removal List
Anti-Adblock Killer | Reek
EasyList​
EasyPrivacy
Malware Domain List
Malware domains

##### Your custom filters (if any)
@@||bild.de^$generichide

**Comment by DarkBlueSkyy** [comment]
I have exactly the same problem with Bild.de since TODAY! :-(
I hope there will be a fix for this site very quickly, because I visit it daily...

![image](https://cloud.githubusercontent.com/assets/29045210/26555696/b5fca944-4496-11e7-9209-0ed266452419.png)

**Comment by zoron1** [comment]
THANK YOU!
