### ISSUE TITLE
Remove links to the scammers' repository

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4264]
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt , and likely other lists, have old links that point to the repository owned by the scammers who kept the original repository and are still profiting from it. 

Replace those with in-line explanations for the filters.

**Comment by mapx-** [comment]
meaning `github.com/chrisaljoudi/uBlock` ?

**Comment by okiehsch** [comment]
They point to links of the fixed issues. Those issues were opened at a time of gorhill's ownership and are clearly still relevant.

**Comment by adranger** [comment]
Like I said, the "clearly relevant" information can be added in-line or elsewhere else.

People seeing the links won't know the history and will assume they have some credit or reputation. 

It's interesting how fast you close issues that other people like @mapx-  are still considering or discussing.

@gorhill

**Comment by okiehsch** [comment]
I close issues I consider invalid. If you are offended by the speed I do this I apologize.

**Comment by okiehsch** [comment]
> People seeing the links won't know the history and will assume they have some credit or reputation, and may end up on their donation pages.

We block their donation page, so even if the user is combing through the `filters.txt` fie and is interested enough to open the links that point to the "dubious" repo and then tries to go their donation page all he/she see is 
![image](https://user-images.githubusercontent.com/16838044/49548812-2e234f80-f8e7-11e8-9e2e-964fb5c9602b.png)
If the same curious user is then going through `badware.txt` he/she will find
`https://github.com/gorhill/uBlock/wiki/Badware-risks#ublockorg`

**Comment by gorhill** [comment]
I have use these links (in filter lists or code) myself for reference in the past when not remembering the details of issues, so we can't remove them. Removing those links is not going to accomplish much really. What accomplish something is just to remind people that this is a sleazy fork whenever there is confusion about this.

In any case, if there is a way I could import these issues into a repo created just for this, that could be a solution. This would take care of the worry that whoever is behind uBlock-LLC could at any time take out the repo and we would lose useful history of the project. I don't know if importing is feasible though.

**Comment by uBlock-user** [comment]
> In any case, if there is a way I could import these issues into a repo created just for this, that could be a solution.

AFAIK, the only way possible right now is for uBlock-LLC to willingly transfer issues one by one to this repo.
