### ISSUE TITLE
uBlock filters – Annoyances​​​​​ result in pinterest's login box cannot shown

### ISSUE THREAD

**Issue by waldens** [uBlockOrigin/uAssets#4267]
### URL(s) where the issue occurs

`https://www.pinterest.com/pin/462956036673734613/`

### Describe the issue

When the `uBlock filters – Annoyances​​​​​` rule is enabled in uBlock origin, clicking the login button (not the Google login button!) in upper right of the page cannot summon the login box.

And if I disable the rule "uBlock filters – Annoyances​​​​​", everything works normal.

### Screenshot(s)

![](https://i.loli.net/2018/12/06/5c08920e35f66.png)
![](https://i.loli.net/2018/12/06/5c08918dda09c.png)
![](https://i.loli.net/2018/12/06/5c089237abf42.png)
![](https://i.loli.net/2018/12/06/5c0892bc01baf.png)

### Versions

- Browser/version: Cent Browser 3.7.2.33 (portable) (Chromium 70.0.3538.110)
- uBlock Origin version: 1.17.0

**Comment by okiehsch** [comment]
Adding `pinterest.*#@#.FullPageModal__scroller` to your fiter list should fix your issue.
I will remove the filter from `uBO-annoyances`.
