### ISSUE TITLE
Update annoyances filter for FANDOM url change

### ISSUE THREAD

**Issue by jaydenkieran** [uBlockOrigin/uAssets#4269]
### URL(s) where the issue occurs

`https://runescape.fandom.com/wiki/Money_making_guide`

### Describe the issue

Follow up to #1532. Wikia wikis are being migrated to a new URL, so we need to add the new URL to the existing annoyances filter.

**Comment by jaydenkieran** [comment]
Thanks @mapx-

**Comment by krystian3w** [comment]
@mapx- again combine per domain into one cosmetic filter.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L179
