### ISSUE TITLE
mycouchtuner.city

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#427]
http://mycouchtuner.city/1/vikings-s4-e20-the-reckoning/
When the video is playing, and you skip through the time or enlarge it to full screen, there's a bunch of pop up windows and tabs that try to open and then are closed, but it's annoying. Also, because of all the pop ups, if you try to view the video in full screen it doesn't change to full screen after you click the full screen button.

![couchtuner](https://cloud.githubusercontent.com/assets/26278182/26599377/6e87b53a-4546-11e7-87b3-e0fb01eedeb4.jpg)

Firefox 53.0.3 (32-bit)
uBlock Origin 1.12.1
Greasemonkey 3.11
Anti-Adblock Killer 10.0

"Show the number of blocked requests on the icon" disabled, "I am an advanced user" enabled.

Interestingly enough, when you go to the same website link with the Firefox Developer Edition 54.0a2 (2017-04-18) (32-bit) there's no pop ups and everything plays properly.

**Comment by okiehsch** [comment]
I can't reproduce with uBlock Origin 1.12.4 and default settings.
No popups with Firefox 53 or Chrome 58 and no problem changing to full screen.

**Comment by SMed79** [comment]
No issue here.

@js017 test in [firefox portable](https://portableapps.com/apps/internet/firefox_portable) with only uBo installed.

**Comment by js017** [comment]
Thanks for the reply. I updated the filters and it works now.

**Comment by js017** [comment]
Thanks for the reply. I updated the filters and it works now
