### ISSUE TITLE
torrentz2.eu, torrentz2.is | Ads

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4272]
### URL(s) where the issue occurs

`https://torrentz2.eu`

`https://www.torrentz2.is`

### Describe the issue

Search for anything. A `Sponsored Links` section shows up above search results. Click on a result. Above the result content there's a VPN ad section containing `Protect your privacy` link button.

### Versions

- Browser/version: Firefox 63.0.3
- uBlock Origin version: 1.17.4

### Settings

Default + Adguard Mobile Filters

### Notes

The `Sponsored Links` section contains links which are detected and blocked by Adguard Mobile Filters.

**Comment by in4u** [comment]
@mapx- The second filter `torrentz2.*##.alert--danger.alert` is no longer hiding the VPN ad. Perhaps it should be updated as `torrentz2.*##.alert--danger`.

**Comment by in4u** [comment]
Please replace `.eu` with `.*` so that the mirror `.is` domain is also covered.

**Comment by mapx-** [comment]
right, fixed

**Comment by in4u** [comment]
One more thing... wouldn't this filter also block all search results with the text `privacy`?

**Comment by in4u** [comment]
Thanks for the fix! Although I think it can be made more specific with something like `torrentz2.*##.alert--danger:has-text(/Protect your privacy/i)` so that search results aren't touched at all.
