### ISSUE TITLE
Anti adblocker not working on Life Selector

### ISSUE THREAD

**Issue by pijcab** [uBlockOrigin/uAssets#4278]
### URL(s) where the issue occurs

**[NSFW]** `https://lifeselector.com/`

### Describe the issue

Anti Adblocker

### Screenshot(s)

**[NSFW]** `https://imgur.com/a/1r0Rvt4`

### Versions

- Browser/version: Chrome Version _70.0.3538.110_
- uBlock Origin version: _v1.17.4_

### Settings

- Followed the Nano Defender extention's instructions to make it work with uBlock : `https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin`

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock, but I'm getting ads.

**Comment by okiehsch** [comment]
I get a push notification, but no obvious ads.

**Comment by okiehsch** [comment]
The "one time offers" are self-promotion.

**Comment by jspenguin2017** [comment]
If you click the big pictures, it starts to play a video that sounds like ads, but considering the context, I think they can count as self-promotion.

**Comment by pijcab** [comment]
@okiehsch i don't really know how to respond, I'm not familier with ads and adb scripts...

I can access the site while having uBlock on if I deactivate javascripts but that's about it

**Comment by okiehsch** [comment]
> can you tell me how u got it to work (your nano defender settings) ?

Well, seeing as the author of nano defender - **jspenguin2017** - can't reproduce I think it is safe to assume that it works with a default setup.
I can say that it also works with a default setup using `uBlock Origin`. 

Post your logger output of `https://lifeselector.com/`

- Open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger)

- Load `https://lifeselector.com/`

- Type `adb` in the "filter log entries" box

**Comment by pijcab** [comment]
@okiehsch here's what I get : 

![image](https://user-images.githubusercontent.com/25269430/49834975-1c85f000-fd9e-11e8-8c9f-fe098ce20e58.png)

I also have the default setup, or I think I do. I've followed the tutorial given at `https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin`

Even with adbd.js blocked, the page detects that I have an ad block on

**Comment by okiehsch** [comment]
If youclick the adbd.js entry on the left

**Comment by okiehsch** [comment]
> Even with adbd.js blocked, the page detects that I have an ad block on

Blocking the request causes the adblock detection.
Add
`@@||img.lifeselector.com/js/adbd.js$script,first-party`
to your filter list.

**Comment by pijcab** [comment]
Oh wow good job my friend...
