### ISSUE TITLE
cineblog.it

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#428]
Hi,

**URL**

`http://www.cineblog.it/post/751237/wonder-woman-recensione-in-anteprima`

**Describe the issue**

Sponsored content

**Screenshot**

* http://i.imgur.com/P6XPW79.png

**Versions**

uBlock Origin 1.12.5.17 / Chromium 58.0.3029.110

**Settings**

default settings

**Suggested filters**

`||cineblog.it^$csp=script-src 'self' * 'unsafe-inline'`

**EL**

* https://forums.lanik.us/viewtopic.php?p=118814

**Comment by okiehsch** [comment]
Does `cineblog.it##script:inject(noeval.js)` work for you?
It works on my end and I think it would be the preferable solution, atleast until the static network filter option: `csp=` has reached uBO-stable.
@gorhill what is your prefered solution if `script:inject(noeval.js)` and `csp=` work?

**Comment by SMed79** [comment]
Maybe `cineblog.it##script:inject(abort-on-property-write.js, upManager)`

**Comment by gorhill** [comment]
`noeval.js` is preferred if it works, until 1.12.5 is shipped and widespread.

**Comment by okiehsch** [comment]
`cineblog.it##script:inject(abort-on-property-write.js, upManager)` does not work with Chrome on my end.
@SMed79 ff `cineblog.it##script:inject(noeval.js)` works for you I will add it.

**Comment by mapx-** [comment]
noeval is working fine.
