### ISSUE TITLE
koozi.info

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#4286]
https://github.com/easylist/EasyListHebrew/issues/304
more info: https://github.com/AdguardTeam/AdguardFilters/issues/26416

**Comment by mapx-** [comment]
uBo translates those filters in
```
koozi.info##.tien-ads-video > div#player:style(visibility: visible!important;)
koozi.info##.tien-ads-video:style(background: none!important;)
```
does not work for you ?

**Comment by IsraeliUser** [comment]
@MrTal
Please try it in uBlock Origin.

**Comment by MrTal** [comment]
@IsraeliUser 
i use with adguard and work for me this filter:

> koozi.info#$#.tien-ads-video > div#player { visibility: visible!important; }
> koozi.info#$#.tien-ads-video { background: none!important; }

**Comment by okiehsch** [comment]
@IsraeliUser 
You could add
````
koozi.info#$#.tien-ads-video > div#player { visibility: visible!important; }
koozi.info#$#.tien-ads-video { background: none!important; }
````
to `EasyList Hebrew`, that way the fix works for Adguard and uBlock Origin users o your list.

**Comment by IsraeliUser** [comment]
@okiehsch 
Added.
I guess you meant
```
koozi.info##.tien-ads-video > div#player:style(visibility: visible!important;)
koozi.info##.tien-ads-video:style(background: none!important;)
```

**Comment by okiehsch** [comment]
It does not matter for uBO,
````
koozi.info#$#.tien-ads-video > div#player { visibility: visible!important; }
koozi.info#$#.tien-ads-video { background: none!important; }
````
would **not** be discarded, it would be translated to the filters you added.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/49761132-71eece00-fcc6-11e8-9a80-a08fd1397ae4.png)
