### ISSUE TITLE
walla.co.il - Chrome

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#4287]
Default settings + EasyList Hebrew
Ads are currently hidden (not blocked) by EasyList Hebrew ( https://github.com/easylist/EasyListHebrew/commit/86099f4d7e7c5d8404ae8e323c1f05e59a67968c ) with some false positives. ( https://github.com/easylist/EasyListHebrew/issues/305 )
Any suggestions?

**Comment by IsraeliUser** [comment]
No.
More info: https://github.com/AdguardTeam/AdguardFilters/issues/26111

**Comment by okiehsch** [comment]
https://github.com/easylist/EasyListHebrew/issues/305
I can't reproduce, the videos play without issue on my end.

For reference, if I go to `https://news.walla.co.il/item/3206242` the video plays fine, what is broken on that site?
I have enabled `EasyList Hebrew`.

**Comment by IsraeliUser** [comment]
using Chrome?
How does uBO translate those filters:
```
walla.co.il#%#window.atob = function() { };
walla.co.il#%#AG_abortInlineScript(/TextDecoder/, 'atob');
```
?

**Comment by okiehsch** [comment]
Yes, using Chrome.
![image](https://user-images.githubusercontent.com/16838044/49755297-c723e300-fcb8-11e8-8f8c-b33c727db3b8.png)


It does not translate those, they will be discarded.
`walla.co.il#%#AG_abortInlineScript(/TextDecoder/, 'atob')`
is the equivalent of the uBO-filter `walla.co.il##+js(abort-current-inline-script.js, atob, TextDecoder)`
which is already part of `EasyList Hebrew`

**Comment by IsraeliUser** [comment]
I know uBO doesn't support this syntax. I meant to ask what is the equivalent.

**Comment by gorhill** [comment]
> please correct me if I am wrong

Yes, your filter seems right.

**Comment by IsraeliUser** [comment]
Ads are back.
[Chrome]
@okiehsch 
@mapx-

**Comment by mapx-** [comment]
test these filters
```
||exposeboxwallashops.blob.core.windows.net^
||walla.yad2.co.il/*banner$subdocument,domain=walla.co.il
walla.co.il##+js(abort-current-inline-script.js, decodeURIComponent, encodeURIComponent)
```

**Comment by IsraeliUser** [comment]
Ads are still there. [Chrome]
Wait about 30 seconds after the page loaded...

What is the equivalent of 
`walla.co.il$$script[tag-content="JorLoad"][min-length="50000"][max-length="150000"]`
in uBlock Origin? More info: https://github.com/AdguardTeam/AdguardFilters/issues/27607

@okiehsch 
@mapx-

**Comment by mapx-** [comment]
I guess it worked for a while, I didn't get any feedback from you.

Test now and report back:
`walla.co.il##+js(setTimeout-defuser.js, (), 1500)`

**Comment by mapx-** [comment]
AS for
`walla.co.il$$script[tag-content="JorLoad"][min-length="50000"][max-length="150000"]`

it's html filtering, so ..not working in chrome.

I still don't understand how is working for MrTal that rule ..

**Comment by MrTal** [comment]
@mapx- 
i use in AdGuard and this rule work for me in chrome and i dont see now ads with the rule this in chrome and AdGuard

**Comment by mapx-** [comment]
adguard extension in chrome, right ? or adguard standalone in windows ?

**Comment by MrTal** [comment]
@mapx- 
adguard standalone in windows

**Comment by mapx-** [comment]
well, well ... html filtering is available only in adguard extension for firefox or as standalone (paid version) in windows. Now is all clear.

**Comment by MrTal** [comment]
@mapx- 
ahh, ok.

**Comment by MrTal** [comment]
@IsraeliUser 
@mapx- 
the ads back again!
also adguard and also uBlock (i try disable adguard and enable uBlock and also uBlock have ads)!
https://image.prntscr.com/image/-4WMTq5USZ6XCMP4S--NLg.png
https://image.prntscr.com/image/BdPwtF8QRcS9fl530IXTuw.png
http://prntscr.com/m3d4ns
http://prntscr.com/m3d57n
can you see here:
https://news.walla.co.il/item/3211101

**Comment by mapx-** [comment]
test this filter (breaking something ?)

`walla.co.il##+js(set-constant.js, String.fromCharCode, noopFunc)`

**Comment by MrTal** [comment]
@mapx- 
this not work...

**Comment by mapx-** [comment]
I get no ad using it. If I disable it => I get ads again.

**Comment by MrTal** [comment]
@mapx- 
yes, now i see this work with uBlock and no have ads with filter this, tank you.
every week have new problem with and site this and the ads back to site this...

**Comment by krystian3w** [comment]
> `walla.co.il$$script[tag-content="JorLoad"][min-length="50000"][max-length="150000"]`

`walla.co.il##^script:has-text(JorLoad)` and uBO no have method count characters in `<script>`.

**Comment by krystian3w** [comment]
@gorhill  possible add `:max-text-length(x)`?

Should be better as me "invalid" regex.

**Comment by gorhill** [comment]
Is the max length **really** needed for the filter to work properly?

**Comment by krystian3w** [comment]
AdGuard to be on the safe side,  so it often narrows the limit from two sides.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1556
