### ISSUE TITLE
Sponsored Stuff on Futurezone

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#429]
### URL(s) where the issue occurs

https://futurezone.at/

### Describe the issue

The site has sponsored posts marked by light grey and a "powered by" tag in the picture.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]
![grafik](https://cloud.githubusercontent.com/assets/17909/26623640/9fea344c-45ee-11e7-83e6-c06a74993079.png)

**Comment by gorhill** [comment]
How about:

    futurezone.at##.type-content-box:has(.poweredby)
    futurezone.at##.type-box:has(#paidcontentslider)

**Comment by okiehsch** [comment]
FYI, it fixes the issue on my end.
