### ISSUE TITLE
ani.gamer.com.tw [Preroll Video Ads]

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#4290]
Reproduced this issue need a VPN via Taiwan
URL: https://ani.gamer.com.tw/animeVideo.php?sn=11161
![image](https://user-images.githubusercontent.com/45059308/49776223-10fede80-fd36-11e8-80b4-4cb88340dfdb.png)

**Comment by discusssth** [comment]
@mapx-  @okiehsch 
need help

**Comment by mapx-** [comment]
> need a VPN via Taiwan

If still neeeding that vpn we cannot help you.

**Comment by mapx-** [comment]
send it here:
`axis.trivia@gmail.com`

**Comment by mapx-** [comment]
well, I get no way to stop the preroll (without breaking the player)

**Comment by discusssth** [comment]
Please think more about it.

**Comment by discusssth** [comment]
@LiCybora  need you , help

**Comment by LiCybora** [comment]
I don't have TW VPN. If you are willing to provide, email to nanodefendertester@gmail.com

**Comment by discusssth** [comment]
@LiCybora   The VPN has been sent in the past, please check your mail inbox.

**Comment by mapx-** [comment]
@discusssth  send it to that address above

**Comment by discusssth** [comment]
@mapx-  what？

**Comment by discusssth** [comment]
I have already sent the VPN to the mailbox of LiCybora.

**Comment by mapx-** [comment]
ah, ok.

**Comment by LiCybora** [comment]
TBH, I cannot think of any pure filter solution in this moment. The site almost check every xhr parameter and verify on server side. It is almost, if not exactly yet, SSAI. Any attempt to redirect or modify will result error response from server and abort the video playback.

The only trick I can do is mod the player's code to reduce the wait time to several seconds, and auto skip ads when timer end. However, it is only possible in Firefox with Nano Defender and I need to deal with a browser bug first before the solution works, or else you will have to clean cache every time which is undesired.

**Comment by discusssth** [comment]
Does anyone need a Taiwan VPN? Leave the mailbox, I will provide it.

**Comment by jspenguin2017** [comment]
Just get Hola for unblocking: https://chrome.google.com/webstore/detail/hola-free-vpn-proxy-unblo/gkojfkhlekighikafcpjkiklfbnlmeio

Also fix is possible for all platforms, no privileged code required. Technically it can be implemented as a scriptlet, but it's kind of big.

**Comment by mapx-** [comment]
closing => fixed in Nano Defender

**Comment by discusssth** [comment]
Is there a way to synchronize this update to ublock?     
@gorhill
