### ISSUE TITLE
v.qq.com [anti adblock]

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#4293]
URL： `https://v.qq.com/x/cover/3hcdu70po7fiuph/i0811lpp5fb.html`
![image](https://user-images.githubusercontent.com/45059308/49777826-0eec4e00-fd3d-11e8-9871-aeeefb6aa6fe.png)

my-ublock-backup:[my-ublock-backup_2018-12-11_11.36.46.txt](https://github.com/uBlockOrigin/uAssets/files/2665914/my-ublock-backup_2018-12-11_11.36.46.txt)

**Comment by mapx-** [comment]
I cannot reproduce the issue using the default setup (+ the 2 chinese lists)

**Comment by discusssth** [comment]
try
https://v.qq.com/x/cover/xn14uorgt5bvd0j/q0029lg9tzt.html

**Comment by mapx-** [comment]
waiting 44 seconds then the video is running ok

**Comment by mapx-** [comment]
try (with and without the chinese lists)

```
/variety.tc.qq.com/*.mp4$media,redirect=noopmp4-1s,domain=v.qq.com
://apd-*.qq.com/$media,redirect=noopmp4-1s,domain=v.qq.com
/vlive.qqvideo.tc.qq.com/*.mp4?*sdtfrom=&$media,redirect=noopmp4-1s,domain=v.qq.com

```

**Comment by discusssth** [comment]
no work.....

**Comment by discusssth** [comment]
no work （with and without the chinese lists）

**Comment by mapx-** [comment]
meaning you still get anti adblock stuff or the preroll ?

**Comment by discusssth** [comment]
![image](https://user-images.githubusercontent.com/45059308/49788840-5e467480-fd65-11e8-9ae2-dbea740a40d3.png)

**Comment by discusssth** [comment]
@mapx-  
yes, still get anti adblock stuff and the preroll

**Comment by mapx-** [comment]
@jspenguin2017  maybe is the same as `iqiyi.com` ?

**Comment by jspenguin2017** [comment]
Looks similar, but Tencent and Baidu (who owns iQiyi) are not the same company. I would assume the technology they are using are different.

**Comment by mapx-** [comment]
...now I get no waiting sequence (no custom filters added)

**Comment by okiehsch** [comment]
I now get this new "thing".
![image](https://user-images.githubusercontent.com/16838044/49972516-3fe1a400-ff32-11e8-8b74-346f833dbb9c.png)

**Comment by jspenguin2017** [comment]
@mapx- I guess it only happens sometimes.

**Comment by jspenguin2017** [comment]
@okiehsch It's just a network error. It should be gone if you refresh.

**Comment by okiehsch** [comment]
Yes, after I refresh I can play the video without issue.

**Comment by okiehsch** [comment]
@mapx- 
````
/variety.tc.qq.com/*.mp4$media,redirect=noopmp4-1s,domain=v.qq.com
://apd-*.qq.com/$media,redirect=noopmp4-1s,domain=v.qq.com
/vlive.qqvideo.tc.qq.com/*.mp4?*sdtfrom=&$media,redirect=noopmp4-1s,domain=v.qq.com
`````
will not result in a redirection,  the filter must start with `||` or `*`, otherwise no redirection will occur, although a blocking filter will be created.

**Comment by mapx-** [comment]
oh, so 
```
*/variety.tc.qq.com/*.mp4$media,redirect=noopmp4-1s,domain=v.qq.com
*://apd-*.qq.com/$media,redirect=noopmp4-1s,domain=v.qq.com
*/vlive.qqvideo.tc.qq.com/*.mp4?*sdtfrom=&$media,redirect=noopmp4-1s,domain=v.qq.com
```

However - now - I get only network errors (with / without any custom filter)

**Comment by okiehsch** [comment]
Well, now I can't reproduce again, great .....
@jspenguin2017 can you test if 
`v.qq.com##+js(nano-setInterval-booster.js)` works for you?

**Comment by jspenguin2017** [comment]
That breaks the player.

**Comment by discusssth** [comment]
@LiCybora  need help

**Comment by LiCybora** [comment]
Redirect not work as they verify all video ads information, such as resolution, url and md5, and timer boost break the playback. I am unwilling to spend time on this nasty site.

If you are willing to use Firefox with Nano Defender, I do have a simple solution (Not work for Chrome/ium due to lacking [StreamFilter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/StreamFilter)).

**Comment by jspenguin2017** [comment]
Looks like the request is a normal XHR, in that case, `a.replaceXHR` is enough to deal with it. It works for all platforms.

**Comment by LiCybora** [comment]
Not really...
![image](https://user-images.githubusercontent.com/40160522/53466003-0fb69580-3a8b-11e9-8e47-99cb2ff9f59d.png)

**Comment by jspenguin2017** [comment]
That's weird... Are you getting POST or JSONP for the requests? It's POST for me on both Chrome and Firefox. 
![image](https://user-images.githubusercontent.com/7283682/53466416-1a334980-3a0f-11e9-80dd-c7225353dcfe.png)

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/53466493-2b22a000-3a8d-11e9-8b6c-e2c05f9e80d0.png)
How come all are GET on my end...?

**Comment by jspenguin2017** [comment]
Are you on Nightly? Can you try a clean install of Firefox stable?

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/53466627-ca479780-3a8d-11e9-8e83-918277453ed0.png)
Clean Firefox Stable now, still GET.

**Comment by jspenguin2017** [comment]
Oh, good catch! I'll add an integration filter rule.

**Comment by jspenguin2017** [comment]
OK, should be good now. Can you verify?

**Comment by LiCybora** [comment]
Yes, it is good now.

**Comment by discusssth** [comment]
![image](https://user-images.githubusercontent.com/45059308/69594230-a920d100-1036-11ea-9d24-bcc2491935ee.png)

https://v.qq.com/x/cover/rdo2y7q0dwmiaxw.html

pre-roll video ad
