### ISSUE TITLE
FMovies - Popups

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#4294]
### URL(s) where the issue occurs

Any page on `https://www4.fmovies.to`

### Describe the issue

Click any link and you'll get a new tab with the page you clicked on, with the other tab going to a different site potentially for a redirect elsewhere (example: `graftaub.com`). Similar to #3764 and maybe #3992.

### Screenshot(s)

If the other 2 issues were easily described without a picture, then this one should also.

### Versions

- Browser/version: Firefox 64.0
- uBlock Origin version: 1.17.4

### Settings

My list of filters (I think I go too overkill on these, and I pretty much copy-paste these at this point):

    uBlock Filters (all except annoyances and experimental)
    AdBlock Warning Removal List
    AdGuard Base Filters
    EasyList
    AdGuard Spyware Filters
    EasyPrivacy
    Malware Domain list
    Malware domains
    Spam404
    Adguard's Annoyance List
    Fanboy's Annoyance List
    Fanboy's Anti-Thirdparty Social (it's actually the anti-facebook list now...)
    Fanboy's Social Blocking List
    Peter Lowe's Ad and tracking server list

### Notes

I'm just going to put some URL's that might be relevant to this:

- latchemt.top (not blocked by default)
- graftaub.com (easylist blocks this one)
- eseecmoa.com (easylist blocks this one also)

Every time I click a link, it always seems to go to `graftaub.com` for the redirect.

**Comment by ghajini** [comment]
Still see video ads although some time is reduced from 30 sec to 5sec for waiting period....also skip button appears after 5 sec

**Comment by okiehsch** [comment]
I can't test with android, what about blocking the whole domain?
`||loadshare.org^$domain=fmovies.cab`

**Comment by okiehsch** [comment]
You have to remove the redirect filter to test.
`||loadshare.org/custom/*$media,redirect=noopmp4-1s,domain=fmovies.cab,badfilter`

**Comment by ghajini** [comment]
Seems
`||loadshare.org^$domain=fmovies.cab`
not a good idea as `loadshare` is used to play actual video and breaks video.....following partially works as `loading ad` flashes for 1 sec followed by actual video
||stream-*.loadshare.org/custom/*$media,domain=fmovies.cab
That scripltlet filter partially works might be bug in filter
