### ISSUE TITLE
topsimages.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4295]
### URL(s) where the issue occurs

`https://www.topsimages.com/images/harlequin-tusk-teeth-45.html`

### Describe the issue

Click anywhere. Pop up.

### Notes

Pop up goes to `desiasm.club` which redirects to `ntsevolandsery.club` and clicking `Block` on request for notification access leads to never ending subdomain redirects.

**Comment by terrorist96** [comment]
Should we also deal with the specific link in case someone somehow manages to be sent to those links?
e.g.
```
https://uev4.ntsevolandsery.club/VOTJDBK?tag_id=758690&sub_id1=&sub_id2=2430519618192999393&cookie_id=aebe2440-789d-4d0b-a8ae-7269426408ae&lp=black_normal&tb=redirect&allb=redirect&ob=redirect&href=https%3A%2F%2Fdesiasm.club%2F%3Ftid%3D758690%26noocp%3D1&hop=3&sub=uev4
https://northeastapp.com/campaign/counttonight2/?ID=acsh18tc&sub=acsh18tc&subid=2177951&S2=15445052312906789399213433451210877&SUTM=520625
```

**Comment by terrorist96** [comment]
> Should we also deal with the specific link in case someone somehow manages to be sent to those links?
> e.g.
> 
> ```
> https://uev4.ntsevolandsery.club/VOTJDBK?tag_id=758690&sub_id1=&sub_id2=2430519618192999393&cookie_id=aebe2440-789d-4d0b-a8ae-7269426408ae&lp=black_normal&tb=redirect&allb=redirect&ob=redirect&href=https%3A%2F%2Fdesiasm.club%2F%3Ftid%3D758690%26noocp%3D1&hop=3&sub=uev4
> https://northeastapp.com/campaign/counttonight2/?ID=acsh18tc&sub=acsh18tc&subid=2177951&S2=15445052312906789399213433451210877&SUTM=520625
> ```

@mapx- what do you think?

**Comment by okiehsch** [comment]
If you think they should be added, then open a pull request and add them to the badware list under an „admaven“ entry.

**Comment by mapx-** [comment]
I guess there are hundreds, thousands of such fake domains, should go in malware domains list.
