### ISSUE TITLE
Twitter Pre-Video ads

### ISSUE THREAD

**Issue by jomo** [uBlockOrigin/uAssets#43]
### URL(s) where the issue occurs

`https://twitter.com/WIRED/status/729436240093708288`
### Describe the issue

Some Twitter videos have a video ad that plays before the actual video.
### Screenshot(s)

![Twitter video screenshot](https://i.imgur.com/5TpjcnV.png)
### Versions
- Browser/version: Firefox Developer Edition 48.0a2 (2016-05-08)
- uBlock Origin version: 1.7.5b1
### Notes

HTML:

``` html
<div class="player-wrapper">
  <div style="display: none;" class="video-display">
    <video class="paused" style="width: 100%; height: 100%;" src="https://snappytv-a.akamaihd.net/video/magnum/importasset/250363/clip/928000.mp4?token=1462748016_d83c69fb71ebf2845bf1f3af0357702f" data-type="content" preload="auto" data-id="content"></video>
  </div>
  <div style="display: block;" class="video-display">
    <video class="visible playing" style="width: 100%; height: 100%;" src="https://snappytv-a.akamaihd.net/video/magnum/importasset/249166/clip/928000.mp4?token=1462748007_3f5d6f8610bef4060edac0303f6e8729" data-type="ad" preload="auto" data-id="ad"></video>
  </div>
</div>
```

The ad video and the actual video URLs follow the same schema, making it hard to block the request.
Blocking `video[data-type="ad"]` simply renders the video black, it still plays with audio enabled.

The video is skippable by clicking on the 'Skip' button, which has an onclick event that calls `this.trigger('uiReportAdSkip')`.

**Comment by anewuser** [comment]
"This content is no longer available."

Can you post another link where you still get ads? If not, please close this issue.

**Comment by jomo** [comment]
Haven't seen any ads on Twitter videos for a while (with uBlock enabled).
