### ISSUE TITLE
mhtviewer.booogle.net

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#4301]
### URL(s) where the issue occurs

`http://mhtviewer.booogle.net/`

### Describe the issue

Try upload file on site in "`Drop a file here`" section.

samples: http://www.fileformat.info/format/mime-html/sample/index.htm

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/49841485-11d85480-fdb8-11e8-999a-a22727b9b86d.png)

### Versions

- Browser/version: Chrome 71/Firefox 63
- uBlock Origin version: uBO 1.17.4

### Settings

- uBO default

### Notes

`@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=mhtviewer.booogle.net`
`||googlesyndication.com^$badfilter`

should enough for my side.

**Comment by okiehsch** [comment]
Redirecting the request works on my end no need to allow it.
````
||pagead2.googlesyndication.com/pagead/show_ads.js$script,redirect=noopjs,domain=mhtviewer.booogle.net
````

**Comment by krystian3w** [comment]
report to Polish anti-adblock filter (to block all `||googlesyndication.com^`)?

**Comment by okiehsch** [comment]
`||googlesyndication.com^` is already part of Peter Lowes list, it is up to the polish list if it wants to include it too, but it is not necessary for `uBO-users`.

**Comment by krystian3w** [comment]
And maybe not, because you would have to pass in Adblock Plus and then for uBO / AdGuard, force blocking and I do not even know if the AdGuard has something like `noopjs`.

**Comment by krystian3w** [comment]
@mapx-  we can remove subdomain I found one more site:

`dicomviewer.booogle.net`
