### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#4314]
### URL(s) where the issue occurs

`https://www.youtube.com/`

### Describe the issue

The left hand side bar displays nothing no favourites list playlists anything because uBlock is blocking the element.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12204587/50020618-70771b80-ffce-11e8-8067-177c8a56fdd5.png)

### Versions

- Browser/version: Firefox Quantum latest
- uBlock Origin version: Latest

### Settings

Default.

### Notes

Disabling uBlock allows youtube to display the playlists etc on the left side again.

**Comment by mapx-** [comment]
see
https://github.com/uBlockOrigin/uBlock-issues/issues/340

even disabling uBo the issue is still reproducible (in firefox)
