### ISSUE TITLE
cmovies.io

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4317]
Should I report these small issues to easylist or not?
(I mean this case to be fixed by ubo extended syntax?)
### URL(s) where the issue occurs

`cmovies.io`

### Describe the issue

Ads

### Versions

- Browser/version: Firefox Android stable
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
It's about popups generated by inline-scripts.
Easylist cannot deal with them. 
ABP (with its special list) will deal in the future (I didn't see am equivalent of abort-current-inline-script.js )

**Comment by mapx-** [comment]
I see no ad chrome / FF, screenshot ?

**Comment by okiehsch** [comment]
It uses the `zmctrack.net` inline script, though right now it does not do anything on my end.
We can add 
`cmovies.io##+js(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)`
to abort the inline-script, that will also remove the `third-party` requests to `zmctrack.net` and `klcheck.com`.

**Comment by ghajini** [comment]
`https://cmovies.me/hd-online-silence/7UW6z`
Clicking on `skip ad` leads to popup ads
