### ISSUE TITLE
Filter Does Not Update

### ISSUE THREAD

**Issue by clementine123** [uBlockOrigin/uAssets#432]
Filters were added from filterlists.com and even after updating, it says out of date on some filters (with a triangle with an exclamation mark)

Screenshot: https://ibb.co/mqKtiF

Is this issue with filter or uBO?

**Comment by gorhill** [comment]
It shows network error, that's not uBO.

**Comment by SMed79** [comment]
@clementine123 try uninstall / reinstall your browser.
or test using **forefox** / **chrome** portable https://portableapps.com/apps/internet
also scan your system for malware and adware ([malwarebytes](https://www.malwarebytes.com/) (free) / [adwcleaner](https://www.malwarebytes.com/adwcleaner/)).

PS: _anyway, after closing... sorry for the noise._
