### ISSUE TITLE
movie sites ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4326]
### URL(s) where the issue occurs

`https://www.hindilinks4u.to/`
`https://mycoolmoviez.mobi/`
`http://www.moviespur.com`
`http://freeload.co/yms675/`
`https://zeefiles.download/c5221a880bad8c8d`
### Describe the issue

ads on clicking site anywhere
### Versions

- Browser/version: firefox 64
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings

### Notes

+ using decentraleyes

**Comment by ghajini** [comment]
similar sites, ads
`https://www2.todaypkfree.com/year/2018`
`https://worldfree2u.com/bhaiaji-superhit-2018-hindi-480p-hd-350mb-World4uFree/`
`https://movie2kfree.com`
`https://xmovies8net.org/watch/bumblebee-2018.html`
`https://movie25com.com`
`https://movie2khd.org/list/featured-movies.html`
`https://moviezxo.com`

**Comment by ghajini** [comment]
`https://mycoolmoviez.com/`
ads back

**Comment by ghajini** [comment]
Popup ads
`zeefiles.download/9f35a713c63842d8`

**Comment by ghajini** [comment]
`zeefiles.download/8a892df66c8cbd61`
Shady xhr's

**Comment by ghajini** [comment]
popup ads
`https://www.hindilinks4u.to/2019/07/arjun-patiala-2019.html`
`http://www.moviespur.com`
`https://mycoolmoviez.xyz/bollywood_movies/indias_most_wanted_(2019)/`

**Comment by mapx-** [comment]
no popup on `hindilinks4u`

**Comment by ghajini** [comment]
opera browser i can reproduce

**Comment by mapx-** [comment]
still nothing in opera too

**Comment by llacb47** [comment]
No popups on `mycoolmoviez`, but there are fake download buttons.

**Comment by ghajini** [comment]
`https://mycoolmoviez.top/animated_movies_(hindi)/madagascar_3:_europe_most_wanted_(2012)/`
Popups

**Comment by mapx-** [comment]
I cannot reproduce the issue

**Comment by ghajini** [comment]
`https://www.hindilinks4u.to/2019/08/batla-house-2019.html`
Player ver 1 (thevideobee)  don't play

**Comment by ghajini** [comment]
`zeefiles.*##+js(abort-current-inline-script, Math.sin, vocabulary)` can be removed

test link = `https://zeefiles.download/e2abd4dd75302a2f`
