### ISSUE TITLE
myanimelist.net - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#433]
Anti adb warnings are displayed on https://myanimelist.net.

**SS:** http://i.imgur.com/0BxRNug.jpg (Full page screenshot showing the warnings)
**Error URL:** https://myanimelist.net/

They seem to be using **BlockAdblock** (_FuckAdblock_) as can be seen in this js:
 https://myanimelist.cdn-dena.com/static/assets/js/pc/header-3f624289c4.js on the website.

**The adblock warning can be fixed by:**
`myanimelist.net##script:inject(fuckadblock.js-3.2.0)`

_**Note:** Using uBO 1.12.4 on Chrome 58 with default settings and filters._

**Comment by okiehsch** [comment]
I am not blocked from accessing the content, so think this should be classified as an annoyance.
 @gorhill  has stated that he 

> could create a "uBlock filters -- Annoyances" (optional) for cases which are fit for Fanboy Annoyances but can't be handled by it
https://github.com/uBlockOrigin/uAssets/issues/322#issuecomment-287567598

your fix works and could be added to such a list.

**Comment by gotitbro** [comment]
That is interesting. Adguard "**_Annoyances filter_**" also has a section for these types of anti adblock annoyances. 

Though it would be better if they listed it separately as well, I may not want to hide/remove general annoyances but I may be wanting not to see elements reminding I am using adblock.

**Comment by dimisa-RUAdList** [comment]
May be: `myanimelist.net##+js(abort-on-property-read.js, blockAdBlock)`?

**Comment by mapx-** [comment]
added as annoyance
https://github.com/uBlockOrigin/uAssets/commit/f7512a409de8c9d9ae7689dcf5b5d8bd8af9c879

**Comment by dimisa-RUAdList** [comment]
https://myanimelist.net/anime/38555
It seems the rule `@@||myanimelist.net^$ghide` is no longer required. In addition, it disables general antisocial rules such as `##.icon-social` (Fanboy’s Social).

**Comment by belnet** [comment]
please make corrections suggested **dimisa-RUAdList**.
TNX!

**Comment by mapx-** [comment]
removed
