### ISSUE TITLE
crisanimex.com [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4332]
URL(s) where the issue occurs

`https://crisanimex.com/boruto-naruto-next-generations-todos-los-capitulos-007-mega-mediafire-openload-zippyshare-actualizable/`

Describe the issue

Pop-up

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 70 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.4

Settings

Default

**Comment by mapx-** [comment]
@KiLL4FuNK  how can we reproduce the issue ? steps ?

**Comment by ghajini** [comment]
Click anywhere in the page
Setup-Firefox android ublock origin 1.17.4
![screenshot_2018-12-17-15-08-26-502_org mozilla firefox](https://user-images.githubusercontent.com/20338483/50078780-c40c8380-01df-11e9-8ee1-791f69f62fb7.png)

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by mapx-** [comment]
test
```
crisanimex.com##+js(abort-on-property-write.js, open)
||crykaxliilz.com^
```

**Comment by okiehsch** [comment]
`||crykaxliilz.com^$third-party` is already part of `EasyList`, I can't reproduce any popups.

We could add
`crisanimex.com##+js(abort-on-property-write.js, _pop)`
 to disable the popads script and there should be no `crykaxliilz.com` request after that.

**Comment by mapx-** [comment]
I get a strange behaviour only in chrome => when the page is loading, automatically another separate ads window is loaded.

**Comment by okiehsch** [comment]
That is caused by the new popads-script, I can reproduce that if I allow the `crykaxliilz.com` request.
`+js(popads.net.js)` does not work with the new script.
What does work is 
`crisanimex.com##+js(abort-on-property-write.js, _pop)
or
`crisanimex.com##+js(abort-on-property-read.js, popjs.init)`
or blocking the random third-party domain.

**Comment by mapx-** [comment]
yeah, my easylist wasn't updated, now is ok.
