### ISSUE TITLE
vitoriadaconquistanoticias.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4334]
### URL(s) where the issue occurs

`http://www.vitoriadaconquistanoticias.com.br/v2/2018/12/17/tristeza-jovem-pisa-em-fio-desencapado-e-morre-enquanto-lavava-roupas-bahia/`

### Describe the issue

Anti-text selection/context menu annoyance.

### Versions

- Browser/version: Firefox 64.0 (64-bit)
- uBlock Origin version: uBlock Origin 1.17.4

### Settings

+Annoyances

**Comment by mapx-** [comment]
@adranger  

for ads add
`||imgur.com/*.gif$image,domain=vitoriadaconquistanoticias.com.br`
