### ISSUE TITLE
news-leader.com anti-adblock modal & hidden overflow scrollbar

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#4335]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.news-leader.com/story/news/crime/2018/12/13/multi-year-poaching-probe-nabs-four-sw-missouri-family-members/2305173002/`

### Describe the issue

Upon page load, there is an anti-adblock modal that pops up and takes away the overflow scroll bar.

### Screenshot(s)

![news-leader](https://user-images.githubusercontent.com/22258847/50130922-e6d58100-024d-11e9-910a-419c03e6530f.PNG)

### Versions

- Browser/version: Chrome Version 72.0.3626.17 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin 1.17.5b10 (Latest Dev Build)
- uBlock Origin Extra 2.79

### Settings

- Test profile with default settings and lists.

### Notes
You may need to reload page once or twice to trigger the adblock modal.

Additional Note: `news-leader.com` is part of the [USA Today Network/Gannett Newspapers](https://www.gannett.com/brands/). I haven't tested if this anti-adblock is on all of their domains yet, but posting their other domains below that this anti adblock could eventually be deployed to since it's research I've already done that could be helpful in the future.

Domain list of USA Today Network/Gannett Sites:

`alamogordonews.com,app.com,argusleader.com,azcentral.com,battlecreekenquirer.com,baxterbulletin.com,bucyrustelegraphforum.com,burlingtonfreepress.com,caller.com,chillicothegazette.com,cincinnati.com,citizen-times.com,clarionledger.com,coloradoan.com,commercialappeal.com,coshoctontribune.com,courier-journal.com,courierpostonline.com,courierpress.com,currentargus.com,daily-times.com,dailyrecord.com,dailyworld.com,delawareonline.com,delmarvanow.com,demingheadlight.com,democratandchronicle.com,desertsun.com,desmoinesregister.com,dnj.com,elpasotimes.com,eveningsun.com,fdlreporter.com,floridatoday.com,freep.com,gosanangelo.com,greatfallstribune.com,greenbaypressgazette.com,greenvilleonline.com,guampdn.com,hattiesburgamerican.com,htrnews.com,independentmail.com,indystar.com,ithacajournal.com,jacksonsun.com,jconline.com,jsonline.com,kitsapsun.com,knoxnews.com,lancastereaglegazette.com,lansingstatejournal.com,lcsun-news.com,ldnews.com,livingstondaily.com,lohud.com,mansfieldnewsjournal.com,marionstar.com,marshfieldnewsherald.com,montgomeryadvertiser.com,mycentraljersey.com,naplesnews.com,newarkadvocate.com,news-leader.com,news-press.com,newsleader.com,northjersey.com,pal-item.com,pnj.com,portclintonnewsherald.com,postcrescent.com,poughkeepsiejournal.com,press-citizen.com,pressconnects.com,publicopiniononline.com,redding.com,reporternews.com,rgj.com,scsun-news.com,sctimes.com,sheboyganpress.com,shreveporttimes.com,stargazette.com,statesmanjournal.com,stevenspointjournal.com,tallahassee.com,tcpalm.com,tennessean.com,theadvertiser.com,thecalifornian.com,thedailyjournal.com,thegleaner.com,theleafchronicle.com,thenews-messenger.com,thenewsstar.com,thenorthwestern.com,thespectrum.com,thestarpress.com,thetimesherald.com,thetowntalk.com,timesrecordnews.com,usatoday.com,vcstar.com,visaliatimesdelta.com,wausaudailyherald.com,wisconsinrapidstribune.com,ydr.com,zanesvilletimesrecorder.com`

**Comment by okiehsch** [comment]
I can't reproduce.
If you click the "X" in the adblock-modal does the message reappear after you reload or not?

**Comment by yourduskquibbles** [comment]
> If you click the "X" in the adblock-modal does the message reappear after you reload or not?

Appears not to come back for me after reloading a few times.

Clearing cookies, reloading page, scrolling down the page, then reloading again brings it back for me. Maybe I missed a step to reproduce with scrolling down the page before reload?

**Comment by okiehsch** [comment]
Maybe it depends on the location if you see the modal or not, the site uses sourcepoint, so you can try to add
`news-leader.com##+js(abort-on-property-read.js, _sp_._networkListenerData)`
to your filter list and see if this fixes the issue for you.

**Comment by yourduskquibbles** [comment]
It doesn't *always* appear for me on 2nd reload + page scroll.

Are you able to try a combination of scrolling both up and down the page and reloading to try and trigger it?

**Comment by yourduskquibbles** [comment]
I clicked around the site a bit, comments still seem to work, the video doesn't play for me, but doesn't play without that filter either with uBO default lists so I think that is unrelated breakage.

**Comment by okiehsch** [comment]
Thank you.

**Comment by okiehsch** [comment]
f

**Comment by okiehsch** [comment]
The video does not work even if I disable `uBO` on my end.
The site is also a good example of what is wrong with online advertising, connecting to 136 domains.
![image](https://user-images.githubusercontent.com/16838044/50132859-7a787300-0289-11e9-81b7-83f97e431878.png)

**Comment by yourduskquibbles** [comment]
> The site is also a good example of what is wrong with online advertising, connecting to 136 domains.

100%

_Unsuck the web_

**Comment by uBlock-user** [comment]
Disabling uBO on such sites is like signing your death warrant. I wouldn't dare.
