### ISSUE TITLE
a-o.ninja/anime-odcinki.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#4338]
`a-o.ninja` domain moved to:

```
https://anime-odcinki.pl/
```

And possible `a-o.ninja` sale to other hands as now owner @otakupl

<div align="center">

> Domena "`a-o.nijna`" jest na sprzedaż.
> Skontaktuj się z nami aby poznać szczegóły: `a-o.ninja@anime-odcinki.pl`

</div>

https://github.com/uBlockOrigin/uAssets/blob/bb22c19c43d4e764c9855fd37d95a7af1623eb94/filters/resource-abuse.txt#L278

**Comment by okiehsch** [comment]
I can't reproduce any mining at the new domain, is your issue only about removing the now obsolete `a-o.ninja` entry or are there any issues with `https://anime-odcinki.pl`?

**Comment by krystian3w** [comment]
remove only obsolete if unless you consider it suspicious that you are moving @otakupl to another domain (attempt to disappear from the adblock lists and a sudden return with support for redirections to the older domain from the server).

**Comment by okiehsch** [comment]
I can keep `*$csp=worker-src 'none',domain=a-o.ninja` in place and continue to monitor `https://anime-odcinki.pl` in case it starts mining.

**Comment by okiehsch** [comment]
I will close for now and if a filter for `anime-odcinki.pl` becomes necessary I will reference this issue.

**Comment by okiehsch** [comment]
Actually the domain does try to push notfications and uses an inline-script that causes many unnecessary 3rd-part requests, I will add a fix for that.

**Comment by krystian3w** [comment]
I could put it on the push list:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/PPB_uBlock_AdGuard/push_supplement.txt

**Comment by okiehsch** [comment]
I consider the push-script at that site to be more than annoying, so it should be fixed for all polish users by default in my opinion.

**Comment by krystian3w** [comment]
@majkiit and what do you think that this was in the list for uBO ads or anti-advertising uBO?

**Comment by OtakuPL** [comment]
Ej, ale to nie moja strona xD hahaha, ktoś się chyba tu pomylił....

**Comment by krystian3w** [comment]
Opierałem się o: https://github.com/hoshsadiq/adblock-nocoin-list/issues/278#issuecomment-410247361

Chyba że to jakiś klon twojego konta lub za koleżankę robisz coś.

**Comment by OtakuPL** [comment]
Stare dzieje... Byłem już w każdej z stron anime online w administracji.

**Comment by MajkiIT** [comment]
> @MajkiIT and what do you think that this was in the Polish list for uBO ads or anti-advertising uBO?

I do not understand you.

**Comment by krystian3w** [comment]
Okiehsch chodzi, że to powinna wycinać lista na reklamy lub antyreklamowa (dlatego jest w `filters.txt` uBO) a nie opcjonalna EI prowadzonej przez hawkeye116477.

**Comment by krystian3w** [comment]
Okiehsch chodzi, że to powinna wycinać to lista na reklamy lub antyreklamowa (dlatego jest w `filters.txt` uBO) a nie opcjonalna EI prowadzona przez hawkeye116477 (push blokuje chyba mniej niż z 14 milinów subskrybentów polski filtrów reklamowych).
