### ISSUE TITLE
Pocket sponsored posts

### ISSUE THREAD

**Issue by Drei109** [uBlockOrigin/uAssets#4339]
### URL(s) where the issue occurs

`https://getpocket.com/a/queue/` (You must be logged in)

### Describe the issue

You can see sponsored posts on the main page, of the "My List" tab.

### Screenshot(s)

https://screenshotscdn.firefoxusercontent.com/images/7493f2cd-26da-4345-9905-1d5037ed0a35.png

### Versions

- Browser/version: Firefox 64.0
- uBlock Origin version: 1.17.5b10

### Settings

- No changes

### Notes
I tried manually blocking the sponsored posts but they keep showing.

**Comment by Drei109** [comment]
I just fixed this issue with this: 
`getpocket.com##.adjusted.spoc.spoc_list_item.item_type_spoc.item`
Should this be added to a list somewhere or should I just close the thread?

**Comment by okiehsch** [comment]
You can open an issue at `https://github.com/easylist/easylist/issues`.
Such a filter will not be added to `uAssets` as per https://github.com/uBlockOrigin/uAssets/blob/master/README.md
"If an issue can be fixed without using extended syntax......"
