### ISSUE TITLE
Potential issues can be caused by a flaw in setTimeout-defuser.js

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#434]
### URL(s) where the issue occurs

Demo (simulate when setTimeout-defuer is on): `https://xuhaiyang1234.gitlab.io/Test/uAsset-setTimeout-defuser-flaw.html`
Demo (simulate when setTimeout-defuer is off): `https://xuhaiyang1234.gitlab.io/Test/uAsset-setTimeout-defuser-flaw.html?off`

The code is embedded to prevent race condition. 

### Describe the issue

`setTimeout-defuser.js` does not pass the rest of the arguments over. 

### Screenshot(s)

First error: breaks Violentmonkey
Second error: breaks page
![image](https://cloud.githubusercontent.com/assets/7283682/26732212/0bed75ce-4774-11e7-810d-19deb506ac90.png)

### Versions

- Browser/version: Chrome/58.0.3029.110
- uBlock Origin version: 1.12.4

### Settings

- Default + uBlock Protector

### Notes

As per standard, extra arguments passed to setTimeout are passed in as arguments to the scheduled function, but the function in uAsset doesn't do that: 
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L1706

Potential fix: Change the section to this: 
```JavaScript
        window.setTimeout = function(a, b, ...rest) {
		if ( (isNaN(delay) || b == delay) && needle.test(a.toString()) ) {
			return 0;
		}
		return z(a, b, ...rest);
	}.bind(window);
```

**Same thing applies to `setTimeout-logger.js`, `setInterval-defuser.js`, and `setInterval-logger.js`.**

Extra: `setTimeout-defuser.js` can be rather easily bypassed: `https://github.com/jspenguin2017/AdBlockChallenge#ublock-origin-settimeout-defuserjs-bypassing`

**Comment by jspenguin2017** [comment]
Or a more old-browser-friendly fix: 
```JavaScript
        window.setTimeout = function(a, b) {
		if ( (isNaN(delay) || b == delay) && needle.test(a.toString()) ) {
			return 0;
		}
		return z.apply(window, arguments);
	}.bind(window);
```

**Comment by ghajini** [comment]
Gorhill will need real-case examples where its bypassing.....

**Comment by jspenguin2017** [comment]
@ghajini I do have a prove-of-concept page... Anyway, it's just something extra, don't worry about it, not important.

**Comment by ghajini** [comment]
Reveal here those 2 pages....gorhill will be able to fix setTimeout-defuser.js `flaw`

**Comment by jspenguin2017** [comment]
https://jspenguin2017.github.io/AdBlockChallenge/setTimeout-defuser%20Bypass.html
https://jspenguin2017.github.io/AdBlockChallenge/bab-defuser%20Bypass%20Nightmare%20Mode.html

**Comment by jspenguin2017** [comment]
@ghajini The issue you shown is very complex, but this is not, it's only 1 line change (actually 4 because there are 4 scriptlets) and setTimeout should accept more than 2 arguments by standard: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout

**Comment by gorhill** [comment]
> Gorhill will need real-case examples where its bypassing

Not really, the scriptlet does change the semantic of `setTimeout()`, while it should not. It needs to mind possible extra arguments.

**Comment by jspenguin2017** [comment]
@ghajini Wait, `setInterval` also accepts extra arguments: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval
