### ISSUE TITLE
camwhoreshd.com (nsfw) (breakage)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4345]
### URL(s) where the issue occurs

`[camwhoreshd.com]`

### Describe the issue

[video player doesn't load because of ublock filter `
||camwhoreshd.com^$csp=child-src 'self' *.cwtvembeds.com; script-src 'self' *` only way to make the player appear is whitelist the csp.]

### Versions

- Browser/version: [firefox mobile v63]
- uBlock Origin version: [1.17.4]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
csp filter prevents video from loading `http://www.camwhoreshd.com/videos/486093/alenaxoxo-anal-523223cfe41b5151/` 

nsfw of course.

**Comment by dumbusernameidk** [comment]
@okiehsch videos have anti-adblock.

**Comment by okiehsch** [comment]
Any specific link for me to reproduce?
I tried a few videos and see no anti adblock message.

**Comment by dumbusernameidk** [comment]
Any with cwtvembeds I guess? There seem to be several. Here's one:

`https://www.camwhoreshd.com/videos/302126/bryci-bikini-shoot-1d9984bcac99916d/`

**Comment by okiehsch** [comment]
Thanks. I will add your fix.
