### ISSUE TITLE
douploads adblock detected

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#4349]
https://douploads.com/tor1b6ps3bpq

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
`https://douploads.net/zm70va5x2v6w`
Clicking create download link leads to ads

can we uncheck `download with addons` button with filters?

**Comment by mapx-** [comment]
test

```
douploads.net##+js(acis, $, show)
douploads.net##+js(ra, checked, input#chkIsAdd)
douploads.net##[href^="https://href.li/"]
```

however on the download page the download wont start due to mixed content (at least in chrome)
![image](https://user-images.githubusercontent.com/10303732/107483318-33444f00-6b81-11eb-8c55-1e0b1b4a64f0.png)

You have to copy the link and use it in a separate tab

**Comment by patrickdrd** [comment]
or disable `chrome://flags/#treat-unsafe-downloads-as-active-content` I guess

**Comment by ghajini** [comment]
Don't know what's happening site is showing me expired download session
![Screenshot_2021-02-10-14-12-44-832_org mozilla fenix](https://user-images.githubusercontent.com/20338483/107485780-3e5fa500-6baa-11eb-820f-ebfbccb8aa86.png)
