### ISSUE TITLE
Remove/unbreak block of dk4ywix.com & rebelsubway.com

### ISSUE THREAD

**Issue by admiral-pubhelp** [uBlockOrigin/uAssets#4350]
### URL(s) where the issue occurs

`https://www.endocrineweb.com/conditions/type-1-diabetes/type-1-diabetes-overview`

### Describe the issue

The site above uses dk4ywix.com & rebelsubway.com for its access control wall. Calls to those domains are currently circumvented by uBO and its integrated filters. 

### Screenshot(s)

How it looks (active circumvention)
![circumvented](https://user-images.githubusercontent.com/41959276/50256307-ae57b380-03c3-11e9-9e01-f7986432e312.png)

How it should look (no circumvention)
![correct](https://user-images.githubusercontent.com/41959276/50256289-9ed86a80-03c3-11e9-8736-a5109a81aaa1.png)

Filters to remove/unbreak
<img width="373" alt="screen shot 2018-12-19 at 7 14 12 pm" src="https://user-images.githubusercontent.com/41959276/50256044-8a47a280-03c2-11e9-9eb0-74d353378c5c.png">
<img width="377" alt="screen shot 2018-12-19 at 7 41 07 pm" src="https://user-images.githubusercontent.com/41959276/50256836-40f95200-03c6-11e9-9ab4-b4f0350ca188.png">

### Versions

- Browser/version: Chrome, Version 71.0.3578.98 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.17.4

### Settings

- removed uBO and re-installed uBO for fresh settings

### Notes

uBO policy on this has been recently clarified here: https://twitter.com/gorhill/status/1072990091625328641

This circumvention can be fixed by either not distributing the circumventing filters, removing those filters or unbreaking them.  Addition of the following to My Filters removed the circumvention:
@@||dk4ywix.com^
@@||rebelsubway.com^

Please advise if you need more info or need us to deliver this circumvention removal request through other channels.

**Comment by gorhill** [comment]
> Please whitelist these Admiral's domain names or else

uBO acts on behalf of users as an extension to their _user_ agent. You are requiring that we subvert a core purpose of an extension of the _user_ agent to act on behalf of Admiral (with which you, user @admiral-pubhelp, may or may not be related).

The logical consequence of agreeing with your request is to render content blockers irrelevant, we are not going to be accessory to this nonsense.

Note that I can also access that site just fine without any filter list enabled, by merely disabling JavaScript or just disabling 3rd-party scripts. According to your logic these features should also be removed.

Declined.

**Comment by mapx-** [comment]
or
```
||dk4ywix.com^$badfilter
||dk4ywix.com^$third-party,badfilter
||rebelsubway.com^$badfilter
```

and adding in annoyances a specific injecting filter

**Comment by gorhill** [comment]
If we use `badfilter` then we assume that all other sites where these domains are use also get a dismissable warning. I suppose that is a fair assumption and if ever a warning is un-dismissable then someone will report it. I let you add these?

**Comment by mapx-** [comment]
yep, testing, I'll add them

**Comment by gorhill** [comment]
What I worry though is why was `dk4ywix.com` in EasyList? Surely it was to block something which deserved to be blocked?

**Comment by mapx-** [comment]
Can you find something in easylist repository about it ?

**Comment by mapx-** [comment]
well, it's part of admiral section in easylist, so I guess nothing else ..

**Comment by gorhill** [comment]
Well after all I think I prefer to keep it to exception filters and unbreak only the reported site -- that same hostname could be used to serve bad stuff on other sites. If there are more out there they will open issues about it, then eventually we can reconsider the `badfilter` approach.
