### ISSUE TITLE
trentonian.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4353]
### URL(s) where the issue occurs

`https://www.trentonian.com/news/nj-gov-phil-murphy-s-christmas-promise-the-specter-of/article_50aace5a-0474-11e9-8c8b-d7b88a6e2bdd.html`

### Describe the issue

Anti-adblock. Clicking `No, thanks.` will remove the overlay but the article will be censored.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/50314323-5180f980-04a6-11e9-9650-438a9af2d2fd.png)

**Comment by okiehsch** [comment]
Does `trentonian.com##+js(set-constant.js, CnnXt.Event.fire, noopFunc)` work for you?

**Comment by terrorist96** [comment]
Yes

**Comment by terrorist96** [comment]
Also, uBO breaks video here:
`https://www.trentonian.com/news/national/eyes-on-trump-as-senate-passes-funding-bill/video_b848fc11-3980-572a-af38-12ca1b26301f.html`
Still testing to figure out the problem.

**Comment by mapx-** [comment]
add
`@@||cdn.turner.com/cnn/van/resources/*/scripts/vendor/loggly.tracker.js$script,xhr,domain=trentonian.com`

**Comment by mapx-** [comment]
only xhr (I modified above)

**Comment by okiehsch** [comment]
I get only an empty placeholder, but that could be because I can only access the site via a VPN.

**Comment by mapx-** [comment]
I use a vpn too (more exactly: ssh tunneling), @terrorist96 does work for you ?

**Comment by terrorist96** [comment]
> add
> `@@||cdn.turner.com/cnn/van/resources/*/scripts/vendor/loggly.tracker.js$xhr,domain=trentonian.com`

Works.

**Comment by terrorist96** [comment]
One more thing. It seems like the email subscription box is being blocked from appearing.
`https://www.trentonian.com/news/crime/trenton-man-charged-with-weapons-offenses-after-spanking-leaves-welts/article_1bf73864-0498-11e9-bb7b-8b396b3e5153.html`
![image](https://user-images.githubusercontent.com/12802056/50315780-fd791380-04ab-11e9-9a3f-b56ebb94711b.png)
I can't figure out why. Something related with `EasyList` and `uBlock filters`. It's not a big deal if you don't wanna deal with it.

**Comment by okiehsch** [comment]
Hm, I don't see such a box even if I disable `EasyLIst` and `uBO-filters`.
Clicking "Signup for newsletters" works on my end.
![image](https://user-images.githubusercontent.com/16838044/50317041-d6c1d980-04b9-11e9-9bf5-146b4e323cbd.png)
I think that is good enough no need to investigate any further in my opinion, but if you find a working filter I will add it.
