### ISSUE TITLE
fashionyip.info (nsfw)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4354]
### URL(s) where the issue occurs

`[fashionyip.info]`

### Describe the issue

[After clicking on a gallery from the homepage trying to open any picture results in multiple redirects to junk sites.]

### Versions

- Browser/version: [firefox mobile v63]
- uBlock Origin version: [1.17.4]

### Settings

- [default]

### Notes

[The cause of the redirects comes from `fashionyip.info/go.php` but you can't block this otherwise it kills all the pictures on the site.]

**Comment by okiehsch** [comment]
I can add 
`fashionyip.info##+js(disable-newtab-links.js)`
that will disable the popups if somebody clicks them and should not break the ability to open the pictures with a `right-click`.

**Comment by dumbusernameidk** [comment]
Sounds good.
