### ISSUE TITLE
play.rtl.hr [Anti-AdBlocker]

### ISSUE THREAD

**Issue by superstolica** [uBlockOrigin/uAssets#4356]
Every video played from this site: `https://play.rtl.hr/`
`https://play.rtl.hr/gospodin-savrseni-p_12041/epizoda-20-c_12239715`

Every video stops playing when i have ublock on, sometimes it shows the message and sometimes it does not.

![https://i.imgur.com/tGtmZ7P.png](https://i.imgur.com/tGtmZ7P.png)

- Browser/version: Chrome Version 71.0.3578.98
- uBlock Origin version: uBlock Origin 1.17.4

Tried accessing with Nano Defender and Nano AdBlocker and it didnt work.

**Comment by mapx-** [comment]
> Zbog pravnih razloga, ovaj video ne može biti pokrenut s vaše lokacije.

You should post here al the blocked items (element + triggered filter) you get in the logger

**Comment by superstolica** [comment]
[logger.txt](https://github.com/uBlockOrigin/uAssets/files/2702114/logger.txt)

**Comment by mapx-** [comment]
what if you add
@@||cdn.ad.server.iprom.net/ipromNS.js

**Comment by superstolica** [comment]
i am still getting the same adblock message

**Comment by mapx-** [comment]
add also & test again
`@@||nqs.nice264.com/data$xmlhttprequest,domain=rtl.hr`

**Comment by superstolica** [comment]
still the same message

**Comment by mapx-** [comment]
keeping the filters above provide again the logger list - but I want **only the blocked requests**
(in the search box type `--` to get only those ones)

**Comment by superstolica** [comment]
[logger2.txt](https://github.com/uBlockOrigin/uAssets/files/2702176/logger2.txt)

**Comment by mapx-** [comment]
test these filters
```
@@||cdn.ad.server.iprom.net$script
@@||nqs.nice264.com/data$xmlhttprequest,domain=rtl.hr
```

**Comment by superstolica** [comment]
still the same message

**Comment by mapx-** [comment]
add also
`@@||adserver.iprom.net/adserver7$xmlhttprequest,domain=rtl.hr`
or
`@@||adserver.iprom.net/adserver7$xmlhttprequest`

**Comment by superstolica** [comment]
adding the first one made it work!
thank you so much for your time and help

**Comment by mapx-** [comment]
You should test if all those filters are necessary and tell us

**Comment by superstolica** [comment]
@@||cdn.ad.server.iprom.net/ipromNS.js
@@||nqs.nice264.com/data$xmlhttprequest,domain=rtl.hr
@@||cdn.ad.server.iprom.net$script
@@||nqs.nice264.com/data$xmlhttprequest,domain=rtl.hr
all of these are not necessary

**Comment by mapx-** [comment]
so, only the last 1 do all the job
`@@||adserver.iprom.net/adserver7$xmlhttprequest,domain=rtl.hr`

**Comment by superstolica** [comment]
@@||adserver.iprom.net/adserver7$xmlhttprequest,domain=rtl.hr
@@||adserver.iprom.net/adserver7$xmlhttprequest 
both work even if used individually

**Comment by mapx-** [comment]
added to the ublock filters list
