### ISSUE TITLE
outlook.live.com - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#436]
Anti adb warning is displayed in the right sidebar on https://outlook.live.com.

**SS:** https://i.imgur.com/C0ftede.png
**Error URL:** https://outlook.live.com/owa/

You need to be signed in to your Microsoft/Outlook account to see the anti adb warning which appears to the right of the inbox.

This issue has already been reported in AdguardFilters (https://github.com/AdguardTeam/AdguardFilters/issues/2570) but the filters which work for Adguard do not seem to for uBlock.

_**Note:** Using uBO 1.12.4 on Chrome 58 with the default filters and settings._

**Comment by SMed79** [comment]
A link just for reference [#118957](https://forums.lanik.us/viewtopic.php?p=118957).

**Comment by mapx-** [comment]
`outlook.live.com##[class*=Adsbar]`

**Comment by gorhill** [comment]
> the filters which work for Adguard do not seem to for uBlock.

They work for uBO, it's the filters you were given which do not work if the browser is not maximized. Reduce the width and see the sidebar reappearing.

**Comment by gorhill** [comment]
outlook.live.com##._n_h[style^="position: absolute;"]
    outlook.live.com###primaryContainer > div[style*="top: 50px;"]:not([class]):not([id]):style(bottom: 0 !important; right: 0 !important;)

**Comment by gotitbro** [comment]
@gorhill The filters posted above work, the ad sidebar is hidden completely.

> it's the filters you were given which do not work if the browser is not maximized.
Not sure what you mean by that but my window was maximized to the full width of the screen already.

**Comment by gorhill** [comment]
> Not sure what you mean by that but my window was maximized to the full width of the screen already.

Read carefully:

> Reduce the width and see the sidebar reappearing.

**Comment by gorhill** [comment]
The Adguard filters were working fine on my side as long as the window was maximized.

**Comment by gotitbro** [comment]
So, I just checked again and seems like the filters posted by @gorhill aren't working either now (even with the window being maximized.)

Though using the Adguard extension itself does seem to hide the sidebar. Might be an issue with uBO itself   :/

**Comment by gorhill** [comment]
There is no issue with uBO, all works fine here.

**Comment by gotitbro** [comment]
Sorry, the issue was on my side disabling and re-enabling the extension worked.

Adguard filters still don't work though (not that it is a problem).
