### ISSUE TITLE
nytimes.com "Comments" button blocked

### ISSUE THREAD

**Issue by duyatran** [uBlockOrigin/uAssets#437]
### URL(s) where the issue occurs

[Any New York Times article, for example](https://www.nytimes.com/2017/06/02/business/dealbook/trump-climate-small-businesses.html)

### Describe the issue

Articles on NYTimes.com has a "Comments" bubble button somewhere in their article (position indeterminate) that opens up a side bar of comments. With uBlock Origin on, this button is nowhere to be found, so one cannot access the comment section of any article.  

### Screenshot(s)

<img width="562" alt="untitled1" src="https://cloud.githubusercontent.com/assets/10622779/26755552/6a10e034-485d-11e7-96d3-b2904d490b77.png">
<img width="556" alt="untitled" src="https://cloud.githubusercontent.com/assets/10622779/26755551/6a0e5f44-485d-11e7-95d7-64fd00b6e8ef.png">

### Versions

- Browser/version: Chrome 58.0.3029.110 (64-bit)
- uBlock Origin version: 1.12.4

### Settings

No changes to default settings

### Notes

I looked around a bit but did not find out much. It does not seem like the button belongs to any "*-ad" class that might be blocked.

**Comment by ghajini** [comment]
If you click on `comments` ,comments will load

**Comment by okiehsch** [comment]
I can't reproduce, with default settings the "Comments" bubble button is visible
![nyt](https://cloud.githubusercontent.com/assets/16838044/26755732/1af8865a-4894-11e7-8f2a-5b8a25aae797.JPG)
and clickable
![nyt1](https://cloud.githubusercontent.com/assets/16838044/26755736/4bc9b9a2-4894-11e7-8f63-eb016f6fe685.JPG)

**Comment by duyatran** [comment]
Thanks for the replies. It seems that the problem is even weirder than I thought. This is what consistently happens on my machine:
- Go to the NYTimes article above, with uBlock on. The comment button is there.
- Refresh the page, now the button is gone.

Another way this problem appears:
- Go to the NYTimes article above, with uBlock off. The comment button is there.
- Turn on uBlock, refresh the page, now the button is gone.

Can you now reproduce it in these two cases? Thanks!

**Comment by gorhill** [comment]
Looks like a timing issue. I can also reproduce with ABP with EasyList/EasyPrivacy only, so not specific to uBO. It does appears EasyPrivacy is needed.

**Comment by duyatran** [comment]
That's right, not using EasyPrivacy in Chrome makes the button appear. The issue can also be reproduced directly in Firefox 53.0.3 (just go to the article with uBO on, the button is not there).

**Comment by gorhill** [comment]
One way I can make the issue disappear is by un-blocking `https://contextual.media.net/bidexchange.js`, but that is not a proper solution.

**Comment by SMed79** [comment]
Not only the "Comments button" (take a look https://forums.lanik.us/viewtopic.php?f=64&t=37002)

needed filter `@@||contextual.media.net/bidexchange.js?cid=$script,domain=nytimes.com`

**Comment by mapx-** [comment]
Now it seems they changed the button which is appearing consistently on the top bar (and on the same row as the article's title
