### ISSUE TITLE
habr.com

### ISSUE THREAD

**Issue by alhimik45** [uBlockOrigin/uAssets#4374]
### URL(s) where the issue occurs

`habr.com`

### Describe the issue

bab-defuser breaks js in popular russian IT site. It was added by [this commit](https://github.com/uBlockOrigin/uAssets/commit/199f540df11d61346fef072f0794bf69f68a98fe) from [automatic scan](https://github.com/uBlockOrigin/uAssets/issues/4268#issuecomment-449126844). This scan found this link `https://habr.com/post/427047/`. There are discussion about ad-blockers and anti-adblockers in this page and source code of blockadblock was posted in [one comment](https://habr.com/post/427047/#comment_19279201) there, which gave a false positive. Please remove rule for habr.com

### Versions

- Browser/version: any
- uBlock Origin version: last

**Comment by jspenguin2017** [comment]
Thanks. Domain whitelisted in scanner.
