### ISSUE TITLE
http://trecetv.es/ and  https://www.intereconomia.tv/ [Anti-Adblock]

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#4378]
Hello, everybody.
Excuse me, I'm with the help of a translator. 

### URL(s) where the issue occurs

`[http://trecetv.es/
https://www.intereconomia.tv/]`

### Describe the issue

[On both pages it warns me to deactivate uBlock. I know there is a case for http://trecetv.es/ that is #1886 but it doesn't work for me. 

I would appreciate if you could tell me exactly what I have to copy and paste into uBlock.

Can you fix it?

Thank you very much and greetings]

### Screenshot(s)

http://img.fenixzone.net/i/0iEJu6m.png
http://img.fenixzone.net/i/m16SgXG.png

### Versions

- Browser/version: [Firefox 64 Bit 64]
- uBlock Origin version: [1.17.4]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
I can't reproduce with a default setup,
`https://www.intereconomia.tv`
![image](https://user-images.githubusercontent.com/16838044/50389218-da5a9800-0727-11e9-8ed7-5512f833d76e.png)


`http://www.trecetv.es/directo`
![image](https://user-images.githubusercontent.com/16838044/50389283-c9f6ed00-0728-11e9-9654-b8f370513987.png)

**Comment by KiLL4FuNK** [comment]
Do you use any antivirus or other blocking extension? @Jose1971AB

**Comment by mapx-** [comment]
Reset uBo to default and turn OFF all other addons, test again

**Comment by Jose1971AB** [comment]
Hello friends...  KiLL4FuNK and mapx 
Sorry for the delay in answering, I'm sorry, for health reasons I could not.
I'm going to do what you have advised me and I'll tell you already
Please, I'd appreciate it if you'd keep in touch.

**Comment by Jose1971AB** [comment]
Hello friends... 

I have Avast Free as antivirus with the windows 7 firewall, but I think the antivirus has nothing to do.

**So far I have tested only with http://www.trecetv.es/directo as https://www.intereconomia.tv/ did not emit a signal at the time of the test.**

I only restored uBlock by default without disabling the other add-ons, I checked that it didn't detect uBlock and played the video.

I was configuring uBlock again filter by filter again until I found two filters that cause the problem... They are two filters that I have included in the Custom section

AdGuard Base filter --> https://filters.adtidy.org/extension/chromium/filters/2.txt
Anudeep´s Blacklist --> https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt 

Apparently I have to deactivate the two filters. If I deactivate the first one, the warning appears detecting uBlock and if I deactivate the second one, the video appears with the button to reproduce but you click on it and it doesn't reproduce it, it doesn't do anything.

Is there any other solution other than deactivating those filters to see the two websites?...

A greeting...

**Comment by mapx-** [comment]
No transmission for me.

**Comment by mapx-** [comment]
I added those 2 lists `AdGuard Base, Anudeep´s Blacklist` => still no anti adb stuff for me (tested `trecetv`)

**Comment by Jose1971AB** [comment]
Hello mapx... first of all happy holidays and a happy new year.

I can only tell you that I have combined my filters in a thousand ways and it is only those two filters that give me the problem that I have an adblocker (uBlock) installed, besides not being able to play the videos. If I deactivate those two filters and refresh the page the problem disappears, being able to reproduce it without problems.

As I said before, I think the antivirus does not influence, I do not know, but I'm for sure, because if it were the case, even deactivating those two filters logically would still appear the problem, don't you think?

Also it doesn't matter that I add what is indicated in #1886, as much if I add it as if not, if I don't deactivate those two filters I get the adblocker warning installed besides not reproducing the videos.

If you require it, I can send you as I have uBlock configured to see what you think.

There may be filters in my configuration that cause conflicts, I do not know, I am a very basic user.

At the moment, to be able to see the broadcasts of those two web I am deactivating those two filters.

See what comes to mind, I'm still in touch friend ... thank you very much

**Comment by mapx-** [comment]
happy new year to you too :)
You could backup your configuration and upload it here.

**Comment by Jose1971AB** [comment]
Hello mapx...

I don't know how to send you the backup file, I don't know how to do it. Where is the option or how is it done?... I told you that I am a very basic user.

Extensions
Bitdefender TrafficLight --> http://img.fenixzone.net/i/salfk2P.png
NanoDefender --> http://img.fenixzone.net/i/5jBYDOZ.png
Violentmonkey --> http://img.fenixzone.net/i/aHKLhTp.png
Cookie AutoDelete --> http://img.fenixzone.net/i/EHwRYWT.png
Translator --> http://img.fenixzone.net/i/YAwQB3C.png

uBlock origin (What doesn't appear is that it's by default)
Configuration tab --> http://img.fenixzone.net/i/m5wkchP.png
Filter List tab --> http://img.fenixzone.net/i/Ewz2oPp.png
Filter List 2 tab --> http://img.fenixzone.net/i/0qD4WHu.png
My filters tab in uBlock --> Same as general configuration. I know how to make the backup but how do I send it to you?.

If you need more information, let me know.

Well, my friend, let's see if this can help you.

Greetings and thank you very much

**Comment by mapx-** [comment]
In the first group of lists (the most important: "incluidos") you disabled the main list (`ublock filters`) . Enable it again and don't touch that group anymore.

However, you should go into settings tab and `Reset to default settings`, then add your other lists (and **don't disable the default lists** !)

Then - if still don't work - disable all other extensions (even nano) and test using only uBo.

**Comment by Jose1971AB** [comment]
Hello friend mapx...

I'm going to do what she says in her answer, but I want to tell you something about her.

First of all you say that I have disabled "uBlock filter". I replaced this filter with another one a long time ago, which according to a Github page, was the same but much more complete. I don't know if this will really be so, but if you indicate it, I will remove it again and put the one I had, which is the one you say. I haven't been able to find the page where I said it, I've taken a while looking for it, so you can check it yourself.

The filter to which I refer and that I put in substitution to "uBlock filter" is one that is called "uBlock Filter Plus". **This filter is the last one that appears in this image --> http://img.fenixzone.net/i/0qD4WHu.png**. If you click on each filter will open a page with the list that make up each and see that "uBlock Filter Plus" is almost the same as "uBlock filter" but more complete, at least said so on the page that I could not find. As there is no point in putting two filters the same (for consumption of resources) because I opted for the most complete, "uBlock Filter Plus", do I explain? Anyway and as I said before, if you consider it I will change it again.

Concerning these two filters I have opened an incidence in this forum, to know which are the differences between one and the other. I think it also belongs to Github, **the incidence or case is at this address --> https://github.com/IDKwhattoputhere/uBlock-Filters-Plus/issues/1**

I expounded the case about 20 days ago and I still haven't heard back.

This was my comment to your question. Now I am going to do what you tell me in your answer, give me some time, I have some things to do at home. When I do, I'll tell you.

Greetings and thank you very much.

**Comment by mapx-** [comment]
Don't use that list, its outdated (7 months ago), use only the official uBo lists.

**Comment by Jose1971AB** [comment]
Hello mapx ... I'm here again.

I have taken as an example only the two pages that we deal with in this case ...

https://www.intereconomia.tv/
http://trecetv.es/

I have done the tests in three ways.

1.- As you told me in your penultimate response. Disable all extensions (except uBlock obviously), including the Nano Defender, and put only the uBlock Configuration tab by default.

2.- Deactivate all the extensions, including the one of Nano Defender, and putting uBlock totally by default, that is to say as if you installed it again.

uBlock defaults to me this way (what I do not put is because it is empty when it is by default) ->

http://img.fenixzone.net/i/Za4GXEk.png
http://img.fenixzone.net/i/YmMQkcK.png

3.- Putting my original configuration (the images are in the first answers of this thread) including the extensions but without the extension Nano Defender and its three filters

Note: When deactivating the Nano Defender extension, I think it's no use having the three Nano Defender filters activated, so I also deactivated them.

With each of the three forms I have tried on both pages and the problem is solved. **The drawback is that it is only solved for those two pages.**

In the little that I have tried browsing, there are pages like for example https://latribunadelpaisvasco.com/ in which the adblocker ad installed again, and there have to be many more because it happened to me before on another occasion. I would have to keep trying.

See this image -> http://img.fenixzone.net/i/Ql4MNIq.png

**The case is that the problem is solved for two specific pages but at a general level the situation worsens.**

I do not know what you think but I think that **in the first place I would have to reactivate the Nano Defender extension plus its three filters, because I know that in this way the problem is solved in a general way**. If so that in https://www.intereconomia.tv/ and http://trecetv.es/ the adblock ad does not appear installed, I just have to deactivate the filters that I said (at the beginning of this thread) I think it would be the more convenient and leave my general configuration. Unless you come up with a specific filter for each of them ... can you explain?

Anyway I have to keep trying because I have not had time for more, I just found with https://latribunadelpaisvasco.com/ I already told him that now I would be a little busier.

Good friend ... let's see what happens ... a greeting
