### ISSUE TITLE
Removed element blinks on and off

### ISSUE THREAD

**Issue by forthrin** [uBlockOrigin/uAssets#4380]
### URL(s) where the issue occurs

`https://www.aftenposten.no/`

### Describe the issue

Added `www.aftenposten.no##.video-playing` to remove autoplaying videos. Result: The video blinks on and off every second rather than being removed.

## Versions

- Browser/version: Safari 12.0.2
- uBlock Origin version: 1.11.3.1

**Comment by mapx-** [comment]
Test 
```
||schibsted.io/player/$script,domain=aftenposten.no
aftenposten.no##.mm-box-video-wrapper
```

However, other legitimate videos will be broken

**Comment by forthrin** [comment]
@mapx-: Seems to work (for the front page at least). By legitimate, you mean videos in articles you can start voluntarily? That's not so good in that case. The point is to stop intrusive autoplaying videos.
