### ISSUE TITLE
Add Anti popads.net filter

### ISSUE THREAD

**Issue by ale5000-git** [uBlockOrigin/uAssets#439]
### Describe the issue

Hi,
is it possible to add this filter to the default list? https://github.com/Yhonay/antipopads/raw/master/popads.txt

**Comment by SMed79** [comment]
Hi,
popads revolving adservers are already blocked in easylist

**Comment by ale5000-git** [comment]
It is updated frequently, see [here](https://github.com/Yhonay/antipopads/commits/master).

EasyList is missing this: `fkianrxjfumm.com`.

**Comment by SMed79** [comment]
Easylist updated frequently too check the [History for easylist](https://github.com/easylist/easylist/commits/master/easylist) withe the commit "**M: Update**".
I know you're doing a great work but be more effective I suggest you to pull popads adservers to EasyList.

**Comment by ale5000-git** [comment]
I'm not the author of the list, sorry for the misunderstanding, I just report it because it may be useful.
