### ISSUE TITLE
[Ads] occasionasaisir.ovh

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#4399]
### URL(s) where the issue occurs

`http://occasionasaisir.ovh/wheeler-dealers-hd-tvr-cerbera/#`

### Describe the issue

15 seconds ads timer. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/50425225-41af3f80-082f-11e9-8910-b40604a39b66.png)

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.17.4

### Settings

Default + uBlock annoyance

### Notes

This is unrelated to other Net Scan issues.

**Comment by mapx-** [comment]
- playing directly `https://www.dailymotion.com/embed/video/x58kk9x` I get no delay
- adding 
`||s3.amazonaws.com/dmas-public/rubicon/bundle.js$script,domain=dailymotion.com`
will remove the ad / delay but I have no idea if something will be broken
