### ISSUE TITLE
dasolo.co

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#440]
### URL(s) where the issue occurs
http://www.dasolo.co/

### Describe the issue
Anti adblock + dasolo.org is now dasolo.co

### Screenshot(s)
![i5663](https://cloud.githubusercontent.com/assets/27068733/26823844/a50eed8c-4a9e-11e7-864e-575724b53a57.jpg)

### Notes
dasolo.org is now dasolo.co
In the ublock filters there are two filters for dasolo.org
`animes-mangas-ddl.com,best-movies.info,bnonews.com,crazymeds.us,dasolo.org,d-h.st,hulkusc.com,ip-address.org,megapanda.net,nplay.com,playlivenewz.com,sadeempc.com,upload.so,uploadshub.com,userscdn.com,yourvideohost.com##script:inject(bab-defuser.js)`
and
`||adscale.de^$image,redirect=1x1-transparent.gif,domain=dasolo.org`

The first filter need to be changed from `dasolo.org` to `dasolo.co` for antiadblock

For me the second filter is no more necessary

**Comment by SMed79** [comment]
Alternative filters 
```
@@||dasolo.co^$generichide
@@||italyshare.club/adframe.js$script,domain=dasolo.co
```

**Comment by gorhill** [comment]
This was [fixed hours ago](https://github.com/uBlockOrigin/uAssets/commit/2500afe0bc1ac29553d40c6a1bfcd64a19e14861), force an update of _uBlock filters_.

**Comment by gorhill** [comment]
@SMed79 I rather not have exception filters such as `@@||italyshare.club/adframe.js$script,domain=dasolo.co` be proposed here when this can be addressed by uBO without such exception filter -- I really don't see the point of proposing such solution _here_.

**Comment by SMed79** [comment]
It's **empty** file as these filters (or others) found in ublock-filters.
```
@@||financialexpress.com/*/ad*$script,first-party
@@||cdn.windows7themes.net/wp-content/advert.js$script,first-party
@@||static.lexpress.fr/*/ads.$script,stylesheet
@@||fullpremiums.com/adblock.js$script,first-party
@@||ops.prismamediadigital.com/js/advertisement.js$xmlhttprequest,domain=programme-tv.net
```
... but ok i'll take note :no_mouth:

**Comment by gorhill** [comment]
> as these filters (or others) found in ublock-filters

Again:

> when this can be addressed by uBO without such exception filter

**Comment by SMed79** [comment]
D'accord, message reçu :cat:

**Comment by bup4gr** [comment]
I have a problem with the new filters.
I don't see anti adblock on home page dasolo.co.
But on http://www.dasolo.co/e-books/riviste-italiane/619362-linux-magazine-giugno-2017.html i see the anti adblock.

**Comment by bup4gr** [comment]
dasolo.co change another time the anti adblock.
I think we must add also this filter:
`dasolo.co###blockblockA`

**Comment by bup4gr** [comment]
If i go here http://www.dasolo.co/e-books/riviste-italiane/619362-linux-magazine-giugno-2017.html i can see the anti adblock.
So i think another change in the anti adblock.

I see also that in Fanboy’s Enhanced Tracking List there is:
`@@||dasolo.club*/adframe.js$script`
`@@||dasolo.co/advertisement.js`

**Comment by okiehsch** [comment]
@gorhill I get two different detection mechanisms  on this site, depending on which browser I use,
are you OK with a broad exception filter `@@||dasolo.co^$image,first-party`?

**Comment by gorhill** [comment]
> are you OK with a broad exception filter @@||dasolo.co^$image,first-party?

Of course, I have no issue allowing when it comes to 1st-party, be it images or scripts.
