### ISSUE TITLE
[Anti-adblock] olympine.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#4404]
### URL(s) where the issue occurs

`http://www.olympine.com/olympine/`

### Describe the issue

Hard anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/50425978-67dcdb80-083f-11e9-9803-706898d55f66.png)

### Versions

Browser/version: Chrome 73
uBlock Origin version: 1.17.4

### Settings

Default + uBlock annoyance

### Notes

This website also has BAB, but that is already fixed
This is unrelated to other Net Scan issues

**Comment by okiehsch** [comment]
Fixed in the regional list.
