### ISSUE TITLE
[Anti-adblock] macdailynews.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#4405]
### URL(s) where the issue occurs

`http://macdailynews.com/#/`

### Describe the issue

Hard anti-adblock (comes up every time)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/50426036-6c09f880-0841-11e9-8c3d-26773b082c4b.png)

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.17.4

### Settings

Default + uBlock annoyance

### Notes

This is unrelated to other Net Scan issues

**Comment by kulfoon** [comment]
Again:

### Screenshot(s)

![capture_022_12-05-2020_15-56-02](https://user-images.githubusercontent.com/43844449/81700598-274c2500-9469-11ea-886c-e4059aa13162.gif)

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.26.2

### Settings

Default
