### ISSUE TITLE
[Anti-adblock] gamesandroidhvga.net

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#4406]
### URL(s) where the issue occurs

`https://gamesandroidhvga.net/`

### Describe the issue

Hard anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/50426088-b344b900-0842-11e9-8d99-b6315fb1a89e.png)

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.17.4

### Settings

Default + uBlock annoyance

### Notes

This is unrelated to other Net Scan issues

**Comment by okiehsch** [comment]
Fixed in the regional list.
