### ISSUE TITLE
cagesideseats.com(antiadblock/annoyance)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4409]
### URL(s) where the issue occurs

`https://www.cagesideseats.com/wwe/2018/12/25/18155938/rusev-wins-united-states-championship-wwe-smackdown`

### Describe the issue
Antiadblock categorised as annoyance (gives no option to disable it)
Comes on multiple refresh of site

### Screenshot(s)

![screenshot_2018-12-26-13-56-52-171_org mozilla firefox](https://user-images.githubusercontent.com/20338483/50439148-e04ba700-08e8-11e9-9adf-53465f460d44.png)

### Versions

- Browser/version: Firefox android 64
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings+ublock annoyance filters

**Comment by mapx-** [comment]
tested on desktop, give it a try on android
