### ISSUE TITLE
BBC Video Clips blocked by updated EasyPrivacy

### ISSUE THREAD

**Issue by Vangelis66** [uBlockOrigin/uAssets#441]
### URL(s) where the issue occurs

Any BBC Video Clip, preferably available worldwide (as opposed to UK-only content): 
```
http://www.bbc.co.uk/programmes/p054xx24
http://www.bbc.co.uk/programmes/p054xw2j
http://www.bbc.co.uk/programmes/p054xvqz
http://www.bbc.co.uk/programmes/p054xvfw
```
etc
### Describe the issue

According to your browser version and when Flash support (NPAPI/PPAPI) for that browser is enabled, 
the default Flash-based BBC player should load and video clip playback should start (AdobeHDS streams). 

When Flash support for your browser is disabled or Flash plugin is not installed, BBC will try to load 
their HTML5-based player (`http://www.bbc.co.uk/html5`); that player has several browser/OS pre-requisites, 
but when you meet those the player should load and start playback of video clips (MPEG-DASH streams) 

With latest uBlock 1.12.5rc1 (non-webext) installed and enabled on Firefox ESR (32bit) 52.1.2, neither the Flash nor the HTML5 BBC player gets loaded, resulting in no playback of the video clip.

### Versions
- OS : Windows Vista SP2 32bit, with all MS updates 
- Browser/version: FirefoxESR 52.1.2  (32bit) [eligible for the HTML5 player when Flash disabled!]
- Flash/version: 25.0.0.171 NPAPI  (32bit) 
- uBlock Origin version: 1.12.5rc1 (non-webext)

### Settings

- uBO's default settings, all filter lists updated manually.

### Notes

When uBO is disabled/uninstalled, both the Flash and the HTML5 BBC players load OK and video playback starts; not so when uBO is enabled :-( 
At first I thought this was a native uBO issue, but installing and checking various previous versions, both stable and beta, ruled that out, as the issue persisted. 
Then, with latest uBO beta (1.12.5rc1), I changed focus on the included third party filters lists. 
To cut a long story short, (updated) EasyPrivacy filter list is the culprit. 
STR: 
1. In `chrome://ublock0/content/dashboard.html`, uncheck **EasyPrivacy** and click red "Apply Changes"
2. Reload, e.g. `http://www.bbc.co.uk/programmes/p054xvfw` tab => Video starts playing
3. Check again **EasyPrivacy** and click red "Apply Changes"
4. Reload, e.g. `http://www.bbc.co.uk/programmes/p054xvfw` tab => Video starts playing
5. Update manually filters lists (so that EasyPrivacy gets updated from v201705131439 to v201706061637)
6. Reload, e.g. `http://www.bbc.co.uk/programmes/p054xvfw` tab => No video player is loaded, only a still photo is displayed!

Probably something the EP people should fix...

**Comment by mapx-** [comment]
add
`||bbci.co.uk^*/analytics.js$badfilter`
or
`@@||bbci.co.uk^*/analytics.js`

**Comment by gorhill** [comment]
Force an update of _"uBlock filters -- Unbreak"_.

**Comment by Vangelis66** [comment]
Thank you both! :+1:
Works now OK :-)
