### ISSUE TITLE
shush.se(antiadblock)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4415]
### URL(s) where the issue occurs

`http://www.shush.se/index.php?id=0&show=thewalkingdead`

### Describe the issue

adblock warning & inviting to install rogue extension of its own site
### Screenshot(s)

![screenshot 71](https://user-images.githubusercontent.com/20338483/50448964-369d0200-094a-11e9-8bef-934a542d6e66.png)

### Versions

- Browser/version: chrome 71
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
Are you sure
`https://openuserjs.org/scripts/shush/Shush_Extension` is a malicious one ?

for anti adb + some obfuscated stuff
```
shush.se##+js(set-constant.js, check, true)
||shush.se/loader/load.js$script
```

**Comment by ghajini** [comment]
don't know as safe or? my antivirus catches it as threat

**Comment by mapx-** [comment]
the source is here:
https://openuserjs.org/scripts/shush/Shush_Extension/source

If someone could assure you it's all ok .. @jspenguin2017 @gorhill

**Comment by ghajini** [comment]
may be false positive detection of my antivirus, extension is required to play the video

**Comment by jspenguin2017** [comment]
Can't tell, no immediate red flag. It does have `@connect *` though. 

```js
function checkReq() {
    var list = document.getElementById("gkpluginsExtListReq");
    if (list == null) {
        return;
    }
    list.title = "ready";
    if (list.childNodes.length > 0) {
        var curReq = list.firstChild;
        if (typeof curReq.innerHTML == "undefined") {
            list.removeChild(curReq);
            return;
        }
        var obj = JSON.parse(atob(curReq.innerHTML));
        obj.onload = obj.onerror = obj.onabor = function(response) {
            var txtout = document.createElement("textarea");
            txtout.id = obj.extreqid;
            txtout.style.display = "none";
            var Hfres = response.status + " " + response.statusText + "\r\n" + response.responseHeaders;
            if (response.finalUrl) {
                Hfres += "FinalLocation: " + response.finalUrl + "\r\n";
            }
            if (obj.returndtaescape) {
                txtout.value = escape(Hfres + "\r\n" + response.responseText);
            } else if (obj.returndtab64) {
                txtout.value = btoa(Hfres + "\r\n" + response.responseText);
            } else {
                txtout.value = Hfres + "\r\n" + response.responseText;
            }
            document.body.appendChild(txtout);
        };
        GM_xmlhttpRequest(obj);
        list.removeChild(curReq);
    }
}
setInterval(checkReq, 100);
```

**Comment by mapx-** [comment]
only a guess: could work with (now blocked) the obfuscated stuff here (?!):
`shush.se/loader/load.js`

**Comment by mapx-** [comment]
well .. the obfuscated stuff has also some mining inside
https://pastebin.com/6Nd1qrJ3
