### ISSUE TITLE
cnet.com auto-playing videos and big side ad

### ISSUE THREAD

**Issue by carstenhag** [uBlockOrigin/uAssets#4420]
### URL(s) where the issue occurs

```
https://www.cnet.com/news/this-man-spent-5000-of-his-own-money-to-put-zimbabwe-on-street-view/
https://www.cnet.com/news/net-neutrality-battle-heads-to-court-in-2019/
```

### Describe the issue

Autoplaying video appears after some seconds. After closing, other big ad shows up.
### Screenshot(s)

https://imgur.com/a/0EUnAvl

### Versions

- Browser/version: Chrome 71.0.3578.98 on Mac
- uBlock Origin version: 1.17.4

### Settings

None

### Notes

Possibly related to #3164, not really sure.

**Comment by mapx-** [comment]
For the ads: did you install ublock extra ? 
https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco

As for the videos: I get no autoplaying video (bottom right I get a video but not playing)
