### ISSUE TITLE
scr.cr

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4427]
### URL(s) where the issue occurs

`https://scr.cr/watchm/8019-the-big-valley-season-1`

### Describe the issue

videos not playing on this site, clicking play doesn't work
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
yours:

> We're Sorry!
We can't find the file you are looking for. It maybe got deleted by the owner or was removed due a copyright violation.

working (no issue)
`https://scr.cr/watchm/18003-duck-dynasty-season-2`

**Comment by ghajini** [comment]
its available sir, 3rd party player is `vidcloud` not `streamcherry`(your side)
![screenshot 75](https://user-images.githubusercontent.com/20338483/50520799-6550df00-0ae8-11e9-9319-7a3e04304910.png)

**Comment by mapx-** [comment]
you can test adding
```
loadvid.online##+js(set-constant.js, pop_cnt, 1)
loadvid.online#@#+js(set-constant.js, pop_cnt, 2)
```

**Comment by mapx-** [comment]
does this work ?
`loadvid.online###overlay-vcplayer`

**Comment by ghajini** [comment]
thanks buddy
