### ISSUE TITLE
Unable to update specific 3rd party filter

### ISSUE THREAD

**Issue by pdbits** [uBlockOrigin/uAssets#443]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

<https://hosts-file.net/>

### Describe the issue

While updating hpHosts’ Ad and tracking servers filter for the past 3 days, I'm getting the following error: A network error prevented the resource from being updated. This filter updated properly before, no issues with other filters. 

### Screenshot(s)

I think the issue explained above should not require screenshots.

### Versions

- Browser/version: Firefox 53.0.3 x64
- uBlock Origin version: 1.12.4

### Settings

- Default + enabled other 3rd party filters: Anti-adblock killer, malware domains, fanboys list etc (advanced user enabled, webrtc blocked)

### Notes

From inspection, I found that the filter site, <https://hosts-file.net/> itself wasn't reachable. However, it has downgraded to http only(no auto redirect). So <http://hosts-file.net/> is reachable, whereas <https://hosts-file.net/> is not. Is there a way to update filter by editing the filter's address?

**Comment by gorhill** [comment]
This was fixed: https://github.com/gorhill/uBlock/issues/2682.

**Comment by pdbits** [comment]
I'm sorry I didn't completely understand. Is the issue fixed in this(1.12.4) non-webext version or only in 1.12.5rc1 webext/non-webext ? 
Thank you

**Comment by gorhill** [comment]
You will have to click _"Purge all caches"_ and _"Update now"_ to get the updated list of filter lists.

**Comment by pdbits** [comment]
Thank you, that worked.
