### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4430]
### URL(s) where the issue occurs

`https://megaup.net/6wv5/`

### Describe the issue

3rd party popunders before actual download on clicking download now, annoying everytime
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
Antiadblock
`megaup.net/4ax6r`

Screenshot=

`i.imgur.com/T1MOWbz.gifv`

**Comment by ghajini** [comment]
Exception filters no longer needed?
I tried blocking exception filters, no antiadblock here

**Comment by mapx-** [comment]
I know, they are changing daily the code so could be they turn back

**Comment by uBlock-user** [comment]
The "manager" joined the reddit to complain about "DDoSing" his website -- `https://www.reddit.com/r/uBlockOrigin/comments/dj483q/ublock_is_abusing_permissions_to_break_and_ddos/` 

🤣

**Comment by ghajini** [comment]
`megaup.net/3uB6v`

`download now` button not working,doesn't get file for download

**Comment by ghajini** [comment]
Are you on latest filters, iam not getting any file for download ....
Then tried with ublock off, some popups then download started

**Comment by uBlock-user** [comment]
@mapx- `megaup.net##[style="display: block;"]`
 blocks the upload dialog box from appearing, should be removed.

**Comment by ghajini** [comment]
`https://megaup.net/1v1es/ExtraMovies.casa_DS12DAHE72BRESD.mkv`

All the existing whitelists can be removed, they are taking advantage of that and inserting push notifications, hence 3rd party xhr's increasing. ....doing that doesn't result in any breakage in download functionality....

**Comment by ghajini** [comment]
`https://megaup.net/2Xhbi/SPCSWSKMHD_(2021)_www.SkymoviesHD.uno_720p_NF_HDRip_Dual_Audio_x264_ESub.mkv`

Antiadblock

**Comment by ghajini** [comment]
Antiadblock
`https://megaup.net/2Xhbi/SPCSWSKMHD_(2021)_www.SkymoviesHD.uno_720p_NF_HDRip_Dual_Audio_x264_ESub.mkv`

**Comment by ghajini** [comment]
Circumvention again

**Comment by ghajini** [comment]
Antiadblock

**Comment by ghajini** [comment]
`https://megaup.net/2XEzO/PADLMSKMHD_(2018)_www.SkymoviesHD.uno_720p_HEVC_UnCut_HDRip_Dual_AUdio_x265_ESUb.mkv`

there's been ads started showing and sometimes antiadblock notice also

![image](https://user-images.githubusercontent.com/20338483/109831113-2341fb80-7c65-11eb-8942-6c2980ad681c.png)

**Comment by wout-codes** [comment]
> `https://megaup.net/2XEzO/PADLMSKMHD_(2018)_www.SkymoviesHD.uno_720p_HEVC_UnCut_HDRip_Dual_AUdio_x265_ESUb.mkv`
> 
> there's been ads started showing and sometimes antiadblock notice also
> 
> ![image](https://user-images.githubusercontent.com/20338483/109831113-2341fb80-7c65-11eb-8942-6c2980ad681c.png)

@ghajini You may want to use `AdGuard Base` in your blocker. It fixes all ads and anti-adb in `megaup.net`.

**Comment by ghajini** [comment]
Antiadblock

`https://megaup.net/1BXap/Bad.Samaritan.2018.480p.BR_[www.Fullmaza.Org].mkv`

**Comment by wout-codes** [comment]
> `https://megaup.net/1BXap/Bad.Samaritan.2018.480p.BR_[www.Fullmaza.Org].mkv`

Fixed in AdGuard Base sometime ago.

**Comment by ghajini** [comment]
@wout-codes 
This is the website which daily change to fight adblocker so one can't be sure one should use adguard or ublock origin

**Comment by wout-codes** [comment]
Btw, does uBO support JS rules?

**Comment by ghajini** [comment]
No

**Comment by okiehsch** [comment]
It works fine for me.
![image](https://user-images.githubusercontent.com/16838044/111016594-29e01980-83af-11eb-9505-87299e4a3b2e.png)

**Comment by ghajini** [comment]
Yes works fine ,iam just explaining wout-codes there is no gurantee in using adguard to fix Antiadblock all the time,site just changes everytime👍

**Comment by okiehsch** [comment]
@wout-codes you can find all supported script-injections [here](https://github.com/gorhill/uBlock/wiki/Resources-Library).

**Comment by okiehsch** [comment]
You can craft your own userscripts and use them via `userResourcesLocation` parameter in Advanced-Settings in uBlock-Origin.
https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation

**Comment by wout-codes** [comment]
> You can craft your own userscripts and use them via `userResourcesLocation` parameter in Advanced-Settings in uBlock-Origin.
> https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation

Okay. uBO is more than an Ad-Blocker. Exceptional case. I have never seen and Ad-Blocker (extension) that supports userscript.
