### ISSUE TITLE
bdotools.xyz [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4438]
URL(s) where the issue occurs

`https://bdotools.xyz/map/`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 71 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.4

Settings

Default

**Comment by okiehsch** [comment]
Message occurs even if one disables `uBO`.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/50528800-c54b8380-0af0-11e9-9313-6fd1aee8f002.png)


I get the message every time, but if you can reproduce you should of course add the filter.
