### ISSUE TITLE
kingofdown antiadblock

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#444]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://kingofdown.com/`
### Describe the issue

Antiadblock by going to above homepage.....

### Screenshot(s)
![img_20170608_201015](https://user-images.githubusercontent.com/20338483/26937904-57da7a24-4c90-11e7-977b-dd72deb64a54.JPG)

### Versions

- Browser/version: firefox for android
- uBlock Origin version: 1.12.4

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
```
@@||kingofdown.com^$generichide
||pagead2.googlesyndication.com^$script,redirect=noopjs,domain=kingofdown.com
```

**Comment by ghajini** [comment]
ovelaybuster.js working.....But for 2 seconds ,antiadblock is shown and then hided

**Comment by mapx-** [comment]
and the other 2 filters ?

**Comment by ghajini** [comment]
No its not working at all.....

**Comment by ghajini** [comment]
Iam trying to download this file `http://m.turbobit.net/02gspvqoiyr2.html` ....After clicking download in upper corner......`Skip` is off when ublock is on....But it should be visible to redirect to download site.....So it's certainly annoyance to ublock users

**Comment by ghajini** [comment]
@gorhill, acc to below thread `antiblock.org v2` is responsible for this
`https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/40`

**Comment by okiehsch** [comment]
@ghajini if I add
````
||pagead2.googlesyndication.com^$script,redirect=noopjs,domain=kingofdown.com|kingofshrink.com
||kingofdown.com/img/180upload.png$image,redirect=2x2-transparent.png
@@||kingofshrink.com/img/skip.png$image,first-party
@@||kingofdown.com^$generichide
@@||kingofshrink.com^$generichide
````
the site works fine on my end with Chrome and Firefox and the `Skip` button is visible and clickable.

**Comment by ghajini** [comment]
Worked 👍
