### ISSUE TITLE
Unblockable Ads on Drudge

### ISSUE THREAD

**Issue by RAcceleration** [uBlockOrigin/uAssets#445]
### URL(s) where the issue occurs

`[http://drudgereport.com/]`

### Describe the issue

[((((Drudge)))) seems to have found a way around. Most ads are still blocked but some are getting through even after manually blocking elements. Some on Reddit have also noticed: https://www.reddit.com/r/uBlockOrigin/comments/6fvuo0/ads_leaking_through_on_drudge_report/]

### Screenshot(s)

[https://i.gyazo.com/feddb0e17e758e9cc0269f251f6ac336.png]

### Versions

- Browser/version: [Firefox 53.0.3, macOS]
- uBlock Origin version: [uBlock Origin v1.12.4]

### Settings

- [None]

### Notes

[]

**Comment by mapx-** [comment]
filter working only in uBo + chrome
`||bn7v3w.8m5sew59gr.bid/http$xmlhttprequest,redirect=nooptext,domain=drudgereport.com`

**Comment by mapx-** [comment]
this 1 seems working for FF too
`drudgereport.com##script:inject(abort-on-property-write.js, adonis)`

**Comment by gorhill** [comment]
Fixed with 1bb541a4, force an update of _"uBlock filters"_.

**Comment by mapx-** [comment]
alternative:
`drudgereport.com##span:matches-css(background-image: /^url\("data:image/jpeg;base64,/)`

**Comment by gorhill** [comment]
Or with 1.12.5, a case to support `csp=` option: `||drudgereport.com^$csp=img-src 'self' *` to forbid `data:`/`blob:` images, if ever they work around the current filter.
