### ISSUE TITLE
Wipliz doesn’t work with “uBlock filters – Privacy​​​​​”

### ISSUE THREAD

**Issue by ariasuni** [uBlockOrigin/uAssets#4450]
### URL(s) where the issue occurs

`https://wipliz.com/cagnotte/Xmn5J/contribute`

### Describe the issue

The page displays a blank page.

### Versions

- Browser/version: Firefox 65.0b6
- uBlock Origin version: 1.17.4

### Notes

Adding `@@https://www.googletagmanager.com/gtm.js$script,domain=wipliz.com` in my custom filters fixes the issue.

**Comment by okiehsch** [comment]
Thanks for reporting.

**Comment by ariasuni** [comment]
Thanks :)
