### ISSUE TITLE
kinopoisk.ru

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#4451]
![111](https://user-images.githubusercontent.com/8535285/50531438-f44c0e80-0b5d-11e9-9dfe-4bb41f39c7e6.png)
@mapx- helpme

I can block it with (plus cosmetic filters from RUS: Adguard Russian Filter and RUS: RU AdList)

`kinopoisk.ru##HTML > HEAD + BODY > DIV:first-child > DIV:first-child + DIV + DIV > DIV + DIV:last-child > A:last-child`
 `kinopoisk.ru##HTML > HEAD + BODY > DIV:first-child > DIV:first-child + DIV + DIV > DIV > DIV:first-child > DIV:first-child > DIV:first-child > DIV:first-child > DIV:first-child + DIV + DIV:last-child`

but
it does not always work + these rules are very long. you can make your voodoo.

**Comment by mapx-** [comment]
try these ones
```
kinopoisk.ru##+js(setInterval-defuser.js)
kinopoisk.ru##[href^="https://www.kinopoisk.ru/15P"]
kinopoisk.ru##[href*="adblock"]:xpath(..)
```

**Comment by bogachenko** [comment]
@mapx- no ads. but there is one nuance. Look at the screenshot, there are 3 white crap. These are widgets, they change at a certain point and show the novelties with the film. So here they are white (either all or that last)

**Comment by mapx-** [comment]
replace
`kinopoisk.ru##+js(setInterval-defuser.js)`
by
`kinopoisk.ru##+js(setInterval-defuser.js, (), 500)`

and test again

**Comment by bogachenko** [comment]
@mapx- Refreshed the page as nervous, just 300 times. Nothing breaks anymore. Thank you so much.

**Comment by bogachenko** [comment]
@mapx- @okiehsch again ads https://www.kinopoisk.ru/film/lipuchka-2011-484470/
![default](https://user-images.githubusercontent.com/8535285/51422116-30bed780-1bfd-11e9-929b-42027de431bc.png)

**Comment by mapx-** [comment]
No such ad for me.

**Comment by bogachenko** [comment]
@mapx- like this? she is shown. It disappears after cleaning the cookies, but it is necessary to update the site once and it is shown again.

By the way, admiring the case, how to remove (reduce) this space?
![default](https://user-images.githubusercontent.com/8535285/51425306-54e6dc80-1c2e-11e9-8441-35f851c1c2b5.png)


This rules does not help.
`kinopoisk.ru###top:style(height: 120px!important;)`
`kinopoisk.ru##html:not(#id) > body:not(#id) > #top:style(margin-bottom: auto !important)`

**Comment by bogachenko** [comment]
@mapx- 
![default](https://user-images.githubusercontent.com/8535285/51430558-14c73000-1c15-11e9-9627-ab8d250ba216.png)
![default](https://user-images.githubusercontent.com/8535285/51430568-30323b00-1c15-11e9-9265-2af8e399840e.png)

**Comment by bogachenko** [comment]
@mapx- @okiehsch  It's not funny...
![default](https://user-images.githubusercontent.com/8535285/51571742-fecaa100-1e9a-11e9-9640-6a31741875c7.png)

**Comment by bogachenko** [comment]
your script is not working

**Comment by bogachenko** [comment]
![default](https://user-images.githubusercontent.com/8535285/52890839-19164700-31db-11e9-9ad9-b23ea8724b2a.png)

not ad
del `kinopoisk.ru##[href^="https://www.kinopoisk.ru/"]`

**Comment by bogachenko** [comment]
![default](https://user-images.githubusercontent.com/8535285/52890897-5f6ba600-31db-11e9-8b62-39c8ef34d5f1.png)

not ad
del `kinopoisk.ru##[href^="https://www.kinopoisk.ru/"]`

**Comment by mapx-** [comment]
the oscar item ? use the element picker
`kinopoisk.ru##[class*="item-content_oscar"]`

**Comment by bogachenko** [comment]
what? her You misunderstood

you have a filter in the list `kinopoisk.ru##[href^="https://www.kinopoisk.ru/"]`, it breaks a banner (not an advertisement)

**Comment by bogachenko** [comment]
@mapx- https://www.kinopoisk.ru/film/1118042/
everywhere (not only on this page) there is a background (advertising) of [the new cartoon](https://www.kinopoisk.ru/film/1041723/?utm_source=kp&utm_medium=branding&utm_campaign=vpj), how can this be removed?

**Comment by mapx-** [comment]
`kinopoisk.ru###wonder-park-main`

**Comment by bogachenko** [comment]
@mapx- Are you for real? They update this background every time someone pays them, and manually enter each DOM like this...You did voodoo last time. And deleted it. Can you do voodoo again? Pull the rabbit out of the top hat. How do I delete this background forever?

**Comment by bogachenko** [comment]
duder pls @mapx-

**Comment by mapx-** [comment]
the russian lists contain a lot of filters for this site, you should ask adguard or @dimisa-RUAdList

However, try these filters
```
kinopoisk.ru##*:style(background: none !important;)
kinopoisk.ru##.js-position-sticky
```

**Comment by bogachenko** [comment]
@mapx- The whole site goes on cunt
![Безымянный](https://user-images.githubusercontent.com/8535285/54564374-89bfa780-49c3-11e9-9c35-6c9ad4a15ac7.png)

**Comment by dimisa-RUAdList** [comment]
This is their own announcement. Added to BitBlock: https://hg.adblockplus.org/ruadlist/rev/53c600aa4a20

However, although this does not apply to this particular case, uBlock Origin may not work correctly on this site when using Firefox because of the CSP bug. This affects the injection of the scriptlets, so you can periodically see the missed ads on this site. But in Google Chrome this does not happen.

**Comment by dimisa-RUAdList** [comment]
Apparently, this fix `kinopoisk.ru###image:style(opacity: 1 !important;)` is no longer needed.

See: https://github.com/gorhill/uBlock/issues/2097
