### ISSUE TITLE
www.torrentfunk.com "open link in new tab"

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#4452]
`www.torrentfunk.com`

Hi. When you search for certain items, like "start10" on the website, then from the list of results you right-click "Stardock Start10 1 61 + patch" and try to select "open link in new tab", it just briefly shows a new tab, then closes it automatically, but when you left-click on it, it opens fine (albeit not in a new tab), and when you disable ublock origin, then right-click on the link and select "open link in new tab", it opens fine. I've already purged all caches and update the filters. Do you know how to fix that? Thanks.

![www torrentfunk com start10](https://user-images.githubusercontent.com/35790889/50539244-18eabb00-0b4b-11e9-89ab-e31326e406d0.jpg)

firefox 64.0 (64-bit)
ublock origin 1.17.4

**Comment by okiehsch** [comment]
I also can't reproduce, you will have to look in the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) to see which filter ist blocks the popup.

**Comment by IoanPaleru** [comment]
What do you mean you can't reproduce? Did you follow the steps I provided? I have the same ublock origin settings as you do with a popular browser. You troubleshoot it yourself, it's your program that doesn't work. Thanks.

**Comment by IoanPaleru** [comment]
16:31:36 |   | ##main > div:nth-of-type(1) > div |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
-- | -- | -- | -- | -- | --
16:31:36 |   | ##a[href*="//xml.revrtb.com/"] |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##[href*="an0n."] |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##[href*="//xml.revrtb.com/"] |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##[href*=".an0n."] |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##[class^="w"] |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##.warn |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##.trtbl:has-text(VPN) |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##.trtbl |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   | ##.buttonv.spo-btn-link |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:36 |   |   |   | image | https://www.torrentfunk.com/favicon-16x16.png
16:31:36 |   |   |   | image | https://www.torrentfunk.com/apple-touch-icon.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/f.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/cat4.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/cat5.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/cat10.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/dl.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/friends.gif
16:31:35 |   | www.torrentfunk.com histats.com *  block | -- | script | https://s10.histats.com/js15_as.js
16:31:35 |   | www.torrentfunk.com cloudflare.com *  block | -- | script | https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/h1.jpg
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/h6.jpg
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/t_tab_v.png
16:31:35 |   | \|\|www.torrentfunk.com/images/rev.png$image | -- | image | https://www.torrentfunk.com/images/rev.png
16:31:35 |   | \|\|adtng.com^$third-party | -- | frame | https://a.adtng.com/get/10002516?time=1545254669867
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/posters/movies/tomb-raider.jpg
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/posters/movies/love-simon.jpg
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/posters/movies/sherlock-gnomes.jpg
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/posters/movies/black-panther.jpg
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/slider/deadpool.jpg
16:31:35 |   | www.torrentfunk.com cloudflare.com *  block | -- | script | https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/h/back.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/headerout.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/searchb1.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/torrent.png
16:31:35 |   |   |   | image | https://www.torrentfunk.com/images/header.jpg
16:31:35 |   | www.torrentfunk.com cloudflare.com *  block | -- | script | https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js
16:31:35 |   | \|\|www.torrentfunk.com/images/rev.png$image | -- | image | https://www.torrentfunk.com/images/rev.png
16:31:35 |   | www.torrentfunk.com cloudflare.com *  block | -- | script | https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js
16:31:35 |   |   |   | script | https://www.torrentfunk.com/images/jquery-3.2.1.min.js
16:31:35 |   |   |   | css | https://www.torrentfunk.com/images/style.css
16:31:35 |   | ##+js(nowebrtc.js) |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:35 |   | ##+js(abort-on-property-write.js, Fingerprint2) |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:35 |   | ##+js(abort-on-property-write.js, bidrev) |   | dom | https://www.torrentfunk.com/all/torrents/start10.html
16:31:35 |   | \|\|torrentfunk.com^$csp=script-src 'self' * 'unsafe-inline' | -- | csp | https://www.torrentfunk.com/all/torrents/start10.html
16:31:35 |   |   |   | inline-script | https://www.torrentfunk.com/all/torrents/start10.html
16:31:35 |   |   |   | doc | https://www.torrentfunk.com/all/torrents/start10.html
  |   | https://www.torrentfunk.com/all/torrents/start10.html

**Comment by mapx-** [comment]
@IoanPaleru  go into uBo settings, reset all the settings to default then test again

**Comment by IoanPaleru** [comment]
Ok, I reset the settings to default and now it works fine, it opens the search results links in a new tab. Thanks, and have a good day.
