### ISSUE TITLE
za.gl 

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4455]
### URL(s) where the issue occurs

`https://za.gl/ko6fI`

### Describe the issue

1.popup ads
2. push notifications if allowed then chain of popup starts
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

uBO's default settings

### Notes
tracking on mouse movements/touch button...on android device its terrible to even enter firefox menu
on firefox android if i click back to return site shows multiple popups

**Comment by mapx-** [comment]
already added
`za.gl##+js(abort-current-inline-script.js, multiClick, popup)`

fixing 

> onmousemove, movemouse,redirect, document.onload ,also console reporting by site for tracking

**Comment by ghajini** [comment]
ok that covers all,thanks

**Comment by ghajini** [comment]
NSFW
`https://za.gl/PQQClrG`

Ad clicks are required to get to destination link

**Comment by mapx-** [comment]
it seems even disabling uBO you cannot go through

**Comment by ghajini** [comment]
it seems they are checking for ad tab opened in new tab and whether ad is opened or not? with ubo disabled for za.gl when you click go ,ad is opened in new tab that ad is bllocked by filter in easylist

to get it work disable ubo from extensions menu and try(i tried on google chrome android, it seems to work with ads)

**Comment by mapx-** [comment]
add

```
/links/popad$popup,badfilter
za.gl#@#+js(abort-on-property-read, open)
```

any click you have to wait 5 seconds (but not necessarily in the new opened tab - which can be closed, any other tab)

**Comment by ghajini** [comment]
that do not work
it opens popup ads in new tab and 5sec timer in original tab doesn't go down

**Comment by okiehsch** [comment]
> 5sec timer in original tab doesn't go down

You have to focus on the popup tab for the timer to go down. We are looking for an easier fix.

**Comment by okiehsch** [comment]
Adding
`za.gl##+js(set, document.hidden, true)`
will let the timer run down even if you focus on the original tab.

**Comment by ghajini** [comment]
would you fix script responsible for opening popup tab which is closed automatically?

**Comment by okiehsch** [comment]
>  fix script responsible for opening popup tab

If you tell me how.

**Comment by ghajini** [comment]
yeah i know, no easy solution without breaking `go` button....with current fix it looks good
