### ISSUE TITLE
Fix wasted space via CSS (Fotor, and others)

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#446]
### URL(s) where the issue occurs

`https://h5.fotor.com/`
Alternative direct link to the editor view:
`https://h5.fotor.com/app.html#/editor`

### Describe the issue

First of all, this is not necessarily specific to the site linked above.
This is just an example, but I've encountered this on other sites as well, of all types, blogs, wikis. etc.
There are no visible ads, these are blocked with default settings of uBO, but hiding of placeholder elements doesn't work properly.

### Screenshot(s)

1: Screenshot with Ads
![2017-06-08_with_ads](https://user-images.githubusercontent.com/12064918/26940226-2aad9330-4c7a-11e7-9e72-7f960e1fdc92.png)

2: Screenshot with blocked Ads, but wasted space
![2017-06-08_no_ads](https://user-images.githubusercontent.com/12064918/26940259-498752dc-4c7a-11e7-9646-6946106ad841.png)

As you can see, the issue is the empty grey areas to the right side and at the bottom of the displayed site.

### Versions

- Browser/version: Chrome 59.0.3071.86 (64-bit) (on Windows 10 x64 Creator's Update)
- uBlock Origin version: 1.12.4

### Settings

- Default settings + EasyList Germany

### Notes

As said before, I have seen this problem on some other sites. In most cases, I tried to use the element picker, but could not select the specific "element", or rather empty area.
Not sure if this really helps, because I suspect these spacing areas are made with some document-wide CSS definitions not specific to any element.

Correct me if I'm wrong, but shouldn't it be possible to use the `:style`-based Cosmetic filter selector [(Wiki)](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#style) to override some CSS style settings?

The only question is how and where to apply the right CSS property declarations, I assume.
I know myself around with the Dev Tools a bit, but I don't know how to find the right CSS stuff.

**Comment by gorhill** [comment]
Does this work without causing trouble?

    h5.fotor.com###main:style(right: 0 !important;)

**Comment by Hrxn** [comment]
Found another good example:

### URL

`https://mind42.com/mindmap/7abd1334-d170-42e7-b869-f74010b9b143?rel=pmb`

(Or any other mindmap on this site)

### Screenshot

![2017-06-08_190443](https://user-images.githubusercontent.com/12064918/26941158-c06ab5a8-4c7d-11e7-999f-1f6b334e4108.png)

The white rectangle on the site is an empty ad container/wrapper, in this case the element picker can select and hide it. (##.wideskyscraper.ad)

The wooden background can be picked as well (###sidebar), but after hiding an empty grey area remains in the exact same place.

**Comment by Hrxn** [comment]
> Does this work without causing troubles?
h5.fotor.com###main:style(right: 0 !important;)

Added this to "My Filters", looks now like this:
![2017-06-08_191407](https://user-images.githubusercontent.com/12064918/26941471-de5a095a-4c7e-11e7-8ee3-4704ddf77c0b.png)

Yeah, no more wasted space on the ride side, and seems to work so far.

**Comment by Hrxn** [comment]
> Does this work without causing troubles?
`h5.fotor.com###main:style(right: 0 !important;)`

FYI, since this only fixes the spacing on the right side, I changed it to this:
`h5.fotor.com###main:style(right: 0 !important; bottom: 0 !important;)`
and it seems to work in this case.

By the way, same issue with another app on the same site, apparently.
`https://www.fotor.com/h5-app.html#/hdr`

Could be that it's made with different CSS, I'll check this again later.

**Comment by gorhill** [comment]
So

    fotor.com###main:style(right: 0 !important; bottom: 0 !important;)

Would work for both cases then?

**Comment by Hrxn** [comment]
Yes, I think it does, thanks @gorhill 

The interesting question now is, because we don't have an obvious generic solution, how to fix CSS style properties on other sites.
Do you know a straightforward way (as in, quick and easy) to do this?
The problem is less the syntax of Selectors, I think that is already pretty straightforward, and also well documented on official sites like w3.org.

Finding the right element inside the document is the real task, here in our example, with two different sites,
we have one selector for `#main` and one for `#content.sidebar2`, right?

It has to be somewhere in the DOM tree, but how to find it directly? Do you have any good tips?
