### ISSUE TITLE
news.yandex.ru, news.yandex.ua, news.yandex.by

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#4462]
advertising. You already have filters for this site (https://github.com/uBlockOrigin/uAssets/commit/ad3e1927965bfec77b6ea60938537875d2aff2f8). but they do not work, they are old(and should they be removed?). can you help me? @mapx-  @okiehsch 

one of the scripts creates these cookies. These cookies are adware. I tried to block with the help of the scriptlet, I was defeated.
```
blcrm
bltsr
yc
yp
adb
```
I tried to block them like this `news.yandex.ru##script:inject(cookie-remover.js, blcrm, bltsr, yc, yp, adb)`
but again, nothing happened

![default](https://user-images.githubusercontent.com/8535285/50542119-f4551880-0c08-11e9-9640-ba872d49bf8f.png)

and further. If you go to any links on this site, then there will be more advertising

see for yourself. Click on any link. I can not upload a screenshot, because the page is too long.

**Comment by mapx-** [comment]
test
`news.yandex.ru##+js(setTimeout-defuser.js, AdvManager)`

**Comment by okiehsch** [comment]
That works for me, we can add it until it is included in the russian list too.

**Comment by mapx-** [comment]
@bogachenko  can you test for all the news sites ?
`news.yandex.ru, news.yandex.ua, news.yandex.by`

`news.yandex.*##+js(setTimeout-defuser.js, AdvManager)`

**Comment by mapx-** [comment]
@okiehsch  did you test all those sites ?

**Comment by bogachenko** [comment]
>news.yandex.ru##+js(setTimeout-defuser.js, AdvManager)
not working

**Comment by mapx-** [comment]
Weird, for `.ru` is working fine for me

**Comment by bogachenko** [comment]
![default](https://user-images.githubusercontent.com/8535285/50542337-60d31600-0c0f-11e9-8449-00b280f98d0e.png)
![1](https://user-images.githubusercontent.com/8535285/50542338-62044300-0c0f-11e9-921e-755b880bede7.png)

uh

**Comment by bogachenko** [comment]
well, I do not know It does not work for me. maybe I need to clean the cookies?

**Comment by mapx-** [comment]
@bogachenko 
What filter did you test ?
`news.yandex.ru##+js(setTimeout-defuser.js, AdvManager)`
or
`news.yandex.*##+js(setTimeout-defuser.js, AdvManager)`

@okiehsch  the second one does not work for me !?

**Comment by bogachenko** [comment]
@mapx- I tried it and so and so

**Comment by mapx-** [comment]
mmhmm .. every 2-3 tests I get the ads even using the first filter

**Comment by bogachenko** [comment]
@mapx- при первом запуске (после очистки куки) твой фильтр (или фильтры из подписок) скрывает рекламу. но стоит 1 раз обновить страницу....

**Comment by mapx-** [comment]
test
```
news.yandex.ru##+js(setTimeout-defuser.js, AdvManager)
news.yandex.ru##+js(set-constant.js, AdvManager, null)
```

**Comment by bogachenko** [comment]
@mapx- Can't you block cookies with the help of the scriptlet I wrote above? fix it there. the whole problem is in them. Yandex uses advertising cookies

**Comment by bogachenko** [comment]
> news.yandex.ru##+js(setTimeout-defuser.js, AdvManager)
> news.yandex.ru##+js(set-constant.js, AdvManager, null)

not working. sry

**Comment by okiehsch** [comment]
> What filter did you test ?
news.yandex.ru##+js(setTimeout-defuser.js, AdvManager)
or
news.yandex.*##+js(setTimeout-defuser.js, AdvManager)
@okiehsch the second one does not work for me !?

I think yandex is a Brand TLD, so you can't use `yandex.*`.

**Comment by bogachenko** [comment]
@okiehsch so with ".ru" does not work

**Comment by okiehsch** [comment]
The filter works for me consistently, I only tested the .ru domain and clicked through quite a few articles without the ads reappearing.
I only tried with Chromium though, I will try with Firefox.

**Comment by bogachenko** [comment]
@okiehsch I'm on firefox. advertising everywhere.

**Comment by bogachenko** [comment]
@mapx- do you use chromium?

**Comment by okiehsch** [comment]
Yes, I can reproduce with Firefox, even disabling all `setTimeout` calls will not fix the issue with Firefox for some reason.

**Comment by bogachenko** [comment]
@okiehsch Uh How does this happen? everything works for my opera, but not on firefox.

**Comment by okiehsch** [comment]
@mapx- if your filter works for you with Chrome/Chromium we can add it for those browsers to atleast partially fix the issue. I can't test with Chrome -  or Windows for that mattter - at the moment.

**Comment by mapx-** [comment]
It works in chrome for me (not in FF). Sometimes ... I get ads even in chrome, could be my old system

**Comment by bogachenko** [comment]
@okiehsch I will ask again. since the answer from @mapx- to this question is not heard. Is it possible to use the cryptlet to delete cookies `cookie-remover.js` ?

I'm asking why. I installed the beta version of adguard in Opera (of course, when testing your filters, I disabled it). so, in the beta version of adguard, cookies were blocked. Advertising cookies. There is a filter for this site = $cookie=/blcrm|bltsr|yc|yp|adb/,domain=news.yandex.ru|yandex.ru he removes them. And no ads.
I created a question here for you (https://github.com/uBlockOrigin/uBlock-issues/issues/352), where I asked to add something like that. I was refused, but we agreed on this scriptlet. Since you are knowledgeable people, is it possible to block these cookies using this scriptlet?

**Comment by mapx-** [comment]
see if breaks the site
`||news.yandex.ru^$script,1p`

**Comment by bogachenko** [comment]
@mapx- works. and as far as I can judge nothing is broken. If I find write here. :+1:

**Comment by mapx-** [comment]
remove the last filter and try
```
news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.sticky_visible
news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##[class*="_name_first"]
news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##[class*="_name_footer"]
```

**Comment by bogachenko** [comment]
> remove the last filter (`||news.yandex.ru^$script,1p`) and try
> 
> ```
> news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.sticky_visible
> news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##[class*="_name_first"]
> news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##[class*="_name_footer"]
> ```

if you click on any links. then there will be another advertisement
![default](https://user-images.githubusercontent.com/8535285/50543115-ec55a280-0c21-11e9-8010-1c9cb6795bd4.png)

**Comment by bogachenko** [comment]
`news.yandex.ru##+js(noeuc.js)`

```js
noeuc.js application/javascript
(function() {
	let needle = '{{1}}';
	if ( needle === '' || needle === '{{1}}' ) {
		needle = '.?';
	} else if ( needle.slice(0,1) === '/' && needle.slice(-1) === '/' ) {
		needle = needle.slice(1,-1);
	} else {
		needle = needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	}
	needle = new RegExp(needle);
	realnoeuc = window.encodeURIComponent;
	window.encodeURIComponent = function(a) {
		if ( !needle.test(a.toString()) ) {
			realnoeuc.call(window, a);
		}
	}.bind(window);
})();
```

**Comment by mapx-** [comment]
add in your vivaldi / chrome (I added those filters only for firefox)

```
||news.yandex.by^$csp=script-src * 'unsafe-inline'
||news.yandex.kz^$csp=script-src * 'unsafe-inline'
||news.yandex.ru^$csp=script-src * 'unsafe-inline'
||news.yandex.ua^$csp=script-src * 'unsafe-inline'
```

**Comment by bogachenko** [comment]
> 
> 
> add in your vivaldi / chrome (I added those filters only for firefox)
> 
> ```
> ||news.yandex.by^$csp=script-src * 'unsafe-inline'
> ||news.yandex.kz^$csp=script-src * 'unsafe-inline'
> ||news.yandex.ru^$csp=script-src * 'unsafe-inline'
> ||news.yandex.ua^$csp=script-src * 'unsafe-inline'
> ```

um. it seems without ads
