### ISSUE TITLE
bmovie related

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4469]
### URL(s) where the issue occurs

`https://bmovies.nl/` or `https://bmovies.nl/watch-halloween-2018-1080p.63774-online-free-bmovies/watching.html?episode_id=117244&s=oserver`
`https://www4.bmovies.film/film/pink-christmas-2018/watching.html`
`https://bmovies.cloud/film/medici-season-1-27253/`
`https://bmovie.org/film/wheels-on-meals/1mjQy`
`https://bmovies.video/online/my-dinner-with-herve/1z6An`
`https://bmovie.me/movie/the-perfect-day/11xwD`
`https://bmovies.life/watch/bumblebee/1uUDU`
### Describe the issue

popup ads/preroll ad
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings

### Notes

`https://bmovie.org/film/wheels-on-meals/1mjQy` 
`https://bmovies.video/online/my-dinner-with-herve/1z6An`
`https://bmovie.me/movie/the-perfect-day/11xwD`
`https://bmovies.life/watch/bumblebee/1uUDU`
has preroll ads before player

**Comment by ghajini** [comment]
popup ads

`https://bmovies.nl/watch-halloween-2018-1080p.63774-online-free-bmovies/watching.html?episode_id=117244&s=oserver`

`https://www4.bmovies.film/film/pink-christmas-2018/watching.html`

`https://bmovie.org/film/wheels-on-meals/1mjQy`

**Comment by ghajini** [comment]
`bmovies.vip/movie/filter/movies`

Popup ads

**Comment by mapx-** [comment]
does this help
`bmovies.*##+js(aeld, , break)`

**Comment by ghajini** [comment]
There's some error at site now saying "too many redirects" 
So I can't test now

**Comment by llacb47** [comment]
this script is detecting devtools and redirecting to homepage: `https://bmovies.vip/bassets/js/jquery.watch.js`

**Comment by uBlock-user** [comment]
`bmovies.vip##+js(aeld, devtoolschange)` should work.

src - https://github.com/sindresorhus/devtools-detect

**Comment by llacb47** [comment]
Can you add that to annoyances list?
