### ISSUE TITLE
watchfree related

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4472]
### URL(s) where the issue occurs

`http://watchfreez.net/movie/oxQDep9v-black-mirror-bandersnatch.html`
`https://www1.watchfree.pw`
`https://www.momomesh.tv`

### Describe the issue
ads
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4
### Settings

- uBO's default settings

**Comment by mapx-** [comment]
`momomesh` not found

**Comment by ghajini** [comment]
`https://www.momomesh.tv`
![screenshot 78](https://user-images.githubusercontent.com/20338483/50547048-5721d080-0c58-11e9-88e0-531ca3233adf.png)

**Comment by mapx-** [comment]
fixed - I "see" the site using an US IP

**Comment by ghajini** [comment]
ads 
`https://www3.watchfree.ac/movie-happy-death-day-2u-2019-watch-free-putlocker.html`
