### ISSUE TITLE
latest uBlock update causes problems with ProtonMail

### ISSUE THREAD

**Issue by B09B1** [uBlockOrigin/uAssets#4474]
ProtonMail is the world's largest secure email provider with over 10 million users worldwide. It is popular among privacy conscious internet users, with significant overlap in the uBlock origin userbase.

### URL(s) where the issue occurs

mail.protonmail.com/inbox (must login first. accounts can be created for free at mail.protonmail.com/signup).

### Describe the issue

In the ProtonMail inbox, the subject lines are vanishing when you look at the emails in the web interface. Disabling UBO fixes the problem, and we have been telling users to remove UBO to fix the problem so they can read their emails. 

### Screenshot(s)

A screenshot of the problem can be found here: https://www.reddit.com/r/ProtonMail/comments/aakms3/how_to_turn_this_thing_back_on/

### Versions

- Browser/version: All
- uBlock Origin version: latest

### Settings

- Happens with Default settings

**Comment by mapx-** [comment]
It's a bad filter in fanboy's annoyances list
`protonmail.com##.top`

To be reported here: https://github.com/ryanbr/fanboy-adblock/issues

waiting the fix just add (tell your users) 
`protonmail.com#@#.top`

@ryanbr
