### ISSUE TITLE
Spotify stops playing music when an audio ad is loaded

### ISSUE THREAD

**Issue by Paviluf** [uBlockOrigin/uAssets#448]
### URL(s) where the issue occurs
https://open.spotify.com/

### Describe the issue
When you listen music on https://open.spotify.com/ after a while an audio ad is loaded and the music stops but the ads is not actually played by Spotify. It's just freezed and you have to refresh the page or manually change song to play audio again.

### Screenshot(s)
https://i.imgur.com/3AzMrGb.png

### Versions
- Browser/version: Firefox 53
- uBlock Origin version: 1.12.4

### Settings
Happen to "many" people with different settings:
https://www.reddit.com/r/uBlockOrigin/comments/6ev5uf/spotify_stops_playing_music_when_an_audio_ad_is/

Thanks !

**Comment by okiehsch** [comment]
Is there any way to consistently reproduce or is this based on your geolocation? 
I now listened to 3 songs in a row without an ad.

**Comment by Paviluf** [comment]
It should happen everywhere. Sometimes it take several songs (up to 10/15) for ad a ad to play.

**Comment by okiehsch** [comment]
I now played this whole album `https://open.spotify.com/album/6EK5AiyrCaxi8Hlp7UfMgr` without being able to reproduce your issue. Looking at the logger two mp3-ads were blocked and the player did not freeze.
![spot](https://user-images.githubusercontent.com/16838044/26993896-6e8debc2-4d65-11e7-9067-b80077397502.PNG)

**Comment by gorhill** [comment]
> Happen to "many" people with different settings

The key is whether it happens with default settings.

**Comment by Mister-Pi** [comment]
I'm having the same issue since today. I have a friend who experienced the problem since almost a week now. Using Chrome + uBlock. The problem doesn't seem to happen very often, for exemple just now, I listened to 2 whole albums and a half before having the playlist to stop because of an ad.

**Comment by Snow8** [comment]
> The key is whether it happens with default settings.

This is happening to me too. I was using uBlock Origin 1.12.4 on Firefox 54beta.

It happens with my modified uBlock as well as default settings.

> Is there any way to consistently reproduce or is this based on your geolocation?
>I now listened to 3 songs in a row without an ad.

To be honest, for me it does not always happen after a certain number of songs. It has more to do with time, from what I have experienced (like when using spotify on android with the unpaid app). Most of the time it happens after ~15-20 minutes for me.

Then the web player of spotify tries to play the ad and greys out the controls, but the actual ad never plays/gets blocked. After a certain amount of time (probably the time the ad would play), controls become available again but playback is not resumed automatically and I cannot simply click the play button as the ad is still "loaded" as currently playing in the bottom left corner (see picture of OP). I usually refresh the page and playback resumes!

**Comment by jleistner** [comment]
I had this issue very consistently for at least the last two weeks.
After about 5-12 songs Spotify tries to play an ad and freezes. The only way to fix this for me is to refresh the page.
I'm running uBlock Origin 1.12.4 with default settings on Chrome 58.0.3029.110 (64-bit). 

According to the logger a couple of ads get blocked successfully without interrupting the playback and then it suddenly just doesn't work anymore.
After blocking the last mp3-ad at the top of the picture Spotify froze.

![spotify](https://user-images.githubusercontent.com/20463017/27004358-6e6de28e-4e08-11e7-87a4-513ab9e1b8de.jpg)

**Comment by gorhill** [comment]
I could reproduce, I left the player on and when I came back it was no longer playing. The output of the logger looks a bit different when this happens.

**Comment by gorhill** [comment]
This is a tentative fix, since it takes a while reproducing the issue. [Force an update](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now) of _"uBlock filters"_.

**Comment by gorhill** [comment]
@okiehsch 

> Looking at the logger two mp3-ads were blocked but the player and the music did not stop.

On my side I have observed that the malfunction kicks in after the request for the media file has been blocked 5 times.

**Comment by okiehsch** [comment]
I can reproduce the issue after the 6th block of the media file, I will now update `uBO filters` and try the same playlist again.

**Comment by okiehsch** [comment]
After updating I could play the whole playlist without issue, so this seems to be fixed on my end.

**Comment by kYwzor** [comment]
After updating the filter it seems to be fixed on my end too. Over 2 hours of playing without any problem.

**Comment by Paviluf** [comment]
Seem to be fixed for me too ! Thanks !

**Comment by thisisjl** [comment]
Could you tell me how can I update the filters?
What I've done, using chrome is:
- Chrome -> More tools -> extensions
- uBlock Origin - > options -> 3-party filters -> Update now

I have also reset the program, but I still have the same issue.

Thanks

**Comment by jleistner** [comment]
@thisisjl 
Make sure you have "uBlock filters" checked. You can force an update by clicking the clock icon and then click "Update Now". 
More information: https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

**Comment by gorhill** [comment]
Also, be sure you do not have another blocker extension interfering, that would defeat uBO's solution.

**Comment by HarveyWilliams** [comment]
Hi, I'm still getting this issue. I am not running another blocker. I have purged all of the caches and updated my 3rd party filters multiple times. There are no clocks on the page.

I am running Firefox 54.0 (32-bit) and uBlock v0.9.5.0.1-let-fixed.

I have noticed that an error call to `https://lon-spclient.spotify.com/melody/v1/logging/jssdk_error` is being made right before the music stops playing (and the advert fails to load):

```
{
  "sdk_id": "harmony:2.18.0-fe97a3a",
  "platform": "Partner spotify web_player",
  "source": "playback.acme-player",
  "source_version": "4.14.0-6a9bc59",
  "type": "PlatformError",
  "message": "Media not supported.",
  "stack": "\"a.prototype._onError@https://open.scdn.co/static/web-player.62a69d9b.js:29:5754\nd@https://cdn.ravenjs.com/3.15.0/raven.min.js:2:6300\n\"",
  "json_data": "{\"track\":{\"uri\":\"spotify:ad:0000000000000000000000202d753e75\",\"fileId\":\"395784f8c16dab28e5f7dbe04290d0d3b75c1a2c\",\"format\":\"MP3\",\"deviceId\":\"###redacted###\",\"resolvedURL\":\"https://d7zatysqm84hv.cloudfront.net/mp3-ad/395784f8c16dab28e5f7dbe04290d0d3b75c1a2c\",\"src_url\":\"https://d7zatysqm84hv.cloudfront.net/mp3-ad/395784f8c16dab28e5f7dbe04290d0d3b75c1a2c\"},\"preloading\":false,\"session_id\":\"###redacted###\",\"playback_id\":\"447061374\",\"license_server\":null}",
  "json_data_version": "1.0.0"
}
```

Any help would be appreciated.

**Comment by gorhill** [comment]
> I am running Firefox 54.0 (32-bit) and uBlock v0.9.5.0.1-let-fixed.

A content blocker is a very important piece of software, and as such due diligence is a requirement, you should be more careful about the content blocker you are using. The one you are using is **not** uBlock Origin. See <>.

**Comment by HarveyWilliams** [comment]
@gorhill Thanks, I feel like an idiot. I thought I was using your fork! I've switched, I'll post something new if it hasn't fixed the issue.

**Comment by CYHSM** [comment]
I am still experiencing the problem! I use uBlock Origin 1.13.2 and updated all filters. Can i do something to solve this? I get only some of these errors when running spotify web : 

GET https://d7zatysqm84hv.cloudfront.net/mp3-ad/2f6b0a914d7fc1f3a5e5b7b66b1d952b83799ef6 net::ERR_BLOCKED_BY_CLIENT

but this only blocks the ad right? There has to be some problem as it does not resume playing after the ad is blocked.

**Comment by gorhill** [comment]
@CYHSM Are you using another blocker?

**Comment by CYHSM** [comment]
@gorhill Thanks for the fast response. 
I found an quite interesting behaviour. I did not have any active other blockers, so i went ahead and installed uBlock in Firefox and it worked fine, so I went back and checked if there were any inactive Blockers in Chrome and i actually had Ghostery (not enabled). I deinstalled it and now it works fine!
I wonder how a disabled extension can have an effect on my browsing?!

**Comment by gorhill** [comment]
> I wonder how a disabled extension can have an effect on my browsing?!

That is not possible. The only sensible explanation is that something was blocking the mp3 file, and it's what the message in the console is saying. This will be for you to figure out why this was happening.

**Comment by Affratus** [comment]
Hi, I'm also having this problem right now, I've purged the filter cache and updated the filter but it's not working. I'm using chrome version 59.0.3071.115 64 bit and UBlock Origin 1.13.2. The other extension that I use is Ublock Origin Extra, but I don't thinks it's the problem, because I'm still stuck on the 6th ads block with or without UBO Extra.

This is the 6th log of the blocked ads from UBO log:
![image](https://user-images.githubusercontent.com/10071459/27979968-30e73314-63a4-11e7-85bd-30a24fc747c8.png)

**Comment by CYHSM** [comment]
Ok, i'm still experiencing this issue. Deactivating all extension except uBlock does not help as it did yesterday... so i'm not sure how to reproduce it. I'll switch to Firefox for now and may investigate it further if I have time. Thanks for your awesome Extension anyway!!!

**Comment by SMed79** [comment]
Try in [firefox portable](https://portableapps.com/apps/internet/firefox_portable) with only uBo installed.

**Comment by Affratus** [comment]
I've tried it on Firefox and there is no problem, then I suspect the problem is within my chrome. So I try running chrome with only UBO and UBO Extra and I have no problem blocking spotify ads. As it turns out my windscribe extension have a built-in ad-block in it.

So for anyone still having trouble with blocking ads on spotify try to check your extension list, there has to be another extension that try to block ads and it's hindering UBO from running properly.

**Comment by dani72092** [comment]
This **just** started happening to me in the last week or so. It's as the other users state, where an ad will "play", but there is no audio. The music fails to resume, even after a reasonable amount of time. I sometimes have to refresh multiple times to get music back. The amount of time between ads seems random. The other extensions that I run are Honey, Smile Always, tab.pics, and Amazon Assistant. I am using the default settings for uBlock, although I've been experimenting with filters without luck for this issue.

Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
uBlock Origin 1.14.20

**Comment by jleistner** [comment]
@dani72092
Try updating the uBlock filters manually: https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

This usually fixes it for me.

**Comment by dani72092** [comment]
@jleistner Thanks for the reply. I've done as you suggested and also relaunched Chrome, but no luck. I'll attempt turning off extensions to see if any of them have a built in ad-blocker as @Affratus suggests.
