### ISSUE TITLE
extreme-down.one

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#449]
Hi,

**Versions**

uBlock Origin 1.12.5.17 / Chromium 58 (64-bit)

**Settings**

Default settings + Liste FR

**URL**

`https://www.extreme-down.one/films-sd/top/44111-john-wick-2-french-hdrip.html`

**Describe the issue**

- Popunder/Redirection
- usenet fake dl link.

**Screenshots**
- http://i.imgur.com/zwqTiRW.png
- http://i.imgur.com/SlRfKoj.png

**Suggested filters**

```
extreme-down.one##script:inject(abort-on-property-write.js, eval)
extreme-down.one##div > a:has-text(anonyme & rapide)
```

**Comment by okiehsch** [comment]
Does 
`||onclkds.com/apu.php$script,redirect=noopjs`
work for you in regards to the Popunder/Redirection?

**Comment by SMed79** [comment]
Yes, fix the issue => no popunder/redirection.
(similar to https://github.com/uBlockOrigin/uAssets/commit/d0f963e16b94)

**Comment by okiehsch** [comment]
@SMed79 I do not see any need for your updated filter on my end,
If I go to `https://www.extreme-down.one/films-sd/top/44111-john-wick-2-french-hdrip.html`
the usenet fake dl link is still hidden.

![has](https://user-images.githubusercontent.com/16838044/29255813-2ca4c604-80a5-11e7-8914-d53769dc4e4b.PNG)

or am I missing something?

**Comment by SMed79** [comment]
Here 

- `https://www.extreme-down.one/films-hd/bluray-1080p/45044-kong-skull-island-multi-bluray-1080p.html`

- http://i.imgur.com/MF4J8dm.png

**Comment by mapx-** [comment]
becomes `extreme-d0wn.net`
