### ISSUE TITLE
Adware/Malware redirection sites

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4493]
These sites should be completely blocked since they exist solely for redirecting users to adware/malware:

`naganoadigei.com`
`decademical.com`
`mutualvehemence.com`
`1bcde.com`
`cobalten.com`
`newsprofin.com`
`speed-open2.com`
`lp.easyziptab.com`

For example, just replace `7259` with some other random no. (like 7256, 7257, 7258, etc.) in the following URLs:

`naganoadigei.com/imp/7259/`
`decademical.com/imp/7259/`
`mutualvehemence.com/imp/7259/`
`1bcde.com/imp/7259/`

Here's another example:

`cobalten.com/afu.php?zoneid=1365143&var=1492756`

A quick search for each of these domains will bring up their notoriety. Ref. [1](https://www.quora.com/What-is-naganoadigei-com-and-is-its-web-value-really-625m-USD), [2](https://askubuntu.com/questions/1087450/how-to-remove-naganoadigei-com-popup-virus), [3](https://broadbandforum.co/threads/bsnl-broadband-ad-injection-random-redirection-to-malware-websites.169151/)

`naganoadigei.com` seems to have been recently included in Peter Lowe's list, which is part of uBO's default setup, so it may be skipped.

`cobalten.com` and `newsprofin.com` are there in Dan Pollock's list but that is not part of uBO's default setup. Rest of the domains have not yet been included in any other filter/lists, so uBO should take care of them as well.

**Comment by mapx-** [comment]
@pgl 

@in4u  you should report such domains to lists like `Peter Lowe's`  and report here the original pages where you get the redirections / popups / popunders

**Comment by in4u** [comment]
Okay @mapx-, will do so.  Can you please point me towards the actual repo where I should report such issues?

**Comment by mapx-** [comment]
As you can see above I cc-ed Peter Lowe, lets see if he can add those domains to his list.

Alternative you could report the domains to malware domains list:
https://www.malwaredomains.com/?page_id=13

**Comment by in4u** [comment]
Is there any way to submit such issues without emailing somewhere?

[This](https://pgl.yoyo.org/adservers/) is the list's homepage as per uBo. I tried to find a way to submit issues on that site and there is supposed to be a form which seems to have been disabled. There's this `Ad server submission disabled until further notice`. So, he's not taking submissions?

**Comment by mapx-** [comment]
only @pgl  could respond your question, otherwise ... emailing the issues

**Comment by in4u** [comment]
I am guessing even emailing won't be of much help. He laments that `Unfortunately it's probably not worth submitting anything at the moment - spam has taken over. 10,000 mails a month to sift through, even with automated checking, is just too much extra. Fuckin spammers.`

Let's just wait for a few days and see if he responds here. It'd be great if he can be contacted on Github, otherwise you guys may have to take up the mantle!

**Comment by mapx-** [comment]
As I said above: you just report the original pages and together the classical fix (for popups, redirections) we can add those malicious domains as part of the fix
