### ISSUE TITLE
[Anti-adblock] asiannice.com

### ISSUE THREAD

**Issue by onmyouji** [uBlockOrigin/uAssets#4494]
### URL(s) where the issue occurs

`https://asiannice.com/drama/shinya-no-damekoi-zukan/watch/`

### Describe the issue

Website shows anti-adblock notification.

### Screenshot(s)

![image 7](https://user-images.githubusercontent.com/8424198/50573529-1b2d6d80-0e08-11e9-96b5-9eed9ffbe73b.png)

### Versions

- Browser/version: Chromium 71.0.3578.98
- uBlock Origin version: v1.17.4

### Settings

![50498525-3a2ca800-0a74-11e9-9a1c-aeb1fb22d2b8](https://user-images.githubusercontent.com/8424198/50573542-55970a80-0e08-11e9-95c7-ce98ccf9e7d6.png)

**Comment by bogachenko** [comment]
@onmyouji enable scriptlets. otherwise it https://github.com/uBlockOrigin/uAssets/commit/315040e027bf81a8a61bf1cc63211137677c8d19 will not work
