### ISSUE TITLE
digitaltrends.com - Pictures not loading, despite being available. A Script?

### ISSUE THREAD

**Issue by Xevion** [uBlockOrigin/uAssets#4496]
### URL(s) where the issue occurs

`https://www.digitaltrends.com/photography/best-camera-bags/2/`

### Describe the issue

Pictures for each of the Camera Bags in the list dissapear while uBlock Origin is enabled.
The logger shows them being loaded but a lot of scripts are being blocked...
Perhaps they are loaded or visualized dynamically by Javascript?

### Screenshot(s)

![image](https://user-images.githubusercontent.com/44609630/50577623-6ab46f00-0df1-11e9-9e45-725091c2b278.png)

### Versions

- Google Chrome | 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)
- uBlock Origin 1.17.4

### Settings

- No changes made, except for enabling and disabling to confirm uBlock's interactions.
- Here are [my Filter Lists](https://i.imgur.com/Zgf3iUb.png) if you require them for any reason.

### Notes

I haven't done much. I'm not sure how uBlock works other than hardcoded lists, and thus, any investigation I do won't yield useful information.

**Comment by okiehsch** [comment]
I can't reproduce with a default setup, which includes all filter lists you use.
![image](https://user-images.githubusercontent.com/16838044/50577766-8474a700-0e2f-11e9-8371-3bd3b1133e61.png)

The only way for me to reproduce the pictures not loading is to manually block
`ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js`
so you can look if that is somehow blocked on your end,
I can block all other third-party scripts and th pictures will still load on my end,

**Comment by Xevion** [comment]
Strange. Maybe I have done something unintentionally? I was checking if it was an extension but after reloading once, it started loading images as it should. Strange.
I suppose this confirms that it's either some strange outside force, slow internet/unable to connect to CDNs/paranormal internet activity and not uBlockOrigin doing it. Closing.

**Comment by okiehsch** [comment]
Actually, I just looked at our screenshot and noticed that it shows a non-loading picture from page 3, while your link opens page 2.
If I follow your link and scroll down to page 3 all pictures of page 3 are indeed not loading.
I doubt that this has anything to do with uBlock though, I will have a look.

**Comment by okiehsch** [comment]
Yes, this is a site issue.

If I

- Disable `uBlock`
- Go to `https://www.digitaltrends.com/photography/best-camera-bags/2/`
- Scroll down until I reach page 3

All pictures of that page are not showing up.
![unbenannt](https://user-images.githubusercontent.com/16838044/50577991-c1429d00-0e33-11e9-9a0a-1f36a6471f27.PNG)
