### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#4497]
ads @mapx- @okiehsch 
![1](https://user-images.githubusercontent.com/8535285/50580978-4320dd80-0ea9-11e9-9bff-baf9e0a0fa4f.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4498
https://github.com/uBlockOrigin/uAssets/issues/4499
https://github.com/uBlockOrigin/uAssets/issues/4500

All yandex subdomains can be discussed in this issue, there is no need to open a seperate issue for every one of them.

FYI, `yandex.ru##+js(set-constant.js, Math.random, trueFunc)` fixes all issues on my end using Chrome/Chromium, but does not work with Firefox except for https://github.com/uBlockOrigin/uAssets/issues/4499

**Comment by bogachenko** [comment]
@okiehsch Advertising not deleted. The filter that you gave me only for yandex.ru/pogoda

**Comment by bogachenko** [comment]
@okiehsch look 
![default](https://user-images.githubusercontent.com/8535285/50582806-3e642580-0eb9-11e9-9dd6-5ef2ae945371.png)
why did you close them all?

**Comment by bogachenko** [comment]
just fucking helped @okiehsch

**Comment by okiehsch** [comment]
What is your problem?
I linked to all of the issues you opened.

> #4498
> #4499
> #4500
> 
> All yandex subdomains can be discussed in this issue, there is no need to open a separate issue for every one of them.
> 
> FYI, `yandex.ru##+js(set-constant.js, Math.random, trueFunc)` fixes all issues on my end using Chrome/Chromium, but does not work with Firefox except for #4499

Like I said all yandex subdomains can be discussed here, they all have the same issue anyway.

**Comment by bogachenko** [comment]
@okiehsch if they had the same problem the filter you gave me would work for all subdomains (and this filter would give a shit on useragent, whether chrome or firefox) and not just for yandex.ru/pogoda

**Comment by okiehsch** [comment]
The filter works for all opened issue on my end using Chromium/Chrome


> What is your problem.
rough

> just fucking helped for me
 
That sounds to me like you have a problem.

**Comment by bogachenko** [comment]
@okiehsch yae. but the banner remained. (which is above)

**Comment by okiehsch** [comment]
I can't reprodcue the banner, maybe it depends on ones location.
![image](https://user-images.githubusercontent.com/16838044/50584959-e30f4480-0e72-11e9-84ad-3ec08ce20188.png)

**Comment by bogachenko** [comment]
@okiehsch shit
![default](https://user-images.githubusercontent.com/8535285/50584992-e502f300-0ec6-11e9-882f-1ba0db905638.png)

**Comment by okiehsch** [comment]
For `tv.yandex.ru`
````
tv.yandex.ru##[class$="4__wrapper"]
````
hides the ads with Firefox on my end.

**Comment by bogachenko** [comment]
@okiehsch number 4 is it static? isn't she changing?

**Comment by bogachenko** [comment]
![2019-01-02 19 52 16-fullpage](https://user-images.githubusercontent.com/8535285/50585212-03b5b980-0ec8-11e9-9d6f-03ada862e89f.png)
and can I hide this space?

**Comment by bogachenko** [comment]
@okiehsch advertising appeared. now this filter (which I have in my filters) is not displayed in the log

> 
> 
> For `tv.yandex.ru`
> 
> ```
> tv.yandex.ru##[class$="4__wrapper"]
> ```
> 
> hides the ads with Firefox on my end.

**Comment by mapx-** [comment]
@bogachenko did you try using ruadlist JS fixes ?
https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes

**Comment by bogachenko** [comment]
@mapx- I don't want to install this script (or any other), dude, you're a magician, you can do anything

**Comment by mapx-** [comment]
@bogachenko , the problem is with firefox ==> due to a bug on their side uBo (and other addons) cannot inject scriptlets in pages using CSP script-src directives.

Tampermonkey (used by ruadlist fixes) - as a userscript manager - managed somehow to workaround this bug in FF design => ruadlist fixed working fine.

**Comment by bogachenko** [comment]
@mapx- 

>somehow to workaround 

???
:)

**Comment by bogachenko** [comment]
@mapx- Okay, how did you delete it with the help of the scriptlet?

**Comment by mapx-** [comment]
Test yourself => install tampermonkey then ruadlist fixes. Already done ?

**Comment by bogachenko** [comment]
done done i am the fucking done

**Comment by mapx-** [comment]
Provide only useful feedback. Thanks. Are you meaning does not work for you ?

**Comment by bogachenko** [comment]
@mapx- works. but this is a superfluous addition, but my laptop will not be very happy about memory loss due to this extension

**Comment by mapx-** [comment]
Well, this is a special case for a lot of russian sites for which the guys at ruadlist have their custom fixes.
And for firefox there is the CSP bug, nothing we can do.

**Comment by mapx-** [comment]
`news.yandex`  has the same csp issue.
I provided only CSP working filter which are working fine (CSP bug avoids only the injecting of the scriptlets)

**Comment by mapx-** [comment]
try this 1 for tv.yandex (but as for news.yandex there are little breakings .. because some of the first-party scripts blocked contain the jquery library used on some pages)

`||tv.yandex.ru^$csp=script-src * 'unsafe-inline'`

see if breaks some functionality

**Comment by mapx-** [comment]
yeah, breaking the entire page

**Comment by bogachenko** [comment]
@mapx- 

>yeah, breaking the entire page

exactly

**Comment by bogachenko** [comment]
@mapx- @okiehsch 

Hey buddyZZZZZ, I seem to have blocked (all banners except one). You can check?

```
tv.yandex.ru##HTML > HEAD + BODY > DIV > DIV > DIV
tv.yandex.ru##HTML > HEAD + BODY > .mount > DIV > DIV + .header + .content > .main-controller > .main-controller__grid-wrapper > .recommended-top + .filters + SECTION > DIV > .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + DIV + :last-child
tv.yandex.ru##HTML > HEAD + BODY > .mount > DIV > DIV + .header + .content > .main-controller > .main-controller__grid-wrapper > .recommended-top + .filters + SECTION > DIV > .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + .grid__item + DIV
```

can you check these filters and if you can block the last one? and how can I cut them? bring in human form?

![2019-01-02 21 41 55-fullpage](https://user-images.githubusercontent.com/8535285/50588688-4fbc2a80-0ed7-11e9-947f-7ec39c7ffb30.png)

**Comment by bogachenko** [comment]
lol hahahahaha
`tv.yandex.ru##.main-controller > div > div:last-child`

![2019-01-02 21 51 28-fullpage](https://user-images.githubusercontent.com/8535285/50588967-a413da00-0ed8-11e9-8f47-b35e5e1b35fb.png)

**Comment by bogachenko** [comment]
@okiehsch  Why is this?

```
||mc.yandex.ru/watch/*$script,first-party,redirect=silent-noeval.js
||mc.yandex.ru/metrika/*$script,first-party,redirect=silent-noeval.js
```

on the main page I deleted the banner like this, I don’t know ads for some reason. Strange
```
yandex.ru,yandex.ua,yandex.by##+js(cookie-remover.js, /adb|bltsr/)
```

**Comment by bogachenko** [comment]
There is a lot of advertising in search queries, VERY MUCH!

My request in screenshot `https://yandex.ru/search/?text=%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C%20%D1%85%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%20%D0%B2%20%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B5&lr=213`

On the screenshot in red outlined the search results with the label "Реклама" (eng ADS)
![2019-02-17 07 09 37-fullpage](https://user-images.githubusercontent.com/8535285/52904742-68648200-3284-11e9-80ab-f4d94a13b6b9.png)

**Comment by mapx-** [comment]
`yandex.ru##.serp-item:has-text(/реклама/i)`

**Comment by bogachenko** [comment]
@mapx- It does not work. Because the word "реклама" is a picture.

https://avatars.mds.yandex.net/get-serp/34166/serpt-jht3e2090.png/orig

**Comment by mapx-** [comment]
Its what works for me in Firefox / chrome.

**Comment by bogachenko** [comment]
How can this work if it is a picture? It is a PNG format, even in theory it cannot work.

**Comment by mapx-** [comment]
They served the page using a normal `реклама` text.
I tried again and again and now I get the image.

**Comment by bogachenko** [comment]
ooo, okay
bro do you have any idea how to cut it all out?

**Comment by mapx-** [comment]
Probably this is a good example for an AI
https://arxiv.org/pdf/1805.09155.pdf

**Comment by bogachenko** [comment]
@mapx- is it so thin trolling?

**Comment by bogachenko** [comment]
maestro @mapx- explain why it does not work and how to make it work?
`yandex.ru##.serp-list_left_yes.serp-list:has(:matches-css(background-image: /.png/origin/i):xpath(../..))`

**Comment by mapx-** [comment]
I don't jnow what do you want to do but the special chars in regex have to be escaped

something like:
`yandex.ru##.serp-list_left_yes.serp-list:has(:matches-css(background-image: /\.png\/origin/i):xpath(../..))`

**Comment by mapx-** [comment]
`matches-css` should addressed some div / class ... so try with `.direct-label`

yandex.ru##.serp-list_left_yes.serp-list:has(.direct-label:matches-css(background-image: /\.png\/origin/i):xpath(../..))

**Comment by mapx-** [comment]
or
`yandex.ru##.direct-label:matches-css(background-image: /\.png\/origin/i):xpath(../..)`

**Comment by bogachenko** [comment]
@mapx- 
its not work
`yandex.ru##.serp-list_left_yes.serp-list:has(.direct-label:matches-css(background-image: /^url\(https:\/\/avatars\.mds\.yandex\.net\/get\-serp\/[^\s]{15,25}\.png\/orig\)/):xpath(../..))`

this too
`yandex.ru##.direct-label:matches-css(background-image: /^url\(https:\/\/avatars\.mds\.yandex\.net\/get\-serp\/[^\s]{15,25}\.png\/orig\)/):xpath(../..))`

хочу здохнуть

**Comment by bogachenko** [comment]
stop

**Comment by bogachenko** [comment]
> png\/orig\

**Comment by bogachenko** [comment]
not. again does not work.

`yandex.ru##.serp-list_left_yes.serp-list:has(.direct-label:matches-css(background-image: /^url\(https:\/\/avatars\.mds\.yandex\.net\/get\-serp\/[^\s]{15,25}\.png\/orig)/):xpath(../..))`

**Comment by mapx-** [comment]
for now I get the text `реклама`, not the image

**Comment by bogachenko** [comment]
in opera I have text, in firefox :walking_man:  image

**Comment by bogachenko** [comment]
what's wrong? do i have the regular expression right?

**Comment by bogachenko** [comment]
it doesn't work either :walking_man: 
`yandex.ru##:xpath(//ul[@class='serp-list serp-list_left_yes']):has(.direct-label:matches-css(background-image: /^url\(https:\/\/avatars\.mds\.yandex\.net\/get\-serp\/[^\s]{15,25}\.png\/orig)/))`

**Comment by mapx-** [comment]
for example this 1 is "working"
`yandex.ru##*:matches-css(background-image: /https:\/\/avatars\.mds\.yandex\.net\/get-serp\//i):xpath(../..)`

the problem is is hiding a lot more (legitimate content too), because they are adding invisible (empty pics) on normal content too, in the same folder.

this is why I told you above we need AI systems

**Comment by bogachenko** [comment]
![Безымянный](https://user-images.githubusercontent.com/8535285/54595585-d8545c80-4a2a-11e9-97dd-296e2b2506a6.png)

**Comment by bogachenko** [comment]
you can not deceive them like that? I understand this RU site and people from Canada have no interest, but this site is a huge problem for the region RU (exp. Yandex Direct), but did you (team) create scriptlets for specific sites?
exp. pornhub-popup-defuser.js adfly-defuser.js xvideos.com.js twitch-videoad.js golem.de.js 
***
+ I'll be honest I googled a little about you, found your account https://greasyfork.org/en/users/10606-mapx  you have already created a similar

**Comment by bogachenko** [comment]
@mapx- anyway. Thanks for your time today. even though we came to zero

**Comment by mapx-** [comment]
The cosmetic filters in this case cannot help (indistinguishable differences on image files).

Someone should find the piece of code where they associate the pics with the various search results.

**Comment by bogachenko** [comment]
heh well I can't even find" Hello world " in js. that's why I aske**d** for help

**Comment by mapx-** [comment]
maybe it could be used /integrated a javascript ocr-library like:
http://antimatter15.com/ocrad.js/demo.html
or
http://tesseract.projectnaptha.com/

but only the experts could say if it's possible (and which are the costs ..) @jspenguin2017 @gorhill @gwarser

**Comment by jspenguin2017** [comment]
OCR is likely going to be too slow, maybe we can hash the image... 

Is there a test link?

**Comment by bogachenko** [comment]
test link of what? Images with the words "Реклама"?

Реклама
`https://avatars.mds.yandex.net/get-serp/39859/serpt-bdok4860.png/orig`

Empty (used for non ad requests to confuse the blocker. @mapx- talked about it)
`https://avatars.mds.yandex.net/get-serp/39011/serpt-iy2m31241.png/orig`

**Comment by jspenguin2017** [comment]
Do you have a link to a page with this issue?

**Comment by bogachenko** [comment]
`https://yandex.ru/search/?text=%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C%20%D1%85%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%20%D0%B2%20%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B5&lr=10636`

Here she is. Advertising appears if you type in a request
`Купить что-то в каком то городе` eng. `Buy something in some city`

**Comment by jspenguin2017** [comment]
I don't have a solution right now, it's probably not going to be trivial...

**Comment by bogachenko** [comment]
@jspenguin2017 thanks anyway

**Comment by gwarser** [comment]
`yandex.ru##:xpath(//li[contains(@class, serp-item)]//a[string-length(@data-counter) > 2000]/ancestor-or-self::li)`?

**Comment by bogachenko** [comment]
@gwarser Holy shit it works but i really don't know how long this is gonna last. the bastards from yandex will probably fix it soon.

**Comment by bogachenko** [comment]
@mapx- @gwarser @jspenguin2017 thank you all.
***
@jspenguin2017 can be closed https://github.com/NanoMeow/QuickReports/issues/845

**Comment by bogachenko** [comment]
@gwarser Stop. 2 bugs.
![1](https://user-images.githubusercontent.com/8535285/54725483-29696b00-4b67-11e9-9bb0-c9e3533fc950.gif)
1. Hides most non ad requests. (This does not always happen. However, when this happens, there are only 3 requests on the page.)
2. there is advertising.

**Comment by bogachenko** [comment]
@mapx- @okiehsch `http://delovoe.tv/event/Putin_poruchil_uchest_mnenie_naseleniya_pri_stroitelstve_svalki_v_Shiese/`


On this site there is a player, there antiadblock. Here people have added a solution https://github.com/AdguardTeam/AdguardFilters/commit/49c9f8fa343b4253b873f92939a488d2d66919c9, it works but is it possible to somehow unlock this player differently without unlocking awaps.yandex.net

**Comment by okiehsch** [comment]
> is it possible to somehow unlock this player differently without unlocking awaps.yandex.net ?

No, redirecting that script will not work.

**Comment by llacb47** [comment]
Getting ads on `https://yandex.ru/pogoda/new-york/maps/temperature` even with Russian lists

**Comment by okiehsch** [comment]
@dimisa-RUAdList

![image](https://user-images.githubusercontent.com/16838044/62405477-c7e9ec00-b59d-11e9-9246-46493ea3da9e.png)

**Comment by llacb47** [comment]
Also ads on `https://yandex.ru/pogoda/new-york`

Test: 
```
yandex.ru###eicg:nth-ancestor(1)
yandex.ru##[class^="y4594aw9N7qkzg"]
```
Or network filters?
`||yandex.ru/weather/1sc700b79/99c100r9/*`

**Comment by dimisa-RUAdList** [comment]
@okiehsch 
Yandex is one of the largest portals in Runet. And for its sections are responsible for different webmasters. Those who deal with news and weather react very quickly to ad blocking. Therefore, adding a rule in filters will have a very short-term effect, most likely a few hours. This problem is known and is solved with the help of RU Adlist JS Fixes: https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes

**Comment by bogachenko** [comment]
How to bypass paywall on music.yandex.ru?

When entering from the mobile version of the browser (I use firefox) to the main page of the Yandex.Music service, a banner is displayed on which there are 2 buttons: Listen in the application <Слушать в приложении> (an aggressive banner appears in the application with the requirement to buy a subscription) and Pamper yourself, buy a Yandex Plus subscription <Побаловать себя, купить подписку Яндекс.Плюс>. Both of these buttons are a paywall.
