### ISSUE TITLE
yandex.ru/pogoda

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#4499]
ads @mapx-  @okiehsch 
![2019-01-02 16 17 56-fullpage](https://user-images.githubusercontent.com/8535285/50581069-13260a00-0eaa-11e9-9cd7-d4601e098aa7.png)

**Comment by bogachenko** [comment]
`||yandex.*/pogoda/$first-party,inline-script`
it breaks the site

**Comment by okiehsch** [comment]
`yandex.ru##+js(set-constant.js, Math.random, trueFunc)`
seems to work on my end.

**Comment by bogachenko** [comment]
@okiehsch you are a magician can be closed

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4497
