### ISSUE TITLE
vooxe.com - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#450]
Anti adb warning is displayed in the video player on http://video-static.vooxe.com.

**SS:** https://i.imgur.com/W7djfDz.png
**Error URL:** `http://video-static.vooxe.com/index.html?gameid=b0f7ec2784174fdce2f2de20d3941d96`

The above video is embedded on the page http://www.gamesgames.com/game/frizzle-fraz.

This can be fixed by:
` @@||vooxe.com/player/js/ads.js$script`

_**Note:** Using uBO 1.12.4 on Chrome 59 with default settings and filters._

**Comment by mapx-** [comment]
`vooxe.com##script:inject(abort-on-property-read.js, canRunAds)`
