### ISSUE TITLE
aulete.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4501]
### URL(s) where the issue occurs

`http://www.aulete.com.br/a`

### Describe the issue

Dictionary definitions are displayed in a small box even on huge monitors.

Adding `aulete.com.br##.definicao_verbete_homologado_interna:style(height:100% !important;)` fixes this.

### Versions

- Browser/version:  Firefox 64.0 (64-bit)
- uBlock Origin version: 1.17.4

### Settings

+Annoyances

**Comment by okiehsch** [comment]
Thanks.

**Comment by adranger** [comment]
@Yuki2718 please add this to AdGuard too to benefit more users.

**Comment by Yuki2718** [comment]
@adranger Please open an issue in AdguardFilters next time.
