### ISSUE TITLE
streamiz-filmze.me

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4505]
### URL(s) where the issue occurs

`https://streamiz-filmze.me/13869-kickboxer-1.html`

### Describe the issue

ads
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
### URL= `https://uqload.com/8x8odals98dw.html

### Issue =
This filter from ublock filters
`||uqload.com^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.googletagmanager.com *.amung.us`

Is preventing captcha loading

![IMG_20201008_001856](https://user-images.githubusercontent.com/20338483/95374449-f5e26300-08fb-11eb-9b5b-67afcb5df8e3.jpg)

Also scriptlet filter needs to be updated

**Comment by mapx-** [comment]
removing csp filter and disabling scriptlet one I get no popups

`||uqload.com^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.googletagmanager.com *.amung.us,badfilter`

**Comment by ghajini** [comment]
Yes CSP filter and scriptlet filter not required
