### ISSUE TITLE
cafemovie.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4506]
### URL(s) where the issue occurs

`https://cafemovie.to/movie/i-feel-pretty-Ln0jz2D6/watch#vmVbqyvrroDXRnxd`

### Describe the issue

ads
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

-  uBO's default settings

**Comment by mapx-** [comment]
What type of ads ? popups ?

**Comment by ghajini** [comment]
Popups ads sometimes

**Comment by okiehsch** [comment]
> Popups ads sometimes on clicking
Download hd or stream in hd(fake)

````
cafemovie.to##.btn-pixel
cafemovie.to##.btn-streaming
````
