### ISSUE TITLE
movies.unlimitedwave.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4509]
### URL(s) where the issue occurs

`https://movies.unlimitedwave.com/dangal-full-movie-online-2016`

### Describe the issue
ads
and fake links for downloading movie
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

-  uBO's default settings

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/99a13d866a10020f0d9e12e99c1e38c8d8cdb6f3
