### ISSUE TITLE
tamilrockers.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4513]
### URL(s) where the issue occurs

`http://tamilrockers.to/index.php/videos/view-15552-hits-of-2018-volume-02-tamil-songs-audio-jukebox/`

### Describe the issue
ads
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

uBO's default settings

**Comment by ghajini** [comment]
Google search function in site (upper right corner) is broken

**Comment by ghajini** [comment]
some filters(may be easylist) causing search function on site to break

**Comment by mapx-** [comment]
tested here
`http://tamilrockerss.ch/index.php/videos/view-15552-hits-of-2018-volume-02-tamil-songs-audio-jukebox/`
and still working for me

**Comment by ghajini** [comment]
iam using search bar on main homepage
`http://tamilrockerss.ch/`

**Comment by mapx-** [comment]
test now (first updating)

**Comment by ghajini** [comment]
got it working
