### ISSUE TITLE
yesmovies.rs(antiadblock)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4514]
### URL(s) where the issue occurs

`https://yesmovies.rs/watch-the-greatest-showman-2017-1080p.39939-online-free-yesmovies/watching.html`

### Describe the issue

antiadblock
## Screenshot(s)

![screenshot 82](https://user-images.githubusercontent.com/20338483/50601273-b7737500-0ed9-11e9-9d38-9ac03cb56572.png)

### Versions

- Browser/version: chrome stable
 uBlock Origin version: 1.17.4
### Settings

 uBO's default settings

**Comment by ghajini** [comment]
`https://yesmovies.rs/watch-the-mandalorian-season-1-2019-1080p.14687-online-free-yesmovies/watching.html?episode_id=133616&s=oserver`

Popups

**Comment by mapx-** [comment]
no popup for me

**Comment by ghajini** [comment]
`yesmovies.rs`

**Comment by mapx-** [comment]
still nothing

**Comment by ghajini** [comment]
https://user-images.githubusercontent.com/20338483/72223474-2972a580-3595-11ea-8c57-d64a40b7e3c6.png

https://user-images.githubusercontent.com/20338483/72223477-3394a400-3595-11ea-8cf6-6bcdae4f0707.png

**Comment by llacb47** [comment]
I get popup going to `wedeegut.net`

**Comment by okiehsch** [comment]
In can reproduce.

**Comment by ghajini** [comment]
`https://yesmovies.vc/yesmovies`

popup ads

**Comment by ghajini** [comment]
`https://yesmovies.ag/movie/enola-holmes-101476/1-1/watching.html`
player doesn't load ,loading only
