### ISSUE TITLE
zdnet.com - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#452]
Ads are displayed above, below and in the sidebar of articles on http://www.zdnet.com.

**SS:** https://i.imgur.com/0s7Pz63.png (Full page screenshot showing the ads)
**Error URL:** http://www.zdnet.com/article/chrome-is-the-most-popular-web-browser-of-all/

**More info:** https://forums.lanik.us/viewtopic.php?p=109841#p109841

While these ads are blocked by `||tags.tiqcdn.com/utag/` as seen in the above link, this filter also breaks some other important site functionality.

***Note:** Using uBO 1.12.4 on Chrome 59 with default filters and settings.*

**Comment by SMed79** [comment]
Try to alow or noop this **blank** script
`zdnet2.cbsistatic.com/fly/js/utils/advertisement-`

**Comment by gorhill** [comment]
Does this work?

    ||zdnet.com/mds/recommendation/*&promo=$xmlhttprequest

**Comment by SMed79** [comment]
Good catch. Yes the filter work.

**Comment by gotitbro** [comment]
@gorhill Ads still load in the right sidebar.

**SS:** https://i.imgur.com/unXe5N4.png

They are loaded through this:
`http://www.zdnet.com/mds/xhr/right-rail/?promo=`

**Comment by gotitbro** [comment]
@gorhill @okiehsch Still more ads are loaded at the bottom on the home page.

**SS:** https://i.imgur.com/e8OA0tF.png
**Error URL:** http://www.zdnet.com

These are loaded through: `http://www.zdnet.com/mds/xhr/horizontal/?promo=`

Please look into this, thank you.

**Comment by mapx-** [comment]
add also
`zdnet.com###taboola-below-home-thumbnails-homepage`

**Comment by gotitbro** [comment]
@mapx- Seeing these ads again `zdnet.com` (ads in the sidebar, middle and bottom of the webpage).

**Error URL:** 
`https://www.zdnet.com/article/windows-warning-tech-support-scammers-are-ramping-up-attacks-says-microsoft/`

_**Note:** Using uBO 1.16.0 on Chrome 66 with the default filters and settings._

**Comment by terrorist96** [comment]
I'm seeing these ads now.

**Comment by mapx-** [comment]
What ads ? screenshot + specific page ?

**Comment by terrorist96** [comment]
Same as the first post.

**Comment by stephenhawk8054** [comment]
Video cannot play.

URL:
`https://www.zdnet.com/video/cybercrime-college-dark-web-courses-teach-wannabe-hackers-how-to-build-botnets/`

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77662
  cosmetic: 39744
  scriptlet: 16319
  html: 607
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30569-131, 5m
    ublock-badware: 3573-1, 5m
    ublock-privacy: 184-0, 5m
    ublock-abuse: 81-0, 5m
    ublock-unbreak: 1733-0, 5m
    easylist: 61826-449, 13m
    easyprivacy: 26499-485, 5m
    urlhaus-1: 7394-0, 5m
    plowe-0: 3690-3, 5m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 709
  launchFromSelfie: false
popupPanel: 
  blocked: 21
```
</details>

Proposed filter:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=zdnet.com`

**Comment by mapx-** [comment]
@ryanbr  maybe you want to fix it in EL
