### ISSUE TITLE
gplinks.in [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4520]
URL(s) where the issue occurs

`http://gplinks.in/EWu8`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 71 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.4

Settings

Default

**Comment by dumbusernameidk** [comment]
name changed to `zerooman.com` and has popups.

**Comment by dumbusernameidk** [comment]
new name `groundslife.com`

**Comment by ghajini** [comment]
`gplinks.in/HcqLKQy5`
3rd party xhr's requests

**Comment by ghajini** [comment]
Captcha blocked, hence not able to go to target link

`https://gplinks.in/PhPFLUx`

**Comment by mapx-** [comment]
I clicked verify and then I got `captcha` box

**Comment by ghajini** [comment]
Sorry false alarm, captcha box was there actually baked in garbage text on site😅😅

**Comment by ghajini** [comment]
`https://gplinks.co/ekpx`
After captcha verification, clicking on **unlock link** results in popup ads
![IMG_20201106_111131](https://user-images.githubusercontent.com/20338483/98330681-ea7c7780-2020-11eb-9e96-b8780f1d5ff6.jpg)

**Comment by okiehsch** [comment]
Where is the link to the destination page?
I don't see any even if I disable uBO.

**Comment by ghajini** [comment]
correct i am tryinng to download movie from `movieflix360.in` and arrived at gplinks.co then final link giving error400 server error
(`https://video-downloads.googleusercontent.com/AGQNM9Kk4maZ_nMBPu10mFvGyOH6s7mxsh1m1y4RJ5wTyHg2SOXLziWFm25ZD2v8QKVpjDOu2eOU0cnor5pdVBIAoAvrETwvBtakA1AXXhUEregnU4MuDqZAAUhRM9M7ACSl-nhaPjqVUsBp41xRuuE0bNzcYuKymhZMqYq8BVoYsokfMfQwgO6xW4kGif7kiReR5l4SFOx9o3oY8Sc20o4lRrveJpS5gBG42EORgodcyXjGY1h_KmM`)

**Comment by okiehsch** [comment]
OK, my filters work for you?

**Comment by ghajini** [comment]
your filters hides `get link` button

**Comment by okiehsch** [comment]
I don't see a get link button, well I will remove it until someone can .

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e0c55e020b733ebaed24b5b0e1a09c0bbc7695d0

**Comment by ghajini** [comment]
did you verify captcha > next page > click `unlock link`(opens new popup in new tab while links unlocks givinng `get link` button

**Comment by okiehsch** [comment]
Does
`gplinks.co##+js(disable-newtab-links)`
work for you?

**Comment by ghajini** [comment]
yes work

**Comment by ghajini** [comment]
`https://gplinks.co/eChFP`
ad ridden website(needs adclick to proceed further) .....firefox

**Comment by mapx-** [comment]
you mean this page ?

![image](https://user-images.githubusercontent.com/10303732/105376657-43b07c00-5c0a-11eb-8efc-a911ac70f3ea.png)

**Comment by mapx-** [comment]
even disabling uBO I get nothing different

**Comment by ghajini** [comment]
`gplinks.in/HcqLKQy5`

this is last page after click ,clicks with ubo disabled

https://user-images.githubusercontent.com/20338483/105390651-47122a80-5c3f-11eb-855a-cb8dee4a7d61.png

**Comment by ghajini** [comment]
Valid test link
May be nsfw
Short link=
`https://gplinks.co/RnLhVj`

Destination site=
`https://mega.nz/folder/HkhxzRJI#UqsNr4XW5GqvLf6f5zF23Q`

**Comment by lain566** [comment]
@ghajini Test these filters. 

```
adomainscan.com##.iframe-overlay
adomainscan.com,mynewspost.in###wpsafe-wait1,#container-countdown
adomainscan.com,mynewspost.in###wpsafe-snp:style(display: block !important;)
adomainscan.com,mynewspost.in###wpsafe-generate:style(display: block !important;)
adomainscan.com##.footer-btns:style(display: block !important;)
mynewspost.in##.box-main > div[style]:not(:has(#wpsafe-snp))
*$frame,domain=adomainscan.com
```

**Comment by ghajini** [comment]
That will fix @lain566 tested on firefox A.

**Comment by ghajini** [comment]
`https://gplinks.co/SCHwv`
pls revise filters, stuck at page
