### ISSUE TITLE
[Anti-AdBlock] mercurynews.com

### ISSUE THREAD

**Issue by zestysoft** [uBlockOrigin/uAssets#4523]
### URL(s) where the issue occurs

`https://www.mercurynews.com/2019/01/01/hot-move-for-real-estate-agents-relocation/`

### Describe the issue

Subscription nag appears.

### Screenshot(s)
![deleteme](https://user-images.githubusercontent.com/742554/50621052-496a8600-0eb8-11e9-9b28-2baade59725d.jpg)

### Versions

- Browser/version: Firefox Quantum 64.0 (64-bit)
- uBlock Origin version: uBlock Origin v1.17.4

### Settings

Default settings.

### Notes

Attempted to select elements that appear "over" the content to add them to my filter list -- Eventually I can see the content but am unable to scroll.

**Comment by zestysoft** [comment]
When I refresh, the subscription message changes.
Here are the rules that expose the article (but don't fix the scroll issue):

www.mercurynews.com##.x-editable-css-bg.bg4.centered.text-center.Mg2-bg-white.body.width-800

www.mercurynews.com##.modal-scrollable

www.mercurynews.com##.in.fade.connext-modal-backdrop

**Comment by yourduskquibbles** [comment]
I don't see the modal popup @zestysoft is getting either but I do see a modal popup for newsletter subscribe.

Most likely the following filters will kill the subscription nag modal as well as the newsletter modal and fix the scrollbar/overflow hijack.

`mercurynews.com##.Mg2-connext, .connext-modal-backdrop, .modal-scrollable`
`mercurynews.com##body.modal-open:style(overflow-x: hidden !important; overflow-y: scroll !important;)`

**Comment by zestysoft** [comment]
Those rules work.

**Comment by okiehsch** [comment]
OK, I will add **yourduskquibbles** filters to `uBO-annoyances`.
