### ISSUE TITLE
"uBlock filters" builtin filter prevents loading mail.yandex.ru

### ISSUE THREAD

**Issue by xDShot** [uBlockOrigin/uAssets#4525]
### URL(s) where the issue occurs

https://mail.yandex.ru/

### Describe the issue

if "uBlock filters" builtin filter enabled, the web page refuses to load showng this:

![image](https://user-images.githubusercontent.com/4261659/50635071-ca318c80-0f61-11e9-95a6-713474122b46.png)

Which means there was an error during load. When disable the filter and apply settings, it loads fine. Only this filter list affects.

Lite and Mobile site versions do work in any cases though.

### Screenshot(s)

See above

### Versions

- Browser/version: Chromium 71.0.3578.98
- uBlock Origin version: uBlock Origin v1.17.4

### Settings

![image](https://user-images.githubusercontent.com/4261659/50635338-d702b000-0f62-11e9-8bf0-42dd137c630d.png)

### Notes

Here is what browser console reports:
![image](https://user-images.githubusercontent.com/4261659/50635194-43c97a80-0f62-11e9-9fc8-6ee96cd0846c.png)

From my understanding web site expects font resources being loaded to work further, bu uBlock decided to block it, which is strange as I didn't find any occurences of that blocked source.

**Comment by okiehsch** [comment]
Does adding
`yandex.ru#@#+js(set-constant.js, Math.random, trueFunc)`
to your filter list fix the issue?

**Comment by xDShot** [comment]
Sorry, where should I add it?

**Comment by xDShot** [comment]
Nwm, added it in My Filters, this works!

**Comment by okiehsch** [comment]
I removed the offending filter form `uBO-filters`, if you force an update of that list in a few minutes you can remove the filter I mentioned from your filter list.

**Comment by xDShot** [comment]
Thank you
