### ISSUE TITLE
wsj.com recirculation/carousel links being rewritten after mouse click to add cxense.com tracking

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#4526]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.wsj.com/articles/wall-streets-big-landlords-are-so-hungry-for-houses-theyre-building-them-11546511401`

### Describe the issue

When initially hovering over a link in a wsj.com article recirculation bar the proper direct link is displayed at bottom of browser window. However after a click event on the link the the link gets updated to route through `cxense.com` tracking domain which is blocked by default in Peter Lowe's list.

I think the mouse click event that triggers the url rewrite can likely be defused (Maybe with a `wsj.com##+js(addEventListener-defuser.js, foo)` filter?) but I don't have enough experience writing these to debug and suggest the proper filter.

### Screenshot(s)

Screenshot 1 below shows the recirculation link when just hovering over the link. Note the link outlined in red is showing as going to wsj.com domain before the mouse click event triggers the url rewrite.

![frame01](https://user-images.githubusercontent.com/22258847/50638072-6475de00-0f2a-11e9-811f-71860901497f.png)

Screenshot 2 below shows the hovered link outlined in red after a mouse click event triggers the url rewrite to route through cxense domain which is in default block list blocked by [Peter Lowe's Ad and tracking server list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext&_=21479)

![frame02](https://user-images.githubusercontent.com/22258847/50638096-7b1c3500-0f2a-11e9-90eb-4075099e573f.png)

### Versions

- Browser/version: Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin 1.17.7b0 (Latest Dev Build)
- uBlock Origin Extra 2.79

### Settings

- Test profile with default settings and lists.

### Notes
I think there is an event listener that can be defused to prevent the link rewrite going through cxense tracking domain that is blocked by @pgl list.

**Comment by krystian3w** [comment]
`wsj.com##+js(addEventListener-defuser.js, mousedown)`

But I have same troubles:

> I don't have enough experience writing these to debug and suggest the proper filter.

**Comment by lassekongo83** [comment]
Try:
```
wsj.com##+js(abort-current-inline-script.js, NREUM)
wsj.com##+js(setTimeout-defuser.js, linkEl)
```

**Comment by krystian3w** [comment]
Works fine on mobile too.

**Comment by yourduskquibbles** [comment]
> 
> 
> Try:
> 
> ```
> wsj.com##+js(abort-current-inline-script.js, NREUM)
> wsj.com##+js(setTimeout-defuser.js, linkEl)
> ```

Tested on Firefox 64.0 & Chrome Version 72.0.3626.28 (Official Build) beta (64-bit) and these work for me as well for the top carousel. 

But when I scroll down the page after the article (or paywall subscribe notice) under 'What to Read Next...' section those links are still being redirected through cxense.com but I'm not sure if there is anything that can be done as I don't know if they ever started as a wsj.com url being rewritten through an event. 


### Hover URL 'What to Read Next,...' before click event - desktop resolution
![frame03](https://user-images.githubusercontent.com/22258847/50646794-01de0b80-0f45-11e9-8b75-449a182a8b06.png)

You can also test this for mobile that these are still infected by cxense if you force resolution of mobile device (408px x 1175px window size) and scroll down to bottom of an article and hover on one of the recirculation links.


### Hover URL 'What to Read Next,...' before click event - mobile resolution
![frame04](https://user-images.githubusercontent.com/22258847/50646896-47023d80-0f45-11e9-8e8e-a609bbe3365b.png)

**Comment by yourduskquibbles** [comment]
After further looking, I think those 'What to Read Next...' links are always routing through cxense.com based on the DOM name they use for that section `###cxsense-editor-pick-01`

![frame05](https://user-images.githubusercontent.com/22258847/50647867-b24d0f00-0f47-11e9-8b6a-f286393e8d63.png)

I think the filters suggested by @lassekongo83 work as good as we will get & should be added to one of the uBO Filter Lists.

**Comment by mapx-** [comment]
could be useful ?
`wsj.com##+js(std, utag)`

**Comment by yourduskquibbles** [comment]
> wsj.com##+js(std, utag)

That appears to just cause the entire `What to read next` section at the bottom of the article to not load for me.

Test link: `https://www.wsj.com/articles/gwen-stefani-unloads-colorful-beverly-hills-estate-for-21-65-million-11569964566?mod=rsswn`

**Comment by mapx-** [comment]
right, ..killing paywall but `read next` too
