### ISSUE TITLE
gomovies related

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4533]
### URL(s) where the issue occurs

`http://gomovies-123.com/the-old-man/`
`http://gomovies123.today/black-mirror-bandersnatch/`
`http://gomovieshd.cc/episode/for-the-people-season-1-episode-1/`
`https://gomovies.ec`
`https://gomoviesm.com/poor-boy-2018-Watch-Movie-online-Gomovies/`
`https://www4.gomovieshub.io`

### Describe the issue

ads

### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

-uBO's default settings

### Notes

antiadblock for this
only
`https://gostream.nu/film/breathe-2017-1080p.53992/watching.html`

**Comment by mapx-** [comment]
I removed `putload.tv` filter, test again

**Comment by ghajini** [comment]
`https://gomoviesc.com`
ads, 
frequently original tab is opened in new tab(bandwidth usage again)

**Comment by ghajini** [comment]
`https://gomovies.tube/movie/triple-frontier/zylyWhaE/ilYenp49-watch-online-free.html`
Popup ads

**Comment by ghajini** [comment]
`https://gomovies.vet/movie/filter/movies`
popup ads

**Comment by ghajini** [comment]
1. player hidden
`https://gomovies.shop/bad-boys-for-life-2020/`

2. play doesn't work
`https://ww.gomovies.click/watch/movie/?1149899-the-croods-a-new-age-CJHM1`
