### ISSUE TITLE
kat.tv

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4534]
### URL(s) where the issue occurs

`http://kat.tv/watch/lx2kozKG-the-old-man-the-gun.html`

### Describe the issue

popup ads
### Versions

- Browser/version: chrome stable
- uBlock Origin version: 1.17.4

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
`kat.tv`
Not able to pass cloudfare ddos protection page 

Issue is gone after disabling ublock origin

**Comment by uBlock-user** [comment]
`##+js(set, String.fromCharCode, trueFunc)` is causing the breakage.

**Comment by ghajini** [comment]
popup ads
propeller crap

`https://kat.fun/movies/`

**Comment by ghajini** [comment]
still getting popup ads & propeller crap

`||kat.fun/x9.php$script,1p`
`kat.fun##+js(aopr, String.fromCharCode)`

**Comment by okiehsch** [comment]
Can't reproduce with Chromium and Firefox.

**Comment by ghajini** [comment]
`kat.tv`

stuck at cloudfare page ddos protection
1.
except this site from these filters
||*$document,csp=script-src *,domain=kat.*
||*$script,1p,domain=kat.*
 &

2.
need update 
kat.tv#@#+js(acis, atob, decodeURIComponent)
kat.tv##+js(acis, String.fromCharCode, break)
