### ISSUE TITLE
megawarez.org [Ads]

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uAssets#4537]
### URL(s) where the issue occurs

`https://www.megawarez.org`

### Describe the issue

There is advertising from an external "chat" site on the top right where it shows an image of a woman and her link to the chat site.

### Versions

- Browser/version: Firefox 64.0
- uBlock Origin version: 1.17.4

**Comment by mapx-** [comment]
add
`megawarez.org##div.w2.widget`

such simple (fixable with classic syntax) ads have to be reported at easylist repository

@ryanbr
