### ISSUE TITLE
europages.it registration problem

### ISSUE THREAD

**Issue by ale5000-git** [uBlockOrigin/uAssets#454]
### URL(s) where the issue occurs

`http://www.europages.it/`

### Describe the issue

When you click on "Iscrizione gratuita",
it open this: `https://fr.sitestat.com/euredit/europages-com/s?it.clic.AN.home.header&ns_type=clickout&ns_url=http://promote-your-business.europages.com/IT/`,
that redirect to this `http://promote-your-business.europages.com/IT/`.

But uBlock Origin is blocking the first page so the redirect cannot happen.

### Screenshot(s)

![screen](https://user-images.githubusercontent.com/15793015/27133286-ed7b63a6-5111-11e7-92a5-e35d9658001e.png)

### Versions

- Browser/version: Google Chrome 59.0.3071.86
- uBlock Origin version: 1.12.4

### Settings

- None

### Notes

`Peter Lowe’s Ad and tracking server list` block the page.

**Comment by gorhill** [comment]
> But uBlock Origin is blocking the first page so the redirect cannot happen.

By design. uBO blocks and inform the user so that he can make an informed decision regarding the 3rd-party tracking. One can choose to proceed ahead by unblocking temporarily or permanently, or even better expand the tracker URL and click directly on the real destination link.

**Comment by ale5000-git** [comment]
@gorhill: Can't it "un-track" the link and redirect to `http://promote-your-business.europages.com/IT/` without pass from the tracking page?

**Comment by gorhill** [comment]
uBO is not a URL rewriter, for this you will need another extension.
