### ISSUE TITLE
macbed.com - anti-adblock

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#4540]
### URL(s) where the issue occurs

**LINK** **–** `https://www.macbed.com/`

### Describe the issue

Anti-Adblock notification.

### Screenshot(s)

–

### Versions

- Browser/version: **Firefox 64.0 (64-bit)**
- uBlock Origin version: **1.17.4**

### Settings

Default

### Notes

–

**Comment by mapx-** [comment]
I cannot reproduce your issue

**Comment by pepablock** [comment]
it's all good now, sorry. closing

**Comment by ghajini** [comment]
its blockadblock
link= `https://www.macbed.com/download/56748.html`
![screenshot 83](https://user-images.githubusercontent.com/20338483/50704357-17eee780-107d-11e9-80a6-01ab3a53d77b.png)

**Comment by mapx-** [comment]
thanks, fixed
