### ISSUE TITLE
@@ -> @@||

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#4541]
`@@uploadproper.com^$generichide`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L15545

**Comment by ghajini** [comment]
`https://uploadproper.net/o4ntbvkaasu4`
antiadblock

**Comment by ghajini** [comment]
`https://uploadproper.net/7xne7g7no812`
pls remove fake `download now and use our download manager` clicking on it leads to ads
