### ISSUE TITLE
mustbuy.gr

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#4545]
`https://mustbuy.gr/`

page unloads immediately after finished loading 

- Browser/version: Cent browser Version 3.7.2.33 (Official Build) (64-bit) (Chromium 70.0.3538.110)
- uBlock Origin version: 1.17.4

**Comment by mapx-** [comment]
What do you mean ? screenshot ?

**Comment by patrickdrd** [comment]
do you want a white screenshot?
white page, totally blank

**Comment by patrickdrd** [comment]
if I disable ublock, it works, does it work for you?

**Comment by mapx-** [comment]
I cannot reproduce the blank page. 
Test the page using the default setup, disable any other extension.

**Comment by patrickdrd** [comment]
no, it's  not an extension issue, but ublock's, because if I disable it for this page, it works, wait to check the filters

**Comment by patrickdrd** [comment]
I added this and it worked:

`mustbuy.gr#@#.cookies
`

(it was blocked by prebake)

**Comment by mapx-** [comment]
Did you try `Fanboy's Cookie List` ?
However, report - if you want - your issue with `prebake list`
