### ISSUE TITLE
vipbox.live

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#4546]
### Describe the issue

[Anti adblock on all streams on the website]

`https://www.vipbox.live/rugby-live`

### Screenshot(s)

[`https://i.imgur.com/3NO4jVn.png`]

### Versions

- Browser/version: [Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)]
- uBlock Origin version: [1.17.4]

### Settings

- [Removed default cookie remover and added custom Fanboy's Cookie List]

### Notes

[Only extension that is active is uBo, nothing else.]

**Comment by mapx-** [comment]
for the moment add
```
@@about:blank$popup,domain=vipbox.live
vipbox.live#@#.position-absolute
```

then use the zapper to remove the overlay and then just play the stream

**Comment by germaloney11** [comment]
It is anti-adblocked again

**Comment by germaloney11** [comment]
It is anti-adblocked again, same thing

**Comment by germaloney11** [comment]
Anti-adblocked again

**Comment by germaloney11** [comment]
Streams keep getting anti-adblocked. 

Current livestream: `https://www.vipbox.live/ulster-vs-kings-1-live`

**Comment by germaloney11** [comment]
Anti-adblocked again. Is there any easy block that you can recommend using until a commit/update is added?

**Comment by mapx-** [comment]
now the specific filter is
`vipbox.live##.position-absolute:style(opacity: 0.2 !important;)`

what can you so:
- disable the filter:
`vipbox.live#@#.position-absolute:style(opacity: 0.2 !important;)`
- add this 1:
`vipbox.live##.position-absolute:style(opacity: 0.1 !important;)`

now I'll add the the 0.1 filter, next time you just switch the filters

**Comment by germaloney11** [comment]
Ah I see thanks

**Comment by germaloney11** [comment]
Keep getting porn popups at random when playing streams.


They link to: `https://click-and-date-now.com/click.php?lp=1`

`sexbadoo.png`




Can reproduced but unsure where in console to look for what you might need.

```
zinrora.pw/rIpdBjA3XeR2ngIr/9431:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.googletagmanager.com/gtag/js?id=UA-39795912-10:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
jsc.mgid.com/v/i/vipbox.st.266667.js?t=11923113:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
jsc.mgid.com/v/i/vipbox.st.267220.js?t=11923113:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
gssjs.js:1 
clksite.com/static/advertisement.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pushlat.com/ntfc.php?p=2116292:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
id.html:5 The key "target-densitydpi" is not supported.
```

**Comment by mapx-** [comment]
provide a working stream

**Comment by germaloney11** [comment]
'https://www.vipbox.live/la-rochelle-vs-bristol-1-live'

**Comment by mapx-** [comment]
test these filters
```
kuntv.pw##+js(window.open-defuser.js)
kuntv.pw##+js(abort-on-property-write.js, decodeURIComponent)
```

**Comment by germaloney11** [comment]
That seems to have blocked it. Thanks!

**Comment by germaloney11** [comment]
Whole website anti-adblocked and each stream
`https://www.vipbox.live/rugby-live`

**Comment by okiehsch** [comment]
Works fine on my end, try updating the `uBO-filters` list.

**Comment by ZaphodBeebblebrox** [comment]
okiehsch, fake buttons on `https://www.vipbox.live/connacht-vs-montpellier-1-live` for example.
`vipbox.live##button[data-open="_blank"]` to remove, perhaps?

**Comment by germaloney11** [comment]
Can you check this issue out again please? All streams covered in anti adblock grey banner "kindly remove/disable adblock, and reload the page." and clicking links also redirecting to other sites

**Comment by okiehsch** [comment]
> All streams covered

Can you give an example link, the first one I tried works without issue on my end.
`https://www.vipbox.lc/nfl-network-1-live`

**Comment by germaloney11** [comment]
![Screenshot_20211217-175516_Kiwi Browser](https://user-images.githubusercontent.com/17252998/146587548-6d947e6f-66ee-43f7-b080-49f1533a959e.jpg)
That stream does not work for me. Do you have custom filters enabled?

**Comment by okiehsch** [comment]
No.

**Comment by mapx-** [comment]
it should work now - @okiehsch it's android specific

**Comment by germaloney11** [comment]
That fixed it cheers @mapx- @okiehsch
