### ISSUE TITLE
Popunder ads on bouncebreak.com

### ISSUE THREAD

**Issue by sfan5** [uBlockOrigin/uAssets#455]
### URL(s) where the issue occurs

`bouncebreak.com` (<b>nsfw</b>)

### Describe the issue

Clicking links on the page randomly open ads in the current tab and the actual destination in a new tab.

### Versions

- Browser/version: Chromium	59.0.3071.86
- uBlock Origin version: uBlock Origin v1.12.4

### Notes

this filter seems to stop it from doing that:
`bouncebreak.com##script:inject(popads.net.js)`

**Comment by gorhill** [comment]
How about something more drastic:

    ||bouncebreak.com^$script,third-party

Does that cause breakage on the site?

**Comment by gorhill** [comment]
Never mind, I did not test properly (need to clear cookie before each test), blocking all 3rd-party scripts does not work.

Your suggested filter works fine.

**Comment by SMed79** [comment]
> blocking all 3rd-party scripts does not work.

Out of curiosity... You mean first-party scripts?
