### ISSUE TITLE
mixcloud.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#4554]
### Describe the issue

popup if i try to close this card

### Screenshot(s)

![2019-01-06-window](https://user-images.githubusercontent.com/5884000/50735893-e463a880-11b5-11e9-93b8-89aa38ee090a.png)

### Details

- Browser/version: latest, stable
- uBlock Origin version: latest, stable

https://gist.github.com/KonoromiHimaries/9bc55fcafd3fab612f1f8dfa59f8f572

**Comment by adranger** [comment]
@mapx- I'm not sure if that's something I'd personally add to the public annoyances list, but it does ask me for confirmation if I try to close the tab while playing something.

**Comment by mapx-** [comment]
@KonoromiHimaries 
add
`mixcloud.com##+js(addEventListener-defuser.js, beforeunload)`

The filter wont be added to uBo lists
