### ISSUE TITLE
kissmanga.com anti-adblock

### ISSUE THREAD

**Issue by comfyneet** [uBlockOrigin/uAssets#4555]
### URL(s) where the issue occurs

`https://kissmanga.com/Manga/Kengan-Ashua/Vol-001-Ch-001--Asura?id=226510`

### Describe the issue

After the page is fully loaded, wait for about 30 seconds, if it detects that an adblock is in use, it will hide all comic pages by changing the attribute `display: block` to `display: none` in the parent div `divImage`.

### Screenshot(s)

![before](https://user-images.githubusercontent.com/7628095/50737981-747b0f80-1201-11e9-8c68-6b41926af4ee.png)
![after](https://user-images.githubusercontent.com/7628095/50737982-76dd6980-1201-11e9-9d4e-e6c2d619f5a0.png)

### Versions

- Browser/version: Chrome 69.0.3497.100 (32-bit)
- uBlock Origin version: 1.17.4

### Settings

- Default settings with `Adblock Warning Removal List`.

### Notes

- The website blocks all Vietnamese IP ranges, one might need to use a VPN to access the page.

**Comment by okiehsch** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/3675
Adding
````
||linkedin.com^$script,redirect=noopjs,domain=kissmanga.com
||googletagmanager.com/gtag/js$script,redirect=noopjs,domain=kissmanga.com
````
still works on my end.

**Comment by uBlock-user** [comment]
`kissmanga.com##+js(setTimeout-defuser.js, /YANABWEKA|HATEDBSDIDSY/)`

Still works for me.

**Comment by comfyneet** [comment]
> 
> 
> `kissmanga.com##+js(setTimeout-defuser.js, /YANABWEKA|HATEDBSDIDSY/)`
> 
> Still works for me.

I deleted kissmanga cookies and reset IP but I'm still banned, with message:

> The site is closed.

**Comment by Procyon-b** [comment]
@comfyneet : I have tried it today (with the filters) and got the "maintenance" message. I have tried with proxies in other countries and it works.
So it seems that kissmanga.com if banning based on ip address. You'll have to change your address, clear kissmanga's cookies, and only then, open a tab to that site.

**Comment by uBlock-user** [comment]
> I deleted kissmanga cookies and reset IP but I'm still banned, with message:

Clear your cache then. I can't reproduce.

**Comment by comfyneet** [comment]
@uBlock-user It seems that they blocked users by IP addresses, I used the same cache, changed my IP, refreshed the page and it loaded normally.

**Comment by uBlock-user** [comment]
@comfyneet https://github.com/uBlockOrigin/uAssets/issues/3675#issuecomment-429224941
