### ISSUE TITLE
e-ptolemeos.gr

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#4567]
`https://e-ptolemeos.gr/`

amazing bs site full of ads

p.s. remove background image too

Browser/version: Cent browser Version 3.7.2.33 (Official Build) (64-bit) (Chromium 70.0.3538.110)
uBlock Origin version: 1.17.4

**Comment by mapx-** [comment]
You should report such classical ads to greek repository (to help other greek users):
https://github.com/kargig/greek-adblockplus-filter/issues

However, test these filters (which wont be added to uBo filters)
```
||e-ptolemeos.gr/*banner$image
||e-ptolemeos.gr/*.gif$image
e-ptolemeos.gr##.background-cover
e-ptolemeos.gr##.e3lan-top
e-ptolemeos.gr##.afterheader
e-ptolemeos.gr##.animated1.fade-in.header-content
e-ptolemeos.gr###custom_html-30
e-ptolemeos.gr##.custom-html-widget
e-ptolemeos.gr##.home-ads
```
