### ISSUE TITLE
gamovideo.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4572]
### URL(s) where the issue occurs

`http://gamovideo.com/03ipvwi77tr9`

### Describe the issue

ads/popups
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
try these
```
||gamovideo.com^$subdocument,first-party
gamovideo.com##[id^="pu-"]
```

**Comment by lain566** [comment]
This filter works for me.
`gamovideo.com##+js(set-constant.js, canRunAds, false)`

**Comment by ghajini** [comment]
`gamovideo.com/q41h2bcf1btn`
Popup ads

**Comment by mapx-** [comment]
- no popup on my end
- clearing cookies / cache I get a weird behaviour => first time I'm redirected to the previous page (same without uBO enabled)
- android => I cannot get a running video

**Comment by ghajini** [comment]
I get ads on opera browser

**Comment by mapx-** [comment]
all fine in opera too
