### ISSUE TITLE
ddl.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4575]
### URL(s) where the issue occurs

`https://ddl.to/p8jg5tifc3su`

### Describe the issue

ads/popups at final download page by clicking `download`(bottom on)
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
add
`||ddl.to/images/*.gif$image`

then in the first page click get link, then (second page): click download => works for me

**Comment by ghajini** [comment]
i added your filter still see ads
![screenshot 86](https://user-images.githubusercontent.com/20338483/50840091-c352b180-1387-11e9-9e2b-fbcb08df541c.png)
![screenshot 87](https://user-images.githubusercontent.com/20338483/50840093-c352b180-1387-11e9-872a-0386ed63b5b0.png)

**Comment by ghajini** [comment]
fake download button
ddl.to##[href="https://ddl.to/download.html"]

**Comment by mapx-** [comment]
screenshot ?

**Comment by ghajini** [comment]
1.
popups
`https://ddl.to/ulhrt0zz68dv`

2. fake download button
`https://user-images.githubusercontent.com/20338483/60396516-40552b80-9b60-11e9-879f-cce645fcf2b8.png`

`ddl.to##[href="https://ddl.to/download.html"]`

**Comment by ghajini** [comment]
`https://ddl.to/praviuzc9gqg`
Download not working

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9e3253dc9a40dfb8716ad8b800a6a39a4b3c1f8e

**Comment by ghajini** [comment]
Domain redirects to new url ddownload.com...

`https://ddownload.com/praviuzc9gqg`

`CDN13.com` need to allowed for download to work in firefox
