### ISSUE TITLE
spotify.com Music stops after some tracks

### ISSUE THREAD

**Issue by mrsamse** [uBlockOrigin/uAssets#4576]
### URL(s) where the issue occurs
`https://open.spotify.com/`

### Describe the issue
The music stops after some tracks. It was fixed some time ago, but today it started again to happen.

### Screenshot(s)
Screenshot from the Google Chrome console tab:
![console](https://user-images.githubusercontent.com/20925205/50833550-caf76380-1351-11e9-8a3e-fac78dabc2a1.png)

Screenshot from the Google Chrome network tab:
![network](https://user-images.githubusercontent.com/20925205/50833563-db0f4300-1351-11e9-8b05-5ed16956fe32.png)

### Versions
- Browser/version: Chrome 71.0.3578.98
- uBlock Origin version: 1.17.4

### Settings
Default settings

**Comment by mapx-** [comment]
open issue (continue there)
https://github.com/uBlockOrigin/uAssets/issues/3561
