### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#4579]
Describe the issue
[Reddit premium ad unblocked]

`https://www.reddit.com/`

Screenshot(s)
`https://i.imgur.com/pbEoR0j.png`

Versions
Browser/version: [Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)]
uBlock Origin version: [1.17.4]
Settings
[Removed default cookie remover and added custom Fanboy's Cookie List]
Notes
[Only extension that is active is uBo, nothing else.]

**Comment by mapx-** [comment]
cannot reproduce, however to be reported at easylist repository @ryanbr

**Comment by ryanbr** [comment]
Saw it, but wont be added to the Easylist stuffs. Only my personal list (Enhanced Trackers)

**Comment by gwarser** [comment]
##.premium-banner

**Comment by krystian3w** [comment]
ps.reddit.com / old.reddit.com
