### ISSUE TITLE
latimes.com - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#458]
Multiple ad/tracker requests and ad frames are created on http://www.latimes.com due to numerous whitelist filters in EasyList (added to tackle anti adb). Blank ad spaces are also visible all over the page.

**SS:**
http://i.imgur.com/lrMbOQ4.jpg (Full page SS showing blank ads)
https://i.imgur.com/Tj5XgNL.png (Ad/Tracker Requests)

**Error URL:**
http://www.latimes.com/nation/la-na-carter-suicide-20170614-story.html

Recommend blocking the ad and tracker requests and hiding the ad spaces.

**Note:** Using uBO 1.12.4 on Chrome 59 with default filters and settings.

**Comment by mapx-** [comment]
```
latimes.com##[id^=trb_ad]
latimes.com##.trb_sntAd
latimes.com##.trb_masthead_adBanner
```

**Comment by okiehsch** [comment]
How about 
`||latimes.com^$generichide,important`?

**Comment by gotitbro** [comment]
@okiehsch That does work, please also look into the whitelisting filters. Thank You.

**Comment by okiehsch** [comment]
About the whitelisting, EasyList seems to think `latimes.com` uses Instart Logic, which it does not and never did, as far as I can tell. They whitelist all 3rd party image formats known to man, so I would have to override every one of them and check if nothing breaks. I will override unnecessary 3rd party script exceptions.

**Comment by gotitbro** [comment]
@okiehsch @gorhill Similar issue on http://www.msn.com (**_Multiple ad/tracker requests and ad frames & Blank ad spaces all over the page_**). These are also caused due to whitelist filters in EasyList added to tackle g00 from Instart Logic but this site indeed uses g00 technology.

**SS:**
https://imgur.com/a/fberu (g00 requests and cookies)
https://i.imgur.com/6wfsQnv.jpg (Full page SS showing blank ads **_and ads_**)
https://i.imgur.com/AxRDxaM.png (Ad/Tracker Requests)

**Error URL:**
http://www.msn.com/en-us/news/us/minimum-wage-set-to-drop-in-missouri/ar-BBDP27V

g00 ads should be blocked in uBO Extra. Also recommend blocking the ad and tracker requests and hiding the ad spaces.

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by okiehsch** [comment]
@gotitbro 
````
||msn.com^$generichide,important
||o.aolcdn.com/ads$script,important,domain=msn.com
````
should work, is there any site breakage if you add `msn.com` to the contentscript of uBO-Extra and are logged in to your microsoft account?
![ubo-extra](https://user-images.githubusercontent.com/16838044/27927583-90226588-628c-11e7-8a7e-75a3b521e7c1.PNG)

**Comment by gotitbro** [comment]
@okiehsch The comments section does not load if `msn.com` is added to the **_contentscript_** does not matter if I am logged in.

Also, this filter: `msn.com##.nextcontentitem` in **EasyList** causes the footer to not load hiding some essential information (this is when the filters suggested above are also added).

**Comment by gorhill** [comment]
Comments show fine if `msn.com` is added to ILv3 instead.

**Comment by gotitbro** [comment]
Sorry for deleting my previous comment. Wrongly reported an issue with a EasyList filter.

@gorhill If you mean this https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js#L469, I just tested and the comments load fine if `msn.com` is added here but **_Taboola_** content still loads for me.

**Comment by SMed79** [comment]
What is better?

`||msn.com^$generichide,important`
or
`@@||msn.com^$generichide,badfilter`

Sorry for the off topic question... and thank you.

**Comment by okiehsch** [comment]
For the Taboola links
`msn.com###promotedlinksplaceholder`
should work. 
The amount of whitelisting is really something and I still get the IL-crap if I don't use uBO-Extra, so
what's the point?

**Comment by gotitbro** [comment]
> what's the point

I don't understand what you are meaning to say.

**Comment by okiehsch** [comment]
The whitelisting of these `Instart Logic` sites does not result in circumventing the IL-g00 redirect, atleast on my end. This was not adressed at you, I was just thinking out loud.

**Comment by gotitbro** [comment]
You are right that was the reason I had to install **uBO Extra** in the first place (g00 ads were loading even with these EasyList fixes). So, why don't we just disable the whitelist filters on our end?

Listing some of the problematic whitelist filters:
```
@@.gif^$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
@@.jpg^$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
@@|http://$third-party,image,domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|spin.com|sporcle.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|timeanddate.com|tmn.today|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com
@@|https://$third-party,image,domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|spin.com|sporcle.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|timeanddate.com|tmn.today|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com
@@||tpc.googlesyndication.com/favicon.ico$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
@@||www.yahoo.com/px.gif$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
@@||s0.2mdn.net/1635909/1x1image.jpg$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
@@||www.google-analytics.com/__utm.gif$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
@@||www.google.com/pagead/drt/ui$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ign.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com
@@||sync.adap.tv/sync$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ign.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com
@@||ti.tradetracker.net/$domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|slickdeals.net|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
```

Also, the g00 redirection still takes place even after adding `msn.com` to **ILv3**: https://i.imgur.com/AEtcemI.png

**Comment by gorhill** [comment]
> amount of whitelisting is really something and I still get the IL-crap

I don't see the point either, and worse it also mean that Firefox users are suffering these exception filters even if they do not suffer the IL crap.

**Comment by gotitbro** [comment]
The amount of whitelisting is crazy. A simple search for `baltimoresun.com|boston.com|calgaryherald.com` on https://easylist-downloads.adblockplus.org/easylist.txt will show you that there are more than **450 whitelisting filters** for Instart Logic!

What should be done about this? This seems a bit extreme to me.

**Comment by okiehsch** [comment]
By my count, right now, there are 547 IL-specific exception filters.
This includes `generichide-filters`.

**Comment by okiehsch** [comment]
@SMed79 
I prefer `||example.com^$generichide,important`.
1. Using the logger I can see that for this specific site there is a `generichide` filter, which was overruled by an `important` filter. If I use `badfilter`, the logger indicates nothing, just that there is no `generichide` filter, which is not unusual.
2. @@||msn.com^$generichide is not really a "badfilter"

**Comment by gotitbro** [comment]
@okiehsch What can or shall be done for these whitelist filters? They possibly cause the page to keep waiting for some tracking domains on http://articles.latimes.com.

**Error URL:** 
http://articles.latimes.com/2014/apr/26/world/la-fg-wn-egyptian-presidential-candidate-said-to-say-hed-put-his-rival-on-trial-20140426

**Comment by gorhill** [comment]
I plan to experiment with stuff to deal with all this, hopefully the outcome will be good.

**Comment by gotitbro** [comment]
@gorhill That's great to hear. Will `msn.com` be fixed currently or that too will be tested with the experimental fixes?

**Comment by okiehsch** [comment]
@gotitbro 
````
http://articles.latimes.com/2014/apr/26/world/la-fg-wn-egyptian-presidential-candidate-said-to-say-hed-put-his-rival-on-trial-20140426
````
should be fixed by adding
````
||pagead2.googlesyndication.com^$script,important,domain=latimes.com
||openx.net^$script,important,domain=latimes.com
````

**Comment by gotitbro** [comment]
@okiehsch @gorhill Another similar issue on `http://nationalpost.com` (**_Multiple ad/tracker requests and ad frames & Blank ad spaces all over the page_**). Again caused due to whitelist filters in **EasyList** added to tackle g00 from Instart Logic, this site also uses g00 technology.

**SS:**
http://imgur.com/a/8Jtz8 (g00 requests, storage and cookies)
http://i.imgur.com/eyBwUpK.jpg (Full page SS showing blank ads and ads)
https://i.imgur.com/94HB8cY.png (Ad/Tracker Requests)

**Error URL:**
`http://nationalpost.com/news/canada/the-strange-tale-of-the-man-who-was-shot-point-blank-for-mispronouncing-newfoundland-in-the-old-west/`

Same issue as above on MSN.com while using **uBO Extra**. These g00 ads seem to be on every site now :/

**PS:** Another interesting thing I noticed is that they are using an **_instart/nginx_** server. Can be seen here in the headers: https://nationalpost.com/

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by gotitbro** [comment]
@okiehsch @gorhill Another site using g00 from Instart Logic: `http://www.metrolyrics.com`, casuing similar issues (**_Multiple ad/tracker requests and ad frames & multiple redirections on the page_**).

**SS:**  
http://imgur.com/a/X9EPI (g00 storage and cookies)
https://i.imgur.com/SiWjigU.png (g00 Requests )

**Error URL:** `http://www.metrolyrics.com/`


_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by gorhill** [comment]
Did you try to add `metrolyrics.com` to ILv1 or ILv3 to see which work best? I tried both, both ILv1 gives best results, I just wonder if this breaks something -- I don't know enough that site.

**Comment by okiehsch** [comment]
@gorhill 
`metrolyrics.com` to ILv1, I checked the videos, comments and search function, all work fine.

`metacritic.com` reported at `https://www.reddit.com/r/uBlockOrigin/comments/6npiot`
has to go to ILv3, because ILv1 breaks even the basic layout of parts of `metacritic.com`.

**Comment by gotitbro** [comment]
@okiehsch @gorhill g00 content is still loading for me on metacritic.com with **uBO Extra 2.27**. The issues are similar to the previous websites  **_(Multiple ad/tracker requests and ad frames & Blank ad spaces all over the page)_**.  Again caused due to whitelist filters in EasyList.

**SS:**
http://imgur.com/a/vPrEQ (g00 requests, storage and cookies)
https://i.imgur.com/qmDfIKg.jpg (Full page SS showing blank ads and ads)
https://i.imgur.com/BpvYOXA.png (Ad/Tracker Requests)

**Error URL:** `http://www.metacritic.com/tv/game-of-thrones/season-7`


_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by gorhill** [comment]
The IL code is not prevented from executing on `metacritic.com`, it is just fooled into thinking the dev console is opened and thus it prevents itself from disguising 3rd-party requests as 1st-party ones. This means that yes, you will still find IL cookies in there.

**Comment by ghajini** [comment]
so cookies of g00 can't be prevented???

also this site also uses IL `http://www.wrestlezone.com/news`

**Comment by gotitbro** [comment]
@gorhill So, g00 redirection can't be stopped on metacritic?

@okiehsch Please see if generichide can be blocked on `metacritic.com`.

**Comment by okiehsch** [comment]
@gotitbro the site looks "normal" to me, can you give me an example that needs to be fixed by
adding `||metacritic.com^$generichide,important`?

**Comment by gorhill** [comment]
> So, g00 redirection can't be stopped on metacritic?

I don't see 3rd-party requests disguised as 1st-party requests with uBO-Extra 2.27.

**Comment by gorhill** [comment]
`metacritic.com##.ad_unit` would probably a good cosmetic filter to add for `metacritic.com`.

**Comment by gotitbro** [comment]
@okiehsch I posted it in my [post above](https://github.com/uBlockOrigin/uAssets/issues/458#issuecomment-315675900). Here you go: https://i.imgur.com/qmDfIKg.jpg

@gorhill Not sure about the disguising but any page I visit redirects me with the **_g00 refferer_** (https://i.imgur.com/sgVqpoB.png) and loads even more domain requests than before, a lot of google ad iframes are also created (https://i.imgur.com/YuC5AGN.png), these iframes might be due to the **EasyList** whitelist filters not sure though.

**Comment by okiehsch** [comment]
@gotitbro 
![meta](https://user-images.githubusercontent.com/16838044/28282666-849ef6d4-6b2b-11e7-94be-ec36e5870769.JPG)
`http://www.metacritic.com/tv/game-of-thrones/season-7` on my end.

**Comment by gotitbro** [comment]
@okiehsch Do you see any hidden elements in the logger? I don't.

**Comment by okiehsch** [comment]
I do not see any applied cosmetic filters.
If I disable generichide by adding `||metacritic.com^$generichide,important`
the only applied cosmetic filter is the `##.ad_unit` filter gorhill mentioned.
Here is what `##.ad_unit` blocks on my end at `http://www.metacritic.com/tv/game-of-thrones/season-7`
![u](https://user-images.githubusercontent.com/16838044/28290903-96c20604-6b48-11e7-9240-440654f4fc34.JPG)

**Comment by ghajini** [comment]
Anyone hearing here.....I see entries of g00 in logger in case of  
`http://www.wrestlezone.com/news`

**Comment by gorhill** [comment]
I rather go with `##.ad_unit` than `||metacritic.com^$generichide,important`. Reason: specific filters are always better than generic one where possible and practical, and on mobile all generic are disabled by default.

**Comment by pepablock** [comment]
I too see blank ads on that page
<img width="1680" alt="screen shot 2017-07-18 at 1 52 05 pm" src="https://user-images.githubusercontent.com/29940017/28315875-a58f21da-6bc0-11e7-8e8b-f702b0d9612d.png">

**Comment by gotitbro** [comment]
@gorhill @okiehsch g00 ads are being loaded on http://www.craveonline.com.

**Error URL:** 
`http://www.craveonline.com/mandatory/1038613-10-missing-people-who-were-eventually-found-alive?fullpage=1#/slide/1`

**Comment by ghajini** [comment]
@gorhill
Are there any side effects of using abp+ubo extra combination.....
I see this effective for users of adblock plus

**Comment by gotitbro** [comment]
@ghajini Not sure about side effects but there definitely will be downsides as uBO Extra is made to be used with uBO. Also, why use ABP? I don't see any benefit there.

**Comment by jjohns71** [comment]
@gorhill @okiehsch @jspenguin2017 https://www.chowhound.com is now injecting g00 / IL crap into their page. Their script is also clearing the Chrome Console.

[example link
](https://www.chowhound.com/food-news/186249/what-is-the-difference-between-crostini-and-bruschetta)

**Comment by jspenguin2017** [comment]
I think only @gorhill has write access to uBO-Extra...

**Comment by jspenguin2017** [comment]
Just a quick thought, is it possible to use `MutationObserver` to prevent one inline script from executiong?

**Comment by jspenguin2017** [comment]
Eh... that actually works... Removing the script prevents it from executing...

**Comment by jspenguin2017** [comment]
After some further testing, it seems `MutationObserver` isn't that reliable... Actually, it works like a charm with DevTools open but sometimes misbehave when DevTools is closed. 

Could be related to cache.
