### ISSUE TITLE
vup.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4582]
### URL(s) where the issue occurs

`https://vup.to/ls9tfll4auqq`

### Describe the issue

ads/popups
window opens/closes automatically....
### Versions

- Browser/version: operA BROWSER
- uBlock Origin version: 1.17.7

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
`vup.to/9wnnu9jubpo7`

Popup ads

Filter
common tracker 

`||augheguw.net^$important`

**Comment by ghajini** [comment]
`vup.to/wkn3qtjo7j26`

filter=
`cadsipz.com^`

**Comment by ghajini** [comment]
Popup ads in firefox android,some redirect ads are sometimes stopped, otherwise they are revolving

`https://user-images.githubusercontent.com/20338483/70936479-5e5c0d00-2068-11ea-8ef2-13561a723ec3.jpg`

**Comment by ghajini** [comment]
`https://vup.to/jq0305bke8k5`
Filter=
`||dadsecz.com^`

**Comment by ghajini** [comment]
Video player broken due to cname blockade `cdn13.com` from Easylist

### Link=
`https://vup.to/v/oi3kvmz0rmyz`

### Platform =
Firefox, ublock origin 1.30.6

**Comment by ghajini** [comment]
`https://vup.to/v/usrpebmaased`

update to `vup.to##+js(acis, String.fromCharCode, break)`

**Comment by mapx-** [comment]
I get no `zfgloaded` or `break` on my side, I'll remove `vup.to##+js(acis, Math, zfgloaded)`

**Comment by ghajini** [comment]
okay

**Comment by ghajini** [comment]
> I get no `zfgloaded` or `break` on my side, I'll remove `vup.to##+js(acis, Math, zfgloaded)`

![IMG_20210130_013909](https://user-images.githubusercontent.com/20338483/106322615-19ab2980-629c-11eb-91f3-c4e0e56cad40.jpg)

**Comment by advertblocker** [comment]
is the site still active?
