### ISSUE TITLE
Plus premiers anti-adblock

### ISSUE THREAD

**Issue by SpaceHoliday** [uBlockOrigin/uAssets#4588]
[(https://www.pluspremieres.nz/)]

Describe the issue

[Anti-Adblock blocks download links from being displayed and only shows links for Apple Music and iTunes.]

Screenshot(s)

![screen shot 2019-01-09 at 20 45 30](https://user-images.githubusercontent.com/39375169/50927413-9f5aa300-144f-11e9-86ef-e94d3612cfc9.png)

Versions

Browser/version: [Firefox Quantum 64.0]
uBlock Origin version: [1.17.14]

Settings

[Default]

Notes

[Every time this website changes its top level domain, this issue returns.]

**Comment by okiehsch** [comment]
Already fixed. https://github.com/uBlockOrigin/uAssets/commit/36e9608f93521cc3a2bbd6563f091c90cc6f52ce

Update your `uBO-filters` list.

**Comment by lain566** [comment]
Anti adblock again.
`https://www.pluspremieres.nz/2019/02/juice-wrld-death-race-for-love.html`

**Comment by SpaceHoliday** [comment]
Issue has re-occurred.
