### ISSUE TITLE
gamewatcher.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4590]
### URL(s) where the issue occurs

`https://www.gamewatcher.com/editorials/the-best-strategy-games-on-pc/12531`

### Describe the issue

Overlay annoyance. Rules by third-party lists will break the site: https://github.com/ryanbr/fanboy-adblock/issues/587

### Versions

- Browser/version: Firefox 64
- uBlock Origin version: 1.17.4

### Settings

+Annoyances

**Comment by mapx-** [comment]
should be fixed by the same fanboy's annoyances list @ryanbr

add
`gamewatcher.com##body:style(overflow: auto!important;)`

**Comment by adranger** [comment]
Did you read my description? It has a link to his repository showing that he had to remove his rule.
