### ISSUE TITLE
kakprosto.ru

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#4591]
### URL(s) where the issue occurs
`https://www.kakprosto.ru`

Redirection to `an.yandex.ru` occurs only in uBO.

### Describe the issue

Gif
https://imgur.com/a/tz2xYYA

### Versions

- Browser/version: [Opera|Beta]
- uBlock Origin version: [1.17.7b2]

### Settings

Screenshot:

https://i.imgur.com/07AhDmV.png

**Comment by mapx-** [comment]
Test (& see if breaks the site)
`kakprosto.ru##+js(abort-on-property-read.js, Date.prototype.toUTCString)`

**Comment by PoRtvine** [comment]
Works fine, I will ask the moderator RU AdList to add this rule.
