### ISSUE TITLE
Peter Lowe's list (& al.) break kartta.hel.fi

### ISSUE THREAD

**Issue by gitarra** [uBlockOrigin/uAssets#46]
### URL(s) where the issue occurs

`http://kartta.hel.fi/?setlanguage=en`

### Describe the issue

Snoobi.com filter breaks almost every function of the website. Try to click one of the map layers visible through the checkboxes on the left-side menu.

Web Console shows: `ReferenceError: snoobi is not defined`

### Versions

- Browser/version: Firefox any
- uBlock Origin version: 1.7.0

**Comment by peace2000** [comment]
@gitarra I don't see any breakages anymore, is this whitelisting still needed?
