### ISSUE TITLE
cbsnews.com - Content Breakage

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#460]
The video player does not load on http://www.cbsnews.com when uBO is turned on, it loads fine if uBO is turned off for the site.

**SS:**
http://i.imgur.com/pXl2Pgp.png (With uBO **_turned off_**)
http://i.imgur.com/DtzOdJ7.png (With uBO **_turned on_**)

**Error URL:** http://www.cbsnews.com/news/michelle-carter-text-suicide-trial-verdict-guilty/

The issue seems to stem from **EasyList** itself though I'm unable to triangulate the exact cause.

_**Note:** Using uBO 1.12.4 on Chrome 59 with the default filters and settings._

**Comment by okiehsch** [comment]
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=cbsnews.com`
