### ISSUE TITLE
programme-tv.net

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#461]
Hi,

**Versions**

Firefox 53.0.3 / uBo 1.12.4

**Settings**

Default settings + Liste FR

**URL**

`http://photo.programme-tv.net/trophee-des-personnalites-du-beau-monde-sur-la-terre-battue-parisienne-16712`

**Describe the issue**

- anti adblock

**SS**

http://i.imgur.com/tWeur1a.png

**Filters**

`programme-tv.net##script:inject(abort-on-property-write.js, setTimeout)`

**Comment by okiehsch** [comment]
Does
`programme-tv.net##script:inject(setTimeout-defuser.js, checkPub, 6000)`
work for you?

**Comment by SMed79** [comment]
Yes, the filter work.
