### ISSUE TITLE
"iblock filters" does not work correctly in yandex.ru/images

### ISSUE THREAD

**Issue by serrufs** [uBlockOrigin/uAssets#4612]
### URL(s) where the issue occurs

https://yandex.ru/images/search?text=test
https://yandex.ru/images/search?text=test%201

### Describe the issue

when you first search for images in Yandex, not all images are loaded (Screenshot -1) . If you do not update the page, but simply add to the current search query such as "1", you get an infinite load (Screenshot - 2)

If "uBlock filters" are disabled, there is no problem

### Screenshot(s)
<a href="https://jpegshare.net/6b/1b/6b1ba8395ed248a491f98a356ba30e2a.jpg.html" target="_blank" title="JpegShare.net - бесплатный хостинг картинок"><img src="https://jpegshare.net/thumbs/6b/1b/6b1ba8395ed248a491f98a356ba30e2a.jpg"/><a>

<a href="https://jpegshare.net/db/e7/dbe7f197b635050c877fdb78c03bcc1a.jpg.html" target="_blank" title="JpegShare.net - бесплатный хостинг картинок"><img src="https://jpegshare.net/thumbs/db/e7/dbe7f197b635050c877fdb78c03bcc1a.jpg"/><a>

### Versions

- Browser/version:  Firefox 60.4.0, Gecko 60.0 build 
- uBlock Origin version: uBlock Origin 1.17.4

### Settings

- as on Screenshot -1 no other

### Notes

I hope for your help and a speedy fix, sorry for my English

**Comment by mapx-** [comment]
test
```
@@||mc.yandex.ru/metrika/$script,first-party
@@||mc.yandex.ru/watch/$script,first-party
```

**Comment by serrufs** [comment]
> 
> 
> test
> 
> ```
> @@||mc.yandex.ru/metrika/$script,first-party
> @@||mc.yandex.ru/watch/$script,first-party
> ```

Thank you, it helped the problem disappeared
