### ISSUE TITLE
xataka.com

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#4615]
### WebSite
`https://www.xataka.com/videojuegos/los-27-mejores-juegos-de-estrategia-para-pc`

### the issue

you can not advance or rewind page

### Screenshot(s)

(buttons of chrome) https://i.imgur.com/npKWmXb.png

### Versions

- Browser/version: Chrome / 71.0.3578.98 (Build oficial) (64 bits)
- uBlock Origin version: v1.17.4

### Settings

- default settings + "uBlock filters – Annoyances" + "spa: EasyList Spanish"

### Notes
👀
👅

**Comment by mapx-** [comment]
The page  is loading fine for me (even slowly), I see no issue. Ca you explain better what do you mean ?

**Comment by pizza90** [comment]
No problem.. just in that site, i need click "50" times the back button of chrome, for go to before page.. I thought it was uBo's problem, because ublock origin is blocking a lot of trash of youtube. 

When i press the "back" button of chrome.. uBo is blocking 3 or 4 things of youtube every click. (i can see in the icon of uBo)

so.. is the youtube iframes.  You can consider this "issue" solved and closed. thanks.
