### ISSUE TITLE
idnes.cz - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#462]
Multiple requests are constantly created for `gemius.pl` on http://www.idnes.cz/. There are ads and leftover ad elements on this site as well. Anti adb warning is also displayed on the subdomain http://technet.idnes.cz.

**SS:**
https://i.imgur.com/qAufNzO.png (**_Gemius requests_**)
https://i.imgur.com/TUaczC8.png (**_Leftover ad elements_**)
https://i.imgur.com/FeNnY9A.png [**_Anti adb (annoyance)_**]
https://i.imgur.com/FuvrYU4.png (**_Ads_**)

**Error URL:**
http://zpravy.idnes.cz/macron-volby-francie-0ri-/zahranicni.aspx?c=A170616_101056_zahranicni_bur
http://technet.idnes.cz/google-translate-neural-networks-dlq-/sw_internet.aspx?c=A170418_224649_sw_internet_pka (Anti adb/ads)

The Gemius requests can be stopped by: `||1gr.cz/js/gem/xgemius.js`
Anti adb can be resolved by: `@@||1gr.cz/reklama/banner.js$script,domain=idnes.cz` 
Please look into the ads and leftover ad elements.

These issues occur while using EasyList Czech/Slovakia.

_**Note:** Using uBO 1.12.4 on Chrome 59 with default settings and additional filter mentioned above._

**Comment by gotitbro** [comment]
They are also loading ads through random URLs such as here http://ona.idnes.cz above the header.

**Comment by okiehsch** [comment]
> The Gemius requests can be stopped by: ||1gr.cz/js/gem/xgemius.js

They are already stopped by `/xgemius.` in EasyPrivacy.

> Please look into the ads and leftover ad elements.

Does
````
idnes.cz##body > div#main > table[id][class]
idnes.cz###space-g
````

work for you?

**Comment by gotitbro** [comment]
> They are already stopped by `/xgemius.` in EasyPrivacy.
Thanks for pointing out, somehow the list got disabled while enabling the CZE list.

The filters work. Please see what can be done about the ads here http://ona.idnes.cz.

**Comment by okiehsch** [comment]
`idnes.cz##script:inject(abort-on-property-write.js, bmone2n)`
you would have to tell if this breaks something on any idnes.cz-subsite, I can't read czech.

**Comment by gotitbro** [comment]
@okiehsch That works, I have checked and nothing seems to be broken. Another thing to note is that the script parameter `bmone2n` seems to belong to the Czech ad network [**Internet BillBoard**](http://www.ibillboard.com/en/):
http://help.billboard.cz/xwiki/bin/view/AdServer+v2/One2manyLook
http://help.billboard.cz/xwiki/bin/view/AdServer+v2/InternalSite

**PS:** I don't know much Czech either but you can translate from Czech in Chrome for which neural support was recently added (the error article I was reading) :)

**Comment by gwarser** [comment]
`https://technet.idnes.cz/`
`https://technet.idnes.cz/mars-curiosity-zivot-buten-organicka-latka-nasa-fud-/tec_vesmir.aspx?c=A180608_055750_tec_vesmir_kuz`
I see banner on top after reload or navigation to article.

**Comment by mapx-** [comment]
test
`/technet\.idnes\.cz\/[0-9a-zA-Z-_]{30,}/$domain=technet.idnes.cz,script`

**Comment by zaphodbeebblebrox** [comment]
It appears to work.

**Comment by gwarser** [comment]
Blocks movie https://technet.idnes.cz/mars-curiosity-zivot-buten-organicka-latka-nasa-fud-/tec_vesmir.aspx?c=A180608_055750_tec_vesmir_kuz

**Comment by mapx-** [comment]
```
technet.idnes.cz##script:inject(set-constant.js, Ads.ok, true)
/technet\.idnes\.cz\/[0-9a-zA-Z-_]{30,}/$domain=technet.idnes.cz,script
@@||technet.idnes.cz^*/$script
```

**Comment by mapx-** [comment]
@tomasko126

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/8psvlk/need_help_with_filters_on_site_with_delayed_ads/

**Comment by trumpeta** [comment]
technet.idnes.cz##script:inject(set-constant.js, Ads.ok, true)
/technet\.idnes\.cz\/[0-9a-zA-Z-_]{30,}/$domain=technet.idnes.cz,script
@@||technet.idnes.cz^*/$script

On *.idnes.cz worked reliably

Can you give a more insight how to build these filters
I have another site with script injection and those don't apply there.

**Comment by gwarser** [comment]
Meta bug https://github.com/uBlockOrigin/uAssets/issues/2790
