### ISSUE TITLE
ganool.watch

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4622]
### URL(s) where the issue occurs

`https://ganool.watch/movie/looking-glass-2018/`

### Describe the issue

whole page surrounded ads/placeholders
### Screenshot(s)
![screenshot 94](https://user-images.githubusercontent.com/20338483/51083892-6ec48300-1747-11e9-8c21-b69aa23e7017.png)

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

-  uBO's default settings

**Comment by mapx-** [comment]
already fixed in the regional list (ABPindo)

However, you can use:

```
ganool.watch###popup-banner
ganool.watch###top-banner
ganool.watch###ptbanner
*.gif$domain=ganool.watch
ganool.watch##[href*="/advertising/"]
```
