### ISSUE TITLE
hdmoviesfair.xyz

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4629]
### URL(s) where the issue occurs

`https://hdmoviesfair.xyz/k-g-f-chapter-1-2018-full-hd-movie-free-download-720p`

### Describe the issue

pop up ads
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

-uBO's default settings

**Comment by ghajini** [comment]
`https://hdmoviesfair.ws/kalank-2019-full-hd-movie-free-download-720p/`
Popup ads

**Comment by ghajini** [comment]
Loading bar at top Firefox android 
`hdmoviesfair.ws##[id*="ScriptRoot"]`

**Comment by ghajini** [comment]
popups

`https://hdmoviesfair.fun/vanguard-2020-full-hd-movie-free-download-hindi-dual-audio-720p-hd/`

**Comment by Yuki2718** [comment]
The player doesn't work on my end, complaining "network error". If I turned uBO off it works after many popups.

**Comment by okiehsch** [comment]
Hm, I can only reproduce with Firefox, it works fine with Chromium.
The breakage is not caused by the filter I added, if I reomove it the player is still broken.

**Comment by Yuki2718** [comment]
Yep, here Firefox too. Haven't tested with the filter disabled.

**Comment by okiehsch** [comment]
`https://dood.so/e/1cozwmym1mij`
the breakage is caused by some `dood.so` filter.

**Comment by okiehsch** [comment]
Hm, it's not caused by any of our script:injections.
I can't pinpoint it.

**Comment by mapx-** [comment]
I disabled uBO for that video and still network error
`https://dood.so/e/1cozwmym1mij`

**Comment by okiehsch** [comment]
@Yuki2718 you said the video played on your end after disabling uBO?

**Comment by Yuki2718** [comment]
Yes, will try again.

**Comment by Yuki2718** [comment]
Now I can't even connect to `hdmoviesfair.ws`. If I use the direct dood URL I also got the error, huh.

**Comment by okiehsch** [comment]
Ok, seems to be some site issue specific to Firefox.

**Comment by Yuki2718** [comment]
Also got the error with the original URL, it only worked once and no more. As you said probably not the uBO issue.

**Comment by mapx-** [comment]
`Cannot play media. No decoders for requested formats: video/mp4`

![image](https://user-images.githubusercontent.com/10303732/105487568-9c3a5480-5cb0-11eb-9381-b5870365bfeb.png)

**Comment by Yuki2718** [comment]
Indeed strange - possibly I mistook something?

**Comment by uBlock-user** [comment]
403 error ? seems its  geo-targeted.

**Comment by mapx-** [comment]
> 403 error ? seems its geo-targeted.

does not make sense, same ip chrome / FF

**Comment by uBlock-user** [comment]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://doodstream.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Webmaster needs to set `Access-Control-Allow-Origin` to `*`

**Comment by ghajini** [comment]
> 
> 
> `https://dood.so/e/1cozwmym1mij`
> the breakage is caused by some `dood.so` filter.

works correctly sir ,nothing happened
https://user-images.githubusercontent.com/20338483/105504284-96af2f80-5ced-11eb-8a92-6688ed0dfc42.png

403 error may be ip restriction  that happens with other sites also eg cloudvideo.tv

**Comment by ghajini** [comment]
can make filters hdmoviesfair.* ,site changes frequently
