### ISSUE TITLE
bloomberg.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#463]
The navigation menu appears under the tabs on pages instead of appearing over them.

**Screen Capture:** https://streamable.com/y70xa
**Error URL:** https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=242837958

_**Note:** Using uBO 1.12.4 on Chrome 59 with the default filters and settings._

**Comment by gorhill** [comment]
The issue also exists without a blocker.

    bloomberg.com##.bb-nav-submenu:style(z-index: 1000 !important;)

**Comment by gotitbro** [comment]
> The issue also exists without a blocker.

It does not actually, when adb is turned off the space below the navigation menu is taken by an ad and when the navigation menu is browsed it does come over the ad: https://streamable.com/32sm4

The filter works. Also similar issue with the search bar, it comes under the tabs as well: http://i.imgur.com/T8fEVkz.png

----------------------------------------------------------------------------------------------------------------------

It takes some time before the elements are hidden on company profile pages.

**Screen Capture:** https://streamable.com/0ct0o
**Error URL:** https://www.bloomberg.com/profiles/companies/1041347D:LN-captify-media-ltd

**Comment by gotitbro** [comment]
> Also similar issue with the search bar, it comes under the tabs as well: http://i.imgur.com/T8fEVkz.png

This is also fixed by a similar filter as the one suggested above: 
`bloomberg.com##.bb-search-drawer:style(z-index: 1000 !important;)`

@gorhill Please see what can be done for the issue of the late hiding elements above.

**Comment by gotitbro** [comment]
@gorhill Just realized that the elements being hidden late are not due to cosmetic filters. These are automatically hidden when no ad loads in them by an inline script on the page. 

One way to solve this is hiding the ad elements through the blocker itself:
`bloomberg.com##.partner_module`

**Comment by gotitbro** [comment]
> I am obviously missing one or more deleted comments here

@okiehsch The initial filter was suggested by @gorhill not sure why he deleted his comment. And yes my issue is fixed by these filters.

**Comment by gotitbro** [comment]
@okiehsch @gorhill The filters above cause a problem wherein the functions of the stickied header become unusable (which also contains the share buttons).

**Screencapture:** https://streamable.com/d07vu

**Error URL:** 
**https://www.bloomberg.com/news/articles/2017-07-31/venezuela-s-president-maduro-personally-sanctioned-by-the-u-s**

**Comment by gotitbro** [comment]
@okiehsch The stock list below the header is blocked on stock quote pages on https://www.bloomberg.com. It loads fine when uBO is disabled.

**SS:** https://i.imgur.com/6GluN94.png (SS of the item getting blocked, marked)
**Error URL:** `https://www.bloomberg.com/quote/FAST:US`

**Comment by mapx-** [comment]
```
bloomberg.com#@#.page-ad
@@||securepubads.g.doubleclick.net^$script,domain=bloomberg.com
@@||googletagservices.com/tag/js/gpt.js$script,domain=bloomberg.com
```

last one necessary to set OFF the filter from ublock privacy

**Comment by gotitbro** [comment]
> last one necessary to set OFF the filter from ublock privacy

@mapx- What do you mean by that?

**Comment by mapx-** [comment]
start by providing your feedback => do the filters work or not for you ?

**Comment by gorhill** [comment]
@mapx- 

> is this normal that redirect filter (last one from ublock privacy) gives no info about its redirecting in the logger ?

I see the redirection on my side (without the exception filter of course).

**Comment by mapx-** [comment]
@gorhill , right ... (first I have selected all "--" , so the redirect wasn't there).
However, zooming in the filter I see the filter from ublock privacy but not ..partially:

`Static filter ||googletagservices.com/tag/js/gpt.js$script found in: uBlock filters – Privacy`

and not `||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices.com/gpt.js`

**Comment by gorhill** [comment]
By design really: the raw redirect filter is parsed into a plain block filter, which is what triggers the block (what you see reported with `--`), and into a redirection directive outside of the static filtering engine, which is what is reported by `<<` (because redirection will also take place if the block is through the dynamic filtering engine).

**Comment by gotitbro** [comment]
@mapx- Yes, the filters seem to work. The stock list loads fine after adding them but a lot additional ad requests are created. No better way to resolve this?

**Comment by mapx-** [comment]
gotitbro, be my guest searching for other "better way".

Well, you can talk about "better way" only after all the tests (you did no tests), trying redirect filters (still nothing, right ?). And learn - first of all - to say "thanks" to the guys helping you (at least for the time spent to help you).

**Comment by gotitbro** [comment]
@mapx- Sorry, I always make sure to say thanks to anyone helping me on their own accord I don't know why I forgot to do that this time. Thank you for taking your time and helping me I am in no way ungrateful for you helping me out. I appreciate all that you do and again thank you for that.

I was only asking as I did't know any better. Sorry again if that made me come out as disingenuous.

**Comment by gotitbro** [comment]
@okiehsch Still facing the header issue, unable to use the dropdown menu and share buttons https://github.com/uBlockOrigin/uAssets/issues/463#issuecomment-319173127 due to these filters in the filter list:
```
bloomberg.com##.bb-nav-categories:style(z-index: 1000 !important;)
bloomberg.com##.bb-nav-search:style(z-index: 1000 !important;)
```

**Screencapture:** `https://streamable.com/bdk13`

**Error URL:** `https://www.bloomberg.com/news/articles/2017-12-20/bitcoin-tech-stocks-and-xi-top-2017-google-financial-searches`

The filters should probably be removed.

**Comment by gotitbro** [comment]
@okiehsch @mapx- Can you see if the above issue can be fixed? Thanks.

**Comment by gotitbro** [comment]
@mapx- Looks like a comment I made was removed but I can't find out which one. I really try not to make comments that offend or aren't appropriate.

Please do tell me which comment was removed so that I can understand and improve.

**Comment by mapx-** [comment]
only noise (from me and you)

see if disabling one of the filters above works for you 
`bloomberg.com#@#.bb-nav-categories:style(z-index: 1000 !important;)`

**Comment by gotitbro** [comment]
@mapx- Thanks for letting me know.

Yes it works but if one filter is removed the second one is rendered useless. So better remove both the filters.

**Comment by mapx-** [comment]
ok, but all other issues are ok now ?

**Comment by gotitbro** [comment]
@mapx- No. The filters were added to fix the dropdown menu in selected pages of the Bloomberg website (company info pages) but since they break majority of the dropdown menus on the main Bloomberg website. I think it will be better to remove them.

**Comment by gotitbro** [comment]
@mapx- The stock list issue https://github.com/uBlockOrigin/uAssets/issues/463#issuecomment-345464753.

Seems to be fixed on my side by the filters:
```
bloomberg.com#@#.page-ad
@@||securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1$domain=bloomberg.com
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=bloomberg.com
@@||googletagservices.com/tag/js/gpt.js$script,domain=bloomberg.com
```

https://forum.adguard.com/index.php?threads/bloomberg-com-missed-ads-windows.27159/#post-160913

**Comment by mapx-** [comment]
- on the main page `https://www.bloomberg.com/` no issue for me
