### ISSUE TITLE
cloudvideo.tv

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4636]
### URL(s) where the issue occurs

`https://cloudvideo.tv/232twfoafeo6`

### Describe the issue

ads sometimes  blocked through existing filters or sometimes ads get through it
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
`cloudvideo.tv/t0pjubv9pl91#`
Clicking on download -direct link to download generates VPN review ads in new tab

**Comment by mapx-** [comment]
click download button unuder the video, then normal download => click again download direct all fine for me, no vpn ads / new tab

**Comment by ghajini** [comment]
Iam on opera browser with uptodate filters,
Firefox not affected

**Comment by mapx-** [comment]
try
`cloudvideo.tv##+js(set-constant.js, SubmitDownload1, noopFunc)`

**Comment by ghajini** [comment]
Sorry for late feedback, it works on my end

**Comment by ghajini** [comment]
`https://cloudvideo.tv/zfyy3b012nnc`
popup ads 
unknown xhr's

**Comment by ghajini** [comment]
Crap xhr's 
`https://cloudvideo.tv/di7d0tj61el5`

**Comment by ghajini** [comment]
`cloudvideo.tv/cl2k1ao9pfwz`

Video not playing due to Easylist bad filter

**Comment by ghajini** [comment]
`https://cloudvideo.tv/nxfkx85u4gn4`
Update existing filters 

`cloudvideo.tv##+js(abort-current-inline-script, Math, zfgloaded)
cloudvideo.tv##+js(abort-current-inline-script, Object.defineProperty, vocabulary)`

to

`cloudvideo.tv##+js(abort-current-inline-script, Math, XMLHttpRequest)`

**Comment by ghajini** [comment]
### URL =`https://cloudvideo.tv/znxusu4ds7ii

### Issue=
Like this 
https://github.com/uBlockOrigin/uAssets/issues/7850
https://github.com/uBlockOrigin/uAssets/issues/7850

problem occurred again

Video inaccessible due to cname blockade by Easylist filter 

`|https://$script,3p,domain=cloudvideo.tv

### Screenshots =

https://user-images.githubusercontent.com/20338483/94409539-e9d80200-0193-11eb-9e7d-054919bbb0cd.png

https://user-images.githubusercontent.com/20338483/94409576-f6f4f100-0193-11eb-86a3-9712cd9ba3f8.png

https://user-images.githubusercontent.com/20338483/94409602-0411e000-0194-11eb-8050-06a8d50e7152.png

Settings =

Default +decentraleyes+browsec vpn(UK)

Notes =
`cloudvideo.tv##+js(acis, Math, btoa)`

Worthy replacing `cloudvideo.tv##+js(acis, Math, XMLHttpRequest)`

**Comment by ghajini** [comment]
Popup ads
### URL =
`https://cloudvideo.tv/embed-yfak4hbptx89.html`

Firefox A. nightly, ublock origin 1.30.6

**Comment by ghajini** [comment]
popup ads

new domain of cloudvideo (old still functional)

`https://cloudvideotv.stream/embed-z0cxg1n3c0mg.html` 
link source from `https://w.seehd.to/tv/the-falcon-and-the-winter-soldier-season-1/watching/?ep=36854&sv=5`

This work
```
cloudvideotv.stream##+js(aopw, Fingerprint2)
cloudvideotv.stream##+js(acis, Math, break;case $.)
```
