### ISSUE TITLE
https://gifsis.com [anti adblock] 

### ISSUE THREAD

**Issue by diab0lik** [uBlockOrigin/uAssets#4638]
### URL(s) where the issue occurs

`https://gifsis.com/M1z6`

### Describe the issue

comes up with this message:
We have detected you are using Adblockers. Please disable your Adblocker for this site and refresh this page to continue. Ads are only our revenue stream.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: chrome 71.0.3578.98
- uBlock Origin version: 1.17.4

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
`https://gifsis.com/5Rl48cX`
after captcha completion in next page during countdown timer if i click anywhere in page i got popups
![screenshot 100](https://user-images.githubusercontent.com/20338483/51164305-86744680-18c2-11e9-95a0-47e3c4985a0c.png)

**Comment by okiehsch** [comment]
I can reproduce, will add a fix.
