### ISSUE TITLE
Rule `myanimelist.net##div[style][data-height]` is problematic

### ISSUE THREAD

**Issue by ethus3h** [uBlockOrigin/uAssets#464]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://myanimelist.net/profile/zZcelsuruZz`

### Describe the issue

The filter entry `myanimelist.net##div[style][data-height]` in _Fanboy’s Enhanced Tracking List_ and _Fanboy+Easylist-Merged Ultimate List_ hides the buttons for expanding hidden sections of the profile page. A fixed replacement rule is `myanimelist.net##div[style][data-height]:not(.btn-truncate)`.

### Screenshot(s)

- https://archive.org/download/Liquid-2017-06-18-14-10-24-575352232-2d303430300a-6417383f-cf55-41d6-9660-39d14bed8398/Screenshot_2017.06.18_14.07.38.png

### Versions

- Browser/version: Firefox 52.1.0 ESR Gentoo package
- uBlock Origin version: 1.12.4

### Settings

- https://archive.org/download/Liquid-2017-06-18-14-12-38-718584347-2d303430300a-cdb1f83e-55f4-4989-84be-032a07af83a4/my-ublock-backup_2017-06-18_14.12.17.txt

### Notes

 A fixed replacement rule is `myanimelist.net##div[style][data-height]:not(.btn-truncate)`.

**Comment by okiehsch** [comment]
> The filter entry `myanimelist.net##div[style][data-height]` in **Fanboy’s Enhanced Tracking List** and 
**Fanboy+Easylist-Merged Ultimate**

This will not be fixed in `uBO filters` https://github.com/uBlockOrigin/uAssets/issues/423#issuecomment-305553681
