### ISSUE TITLE
Openload.co blocking upload on home page

### ISSUE THREAD

**Issue by Brolyns** [uBlockOrigin/uAssets#4644]
`https://openload.co` 

I'm getting this message on the homepage

> You might have to disable your adblocker for uploading. Their latest filter blocks uploads.
> Feel free to blame the AdBlock people...

**Comment by mapx-** [comment]
Did you test if it's only an annoyance or the uploads are somehow blocked / broken ?

**Comment by Brolyns** [comment]
he prevents me of uploading the videos if I let the easylist filter marked

**Comment by mapx-** [comment]
ok, using the filter above I guess all is ok now, right ?

**Comment by mapx-** [comment]
uBo icon, last icon on the right (dashboard), "my filters" tab

**Comment by Brolyns** [comment]
this works on old versions of chrome or ublock? i uses version 49 of chrome and 1.16.18 on windows xp

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

Did you follow my indications ? read also the wiki linked above

**Comment by mapx-** [comment]
I added the filter to `ublock filters list`
