### ISSUE TITLE
brainly

### ISSUE THREAD

**Issue by TristramGreenman** [uBlockOrigin/uAssets#4645]
### URL(s) where the issue occurs 

`[ https://brainly.com/ ]`

### Describe the issue

[ After browsing 1 or 2 answers on brainly i get this page (look at screenshot provided
and the answer is also hidden.]

### Screenshot(s)

[ https://gyazo.com/4680f6fb868a54c0388f45354facc641 ]

### Versions

- Browser/version: [newest]
- uBlock Origin version: [newest]

### Settings

- [default]

**Comment by mapx-** [comment]
Enable ublock annoyances list and test again

**Comment by TristramGreenman** [comment]
> Enable `uBlock filters – Annoyances list` and test again

Just tested and the issue is still the same

**Comment by okiehsch** [comment]
I can't reproduce, with `uBO-annoyances` enabled.
![image](https://user-images.githubusercontent.com/16838044/51214759-22cc3680-191f-11e9-8276-d38607548185.png)

With `uBO-annoyances` disabled.

![image](https://user-images.githubusercontent.com/16838044/51214819-4abb9a00-191f-11e9-80af-59bffe332b11.png)

**Comment by TristramGreenman** [comment]
> I can't reproduce, with `uBO-annoyances` enabled.
> ![image](https://user-images.githubusercontent.com/16838044/51214759-22cc3680-191f-11e9-8276-d38607548185.png)
> 
> With `uBO-annoyances` disabled.
> 
> ![image](https://user-images.githubusercontent.com/16838044/51214819-4abb9a00-191f-11e9-80af-59bffe332b11.png)

Can you see the answer on the bottom of the page? And if you can open up some other answers and see if it hides it. I should have structured my main thread better. The real problem is the fact that i can't see the answer on the bottom of the page after browsing a couple of answers because it makes me watch an ad first when before UBlock was able to fix that problem for me. Apologizes.
 ( https://gyazo.com/eb4338b6b2750b0398f2460929e7b2b3 ) As you can see it says "watch a video to unlock the answer".

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/51215681-0b427d00-1922-11e9-9563-3727bd16df35.png)

This is unrelated to any adblocker one uses, as you can see in my screenshot I disabled `uBO` and the answers are still blocked.

**Comment by mapx-** [comment]
use as custom filter
`brainly.com##+js(setTimeout-defuser.js, trigger, 0)`

**Comment by okiehsch** [comment]
I can circumvent it, not sure if it should be added to a filter list.
@gorhill

**Comment by TristramGreenman** [comment]
> use as custom filter
> `brainly.com##+js(setTimeout-defuser.js, trigger, 0)`

This works, thanks a lot <3

**Comment by gorhill** [comment]
> maybe we should add a fix

Well when I click "Watch a video", I am being presented with a "Disable ad-blocker" message, so this falls under the anti-blocker policy.
