### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4648]
### URL(s) where the issue occurs

`https://www.cnn.com/travel/article/airlander-10-prototype-new-model-gbr-intl/index.html`

### Describe the issue

Unblocked ads on the bottom right column.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/51253621-d7407980-196c-11e9-8e68-191759b2a5e5.png)

### Versions

- Browser/version: Chrome 71
- uBlock Origin version: 1.17.4

### Settings

default

### Notes

`##div.PartnerLinks__component.PartnerLinks__isSmall:nth-of-type(1)`
`##div.PartnerLinks__component.PartnerLinks__isSmall:nth-of-type(2)`

or

`##div.Article__wrapper:nth-of-type(3) > .Article__secondary`

**Comment by mapx-** [comment]
add
`cnn.com##.PartnerLinks__component, .PromoBestBeaches__component`

@ryanbr

**Comment by Khrin** [comment]
these are still present?
