### ISSUE TITLE
gaana.com - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#465]
An ad is displayed specifically for adblock users in the right sidebar on http://gaana.com.

**SS:** https://i.imgur.com/XjCEKTk.png
**Error URL:** http://gaana.com

While this ad can be blocked by:
`||gaanacdn.com/images/rhs_banner` 
OR 
`gaana.com##script:inject(abort-on-property-read.js,dfp.trackBlocker)`

The right sidebar is still not completely hidden. Please see if the right sidebar can be hidden,

_**Note:** Using uBO 1.12.4 on Chrome 59 with the default filters and settings._

**Comment by gotitbro** [comment]
@okiehsch @gorhill Can something be done about this issue?

**Comment by okiehsch** [comment]
I would classify this as self-promotion, which, @gorhill  has [stated](https://github.com/uBlockOrigin/uAssets/issues/390#issuecomment-298669083), will not go into uBO-filters.

**Comment by gotitbro** [comment]
@okiehsch I understand, can I do something to hide the sidebar on my side. It would be great if you can help, thank you.

**Comment by SMed79** [comment]
> can I do something to hide the sidebar on my side.

Check https://forums.lanik.us/viewtopic.php?f=62&t=36082&hilit=/loaddfp?#p115402

**Comment by gotitbro** [comment]
@SMed79 Thanks, as I said in the first post the ad can be blocked but can I hide the ad sidebar?

**Comment by gotitbro** [comment]
The sidebar can be hidden by:
```
gaana.com###mainarea:style(padding:0;)
gaana.com##.add_block:style(display:none!important;)
```

Automatically converted filters by uBO from **_Adguard English Filter_**: https://github.com/AdguardTeam/AdguardFilters/commit/774b67d29ef3a2dd9c5e45954babd08a7b9444b7

Thanks @seanl-adg

**Comment by gotitbro** [comment]
@okiehsch The above filters don't seem to be working for me anymore, they work with Adguard as intended. From what I can see they should work, can you please check if they work for you?

**Comment by gwarser** [comment]
`gaana.com###mainarea:style(padding:0 !important;)`

**Comment by gotitbro** [comment]
@gwarser That works, thanks.
