### ISSUE TITLE
aniwatcher.com/anilinkz.com{NSFW}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4653]
### URL(s) where the issue occurs
NSFW
1.
`https://aniwatcher.com/boruto-naruto-next-generations-episode-89?src=3`

2.
`http://v.anilinkz.com/watch-EasyV-boruto_naruto_next_generations_-_89.mp4`
`http://v.anilinkz.com/watch-Pbb-at/nw/boruto_naruto_next_generations_-_89.mp4`

### Describe the issue

1.popup ads when i select `mystream` as a video source at aniwatcher

2.page blank here
 `http://v.anilinkz.com/watch-Pbb-at/nw/boruto_naruto_next_generations_-_89.mp4`
`http://v.anilinkz.com/watch-EasyV-boruto_naruto_next_generations_-_89.mp4`
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
`https://aniwatcher.com/boku-no-hero-academia-the-movie-futari-no-hero?src=3`
popup ads
firefox 65 default settings

**Comment by ghajini** [comment]
still there popup ads on
`https://aniwatcher.com/boku-no-hero-academia-the-movie-futari-no-hero?src=9`
![screenshot 119](https://user-images.githubusercontent.com/20338483/52737194-bb72d680-2ff1-11e9-9fbb-35f5c802d7f0.png)

**Comment by mapx-** [comment]
I get no other popup

**Comment by ghajini** [comment]
did you try chromium browsers...on my side with opera browser still get ads
`https://aniwatcher.com/boku-no-hero-academia-the-movie-futari-no-hero?src=9`
![screenshot 120](https://user-images.githubusercontent.com/20338483/52741747-20332e80-2ffc-11e9-921f-52da471dfb25.png)

**Comment by okiehsch** [comment]
No popups with chromium on my end.

**Comment by mapx-** [comment]
I get popups with opera ..

**Comment by mapx-** [comment]
@ghajini  see if works for you
`||vev.io^$inline-script`

**Comment by ghajini** [comment]
if it doesn't break anythung on `vev.io` then its good
popup ads gone...
also video over here `https://vev.io/1lok812lq1ok` plays

**Comment by okiehsch** [comment]
No breakage with `||vev.io^$inline-script` at
`https://vev.io/embed/zl32wn998k3v`
on my end.
