### ISSUE TITLE
https://www.mamahd.org/ [anti-adblock]

### ISSUE THREAD

**Issue by boolbaall** [uBlockOrigin/uAssets#4654]
### URL(s) where the issue occurs

`https://www.mamahd.org/`

### Describe the issue

After a few seconds on the page, or clicking one of the menu links, anti-adblock message comes up

### Screenshot(s)
![image](https://user-images.githubusercontent.com/46777772/51307304-3ff42880-1a37-11e9-8899-6f0fec208d33.png)

### Versions

- Browser/version: latest Chrome
- uBlock Origin version: latest ublock Origin (with nano defender installed)

### Settings

[my-ublock-backup_2019-01-17_08.57.30.txt]

**Comment by mapx-** [comment]
> nginx error! The page you are looking for is temporarily unavailable. Please try again later.

**Comment by adranger** [comment]
The server is back online now. I don't get that message with the lists I use. 

@boolbaall When you want to share you settings, you need to drag and drop your list to the issue textbox and wait for it to be uploaded, and then not to edit the generated code. 

@AdamWr bottom cookie notice with `Adguard Annoyances`.

**Comment by AdamWr** [comment]
>@AdamWr bottom cookie notice with Adguard Annoyances.

Ok, added:
`mamahd.org###easy-cookies-policy-main-wrapper`
