### ISSUE TITLE
bitcoinqrcodegenerator.win

### ISSUE THREAD

**Issue by giantoppai** [uBlockOrigin/uAssets#4656]
### URL(s) where the issue occurs

`bitcoinqrcodegenerator.win`

### Describe the issue

It provides false QR codes to their own bitcoin address possibly at random times.

### Notes

[Reddit Source 1](https://www.reddit.com/r/Bitcoin/comments/9evc2m/pretty_sure_i_just_got_scammed_using_a_qr/)
[Reddit Source 2](https://www.reddit.com/r/btc/comments/acaz09/i_am_an_idiot_and_i_got_scammed/ed6sesz/)
[Reddit Source 3](https://reddit.com/r/Bitcoin/comments/8yuuly/please_report_these_known_scams/)

**Comment by adranger** [comment]
On a related note, try `the-qrcode-generator.com`. I've been using it for a long time and never had any problem with it.

**Comment by mapx-** [comment]
@giantoppai Are you saying the site should be blocked (`badware list`)

**Comment by smed79** [comment]
> Are you saying the site should be blocked (badware list) ?

Yes, because it's provide a fake QR code BTC adress
