### ISSUE TITLE
Live broadcasting is broken on RT.com when «hpHosts’ Ad and tracking servers» is enabled.

### ISSUE THREAD

**Issue by pubmikeb** [uBlockOrigin/uAssets#466]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
https://www.rt.com/on-air/

### Describe the issue
I get `manifestLoadError` instead of video player when «hpHosts’ Ad and tracking servers» is enabled.

### Versions

- Browser/version: Google Chrome 61.0.3128.2
- uBlock Origin version: 1.12.4

### Settings
I disabled all list except «hpHosts’ Ad and tracking servers» but the problem still persists.

### Notes

**Comment by gorhill** [comment]
Use `@@||secure.footprint.net^$domain=rt.com`.
