### ISSUE TITLE
freeonilneanime.net

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4662]
### URL(s) where the issue occurs

`http://freeonlineanime.net/episode/dragon-ball-super-dub-episode-93/`

### Describe the issue

pop ads
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

- uBO's default settings

**Comment by okiehsch** [comment]
Well, https://github.com/uBlockOrigin/uAssets/commit/b0a5d429254df32f93917e180b28fb5012a327f9 has fixed this issue too.
