### ISSUE TITLE
Microsoft Pop Ups

### ISSUE THREAD

**Issue by dhigh88** [uBlockOrigin/uAssets#467]
### URL(s) where the issue occurs
https://www.iwatchonline.cr

### Describe the issue
Whenever I visit this website iwatchonline.cr and click anywhere inside this page, I have "Microsoft Official Support" Pop ups and they are frustrating. I have to open task manager just to shut down MS Edge immediately. This doesn't happen on Firefox or Chrome. I did a malware scan to make sure as it didn't find anything. It's a Ublock Origin issue with Edge because these ads also appeared on other random sites in the past that normally Ublock Origin should be blocking. Firefox and Chrome doesn't have this problem when tested, and I also read somewhere this is a common fake scam with Edge apparently.
### Screenshot(s)
![27307136-4a83b622-5516-11e7-8a06-9adca7916488](https://user-images.githubusercontent.com/26260953/27397613-f6265f4c-5684-11e7-8cd1-6419dd6532ea.jpg)
![27307147-595ca3e8-5516-11e7-9d66-14c21e7e6777](https://user-images.githubusercontent.com/26260953/27397624-fc0f0332-5684-11e7-877e-8ba5b2c77870.jpg)

### Versions
 Browser/version: Microsoft Edge 40.15063.0.0
uBlock Origin version: 1.12.4

### Settings
Default

### Notes

Went to iwatchonline.cr and clicked anywhere around the page. Pop ups would appear (as they rarely get closed immediately each visit to the site). It's false pop up ads from Microsoft telling you to call the number as it locks the browser.  Task manager has to be opened in order to completely close these pop ups.

**Comment by mapx-** [comment]
add
```
||s3.amazonaws.com/$xmlhttprequest,domain=www.iwatchonline.cr
||ov2ochu.bid
```

**Comment by okiehsch** [comment]
I can't check if this works with Edge, so @dhigh88 I need some feedback, does
````
iwatchonline.cr##script:inject(abort-on-property-write.js, Fingerprint2)
||s3.amazonaws.com^$xmlhttprequest,domain=iwatchonline.cr
||ov2ochu.bid^
````
work for you?

**Comment by dhigh88** [comment]
@mapx- Thank you! It works. Hopefully Ublock origin with Edge avoids more of these pop ups on future sites as sometimes it gets really random.

**Comment by dhigh88** [comment]
@okiehsch Hello, thanks for the response. I tried the first suggestion before yours as it worked already. Appreciate very much the help. the two lines did the trick.

**Comment by SMed79** [comment]
@okiehsch add also `iwatchonline.eu`

```
|http://$xmlhttprequest,script,subdocument,third-party,domain=iwatchonline.cr|iwatchonline.eu
|https://$xmlhttprequest,script,subdocument,third-party,domain=iwatchonline.cr|iwatchonline.eu
```
SS: http://i.imgur.com/cDWEUps.png
about `ov2ochu.bid` admeasures revolving adservers [viewtopic.php?p=115673#p115673](https://forums.lanik.us/viewtopic.php?p=115673#p115673)
subdocument adservers https://pastebin.com/raw/BDPHJJNQ
