### ISSUE TITLE
shrinkearn.com + clk.sh 

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4672]
### URL(s) where the issue occurs

`[https://shrinkearn.com/CD9nC]`
`[https://clk.sh/nLjHLwz]`

### Describe the issue

[can't right click or copy for both sites.]

### Versions

- Browser/version: [chrome 71.0.3578.98]
- uBlock Origin version: [1.17.4]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
@mapx- 
`https://shrinkearn.com/CD9nC`

popup after  doing captcha and clicking the skip ad button. also malicious site to block `qkpcihpo16.com`.

**Comment by mapx-** [comment]
does thse work for you ?
```
*$frame,domain=shrinkearn.com,3p
shrinkearn.com##+js(addEventListener-defuser.js, click, trigger)
```

**Comment by okiehsch** [comment]
````
*$frame,domain=shrinkearn.com
shrinkearn.com##+js(abort-on-property-read.js, open)
||qkpcihpo16.com^
````
works fine on my end.

**Comment by dumbusernameidk** [comment]
both work.
