### ISSUE TITLE
legionprogramas.org [Fake Button] [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4677]
URL(s) where the issue occurs

`http://legionprogramas.org/descargar/ccleaner-professional-technician-business-v5-52-6967-espanol-u4e`

Describe the issue

Fake Button Pop-up

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 71 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.4

Settings

Default

**Comment by lain566** [comment]
@okiehsch Click on the download link, there's an anti adblock warning.

![880538bc-9e62-4a4b-9d6b-3c9fb9d43ccb](https://user-images.githubusercontent.com/27441315/51432895-d72bcc80-1c3f-11e9-9292-bb4abef45bf1.png)

**Comment by KiLL4FuNK** [comment]
anti adblock

**Comment by KiLL4FuNK** [comment]
Anti Adblock

**Comment by KiLL4FuNK** [comment]
Anti Adblock
