### ISSUE TITLE
europixhd.com & topeuropix.net (same site, different appearance)

### ISSUE THREAD

**Issue by Qu4dr0** [uBlockOrigin/uAssets#4678]
### URL(s) where the issue occurs

```
https://europixhd.com/tvseries/scrubs-online/scrubs-season-1-hd-with-subtitles-europix
https://topeuropix.net/tvseries/scrubs-online/scrubs-season-1-hd-with-subtitles-europix
```

### Describe the issue

Every once in a while an invisible window appears to catch the clicks when you try to pause the video or choose another episode, when you click it opens and closes a new tab, collecting clicks I pressume.

### Screenshot(s)

https://i.imgur.com/TqmS8TR.jpg

### Versions

- Browser/version: Google Chrome 71.0.3578.98 (64-bit) (I'm 100% sure it applies to any version)
- uBlock Origin version: 1.17.4
- Tampermonkey + RU AdList JS Fixes

### Settings

uBlock filters​​​​​, uBlock filters – Badware risks​​​​​, uBlock filters – Privacy​​​​​, uBlock filters – Resource abuse, uBlock filters – Unbreak​​​​​, Adblock Warning Removal List​​​​​, EasyList​​​​​, EasyPrivacy, Malware Domain List​​​​​, Malware domains, Peter Lowe’s Ad and tracking server list​​​​​, RUS: Adguard Russian Filter​​​​​, RUS: RU AdList, RU AdList: BitBlock

**Comment by krystian3w** [comment]
I do not have in Firefox should this maybe true:

>  (I'm 100% sure it applies to any version)
