### ISSUE TITLE
Can't post link to Facebook ads preferences

### ISSUE THREAD

**Issue by S-Graham** [uBlockOrigin/uAssets#4680]
### URL(s) where the issue occurs

`https://www.facebook.com/ads/preferences`

### Describe the issue

I wrote a Facebook post to help friends manage their Facebook advertising preferences, but Ublock Origin hides it from me!
The rule "facebook.com,facebookcorewwwi.onion##.userContentWrapper:has(a[href*="/ads/"])" matches a post if it includes a reference to "https://www.facebook.com/ads/preferences"

### Versions

- Browser/version: Vivaldi	2.2.1388.37
- uBlock Origin version: 1.17.4
### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
Disable the above filter with `facebook.com,facebookcorewwwi.onion#@#.userContentWrapper:has(a[href*="/ads/"]) ` and try `facebook.com,facebookcorewwwi.onion##.userContentWrapper:has(a[href*="/ads/"]):not(a[href*="/ads/preferances"])`

**Comment by krystian3w** [comment]
>`facebook.com,facebookcorewwwi.onion##.userContentWrapper:has(a[href*="/ads/"]):not(a[href*="/ads/preferences"])`

Invalid? <sup> https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pseudo-class-if-not </sup>

`##.userContentWrapper:if(a[href*="/ads/"]):if-not(a[href*="/ads/preferences"])`

`##.userContentWrapper:has(a[href*="/ads/"]):not(:has(a[href*="/ads/preferences"]))`


---

Demo on github to try block my post with bait:

> <sup> https://github.com/#/ads/find </sup>

###### old syntax:
`github.com##.timeline-comment-wrapper:if(a[href*="/ads/"]):if-not(a[href*="/ads/preferences"])`

###### uBO dev 1.17.7+ recommend syntax:
`github.com##.timeline-comment-wrapper:has(a[href*="/ads/"]):not(:has(a[href*="/ads/preferences"]))`
