### ISSUE TITLE
clasicotas.org [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4684]
URL(s) where the issue occurs

`http://www.clasicotas.org/posts/hd720p/5533/Mentes-Poderosas-720p-Lat-Cast-Ing-5-1-2018-.html`

Describe the issue

Pop-up

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 71 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.17.4

Settings

Default

**Comment by lain566** [comment]
@okiehsch The website is broken, register button does not work, and comments are not shown.
This filter.
`clasicotas.org##+js(noeval.js)`

`http://www.clasicotas.org/`
<details>

![2eb28930-1738-4398-85bb-f686b72940e3](https://user-images.githubusercontent.com/27441315/53122102-0e024480-3556-11e9-90e7-5faa5c48a4b9.png)

</details>

-----------------------------------

`http://www.clasicotas.org/posts/dvdfull/1183/Harry-Potter-7-Las-Reliquias-de-La-Muerte-Parte-I-2010.html`
<details>

![0cd4df71-8e3e-4bf4-8477-6b5154a7ed13](https://user-images.githubusercontent.com/27441315/53122197-5588d080-3556-11e9-8d48-c056dd375c8b.png)

</details>

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://www.clasicotas.org/posts/dvdfull/6146/Vuelven-los-Garc-a-1947-Latino-Dvd5.html`


![2019-10-14_01h59_43](https://user-images.githubusercontent.com/36675858/66730259-e171a480-ee26-11e9-9fd2-2d6024aa6c8d.png)
![2019-10-14_02h01_16](https://user-images.githubusercontent.com/36675858/66730265-e6365880-ee26-11e9-9dad-0c3d90c9e353.png)
![2019-10-14_02h01_46](https://user-images.githubusercontent.com/36675858/66730266-ea627600-ee26-11e9-98e9-a06953ca90f7.png)
