### ISSUE TITLE
Twitter Redesign Promoted Tweets

### ISSUE THREAD

**Issue by RibShark** [uBlockOrigin/uAssets#4687]
### URL(s) where the issue occurs

`https://twitter.com`

### Describe the issue

If a user has been offered and opted into the redesign for Twitter, Promoted Tweets (and Promoted Followers etc...) will not be blocked. Additionally, the "Requests Blocked" counter will continually increase, going into the thousands very quickly.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1957489/51442978-c54b3780-1cda-11e9-8c02-4137393e505e.png)

### Versions

- Browser/version: Firefox 64.0.2
- uBlock Origin version: 1.17.4

### Settings

- I installed Nano Defender alongside uBlock as described [here](https://jspenguin2017.github.io/uBlockProtector/), but the issue still occurs on a fresh uBlock install.

### Notes

The redesign is very similar to mobile.twitter.com, but applying that filter to twitter.com leaves a blank gap where the promoted tweet was: 
![image](https://user-images.githubusercontent.com/1957489/51443026-5fab7b00-1cdb-11e9-9963-1d29693cced6.png)

**Comment by mapx-** [comment]
tested this 1 and work for me
`twitter.com##[data-testid="tweet"]:has-text(/Promoted|Gesponsert/)`

**Comment by Werner9** [comment]
Please add chinese '推荐'

**Comment by mapx-** [comment]
Could you test now for chinese ?

**Comment by Werner9** [comment]
Tested for 2 days and I still can see the ads

**Comment by mapx-** [comment]
What cosmetic filters do you see in the logger ?

**Comment by Werner9** [comment]
I did and I searched the word '推荐' in the ublock to make sure its updated.

What cosmetic filters do you see in the logger ? <- not sure what do you mean

**Comment by mapx-** [comment]
open the logger, refresh the page, search for `##` 

cosmetic filters:
```
twitter.com##:xpath(//span[(text()='Promoted' or text()='Gesponsert' or text()='Реклама' or text()='Promocionado' or text()='Sponsorisé' or text()='Uitgelicht') or text()='推荐')]/../../../../..)
twitter.com##[data-testid="trend"]:has-text(/推荐|Promoted|Gesponsert|Реклама|Promocionado|Sponsorisé|Uitgelicht/):xpath(..)
```

**Comment by Werner9** [comment]
if i input ## in the filter, nothing left

**Comment by mapx-** [comment]
Well, could be in China there is a different page code.
Right click on page (when you get promoted stuff), "save as.." the page (give it a readable name) => zip together page (html) + folder => upload the zip on some free server and put the link here.

If you don't want to make public the saved stuff just tell me.

**Comment by Werner9** [comment]
http://www.mediafire.com/file/gei1uicmyf5pze6/t.zip/file

**Comment by mapx-** [comment]
as I said => when you save the page give it a readable name, I get errors with that weird name, try again please

**Comment by Werner9** [comment]
Ha sorry about that I will do it again.

**Comment by Werner9** [comment]
http://www.mediafire.com/file/n4q737nkzd6dxbd/t.zip/file

**Comment by mapx-** [comment]
unfortunately, something is wrong, I get only this almost empty page:
![image](https://user-images.githubusercontent.com/10303732/66605771-fba24d00-ebb0-11e9-8a4d-e9e681f91838.png)

**Comment by Werner9** [comment]
The page says 'Sorry, this page doesn't exist'

Weird it can be read by chrome locally. What can I do to help this situation?

**Comment by mapx-** [comment]
it's very weird, I cannot save a normal page of twitter in chrome or firefox (tried as complete page or html only)

I can save only in the old internet explorer (not edge) and only as html only modality (otherwise the pages are broken, not readable)

**Comment by Werner9** [comment]
Actually this works:

```
twitter.com##[data-testid="tweet"]:has-text(/Promoted|Gesponsert|Реклама|推荐/)
twitter.com##[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама|推荐/)
```

got from reddit https://www.reddit.com/r/uBlockOrigin/comments/aku0uo/cant_get_it_to_block_twitter_ads_promoted_tweets/efdr29r?utm_source=share&utm_medium=web2x
