### ISSUE TITLE
acfun.to  pre video ads

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#4689]
`http://acfun.to/10281/`

![ad1](https://user-images.githubusercontent.com/45059308/51455362-21b66180-1d84-11e9-8ab6-f3cbe7d9036b.jpg)

**Comment by Jap2-0** [comment]
I only get 404s, is the link still working for you?

**Comment by discusssth** [comment]
@Jap2-0   still working , now

**Comment by Jap2-0** [comment]
I'm still getting a 404 in the box where you have a video, so it might be geolocked.

**Comment by discusssth** [comment]
@Jap2-0   ..it seems  geolock in China

**Comment by LiCybora** [comment]
Add these:
```
acfun.to##+js(nano-setTimeout-booster.js)
acfun.to##+js(alert-buster.js)
```
First one bypass timer, second one abort anti-adblock dialog

**Comment by discusssth** [comment]
@LiCybora  thank you very much, it works perfect!!!
