### ISSUE TITLE
false positive - data.*.info

### ISSUE THREAD

**Issue by mibe** [uBlockOrigin/uAssets#469]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://data.wetter.info/wetterapp/wetterAppController.php?mapName=xxlradar-de&layers=radar&enableStandalone=iframe&enableHighlighting=false&enableCityClick=false&enableSelector=false&autoplay=true&enableShowTimestamp=true`

### Describe the issue

The above URL is falsly blocked by the `||data.*.info^$document` rule.

### Versions

- Browser/version: FF 52.2.0 (32 bit)
- uBlock Origin version: 1.13.0

**Comment by SMed79** [comment]
Instead of the whitelisting rule you can exclude `data.wetter.info`

`||data.*.info^$document,popunder,popup,domain=~data.wetter.info`

**Comment by okiehsch** [comment]
I know, but gorhill used `@@||data.example.info^$document` in a [similar case](https://github.com/uBlockOrigin/uAssets/commit/3a6b2f8535a80a1c5b5833c524ddc94212664f26#diff-597a9408879bda0da942803b82285184), so I decided to be consistent.

**Comment by SMed79** [comment]
Ok. Thank you.
