### ISSUE TITLE
Treat Wikia/FANDOM Fan Feed as an annoyance?

### ISSUE THREAD

**Issue by gakada** [uBlockOrigin/uAssets#4692]
### URL(s) where the issue occurs

[Fan Feeds](https://community.wikia.com/wiki/Help:Fan_Feed) can be found on most pages on most FANDOM communities, as stated on that pages (for example, [1](https://fategrandorder.fandom.com/wiki/Fate/Grand_Order_Wikia), [2](https://kancolle.fandom.com/wiki/Kancolle_Wiki)).

### Describe the issue

A big footer section with unrelated or meaningless links/images/videos is added to every page.

### Screenshot(s)

https://vignette.wikia.nocookie.net/central/images/e/e8/Fan_Feed.jpg/revision/latest?cb=20171228174827

![u](https://user-images.githubusercontent.com/13043588/51493225-02591c00-1df8-11e9-98f7-be65701e6362.png)

### Notes

Currently blocking with

```
fandom.com,wikia.com###mixed-content-footer
```

**Comment by okiehsch** [comment]
`uBO-annoyances` is for issues that can't be fixed in the "normal" annoyances lists because extended syntax is required, for example `:style` or `script:inject` filters.

**Comment by gakada** [comment]
@okiehsch this is different from https://github.com/uBlockOrigin/uAssets/issues/4256? Was thinking `fandom.com###mixed-content-footer` is similar to `fandom.com##.featured-video__wrapper`. If yes, is there a place where I can open this issue? Maybe another filter list supported by uBO.

**Comment by okiehsch** [comment]
`Fanboy’s Annoyance List` or `Adguard AdGuard Annoyances filter` are stock filters in uBO, so you can open an issue there.
https://github.com/AdguardTeam/AdguardFilters
https://github.com/ryanbr/fanboy-adblock

**Comment by krystian3w** [comment]
Read this:

https://www.reddit.com/r/uBlockOrigin/comments/b4ylcg/how_do_i_block_wikiafandom_videos/

So maybe we need use this in uBO Annoyance.
