### ISSUE TITLE
lpe.pw

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4693]
### URL(s) where the issue occurs

`[http://short.pe/ZTDUg]`

### Describe the issue

[Fake push notification that forces you to press allow. Also redirects after solving captcha and clicking continue. And maybe popups + there is mention of anti-adblock though this didn't trigger for me. Also site has malicious third party scripts running.]

### Versions

- Browser/version: [Firefox mobile v63]
- uBlock Origin version: [1.17.4]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
@mapx-

Another site to block or at least the script. 

`||letaikay.net^$script`

**Comment by mapx-** [comment]
added `||letaikay.net^`

**Comment by mapx-** [comment]
so, you get redirects in android ?

**Comment by dumbusernameidk** [comment]
seems I don't even need to click the continue button just clicking around it forces redirects? Can you reproduce?

**Comment by mapx-** [comment]
it seems to be a race condition, I personally cannot reproduce the redirection

**Comment by dumbusernameidk** [comment]
Yep that stopped the forced redirects.
