### ISSUE TITLE
movierulzfree.mx

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4698]
### URL(s) where the issue occurs

`https://movierulzfree.mx/watch/fraud-saiyyan-2019-hindi/dvdscr-5463`

### Describe the issue
popup ads
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.17.7

### Settings

-  uBO's default settings

### Notes
||mixturehopeful.com^$important worthy addition present on many sites

**Comment by ghajini** [comment]
Site changed to `movierulzfree.ms`
Popup ads

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/102590480-f0ca3d00-4110-11eb-8da5-51f850a82fb8.png)

**Comment by ghajini** [comment]
Sorry its typo
`https://ww1.movierulzfree.is/` browse movies get ads

**Comment by ghajini** [comment]
Another variants of movierulz

`https://www2.5movierulzfree.me/bigg-boss-2020-telugu-season-4-day-100/full-movie-watch-online-free.html`
`https://newmovierulz.org/dvd/4647/unpaused-full-movie-watch-online/`

**Comment by ghajini** [comment]
popup ads & sometimes propeller crap

`https://newmovierulz.org/dvd/4903/wild-world-full-movie-watch-online/`
`https://movierulzlink.org/watch-wild-world-2021-online-free-full-movie-4903/`

**Comment by ghajini** [comment]
i see propeller crap requests when clicking play as reported above

**Comment by ghajini** [comment]
on refresh or clicking next player crap is back
https://user-images.githubusercontent.com/20338483/105370041-2939cb00-5c29-11eb-97df-7459a022d034.png
https://user-images.githubusercontent.com/20338483/105370507-a8c79a00-5c29-11eb-926d-4d677aabdb5f.png

**Comment by mapx-** [comment]
same here, test

`movierulzlink.*##+js(aopr, String.fromCharCode)`

**Comment by ghajini** [comment]
yes,work
