### ISSUE TITLE
uBlock Privacy breaks Primagames.com

### ISSUE THREAD

**Issue by liracobopu** [uBlockOrigin/uAssets#47]
### URL(s) where the issue occurs

`https://www.primagames.com/shop`

### Describe the issue

uBlock Privacy breaks the ability to click on the guides for purchase.

### Versions

- Browser/version: Google Chrome 50.0.2661.102
- uBlock Origin version: 1.72

### Notes

Unselecting uBlock Privacy allows Primagames site to work properly.
Adding the following rule fixes the problem:
`@@||google-analytics.com/analytics.js$script,domain=primagames.com`

**Comment by gorhill** [comment]
Can't reproduce with default settings: I clicked on any of the items at `https://www.primagames.com/shop` and I could navigate fine to the corresponding page.

**Comment by liracobopu** [comment]
I cleared cache and updated filters. Still broken for me. The only way to work is to disable UBO Privacy Filter, or add the filter rule `@@||google-analytics.com/analytics.js$script,domain=primagames.com`

Even on the guide purchase pages, the "Buy now"/"Unlock" buttons do not work until I disable the UBO Privacy Filter or add the filter rule.

**Comment by IDKwhattoputhere** [comment]
I can click on the guides without problem in Chrome and Firefox. Only when clicking the `Buy now` button I get a strict warning message from `Peter Lowe’s Ad server list` about `||esellerate.net^`.

**Comment by gorhill** [comment]
- Paste `https://www.primagames.com/shop` in URL address bar.
    - Page loads fine.
- Click thumbnail for _"Dark Souls III eGuide"_.
    - Page `https://www.primagames.com/games/dark-souls-3/products/dark-souls-iii-eguide` loads fine.
- Click _"Buy Now"_ button.
    - Web page `https://secure.esellerate.net/secure/prefill.aspx?_cartitem0.quantity=1&cmd=buy&_cartitem0.skurefnum=SKU07498527628&page=MultiPageCart.htm&_eseller.esellerid=STR6994361948` loads (destination page is strict-blocked by uBO).
- Dismiss temporarily strict blocking for that page.
    - Web page `chrome-extension://pbffolnficoggnnamkphaffidiafpeaf/document-blocked.html?details=eyJ1cmwiOiJodHRwczovL3N0b3JlMy5lc2VsbGVyYXRlLm5ldC9zdG9yZS9jaGVja291dC9wLmFzcHg/cHJlZmlsbD1GMTJGQzQ3Qi00NEM0LTQzQ0YtOTQ0Ny1FQjY3NThDODI1MTAmcz1TVFI2OTk0MzYxOTQ4JmNtZD1idXkiLCJobiI6InN0b3JlMy5lc2VsbGVyYXRlLm5ldCIsImRuIjoiZXNlbGxlcmF0ZS5uZXQiLCJmYyI6IjBcdTAwMGIuXHUwMDBiZXNlbGxlcmF0ZS5uZXQiLCJmcyI6Inx8ZXNlbGxlcmF0ZS5uZXReIn0=` loads (destination page is strict-blocked by uBO).
- Dismiss temporarily strict blocking for that page.
    - Web page `https://store3.esellerate.net/store/checkout/CustomLayout.aspx?s=STR6994361948&pc=&page=MultiPageCart.htm` loads.

**Comment by gorhill** [comment]
You will have to find out how I and other can reproduce.

**Comment by liracobopu** [comment]
These are my steps.
1. Disable all filters except uBlock Filters, Privacy, and Unbreak.
2. Purge Cache & Update
3. Go to `https://www.primagames.com/shop`
4. Attempt to click any thumbnail/text of guides. **Result: Nothing Loading**
5. Go to `https://www.primagames.com/games/splatoon/products/splatoon-eguide`
6. Attempt to click "Buy now". **Result: Nothing Loading**

Workaround:
1. Add ``@@||google-analytics.com/analytics.js$script,domain=primagames.com` to My filters.
2. Enable My filters (This is the only rule I have)
3. Go to `https://www.primagames.com/shop`
4. Attempt to click any thumbnail/text of guides. **Result: Next page loads**
5. Go to `https://www.primagames.com/games/splatoon/products/splatoon-eguide`
6. Attempt to click "Buy now". **Result: Next page loads**


Under uBlock Settings, only "Hide placeholders of blocked elements", "Show the number of blocked requests on the icon", "Disable pre-fetching", and "Disable hyperlink auditing/beacon" are checked.

These steps are all reproducible under Chrome for Windows and OS X, and Firefox for Android on my devices.

**Comment by gorhill** [comment]
> 1. Disable all filters except uBlock Filters, Privacy, and Unbreak

I can reproduce if only these filter lists are selected. That was an important missing piece of info.

EasyPrivacy's `/googleanalytics.js` is required to unbreak the page in such case.

*However*, uBO's filters are meant to be used as complement of the default 3rd-party filter lists, I can't provide any guarantee when used on their own. So, just enable _EasyPrivacy_ to unbreak the site.

**Comment by liracobopu** [comment]
> However, uBO's filters are meant to be used as complement of the default 3rd-party filter lists, I can't provide any guarantee when used on their own.

Thanks @gorhill. I basically had to fall back to your [very easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-very-easy-mode) as EasyPrivacy broke a lot of sites at the time. Your very easy mode wiki page does say to use uBlock filters though, so perhaps a clarification on the use of uBlock filters with this mode is needed.

**Comment by IDKwhattoputhere** [comment]
I'd say it's expected that a site may break if not using default settings since breakage with other settings than default is much less likely to be found because less people use that configuration.
If a filter list breaks a site you should always report to the maintainers of that list btw.

**Comment by gorhill** [comment]
> Your very easy mode wiki page does say to use uBlock filters though

Yes, it says:
- _uBlock filters‎_

It does not say:
-  _uBlock filters – Badware risks_
- _uBlock filters – Privacy_
- _uBlock filters – Unbreak‎_
