### ISSUE TITLE
xclusivejams.xyz

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#470]
Hi,

**Versions**

Chrome 58 / uBo 1.13.2

**Settings**

Default settings

**URL**

`https://www.xclusivejams.xyz/`

**Describe the issue**

- popunder + redirection

**Filters**

`||xclusivejams.xyz^$popunder`

or

```
/pop.redirect.$popup
?id_publisher=$popup
xclusivejams.xyz##script:inject(popads.net.js)
```

**Source**

https://forums.lanik.us/viewtopic.php?f=62&t=36906

**Comment by okiehsch** [comment]
Does
````
xclusivejams.xyz##script:inject(abort-on-property-write.js, Fingerprint2)
xclusivejams.xyz##script:inject(abort-on-property-write.js, _pop)
````
work for you?
By the way, the filters you propose at `https://forums.lanik.us/viewtopic.php?f=62&t=36906` should work for "enbob", if he uses a default setting.

**Comment by SMed79** [comment]
> work for you?

Yes, work.
