### ISSUE TITLE
prad.de [Ads circumvention]

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#4701]
### URL(s) where the issue occurs

`https://www.prad.de/`
`https://www.prad.de/amazon-blitzangebote/`

### Describe the issue

Banner ads top center and to the right.

### Versions

- Browser/version: Chrome Stable 71.0.3578.98 (64-bit)
- uBlock Origin version: 1.17.4

### Settings

- All default + EasyList DE

**Comment by okiehsch** [comment]
Try after updating your `uBO-filter` list.

**Comment by Hrxn** [comment]
😂

Well, forced an update of EasyList DE beforehand, because I assumed that would be the list responsible.

But updating uBO's own filter list seems to work, yes. Thanks. Closing now.

**Comment by Hrxn** [comment]
New ad banners on `https://www.prad.de`

**Comment by mapx-** [comment]
could you test
`prad.de##+js(set-constant.js, String.prototype.slice, noopFunc)`

**Comment by Hrxn** [comment]
Well, banner on the right side seems to be gone, but the main menu bar (white horizontal bar) at the top seems to be broken now?

**Comment by mapx-** [comment]
The odd thing is ... the filter is already in ublock filters, did you update your lists ?

**Comment by mapx-** [comment]
and the menu seems ok on my side

**Comment by mapx-** [comment]
hmm, I see, the menu is indeed broken

**Comment by mapx-** [comment]
try this 1 instead
`prad.de##+js(abort-on-property-read.js, document.cookie)`

**Comment by Hrxn** [comment]
I've added
```
prad.de##+js(abort-on-property-read.js, document.cookie)
prad.de#@#+js(set-constant.js, String.prototype.slice, noopFunc)
```
to my filters, and this seems to work, yes.
There is still the unused space on the right (instead of the banner), but this is a minor cosmetic issue only.

**Comment by gwarser** [comment]
`prad.de##+js(abort-on-property-read.js, document.cookie)` breaks "AUSWAHLKRITERIEN" in Chrome on https://www.prad.de/test-kaufberatung/produktsuche/monitor-suche-datenbank/
