### ISSUE TITLE
exrapideech.info antiadblock

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4703]
### URL(s) where the issue occurs

`http://www.exrapidleech.info/index.html`

### Describe the issue
***Antiadblock***
1.
after you go to site
`http://www.exrapidleech.info/index.html`

 enter this link e.g
`https://openload.co/f/2eF-8Yz2aV4`
And
2. Click transload
3.verify captcha
4.in next page click public rapidleech
5.next page again enter ***if required*** 
`https://openload.co/f/2eF-8Yz2aV4`
 link and click transload
6.next page will be of classic antiadblock
### Screenshot(s)
![screenshot 106](https://user-images.githubusercontent.com/20338483/51588917-6f110b00-1f0b-11e9-86c8-cc0f2914bc93.png)

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.17.7

### Settings

- uBO's default settings

### Notes
repro steps `https://streamable.com/wvj8y`

old thread `https://github.com/uBlockOrigin/uAssets/issues/183` outdated....

**Comment by okiehsch** [comment]
Why is the old issue "oudated"? 
I can't get it to work even if I disable `uBO`.
`4.in next page click public rapidleech`
The site simply reloads on my end, nothing else happens.

**Comment by okiehsch** [comment]
You misunderstand me, after I verify the captcha  - with uBO **disabled** - if I click `public rapidleech` the site simply reloads no matter how often I click `public rapidleech`.
If I **don't** disable uBO and click `public rapidleech` I get the anti adblock message after entering the link for a second time.

**Comment by okiehsch** [comment]
Well, maybe my location is blocked, I can't get the download to work on my end.

I would also recommend to not try to use this page unless one knows what he/she is doing.

**Comment by ghajini** [comment]
If using adguard browser extension I don't get antiadblock,just checked

**Comment by ghajini** [comment]
works with ublock origin+ubo extra+ nano defender
![screenshot 108](https://user-images.githubusercontent.com/20338483/52139435-288f7f00-2676-11e9-9cfc-e84998c12746.png)

doesn't work with ubo alone

**Comment by krystian3w** [comment]
Maybe no used Opera to reproduce?

**Comment by ghajini** [comment]
closed  silently, why so?
STR given very briefly
@mapx- @okiehsch @gorhill

**Comment by mapx-** [comment]
The site is considered a malicious one. If is working for you using `nano defender`, just stick with that configuration.

**Comment by ghajini** [comment]
you can fix atleast antiadblock part.....

**Comment by gorhill** [comment]
Browsers block that site, no point for volunteers to sink their precious free time for that site.

**Comment by uBlock-user** [comment]
@ghajini 

Here's your solution --

https://github.com/jspenguin2017/uBlockProtector/blob/master/src/content/rules-specific.js#L1835-L1844

https://github.com/jspenguin2017/uBlockProtector/blob/master/src/content/rules-common.js#L247-L257

convert those rules into filters and you're done.

**Comment by ghajini** [comment]
@ublock-user would you provide ubo filters for that, I don't want extra memory usage of nano defender for specific site .....iam solely ubo+ubo extra user
