### ISSUE TITLE
finanzen.net

### ISSUE THREAD

**Issue by drunkenclam** [uBlockOrigin/uAssets#4705]
### URL(s) where the issue occurs

finanzen.net

### Describe the issue

static ads since today when adblocker detected.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/10271314/51611070-9b825280-1f1e-11e9-99fc-ba32e5908064.png)

### Versions

- Browser/version: current Chrome
- uBlock Origin version: 1.17.4

### Settings

default

**Comment by mapx-** [comment]
test these filters
```
finanzen.*#@#+js(abort-current-inline-script.js, Math.floor, uabp)
finanzen.*##+js(abort-current-inline-script.js, Math.floor, atob)
```

**Comment by drunkenclam** [comment]
Works! Thank you!

**Comment by drunkenclam** [comment]
Damn, stops working a few hours later:

![image](https://user-images.githubusercontent.com/10271314/51670675-71389f80-1fc7-11e9-82ee-7015b6609813.png)

**Comment by okiehsch** [comment]
@drunkenclam should work again if you update your `uBO-filters` list, it does on my end.
