### ISSUE TITLE
welt.de

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#4706]
### URL(s) where the issue occurs

`https://www.welt.de/debatte/kommentare/article183830806/Hoechstes-deutsches-Gericht-Merkels-Mann-fuer-Karlsruhe-ist-der-richtige.html`

### Describe the issue

Ads appear at top center and right scrolling when you scroll. Also background when you visit any other than the homepage of this site. Please note that it takes up to 5 seconds after site load before ads appear. Started to happen since less than 5 hours after creating this report.

### Screenshot(s)

https://imgur.com/a/EEm1exs

### Versions

- Browser/version: FF 64.0.2
- uBlock Origin version: 1.17.4

### Settings

- Assigned to German lists (EasyList Germany)

### Notes

Has been fixed a while ago but they changed something and now ads are shown again. In reference to (cannot re open the issue): https://github.com/uBlockOrigin/uAssets/issues/4116

**Comment by mapx-** [comment]
force updating your lists, test again, it was fixed yesterday

**Comment by kirchwitz** [comment]
With freshly updated filter lists (right now) the ads are still displayed. Like in the past, it affects not only welt.de but a large number of german web-sites. They all seem to use AdDefend.

**Comment by mapx-** [comment]
Check your logger and see if this filter is triggered
`welt.de##^script:has-text(.createShadowRoot)`

**Comment by okiehsch** [comment]
This has been fixed with https://github.com/uBlockOrigin/uAssets/commit/dc45a44e85fec9d3757855e6f9a81fc1ec1d7a12
`welt.de##^script:has-text(.createShadowRoot)` for Firefox.
`welt.de##+js(setInterval-defuser.js, text/css, 10)` for Chrome.

The fix still works on my end with both browsers and Windows or Linux.

**Comment by mapx-** [comment]
@okiehsch  could be we are served different code ? (for me your filters still work)

see also https://www.reddit.com/r/uBlockOrigin/comments/aj0d9f/%C2%B5block_not_working_anymore_for_certain_pages/eerzfu1/

**Comment by okiehsch** [comment]
That user never tried adding
`##^script:has-text(.createShadowRoot)`
to his filter list as far as I can see, only updating did not work, for whatever reason.

I can see numerous german forums where the addefend fix is confirmed working, after updating the filter list.

**Comment by okiehsch** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/aj0d9f/%C2%B5block_not_working_anymore_for_certain_pages/eesx4b2/

As I expected the filter works but the update failed for some reason.
