### ISSUE TITLE
[Anti-Adblock] clk.ink

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#4707]
URL(s) where the issue occurs

`https://clk.ink/usVcZHL`

Describe the issue

Anti-Adblock

Versions

Firefox x64 v64
uBlock Origin v1.17.4

Settings

default settings

**Comment by ghajini** [comment]
`https://clk.ink/XL6JN`
malware popups at final page when clicked anywhere in page

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://clk.ink/uksF1F`

**Comment by ghajini** [comment]
`https://clk.ink/lngvsDy`
3rd party increased after captcha completion at final download page
