### ISSUE TITLE
merriam-webster.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4708]
### URL(s) where the issue occurs

`https://www.merriam-webster.com/dictionary/Janus-faced`

### Describe the issue/Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/51633149-ef8d3700-1f1e-11e9-857d-c8363debf55e.png)

It also breaks comments
```
Comments on Janus-faced
What made you want to look up Janus-faced? Please tell us where you read or heard it (including the quote, if possible).
```
### Notes

`@@|https://$third-party,xmlhttprequest,domain=merriam-webster.com`

**Comment by terrorist96** [comment]
Thanks, but the Facebook comments are still broken. (I had edited my original post, you may have missed it).

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e8f0f96e13a84ec0e83a38dc5b3bb9357fcba308
